### ISSUE TITLE
Sign In With Google screen is confusing to users without accounts

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#10009]
We use Sign in With Google to give everyone in our organization access to Metabase.  I keep getting requests from new employees asking for access, and have to explain that they already have access if they just click "Sign in with Google".

This screen would be a lot clearer if there was text indicating that the Sign in With Google button can be used to create an account.

Alternatively, if there was a setting in admin to change the "Sign in to Metabase" title or add a paragraph underneath it describing how to sign up that would help too.

![image](https://user-images.githubusercontent.com/82608/58044220-15ed6880-7af4-11e9-92f3-f646d03629a2.png)

**Comment by benjR** [comment]
Or just hide the default login/pass when you have a Sign in with Google enabled, like Slack does:
![image](https://user-images.githubusercontent.com/1074675/58174203-9ac7b600-7c9d-11e9-90bb-f08fe6faf347.png)

Sorry, in french.

**Comment by bcherry** [comment]
👍 thanks @kdoh!

**Comment by dbirlem-fincompare** [comment]
Signing in with Google does not work

**Comment by flamber** [comment]
@dbirlem-fincompare 
Please provide more information.
Are you using 0.33.1?
Do you see any errors in the Metabase log or browser console?
