### ISSUE TITLE
Missing Index props for the ParameterWidget in Parameters.jsx at line 166

### ISSUE THREAD

**Issue by alextanghk** [metabase/metabase#10001]
Hi, I am just playing around and found out two big issues with I am working on the filter in dashboard.

I found that if you try to reorder the filter, other the filter box will hidden and cannot rearrange.

So I look into the sources code and found out the index props was missing in the file (see title).

Also when I try to rename the filter. The filter will be delete if I do the following step:
1. Ctrl + a to select all.
2. Press delete / backspace

I understand that the name should not be empty but I also thinks this is a issues to any type of users.

I added a alert for that when user try to clear the name but I don't thinks that is a correct way to handle this case. Do anybody have other idea?

**Comment by flamber** [comment]
Confirmed on 0.32.8 with Firefox and Chromium.
