### ISSUE TITLE
Datetime column is recognized as str not date in saved question

### ISSUE THREAD

**Issue by codequokka** [metabase/metabase#10008]
### Environment
- Your browser and the version: None
- Your operating system: OS X 10.14.4
- Your databases: sqlite3 3.24.0
- Metabase version: 0.32.8
- Metabase hosting environment: Mac app
- Metabase internal database: H2

### *Repeatable steps to reproduce the issue*
- Create a simple table has datetime column in sqlite

- In making custom question from sqlite3 table directly, date column is recognized as date properly(This behavior is what I want to let metabase do)
![スクリーンショット 2019-05-20 10 39 16](https://user-images.githubusercontent.com/50156460/57992241-0ec35c00-7aee-11e9-8295-33681cd1100f.png)

- But in making custom question from save question, date column is recognized as str not date
![スクリーンショット 2019-05-20 10 41 55](https://user-images.githubusercontent.com/50156460/57992342-81343c00-7aee-11e9-9c4c-9ae5585c5026.png)

Is there any way that date column is recognized as date properly from saved question?

**Comment by flamber** [comment]
Hi @codequokka 
I cannot reproduce your issue on 0.32.8 with a [sample database](http://www.sqlitetutorial.net/sqlite-sample-database/), which returns version 3.25.2 (when running `select sqlite_version();`), so maybe it's something specific to the earlier version or column types?
How come the `History` table does not have `Epoch Time`, but the "Saved Question" does?

**Comment by codequokka** [comment]
Hi @flamber 
Thank you for replying

>How come the History table does not have Epoch Time, but the "Saved Question" does?

Epoch time is generated in my saved question.
To simplify the issue, I will show another example.

- Make a saved question with following SQL(This query is same as original table)
```
SELECT 
  *
FROM
  history;
```

- Then make a custom question from a saved question above, date column is recognized as str not date
![スクリーンショット 2019-05-20 12 08 40](https://user-images.githubusercontent.com/50156460/57995204-dcb8f680-7afb-11e9-9ca0-6aa5adee5a6d.png)

Date column from sqlite3 table and from saved query has exact same values.
But the latter is recognized as str not date.
Do you know how metabase recognize date column type?

**Comment by flamber** [comment]
Ahhh okay, so you're creating a Native Query (SQL), which converts the `date(time)` to a string, so you cannot use that question as a "Saved Question" via Custom.
Okay, I can reproduce that issue on 0.32.8 - I don't know a workaround for that.

**Comment by codequokka** [comment]
> you're creating a Native Query (SQL), which converts the date(time) to a string, so you cannot use that question as a "Saved Question" via Custom.

I understand why date column is recognized as str rather than date.
I look for another way.
Thank you.
