### ISSUE TITLE
Folder organization for tables

### ISSUE THREAD

**Issue by Alexsandr0x** [metabase/metabase#10005]
I guess this could be a great feature:

At least for me organizing a lot of tables plugged into Metabase without an option to group them in a folder is starting to get difficult.

![Screenshot from 2019-05-17 14-40-51](https://user-images.githubusercontent.com/8901883/57946070-d59ea800-78b1-11e9-8251-a1eabfbef622.png)

For example: in schemas "mock 1" and "mock 2" I have a large number of tables, would be great if I could have a second level of folders to organize as I wish.

sorry if this feature idea was already posted, I didn't found anything like that.

**Comment by flamber** [comment]
Hi @Alexsandr0x It sounds like a duplicate of #9518. If yes, then please close this and upvote the other.

**Comment by Alexsandr0x** [comment]
@flamber it is the same idea, thanks to inform me
