### ISSUE TITLE
Now that the drivers are split off into separate jar files, I do not see any SHA hashes posted for those (for example crate-driver)

### ISSUE THREAD

**Issue by hushfrog2** [metabase/metabase#10015]
Now that the drivers are split off into separate jar files, I do not see any SHA hashes posted for those (for example crate-driver)

could you please post hashes for these driver jar files?

https://github.com/metabase/crate-driver/releases

**Comment by flamber** [comment]
Fixed https://github.com/metabase/crate-driver/issues/2
