### ISSUE TITLE
Filters shouldn't be hidden when using a time range and an additional filter

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1001]
Steps to reproduce: use a time range filter in qb, then add a second filter. Expected behavior: you should be able to see the full text of the second filter and the X button to remove it. Actual behavior: the second filter's text gets truncated, and the X button is hidden.

![screen shot 2015-09-17 at 9 26 24 am](https://cloud.githubusercontent.com/assets/2223916/9939374/c6403db8-5d1e-11e5-8dc2-ec2b59e53b27.png)

![screen shot 2015-09-17 at 9 27 47 am](https://cloud.githubusercontent.com/assets/2223916/9939378/ca3bad1c-5d1e-11e5-96a5-0ce94b70ae58.png)

**Comment by agilliland** [comment]
@kdoh @tlrobinson I believe the original intention was that the filter section would horizontally scale as new filters are added until reaching the edge of the screen, possibly pushing the QB bar into 2 rows.  However, that would be the maximum length of the filter section and thus, it would always be possible for a user to put in enough filters for this issue to occur.

is that still accurate?  this is labeled as a bug, so i'm trying to clarify what the intended behavior is that's not being met.

**Comment by kdoh** [comment]
@agilliland Yeah the intention was that the filter section would grow as needed to accommodate the total number of filters added and if it pushed the aggregation section to a 2nd line like on smaller screens mobile then it would have a visible scroll bar. Right now it seems to have a max width and overflows without a scroll bar which is incorrect.
