### ISSUE TITLE
Pin Map - Draw Box to Filter, issues when Lat and long are in linked table

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#10017]
- Your browser and the version: Firefox 66.0.4 (64-bit)
- Your operating system: Windows 7
- Your databases: MS SQL
- Metabase version: 0.32.7
- Metabase hosting environment: jar file on Windows
- Metabase internal database: Postgres

*Repeatable steps to reproduce the issue*
- Metabase new custom query Sample Dataset > Orders
- Row limit set to 100
- Table settings, add Latitude and Longitude from the linked People table (I'll be logging another ticket about that, it's a bit wonky for me Edit: #9144 already exists to cover this)
- Change visualization to Map
- Pin Map is presented with the expected pins
- click "Draw box to filter" button and select area containing pins
- Get error reported "there was a problem ..." 
- Show error details gives `Column "PUBLIC.PEOPLE.LATITUDE" not found`

I think there's an issue with the generated query, I've attached my log output

[metabase_log_map_filter_box.txt](https://github.com/metabase/metabase/files/3204855/metabase_log_map_filter_box.txt)

I also get a similar issue when using my data from SQL Server but it presents differently by just showing no results found. Again the generated query isn't correct i.e. I can't run it in SQL Management studio. The fields in the where clause from the joined tables are referenced incorrectly using the `schema.table.field` scheme, not the joined table name i.e. `X__via__Y.field`.

This incorrect query generation could actually explain another issue I'm seeing where the map doesn't even display if any of the lat long fields are null (as some of mine are). I get an error "e is null". May be related but I can't see the query so it's hard to know.

I'm just starting down the maps path and it seems really good, but there are a few quirks around having the lat/long in a linked table, if I can figure out how to avoid them this will really drive Metabase acceptance in my org.

Thanks

**Comment by flamber** [comment]
I cannot reproduce this on 0.35.3. It was probably fixed since 0.33
