### ISSUE TITLE
Does Metabase support 100-200 simultaneous users? When I create 50 users and use the JMeter test (calling API/api/session), it returns“Too many attempts! You must wait 15 seconds before trying again.”

### ISSUE THREAD

**Issue by CrazyZhangsk** [metabase/metabase#10019]
Does Metabase support 100-200 simultaneous users? When I create 50 users and use the JMeter test (calling API/api/session), it returns“Too many attempts! You must wait 15 seconds before trying again.” What should I do to support 100-200 people using it at the same time?I've set the maximum number of threads for jetty to 450

**Comment by flamber** [comment]
Hi @CrazyZhangsk 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Which version of Metabase? Docker or JAR?
There's a difference between 50 users doing a login at the same time - and 50 users using Metabase.
If you expect that amount of load, then you might want to run multiple instances #2754
Related #8548

**Comment by salsakran** [comment]
you're hitting a rate limit (as per the error message - "Too many attempts! You must wait 15 seconds before trying again")

As @flamber said, this question is more appropriately asked on our forum.
