### ISSUE TITLE
Allow other protocols to be clickable with the url field type

### ISSUE THREAD

**Issue by taungerSve** [metabase/metabase#10028]
Can you make other url protocols than http/https clickable for the url field type?

We want to use a company internal protocol to jump from metabase to a local rich client, but it's the same issue with ftp:// and probably others.

**Comment by RMMSecurity** [comment]
Can I give this more than one thumbs up?

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
