### ISSUE TITLE
error getting autocompletion data

### ISSUE THREAD

**Issue by Gitii** [metabase/metabase#10032]
Hi,

I am using an fresh installation of metabase.
It looks promising, but the autocompletion of the native sql editor does work:
All keywords & attributes are suggested, the suggestions are not based on the current input:

The console log shows several identical errors:
"error getting autocompletion data"
& 
"GET http://10.35.50.58:8080/api/database/2/autocomplete_suggestions?prefix= 400 (Bad Request)"
(the response was: {"errors":{"prefix":"der Wert muss ein nicht-leerer String sein."}}) (translated: the string must not be empty)

I also tested 0.31.2 with the same results.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Chrome 74
- Win 10
- mariaDB 10
- v0.32.8
- docker
- H2

**Comment by flamber** [comment]
Hi @Gitii 
Are you accessing Metabase through this address `http://10.35.50.58:8080/` ?
If no, then it's probably because the "Site URL" isn't correct in the Admin Settings > Settings > General.

**Comment by Gitii** [comment]
Yes, I am accessing metabase though this address. The request returns the response that the prefix is empty - which it is.
Does metabase support attribute completion based on the table name? If not, this is not a bug but rather a missing feature.

**Comment by flamber** [comment]
I think I might be totally misunderstanding what you're trying to do or what the problem is.
Are you using the SQL editor in the Metabase interface, the autocomplete doesn't give any results?
Does it work in other browsers or in incognito-mode?
When I type `P`, then I get all keywords, functions, tables, columns, ... starting with that letter.
![image](https://user-images.githubusercontent.com/1447303/58276676-45e77680-7d55-11e9-954b-b75f4fda362c.png)

**Comment by Gitii** [comment]
![image](https://user-images.githubusercontent.com/4958574/58282961-70621f80-7da7-11e9-933b-03d97d1e8dd7.png)
and pressing strg+space raises the error which I described above.

I expected the editor to suggest the table attributes at this point, but instead it shows all everything and tries so get a completion from the server for an empty string.
![image](https://user-images.githubusercontent.com/4958574/58283456-9f2cc580-7da8-11e9-94ff-4579ab7d9209.png)

I executed
`/api/database/1/autocomplete_suggestions?prefix=Orders.c` to see if there is a reasonable result, but the response is an empty array.

Am I right that metabase does not support context aware suggestions?

I that's the case, than I misinterpreted the logged error as a bug and this issue can be closed.
Sorry for the inconvenience.

**Comment by flamber** [comment]
I cannot reproduce the error, so I would think it might have something to do with your browser.
Your last image shows `localhost:3000` - is that a different test you're running?

Yes, the autocomplete is not context aware, besides which database you've selected.
Metabase uses [ACE Editor](https://github.com/ajaxorg/ace), so it's limited to what is provided from that, but there's a request for a smarter autocomplete in issue #3885 - go and upvote by clicking :+1:

**Comment by Gitii** [comment]
Thanks for your clarification. I took the Screenshots on a different machine. But I do not think that the error is critical. I just misinterpreted it. Try hitting strg+space after an dot. That should trigger it.

**Comment by flamber** [comment]
What's `strg` ?

**Comment by Gitii** [comment]
Oh, sorry. My fault. I mean control. I have an non english keyboard.

**Comment by flamber** [comment]
I cannot reproduce this anymore. Think it was fixed around 42, but might have been 43 - there has been several autocomplete fixes.
