### ISSUE TITLE
Feature request: Add sponsor button

### ISSUE THREAD

**Issue by coderberry** [metabase/metabase#10034]
I would love to pay you on a monthly donation. Please add the new sponsor button so I can do this.

**Comment by flamber** [comment]
Hi @coderberry 
Where is that button supposed to be?
There's a several enterprise options available, like Paid Support: https://metabase.com/support/

**Comment by coderberry** [comment]
@flamber The button appears directly on GitHub. It will allow the contribution of funds directly to your team. It's not meant to be a support/service payment, merely a "we love your project, here's a small amount each month to keep it going".

See this article: https://help.github.com/en/articles/about-github-sponsors
