### ISSUE TITLE
Driver: Memsql

### ISSUE THREAD

**Issue by pstoll** [metabase/metabase#10045]
### Database support

We use MemSQL as a fast datastore for analytic workloads. It is speaks the MySql wire protocol but it handles dates sufficiently different that the MySql driver does not work well out of the box. As an example, Group by Timestamp fields work for days but not for hour or minutes on datetime or timestamp fields.

I've done a rough first cut of a MemSQL driver (in style of the modules, not the built in mysql or postgres) as a working prototype to show that it works. I basically started from the current MySql driver and started adjusting the conversion functions. It seems to work, i.e. it now slices datetime and timestamps correctly for minute, hour, week, etc where using the normal MySql driver does not.

Are you open to a MemSQL driver? And if so, would you want a starting point or would you want to start from scratch? 

memsql_version                      | 6.7.8

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by nicosuave** [comment]
A recent Metabase update also causes compatibility issues when a table has a json field, due to new unfurling/exploding of json keys (might only be new for the MySql driver?)

**Comment by nicosuave** [comment]
@pstoll do you happen to have a copy of your modified driver you could share? I gave it shot ~1.5 years ago but didn't quite nail it

**Comment by pstoll** [comment]
@nicosuave sorry, no longer have access to it; changed jobs since.

**Comment by nicosuave** [comment]
FYI for any onlookers, the mysql driver seems to have received enough compatibility updates to be useable

**Comment by paoliniluis** [comment]
@nicosuave does this mean that we can close this feature request?

**Comment by nicosuave** [comment]
@paoliniluis Yes IMO

**Comment by paoliniluis** [comment]
I will proceed to close this
