### ISSUE TITLE
Proposal - select fields from question for pulse (to exclude sensitive information)

### ISSUE THREAD

**Issue by darylteo** [metabase/metabase#10048]
### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

-------

Hi guys , thanks very much for such a great project.

This is slightly different to https://github.com/metabase/metabase/issues/7918

Instead of customising a question to fit the pulse, I'd like the pulse to only send information that we select to display in the pulse. 

We are currently sending a pulse to alert us of new user registrations and to trigger our human-based workflows. This notably has some fields that are naturally sensitive (names etc.) that we'd rather not have stored on an uncontrolled email server. However, we'd like the information to be displayed when we go through the links provided via email. But we're receiving frustration that our humans are required to proceed to another Question to view the required information.

There is no way to workaround this currently afaik.

My proposal is to allow for the fields from each question to be selected at the pulse creation step.

Alternatively, I'm waiting for this PR https://github.com/metabase/metabase/pull/8068 to be merged. This will let me insert a link to the full "Question" in the column at least, so that our humans can click those from the email instead.

Kind Regards,
Daryl

**Comment by flamber** [comment]
Closing, since Subscriptions support Textbox and there's Click Behavior now too. Related #16922
