### ISSUE TITLE
Error when downloading excel data

### ISSUE THREAD

**Issue by jianbowan** [metabase/metabase#10046]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

 Browser . Chrome 73.0.3683.86
 Operating system: Windows 10
 Databases: Spark
 Metabase version: (v 0.32.8)
 Metabase hosting environment:  Linux
 Metabase internal database: Postgres

-------
I used spark sql to query 10 data. When I clicked to download the result in excel format, the page was displayed in the buffer, and then the following error pops up: "org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe ( Write failed)"

`May 25 11:01:08 ERROR metabase.driver.sql-jdbc.execute :: nil
May 25 11:01:08 WARN org.apache.thrift.transport.TIOStreamTransport :: Error closing output stream.
java.net.SocketException: Socket closed
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:110)
at org.apache.thrift.transport.TSocket.close(TSocket.java:196)
at org.apache.thrift.transport.TSaslTransport.close(TSaslTransport.java:402)
at org.apache.thrift.transport.TSaslClientTransport.close(TSaslClientTransport.java:37)
at org.apache.hive.jdbc.HiveConnection.close(HiveConnection.java:727)
at metabase.driver.FixedHiveConnection.close(Unknown Source)
at com.mchange.v2.c3p0.impl.NewPooledConnection.close(NewPooledConnection.java:642)
at com.mchange.v2.c3p0.impl.NewPooledConnection.closeMaybeCheckedOut(NewPooledConnection.java:255)
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.destroyResource(C3P0PooledConnectionPool.java:622)
at com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask.run(BasicResourcePool.java:1076)
at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
May 25 11:01:08 WARN metabase.query-processor.middleware.process-userland-query :: Query failure {:status :failed,
:class java.sql.SQLException,
:error "org.apache.thrift.transport.TTransportException",
:stacktrace
("org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:262)"
"org.apache.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:392)"
"org.apache.hive.jdbc.HivePreparedStatement.executeQuery(HivePreparedStatement.java:109)"
"com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:379)"
"clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
"clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
"clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1081)"
"clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
"clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
"clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
"--> driver.hive_like$run_query.invokeStatic(hive_like.clj:124)"
"driver.hive_like$run_query.invoke(hive_like.clj:114)"
"driver.hive_like$run_query_without_timezone.invokeStatic(hive_like.clj:131)"
"driver.hive_like$run_query_without_timezone.invoke(hive_like.clj:128)"
"driver.sparksql$eval551$fn__553$fn__555.invoke(sparksql.clj:129)"
"driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:216)"
"driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:210)"
"driver.sparksql$eval551$fn__553.invoke(sparksql.clj:126)"
"query_processor$fn__40384$execute_query__40389$fn__40390.invoke(query_processor.clj:61)"
"query_processor$fn__40384$execute_query__40389.invoke(query_processor.clj:55)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__34664.invoke(mbql_to_native.clj:36)"
"query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__32695.invoke(annotate.clj:368)"
"query_processor.middleware.annotate$add_column_info$fn__32600.invoke(annotate.clj:303)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__34144.invoke(cumulative_aggregations.clj:57)"
"query_processor.middleware.limit$limit$fn__34637.invoke(limit.clj:19)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__40249.invoke(results_metadata.clj:86)"
"query_processor.middleware.format_rows$format_rows$fn__34625.invoke(format_rows.clj:26)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__31752.invoke(add_dimension_projections.clj:234)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__32146.invoke(add_row_count_and_status.clj:16)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__34386.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__37215.invoke(resolve_driver.clj:15)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__33550$fn__33551.invoke(bind_effective_timezone.clj:9)"
"util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
"util.date$call_with_effective_timezone.invoke(date.clj:77)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__33550.invoke(bind_effective_timezone.clj:8)"
"query_processor.middleware.store$initialize_store$fn__40274$fn__40275.invoke(store.clj:11)"
"query_processor.store$do_with_new_store.invokeStatic(store.clj:35)"
"query_processor.store$do_with_new_store.invoke(store.clj:31)"
"query_processor.middleware.store$initialize_store$fn__40274.invoke(store.clj:10)"
"query_processor.middleware.async$async__GT_sync$fn__33146.invoke(async.clj:19)"
"query_processor.middleware.async_wait$runnable$fn__33277.invoke(async_wait.clj:71)"),
:query
{:type "native",
:native
{:query
"select os,event_time,u_user,event_key,uuid,count(id) as cnt \r\nfrom test.table \r\nwhere day between 20190514 and 20190524\r\nand uuid<>''\r\nand u_user<>''\r\ngroup by os,event_time,u_user,event_key,uuid\r\nhaving cnt>=2\r\ndistribute by cnt \r\nsort by cnt desc\r\n--cluster by \r\nlimit 10",
:template-tags {}},
:parameters [],
:async? true,
:middleware {:add-default-userland-constraints? true, :userland-query? true},
:info
{:executed-by 1,
:context :ad-hoc,
:card-id nil,
:nested? false,
:query-hash [-78, 64, -119, 93, 35, -101, -78, 38, 21, 86, -42, 126, -105, 39, -30, 13, 2, 89, -18, 109, 56, 78, 2, -60, 59, 107, -10, 90, 18, 84, 53, -106]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}}}`

**Comment by flamber** [comment]
There has been many connection handling improvements in later version.
Please comment "Diagnostic Info" and new error log, if this is still a problem in latest release 0.35.4
