### ISSUE TITLE
Personal collection restricted access bug

### ISSUE THREAD

**Issue by Crusader4Christ** [metabase/metabase#10049]
Your browser and the version: Chromium 73.0.3683.75 (Official Build) Built on Ubuntu 16.04 (64-bit)
Your operating system: Ubuntu 16.04 (64-bit)
Your databases: MySQL
Metabase version: v0.30.4
Metabase hosting environment: Docker
Metabase internal database: MySQL

*Repeatable steps to reproduce the issue*
Create restricted-everything group 
Add user to it
Create group of questions with filters for this user in his PC

Result: user hasn't access to tables, so he don't have access to filters, so on the question page he see only "Sorry, you don’t have permission to see that"
Expected: Every user have full access to their PCs

**Comment by mazameli** [comment]
This should also be fixed in the latest version of Metabase, just like #10050. Please let us know if you're still seeing this problem. Thanks.
