### ISSUE TITLE
Map widget sends unsecure requests for image tiles

### ISSUE THREAD

**Issue by nkconnor** [metabase/metabase#10040]
The maps request tiles from open street map over http and are then redirected to a secure resource. The HTTPS URI format should be the default

**Comment by RMMSecurity** [comment]
Oh good! I've always just made one of the things on my checklist to manually do this on each instance I stand up.

**Comment by RMMSecurity** [comment]
Oh good! I've always just made one of the things on my checklist to manually do this on each instance I stand up.
