### ISSUE TITLE
Permission to view data in saved questions without updating them (SQL)

### ISSUE THREAD

**Issue by TheRusskiy** [metabase/metabase#10056]
Howdy!

Is there a way to allow certain user group to read some questions, without ability to edit them / ask new ones?

Essentially doing permissions in the query itself.
The use case is for a user with email dude@coca-cola.com
allow to see a question:
`SELECT * FROM orders WHERE email ILIKE '%@coca-cola.com'`
Here we want this user to be able to see all coca cola orders, but not other others.
So if we add a permission to view orders, he will be able to ask new questions and see all orders, not just the ones we want.
If he was restricted to viewing saved questions regardless of their content this problem would be solved.

Thank you for Metabase, making our life a lot easier.

**Comment by TicklesTheBrain** [comment]
This sounds a lot like the data sandboxing feature of Metabase Enterprise:
https://metabase.com/enterprise/

**Comment by TheRusskiy** [comment]
@TicklesTheBrain oh... If it's an enterprise feature then I guess we can close this issue then.
