### ISSUE TITLE
Filtered by value is not rendered on previously saved questions

### ISSUE THREAD

**Issue by evacorvil** [metabase/metabase#10052]
- Your browser and the version: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- Your operating system: Ubuntu 16
- Your database: MySQL
- Metabase version: v0.32.7
- Metabase hosting environment: Ubuntu 16
- Metabase internal database: Postgres

Create a question including a value in the "Filtered by" field, save the question, reload the question, the "Filtered by" field is not rendered only an "x" is displayed.

Although the data is correctly filtered, it's not possible to modify the filter or see what filter was used.

![metabase-bug](https://user-images.githubusercontent.com/49711836/58483846-e4f6de80-8158-11e9-95e7-4bb10b1c2700.png)

**Comment by flamber** [comment]
Hi @evacorvil 
It looks like a duplicate of #8971. If you think so too, then please close this issue and upvote the other.

**Comment by evacorvil** [comment]
Duplicate of #8971
