### ISSUE TITLE
Line Chart Y axis display zero incorrectly

### ISSUE THREAD

**Issue by alextanghk** [metabase/metabase#10062]
I have a line chart which render by a sql question that show -0.00000000000000036 (too many zero) instead of just 0.

did anybody have the same issues?

this happened when the chart has just one data and the data is a negative number.

**Comment by flamber** [comment]
Hi @alextanghk 
Since you haven't given any details or ways to reproduce, I've tried to with 0.32.8 without success:
![Screenshot_00001](https://user-images.githubusercontent.com/1447303/58607511-253f8500-825d-11e9-82e0-850a1b29b252.png)
```
SELECT -0.00000000000000036 AS number, '2017' AS xaxis
UNION ALL
SELECT -1 AS number, '2018' AS xaxis
UNION ALL
SELECT 2 AS number, '2019' AS xaxis
```

**Comment by paulrosenzweig** [comment]
I think this is a dupe of #9986
