### ISSUE TITLE
No widget appearing in sql query

### ISSUE THREAD

**Issue by catabram** [metabase/metabase#10066]
Hi!

I can not add filter widget to one specific table in metabase - I've already tried to make it as view, matview, local table, I've updated metaиase to the new version - nothing works. The filter widget does not appear. Is there any chance to fix this?

![image](https://user-images.githubusercontent.com/15132002/58642835-c33b5a00-8306-11e9-9f62-e140d9d9f5e3.png)

Metabase 0.32.4/0.32.8
Postgres
Chrome 74.0.3729.131
Windows 10

Data in the table:
A3ECS
AMEX
ARCA
ASC
ASCG
ASX
ATH
AUDC
BATS
BIST
BM
CBOE
CBOT
CFD
CME
COMEX
DNCM
DSE
EONE
EUR
EUREX
EURONEXT
FOREX
FORTS
FWB
GK
H_KEX
HTF
H.TMX
ICE
IDEM
IPO
JSE
LGML
LIFFE
LME
LSE
LSEAIM
LSEIOB
MICEX
MIL
MSE
NASDAQ
NEX
NOMX
NYMEX
NYSE
OEF
OMXC
OMXH
OSE
OTCBB
OTCMKTS
PD.NYSE
PI.NYSE
PL
SAFT
SB
SET
SGX
SIX
SOMX
SSE
TMX
TOCOM
TSE
TSF
UKIM
UN.TMX
U.TMX
VSE
WSE
XETRA

**Comment by mazameli** [comment]
If you go into the Admin Panel's Data Model section, does the `exchange` column have a metadata type set? (E.g. `Category`) From that same data model page, you can also try clicking on the gear in the top right of the page and then click `re-scan this table` to see if that helps things.

It would also be helpful if you could provide any server log errors or JavaScript console errors that might appear when you select the `field filter` option from the SQL editor screen.

**Comment by catabram** [comment]
Thanks a lot, that helped!
