### ISSUE TITLE
Snowflake Schema change - removing a field

### ISSUE THREAD

**Issue by mattarderne** [metabase/metabase#10064]
I'm not sure if this is a bug or a feature request, I couldn't find a discussion on this.

I'm using [dbt](https://www.getdbt.com/) to manage my semantic layer of my Snowflake instance. 

Essentially  dbt rebuilds using `CREATE OR REPLACE VIEW` to modify the schema when it runs. I've encountered a scenario where a column is removed from a view in Snowflake, and Metabase doesn't handle the missing column very well.

Running the Sync & Rescan doesn't always seem to fix the issue. I understand that this is because the question relies on a specific column existing, however I wanted to know if there is an elegant way to deal with these, as I foresee this happening frequently as I build out the semantic layer. I now have a situation where a few tables are no longer working, and I can't seem to get them working again.
 
In the below example, I demonstrate the issue, however I have other issues where I haven't managed to get it working again after "re-adding" the missing column.

1. Create table and view in Snowflake
```
CREATE OR REPLACE TABLE mytable (amount NUMBER);
INSERT INTO mytable VALUES(1);
CREATE OR REPLACE VIEW myview AS SELECT amount as col1 FROM mytable;
```

2. Create a new Metabase question based on `myview`
![image](https://user-images.githubusercontent.com/23472325/58634205-324e8980-82da-11e9-86e2-8b9ef9c6b5fd.png)

3. Modify the SQL to add a column, which as expected doesn't include the added `col2` when I refresh the question.
```
CREATE OR REPLACE VIEW myview AS SELECT amount as col1 , amount + 2 as col2 FROM mytable;
```
![image](https://user-images.githubusercontent.com/23472325/58634348-9c672e80-82da-11e9-8a79-500072d475b1.png)

4. Sync & Re-scan the source, now the new field is added to the question, this is good.
![image](https://user-images.githubusercontent.com/23472325/58634368-aab54a80-82da-11e9-870b-ae9d2fca9e0e.png)

5. Remove a column from myview and refresh the query, an error is thrown as the question can't find the column.
```
CREATE OR REPLACE VIEW myview AS SELECT amount + 2 as col2 FROM mytable;
```
```
There was a problem with your question
Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.
Show error details
Here's the full error message
SQL compilation error: error line 1 at position 7 invalid identifier 'DBT_DEV.SCHEMA1.MYVIEW.COL1'
```

6. If I rescan the Database, it seems to identify the missing field, and if only used in a table, it will re-add it, 

    6.1 however if I modify the fields for that table then I can't get the question to work again, ie by excluding a field, removing it from the backend and then readding it, as below where the field was hidden, re-adding it throws an error by Clicking `COL1 +` and then saving
![image](https://user-images.githubusercontent.com/23472325/58635505-9292fa80-82dd-11e9-9a77-ceeee467492c.png)

    6.2 Also, same issue with a visualisation that relies on the field then the question remains broken.

    6.3 Worth noting that a new question based on this same table has no issues

Note: In some cases step 6 doesn't solve the issue, on a big table I was not able to

**Comment by salsakran** [comment]
The root problem is the same as in #10371 closing in favor of that issue.
