### ISSUE TITLE
Connection to Oracle Database

### ISSUE THREAD

**Issue by PepijnV** [metabase/metabase#10075]
Hello,

This is my first issue on Github & Metabase, hope I am doing this right.

I am trying to add an oracle database to metabase.

So far I am doing the following:
1. Create docker while setting envoirment variable: docker run -d -p 3000:3000 --name metabase -e MB_PLUGINS_DIR=/app/plugins metabase/metabase
2. Check if envoirment table was set correctly: docker exec metabase env -> Succes
3. Create plugins folder: docker exec -it metabase mkdir /app/plugins
4. Copy Jar file from Oracle: docker cp ojdbc8.jar metabase:/app/plugins/ojdbc8.jar
5. Give full rights to jar file: docker exec -it metabase chmod 777 /app/plugins/ojdbc8.jar
6. Check if all is correct: docker exec -it metabase ls -lR /app

All seems to be fine, yet still no menu option to add the database type: Oracle.

Any idea what I am missing? Thanks in advance.

**Comment by camsaul** [comment]
@PepijnV these sorts of help questions are best asked on https://discourse.metabase.com 

What Metabase version are you using?

**Comment by salsakran** [comment]
@PepijnV the issue tracker is meant to be a place where work on the metabase application happens. If you believe you have found a bug, it's the right place to go, but for questions like this our user forum (discourse.metabase.com) is the right place to go.

Apologies but we can't offer individual support for these kinds of questions.

aka WhatCamSaid.

**Comment by flamber** [comment]
For reference: https://discourse.metabase.com/t/connection-to-oracle-database/6367
