### ISSUE TITLE
Bug. Pie graph shows 100% when other value is very little.

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#10070]
### Bug. Pie graph shows 100% (instead 99,93% for example) when other value is very little.

- Your browser and the version: Chrome 74.0
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.32.8
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Example:
![image](https://user-images.githubusercontent.com/33416503/58683035-472b2b80-8373-11e9-877e-d314b128e722.png)

Thanks for Metabase project!
-------

**Comment by flamber** [comment]
Hi @jlisyc 
I cannot reproduce your exact issue, but I can see there is some rounding issues going on.
A work-around seems to work if you set "Minimum number of decimal places" to `2`.

Very similar to #9914, but might also be related to #9174

**Comment by jlisyc** [comment]
thanks @flamber, but it does not work, because of it change also to % the value inside de pie. 
It should be ok to show the count (for example) inside the pie, and the % in the legend.
If you set "Minimum number of decimal places" to 2, then you have to multiply x100 to show % and it multiply also the value inside the pie.
![image](https://user-images.githubusercontent.com/33416503/58687100-fa4e5180-8380-11e9-83b4-7556be5c7622.png)

**Comment by flamber** [comment]
Okay, I actually think that another issue, since changing formatting shouldn't change percentage legend.
Reproducible H2 example:
```SQL
SELECT 'One' AS "cat", 48000 AS "num"
UNION ALL
SELECT 'Two' AS "cat", 7 AS "num"
```
