### ISSUE TITLE
Bug. Question with relative date filter fails with ORA-01839

### ISSUE THREAD

**Issue by sokolsaiti** [metabase/metabase#10072]
- Your browser and the version: Firefox 67.0
- Your operating system: Windows 10
- Your databases: Oracle Database 12c Enterprise Edition Release 12.1.0.2 - 64bit
- Metabase version:  0.32.4
- Metabase hosting environment: Windows Server 2012 R2
- Metabase internal database: H2

When we use Query Builder and then filter the results using a date column for previous 6 months the query will fail with the following Oracle specific error:

*java.sql.SQLDataException: ORA-01839: date not valid for month specified*

I believe this is caused with how Metabase generates Oracle queries, I checked the debug log and saw that in order to select data for the previous months Metabase uses the numtoyminterval() function and then applies it to the sysdate. 

So a query date filter is generated like this:
trunc((SYSDATE + numtoyminterval(-6, 'month')), 'month') , this would generate the date 31-NOV-2018 (since today's date is 31-MAY) which in fact doesn't exist. Maybe when doing month based filtering using the add_months() function would be safer?

Regards and thanks for the product!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by sokolsaiti** [comment]
Hello again,
it seems this bug does not have enough priority for the developers.

I just wanted to say that we hit it today as well, so the Query Builder is generating 30.02.2020 when we filter with Previous Month.

Regards,
Sokol

**Comment by Philippe-M** [comment]
Hello,

Without this fix Metabase is totally useless for us :(

But I don't really understand the problem because last week this same query was working fine.

**Comment by flamber** [comment]
@Philippe-M Post "Diagnostic Info" from Admin > Troubleshooting, and which ojdbc8.jar version you're using.

**Comment by Philippe-M** [comment]
@flamber 

```
[]({
  "browser-info": {
    "language": "fr-FR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_292-b10",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_292",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.292-b10",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.25.1.el7.x86_64",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.10-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.3",
      "date": "2021-05-27",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
})
```

I use well  ojdbc8.jar

**Comment by flamber** [comment]
@Philippe-M I know you're using ojdbc - otherwise Oracle wouldn't function. I'm asking for which version you're using.
https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html

**Comment by Philippe-M** [comment]
@flamber I am using version 12.2.0.1 because I am on an old Oracle 9 base and I don't know if a newer version of ojdbc will work fine with my version.

**Comment by flamber** [comment]
@Philippe-M Try 19.3 or newer: https://www.metabase.com/docs/latest/administration-guide/databases/oracle.html
Metabase cannot work for every version of every database forever. Oracle 9 was [EOL in 2007/2010](https://www.oracle.com/us/support/library/lifetime-support-technology-069183.pdf). If a newer ojdbc8.jar does not work, then it will not be supported, and you would have to create your own custom driver to support legacy databases.

**Comment by Philippe-M** [comment]
@flamber I've the same error with the 19.3 or 21.1 version.

I tested with the same filter but for a day and a week and in this case I have no error. But as soon as I chose this error for a month.

I have to use Oracle 9 again because of an old ERP which will evolve next year. But in the meantime we are looking for a BI solution.
