### ISSUE TITLE
Support SSO via Google Auth

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1008]
Allow admins to enable account signup + login via Google Authentication Accounts.

**Comment by shaneog** [comment]
+1

**Comment by pygeek** [comment]
+1

**Comment by mattdoran** [comment]
+1

**Comment by MrMauricioLeite** [comment]
+1

**Comment by salsakran** [comment]
I've been thinking a fair bit about this lately, and think we should couple it with #764

Goals: Allow an admin to just set up a box, send out an email and do no further work to allow others in the google domain use Metabase. The current model of explicitly adding each user, while reasonable to situations where a select subset of users in a company should be given access, doesn't match our common use case of a company wide place for dashboards/pulses.

Rough requirements:

* Admin should be able to set an auth setting allowing anyone with an account for the specific domain to login
* Admin should be able to allow login for pre-existing email accounts tied to a google account
* (Bonus points) Pulses should be able to add anyone with a domain account

**Comment by salsakran** [comment]
per an offline conversation w/ @snarfed  - 

It seems like we could use “Metabase” as the app, and sign in client side via https://developers.google.com/identity/sign-in/web/sign-in , pass the token to the backend and verify ala https://developers.google.com/identity/sign-in/web/backend-auth#verify-the-integrity-of-the-id-token . At least in theory, this would eliminate the need for an end user to do anything other than specify that users could log in via google auth + give an ending domain (or potentially other policy for creating an account the first time a google auth email is seen)

**Comment by salsakran** [comment]
@kdoh has a design for this, if anyone is feeling froggy and wants to help out ;)

**Comment by moumny** [comment]
Suggestion: make this modular so that we can add OAuth2 or other auth systems.

**Comment by salsakran** [comment]
@kdoh do we want to include this in the setup wizard?

**Comment by kdoh** [comment]
@salsakran I think at some point we'll want to let people know about that and email as part of the setup flow. For now though I'm inclined to keep the setup flow fairly streamlined to help people get in and try Metabase as quickly as possible. Things like the admin checklist or other forms of post setup onboarding might be a better fit for this kind of feature.

**Comment by kdoh** [comment]
#2818

**Comment by snarfed** [comment]
woo! i just set this up and it worked perfectly. thanks all!

next feature request is to be able to disable email login entirely, globally and/or per user. let me know if you want me to file a new issue for that.

thanks again!

**Comment by salsakran** [comment]
@snarfed yeah, open an issue for that =)

**Comment by nitikeshbhavsar** [comment]
@salsakran I have entered the Google Client ID under SSO in my metabase instance.
But sadly I am not able to enable SSO or Signup.

It shows a Message stating "Password: did not match stored password"

**Comment by gowtham-sai** [comment]
Is there a way to disable login through password? Only Oauth login ?

**Comment by drewB** [comment]
+1 on disabling login through password.  Kind of defeats the purpose of using google for MFA if you can still sign in with a simple username and password.

**Comment by camsaul** [comment]
@drewB we have an open issue for that, #3136
