### ISSUE TITLE
Data Model > Foreign Keys no longer alphabetical/sorted!

### ISSUE THREAD

**Issue by RMMSecurity** [metabase/metabase#10080]
- Your browser and the version: Chrome 74.0.3729.169
- Your operating system: Windows 10
- Your databases: MySQL
- Metabase version: master
- Metabase hosting environment: Windows Server (JAR)
- Metabase internal database: MySQL

This was from the master branch as of today. Possibly caused by #9957 ?

Go to Admin > Data Model 

Select a Table under any database. Change a field to Foreign key and click "Select a target"

![image](https://user-images.githubusercontent.com/802527/58813936-cc704380-85f2-11e9-9bcc-1ae7fe7ea35e.png)

Nothing is in alphabetic order anymore. I have thousands of entries and it's unusable.

![image](https://user-images.githubusercontent.com/802527/58813965-dbef8c80-85f2-11e9-8b3b-4e0c4ecc85b2.png)

![image](https://user-images.githubusercontent.com/802527/58814021-f6296a80-85f2-11e9-989c-6de426b22ca7.png)

**Comment by RMMSecurity** [comment]
Actually I just double checked this and it's still not sorting correctly. 

Built from master and under Data Model > Table > Change Type to FK then see the results are unsorted or at least not sorted to name/display_name.

**Comment by paulrosenzweig** [comment]
@RMMSecurity huh! Are the FKs in the Sample DB appearing in sorted order for you? I'm wondering if I just need better sample data. Also, do the unsorted keys appear with or without the schema name?

**Comment by RMMSecurity** [comment]
@paulrosenzweig 
![image](https://user-images.githubusercontent.com/802527/59568051-6bf5f300-9043-11e9-89e2-be269cffbc2e.png)
It happens on the Sample DB as well. See the ordering Products, Orders, People, Reviews for FKs. 

![image](https://user-images.githubusercontent.com/802527/59568110-30a7f400-9044-11e9-93eb-ffa11882d6b9.png)

No schema names, though I could set up a PrestoDB instance and see how that's sorted. I think that used to have the schema name with it.

**Comment by RMMSecurity** [comment]
@paulrosenzweig 
![image](https://user-images.githubusercontent.com/802527/59568125-6f3dae80-9044-11e9-93fe-9767ae06b225.png)

It happens on the Sample DB as well. See the ordering Products, Orders, People, Reviews for FKs. 

![image](https://user-images.githubusercontent.com/802527/59568110-30a7f400-9044-11e9-93eb-ffa11882d6b9.png)

No schema names, though I could set up a PrestoDB instance and see how that's sorted. I think that used to have the schema name with it.

**Comment by RMMSecurity** [comment]
Opps, turns out the script I wrote to sync the jar over to staging when finished actually broke. It was working right up until that patch so I didn't even think to check. 

Sorry about that! Looks like it's all working perfectly after all.
