### ISSUE TITLE
Cannot connect card filter, when starting with an empty dashboard

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10085]
1. Create new dashboard (or use an existing empty dashboard)
2. Add question to dashboard (I just used simple Orders table question)
3. Add a filter (I used Time All Options, since it exists in Orders)
4. *(should be able to select the card connection to filter)*

**Work-around**: Save the dashboard with at least 1 card and then edit the dashboard again, then you'll be able to connect filters.

![Screencast 2019-06-03 13 27 06](https://user-images.githubusercontent.com/1447303/58829408-f7639300-8604-11e9-9b71-2d530dfa6939.gif)

It's not an issue, if you click the "Add to dashboard" from a question.

Metabase 0.32.8 (test env on H2 and production on MariaDB) with Firefox 67 and Chromium 74.

I'm not sure when this was introduced, but I remember someone created reported something similar a few months back (cannot find it), but without steps to reproduce.
Might be related to #8627

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
