### ISSUE TITLE
Clean up the search UI/IX for the add-question-to-dashboard modal

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10095]
I think we got too cute with the current interaction in this modal that allows you to show/hide the search bar. I think we could do something simpler as sketched out below. (Also going to file a separate issue about how the search results don't give any indication of which collection a saved question is in.)

## Current default state:

![image](https://user-images.githubusercontent.com/2223916/58986573-8a7e0380-8792-11e9-9c2d-fd2d30eba71c.png)

## Current searching state:

![image](https://user-images.githubusercontent.com/2223916/58986452-425ee100-8792-11e9-8293-ceb3c581ea0e.png)

## Proposed new default state:

![add-to-dashboard-modal](https://user-images.githubusercontent.com/2223916/58986488-56a2de00-8792-11e9-9075-844ee0e626f0.png)

## Proposed search results state:

![add-to-dashboard-modal-search](https://user-images.githubusercontent.com/2223916/58986510-67535400-8792-11e9-9b60-f760ef05c6ba.png)

**Comment by flamber** [comment]
Version 0.40 introduced a new way of adding questions: https://www.metabase.com/blog/Metabase-0.40/index.html
