### ISSUE TITLE
Detail View Formatting

### ISSUE THREAD

**Issue by harrywynn** [metabase/metabase#10099]
- Your browser and the version: Chrome 74.0.3729.169
- Your operating system: macOS 10.13.6
- Your databases: SQL Server 2016
- Metabase version:  0.32.8
- Metabase hosting environment: CentOS 7
- Metabase internal database: MySQL 5.6.40

Originally discussed here: https://discourse.metabase.com/t/detail-view-formatting/6403

The detail view for a single record isn't applying the formatting specified on the data model for field values.  As an example, In the image below Effective Date should appear as “4/10/2019” and Estimated Weekly Revenue should appear as “$7,000”.

<img width="627" alt="detail_formatting" src="https://user-images.githubusercontent.com/103879/59037239-e30ada80-883e-11e9-9b3c-b350038d20cf.png">

<img width="384" alt="effective_date_formatting" src="https://user-images.githubusercontent.com/103879/59037311-046bc680-883f-11e9-8f4c-d9e4da97e4ef.png">

<img width="454" alt="revenue_formatting" src="https://user-images.githubusercontent.com/103879/59037335-0766b700-883f-11e9-8457-d088537dbe51.png">

**Comment by flamber** [comment]
Just for reference, it looks like formatting properties are not part of Detail View (aka Object Details)
https://github.com/metabase/metabase/blob/ff2141a4c2b5d72c64b160f4b65a7c3d95f7d02b/frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx#L110-L114
