### ISSUE TITLE
Pulses

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1010]
User Story: An admin should be able to set up a recurring report that sends out an email to subscribers.

Some things we've learned from the current version of the datahub emailed reports:

1. It should be possible to disable an email report
2. It should be possible to subscribe either users with an account on the Metabase instance to the report
3. It should be possible to subscribe an email address (for individuals or a distribution list) to a report
4. Reports should have a period, nightly, weekly, and perhaps other frequencies.
5. For nightlies, it is useful to be able to set the send time

Remaining issues:

- [x] Remove "View all" button from Slack pulses
- [x] Sparkline Y-axis spacing
- [x] Slack admin setup should link to the url for obtaining a token.
- [x]  Pulse list button spacing in safari

**Comment by agilliland** [comment]
Closing this now as this is feature complete.
