### ISSUE TITLE
Download data button doesn't reappear after saving question

### ISSUE THREAD

**Issue by bhmayer** [metabase/metabase#10101]
The "download full results" button on the custom query question page next to the row count disappears when you being editing the question. However, it does not reappear when you save the question and the user has to refresh the page to download the data. 

I think the button should reappear once you save the question? Definitely would improve my personal Metabase workflow.

**Comment by flamber** [comment]
Hi @bhmayer 
Looks like a duplicate of #4820 - or at least very related

**Comment by bhmayer** [comment]
Realized you just need to refresh the data and the download button reappears. Seems like a good feature to prevent the user from downloading data reflecting the pre-change query.
