### ISSUE TITLE
site-url validation is too strict

### ISSUE THREAD

**Issue by yannickcornaille** [metabase/metabase#10100]
This issue is related to the issue #9850 and to the PR #9873 

I recently updated Metabase to version 0.32.8 and validation of the url is problematic. I'm using Metabase on an internal corporate network and tld is not accepted. It seems that UrlValidator uses DomainValidator and a finished list like this (http://data.iana.org/TLD/tlds-alpha-by-domain.txt) to validate. And my internal top level domain is not in it.
It's a very good thing to have made the url validation of the site stricter but I think it is too strict now.

- Browser and the version: All
- Operating system: All
- Databases: MySQL and MongoDB
- Metabase version: 0.32.8
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*
    - Go to the administration page in the General tab.
    - Try to fill the site url field with an unsupported top level domain, in my case *.intraorange (https://metabase.intraorange)
    - The error "Assert failed: Invalid site URL: https://metabase.intraorange (u/url? s)" appears.

Can we make validation more permissive easily?

**Comment by flamber** [comment]
Hi @yannickcornaille 
It looks like it's being discussed in #4617 (scroll down to comments from this year) and has 0.33 as milestone.

**Comment by yannickcornaille** [comment]
Hi @flamber 
Indeed it's the same problem, thanks for referencing this issue.

**Comment by salsakran** [comment]
closing as a dupe
