### ISSUE TITLE
There was a problem displaying this chart - after upgrade to 32.8.

### ISSUE THREAD

**Issue by dgleba** [metabase/metabase#10119]
This seems to be a continuation of  issue #9784 - Dashboard charts fail at random after upgrade to 0.32.x

I upgraded from 25.x to 32.8. I have the issue like #9784 as well. I still have the 25.x instance running. 

My metabase v32.8 is a docker setup where I used a mysqldump from the 25.x db. 
First, I started 32.8 and let it create a blank mysql db. 
I then imported the 25.x db and then pointed v32.8 instance at that db.
It started OK, but I have the issue - There was a problem displaying this chart.
When I open the question from the dashboard, the question works. Just the dashboard doesn't show the questions randomly.

I could easily do the export/import on a totally fresh metabase and provide more information if that would be helpful. Let me know what more I can provide.

_Originally posted by @dgleba in https://github.com/metabase/metabase/issues/9784#issuecomment-500431773_

How to reproduce:  Open a dashboard. Charts randomly show the message.

Browser: Chrome Version 75.0.3770.80 (Official Build) (64-bit)  Windows 10 
OS: Win 10
DBs: mysql
Metabase version: 32.8
Metabase hosting environment: Linux ubuntu 16.04
Metabase internal database: mysql 5.7

**Comment by flamber** [comment]
Hi @dgleba 
What errors do you see in the Metabase log, when it doesn't show the chart?
I'm pretty sure you're either seeing #9989 or #10119

**Comment by flamber** [comment]
Closing, since this was likely fixed in 0.33/0.34. Please comment if you're still experiencing this.
