### ISSUE TITLE
"Edit Settings" button broken on map visualization

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#10118]
This button doesn't work:

![image](https://user-images.githubusercontent.com/691495/59198023-bf0e0880-8b60-11e9-942e-d856fc951244.png)

Example question to trigger the behavior:

![image](https://user-images.githubusercontent.com/691495/59198064-dbaa4080-8b60-11e9-87b7-ba1d5c8e75c1.png)

**Comment by flamber** [comment]
@paulrosenzweig I think you're seeing https://github.com/metabase/metabase/issues/9346#issuecomment-458985874 - do you get the TypeError in console?

**Comment by paulrosenzweig** [comment]
@flamber good call! This issue is a dupe. Just created a PR: https://github.com/metabase/metabase/pull/10120
