### ISSUE TITLE
Unable to Update MongoDB Database Config Without Re-Entering Password

### ISSUE THREAD

**Issue by stieg** [metabase/metabase#10114]
*Info*
* Browser: Firefox 67.0
* Metabase Version: 0.32.8

*Current Behavior*
* Navigate to `admin/databases/<DB_ID>` where DB_ID is a pre-configured MongoDB database
* Try and update a field such as `Additional Mongo connection string options` field
* Click `Save`.  You should get the following exception: `com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='<REDACTED>*, source='<REDACTED>', password=<hidden>, mechanismProperties={}}`
* Re-enter the password for the database and click `Save` again.  It will work this time.

*Expected Behavior*
* Should be able to save right off the bat if I don't update the password field.

**Comment by antony** [comment]
This is a duplicate of https://github.com/metabase/metabase/issues/10114

**Comment by flamber** [comment]
@antony Do you mean #6262?

**Comment by stieg** [comment]
Definitely a duplicate of https://github.com/metabase/metabase/issues/6262
