### ISSUE TITLE
how can i use date range filter when i write sql-parameters

### ISSUE THREAD

**Issue by kkxxr66573** [metabase/metabase#10128]
such as i want use
```sql
[[where "date" between {{begin_date}} and {{end_date}}]]
```

![截图](https://user-images.githubusercontent.com/13388843/59271493-85372200-8c86-11e9-92b2-ee8047390771.PNG)

**Comment by mazameli** [comment]
Hi, @kkxxr66573. Questions such as these are best asked on our [discussion forum](https://discourse.metabase.com).

The way you've done it should work; your users would just have to pick a start date and an end date.

You can also instead use a [field filter](https://metabase.com/docs/latest/users-guide/08-dashboard-filters.html) variable, which inserts a SQL snippet and which allows you to use our different date filter widgets. The syntax in your case would look like this:

`[[where {{date_variable}}]]`

And then in the variable side panel of your SQL question, you'd set the `date_variable` to be a field filter, and link it to your `date` column.

I hope that helps!
