### ISSUE TITLE
Need to implement paging for GET /api/database API endpoint (and others)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10134]
`GET /api/database` is probably the most important because with `?include_cards=true` it returns all the Cards that can be used as source queries which as we have seen may number in the tens of thousands in larger instances.

We should settle on a general paging pattern and work towards implementing that across the API; I think it would be moderately easy to do from a backend perspective, I would imaging there's some sort of endless-scroll component that already exists for React that we can leverage to implement it on the FE.

Thoughts @tlrobinson @paulrosenzweig ?

**Comment by tlrobinson** [comment]
I think it's likely we're going to remove the Saved Questions "database" from that endpoint entirely, since on large instances the majority of cards won't make sense as starting points for new questions. I'd like to see the ability to "promote" a saved question to appear as if it's a normal table (basically our old virtual tables concept)

As far as general paging patterns, we currently use `limit`/`offset` for task lists (in the admin troubleshooting tab) and audit log (in enterprise), and I added basic pagination support to our `EntityListLoader` component that uses that. But I'm open to alternatives.

**Comment by camsaul** [comment]
The certified "Right Way" to do paging would be to do something like `after=<some-property>` 

In SQL databases `OFFSET` still means the DB cursor still has to iterate over all the rows, e.g. `OFFSET=1000` means it has to iterate over those rows and discard them before getting the ones we want. For a lot of API endpoints where we return things in alphabetical order you would do something like `after=My%20Database` (if `My Database` were the last one returned by the previous call) which would let us leverage the index on the `name` Field.

That being said I don't want to let the perfect be the enemy of the good and we've managed to make it this long without implementing more paging because we're not dealing with totally insane numbers of objects so I think `limit`/`offset` will suffice for now. It's clear and easy to implement in a general way. We can always do high-performance, complicated paging in specific places we need it down the road. `limit`/`offset` paging will still be a huge perf win.

Thoughts? @salsakran @tlrobinson

**Comment by camsaul** [comment]
One other common pattern I'm sure you guys have seen is to have the API endpoint return either the URL for fetching the next page or the query parameters (such as `after`) so we could also consider doing that which would make it easier to switch from `offset` to `after` in the future if we were so inclined.

**Comment by paulrosenzweig** [comment]
Is there ever a time when we'd want to let users jump ahead pages? e.g. UI like this:

![image](https://user-images.githubusercontent.com/691495/59300779-03cb9980-8c5e-11e9-98dc-d2c39495fa63.png)

If not, an `after` param or `nextPageUrl` make sense to me.

**Comment by camsaul** [comment]
@paulrosenzweig yeah, that's a good point, `after` would limit us a bit there.

It think `offset` should be fine for now, for example skipping over 1000 results to return 1001-1100 is still a huge win over returning everything from 1-1100 all at once

**Comment by camsaul** [comment]
Duplicate of #5504
