### ISSUE TITLE
inner join problem

### ISSUE THREAD

**Issue by m-szczepanik** [metabase/metabase#10138]
Hey,
I have a problem with matching information from other tables to ID.
From the table "Reporting" I have to draw the appropriate data. Some of the data has an ID, so "for a normal user" is unreadable.

I need to replace the ID with information from other tables.

Does anyone have any tips? Most of the information you need is in the "Users" table
Name and surname - applicant - zgłaszający
First and surname - responsible - odpowiedzialny
![Zrzut ekranu 2019-06-12 o 02 50 33](https://user-images.githubusercontent.com/51707009/59316523-44a7ca80-8cbf-11e9-9695-89c53aed0e5f.png)

**Comment by salsakran** [comment]
@m-szczepanik This isn't a good place to ask questions about SQL.

It's a place where Metabase specific bug reports and new feature development take place. Our user discussion forum is a better place for these kinds of questions - discourse.metabase.com
