### ISSUE TITLE
iframe communication with another application

### ISSUE THREAD

**Issue by httpsOmkar** [metabase/metabase#10141]
If I embed the report into the application like react. I have no control over the iframe from that application. So with the help of postMessage, we can implement the secure communication between the application and the metabase.

Example: 
If I want to change any parameter in the metabase embed iframe I need to generate new URL for each time I change the variable. (I want variable from the application).

And when the user clicks on an item it should notify the application with the postMessage.

And one more thing the ability to add custom CSS in the report. Usually helpful for the dark theme and other stuff.

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by flamber** [comment]
Hi @httpsOmkar 
I haven't checked if this only works in Enterprise Edition, but `postMessage` is already implemented:
https://www.metabase.com/docs/latest/enterprise-guide/full-app-embedding.html#setting-things-up-in-your-web-app
Other reference: #7817

**Comment by httpsOmkar** [comment]
@flamber Thanks for the reply.
If I want to notify the application when the user clicks on any row of the table.
Example:
If the report contains a table on that table when the user clicks on any row then the application should get notified with postMessage.
I tried with the link like `javascript:window.parent.postMessage({ id: 'STUDENT_ID' })`. But it didn't work because maybe XSS protection.

**Comment by flamber** [comment]
@httpsOmkar 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It looks like only `frame` and `location` are implemented. If something is blocked because of XSS, then you should see a note in your browser console.

**Comment by httpsOmkar** [comment]
Thanks
