### ISSUE TITLE
Snowflake Connector Requires Deprecated Region Id

### ISSUE THREAD

**Issue by nigelainscoe** [metabase/metabase#10142]
**Expected behaviour:**
Account name is entered as described in the  [Account name details section here](https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters).
Login is successful

**Actual Behaviour:**
Account name is entered as described in the  [Account name details section here](https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters).
Login fails with the error "DEBUG metabase.middleware.log :: POST /api/database 400 2 s (0 DB calls) {:valid false, :dbname "net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver not able to connect to Snowflake. Error code: 390100, Message: Incorrect username or password was specified..""

**Problem:**
Region Id is now deprecated in Snowflake JDBC connections as per [the Snowflake documentation](https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters)

The Snowflake database connector dialog asks for a separate Region Id field. In order to successfully connect, account name and region Id need to be entered in the deprecated manner.

**Solution:**
At the very least the dialogue should allow successful connection when account name is entered as per the  [Account name details section here](https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters)
Better still the deprecated Region ID should be removed and users guided to use the Snowflake account name guidance.

**Note**
The [code in the driver](https://github.com/metabase/metabase/blob/master/modules/drivers/snowflake/src/metabase/driver/snowflake.clj) appears to try to solve it with this:

`  (let [host (if regionid
               (str account "." regionid)
               account)]
`

but using the driver dialog, it doesn't seem to work. 
Unfortunately my Clojure is not up to debugging it - although I wondered if the display-name: Region ID from the YAML file is getting used when nothing is entered in that field?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Hi @nigelainscoe what version of Metabase are you using

**Comment by flamber** [comment]
@camsaul 0.32.8 according to the forum: https://discourse.metabase.com/t/snowflake-authentication-failing/6436/3

**Comment by nigelainscoe** [comment]
Version 0.32.8 is correct.

**Comment by paulrosenzweig** [comment]
Another user just ran into this on 0.32.9.

**Comment by kutny** [comment]
Not working on 0.32.9

**Comment by kfranci2** [comment]
Is there a workaround for this issue?  I've tried using the region_id, excluding it, putting it in the account name, etc but can't get a successful connection.

**Comment by flamber** [comment]
@kfranci2 According to [this forum post](https://discourse.metabase.com/t/snowflake-authentication-failing/6436/5?u=flamber):
> Turns out it is the dialog uses a deprecated format. Region ID is now combined with account name for the JDBC connection. You have to enter account name and region Id separately in the Metabase dialog (you should be able to combine them).

**Comment by kfranci2** [comment]
Turns out I needed to uppercase the database and username attributes in order to connect.

**Comment by flamber** [comment]
@kfranci2 Okay, that's issue #9511.

**Comment by davehowell** [comment]
`us-west-2` is the default region for snowflake, so if that is what you use then you should leave the region field blank otherwise it doesn't connect. See the [account name examples by region](https://docs.snowflake.net/manuals/user-guide/intro-regions.html#specifying-region-information-in-your-account-hostname)

I also tested and found I had to uppercase these fields:

    - Database username
    - Warehouse
    - Database name
    - Role

**Comment by Rajesh-Balsuni** [comment]
I am also facing the same issue "net.snowflake.client.jdbc.SnowflakeSQLException: Incorrect username or password was specified."
my region is not `us-west-2`. tried doing uppercase but didn't work. 
Did anyone get any solution for this?

**Comment by joaoclemencio** [comment]
I've managed to connect to our Snowflake database using the following config

Account: the account prefix without the region i.e. if your account name is `xy12345.eu-west-1`, then this value should just be `xy12345`
Region ID: per the example above, this should just be `eu-west-1` or your region equivalent

Database username: our usernames are all in Uppercase, so this should be equivalent, but when using lowercase I was not able to access, so it's likely case-dependent

Database Warehouse, Name, Schema, Role: all in Uppercase; note that if Schema is set, no other schemas are available in Metabase; if schema is left empty, all schemas will be loaded

No additional options set for the JDBC connection; have not tested using SSH tunnel.

**Comment by stammi922** [comment]
In case anyone of you is still struggling with setting the right region. 
The thing that did the trick for me, was appending the cloud provider in the end of my region: `europe-west2.gcp`

Hope that info helps.

**Comment by kdesimone** [comment]
> In case anyone of you is still struggling with setting the right region.
> The thing that did the trick for me, was appending the cloud provider in the end of my region: `europe-west2.gcp`
> 
> Hope that info helps.

Champ.

**Comment by jeff303** [comment]
The "simple" fix here is just to put the `regionid` (prefixed with a dot, if present) as a suffix for `account`, then git rid of `regionid` entirely.  Unfortunately, this has some drawbacks.

1. Since `regionid` goes away from the UI, but is still in the app DB, how will people edit it?
2. If someone does the "right" thing by suffixing the `account` themselves, do we simply delete this key entirely?
3. How long do we need to support the weird mode of having a hidden `regionid` that is sometimes appended to the URL?

Open to suggestions on how best to balance usability with incurring tech debt and general hackiness.

**Comment by davehowell** [comment]
When you use the Python snowflake connector SDK, you do exactly that - the region is a suffix for the account name. There's potentially other suffixes too for people using direct connect. It's a quirk of Snowflake, not something that Metabase needs to fix. Lots of other tools face the same issue. Don't store the region if it's not used anywhere apart from sometimes being appended to the account name.
