### ISSUE TITLE
Monthly alerts

### ISSUE THREAD

**Issue by etiennecallies** [metabase/metabase#10155]
Hi,

We're using latest version 0.32.8, and we cannot set monthly alerts any more (only weekly, daily and hourly). However, we use this feature a lot, and we already have monthly alerts (aka pulses) set up when we were using previous versions of metabase. And these alerts seem to keep working.

Is it possible to make it available again? Or hack metabase database to set it up?

Thanks

**Comment by flamber** [comment]
Hi @etiennecallies 
Which version did you upgrade from? I don't recall ever seeing Monthly as an option for Alerts.
In #3846 there's several designs for making periods for Pulses/Alerts more customizable.

**Comment by etiennecallies** [comment]
Thanks for your answer.
I can't very accurate. It should be 0.30.x, I believe it was called Pulse (not Alerts) at this time in the UI.
Glad to see it'll come in future releases.

**Comment by flamber** [comment]
Okay, that's two different things - Alerts and Pulses.
https://metabase.com/docs/latest/users-guide/10-pulses.html
https://metabase.com/docs/latest/users-guide/15-alerts.html

"Monthly" is still available under Pulses, so if that "solves" your issue, then please close this :+1:

**Comment by etiennecallies** [comment]
You're damn right :man_facepalming:  Sorry and thanks !
