### ISSUE TITLE
Variables don't open with certain queries

### ISSUE THREAD

**Issue by paulinabarszcz** [metabase/metabase#10151]
I cannot set up a variable on this query 

select * from geolocation_records
where {{ip_address}}

internal-nabu_gateway_sanitised

Variables seem to work with other queries, e.g. using the users table etc.

**Comment by flamber** [comment]
Hi @paulinabarszcz 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
When using Filter Filters, the Field Type has to one of the [allowed types](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type).
Admin > Data Model > (database) > (table) > (column) :gear:

**Comment by salsakran** [comment]
what flamber said.
