### ISSUE TITLE
Proposal. Permissions. Control download permissions for embedding dashboards (allow , not allow). 

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#10153]
### Proposal. Permissions. Control download permissions for embedding dashboards (allow , not allow). 

![image](https://user-images.githubusercontent.com/33416503/59429686-9431e780-8de0-11e9-969f-a58d9bd44639.png)

Thanks for Metabase project!
-------

**Comment by jlisyc** [comment]
Related https://github.com/metabase/metabase/issues/9264

**Comment by flamber** [comment]
Looks like a duplicate of #6369
