### ISSUE TITLE
Graph image URL

### ISSUE THREAD

**Issue by joshhopkins** [metabase/metabase#10157]
Would be nice if table views could (optionally) render images for ordinary URLs. Perhaps even pull in the page titles.

**Comment by flamber** [comment]
Hi @joshhopkins 
That's already possible - since version 0.31 I think.
![image](https://user-images.githubusercontent.com/1447303/59454418-3ea10f00-8dcf-11e9-9b2c-0ce474537409.png)

**Comment by mazameli** [comment]
Closing as already fixed, but let me know if we're misunderstanding your request @joshhopkins.

**Comment by joshhopkins** [comment]
This is also great. But I'm actually referring to the `og:image` property described in the [Open Graph](http://ogp.me) protocol, rather than image recourses.

**Comment by tlrobinson** [comment]
I think fetching metadata from from URLs is outside the scope of Metabase, at least for now.

A possible solution is to have an ETL process that does that and adds columns to your database/data warehouse.

**Comment by joshhopkins** [comment]
Yeah, that's what we currently do. It's certainly a 'nice to have' request.

**Comment by joshhopkins** [comment]
Thinking a little more. The main advantage of this is that the fetched image could also be a link. Rather than having one column for the URL and another for the image.
