### ISSUE TITLE
Category drop-down filter jumps while searching 

### ISSUE THREAD

**Issue by joshhopkins** [metabase/metabase#10162]
- Your browser and the version: Safari Version 12.1.1 (14607.2.6.1.1)
- Your operating system: MacOS 10.14.5
- Your databases: Postgres
- Metabase version: v0.32.8
- Metabase hosting environment: Docker
- Metabase internal database: H2

*Repeatable steps to reproduce the issue*

1. Select a category filter (Drop down appears)
2. Make a free text search
3. Page jumps down in-line with filter

*Expected behaviour*

1. Page doesn't jump while searching

**Comment by mazameli** [comment]
Could you provide some screenshots or a GIF to show us what you're seeing specifically? Is this a SQL/native query filter, or a dashboard filter?

**Comment by joshhopkins** [comment]
![Drop-down jump](https://hoppie-files.s3-eu-central-1.amazonaws.com/Screen-Recording-2019-06-13-21-13-09/Screen-Recording-2019-06-13-21-13-09.gif)

**Comment by joshhopkins** [comment]
>Is this a SQL/native query filter, or a dashboard filter?

Dashboard filter. Appears to be an issue in Chrome too.

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.

**Comment by joshhopkins** [comment]
Great. Thanks for the quick fix!
