### ISSUE TITLE
Add Metabase to CapRover One-Click apps

### ISSUE THREAD

**Issue by mnlbox** [metabase/metabase#10182]
Hi guys,
[CapRover](https://caprover.com/) is an awesome tools to create self hosted PaaS. It now support many project as a One-Click apps. I suggest to add Metabase officially to this tools so we can setup Metabase easily with CapRover too.
This is related repository: https://github.com/caprover/one-click-apps

Thanks guys.

**Comment by laruche** [comment]
Great Idea ! 
you can use this template : 

```
{
    "captainVersion": "1",
    "documentation": "Taken from https://metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html",
    "dockerCompose": {
        "version": "2",
        "services": {
            "$$cap_appname-metabase": {
                "image": "metabase/metabase",
                "restart": "always",
                "environment": {
                    "MB_DB_TYPE": "postgres",
                    "MB_DB_CONNECTION_URI" : "$$cap_db_uri"                    
                }
            }
        },
        "volumes": {
            "db_data": {}
        }
    },
    "instructions": {
        "start": "Metabase sekelton",
        "end": "Metabase is ready"
    },
    "variables": [{
            "id": "$$cap_db_uri",
            "label": "Database URI",
            "defaultValue": "postgres://<username>:<password>@<host>:<port>/<dbname>?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory",
            "validRegex": "/.{1,}/"
        }
    ]

}
```

**Comment by mnlbox** [comment]
Thanks @laruche I test it and we can then make PR in https://github.com/caprover/one-click-apps then other guys also can find this simply :wink:

**Comment by laruche** [comment]
great idea 
I will

**Comment by tonxxd** [comment]
Hi, I cannot find metabase in 1-click apps, is it not available yet?
Thanks!

**Comment by flamber** [comment]
@tonxxd You should open an issue on https://github.com/caprover/one-click-apps/issues/new/choose

**Comment by tonxxd** [comment]
Ok thanks ;)
