### ISSUE TITLE
Bar-chart time series wrong labels

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#10183]
Hello, I have some sums aggregated by month.
When the X axis is set to "time series" the bar labels are wrong (see below - twice "march 2019"). 

However, the bar hover tooltips are correct. 

When I set the X axis to "ordinal" mode this issue disappears. 

**Charts affected**: bar, line, area (the ones with "time series" option).
**Metabase version**: 0.32.9 docker
**Browser**: latest Chrome
<img width="1433" alt="Snímek obrazovky 2019-06-15 v 13 26 12" src="https://user-images.githubusercontent.com/1764151/59551039-c031a200-8f73-11e9-8bcb-9e2b197a7187.png">

**Comment by flamber** [comment]
Hi @dfx413 
This looks like a duplicate of #5916, if you agree, then please close this issue.

**Comment by dfx413** [comment]
> Hi @dfx413
> This looks like a duplicate of #5916, if you agree, then please close this issue.

Looks like it. Thanks.
