### ISSUE TITLE
When there's only one x value with a timeseries scale, it only shows the year

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#10188]
This was split off of #10184:

When there's only one row, then it positions the graph to the left. Also, the x-axis tick shows "2000", when using Timeseries.

![Screencast 2019-06-15 20 01 29](https://user-images.githubusercontent.com/1447303/59558149-02290b00-8fa9-11e9-9c68-71431eaacb7e.gif)

_Originally posted by @flamber in https://github.com/metabase/metabase/issues/10184#issuecomment-502413138_

**Comment by flamber** [comment]
I cannot reproduce anymore on 0.35.4 - the misalignment is likely the same as #11216
```
SELECT CAST('2019-06-01' AS DATE) AS Date, 1340.31 AS Daily, 1340.31 AS Accu, 1020.00 AS Goal
```
![image](https://user-images.githubusercontent.com/1447303/83525911-f00be980-a4e5-11ea-8d2b-14457d78f525.png)
