### ISSUE TITLE
Server Side code is throwing error

### ISSUE THREAD

**Issue by crazilazi** [metabase/metabase#10187]
Metabase version : 0.32.9

While building server side code, i'm getting below warning :
![Screenshot from 2019-06-17 08-39-29](https://user-images.githubusercontent.com/24241036/59604930-84195100-90db-11e9-815e-5a1a2e6e12b1.png)

Once it is up, i'm getting below issue
![Screenshot from 2019-06-17 08-41-18](https://user-images.githubusercontent.com/24241036/59604993-b32fc280-90db-11e9-9e4d-e652e5983ea8.png)

**Comment by flamber** [comment]
Hi @crazilazi 
Are you building your own version of Metabase? Which branch/tag are you using?
Which warning are you referring to? There are many warnings, when building, but most of them can be ignored.
I guess you're seeing issue #9989 - you would find it if you searched for "No method in multimethod"
And please do not use images for console errors - it makes it impossible to search.

**Comment by camsaul** [comment]
Hi @crazilazi, it looks like you're running from source either via `lein ring server` or `lein run`.

If you do that you'll need to build the drivers yourself for everything to work properly.

Please run

```bash
./bin/build-drivers.sh
```

to build all the drivers and then running from source should work as expected. Alternatively, you can use our pre-built Docker image or JARs.

**Comment by crazilazi** [comment]
@flamber , sorry for the images, yes i'm working 'release-0.32.x' branch.
@camsaul , thank you for the quick solution. that worked.

Thank you both for quick and awesome support.
