### ISSUE TITLE
If I select the 1st day of a month, metabase considers results from the last day os previous month

### ISSUE THREAD

**Issue by izabelamcampos** [metabase/metabase#10195]
I'm trying to count the orders (distinct ids) in a timeframe, but when I select a month (any month), Metabase includes results from last day of the previous month.
i.e.: if i select to count all distinct ids from 1st to 17th june, it will include ids from may 31st.

Also happens when I select one specific day (any day), Metabase returns all results from the previous day.

I attached a screenshot from the raw data, showing the wrogn results.

- Your browser and the version: Safari 12.1.1, same result using Chrome
- Your operating system: macOS Mojave 10.14.5
- Your database: MongoDB
- Metabase version: v0.32.8
- Metabase hosting environment: Docker
- Metabase internal database: Snowflake

![Screen Shot 2019-06-17 at 17 22 24](https://user-images.githubusercontent.com/49628001/59634159-805dec80-9124-11e9-81cd-89d19668ebb4.png)

**Comment by flamber** [comment]
Hi @izabelamcampos 
It sounds like a timezone issue. Please have a look at this troubleshooting guide:
https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html

**Comment by salsakran** [comment]
Hello @izabelamcampos -

Can you share the timezone information laid out in the troubleshooting guide? That will help us understand if the numbers are "correct" (i.e. in accordance with the timezones present on your systems, but with a misconfiguration somewhere) or if there is a bug in conversions.

**Comment by flamber** [comment]
Closing, since hard to fix without further details. Likely fixed in 0.34 with many other timezone fixes.
