### ISSUE TITLE
Stuck at "Starting Metabase..." because of CSP doesn't allow <script>

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10197]
When accessing Metabase before it's started, then it's stuck on "Starting Metabase..." until manual browser refresh because the `<script>` is being blocked by CSP, so the `poll()` is never executed - neither are the little text/image teaser `switcher()`.
At least two forum users was hit by this, but I didn't understand the problem until now.
Metabase 0.32.9

**Comment by tlrobinson** [comment]
We should fix this since it's a bug, but I'd call it a P2 since it only happens when Metabase is first starting, and refreshing fixes it.

**Comment by camsaul** [comment]
To fix this: 

1.  spin up a new instance of Metabase
2.  Look at the CSP error message in the browser inspector. In Brave it tells you what hash you need to add to your CSP for the script in question
3.  add hash to the CSP here https://github.com/metabase/metabase/blob/master/src/metabase/middleware/security.clj#L44

**Comment by tlrobinson** [comment]
@camsaul How hard would it be to compute those hashes automatically?

**Comment by camsaul** [comment]
@tlrobinson we could do it I think no prob if we kept those inline scripts in separate files

**Comment by camsaul** [comment]
Updating the steps to fix this:

4.  Huge bonus points if you put the inline scripts in separate files and then compute the hashes dynamically and include the scripts in the index template with `{{{mustache}}}` templating (which is how we're putting other stuff in there). Files only need to be read/hashed once since they won't change after instance is launched instead of every time index.html is fetched (slower)

Relevant code is in `metabase.routes.index` and `./resources/index_template.html`

**Comment by flamber** [comment]
@camsaul 
Okay, I really wanted to get the :cake:, but it's way more difficult than what I expected - well Clojure :smile: 
I have this [working great](https://github.com/metabase/metabase/compare/master...flamber:csp_inlinejs_dynamic#diff-1ec28ec031557136f7ea70ad3749534f) with `lein`, it just doesn't work when compiling the jar, since `.listFiles` doesn't handle jar archives, so I looked at how plugins are being picked up, but I just can't get it to work.
(Do I know what I'm doing in Clojure? Nope. Does it seem to work and stored in memory? Yep)
It probably takes you 10 minutes to fix this, but I've spend waaay to long, so I have to throw in the :towel:

**Comment by walterl** [comment]
@camsaul @tlrobinson 
Seeing as computing the script hashes dynamically kinda defeats the purpose of the hashes (verifying the content of the scripts), how about using a CSP nonce value for each inline script instead?

It'll be simpler and easier to implement, since the nonce is independent of the script content. That means we don't need to split out the inline scripts and figure out how to hash them, which isn't easy as @flamber pointed out.

It'll also be (slightly) less computationally expensive, since we only need to hash a random number, not an entire script.

**Comment by camsaul** [comment]
The point of bashing them is so someone can't inject <script> tags, not to make sure we didn't change the underlying code in them

**Comment by camsaul** [comment]
Put the scripts in /resources and use io/resource to get them it works for either

**Comment by camsaul** [comment]
Also WRT to hashing be expensive you only need to do it once anyway

**Comment by camsaul** [comment]
But yeah nonces should work fine, but a little more computationally expensive computing several cryptographically secure random numbers on each request as opposed to a couple of hashes once  and could exacerbate the issues we've had with hosts running out of entropy on Heroku

**Comment by camsaul** [comment]
We have ran into issues with instances on Heroku running out of entropy and stalling tho so generating a pair of cryptographically secure randoms could be bad so we should probably only do it for requests that include the files in question

**Comment by walterl** [comment]
That makes sense. The patch I've been working on does exactly that: it only generates a nonce for `init.html` request. Although we may want to expand that to the inline JS in `index*.html` too, slightly exacerbating the entropy issue.

**Comment by camsaul** [comment]
We should do it for `index.html` while we're at it.

Here's a general idea for how you could implement the nonces thing in a way that only creates them if needed. This way they're only created on demand for the tiny subset of requests that need them and only the created ones are included in the CSP

```clj
;; probably in metabase.middleware.security
(def ^:private ^:dynamic *nonces* nil)

(defn- add-nonce! [nonce]
  (swap! (or *nonces* (throw (Execption. "*nonces* is unbound."))) conj nonce))

(defn- nonces []
  @(or *nonces* (throw (Execption. "*nonces* is unbound."))))

(defn- random-nonce []
  (ring.util.codec/base64-encode (buddy.core.nonce/random-nonce 32)))

(defn create-nonce! []
  (let [nonce (random-nonce)]
    (add-nonce! nonce)
    nonce))

;; middleware code
;; bind nonces for duration of run
;; this should go in some request middleware somewhere
(binding [*nonces* (atom [])]
  ...
  )

;; template code for index.html etc.
(format "<script type=\"text/javascript\" nonce=\"%s\">" (mw.security/create-nonce!))

;; CSP header (in security.clj)
{:script-source (for [nonce (nonces)]
                  (str "nonce-" nonce))}
```
