### ISSUE TITLE
Password policies

### ISSUE THREAD

**Issue by fabiolanza** [metabase/metabase#10190]
This topic is not a bug. I would like to ask what are the default password policies for local accounts. Can you please inform?

Also, is it possible to change the local account password policies to strengthen it?

Thanks

**Comment by flamber** [comment]
Hi @fabiolanza 
You can change length and complexity with environment variables:
https://metabase.com/docs/latest/operations-guide/start.html#changing-metabase-password-complexity
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue.
