### ISSUE TITLE
Group Ids Data showing up as 0x382C3330

### ISSUE THREAD

**Issue by RobinLollig** [metabase/metabase#10219]
I want to use the group date to sort on groups. The only problem is that the data is showing up weird.

Secondery_Group_Ids **' 3,15,16,17,22,25,29,30,28,34,24,23,33,26,35,27 '**

Showing up ass **'0x332C3135'**

Is this a known probleem ?

**Comment by flamber** [comment]
Hi @RobinLollig 
Without providing any of the information requested, when you opened the issue, then it's hard to help.
What Field Type is `Secondery_Group_Ids`? Admin > Data Model > (database) > (table) > (colulm) :gear:
And please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by salsakran** [comment]
closing since there isn't enough info to diagnose this and there's been no further response for months.

@RobinLollig if you can share the underlying schema that would help us figure out what's going on and what can be done to support your specific use case.
