### ISSUE TITLE
Add a custom database connection driver

### ISSUE THREAD

**Issue by BetaLi** [metabase/metabase#10228]
It is a great thing to show my data, but it does not have the feature about add a custom sql driver, can this function will be add to metabase in the future?

**Comment by flamber** [comment]
Hi @BetaLi 
I'm not sure I understand what you're looking for. Can you be more descriptive?
It sounds like you're looking for https://github.com/metabase/metabase/wiki/Writing-A-Driver

**Comment by BetaLi** [comment]
yes, got it , i want to write a driver

**Comment by flamber** [comment]
@BetaLi Okay, then please close this issue.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by mbvictoria** [comment]
Closing - redirected to Discourse
