### ISSUE TITLE
Funky data in Question results

### ISSUE THREAD

**Issue by aogilvie** [metabase/metabase#10227]
**Describe the bug**
When creating a question the results returned are... not expected :)

**Logs**
After executing Question "get Answer" button query the server logs show:

```
2019-06-20T03:49:21.147804508Z 06-20 03:49:21 WARN query-processor.annotate :: There are fields we (maybe) weren't expecting in the results: #{:ga:totalEvents}
2019-06-20T03:49:21.147865050Z Expected: #{:ga:eventLabel :ga:eventAction :ga:date}
2019-06-20T03:49:21.147869412Z Actual: #{:ga:eventLabel :ga:eventAction :ga:totalEvents :ga:date}
2019-06-20T03:49:21.226155639Z 06-20 03:49:21 DEBUG metabase.middleware :: POST /api/dataset 200 (490 ms) (11 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
```

**To Reproduce**
1. Add a Google Analytics DB in Admin settings
2. Trigger some Events - can use node.js lib Universal Analytics
3. Sample code: 
```
ua(CONFIG.analytics.google.id)
            .event('category', 'action', 'label', 'value')
            .send();
```

**Expected behavior**
As you can see, before June 14th we had accurate data being displayed. After that date (no code changes to our google events) data is mixed with junk query text.

**Screenshots**
![example2](https://user-images.githubusercontent.com/970364/59816866-aa97f000-9358-11e9-98a1-b701f2fcd57c.png)
![example](https://user-images.githubusercontent.com/970364/59816868-ae2b7700-9358-11e9-8885-882e3133c90e.png)

**Information about your Metabase Installation:**
- Testing with Chrome 75.0.3775

- Chrome on Fedora 30

- Metabase connected DB - Google Analytics

- Metabase version 0.30.1

- Hosted on Docker on CentOS 7

**Severity**
Annoying/slight blocker from creating meaningful questions with GA

**Additional context**
Looking at the data, it seems like this started recently around June 14th. Perhaps something has change with Google Analytics format and Metabase is not compatible?

**Comment by flamber** [comment]
Hi @aogilvie 
Thanks for doing a great bug report!
There has been many changes since 0.30.1 - the latest release is 0.32.9, could you try that?
Remember to backup before upgrading.

**Comment by aogilvie** [comment]
@flamber pulled the latest docker image, still have the same issue.

>お使いのMetabase 0.32.9は最新です
(your current version is latest)

![example3](https://user-images.githubusercontent.com/970364/59818361-8f2fe380-935e-11e9-9387-6795c5a0e786.png)

There are now less data from the docker logs, only one line after executing query:

```
2019-06-20T04:23:35.314012257Z 06-20 04:23:35 DEBUG middleware.log :: POST /api/card/165/query 200 [ASYNC: completed] 593 ms (15 DB calls) Jetty threads: 2/50 (5 idle, 0 queued) (48 total active threads) Queries in flight: 0

```

**Comment by aogilvie** [comment]
(Sorry for the drips of info/updates...) 
Adding some more information, this is not necessary fixed to event label, I also see this in event category:

![example3](https://user-images.githubusercontent.com/970364/59818936-d9b25f80-9360-11e9-9346-659287ef2b62.png)

**Comment by aogilvie** [comment]
OK, I checked GA dashboard:
![example4](https://user-images.githubusercontent.com/970364/59819058-61986980-9361-11e9-817b-d7ed6268b38d.png)

Wow. Something funky going on. Looks like a node module broke or GA issue.

Closing. Cheers for all your hard work on this product. It rocks. I'll continue to provide Japanese translations as I can :)

**Comment by flamber** [comment]
When I do some search online for what's inside the `CONCAT(...)`, then it looks like typical SQL injections. Check if your website might be under attack.
Thank you for the doing translations! :heart:

**Comment by aogilvie** [comment]
Thanks. I'll look into it.
