### ISSUE TITLE
0.32.9 - counting HLL field from Druid datasource stopped working

### ISSUE THREAD

**Issue by amin-amirali** [metabase/metabase#10221]
In version 0.32.9, the generated query when counting a druid hyperloglog field is incorrect:
"aggregations":[{"type":"cardinality","name":"count","fieldNames":["hll_field"]}]

It should be:
"aggregations":[{"type":"hyperUnique","name":"count","fieldName":"hll_field"}]

This was working in version 0.31.0.

**Comment by salsakran** [comment]
@cam @sbelak did we change anything about the druid QP in 0.32 that might cause this?

**Comment by amin-amirali** [comment]
Correction: its not working on 0.31.0 either...
It is working on a custom build that we have, based on hash: beb860d

**Comment by amin-amirali** [comment]
I've just built metabase based on one of the latest commits (207e8d661) that includes the above fix and... Im sorry but it is still not working on my side... The generated query still uses "type: cardinality" instead of "hyperUnique" - even though the field that Im using is a "type/DruidHyperUnique"...

**Comment by flamber** [comment]
Not sure if Simon gets a notification unless he's tagged, so @sbelak :smiley:

**Comment by sbelak** [comment]
Can you share the MBQL query (it should be somewhere in the log) and what /api/field/:id for the field.

**Comment by amin-amirali** [comment]
@sbelak The log shows debug messages but I can't see any MBQL there. Is there any java flag that I should start Metabase with?

**Comment by sbelak** [comment]
@amin-amirali mind checking out master after #11360 and report if it's finally fixed

**Comment by amin-amirali** [comment]
@sbelak I ran a couple of queries and the numbers are looking as they should. It looks corrected on my side. Thank you!

**Comment by sbelak** [comment]
Awesome. Thanks for your help!
