### ISSUE TITLE
Unable to use Google Analytics Individual Goal Completions

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#10231]
**Describe the bug**
If you want to measure an individual Google Analytics Goal's Metrics (e.g., Completions), it appears to not be possible (or I'm being obtuse and can't figure it out and can't find docs to help).

**To Reproduce**
1. Select a Google Analytics profile with configured goals.
2. Select a date range
3. Select metric `Goal XX Completions`
4. Group by Week

![Question · Metabase 2019-06-20 14-55-53](https://user-images.githubusercontent.com/199588/59874416-27809500-936c-11e9-92cd-b58a03c5a7c0.jpg)

**Expected behavior**
Expected behavior would be for there to be an input field where you can specify _which goal_ you are looking for.  Or else instead of having one single `Goal XX Completions` metric to have one for each configured Goal (bonus if Metabase pulled in the Goal's name for convenience, but number would be better than nothing).

**Actual behavior**
An error is received:
> Unknown metric(s): ga:goalXXCompletions For details see https://developers.google.com/analytics/devguides/reporting/core/dimsmets.

**Information about your Metabase Installation:**
Your browser and the version: Issue occurs in both Safari 12.1 and Chrome 74.0.*
Your operating system: macOS 10.14.5
Your databases: Google Analytics
Metabase version: 0.32.5
Metabase hosting environment: Unsure, but if I had to guess, Beanstalk.
Metabase internal database: Again unsure, but if I had to guess, Postgres

**Severity**
Blocking some dashboards that are desired to be consumed at the Executive level and throughout the organization, but not blocking Metabase usage entirely.

**Comment by phillipadsmith** [comment]
@chucksense Quick question as someone who's not using the Google Analytics connector much yet but is considering it: Are you able to display goal completions at all in your dashboard or pulses?

**Comment by chucksense** [comment]
@phillipadsmith no I have not gotten it working.

**Comment by flamber** [comment]
Closing in favor of #4717
