### ISSUE TITLE
Tooltips not appearing correctly if they get cut off by the screen

### ISSUE THREAD

**Issue by mbvictoria** [metabase/metabase#10234]
**Describe the bug**
Certain points on graphs have tooltips that flicker in and out - seems to be related to if they're getting cut off by the screen.

**To Reproduce**

1. Open a line graph
2. Put your mouse over the point that's the furthest to the right

Couldn't reproduce when tried on a couple different Macs, may be Windows specific?

**Expected behavior**
Tooltip appears as expected.

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 74

- Your operating system: Windows

Using the internal Metabase instance.

**Comment by flamber** [comment]
I've never experienced this, but a lot has changed since and most of the underlying libraries has been updated.
