### ISSUE TITLE
Div/pane color Does not fill full record view

### ISSUE THREAD

**Issue by robertsosinski** [metabase/metabase#10232]
**Describe the bug**
When clicking on the id of a record in the results view, and seeing the "full" record view, the left div/pane is a white and the right one is light-blue.  However, the left pane is only filled in white up to the bottom of the original scroll height.  As such, when you scroll down, the area beyond the original scroll height is now light-blue.

See attached screen shots to see.

**To Reproduce**
1. Go to the full record view.
2. Scroll down.

**Expected behavior**
The full length of the left div/pane should be white.

**Information about your Metabase Installation:**
- Your browser and the version: (Chrome 74.0.3729.169, Firefox 67.0.2, IE 10)

- Your operating system: (Windows 10)

- Your databases: (H2, Postgres)

- Metabase version: (0.32.9)

- Metabase hosting environment: (Windows 10 Java 11 .jar file)

- Metabase internal database: (Postgres)

**Severity**
Not a big issue, no loss of capability.  Just a visual bug.

**Screen Shots**

Before scrolling down...
![Capture-Top](https://user-images.githubusercontent.com/6429/59877543-b4771e80-936b-11e9-98be-b1dd93f82da6.PNG)

After scrolling down (red arrow mine)...
![Capture-Bottom](https://user-images.githubusercontent.com/6429/59877560-bb059600-936b-11e9-94a4-70e8e1cd32a3.PNG)

**Comment by flamber** [comment]
Hi @robertsosinski This looks like a duplicate of #9868, if you agree, then please close this.

**Comment by robertsosinski** [comment]
Hey there,

You are absolutely correct, this is a dup; closing now.

Thanks!

-Robert
