### ISSUE TITLE
A sidebar for collections to speed up navigation between dashboards and charts?

### ISSUE THREAD

**Issue by cqcn1991** [metabase/metabase#10237]
**Is your feature request related to a problem? Please describe.**
quickly navigate between different dashboards, charts

**Describe the solution you'd like**
Just like google analytics, add a sidebar on the left for quick navigation 

![image](https://user-images.githubusercontent.com/2425141/59901379-9eca2d80-942d-11e9-98e8-ac30b8a0f095.png)

**Describe alternatives you've considered**
Users need to open more tabs (one for collection page and others for dashboards) and switch between them is tedious.

**How important is this feature to you?**
So everyone using Metabase can have an easier time switching between different dashboards

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by kulyk** [comment]
Coming in 43
