### ISSUE TITLE
Better placement for New Collection button

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10240]
If a collection has no sub-collections, it would be nice if the new collection button/link had a better place to live so that the list of items could be flush-left with the page title and first pinned item. 

## Current layout
![image](https://user-images.githubusercontent.com/2223916/59948317-86a1e080-9424-11e9-9d2a-7dc21b863c60.png)

## Possibilities
This bears actual design cycles, but a stupid example solution would be to just put a button in the top-right:

![image](https://user-images.githubusercontent.com/2223916/59948740-ef3d8d00-9425-11e9-96e0-08ceced7f838.png)

**Comment by flamber** [comment]
This was implemented in 0.38: https://www.metabase.com/blog/Metabase-0.38/index.html
