### ISSUE TITLE
Production Dockerfile broken in master

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#10244]
Switching to `adoptopenjdk/openjdk11:alpine-jre` broke our `./bin/docker/Dockerfile`, specifically:

```
# fix broken cacerts
RUN apk add --update java-cacerts && \
    rm -f /usr/lib/jvm/default-jvm/jre/lib/security/cacerts && \
    ln -s /etc/ssl/certs/java/cacerts /usr/lib/jvm/default-jvm/jre/lib/security/cacerts && \
    rm -rf /tmp/* /var/cache/apk/*
```

Fails like:

```
Building Docker image metabase/metabase-head:qb3-rc1asdf from local source
Sending build context to Docker daemon  185.2MB
Step 1/11 : FROM adoptopenjdk/openjdk11:alpine-jre
 ---> d3254d10b635
Step 2/11 : ENV FC_LANG en-US
 ---> Using cache
 ---> 0d025e1896d3
Step 3/11 : ENV LC_CTYPE en_US.UTF-8
 ---> Using cache
 ---> 2dd99b2d0535
Step 4/11 : RUN apk add --update bash ttf-dejavu fontconfig
 ---> Using cache
 ---> f4934b1a19cf
Step 5/11 : RUN apk add --update java-cacerts &&     rm -f /usr/lib/jvm/default-jvm/jre/lib/security/cacerts &&     ln -s /etc/ssl/certs/java/cacerts /usr/lib/jvm/default-jvm/jre/lib/security/cacerts &&     rm -rf /tmp/* /var/cache/apk/*
 ---> Running in be7400f5c85a
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/6) Installing libffi (3.2.1-r6)
(2/6) Installing p11-kit (0.23.14-r0)
(3/6) Installing libtasn1 (4.13-r0)
(4/6) Installing p11-kit-trust (0.23.14-r0)
(5/6) Installing ca-certificates (20190108-r0)
(6/6) Installing java-cacerts (1.0-r0)
Executing busybox-1.29.3-r10.trigger
Executing glibc-bin-2.29-r0.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 44 MiB in 39 packages
ln: /usr/lib/jvm/default-jvm/jre/lib/security/cacerts: No such file or directory
The command '/bin/sh -c apk add --update java-cacerts &&     rm -f /usr/lib/jvm/default-jvm/jre/lib/security/cacerts &&     ln -s /etc/ssl/certs/java/cacerts /usr/lib/jvm/default-jvm/jre/lib/security/cacerts &&     rm -rf /tmp/* /var/cache/apk/*' returned a non-zero code: 1
```

It's entirely possible we don't even need to "fix broken cacerts" on that image, or a different fix is needed, but I haven't had a chance to try it.

Actually, the `./Dockerfile` actually has completely different `cacert` shenanigans:

```
# install updated cacerts to /etc/ssl/certs/java/cacerts
RUN apk add --update java-cacerts

# import AWS RDS cert into /etc/ssl/certs/java/cacerts
ADD https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem .
RUN keytool -noprompt -import -trustcacerts -alias aws-rds \
  -file rds-combined-ca-bundle.pem \
  -keystore /etc/ssl/certs/java/cacerts \
  -keypass changeit -storepass changeit
```

It seems like that one is still building (e.x. the `metabase/metabase-head` DockerHub repo)

I'm not sure why we don't need the RDS cert on the production Dockerfile?

Also, it would be nice if we could [eliminate one of these Dockefiles](https://github.com/metabase/metabase/issues/2849). The `./Dockerfile` is a "multistage" one with `builder` and `runner` stages. Maybe we could skip the `builder` stage if we provide a jar built externally.

**Comment by TomSesselmann** [comment]
I'm not sure if this is related but I was getting an issue when trying to run `docker build` with `./Dockerfile`

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
```

Removing `JAVA_OPTS="$JAVA_OPTS --add-modules=java.xml.bind"` from `/bin/start` seemed to have fixed it, but I don't know enough about the stack to know if this will just break other things down the line. Got the solution from this old commit in another repo
https://git.xyser.com/Test/metabase/commit/b0bdc2808c118cc0514feacca07e6f637495239e

@camsaul

**Comment by dfx413** [comment]
Not sure whether this is related (seems like to be related what @TomSesselmann wrote)but all of the images on https://hub.docker.com/r/metabase/metabase-head
since about 20 days ago are broken. They all crash with the same message when starting:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
```

**Comment by tlrobinson** [comment]
I wonder if this is due to continuing to use Java 8 for the `builder` stage

https://github.com/metabase/metabase/blob/master/Dockerfile#L5

but Java 11 for the `runner` stage

https://github.com/metabase/metabase/blob/master/Dockerfile#L56

?

**Comment by walterl** [comment]
The original cacert issue was fixed by @camsaul in #10246.

**Comment by dfx413** [comment]
Can confirm that docker tag _remove-java-add-modules-option_ is working again.

**Comment by tlrobinson** [comment]
@walterl this appears to still be broken:

```
$ docker run --rm -it -p3000:3000 metabase/metabase-head:latest                                                     
Using these JAVA_OPTS:  -XX:+IgnoreUnrecognizedVMOptions -Djava.awt.headless=true -Dfile.encoding=UTF-8 --add-modules=java.xml.bind
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
```

This isn't tested via CI so we should manually verify by doing:

```
docker build . -t metabase-test-image
docker run --rm -it -p3000:3000 metabase-test-image
```
