### ISSUE TITLE
Date range picker unchecks "include today" when date range is changed

### ISSUE THREAD

**Issue by dontcallmesherryli** [metabase/metabase#10249]
**Describe the bug**
Date range picker unchecks "include today" whenever user changes the date range. User has to save twice in order to change a date range AND have the date range include today.

**Logs**

**To Reproduce**
1. Open a report dashboard
2. Open date range data filter 
3. See that "include today" is checked on default 
4. Change the number of days 
5. Click save 

Observe "include today" is unchecked.

**Expected behavior**
"Include today" checkbox remains checked upon save

**Screenshots**
![image](https://user-images.githubusercontent.com/52211561/60112870-9ed47100-973e-11e9-919f-08ca56a1e5db.png)
"include today" checked.

Change date to 10 days ago, click save.
![image](https://user-images.githubusercontent.com/52211561/60112945-bd3a6c80-973e-11e9-9ccd-46f89ef11410.png)
"include today" unchecked.

**Information about your Metabase Installation:**
- Your browser and the version: chrome Version 74.0.3729.169 (Official Build) (64-bit)

- Your operating system: (MacOS)

- Metabase version: version v0.32.4

**Severity**
Annoying for users, must save twice to change date range.

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
