### ISSUE TITLE
Table headings hidden behind horizontal scrollbar after filter reset

### ISSUE THREAD

**Issue by qerim** [metabase/metabase#10255]
![image](https://user-images.githubusercontent.com/3625009/60168017-23d19000-97fc-11e9-956d-99dd16713c76.png)

GIF Preview: https://i.imgur.com/9ayd70Q.gif

After applying a filter or more, then removing those filters, a horizontal bar appears under the headings.

About 30 fields exists in this table.

The usual horizontal bar on the bottom remains as is.

Metabase version: 0.32.9
Metabase hosting environment: Elastic Beanstalk
Browser: Firefox 67.0.2 x64
Screen Resolution: 3840x2160 and also tried on 1920x1080
Platform: Windows

No issue on Chrome browser.

**Comment by flamber** [comment]
The latest releases of 0.33 has fixed several Firefox specific issue.
And I cannot reproduce this on `master` (upcoming 0.33.4/0.34.0) anymore with Firefox 69:
![image](https://user-images.githubusercontent.com/1447303/66278844-1f405d00-e86a-11e9-81eb-b93e4bd3c953.png)

**Comment by qerim** [comment]
@flamber tested it and it looks resolved now. Thank you.
