### ISSUE TITLE
Failed to connect to database: Timed out after 5000 milliseconds. java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB. On Windows Server 2012 R2

### ISSUE THREAD

**Issue by sirawichj** [metabase/metabase#10261]
The following error occured after running   java -jar metabase.jar.  Could anyone please advise me how to fix it?  Thank you so much. 
.................................................................................................................................
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\sirawicj>java -jar metabase.jar
06-27 00:57:21 ←[1mINFO metabase.core←[0m :: Starting Metabase in STANDALONE mod
e
06-27 00:57:21 ←[1mINFO metabase.core←[0m :: Launching Embedded Jetty Webserver
with config:
 {:port 3000}

06-27 00:57:22 ←[1mINFO metabase.core←[0m :: Starting Metabase version v0.16.1 (
ba7fba0 HEAD)...
06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:bigquery
←[0m ?
06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:druid←[0
m ?
06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:h2←[0m ?

06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:mongo←[0
m ?
06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:mysql←[0
m ?
06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:postgres
←[0m ?
06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:redshift
←[0m ?
06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:sqlite←[
0m ?
06-27 00:57:23 ←[1mDEBUG metabase.driver←[0m :: Registered driver ←[34m:sqlserve
r←[0m ?
06-27 00:57:23 ←[1mINFO metabase.db←[0m :: ←[36mVerifying Database Connection ..
.←[0m
06-27 00:57:28 ←[1mERROR metabase.driver←[0m :: Failed to connect to database: T
imed out after 5000 milliseconds.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.
driver)) ((clojure.core/deref (resolve (quote metabase.driver/can-connect-with-d
etails?))) engine details))
        at metabase.db$verify_db_connection.invokeStatic(db.clj:148)
        at metabase.db$verify_db_connection.invoke(db.clj:143)
        at metabase.db$setup_db.invokeStatic(db.clj:162)
        at metabase.db$setup_db.doInvoke(db.clj:154)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:128)
        at metabase.core$init_BANG_.invoke(core.clj:113)
        at metabase.core$start_normally.invokeStatic(core.clj:212)
        at metabase.core$start_normally.invoke(core.clj:206)
        at metabase.core$_main.invokeStatic(core.clj:246)
        at metabase.core$_main.doInvoke(core.clj:241)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
06-27 00:57:28 ←[1mERROR metabase.core←[0m :: Metabase Initialization FAILED:  A
ssert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.
driver)) ((clojure.core/deref (resolve (quote metabase.driver/can-connect-with-d
etails?))) engine details))
06-27 00:57:29 ←[1mINFO metabase.core←[0m :: Metabase Shutting Down ...
06-27 00:57:29 ←[1mDEBUG metabase.task←[0m :: Stopping Quartz Scheduler
06-27 00:57:29 ←[1mINFO metabase.core←[0m :: Metabase Shutdown COMPLETE

C:\Users\sirawicj>

**Comment by flamber** [comment]
Hi @sirawichj 
It looks like you're using 0.16.1 (more than 3 years old) - the latest release is 0.32.9
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
