### ISSUE TITLE
Tool tip showing wrong series on multi-series charts

### ISSUE THREAD

**Issue by chen1tian** [metabase/metabase#10266]
**Describe the bug**
showing all series in one tooltip of bar

**To Reproduce**
1. add new sql query like 'SELECT 'x' as x_axis, 1 as serie_one, 2 as serie_two, 3 as serie_three'
2. choose chart type = 'bar'
3. move mouse to middle bar, the tooltip showing all of three seris name, should show only one

**Screenshots**
![bug](https://user-images.githubusercontent.com/654089/60231479-e3d9de00-98cb-11e9-9635-6cca64f111ae.png)
___

add series to 5, the second series and the forth series showing error tooltip.

![bug2](https://user-images.githubusercontent.com/654089/60232233-8a26e300-98ce-11e9-94b9-c041ce96d424.jpg)
![bug3](https://user-images.githubusercontent.com/654089/60232234-8abf7980-98ce-11e9-8de0-08661c51d92e.jpg)

**Comment by ranquild** [comment]
I don't think it's a bug. We show unaggregated data matching the X value in the tooltip. This case just makes it look like a bug. 

Another one with real data:
<img width="1679" alt="Screen Shot 2021-09-20 at 3 03 11 pm" src="https://user-images.githubusercontent.com/8542534/133999115-b5d5f97a-4bc6-47fc-94e7-f631b61d5d18.png">

The main point here is that we don't show values for other bars, it's unaggregated data from the source row for this bar.

@flamber WDYT about closing this issue?

**Comment by flamber** [comment]
Yeah, seems like it is the correct behavior. Closing in favor of #5176
