### ISSUE TITLE
BigQuery column of ARRAY type in results causes a casting exception

### ISSUE THREAD

**Issue by lukeman** [metabase/metabase#10275]
**Describe the bug**
BigQuery queries that return a column of ARRAY type trigger a backend exception: `java.util.ArrayList cannot be cast to java.lang.String`

**Logs**
`Jun 28 09:43:54 WARN metabase.query-processor.middleware.process-userland-query :: Query failure {:status :failed,
:class java.lang.ClassCastException,
:error "java.util.ArrayList cannot be cast to java.lang.String",
:stacktrace
("--> driver.bigquery$fn__576.invokeStatic(bigquery.clj:215)"
"driver.bigquery$fn__576.invoke(bigquery.clj:215)"
"driver.bigquery$post_process_native$iter__610__614$fn__615$iter__640__644$fn__645.invoke(bigquery.clj:255)"
"query_processor.middleware.annotate$native_cols$iter__33058__33062$fn__33063$fn__33064$iter__33065__33069$fn__33070.invoke(annotate.clj:50)"
"driver.common$values__GT_base_type.invokeStatic(common.clj:237)"
"driver.common$values__GT_base_type.invoke(common.clj:231)"
"query_processor.middleware.annotate$native_cols$iter__33058__33062$fn__33063$fn__33064.invoke(annotate.clj:49)"
"query_processor.middleware.annotate$native_cols$iter__33058__33062$fn__33063.invoke(annotate.clj:44)"
"query_processor.middleware.annotate$native_cols.invokeStatic(annotate.clj:44)"
"query_processor.middleware.annotate$native_cols.invoke(annotate.clj:39)"
"query_processor.middleware.annotate$add_native_column_info.invokeStatic(annotate.clj:58)"
"query_processor.middleware.annotate$add_native_column_info.invoke(annotate.clj:54)"
"query_processor.middleware.annotate$fn__33527$add_column_info_STAR___33532$fn__33539.invoke(annotate.clj:345)"
"query_processor.middleware.annotate$fn__33527$add_column_info_STAR___33532.invoke(annotate.clj:340)"
"query_processor.middleware.annotate$add_column_info$fn__33555.invoke(annotate.clj:363)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__35249.invoke(cumulative_aggregations.clj:57)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__39124.invoke(resolve_joins.clj:184)"
"query_processor.middleware.limit$limit$fn__36107.invoke(limit.clj:19)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__41885.invoke(results_metadata.clj:86)"
"query_processor.middleware.format_rows$format_rows$fn__36095.invoke(format_rows.clj:26)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__32190.invoke(add_dimension_projections.clj:234)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__33789.invoke(add_source_metadata.clj:127)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__39168.invoke(resolve_source_table.clj:48)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__32952.invoke(add_row_count_and_status.clj:16)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__35460.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__38788.invoke(resolve_driver.clj:23)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__34649$fn__34650.invoke(bind_effective_timezone.clj:9)"
"util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
"util.date$call_with_effective_timezone.invoke(date.clj:77)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__34649.invoke(bind_effective_timezone.clj:8)"
"query_processor.middleware.store$initialize_store$fn__41910$fn__41911.invoke(store.clj:11)"
"query_processor.store$do_with_new_store.invokeStatic(store.clj:41)"
"query_processor.store$do_with_new_store.invoke(store.clj:37)"
"query_processor.middleware.store$initialize_store$fn__41910.invoke(store.clj:10)"
"query_processor.middleware.async$async__GT_sync$fn__34250.invoke(async.clj:23)"
"query_processor.middleware.async_wait$runnable$fn__34375.invoke(async_wait.clj:89)"),
:query
{:type "native",
:native {:query "select [1, 2]", :template-tags {}},
:parameters [],
:async? true,
:middleware {:add-default-userland-constraints? true, :userland-query? true},
:info
{:executed-by 1,
:context :ad-hoc,
:card-id nil,
:nested? false,
:query-hash [20, 66, 5, -36, -46, 10, -105, -101, -68, 63, -102, -44, 10, 49, -98, 86, 115, -94, -122, 82, 52, 45, -17, 41, 48, 2, 15, 51, 124, 62, 103, 98]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}}}`

**To Reproduce**
1. Select a BigQuery connection
2. Run a native query that returns an ARRAY: `select [1, 2]`
3. Casting error shows in the results area

**Expected behavior**
Results of the successful query should display.

**Information about your Metabase Installation:**
- Your browser and the version: Safari 13

- Your operating system: macOS 10.14.5

- Your databases: BigQuery

- Metabase version: 0.32.9 (bug experienced with 0.32.8 as well)

- Metabase hosting environment: Docker

- Metabase internal database: Postgres

**Severity**
I'm comfortable working around this or simply using the BigQuery UI, although I imagine it'd be a blocker for less technical users.

**Comment by genk1** [comment]
Having same problem using BigQuery, there is no problem with Array with `string` or `key value object`, only number array causing the error.

**Comment by camsaul** [comment]
It seems like a fix so this doesn't throw an Exception should be pretty straightforward. I'm not sure how we should return arrays at this point (CSV?) but if it's working for string arrays we could probably do the same thing for number arrays.
