### ISSUE TITLE
Create expression question based on two existing questions

### ISSUE THREAD

**Issue by dinsaw** [metabase/metabase#10271]
I am seeking functionality in Metabase, which allows User to create new question/chart based on expression on existing questions.

For example,
I have following two questions in dashboard panel. These two questions are based on two different tables.

![image](https://user-images.githubusercontent.com/6128184/60320223-b27a1480-9996-11e9-9e44-97c9cd31a9cd.png)

Now, User wants to plot conversion rate from views to orders. Is there any feature to write expression, like (OrderCount/ViewsCount) * 100. This OrderCount and ViewCount is referring to two line charts. And the resulting expression can be termed as new question or chart.

I am using Metabase v0.32.7. Is there a way to do this in Metabase?

**Comment by flamber** [comment]
Hi @dinsaw 
Currently not without doing first two questions in a single SQL query. By the way, latest release is 0.32.9
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by dinsaw** [comment]
Thanks @flamber.  Created feature proposal https://github.com/metabase/metabase/issues/10273
