### ISSUE TITLE
User password reset not working anymore for Admin

### ISSUE THREAD

**Issue by Anne-Caroline** [metabase/metabase#10274]
**Describe the bug**
When trying to reset the password of another user on the admin panel, the popup with the new password is no more displayed. 

**To Reproduce**
1. Go to 'People' in Admin 
2. Click on 'Reset password'

**Expected behavior**
A pop up with the new password should appear.

- Metabase version: (e.x. 0.32.5)

**Comment by mbvictoria** [comment]
@Anne-Caroline Can you confirm which Metabase version you're on - is it 0.32.5, or a more recent version? What browser are you experiencing this in? Thanks!

**Comment by Anne-Caroline** [comment]
I'm on the latest one,  0.32.9 (updated yesterday but the bug remained). I'm a using Chrome. Thank you!

**Comment by flamber** [comment]
Do you see any errors in the Metabase log or in your browser console, when clicking "Reset password"?

**Comment by Anne-Caroline** [comment]
No error no, nothing is sent after the "Reset password" pop up

**Comment by flamber** [comment]
@Anne-Caroline Okay, but you do see a debug log similar to this, when clicking reset?
```
07-01 04:22:23 DEBUG middleware.log :: POST /api/session/forgot_password 200 232 ms (2 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (128 total active threads) Queries in flight: 0
```

**Comment by DennisMugambi** [comment]
@flamber also experiencing the same issue for the same version 0.32.9.`Jul 23 14:11:02 DEBUG metabase.middleware.log :: POST /api/session/forgot_password 200 2 mins (2 DB calls) Jetty threads: 8/50 (8 idle, 0 queued) (293 total active threads) Queries in flight: 0`

**Comment by flamber** [comment]
@DennisMugambi 
If you're seeing that message, that means the browser asked Metabase to send the mail.
Then you should check your SMTP mail server log for any activity.
Use the Admin > Settings > Email > Send test mail, to make sure that Metabase is allowed to send mails through your SMTP.

**Comment by salsakran** [comment]
I just tried to reproduce this on master and was unable to. 

@Anne-Caroline we only show that pop up when an instance does not have SMTP credentials configured. If the instance can send emails, we send the user an email with password resets.

@DennisMugambi if you see that line, we tried to send an email. Anything past that is impossible for us to debug as we have no visibility into where the email is being dropped. Check your email delivery service and the spam filters of the user you're trying to reset. 

Closing this as there doesn't seem to be a specific bug. If you can reproduce this (or provide more information from the SMTP gateway that indicated that Metabase is sending malformed emails) please chime in and I'll re-open.
