### ISSUE TITLE
could not sign in

### ISSUE THREAD

**Issue by toby2** [metabase/metabase#10284]
**Describe the bug**
could not sign in

**Logs**
07-02 18:36:29 ERROR middleware.log :: POST /api/session 500 143 ms (1 DB calls) 
{:value
 [{:ıd 1, :password_salt "34e86b4e-9a1e-4553-a558-2f62ae0c1d0f", :password "$2a$10$C95kmS97MWmTCYEQayA1CuWlQaSDReb1.bV6giPiWeJDPljgnTihe", :last_logın #inst "2019-07-02T01:44:31.265000000-00:00"}],
 :error [(named {:id missing-required-key, :last_login missing-required-key} user)],
 :message "Input to create-session! does not match schema: \n\n\t   [(named {:id missing-required-key, :last_login missing-required-key} user)]  \n\n",
 :type clojure.lang.ExceptionInfo,
 :stacktrace
 ("--> api.session$fn__60357$create_session_BANG___60362.invoke(session.clj:31)"
  "api.session$fn__60408$email_login__60413$fn__60414.invoke(session.clj:76)"
  "api.session$fn__60408$email_login__60413.invoke(session.clj:71)"
  "api.session$fn__60434$login__60439$fn__60440.invoke(session.clj:92)"
  "api.session$fn__60434$login__60439.invoke(session.clj:86)"
  "api.session$fn__60454.invokeStatic(session.clj:107)"
  "api.session$fn__60454.invoke(session.clj:100)"
  "routes$fn__62814$fn__62815.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__61768.invoke(exceptions.clj:104)"
  "middleware.exceptions$catch_api_exceptions$fn__61765.invoke(exceptions.clj:92)"
  "middleware.log$log_api_call$fn__63188$fn__63189.invoke(log.clj:170)"
  "middleware.log$log_api_call$fn__63188.invoke(log.clj:164)"
  "middleware.security$add_security_headers$fn__61731.invoke(security.clj:105)"
  "middleware.json$wrap_json_body$fn__62893.invoke(json.clj:61)"
  "middleware.json$wrap_streamed_json_response$fn__62911.invoke(json.clj:97)"
  "middleware.session$bind_current_user$fn__60345$fn__60346.invoke(session.clj:193)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:177)"
  "middleware.session$do_with_current_user.invoke(session.clj:170)"
  "middleware.session$bind_current_user$fn__60345.invoke(session.clj:192)"
  "middleware.session$wrap_current_user_id$fn__60334.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__60319.invoke(session.clj:123)"
  "middleware.auth$wrap_api_key$fn__61685.invoke(auth.clj:27)"
  "middleware.misc$maybe_set_site_url$fn__63253.invoke(misc.clj:58)"
  "middleware.misc$bind_user_locale$fn__63256.invoke(misc.clj:74)"
  "middleware.misc$add_content_type$fn__63241.invoke(misc.clj:30)"
  "middleware.misc$disable_streaming_buffering$fn__63278.invoke(misc.clj:119)"
  "middleware.misc$wrap_gzip$fn__63271.invoke(misc.clj:101)")}

**To Reproduce**
1. input email address and password
2. Click on 'sign in'
3. See error
Input to create-session! does not match schema: [0;33m [(named {:id missing-required-key, :last_login missing-required-key} user)] [0m

**Information about your Metabase Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
chrome 75.0.3770.100

- Your operating system: (e.x. OS X 10, Windows XP, etc)
windows 10

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Mysql 5.7

- Metabase version: (e.x. 0.19.3)
0.32.8

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Linux

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
H2

**Comment by flamber** [comment]
Hi @toby2 
Is this a new or existing setup?
I think something might have corrupted the H2 database. I would recommend that you change database;
https://metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

**Comment by toby2** [comment]
existing setup。
After migrating the h2 database to mysql 5.7，sign in is successful, but I can't see all the collections。
See error：
07-03 11:50:25 ERROR middleware.log :: GET /api/collection/root/items 500 4 ms (2 DB calls) 
{:message
 "(conn=24393) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'İNNER JOIN `permissions_group` `pg` ON `pgm`.`group_id` = `pg`.`id` İNNER JOIN' at line 1",
 :type java.sql.SQLSyntaxErrorException,
 :stacktrace
 ("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)"
  "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
  "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
  "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)"
  "org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)"
  "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:379)"
  "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
  "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
  "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
  "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
  "toucan.db$query.invokeStatic(db.clj:274)"
  "toucan.db$query.doInvoke(db.clj:270)"
  "clojure.lang.RestFn.invoke(RestFn.java:410)"
  "--> models.user$permissions_set.invokeStatic(user.clj:280)"
  "models.user$permissions_set.invoke(user.clj:272)"
  "middleware.session$do_with_current_user$fn__58588.invoke(session.clj:175)"
  "models.interface$current_user_permissions_set.invokeStatic(interface.clj:234)"
  "models.interface$current_user_permissions_set.invoke(interface.clj:234)"
  "models.interface$make_perms_check_fn$_has_perms_QMARK___24078.invoke(interface.clj:249)"
  "models.interface$make_perms_check_fn$_has_perms_QMARK___24078.invoke(interface.clj:247)"
  "models.interface$fn__24013$G__24004__24022.invoke(interface.clj:181)"
  "api.collection$fn__44863.invokeStatic(collection.clj:162)"
  "api.collection$fn__44863.invoke(collection.clj:144)"
  "middleware.auth$enforce_authentication$fn__59926.invoke(auth.clj:14)"
  "routes$fn__61084$fn__61085.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__60017.invoke(exceptions.clj:104)"
  "middleware.exceptions$catch_api_exceptions$fn__60014.invoke(exceptions.clj:92)"
  "middleware.log$log_api_call$fn__61458$fn__61459.invoke(log.clj:170)"
  "middleware.log$log_api_call$fn__61458.invoke(log.clj:164)"
  "middleware.security$add_security_headers$fn__59980.invoke(security.clj:105)"
  "middleware.json$wrap_json_body$fn__61163.invoke(json.clj:61)"
  "middleware.json$wrap_streamed_json_response$fn__61181.invoke(json.clj:97)"
  "middleware.session$bind_current_user$fn__58593$fn__58594.invoke(session.clj:193)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:176)"
  "middleware.session$do_with_current_user.invoke(session.clj:170)"
  "middleware.session$bind_current_user$fn__58593.invoke(session.clj:192)"
  "middleware.session$wrap_current_user_id$fn__58582.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__58567.invoke(session.clj:123)"
  "middleware.auth$wrap_api_key$fn__59934.invoke(auth.clj:27)"
  "middleware.misc$maybe_set_site_url$fn__61523.invoke(misc.clj:58)"
  "middleware.misc$bind_user_locale$fn__61526.invoke(misc.clj:74)"
  "middleware.misc$add_content_type$fn__61511.invoke(misc.clj:30)"
  "middleware.misc$disable_streaming_buffering$fn__61548.invoke(misc.clj:119)"
  "middleware.misc$wrap_gzip$fn__61541.invoke(misc.clj:101)"),
 :sql-exception-chain
 ["SQLSyntaxErrorException:"
  "Message: (conn=24393) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'İNNER JOIN `permissions_group` `pg` ON `pgm`.`group_id` = `pg`.`id` İNNER JOIN' at line 1"
  "SQLState: 42000"
  "Error Code: 1064"]}

**Comment by flamber** [comment]
@toby2 
Hmmm....okay, so maybe something was more corrupted than what I expected. You're still using 0.32.8?
Can you check your MySQL error log, which should include the entire failed query?

**Comment by flamber** [comment]
@toby2 Wait, just noticed something interesting `İNNER JOIN` - notice the first letter, which should be a capital `i`, but it looks like it's similar to the Turkish capital `i`, which of course is something completely different for "stupid" computers. Very similar to issue #9177 
What is the language of the OS running Metabase? Are you using Docker or JAR?

**Comment by toby2** [comment]
Thanks for your help, The reason is  a new comer changed the language setting to Turkish . then we can not sign in。after migrating from H2 to mysql, sign in problem is solved., but can't see all the collections.  modifying the language, it has been solved.

**Comment by flamber** [comment]
@toby2 Great that you got it working. Go and upvote #9177 by clicking :+1: on the first post. And click the Subscribe button on the side-panel to get notifications when changed.
And please close this issue :-)
