### ISSUE TITLE
Non-optimal timeseries axis label placement

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#10280]
Here's a chart that nicely shows monthly ticks when the data has weekly ticks.

<img width="500" alt="Screen Shot 2019-07-01 at 7 36 04 PM" src="https://user-images.githubusercontent.com/691495/60472943-f2602680-9c38-11e9-833a-8918c65ba75e.png">

That looks great, but if you make it _slightly_ narrower, the `tickInterval` switches to quarterly, which doesn't use the available space very well:

<img width="500" alt="Screen Shot 2019-07-01 at 7 36 32 PM" src="https://user-images.githubusercontent.com/691495/60472946-f7bd7100-9c38-11e9-88c9-e06c34de45fc.png">

**Comment by mazameli** [comment]
Resolved by https://github.com/metabase/metabase/pull/10307

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
