### ISSUE TITLE
Dynamic thresholds for alerts for individual entities of a table

### ISSUE THREAD

**Issue by anastasiapapa** [metabase/metabase#10293]
Hello there,

To my understanding a feature like this is not present according to what I have read about alerts in the platform. 
Let's say you have a card that you are monitoring the amount of clients in individual stores of a store chain. One store might have 100 a day, and one might have 1000 a day. I know there is already a threshold as a goal to be reached and then you get alerted, but in the scenario above, you will never be alerted about the growth of a smaller store. So would it be possible to create anything dynamic that would compare the previous status of an entity (from the day before for example), and the user would be able to set an alert like "if the amount of clients was raised 30% in a day, in whatever store, send an alert". 
I hope that's clear.

Thanks :)

**Comment by flamber** [comment]
Closing in favor of #7198
