### ISSUE TITLE
/api/card fails to save with SQLException (0.33-preview / notebook-mode)

### ISSUE THREAD

**Issue by RMMSecurity** [metabase/metabase#10292]
**Describe the bug**

**Logs**
`{
    "message": "(conn=442) Incorrect string value: '\\xE2\\x86\\x92 So...' for column 'result_metadata' at row 1",
    "type": "class java.sql.SQLException",
    "stacktrace": [
        "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:255)",
        "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)",
        "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)",
        "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)",
        "org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)",
        "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:194)",
        "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:410)",
        "clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__14568.invoke(jdbc.clj:961)",
        "clojure.java.jdbc$db_do_execute_prepared_return_keys.invokeStatic(jdbc.clj:989)",
        "clojure.java.jdbc$db_do_execute_prepared_return_keys.invoke(jdbc.clj:945)",
        "clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:1020)",
        "clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:997)",
        "toucan.db$simple_insert_many_BANG_$iter__17470__17474$fn__17475$fn__17476.invoke(db.clj:547)",
        "toucan.db$simple_insert_many_BANG_$iter__17470__17474$fn__17475.invoke(db.clj:545)",
        "clojure.lang.LazySeq.sval(LazySeq.java:42)",
        "clojure.lang.LazySeq.seq(LazySeq.java:51)",
        "clojure.lang.RT.seq(RT.java:535)",
        "clojure.core$seq__5402.invokeStatic(core.clj:137)",
        "clojure.core$dorun.invokeStatic(core.clj:3133)",
        "clojure.core$doall.invokeStatic(core.clj:3148)",
        "clojure.core$doall.invoke(core.clj:3148)",
        "toucan.db$simple_insert_many_BANG_.invokeStatic(db.clj:544)",
        "toucan.db$simple_insert_many_BANG_.invoke(db.clj:530)",
        "toucan.db$simple_insert_BANG_.invokeStatic(db.clj:577)",
        "toucan.db$simple_insert_BANG_.invoke(db.clj:566)",
        "toucan.db$insert_BANG_.invokeStatic(db.clj:594)",
        "toucan.db$insert_BANG_.invoke(db.clj:581)",
        "--> api.card$save_new_card_async_BANG_$fn__46947$fn__46948.invoke(card.clj:212)",
        "api.card$save_new_card_async_BANG_$fn__46947.invoke(card.clj:208)",
        "async.util$fn__32740$do_on_separate_thread_STAR___32745$fn__32746$fn__32747.invoke(util.clj:71)"
    ],
    "sql-exception-chain": [
        "SQLException:",
        "Message: (conn=442) Incorrect string value: '\\xE2\\x86\\x92 So...' for column 'result_metadata' at row 1",
        "SQLState: HY000",
        "Error Code: 1366"
    ]
}`

**Question:**

[body.json.txt](https://github.com/metabase/metabase/files/3356898/body.json.txt)

**To Reproduce**
1. Go to table
2. Join it with 1-2 tables
3. Confirm the correct info returns
4. Try to save and fails

**Screenshots**

![image](https://user-images.githubusercontent.com/802527/60626121-c0c19980-9db7-11e9-8fdf-468e61c6eca4.png)

![image](https://user-images.githubusercontent.com/802527/60626388-9de3b500-9db8-11e9-8289-2074131ec76a.png)

**Information about your Metabase Installation:**

- Your databases: MySQL, MSSQL

- Metabase version: 0.33-preview, notebook-mode

- Metabase hosting environment: Windows 10 (Dev), Windows Server 2012 + 2016

- Metabase internal database: MySQL 5.6, MySQL 5.7

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

Every other question I try to write in notebook mode with sufficient complexity fails to save. Pretty high!

**Additional context**

I've tested this on multiple databases, the only thing being in common is the Metabase db for questions is MySQL, I tested this with 5.6, 5.7.

**Comment by flamber** [comment]
Hi @RMMSecurity 
Looking at the error code, it looks like charset problems - are you using `utf8mb4`?
https://stackoverflow.com/questions/34165523/error-1366-hy000-incorrect-string-value-xf0-x9f-x98-x9c-for-column-comme

**Comment by RMMSecurity** [comment]
Short answer no, but oddly enough it was never an issue until this very moment. I'm not sure what happened, but I was on 5.6 on one of them as well as 5.7 with the other. 

5.6 is especially a pain because it runs into an issue when trying to update the fields to utf8mb4 for any varchar length > 191. 5.7 has this fixed by default, but still requires you to update every table and every column to utf8mb4. Did something change? Did result_metadata start having more raw data that appears to be unicode characters/emojis?

**Comment by flamber** [comment]
While it might be possible to use MySQL 5.6 with Metabase 0.32+, you might run into some [issues](https://github.com/metabase/metabase/issues/9954).
There has been many posts in the forum, where the fix was to change charset to `utf8mb`, so it's interesting that you have been able to run with a different charset without any issues.
With the new notebook-mode, I'm guessing `result_metadata` will quickly become larger, since you can do more advanced things (join tables, etc), so maybe that is triggering the error?

**Comment by RMMSecurity** [comment]
Forgot to give an update:

This was due to the fact that Metabase didn't use utf8mb4 by default. It was so much work to go through everything and convert it all to using utf8mb4 after the fact, but it solved the issue.

**Comment by flamber** [comment]
That's why I created #10691, but great you got it working. I would guess you can close this then.

**Comment by RMMSecurity** [comment]
@flamber Thanks for everything you do!
