### ISSUE TITLE
Reordering fields in dashboard causes fields to disappear in edit mode

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#10299]
**Describe the bug**
In a dashboard that has many fields click the edit button and try to reorder one of the fields, it will cause other fields to disappear.

**Logs**
When clicking one of the fields to change its place it gives the error below in console:
```

Uncaught TypeError: Cannot read property 'id' of undefined
    at r.handleSortEnd (app-main.bundle.js?0d1325582067a4b57db2:5)
    at t.handleSortEnd (vendor.bundle.js?0d1325582067a4b57db2:1)
```

**To Reproduce**
Explained in the description above

**Expected behavior**
Reorder fields and place them anywhere we want without ever causing the fields to disappear.

**Screenshots**
![1st-pic](https://user-images.githubusercontent.com/6417083/60767299-65e7b500-a0cb-11e9-9e13-1248240b6a81.jpg)

![2nd-pic](https://user-images.githubusercontent.com/6417083/60767234-32585b00-a0ca-11e9-9cab-b981607c0982.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 75.0

- Your operating system: Ubuntu

- Your databases: Postgres

- Metabase version: 0.32.9

- Metabase hosting environment: Docker

- Metabase internal database: H2

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
