### ISSUE TITLE
Schema of Redshift DB not syncing

### ISSUE THREAD

**Issue by vishnuzoom** [metabase/metabase#10294]
Description of the bug:
'sync-table' task is not working for Redshift DB. We have a lot of tables (could be a reason as smaller databases don't have this issue) and newly created tables are not being synced at all. Can see some of the tables under the data model but the table won't have any column. Due to this, custom queries and field filters are not applicable for the table.
This bug is similar to issue 9844 and 10267. Also tried to manually trigger sync columns, but columns still don't get synced.

Information about Metabase Installation:
•    Database: Redshift DB
•    Metabase version: 0.33.0
•    Metabase hosting environment: Ubuntu 14.04
•    Metabase internal database: MySQL

Severity:
This is hampering querying ( using custom queries ) and applying filters in questions ( in turn in dashboards ).

**Comment by flamber** [comment]
Hi @vishnuzoom 
How is this different from #10267?
Do you see any errors or is the `sync-table` task just not running?
Metabase 0.33.0 is not released, so are you using one of the `preview` releases or `master`?

**Comment by vishnuzoom** [comment]
sorry, my mistake. the version is 0.32.0, changed the description accordingly.
Also, my issue is exactly similar to #9844. So, closing this issue. 
Thanks
