### ISSUE TITLE
Not possible to restore Visibility after setting "Do Not Include" in Data Model

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10297]
After setting "Do Not Include" on a column in Data Model, and refresh browser, then the column is completely gone, so it's not possible to make it visible again.

Looking at the return from `/api/table/X/query_metadata`, the column is not included in `fields`.

**Workaround** to restore visibility:
Click `Queryable` just below the table title, which will temporary reload the column list - including the hidden ones - which can then be changed from "Do Not Include" to "Everywhere"
_Alternatively: Change metadata `metabase_field.visibility_type=normal`_

Tested with Metabase 0.32.9 and 0.33.0-preview2

*This was reported in the [forum](https://discourse.metabase.com/t/problems-with-pulse-email-setup/6600/10)*

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` comment or no added details

**Comment by kurumpa** [comment]
bumped into this recently, came out with this solution:
[columns-visibility.diff](https://github.com/metabase/metabase/files/3407431/columns-visibility.diff.txt) (note: i am a little behind master, so the lines can be messed up)

**Comment by salsakran** [comment]
bumping this in priority because it's irreversible, unexpected and hit by a number of people in the wild

**Comment by mallchin** [comment]
Any update on this?  Been several months but still broken :(

On a sidenote, do you not have tests?  I often find new versions introduce new bugs which could be avoided with testing.

**Comment by cedmo8** [comment]
Just ran into this issue, managed to work around it by clicking on the "Field Settings" cog next to a visible field and incrementing the column ID until I found the hidden field I wanted, then you can change it back to visible.

e.g. http://[SERVER]:3000/admin/datamodel/database/2/table/5/**[Change this Number]**/general

I was able to step through the detailed field settings and change them back regardless of the fields being hidden or not.

**Comment by mark-uscbi** [comment]
We were affected by this today, but the workaround worked. It would be nice if there was some verbiage in the product when there is a known bug that could give you a mini heart attack when your fields are not showing up anywhere.

**Comment by 2Ben** [comment]
Same issue, and since numbers are not consecutive, it's a PITA to find the right field in a big table...

**Comment by amex-doug** [comment]
> Same issue, and since numbers are not consecutive, it's a PITA to find the right field in a big table...

This is the same problem I have right now. I hope this will be fixed soon.

**Comment by amex-doug** [comment]
> Any update on this? Been several months but still broken :(
> 
> On a sidenote, do you not have tests? I often find new versions introduce new bugs which could be avoided with testing.

It seems they have tests right here: https://github.com/metabase/metabase/tree/master/test/

**Comment by amex-doug** [comment]
@salsakran Are there plans to release this soon?

**Comment by PauloHFM** [comment]
Wow! affected by this too, update in metabase database   resolved

**Comment by dylancarruthers** [comment]
Also affected, I hope it will be fixed soon

**Comment by camsaul** [comment]
Copying my notes on this issue from Slack so everything is in one place:
 
> If you don't want a Field to come back when you query a Table you can change its "visibility type" to "hidden". Admins can change this in the Data Model interface in the Admin Panel. The problem is, the API endpoint that's used in the Data Model doesn't return hidden Fields
> 
> I think that API endpoint is also used to power other pages as well, but you will have to double-check.
> 
> I think the best way to fix this would be to add support for a `?include_hidden=true` param to the API endpoint and then the frontend client can use that in the Data Model (but not elsewhere)
> 
> The endpoint lives here https://github.com/metabase/metabase/blob/master/src/metabase/api/table.clj#L233
> 
> It already supports an `include_sensitive_fields` option ("sensitive" is another visibility type) so you can look at how that's implemented as an example.
> 
> I think the basic order to fixing this is adding the param to the endpoint and adding a test for it and then tweaking the frontend code which should only be a couple of lines. When you get to that point you can ask Tom or Paul to point you in the right direction for which code needs to be changed, but it should only be a couple lines

**Comment by robdaemon** [comment]
It looks like this is a frontend bug. 

Repro steps:
1. Go to datamodel admin page
1. Pick a database, then select a table
1. Pick a field, and change "Visibility" to "Do not include"
1. Refresh.
1. Note field is missing from page
1. Click "Queryable" in the page header
1. Note field has reappeared

The `/api/database/:id/metadata` call is used to populate the table's metadata, and it is including the sensitive fields.

**Comment by paulrosenzweig** [comment]
Fixed in #12485
