### ISSUE TITLE
Separate new user account setup from password resets

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1029]
Right now when a new user is created and sent an invite via email, we direct them to a password reset page.

We should treat this as a distinct set of pages to allow us to both set appropriate expiration times and to optimize this without affecting the password reset user flow.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by brunobergher** [comment]
Not applicable anynmore.
