### ISSUE TITLE
Region map break the filter after load finish

### ISSUE THREAD

**Issue by Denis717** [metabase/metabase#10301]
**Describe the bug**
we use version v0.31.2 to design our dashboard, but found a problem when loading the region map with filter, after the region map load finished, the filter not apply to any of the question in the dashboard.

below is region map we use:
![image](https://user-images.githubusercontent.com/44861380/60785922-3a2a0500-a187-11e9-8da1-12a609934f0d.png)
the map display the UK map, and map to the district name in our source table.

when load the page without filter, it working:
![image](https://user-images.githubusercontent.com/44861380/60786093-c9371d00-a187-11e9-9da2-2fb8801abf36.png)
it display the data for all UK region.
when select a district from the filter, the other question finish first, but the map still loading:
![image](https://user-images.githubusercontent.com/44861380/60786174-11563f80-a188-11e9-9b99-727fda06b9d7.png)
and wait until the map finished, all the question show the data without select filer:
![image](https://user-images.githubusercontent.com/44861380/60786235-54181780-a188-11e9-8b02-54e065f98a38.png)
![image](https://user-images.githubusercontent.com/44861380/60786241-5b3f2580-a188-11e9-845c-d52eba603d96.png)

**Expected behavior**
the map should work with the filter, but it break all other question and none of them apply select filter.

**Information about your Metabase Installation:**
- Your browser and the version: Firefox and IE

- Your operating system: Windows 10,

- Your databases: SQL server

- Metabase version: v0.31.2 

**Severity**
 blocking usage of Metabase entirely?

**Comment by flamber** [comment]
Hi @Denis717 
Do you see any errors in the browser console, when it's just spinning?
I'm fairly sure you're seeing issue #4684, which was fixed in 0.32.9

**Comment by Denis717** [comment]
HI, 
Thanks for the help,  it is the same issue, I get the error in the question design page:
![image](https://user-images.githubusercontent.com/44861380/60788125-8a589580-a18e-11e9-8da8-ab685ed7e752.png)
I have to upgrade to version 0.32.9 to make it work.
