### ISSUE TITLE
Upgrade database with heroku

### ISSUE THREAD

**Issue by benjaminb10** [metabase/metabase#10302]
I have installed metabase with heroku.
As my pg database associated is now full, I have to upgrade it, and hit a `pg copy` command.
But to do so, my CLI has to know which app to use, and the CLI infer it from the local folder.
But I don't have any local metabase folder since I have installed metabase following this: https://metabase.com/start/heroku.html

So how can I upgrade my database here?

**Comment by salsakran** [comment]
@benjaminb10 the Heroku UI lets you upgrade a database in place.

We can't offer support for someone else's paid service however, please reach out to Heroku support with this question.
