### ISSUE TITLE
Create a page with links to Metabase plugins

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#10304]
Since we set up the modular database drivers, there are a number of third party drivers out there.

We should have a central list that makes it easy for users to find the right drivers.

Some thoughts
- Sometimes there will be multiple drivers for a given DB available. 
- We can't validate every driver out there
- We should have a way to collect information about how feature complete or stable a driver is
- We should provide a process for a fully stable, supported and feature complete driver to make it into the core set of metabase drivers

**Comment by pkoch** [comment]
This was talked a little bit on https://github.com/metabase/metabase/issues/9348.
