### ISSUE TITLE
Negative segment

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#10313]
Hi everyone, 
currently we can create segments and then use them in queries so that they allow us to select the rows matching the segment. While that is a useful feature there is currently no way to select the rows that do not match the segment. 
That would be a really powerful addition to the filtering capabilities. 
Are you planning to implement such feature?
Thank you for this great tool.

**Comment by flamber** [comment]
This has been possible since 0.34 with Custom Expression `NOT [your-segment]`:
https://www.metabase.com/docs/latest/users-guide/expressions.html
