### ISSUE TITLE
Help with Vitess Driver

### ISSUE THREAD

**Issue by jawabuu** [metabase/metabase#10315]
**Is your feature request related to a problem? Please describe.**
I'm testing out Vitess https://vitess.io and would like to use Metabase as my Business Intelligence application.
I am however unable to add my database using the mysql driver because of unsupported queries.
**Describe the solution you'd like**
I'd like assistance with modifying the mysql driver to work with Vitess. The unsupported queries are the default `concat...` strings sent when connecting to the database.

**Describe alternatives you've considered**
I have looked at the metabase plugin api and searched for compatible drivers.

**How important is this feature to you?**

**Additional context**

**Comment by flamber** [comment]
Hi @jawabuu 
Since I don't know the "unsupported queries" you're referring to, I would guess this is the function that is causing you problems:
https://github.com/metabase/metabase/blob/01e0dc3251eeb3cc8f9e48cdfd1d96c670918459/src/metabase/driver/mysql.clj#L89-L90
It's probably better to ask questions like this in the forum: https://discourse.metabase.com/

**Comment by jawabuu** [comment]
Thanks for the response @flamber .
This is the exact error
` invalid syntax: concat(@@sql_mode, ',STRICT_TRANS_TABLES')`
I'll check out the forum too.

**Comment by flamber** [comment]
@jawabuu It looks like that is being added by the MariaDB Connector/J driver:
https://github.com/MariaDB/mariadb-connector-j/blob/c160500cc2e7eb423c37cc72f2c95151e67954f5/src/main/java/org/mariadb/jdbc/internal/protocol/AbstractConnectProtocol.java#L505-L507
So you should be able to use the additional connection options in Metabase and set the following to disable it:
```
jdbcCompliantTruncation=false
```

**Comment by jawabuu** [comment]
@flamber 
Thank you very much. I am trying it right now.
Successfully added the database, but I have this from the logs;

`metabase_1      | 07-10 06:06:09 ERROR middleware.log :: GET /api/automagic-dashboards/database/4/candidates 500 28 ms (6 DB calls)
metabase_1      | {:message
metabase_1      |  "(conn=3979) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL) AND `active` = TRUE AND (`special_typ
e` in ('type/PK', 'type/FK'))) GROUP ' at line 1",
metabase_1      |  :type java.sql.SQLSyntaxErrorException,
metabase_1      |  :stacktrace
metabase_1      |  ("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)"
metabase_1      |   "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
metabase_1      |   "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
metabase_1      |   "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)"
metabase_1      |   "org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)"
metabase_1      |   "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)"
metabase_1      |   "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:379)"
metabase_1      |   "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
metabase_1      |   "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
metabase_1      |   "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)"
metabase_1      |   "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
metabase_1      |   "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
metabase_1      |   "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
metabase_1      |   "toucan.db$query.invokeStatic(db.clj:274)"
metabase_1      |   "toucan.db$query.doInvoke(db.clj:270)"
metabase_1      |   "clojure.lang.RestFn.invoke(RestFn.java:410)"
metabase_1      |   "--> automagic_dashboards.core$enhance_table_stats.invokeStatic(core.clj:1240)"
metabase_1      |   "automagic_dashboards.core$enhance_table_stats.invoke(core.clj:1217)"
metabase_1      |   "automagic_dashboards.core$candidate_tables.invokeStatic(core.clj:1279)"
metabase_1      |   "automagic_dashboards.core$candidate_tables.invoke(core.clj:1259)"
metabase_1      |   "automagic_dashboards.core$candidate_tables.invokeStatic(core.clj:1269)"
metabase_1      |   "automagic_dashboards.core$candidate_tables.invoke(core.clj:1259)"
metabase_1      |   "api.automagic_dashboards$fn__45598.invokeStatic(automagic_dashboards.clj:59)"
metabase_1      |   "api.automagic_dashboards$fn__45598.invoke(automagic_dashboards.clj:56)"
metabase_1      |   "middleware.auth$enforce_authentication$fn__61677.invoke(auth.clj:14)"
metabase_1      |   "routes$fn__62814$fn__62815.doInvoke(routes.clj:56)"
metabase_1      |   "middleware.exceptions$catch_uncaught_exceptions$fn__61768.invoke(exceptions.clj:104)"
metabase_1      |   "middleware.exceptions$catch_api_exceptions$fn__61765.invoke(exceptions.clj:92)"
metabase_1      |   "middleware.log$log_api_call$fn__63188$fn__63189.invoke(log.clj:170)"
metabase_1      |   "middleware.log$log_api_call$fn__63188.invoke(log.clj:164)"
metabase_1      |   "middleware.security$add_security_headers$fn__61731.invoke(security.clj:105)"
metabase_1      |   "middleware.json$wrap_json_body$fn__62893.invoke(json.clj:61)"
metabase_1      |   "middleware.json$wrap_streamed_json_response$fn__62911.invoke(json.clj:97)"
metabase_1      |   "middleware.session$bind_current_user$fn__60345$fn__60346.invoke(session.clj:193)"
metabase_1      |   "middleware.session$do_with_current_user.invokeStatic(session.clj:176)"
metabase_1      |   "middleware.session$do_with_current_user.invoke(session.clj:170)"
metabase_1      |   "middleware.session$bind_current_user$fn__60345.invoke(session.clj:192)"
metabase_1      |   "middleware.session$wrap_current_user_id$fn__60334.invoke(session.clj:161)"
metabase_1      |   "middleware.session$wrap_session_id$fn__60319.invoke(session.clj:123)"
metabase_1      |   "middleware.auth$wrap_api_key$fn__61685.invoke(auth.clj:27)"
metabase_1      |   "middleware.misc$maybe_set_site_url$fn__63253.invoke(misc.clj:58)"
metabase_1      |   "middleware.misc$bind_user_locale$fn__63256.invoke(misc.clj:74)"
metabase_1      |   "middleware.misc$add_content_type$fn__63241.invoke(misc.clj:30)"
metabase_1      |   "middleware.misc$disable_streaming_buffering$fn__63278.invoke(misc.clj:119)"
metabase_1      |   "middleware.misc$wrap_gzip$fn__63271.invoke(misc.clj:101)"),
metabase_1      |  :sql-exception-chain
metabase_1      |  ["SQLSyntaxErrorException:"
metabase_1      |   "Message: (conn=3979) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL) AND `active` = TRUE AND (`s
pecial_type` in ('type/PK', 'type/FK'))) GROUP ' at line 1"
metabase_1      |   "SQLState: 42000"
metabase_1      |   "Error Code: 1064"]}
`

**Comment by jawabuu** [comment]
@flamber 
MySQL version is **5.7.26**
`Server version: 5.7.26-log MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.
`

**Comment by flamber** [comment]
@jawabuu Without seeing the full error, I wouldn't know what's going on. You might be able to see on it Vitess or setting debug [logging](https://metabase.com/docs/latest/operations-guide/start.html#configuring-logging-level) or using tcpdump (or similar) to check the packages.
Otherwise find another service, as far as I know, Metabase works fine with AWS RDS.

**Comment by jawabuu** [comment]
@flamber 
This happens when exploring the newly added database
http://metabase:300/explore/3/
![image](https://user-images.githubusercontent.com/49921621/60947804-2e128480-a2fa-11e9-9447-34cf5a6c7cad.png)

The query from mysql logs
`
SELECT * FROM `metabase_field` WHERE ((`active` = TRUE AND (NOT (`special_type` in ('type/PK')) OR `special_type` IS NULL) AND `visibility_type` <> 'retired' AND
((`fingerprint_version` < 4 AND (`base_type` in ('type/Quantity', 'type/DruidHyperUnique', 'type/Decimal', 'type/Income', 'type/Boolean', 'type/Time', 'type/Latitude', 'type/Integer', 'type/Author', 'type/Birth
date', 'type/SerializedJSON', 'type/PostgresEnum', 'type/Price', 'type/Source', 'type/Category', 'type/Duration', 'type/Comment', 'type/Special', 'type/Score', 'type/Title', 'type/FK', 'type/JoinTime', 'type/CreationTime', 'type/Enum', 'type/DateTimeWithTZ', 'type/Name', 'type/Number', 'type/Text', 'type/*', 'type/Product', 'type/Address', 'type/UUID', 'type/State', 'type/Dictionary', 'type/Company', 'type/Discount',
 'type/City', 'type/Currency', 'type/Longitude', 'type/UNIXTimestamp', 'type/IPAddress', 'type/Country', 'type/GrossMargin', 'type/BigInteger', 'type/MongoBSONID', 'type/Array', 'type/Cost', 'type/Subscription'
, 'type/Coordinate', 'type/Collection', 'type/Date', 'type/UNIXTimestampSeconds', 'type/URL', 'type/JoinTimestamp', 'type/Float', 'type/UNIXTimestampMilliseconds', 'type/PK', 'type/TextLike', 'type/Email', 'type/DateTime', 'type/CreationDate', 'type/JoinDate', 'type/User', 'type/Share', 'type/Owner', 'type/ZipCode', 'type/ImageURL', 'type/AvatarURL', 'type/CreationTimestamp', 'type/Description'))))) AND `table_id` =
262)
`


The error from metabase logs
`metabase_1      | 07-10 07:02:01 ERROR middleware.log :: GET /api/automagic-dashboards/database/3/candidates 500 33 ms (6 DB calls)
metabase_1      | {:message
metabase_1      |  "(conn=3) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL) AND `active` = TRUE AND (`special_type`
in ('type/PK', 'type/FK'))) GROUP ' at line 1",
metabase_1      |  :type java.sql.SQLSyntaxErrorException,
metabase_1      |  :stacktrace
metabase_1      |  ("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)"
metabase_1      |   "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
metabase_1      |   "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
metabase_1      |   "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)"
metabase_1      |   "org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)"
metabase_1      |   "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)"
metabase_1      |   "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:379)"
metabase_1      |   "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
metabase_1      |   "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
metabase_1      |   "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)"
metabase_1      |   "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
metabase_1      |   "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
metabase_1      |   "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
metabase_1      |   "toucan.db$query.invokeStatic(db.clj:274)"
metabase_1      |   "toucan.db$query.doInvoke(db.clj:270)"
metabase_1      |   "clojure.lang.RestFn.invoke(RestFn.java:410)"
metabase_1      |   "--> automagic_dashboards.core$enhance_table_stats.invokeStatic(core.clj:1240)"
metabase_1      |   "automagic_dashboards.core$enhance_table_stats.invoke(core.clj:1217)"
metabase_1      |   "automagic_dashboards.core$candidate_tables.invokeStatic(core.clj:1279)"
metabase_1      |   "automagic_dashboards.core$candidate_tables.invoke(core.clj:1259)"
metabase_1      |   "automagic_dashboards.core$candidate_tables.invokeStatic(core.clj:1269)"
metabase_1      |   "automagic_dashboards.core$candidate_tables.invoke(core.clj:1259)"
metabase_1      |   "api.automagic_dashboards$fn__45598.invokeStatic(automagic_dashboards.clj:59)"
metabase_1      |   "api.automagic_dashboards$fn__45598.invoke(automagic_dashboards.clj:56)"
metabase_1      |   "middleware.auth$enforce_authentication$fn__61677.invoke(auth.clj:14)"
metabase_1      |   "routes$fn__62814$fn__62815.doInvoke(routes.clj:56)"
metabase_1      |   "middleware.exceptions$catch_uncaught_exceptions$fn__61768.invoke(exceptions.clj:104)"
metabase_1      |   "middleware.exceptions$catch_api_exceptions$fn__61765.invoke(exceptions.clj:92)"
metabase_1      |   "middleware.log$log_api_call$fn__63188$fn__63189.invoke(log.clj:170)"
metabase_1      |   "middleware.log$log_api_call$fn__63188.invoke(log.clj:164)"
metabase_1      |   "middleware.security$add_security_headers$fn__61731.invoke(security.clj:105)"
metabase_1      |   "middleware.json$wrap_json_body$fn__62893.invoke(json.clj:61)"
metabase_1      |   "middleware.json$wrap_streamed_json_response$fn__62911.invoke(json.clj:97)"
metabase_1      |   "middleware.session$bind_current_user$fn__60345$fn__60346.invoke(session.clj:193)"
metabase_1      |   "middleware.session$do_with_current_user.invokeStatic(session.clj:176)"
metabase_1      |   "middleware.session$do_with_current_user.invoke(session.clj:170)"
metabase_1      |   "middleware.session$bind_current_user$fn__60345.invoke(session.clj:192)"
metabase_1      |   "middleware.session$wrap_current_user_id$fn__60334.invoke(session.clj:161)"
metabase_1      |   "middleware.session$wrap_session_id$fn__60319.invoke(session.clj:123)"
metabase_1      |   "middleware.auth$wrap_api_key$fn__61685.invoke(auth.clj:27)"
metabase_1      |   "middleware.misc$maybe_set_site_url$fn__63253.invoke(misc.clj:58)"
metabase_1      |   "middleware.misc$bind_user_locale$fn__63256.invoke(misc.clj:74)"
metabase_1      |   "middleware.misc$add_content_type$fn__63241.invoke(misc.clj:30)"
metabase_1      |   "middleware.misc$disable_streaming_buffering$fn__63278.invoke(misc.clj:119)"
metabase_1      |   "middleware.misc$wrap_gzip$fn__63271.invoke(misc.clj:101)"),
metabase_1      |  :sql-exception-chain
metabase_1      |  ["SQLSyntaxErrorException:"
metabase_1      |   "Message: (conn=3) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL) AND `active` = TRUE AND (`spec
ial_type` in ('type/PK', 'type/FK'))) GROUP ' at line 1"
metabase_1      |   "SQLState: 42000"
metabase_1      |   "Error Code: 1064"]}
metabase_1      |
`

**Comment by flamber** [comment]
@jawabuu That's two different queries. One doesn't contain `GROUP`. You probably need to check the MySQL log for more problems and make sure that you always use the same timestamp, when pulling logs from multiple different servers/services.
Instead of using X-Rays (`/explore/X`), just use "Ask a question" to see if there's access to data.
If you can ask questions, then this issue is resolved and you should open a new issue about X-Rays.

**Comment by jawabuu** [comment]
Thanks. Let me open a new issue.

**Comment by ans-4175** [comment]
@jawabuu is this already resolved or which issue tracked down from this?

**Comment by jawabuu** [comment]
Hey @ans-4175 In terms of the unsupported query, you can set
`jdbcCompliantTruncation=false` to resolve.
but using vitess with vtgate is still sub-optimal, you will need to use passthrough mode
https://github.com/vitessio/vitess/issues/5166
https://github.com/vitessio/vitess/pull/6034

**Comment by ans-4175** [comment]
What is `passthrough mode` @jawabuu ?
Is it work on your setup?
I think I am facing similar situation with you, trying to use Vitess(mysqls-mysqls) for BI DataSource that scale.

**Comment by jawabuu** [comment]
You will need the following additional-jdbc-options on the UI
`jdbcCompliantTruncation=false`
You will also need to add your database  as
`<db_name>:<shard>@<type>`
Example For an unsharded keyspace
`db_name:0@rdonly`
