### ISSUE TITLE
Include current [period] option un-checks itself on any change

### ISSUE THREAD

**Issue by tristang** [metabase/metabase#10322]
**Describe the bug**
The checkbox to _Include current day/week/month/year_ unchecks itself whenever any of the filter conditions change. 

**Logs**
N/A

**To Reproduce** 
1. Add a filter based on a timestamp column such as "Created at, Previous, 30, Days"
2. Check the box to "Include today".
3. Change the range from 30 to any other number
4. Blur that field
5. Checkbox for "Include today" will automatically uncheck itself

**Expected behavior**
Checkbox for current period remains checked until unchecked by the user.

**Screenshots**
https://www.loom.com/share/79a55713345a47afb16825531adc8cc5 

**Information about your Metabase Installation:**
- Your browser and the version: Google Chrome 68.0.3440.75 (Official Build) beta (64-bit)
- Your operating system: Linux
- Your databases: Postgres
- Metabase version: v0.32.3
- Metabase hosting environment: Heroku
- Metabase internal database: Unsure

**Severity**
Minor UX annoyance.

**Additional context**
I love Metabase.

**Comment by flamber** [comment]
Hi @tristang Looks like a duplicate of #10249 - just a note, latest release is 0.32.9

**Comment by tristang** [comment]
Thanks @flamber. I searched but somehow missed it.
