### ISSUE TITLE
Field Settings Formatting on URL "Link Text" needs de-bounced save

### ISSUE THREAD

**Issue by ryrobes** [metabase/metabase#10328]
Link Text box saves on each keystroke and (typing normally) misses chars. Need to de-bounce the save. Super low priority, but will certainly irritate / confuse users who don't understand what is happening.

![image](https://user-images.githubusercontent.com/757387/61024052-3f42ac00-a361-11e9-8b60-b6091783fb9b.png)

**Comment by walterl** [comment]
This behaviour changed as part of #9592. Changes are now saved `onBlur`.

New behaviour is inconsistent with other inputs, and that is tracked in #10462.
