### ISSUE TITLE
Ability to hide and rename schemas in Data Model (if wanted) or explicitly default to one

### ISSUE THREAD

**Issue by ryrobes** [metabase/metabase#10329]
Unsure how often this is an issue for others - but in DB Conns that have multiple queryable schemas they will always all be shown (minus the internal ones) in the browse flow. This can get in the way of discover-ability a bit when browsing, since it feels like a sudden "non-curated step" in the middle of other obviously "human curated steps" (odd way to put it).

Forcing a Data connection to only use ONE schema would also be a solution, since the "builder" knows that her/his users won't potentially hit that step and be confused.

This is very dependent on how you data is organized, obviously. But when it *is* an issue, it's an unavoidable one.

Another low-pri, but curious if it's just me.

**Comment by flamber** [comment]
Hi @ryrobes Is this different from #2086?

**Comment by ryrobes** [comment]
> Hi @ryrobes Is this different from #2086?

Ah. Nope. Will do the needful, thanks.
