### ISSUE TITLE
Field filters on columns with no available widgets

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#10334]
When you create a new field filter in the SQL editor, you're able to pick which field to map it to from all fields in the current database.

<img width="274" src="https://user-images.githubusercontent.com/691495/61091414-16c5bb00-a410-11e9-8757-299a4e21db26.png">

However, if it's a type where we don't have any available widgets, that "Filter widget type" drop down is hidden. (Ratings here is a "Score" rather than "Category" in the datamodel.)

<img width="275" src="https://user-images.githubusercontent.com/691495/61091411-14636100-a410-11e9-9dd9-19dbd4f8cc77.png">

We document this behavior [here](https://metabase.com/docs/latest/users-guide/13-sql-parameters.html):
> Note: If you’re not seeing the option to display a filter widget, make sure the mapped field is set to one of the above types, and then try manually syncing your database from the Databases section of the Admin Panel to force Metabase to scan and cache the field’s values.

Even though we document it, it's confusing. I think this issue is expected behavior according to the docs: https://github.com/metabase/metabase/issues/8800

Some options:
1. Don't show every field in the "Field to map to" dropdown. Only show fields that have available widgets.
2. Let users select any field, but alert them that there are no available widgets. This could just be displaying a message instead of the dropdown.
3. Add more filter widgets. If we add a few more filter widgets (text, number, etc), it seems like every type could have a corresponding widget.

**Comment by flamber** [comment]
Great idea. My take after many forum posts about this:
1. That wouldn't solve anything, it would just make people ask why a specific column isn't available.
2. Probably the fastest solution. Very short text with a link to docs.
3. Probably the most extensive solution. Would require expanding the dashboard filter selector too, but would then allow filtering a numeric column like Score (there's an issue on adding Number as a filter option, but I cannot find it)
