### ISSUE TITLE
how can I access metabase without the port number?

### ISSUE THREAD

**Issue by alihaider1793** [metabase/metabase#10331]
metabase is running on the 8086 port right now. How can I access it without the port number via apache virtualhost i.e. mymetabase.test?

**Comment by flamber** [comment]
Hi @alihaider1793 
Yes, it's possible with Apache virtualhost `mymetabase.test:80` using reverse proxy to `localhost:8086`.
I haven't used Apache for many years, but this tutorial should but you on the right track:
https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
