### ISSUE TITLE
Cannot sync new postgres database

### ISSUE THREAD

**Issue by ConnorBarnhill** [metabase/metabase#10333]
**Describe the bug**
When creating a new postgres database, the sync fails.

**Logs**
07-11 17:04:00 ERROR events.sync-database :: Error syncing Database: 146 #error {
:cause A ResourcePool could not acquire a resource from its primary factory or source.
:via
[{:type java.sql.SQLException
:message Connections could not be acquired from the underlying database!
:at [com.mchange.v2.sql.SqlUtils toSQLException SqlUtils.java 118]}
{:type com.mchange.v2.resourcepool.CannotAcquireResourceException
:message A ResourcePool could not acquire a resource from its primary factory or source.
:at [com.mchange.v2.resourcepool.BasicResourcePool awaitAvailable BasicResourcePool.java 1319]}]
:trace
[[com.mchange.v2.resourcepool.BasicResourcePool awaitAvailable BasicResourcePool.java 1319]
[com.mchange.v2.resourcepool.BasicResourcePool prelimCheckoutResource BasicResourcePool.java 557]
[com.mchange.v2.resourcepool.BasicResourcePool checkoutResource BasicResourcePool.java 477]
[com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool checkoutPooledConnection C3P0PooledConnectionPool.java 525]
[com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource getConnection AbstractPoolBackedDataSource.java 128]
[clojure.java.jdbc$get_connection invokeStatic jdbc.clj 298]
[clojure.java.jdbc$get_connection invoke jdbc.clj 193]
[metabase.driver.generic_sql$describe_database invokeStatic generic_sql.clj 412]
[metabase.driver.generic_sql$describe_database invoke generic_sql.clj 409]
[metabase.driver$fn__22486$G__22452__22493 invoke driver.clj 45]
[metabase.sync_database.introspect$db__GT_tables invokeStatic introspect.clj 188]
[metabase.sync_database.introspect$db__GT_tables invoke introspect.clj 187]
[metabase.sync_database.introspect$introspect_database_and_update_raw_tables_BANG_ invokeStatic introspect.clj 204]
[metabase.sync_database.introspect$introspect_database_and_update_raw_tables_BANG_ invoke introspect.clj 198]
[metabase.sync_database$sync_database_with_tracking_BANG_$fn__30875 invoke sync_database.clj 78]
[metabase.sync_database$sync_database_with_tracking_BANG_ invokeStatic sync_database.clj 75]
[metabase.sync_database$sync_database_with_tracking_BANG_ invoke sync_database.clj 69]
[clojure.core$partial$fn__4763 invoke core.clj 2528]
[metabase.driver$fn__22710 invokeStatic driver.clj 252]
[metabase.driver$fn__22710 invoke driver.clj 252]
[metabase.driver$fn__22659$G__22442__22668 invoke driver.clj 45]
[metabase.sync_database$sync_database_BANG_ invokeStatic sync_database.clj 44]
[metabase.sync_database$sync_database_BANG_ doInvoke sync_database.clj 25]
[clojure.lang.RestFn invoke RestFn.java 410]
[metabase.events.sync_database$process_sync_database_event$fn__45970 invoke sync_database.clj 31]
[clojure.core$binding_conveyor_fn$fn__4676 invoke core.clj 1938]
[clojure.lang.AFn call AFn.java 18]
[java.util.concurrent.FutureTask run FutureTask.java 266]
[java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
[java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
[java.lang.Thread run Thread.java 745]]}

**To Reproduce**
Create a postgres database version server 11.3 (Debian 11.3-1.pgdg90+1)
Add database through console
Look at metabase logs

**Expected behavior**
The database connection to succeed

**Information about your Metabase Installation:**
- Your databases: Postgres 11.3 (Debian 11.3-1.pgdg90+1)

- Metabase version: v0.25.2

- Metabase hosting environment: Docker/Kubernetes

**Severity**
Blocking crucial database migration

**Comment by flamber** [comment]
Hi @ConnorBarnhill 
Metabase version 0.25.2 is almost two years old. The latest release is 0.32.9.
Make sure to backup before upgrading.

**Comment by ConnorBarnhill** [comment]
Thanks @flamber. Downgrading to postgres 9 fixed. Will look into upgrading metabase as well.
