### ISSUE TITLE
No schemas / tables / collection found for MongoDB 4 (Atlas) 

### ISSUE THREAD

**Issue by antony** [metabase/metabase#10343]
**Describe the bug**
I've connected a new, dockerised version of Metabase to a MongoDB Atlas Sandbox with a read-only user. The dataset is small, with 6 collections - there is less than 5mb of data in total.

The connection succeeds and the database is connected.

Scanning tables manually / syncing manually, or automatically, all result in no tables found - empty dataset. It can't see any of my collections.

**Logs**

The result of any sync/analyze is as follows:

```
07-13 09:50:00 INFO sync.util :: STARTING: Sync metadata for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: STARTING: step 'sync-timezone' for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: FINISHED: step 'sync-timezone' for mongo Database 2 'Byk Production' (260 µs)
07-13 09:50:00 DEBUG sync.util :: STARTING: step 'sync-tables' for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: FINISHED: step 'sync-tables' for mongo Database 2 'Byk Production' (371 ms)
07-13 09:50:00 DEBUG sync.util :: STARTING: step 'sync-fields' for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: FINISHED: step 'sync-fields' for mongo Database 2 'Byk Production' (2 ms)
07-13 09:50:00 DEBUG sync.util :: STARTING: step 'sync-fks' for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: FINISHED: step 'sync-fks' for mongo Database 2 'Byk Production' (1 ms)
07-13 09:50:00 DEBUG sync.util :: STARTING: step 'sync-metabase-metadata' for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: FINISHED: step 'sync-metabase-metadata' for mongo Database 2 'Byk Production' (20 ms)
07-13 09:50:00 DEBUG sync.util :: 
#################################################################
# Completed sync on Byk Production
# Start: 2019-07-13T09:50:00.487Z
# End: 2019-07-13T09:50:00.893Z
# Duration: 406 ms
# ---------------------------------------------------------------
# Completed step 'sync-timezone'
# Start: 2019-07-13T09:50:00.487Z
# End: 2019-07-13T09:50:00.488Z
# Duration: 1000 µs
# Found timezone id null
# ---------------------------------------------------------------
# Completed step 'sync-tables'
# Start: 2019-07-13T09:50:00.488Z
# End: 2019-07-13T09:50:00.866Z
# Duration: 378 ms
# Total number of tables sync'd 0, number of tables updated 0
# ---------------------------------------------------------------
# Completed step 'sync-fields'
# Start: 2019-07-13T09:50:00.866Z
# End: 2019-07-13T09:50:00.869Z
# Duration: 3 ms
# Total number of fields sync'd null, number of fields updated null
# ---------------------------------------------------------------
# Completed step 'sync-fks'
# Start: 2019-07-13T09:50:00.869Z
# End: 2019-07-13T09:50:00.872Z
# Duration: 3 ms
# Total number of foreign keys sync'd 0, 0 updated and 0 tables failed to update
# ---------------------------------------------------------------
# Completed step 'sync-metabase-metadata'
# Start: 2019-07-13T09:50:00.872Z
# End: 2019-07-13T09:50:00.893Z
# Duration: 21 ms
#################################################################

07-13 09:50:00 INFO sync.util :: FINISHED: Sync metadata for mongo Database 2 'Byk Production' (778 ms)
07-13 09:50:00 DEBUG sync.util :: Sync operations in flight: {:analyze #{2}}
07-13 09:50:00 INFO sync.util :: STARTING: Analyze data for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: STARTING: step 'fingerprint-fields' for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: FINISHED: step 'fingerprint-fields' for mongo Database 2 'Byk Production' (285 µs)
07-13 09:50:00 DEBUG sync.util :: STARTING: step 'classify-fields' for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: FINISHED: step 'classify-fields' for mongo Database 2 'Byk Production' (150 µs)
07-13 09:50:00 DEBUG sync.util :: STARTING: step 'classify-tables' for mongo Database 2 'Byk Production'
07-13 09:50:00 DEBUG sync.util :: FINISHED: step 'classify-tables' for mongo Database 2 'Byk Production' (123 µs)
07-13 09:50:00 DEBUG sync.util :: 
#################################################################
# Completed analyze on Byk Production
# Start: 2019-07-13T09:50:00.936Z
# End: 2019-07-13T09:50:00.938Z
# Duration: 2 ms
# ---------------------------------------------------------------
# Completed step 'fingerprint-fields'
# Start: 2019-07-13T09:50:00.936Z
# End: 2019-07-13T09:50:00.937Z
# Duration: 1000 µs
# Fingerprint updates attempted null, updated null, no data found null, failed null
# ---------------------------------------------------------------
# Completed step 'classify-fields'
# Start: 2019-07-13T09:50:00.937Z
# End: 2019-07-13T09:50:00.937Z
# Duration: 0 ns
# Total number of fields classified 0, 0 failed
# ---------------------------------------------------------------
# Completed step 'classify-tables'
# Start: 2019-07-13T09:50:00.937Z
# End: 2019-07-13T09:50:00.938Z
# Duration: 1000 µs
# Total number of tables classified 0, 0 updated
#################################################################

07-13 09:50:00 INFO sync.util :: FINISHED: Analyze data for mongo Database 2 'Byk Production' (24 ms)
```

**To Reproduce**
1. Add and connect a Mongo database
1. Click either sync button, or just hit save and examine your dataset
2. Dataset is empty, no tables found.

**Expected behavior**
I would expect to see my five collections.

**Screenshots**
![Screenshot from 2019-07-13 11-51-06](https://user-images.githubusercontent.com/218949/61170668-96649e80-a564-11e9-8daa-333fdca7d952.png)

**Information about your Metabase Installation:**
- Chrome Version 75.0.3770.100 (Official Build) (64-bit)

- Ubuntu Linux 19.04

- MongoDB (Atlas) / MongoDB 4.0.10

- Metabase version: Replicated with 0.32.9, 0.33-preview1,  0.33-preview2

- Metabase hosting environment: Local Docker - Server Version: 18.09.7

- Metabase internal database: h2 (Default)

**Severity**
Critical - I can't see any of my data, and I can't work around it.

**Comment by antony** [comment]
My current workaround for this is to clone my database into a local, single mongo instance. Obviously this isn't possible for medium or large datasets, and is quite infra-intensive.

However this does confirm that the current and proposed metabase mongo connectivity is broken when used with Atlas.

**Comment by zzaacchh** [comment]
I, too, am experiencing this same behavior.

**Comment by zzaacchh** [comment]
I think I have new finding that relates to this issue.  If I attempt to set up a connection with the authentication database set to *anything other* than admin, I get a blank schema.  If I set the authentication database to admin, I get the following log4j DEBUG log message (which required manually running the jar with special log config to extract):

```
10-17 21:41:00 ERROR driver.mongo :: Error introspecting collection: system.keys #error {
:cause Query failed with error code 13 and error message ‘not authorized on admin to execute command { find: “system.keys”, $db: “admin”, $clusterTime: { clusterTime: Timestamp(1571362852, 1), signature: { hash: BinData(0, F6D61EC48D507A25BE7F88585E0D52DDE228AA90), keyId: 6747849726067998721 } }, lsid: { id: UUID(“5fb7b44a-c109-4d1f-954c-b01acce7a11d”) } }’ on server ssi-server-cfbsa-shard-00-00-joztm.mongodb.net:27017
```

I suspect this means that Atlas is somehow advertising some of its internal, private structures as collections, and Metabase is attempting to scan them as possible sources of data, and is stopping when it gets an authorization error from Atlas.

**Comment by n7best** [comment]
I'm having the same issues, my current work around is connecting to the primary shard directly but somehow it only works with the initial setup page with this method (not the database configuration page).

**Comment by alessandrocentanni** [comment]
I've managed to show results/schemas by leaving "Authentication Database" empty and having the following additional Mongo connection string options.
`retryWrites=true&w=majority&authSource=admin&readPreference=secondary`

**Comment by antony** [comment]
@alessandrocentanni do you have the full settings you use for connecting to Atlas?

I am stilll having the same issue even with your configuration - no schemas or collections shown.

**Comment by alessandrocentanni** [comment]
My Metabase was actually already connected to a MongoDB server which wasn't hosted on Atlas, and it was working well. I found the same issue while moving to Atlas (M2 cluster /w Replica Set - 3 nodes) and editing the current database information into the Metabase admin's dashboard. At first, I used pretty much the same settings you would use for a normal connection taken from the query string.

`mongodb+srv://<user>:<password>@<host>/<db>`

I changed the settings with those taken from the query string, I included the authentication database, checked the DNS SRV option and left Additional Mongo connection string options empty. 
My database user has _readWriteAnyDatabase_ privileges and I'm using SCRAM as the authentication method. No SSH tunnel used.

At that point, I had the same issue - no error but no schemas or collections shown.
That's when I simply left the authentication database field empty and added that extra connection string option. 
** authSource ** is basically what you'd put in the authentication database (admin by default I think), so in case some of you don't have 'admin' as a database for the user's credentials, then you'd have to change it with the corresponding one. 

I am also currently whitelisting any IP on Atlas ( 0.0.0.0/0 ), just to be sure.

**Comment by lazarohcm** [comment]
Same here. 
Also, whenever I try to save the config, without typing again the password, I get this error 
`Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='privilee', source='admin', password=<hidden>, mechanismProperties={}}`

Not sure if it is related

**Comment by lazarohcm** [comment]
Same here.
Also, whenever I try to save the config, without typing again the password, I get this error

`Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='<USER>', source='admin', password=<hidden>, mechanismProperties={}}`

Not sure if it is related

**Comment by Songkeys** [comment]
@alessandrocentanni leaving the authentication database field empty saved me! thanks!

**Comment by alexnavis** [comment]
Follow what @alessandrocentanni has mentioned. The trick which worked was moving from 'admin' role to user with 'readWriteAnyDatabase' role worked.

**Comment by antony** [comment]
Just for some extra information - none of the above solutions work fof me, and if I do manage to connect and then go to scan tables, I can't even connect any more:

```
Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='xxx', source='admin', password=<hidden>, mechanismProperties={}}
```

something very wrong here.

**Comment by StanBoyet** [comment]
I'm sorry but this issue is the "main" one apparently (others refer to it) and it's dormant even though the issue persists.
Same as Antony, nothing mentioned works for me even though -- at some point -- it did.

**Comment by paoliniluis** [comment]
For everyone seeing this issue, please upgrade to the latest version (both Metabase and if possible Mongo Atlas), and let us know if it keeps happening. Thanks!

**Comment by tschut** [comment]
I'm running into the same thing with a MongoDB hosted on digitalocean. I'm assuming setup is similar to atlas. I see the same error in the logs (`not authorized on admin to execute command { find: "system.keys",` ...)

I'm on latest metabase v0.40.2. Tried setting the authSource, but metabase didn't seem to pick it up correctly and instead try to auth on the actual database instead of admin.

**Comment by darkamenosa** [comment]
I faced this problem 2 days ago. I copied the connection string from Mongo Atlas.
It is something like this: `mongodb+srv://<username>:<password>@tn-dashboard-dev.sth05.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`

I put correct username + password, and change network to public: `0.0.0.0/0`. But tables showed on my Metabase.

I changed `myFirstDatabase` to my database name (it was `business`). Then it worked like a charm. So when you face this issue, please ensure your database name is correct.

**Comment by StorkZ** [comment]
Hi,
@tschut did you resolve this problem somehow? 
I am using the newest Metabase (0.40.4) and fresh digitalocean mongodb instance.

**Comment by luizarakaki** [comment]
I couldn't repro this. I'm connecting to a MongoDB instance in Atlas without any problems.

If people are facing problems with other providers (like DigitalOcean), I ask you to open a new issue with details about your case.
