### ISSUE TITLE
504 Gateway Time-out because of 100 % of CPU is in use

### ISSUE THREAD

**Issue by bkowshik** [metabase/metabase#10346]
- Docker version: `metabase/metabase:v0.32.9`

👋 I setup Metabase on Amazon Beanstalk yesterday following the official documentation. It's been a very enjoyable last couple of hours exploring the different aspects of Metabase and setting things up.

- https://metabase.com/docs/v0.12.0/operations-guide/running-metabase-on-elastic-beanstalk.html

But, all of a sudden, I see a `504 Gateway Time-out` on all Metabase pages, even the homepage. And when I look at the Elastic Beanstalk health logs, I see the following two messages:
- Process default has been unhealthy for 37 minutes (Target.Timeout)
- 100 % of CPU is in use

## Questions
- Why could this have happened, links to any related material will be helpful
- What needs to be done to get Metabase up & running once again

**Comment by flamber** [comment]
Hi @bkowshik 
First, I would say that you should remove it and start over with the documentation matching your version: https://metabase.com/docs/v0.32.9/operations-guide/running-metabase-on-elastic-beanstalk.html
Do you see any errors in the EB application log that could hint at what's going on?

**Comment by bkowshik** [comment]
Ahhhh @flamber looks like posted the wrong link. I did follow the steps outlined here:
- https://metabase.com/docs/v0.32.9/operations-guide/running-metabase-on-elastic-beanstalk.html

Followed the initial steps here to view the EB application logs and I see the lines below. Not sure if these are helpful enough. Where else should I be looking?
- https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.logging.html

#### `/var/log/nginx/error.log`

> 2019/07/14 13:50:23 [error] 4681#0: *8159 upstream timed out (110: Connection timed out) while connecting to upstream, client: IP address, server: , request: "GET / HTTP/1.1", upstream: "http://IP address:3000/", host: "hostname"

#### `/var/log/docker`

> time="2019-07-13T21:55:43Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1" 

#### `/var/log/eb-activity.log`

>   jq: error (at <stdin>:13): Cannot iterate over null (null)

**Comment by flamber** [comment]
@bkowshik 
Okay, so you don't have any `/var/log/metabase` log? Then it seems like the application doesn't even get started. Not sure what's going on, if you used the Quick Launch and followed the guide.

**Comment by bkowshik** [comment]
In the `Request Logs` section, I downloaded the `Full logs`. I see the following files in the dump.

<img width="1245" alt="Screenshot 2019-07-15 at 11 38 37" src="https://user-images.githubusercontent.com/2899501/61197974-305b5100-a6f5-11e9-86de-6a572f68c27c.png">

**Comment by bkowshik** [comment]
Closing here. Will create a fresh Beanstalk setup and try again.
