### ISSUE TITLE
How to apply conditional formatting with two ranges?

### ISSUE THREAD

**Issue by gajus** [metabase/metabase#10344]
I have a column with a desired value being 10.

* Values less than 10 should fade into red.
* Values more than 10 should fade into red.

Since there is no gradient with midpoint, I am trying to create two rules:

<img width="414" alt="Screenshot 2019-07-13 at 14 07 55" src="https://user-images.githubusercontent.com/973543/61172074-acc82580-a577-11e9-8505-846034846d93.png">

and

<img width="409" alt="Screenshot 2019-07-13 at 14 08 47" src="https://user-images.githubusercontent.com/973543/61172084-c1a4b900-a577-11e9-83b8-da29f7486f4c.png">

However, instead of achieving a gradient with a midpoint, the last rule overrides the former.

How to achieve a gradient with a midpoint using conditional formatting?

**Comment by salsakran** [comment]
@gajus this is the wrong forum to ask questions on how to use Metabase. Please post questions like this to our user discussion forum (discourse.metabase.com)
