### ISSUE TITLE
Insecure scripts warning

### ISSUE THREAD

**Issue by anton-khodak** [metabase/metabase#10349]
**Describe the bug**
Chrome displays "Insecure content blocked" warning trying to download data from a question in an iframe. Once insecure scripts are allowed, the whole website that contains the frame becomes insecure. 

Further investigation shows that the problem is in the download form: although the frame is loaded through https, the download form uses http:
```
<form method="GET" action="http://metabase.cellgeni.sanger.ac.uk/public/question/a0520869-7fb6-4ca1-b5a1-829bebe61cd0.json">
...
```

**Logs**

```
// Once the page is loaded
GET https://metabase.cellgeni.sanger.ac.uk/api/user/current 401 (Unauthorized)
```
```
// When clicked on the download button 
Mixed Content: The page at 'https://cellgeni.readthedocs.io/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://metabase.cellgeni.sanger.ac.uk/public/question/a0520869-7fb6-4ca1-b5a1-829bebe61cd0.csv'. This endpoint should be made available over a secure connection.
```

**Expected behavior**
The download form uses the same protocol as the source, if the source is https, downloads should go through https

**Screenshots**

Insecure scripts warning
![image](https://user-images.githubusercontent.com/10351924/61217879-969d9f00-a708-11e9-9de3-96699a296fae.png)

Form has an http endpoint
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10351924/61220087-7a503100-a70d-11e9-9df5-91b7d7f4e6e4.png">

...but it's loaded from an https website
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/10351924/61220117-8b993d80-a70d-11e9-9b32-942bec73a438.png">

**Information about your Metabase Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

Chrome Version 75.0.3770.100 (Official Build) (64-bit)

- Your operating system: (e.x. OS X 10, Windows XP, etc)

macOS High Sierra v10.13.6

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)

MyS

- Metabase version: (e.x. 0.19.3)

v0.32.9

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)

Kubernetes (Docker container)

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

Default

**Severity**

This invalidates https certificate thus makes our domain appear insecure to users. On Firefox though, it doesn't issue a warning, it just doesn't react on a button click, so downloads are impossible.

**Comment by flamber** [comment]
Hi @anton-khodak 
Since it doesn't seem like your Metabase is public, so I cannot see what's going on, but have you configured `https://metabase.cellgeni.sanger.ac.uk` as Site URL in Admin > Settings > General?
I'm guessing you're using the LE wildcard certificate for `cellgeni.sanger.ac.uk`?

**Comment by anton-khodak** [comment]
Hi @flamber , yes, the site URL was the issue, changing it to https worked. Thank you so much!
