### ISSUE TITLE
Loading indicator on main page perpetually spins.

### ISSUE THREAD

**Issue by dvanrijswijk** [metabase/metabase#10356]
**Describe the bug**
Upon logging in to Metabase, the main page includes a loading indicator that spins forever.

**To Reproduce**
1. Open the instance in any web browser
2. Log in to the system
3. The spinning loading indicator appears and continues spinning forever

**Expected behavior**
Whatever underlying process it is indicating is loading should finish and the spinning indicator should dissappear.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/10403194/61321264-26128300-a7d9-11e9-90e1-15a593382b1e.jpg)

Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Experienced on:
IE 11.0.9600.19377
Iron Version 69.0.3600.0 (Official Build) (32-bit)
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

Your operating system: (e.x. OS X 10, Windows XP, etc)
Windows 7

Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres 9.6

Metabase version: (e.x. 0.19.3)
0.32.9

Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Ubuntu 16.04.6 LTS

Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Postgres

**Severity**
No severity. Just peculiar.

**Comment by flamber** [comment]
Hi @dvanrijswijk 
Without seeing your browser console, you're most likely seeing the error `Minified React error #143` 
If yes, then it's a duplicate of #10191

**Comment by dvanrijswijk** [comment]
![image](https://user-images.githubusercontent.com/10403194/61323293-991df880-a7dd-11e9-9ed4-c52da0fd93c1.png)

**Comment by flamber** [comment]
Then yes, it's a duplicate and the fix is already part of next release. Please close this issue :+1:

**Comment by dvanrijswijk** [comment]
Thank you for making the connection @flamber.  
I've implemented the work around suggested in the other issue, resolving this.
