### ISSUE TITLE
Unable to get API session token

### ISSUE THREAD

**Issue by cshort-easyagile** [metabase/metabase#10359]
I followed the Authorizing instructions at https://github.com/metabase/metabase/wiki/Using-the-REST-API

However I keep getting a 400 error: username value must be a non-blank string. Here is the curl command I'm using. Am I missing something here? Majority of our accounts are via google auth but we created a separate account with the same domain with a username/password for API access.

curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"email": "email@email.com", "password": "mypassword"}' \
  https://url/api/session

**Comment by flamber** [comment]
Hi @cshort-easyagile 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It's because you're sending `email` and not `username` - example from instructions:
```
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"username": "cam@metabase.com", "password": "myPassword"}' \
  http://localhost:3000/api/session 
```
