### ISSUE TITLE
How to query for either one of the variable among two optional variables...

### ISSUE THREAD

**Issue by janakivanka** [metabase/metabase#10357]
Hi,

I have to run a query with two variables, both are not mandatory,but either one is required to run the query.
For Example: select * from employee, here we have two variables set emp_id and emp_city both are set as not required. How to run the query only if either of the variable is present.

**Comment by flamber** [comment]
Hi @janakivanka 
You can make use of [Optional Clauses](https://metabase.com/docs/latest/users-guide/13-sql-parameters.html#optional-clauses) (if you're not using Field Filters):
```
SELECT * FROM table
WHERE 1=1
[[AND emp_id={{filter1}}]]
[[AND emp_city={{filter2}}]]
AND COALESCE([[{{filter1}}, ]][[{{filter2}}, ]]NULL) IS NOT NULL
```
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by mbvictoria** [comment]
Closing - answered/redirected to Discourse.
