### ISSUE TITLE
Can I delete data on public.query table on PostgreSQL metadata

### ISSUE THREAD

**Issue by dungngo2912** [metabase/metabase#10369]
hi,
Currently, we have 3M rows (~10GB stored) on the `public.query table`. Can I delete data on this table? 
I just truncated history data on table `query_execution` allow issue [4155](https://github.com/metabase/metabase/issues/4155) and then I want to do it with table `query`hn
Please help me. Thank!!!

**Comment by flamber** [comment]
@dungngo2912 Can we keep the conversation in one place?
https://discourse.metabase.com/t/can-i-delete-data-on-query-table/6568
Please close this issue.
