### ISSUE TITLE
Embedding entire metabase app to other application

### ISSUE THREAD

**Issue by ddey-71** [metabase/metabase#10362]
As per the documentation given in https://metabase.com/docs/latest/enterprise-guide/full-app-embedding.html entire interactive metabase app can be embedded using the option "**Embedding the entire metabase app**" under Settings, “Embedding in other applications” tab. 
 
However, in v0.32.9 jar i don't see any such options. I can see only the below options:
![image](https://user-images.githubusercontent.com/52992504/61352852-0720f900-a88c-11e9-8f43-10daa8101064.png)

Can someone help me please? New to metabase..

**Comment by flamber** [comment]
Hi @ddey-71 
You need to use the Enterprise Edition, which is a different download than the Open Source:
https://metabase.com/docs/latest/enterprise-guide/activating-the-enterprise-edition.html
You can read more about Enterprise Edition on https://metabase.com/enterprise/

**Comment by mbvictoria** [comment]
Closing - answered.
