### ISSUE TITLE
Is there a way to disable the Scheduler?

### ISSUE THREAD

**Issue by wkk1020** [metabase/metabase#10368]
Hello! I would like to know if there's a way to disable the Scheduler? Say I have two Metabase installation at different sites, and would like to disable the Scheduler to avoid Pulses being executed at the DR site at normal time.

Thank you!

Regards,
Mike Yeap

**Comment by vi-vsn** [comment]
Just an idea for you to work around your problem - consider null-routing your SMTP (or Slack if you use that) servers via /etc/hosts entries in DR.

**Comment by wkk1020** [comment]
I see..... I was looking for a way to disable the schedule at the configuration level. But thanks a lot for the workaround!

**Comment by salsakran** [comment]
Closing as we don't have this option and this kind of low level control isn't on our roadmap for the foreseeable future.
