### ISSUE TITLE
Allow an array of manually entered values for SQL Variables

### ISSUE THREAD

**Issue by ryrobes** [metabase/metabase#10363]
Fairly self-explanatory. Would be nice to have an option of SQL params to provide a simple array of values for drop-down population (*not* type ahead). This opens up some clever and arbitrary uses for static params that are currently difficult.

Simple Ex.  ` [[order by {{order_field}} {{dir}} ]]`

Variable UI somewhere:
order_field =` ["upvotes", "downvotes", "issues"]`
dir = `["asc", "desc"]`

Also Interesting: Allowing the value of a dynamic Question to power this list (would help #4509 as well).
The allowable values would be Question-1234 or `select distinct region from sales;` etc. 'Field Filter' somewhat covers that, albeit in a specific way that isn't really applicable to the above example, I don't believe.

**Comment by flamber** [comment]
Sounds very similar to #5445 - or maybe #5245?

**Comment by flamber** [comment]
Closing in favor of #5245
Related to #6820 and #7605
