### ISSUE TITLE
Fixed width dashboard option

### ISSUE THREAD

**Issue by ryrobes** [metabase/metabase#10364]
Simply put, at times the auto-resizing tends to result in dashboards looking very inconsistent in other browser sizes - somewhat negating any effort put into layout + polish. Different viz types tend to resize in sub-optimal ways (hiding axes, labels, counts having more white-space than actual data ink, overlapping labels, grid columns get hidden with no padding, shrinking the viz but leaving huge text, etc).

No fault of the widgets, fluid and legible resizing (w/o being ugly) is a non-trivial problem with a deep rabbit hole of gotchas.

However, a simple solution would be to **allow me to optionally set a fixed (pixel) width** so the size of my dashboard "blocks" never change and I'm confident that it *will look as close to 1:1 as I designed it to*.

**For delivering reports and dashboards to Executives this is esp important.** I would never leave that rendering to chance.... and you can't get away with a PDF anymore. ; ) 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by notrom** [comment]
@ryrobes how would you get PDF from a Metabase dashboard? This is something I'd like to do at times but haven't come up with what I'd call a sensible approach yet.

**Comment by cdeweyx** [comment]
@ryrobes We are working on this feature now and I have an update to share. Below is a loom showing off how we're thinking about implementing this. Would love to hear your thoughts on:
* Does the solution match address the problem?
* Are there concerns about making fixed-width dashboards the new default?
* We're thinking this is a editorial decision made per-dashboard by the creator within "Edit mode" where you can choose between a fixed-width or autoscaling as is the current behavior. How does that sound?
* Would you want the width to be configurable or is a standard value fine? e.g. we could potentially add a "Custom" option where you can input X% or Xpx instead.

https://www.loom.com/share/67ba500da7e14d14877f7037be9702d8?sid=250fef1a-2abe-459b-a860-07fafd9ad41d

**Comment by RaphaelKimmig** [comment]
This would be very helpful for us to increase the usefulness of the pdf export feature. The changing widths and resulting changes in displayed information make it hard to prepare a dashboard that is easy to export to pdf.

**Comment by cdeweyx** [comment]
> This would be very helpful for us to increase the usefulness of the pdf export feature. The changing widths and resulting changes in displayed information make it hard to prepare a dashboard that is easy to export to pdf.

Great point!

**Comment by L120Git** [comment]
> Ahora .. . . . . . . . . . . . . . . . . . A continuación se muestra una telar de cómo estamos pensando en esto. Me encantaría oír tus pensamientos sobre:
> 
>     * La siguiente solución aborda el problema?
> 
>     * Hay preocupaciones sobre el hecho de paneles fijos el nuevo default?
> 
>     * Estamos pensando que esta es una decisión editorial tocida por el creador dentro del "modo de edición donde" se puede elegir entre un ancho fijo o autoescalado como es el comportamiento real. Cómo suena eso?
> 
>     * Quieres que el ancho mar configurable o es una multa de valor estándar? por ejemplo, podríamosmos añadir una opción "asomota" donde puedes introducir X% o Xpx en su lugar.
> 
> 
> [https://www.loom.com/share/67ba500dada7e14d1487777777777be970204dé8?sid=250fef1a-2abe-459b-a860-07fafd9ad41d](https://www.loom.com/share/67ba500da7e14d14877f7037be9702d8?sid=250fef1a-2abe-459b-a860-07fafd9ad41d)


> @ryrobes We are working on this feature now and I have an update to share. Below is a loom showing off how we're thinking about implementing this. Would love to hear your thoughts on:
> 
>     * Does the solution below address the problem?
> 
>     * Are there concerns about making fixed-width dashboards the new default?
> 
>     * We're thinking this is a editorial decision made per-dashboard by the creator within "Edit mode" where you can choose between a fixed-width or autoscaling as is the current behavior. How does that sound?
> 
>     * Would you want the width to be configurable or is a standard value fine? e.g. we could potentially add a "Custom" option where you can input X% or Xpx instead.
> 
> 
> https://www.loom.com/share/67ba500da7e14d14877f7037be9702d8?sid=250fef1a-2abe-459b-a860-07fafd9ad41d


That's sound great.  This solves my problem. When can it be implemented?

**Comment by cdeweyx** [comment]
> > Ahora .. . . . . . . . . . . . . . . . . . A continuación se muestra una telar de cómo estamos pensando en esto. Me encantaría oír tus pensamientos sobre:
> > ```
> > * La siguiente solución aborda el problema?
> > 
> > * Hay preocupaciones sobre el hecho de paneles fijos el nuevo default?
> > 
> > * Estamos pensando que esta es una decisión editorial tocida por el creador dentro del "modo de edición donde" se puede elegir entre un ancho fijo o autoescalado como es el comportamiento real. Cómo suena eso?
> > 
> > * Quieres que el ancho mar configurable o es una multa de valor estándar? por ejemplo, podríamosmos añadir una opción "asomota" donde puedes introducir X% o Xpx en su lugar.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [https://www.loom.com/share/67ba500dada7e14d1487777777777be970204dé8?sid=250fef1a-2abe-459b-a860-07fafd9ad41d](https://www.loom.com/share/67ba500da7e14d14877f7037be9702d8?sid=250fef1a-2abe-459b-a860-07fafd9ad41d)
> 
> That's sounds great. This solves my problem. When can it be implemented?

This will be available in Metabase Version 0.49
