### ISSUE TITLE
Cannot Locate Where MB Stores Variables In It's Postgresql DB

### ISSUE THREAD

**Issue by danmitzer** [metabase/metabase#10379]
does anyone know what table to look in to find where variable data for questions are stored in the Metabase Application's DB?

**Comment by flamber** [comment]
Hi @danmitzer 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Not sure what variable data you're talking about. Probably `report_card.dataset_query` or `metabase_fieldvalues`

**Comment by mbvictoria** [comment]
Closing - redirected to Github
