### ISSUE TITLE
Static vs responsive layout for dashboards

### ISSUE THREAD

**Issue by ogeagla** [metabase/metabase#10373]
For some users, a responsive layout becomes harder to use on different screen sizes.  Some would prefer that the frontend maintains a "full-size" / static layout and respond to different screen sizes by proportionately scaling the elements on the web page.  That way, for example, the legend maintains its relative position on screen vs being moved into a different location as screen width changes.

**Comment by flamber** [comment]
Related or dupe of #10364?

**Comment by ogeagla** [comment]
Dupe, thanks.
