### ISSUE TITLE
Allow users to modify invalid questions

### ISSUE THREAD

**Issue by ogeagla** [metabase/metabase#10371]
After a question is created, if we change a column name of the underlying table, the question breaks in the frontend.  I can imagine a more user-friendly behaviour that could be something like:

 - Even after table modifications that makes the question have no data, ensure that the question is still renderable (but empty) on the frontend
 - Hint to the user that a column is no longer available
 - Allow them to modify the question to remove the now-outdated column name

Currently, the only resolution to this is to delete the question and create a new one.

Related #12721

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Upgrading to P1 since duplicate #38532 was marked as such. 

See #38532 for more information. 

This issue is about making sure the Notebook Editor lets you edit questions that have columns that no longer exist, not about removing them automatically in the QP when you attempt to run those queries. We are tracking that issue separately in #12721

**Comment by camsaul** [comment]
Since this is QB related this is either an MLv2 issue or a pure FE issue

**Comment by snoe** [comment]
> This issue is about making sure the Notebook Editor lets you edit questions that have columns that no longer exist, not about removing them automatically in the QP when you attempt to run those queries. We are tracking that issue separately in https://github.com/metabase/metabase/issues/12721

Repro:
- In appdb (postgres with psql in my case)
  `create table ledger (id int, buyer_id int, seller_id int, comment text);`
- Add appdb as database to metabase instance
- Sync database schema
- Create question based on Ledger table (see screenshot)
- Back in appdb psql
  `alter table ledger rename buyer_id to crier_id;`
- Sync database schema
- Open question - see expected error about executing the query, suggests renamed column
- Open editor - see placeholders for the old column, which can be removed (with cascading deletes) and new column can be put in place.

Expected error when running query:
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/0a64cad2-d647-49db-896b-7af3fe12a669">

In this case, even very complicated questions are editable
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/2b66f990-c650-4a3b-b340-7d752d52d9e0">

**Comment by snoe** [comment]
Discussed with @ranquild closing as the query can be edited.
