### ISSUE TITLE
Metabase sends alerts from archived questions

### ISSUE THREAD

**Issue by Lightblash** [metabase/metabase#10377]
Hi!

Two weeks ago, Metabase alerts and pulses were behaving strangely:
- Alerts began to arrive hourly instead of daily
- Query return NULL, but alert return some data
- After archiving the question, alerts keep coming
Something similar happens with pulses.

When I set up a new alert, it works correctly.
How to stop receiving alerts from archived questions? How do I fix this? Restart, update Metabase to the new version - nothing works.
Cache settings:
![cache_settings](https://user-images.githubusercontent.com/10193021/61485130-0fbb2180-a9a9-11e9-832c-0935c8a6b028.png)

Metabase 0.32.8
PostgreSQL
Ubuntu 10.04

**Comment by flamber** [comment]
Hi @Lightblash 

Which version did you upgrade from?

On 0.32.9, when I archive a question with an alert, then it removes the alert, so even if I un-archive the question, then I need to setup the alert again.

Not sure if you are able to trigger the removal if you un-archive the question and archive it again with the latest version, but try it.
Otherwise you would need to delete the alerts in the table `pulse` of your metadata database.

**Comment by Lightblash** [comment]
Hi @flamber, thanks for the answer!

We updated from version 0.32.4. Update to latest version did not help.

Could you please tell me where metadata database is located and how can I delete alerts from the table `pulse`? I could not find any information about it.

**Comment by flamber** [comment]
@Lightblash I'm guessing you're probably still using the H2 default database for metadata, which is not recommended in production, so you should migrate to another database, which makes it easier for you to work with. Have a look in the documentation about migration:
https://metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

**Comment by Lightblash** [comment]
The problem turned out to be internal and not related to Metabase settings. Thanks.

**Comment by quackquackrubberducky** [comment]
@Lightblash do you remember what the problem was? I'm seeing similar behavior with subscriptions.

**Comment by Lightblash** [comment]
In my case the problem was in second running instance of Metabase in test environment

**Comment by quackquackrubberducky** [comment]
Thank you!
