### ISSUE TITLE
Using field filters in raw query causes permission error 

### ISSUE THREAD

**Issue by x670** [metabase/metabase#10382]
**To Reproduce**
1. Create two tables: 
```
CREATE TABLE company (
  company_id uuid,
  company_name varchar,
  created_at datetime
);
CREATE TABLE employee(  
  user_id uuid, 
  company_id uuid,
  employee_name varchar
  created_at varchar
);
```
2. Create collection1, grant to Johny access on collection1, create question inside collection:
```
SELECT ee.*, company.company_name
FROM employee ee
INNER JOIN company USING (company_id)
WHERE {{c_name}}
```
3. Set `c_name` as field filter on `company.company_name` column
4. Also you can add this question to dashboard also in this collection
5. When John opens dashboard, he see result so as dashboard contained in collection, where he has access to. But opening particular question lead to error
 ![image](https://user-images.githubusercontent.com/29977642/61529668-9d8b2100-aa2a-11e9-818b-65ba616451f2.png)

**Expected behavior**
When John opens dashboard or particular question, he see result and can use filtering so as he have access to collection

**Logs**
Browser requests status show 403 error on:
```
GET https://met.youdrive.today/api/field/2354
GET https://met.youdrive.today/api/field/2354/values
```
Metabase logs:
```
Jul 19 07:22:29 WARN metabase.middleware.log :: GET /api/field/2354 403 6 ms (4 DB calls) 
"You don't have permissions to do that."

Jul 19 07:22:29 WARN metabase.middleware.log :: GET /api/field/2354/values 403 3 ms (3 DB calls) 
"You don't have permissions to do that."
```

**Information about Metabase Installation:**
_- Your browser and the version:_ Any

_- Your operating system:_ No matter

_- Your databases:_ Postgres

_- Metabase version:_ 0.32.9, 0.33.0-preview2 jar

_- Metabase hosting environment:_ Linux/Debian

_- Metabase internal database:_ Postgres

**Severity**
This bug completely blocking workflow of some users, that have need to download results in xls format

**Comment by flamber** [comment]
Hi @x670 
I'm think you're seeing issue #8472 - if you agree, then please close this issue.
