### ISSUE TITLE
date format question

### ISSUE THREAD

**Issue by cqcn1991** [metabase/metabase#10381]
When performing date format in metabase

![image](https://user-images.githubusercontent.com/2425141/61519802-670bd100-aa3f-11e9-9941-0a8d53f51fd6.png)

I only see option as `2019-8-1`, is there any way to convert it to `2019-08-01`?

**Comment by flamber** [comment]
Hi @cqcn1991 
Go and upvote #9191 and close this issue.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
