### ISSUE TITLE
Segmentation fault (core dumped) - Metabase(v0.32.9) crash 

### ISSUE THREAD

**Issue by hemantkrsingh** [metabase/metabase#10386]
We are facing  Segmentation fault (core dumped) which has occurred twice in last one week. Below are the details on out Metabase environment.

- Your databases: Redshift
- Metabase version: v0.32.9
- Metabase hosting environment: AWS EC2 instance (two instances behind load balancer)
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
This has happened when Redshift goes to maintenance mode(redshift restart), like for instance on 2019-07-20 redshift began re-start around 2:31 AM IST and was up by 2:36 AM. At 2:33 AM 
 one of the instance memory usage spiked to 97%. 
At 2:51 AM we see Segmentation fault (core dumped) in our monitoring application.

See these entry in logs for crashed instance -
07-21 02:30:09 ERROR sync.util :: Error syncing FKs for Table 1,827 'public.yyy': [Amazon](600001) The server closed the connection.
...........
...................
07-21 02:34:11 ERROR sync.util :: Error syncing FKs for Table 1,853 'public.xxx': Connections could not be acquired from the underlying database!
07-21 02:34:41 ERROR sync.util :: Error syncing FKs for Table 1,837 'public.xxx': Connections could not be acquired from the underlying database!
07-21 02:35:11 ERROR sync.util :: Error syncing FKs for Table 1,807 'public.xxxx': Connections could not be acquired from the underlying database!
07-21 02:35:41 ERROR sync.util :: Error syncing FKs for Table 1,813 'public.xxx': Connections could not be acquired from the underlying database!
07-21 02:36:56 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
07-21 02:37:36 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
07-21 02:39:04 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
07-21 02:45:24 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
07-21 02:46:12 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
07-21 02:47:39 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
07-21 02:48:14 INFO middleware.exceptions :: Request canceled before finishing.
07-21 02:48:14 INFO middleware.exceptions :: Request canceled before finishing.
07-21 02:48:47 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
07-21 02:49:49 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
07-21 02:50:49 WARN jdbcjobstore.JobStoreTX :: This scheduler instance ( 1-xxxx) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.

Is the cause the unavailable redshift instance for sometime, if yes then why does this occur s only on one of the instances not the other.

**Comment by salsakran** [comment]
how much memory is there on the instance?

@camsaul @sbelak is it possible queries are backing up from the sync process?

**Comment by salsakran** [comment]
labeling P1 in case there is a resource leak (which affects overall stability). In the event there isn't a resource leak, this should be a p2

**Comment by salsakran** [comment]
@hemantkrsingh Can you share how much memory was on this instance?

**Comment by camsaul** [comment]
This is a similar issue to #9989 in that we weren't testing DB connections upon checkout which led to things getting in broken states. So like that issue this should be fixed by #11018. 

I don't know why the segfault occurred but the sync failures at least are fixed

**Comment by hemantkrsingh** [comment]
This instance jvm has 24 GB memory.

**Comment by hemantkrsingh** [comment]
++ Saurabh

Thanks,
Hemant Singh
hemant.singh@meesho.com

**Comment by camsaul** [comment]
I believe this was fixed by #11018. @hemantkrsingh please let me know if you're still seeing this issue in Metabase 0.33.4 or above.
