### ISSUE TITLE
New release 0.32.10?

### ISSUE THREAD

**Issue by cemsbr** [metabase/metabase#10389]
Dear @camsaul, are you going to release 0.32.10 in this month? I'm asking this because latest releases are for 0.33.x, but bug fixes like #9783 in 0.32.x would really help us. Thanks a lot.

**Comment by camsaul** [comment]
I don't think we're planning on doing a 0.32.10 release, but hopefully we will be releasing 0.33.0 in the next few weeks.

**Comment by mbvictoria** [comment]
0.32.10 was released yesterday. You can find the list of bug fixes that went into this release here: https://github.com/metabase/metabase/releases/tag/v0.32.10
