### ISSUE TITLE
How to format mysql date time field so that it works for time series graphs

### ISSUE THREAD

**Issue by ttristan** [metabase/metabase#10397]
I have a table of data containing logged requests that I show as a graph. The table has an auto generated **date and time** (timestamp) field that I use to aggregate data in a metabase Dashboard. 

This works totally fine for **data of one day**. However, when I pick a larger time frame, the chart does not show the data correctly, while all other fields on the Dashboard do. 

See here the difference in amounts, but not in the chart, only showing one day:
![Screenshot 2019-07-09 at 09 15 49](https://user-images.githubusercontent.com/24268434/61706245-dfc4a300-ad47-11e9-87a3-b416c794c1bb.png)
![Screenshot 2019-07-09 at 09 15 25](https://user-images.githubusercontent.com/24268434/61706244-dfc4a300-ad47-11e9-9616-8c9f67dc480b.png)

**mysql table create statement:**
```
CREATE TABLE `x` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `time_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `data` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=84505 DEFAULT CHARSET=utf8;
```
**Question & Dashboard setup:**
Question query:
<img width="880" alt="Screenshot 2019-07-23 at 12 00 21" src="https://user-images.githubusercontent.com/24268434/61706337-1c909a00-ad48-11e9-82e2-bb69a8665ef2.png">

time variable:
<img width="321" alt="Screenshot 2019-07-23 at 12 00 28" src="https://user-images.githubusercontent.com/24268434/61706340-20242100-ad48-11e9-8e38-972e0b947f28.png">

Chart settings:
<img width="378" alt="Screenshot 2019-07-23 at 11 58 38" src="https://user-images.githubusercontent.com/24268434/61706329-16022280-ad48-11e9-96cd-6a34c3d7f126.png">

time setting for chart:
<img width="256" alt="Screenshot 2019-07-23 at 11 58 50" src="https://user-images.githubusercontent.com/24268434/61706331-18fd1300-ad48-11e9-8841-ab7f6100eb33.png">

What am I doing wrong or how do I need to adjust the field format in the mysql DB so that metabase can work with it?

**Comment by flamber** [comment]
Hi @ttristan 
Which version of Metabase?
Do you see any errors in the Metabase log or your browser console?
Does it make a difference if you change from Timeseries to Ordinal?
In the future, please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by ttristan** [comment]
Hi @flamber 
thanks for your quick reaction, sorry if this is the wrong place to post, I will stick to discourse next time.
**Version:**
> You're on version v0.32.9
> Built on 2019-06-14

There are no visible errors for me other than a few warnings.
**Here is today:**
![today](https://user-images.githubusercontent.com/24268434/61772333-47372d00-adf2-11e9-84ab-6fc1a3222489.png)

**Here is past 7 days (only showing 2 days for some reason):**
![7 days](https://user-images.githubusercontent.com/24268434/61772364-5c13c080-adf2-11e9-9455-cda006c81424.png)

**Here is ordinal, which also only shows the first 2 days:**
![7 days ordinal](https://user-images.githubusercontent.com/24268434/61772380-6635bf00-adf2-11e9-836c-d7d23d20607a.png)

Is there any guide/docs on how to create time series chart out of mysql data in metabase?

**Comment by flamber** [comment]
@ttristan 
Let's ignore the dashboard right now.
If you go to the question and it defaults to "This Week", is the data shown correctly? If yes, also when you change the filter?

**Comment by ttristan** [comment]
@flamber 
alright, it does not look like it shows correct data for the default value "This Week". It is missing todays data. 
<img width="1380" alt="Screenshot 2019-07-24 at 14 38 17" src="https://user-images.githubusercontent.com/24268434/61794230-06a2d800-ae21-11e9-948e-8ad2d3cc2201.png">


After that, I changed the default to "This Month" and reloaded the question. It only shows the first date where data was available (05th of july)

<img width="1398" alt="Screenshot 2019-07-24 at 14 42 36" src="https://user-images.githubusercontent.com/24268434/61794348-4bc70a00-ae21-11e9-859b-05e963f62997.png">

**Comment by flamber** [comment]
I cannot reproduce the issue with Sample Dataset, where I get the count of Orders, grouped by Created At (hour), filtered by this year, which gives me more than 10,000 rows, but it's limited to 10,000, but when converting it to SQL, then the limit is 2,000 (no matter if I `GROUP BY` or not).

So I think your problem is that you're hitting the hardcoded limits, which are 1 million rows for downloads, 10,000 rows for viewing with aggregation, 2,000 rows for viewing without aggregation.

You would need to bin the results, when viewing more than a day or two of data, so it would accumulate the data.
It's also almost impossible to view a months worth of data with so many data points.

**Comment by ttristan** [comment]
@flamber thanks for lot for taking the time to investigate this!
I did not know anything about these hardcoded limits, are there any docs about this?
Anyhow the cap fo 2000 data points makes perfect sense now. This explains why only the first part/days of the data is displayed in the graph, as we have about 1-2k requests per day and no more would show.

**Comment by flamber** [comment]
Uhh, I actually don't think that's in the documentation, but do you see the little triangle in the top-right corner? It should say something about the graph being limited.
You might want to upvote issue #4564, which is about allowing changing the hardcoded limits.

**Comment by laratutoteam** [comment]
[Solevd easy query to have this](https://laratuto.com/date-format-in-mysql/)
