### ISSUE TITLE
After a successful front-end compilation of a metabse project, the web page displays only the directory structure

### ISSUE THREAD

**Issue by liuliu66666** [metabase/metabase#10408]
```
1. git clone https://github.com/metabase/metabase.git
2. yarn run build-hot
```

Compile successfully

```
Project is running at http://localhost:8080/
webpack output is served from http://localhost:8080/app/dist/
```

open http://localhost:8080/ in the browser, I want to see the front page, but the directory structure corresponding to the front file.
open http://localhost:8080/app/dist/ in your browser and display Cannot GET /app/dist/

How can I see the page?

**Comment by liuliu66666** [comment]
I got it, I have to run 

```
lein run
```
done
open http://localhost:3000/

I am new to metabase. Fortunately I succeeded in my attempt.

**Comment by flamber** [comment]
Hi @liuliu66666 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Have a look in the documentation: https://metabase.com/docs/latest/developers-guide.html
And close this issue :+1:
