### ISSUE TITLE
Allow users to paste a value into filter widgets

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1040]
This is most specifically about filter widgets that have a pre-defined set of options which are being listed for the user.  It would be cool if you could simply paste a value in and that choice would be selected as if you had scanned the list, found the value, and clicked on it.

**Comment by caske33** [comment]
I think filter-as-you-type should maybe be a 2nd step, so it's a least possible to filter on a specific (known) value. Now the SQL editor has to be used for this purposes.

**Comment by EvertEt** [comment]
There are unselectable values when dealing with huge lists which forces the use of SQL. A normal input on top of the suggestions would be great.

**Comment by kdoh** [comment]
Hey @EvertEt when you say there are "unselectable values" with huge lists do you mean you're seeing fields but can't actually click them or are you not seeing fields you'd expect to see?

**Comment by EvertEt** [comment]
Not all fields are listed. (For example, setting_value can go from 0 to 80000 but only 0-40 is displayed and thus selectable)

**Comment by kdoh** [comment]
Ah I see. So sounds like you're talking about being presented a set of checkbox options for values of a field that doesn't encompass the full range you're expecting, not missing the fields themselves? If so, it seems like the field is probably being marked as a category but for some reason the sync might not be properly identifying that the range of values is too high to make sense to display a set of checks. 

To work around this, you can go into Admin - > Data model and find the field in question and change the details dropdown from category to Number and you'll have a normal input field to use to filter the values.

**Comment by EvertEt** [comment]
Changing category to number did the trick, now I can input every value we need. Thank you very much!

**Comment by kdoh** [comment]
@EvertEt Of course. Mind giving me a bit of info about the type of DB and the type of field it is in the db schema, so we can try and investigate as to why it was marked as a category way in the beginning?

**Comment by agilliland** [comment]
I created a new issue to fix the issue described above.  Ultimately there should never be a situation where a field has more values than the set that we present in the checkboxes.  If that ever becomes the case then the checkboxes should automatically disappear and a freeform input should be provided instead.

**Comment by EvertEt** [comment]
@kdoh It's a mysql database and the field is a nullable VARCHAR(255) with 58 different values.

**Comment by camsaul** [comment]
@kdoh we mark fields as categories automatically if they have 40 or fewer distinct values. If the column gets new values and its airity passes 40 we don't yet unmark "category" -- see #1499. The `FieldValues` however are always capped at 40 values.

**Comment by kdoh** [comment]
With the recent merge of #4241 for 0.29 I'm guessing we can finally resolve this?
