### ISSUE TITLE
metabase failing to synchronise oracle tables with geodata

### ISSUE THREAD

**Issue by joeyboey** [metabase/metabase#10417]
**Describe the bug**
When trying do synchronise the database scheme of an oracle database containing tables with geodata (in my case shape files), the prepared statement will trigger an "ORA-01427: single-row subquery returns more than one row" error. The sync process is stopped after the first occurence.

**Logs**
`07-26 10:47:34 [1mERROR sync.util[0m :: Fehler beim Synchronisieren der Felder für Tabelle Tabelle 472 DWHEXT.PARTY_GEODATA: ORA-01427: single-row subquery returns more than one row

(oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:957)
oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
oracle.jdbc.driver.OracleDatabaseMetaData.getColumnsWithWildcards(OracleDatabaseMetaData.java:350)
oracle.jdbc.driver.OracleDatabaseMetaData.getColumns(OracleDatabaseMetaData.java:128)
com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3068)
--> driver.sql_jdbc.sync$describe_table_fields.invokeStatic(sync.clj:150)
driver.sql_jdbc.sync$describe_table_fields.doInvoke(sync.clj:147)
driver.sql_jdbc.sync$describe_table.invokeStatic(sync.clj:196)
driver.sql_jdbc.sync$describe_table.invoke(sync.clj:191)
driver.sql_jdbc$fn__64587.invokeStatic(sql_jdbc.clj:53)
driver.sql_jdbc$fn__64587.invoke(sql_jdbc.clj:52)
sync.fetch_metadata$fn__47680$table_metadata__47685$fn__47686.invoke(fetch_metadata.clj:18)
sync.fetch_metadata$fn__47680$table_metadata__47685.invoke(fetch_metadata.clj:15)
sync.sync_metadata.fields.fetch_metadata$fn__48002$db_metadata__48007$fn__48008.invoke(fetch_metadata.clj:82)
sync.sync_metadata.fields.fetch_metadata$fn__48002$db_metadata__48007.invoke(fetch_metadata.clj:78)
sync.sync_metadata.fields$fn__48506$sync_fields_for_table_BANG___48515$fn__48521$fn__48523.invoke(fields.clj:91)
sync.util$do_with_error_handling.invokeStatic(util.clj:149)
sync.util$do_with_error_handling.invoke(util.clj:144)
sync.sync_metadata.fields$fn__48506$sync_fields_for_table_BANG___48515$fn__48521.invoke(fields.clj:90)
sync.sync_metadata.fields$fn__48506$sync_fields_for_table_BANG___48515.invoke(fields.clj:83)
sync.sync_metadata.fields$fn__48551$sync_fields_BANG___48556$fn__48557$iter__48558__48562$fn__48563$fn__48564.invoke(fields.clj:117)
sync.sync_metadata.fields$fn__48551$sync_fields_BANG___48556$fn__48557$iter__48558__48562$fn__48563.invoke(fields.clj:116)
sync.sync_metadata.fields$fn__48551$sync_fields_BANG___48556$fn__48557.invoke(fields.clj:116)
sync.sync_metadata.fields$fn__48551$sync_fields_BANG___48556.invoke(fields.clj:111)
sync.util$fn__39397$run_step_with_metadata__39402$fn__39406$fn__39408.invoke(util.clj:356)
sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)
sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)
sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
sync.util$fn__39397$run_step_with_metadata__39402$fn__39406.invoke(util.clj:353)
sync.util$fn__39397$run_step_with_metadata__39402.invoke(util.clj:348)
sync.util$fn__39589$run_sync_operation__39594$fn__39595$fn__39596.invoke(util.clj:441)
sync.util$fn__39589$run_sync_operation__39594$fn__39595.invoke(util.clj:441)
sync.util$fn__39589$run_sync_operation__39594.invoke(util.clj:435)
sync.sync_metadata$fn__49238$sync_db_metadata_BANG___49243$fn__49244$fn__49245.invoke(sync_metadata.clj:51)
sync.util$do_with_error_handling.invokeStatic(util.clj:149)
sync.util$do_with_error_handling.invoke(util.clj:144)
sync.util$do_with_error_handling.invokeStatic(util.clj:147)
sync.util$do_with_error_handling.invoke(util.clj:144)
driver$fn__18264.invokeStatic(driver.clj:646)
driver$fn__18264.invoke(driver.clj:646)
sync.util$sync_in_context$fn__39303.invoke(util.clj:140)
sync.util$with_db_logging_disabled$fn__39300.invoke(util.clj:131)
sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)
sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)
sync.util$with_start_and_finish_logging$fn__39289.invoke(util.clj:116)
sync.util$with_sync_events$fn__39284.invoke(util.clj:90)
sync.util$with_duplicate_ops_prevented$fn__39275.invoke(util.clj:69)
sync.util$do_sync_operation.invokeStatic(util.clj:168)
sync.util$do_sync_operation.invoke(util.clj:165)
sync.sync_metadata$fn__49238$sync_db_metadata_BANG___49243$fn__49244.invoke(sync_metadata.clj:50)
sync.sync_metadata$fn__49238$sync_db_metadata_BANG___49243.invoke(sync_metadata.clj:47)
api.database$fn__49907$fn__49909.invoke(database.clj:513))

07-26 10:47:34 [1mERROR sync.util [0m :: Error running sync step: Output of sync-fields-for-table! does not match schema:
[0;33m (not (map? a-java.sql.SQLException)) [0m
(--> sync.sync_metadata.fields$fn__48506$sync_fields_for_table_BANG___48515.invoke(fields.clj:83)
sync.sync_metadata.fields$fn__48551$sync_fields_BANG___48556$fn__48557$iter__48558__48562$fn__48563$fn__48564.invoke(fields.clj:117)
sync.sync_metadata.fields$fn__48551$sync_fields_BANG___48556$fn__48557$iter__48558__48562$fn__48563.invoke(fields.clj:116)
sync.sync_metadata.fields$fn__48551$sync_fields_BANG___48556$fn__48557.invoke(fields.clj:116)
sync.sync_metadata.fields$fn__48551$sync_fields_BANG___48556.invoke(fields.clj:111)
sync.util$fn__39397$run_step_with_metadata__39402$fn__39406$fn__39408.invoke(util.clj:356)
sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)
sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)
sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
sync.util$fn__39397$run_step_with_metadata__39402$fn__39406.invoke(util.clj:353)
sync.util$fn__39397$run_step_with_metadata__39402.invoke(util.clj:348)
sync.util$fn__39589$run_sync_operation__39594$fn__39595$fn__39596.invoke(util.clj:441)
sync.util$fn__39589$run_sync_operation__39594$fn__39595.invoke(util.clj:441)
sync.util$fn__39589$run_sync_operation__39594.invoke(util.clj:435)
sync.sync_metadata$fn__49238$sync_db_metadata_BANG___49243$fn__49244$fn__49245.invoke(sync_metadata.clj:51)
sync.util$do_with_error_handling.invokeStatic(util.clj:149)
sync.util$do_with_error_handling.invoke(util.clj:144)
sync.util$do_with_error_handling.invokeStatic(util.clj:147)
sync.util$do_with_error_handling.invoke(util.clj:144)
driver$fn__18264.invokeStatic(driver.clj:646)
driver$fn__18264.invoke(driver.clj:646)
sync.util$sync_in_context$fn__39303.invoke(util.clj:140)
sync.util$with_db_logging_disabled$fn__39300.invoke(util.clj:131)
sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)
sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)
sync.util$with_start_and_finish_logging$fn__39289.invoke(util.clj:116)
sync.util$with_sync_events$fn__39284.invoke(util.clj:90)
sync.util$with_duplicate_ops_prevented$fn__39275.invoke(util.clj:69)
sync.util$do_sync_operation.invokeStatic(util.clj:168)
sync.util$do_sync_operation.invoke(util.clj:165)
sync.sync_metadata$fn__49238$sync_db_metadata_BANG___49243$fn__49244.invoke(sync_metadata.clj:50)
sync.sync_metadata$fn__49238$sync_db_metadata_BANG___49243.invoke(sync_metadata.clj:47)
api.database$fn__49907$fn__49909.invoke(database.clj:513))`

**To Reproduce**
1. Have a table with some data of type st_geometry (http://desktop.arcgis.com/de/arcmap/10.3/manage-data/using-sql-with-gdbs/st-geometry.htm)
2. Start the scanning process in admin panel
3. synch process will terminate after first table with geodata, saying the scan was successful

**Expected behavior**
First of all, i think the whole syncing should not terminate, if one table fails to sync it should still be tried for the other tables.
In addition to that metabase should be able to also scan tables with spatial data.

**Information about your Metabase Installation:**
- Your browser and the version:  Chrome 75

- Your operating system: Windows 10

- Your databases: Oracle 11g

- Metabase version: 0.32.9

- Metabase hosting environment: jar

- Metabase internal database: H2 (default)

**Severity**
it prevents me from using metabase entirely, because most of the functionality is broken due to this error

**Comment by salsakran** [comment]
The p1 is targeted towards the fact that a single column failing to sync should never stop all of sync.

**Comment by salsakran** [comment]
If/when that is closed, the underlying issue (geo fields w/ Oracle) is a P2

**Comment by sbelak** [comment]
Sync crash fixed with #11820, leaving this open as we still don't handle geodata itself, but downgraded severity.

**Comment by flamber** [comment]
Closing in favor of #2327 and #12724
