### ISSUE TITLE
Pivot tables, dates in result is not sorted as sql

### ISSUE THREAD

**Issue by crakter** [metabase/metabase#10416]
**Is your feature request related to a problem? Please describe.**
Pivot tables does not show the dates in sorted order in columns. Somewhat linked to #9805 but this might also be a bug? As this changes from day to day and cannot be customized easily.

**Describe the solution you'd like**
I would want the columns to reflect what i sort it by in the query manager.

**Describe alternatives you've considered**
I did not find any alternatives

**How important is this feature to you?**
Just slightly annoying

**Additional context**
![image](https://user-images.githubusercontent.com/24833502/61939592-eb0c0e80-af93-11e9-9cfe-190a298a14d0.png)
July 25, 2019 before July 23, 2019

![image](https://user-images.githubusercontent.com/24833502/61939684-14c53580-af94-11e9-9cb0-7fefd47f7f45.png)

**Comment by mazameli** [comment]
I can't reproduce this on master. Which version of Metbase are you using? What type of database are you querying? What is the underlying variable type of your date column here?

**Comment by crakter** [comment]
It was because it was sorted on count before Date. So when the count was larger on older dates it would display it first. Switching it fixed it. I will close this.
