### ISSUE TITLE
Metadata FieldValues should be skipped if field has high cardinality

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1041]
There are cases where a Field has a high cardinality and thus using pre-defined FieldValues just doesnt' make a lot of sense.  In these cases the sync logic should be smart enough to detect this situation and prevent FieldValues from growing larger than is reasonable.

**Comment by camsaul** [comment]
This was actually implemented in #1276. I [added a limit to the query used to get values for FieldValues last week](https://github.com/metabase/metabase/commit/afa50d0feb28a18f04a3d6dfd1297aefb7593031#diff-84a38741dd5bf440f12a3d99cacf1d37R21) when I was working on the new Mongo QP. So `FieldValues` will never grow past our current limit of 40 anymore.

Automatically unmarking a `Field` that was marked as a `:category` in the past once it grows beyond 40 distinct values will require some changes to sync and is of less immediate importance than preventing the `FieldValues` themselves from growing out of control so I've opened issue #1499 to address that in the future.
