### ISSUE TITLE
Problem in Dashboard to load some assets

### ISSUE THREAD

**Issue by rodrigodocket** [metabase/metabase#10410]
**Describe the bug**
When I access the home page I get this error: Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' fonts.gstatic.com themes.googleusercontent.com ".

**Screenshots**
Attached, the problem happens when I access the home

**Information about your Metabase Installation:**
- Metabase version: (e.x. 0.19.3)
v0.32.9 Built on 2019-06-14

- Metabase hosting environment: 
EC2 AWS Ubuntu

- Metabase internal database: 
H2

**Comment by rodrigodocket** [comment]
![Screen Shot 2019-07-25 at 10 53 12](https://user-images.githubusercontent.com/35839253/61880640-a61ca500-aecb-11e9-8154-9bd8f1458fc4.png)
![Uploading Screen Shot 2019-07-25 at 10.53.02.png…]()

**Comment by rodrigodocket** [comment]
![Screen Shot 2019-07-25 at 10 53 02](https://user-images.githubusercontent.com/35839253/61880826-f7c52f80-aecb-11e9-89dc-04e76c9a43f0.png)

**Comment by rodrigodocket** [comment]
![Screen Shot 2019-07-25 at 10 53 12](https://user-images.githubusercontent.com/35839253/61880856-03b0f180-aecc-11e9-9cb0-46b8eb499059.png)

**Comment by rodrigodocket** [comment]
![Screen Shot 2019-07-25 at 11 06 42](https://user-images.githubusercontent.com/35839253/61881001-4c68aa80-aecc-11e9-8477-31c8341f962f.png)

**Comment by flamber** [comment]
Hi @rodrigodocket 
I'm fairly sure you're just seeing #10191, which has been fixed and will be part of next release.
There's a work-around: https://github.com/metabase/metabase/issues/10191#issuecomment-505240542

**Comment by rodrigodocket** [comment]
Nice! Thank you!

**Comment by flamber** [comment]
@rodrigodocket If it works, then please close this issue.
