### ISSUE TITLE
Feature request: Dashboard editing: "Are you sure" dialog on leaving

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#10427]
**Describe the solution you'd like**
When you're editing a dashboard and you've made changes, then click something that takes you away from the dashboard, it would be great to trigger an alert like "You have unsaved changes. Are you sure you want to leave?"

**How important is this feature to you?**
Would be useful.  I sometimes lose edits I've made because I mistakenly click another card when I meant to drag it.  Not a blocker, however.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @chucksense 
I think I've seen this request before, but cannot find it. Anyhow, yes, it would be a good idea to warn on exit, but you shouldn't even be able to click a card, when you're in editing mode - issue #6888.

**Comment by brunobergher** [comment]
This is mostly complete, leaving the only one open which is around dashboards.
