### ISSUE TITLE
Metabase unable to use letter č

### ISSUE THREAD

**Issue by Linguk** [metabase/metabase#10431]
Hello,

so in my country (Slovenia), we have some special characters like čšž, where šž work normally, _č_ transforms into _?_ and the filters stop working. We use Metabase at work, so this issue comes knocking on the door quite often. 

For example if you pick a filter that checks if Status is _zaključeno_, it will never be correct, as it compares like this: 
zaključeno == zaklju?eno

Of course there are workarounds, but it makes unnecessary work for a single letter.

**Comment by dfx413** [comment]
That is rather strange. I also need the letter č (using Metabase in Czech Republic) and it works without any problems. I would guess you have some locale settings wrong.
![image](https://user-images.githubusercontent.com/1764151/62108301-0899ea80-b2aa-11e9-81d9-39e281e75c7f.png)

**Comment by Linguk** [comment]
Hmm, so how would I be able to check if this is a local setting's fault?

PS: it shows it correctly, but we cannot use any filter with it.

**Comment by dfx413** [comment]
The example above (search suggest box) shows that the filtering works correctly. When I apply it I get the corresponding rows.
Your locale has to be correctly setup in the database (which I assume it is), the system running Metabase (I would recommend to use the Docker version) and in the database connection settings in Metabase.
Since I don't know what version of Metabase, what operating system and what DB you are using I cannot tell you more right now.

**Comment by Linguk** [comment]
This is SQL code before I save question:
![image](https://user-images.githubusercontent.com/51593392/62109854-71cf2d00-b2ad-11e9-9a2d-8376cb750b3b.png)

And this is after: 
![image](https://user-images.githubusercontent.com/51593392/62109953-a93dd980-b2ad-11e9-8c2d-28b20fefd8e3.png)

I am checking if any Status is incorrect in this case.

Yes, databases have them stored correctly. What systems runs Metabase is unkown to me, will ask.
Databases vary, from PostgreSQL, MySQL and GoogleAnalytics. Metabase version is 0.31.2

**Comment by dfx413** [comment]
What happens when you save a question with a title cointaining "č"? Is the title also garbled after saving it? 

This seems like a problem with the Metabase system DB (where it stores all the data about questions, tables etc). 
For example if you used Mysql as the system database and did not set the correct locale in the connection you would get errors like this when trying to save letters with accent.

**Comment by Linguk** [comment]
Same thing happens if "č" is in title, it gets replaced by "?" after saving.

I will check the settings with the person that set it up. I will let you know what we find.

Thank you very much for now.

**Comment by Linguk** [comment]
Ok, so Metabase is running on MySql, using InnoDB and everything is set on utf8_general_ci.

Are there any settings that should be set on server?
Here is what we have:
![image](https://user-images.githubusercontent.com/51593392/62118726-7a7c2f00-b2be-11e9-984e-55ba1ceb29e6.png)

**Comment by dfx413** [comment]
you are missing the charset specification. 
I don't know whether Metabase has an environment variable for it so you need to specify the connection using JDBC URI. 
The env variable is named MB_DB_CONNECTION_URI
Here is the example (taken from Metabase documentation):
```
export MB_DB_CONNECTION_URI="mysql://localhost:3306/metabase?user=<username>&password=<password>"
```
you can find more info here: https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-url-format.html

and here

https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html

**Comment by Linguk** [comment]
I added `export MB_DB_CONNECTION_URI="mysql://localhost:3306/metabase?user=<username>&password=<password>"`
restarted service, but it is still the same. Do I maybe have to set collation server?

**Comment by dfx413** [comment]
Yes, that won't work for sure. As I said, that was just an example how the JDBC string works. 
You need to replace all the connection options (MB_DB_[whatever]) with single option MB_DB_CONNECTION_URI which contains all the options in one string.
Your system administrator should know how to setup DB connection using JDBC URL string.

**Comment by Linguk** [comment]
I will try on my own, as system admin went home already. If i won't be able to find a solution, I'll continue tomorrow.

Thanks again :)

**Comment by Linguk** [comment]
Good morning, 
so I've tried to set it as a single URL, but had to revert, as it showed me the screen "Get started". I suppose, there was either something wrong with the connection I set.

it was like this:
`export MB_DB_CONNECTION_URI="mysql://localhost:3306/services_int_metabase?user=services_int_metabase&password=***The password that we use***"`

The MB_PLUGINS_DIR was left as is, since I did not find how to add it into an url. Other MB_DB_* were erased from the file.

**Comment by dfx413** [comment]
Don't write 
`Export [xyz]`,  make it `Environment=[xyz]` just as it was in your screenshot.
The URL looks fine but you still don't have the charset spec there. Make sure to add it later.

**Comment by Linguk** [comment]
Something is still wrong (leaving the charset),
![image](https://user-images.githubusercontent.com/51593392/62190852-9e994800-b372-11e9-9900-0009088424f7.png)
gives me this:
![image](https://user-images.githubusercontent.com/51593392/62190918-bcff4380-b372-11e9-9971-baa1f66dc748.png)

**Comment by dfx413** [comment]
Something is wrong with the connection string.
Mine is like this : ```"MB_DB_CONNECTION_URI=postgresql://172.17.0.1:5432/metabase_test_config?user=metabase&password=mytopsecretpassword"```
I use it in different way than you (I use the Docker version instead of running the JAR as a system service) but my guess would be to put the opening quote in your connection string before `MB_DB_CONNECTION_URI`.
But you should consult your sysadmin and inspect the logs. This way it is just guesswork.

**Comment by Linguk** [comment]
You were correct, the issue was indeed with the quotes. Now it opens up as usual.

As for the charset, is the param I have to add `connectionCollation` or `character_set_server` and set them to `UTF-8` I suppose?

**Comment by dfx413** [comment]
I don't use MySQL. I gave you two links that should point you to the right direction. Just try it and consult your admin if you have problems. There is nothing you can mess up.

**Comment by Linguk** [comment]
Ok I made it! 
I had to set `characterEncoding=UTF-8` and now it works. 

Thank you very much for your assistance! 😄

**Comment by dfx413** [comment]
Nice!
