### ISSUE TITLE
Large api responses are truncated (not returning valid JSON)

### ISSUE THREAD

**Issue by dleard** [metabase/metabase#10432]
**Describe the bug**
A large response from a call to the api causes the results to be truncated. This appears to be a write-stream that is not being flushed properly as it truncates at different points when sending the request multiple times.

**Logs**
The server responds with a 200 status as it believes it has sent the entirety of the JSON response, but the response is truncated and this cannot be parsed.
FetchError: invalid json response body at api/card/100/related reason: Unexpected end of JSON input

**To Reproduce**
It appears most api endpoints respond with a small enough chunk that not flushing the stream is not an issue.
The best way to reproduce this is to create a question & relate it to many entities so that the api call to  /api/card/:id/related on that card will have a large response.
Try to parse the json response or make the api call in browser and see that the raw response cuts off.

**Expected behavior**
It should write a complete JSON object

**Screenshots**

**Information about your Metabase Installation:**
Chrome 72

- Your operating system: (e.x. OS X 10, Windows XP, etc)
Linux Ubuntu 16.04

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres 11.2

- Metabase version: (e.x. 0.19.3)
0.33.0

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Openshift

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Postgres

**Severity**
Annoying

**Comment by salsakran** [comment]
might be related to #9556

**Comment by flamber** [comment]
There has been many optimizations to responses in 0.34 and 0.35, which are now provided as a stream. Please comment with more details if you are still experiencing this on the latest release.
