### ISSUE TITLE
Dollar symbol not appearing in Safari

### ISSUE THREAD

**Issue by liran-co** [metabase/metabase#10435]
**Describe the bug**
The dollar / currency symbol is not appearing in Safari (appears in all other major browsers)

**Screenshots**
Safari:
<img width="295" alt="Screen Shot 2019-07-31 at 9 07 12 AM" src="https://user-images.githubusercontent.com/5923787/62214218-9b9e5780-b372-11e9-9955-bf304aa347b1.png">

Expected behavior:
<img width="251" alt="Screen Shot 2019-07-31 at 9 10 09 AM" src="https://user-images.githubusercontent.com/5923787/62214408-0354a280-b373-11e9-828c-24591818b0aa.png">

**Information about your Metabase Installation:**
- Safari Version 12.1.1 
- Your operating system: macOS 10.14.5.
- Your databases: MySQL
- Metabase version: v0.33.0-preview2
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

**Comment by flamber** [comment]
Hi @liran-co Just for good measures, can you try 0.33.0-RC1? I don't have Mac, so can't verify.

**Comment by liran-co** [comment]
Upgraded to 0.33.0-RC1, and the issue persists.

**Comment by alxnddr** [comment]
Could not reproduce it now using `Version 14.1.2 (16611.3.10.1.6)`
<img width="359" alt="Screen Shot 2021-09-22 at 14 11 33" src="https://user-images.githubusercontent.com/14301985/134333573-77eebb4d-4867-4bff-86cf-f36681949842.png">
