### ISSUE TITLE
Metabase pulses on Slack is posting blank charts

### ISSUE THREAD

**Issue by PalaToptal** [metabase/metabase#10436]
** Bug description **

Metabase pulses on Slack started to post blank charts starting from July 31 2019. These were working just fine in the past. Nothing was changed to the pulse settings. 
Also, the same pulse sends out emails too. The charts are just fine on the emails. Just the slack posts are showing up blank starting today. 

**To Reproduce**
1. Go to Metabase pulses
2. Click on send now for slack channel
3. Go to slack
4. See blank charts

**Expected behavior**
Slack should be showing the populated chart coming from Metabase

**Screenshots**
Attached

**Information about your Metabase Installation:**
Chrome Version 75.0.3770.142 (Official Build) (64-bit

- Your operating system: 
Mac OS  Mojave 10.14.5

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
MySQL

- Metabase version: (e.x. 0.19.3)
version v0.31.0-RC1
Built on 2018-10-30
Branch: release-0.31.0

- Metabase hosting environment: 
Heroku

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

**Severity**
We primarily use Metabase to generate important BI reports and share with stakeholders via Slack. Showing blank reports is a show stopper for us. 
Hence Severity is high. 

![Screen Shot 2019-07-31 at 10 53 02 AM](https://user-images.githubusercontent.com/42474940/62222760-e1aee780-b381-11e9-9c50-e9aea203a30a.png)

**Comment by flamber** [comment]
Hi @PalaToptal 
It sounds like the channel `metabase_files` has been deleted/limited. Check that everything is still setup correctly, otherwise try setting it up again.
https://metabase.com/docs/latest/administration-guide/09-setting-up-slack.html
Version 0.32.10 was released yesterday, so you should consider upgrading at some point, since supporting an old RC is going to be difficult.

**Comment by salsakran** [comment]
@PalaToptal Can you confirm whether or not the "metabase_files" channel is deleted or closed down to write from the Metabot user?
