### ISSUE TITLE
Trying to do a post-aggregation filter on a Date:Year column results in an error

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10446]
In this example, I've grouped by Created At: Year, then tried to filter to only get the last two years, and I get `Cannot parse "TIMESTAMP" constant "2016"`. This also happens when trying to do this in View mode. Only seems to happen when the granularity is set to `year`.

![image](https://user-images.githubusercontent.com/2223916/62251668-59423e00-b3a5-11e9-850f-8ab16b68cb44.png)

**Comment by camsaul** [comment]
Fixed by #10561
