### ISSUE TITLE
Is possible have all animated gif for last 10 versions

### ISSUE THREAD

**Issue by johnfelipe** [metabase/metabase#10453]
https://github.com/metabase/metabase/releases/tag/v0.33.0-RC1

That aminated gif is really nice, is possible have all big features for lastest 10 versions?
Stay alert

**Comment by flamber** [comment]
Hi @johnfelipe 
All releases are available in the archive - usually with big features/bugs listed - sometimes images too.
https://github.com/metabase/metabase/releases
https://www.metabase.com/blog/
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:

**Comment by mazameli** [comment]
Glad you like the GIFs, John. :) As Flamber already said, the blog is probably the best place to look at each of our major release posts where we've typically included images and/or GIFs of major features. Was there a specific reason you wanted or needed those GIFs?

If and when we finally decide to label Metabase `1.0`, I think having a retrospective post with some of the highlights along the way could be a kind of fun idea. Thanks for the thought.

**Comment by johnfelipe** [comment]
Is for show to my supervisor and show best option for BI software, because
is reviewing superset, Megatron and others, may be have a list with feature
and with animated gif take a better resolution
I hope your help
