### ISSUE TITLE
Changing table column order shows "Get answer" instead of just refreshing

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10466]
**Describe the bug**
Changing table column order shows "Get answer" instead of just refreshing.

**To Reproduce**
1. Create a "Simple question" (any table) and visualize as Table.
2. Either drag one of the column headers to a different position, or click Visualization Settings and drag the "Visible columns" to a different position.
3. Shows "Get answer" button overlay on the table.

**Expected behavior**
Just fresh the UI without clicking a button :smiley: 

**Screenshots**
![image](https://user-images.githubusercontent.com/1447303/62328453-72fc8780-b470-11e9-881f-2c3656b2d447.png)

**Information about your Metabase Installation:**
Metabase 0.33.0-RC1 local test with Sample Dataset - Firefox 68 and Chromium 76.

**Additional context**
From the [forum 0.33-preview thread](https://discourse.metabase.com/t/preview-upcoming-changes-to-the-gui-query-builder-updated/6551/78).

**Comment by mazameli** [comment]
Yeah, this doesn't seem right:

![moving-columns](https://user-images.githubusercontent.com/2223916/62494251-e14e8c00-b787-11e9-962b-b323d28bc367.gif)

**Comment by tlrobinson** [comment]
Ugh, I agree this is wrong, but technically the query is dirty because we update the order of the `fields` clause.

**Comment by mazameli** [comment]
(Just to clarify, this is happening even when auto-running is turned on for the DB.)

**Comment by flamber** [comment]
@mazameli I cannot reproduce this on latest `release-0.33.x` with a couple of tests. Think it was part of one of Tom's large PR last week. Close it?

**Comment by mazameli** [comment]
Really? I'm still seeing it and I just pulled the latest for `release-0.33.x`

**Comment by flamber** [comment]
@mazameli I was only testing on summarized data, which now doesn't trigger.
You're right, it's still triggering by moving a column on a plain Simple question.

**Comment by mazameli** [comment]
@paulrosenzweig Tom said above that changing the order of columns dirties the query, but it sure seems bad from a UX perspective to have to rerun the entire query just to change what feels like a visualization setting. Do you see any other approach we could take where changing the column order would feel immediate to the user?

**Comment by paulrosenzweig** [comment]
@mazameli I just updated the QB's definition of `getIsResultDirty` to ignore field order when doing the check. That fixes this issue, but I'm not sure if it creates new ones. 

I thought it might break the ability to save the new column order, but that seems to work. Any other things I should check before adding tests and opening a PR?

I'm guessing I'm missing something since Tom marked this with "Difficulty:Medium" and he knows this code much better than I do.

**Comment by mazameli** [comment]
@paulrosenzweig Thanks for checking this out! I'm wondering if this will affect column formatting settings or something, but if you push up a branch I can do a little manual testing to see if I notice any unintended consequences of the change.

**Comment by paulrosenzweig** [comment]
☝️ @mazameli, here's the branch. I didn't see anything with column formatting.

**Comment by paulrosenzweig** [comment]
Fixed in #11311
