### ISSUE TITLE
"Reset to default" doesn't reset UI value

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#10464]
When clicking the _Reset to default_ icon on a change _Link text_ input does not reset the value in the input to an empty value.

**To Reproduce**
1. Go to _Admin_ → _Data Model_ → [Table] → [Field settings] → _Formatting_ tab
2. Change the _Link text_ setting's value (and blur the field to trigger save)
3. Click the _Reset to default_ icon which is now visible 
![image](https://user-images.githubusercontent.com/23798/62326107-a0b3f180-b4ad-11e9-80ba-2ce2f0d129fa.png)
4. The value of the input remains unchanged, even though an update Ajax request was triggered.
5. Switch to _General_ tab.
6. Switch back to _Formatting_ tab.
7. See that the _Link text_ field has now been reset (to empty value).

**Expected behavior**
The _Link text_ value should reset as soon as the Ajax request to reset the value completes.

**Information about your Metabase Installation:**
- Metabase version: 0.33.0-RC1 (399c9bd)

**Severity**
Slight annoyance.

**Comment by walterl** [comment]
I only tested on the _Link text_ field, but @flamber [notes](https://github.com/metabase/metabase/issues/10462#issuecomment-517449938) that it also applies to _Add a prefix_ and _Add a suffix_ fields.

> It's the same behavior in Visualization Settings.

**Comment by flamber** [comment]
Closing, since functionality was removed in 0.38.0 - #13968
