### ISSUE TITLE
Metabase site base URL not accepting a valid (intranet only) FQDN

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#10469]
**Describe the bug**
For reasons that are beyond scope here our internal domain is called XXX.YY.inet. With the move to v0.32.10 Metabase no longer accepts servers referred to using this domain in the site base URL. If I use a replace the ".inet" with a ".com" or ".org" it is accepted even though these are not valid names.

**Logs**
```
Aug 02 12:41:28 DEBUG metabase.middleware.log :: PUT /api/setting/site-url 200 10 ms (3 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (121 total active threads) Queries in flight: 0
Aug 02 12:41:28 DEBUG metabase.middleware.log :: GET /api/session/properties 200 9 ms (1 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (121 total active threads) Queries in flight: 0
Aug 02 12:41:28 DEBUG metabase.middleware.log :: GET /api/setting 200 2 ms (0 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (122 total active threads) Queries in flight: 0
Aug 02 12:41:38 DEBUG metabase.middleware.log :: PUT /api/setting/site-name 200 6 ms (3 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (122 total active threads) Queries in flight: 0
Aug 02 12:41:38 DEBUG metabase.middleware.log :: GET /api/session/properties 200 7 ms (1 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (122 total active threads) Queries in flight: 0
Aug 02 12:41:38 DEBUG metabase.middleware.log :: GET /api/setting 200 1 ms (0 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (122 total active threads) Queries in flight: 0
Aug 02 12:41:45 ERROR metabase.middleware.log :: PUT /api/setting/site-url 500 2 ms (0 DB calls) 
{:message "Assert failed: Invalid site URL: http://something.inet\n(u/url? s)",

 :type java.lang.AssertionError,

 :stacktrace

 ("--> public_settings$normalize_site_url.invokeStatic(public_settings.clj:56)"

  "public_settings$normalize_site_url.invoke(public_settings.clj:48)"

  "public_settings$fn__21200$fn__21201.invoke(public_settings.clj:70)"

  "models.setting$set_BANG_.invokeStatic(setting.clj:368)"

  "models.setting$set_BANG_.invoke(setting.clj:356)"

  "api.setting$fn__63036.invokeStatic(setting.clj:33)"

  "api.setting$fn__63036.invoke(setting.clj:27)"

  "middleware.auth$enforce_authentication$fn__46209.invoke(auth.clj:14)"

  "routes$fn__64248$fn__64249.doInvoke(routes.clj:56)"

  "middleware.exceptions$catch_uncaught_exceptions$fn__46165.invoke(exceptions.clj:104)"

  "middleware.exceptions$catch_api_exceptions$fn__46162.invoke(exceptions.clj:92)"

  "middleware.log$log_api_call$fn__46083$fn__46084.invoke(log.clj:170)"

  "middleware.log$log_api_call$fn__46083.invoke(log.clj:164)"

  "middleware.security$add_security_headers$fn__46126.invoke(security.clj:105)"

  "middleware.json$wrap_json_body$fn__46292.invoke(json.clj:61)"

  "middleware.json$wrap_streamed_json_response$fn__46310.invoke(json.clj:97)"

  "middleware.session$bind_current_user$fn__46424$fn__46425.invoke(session.clj:193)"

  "middleware.session$do_with_current_user.invokeStatic(session.clj:176)"

  "middleware.session$do_with_current_user.invoke(session.clj:170)"

  "middleware.session$bind_current_user$fn__46424.invoke(session.clj:192)"

  "middleware.session$wrap_current_user_id$fn__46413.invoke(session.clj:161)"

  "middleware.session$wrap_session_id$fn__46398.invoke(session.clj:123)"

  "middleware.auth$wrap_api_key$fn__46217.invoke(auth.clj:27)"

  "middleware.misc$maybe_set_site_url$fn__46190.invoke(misc.clj:56)"

  "middleware.misc$bind_user_locale$fn__46193.invoke(misc.clj:72)"

  "middleware.misc$add_content_type$fn__46178.invoke(misc.clj:28)"

  "middleware.misc$disable_streaming_buffering$fn__46201.invoke(misc.clj:87)")}
```

**To Reproduce**
1. Go to Admin > General
2. Change the "Site URL" to `http://something.inet`
3. Error given in screen: Error: Assert failed: Invalid site URL: http://something.inet (u/url? s)
4. Change URL to `http://something.com`
5. change is saved without error

**Expected behavior**
I expected it to continue to accept our valid internal FQDN for a server. I think it's probably doing some lookup on what are valid *internet* TLD values, but as we can and are encouraged to self host Metabase I think we should be able to use any valid host name.

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/62336114-ed85df80-b522-11e9-9d04-67e1e4922b95.png)

![image](https://user-images.githubusercontent.com/4504437/62336255-959ba880-b523-11e9-9b94-de8232acb463.png)

**Information about your Metabase Installation:**
Your browser and the version: Chrome Version 75.0.3770.142 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: MS SQL 2014
Metabase version: v0.32.10, v0.33.0-RC1
Metabase hosting environment: Windows server, jar file
Metabase internal database: Postgres

**Severity**
Produces a lot of error logs, will cause issues with new shared public URLs, pulses etc. We can work around using IP address or simply the server name, but it's less than ideal and won't be an option in all environments.

**Comment by flamber** [comment]
Hi @notrom 
I think you're seeing issue https://github.com/metabase/metabase/issues/4617#issuecomment-486489780, which is has a 0.33 milestone.

**Comment by notrom** [comment]
Thanks @flamber the last comment on that ticket is exactly our situation. I don't want Metabase to limit what I can do in my internal network.

Cheers

**Comment by stel-lest** [comment]
so, when will it be fixed?

**Comment by salsakran** [comment]
bumping in priority since this is breaking emails for folks

**Comment by flyingmachine** [comment]
closed by https://github.com/metabase/metabase/pull/11710
