### ISSUE TITLE
Search dialog for adding a question to a dashboard is repeating results

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#10468]
**Describe the bug**
When adding a question to a dashboard I'm getting repeated results for the same questions. Each question is repeating multiple times, the exact number of repeats is variable.

**Logs**
No cosole or metabase logs around this time

**To Reproduce**
1. Go to a dashboard
2. Click on "Add a Question"
3. Search for a term you know has questions
3. The results has repeated questions

**Expected behavior**
one result per matching question

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/62334522-1a82c400-b51c-11e9-803b-e0929e94c5b0.png)

This doesn't happen when using the global search
![image](https://user-images.githubusercontent.com/4504437/62334808-5407ff00-b51d-11e9-959e-32d968ecbf3e.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome Version 75.0.3770.142 (Official Build) (64-bit)

- Your operating system: Windows 7

- Your databases: MS SQL 2014

- Metabase version: v0.32.10, v0.33.0-RC1

- Metabase hosting environment: Windows server, jar file

- Metabase internal database: Postgres

**Severity**
Annoyance, makes that search dialog largely useless, but can still navigate to the question.

**Comment by walterl** [comment]
Fixed in #10481
