### ISSUE TITLE
Mongodb query use double $project

### ISSUE THREAD

**Issue by rjurado01** [metabase/metabase#10471]
When I make a simple question without any filter with UI interface to mongodb database it runs a query like this (users collection):

```
[
  {
    "$project": {
      "_id": "$_id",
      "full_name": "$full_name",
      "avatar": "$avatar",
      "confirmed_at~~~default": {
        "$let": {
          "vars": {
            "column": "$confirmed_at"
          },
          "in": "$$column"
        }
      },
      "created_at~~~default": {
        "$let": {
          "vars": {
            "column": "$created_at"
          },
          "in": "$$column"
        }
      },
      "email": "$email",
      "project_ids": "$project_ids",
      "role_ids": "$role_ids",
      "updated_at~~~default": {
        "$let": {
          "vars": {
            "column": "$updated_at"
          },
          "in": "$$column"
        }
      },
      "username": "$username"
    }
  },
  {
    "$project": {
      "_id": "$_id",
      "full_name": "$full_name",
      "avatar": "$avatar",
      "confirmed_at~~~default": "$confirmed_at~~~default",
      "created_at~~~default": "$created_at~~~default",
      "email": "$email",
      "project_ids": "$project_ids",
      "role_ids": "$role_ids",
      "updated_at~~~default": "$updated_at~~~default",
      "username": "$username"
    }
  },
  {
    "$limit": 2000
  }
]
```

Why does it use the operator `$project` twice and the operator `$let` for datetime fields?

I think that this has a performance cost.

**Comment by salsakran** [comment]
@rjurado01 Do you have any timing information that suggests this has a performance impact?

We generate queries defensively, but it's entirely possible we're generating inefficient queries. However, we'd prefer to have some sort of quantitative performance data before we do much tweaking

**Comment by rjurado01** [comment]
With big databases has a performance impact. For example with [Stocks database](https://dl.dropbox.com/s/p75zp1karqg6nnn/stocks.zip) (4,308,303 documents with only 10 fields) downloaded from [this github repository](https://github.com/ozlerhakan/mongodb-json-files).

When I run default query (double `$project`) it takes around 840ms in my machine.

![image](https://user-images.githubusercontent.com/1703608/66336015-83cbec80-e93c-11e9-9272-e190c20e6c40.png)

When I run query with only one `$project` it takes around 720ms.

![image](https://user-images.githubusercontent.com/1703608/66336186-e6bd8380-e93c-11e9-84a3-ef5369c53f99.png)

When I run query without `$project` it takes around 560ms.

![image](https://user-images.githubusercontent.com/1703608/66336072-ac53e680-e93c-11e9-8669-0f29bcd56ae7.png)

**Comment by rjurado01** [comment]
I add a production example with a collection with 10.000.000 documents:

When I run default query (double $project):

![image](https://user-images.githubusercontent.com/1703608/73533697-b932a380-441f-11ea-9bc2-c0abf9f4e31b.png)

![image](https://user-images.githubusercontent.com/1703608/73533798-f0a15000-441f-11ea-9295-b76a6e8dd6d4.png)

When I run query without $project:

![image](https://user-images.githubusercontent.com/1703608/73533905-29d9c000-4420-11ea-99e9-a6e003da40e9.png)

The difference is too big 36 seconds vs 225 ms

**Comment by paoliniluis** [comment]
@camsaul will this issue be solved with https://github.com/metabase/metabase/pull/14840?

**Comment by rjurado01** [comment]
@paoliniluis Are this changes on v0.38.1 version?

**Comment by flamber** [comment]
@rjurado01 No, #14840 will be in the upcoming 0.39.0

**Comment by flamber** [comment]
@rjurado01 Have you tried newer releases? Latest is 0.41.2.
I'm only seeing a single $project, but after $match, which should be the performance bottleneck. Closing for now.
