### ISSUE TITLE
Tooltips missing from Segments

### ISSUE THREAD

**Issue by victoriaspek** [metabase/metabase#10476]
**Describe the bug**
The tooltip for the definition of a segment that previously appeared no longer appear.

Old behavior:
<img width="417" alt="segmenttooltip" src="https://user-images.githubusercontent.com/51675861/62388838-3766c980-b513-11e9-902b-a42f3d825243.png">

New behavior (missing from both Notebook mode and Summarize):
<img width="364" alt="segmentnotooltip" src="https://user-images.githubusercontent.com/51675861/62388994-8a408100-b513-11e9-827c-a780c1dae5aa.png">

**To Reproduce**
1. Create a segment and add a description
2. Navigate to asking a question, select Filter and look for the tooltip.

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 75

- Your operating system: Windows

- Your databases: Repro'd on the Sample Database

- Metabase version: 0.33-rc

**Comment by ranquild** [comment]
The issue is still present. Not sure if this can be entirely on the FE - might need MLv2 changes.

**Comment by ranquild** [comment]
We decided not to fix this since updated metrics are in the roadmap https://www.metabase.com/roadmap.
