### ISSUE TITLE
Couldn't create PostgreSQL datasource with ssl tunneling

### ISSUE THREAD

**Issue by sinnus** [metabase/metabase#10472]
**Describe the bug**
Couldn't create PostgreSQL datasource with ssl tunneling

**Logs**

> Aug 02 11:40:39 ERROR metabase.sync.util :: Error syncing Fields for Table 'Table 105 'public.account'': FATAL: password authentication failed for user "mlm_assist_prod_db"
> ("org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:514)"
> "org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)"
> "org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)"
> "org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)"
> "org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)"
> "org.postgresql.Driver.makeConnection(Driver.java:454)"
> "org.postgresql.Driver.connect(Driver.java:256)"
> "java.sql.DriverManager.getConnection(DriverManager.java:664)"
> "java.sql.DriverManager.getConnection(DriverManager.java:208)"
> "clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)"
> "clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)"
> "clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)"
> "clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)"
> "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)"
> "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
> "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
> "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
> "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1142)"
> "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
> "--> driver.postgres$enum_types.invokeStatic(postgres.clj:88)"
> "driver.postgres$enum_types.invoke(postgres.clj:85)"
> "driver.postgres$fn__65218.invokeStatic(postgres.clj:100)"
> "driver.postgres$fn__65218.invoke(postgres.clj:99)"
> "sync.fetch_metadata$fn__47681$table_metadata__47686$fn__47687.invoke(fetch_metadata.clj:18)"
> "sync.fetch_metadata$fn__47681$table_metadata__47686.invoke(fetch_metadata.clj:15)"
> "sync.sync_metadata.fields.fetch_metadata$fn__48003$db_metadata__48008$fn__48009.invoke(fetch_metadata.clj:82)"
> "sync.sync_metadata.fields.fetch_metadata$fn__48003$db_metadata__48008.invoke(fetch_metadata.clj:78)"
> "sync.sync_metadata.fields$fn__48507$sync_fields_for_table_BANG___48516$fn__48522$fn__48524.invoke(fields.clj:91)"
> "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
> "sync.util$do_with_error_handling.invoke(util.clj:144)"
> "sync.sync_metadata.fields$fn__48507$sync_fields_for_table_BANG___48516$fn__48522.invoke(fields.clj:90)"
> "sync.sync_metadata.fields$fn__48507$sync_fields_for_table_BANG___48516.invoke(fields.clj:83)"
> "sync.sync_metadata.fields$fn__48552$sync_fields_BANG___48557$fn__48558$iter__48559__48563$fn__48564$fn__48565.invoke(fields.clj:117)"
> "sync.sync_metadata.fields$fn__48552$sync_fields_BANG___48557$fn__48558$iter__48559__48563$fn__48564.invoke(fields.clj:116)"
> "sync.sync_metadata.fields$fn__48552$sync_fields_BANG___48557$fn__48558.invoke(fields.clj:116)"
> "sync.sync_metadata.fields$fn__48552$sync_fields_BANG___48557.invoke(fields.clj:111)"
> "sync.util$fn__40355$run_step_with_metadata__40360$fn__40364$fn__40366.invoke(util.clj:356)"
> "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
> "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
> "sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
> "sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
> "sync.util$fn__40355$run_step_with_metadata__40360$fn__40364.invoke(util.clj:353)"
> "sync.util$fn__40355$run_step_with_metadata__40360.invoke(util.clj:348)"
> "sync.util$fn__40547$run_sync_operation__40552$fn__40553$fn__40554.invoke(util.clj:441)"
> "sync.util$fn__40547$run_sync_operation__40552$fn__40553.invoke(util.clj:441)"
> "sync.util$fn__40547$run_sync_operation__40552.invoke(util.clj:435)"
> "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244$fn__49245$fn__49246.invoke(sync_metadata.clj:51)"
> "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
> "sync.util$do_with_error_handling.invoke(util.clj:144)"
> "sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
> "sync.util$do_with_error_handling.invoke(util.clj:144)"
> "driver$fn__17376.invokeStatic(driver.clj:668)"
> "driver$fn__17376.invoke(driver.clj:668)"
> "sync.util$sync_in_context$fn__40261.invoke(util.clj:140)"
> "sync.util$with_db_logging_disabled$fn__40258.invoke(util.clj:131)"
> "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
> "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
> "sync.util$with_start_and_finish_logging$fn__40247.invoke(util.clj:116)"
> "sync.util$with_sync_events$fn__40242.invoke(util.clj:90)"
> "sync.util$with_duplicate_ops_prevented$fn__40233.invoke(util.clj:69)"
> "sync.util$do_sync_operation.invokeStatic(util.clj:168)"
> "sync.util$do_sync_operation.invoke(util.clj:165)"
> "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244$fn__49245.invoke(sync_metadata.clj:50)"
> "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244.invoke(sync_metadata.clj:47)"
> "sync$fn__49289$sync_database_BANG___49294$fn__49295$fn__49296.invoke(sync.clj:28)"
> "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
> "sync.util$do_with_error_handling.invoke(util.clj:144)"
> "sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
> "sync.util$do_with_error_handling.invoke(util.clj:144)"
> "driver$fn__17376.invokeStatic(driver.clj:668)"
> "driver$fn__17376.invoke(driver.clj:668)"
> "sync.util$sync_in_context$fn__40261.invoke(util.clj:140)"
> "sync.util$with_db_logging_disabled$fn__40258.invoke(util.clj:131)"
> "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
> "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
> "sync.util$with_start_and_finish_logging$fn__40247.invoke(util.clj:116)"
> "sync.util$with_sync_events$fn__40242.invoke(util.clj:90)"
> "sync.util$with_duplicate_ops_prevented$fn__40233.invoke(util.clj:69)"
> "sync.util$do_sync_operation.invokeStatic(util.clj:168)"
> "sync.util$do_sync_operation.invoke(util.clj:165)"
> "sync$fn__49289$sync_database_BANG___49294$fn__49295.invoke(sync.clj:26)"
> "sync$fn__49289$sync_database_BANG___49294.invoke(sync.clj:19)"
> "events.sync_database$process_sync_database_event$fn__67009.invoke(sync_database.clj:36)")
> 

**Additional context**
Use H2 DB for metabase

**Comment by flamber** [comment]
Hi @sinnus 
Can you provide more information - like which version of Metabase, Postgres.
It seems like you're using wrong credentials: `FATAL: password authentication failed for user`

**Comment by sinnus** [comment]
I use right credentials.

Addition log from Browser console after datasource creation: 

> Failed to load resource: the server responded with a status of 500 (Server Error)
> app-main.bundle.js?db89dea08bd003ad80f4:5 
> 
> Object
> data: {message: "Syntax error in SQL statement "SELECT ""TABLE_ID""…TYPE" in (?, ?))) GROUP BY "TABLE_ID" [42001-197]", type: "class org.h2.jdbc.JdbcSQLException", stacktrace: Array(72), sql-exception-chain: Array(5)}
> isCancelled: false
> status: 500
> __proto__: Object

**Comment by flamber** [comment]
Which version of Metabase?
Which version of Postgres?
The browser console error seems different from the first stacktrace. Can you post the matching error from the Metabase log?
Do you see any errors on your Postgres log?

**Comment by flamber** [comment]
Closing, since no reply.
