### ISSUE TITLE
Confusing error message when entering incorrect DB connection details 

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10473]
If I enter wrong connection details like this, the error message reads `Save
metabase.util.i18n.UserLocalizedString cannot be cast to java.lang.String`. Seems like there's something wrong with localization? I'd expect it to say something human readable like "Couldn't connect to the database. Double check your connection settings."

![image](https://user-images.githubusercontent.com/2223916/62384863-60359180-b508-11e9-9965-3c493a1cb497.png)

This issue was mentioned in https://github.com/metabase/metabase/issues/10347

**Comment by walterl** [comment]
Fixed in #10571.
