### ISSUE TITLE
Presto timezone bug

### ISSUE THREAD

**Issue by gadfly0x** [metabase/metabase#10487]
Settings> General> Report Timezone to Asia / HongKong
When I use Date type Variable in Query, subtracted 8 hours.

![image](https://user-images.githubusercontent.com/33145499/62452430-08c03d00-b725-11e9-849d-04205b9501bb.png)

**Comment by gadfly0x** [comment]
Presto's log also subtracts 8 hours
![image](https://user-images.githubusercontent.com/33145499/62452941-0a3e3500-b726-11e9-9b60-fe0780d6ebd5.png)

**Comment by gadfly0x** [comment]
presto timezone: Asia / HongKong
docker timezone: Asia / HongKong
chrome timezone: Asia / HongKong

**Comment by gadfly0x** [comment]
When I used the Sample Dataset, the time was right
![image](https://user-images.githubusercontent.com/33145499/62459673-9a29c080-b7b2-11e9-9455-7e4096be12c7.png)

**Comment by mbvictoria** [comment]
Can you please take a look at our Timezone troubleshooting guide? https://metabase.com/docs/latest/troubleshooting-guide/timezones.html After you follow the steps there, let us know if you're still seeing a problem.

**Comment by gadfly0x** [comment]
metabase：
select {{start_date}},cast({{start_date}} as date)
![image](https://user-images.githubusercontent.com/33145499/62509531-27febd80-b83e-11e9-8429-45baa917c6f4.png)

After the transformation in presto：
select from_iso8601_timestamp('2019-07-31T16:00:00.000Z') as aaa,cast(from_iso8601_timestamp('2019-07-31T16:00:00.000Z') as date) as bbb
![image](https://user-images.githubusercontent.com/33145499/62509656-92176280-b83e-11e9-8642-ca917b500382.png)

When I set the time zone:
SELECT cast(timestamp '2019-07-31 16:00:00.000 UTC' as date),
cast(timestamp '2019-07-31 16:00:00.000 UTC' AT TIME ZONE 'Asia/Shanghai' as date),
date_format(timestamp '2019-07-31 16:00:00.000 UTC', '%Y%m%d'),
date_format(timestamp '2019-07-31 16:00:00.000 UTC' AT TIME ZONE 'Asia/Shanghai', '%Y%m%d')
![image](https://user-images.githubusercontent.com/33145499/62509841-5a5cea80-b83f-11e9-8224-efba29797a8a.png)

So, presto does not use the local time zone when converting utc time to date. But I don't know if it's a feature or a bug. If this is the feature of presto, metabase should use `AT TIME ZONE 'Asia/Shanghai'`.

**Comment by gadfly0x** [comment]
Related discussion on presto：
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/presto-users/y0Xx_Rv_QbE/QKuUcHW7DgAJ

**Comment by salsakran** [comment]
bumping this to p1 to match other timezone bugs.
