### ISSUE TITLE
0.33.0-RC1 Text color is very light

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10485]
The class `text-medium`, which is used for text many places (menus, settings, activity, etc) was [changed](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/css/core/colors.css#L20) from `#74838f` to `#a4adb3`.
It makes all the text difficult to read and for menus and select boxes, it looks like they're disabled.

**0.32.10:**
![Screen Shot 2019-08-03 at 20 25 37](https://user-images.githubusercontent.com/1447303/62418726-c9fb8b80-b62d-11e9-8e8c-bd8461082e34.png)

**0.33.0-RC1:**
![Screen Shot 2019-08-03 at 20 25 46](https://user-images.githubusercontent.com/1447303/62418727-d08a0300-b62d-11e9-9b9e-735edd7e1983.png)

**Comment by mazameli** [comment]
Mind taking a look at this @kdoh? Can't recall if this was an intentional change, but it does look a bit too light to me.
