### ISSUE TITLE
Show/hide all fields toggle in Custom Question

### ISSUE THREAD

**Issue by kattunga** [metabase/metabase#10488]
In Custom Question, Field lookup has only a "Select All" checkbox that not lets you unselect all fields.
I have tables with many fields (> 100), when I need only a subset of those fields (2 or 3) It is very frustrating to uncheck one by one.

![image](https://user-images.githubusercontent.com/2139720/62462588-265dc880-b75e-11e9-94d2-210bbfbca964.png)

Why don't allow Select All checkbox to toggle fields selection?

**Comment by flamber** [comment]
Hi @kattunga 
It looks like a duplicate of #10460 - if you agree, then please close this issue.

**Comment by kattunga** [comment]
Yes, I'm sorry, I didn't see that issue.
