### ISSUE TITLE
Stacked Bar Chart Incorrect Rendering with Negative Values 

### ISSUE THREAD

**Issue by YurZ** [metabase/metabase#10482]
**Describe the bug**
Stacked bar chart produces incorrect results when given a combination of positive and negative values to stack. Issue seems to be present for both - Custom/SQL and Native Query types of questions. Tested with Metabase versions v0.32.8 and v0.32.10. Database type seems to be irrelevant, tested with Postgres, H2 and MS SQL Server. 

**To Reproduce**
1. Create a new Native Query or Custom question where underlying values contain combination of negatives and positives, for example for native query use this sample sql: 
```
select * 
from (values 
      ('2019-07-30', 'A', 10)
     ,('2019-07-30', 'B', 5)
     ,('2019-07-30', 'C', 3)
     ,('2019-07-31', 'A', 10)
     ,('2019-07-31', 'B', -5)
     ,('2019-07-31', 'C', -3)
) t1 ("Date", "Category", "Net Sales") 
```
![Selection_20190803_150723_01](https://user-images.githubusercontent.com/2660088/62407716-745cba00-b600-11e9-983c-b32cbf307083.png)

2. Based on the data above build a visualisation of type Bar with X-axis set to 'Date' and 'Category', and Y-axis to 'Net Sales'   

3. Under 'Display' tab select Stacking option 'Stack'

4. Observe visualization results
![Selection_20190803_142448_01](https://user-images.githubusercontent.com/2660088/62407382-0c57a500-b5fb-11e9-9f7b-47798757f5bf.png)

**Issues with the above visualization, 2nd stacked bar**: 
- Total Net Sales for 2019-07-31 look like they are at 10 while actually it's 2 (= 10 - 5 - 3)
- 2019-07-31 Net Sales for Category A are at 2, while it should be 10
- Net sales for Categories B and C look like positive 5 and 3, while they are negative

**Expected behavior**
Expected result - something inline with the below: 
![Selection_20190803_144027_01](https://user-images.githubusercontent.com/2660088/62407788-6f4c3a80-b601-11e9-9b7e-f41f892de8db.png)

**Information about your Metabase Installation:**
- Your databases: 
Tested with Postgres, H2, MS SQL Server

- Metabase version: 
Tested with v0.32.8 and v0.32.10  

- Metabase hosting environment: 
Docker 

- Metabase internal database: 
Postgres

**Severity**
Blocking usage of Metabase Stacked Bar chart visualization type. 
Some existing reports are affected.   

**Additional context**
There are potentially related or similar issues mentioned previously but they seem to lack details and response: 
- https://github.com/metabase/metabase/issues/9147
- https://github.com/metabase/metabase/issues/5763 
- https://discourse.metabase.com/t/how-to-make-a-correct-bar-plot-with-negative-values/4910

Please advise if this is not a bug and/or there is a known workaround. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by wenyouzheng** [comment]
@salsakran Is this bug fixed?

**Comment by hagaetc** [comment]
Would love to see this bug fixed!

**Comment by MarcioVaka017** [comment]
Would love to see this bug fixed! [2]

**Comment by flamber** [comment]
Closing this in favor of #5763, which is the original issue, has more upvotes and (now) has a comment with a reproducible comment. Please upvote by clicking :+1: on the first post of that issue.
