### ISSUE TITLE
Show/hide all fields toggle in Browse Data Settings

### ISSUE THREAD

**Issue by kattunga** [metabase/metabase#10489]
Browse data -> Settings miss a toggle button to Show/Hide all fields.
I have tables with more than 100 fields and it is very frustrating to hide fields one by one.

![image](https://user-images.githubusercontent.com/2139720/62463859-83a74900-b761-11e9-9006-5818c64bcaac.png)

It's possible to add this feature?

**Comment by flamber** [comment]
Hi @kattunga 
It looks like a duplicate of #3266 - if you agree, then please close this issue.
I think the new Fields selection in Editor was trying to be the advanced way (#10460)

**Comment by kattunga** [comment]
Agree
