### ISSUE TITLE
 Field Filter not visible in editor mode when mapping field have difference 247 values

### ISSUE THREAD

**Issue by takaaptech** [metabase/metabase#10498]
**Describe the bug**
I try to create field Filter for simple SQL:
```
select * from country
where true
[[and {{code}}]]
```
But the Filter does not show on Editor

- Your databases: Postgres

- Metabase version: Metabase 0.33 - RC1

- Metabase hosting environment: (e.x. Centos 7)

- Metabase internal database: ( Postgres)
**Screenshots**
<img width="1587" alt="Screen Shot 2019-08-06 at 2 07 09 PM" src="https://user-images.githubusercontent.com/6276251/62519049-06f59700-b855-11e9-9e5d-282fc3054b54.png">

**Comment by flamber** [comment]
Hi @takaaptech 
It looks like you haven't set the Field Type of `Country.Code` to one of required ones in Data Model:
 https://metabase.com/docs/latest/users-guide/13-sql-parameters.html#creating-sql-question-filters-using-field-filter-variables

**Comment by takaaptech** [comment]
Hi @flamber !
Excellent! I can now have Widget with cool filter by country code! Thank so much for your quick help!
