### ISSUE TITLE
When viewing column settings in viz options we should hide the other sidebar "chrome"

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10492]
Right now it looks confusing after you click into a columns settings. The column back link should be at the top, and we should hide the tabs and the back button to go back to the viz type selection panel.

![column-options](https://user-images.githubusercontent.com/2223916/62492121-8cf4dd80-b782-11e9-8683-8ccec6c410bf.png)

**Comment by paulrosenzweig** [comment]
Fixed in #10996
