### ISSUE TITLE
Regression: Converting question filters to SQL 

### ISSUE THREAD

**Issue by RMMSecurity** [metabase/metabase#10496]
**Describe the bug**
Regression of #3549

Found on master and on 0.33-preview.

**Severity**
Pretty annoying since you can't copy/paste from the question itself. You can only Inspect element and copy/paste from there or change the filter from "is" to "contains" the copy/paste one by one for each condition.

**Comment by mazameli** [comment]
Reproduced this on master.

GUI query filters:

![Screen Shot 2019-08-07 at 2 19 24 PM](https://user-images.githubusercontent.com/2223916/62658789-76838900-b91e-11e9-96f4-ebc1c69887aa.png)

View the SQL:

![Screen Shot 2019-08-07 at 2 19 35 PM](https://user-images.githubusercontent.com/2223916/62658791-784d4c80-b91e-11e9-9a67-783354729e01.png)

Question converted to SQL:

![Screen Shot 2019-08-07 at 2 19 53 PM](https://user-images.githubusercontent.com/2223916/62658802-7b483d00-b91e-11e9-9275-ad6369a54c18.png)
