### ISSUE TITLE
Can I put my param into the jwt?

### ISSUE THREAD

**Issue by zhijianfree** [metabase/metabase#10490]
now , i have a special situation that when i embed dashbord in another system, i need put clear-text  parameters in the url. i think it's not safe.  can i  I put my parameters into the jwt? and then metabase can analyse  the parameters from jwt and put parameters in my SQL.

**Comment by flamber** [comment]
Hi @zhijianfree 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Have you read the documentation? https://metabase.com/docs/latest/administration-guide/13-embedding.html
And please close this issue :+1:

**Comment by zhijianfree** [comment]
@flamber  OK , thanks. i have  got solution  from the artical .
