### ISSUE TITLE
View mode shouldn't look broken on mobile

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10503]
There are some max-widths and wrapping behaviors that we should alter to make questions look respectable at mobile widths:

- Title can be wider
- Collection and data source breadcrumbs should be wider and wrap to next line if needed
- Active filters should wrap to new line if expanded
- Lineage should be on a new line
- Refresh should be visible, ideally in top-right
- Probably hide the Open Editor button
- Either hide Filter and Summarize, or put on new line
- Stretch: have filter, summarize, and viz sidebars slide all the way in to take up 100% of the available width

![image](https://user-images.githubusercontent.com/2223916/62565658-19170b80-b83c-11e9-9a8b-2fdba2a54974.png)

![image](https://user-images.githubusercontent.com/2223916/62566007-d9045880-b83c-11e9-9cca-86f32d666646.png)

**Comment by tlrobinson** [comment]
@mazameli I've fixed some of these issues in #10497

**Comment by mazameli** [comment]
Fixed by #10563
