### ISSUE TITLE
Field Filter by another table in the database (Sub Query)

### ISSUE THREAD

**Issue by takaaptech** [metabase/metabase#10500]
Hi All!
I need to create Field Filter by another table in the database
```
Select * from People where {{country_code}}

And Filter country_code get data from the country table like this  select code, from country
```
Is this possible now yet?

**Comment by flamber** [comment]
Hi @takaaptech 
Field Filter does not support alias, so you would need to join your `Country` table like so:
```
select * from People
left join country on Country.Code = People.Country_code
WHERE {{country_code}}
```
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by takaaptech** [comment]
Hi @flamber ! Thank for the help! Next time I will use the forum to ask for help!
