### ISSUE TITLE
Add Heroku Deploy Button to Repo

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1050]
Provide a one-click deployment option for users on heroku, using the Heroku button.

* [x] Create an app.json file using heroku/clojure as the base image
* [ ] Parse heroku db connection url 
- [ ] Output the correct setup URL to logs and/or securely redirect to the setup page (using app.json `success_url`?)

Stretch
* [ ] On timeout errors while running on heroku, change the error message to blame heroku on the timeout and prompt the user to simplify the query or run it on something a little more grown up
* [ ] Use an addon to automatically setup SMTP https://addons.heroku.com/?q=smtp

**Comment by agilliland** [comment]
I'm going to close this issue because we have included Heroku deployment since v0.12.0 (in beta) and we have individualized issues for any outstanding work related to Heroku.

#1311 #1187 #1317
