### ISSUE TITLE
Databases are sorted in random? order in QB when selecting DB

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10515]
I'm pretty sure they come back from the API endpoint sorted by `:name`, case-insensitive. It looks like they're getting resorted by `:id` or something in the UI

![image](https://user-images.githubusercontent.com/1455846/62589171-3cae7600-b87d-11e9-85cf-344aeba78b36.png)

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/10530
