### ISSUE TITLE
Support for a wide range of script languages 

### ISSUE THREAD

**Issue by HongjiangHuang** [metabase/metabase#10519]
**Is your feature request related to a problem? Please describe.**
The maintainability of the SQL language may be poor...

**Describe the solution you'd like**
Support script language to output table information, such as php, python.

**Describe alternatives you've considered**

**How important is this feature to you?**
I face the statistical needs to be changed every day. Now sql is very difficult to maintain.

**Additional context**
Too complicated sql language maintenance  to headless....
![image](https://user-images.githubusercontent.com/20190812/62608438-6aa1c200-b932-11e9-84e1-cb856df53a2f.png)

**Comment by salsakran** [comment]
This is outside of the scope of the project.

We do not expect to provide post processing of query results in the foreseeable future. I'll reopen if that changes.
