### ISSUE TITLE
download charts

### ISSUE THREAD

**Issue by CrazyZhangsk** [metabase/metabase#10518]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by CrazyZhangsk** [comment]
I want to download not only data, but also charts.

**Comment by CrazyZhangsk** [comment]
In the use process, we may prefer to generate charts to analyze problems through charts. For example, when I report to my supervisor, I can't hold the data for him to review, but through the generated charts, which can be more intuitive.

**Comment by flamber** [comment]
Hi @CrazyZhangsk 
Sounds like you're looking #4701 - go and upvote - and please close this issue.

**Comment by camsaul** [comment]
Duplicate on #4701
