### ISSUE TITLE
The Data Reference sidebar should organize tables by schema when applicable

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10520]
Right now when looking at the contents of a DB that has its tables organized in schemas in the data reference sidebar panel, the tables are shown as a flat list. We should really show the list of schemas, with the ability to click in to see a schema's contents. It's hard or impossible right now to know which table is which if there's more than one with the same name in multiple schemas.

Somewhat related to https://github.com/metabase/metabase/issues/7926

**Comment by paulrosenzweig** [comment]
@mazameli do we still have the data reference "sidebar"? When I looked in the full page data reference it looks like we do split up tables by schema. Though, we don't show them in an accordion.

![image](https://user-images.githubusercontent.com/691495/65362743-9de49b80-dbd6-11e9-8688-f50e602e45cd.png)

**Comment by mazameli** [comment]
Ah, yeah that's confusing — in this case I'm referring to the data reference or glossary side panel that's available when writing native queries by clicking the book icon in the top-right of the editor.

As an example, this test redshift DB on our stats instance is showing all these tables in a flat list instead of grouping them into their corresponding schemas:

![image](https://user-images.githubusercontent.com/2223916/65362887-ff4c4080-dbbd-11e9-957c-c8d4a7b9efbc.png)

**Comment by paulrosenzweig** [comment]
Fixed in #11030
