### ISSUE TITLE
Access via "Write SQL" works, but not via "Ask a question" > "Native query"

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10527]
**Describe the bug**
When having two databases and only setting SQL permissions for one, then users cannot access the editor via "Ask a question" > "Native query". It works via "Write SQL" button.

**Logs**
I don't see any errors related to this.

**To Reproduce**
1. Have two databases (Sample Dataset, and then setup another H2 to the same file)
2. Only allow data+SQL permissions on one of the databases for "All users".
3. Login as user, click "Ask a question". Note the larger options looks like it's only expecting two options, which is "fixed" if data permissions are allowed for both databases. (Not sure if I should have created a separate issue for this, but I think it's related to the way it checks permissions).
4. Click "Native query". No database is pre-selected in the editor and the editor is read-only.
5. If using "Write SQL", then it works as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/1447303/62747494-f0e10580-ba11-11e9-825a-63365344ce19.png)
![image](https://user-images.githubusercontent.com/1447303/62747516-05bd9900-ba12-11e9-9c46-39adf8386630.png)
![image](https://user-images.githubusercontent.com/1447303/62747690-d52a2f00-ba12-11e9-8d61-6ac19d5d3181.png)

**Information about your Metabase Installation:**
Tested `release-0.33.x` (commit 7ab9d9351adff5468b784c8364beafba7ba0bf76) and 0.33.0-RC1

**Comment by mazameli** [comment]
Fixed by #10574
