### ISSUE TITLE
metadata page slow on big tables

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1052]
our biggest db has 70 tables, and some of them have 20-40 columns. scrolling vertically in the metadata page for those tables is jerky, and opening drop-downs and selecting items each take a few seconds. (i'm on firefox 40, mac os x 10.10.5, mid 2014 13" MBP.)

this is low priority for us, since i don't spend a lot of time in there, and users don't see the metadata pages at all. just a heads up.

**Comment by flamber** [comment]
Hi @snarfed 
Is this still an issue for you? I cannot reproduce with 231 tables, selecting a table with 178 columns.
Metabase 0.32.9 with Firefox 67 on Ubuntu 19.04 on a laptop from 2011.

**Comment by snarfed** [comment]
thanks for the nudge! agreed, scrolling and UI controls are snappy now for me too, on a similar sized db and table. metabase 0.32.4, firefox 67, mac OS 10.14. four years of improvements evidently did the trick. closing!
