### ISSUE TITLE
AWS Elastic Beanstalk launch URL is broken

### ISSUE THREAD

**Issue by AlmogCohen** [metabase/metabase#10523]
**Describe the bug**
Navigating to https://metabase.com/start/aws/ and clicking the button, the launched environment does not automatically configure the **Platform** and the **Application code** which are the two most important configuration lines.

A short video of the issue can be seen here https://cl.ly/79b2ab

**To Reproduce**
1. Go to https://metabase.com/start/aws/
2. Click on "Launch Metabase on AWS"
3. See that both the Platform and Application code are not prepopulated as they should

**Expected behavior**
Both Platform and Application code should be populated with the proper configuration.

**Screenshots**
https://cl.ly/79b2ab

**Comment by AlmogCohen** [comment]
Maybe it's because the application code url is using unsecured https?

https://cl.ly/3fde2a

**Comment by walterl** [comment]
Hi @AlmogCohen. I've been looking into this for the last few days, and would just like to confirm whether we're seeing the same things.

When I click on the _Launch Metabase on AWS_ button from https://metabase.com/start/aws/...
1) I _don't_ see a _Preconfigured platform_ selected for the **Platform** option, and
2) I see _Sample application_ selected for the **Application code** option.

I think that is the same as what you were seeing.

When you select _Upload your code_ and click the _Upload_ button, do you also see the details filled in as follows? (The full value of _Public S3 URL_ is `https://downloads.metabase.com.s3.amazonaws.com/v0.33.3/metabase-aws-eb.zip`)
![image](https://user-images.githubusercontent.com/23798/65918012-fb4bca00-e3d8-11e9-87fe-acd12723aed1.png)

Also, could you please confirm that, when using [this _Launch Now_ link](https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-1#/newApplication?applicationName=Metabase&tierName=WebServer&platform=Docker&sourceBundleUrl=https%3A%2F%2Fdownloads.metabase.com.s3.amazonaws.com%2Fv0.33.3%2Fmetabase-aws-eb.zip&instanceType=t2.small&withRds=true&rdsDBEngine=postgres&rdsDBAllocatedStorage=10&rdsDBInstanceClass=db.t2.small&rdsMultiAZDatabase=false&rdsDBDeletionPolicy=Snapshot), that you see _Docker_ selected as the **Preconfigured platform**?

**Comment by flamber** [comment]
@walterl 
Could it be that some browsers might catch the `location=...` redirect, which is different from the `<meta ...refresh...` ?
One contains `...&platform=Docker&...` and the other `...&solutionStackName=Docker&...`
I'm unsure if the [template](https://github.com/metabase/metabase/blob/master/bin/aws-eb-docker/launch-aws-eb.html.template) could use a variable, so the finished html file always use the same URL.

**Comment by walterl** [comment]
@flamber Indeed, that parameter name is the difference in the link that I posted in my previous comment, asking for confirmation.

But that solves half the problem. The other half is _Sample application_ being the default value for **Application code**, instead of the source bundle. I'm couldn't find any AWS docs indicating that this is something we can change. o_O

**Comment by walterl** [comment]
I found that the instructions to fill in the **Application code** value (and much more) is already captured in the [installation docs](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html), so it's a known limitation of AWS _Launch now_ links.

The missing **Platform** value was fixed, exactly as @flamber suggested :)
