### ISSUE TITLE
Implicitly joined fields should be prefixed with foreign key field display_name

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#10549]
Currently the frontend uses the foreign key field `display_name` ([with trailing "id" removed](https://github.com/metabase/metabase/blob/754b2dee81cc6930a828bf2d86234a929ed9ddb8/frontend/src/metabase/lib/formatting.js#L796)) but the backend uses the joined table name:

![Screen Shot 2019-08-09 at 4 42 53 PM](https://user-images.githubusercontent.com/18193/62815142-dfa7ff80-baca-11e9-9105-278310dc0f60.png)

They should both use the fk field display_name with trailing "id" removed.

**Comment by camsaul** [comment]
Implemented by #10564
