### ISSUE TITLE
CSV/JSON as GET urls

### ISSUE THREAD

**Issue by key88sf** [metabase/metabase#10545]
**Is your feature request related to a problem? Please describe.**
Currently you cannot link to a CSV/JSON report for a question unless it's via the public shareable URLs, which are unsafe for most organizations. We would like a way to link to CSVs that still requires the authorization check.

**Describe the solution you'd like**
The ability to easily link to a CSV version of a question. For example, by adding `/csv` or `?format=csv` to the end of any question URL. That would use the default parameters for the query.

**Describe alternatives you've considered**
Parsing the returned HTML from the standard GET request for a question.

**How important is this feature to you?**
VERY important, since it enables things like importing to google sheets without public sharing.

**Additional context**

**Comment by flamber** [comment]
Hi @key88sf 
How should the authentication be handled if you're using `GET` requests without cookies?
As I wrote in the forum, you can do `POST` requests in Google Sheets:
https://discourse.metabase.com/t/access-csv-of-a-query-result-without-publicly-sharing/4688/8

**Comment by key88sf** [comment]
@flamber Auth would be handled by using an OAuth provider like Google Auth, not username/password.

**Comment by camsaul** [comment]
The problem is if we made external links clickable for download purposes it leaves those same links open to CSRF -- a malicious third party could potentially trigger those links and then steal the query results. It sounds like implementing this would negatively affect our security posture

**Comment by paoliniluis** [comment]
This is coming as a result of us enabling API keys in v49 :) what a time to be alive huh?
