### ISSUE TITLE
We should improve default titles for columns in joined saved questions 

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10548]
Right now columns brought over from saved questions look like `table_card__57 → Created At: Week`. There's a challenge here because we probably don't want to include the full title in each joined column heading, but we should make it look a bit nicer than this.

![image](https://user-images.githubusercontent.com/2223916/62814138-b768d280-bac3-11e9-8c68-f2d78a182377.png)

Ideas:
1. Use the word "Question" plus the ID number, like: 
`Question 57 → Created At: Week` 
This option makes it easier to distinguish columns when joining from multiple saved questions, but doesn't really tell you what the saved question is. Visually, an improvement.

2. Use the first `n` characters of the saved question plus an elipses like:
 `Revenue in las… → Created At: Week`
A bit more human readable-ish, but would be annoying if you're joining "Revenue in last 30 days from Texas" and also "Revenue in last 30 days from California," since you wouldn't be able to distinguish them.

Option 1 seems like a simple enough enhancement.

**Comment by salsakran** [comment]
Option 1 is probably the way to go. 

All roads lead to `give things names in the notebook` for me.

**Comment by tlrobinson** [comment]
@mazameli @salsakran I feel like the question name would be nice in some cases. Would

```
if question.name.length < 30: // or whatever limit we want
  question.name
else
  `Question ${question.id}`
```

be too much magic?

**Comment by tlrobinson** [comment]
@mazameli @salsakran It turns out #10531 already partially fixes this without any special logic because it sets the join alias to the joined table name (if the LHS of the condition is not a FK), which is the question title in the case of saved questions. It does not truncate long names though (the same is true of other tables, but that's less likely than saved question names)

**Comment by mazameli** [comment]
I feel like more often than not in this situation, full saved question names are going to be less help than harm. And yeah, I think it might be too much magic to sometimes swap the name to `Question 57 →` but other times leave it as `Revenue per month →`. Think I'm in favor of having saved questions always getting the `Question 57` treatment.

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/10531
