### ISSUE TITLE
Sort by saved metrics impossible

### ISSUE THREAD

**Issue by on99** [metabase/metabase#10554]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when saved metrics cannot be sorted in a custom question.

**Describe the solution you'd like**
Make saved metrics sortable.

**How important is this feature to you?**
We(engineers) have to convert a custom question into native query (sql) so that metrics can be sorted for our colleagues(not engineers, without sql background), but that's too annoying since we need to do this for every question, every metrics.

refs #8283

**Comment by flamber** [comment]
Hi @on99 
While I understand you might be frustrated by #8283 not being resolved yet, creating duplicate issues doesn't help maintaining an overview of all the open issues. Please close this issue.
