### ISSUE TITLE
Explicitly joined fields should be prefixed with join alias, which should be set to foreign key display_name by default

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#10550]
Similar to #10549

- [x] backend: columns from a `joined-field` should be prefixed with the join `alias` instead of the table name
- [x] frontend: join `alias` should be set to the foreign key field's `display_name` with trailing "id" removed 

![Screen Shot 2019-08-09 at 4 42 53 PM](https://user-images.githubusercontent.com/18193/62815168-20077d80-bacb-11e9-9450-f31e4a753bd8.png)

**Comment by camsaul** [comment]
Backend implemented by #10564

**Comment by mazameli** [comment]
Fixed by #10531 and #10564
