### ISSUE TITLE
Ask a question button doesn't take you to new question page when modal is open 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10558]
Steps to repro 

1. Create a new question
2.  Click a modal like public sharing & embedding 
3.  Click "Ask a Question" in the nav bar
4.  Runs the query again and takes you back to the query results/visualization

Running a query when it is unchanged is something we should try to avoid doing (if the query takes 5 minutes to run, it's a little annoying). Also I'd expect the "Ask a Question" button to always take me to the new question page whether a modal is open or not, rather than simply close any open modals.

**Comment by mazameli** [comment]
I can't reproduce this anymore in 0.33.4, @camsaul. Go ahead and reopen it if you can repro it.
