### ISSUE TITLE
Admin Settings Do Not Show Up

### ISSUE THREAD

**Issue by bvallelunga** [metabase/metabase#10565]
**Describe the bug**
The admin settings page does not show after migrating the database from one Postgres database to another.

**Screenshots**
<img width="1279" alt="Screen Shot 2019-08-12 at 6 50 17 PM" src="https://user-images.githubusercontent.com/1920007/62909589-0b78ee80-bd32-11e9-8bdd-7ba2b3bbbe31.png">

**Information about your Metabase Installation:**
- Chrome 76.0.3809.100

- OS X

- Postgres

- metabase/metabase docker image

- Google Cloud - Kubernetes

- Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Blocking our usage as we can not change settings that allows the rest of the team to use the product.

**Comment by salsakran** [comment]
@bvallelunga can you share the server and javascript logs from this time? At the very least , the javascript logs should contain an error message if this page isn't rendering

**Comment by bvallelunga** [comment]
@salsakran thank you for reaching out. I just took a look and oddly enough it looks like the problem has resolved itself. The dashboard is working normally as usual. Would you like me to close the issue?

**Comment by salsakran** [comment]
glad to hear it.

I'll close it, but chime in if it ever happens again. I'm going to guess it was a transient error that resulted in an invalid setting somehow making it to the client that resolved itself.

**Comment by ajulm** [comment]
Hard refresh resolved the issue!
