### ISSUE TITLE
Custom fields, done button is disabled

### ISSUE THREAD

**Issue by crakter** [metabase/metabase#10578]
**Describe the bug**
Not able to save custom fields, done button is disabled
I couldn't find any existing bugreports, if so sorry about that.

**Logs**
[error_in_console.log](https://github.com/metabase/metabase/files/3500894/error_in_console.log)
Please check attached logs from console

**To Reproduce**
1. Go to 'Query builder 3'
2. Go down to 'Custom column'
2. Click on '+'
3. Add formula
4. See nothing changing on button, still disabled

**Expected behavior**
To be able to save the custom column

**Screenshots**
![image](https://user-images.githubusercontent.com/24833502/63013689-12684400-be8d-11e9-8a57-0bd3d7adf96a.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76.0.3809.100

- Your operating system: Windows 10

- Your databases: MySQL

- Metabase version: 0.33-RC1

- Metabase hosting environment: Docker

- Metabase internal database: MySQL

**Severity**
Not being able to save the field is not good. 

**Additional context**

**Comment by mazameli** [comment]
Is this happening for you if you try to create a custom column _before_ aggregating? I am able to reproduce this, but only when trying to create a custom column after an aggregation.

![image](https://user-images.githubusercontent.com/2223916/63039810-f5c21100-be78-11e9-8849-23606bffb724.png)

**Comment by crakter** [comment]
Yea, correct. I'm able to add column without aggregation aswell.
