### ISSUE TITLE
Unable to edit database description

### ISSUE THREAD

**Issue by enqueue** [metabase/metabase#10576]
**Describe the bug**
I am unable to change the description for a database. When I click on "Save" I am presented with an error message `e.actions is undefined`.

**To Reproduce**
1. Go to 'Learn about our data / Databases and tables / Sample Dataset
2. Click on '🖉 Edit'
3. Enter some text in the 'Description' text area
4. Click on 'Save'
5. See error 'e.actions is undefined'
6. Database description is not updated

**Expected behavior**
The database's description should be updated, the view should show the current values.

**Screenshots**
![Metabase_db_description_2019-08-14 10-21](https://user-images.githubusercontent.com/5407006/63006938-fad68e80-be7f-11e9-8595-8abc79aefc72.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 68.0.1
- Your operating system: GNU/Linux x86_64 5.2.8-arch1-1-ARCH
- Your databases: happens for both, H2 (sample dataset) and ClickHouse

- Metabase version: 0.33.0-RC1

- Metabase hosting environment: RHEL 7.4 GNU/Linux x86_64, openjdk 1.8.0_201

- Metabase internal database: H2

**Severity**
This is just a cosmetic nuisance. Most colleagues know what the databases are there for.

**Comment by flamber** [comment]
Hi @enqueue 
Looks like a duplicate of #8443 - if you agree, then upvote by clicking :+1: and closing this issue.

**Comment by enqueue** [comment]
@flamber sorry, did not see the other ticket. Fine to close this one as duplicate.
