### ISSUE TITLE
Multiple remapped columns to the same table/field don't return correct column info

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#10575]
This is the classic example we've been using of a table for "Posts" with two foreign keys to the same "People" table, "Author" and "Reviewer":

![Screenshot 2019-08-13 17 44 55](https://user-images.githubusercontent.com/18193/62987178-6292c800-bdf3-11e9-8162-100cb0c57b7b.png)

Column 1 is `author` (`remapped_to` is incorrect)
Column 4 is the remapped author name (`remapped_from` and `display_name` are incorrect) 

Column 2 is `reviewer` (correct)
Column 5 is the remapped reviewer name (correct)

This results in only the Reviewer remapping being shown:

![Screenshot 2019-08-13 17 58 06](https://user-images.githubusercontent.com/18193/62987312-00869280-bdf4-11e9-85fa-6183ec357c0e.png)

**Comment by flamber** [comment]
Avoiding linking, since I'm not quite sure, but it looks like 9236 - or am I misunderstanding this?

**Comment by flamber** [comment]
Closing in favor of #9236
