### ISSUE TITLE
When a user doesn't have SQL editor access, the new question page doesn't show the Custom Question option

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10582]
Possibly related to #10527? But not fixed by https://github.com/metabase/metabase/pull/10574

If I don't have SQL editor access to any database, when I click the New Question button I go straight to the Simple Question data selection step. I can still get to the notebook from the top-right button and use it normally, though:

![no-notebook-option](https://user-images.githubusercontent.com/2223916/63041311-6d456f80-be7c-11e9-8904-232a8c502c2d.gif)

**Comment by flamber** [comment]
Good catch, didn't see that. It sounds very related to Cam's recent issue #10558

**Comment by tlrobinson** [comment]
Resolved by #10563
