### ISSUE TITLE
Cannot toggle off 'Automatically run queries when doing simple filtering and summarizing' 

### ISSUE THREAD

**Issue by mrdanjl** [metabase/metabase#10594]
**Describe the bug**
In Admin -> Databases, when attempting to toggle off 'Automatically run queries when doing simple filtering and summarizing' and saving it, it presents an error.

**Logs**
```
Aug 15 07:03:23 DEBUG metabase.middleware.log :: GET /api/database/2 200 6 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (64 total active threads) Queries in flight: 0
Aug 15 07:03:27 DEBUG metabase.middleware.log :: PUT /api/database/2 400 56 ms (1 DB calls) 
{:valid false,
:dbname
"class metabase.util.i18n.UserLocalizedString cannot be cast to class java.lang.String (metabase.util.i18n.UserLocalizedString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')",
:message
"class metabase.util.i18n.UserLocalizedString cannot be cast to class java.lang.String (metabase.util.i18n.UserLocalizedString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')"}
```

**Screenshots**
<img width="1210" alt="Screen Shot 2019-08-15 at 4 53 21 pm" src="https://user-images.githubusercontent.com/365575/63078805-0a3d0100-bf80-11e9-8c9e-32b6bc369ddb.png">

**Information about your Metabase Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Version 76.0.3809.100 (Official Build) (64-bit)

- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X 10

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
MySQL 8.0.15

- Metabase version: (e.x. 0.19.3)
v0.33.0-RC1
Built on 2019-07-30
Branch: release-0.33.x
Hash: 592ef43

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
AWS Docker

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
MySQL

**Severity**
Relatively annoying due to the large sizes of our dataset

**Comment by flamber** [comment]
Hi @mrdanjl 
The confusing error message was fixed yesterday (#10571), which is covering up the real error message, so could you try the docker image metabase/metabase-head ?
In most cases, when people encountered this error message, it was because of wrong username, password or database name, so can you triple-check that it's correct?

**Comment by mazameli** [comment]
I'm unable to reproduce this on `release-0.33.x`. If you toggle this off and then back on again, do you get the error message when you try to save? If so, then it is probably an incorrect username/password/db name as @flamber mentioned.

**Comment by mrdanjl** [comment]
Thanks -- all sorted by upgrading and re-checking the connection details.

**Comment by GabeBigBoxVR** [comment]
I'm reproducing this on `0.37.0.1` as well. I'm unable to turn `Automatically run queries when doing simple filtering and summarizing` off.  I've confirmed by database credentials are indeed correct.  What info can I provide to help diagnose this?

**Comment by flamber** [comment]
@GabeBigBoxVR 
Please post "Diagnostic Info" from Admin > Troubleshooting, and which database type you're trying to disable this for.
And check the log for any detailed errors - Admin > Troubleshooting > Logs.
