### ISSUE TITLE
Search field doesn't show input field - width: 0;

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10598]
Search field doesn't show input field - looks like it's getting `width: 0;` somewhere.
release-0.33.x (commit 34c37f7d313790d61104c2a287f3d80c1f846a8b) - Firefox and Chromium

![image](https://user-images.githubusercontent.com/1447303/63130193-e3c69800-bf76-11e9-8729-946a9bfba118.png)

**Comment by mazameli** [comment]
@tlrobinson I think this was the commit you'd added to get the gear button/icon to show up on mobile.

**Comment by mazameli** [comment]
Fixed by #10600
