### ISSUE TITLE
Metabase cannot process Postgresql "money" datatype.

### ISSUE THREAD

**Issue by adjenks** [metabase/metabase#10599]
**Describe the bug**
Casting a large number to ::money results in an error.

**To Reproduce**
1. Attach Metabase to a PostgreSQL database
2. Execute this:
```sql
SELECT 99999999.00::money;
```
3. See error

> Bad value for type double : 99,999,999.00

**Expected behavior**
For it to display the value.

**Screenshots**

**Information about your Metabase Installation:**
- Your browser and the version: FireFox but n/a

- Your operating system: Windows

- Your databases: PostgreSQL

- Metabase version: v0.32.10

- Metabase hosting environment: Ubuntu

- Metabase internal database: PostgreSQL

**Severity**
Low-medium: It means I have to rewrite my existing report queries.

**Additional context**
None

**Comment by flamber** [comment]
Hi @adjenks 
It looks like a duplicate of #3754 - if you agree, then please close this issue.
And looking at the other issue, it looks like it's an open issue in the PgJDBC driver.

**Comment by adjenks** [comment]
@flamber Oh, thank you, I somehow missed that one.

**Comment by camsaul** [comment]
This is an upstream issue with the Postgres JDBC driver: https://github.com/pgjdbc/pgjdbc/issues/425

They have closed it as won't fix.

**Comment by camsaul** [comment]
Fixed by #11716
