### ISSUE TITLE
Revert cache-busting when dashboards auto-refresh

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10603]
https://github.com/metabase/metabase/pull/10479 had some unintended consequences when looking at dashboards that had a mix of fast and slow queries, so we want to revert that before 0.33 goes out.

**Comment by tlrobinson** [comment]
I'd probably just revert this line rather than the whole thing https://github.com/metabase/metabase/pull/10479/files#diff-7ff9b7220eed8c341e0c8a78c1ff0151R193

**Comment by mazameli** [comment]
Resolved by #10608
