### ISSUE TITLE
Make minimum width of text field smaller

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#10607]
**Is your feature request related to a problem? Please describe.**
I have a dashboard laid as follows:
Row 1, 2 columns 9-width each, both showing charts
Row 2, 6 columns 3-width each, showing a mix of numbers smart numbers

If I want to swap a number for a text box, I can't because the min-width of a text box is 4 instead of the 3 of the number boxes.

See screenshot:

![Daily Marketing Overview - New · Dashboard · Metabase 2019-08-16 14-39-04](https://user-images.githubusercontent.com/199588/63190199-b55ac280-c033-11e9-887d-389f313536bf.jpg)

**Describe the solution you'd like**
I'd like to be able to make a 3-width text box.

**How important is this feature to you?**
Not a deal breaker, just an annoyance.

**Comment by flamber** [comment]
Just for reference, there's a request for even allowing smaller than 3x3 cards - #5662

**Comment by chucksense** [comment]
Thanks.  Closing this one and subscribing / +1 that one instead.
