### ISSUE TITLE
Error syncing Fields for Table “m_dim_day”': (conn=28341) unexpected end of stream, read 0 bytes from 4 (socket was closed by server

### ISSUE THREAD

**Issue by xqwbx163** [metabase/metabase#10614]
i try to use metabase0.32.10 link to tidb 3.0,
sync database schema   
show error :
![image](https://user-images.githubusercontent.com/20455410/63152047-7d587d00-c03d-11e9-87e2-995538b9d1c4.png)
then i print the tidb log 
find this error sql 
![image](https://user-images.githubusercontent.com/20455410/63152451-754d0d00-c03e-11e9-8176-75c5317cb1b9.png)

execute sql on tidb  > 2013 - Lost connection to MySQL server during query
![image](https://user-images.githubusercontent.com/20455410/63157583-d8906c80-c049-11e9-80a7-4513496036ff.png)

"
SELECT
	TABLE_SCHEMA TABLE_CAT,
	NULL TABLE_SCHEM,
	TABLE_NAME,
	COLUMN_NAME,
CASE	data_type 	WHEN 'bit' THEN	- 7 WHEN 'tinyblob' THEN -3 
	WHEN 'mediumblob' THEN -4 
	WHEN 'longblob' THEN -4 
	WHEN 'blob' THEN -4 
	WHEN 'tinytext' THEN 12 
	WHEN 'mediumtext' THEN -1 
	WHEN 'longtext' THEN -1 
	WHEN 'text' THEN -1 
	WHEN 'date' THEN 91 
	WHEN 'datetime' THEN 93 
	WHEN 'decimal' THEN 3 
	WHEN 'double' THEN 8 
	WHEN 'enum' THEN 12 
	WHEN 'float' THEN 7 
	WHEN 'int' THEN IF ( COLUMN_TYPE LIKE '%unsigned%', 4, 4 ) 	
	WHEN 'bigint' THEN -5 
	WHEN 'mediumint' THEN 4 
	WHEN 'null' THEN 0 
	WHEN 'set' THEN 12 
	WHEN 'smallint' THEN IF( COLUMN_TYPE LIKE '%unsigned%', 5, 5 ) 
	WHEN 'varchar' THEN 12 
	WHEN 'varbinary' THEN -3 
	WHEN 'char' THEN 1 
	WHEN 'binary' THEN - 2 
	WHEN 'time' THEN 92 
	WHEN 'timestamp' THEN 93 
	WHEN 'tinyint' THEN IF ( COLUMN_TYPE LIKE 'tinyint(1)%',- 7,- 6 ) 
	WHEN 'year' THEN 91 ELSE 1111 
	END DATA_TYPE,
IF (COLUMN_TYPE LIKE 'tinyint(1)%','BIT',UCASE(IF(COLUMN_TYPE LIKE '%(%)%',CONCAT(SUBSTRING( COLUMN_TYPE, 1, LOCATE( '(', COLUMN_TYPE ) - 1 ),SUBSTRING( COLUMN_TYPE, 1+ locate( ')', COLUMN_TYPE ) ) ),COLUMN_TYPE ) ) ) TYPE_NAME,
CASE	DATA_TYPE 	WHEN 'time' THEN IF( DATETIME_PRECISION = 0, 10, CAST( 11 + DATETIME_PRECISION AS signed INTeger ) ) 
	WHEN 'date' THEN 10 
	WHEN 'datetime' THEN IF( DATETIME_PRECISION = 0, 19, CAST( 20 + DATETIME_PRECISION AS signed INTEGER ) ) 
	WHEN 'timestamp' THEN IF( DATETIME_PRECISION = 0, 19, CAST( 20 + DATETIME_PRECISION AS signed INTEGER ) ) ELSE IF( NUMERIC_PRECISION IS NULL, LEAST( CHARACTER_MAXIMUM_LENGTH, 2147483647 ), NUMERIC_PRECISION ) END COLUMN_SIZE,
	65535 BUFFER_LENGTH,
	CONVERT ( CASE DATA_TYPE WHEN 'year' THEN NUMERIC_SCALE WHEN 'tinyint' THEN 0 ELSE NUMERIC_SCALE END, UNSIGNED INTEGER ) DECIMAL_DIGITS,
	10 NUM_PREC_RADIX,
IF( IS_NULLABLE = 'yes', 1, 0 ) NULLABLE,
	COLUMN_COMMENT REMARKS,
	COLUMN_DEFAULT COLUMN_DEF,
	0 SQL_DATA_TYPE,
	0 SQL_DATETIME_SUB,
	LEAST( CHARACTER_OCTET_LENGTH, 2147483647 ) CHAR_OCTET_LENGTH,
	ORDINAL_POSITION,
	IS_NULLABLE,
	NULL SCOPE_CATALOG,
	NULL SCOPE_SCHEMA,
	NULL SCOPE_TABLE,
	NULL SOURCE_DATA_TYPE,
IF( EXTRA = 'auto_increment', 'YES', 'NO' ) IS_AUTOINCREMENT,
IF( EXTRA IN ( 'VIRTUAL', 'PERSISTENT', 'VIRTUAL GENERATED', 'STORED GENERATED' ), 'YES', 'NO' ) IS_GENERATEDCOLUMN 
FROM
	INFORMATION_SCHEMA.COLUMNS 
WHERE
	( ISNULL( DATABASE ( ) ) OR ( TABLE_SCHEMA = DATABASE ( ) ) ) 
and ( TABLE_NAME LIKE 'm_dim_day' ) 
and (1=1)
ORDER BY
	TABLE_CAT,
	TABLE_SCHEM,
	TABLE_NAME,
	ORDINAL_POSITION
	
"
But the same sql ,i run in mysql ,it is ok .
i guess that the second column"NULL TABLE_SCHEM," is key, 
when i remove order by TABLE_SCHEM, the sql execute is ok and get the columns,
![image](https://user-images.githubusercontent.com/20455410/63157792-56ed0e80-c04a-11e9-93ac-15439d4f1815.png)

or change "NULL TABLE_SCHEM," into "1 TABLE_SCHEM," it is ok.
![image](https://user-images.githubusercontent.com/20455410/63158743-856be900-c04c-11e9-93f7-6d868e01c131.png)

**Comment by salsakran** [comment]
@xqwbx163 we technically don't support TIDB except insomuch as whatever you're experiencing is also a MySQL bug. 

There are a lot of databases that promise MySQL or PostgreSQL compatibility that don't actually deliver it, and while we're going to do our best to have them not break, we definitely haven't verified running Metabase on TIDB yet.

**Comment by xqwbx163** [comment]
@salsakran OK,i will push this bug to pingCAP tidb team.
but i wish that If you can modify it, it will be more perfect.

**Comment by camsaul** [comment]
Same issue as #9885
