### ISSUE TITLE
map visualizations fail if there are NULL values in the data

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1061]
we should try to make them more robust so that they don't fail in these cases.

**Comment by camsaul** [comment]
@agilliland do you have an example card or query :flushed:

**Comment by tlrobinson** [comment]
I can't reproduce this either:

```
hello=# create table lat_lon (lat float, lon float);
CREATE TABLE
hello=# insert into lat_lon values (38, -122);
INSERT 0 1
hello=# insert into lat_lon values (38.1, null);
INSERT 0 1
hello=#
```

![screenshot 2016-02-17 01 04 01](https://cloud.githubusercontent.com/assets/18193/13104529/93eaf6d4-d512-11e5-8a2f-f1d23591736c.png)

![screenshot 2016-02-17 01 04 17](https://cloud.githubusercontent.com/assets/18193/13104533/97aa2b96-d512-11e5-9862-7a4a3e7a2069.png)

**Comment by agilliland** [comment]
This was specifically for the geojson maps for state/country.  i'll take a look at it today.

**Comment by tlrobinson** [comment]
Hmm, still can't reproduce with state maps:

![screenshot 2016-02-17 12 53 50](https://cloud.githubusercontent.com/assets/18193/13124478/8625b22e-d575-11e5-888e-bcf92f647571.png)

**Comment by agilliland** [comment]
Cool.  if you tried that out and couldn't get it to happen then lets just close this.
