### ISSUE TITLE
Make it clearer that MB comes with Sample Dataset

### ISSUE THREAD

**Issue by flyingmachine** [metabase/metabase#10624]
**Is your feature request related to a problem? Please describe.**

While setting up MB I had the impression that I needed to connect to postgres. When I wasn't able to connect, I went to click "I'll add my data later" but was uncertain if there would be anything for me to play with without my having to connect to postgres. When I finished the wizard I was surprised (happily!) that there was sample data.

**Describe the solution you'd like**

A couple possibilities:

* Include `(optional)` in the `Add your data` header for step 2 of the wizard
* Change `I'll add my data later` to something like `I'll add my data later (you'll still be able to play the sample dataset)`

**How important is this feature to you?**

Not very

**Comment by brunobergher** [comment]
Handled in the setup redesigns of 2022, and more work happening here soon.
