### ISSUE TITLE
"Server error occurred" message when connecting to local Postgres

### ISSUE THREAD

**Issue by flyingmachine** [metabase/metabase#10623]
**Describe the bug**

With a MB instance running on docker, I tried to connect to a postgres db running on the docker host (my laptop) using the setup wizard. MB could not connect and displayed the message "Server error encountered"

**Logs**

```
08-19 19:17:01 DEBUG middleware.log :: POST /api/setup/validate 400 2 ms (0 DB calls)
{:errors {:dbname "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."}}
```

**To Reproduce**

1. Run dockerized MB
2. In the setup wizard, enter postgres connection details and click "next"

**Expected behavior**

An error message with more details. I think conveying the error message that postgres returns would have been more useful than "Server error encountered". I get that we're trying to improve error message handling overall, though :)

**Screenshots**

<img width="808" alt="Screen Shot 2019-08-19 at 3 12 37 PM" src="https://user-images.githubusercontent.com/1421/63292880-b0487e00-c294-11e9-91a6-c20d405c6c92.png">

**Information about your Metabase Installation:**

- Docker install
- OS X 10.14

**Severity**

Annoying

**Comment by flamber** [comment]
Hi @flyingmachine 
Looks like a duplicate of #8298 - if you agree, then please close this and upvote the other issue.

**Comment by flyingmachine** [comment]
@flamber you're right! :)
