### ISSUE TITLE
When I created a timed task to send to email, but prompted, Email needs to be set up as an administrator

### ISSUE THREAD

**Issue by telltime** [metabase/metabase#10637]
![aaaaaaaaaaa](https://user-images.githubusercontent.com/23161557/63322965-35946700-c357-11e9-9b35-50a304356bb1.png)

I am an admin user.
When I create a timed task to send an email, it prompts me that Email needs to be set up as an administrator.

**Comment by flamber** [comment]
Hi @telltime 
Which version of Metabase?
Did you setup email in Admin > Settings > Email?
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by salsakran** [comment]
That is displayed if there isn't an smtp connection set up in "Admin > Settings > Email

Closing since this isn't the appropriate place to ask for help in configuring Metabase
