### ISSUE TITLE
Settings are not consistent across multiple instances

### ISSUE THREAD

**Issue by flyingmachine** [metabase/metabase#10630]
**Describe the bug**

Pulled out from #10543 

Certain settings are cached or not updated across all instances when set, in particular some settings that use a custom `:setter`

* [ ] `site-locale`: https://github.com/metabase/metabase/blob/754b2dee81cc6930a828bf2d86234a929ed9ddb8/src/metabase/public_settings.clj#L79

**Additional context**

Start with

* [cache synchronization code](https://github.com/metabase/metabase/blob/master/src/metabase/models/setting/cache.clj#L33)
* [`update-setting!`](https://github.com/metabase/metabase/blob/master/src/metabase/models/setting.clj#L218)
* [locale "setting"](https://github.com/metabase/metabase/blob/master/src/metabase/util/i18n.clj#L16)

**Comment by flyingmachine** [comment]
It looks like the issue is:

1. Request comes in to update `site-locale`
2. The custom setter calls `set-locale`: https://github.com/metabase/metabase/blob/754b2dee81cc6930a828bf2d86234a929ed9ddb8/src/metabase/public_settings.clj#L79
3. `set-locale` updates the locale with `Locale/setDefault` for that instance and that instance alone https://github.com/metabase/metabase/blob/master/src/metabase/util/i18n.clj#L16
4. When other instances update their cache with the new locale, they don't call `set-locale` and therefore do not set the locale for that instance

Further evidence that this is happening is that if you refresh the settings page, the "language" dropdown value will be correct even if the language actually being used is incorrect:

<img width="638" alt="Screen Shot 2019-08-19 at 6 09 13 PM" src="https://user-images.githubusercontent.com/1421/63303036-b5b1c280-c2ac-11e9-939f-7f4960b58270.png">
<img width="602" alt="Screen Shot 2019-08-19 at 6 10 29 PM" src="https://user-images.githubusercontent.com/1421/63303037-b5b1c280-c2ac-11e9-9d41-5b7694f31a62.png">

Not sure what the best solution is here. One option would be to 

1. add an `:on-change` key to settings
2. add a watcher to the `cache*` atom that does a diff on the old and new cache and calls all relevant `:on-change` functions

The resulting `site-locale` setting definition would look something like this:

```clojure
(defsetting site-locale
  (str  (deferred-tru "The default language for this Metabase instance.")
        " "
        (deferred-tru "This only applies to emails, Pulses, etc. Users'' browsers will specify the language used in the user interface."))
  :type    :string
  :on-change (fn [old-value new-value] (set-locale new-value))
  :default "en")
```

**Comment by flyingmachine** [comment]
@camsaul would love your thoughts on this :)

**Comment by camsaul** [comment]
A watcher on the cache atom and an `:on-change` fn definitely sounds like it would be a good way to go about it. My only request is that you update the docstrings as well to make it clear that people need to add an `:on-change` for situations like this

**Comment by flyingmachine** [comment]
@camsaul what do you think of finding all references to `Locale/getDefault` (like the call to i18n/user-locale at https://github.com/metabase/metabase/blob/master/src/metabase/util/i18n.clj#L28) and replacing them with references to the `site-locale` setting?
