### ISSUE TITLE
Native Query - Timestamp formatting issue

### ISSUE THREAD

**Issue by MarouaneMan** [metabase/metabase#10638]
Hello,

Timestamp is not formatted as the specified rules in the Native Query, time is missing even if it's checked.

<img width="1062" alt="Capture" src="https://user-images.githubusercontent.com/6729798/63341363-5786ed00-c349-11e9-8bf1-fc6307155c7f.PNG">

Metabase version: 0.33
Field : timestampz
Database : Postgresql 11

Thank you

**Comment by salsakran** [comment]
@nindolabs can you share the raw results that are being graphed in that query?

**Comment by flamber** [comment]
Closing in favor of #11435
