### ISSUE TITLE
Help link in dropdown goes to 404

### ISSUE THREAD

**Issue by jrupp** [metabase/metabase#10641]
**Describe the bug**
It appears that the documentation for version 0.33.0 is not uploaded to metabase.com.

**To Reproduce**
1. Click on the gear icon in the top right
2. Click on 'Help'
3. Browser will navigate to https://metabase.com/docs/v0.33.0
4. Get 404 error page

**Expected behavior**
The documentation for v0.33.0 to load

**Information about your Metabase Installation:**
- Metabase version: v0.33.0

**Severity**
We just upgraded and our coworkers are going to want to read documentation on all the new features.

**Comment by flamber** [comment]
@jrupp The website has been updated with the 0.33 docs :tada:

**Comment by mazameli** [comment]
Yep, sorry about that! Closing as fixed.
