### ISSUE TITLE
Universal search can't find tables by Metabase friendly name

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#10665]
**Describe the bug**
Addition of tables to the universal search bar is great, but just found that it will only search on the actual table name, not the friendly name used everywhere else in Metabase. Note that these are the friendly names automatically generated by Meatbase, not manually overwritten.

**Logs**
No logs

**To Reproduce**
1. Have a table name in a database that maps to a friendly name with multiple words in Metabase e.g. "ServiceRequestType" in SQL Server -> "Service Request Type" in Metabase
2. In search bar type the friendly name as shown in the Admin > Data Model screen. e.g. "Service Request Type"
3. The table known everywhere in Metabase as "Service Request Type" is not listed
4. Search for the actual table name "ServiceRequestType" and the table is listed but not by it's friendly name.

**Expected behavior**
I would expect the search to be able to find tables based on how they are referenced in the rest of Metabase, i.e. by the friendly name.

**Screenshots**
Admin showing the table friendly name
![image](https://user-images.githubusercontent.com/4504437/63467166-f0884600-c4b8-11e9-9b7a-8a54a5a00a04.png)

Admin showing the actual table name
![image](https://user-images.githubusercontent.com/4504437/63467231-11509b80-c4b9-11e9-9971-cfa55d69bbde.png)

Searching by friendly name
![image](https://user-images.githubusercontent.com/4504437/63467263-2af1e300-c4b9-11e9-829f-766b4542bfe3.png)

Searching by actual table name
![image](https://user-images.githubusercontent.com/4504437/63467337-570d6400-c4b9-11e9-9919-fa7ce1b16c1c.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76.0.3809.100
- Your operating system: Windows 7
- Your databases: SQL Server
- Metabase version: v0.33.0
- Metabase hosting environment: Jar file on Windows
- Metabase internal database: H2

**Severity**
Annoyance. Users can't search for tables by the names they know them by. This limits the usefulness of the improved search function.

**Additional context**

**Comment by salsakran** [comment]
This isn't a bug per se, but an issue of an expected feature not being supported. 

It's relevant however.
