### ISSUE TITLE
"Deselect All" instead of/in addition to "Select All" in notebook

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#10668]
In Notebooks by default all columns are selected:
![Untitled](https://user-images.githubusercontent.com/15974735/63469002-0563cb80-c41e-11e9-888f-fa487222622f.png)

So having a "Deselect all" option is more needed than the current "Select All" option.

**Comment by flamber** [comment]
Hi @vvaezian Looks like a duplicate of #10460
