### ISSUE TITLE
"Add this question to a dashboard" model displayed when navigating "back" from dashboard to added question

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#10672]
When selecting a dashboard from the _Add this question to a dashboard_ modal, placing the question, and then hitting the browser's _Back_ button, the _Add this question to a dashboard_ modal is "still" being displayed on the question.

**To Reproduce**
1. Save a new question
2. When presented with the _Add this question to a dashboard_ model, select a dashboard.
3. Hit the browser's _Back_ button.
4. See the _Add this question to a dashboard_ modal displayed.

**Expected behavior**
The _Add this question to a dashboard_ modal should not be displayed when navigating back to an existing question in any way.

**Information about your Metabase Installation:**
- Browser version: Chromium Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

- Metabase version: metabase@f61bf25 (`release-0.33.x` branch)

**Comment by paulrosenzweig** [comment]
Fixed in #11707
