### ISSUE TITLE
Can't view dashboard card viz settings in Mac app

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10677]
[Originally reported on discourse](https://discourse.metabase.com/t/dashboard-issues-since-upgrading-to-0-33-0/7093/6). In the mac app, if you edit a dashboard and click the gear on a card to try and view the chart settings, you'll get a truncated modal like this:

![image](https://user-images.githubusercontent.com/2223916/63477654-03f4cc00-c43b-11e9-9e7f-2644f75b86f6.png)

This modal renders correctly when using the web app though:

![image](https://user-images.githubusercontent.com/2223916/63477694-2a1a6c00-c43b-11e9-9b50-a666b9f55781.png)

**Comment by paulrosenzweig** [comment]
Resolved by #10686
