### ISSUE TITLE
Filtering by current Year in MongoDB returns no results after upgrade to 0.33

### ISSUE THREAD

**Issue by kimus** [metabase/metabase#10683]
After upgrading to 0.33 some of my queries (answers) stopped working and return no results. After investigating (converting no native). I think the converted query has a error:

```
[
  {
    "$project": {
      ...
      "orderdate~~~year": {
        "$let": {
          "vars": { "column": "$orderdate" },
          "in": {
            "___date": {
              "$dateToString": { "format": "%Y", "date": "$$column" }
            }
          }
        }
      }
    }
  },
  { "$match": { "orderdate~~~year": { "$eq": { "___date": "2019-01-01" } } } },

  ... removed for brevity ...
```

there’s a miss match between format and filter.

1. the $match shoudn’t be something like?:
`{ "$match": { "orderdate~~~year": { "$eq": { "___date": "2019" } } } },`

2. or, the format shoud be:
`"$dateToString": { "format": "%Y-%m-%d", "date": "$$column" }`

**Comment by mazameli** [comment]
@flamber mentioned this might have been caused by https://github.com/metabase/metabase/pull/10561, @camsaul.
