### ISSUE TITLE
Include UTC offset in timezone selection

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#10685]
Metabase does not include the _Africa/Johannesburg_ timezone, so I have to choose one that is "closest". But the geographically closest city does is not always in the same timezone, and users (like me) don't always know which timezones those cities are in.

It would assist users in such situations if the UTC offset of each timezone was included in the timezones list.

This is not an important issue, but a minor user convenience.

Timezones are hard. :sweat_smile:

**Comment by flamber** [comment]
@walterl I think it's among other things what PR #8943 was trying to solve.

**Comment by walterl** [comment]
@flamber Yes, that would resolve part of the issue. I was just using _Africa/Johannesburg_ as an example, though. There will always be people living outside of the cities in any list of timezones like that, so this suggestion is rather looking towards hinting at the appropriate timezone in the UI, rather than focusing on specific timezones being missing.

**Comment by flamber** [comment]
Closing as fixed by PR #14429 in 0.38.0
