### ISSUE TITLE
Variable name in comment causes index error.

### ISSUE THREAD

**Issue by adjenks** [metabase/metabase#10694]
Variable name in comment causes index error.
I think this should be resolved in a way that still allows toggling of optional sections that do not need to contain the variable but are dependent on it. Like in examples 1 and 2.

![image](https://user-images.githubusercontent.com/10687569/63557099-213d9f00-c4fc-11e9-8370-e6a93918b121.png)

![image](https://user-images.githubusercontent.com/10687569/63553826-88eded00-c4f0-11e9-916b-9c4d821d760f.png)

![image](https://user-images.githubusercontent.com/10687569/63553941-d8ccb400-c4f0-11e9-8ab0-6d746e826c37.png)

![image](https://user-images.githubusercontent.com/10687569/63557086-1256ec80-c4fc-11e9-96c3-062d1c967e09.png)

**Comment by flamber** [comment]
Hi @adjenks 
It looks very similar to #7742

**Comment by adjenks** [comment]
@flamber Thank you, I think it is. Good catch.
