### ISSUE TITLE
0.33 ignores y axis range if values are outside of this range

### ISSUE THREAD

**Issue by sgvandijk** [metabase/metabase#10697]
**Describe the bug**
When auto y range is disabled and a manual range is set, this range is ignored if a data series has values outside of that range. Instead, the range is set to the minimum and maximum values of the series.

**To Reproduce**
1. Create a question that produces a series with any values between _a_ and _b_
2. Select 'Line' visualisation
3. Go to Settings -> Axes
4. Set a Min value higher than _a_ and/or a Max value less than _b_

**Expected behavior**
The y range adheres to the manually set values

**Screenshots**
![image](https://user-images.githubusercontent.com/157656/63611281-6ed90b00-c5d3-11e9-83c2-3170d53364a9.png)

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 68

- Your operating system: Ubuntu 18.04

- Your databases: MySQL

- Metabase version: 0.33

- Metabase hosting environment: Docker

- Metabase internal database: H2

**Severity**
Annoying - makes some plots difficult to read, or in need of having to be reworked/split into separate questions

**Comment by flamber** [comment]
Hi @sgvandijk 
This looks very similar to #10434

**Comment by paulrosenzweig** [comment]
@flamber thanks. I'll close in favor of that one.

Thanks for reporting @sgvandijk! This was a recent change to avoid some UI bugs, but I think we'll have to undo it or find a better work around. Feel free to subscribe to #10434 for updates.
