### ISSUE TITLE
Trend widget don't works with years

### ISSUE THREAD

**Issue by Oberonhive** [metabase/metabase#10699]
Trend widget shows `Group by a time field to see how this has changed over time` when grouping by years. Others groupings works fine. Any workaround for this? We massively use trend widget for year to year KPI.

![trend_year](https://user-images.githubusercontent.com/10414629/63612232-70f89500-c5e6-11e9-8fb1-796394025fae.gif)

**Comment by camsaul** [comment]
Fixed by #10722
