### ISSUE TITLE
Dashed, horizontal background grid lines in charts not showing up in Safari

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10707]
Safari on left, Chrome on right:

![image](https://user-images.githubusercontent.com/2223916/63629034-95437a00-c5c4-11e9-969c-8efd7b69004e.png)

**Comment by lukas104** [comment]
Even in Chrome, these lines are extremely hard to see and not very accessible. Removing the `opacity: .5` from `grid-line` improves this quite a bit.

**Comment by ranquild** [comment]
Works for me on Safari `v14.1.1`. @flamber I'll close this issue fyi
