### ISSUE TITLE
Troubleshooting server logs should line wrap

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10708]
When viewing the server logs, instead of the lines wrapping, they extended farther out horizontally resulting in horizontal scrollbars:

![logs-overflow](https://user-images.githubusercontent.com/2223916/63629801-59f77a00-c5c9-11e9-9c2d-1a5f60b0a22a.gif)

**Comment by kdoh** [comment]
I wasn't able to reproduce this when taking a fresh look off of master. I think https://github.com/metabase/metabase/pull/10845/commits/865bd3d1a739465b6fe5dc2ae8a2fd6670cafe37 in #10845 fixed this.
