### ISSUE TITLE
Pie chart overlap title and prevent clicking on it

### ISSUE THREAD

**Issue by Oberonhive** [metabase/metabase#10700]
Pie chart with turned off legend overlaps title. Chart ignoring vertical size of container.

![image](https://user-images.githubusercontent.com/10414629/63612665-760a1400-c5e7-11e9-8aeb-1a0d99d36ac0.png)

**Comment by paulrosenzweig** [comment]
@Oberonhive thanks for filing this issue! 

I just reproduced this on `v0.33.0`, but when I checked out the next release branch (`release-0.33.x`) the issue was fixed.

`v0.33.1` will be released in a few weeks with the fix. Sorry for any issues this is causing in the meantime!
