### ISSUE TITLE
Average Basic Metric Missing on Certain Tables

### ISSUE THREAD

**Issue by bvallelunga** [metabase/metabase#10710]
**Describe the bug**
On tables created a couple months ago, some of the basic metrics like averaging, sum of, etc are not available. On newly created tables (< 1 week old) these metrics are available for use.

**To Reproduce**
1. Go to 'Ask Question'
2. Click on 'Select a table'
3. Click on 'Summarize'
4. Notice some of the basic metrics are missing.

**Expected behavior**
I am expecting all basic metrics to be available on all tables, regardless of when they are created.

**Screenshots**
Table with All Basic Metrics
<img width="1469" alt="Screen Shot 2019-08-25 at 4 10 06 AM" src="https://user-images.githubusercontent.com/1920007/63649108-5e698300-c6ee-11e9-87bc-0147f59acbdd.png">

Table with Missing Basic Metrics
<img width="1352" alt="Screen Shot 2019-08-25 at 4 10 14 AM" src="https://user-images.githubusercontent.com/1920007/63649112-675a5480-c6ee-11e9-835b-6db6fd08e173.png">

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76.0.3809.100

- Your operating system: OSX 10.14.16

- Your databases: Postgres

- Metabase version: 0.33.0

- Metabase hosting environment: Kubernetes

- Metabase internal database: Postgres

**Severity**
Not very severe but is blocking our team.

**Comment by flamber** [comment]
Hi @bvallelunga 
The old tables, do they have any numeric columns (like `integer`, `decimal`, `float`)?
What are the Field Type of those column? Admin > Data Model > (database) > (table) > (column) :gear:

**Comment by bvallelunga** [comment]
Yes there are a couple that are integers which are used as foreign keys.

**Comment by flamber** [comment]
@bvallelunga Okay, but that means that you don't have any columns/fields that are actual metrics, which is why you don't see any of those metric options.

**Comment by bvallelunga** [comment]
Ahh I see. Makes sense. Closing the issue. Thank you for the help!
