### ISSUE TITLE
Metabase 0.33 Cannot use columns from "Join data" in Custom Expression

### ISSUE THREAD

**Issue by cfngiam** [metabase/metabase#10714]
**Describe the bug**
When you manually join a table using "Join data" - you cannot write a Custom Expression that contains fields from multiple table. Field / Column from joined table will not show up in Custom Expression

**To Reproduce**
1. Go to Ask a question / Custom question.
2. Pick a table, e.g. MainTable.
3. Create a Join data, e.g. JoinTable.
4. At Summarize section, click "Pick the metric you want to see" and choose Custom Expression.
5. Choose SUM, field from JoinTable is not included in the list. 

**Expected behavior**
The list of field from JoinTable should be included in the list for user to select in the Custom Expression. 

**Screenshots**

**Information about your Metabase Installation:**
- Metabase version: 0.33.0
- Metabase hosting environment: JAR

**Severity**
Not blocking but it should be part of the feature to allow Join data. 

**Additional context**
This is working fine for Basic Metrics, fields from Join Data are included.

**Comment by flamber** [comment]
Hi @cfngiam 
Looks like a duplicate of #5775 - if you agree, then upvote by clicking :+1: on the issue and close this.

**Comment by cfngiam** [comment]
> Hi @cfngiam
> Looks like a duplicate of #5775 - if you agree, then upvote by clicking 👍 on the issue and close this.

Agree, closing this now.
