### ISSUE TITLE
Filtered Records in the Field Filter Widget

### ISSUE THREAD

**Issue by SushantFc** [metabase/metabase#10727]
I am filtering data on the basis of form_name in a view view_form_fill_info.

This view has 25+ forms, I want the Widget for the Field Filter to only show a few particular Forms, and selection gives me data just for that form, the query I am using is.

Currently it gives me all the forms in the dropdown.

```
SELECT 
CASE Form_Name
    WHEN 'Data Story - Download' THEN 'DataStory-SRC'
    WHEN 'Dashboard - Download' THEN 'Dashboard-SRC'
    WHEN 'FusionExport Trial Download' THEN 'FusionExport'
    WHEN 'FusionTime Trial Download' THEN 'FusionTime'
    WHEN 'FusionCharts.net Download from dev centre' THEN 'FC.NET'
END AS form_name,cast(created_at as Date) as created_at,
count(*)
FROM
  (SELECT DISTINCT id, Form_Name, created_at
   FROM view_form_fill_info
   WHERE date(created_at) >= coalesce([[{{start_date}},]] DATE_SUB(CURDATE(), INTERVAL 7 DAY))
   AND date(created_at) <= coalesce([[{{end_date}},]] CURDATE())
   AND {{form}}
   AND email not like '%fusioncharts.com'
   AND (form_name LIKE '%- Download' or form_name in ('FusionExport Trial Download','FusionTime Trial Download','FusionCharts.net Download from dev centre')))a
GROUP BY Form_Name, cast(created_at as Date)
ORDER BY created_at DESC
```

**Comment by mazameli** [comment]
The way we'd looked at addressing this in the past, which we're still interested in doing, is connecting a field filter to a single-column saved question, whose results would be used to populate the selectable values for the filter:

https://github.com/metabase/metabase/issues/6820

I'd recommend anding a 👍reaction to that issue to show your support, and feel free to comment there if you have any additional thoughts, feedback or suggestions. I'll close this issue.
