### ISSUE TITLE
Conditional classification

### ISSUE THREAD

**Issue by Amo-MD** [metabase/metabase#10726]
Hi guys !
I was wondering if it was possible to use **if conditions** in a custom column?

**Example**:
Let's say that I have birthday date, I would like to create a column containing 0 or 1
- if birthday date is before 1980-01-01 -> 1
- else -> 0

Thank you in advance!

**Comment by Amo-MD** [comment]
Thanks for your answer! I will!

**Comment by mazameli** [comment]
Closing as a duplicate of #6331
