### ISSUE TITLE
Drill-thru filters does not work on joined tables

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10735]
**Describe the bug**
Drill-through filters on joined tables doesn't use aliased name, so it ends with error.

**To Reproduce**
1. Go to Custom question, select Sample Dataset and Orders
2. Join Products table and join People table, visualize.
3. Click a cell of one of the joined tables i.e. People->Email and select `=` in the drill-down.
4. Shows the error `Column "PUBLIC.PEOPLE.EMAIL" not found`
5. Remove that filter and create the exact same filter, but via the Filter sidebar and it works.

**Expected behavior**
Should behave like the Filter sidebar, which uses the aliased table name.

**Information about your Metabase Installation:**
Dev setup of `release-0.33.x` (commit bbd268b24eec98745952ce0dc5360faaea5b3925) with Firefox 68 on Ubuntu.

**Additional context**
Seems like it's friends with #10017

**Comment by mazameli** [comment]
Reproduced.

**Comment by notrom** [comment]
Hi, I see some good work on resolving this which is great. There's also the likely related similar issue of drill down by "View these Orders" when clicking on an aggregate value of the same join. Will these changes resolve this too?

**To Reproduce**
- Go to Custom question, select Sample Dataset and Orders
- Join Orders table and join People table
- Summarise "Count of rows" by joined User -> Source, visualise
- Click a count, then "View the Orders"
- Shows the error `Column "User.SOURCE" not found`

Remove the manual join from the query builder and use the one as defined in the data model for the group by and the drill down works as expected.

**Metabase Version**
v0.33.3

Seems related to me so didn't want to raise a new ticket if this already fixes it.

Thanks

**Comment by flamber** [comment]
This is fixed in 0.33.3 - just wasn't closed. I cannot reproduce on `release-0.33.x` (commit 445da0e12674c909fbd2e53cd7b028dfdc67c0f3)

@notrom Your issue sounds a lot like #10871 - the error has just changed (adding a comment).
