### ISSUE TITLE
Diacritics in a user's name prevent a user's personal collection from being created via LDAP SSO

### ISSUE THREAD

**Issue by RichardKlem** [metabase/metabase#10738]
**Description of the bug**
The bug is probably that after new user's LDAP sign-up the proper row in collection table is not added.
After new user signs up with LDAP to Metabase all access to people management is not available and a error message is shown:

> Output of user->personal-collection does not match schema: \n\n\t   (not (instance? metabase.models.collection.CollectionInstance nil)) \n\n

I have to add manually a new row into `collection`table in the metabase database with proper content. After that the problem is gone/solved. 

**Logs**
`Aug 28 10:33:33 ERROR metabase.middleware.log :: GET /api/user 500 18 ms (6 DB calls) 
{:value nil,
 :error (not (instance? metabase.models.collection.CollectionInstance nil)),
 :message "Output of user->personal-collection does not match schema: \n\n\t   (not (instance? metabase.models.collection.CollectionInstance nil))  \n\n",
 :type clojure.lang.ExceptionInfo,
 :stacktrace
 ("--> models.collection$fn__31791$user__GT_personal_collection__31796.invoke(collection.clj:1024)"
  "models.collection$fn__31815$user__GT_personal_collection_id_STAR___31820$fn__31821.invoke(collection.clj:1047)"
  "models.collection$fn__31815$user__GT_personal_collection_id_STAR___31820.invoke(collection.clj:1045)"
  "models.collection$include_personal_collection_ids$iter__31855__31859$fn__31860$fn__31861.invoke(collection.clj:1078)"
  "models.collection$include_personal_collection_ids$iter__31855__31859$fn__31860.invoke(collection.clj:1076)"
  "models.user$add_group_ids.invokeStatic(user.clj:163)"
  "models.user$add_group_ids.invoke(user.clj:157)"
  "api.user$fn__63764.invokeStatic(user.clj:69)"
  "api.user$fn__63764.invoke(user.clj:53)"
  "middleware.auth$enforce_authentication$fn__46209.invoke(auth.clj:14)"
  "routes$fn__64248$fn__64249.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__46165.invoke(exceptions.clj:104)"
  "middleware.exceptions$catch_api_exceptions$fn__46162.invoke(exceptions.clj:92)"
  "middleware.log$log_api_call$fn__46083$fn__46084.invoke(log.clj:170)"
  "middleware.log$log_api_call$fn__46083.invoke(log.clj:164)"
  "middleware.security$add_security_headers$fn__46126.invoke(security.clj:105)"
  "middleware.json$wrap_json_body$fn__46292.invoke(json.clj:61)"
  "middleware.json$wrap_streamed_json_response$fn__46310.invoke(json.clj:97)"
  "middleware.session$bind_current_user$fn__46424$fn__46425.invoke(session.clj:193)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:176)"
  "middleware.session$do_with_current_user.invoke(session.clj:170)"
  "middleware.session$bind_current_user$fn__46424.invoke(session.clj:192)"
  "middleware.session$wrap_current_user_id$fn__46413.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__46398.invoke(session.clj:123)"
  "middleware.auth$wrap_api_key$fn__46217.invoke(auth.clj:27)"
  "middleware.misc$maybe_set_site_url$fn__46190.invoke(misc.clj:56)"
  "middleware.misc$bind_user_locale$fn__46193.invoke(misc.clj:72)"
  "middleware.misc$add_content_type$fn__46178.invoke(misc.clj:28)"
  "middleware.misc$disable_streaming_buffering$fn__46201.invoke(misc.clj:87)")}`

**To Reproduce**
1. New user signs up with LDAP. (after that the error occurs)

**Expected behavior**
After new user signs up with LDAP to Metabase all access to people management is not available and cannot see Al personal collections 

**Information about our Metabase Installation:**
- Our browser and the version: (Firefox 68.0.2 (64-bit))

- Our operating system: Debian 9.9, Centos 7.6

- Our databases: MariaDB

- Metabase version: 0.32.10

- Metabase hosting environment: Linux

**Severity**
It is blocking user's management and viewing All personal collections.

**Additional context**
We had that problem in the past while we were trying to update our Metabase over many updates(about 1 year of non updating) all at once. After that failure we have updated Metabase by steps and everything looked good. Now after new user signed up, the same problem have occurred again. We have been very lucky that we have found out a solution(adding data into your=Metabase database). 

Thank you for solving that bug!
Richard

**Comment by RichardKlem** [comment]
I've found out that it is probably caused by diacritics in user name. New user without diacritics inside his name signed in the Metabase and any problem had occurred. So maybe there is something wrong with text coding. Also I have found out that names with diacritics have question mark at some diacritics character position in admin-mode bookmark People. Hope it will help you.

**Comment by camsaul** [comment]
Same underlying issue as #10691

**Comment by camsaul** [comment]
Fixed by #11753
