### ISSUE TITLE
How Does Metabase's Caching & Cache Clearing Work?

### ISSUE THREAD

**Issue by sharedphysics** [metabase/metabase#10745]
Curious as to how is caching was technically set up in Metabase? 
- Are cached results written into a temporary table? 
- After the cache expires, is that table flushed/dumped or does it remain and get overwritten next time the query runs? 
- Is there a default cache dump/flush/expire time?
- Is the cache default on all questions or only those running at least 2 minutes/what anyone else sets? 

I tried to follow https://github.com/metabase/metabase/pull/4490 and https://github.com/metabase/metabase/issues/1666 and https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/cache_backend/db.clj but wasn't able to conclusively understand the mechanics. 
Thanks!

**Comment by sharedphysics** [comment]
@flamber - Good to know. I think that addresses my issue.

For the record for anyone doing a `PII`/`PHI`/`HIPAA` audit, it should be noted that identifiable information might be inadvertently saved and persisted in the metabase database itself then.

Are there any thoughts on having an admin option to flush/cleanup caches and clear this data manually?

**Comment by flamber** [comment]
@sharedphysics 

If you have to comply to various standards, then you should know what an application does before putting it into production, but that's out of scope of this issue :smile: 
I have done enough audits of huge companies to know that it's usually the last thing anyone thinks of.

As for flushing cache, that's already available:
Admin > Databases > (database) > Discard saved field values
And if you want to disable saving field values, then activate "This is a large database, so let me choose when Metabase syncs and scans" and click Save, which gives you a Scheduling-tab, and here you can disable Scanning for Filter Values.
