### ISSUE TITLE
Replace use of deprecated Nashorn

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#10749]
Nashorn is [deprecated](https://openjdk.java.net/jeps/335) and will be removed at some point in the future. Oracle recommends [switching to GraalVM](https://www.infoworld.com/article/3291322/oracle-switch-now-from-nashorn-javascript-engine-to-graalvm.html).

Nashorn is currently only used in Metabase for rendering pulses in the back-end.

This is not urgent but should be addressed at some point before we start supporting a JVM version in which Nashorn has been removed.

**Comment by flamber** [comment]
Fixed by #15708
