### ISSUE TITLE
No favicon when non-root path

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#10743]
I've tried to use Metabase 0.33 in non-root path with appropriate URL in Metabase Admin panel and docker env. But the icon isn't loaded as expected.

Example:
![image](https://user-images.githubusercontent.com/1708680/63862458-4a0adc00-c9b5-11e9-9b29-4921d696af99.png)

![image](https://user-images.githubusercontent.com/1708680/63862244-f3050700-c9b4-11e9-83e0-a0eeb07d711b.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by dannyeuu** [comment]
Ayn update here @flamber ?

**Comment by rhclayto** [comment]
Why not just make the link elements href relative paths rather than absolute? The template is here: https://github.com/metabase/metabase/blob/master/resources/frontend_client/index_template.html
