### ISSUE TITLE
I should be able to reference joined columns in custom column widget

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10759]
This is on `release-0.33.x`. This might be a duplicate or related to https://github.com/metabase/metabase/issues/6164, and is somewhat related to https://github.com/metabase/metabase/issues/5775.

I've joined two time series saved questions to each other: `count of users per month` and `count of twitter users per month`. What I'd like to do next is add a custom column to divide the latter count column by the former in order to get the ratio each month of what percent of my users came from twitter.

The problem, which I believe is a bug, is that the `count` column from the joined saved question doesn't show up as a valid referenceable column:

![image](https://user-images.githubusercontent.com/2223916/63963707-6f95f500-ca4a-11e9-9af5-c9a5d815fdcf.png)

Trying to manually type in the display name of the joined count column does not work either: 

![image](https://user-images.githubusercontent.com/2223916/63964038-1a0e1800-ca4b-11e9-9aff-5ccf9e28fe48.png)

**Comment by EBoisseauSierra** [comment]
Note that there is no need to join two data sets to reproduce the bug: using the same aggregation (sum, count, etc.) over 2 metrics on a single dataset creates the same situation (see #10908)
