### ISSUE TITLE
Unable to move collections for saved queries

### ISSUE THREAD

**Issue by nfrimando** [metabase/metabase#10763]
**Describe the bug**
Moving queries from a personal collection to a public collection has options to do so, but upon saving the move and refreshing the question, the question remains saved in the personal collection

**Logs**
Metabase Version: v0.33
Run on Docker Image (Hosted in Digital Ocean Server)
Chrome Browser

**To Reproduce**
1. Go to saved question in personal collection
2. Click on pencil icon beside question name
3. Click on move
4. Select a public collection
5. Click move on the modal
6. Save question
7. Refresh
8. See that question did not move

**Expected behavior**
The collection of the question has moved

**Information about your Metabase Installation:**
- Your browser: Chrome
- Your databases: Postgres
- Metabase version: v0.33
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
It is blocking permissions management.

**Comment by flamber** [comment]
Confirmed on latest `release-0.33.x`. Also, the move modal feels like it will move the question upon clicking the blue "Move" button, but you have to "Save" the question after (if it worked).
Temporary work-around: Go to the collection, hover the question and click `...` and "Move this item".

**Comment by paulrosenzweig** [comment]
Fixed in  #10832
