### ISSUE TITLE
X-axis on saved charts is obscured by the footer until it's resized

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10762]
Whenever I open a saved question on `release-0.33.x` if it's an x/y chart of any kind, the x-axis labels are covered up by the footer UI elements until I either resize the browser window or cause the chart to rerender by opening up a sidebar.

![image](https://user-images.githubusercontent.com/2223916/63873978-769f0380-c975-11e9-96f2-32b5eadd0573.png)

**Comment by paulrosenzweig** [comment]
Fixed by #10890
