### ISSUE TITLE
Stacked-Bar & Scatter charts duplicate breakout labels

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#10761]
Breakout labels double in focus pop-ups for Stacked-Bar & Scatter charts when using "Native query" option to build a question on added database.  Curiously this doesn't happen for the Sample database.  Code to reproduce below, screenshots at 
https://discourse.metabase.com/t/stacked-bar-scatter-charts-duplicate-breakout-labels/7192
(GitHub no longer supports Firefox 52.9.0, the highest available for Win 6)

Metabase: v0.33.0
Host: Localhost:3000
Databases: H2 internal default, Server SQL added
Browser: Firefox 52.9.0
OS: Microsoft Windows [Version 6.0.6002]

<b>/*Table create & populate script using added database (e.g. SQL Server)*/</b>
<code>
USE [MyDatabase]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TEST_TABLE](
	[VARIETY] [nvarchar](255) NULL,
	[CATEGORY] [nvarchar](255) NULL,
	[PRICE] [float] NULL,
	[QUANTITY] [float] NULL
) ON [PRIMARY]

INSERT INTO [MyDatabase].[dbo].[TEST_TABLE] (VARIETY, CATEGORY, PRICE, QUANTITY)
VALUES 
('RED', '16 SIZE', 250, 3714.4),
('RED', '16.5 SIZE', 264.88, 10427.2),
('RED', '17 SIZE', 326.97, 3688.3),
('RED', '18 SIZE', 332.87, 37080.8),
('RED', '18-19 SIZE', 350, 476.3),
('BLUE', '22 SIZE', 350, 1930.9),
('BLUE', '23 SIZE', 409.1, 3069.5),
('BLUE', '23-24.5 SIZE', 400, 921.8),
('RED', '23.5 SIZE', 450, 1937.7),
('RED', '23.5-24.5 SIZE', 450, 2749.9),
('BLUE', '24-26 SIZE', 350, 13158.8),
('BLUE', 'CUSTOM', 352.84, 16439.4),
('RED', 'CUSTOM', 287.29, 96422.2)

GO
</code>

<b>/*SQL for question using added database (e.g. SQL Server)*/</b>
<code>
SELECT 
[VARIETY], 
[CATEGORY], 
[PRICE], 
[QUANTITY]

FROM [MyDatabase].[dbo].[TEST_TABLE]
</code>

<b>/*SQL for question using Sample database*/</b>
<code>
SELECT "PUBLIC"."PRODUCTS"."VENDOR" AS "VENDOR", "PUBLIC"."PRODUCTS"."RATING" AS "RATING", 
"PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", "Orders"."QUANTITY" AS "QUANTITY", 
"PUBLIC"."PRODUCTS"."PRICE" AS "PRICE", 
sum("Orders"."QUANTITY") AS "sum"

FROM "PUBLIC"."PRODUCTS"
LEFT JOIN "PUBLIC"."ORDERS" "Orders" ON "PUBLIC"."PRODUCTS"."ID" = "Orders"."PRODUCT_ID"

WHERE ("Orders"."QUANTITY" BETWEEN 20 AND 30 
AND "PUBLIC"."PRODUCTS"."PRICE" BETWEEN 20 AND 30)

GROUP BY "PUBLIC"."PRODUCTS"."VENDOR", "PUBLIC"."PRODUCTS"."RATING", 
"PUBLIC"."PRODUCTS"."CATEGORY", "Orders"."QUANTITY", "PUBLIC"."PRODUCTS"."PRICE"
</code>

**Comment by MarcGJA** [comment]
<b>Scatter Plot>Settings>Show label on y-axis</b> -- Does not attach the label when required nor upon refresh.  Manually typing in a label is the only workaround.

**Comment by flamber** [comment]
@MarcGJA 
Why did you post here after I already replied to your forum post?
This will be fixed by #10555
![Screenshot_00001](https://user-images.githubusercontent.com/1447303/63991008-5cfbda00-caa3-11e9-9f09-5ab5b076ec3b.png)
As for the missing y-axis label, that should be a separate issue, but I can reproduce that, so please create an issue for it :+1:

**Comment by MarcGJA** [comment]
Thanks @flamber, you are right this issue will be fixed by Pull Request 10555. I didn't spot the non-consecutive tooltip label duplication until my own wrangling with this also began producing different patterns. In any event I'll post the Y-axis issue separately on GitHub (only).

**Comment by flamber** [comment]
@MarcGJA Great. Please close this issue :+1:
