### ISSUE TITLE
Y-axis label requires manual entry (v0.33.0)

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#10765]
<b>Scatter Plot>Settings>Show label on y-axis</b> -- Does not attach the label when required nor on reset. Manually typing in a label seems the only workaround.

Metabase: v0.33.0
Host: Localhost:3000
Databases: H2 internal default, Server SQL added
Browser: Firefox 52.9.0
OS: Microsoft Windows [Version 6.0.6002]

**Comment by flamber** [comment]
It's not specific to scatter, same goes for line/bar charts.
Reproduce with Sample Orders - Count of rows by Created At: Year and Product → Category

**Comment by mazameli** [comment]
Repro'd, but only when the chart has a single metric and two dimensions — i.e., when there's a series breakout.
