### ISSUE TITLE
Timezone settings for each user

### ISSUE THREAD

**Issue by rfitsyk** [metabase/metabase#10779]
Hi!

There is a need to consider time zones for users located in different countries.
It's can be implemented as user local option instead of current global:

![image](https://user-images.githubusercontent.com/36033262/64105257-8dcb6000-cd7e-11e9-9f26-d981072d1346.png)

Have you considered the development of this feature in future versions?

Thanks.

**Comment by flamber** [comment]
@mazameli Isn't it a duplicate of #4284?

**Comment by mazameli** [comment]
Great catch, thanks!

**Comment by rfitsyk** [comment]
Sorry for duplication :(
