### ISSUE TITLE
Send pulses at times that are not "on the hour"

### ISSUE THREAD

**Issue by dataxpress** [metabase/metabase#10775]
**Is your feature request related to a problem? Please describe.**
My database runs its update and processing jobs on the hour, for example 7:00am, 8:00am. I have a Metabase pulse that references tables that are being updated during these jobs, and my 8:00am Pulse sometimes returns different data depending on the status of these jobs.

**Describe the solution you'd like**
I'd like the ability to set the Pulse to send at 7:55am or 8:25am so that it doesn't execute until I know the rest of the data is in the clear

**Describe alternatives you've considered**
I could change my data warehouse setup to not run jobs on the hour, but it feels wrong to change the data source to accommodate my analytics tools.

**How important is this feature to you?**
This feature is not very important, but it also seems like a minor UI improvement that could make an existing feature more powerful for a very small investment.

**Additional context**
I haven't updated to 0.33 yet so apologies if this is already fixed! I am going to look into making a pull request for this myself but I am unfamiliar with the code base so might not be the best person for the job.

Thank you so much for everything the Metabase team and community does!

**Comment by flamber** [comment]
Hi @dataxpress 
This is duplicate of #3846 - check some of the comments, which contains UI proposals.
Upvote by clicking :+1: on the first post - and please close this issue.

**Comment by dataxpress** [comment]
> Hi @dataxpress
> This is duplicate of #3846 - check some of the comments, which contains UI proposals.
> Upvote by clicking 👍 on the first post - and please close this issue.

Thank you so much, will do!
