### ISSUE TITLE
Combining multiple questions on the same card doesn't load if one of them returns null

### ISSUE THREAD

**Issue by nogaz-gc** [metabase/metabase#10774]
**Description**
I have a few Number visualizations that are combined in the same card as a bar chart, the dashboard also has a filter which can result in some of the questions returning no results. When this happens the dashboard is stuck in loading.

**Logs**
The following error appears in the console:
`Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at app-main.bundle.js?0d1325582067a4b57db2:5
    at Array.map (<anonymous>)
    at Function.value (app-main.bundle.js?0d1325582067a4b57db2:5)
    at t.getVisualizationTransformed (app-main.bundle.js?0d1325582067a4b57db2:5)
    at t.value (app-main.bundle.js?0d1325582067a4b57db2:5)
    at t.value (app-main.bundle.js?0d1325582067a4b57db2:5)
    at updateComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u.receiveComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at Object.receiveComponent (vendor.bundle.js?0d1325582067a4b57db2:1)
    at u._updateRenderedComponent (vendor.bundle.js?0d1325582067a4b57db2:1)`

**Expected behavior**
Option 1:
Any series that doesn't have results is ignored, and only the series with results appear in the dashboard. (If all of them return None then the card should appear with "No results")

Option 2:
Show all of the series that didn't have any results on the card with 0

**Information about your Metabase Installation:**
- Chrome version 76.0.3809.132 (Official Build) (64-bit)
- DB: MongoDB
- Metabase version: v0.32.9

**Comment by flamber** [comment]
Hi @nz1234 
It looks very similar to #4488.
But I cannot reproduce on latest `release-0.33.x`, which will become the upcoming 0.33.1 next week.

**Comment by nz1234** [comment]
Hi @flamber , It's still happening after updating to 0.33.2. Multiple questions on the same chart fail loading when some of them return None

**Comment by flamber** [comment]
@nz1234 
I'm not sure if it has something to do with MongoDB specifically, but I've tried multiple ways to reproduce the issue with Sample Dataset (Orders) without success:
![image](https://user-images.githubusercontent.com/1447303/64925351-780d6000-d7ac-11e9-825f-fb1bb92d20dd.png)

**Comment by nz1234** [comment]
It could be specific to MongoDB, I see that the empty query returns with `data: {rows: []}` instead of `data: {rows: [[]]}` and it crashes when trying to access rows[0][0]. 
This problem is only when you combine multiple queries in a bar chart, the empty question on it's own is displayed properly.

I'm attaching the full json if it helps:
`{
	"database_id": 8,
	"started_at": "2019-09-16T07:31:02.827Z",
	"json_query": {
		"constraints": {
			"max-results": 10000,
			"max-results-bare-rows": 2000
		},
		"type": "query",
		"middleware": {
			"userland-query?": true
		},
		"database": 8,
		"query": {
			"source-table": 38,
			"filter": ["and", ["=", ["field-id", 769], 1], [">=", ["field-id", 763], 1000]],
			"aggregation": [["count"]]
		},
		"parameters": [{
				"type": "category",
				"target": ["dimension", ["field-id", 790]],
				"value": " A"
			}
		],
		"async?": true,
		"cache-ttl": null
	},
	"average_execution_time": null,
	"status": "completed",
	"context": "question",
	"row_count": 0,
	"running_time": 121,
	"data": {
		"rows": [],
		"native_form": {
			"projections": ["count"],
			"query": [{
					"$project": {
						"b_total": "$b_total",
						"c_status": "$c_status"
					}
				}, {
					"$match": {
						"$and": [{
								"b_total": {
									"$gte": 1000
								}
							}, {
								"c_status": {
									"$eq": " A"
								}
							}
						]
					}
				}, {
					"$group": {
						"_id": null,
						"count": {
							"$sum": 1
						}
					}
				}, {
					"$sort": {
						"_id": 1
					}
				}, {
					"$project": {
						"_id": false,
						"count": true
					}
				}
			],
			"collection": "D",
			"mbql?": true
		},
		"cols": [{
				"base_type": "type/Integer",
				"special_type": "type/Number",
				"name": "count",
				"display_name": "Count",
				"source": "aggregation",
				"field_ref": ["aggregation", 0]
			}
		],
		"results_metadata": {
			"checksum": "OhbjoAhcaa8fmLcv9HbVKw==",
			"columns": [{
					"name": "count",
					"display_name": "Count",
					"base_type": "type/Integer",
					"special_type": "type/Quantity",
					"fingerprint": {
						"global": {
							"distinct-count": 0,
							"nil%": null
						},
						"type": {
							"type/Number": {
								"min": null,
								"max": null,
								"avg": null,
								"sd": null,
								"q1": null,
								"q3": null
							}
						}
					}
				}
			]
		},
		"insights": null
	}
}
`

**Comment by sbelak** [comment]
`rows` being [] is consistent with what other drivers would return in this case (and semantically correct -- [[]] would be inconsistent with what the `cols` say). I can't repo it either though. Have tried having the no results one both as the initial card and the one layered on top.

**Comment by flamber** [comment]
@nz1234 Can you still reproduce this on 0.34.3? Can you reproduce it with Sample Dataset and provide the steps, so I can reproduce?
