### ISSUE TITLE
Seperate Front end Back end

### ISSUE THREAD

**Issue by binodsarkar** [metabase/metabase#10784]
Hi all,
Can you please help me to separate front end and back end. I want to work on front end only.

https://github.com/metabase/metabase/issues/new/choose

**Comment by mazameli** [comment]
If you're asking how to build just the front end, you can find instructions for building Metabase from the source code here: https://github.com/metabase/metabase/blob/master/docs/developers-guide.md

The best place for asking general questions is on our [discussion forum](https://discourse.metabase.com/).
