### ISSUE TITLE
Trend tile on dashboard differs from tile on full screen

### ISSUE THREAD

**Issue by conradhagemans** [metabase/metabase#10786]
**Describe the bug**
I created a Trend tile. Shown correctly on the dashboard

![Screenshot 2019-09-03 at 10 34 31](https://user-images.githubusercontent.com/9007177/64157304-c595de80-ce36-11e9-9ee7-aa01bcf4df51.png)

But when I go to full screen mode the tile is shown different and is missing info.

![Screenshot 2019-09-03 at 10 34 45](https://user-images.githubusercontent.com/9007177/64157341-d9d9db80-ce36-11e9-87eb-4be54a5d0570.png)

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 68.0.2
- Your operating system: Ubuntu 18.04
- Your databases: MySQL
- Metabase version: 0.33
- Metabase hosting environment: Docker,
- Metabase internal database: (H2 (default)

**Severity**
This is annoying, blocking some users

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by paulrosenzweig** [comment]
@sbelak it looks like this [fullscreen logic](https://github.com/metabase/metabase/blob/fix-9314/frontend/src/metabase/visualizations/visualizations/SmartScalar.jsx#L198) was added with the original [Superscalars PR](https://github.com/metabase/metabase/pull/8383/files#diff-ef94ea39c7085f620ca6fdacc7a2f0eeR179). Any recollection of why we wanted fullscreen display to be different?
