### ISSUE TITLE
[Epic] Option for restricting pulse recipients to those in the same group

### ISSUE THREAD

**Issue by PalomaSystems** [metabase/metabase#10795]
Edit Apr/23 . [Product doc](https://www.notion.so/metabase/New-Subscriptions-and-Alerts-permissions-send-only-to-same-group-members-7bd5fe0dfea54a87a914c3d71b59a414)

```[tasklist]
### Tasks
- [x] Add FE toggle in admin settings for restricting pulse recipients to those in the same group
```

--

Currently when a user is creating a pulse and chosing the recipients they are presented with a list of all Metabase users. We need this to just be restricted to those in the same group as the user.

Could an option be added to the permissions tab to allow the restriction of this list to either just those in their group.

Alternatively add another category to a user account such as Mailshot or Mail Groups.

It is currently stopping us from roling Metabase out organisation wide as certain users would not find it acceptable that everyone could see their name in the list.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by Olaktal** [comment]
Hello,
We have exactly the same issue: we can't allow people to create pulses for people out of their group.
Any advance on this subject ?

**Comment by robfras** [comment]
Same issue here

**Comment by robfras** [comment]
This issue is important to our company as it is the only obstacle to start sharing metabase accesses across multiple client companies for our commercial datasets. We can contribute to the development after a discussion on the impact on the overall system.

**Comment by dker92** [comment]
Yeah I got the same issue

**Comment by silversilver** [comment]
Very much need this resolved as it is a privacy issue exposing user's information outside the zone they have permission too.

**Comment by flamber** [comment]
Very related to #6744

**Comment by krsnik93** [comment]
Furthermore, it's possible to set any email address as the recipient, does not even have to be using Metabase, regardless of the group etc.

**Comment by luizarakaki** [comment]
Should close #27779

**Comment by EmmadUsmani** [comment]
https://github.com/metabase/metabase/pull/32432 merged into master
