### ISSUE TITLE
Line/area/bar option in scatterplot visualization has weird UX

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10790]
![image](https://user-images.githubusercontent.com/2223916/64135248-325b9b00-cd9b-11e9-9a84-ec2b04aa051d.png)

Currently if you click on the line/area/bar icons, you can't get back to using circles as the scatterplot's marks. We should either remove this button group on scatterplot charts, or add circles/bubbles as a fourth option (since they're all x/y charts, and you're really just changing the marks on the chart, with different suboptions for different marks).

**Comment by paulrosenzweig** [comment]
@mazameli adding a fourth button here makes sense to me! I'm guessing I should just use the same icon as this?
![image](https://user-images.githubusercontent.com/691495/64998067-bc822400-d8b0-11e9-8e78-193e6e103675.png)

**Comment by mazameli** [comment]
I think that just adding a fourth option without moving things around slightly to accommodate that fourth option is probably going to make things cramped here. Let me confer with @salsakran and @kdoh about these series options before we make a move here.

**Comment by flamber** [comment]
This is also the case for Row - should it have a separate issue or will this cover?
If Row-viz, in Settings>Display, click Line-icon, and then change to Bar-viz, then it shows as Line-viz

**Comment by mazameli** [comment]
@flamber I'd call that a bug. I'll open an issue for it. Thanks as always for catching that. 👍

**Comment by brunobergher** [comment]
Not applicable after one of the viz settings redesigns.
