### ISSUE TITLE
Line & Bar visualizations broken after upgrading to v0.33.1

### ISSUE THREAD

**Issue by javiercr** [metabase/metabase#10804]
**Describe the bug**
After upgrading from 0.33.0 to 0.33.1 some of our existings questions containing line and bar charts are broken displaying an error like this:

![image](https://user-images.githubusercontent.com/855995/64327158-84830300-cfcb-11e9-806c-046275a8b1e2.png)

**Logs**
I can't see any relevant logs in the browser console, nor in the metabase logs. Just the error in the screenshot, where 

**To Reproduce**
I haven't been able to reproduce the issue, as it seems it doesn't happen with new questions.

**Expected behavior**
It should show the chart and not an error :)

**Information about your Metabase Installation:**
- Using the metabase `v0.33.1` Docker image on a kubernetes cluster
- Metabase internal database: H2

**Severity**
I think it's a big deal and some users would prefer to wait before upgrading to v0.33.1 to not break their dashboards.

PS: metabase is amazing, thank you for it!

**Comment by kritop** [comment]
same here too, they questions are loading without error but no bar chart is being displayed if i try to stack them and have multiple series.

**Comment by paulrosenzweig** [comment]
Fixed by #10809. We'll try to get the fix released soon!
