### ISSUE TITLE
Pie charts significantly larger after update to 0.33

### ISSUE THREAD

**Issue by vrsttl** [metabase/metabase#10802]
**Describe the bug**
Pie charts are significantly larger across all dashboards since the upgrade to 0.33

**To Reproduce**
Upgrade 0.32 -> 0.33

**Information about your Metabase Installation:**
- Your browser and the version: All major browsers
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.33
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

90% of our visualizations are pie charts. This is a severe issue.

![piecharts](https://user-images.githubusercontent.com/36707938/64318992-a3799900-cfbb-11e9-8487-81c48831b247.png)

**Comment by paulrosenzweig** [comment]
@vrsttl this should be fixed in 33.1, which was just released. Let us know if you still see any issues after upgrading though!

**Comment by vrsttl** [comment]
> @vrsttl this should be fixed in 33.1, which was just released. Let us know if you still see any issues after upgrading though!

33.1 - Search bar didn't work, on saving a modified question the following happened. Quickly reverted to 33.0 and restyled all the charts instead.
![mberror](https://user-images.githubusercontent.com/36707938/64406117-49430b80-d081-11e9-90b3-4797c8adfef2.png)

**Comment by flamber** [comment]
@vrsttl The search and save issue was fixed in 0.33.2 released earlier today.

**Comment by vrsttl** [comment]
@flamber Thank you!
