### ISSUE TITLE
Download full results of a Query to CSV or XLSX - Excel does not recognize the Timestamp format

### ISSUE THREAD

**Issue by grimete** [metabase/metabase#10803]
Download full results of a Query to CSV or XLSX - Excel does not recognize the Timestamp format

**To Reproduce**
1. Go to any query you may have that has a timestamp field (at least in Oracle database as data source).
2. Click on 'Download full results' in XLSX or CSV.
3. Open with Excel.
4. See column containing timestamp, it is shown in the cell as:
2019-03-18T17:24:31.000+01:00 (type 'General', i.e. not recognized).
It cannot be converted either or get recognized if cell is changed to date, time, ...

**Expected behavior**
When exporting results containing dates, times or datetimes (timestamps fields), the formatting should be recognized by Excel on Open without any need to convert or tweak the data.

**Screenshots**
![image](https://user-images.githubusercontent.com/10819908/64324141-10922c00-cfc6-11e9-947f-35197fb400d6.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome version 76.0.3809.132 (Official Build) (32-bit)
- Your operating system: Windows 10.0.17134 Build 17134
- Your databases: Oracle, MySQL
- Metabase version: v.0.33
- Metabase hosting environment: Jar-file on CentOS
- Metabase internal database: MySQL

**Severity**
This annoying and prevents that some users can make use of Metabase to complete some of their tasks.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by dumplingbao** [comment]
This problem also exists for Mongo database

**Comment by jodistiara** [comment]
also happens in PostgreSQL database

**Comment by MiltonDouglas** [comment]
We still have problems with this error. PostgreSQL database

**Comment by camsaul** [comment]
@grimete @dumplingbao @jodistiara @MiltonDouglas @flamber I'm not an expert Excel user... what timestamp format should we use? We can change the format pretty easily I think if someone knows what we should change it to.

**Comment by ckorhonen** [comment]
I think it needs to be `dd-mm-yyyy hh:mm:ss`.

One thing to note is that I don't believe Excel will nicely handle timezones, so that information may need to be dropped. 😕

**Comment by MiltonDouglas** [comment]
dd/mm/yyyy hh:mm:ss

But it is important to test it, with the export option and verify that in MS Excel it is being taken as a date data. You can test that it is in date format, taking a cell and adding 1 to it, to see if it performs the operation correctly.  Watch this video: https://www.screencast.com/t/dvmUwHfh7Gf

**Comment by flamber** [comment]
`yyyy-MM-dd hh:mm:ss` (not starting with year, how would Excel know if first part is a day or month?)
- replace the `T` with space
- remove the millisecond (compatibility with crazy languages like Danish that switches dots and commas)
- I don't see the timezone anymore on 0.35.3 or master, but I think that went away in 0.33
- Would it be smart to do the same for CSV and JSON, so they're all using the same format?

Just note that there's an issue that covers all formatting in general for exports #10879

**Comment by ckorhonen** [comment]
For JSON I'd argue the formatting should be [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) formatted. That would be the most widely supported and compatible.

**Comment by dacort** [comment]
For Excel, we should go with the ECMA-376 spec. Will try to find the exact spec. CSV should probably have the same format as JSON.

**Comment by flamber** [comment]
After some more testing, I have stumbled on some strange behavior. Results are different for unsaved (aka "dirty") questions.

Native (H2 Sample Dataset)
1. Run `SELECT PARSEDATETIME('2020-06-03', 'yyyy-MM-dd') AS birth_date, PARSEDATETIME('2020-06-03 23:41:23', 'yyyy-MM-dd hh:mm:ss') AS created_at`, without saving export CSV/XLSX:
birth_date `2020-06-03`
created_at `2020-06-03T23:41:23`
2. Save as question, export CSV/XLSX:
birth_date `2020-06-03T00:00:00+02:00`
created_at `2020-06-03T23:41:23+02:00`

QB (H2 Sample Dataset)
1. Simple question > Sample Dataset > People > Limit 1 row, without saving export CSV/XLSX:
birth_date `1986-12-12`
created_at `2017-10-07T01:34:35.462`
2. Save as question, export CSV/XLSX:
birth_date `1986-12-12T00:00:00+01:00` - **notice** the different timezone, not sure how/why
created_at `2017-10-07T01:34:35.462+02:00`

Step 2 in both tests are same behavior for Pulse attachments.

From the looks of it, it seems like it's saving the value as a string, which might be why SXSSFWorkbook or Docjure doesn't translate it automatically to a proper format.
Example: `<c r="B2" t="inlineStr"><is><t>2020-06-03T23:41:23+02:00</t></is></c>`
https://github.com/metabase/metabase/blob/e2e36910c4afe432e2060f64b423c2eecca6074f/src/metabase/query_processor/streaming/xlsx.clj#L22-L33

<details><summary>Diagnostic Info</summary>

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.3.0-55-generic",
    "user.language": "en",
    "user.timezone": "Europe/Copenhagen"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "sqlite",
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

</details>

**Comment by camsaul** [comment]
I think this should be pretty straightforward. @flamber has set us on the right track already.

**Comment by camsaul** [comment]
Fixed by #13133

**Comment by dacort** [comment]
There's a few different use cases/behavior happening:
1. Download SQL question with date and timestamp before and after saving
2. Download Simple question with date and timestamp before and after saving

In case #1, it works fine _before_ saving (dates/times are recognized in excel), but not _after_ (dates/times are strings and dates include time data).

In case #2, the Excel file is corrupted (it's actually a stack trace text file) when I download _before_ saving. And dates/times are strings after saving. 

Relevant: https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download :)

**Comment by flamber** [comment]
Fixed by #13447

**Comment by jlisyc** [comment]
Metabase 0.36.12
Date format downloaded excel does not respect the date format when chose to show minutes.
For example: for 24 September 2020, with format configuration is D/M/YYYY
, in the downloaded excel shows:
 for a date "with minutes" it change to M/D/YYYY ![image](https://user-images.githubusercontent.com/33416503/114665114-ea358600-9cfc-11eb-80b4-c1329a1a7bd2.png)

, but for date (just day) is ok ![image](https://user-images.githubusercontent.com/33416503/114665014-c83c0380-9cfc-11eb-8879-4e509924c7e5.png)

**Comment by Yambr** [comment]
fixed only in query - in embedded dashboard have same problem

**Comment by flamber** [comment]
@Yambr There's an issue open specifically for that #14393
