### ISSUE TITLE
Percentage formatting no longer works after v0.33.1 upgrade

### ISSUE THREAD

**Issue by CoconutTherapy** [metabase/metabase#10807]
**Describe the bug**
Percentage formatting no longer works whenever values are shown (tables, tooltips, etc.)

**To Reproduce**
Upgrade to 0.33.1.
Check any percentage formatted field

**Expected behavior**
Values set as percentage should show in percentage format.

**Screenshots**
![image](https://user-images.githubusercontent.com/29283297/64334230-666fcf80-cfd8-11e9-8a27-d9db731f2c77.png)

![image](https://user-images.githubusercontent.com/29283297/64334302-87382500-cfd8-11e9-8c7d-2642a1458e3b.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76
- Your operating system: Windows 10
- Your databases: Redshift
- Metabase version: 0.33.1
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
All formatting has disappeared for percentages which makes tables and tooltips unreadable. Quite severe indeed.

**Comment by GitsMcGee** [comment]
Not sure if it's worth me creating a separate ticket for this, as it's probably the same issue underneath, but currency formatting is also broken in 0.33.1 for us.

**Comment by paulrosenzweig** [comment]
Fixed by #10809. We'll try to get the fix released soon!
