### ISSUE TITLE
backend server not starting in gitbash on windows

### ISSUE THREAD

**Issue by tarangdave** [metabase/metabase#10813]
**Describe the bug**
Trying to run Metabase on Windows 7. Using gitbash for installing. Build installed successfully but when running the backend server using `lein ring server` I'm getting the following error -
```
Syntax error (InvalidPathException) compiling at (C:\Users\<user>\AppData\Local\Temp\form-init12131717271277502924.clj:1:109).
Illegal char <:> at index 2: /C:/Users/<user>/environment/metabase/resources/modules
```

This is error is definitely due to the path mismatch between windows and linux - `/C:/` might be causing this exception. 

I couldn't find any useful resources to solve this issue. 

This same issue is reproduced when using Windows Command Prompt for running.

**Logs**
```
{:clojure.main/message
 "Syntax error (InvalidPathException) compiling at (C:\\Users\\<user>\\AppData\\Local\\Temp\\form-init12131717271277502924.clj:1:109).\r\nIllegal char <:> at index 2: /C:/Users/<user>/environment/metabase/resources/modules\r\n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 1,
  :clojure.error/column 109,
  :clojure.error/source "form-init12131717271277502924.clj",
  :clojure.error/path "C:\\Users\\<user>\\AppData\\Local\\Temp\\form-init12131717271277502924.clj",
  :clojure.error/class java.nio.file.InvalidPathException,
  :clojure.error/cause "Illegal char <:> at index 2: /C:/Users/<user>/environment/metabase/resources/modules"},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message "Syntax error compiling at (C:\\Users\\<user>\\AppData\\Local\\Temp\\form-init12131717271277502924.clj:1:109).",
    :data
    {:clojure.error/phase :compile-syntax-check, :clojure.error/line 1, :clojure.error/column 109, :clojure.error/source "C:\\Users\\<user>\\AppData\\Local\\Temp\\form-init12131717271277502924.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7648]}
   {:type java.nio.file.InvalidPathException,
    :message "Illegal char <:> at index 2: /C:/Users/<user>/environment/metabase/resources/modules",
    :at [sun.nio.fs.WindowsPathParser normalize "WindowsPathParser.java" 182]}],
  :trace
  [[sun.nio.fs.WindowsPathParser normalize "WindowsPathParser.java" 182]
   [sun.nio.fs.WindowsPathParser parse "WindowsPathParser.java" 153]
   [sun.nio.fs.WindowsPathParser parse "WindowsPathParser.java" 77]
   [sun.nio.fs.WindowsPath parse "WindowsPath.java" 92]
   [sun.nio.fs.WindowsFileSystem getPath "WindowsFileSystem.java" 229]
   [metabase.util.files$get_path_in_filesystem invokeStatic "files.clj" 24]
   [metabase.util.files$get_path_in_filesystem doInvoke "files.clj" 23]
   [clojure.lang.RestFn invoke "RestFn.java" 425]
   [clojure.lang.AFn applyToHelper "AFn.java" 156]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$apply invoke "core.clj" 660]
   [metabase.util.files$get_path invokeStatic "files.clj" 32]
   [metabase.util.files$get_path doInvoke "files.clj" 26]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [metabase.util.files$do_with_open_path_to_resource invokeStatic "files.clj" 112]
   [metabase.util.files$do_with_open_path_to_resource invoke "files.clj" 103]
   [metabase.plugins$extract_system_modules_BANG_ invokeStatic "plugins.clj" 57]
   [metabase.plugins$extract_system_modules_BANG_ invoke "plugins.clj" 54]
   [metabase.plugins$load_plugins_BANG_ invokeStatic "plugins.clj" 136]
   [metabase.plugins$load_plugins_BANG_ invoke "plugins.clj" 122]
   [metabase.core$init_BANG_ invokeStatic "core.clj" 67]
   [metabase.core$init_BANG_ invoke "core.clj" 55]
   [clojure.lang.Var invoke "Var.java" 380]
   [ring.server.standalone$serve invokeStatic "standalone.clj" 96]
   [ring.server.standalone$serve doInvoke "standalone.clj" 75]
   [clojure.lang.RestFn invoke "RestFn.java" 423]
   [ring.server.leiningen$serve invokeStatic "leiningen.clj" 19]
   [ring.server.leiningen$serve invoke "leiningen.clj" 16]
   [user$eval77069 invokeStatic "form-init12131717271277502924.clj" 1]
   [user$eval77069 invoke "form-init12131717271277502924.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7167]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.Compiler loadFile "Compiler.java" 7574]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "Illegal char <:> at index 2: /C:/Users/<user>/environment/metabase/resources/modules",
  :phase :compile-syntax-check}}
```

**To Reproduce**
1. Run gitbash on Windows 7
2. Follow install instructions from docs
3. Install build
4. run `lein ring server`
5. See error

**Information about your Metabase Installation:**
- Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Windows 7 (SP1)
- Metabase version: Latest Master Branch Clone

**Comment by flamber** [comment]
Hi @tarangdave 
I think the entire development team uses Mac currently, so someone with an older Windows version would probably need to submit a PR for this to be fixed.
Since Windows 7 doesn't have WSL and I don't know if it has Ubuntu Bash, then your way around it would be a VM running some Unix-based system.

From the documentation: https://metabase.com/docs/latest/developers-guide.html
> The development scripts are designed for Linux/Mac environment, so we recommend using the latest Windows 10 version with WSL (Windows Subsystem for Linux) and Ubuntu on Windows. The Ubuntu Bash shell works well for both backend and frontend development.

**Comment by salsakran** [comment]
Removing the bug label since we explicitly call out Windows 10 as a requirement.

Not the best developer experience, but as @flamber mentioned none of the core team are on windows 7. We'd absolutely take a PR that fixes this however.

**Comment by saravananselvamohan** [comment]
But even I am getting same error in Windows 10  System:

_Syntax error (InvalidPathException) compiling at (C:\Users\Admin\AppData\Local\Temp\form-init17010896802776182378
.clj:1:109).
Illegal char <:> at index 2: /D:/Test/Source%20Code/metabase/resources/modules_

**Comment by flamber** [comment]
@saravananselvamohan 
But are you using [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) and Ubuntu Bash shell, as noted in the documentation?
https://www.metabase.com/docs/latest/developers-guide.html#development-on-windows
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by flamber** [comment]
I'm fairly sure this was fixed by PR #11705 addressing similar issue #11695. Leaving this open for now, since I don't have ways to verify it currently.

**Comment by tarangdave** [comment]
@flamber 
I checked in my current windows 7 setup with a fresh clone from master, it works.
![image](https://user-images.githubusercontent.com/10511718/73796644-9deacf80-4762-11ea-9c6b-cf0e1bda318c.png)


Although, I did get this error using `lein ring server` - 
`
Syntax error (HeadlessException) compiling at (C:\Users\<user>\AppData\Local\Temp\form-init2608524970270275231.clj:1:108).
null
`

So I had to use `lein ring server-headless`

**Comment by flamber** [comment]
@tarangdave Great! Thank you for verifying. I'm going to close this then, since headless just means without automatically starting the browser.
