### ISSUE TITLE
Is there a way to support script running?

### ISSUE THREAD

**Issue by ChaimCode** [metabase/metabase#10817]
Querying SQL separately does not meet the requirements.
Is there a way to support script running?
Or can it only be developed based on metabase?  However, I don’t think this is a good way. 

need help, thanks.

**Comment by flamber** [comment]
Hi @ChaimCode 
Maybe too much got lost in translation, but what are you asking for? And what is "script running"?
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by salsakran** [comment]
We don't offer post-processing via scripts and it's not on our roadmap for the foreseeable future.
