### ISSUE TITLE
Don't abort on any 403

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#10816]
We've had two recent bugs resulting from 403 errors blocking all usage.

* #9270 
* #10810

Currently, even if all the required data has loaded correct, a stray request to a blocked resource will break the whole page. We shouldn't be making requests that will be blocked, but it also seems that this behavior makes small bugs much more severe.

[This is where](https://github.com/metabase/metabase/blob/fix-10810/frontend/src/metabase/app-main.js#L45) we pop up the error page unless the failed request is in a certain list of allowed paths.

**Comment by salsakran** [comment]
Bumping this in priority since it makes entire pages break when a single resource call fails, which is unacceptable.

**Comment by paulrosenzweig** [comment]
Fixed in #11747
