### ISSUE TITLE
Updating Account Settings returns permission error

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10810]
**Describe the bug**
Updating user name/email via :gear: Account Settings returns `Sorry, you don't have permission to see that.`, but actually saves the changes.

**Logs**
`Error: Object { status: 403 }` from `/api/permissions/membership`, when clicking Update.

**To Reproduce**
1. Login as non-admin user
2. Go to :gear: Account Settings and change name/email and click Update.
3. `Sorry, you don't have permission to see that.`

**Expected behavior**
Clicking Update would return a little confirmation message, just like changing password does.

**Screenshots**

**Information about your Metabase Installation:**
Metabase 0.33.0/0.33.1 on H2 with various OS/browsers.

**Additional context**
https://discourse.metabase.com/t/tweak-to-all-users-rights/7238

**Comment by flamber** [comment]
On a side-note. When updating an admin-user, then it doesn't give any feedback that it has been updated. And after clicking Update, click Password-tab and click Profile-tab again, then it shows the old data, but doing a browser refresh shows the new data.
Also, there's zero margin below the action buttons (Update/Save), which make the page look cut-off.

**Comment by kdoh** [comment]
It looks like [this line](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/entities/users.js#L96) is the culprit. `loadMemberships` gets called on user updates and the endpoint that calls requires the user to be an admin. We should follow the `TODO` in the code there and only call that if something about the user's group is changing. Making sure that's all right and tested is a bit beyond my understanding of entities, so seems like an @paulrosenzweig or @tlrobinson job.

**Comment by paulrosenzweig** [comment]
Fixed in #10815
