### ISSUE TITLE
Elastic Search (ELK) driver or connector

### ISSUE THREAD

**Issue by grimete** [metabase/metabase#10821]
**Describe the solution you'd like**
Possibility to have our ELK cluster as a data source in Metabase.

**How important is this feature to you?**
Nice to have, as in our ELK we have already calculations done, this would complement quite well our analysis/reporting toolset. Kibana is nice for some things but for others falls short.

**Comment by flamber** [comment]
Hi @grimete Duplicate of #1300. Please close this issue.

**Comment by grimete** [comment]
Duplicate
