### ISSUE TITLE
Provide a message when the last admin tries to remove their admin privileges (this will be implemented as part of permissions v1)

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1083]
Right now we will not allow the last admin to set their role to be a normal user in the People section of the admin. We don't provide a visual indication that they're not able to or an error message on the attempt but just do nothing. We should either disable the option with an explanation or provide an error message.

**Comment by camsaul** [comment]
This will be implemented by Permissions v1 #3088

**Comment by camsaul** [comment]
Implemented by #3376
