### ISSUE TITLE
Month is displayed on the line chart tooltips instead of week when grouped by week

### ISSUE THREAD

**Issue by easeev** [metabase/metabase#10841]
**Describe the bug**
Month is displayed on the line chart tooltips instead of week when grouped by week. Looks like regression in 0.33.0 since it was displaying properly in previous versions.

**To Reproduce**
1. Create line visualization with grouping by week
2. Hover on the dot on the line
3. See month instead of the week

**Expected behavior**
See week.

**Screenshots**

![pVxliJknFP](https://user-images.githubusercontent.com/14873170/64525591-cc8b8800-d333-11e9-8922-b7efe02781ef.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76.0.3809.132
- Your operating system: Windows 10
- Metabase version: 0.33.2
- Metabase hosting environment: Google App Engine
- Metabase internal database: Postgres

**Severity**
Annoying.

**Comment by paulrosenzweig** [comment]
Fixed in #10864
