### ISSUE TITLE
Display of the Raw Data is Capped to 2k Rows 

### ISSUE THREAD

**Issue by ankitck001** [metabase/metabase#10849]
i am using latest version 0.33.2 but not able to edit the max row display it is still capped to 2k.

**Comment by flamber** [comment]
Hi @ankitck001 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
That's the hardcoded limit of 10k aggregated and 2k un-aggregated. There's a request for making this limit (amount others) changeable. Go and upvote #4564 by clicking :+1: on the first post.
And please close this issue.

**Comment by salsakran** [comment]
We do not expose this as a setting. #4564 is the tracking issue for this being a setting. Closing as a dupe.
