### ISSUE TITLE
Pulse stopped working - emails not sent

### ISSUE THREAD

**Issue by nire0510** [metabase/metabase#10848]
**Describe the bug**
Hi,

Few days after running Metabase, email pulses stopped working.
Log file seems clean. The only way to get it work again was to restart the service (but again - after a couple of days pulses stopped working again)

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
![image](https://user-images.githubusercontent.com/3891695/64589704-6b54ca80-d3ae-11e9-8a17-a21f1af3989b.png)

**To Reproduce**
N/A
**Expected behavior**
Receive a pulse email every day 08:00

**Screenshots**
![image](https://user-images.githubusercontent.com/3891695/64589653-4d876580-d3ae-11e9-98b2-e37cc6ed930f.png)

**Information about your Metabase Installation:**
- Your browser and the version: Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- Your operating system: OS X 10.14
- Your databases: Postgres
- Metabase version: v0.33.0
- Metabase hosting environment: Jar-file on Ubuntu
- Metabase internal database: Postgres (used to be H2, happened as well)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
This feature is very useful and negatively affects our users' experience

**Additional context**

**Comment by flamber** [comment]
Hi @nire0510 Did you fix the problem? Do you mind just telling what you did in case someone finds your issue in the future?

**Comment by nire0510** [comment]
With pleasure, @flamber:
I took another look at the EMAIL settings page, and found out that the SMTP credentials there belong to a limited user which is eligible to send a handful of emails every day. I have switched to our official account credentials and pulses started to send.

I'll keep you posted if any issue comes up.
