### ISSUE TITLE
Query builder - join saved questions - wrong SQL

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#10854]
**Bug description**
When I try to join two previously created questions (these were created using the query builder, not by raw SQL) I end up with this error:
```The multi-part identifier "Question 379.DATUM" could not be bound.```
This happens because the subquery representing the second question references its' alias from inside itself. see below:

```sql
SELECT TOP 1048576
    [columns]
FROM 
    ( [first subquery] ) "source" --not important as this subquery is just right
LEFT JOIN 
    (
        SELECT --missing TOP [xxxxx] clause, query won't work unless ordering is disabled
            "Question 379"."JM_LEKAR" AS "JM_LEKAR", --wrong self-referencing HERE
            "dbo"."_metabaseReport_lekari_prohlidky_dekurzy"."TYP" AS "TYP", 
            sum("dbo"."_metabaseReport_lekari_prohlidky_dekurzy"."PROVEDENO") AS "sum"
    FROM 
        "dbo"."_metabaseReport_lekari_prohlidky_dekurzy"
    WHERE 
        (datefromparts(year("Question 379"."DATUM"), 1, 1) = datefromparts(year(getdate()), 1, 1) AND "dbo"."_metabaseReport_lekari_prohlidky_dekurzy"."PROVEDENO" = 1)
    GROUP BY "Question 379"."JM_LEKAR", "dbo"."_metabaseReport_lekari_prohlidky_dekurzy"."TYP"
    ORDER BY "Question 379"."JM_LEKAR" ASC) "Question 379" 
    
ON "source"."JM_LEKAR" = "Question 379"."JM_LEKAR" 
```
You can actually see 2 different errors here:

- The second subquery lacks the `TOP xxxx` clause so it results in an error unless the `ORDER BY` clause is removed
- The strange self-referencing. `Question 379` is not valid inside the query. The correct fully qualified name would be `"dbo"."_metabaseReport_lekari_prohlidky_dekurzy"`

**Version information**
https://github.com/metabase/metabase/commit/bf3b25a6b7a2e1460f895033b900f0292310fc9d

**Comment by sbelak** [comment]
I'm having trouble reproducing this. Can you share how `source` query looks like

**Comment by dfx413** [comment]
@sbelak Sure, here is the whole nested query: https://gist.github.com/dfx413/dca9bb6219ed533f664a6883dda001bf

Here is the SQL representation (made using Convert to SQL) of the "source" query:
https://gist.github.com/dfx413/303a34ba3c7ef020916ef0914d78a19c

And here is the "Question 379":
https://gist.github.com/dfx413/a4e1de44d4556fb6b36195898e4d19a5

**Comment by sbelak** [comment]
@dfx413 we've done a number of fixes to how we generate queries. Mind checking if you are still hitting this with the latest?

**Comment by dfx413** [comment]
@sbelak Sure, will test it out today or tomorrow and let you know how it went. Thanks!

**Comment by dfx413** [comment]
Tried some examples and it looks good to me so far!
