### ISSUE TITLE
Data access and SQL queries access is not isolation

### ISSUE THREAD

**Issue by Lemon-le** [metabase/metabase#10850]
When I set the sql queries is open，then the data access is all open。But I want only which I'm want open access about data access table

**Comment by flamber** [comment]
Hi @Lemon-le 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
I'm not sure what you're asking, but when users have access to SQL, then they have full access.
There's a request for more detailed access in #10525 - go and upvote by clicking :+1: 
And please close this issue.

**Comment by salsakran** [comment]
This is working as expected. If someone has SQL access, they can access any table via SQL. Our data access permissions only apply to the query builder.
