### ISSUE TITLE
Wrong with formatting numbers on public shared dashboards

### ISSUE THREAD

**Issue by crakter** [metabase/metabase#10856]
**Describe the bug**
There is some inconsistencies between the public shared dashboard and the dashboard accessed from metabase directly.

**Logs**
[1568141424483.log](https://github.com/metabase/metabase/files/3597289/1568141424483.log)
Console log, it doesn't contain any javascript errors, but alot of warnings.

**To Reproduce**
Access public shared link with different number settings then default and access it directly from Metabase,  see the difference between them. This seems to happen sometimes, and other times it's okey.

**Expected behavior**

**Screenshots**
Please see the right image compared to the left image. Right image is the public shared one and the left is accessed directly from Metabase. 
![image](https://user-images.githubusercontent.com/24833502/64641300-2d868f00-d40c-11e9-8411-d97e597c0be7.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76.0.3809.132
- Your operating system: Windows 10
- Your databases: MySQL
- Metabase version: 0.33.0
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
Slightly annoying

**Comment by flamber** [comment]
Hi @crakter 
Can you try 0.33.2? There was several issues with formatting fixed since 0.33.0
I cannot reproduce the currency unit or separator style on 0.33.2, but I do see the overflowing when using `NOK`, so I'm pinging @paulrosenzweig 
But maybe you're seeing #10787

**Comment by crakter** [comment]
Thanks @flamber, seem to have fixed it.

**Comment by crakter** [comment]
Reopening this as seeing it in the latest version aswell. 
Attaching console logs and image. It should be formatted as "xxx xxx,xx" and not "xxx,xxx.xx"

[Console.log](https://github.com/metabase/metabase/files/3728272/Console.log)
![image](https://user-images.githubusercontent.com/24833502/66816046-af9d3280-ef39-11e9-8ed8-621b518325cd.png)

**Comment by flamber** [comment]
Hi @crakter 
Which version of Metabase?
I cannot reproduce your issue.
Which type of question is it, Custom or Native?
Have you defined formatting for the question or are you only using the global formatting (Admin > Settings > Formatting) ?

**Comment by crakter** [comment]
@flamber , 0.33.4, latest.
This only happens sometimes, and not all the times. Both of these questions are Custom.
Global formatting is as follows,
![image](https://user-images.githubusercontent.com/24833502/66868306-6383d980-ef9d-11e9-8d54-883445dde8bd.png)
And on the question:
![image](https://user-images.githubusercontent.com/24833502/66868404-8adaa680-ef9d-11e9-9c7d-921b3d291910.png)

**Comment by flamber** [comment]
@crakter 
Do you mean that it only happens to specific questions, or it happens to all questions but randomly failing to apply the set formatting?

Don't know if you know, but there's actually 3 layers of formatting - global, question and card.
So if you edit a dashboard, and click the :gear: of a card, then you can click the "Reset to defaults" and "Done", which will mean it will use the settings from the question.
I have a feeling that the dashboard card settings might be causing the problem.

**Comment by crakter** [comment]
@flamber 
I have only seen this on public dashboards that have been generated. And sometimes it helps to refresh, other times it does not. So it's really weird.
Public dashboards from here:
![image](https://user-images.githubusercontent.com/24833502/66870862-a85e3f00-efa2-11e9-8466-a5973bf1aca4.png)

The image above is from the card and not the question.

**Comment by flamber** [comment]
@crakter I think you misunderstood. The terminology can be a little tricky. You can only share a Question or a Dashboard.
When you add questions to a dashboard, then they're called Cards - but they belong to the dashboard, if you enable sharing, so then you're just sharing the dashboard.
If you edit a dashboard, and hover with your mouse over a card, then click the :gear: to edit the cards settings - that's where you should "Reset to defaults".

It's really tricky to fix something, if it cannot be reproduced.
Have you tried other browsers than Chrome?
Is the Public Shared dashboard in full-screen?

**Comment by crakter** [comment]
@flamber i don't think i'm misunderstanding. I have reset the defaults now from where i took the screenshot, from the card on the dashboard.
I tried it now and still the same problem. I have tried other browser aswell, on mobile and desktop, Firefox and Huawei Internet browser. Same result. It almost always defaults to us signs.
Have you tried making a public link for the dashboard and accessing it? As Said it does not happen on accessing from logged in Metabase.

**Comment by flamber** [comment]
@crakter Okay, it took me a little while to reproduce this, since I originally tried to reproduce by modifying the questions formatting, which works.
The work-around is to (re)define the formatting on the question or card, then it's applied.

@paulrosenzweig When using a question/card does not have formatting defined, then it does not apply the global formatting on Public Sharing, but falls back to Metabase defaults (US-style).

Dashboard (global formatting is Number=`100000.00` and Currency=`Danish Kroner`:
![image](https://user-images.githubusercontent.com/1447303/66875650-53073b00-ef6c-11e9-8145-834133f55322.png)
Public Sharing:
![image](https://user-images.githubusercontent.com/1447303/66875693-7500bd80-ef6c-11e9-90d9-fd5e8f3e789e.png)

**Comment by crakter** [comment]
@mazameli @paulrosenzweig this should probably get an triage and move from already fixed.

**Comment by dfx413** [comment]
Hi, 
I have a similar problem.
When logged in as ordinary user I keep seeing currency as USD with US formatting.
The underlying column is set to CZK.

**What I see as admin (this is correct)**:
<img width="211" alt="Snímek obrazovky 2020-01-14 v 10 59 01" src="https://user-images.githubusercontent.com/1764151/72334282-56ba7300-36bd-11ea-9a7f-e06fd80e78a8.png">

-----

**What the user sees (wrong)**:
![Snímek obrazovky 2020-01-14 v 10 59 06](https://user-images.githubusercontent.com/1764151/72334312-646ff880-36bd-11ea-8885-97a726a9dfd7.png)

-----

**Column setting**: 
<img width="974" alt="Snímek obrazovky 2020-01-14 v 11 00 57" src="https://user-images.githubusercontent.com/1764151/72334379-7f426d00-36bd-11ea-8b6a-edd82620b82d.png">

-----

**Global settings**:
<img width="279" alt="Snímek obrazovky 2020-01-14 v 11 04 02" src="https://user-images.githubusercontent.com/1764151/72334440-98e3b480-36bd-11ea-8e65-11cfc0b32a13.png">

**Comment by flamber** [comment]
@dfx413 
Are these two different questions or did you rename it from `__test currency` to `test currency`?
I cannot reproduce your issue on master, but this issue is specific to Public dashboards.
Maybe you're seeing one of the related issues linked in #11394.
Also, note that you haven't set any of the values in the "Admin view" question, since there would be a little reload-icon next to the section header like this (otherwise it's just using the Global formatting):
![image](https://user-images.githubusercontent.com/1447303/73697197-43a82b00-46de-11ea-97e8-4b3490261e88.png)

**Comment by dfx413** [comment]
Hello @flamber, thanks for the reply. 
1) This is the same question, just renamed it during my test, sorry for that. 
2) Yeah, it is probably related to #11394 , should we continue there?
3) You are right, the question has no specific formatting settings, that is my intention. It should be displayed the same way for admin and for normal user, but it is not. Global Formatting is set to the same values that you see on the Admin screenshot, Column is set to "Income" type in CZK. But when logged in as normal user, these values are not being used. Instead it uses some implicit default setting.

**Comment by flamber** [comment]
@dfx413 It's most likely #11394 or one of the many issues referenced in that. The workaround is to define the formatting on the question. But it's not this issue, which is specific to Public dashboards.

**Comment by flamber** [comment]
I cannot reproduce on latest release 0.39.4. Think it was fixed around 0.36. Please comment with steps-to-reproduce and "Diagnostic Info" from Admin > Troubleshooting, if you are still seeing this issue.
