### ISSUE TITLE
Configuração do LDAP AD

### ISSUE THREAD

**Issue by renatofritola** [metabase/metabase#10855]
I tried to configure LDAP by passing all access settings to LDAP AD but was unsuccessful.
I have other applications working correctly but Metabase does not recognize the user's password.

Every time I try to log in it returns the message: Did not match the recorded password !.

Can you help me please?

Thank you.

**Comment by flamber** [comment]
Hi @renatofritola 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:

**Comment by salsakran** [comment]
@renatofritola we're not able to provide support via the issue tracker. 

As @flamber mentioned, the forum is the appropriate venue for these kinds of questions
