### ISSUE TITLE
Group by Month Date Encoding Issue with MemSQL Database

### ISSUE THREAD

**Issue by nick-at** [metabase/metabase#10868]
**Describe the bug**
When aggregating by month, the truncated dates are returned in the incorrect format, preventing Metabase for charting anything. This issue appears to be related to the str_to_date() MySQL function which Metabase uses in its truncation of dates.

For example, I want the count of rows by month from a table. Using the custom question UI to construct a count of rows with by month. The result I get back is a blank chart with an error:

![image](https://user-images.githubusercontent.com/34499982/64747834-8b71be80-d553-11e9-8e3c-4f788e658f77.png)

The error reads:
> Data includes missing dimension values
> We encountered an invalid date: “0x32303131”
> “Launched At” is an unaggregated field: if it has more than one value at a point on the x-axis, the values will be summed.

Note that in this case launched_at is a DATETIME type column. 

**Logs**
This is the query that Metabase constructs with this error:

```
 SELECT str_to_date(concat(date_format(`fact_surveys`.`launched_at`, '%Y-%m'), '-01'), '%Y-%m-%d') AS `launched_at`, count(*) AS `count`
 FROM `fact_surveys`
    GROUP BY str_to_date(concat(date_format(`fact_surveys`.`launched_at`, '%Y-%m'), '-01'), '%Y-%m-%d')
    ORDER BY str_to_date(concat(date_format(`fact_surveys`.`launched_at`, '%Y-%m'), '-01'), '%Y-%m-%d') ASC
```
When I run this query directly against the database (in a SQL workbench) I get the expected results back, with a date in the first column and count in the second. However when I run the same query as a ‘native query’ in Metabase against the same database, the dates come back in what looks like some kind of encoding.

This issue only exists when aggregating by month - aggregating by day, for example, works as expected.

**To Reproduce**
You can reproduce this issue with the following query against a MySQL database.

`SELECT str_to_date('2019-09-10', '%Y-%m-%d')`
Which will return `2019-01-10` directly against the database but returns `0x32303139` in Metabase

**Expected behavior**
Dates returned as dates so that they can be graphed.

**Information about your Metabase Installation:**
Database: MemSQL v6 (MySQL v5.x)
Metabase Version: 0.33.2
Hosting Environment: docker
OS: MacOS 10.14.06
Browser: Chrome 76.0.3809.132

**Severity**
Monthly aggregation is a very common aggregation used. We may not roll out Metabase to non-technical users with this bug present (i.e. people who won't write SQL)

**Comment by nick-at** [comment]
Note this works if you wrap the function in `DATE()` e.g. `SELECT date( str_to_date('2019-09-10', '%Y-%m-%d') )`

**Comment by nick-at** [comment]
It appears this issue also exists for JSON type data

**Comment by flamber** [comment]
Hi @nick-at 
Metabase technically don't support MemSQL except if what you're experiencing is also a MySQL bug. A lot of databases promises compatibility, but that don't actually deliver it.
Metabase version 0.33.5.1 got an upgraded driver, so please try that version or newer.
Metabase uses MariaDB Connector/J, whereas Workbench uses MySQL Connector/?.

**Comment by flamber** [comment]
Closing, since Metabase would likely need a modified driver to work with MemSQL.
