### ISSUE TITLE
CASE THEN in date field

### ISSUE THREAD

**Issue by Jona-than4** [metabase/metabase#10866]
criei a view no sql developer, banco de dados oracle

CASE
    WHEN (TO_DATE(E1_VENCREA,'YYYYMMDD')) < SYSDATE
    THEN SYSDATE-1
    ELSE TO_DATE(E1_VENCREA,'YYYYMMDD') 
END AS VENCREA

No sql developer o resultado é apresentado corretamente

Já no Metabase mostra a data original, não faz a substituição indicada no case

**Comment by flamber** [comment]
Hi @Jona-than4 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
If you write in English, then you'll likely get help from more people.
And please close this issue :+1:

**Comment by Jona-than4** [comment]
I created a view in sql developer, oracle database..

CASE
WHEN (TO_DATE (E1_VENCREA, 'YYYYMMDD')) <SYSDATE
THEN SYSDATE-1
ELSE TO_DATE (E1_VENCREA, 'YYYYMMDD')
END WIN THEM

In sql developer the result is presented correctly

Already in Metabase shows the original date, does not replace the case indicated

**Comment by flamber** [comment]
@Jona-than4 
If you have created a view, then the query is handled by Oracle not by Metabase.
And without more context or how you're using the query, then it's difficult to know what's going on.

**Comment by salsakran** [comment]
@Jona-than4 at a minimum, we'd need to know what versions of Metabase and Oracle you're using to be able to help you.

**Comment by flamber** [comment]
Closing, since not enough details.
