### ISSUE TITLE
can metabase offer the extend ability to redevelopment ?

### ISSUE THREAD

**Issue by zhijianfree** [metabase/metabase#10869]
when we use metabase, we want to know some notify event(for example: when we  publishing the dashboard or question int the metabase,  we want ot tell the developer or other system  do some  work.) and on the other hand , can metabase offer ability to cunstom developing? sometimes we need to do filter before view the dashborad. althougth , metabase offer the token to encrypt data,but we think it's not very useful

**Comment by salsakran** [comment]
Hello @zhijianfree -

I'm not sure specifically what you're asking for. Also it seems like you're asking for two separate things.

Can you break this up into two issues and be more specific?

**Comment by salsakran** [comment]
closing this since it isn't at all clear what is being requested and there's been no response for 3 weeks
