### ISSUE TITLE
v0.33.2 - Link to Fullscreen Dashboards No Longer Works

### ISSUE THREAD

**Issue by dolly-bi** [metabase/metabase#10876]
https://metabase.dolly.com/dashboard/5#theme=night&refresh-60&fullscreen

My company has a number of dashboards open on separate tabs showing on a TV in our main office area. Since the upgrade to v0.33.x the link https://metabase.dolly.com/dashboard/5#theme=night&refresh-60&fullscreen drops the "**&fullscreen**" portion of the link and does not load in fullscreen. In previous versions of metabase adding "**&fullscreen**" to a URL would load a dashboard in fullscreen mode.

The documentation online states that this method should still work https://metabase.com/docs/latest/users-guide/07-dashboards.html (Section **Configuring a dashboard through its URL**)

Are other users experiencing this same issue? Has the method to link to a full screen dashboard changed?

I'm running metabase v0.33.2 on AWS EBS Docker running on 64bit Amazon Linux/2.12.16 and accessing it via Windows 10 via Chrome browser version 76.0.3809.132.

This is annoying since it makes the dashboards look not as professional but is not a showstopper.

**Comment by paulrosenzweig** [comment]
fixed in #10896
