### ISSUE TITLE
CSV/XLSX/JSON exports should respect table formatting selections

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10879]
There is a strong user expectation in working with tabular data that formatting selections they make should carry over to exports.

Right now, CSVs don't respect:
- The number of decimal places shown in columns
- Percent etc. number formatting
- Date column formatting
- Currency formatting
- Number multiplication
- Prefixes/suffixes
- Hyperlinks
- Custom column name/title

## Formatted table:

![image](https://user-images.githubusercontent.com/2223916/64824617-71de7000-d56f-11e9-88cc-01a4de3fc79d.png)

## CSV:

![image](https://user-images.githubusercontent.com/2223916/64824578-51aeb100-d56f-11e9-9ce7-ea795a658873.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by sajjadkhanGit** [comment]
Is there any update?

**Comment by dannyeuu** [comment]
@mazameli There are lots of issues mentioning this, all closed, is this important?

**Comment by RoyHP** [comment]
Same issue here, it also doesn't export the column names correctly if they were changed/aliased in the table column formatting.

It's especially bad if the report is generated from a nested query: If we set the column to display something reasonable like "Price" it will export with "Question 47 -> sum where" and we can't seem to change this.

**Comment by RoyHP** [comment]
We are wondering if at least fixing the column name is trivial here https://github.com/metabase/metabase/blob/e2e36910c4afe432e2060f64b423c2eecca6074f/src/metabase/query_processor/streaming/xlsx.clj#L42 (in each of the export formats)

The formatting issues are an inconvenience, but the column name issue makes the reports completely unusable for us when joining questions and trying to use their columns in the result set.

**Comment by WhyNotHugo** [comment]
I think things like currency formatting would be problematic. They're display settings, not part of the data.

CSV is a raw file format. Having currency symbols changes how a column is treated from Number to Text (I've had complaints many time when CSVs have this kind of thing).

**Comment by yexingok** [comment]
> Same issue here, it also doesn't export the column names correctly if they were changed/aliased in the table column formatting.
> 
> It's especially bad if the report is generated from a nested query: If we set the column to display something reasonable like "Price" it will export with "Question 47 -> sum where" and we can't seem to change this.

Hi @RoyHP   We have same issue here, we join couple of tables and make alias from the virtual result table, 
But when export to xlst or csv, it does not keep the alias or the order of the virtual table, it export the original db name, which can be mis-understanding in some cases..
I agree with you it will be great if the export feature can support to export the field defined by user from the virtual table.

**Comment by radzserg** [comment]
Hey there, 

We have the same issue - our clients are confused because the report does not have the data they see.

<img width="1328" alt="Screenshot 2021-01-14 at 11 47 06" src="https://user-images.githubusercontent.com/293785/104681771-32480b00-5704-11eb-9a0c-e5cc9f6fc00b.png">

I upvote this issue in the hope that it will be implemented soon

**Comment by SetSails** [comment]
it should be possible to configure a date and date/time format to be used for csv exports.

**Comment by ochiers** [comment]
Hi,

The export with color will be a huge benefit !

**Comment by gferrette** [comment]
Hello!

This feature would be incredible!

Is there a chance to be implemented?

Thanks!

**Comment by jeff303** [comment]
> Hi,
> 
> The export with color will be a huge benefit !

How would color work in a CSV?

**Comment by jlisyc** [comment]
Metabase 0.36.12
Date format downloaded excel does not respect the date format when chose to show minutes.
For example: for 24 September 2020, with format configuration is D/M/YYYY
, in the downloaded excel shows:
 for a date "with minutes" it change to M/D/YYYY ![image](https://user-images.githubusercontent.com/33416503/114665114-ea358600-9cfc-11eb-80b4-c1329a1a7bd2.png)

, but for date (just day) is ok ![image](https://user-images.githubusercontent.com/33416503/114665014-c83c0380-9cfc-11eb-8879-4e509924c7e5.png)

**Comment by neilrobert** [comment]
Column Headings to be same as aliased or in Admin/Data model is critical
Also data model - redefines eg : 1 = high 2= Medium 3 = Low - report the text, not the original field thx

**Comment by ghiculescu** [comment]
We have found that column formatting works fine when downloading to a CSV if viewing a report in Metabase directly, but *not* if viewing the report through a public link, or using embedding.

Do these downloads use different code paths to generate the CSV? @noahmoss 

I know zero clojure but if someone can point me to the relevant code I can try and find the differences and make a PR.

**Comment by noahmoss** [comment]
> We have found that column formatting works fine when downloading to a CSV if viewing a report in Metabase directly, but not if viewing the report through a public link, or using embedding.

Hi @ghiculescu, what exactly do you mean by "column formatting works fine"? Formatting for CSV exports doesn't currently exist at all (e.g. for numbers, currencies, dates, etc)

**Comment by ghiculescu** [comment]
@noahmoss sorry, let me give a bit more detail. Say you have this question:

```sql
select date '2001-10-05' as "dmyyyy", date '2001-10-05' as "default format"
```

For the first column you choose a date format in "settings", for the second you don't.

![image](https://user-images.githubusercontent.com/509837/128238355-9489edcc-74d8-4475-95c2-ec12c06b3e87.png)

If export that to CSV by clicking the button in the metabase UI...

![image](https://user-images.githubusercontent.com/509837/128238972-fd83a6eb-12f3-49d1-b357-f509c8a2cc6c.png)

You get a file that has the dates formatted as dates:

![image](https://user-images.githubusercontent.com/509837/128238766-af242549-a485-418c-b514-c28bcbf2427a.png)

If you click share -> public link, go to the public link, and then click export to CSV...

![image](https://user-images.githubusercontent.com/509837/128238921-66a69744-7556-42a5-9ce9-6d0b66b95d47.png)

You get a file that has the dates formatted as datetimes:

![image](https://user-images.githubusercontent.com/509837/128238933-133b5ba6-76fe-4ae7-86fa-bfc3ac17b2e2.png)

If you like I can email you a link to the public report so you can test it for yourself, just let me know your email.

**Comment by flamber** [comment]
@ghiculescu You're seeing this issue: #14393

**Comment by noahmoss** [comment]
To anyone following this issue:

I've merged #17226, which means that number, currency and datetime formatting will be included in XLSX exports starting in v40 of Metabase. Renamed, reordered, and remapped columns will also be supported across all export formats.

I'm going to close this issue since it is now partially resolved. The parts that are unresolved will be tracked by separate issues:
* CSV and JSON exports still have unformatted values (#17422)
* Formatting is not applied to pulse attachments (#3735)

**Comment by HugoDellinger** [comment]
I think that pivot formatting, as specified in https://github.com/metabase/metabase/issues/2473 should also be added on the roadmap

**Comment by laurenbetz** [comment]
This is needed for pivot formatting, conditional formatting, and graphs. Without this Metabase becomes a very challenging tool for generating reports

**Comment by kogden-pp** [comment]
Aligned this is still needed - reports are unusable right now because Metabase is creating a timestamp on all of my date fields. Very hard to remove in Excel.
