### ISSUE TITLE
Native query > MIME type ('text/html') is not executable on latest AWS install

### ISSUE THREAD

**Issue by JonCrawford** [metabase/metabase#10886]
**Describe the bug**
I've seen this bug discussed and _supposedly_ fixed, but I'm definitely seeing it again on v0.33.2. When creating a native query visualization with Line graphs, no lines appear and a javascript error is displayed in the console.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Do a fresh install on AWS of v0.33.2.
2. Create a Native Query and visualize it with a Line graph.
3. Check the JS console.

**Expected behavior**
It should display line graph with no errors.

**Screenshots**
![Screenshot](https://d2rsw2kbemic8w.cloudfront.net/items/3g001i2M2u3D0D253Y3U/%5B0a869d71f4e5c30e5a578d7b4bca5851%5D_broken+line+graph+in+metabase.png?X-CloudApp-Visitor-Id=43338)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76.0.3809.132
- Your operating system: Mac OSX 10 
- Your databases: Postgres
- Metabase version: 0.33.2
- Metabase hosting environment: Elastic Beanstalk, Docker
- Metabase internal database: Postgres

**Severity**
This is blocking some users and frankly making me look bad.

**Comment by flamber** [comment]
Hi @JonCrawford 
I'm fairly sure you're seeing #10818 or #10840 or #10862, which is unrelated to the MIME error.
Can you provide the full console error? (It's not everyone who has an AWS account)

**Comment by salsakran** [comment]
@JonCrawford Can you include the error and stack trace (as well as ideally the server logs)?

**Comment by JonCrawford** [comment]
This resolved itself in v0.33.3.

**Comment by flamber** [comment]
@JonCrawford Thanks for the update. Then it probably was #10818, which was fixed in 0.33.3
