### ISSUE TITLE
Font size and color of table cells in pulses should match the in-app style

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10881]
It's not super easy to tell from these screenshots, but the font size and color of text cells in pulses is different from that of tables in-app. Seems like pulses were forgotten in the `table-vibes` refresh.

## Pulse table

![image](https://user-images.githubusercontent.com/2223916/64825182-2f1d9780-d571-11e9-919a-638d233bdd14.png)

## In-app table

![image](https://user-images.githubusercontent.com/2223916/64825196-3c3a8680-d571-11e9-9f98-cc095c830485.png)

**Comment by paulrosenzweig** [comment]
Fixed in #10989
