### ISSUE TITLE
Ability to Choose which tables to update (Presto)

### ISSUE THREAD

**Issue by tomaspe** [metabase/metabase#10884]
So with presto we have a bunch of schemas and tables inside them. I'd want the ability in metabase to be able to choose which schemas and tables to refresh without doing changes in presto. 

It could be in Permissions to choose which schemas (and tables in them) to update metadata on.

Could it also be solved via disabling admin data access and sql queries on them in same tab?

**Comment by salsakran** [comment]
Is this a question of controlling which tables Metabase accesses or a matter of some tables not changing and you not wanting us to re-sync them?

**Comment by tomaspe** [comment]
Mainly controlling access. In particular I'm only interested in several schemas only.

**Comment by flamber** [comment]
@tomaspe It sounds like #2086 and #2591 - if you agree, then please close this issue and upvote the other issues by clicking :+1: on the first post of each.

**Comment by tomaspe** [comment]
you're correct. Thank you!
