### ISSUE TITLE
AWS Deployment - how to un-specify Postgres version?

### ISSUE THREAD

**Issue by romanr** [metabase/metabase#10891]
AWS RDS automatically upgrades to next minor version if you don't deny that. After initial Metabase install my RDS was upgraded and I don't have the pre-upgrade snapshot. Since then while starting-deploying Metabase I am stuck with this error from Elastic Beanstalk:

> Updating RDS database named: ddj49jr4ffhpv failed Reason: Cannot upgrade postgres from 9.6.5 to 9.6.2

And it don't start anymore. obviously there's nothing in `9.6.5` that will break Metabase. It's a superficial requirement. I Am sure Metabase will work even on Postgres 10, 11.

I searched Metabase sources, Metabase docker project (https://hub.docker.com/r/metabase/metabase) and string `9.6.2` is nowhere to be found. 
Can anyone please point me where I can change this version requirement to pass with my deployment?

Thank you.

**Comment by flamber** [comment]
Hi @romanr 
I'm quite sure the version is not controlled by Metabase, but it's auto-magic by RDS/EBS.
Metabase can work with Postgres 9.4+ as the metadata database.
Have you checked the user guide AWS provides?
https://docs.aws.amazon.com/en_pv/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html

**Comment by salsakran** [comment]
This isn't coming from Metabase, but rather from beanstalk. 

Can you take a snapshot and recreate your environment? I.e. I'm not certain exactly how you got in a situation where beanstalk thinks your RDS instance should be 9.6.2 instead of 9.6.5 or why that would matter.

**Comment by salsakran** [comment]
Also, strictly speaking, since this isn't a Metabase issue, it should move to our user forum - discourse.metabase.com

**Comment by romanr** [comment]
Question is not about if Metabase controls Postgres version.
If Postgres version is higher than `9.6.2` Metabase AWS package will not deploy with above error. I am just asking where is that version is specified. I spent countless hours trying to figure out how AWS Elastic Beanstalk package configuration is created and where is `9.6.2` specified. Does anyone know?

**Comment by salsakran** [comment]
@romanr Nowhere in our code do we care about a specific patch release of PG.

This is specific to your beanstalk environment and out of our control. 

Beanstalk has a lot of internal state that we have no control or even awareness of within Metabase. Closing since this is a specific problem with beanstalk and not us.

I suggest taking a snapshot of your application database and starting with a fresh beanstalk environment. If things are still borked, kindly continue the conversation in our user forum (discourse.metabase.com).
