### ISSUE TITLE
Alert is set to be triggered when progressBar goes below the goal; it gets trigerred also when progressBar equals the goal

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#10899]
I have setup an alert for a progressBar to check hourly and if progressBar is below the goal, it send an email. The problem is that it sends email when the progressBar is less than *or the same as the goal*. In the latter it shouldn't send email. In the email subject it says "[alert_name] has gone below its goal", while in the email body the number it is showing is the same as the goal that I had set.

Metabase Version: 0.33.0

<details><summary>To Reproduce</summary>
<ul>
<li> SampleDB > Orders
<li> create a question: `total count`
<li> Visualization -> progressBar. 
<li> set goal to the result of the query (18760). 
<li> Set alert to send email whenever it goes below the goal (hourly)
</details>

Also a minor edit suggestion regarding Alerts: In the alert setup page, in the third line it says "The first time it *reaches the goal*, ...", but if in second line we choose "Goes Below the goal", this sentence doesn't make much sense. In this case I believe the third line should change to "The first time it goes below the goal, or ...".
![alert](https://user-images.githubusercontent.com/15974735/65001175-593dc500-d8a3-11e9-8fda-7d4ade52806a.png)

**Comment by vvaezian** [comment]
Hi @flamber, any comment on this? I opened this 2 weeks ago, but didn't get any response. Thanks

**Comment by mazameli** [comment]
Hey, @vvaezian. Sorry you didn't get a response from us (incidentally, @flamber is an extremely diligent, but volunteer member of our community, so it's really the job of us @metabase/core-developers to respond to bug reports). I'll need to try and repro this. How much is this impacting your usage of Metabase?

**Comment by vvaezian** [comment]
No worries, and thanks for the reply. Yeah @flamber is very quick and to the point both here and in the discussion forum. I've used his help quite a few times.
 
The impact is not considerable. I guess the workaround is to set the goal one higher than the actual goal (for discrete numbers). 
I just though it is good to have this fixed on the long run.
