### ISSUE TITLE
Cast a string into an integer for a join condition

### ISSUE THREAD

**Issue by khelal** [metabase/metabase#10893]
Using 0.33.2 version of Metabase, and the Papertrail gem in Ruby on Rails, I'm trying to create a join between two tables, using the "whodunnit" as join condition. Unfortunately, I need to "force" that column to an integer as I'm otherwise getting an error. Any idea how I could this?

**Comment by salsakran** [comment]
We do not have the ability to specify a cast for a join condition.

**Comment by flamber** [comment]
Closing in favor of #18974
