### ISSUE TITLE
How to submit a new driver - DB2

### ISSUE THREAD

**Issue by dludwig-jrt** [metabase/metabase#10901]
I am trying to submit my implementation for a AS400 DB2 driver.  What are the procedures?  Attached is my driver project.  It is coded for v0.32 and higher.
[db2.zip](https://github.com/metabase/metabase/files/3621724/db2.zip)

**Comment by flamber** [comment]
Hi @dludwig-jrt 
Awesome job! I don't use DB2, so you'll need other people to test it - ask in #1509.
You'll have to host the driver and receive bug/feature reports. You could setup a repo here on Github.
Check out the Athena driver for inspiration: https://github.com/dacort/metabase-athena-driver
If the driver gets a lot of users, then it might be considered as an officially supported driver and be included in the main releases.

**Comment by dludwig-jrt** [comment]
Uploaded to https://github.com/dludwig-jrt/metabase-db2-driver
