### ISSUE TITLE
Custom column after aggregation: cannot select both aggregated metrics

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#10908]
**Describe the bug**
I want to create a custom column _after_ I have aggregated (as `sum of`) two metrics.  
However, I'm only able to choose one of these.

**To Reproduce**
Remember that [I'm a medium](https://github.com/metabase/metabase/issues/10905)? (TL;DR: I record `(date ; #success ; #attempt)` on a daily basis.)

I now want to get an overview of my potential; namely, by reporting monthly data.

However, _I cannot calculate my monthly succes rate as the average of daily success rates_. 

Indeed, **my monthly average success rate is defined as `sum(#successes) ÷ sum(#attempts)` over a month** (and _not_ as `average(#success ÷ #attempt)`).

Thus, I create a question as follows:

![q2](https://user-images.githubusercontent.com/37387755/65067577-bb1f2d00-d97e-11e9-9d68-4a45b8eef0af.png)

However, when I click on "Custom column" (below the aggregation part), I can select only one metric named `sum` (which is, in this case, the sum of successes):

![Screenshot from 2019-09-17 19-13-24](https://user-images.githubusercontent.com/37387755/65067835-56180700-d97f-11e9-820d-888072a9ae8f.png)

**Expected behavior**

I want to be able to select both of my aggregated metrics (named, e.g., `sum_successes` and `sum_attempts`), so I can create the metric `sum_successes / sum_attempts`.

**Information about your Metabase Installation:**
- Your browser and the version: Firefox Developer Edition 70.0b6
- Your operating system: Fedora 30
- Your databases: Postgres
- Metabase version: 33.2
- Metabase hosting environment: Jar-file
- Metabase internal database: Postgres

**How severe an issue is this bug to you?**
It's quite annoying, as all my percentage metrics are wrong when not plot on a daily basis.

**Comment by flamber** [comment]
Hi @EBoisseauSierra 
Sounds like a duplicate of #5775 (#10759) - if you agree, then please close this issue and upvote the other issue by clicking :+1: on the first post.

**Comment by EBoisseauSierra** [comment]
@flamber It's more related to #10759 imho. Happy to close.
