### ISSUE TITLE
java.lang.NoSuchMethodError error with metabase 0.33.2

### ISSUE THREAD

**Issue by attsn** [metabase/metabase#10916]
**Describe the bug**
We have recently upgraded to metabse 0.33.2 from 0.31.2. 
After the upgrade we have observed that our dashboards and questions are showing  following error frequently-

 ":error "'java.util.List com.google.common.base.Splitter.splitToList(java.lang.CharSequence)'","  error.

To fix the error we have to restart the metabse services. But the error again shows up after couple of hours.

**Logs**
Sep 16 05:36:19 metabase-vm-dup java[13330]:  :class java.lang.NoSuchMethodError,
Sep 16 05:36:19 metabase-vm-dup java[13330]:  :error "'java.util.List com.google.common.base.Splitter.splitToList(java.lang.CharSequence)'",
Sep 16 05:36:19 metabase-vm-dup java[13330]:  :stacktrace
Sep 16 05:36:19 metabase-vm-dup java[13330]:  ("com.google.api.client.http.UriTemplate.expand(UriTemplate.java:305)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "com.google.api.client.http.UriTemplate.expand(UriTemplate.java:262)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequestUrl(AbstractGoogleClientRequest.java:346)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:381)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:499)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:549)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "--> driver.google$execute_no_auto_retry.invokeStatic(google.clj:36)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.google$execute_no_auto_retry.invoke(google.clj:32)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.google$execute$fn__1128.invoke(google.clj:50)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invokeStatic(util.clj:429)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invoke(util.clj:421)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invokeStatic(util.clj:433)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invoke(util.clj:421)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invokeStatic(util.clj:433)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invoke(util.clj:421)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.google$execute.invokeStatic(google.clj:49)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.google$execute.invoke(google.clj:43)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:174)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.bigquery$execute_bigquery.invoke(bigquery.clj:163)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:165)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.bigquery$execute_bigquery.invoke(bigquery.clj:163)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.bigquery$process_native_STAR_$fn__1432.invoke(bigquery.clj:259)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invokeStatic(util.clj:429)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invoke(util.clj:421)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invokeStatic(util.clj:433)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util$do_with_auto_retries.invoke(util.clj:421)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:258)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.bigquery$process_native_STAR_.invoke(bigquery.clj:254)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "driver.bigquery$eval1626$fn__1628.invoke(bigquery.clj:443)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor$fn__43955$execute_query__43960$fn__43961.invoke(query_processor.clj:70)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor$fn__43955$execute_query__43960.invoke(query_processor.clj:64)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__34096.invoke(mbql_to_native.clj:38)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__36340.invoke(annotate.clj:540)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.annotate$add_column_info$fn__36246.invoke(annotate.clj:484)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__37267.invoke(cumulative_aggregations.clj:57)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.resolve_joins$resolve_joins$fn__41065.invoke(resolve_joins.clj:184)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.limit$limit$fn__38003.invoke(limit.clj:19)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__43824.invoke(results_metadata.clj:87)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.format_rows$format_rows$fn__37991.invoke(format_rows.clj:26)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.add_dimension_projections$add_remapping$fn__34855.invoke(add_dimension_projections.clj:232)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__35474.invoke(add_source_metadata.clj:107)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__41115.invoke(resolve_source_table.clj:46)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__35334.invoke(add_row_count_and_status.clj:16)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.driver_specific$process_query_in_context$fn__37478.invoke(driver_specific.clj:12)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.resolve_driver$resolve_driver$fn__40729.invoke(resolve_driver.clj:22)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36669$fn__36670.invoke(bind_effective_timezone.clj:9)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "util.date$call_with_effective_timezone.invoke(date.clj:77)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36669.invoke(bind_effective_timezone.clj:8)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.store$initialize_store$fn__43849$fn__43850.invoke(store.clj:11)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.store$do_with_store.invoke(store.clj:40)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.store$initialize_store$fn__43849.invoke(store.clj:10)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.async$async__GT_sync$fn__34007.invoke(async.clj:23)"
Sep 16 05:36:19 metabase-vm-dup java[13330]:   "query_processor.middleware.async_wait$runnable$fn__36397.invoke(async_wait.clj:89)"),
Sep 16 05:36:19 metabase-vm-dup java[13330]:  :query
Sep 16 05:36:19 metabase-vm-dup java[13330]:  {:constraints {:max-results 10000, :max-results-bare-rows 2000},
Sep 16 05:36:19 metabase-vm-dup java[13330]:   :type :native,
Sep 16 05:36:19 metabase-vm-dup java[13330]:   :middleware {:userland-query? true},
Sep 16 05:36:19 metabase-vm-dup java[13330]:   :native
Sep 16 05:36:19 metabase-vm-dup java[13330]:   {:template-tags
Sep 16 05:36:19 metabase-vm-dup java[13330]:    {"Customer_base"
Sep 16 05:36:19 metabase-vm-dup java[13330]:     {:id "03cb1f70-ae23-74ce-5896-7522fff6c6b0",

**To Reproduce**
1. Start metabase application.
2. Let it run for couple of hours and then the error shows up for all dashboards and questions.

**Information about your Metabase Installation:**
- Your operating system: Ubuntu 18.04
- Your databases: BigQuery
- Metabase version: 0.33.2
- Metabase hosting environment: Jar-file on Ubuntu (GCP Compute Engine)
- Metabase internal database: MySQL

**Severity**
It is impacting all our metabase users. Including Production users.  

**Additional context**
This error was not observed in metabase 0.31.2 version.

**Comment by salsakran** [comment]
I think this might be due to us trying to use a null result from BQ.

I suspect it might be the same root cause as #9989

@attsn can you try out 0.33.4 once that goes out and see if that resolves this?

**Comment by salsakran** [comment]
Calling this a P1 since it's a fundamental thing breaking in an unstable and unpredictable manner, and I _think_ it's already fixed.

**Comment by salsakran** [comment]
closing since:
1)  I think we've fixed it
2) Only one person reported it
3) There's been no response to a confirmation of a fix since October

@attsn if this is still occurring, please let us know and I'll re-open it
