### ISSUE TITLE
Weird, off-logic aggregation shows on a simple coalesce in pie chart

### ISSUE THREAD

**Issue by vrsttl** [metabase/metabase#10914]
**Describe the bug**

In a 445-entry table there's one single entry that should be coalesced into an N/A pie slice. In table view it is displayed correctly as 1, in Pie Chart view it is 1.34.

**To Reproduce**
See attached gif

**Expected behavior**
Pie slice should show 1

**Information about your Metabase Installation:**
- Your browser and the version: All major browsers
- Your operating system: Windows 10 64 bit
- Your databases: Postgres
- Metabase version: 0.33.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

This issue is blocking a minor release.

![pie](https://user-images.githubusercontent.com/36707938/65127764-68825700-d9f8-11e9-8b0d-c2521ac6f82b.gif)

**Comment by vrsttl** [comment]
Also, despite the column title and count being returned they don't show up in the tooltip 😱

**Comment by flamber** [comment]
Hi @vrsttl There were a lot of fixes to pie charts and tooltips in 0.33.2 - can you try that version?

**Comment by vrsttl** [comment]
Hi @flamber , unfortunately it’s not an option at this point, 0.33.1 broke everything so we fell back to 0.33.0. The product owner has explicitly forbidden any changes to MB version. Do you maybe have another suggestion?

**Comment by flamber** [comment]
@vrsttl 
0.33.1 was a botched release, which is why I was saying 0.33.2 (released less then a day after 0.33.1)
But if you are not permitted to update Metabase, then I don't have a solution.
You should probably reconsider the setup, so you have staging before production. This way you can test if a release fixes specific issues or breaks something else.

**Comment by vrsttl** [comment]
@flamber thank you! We’ll see what we can do about it.

**Comment by paulrosenzweig** [comment]
Fixed in #10994
