### ISSUE TITLE
show text instead of ID of foreign key

### ISSUE THREAD

**Issue by 1Nmokhele** [metabase/metabase#10915]
have created a football management system. The problem im getting is that when I fetch the data from the database using PHP, i get the ID of the records however i need to get the text and not ID. When I run the script below on PHPMYADMIN, it returns the correct data

SELECT players.player_name, teams.team_name, players.player_sqd_num, playerposition.position_descr FROM players JOIN teams ON players.team_id = teams.team_id JOIN playerposition ON players.position_id = playerposition.position_id;

But when i try to use the same query on the PHP file, it throws an error:

( ! ) Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in C:\wamp\www\soccersystem\players.php on line 85

The following is my code syntax:

`$count = 1; 
$sel_query = "SELECT players.player_name, teams.team_name, players.player_sqd_num, playerposition.position_descr FROM players JOIN teams ON players.team_id = teams.team_id JOIN playerposition ON players.position_id = playerposition.position_id;";`

The following is my code syntax:

        $result = mysqli_query($con, $sel_query);
        while(
            $row = mysqli_fetch_assoc($result)) { ?>
            <tr>
                <td><?php echo $row["player_name"]; ?></td>
                <td><?php echo $row["team_id"]; ?></td>
                <td><?php echo $row["player_sqd_num"]; ?></td>
                <td><?php echo $row["position_id"]; ?></td>
Where there is an ID field i want it to show the record of the relating to that ID however this is not happening, what am I doing wrong?

Below is my code:

<!DOCTYPE html>
<html>
<head>
	<title>Players Information - Football (Soccer) Management System</title>
</head>
<body>
		<h1 align="center">Welcome To The Players Information Page</h1>

			<table align="center">
			
			<tr>
				<td><a href="competitions.php">| Competitions </a></td>
				<td><a href="teams.php">| Teams </a></td>
				<td><a href="fixtures.php">| Fixtures </a></td>
				<td><a href="player_position.php">| Players Position </a></td>
				<td><a href="players.php">| Players </a></td>
				<td><a href="player_fixtures.php">| Players Fixtures </a></td>
				<td><a href="Reports.php">| Reports |</a></td>
			</tr>
		</table>

		<br>
			<div align="center" style="color: red;">
				<?php 
					date_default_timezone_set('Africa/Johannesburg');

					echo "The time is: "; 
					echo date('h:i:s:A');
					echo "<br />";
					echo "The date is: ";
					echo date('l F jS Y');

				?>
			</div>
		<br>

		<div align="center">
			<img src="img/playerinfo.gif">
		</div>

		<form>
		<table width="100%" border="1" style="border-collapse:collapse;">
		<thead>
		<tr>
		<th align="left"><strong><a href="">Player</a></strong></th>
		<th align="left"><strong><a href="">Team</a></strong></th>
		<th align="left"><strong>Shirt Number</strong></th>
		<th align="left"><strong>Position</strong></th>
		<th align="left"><strong>Actions</strong></th>
		</tr>
		</thead>
		<tbody>
			<?php

			$count = 1;
			$sel_query = "SELECT Distinct * FROM players;";

			$result = mysqli_query($con, $sel_query);
			while(
				$row = mysqli_fetch_assoc($result)) { ?>
				<tr>
					<td><?php echo $row["player_name"]; ?></td>
					<td><?php echo $row["team_id"]; ?></td>
					<td><?php echo $row["player_sqd_num"]; ?></td>
					<td><?php echo $row["position_id"]; ?></td>
					<td>
					<a href="5edit_player.php?id=<?php echo $row["player_id"]; ?>" onclick="return confirm('Do you have administrative rights to edit this record? If yes, click OK or CANCEL to proceed')">Edit</a>

					<a href="5delete_player.php?id=<?php echo $row["player_id"]; ?>" onclick="return confirm('Do you want to delete this player record? If yes, click OK or CANCEL to proceed')">Delete</a>
					</td>
				</tr>
			<?php $count++; } ?>
		</tbody>
		</table>
	</form>

	<?php 

		$query = "SELECT Distinct * FROM teams";

		$team_select = mysqli_query($con, $query);

		$options_team_id = "";

		while($row2 = mysqli_fetch_array($team_select)) {
    	$options_team_id = $options_team_id."<option>$row2[1]</option>";
    	}

	 ?>

	<form action="players.php" method="POST">
		<table>
			<br>
			Add player <br>
			<tr>
				<td>Surname Name
				
				<input type="text" name="player_name" required>
			</td></tr>
			<tr>
			<td>Select Team: 
             <select name="team_id">
             	<?php echo $options_team_id;?>
             </select>
             </td></tr>
			<tr>
			<td>Number
				
				<input type="text" name="player_sqd_num" required>
			</td></tr>
			<br>
				<table width="20%" border="1" style="border-collapse:collapse;">
				<tr>Position</tr>
				<tr>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "1"?> value="">GK
					</td>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "2"?> value="">CB
					</td>
				</tr>
				<tr>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "3"?> value="">LB
					</td>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "4"?> value="">FB
					</td>
				</tr>
				<tr>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "5"?> value="">LWB
					</td>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "6"?> value="">RWB
					</td>
				</tr>
				<tr>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "7"?> value="">SW
					</td>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "8"?> value="">DM
					</td>
				</tr>
				<tr>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "9"?> value="">CM
					</td>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "10"?> value="">AM
					</td>
				</tr>
				<tr>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "11"?> value="">LW
					</td>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "12"?> value="">RW
					</td>
				</tr>
				<tr>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "13"?> value="">CF
					</td>
					<td>
						<input type="radio" name="position_id" <?=$row['position_id'] ? "checked" : "14"?> value="">WF
					</td>
				</tr>
			</table>
			<tr>
			<tr></tr>
				<td>
					<input type="submit" name="insert" value="Submit">
				</td>
			</tr>
		</table>
	</form>
	<?php
		echo $msg;
	?>
	<br>

</body>

</html>`

**Comment by flamber** [comment]
Hi @1Nmokhele 
This is not a PHP support forum. You should use www.stackoverflow.com or such for your question.
Please close this issue :+1:
