### ISSUE TITLE
We need to improve error messages for invalid queries

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10929]
See #10928. In most cases they're schema error messages which are not very friendly.

Since schema error messages are ExceptionInfos that contain data with info about where the schema invalidation occurred we should parse that data and produce a nicer human-readable message. We can do that all in the `catch-exceptions` middleware in the QP. We already simplify the schema exceptions somewhat there so we can build on that logic and humanize the errors as well.

**Comment by camsaul** [comment]
This isn't really a bug. It's more of an improvement proposal

**Comment by luizarakaki** [comment]
Closing in favor of https://github.com/metabase/metabase/issues/27468
