### ISSUE TITLE
permission error messages are not showing

### ISSUE THREAD

**Issue by flyingmachine** [metabase/metabase#10921]
**Describe the bug**

If you try to save data permissions and the server responds with an error message, that error message is not displayed anywhere.

**Logs**

One such error message: `Looks like someone else edited the permissions and your data is out of date. Please fetch new data and try again.`

**To Reproduce**

1. Go to admin -> permissions in two separate tabs
2. Edit and save permissions in tab 1
3. Edit and save permissions in tab 2 - in the devtools console you'll see the server responds with a 409 and the above error message

**Expected behavior**
The error message should be displayed

**Information about your Metabase Installation:**
- chrome
- working on release-0.33.x locally

**Severity**
Annoying

**Comment by salsakran** [comment]
Escalating this since it's possibly dangerous -- If I set permissions and no error occurs, I'd expect it to have been set. Could be convinced it's a p2 if you think otherwise (@mazameli @flyingmachine ?)

**Comment by paulrosenzweig** [comment]
Fixed in #11709
