### ISSUE TITLE
Joining two tables by DateTime columns, casts/parses the join as week/month

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10924]
**Describe the bug**
When using Custom question (Notebook), and joining two tables by `DateTime` columns, the SQL casts/parses the joining-columns as weeks (Postgres) or months (H2).

**To Reproduce**
1. Go to Custom question
2. Select Orders
3. Join by Reviews on Created At = Created At
4. Click "View the SQL"
```SQL
SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PRODUCTS__via__PRODUCT_ID"."TITLE" AS "TITLE", "Reviews"."ID" AS "ID_2", "Reviews"."BODY" AS "BODY", "Reviews"."CREATED_AT" AS "CREATED_AT_2", "Reviews"."PRODUCT_ID" AS "PRODUCT_ID_2", "Reviews"."RATING" AS "RATING", "Reviews"."REVIEWER" AS "REVIEWER"
FROM "PUBLIC"."ORDERS"
LEFT JOIN "PUBLIC"."REVIEWS" "Reviews" ON parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') = parsedatetime(formatdatetime("Reviews"."CREATED_AT", 'yyyyMM'), 'yyyyMM') LEFT JOIN "PUBLIC"."PRODUCTS" "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
LIMIT 1048576
```

**Expected behavior**
Just to join by the selected columns without any casting/parsing.

**Information about your Metabase Installation:**
Metabase 0.33.2 querying Postgres and H2.

**Additional context**
https://discourse.metabase.com/t/0-33-2-join-table-duplicate-rows/7393

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
I'm don't think this is a bug so much as incomplete display of what's happening.

We explicitly cast joined Datetimes and default to weeks or months based on our knowledge of the range. (Correct me if I'm wrong @sbelak @camsaul regarding why H2 and PG have different cases).

With datetimes of arbitrary data, it's extremely unlikely that a join would match given that times are down to seconds. Unless the datetimes are discretized to a large granularity, more often than not the right thing to do is join on a specific time bin. I.e. if you have microsecond based data, most inner joins wouldn't return much. 

We should, whoever, be clear about what's happening and explicitly allow the user to select the date extract

**Comment by sgvandijk** [comment]
As a small extra, this also happens for DATE columns. At least for MySQL, when trying to join on two date columns (`ds`), the join is actually on `str_to_date(concat(yearweek(`table`.`ds`), ' Sunday'), '%X%V %W')`. For DATETIME I can understand binning by default could make sense, but IMHO for date columns this should not be the default case, as they already inherently represent some time binning.

Either way it would indeed be great if an explicit choice can be given, similar to how it works for summarizing by a date/time column!

**Comment by jankatins** [comment]
> With datetimes of arbitrary data, it's extremely unlikely that a join would match given that times are down to seconds. Unless the datetimes are discretized to a large granularity, more often than not the right thing to do is join on a specific time bin. I.e. if you have microsecond based data, most inner joins wouldn't return much.

While this might be true for Timestamps, I don't think it's correct for Dates. 

E.g. when trying to do the equivalent of `Select fact.whatever_date, day.day_date FROM fact LEFT JOIN time.day on fact.whatever_date = day.day_date` with whatever_date has a FK constraint against  day.day_date, it's still doing the conversion to week (postgresql).

But even for TS I would expect that the default JOIN is on equality and only get a warning that such joins are problematic (and a dropdown similar to the way GROUP BYs are done).

**Comment by contradironee** [comment]
+1 especially when something is explicitly cast to a Date type, the granularity should be on a day level, which it currently defaults to months (!) (0.34.0 on Amazon Redshift).

**Comment by Go2ClassPoorYorick** [comment]
Would love to see issues like this get a little bit more attention.

I love metabase and it's been a huge boon with developing BI reports, but I feel like each new release gets me closer to doing everything in the custom query builder for Just one little part preventing a new report from being possible. I'd love to be at the point where all of my questions have drill-downs into other information.

**Comment by vitorbaptista** [comment]
I'm also affected by this, on Metabase v0.36.6 and Snowflake, the default is truncating by month. For my use case, the ideal would be to truncate by day or allow the user to change it.

**Comment by paulvolk** [comment]
@flamber we also encountered this on `Metabase  0.36.4` and Redshift. Hasn't been much movement on this in awhile. Any idea where it lives in the priority stack? Thanks! 🙏

**Comment by apostoltego** [comment]
@flamber We're also facing issues with this on `0.39.1` with postgres.
Primarily the objective is to do time period comparisons (e.g. month on month but limited up until current day) and when attempting to join against a calendar table we're unable to join correctly. Ideally we should be able to choose how timestamps are truncated. There's always the option to write native queries but that never creates an optimal experience for drilldown for end users.

**Comment by RyanHecht** [comment]
+1 for this on `0.39.2` and MySQL -- joining on `DATE(datetime)` casts, they're truncating to month. 

Echoing what @Go2ClassPoorYorick said, I always get _sooo_ close to implementing a complex query in the question editor, but always run into an edge case like this that prompts me to completely rewrite it as a native query, removing all the scalability and flexibility (not to mention non-SQL-literate readability) of the question editor.

**Comment by dabogg** [comment]
We are also facing the same issue basically whenever someone in our company tries to make a join on a date column. As this use case appears on a nearly daily basis and not everyone can simply create a native SQL question this is unfortunately impacting the usability for end users. My assumption would be that if at least only for one certain period (e.g. date) the join would be made "as-is" without casting or parsing, then most users (and people reading this thread) would have a workaround that they can use.

Is there any guess on when this might be addressed? Thanks!
