### ISSUE TITLE
metabot shows up in data permissions but can't have data permissions

### ISSUE THREAD

**Issue by flyingmachine** [metabase/metabase#10920]
**Describe the bug**

1. The Metabot group appears in data permissions and the UI communicates that you can set data permissions for it. However, you are actually not allowed to set permissions for Metabot. You can only set collection permission for Metabot.
2. The user has no way of knowing why they can't set permissions for Metabot because the UI doesn't give them that information.

**To Reproduce**

1. Go to admin -> permissions
2. Try to set grant Metabot with access to a database - change the setting and save
3. The page updates Metabot permissions to show it does not have the access you just granted

**Expected behavior**
Either clearly explain that Metabot can't have data permissions, or remove Metabot from this screen entirely.

**Screenshots**

<img width="1496" alt="Screen Shot 2019-09-18 at 12 23 35 PM" src="https://user-images.githubusercontent.com/1421/65167223-21a05b80-da10-11e9-8460-92e5054ea56f.png">

**Information about your Metabase Installation:**
- local development
- release-0.33.x branch

**Severity**
Annoying

**Comment by marcoruggine** [comment]
I just ran into this issue! Metabot has always run well... we added BigQuery and boom, here we are: we can't save access permission.

**Comment by flamber** [comment]
@marcoruggine Ignore the column. You cannot define Data permissions for MetaBot group, only Collection permissions.

**Comment by Piccirello** [comment]
What's the recommended way to provide MetaBot access to data- is the only way by granting All Users access? Or are you saying that MetaBot will never need direct access to data?
