### ISSUE TITLE
Bar visualization does not work (v0.33.2)

### ISSUE THREAD

**Issue by rjurado01** [metabase/metabase#10934]
**Describe the bug**

Bar visualization does not work

**To Reproduce**

I run this native query on a MongoDB database:

```
[
    {"$match":{
        "date": {
            "$gte": ISODate("2019-09-01T00:00:00.000Z"),
            "$lte": ISODate("2019-09-02T00:00:00.000Z")
        }
    }},
    {"$group": {
       "_id": {"project_id": "$project_id"},
       "project_id": {"$first": "$project_id"},
        "tracking_hours": {"$sum": "$hours"}
    }}
]
```

That returns this information:

![image](https://user-images.githubusercontent.com/1703608/65224840-46560b00-dac4-11e9-96cb-1ee850ce59cc.png)

When I try to create a bar graph with x-axis: `project_id` and y-axis: `tracking_hours` it shows only one bar.

**Screenshots**

![image](https://user-images.githubusercontent.com/1703608/65224972-861cf280-dac4-11e9-9a4d-3c718ac0f41c.png)

![image](https://user-images.githubusercontent.com/1703608/65225719-e3fe0a00-dac5-11e9-8508-3f8d73c23a5b.png)

**Expected behavior**

It should show one bar for each `project_id`, similar to this:

![image](https://user-images.githubusercontent.com/1703608/65225799-08f27d00-dac6-11e9-9be2-c200a9e7439c.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 73.0.3683.86
- Your operating system: Ubuntu 18.04
- Your databases: MongoDB
- Metabase version: v0.33.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**

Hight, some of my graphs are broken.

**Additional context**

The problem apears when I update to `v0.33.2` from `v0.32.10`.

**Comment by paulrosenzweig** [comment]
@rjurado01 thanks for reporting. This bug was fixed in #10827 and will go out with v0.33.3 in the next few days. Sorry for the issues this is causing!
