### ISSUE TITLE
Admin should be told they've tried to add an already existing user or re-activated a de-activated user

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1093]
In the Admin > People screen, when adding a new user, if you enter in an email address that's the same as an already existing user, and then click Add Person, you'll get a confirmation dialog telling you that that person has been added, when in reality nothing happened.

We probably should give an error back as the user is typing in the email field if we see a match between the email address they've added and an existing user: "There's already a user with this email address."

**Comment by camsaul** [comment]
+1 we should probably add a unique constraint to email address so people can't register multiple accounts with the same address.

**Comment by mazameli** [comment]
@agilliland can correct me if I'm wrong, but I think that constraint already exists — the user-facing message is just misleading in that it tells you one thing happened when in reality the app rejected the addition of a duplicate user. So this ticket is strictly about clarifying the user-facing message.

**Comment by agilliland** [comment]
Right, this isn't actually adding a user a second time, it's either 1) making no change because the user already existed and was active or 2) the user was re-activated because the account existed and was disabled.

In either case this is more about messaging to the admin about what actually happened because right now it just appears to the user as if the account was created.

**Comment by mazameli** [comment]
This should be super duper easy if someone has 15 minutes to kill. I took a quick perusal of the frontend code but couldn't figure out where the `else` was to handle the case where we find the user already exists.

**Comment by kdoh** [comment]
This is actually not a problem anymore. When adding a new user if you try and hit "Add" and the email is already in use, the email field gets a message to that effect.
