### ISSUE TITLE
New/Custom Formatting Options

### ISSUE THREAD

**Issue by Linuxfabrik** [metabase/metabase#10941]
Under "Settings" it would be nice to enhance or define custom "Formatting Options" instead of using the predefined ones (because in our case they all don't fit).

* Date style: 2019-12-31
* Date separators: YYYY-MM-DD
* Numbers separator style: 100'000.00

**Comment by flamber** [comment]
Related to #9191

**Comment by flamber** [comment]
Swiss number formatting was implemented in 0.38.0 - closing in favor of #9539 for date format request.
