### ISSUE TITLE
All "date" types in "Data Model" print timestamps in question output

### ISSUE THREAD

**Issue by Linuxfabrik** [metabase/metabase#10944]
Data Model: If you use "Creation date", "Cancelation date", "Join date" etc. for DATE columns in your Metabase Data Model, in a question after "doing science", all date columns are formatted including a timestamp ("2019-2-18, 00:00"). I would expect a "2019-2-18" only.

**Comment by flamber** [comment]
Would be smart if setting Field Type would adjust formatting automatically.
Work-around: Remove the time by clicking the :gear: of the column in Data Model, then Formatting.

**Comment by salsakran** [comment]
This is reasonable, and we have a way of doing that via Formatting as @flamber points out.

I do agree that we should be smarter about this, however.

**Comment by caleb15** [comment]
I'm seeing the same issue for fields that don't have a special type too.

**Comment by flamber** [comment]
Actually this is probably a duplicate of #5859 or #7494

**Comment by flamber** [comment]
Closing in favor of #5859/#7494. Related to #11394
