### ISSUE TITLE
Change in query result before visualization

### ISSUE THREAD

**Issue by amirasaran** [metabase/metabase#10958]
**Is your feature request related to a problem? Please describe.**
I need to alter a query result before being passed to visualization. For example, I have a Mongo query that returns a JSON and I need to alter the JSON before passing to visualization. 

I have a query that results like this:
[Image](https://i.screenshot.net/ypeeeh5)

I need to remove the first layer from the result.

**Describe the solution you'd like**
I think the proper resolution would be a box using JavaScript that can provide access to the result, so the user can change it.

**Describe alternatives you've considered**
I have no idea.

**How important is this feature to you?**
I think this feature can help everyone using Metabase.

**Comment by salsakran** [comment]
Closing, since this is out of scope for the Metabase project. We will not be doing client-side or server side post processing in the foreseeable future. 

We suggest using Native queries for this, or otherwise transforming your data prior to visualization.
