### ISSUE TITLE
[help] Any way to get same day last year revenue for smart card visualisation without having 2 separate filters ?

### ISSUE THREAD

**Issue by prigal** [metabase/metabase#10969]
I have a dashboard with 2 different date filters user can choose to compare one period against the other one.

Most of the time, all my cards on the dashboard are built with SQL to correctly handle dates with join or union queries so we can compare time series or just display smart card with % variations. 

But it's quite a pain, and 100% of time, user compare actual period with same period last year. I ended duplicating my dashboards to remove filters and build :

- day vs same day last year (monday -> monday)
- week vs same week last year
- month vs same month last year

Each dashboard have about 20 queries, all are duplicated 4 times with just some changes in where clauses for dates. 

I'm sure I should be able to build a unique dashboard that handle all these use cases with only a single date filter like this one : 

![Capture d’écran 2019-09-24 à 11 45 35](https://user-images.githubusercontent.com/895267/65501232-e646d680-dec0-11e9-97b1-cb37bd223252.png)

Eg of question :

```
SELECT str_to_date(concat(date_format(`checkout_completed_at`, '%Y-%m'), '-01'), '%Y-%m-%d') AS `checkout_completed_at`, sum(`total`) AS `sum`
FROM `order`
WHERE 1=1
and {{date1}}
union
SELECT str_to_date(concat(date_format(`checkout_completed_at`, '%Y-%m'), '-01'), '%Y-%m-%d') AS `checkout_completed_at`, sum(`total`) AS `sum`
FROM `order`
WHERE 1=1
and {{date2}}
```

I would love to write something like 

```
SELECT str_to_date(concat(date_format(`checkout_completed_at`, '%Y-%m'), '-01'), '%Y-%m-%d') AS `checkout_completed_at`, sum(`total`) AS `sum`
FROM `order`
WHERE 1=1
and {{date1}}
union
SELECT str_to_date(concat(date_format(`checkout_completed_at`, '%Y-%m'), '-01'), '%Y-%m-%d') AS `checkout_completed_at`, sum(`total`) AS `sum`
FROM `order`
WHERE 1=1
and {{date1|offset(1 year)}}
```

Is it something possible ?

**Comment by flamber** [comment]
Hi @prigal 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Currently, you cannot use Field Filters like that. You could perhaps make an advanced sub-query in a calendar-table, which returned `min`/`max`, where you offset those by a period.
You have even commented on one of the issues about time-shifting: https://github.com/metabase/metabase/issues/5817#issuecomment-327190439
There's a request for being able to change the SQL generated by Field Filters - #9155 - but I think it's going to be difficult to implement.
Please close this issue :+1:

**Comment by prigal** [comment]
I totally forgot I have commented on #5817 :)
Ok I understand, I'll close it as long it's referenced on #5817.
