### ISSUE TITLE
Download menu does not close after clicking on the desired download format

### ISSUE THREAD

**Issue by anubhavsahoo** [metabase/metabase#10968]
**Describe the bug**

1. Open any embedded dashboard
2. User clicks download icon
3. Download menu opens
4. User clicks on one of the formats - csv /xslx/json
5. Nothing happens. In the background the API call is in progress to download the results (which might take time depending on the size and complexity of the query)
6. User keeps clicking on one of the options after assuming that no action is taking place
7. This repetitive behaviour quickly overloads the system.

Ideally one of the following should happen after clicking on one of the download formats

1. Disable the download menu and show a loading icon instead
2. Close the menu altogether and show loading for the entire dashboard

**Logs**

Browser Logs
> Please include javascript console and server logs around the time this bug occurred. For dataset::fieldRefForColumn mismatch
> app-embed.bundle.js:5 dataset::fieldRefForColumn mismatch
> app-embed.bundle.js:5 column task_update_time Array(3)
> s @ app-embed.bundle.js:5
> app-embed.bundle.js:5 new Array(3)
> s @ app-embed.bundle.js:5
> app-embed.bundle.js:5 old null
> s @ app-embed.bundle.js:5
> app-embed.bundle.js:5 Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
>     at Object.getDefault (app-embed.bundle.js:5)
>     at b (app-embed.bundle.js:5)
>     at t.getComputedSettings (app-embed.bundle.js:5)
>     at h (app-embed.bundle.js:5)
>     at t.value (app-embed.bundle.js:5)
>     at t.value (app-embed.bundle.js:5)
>     at updateComponent (vendor.bundle.js:1)
>     at u.receiveComponent (vendor.bundle.js:1)
>     at Object.receiveComponent (vendor.bundle.js:1)
>     at u._updateRenderedComponent (vendor.bundle.js:1)
> b @ app-embed.bundle.js:5
> app-embed.bundle.js:5 Error getting setting table._cell_background_getter TypeError: Cannot read property 'rows' of undefined
>     at Object.getValue (app-embed.bundle.js:5)
>     at b (app-embed.bundle.js:5)
>     at t.getComputedSettings (app-embed.bundle.js:5)
>     at h (app-embed.bundle.js:5)
>     at t.value (app-embed.bundle.js:5)
>     at t.value (app-embed.bundle.js:5)
>     at updateComponent (vendor.bundle.js:1)
>     at u.receiveComponent (vendor.bundle.js:1)
>     at Object.receiveComponent (vendor.bundle.js:1)
>     at u._updateRenderedComponent (vendor.bundle.js:1)
> b @ app-embed.bundle.js:5

**To Reproduce**
0. Open any embedded dashboard
1. User clicks download icon
2. Download menu opens
3. User clicks on one of the formats - csv /xslx/json
4. Nothing happens. In the background the API call is in progress to download the results (which might take time depending on the size and complexity of the query)
5. User keeps clicking on one of the options after assuming that no action is taking place
6. This repetitive behaviour quickly overloads the system.

**Expected behavior**
Ideally one of the following should happen after clicking on one of the download formats
1. Disable the download menu and show a loading icon instead
2. Close the menu altogether and show loading for the entire dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/846209/65487959-9ddde780-dec5-11e9-93a5-d55933c41885.png)

**Information about your Metabase Installation:**
Metabase version - 0.33.0
Browser Version - Chrome 76.0.3809.132
Operating System - MacOS 10.14.5
Database - Postgres
Metabase hosting environment - Docker
Metabase internal database - Postgres

**Severity**
I would rate this as a blocker. Most of our users download large datasets via metabase. Because of this bug, a very small set of users are able to block the entire metabase installation. We are left with 2 options either to significantly increase the size/# of instances or move this functionality our of metabase

**Additional context**
NA

**Comment by flamber** [comment]
Hi @anubhavsahoo 
The errors you list are not related to clicking the download buttons. And I think they're fixed in 0.33.3
As for having an loading indicator/status/spinner, when downloading, that's covered in #10566

**Comment by anubhavsahoo** [comment]
Thanks!
I did not know if the logs were related to the issue. 
Can anyone tag this as a duplicate of #10566

**Comment by flamber** [comment]
@anubhavsahoo Just close this issue, if you agree that it's a duplicate of #10566

**Comment by anubhavsahoo** [comment]
Sure
