### ISSUE TITLE
Support Stacked Row charts

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#10967]
We currently allow you to have a stacked bar chart, but not a row chart.

In general, row charts should just be a rotation of a bar chart and otherwise be equivalent.

thoughts @mazameli @kdoh ?

#5855

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
100%. There's no reason not to do this other than time constraints.

**Comment by sbelak** [comment]
Massive +1. Stacked row charts would be super useful in comparison x-rays

**Comment by henrytran026** [comment]
is there any timeline for this feature?
