### ISSUE TITLE
Chart legend not fully visible in dashboard (only color dot)

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#10971]
Adding for example a bar chart with several series to a dashboard makes the series legend disappear, i.e. only the coloured dots are seen:

![image](https://user-images.githubusercontent.com/24734846/65517542-2e76f080-dee3-11e9-98b8-96d20ba0efe8.png)

Would be great if spread across the width of the dashboard card, so that (at least) part of the description can be seen without needing to hover over the series.

Your browser and the version: Chrome Version 66.0.3359.181
Your operating system: Windows 10
Your databases: BigQuery
Metabase version:v0.33.3
Metabase hosting environment: Heroku

**Severity**
Annoying when viewing dashboards

**Comment by salsakran** [comment]
what I think is happening is that we don't have room to display all the chart labels in the horizontal space present.

Regardless, this is annoying.

**Comment by flamber** [comment]
Closing in favor of #11355
