### ISSUE TITLE
Axes value does not adjust automatically when changing to "stacked" chart view

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#10972]
Axes value does not adjust when changing the visualization of a chart to "stacked". 
I have to add up the stacked value and adjust the axis' maximum manually to make it fit.

Your browser and the version: Chrome Version 66.0.3359.181
Your operating system: Windows 10
Your databases: BigQuery
Metabase version:v0.33.3
Metabase hosting environment: Heroku

**Severity**
annoying

**Comment by paulrosenzweig** [comment]
@HelenMertes I wasn't able to reproduce the issue. What does your data look like? Are you able to reproduce the issue on the sample dataset that ships with Metabase? 

I updated some of the y-axis scaling code in v0.33.3, so I'm guessing this is related that. Thanks in advance for your help reproducing this!

**Comment by paulrosenzweig** [comment]
@HelenMertes is there any other info you can provide to help us reproduce this issue? Thanks!
