### ISSUE TITLE
Allow scrolling (remove freezing) of query output when raw query edited, until run again

### ISSUE THREAD

**Issue by dnmabra12** [metabase/metabase#10975]
A new 'feature' was added recently that freezes, or grays out the query output if a question is manipulated. 

This leads to issues in copying text, scrolling through output to edit a query, etc. 

Is there a reason this was added? It seems far more useful to allow users to scroll through output as normal, until the edited query is run again.

**Comment by Mycorino** [comment]
Totally agree with dnmabra12 !!! I face often large tables where I forget the exact name of the columns so I need to cmdZ and then cmd shift z to see the previous result and come back because I can't scroll and see my previous result

**Comment by mazameli** [comment]
Yeah, the attempt with this change was to free up space for the results by only displaying the run button when necessary, but it's clear it's caused unnecessary problems.

My thinking is we should move the run button into the editor when it's expanded and stop fading out the results. When the editor is _collapsed_ I think we can keep the current behavior (so for example if a user fills in a SQL filter widget, they'd then see the run button over the results spaces as it currently works).

**Comment by mazameli** [comment]
Fixed via https://github.com/metabase/metabase/pull/11378
