### ISSUE TITLE
Row charts should not display options to use line or area markings on the Display tab

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10974]
![image](https://user-images.githubusercontent.com/2223916/65540249-d8dd1c80-debf-11e9-8a20-e94a8a7b4487.png)

It's nonsensical to display the button group with line/area/bar next to the series input box for Row Charts. They don't do anything. The only Display options that should be currently available for Row Charts are color and series name.

**Comment by paulrosenzweig** [comment]
Fixed in #10979
