### ISSUE TITLE
Issues logging in with LDAP in 0.33.0

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10988]
From @amoskaliov in #10986:

> So after upgrading to 0.33.3 I had two problems:
> * this one [#10986]
> * LDAP users can't log in. In logs I had the following error:
>     ```
>    ERROR api.session :: Problem connecting to LDAP server, will fall back to local authentication
>    LDAPException(resultCode=34 (invalid DN syntax), errorMessage='Unable to parse string 'DN: cn=data-analysts,ou=group,dc=***,dc=***' as a DN because it does not have an equal sign after RDN attribute 'DN:'.', ldapSDKVersion=4.0.4, revision=27051)
>    ```
>    (asterisks added)
> 
> I connected to Postgres DB and edited `ldap-group-mappings` field in public.setting (removed `DN: `) and also `settings-last-updated` field (set to current time). After this fix and restart both problems disappeared. Can't say exactly how it's all connected, but I hope this will help you.

**Comment by camsaul** [comment]
It sounds like the LDAP attribute we're using to sync groups doesn't work on this LDAP server

> Unable to parse string 'DN: cn=data-analysts,ou=group,dc=***,dc=***' as a DN because it does not have an equal sign after RDN attribute 'DN:'.'

**Comment by camsaul** [comment]
AFAIK it is working on other LDAP setups. @amoskaliov what LDAP server are you using?

**Comment by amoskaliov** [comment]
This is OpenLDAP: slapd 2.4.47. Are you sure it is the LDAP server problem? As I understand the error comes from ldapSDK.

**Comment by flamber** [comment]
@amoskaliov Are you using group mapping? If yes, then it should work if you disable that. Not a fix/workaround, but just to try to narrow down the problem.
Reference: https://discourse.metabase.com/t/ad-ldap-authentification-with-metabase-v0-33-2/7417

**Comment by BartOon** [comment]
It's with Windows Active Directory ?

**Comment by amoskaliov** [comment]
It's not AD, it's OpenLDAP. I tried to use group mappings, but we use `memberUid` scheme, which doesn't seem to be supported in Metabase. Some group mapping settings were set though. Maybe this is was the problem. But while using 0.32.8 I had no problems with them.

**Comment by hameno** [comment]
Any update here? Getting the same errors in our install (0.33.5)

**Comment by flamber** [comment]
@hameno Please upgrade to 0.33.6, since 0.33.5 was a bad release (depending on how you run it).

**Comment by walterl** [comment]
I was unable to reproduce this on current `master`, 0.33.5 or 0.33.0. All connecting to a slapd 2.4.40-16.el6 (Centos 6) server, based on [this Dockerfile](https://github.com/Enalean/docker-ldap/blob/master/Dockerfile).

@amoskaliov, @hameno: Can you still reproduce this error? If so, we're going to have to dig a bit deeper into your setups.

**Comment by walterl** [comment]
Closing until we can confirm that this is still an issue.
