### ISSUE TITLE
Unarchive question/dashboard/etc in one click from the "We're a little lost..." page

### ISSUE THREAD

**Issue by CyrilVinot** [metabase/metabase#10987]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open the page of a question (https://alan-metabase.herokuapp.com/question/<card_id>) that turns out to be archived and I cannot :
- see the name and description of the question anymore
- unarchive the question in a click (looks like going to the `/archive` page which is far from easy to use, or using the API are the only options) 

**Describe the solution you'd like**
I want to be able to unarchive a question in a click from the question's page
I also think it's useful to show more on the page of an archived questions (at least the name and description which can be handy to give some context on the question)

**How important is this feature to you?**
We are offensively archiving deprecated questions to keep a 'clean' Metabase. Sometimes we end up mistakenly archiving questions that are still useful. For this to work efficiently we need every contributor to be able to easily recover archived questions.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by haydn** [comment]
Here's a bit of a workaround for anyone trying to work out what the name of an archived question is:

1. Open the page for the archived question (`http://<YOUR METABASE INSTANCE>/question/<CARD ID>`).
2. Pop open the [browser developer tools](https://en.wikipedia.org/wiki/Web_development_tools).
3. Go to the _Network_ tab and refresh the page.
4. Select the XHR request to `/api/card/<CARD ID>`.

You should see some JSON content in the _Preview_  or _Response_ tab that includes a `name` field.
