### ISSUE TITLE
Pulse emails not getting triggered

### ISSUE THREAD

**Issue by nishu** [metabase/metabase#10991]
**Describe the bug**
On version 0.33.4 and 0.33.3 pulses are not getting triggered for last 2 days. This is for both test and scheduled pulses.

**Logs**
API log suggests that pulse test is triggered but there is no corresponding entry in the table task_history corresponding to it. 
09-26 09:25:35 DEBUG middleware.log :: POST /api/pulse/test 200 3.5 s (11 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (72 total active threads) Queries in flight: 0

Test Email from Metabase Admin is getting delivered.

**To Reproduce**
1. Go to 'New Pulse'
2. Create a New Pulse with existing question
3. Click on 'Send email now'

**Information about your Metabase Installation:**
Metabase is running on OpenJDK with Postgres as database. It uses AWS SES for sending emails.

**Severity**
This bug impacts workflow depending on getting data in emails.

**Comment by nishu** [comment]
Resolution:
AWS SES was the issue.

**Comment by flamber** [comment]
Hi @nishu 
Did you resolve the problem? Could you explain what you did, in case someone else searches for the same solution?
By the way, latest release is 0.33.3
