### ISSUE TITLE
Consider more data source support, such as Clickhouse

### ISSUE THREAD

**Issue by telltime** [metabase/metabase#10990]
Consider more data source support, such as Clickhouse

**Comment by amoskaliov** [comment]
I can advise you https://github.com/enqueue/metabase-clickhouse-driver . Works perfect.

**Comment by flamber** [comment]
Hi @telltime 
As @amoskaliov pointed out, there's a third-party driver available.
You might want to update #3332, if you're asking for getting a driver integrated in main releases.
But please close this issue :+1:

**Comment by salsakran** [comment]
duplicate of #3332
