### ISSUE TITLE
Support Multiple Value Parameters in Custom SQL

### ISSUE THREAD

**Issue by tuaris** [metabase/metabase#10992]
**Is your feature request related to a problem? Please describe.**
It's only possible to setup an SQL Parameters that allows the user to type in a single value when not using a field filter in custom SQL mode.

**Describe the solution you'd like**
When not using a field filter, there should be an option to have the user type in multiple values so that the value can be used as an "IN" clause.

**Describe alternatives you've considered**
Filter widgets although provide this ability can’t be used for all data types.  

**How important is this feature to you?**
In my specific case I want to filter on one or more email addresses.  As stated in the [documentation](https://metabase.com/docs/v0.33.3/users-guide/13-sql-parameters.html#the-field-filter-variable-type), it's not possible to use a field filter on an email address data type.

**Additional context**
https://discourse.metabase.com/t/table-fields-missing-in-from-select-list-when-setting-up-filters/7465/2

**Comment by flamber** [comment]
@tuaris A work-around would be to split the variable string into rows or something like this:
```SQL
--MySQL
SELECT * FROM table WHERE FIND_IN_SET(column, {{FilterText}});
--Postgres
SELECT * FROM table WHERE column = ANY(string_to_array({{FilterText}}, ','))
```

**Comment by camsaul** [comment]
Actually we do support this already but only for filtering against numbers right now. If you type in `1,2,3` for example it with do the equivalent of `column IN (1, 2, 3)`.

**Comment by flamber** [comment]
Not sure how I forgot, closing in favor of #4728
