### ISSUE TITLE
Group by Sliding Window

### ISSUE THREAD

**Issue by bvallelunga** [metabase/metabase#10995]
**Is your feature request related to a problem? Please describe.**
We are using Metabase to look at averages of a metric grouped by week. The problem with this approach is that the current week is getting compared to the previous week. If I am on a Monday, then the current week has 2 days of data points where last week had seven days creating an unfair average comparison.

**Describe the solution you'd like**
It would be great if we could group by a sliding window of (hours, days, months, years). For example if I could get a slide window of grouping of the last 7 days, that would solve my current problem.

**How important is this feature to you?**
This feature is a very important request for us as a lot of metrics are averages benchmarked on a weekly (preferred 7 day window) caidence.

**Comment by flamber** [comment]
Hi @bvallelunga 
Sounds like a duplicate of #9393 (or one of the several issues linked from that) - if you agree, then please close this and upvote the issue by clicking :+1: on the first post.

**Comment by sbelak** [comment]
@bvallelunga would something like #9400 be useful to you as well?

**Comment by bvallelunga** [comment]
Hi @flamber and @sbelak both of those issues would be useful. Will close issue and upvote.
