### ISSUE TITLE
Running Metabase on Debian as a service with nginx - ubuntu log permissions issue

### ISSUE THREAD

**Issue by grimxd** [metabase/metabase#11001]
**Describe the bug**
I didn't test on Debian but on Ubuntu 18.04 the following commands are causing the metabase.log not being populated because of permission issues. 

```
$ sudo touch /var/log/metabase.log
$ sudo chown metabase:metabase /var/log/metabase.log
$ sudo touch /etc/default/metabase
$ sudo chmod 640 /etc/default/metabase
```
For some reason rsyslog is writing the logs as a special user and not as the user that is running the process, in this case the `metabase` user. 
So giving permissions only to the `metabase` user is blocking rsyslog from writing the logs in the file. 
The solution that worked for me was to ignore those lines completely in the deployment process or simply to remove the /var/log/metabase.log so rsyslog would create it by itself. 

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-VI",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11-post-Ubuntu-1ubuntu218.04.3",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11-post-Ubuntu-1ubuntu218.04.3",
    "os.name": "Linux",
    "os.version": "4.15.0-64-generic",
    "user.language": "en",
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-09-20",
      "tag": "v0.33.3",
      "branch": "release-0.33.x",
      "hash": "86d32bf"
    },
  }
}
```
**Severity**
**LOW**: /var/log/metabase.log file is not being populated with logs on Ubuntu 18.04 but you can find the logs in the /var/log/syslog.log file

**Comment by salsakran** [comment]
Closing this since specifics of permissions in various deployments is outside the scope of the project. Lots of folks run us in all kinds of configurations and we can't account for every nuance.

Also, I'm unclear as to why you're "running Metabase on debian" on an ubuntu machine? If I'm not understanding this correctly, please let me know and we'll re-open if it's actually a bug in the Metabase code itself.
