### ISSUE TITLE
Make it more clear which dimensions are being summarized by in the query builder

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#11019]
**Is your feature request related to a problem? Please describe.**
We've got some quite wide tables in our data model, many are linked to quite a few other tables.

In the v0.33.3 simple query builder it can be hard to see what "Group Bys" are currently active, and also hard to browse for a specific field. I know I can use the search which is great, but sometimes it makes more sense to browse.

v0.33.3:
By glancing at the group by panel on right I don't know what groupings are active, and I've got a lot of scrolling to see what fields are available in each linked table
![image](https://user-images.githubusercontent.com/4504437/65918059-45629900-e435-11e9-86bf-70fe40f7f49f.png)

v0.32.10:
I can instantly glance up at the group by section and know what's active (and remove/update them), and the collapsible sections for each linked table makes it easy to find new fields to group by.
![image](https://user-images.githubusercontent.com/4504437/65918664-b2c2f980-e436-11e9-83fd-bff024b76d77.png)

**Describe the solution you'd like**
Add a section at the top of the "Group By" panel listing the current active groupings.

Make the tables under the "Find" box individually collapsible, base table expanded by default, linked tables collapsed.

**Describe alternatives you've considered**
Using the search works but is sometimes cumbersome. 

The active groupings could also be added above the charts beside the active filters, with the same collapsible button, that may be more consistent as you can see them without activating the summarise panel on the right.

**How important is this feature to you?**
It's a usability thing so not really critical, but in saying that I'm trying to push the use of Metabase here and little things like this matter to the wider user base. We're trying to push Metabase for data exploration and having to scroll endlessly to see what fields are available for a specific table feels like a chore.

**Additional context**

Thanks

**Comment by salsakran** [comment]
Thanks for the feedback. I'm changed the title to reflect the underlying problem (clarity of what the summarization is by) rather than a specific mechanism for solving it (collapsing).

**Comment by notrom** [comment]
@salsakran thanks for that. Just want to convey that the collapsing is still important when dealing with large wide tables. Finding what you're looking for and/or is available is much simpler when you've got the context of the tables as the first level of visual filtering.

**Comment by flamber** [comment]
Fixed by #18587
