### ISSUE TITLE
Simple question builder, adding a second (or subsequent) date grouping forces a month grouping regardless of what you actually want

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#11021]
**Describe the bug**
If I've already got a grouping on, then want to add a second (or third ...) grouping by a date year, I need to first get the month grouping summary, then update that to select the year instead. This feels like a UX bug to me?

**Logs**
No logs

**To Reproduce**
1. Simple Question > Sample Data > Order
2. Summarize, group by Product > Category
3. Want to add a yearly summary of orders by category.
4. Selecting Order > Created At > Year replaces the previous grouping
5. Browser back button
6. This time use the "+" button on Created At, this creates monthly summary of orders by category.
7. Can now update the Created At grouping to use by year

This is OK on the sample data set, but on some larger more complex datasets this requirement to hop through the monthly summary to get to yearly can take some time.

In v0.32.10 this doesn't occur, you can select the date summary period up front when adding the grouping.

**Expected behavior**
I should be able to specify the period of a date summary up front.

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/65921340-76939700-e43e-11e9-9d38-e4e92133e3a0.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome v76.0.3809.100
- Your operating system: Windows
- Your databases: SQL Server
- Metabase version: 0.33.3
- Metabase hosting environment: Jar file on Windows
- Metabase internal database: Postgres

**Severity**
Frustration only, not critical. But we've got a couple of large slow tables and this extra step can cause frustration.

Thanks

**Comment by flamber** [comment]
Fixed by #18587
