### ISSUE TITLE
Update Hive/Spark SQL JDBC driver (?)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#11023]
We're currently using 1.2.1 but it looks like [3.1.2 is out](https://mvnrepository.com/artifact/org.apache.hive/hive-jdbc). It seems like the newer driver isn't backward-compatible with the version of Hive/Spark SQL we're running in the test suite so we'll want to consider what version(s) to support going forward.

I ran into this issue when using the newer driver:

> Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{set:hiveconf:hive.server2.thrift.resultset.default.fetch.size=1000, use:database=default}

We should try to figure out which JDBC driver will support the most versions or if there's some way we can support as many version as possible with a single JDBC version.

**Comment by sbelak** [comment]
At he very least it would be nice to require 2.3 as that gives a ton of new built in SQL functions to work with.
