### ISSUE TITLE
Update to newer Vertica DB for tests

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#11022]
Right now we're testing against Vertica 7.1.2, but 9.2.1 is out. 

We'll need to use a newer Docker image for CI. The one we're currently using seems like it's no longer being actively developed/ [jbfavre/vertica:latest](https://github.com/jbfavre/docker-vertica) looks like a reasonable replacement, I was able to drop it in without having to change any env vars. We will also need to switch the JDBC driver version used in CI.

I switched to a newer 9.x JDBC driver, but I've ran into a few problems when running tests: 

```
Caused by: com.vertica.support.exceptions.DataException: [Vertica][VJDBC](3787) ROLLBACK: Invalid value for parameter
 at com.vertica.util.ServerErrorData.buildException (:-1)
    com.vertica.dataengine.VResultSet.fetchChunk (:-1)
    com.vertica.dataengine.VResultSet.initialize (:-1)
    com.vertica.dataengine.VQueryExecutor.readExecuteResponse (:-1)
    com.vertica.dataengine.VQueryExecutor.handleExecuteResponse (:-1)
    com.vertica.dataengine.VQueryExecutor.execute (:-1)
    com.vertica.jdbc.common.SPreparedStatement.executeWithParams (:-1)
    com.vertica.jdbc.common.SPreparedStatement.executeUpdate (:-1)
```

This was happening when loading the test data. So we'll have to work out why that's happening in order to upgrade.

**Comment by metamben** [comment]
@camsaul Should we use [vertica/vertica-ce](https://hub.docker.com/r/vertica/vertica-ce)?

**Comment by camsaul** [comment]
Yeah, that looks like it could work!
