### ISSUE TITLE
Allow email-based pulses to be sent hourly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11029]
This is kind of related to https://github.com/metabase/metabase/issues/3846 and https://github.com/metabase/metabase/issues/3135 but is a much simpler proposal to just give email pulses the same options as Slack pulses — i.e. just add the `Hourly` option to emails.

![image](https://user-images.githubusercontent.com/2223916/65995407-510c8a80-e44a-11e9-9727-62506a3b5450.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by liaoxu** [comment]
yes, quite useful, and it would be better if can support cron expressions

**Comment by eshnil** [comment]
@liaoxu We at polyglot.network had implemented both these patches: Hourly email, and Cron expression for Email & Slack pulses. Whatever quartz-scheduler can do, Metabase can do too. We did this work for a client, who's using an earlier version of metabase. Please get in touch if you're interested.

**Comment by liaoxu** [comment]
> @liaoxu We at polyglot.network had implemented both these patches: Hourly email, and Cron expression for Email & Slack pulses. Whatever quartz-scheduler can do, Metabase can do too. We did this work for a client, who's using an earlier version of metabase. Please get in touch if you're interested.

thanks

**Comment by xjuanc** [comment]
Any news on this for the official repo?
