### ISSUE TITLE
How to make native/custom queries uneditable ?

### ISSUE THREAD

**Issue by HamzaInayat** [metabase/metabase#11033]
I have unrestricted data access of metabase (not admin). I want to lock my queries that i have written , so that someone cannot change those queries. They will be able to see the output of the query or may even read/copy the code as well. But, cannot change the sql code in already saved questions. How to do that in meta ?

**Comment by flamber** [comment]
Hi @HamzaInayat 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
If you want questions to be view-only, then add then to a collection, where you have set that permission level. Read more about collection permissions in the documentation:
https://www.metabase.com/docs/latest/administration-guide/06-collections.html
And please close this issue :+1:

**Comment by salsakran** [comment]
closing since this isn't the appropriate forum to ask questions. Please use the forum, as @flamber suggested.
