### ISSUE TITLE
User feedback when downloading results to CSV/XLSX/JSON

### ISSUE THREAD

**Issue by sebasgarcep** [metabase/metabase#11035]
Currently, if you try downloading a report as CSV/XLSX/JSON, there is no feedback to indicate the user that the download has begun and that he must wait for results. We would like the download menu to close automatically and for some indicator to appear and notify the user that his download is in progress.

**Comment by mazameli** [comment]
Thanks for the feedback @sebasgarcep. This is a direct duplicate of issue https://github.com/metabase/metabase/issues/10566 however, so I'm going to close this in favor of that issue.
