### ISSUE TITLE
Disable Transactions for Native Query

### ISSUE THREAD

**Issue by sebasgarcep** [metabase/metabase#11034]
I'm using native queries to execute a stored procedure on our Azure SQL Data Warehouse. Unfortunately, native queries are run inside transactions, which do not allow DDL statements to be run. This means that Session-level temp tables cannot be created and we must rely on Database tables to write intermediate results (we haven't been able to optimize certain views to run as efficiently as stored procedures would). Then we have either of two problems:

1. The same question cannot be run more than once at the same time.
2. We need to namespace the intermediate results and periodically delete old records from these tables. This is unwieldy as a stored procedure can easily use 10 temp tables and this just makes everything more complex.

If we could disable transactions our problem would be solved but we currently haven't found a way to do so. Is there any way to do this or is this feature missing ?

**Comment by lindsay-stevens** [comment]
If you want to customise how Metabase interacts with your data warehouse, the easiest way to do that would be to [create a custom driver](https://github.com/metabase/metabase/wiki/Writing-A-Driver). This doesn't mean you have to re-implement the entire MSSQL driver, or worry about query protocols, or fork Metabase, etc. In this case a "driver" is just a Clojure module that defines how to interact with a type of database. To make it even easier, you can inherit methods from an existing driver, and just implement the parts that are different for your use case. Then you distribute your driver as a plugin JAR. The hardest part is learning some Clojure, but even then you could learn just enough to call out to Java and implement it in Java.

**Comment by sebasgarcep** [comment]
Ok
