### ISSUE TITLE
Cannot decrypt encrypted string on v0.33.3

### ISSUE THREAD

**Issue by Siao-pin** [metabase/metabase#11048]
**Describe the bug**
I see in logs a crypto bug on latest metabase version v0.33.3. I saw similar problem was fixed already for previous version - https://github.com/metabase/metabase/pull/10539. Why it is reappeared?

**Logs**
[0ea7a254-d637-45da-96bd-93190728bbda] 2019-10-03T11:21:50+03:00 WARN metabase.util.encryption Невозможно расшифровать зашифрованную строку. Вы изменили или забыли установить MB_ENCRYPTION_SECRET_KEY? Message seems corrupt or manipulated. ("buddy.core.crypto$fn__23094.invokeStatic(crypto.clj:489)"
"buddy.core.crypto$fn__23094.invoke(crypto.clj:478)"
"clojure.lang.MultiFn.invoke(MultiFn.java:229)"
"buddy.core.crypto$decrypt.invokeStatic(crypto.clj:572)"
"buddy.core.crypto$decrypt.invoke(crypto.clj:559)"
"--> util.encryption$decrypt.invokeStatic(encryption.clj:65)"
"util.encryption$decrypt.invoke(encryption.clj:57)"
"util.encryption$maybe_decrypt.invokeStatic(encryption.clj:108)"
"util.encryption$maybe_decrypt.doInvoke(encryption.clj:96)"
"models.setting.cache$restore_cache_BANG_.invokeStatic(cache.clj:122)"
"models.setting.cache$restore_cache_BANG_.invoke(cache.clj:118)"
"models.setting$fn__18970$set_string_BANG___18975$fn__18976.invoke(setting.clj:283)"
"models.setting$fn__18970$set_string_BANG___18975.invoke(setting.clj:268)"
"models.setting$set_timestamp_BANG_.invokeStatic(setting.clj:343)"
"models.setting$set_timestamp_BANG_.invoke(setting.clj:340)"
"models.setting$set_BANG_.invokeStatic(setting.clj:386)"
"models.setting$set_BANG_.invoke(setting.clj:374)"
"models.setting$setting_fn$fn__19016.invoke(setting.clj:459)"
"metabot.instance$update_last_checkin_BANG_.invokeStatic(instance.clj:63)"
"metabot.instance$update_last_checkin_BANG_.invoke(instance.clj:60)"
"metabot.instance$become_metabot_BANG_.invokeStatic(instance.clj:105)"
"metabot.instance$become_metabot_BANG_.invoke(instance.clj:99)"
"metabot.instance$check_and_update_instance_status_BANG_.invokeStatic(instance.clj:120)"
"metabot.instance$check_and_update_instance_status_BANG_.invoke(instance.clj:108)"
"metabot.instance$start_instance_monitor_BANG_$fn__55191.invoke(instance.clj:132)")

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_191-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_191",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.191-b12",
    "os.name": "Linux",
    "os.version": "3.10.0-862.14.4.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Moscow"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "vertica",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.3",
      "date": "2019-09-20",
      "branch": "release-0.33.x",
      "hash": "86d32bf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Just confirming. It was reported in the forum too yesterday (along with another problem):
https://discourse.metabase.com/t/changing-an-existing-question-sorry-you-dont-have-permission-to-see-that/7553

**Comment by Siao-pin** [comment]
So, will you fix this issue?

**Comment by flamber** [comment]
@Siao-pin As you've probably noticed, there's more than 2k open issues, so please allow some time to check, validate and fix new issues. But yes, it will be fixed.

**Comment by flamber** [comment]
Similar problem was [reported in the forum](https://discourse.metabase.com/t/problem-after-dist-upgrade-ubuntu-16-04-18-04/8054/8?u=flamber) after Ubuntu 16.04 -> 18.04 upgrade. Long thread. I'm not sure if it's relevant, but the key was 44 characters.
There was also a [different forum topic](https://discourse.metabase.com/t/changing-an-existing-question-sorry-you-dont-have-permission-to-see-that/7553/3?u=flamber) about another problem, but gave same error too.
Still don't know what's causing this.

**Comment by Limess** [comment]
We're also seeing this issue, but it seems we're only seeing it on one of the two instances we're running:

```
[175aba42-d460-48b9-b4ef-a78dea0f2eda] 2020-04-04T18:03:25+01:00 WARN metabase.util.encryption Cannot decrypt encrypted string. Have you changed or forgot to set MB_ENCRYPTION_SECRET_KEY? Message seems corrupt or manipulated. ["buddy.core.crypto$fn__26906.invokeStatic(crypto.clj:489)"
 "buddy.core.crypto$fn__26906.invoke(crypto.clj:478)"
 "clojure.lang.MultiFn.invoke(MultiFn.java:229)"
 "buddy.core.crypto$decrypt.invokeStatic(crypto.clj:572)"
 "buddy.core.crypto$decrypt.invoke(crypto.clj:559)"
 "--> util.encryption$decrypt.invokeStatic(encryption.clj:65)"
 "util.encryption$decrypt.invoke(encryption.clj:57)"
 "util.encryption$maybe_decrypt.invokeStatic(encryption.clj:108)"
 "util.encryption$maybe_decrypt.doInvoke(encryption.clj:96)"
 "models.setting.cache$restore_cache_BANG_.invokeStatic(cache.clj:122)"
 "models.setting.cache$restore_cache_BANG_.invoke(cache.clj:118)"
 "models.setting$fn__21711$set_string_BANG___21716$fn__21717.invoke(setting.clj:286)"
 "models.setting$fn__21711$set_string_BANG___21716.invoke(setting.clj:271)"
 "models.setting$set_timestamp_BANG_.invokeStatic(setting.clj:347)"
 "models.setting$set_timestamp_BANG_.invoke(setting.clj:344)"
 "models.setting$set_BANG_.invokeStatic(setting.clj:393)"
 "models.setting$set_BANG_.invoke(setting.clj:378)"
 "models.setting$setting_fn$fn__21757.invoke(setting.clj:466)"
 "metabot.instance$update_last_checkin_BANG_.invokeStatic(instance.clj:62)"
 "metabot.instance$update_last_checkin_BANG_.invoke(instance.clj:59)"
 "metabot.instance$check_and_update_instance_status_BANG_.invokeStatic(instance.clj:114)"
 "metabot.instance$check_and_update_instance_status_BANG_.invoke(instance.clj:105)"
 "metabot.instance$start_instance_monitor_BANG_$fn__57932.invoke(instance.clj:129)"]
```

I have tried manually removing the relevant metabot settings row however it doesn't resolve the issue (the row is just re-created later and still logs the same encryption error).

We are using an encryption key.

**Comment by marciuz** [comment]
Hi some update about this? 
I have the same problem also with an update from Ubuntu 16.04 to 20.04 ...

**Comment by flamber** [comment]
@marciuz I'm sure you'll have the same problem with any update you make, since the problem was there when you tried to update 16.04->18.04.
Something has caused the encryption to be bad - I think it's something to do with quotes on environment variables and shell versions.

Your best solution would be to manually replace the encrypted parts (mainly `metabase_database.details` I think in your case) with unencrypted strings, then update the system, and then re-apply encryption (which most likely will be different, and work correctly from that point).
Have look in the forums posts linked in my previous comment.

**Comment by marciuz** [comment]
Great insight @flamber , I resolved! 

I have a service in `/etc/systemd/system/metabase.service` 
with this code: 

```
[Unit]
Description=Metabase application service
Documentation=https://www.metabase.com/docs/latest

[Service]
WorkingDirectory=/opt/metabase

Environment=MB_DB_TYPE=mysql
Environment=MB_DB_DBNAME=mydb
Environment=MB_DB_PORT=3306
Environment=MB_DB_USER=myuser
Environment=MB_DB_PASS=mypassword
Environment=MB_DB_HOST=127.0.0.1

Environment=MB_JETTY_PORT=3003
Environment=MB_ENCRYPTION_SECRET_KEY='beo5HU----------mykey--------ahg8='
ExecStart=/usr/bin/java -Xms128m -Xmx256m -jar metabase.jar
User=metabase
Type=simple
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target

```

The quotes were interpreted literally on Ubuntu 18.04 or 20.04, so it was enough to add two double quotes: 
```
Environment=MB_ENCRYPTION_SECRET_KEY="'beo5HU----------mykey--------ahg8='"
```

... and **it works!**

**Comment by flamber** [comment]
@marciuz Excellent details and wonderful it works! I will make a note in the documentation.
