### ISSUE TITLE
Add OData driver

### ISSUE THREAD

**Issue by nosovk** [metabase/metabase#11053]
Part of erp systems provides OData api to fetch data:
Microsoft Axapta - https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/odata
1C Enterprice - https://1c-dn.com/1c_enterprise/rest_interface/
bpmOnline - https://academy.bpmonline.com/documents/technic-sdk/7-13/possibilities-bpmonline-integration-over-odata-protocol

would like to analize data from those systems in metabase

There is JDBC connector avalible https://www.cdata.com/drivers/odata/jdbc/
but wasnt able to get it to work with 1C solution.

**Comment by flamber** [comment]
Hi @nosovk 
I guess it would first require that Metabase had a REST API driver? If yes, then have a look at #4831

**Comment by salsakran** [comment]
As currently scoped, we're not planning on supporting arbitrary 3rd party APIs. We're intended to be used as a tool to visualize data in a database or data warehouse. 

If we expand scope, I will re-open, but realistically, this is not going to be supported for the foreseeable future.

**Comment by ArtGangsta** [comment]
OData is a way for a REST end-point to make the data look more like a database.   If you squint, you can say that JMESPath and GraphQL are similar.

I understand the reason this is closed.   If metabase was focused on Microsoft techology, OData would certainly be supported.  It 's a very good fit for Metabase, such like how OData is the main way of getting database-like data from Excel or PowerBI.   But this is clearly not the Microsoft world, so I understand the rationale to give OData a low-priority, or leave it for a third-party to support.

**Comment by 50shashwat** [comment]
Any update on the plugin for OData Connector ?

**Comment by mmetr** [comment]
This would be great since more database are connecting via odata protocols... This would greatly expand the utility of metabase

**Comment by paolo-arge-lf** [comment]
Agree, OData (v4) would open up a lot of options: Azure Dev Ops, Salesforce, SAP, and many more ...

**Comment by venkatamandavilli-code** [comment]
Thanks for raising this — OData is indeed widely used across ERP systems like Microsoft Dynamics AX, 1C Enterprise, and bpmOnline, and it’s a common integration pattern in enterprise environments. Having native OData support in Metabase would make it much easier to analyze data from these systems without needing an intermediate layer.

Right now, Metabase doesn’t include a built‑in OData driver, and support depends entirely on what can be achieved through third‑party JDBC connectors. The CData OData JDBC driver is one option, but compatibility varies by vendor implementation, and as you’ve seen, it doesn’t always work reliably with systems like 1C.

At this point, native OData support isn’t on the immediate roadmap, but the use case is valid — especially for ERP users who want a simpler analytics path without building custom sync pipelines. If more interest builds around this, it may be worth revisiting.

In the meantime, exploring a workaround (e.g., syncing OData entities into SQL Server or another relational store) is likely the most stable approach, particularly for 1C.

Happy to help review any workaround approach you’re considering.
