### ISSUE TITLE
Can't change database to authenticate on MongoDB

### ISSUE THREAD

**Issue by Guiraiol** [metabase/metabase#11072]
I working on migration to a cluster in MongoDB Atlas. Our users don't have permission to authenticate on "admin", so I need to change the authentication database. 
I tried to change in the option "Authentication Database" and pass by connection string with "authSource", but metabase is always trying to authenticate on admin.

Changing metabase options
![image](https://user-images.githubusercontent.com/22764886/66324866-a76f4280-e8fc-11e9-8a54-c0af03fd9e04.png)

It doesn't affect at all the method of authentication, it always trying to authenticate on admin database
![image](https://user-images.githubusercontent.com/22764886/66325153-22385d80-e8fd-11e9-92ff-b2f10c3db745.png)

As a quick fix, I gave permission to read on admin, but it's not ideal not have the possibility to change where I want to authenticate.

**Comment by Guiraiol** [comment]
The error was not in changing the auth database. The password stored as saved was giving this auth error, so when I save configuration and update the page, just by clicking in save raise the same error.

**Comment by flamber** [comment]
Hi @Guiraiol 
Just to confirm, it was your browser (or an extension/addon) that was auto-filling the username/password with the wrong credentials, which caused the problem for you?
