### ISSUE TITLE
Aggregation dropdown should match dropdown and hover style of field select

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1108]
<img width="424" alt="screen shot 2015-10-05 at 9 20 19 am" src="https://cloud.githubusercontent.com/assets/5248953/10286382/566532b4-6b42-11e5-884a-e0e18bcbffe9.png">
<img width="380" alt="screen shot 2015-10-05 at 9 20 16 am" src="https://cloud.githubusercontent.com/assets/5248953/10286383/5665613a-6b42-11e5-966c-c7f0dff8a154.png">

**Comment by agilliland** [comment]
This was addressed at some point.
