### ISSUE TITLE
Trend/Smart Number does not work when dates are descending

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11089]
**Describe the bug**
When sorting data for Trend (Smart Number) in descending order, then it stops working and just displays the message `Nothing to compare for the previous X.`
This is applicable to QB and SQL.
**Work-around**: Sort by ascending.

@sbelak said in the [forum](https://discourse.metabase.com/t/trend-visualization-aka-smart-number-custom-sql-query/7604):
> It’s not really intended, but rather a side-effect of how we check if you have evenly spaced data (ie. if it makes sense to do a comparison).

**To Reproduce**
1. Go to Custom question. Select Sample Dataset and Orders
2. Summarize Count by CreatedAt:Week
3. Sort CreatedAt:Week descending
4. `Nothing to compare for the previous week.`

**Information about your Metabase Installation:**
- Metabase 0.33.0 and 0.33.4, various browsers.

**Comment by camsaul** [comment]
Fixed by #11658

**Comment by ValdarT** [comment]
Just ran into this. Custom SQL query against Redshift on Metabase v0.42.3. Trend works if there is no `order by` clause but gives "Nothing to compare for the previous ." otherwise (regardless of whether the ordering is `asc` or `desc)`.

**Comment by ValdarT** [comment]
It's actually related to a filter that leaves out every other week. The visual works fine if I remove that filter (just doesn't meet the use case anymore).

**Comment by flamber** [comment]
@ValdarT Sounds like you're looking for #11200/#9510
