### ISSUE TITLE
Multi-line description for questions

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#11091]
Multi-line question descriptions are shown as single line in the tooltip.

<img src="https://user-images.githubusercontent.com/15974735/66433390-19b35600-e9d5-11e9-9f2f-6fa142ea5940.png" width="500" >

<img src="https://user-images.githubusercontent.com/15974735/66433396-1c15b000-e9d5-11e9-8484-bbc89828ac7f.png" width="500" >

MB version: 0.33.3

**Comment by gusaiani** [comment]
@flamber, I think this Tooltip has been removed.
Correct?

**Comment by flamber** [comment]
@gusaiani It's also applicable to dashboards. Perhaps it will be removed there as well, difficult to say. Then close this issue.

**Comment by gusaiani** [comment]
@flamber ah, I am seeing this in more places. Thanks, let me see if it's a quick fix.
