### ISSUE TITLE
Column description in tooltip on hover

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#11092]
Currently (0.33.3) when hovering over column headers, a tooltip is shown only if the whole column name is not visible, and in this case it only contains the column name (implemented in response to issue [#1174](https://github.com/metabase/metabase/issues/1174) )

I suggest one of the following for showing a tooltip containing column name and column description when hovering over column headers (with some delay maybe):
- A tooltip always be shown. 
- A tooltip be shown when either the full column name is not visible (the current version) OR column description is not empty.

The column description is actually very helpful, and makes the users more independent.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by dubravcik** [comment]
Yes, this would be a super useful feature (after the data reference was removed).

I can imagine simple tooltip on a column header or axis name
![metabase - add title description on fields - account country](https://user-images.githubusercontent.com/2481962/72222968-9755a780-356a-11ea-8e95-abbb395b096a.png)
and also in Summarization selector
![metabase - add title description on fields - account country 2 summarize](https://user-images.githubusercontent.com/2481962/72223028-324e8180-356b-11ea-896b-5f8a1ab3839b.png)

**Comment by flamber** [comment]
Implemented in #19350 and several other related PRs
