### ISSUE TITLE
Cannot clear Description from a column in Reference or Data Model

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11097]
**Describe the bug**
It is not possible to clear/empty/remove the Description of table/column in Data Model. Same goes for Description/Interesting/Aware of table in Data Reference, but it is possible to clear those fields for database in Data Reference.
Note that it is possible to add and edit those fields without any errors.

**Logs**
Metabase logs the following error, where the URL might differ depending on field being edited. There's a matching javascript error object logged too.
```
PUT /api/field/81 400 1.1 ms (0 DB calls) 
{:errors {:description "value may be nil, or if non-nil, value must be a non-blank string."}}
```

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Orders _or_ Data Reference > Sample Dataset > Orders
2. Clear the description of table or a column
3. See error in console or log
4. Either the previous content gets restored or the field is empty until browser refresh.

**Information about your Metabase Installation:**
Metabase 0.33.4 on Firefox 69 (reported by several other versions and browsers too)

**Additional context**
Creating this issue, so reports by @vvaezian https://github.com/metabase/metabase/issues/4738#issuecomment-539712811 and @mazameli https://github.com/metabase/metabase/issues/8443#issuecomment-533234614 don't get lost in the comments.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by paoliniluis** [comment]
Same as if you try to save a question (not a dashboard, IDK why) with just an enter, we're not trimming the value of the question description so it returns an error
![image](https://user-images.githubusercontent.com/1711649/156650529-63f7f938-fa0b-43e9-91ef-2b0d14e40f12.png)

**Comment by flamber** [comment]
Still causing the same error on 0.44.2 for field description
```
2022-09-09 13:20:37,664 DEBUG middleware.log :: PUT /api/field/48754 400 5.7 ms (0 DB calls) 
{:errors {:description "value may be nil, or if non-nil, value must be a non-blank string."}}
```

**Comment by WiNloSt** [comment]
I couldn't reproduce this on `master` @ 844c67b651bf64de25227350ea7963e1a847a1c5 anymore, but the problem still persist @ `v0.46.6` tag
