### ISSUE TITLE
Centered pie chart truncate legend

### ISSUE THREAD

**Issue by Olaktal** [metabase/metabase#11102]
Hello community !

**Describe the bug**

Legends are truncated since pie charts are centered. ( the end of legend is replaced by "...")
It is very annoying since our sales team make screenshot to send data to customers and having a truncated legend is not an option.

**Expected behavior**
I don't know if centered pie charts is a good idea. Or maybe these is something to do to avoid truncated legends ?

**Screenshots**

![image](https://user-images.githubusercontent.com/5711131/66473072-d9181300-ea8e-11e9-92f1-8b001d628255.png)

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 69.0.1
- Your operating system:OS X
- Your databases: Redshift
- Metabase version: v0.33.3
- Metabase hosting environment: Jar file
- Metabase internal database: Postgres

**Comment by flamber** [comment]
Hi @Olaktal 
There's an issue open about the justification fixes introduced in 0.33.2 to pie charts.
If you think #10837 covers your issue too, then please close this, but otherwise leave it open.
