### ISSUE TITLE
broken link on documentation

### ISSUE THREAD

**Issue by caleb15** [metabase/metabase#11119]
see https://www.metabase.com/docs/v0.20.0/users-guide/10-metabot.html

The "setting up slack" link https://www.metabase.com/docs/latest/administration-guide/07-setting-up-slack 404's

**Comment by flamber** [comment]
Hi @caleb15 
That's a very old version of the documentation - you're reading `v0.20.0`
Latest version is `v0.33.4` - or `latest` to always show latest version:
https://www.metabase.com/docs/v0.33.4/users-guide/11-metabot.html
https://www.metabase.com/docs/latest/users-guide/11-metabot.html
I doubt there's going to be any fixes to old versions of the documentation.

**Comment by Almenon** [comment]
Oh, good point. Sorry.
