### ISSUE TITLE
Allow custom dates format for Excel exports

### ISSUE THREAD

**Issue by chteuchteu** [metabase/metabase#11114]
Downloading results as an xlsx file exports dates in the ISO format, which is complicated for Excel to recognize.

It would be great to have a ready-to-use cell when downloading an Excel export (with the right datatype, and the according format) - or at list some way to customize the format in which the date is formatted.

We can currently use `DATE_FORMAT` MySQL function to properly format dates in native queries, but this solution isn't suitable for metrics or custom questions.

Manipulating dates is quite hard right now, so we would really benefit from such a feature.

**Comment by flamber** [comment]
Hi @chteuchteu 
This looks similar or related to #10879 or #10803 or #6012 - if you think it might be a duplicate of one of those, then please close this and upvote the other issue :+1:

**Comment by chteuchteu** [comment]
+1, seems to be a duplicate of #10803, let's close this one!

**Comment by jlisyc** [comment]
Metabase 0.36.12
Date format downloaded excel does not respect the date format when chose to show minutes.
For example: for 24 September 2020, with format configuration is D/M/YYYY
, in the downloaded excel shows:
 for a date "with minutes" it change to M/D/YYYY ![image](https://user-images.githubusercontent.com/33416503/114665114-ea358600-9cfc-11eb-80b4-c1329a1a7bd2.png)

, but for date (just day) is ok ![image](https://user-images.githubusercontent.com/33416503/114665014-c83c0380-9cfc-11eb-8879-4e509924c7e5.png)
