### ISSUE TITLE
Allow me to see stale query results

### ISSUE THREAD

**Issue by ConradIrwin** [metabase/metabase#11112]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I run a query, and then continue editing while waiting for the query to load — since v0.33 it has greyed-out the results of the query I ran so to see if it worked I have to run another query.

This is most frustrating because I use that time while waiting for results to continue to refine my query; anything from tidying up the formatting, or tweaking which columns are coming back, to adding another table to a join.

I run the query before I'm 'finished' because I want to get feedback early in case I made a mistake. 

**Describe the solution you'd like**
Instead of overlaying the play button on the results, it could be a warning between the editor and the results: "The query has changed since you ran it, [ RE RUN ]"

**Describe alternatives you've considered**
It could do the same as v0.32, as I don't remember having a problem with that.

**How important is this feature to you?**
It makes me enjoy creating queries in metabase a lot less; but I'd probably continue using it even if you didn't fix this.

**Comment by flamber** [comment]
Hi @ConradIrwin 
Sounds like a duplicate of #10975 - if you agree, then please close this and upvote the other issue.

**Comment by ConradIrwin** [comment]
Agreed, sorry for not finding that.
