### ISSUE TITLE
I would like metabase to have a security advisories page

### ISSUE THREAD

**Issue by adjenks** [metabase/metabase#11110]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like Metabase to have a dedicated security advisories page. Much like Sonatype Nexus:
https://support.sonatype.com/hc/en-us/sections/203012668-Security-Advisories

**Describe alternatives you've considered**
Metabase could just provide a link to it's CVEs hosted on another website and post the most recent security advisories on its github page.

**How important is this feature to you?**
7/10
It would make it easier to convince people to use it.

**Comment by flamber** [comment]
The GitHub security advisory has been used the past few months: https://github.com/metabase/metabase/security/advisories
