### ISSUE TITLE
Obvious warning on out of date metabase documentation pages

### ISSUE THREAD

**Issue by caleb15** [metabase/metabase#11126]
**Is your feature request related to a problem? Please describe.**
Google might have a link to an out-of-date metabase documentation page as the first result. It's easy to miss the small version number at the top and just start reading the guide.

**Describe the solution you'd like**
Next to the version number in bold red it would say that the version is not the latest version.

**Describe alternatives you've considered**
All sorts of alternatives in terms of UI design, as long as the end result is a obvious indicator.
Also I could just read better :roll_eyes: 

**How important is this feature to you?**
Not important, just a minor improvement. Would potentially result in less issues being raised from people reading out-of-date documentation and wondering why it doesn't work.

**Additional context**
https://github.com/metabase/metabase/issues/11119#issuecomment-540886270

**Comment by flamber** [comment]
Closing, since we now have a top-banner on older documentation pages:
![image](https://user-images.githubusercontent.com/1447303/76315629-58796f00-62d9-11ea-957f-7da604681376.png)

**Comment by caleb15** [comment]
Thanks @flamber :)
