### ISSUE TITLE
Improve discoverability of the database switcher dropdown in the data model page

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11127]
https://github.com/metabase/metabase/issues/1521 mentioned that the database dropdown might not be super obviously clickable:

![image](https://user-images.githubusercontent.com/2223916/106831291-83348a80-6644-11eb-841e-a88a6c8e2b3e.png)

**Comment by brunobergher** [comment]
Hasn't _really_ come up in 5+ years, so closing.
