### ISSUE TITLE
Questions break when renaming a schema

### ISSUE THREAD

**Issue by soltanianalytics** [metabase/metabase#11128]
**Describe the bug**
When renaming the schema of a database, previously existing questions break.

**To Reproduce**
1. Connect a data source e.g. DWH
2. Create a question
3. Rename the schema containing the table pertaining to that question
4. Rename the schema in the corresponding connection in Metabase
5. New questions correctly query the renamed schema, but existing question don't update! What's more, even additional changes within the question don't update the schema name. E.g. if I add a grouping, the `GROUP BY` clause will refer to the old schema name, not the new schema name.

**Expected behavior**
The questions should not have static information on the schema name saved but query the database connection for the current schema name.

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 77
- Your operating system: Win 10
- Your databases: Snowflake
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: PostgreSQL

**Severity**
Well, what I assumed to be a trivial exercised invalidated all existing reports and questions. That's pretty severe... Though I could take a backup of the metabase internal database to undo the damage, so at least it's not crippling.

**Comment by soltanianalytics** [comment]
I made a wrong assumption in *Expected behavior*. I'll leave it as is and write what I found out in this comment: Metabase does actually query the database connection for the current schema, but it doesn't update the schema in the metadata database, instead it creates new table entries for each table instead of updating their schema field.

I was able to fix this for me using this query:

```
DELETE FROM metabase_field
WHERE table_id IN (
	SELECT id FROM metabase_table
	WHERE db_id = 2 AND active
	AND NAME LIKE 'REP_%' -- this was specific to my case
)
;
DELETE from PUBLIC.metabase_table
WHERE db_id = 2 AND active
AND NAME LIKE 'REP_%' -- this was specific to my case
;
UPDATE PUBLIC.metabase_table
SET schema = 'ANALYTICS_REP'
WHERE db_id = 2 AND not active
AND NAME LIKE 'REP_%' -- this was specific to my case
```

**Comment by mazameli** [comment]
Were your existing questions SQL queries or GUI queries?

**Comment by soltanianalytics** [comment]
GUI queries, if I remember correctly

**Comment by salsakran** [comment]
closing this as we're not practically going to guess when a schema was renamed vs dropped.
