### ISSUE TITLE
Select widget's search input autofocus causes scrolling

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11132]
When @tlrobinson and I were trying to add a search input to the data model foreign key mapping popover, we noticed that the autofocus prop on the search box caused odd scrolling of the browser, making it scroll up to the top of the page.

This is the popover I'm talking about:

![image](https://user-images.githubusercontent.com/2223916/66770574-d7729480-ee6c-11e9-8b9c-ad997557c579.png)

**Comment by flamber** [comment]
Same for "With search" on http://localhost:3000/_internal/components#select

**Comment by mazameli** [comment]
This will be fixed by the new consolidated Select component.
