### ISSUE TITLE
MongoDB driver should support Delegated Authentication (authSource connection string option)

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1113]
http://docs.mongodb.org/manual/reference/connection-string/#uri.authSource

Or just support a raw connection string?

**Comment by camsaul** [comment]
This should be really easy to support, but as far as I know @iiSeymour is the only person who ever asked for this. @tlrobinson have you ever used this personally?

**Comment by tlrobinson** [comment]
I haven't but I reported this for a friend who needed it

**Comment by camsaul** [comment]
Implemented by #3727, thanks @nickspacek !
