### ISSUE TITLE
MongoDB: Error filtering by ObjectId field with "Is empty" or "Not empty" options

### ISSUE THREAD

**Issue by kimus** [metabase/metabase#11134]
While trying to create a 'Question' filtering by a field that it's an ObjectId with the "Is empty" or "Not empty" options the result it's always the error - "invalid hexadecimal representation of an ObjectId: []"

**Steps to reproduce**
1. Choose any field that it's an ObjectId and choose "Is empty" or "Not empty" option:
<img width="571" alt="Screenshot 2019-10-14 at 19 27 44" src="https://user-images.githubusercontent.com/188404/66774381-5a214100-eeb9-11e9-9320-aade03a5be8f.png">

2. Click "Get Answer" and should get this error:
<img width="702" alt="Screenshot 2019-10-14 at 19 27 50" src="https://user-images.githubusercontent.com/188404/66774392-60afb880-eeb9-11e9-9152-187477c2bac3.png">
.

**Comment by mazameli** [comment]
Are you still experiencing this in version 0.34?

**Comment by kimus** [comment]
@mazameli Yes. Same error.

**Comment by mazameli** [comment]
Okay, thanks for the update, @kimus.

**Comment by pranitskaya** [comment]
Hi! Still having this issue 
![image](https://user-images.githubusercontent.com/39004309/92225213-941d7c00-eeab-11ea-8a75-697b72125b84.png)

**Comment by flamber** [comment]
@pranitskaya Please post "Diagnostic Info" from Admin > Troubleshooting, and your query.
