### ISSUE TITLE
i want to change some words 

### ISSUE THREAD

**Issue by DOVER123** [metabase/metabase#11130]
i want to change some words，then i rewrite the zh.json，but when i rewrite this words

"${ 0 } table":{"msgid_plural":"{0} tables","msgstr":["表格 ${ 0 }\nPluralsssss: ${ 0 } 张表格"]}}, the page
still show 表格 People Plural: People 张表格,how can i change it?

**Comment by paulrosenzweig** [comment]
@DOVER123 we manage translations in a project on POEditor. There you can edit translations and they'll be included in the next release. https://github.com/metabase/metabase#internationalization
