### ISSUE TITLE
Chart X-axis doesn't reflect order changes 

### ISSUE THREAD

**Issue by zolee** [metabase/metabase#11131]
**Describe the bug**
Chart (in my case a stacked bar chart) X-axis doesn't reflect the order changes (ascending/descending) of the used column.

**Logs**
None.

**To Reproduce**
You can use the bundled Sample Dataset to reproduce the issue (screenshots also included).
1. Create a new question from the `Sample Dataset`, `Orders` table.
2. Configure the question like

      - Filter: `Created At previous month` (including this)
      - Summarize: `Sum of Total` by `CretedAt: Week`, `User → Name`
      - Filter: `Sum of Total is greater than 250`
      - Sort: `Created At` Ascending

3. In the visualization configure a Stacked bar chart, and in the data section, set Created At on the X-axis
4. Try to change the Sort from Ascending to Descending (in my case it would be Created At) and you will see that the chart X-axis will be always ordered Ascending.

**Expected behavior**
The X-axis should reflect the ordering changes in the filter configuration.

**Screenshots**
![0_filter_configuration](https://user-images.githubusercontent.com/2125279/66744362-88346000-ee7c-11e9-98db-77c274575e33.png)
![1_filter_result_ascending](https://user-images.githubusercontent.com/2125279/66744364-88346000-ee7c-11e9-951f-f6fbc8e84c1d.png)
![2_stacked_bar_chart](https://user-images.githubusercontent.com/2125279/66744366-88346000-ee7c-11e9-9af1-674021ee9e11.png)
![3_result_descending](https://user-images.githubusercontent.com/2125279/66744367-88ccf680-ee7c-11e9-983f-ff711da31669.png)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 77 / Firefox 69 / Edge 18
- Your operating system: Windows 10 1903
- Your databases: Bundled Sample dataset
- Metabase version: 0.33.4
- Metabase hosting environment: Jar file on Windows 10 1903
- Metabase internal database: H2 (default)

**Severity**
This doesn't prevent us to use the different kind of charts but as ordering is a basic functionality I think it is an essential thing to work.

**Additional context**
None.

**Comment by paulrosenzweig** [comment]
Is your x-axis set to "Ordinal" or "Timeseries" under the "Axes" tab? A timeseries scale will always move from earlier to later, but an ordinal scale will respect the order of the source data.

**Comment by zolee** [comment]
Changing the X-axis scale from `Timeseries` to the proposed `Ordinal` allows to use the actual ordering so it is not a bug rather than a user/configuration problem.

Truth is I tried to look for answers regarding the effect of Timeseries or Ordinal but I have not found any information regarding this that is why I have not tried this option.

Instead of any bugfix could we somehow add some kind of tooltip or simply just give a note in [Visualizing results - Line, bar, and area charts](https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#line-bar-and-area-charts) documentation section?
