### ISSUE TITLE
Cannot connect to MySQL instance without ssl

### ISSUE THREAD

**Issue by blackpill** [metabase/metabase#11138]
Environment:
MySQL version: 5.6.40
+---------------+----------+
| variable_name | value    |
+---------------+----------+
| have_openssl  | DISABLED |
| have_ssl      | DISABLED |
| ssl_ca        |          |
| ssl_capath    |          |
| ssl_cert      |          |
| ssl_cipher    |          |
| ssl_key       |          |
+---------------+----------+
Metabase version: 0.33.4

Problem:
When I tried to add a connection to this instance, I get a message "java.sql.SQLException: Trying to connect with ssl, but ssl not enabled in the server"

I tried to add "useSSL=false" to JDBC parameters, but I got the same error.
However, I can connect to another mysql instance without any JDBC parameters.
Why metabase always connects to this instance using SSL?

**Comment by flamber** [comment]
Hi @blackpill 
Did you upgrade from an earlier version (like 0.31) ?
If yes, then a few people have encountered an issue, where the SSL setting is somehow enabled for the connection.
You need to modify the metadata directly to ensure that `"ssl": false` is defined in the `details` column of the `metabase_database` table.

**Comment by blackpill** [comment]
@flamber , thanks for your reply.
Since the problem occured when I tried to create a new connection, I cannot find the corresponding connection data in the `metabase_database` table.
I upgraded from version 0.32. After upgrading, the old connections worked correctly.
Now, the error only occured for only one MySQL instance. Metabase can connect to the other MySQL instances correctly.

**Comment by flamber** [comment]
@blackpill 
Okay, then I think I completely misunderstood your problem then.

So you're trying to connect to a MySQL 5.6.40 for the first time, and it constantly tries to connect with SSL even though you have no activated SSL on Metabase?
And the other working MySQL connections are using a different version of MySQL?
Check the Metabase log and MySQL log for any further information that could help.

Metabase only officially supports MySQL 5.7+, but I have been able to connect to MySQL 5.6.24 without any issues, so I think it must be a database configuration difference.

There's another issue #9826, which looks very similar to your problem.

**Comment by blackpill** [comment]
The metabase log file 

is attached.

[log.txt](https://github.com/metabase/metabase/files/3732401/default.txt)

**Comment by blackpill** [comment]
My problem is different from the issue #9826.
The instance didn't support SSL, but metabase tried to connect with SSL.
Why did metabase try to connect with SSL?

**Comment by flamber** [comment]
@blackpill 
It is exactly the same problem as #9826 - you are trying to connect to a server without SSL, but Metabase somehow still tries to connect with SSL.
Just see your log: `java.sql.SQLException: Trying to connect with ssl, but ssl not enabled in the server`
I don't know why or what is going on for that to happen. I have not been able to reproduce.

**Comment by blackpill** [comment]
Yes, you are correct. It is the same as #9826.
But his database is MariaDB 10.1.24.
I don't know how he solve the problem finally, maybe use ssl or change database.
Can metabase connect to MySQL without ssl by force? Because I can't change the database setting.

**Comment by flamber** [comment]
@blackpill 
By default Metabase does not connect with SSL, so I don't understand why it tries anyway.
I have not been able to reproduce this issue, so I cannot give you any hints on what to do, but if you don't have any issues connecting with other MySQL versions, then perhaps something goes wrong with the negotiation between Metabase and older versions of MySQL/MariaDB.

You can close this issue and go to #9826 and Subscribe to get updates when anything happens.
