### ISSUE TITLE
First Schema / Table Being Displayed in Saved Custom Question

### ISSUE THREAD

**Issue by orware** [metabase/metabase#11136]
**Describe the bug**
If a user has written a custom query, in some cases it is showing an incorrect association to a table not used in the custom query.

For example:

Custom Question Shows: "Example Database | Example Schema | Example Table" but "Example Table" is not being used anywhere in the custom query.

What makes the issue a little more odd is that I don't see this necessarily happening with all custom queries so I'm not sure why it's doing for this particular custom query (which was written by another user).

**To Reproduce**
Not sure how others would be able to replicate this behavior at the moment.

**Expected behavior**
Probably would prefer things to be like the other custom queries where just the "Example Database" name would be shown.

**Screenshots**
Example Question showing the issue in action (note that the table being shown is not being used anywhere in the query):
![image](https://user-images.githubusercontent.com/931650/66784353-0d287500-ee8f-11e9-831d-f74950bf9605.png)

That looked like it might be the first result so I started creating a new normal question to confirm (so it looks like Metabase decided to use that first table result and associated it with the custom question above):
![image](https://user-images.githubusercontent.com/931650/66784361-11549280-ee8f-11e9-857c-8bcb87129147.png)

Example of a custom question that doesn't have the same issue:
![image](https://user-images.githubusercontent.com/931650/66784498-80ca8200-ee8f-11e9-92d5-d48cc61abcc0.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Chrome
- Windows 10
- Oracle
- Metabase version: 0.33.3
- Metabase hosting environment: JAR on Windows Server 2016
- Metabase internal database: MariaDB 10.2

**Severity**
It's mainly an oddity and a little confusing for the user putting the question together, since he thought he was doing something wrong and didn't know why it was doing this.

**Comment by mazameli** [comment]
Odd. One guess I have is that the original question might have started off as a notebook GUI query, and was then converted to SQL? I haven't encountered this in the wild myself, but I'll keep an eye out for it.

**Comment by flamber** [comment]
I remember seeing this a long time ago, but a lot has changed since and I cannot reproduce.
It was caused by `report_card.table_id` not being set to null for native queries, but this has been fixed, so it always does this on save.
