### ISSUE TITLE
Schema Columns Not Updating

### ISSUE THREAD

**Issue by danielchangsoojones** [metabase/metabase#11135]
I'm running a MongoDB MLab database cluster. It is deployed on Heroku. I have a column called "driverTypes" in a table called "Ride". It shows up in my real database, but it is not showing up in my Metabase table. I have tried resyncing the schema and reloading everything. I have even deleted the entire database and set it up again. It just won't show. I created additional columns in my real database to see if they would show up in my metabase tables. They did not, which means that none of the schema is updating at all. I can not figure out why the schema won't update even when I completely set up a new database connection.

**Comment by flamber** [comment]
Hi @danielchangsoojones 
Which version of Metabase?
Do you see any warnings/errors in the log, when running the sync?

**Comment by flamber** [comment]
@danielchangsoojones Did you find a solution for your problem? If so, could you please share it, so others might learn from it?
