### ISSUE TITLE
Mongo Driver Timezone Issue When Grouping

### ISSUE THREAD

**Issue by JadCham** [metabase/metabase#11149]
**Describe the bug**
I've configure the timezone to be `US/Pacific` in the JVM and when i query without grouping using the custom question builder it works fine but the timezone isn't being considered when using `Group By`. It directly considers it a `UTC` timezone and starts displaying the data in `UTC` time.

**Logs**
Nothing suspicious in the backend logs, not sure if these console logs are relevant : 
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/11646314/66893459-fbd08d00-efa2-11e9-86bc-7ced326aeaa3.png">

**Expected behavior**
The Java `user.timezone` to be respected when grouping.

**Screenshots**
These are the same 17 Rows.

Without Grouping:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/11646314/66893047-063e5700-efa2-11e9-81c3-53a75082db15.png">

With Grouping:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/11646314/66892961-d4c58b80-efa1-11e9-8602-7c3c45dcb2c2.png">

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:69.0) Gecko/20100101 Firefox/69.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.14.133-113.112.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

I can provide more information if needed.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mazameli** [comment]
Version 0.34 includes a lot of timezone fixes (as well as variables in native queries for Mongo!). Have you tried backing up your Metabase app DB and upgrading to see if that resolves this for you?

**Comment by JadCham** [comment]
@mazameli the issue is fixed with 0.34! Thank You!

**Comment by mazameli** [comment]
Nice, glad to hear it!

**Comment by sytuacmdyh** [comment]
In the latest 0.37.7, this problem appears again 😭

**Comment by flamber** [comment]
@sytuacmdyh Can you include steps-to-reproduce and "Diagnostic Info" from Admin > Troubleshooting?

**Comment by sytuacmdyh** [comment]
> @sytuacmdyh Can you include steps-to-reproduce and "Diagnostic Info" from Admin > Troubleshooting?

After a lot of try of `0.37.7`, I rollback to the `0.34.0`, but it looks same. Here are steps-to-reproduce:
![image](https://user-images.githubusercontent.com/13233969/105932585-07f13880-6088-11eb-9469-d87846a26c8b.png)
![image](https://user-images.githubusercontent.com/13233969/105932603-0fb0dd00-6088-11eb-93ca-edfa0f4adbdd.png)

And the Troubleshooting
```
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_20-b26",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_20",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.20-b23",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.11.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.0",
      "date": "2019-12-19",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
Thanks a lot for your reply!

**Comment by flamber** [comment]
Reopening. Reproduced with https://github.com/metabase/metabase-qa

When I start with user.timezone=Asia/Shanghai, then sample orders looks like this:
![image](https://user-images.githubusercontent.com/1447303/105994564-10f20200-60a8-11eb-861b-cfdb6f5b9296.png)
But when grouping by Hour, then it looks like this:
![image](https://user-images.githubusercontent.com/1447303/105994639-2e26d080-60a8-11eb-9405-785354cd0e86.png)

If I start with UTC, then everything matches:
![image](https://user-images.githubusercontent.com/1447303/105994864-7c3bd400-60a8-11eb-8759-92045230f685.png)
![image](https://user-images.githubusercontent.com/1447303/105994884-8362e200-60a8-11eb-9e27-9b3ffbebec87.png)

And I'm also seeing #10767, when trying to "View these Orders"

**Comment by sytuacmdyh** [comment]
any progress?

**Comment by trialsin** [comment]
A possible solution for that problem

https://discourse.metabase.com/t/strange-behavior-in-mongodb-date-attribute-when-grouping-by-month/18297/7?u=trialsin
