### ISSUE TITLE
Update redshift driver to  1.2.36.1060

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#11147]
The latest version of the Redshift driver fixes the server side (on the redshift cluster) memory leak we were experiencing on sync.

https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.36.1060/RedshiftJDBC42-no-awssdk-1.2.36.1060.jar has the latest version.

We should bump this in our next patch release.

**Comment by salsakran** [comment]
for posterity, https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html#download-jdbc-driver has the latest driver.

**Comment by camsaul** [comment]
Fixed by #11181
