### ISSUE TITLE
Need ability to disable Quotations on emails

### ISSUE THREAD

**Issue by dhayner** [metabase/metabase#11155]
Our users would rather not see Quotations at the bottom of the Pulses.  Sending a report every day to the CEO with a quotation like "Data is sexy" doesn't look very professional.

**Describe the solution you'd like**
A simple checkbox in the UI to disable the Quotations from being added to the emails would suffice.

**How important is this feature to you?**
Very.  It tarnishes the product in some folks' eyes, when the outputs have these odd quotes on them.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by iGitScor** [comment]
Exactly, not professional. I think the email pulse could be improved (attach csv file, remove quote, customize icon, custom email content salutations...)

**Comment by kenaniah** [comment]
My org really needs the ability to disable the quotations -- one of our customers that receives pulses directly specifically complained about them being unprofessional.

**Comment by nickhamlin** [comment]
This came up for us today as well, where a pulse containing the Hal Varian "data is sexy" quote was sent to an external partner. We weren't aware of all the possible quotes that might be sent previously and agree that this doesn't convey the level of professionalism that our staff or our partners deserve.

I'd strongly support the removal of these in future releases, or at least adding the ability for users to easily see the full list of quotes that might be sent (or even configure their own). In the meantime, we'll be adding a custom patch to replace these quotes with some that are a better fit.

For future searchers on this issue looking to do something similar or at least see the full list of existing quotes, they appear in https://github.com/metabase/metabase/blob/master/src/metabase/util/quotation.clj, which seems to be pretty straightforward to modify (CC @kenaniah in case this is a helpful workaround in lieu of a PR around configurability).
