### ISSUE TITLE
Feature request: filter by 「in」 query

### ISSUE THREAD

**Issue by yemingfeng** [metabase/metabase#11153]
I want to use **in** query in filter. But I can not find this option
Cloud you help me?

**Comment by yemingfeng** [comment]
![](https://user-gold-cdn.xitu.io/2019/10/17/16dd78ecbe517b31?w=2858&h=1300&f=jpeg&s=165215)

**Comment by flamber** [comment]
@yemingfeng Okay, you would just use "Equal to" or "is" and then separate the IDs with a comma, but there's a bug currently with selecting multiple Entity Keys (Primary Keys).
See #11162 - upvote by clicking :+1: on the first post.
Please close this issue. And in the future, please provide more details in feature requests or use the forum for questions and troubleshooting.

**Comment by yemingfeng** [comment]
Ok. Thanks a lot!
