### ISSUE TITLE
X-axis date formatting settings don't work when scale is "Timeseries"

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11159]
On master, if I go into my column settings on a timeseries chart and try to change the formatting of the date, nothing happens. 

![image](https://user-images.githubusercontent.com/2223916/66967341-8bbf1700-f035-11e9-91a4-d43b35521f5d.png)

If I change the x-axis scale setting from "Timeseries" (the default), to "Ordinal," the settings take effect:

![image](https://user-images.githubusercontent.com/2223916/66967383-a72a2200-f035-11e9-9401-84cac36eb6a1.png)

**Comment by flamber** [comment]
@mazameli Isn't it the same as #11113? Looks like Paul is working on it :rocket:

**Comment by mazameli** [comment]
Ah yes! I had thought there was an existing issue. Thanks again.
