### ISSUE TITLE
Search fails in cyrillic

### ISSUE THREAD

**Issue by citizen-seven** [metabase/metabase#11151]
**Describe the bug**
Search works poorly in cyrillic (russian). I know there saved questions containing a certain word (`Антитоп`, for example). But typing even first 4 letters returns empty search

**To Reproduce**
1. Save a question with name in Cyrillic, for example copy this `Антитоп сотрудников`
2. Try searching the question using search bar by `Антитоп`
3. See empty result

**Expected behavior**
The question found correctly.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
- Your operating system: macOS Catalina 10.15
- Your databases: MySQL
- Metabase version: 0.33.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Annoying and time-consuming

**Comment by citizen-seven** [comment]
Any updates here?

**Comment by citizen-seven** [comment]
@mazameli could you please take a look? The issue stops company from upgrading to latest version

**Comment by flamber** [comment]
Hi @citizen-seven 
I cannot reproduce your issue - I tried creating a question named `Антитоп сотрудников` and searched for `Антитоп`, and I get one result.
You say that it prevents you from upgrading - did it used to work in an earlier versions, which?
![image](https://user-images.githubusercontent.com/1447303/68439327-cf1c2980-018c-11ea-8eb7-6a19d2111648.png)

**Comment by citizen-seven** [comment]
Fixed! There was an issue with Metabase's LC_COLLATE setting! everything works now, thanks
