### ISSUE TITLE
Native Query > Data Reference > Saved Questions > Invisible Text on List

### ISSUE THREAD

**Issue by lindsay-stevens** [metabase/metabase#11150]
**Describe the bug**

Start a Native Query, go to Data Reference, select the Saved Questions. It'll show how many saved questions there are, but the link text is invisible. The links are still clickable, and go to the data reference for those entries.

**Expected behavior**

Maybe the Saved Questions shouldn't be listed at all, since those data can't be queried in a Native Query.

**Screenshots**

![invisible data reference entries](https://user-images.githubusercontent.com/6345269/66897621-18240680-f043-11e9-97a0-17950596aec6.png)

**Information about your Metabase Installation:**

- Your browser and the version: Firefox 69 😎 
- Your operating system: Windows 10
- Your databases: Postgres 10
- Metabase version: 0.33.4
- Metabase hosting environment: CentOS 7 / nginx
- Metabase internal database: Postgres 10

**Severity**
Very low. Just a weird thing.

**Comment by flamber** [comment]
Hi @lindsay-stevens 
I don't think Saved Questions are supposed to be shown at all - #9458.
I'm never changing my Firefox version either :crazy:

**Comment by mazameli** [comment]
This appears to me to be fixed in 0.34.1. I'm not seeing the saved questions "DB" listed in the side panel at all.
