### ISSUE TITLE
Filter Equal with multiple IDs of Entity Key only shows Object Details of single ID

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11162]
**Describe the bug**
When filtering an Entity Key (PK) using "Equal to" and comma separating to select multiple IDs, the result only shows Object Details of a single ID.
Works fine for numbers (like Orders.Quantity).
Also works fine when filtering Foreign Key (FK), but filter selection is different - it's called "Is".

**Logs**
I don't see any logs or console errors. The request params and response includes all the IDs, so this must be some frontend code not doing it's thing.

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Filter by "ID" with "Equal to"
3. Type `5` comma `8` comma `15`, click "Add filter"
4. Only shows Object Details for ID `5`

**Expected behavior**
Show table result with filtered IDs. I would expect similar behavior as filtering Foreign Keys.

**Information about your Metabase Installation:**
Metabase 0.33.4 and `release-33.x` on Firefox 69

**Comment by yemingfeng** [comment]
Thanks your description.
And Could you tell me the fixed time or fixed version? @flamber 
Thanks a lot!

**Comment by flamber** [comment]
@yemingfeng I don't know. As you can see, there's almost 2000 issues open, so please allow some time to verify, test and fix issues.

**Comment by yemingfeng** [comment]
@flamber Okay~ I will keep my patient to wait. And Thank you 😄
