### ISSUE TITLE
We should update iFrameResizer

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11166]
@flamber [mentioned](https://github.com/metabase/metabase/issues/11152#issuecomment-542773955) that there have been some [updates in iFrameResizer](https://github.com/davidjbradshaw/iframe-resizer/blob/master/CHANGELOG.md) that might help fix performance problems for folks using IE 11, like  https://github.com/metabase/metabase/issues/11152.

We're using it here: https://github.com/metabase/metabase/blob/master/resources/frontend_client/app/iframeResizer.js

**Comment by flamber** [comment]
It's also being included as a package: https://github.com/metabase/metabase/blob/master/package.json#L29

There might also be a race-condition, if a question is failing (status 400) - see #11144 - which I don't know would be fixed by an upgrade.

**Comment by rlotun** [comment]
closed as part of https://github.com/metabase/metabase/pull/16929
