### ISSUE TITLE
Can/Should Metabase connect to Metabase Database itself?

### ISSUE THREAD

**Issue by maurociancio** [metabase/metabase#11179]
Hi, I'm running metabase with mysql as database. I want to find all questions that have notifications enabled. I guessed that I can query metabase itself? Should I do this? Is it expected?
Thanks!

**Comment by flamber** [comment]
Hi @maurociancio 
Yes, you can add Metabase's own application database (metadata) to Admin > Databases.
Just note that some data might be sensitive, so you might want to restrict access via Permissions.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
If that answers the question, then please close this issue :+1:

**Comment by maurociancio** [comment]
Thanks

--
Mauro Ciancio

**Comment by maurociancio** [comment]
I've tried it and worked pretty good!
