### ISSUE TITLE
Row chart shows only two rows in Firefox

### ISSUE THREAD

**Issue by kafran** [metabase/metabase#11178]
**Describe the bug**

The row chart shows only two rows in Firefox. Also it is performing worse than Chrome.

![Screenshot from 2019-10-19 09-26-28](https://user-images.githubusercontent.com/1889828/67144941-0d3fc080-f253-11e9-9f67-80ca8087d409.png)

This doesn't happens on Chrome.

Here is the dashboard: http://35.222.44.62/public/dashboard/c0ee9495-52d0-4d45-941b-d1ae98868758

**Comment by flamber** [comment]
Hi @kafran 
Related to #7544 (possibly duplicate). And yes, it seems like a Firefox specific issue.

**Comment by kafran** [comment]
@flamber Yes. It is the same. Thank you.
