### ISSUE TITLE
Base href broken webpack config

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#11171]
One of the changes to bundle fonts broke our option to set a non-root base path.

https://github.com/metabase/metabase/pull/10963#discussion_r336263951

I changed that to root to work around some issue with the webpack config without realizing that it broke this use case. Hopefully there's a better work around.

**Comment by mazameli** [comment]
Bumping this in priority as it's blocking some of our users from being able to upgrade to the latest version.

**Comment by flamber** [comment]
I guess this is the main cause of #11139 and #11148

**Comment by allangomessl** [comment]
this error happens with `png,svg,icon,manifest` too by html_template.html
https://github.com/metabase/metabase/blob/18da2fe56cfb6a2bc510ee6755f558a72c964e52/resources/frontend_client/index_template.html#L9

and `js, css, etc` by webpack inject
https://github.com/metabase/metabase/blob/18da2fe56cfb6a2bc510ee6755f558a72c964e52/resources/frontend_client/index_template.html#L37

**Comment by flamber** [comment]
@allangomessl `{{{bootstrapJS}}}` is not a webpack inject, but a Mustache template tag. If that's also causing problems, then updating this is needed too:
https://github.com/metabase/metabase/blob/458818663170ed4f0996559f5d9e05f489590d46/resources/frontend_client/init.html#L139

**Comment by paulrosenzweig** [comment]
Fixed in #11174
