### ISSUE TITLE
Update the SQL Server JDBC Driver

### ISSUE THREAD

**Issue by kafran** [metabase/metabase#11182]
**Is your feature request related to a problem? Please describe.**

It is not possible to connect to SQL Server through Windows Authentication

**Describe the solution you'd like**

I want to connect to a SQL Server instance using Windows Active Directory Authentication

**Describe alternatives you've considered**

Update the JDBC Driver to the latest stable version (7.4.1) which supports NTLM protocol since 7.3.1: https://github.com/Microsoft/mssql-jdbc/pull/998  

This will make the connection to SQL Server using Windows Authentication pretty simple. Installing and configuring Kerberos will not be needed any more.

**How important is this feature to you?**

This is very important. It is a long-time user's wish.

**Comment by flamber** [comment]
Hi @kafran 
The SQL Server driver has been [updated to 7.4.1](https://github.com/metabase/metabase/blob/master/modules/drivers/sqlserver/project.clj) via PR #11280, which will be part of 0.34.0
I'm not sure if just the driver upgrade is needed (and connection string changes) or if more changes are needed to be done in Metabase for this to work.

**Comment by kafran** [comment]
I think this can be passed via connection string. I will test when 0.34.0 arrives.

**Comment by flamber** [comment]
@kafran 
Did you get to test this yet? Did it work just with a connection string?
If yes, could you provide an example or reference, just for future documentation?

**Comment by kafran** [comment]
@flamber I still haven't tested it. Give me a few more days and I will install it on my desktop to test.

**Comment by kafran** [comment]
I finally could test this. On Metabase 0.34.3 it is possible to connect to Microsoft SQL Server with the updated version of JDBC Driver using these parameters on connection string: `integratedSecurity=true;authenticationScheme=NTLM;domain=your_domain`

Thank you.
