### ISSUE TITLE
Dashboard filters should be pinned on top / sticky on top

### ISSUE THREAD

**Issue by niparis** [metabase/metabase#11187]
**Is your feature request related to a problem? Please describe.**
We’ve implemented a few dashboards on metabase, and noticed an important UX issues for dashboards that have more than a few charts: the filters disappear as soon as you scroll down.

Now clearly that’s not a bug, and that’s the expected behaviour for metabase dashboard.

Two workflows aren’t possible when filters are not visible:

Checking that the correct filter is selected (quite important when presenting)
Exploring data (right now you have to scroll up, change the filter, then scroll down to see changes - not exactly ideal)

**Describe the solution you'd like**
Having a sticky bar with the filters on top (or some other design) would allow these two workflows.
Or designs are fine, what really matters is that the user can always see and interact with the filters

**Describe alternatives you've considered**
N/A
**How important is this feature to you?**
Makes it hard to use metabase for dashboards that don't fit on a single screen, which is quite limiting

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by khan94** [comment]
Hello, do you guys edit the code from the github? There is a tweak you can make, we did it for our project as well, go into the Dashboard.jsx in src/metabase/Dashboard/components/Dashboard.jsx and adjust the widget to be sticky, and add some other css, and see if it works, dont have the exact code atm.

**Comment by TamirisCrepalde** [comment]
Another possibility that seems interesting is the possibility of moving the filters, as we can move the questions themselves. Sometimes a filter refers only to one part of the panel, but it is currently necessary to leave all filters in one spot at the top of the panel.

**Comment by luukhaijes** [comment]
@flamber is it possible to turn this header off?

**Comment by flamber** [comment]
@luukhaijes No, besides creating your own build.

**Comment by luukhaijes** [comment]
Sad.. we have some unusable dashboards now because we have quite a few filters, worsens the UX @flamber

**Comment by flamber** [comment]
@luukhaijes You should either upvote #13821/#12482 or create a new issue, where you include screenshots, so it's possible to understand the context. But it sounds like you should probably split your dashboard into multiple dashboards, since having 20 (or whatever "quite a few" means) filters seems like something that can overwhelm most users: https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html#best-practices
