### ISSUE TITLE
when I create a new dashboard while saving a question, the default folder should be the same folder chosen earlier in the command

### ISSUE THREAD

**Issue by stephrmb** [metabase/metabase#11184]
![Screen Shot 2019-10-21 at 2 45 20 PM](https://user-images.githubusercontent.com/56848859/67245739-91d83d80-f411-11e9-9622-47f05e2e5ff0.png)

when saving a question and clicking "add to dashboard, you select the folder where you want to save the question, then "create a new dashboard", intuitively, the folder you are saving it to is the same as what you've already chosen, but instead it reverts to your overall account default folder and the question is saved there.

**Comment by flamber** [comment]
This was fixed sometime in 0.39 I believe, I cannot reproduce in 0.41.2
