### ISSUE TITLE
Time series filter and granularity widgets at bottom of screen are missing

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11183]
In Simple mode, the user should see two dropdowns at the bottom of the screen when working with a time series result that lets them change the time range as well as the granularity. These widgets were still present in 0.33.0:

![image](https://user-images.githubusercontent.com/2223916/67225102-71938900-f3e7-11e9-94f9-b9819ebb6734.png)

It looks like they first disappeared in 0.33.1:

![image](https://user-images.githubusercontent.com/2223916/67225474-29c13180-f3e8-11e9-9cdb-27feb8a55372.png)

They were still missing in 0.33.3:

![image](https://user-images.githubusercontent.com/2223916/67225202-a8699f00-f3e7-11e9-8bb0-1ead241b315d.png)

They remain missing in master/0.34-snapshot:

![image](https://user-images.githubusercontent.com/2223916/67225543-4b221d80-f3e8-11e9-8b4a-41b3e2f68a9d.png)

**Comment by salsakran** [comment]
This is a pretty major regression. While it's ok that it's a P2 in terms of severity, the fact that it affects everyone using a x-axis rates it a bit higher than most P2s. 

Escalating and putting it in 0.36 (bonus points for tackling it earlier)

**Comment by flamber** [comment]
Related to #5346 and #6583 (though features, not regressions)

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/16478
