### ISSUE TITLE
Can´t use match options on MongoDB native query

### ISSUE THREAD

**Issue by AndreLuizRego** [metabase/metabase#11189]
I can´t figure out how to use wildcards on a native query for MongoDB. Here is the query that I wish to use wildcards with:

[{"$match":{"nome_entidade":"Alto Forno"}},{"$project":{"Ponto_A_456_1":{ "$subtract": [ "$Ponto_A_456_1",860]},"nome_entidade":"$nome_entidade"}},{"$group":{"_id":null,"max":{"$max":"$Ponto_A_456_1"}}},{"$sort":{"_id":1}},{"$project":{"_id":false,"max":true}}]

I need to match "nome.entidade" to all results that contain "Forno" on the string and not just the string itself. In SQL it would be something like "%Forno%".

I tried to use many syntaxes that I´ve found googling, but none of them worked with Metabase.

Is it a Metabase limitation? If not, please advice me on how to achieve the result I need.

I´m using Metabase 0.33.4 and MongoDB 4.0.5.

Thank you!

P.S.: I´m using the native query builder because I need to perform a calculation that I also could't find a way to do it using the custom query UI (no calculated fields for MongoDB)..

**Comment by flamber** [comment]
Hi @AndreLuizRego 
I don't use MongoDB, but doing a quick search seems to indicate the you should use `$regex`:
https://stackoverflow.com/questions/3305561/how-to-query-mongodb-with-like
Have you tried to build the question in the UI and then converting it to Native afterwards?

I don't think Metabase pose any limitation on the Mongo queries, so this question is better suited in a MongoDB forum - or Metabase's forum https://discourse.metabase.com/ - not in the issue tracker.

There's a request for supporting Custom Expressions on MongoDB - #7097 - upvote by clicking :+1: on the first post.

**Comment by AndreLuizRego** [comment]
Hello Flamber,
Yes, I did try to build the question on UI and then use it on Native. When I do that the resulting question doesn't work on Native ("No Results" is showed), what is odd since it returns the proper results on the UI. 
Anyway, thank you for your answer and advice!

**Comment by flamber** [comment]
Just for reference, you found the solution and updated the forum post:
https://discourse.metabase.com/t/native-questions-using-mongodb-solved/7759
Please close this issue :+1:

**Comment by mazameli** [comment]
Looks like the solution was as follows for reference:


`Finally I got to figure out how to write the question (using $regex):`

`[{"$match":{“nome_entidade”:{"$regex" : “alto”, “$options” : “i”}}},{"$project":{“Ponto_A_456_1”:{"$subtract": [ “$Ponto_A_456_1”,860]},“nome_entidade”:"$nome_entidade"}},{"$group":{"_id":null,“max”:{"$max":"$Ponto_A_456_1"}}},{"$sort":{"_id":1}},{"$project":{"_id":false,“max”:true}}]`

`Hope this will help someone else!`

Closing this as solved.
