### ISSUE TITLE
Manual maximum y-axis range not working correctly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11191]
When I enter a maximum for my y-axis, instead of clipping the top of the chart where I've specified that maximum, the y-axis instead expands as high as it needs to in order to display the maximum value in the series.

![image](https://user-images.githubusercontent.com/2223916/67345246-3b413100-f4ef-11e9-8ed9-566646cf1e50.png)

**Comment by flamber** [comment]
@mazameli I'm fairly sure that's a result of PR #10396 - duplicate of issue #10434?

**Comment by mazameli** [comment]
Thanks, yep — my quick searching didn't find 10434.
