### ISSUE TITLE
float number is not correctly displayed (due to float-point rounding error?)

### ISSUE THREAD

**Issue by wxiaoguang** [metabase/metabase#11198]
**Describe the bug**

Pie Chart should display 1 but show 0 instead (caused by 0.999999999 ? )

**Screenshots**

<img width="941" alt="image" src="https://user-images.githubusercontent.com/2114189/67382476-1bc60900-f5c0-11e9-8985-825597c1dccb.png">

**Information about your Metabase Installation:**

- Metabase version: (e.x. 0.33.4)

**Comment by mazameli** [comment]
Hi, @wxiaoguang. I see that you closed this issue. Did you figure out what was going on?

**Comment by wxiaoguang** [comment]
@mazameli Thank you for your attention.

I am sorry and I find the root problem on my side.

The number behind the left chart is "0.6", rounded up to 1.
The number behind the left chart is "0.4", rounded down to 0.

Well, at most, I think this is a flaw of the chart (number) display, it's not smart enough and misleads us.
