### ISSUE TITLE
Cannot use saved questions with JOINS

### ISSUE THREAD

**Issue by operman18** [metabase/metabase#11194]
**Describe the bug**
I have two schemas. When I write a SQL query without a JOIN, I can reuse the results as a saved quetions.
Once I join two tables across 2 differrent schemas. Then I cannot find the question anymore, in the saved questions.

**Expected behavior**
JOINs should be allowed for saved questions

**Information about your Metabase Installation:**
I am using 1.33.4.1. 

**Severity**
I found an hack to work arround this by creating a question without join (question A). 
Then I've built a new quetion (question B) on top of the first one (quesstion A),
Finally, I modified question A to include the join, question A will not be availlable anymore and question B, will be my new data source.

**Comment by operman18** [comment]
I think this is more of a logging issue. There should be a warning when you have ambiguous columns. Those issues break saved questions.

**Comment by flamber** [comment]
Hi @operman18 
There's a note about limitations of Saved Questions with ambiguous columns in the docs, but perhaps it should give more feedback. What would you suggest?
https://www.metabase.com/docs/latest/users-guide/custom-questions.html#picking-your-starting-data

**Comment by operman18** [comment]
@flamber thank you, I think a simple warning when saving a question with ambiguous would be enough. Including more advanced logging like what question might be affected would be a great plus, but it's not necessary.

**Comment by flamber** [comment]
A lot has changed, and the ambiguous column problem has been improved a lot, so problems like this shouldn't occur.
