### ISSUE TITLE
Format fields, how to splice the values of other fields

### ISSUE THREAD

**Issue by dumplingbao** [metabase/metabase#11195]
Format field, link address plus other fields of this table as parameters.

For example, if there is a table with country and city, I need to format the field as a connection, and then splice the country and city fields of this table to form a complete connection. How can I do this?

**Comment by flamber** [comment]
Please only post once: https://discourse.metabase.com/t/format-fields-how-to-splice-the-values-of-other-fields/7747
Please close this issue.
