### ISSUE TITLE
Manual y-axis range doesn't display as expected with logarithmic scale

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11190]
If you set a manual maximum range for a y-axis when using the logarithmic scale, the y-axis tick marks don't match your input. In this case, I've input `100,000` for the max of my y-axis, but `59,874.14` is displayed instead:

![image](https://user-images.githubusercontent.com/2223916/67345322-76dbfb00-f4ef-11e9-944e-90ae3e7eee8b.png)

**Comment by flamber** [comment]
@mazameli Probably caused by PR #10396 - not sure if this is a duplicate of issue #10434, since this involves log scale, but it has all the same characteristics.

**Comment by JesseSDevaney** [comment]
Could not reproduce:


https://github.com/metabase/metabase/assets/22608765/f08e4cee-7a3a-4699-bac9-42655fe79235
