### ISSUE TITLE
Line point tooltip missing data when not Linear Interpolated

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11205]
**Describe the bug**
When setting "Replace missing values with" to not "Linear Interpolated", then line point tooltip is missing data.

**To Reproduce**
1. Custom question - Sample Dataset - Orders
2. Summarize Count and Sum-of-Toal by CreatedAt:Year
3. Viz settings > Display > change "Replace missing values with" to not "Linear Interpolated"
4. Hover the line points and notice the missing data.

**Screenshots**
Replace missing values with: Zero
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/67423711-fcb08280-f591-11e9-85f4-8e5aa92bb461.png)
Replace missing values with: Linear Interpolated
![Screenshot_00001](https://user-images.githubusercontent.com/1447303/67423720-00440980-f592-11e9-88c7-90b582463f15.png)

**Information about your Metabase Installation:**
Metabase 0.33.3, 0.33.4, release-0.33.x on various browsers

**Additional context**
https://discourse.metabase.com/t/visualisation-bug-not-showing-figures/7600

**Comment by mazameli** [comment]
@paulrosenzweig said this should be fixed via https://github.com/metabase/metabase/pull/11143

**Comment by flamber** [comment]
@mazameli Yes, but it's on `master` and that was not merged with `release-0.33.x`, so it's not part of 0.33.5 as far as I can tell. I've just tested my dev `release-0.33.x` (commit bf436b4cfb9f97abe5283cfe069b8503a812712b):
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/68499895-07b91300-0220-11ea-852d-ee439b2578a8.png)

**Comment by mazameli** [comment]
@flamber Yep, we're sorting out why items from master weren't correctly merged into the 0.33.5 release tag. The intent is to include this fix in 0.33.5.
