### ISSUE TITLE
There should be a way to see all questions that have alerts turned on

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11203]
This was mentioned as a question in https://github.com/metabase/metabase/issues/11179. It would be useful if users (maybe only admins?) could access a list somewhere to see all the questions that have alerts enabled, so that they could be cleaned up, or modified to make sure not all alerts run the query to see if they should be fired at the same time. Maybe @maurociancio has other use cases to add?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by maurociancio** [comment]
That is the use case. I want to change every question that has notifications enabled. I want them to stop pinging on slack and sending an email.

**Comment by ipeevski** [comment]
Another use case is slack channel has been renamed/removed and all alerts need to be updated.

**Comment by flamber** [comment]
Another use-case is to be able to find alerts that has been triggered, but not sending anymore, but it seems like the alert is deleted (instead of archived), so that wouldn't be possible until #6647 is fixed.

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/pull/17503 and https://github.com/metabase/metabase/pull/17503
