### ISSUE TITLE
Bar chart resizing animation gets out of sync

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11204]
This is happening on our stats instance, and the pattern seems to be that this happens when switching to a bar chart from another visualization when there is a small enough number of bars that the resizing animation should be happening (rather than the fade out behavior that happens with lots of bars). The behavior is that the bar chart doesn't resize correctly when a sidebar is closed, and then incorrectly expands out when a sidebar is opened.

**Example 1:**

![bar-resize-1](https://user-images.githubusercontent.com/2223916/67418822-6031b480-f580-11e9-8556-0ece7a833e50.gif)

**Example 2:**

![bar-resizing-2](https://user-images.githubusercontent.com/2223916/67418908-8d7e6280-f580-11e9-83c3-4479d2b8a373.gif)

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4, but I remember this being a problem in earlier versions
