### ISSUE TITLE
Editor screen jumps to top when unselecting the columns where list exceeds screen height

### ISSUE THREAD

**Issue by rarup1** [metabase/metabase#11202]
When you attempt to untick unwanted columns from within the editor (below the fold) the screen always defaults back to top of the list where the list is longer than the screen height. This only happens if you are clicking columns near the bottom (that you have to scroll to). This makes unticking columns incredibly hard - especially as the unselect all feature does not work either on primary tables.

**Logs**
Unable to record logs as its a static page..

**To Reproduce**
Using Chrome Browser
1. Go to a large table and enter 'editor'
2. Click on 'columns'
3. Scroll to a column at the bottom (exceeding screen height) and untick
4. It flicks back to the top.

**Expected behavior**
You can unselect without the issues

**Screenshots**

**Information about your Metabase Installation:**
You're on version v0.33.4

- Your browser and the version: (e.x. Chrome 52.1)
- Your operating system: (e.x. OS X 10.15)
- Your databases: (e.x. MySQL)
- Metabase version: (e.x. v0.33.4)
- Metabase hosting environment: (docker …)
- Metabase internal database: Postgres

**Severity**
This makes it incredibly hard for me to use the feature on big data sets. Unticking all works on joined tables but not on the primary table. You can only select all. This would be very useful when you just want to trim down to 10-15 columns.

**Additional context**

**Comment by flamber** [comment]
Hi @rarup1 

This seems to be all browsers, not just Chrome.
A temporary workaround is to set the browser zoom level to 50% or similar, which will allow you to untick more options quickly without the screen jumps. And then revert to 100% when done.

Issue #10460 about making the UX better and with the possibility to deselect all columns. Go and upvote that issue by clicking :+1: on the first post.

**Comment by rarup1** [comment]
@flamber  Thanks for your response. I have tested the bug on Catalina > Safari (Version 13.0.2 ) and the issue does not happen. It also doesn't happen in Internet Explorer (Microsoft Edge 44.17763.771.0). So I wouldn't be able to tell you when / how this got fixed on Safari/IE but it is fixed in the current version. Still unable to untick all which is frustrating.

Which version of Safari are you using?

I will upvote that ticket!

**Comment by flamber** [comment]
@rarup1 I don't use OSX nor Windows. I was just testing with Firefox and Chromium. But specifically Internet Explorer, Edge (non-Chromium version) and Safari are probably the worst browsers to follow web-standards, so they generally behave differently than browsers based on Firefox and Chromium.
