### ISSUE TITLE
Provide a clear error message on QB for case when database connection failed

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1121]
Finish off the designs half done in #1107

**Comment by agilliland** [comment]
@salsakran are we considering this done now that #1245 is done?

**Comment by salsakran** [comment]
Dumb question: which error conditions are we handling? Specifically do we
have a state for "the data warehouse is dead"? That's the only thing I
didn't remember hitting master.

**Comment by agilliland** [comment]
We are covering ...

* server 5xx = server error
* server 5xx + extend time = server timeout
* server 200 + error message = query error
* server 200 + no rows = overly strict query

We don't have a specifically identified condition for something like "database unavailable".  That would end up being covered in the 3rd case above, query error.

I think if that's the specific error condition we want to look out for and handle better then we should rename this issue and be clear that's what needs to be added.

**Comment by salsakran** [comment]
We should break out case 3 for "bad query" and "no db connection".

Eg with
http://discourse.metabase.com/t/connected-to-rds-postgres-cant-run-queries/21
it
would have been useful to get a more detailed error message.

It's going to be pretty annoying to deal with support posts if we don't get
more information than just "query error"

**Comment by camsaul** [comment]
Why are we using 200s for error messages ?
