### ISSUE TITLE
Have static URL for latest .jar file on website

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#11231]
## Context
I am installing Metabase using the `.jar` file on a remote VM. To download the file I'm usign 
```
wget http://downloads.metabase.com/v0.33.4/metabase.jar
```
To know which version to download, I need to go to [the website](http://downloads.metabase.com/v0.33.4/metabase.jar), check what version is the most up-to-date, and edit the URL accordingly.

## Feature request
**Could you please provide a static URL pointing to the most up-to-date `.jar` file** (e.g. `downloads.metabase.com/latest/metabase.jar`)**?**

## How important is this feature to you?
I'm only losing 30 seconds each time I spin up a new instance, or when I want to update current ones. A static URL would enable me to automate this process — and so make the world a (slightly) better place.

**Comment by flamber** [comment]
Sounds like a duplicate of #5252.
A hacky workaround is to check the `version-info.json`, get the top version, and download that:
```
curl -O $(curl -s http://static.metabase.com/version-info.json | sed -nE '3 s%^.*: "([^"]+).*$%https://downloads.metabase.com/\1/metabase.jar%p')
```

**Comment by EBoisseauSierra** [comment]
Happy to close, as it's a duplicate indeed.
Happy to confirm that the workaround works.
