### ISSUE TITLE
Pie Chart with different filter Metric

### ISSUE THREAD

**Issue by Frank-iotex** [metabase/metabase#11248]
Hi there, I have some users from two different channels, some users only have Discord email and the others only have emails. My purpose is that find out the user has either Discord email **OR** email (many of them have none), and visualization by pie/donut chart.

I can't find how to use the filter to make it because it will have no result if I add two filters at the same time. but I solve it with SQL as shown.

now I have a joint bar chart and a table, but neither of them supports the pie chart. I will be very grateful if anyone tells me how to write a correct SQL or where I can learn it. 
Thank you!

**Screenshots**
![image](https://user-images.githubusercontent.com/55771915/67991376-40406780-fbf6-11e9-90c4-e134b878f09a.png)

Joint bar chart and table
![image](https://user-images.githubusercontent.com/55771915/67991104-5699f380-fbf5-11e9-8b51-84ea57ce812f.png)
Can't find how to make it to pie/donut chart
![image](https://user-images.githubusercontent.com/55771915/67991160-7fba8400-fbf5-11e9-863d-fd00af3b1b57.png)
SQL of select two different filter metric
![image](https://user-images.githubusercontent.com/55771915/67991220-ac6e9b80-fbf5-11e9-8aca-60ee06e04c56.png)

**Comment by paulrosenzweig** [comment]
@Frank-iotex thanks for creating this issue. I think the same issue is described here: https://github.com/metabase/metabase/issues/3217

I'll close this issue, but please go 👍the other!
