### ISSUE TITLE
When I quit a page or change a query, the previous query should be killed

### ISSUE THREAD

**Issue by antoine-lizee** [metabase/metabase#11240]
**Is your feature request related to a problem? Please describe.**
We have more and more long-running queries (5-30 minutes), especially for exploration purposes. These never get cancelled properly which means that our database get clogged by variations of the same query being run several times concurrently.

Examples:
- I want to edit a long query before it has finished, to add a detail, I edit the SQL and rerun.
- I want to edit a long query before it has finished, to make it execute faster, I edit the SQL and rerun.
- I realize I'm seeing the wrong table in the QBUI, I go back in my browser.
- etc...

These will prevent other users of metabase to access the database, because it already has tens of long queries running (sometimes by the same user!).

**Describe the solution you'd like**
When I change the query I want to run and run it, the previous running query should be cancelled.
When I close a tab or change the page with a running query, the running query if any should be killed.

**Describe alternatives you've considered**
More general performance tuning of metabase (for instance: allow only N max concurrent queries that run for more than M minutes...). But that's more complicated and this precise sollution both makes sense and would solve most of my problems.

**How important is this feature to you?**
As we are growing, we get more and more "heavy users" of metabase that rely on it to do live explorations and live checks, especially for our operations. I recently had to tell these people to "use less" or "use more carefully" metabase because they caused problems on our infrastructure. These zombie queries have halted our infrastructure twice in the last week for more than an hour each. That much time where our support (they have small, clean, fast running queries supporting them) couldn't help our users!

**Comment by flamber** [comment]
Just for reference. This seems like a broader description than #7849.
