### ISSUE TITLE
test file erros

### ISSUE THREAD

**Issue by kavindyasinthasilva** [metabase/metabase#11258]
*  [expected actual _]
  (when (= expected ::truthy)
    (if actual
      {:type :pass}
      {:type :fail, :expected "A truthy value"})))
**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by mazameli** [comment]
I'm sorry, can you please clarify this issue? I don't understand what's being reported.

**Comment by flamber** [comment]
@mazameli I think you can close this - looks like it's was a PR - #11259
