### ISSUE TITLE
New version timestamp export is not formatted

### ISSUE THREAD

**Issue by dumplingbao** [metabase/metabase#11252]
hi！
The field is a time stamp. After the field is formatted, the page display is normal. The excel export is still a time stamp. If the latest version appears, the previous version does not appear.

**Comment by flamber** [comment]
Hi @dumplingbao 
You provide very little information, but it sounds like a duplicate of #10879 or #10803.
If you agree, then close this issue and upvote the other issue by clicking :+1: on the first post.

**Comment by dumplingbao** [comment]
@flamber  +1, seems to be a duplicate of #10803, let's close this one!
