### ISSUE TITLE
Scale not correct for Charts with more than on value in grouping

### ISSUE THREAD

**Issue by ferarnoled** [metabase/metabase#11257]
**Describe the bug**
Bar chart scale is not correct when you have more than one value in a grouping.

**To Reproduce**
Check this query and select bar chart using the Sample Data set
```
SELECT "PRODUCT_ID"."CATEGORY" AS "CATEGORY", count(*) AS "count", count(distinct "PUBLIC"."ORDERS"."TAX") AS "count_2"
FROM "PUBLIC"."ORDERS"
LEFT JOIN "PUBLIC"."PRODUCTS" "PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCT_ID"."ID"
GROUP BY "PRODUCT_ID"."CATEGORY"
ORDER BY "PRODUCT_ID"."CATEGORY" ASC
```

**Expected behavior**
For the given example the difference with the charts should be of 1/8, not almost the same.

**Screenshots**
See incorrect scale for Bar chart
![1](https://user-images.githubusercontent.com/8064032/68064048-e3b37a00-fcd3-11e9-9fad-cea230ecb1cb.png)
![2](https://user-images.githubusercontent.com/8064032/68064049-e7470100-fcd3-11e9-9beb-b9559fc7f067.png)

Also Area chart
![3](https://user-images.githubusercontent.com/8064032/68064422-83730700-fcd8-11e9-8a81-990a8ba2e1b9.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.14.138-89.102.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-09-20",
      "tag": "v0.33.3",
      "branch": "release-0.33.x",
      "hash": "86d32bf"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}

**Severity**
This type of report is not usable since it gives you inaccurate data. I wouldn't count this as critical though.

**Additional context**
I discovered this using a Custom Query but the same problem applies using SQL query

**Comment by flamber** [comment]
Hi @ferarnoled 
When you have multiple series with very different scales, then Metabase automatically uses split y-axis, which you can disable under Settings > Axes.
Notice the y-axis on both sides. If that solves it, then please close this issue :+1: 
![image](https://user-images.githubusercontent.com/1447303/68437106-94fb5980-0185-11ea-8f15-22feb82eff32.png)
