### ISSUE TITLE
Should we put visualization illustrations next to saved questions in activity feed?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1126]
![activity_icons](https://cloud.githubusercontent.com/assets/2223916/10315076/e897d220-6c0c-11e5-919a-a574c8abbd46.png)

**Comment by mazameli** [comment]
As we're revisiting the design of the saved questions page, I thought I'd bump this issue. We could potentially use the new visualization icons from the saved questions page here on the activity feed, too. I think it might help to break up the activity feed, and to give a cue to users as to what to expect when they click.

**Comment by kdoh** [comment]
Yup! I forgot we actually had an issue for that so thanks for resurfacing. Been playing around with that as part of exploring the new saved question anatomy in other places.

**Comment by MrMauricioLeite** [comment]
+1

**Comment by salsakran** [comment]
@kdoh where did we  land on this?

**Comment by kdoh** [comment]
Think we'll tackle this when we start to propagate the new question item design around the rest of Metabase. I think visualization type is a set thing in the activity feed for sure, and did a quick exploration but I need to spend a bit more time on it to explore if we want to show labels and the other metadata as well.

**Comment by mbvictoria** [comment]
Closing per Slack conversation.
