### ISSUE TITLE
metabase installation error

### ISSUE THREAD

**Issue by jinlan0639** [metabase/metabase#11260]
![image](https://user-images.githubusercontent.com/44486674/68124141-95a7ac00-ff49-11e9-8200-c32292fac63e.png)
 don‘t know how to deal with it...need help

**Comment by TurkerTunali** [comment]
Most probably you have another application which uses 3000 port. You may have another instance of MB or Grafana or something else. You may try access the page http://localhost:3000 on that computer. You may try to change the default port by using this guide https://www.metabase.com/docs/latest/operations-guide/running-the-metabase-jar-file.html .

**Comment by mazameli** [comment]
@jinlan0639, I think @TurkerTunali answered your question pretty much as I would have. Going to close this for now, but if you need more help, please start a discussion on our forum: https://discourse.metabase.com/
