### ISSUE TITLE
No Tables visible when using MongoDB (Atlas)

### ISSUE THREAD

**Issue by gswebspace** [metabase/metabase#11269]
**Describe the bug**
Connected a local (docker based) Metabase setup to a MongoDB Atlas database but after
connecting there are no tables (or collections) shown in the Metabase dashboard.
Metabase image: `metabase/metabase:v0.33.4`
MongoDB Version: `4.0.13`
Connection string format : `mongodb+srv://<redacted>@dummyid-abc123.mongodb.net/test?retryWrites=true&w=majority`

**Logs**
- No Console Logs available
- Server Logs

```
11-06 08:28:45 DEBUG middleware.log :: GET /api/user/current 200 929.5 µs (3 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (96 total active threads) Queries in flight: 0
11-06 08:28:45 DEBUG middleware.log :: GET /api/session/properties 200 2.8 ms (1 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (96 total active threads) Queries in flight: 0
11-06 08:28:46 DEBUG middleware.log :: GET /api/database 200 2.4 ms (3 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (96 total active threads) Queries in flight: 0
11-06 08:28:46 DEBUG middleware.log :: GET /api/database/5/schemas 200 1.4 ms (4 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (96 total active threads) Queries in flight: 0
11-06 08:28:46 DEBUG middleware.log :: GET /api/setting 200 635.0 µs (0 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (96 total active threads) Queries in flight: 0
11-06 08:28:46 DEBUG middleware.log :: GET /api/database/5/metadata 200 2.1 ms (4 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (96 total active threads) Queries in flight: 0

```

**To Reproduce**
1. Go to [MongoDB Atlas](https://cloud.mongodb.com) and setup a M0 account and obtain the connection string in the format mentioned above.
2. Create a dummy collection and add some dummy data
3. Login into Metabase and goto Settings > Admin > Databases > Add database
4. Enter details as follows -
Type : MongoDB
Name : dummydb
Host: dummyid-abc123.mongodb.net
Database Name : cam
Port : 27017
Database username : <redacted>
Database password : <redacted>
Authentication Database : test
Additional mongo connection string options : `retryWrites=true&w=majority`
Use DNS SRV when connecting : Yes
Automatically run queries when doing simple filtering and summarizing : Yes
5. Click Save
6. Goto homepage, scroll down and click on dummydb
7. There will be no data which was created in step2

**Expected behavior**
Expected Metabase to be able to show existing collections once the database was added.

**Screenshots**
![Screenshot from 2019-11-06 14-12-06](https://user-images.githubusercontent.com/13507015/68282313-758a0100-009f-11ea-981e-44808c8e14c5.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "5.0.0-31-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Your browser and the version: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Your operating system: Ubuntu 18.04.3
- Your databases: MongoDB 4.0.13
- Metabase version: v0.33.4
- Metabase hosting environment: Docker version 19.03.3, build a872fc2f86
- Metabase internal database: default

**Severity**
This is a blocker for us. Having no data to view in Metabase is MOST problematic.

**Additional context**
I have been able to use Metabase with MongoDB 3.6, but due to some reason the newer version just doesn't work.

**Comment by flamber** [comment]
Hi @gswebspace 
I don't have Atlas, but it sounds like a duplicate of #10343 - if you agree, then please close this.

**Comment by gswebspace** [comment]
@flamber Yes this is quite similar to #10343. I hope this gets solved soon.
