### ISSUE TITLE
2019-11-03 replaced with null

### ISSUE THREAD

**Issue by raffsalvetti** [metabase/metabase#11261]
**Describe the bug**
when creating native mysql query using date filter widget, the date '2019-11-03' is replaced with null during execution. While this is not a sql or java error, this is not expected.
I mean, literally this particular date behave this way!! I tested many other dates. Even '2020-11-03' is doing great!

OBS: I've added an error to the query to force print the Metabase console stack trace (added DAYS instead of DAY)

**Logs**

-- BROWSER REQUEST DATA --
{"database":3,"type":"native","native":{"template-tags":{"TESTE":{"id":"2fb73e2a-2318-356d-c869-7166443e4d90","name":"TESTE","display_name":"Teste","type":"date"}},"query":"select {{TESTE}} as 'my_date' from dual where {{TESTE}} = DATE_ADD({{TESTE}}, INTERVAL 1 DAYS)"},"parameters":[{"type":"date/single","target":["variable",["template-tag","TESTE"]],"value":"2019-11-03"}]}

-- BROWSER RESPONSE DATA --

{"database_id":3,"started_at":"2019-11-04T13:48:40.182Z","json_query":{"database":3,"type":"native","native":{"template-tags":{"TESTE":{"id":"2fb73e2a-2318-356d-c869-7166443e4d90","name":"TESTE","display_name":"Teste","type":"date"}},"query":"select {{TESTE}} as 'my_date' from dual where {{TESTE}} = DATE_ADD({{TESTE}}, INTERVAL 1 DAYS)"},"parameters":[{"type":"date/single","target":["variable",["template-tag","TESTE"]],"value":"2019-11-03"}],"async?":true,"middleware":{"add-default-userland-constraints?":true,"userland-query?":true},"constraints":{"max-results":10000,"max-results-bare-rows":2000}},"status":"failed","stacktrace":["--> driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:221)","driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:211)","driver.sql_jdbc.execute$execute_query.invokeStatic(execute.clj:285)","driver.sql_jdbc.execute$execute_query.invoke(execute.clj:279)","driver.sql_jdbc$fn__67112.invokeStatic(sql_jdbc.clj:44)","driver.sql_jdbc$fn__67112.invoke(sql_jdbc.clj:43)","query_processor$fn__44449$execute_query__44454$fn__44455.invoke(query_processor.clj:71)","query_processor$fn__44449$execute_query__44454.invoke(query_processor.clj:65)","query_processor.middleware.mbql_to_native$mbql__GT_native$fn__20887.invoke(mbql_to_native.clj:38)","query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__36504.invoke(annotate.clj:541)","query_processor.middleware.annotate$add_column_info$fn__36410.invoke(annotate.clj:485)","query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__37445.invoke(cumulative_aggregations.clj:57)","query_processor.middleware.resolve_joins$resolve_joins$fn__41557.invoke(resolve_joins.clj:184)","query_processor.middleware.limit$limit$fn__38522.invoke(limit.clj:19)","query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__44316.invoke(results_metadata.clj:87)","query_processor.middleware.format_rows$format_rows$fn__38510.invoke(format_rows.clj:26)","query_processor.middleware.add_dimension_projections$add_remapping$fn__34938.invoke(add_dimension_projections.clj:232)","query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__35638.invoke(add_source_metadata.clj:107)","query_processor.middleware.resolve_source_table$resolve_source_tables$fn__41607.invoke(resolve_source_table.clj:46)","query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__35498.invoke(add_row_count_and_status.clj:16)","query_processor.middleware.driver_specific$process_query_in_context$fn__37521.invoke(driver_specific.clj:12)","query_processor.middleware.resolve_driver$resolve_driver$fn__41221.invoke(resolve_driver.clj:22)","query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36835$fn__36836.invoke(bind_effective_timezone.clj:9)","util.date$call_with_effective_timezone.invokeStatic(date.clj:88)","util.date$call_with_effective_timezone.invoke(date.clj:77)","query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36835.invoke(bind_effective_timezone.clj:8)","query_processor.middleware.store$initialize_store$fn__44341$fn__44342.invoke(store.clj:11)","query_processor.store$do_with_store.invokeStatic(store.clj:46)","query_processor.store$do_with_store.invoke(store.clj:40)","query_processor.middleware.store$initialize_store$fn__44341.invoke(store.clj:10)","query_processor.middleware.async$async__GT_sync$fn__20798.invoke(async.clj:23)","query_processor.middleware.async_wait$runnable$fn__36561.invoke(async_wait.clj:89)"],"context":"ad-hoc","error":"(conn=1000) You have an error in your SQL syntax","row_count":0,"running_time":96,"data":{"rows":[],"cols":[]}}

-- METABASE CONSOLE LOG --
11-04 11:48:40 [1mWARN middleware.process-userland-query[0m :: Falha na consulta {:status :failed,
 :class java.lang.Exception,
 :error "(conn=1000) You have an error in your SQL syntax",
 :stacktrace
 ("--> driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:221)"
  "driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:211)"
  "driver.sql_jdbc.execute$execute_query.invokeStatic(execute.clj:285)"
  "driver.sql_jdbc.execute$execute_query.invoke(execute.clj:279)"
  "driver.sql_jdbc$fn__67112.invokeStatic(sql_jdbc.clj:44)"
  "driver.sql_jdbc$fn__67112.invoke(sql_jdbc.clj:43)"
  "query_processor$fn__44449$execute_query__44454$fn__44455.invoke(query_processor.clj:71)"
  "query_processor$fn__44449$execute_query__44454.invoke(query_processor.clj:65)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__20887.invoke(mbql_to_native.clj:38)"
  "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__36504.invoke(annotate.clj:541)"
  "query_processor.middleware.annotate$add_column_info$fn__36410.invoke(annotate.clj:485)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__37445.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__41557.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.limit$limit$fn__38522.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__44316.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__38510.invoke(format_rows.clj:26)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__34938.invoke(add_dimension_projections.clj:232)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__35638.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__41607.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__35498.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__37521.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__41221.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36835$fn__36836.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__36835.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__44341$fn__44342.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__44341.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__20798.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__36561.invoke(async_wait.clj:89)"),
 :query
 {:type "native",
  :native
  {:template-tags {:TESTE {:id "2fb73e2a-2318-356d-c869-7166443e4d90", :name "TESTE", :display_name "Teste", :type "date"}},
   :query "select {{TESTE}} as 'my_date' from dual where {{TESTE}} = DATE_ADD({{TESTE}}, INTERVAL 1 DAYS)"},
  :parameters [{:type "date/single", :target ["variable" ["template-tag" "TESTE"]], :value "2019-11-03"}],
  :async? true,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [-14, -121, 67, -116, 28, 88, -16, 95, -102, 32, -18, 26, 29, 112, 86, -60, -56, -92, -76, -46, -115, -92, -89, 1, 86, -70, -10, -2, 38, -68, -100, 113]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :cause
 {:class java.sql.SQLSyntaxErrorException,
  :error "(conn=1000) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DAYS)' at line 2",
  :cause
  {:class java.sql.SQLException,
   :error
   "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DAYS)' at line 2\nQuery is: -- Metabase:: userID: 1 queryType: native queryHash: f287438c1c58f05f9a20ee1a1d7056c4c8a4b4d28da4a70156baf6fe26bc9c71\nselect NULL as 'my_date' from dual where NULL = DATE_ADD(NULL, INTERVAL 1 DAYS)\njava thread: qp-database-3-threadpool-6"}}}

11-04 11:48:40 [1mDEBUG middleware.log[0m :: POST /api/dataset 200 [ASYNC: completed] 97,2 ms (10 DB calls) Jetty threads: 2/50 (4 idle, 0 queued) (109 total active threads) Queries in flight: 0

**To Reproduce**
1. Go to Metabase main page
2. Click on menu 'ASK A QUESTION'
3. Click on 'NATIVE QUERY'
4. Select 'ANY MYSQL DATABASE'
5. Write this query 'select {{DATE_FIELD}} as 'my_date' from dual where {{DATE_FIELD}} = DATE_ADD({{DATE_FIELD}}, INTERVAL 1 DAYS)'
6. Change the DATE_FIELD type to DATE widget
7. Select the date 2019-11-03 on the date widget 
8. Click on Play to run this query
9. Go to Metabase console
10. Search for the executed native query
11. Search for the replaced date from the filter (you'll see NULL instead)
12. See error

**Expected behavior**
This query should run with the selected date, not NULL

**Information about your Metabase Installation:**
version v0.33.4 Built on 2019-10-07
Windows Server 2016

**Comment by petrusgomes** [comment]
Hi, we're seeing the same issue here in production with postgres and metabase 0.32.8. Any query including 2019-11-03 is returning 0 or similar values.
If the interval includes this day, but don't end with it, everything works as expected.

**Comment by fabianoengler** [comment]
Same issue here in production, any query including 2019-11-03 fails.
metabase v0.33.3 with postgres 11.5.
We also tried with metabase v0.33.4 and the same issue happened.

**Comment by fabianoengler** [comment]
I find very curious that only this specific date, 2019-11-03, is causing issues, all other dates work fine. FWIIW, I can see from @raffsalvetti's log message that his installation is in Portuguese, as well as mine, and that got me thinking: Not sure if it is is related (may be a long shot) but here in Brazil we have been experiencing time skew issues with a lot of servers and services (from food delivery networks to telecoms) because there was a change in the Daylight Saving Time this year: the day in question, 2019-11-03 was supposed to be the day we would advance our clocks 1 hour ahead for the DST, but government decided few months ago that we would not have DST this year.

What's happening is that many servers (including a few of my own, and the metabase instance in question) didn't had their timezone data (ie [tzdata](https://packages.debian.org/sid/tzdata)) updated in time, and last Sunday all those server had their time adjusted automatically, according to the old rules. I just updated the tzdata package on my servers and all of them got the correct time immediately, all my applications are using UTC and the tz info are used for display only, so no harm done.

I read that mysql uses its own tz data table and doesn't get the update from the OS automatically and many ppl had issues with mysql even when updating their OS' tzdata. Postgres oth didn't seem to be affected (I'm using pg with my metabase instances), but still, that got me thinking if this could be related somehow, I though perhaps some cache got an invalid date during the time the tz was incorrect, I tried to truncate my query_cache table, resync all my tables and stored values, but the issue persisted.

I have many panels that have date filters, in all of them and all questions that I filter by date, if I select the specific date `2019-11-03`, I trigger this bug, if I select a date range, the bug is triggered only if `2019-11-03` is the starting or the ending date, but not in the middle. Eg.: `2019-11-02~2019-11-04` works fine, but `2019-11-03~2019-11-04` or `2019-11-02~2019-11-03` does not.

I'm using docker on linux with official images for postgres 11.5 and metabase 0.33.3.

**Comment by JeffersonCN** [comment]
I was facing the same problem on our production environment.

The solution was to set the Metabase server timezone from "America/Sao_Paulo" to UTC.

**Comment by flamber** [comment]
Is anyone still having problem with this after updating `tzdata` or manually in case of MySQL as per https://github.com/metabase/metabase/issues/11261#issuecomment-550542064
I doubt this is anything we can fix in Metabase, so I'm inclined to close this issue if it has been fixed by updating timezone data on the server/database.
