### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by bobzz-zone** [metabase/metabase#11275]
I have a problem with font size , because i want to fit more question in a dash board that displayed on Screen (not a Laptop or PC just for the team to take a look) , the TV might be big but the font being too big

I hope there is an adjustable font size
or can the resized question fit to the frame size and there is not minimum squerae or at least the minimum square is 2x2

**Comment by flamber** [comment]
Hi @bobzz-zone 
Are you talking about Number/Trend visualizations? I guess it would be solved if #5662 was implemented.
You might also be interested in #9615 and #2552. Upvote issues by clicking :+1: on the first post.

**Comment by bobzz-zone** [comment]
Cool i think its the same with grid issue
