### ISSUE TITLE
Custom mapping for other databases

### ISSUE THREAD

**Issue by AndreLuizRego** [metabase/metabase#11276]
Are there any plans to support custom mapping for databases like MongoDB / Postgres? That is indeed necessary for everyone.

Thanks!

**Comment by flamber** [comment]
Hi @AndreLuizRego 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

I'm guessing you're asking about this? https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#remapping-field-values
I don't use MongoDB, but as far as I know it should work with Postgres.

**Comment by AndreLuizRego** [comment]
> Hi @AndreLuizRego
> Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
> 
> I'm guessing you're asking about this? https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#remapping-field-values
> I don't use MongoDB, but as far as I know it should work with Postgres.

Hi Flamber,
Custom remapping does not work with MongoDB. Not sure on Postgres, but probably will not work on JSON fields either.

Regards,

**Comment by flamber** [comment]
@AndreLuizRego 
There's an issue open on MongoDB #7462 - upvote by clicking :+1: on the first post.
And until #708 is implemented, then I don't think other features like remapping will be possible.
Please close this issue :+1:
