### ISSUE TITLE
Fields with the Email metadata type should be selectable for dashboard Category filter widgets

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11274]
If I try to set up a filter to let me pick user email addresses from the `People` table, I can't select the `Email` field because the Email metadata special type doesn't seem to consider it a categorical type. This means you can't currently filter on email addresses unless you switch the type to `Category` manually.

![image](https://user-images.githubusercontent.com/2223916/68337239-ed9ef980-0094-11ea-9a07-55a550ce92de.png)

![image](https://user-images.githubusercontent.com/2223916/68337266-fbed1580-0094-11ea-8cc2-f41c0e7a5112.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by rajdeep26** [comment]
Is there any update on this? Any other way we can filter on email fields?
