### ISSUE TITLE
metabase docker 0.33.5 not correct hash 

### ISSUE THREAD

**Issue by mix5003** [metabase/metabase#11289]
**Describe the bug**
Latest update of metabase fix MySQL JSON bug (issue 9800). but after i updated docker images  bug still not fixed. i found that latest metabase docker images use incorrect metabase.jar (i use sha256sum for compare hash with release page) 

**To Reproduce**
1. install docker 
2. run command `docker run -it  --entrypoint /bin/bash metabase/metabase:v0.33.5 -c "sha256sum /app/metabase.jar"` the result will be
```
bash-5.0# docker run -it  --entrypoint /bin/bash metabase/metabase:v0.33.5 -c "sha256sum /app/metabase.jar"
36db11ba6b1b2c5bae57568c0db9bcd543e946790e4ef1d7cc11536aefe19d89  /app/metabase.jar
```

**Expected behavior**
The release page said hash should be `7f318f1bbbab4723500aac6c719957cad14d342efa5656250114cd93a1e4dc39`

**Comment by flamber** [comment]
Just to confirm, Docker image that is failing:
`Digest: sha256:bf5604fd7b545eb498ff466fc0609e596159c33b3ba5a136499ba5aebcc4bbd6`
This is probably caused by a cache from yesterday, so when the image was generated, then it downloaded the cached file instead of the latest release file.
I noticed it served the wrong download, when getting the JAR file from some locations, but after an hour or so, then it was correct.

Pinging @camsaul @mazameli @salsakran since this needs to get pulled or maybe a version bump.

**Comment by jeremybdk** [comment]
Anyone had luck in fixing this on their own without waiting for a new release? Thanks

**Comment by mix5003** [comment]
@jeremybdk you can create your own images. like this
```bash
docker rmi metabase/metabase:v0.33.5
mkdir tmp-metabase/
cd tmp-metabase/
echo -e "FROM metabase/metabase:v0.33.4\nADD http://downloads.metabase.com/v0.33.5/metabase.jar /app/metabase.jar\nRUN chmod o+r /app/metabase.jar" > Dockerfile
docker build . -t metabase/metabase:v0.33.5
docker run -d -p 3000:3000 --name metabase metabase/metabase:v0.33.5
```

**Comment by mbiberhofer** [comment]
@mix5003 I guess that was not his point. I can only speak for myself but... 4 days to trigger a docker image rebuild is quite "meh".

I just tried building the image naively by simply cloning the repository and running "docker build", but it fails:

```
#21 1518. Compiling metabase.driver.oracle
#21 1521. 11-12 08:45:26 DEBUG plugins.classloader :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@1bb15351
#21 1521. 11-12 08:45:26 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@1bb15351...
#21 1528. Syntax error macroexpanding at (oracle.clj:1:1).
#21 1528. Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:382).
#21 1528. oracle.jdbc.OracleConnection
#21 1528.
#21 1528. Full report at:
#21 1528. /tmp/clojure-7997384500351900699.edn
#21 1529. Compilation failed: Subprocess failed
#21 1529. Error: could not find /app/source/modules/drivers/oracle/target/uberjar/oracle.metabase-driver.jar. Build failed.
```
Dunno if I skipped a necessary step, couldn't find docker build instructions after a quick glance over the docs. (and I can't spare the time to dive into the matter)

**Comment by flamber** [comment]
I think there were some misunderstandings on the seriousness of this. Expect a fix very soon.
A quick hack is to replace the JAR file in the official Docker image - that's a lot faster than building.
Or just downgrade to 0.33.4
```
// host - access the container - replace metabase with your container name
docker exec -it metabase bash
// container - download the correct JAR
wget -O /app/metabase.jar https://downloads.metabase.com/v0.33.5/metabase.jar
// container - verify the JAR sum - https://github.com/metabase/metabase/releases/tag/v0.33.5
sha256sum /app/metabase.jar
// container - quit the container
quit
// host - restart the container - replace metabase with your container name
docker container restart metabase
```

**Comment by jeremybdk** [comment]
Thank you @flamber seems hard to do in our kubernetes setup as it will pull the latest image if a reboot command is issued. 

@camsaul anychance that you could trigger a new release? Thanks so much!

**Comment by flamber** [comment]
@jeremybdk There's work being done right now. A new release (0.33.5.1) is being created. Not done yet, though.
https://github.com/metabase/metabase/releases/tag/v0.33.5.1

**Comment by camsaul** [comment]
@jeremybdk @flamber the release should be up in a few minutes I'm wrapping up the process

**Comment by flamber** [comment]
@camsaul Did a quick test and everything looks correct :+1: Just missing website + docs + version-info.
It was reported that #11137 isn't fixed, but I don't have a GA account to test with.

**Comment by mix5003** [comment]
close issue because it has new docker release
