### ISSUE TITLE
Mongo Query with more than 2 collections

### ISSUE THREAD

**Issue by baoanhvu** [metabase/metabase#11281]
Hi all, I am new to Metabase.
I connected MongoDB with Metabase and then I am trying to build a report but it needs data from 2 collections.
Can anyone tell me the way to do that?
Thank you

**Comment by flamber** [comment]
@baoanhvu Only create questions in the forum:
https://discourse.metabase.com/t/query-between-2-tables-with-mongodb/7915
Please close this issue :+1:
