### ISSUE TITLE
No Results Icon is broken

### ISSUE THREAD

**Issue by floushee** [metabase/metabase#11282]
In previous versions the Icon was loaded from app/assets/img/no_results.svg

Since 0.33.5 it is loaded from ./1e07783e66572fcf1816d1195b38188b.svg

Seems like this file does not exist

**Comment by floushee** [comment]
my bad :)

**Comment by ProgrammerFu** [comment]
Hi , @floushee , how did you solved it? It bother me for a long time.

**Comment by floushee** [comment]
We have an NGINX in front of Metabase running under <host>/metabase

I have added this to NGINX:

`location ~ /metabase/1e07783e66572fcf1816d1195b38188b.svg {
      alias /etc/nginx/static/no_results.svg;
}`

Not elegant, but it works for us :)

**Comment by ProgrammerFu** [comment]
> We have an NGINX in front of Metabase running under /metabase
> 
> I have added this to NGINX:
> 
> `location ~ /metabase/1e07783e66572fcf1816d1195b38188b.svg { alias /etc/nginx/static/no_results.svg; }`
> 
> Not elegant, but it works for us :)

Ths， It solved the problem.

**Comment by ProgrammerFu** [comment]
> We have an NGINX in front of Metabase running under /metabase
> 
> I have added this to NGINX:
> 
> `location ~ /metabase/1e07783e66572fcf1816d1195b38188b.svg { alias /etc/nginx/static/no_results.svg; }`
> 
> Not elegant, but it works for us :)

Thank you. It solved the problem.

**Comment by flamber** [comment]
@floushee Can you re-open this, so it's not forgotten and can get fixed? Nice workaround :wink:

**Comment by mazameli** [comment]
Reproduced this on master.

## Dashboard
![image](https://user-images.githubusercontent.com/2223916/68972575-07c98d80-07a1-11ea-89f8-73dc4dbcf7dc.png)

## Question
![image](https://user-images.githubusercontent.com/2223916/68973450-2892e280-07a3-11ea-8c2d-81885be1d586.png)

**Comment by paulrosenzweig** [comment]
Fixed in #11350
