### ISSUE TITLE
max_allowed_packet is too big when connecting to mysql

### ISSUE THREAD

**Issue by offcocoa** [metabase/metabase#11283]
![17_43_10__11_08_2019](https://user-images.githubusercontent.com/19444728/68466442-65b11f00-024f-11ea-8b4f-9328fec11b01.jpg)
Because max_allowed_packet is too large, cant connect to mysql database

**Comment by flamber** [comment]
Hi @offcocoa 
Without providing more details, it's going to be really difficult to figure out what's going on.
Please post all the details requested when opening an issue.

**Comment by offcocoa** [comment]
Hi @flamber 
Due to the special needs of the business, we need to set max_allowed_packet to 4G, and metabase will  query the max_allowed_packet parameter when creating the Mysql connection. However, it exceeds the maximum value of 32 bit integer type. I suggest that using Long type to store max_allowed_packet.

**Comment by flamber** [comment]
@offcocoa I still don't understand the problem and you're providing close to no details. How do I reproduce your issue? Which versions are you using? ...?

**Comment by offcocoa** [comment]
Hi @flamber 
We are using version 0.33.4，you need to set max_allowed_packet of the mysql database to 4G, and then create a mysql connection in the metabase.

**Comment by flamber** [comment]
@offcocoa 
According to the documentation, the largest packet allowed is 1GB:
https://dev.mysql.com/doc/refman/8.0/en/packet-too-large.html

And I have just tested with MySQL 8 and MariaDB 10.4 with:
```
[mysqld]
max_allowed_packet=4G
```
And after restarting, it's maxing out at 1G (1073741824) - and no problems connecting from Metabase. Testing on 0.33.5 (which will likely be called 0.33.6 tomorrow), which is using an updated driver.

**Comment by offcocoa** [comment]
Hi @flamber 
Sorry, I did not express the relevant information clearly, we can set max_allowed_packet more than 1G, because we use TiDB.

**Comment by flamber** [comment]
@offcocoa And this is exactly the reason why I repeatedly asked for more details.
Metabase does not officially support TiDB (https://github.com/metabase/metabase/issues/10614#issuecomment-522196664), but I guess adding the Connection String should work.

**Comment by offcocoa** [comment]
@flamber 

> EDIT:
> Otherwise you can probably set a much smaller size for the Metabase client connection in (Admin > Databases > db > Connection String):
> `maxAllowedPacket=65535`

This setting is invalid, we lowered the max_allowed_packet configuration to skip this issue, thanks for your suggestion.
