### ISSUE TITLE
Group by Quarter shows incorrect labels on bar graph (Q1 is repeated) in v0.33.4

### ISSUE THREAD

**Issue by errenTulcoLabs** [metabase/metabase#11285]
I am experiencing the exact same issue described in this closed bug 
https://github.com/metabase/metabase/issues/6987

Group by Quarter shows incorrect labels on bar graph, but when you hover over each bar it shows the correct information. Is there a fix or workaround for this issue?

Metabase v0.33.4
AWS EC2 
AWS Redshift 
Datetime field is in UTC 
Chrome Browser 

Thanks for your help!

**Comment by flamber** [comment]
Hi @errenTulcoLabs 
It sounds like a [timezone issue](https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html) - you're most likely seeing #5916, which has been fixed and will be part of the upcoming 0.34.0 release.
I think a workaround is to use Ordinal in the "X-axis scale" under Visualization Settings > Axes.

**Comment by errenTulcoLabs** [comment]
Thanks for the quick response @flamber! That resolved my issue.
