### ISSUE TITLE
Unsquash map icon

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1128]
Right now the map icon in the recents is squashed vertically. 
![screen shot 2015-10-06 at 10 25 41 am](https://cloud.githubusercontent.com/assets/107439/10316539/9477f3d4-6c14-11e5-9f73-a8d278a8969f.png)

We should let freedom stretch out, expand, and generally spread to all available corners. 

'Murika :us:

**Comment by camsaul** [comment]
I don't think this is an issue anymore since we use the map icon instead of the state map these days.

![screen shot 2016-04-27 at 4 57 48 pm](https://cloud.githubusercontent.com/assets/1455846/14871659/312e1210-0c99-11e6-98da-7c41adec2da2.png)
