### ISSUE TITLE
Let field match filters be used as variables in select

### ISSUE THREAD

**Issue by smic-datalabs-aaron** [metabase/metabase#11296]
Hi, I'm making a dashboard which does mean that I need to group by and sum the same table with different group by keys. Instead of creating multiple queries and adding them to the dashboard. It would be much better to just put a variable in the select field. So I can just put the group by that I want and let metabase query.

I saw that the issue here is that it makes it vulnerable to SQL injection attacks however, I'm not sure if you can just make a seperate table and use a field match variable. This way it's not free form so you can only put in values already defined in a table.

Thanks!

**Comment by flamber** [comment]
Hi @smic-datalabs-aaron 
It sounds like a duplicate of #10768 - if you agree, then please close this issue.
Related to #5247 and #6820.
