### ISSUE TITLE
Allow Group By [arbitrary duration] aggregation for timestamps 

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#11299]
**Context**
I am plotting time series — let say "Count of rows". I want to group it by `Timestamp`. I choose to aggregate the time per minute, hour, day, etc.
In my case, I find that the `minute` aggregation is too detailed, and `hour` not enough.

**Describe the solution you'd like**
I would like to be able to aggregate results by `15-minute` slots, or `3.14 day`, or whatever duration I want.

**Describe alternatives you've considered**
Doing some convoluted SQL query. But GUI is much nicer (; 

**How important is this feature to you?**
I would enjoy it quite a bit.

**Comment by flamber** [comment]
Hi @EBoisseauSierra 
Looks like a duplicate of #9542 - if you agree, then please close this and upvote the other issue.

**Comment by EBoisseauSierra** [comment]
I do agree, it's a dup (with the slight difference that it shouldn't limited to _"x minutes"_ aggregations, but potentially _"x days"_, _"x years"_, etc. as well — even if this would of course be possible by multipyling minutes by 60, 24, 365, … <sub>[but what about leap years, etc.]</sub>)

**Comment by flamber** [comment]
@EBoisseauSierra There's other requests for more control/custom binning in general #7782/#9208
