### ISSUE TITLE
Saved Questions Nav bar item should be activated when on that page

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1129]
Right now we don't mark the "Saved Questions" link as active when on that page. We should give the user a reminder of where they are, similar to the admin nav bar.

**Comment by mazameli** [comment]
Tried a few different things, but I think the simplest and best thing for now would be to have the hover state act as the current-page state also. This should be true for Saved Questions and other new sections, and I think the Dashboard link should also have this state when any dashboard is being viewed, for consistency's sake.

**Comment by tlrobinson** [comment]
Should "Questions" be active when on a specific question (`/card/:id` or even the new query page `/q/*`)? i.e. should one of the header buttons always be active?

**Comment by agilliland** [comment]
I feel like that would be a bit strange.  I guess we are creating problem for ourselves in a sense because the only navbar item that realistically represents the QB is the `New Question` button, but that's such a special case.

sigh.

**Comment by mazameli** [comment]
"Questions" used to be "Saved Questions" (unless I'm completely misremembering), and it's really just meant to relate to the list of saved questions, similar to how the Dashboards link (though it's a dropdown… sigh) shows you the list of dashboards. 

So yeah, I don't think Questions should be highlighted except when you're on the Saved Questions page.

**Comment by tlrobinson** [comment]
That makes sense, but then why should the dashboards dropdown be selected when a particular dashboard is selected?

**Comment by agilliland** [comment]
I agree with @mazameli , and IMO the Dashboards nav item is fitting to be highlighted because it's a clearly appropriate context when you are on a Dashboard.  If we didn't have a separate `New Question` button then I'd say that Questions should be highlighted when you are in the QB.
