### ISSUE TITLE
Newly added columns are not visible in when ask question through "Custom question"

### ISSUE THREAD

**Issue by Owais316** [metabase/metabase#11292]
I added three columns in a table, which is visible in "Simple question" and in "Native query" but newly added columns are visible when ask question through "Custom question".

**Comment by flamber** [comment]
Hi @Owais316 
Metabase only sync the database every hour (unless set to something different).
You need to manually sync the database in Admin > Databases.
If that solves your problem, then close this issue :+1: 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by Owais316** [comment]
I have already refreshed/sync database, but reported issue still persist.
Any other suggestion(s).

**Comment by flamber** [comment]
@Owais316 Then please provide all the details as requested when opening an issue. And check the logs/console for any errors.

**Comment by Owais316** [comment]
Issue has been resolved, there was an issue with one of the table structure in same dataset.
Thanks @flamber for your precious time.
