### ISSUE TITLE
when I flush the index page,error  generation

### ISSUE THREAD

**Issue by jsonyin** [metabase/metabase#11290]
the detail log 
GET /api/automagic-dashboards/database/2/candidates 500 4.2 ms (6 DB calls)
{:message
 "(conn=20) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL) AND `active` = TRUE AND (`special_type` in ('type/PK', 'type/FK'))) GROUP ' at line 1",
 :type java.sql.SQLSyntaxErrorException,
 :stacktrace
 ("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)"
  "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
  "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
  "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)"
  "org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)"
  "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
  "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
  "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
  "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
  "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
  "toucan.db$query.invokeStatic(db.clj:285)"
  "toucan.db$query.doInvoke(db.clj:281)"
  "clojure.lang.RestFn.invoke(RestFn.java:410)"
  "--> automagic_dashboards.core$enhance_table_stats.invokeStatic(core.clj:1247)"
  "automagic_dashboards.core$enhance_table_stats.invoke(core.clj:1224)"
  "automagic_dashboards.core$candidate_tables.invokeStatic(core.clj:1286)"
  "automagic_dashboards.core$candidate_tables.invoke(core.clj:1266)"
  "automagic_dashboards.core$candidate_tables.invokeStatic(core.clj:1276)"
  "automagic_dashboards.core$candidate_tables.invoke(core.clj:1266)"
  "api.automagic_dashboards$fn__60347.invokeStatic(automagic_dashboards.clj:63)"
  "api.automagic_dashboards$fn__60347.invoke(automagic_dashboards.clj:60)"
  "middleware.auth$enforce_authentication$fn__47314.invoke(auth.clj:14)"
  "routes$fn__66170$fn__66171.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__47270.invoke(exceptions.clj:104)"
  "middleware.exceptions$catch_api_exceptions$fn__47267.invoke(exceptions.clj:92)"
  "middleware.log$log_api_call$fn__47180$fn__47181.invoke(log.clj:170)"
  "middleware.log$log_api_call$fn__47180.invoke(log.clj:164)"
  "middleware.security$add_security_headers$fn__47231.invoke(security.clj:122)"
  "middleware.json$wrap_json_body$fn__47397.invoke(json.clj:61)"
  "middleware.json$wrap_streamed_json_response$fn__47415.invoke(json.clj:97)"
  "middleware.session$bind_current_user$fn__47529$fn__47530.invoke(session.clj:193)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:176)"
  "middleware.session$do_with_current_user.invoke(session.clj:170)"
  "middleware.session$bind_current_user$fn__47529.invoke(session.clj:192)"
  "middleware.session$wrap_current_user_id$fn__47518.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__47503.invoke(session.clj:123)"
  "middleware.auth$wrap_api_key$fn__47322.invoke(auth.clj:27)"
  "middleware.misc$maybe_set_site_url$fn__47295.invoke(misc.clj:56)"
  "middleware.misc$bind_user_locale$fn__47298.invoke(misc.clj:72)"
  "middleware.misc$add_content_type$fn__47283.invoke(misc.clj:28)"
  "middleware.misc$disable_streaming_buffering$fn__47306.invoke(misc.clj:87)"),
 :sql-exception-chain
 ["SQLSyntaxErrorException:"
  "Message: (conn=20) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL) AND `active` = TRUE AND (`special_type` in ('type/PK', 'type/FK'))) GROUP ' at line 1"
  "SQLState: 42000"
  "Error Code: 1064"]}

what should i do ,i delete all fks,but have no effect

**Comment by flamber** [comment]
Hi @jsonyin 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
I'm not sure what you're trying to do. Can you explain it in more details? And can you provide Diagnostic Info from Admin > Troubleshooting?
