### ISSUE TITLE
Bug? Pulses are ignoring formatting applied elsewhere

### ISSUE THREAD

**Issue by sharedphysics** [metabase/metabase#11301]
**Describe the bug**
There seem to be a two possibly related bugs here:
1. Pulses are ignoring data-model created formatting.
2. Pulses are ignoring chart/visualization types
3. The size of charts has changed and now they are extra tall (but that is covered here: https://github.com/metabase/metabase/issues/1078 ... and the comments there suggest this might all be related?)

Case 1:
Google Adwords tends to store their costs data in local microunits. So to get a real cost, you have to divide the data by 1,000,000. I've done this in the data model (and added the dollar sign prefix) to make my charts human-readable and not heart-attack inducing. 

But when I go to create a pulse, I am still getting the original data brought in, devoid of formatting I've applied.

For example: 
Rule in Admin/Data Model: 
![Screenshot 2019-11-12 15 13 31](https://user-images.githubusercontent.com/5796884/68708463-c0a18980-0561-11ea-9a29-c1984cf64f3e.png)
The chart in regular metabase comes out like this (which is correct):
![Screenshot 2019-11-12 15 14 08](https://user-images.githubusercontent.com/5796884/68708864-8d132f00-0562-11ea-88aa-f85e93ad55b3.png)
Final Output in Pulse:
![Screenshot 2019-11-12 15 13 45](https://user-images.githubusercontent.com/5796884/68708474-c7c89780-0561-11ea-9b65-1f93bd0c7fb3.png)

Case 2:
This is very much related to the above. I have a query that visualizes the data as a smart number:
![Screenshot 2019-11-12 15 14 08](https://user-images.githubusercontent.com/5796884/68708864-8d132f00-0562-11ea-88aa-f85e93ad55b3.png)
... which is what I want the pulse to show. But (it seems since the upgrade from 32.x to 33.x), it comes in as a line graph:
![Screenshot 2019-11-12 15 13 45](https://user-images.githubusercontent.com/5796884/68708915-a5834980-0562-11ea-890a-e3b85bee9f84.png)
Other things that are visualized as bar charts or have different rules around how "0" values are handled come in as line graphs too.

**Information about your Metabase Installation:**
33.2 running on AWS

**Severity**
Depending on the data, it ranges from "annoying" to "stopping me from generating a pulse because the data is all wrong" (from an end-user's or goal-of-visualization perspective).

**Comment by flamber** [comment]
Hi @sharedphysics 
1. This is probably #3735 (aka #9216), since no formatting is applied to pulses.
2. That's #5493.
3. I guess you meant #10781.
You should upvote the issues by clicking :+1: on the first post of each - and if you feel that this covers all your points, then you can close this.

**Comment by sharedphysics** [comment]
Done, thanks! Not sure why I didn't see the first two!
