### ISSUE TITLE
0.33.5 Date/Timestamp Filtering Error

### ISSUE THREAD

**Issue by anandabudi** [metabase/metabase#11306]
**Bug**
Date/Timestamp filtering error with the latest version of Metabase (0.33.5)

**Logs**
I got this error message again when filtering DATE/TIMESTAMP with this version

> No matching signature for operator >= for argument types: DATE, TIMESTAMP. Supported signatures: ANY >= ANY at [2:1761]

Hereby attached the screenshot from the broken card. My temporary solution is to revert back to 0.33.2 version (the latest stable one in our environment at least)

![image](https://user-images.githubusercontent.com/8414151/68725251-68fe2f00-05f0-11ea-9565-1288afa0c8e0.png)

Thanks !

**Comment by flamber** [comment]
Hi @anandabudi 
Please post the Diagnostic Info from Admin > Troubleshooting.

**Comment by anandabudi** [comment]
Hi @flamber, thanks for the reply. Same problem with different version of Metabase. Looks like this bug also happened in the previous version (0.33.4)
