### ISSUE TITLE
Dashboard filters don't work if multiple aggregation levels in question

### ISSUE THREAD

**Issue by shafy** [metabase/metabase#11304]
**Describe the bug**
If there are multiple aggregation levels in question, dashboard filters can't be applied. The same happens if I used joined data. See for example this question:

<img width="957" alt="Screenshot 2019-11-12 at 10 44 32 PM" src="https://user-images.githubusercontent.com/1881676/68717246-26ac0200-059e-11ea-846e-4f9cc334de20.png">

I'm running v0.33.5 on Heroku with BigQuery.

**Comment by flamber** [comment]
Hi @shafy 
Sounds like a duplicate of #11007 - if you agree, then please close this and upvote the other issue.

**Comment by shafy** [comment]
Exactly. Thanks, closing this one.
