### ISSUE TITLE
I need help to show different colour for different state (heat map) in metabase

### ISSUE THREAD

**Issue by SeniorJunior** [metabase/metabase#11307]
Hi can someone help me, I want to display different colour for different state of India in Metabase, but I don't know how to do it, currently I only can display pin map which is not that important for plotting the database, I imported custom map of India map in metabase
<img width="546" alt="Screenshot 2019-11-13 at 11 16 38" src="https://user-images.githubusercontent.com/37260722/68730276-30b61b00-0607-11ea-8bda-0edb6615ba4d.png">
this is my custom map in Metabase

**Comment by flamber** [comment]
Hi @SeniorJunior 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You need to specify the region identifier, when adding the map under Admin. And then your data needs to use the same identifier, which you connect in Visualization Settings.
There's also a request for a real heat map #3206 - upvote by clicking :+1: on the first post.
Please close this issue.
