### ISSUE TITLE
Native Query Editor

### ISSUE THREAD

**Issue by ceyhunkerti** [metabase/metabase#11309]
Native query editor can be improved with;

- Allow multiple tabs
- Use [monaco editor](https://microsoft.github.io/monaco-editor/)
- Allow sorting on header click

**Comment by mazameli** [comment]
I'm going to go ahead and split this issue into three different ones to keep the individual feature requests atomic if that's okay with you, @ceyhunkerti.

**Comment by mazameli** [comment]
Closing this in favor of the individual issues I opened that correspond to each request in the description.
