### ISSUE TITLE
Sign in with Google with several domains support

### ISSUE THREAD

**Issue by luosprz** [metabase/metabase#11300]
I was trying to configure my own Metabase enabling the option for Authentication with Google Sign-in.

Could be possible to support it with more than one domain name? 

Now it is only possible to filter by one domain name in:
```Allow users to sign up on their own if their Google account email address is from:```

Thanks

**Comment by flamber** [comment]
Hi @luosprz 
Sounds like a duplicate of #5218 - if you agree, then please close this and upvote the other issue.
