### ISSUE TITLE
Cant Save question when on custom question (PrestoDB)

### ISSUE THREAD

**Issue by huseinmb** [metabase/metabase#11318]
**Describe the bug**
Unable to save/replace questions when the query has join tables, I tried on native query with the same query and even with multiple join tables from multiple database/catalogs(im using presto), miraculously I could save the question with no issue

**Logs**
Im not sure which log refer to my bug, but I capture this log when I tried saving my questions and it prompts "Saving Failed"

``
Oct 7 16:22:54 metabase02a metabase: 10-07 16:22:54 #033[1mINFO api.card#033[0m :: Card results metadata passed in to API is VALID. Thanks!
Oct 7 16:22:54 metabase02a metabase: 10-07 16:22:54 #033[1mDEBUG async.util#033[0m :: Running metabase.api.card$save_new_card_async_BANG_$fn__47698@5e44eb5c on separate thread...
Oct 7 16:22:54 metabase02a metabase: 10-07 16:22:54 #033[1mERROR async.util#033[0m :: Caught error running metabase.api.card$save_new_card_async_BANG_$fn__47698@5e44eb5c
Oct 7 16:22:54 metabase02a metabase: java.sql.SQLException: (conn=3254) Incorrect string value: '\xE2\x86\x92 id...' for column 'result_metadata' at row 1
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:255)
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:194)
Oct 7 16:22:54 metabase02a metabase: at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:462)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__15487.invoke(jdbc.clj:961)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_do_execute_prepared_return_keys.invokeStatic(jdbc.clj:989)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_do_execute_prepared_return_keys.invoke(jdbc.clj:945)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:1020)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:997)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$simple_insert_many_BANG_$iter__18384__18388$fn__18389$fn__18390.invoke(db.clj:560)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$simple_insert_many_BANG_$iter__18384__18388$fn__18389.invoke(db.clj:558)
Oct 7 16:22:54 metabase02a metabase: at clojure.lang.LazySeq.sval(LazySeq.java:42)
Oct 7 16:22:54 metabase02a metabase: at clojure.lang.LazySeq.seq(LazySeq.java:51)
Oct 7 16:22:54 metabase02a metabase: at clojure.lang.RT.seq(RT.java:535)
Oct 7 16:22:54 metabase02a metabase: at clojure.core$seq__5402.invokeStatic(core.clj:137)
Oct 7 16:22:54 metabase02a metabase: at clojure.core$dorun.invokeStatic(core.clj:3133)
Oct 7 16:22:54 metabase02a metabase: at clojure.core$doall.invokeStatic(core.clj:3148)
Oct 7 16:22:54 metabase02a metabase: at clojure.core$doall.invoke(core.clj:3148)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$simple_insert_many_BANG_.invokeStatic(db.clj:557)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$simple_insert_many_BANG_.invoke(db.clj:543)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$simple_insert_BANG_.invokeStatic(db.clj:590)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$simple_insert_BANG_.invoke(db.clj:579)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$insert_BANG_.invokeStatic(db.clj:607)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$insert_BANG_.invoke(db.clj:594)
Oct 7 16:22:54 metabase02a metabase: at metabase.api.card$save_new_card_async_BANG_$fn__47698$fn__47699.invoke(card.clj:212)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$do_in_transaction$fn__18216.invoke(db.clj:144)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
Oct 7 16:22:54 metabase02a metabase: at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$do_in_transaction.invokeStatic(db.clj:142)
Oct 7 16:22:54 metabase02a metabase: at toucan.db$do_in_transaction.invoke(db.clj:139)
Oct 7 16:22:54 metabase02a metabase: at metabase.api.card$save_new_card_async_BANG_$fn__47698.invoke(card.clj:208)
Oct 7 16:22:54 metabase02a metabase: at clojure.lang.AFn.applyToHelper(AFn.java:152)
Oct 7 16:22:54 metabase02a metabase: at clojure.lang.AFn.applyTo(AFn.java:144)
Oct 7 16:22:54 metabase02a metabase: at clojure.core$apply.invokeStatic(core.clj:665)
Oct 7 16:22:54 metabase02a metabase: at clojure.core$apply.invoke(core.clj:660)
Oct 7 16:22:54 metabase02a metabase: at metabase.async.util$fn__33788$do_on_separate_thread_STAR___33793$fn__33794$fn__33795.invoke(util.clj:71)
Oct 7 16:22:54 metabase02a metabase: at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
Oct 7 16:22:54 metabase02a metabase: at clojure.lang.AFn.call(AFn.java:18)
Oct 7 16:22:54 metabase02a metabase: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Oct 7 16:22:54 metabase02a metabase: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Oct 7 16:22:54 metabase02a metabase: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Oct 7 16:22:54 metabase02a metabase: at java.lang.Thread.run(Thread.java:748)
Oct 7 16:22:54 metabase02a metabase: Caused by: java.sql.SQLException: Incorrect string value: '\xE2\x86\x92 id...' for column 'result_metadata' at row 1
Oct  7 16:22:54 metabase02a metabase: Query is: INSERT INTO report_card (description, collection_position, table_id, result_metadata, database_id, collection_id, query_type, name, creator_id, updated_at, dataset_query, display, visualization_settings, created_at) VALUES (NULL, NULL, 1181, ?, 2, NULL, ?, ?, 2, ?, ?, ?, ?, ?), parameters ['[{"name":"id","display_name":"id","base_type":"type/Integer","special_type":"type/PK","fingerprint":null},{"name":"full_name","display_name":"full_name","base_type":"type/Text","special_type":"type/Name","fingerprint":{"global":{"distinct-count":2742,"nil%":0},"type":{"type/Text":{"percent-json":0,"percent-url":0,"percent-email":0,"average-length":11.507936507936508}}}},{"name":"amount_to_finance","display_name":"amount_to_finance","base_type":"type/BigInteger","special_type":"type/Income","fingerprint":{"global":{"distinct-count":172,"nil%":0},"type":{"type/Number":{"min":1000000,"max":200000000,"avg":6432403.929581529,"sd":2.1475675664085276E7,"q1":1149177.0073424545,"q3":3172185.30335463...
Oct 7 16:22:54 metabase02a metabase: java thread: clojure-agent-send-off-pool-13
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:163)
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:280)
Oct 7 16:22:54 metabase02a metabase: at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:223)
Oct 7 16:22:54 metabase02a metabase: ... 45 more
``

**To Reproduce**
1. Go to custom question
2. join one or few tables
3. click save
4. saving failed

**Expected behavior**
when querying using custom question with joining one or two tables, unable to save the result as a question, however when queries has no joins even on heavy aggregation, Iam able to save the question with no issue.

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-957.12.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Jakarta"
  },
  "metabase-info": {
    "databases": [
      "presto",
      "h2",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.4",
      "date": "2019-10-07",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

- Browser:Chrome Version 78.0.3904.97 (Official Build) (64-bit)
- Your operating system: OS X 10.15.1
- Your databases: PrestoDB (on MariaDB)
- Metabase version: 0.33.4
- Metabase hosting environment: alibaba ECS (CentOS Linux release 7.6.1810)
- Metabase internal database:MySQL

**Severity**
Its really annoying and troublesome as I was championing metabase to my C-levels over looker/qliksense for non-technical users as the new notebook features are able to go head to head with the aforementioned BI tools, now all the business users on my company are in love with metabase yet they are frustrated all the analysis they've done cant be saved.

**Additional context**
I had this bug since metabase 0.33 and I have updated twice hoping it will clear this bug

**Comment by flamber** [comment]
Hi @huseinmb 
I'm almost 100% sure that you are not using `utf8mb4` charset in your MySQL application database.
See #10691 for more information on how to check and change charset. Upvote by clicking :+1: on the issue. If it fixes your problem, then please close this issue.

**Comment by huseinmb** [comment]
Hi @flamber thank you for pointing out the solution, ill work on it and if it fixes the problem ill make sure to upvote and close the issue. thank you so much!

**Comment by huseinmb** [comment]
@flamber It works, you are right the issue is because of the encoding in one of the tables in the application database, many thanks!
