### ISSUE TITLE
Dashboard embed not working in 0.33.5 (Not found)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11315]
**Describe the bug**
Dashboard embed not working in 0.33.5 - just gives a `Not found` error page instead of the preview on 0.33.4
Question embed works.

**Logs**
When trying to embed a Dashboard on 0.33.4, I can see the following log, when previewing:
```
DEBUG middleware.log :: GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjJ9LCJwYXJhbXMiOnt9LCJpYXQiOjE1NzM2NzQyNDMsIl9lbWJlZGRpbmdfcGFyYW1zIjp7fX0.X-Ih2ssOo19U0A3D0Mz74tgUMqqpu2_WDKH-vyyTQbA/dashcard/2/card/11 200 [ASYNC: completed] 153.4 ms (18 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (55 total active threads) Queries in flight: 0
```
But there is no GET request or errors on 0.33.5.

**To Reproduce**
1. Go to dashboard
2. Click share/embed-icon and select "Embed this in an application"
3. Just shows `Not found` page with the fly drawer icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/1447303/68798915-e5a70280-061c-11ea-896e-622881d22f2d.png)

**Information about your Metabase Installation:**
Metabase 0.33.5 (various hosting environments and metadata databases)

**Additional context**
https://discourse.metabase.com/t/undefined-not-found-dashboard/7984

**Comment by mazameli** [comment]
Reproduced the following:
- Dashboard app embedding previews aren't loading
- Question app embed previews _are_ loading

I need to fire up an embedding app and see if dashboard embeds are still correctly loading, but one clue is that the embedding example code in the modal has `/embed/undefined` in it instead of `/embed/dashboard`.

**Comment by flamber** [comment]
@mazameli Need to change the `resource: { undefined: 2 },` too, since it generates a wrong token.
But yes, looks like it's just the preview/example code. I don't have any embed on 0.33.5 yet.

**Comment by prophecyOne** [comment]
@flamber is this issue resolved ? i would like to use metabase embedding for my website.
If not for now can you suggest a work around on how to implement embedding untill this issue is solved ?

**Comment by flamber** [comment]
@prophecyOne No, the issue is still open. You can still embed, but you need to modify the example code to get it to work, since the examples will create a wrong token. Or you can downgrade to 0.33.4
