### ISSUE TITLE
Metabase fails to load behind reverse proxy

### ISSUE THREAD

**Issue by excentrik** [metabase/metabase#11317]
**Describe the bug**
Trying to set up Metabase behind a reverse proxy using proxypass fails.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

1) Create a folder with two files

`docker-compose.yml`
```
version: '3'
services:
    nginx:
        image: nginx:stable
        ports:
            - 8080:8080
        volumes:
            - "./nginx.conf:/etc/nginx/conf.d/default.conf"

    metabase:
        image: metabase/metabase:v0.33.5.1
        ports:
            - "3000:3000"
        environment:
            - MB_SITE_URL=http://localhost:8080/metabase/
```

`nginx.conf`

```
server {
    listen 8080 default;

    access_log /dev/stdout;

    error_log /dev/stderr;
 
    location /metabase/ {
        proxy_pass http://metabase:3000;
    }
}
```

2) Run `docker-compose up`

3) Wait for metabase to load

4) Go to http://localhost:8080/metabase/

4) Page fails to load with console errors:
```
Warning: the Metabase site URL basename "/metabase/" does not match the actual basename "/".
You probably want to update the Site URL setting to "http://localhost:8080/"
GET http://localhost:8080/app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3 net::ERR_ABORTED 404 (Not Found)
Refused to apply style from 'http://localhost:8080/metabase/app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
GET http://localhost:8080/app/dist/styles.bundle.js?3f1abe1edb553ce0ef99 net::ERR_ABORTED 404 (Not Found)
Refused to apply style from 'http://localhost:8080/metabase/app/dist/styles.bundle.css?032cae4fcf446d242289184f59918c57' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from 'http://localhost:8080/metabase/app/dist/app-main.bundle.css?e0ccfaeaa5f9f7bc28e85a7454277643' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
GET http://localhost:8080/app/assets/img/favicon.ico 404 (Not Found)
GET http://localhost:8080/app/assets/img/site.webmanifest 404 (Not Found)
GET http://localhost:8080/app/assets/img/favicon-32x32.png 404 (Not Found)
GET http://localhost:8080/app/assets/img/favicon-16x16.png 404 (Not Found)
```

Docker-compose log:

```
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:51 +0000] "GET /metabase/ HTTP/1.1" 200 5250 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /metabase/app/dist/vendor.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 200 5256 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/vendor.bundle.css" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/styles.bundle.css" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/styles.bundle.css?032cae4fcf446d242289184f59918c57 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/styles.bundle.css?032cae4fcf446d242289184f59918c57 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/app-main.bundle.css?e0ccfaeaa5f9f7bc28e85a7454277643 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/vendor.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/app-main.bundle.css" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/app-main.bundle.css?e0ccfaeaa5f9f7bc28e85a7454277643 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/vendor.bundle.js" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/vendor.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/styles.bundle.js" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/styles.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/styles.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /metabase/app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3 HTTP/1.1" 200 3062 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/app-main.bundle.js" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
metabase_1  | 11-14 12:38:52 INFO middleware.exceptions :: Request canceled before finishing.
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /metabase/app/dist/styles.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 200 5262 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /metabase/app/dist/styles.bundle.css?032cae4fcf446d242289184f59918c57 HTTP/1.1" 200 5259 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /metabase/app/dist/app-main.bundle.css?e0ccfaeaa5f9f7bc28e85a7454277643 HTTP/1.1" 200 3062 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /metabase/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 200 5260 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /app/assets/img/favicon.ico HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /app/assets/img/site.webmanifest HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 2019/11/14 12:38:53 [error] 6#6: *14 open() "/etc/nginx/html/app/assets/img/favicon.ico" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/assets/img/favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 2019/11/14 12:38:53 [error] 6#6: *16 open() "/etc/nginx/html/app/assets/img/site.webmanifest" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/assets/img/site.webmanifest HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 2019/11/14 12:38:53 [error] 6#6: *14 open() "/etc/nginx/html/app/assets/img/favicon-32x32.png" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/assets/img/favicon-32x32.png HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 2019/11/14 12:38:53 [error] 6#6: *14 open() "/etc/nginx/html/app/assets/img/favicon-16x16.png" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/assets/img/favicon-16x16.png HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /app/assets/img/favicon-32x32.png HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /app/assets/img/favicon-16x16.png HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
```

**Expected behavior**
It should open metabase setup page correctly.

**Information about your Metabase Installation:**

- Metabase version: Tried 0.32.3/0.33.3/0.33.5/0.33.5.1
- Metabase hosting environment: Docker

**Severity**
This pretty much blocks us from using Metabase at our company.

**Additional context**
I've browsed through other issues, namely:
* https://github.com/metabase/metabase/issues/10657
  * Version 0.32.3 failed in the same manner
* https://github.com/metabase/metabase/issues/2090
  * Tried different nginx settings and `MB_SITE_URL`, none of it worked
* https://github.com/metabase/metabase/issues/11171

As additional test, I tried to set up a redirect rule that would fix the issue of requests not including the base `/metabase/`, which worked to redirect to the container, but the requests always return the main metabase app script, not the proper assets.

**Comment by excentrik** [comment]
Going to close this since the issue disappears by changing the `nginx.conf` configuration to:
```
server {
    listen 8080 default;

    access_log /dev/stdout;

    error_log /dev/stderr;
 
    location /metabase/ {
        proxy_pass http://metabase:3000/;
    }
}
```
(notice the extra slash at the end of the proxy pass directive)

**Comment by ZerNox** [comment]
> **Describe the bug**
> Trying to set up Metabase behind a reverse proxy using proxypass fails.
> 
> **Logs**
> Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Create a folder with two files
> 
> `docker-compose.yml`
> 
> ```
> version: '3'
> services:
>     nginx:
>         image: nginx:stable
>         ports:
>             - 8080:8080
>         volumes:
>             - "./nginx.conf:/etc/nginx/conf.d/default.conf"
> 
>     metabase:
>         image: metabase/metabase:v0.33.5.1
>         ports:
>             - "3000:3000"
>         environment:
>             - MB_SITE_URL=http://localhost:8080/metabase/
> ```
> 
> `nginx.conf`
> 
> ```
> server {
>     listen 8080 default;
> 
>     access_log /dev/stdout;
> 
>     error_log /dev/stderr;
>  
>     location /metabase/ {
>         proxy_pass http://metabase:3000;
>     }
> }
> ```
> 
> 1. Run `docker-compose up`
> 2. Wait for metabase to load
> 3. Go to http://localhost:8080/metabase/
> 4. Page fails to load with console errors:
> 
> ```
> Warning: the Metabase site URL basename "/metabase/" does not match the actual basename "/".
> You probably want to update the Site URL setting to "http://localhost:8080/"
> GET http://localhost:8080/app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3 net::ERR_ABORTED 404 (Not Found)
> Refused to apply style from 'http://localhost:8080/metabase/app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
> GET http://localhost:8080/app/dist/styles.bundle.js?3f1abe1edb553ce0ef99 net::ERR_ABORTED 404 (Not Found)
> Refused to apply style from 'http://localhost:8080/metabase/app/dist/styles.bundle.css?032cae4fcf446d242289184f59918c57' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
> Refused to apply style from 'http://localhost:8080/metabase/app/dist/app-main.bundle.css?e0ccfaeaa5f9f7bc28e85a7454277643' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
> GET http://localhost:8080/app/assets/img/favicon.ico 404 (Not Found)
> GET http://localhost:8080/app/assets/img/site.webmanifest 404 (Not Found)
> GET http://localhost:8080/app/assets/img/favicon-32x32.png 404 (Not Found)
> GET http://localhost:8080/app/assets/img/favicon-16x16.png 404 (Not Found)
> ```
> 
> Docker-compose log:
> 
> ```
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:51 +0000] "GET /metabase/ HTTP/1.1" 200 5250 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /metabase/app/dist/vendor.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 200 5256 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/vendor.bundle.css" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/styles.bundle.css" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/styles.bundle.css?032cae4fcf446d242289184f59918c57 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/styles.bundle.css?032cae4fcf446d242289184f59918c57 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/app-main.bundle.css?e0ccfaeaa5f9f7bc28e85a7454277643 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/vendor.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/app-main.bundle.css" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/app-main.bundle.css?e0ccfaeaa5f9f7bc28e85a7454277643 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/vendor.bundle.js" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/vendor.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/styles.bundle.js" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/styles.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/styles.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /metabase/app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3 HTTP/1.1" 200 3062 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 2019/11/14 12:38:52 [error] 6#6: *9 open() "/etc/nginx/html/app/dist/app-main.bundle.js" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> metabase_1  | 11-14 12:38:52 INFO middleware.exceptions :: Request canceled before finishing.
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /metabase/app/dist/styles.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 200 5262 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:52 +0000] "GET /metabase/app/dist/styles.bundle.css?032cae4fcf446d242289184f59918c57 HTTP/1.1" 200 5259 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /metabase/app/dist/app-main.bundle.css?e0ccfaeaa5f9f7bc28e85a7454277643 HTTP/1.1" 200 3062 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /metabase/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99 HTTP/1.1" 200 5260 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /app/assets/img/favicon.ico HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /app/assets/img/site.webmanifest HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 2019/11/14 12:38:53 [error] 6#6: *14 open() "/etc/nginx/html/app/assets/img/favicon.ico" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/assets/img/favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 2019/11/14 12:38:53 [error] 6#6: *16 open() "/etc/nginx/html/app/assets/img/site.webmanifest" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/assets/img/site.webmanifest HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 2019/11/14 12:38:53 [error] 6#6: *14 open() "/etc/nginx/html/app/assets/img/favicon-32x32.png" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/assets/img/favicon-32x32.png HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 2019/11/14 12:38:53 [error] 6#6: *14 open() "/etc/nginx/html/app/assets/img/favicon-16x16.png" failed (2: No such file or directory), client: 172.24.0.1, server: , request: "GET /app/assets/img/favicon-16x16.png HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/metabase/"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /app/assets/img/favicon-32x32.png HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> nginx_1     | 172.24.0.1 - - [14/Nov/2019:12:38:53 +0000] "GET /app/assets/img/favicon-16x16.png HTTP/1.1" 404 555 "http://localhost:8080/metabase/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
> ```
> 
> **Expected behavior**
> It should open metabase setup page correctly.
> 
> **Information about your Metabase Installation:**
> 
> * Metabase version: Tried 0.32.3/0.33.3/0.33.5/0.33.5.1
> * Metabase hosting environment: Docker
> 
> **Severity**
> This pretty much blocks us from using Metabase at our company.
> 
> **Additional context**
> I've browsed through other issues, namely:
> 
> * #10657
>   
>   * Version 0.32.3 failed in the same manner
> * #2090
>   
>   * Tried different nginx settings and `MB_SITE_URL`, none of it worked
> * #11171
> 
> As additional test, I tried to set up a redirect rule that would fix the issue of requests not including the base `/metabase/`, which worked to redirect to the container, but the requests always return the main metabase app script, not the proper assets.

The nginx  and metabase config seems to be a pain with working examples did you manage to get a working, config and are you willing to share it?

**Comment by excentrik** [comment]
@ZerNox The config I posted in the first post with the extra slash shown in https://github.com/metabase/metabase/issues/11317#issuecomment-553893632 seems to work.
But I haven't touched this in a while now.
