### ISSUE TITLE
Custom question, native query with json in Analytics

### ISSUE THREAD

**Issue by coutinhomoreno** [metabase/metabase#11312]
I need to split the Metric Duration session or convert to date, to help me?
{
  "ids": "ga:---------",
  "start-date": "30daysAgo",
  "end-date": "today",
  **"metrics": "ga:sessionDuration",**
  "dimensions": "ga:yearMonth",
  "sort": "ga:yearMonth",
  "include-empty-rows": false,
  "max-results": 10000
},
example:

**ga:sessionDuration / 60**

**how can i use?**

**Comment by flamber** [comment]
Hi @coutinhomoreno 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You might want to search/ask in a GA specific forum first.
And please close this issue :+1:
