### ISSUE TITLE
Adding question to Dashboard takes 1-2 minutes

### ISSUE THREAD

**Issue by adriank-convoy** [metabase/metabase#11316]
**Describe the bug**

After clicking the '+' button to add a question to a dashboard, users are unable to actually select a question for 1-2 minutes when Metabase instance has a large number of cards. The problem appears to be the call to the `card` API with `filter=all`, which loads metadata for every card in Metabase. We have approximately 38,000 questions, so this call usually takes 1-2 minutes, and ends up returning ~40MB of data.

**Logs**

There's no actual error, so no relevant logs

**To Reproduce**
1. Create 30,000+ cards
2. Create a new dashboard
3. Click '+' to add a new question
4. Try to add a question

**Expected behavior**
You're able to select a question in a reasonable amount of time

**Screenshots**
![image](https://user-images.githubusercontent.com/40185566/68809060-ec834480-061f-11ea-893b-1f2a9fd7cc1f.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 76.0.3809.132
- Your operating system: OS X 
- Your databases: Snowflake
- Metabase version: v0.31.2
- Metabase hosting environment: ECS
- Metabase internal database:  Postgres

**Severity**
Getting a lot of user complaint that creating/maintaining dashboards is very frustrating

**Comment by flamber** [comment]
Hi @adriank-convoy 
That's a lot of questions! Related to #5504 and #10163.

I'm not sure if it would work as a workaround - but perhaps blocking (or returning empty) the request and force the users to use the search to find questions?
Or perhaps make a rewrite, so `all` as changed to `mine` or `recent`. See more in the [API docs](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apicard).

There's a lot of changes in the newer releases (latest 0.33.5.1), where things are loaded async, so it's not blocking the interface. I'm not sure if it also includes your specific case.

**Comment by mazameli** [comment]
Hey, Adrian! 👋 Have you guys had a chance to try upgrading to 0.34? As @flamber mentioned, there might be some async loading changes we've made since version 0.31.2 that could potentially ameliorate these slowdowns for you.

Having to wait 1–2 minutes to be able to select a question to add to a dashboard isn't acceptable, so I'm raising this to a P1 until we can verify if this is still a problem in 0.34.

**Comment by adriank-convoy** [comment]
Heyo,

We actually just upgraded to 0.34.1 today, and unfortunately the issue is still there. The questions load, but when I click on one nothing happens until the `card?f=all` call completes. However, I did notice an error in the developer tool's console every time I click a question that I might have missed when I first reported the bug. It looks like adding a card to a dashboard needs to pull something from the results returned by the `card?f=all` call, which fails until the call is complete

```
Uncaught TypeError: Cannot read property 'id' of undefined
    at app-main.bundle.js?f44db61c4ead99c0a757:5
    at app-main.bundle.js?f44db61c4ead99c0a757:5
    at Object.addCardToDashboard (vendor.bundle.js?f44db61c4ead99c0a757:1)
    at r.onAdd (app-main.bundle.js?f44db61c4ead99c0a757:5)
    at onChange (app-main.bundle.js?f44db61c4ead99c0a757:5)
    at S.u.default.createElement.onClick (app-main.bundle.js?f44db61c4ead99c0a757:5)
    at Object.i (vendor.bundle.js?f44db61c4ead99c0a757:1)
    at s (vendor.bundle.js?f44db61c4ead99c0a757:1)
    at Object.executeDispatchesInOrder (vendor.bundle.js?f44db61c4ead99c0a757:1)
    at d (vendor.bundle.js?f44db61c4ead99c0a757:1)
```

**Comment by Tadimsky** [comment]
This has made such an improvement to usability - thank you!!
I was waiting 2 minutes each time I wanted to add a question and that's now gone.
