### ISSUE TITLE
Cannot click back on Trend/Number visualization Settings

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11320]
**Describe the bug**
When selecting Trend/Number visualization, the title back-button to return to viz selection does not work. It works for all other viz types.
Workaround: Just click the Visualization-button in bottom left to show visualization selection.

**Logs**
I don't see any JS error/warning.

**To Reproduce**
1. Simple question - Sample Dataset - Orders
2. Summarize count-of-rows by CreatedAt:Month
3. Change viz to Trend/Number, so it shows the Settings
4. Click the `< (column)` title and nothing happens.

**Expected behavior**
Return to viz selection, like all other viz types.

**Information about your Metabase Installation:**
Metabase 0.33.5.1 on Firefox 70, dev and JAR and docker.

**Comment by mazameli** [comment]
Reproduced this in 0.33.5.1. The breadcrumb link at the top of the sidebar should read `< Trend options`, and when I click it, it should show me the chart selection list. I also am not seeing any JS console errors.

![image](https://user-images.githubusercontent.com/2223916/68974222-0e5a0400-07a5-11ea-93ff-3134af86c128.png)

**Comment by flamber** [comment]
Fixed by PR #11833
