### ISSUE TITLE
Allow custom fields ("custom columns") to work with text and datetime fields

### ISSUE THREAD

**Issue by phaedratinder** [metabase/metabase#11330]
**Is your feature request related to a problem? Please describe.**
Currently when creating a custom column, the field formula calculation only allows numeric fields be included.

**Describe the solution you'd like**
I would like to be able to do operations on text and datetime fields, including:
- extract substrings and concatenate fields
- convert dates or numbers stored as text to datetime/numeric formats
- subtract datetime fields to get difference in time between two dates
- extract year/month/day/hour/minute/second etc from datetime value

**Describe alternatives you've considered**
Alternative solutions include:
- exporting the dataset to excel and doing the work there: consequence of this is that metabase can not be used any further on that dataset, and the columns can't be saved, reused, or included in metabase dashboards

- including these fields in the raw database: typically this is not desirable as the derived fields are idiosyncratic to the particular analysis and would not be stored as distinct fields in the master dataset 

Some of this functionality is available in metabase (using group by to extract datetime components, filter by values in two fields if looking for exactly one concatenated value filter by contains if looking for exactly one substring value) but in more limited capability than if the values could be operated on as a field.  For instance, if I want to show a pie chart that breaks down the proportion of complaints received in a small town by street name or zip code, I could not use a filter or group by to do this if the addresses are stored as a single field. 

**How important is this feature to you?**
When working in excel, these are some of the most frequent functions I use to be able to drill into the datasets.  This roadblock has emerged early in testing metabase because of how frequently these functions are useful or necessary, especially for working with imperfect data.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to https://github.com/metabase/metabase/issues/10290#issuecomment-543289604 and #6331

**Comment by ohld** [comment]
Any update on that? There is no way to calculate retention (custom column which is basically subtraction of two datetime columns) based on Postgres data. And this is sad.

**Comment by flamber** [comment]
Version 0.35.0 got a lot more expression functions for math and strings (though not date functions):
https://github.com/metabase/metabase/releases/tag/v0.35.0

**Comment by dannyeuu** [comment]
@flamber this particular feature has did not included in release v0.35.0, correct? There are new planning?

**Comment by flamber** [comment]
@dannyeuu 
It depends on what which you're referring to, date function are not in 0.35 - besides `between`.
https://www.metabase.com/docs/latest/users-guide/expressions.html

@PauloHFM 
But string functions are, so example ` SumIf([Purchases], [Client] LIKE '%John%'))` works as:
```
SumIf([Purchaces], contains([Client], "John"))
```

**Comment by sbelak** [comment]
`CountIf` and `SumIf` work with all types of filter expressions, including dates. What we currently don't expose are date extractors like `YEAR` in example above. 

We also don't expose datetime arithmetic even though MBQL supports adding/subtracting intervals from dates (eg `[:+ [:datetime-field [:field-id 1] :day] [:interval -31 :day]]`). What we don't support in any capacity is adding/subtracting 2 dates.

**Comment by guilhermecomum** [comment]
I'm hopping a lot for this feature, I have a database and a I wish to create a column with (start_datetime - end_datetime)

**Comment by ngunyimacharia** [comment]
Also greatly looking forward to being able to do datetime arithmetic with Metabase.

**Comment by schwarzjan** [comment]
Please allow hh:mm:ss formatting

**Comment by ReneSoul** [comment]
I would love to see this as well. My use case is actually simple, I have support tickets with a start and end date, so its important to see the average solution date

**Comment by abhayIII** [comment]
This needs to be addressed. I have a table that has the date of births, how do I convert them to the current ages?
I am hoping to find a work around, anyone?

**Comment by noahatrasa** [comment]
this would also be very helpful in terms of filtering on these columns... currently, it's not possible to filter on text or even if blank for text fields

**Comment by flamber** [comment]
@noahatrasa 
It is possible to use Custom Expression for blank text field with `[column] = ""` or other texts functions like `contains` etc
But `null` values is not possible #12225

**Comment by rentgratatech** [comment]
> I'm hoping a lot for this feature, I have a database and I wish to create a column with (start_datetime - end_datetime)

@flamber are you able to provide any clarity on alternative solutions or when this may be possible? The alternative solution of storing a calculated value is highly undesirable.

**Comment by CoderickLamar** [comment]
+1

**Comment by LarissaGuder** [comment]
> This needs to be addressed. I have a table that has the dates of birth, how do I convert them to the current ages?
> I am hoping to find a work around, anyone?

`SELECT *, TIMESTAMPDIFF(YEAR, `BIRTH_DATE`, DATE(NOW())) AS `age` FROM `PEOPLE`
`

**Comment by Husselbossel** [comment]
This works for me: http://www.sqlines.com/postgresql/how-to/datediff

DATE_PART('day', min("public"."order"."created_at") - "User"."created_at") as "day_btw_acc_order",


(DATE_PART('day', min("public"."order"."created_at") - "User"."created_at") * 24 
+ DATE_PART('hour', min("public"."order"."created_at") - "User"."created_at")
) AS     "hrs_btw_acc_order",

(
    (
        (DATE_PART('day', min("public"."order"."created_at") - "User"."created_at") * 24 
        + DATE_PART('hour', min("public"."order"."created_at") - "User"."created_at")) 
        * 60
    )
    + DATE_PART('minute', min("public"."order"."created_at") - "User"."created_at")
) AS     "min_btw_acc_order"

**Comment by flamber** [comment]
Closing this as fixed from 0.40 (tentative ETA [in a month](https://github.com/metabase/metabase/milestone/131)).
Any subsequent requests will need their own separate feature request, since it's difficult to tackle issues with multiple requests.

**Comment by ashajkofci** [comment]
How is current_date implemented then ?

**Comment by flamber** [comment]
@ashajkofci 
It is not. But please create a feature request specific to only that. https://github.com/metabase/metabase/issues/new/choose
