### ISSUE TITLE
Custom Question builder, changing first step removes subsequent steps completely

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#11334]
**Describe the bug**
When using the Custom question builder (notebook mode), if there are a series of joins and processing steps, changing the first step completely removes the subsequent steps.

This essentially means you've got to get the first step 100% correct before moving forward. Part of the benefit of these notebook style editors is that you can try stuff then tweak it to correct issues, this reset is blocking that.

**Logs**
No output in any logs

**To Reproduce**
1. Go to Custom question screen
2. Setup as shown below (Orders > filter for Product category "Doohickey" > Sum Total by user ID > Join People > Count by People ID
![image](https://user-images.githubusercontent.com/4504437/69019279-cd682680-0a14-11ea-8919-1670876d0868.png)

3. In the first "Filter" section add category "Gizmo" and click the "Update Filter" button
4. Note the 2nd step of the question is removed (see screenshot) meaning I need to repeat those step from memory
![image](https://user-images.githubusercontent.com/4504437/69019341-15874900-0a15-11ea-8589-d05854f537cc.png)

**Expected behavior**
Subsequent processing steps should be retained when editing earlier steps. I understand that there could be dependencies between these steps but often that's not the case.

I expected to be able to add a new filter and not lose most of my work. Notebooks should enable exploratory analysis, and allow you to build up a complex series of operations. Resetting these steps prevents that.

**Screenshots**

**Information about your Metabase Installation:**

- Your browser and the version: Chrome (v77.0.3865.120)
- Your operating system: Windows 7
- Your databases: MS SQL Server
- Metabase version: v0.33.4
- Metabase hosting environment: Jar file on Windows server
- Metabase internal database: Postgres

**Severity**
Frustrating and stopping me from using the advanced query builder to it's full potential. If I can't change previous steps then what's the point?

**Comment by gb-ita** [comment]
Same in 0.33.6, Firefox browser, MacOS. Annoying.

**Comment by mazameli** [comment]
Hmm, yeah, that shouldn't be happening. Any idea what might be up, @tlrobinson?

**Comment by tlrobinson** [comment]
The expected behavior is to only remove dependent clauses (recursively), so this sounds like a bug.

**Comment by tlrobinson** [comment]
@notrom @gb-ita This should be resolved by #11792. Please try out that branch if you can.

**Comment by gb-ita** [comment]
I'm using a docker installation. Can you please point me how to try out a different branch? Thanks in advance.
