### ISSUE TITLE
how can i show message on the map like this？

### ISSUE THREAD

**Issue by DOVER123** [metabase/metabase#11346]
![221304e0eda5a7f5b833c51e99d3ddd](https://user-images.githubusercontent.com/17616876/69116321-edf0b900-0ac6-11ea-8298-c5bade7d2815.jpg)

**Comment by DOVER123** [comment]
show the data on the map not on the tips when hover

**Comment by flamber** [comment]
Hi @DOVER123 

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Please close this issue :+1: 

No, Metabase does not have a way to show values on the region. And it would also be difficult to do, if the regions are small or the values are large.

Currently you can display color-graded regions, where darkest has the highest value, and a legend.

![image](https://user-images.githubusercontent.com/1447303/69117480-6cad0e00-0a55-11ea-9a78-bce3cfc50c2b.png)

**Comment by DOVER123** [comment]
ok i understand，thank you very much

**Comment by ScottZt** [comment]
hi ,Could you tell me ,What kind of data can I create to change the map? for now , The maps are all gray，My data seems like unuseful
