### ISSUE TITLE
Disable multiselect for dashboard filter

### ISSUE THREAD

**Issue by develar** [metabase/metabase#11348]
**Is your feature request related to a problem? Please describe.**
`Product` field it is enum of values (strings, clickhouse enum). Dashboard cannot be displayed for several products, the only product should be selected (performance metrics — data cannot be mixed).

**Describe the solution you'd like**
I want ability to explicitly set input type.

Actual: multiselect

<img width="417" alt="Screenshot 2019-11-19 at 07 39 56" src="https://user-images.githubusercontent.com/350686/69122687-cf2afc00-0a9f-11ea-9d1d-4f91922926d4.png">

Wanted: combox.

<img width="252" alt="Screenshot 2019-11-19 at 07 36 06" src="https://user-images.githubusercontent.com/350686/69122491-44e29800-0a9f-11ea-824d-af9e549077b4.png">

It is screenshot from custom-made dashboard, but I want to migrate to metabase.

**Describe alternatives you've considered**
No alternatives — only single selection should be allowed.

**How important is this feature to you?**
Not really important, but will be great if dashboard filter will be more tailored for needs.

**Additional context**

**Comment by flamber** [comment]
Hi @develar 
It sounds like a duplicate of #7605, if you agree, then please close this and upvote the other issue :+1:

**Comment by develar** [comment]
Duplicates #7605
