### ISSUE TITLE
Grouping by two columns not working on some column combinations

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#11340]
In custom questions when I do grouping on two columns, sometimes (i.e. depending on which two columns to choose) it doesn't work as expected. It shows an "unset" column:

![bug1](https://user-images.githubusercontent.com/15974735/69080992-e57a7e80-09f1-11ea-87f4-ebe996e2eef8.png)

It works fine in native queries.

No error in Metabase Logs.

JS Console Logs:
- FireFox 70.0.1:
```javascript
TypeError: "e is undefined"
    b https://[MY_DOMAIN]/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99:5
    m https://[MY_DOMAIN]/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99:5
    n https://[MY_DOMAIN]/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99:5
    E https://[MY_DOMAIN]/app/dist/vendor.bundle.js?3f1abe1edb553ce0ef99:1
    h https://[MY_DOMAIN]/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99:5
    all https://[MY_DOMAIN]/app/dist/vendor.bundle.js?3f1abe1edb553ce0ef99:1
    h https://[MY_DOMAIN]/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99:5
    drillDownForDimensions https://[MY_DOMAIN]/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99:5
    default https://[MY_DOMAIN]/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99:5
    value https://[MY_DOMAIN]/app/dist/app-main.bundle.js?3f1abe1edb553ce0ef99:5
```
- Chrome 78.0.3:
```javascript
app-main.bundle.js?3f1abe1edb553ce0ef99:5 TypeError: Cannot read property 'unit' of undefined
    at b (app-main.bundle.js?3f1abe1edb553ce0ef99:5)
    at m (app-main.bundle.js?3f1abe1edb553ce0ef99:5)
    at app-main.bundle.js?3f1abe1edb553ce0ef99:5
    at Function.findIndex (vendor.bundle.js?3f1abe1edb553ce0ef99:1)
    at app-main.bundle.js?3f1abe1edb553ce0ef99:5
    at Function._.every._.all (vendor.bundle.js?3f1abe1edb553ce0ef99:1)
    at h (app-main.bundle.js?3f1abe1edb553ce0ef99:5)
    at t.drillDownForDimensions (app-main.bundle.js?3f1abe1edb553ce0ef99:5)
    at t.default (app-main.bundle.js?3f1abe1edb553ce0ef99:5)
    at app-main.bundle.js?3f1abe1edb553ce0ef99:5
```
<details><summary>Expanded Chrome Console Logs for this Error</summary>
<pre>
n.visualizationIsClickable | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
-- | -- | --
  | value | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | r | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | n.value | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | value | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | n.cellRenderer | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | t.a | @ | vendor.bundle.js?3f1abe1…:1
  | value | @ | vendor.bundle.js?3f1abe1…:1
  | value | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _reconcilerUpdateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateChildren | @ | vendor.bundle.js?3f1abe1…:1
  | _updateDOMChildren | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | receiveComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _updateRenderedComponent | @ | vendor.bundle.js?3f1abe1…:1
  | _performComponentUpdate | @ | vendor.bundle.js?3f1abe1…:1
  | updateComponent | @ | vendor.bundle.js?3f1abe1…:1
  | performUpdateIfNecessary | @ | vendor.bundle.js?3f1abe1…:1
  | performUpdateIfNecessary | @ | vendor.bundle.js?3f1abe1…:1
  | b | @ | vendor.bundle.js?3f1abe1…:1
  | perform | @ | vendor.bundle.js?3f1abe1…:1
  | perform | @ | vendor.bundle.js?3f1abe1…:1
  | perform | @ | vendor.bundle.js?3f1abe1…:1
  | M | @ | vendor.bundle.js?3f1abe1…:1
  | closeAll | @ | vendor.bundle.js?3f1abe1…:1
  | Promise.then (async) |   |  
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | M | @ | vendor.bundle.js?3f1abe1…:1
  | u._invoke | @ | vendor.bundle.js?3f1abe1…:1
  | e.<computed> | @ | vendor.bundle.js?3f1abe1…:1
  | r | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | dispatch | @ | vendor.bundle.js?3f1abe1…:1
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | M | @ | vendor.bundle.js?3f1abe1…:1
  | u._invoke | @ | vendor.bundle.js?3f1abe1…:1
  | e.<computed> | @ | vendor.bundle.js?3f1abe1…:1
  | r | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | Promise.then (async) |   |  
  | r | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | (anonymous) | @ | vendor.bundle.js?3f1abe1…:1
  | value | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | C | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | onAddDimension | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | r.handleAdd | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | onClick | @ | app-main.bundle.js?3…abe1edb553ce0ef99:5
  | i | @ | vendor.bundle.js?3f1abe1…:1
  | s | @ | vendor.bundle.js?3f1abe1…:1
  | executeDispatchesInOrder | @ | vendor.bundle.js?3f1abe1…:1
  | d | @ | vendor.bundle.js?3f1abe1…:1
  | f | @ | vendor.bundle.js?3f1abe1…:1
  | e.exports | @ | vendor.bundle.js?3f1abe1…:1
  | processEventQueue | @ | vendor.bundle.js?3f1abe1…:1
  | handleTopLevel | @ | vendor.bundle.js?3f1abe1…:1
  | f | @ | vendor.bundle.js?3f1abe1…:1
  | perform | @ | vendor.bundle.js?3f1abe1…:1
  | batchedUpdates | @ | vendor.bundle.js?3f1abe1…:1
  | batchedUpdates | @ | vendor.bundle.js?3f1abe1…:1
  | dispatchEvent | @ | vendor.bundle.js?3f1abe1…:1
</pre>
</details>

- Metabase version: Tested on `0.33.5.1` and `0.33.3`
- Metabase hosting environment: Elastic Beanstalk for  `0.33.5.1`, Local jar file for `0.33.3`
- Metabase internal database: Postgres
- Database: Postgres

**Comment by flamber** [comment]
Hi @vvaezian 
What's the Field Type (Admin > Data Model) and the actual database column type for those columns?
It looks like the table is showing as Pivot - if you disable Pivot, does it then show correctly?

**Comment by vvaezian** [comment]
In the data model one of the two columns did not have "Type" defined for it. When I set the type to `Category` the problem was fixed. The actual data types were VARCHAR.

I had created this card using Metabase API's [`POST /api/card/`](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apicard), where the JSON was as follows (`{n}`'s are placeholders that were filled properly)
```
{ 'dataset_query': {'database': {1},
                    'query': {'fields': {4},
                              'source-table': {2}},
                    'type': 'query'},
  'display': 'table',
  'name': '{0}',
  'collection_id': {3},
  'visualization_settings': {"table.column_formatting":[{"columns":["Diff_Scaled"],
                                                          "type":"range",
                                                          "colors":["#ED6E6E","white","#84BB4C"],
                                                          "min_type":"custom",
                                                          "max_type":"custom",
                                                          "min_value":-10,
                                                          "max_value":10,
                                                          "operator":"=",
                                                          "value":"",
                                                          "color":"#509EE3",
                                                          "highlight_row":False
                                                        }]
                            } 
}
```

I don't know about enabling/disabling Pivot. How does it work?

I just created a test card from the web interface and checked the API request. In the `visualization_settings` there were these keys:
- `'table.columns'`
- `'table.pivot_column'`
- `'table.cell_column'`

I didn't use any of these keys in my JSON. I know  'visualization_settings' itself is required, but not sure if any of its keys should be included as well.

**Comment by flamber** [comment]
@vvaezian To enable/disable Pivot on tables (when there's 3 columns), just click visualization Settings in bottom-left of a question, or hover dashboard card and click :gear: 
The `dataset_query` you're showing, are you returning 3 columns instead of `{4}` placeholder?
It's very tricky to fix an issue, when it's not possible to reproduce on Sample Dataset and so much of the `dataset_query` has been redacted.
But it's informative that you're creating the questions via API. What if you make the same question, but using the interface and compare the API requests?

**Comment by vvaezian** [comment]
The `dataset_query` would be something like this after replacement:
```
{'database': 123,
 'query': {'fields': [ ['field-id', 32605],
                       ['field-id', 23240],
                       ['field-id', 23249],
                       ['field-id', 23247],
                        ... 
                     ],
           'source-table': 456},
'type': 'query'}
```
The JSON is for creating a simple card which only reorders columns. So the number of columns is more than 3. I then manually tried what was described in the first post (average of col1 group by col2 and col3) which resulted in the error mentioned.

I'll close this issue as it is fixed now, but need to dig deeper to find the root cause.

Thanks.

**Comment by flamber** [comment]
@vvaezian You might be interested in #9874
