### ISSUE TITLE
Dashboard widget "View these xxx" for NULL category summary doesn't apply "Is Empty" filter

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#11345]
**Describe the bug**
Clicking "view these xxx" on an aggregate value where the Group by value is NULL, i.e. "Is Empty", the resulting table doesn't apply the "Is Empty" filter to that field and all the underlying records are displayed.

The same action on the question itself seems to work, but it may not be exactly as intended. It relies on an empty "Is" selection list, that's probably OK but it presents slightly oddly.

**Logs**
Nothing different in the javascript console

**To Reproduce**
1. Create a simple question that counts grouped by a field that contains NULL values
2. Click the Count summary of the NULL row, click "View these xxx"
3. Resulting table is filtered with an empty "Is" list for the grouped by field
2. Add that question to a dashboard
3. In the dashboard click the Count summary of the NULL row, click "View these xxx"
4. The resulting table is **not** filtered to include only those records where the grouped by value is NULL

**Expected behavior**
NULL or "Is Empty" filters are retained on the "View these xxx" function. Consistent behaviour between "View these xxx" from the dashboard and the base question.

**Screenshots**
Question itself
![image](https://user-images.githubusercontent.com/4504437/69115099-4edeb800-0aec-11ea-944d-07d0c8565e38.png)
After clicking the 913 and "View these xxx"
![image](https://user-images.githubusercontent.com/4504437/69115206-a11fd900-0aec-11ea-95ac-1602fd743ecc.png)

Then same question in a dashboard
![image](https://user-images.githubusercontent.com/4504437/69115256-cf051d80-0aec-11ea-9f75-c00325f5260b.png)
After clicking the 913 and "View these xxx"
![image](https://user-images.githubusercontent.com/4504437/69115316-fbb93500-0aec-11ea-8d40-f8e6dde99765.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
- Your browser and the version: Chrome (v77.0.3865.120)
- Your operating system: Windows 7
- Your databases: MS SQL Server
- Metabase version: v0.33.4
- Metabase hosting environment: Jar file on Windows server
- Metabase internal database: Postgres

**Severity**
Frustration, and need to remember what to expect, the drill down appears "wrong" if you don't remember or know.

**Additional context**

**Comment by flamber** [comment]
Confirmed on 0.33.5.1 (also tested 0.32.10) - It's possible to reproduce with Sample Dataset:

1. Simple question - Sample Dataset > Orders
2. Summarize Count-of-rows by Discount:Auto - change visualization to table - save question
3. Clicking the top row of column "Count" (16845) > "View these Orders", adds the filter "Discount is equal to" instead of "Discount is empty", but result is correct.
4. Add step 2 question to dashboard and click top row of column "Count" (16845) > "View these Orders", does not add any filter.

Looking at the `/api/dataset` request in step 4, it does not add a `query>filter` from a `null` column.

**Comment by notrom** [comment]
Thanks @flamber I struggled to find a NULL value in the Sample Dataset. Thanks for chasing it up.
