### ISSUE TITLE
Improve display of legends with many series

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11355]
Currently, when there isn't enough room to display all the text for every series' legend on a chart, we just collapse everything down into an unhelpful row of dots:
![image](https://user-images.githubusercontent.com/2223916/69199494-f3f99080-0aec-11ea-808b-088d74ea4b17.png)

There are a number of possible solutions we could explore that would allow us to display the names of series:
1. Let the legends wrap to multiple lines. This could end up squishing visualizations, especially in dashboard cards.
2. Display as many legend items as we can fit, and collapse the rest into a `and n more` element, which could either display the rest of the items in a tooltip on hover, or expand the rest of the items on click. We do the former for pie charts: 
![image](https://user-images.githubusercontent.com/2223916/69199833-2061dc80-0aee-11ea-9be8-a75da55340c4.png)
3. Display the legends vertically on the side of the chart, like we do for pie charts, if there are too many to be displayed horizontally. I posted a mockup of this here: https://github.com/metabase/metabase/issues/3656#issuecomment-512610895

**I currently think 3 is the best approach:** vertical real estate tends to be scarcer than horizontal real estate in our 16:9-aspect-ratio world; this more closely matches what we already do for pie charts; and this doesn't rely on hover as heavily as option 2. I think option 2 is the runner-up for me.

_Side note: somewhat related is the request to be able to hide legends entirely: https://github.com/metabase/metabase/issues/8437_

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
All three options would probably fix #10971 and second option sounds related to #11325.

**Comment by maxzheng** [comment]
#3 will show more # of legends, but could still run into limits if the height of the chart isn't that tall. It would be great if there are options to let users choose what they want (default to "auto" -- do horizontal or vertical depending on space), but allow users to choose horizontal or vertical. In any option, it will show all selections in one/multiple rows/columns (instead of hiding/turning into dots). I think some users prefer horizontally while others prefer the other. If we have to choose one, I guess vertical.

**Comment by maxzheng** [comment]
One of our data scientists wanted to move the horizontal legends (just 4 of them) to the right of the chart, so it is definitely ideal to have the option of putting the labels on the top, left, or right side regardless of the # of legends.

**Comment by keshav0129** [comment]
Is someone working on this already. Just allowing legends to wrap to multiple lines would do the trick for me.

**Comment by mlm603** [comment]
+1 to giving the user the option to choose the legend location. Especially for stacked bar/area charts, it's often easier to read the legend when they are on the right side of the viz. Sometimes we like to have the legend centered under the bottom of the chart too, for things like grouped bars.

**Comment by flamber** [comment]
@patulacci I've created a separate issue for that - #16000

**Comment by ranquild** [comment]
This issue is resolved by:
- https://github.com/metabase/metabase/pull/17396
- https://github.com/metabase/metabase/pull/17412
- https://github.com/metabase/metabase/pull/17433
- https://github.com/metabase/metabase/pull/17552

**Comment by BadrBensassi** [comment]
@flamber for the legend location issue, I see that the current #11355 is Closed. Does it mean that this feature has been planned on the roadmap or did we move the conversation to a different thread?
