### ISSUE TITLE
using multiple variables within one question/query

### ISSUE THREAD

**Issue by Flousa92** [metabase/metabase#11359]
I'm trying to independently filter two metrics that run on different timeframes within the same question/query but I can't find a way to do it. For the context, I'm trying to get a rate by dividing two different metrics at any given period of time. Both have to be filtered by different timeframes (contract end date and close date).  

Is this something Metabase can handle at the moment?  Would love your suggestions..

Thanks,

**Comment by flamber** [comment]
Hi @Flousa92 
Only open questions in the forum: https://discourse.metabase.com/t/using-multiple-variables-within-one-question-query/8081
Please close this issue :+1:
