### ISSUE TITLE
Make it clearer in the query builders and data browser if a DB is still going through first-time sync+scan

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11354]
Fairly often we get reports of users being confused or running into error messages when trying to query their database for the first time because it hasn't finished the first sync + scan, particularly if they've just connected a really large DB.

Here's a sampling of some such reports:
https://discourse.metabase.com/t/unable-to-browse-database-tables/8065
https://github.com/metabase/metabase/issues/11324
https://github.com/metabase/metabase/issues/11332

A simple solution would be to have the Data Browser and database selection menus of the query builders have a way to display a database in a disabled state if it's not done with the initial sync+scan, with some microcopy to indicate what's happening, like `Syncing…`

I'd consider this a follow-on to https://github.com/metabase/metabase/issues/649.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Fixed in #18675
