### ISSUE TITLE
[minor/harmless bug] Check for updates thinks 0.33.5.1 needs to be updated to 0.33.5

### ISSUE THREAD

**Issue by giovannibonetti** [metabase/metabase#11352]
**Describe the bug**
Check for updates thinks 0.33.5.1 needs to be updated to 0.33.5.

**To Reproduce**
1. Go to 'admin'
2. Click on 'settings > update'
3. See update notification

**Expected behavior**
It should say that I'm running the latest version

**Screenshots**

![Screenshot 2019-11-19 18 13 13](https://user-images.githubusercontent.com/3451581/69187197-e0ecbd80-0af8-11ea-9e91-cfc04351b09e.png)

![Screenshot 2019-11-19 18 10 33](https://user-images.githubusercontent.com/3451581/69186850-2b216f00-0af8-11ea-81ff-cd19d87825a5.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 78.0
- Your operating system: OS X 10.14.6
- Your databases: Postgres
- Metabase version: 0.33.5.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Harmless, just reported it out of curiosity.

**Additional context**
--

**Comment by flamber** [comment]
@giovannibonetti It's because version-info.json still announces 0.33.5 as `latest`. https://github.com/metabase/metabase/issues/11289#issuecomment-553652527
There's a 0.33.6 being pushed [right now](https://github.com/metabase/metabase/releases/tag/v0.33.6), so hopefully it'll be fixed in an hour or so.
Related to #11336

**Comment by mazameli** [comment]
This should be fixed now since `version-info.json` indicates that 0.33.6 is the `latest`. 

![image](https://user-images.githubusercontent.com/2223916/69278181-a33e7200-0b96-11ea-8670-2c9c3d642e21.png)
