### ISSUE TITLE
Table visualisation bugs

### ISSUE THREAD

**Issue by jc-paris** [metabase/metabase#11364]
**Describe the bug**
When using the table view to see request result, editing columns doesn't work.

**Logs**
No strange logs in the console.. 

**To Reproduce**
- Open a question with table visualization
- (1) Try to add a column : all selected columns changes (after a play button displayed to re-run the request)
- (2) Try to reorder a column : all selected columns changes, some disappear and need to be re-selected (after a play button displayed to re-run the request)
- (3) The timestamp date formatting display a January 1970 date instead of November 2019 (not when browsing the all table by default, by as soon as I customize the view, date is wrong. (after a play button displayed to re-run the request)

**Expected behavior**
When adding a column, keep existing column.
When reordering column, keep existing column.
When displaying timestamp in table, always show the correct date.

**Screenshots**
Using default browsing // After reordering
<img width="300" alt="Screenshot 2019-11-21 at 08 44 46" src="https://user-images.githubusercontent.com/6810502/69317423-37621500-0c3b-11ea-8ece-43c1c59b1136.png"> <img width="300" alt="Screenshot 2019-11-21 at 08 44 53" src="https://user-images.githubusercontent.com/6810502/69317435-3d57f600-0c3b-11ea-8962-c0fc5a7aff6e.png">

After successfully configured all column // After moving or adding only 1 column
<img width="1591" alt="Screenshot 2019-11-21 at 08 49 29" src="https://user-images.githubusercontent.com/6810502/69317857-249c1000-0c3c-11ea-8bf0-d73bc4665dfc.png">
<img width="1206" alt="Screenshot 2019-11-21 at 08 49 37" src="https://user-images.githubusercontent.com/6810502/69317872-2e257800-0c3c-11ea-87cc-26f164f552e6.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
```json
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_141-b15",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_141",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.141-b15",
    "os.name": "Mac OS X",
    "os.version": "10.15.1",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Your browser and the version:  Chrome 78.0.3904.108 (but also happening inside mac app)
- Your operating system: Mac OS Catalina 10.15.1
- Your databases:  MongoDB
- Metabase version: 0.33.6
- Metabase hosting environment: Mac app
- Metabase internal database: H2 (default)

**Severity**
This issue is blocking me from generating proper dashboard or read the data and I can't configure the table with all the expected column.

**Additional context**

**Comment by mazameli** [comment]
Is this happening when using the native query builder, or the GUI query builder? I have not yet been able to reproduce this using MongoDB with the macOS app v0.33.6, or with any other databases when running master in my browser.

**Comment by jc-paris** [comment]
Hi @mazameli,
It's happening with GUI query builder, I noticed that the native query is not correct (see queries below).
It seems there is some adjustment made on `ts` field to compute the correct date.

Default native query generated when browsing the collection 
```json
[
  {
    "$project": {
      "_id": "$_id",
      "affinity_type": "$affinity_type",
      "cty": "$cty",
      "destination": "$destination",
      "error_response": "$error_response",
      "item": "$item",
      "off": "$off",
      "platform": "$platform",
      "pop": "$pop",
      "queue_location": "$queue_location",
      "repeat_mode": "$repeat_mode",
      "resume_playback": "$resume_playback",
      "search": "$search",
      "server_ts~~~default": {
        "$let": {
          "vars": {
            "column": {
              "$add": [
                "1970-01-01T00:00:00.000Z",
                {
                  "$multiply": [
                    "$server_ts",
                    1000
                  ]
                }
              ]
            }
          },
          "in": "$$column"
        }
      },
      "shuffled": "$shuffled",
      "ts~~~default": {
        "$let": {
          "vars": {
            "column": {
              "$add": [
                "1970-01-01T00:00:00.000Z",
                {
                  "$multiply": [
                    "$ts",
                    1000
                  ]
                }
              ]
            }
          },
          "in": "$$column"
        }
      },
      "type": "$type",
      "uniq_id": "$uniq_id",
      "usr": "$usr",
      "version": "$version"
    }
  },
  {
    "$project": {
      "_id": "$_id",
      "affinity_type": "$affinity_type",
      "cty": "$cty",
      "destination": "$destination",
      "error_response": "$error_response",
      "item": "$item",
      "off": "$off",
      "platform": "$platform",
      "pop": "$pop",
      "queue_location": "$queue_location",
      "repeat_mode": "$repeat_mode",
      "resume_playback": "$resume_playback",
      "search": "$search",
      "server_ts~~~default": "$server_ts~~~default",
      "shuffled": "$shuffled",
      "ts~~~default": "$ts~~~default",
      "type": "$type",
      "uniq_id": "$uniq_id",
      "usr": "$usr",
      "version": "$version"
    }
  },
  {
    "$limit": 1048576
  }
]
```

And the native query after reordering any row:
```json
[
  {
    "$project": {
      "_id": "$_id",
      "affinity_type": "$affinity_type",
      "cty": "$cty",
      "destination": "$destination",
      "error_response": "$error_response",
      "item": "$item",
      "off": "$off",
      "platform": "$platform",
      "pop": "$pop",
      "queue_location": "$queue_location",
      "repeat_mode": "$repeat_mode",
      "resume_playback": "$resume_playback",
      "search": "$search",
      "server_ts": "$server_ts",
      "ts": "$ts",
      "shuffled": "$shuffled",
      "type": "$type",
      "uniq_id": "$uniq_id",
      "usr": "$usr",
      "version": "$version"
    }
  },
  {
    "$project": {
      "_id": "$_id",
      "affinity_type": "$affinity_type",
      "cty": "$cty",
      "destination": "$destination",
      "error_response": "$error_response",
      "item": "$item",
      "off": "$off",
      "platform": "$platform",
      "pop": "$pop",
      "queue_location": "$queue_location",
      "repeat_mode": "$repeat_mode",
      "resume_playback": "$resume_playback",
      "search": "$search",
      "server_ts": "$server_ts",
      "ts": "$ts",
      "shuffled": "$shuffled",
      "type": "$type",
      "uniq_id": "$uniq_id",
      "usr": "$usr",
      "version": "$version"
    }
  },
  {
    "$limit": 1048576
  }
]```

**Comment by jc-paris** [comment]
NB: I have timestamp in second, not milliseconds.

**Comment by flamber** [comment]
There has been a lot of changes to both Mongo query processor, metadata casting and frontend formatting.
I've not been able to reproduce on 0.41.2
