### ISSUE TITLE
New database default permissions are dangerous in multi-user/multi-tenant

### ISSUE THREAD

**Issue by dillondoyle** [metabase/metabase#11362]
This issue was [brought up in a previous ticket ](https://github.com/metabase/metabase/issues/6735) that was closed, but it looks like only the first issue was resolved (not this issue).

When adding a new database, the default permission is set to all users.

We are multi-user / multi-tenant. Client data is stored in separate databases. When adding a new client database it automatically sets that database permission for all users. We have to then go into permissions and fix/restrict.

This seems like a dangerous default for multi-user installs. And even though the time between adding new database and updating permissions is short, humans can forget.

Maybe could change the default only for multi-user installs? So that first time installers with only admin wont run into a problem if they forget or dont know to check permissions.

**Comment by flamber** [comment]
Hi @dillondoyle 
Issue #6735 is still open - multiple points in issues makes it more difficult to handle them.
Not sure if we should close it and use yours as a base, or if you want to close your issue.

**Comment by dillondoyle** [comment]
Oh sorry! I don't use github much thought it was closed. I can close this one if you want?

**Comment by flamber** [comment]
@dillondoyle Yes, let's close this, since the other one already has several upvotes.

**Comment by dillondoyle** [comment]
Sorry closed this is a dupe the mentioned issue is actually still open
