### ISSUE TITLE
Export Excel Bug

### ISSUE THREAD

**Issue by salemilk** [metabase/metabase#11365]
I have about a few million pieces of data, and I want to export tens of thousands of results to excel to give an error.

`{"message":"Java heap space","type":"class java.lang.OutOfMemoryError","stacktrace":["org.apache.xmlbeans.impl.store.Saver$TextSaver.resize(Saver.java:1700)","org.apache.xmlbeans.impl.store.Saver$TextSaver.preEmit(Saver.java:1303)","org.apache.xmlbeans.impl.store.Saver$TextSaver.emit(Saver.java:1190)","org.apache.xmlbeans.impl.store.Saver$TextSaver.emitElement(Saver.java:962)","org.apache.xmlbeans.impl.store.Saver.processElement(Saver.java:476)","org.apache.xmlbeans.impl.store.Saver.process(Saver.java:307)","org.apache.xmlbeans.impl.store.Saver$TextSaver.saveToString(Saver.java:1864)","org.apache.xmlbeans.impl.store.Cursor._xmlText(Cursor.java:546)","org.apache.xmlbeans.impl.store.Cursor.xmlText(Cursor.java:2436)","org.apache.xmlbeans.impl.values.XmlObjectBase.xmlText(XmlObjectBase.java:1500)","org.apache.poi.xssf.model.SharedStringsTable.getKey(SharedStringsTable.java:135)","org.apache.poi.xssf.model.SharedStringsTable.addEntry(SharedStringsTable.java:181)","org.apache.poi.xssf.usermodel.XSSFCell.setCellValue(XSSFCell.java:453)","org.apache.poi.xssf.usermodel.XSSFCell.setCellValue(XSSFCell.java:417)","dk.ative.docjure.spreadsheet$fn__29694.invokeStatic(spreadsheet.clj:236)","dk.ative.docjure.spreadsheet$fn__29694.invoke(spreadsheet.clj:233)","clojure.lang.MultiFn.invoke(MultiFn.java:234)","dk.ative.docjure.spreadsheet$add_row_BANG_.invokeStatic(spreadsheet.clj:267)","dk.ative.docjure.spreadsheet$add_row_BANG_.invoke(spreadsheet.clj:260)","dk.ative.docjure.spreadsheet$add_rows_BANG_.invokeStatic(spreadsheet.clj:277)","dk.ative.docjure.spreadsheet$add_rows_BANG_.invoke(spreadsheet.clj:270)","dk.ative.docjure.spreadsheet$create_workbook.invokeStatic(spreadsheet.clj:295)","dk.ative.docjure.spreadsheet$create_workbook.invoke(spreadsheet.clj:285)","--> util.export$export_to_xlsx.invokeStatic(export.clj:28)","util.export$export_to_xlsx.invoke(export.clj:27)","api.dataset$as_format_response.invokeStatic(dataset.clj:111)","api.dataset$as_format_response.invoke(dataset.clj:103)","api.dataset$fn__47520$as_format_async__47525$fn__47526$fn__47591$state_machine__12321__auto____47620$fn__47623.invoke(dataset.clj:133)","api.dataset$fn__47520$as_format_async__47525$fn__47526$fn__47591$state_machine__12321__auto____47620.invoke(dataset.clj:128)"]}`

thanks

**Comment by EdwardOwusuAdjei** [comment]
Whats the memory allocated to your heap space for the JVM... You might have to increase it from checking here https://www.metabase.com/docs/latest/troubleshooting-guide/running

**Comment by flamber** [comment]
Hi @salemilk 
As already said, you're running out of memory, so you need to allocate RAM.
If that solves your issue, then please close this issue :+1: 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by salemilk** [comment]
Command to increase memory

Do you know how to solve it?

`Invalid maximum heap size:-Xmx6g
the specified size exceeds the maximum representable size
Error :Could not create the java Virtual Machine
Error :A fatal exception has ocurred. Program will exit.`

**Comment by flamber** [comment]
@salemilk It sounds like you don't have 6GB of RAM available on the machine/container. You need to specify a smaller number than all the available RAM on your machine.

**Comment by salemilk** [comment]
@flamber hi,my machine is 32 grams of memory.
[#5187](https://github.com/metabase/metabase/issues/5187) same question.

**Comment by flamber** [comment]
@salemilk Could it be that you are using 32bit Java instead of 64bit?
If #5187 is the same issue, then please close this issue :+1: 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by salemilk** [comment]
@flamber hi,

I checked my java version and replaced it with 64 bit.

Solved my problem, thank you very much! :)
