### ISSUE TITLE
Default Text Filters to `contains`

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#11369]
A case insensitive `contains` is a much lazier option for most people than a `equals` for most text fields. We should default to this for DBs that support it. (Think that's all of them?)

Related to #6023

## Expected Behavior
Let's change the default filter operator for strings to "Contains" instead. Bonus points if we can do this only when there are 10+ distinct values in the column.

[Slack context](https://metaboat.slack.com/archives/C01MS7DQKR6/p1677765300623519).

**Comment by flamber** [comment]
Guess it would depend on #8910, if I understand this correctly.
And also related to #8219 on dashboard filter and question widgets, which uses "begins with"

**Comment by ranquild** [comment]
Closed by https://github.com/metabase/metabase/issues/29881
