### ISSUE TITLE
Some time filters not working on Google Analytics on master

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11372]
When trying to filter on `Date` using any of these types of filters on master:
- Before
- After
- On
- Between

…I'm getting the following error message:

`No implementation of method: :coerce-to-timestamp of protocol: #'metabase.util.date/ITimestampCoercible found for class: java.time.ZonedDateTime`

This also means drag-to-filter on line charts is broken, as well as the `Zoom In` drill-through function.

Could this be related to https://github.com/metabase/metabase/pull/11347 @camsaul?

**Comment by camsaul** [comment]
This was fixed in #11390, which includes tests for the underlying issue. Confirmed this is now working on stats/`master`
