### ISSUE TITLE
Allow joins on multiple fields in the notebook editor

### ISSUE THREAD

**Issue by PauloHFM** [metabase/metabase#11375]
Hey! I didn't find a issue about this!

You guys are planning to put more columns, in join data?

![image](https://user-images.githubusercontent.com/38223133/69464286-a97e4b00-0d5c-11ea-87a1-dc5f83c0cc16.png)

I am using v0.33.6

Like in the example above, i need to join with date and some other columns but I can't!

Thanks a lot!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Good idea. I think I have seen this request before, but can't find it. See #10924 about join with date.
Related to #3475 and #7335?

**Comment by PauloHFM** [comment]
@flamber I think is simpler than that. It's just like i can put "LEFT JOIN table2.column ON 1.date = 2.date AND 1.id = 2.other_id AND 1.name = 2.first_name" 
Today we can only choose join data with date, OR id OR name. And that's just wrong because it causes some various duplicates in data.

**Comment by Perdjesk** [comment]
Allowing join definition on multiple columns allow as well better performance when joining big tables that have to be joined on multiple columns. The query generated by adding several joins on the same table with an individual column each time is not optimal and can not be optimized (at least by PostgreSQL).

**Comment by flamber** [comment]
Implemented by #17633
