### ISSUE TITLE
Variable on Question SQL Editor not works

### ISSUE THREAD

**Issue by omysurya** [metabase/metabase#11382]
(conn=81) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SET @date_start = '2019-10-01'

**Comment by flamber** [comment]
Hi @omysurya 
Please provide all the information as requested, when opening a bug.
Looks like a duplicate of #4050. If you agree, then please close this and upvote the other issue :+1:
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by mazameli** [comment]
Closing as duplicate of #4050
