### ISSUE TITLE
Cannot go back on column visualization settings on dashboard + breaks preview

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11388]
**Describe the bug**
When editing visualization settings of a card on dashboard, then it's impossible to go back after clicking into a column's :gear: 
And depending on the column type, it'll break the preview too.

**Logs**
No console errors.

**To Reproduce**
1. Simple question > Sample Dataset > Orders, and save
2. Add question to dashboard, and save
3. Edit dashboard, hover the table card, click :gear: 
4. Click ID's :gear: and table preview disappears, and no way to return to columns other than closing the dialog. Click CreatedAt's :gear: and preview looks normal.

**Screenshots**
![Screencast 2019-11-25 20 16 17](https://user-images.githubusercontent.com/1447303/69594510-2f4f0000-0fc2-11ea-8e00-32992528ab1c.gif)

**Information about your Metabase Installation:**
Metabase 0.33.6 + master, H2/MySQL, Firefox 70 and Chromium 78.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Repro'd on 0.34.1

**Comment by LouisMonierSpark** [comment]
Any update on this one @flamber ? 
Thanks

**Comment by nemanjaglumac** [comment]
The UI has changed a lot and this is not reproducible anymore.
![image](https://user-images.githubusercontent.com/31325167/217356528-108286a0-561f-48c2-82f4-930304d5ef6e.png)

![image](https://user-images.githubusercontent.com/31325167/217356945-28667b44-7584-4940-80c5-cb36a6d6b54d.png)

All these work as expected.
