### ISSUE TITLE
Reverse (negate) filter rule

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#11397]
**Is your feature request related to a problem?**
Say I have a text column. I want to select all records that **do not "start with"**  the text `A`.
At the moment (`v0.33.6`), I can only select records that do start with `A`.

**Describe the solution you'd like**
When setting a filter, I would like to have ***a checkbox that allow me to "reverse" (or negate) the filter rule*** (i.e. when ticked, records that the filter would have filtered out would be kept — and vice versa.)
For some filters, (e.g. `is`, or `greater than`), you have already implemented the opposite (e.g. `is not`, or `lower or equal than`). Yet I think having a checkbox would make it easier to extend the "negativation" to all types of filtering.

**Describe alternatives you've considered**
Well, it's difficult for "does not start with 'A'". I'm not sure it's possible to say "start with B, or start with C, or start with D, or start with E, …". And won't be feasible anyway if I want to select all records bet the ones starting with "BÉPO"

**How important is this feature to you?**
It prevents me to do some analysis on my data.

**Comment by flamber** [comment]
Hi @EBoisseauSierra 
Sounds like a duplicate of #7402. I kinda like the concept of using a checkbox to make it negative of what the selection is, and it would mean less options to display, but might be more difficult to understand.

**Comment by EBoisseauSierra** [comment]
Yes it's a dup, in this particular instance (⇒ closing this Issue). 
Yet I think that a global "not" (or, in English, "all but…" works quite well as well) — for either text, number, or categorical columns — could be more generic and useful, than keep expanding the list.
(Of couse, it's also because a `NOT operation` feels more natural in a "developer mindset".)
