### ISSUE TITLE
Formatting not always respecting Global formatting

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11394]
**Describe the bug**
There has been several questions/problems with how formatting is applied. Some of it could be documented better. But currently Global formatting is not applied unless the Field Type is `Creation/Cancellation/Deletion/Join timestamp`.
It's not specific to date/time, but also number formatting.

This means that Native/SQL questions always shows Default formatting (can be overruled by Question formatting).
Same goes for QB questions, where the Field Type isn't defined as `*** timestamp` (can be overruled by Question formatting).

Another trickery thing. When Global formatting is applied, and when seeing the column formatting in Data Model, but where Field Type is i.e. `No special type`, then it shows Default formatting.

These are the levels of formatting, as I understand - [documentation only lists 3](https://www.metabase.com/docs/latest/administration-guide/19-formatting-settings.html):
1. Default/fall-back (US-style generally, but this is at code-level)
2. Global: Admin > Settings > Formatting
3. Model: Admin > Data Model > (database) > (table) > (column) :gear: > Formatting
4. Question: visualization Settings > Data > (column) :gear: > Formatting
5. Card: hover dashboard card and click :gear: > Formatting

**To Reproduce**
1. Admin > Settings > Formatting > set to `2018-1-7` and `24h-style`
2. Admin > Data Model > Sample Dataset > Orders > Created At :gear: > set Field Type to `No special type`, and check Formatting side menu, which shows Default formatting
   1. Simple question > Sample Dataset > Orders, shows "Created At" with Default formatting (can be overruled by Model and Question formatting)
   2. Native question > Sample Dataset > `SELECT * FROM ORDERS`, shows Default formatting (can be overruled by Question formatting)
3. Revert Field Type to `Creation timestamp`, and check Formatting side menu, which shows Global formatting
   1. Simple question > Sample Dataset > Orders, shows "Created At" with Global formatting
   2. Native question > Sample Dataset > `SELECT * FROM ORDERS`, shows Default formatting (can be overruled by Question formatting)

**Expected behavior**
Always respect Global formatting.

**Information about your Metabase Installation:**
Metabase 0.33.6 and master on different backends and various browsers.

**Severity**
If you're not used to US-style formatting, then this is just as difficult to understand as feet/meters or Fahrenheit/Celsius.

**Additional context**
Related to #5859, #7447, #7494, #9079, #10787, #10856, #11398, #11426

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by bevanbennett** [comment]
The inability of most queries to respect global formatting is killing us.

**Comment by rthouvenin** [comment]
I don't know if this is the same issue or just related, let me know if I should open a new one: 

After changing the global date and number formatting, many values still display with the old format. I think this is because the formatting set at column level when the schema was imported is not reset (even though I didn't change any of them and would like the global to still apply).

For example, assuming the Global formatting is set to Default, I import the sample dataset and change the Global formatting to something else. Then going to `Admin > Data Model > Sample Dataset > Orders > Created At > Formatting` will still show the Default formatting, and this is what I will see when I browse data and in questions.

I would expect that columns that use the global formatting setting still do so after changing it.
If the formatting is stored in column settings during import (as opposed to storing empty value to mean use the global), then the new formatting could be propagated to all columns that use the old formatting.

**Comment by flamber** [comment]
@rthouvenin That sounds like cache - try reloading the browser. You'll see a reload-icon next to a setting if it has been set and is different from it's parent.

**Comment by rthouvenin** [comment]
@flamber Thought of it, but does not seem so. Browsing with cache disabled still shows the old formatting settings, and there is no reload-icon. I also tried to run a schema analysis after changing the formatting settings. You don't reproduce this behaviour?

**Comment by flamber** [comment]
@rthouvenin 
Formatting is not set on the columns in Data Model unless set manually (or that's how it should be) - same goes for questions and dashboard cards (3, 4 and 5 of list in the original post).
Data Model is stored in `metabase_field.setting`.
Questions in `report_card.visualization_settings[column_settings]`.
Dashboard cards in `report_dashboard_card.visualization_settings[column_settings]`.

I've just spun up a new instance just with Sample Dataset, where I changed all Global formatting.
I then checked Data Model, which correctly show the changes.
Then I changed Global back to default, and check Data Model, which correctly reverted the settings (to follow what I set in Global), when I refreshed the browser.

Can you check your application database to see if the formatting is stored already. It might be a problem from earlier versions passed on, but it's not the behavior anymore (as far as I can see).

Check the forum link, you'll see what you're saying and what the forum poster wrote are similar. But it's not something I've been able to reproduce - if you can help here, I would appreciate it :+1:
And likely should get it's own issue, since I created this as a meta-issue with explanation and details.

**Comment by rthouvenin** [comment]
I opened #12664 to continue the discussion and give my latest findings

**Comment by semaperepelitsa** [comment]
I wish Metabase would use the international date time format by default "2020-07-09 20:00:00" just like all the database systems (Postgres, MySQL, etc). Custom formatting would be a much less important issue then.

**Comment by flamber** [comment]
@semaperepelitsa It has nothing to do with this issue, but there's a request for it - #9539 - upvote by clicking :+1:

**Comment by flamber** [comment]
This has been fixed across multiple versions ranging from 0.35 to 0.39. Cannot reproduce on latest release 0.39.4. Closing.
Tests will be created to ensure correct behavior going forward.
There are still some specific issues open, where localized formatting isn't applied.
