### ISSUE TITLE
Enhancements to Full App Embedding Docs

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#11399]
* It would be helpful if we also link to how to do an SSO endpoint (link to example) where we say you need it and in general link to setting up SSO. 
In an ideal world there would be some (visual) schema or some such explaining the entire SSO workflow for people who've never worked with that before. 

* Mention serialization under deployment considerations or some such, as else the pre-made dashboards are awkward state you carry around in a DB (or dump thereof), but from an app-developer perspective I'd definitely like the workflow for making & tweaking my dashboards be closer to how I do the rest of my development.

**Comment by sbelak** [comment]
Also the example app (https://github.com/metabase/sso-examples/tree/master/app-embed-example) is nice and helpful, but I feel it's too cute/trying to do too much. In being end-2-end including the docker image it somewhat obscures what's necessary & sufficient to embed and what's incidental complexity.

**Comment by albertoperdomo** [comment]
We've shipped a new Quickstart that includes SSO w/ JWT: https://www.metabase.com/learn/customer-facing-analytics/interactive-embedding-quick-start

We've got a new basic sample for Node.js as a companion for the Quickstart that is much simpler and does not depend on Docker: https://github.com/metabase/metabase-nodejs-express-interactive-embedding-sample

We've also shipped a guide for git workflows using our updated serialization feature: https://www.metabase.com/learn/administration/git-based-workflow

Closing.
