### ISSUE TITLE
Add Bitcoin as a unit of currency

### ISSUE THREAD

**Issue by maxmalysh** [metabase/metabase#11406]
Hi,

We use Metabase in a cryptocurrency company. It's a pity that Metabase doesn't support Bitcoin as a unit of currency. 

Bitcoin is far more popular than all the minor currencies like Ethiopian Birr or Cape Verdian Escudo. Some of the supported currencies don't even exist anymore (e.g. Estonian Kroon).

Please add Bitcoin!  :)

Code: BTC
Symbol: BTC
Name: Bitcoin

**Comment by flamber** [comment]
Fixed in #15167
