### ISSUE TITLE
mongo.metabase-driver.jar. Build failed.

### ISSUE THREAD

**Issue by samcaicn** [metabase/metabase#11404]
Error: could not find /opt/mtitleyuanma/modules/drivers/mongo/target/uberjar/mongo.metabase-driver.jar. Build failed.
Failed to build driver mongo.

**Comment by flamber** [comment]
Hi @samcaicn 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Without providing more details, it's going to be impossible to help.
Please close this issue :+1:
