### ISSUE TITLE
Random text popping into pulse data.

### ISSUE THREAD

**Issue by Saura1996** [metabase/metabase#11405]
**Describe the bug**
Random text is appearing in pulse data table whenever the pulse is triggered. (I have attached screenshot regarding same)
You can see in the screenshot 'this' appears from nowhere and concats with the number in the data table. 

**Screenshots**
![image](https://user-images.githubusercontent.com/39013839/69806491-f9e82380-1208-11ea-83a3-eeb9574798be.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 70.0.1
- Your operating system: Ubuntu 18.04
- Your databases: Postgres
- Metabase version: ( v0.33.0-snapshot)
- Metabase internal database: (PostgreSQL)

**Comment by flamber** [comment]
Hi @Saura1996 
Are you also seeing this problem on latest release 0.33.6?
Which commit/hash is your `v0.33.0-snapshot`?

**Comment by Saura1996** [comment]
Thanks. Works fine on the updated release.
