### ISSUE TITLE
Proposal. Dashboards code, Question code. Posisibility to have a "manual" code to identify a dashboard (o question) (for easy manage embedded dashboard between test/preproduction, production environments)

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#11408]
**Describe the solution you'd like**
Proposal. Dashboards code, Question code. Posisibility to have a NEW "manual code" to identify a dashboard (o question) (for easy manage embedded dashboard between test/preproduction, production environments).
It means it will be the same "new manual code" for every environment.
Then it will be the "code" (manage by users)  for a dashboard (or question) for a "same" dashboard between environments.
It means, the api has to support the way a dashboard is embedeed (through a "standard code" (sequencial id), or through this "new code". And metabase has to control to not repeat the "new code" (could be always with a prefix )

**Describe alternatives you've considered**
Other options:
- Possibility to change the code of a dashboard or question. Metabase has to control the secuence of others...
- Possibility to copy dashboards or questions between environments...

**How important is this feature to you?**
It will simplify management between environments.

**Comment by flamber** [comment]
Hi @jlisyc 
By "code", I'm guessing you mean `ID`. Related to #8657 and #9441.

**Comment by jlisyc** [comment]
More like 9441
"code" could be ID but not really.
Example. I have a dashboard named "Issues by month". In test environment the ID of that dashbhoard is 55 for example. But the same dashboard in production has an ID 23 (we can not control de sequence of IDs).

When a call for them to embed it ... Instead to use 55 for pre and 23 for pro, I would like to call just by some "code"  , the same "code" for prediction and foro production), for example "D-101"

**Comment by mazameli** [comment]
Closing this as it seems quite close to #9441, and the alternative solution proposed, "Possibility to copy dashboards or questions between environments," is [possible in the enterprise edition](https://www.metabase.com/docs/latest/enterprise-guide/serialization.html).
