### ISSUE TITLE
Metabase FAQ web page needs to be updated

### ISSUE THREAD

**Issue by ethanbienstock** [metabase/metabase#11413]
**The FAQ page on the Metabase web page still states joins are NOT supported**

Joins have been included as of version 0.33 which is indicated at https://github.com/metabase/metabase/blob/master/docs/faq.md

The FAQ page at https://www.metabase.com/faq/ states Joins are NOT supported. Site needs to be updated. 

![image](https://user-images.githubusercontent.com/27466680/69880568-3d3da300-1298-11ea-933c-60e25935437d.png)

vs. 

![image](https://user-images.githubusercontent.com/27466680/69880601-58101780-1298-11ea-8c9a-8d34c7854512.png)

**Comment by flamber** [comment]
Good eagle eyes :+1: 

Actually https://www.metabase.com/faq/ should redirect to https://www.metabase.com/docs/latest/faq/start.html
And https://github.com/metabase/metabase/blob/master/docs/faq.md should have a "This page has been moved [link]" (similar to [old SAML doc](https://github.com/metabase/metabase/blob/master/docs/administration-guide/16-authenticating-with-saml.md))

There's an updated joins faq: https://www.metabase.com/docs/latest/faq/using-metabase/how-do-i-answer-questions-with-joins.html
