### ISSUE TITLE
Deleted schemas in PostgreSQL remain present in the UI

### ISSUE THREAD

**Issue by calz1** [metabase/metabase#11415]
**Describe the bug**
Deleted schemas on the database are still present.

**To Reproduce**
1. Have multiple schemas in your PostgreSQL DB.
2. Delete one called "import"
3. Run the sync on the database.
4. Go to browse data, then click on your database.
4. The deleted schema is still visible as is the real one. Clicking on the deleted schema takes you to a screen that says "Not found"

**Expected behavior**
When a schema is deleted, it should no longer show in the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/25329703/69889717-830e6180-12c0-11ea-987f-a0e79f7aef21.png)

**Severity**
The system isn't down but a lot of people click it and then wonder why it is empty.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.2+7-LTS",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "11.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.2+7-LTS",
    "os.name": "Linux",
    "os.version": "4.14.146-119.123.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-09-20",
      "tag": "v0.33.3",
      "branch": "release-0.33.x",
      "hash": "86d32bf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @calz1 
What happens if you refresh the browser, when viewing the list of schemas under Browse Data?
Looks like a duplicate of #9781 - if you agree, then please close this and upvote the other issue :+1: 
By the way, latest release is 0.33.6 - not that I remember any sync fixes between your version.

**Comment by calz1** [comment]
@flamber 

Refreshing the browser, and Ctrl+F5 don't seem to help. I even tried it in another browser I've never used Metabase in and it is still there :( 

I think you are right 9781 is the same one, I will close this.
