### ISSUE TITLE
High CPU load while editing a dashboard.

### ISSUE THREAD

**Issue by mfific-panagenda** [metabase/metabase#11410]
**Describe the bug**
Editing a Dashboard at certain Window sizes causes a high-cpu load and makes Metabase unusable.

**Logs**
dev tool console error:
too much recursion vendor.bundle.js:1:1
    _updateDOMProperties https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateRenderedComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _performComponentUpdate https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateRenderedComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _performComponentUpdate https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _reconcilerUpdateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateDOMChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _reconcilerUpdateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateDOMChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateRenderedComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _performComponentUpdate https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateRenderedComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _performComponentUpdate https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _reconcilerUpdateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateDOMChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _reconcilerUpdateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateDOMChildren https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    receiveComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _updateRenderedComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    _performComponentUpdate https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    updateComponent https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    performUpdateIfNecessary https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    performUpdateIfNecessary https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    b https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    perform https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    M https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    close https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1
    closeAll https://ifa-dev-02.panagenda.local/metabase/app/dist/vendor.bundle.js?d1dced319abf1b617b66:1

**To Reproduce**
1. Open a Dashboard
2. Click on Edit Dashboard
3. Click on the cog wheel to start editing a Report Card
   (our card contained a pie chart with a legend)
   Show Legend needs to be enabled
4. Resize Browser Window to 1920x1200 
5. Click on Show Percentages in Legend

alternatively: open dev tools and start resizing the browser screen. When the browser screen reaches the height of 1200px (somethings a bit higher or lover) you should see a "too much recursion" error in the dev tools console 

**Expected behavior**
Better performance

**Screenshots**
i have recorded a video of the behaviour.
you can see the delay between hovering of the pie chart and the tooltip being display.
and also the delay between clicking on "Show Percentages in Legend" and the legend being updated

[k20. User Activity Overview (Focus DBs) · Dashboard · Metabase - Mozilla Firefox 2019-11-29 09-37-49.zip](https://github.com/metabase/metabase/files/3904425/k20.User.Activity.Overview.Focus.DBs.Dashboard.Metabase.-.Mozilla.Firefox.2019-11-29.09-37-49.zip)

**Information about your Metabase Installation:**
0.33.6

You can get this information by going to Admin -> Troubleshooting.
Firefox 70.0.1 (64bit)
Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Severity**
Highly annoying, since editing dashboards becomes unusable at a certain (usualy around 1920x1200) resolution

**Comment by flamber** [comment]
Hi @mfific-panagenda 
Sounds like a duplicate of #11122, which has been fixed by #11393 and will be part of next release.
I think on Chrome the error is `Maximum call stack size exceeded` instead of `too much recursion`

**Comment by mfific-panagenda** [comment]
thanks for the info @flamber 
I'll close this and reopen if the issue still occurs in the next release
