### ISSUE TITLE
Slovak name of month even when set to English in Firefox

### ISSUE THREAD

**Issue by atranel** [metabase/metabase#11418]
I have Metabase set to English, but in 0.33.6 I have in one dashboard filter to select month and year and instead of showing "October, 2019" it shows "október, 2019" in Firefox but not in Vivaldi. Similarly other months are in Slovak. Both browsers are set to Czech language.
This is Firefox:
![obrazek](https://user-images.githubusercontent.com/42370527/69951426-85a5cc80-14f5-11ea-8449-e6feb4967fe9.png)
This is Vivaldi:
![obrazek](https://user-images.githubusercontent.com/42370527/69951776-3318e000-14f6-11ea-92d8-99f7f3efb9e1.png)

**Comment by flamber** [comment]
Hi @atranel 
Currently Metabase uses the browser to determine interface language via the `Accept-Language` HTTP header. And your browser's interface language does not have to be the same as it's preferred content language. Goto your browser settings and search for "language".
The option in Admin > Settings > General only applies to emails, pulses and a few other things.
There's work being done to allow full control over the language in #8384 - upvote by clicking :+1: 
If that fixes your problem, then please close this issue.

**Comment by mazameli** [comment]
Expected behavior for now. Closing as such.
