### ISSUE TITLE
Review usage of locale-specific `lower-case` and `upper-case`

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#11424]
Since we've discovered that `str/lower-case` and `String.toLowerCase` do locale-specific conversions (e.g. "ID" → "ıd" in Turkish locale), we haven't really reviewed all our uses of `lower-case` and `upper-case` for possible locale induced bugs. We should do so at some point.

I think we should default to using `metabase.util/lower-case-en` and `metabase.util/upper-case-en` for all casing needs, except for strings that are meant for display.

The fact that we haven't had reports of any bugs due to this, probably means that it's not super high priority.

**Comment by ertugrulcetin** [comment]
@walterl Having problem with Turkish locale: https://github.com/metabase/metabase/issues/12171
