### ISSUE TITLE
Date formats are incorrect when day is less than 10 and date is in d/m/yyyy format

### ISSUE THREAD

**Issue by calvinthomas150** [metabase/metabase#11421]
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to any report containing dates
2. Set date format to d/m/yyyy format
3. Look at any date where the day part is less than 10
4. Notice this displays in m/d/yyyy format

**Expected behavior**
The format should correctly be d/m/yyyy regardless of the day being less than 10.

**Screenshots**

**Information about your Metabase Installation:**

- Your browser and the version: Chrome
- Your operating system: Centos 7
- Your databases: Postgres
- Metabase version: 0.33.6
- Metabase hosting environment: Jar file
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Medium severity, causes users to see incorrect results and can lead to incorrect analysis

**Additional context**
The results only display incorrectly on screen, if the report is downloaded then the issue is corrected.

**Comment by mazameli** [comment]
I wasn't able to reproduce this on master. I tried with both the sample dataset and with a postgres db. What is the underlying variable type for the date column you're looking at? Does this happen with all of your tables? What are the global formatting settings you have in the Admin panel in `/admin/settings/formatting`?

### Original settings
![image](https://user-images.githubusercontent.com/2223916/69999895-9ca4e880-150e-11ea-8663-c29c8000e43a.png)

### d/m/yyyy setting turned on
Notice for example that row 3 is correctly displaying `6/12/2019` for Dec 12 2019.

![image](https://user-images.githubusercontent.com/2223916/70000012-e2fa4780-150e-11ea-9b19-39f04ec768c8.png)

**Comment by calvinthomas150** [comment]
Thanks for the reply and thoughts - I've managed to resolve this now by changing the column type from 'Creation Date' to no special type within the data model section, so it seems this problem may only occur when using the special types. Apologies for the confusing information.

**Comment by flamber** [comment]
Sounds like what I have described in #11394 - along with other general issues about formatting.
If you think my issue also covers your issue, then please close this and upvote the other issue :+1:

**Comment by calvinthomas150** [comment]
Closing as covered by #11394
