### ISSUE TITLE
Time display in Tooltip/ticks is broken for timeseries charts

### ISSUE THREAD

**Issue by ckc4823** [metabase/metabase#11435]
Display of time in tooltips of timeseries charts has been missing/broken since 0.33.1 

![image](https://user-images.githubusercontent.com/27238218/70083957-62ede380-15db-11ea-8b60-4ff4a5266b8b.png)

- Metabase jar file on Win10
- Postgres 12.1
- Chrome 78.0.3904.108 (Official Build) (64-bit)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Reproduced on `master`, but only Native/SQL question. Have a feeling it's related to #11394.
- Simple question > Sample Dataset > Orders
- Filter CreatedAt=CurrentDay
- Change visualization to Line, set X-axis=CreatedAt, Y-axis=Total
- Check CreatedAt :gear:, set time to "HH:MM:SS:MS"
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/70100386-2a5c0300-15f7-11ea-92aa-ff40ba1c6518.png)
- Click Editor (top-right) > SQL-icon (Convert to SQL)
![Screenshot_00001](https://user-images.githubusercontent.com/1447303/70100434-52e3fd00-15f7-11ea-8cc0-d368572a8a37.png)

**Comment by jens-totemic** [comment]
Is there any known workaround for this?

**Comment by flamber** [comment]
@jens-totemic Casting as text is currently the only workaround.

**Comment by jens-totemic** [comment]
Thanks @flamber. I applied casting to my sample from #18956 and I still get the same result:

```
WITH test(ts, v) AS (VALUES
	('2021-11-11 13:00:56Z'::timestamptz, 6),
	('2021-11-11 15:11:43Z'::timestamptz, 5),
	('2021-11-11 17:22:35Z'::timestamptz, 4),
	('2021-11-11 19:33:22Z'::timestamptz, 6),
	('2021-11-11 21:44:19Z'::timestamptz, 5),
	('2021-11-11 23:55:02Z'::timestamptz, 4)
)
SELECT cast(ts as text), v
FROM test
```

The output in the tooltip is still without time (same also in the x-axis label).

**Comment by flamber** [comment]
@jens-totemic Sorry, you'll need to format the date yourself, so the frontend does not understand it's a date and tries to do it's magic.

**Comment by jens-totemic** [comment]
Ok, got it. The problem unfortunately is that this specific column is the one needed as the x-axis in the visualization. So pretty much any time series display will be affected by this.

**Comment by jens-totemic** [comment]
Using some more info from #12370, here's a somewhat contrived way to display the data at least on a minute level resolution with both the tooltip and x-axis showing proper numbers.

What makes this contrived is that if Metabase sees multiple values for the same exact minute, it will add them up in the graph - which is not what we needed. Our regular dataset will never have more than one value for each timestamp but now that we group all of them together into the same minute, it can happen. To fix this, we are just picking exactly one value to visualize for each given minute. So it might be only a 50% workaround depending on the use case but sharing here since it allowed us to keep going.
 
```
WITH test(ts, v) AS (VALUES
	('2021-11-11 13:00:15Z'::timestamptz, 6),
	('2021-11-11 13:00:56Z'::timestamptz, 5),
	('2021-11-11 15:11:43Z'::timestamptz, 5),
	('2021-11-11 17:22:35Z'::timestamptz, 4),
	('2021-11-11 19:33:22Z'::timestamptz, 6),
	('2021-11-11 21:44:19Z'::timestamptz, 5),
	('2021-11-11 23:55:02Z'::timestamptz, 4)
)
SELECT DISTINCT ON (ts) ts, v
FROM (
  SELECT date_trunc('minute', ts) AS ts, v
  FROM test
) AS test2
ORDER BY ts, v DESC
```

**Comment by flamber** [comment]
@jens-totemic Metabase has several feature requests open about second-handling. It has not really been the main use-case.
If you define "X-axis scale"=Ordinal, then it won't try to merge things together:
![image](https://user-images.githubusercontent.com/1447303/141612576-737f839f-f5c7-43ce-b04e-a73e54bee71b.png)

**Comment by jens-totemic** [comment]
Thanks @flamber When using the Ordinal display each entry is equally spaced apart on the screen, no matter if they are just seconds or hours away from each other. The screenshot above illustrates this well. For actual time series data this is not desirable as the time relationship would need to be kept on the graph.

**Comment by ckc4823** [comment]
Thanks @jens-totemic for the DISTINCT ON workaround!  This issue has been a thorn in my side for years.
