### ISSUE TITLE
Parse-Server Database Foreign Key Relationship mapping for other collection

### ISSUE THREAD

**Issue by Code-Crash** [metabase/metabase#11431]
Hi Team,

I'm using Parse-Server library for my application, and want to use `metabase` for reporting purpose.

I want to tell `metabase` about relationship among different collections on Parse-Server database (which is MongoDb).

Example as Below:

Collections:

1. _User: Primary is _id
2. Company: Primary is _id

Relationship Identity is _User has _p_company field which has values like `Company$<id of Company>` as foreign key reference.

I need to enable joins on _User and Company, base on this foreign key reference, which  metbase would not allow as there is a 'Company' as prefix to the company id.

Example:

_User Collection: 
_id: 123
username: foo
_p_company: Company$bar

Company Collection:
_id: bar
name: Demo Company.

is there any ways to tell metabase that's there is prefix for foreign key in the _User?

Thanks in Advanced.

**Comment by mazameli** [comment]
Hey, @Code-Crash. You might have more luck troubleshooting something like this on our [discussion forum](https://discourse.metabase.com/). Cheers.

**Comment by Code-Crash** [comment]
Sure @mazameli , Thanks, I will start the same thread in the forum.
