### ISSUE TITLE
Cannot choose granularity of dates on Summarize with Simple question from Saved Question

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11439]
**Describe the bug**
The sub-options grouping (binning or bucket?) for date columns, when using a nested question, is only available in Editor/Notebook's Summarize, but not in Simple Summarize.

**To Reproduce**
1. Simple question > Sample Dataset > Orders, and save (could also be SQL)
2. Simple question > Saved Questions > (select step 1 question)
3. Click Summarize and hover Created At, notice the missing sub grouping
4. Click Editor > Summarize and hover Created At, notice the missing default "by month", select grouping manually to "Month", and Visualize
5. It's now possible to change the grouping in Simple Summarize

**Screenshots**
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/70154782-acd7d780-1676-11ea-9b96-9a0b23df8adf.png) 
![Screenshot_00002](https://user-images.githubusercontent.com/1447303/70154880-e27cc080-1676-11ea-8a9e-ca686fc8b178.png)

**Information about your Metabase Installation:**
Metabase 0.33.5.1 and `master`

**Additional context**
Reported in comment: https://github.com/metabase/metabase/issues/6100#issuecomment-561583858
EDIT: I was sure that I had reported this before, but just forgot the name "granularity". This is a reappearance of #10441.

**Comment by mazameli** [comment]
This is a regression of #10441, so we should make sure to add a test around this when fixing it again if we didn't the first time.

**Comment by camsaul** [comment]
Fixed by #14695
