### ISSUE TITLE
是否支持跨数据的图表配置？

### ISSUE THREAD

**Issue by blangeblue** [metabase/metabase#11434]
For help with installation and setup, information on how specific features work, or general questions about Metabase, please use our discussion forum:

https://discourse.metabase.com

The Github issue tracker is intended to collect bug reports and feature requests.
Any issues open for help requests will be closed to keep from clogging up the issue tracker.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And provide more information, and if possible write in English.
Please close this issue :+1:
