### ISSUE TITLE
Create api developer docs on www

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#11440]
For Metabase users that want to integrate with our API, we should create a set of docs on metabase.com/docs

Right now the developer guide is for folks that want to make modifications to the app, rather than integrate with it.

https://github.com/metabase/metabase/wiki/Using-the-REST-API would be a good starting point. As part of this we should also organize our wiki https://github.com/metabase/metabase/wiki as it's not clear what should be there vs on the website.

**Comment by jeff-bruemmer** [comment]
@salsakran: I'm closing this issue, as we did our [guide to the API on learn](https://www.metabase.com/learn/administration/metabase-api) that closed a similar issue that Damon created. Feel free to reopen this issue if you had something else in mind. We'll tackle the larger issue of migrating the developer wiki to the docs elsewhere.
