### ISSUE TITLE
Can't scroll while loading the data

### ISSUE THREAD

**Issue by jeromemmiranda** [metabase/metabase#11456]
**Describe the bug**
In the dashboard view, while loading the data, you can't do anytime like scroll.

**Logs**
N/A

**To Reproduce**
Just go to a specific dashboard.

**Expected behavior**
Should be able to do other things like, scroll, click the filters, or interact with the charts

**Screenshots**
N/A

**Severity**
Users being annoyed.

**Additional context**
N/A

**Comment by flamber** [comment]
Hi @jeromemmiranda 
It would be helpful if you provided more information as requested, like "Diagnostic Info" and browser console logs. Also the amount of charts and what type they are.
I cannot reproduce your issue on 0.33.6 with Firefox 70 on a laptop from 2011:
![Screencast 2019-12-05 21 14 04](https://user-images.githubusercontent.com/1447303/70292596-3afdac00-17a4-11ea-8e72-9616293dd53b.gif)

**Comment by jeromemmiranda** [comment]
@flamber thank you, actually I was able to fix it by just upgrading the version. Default version of metabase in digital ocean is 0.32.10. Closing this ticket now.
