### ISSUE TITLE
Avoid timeouts when downloading the results of a query

### ISSUE THREAD

**Issue by CyrilVinot** [metabase/metabase#11463]
**Is your feature request related to a problem? Please describe.**

When trying to download the result of a query as a csv, xls or json file, the **download request will time out if the query is too long to execute. This is quite frustrating when the result of the query isn't more than a few thousands of lines**

On our specific context : we are using Heroku and it triggers a timeout [if the request takes longer than 30sec](https://devcenter.heroku.com/articles/error-codes#h12-request-timeout) which makes sense.

**Describe the solution you'd like**

Either use async or a caching mechanism on the data to avoid such timeouts related to the execution time of the request

**How important is this feature to you?**

Since we have several queries than can take more than the 30sec limit, this currently prevents the end-users of Metabase that don't have an eng. background from downloading the results all by themselves (~100 ppl)

**Context**

A similar issue has been already vaguely reported [here](https://github.com/metabase/metabase/issues/9533) and [here](https://github.com/metabase/metabase/issues/8616) already and is somewhat related to [that one](https://github.com/metabase/metabase/issues/10566) (related to the UX when downloading)

**Thank you Metabase team!**

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tiwariayush** [comment]
Hi, thanks for adding this issue. Would be quite helpful in our case also. You mention:

> Since we have several queries than can take more than the 30sec limit, this currently prevents the end-users of Metabase that don't have an eng. background from downloading the results all by themselves (~100 ppl)

@CyrilVinot : What are the options for people with eng. background to download these reults which take more than 30sec ? Thanks beforehand.

**Comment by CyrilVinot** [comment]
>What are the options for people with eng. background to download these reults which take more than 30sec ?

Don't go through Metabase ! (connect to the DB, execute the query and retrieve the data...)

**Comment by dayjobtitus** [comment]
I too would like this issue resolved and using another tool outside of Metabase defeated the purpose it was meant to serve and eliminate more services and the need for engineering.

**Comment by paoliniluis** [comment]
As we no longer support Heroku due to limitations like this one, I'll proceed to close it and open new issues like configurable query-timeout-ms
