### ISSUE TITLE
How do I connect to use spark?

### ISSUE THREAD

**Issue by dt1018614769** [metabase/metabase#11460]
Hi,
I'm a green hand  But I want to connect sparksql with metabase   ，I can use the command "sparksql" on the server，Using metabase requires entering a user name and password，What do usernames and passwords refer to？   think you，I look forward to your help！

**Comment by flamber** [comment]
Hi @dt1018614769 
I don't know Spark, but that would be the credentials of the database you're connecting to.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:

**Comment by RedwanAlkurdi** [comment]
Spark SQL refers to spark Thrift server, which does not provide a username and password capability. therefore, the two fields should not be required. Moreover, the spark thrift server is usually connected to hive metastore which also does not provide the functionality of a username and password. both of these technologies (i.e., spark, hive) use Kerberos only.
