### ISSUE TITLE
Average over integer column produces integer result (not double/decimal as expected)

### ISSUE THREAD

**Issue by ZlobnyiSerg** [metabase/metabase#11488]
**Describe the bug**
I've had a task to calculate average stay in hotel. We have int column for earch reservation where integer number of stay duration is stored. I've made AVG aggregation over this column.

**Expected behavior**
I've expected that aggregation will produce decimal result, but average also was integer.

**Screenshots**
![image](https://user-images.githubusercontent.com/828963/70523981-3e52b800-1b55-11ea-880b-bd27e874fd82.png)

**Information about your Metabase Installation:**
- Metabase version: (e.x. 0.33.4)
- Metabase hosting - docker

**Comment by ZlobnyiSerg** [comment]
Workaround for these who may face the same problem: introduce new calculated column and add very subtle small decimal value to source value (ex. 0.00001 - it doesn't matter for stay duration). After that average on calculated column will product decimal result.

**Comment by sbelak** [comment]
We're already working on a fix for this bug in #11116 and hope to have it ready for the next release.

**Comment by Beau-Bristow** [comment]
It looks like this is still an issue as of v0.45.3.

I get around it using a custom expression: `average([int_column] * .1 * 10)`
