### ISSUE TITLE
Changing one parameter in native query builder changes all parameters

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#11484]
Confirmed that this is affecting `master` on stats.

1.  Click Ask a Question > Native
2.  Open Variables Pane, click `Help`
3.  Click the `Try It` button for the multiple optional clauses example (this is the second-to-last `Try It` example)
4.  Try to set each parameter independently. Good luck!

![wtf](https://user-images.githubusercontent.com/1455846/70486685-929f5e80-1aa7-11ea-9205-62c6e541b2ee.gif)

This doesn't seem to trigger in every query with multiple params, although it does trigger consistently when clicking the `Try It` button.

**Comment by mazameli** [comment]
I can only get this to happen when using those "Try it" buttons. If I use one of those try it buttons, then enter a value into the `Filter label` input box, this behavior in your example stops happening.

If I copy and paste the exact SQL generated from that "Try it" button (the one in your example) in a fresh sql query, this behavior doesn't happen.
