### ISSUE TITLE
SMTP password is stored in plaintext and can be accessed by admins (e.g. from the admin settings email page)

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1148]
We should probably never allow users to see previously set credentials, and possibly encrypt them somehow.

**Comment by camsaul** [comment]
One option always available to people is setting settings via env var, as mentioned in #3613. This is definitely the most secure since users will never get to see them at all and they'll never be saved in our database in any way, shape, or form.

Barring that we might want to add some new options to `defsetting` that prevent certain settings from coming back from the API endpoint, and perhaps even considering allowing an optional encryption key, similar to what's proposed for DB details in #865.

**Comment by salsakran** [comment]
I think modifying `defsetting` to make some keys as `write-only` makes the most sense. 

In-db encryption isn't a bad idea, and I'd guess that if we ever did #865 any settings that were `write-only` should also be protected.

**Comment by tlrobinson** [comment]
I looked into implementing this and it's slightly complicated but not a lot of work. I could probably do it but @camsaul could probably do it much faster and better. Here's what I suggest:

We could add a `secret?` option to settings, or just have a `:secret` type, since I think they will always be strings.

```clojure
(defsetting email-smtp-password
  (tru "SMTP password.")
  :type :secret)
```

Then we'd want the `GET /api/settings` endpoint to return dummy values like `•••••••` (maybe same length as actual value? or does that leak too much info?)

Then when we set a value, if it's a `:secret` setting and the value is `•••••••` (or whatever) then don't actually set the setting.

The slight complication is that we have some custom settings endpoints for email, Slack, etc that will need to be handled specially.

**Comment by tlrobinson** [comment]
Also we should remove the `GET /api/settings/:key` endpoint. I don't think we use it anyway, and it doesn't even return JSON like the rest of our endpoints.

**Comment by camsaul** [comment]
Fixed by #9451

**Comment by TMFRook** [comment]
SMTP Email password is still left unencrypted in the db. For reference, this is in 0.39.0.1. 

While it isn't being sent in any way to a client, this still is a security issue in case the database is breached (e.g. SQLi). Can we look into encrypting the field somehow?

**Comment by flamber** [comment]
@TMFRook Encrypt data at rest: https://www.metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
Since you haven't enabled to from the beginning, then you'll need to re-save settings before they get encrypted.
