### ISSUE TITLE
Cannot add more than one foreign key columns if primary columns are removed

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#11499]
**Describe the bug**
Cannot add more than 1 foreign key column unless *all* primary key columns are visible.

**Logs**

***javascript console***
Of note are these two messages. They occur when I try to add a second column from the foreign key table. As noted in the repro below, I can add the "category" column, but when I try to add the "created_at" column I get the first error message. If I try to add "category" back again, I get the second error message.
```
app-main.bundle.js?fd220da862d7458722d7:5 Unknown column {name: "CATEGORY", enabled: true}
app-main.bundle.js?fd220da862d7458722d7:5 Unknown column {name: "CREATED_AT_2", enabled: true}
```

Full stack trace from the first error message:
```
app-main.bundle.js?fd220da862d7458722d7:5 Unknown column {name: "CATEGORY", enabled: true}
m @ app-main.bundle.js?fd220da862d7458722d7:5
t.syncTableColumnsToQuery @ app-main.bundle.js?fd220da862d7458722d7:5
value @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
c @ vendor.bundle.js?fd220da862d7458722d7:1
m._invoke @ vendor.bundle.js?fd220da862d7458722d7:1
e.<computed> @ vendor.bundle.js?fd220da862d7458722d7:1
r @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
dispatch @ vendor.bundle.js?fd220da862d7458722d7:1
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
c @ vendor.bundle.js?fd220da862d7458722d7:1
m._invoke @ vendor.bundle.js?fd220da862d7458722d7:1
e.<computed> @ vendor.bundle.js?fd220da862d7458722d7:1
r @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ app-main.bundle.js?fd220da862d7458722d7:5
(anonymous) @ vendor.bundle.js?fd220da862d7458722d7:1
n.handleChangeSettings @ app-main.bundle.js?fd220da862d7458722d7:5
c @ app-main.bundle.js?fd220da862d7458722d7:5
r.handleAddNewField @ app-main.bundle.js?fd220da862d7458722d7:5
onAdd @ app-main.bundle.js?fd220da862d7458722d7:5
onClick @ app-main.bundle.js?fd220da862d7458722d7:5
i @ vendor.bundle.js?fd220da862d7458722d7:1
s @ vendor.bundle.js?fd220da862d7458722d7:1
executeDispatchesInOrder @ vendor.bundle.js?fd220da862d7458722d7:1
h @ vendor.bundle.js?fd220da862d7458722d7:1
f @ vendor.bundle.js?fd220da862d7458722d7:1
e.exports @ vendor.bundle.js?fd220da862d7458722d7:1
processEventQueue @ vendor.bundle.js?fd220da862d7458722d7:1
handleTopLevel @ vendor.bundle.js?fd220da862d7458722d7:1
f @ vendor.bundle.js?fd220da862d7458722d7:1
perform @ vendor.bundle.js?fd220da862d7458722d7:1
batchedUpdates @ vendor.bundle.js?fd220da862d7458722d7:1
batchedUpdates @ vendor.bundle.js?fd220da862d7458722d7:1
dispatchEvent @ vendor.bundle.js?fd220da862d7458722d7:1
Show 11 more frames
```

***Server logs***
Not much interesting...just one request when I try to add the column.
```
12-11 12:06:48 DEBUG middleware.log :: POST /api/dataset 200 [ASYNC: completed] 191.0 ms (18 DB calls) Jetty threads: 3/50 (2 idle, 0 queued) (61 total active threads) Queries in flight: 0
```

**To Reproduce**

Metabase version: Tested on 0.33.3 and 0.33.6. 0.32.10 did not have this issue.

1. Open the Sample Dataset in Metabase http://localhost:3000/browse/1
2. Click on the "Orders" table
3. Click on the "Settings button"
4. Remove a column from the primary table, e.g. "Total"
5. Under the "More columns" section, add the "Category" column from the "Products" table
6. Note that the list of columns is updated and the table refresh
7. Add another column from the "Products" table, e.g. "Created At"
8. Note an error in the javascript console and that "Category" is _replaced_ with "Created At" in the list of visible columns and the table refresh
9. Try to add other foreign key columns, even from other tables, and note that you can only ever add one additional foreign key column.

**Expected behavior**
I would expect to be able to add multiple foreign key columns to the list of visible columns, instead of only being able to add one.

**Screenshots**
![column selector with one foreign key column added](https://user-images.githubusercontent.com/1512/70657127-1f652c00-1c10-11ea-93ff-661df3fc8ef1.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "9.0.1+11",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "9.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "9.0.1+11",
    "os.name": "Mac OS X",
    "os.version": "10.14.6",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2019-09-20",
      "tag": "v0.33.3",
      "branch": "release-0.33.x",
      "hash": "86d32bf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Annoying in that I have to include all columns from the primary table to have >1 column from a foreign key table.

**Additional context**
n/a

**Comment by flamber** [comment]
Reproduced on `master` - but it works correctly on 0.32.10.
**Workaround:** Use Custom question (or Editor) and join the table and select the columns wanted, since it seems like the problem is only on linked tables.
