### ISSUE TITLE
Don't need to cast DATE columns with `date()`

### ISSUE THREAD

**Issue by sigismund** [metabase/metabase#11502]
**Bug description**
When segmenting by DATE column resulting SQL query uses date() function even though field is already DATE. This results in a quite slower query, specially if used column is indexed.

**To Reproduce**
1. Go to 'Admin > Data Model > Segment'
2. Create a segment on DATE column for last 30 days
3. Add filter
4. Create new question using newly created segment

**Expected behavior**
If column type is DATE there is no need to do another conversion.

**Information about your Metabase Installation:**
```
"metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Europe/Belgrade"
    }
  }
```
We are using MySQL 8.0.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Looks like #10980 didn't completely get rid of those `date()` wrappers (original issue #9139).
Reproduced on `master` with MariaDB-10.4 with an imported version of Sample Dataset:
```
SELECT count(*) AS `count`
FROM `PEOPLE`
WHERE date(`PEOPLE`.`BIRTH_DATE`) BETWEEN date(date_add(now(), INTERVAL -10000 day))
   AND date(date_add(now(), INTERVAL -1 day))
```
`BIRTH_DATE` column type `date` and field type "Creation Date"

**Comment by mazameli** [comment]
CC @camsaul

**Comment by jinfenggt** [comment]
Mysql date field filter using date function which seriously  affect the performance of sql query.
Any progress on this issue?

**Comment by sina-attarzadeh** [comment]
I have the same performance issue. Any changes suggested by "fingerprint" configuration?

Metabase version:0.35.2
MySQL version: 5.7.28

**Comment by ghomem** [comment]
I have the same performance issue with MariaDB 10.1.

**Comment by wjh000123** [comment]
Hi, @camsaul, I'm doubt whether this problem has been fixed or not, because I'm still facing this issue in the latest version (0.40.3.1, chrome v93) in custom query. Or did I miss some config?

**Comment by flamber** [comment]
@wjh000123 You need to provide more details. At a minimum the query you are seeing, the table schema and "Diagnostic Info" from Admin > Troubleshooting.
I'm seeing queries like this for `DATE` columns on 0.40.3.1 against MariaDB 10.4 - exactly what is expected:
```
SELECT
  count(*) AS `count` 
FROM
  `PEOPLE` 
WHERE
  (
    `PEOPLE`.`BIRTH_DATE` >= date(date_add(now(6), INTERVAL - 10000 day)) 
    AND `PEOPLE`.`BIRTH_DATE` < date(now(6))
  )
```

**Comment by wjh000123** [comment]
@flamber I have a simple table to store data, which has a field to store the time of data created, named `created_at`, the type in data model is `creation timestamp`.
For detailed info, please check the sreenshot, thanks.
![image](https://user-images.githubusercontent.com/4396063/131637538-4f2407d5-6a36-4beb-be94-9d7eae2c0ada.png)

Diagnostic Info:
```json {
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.18.0-305.3.1.el8.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.18"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-26",
      "tag": "v0.40.3.1",
      "branch": "release-x.40.x",
      "hash": "0550b86"
    },
    "settings": {
      "report-timezone": null
    }
  }
}```

**Comment by flamber** [comment]
@wjh000123 So you have a `DATETIME` or `TIMESTAMP` column, then Metabase does the correct thing by casting as `date()`

**Comment by wjh000123** [comment]
@flamber yes, then I created a new field, the type in mysql is date, and the type in metabase is `creation date`. But the behavior is still the same, what can I do then?
![image](https://user-images.githubusercontent.com/4396063/131639463-db7a5ad9-e3c5-4f2d-bd59-228d6bcdaa64.png)

**Comment by flamber** [comment]
@wjh000123 I have created an issue for it - #17711 - upvote by clicking :+1: on the first post

**Comment by caochangshan** [comment]
Mysql date field filter using date function which seriously affect the performance of sql query.
Any progress on this issue?  @flamber

**Comment by flamber** [comment]
@caochangshan There's an issue for it - #17711 - go and upvote and subscribe to that issue. There's no timeline.

**Comment by camsaul** [comment]
#17711 was fixed in #19759

**Comment by ghomem** [comment]
Amazing that this has been fixed. It will be a great product improvement. Any idea of the release where it will land? Thank you for the efforts.

**Comment by flamber** [comment]
@ghomem If you go to an issue (e.g. #17711), when it is closed, then it is fixed and will have a milestone attached in the sidebar. You can click the milestone to see the tentative release date.
