### ISSUE TITLE
Dashboard Filter based on another question

### ISSUE THREAD

**Issue by brow1998** [metabase/metabase#11505]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I develop a dashboard and try to use a question info as a filter, and make every other question filtered based on that first selection.

**Describe the solution you'd like**
Something like Tableau, you know? Where you can use a question as a filter and make it affect every question inside that dashboard who shares the same info.

**Describe alternatives you've considered**
I haven't found any alternatives to solve this inside Metabase. 

**How important is this feature to you?**
This would help our business a lot, making the dashboards even more intuitive.

**Comment by flamber** [comment]
Hi @brow1998 
I'm not sure what you mean by "use a question info as a filter"
For anyone that doesn't know Tableau, could you link or share a screenshot of the functionality?
It sounds like you're asking for #5540. If you agree, then please close this and upvote the other :+1:

**Comment by brow1998** [comment]
Hi @flamber !

I was thinking something like this:
https://public.tableau.com/pt-br/gallery/taste-america?tab=viz-of-the-day&type=viz-of-the-day

If you enter this dashboard, you can use the map as a filter, which makes the whole dashboard updates based on the country selected. 

#5540 seems like the thing I was looking for, but haven't found before. Closing here and upvoting there ;)
