### ISSUE TITLE
Missing Translation at modal on new user at question

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#11504]
When a new user first time at a question show this modal, it's a missing translation:
![Screenshot from 2019-12-11 19-30-53](https://user-images.githubusercontent.com/6808348/70666294-1b0b3400-1c4d-11ea-9ff1-f5d3d7705386.png)

I'm using the Portuguese language.

**Comment by dannyeuu** [comment]
@mazameli any updates here?

**Comment by dannyeuu** [comment]
@mazameli I saw that for v0.36.0 it has added a lot of phrases, this can be included. My time already did the translation for Portuguese =)

**Comment by mazameli** [comment]
@dannyeuu This actually looks like it's already fixed in master, which means I think the translation was already included in version 0.35:

![image](https://user-images.githubusercontent.com/2223916/86855765-e1c66580-c06f-11ea-91ad-800bdf555c82.png)

Closing as fixed.

**Comment by dannyeuu** [comment]
Cool @mazameli! German in progress here =) translations is our chance to contribute as BI users.
