### ISSUE TITLE
Keep today as date_to in between date filter type

### ISSUE THREAD

**Issue by jhettler** [metabase/metabase#11500]
**Is your feature request related to a problem? Please describe.**
When you choose the between type of date filter. You have to fill "date from" and "date to", but it would be nice to have "date to" as today date by default. It is annoying to jump for March date and then back to December if it is 12th of December and you want to filter March - December range.

**Describe the solution you'd like**
Above.

**Additional context**
Workaround is to fill any date to "date to" field and then delete it and then "Update filter" button is accessible and you don't have to scroll back to today date.

**Comment by flamber** [comment]
Related to #4585 and somewhat #4083.
