### ISSUE TITLE
No suitable driver found for jdbc:oracle

### ISSUE THREAD

**Issue by argnist** [metabase/metabase#11514]
**Describe the bug**
We can't create new source Oracle database for Metabase 0.33.6

**Logs**
{:valid false, :dbname "No suitable driver found for jdbc:oracle:thin:@**address**", :message "No suitable driver found for jdbc:oracle:thin:@**address**"}

**To Reproduce**
1. Add ojdbc8.jar to plugins directory
2. Restart metabase
3. Create new Oracle database

**Expected behavior**
Db should be created

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "3.10.0-957.5.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Moscow"
  },
  "metabase-info": {
    "databases": [
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Blocker of usage

**Additional context**
Metabase works fine for Clickhouse, but we need Oracle as the second source.

**Comment by flamber** [comment]
Hi @argnist 
Do you see any warnings/errors during startup (specifically the registration of drivers)?
Which version of ojdbc8.jar? And what's the SHA1-checksum?
Recommended version is [19.3](https://www.metabase.com/docs/latest/administration-guide/databases/oracle.html) and should be `SHA1: 967c0b1a2d5b1435324de34a9b8018d294f8f47b`, but note that Oracle says it's only certified with JDK8.

**Comment by camsaul** [comment]
@argnist @flamber any version of `ojdbc8.jar` or above from the last 2 or 3 years should work. Metabase v0.33.7.1 is working for me locally with the 19.3 `ojdbc10.jar` JDBC driver and OpenJDK 13.0. Here's my exact version info:

```shell
% shasum -a 256 plugins/ojdbc10.jar 
fa22689cd3fbb037f4ec864125ebe78325f3811fc50cf194c6bd70fe7e514568  plugins/ojdbc10.jar

% java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)
```

We also run tests with the 19.3 `ojdbc8.jar` against Java 8 and Java 11 so it should work without issue there as well.

**Comment by argnist** [comment]
Strange, but it works in local docker container on my machine:
`{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.9.184-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

Difference is only in os.version and application-database

**Comment by flamber** [comment]
@argnist 
Are you using the official Docker image or your own custom build?
What OS and version is the difference between the two setups?

**Comment by argnist** [comment]
Not working (I'll clarify what image with our DevOps):
"os.version": "3.10.0-957.5.1.el7.x86_64",
"application-database": "postgres",

Working (official Docker image):
"os.version": "4.9.184-linuxkit"
"application-database": "h2"

**Comment by flamber** [comment]
@argnist Sadly Java only returns the kernel version, so it doesn't tell which OS or version it is.

**Comment by argnist** [comment]
It seems Red Hat Enterprise Linux Server (v. 7)

**Comment by flamber** [comment]
@argnist The [official Metabase Docker image](https://hub.docker.com/r/metabase/metabase) for 0.33.6 uses AlpineLinux 3.9.4 kernel 5.0.0-37-generic, but perhaps you're running on AWS, which changes something and uses xxxx kernel 4.9.184-linuxkit?
I'm not sure if Metabase can check/do anything in regards to the "No suitable driver found", or if this is an environmental issue on the EL7. But it's great that you got it working one place.

**Comment by flamber** [comment]
Closing, since this was likely a specific environment issue. The closest other issue was #10475.
Before version 0.34.1, drivers might not correctly have been pushed to `plugins` directory on every startup, but that should have been reported in the log during startup if something failed there.
