### ISSUE TITLE
Google SSO login not working in Chrome

### ISSUE THREAD

**Issue by mcg** [metabase/metabase#11516]
- Metabase v0.33.5
- Chrome Version 79.0.3945.56 (Official Build) beta (64-bit)

**Describe the bug**
The issue looks similar to #9738. When attempting to login using Google SSO the login window will be displayed, login happens, window closes. Nothing happens on the parent login page. The result is not being able to login.

Reports of this are coming from users using `Chrome Version 79.0.3945.56 (Official Build) beta (64-bit)`, and the Chrome change that is causing this is slated to be out in Chrome Stable version 80.

Viewing the developer console, requests to `https://ourhost/api/user/current` are 401 and the following error:

> A cookie associated with a cross-site resource at https://accounts.google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Making the suggested Chrome flag changes does allow logins to work.

**Expected behavior**
Being able to login via Google SSO

**Severity**
Not high severity yet, but once this Chrome change is out of beta, it would be a complete blocker to our usage of Metabase.

**Comment by dannyeuu** [comment]
@mcg yesterday has a release  v.33.7.1 that has fixed this bug, did u tried to update?

**Comment by flamber** [comment]
@dannyeuu There will be a new release because of a couple of issues in 0.33.7.1 #11525

**Comment by mcg** [comment]
Have not updated to .33.7.1, but will update as soon as the fixes for it are released.

**Comment by mazameli** [comment]
Hmm, was not able to reproduce on `v0.34.0-snapshot` with Chrome `Version 79.0.3945.79 (Official Build) (64-bit)`

**Comment by mcg** [comment]
Updated to `0.33.7.3` and the problem is not fixed.

**Comment by mcg** [comment]
Setting  set chrome://flags/#same-site-by-default-cookies and chrome://flags/#enable-removing-all-third-party-cookies to disabled to `disabled` does workaround the issue. So it does appear to be related to SameSite cookie change.

**Comment by walterl** [comment]
I was able to reproduce the issue on Chromium Version 79.0.3945.79 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit), after enabling the _SameSite by default cookies_ flag in `chrome://flags`, as @mcg suggested.

As far as I can tell Metabase [always sets `SameSite=Lax`](https://github.com/metabase/metabase/blob/master/src/metabase/middleware/session.clj#L87) on its cookies.

This looks to me like an issue with cookies set by Google, and not Metabase. Even the error message in OP indicates that it's a cookie from accounts.google.com that was set without `SameSite`. In fact, if I clear all site data and just open a new tab (with the Google search box), I see such errors popping up for google.com and ogs.google.com.

I'm not sure what, if anything, we can do about this.

**Comment by mcg** [comment]
@walterl I guess Google may not have updated it’s OAuth endpoint for this. Can’t find anything documenting this specifically.  Not exactly sure of the OAuth login flow either, but Metabase setting `lax` may be part of the issue.

> To safeguard more websites and their users, the new secure-by-default model assumes all cookies should be protected from external access unless otherwise specified. Developers must use a new cookie setting, SameSite=None, to designate cookies for cross-site access. When the SameSite=None attribute is present, an additional Secure attribute must be used so cross-site cookies can only be accessed over HTTPS connections

> With Chrome 80 in February, Chrome will treat cookies that have no declared SameSite value as SameSite=Lax cookies. Only cookies with the SameSite=None; Secure setting will be available for external access, provided they are being accessed from secure connections

And then this caveat:

> Some browsers, including some versions of Chrome, Safari and UC Browser, might handle the  None value in unintended ways, requiring developers to code exceptions for those clients.

Via: https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

**Comment by walterl** [comment]
@mcg Thank you for the link and quotes. It was most clarifying.

However, I don't think that it changes anything from what I said before. The cookies in question are set by Google during authentication. Metabase therefore has no control over the options (e.g. `SameSite`) that it's set with. Furthermore, Metabase already setting the `SameSite` flag, should mean that its already handling cookies in line with this upcoming change.

**Comment by mcg** [comment]
@walterl  I'd like to place all the blame on google for this, but I've tried a bunch of other services that also use Google SSO in the same browser and they all work. Something is different(or broken) with Metabases usage of Google SSO.

**Comment by walterl** [comment]
@mcg Yeah. It's doesn't feel right to me either. If the issue really was with Google, the internet would've exploded by now :stuck_out_tongue_closed_eyes:. The bit of searching I've done yielded [this post](https://github.com/google/google-api-javascript-client/issues/561#issuecomment-564908497) (the whole thread, really), which describes the exact same issue, with no resolution yet.

What's alarming, though, is that those warnings are _everywhere_. With a clean Chromium profile, I got no less than 5 of them loading https://developers.google.com/identity/sign-in/web/sign-in. 6 if you count the one on the (Google search) home page.

**Comment by neontuna** [comment]
I'm not sure if this is related but our instance, on 0.33.7.3 is running into the same issues in Chrome.  

However in Firefox I get a different error - POST to https://my-heroku-instance/api/session/google_auth returns error 400, "Google Auth token meant for a different site."

**Comment by flamber** [comment]
@neontuna You're seeing a different problem, since this is specific to a future version of Chrome, so please open a new issue and provide all the information (preferably something that can be reproduced), or use the forum for troubleshooting: https://discourse.metabase.com/
More precisely, you're seeing an issue with specifically 0.33.7.x, which was a security fix for how Google Auth was handled in Metabase.

**Comment by cyhhao** [comment]
On 0.34.0 I also encountered this problem with the 400 error returned message: "Google Auth token meant for a different site."

**Comment by walterl** [comment]
@cyhhao That error message was added as part of a Google Auth bug that was fixed in [version 0.33.7.3](https://github.com/metabase/metabase/releases/tag/v0.33.7.3), and is unrelated to this issue.

The error message indicates that the Google Client ID configured in Metabase's settings is likely incorrect. Please make sure that your configured Google Client ID is correct, and open a new issue if it is.

**Comment by zvickery** [comment]
I was receiving the `Google Auth token meant for a different site` error when attempting to login.  It turns out the Google Client ID configuration was missing the `.apps.googleusercontent.com` suffix.  Apparently this worked with previous versions of Metabase but fails after the 0.33.7 changes.  After adding the suffix everything works great!

**Comment by vic4hub** [comment]
> I was receiving the `Google Auth token meant for a different site` error when attempting to login. It turns out the Google Client ID configuration was missing the `.apps.googleusercontent.com` suffix. Apparently this worked with previous versions of Metabase but fails after the 0.33.7 changes. After adding the suffix everything works great!

Hey @zvickery can you please elaborate your case as I am also in this predicament.

1. Are you using "Web application" or "Other" Type OAuth 2.0 Client ? (in https://console.developers.google.com/apis/credentials)
2. Where exactly would I need to add this suffix? (Metabase GUI?)

thanks in advance!

**Comment by walterl** [comment]
Hi @vic4hub,

>     1. Are you using "Web application" or "Other" Type OAuth 2.0 Client ? (in https://console.developers.google.com/apis/credentials)

_Web application_ is fine.
 
>     2. Where exactly would I need to add this suffix? (Metabase GUI?)

Yes, you need to ensure that the entire Google Client ID is set in Metabase's Google Sign-in settings. That includes the `.apps.googleusercontent.com` suffix, as it would be copied by clicking the copy icon in the Google API Console: 
![image](https://user-images.githubusercontent.com/23798/72182942-47090900-33f5-11ea-8ed2-0449f29be885.png)

**Comment by mcg** [comment]
Just for FYI, we do have the full Google Client ID configured. This issue isn't related to this misconfiguration.

**Comment by walterl** [comment]
@mcg Indeed. The invalid clietn ID is only related to the _Google Auth token meant for a different site_ error, and not the `SameSite` flag issue that this issue is really about.

I'm keeping an eye on the [this issue](https://github.com/google/google-api-javascript-client/issues/561#issuecomment-564908497) for a solution.

**Comment by vic4hub** [comment]
makes sense, thx guys

**Comment by walterl** [comment]
@mcg I just tried to reproduce this issue again, but was unable. I still see the same `SameSite` warnings in the JS console, but login succeeds. This is with a clean browser profile, and chrome://flags/#same-site-by-default-cookies enabled.

Browser: Chromium 79.0.3945.79 (Official Build)
Metabase version: Current `master`

**Comment by mcg** [comment]
Looks like Google updated it's cookies and this is fixed now. Still weird it was only happening in Metabase. Thanks for looking at this @walterl

**Comment by walterl** [comment]
@mcg Thanks for confirming! I share your sentiments, but just glad it's resolved.

**Comment by henpenben** [comment]
Experiencing this issue on Windows 10 `Version 10.0.18362 Build 18362`, in both Chrome `Version 79.0.3945.130 (64-bit)` and Firefox `Version 72.0.2 (64-bit)`.

**Comment by MaxGabriel** [comment]
I just ran into this on Chrome 84.0.4147.125 on Metabase v0.34.2. I get the same error as the OP:

> A cookie associated with a cross-site resource at https://accounts.google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
13:05:25.142

Logins work in Firefox/Safari. I'm not sure why this went away before. I know google was doing a steady roll-out of this, and I think delayed it b/c of coronavirus, but I think is ramping it up again now? https://www.chromestatus.com/feature/5088147346030592 says the rollout starts July 14, 2020

**Comment by flamber** [comment]
@MaxGabriel 
https://www.chromium.org/updates/same-site
It should already have been rolled out to 100% a month ago, and given the amount of installations with Google Auth and all their users, we should have seen a lot more reports.
Could it be a non-default setting or an extension that is causing problems for you?
Latest release is 0.36.4

**Comment by MaxGabriel** [comment]
Ok cool, I went to chrome://flags and turned that feature off, and still reproduced, so it must not be that. Also one of my coworkers couldn't reproduce. So, I think I'll just live with it for now. Thanks for the help debugging 👍

**Comment by josephtrinh** [comment]
I faced a similar issue with Google login with a number of new users recently but, in our case, it was those emails having upper and lower case mixed together after debugging with Metabase's log. Email is CASE-SENSITIVE in Metabase and, after fixing this, all users were able to login fine using Google for us. (On v0.36.7)

**Comment by flamber** [comment]
@josephtrinh Emails were case sensitive until 0.37.0 - #3047

**Comment by taurus227** [comment]
I'm a first time user, running the `metabase/metabase:v0.40.4` docker container.
I'm getting this `The window was closed before completing Google Authentication.` message on Chrome 93.0.4577.63 on Windows. My friend tried it on his machine, he doesn't get the error, he can log in with Google.

**Comment by joshfraser** [comment]
On my initial attempt, I missed the step about adding specifying the URI of my Metabase instance in the “Authorized JavaScript origins” section. I came back and added it, but still kept getting "The window was closed before completing Google Authentication." and a "Not valid origin for the client" in the developer console.

Nothing worked until I created fresh Credentials with the correct Javascript origin specified at the beginning. Might just be a caching issue, but documenting it here in case others run into the same issue.

**Comment by maricn** [comment]
I'm still experiencing this issue. I was able to log into metabase with SSO until Chromium updated to Version 91 and [removed the experimental samesite flag](https://support.google.com/chrome/thread/111426858/after-version-91-update-how-do-you-disable-samesite-cookie-options?hl=en).
Now I can't login from Chromium (+incognito) (currently at `97.0.4692.71`), nor from vanilla Google Chrome (+incognito) (currently at `97.0.4692.99`) nor from Firefox `96.0.1` on Arch Linux (I don't have Safari).

**Comment by flamber** [comment]
@maricn You're seeing a different problem. There's thousands of Metabase installations using Google Sign-in for all their users.
There has been posted quite a few different problems in this issue, which is completely different from the original.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
