### ISSUE TITLE
set Email success but  restore default settings soon

### ISSUE THREAD

**Issue by francisyan123** [metabase/metabase#11528]
hello everyone , I set Email with the Metabase Documentation,then I can receive "Metabase Test Email" successfully,but the Email setting will restore default settings soon.can anyone fix this problem?help me ,thanks a lot.

**Comment by flamber** [comment]
@francisyan123 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:

**Comment by francisyan123** [comment]
> @francisyan123
> Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
> And please close this issue

@flamber ok, thanks
