### ISSUE TITLE
Incorrect handling of minor versions in 'Check for update'

### ISSUE THREAD

**Issue by maxgashkov** [metabase/metabase#11527]
Admin area says that update is available when I'm running latest version:

'Metabase 0.33.7 is available. You're running 0.33.7.1'

**Comment by flamber** [comment]
Hi @maxgashkov 
Thanks for pointing it out. This happened because there was a build problem with 0.33.7, so 0.33.7.1 got released just an hour later. You can ignore the "downgrade" information.

**Comment by flamber** [comment]
@mazameli 
Shouldn't this be closed, since it was because version-info wasn't updated correctly? And 11535 too?
