### ISSUE TITLE
I cant find slack channel when create a pulse

### ISSUE THREAD

**Issue by masjaya19** [metabase/metabase#11523]
Dear Team,

Need your help, this first I use Metabase and create a pulse when I create the pulse and already follow the user guide > https://www.metabase.com/docs/latest/users-guide/10-pulses , I've some issue.

I already create bot slack with bot name: meta-base and I've filled the slack API token also and I've created the slack channel is metabase_files.

Right now I have some issue:

1. when I save the setting of slack in the admin panel, I have an error like this.
**https://data.sirogu.com/api/slack/settings 
error 500 > api.js:120** >>
```
{message: "slack.com: unknown error",…}
message: "slack.com: unknown error"
stacktrace: ["integrations.slack$do_slack_request.invokeStatic(slack.clj:32)",…]
0: "integrations.slack$do_slack_request.invokeStatic(slack.clj:32)"
1: "integrations.slack$do_slack_request.doInvoke(slack.clj:30)"
2: "api.slack$fn__43035$fn__43038$fn__43039.invoke(slack.clj:22)"
3: "api.slack$fn__43035$fn__43038.invoke(slack.clj:19)"
4: "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:248)"
5: "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:243)"
6: "api.slack$fn__43035.invokeStatic(slack.clj:11)"
7: "api.slack$fn__43035.invoke(slack.clj:11)"
8: "middleware$enforce_authentication$fn__31785.invoke(middleware.clj:122)"
9: "api.routes$fn__45034.invokeStatic(routes.clj:85)"
10: "api.routes$fn__45034.invoke(routes.clj:85)"
11: "routes$fn__45721$fn__45722.doInvoke(routes.clj:101)"
12: "routes$fn__45721.invokeStatic(routes.clj:97)"
13: "routes$fn__45721.invoke(routes.clj:97)"
14: "middleware$log_api_call$fn__31884$fn__31886.invoke(middleware.clj:330)"
15: "middleware$log_api_call$fn__31884.invoke(middleware.clj:329)"
16: "middleware$add_security_headers$fn__31834.invoke(middleware.clj:245)"
17: "middleware$bind_current_user$fn__31789.invoke(middleware.clj:142)"
18: "middleware$maybe_set_site_url$fn__31838.invoke(middleware.clj:268)"
```

2. When I create a pulse, I have an error in the console browser like this.
**240 Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' fonts.gstatic.com themes.googleusercontent.com ".**

**Error handling response: TypeError: Cannot read property 'state' of null
    at CSRecorder.onQueryStateCompleted (chrome-extension://cplklnmnlbnpmjogncfgfijoopmnlemp/content_scripts/recorder.js:106:18)**

**Failed to load resource: the server responded with a status of 500 ()**

I can't find the slack channel and I already create a pulse send to general as well but the pulse does not send to the #general channel.

<img width="891" alt="Error_pulse" src="https://user-images.githubusercontent.com/12791065/70847465-4d0fd680-1e97-11ea-8d22-47445227b82e.PNG">

<img width="877" alt="Error_pulse1" src="https://user-images.githubusercontent.com/12791065/70847581-89900200-1e98-11ea-91d1-3a8e7cda8394.PNG">

Thanks
Mas Jaya Sutarno

**Comment by flamber** [comment]
Hi @masjaya19 
The unknown error looks to be coming from Slack, not Metabase.
You might want to look into upgrading Metabase. You are running 0.27.2, which is 2 years old.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:

**Comment by masjaya19** [comment]
Ok, sure and thank you @flamber
