### ISSUE TITLE
Getting back from Admin panel is hard (UI)

### ISSUE THREAD

**Issue by ottomatias** [metabase/metabase#11529]
**Describe the bug**
The Admin part of the web UI doesn't have a way to go back to data/analytics part of the tool and the normal way of getting back to home, clicking the logo on top left, goes to Admin home, not the actual home

**To Reproduce**
1. Go to any page on Metabase (URL such as https://metabase.xx.com/question/68)
2. Click top left logo 
3. You'll see the front page of your Metabase installation
4. Go to your Metabase admin panel (URL such as metabase.xx.com/admin/)
5. Top left Metabase logo turns into text "Metabase Admin" and you can't go back to home without changing the URL manually

**Expected behavior**
Clicking top left **ALWAYS** goes back to Metabase home

**Screenshots**
<img width="930" alt="Näyttökuva 2019-12-16 kello 12 19 06" src="https://user-images.githubusercontent.com/2462500/70898907-48196700-1ffe-11ea-922c-b94a8300debd.png">

**Severity**
Annoying

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by rjbijl** [comment]
+1, for now, I go to 'Account Settings' through the menu and then clicking the top left logo. At least beats having to change the URL

**Comment by flamber** [comment]
If you click the gear-icon (:gear:) while in the Admin panel, you'll see an option called "Exit admin", which will return you to the home screen.
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/70971303-4d120100-2066-11ea-8fb0-bcf1c0e1a29b.png)

**Comment by mazameli** [comment]
Huh, thanks for this feedback — I was not aware folks were having trouble finding the `Exit admin` link. We'll take a look at improving this somehow.

**Comment by mazameli** [comment]
It would be simple enough to replace the current gear icon+text in the top-left with the Metabase logo in the same position and size as it is in the rest of the app and have it be a link back to the main homepage. If we did that, I still think we should keep the "Exit Admin" link in the top-right menu because of muscle memory and the fact that the way you _enter_ the admin panel is from that menu.

![image](https://user-images.githubusercontent.com/2223916/74177551-cd7c5a80-4bee-11ea-964c-c9a11e047d9e.png)

**Comment by xgdgsc** [comment]
I would be scared at first looking at "Exit..." (would that log me off?). Please fix this using the Metabase icon on top left to return as almost every such admin page does.

**Comment by flamber** [comment]
Fixed by #19304
