### ISSUE TITLE
[Feature Request] Show current count for a "Progress" Visualization

### ISSUE THREAD

**Issue by SirWellington** [metabase/metabase#11530]
**Is your feature request related to a problem? Please describe.**
When editing a "Progress" visualization in the dashboard, we see this very nice indicator of the current count.

<img width="751" alt="Screen Shot 2019-12-16 at 8 18 48 AM" src="https://user-images.githubusercontent.com/992646/70923774-48edd100-1fdd-11ea-8f47-e1ce36b6dfed.png">

…however when viewing this in a dashboard, this is what is shown:

![screenshot](https://user-images.githubusercontent.com/992646/70923818-5f942800-1fdd-11ea-9e9e-0a8cf95bcaf9.png)

**Describe the solution you'd like**
See this from the dashboard:
<img width="751" alt="Screen Shot 2019-12-16 at 8 18 48 AM" src="https://user-images.githubusercontent.com/992646/70923774-48edd100-1fdd-11ea-8f47-e1ce36b6dfed.png">

**How important is this feature to you?**
We use the progress visualization to help with setting and tracking goals. An important part of that is knowing where you are (quantifiably) and where you want to be. This one little feature would help tremendously in achieving our goals.

**Additional context**

**Comment by SirWellington** [comment]
I realized that this shows when the graph is shown with 4+ rows. At 3 rows it is hidden. 

#### 3 Rows
![image](https://user-images.githubusercontent.com/992646/71050783-05898480-20fb-11ea-8038-5cafbeacd2cc.png)

#### 4 Rows
![image](https://user-images.githubusercontent.com/992646/71050756-e8ed4c80-20fa-11ea-85ea-6d7409ea85de.png)

**Comment by flamber** [comment]
Related to #7058. Generally tricky to display a lot of information on small cards, while still making the core visualization big enough.

**Comment by SirWellington** [comment]
Closing this issue as we can make due with a "4-row" Progress bar. It is less than ideal but we can live with it.
