### ISSUE TITLE
Update message still showing for 0.33.7.3

### ISSUE THREAD

**Issue by jasongi-actu** [metabase/metabase#11535]
**Describe the bug**
Update message showing for 0.33.7.3
![Screen Shot 2019-12-17 at 3 32 15 pm](https://user-images.githubusercontent.com/40749062/70965059-78d2cc80-20e2-11ea-9300-0887b9f37d81.png)

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
N/A, see screenshot

**To Reproduce**
1. Update to the 0.33.7.3 docker container

**Expected behavior**
It should say the it's the latest version

**Screenshots**
See above

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: OS X 
- Your databases: Postgres
- Metabase version: 0.33.7.3
- Metabase hosting environment: Kubernetes (Docker)
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.
Minor

**Additional context**

**Comment by flamber** [comment]
Hi @jasongi-actu 
That's just because the job called `metabase.task.upgrade-checks.job` hasn't been executed yet.
The message will go away in less than 12 hours. Check Admin > Troubleshooting > Jobs (note that timestamps are Zulu/UTC)
Have a look at #11336 for more information. If that covers it, then please close this issue :+1:

**Comment by SpringMagnolia** [comment]
I down the jar file from `.jar: http://downloads.metabase.com/v0.33.7.3/metabase.jar` , and I replaced the old one , but when I restart it again ,still show this `Starting Metabase version v0.33.7.1 (d2dda64 release-0.33.x) ...` ,

**Comment by flamber** [comment]
@SpringMagnolia Please keep the conversation in one place:
https://discourse.metabase.com/t/cant-add-a-new-user-no-implementation-of-method-render-error/8350/7

**Comment by mazameli** [comment]
Closing as fixed.
