### ISSUE TITLE
Table columns won't sync in Metabase Data Model

### ISSUE THREAD

**Issue by mimi0604** [metabase/metabase#11536]
**Describe the bug**
For two of our tables that come from a MongoDB database, we don't see any columns. I updated the Metabase version, tried syncing the database again, but nothing works.

**To Reproduce**
1. Go to 'Data Model'
2. Click on 'Uses' table
3. See that there are no columns for this table

**Expected behavior**
We have always had the issue that the columns of this and on other table are not available. We are using MongoDB.

**Screenshots**
![empty_columns_metabase](https://user-images.githubusercontent.com/6690060/70980873-ba508100-20bc-11ea-8638-199483c5c049.png)

**Severity**
blocking our usage of Metabase partly

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-1061-azure",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-13",
      "tag": "v0.33.7.1",
      "branch": "release-0.33.x",
      "hash": "d2dda64"
    },
    "settings": {
      "report-timezone": "Europe/Athens"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @mimi0604 
Do you see any errors in the logs? Admin > Troubleshooting > Logs
You might want to force a sync and then check the logs. Admin > Databases > (mongodb) > Sync... 
And upgrade to 0.33.7.3 released yesterday.

**Comment by mimi0604** [comment]
@flamber I tried the syncing and I get no errors. The last lines'in the log regarding the syncing and the table 'users that I have issues with are:
[5301c1ac-f6df-4971-afaa-840df83499da] 2019-12-17T14:47:07+02:00 INFO metabase.sync.analyze classify-tables Analyzed [***********************************************···] 😍 95% Table 267 'users'
[5301c1ac-f6df-4971-afaa-840df83499da] 2019-12-17T14:47:07+02:00 INFO metabase.sync.util FINISHED: step 'classify-tables' for mongo Database 8 'Claims API' (34.2 ms)
[5301c1ac-f6df-4971-afaa-840df83499da] 2019-12-17T14:47:07+02:00 INFO metabase.sync.util FINISHED: Analyze data for mongo Database 8 'Claims API' (19.1 s)'

**Comment by flamber** [comment]
@mimi0604 Okay, if there are no errors at all in the log, then I'm not sure what's going on.

**Comment by mazameli** [comment]
@mimi0604 Could you please try either version 0.33.7.3 or 0.34 to see if that fixes your issue? (Incidentally, version 0.34 includes support for variables in Mongo queries. :) )

**Comment by flamber** [comment]
@mimi0604 By any chance, did you have any Metrics for the tables that are empty?
If yes, then you're likely seeing #10844, but verify that you're seeing the same browser console errors.

**Comment by mimi0604** [comment]
Thanks for the help @mazameli and @flamber ! Installing the latest version fixed the issue!

**Comment by mazameli** [comment]
Glad to hear it, @mimi0604 :)
