### ISSUE TITLE
SQL Parameter field: "drop-down" or "multi-select" widget type with custom SQL query

### ISSUE THREAD

**Issue by tuaris** [metabase/metabase#11531]
This is a feature request for a new functionality to custom SQL.  Specifically when setting up an SQL Parameter and Defining a Variable that is not a field filter as per https://www.metabase.com/docs/v0.33.6/users-guide/13-sql-parameters.html).

The request is to add additional widget types when defining the variable.  A single select drop down and multi-select box widgets.  The contents of which are defined by an SQL query that can be built using a UI (smaller version of the query builder, or custom SQL).

This is slightly similar to #9155 and #5445.

I would put this under "nice to have".  It would also help with #10992.

**Comment by flamber** [comment]
Hi @tuaris 
Sounds like #5245/#6820. As for restricting the category dropdown to a single selection, that's #7605.
If you feel like those cover what you're looking for, then please close this, otherwise could you add more details on how this request is different from all the linked issues?

**Comment by mazameli** [comment]
Closing this as a duplicate, but we'd love your upvotes and thoughts on the issues referenced above. :)
