### ISSUE TITLE
Not all messages are translated correctly

### ISSUE THREAD

**Issue by argnist** [metabase/metabase#11542]
**Describe the bug**
I use Russian language. For example string "No result!" has translation in
https://github.com/metabase/metabase/blob/master/locales/ru.po but in query table it is in English "No result!"

Also I've found:
"Other" and "Percentage" in Pie chart
"Add filter" in filters

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
It's probably the case that these strings haven't been properly tagged.

**Comment by flamber** [comment]
Another. When going to Ask question > Custom question, then it says `Pick your starting data`
