### ISSUE TITLE
GSuite. Starting in June 2020, Google will limit to support OAuth to access G Suite account data. Affect to Email account in Metabase for instance.

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#11543]
Hi All,

Starting in June 2020, Google will limit to support OAuth to access G Suite account data. 
https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html

Could affect to Email configuration account in Metabase for instance.

Are you planning the possibility to access through oauth to gmail (gsuite) in metabase opensource?

Thanks a lot!

**Comment by flamber** [comment]
Hi @jlisyc 
Metabase doesn't have access to email data - it only uses SMTP to send emails.
You shouldn't be using Less Secure Apps (LSA), which is what Google is removing completely.
The recommended option is App Passwords:
https://support.google.com/accounts/answer/185833?hl=en
Alternatively using the SMTP Relay:
https://support.google.com/a/answer/2956491?hl=en

**Comment by jlisyc** [comment]
Thanks Flamber
