### ISSUE TITLE
SameSite Cookie restriction when metabase embedded in iframe

### ISSUE THREAD

**Issue by kumar-tdx** [metabase/metabase#11545]
Hi, I'm trying to embed metabase app in an iframe. The URL looks something like this.

https://dev.mydomain.io/a23185a7dda04007a5d259bacb811244--metabase/browse/2

The iframe is in a different domain than the metabase app.

The login page loads fine in iframe.. But when logged in, api/user/current returns "Unauthenticated". I think it is because if the Set-Cookie of the response headers of api/session has SameSite=Lax. Is there a way to change that to SameSite=None?

**Comment by flamber** [comment]
Hi @kumar-tdx 
Sounds like you're trying to do FullApp Embedding, which is an Enterprise Edition feature.
https://www.metabase.com/docs/latest/enterprise-guide/full-app-embedding.html
Have you defined `MB_EMBEDDING_APP_ORIGIN` as noted in the documentation?
If you're using the Community Edition, then please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:

**Comment by kumar-tdx** [comment]
Thanks.. I'll check that. Closing issue now.

**Comment by denkomanceski** [comment]
@kumar-tdx did you manage to fix this?

**Comment by flamber** [comment]
@denkomanceski Version 1.35.0 (Enterprise) will have the option to change this with the environment variable `MB_SESSION_COOKIE_SAMESITE`, which can be set to `Lax` (default), `None` or `Strict`

**Comment by denkomanceski** [comment]
I am on 
You're on version v1.34.3
Built on 2020-02-28

Does this mean that we have to wait until 1.35.0 becomes available? Is there some way to install it earlier (even if its still not stable). We need to ship full app embedding

**Comment by flamber** [comment]
@denkomanceski Think the only hack right now would be with a reverse proxy:
https://serverfault.com/questions/849888/add-samesite-to-cookies-using-nginx-as-reverse-proxy

**Comment by denkomanceski** [comment]
Okay, that should be good enough for now. Will give it a shot.
