### ISSUE TITLE
Dashboard ID filter not available for nested question

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#11559]
**Describe the bug**
When I add to a dashboard a question that is based on a saved question, I can't link a ID dashboard filter to the question.
The problem is similar to what's reported in #2813 or #9802, but in my case this happens with a GUI saved question so I am opening a separate issue in case it is a different root cause.

**To Reproduce**
I have created (using GUI query editor) a saved question with 3 columns: 2 group by columns which are foreign keys to the ID of other tables, and 1 count of rows column. For example:
![Screenshot from 2019-12-19 14-56-32](https://user-images.githubusercontent.com/7570541/71180455-87e88480-2272-11ea-81b1-8b3bbdc0abc5.png)

Then I created a new question based on the saved question that filters it and groups by one column. For example:
![Screenshot from 2019-12-19 14-59-03](https://user-images.githubusercontent.com/7570541/71184018-5626ec00-2279-11ea-92c5-5f39170e45f2.png)

When I add those 2 questions on a dashboard with an ID dashboard filter, I can link the filter to the first question, but not the second one: 
![Screenshot from 2019-12-19 15-00-15](https://user-images.githubusercontent.com/7570541/71184095-7f477c80-2279-11ea-99b8-19fa4986851c.png)

**Logs**
When I click the Edit button of the dashboard filter, this shows up in the JS console:

> Missing id: Object { values: values() }

**Expected behavior**
The metadata of the ID column should be carried over so that it can be linked to a dashboard filter.

**Severity**
In my use case, the question I created is specifically for that dashboard and I cannot use it at all if I can't link it to the ID filter.

I did find a workaround, but it's not obvious because there seem to be another bug in the way. You need to create the question based on the foreign table, and join it to the saved question. Filtering on the aggregated column wouldn't work for me (only "Is" option and not possible to enter a value), so I had to create a custom column that is equal to the aggregated column, and use that in the filter. Here is what it looks like:

![Screenshot from 2019-12-19 16-21-58](https://user-images.githubusercontent.com/7570541/71185426-b454ce80-227b-11ea-840d-92ee70441639.png)

With that question, I am able to use the dashboard filter. Note that the join must be in this order, otherwise it faces the same bug.

**Comment by flamber** [comment]
Hi @rthouvenin 
Looks like a duplicate of #11007. If you agree, then please close this and upvote the other issue :+1:

**Comment by rthouvenin** [comment]
Ah I tried hard to find an existing issue before spending time describing it but didn't use the right keywords it seems :( Thanks for spotting it!
