### ISSUE TITLE
Legend and tooltips for time ranges on pie charts are hard to read

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1155]
Looks like we need to strip out everything after and including "T0". This is true for Hour, Month, Week, and Quarter. Year and Day look great.

![screen shot 2015-10-06 at 4 53 08 pm](https://cloud.githubusercontent.com/assets/2223916/10325982/09567e2e-6c4b-11e5-8b3a-017634b8e18a.png)

**Comment by mazameli** [comment]
@kdoh: just a reminder about this one as you're revisiting donut charts.

**Comment by salsakran** [comment]
@kdoh this still a thing or have Bru-nut charts fixed this?

**Comment by kdoh** [comment]
This particular one has less to do with donut vs pie and more just tooltip formatting, which is standardized in 0.16 so we should be good to close this.
