### ISSUE TITLE
Chart labels don't show significant decimals

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11565]
Our new chart labels use `compact` formatting, which is great for larger numbers, but it unfortunately rounds off decimals that can be significant when looking at things like average scores (or ERA in baseball in this example below). Here I would expect the "Minimum number of decimals" setting to force the labels to show two decimal places — this expectation is reinforced by the fact that all of the other column settings here, like prefix, _do_ affect the labels.

![image](https://user-images.githubusercontent.com/2223916/71210914-e3ab1180-2262-11ea-90ee-d8843dd4c4ba.png)

@paulrosenzweig and I talked about this briefly, and he suggests that another way to address this issue more broadly is to revisit the logic for the `compact` setting, so that it might e.g. always show two decimal places for floats or currency fields if they're under some threshold.

**Comment by npuglisi** [comment]
Where that I change this compact setting?
I have trouble for not showing the decimals =/

**Comment by paulrosenzweig** [comment]
Fixed in #11893
