### ISSUE TITLE
Difficult to access Saved Questions on join

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11571]
**Describe the bug**
Can be difficult to access Saved Questions on join. When showing the popover for join, it sometimes shows the database's tables instead of Saved Questions.
It's difficult to explain, see video.

**Logs** No warning or errors

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Click Join-icon, click the Saved Questions in the popover
3. If it shows the actual list of Saved Questions, click outside the popover to close it, and try again - or start by clicking the database (first option), go back, click Saved Questions.
Doesn't always trigger, which is why I thought I had clicked something wrong, but then it happened twice within a few minutes during debugging.

**Screenshots**
![Screencast 2019-12-19 21 53 09](https://user-images.githubusercontent.com/1447303/71229916-17128e00-22ad-11ea-92df-88d0a6c9977a.gif)

**Information about your Metabase Installation:**
Metabase 0.34.0 with Firefox 71 and Chromium 79

**Comment by mazameli** [comment]
I have yet to reproduce this, but I believe you. ;)

**Comment by flamber** [comment]
Saved Question picker was completely revamped in 0.40
