### ISSUE TITLE
MySQL Connect Failed

### ISSUE THREAD

**Issue by but0n** [metabase/metabase#11575]
Hi, I'm attempt to add a MySQL database, but all fialed, even through SSH tunnel.
![image](https://user-images.githubusercontent.com/7625588/71244245-0dd8fe00-234d-11ea-9ff2-98033353eb58.png)

I'm already confirmed that mysql server can be accesse successful with same configuration in command line.

**Comment by flamber** [comment]
Hi @but0n 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Remember to provide more details, like version numbers of Metabase and MySQL and anything else.
And please close this issue :+1:
