### ISSUE TITLE
Native questions shows Save-button without changing anything

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11572]
**Describe the bug**
When accessing SQL question, it shows Save-button - like the query is dirty.
But clicking the Save-button shows a blank dialog.
Also, the URL is not `/question/1`, but `/question/1#---queryhash---`

**Logs**
A couple of errors, but I don't think it's related to this:
`Uncaught TypeError: Cannot read property 'offsetHeight' of null` and `Uncaught Invariant Violation: Minified React error #44`

**To Reproduce**
1. Go to a Native/SQL question
2. Notice the URL is not clean, and Save-button is active in top-right
3. Click Save-button and it shows an empty dialog, cancel
4. Change the query, click Save-button, now the dialog is normal

**Screenshots**
![Screencast 2019-12-19 22 33 50](https://user-images.githubusercontent.com/1447303/71230553-bdf82980-22af-11ea-8f77-1b7974194304.gif)

**Information about your Metabase Installation:**
Metabase 0.34.0 on Firefox 71 and Chromium 79

**Comment by mazameli** [comment]
I wonder if this is due to the fix to keep saving a question from dirtying a query, @paulrosenzweig?

**Comment by flamber** [comment]
This causes more problems than just visual annoyances. See #11590
It gives permission errors to users with non-data/SQL access, since it tries to run the query as `POST /api/dataset` instead of `POST /api/card/:id/query` (but only for queries without filters - huh?).
P1? I've tested `fix-11572` and that fixes the permission error too.

**Comment by salsakran** [comment]
bumping to P1 due to #11590 as users w/o native query access not being able to run native queries they have collections for breaks a fundamental use case
