### ISSUE TITLE
Cannot download 0.34.0 MacApp

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11576]
The download link on the [website](https://www.metabase.com/start/mac.html) leads to `404`:
https://downloads.metabase.com/v0.34.0/Metabase.dmg

Reported in https://discourse.metabase.com/t/cant-download-app/8404

**Comment by mazameli** [comment]
Yeah, we had an issue building the MacOS app last night; it's an independent process from the rest of the build. We're looking into what went wrong and will give this another attempt today.

**Comment by dacort** [comment]
@camsaul This is good to close now, right?

**Comment by salsakran** [comment]
fixed now.

**Comment by artinsane** [comment]
https://downloads.metabase.com/v0.35.1/Metabase.dmg - not working. 404 error
