### ISSUE TITLE
metabase Trend visualization not showing "was" value in fullscreen

### ISSUE THREAD

**Issue by faadhiljacobs** [metabase/metabase#11573]
**Describe the bug**
I have a trend view of today vs yesterday, on my dashboard the card shows correctly however when changing the dashboard to full screen the "was" value does show, only the percentage down or up.

**Expected behavior**

See picture on this link shows "was" value 

https://ibb.co/hLrdR3Y

**Screenshots**

- Working here 
https://ibb.co/hLrdR3Y

- Not Working here 

https://ibb.co/PDRzZb3

**Severity**
Severe as its critical info not showing.
<img width="447" alt="Screenshot 2019-12-20 at 08 29 01" src="https://user-images.githubusercontent.com/32433564/71234923-36d4a100-2303-11ea-9844-c7d9c857dcf9.png">
<img width="463" alt="Screenshot 2019-12-20 at 08 31 06" src="https://user-images.githubusercontent.com/32433564/71234924-36d4a100-2303-11ea-94b2-4c706a7d1ab7.png">

**Comment by flamber** [comment]
Hi @faadhiljacobs 
Looks like a duplicate of #10786. If you agree, then please close this and upvote the other issue :+1:

**Comment by faadhiljacobs** [comment]
Closing as it is duplicate of #10786
