### ISSUE TITLE
Extend v0.34.0's show data values to multiple series (breakouts & combos) [Enhancement]

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#11585]
Great new feature!  Would love for it to also apply to multiple series such as breakouts and especially combos.  With two series with different scales, each on it's own y-axis, for example, this would help viewers to immediately see which set of values go with which y-axis.  Something along the lines of the first example in the Discourse post <a href="https://discourse.metabase.com/t/combo-stacked-breakout-with-addtional-fields/8395">"Combo, stacked breakout, with additional fields"</a> would be ideal.  From this example and the discussion in <a href="https://github.com/metabase/metabase/pull/11363">Pull request #11363, Show data values on charts</a> multiple series are a rather more complicated thing for showing values than just a single series chart.  With the logic in place, however, it might now be fairly easy to do it for stacked column totals alone as described in <a href="https://github.com/metabase/metabase/issues/4109">Issue #4109, Stacked bar "sum" data label</a>.

Additional reference, posted to Discourse as <a href="https://discourse.metabase.com/t/v0-34-0-values-on-chart-needed-for-multiple-series/8416">V0.34.0 values on chart needed for multiple series</a>.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by exabrial** [comment]
Can we also do this with pie charts? Currently the only way to see the values in a pie chart is to physically mouse over. Without labels on pie charts, they're fairly useless on TV Wall Dashboards because nobody has pointer access.

**Comment by RobinCowash** [comment]
+1
Having total on top of each bar would be so great...
![musthave](https://user-images.githubusercontent.com/52792560/72370646-fea65f80-3702-11ea-877b-84df6d053fa8.PNG)

**Comment by chris-guidry** [comment]
Extending it to scatter plots would also be great.

**Comment by brecher** [comment]
It would be great to be able to add values ​​for multiple series on lines and bars chart.

**Comment by paulrosenzweig** [comment]
This feature was added with #12645. It will go out in v0.36.0.
