### ISSUE TITLE
Distinct, non-empty sequence of Field clauses metabse-mac

### ISSUE THREAD

**Issue by lmsanch** [metabase/metabase#11588]
**Describe the bug**
I am using metabase for mac. My mongo db has 5 tables, I was able to connect it to 3, but 2 had errors **Distinct, non-empty sequence of Field clauses** I assume due to naming of the collection ( I was using underscores in 2 of them)  and/or using dual keys. Not being very proficient with dbs, I uninstalled the software and installed again.
Now I have a single key in each collection and I don't use underscores in my names. 
Now, I can read only one of the original collections and the other 4 show the same error.
`Distinct, non-empty sequence of Field clauses`
I tried running a forced sync+scan (Admin > Databases > (db) > Sync database schema now + Re-scan field values now), and the problem persists.
Any ideas what's wrong?

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_202-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_202",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.202-b08",
    "os.name": "Mac OS X",
    "os.version": "10.14.6",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.7.1",
      "date": "2019-12-13",
      "branch": "release-0.33.x",
      "hash": "d2dda64"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
Decided to use the java version...same problem. Below more detail about the problem:
```
12-24 19:14:01 WARN middleware.process-userland-query :: Query failure {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Distinct, non-empty sequence of Field clauses",
 :stacktrace
 ("--> query_processor.middleware.add_implicit_clauses$fn__37199$sorted_implicit_fields_for_table__37204.invoke(add_implicit_clauses.clj:48)"
  "query_processor.middleware.add_implicit_clauses$fn__37307$add_implicit_fields__37312$fn__37316.invoke(add_implicit_clauses.clj:93)"
  "query_processor.middleware.add_implicit_clauses$fn__37307$add_implicit_fields__37312.invoke(add_implicit_clauses.clj:86)"
  "query_processor.middleware.add_implicit_clauses$fn__37395$add_implicit_mbql_clauses__37400$fn__37404.invoke(add_implicit_clauses.clj:130)"
  "query_processor.middleware.add_implicit_clauses$fn__37395$add_implicit_mbql_clauses__37400.invoke(add_implicit_clauses.clj:126)"
  "query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invoke(add_implicit_clauses.clj:137)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__37904.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42923.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__37741.invoke(add_row_count_and_status.clj:16)"
  "driver.mongo$eval2008$fn__2009$fn__2011$f__702__auto____2013.invoke(mongo.clj:86)"
  "driver.mongo.util$_with_mongo_connection$fn__693.invoke(util.clj:205)"
  "util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)"
  "util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)"
  "driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)"
  "driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)"
  "driver.mongo$eval2008$fn__2009$fn__2011.invoke(mongo.clj:85)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__40615.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__42537.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.store$initialize_store$fn__45667$fn__45668.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__45667.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__22968.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__39657.invoke(async_wait.clj:89)"),
 :query
 {:type "query",
  :query {:source-table 7},
  :parameters [],
  :async? true,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [59, 36, -9, 35, 39, -40, -16, -44, 89, -97, -75, 110, -55, 49, 86, -9, -88, -21, 4, -15, 4, 108, -84, 100, -51, -97, -97, 107, -12, -46, -114, 39]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :preprocessed nil,
 :native nil,
 :ex-data {:type :schema.core/error, :value (), :error (named (not ("Non-empty" a-clojure.lang.LazySeq)) "Distinct, non-empty sequence of Field clauses")}}
```

**Comment by flamber** [comment]
Hi @lmsanch 
Can you upgrade to 0.33.7.3 or 0.34.0? Since 0.33.7.1 had some build problems, so just want to make sure that isn't affecting you.

The error that you describe is usually because it hasn't finished the sync/scan yet. But you already tried to a forced sync+scan, and still have problems, which make me think that something else might failing. There's an issue open about giving more visual indication about the sync/scan #11354.

How big are the tables that still fails? Could it be that the sync/scan just needs more time?
When you run the forced sync/scan, do you see any errors/warnings (or other indications) that the process isn't completed correctly? See Admin > Troubleshooting > Logs, while the process is running.

**Comment by lmsanch** [comment]
Thank you. 
I downloaded what I thought was metabase v0.34.0 for mac from this link:
https://www.metabase.com/docs/latest/operations-guide/running-the-metabase-mac-app.html
When I check the version, it says it is the latest:
<img width="601" alt="Screen Shot 2019-12-24 at 9 58 50 PM" src="https://user-images.githubusercontent.com/3156487/71430311-fbd2c480-2698-11ea-97a6-8dfa0142ec87.png">
However, the version is clearly indicated as 0.33.7.1
The tables are very small: 1 with about 350 records, and the other 4 with less than 100 records each. 
```
print(db.command("dbstats")
{'db': 'Rumors', 'collections': 5, 'views': 0, 'objects': 597, 'avgObjSize': 789.4673366834171, 'dataSize': 471312.0, 'storageSize': 512000.0, 'numExtents': 0, 'indexes': 5, 'indexSize': 184320.0, 'scaleFactor': 1.0, 'fsUsedSize': 80647020544.0, 'fsTotalSize': 982900588544.0, 'ok': 1.0}
```

**Comment by flamber** [comment]
@lmsanch Uhh, sorry, I forgot that you were using the Mac App.
Currently it's not available in the latest version because of build issues #11576 and the "latest and greatest" confusing message is covered by #11336. I don't have Mac, so cannot even test this for you.
If possible, could you use the JAR version instead? It exists in 0.33.7.3 and 0.34.0

**Comment by lmsanch** [comment]
Thank you. 
I am using now the java version, and I get the same problem.
<img width="478" alt="Screen Shot 2019-12-25 at 10 26 07 AM" src="https://user-images.githubusercontent.com/3156487/71447785-fc06aa80-2700-11ea-8bd9-d6a352c684de.png">
Here is the problem in one of my tables (2 out of my 5 tables are showing the problem):

<img width="920" alt="Screen Shot 2019-12-25 at 10 21 16 AM" src="https://user-images.githubusercontent.com/3156487/71447791-19d40f80-2701-11ea-84e1-1b6209847677.png">

That table does not have anything strange at first glance in mongodb:
<img width="896" alt="Screen Shot 2019-12-25 at 10 24 32 AM" src="https://user-images.githubusercontent.com/3156487/71447803-47b95400-2701-11ea-9095-5ebb82d51be0.png">

Console displays this:
```
12-25 10:32:02 WARN middleware.process-userland-query :: Query failure {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Distinct, non-empty sequence of Field clauses",
 :stacktrace
 ("--> query_processor.middleware.add_implicit_clauses$fn__37199$sorted_implicit_fields_for_table__37204.invoke(add_implicit_clauses.clj:48)"
  "query_processor.middleware.add_implicit_clauses$fn__37307$add_implicit_fields__37312$fn__37316.invoke(add_implicit_clauses.clj:93)"
  "query_processor.middleware.add_implicit_clauses$fn__37307$add_implicit_fields__37312.invoke(add_implicit_clauses.clj:86)"
  "query_processor.middleware.add_implicit_clauses$fn__37395$add_implicit_mbql_clauses__37400$fn__37404.invoke(add_implicit_clauses.clj:130)"
  "query_processor.middleware.add_implicit_clauses$fn__37395$add_implicit_mbql_clauses__37400.invoke(add_implicit_clauses.clj:126)"
  "query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invoke(add_implicit_clauses.clj:137)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__37904.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42923.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__37741.invoke(add_row_count_and_status.clj:16)"
  "driver.mongo$eval2008$fn__2009$fn__2011$f__702__auto____2013.invoke(mongo.clj:86)"
  "driver.mongo.util$_with_mongo_connection$fn__693.invoke(util.clj:205)"
  "util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)"
  "util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)"
  "driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)"
  "driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)"
  "driver.mongo$eval2008$fn__2009$fn__2011.invoke(mongo.clj:85)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__40615.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__42537.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.store$initialize_store$fn__45667$fn__45668.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__45667.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__22968.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__39657.invoke(async_wait.clj:89)"),
 :query
 {:type "query",
  :query {:source-table 8},
  :parameters [],
  :async? true,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [-6, -6, 120, -85, -76, -127, -113, -120, 67, -105, 9, 37, -52, 40, 38, -118, 13, -34, -61, 8, -10, -72, -114, 71, -61, 68, -124, -101, 101, 18, -14, -24]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :preprocessed nil,
 :native nil,
 :ex-data {:type :schema.core/error, :value (), :error (named (not ("Non-empty" a-clojure.lang.LazySeq)) "Distinct, non-empty sequence of Field clauses")}}
```

**Comment by flamber** [comment]
@lmsanch 
Great with all the info you provide. I have very little knowledge about MongoDB, so let's see what one of the database guys can figure out, when they return from vacation.
The only thing that I'm noticing in the error is that it seems like you're using SSH to connect to the MongoDB database from Metabase, is that correct? Are you using the built-in SSH-tunnel? If yes, could you try without the built-in tunnel, but setup the tunnel on your machine manually?
I've seen some really strange sync/scan behavior with other databases, when using a tunnel (#8396)

**Comment by lmsanch** [comment]
Thank you. My mongo db is running locally in my Ubuntu machine, but when I connect with mac, I use a VPN. I suspected that something like that could be the problem, so I logged in in the Ubuntu machine directly, used metabase java version (latest) directly in that machine, connected to localhost and the problem persists. So I can safely discard any connection issues via SSH, etc.
Thanks again.

**Comment by caleb15** [comment]
One of our users just got the same problem now that I upgraded metabase to v33.6

```
Value does not match schema: {:query {:fields (named (not ("distinct" a-clojure.lang.PersistentVector)) "Distinct, non-empty sequence of Field clauses")}}
```

I tried editing the question to get rid of the custom column and filters and sorting but the error remained. I recreated the question and the new question (with the exact same sorts and filters and custom column) worked for some reason.

We use v11 postgres for our database (and for our metabase db too)

**Comment by lmsanch** [comment]
Any feedback about what I should try to get metabase to work with my mongo db?

**Comment by flamber** [comment]
@lmsanch Are you still seeing this problem on newer versions of Metabase?

**Comment by flamber** [comment]
Closing, since there has been several fixes to the sync process in the past few versions.

If you're still experiencing this issue, then please start Metabase with debug logging and provide logs from the sync+scan process.
If using Docker, add this to the run command:
```
-e JAVA_OPTS="-Dlog4j.configuration=https://log4j.us/templates/metabase?trace=metabase.sync"
```
If using JAR, add this:
```
java -Dlog4j.configuration="https://log4j.us/templates/metabase?trace=metabase.sync" -jar metabase.jar
```
