### ISSUE TITLE
Native/SQL variable panel, cards jumps around when editing

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11580]
**Describe the bug**
When editing the variable sidebar filters, the cards jumps around (Chris Kross - Jump :musical_note:).

**Logs** No errors/warnings related to this.

**To Reproduce**
1. Native query > click Variables-icon (right side) > click "Try it" on first example
2. Add ` AND {{another}}` after `... {{category}}` (`another` is now add as the last card)
3. Give `another` a "Filter label" and try to click "Variable type" (`another` is now the first card)
4. Set the "Variable type" for `another` to "Field Filter" (`another` is now the last card)

**Expected behavior**
Keep the same position throughout - manual reordering is covered in #9357.

**Screenshots**
![Screencast 2019-12-20 14 58 15](https://user-images.githubusercontent.com/1447303/71291929-55558f00-2339-11ea-9765-71f472353327.gif)

**Information about your Metabase Installation:**
Metabase 0.34.0 various browsers and backends.

**Severity**
I would normally give this P2, but it's making it almost impossible work with filters, so P1.

**Additional context**
https://discourse.metabase.com/t/v0-34-0-unstable-variables-panel/8413

**Comment by salsakran** [comment]
P1 since this is a highly trafficked path and it's a regression. Could be a P1.5 but rounded "up".

**Comment by MarcGJA** [comment]
And it's populating corresponding fields in the next variable's sub-panel too.  And the default filter widget field is almost impossible to fill, every character typed-in sends the sub-panel zooming off somewhere.  Plus the editor window cursor is displaced right by one space... Switching back to v0.33.2 for the time being, looking forward to v0.34.1
