### ISSUE TITLE
Native/SQL editor displaces cursor one position to the right of mouse click

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11584]
**Describe the bug**
When trying to click a position in the Native/SQL editor, it's displaced ~one character to the right.
It's a little difficult to show on a GIF, but should be easy to reproduce.
Fixed by removing `.NativeQueryEditor .ace_editor .ace_content { padding-left: 7px; }`
https://github.com/metabase/metabase/pull/11515/files#diff-2241b17415b77474d12a7b9fa0546d27R53

**Information about your Metabase Installation:**
Metabase 0.34.0 on Firefox 71 and Chromium 79

**Comment by MarcGJA** [comment]
Minor but rather awkward for users modifying sql.

**Comment by rdlu** [comment]
It occurs with all  4 analysts from my team, using MacOS Mavericks / High Sierra / Catalina and Windows 10, no matter what browser they are using.

I'm using linux (Manjaro Linux with Vivaldi and Firefox fully updated) and works perfectly fine.

**Comment by pshahVA** [comment]
This is still happening when I tried this on my PC using chrome and MS edge.  Please look into it.
