### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by abalfazl9776** [metabase/metabase#11593]
Translations that are relevant to frontend (strings in the frontend folder) do not work.
When I change the language some parts won't translate, and I figured that all strings from js files have this issue.

But when I change my browser language it's showing all the parts on language that I chose in browser language.

I'm using the latest commit : [https://github.com/metabase/metabase/commit/5996deb09464ddb814ba42cf3a76ce63237e6957](url)

**Comment by flamber** [comment]
Hi @abalfazl9776 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
I don't understand what you're trying to do or which files you're trying to modify.
All translations in Metabase are imported from https://poeditor.com/join/project/ynjQmwSsGh
If you're manually changing some files, then you might need to run the compiler:
`./bin/i18n/build-translation-frontend-resource` and `./bin/i18n/build-translation-resources`

**Comment by abalfazl9776** [comment]
Hello again
Thanks for answering @flamber
I mean when you change the language from Admin>General>Language settings it does not change the whole application language, it just translate some parts and some parts still shown in English.
But if I change the browser the application translates completely to browser language.
It's so bad for ux. I want to use my browser in English but my application in any language that I want.

**Comment by flamber** [comment]
@abalfazl9776 That's a duplicate of #8384. Please close this and upvote the other issue :+1:
