### ISSUE TITLE
Google SSO not working on version 0.34.0

### ISSUE THREAD

**Issue by diogojapinto** [metabase/metabase#11595]
Signing-in using Google SSO is not working after upgrade from version 0.33.5.1 to 0.34.0. When I try to do so, I am redirected to the login screen again.

**Logs**
```
A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
cb=gapi.loaded_0:737 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
ie @ cb=gapi.loaded_0:737
cb=gapi.loaded_0:737 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
ie @ cb=gapi.loaded_0:737
cb=gapi.loaded_0:737 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
ie @ cb=gapi.loaded_0:737
cb=gapi.loaded_0:737 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
ie @ cb=gapi.loaded_0:737
2/api/user/current:1 Failed to load resource: the server responded with a status of 401 ()
login:1 A cookie associated with a cross-site resource at https://accounts.google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
login:1 A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/api/session/google_auth:1 Failed to load resource: the server responded with a status of 400 ()
```

**To Reproduce**
1. Go to Metabese login screen
2. Click on Sign in with Google
3. Use the applicable Google account
4. See the login screen, with errors on the console.

**Expected behavior**
I should be redirected to Metabase's dashboard.

**Screenshots**

Screenshot after trying to login and being redirected to the login page:

<img width="1679" alt="Screen Shot 2019-12-26 at 09 27 21" src="https://user-images.githubusercontent.com/3718837/71469998-c0341980-27c2-11ea-932a-43a78de44ef5.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: 79.0.3945.88 (Official Build) (64-bit)
- Your operating system: Mac OS X 10.15.1
- Metabase version: 0.34.0
- Metabase internal database: Postgres

**Severity**
This is making impossible for everyone with SSO on my company to login to Metabase.

**Additional information**
Login via email+password and cached sessions that started with an SSO login still work.

**Comment by diogojapinto** [comment]
We're trying to postpone rolling back so that we can help testing it.

**Comment by flamber** [comment]
Hi @diogojapinto 
It looks like a duplicate of #11516. If you agree, then please close this and follow the other issue :+1:

**Comment by cyhhao** [comment]
I also encountered this problem with the 400 error returned message: "Google Auth token meant for a different site."

**Comment by mahegetitdone** [comment]
we have the same problem with v.0.34.0, 0.34.1 and latest
i don't know why this is closed?
In the potential duplicate https://github.com/metabase/metabase/issues/11516 they advised @diogojapinto to open a new issue
and still not resolved

**Comment by diogojapinto** [comment]
Hi! Quick update, we have applied the changes suggested in  https://github.com/metabase/metabase/issues/11516#issuecomment-573186086 and it worked perfectly!

**Comment by mahegetitdone** [comment]
@diogojapinto  thanks, we will test it

**Comment by mahegetitdone** [comment]
worked fine for us too

**Comment by yeonhoyoon** [comment]
Anyone having this issue for only some of the accounts, check if the the Google account used for login has 'Last name' configured in their Google account settings.

**Comment by flamber** [comment]
@yeonhoyoon That's a known issue - #9418 - upvote by clicking :+1:  on the first post
