### ISSUE TITLE
Calendar filter UI ignores date format setting

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11604]
1. Create a question.
2. Add a filter on a date field.
3. Set the type to exact value.
4. The date entry UI appears.
5. Observe the date format used is the default MM/DD/YYYY.

![image](https://user-images.githubusercontent.com/30152071/71544649-975a8280-2982-11ea-9300-982c88ab5ffb.png)

**MB date/time config**
![image](https://user-images.githubusercontent.com/30152071/71544698-03d58180-2983-11ea-8112-1c4d1e9a4d29.png)

**MB config**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Comment by flamber** [comment]
Hi @andreychirikba 
Looks like a duplicate of #9151. If you agree, then please close this and upvote the other issue :+1:

**Comment by andreychirikba** [comment]
@flamber agree, have voted and closing this one.
