### ISSUE TITLE
Automagic dashboards fail on PeriodDuration.between

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11603]
In a fresh MB instance, I have added a DB, clicked on an automagic dashboard and it showed an error message. All automagic dashboards on all our production MB instances are affected. As soon as I make the allegedly affecting field invisible in the data model, the automagic dashboard works fine.

**Logs**
`12-28 13:21:29 ERROR middleware.log :: GET /api/automagic-dashboards/table/7 500 34,3 ms (6 DB calls) 
{:message nil,
 :type java.lang.NullPointerException,
 :stacktrace
 ("org.threeten.extra.PeriodDuration.between(PeriodDuration.java:317)"
  "--> util.date_2$period_duration.invokeStatic(date_2.clj:337)"
  "util.date_2$period_duration.invoke(date_2.clj:314)"
  "automagic_dashboards.core$optimal_datetime_resolution.invokeStatic(core.clj:289)"
  "automagic_dashboards.core$optimal_datetime_resolution.invoke(core.clj:280)"
  "automagic_dashboards.core$fn__60935.invokeStatic(core.clj:307)"
  "automagic_dashboards.core$fn__60935.invoke(core.clj:297)"
  "automagic_dashboards.core$build_query$fn__61076.invoke(core.clj:511)"
  "automagic_dashboards.core$build_query.invokeStatic(core.clj:507)"
  "automagic_dashboards.core$build_query.invoke(core.clj:505)"
  "automagic_dashboards.core$card_candidates$fn__61122.invoke(core.clj:649)"
  "automagic_dashboards.populate$shown_cards.invokeStatic(populate.clj:243)"
  "automagic_dashboards.populate$shown_cards.invoke(populate.clj:233)"
  "automagic_dashboards.populate$create_dashboard.invokeStatic(populate.clj:267)"
  "automagic_dashboards.populate$create_dashboard.invoke(populate.clj:254)"
  "automagic_dashboards.core$automagic_dashboard.invokeStatic(core.clj:1008)"
  "automagic_dashboards.core$automagic_dashboard.invoke(core.clj:985)"
  "automagic_dashboards.core$fn__61448.invokeStatic(core.clj:1028)"
  "automagic_dashboards.core$fn__61448.invoke(core.clj:1026)"
  "api.automagic_dashboards$fn__61759.invokeStatic(automagic_dashboards.clj:113)"
  "api.automagic_dashboards$fn__61759.invoke(automagic_dashboards.clj:106)"
  "middleware.auth$enforce_authentication$fn__48819.invoke(auth.clj:14)"
  "routes$fn__67566$fn__67567.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__48775.invoke(exceptions.clj:104)"
  "middleware.exceptions$catch_api_exceptions$fn__48772.invoke(exceptions.clj:92)"
  "middleware.log$log_api_call$fn__48685$fn__48686.invoke(log.clj:178)"
  "middleware.log$log_api_call$fn__48685.invoke(log.clj:172)"
  "middleware.security$add_security_headers$fn__48736.invoke(security.clj:121)"
  "middleware.json$wrap_json_body$fn__48904.invoke(json.clj:64)"
  "middleware.json$wrap_streamed_json_response$fn__48922.invoke(json.clj:100)"
  "middleware.session$bind_current_user$fn__47354$fn__47355.invoke(session.clj:209)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:184)"
  "middleware.session$do_with_current_user.invoke(session.clj:177)"
  "middleware.session$bind_current_user$fn__47354.invoke(session.clj:208)"
  "middleware.session$wrap_current_user_id$fn__47339.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__47283.invoke(session.clj:125)"
  "middleware.auth$wrap_api_key$fn__48827.invoke(auth.clj:27)"
  "middleware.misc$maybe_set_site_url$fn__48800.invoke(misc.clj:56)"
  "middleware.misc$bind_user_locale$fn__48803.invoke(misc.clj:72)"
  "middleware.misc$add_content_type$fn__48788.invoke(misc.clj:28)"
  "middleware.misc$disable_streaming_buffering$fn__48811.invoke(misc.clj:87)")}
`

Slightly before, I see this error message, which I believe to be the cause:

`12-28 13:19:38 ERROR sql-jdbc.execute :: Error reading :mysql column 14 Volgende afspraak TIMESTAMP
java.lang.NullPointerException
12-28 13:19:38 ERROR sql-jdbc.execute :: Error reading :mysql column 14 Volgende afspraak TIMESTAMP
`

**MB config**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Comment by flamber** [comment]
Hi @andreychirikba 
Do you see any errors in the log, when doing a forced sync/scan? Admin > Databases > (db)
Can you translate this "column 14 Volgende afspraak TIMESTAMP"?
I'm guessing that the column 14, is also the column that you set to hidden in Data Model?
What is the actual database column type? And what is the Field Type in Data Model?

**Comment by andreychirikba** [comment]
@flamber, I did a forced sync and saw the same error message (on a different column):
`12-28 15:30:08 ERROR sql-jdbc.execute :: Error reading :mysql column 2 Eind TIMESTAMP`
Further (repeated) resyncing doesn't show any errors.
Indeed, it's column 14 called `Volgende afspraak`. I'm querying a view and the column type is indeed timestamp. Data model doesn't have a specific type for it (is prompting to select a type).

**Comment by flamber** [comment]
@andreychirikba 
I haven't seen this type of error before, so I'm not sure what's going on.
Can you try setting a Field Type? Example "Creation timestamp" - just to see if that makes a difference.
Also, which version of MySQL are you using?

**Comment by sbelak** [comment]
This looks like the field is not fingerprinted properly (... and we don't handle this intermediate state well). Can you show me the output of /api/field/:id where id is the id Metabase gives to that field.

**Comment by andreychirikba** [comment]
Below is the output of /api/field/:id for the field in question (have removed DB details):

`{
    "description": null,
    "database_type": "TIMESTAMP",
    "table_id": 7,
    "table": {
        "description": "VIEW",
        "entity_type": "entity/UserTable",
        "schema": null,
        "show_in_getting_started": false,
        "name": "Personen",
        "caveats": null,
        "fields_hash": "NUAmr6vvIJkrcUm3QYZXkw==",
        "rows": null,
        "updated_at": "2019-12-28T12:52:27",
        "entity_name": null,
        "active": true,
        "id": 7,
        "db_id": 2,
        "visibility_type": null,
        "display_name": "Personen",
        "created_at": "2019-12-28T12:51:06",
        "points_of_interest": null
    },
    "special_type": null,
    "name": "Volgende afspraak",
    "fingerprint_version": 4,
    "has_field_values": "none",
    "settings": null,
    "caveats": null,
    "fk_target_field_id": null,
    "dimensions": [],
    "updated_at": "2020-01-08T19:14:11",
    "active": true,
    "parent_id": null,
    "id": 73,
    "last_analyzed": "2019-12-28T12:52:13",
    "position": 0,
    "visibility_type": "sensitive",
    "preview_display": true,
    "display_name": "Volgende afspraak",
    "name_field": null,
    "fingerprint": {
        "global": {
            "distinct-count": 1,
            "nil%": 1.0
        },
        "type": {
            "type/DateTime": {
                "earliest": null,
                "latest": null
            }
        }
    },
    "created_at": "2019-12-28T12:51:07",
    "base_type": "type/DateTimeWithLocalTZ",
    "points_of_interest": null
}`

**Comment by camsaul** [comment]
Fixed by #5057 11698
