### ISSUE TITLE
Can't create Pulse for read only collection

### ISSUE THREAD

**Issue by Mrmiffo** [metabase/metabase#11605]
**Describe the bug**
When creating a Pulse it is not possible to select collections which the user has read-only access to if that collection is within another collection which the user has no access.

**To Reproduce**
1. Create a collection 'A' in Our analytics.
2. Create a sub-collection 'B' in that collection.
3. Create a user group with Permissions 'View collection' for collection 'B'
4. Assign a user to the user group and login.
5. Create a Pulse and select Pick your data.
6. Collection 'B' is not displayed, and can't find cards in this collection.

**Screenshot**
![Create Pulse issue](https://user-images.githubusercontent.com/8545443/71557860-575fd200-2a4c-11ea-8451-e719b6910403.png)

**Expected behavior**
Users should be able to select Cards from questions in all collections he/she has access to.

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_144-b01",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_144",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.144-b01",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.0",
      "date": "2019-12-19",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

**Severity**
Due to our collection setup and use cases, our users are unable to create pulses for their most important questions.

**Additional context**
From Metabase help discussion: https://discourse.metabase.com/t/cant-create-pulse-for-view-only-collection-questions/8425

**Comment by qnkhuat** [comment]
Creating Pulse for read-only dashboards has been fixed by https://github.com/metabase/metabase/pull/17722
