### ISSUE TITLE
You spelled GitHub wrong 

### ISSUE THREAD

**Issue by fulldecent** [metabase/metabase#11601]
on the metabase homepage

**Comment by flamber** [comment]
Hi @fulldecent It would be helpful if you provided a link...

**Comment by fulldecent** [comment]
https://www.metabase.com

**Comment by prakharjain-vogo** [comment]
Do you mean `GitHub` instead of `Github`

**Comment by fulldecent** [comment]
Yes, that's it

**Comment by mazameli** [comment]
This should be corrected on the site momentarily. Thanks.
