### ISSUE TITLE
SQLite group by year it only returns current year

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11615]
**Describe the bug**
When binning a date "by year", it only returns current year. When using "by month", it shows correct month and year.

**Logs** No errors/warning.

**To Reproduce**
Guess any SQLite db will do, but tested with https://www.sqlitetutorial.net/sqlite-sample-database/
1. Simple question > SQLite Chinook > Invoices
2. Summarize count-of-rows by InvoiceDate:Year
Shows a line graph with a single point (and unaggregated warning triangle), checking raw-data shows 5 rows of 2019
![image](https://user-images.githubusercontent.com/1447303/71636212-99c31380-2bf2-11ea-97cd-641b2253a08b.png)
3. Summarize count-of-rows by InvoiceDate:Month
Shows line graph grouped by month, spanning 2009-2013 (5 years)
![image](https://user-images.githubusercontent.com/1447303/71636223-c840ee80-2bf2-11ea-87aa-f655af0dd1d8.png)

**Information about your Metabase Installation:**
Metabase `master`, 0.34.0 and 0.33.7.3 - various setups and browsers

**Additional context**
https://discourse.metabase.com/t/dates-by-year-defaulting-to-2019/8486

**Comment by lins05** [comment]
I've submitted a fix for this in #11662

**Comment by paulrosenzweig** [comment]
Thanks @lins05 for the fix!

Separately, I think we should probably enforce that all drivers return dates in the same format. I don't see anything else that could happen with this Sqlite behavior, so it probably makes sense to leave it for now.

**Comment by lins05** [comment]
>  enforce that all drivers return dates in the same format

@paulrosenzweig +1, that makes great sense and would make the interface more reasonable - assume in the future someone want to build a third-party tool with the dataset api and they would be puzzled by this inconsistencies among different drivers.
