### ISSUE TITLE
Input to store-field (0.33.0-preview2)

### ISSUE THREAD

**Issue by adikhel** [metabase/metabase#11612]
**Describe the bug**
> Input to store-field! does not match schema: [0;33m [(named {:database_type (not (instance? java.lang.String a-org.h2.jdbc.JdbcClob))} field)] [0m

**Logs**

Logs only have only this single line. Nothing else is visible in logs.
[---] 2019-12-31T14:04:13+05:30 undefined undefined undefined

**To Reproduce**
1) Download the preview version from here: https://github.com/metabase/metabase/releases/tag/v0.33.0-preview2

2) Clicked '+' and selected 'new custom question'.

3) Selected a database and a collection (all are imported from mongodb).

4) Click on the 'visualize' button.

**Expected behavior**
Results of the question should be visualized

**Screenshots**
![image](https://user-images.githubusercontent.com/48748486/71615207-1d223c00-2bd6-11ea-957c-4587bc92c62c.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your operating system: (Windows 10)
- Your databases: (MongoDB)
- Metabase version: (v0.33.0-preview2)
- Metabase hosting environment: (Jar-file)
- Metabase internal database: (e.x. MongoDB)

**Severity**
New feature does not seem to work.

**Comment by flamber** [comment]
Hi @adikhel 
That's an old preview release. Please download latest stable version: https://www.metabase.com/start/
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:
