### ISSUE TITLE
AWS Elastic Beanstalk installation guide has a mistake about "Application health check URL"

### ISSUE THREAD

**Issue by drewrwilson** [metabase/metabase#11628]
**Describe the bug**
On line 125 of [the Running Metabase on Elastic Beanstalk howto page](https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-metabase-on-elastic-beanstalk.md), it says "the Application health check URL is how Elastic Beanstalk knows when the application is ready to run. You must set this to /api/health." 

But when I was deploying it, this option does not appear in any of the setting. Where should this be set? Or is this old?

**Logs**
No logs

**To Reproduce**
Follow the guide linked above.

**Expected behavior**
To fix, please update the text of the guide to reflect how we should do the setup

**Screenshots**
N/A

**Information about your Metabase Installation:**
N/A

**Severity**
Blocking installation on AWS

**Additional context**
Thank you! Thank you!

**Comment by hcNick** [comment]
This should say something along the lines of:

Under _Load Balancer_ select _Modify_, then find the subheading marked _Processes_, tick the option marked _default_, select _Actions_ and then _Edit_. Make sure the HTTP code is `200` and the Health Check URL is `/api/health`.

**Comment by clueoded** [comment]
Thank you.
