### ISSUE TITLE
Need to add cloudwatch metrics to the Metabase

### ISSUE THREAD

**Issue by ayush121195** [metabase/metabase#11620]
Hello Team,

I am new in Metabase. I have an EC2 instance, aws cloudwatch is already set up there and I want to use Metabase to check the data. Is it feasible using Metabase? Can anyone tell me how we can achieve that?

Thanks
Ayush

**Comment by flamber** [comment]
Hi @ayush121195 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:
