### ISSUE TITLE
Refresh the page after setting the filter conditions, other filter settings will automatically add the same conditions;

### ISSUE THREAD

**Issue by OLEREO** [metabase/metabase#11637]
**Describe the bug**
When there are multiple filters in my dashboard, once one or more of them are set. When you refresh the page in your browser, the filter criteria on the page automatically become messy.

**To Reproduce**
Check out gif

**Expected behavior**
After refreshing, keep the correct filters.

**Screenshots**
![image](http://q3nx0fqwt.bkt.gdipper.com/20200106095659724.gif)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_231-b11",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_231",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.231-b11",
    "os.name": "Mac OS X",
    "os.version": "10.14.6",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.0",
      "date": "2019-12-19",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

- Chrome 79.0.3945.88
- OS X 10.14.6
- MySQL
- 0.34.0
- Metabase hosting environment: (Jar-file)

**Severity**
It is not serious, and the actual work is less troublesome.

**Comment by flamber** [comment]
Hi @OLEREO 
Looks like a duplicate of #5313. If you agree, then please close this and upvote the other issue :+1:
See https://github.com/metabase/metabase/issues/5313#issuecomment-570984864 for workaround.

**Comment by OLEREO** [comment]
> Hi @OLEREO
> Looks like a duplicate of #5313. If you agree, then please close this and upvote the other issue 👍
> See [#5313 (comment)](https://github.com/metabase/metabase/issues/5313#issuecomment-570984864) for workaround.

Yes, thank you very much for answering my question.
