### ISSUE TITLE
The number at the top is not displayed when multiple histogram are superimposed and compared

### ISSUE THREAD

**Issue by kinbod** [metabase/metabase#11634]
The number at the top is not displayed when multiple histogram are superimposed and compared.

**Comment by mazameli** [comment]
A current limitation of chart labels, which were introduced in version 0.34, is they only work on single-series charts (charts with a single metric). We plan on expanding this feature over time.

**Comment by kinbod** [comment]
> A current limitation of chart labels, which were introduced in version 0.34, is they only work on single-series charts (charts with a single metric). We plan on expanding this feature over time.

ok, I think make it as an selection will be a good feature.

**Comment by flamber** [comment]
Is this a duplicate of #11585 or just very related? I'm not sure what "superimposed" and "compared" means - combining cards on the dashboard?

**Comment by kinbod** [comment]
> Is this a duplicate of #11585 or just very related? I'm not sure what "superimposed" and "compared" means - combining cards on the dashboard?

yes, it is. combining cards on the dashboard then top number disappeared

**Comment by flamber** [comment]
Closing in favor of #11585
