### ISSUE TITLE
Trend/SmartScalar shows 'Nothing to compare for previous {month}' when %change is 0

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#11631]
**Describe the bug**
When calculating % growth in the Trend visualization, when the values are the same, the visualization shows `Nothing to compare for the previous month.`

**Logs**
Nothing relevant.

**To Reproduce**
1. Go to "Ask a question"
2. Select "Native query"
3. If necessary, select the "Sample Dataset"
4. Paste this query into the SQL editor:
    ```sql
    select `period`, sum(`count`)
    from
    (select timestamp '2019-10-01' as `period`, 9 as `count`
    union all
    select timestamp '2019-11-01' as `period`, 9 as `count`)
    group by `period`
    order by `period`
    ```
5. Run query
6. Click on visualization button, select "Trend"
7. Note that visualization shows "Nothing to compare for the previous month."
8. Change the `9` above to something different (`8`) and re-run the query
9. Note that visualization now shows "11.11% • was 9 last month"

**Expected behavior**
I would expect the visualization to display "0% • was 9 last month"

**Screenshots**
Screenshot of "error" state:
![image](https://user-images.githubusercontent.com/1512/71747543-cc545280-2e24-11ea-9f49-192e14eae934.png)

Screenshot of correct change:
![image](https://user-images.githubusercontent.com/1512/71747564-de35f580-2e24-11ea-9901-245fda8f60ab.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.9.184-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Annoying in cases where % growth is 0.

**Additional context**
Possibly related to #11630

**Comment by sbelak** [comment]
The data coming from the server is correct, I'm guessing this is some 0==false JS nonsense.

**Comment by ndrozd** [comment]
May be related to this issue, when there's only one row in a result – trend shows "**Nothing to compare for the previous week**" even if the data is from previous week and it should write something like "no data for this week".
@sbelak

**Comment by ndrozd** [comment]
I guess when there's no data for one of requested weeks we should have 0 to be able to compare. But now query returns just one week and it breaks the smart number...

**Comment by sbelak** [comment]
Previous here is meant more as "one before" we don't want to make the assumption that the data is until now, you may well have a time series that ended a year ago or some such.

**Comment by ndrozd** [comment]
I mean that it'll say same "Nothing to compare for the previous week" in both cases where there's just one week available. Not taking into account that it may be earliest week or the latest.
