### ISSUE TITLE
No UI feedback when updating profile

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#11647]
When a user changes their profile information (at `/user/edit_current`) and clicks the _Update_ button, there is no feedback to the user that the update was attempted, or its outcome. This could lead users to believe that nothing happened.

**Steps to reproduce**
1. Log in
2. Click on the gear icon in the top left, and select _Account settings_
3. Change your first/last name
4. Click the _Update_ button
5. Observe no feedback

**Expected behavior**
The user should be notified that the update was successful, similar to how the password change form does.

**Information about your Metabase Installation:**

- Metabase version: current `master`
- Browser: Firefox 71.0 (Ubuntu)

**Severity**
Very low. It's just a minor UX issue.

**Comment by morganhankins** [comment]
Looks like this issue was resolved by recent cleanup of Form code: 98a4197bd53844e4b9daeb6f9daeef5754ac992f

Now, after successfully updating the account settings, you get:

![image](https://user-images.githubusercontent.com/674285/74387195-c13dfc00-4dac-11ea-8367-7726b66349b2.png)

**Comment by flamber** [comment]
Fixed by PR #11087 on `master`.
