### ISSUE TITLE
MongoDB date literals no longer automatically bucket by day

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1164]
I have a table in Mongo with a native Mongo Date field e.x. `insert({ name: "Tom", created: new Date() })`. This shows up in schema as a `DateField`.

However:

1. The field does now show up in the bare rows at all (it isn't marked as hidden in the metadata)
2. It does show up as a groupable field, but does not actually group by any time granularities (i.e. appears to be treated as a string?)
3. Relative filters don't seem to have any effect (every relative time filter returns all rows, even ones with no date at all)
4. For Specific date filters the end date is exclusive vs on the SQL databases it's inclusive. e.x. if I select Oct 6 - Oct 7 it does not return dates on Oct 7, but if I select Oct 7 - Oct 8 it does return dates on Oct 7.

**Comment by andrewcurioso** [comment]
Any ETA on this one? It makes things like "Signups by date" more or less impossible to do with Mongo.

**Comment by camsaul** [comment]
@andrewcurioso Should make it into our next release in a week or so

**Comment by andrewcurioso** [comment]
@camsaul Awesome. Thanks for the update.
