### ISSUE TITLE
Refactor `SettingsSingleSignOnForm`

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#11657]
The use of `domain`/`domainValue` is confusing. Do we need to overwrite `domain`'s `value` like we are?

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx

@tlrobinson pointed out that this should be updated to use the new form components: metabase/containers/Form.

**Comment by flamber** [comment]
Closing in favor of #11659
