### ISSUE TITLE
Errors on Google Auth settings page don't look great

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#11659]
Screenshot: ![image](https://user-images.githubusercontent.com/23798/72025864-28363580-3282-11ea-9dee-0f24f0d4e2e2.png)

The error in the screenshot was triggered by changing and saving the email domain value multiple times.

@tlrobinson mentioned that this form should be ported to the new form code.

**Comment by flamber** [comment]
_Originally post by Paul on #11657_
> The use of `domain`/`domainValue` is confusing. Do we need to overwrite `domain`'s `value` like we are?
> 
> https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx
> 
> Tom pointed out that this should be updated to use the new form components: metabase/containers/Form.
