### ISSUE TITLE
"Add to dashboard" popup shown when starting a new question

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11666]
**Describe the bug**
Saving a question and adding it to a dashboard causes the next question to start with the "Add to dashboard" popup.

**To Reproduce**
1. Create a new simple question and save it.
2. Add the question to a dashboard when prompted to do so.
3. Click on "Create a question" and choose "Simple question" again.
4. Choose same table (any different should also exhibit the same behaviour).
5. Observe you are presented with the same "Add to dashboard" popup.

**Expected behavior**
I expect the question to start with clean state: just the table and no popup from the previous time.

**Screenshots**
![image](https://user-images.githubusercontent.com/30152071/72072993-569e2a00-32ef-11ea-9ec3-6dbef750b6a5.png)

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
It's a nuisance that we need to explain to our customers.

**Additional context**
I actually see this restoration of state in multiple places, think this has to do with the way React works, can try to provide more examples if needed.

**Comment by dacort** [comment]
Hi @andreychirikba - thanks for filing this with the detailed repro steps. I can confirm this is an issue on v0.34.0. 

If there are other specific places you're seeing this, please do let us know.

**Comment by walterl** [comment]
Sounds somewhat similar to #10672. Maybe there's a common cause.

**Comment by paulrosenzweig** [comment]
Fixed by #11707
