### ISSUE TITLE
Feature for relative date queries in MondoDb

### ISSUE THREAD

**Issue by teotia-bizSystems-curefit** [metabase/metabase#11669]
**Is your feature request related to a problem? Please describe.**
Metabase fails to parse mongodb relative date queries like `{$lte: new Date().getTime()-(1*60*60*1000) }`

**Describe the solution you'd like**
We implemented a custom solution for us over version 0.30.x by implementing `RelativeDateTime("Date string("2019-12-12")" - inetegerOffset)` method in `src/metabase/driver/mongo/query_processor.clj` as
```
:RelativeDateTimeValue  (fn [unit]
                                (du/ndays unit "yyyy-MM-dd"))
``` 

```
(defn ndays
      ([^Integer unit ^String date-format]
        (def relative-var (* unit 86400000))
        (println (format-date date-format (- (System/currentTimeMillis) relative-var)))
        (format-date date-format (- (System/currentTimeMillis) relative-var))))
```

**Additional context**
Now, we're looking to upgrade metabase version for us. Since a lot of code base has changed since v30.x, it seems very difficult to track where to make code changes. It will be of great help if someone can guide.

**Comment by dacort** [comment]
@teotia-bizSystems-curefit Take a quick look at the most recent release of Metabase (0.34.0) - we added functionality in for [Mongo variables](https://www.metabase.com/blog/0.34/index.html) that might be helpful to you. You can find documentation on using the variables [here](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html), but here's a couple examples to get you started:

If you just want a raw date picker, you select the "Date" filter type and use a query like this:
` [{"$match":{"birthdate":{"$lte": {{ something }} }}}]`

You can also use a field filter that maps to a specific field, and you can select a few different options with respect to single dates or relative dates.
`[ {$match: {{date_var}} } ]`

If those match your needs, feel free to close this issue. Thanks!

**Comment by teotia-bizSystems-curefit** [comment]
@dacort 
Thanks for the information. The variable feature allows us to define a variable and set corresponding values through UI.
What we exactly need is a feature where we can pass relative date parameters in native query itself rather than through UI.

**Comment by teotia-bizSystems-curefit** [comment]
This feature will also work for us. Thanks a lot. Closing the issue.
