### ISSUE TITLE
we cant find any tables when conn to dble or mycat?

### ISSUE THREAD

**Issue by KU4NG** [metabase/metabase#11664]
we cant find any tables when conn to dble or mycat，but i can use ‘show tables’ to find all tables。

**Comment by dacort** [comment]
Hi @KU4NG - do you have more details on this? Is this a bug or more of a general question? Feel free to post over on Discourse ( https://discourse.metabase.com/ ) to see if other folks have used dble or mycat and please include specific details and/or error messages.
