### ISSUE TITLE
Switch Column to rows

### ISSUE THREAD

**Issue by jiwaniakbarpp1** [metabase/metabase#11668]
Hi,
I have a query like below which returns a single row and 5 columns. I would like to display it 5 rows in a single column. Basically switch columns to rows.
SELECT
    round(sum(case when Column1 = 'ABC' then 1 0 end)) AS "CL1",
    round(sum(case when Column2 = 'XYZ' then 1 else 0 end)) AS "CL2",
    round(sum(case when Column3 = 'PQR' then 1 else 0 end)) AS "CL3",
    round(sum(case when Column4 = 'EFG' then 1 else 0 end)) AS "CL4",
    round(sum(case when Column5 = 'HIJ' then 1 else 0 end)) AS "CL5",
FROM mytable
where {{Filter1}} and {{filter2}} and {{filter3}}

**Comment by mazameli** [comment]
Are you asking how to do that in SQL, or asking for Metabase to have a feature to swap columns and rows in table settings?
