### ISSUE TITLE
Visualization type cannot be saved when is only one result

### ISSUE THREAD

**Issue by grimxd** [metabase/metabase#11675]
**Describe the bug**
Since updating from 0.33 to 0.34, on sql questions with only 1 row as result I cannot save the visualization type. Every time I refresh the question it reverts back to table visualization and makes a new question.
If I have more than 1 row as a result the visualization works. If I downgrade to 0.33.x it works again.

**To Reproduce**
1.Create a question with 1 row as result
2.Set visualization to bar
4. Save
3. Reload question

**Expected behavior**
The visualization should be saved.

**Screenshots**
Same issue even when I save before reload. When I open the question it automatically creates a new question from the old one with a table visualization. 
![Visualization error](https://i.imgur.com/FZcEQL8.gif)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-VI",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10-post-Ubuntu-0ubuntu1.118.04",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10-post-Ubuntu-0ubuntu1.118.04",
    "os.name": "Linux",
    "os.version": "4.15.0-74-generic",
    "user.language": "en",
    "user.timezone": "Europe/Bucharest"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flyingmachine** [comment]
related: #11368

**Comment by mazameli** [comment]
Repro'd

**Comment by matthewrj** [comment]
I'm getting the same for a funnel visualisation with 7 rows, 2 columns. Whenever I enter the edit screen, it resets to table.

**Comment by flamber** [comment]
@matthewrj 
Which version of Metabase? Native or Custom question? Can you provide steps-to-reproduce?

**Comment by grimxd** [comment]
Updated from 0.33 to 0.35.3 and somewhere along the way this got fixed for me.

**Comment by flamber** [comment]
@grimxd I can still reproduce on Sample Dataset with the following query as bar visualization:
```
SELECT YEAR(CREATED_AT), SUM(PRICE) FROM PRODUCTS GROUP BY YEAR(CREATED_AT) LIMIT 1
```
![image](https://user-images.githubusercontent.com/1447303/80860837-a9b73680-8c6a-11ea-8d06-e2bb48720bb6.png)
When saving the question and reloading, it shows a table:
![image](https://user-images.githubusercontent.com/1447303/80860847-bdfb3380-8c6a-11ea-941b-6c3e8ab6a326.png)
