### ISSUE TITLE
Rows count is not showed in Russian version

### ISSUE THREAD

**Issue by citizen-seven** [metabase/metabase#11674]
**Describe the bug**
Same question in two different languages has different footers. One shows number of rows, the other doesn't.

**To Reproduce**
1. Change browser language to Russian
2. Run any query
3. See empty row count

**Expected behavior**
Row count in Russian version.

**Screenshots**
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/14357228/72144243-49457600-33a9-11ea-83d2-6f0fc859c2cb.png">
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/14357228/72144250-4e0a2a00-33a9-11ea-8a5e-ee5f5841b0fc.png">

**Information about your Metabase Installation:**

> {
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.4.0-116-generic",
    "user.language": "en",
    "user.timezone": "Europe/Moscow"
  },
  "metabase-info": {
    "databases": [
      "bigquery",
      "mysql",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-16",
      "tag": "v0.33.7.3",
      "branch": "release-0.33.x",
      "hash": "7ee7193"
    },
    "settings": {
      "report-timezone": "Europe/Moscow"
    }
  }
}

**Severity**
Blocking some users, annoying. We have to download or rerun the query with count(*).

**Comment by kdoh** [comment]
It looks like this is something specific in the Russian translation. I tested this out in German and the row count is showing up as I'd expect.

<img width="1680" alt="Bildschirmfoto 2020-01-13 um 11 43 25 AM" src="https://user-images.githubusercontent.com/5248953/72274407-21991c80-35fa-11ea-93f5-36b483f90d36.png">

Here are the associated strings for Russian [over on POEditor](https://poeditor.com/projects/po_edit?order=&filter=&per_page=20&id=200535&id_language=134&search=showing) which is where our community manages translation.

**Comment by citizen-seven** [comment]
I've already checked both English, Russian and German translation and I see no differences there. The translation was made 1 year ago and the row count used to work correctly previously. I don't see any reasons for it to fail...
