### ISSUE TITLE
Schema sync issue, only on certain Metabase instances, with certain schemas.

### ISSUE THREAD

**Issue by BrieucVanThienen** [metabase/metabase#11677]
Hello,

I am experiencing some issues with the sync of the database schema.

It happens that newly created tables / columns do not show on Metabase, even after triggering the sync. More precisely, the tables / columns can be queried, but they do not show under the data models page and the tables / columns cannot be used as filters in the queries.

We run different instances of Metabase at our company for our different departments. What is weird is that I am only facing such issues on certains instances, and not all.

For now, this issue only arises with only one of our schemas (DBT: https://www.getdbt.com/).

thanks in advance for your availability and support!

Brieuc Van Thienen

**Comment by mazameli** [comment]
Sync can sometimes take a bit. Do you still not see the added tables / columns now?

**Comment by camsaul** [comment]
@BrieucVanThienen you may need to refresh the page (this is a known issue). Can you give that a try?

**Comment by flamber** [comment]
Closing, since no reply. Likely a duplicate of #10330. Related to #11354
