### ISSUE TITLE
Support "Contains", "Begins With", etc for Category Filter Widget

### ISSUE THREAD

**Issue by tuaris** [metabase/metabase#11682]
When using field filter variables the Filter Widget type "Category" should use the standard options: "is, is not, contains, does not contain, is empty, not empty, starts with, ends with"

**Describe alternatives you've considered**
I tried using a basic SQL parameter, but this is limited and clunky.  

**How important is this feature to you?**
It improves the quality of life for us who rely on custom SQL.

**Additional context**
The query builder in the notebook is able to do this.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #8219
