### ISSUE TITLE
How to add custom property or field on chart property box

### ISSUE THREAD

**Issue by binodsarkar** [metabase/metabase#11694]
I want to add custom input box on chart property box. Suppose there will be two dropdowns, left and right. I have found that we can pass json for property box but no configuration found mentioned one.

**Comment by mazameli** [comment]
If I'm understanding you correctly, it's extremely unlikely will add the ability to add in custom chart property input boxes or settings any time soon. 

If you have more general how-to questions, please check out our discussion forum: https://discourse.metabase.com/
