### ISSUE TITLE
about GroupOfUniqueNames and groupOfNames

### ISSUE THREAD

**Issue by Duan-fei** [metabase/metabase#11697]
When I use GroupOfUniqueNames, I can't achieve the mapping effect。But using GroupOfNames is OK. Can you also support GroupOfUniqueNames!
![image](https://user-images.githubusercontent.com/31236990/72236609-9f692200-3612-11ea-9b01-9193b7193f05.png)  
This is the log of LDAP！

**Comment by hcpony** [comment]
This issue is still present in the opensource version, and the membership filter settings to use (uniqueMember={dn}) to support the `GroupOfUniqueNames` is only available in pro and enterprise version?
