### ISSUE TITLE
Starting repl from Emacs in windows 10 results in error

### ISSUE THREAD

**Issue by nvercamm** [metabase/metabase#11695]
**Describe the bug**
When starting the repl in windows 10 within emacs an error occurs.

**Logs**
{:clojure.main/message
 "Syntax error (InvalidPathException) compiling at (C:\\Users\\Nick\\AppData\\Local\\Temp\\form-init5404356083308189565.clj:1:107).\r\nIllegal char <:> at index 2: /D:/playground/metabase/resources/modules\r\n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 1,
  :clojure.error/column 107,
  :clojure.error/source "form-init5404356083308189565.clj",
  :clojure.error/path "C:\\Users\\Nick\\AppData\\Local\\Temp\\form-init5404356083308189565.clj",
  :clojure.error/class java.nio.file.InvalidPathException,
  :clojure.error/cause " /D:/playground/metabase/resources/modules"},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message "Syntax error compiling at (C:\\Users\\Nick\\AppData\\Local\\Temp\\form-init5404356083308189565.clj:1:107).",
    :data
    {:clojure.error/phase :compile-syntax-check, :clojure.error/line 1, :clojure.error/column 107, :clojure.error/source "C:\\Users\\Nick\\AppData\\Local\\Temp\\form-init5404356083308189565.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7648]}
   {:type java.nio.file.InvalidPathException, :message "Illegal char <:> at index 2: /D:/playground/metabase/resources/modules", :at [sun.nio.fs.WindowsPathParser normalize nil -1]}],
  :trace
  [[sun.nio.fs.WindowsPathParser normalize nil -1]
   [sun.nio.fs.WindowsPathParser parse nil -1]
   [sun.nio.fs.WindowsPathParser parse nil -1]
   [sun.nio.fs.WindowsPath parse nil -1]
   [sun.nio.fs.WindowsFileSystem getPath nil -1]
   [metabase.util.files$get_path_in_filesystem invokeStatic "files.clj" 22]
   [metabase.util.files$get_path_in_filesystem doInvoke "files.clj" 21]
   [clojure.lang.RestFn invoke "RestFn.java" 425]
   [clojure.lang.AFn applyToHelper "AFn.java" 156]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$apply invoke "core.clj" 660]
   [metabase.util.files$get_path invokeStatic "files.clj" 30]
   [metabase.util.files$get_path doInvoke "files.clj" 24]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [metabase.util.files$do_with_open_path_to_resource invokeStatic "files.clj" 110]
   [metabase.util.files$do_with_open_path_to_resource invoke "files.clj" 101]
   [metabase.plugins$extract_system_modules_BANG_ invokeStatic "plugins.clj" 58]
   [metabase.plugins$extract_system_modules_BANG_ invoke "plugins.clj" 55]
   [metabase.plugins$load_BANG_ invokeStatic "plugins.clj" 124]
   [metabase.plugins$load_BANG_ invoke "plugins.clj" 122]
   [metabase.plugins$eval48051$fn__48052 invoke "plugins.clj" 128]
   [clojure.lang.Delay deref "Delay.java" 42]
   [clojure.core$deref invokeStatic "core.clj" 2320]
   [clojure.core$deref invoke "core.clj" 2306]
   [metabase.plugins$load_plugins_BANG_ invokeStatic "plugins.clj" 130]
   [metabase.plugins$load_plugins_BANG_ invoke "plugins.clj" 130]
   [user$eval48057 invokeStatic "form-init5404356083308189565.clj" 1]
   [user$eval48057 invoke "form-init5404356083308189565.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.Compiler loadFile "Compiler.java" 7574]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "Illegal char <:> at index 2: /D:/playground/metabase/resources/modules",
  :phase :compile-syntax-check}}

**To Reproduce**
1. Open emacs
2. find file proj.clj within metabase
3. C-u M-x cider-jack-in
4. add with-profiles +include-all-drivers

**Expected behavior**
I would expect it to run without problems

**Screenshots**

**Information about your Metabase Installation:**
Master version of metabase

**Severity**
I'm in the process of writing a driver for solr. Not being able to use the repl slows down development and testing the driver

**Additional context**

**Comment by camsaul** [comment]
@nvercamm I usually use the [WSL 2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/) when I'm developing with a Windows PC, and I've used the CIDER REPL without issue that way. So until we have a fix for this issue that's something you can try.

**Comment by nvercamm** [comment]
@camsaul Thanks for the swift reply. I actually have implemented a fix (small code change in files.clj). So if you welcome a pull request I'll be glad to make one. Although not sure what tests should be executed.

**Comment by camsaul** [comment]
@nvercamm a PR is welcome. If you submit it as-is I can try to figure out how to test it

**Comment by nvercamm** [comment]
#11705

**Comment by nvercamm** [comment]
Here you go #11705
