### ISSUE TITLE
Field values scan doesn't find all values if initial values are all or mostly null

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#11700]
When scanning for Field values during the sync process we scan the first 5000 rows, regardless of whether the value of the column in question is null. This is done to ensure we don't destroy computers with very large datasets by doing a full table scan.

If you have a table where the first 5000 values all happen to be NULL, this part of the sync process won't capture the correct values.

PR #11486 was a proposed solution for this issue, by adding a `WHERE field IS NOT NULL` clause to the query. I believe this approach would lead to unacceptable performance issues; the following is from my review of the PR:

> I'm not confident this fix won't introduce unacceptable performance issues for people with very large datasets. The code being changed is used across all of the databases we support, and with large datasets Metabase would potentially be scanning millions or even billions of rows looking for the first 5000 non-null values, which it may never find. 
> 
> It would probably make more sense to do a nested query along these lines (example in SQL since I am better at writing it off the top of my head)
> 
> ```sql
> SELECT DISTINCT some_field
> FROM (
>   SELECT some_field
>   FROM some_table
>   LIMIT 100000
> ) t
> WHERE some_field IS NOT NULL
> LIMIT 101 -- if there are more than 100 (?) values, we don't want to store the values
> ```
> 
> (i.e., scan up to hundred thousand rows, and select up to 101 distinct non-null values. IIRC the limit for storing field values is 100 distinct values. Not sure if that number is actually correct or not, so don't quote me on that)
> 
> That upper bound would at least prevent a potentially massive full table scan. Also I think that it would be a better long-term change to rework the way this step is done in the first place, and generate optimized queries for different databases instead of compiling the generic MBQL query currently used. 
> 
> Since this would require reworking some of our driver architecture I think it's an issue the core team would best be equipped to address. 

So I think we should investigate the approach I suggested in that PR and rework the way we do distinct value scans for Fields so we can rectify the issues where initial rows are all or mostly null

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Possibly related: #5267

**Comment by sbelak** [comment]
Possibly related: #6924

**Comment by sbelak** [comment]
This approach also makes any estimates/sketches of the data difficult. Currently we fingerprint for things such as % of null values, and I'm pretty certain we'll sooner or later do some quintile sketches as well. I'd much rather we use a pagination-like approach with cap where we fetch the next N rows if all are null, trying up to M times.

**Comment by johnbacon** [comment]
> If you have a table where the first 5000 values all happen to be NULL, this part of the sync process won't capture the correct values.

What would it take to scan the latest 5000 rows? In my use case (and many others), I imagine new columns are being added to old tables. By scanning the oldest rows, this is guaranteeing all columns are NULL in our use case.

**Comment by dpsutton** [comment]
A couple thoughts.

1. The field values query is 
```clojure
{:breakout [[:field-id (u/get-id field)]]
 :limit    max-results}
```

This emits (for pg) sql roughly like:

```sql
SELECT "public"."times"."stuff" AS "stuff"
FROM "public"."times"
GROUP BY "public"."times"."stuff"
ORDER BY "public"."times"."stuff" ASC
LIMIT 5000
```

I believe the limit is not on the number of rows scanned for distinct values but the number of distinct values returned. In a sparse column, this could be an entire table scan. Depending on the optimizer, this might always be a full table scan for distinct values and then 5000 of those chosen.

2. This query is prompted in `metabase.sync.field-values` which is a separate step from fingerprinting. This query issues one query per field or column, whereas when we fingerprint we issue one query per table (`metadata-queries/table-rows-sample` from `metabase.sync.analyze.fingerprint`). So improvements to the field values query do not impact our fingerprinting stats (percent nils, percent emails, etc.) Changing this to a pagination style workflow wouldn't impact our fingerprinting at all.

**Comment by sbelak** [comment]
re 1: that's why Cam proposed a subselect. The inner limit is just to cap the scan to max 100000, the outer limit (and distinct) is what we're actually interested in. 

re 2: my comment was in reference to reusing the data (which is something that we've been discussing at the time), but is completely out of scope.

**Comment by salsakran** [comment]
One thing wrt pr #11486, and this is that the problem the user was trying to fix was not the presence of null in the 100 results, but rather all the field values being null. 

I'm not sure that introducing correctness problems (eg, in a 10B row table, having new values never come up) is worth removing one null. 

This is especially annoying because when new values are used, they won't ever show up if there are already 100k (or whatever number we use), and they'll be "fresh" in the user's minds. It's not like we're taking a sample, we're essentially saying that for a large database table, we'll never see new values unless they're writing back to old rows. For any kind of appending table (eg events), this means that every scan done after a table reaches 100k rows is a waste of cpu.

**Comment by sbelak** [comment]
The tradeoff is also users turning this off due to performance considerations (we get an issue around us firing these relatively expensive field values queries all the time every few months).

**Comment by luizarakaki** [comment]
Confirming. For SQL databases we run the following query and it doens't face this problem:

```
{:type :query,
 :database 2,
 :query {:breakout [[:field 1343 nil]], :limit 1000, :source-table 175},
 :middleware {:disable-remaps? true}}
```

```
{:query
 "SELECT \"uploads\".\"addresses_20230704170136\".\"nj\" AS \"nj\" FROM \"uploads\".\"addresses_20230704170136\" GROUP BY \"uploads\".\"addresses_20230704170136\".\"nj\" ORDER BY \"uploads\".\"addresses_20230704170136\".\"nj\" ASC LIMIT 1000",
 :params nil}
```
