### ISSUE TITLE
Question filter on Description type fields does not work, not filter can be applied

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#11721]
**Describe the bug**
When using a question filter on a field set to Description in the Metabase data model, a filter cannot be applied at all to this field.

**Logs**
No errors or useful output in javascript console

**To Reproduce**
1. In the Metabase data model for Sample Dataset > Products, set the type of the Title field to "Description" - *Note that "Description" seems to appear 2 times in that list.*
2. Ask a question > Simple question > Sample Dataset > Products
3. Filter button on top right now no longer includes "Title" field - *I'm not sure if this is intended*
4. Click the "Title" column header > Filter
5. There seems to be no way of enabling the "Update filter" button. Tried selecting some item, or typing something but never seemed to enable the button.
6. Tried "Is", "Contains", "Starts with", "Is empty" but could get it to do anything.
7. No filter can be applied to that field.
8. Same with the "Reviews" > "Body" field (which is already a Description)

**Expected behavior**
I expect to be able to filter by "Description" fields when building questions.

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/72401247-5ea70f80-37b0-11ea-9389-1902b273da8f.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_101-b13",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_101",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.101-b13",
    "os.name": "Windows 7",
    "os.version": "6.1",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.1",
      "date": "2020-01-13",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Severity**
I've just changed the field type to something different. There's a work around but only if you're an admin. A user pointed it out to me after quite a bit of frustration, they were about to to resort to exporting it all to Excel and doing it there which I'd really like to get avoid for something this simple.

**Comment by flamber** [comment]
This was fixed long ago, I cannot reproduce on 0.41.2
