### ISSUE TITLE
still having TIMESTAMP_ADD does not support the YEAR date part at issue

### ISSUE THREAD

**Issue by AgentBlond** [metabase/metabase#11725]
Bug Description: 
I am using metabase with bigquery and since the new update on 0.34 there is a bug when it comes to Date Ranges. Whenever I want to apply a date filter I get the following error message: TIMESTAMP_ADD does not support the YEAR date part at.

Can you let me know when this is fixed, please?

**Screenshots**
![image](https://user-images.githubusercontent.com/22956171/72443070-fe16d300-37ad-11ea-8a4f-b8b49afb5bd7.png)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome Version 78.0.3904.108
- Your operating system: Mac OS Catalina
- Your databases: BigQuery
- Metabase version: 0.34.1
- Metabase hosting environment: Docker

Severity
It is super urgent, because most of our graphs are using the time dimension. If this error persists, we will need to look for another tool.

PS: This is my first bug report ever, so please be understanding :)

**Comment by HelenMertes** [comment]
Same here, got the error message for "month":
![image](https://user-images.githubusercontent.com/24734846/72601773-57017b00-3916-11ea-908b-39214aa06702.png)

Your browser and the version: Chrome 79.0.3945.117 
Your operating system: Windows 10
Your databases: BigQuery
Metabase version:v0.33.3
Metabase hosting environment: Heroku

**Comment by dacort** [comment]
Need to ensure it works for weeks/quarters as well.

**Comment by camsaul** [comment]
Ok, looks like this is what's supported and what's not

<table>
    <thead>
        <tr>
            <th></th>
            <th>minute</th>
            <th>hour</th>
            <th>day</th>
            <th>week</th>
            <th>month</th>
            <th>quarter</th>
            <th>year</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>datetime_add</td>
            <td>✅</td>
            <td>✅</td>
            <td>✅</td>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
        </tr>
        <tr>
            <td>date_add</td>
            <td>❌</td>
            <td>❌</td>
            <td>✅</td>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
        </tr>
        <tr>
            <td>timestamp_add</td>
            <td>✅</td>
            <td>✅</td>
            <td>✅</td>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
        </tr>
    </tbody>
</table>

**Comment by camsaul** [comment]
Not being able to add a minute or an hour to a `DATE` field absolutely makes sense, but I didn't realize the various BQ `_add` functions don't support anything bigger than a day. ([dox](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#timestamp_add))

Should be easy enough to work around that.

**Comment by dacort** [comment]
Huh, well that's interesting! 

Curious about the `date_add` piece from the table above, though, based on [DATE_ADD](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_add) docs looks like it does support week/month/quarter/year?

**Comment by camsaul** [comment]
Yeah, as does `DATETIME_ADD`. That table should have been titled "what's currently working". So either my test was busted or we're coercing `date`/`datetime` columns to timestamp somewhere. I'll investigate.

**Comment by dacort** [comment]
Ah gotcha.

**Comment by camsaul** [comment]
so it turns out that it was actually doing the `date_add` and the like against `current_timestamp` which was why it wasn't working as expected.

**Comment by camsaul** [comment]
K got things working!

<table><thead><tr><th></th><th>minute</th><th>hour</th><th>day</th><th>week</th><th>month</th><th>quarter</th><th>year</th></tr></thead><tbody><tr><td>time_add</td><td>✅</td><td>✅</td><td>❌</td><td>❌</td><td>❌</td><td>❌</td><td>❌</td></tr><tr><td>datetime_add</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td></tr><tr><td>date_add</td><td>❌</td><td>❌</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td></tr><tr><td>timestamp_add</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td></tr></tbody></table>

**Comment by camsaul** [comment]
Fixed by #11838
