### ISSUE TITLE
Cant find Mssql in the setup drop down 

### ISSUE THREAD

**Issue by viazerd** [metabase/metabase#11723]
Hey there, 

I recently downloaded the metabase repo from github after executing it , during the setup process I cant find the Mssql  in the drop, or selecting SQL should do the job ? 

Kindly help. 

Regards 
Sandeep

**Comment by flamber** [comment]
Hi @viazerd 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And you'll get better help if you provide more information - like version, OS, etc.
