### ISSUE TITLE
Pulse Ideas

### ISSUE THREAD

**Issue by cmwillett** [metabase/metabase#11729]
**Is your feature request related to a problem? Please describe.**
User thinks it's a little bit difficult to read the email data when multiple tables were sent in a row...

**Describe the solution you'd like**
I think it would be nice to be able to space out each question a little bit and/or add color/formatting to the emails... 

**Describe alternatives you've considered**
An alternative I thought of was adding a link to the email that points to the dashboard I have built for them, containing mostly the same data - however, this isn't possible either...

**How important is this feature to you?**
This isn't super serious to me, but the users I built this for have requested it from me.  I think they would be more likely to want to use this tool in the future with these implementations.

**Additional context**

**Comment by flamber** [comment]
Closing in favor of #3315 and #6659. Related to #10022
