### ISSUE TITLE
Don't set primary key for Druid Datasources

### ISSUE THREAD

**Issue by denisesenguel** [metabase/metabase#11736]
**Describe the bug**
The issue title says it all: whenever a new Druid datasource is created, one or several dimensions are automatically declared as type `Primary Key`, while the concept of a primary key does not apply in the case of Druid data schemas (see https://druid.apache.org/docs/latest/ingestion/schema-design.html)

**Expected behavior**
Just don't set a primary key for Druid! I would actually disable the possibility to select a primary / foreign key on Druid datasources altogether.

The problem occurs on..

- Druid 0.16.1
- Metabase 0.34.1 hosted on Docker with internal Postgres database

.. regardless of OS or browser.

**Severity**
It used to bother us a lot due to #11162, but as this is fixed is not even noticeable right now unless checking Admin > Data Model. I'm just worried it has other unwanted implications (now or in the future) that I'm not aware of PLUS it's just not right ;)

**Comment by sbelak** [comment]
Fixed via #12542
