### ISSUE TITLE
serialization docs may be incorrect

### ISSUE THREAD

**Issue by flyingmachine** [metabase/metabase#11730]
The serialization docs at https://www.metabase.com/docs/latest/enterprise-guide/serialization may be incorrect. The docs say to run these commands:

```
java -jar metabase.jar dump [dump_name] --user [example@example.com]
java -jar metabase.jar load [my_dump] --mode [skip/update] --on-error [continue/abort]
```

However, I just performed serialization, and the commands that worked were

```
java -jar metabase.jar dump-to-h2 [dump_name]
java -jar metabase.jar load-from-h2 [dump_name]
```

**Comment by sbelak** [comment]
I think that's a different serialization that is/was part of submarine/hosting: https://github.com/metabase/metabase-enterprise/blob/enterprise-release-1.33.x/src/metabase/cmd.clj

**Comment by mazameli** [comment]
Yeah, gonna close this as those docs refer to the user-facing EE serialization feature.
