### ISSUE TITLE
Heroku Update Out of Date

### ISSUE THREAD

**Issue by searchy2** [metabase/metabase#11756]
**Describe the bug**
Heroku deployments cannot be updated because the update repo is out of date (last updated over 1 year ago).

**Logs**
![MaxthonSnap20200119230922](https://user-images.githubusercontent.com/19896174/72700291-20dc1b00-3b11-11ea-9d14-fd1648d9c1f5.png)
Latest update is v34.0

![MaxthonSnap20200119224600](https://user-images.githubusercontent.com/19896174/72700301-289bbf80-3b11-11ea-8ef4-3198da865ec8.png)
Heroku update is v30.

**To Reproduce**
Follow update instructions at https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html#deploying-new-versions-of-metabase

**Expected behavior**
Update contains latest version of Metabase.

**Screenshots**
(See above)

**Information about your Metabase Installation:**
Heroku Deployment
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 OPR/65.0.3467.78",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-heroku-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "4.4.0-1057-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "US/Central"
    }
  }
}
```
**Severity**
Blocking upgrade. 

**Additional context**
Thanks for making Metabase!

**Comment by noppaz** [comment]
You can actually use the repository to update to 0.34.1. I can't understand exactly how it's done, but I guess it uses the stable tag version from the [Metabase core repo](https://github.com/metabase/metabase) somehow. The previous commits to add new versions to the deploy has been [empty commits](https://github.com/metabase/metabase-deploy/commit/cd62829a03d79a0ec13cf06e0c081d839c5680d0) to satisfy the last [Heroku upgrade instructions](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html#deploying-new-versions-of-metabase) but I guess those stopped to be necessary and therefore these empty commits stopped as well.

**Comment by searchy2** [comment]
Thanks for taking a look Noah (@noppaz)

Trying to update the local repo and then pushing the update doesn't work because the local repo thinks its already up to date. `git push -f heroku master` will output that everything is already up to date due to lack of updated tags. 

The solution might be to delete the local repository and run the update steps from a clean slate. I'll give that a try and report back!

**Comment by tlrobinson** [comment]
@searchy2 Did you add an empty commit?

> If there have been no new changes to the metabase-deploy repository, you will need to add an empty commit. This triggers Heroku to re-deploy the code, fetching the newest version of Metabase in the process.
>
> git commit --allow-empty -m "empty commit"
> git push -f heroku master

**Comment by dacort** [comment]
Hi @searchy2 - as @tlrobinson mentioned, try pushing an empty commit to your heroku git remote as mentioned in the bottom of the docs on [upgrading metabase](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html#deploying-new-versions-of-metabase).

The documentation is, unfortunately, out-of-date. I've created issue #11759 to remedy this and will close this issue for now. Feel free to reopen if there's a different issue.

**Comment by searchy2** [comment]
Thanks @noppaz , @tlrobinson , and @dacort for the help. I used `git commit --allow-empty -m "empty commit"` and it allowed me to update Metabase successfully.
