### ISSUE TITLE
filter connections window overflows window, hard to scroll

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1176]
example: there's another connection here, but scrolling in the filter pop-up window doesn't show it:

...because the pop-up window is already fully scrolled to the bottom, it's just overflowed beyond the window, so i had to scroll the window itself to see it:

minor, admittedly, but definitely confusing.

**Comment by agilliland** [comment]
going to close this as a duplicate of #1193 which will resolve this problem.
