### ISSUE TITLE
Can you disable Elastic Beanstalk URL or redirect it to your own?

### ISSUE THREAD

**Issue by thenicedeveloper** [metabase/metabase#11776]
Can you disable Elastic Beanstalk URL or redirect it to your own?

I feel that I had done this via a configuration file before.

I have already set the "NGINX_FORCE_SSL" but I am still able to access to app via the Beanstalk (http) url.

**Comment by dacort** [comment]
Hi @thenicedeveloper,

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It looks like there may be some relevant questions there on the Beanstalk URL: https://discourse.metabase.com/search?q=elastic%20beanstalk%20url

**Comment by dacort** [comment]
FYI, was working on something else and remembered we have some documentation on what you may be trying to do here: https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#setup-dns-cname-using-aws
