### ISSUE TITLE
Integrate newrelic with Metabase

### ISSUE THREAD

**Issue by ayush121195** [metabase/metabase#11795]
Do we have any option to integrate data from new relic?

**Comment by dacort** [comment]
Hi @ayush121195 - No plans for this at the moment. Feel free to ask on the forums if other people have integrated new relic data. https://discourse.metabase.com/

**Comment by mustmodify** [comment]
@ayush121195 any luck with this? We're trying to debug some Metabase slowness and are having a hard time seeing Metabase as anything but a black box... though to be fair, the person who set it up left the team.

**Comment by paoliniluis** [comment]
You can easily achieve this via their agent https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java/

**Comment by paoliniluis** [comment]
Unfortunately I don’t know, haven’t tried new relic with Metabase
