### ISSUE TITLE
ERROR: Heroku Database Exceeded 10,000 Rows

### ISSUE THREAD

**Issue by searchy2** [metabase/metabase#11802]
![MaxthonSnap20200126224010](https://user-images.githubusercontent.com/19896174/73150757-81c59f00-408d-11ea-8756-9487bfbc1d22.png)

Please feel free to close this issue if this is more appropriate for Discourse instead. 

I've searched the issues and documentation for steps to take to reduce the number of rows Metabase uses in the database. I was unable to find any information of assistance. 

The problem is Metabase's database keeps on growing and has now exceeded the limits of the free plan. I would like to delete unnecessary rows to restore usage and functionality.

1. Why does Metabase keep writing rows to the database? (logs perhaps?)
2. How do I cleanup the database to reduce the number of rows.

Thanks for making Metabase and taking a look at my questions!

**Comment by searchy2** [comment]
Any updates? I'm unable to use my Metabase instance anymore. I can definitely delete the instance and database but then I'll lose everything.

**Comment by flamber** [comment]
Hi @searchy2 
Without knowing which tables are taking up the rows, it's difficult to answer, but it's probably `query_execution` or `task_history`. You can truncate those tables, but always make a backup first!
You might want to upvote the following issues by clicking :+1: on the first post of each: #4155 #9688 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by raphodn** [comment]
I ran into the same issue (row limit on the free Heroku plan). Cleaning up `query_execution` and `task_history` helped me to go back under the 10k row limit.

1. First go to your Heroku dashboard, and select your Postgres instance.
2. In the Postgres DB dashboard, select Settings > Database Credentials > View Credentials.
3. Run the command `heroku pg:psql <postgresql-db-name> --app <heroku-app-name>`
4. List all your tables with `\d`. List all your tables with their size with https://stackoverflow.com/a/21738505
5. Truncate the two tables with `TRUNCATE query_execution;` and `TRUNCATE task_history;`
