### ISSUE TITLE
MongoDB query multiple collection

### ISSUE THREAD

**Issue by jeromemmiranda** [metabase/metabase#11801]
**Is your feature request related to a problem? Please describe.**
Currently we are using mongoose as a driver in our app. With mongoose, we are using Schema wherein you can specify relationships by passing a field "ref"

**Describe the solution you'd like**
Support JOIN/populate for referenced fields in mongodb

**Describe alternatives you've considered**
Currently we're trying to find other charting tool that supports the populate

**How important is this feature to you?**
Very important, other features on our app depends on this functionality.

**Comment by flamber** [comment]
Hi @jeromemmiranda 
It sounds like a duplicate of #1687 - or am I misunderstanding what you're looking for, if so, could you give a little more context?

**Comment by flamber** [comment]
Closing in favor of #1687
