### ISSUE TITLE
Documentation fonts are very low contrast

### ISSUE THREAD

**Issue by willscripted** [metabase/metabase#11808]
Your [documentation](https://www.metabase.com/docs/latest/) is rather hard to read.

https://contrast-ratio.com/#%23727879-on-white
https://contrast-ratio.com/#%239b9999-on-white

**Comment by mazameli** [comment]
The primary text on the page is 18px with a contrast ratio of 4.48:1 — only .02 less than the recommended contrast ratio for _smaller_ text. Do you personally find the text hard to read?

**Comment by willscripted** [comment]
> Do you personally find the text hard to read?

Yes

**Comment by jeff-bruemmer** [comment]
@willscripted We've bumped up the contrast on the [Metabase documentation](https://www.metabase.com/docs/latest/). Hope this helps. Cheers.
