### ISSUE TITLE
Joining a saved question with another table can lead to duplicate column names

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11811]
**Describe the bug**
A saved question, when joined with a different table that has the same column name, fails with the "duplicate column name" error. This same query succeeds when editing the saved question and joining the same table.

**To Reproduce**
1. Create a simple question on a table, e.g. t1 (id, name, t2_id).
2. Save the question.
3. Create a new simple question from the saved question.
4. Open the query editor and join another table, e.g. t2 (id, name) on t2_id = t2.id.
5. Observe the query fail with "duplicate column name" error.

**Expected behavior**
The join should work correctly, just as it works when one edits the saved question and adds a join to it (instead of starting a new question from the saved one).

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
A nuisance, as we have to explain this to customers and are unable to use saved questions in some cases.

**Additional context**
DBMS is MySQL 5.7.28.

**Comment by dacort** [comment]
Hi @andreychirikba 

I'm having trouble reproducing this, although I will admit I haven't tried on MySQL yet. Can you provide any server error logs or browser console errors that pop up when this happens for you?

Here is what I was trying to reproduce with Postgres:

1. Create two new tables
    ```sql
    create table t1 (id int, name varchar(255), t2_id int);
    create table t2 (id int, name varchar(255));
    ```

2. Insert some sample data into them
   ```sql
    insert into t1 values (1,'damon', 1), (2, 'alice', 1);
    insert into t2 values (1,'dacort'), (2, 'notdacort');
   ```

3. Repro using your steps above, but get results:
![image](https://user-images.githubusercontent.com/1512/73317225-31178880-41ea-11ea-826b-900b27d6edbd.png)

And a screenshot of my query editor:
![image](https://user-images.githubusercontent.com/1512/73317261-56a49200-41ea-11ea-9607-b2757b243435.png)

**Comment by flamber** [comment]
I'm fairly sure this is a duplicate of #10511. Happens when doing post-aggregated stuff.

**Comment by andreychirikba** [comment]
@flamber, looks like that, it was still on my todo list to provide step to reproduce, but I'll close it now.
