### ISSUE TITLE
Unable to migrate to Mysql - key was too long

### ISSUE THREAD

**Issue by mab18** [metabase/metabase#11810]
Hi,

**Describe the bug**
Next to use this script (https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2), I'd like migrate to Mysql (MariaDB).

I have this error and it's not works :

ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::1::agilliland failed.  Error: (conn=5820) Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`))]

**Logs**
...
01-28 11:30:16 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
01-28 11:30:16 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::1::agilliland failed.  Error: (conn=5820) Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`))]
01-28 11:30:16 WARN metabase.util :: auto-retry metabase.db$migrate_up_if_needed_BANG_$fn__21312@550a209c: Migration failed for change set migrations/000_migrations.yaml::1::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=5820) Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`))]
...
**To Reproduce**
launch this script : 
export MB_DB_TYPE=mysql
export MB_DB_DBNAME=mymetabase
export MB_DB_PORT=3306
export MB_DB_USER=mymetabase_user
export MB_DB_PASS=mymetabase_password
export MB_DB_HOST=my ip_host_of_mysql
/usr/bin/java -Xmx1024m -Xms768m -jar ./metabase.jar load-from-h2 ./mymetabase.db

- operating system: Ubuntu 18.04 LTS
- databases: MariaDB/v10.1.43
- Metabase version: (e.x. 0.34.1)
- Metabase hosting environment:  Jar-file on Ubuntu
- Metabase internal database: H2 want to migrate to MySQL)

**Comment by tnikkila** [comment]
I have the same problem. Running metabase in Docker on Ubuntu 18.04 LTS:
`
docker run --name metabase-migration -v /tmp/metabase_backup:/metabase-data \
-e "MB_DB_FILE=/metabase-data/metabase.db"\
-e "MB_DB_TYPE=mysql" \
-e "MB_DB_DBNAME=metabase" \
-e "MB_DB_PORT=3306"
-e "MB_DB_USER=metabase-user"
-e "MB_DB_PASS=metabase-password"
-e "MB_DB_HOST=ip"
metabase/metabase load-from-h2
`
Fails with:

Command failed with exception: Migration failed for change set migrations/000_migrations.yaml::1::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=229) Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`))]

**Comment by tnikkila** [comment]
I tried running the CREATE TABLE statement in MariaDB with same result: Specified key was too long; max key length is 767 bytes

Solution - as user root in MariaDB run:

SET GLOBAL innodb_file_format = Barracuda;
SET GLOBAL innodb_file_per_table = on;
SET GLOBAL innodb_default_row_format = dynamic;
SET GLOBAL innodb_large_prefix = 1;
SET GLOBAL innodb_file_format_max = Barracuda;

This allowed me to run the migration succesfully.

**Comment by mab18** [comment]
Hi, 
Where and how do you put these parameters ?

**Comment by tnikkila** [comment]
Hi,

I started the mysql client as root on the server:

sudo mysql -u root

and run the queries one by one. Also added the parameters
in /etc/mysql/mariadb.conf.d/50-server.cnf:

...
#
# * InnoDB
#
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
innodb_file_format = Barracuda
innodb_file_per_table = on
innodb_default_row_format = dynamic
innodb_large_prefix = 1
innodb_file_format_max = Barracuda

**Comment by mab18** [comment]
@tnikkila 
hi !
excellent solution !
this is working perfectly. My target is mariadb.
thanks 😉

**Comment by dacort** [comment]
Thanks @tnikkila for helping out here! 

Going to leave this open as it seems like something we should add documentation for.

**Comment by flamber** [comment]
`innodb_large_prefix` has been enabled by default since [MariaDB](https://mariadb.com/kb/en/innodb-system-variables/#innodb_large_prefix) 10.2.2 and [MySQL](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix) 5.7.7 (4-5 years old)
There's a note in the migration documentation about minimum recommended versions, but maybe it should specifically be called out as a requirement: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
@camsaul wrote a couple of weeks ago that he hadn't noticed this problem lately https://github.com/metabase/metabase/issues/2688#issuecomment-576833426, but maybe it's worth having check for? It was also noted in the `utf8mb4`-issue https://github.com/metabase/metabase/issues/10691#issuecomment-560211344

**Comment by camsaul** [comment]
We only support MariaDB 10.2 or MySQL 5.7 and above. Closing as won't fix

**Comment by mab18** [comment]
Hi
@camsaul 
Yes @tnikkila find the solution ! His solution corrects perfectly the problem. 
His solution FIX the problem.
Note that Mariadb version in Ubuntu 18.04.4 LTS (lastest LTS) is 10.1.44 actually ;-)

**Comment by flamber** [comment]
@mab18 Closing this as `Won't Fix` just means that Metabase is not going to implement any code, since the configuration needs to be set on MariaDB/MySQL server, so not something Metabase would be able to fix anyways. At most Metabase would be able to do a check and show an error.
The minimum recommended version is still MariaDB 10.2.2 and MySQL 5.7.7 with default config. You can most likely get Metabase to work with earlier versions, but then you need to do a few modifications to the database server configuration, like enabling `innodb_large_prefix`.

**Comment by mab18** [comment]
@flamber : Thanks for your clarifications ;-)
