### ISSUE TITLE
setting default date as yesterday

### ISSUE THREAD

**Issue by 61fffan** [metabase/metabase#11825]
I have current difficulty in setting the default date as yesterday if the date parameter is empty. The same code works on date fields, however, it doesn't work on timestamp fields that I still need to set the date parameter to run the code.
The one which works like this:
finished_at >= [[{{dateOfCreation}} #]]DATE_SUB(CURDATE(),interval '1' day)
This one doesn't work:
orders.created_at >= unix_timestamp([[{{dateOfCreation}} #]]DATE_SUB(CURDATE(),interval '1' day))

**Comment by dacort** [comment]
Hi @61fffan - this seems more like a question than a bug. Please try asking on the forum ( https://discourse.metabase.com/ ) to see if anybody can help there.

If you feel this is a bug, please reopen and provide more details including relevant server logs and diagnostics info as mentioned in the bug template.

Thanks!
