### ISSUE TITLE
Add OR support to Notebook mode filters in the Metabase FE

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#11836]
Designs to be copied over

**Comment by mazameli** [comment]
## Relevant docs
Product doc: https://docs.google.com/document/d/1PAyv_G0RYXc6Y7VuA8t50iq9L2TvULRHkPnZzZTI6qo/edit#

Sketch file:
https://share.goabstract.com/4d917585-8751-494b-b034-2f496fe484f0?

## Basic flow

### Start in the notebook with a couple basic filteres

![image](https://user-images.githubusercontent.com/2223916/73579803-61546680-4438-11ea-8c9d-fd2a0c426444.png)

### Add a new filter expression from the bottom of the filter popover

![image](https://user-images.githubusercontent.com/2223916/73579824-70d3af80-4438-11ea-94ce-4328743f4da2.png)

### Empty filter expression popover

![image](https://user-images.githubusercontent.com/2223916/73579844-7e893500-4438-11ea-8866-fedecf88654f.png)

### Filter expression typed in

![image](https://user-images.githubusercontent.com/2223916/73579858-8ba62400-4438-11ea-974f-1ae18a255d78.png)

### Filter expression added without a custom label

![image](https://user-images.githubusercontent.com/2223916/73579890-a1b3e480-4438-11ea-85bf-e128d8afa1e5.png)

### Filter expression added _with_ a custom label
![image](https://user-images.githubusercontent.com/2223916/73579919-bc865900-4438-11ea-84f6-854c6d5205af.png)

### Click on filter to edit expression

![image](https://user-images.githubusercontent.com/2223916/73579943-cc9e3880-4438-11ea-8a2b-cb4a9b1957ab.png)

### Filter expression without a custom label in View mode

![image](https://user-images.githubusercontent.com/2223916/73579992-e93a7080-4438-11ea-8861-ea4e38d09d8f.png)

### Filter expression with custom label in View mode

![image](https://user-images.githubusercontent.com/2223916/73579964-dcb61800-4438-11ea-9033-3c7511a95afe.png)

### Clicking on the filter opens the expression editor popover

![image](https://user-images.githubusercontent.com/2223916/73580016-fd7e6d80-4438-11ea-841c-a9b96ad3ebd1.png)
