### ISSUE TITLE
Missing cloud provider parameter for Snowflake connection

### ISSUE THREAD

**Issue by juanchristensen** [metabase/metabase#11852]
**Describe the bug**
Currently the full connection string for Snowflake is something like this:
<account>.<region>.<provider>.snowflakecomputing.com
e.g.
<account>.us-central1.gcp.snowflakecomputing.com

We are missing the <provider> parameter on the setup dialog.

**Workaround**
Setting the provider as a postfix of the region (i.e. 'us-central1.gcp') works.

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Mac OS X",
    "os.version": "10.14.6",
    "user.language": "en",
    "user.timezone": "America/Argentina/Buenos_Aires"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "snowflake"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.1",
      "date": "2020-01-13",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
Hi @juanchristensen 
If I understand you correctly, you're having problems with the deprecated region field, which now should be part of the account field, but for Metabase you still need to use the deprecated way of inputting.
If yes, then deprecated region is covered in #10142, so I'll close this issue.
If I misunderstood you, then please comment with more information and I'll re-open this issue.
