### ISSUE TITLE
Pinpoints on maps do not appear on a public panel

### ISSUE THREAD

**Issue by AndreLuizRego** [metabase/metabase#11855]
Pinpoints (data defined by latitude and longitude) on maps do not appear on a public panel. When used inside the query builder they are shown, but when accessed from a public link they are not. Please see images attached.

Accessed from public link:
![Tela02](https://user-images.githubusercontent.com/56892990/73756086-cadcb980-4745-11ea-9783-1200bd82f20f.PNG)

Accessed from query builder:
![Tela01](https://user-images.githubusercontent.com/56892990/73756087-cadcb980-4745-11ea-81a8-126c1b4e00c1.PNG)

**Comment by flamber** [comment]
Hi @AndreLuizRego 
Which version of Metabase? Please provide "Diagnostic Info" from Admin > Troubleshooting.
Are you hosting Metabase on it's own sub-domain (metabase.example.tld) or sub-directory (example.tld/metabase)?
Have you checked the browser console/network-tab for any 404-errors?
Are you using a non-default tile server? The OpenStreetMaps should look like this via Public link:
![image](https://user-images.githubusercontent.com/1447303/73939496-e41e6b00-48e9-11ea-817c-c091a196c6c5.png)

**Comment by AndreLuizRego** [comment]
Hello!

Here is my Metabase Diagnostic Info:

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-693.17.1.el7.x86_64",
    "user.language": "pt",
    "user.timezone": "America/Argentina/Buenos_Aires"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.0-snapshot",
      "date": "2019-09-22",
      "branch": "simple-sso",
      "hash": "60d2905"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

I can´t assure how Metabase was installed in our server, but I´m almost sure that all default options were maintained.

**Comment by flamber** [comment]
@AndreLuizRego You're not using the official release of Metabase, so you would need to talk to the people who created your version. Or use an official release: https://www.metabase.com/start/
I'm going to close the issue, since we cannot support third party versions.
