### ISSUE TITLE
Conditional formatting color range by min/max values should apply to not-null values only

### ISSUE THREAD

**Issue by funcius** [metabase/metabase#11875]
**Describe the bug**

When color range by min / max value is applied to a column including null values, the color range will not work.
![1](https://user-images.githubusercontent.com/13347213/74122705-12ac8680-4c07-11ea-813a-7c1b344b59da.png)

I have to arbitrarily define a min value (like 0) in order to make color range function.
![2](https://user-images.githubusercontent.com/13347213/74122716-1809d100-4c07-11ea-8221-5941d9002d16.png)

**Javascript error**

![3](https://user-images.githubusercontent.com/13347213/74123094-71becb00-4c08-11ea-9f0d-aeff7dfc180e.png)

**Comment by flamber** [comment]
Reproduced on `master` with following query on H2:
```
SELECT '0-1' AS "g", parsedatetime('2019-12-11', 'yyyy-MM-dd') AS "d", 17 AS "c" UNION ALL
SELECT '2-3' AS "g", parsedatetime('2019-12-11', 'yyyy-MM-dd') AS "d", 17 AS "c" UNION ALL
SELECT '4-5' AS "g", parsedatetime('2019-12-11', 'yyyy-MM-dd') AS "d", 15 AS "c" UNION ALL
SELECT '6-7' AS "g", parsedatetime('2019-12-11', 'yyyy-MM-dd') AS "d", 2 AS "c" UNION ALL
SELECT '8-9' AS "g", parsedatetime('2019-12-11', 'yyyy-MM-dd') AS "d", 15 AS "c" UNION ALL
SELECT '0-1' AS "g", parsedatetime('2019-12-12', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '2-3' AS "g", parsedatetime('2019-12-12', 'yyyy-MM-dd') AS "d", 13 AS "c" UNION ALL
SELECT '4-5' AS "g", parsedatetime('2019-12-12', 'yyyy-MM-dd') AS "d", 11 AS "c" UNION ALL
SELECT '6-7' AS "g", parsedatetime('2019-12-12', 'yyyy-MM-dd') AS "d", 1 AS "c" UNION ALL
SELECT '8-9' AS "g", parsedatetime('2019-12-12', 'yyyy-MM-dd') AS "d", 16 AS "c" UNION ALL
SELECT '0-1' AS "g", parsedatetime('2019-12-13', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '2-3' AS "g", parsedatetime('2019-12-13', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '4-5' AS "g", parsedatetime('2019-12-13', 'yyyy-MM-dd') AS "d", 14 AS "c" UNION ALL
SELECT '6-7' AS "g", parsedatetime('2019-12-13', 'yyyy-MM-dd') AS "d", 17 AS "c" UNION ALL
SELECT '8-9' AS "g", parsedatetime('2019-12-13', 'yyyy-MM-dd') AS "d", 5 AS "c" UNION ALL
SELECT '0-1' AS "g", parsedatetime('2019-12-14', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '2-3' AS "g", parsedatetime('2019-12-14', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '4-5' AS "g", parsedatetime('2019-12-14', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '6-7' AS "g", parsedatetime('2019-12-14', 'yyyy-MM-dd') AS "d", 8 AS "c" UNION ALL
SELECT '8-9' AS "g", parsedatetime('2019-12-14', 'yyyy-MM-dd') AS "d", 17 AS "c" UNION ALL
SELECT '0-1' AS "g", parsedatetime('2019-12-15', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '2-3' AS "g", parsedatetime('2019-12-15', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '4-5' AS "g", parsedatetime('2019-12-15', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '6-7' AS "g", parsedatetime('2019-12-15', 'yyyy-MM-dd') AS "d", null AS "c" UNION ALL
SELECT '8-9' AS "g", parsedatetime('2019-12-15', 'yyyy-MM-dd') AS "d", 14 AS "c"
```

**Comment by paoliniluis** [comment]
A workaround for this one would be to do a coalesce(field, 0) on every field that might return a null, then it will automatically populate a 0 on the null field and you won't have to do the manual setting

**Comment by funcius** [comment]
> A workaround for this one would be to do a coalesce(field, 0) on every field that might return a null, then it will automatically populate a 0 on the null field and you won't have to do the manual setting

Thanks for the suggestion.
This is actually the walkaround i'm using.
But the problem is if the normal range of value is far away from 0, say 800 to 1200, the occurrence of value 0 will distort the shades of color significantly.

**Comment by noahmoss** [comment]
I've noticed conditional formatting by min/max values is also broken if you try to apply it to a primary key/foreign key column.

**Comment by flamber** [comment]
@noahmoss That's a regression from when trying to fix issue 5816. PK/FK are now handled as strings in some areas. That also causes problems with sorting.

**Comment by gabesolomon10** [comment]
Is there a solid workaround for this?  I'm having a similar issue with a triangle chart like the above - I don't want the null values to have any color, but they do if I set the range as a custom value between 0 and 1:
![Screen Shot 2022-05-20 at 11 29 33 AM](https://user-images.githubusercontent.com/34111771/169561686-1e0cb7af-ed02-415d-afb6-ec95f5707cb6.png)

**Comment by gabesolomon10** [comment]
> > Is there a solid workaround for this? I'm having a similar issue with a triangle chart like the above - I don't want the null values to have any color, but they do if I set the range as a custom value between 0 and 1: ![Screen Shot 2022-05-20 at 11 30 49 AM](https://user-images.githubusercontent.com/34111771/169561947-5913998a-bc74-4e1c-ae22-d6bba28f2836.png)
> 
> Same problem here. Did you find any way around?

I don't think this is the greatest workaround ever, but we went with changing the color scale from white to green, so null values would be shown in white.  Then we used a custom scale based on our data to make it look as best we could.  Here are the settings we used:
<img width="346" alt="Screen Shot 2022-06-30 at 10 16 43 AM" src="https://user-images.githubusercontent.com/34111771/176700688-e6b780bc-cc6b-43df-9109-98a4a3fb8fec.png">

And the result:
<img width="1551" alt="Screen Shot 2022-06-30 at 10 18 21 AM" src="https://user-images.githubusercontent.com/34111771/176700883-a8cbd1e1-b179-47c5-98fc-357f1513db9f.png">

**Comment by lauroandrade** [comment]
> > > Is there a solid workaround for this? I'm having a similar issue with a triangle chart like the above - I don't want the null values to have any color, but they do if I set the range as a custom value between 0 and 1: ![Screen Shot 2022-05-20 at 11 30 49 AM](https://user-images.githubusercontent.com/34111771/169561947-5913998a-bc74-4e1c-ae22-d6bba28f2836.png)
> > 
> > 
> > Same problem here. Did you find any way around?
> 
> I don't think this is the greatest workaround ever, but we went with changing the color scale from white to green, so null values would be shown in white. Then we used a custom scale based on our data to make it look as best we could. Here are the settings we used: <img alt="Screen Shot 2022-06-30 at 10 16 43 AM" width="346" src="https://user-images.githubusercontent.com/34111771/176700688-e6b780bc-cc6b-43df-9109-98a4a3fb8fec.png">
> 
> And the result: <img alt="Screen Shot 2022-06-30 at 10 18 21 AM" width="1551" src="https://user-images.githubusercontent.com/34111771/176700883-a8cbd1e1-b179-47c5-98fc-357f1513db9f.png">

Thank you for answering, @gabesolomon10! Our indicator scale is [-100, 100], but we can't set it manually, because daily the results vary near the bigger value. To sum up, we have no way to scape from option "Smallest value in this column". Hoping this bug fix come out soon.
