### ISSUE TITLE
Add select dropdown as dashboard filter

### ISSUE THREAD

**Issue by luqmanrom** [metabase/metabase#11876]
**Is your feature request related to a problem? Please describe.**
Dashboard user cannot related what id value equally means. 

**Describe the solution you'd like**
A feature where user can add dashboard filter with dropdown type. It will show human readable text as the label and associate it with id value;

**Describe alternatives you've considered**

**How important is this feature to you?**

**Comment by flamber** [comment]
Hi @luqmanrom 
Can you describe in more details what you're looking for? It sounds like you're looking for the functionality that already exists if you connect the Data Model correctly with Entity Key/Name and making it a search/list box, and perhaps you want to look at Display Value too:
https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html
![image](https://user-images.githubusercontent.com/1447303/74140266-120af480-4bf5-11ea-98ca-4da923c3d3b1.png)
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
