### ISSUE TITLE
Unable to use responsive iframe libraries with Metabase iframes because the height and width of html is being set to 100%

### ISSUE THREAD

**Issue by exzizt** [metabase/metabase#11873]
**Describe the bug**
It is practically impossible to use Metabase's iframes in a responsive fashion (i.e., having the width and height dynamically change depending on window size and other factors) because the "html" element's styling is being set in the iframe to 100%. See issue #10132 and "Iframe not downsizing at" http://davidjbradshaw.github.io/iframe-resizer/.

**Expected behavior**
Height and width are not set!

**Screenshots**
![image](https://user-images.githubusercontent.com/17113094/74097125-75920680-4abd-11ea-8c40-c164849e2fbe.png)

**Information about your Metabase Installation:**
Using latest version.

**Severity**
It is severe. Responsiveness is important.

**Comment by lindsay-stevens** [comment]
Can you please add some screenshots of the undesirable behaviour, the desired behaviour (e.g. if you manually override CSS), and for bonus points a suggested fix (or even a PR)?

There's 2k open issues here so going a bit further will greatly increase the chances of it being fixed.

**Comment by exzizt** [comment]
> Can you please add some screenshots of the undesirable behaviour, the desired behaviour (e.g. if you manually override CSS), and for bonus points a suggested fix (or even a PR)?
> 
> There's 2k open issues here so going a bit further will greatly increase the chances of it being fixed.

The issue is that, in the iframe, is CSS that is setting the "html" element's width and height attributes to 100% (see screenshot). Since it is in the iframe, the parent page cannot change it. I need to remove somehow the setting of html's width and height. Can you just not send it in the iframe to begin with?

**Comment by flamber** [comment]
Hi @exzizt 
Which version of Metabase? Please post "Diagnostic Info" from Admin > Troubleshooting.
Whatever happens inside an iframe does not affect the outside, so I'm not sure I understand the issue here.
Can you please provide sample code, so we can reproduce?

**Comment by exzizt** [comment]
> Hi @exzizt
> Which version of Metabase? Please post "Diagnostic Info" from Admin > Troubleshooting.
> Whatever happens inside an iframe does not affect the outside, so I'm not sure I understand the issue here.
> Can you please provide sample code, so we can reproduce?

Thank you for your time. Although I regretfully don't have much time at the moment to put together a good example and I can't use my project's private Metabase URLs. Maybe in the future I can. However, I think this is an issue that can be resolved without that.
We are currently using version  0.33.4, although I don't think this is an issue that has been patched in more recent versions.
The issue is that Metabase's iframe content is including styling that is setting "html"'s "width" and "height" to 100%. If you see the "IFrame not downsizing" on [my provided link](http://davidjbradshaw.github.io/iframe-resizer/), you will see the issue explained here, noting that it's due to the 100% sizes being set.

**Comment by flamber** [comment]
Closing in favor of #10132
