### ISSUE TITLE
Ablity to set jdbc fetch size for database

### ISSUE THREAD

**Issue by nitzien** [metabase/metabase#11878]
**Is your feature request related to a problem? Please describe.**

Most database has smaller default fetch size but not Redshift.

From Redshift documentation- “By default, the JDBC driver collects all the results for a query at one time. As a result, when you attempt to retrieve a large result set over a JDBC connection, you might encounter a client-side out-of-memory error. To enable your client to retrieve result sets in batches instead of in a single all-or-nothing fetch, set the JDBC fetch size parameter in your client application.”

https://docs.aws.amazon.com/redshift/latest/dg/queries-troubleshooting.html#set-the-JDBC-fetch-size-parameter

**Describe the solution you'd like**
We should be able to set a fetch size parameter for a database in metabase. Blank should mean default server settting.

**Describe alternatives you've considered**
Increasing heap size for metabase jvm

**How important is this feature to you?**
This has caused out of memory in metabase jvm. Increasing heap size is possibility and it works up to an extent. 

**Additional context**
Discussion about this in metabase fourm: 
https://discourse.metabase.com/t/is-there-a-way-we-can-set-fetch-size-for-jdbc-for-redshift-database-in-metabase/8880

**Comment by jeff303** [comment]
Fixed in 0.39.  The option to set fetch size for Redshift is added, configurable through an environment variable, with a default value of 5000.
