### ISSUE TITLE
Object Details (single record view) places the results outside of view

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11887]
**Describe the bug**
Viewing ObjectDetails with JSON data with long lines can displace the data outside of the view.

**To Reproduce**
Have a table with various columns, and minimum one JSON. Fill one data row with data and make sure the JSON column is filled with long lines.
See screencast - easier to show than explain :laughing: 

**Screenshots**
![Screencast 2020-02-11 22 28 24](https://user-images.githubusercontent.com/1447303/74281199-4d551280-4d1e-11ea-9e8f-99cc49190c12.gif)

**Information about your Metabase Installation:**
Metabase 0.34.2 and `master` with various browsers and setups.

**Additional context**
Was originally reported by @AlmogCohen in #11865.

**Comment by mazameli** [comment]
Bumping priority up — it's affecting our own stats instance and it makes things look flat out broken on this page.

**Comment by flamber** [comment]
Fixed by #12442
