### ISSUE TITLE
Unexpected behaviour when setting manual y-axis range on scatterplots with bubble size variables

### ISSUE THREAD

**Issue by BoschJoan** [metabase/metabase#11889]
If you set a manual y-axis range on a scatterplot on which bubble size does represent a variable, and the bubble size's maximum is higher than the y-value maximum, **the maximum range for the y-axis is set to the maximum of the bubble size variable**.

One would expect the values of the y-axis variable and not the ones of the bubble size variable to be taken into account when calculating if the manual y-axis range needs to be expanded or not. This is actually what it does when on "Auto y-axis range". On the example below one can see how the maximum y-axis range is expanded from the manually set value of 100 (which should be enough as the highest y value is 60) to 800+, due to the bubble size maximum being 804. This is unexpected and desired.

![Screenshot 2020-02-12 at 11 48 11](https://user-images.githubusercontent.com/9371028/74329291-cfc9ea80-4d8f-11ea-8942-d0e2f0651c13.png)

This is not a severe issue for me, as the default setting does what it's supposed to.

{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.152-127.182.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
Reproduce on `master`. I think it's related to #10434.

Steps:
1. Simple question > Sample Dataset > Orders
2. Filter by CreatedAt between 2020-02-01 and 2020-02-29
3. Summarize by Count-of-rows and grouped by CreatedAt:Day and Quantity:Unbinned
4. Filter by Metric "# Count" <= 8
5. Visualization as Scatterplot, x=CreatedAt, y=Count, size=Quantity
6. Visualization Settings > Axes > disable "Auto y-axis range" and set min=0, max=5

![image](https://user-images.githubusercontent.com/1447303/75092236-0bc23400-5576-11ea-9ce3-bfda10f13749.png)
