### ISSUE TITLE
Blank screen - Uncaught TypeError: Cannot read property 'withConfig' of undefined

### ISSUE THREAD

**Issue by johnpkennedy** [metabase/metabase#11898]
For the past week, myself and other co-workers have encountered a blank white screen when we try to log into our Metabase instance.

This is the only error that appears in browser console:

```
app-main.bundle.js?1283043d8d6d3679e46b:5 Uncaught TypeError: Cannot read property 'withConfig' of undefined
    at Object.<anonymous> (app-main.bundle.js?1283043d8d6d3679e46b:5)
    at i (vendor.bundle.js?1283043d8d6d3679e46b:1)
    at Object.<anonymous> (vendor.bundle.js?1283043d8d6d3679e46b:1)
    at i (vendor.bundle.js?1283043d8d6d3679e46b:1)
    at Object.<anonymous> (app-main.bundle.js?1283043d8d6d3679e46b:5)
    at i (vendor.bundle.js?1283043d8d6d3679e46b:1)
    at window.webpackJsonp (vendor.bundle.js?1283043d8d6d3679e46b:1)
    at app-main.bundle.js?1283043d8d6d3679e46b:5
```

Multiple people have encountered this. We've tested with Google Chrome, Firefox, Microsoft Edge, and Safari in both normal and private/incognito modes.

**To Reproduce**
1. Open a web browser
2. Goto the Metabase URL

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**Screenshots**
![Metabase](https://user-images.githubusercontent.com/3617844/74384425-34e90480-4dbf-11ea-8e61-59c7f36d04d4.png)

**Information about your Metabase Installation:**
I believe we were using 0.34.2 but I can't access the admin page to get the troubleshooting information

**Severity**
Blocking usage of Metabase entirely

**Additional context**
It doesn't appear to be related to extensions because the problem still occurs when the browser has no extension.

Clearing the cache and erasing cookies has no impact.

**Comment by johnpkennedy** [comment]
We downgraded to **0.34.1** and it is working again.

**Comment by flamber** [comment]
Hi @johnpkennedy 
Are you using a proxy/CDN/WAF like CloudFlare or similar optimization service? If yes, then disable such optimizations.
Do you keep the Metabase logs or are those lost on the downgrade? Do you see any errors there?
Have you tried to upgrade again to 0.34.2? Just to see the it might have had something to do with the installation.

**Comment by johnpkennedy** [comment]
@flamber - No proxy/CDN/WAF. Sorry, we didn't preserve the logs before the downgrade. We haven't tried upgrading to 0.34.2 again yet

**Comment by flamber** [comment]
Closing this, since it has not been reported by any other and there's not enough information to figure out what happened.
It sounds like a corrupted download or a proxy doing something that blocked Metabase, example:
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html
