### ISSUE TITLE
Permission to submit to FreeBSD as port and package

### ISSUE THREAD

**Issue by tuaris** [metabase/metabase#11905]
I've created a port for FreeBSD (https://github.com/tuaris/freebsd-metabase) and would like to have your permission to submit it so that it's available to all FreeBSD users by means of the port and package system.

Once accepted, FreeBSD users will be able to install and run Metabase on FreeBSD using a pre-built package:

```
pkg install metabase
```

Or from the ports systems:

```
cd /usr/ports/databases/metabase
make install
```

To run

```
service metabase start
```

Options for Metabase can be configured using `/usr/local/etc/metabase.conf`

**Comment by flamber** [comment]
Hi @tuaris 
Thank you for doing this :tada: The Metabase will feel home in the ports tree :-)
As long as it's within the license of Metabase, making it available in other package systems should be all fine and you normally don't need permission to do that for open source projects.
