### ISSUE TITLE
Clone link 404's

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1190]
eg https://staging.metabase.com/card/63?clone

**Comment by tlrobinson** [comment]
Who wants to play spot the bug?

![screenshot 2015-11-25 14 26 44](https://cloud.githubusercontent.com/assets/18193/11411224/efbbeeae-9382-11e5-8063-9385f09890b8.png)


.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.

.
.
.
.
![screenshot 2015-11-25 14 26 44](https://cloud.githubusercontent.com/assets/18193/11411236/14713e34-9383-11e5-9594-5bbe7ba0a5b6.png)

Base64 encoding can include "+" and "/", which was occasionally causing these URLs to not be matched by the card's route. Oops.

**Comment by agilliland** [comment]
hazahhh!  :imp:
