### ISSUE TITLE
Adding questionId to query remark for embedded reports and dashboard

### ISSUE THREAD

**Issue by nitzien** [metabase/metabase#11902]
**Is your feature request related to a problem? Please describe.**
Currently, we add user id and query hash to query remark when a user executes  a query. But for a query that is executed from embedded dashboard or report, there is no information. Debugging gets difficult if we have multiple reports with similar looking query.

**Describe the solution you'd like**
It will be good idea to at least add question Id [[ and dashboard id if available ]] to query remark

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Good to have. Time saver while debugging.

**Additional context**
Related to #2386

**Comment by flamber** [comment]
Hi @nitzien 
It looks like a duplicate of #9514, but perhaps you're asking for more than that issue. If you agree it's a duplicate, then please close this issue and upvote the other by clicking :+1: on the first post.

**Comment by nitzien** [comment]
Thanks @flamber 

Yes almost a duplicate. But we should also ensure that this is also available for embedded query. Today there is almost no information available for query from embedded reports and dashboards.
