### ISSUE TITLE
Waterfall chart

### ISSUE THREAD

**Issue by botchniaque** [metabase/metabase#11904]
We would like to be able to visualize our financials as a waterfall chart 

**Describe the solution you'd like**
As a user I would like to select stages with respective values and/or deltas and get a waterfall chart - similarly to existing funnel charts.  

**How important is this feature to you?**
We're a company of ~100, heavily using Metabase. Still we're reaching out to other tools to be able to create waterfall charts. 

**Additional context**
![image](https://user-images.githubusercontent.com/881640/74422071-46c5b880-4e4e-11ea-96f3-e1b79bddf55f.png)

examples:
- wikipedia: https://en.wikipedia.org/wiki/Waterfall_chart
- plotly: https://plot.ly/python/waterfall-charts/
- tableau: https://evolytics.com/blog/tableau-201-make-waterfall-chart/

**Comment by mazameli** [comment]
Implemented in 0.38!
