### ISSUE TITLE
Only show users in same usergroup when creating Pulse

### ISSUE THREAD

**Issue by Mrmiffo** [metabase/metabase#11913]
**Is your feature request related to a problem? Please describe.**
We're providing Metabase to a number of different customers, using the same Metabase instance. When a user from Customer A creates a pulse and selects who to send the pulse too, all users currently in Metabase are visible, even users belonging to other customers. This is not desirable as Company A may select a user from Company B (for example with a similar name) and send pulses to that user with sensitive information.

**Describe the solution you'd like**
Have an option in Metabase Admin panel which would make the user selection in Pulses only show users belonging to the same user group (excluding the All users user group) as the current user. If the user belongs to several groups, all users in all groups should be visible (admins should see all users in the system).

**Describe alternatives you've considered**
@flamber described in this post: https://discourse.metabase.com/t/all-users-display-in-a-pulse-list/6131 how one could use a proxy and modify the /api/user call from the browsers, however as we use the Metabase API for adding and removing users via an external tool, this could probably cause issues in other scenarios.

**How important is this feature to you?**
This is fairly important for our business case, but not a deal-breaker. From a user experience point of view, in our use case, it's kind of weird to see all these users that you've never heard of and the customer could feel that their data might be available to users who should not have access to it.

**Additional context**
Briefly discussed here: https://discourse.metabase.com/t/all-users-display-in-a-pulse-list/6131

**Comment by flamber** [comment]
Hi @Mrmiffo 
Someone created this request in the meantime - #10795 - upvote by clicking :+1: on the first post.
