### ISSUE TITLE
Custom China map doesn't show the chinese name when put the mouse on the map juse the error code

### ISSUE THREAD

**Issue by yelikechen** [metabase/metabase#11924]
Hi guys,

Custom China map doesn't show the Chinese name when put the mouse on the map only shows the error code. 

By the way, I just wanna to confirm that Metabase doesn't support the Chinese ?

The error code just like the below screenshot: 
![image](https://user-images.githubusercontent.com/16464947/74582493-7bc13f00-4ff7-11ea-9e2f-a6bbe470e974.png)

Thanks for you advanced help. And looking forward to your reply.

**Comment by flamber** [comment]
Hi @yelikechen 

Since you don't give any version or GeoJSON information, I tested 0.34.2 with map from https://github.com/longwosion/geojson-map-china on Firefox and Chromium, and it looks correct:
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/74591877-0c117b00-501c-11ea-980c-3f9dc6f14168.png)

**Comment by yelikechen** [comment]
Hi Flamber,
I'm sure the GeoJSON is UTF-8 format. I use the version is 0.34.2. I used you supported me the GeoJSON，however,  it doesn't work, cause the name still shows error code.  

Below is Chromium's information (name is error code and the name is Chinese):
![image](https://user-images.githubusercontent.com/16464947/74600531-feb4c900-50cd-11ea-8877-478cec8606be.png)

Below is GeoJson with UTF-8 format:
![image](https://user-images.githubusercontent.com/16464947/74600543-2c9a0d80-50ce-11ea-802d-9857ec4e8c08.png)

**Comment by huangyuan027** [comment]
me too

**Comment by flamber** [comment]
@huangyuan027 Make sure you're using a Java that supports your charset or use the Docker version:
https://discourse.metabase.com/t/custom-china-map-the-chinese-name-is-error-code/9022
