### ISSUE TITLE
Druid v0.17.0 Error for a simple query

### ISSUE THREAD

**Issue by bad-blood** [metabase/metabase#11925]
java.lang.Exception: Cannot construct instance of `org.apache.druid.query.select.SelectQuery`, problem: The 'select' query has been removed, use 'scan' instead. See https://druid.apache.org/docs/latest/querying/select-query.html for more details. at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 1, column: 32] Error class:

![image](https://user-images.githubusercontent.com/58202629/74592223-266a4980-505a-11ea-8d1d-7a808b56d989.png)

![image](https://user-images.githubusercontent.com/58202629/74592214-0d619880-505a-11ea-9173-54985f774cd3.png)

what should I do？

**Comment by flamber** [comment]
Setting as P1, since it seems like the included Metabase driver will not work for Druid 0.17+ on QB.
I have not been able to get a Druid environment up to confirm with, so please correct me if it's wrong.

**Comment by bad-blood** [comment]
@flamber I want know which druid version is the last supported release

**Comment by flamber** [comment]
@bad-blood I know people have been using 0.16 and earlier, so try anything before 0.17.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by tomas-kucera** [comment]
I can confirm that the built in driver for Druid does not work with Druid 0.17, which is the latest stable release.

Would be great to have that fixed.

**Comment by tomas-kucera** [comment]
Is there a way to get the build? I tried to build it myself but it failed.

I am not as proficient in the builds but would gladly help to test the druid implementation.

I understand that it would be a dev build. ;)

**Comment by flamber** [comment]
You can try https://hub.docker.com/r/metabase/metabase-head - please make sure that you have backups of Metabase application database, if you connect it to existing - and don't expect to be able to downgrade. So I would recommend that you just use it for testing.

**Comment by tomas-kucera** [comment]
So, I had downloaded this build: https://downloads.metabase.com/v0.34.3/metabase.jar and ran it.

I am quite sure it is the right .jar running:
02-27 22:20:12 INFO metabase.core :: Starting Metabase version v0.34.3 (1a83edb release-0.34.x) ...

Unfortunately when trying to browse the data, I still get this:
java.lang.Exception: Unknown exception Cannot construct instance of `org.apache.druid.query.select.SelectQuery`, problem: The 'select' query has been removed, use 'scan' instead. See https://druid.apache.org/docs/latest/querying/select-query.html for more details. at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 1, column: 32] Error class:com.fasterxml.jackson.databind.exc.ValueInstantiationException

I can provide the full stack trace with the query defintion, if it can help. Let me know.

**Comment by flamber** [comment]
@tomas-kucera It is not implemented in 0.34.3 - it will be part of the upcoming 0.35.0

**Comment by tomas-kucera** [comment]
OK. I thought that you are pointing me to the place to find the jar to be able to test it. And the link led me to this 0.34.3 file.

That is why I tested with it.

Sorry for the silly question: is there a way to test the implementation? Thanks!

**Comment by flamber** [comment]
@tomas-kucera 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Yes, use with Docker, like I already linked to: `docker pull metabase/metabase-head`

**Comment by tomas-kucera** [comment]
@flamber 
Thanks for redirecting me. Trying to get help there. I would like to avoid having to go through the hassle of Heroku / Docker. Not my cup of coffee.

Would be nice to have something like nightly builds, when one could just grab it and use. 👍 

Anyways, I guess, you can close this ticket.
