### ISSUE TITLE
Dashboard with filter and Text Box breaks interface when editing

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11927]
**Describe the bug**
When editing a dashboard with filter and a Text Box as the first card, it's impossible to connect the filter, and cannot save the dashboard. When Text Box is not the first card, then it's possible to connect the filter to questions, but still cannot save the dashboard.

**To Reproduce**
A. Go to a dashboard with a question
  - Add a Text Box as the first card
  - Add a filter and try to connect to question (not possible)
Console `Error: Unknown query type: undefined`
  - Save dashboard - results in "Save Failed" - refreshing browser will show ghost card
Console `Error: Minified React error #136`

B. Go to a dashboard with a question
  - Add a Text Box **not** as the first card (i.e. last card)
  - Add a filter and connect to question
  - Save dashboard - results in "Save Failed" - refreshing browser will show ghost card
Console `Error: Minified React error #136`

**Screenshots**
![Screencast 2020-02-16 01 51 38](https://user-images.githubusercontent.com/1447303/74597385-0426fa80-505f-11ea-90f0-c8e7f3395538.gif)

**Information about your Metabase Installation:**
Metabase 0.34.1+2 and `master`. Could **not** reproduce on 0.34.0, 0.33.7.3, 0.33.5.1 or 0.32.10

**Severity**
Giving it P1, since it's a lot easier to trigger than it's sister (#11163). And because it's been reported a couple of times in the forum the past weeks without much details until topic 9017.

**Additional context**
https://discourse.metabase.com/t/dashboard-filters-javascript-problem/9017
Might be related to #10796 - very similar behavior, but that was 0.33.5.1

**Comment by paulrosenzweig** [comment]
Fixed in #11929
