### ISSUE TITLE
For discussion: consider making the tooltip behavior for time series be scrubber-like

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11935]
Filing this as a request on behalf of a user. Particularly when dealing with time series that have a lot of values, it can be hard and annoying to try and hover over a single point to see its x- and y-axis values. Charts like this Dow Jones one tend to have behavior like this, where the tooltip appears when hovering over any part of the chart and stays in a fixed vertical position, while a vertical rule appears to help indicate which x-axis point is being hovered over and displayed.

**Benefits:**
- decreases mouse travel and required mouse pointer precision when trying to see values for points on a chart

**Potential downsides:**
- overusing hover effects can be annoying
- might feel odd when trying to open the actions/drill-through menu by clicking on a point
- could feel weird when dealing with a time series with a smaller set of values

![scrubber](https://user-images.githubusercontent.com/2223916/74768605-b74d4a80-523d-11ea-9371-0b85a61fea0c.gif)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by brunobergher** [comment]
We effectively went for this in the recent tooltip work. Closing.

**Comment by jasonlpapadopoulos** [comment]
Hello! How come this issue is closed? I am doing a demo on Metabase right now and hovering on the x axis of a line chart does not show the tooltip with the values. Thanks!
