### ISSUE TITLE
Drag-to-zoom drill-through on timeseries with pre-aggregated data is missing the metric column(s)

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11933]
This is on our stats instance (0.34.2). If I visualize some unaggregated or pre-aggregated data as a time series and then drag on it to zoom in or select some of the points only gives me the time column back as a result. I would expect to see the column for the metric I've assigned to the y-axis in my result.

![preaggregated-drill-through](https://user-images.githubusercontent.com/2223916/74766063-81a66280-5239-11ea-94bc-c26ee54bf2f0.gif)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by cdeweyx** [comment]
Can't repro - Getting a line chart after zoom-in like I would expect, when I flip to tabular view it has expected columns.
