### ISSUE TITLE
User with no data access are not allowed to see questions

### ISSUE THREAD

**Issue by antoineverger1** [metabase/metabase#11932]
**Describe the bug**
A user that belongs to a group that has not data access but a view permission can not see the questions page anymore (regression in 0.34.2, working in 0.34.1)

**Logs**

> app-main.bundle.js?1283043d8d6d3679e46b:5 Request entities,tables,2,fetchMetadata failed
> status: 403, data: "You don't have permissions to do that."

**To Reproduce**
1. Using the sample dataset, create a new question using, for example, the order Table.
2. Store the question in "Our Analytics" collection
3. Create a new group and a new user
4. Remove data access from All Users and from the newly created group
5. Give a "View collection" permission to the newly created group
6. Try to access the created question from the test user (assigned to the mentioned group)
7. Spinner keeps spinning

**Expected behavior**
In 0.34.1 and before, user was able to access the question and all others related to the collection he has the permission to view.

**Screenshots**
![image](https://user-images.githubusercontent.com/43539846/74738011-52521e80-5256-11ea-888e-4a480f177a3f.png)
![image](https://user-images.githubusercontent.com/43539846/74738027-5a11c300-5256-11ea-894d-afe1794cb2fe.png)
![image](https://user-images.githubusercontent.com/43539846/74738349-ffc53200-5256-11ea-9228-e32c004279bc.png)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome - Version 80.0.3987.106 (Official Build) (64-bit)
- Your operating system: Ubuntu 18.04 
- Your databases: None (sample dataset)
- Metabase version: 0.34.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
It's very severe. We are broadly using Metabase internally through different departments to whom we don't want to give the full data permission also within a given table and therefore we are massively using the combination no data access and collection permissions to do that.
 
**Additional context**
As mentioned, it seems to be a regression since it is working on 0.34.1.

Let me know if I can help more. Too bad that I don't know (yet) Clojure :(

**Comment by tuaris** [comment]
Dashboards are still accessible even though the questions are not.

**Comment by camsaul** [comment]
This might be fixed on `master`, I fixed a related bug earlier today

**Comment by flamber** [comment]
@camsaul Just tested `master`, but can still reproduce:
- Native question works
- QB question fails with error in log (`You don't have permissions to do that.`) and a couple in console too:
`Request entities,tables,11,fetchMetadata failed: Object { status: 403, data: "You don't have permissions to do that.", isCancelled: false }` and `uncaught exception: Object`
- Saved Question fails with only errors in the console and breaks UI (refresh to make it work):
`TypeError: prevComponentInstance is null` and `TypeError: this.db is null`

**Comment by antoineverger1** [comment]
Hey @paulrosenzweig , @camsaul,

any perspective on when the issue will be addressed? Is it gonna be part of the 0.34.4 ?

Cheers !

**Comment by flamber** [comment]
@antoineverger1 
There's a patch for this - #12048 - it will be part of 0.35.0, which should be released this month.

**Comment by antoineverger1** [comment]
Amazing. Thank you very much for the quick response.
