### ISSUE TITLE
Custom columns from joined tables can't be selected

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11946]
**Describe the bug**
When joining a saved question and selecting a custom column from that question to be displayed, an SQL error is generated.

**To Reproduce**
1. Create a question and add a custom column (eg. equal to an existing column).
2. Create another question and join the previous one to this one.
3. Select the custom column for display.
4. Observe the error message is given.

**Expected behavior**
Custom columns should be treated as regular columns when joining saved questions.

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
A nuisance as I have to resort to SQL questions.

**Additional context**
I was trying to use a custom column to have that column name appear in a Pulse Excel attachment instead of the autogenerated "Question 8.Sum".

**Comment by andreychirikba** [comment]
Below is the SQL generated for the saved question being joined:

> SELECT `source`.`Gebruiker` AS `Gebruiker`, `source`.`count` AS `count`, `source`.`count` AS `Logboekverslagen`
FROM (SELECT `Verslagen`.`Gebruiker` AS `Gebruiker`, count(*) AS `count` FROM `Verslagen`
WHERE str_to_date(concat(yearweek(`Verslagen`.`Datum`), ' Sunday'), '%X%V %W') = str_to_date(concat(yearweek(date_add(now(), INTERVAL -1 week)), ' Sunday'), '%X%V %W')
GROUP BY `Verslagen`.`Gebruiker`
ORDER BY `Verslagen`.`Gebruiker` ASC) `source`

Notice the custom column

> `source`.`count` AS `Logboekverslagen`

correctly added. Below is the relevant part from the query that joins the saved question:

> LEFT JOIN (SELECT `source`.* FROM (SELECT `Verslagen`.`Gebruiker` AS `Gebruiker`, count(*) AS `count` FROM `Verslagen` WHERE str_to_date(concat(yearweek(`Verslagen`.`Datum`), ' Sunday'), '%X%V %W') = str_to_date(concat(yearweek(date_add(now(), INTERVAL -1 week)), ' Sunday'), '%X%V %W') GROUP BY `Verslagen`.`Gebruiker`) `source`) `Question 8` ON `Gebruikers`.`Naam` = `Question 8`.`Gebruiker`

Notice the custom column bit is missing.

**Comment by flamber** [comment]
Reproduced on `master` with Sample Dataset.
1. Custom question > Sample Dataset > Orders
2. Add "Custom Column" with `Discount * 2` as "Discount Bonanza", visualize and save question "Q1"
3. Custom question > Sample Dataset > People
4. Join with Q1 on `People.ID`=`Q1.User ID`, visualize and shows the error:

```
Column "Question 218.Discount Bonanza" not found; SQL statement: -- Metabase:: userID: 1 queryType: MBQL queryHash: fefd44cde6dd371fe7482c8a800e1b7b62a245b59deca810d49771083a95ef26 SELECT "PUBLIC"."PEOPLE"."ID" AS "ID", "PUBLIC"."PEOPLE"."NAME" AS "NAME", "PUBLIC"."PEOPLE"."ADDRESS" AS "ADDRESS", "PUBLIC"."PEOPLE"."BIRTH_DATE" AS "BIRTH_DATE", "PUBLIC"."PEOPLE"."CITY" AS "CITY", "PUBLIC"."PEOPLE"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."PEOPLE"."EMAIL" AS "EMAIL", "PUBLIC"."PEOPLE"."LATITUDE" AS "LATITUDE", "PUBLIC"."PEOPLE"."LONGITUDE" AS "LONGITUDE", "PUBLIC"."PEOPLE"."SOURCE" AS "SOURCE", "PUBLIC"."PEOPLE"."STATE" AS "STATE", "PUBLIC"."PEOPLE"."ZIP" AS "ZIP", "Question 218"."ID" AS "ID_2", "Question 218"."CREATED_AT" AS "CREATED_AT_2", "Question 218"."DISCOUNT" AS "DISCOUNT", "Question 218"."PRODUCT_ID" AS "PRODUCT_ID", "Question 218"."QUANTITY" AS "QUANTITY", "Question 218"."SUBTOTAL" AS "SUBTOTAL", "Question 218"."TAX" AS "TAX", "Question 218"."TOTAL" AS "TOTAL", "Question 218"."USER_ID" AS "USER_ID", "Question 218"."Discount Bonanza" AS "Discount Bonanza" FROM "PUBLIC"."PEOPLE" LEFT JOIN (SELECT "PUBLIC"."ORDERS".* FROM "PUBLIC"."ORDERS") "Question 218" ON "PUBLIC"."PEOPLE"."ID" = "Question 218"."USER_ID" LIMIT 2000 [42122-197]
```

I have a feeling it's the same core problem as #10474.

**Comment by sbelak** [comment]
Without any remapping, this works on release-0.35.x.
