### ISSUE TITLE
scatter plot Y-Axis Minimum won't set correctly

### ISSUE THREAD

**Issue by rfriedr1** [metabase/metabase#11968]
**Description**
When setting the y-axis minumim value, decimal placed are irgnored. E.g. setting value of "1.4" would set the y-axis min to "1". it does seem to work for y-axis maximum value. See screenshot.

**To Reproduce**
1. Go to a scatter plot
2. Click on 'setting'
3. Click on 'axis'
4. Toggle off 'Auto y-axis range'
5. set Min to "1.4"
4. See error: Y-axis min is displayed as "1" and not "1.4"

**Expected behavior**
y-axis min should be displayed an set to 1.4

**Screenshots**
![screenshot_metabase](https://user-images.githubusercontent.com/4603154/75170441-67cdb980-572a-11ea-80ad-2c8a93459fca.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_221-b11",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_221",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.221-b11",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "de",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.2",
      "date": "2020-02-04",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
not severe

**Comment by flamber** [comment]
Reproduce on `master`. Seems related to #10434
I don't think it has anything to do with the decimal, but the highest minimum value seems to be `1`.

**Reproduce:**
1. Simple question > Sample Dataset > Products
2. Summarize by Average:Rating, grouped by CreatedAt:Month
3. Visualization > Scatter > Data: x=CreatedAt, y=Rating > Axes > disable "Auto y-axis range" and set min=2, max=5
4. Minimum range is displayed as 1, even though the minimum value of the dataset is 2.08

![image](https://user-images.githubusercontent.com/1447303/75178200-f1d04f00-5737-11ea-8711-14a1f76898de.png)
