### ISSUE TITLE
API - POST card query - parameters ignored when specifying export format 

### ISSUE THREAD

**Issue by jBarrulas** [metabase/metabase#11967]
**Bug description**
I created a dashboard with cards that have queries with variables. Each card has been tested in the Metabase platform and each works as intended.
I've been doing API requests using Postman software and a Java project environment with HttpURLConnection package. I have an active X-Metabase-Session value specified in the request's header.

When executing the request - POST /api/card/:card-id/query/ - with the following JSON body
```
{
	"parameters":[{
		"type":"category",
		"target":[
			"variable",[
				"template-tag",
				"<VARIABLE-NAME>"
			]
		],
		"value":"<VARIABLE-VALUE>"
	}]
}
```
I obtain the intended card query results (filtered by the specified variable) in JSON format (the default format)

When executing the request specifying the export format (json, csv or xlsx) - POST /api/card/:card-id/query/:export-format - with the same request body, the results aren't filtered and the "parameters" seem to be ignored. Am I doing something wrong or is it an actual bug?

**Severity**
Low

**Comment by flamber** [comment]
Hi @jBarrulas 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It looks like the exact same question as this topic: https://discourse.metabase.com/t/api-post-api-card-card-id-query-export-format-with-parameters/8113

**Comment by jBarrulas** [comment]
Hi @flamber 
The issue I described seems to be different from the one you shared, but thank you for indicating the right forum.
I've been using the right request parameter format for queries with variables. The issue I described shows that when you specify the export format in the request URL those parameters are ignored.
Best regards

**Comment by flamber** [comment]
@jBarrulas 

But you say that is works correctly, when you use Metabase, but not when you're writing your own API call, so something must be different, since the Metabase interface gets all it's information from that API too. Hence, it's not a problem with Metabase.
If you've found a bug in Metabase, then please open issues for that - and if you're unsure, then you're more than welcome to ask in the forum.

I would highly recommend that you use your browser developer console, when using Metabase, to see which request are actually being made in the Network-tab. It's the best way to learn how to write API calls, since you just use the Metabase interface and check the requests.

**Comment by brandonkboswell** [comment]
I am also running into this problem. The query functions as you would expect when you don't set a format (which appears to be the format that the Metabase interface uses), but when you add the format of JSON it ignores the parameters.

**Comment by flamber** [comment]
@brandonkboswell 
Have a look here: https://discourse.metabase.com/t/api-post-api-card-card-id-query-export-format-with-parameters/8113

As noted in the endpoint: https://www.metabase.com/docs/latest/api-documentation.html#post-apicardcard-idqueryexport-format
> Note that this expects the parameters as serialized JSON in the ‘parameters’ parameter

**Comment by brandonkboswell** [comment]
Flamber, perhaps I'm doing something wrong, but I am doing that and it doesn't seem to honor it.

**Comment by flamber** [comment]
@brandonkboswell Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
