### ISSUE TITLE
Native question will reset visualization to Table unless there's data from the beginning

### ISSUE THREAD

**Issue by alexandreb11** [metabase/metabase#11960]
When making any change to a question, even one that doesn’t require Saving - like changing the Question description - the Display Option changes to Table.
It seems that Metabase always tries to infer the questions data result, but after any change it is like there is no sample data, so it loses any Display Option applied before.

**Note:** when we manually switch back to the desired Display Option, the previously used formatting (like column names, number formatting, column order, axis) are restored - they are not lost (gladly).

Metabase version - v0.34.1 - 2020-01-13

**Comment by flamber** [comment]
Hi @alexandreb11 
I cannot reproduce on 0.34.2. Can you give steps-to-reproduce with the Sample Dataset database?

**Comment by alexandreb11** [comment]
> Hi @alexandreb11
> I cannot reproduce on 0.34.2. Can you give steps-to-reproduce with the Sample Dataset database?

I reproduced using the Sample Dataset and figured that the error only applied for questions with Obligatory Filter Value.
And the question returns to Table Display option everytime I open it.

Here are the steps:
1- Create and save the question with a obligatory filter (date)
![Captura de Tela (72)](https://user-images.githubusercontent.com/54741502/75116321-e8ff5080-5645-11ea-9de1-a251aa9758b9.png)
2- open the question again (from my personal collection in the case)
![Captura de Tela (73)](https://user-images.githubusercontent.com/54741502/75116333-fc122080-5645-11ea-9aed-77b1315033df.png)
3- add value to the filter
![Captura de Tela (74)](https://user-images.githubusercontent.com/54741502/75116348-2b289200-5646-11ea-979d-fa8218a5929f.png)
4- run the question again
![Captura de Tela (75)](https://user-images.githubusercontent.com/54741502/75116352-354a9080-5646-11ea-902a-7bdd4b0109bb.png)

**Comment by flamber** [comment]
@alexandreb11 Okay, thanks, that helped to understand the issue.
I'm pretty sure it's covered by #11218 (as noted in the comments), but I'll leave this open.

**Comment by Tbodewes** [comment]
We have a very similar issue on V0.34.3. When opening a question from a dashboard, the visualization automatically reverts back to table. This actually also happens even when the query returns data right away (i.e. all filters are set up correctly etc.). When selecting the correct visualization, the formatting does come back exactly as it was before opening the question (same colours, etc.).

See screenshots below:
![Report as viewed from dashboard](https://user-images.githubusercontent.com/40305973/77531558-6b706f80-6e93-11ea-8bdc-e492e05afd8a.png)

![Report when clicking on link](https://user-images.githubusercontent.com/40305973/77531682-9a86e100-6e93-11ea-8666-29c4ff97e37e.png)
