### ISSUE TITLE
Remember window size on close of Mac app

### ISSUE THREAD

**Issue by jeffbowen** [metabase/metabase#11970]
When closing and reopening the Mac app, the previous window size is not remembered. The app always starts up with the same initial window size. It would be very nice if it remembered what size it was last like most Mac apps.

The following might be helpful/relevant info. Possibly a one-line fix?

https://github.com/metabase/metabase/pull/6392
https://stackoverflow.com/questions/10115280/save-nswindow-size-on-resize-close-for-user

**Comment by flamber** [comment]
Closing, since we are deprecating the Mac App: https://www.metabase.com/blog/Metabase-0.41/#other-news-at-metabase
