### ISSUE TITLE
Variables doesn't work in joining table 

### ISSUE THREAD

**Issue by JasonWu2008** [metabase/metabase#11976]
**Describe the bug**
I'm trying to use the Variable feature but I got an error as below when I join two tables with default Sample Dataset. And then as filter conditions add to the dashboard. 
I'm not sure where I'm wrong or have other alternative approaches to achieve that?

Error Message: _Column "PUBLIC.PRODUCTS.CATEGORY" not found_

My query SQL:
_select b.category,b.title,b.price,a.tax,a.total,a.user_id from orders a,products b where a.product_id=b.id 
[[and {{userId}}]] [[and {{productCategory}}]]_

**Expected behavior**

**Information about your Metabase Installation:**
- Your databases: (e.x. MySQL 5.7)
- Metabase version: (e.x. v0.34.2)
- Metabase internal database: (e.x. MySQL 5.7)

**Comment by flamber** [comment]
Hi @JasonWu2008 
You cannot use table aliases for the Field Filter references:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
