### ISSUE TITLE
Error: "Content Security Policy" with custom domain 

### ISSUE THREAD

**Issue by dersteppenwolf** [metabase/metabase#11979]
**Describe the bug**
The error "Content Security Policy " is thrown when I try to use the app using a custom doman (ie. reports.example.com)
It only works using the IP address.

**version**
v0.34.2
http://downloads.metabase.com/v0.34.2/metabase.jar

**Logs**

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com  'sha256-lMAh4yjVuDkQ9NqkK4H+YHUga+anpFs5JAuj/uZh0Rs=' 'sha256-7t0fjA/BVlVoDzQGo5fjx1QcGZGP/YHzqHjtle6rQr0=' 'sha256-JJa56hyDfUbgNfq+0nq6Qs866JKgZ/+qCq2pkDJED8k='". Either the 'unsafe-inline' keyword, a hash ('sha256-1F0lw4Fmv8y6OvrkD3Kg93KSyCqdKFo5X4bnHBFS6zo='), or a nonce ('nonce-...') is required to enable inline execution.`

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "es-CO",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_212",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.212-b03",
    "os.name": "Linux",
    "os.version": "4.4.0-131-generic",
    "user.language": "en",
    "user.timezone": "America/Bogota"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.2 (Debian 11.2-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.2",
      "date": "2020-02-04",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": "America/Bogota"
    }
  }
}
`

**Severity**
The app doesn't work

**Comment by flamber** [comment]
Hi @dersteppenwolf 
Are you using a proxy or load balancer or Cloudflare, that might be changing something?
Or maybe antivirus or a browser extension?

Please post the environment variables you've used to start the JAR file with (redact where needed).

Did you setup Metabase first via the IP, and then later changed to a domain? If yes, then you need to set the Site URL via Admin > Settings > General.

If you cannot access the interface, then you can set it via the environment variable `MB_SITE_URL="https://reports.example.com:3333/"` or manually change the row `site_url` in the table `setting` in your application database.

For reference: https://discourse.metabase.com/t/error-unsafe-eval-csp/6823

**Comment by dersteppenwolf** [comment]
> Hi @dersteppenwolf

Hi

> Are you using a proxy or load balancer or Cloudflare, that might be changing something?

Reverse proxy using apache web server

> Or maybe antivirus or a browser extension?

tested using Google Chrome's Incognito Mode 


> Did you setup Metabase first via the IP, and then later changed to a domain? If yes, then you need to set the Site URL via Admin > Settings > General.

yes, yes and yes

> If you cannot access the interface, then you can set it via the environment variable `MB_SITE_URL="https://reports.example.com:3333/"` or manually change the row `site_url` in the table `setting` in your application database.
> For reference: https://discourse.metabase.com/t/error-unsafe-eval-csp/6823

> Please post the environment variables you've used to start the JAR file with (redact where needed).


Parameters:
```bash
export MB_DB_TYPE=postgres
export MB_DB_DBNAME=metabase_db
export MB_DB_PORT=5432
export MB_DB_USER=metabase_user
export MB_DB_PASS=mypwd
export MB_DB_HOST=myserver
nohup java -jar metabase.jar &
```

**Comment by flamber** [comment]
@dersteppenwolf Post you Apache config for the site (redact only where absolutely needed).

**Comment by dersteppenwolf** [comment]
```bash
<VirtualHost *:80>
  ServerAdmin webmaster@example.com
  ServerName reports.example.com

  PassengerEnabled off

  AddOutputFilterByType DEFLATE text/html text/css application/x-javascript application/javascript text/javascript

  KeepAlive On
  Header set Access-Control-Allow-Origin "*"

ProxyPass / 			http://127.0.0.1:3000/
  ProxyPassReverse /		http://127.0.0.1:3000/

  ModPagespeedDisallow "*/*.js"
ExpiresByType image/png A31536000
...
</VirtualHost>
```

**Comment by flamber** [comment]
@dersteppenwolf Try disabling all extra modules that you have added to Apache, like PageSpeed.
Keep it simple, just start with the minimum and set Site URL to `http://reports.example.com/`:
```
<VirtualHost *:80>
  ServerName reports.example.com
  ProxyPass / http://127.0.0.1:3000/
  ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
```
And check your Apache logs. Otherwise try Nginx and another reverse-proxy, if you cannot make it work with Apache.
Closing this issue, since it's not a problem with Metabase.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by dersteppenwolf** [comment]
OMG, It worked 18 months ago... (I do not remember exactly but probaby version 0.32)
One of the updates generated the error.

anyway..
Definitely I'll have to look for a different tool.

**Comment by flamber** [comment]
@dersteppenwolf 
CSP has been added in 0.32.0 and got enhanced security in 0.32.6
So it's likely that it was working before, but since I cannot see your entire Apache config, then I can only guess that you're doing some PageSpeed optimizations, and that will break CSP.
Metabase doesn't work with CDN optimizers like CloudFlare's RocketLoader either.
You're welcome to build your own version of Metabase with the security of CSP removed.

**Comment by danaivehr** [comment]
Hi, @dersteppenwolf 

Had the same issue (duplicate #12020)

In my case it was an issue with pagespeed module. It may help you.
Try to set SCP honor (pagespeed version >= 1.13.35.1) or completely disable it by wildcard or virtualhost

For wildcard - consult https://www.modpagespeed.com/doc/configuration 
* Apache Example:  `ModPagespeedDisallow */metabase/*`
* Apache Example:  `ModPagespeedDisallow metabase.mysite.com/*`

For SCP honor - consult https://www.modpagespeed.com/doc/configuration#honor-csp
* Apache Example: `ModPagespeedHonorCsp on`

**Comment by dersteppenwolf** [comment]
> Hi, @dersteppenwolf
> 
> Had the same issue (duplicate #12020)
> 
> In my case it was an issue with pagespeed module. It may help you.
> Try to set SCP honor (pagespeed version >= 1.13.35.1) or completely disable it by wildcard or virtualhost
> 
> For wildcard - consult https://www.modpagespeed.com/doc/configuration
> 
> * Apache Example:  `ModPagespeedDisallow */metabase/*`
> * Apache Example:  `ModPagespeedDisallow metabase.mysite.com/*`
> 
> For SCP honor - consult https://www.modpagespeed.com/doc/configuration#honor-csp
> 
> * Apache Example: `ModPagespeedHonorCsp on`

Hi, looks like `ModPagespeedHonorCsp on` and `ModPagespeedDisallow metabase.mysite.com/*` work.    It is necesary to upgrade modpagespeed to 1.13.35.x

Thanks!
