### ISSUE TITLE
Pulse fails to load card. NullPointerException

### ISSUE THREAD

**Issue by pan-christensen** [metabase/metabase#11982]
Hello!

I've saved a question which displays just fine. When I try to add this question to a pulse, it fails to load. If I try to send the pulse, that also fails.

Here are the errors from the logs:

[bbfcac07-0ccb-45fe-bd49-b0833fd99a28] 2020-02-25T18:02:47+01:00 ERROR metabase.middleware.log GET /api/pulse/preview_card_info/20 500 243.2 ms (19 DB calls) 
{:message "temporal",
:type java.lang.NullPointerException,
:stacktrace
("java.util.Objects.requireNonNull(Objects.java:228)"
"java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1741)"
"java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)"
"java_time.format$format.invokeStatic(format.clj:50)"
"java_time.format$format.invoke(format.clj:43)"
"--> pulse.render.datetime$reformat_temporal_str.invokeStatic(datetime.clj:14)"
"pulse.render.datetime$reformat_temporal_str.invoke(datetime.clj:13)"
"pulse.render.datetime$format_temporal_str.invokeStatic(datetime.clj:33)"
"pulse.render.datetime$format_temporal_str.invoke(datetime.clj:16)"
"pulse.render.body$fn__31956$format_cell__31961$fn__31962.invoke(body.clj:48)"
"pulse.render.body$fn__31956$format_cell__31961.invoke(body.clj:45)"
"pulse.render.body$fn__32036$query_results__GT_row_seq__32041$fn__32042$iter__32043__32047$fn__32048$iter__32081__32085$fn__32086.invoke(body.clj:110)"
"pulse.render.table$render_table_body$iter__31870__31874$fn__31875$iter__31908__31912$fn__31913.invoke(table.clj:75)"
"api.pulse$fn__63442.invokeStatic(pulse.clj:166)"
"api.pulse$fn__63442.invoke(pulse.clj:159)"
"middleware.auth$enforce_authentication$fn__66187.invoke(auth.clj:14)"
"routes$fn__67541$fn__67542.doInvoke(routes.clj:56)"
"middleware.exceptions$catch_uncaught_exceptions$fn__66286.invoke(exceptions.clj:97)"
"middleware.exceptions$catch_api_exceptions$fn__66283.invoke(exceptions.clj:85)"
"middleware.log$log_api_call$fn__67917$fn__67918.invoke(log.clj:178)"
"middleware.log$log_api_call$fn__67917.invoke(log.clj:172)"
"middleware.security$add_security_headers$fn__66249.invoke(security.clj:121)"
"middleware.json$wrap_json_body$fn__67622.invoke(json.clj:64)"
"middleware.json$wrap_streamed_json_response$fn__67640.invoke(json.clj:100)"
"middleware.misc$maybe_set_site_url$fn__67946.invoke(misc.clj:58)"
"middleware.session$bind_current_user$fn__62772$fn__62773.invoke(session.clj:209)"
"middleware.session$do_with_current_user.invokeStatic(session.clj:184)"
"middleware.session$do_with_current_user.invoke(session.clj:177)"
"middleware.session$bind_current_user$fn__62772.invoke(session.clj:208)"
"middleware.session$wrap_current_user_id$fn__62757.invoke(session.clj:161)"
"middleware.session$wrap_session_id$fn__62701.invoke(session.clj:125)"
"middleware.auth$wrap_api_key$fn__66195.invoke(auth.clj:27)"
"middleware.misc$bind_user_locale$fn__67949.invoke(misc.clj:74)"
"middleware.misc$add_content_type$fn__67932.invoke(misc.clj:29)"
"middleware.misc$disable_streaming_buffering$fn__67957.invoke(misc.clj:89)")}

[bbfcac07-0ccb-45fe-bd49-b0833fd99a28] 2020-02-25T18:14:25+01:00 ERROR metabase.pulse Error sending notification!
[bbfcac07-0ccb-45fe-bd49-b0833fd99a28] 2020-02-25T18:14:25+01:00 DEBUG metabase.middleware.log POST /api/pulse/test 200 258.5 ms (20 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (100 total active threads) Queries in flight: 0

I've tested this on two different metabase versions with two different internal databases, H2 in the lab and MySQL 5.7 in production. The database holding my data is MySQL 8 in both instances, and the schema is the same. I've played around with the question a bit and found that if I use a filter of "next X days" on a datetime column, it fails. If I use "on day X", it works. The question is displayed as a table (no visualization).

Here's the production environment:
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3900.0 Iron Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "4.18.0-147.3.1.el8_1.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Oslo"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.20-19-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.2",
      "date": "2020-02-04",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

Users can manually click on the question to get the required data instead of having it sent automatically, so there is a workaround if they remember to use it.

I have found two other issues connected to datetime, which are probably unrelated. I'll mention them here then I'll write separate reports for them.

1: If I group the same result set by time (hour) and visualize it as 'bar', it loads as 'sparkline' in the pulse. Sparkline is not a very useful visualization for this data.
2: Formatting of datetime columns don't seem to work. The values are always displayed in the format: "February 26, 2020, 10:00 AM", no matter what I select. (There's also some issue with formatting of numbers.)

All 3 bugs are present in both of my setups.

**Comment by flamber** [comment]
Hi @pan-christensen 
It looks like a duplicate of #11665. Can you check if the workaround works for you as well?

**Comment by pan-christensen** [comment]
Hello @flamber.

I looked at #11665 before writing this report, but my data does not contain NULL or ZERO datetime values.

Thanks for the other two links. I didn't investigate those bugs yet as I feel that they're less serious. I may be able to provide additional information to the existing reports. I'll read them now.

**Comment by flamber** [comment]
@pan-christensen 
Can you give any other details about the question, like which the visualization, types of columns and such?
Can you always reproduce the issue or is it only specific tables that causes the question to fail on pulse?

**Comment by pan-christensen** [comment]
Hello @flamber 
Thanks for the quick reply. I think you may have missed the part in the middle of my original post (the most important part).
 
> I've tested this on two different metabase versions with two different internal databases, H2 in the lab and MySQL 5.7 in production. The database holding my data is MySQL 8 in both instances, and the schema is the same. I've played around with the question a bit and found that if I use a filter of "next X days" on a datetime column, it fails. If I use "on day X", it works. The question is displayed as a table (no visualization).

Additionally, there's no grouping. I'm trying to display the raw data as it exists in a single table with a single filter. I believe that a very important clue is that the pulse works when I change how the filter works.

I can always reproduce the issue. I've deleted and recreated the questions. I've also modified them several times in different ways. I haven't tested on other tables yet, but I'm sure I can reproduce the issue in tables with datetime columns. We have created several other questions that work fine in pulses.

**Comment by pan-christensen** [comment]
> Hello @flamber.
> 
> I looked at #11665 before writing this report, but my data does not contain NULL or ZERO datetime values.

Sorry about that statement. It's incorrect. My data does have NULL values in a different column than the one I'm filtering on for events happening in the future. I don't care about the data in that column, so I didn't think about it. You can mark this as a duplicate.
