### ISSUE TITLE
Download in Excel not working in Edge (legacy)

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11984]
**Describe the bug**
I try to download the query data in Edge on Windows, but nothing seems to happen.

**Logs**
Frontend (not sure if relevant):
`3SCRIPT5022: SCRIPT5022: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vendor.bundle.js (1,285943)
8TypeError: Unable to get property 'displayName' of undefined or null reference
column Naam joined-field,Gebruikers,field-id,250
new joined-field,Gebruikers,field-id,250
old field-id,250
`

Backend:
`x.x.x.x - - [25/Feb/2020:20:29:31 +0000] "POST /api/card/2/query/xlsx HTTP/1.1" 202 4554 "https://x.x.x/question/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362"`

**To Reproduce**
1. Go to any question.
2. Click on the download icon and choose Excel (maybe any other one).
3. Observe nothings happens.

**Expected behavior**
The file should download.

**Information about your Metabase Installation:**
Browser info below is my dev browser. The Edge version in question is above in the backend log.
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
Pretty bad, as we have to tell our clients not to use IE 11, but now also not Edge.

**Additional context**
I suspect a regression, as I think it used to work in a previous minor version. Edge on Mac does work. Chrome on Windows and Mac do, too.

**Comment by flamber** [comment]
Hi @andreychirikba 
Which version of Edge? The old Edge or the new that uses Blink (Chromium) for rendering?
I have a feeling it's the new `202` response that Edge doesn't like - #11817.
Workaround: Downgrade to 0.34.1, it should work. Remember to backup before downgrading.

**Comment by andreychirikba** [comment]
@flamber, not sure as this was reported by a customer. I tried on Edge/18.18362, which is from May 2019 with the same results.
Thanks for your tip.

**Comment by annikolov** [comment]
@flamber  Same issue here with Microsoft EdgeHTML 18.18363

**Comment by flamber** [comment]
@annikolov Microsoft is replacing Edge (EdgeHTML) with Edge Chromium (Blink). They started pushing Windows Updates in June 2020 to some versions of Windows 10.

**Comment by annikolov** [comment]
@flamber Thanks, I checked it - as of beginning of June 2020 "Microsoft is now rolling out the updated version of its Edge browser on Windows 10 through Windows Software Updates. The update will be available to Windows 10 users running 1803, 1809, 1903, and 1909 builds."

I am running Windows 10 build 1909 and waiting for the May update to be available to me. Will post once when/if it gets fixed!

**Comment by annikolov** [comment]
Works now after the last Edge update

"Version 85.0.564.44 (Official build) (64-bit)
This browser is made possible by the Chromium open source project and other open source software."

**Comment by flamber** [comment]
Fixed by #13500
