### ISSUE TITLE
Incorrect date sorting in dashboard

### ISSUE THREAD

**Issue by lucas34** [metabase/metabase#11999]
**Describe the bug**
Sorting date for data in table's dashboard is only sorting based on the date of the month. Date is sorted from 0-31. Regardless of the month or the year.

**To Reproduce**
1. Create a query and format with date_format
2. Add your query to a dashboard
3. Tap on the date header name to sort by date

**Expected behavior**
Date should be sorted with year and month as well.

**Screenshots**
![Screenshot 2020-02-27 at 2 51 55 PM](https://user-images.githubusercontent.com/7482647/75419986-f1bb9380-5971-11ea-8f0a-88a935e2093c.png)

**Information about your Metabase Installation:**
- Your browser and the version: Safari 13.0.5 
- Metabase version: 0.33.7.3

**Severity**
Would be nice to have but severity is low

**Comment by flamber** [comment]
Hi @lucas34 
But if you're doing `date_format`, then you're essentially returning a string that Metabase cannot understand.
I've just tested on `master` and it correctly works for Custom and Native questions, but for Native, it needs to return a `date`, which you format via the visualization Settings.
![image](https://user-images.githubusercontent.com/1447303/75438272-f2473080-5957-11ea-8eef-b7599e8d8de6.png)
I'm going to close this, but please let me know if I misunderstood the problem - if so, then please provide full steps-to-reproduce.
