### ISSUE TITLE
Clicking RawData-toggle on pivoted table makes the question dirty and shows Save-button

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11994]
**Describe the bug**
When viewing a pivot table with a user with view-only permissions, then clicking raw-data-toggle makes the question "dirty" (modified URL) and shows Save button, and will fail to refresh the query if run again.

**To Reproduce**
1. Login as view-only user (no data permissions, and view-only to collection)
2. Go to a question visualized as pivot table
3. Click the raw-data-toggle (bottom-center)
4. Will change the URL and show Save button
5. Trying to run the query again will result in error `Sorry, you don’t have permission to see that.`

**Information about your Metabase Installation:**
Metabase 0.34.3 and `master`

**Additional context**
Very similar to #6718 #9772

**Comment by kamilmielnik** [comment]
Reproducible in 0.35.3 (warning: requires JDK 11).
Cannot reproduce in `master` at 90d2b800b3.

> Click the raw-data-toggle (bottom-center)

For pivot questions this is no longer shown.
I tried with combo visualization and still cannot reproduce.
