### ISSUE TITLE
Feature Request/Assistance Needed: Dynamic Goal Setting in 'Progress' visualization

### ISSUE THREAD

**Issue by AmirTKashi** [metabase/metabase#11993]
**Current Situation**

I have an aggregated table (a single number), like this:

![sumoftotal](https://user-images.githubusercontent.com/40166454/75338609-e8a1c800-5886-11ea-8790-a8df5c13c764.png)

I can visualize this number with `Progress` visualization tool, if I statically set the `Goal` in the settings of this card, like this:

![Progress](https://user-images.githubusercontent.com/40166454/75339053-adec5f80-5887-11ea-9ba8-2d32536867db.png)

**Desired Feature: Dynamic setting of the `Goal`**

I want to give an option to the user to set the `Goal` dynamically when I add the card to the dashboard. One possible solution could be making the capability to click on the `Goal` in the dashboard and change the goal value.

![dash](https://user-images.githubusercontent.com/40166454/75339462-7b8f3200-5888-11ea-8bd9-372a004ecc1e.png)

**Alternatives**
I considered to read the `Goal` value from another table, but one problem is that the `Progress` accepts just one input. So even I have the value for the `Goal` in another column, I can not use it in `Goal` visualization.

**Importance**
Having this capability is something more than 'nice to have', because in most of the times the `Goal` is not a fixed number that we can set it beforehand, and the user needs to have the option to set it on his dashboard manually (say every month for example).

**Comment by flamber** [comment]
Hi @AmirTKashi 
You can change the visualization settings of a card on the dashboard. When you edit the dashboard, then hover the card and click the gear icon (:gear:). Those settings are different from the question.
As for dynamic goal, that's requested in #4412, so closing this a duplicate. Upvote by clicking :+1:
