### ISSUE TITLE
Remove 60 second timeout from the BigQuery driver

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12003]
### NOTE
This is specific to the BigQuery and Druid driver.
If you're seeing the message "Your question took too long", then adjust the timeout of your proxy/load-balancer - see #12423 for more details.
### NOTE

---

**Is your feature request related to a problem? Please describe.**
Some drivers (BigQuery and Druid) still have 60 seconds query timeouts, which seems like legacy code compared to other drivers.

https://github.com/metabase/metabase/blob/256f8cef7a7c68ea9c29ff66b2c8c5168fb3c837/modules/drivers/bigquery/src/metabase/driver/bigquery.clj#L129

https://github.com/metabase/metabase/blob/256f8cef7a7c68ea9c29ff66b2c8c5168fb3c837/modules/drivers/druid/src/metabase/driver/druid/query_processor.clj#L144

Simon said:
> We might get away with removing it completely with the new streaming QP as it also improves query cancelation.

**Describe the solution you'd like**
Remove timeouts, so it matches other drivers - or make it possible to configure it (i.e. conn string?).

**Describe alternatives you've considered**
It doesn't seem like it's possible to modify the timeout unless creating a custom driver.

**Additional context**
_Not sure if this should have been tagged as a bug instead?_
https://discourse.metabase.com/t/cant-modify-60s-query-timeout-threshold-not-enough-bigquery/8712
https://github.com/metabase/metabase/issues/1749#issuecomment-553830844
Would perhaps close #6836 and #7013 too, but maybe that was fixed by connection handling in 0.35 already?

_(Most of the votes here are for #12423, so this cannot be used for anything)_

**PLEASE DO NOT UPVOTE THIS ISSUE - YOU ARE LOOKING FOR #12423**

**Comment by ChethanUK** [comment]
+1 
Issuse with Presto in v0.35.3

**Comment by flamber** [comment]
@ChethanUK 
I don't see any timeouts in the driver of Presto, so perhaps you're experiencing different timeouts, like your proxy/load-balancer is dropping the connection? See #12335

**Comment by smatting** [comment]
Same issue with Postgres in v0.35.3. All questions fail when they don't finish within 60 seconds. We had to downgrade to v0.34.3 which allowed for longer running questions again.

**Comment by ChethanUK** [comment]
> We had to downgrade to v0.34.3

Ha, I did the same..

**Comment by flamber** [comment]
@smatting @ChethanUK Can we move the discussion to the forum, since it has nothing to do with this issue, which is specific to the drivers of BigQuery and Druid. https://discourse.metabase.com/

**Comment by Japhys** [comment]
Experiencing the same when connecting to a Matomo database (MySQL 8). It is recording 5-7 million visits a month and 60 seconds will definitely not suffice for a quarterly report I have noticed

![Screenshot (6)](https://user-images.githubusercontent.com/24695937/81590686-7e93bc00-93bb-11ea-98ae-e35f21df5ca7.png)

**Comment by flamber** [comment]
@Japhys You didn't read the **NOTE** in the beginning - see #12423

**Comment by Japhys** [comment]
@flamber You are quite righ! Srorry about that and thanks for pointing it out to me. I will edit proxy

**Comment by haochencheng** [comment]
eye

**Comment by flamber** [comment]
This specific driver issue was fixed by #17959 and will be part of Metabase 0.41.0 with the new BigQuery driver.
