### ISSUE TITLE
Block automatic loading of the tables (automatic query execution) in Browse your data

### ISSUE THREAD

**Issue by lucaslrolim** [metabase/metabase#12002]
When we explore data in "Browse your Data," if we click on a database and then on a table, Metabase automatically executes a query with a TOP statement in this table. 

That is very risky for high resource-consuming data, like views or huge tables. Take BigQuery as an example, where we pay by computation resources, and a TOP * statement can be costly even if we use a LIMIT clause. 

It could be interesting to allow to deny this kind of behavior from Metabase or implement some cache system to cover this case.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @lucaslrolim 
It sounds like you're looking for the setting "Automatically run queries when doing simple filtering and summarizing" under Admin > Troubleshooting > Databases > (db)
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#query-auto-running-settings
Does that fix your issue?

**Comment by lucaslrolim** [comment]
Hi @flamber 

The issue is more related to the user's interaction with the tables after choosing a database in the "Browser Data" section.

For example, I would like the users to have the possibility to navigate through databases and tables, but I don't want they have the possibility to automatic run a TOP statement in all the table after selecting it. Or I would like a cache to this all table TOP statements. 

![metabase_ex](https://user-images.githubusercontent.com/9875473/75697267-9815da80-5c8b-11ea-8627-a8c721735ba9.png)

**Comment by pcreux** [comment]
+1 for this. These queries can be very costly for large tables on BigQuery.

**Comment by dpsutton** [comment]
We seem to not be running TOP queries for bigquery, or for any other databases. 
When I browse data, the only query that runs is when i select a table and it runs the following:

```sql
SELECT `google_trends.international_top_rising_terms`.`rank`         AS `rank`,
       `google_trends.international_top_rising_terms`.`percent_gain` AS
       `percent_gain`,
       `google_trends.international_top_rising_terms`.`refresh_date` AS
       `refresh_date`,
       `google_trends.international_top_rising_terms`.`region_code`  AS
       `region_code`,
       `google_trends.international_top_rising_terms`.`term`         AS `term`,
       `google_trends.international_top_rising_terms`.`week`         AS `week`,
       `google_trends.international_top_rising_terms`.`score`        AS `score`,
       `google_trends.international_top_rising_terms`.`country_name` AS
       `country_name`,
       `google_trends.international_top_rising_terms`.`country_code` AS
       `country_code`,
       `google_trends.international_top_rising_terms`.`region_name`  AS
       `region_name`
FROM   `google_trends.international_top_rising_terms`
LIMIT  2000  
```

We also have new caching features that have landed.
