### ISSUE TITLE
Invalid conversion requested with native oracle SQL query and date parameters

### ISSUE THREAD

**Issue by buckelieg** [metabase/metabase#12009]
I have a native SQL query run against ORACLE with date parameters.
Query is recursive and looks like:

`WITH parameters AS (
        SELECT
            TO_DATE('{{dateFrom}}', 'yyyy-mm-dd') AS date_from,
            LEAST(SYSDATE, TO_DATE('{{dateTo}}', 'yyyy-mm-dd')) AS date_to
      FROM dual
    )
.... blah blah blah

SELECT * FROM ds  WHERE 1=1 AND dateField <= (SELECT date_to FROM parameters)`

when I try to execute it gives me an error of "Invalid conversion requested (code 17132)".
When I change parameters type to text andd enter data in appropriate format - everything is fine, but on UI user have to enter values manually - w/o datepicker widget.
How should I set up the things to get my query execute successfully?

**Comment by flamber** [comment]
Hi @buckelieg 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Try removing the single-quote around the variable - that should automatically be added based on type.
