### ISSUE TITLE
Visualization: Stacked combo charts (stacked bars with lines)

### ISSUE THREAD

**Issue by adysssal** [metabase/metabase#12008]
Is there a stacked bar with a line series (similar to combo but stacked bars) feature?'

![image](https://user-images.githubusercontent.com/24953920/75520836-6a3d5580-5a41-11ea-993a-f6306b96c992.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by EBoisseauSierra** [comment]
There could have been a workaround, where you overlay 2 charts: one stacked bar, and one line.
![Screenshot from 2020-02-28 10-19-19](https://user-images.githubusercontent.com/37387755/75540444-f8024c00-5a13-11ea-8d95-63ed2fe437bf.png)

However, it doesn't work, as you either “stack” the series (and the line is transformed as a beam — despite its type still being a line):
![Screenshot from 2020-02-28 10-18-56](https://user-images.githubusercontent.com/37387755/75540499-0fd9d000-5a14-11ea-80e1-fea054b34f3c.png)

Or if you want to keep the line as a line, you are forced to unstack the beams
![Screenshot from 2020-02-28 10-19-05](https://user-images.githubusercontent.com/37387755/75540541-241dcd00-5a14-11ea-94cf-0a32ed3e99ce.png)

**Comment by denispavliha** [comment]
Probably, there should be introduced something as "stack groups" under Stacking where now there are the three options (Don't Stack, Stack, Stack-100%). Because otherwise by only moving the "Stacking" sections under separate dataseries, you would only solve this partially (i.e. you would only put data as stacked or not-stacked, whereas one could probably need multiple stacked bars). So "stack groups" should solve this.

**Comment by nawababuzer** [comment]
+1

**Comment by waydev** [comment]
This will be a very useful feature for reporting (the ability to combine two different chart types: stack group and line). Are you considering adding it to the next release?

**Comment by ASHISHTOM** [comment]
Any update on this??

**Comment by ASHISHTOM** [comment]
> This will be a very useful feature for reporting (the ability to combine two different chart types: stack group and line). Are you considering adding it to the next release?

Will be very helpful if it is included this feature in the next release.

**Comment by agenterp** [comment]
@brunobergher is there any plan to realize this feature ?

**Comment by brunobergher** [comment]
Yes, it's planned for the next release. You can follow along on metabase.com/roadmap (which will have varying levels of granularity).

**Comment by TVanneufvilleJoko** [comment]
Hey there, is there any plan of action regarding this feature? When can we expect to have it on Metabase? I'm currently negotiating with my CEO to upgrade our Starter Plan to the Pro Plan, but he's telling me that not having such basic feature is a strong no against paying more for this tool. Thanks a lot in advance!

**Comment by bethrice44** [comment]
Hey, I'm also keen for this feature - are there any plans to have it in a future release?

**Comment by cdeweyx** [comment]
This is merged for Metabase 50 and available now if you try out the [Release Candidate 1](https://github.com/metabase/metabase/releases/tag/v0.50.0-RC1). If you give it a spin, drop us a note with how it goes.
