### ISSUE TITLE
Public shared question does not show Y-axis

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12018]
**Describe the bug**
When viewing a question via the public sharing, the Y-axis is not shown.
Doesn't matter if there's one/multiple series, or auto/force axis position.
If using public dashboard, then the Y-axis is displayed on the card.

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Summarize by Count, grouped by CreatedAt:Year
3. Save question and enable public sharing
4. View the public link - no Y-axis
5. Resizing the browser (thanks Andrew!) makes it display the Y-axis.

**Screenshots**
![image](https://user-images.githubusercontent.com/1447303/75664174-5167b680-5c72-11ea-8ba0-47ea81139ce6.png)
![image](https://user-images.githubusercontent.com/1447303/75664193-59bff180-5c72-11ea-8a43-6465f5545946.png)

**Information about your Metabase Installation:**
Metabase 0.33.5.1, 0.34.3 and `master`, various setups and browsers.

**Additional context**
https://discourse.metabase.com/t/public-question-doesnt-show-y-axis-via-shared-link-or-iframe-on-load/9201

**Comment by paulrosenzweig** [comment]
Fixed in #12022
