### ISSUE TITLE
Oracle Tables not getting listed in Metabase 

### ISSUE THREAD

**Issue by Mohammedhusen** [metabase/metabase#12041]
Hi Team,

I was trying to generate some reports using oracle database but I could see a issues while importing tables however I can write custom query using sql.

So is there solution for this issues ?

**Comment by flamber** [comment]
Hi @Mohammedhusen 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
If you see any issues/errors, while importing, then post those. Admin > Troubleshooting > Logs
Remember to include Admin > Troubleshooting > Diagnostic Info
And the version of ojdbc driver.
