### ISSUE TITLE
Changing columns via visualization Settings makes Notebook column list inconsistent

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12044]
**Describe the bug**
When changing visible columns via visualization Settings ("Visible columns" and "More columns") makes the column list under Notebook editor incorrectly selected.

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Click visualization Settings and add "Product -> EAN"
3. Go to Notebook editor (top-right)
4. Click Columns (to the right) of Orders table
5. "Created At" is deselected

Same thing happens if removing columns:
1. Simple question > Sample Dataset > Orders
2. Click visualization Settings and remove "Subtotal"
3. Go to Notebook editor (top-right)
4. Click Columns (to the right) of Orders table
5. "Created At" is deselected, along with "Subtotal"

**Expected behavior**
When adding a column, expected it would create a joined table under Notebook and select the column.
Right now it feels like it's doing two different things if done via Simple vs Notebook. Legacy?

**Information about your Metabase Installation:**
Metabase 0.34.3 and `master`

**Comment by uladzimirdev** [comment]
It was broken in 0.46.5 and all the prior versions, but it's fixed in master as of bdbbb61d57

**Comment by uladzimirdev** [comment]
I was able to reproduce the problem even in 0.47.3, but not in master, thanks team for the fix

**Comment by uladzimirdev** [comment]
seems https://github.com/metabase/metabase/pull/33030 fixed the problem

**Comment by camsaul** [comment]
Fixed by #33030 in `master`/48
