### ISSUE TITLE
SQLite TIMESTAMP column can only be displayed as time (“8:00 PM”) 

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#12045]
## Bug description

I have a SQLite database (attached) with a `TIMESTAMP` column.

![Screenshot from 2020-03-04 15-56-35](https://user-images.githubusercontent.com/37387755/75898313-ce8d5a00-5e31-11ea-815b-6746f9809ee2.png)
![Screenshot from 2020-03-04 15-56-47](https://user-images.githubusercontent.com/37387755/75898320-d0efb400-5e31-11ea-8418-cbc1306a8421.png)

I connect the database, and set the column as _Creation Date_ in the data model.

![datamodel](https://user-images.githubusercontent.com/37387755/75898492-07c5ca00-5e32-11ea-9b1d-60e207022b32.png)

However, the `Date` column is rendered as a time, despite correct formatting.

![question](https://user-images.githubusercontent.com/37387755/75898605-32178780-5e32-11ea-8d80-94c2adfa0923.png)

Additionally, when trying to aggregate by `Date`, I cannot select the time granularity (here forced to Week — but forced to Month in my real db):
![Screenshot from 2020-03-04 16-12-27](https://user-images.githubusercontent.com/37387755/75899342-50ca4e00-5e33-11ea-9954-d0c76179b40c.png)
![Screenshot from 2020-03-04 16-12-31](https://user-images.githubusercontent.com/37387755/75899360-53c53e80-5e33-11ea-874a-950de51237a9.png)

Logs don't seem to raise any issue.

## Expected behaviour

I would like my `Date` column to be treated as a date.

## Severity

My data set isn't usable for what regards time series at the moment.

## System

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "5.5.7-200.fc31.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "sqlite"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.3",
      "date": "2020-02-25",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": "Europe/London"
    }
  }
}
```

## Sample database

[test.db.pdf](https://github.com/metabase/metabase/files/4288375/test.db.pdf)
(Just remove the `.pdf` suffix I had to add to circumvent file type upload restriction.)

**Comment by flamber** [comment]
Interesting. It's getting base_type as `type/Time`, but still fingerprinted as `type/DateTime`.
I'm not sure how related it might be to #11703.
`/api/table/X/query_metadata`:
```
...
{
  "3": {
    "description": null,
    "database_type": "TIMESTAMP",
    "table_id": 130,
    "special_type": "type/CreationDate",
    "name": "Date",
    "fingerprint_version": 4,
    "has_field_values": "none",
    "settings": null,
    "caveats": null,
    "fk_target_field_id": null,
    "dimensions": [],
    "dimension_options": [],
    "updated_at": "2020-03-04T22:43:51.824",
    "active": true,
    "parent_id": null,
    "id": 855,
    "last_analyzed": "2020-03-04T22:42:44.344",
    "position": 0,
    "visibility_type": "normal",
    "default_dimension_option": null,
    "target": null,
    "preview_display": true,
    "display_name": "Date",
    "fingerprint": {
      "global": {
        "distinct-count": 6,
        "nil%": 0
      },
      "type": {
        "type/DateTime": {
          "earliest": "2017-12-03T00:00:00",
          "latest": "2018-01-31T00:00:00"
        }
      }
    },
    "created_at": "2020-03-04T22:42:44.169",
    "base_type": "type/Time",
    "points_of_interest": null
  }
}
...
```
