### ISSUE TITLE
Funnel graph cuts labels, when dashboard card is specific sizes (and/or smaller viewport)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12042]
**Describe the bug**
Funnel graph doesn't stay within card size when resizing card on dashboard or browser window.

**To Reproduce**
1. Native question with this query, change visualization to Funnel, save and add to dashboard
```
SELECT 'Registered' AS Step, 31159 AS Count UNION ALL 
SELECT 'Info_first' AS Step, 28372 AS Count UNION ALL 
SELECT 'Info_second' AS Step, 21494 AS Count UNION ALL 
SELECT 'DOI' AS Step, 19317 AS Count UNION ALL 
SELECT 'Verified' AS Step, 12284 AS Count UNION ALL 
SELECT 'Paid' AS Step, 1522 AS Count
```
2. Resize the card to 7x5:
![image](https://user-images.githubusercontent.com/1447303/75876393-ea830280-5e15-11ea-8d3e-4aab4ae8ebf4.png)
3. Resize the card to 8x5 resize the browser window to ~900px
![image](https://user-images.githubusercontent.com/1447303/75876598-45b4f500-5e16-11ea-8452-b9108df8c802.png)

**Information about your Metabase Installation:**
Metabase 0.34.3, various backends and browsers.

**Additional context**
https://discourse.metabase.com/t/funnel-graph-breaks/9238
Related to #12175

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by saeedesmaili** [comment]
The funnel chart doesn't look good for me too if the steps are less than 5:
(Metabase v0.33.6)
![image](https://user-images.githubusercontent.com/13351748/77255823-e36a4a00-6c87-11ea-835e-7f718faab468.png)

**Comment by flamber** [comment]
@saeedesmaili Please upgrade to latest release (0.34.3) and can you provide a static SQL to reproduce your problem?

**Comment by saeedesmaili** [comment]
Here is the result for a sample dummy query:
![image](https://user-images.githubusercontent.com/13351748/77315736-b1a7c080-6d25-11ea-8457-2b31781bd945.png)
The Metabase that I'm using is deployed in my organization, so I have to ask our data engineering team to update it (and I will do).

**Comment by flamber** [comment]
@saeedesmaili Created #12175 - go and upvote.

**Comment by flamber** [comment]
Changing priority, since this makes funnels very difficult via Embedding, which changes the viewport similar to low resolution.
