### ISSUE TITLE
[Regression] Can't select table for joins in notebook on master

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#12059]
If you try to select a table to join to, all you see is the database. Clicking the database doesn't do anything.

![image](https://user-images.githubusercontent.com/2223916/75951653-6bb3b700-5e61-11ea-8fa1-58c2d35564d4.png)

**Comment by jankatins** [comment]
I've similar issue which happen when I click on an already safed question and try to edit it: the columns are gone. I've also seen the above where I couldn't pick tables. 

![image](https://user-images.githubusercontent.com/890156/75965121-a6046f00-5ec8-11ea-8c24-8b3806e1c176.png)

I also have problems when I insert stuff in dashboards where two questions have both the city table joined but I cannot add a filter. I remember I was able to add the filter earlier, so no clue why it disappeared now:

![image](https://user-images.githubusercontent.com/890156/75965427-1c08d600-5ec9-11ea-83c4-dd70c48e96e7.png)

We are on v0.34.1

**Comment by mazameli** [comment]
In case @metabase/core-developers missed this last night, I think this is a 0.35 release blocker. We shouldn't be breaking joins in a new release. I've added this issue to the 0.35 milestone and to the to-dos in our product team board.
