### ISSUE TITLE
"Run query" button should say "Get Answer"

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1205]
Nowhere else do we reference the word "query," and throughout the product we refer instead to "questions:" New Question, Saved Questions, etc. For consistency and great justice. 👻

**Comment by mazameli** [comment]
I'm good with "Get answer" for the button, which means we should change the placeholder copy on the QB empty state to "If you're stuck, you can always just pick a table and hit "Get answer" to get started."

I'm talking about this copy:

<img width="598" alt="screen shot 2015-10-29 at 5 03 04 pm" src="https://cloud.githubusercontent.com/assets/2223916/10835380/f4d9a522-7e5e-11e5-8f0a-36c013d3215c.png">

**Comment by salsakran** [comment]
Did we want to go forward with this? I'm still +1 for "Get Answer".

**Comment by mazameli** [comment]
Yeah, I still think I like it better than "run query."

**Comment by salsakran** [comment]
cool, it's marked as ready to go.
