### ISSUE TITLE
Full App embed postMessage listener not working with multiple domains

### ISSUE THREAD

**Issue by denkomanceski** [metabase/metabase#12069]
**Describe the bug**
I have the following handler for messages

```window.addEventListener('message', (e) => { console.log(e) })```
Whenever I change the url on the metabase embedded iframe, I should get a message with the new location. I am not getting anything

On the other hand, when I postMessage from the parent (I use this when I want the parent to modify the URL, it works fine)

I am on enterprise edition.

**To Reproduce**
Attach a window.addEventListener('message') and click around on the embedded metabase. You will not get any messages.

**Expected behavior**
https://www.metabase.com/docs/latest/enterprise-guide/full-app-embedding.html

As documented, I am supposed to get an object in which I will see the current URL

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @denkomanceski 
Please post "Diagnostic Info" from Admin > Troubleshooting.
Can you post your (redact domains if needed) `MB_EMBEDDING_APP_ORIGIN`?
I think I'm seeing a possible problem, but I need extra info, so I can try to reproduce.

**Comment by denkomanceski** [comment]
Yeah. We are using reverse proxy. Embedding app origin is okay otherwise I wont be able to embed the site at all, right?

**Comment by denkomanceski** [comment]
[e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:10+01:00 INFO metabase.core Starting Metabase in STANDALONE mode [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:10+01:00 INFO metabase.server Launching Embedded Jetty Webserver with config:  {:port 3000, :host "0.0.0.0"}  [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:10+01:00 INFO metabase.core Starting Metabase version v1.34.3 (ab6cc46 enterprise-release-1.34.x) ... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:11+01:00 INFO metabase.core System info: {"java.runtime.name" "OpenJDK Runtime Environment", "java.runtime.version" "11.0.5+10", "java.vendor" "AdoptOpenJDK", "java.vendor.url" "https://adoptopenjdk.net/", "java.version" "11.0.5", "java.vm.name" "OpenJDK 64-Bit Server VM", "java.vm.version" "11.0.5+10", "os.name" "Linux", "os.version" "4.15.0-62-generic", "user.language" "en", "user.timezone" "GMT"}  [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:11+01:00 INFO metabase.plugins Loading plugins in /plugins... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :hive-like... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered abstract driver :sql 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :sparksql... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :sparksql (parents: [:hive-like]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.  [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Plugins with unsatisfied deps: ["Metabase Oracle Driver"] [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :redshift... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :postgres (parents: [:sql-jdbc]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :redshift (parents: [:postgres]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies' [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Google Analytics Driver"] [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :snowflake... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :snowflake (parents: [:sql-jdbc]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :presto... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :presto (parents: [:sql]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :google... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered abstract driver :google 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.initialize Dependencies satisfied; these plugins will now be loaded: ["Metabase Google Analytics Driver"] [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :googleanalytics... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :googleanalytics (parents: [:google]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :sqlite... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :sqlite (parents: [:sql-jdbc]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.  [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Vertica Driver"] [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies' [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.plugins.dependencies Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :bigquery... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :bigquery (parents: [:sql :google]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :sqlserver... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :druid... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:13+01:00 INFO metabase.driver.impl Registered driver :druid 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :mongo... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.driver.impl Registered driver :mongo 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.driver.impl Registered driver :h2 (parents: [:sql-jdbc]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.driver.impl Registered driver :mysql (parents: [:sql-jdbc]) 🚚 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.core Setting up and migrating Metabase DB. Please sit tight, this may take a minute... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.db Verifying postgres Database Connection ... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.driver.impl Initializing driver :sql... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.driver.impl Initializing driver :sql-jdbc... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.driver.impl Initializing driver :postgres... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.db Successfully verified PostgreSQL 11.5 application database connection. ✅ [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:14+01:00 INFO metabase.db Running Database Migrations... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:15+01:00 INFO metabase.db Setting up Liquibase... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:15+01:00 INFO metabase.db Liquibase is ready. [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:15+01:00 INFO metabase.db.liquibase Checking if Database has unrun migrations... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:18+01:00 INFO metabase.db Database Migrations Current ... ✅ [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:18+01:00 INFO metabase.db.migrations Running all necessary data migrations, this may take a minute. [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:18+01:00 INFO metabase.db.migrations Finished running data migrations. [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.activity-feed 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.dependencies 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.driver-notifications 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.last-login 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.metabot-lifecycle 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.notifications 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.revision 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.sync-database 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.events Starting events listener: metabase.events.view-log 👂 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:19+01:00 INFO metabase.task Initializing task SyncDatabases 📆 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:20+01:00 INFO metabase.task Initializing task CheckForNewVersions 📆 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:20+01:00 INFO metabase.task Initializing task SendAnonymousUsageStats 📆 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:20+01:00 INFO metabase.task Initializing task SendAbandomentEmails 📆 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:20+01:00 INFO metabase.task Initializing task SendPulses 📆 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:20+01:00 INFO metabase.task Initializing task SendFollowUpEmails 📆 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:21+01:00 INFO metabase.task Initializing task TaskHistoryCleanup 📆 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:37:21+01:00 INFO metabase.core Metabase Initialization COMPLETE [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:26+01:00 INFO metabase.public-settings.metastore Checking with the MetaStore to see whether b5c81d99f2ef3e4ce4dae0cc1083fd025e01da129367c144240d7370320eb9de is valid... [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:26+01:00 INFO metabase.public-settings.metastore Using this URL to check token: https://store.metabase.com/api/b5c81d99f2ef3e4ce4dae0cc1083fd025e01da129367c144240d7370320eb9de/v2/status [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:27+01:00 WARN metabase.routes.index Locale 'en' not found. [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:28+01:00 DEBUG metabase.middleware.log GET /api/session/properties 200 55.6 ms (1 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (39 total active threads) Queries in flight: 0 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:28+01:00 DEBUG metabase.middleware.log GET /api/user/current 200 497.8 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (40 total active threads) Queries in flight: 0 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:29+01:00 DEBUG metabase.middleware.log GET /api/user/current 200 49.0 ms (3 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (40 total active threads) Queries in flight: 0 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:29+01:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 352.8 ms (8 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (40 total active threads) Queries in flight: 0 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:29+01:00 DEBUG metabase.middleware.log GET /api/collection/root 200 49.8 ms (2 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (40 total active threads) Queries in flight: 0 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:29+01:00 DEBUG metabase.middleware.log GET /api/database 200 61.7 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (40 total active threads) Queries in flight: 0 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:33+01:00 DEBUG metabase.middleware.log GET /api/database 200 35.7 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (40 total active threads) Queries in flight: 0 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 DEBUG metabase.middleware.log GET /api/dashboard/4 200 450.3 ms (15 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (40 total active threads) Queries in flight: 0 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 4092 ms; using 'magic' TTL of 41 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 4078 ms; using 'magic' TTL of 41 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 WARN metabase.middleware.log GET /api/database/2/metadata 403 427.4 ms (3 DB calls)  "You don't have permissions to do that."  [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 4108 ms; using 'magic' TTL of 41 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 1107 ms; using 'magic' TTL of 11 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 1494 ms; using 'magic' TTL of 15 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 4154 ms; using 'magic' TTL of 42 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.query-processor.middleware.cache Using query processor cache backend: :db 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 1989 ms; using 'magic' TTL of 20 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 4137 ms; using 'magic' TTL of 41 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:38+01:00 INFO metabase.api.card Question's average execution duration is 4155 ms; using 'magic' TTL of 42 seconds 💾 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:41+01:00 INFO metabase.query-processor.middleware.cache Query took 2914 ms to run; miminum for cache eligibility is 30000 ms [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:41+01:00 INFO metabase.query-processor.middleware.cache Query took 2906 ms to run; miminum for cache eligibility is 30000 ms [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:41+01:00 INFO metabase.query-processor.middleware.cache Query took 2906 ms to run; miminum for cache eligibility is 30000 ms [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:41+01:00 DEBUG metabase.middleware.log POST /api/card/37/query 202 [ASYNC: completed] 3.2 s (17 DB calls) Jetty threads: 2/50 (12 idle, 0 queued) (61 total active threads) Queries in flight: 8 [e816ee5a-401d-4bea-a68b-bdd267f80ba3] 2020-03-06T21:44:41+01:00 DEBUG metabase.middleware.log POST /api/card/23/query 202 [ASYNC: completed] 3.3 s (17 DB calls) Jetty threads: 2/50 (12 idle, 0 queued) (61 total active threads) Queries in flight: 6

**Comment by flamber** [comment]
@denkomanceski 
Okay, I mean just the "Diagnostic Info" from Admin > Troubleshooting, but I can see most of the information from the log.
Please post your `MB_EMBEDDING_APP_ORIGIN` or the field in Admin > Settings > Embedding, if you're not using the environment variable. Redact domains with `example.com`, `sub.domain.example` etc.

**Comment by denkomanceski** [comment]
![2CFBA81C-F771-4318-B517-9D2E52891883](https://user-images.githubusercontent.com/10501247/76144025-8615ac80-607c-11ea-9735-919473e6c92c.jpeg)

The second is localhost:4200

**Comment by denkomanceski** [comment]
I also got this now: https://prnt.sc/rcz75o

I removed localhost, and I removed the wildcard.. its only `app.viewly.one` now

**Comment by denkomanceski** [comment]
I found the bug, it was my bad

**Comment by flamber** [comment]
@denkomanceski Great you found a solution, but I actually think we have a "bug".
We're setting the `targetOrigin` of [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to setting of `MB_EMBEDDING_APP_ORIGIN`.
The problem is that `MB_EMBEDDING_APP_ORIGIN` can contain multiple URLs, but `targetOrigin` only allows a single URL.
So I'll reopen this, since we either need to document it more clearly or have different settings.

**Comment by andybluntish** [comment]
I believe we're are running into this issue too.

Specifying multiple domains doesn't appear to work—as you noted above, the `targetOrigin` only supports a single value, while the configuration allows for multiple values.

Even with a single value, a wildcard character in the domain is causing errors—e.g `https://*.example.com`:

Chrome
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://%2A.example.com') does not match the recipient window's origin ('https://app.example.com').
```

FireFox
```
SyntaxError: An invalid or illegal string was specified
```

It seems using `MB_EMBEDDING_APP_ORIGIN` as the `targetOrigin` directly is not going to work to support multiple origins/wildcards.

Perhaps a solution might be to use the parent window's origin as the `targetOrigin`, and use `MB_EMBEDDING_APP_ORIGIN` to validate that during initialisation? (just thinking out loud, I am quite unfamiliar with the Metabase internals).

**Comment by intellischool-dave** [comment]
+1 for this - we're having this exact issue with Metabase Enterprise. We use a couple of TLDs and having multiple `MB_EMBEDDING_APP_ORIGIN` values breaks messaging between the parent and child iframe.

Changing it to a single value is fine for our dev purposes, but we'll need this fixed before we put Metabase into our beta or production environments :)

**Comment by coffeedoughnuts** [comment]
We're evaluating enterprise metabase integration and just run into this bug too.. we have our origin set to `https://*.ourdomain.com http://localhost:3000" and messages don't work. They work fine when I set it to just "http://localhost:3000" but obviously that isn't going to work when we deploy

**Comment by paoliniluis** [comment]
I think this might be an issue in iframe-resizer component, but I might be wrong: https://github.com/davidjbradshaw/iframe-resizer/issues/707
