### ISSUE TITLE
How could I get "table" name on mongoDB

### ISSUE THREAD

**Issue by baocaixue** [metabase/metabase#12067]
Now, I wanna get table name, just like ''8 D6f31441 9156 418e 87c9 504d67d46032", because the table name is my filter condition
![image](https://user-images.githubusercontent.com/30517451/76039747-4d94a680-5f88-11ea-9466-0153f9133d45.png)

**Comment by flamber** [comment]
Hi @baocaixue 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
