### ISSUE TITLE
Support filtering on aggregate values (aka SQL having clause)

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1207]
This is meant to be the SQL equivalent of the HAVING clause ... https://en.wikipedia.org/wiki/Having_(SQL)

An example of its use would be to select the count of Posts for any user having more than 100 posts.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by camsaul** [comment]
Just like expressions we'll have to add aggregate columns to the filter widget. I think we'll want to make sure we only do it if we have a breakout column as well (e.g. it doesn't make sense to filter by `SUM(x) > 100` if we're just returning a single row)

**Comment by VikramTiwari** [comment]
Wow! This is an old issue. Any thoughts on this?

**Comment by thesequelgroup** [comment]
Agreed this is useful. Please consider adding it? Maybe a toggle for simple GUI builder and Advanced with more features.

**Comment by ashalitkin** [comment]
Would be a super useful, any plans on it's implementation?

**Comment by matrpedreira** [comment]
I'm in need of this feature too. As an example, I was trying to figure it out the lifetime value of my clientes who purchased my product at least 2 times and this feature would be really helpful for something like that.

Each purchase is a row on the DB.

**Comment by asaqer** [comment]
Any Updates regarding this? Its super useful

**Comment by anoopk19** [comment]
Any updates on this?

**Comment by salsakran** [comment]
the new notebook mode does this.
