### ISSUE TITLE
[0.35 blocker] `coalesce` function doesn't work correctly in the notebook

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#12073]
I'm either misunderstanding `coalesce` or it's broken. Here I'm using it to try and create a custom column called "Habits Column" and I'm expecting it to return for each row either the value of `Uses Drugs?`, `Diet`, `Drinks?`, or the string "No answer" if all the others are empty. 

The main oddity is that the resulting column is named "Uses Drugs?" instead of the expected "Habits Column". The second problem is that I'm still seeing empty cells in this new column, but I'm guessing that's because one of the columns (maybe the first one) actually contains whitespace instead of null, so it's technically not empty?

![image](https://user-images.githubusercontent.com/2223916/76014334-48732100-5ece-11ea-854f-ab5b3472a234.png)

**Comment by sbelak** [comment]
I've verified that coalesce works correctly wrt nulls, so I assume the blanks are actually empty strings. 

Have also verified the name being wrong. The response from the server contains the correct name though, so it seems to be a FE/display issue.

**Comment by tlrobinson** [comment]
@sbelak it looks like the column also contains a the `id` of the first argument to `coalesce`, which I don't think makes sense. I can fix it on the frontend but it probably makes sense to fix it in the backend too.
