### ISSUE TITLE
Bar charts show really skinny lines when the x-axis is a timeseries

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1208]
Ran a query on the Orders table: Created At = last month, Sum of Subtotal by Created At: Week. Expected to see the sum of subtotals for each of the 4 weeks in the last month. 

I correctly saw this in the table and line/area views:
![screen shot 2015-10-09 at 10 45 32 am](https://cloud.githubusercontent.com/assets/2223916/10401327/24be3eca-6e73-11e5-874f-55c9842ff895.png)

![screen shot 2015-10-09 at 10 44 50 am](https://cloud.githubusercontent.com/assets/2223916/10401330/2aa31c8e-6e73-11e5-90bf-fc1dc4651b93.png)

**But the bar chart only showed two of the weeks:** (I actually think it's rendering 3 — you can faintly see the first one abutting the y-axis — but you can't hover over it or really see it, making it useless)
![screen shot 2015-10-09 at 10 45 26 am](https://cloud.githubusercontent.com/assets/2223916/10401344/3e0eacb6-6e73-11e5-9734-624b273f68ca.png)

**Comment by tlrobinson** [comment]
This is partially resolved by #1394, but there's also an issue with the wrong granularity being used due to #1257
