### ISSUE TITLE
Larger fonts cause some bar charts to squish into a single column on the left

### ISSUE THREAD

**Issue by snblitz** [metabase/metabase#12081]
**Describe the bug**
Display a regular barchart.  Increase the font size via ctrl +.  In certain resolutions and font sizes the bar chart data squishes itself into a single bar on the left side of the image.

**Logs**

**To Reproduce**
Display a regular barchart.  Increase the font size via ctrl +.  In certain resolutions and font sizes the bar chart data squishes itself into a single bar on the left side of the image.

**Expected behavior**
Bar charts should scale normally and not become squished into a single column on the left.

**Screenshots**
(i removed the titles prior to upload)

before
![before-metabase](https://user-images.githubusercontent.com/4516175/76150606-31186d00-6061-11ea-8a9e-d5ff155f9487.png)
after a single ctrl +
![afterctrlplus-metabase](https://user-images.githubusercontent.com/4516175/76150614-35dd2100-6061-11ea-9bd9-ffc27904c357.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 74.0b9 (64-bit)
- Your operating system: Debian 10
- Your databases: 
- Metabase version: v0.34.0
- Metabase hosting environment: docker
- Metabase internal database: postgresql

**Severity**
Annoying -- work around available.

**Additional context**

**Comment by flamber** [comment]
Hi @snblitz 
I cannot reproduce your issue.
Can you try with the latest release 0.34.3 and with a non-beta version of Firefox?
Can you reproduce the issue with Sample Dataset?
Most browsers defaults to page zoom instead of text zoom. Are you only using text zoom?

**Comment by snblitz** [comment]
The person who originally reported this issue is running MacOS
(current) and Google Chrome 80.

I am able to duplicate the behavior using a stock google chrome
80.0.3987.106 (Official Build) (64-bit) with no plugins under Debian
10.  However, in this case, simply making the window smaller causes
the behavior to occur.

**Comment by snblitz** [comment]
I upgraded metabase to v0.34.3 and the issue no longer occurs in my two test cases.
