### ISSUE TITLE
Surface statistics about Pulse send status

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#12084]
**Is your feature request related to a problem? Please describe.**
For a variety of reasons (invalid email, the internet is down, etc), it is possible that Pulses may send to fail. Today, outside of perusing the logs, it is hard to identify this. We should provide more insight into Pulse status.

**Describe the solution you'd like**
For each pulse, I'd like to be able to track the success and/or failure of the Pulse channels. For example, if I have a Pulse scheduled to send to 3 emails, but one of those fails for some reason I'd like to know that there was a failure and ideally what the reason was.

**Describe alternatives you've considered**
Digging through logs - can be onerous in a large enviroment.

**Comment by sbelak** [comment]
We should probably do the same for cards. In large instanced card rot is a real annoyance.

**Comment by flamber** [comment]
Same for Alerts, but an alert behaves more or less the same way as a pulse

**Comment by ignacio-mb** [comment]
@qnkhuat is this going to be for 50? Should we put that milestone?
