### ISSUE TITLE
Sync Auto-query for limit 10000 concerns

### ISSUE THREAD

**Issue by Jacky1313** [metabase/metabase#12092]
Hi all,

This is our metabase auto-query to my postgres db, we try to adjust the limit #, is it possible to adjust and lower the limit count to 3 or 10? can i revise the source code at the backend of Metabase?

FYI

"-- Metabase SELECT "etlc1"."ml"."context" AS "context", "etlc1"."ml"."connection_from" AS "connection_from", 
" FROM "etlc1"."ml" LIMIT 10000"

limit 10000 down to limit 3

We've checked the following, and turned off the auto-query button.
"These are from our sync and analysis process. You can schedule/disable this as per https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis "

Cheers,

**Comment by flamber** [comment]
Hi @Jacky1313 
That looks like a regular query - not a analysis/scan, which gets 5000 distinct field values.
The current limits are hardcoded here:
https://github.com/metabase/metabase/blob/1befabcfb274031385b4c1e8b53035c82757078c/src/metabase/query_processor/middleware/constraints.clj#L5-L11
There's an issue open about making the value configurable - #4564 - upvote by clicking :+1:
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
