### ISSUE TITLE
Unable to save questions- "Sorry you do not have permission to see that"

### ISSUE THREAD

**Issue by aornugent** [metabase/metabase#12097]
**Describe the bug**
Similar to #10897 - I am unable to save queries after a version bump to 0.34.2, even as admin user.

@ralfeus @antoineverger1 describe the same problem. @flamber asked for a new issue.

**Logs**
[metabase.climatefriendly.com-1583886580316-server.log](https://github.com/metabase/metabase/files/4315426/metabase.climatefriendly.com-1583886580316-server.log)
[metabase.climatefriendly.com-1583886580316-console.log](https://github.com/metabase/metabase/files/4315427/metabase.climatefriendly.com-1583886580316-console.log)

**To Reproduce**
1. Go to an existing question
2. Add a filter
3. Save and replace question
4. Error message.

Alternative:
1. Create question using SQL editor
2. Save question
3. Error message

**Expected behavior**
Create and save questions as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/20387761/76370858-5b816780-638c-11ea-8bf6-4b0cf3b2e0c9.png)

**Severity**
Severe - blocking the creation and modification of questions on the day of launch 😰

**Additional context**
Only developed after bumping versions.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "5.0.0-1023-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-04",
      "tag": "v0.34.2",
      "branch": "release-0.34.x",
      "hash": "dab738c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @aornugent 

Which version did you upgrade from, where it worked?
Please upgrade to 0.34.3 - it fixes other errors with dashboard filters.

Are you using a reverse proxy, CDN or cache?
I'm asking, since the error in the browser console looks to be coming from Nginx, and that `403` request is not shown in the Metabase log, so it's not sending the request to the right place or being intercepted somewhere.

Have a look at the browser developer Network-tab, when saving a dashboard - it should tell you where the request is going, the parameters, and the response.

**Comment by aornugent** [comment]
Thanks @flamber!

I found this in the network diagnostics:

```
https://metabase.climatefriendly.com/api/card/21

PUT /api/card/21 HTTP/1.1
Host: metabase.climatefriendly.com
Connection: keep-alive
Content-Length: 2114
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Content-Type: application/json
Origin: https://metabase.climatefriendly.com
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: https://metabase.climatefriendly.com/question
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: metabase.SESSION=2c33c621-d624-4cd9-9bf5-5acd838f2689

HTTP/1.1 403 Forbidden
Server: Microsoft-Azure-Application-Gateway/v2
Date: Wed, 11 Mar 2020 20:26:29 GMT
Content-Type: text/html
Content-Length: 581
Connection: keep-alive

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

Which led us to a Azure Application Gateway setting that was blocking the request. 

This suggests that here's an OWASP 3.1 rule (or other implicit WAF constraint) that's being violated. Why this started now 🤷‍♂️
