### ISSUE TITLE
Feature Request: Cmd-enter to run query

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#1209]
Would be nice to be able to run queries while I'm refining queries using a keyboard shortcut

**Comment by tlrobinson** [comment]
This should be easy. Any preferences on the command? @michaelshobbs suggested command-enter, which seems reasonable.

**Comment by camsaul** [comment]
@tlrobinson I think @infomofo also wants Command-enter, or as we like to say `<s-return>`. It's in the title 😉

**Comment by diwu1989** [comment]
this will increase productivity by so much
![image](https://cloud.githubusercontent.com/assets/380950/19507124/aaf41ade-9585-11e6-9454-55e13193a960.png)
