### ISSUE TITLE
DataSelector multiple loading spinners

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#12105]
There's some visual wonkiness in the DataSelector when loading a database with a single schema. It's especially weird if the request to load schemas is fast.

Here's what happens:
1. Displays loading spinner while requesting schemas
2. Receives response with a single schema and auto-advance to display tables
3. Updates UI and immediately display a different spinner while loading tables

**Comment by flamber** [comment]
I cannot reproduce, but there has been a lot of changes to how this is handled in the past few versions.
