### ISSUE TITLE
Coloring of line chart etc. by discreptive values in field

### ISSUE THREAD

**Issue by fr4nk3nst3in** [metabase/metabase#12115]
**Is your feature request related to a problem? Please describe.**
Suppose we have data with following data:
- filed with discrete values
- date
- continuous values.

like this table:

|Category | Sales Date | Price|
| ------------- |-------------| -----|
|Cat1 | 2020-01-01 | 10.00|
|Cat1 | 2020-01-02 | 40.00|
|Cat2 | 2020-01-01 | 15.00|
|Cat3 | 2020-01-01 | 20.00|
|...|||

Now I want to build a line chart for this time series and color code lines by the category, which are discrete values in a defined filed. Each line should represent each discrete value e.g. Category from defined field.

**Describe the solution you'd like**

Here is a sample how it should look like.

<img width="1461" alt="Снимок экрана 2020-03-12 в 19 23 26" src="https://user-images.githubusercontent.com/4451184/76554951-0bdb9280-6497-11ea-980c-43448f450a11.png">

This is only a sample for a line chart. In consideration something like this for bar charts.

<img width="1466" alt="Снимок экрана 2020-03-12 в 19 26 57" src="https://user-images.githubusercontent.com/4451184/76555218-84daea00-6497-11ea-9ab7-b41602d2e9e2.png">

**Comment by flamber** [comment]
Hi @fr4nk3nst3in 
I think I might be misunderstanding what you're looking for, but from your screenshots, it's already possible. If you want dynamic color of the line/bar from the query, then it sounds like #6606.
![image](https://user-images.githubusercontent.com/1447303/76558354-7099eb80-649d-11ea-8526-c6e89fe7551c.png)
![image](https://user-images.githubusercontent.com/1447303/76558435-9c1cd600-649d-11ea-8cec-3ed7ec1e5e10.png)

**Comment by fr4nk3nst3in** [comment]
HI @flamber,

I see, this viz that I was looking for. I see it is a point of aggregation and not a point of formatting by colors. I was looking for this feature line options. I am close this ticket.
