### ISSUE TITLE
Write docs for env vars

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12110]
New vars from #12107
`MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE`
`MB_JDBC_DATA_WAREHOUSE_MAX_CONNECTION_POOL_SIZE`
`MB_ASYNC_QUERY_THREAD_POOL_SIZE`

and `MB_JETTY_MAXTHREADS`, which it seems has slipped by too.

This is a comprehensive list of ~124 (likely not complete/correct) - stolen from https://github.com/metabase/metabase/pull/11764#discussion_r369691430
`(grep -riEoh 'mb[_-][a-z_-]+' src ; grep -riEoh 'defsetting [a-z_-]+' src | awk '{ print "mb-" $2 }') | sed 's/-/_/g' | sort | awk '{print toupper($1)}' | uniq`

Related: #9495 `MAX_SESSION_AGE`

_If you're missing docs on an env var, then please comment :arrow_down:_

**Comment by ertugrulcetin** [comment]
@flamber added missing ENV vars. Related issue: https://github.com/metabase/metabase/pull/12145
