### ISSUE TITLE
[0.35 blocker] Can't scroll columns list when creating a filter in the notebook

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#12139]
This is on master. I can scroll the list of columns for the join, and aggregation and grouping actions just fine.

![filter-column-scroll](https://user-images.githubusercontent.com/2223916/76803520-42672500-6797-11ea-8e59-3a68d84a28bf.gif)

**Comment by kdoh** [comment]
Might be something to do with this? https://github.com/metabase/metabase/pull/12094/files#diff-e3106e9c352299749030bb04af770fb7R23
