### ISSUE TITLE
Downdrilling from dashboard on a pie segment with an empty value omits filter value

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#12134]
**Describe the bug**
WIth a pie chart on a dashboard, when I click on a pie segment representing an empty value and select to see the rows, the table view is opened, but the actual filter (`<Field> is ""`) is not applied.

**To Reproduce**
1. Create a pie chart on a column that has non-empty and empty values.
2. Save the chart and add it to a dashboard.
3. On the dashboard, click on the pie segment representing empty values and from the dropdown menu, select the option to view the actual rows.
4. Notice the table view is opened, but the filter `<Field> is ""` (or `<Field> is empty`) is not applied, and so all rows are shown instead of only the ones with the empty value.

**Expected behavior**
The filter should be applied, so as to only show the rows with the empty value.

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "Eclipse OpenJ9 VM",
    "java.vm.version": "openj9-0.18.0",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
Minor.

**Additional context**
The workaround for now is to first open the actual chart by clicking its title on the dashboard. It does work when used from within the question as opposed to the dashboard.

**Comment by flamber** [comment]
Hi @andreychirikba 
Unless I'm misunderstanding something, this looks like a duplicate of #11345 - correct?

**Comment by andreychirikba** [comment]
@flamber, agree, I'll close this one.
