### ISSUE TITLE
[0.35.0 blocker] UI doesn't work in non-English

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12147]
**Describe the bug**
When using non-English browser content language, the UI is a blank page.

**To Reproduce**
1. Change browser content language to i.e. French
2. Refresh browser - result: blank page
3. Browser console:
```
Error: Errors detected in definition of Lexer:
Token: ->Somme cumulée<- can never be matched.
Because it appears AFTER the Token Type ->Somme<-in the lexer's definition.
See https://sap.github.io/chevrotain/docs/guide/resolving_lexer_errors.html#UNREACHABLE
```

**Information about your Metabase Installation:**
`master`, snapshot, stats

**Comment by tlrobinson** [comment]
This is due to function/aggregation names in the expression syntax being i18n'd which is probably a bad idea. I guess we should just stick to the English names. I'll fix that.
