### ISSUE TITLE
The expression editor shouldn't start in error mode without any user input

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#12140]
**Describe the bug**
Right now when you try to create a custom expression or custom column once the editor opens it starts off in an error state even though you haven't entered any input yet. This makes me think I'm bad at expressions, when I really don't even know if I am yet. (I am).

**To Reproduce**
1. Go to the notbook
2. Select any data source and try and create a custom column or aggregation.
3. The expression editor input field will have a red border and an error message shows if you click out of it to hide the suggestion list.

**Expected behavior**
The expression editor should be in a non angry state to begin.

**Screenshots**
<img width="618" alt="Screen Shot 2020-03-16 at 3 30 46 PM" src="https://user-images.githubusercontent.com/5248953/76805364-d5a25980-679b-11ea-8ddd-a2e4cf82e1f4.png">

**Information about your Metabase Installation:**
```{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Mac OS X",
    "os.version": "10.15.3",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "tag": "v0.35.0-rc1",
      "hash": "37b3f82",
      "branch": "fix-12139",
      "date": "2020-03-16"
    },
    "settings": {
      "report-timezone": null
    }
  }
}```

**Comment by camsaul** [comment]
Fixed by #13724
