### ISSUE TITLE
H2 losing column type info for date_trunc results

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#12150]
The query `SELECT DATE_TRUNC('day', CREATED_AT) FROM ORDERS` fails against the test database on **H2**, on current `master` (37dfebf), with a `NullPointerException`.

The NPE is caused by [this call to `getColumnClassName`](https://github.com/metabase/metabase/blob/37dfebf0589f82da4aefafabaa5da1559b81fd68/src/metabase/driver/h2.clj#L300) returning `nil`.

The patch below handles the `nil` value, but the root problem persists: it appears that the result set metadata has no type information for this column.

```diff
diff --git a/src/metabase/driver/h2.clj b/src/metabase/driver/h2.clj
index 8ee61b68d..d980ff001 100644
--- a/src/metabase/driver/h2.clj
+++ b/src/metabase/driver/h2.clj
@@ -297,12 +297,13 @@
 ;; de-CLOB any CLOB values that come back
 (defmethod sql-jdbc.execute/read-column-thunk :h2
   [_ ^ResultSet rs ^ResultSetMetaData rsmeta ^Integer i]
-  (let [classname (Class/forName (.getColumnClassName rsmeta i) true (classloader/the-classloader))]
-    (if (isa? classname Clob)
+  (if (some-> (.getColumnClassName rsmeta i)
+              (Class/forName true (classloader/the-classloader))
+              (isa? Clob))
     (fn []
       (jdbc-protocols/clob->str (.getObject rs i)))
     (fn []
-        (.getObject rs i)))))
+      (.getObject rs i))))
 
 (defmethod sql-jdbc.execute/set-parameter [:h2 OffsetTime]
   [driver prepared-statement i t]
```

The result is that the column has a base type of `types/*` in the API response, and the row values are interpreted as strings instead of timestamps.

_This is a **regression** from 0.34.3._

## Scope
This bug does _not_ manifest for the same query without the `DATE_TRUNC` function call. The same query also works as expected on PostgreSQL.

I did not test other H2 functions for similar issues.

## Preliminary debugging
Here are some concrete values from `rsmeta` that I found during debugging:

* `(.getObject rs i)`: `#inst "2019-02-11T00:00:00.000000000-00:00"` (type `java.sql.Timestamp`)
* `(.getColumnName rsmeta i)`: `"DATE_TRUNC('day', CREATED_AT)"`
* `(.getColumnType rsmeta i)`: `0`
* `(.getColumnTypeName rsmeta i)`: `"NULL"`

The affected `sql-jdbc.execute/read-column-hunk` method seems to be part of the new async query processor for 0.35.0, but I couldn't find any obvious reason why the result metadata would be affected in this way.

I found this issue while trying to reproduce #9802.

**Comment by sbelak** [comment]
This might be related (at least spiritually) to #11358 (which I haven’t managed to come to the bottom of)
