### ISSUE TITLE
Allow setting the number of decimal places for Pie Chart percentages

### ISSUE THREAD

**Issue by asaf050** [metabase/metabase#12152]
**Is your feature request related to a problem? Please describe.**
I want to be able to set the number of decimal places that displayed in the pie chart widgets.

**Describe the solution you'd like**
Add input box of number of decimal places, let the user decide if he wants 3 , 2 , 1 or 0

![image](https://user-images.githubusercontent.com/7129342/76952145-5769c280-6915-11ea-8dd0-a330bcdd7d56.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @asaf050 
That's already possible. Though the percentages are calculated automatically, so it will find the maximum number of decimals needed to show. Is it the percentages you want to control?
This is how it looks in 0.34.3:
![image](https://user-images.githubusercontent.com/1447303/76953062-58e3bc80-690e-11ea-93e0-fc812bc96aca.png)

**Comment by asaf050** [comment]
Hi
Thanks for the fast reply!

Yes, I want to change the percentage.

**Comment by jlcornejo** [comment]
I have the same problem, users have sent me these cases.
But I don't have how to correct it, since the number of decimal places cannot be configured in the display
Is this still ongoing?

![image](https://user-images.githubusercontent.com/16454892/206283153-9d3dff83-a99f-4e46-8621-d8cfa5e58cf7.png)

If I filter another country, change the number of decimal places

![image](https://user-images.githubusercontent.com/16454892/206283300-dd5c49ed-1c51-43b6-97b8-857fbf0a1715.png)

**Comment by kayumuzzaman** [comment]
any update regarding this feature?

**Comment by mkoppanen** [comment]
update?

**Comment by ojjj13** [comment]
Hi team, I want to bring this issue up since it should be a fairly easy implementation. Current version sometimes show 5-6 decimal places which is really not elegant on a card view.

**Comment by jfrickecampact** [comment]
Is this still an unresolved issue? I find multiple threads on this but no solution. 
![Bildschirmfoto 2024-04-05 um 10 04 28](https://github.com/metabase/metabase/assets/79312710/2f18cd39-b17d-4daa-b490-d53067c787b4)

**Comment by paoliniluis** [comment]
@jfrickecampact @jlcornejo @ojjj13 what's the version that you're running?

**Comment by jfrickecampact** [comment]
> @jfrickecampact @jlcornejo @ojjj13 what's the version that you're running?

v0.48.3

**Comment by paoliniluis** [comment]
Reading the code it seems that we should truncate the decimals to 2 or 3 characters, so this is probably a bug (and a feature request as well as the user wants to control the decimal places

**Comment by StevenWaltman** [comment]
On our dashboards is does limit the amount of decimals to 2 or 3 characters for the percentages. 
It appears to do so in all the examples in this issue. 
No bug there I would say.

I am curious to why 3 decimals seems needed in the first place? 
1 decimal would be enough in my opinion.

Version: 1.47.10

**Comment by ojjj13** [comment]
On my end it sometimes show 5-6 decimal places depends on the data.在 2024年4月5日，19:02，Steven Waltman ***@***.***> 写道：﻿
On our dashboards is does limit the amount of decimals to 2 or 3 characters for the percentages.
It appears to do so in all the examples in this issue.
No bug there I would say.
I am curious to why 3 decimals seems needed in the first place?
1 decimal would be enough in my opinion.
Version: 1.47.10

**Comment by Phorta** [comment]
![graficos porcetagem](https://github.com/metabase/metabase/assets/30396674/a755f22d-8f5f-45e6-b40b-4c58558e2737)

I'm using Metabase 0.49.6. In the pie charts I see that Metabase, when presenting the percentage in the legend, presents it in two different ways, which makes it complicated for the user.
Does anyone know why? or how do I make it show the normal percentage like 12.50%?

**Comment by vektor330** [comment]
Can you please clarify which Metabase release version contains the fix from #46397 ? We are currently running 1.50.25, we don't seem to have the new option available in the chart Visualization options, and the number of decimal places is through the roof:
<img width="1426" alt="Screenshot 2024-09-18 at 9 57 16" src="https://github.com/user-attachments/assets/f4eefb4d-076c-44de-aec4-4e1e5a080108">

Thanks in advance!

**Comment by lobindam** [comment]
I am runing  Metabase 0.50.25 which is the latest, I  have the same issue:  Thanks in advase for any help !!!!!! 
![Captura de pantalla 2024-09-18 170424](https://github.com/user-attachments/assets/14ea93c2-0c1d-4d63-9de0-a1e4fef79cf7)

**Comment by EmmadUsmani** [comment]
Hi @vektor330 @lobindam, since this is a new feature, it will be included in the next major release (v51). The first release candidate for v51 is expected to be released sometime in the next few weeks.
