### ISSUE TITLE
Using a long "field formula" in Custom Column/Expression freezes browser

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12154]
**Describe the bug**
Using the new functions like `concat`/`coalesce`/`contains` can become almost impossible, when strings become more than ~30 characters, because the browser becomes unresponsive.

**Logs**
Nothing, but browser will ask to stop slow-running-script.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2.
    - Add Custom Column and try writing `concat('this is a test of a long string with an ID: ', [ID])` - it should become unresponsive around the word "string".
    - Add Filter > Custom Expression and try writing `contains([Product → Title], 'this is a test of a long string')`

**Information about your Metabase Installation:**
1.35.0-snapshot and stats on Firefox and Chromium.

**Comment by flamber** [comment]
Upping priority, since the only workaround I can find is to write the formula in external program and copying it in without doing any modifications in Metabase.

**Comment by tlrobinson** [comment]
This is due to a bug in the expression lexer, or underlying Chevrotain parser/lexer library, I'm not sure which. I've posted an issue here https://github.com/SAP/chevrotain/issues/1151
