### ISSUE TITLE
Missing headers in table results

### ISSUE THREAD

**Issue by nautilus28** [metabase/metabase#12165]
**Describe the bug**
Missing headers in table results, only happens when we refresh the page

**Logs**

<img width="513" alt="Screenshot 2020-03-20 at 12 56 50" src="https://user-images.githubusercontent.com/4472857/77165468-4605ef00-6aaa-11ea-9698-34bef7a84b13.png">

**Screenshots**

<img width="1145" alt="Screenshot 2020-03-20 at 12 55 18" src="https://user-images.githubusercontent.com/4472857/77165402-1a830480-6aaa-11ea-92b6-47a59eb83c5f.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.9.0-7-amd64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "exasol",
      "bigquery",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-03-16",
      "tag": "v0.35.0-rc1",
      "branch": "master",
      "hash": "022d0ca"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Comment by flamber** [comment]
Hi @nautilus28 
I cannot reproduce on `master` commit `943e667` (2020-03-18).
It looks like this is a Native/SQL question - correct?
Can you reproduce this with Sample Dataset?

**Comment by nautilus28** [comment]
@flamber I couldn't reproduce it with Sample Dataset. The issue only appears when you load question from cache result. What I noticed is that the cached response doesn't have field_ref in the json response.

original response: 
<img width="300" alt="Screenshot 2020-03-22 at 03 38 38" src="https://user-images.githubusercontent.com/4472857/77241770-f7ae3880-6bee-11ea-9359-194e9178fa3d.png">

cached response:
<img width="256" alt="Screenshot 2020-03-22 at 03 38 19" src="https://user-images.githubusercontent.com/4472857/77241776-0268cd80-6bef-11ea-9ed2-7a1992a07ece.png">

**Comment by flamber** [comment]
Excellent info @nautilus28 
Reproduced on MariaDB and Postgres by adding a sleep and enabling cache. I don't need to refresh the browser, it just needs to get the data from cache instead of directly. I haven't tested if the same is true for non-Native questions.
![image](https://user-images.githubusercontent.com/1447303/77247263-99ee1080-6c2f-11ea-80da-4da277af9376.png)
![image](https://user-images.githubusercontent.com/1447303/77247287-dcafe880-6c2f-11ea-86f0-d6f15e366db0.png)

**Comment by nautilus28** [comment]
We would highly appreciate if someone could have a look at this issue. Thanks.

**Comment by flamber** [comment]
@nautilus28 It's on the board of things to try to wrap-up before 0.35.0, since it's a regression.
