### ISSUE TITLE
Improve chart value labels styling

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#12160]
![image](https://user-images.githubusercontent.com/691495/77110369-df29fc80-69fb-11ea-8025-b8fa94d69e36.png)

Some issues:
- Color doesn't match other labels.
- Font size doesn't work for small charts.
- Do we need to display all those zeros?

**Comment by mazameli** [comment]
I'll see if I can mock something better up before your day starts tomorrow.

**Comment by mazameli** [comment]
So here are two different, but very similar possibilities for dashboard cards.

In both mocks:
- Chart titles are 14px
- All other labels are 12px
- The chart title and bottom x-axis label ("Date") are text-dark

The top version has all the axis tick marks and bar value labels set to text-medium. The bottom version's bar value labels are text-dark.

I lean towards the second option: I think the bar values should have a slightly higher hierarchy over the axis tick marks.

![image](https://user-images.githubusercontent.com/2223916/77191496-49907a80-6a98-11ea-8611-9e03f16afcb5.png)

I think that we can keep the query builder detail view essentially unchanged — all I've done is made the x- and y-axis labels ("Count" and "Created At") 14px and text-dark with a font weight of 800, and made the bar value labels match that exactly.

![image](https://user-images.githubusercontent.com/2223916/77195689-4482f980-6a9f-11ea-982c-0f7f98c780ba.png)

![image](https://user-images.githubusercontent.com/2223916/77195717-4e0c6180-6a9f-11ea-8b84-903ba122ac81.png)
