### ISSUE TITLE
Multiply by a number - does not accept decimal

### ISSUE THREAD

**Issue by litegirl32** [metabase/metabase#12166]
Multiply by a number does not allow any decimal number.  

1. Open Data Settings for a column
2. Scroll down to Multiply by a number
3. Type in 
       .    - this works, 0 is displayed
       0   - (or any number at all) causes the decimal to be removed 
.......rendering the inability to show 75000 as 75 

Per the Metabase documentation, supposed to be able to multiply by .01 (or any decimal)

**Comment by flamber** [comment]
Hi @litegirl32 
I cannot reproduce 0.34.3, but you're not giving any information about your system like we ask for, when opening an issue.
![image](https://user-images.githubusercontent.com/1447303/77185039-fb4b9d80-6ad0-11ea-8efc-c54b839e7cf4.png)

**Comment by litegirl32** [comment]
WOW!  Your screenshot pointed out my problem, one *must* type the leading zero. I'm so sorry for the silly question! Thank you so much!!
