### ISSUE TITLE
Update stable version to 0.34.3

### ISSUE THREAD

**Issue by iglv** [metabase/metabase#12162]
**Is your feature request related to a problem? Please describe.**
Charts not works on dashboard on stable version on docker:
![image](https://user-images.githubusercontent.com/1250680/77140747-7e89d680-6a72-11ea-9ce2-e27f75dba7ba.png)

**Describe the solution you'd like**
Update stable to v0.34.3

**Comment by flamber** [comment]
Hi @iglv 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
