### ISSUE TITLE
Can't create new pulse

### ISSUE THREAD

**Issue by nautilus28** [metabase/metabase#12174]
**Describe the bug**
We have upgraded from version 0.31.2 to 0.35.0-rc1. After that, we can't create pulse anymore. The `Send to slack now` button is always grey.

**Screenshots**

<img width="590" alt="Screenshot 2020-03-23 at 11 11 36" src="https://user-images.githubusercontent.com/4472857/77310978-2a435880-6cf7-11ea-9115-ac3ae6991d92.png">

**Information about your Metabase Installation:**

{
"browser-info": {
"language": "en-GB",
"platform": "MacIntel",
"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
"vendor": "Google Inc."
},
"system-info": {
"java.runtime.name": "OpenJDK Runtime Environment",
"java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
"java.vendor": "Debian",
"java.vendor.url": "https://tracker.debian.org/openjdk-11",
"java.version": "11.0.6",
"java.vm.name": "OpenJDK 64-Bit Server VM",
"java.vm.version": "11.0.6+10-post-Debian-1bpo91",
"os.name": "Linux",
"os.version": "4.9.0-7-amd64",
"user.language": "en",
"user.timezone": "UTC"
},
"metabase-info": {
"databases": [
"postgres",
"exasol",
"bigquery",
"h2"
],
"hosting-env": "unknown",
"application-database": "postgres",
"application-database-details": {
"database": {
"name": "PostgreSQL",
"version": "9.6.16"
},
"jdbc-driver": {
"name": "PostgreSQL JDBC Driver",
"version": "42.2.8"
}
},
"run-mode": "prod",
"version": {
"date": "2020-03-16",
"tag": "v0.35.0-rc1",
"branch": "master",
"hash": "022d0ca"
},
"settings": {
"report-timezone": "UTC"
}
}
}

**Comment by flamber** [comment]
Reproduced on `master` (commit `4aa8368` 2020-03-20). The Slack pulses are still working if saved, but the "send now" button is always disabled. The email pulses has a working "send now" button.

**Comment by nautilus28** [comment]
@flamber thanks for looking into the issue.

Moreover, the configured channel is not persisted into the database.

**Comment by flamber** [comment]
> Moreover, the configured channel is not persisted into the database.

That is much more critical - actually blocking the release.

**Comment by nautilus28** [comment]
@paulrosenzweig Thanks for the PR. However, I have just tested it, it doesn't seem to fix the isssue.
