### ISSUE TITLE
Funnel data value labels not visible in question visualization

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12175]
**Describe the bug**
When having a short funnel (eg. 3 rows), the funnel is oversized and cannot view data value labels.

**To Reproduce**
1. Create a Native question and change visualization to Funnel.
```
SELECT 'Registered' AS Step, 31159 AS Count UNION ALL 
SELECT 'Info_first' AS Step, 28372 AS Count UNION ALL 
SELECT 'Info_second' AS Step, 21494 AS Count
```
2. Will look like this (Zooming out to 80% in the browsers seems to show the labels for this specific example):
![image](https://user-images.githubusercontent.com/1447303/77316627-0b9a8d00-6d0a-11ea-8b45-e35f0bcd788a.png)

**Information about your Metabase Installation:**
Metabase `master` (0.35-RC), 0.33.6 - various browsers and backends.

**Additional context**
Related to #12042

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by saeedesmaili** [comment]
You also can't display a funnel chart in a dashboard properly, regardless of how many steps your funnel has or how much you stretch it from bottom:
![screenshot-hekmat divar ir-2020 03 24-21_41_10](https://user-images.githubusercontent.com/13351748/77456497-ecd6ec00-6e18-11ea-893a-86aad34d3cee.png)

**Comment by flamber** [comment]
@saeedesmaili That's covered by #12042.
