### ISSUE TITLE
Add some docs for scaling Metabase

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#12177]
A common question customers have is "how many users can Metabase support?" or "what configuration do I need to support N number of concurrent users". 

We should add some documentation to at least give a high level over for these scenarios. For example:

Metabase scales to several hundred users and thousands of questions with a single server deployment. When scaling Metabase, there are several components to keep in mind: The HTTP server (Jetty), the application database, and the data warehouse. Each of these components can be scaled or configured individually and should tracked as Metabase usage increases.

[MB_JETTY_PORT](https://www.metabase.com/docs/latest/operations-guide/customizing-jetty-webserver.html)
[`c3p0.maxPoolSize`](https://github.com/metabase/metabase/issues/2172)
[App DB/Data Warehouse DB pool sizes](https://github.com/metabase/metabase/pull/12107)

Metabase can also be run in a clustered environment. Session state is stored in the database so you can easily run Metabase behind a load balancer. While sticky sessions are not required, many folks enable them for consistency and ease of debugging.

Related performance improvements:
https://github.com/metabase/metabase/issues/11856

**Comment by jeff-bruemmer** [comment]
We've added an article on Learn: [Metabase at scale](https://www.metabase.com/learn/data-diet/analytics/metabase-at-scale.html).

**Comment by paoliniluis** [comment]
Do you think we can close this one @jeff-bruemmer or we wait till we add a few more docs (load balancing?)

**Comment by jeff-bruemmer** [comment]
Closing it, as the Learn article covers this territory. If we need to add additional docs, we should create specific issues for those docs.
