### ISSUE TITLE
Old date format.

### ISSUE THREAD

**Issue by Gu3** [metabase/metabase#12173]
Hi everyone !
I hope someone can help me with this :
I've got one Date field, if this one is older than 1911-03-12 the result inside Metabase will be : 1911-03-11T00:00:00+00:09:21
Start to 1911-03-12 the format will be correct : 12 mars, 1911
I think is a conf issue because I don't have this problem on local : only on production.
Production and Local installation are on Docker.
Any clues ?
Thanks !
Vince.

**Comment by flamber** [comment]
Hi @Gu3 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And include "Diagnostic Info" from Admin > Troubleshooting of both systems.

**Comment by Gu3** [comment]
Ok, thanks you but the problem is solve. 
If someone had this issues, check your user.timezone : need to be "GMT".
