### ISSUE TITLE
Embeded Dashboard Error on some browsers

### ISSUE THREAD

**Issue by nicokras** [metabase/metabase#12192]
Hi

I Have  a strange problem. We have correctly embedded some dashboards in an IFRAME in our web app with some blocked parameters and some visible ones.

The thing is dashboard loads ok in a big quantity of machines and browsers, but we have some ones (mainly in Chrome Mac but we have also seen it in one Chrome Windows), that it tries to load, but after a few seconds it says "An error has ocurred", and no data is displayed. 

![metabase](https://user-images.githubusercontent.com/14184357/77559963-9068e080-6e9b-11ea-8971-32622bb44b30.png)

Do you have any idea of what could be happening? We are currently on 0.33.6

Thanks

**Comment by flamber** [comment]
Hi @nicokras 
Please test with the latest release - currently 0.34.3
Check the log for more details about the error - Admin > Troubleshooting > Logs.
Also see your browser developer console for any errors.

**Comment by flamber** [comment]
Continue here: https://discourse.metabase.com/t/embeded-dashboard-error-on-some-browsers/9484
