### ISSUE TITLE
"A group with that name already exists." error when editing permissions or users

### ISSUE THREAD

**Issue by GitBronch** [metabase/metabase#12196]
**Bug description**
**"A group with that name already exists."** error when:
   - Adding, editing or deleting a user or a group
   - Assigning permissions to a user

Previously we couldn't even access "Permissions" or "People" menus but after trying to access via API this got unblocked. We believe that this could be somehow related with a db update some weeks ago but it can be just a coincidence.

**Logs**
[0f2faf9f-d2c2-46f9-ab91-5ea7e2b6d2eb] 2020-03-26T08:30:43+01:00 DEBUG metabase.middleware.log POST /api/permissions/membership 400 2.4 ms (2 DB calls)
"A group with that name already exists."

**Metabase installation details:**
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "IcedTea",
    "java.vendor.url": "https://icedtea.classpath.org",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "5.5.2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.12-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.3",
      "date": "2020-02-25",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Critical

**Comment by flamber** [comment]
Hi @GitBronch 
Which version were you using before, when you couldn't even access People/Permission menus?
Have you ever manually edited the Metabase application database?
You might need to check all your group names in the table `permissions_group` - maybe you can spot why it's failing.
Also, if you can revert to a backup, where it used to work, and compare with the current data, that would help in figuring out how to fix this.
Reference:
https://github.com/metabase/metabase/blob/f8e72fd6df0f9e51807740f77313c616336b1d61/src/metabase/models/permissions_group.clj#L58-L61

**Comment by GitBronch** [comment]
**Update**: The error "This group already exists" also shows when trying to create a new collection. The collection is created though.

Hi Flamber,

I didn't change the version. We didn't need to add permissions or users for some weeks. Everything seemed to work correctly. At some point we tried to access permissions and groups and both failed (it only showed a loading page). Trying to find out which was the undergoing problem we accessed using the api endpoints. We didn't make any changes, but just this seemed to unblock those loading pages. From that moment we were able to access those parts of the admin menu that didn't show before.
Despite that we still cannot modify the permissions or groups. The only way of doing it manually editing the db. Before this issue we never needed to make manual changes on metabase's database.

We checked the tables with permissions and everything seems correct.

**Comment by flamber** [comment]
@GitBronch 
By any chance, could it be because of two groups with the same name, but different case?
It's really strange that this suddenly started to be a problem, but any extra information you can give, which can help figuring out why it start failing would be helpful.
I can see there's a "TODO" on the migration changeset because of missing case-insensitivity:
https://github.com/metabase/metabase/blob/be2bbfa8845cca5b7bade06b81fe874c1d61edbc/resources/migrations/000_migrations.yaml#L2925-L2956

**Comment by GitBronch** [comment]
Hi Flamber,

We found the cause and the solution. The cause was quite weird and still now we don't really understand how that happened. It seems a db issue.

When accessing the table with a SQL client (non-cli) the table showed **only 1 record** for group id 3 (Metabot) so everything seemed right. We tried to make a copy of the table and it threw a duplicate alert for that group. That was strange because there was only one that we could see. 

So we shutted down Metabase and we deleted all the occurrences of that user. **We verified there was not any user id 3 anymore**. Then we inserted it again (obviously only 1 record). After this surprisingly there were **2 records (!) under the same id and name again**. We eventually decided to drop the fk from other tables, rebuild the table and restore the fk from scratch to discard any db's data corruption.

This fixed the issue, we don't get the error message anymore and everything seems to work correctly. I hope it can help if someone finds the same issue.

**Comment by camsaul** [comment]
@GitBronch glad that resolved your issue, going to go ahead and close this as solved. I think if your application DB gets in a state where it's not enforcing primary key constraints and you have duplicate rows with the same primary key/`id`, it's something that we'd consider to be an issue with your deployment of the application DB and not Metabase code in particular
