### ISSUE TITLE
Setting up logs to output to a file with Docker

### ISSUE THREAD

**Issue by ManuHeel** [metabase/metabase#12190]
Hi,

I'm using Docker (with docker-compose) to start up a Metabase instance with an additionnal database.

My issue is that I can't find a way to output Metabase's logs to a file when using it in Docker.
I've seen a way to pass a log4j configuration file and thus manage other logging config (log level, etc) here : https://github.com/metabase/metabase/issues/8158
However the "-Dlogfile.path=target/log" Java option that gets automatically added to Metabase's JAR execution seems to overwrite everything I add to the JAVA_OPTS environment variable as it's added after the custom configuration file I use.
I can't understand where this **target/log** might be.

Do you have some help on this subject ?
Thanks.

**Comment by sairam** [comment]
@ManuHeel , when using any app with docker, logs go to stdout. this is required as a best practice so that the docker image that is running does not become large. You should use solutions like logspout to push the logs to a central repo. 

you can usually use `docker logs -f $container_name`

**Comment by ManuHeel** [comment]
@sairam Thank you for your response.
I understand the logspout pushes the log to a repo, however I need my logs to stay as files inside of my host, as my final objective is to parse them with fail2ban to improve security on my server.

**Comment by sairam** [comment]
@ManuHeel , see https://stackoverflow.com/questions/41144589/how-to-redirect-docker-container-logs-to-a-single-file

**Comment by sairam** [comment]
When I setup for a client, I used nginx on top of metabase to restrict access to the specific users of the domain which would avoid hitting the metabase application itself.

**Comment by flamber** [comment]
@ManuHeel Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
@sairam Thanks for helping out on this :+1:
