### ISSUE TITLE
Sample Dataset data doesn't add up

### ISSUE THREAD

**Issue by amgsmith** [metabase/metabase#12203]
The data on the Orders table for Metabase's dummy data does not seem to add up in many cases - ie Subtotal +Tax - Discount does not equal the Total amount in the majority of cases.
![Screenshot_2020-03-27 Question · Metabase](https://user-images.githubusercontent.com/56402008/77783953-a3bdac80-7051-11ea-8c60-dcabff2b86dc.png)

**Comment by camsaul** [comment]
Fixed by #14513
