### ISSUE TITLE
How to debug stuck instance.

### ISSUE THREAD

**Issue by ashoksahoo** [metabase/metabase#12216]
One of our instances is not able to perform SQL queries, but there are no errors as such. 
It just has too many queries in flight and its increasing over time.
Also, we do not see any query originating from this instance to our redshift cluster.
Also, our load balancer sees this instance as healthy and does not take it down.

`03-31 08:04:12 DEBUG middleware.log :: POST /api/dataset 200 [ASYNC: canceled] 10.0 mins (4 DB calls) Jetty threads: 5/50 (3 idle, 0 queued) (137 total active threads) Queries in flight: 18792`

Is there any way to get alerts on Queries in flight, is there any way to drop this instance from LB by failing a health check.
Anything JMX monitoring can help. 
Is there any internal metrics which can be send to prometheus/datadog/sensu/cloudwatch alarms can be added on top of that.

**Comment by flamber** [comment]
Hi @ashoksahoo 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And include "Diagnostic Info" from Admin > Troubleshooting too.
There's a massive change in how connections are handled in 0.35.0, so you might want to try it:
https://github.com/metabase/metabase/releases/tag/v0.35.0
