### ISSUE TITLE
Binning doesn't create bins on continuous value

### ISSUE THREAD

**Issue by ralfeus** [metabase/metabase#12210]
**Describe the bug**
I have a table with a decimal column Price ranging its values from 1 to 180000. I want to create a histogram and so I specify binning on that column. 
If I choose auto-binning it creates only one bin: 0-750000 although there is no such value as 750000
If I choose 10 bins it creates only one bin: 0-500000
If I choose 50 bins it creates 2 bins: 0-100000 and 100000-200000
If I choose 100 bins it creates 4 bins: 0-50000, 50000-100000, 100000-150000 and 150000-200000

**Logs**
<details>

> 03-30 05:51:08 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 36.9 ms (14 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (76 total active threads) Queries in flight: 0
> 03-30 05:51:14 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 36.8 ms (14 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (76 total active threads) Queries in flight: 0
> 03-30 05:51:16 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 36.7 ms (14 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (76 total active threads) Queries in flight: 0
> 03-30 05:51:18 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 35.6 ms (14 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (76 total active threads) Queries in flight: 0
> 03-30 05:51:20 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 46.7 ms (15 DB calls) Jetty threads: 3/50 (3 idle, 0 queued) (76 total active threads) Queries in flight: 0

</details>

Javascript logs:
<details>

> GEThttps://www.google-analytics.com/r/collect?v=1&_v=j81&a=1277936015&t=pageview&_s=202&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&_u=SACAAMABAAAAAC~&jid=465044875&gjid=1016284489&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&_r=1&cd1=v0.34.3&z=568641710
> [HTTP/2 200 OK 30ms]
> 
> XHRPOSThttp://sandlet:3000/api/dataset
> [HTTP/1.1 202 Accepted 50ms]
> 
> onMessage extension extension.js:24:25
> Clean the cache of the scraper (new onComplete event) ial.js:425:21
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=event&_s=203&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&ec=QueryBuilder&ea=Run%20Query&el=query&ev=180&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=2069862305
> [HTTP/2 200 OK 20ms]
> 
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=pageview&_s=204&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=216037938
> [HTTP/2 200 OK 30ms]
> 
> XHRPOSThttp://sandlet:3000/api/dataset
> [HTTP/1.1 202 Accepted 40ms]
> 
> onMessage extension extension.js:24:25
> Clean the cache of the scraper (new onComplete event) ial.js:425:21
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=event&_s=205&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&ec=QueryBuilder&ea=Run%20Query&el=query&ev=135&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=262511457
> [HTTP/2 200 OK 18ms]
> 
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=pageview&_s=206&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=290988317
> [HTTP/2 200 OK 18ms]
> 
> XHRPOSThttp://sandlet:3000/api/dataset
> [HTTP/1.1 202 Accepted 51ms]
> 
> onMessage extension extension.js:24:25
> Clean the cache of the scraper (new onComplete event) ial.js:425:21
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=event&_s=207&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&ec=QueryBuilder&ea=Run%20Query&el=query&ev=129&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=1674392587
> [HTTP/2 200 OK 20ms]
> 
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=pageview&_s=208&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=583685260
> [HTTP/2 200 OK 20ms]
> 
> XHRPOSThttp://sandlet:3000/api/dataset
> [HTTP/1.1 202 Accepted 61ms]
> 
> onMessage extension extension.js:24:25
> Clean the cache of the scraper (new onComplete event) ial.js:425:21
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=event&_s=209&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&ec=QueryBuilder&ea=Run%20Query&el=query&ev=98&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=450727142
> [HTTP/2 200 OK 21ms]
> 
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=pageview&_s=210&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=1496007259
> [HTTP/2 200 OK 20ms]
> 
> XHRPOSThttp://sandlet:3000/api/dataset
> [HTTP/1.1 202 Accepted 70ms]
> 
> onMessage extension extension.js:24:25
> Clean the cache of the scraper (new onComplete event) ial.js:425:21
> GEThttps://www.google-analytics.com/collect?v=1&_v=j81&a=1277936015&t=event&_s=211&dl=http%3A%2F%2Fsandlet%2Fquestion&dp=%2Fquestion&ul=cs&de=UTF-8&dt=Question%20%C2%B7%20Metabase&sd=24-bit&sr=1280x720&vp=1217x647&je=0&ec=QueryBuilder&ea=Run%20Query&el=query&ev=125&_u=SACAAMABAAAAAC~&jid=&gjid=&cid=913327246.1583759758&tid=UA-60817802-1&_gid=134159126.1585312402&cd1=v0.34.3&z=812916045
> [HTTP/2 200 OK 18ms]
> 
> Error in parsing value for ‘contain’.  Declaration dropped. sandlet:3000:1:1710
> Elements matching selector: .ace_content
> NodeList []
> ​
> length: 0
> ​
> <prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
> Error in parsing value for ‘contain’.  Declaration dropped. sandlet:3000:1:2230
> Error in parsing value for ‘contain’.  Declaration dropped. sandlet:3000:1:6403
> Error in parsing value for ‘contain’.  Declaration dropped. sandlet:3000:1:6527
> Error in parsing value for ‘contain’.  Declaration dropped. sandlet:3000:1:6619
> GEThttp://sandlet:3000/app/dist/vendor.bundle.css?94b86072a8b0384f6b02e56ef9d0f4e3
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttp://sandlet:3000/app/dist/styles.bundle.css?b6da62ba19505f3fadab15fc78a81116
> [HTTP/1.1 200 OK 0ms]
> 
> GEThttp://sandlet:3000/app/dist/app-main.bundle.css?556efddd9ab48ef53ebc0d9e2f447177
> [HTTP/1.1 200 OK 0ms]
> 
> Error in parsing value for ‘image-rendering’.  Declaration dropped. vendor.bundle.css:136:19
> Unknown property ‘behavior’.  Declaration dropped. vendor.bundle.css:233:11
> Unknown property ‘zoom’.  Declaration dropped. vendor.bundle.css:699:7
> Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. vendor.bundle.css:707:10
> Keyframe rule ignored due to bad selector. styles.bundle.css:177:43
> Keyframe rule ignored due to bad selector. styles.bundle.css:178:43
> Keyframe rule ignored due to bad selector. styles.bundle.css:187:43
> Keyframe rule ignored due to bad selector. styles.bundle.css:188:43
> Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. styles.bundle.css:303:27
> Expected declaration but found ‘*’.  Skipped to next declaration. styles.bundle.css:517:3
> Unexpected token ‘h’ in media list. styles.bundle.css:1572:37
> Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. styles.bundle.css:1618:8
> Ruleset ignored due to bad selector. styles.bundle.css:1882:39
> Ruleset ignored due to bad selector. styles.bundle.css:1886:39
> Ruleset ignored due to bad selector. styles.bundle.css:1895:53
> Error in parsing value for ‘overflow’.  Declaration dropped. styles.bundle.css:1903:13
> Error in parsing value for ‘overflow’.  Declaration dropped. styles.bundle.css:1911:13
> Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. styles.bundle.css:3780:2
> Keyframe rule ignored due to bad selector. styles.bundle.css:5089:41
> Keyframe rule ignored due to bad selector. styles.bundle.css:5090:41
> Keyframe rule ignored due to bad selector. styles.bundle.css:5102:41
> Keyframe rule ignored due to bad selector. styles.bundle.css:5103:41
> Expected ‘none’, URL, or filter function but found ‘fliph’.  Error in parsing value for ‘-webkit-filter’.  Declaration dropped. styles.bundle.css:5215:19
> Expected ‘none’, URL, or filter function but found ‘fliph’.  Error in parsing value for ‘filter’.  Declaration dropped. styles.bundle.css:5216:19
> Error in parsing value for ‘right’.  Declaration dropped. styles.bundle.css:5853:10
> Keyframe rule ignored due to bad selector. app-main.bundle.css:1434:43
> Keyframe rule ignored due to bad selector. app-main.bundle.css:1435:43
> Keyframe rule ignored due to bad selector. app-main.bundle.css:1444:43
> Keyframe rule ignored due to bad selector. app-main.bundle.css:1445:43
> Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. app-main.bundle.css:1560:27
> Expected declaration but found ‘*’.  Skipped to next declaration. app-main.bundle.css:1774:3
> Unexpected token ‘h’ in media list. app-main.bundle.css:2829:37
> Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. app-main.bundle.css:2875:8
> Ruleset ignored due to bad selector. app-main.bundle.css:3139:39
> Ruleset ignored due to bad selector. app-main.bundle.css:3143:39
> Ruleset ignored due to bad selector. app-main.bundle.css:3152:53
> Error in parsing value for ‘overflow’.  Declaration dropped. app-main.bundle.css:3160:13
> Error in parsing value for ‘overflow’.  Declaration dropped. app-main.bundle.css:3168:13
> Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. app-main.bundle.css:5092:21
> Expected media feature name but found ‘-ms-high-contrast’. app-main.bundle.css:5454:17
> Expected media feature name but found ‘-ms-high-contrast’. app-main.bundle.css:5454:44
> 

​</details>

**To Reproduce**
1. Go to 'Browser data'
2. Choose MySQL DB
3. Choose a table
4. Click on "Summarize"
5. Choose a column with a number value types
6. Click "+" on the column
6.5 "Auto-binned" option is already chosen. Also any other binning option except "no binning" shows same issue

**Expected behavior**
Not sure how many bins are expected to be created for auto-binning. But for predefined number of bins exactly that number of bins are expected to be created assuming count of records allow that (over 6000 in my case)

**Screenshots**
![image](https://user-images.githubusercontent.com/1980527/77880300-a2140480-725c-11ea-8b48-ab642f304f7b.png)
![image](https://user-images.githubusercontent.com/1980527/77880324-b0fab700-725c-11ea-8c8e-bdb0e6367529.png)
![image](https://user-images.githubusercontent.com/1980527/77880359-c4a61d80-725c-11ea-8cc2-813ec6e12531.png)
![image](https://user-images.githubusercontent.com/1980527/77880373-cec81c00-725c-11ea-89d9-6ee30a2b1872.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 74.0
- Your operating system: Windows 10.0.18362
- Your databases: MySQL
- Metabase version: 0.34.3
- Metabase hosting environment: Docker on Ubuntu
- Metabase internal database: H2

**Severity**
It's annoying

**Additional context**

**Comment by sbelak** [comment]
Probably related to #12004

**Comment by PauloHFM** [comment]
Hey I have the same issue, using currency column:
The values:
![Screenshot from 2020-04-07 17-37-31](https://user-images.githubusercontent.com/38223133/78717261-b9a35b00-78f6-11ea-8db1-3b2fa789ad72.png)

The bins:
100:
![Screenshot from 2020-04-07 17-38-04](https://user-images.githubusercontent.com/38223133/78717308-caec6780-78f6-11ea-8984-089df8ef98ec.png)

50:
![Screenshot from 2020-04-07 17-38-17](https://user-images.githubusercontent.com/38223133/78717330-d0e24880-78f6-11ea-9f25-aee9201d6323.png)

10:
![Screenshot from 2020-04-07 17-38-28](https://user-images.githubusercontent.com/38223133/78717338-d3dd3900-78f6-11ea-994f-a64eae009711.png)

Using PostgreSQL and Metabase v0.34.3

**Comment by sbelak** [comment]
@PauloHFM, @ralfeus could you show me what /api/field/:id where id is the id of the field you are trying to bin, returns.

**Comment by PauloHFM** [comment]
Hi @sbelak this helps? Got from the database!

id = 12284	
created_at = 2020-05-14 16:56:53	
updated_at = 2020-05-15 11:14:29	
name = preco_medio	
base_type = type/Float	
special_type = type/Price	
active = true	
description = 	
preview_display = true	
position = 0	
table_id = 829	
parent_id = 	
display_name = Preco Medio	
visibility_type = normal	
fk_target_field_id = 	
last_analyzed = 2020-05-14 16:56:58	
points_of_interest = 	
caveats = 	
fingerprint = {"global":{"distinct-count":1697,"nil%":0.0},"type":{"type/Number":{"min":0.38,"max":1599.0,"avg":8.8221948333333,"sd":31.446737766221894,"q1":2.6327219208958255,"q3":9.715240049717597}}}	
fingerprint_version = 4	
database_type = Float64	
has_field_values = none	
settings = {"number_separators":", "}
