### ISSUE TITLE
Region map needs 5 values minimum to show

### ISSUE THREAD

**Issue by EvaSchreyer** [metabase/metabase#12212]
I use a geojson region map to show the german states with their values and it works fine (map is here: https://raw.githubusercontent.com/EvaSchreyer/stuff/master/German_states_add_info).

The map does not load anymore when there are less than 5 states with values as a result. 

I use metabase 0.31.2

Thanks!

**Comment by flamber** [comment]
This has been fixed since 0.32.9 - latest release is 0.34.3 - and probably this week 0.35.0

**Comment by EvaSchreyer** [comment]
Great!! thanks :-)
