### ISSUE TITLE
Manual Y axis min/max don't take the "Multiply by" factor into account

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#12214]
**Describe the bug**
With the "Multiply by" factor set on Y axis, the manual min and max axis settings expect values on original scale instead of on the multiplied scale.

**To Reproduce**
1. Create a line chart.
2. Set Y multiplication factor (e.g. 0.000453 for metric tons to pounds).
3. Turn off the "Automatic Y axis range" and set your own min and max values.
4. Notice you have to input the values for original data scale (before multiplication).

**Expected behavior**
User would expect to use the same scale he sees on chart after setting the multiplication factor (i.e. min and max should be applied after the multiplication instead of before).

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.165-103.209.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Severity**
A nuisance, as I have to convert values back and forth.

**Comment by JesseSDevaney** [comment]
Reproduction:


https://github.com/metabase/metabase/assets/22608765/b1371b14-367b-4d28-b3a7-790c336c7e8e

**Comment by JesseSDevaney** [comment]
Waiting until backport merges to officially close
