### ISSUE TITLE
IE - Dashboard resizing and re-arranging do not work

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1222]

**Comment by STRML** [comment]
It does now! `0.10` has some minor breaking changes but it should support IE 10+ without issue.

**Comment by kdoh** [comment]
@STRML Thanks for the heads up!

**Comment by tlrobinson** [comment]
This appears to be resolved in #1859 due to moving off of react-grid-layout.

**Comment by agilliland** [comment]
nice! :joy_cat:

**Comment by STRML** [comment]
Bummer you guys felt the need to move off (but understandable, I was so busy it took nearly 9mo for the 0.14 update to come out) - interested in your alternative solution though.

**Comment by tlrobinson** [comment]
@STRML aside from the 0.14 and IE issues we also decided we didn't need/want the auto-layout features of `react-grid-layout` and generally just wanted more control. It seemed difficult to implement layout "strategies" other than the default. In particular we didn't want vertical compaction, but without it dragging a cell could wreak havoc on your layout.

Our new implementation is very basic, and also uses `react-draggable` and `react-resizable`: https://github.com/metabase/metabase/tree/multiseries_charts_v1/frontend/src/dashboard/components/grid

That said, `react-grid-layout` was very helpful to us in porting from Angular/Gridster to React. I'll continue to evaluate it and would consider switching back.

**Comment by STRML** [comment]
I appreciate the stripped implementation - in the near future I want to evolve the default build of RGL to be something more like that, and to work in compaction and other features via a mixin/plugin system so other developers can release dependent packages.

This is a good look at what a minimum featureset is - thanks.
