### ISSUE TITLE
Unable to filter on manually JOINed table

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#12221]
**Describe the bug**
When JOINing a table via the notebook editor, I'm unable to subsequently filter properly on that table's fields in the results table view.

**Logs**
n/a No relevant error logs

**To Reproduce**
1. On a new instance, create a new "Custom Question" on the Sample Dataset
2. Select the "Orders" table
3. On the editor page, select "Join data" and then select the "People" table
4. Use the populated defaults and select "Visualize"
5. On the resulting table results, click the "Filter" button
6. Select any field from the "User" section
7. Note that the popover does not change
8. Notice that selecting fields under the "Order" or "Product" sections result in the popover updating

**Expected behavior**
Expect the popover to contain the filter dialog for the selected field.

**Screenshots**
![image](https://user-images.githubusercontent.com/1512/78084333-bc3d0800-736c-11ea-880a-bae6e0c9c9ac.png)

![image](https://user-images.githubusercontent.com/1512/78084397-ee4e6a00-736c-11ea-9c68-671343513d9e.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.19.76-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-03-31",
      "tag": "v0.35.0",
      "branch": "master",
      "hash": "3f96c47"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Critical

**Additional context**
I can't get this to repro in Cypress for some reason, but was able to on our stats instance, docker, and local master.

**Comment by dacort** [comment]
FYI, this did not happen on rc2.

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/12244
