### ISSUE TITLE
big number "No change from last {0}" translation problem

### ISSUE THREAD

**Issue by ggentili** [metabase/metabase#12224]
in v.0.35 using a chrome browser with a language setting "italian" in big number, the string "No change from last {0}" is not traslated with the correct value "Nessun cambiamento dall'ultimo {0}" while the other trend cases are transated corrected

**Comment by flamber** [comment]
Hi @ggentili 
Please provide all the details requested, when opening a new issue.
I cannot reproduce on 0.35.0 with Italian browser content-language and with this query:
```
SELECT parsedatetime(formatdatetime('2020-03-01', 'yyyyMM'), 'yyyyMM') AS "MONTH", 500 AS "VALUE" UNION ALL
SELECT parsedatetime(formatdatetime('2020-04-01', 'yyyyMM'), 'yyyyMM') AS "MONTH", 500 AS "VALUE"
```

**Comment by ggentili** [comment]
the problem is present in every query. look at dashboard live here:
https://coronavirus.regione.umbria.it/  

screenshot today here:
![image](https://user-images.githubusercontent.com/6293268/78258880-26d07e00-74fc-11ea-9be3-8042b2cf7cab.png)

**Comment by flamber** [comment]
@ggentili You're using version 0.34.3. I cannot reproduce this problem on 0.35.0, but I would not recommend that you upgrade right now - please wait for 0.35.1
