### ISSUE TITLE
New filter expressions does not support `null`

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#12225]
Impossible to compare with null value
![Capture d’écran 2020-04-01 à 15 19 09](https://user-images.githubusercontent.com/1840026/78141903-7182c500-742c-11ea-94e0-7181b13bcc0d.png)
![Capture d’écran 2020-04-01 à 15 18 52](https://user-images.githubusercontent.com/1840026/78141910-734c8880-742c-11ea-8c40-6fb94a235a90.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @maximepvrt 
While I can see it's really frustrating now to be able to use `null`, I would not call it a bug - more a feature request or completeness. It's not listed in the documentation either:
https://www.metabase.com/docs/latest/users-guide/expressions.html
As for the date, have a look at #11330 - upvote by clicking :+1: on the first post.

**Comment by sbelak** [comment]
I've tried and the BE supports expressions comparing with `nil`, so this seems like only a FE limitation. 

We don't support `now()` in any shape or form though.

**Comment by flamber** [comment]
@sbelak Is it just FE that doesn't use the right MBQL function for "empty"?

1. Simple question > Sample Dataset > Orders
2. Filter by Discount = "Is empty"
3. The post request is `"query":{"source-table":1,"filter":["is-null",["field-id",15092]]}`
4. Now click the newly created filter "Discount is empty", go back, scroll to bottom and click Custom Expression - nothing happens.
5. Will generate a console error: `Error: Unknown MBQL clause ["is-null",["field-id",15092]]`

Doing step 4 with any other default function will convert it to the Custom Expression formula.

**Comment by sbelak** [comment]
The function is correct (`is-null` is just syntax sugar for `[:= nil]`), I think it's just the FE grammar that doesn't support it

**Comment by etcook** [comment]
This is significant for any situation where you are trying to filter a column that has NULLs as values. I was attempting to create a custom expression workaround ([column] = 'this' OR [column] IS NULL) for a particular query to save as a segment and ran into this solution. I might be wrong, but as it stands, I don't believe there is a way to filter a table in metabase (for certain DBs) while retaining the records with NULL values.

**Comment by nemanjaglumac** [comment]
@etcook - a repro test (for https://github.com/metabase/metabase/issues/13332) that checks for removed null values [has been added recently](https://github.com/metabase/metabase/commit/2a0683bc3dcf1b3e11e41d073c84bac71b3ddce5). Adding it here just to have cross-reference for different related issues.

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/15061
