### ISSUE TITLE
Loading dashboard with date params

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#12229]
infinie loop and js errors for loading dashboard with date parms, it's work only if edit param after loading
 
https://metabase.******.fr/public/dashboard/******?dates=2020-04-05~2020-04-23
https://metabase.******.fr/dashboard/******?dates=2020-03-01~2020-04-30

![Capture d’écran 2020-04-01 à 17 18 10](https://user-images.githubusercontent.com/1840026/78154665-d0503a80-743c-11ea-8e74-cedca1a730bc.png)

**Comment by flamber** [comment]
@maximepvrt Please fill out all the requested information. It would be very helpful to have the logs and browser console instead of just a screenshot.

**Comment by maximepvrt** [comment]
![Capture d’écran 2020-04-01 à 17 56 21](https://user-images.githubusercontent.com/1840026/78158931-283d7000-7442-11ea-8b6c-f2c45b4a3dcb.png)

**Comment by maximepvrt** [comment]
`{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "10.0.2.13+0",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "10.0.2.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "10.0.2.13+0",
    "os.name": "Linux",
    "os.version": "5.6.0+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-03-31",
      "tag": "v0.35.0",
      "branch": "master",
      "hash": "3f96c47"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Comment by mazameli** [comment]
Repro'd this as well. This specifically seems to be a problem for only date params when the dashboard includes SQL queries with field filters.

It does _not_ seem to be a problem if using e.g. a Category dashboard filter connected to a Category field filter in the SQL query.

**Comment by paulrosenzweig** [comment]
It was the same cause as #12228, so I'm going to mark as a duplicate.
