### ISSUE TITLE
Inherit referenced custom query parameters in v.35

### ISSUE THREAD

**Issue by buckelieg** [metabase/metabase#12231]
Whenever I am trying to reference custom query from another one it fails with the unsupplied query parameters error.
Therefore the parameters of referenced question needs to be promoted in the current one.

**Comment by flamber** [comment]
Hi @buckelieg 
Please provide the information requested, when opening a new issue. Without logs or steps-to-reproduce, it's almost impossible know what's wrong.

**Comment by buckelieg** [comment]
![query_test1](https://user-images.githubusercontent.com/23184851/78165156-93dc0900-7453-11ea-80c4-ca13558118be.png)
![query_test2](https://user-images.githubusercontent.com/23184851/78165174-98a0bd00-7453-11ea-9b55-ceff3c20eac9.png)

**Comment by flamber** [comment]
@buckelieg That's similar request to #6449

**Comment by buckelieg** [comment]
It seems so. Closing.
