### ISSUE TITLE
Pulse interval

### ISSUE THREAD

**Issue by nathansantanna** [metabase/metabase#12237]
Hello, 

I loved metabase, i tried many tools and metabase is by far the most easy and intuitive one. 
My request is in alerts and pulses via email that can only be sent hourly, i wanted a shorter interval like minutes. 

Thanks in advance

**Comment by mazameli** [comment]
Thanks for the kind words! I think you're looking for this issue, so please click on the 👍 button there to show your support:https://github.com/metabase/metabase/issues/3846

 I'll close this issue as a duplicate.
