### ISSUE TITLE
Error log not shown because errors are wrapped in 202-success requests

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12233]
**Describe the bug**
Errors are not shown in the log anymore (Admin > Troubleshooting > Logs), because the requests are `202` even for failed queries.

To get the error, you need to disassemble the response in the request in the browser developer Network-tab.

**To Reproduce**
1. Native query `SELECT * FROM FAKETABLE`
2. Shows this in the log instead of an error:
`[962e499e-d224-4b31-b78d-c985fe280ad4] 2020-04-01T19:00:46+02:00 DEBUG metabase.middleware.log POST /api/dataset 202 [ASYNC: completed] 23.1 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (2 idle, 0 queued) (128 total active threads) Queries in flight: 0 (0 queued)`

**Information about your Metabase Installation:**
Metabase 0.35.0

**Comment by camsaul** [comment]
Fixed by #12325
