### ISSUE TITLE
Horizontal Rule (HR) not working in Text Box markdown

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12256]
**Describe the bug**
Adding a horizontal rule to Text Box only shows a tiny dot instead of a full width ruler.

**To Reproduce**
1. Edit dashboard and add Text Box with the content:
```
# Header
---
Text
```
3. There's only a tiny dot between Header and Text:
![image](https://user-images.githubusercontent.com/1447303/78344853-453a8600-759d-11ea-8723-549cf9f7dfae.png)

**Expected behavior**
Full width ruler

**Information about your Metabase Installation:**
Metabase 1.34.3 and 0.35.0 with various browsers and backends.

**Additional context**
https://discourse.metabase.com/t/horizontal-rule-not-working-in-markdown/9567

**Comment by noahmoss** [comment]
When this is fixed, our Markdown->Slack processing code on the backend should be changed to include this as well (currently it is just omitted).
