### ISSUE TITLE
Higher Granuality when binning longitude and latitude

### ISSUE THREAD

**Issue by amirtvkli1** [metabase/metabase#12257]
**Problem**
I want to show my data on a grid map. I have two columns for Longitude and Lattitude in the data. In can summarize the data based on longitude and lattice with different bin size, but the smallest available bin size is 0.1 degree which is still very large (the range of longitude/latitude in my data is less than 5 degree and I want to bin them in 0.05 degrees or less).

Also, when I convert my question to the SQL query, the map doesn't work anymore (it has been reported before in [here](https://github.com/metabase/metabase/issues/9346#issuecomment-458985874) and [here](https://github.com/metabase/metabase/issues/8362).

**The solution I'd like**
Have either:
* smaller bin size (0.05 and 0.01 degrees)
* custom bin size
Alternatively, if we can convert the `Custom Question` to `Native Query` without losing the bins, then I can put mu custom bin size in the query.

**The alternatives I've tried**
1. I tried to convert the `Custom Question` to `Native Query` and put mu custom bin size, but it didn't work.
2. I tried to bin the longitude and latitudes on my own in the SQL query, but when I do that the grid map doesn't recognise these columns as proper long/lat:
```
(width_bucket("Postcode"."lat", 0, 90, 9000)-1)*0.01 || ' - ' || width_bucket("Postcode"."lat", 0, 90, 9000)*0.01 AS lat_bucket,
(width_bucket("Postcode"."long", -180, 180, 36000)-18001)*0.01 || ' - ' || (width_bucket("Postcode"."long", -180, 180, 36000)-18000)*0.01 AS long_bucket,
```
![5](https://user-images.githubusercontent.com/40166454/78345509-9cd4f380-7595-11ea-8dc5-7acf9da13cb7.png)

**Importance**
Without this feature, I can not use maps on my dashboards. This is the only way that I can represent my data over the map.

**How to regenerate the question**
To regenerate the question and see the problem, simply follow these on the sample data:

Data: Orders
Join data: `Orders` with `People` on `User ID | ID`
Summarize: `Sum of Subtotal` by `User-Lattitude:1` and `User-Longtitude:1`
(you don't have grid size less than 0.1 degrees)
![1](https://user-images.githubusercontent.com/40166454/78345998-55029c00-7596-11ea-9f34-f605c11ec721.png)

and the result, if shown on the grid map:
![2](https://user-images.githubusercontent.com/40166454/78346038-651a7b80-7596-11ea-8c69-a71384f2c752.png)

But if you convert the Question to the Query, you will lose the bins:
![3](https://user-images.githubusercontent.com/40166454/78346114-7b283c00-7596-11ea-8921-6b18194c0a7f.png)

**Comment by flamber** [comment]
Related to #9208 (possibly a duplicate). As you mention/link, binning isn't available in SQL #8362

**Comment by flamber** [comment]
A workaround/hack is to use [MB_BREAKOUT_BIN_WIDTH](https://github.com/metabase/metabase/blob/master/docs/operations-guide/environment-variables.md#mb_breakout_bin_width), which will allow you to define smaller bins like `0.01` and that value is used when selecting "Auto binned".

**Comment by ezmckinn** [comment]
> A workaround/hack is to use [MB_BREAKOUT_BIN_WIDTH](https://github.com/metabase/metabase/blob/master/docs/operations-guide/environment-variables.md#mb_breakout_bin_width), which will allow you to define smaller bins like `0.01` and that value is used when selecting "Auto binned".

This is really interesting! Can we configure this environment variable within an open-source deployment? Or

**Comment by flamber** [comment]
@ezmckinn Yes, click the link - scroll to the top to see how to add environment variables.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by zell180** [comment]
@willbryant when this fix will be released? is possible to build a specific version with this improvement?

**Comment by willbryant** [comment]
@zell180 I have no idea, I am not part of the metabase team. You can definitely do a build with my patch above - that's what I've done. Works fine for me.

**Comment by lucasmocellin** [comment]
> A workaround/hack is to use [MB_BREAKOUT_BIN_WIDTH](https://github.com/metabase/metabase/blob/master/docs/operations-guide/environment-variables.md#mb_breakout_bin_width), which will allow you to define smaller bins like `0.01` and that value is used when selecting "Auto binned".

I found another workaround: 
* select 0.1degrees
* then go to the map click on any square
* select "zoom in"
* then go to the query editor and BOOM: it binned to 0.01 degrees:
<img width="324" alt="image" src="https://github.com/metabase/metabase/assets/26748111/84662bfc-2e9e-46c1-b800-fdd204b4a918">
* remove all the filters from your query
* save the query, then you should have the 0.01 degrees

I noticed everytime you zoom in it adds a 0, thus zooming in again would create binning of 0.001degrees.

**Comment by mngr** [comment]
Closed by https://github.com/metabase/metabase/pull/51472
