### ISSUE TITLE
Not connecting MangoDB compass with Atlas:.

### ISSUE THREAD

**Issue by abdullah7111** [metabase/metabase#12254]
![image](https://user-images.githubusercontent.com/45183164/78329369-f55abf80-759a-11ea-9a21-34401cb1dcc9.png)
I am unable to connect Atlas with compass when I copy and paste the link from atlas and tap the connect button but no response. Please see the screenshot. Thank you

**Comment by flamber** [comment]
Hi @abdullah7111 
Seems like you're reporting a problem with a different software than Metabase.
