### ISSUE TITLE
Can't login with google

### ISSUE THREAD

**Issue by Limess** [metabase/metabase#12258]
**Describe the bug**
Cannot signin with google on Metabase 0.35.1

**Logs**
In both the javascript console and the server logs
```
"Google Auth token appears to be incorrect. Double check that it matches in Google and Metabase."
```

**To Reproduce**
1. Logout of metabase
2. Click sign in with google
3. Log in with google
4. See message in javascript console along with 400 error.

**Expected behavior**
Login to work successfully

**Screenshots**

**Information about your Metabase Installation:**

Tested with multiple browsers (Chrome, Firefox) and clearing all cookies.

The following debug information is from our _working installation_ (`v0.33.x`) not the 0.35.1 version as we couldn't log in to get that info before rolling back, included as it shows the rest of our setup.

We're deploying metabase on ECS using the docker image.

_(EDIT - removed Diagnostic Info from a different version, since it causes confusion)_

**Severity**
Blocker for using metabase, had to rollback to get it working again.

**Comment by flamber** [comment]
Hi @Limess 
I have not been able to reproduce this on 0.35.1. I would suggest that you upgrade to 0.33.7.3, since that includes a security fix for Google Auth. And I'm sure the problem would also occur on that version.

**Comment by Limess** [comment]
Thanks flamber

After your comment I resolved this by updating the google client ID to include the `.apps.googleusercontent.com` suffix which was previously missing (but working without inclusion in older versions).

I'll close this.
