### ISSUE TITLE
Impossible to use custom questions for segments

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#12261]
Create a segment with "custom question" create "Unknow Segment" error.

I tried with several parameters in "custom question", I still get this error.

![Capture d’écran 2020-04-03 à 17 27 51](https://user-images.githubusercontent.com/1840026/78378230-fa3a6600-75d0-11ea-972b-d876604eef09.png)

Same, if use a basic segment (without "custom question") in a question, impossible to add a filter with a "custom question".

![Capture d’écran 2020-04-04 à 11 29 08](https://user-images.githubusercontent.com/1840026/78423582-84350e00-7667-11ea-9185-e1b5b9ef0eeb.png)

![Capture d’écran 2020-04-04 à 11 30 20](https://user-images.githubusercontent.com/1840026/78423621-d413d500-7667-11ea-9903-82d05ee758e1.png)

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "10.0.2.13+0",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "10.0.2.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "10.0.2.13+0",
    "os.name": "Linux",
    "os.version": "5.6.0+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-02",
      "tag": "v0.35.1",
      "branch": "release-0.35.x",
      "hash": "e67f169"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
Thanks again for your product 😍

**Comment by flamber** [comment]
Hi @maximepvrt 
It would be really helpful if you posted all the information requested, when opening a new issue.

**Comment by maximepvrt** [comment]
updated :-)

**Comment by flamber** [comment]
Can you provide steps to reproduce? Preferably using the Sample Dataset.
I would recommend that you use Java 11, or 8 or 13 - version 10 is EOL.
Error in text, cannot search images: `Error: Unknown Segment: Activity Type ID`

**Comment by maximepvrt** [comment]
I updated java to v13, same error.
I tested with your dataset Sample Dataset, too.

To reproduce that :
- create a new segment
- define a custom question with any data filter
![Capture d’écran 2020-04-04 à 15 06 51](https://user-images.githubusercontent.com/1840026/78451564-8d81a300-7686-11ea-8c2f-57aabf6af792.png)
- an error Unknown Segment is created :(

An other similar bug : 
- create a new segment with a simple filter
![Capture d’écran 2020-04-04 à 15 13 15](https://user-images.githubusercontent.com/1840026/78451619-d89bb600-7686-11ea-99a9-4a477a2b5eca.png)
- create a new question with this segment
- add a custom question filter
![Capture d’écran 2020-04-04 à 15 15 13](https://user-images.githubusercontent.com/1840026/78451653-27495000-7687-11ea-8324-0b52af0e300b.png)
- an error Unknown Segment is created :(

**Comment by flamber** [comment]
@maximepvrt All your formulas look wrong. I know the error message is not very helpful, but what are you trying to achieve with `[Name] or [Email]` or just `[Email]` ?
Have a look at the documentation: https://www.metabase.com/docs/latest/users-guide/expressions.html

**Comment by maximepvrt** [comment]
Sorry :(
I would like to describe if the value was defined. It seemed to me that it worked outside the segment, but not. Sorry for my issues requested too quickly 😬

**Comment by flamber** [comment]
But that's exactly the same as what you're trying to do with #12225 - right? Until there's a solution for that, then it's not possible, when using multiple fields together with `OR`. It is possible by using the regular filter "Is not empty" for single columns.
