### ISSUE TITLE
Filter "Custom Expression" could provide more guidance and helpful errors

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12268]
**Describe the bug**
The new (0.35.0) Custom Expressions can be a little tricky to get started with and the errors can be difficult to understand (or rather misleading).

**To Reproduce**
Example 1:
1. Custom question > Sample Dataset > Orders
2. Filter > Custom Expression
3. Select "Discount" and try to click Done
4. Errors with `Unknown Segment: Discount`:
![image](https://user-images.githubusercontent.com/1447303/79844816-7ba93b00-83bc-11ea-9aff-050687f31e5d.png)
5. The correct formula would be `[Discount] = 10`, example. There's a request to check if field is `null` #12225

Example 2:
1. Custom question > Sample Dataset > Products
2. Create a Custom Field
3. Write `contains([Title], "Awesome")`
4. No help is shown:
![image](https://user-images.githubusercontent.com/1447303/79844739-5a484f00-83bc-11ea-83d5-fd5527f6f748.png)
5. It seems like it's not obvious which functions are available where (#12363), but `contains` cannot be used on Custom Field, only Filter.

Example 3:
1. Simple question > Sample Dataset > Products
2. Filtered by > Custom Expression
3. Manually write `contains` and click outside the input formula to unfocus/blur the input, which shows the following error, which breaks UI a little and doesn't provide much help:
![image](https://user-images.githubusercontent.com/1447303/79841417-aa70e280-83b7-11ea-914b-c8d8a225150f.png)

Example 4:
It seems like the input doesn't error, when using `regexextract` on SQL Server for some users/browser even though the driver says `regex` isn't supported.
https://discourse.metabase.com/t/regexextract-in-custom-column/10403
![image](https://user-images.githubusercontent.com/1447303/83859150-d1903300-a71d-11ea-850f-af2019f98029.png)
And it's possible to input `Median()` and `Percentile()`, which doesn't show an error, but the query fails #12222

**Expected behavior**
Maybe the beginning equal sign on the formula is a little misleading?
Maybe an error like "Missing field comparison expression and value"?
Perhaps a link to [expression documentation](https://www.metabase.com/docs/latest/users-guide/expressions.html) somewhere?

**Information about your Metabase Installation:**
Metabase 0.35.2

**Additional context**
Created after trying to understand this closed issue #12261
Related #12140 and #12393

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/15061
