### ISSUE TITLE
 Ability to define dashboard filter as required

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#12267]
I share the same reporting to all my clients in an iframe with an uuid id parameter. I have hidden the parameter with #hide_parameters. But if a developer inspects the iframe and opens the link without defining the parameter, he has access to all of the company's data 😬

I don't know if the parameter should be defined required for the dashboard or only for the sharing link

**Comment by flamber** [comment]
Hi @maximepvrt 
That already exists. It's called locked parameters:
https://www.metabase.com/docs/latest/administration-guide/13-embedding.html#embedding-charts-and-dashboards-with-locked-parameters
Or maybe I don't understand what you're requesting - then please describe with a lot more details.
You can find a lot of other examples and help in the forum: https://discourse.metabase.com/

**Comment by maximepvrt** [comment]
Perfect 🙌
Sorry to have opened a issue for nothing
