### ISSUE TITLE
Cannot view/edit table-level permissions for databases that are not schema-based

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12269]
**Describe the bug**
Cannot view/edit table-level permissions for databases that are not schema-based (like MySQL, SQLite, BigQuery, etc). It still works for Postgres/Redshift etc that are schema-based.

**To Reproduce**
1. Go to Admin > Permissions > for a non-schema database, try clicking "View tables" on the left
2. Nothing happens,  - browser console says:
`TypeError: Unable to get property 'tables' of undefined or null reference`

Notice that the URL is:
`/admin/permissions/databases/8/schemas/null/tables`
Whereas on 0.34.3, the URL was:
`/admin/permissions/databases/8/tables`

**Information about your Metabase Installation:**
Metabase 0.35.1, various backends and browsers.

**Additional context**
https://discourse.metabase.com/t/hanging-waiting-for-permissions/9579

**Comment by paulrosenzweig** [comment]
Fixed in #12299
