### ISSUE TITLE
Pinned dashboards always sorted ascending on "Start here" section on homepage

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12284]
**Describe the bug**
Ordering the pinned dashboards in "Our analytics" in a manual order works, but the order on the home page is always ascending/alphabetically.

**To Reproduce**
1. Go to "Our analytics"
2. Pin two dashboards and reorder them manually, so they're not alphabetical order
![image](https://user-images.githubusercontent.com/1447303/78656417-a6c56200-78c7-11ea-90fd-90fead07ac47.png)
3. Go to homepage, where the "Start here" section will show the pinned dashboards in alphabetical order
![image](https://user-images.githubusercontent.com/1447303/78656482-bfce1300-78c7-11ea-8009-11ceed8ac5e7.png)

**Expected behavior**
Preserve the order defined in "Our analytics".

**Information about your Metabase Installation:**
Metabase 0.34.3 and 0.35.1, various browsers and backends

**Additional context**
https://discourse.metabase.com/t/0-34-3-version-some-problems/9602
Related #9992

**Comment by dpsutton** [comment]
I believe the "start here" section has been replaced with a "pick up where you left off" section so this bug no longer exists.
