### ISSUE TITLE
Unable to save Native Query Result as Question

### ISSUE THREAD

**Issue by denisesenguel** [metabase/metabase#12285]
**Describe the bug**
Whenever I want to save the result of a Druid native query as a question in Metabase, either as a change of an existing question or an entirely new one, the result cannot be saved!

**To Reproduce**
1. Either 
- Go to an existing question based on a native query and change anything
- Create a new Druid native query question
2. Click on 'Save'
3. In the pop-up window, click on 'Save as new question', type in any name and click 'Save'

**Expected behavior**
- the pop-up should close automatically and I should be redirected to the newly saved question (as is happening when saving a query builder question)
- the question should be saved and appear in the chosen collection

**Actual behaviour**
- The 'Save' Button turns green for a while and says 'Successful' but nothing happens, the pop-up stays opened and the button turns back blue and allows me to click "save" again after a whie
- when navigating to the collection the question should have been saved to it doesn't appear anywhere

**Screenshots**
This is what I see after clicking "save"
![Bildschirmfoto 2020-04-07 um 12 28 47](https://user-images.githubusercontent.com/17010657/78659645-29e8b700-78cc-11ea-8721-075dc1f2d06c.png)
(sorry it's in German..)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 80.0.3987.132 (tried on Firefox as well)
- Your operating system: MacOS Catalina 10.15.1
- Your databases: Druid 0.17.1
- Metabase version: 0.35.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
This is considerably blocking my work. I was even thinking of downgrading but then I'll be confronted with #10935 again 😞 

**Additional context**
Saving or changing questions based on the Query Builder works without any problems!

**Comment by flamber** [comment]
Hi @denisesenguel 
It would be very helpful if you checked the log (Admin > Troubleshooting) or browser console for any errors. I have a feeling that you're most likely seeing the same errors as #12265

**Comment by denisesenguel** [comment]
@flamber yes you're right! I'm also seeing 
```"value may be nil, or if non-nil, value must be an array of valid results column metadata maps."```

**Comment by flamber** [comment]
Okay, then I'm going to close this in favor of the other issue.
