### ISSUE TITLE
SMTP config page has redundant subheading text

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1229]
We should get rid of the subheading text for:
* Host
* Port
* Username
* Password

The security one could also go if we change the main heading for that field to "SMTP Security Protocol."

Screenshot:
<img width="735" alt="emailcredentials" src="https://cloud.githubusercontent.com/assets/2223916/10441532/d48c98c8-70fe-11e5-9727-9d3c1c7ee9db.png">

**Comment by agilliland** [comment]
Done as part of #1482
