### ISSUE TITLE
Referencing Saved Questions and Permissions

### ISSUE THREAD

**Issue by michael-plusdental** [metabase/metabase#12300]
**Describe the bug**
There might be an issue, could also be intended to work like this, when using [this feature](https://github.com/metabase/metabase/pull/11835). A user has to be able to also access the collection the referenced question is in. 

**Context**
1. We have a stored question we want to limit direct access to, but we want to use the results from this question
2. We store that question in a collection the end user does not have access to
3. The end user cannot use questions that reference the stored question despite having access to the underlying DB connection (so were the stored question put into a public folder they could access it)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a question
2. Store question in a non-public collection
3. Create a new question that references the stored question
4. Attempt to use the new question from a user that does not have access to the non-public collection
5. Ensure the user could access the stored question were it not in a non-public collection (move to a public folder)

**Expected behaviour**
If a user has access to the required DB connections then they should be able to use the results of stored questions even if the stored questions reside in collections they do not have access to.

**Information about your Metabase Installation:**

- Your browser and the version: Various
- Your operating system: Various
- Your databases: Postgres, Redshift, H2
- Metabase version: v0.35.1
- Metabase hosting environment: elastic-beanstalk
- Metabase internal database: Postgres

**Severity**
Low, there are only a few circumstances the feature would be used like this.

**Additional context**

As a note [this bug](https://github.com/metabase/metabase/issues/12294) should not be an issue.

**Comment by flamber** [comment]
Hi @michael-plusdental 

This doesn't sound like a bug, but more like a feature request?

It sounds like you're asking for collection permissions to be overruled, when a user has "Write SQL" permissions, to questions from the same database - or at least for when the user is trying to use the question as a sub-query in their own Native question?

**Comment by michael-plusdental** [comment]
> Hi @michael-plusdental
> 
> This doesn't sound like a bug, but more like a feature request?
> 
> It sounds like you're asking for collection permissions to be overruled, when a user has "Write SQL" permissions, to questions from the same database - or at least for when the user is trying to use the question as a sub-query in their own Native question?

I think you are correct? But to make sure (and then I will move this over to the correct place) I will give a few more details:

In this exact situation I was making a single question for a user and placing it into their personal collection. But that question referred to another question in a collection the user did not have access to. Because of this, the question in the personal collection would not work. 

Both questions use the same connection as a note, so if I combined the two questions into one and placed that into the user's collection they would be able to run it no problem.

**Comment by flamber** [comment]
@michael-plusdental I highly doubt that such functionality will be added, since it would override how permissions work and would make it difficult to figure out why some questions are accessible all the time even when added to collections that only some people have access, but you're welcome to open a feature request for that. Closing this bug report.
