### ISSUE TITLE
Custom Expression - `substitute` or `replace` ?

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12306]
**Describe the bug**
The function `replace` does not exist even though the [documentation lists it](https://www.metabase.com/docs/latest/users-guide/expressions.html), but `substitute` does exist (but not in documentation), and when using `substitute` the helper dropdown says "replace".
~~Not sure if this is a documentation miss or if the function should actually be called `replace`?~~
_Not sure if we can change the function to `replace` without breaking questions already created with `substitute` (even though that would be fairly few, since it arrived in 0.35)?_ [See comment](https://github.com/metabase/metabase/issues/12306#issuecomment-612196116)

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Custom Column - in formula try finding `replace`, then go for `substitute` and notice dropdown helper says "replace" everywhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/1447303/79018097-3f333f00-7b73-11ea-918c-892f6730bbf1.png)

**Information about your Metabase Installation:**
Metabase 0.35.1, various backend and browsers

**Comment by sbelak** [comment]
I don't think renaming will break anything as the MBQL generated will remain the same no matter how we name it in QB.

**Comment by flamber** [comment]
Fixed by #12316
