### ISSUE TITLE
Show multiple metrics in tooltip when hovering on region map

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12308]
**Is your feature request related to a problem? Please describe.**
Currently region map only shows 1 metric and 1 region name in tooltip, when hovering the region:
![image](https://user-images.githubusercontent.com/1447303/79027629-4bc49100-7b8d-11ea-92f9-bc94eddaef6e.png)

**Describe the solution you'd like**
It would be great to allow multiple extra fields to show details in tooltips - just like pin maps does:
![image](https://user-images.githubusercontent.com/1447303/79027376-49156c00-7b8c-11ea-9c96-dd92493a0b01.png)

**Describe alternatives you've considered**
Creating multiple maps on the dashboard - each with their own single metric :cry: 

**Additional context**
Has been requested a couple times in the forums the past few weeks:
https://discourse.metabase.com/t/custom-maps/9676
https://discourse.metabase.com/t/how-do-i-include-multiple-metrics-in-a-custom-map/9597

Related to #3971 #4748 #5176

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Gotcha — it seems that the main thrust of this request is to just have the additional fields from the result table be displayed in the tooltip. (I.e. this is not a request for [bivariate choropleth maps](https://www.visualisingdata.com/2017/06/bivariate-choropleth-maps/).)

**Comment by devFiledTech** [comment]
Even if showing the other data of the question would already solve the problem, and it is possible to implement this in
a future update?

**Comment by nemanjaglumac** [comment]
Reproduced as part of the repro for #14650 in #14688.

**Comment by paulrosenzweig** [comment]
I don't think it was actually reproduced in that issue. That test only has a single metric.

That said, this is fixed (as of 0.37.0 according to @flamber) so we can close the issue.
