### ISSUE TITLE
Language is not listed

### ISSUE THREAD

**Issue by fly2moon** [metabase/metabase#12313]
Hello.

I tied to add the Korean language to Metabase.
I added the kr.po file under /locales and edited /resources/locales.clj.
The build completed successful. But after starting Metabase, Korean was not listed at admin/General/LANGUAGE.
Did I miss something??

**Comment by fly2moon** [comment]
While building, there are the warning about i18n. \

Compiling metabase.api.routes
04-13 02:47:11 WARN api.common :: #metabase.util.i18n.SystemLocalizedString{:ns-str metabase.api.common, :msg Warning: endpoint {0}/{1} does not have a docstring., :args [metabase.api.testing POST_snapshot_:name]}
04-13 02:47:11 WARN api.common :: #metabase.util.i18n.SystemLocalizedString{:ns-str metabase.api.common, :msg Warning: endpoint {0}/{1} does not have a docstring., :args [metabase.api.testing POST_restore_:name]}
04-13 02:47:12 WARN api.common :: #metabase.util.i18n.SystemLocalizedString{:ns-str metabase.api.common, :msg Warning: endpoint {0}/{1} does not have a docstring., :args [metabase.api.transform GET_:db-id_:schema_:transform-name]}
04-13 02:47:13 WARN api.common :: #metabase.util.i18n.SystemLocalizedString{:ns-str metabase.api.common, :msg Warning: endpoint {0}/{1} does not have a docstring., :args [metabase.api.util GET_bug_report_details]}
Compiling metabase.api.search

**Comment by flamber** [comment]
Hi @fly2moon 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
How are you building? Have you tried `./bin/build translations` ?
It would be great if you joined the translation group, so Korean could become part of Metabase: https://poeditor.com/join/project/ynjQmwSsGh
