### ISSUE TITLE
Issue with Metabase pulse card in Slack - version v0.34.1

### ISSUE THREAD

**Issue by amitbgrg** [metabase/metabase#12312]
**Describe the bug**
Few of the pulses that come in slack doesn't give any data table under it. Even after trying to expand the pulse, it doesn't respond. This is very random, happening with few queries only. Pulse card is not available even after expanding

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/63544105/79068610-d7e9cc00-7ce5-11ea-9059-46b2e24fbc0b.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Hi @amitbgrg 
Latest version of Metabase is 0.35.2, so please upgrade to that.
Please post "Diagnostic Info" from Admin > Troubleshooting.
And check the logs for any errors and warning. Admin > Troubleshooting > Logs.

**Comment by flamber** [comment]
Closing, since there's no response or enough details to figure out what happened.
