### ISSUE TITLE
Navicat vs Metabase - The Speed of running Mysql

### ISSUE THREAD

**Issue by Scugzd** [metabase/metabase#12314]
I tried to run the mysql command on Navicat and Metabase which got totally differnt time.

Take example, I run the same command, like "select * from table_name where time>"2020-04-01", in Navicat, it takes 1 second , and Metabase takes 10 times.

I'm not sure why it happened?  And I already tried to cut the elements from "Select", and keep the select as small as I can, but nothing change.

**Comment by flamber** [comment]
Hi @Scugzd 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
