### ISSUE TITLE
0.35.2 Mac App download not working

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12310]
There's currently no 0.35.2 release of the Mac App because of technical issue with Apple developer site. Will be fixed as soon as possible.
https://downloads.metabase.com/v0.35.2/Metabase.dmg -> 404 error

**Comment by camsaul** [comment]
What technical issue is this? Last I checked @salsakran just needs to update our developer agreement

**Comment by flamber** [comment]
Simply just created this, so it we didn't forget it and people know we're working on it. Might not be technical problem, from the users point it's an error.

**Comment by matteing** [comment]
Hey - affected by this at the moment.

**Comment by flamber** [comment]
Fixed yesterday
