### ISSUE TITLE
New columns in Data Model have null visibility_type

### ISSUE THREAD

**Issue by bplmp** [metabase/metabase#12321]
**Describe the bug**
When we add new columns to an existing table in our Redshift DB, Metabase is able to sync them, but they still don't show in the Data Model. Examining the `metabase_field` table, I can see that they have `visibility_type = NULL`. 

If I change the `visibility_type` to `normal` manually using the API, then they start appearing in the Data Model.

**To Reproduce**
1. Create a table in a Redshift DB
2. Sync database schema in Metabase
3. Add new columns
4. Sync schema again
5. Go to Data Model and see that columns are not showing

**Expected behavior**
New columns in an existing table should have `visibility_type = 'normal'` when syncing for the first time.

**Version**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.19.106-coreos",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo",
      "mysql",
      "redshift",
      "postgres",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.28-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Annoying users as we have to manually update `visibility_type`. As this step requires using the Metabase API, it is blocking users who can't / don't know how to use the API.

**Comment by flamber** [comment]
Hi @bplmp 
I have not been able to reproduce this on 0.35.2 with MariaDB 10.4 as backend, but I haven't tested against Redshift as datasource. All the different database types I tested created `'normal'`.
Are you seeing this problem only with Redshift?
By any chance, could you have created a trigger that does something, when the row is created?
There's issue #5129, where Data Model needs a browser refresh to show new tables/columns, but it sounds like you're experiencing something that isn't fixed by a simple browser refresh.

**Comment by bplmp** [comment]
Hi @flamber, sorry for the delay in responding here, thanks for the response.

Yes, I was seeing this only with Redshift. We don't have any triggers after creating tables / adding columns... 

I did do a browser refresh and cleaned cache but the problem persisted.

I haven't seen this issue since my first comment because we've created no new tables / columns. Since you're unable to reproduce, I'll close this for now, and reopen if it happens again.

**Comment by bplmp** [comment]
@flamber this has just happened again... reopening this issue.

**Comment by flamber** [comment]
@bplmp Okay, but without steps to reproduce I don't even know where the problem could be.

**Comment by bplmp** [comment]
Got it, maybe this is something that is specific to Metabase 0.34.3? I am not sure either how to tell you the steps to reproduce this other than what I had posted originally, so I'll close it again.

**Comment by flamber** [comment]
@bplmp Perhaps you can log any changes to `metabase_field` for a period - it's probably a lot of logs.
But I have a feeling that there's something off with your application database.
When I run this, it doesn't seem like the default schema even allows `null` for that column:
```
show columns from metabase_field where Field='visibility_type';
+-----------------+-------------+------+-----+---------+-------+
| Field           | Type        | Null | Key | Default | Extra |
+-----------------+-------------+------+-----+---------+-------+
| visibility_type | varchar(32) | NO   |     | normal  |       |
+-----------------+-------------+------+-----+---------+-------+
1 row in set (0.003 sec)
```
