### ISSUE TITLE
Can't connect to smtp service

### ISSUE THREAD

**Issue by AxelFurlanF** [metabase/metabase#12334]
**Describe the bug**
Out of nowhere, emails stopped working. Neither from the test email button in the smtp settings nor through pulses.

**Logs**
```
2020-04-16T11:48:28-03:00 WARN metabase.email Failed to send email
2020-04-16T11:48:28-03:00 WARN metabase.api.email Problem connecting to mail server: Couldn't connect to host, port: email-smtp.us-east-1.amazonaws.com, 25; timeout -1
2020-04-16T11:48:28-03:00 ERROR metabase.middleware.log POST /api/email/test 500 2.2 mins (1 DB calls)  {:message "Sorry, something went wrong. Please try again."}
```

**To Reproduce**
This happens using an aws SES service. I use TLS and port 25. I use this smtp user to send emails through other services like Airflow and works flawlesly.
**Screenshots**
![image](https://user-images.githubusercontent.com/19914428/79471425-006d1100-7fd9-11ea-9a87-feb5b7657d88.png)

**Severity**
With this issue, our company cannot be notified about important information.

**Additional context**
I have another metabase intended for other uses, this also happens with this metabase - same version.
Also, when I entered the metadata database, in the `pulse_channel` table I saw that the majority of email pulses had this on the details column:
```
{"emails":null}
```
But if you enter the pulse in the webserver, you can see the actual people that should be sent the email.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.152-127.182.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-10",
      "tag": "v0.35.2",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @AxelFurlanF 
You're using the Docker image, right?
My first guess is that something has happened with DNS, but it would also be a firewall blocking.
Have you tried doing a `ping email-smtp.us-east-1.amazonaws.com` from within the container?

**Comment by AxelFurlanF** [comment]
> Hi @AxelFurlanF
> You're using the Docker image, right?
> My first guess is that something has happened with DNS, but it would also be a firewall blocking.
> Have you tried doing a `ping email-smtp.us-east-1.amazonaws.com` from within the container?

Hi @flamber , thanks for reaching out! Yes, I use the docker image with AWS ECS on Fargate (a serverless service of AWS).
Ok so I ran locally:
```
docker run -d -p 3000:3000 --name metabase metabase/metabase
```

Inside the container I could:
```
bash-5.0# telnet email-smtp.us-east-1.amazonaws.com 25
220 email-smtp.amazonaws.com ESMTP SimpleEmailService-d-AF7312DK3 pOJnlR8cbTcn2oaUfKCQ
```

Which I think it's expected behaviour according to https://aws.amazon.com/premiumsupport/knowledge-center/smtp-connectivity-timeout-issues-ses/

Also, the security group associated with the ECS container allows all inbound and outbound traffic.

**Comment by flamber** [comment]
@AxelFurlanF Interesting. Normally when something like this "out of nowhere" starting failing, then it's likely not related to Metabase, but network related.
Could it be that Amazon has changed something? Have you tried to use port `587` and `TLS`?

**Comment by AxelFurlanF** [comment]
@flamber THANK YOU! I've already tried all types of smtp security settings but never changing the port. Using port 587 the test email and pulses worked flawlessly!
