### ISSUE TITLE
Only admins can search for tables via universal search.

### ISSUE THREAD

**Issue by cgddrd** [metabase/metabase#12332]
**Describe the bug**

As a 'standard' (non-admin) user of Metabase, I expect to be able to search for tables via their name using the universal search functionality, however I am unable to do this - if I attempt to search for a table name that I know to exist, Metabase returns no search results. 

However, if I perform the same action as an **admin user**, then the search results include the relevant tables.

**Note:** In both examples, the user group assigned to each user ('All Users' and 'Admins' respectively) are set to have unrestricted access to the tables I am attempting to search for.

**Logs**

No logs.

**To Reproduce**

1. Identify a valid/existing table name that you want to search for.
2. Ensure the user group has permissions to query/access the table you wish to search for (via 'Admin' -> 'Permissions')
3. Attempt to search for the table name via the universal search bar at the top of the Metabase UI. 
4. Note how **the table is not included in the search results** (although questions whose name contains part of the search term may be returned).
5. Repeat steps 1-3, but as an **admin user**, where this time you will see the table correctly returned in the search results.

**Expected behavior**

All users whose parent user group has permissions to query/access tables within Metabase should be able to search for these tables via universal search, and have these returned in the search results (i.e. this should not just be limited to those in the 'Administrator' group)

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

Metabase is running within **AWS Elastic Beanstalk** as reported.

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.171-105.231.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "redshift"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-10",
      "tag": "v0.35.2",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**

This is not a showstopper as a clear workaround of manually locating tables exists, but it does seem to affect all users who aren't admins (which of course, the majority will be in most deployments). 

**Additional context**

N/A

**Comment by camsaul** [comment]
Fixed by #13106
