### ISSUE TITLE
Not possible to view or restore a table after setting Visibility to "Hidden" in Data Model

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12344]
**Describe the bug**
After setting a table Visibility to "Hidden", and refreshing the browser page, then the table is not listed in "Hidden Table"-section of the table list anymore, so it's not possible to restore it.
Used to work in 0.34.3

**Workaround:**
1. Go to "Browse Data" > (database), which still lists the table (#9759). Copy the URL by hovering the book-icon "Learn about this table" (example `/reference/databases/4/tables/13`), change the URL to go to the Data Model of that table (example `/admin/datamodel/database/4/table/13`) and click "Queryable" in Visibility to show the table again, or
2. Manually change the metadata `metabase_table.visibility_type=null`

**Logs**
There's no errors.
`GET /api/table` isn't called anymore (probably since #12025). Now only `GET /api/database/:id/metadata` is called, which contains the hidden table. Seems like a FE issue, not BE like #10297.

**To Reproduce**
1. Go to Admin > Data Model > Sample Dataset
2. Select table Reviews
3. Click "Hidden" in Visibility at the top (doesn't matter if the "Why Hide?" options are selected)
4. Refresh browser page, now Reviews table is completely gone and not possible to view/restore it.

**Information about your Metabase Installation:**
Metabase 0.35.0, 0.35.2, `master`

**Additional context**
Similar to #10297, which is specific to columns visibility.
Related to #9759.
Setting this as P2, since it's less likely to need to restore visibility of a table, and since it's easier to restore than #10297.

**Comment by paulrosenzweig** [comment]
Closed by #12355
