### ISSUE TITLE
Add the ability to register maps via the API

### ISSUE THREAD

**Issue by jrtapsell** [metabase/metabase#12342]
**Is your feature request related to a problem? Please describe.**
When provisioning an instance via the API, maps cannot be added.

**Describe the solution you'd like**
Maps should be able to be added via the API to allow setting up instances via the API.

**Describe alternatives you've considered**
The maps could be added by modifying the database directly, but that would be fragile and break when versions are updated.

**How important is this feature to you?**
This is a nice to have feature, but for now, direct database manipulation can be used instead.

**Additional context**
At the moment there is one documented geojson API definition:
- /api/geojson/
  > Fetch a custom GeoJSON file as defined in the custom-geojson setting. (This just acts as a simple proxy for the file specified for KEY).

  <https://www.metabase.com/docs/latest/api-documentation.html#get-apigeojsonkey>

**Comment by tlrobinson** [comment]
Pretty much anything that can be done via the UI should be possible through “the API”, it’s just not officially supported/documented. Take a look at the network requests that occur when adding a map.

**Comment by tlrobinson** [comment]
Specifically `PUT /api/settings/custom-geojson` I believe

**Comment by flamber** [comment]
Closing this in favor of #9033/#11440.
https://www.metabase.com/docs/latest/api-documentation.html#put-apisettingkey
