### ISSUE TITLE
Creating an alert always turns on email alerts, even when they are toggled off

### ISSUE THREAD

**Issue by nfm** [metabase/metabase#12349]
**Describe the bug**

When I attempt to set up a new alert, the toggle for email notifications defaults to on in the UI. Toggling this off and toggling on a Slack alert results in the following payload (which looks correct):

![image](https://user-images.githubusercontent.com/127960/79705418-fdd02b80-82f8-11ea-85b0-85c5686e0fcf.png)

However, the server does persist an email alert:

![image](https://user-images.githubusercontent.com/127960/79705479-307a2400-82f9-11ea-9816-afc751ef405d.png)

And the UI reflects this:

![image](https://user-images.githubusercontent.com/127960/79705504-438cf400-82f9-11ea-951d-f40aa095ed21.png)

**Logs**

I can provide more detail if necessary, just don't want to bother sanitizing logs if this is easily reproducible.

**To Reproduce**
1. Go to an existing saved question
2. Click on 'Get Alerts'
3. Toggle off the 'Email' alert
4. Toggle on a 'Slack' alert, and choose a channel
5. Click 'Done'

**Expected behavior**
Alert is created for Slack only, without email alerts enabled.

**Screenshots**
See above.

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1062-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.2",
      "date": "2020-04-10",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**

Low severity but presumably an easy bug to squash.

**Additional context**
nil

**Comment by flamber** [comment]
Reproduced on internal instance. When editing the alert afterwards, then it's possible to disable email alerts, so seems like it's only a problem when creating the alert.
