### ISSUE TITLE
bug about mysql create table #5073 still not fix in new build

### ISSUE THREAD

**Issue by catCokkie** [metabase/metabase#12340]
| com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'core_organization' already exists

**Comment by catCokkie** [comment]
Oracle linux Server release 6.7
mysql: 5.73
tried to run jar as command followed:
 java -jar -DMB_DB_TYPE=mysql -DMB_DB_DBNAME=metabase -DMB_DB_PORT=3306 -DMB_DB_USER=meta -DMB_DB_PASS=“Password” -DMB_DB_HOST=123.123.123.123 metabase.jar

**Comment by flamber** [comment]
Hi @catCokkie 
Please provide the information asked, when creating a new issue. I'm sure there's more errors that that.
There's no version of MySQL called `5.73` - there's one called `5.7.3` - Metabase requires `5.7.7`: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html#notes

**Comment by catCokkie** [comment]
sorry @flamber 
my mysql version is 5.7.2,I'll try to use 5.7.7 and 8.0.19 to run  the jar again,if there's nothing wrong with these two version
 well ,maybe just all caused by the wrong version mysql

**Comment by flamber** [comment]
@catCokkie 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And in the future, please provide more information. Closing this, since it's a troubleshooting problem.
