### ISSUE TITLE
All settings goes once Metabase is restarted

### ISSUE THREAD

**Issue by shailendraphonon** [metabase/metabase#12348]
**Describe the bug**
I have used JAR file to run on CentOS6. This is by using the command **java -jar metabase.jar** 
As soon as I restart the application using the same command, all database configurations, SMTP configuration, User configuration clears up. I get /setup page again.
Please suggest how to resolve this.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_171-b11",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_171",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.171-b11",
    "os.name": "Linux",
    "os.version": "2.6.32-504.8.1.el6.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.2",
      "date": "2020-04-10",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @shailendraphonon 
If you look in the log (Admin > Troubleshooting > Logs), then you'll probably see some warnings or errors during the startup, which could indicate that you're storing the H2 application database in a temporary location.
Make sure that you're storing the application database in location that is permanent, or even better migrate to a better database such as Postgres or MariaDB/MySQL:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by shailendraphonon** [comment]
> Hi @shailendraphonon
> If you look in the log (Admin > Troubleshooting > Logs), then you'll probably see some warnings or errors during the startup, which could indicate that you're storing the H2 application database in a temporary location.
> Make sure that you're storing the application database in location that is permanent, or even better migrate to a better database such as Postgres or MariaDB/MySQL:
> https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
> Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

Hi @flamber 
Thanks, integrated MySQl, worked fine. Thanks.
