### ISSUE TITLE
Missing functions for expressions

### ISSUE THREAD

**Issue by friendofasquid** [metabase/metabase#12363]
**Describe the bug**

When trying to create a custom column in the notebook, I don't see some functions, e.g. `Contains` which should be present according to the [docs](https://www.metabase.com/docs/v0.35.1/users-guide/expressions.html).

Running 0.35.1.

- Create a new notebook ('Ask Question')
- Select any database
- Select any table
- Select custom column icon
- Type "contains"; no autocomplete appears

**Expected behavior**

Expected to see more functions, including `contains`.

**Screenshots**

<img width="679" alt="Screen Shot 2020-04-21 at 12 30 07 pm" src="https://user-images.githubusercontent.com/80615/79818735-dac27c00-83cb-11ea-82c0-083c04531ed4.png">

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.152-127.182.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "presto",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-02",
      "tag": "v0.35.1",
      "branch": "release-0.35.x",
      "hash": "e67f169"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**

Medium.

We are trying this as a workaround to a pulse issue (https://github.com/metabase/metabase/issues/12330) with custom SQL, but cannot recreate the logic using workbooks. This is reasonably severe as the documentation doesn't match capability, but won't break any production reports because these functions can't be used.

**Comment by flamber** [comment]
Hi @friendofasquid 
But `contains()` is a filter expression, not a column expression, so that's why it's not available under Custom Column, and why there's no helper shown if you're writing that manually.

**Comment by friendofasquid** [comment]
Sorry. That makes sense.  I guess I'm surprised the same functions aren't available in all contexts.

Why the distinction between functions available for filtering and custom columns?

**Comment by flamber** [comment]
@friendofasquid How are you going to use `contains` in the context of a custom column? It's a question, just like `between`, so the only place I can see them used is in context of a filter.

**Comment by friendofasquid** [comment]
If you combine with `CASE` that you can put some logic that generates new columns.

`CASE(CONTAINS([a] , 'foo'), 'Foo', Contains([a], 'bar'), 'Bar')`

And I guess the second point is regarding documentation. In [the docs](https://www.metabase.com/docs/latest/users-guide/expressions.html), the heading is 

*List of all available functions for expressions*

and this looks like a combination of functions that are either available for generating custom columns, or filter expressions, but not necessarily both. Perhaps adding a new column to that table saying where they can be used would be help.

**Comment by flamber** [comment]
@friendofasquid Seems like it's actually possible to use it together with `case`. Example on Sample Dataset's Products:
`case(contains([Category], "Widget"), "Yes", "No")`
But `case` isn't listed as one of the available functions, but manually writing it will show a helper, and using `contains` inside of that also shows a helper.
#12268 was created, since the user experience could be enhanced. Upvote by clicking :+1: 
Reopening this, even though I think #12268 will cover it.

**Comment by friendofasquid** [comment]
Thanks. It does look to me like #12268 will cover it.
