### ISSUE TITLE
Dashboard "OR" for multiple series

### ISSUE THREAD

**Issue by k2xl** [metabase/metabase#12369]
In a dashboard, it'd be sweet if filters could be "OR" based to allow multiple series to show.

For example, I have a line chart (SUM(data)) and a dashboard filter for a Country. When adding filter for Canada and then another filter for US, it shows a line chart for SUM(data) where country=Canada or country=US

Would be nice to have the ability to do two line charts in this situation.

**Comment by flamber** [comment]
Hi @k2xl 
I'm inclined to close this, since it doesn't seem to have anything to do with dashboards, but with questions/querying.
And it's possible to do what you want if you use `GROUP BY` and [Field Filter](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type), example:
```
SELECT date_column, country_column, SUM(data_column)
WHERE {{country}}
GROUP BY date_column, country_column
```

**Comment by k2xl** [comment]
So when creating dashboards, you can add filters - those are the filters im referring to.

**Comment by flamber** [comment]
@k2xl I might completely misunderstand what you're trying to do. Can you explain with more details, perhaps add screenshots?
Using filters with multiple values (on dashboards or in questions) will create queries like:
`WHERE country IN ('Canada', 'US')`

**Comment by k2xl** [comment]
Let's say you put a line chart to show the sum of sales over time. You add a filter for salesperson on the dashboard.

You set it blank and it shows all sales from everyone.

You click on the filter and select Bob and click Add. The line graph shows Bob's sales. All good. 

You go back to the filter, and add Joe. Now you see the sum for Bob and Joe (in one line).

What I'm asking for is the ability to have two lines comparing Bob and Joe's sales.

**Comment by flamber** [comment]
@k2xl Okay, I understand now. It's not really specific to dashboards, it would be same behavior with filters in a question. You can get the results you want by doing a group by "salesperson".

What you're asking for wouldn't be possible to do only with filters - the query would need to be modified, so the results where grouped by the same column as the filtered (with some option to enable/disable this functionality?), and that would not be possible to do with Native questions.

I actually think #10751 is asking for something very similar.

**Comment by flamber** [comment]
Closing this in favor of #10751, since it sounds like that's what is being requested.

**Comment by flamber** [comment]
Actually, this is probably closer to #5346 - upvote by clicking :+1: on the first post
