### ISSUE TITLE
Drill-through from Pivot table doesn't change table format to raw

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12368]
**Describe the bug**
When doing a drill-through from a Pivot table, somehow the results of example "View these ..." are returned, but kept inside the same Pivot, which means it doesn't show the correct columns.

_It took a couple of times to reproduce this, so think it might be a race-condition or a state thing. When it started returning the correct result (I'm not sure why, just playing around with settings), then I had to open a new tab and follow every step to reproduce again._

**Logs**
No errors to do with this, as far as I can see.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Join table Products
3. Summarize by "Sum of Quantity", group by "Product->Category" and "Product->Vendor"
![image](https://user-images.githubusercontent.com/1447303/79890561-f3e52000-83ff-11ea-9780-d3d1dea2d55f.png)
4. (validation step, can be skipped) Try clicking the first row value `295` (Alfreda Konopelski II Group / Gadget) > View these Orders. This returns 91 orders in full result set, which is correct. Click browser back-button.
![image](https://user-images.githubusercontent.com/1447303/79892180-6d7e0d80-8402-11ea-9418-12f9b20e00da.png)
5. Go to visualization Settings, disable Pivot, click "Sum of Quantity" column :gear:, enable "mini bar chart", enable Pivot again. It should look like this:
![image](https://user-images.githubusercontent.com/1447303/79890746-3c044280-8400-11ea-8bb3-c7bca338013c.png)
6. Like step 4, click first row value `295` (Alfreda Konopelski II Group / Gadget) > View these Orders. Somehow the Pivot table stays instead of showing a regular table:
![image](https://user-images.githubusercontent.com/1447303/79891809-cbf6bc00-8401-11ea-8d67-7be97808457f.png)

**Expected behavior**
Expected full results in raw table format (similar to step 4).

**Information about your Metabase Installation:**
Metabase 1.34.3 and 0.35.2

**Additional context**
I'm not sure how important it is to enable "mini bar chart", but it seems to help triggering the issue.

**Comment by kamilmielnik** [comment]
We should do this after the drill i migrated to MLv2 (see [Slack](https://metaboat.slack.com/archives/C0645JP1W81/p1699622956049349?thread_ts=1699622902.041679&cid=C0645JP1W81))

**Comment by ranquild** [comment]
"View underlying records" drill isn't migrated yet, postponing the fix

**Comment by kamilmielnik** [comment]
Reproducible in `master` at a926009707.
Assigning to QP team.
