### ISSUE TITLE
Regression with URL links

### ISSUE THREAD

**Issue by mfeckie** [metabase/metabase#12366]
**Describe the bug**
Previously when URLs were rendered in results the default behaviour on clicking was to open in a new window / tab.

When we updated to the latest metabase version we find that URLs are visited in the same tab.

**Logs**
N/a

**To Reproduce**
Click a URL in query results

**Expected behavior**
To open in a new tab / window

**Screenshots**
N/a

**Information about your Metabase Installation:**
N/a

**Severity**
Minor

**Additional context**

Previously this line https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/ExternalLink.jsx#L15 used to be  `target="_blank"`, in this new change it looks like this is now delegated to PLUGIN_FORMATTING_HELPERS

The previous target value is not present in the PLUGIN_FORMATTING_HELPERS https://github.com/metabase/metabase/blob/master/frontend/src/metabase/plugins/index.js#L52-L56

I'd be happy to submit a PR if this is something that is welcome.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related #10370
