### ISSUE TITLE
Login wouldn't stick on Kubernetes

### ISSUE THREAD

**Issue by Zonalds** [metabase/metabase#12374]
**Describe the bug**

I would deploy Metabase using the docker image on metabase/metabase but somehow the logins wouldn't stick. After creating an account, it wouldn't remember my password or the user anymore. Then I have to start all over again.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:** K8s using docker image.

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …) **Chrome**
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …) **K8s, Debian 9**
- Your databases: (e.x. MySQL, Postgres, MongoDB, …) 
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …) **K8s using the docker image.**
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Hi @Zonalds 
Without more information it's impossible to know what's going on. Make sure you're not using H2 for the application database, and if you are using H2, then make sure you're saving it on a volume.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by Zonalds** [comment]
@flamber Thank you for your response. I don't really know how to verify if I am using H2 or not. 
Here are the steps I took to set up Metabase, you might be able to figure out where I went wrong from here:

1. I pushed the image into my GCP registry and exposed it through port 3000 on GKE.
Upon testing, the login would not hold. Each time I log out, it will not recognize the login details anymore. In some cases, it wouldn't even load the /auth/login/. Instead, it shows the getting started. I had to recreate the login and completely the onboarding again. The entire cycle continues.

The commands were:
`docker pull metabase/metabase`
`docker run -d -p 3000:3000 --name metabase metabase/metabase`

2. When these failed I deployed it using **docker commit**  image of a running container. The argument was to use the instruction here:

> NOTE: this will run Metabase without any persistent storage for the application. if you plan to run Metabase continually we recommend establishing a way to keep the application data outside of the docker container

> 

So I used:
 **docker run -d -p 3000:3000 \
-v ~/metabase-data:/metabase-data \
-e "MB_DB_FILE=/metabase-data/metabase.db" \
--name metabase metabase/metabase**

to set up the container and then commit the container into an image. These still failed.

What could I possibly be doing wrong?

**Comment by flamber** [comment]
@Zonalds 
You are using H2, so you should use Postgres or MySQL instead. Have a look at the documentation:
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-kubernetes.html
And please use the forum for questions and troubleshooting: https://discourse.metabase.com/
