### ISSUE TITLE
Session timestamps are created for UTC but validated against provided "user.timezone"

### ISSUE THREAD

**Issue by kanchev** [metabase/metabase#12379]
**Describe the bug**
When logging in to metabase the user credentials are provided via the /api/session rest endpoint. The backend will authenticate the user, create an entry in the core_session and return a sessionId. Afterwards the frontend will use the sessionId to fetch the user's information via the /api/user/current rest endpoint. The backend will always validate the session if it has already expired and if so it'll simply return 401 Unauthorized.

With metabase v0.34.0 there was a huge rework of the time zone logic (see #11308). It seems that sessions are always created using the default UTC time zone but validated against user provided "-Duser.timezone=" parameter. In our case we had set the MAX_SESSION_AGE=120 (2h) with "-Duser.timezone=Europe/Berlin" which resulted in our sessions always marked as "expired", so that nobody (even the admin user) was being able to login to metabase.

**To Reproduce**
1. Create empty db schema for metabase (in our case PostgreSQL >= 9.5)
2. Start metabase >= v0.34.0 (also latest v0.35.3) with MAX_SESSION_AGE=120 and -Duser.timezone=Europe/Berlin (in our case we're using the docker image from hub.docker.com)
3. Open the metabase URL, e.g. http://localhost:3000/setup/
4. Enter the admin user information
5. As soon as you finish the initial wizard and click on the "Take me to Metabase" button you'll be redirected to the "Sign in to Metabase" page. Also providing the admin credentials again you'll still stay on the same page.  Chrome's DevTools will show you that /api/session was successful but  /api/user/current failed with 401 and the following message will be logged: "Failed to load resource: the server responded with a status of 401 (Unauthorized)".

**Expected behavior**
After clicking on the "Take me to Metabase" button the home page should be displayed and the user should be logged in.

**Screenshots**

**Information about your Metabase Installation:**
- Your browser and the version: Google Chrome 81.0.4044.113
- Your operating system: Windows 10.0.18363.778, with 
- Your databases: PostgreSQL 9.5 (also tested under v11)
- Metabase version: v0.34.0 up to v0.35.3
- Metabase hosting environment: Docker Desktop 2.2.0.5 (43884) stable, also OpenShift 3.11
- Metabase internal database: PostgreSQL 9.5 (also tested under v11)

**Severity**
It was a very severe issue for us since suddenly nobody was able to login anymore and we couldn't downgrade to a previous version. We upgraded the docker image at the beginning of march to v0.34.0 and everything was working normal until around the end of march. We assume that this was due to the switching from winter time to summer time, afterwards everybody was "locked out". 

**Workaround**
For everybody looking for a quick workaround, simply increase the MAX_SESSION_AGE or remove it from your metabase parameters.

**Comment by flamber** [comment]
@kanchev Nice detailed write-up + workaround :+1:

**Comment by camsaul** [comment]
we should just change the column in the application DB from `DATETIME` to `TIMESTAMP WITH TIME ZONE` (or `TIMESTAMP(3)` or `TIMESTAMP(6)` for MySQL/MariaDB)

**Comment by noahmoss** [comment]
Was already fixed by #12541
