### ISSUE TITLE
Metabase Prometheus Exporter

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#12377]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it has some problem monitoring Metabase as a platform, with queries, access, errors.

**Describe the solution you'd like**
Create an endpoint for export metrics.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by luizsfer** [comment]
Is there a point on the Roadmap for this new feature?

**Comment by Onlinehead** [comment]
That is another possible implementation which also can be helpful - https://github.com/clj-commons/iapetos (actually, that is a Clojure wrapper around the official library).

**Comment by paoliniluis** [comment]
mostly sure this other issue lands into this territory: https://github.com/metabase/metabase/issues/22566

**Comment by ranquild** [comment]
Resolved by https://github.com/metabase/metabase/pull/25149
