### ISSUE TITLE
Can not connect to MongoDB on cloud from metabase (Add Database form). But connect successed by MongoDb Compass with the same connection string.

### ISSUE THREAD

**Issue by thienanlktl** [metabase/metabase#12376]
Hi Team,

I want to add new database in Metabase with data type is MongoDb (MongoDb is on cloud). The connection string on cloud below:

<img width="393" alt="setuponclound" src="https://user-images.githubusercontent.com/28398033/79991829-efdb0000-84dc-11ea-8faa-1084ad5f3b83.PNG">

And this is my set up on Add Database form in Metabase:

![failedconnection](https://user-images.githubusercontent.com/28398033/79989686-57dc1700-84da-11ea-90d1-fcfc43d4e899.png)

I use above config connection for connect to MongoDb but i get the error:

<img width="406" alt="error" src="https://user-images.githubusercontent.com/28398033/79989809-7e9a4d80-84da-11ea-9443-828c9e93ba90.PNG">

But with the same connection string config i can connect successful by MongoDb Compass.

- This is config on MonggoDB Compass:
![successcompass](https://user-images.githubusercontent.com/28398033/79989937-a2f62a00-84da-11ea-91de-58b3f4cfbc05.png)

- This is when connected:

![connected](https://user-images.githubusercontent.com/28398033/79990583-6e36a280-84db-11ea-81c9-98d377d57db8.png)

*Note : i followed very strictly Metabase's document : [https://www.metabase.com/docs/latest/administration-guide/databases/mongodb.html](url) but i can not add new database.

Do someone know how to fix this issue?
Please help!

Thanks in advance!

**Comment by flamber** [comment]
Hi @thienanlktl 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It would be help if you added "Diagnostic Info" from Admin > Troubleshooting. And checked the log for more details in Admin > Troubleshooting > Logs.
