### ISSUE TITLE
Cannot view/edit table-level permissions for databases that are not schema-based

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12372]
**Describe the bug**
This is another round of #12269, which fixed so it's possible to click "View tables" on the left, but clicking the squares and selecting "Limit access" in the dropdown breaks the interface.

EDIT: But when accessing via "View tables", then clicking the table squares and selecting "Grant unrestricted access" (and OK), then nothing happens.

**To Reproduce**
1. Go to Admin > Permissions
2. Click on the squares for a non-schema-based database (like MySQL) and select "Limit access"
3. The URL is changed to `/admin/permissions/databases/11/schemas/null/tables`, but the interface freezes and needs a browser refresh to make it work again.

Cannot change table permissions:
1. Go to Admin > Permissions
2. Click "View tables" for a non-schema-based database (like MySQL)
3. Clicking a table-square to "Grant unrestricted access", and OK, nothing happens, but the "Save changes" becomes active, but is also empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/1447303/79966270-7d8eff00-848d-11ea-8f87-e419c3f8e60b.png)

**Information about your Metabase Installation:**
Metabase 0.35.3

Currently the only workaround is to downgrade to 0.34.3 (remember to backup first!)

**Comment by paulrosenzweig** [comment]
Fixed in #12404
