### ISSUE TITLE
BigQuery filter by "current day" (today) showing items from yesterday

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#12380]
**Describe the bug**
If I set my filter to to be "today" (Today is the 22nd), it will show results from yesterday:
![image](https://user-images.githubusercontent.com/113870/80020506-c8654280-849e-11ea-8120-f5ad63635e82.png)

You can see in the image above that its set for "today" (today is the 22nd) and that it is showing items from the 21st (yesterday).

If I were to filter on April 22nd, it shows the correct results:
![image](https://user-images.githubusercontent.com/113870/80020620-f5b1f080-849e-11ea-90c0-3e86b60b6347.png)

**To Reproduce**
1. Create a new question
2. Use a  BigQuery database
3. filter by a column that has dates, filter by "current" "day"
4. See its displaying stuff from yesterday.

**Expected behavior**
I expect it to show only items with the current day (April 22nd) not items in the 24 hour period.

**Screenshots**

**Information about your Metabase Installation:**
You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: Windows 10, Chrome
- Your databases: Big Query
- Metabase version:v 0.35.3
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
This is annoying, causes users to not trust the data.

**Comment by that0n3guy** [comment]
After some more testing, maybe this has to do w/ bigquery timezone stuff... I don't know.   

If I run `SELECT CURRENT_DATE()` on a mysql db, I get April 22nd.   If I run `SELECT CURRENT_DATE()` on bigquery db, it shows April 21st...

**Comment by that0n3guy** [comment]
I do not have this on in my bigquery db:
![image](https://user-images.githubusercontent.com/113870/80022457-b46f1000-84a1-11ea-805d-18b8bd8e5b9e.png)

**Comment by that0n3guy** [comment]
I have my java_timezone set on my docker container env vars: 
![image](https://user-images.githubusercontent.com/113870/80022842-40813780-84a2-11ea-9798-7e228dfad495.png)

**Comment by flamber** [comment]
@that0n3guy 
Did this use to work in previous versions or have this always been a problem?
Can you post "Diagnostic Info" from Admin > Troubleshooting?
It sounds related to #11819 and #7435.

**Comment by that0n3guy** [comment]
We've just started using BigQuery this week so i can't say if it worked before.   We have always use mysql before.


Diagnostic info: 
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.4.0-1047-aws",
    "user.language": "en",
    "user.timezone": "US/Central"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres",
      "redshift",
      "googleanalytics",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.23-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "US/Central"
    }
  }
}
```

**Comment by that0n3guy** [comment]
Just for some more info.   If I do:
![image](https://user-images.githubusercontent.com/113870/80029652-b7bbc900-84ac-11ea-8181-031c028aa747.png)

My current time: 
![image](https://user-images.githubusercontent.com/113870/80029691-bf7b6d80-84ac-11ea-93ce-756fae8756b0.png)


If I change this to ON:
![image](https://user-images.githubusercontent.com/113870/80029744-d752f180-84ac-11ea-83a4-e48602259f32.png)

Then my same query shows: 
![image](https://user-images.githubusercontent.com/113870/80029796-e6d23a80-84ac-11ea-8749-04407e02de0b.png)

**Comment by that0n3guy** [comment]
Using some ETL I dumped the exact same data into postgres.    The "current day"  works fine pulling from postgres.

So it seems like a bigquery issue.

**Comment by that0n3guy** [comment]
Ok I think I figured out the issue.   In BigQuery, the "today" is searching by UTC, but the dates displaying are in my Metabase set (REPORT TIMEZONE) timezone of CST.

Does that make sense?

**Comment by georgetam** [comment]
> Ok I think I figured out the issue. In BigQuery, the "today" is searching by UTC, but the dates displaying are in my Metabase set (REPORT TIMEZONE) timezone of CST.
> 
> Does that make sense?

Have you found any solution/ workaround? I'm stuck with the same issue.

**Comment by that0n3guy** [comment]
> Have you found any solution/ workaround? I'm stuck with the same issue.

@georgetam Nope.   I just gave up on bigquery for the moment (because of this metabase issue).  Using a different DB for now.
