### ISSUE TITLE
Update Slack implementation from Bot to App

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#12383]
**Is your feature request related to a problem? Please describe.**
Slack has made the move more towards apps than bots. This appears to be largely due to their old "bot" implementation requiring global permissions and new apps are more appropriately scoped. The current bot implementation is not deprecated, but we don't know if or when it will be.

From https://api.slack.com/authentication/quickstart
 > You can now select individual scopes for your bot token, rather than just one umbrella [`bot scope`](https://api.slack.com/scopes/bot) that grants access to many methods, some of which you may not need.

![image](https://user-images.githubusercontent.com/1512/80044300-ec358200-84b8-11ea-98aa-76f2cfc5e0c6.png)

**Describe the solution you'd like**
Option 1: Update our documentation to reflect the current best practice approach
Option 2: Overhaul our Slack implementation to use a proper "App"

**How important is this feature to you?**
Slack is an important way that folks share Metabase questions.

**Additional context**
Discovered while looking into #12382 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by dacort** [comment]
Enumerating the methods we currently use and their docs/deprecation status based on [slack.clj](https://github.com/metabase/metabase/blob/abfccb26bb3f08ef46993e5d38e17a8ed87e32d7/src/metabase/integrations/slack.clj):

Method | Scope | Deprecated?
------------ | ------------- | ------
[`channels.list`](https://api.slack.com/methods/channels.list) | `channels:read` | Y
[`users.list`](https://api.slack.com/methods/users.list) | `users.read` | N
[`files.upload`](https://api.slack.com/methods/files.upload) | `files:write` | N
[`chat.postMessage`](https://api.slack.com/methods/chat.postMessage) | `chat:write` | N
[`rtm.start`](https://api.slack.com/methods/rtm.start)(?) | `bot` (classic) | Y

That said, I created a new Bot app and added the necessary scopes and images and the MetaBot avatar aren't getting set properly.

**Comment by matthewlent** [comment]
@dacort nit `users:read`

**Comment by ctivanovich** [comment]
I'm attempting to set this up now at my organization--is it still a requirement that the API be set-up specifically for a channel called `metabase_files`?

**Comment by dacort** [comment]
> is it still a requirement that the API be set-up specifically for a channel called `metabase_files`?

Yes, although it can be archived if you like. Note that you still need to create a “bot” user and not an app.

**Comment by ctivanovich** [comment]
@dacort Hmmm, i've done that, and yet, the bot is unresponsive and silently fails to send a test Pulse.

**Comment by ctivanovich** [comment]
> > is it still a requirement that the API be set-up specifically for a channel called `metabase_files`?
> 
> Yes, although it can be archived if you like. Note that you still need to create a “bot” user and not an app.

Also, this is a bit misleading. I think what you mean is you must create an app, and a bot user for that app. There is no "just a bot user" option anymore, everything is encapsulated in the Slack API app service now.

**Comment by dacort** [comment]
@ctivanovich Please take a look at the workaround in #12382 - we're still using the "bot" user in Slack and have not migrated to proper apps yet. You can still create a bot user using the link in that ticket.

This ticket is for researching what the required permissions are to move to an app.

**Comment by manghat** [comment]
It would also be great if metabot could send files into private channels.

**Comment by flamber** [comment]
@manghat I think you're looking for #2694 / #3949

**Comment by nmuldoon** [comment]
We just received a notification (below) from Slack that the API used by the Metabase Bot will be deprecated on 24th February 2021. Rewriting the bot as an app before then would be greatly appreciated.

> The Conversations API  is a one-size-fits-all replacement for a variety of APIs that are used  to read and write information about channels, private channels, direct  messages and multi-party direct messages. On 24th February 2021, Slack  will end support for any methods preceding the Conversations API. We’ve detected that your organisation has created Slack apps using  these legacy methods. If users expect your app to work in channels of  any kind, you’ll need to verify use of the Conversations API by  following these suggested next steps.

**Comment by dacort** [comment]
@nmuldoon Thanks for the notice, Slack integration is certainly critical so will address this in an upcoming release.

**Comment by camsaul** [comment]
We don't use `channels.list` anymore -- I fixed this in #12921

**Comment by Limess** [comment]
The date above rapidly approaching, are there still plans to address this before then?

**Comment by flamber** [comment]
@Limess Which date? Metabase has been using Conversations API since 0.36.0. Additional information would be appreciated.

**Comment by Limess** [comment]
Ah thanks, I didn't find it clear from the above that this was changed - if this is the case that's great.

As an aside, while re-adding metabot to our slack install, I tried creating a new Slack app, and adding the appropriate scopes - rather than using a bot integration, and received this error in the metabase logs:

```
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 2021-01-13 15:14:38,403 WARN integrations.slack :: {:error-code "not_allowed_token_type", :message "Slack API error: not_allowed_token_type", :response {:ok false, :error "not_allowed_token_type"}}
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$do_slack_request.invokeStatic(slack.clj:65) ~[metabase.jar:?]
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$do_slack_request.invoke(slack.clj:47) ~[metabase.jar:?]
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$GET.invokeStatic(slack.clj:70) ~[metabase.jar:?]
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$GET.doInvoke(slack.clj:67) ~[metabase.jar:?]
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$handle_error.invokeStatic(slack.clj:38) ~[metabase.jar:?]
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$handle_error.invoke(slack.clj:26) ~[metabase.jar:?]
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$handle_response.invokeStatic(slack.clj:45) ~[metabase.jar:?]
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$handle_response.invoke(slack.clj:40) ~[metabase.jar:?]
2021-01-13T15:14:38 - default/application/e8a68ad5714d4c84aa65355b47fd638a - 	at metabase.integrations.slack$do_slack_request.invokeStatic(slack.clj:63) ~[metabase.jar:?]
2021-01-13T15:19:23 - default/application/e8a68ad5714d4c84aa65355b47fd638a -  "api.slack$fn__71273$fn__71276.invoke(slack.clj:25)"
2021-01-13T15:19:23 - default/application/e8a68ad5714d4c84aa65355b47fd638a -  "api.slack$fn__71273.invokeStatic(slack.clj:21)"
2021-01-13T15:19:23 - default/application/e8a68ad5714d4c84aa65355b47fd638a -  "api.slack$fn__71273.invoke(slack.clj:13)"
2021-01-13T15:19:23 - default/application/e8a68ad5714d4c84aa65355b47fd638a -  "api.slack$fn__71273$fn__71276.invoke(slack.clj:25)"
2021-01-13T15:19:23 - default/application/e8a68ad5714d4c84aa65355b47fd638a -  "api.slack$fn__71273.invokeStatic(slack.clj:21)"
2021-01-13T15:19:23 - default/application/e8a68ad5714d4c84aa65355b47fd638a -  "api.slack$fn__71273.invoke(slack.clj:13)"
```

**Comment by flamber** [comment]
@Limess That's what this issue is - about updating Metabase to allow using the App instead of the Bot.

**Comment by cernael** [comment]
@flamber I just upgraded from 0.35.3 to 0.37.6, but I see no changes in the Slack integration, which I expected to do.

Do I understand correctly that, while the integration in Metabase has switched over to the Conversations API, there's still stuff in the Bots Slack app that allows use of the old API, and that's why it still shows up in the warnings in my Slack admin interface?

**Comment by flamber** [comment]
@cernael Metabase does not support App, only the Bot. That is what this issue is about. I don't know what warning you're seeing.

**Comment by cernael** [comment]
@flamber In my Slack admin page, Bots show up on this warning page. And Metabot is the only one we're using. As someone with very limited knowledge of how Slack apps in general, and the Bots app in particular, work, the warning here makes me a bit uneasy.

On reflection, it seems reasonable that the warning arises because some Bot, somewhere, still uses the deprecated API, and that the shutdown only will mean that that bot breaks. But it's not really clear that that is the case.
Slack could have been clearer by also breaking down the usage to the API tokens I have generated for Bots.
Metabase could have been clearer by including a more explicit mention of the switch to Conversations in the release notes for 0.36.0 - up until now the only mention of a fix I've found is your offhand comment above. I did just now go looking deeper, and while there is a mention of Slack in the 0.36.0 release notes, neither it nor the linked issues ever explicitly mention the Conversations API by name - it's only by digging into the code itself, in https://github.com/metabase/metabase/pull/12921 (which is not even the issue linked from the release notes), that I get solid hints that this is fixed. 
![bots](https://user-images.githubusercontent.com/4858696/105156787-94da4600-5b0c-11eb-908c-f8f89cecc17e.png)

**Comment by flamber** [comment]
@cernael If you have just upgraded, then you'll see MetaBot on that list - as it says:
> Apps listed here have used at least one of these deprecated APIs within the last 30 days.

While we are trying to become better at making release notes, in [0.36.0 release notes](https://github.com/metabase/metabase/releases/tag/v0.36.0) it links to the issue #12678 and was fixed by PR #12921.
Anyhow this is going way off-topic.

**Comment by easeev** [comment]
Looks like MetaBot is pretty much broken now (we're on v0.39.4) 🤕 

![image](https://user-images.githubusercontent.com/14873170/123504549-99db8c80-d68c-11eb-9d05-02d504c479cc.png)

**Comment by flamber** [comment]
@easeev Sounds like a completely different problem than this issue. I would recommend that you create a new issue.
Post "Diagnostic Info" from Admin > Troubleshooting.
And post the full stacktrace from Admin > Troubleshooting > Logs.

**Comment by easeev** [comment]
@flamber you are right. Described and resolved in https://github.com/metabase/metabase/issues/16791#issuecomment-869480594. Thanks!

**Comment by camsaul** [comment]
We're currently investigating this issue and should have a hotfix for it later today regardless of whether Slack fixes the upstream issue. We expect to ship the hotfix as a 0.40.3 release later today

**Comment by codyborn** [comment]
I've [received a notice](https://api.slack.com/changelog/2021-10-rtm-start-to-stop#:~:text=Beginning%20November%2030%2C%202021%2C%20newly%20created%20Slack%20apps%20will%20no,current%20response%20will%20completely%20retire.) that the metabase slack bot `rtm.start` functionality will be deprecated beginning November 30, 2021 for newly created connections. 
Is there an existing alternative to the Slack bot? Is there any ETA on the Slack app? Thanks!
