### ISSUE TITLE
Confirm navigation on unsaved changes

### ISSUE THREAD

**Issue by TheRusskiy** [metabase/metabase#12389]
**Is your feature request related to a problem? Please describe.**
A progress is often lost when you accidentally navigate to a different screen, especially on MacOS where you can accidentally swipe to a previous page.

**Describe the solution you'd like**
Set `window.onbeforeunload ` when there's unsaved progress.

**How important is this feature to you?**
I think that this simple feature can save hours of lost work over time.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @TheRusskiy 
Wouldn't you be able to swipe "back" and return to where you left off? I know that's not the case for dashboards, but there's an issue open on that already #10427 - upvote by clicking :+1: on the first post

**Comment by TheRusskiy** [comment]
@flamber sometimes it helps, other times for whatever reasons it's not possible. May be URL hash doesn't get updated due to some bug, I am not sure. I am aware that this feature exist but I still lost progress many times due to a swipe back.

**Comment by paoliniluis** [comment]
@cdeweyx can we close this one?

**Comment by TheRusskiy** [comment]
@paoliniluis I see that ti's working fine now, thank you!
