### ISSUE TITLE
Request to add *Updated timestamp* type to data model, or generic timestamp type

### ISSUE THREAD

**Issue by RoyHP** [metabase/metabase#12386]
**Is your feature request related to a problem? Please describe.**
We have updated_at timestamps in our database (we use Laravel's Eloquent ORM) and want to tell the data model tool that they are updated_at timestamps - and also just have the option of selecting a generic *timestamp* data type from the dropdown.

**Describe the solution you'd like**
As you can see in the screenshot below, in the "DATE AND TIME" list of data types, there are types for cancelation timestamp, creation, deletion, join, etc. but there is no *updated* timestamp type. Can this or a generic *timestamp* type be added to the dropdown/options?

**Describe alternatives you've considered**
Which of the other DATE AND TIME types should we use in this scenario? We're not sure how they affect the behavior of the application.

**How important is this feature to you?**
If we can use one of the other types in the DATE AND TIME options then it's not very important, but as I mentioned above we don't know what the affect is of using them in the rest of the platform. We think having a generic *timestamp* type could be useful too.

**Additional context**
<img width="1046" alt="Screen Shot 2020-04-23 at 11 34 41 AM" src="https://user-images.githubusercontent.com/1066439/80118788-e2faf280-8556-11ea-90a6-03cff8a495c2.png">

**Comment by flamber** [comment]
Hi @RoyHP 
The different types of timestamp is mainly used for x-rays, so if you're not using that, then you can probably get by with any of them. The Field Type is also used for formatting, so setting a wrong type can limit some options or show options that might lead to errors.
Also worth reading #9202

**Comment by RoyHP** [comment]
@flamber Thanks for this! We do think that Updated should be added - but is there a reason there is no generic/plain **timestamp** type?

**Comment by flamber** [comment]
@RoyHP From https://github.com/metabase/metabase/issues/9202#issuecomment-451308837:
> One of the explicit goals of the project is to capture as much type info as possible and use it in smart places. X-Rays is our first big attempt in this, but there will be more.
> 
> This is less "business types" and more semantic metadata, and deletion is definitely something we'd be interested in getting a grip on, and eg, automatically recognizing soft-deletes.

**Comment by dpsutton** [comment]
closed by PR: https://github.com/metabase/metabase/pull/13818
