### ISSUE TITLE
Whitelist a domain for CSS injection in Content Security Policy

### ISSUE THREAD

**Issue by ApoorvSaxena** [metabase/metabase#12399]
We have a use case, where we want to inject an external CSS in the page, and at present we're getting the error regarding Content Security Policy violation

```
Refused to load the stylesheet '<URL>' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' fonts.googleapis.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

Please share how to whitelist a domain in Content Security Policy of Metabase for the CSS injection use case.

**Comment by flamber** [comment]
Hi @ApoorvSaxena 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You can use a reverse-proxy to replace the CSP headers with your own.
