### ISSUE TITLE
Cannot use Custom Expression on boolean columns

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12393]
**Describe the bug**
The new [expressions](https://www.metabase.com/docs/latest/users-guide/expressions.html) in 0.35 doesn't allow `CountIf`/`Case` to be used on boolean columns.

**NOTE** There's a separate issue for being able to filter `null` values with Custom Expression - #12225

**To Reproduce**
_(Sample Dataset doesn't have a boolean field - #1681)_
1. Custom question > (table with boolean field)
2. Summarize > Custom Expression > formula `CountIf([bool_column] = true)`
3. Shows error `Unknown Field: true`

- Using `CountIf([bool_column] = "true")` does not show a formula error, but the query fails (depending on the database eg Postgres `ERROR: operator does not exist: boolean = character varying`)
- Using `CountIf([bool_column] = 1)` works for some databases (eg Redshift).

**Expected behavior**
Boolean should allow `true`/`false`

**Information about your Metabase Installation:**
Metabase 0.35.3

**Additional context**
Spinning this into it's own issue. Was one of the examples of #12268 before.
https://discourse.metabase.com/t/custom-expression-boolean-comparison/9827
Related to #5123

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mvtemple** [comment]
Hello, what's the update on this issue? This is something I need to use daily!

**Comment by jkeys089** [comment]
I hit this today and I found a workaround that seems to work (tested with BigQuery):
```
=concat([MyField], "") = "true"
```

**Comment by adjenks** [comment]
I wanted to do this, but could not
`=coalesce(my_field,true)`
> Unknown Field: true

**Comment by flamber** [comment]
Coming in 0.43

**Comment by henrik** [comment]
For future googlers – when used with Postgres (if that's relevant), we got a "Unknown Segment" error doing `case(my_bool, "foo", "bar")` but `case(my_bool = true, "foo", "bar")` seems to work as expected.
