### ISSUE TITLE
Changing shown table columns hides all Custom Columns

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12395]
**Describe the bug**
Changing included/selected/shown columns of a table makes Custom Columns disappear. It is possible to get regain them via visualization Settings and clicking the `+` under "More columns"

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Add a Custom Column
3. Click preview - shows all columns, including the Custom Column
4. Click the far-right Column and deselect "Created At" (or any column)
5. Visualize - missing "Created At", as expected, and the Custom Column
6. Restore: Click visualization Settings > under "More columns", click the `+` next to the Custom Column

**Expected behavior**
Custom Column shouldn't go missing, when changing visibility of other columns :-)

**Information about your Metabase Installation:**
Metabase 0.35.3 with various backends and databases

**Additional context**
Related to #12044

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by amir5121** [comment]
I still have this issue on version 0.42.4
