### ISSUE TITLE
Don't complain about API endpoints/schemas missing docstrings when running linters

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12417]
The docstrings for API endpoint schemas are used when generating the documentation for API endpoints. I set it up to complain if you don't add one:

```
04-28 14:15:59 WARN common.internal :: We don't have a nice error message for schema: (maybe {(named (cond-pre Keyword Str) "Keyword or string") Any})
```

I think these are configured to only show in `dev` or `test` run modes (but not `prod`). They probably don't need to be shown unless we're in `dev`. We should make sure linters run in `test` mode or give them their own run mode such as `lint`

**Comment by robdaemon** [comment]
Resolved in #12711
