### ISSUE TITLE
native support for postgres datetime types (with time zones?)

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1242]
when i tell metabase to use _UNIX Timestamp (seconds)_ for a postgres column of type `timestamp with time zone`, i get this error when i query it:

`ERROR: function to_timestamp(timestamp with time zone) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 656`

not sure if this is a bug or operator error or something in between. :P thanks in advance!

**Comment by salsakran** [comment]
The unix timestamp is meant to be used with fields that are integers that should be interepreted as unix timestamps.

`timestamp with time zone` fields don't need to be annotated.

**Comment by snarfed** [comment]
hi again! we came across this recently....we were hoping to sort a raw data query by a `timestamp with time zone` field. sort let us group by time periods like week, day, or hour, ie the rows were sorted down to those buckets, but not within. is there a way to sort absolutely by a `timestamp` field? or is that grouping just how sorting works?

cc @kurtosis-color. thanks in advance!
