### ISSUE TITLE
Conditional Formatting for Map Regions

### ISSUE THREAD

**Issue by chrispruitt** [metabase/metabase#12434]
**Is your feature request related to a problem? Please describe.**
Currently, you can only use one single color at different gradients to highlight regions on a map visualization.

**Describe the solution you'd like**
I would like to add conditional formatting controls of regions on a Map. This would look a lot like how you can change the background color of a row/cell in a table with the conditional formatting option. This would really help in a scenario where you are tracking economic comparisons. For instance, if a region is above a predefined average you could fill those regions with a green gradient range. If a region is below the predefined average, you could fill those with a red gradient. I would also like to consider the direction of the gradient by allowing it to be reversible to support the visual below.

**Describe alternatives you've considered**
Currently, we have two maps side by side (pictured below) to display regions in green and others in red. We use SQL to filter by a predefined limit. We have found no way to combine these two visuals with the current map options.

**How important is this feature to you?**
Very important. We have many dashboards that would benefit from this feature and it would greatly improve the visual aspect of our dashboards. I would love to collaborate and contribute with anyone that would also benefit from this feature.

**Additional context**
What we can currently do:
![Screen Shot 2020-04-30 at 2 43 56 PM](https://user-images.githubusercontent.com/7242712/80753711-579fd500-8af3-11ea-9421-4a5d20546920.png)
With this feature the above visual could be condensed to a single visual like this:
<img width="1127" alt="Screen Shot 2020-04-30 at 2 45 13 PM" src="https://user-images.githubusercontent.com/7242712/80753718-5a022f00-8af3-11ea-891d-6750e886ca6c.png">

**Comment by flamber** [comment]
Hi @chrispruitt 
It sounds very similar to #12410 (related to #9682), but I really like your mockup. If you agree it's a duplicate, then please close this and could you post a comment on the other issue with the image?

**Comment by chrispruitt** [comment]
@flamber, you are right, sorry about that. I missed that when looking through the issues. I'll close this issue and upvote the other. Thanks!
