### ISSUE TITLE
Cannot aggregate question with unix timestamp column that is converted/cast in Metabase

### ISSUE THREAD

**Issue by survivingwithandroid** [metabase/metabase#12430]
**Describe the bug**
operator does not exist: timestamp with time zone / integer Suggerimento: No operator matches the given name and argument type(s). You might need to add explicit type casts. This error happens when we try to sum two fields.

we are using Metabase that connects to PostgreSQL. After upgrading to the 0.35.3 version, we get the following error:

ERROR: operator does not exist: timestamp with time zone / integer Suggerimento: No operator matches the given name and argument type(s). You might need to add explicit type casts.

We have added a custom column that is a sum of two columns. The resulting query produced by Metabse is:
    
```
select
	to_timestamp(("source"."agg_event_timestamp" / 1000)) as "agg_event_timestamp",
	"source"."agg_sum_successcount" as "agg_sum_successcount",
	"source"."agg_sum_throttlecount" as "agg_sum_throttlecount",
	"source"."agg_sum_total" as "agg_sum_total"
from
	(
	select
		("public"."apim_reqcountagg_days"."agg_sum_successcount" + "public"."apim_reqcountagg_days"."agg_sum_throttlecount") as "agg_sum_total",
		to_timestamp(("public"."apim_reqcountagg_days"."agg_event_timestamp" / 1000)) as "agg_event_timestamp",
		"public"."apim_reqcountagg_days"."agg_sum_successcount" as "agg_sum_successcount",
		"public"."apim_reqcountagg_days"."agg_sum_throttlecount" as "agg_sum_throttlecount"
	from
		"public"."apim_reqcountagg_days") "source"
```

where agg_sum_total is the custom column. In our previous version (0.34.3), the query produced by Metabase was:

```
select
	to_timestamp(("public"."apim_reqcountagg_days"."agg_event_timestamp" / 1000)) as "agg_event_timestamp",
	"public"."apim_reqcountagg_days"."agg_sum_successcount" as "agg_sum_successcount",
	"public"."apim_reqcountagg_days"."agg_sum_throttlecount" as "agg_sum_throttlecount",
	("public"."apim_reqcountagg_days"."agg_sum_successcount" + "public"."apim_reqcountagg_days"."agg_sum_throttlecount") as "agg_sum_total"
from
	"public"."apim_reqcountagg_days"
```

the agg_event_timestamp is a int8 while we have mapped it in Metabase as  timestamp unix milliseconds.

**Expected behavior**
The result should be the custom field generated by added two other fields

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your databases: PostgreSQL 
- Metabase version: 0.35.3
- Metabase hosting environment: Ubuntu 16.04.3 LTS
- Metabase internal database: Postgress 10.8

**Severity**
This bug is impacting some dashboard we have created previsouly using the previous version

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by survivingwithandroid** [comment]
Do you have any updates regarding this problem?

**Comment by flamber** [comment]
@survivingwithandroid There's 1700+ other issues, so it would probably be faster if you downgraded or found a workaround.

**Comment by survivingwithandroid** [comment]
Thank you

**Comment by achilleasknkwiff** [comment]
The problem still exists for me in v0.40.1 (Built on 2021-07-14). I use the [metabase-athena-driver](https://github.com/dacort/metabase-athena-driver) in case that helps. 

Getting the same `'/' cannot be applied to timestamp, integer` error as described above by @flamber due to the outer casting.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Windows Server 2019",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-14",
      "tag": "v0.40.1",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
