### ISSUE TITLE
Some interface elements have disappeared

### ISSUE THREAD

**Issue by ralfeus** [metabase/metabase#12448]
**Describe the bug**
I use Firefox to access Metabase. Today the GUI lacks several elements: custom SQL query writing, summarizing etc.

If I open a private window it works fine. If I open Metabase in Chrome it works fine. 
I tried to:
- restart Metabase
- install latest version of Metabase
- log off and log on to Metabase
- restart Firefox
- clear cache and cookies at Firefox.

None of those helps.

**Logs**
Attached

[Javascript logs.txt](https://github.com/metabase/metabase/files/4567427/Javascript.logs.txt)
[Server logs.txt](https://github.com/metabase/metabase/files/4567428/Server.logs.txt)
**To Reproduce**
Nothing has been done to have this behavior. I just opened it in the morning same way as day before.

**Expected behavior**
Missing interface elements are in place.

**Screenshots**
Erroneous interface:
![image](https://user-images.githubusercontent.com/1980527/80860361-7626dd00-8c67-11ea-80e9-cb3a2dd948d0.png)
Expected interface:
![image](https://user-images.githubusercontent.com/1980527/80860381-96ef3280-8c67-11ea-802a-de46a1c7219d.png)

**Severity**
Blocking users

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "cs",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "5.3.0-46-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @ralfeus 
This first screenshot you show only happens, when the viewport is less than 628px (mobile-mode).
I guess you have some setting or addon in Firefox that is triggering this problem.
I cannot reproduce on 0.35.3 with Firefox 75.

**Comment by ralfeus** [comment]
Indeed it was one of add-ons - Avast SafePrice. 
Thank you for the tip
