### ISSUE TITLE
Filter box go off on right of viewport on mobile

### ISSUE THREAD

**Issue by ggentili** [metabase/metabase#12440]
## Describe the bug
We have a problem with filter box selection on mobile with small view port.
When you click on the filter, the box pop-up aligned off the left of viewport and is impossibile to view the list of possible selections.

## To Reproduce
Visit https://coronavirus.regione.umbria.it/comuni

## Expected behavior
The filter box align on the right of viewport.

## Screenshots
![image](https://user-images.githubusercontent.com/1447303/85567684-5e4d5300-b631-11ea-866d-391f5043f8f0.png)

## Information about your Metabase Installation:
Your browser : Chrome
Your operating system: Android 8.0.0
Your databases: Postgres
Metabase version: v0.35.3

## Severity
blocking the use of filter on mobile

**Comment by Sire** [comment]
Possible fix here: https://github.com/metabase/metabase/issues/12768

**Comment by losrebellos** [comment]
@flamber 

After trying to repro and also checked #12768, I don't think this issue applies anymore.

__Now__

![image](https://user-images.githubusercontent.com/348552/164741028-1375b65f-3ee6-4655-8776-adf924926309.png)
