### ISSUE TITLE
Wrong "Stunden Netto" When Person was in Sabbatical

### ISSUE THREAD

**Issue by JudithMBW** [metabase/metabase#12452]
**Describe the bug**
I attached two examples. From Kristin and me. There you can see clearly that during our Sabbatical time the "Stunden Netto" goes into the negativ, because the "Stunden Brutto" is 0 AND the vacation is set. So This makes a negativ "Stunden Netto" and in conclusion Metabase will calculate the total number of Overhours totally wrong. 

**To Reproduce**
1. Go to fMitarbeiterstunden
2. Set Filter to before today and "Judith Eckerle" or "Kristin Mühlhäuser"
3. Zusammenfassung: "Stunden Brutto" and "Stunden Netto"
4. Group the Zusammenfassung by month

**Screenshots**
![Bug Metabase Kristin](https://user-images.githubusercontent.com/64780914/80959148-7c9f8b00-8e06-11ea-9a98-872d5a187dd3.png)
![Bug-Metabas-Judith](https://user-images.githubusercontent.com/64780914/80959155-80cba880-8e06-11ea-8142-c5695a5e54e9.png)

**Comment by flamber** [comment]
Hi @JudithMBW 
Please post "Diagnostic Info" from Admin > Troubleshooting.
And attach the CSV download of the data for both, since we don't have access to your data, so it's possible to reproduce with your steps.

**Comment by JudithMBW** [comment]
Hello, sorry that was the wrong place to put this ticket. We have to solve this internally. 
Thank you
