### ISSUE TITLE
Pick a table for joins doesn't allow selecting schema

### ISSUE THREAD

**Issue by landreville** [metabase/metabase#12456]
**Describe the bug**
Creating a simple report and adding joins shows the "Pick a table" dropdown of databases and the schemas within. Clicking on any schema name does not go to the clicked schema. Instead it always goes to the first schema in the dropdown.

**Logs**

Does not cause any log output.

**To Reproduce**
1. Create simple question
2. Click on Join Data - > "Pick a Table" 
3. Click on schema in dropdown that is not the top one
4. Tables in top schema is displayed

**Expected behavior**
The dropdown should show the tables in the schema you clicked.

**Information about your Metabase Installation:**
Also tried with Chrome with same results.
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.4.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.1",
      "date": "2020-01-13",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Severity**
The simple question can't be used with multiple tables.

**Comment by flamber** [comment]
Hi @landreville 
It sounds like a duplicate of #11958 - can you reproduce this with latest release 0.35.3 too?

**Comment by landreville** [comment]
Yes, it definitely sounds like a duplicate.
