### ISSUE TITLE
Drill-through is broken on nested question on dashboard

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12455]
**Describe the bug**
This is close relative to #11807, but with a twist.
Drill-through actions on dashboard is not working on questions based on Saved Question, when arriving directly to dashboard (e.g. via email link) or refreshing browser (F5).
**Workaround** is to click the title of the question and then click the Back-browser-button :crying_cat_face:

**Logs**
When clicking to drill-through, nothing happens, but console logs this error:
```
Firefox: TypeError: this._query.table(...) is null

Chromium: TypeError: Cannot read property 'fields' of null
```

**To Reproduce**
1. Simple question > Sample Dataset > People
2. Filter by State=`CA`
3. Save question as "Q1"
4. Simple question > Saved Question > Q1
5. Summarize Count group by City
6. Save question as "Q2"
7. Add Q2 to dashboard and save
8. Browser refresh the dashboard
9. Try to drill-through Q2 card (nothing happens, but there's TypeError in console)
10. Click on Q2 card title, which goes to the question browser
11. Click Back-browser-button and try to drill-through Q2 card again, which now works

**Information about your Metabase Installation:**
Metabase 1.34.2 and 1.35.3, and 0.35.3 on multiple backends with various browsers

**Comment by paulrosenzweig** [comment]
Closed by #12734
