### ISSUE TITLE
SMTP Credentials invalid using AWS SES

### ISSUE THREAD

**Issue by toedio** [metabase/metabase#12466]
**Describe the bug**
I am trying to configure SMTP using AWS SWS. When I put credentials and click "save" metabase return "success" and test email work. But email notification not work and log ERROR 500.

If you put credentials, click save return success. But if you click it a second time show the message "535 Authentication Credentials Invalid" immediately appears.

**Logs**
`[5682a77d-dcb5-41e2-96a8-c5253bce80d3] 2020-04-19T00:36:27-03:00 ERROR metabase.middleware.log PUT /api/email 500 5,0 s (0 DB calls)
{:message "No matching clause: 535 Authentication Credentials Invalid\n",
:type java.lang.IllegalArgumentException,
:stacktrace
("--> api.email$humanize_error_messages.invokeStatic(email.clj:35)"
"api.email$humanize_error_messages.invoke(email.clj:26)"
"api.email$fn__54122.invokeStatic(email.clj:95)"
"api.email$fn__54122.invoke(email.clj:70)"
"middleware.auth$enforce_authentication$fn__66187.invoke(auth.clj:14)"
"routes$fn__67541$fn__67542.doInvoke(routes.clj:56)"
"middleware.exceptions$catch_uncaught_exceptions$fn__66286.invoke(exceptions.clj:97)"
"middleware.exceptions$catch_api_exceptions$fn__66283.invoke(exceptions.clj:85)"
"middleware.log$log_api_call$fn__67917$fn__67918.invoke(log.clj:178)"
"middleware.log$log_api_call$fn__67917.invoke(log.clj:172)"
"middleware.security$add_security_headers$fn__66249.invoke(security.clj:121)"
"middleware.json$wrap_json_body$fn__67622.invoke(json.clj:64)"
"middleware.json$wrap_streamed_json_response$fn__67640.invoke(json.clj:100)"
"middleware.misc$maybe_set_site_url$fn__67946.invoke(misc.clj:58)"
"middleware.session$bind_current_user$fn__62772$fn__62773.invoke(session.clj:209)"
"middleware.session$do_with_current_user.invokeStatic(session.clj:184)"
"middleware.session$do_with_current_user.invoke(session.clj:177)"
"middleware.session$bind_current_user$fn__62772.invoke(session.clj:208)"
"middleware.session$wrap_current_user_id$fn__62757.invoke(session.clj:161)"
"middleware.session$wrap_session_id$fn__62701.invoke(session.clj:125)"
"middleware.auth$wrap_api_key$fn__66195.invoke(auth.clj:27)"
"middleware.misc$bind_user_locale$fn__67949.invoke(misc.clj:74)"
"middleware.misc$add_content_type$fn__67932.invoke(misc.clj:29)"
"middleware.misc$disable_streaming_buffering$fn__67957.invoke(misc.clj:89)")}
`

**To Reproduce**
1. Go to Administrator
2. Put SMTP Credentials
3. Wait a email notification
4. Email is not sent

```
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-8u242-b08-1~deb9u1-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.9.0-12-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.3",
      "date": "2020-02-25",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
```

**Severity**
Blocking notifications feature

**Comment by flamber** [comment]
Hi @toedio 
Just to confirm: You're **not** using your AWS credentials, right?
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html
What happens if you use the exact same credentials with another SMTP client like Thunderbird?

**Comment by toedio** [comment]
Yes, I generated SMTP credentials. I dont test in other SMTP client

**Comment by flamber** [comment]
@toedio Okay. Can you please test with another SMTP client?

**Comment by toedio** [comment]
I tested and workin. PS. E-mails like send test verification or You set up an alert is working

**Comment by flamber** [comment]
@toedio I don't understand.
Please post "Diagnostic Info" from Admin > Troubleshooting.
Are you saying that it's working now? Then we can close this.
Or are you saying that some things are working, but others are failing? Please describe which are working and which are failing.

**Comment by toedio** [comment]
@flamber 
Its not working! Credentials work normally in other SMTP client. I observed that "Send test e-mail verification" work and I receive e-mail, but when metabase will send notifications scheduled show error message "535 Authentication Credentials Invalid" in log

**Comment by paoliniluis** [comment]
I just tested that this works without issues in latest Metabase version (39.4), the only change that needs to be done in SES for it to work is to move SES out of sandbox mode so AWS allows Metabase to send emails to non-verified accounts.

The credentials that you need to use the ones that IAM gives you by creating a programmatic user with the following policy (it's called AmazonSesSendingAccess):
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ses:SendRawEmail",
            "Resource": "*"
        }
    ]
}
```
