### ISSUE TITLE
The question took too long on versions v0.35.0 and above

### ISSUE THREAD

**Issue by avicenna13** [metabase/metabase#12460]
**Describe the bug**
There is a problem "The question took too long" on v0.35.0 and higher when accessing heavier queries, on v0.34.3 there is no such problem. There is nothing about it in the logs.

**Logs**
No messages

**Expected behavior**
Analytics should be uploaded

**Information about your Metabase Installation:**
- Your databases: PostgreSQL
- Metabase version: v0.35.0 and above
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL

**Severity**
It blocks the metabase update

**Comment by flamber** [comment]
Hi @avicenna13 
You need to adjust your proxy, so it doesn't close the connection. Have a look at #12423
