### ISSUE TITLE
Make the Time Picker use 24h if 24h clock is configured

### ISSUE THREAD

**Issue by viblo** [metabase/metabase#12472]
Currently (tested in v0.35.3 and earlier versions) when using the date & time picker the times are always in 12 hour format, regardless of what I have selected as time format in settings. 

For users not used to AM/PM this is quite confusing, especially when selecting times around 12AM & 12PM.  

Instead I would like to (and expect it) to follow what I have configured in the Admin. If that is tricky a alternative solution would be to let me toggle between 12/24h format in the time picker itself.

**Comment by flamber** [comment]
Very much related to #9151
