### ISSUE TITLE
Retry sending Pulse/Alert on error

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12487]
**Is your feature request related to a problem? Please describe.**
Currently if the SMTP configured or Slack is temporarily unreachable, then Pulses/Alerts will not be sent, which can have business impact.

**Describe the solution you'd like**
An option to retry for X times with Y (incremental) delay (+1 if configurable via env vars)
It should probably keep the data (the pulse/alert) in memory, and just retry with that, instead of doing a new query, which could give a different result and would also have a performance impact.

**Describe alternatives you've considered**
Setup a SMTP relay (eg Postfix), where Metabase would deliver the mail to the relay, and from there it would take care of queuing and proper delivery to the final SMTP, no matter if it was connectivity issues, temporary rate limiting or other things that would normally mean failure.
No alternative options for Slack.

**Additional context**
Related #12084 and #3732 and #8416

Partial trace, when Slack fails:
```
05-11 15:03:17 [1mERROR metabase.pulse [0m :: Error sending notification!
java.net.SocketTimeoutException: Read timed out at java.base/java.net.SocketInputStream.socketRead0(Native Method) at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115) at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168) at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140) at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448) at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1103) at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
...
```

**Comment by metamben** [comment]
In order to reduce the risk of blocking threads serving the UI for longer periods, we decided to restrict the retries to notifications (pulses, alerts) only. These are triggered from the backend except when testing the connection from the UI.
