### ISSUE TITLE
Provide column ordering / hiding options from table header dropdown

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#12494]
**Is your feature request related to a problem? Please describe.**
When working  with table questions with many columns (especially when a join is involved), it can be very frustrating to reorder the columns, or hide ones you don't want to see. This is partially because the existing interfaces don't work well with lots of columns, and partially because sometimes while dragging the question refreshes, or you trigger a browser back action on accident.

There are two existing ways to reorder the columns:
1. Drag up/down within the "settings" view of the table visualization
2. Drag left/right within the results view

And two ways to hide a column:
1. Uncheck it in the notebook question editor
2. Click X in the settings for the table visualization

**Describe the solution you'd like**
When you click a column header, there should be three additional options:
- move to front
- move to back
- hide column

**Describe alternatives you've considered**
Adding the same top/bottom actions to the visualization settings column order thing could also help but I think putting it in the visualization itself is always best and most friendly to non-technical users of metabase.

**How important is this feature to you?**
This is a common annoyance when working with large datasets but obviously not a show-stopping bug or UX problem. 

**Additional context**
This is the drop-down menu I referenced, in case it's not clear.
![image](https://user-images.githubusercontent.com/82608/81589872-c6402680-936e-11ea-9ed0-b0c5b59dfda1.png)

**Comment by mazameli** [comment]
The hide column action being in here is interesting, but do you think you'd need the reordering controls less if and when we allow admins to change the default table column order in the data model? I.e., https://github.com/metabase/metabase/issues/3720

**Comment by bcherry** [comment]
@mazameli #3720 is a great idea and would definitely solve some of the cases. But I frequently run into this problem when using joins, which that would only help a little bit.  I'm not sure how common my use case is, but I use metabase extensively for debugging and other exploration of production data. For example, sometimes I've got some business object with a bunch of fields, then I join it to users and want to pull the user's email all the way to the top-level report. Sometimes that email might be 30 or or 40 columns down in the table, especially if there's more than one external table referenced (and "Users" also tends to sort low alphabetically which is the default sort order for foreign-key associations without an explicit join, although #3720 could help that perhaps)

**Comment by flamber** [comment]
I'm sure #10460 would help a lot too.

**Comment by bcherry** [comment]
@flamber totally agree - I chose not to include complaints about that UI in this issue but I agree with everything mentioned in #10640

**Comment by npfitz** [comment]
Resolved in https://github.com/metabase/metabase/issues/33841
