### ISSUE TITLE
Create a monthly SaaS model to support faster development

### ISSUE THREAD

**Issue by rayventerprise** [metabase/metabase#12490]
**Is your feature request related to a problem? Please describe.**
Yes, great project potential but seems like slow development turnaround.

**Describe the solution you'd like**
Not sure if funding is the issue, but if so please consider adding a monthly subscription fee for small/medium-sized businesses to fund the developers who work on this, I would be willing to pay to see faster turnaround on development. Really good project!

**Comment by flamber** [comment]
Hi @rayventerprise 
Thank you for the kind words. Up until very recently the Metabase team was very small.
There's an Enterprise Edition, geared for larger companies: https://www.metabase.com/enterprise/
And then there's sponsorships: https://www.metabase.com/support/sponsorship/
But this isn't the right place for any such discussion - please use the forum https://discourse.metabase.com/ or https://www.metabase.com/contact/
