### ISSUE TITLE
There is no type `Other` when setting up Google oAuth credentials

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12491]
**Describe the bug**
I'm not sure what Google is doing, but something has changed, so `Other` is no longer an option in the "Application type" select of "Create a OAuth client ID", but it is still referenced in their docs.

Errors with `400: redirect_uri_mismatch: The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at`

**To Reproduce**
1. Go to Admin > Databases > Add database
2. Select "Google Analytics"
3. Click link to create Client ID: https://console.developers.google.com/apis/credentials/oauthclient
4. `Other` isn't listed:
![image](https://user-images.githubusercontent.com/1447303/81507750-af162000-92ff-11ea-8cfb-8a283f2e5db6.png)
5. It seems like `Desktop App` works (difficult to test because of #12411), but not sure if there will be consequences with that choice.

**Information about your Metabase Installation:**
Metabase 0.35.3

**Additional context**
https://discourse.metabase.com/t/connecting-google-analytics-there-is-no-type-other-when-setting-up-credentials/10084

**Comment by dacort** [comment]
Looks like this is an issue for our BigQuery docs as well per https://stackoverflow.com/questions/61692163/how-to-connect-metabase-to-google-bigquery

In that thread, `Desktop App` seemed to work as well.

**Comment by zasana** [comment]
I tried out `Desktop App` for the native Mac client and it works.

**Comment by kshivang** [comment]
I tried with Jar, ```Desktop App``` work fine there as well.

**Comment by ATL64** [comment]
Thanks zasana, been scratching my head for a while today with this one until Desktop App worked
