### ISSUE TITLE
A table with an existing SQL description does not get updated when it is sync'ed

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#12493]
**Describe the bug**
If a table has a metadata description field imported from the MySQL comment, and this MySQL comment is updated, the sync process does not update the description of the table.

**Logs**

The server logs show that the table was considered by the sync, yet in the reference data I still see the old description. For example, below the source table had its description change in the MySQL server, but the old one is still shown in Metabase.

```
05-11 15:39:20 INFO sync.util :: STARTING: step 'sync-tables' for mysql Database 9 'MyTableName'
05-11 15:39:20 INFO sync-metadata.tables :: Updating description for tables: (Table  'campaign' Table  'source' Table  'broadcast_link')  
05-11 15:39:20 INFO sync.util :: FINISHED: step 'sync-tables' for mysql Database 9 'MyTableName' (130.8 ms)
```

**To Reproduce**
1. Create a MySQL DB with a table and a comment associated to this table. E.g.
```
CREATE TABLE source (
  id INT NOT NULL AUTO_INCREMENT,
)
COMMENT = 'Initial comment';
```
2. Connect Metabase to this DB
3. Open the data reference, and see that the description of the table was set with the MySQL comment
4. Update the comment: `ALTER TABLE source COMMENT = 'A source is something with an id';`
5. Sync the DB in Metabase
6. Open the data reference, and see that the description of the table is still set with the old comment

**Expected behavior**
Since the description was not set by me but imported from the schema, I would like that a schema update also updates the description. I would also like the same behaviour for columns.

I can understand that this may not be possible without storing the fact that the description was not "manually" altered, because overwriting it may cause data loss. If storing this fact is not an option, I would at least expect that I can clear the field and have it reset by a new sync. This is currently not possible because of #11097, which you may therefore consider as duplicate.

**Information about your Metabase Installation:**

- Database: MySQL
- Metabase version: 0.33.6
- Metabase internal database: MySQL

**Severity**
This is annoying: the only way to update the description is a copy-paste. This is fine for a single table, less so for many tables, even less so if I am updating fields. In my case, I am documenting most tables and columns so that the description is useful for users, but many tables and columns have obscure comments  coming from the schema design stage.

**Comment by flamber** [comment]
Hi @rthouvenin 
Reproduced on 0.35.3 with MariaDB, but I'm guessing is relevant to all databases.
It seems like if a table does not have a description initially (`null`), then setting a comment and syncing will actually update the description, so guessing sync code checks for `null` before populating.
That means you should be able to remove all descriptions and then sync again, if you want the description to be reset to your table comment (I have not tested this):
```
UPDATE `metabase_table` SET `description`=null WHERE `db_id`=<your db id, which is 9>
```
_(as always, when messing with metadata, make sure you have a backup!)_

**Comment by rthouvenin** [comment]
Thanks for the tip @flamber, does work.

I can also confirm your guess, only nil descriptions are updated. This is what I found in the code:
```
(db/update-where! Table {:db_id       (u/get-id database)
                         :schema      schema
                         :name        table-name
                         :description nil}
                  :description description)
```

**Comment by sbelak** [comment]
Closing this in favour of #12574 as the latter is more comprehensive.
