### ISSUE TITLE
Pie chart sometimes does not show total

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#12506]
**Describe the bug**
Pie chart sometimes does not show total.

**Expected behavior**
pie chart sometimes does not show total, neither in the individual question nor when the question is on a panel. The total appears when you pass the mouse over the chart.

**Screenshots**
![pie_chart](https://user-images.githubusercontent.com/55719904/81631727-e90a2380-93de-11ea-8957-11fb737662ee.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
The error directly impacts the user experience. It is necessary to pass the mouse over the chart for it to work correctly.

**Comment by bjoernhasse** [comment]
Hi @tatusis, I think this has something to do with the size of the pie chart.
Try to make the chart wider. This should display the total sum.

**Comment by flamber** [comment]
Hi @tatusis 
Can you provide steps to reproduce? Preferably with Sample Dataset or static SQL

**Comment by tatusis** [comment]
Hi @flamber 

Follow the steps below:

- Select the products table from the sample dataset
- Summarize the number of lines grouped by categories

![pie_chart_example](https://user-images.githubusercontent.com/55719904/81702538-cb21da80-9441-11ea-9eae-3845f70827ca.png)

@bjoernhasse , I believe it is not the size of the chart, because the error does not appear only in the panel.

Thank you.

**Comment by tatusis** [comment]
Hi
I believe that this error below appears when the total is not displayed. Even when the total appears, it takes a long time. It should be fast, at least in the sample dataset. When the total appears this error below is not displayed.

![error](https://user-images.githubusercontent.com/55719904/81703675-4932b100-9443-11ea-8085-1e6696bf1793.png)

**Comment by flamber** [comment]
**Steps to reproduce**
1. Simple question > Sample Dataset > Products
2. Summarize Count by Category
3. Change visualization to Pie chart
4. Save question
5. Refresh browser (or go to the question from a collection/search), shows no total

Same behavior on the dashboard, so giving P2, since it makes Pie viz not very good - specially for non-interactive dashboards.
I don't know if the error is specific to this or something general about Pie:
`Invariant Violation: Minified React error #44; visit ...`
