### ISSUE TITLE
Nested queries using metric got wrong SQL

### ISSUE THREAD

**Issue by sunui** [metabase/metabase#12507]
**Describe the bug**
Nested queries using metric got error，I think Wrong SQL was generated

**Logs**
<details>
<summary>Logs</summary>
<pre><code>

05-12 16:44:17 INFO api.dataset :: Source query for this query is Card 1
05-12 16:44:17 INFO middleware.fetch-source-query :: Fetched source query from Card 1: 
 {:source-table 4, :aggregation [[:metric 1]], :breakout [[:field-id 31]]}

05-12 16:44:17 INFO middleware.fetch-source-query :: Fetched source query from Card 1: 
 {:source-table 4, :aggregation [[:metric 1]], :breakout [[:field-id 31]]}

05-12 16:44:17 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 1,
 :started_at (t/zoned-date-time "2020-05-12T16:44:17.560+08:00[Asia/Shanghai]"),
 :state "42S22",
 :json_query {:database 1, :query {:source-table "card__1", :limit 10}, :type "query", :parameters [], :middleware {:add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"count\" AS \"count\" FROM (SELECT \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", count(*) AS \"count\" FROM \"PUBLIC\".\"REVIEWS\" GROUP BY \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" ORDER BY \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" ASC) \"source\" WHERE \"source\".\"ID\" IS NOT NULL LIMIT 10",
  :params nil},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Comparison.optimize(Comparison.java:177)"
  "org.h2.command.dml.Select.prepare(Select.java:861)"
  "org.h2.command.Parser.prepareCommand(Parser.java:283)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1135)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)"
  "--> driver.sql_jdbc.execute$eval58653$fn__58654.invoke(execute.clj:239)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:257)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:254)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:387)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$eval58933$fn__58934.invoke(sql_jdbc.clj:50)"
  "driver.h2$eval83587$fn__83588.invoke(h2.clj:81)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__51336.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__50558.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__51535.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__55914.invoke(wrap_value_literals.clj:137)"
  "query_processor.middleware.annotate$add_column_info$fn__49069.invoke(annotate.clj:577)"
  "query_processor.middleware.permissions$check_query_permissions$fn__50417.invoke(permissions.clj:64)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__52072.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__50647.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__52646.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__48128.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.limit$limit$fn__51314.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__51287.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__50719.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__49629.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__50211.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__47640.invoke(add_dimension_projections.clj:272)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__47876.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__48291.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__52297.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__49262.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__50266.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__52048.invoke(parameters.clj:99)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__50320.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__50983.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48338.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__55746.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52314$fn__52318.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52314.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__51209.invoke(fetch_source_query.clj:261)"
  "query_processor.middleware.store$initialize_store$fn__55763$fn__55764.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__55763.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__50163.invoke(cache.clj:208)"
  "query_processor.middleware.validate$validate_query$fn__55780.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__51357.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48154.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__55725.invoke(results_metadata.clj:128)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__50582.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__52163.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__50511.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___47265$thunk__47266.invoke(reducible.clj:101)"
  "query_processor.reducible$async_qp$qp_STAR___47265.invoke(reducible.clj:107)"
  "query_processor$base_qp$fn__55923.doInvoke(query_processor.clj:105)"
  "query_processor.reducible$sync_qp$qp_STAR___47274$fn__47277.invoke(reducible.clj:133)"
  "query_processor.reducible$sync_qp$qp_STAR___47274.invoke(reducible.clj:132)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:216)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:212)"
  "query_processor$eval55960$process_query_and_save_execution_BANG___55969$fn__55972.invoke(query_processor.clj:228)"
  "query_processor$eval55960$process_query_and_save_execution_BANG___55969.invoke(query_processor.clj:220)"
  "query_processor$eval56004$process_query_and_save_with_max_results_constraints_BANG___56013$fn__56016.invoke(query_processor.clj:240)"
  "query_processor$eval56004$process_query_and_save_with_max_results_constraints_BANG___56013.invoke(query_processor.clj:233)"
  "api.dataset$fn__61399$fn__61402.invoke(dataset.clj:52)"
  "query_processor.streaming$streaming_response_STAR_$fn__42338$fn__42339.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__42338.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__29210.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error
 "Column \"source.ID\" not found; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 402e33e7d12193b1d07010be3e501a50b1d3fb8a319c0324060dec3007e6bc53\nSELECT \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"count\" AS \"count\" FROM (SELECT \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", count(*) AS \"count\" FROM \"PUBLIC\".\"REVIEWS\" GROUP BY \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" ORDER BY \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" ASC) \"source\" WHERE \"source\".\"ID\" IS NOT NULL LIMIT 10 [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 1,
  :query
  {:limit 10,
   :source-query
   {:source-table 4, :aggregation [[:aggregation-options [:count] {:display-name "count with filter metrix", :name "count"}]], :breakout [[:field-id 31]], :order-by [[:asc [:field-id 31]]]},
   :source-metadata
   [{:base_type :type/Integer,
     :display_name "Product ID",
     :name "PRODUCT_ID",
     :description "The product the review was for",
     :special_type :type/FK,
     :fingerprint {:global {:distinct-count 176, :nil% 0.0}}}
    {:base_type :type/BigInteger,
     :display_name "count with filter metrix",
     :name "count",
     :special_type :type/Quantity,
     :fingerprint
     {:global {:distinct-count 16, :nil% 0.0}, :type {:type/Number {:min 1.0, :max 18.0, :avg 6.318181818181818, :sd 3.427770469213245, :q1 3.9279534881100586, :q3 8.082762530298218}}}}],
   :filter [:!= [:field-id 32] [:value nil {:base_type :type/BigInteger, :special_type :type/PK, :database_type "BIGINT", :name "ID"}]],
   :fields [[:field-literal "PRODUCT_ID" :type/Integer] [:field-literal "count" :type/BigInteger]]},
  :type :query,
  :middleware {:add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id 1,
   :nested? true,
   :query-hash [64, 46, 51, -25, -47, 33, -109, -79, -48, 112, 16, -66, 62, 80, 26, 80, -79, -45, -5, -118, 49, -100, 3, 36, 6, 13, -20, 48, 7, -26, -68, 83]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}
</code></pre>
</details>

**To Reproduce**
1. Add a metric  with filters
![image](https://user-images.githubusercontent.com/15194498/81665024-c45f8b80-9472-11ea-9672-5e2d70e20a9f.png)

2. Add a question , got right result , save the question
![image](https://user-images.githubusercontent.com/15194498/81665180-fec92880-9472-11ea-8168-b8a84c0365eb.png)

3. Add a new Nested question using the question in previous step ,just run it , got error
![image](https://user-images.githubusercontent.com/15194498/81665838-ce35be80-9473-11ea-8c93-466e27677f34.png)

this is the SQL for this question , I think the outer query filter got wrong position
![image](https://user-images.githubusercontent.com/15194498/81666205-51efab00-9474-11ea-8da0-3a8e4137d6b3.png)

And I have learnt about source code in `src/metabase/query_processor/middleware/expand_macros.clj`, ,I think the `add-metrics-filters` function put the `filters`  in  `metric-id->info` to `outer-query` instead of `inner-query`,maybe

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4136.5 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_131-b11",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_131",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.131-b11",
    "os.name": "Mac OS X",
    "os.version": "10.15.4",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "tag": "v0.35.2",
      "hash": "dd09386",
      "branch": "master",
      "date": "2020-05-11"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Related to #8621 and #10474
