### ISSUE TITLE
Fingerprinting breaks on infinities

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#12511]
If data contains infinities, fingerprinting breaks, because the underlying histogram data structure does not know how to calculate the mean and variance in such case. I see 3 possibilities:
1) omit infinite data points from the calculation;
2) don't calculate mean and var in such cases;
3) set mean and var to infinity (mathematically correct)

As a user I think I'd usually want 1), but I can see an argument for absolute correctness. I think 3) is strictly better than 2) as 3) makes it more unambiguous what's going on.

Thoughts @dacort, @salsakran?

**Comment by dacort** [comment]
Do you have a real-world example of this? I'm having trouble understanding how it would come up during fingerprinting.

**Comment by dacort** [comment]
> For example, a database view that includes a calculation of two float fields can result in an infinity value.
I feel like infinity should be treated as a discrete value, ignored for the mean and variance, but included in a resulting chart.
