### ISSUE TITLE
Query results_metadata coming back with columns that don't exist

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12519]
This is on stats (0.35.2). This is sort of a big issue because the `results_metadata` is used when using that query as a source query -- all queries using it as a source will be broken because they'll attempt to `SELECT` columns that don't exist.

Check out the API response in 

`<stats>/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjF9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319`

**Comment by flamber** [comment]
Unless I'm misunderstanding this, isn't it because of "Display values"="Use foreign key"? #10474

**Comment by sbelak** [comment]
You are correct.
