### ISSUE TITLE
Pulse bar charts look wrong in Slack

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#12526]
Bar charts in the pulse creation preview and in emails look right:

![image](https://user-images.githubusercontent.com/2223916/81836569-7c834780-94f8-11ea-9a13-6d44d8c1c493.png)

![image](https://user-images.githubusercontent.com/2223916/81836477-61b0d300-94f8-11ea-8e65-5ee97f534966.png)

But in Slack, the bars are aligned to the top incorrectly, the rows are missing dividing lines, and the top row is too close to the top:

![image](https://user-images.githubusercontent.com/2223916/81836440-5493e400-94f8-11ea-88ab-4d38fc7ab477.png)

**Comment by mazameli** [comment]
Tried futzing with this for a bit, but the code it turns out is a bit byzantine for me. I think I narrowed the problem down to something in `/src/metabase/pulse/render/table.clj`:

```clojure
(when bar-width
        [:td {:style (style/style (bar-td-style) {:width :99%})}
         [:div {:style (style/style {:background-color (style/primary-color)
                                     :max-height       :10px
                                     :height           :10px
                                     :border-radius    :2px
                                     :width            (str bar-width "%")})}
          "&#160;"]])])])
```

I tried adding `:vertical-align :middle` but it didn't seem to do the trick, and trying to add manual vertical margin caused the bars to be misaligned in the pulse edit/creation preview. 

The real problem seems to be a discrepancy in how these bar cards are rendered when they're converted to PNGs.

**Comment by tsmacdonald** [comment]
I poked around with it a little and agree with @mazameli. The issue seems to be with CSSBox as the same HTML renders fine in a browser but not as a PNG (i.e., the HTML from [here](https://github.com/metabase/metabase/blob/e03bad72ffecac5df66429d0453456ab4d7850ed/src/metabase/pulse/render/png.clj#L91)). I tried upgrading CSSBox from 4.12 to 4.17 but didn't see any difference.

**Comment by flamber** [comment]
0.41 completely changed how this static viz looks.
