### ISSUE TITLE
Row chart visual problems

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12523]
**Describe the bug**
Row chart is very difficult to read, when hovering the row, and cannot drill-through if clicking value

**To Reproduce**
1. Simple question > Sample Dataset > Products
2. Filter by Title starting with `A`
3. Summarize Sum of Price by CreatedAt:Day
![image](https://user-images.githubusercontent.com/1447303/81807197-f24dda00-951d-11ea-8ef8-12426f7de290.png)
4. Problems:
![image](https://user-images.githubusercontent.com/1447303/124581616-8cbf5a00-de51-11eb-92fe-a87bef35baad.png)
    a. Formatting is not applied to the row value, only the regular hover
    b. Custom "Column title" is not applied to tooltip
    c. Hovering a row, makes it very difficult to read the value
    d. Shows browser style tooltip along with regular hover
    e. Hovering the row value (not the bar) only shows browser style tooltip, and doesn't outline the row
    f. Not possible to drill-through if clicking the row value (not the bar)
    g. Hovering the special series "Others" (Products > summarize Count by Vendor) will show empty value.

**Information about your Metabase Installation:**
Tested 0.35.3 thru 0.40.0-rc1

**Additional context**
Related to #11394 and #12185

:point_down: :point_down: :point_down: 
Alternatively, make Row a rotated Bar component #10967, which would fix this and many others issues, example:
#15535 #15133 #8150 #5855 #4588
:point_up: :point_up: :point_up: 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by luizarakaki** [comment]
Looks like everything here was fixed with the row chart refactor
