### ISSUE TITLE
SMTP 535 Authentication fails for Sendgrid. 

### ISSUE THREAD

**Issue by SergeDou** [metabase/metabase#12532]
**Describe the bug**
While setting up the SMTP send for Sendgrid I keep getting 535 Authentication fail. I have confirmed that credentials are correct when connecting through a terminal. 

Additional info: in the UI, when base64 password is entered and "Save Changes" is clicked, the masked password changes in length visually. 

**Logs**
`[b45d0ba9-323f-457b-9a47-72e5b6b104e1] 2020-05-13T15:46:53-07:00 ERROR metabase.middleware.log POST /api/email/test 500 112.0 ms (1 DB calls)
{:message "No matching clause: 535 Authentication failed: Bad username / password\n",
:type java.lang.IllegalArgumentException,
:stacktrace
["--> api.email$humanize_error_messages.invokeStatic(email.clj:35)"
"api.email$humanize_error_messages.invoke(email.clj:26)"
"api.email$fn__54693.invokeStatic(email.clj:116)"
"api.email$fn__54693.invoke(email.clj:104)"
"middleware.auth$enforce_authentication$fn__66808.invoke(auth.clj:14)"
"routes$fn__68332$fn__68333.doInvoke(routes.clj:56)"
"middleware.exceptions$catch_uncaught_exceptions$fn__66907.invoke(exceptions.clj:97)"
"middleware.exceptions$catch_api_exceptions$fn__66904.invoke(exceptions.clj:85)"
"middleware.log$log_api_call$fn__68710$fn__68711.invoke(log.clj:197)"
"middleware.log$log_api_call$fn__68710.invoke(log.clj:191)"
"middleware.security$add_security_headers$fn__66870.invoke(security.clj:121)"
"middleware.json$wrap_json_body$fn__68413.invoke(json.clj:64)"
"middleware.json$wrap_streamed_json_response$fn__68431.invoke(json.clj:100)"
"middleware.misc$maybe_set_site_url$fn__68740.invoke(misc.clj:59)"
"middleware.session$bind_current_user$fn__63397$fn__63398.invoke(session.clj:209)"
"middleware.session$do_with_current_user.invokeStatic(session.clj:184)"
"middleware.session$do_with_current_user.invoke(session.clj:177)"
"middleware.session$bind_current_user$fn__63397.invoke(session.clj:208)"
"middleware.session$wrap_current_user_id$fn__63382.invoke(session.clj:161)"
"middleware.session$wrap_session_id$fn__63326.invoke(session.clj:125)"
"middleware.auth$wrap_api_key$fn__66816.invoke(auth.clj:27)"
"middleware.misc$bind_user_locale$fn__68745.invoke(misc.clj:78)"
"middleware.misc$add_content_type$fn__68726.invoke(misc.clj:29)"
"middleware.misc$disable_streaming_buffering$fn__68754.invoke(misc.clj:94)"
"server$async_proxy_handler$fn__68488.invoke(server.clj:70)"
"server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"]`

**To Reproduce**
1. Go to Administrator
2. Put SMTP Credentials
3. Click Save Changes
4. Click Send Test Email
5. Get Error: "No matching clause: 535 Authentication failed: Bad username / password"

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.173-137.229.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
Blocking my team from getting alerts and notification from our data warehouse analytics.

**Additional context**
Related to https://github.com/metabase/metabase/issues/12466 ?

**Comment by flamber** [comment]
Hi @SergeDou 
Did you input the the username and password as base64 encoded?
https://sendgrid.com/docs/API_Reference/SMTP_API/getting_started_smtp.html
Since Sendgrid has changed their model, I cannot even setup a test account.

**Comment by flamber** [comment]
Closing, since there's no response.

**Comment by SergeDou** [comment]
Sorry didn't get notified of response for some reason. 

Yes, base64 as described in the report.

**Comment by flamber** [comment]
@SergeDou Are you saying that it's working or not working? Have you tested with other SMTP clients like Thunderbird?

**Comment by SergeDou** [comment]
It is **not** working. I am receiving error `No matching clause: 535 Authentication failed: Bad username / password`

I have tested through telnet and I'm able to successfully login.

![image](https://user-images.githubusercontent.com/5935169/82564412-91319200-9b2d-11ea-9905-dd9f2f4fe3b1.png)

**Comment by flamber** [comment]
@SergeDou Look in the application database table `setting` for column `key` starting with "email-smtp" and verify that the information matches what you expect. It might be a password manager that does something is shouldn't, when you're saving the email settings.

**Comment by SergeDou** [comment]
Thank you for spending the time on this. Apparently base64 is **not** needed for user and password. These are the correct instructions: 
https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html

**Comment by flamber** [comment]
@SergeDou Thank you for providing a link :+1: - closing the issue.
