### ISSUE TITLE
Integrate load-from-h2 and dump-to-h2 tests into main test suite

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12533]
Right now tests to make sure these are working run as part of separate scripts and separate CI steps. It seems like we could test them as part of the main test suite instead (creating a new Postgres/MySQL/MariaDB database and the dumping the current app DB to H2 and then loading into the new database) -- this will result in better coverage since the main test suite runs against 2 different versions each of Postgres/MySQL/MariaDB

**Comment by kidd** [comment]
I'm starting to look at this one.
This is what I gather from it and plan keep investigating:

- test-mirate-from-h2 ends up calling `./bin/test-load-and-dump.sh` which runs `lein ... load-from-h2` and `lein ... dump-to-h2`.
- `load-from-h2` and `dump-to-h2` are cmds. they live in `metabase/cmd.clj`.
- The goal would be to move away from the `.sh` and write a test in `/test/metabase/db/...` that would call the cmds from inside clojure (or the functions that are called by the cmds)
 
Is that more or less accurate?
