### ISSUE TITLE
Long names (without spaces) in tooltips gets cut off

### ISSUE THREAD

**Issue by rayventerprise** [metabase/metabase#12535]
**Describe the bug**
With large labels within the "Other" category on the pie visualization, it will clip off the characters
and will be unreadable.

**To Reproduce**
Create a pie chart and group by large labels.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1447303/96023777-389fc000-0e53-11eb-8f27-7ccec89fd66e.png)

**Information about your Metabase Installation:**
Version 0.35.3

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
This is not specific to Pie chart, but tooltips in general with long (non-spaced) strings. There's a bunch of other places too that has problems with long strings. See comments on #9711 
Workaround is to use spaces instead of underscore for values.

**Comment by shaunlebron** [comment]
The tooltip for “Other” is rendered differently in the latest release, and limits the title length to prevent overflow:
<img width="658" alt="CleanShot 2023-06-05 at 15 51 25@2x" src="https://github.com/metabase/metabase/assets/116838/239261ae-189c-45fb-a7b6-34b0d3f68e56">
