### ISSUE TITLE
Connecting a SQL question to a dashboard filter doesn't support simple types

### ISSUE THREAD

**Issue by MSch** [metabase/metabase#12538]
We have SQL questions that we want to show and filter in a Dashboard. Unfortunately this is only supported for "Field Filter" variables, not simple types like dates or text.

From the [SQL Parameters](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html) documentation:
> In order for a saved SQL/native question to be usable with a dashboard filter, it must contain at least one field filter.

### Use Cases
1. Have a dashboard showing the status of the sales pipeline (we have this mirrored into our PostgreSQL database) by month and/or by platform (Android, iOS, etc).
2. Have a dashboard highlighting support outliers by month/and or platform (Android, iOS, etc)

### Workarounds
Right now I'm considering to create views for each question. This is not ideal, since it adds friction, but for the most important data it can be done. I haven't yet tried if this would actually allow the filtering I want to do, but I assume views are treated as tables by Metabase.

Having this functionality is critical for us.

Thank you very much for considering it, and let me say that I am thoroughly impressed by Metabase!

**Comment by flamber** [comment]
Hi @MSch 
It is possible to use simple filters like Date, Number or Text, but they're just more limited compared to Field Filter.
Just for reference: https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html
But it sounds like you're asking for #6009 or #5245 or #6820 - if yes, then please close this and upvote the issue(s) by clicking :+1: on the first post of each.

**Comment by MSch** [comment]
@flamber thanks for checking, I don't think so.

I'll give three steps to reproduce:

1. Create a custom SQL question with variable `d` as type date:

```sql
SELECT d, random() from generate_series('2000-01-01'::timestamptz, '2020-12-12'::timestamptz, '1 day'::interval) d
[[where d between date_trunc('month', {{d}}) and date_trunc('month', {{d}}) + interval '1 month' - interval '1 day']]
```

2. Put it on a dashboard and add a date filter:

<img width="436" alt="Screenshot 2020-05-14 at 20 45 44" src="https://user-images.githubusercontent.com/7475/81973407-64a8e200-9624-11ea-9212-4e8bd5816759.png">

3. Then try to link the date variable to the date filter:
<img width="399" alt="Screenshot 2020-05-14 at 20 45 51" src="https://user-images.githubusercontent.com/7475/81973414-67a3d280-9624-11ea-8752-12d893aff6fe.png">

If this would be a table/view it would work.

**Comment by flamber** [comment]
Okay, so you're specifically asking for dashboard filter type "Month and Year" to be supported with Native question's simple Date filter?
So simple Date filter should be able to accept both full dates and just parts of it?

**Comment by flamber** [comment]
Closing in favor of #5781 and #4509/#3156
