### ISSUE TITLE
Settings with multi-line docstrings localize to site locale rather than user locale

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12558]
In the admin pages. This only affects 2 or 3 settings.

This is an example:

```clj
(defsetting query-caching-ttl-ratio
  (str (deferred-tru "To determine how long each saved question''s cached result should stick around, we take the query''s average execution time and multiply that by whatever you input here.")
       " "
       (deferred-tru "So if a query takes on average 2 minutes to run, and you input 10 for your multiplier, its cache entry will persist for 20 minutes."))
  :type    :integer
  :default 10)
```

I have site locale set to Spanish and user locale set to Italian:

![image](https://user-images.githubusercontent.com/1455846/82499702-027a3200-9aa7-11ea-89ea-f5edae42dd66.png)

You can see the cache TTL is still in Spanish. This is because by combining the `deferred-tru` forms with `str` the Setting docstring is getting realized right away rather than when it is serialized to JSON.

I think we can fix this by either having defsetting defer evaluation of the docstring/description by default, or by creating some sort of `deferred-str` helper function

**Comment by flamber** [comment]
Is this the same as #10770?

**Comment by camsaul** [comment]
Duplicate of #10770
