### ISSUE TITLE
Unable to connect GCP Load balancer through Metabase which is sitting on top of my Clickhouser servers

### ISSUE THREAD

**Issue by deepanwita-roy** [metabase/metabase#12555]
Please use the issue chooser, when creating a new issue:
I setup an instance of metabase and using the enqueue/clickhouse-driver to connect to Clickhouse from metabase.
I am able to connect through individual CH nodes from metabase. But I want metabase to connect to the GCP load balancer that I have set up on top of Clickhouse nodes. How do I enable that

https://github.com/metabase/metabase/issues/new/choose

**Comment by flamber** [comment]
Hi @deepanwita-roy 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And when using third-party drivers, you'll likely find better help on their site.
