### ISSUE TITLE
"select" admin settings are busted: showing keys instead of user-friendly descriptions

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12560]
This is in `master`. Instead of `advanced` it should be displaying `Enabled` -- `advanced` is the internal value, and `Enabled` is the user-facing description.

![image](https://user-images.githubusercontent.com/1455846/82502078-3a837400-9aab-11ea-9dac-ea99b32d0d6f.png)

**Comment by kdoh** [comment]
I *think* this was introduced by changes in https://github.com/metabase/metabase/pull/11522  It only seems to be an issue if a setting is using the out of the box default.

**Comment by flamber** [comment]
This is fixed on `master`, but not sure which PR it was.

**Comment by daltojohnso** [comment]
Can confirm that the issue is fixed, so I am closing this issue. I've opened #14682 to fix the issue with the Report Timezone dropdown that @flamber noted.
