### ISSUE TITLE
Adding card on dashboard through API works incorrectly

### ISSUE THREAD

**Issue by jayrumi** [metabase/metabase#12565]
**Describe the bug**

I have got installed metabase on the local machine. I use python for work with API. 
My code is next:

`conn_header_local = {'username': 'email', 'password': 'pass'}`

`res_local = requests.post('http://localhost:3000/api/session', json=conn_header_local, verify=False)`

`local_session_id = res_local.json()['id']`

`header_local = {'X-Metabase-Session':local_session_id}`

`result_local = requests.get('http://localhost:3000/api/dashboard/1', headers = header_local, verify=False)`

`jl_raw = '''
{
  "sizeX": 6,
  "sizeY": 6,
  "series": [],
  "id": None,
  "parameter_mappings": [],
  "card_id": 1,
  "visualization_settings": {'description': None, 'archived': False, 'collection_position': None, 'table_id': 2, 'result_metadata': [{'base_type': 'type/BigInteger', 'display_name': 'ID', 'name': 'ID', 'description': 'This is a unique ID for the product. It is also called the “Invoice number” or “Confirmation number” in customer facing emails and screens.', 'special_type': 'type/PK', 'fingerprint': None}, {'base_type': 'type/DateTime', 'display_name': 'Created At', 'name': 'CREATED_AT', 'description': 'The date and time an order was submitted.', 'special_type': 'type/CreationTimestamp', 'unit': 'default', 'fingerprint': {'global': {'distinct-count': 9998, 'nil%': 0.0}, 'type': {'type/DateTime': {'earliest': '2016-04-30T18:56:13.352', 'latest': '2020-04-19T14:07:15.657'}}}}, {'base_type': 'type/Float', 'display_name': 'Discount', 'name': 'DISCOUNT', 'description': 'Discount amount.', 'special_type': 'type/Discount', 'fingerprint': {'global': {'distinct-count': 701, 'nil%': 0.898}, 'type': {'type/Number': {'min': 0.17088996672584322, 'max': 61.69684269960571, 'avg': 5.161255547580326, 'sd': 3.053663125001991, 'q1': 2.9786226681458743, 'q3': 7.338187788658235}}}}, {'base_type': 'type/Integer', 'display_name': 'Product ID', 'name': 'PRODUCT_ID', 'description': 'The product ID. This is an internal identifier for the product, NOT the SKU.', 'special_type': 'type/FK', 'fingerprint': {'global': {'distinct-count': 200, 'nil%': 0.0}}}, {'base_type': 'type/Integer', 'display_name': 'Quantity', 'name': 'QUANTITY', 'description': 'Number of products bought.', 'special_type': 'type/Quantity', 'fingerprint': {'global': {'distinct-count': 62, 'nil%': 0.0}, 'type': {'type/Number': {'min': 0.0, 'max': 100.0, 'avg': 3.7015, 'sd': 4.214258386403798, 'q1': 1.755882607764982, 'q3': 4.882654507928044}}}}, {'base_type': 'type/Float', 'display_name': 'Subtotal', 'name': 'SUBTOTAL', 'description': 'The raw, pre-tax cost of the order. Note that this might be different in the future from the product price due to promotions, credits, etc.', 'fingerprint': {'global': {'distinct-count': 340, 'nil%': 0.0}, 'type': {'type/Number': {'min': 15.691943673970439, 'max': 148.22900526552291, 'avg': 77.01295465356547, 'sd': 32.53705013056317, 'q1': 49.74894519060184, 'q3': 105.42965746993103}}}, 'special_type': None}, {'base_type': 'type/Float', 'display_name': 'Tax', 'name': 'TAX', 'description': 'This is the amount of local and federal taxes that are collected on the purchase. Note that other governmental fees on some products are not included here, but instead are accounted for in the subtotal.', 'fingerprint': {'global': {'distinct-count': 797, 'nil%': 0.0}, 'type': {'type/Number': {'min': 0.0, 'max': 11.12, 'avg': 3.8722100000000004, 'sd': 2.3206651358900316, 'q1': 2.273340386603857, 'q3': 5.337275338216307}}}, 'special_type': None}, {'base_type': 'type/Float', 'display_name': 'Total', 'name': 'TOTAL', 'description': 'The total billed amount.', 'fingerprint': {'global': {'distinct-count': 10000, 'nil%': 0.0}, 'type': {'type/Number': {'min': 12.061602936923117, 'max': 238.32732001721533, 'avg': 82.96014815230805, 'sd': 38.35967664847571, 'q1': 52.006147617878135, 'q3': 109.55803018499738}}}, 'special_type': None}, {'base_type': 'type/Integer', 'display_name': 'User ID', 'name': 'USER_ID', 'description': 'The id of the user who made this order. Note that in some cases where an order was created on behalf of a customer who phoned the order in, this might be the employee who handled the request.', 'special_type': 'type/FK', 'fingerprint': {'global': {'distinct-count': 929, 'nil%': 0.0}}}], 'creator': {'email': ‘email', 'first_name': ’Name', 'last_login': '2020-05-21T17:01:04.717', 'is_qbnewb': False, 'is_superuser': True, 'id': 1, 'last_name': ‘LastName', 'date_joined': '2020-05-04T13:53:31.291', 'common_name': ’Name LastName'}, 'can_write': True, 'database_id': 1, 'enable_embedding': False, 'collection_id': None, 'query_type': 'query', 'name': 'Orders', 'dashboard_count': 1, 'read_permissions': None, 'creator_id': 1, 'updated_at': '2020-05-21T17:06:00.089', 'made_public_by_id': None, 'embedding_params': None, 'cache_ttl': None, 'dataset_query': {'database': 1, 'query': {'source-table': 2}, 'type': 'query'}, 'id': 1, 'display': 'table', 'visualization_settings': {'table.pivot_column': 'QUANTITY', 'table.cell_column': 'DISCOUNT'}, 'collection': None, 'created_at': '2020-05-04T17:17:33.825', 'public_uuid': None},
  "row": 10
}
'''`

`add_card = requests.post('http://localhost:3000/api/dashboard/1/cards', json=eval(jl_raw), headers = header_local, verify=False)`

`print(add_card)`
`print(add_card.json())`

When I go to dashboard I see the next:

![image](https://user-images.githubusercontent.com/15921439/82571350-84438b80-9b8b-11ea-85bd-57a5362e6641.png)

**Logs**

[c3baebce-8dc6-4304-84ed-2dd4e5865938] 2020-05-21T17:53:14+03:00 DEBUG metabase.middleware.log POST /api/dashboard/1/cards 200 8.1 ms (14 DB calls) App DB connections: 2/7 Jetty threads: 5/50 (1 idle, 0 queued) (93 total active threads) Queries in flight: 0 (0 queued)
[c3baebce-8dc6-4304-84ed-2dd4e5865938] 2020-05-21T17:53:27+03:00 DEBUG metabase.middleware.log GET /api/user/current 200 1.4 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (1 idle, 0 queued) (93 total active threads) Queries in flight: 0 (0 queued)
[c3baebce-8dc6-4304-84ed-2dd4e5865938] 2020-05-21T17:53:27+03:00 DEBUG metabase.middleware.log GET /api/session/properties 200 5.4 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (93 total active threads) Queries in flight: 0 (0 queued)
[c3baebce-8dc6-4304-84ed-2dd4e5865938] 2020-05-21T17:53:27+03:00 DEBUG metabase.middleware.log GET /api/database 200 1.1 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (93 total active threads) Queries in flight: 0 (0 queued)

**Expected behavior**

The card looks like

![image](https://user-images.githubusercontent.com/15921439/82571909-501c9a80-9b8c-11ea-91aa-4ac2367b535e.png)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_231-b11",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_231",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.231-b11",
    "os.name": "Mac OS X",
    "os.version": "10.15.4",
    "user.language": "en",
    "user.timezone": "Europe/Minsk"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v1.35.3",
      "date": "2020-04-29",
      "branch": "enterprise-release-1.35.x",
      "hash": "10740ae"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @jayrumi 
Have a look at this forum topic - you need to create the card with `POST`, which will then give you the card ID, and the you use `PUT` to fill out the details.
https://discourse.metabase.com/t/add-textcard-to-dashboard-with-api/9972

The best way to learn the API, is to just use Metabase while having your browser developer Network-tab open and looking at the request, and what data is being send/received.

**Comment by jayrumi** [comment]
hi @flamber 
I tried to POST and PUT the card as you advised and I had the same result.

**Comment by flamber** [comment]
@jayrumi Okay, have a look in your browser to see exactly what it's sending and then try to replicate that in your code.

**Comment by jayrumi** [comment]
@flamber do you mean I should go to the dash in browser, open console, press "Add a question", choose the question and after that investigate which actions was done in console?

**Comment by flamber** [comment]
@jayrumi Yes, like I wrote, the best way to learn the API, is to just use Metabase while having your browser developer Network-tab open and looking at the request, and what data is being send/received.
