### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by pitrador** [metabase/metabase#12579]
Metabase cover most of the used charts except of the gantt chart.

It could be great to have also the possibility of drawing gantt chart throw the Metabase.

Up to now I'm using external javascript library to show only the gantt, with an external link.

**How important is this feature to you?**
Personally I think that resuming the picture of a business a gantt view is very important; without it, managers have lack-view.

**Comment by flamber** [comment]
Duplicate of #10822
