### ISSUE TITLE
Filter and group same field by different granularities results in wrong "unit" result column.

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1257]
```
{
  source_table: 12,
  filter: ["TIME_INTERVAL", 45, "current", "year"],
  aggregation: ["count"],
  breakout: [["datetime_field", 45, "as", "quarter"]]
}
```

Expected: `data.cols[0].unit  == "quarter"`
Actual: `data.cols[0].unit  == "year"`

**Comment by agilliland** [comment]
A few very specific cases as examples

When I set a filter like "last month" i'm just getting a solid block of bars and something seems very out of place.

<img width="1394" alt="screen shot 2015-10-29 at 11 33 32 am" src="https://cloud.githubusercontent.com/assets/1987787/10828477/b5856758-7e31-11e5-8dc0-81b6e15d3406.png">

When doing weekly groupings for a single month the axis still feels a bit strange and the bars are fairly spread out.  Same issue is exacerbated more when there are fewer bars to display in the axis.  
Much better than before, but still not really what a user would expect ...

<img width="1398" alt="screen shot 2015-10-29 at 11 34 50 am" src="https://cloud.githubusercontent.com/assets/1987787/10828509/03027282-7e32-11e5-9d94-7cd988c40788.png">

<img width="1410" alt="screen shot 2015-10-29 at 11 35 06 am" src="https://cloud.githubusercontent.com/assets/1987787/10828539/2aa9cee8-7e32-11e5-8f2b-1732ebaf2802.png">

**Comment by camsaul** [comment]
Motion to close as unable to reproduce

**Comment by agilliland** [comment]
This is definitely still happening for me.  Not sure what scenario you are testing, but make sure you are using the exact same field in the filter and breakout clauses.
