### ISSUE TITLE
LDAP Sync Groups

### ISSUE THREAD

**Issue by jannishuebl** [metabase/metabase#12576]
**Is your feature request related to a problem? Please describe.**
I need to manually create the groups from my ldap also in metabase, and a apply a group mapping.

**Describe the solution you'd like**
The groups are automatically created when the user logs in, an the group mapping does not to be done manually.

**How important is this feature to you?**
I can live with this right know, but i should not be a big change, and would be less annoying

**Comment by flamber** [comment]
Sounds like a duplicate of #12151, which is a bug. Or am I misunderstanding what you're asking for?

**Comment by jannishuebl** [comment]
oh, sorry, missed that one!
