### ISSUE TITLE
Getting username blank error when connecting to API

### ISSUE THREAD

**Issue by kleban31** [metabase/metabase#12571]
**Issue**
Trying to connect to the REST API using _POST /api/session_ to authorize. 

Getting error:
`{"errors":{"username":"value must be a non-blank string."}}`

**Steps to Reproduce**
1. Run jar file
2. Sign into Metabase
3. Open Python
4. Execute the following:
```import requests

url = "https://localhost:3000/api/session"

payload = {}
headers = {
  'username': '_email@email.com_',
  'password': '_password_'
}

response = requests.request("POST", url, headers=headers, data = payload)

print(response.text.encode('utf8'))
```

**I Have Also Tried**
* Used Postman to send the call. Same error
* Used curl to send the call (```curl -X POST -d "Content-Type: application/json" -H '{"username": "email@email.com", "password": "password"}' http://localhost:3000/api/session```) . Same error

**Metabase Version**
* Metabase 0.35.3 
* Using jar file

**Comment by flamber** [comment]
Hi @kleban31 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You're sending the parameters as a header. cURL would look like this:
```
curl -X POST -H 'Content-Type: application/json' -d '{"username":"email@example.com","password":"secret"}' 'http://localhost:3001/api/session'
```
The best way to learn the API, is to just use Metabase while having your browser developer Network-tab open and looking at the request, and what data is being send/received.

**Comment by paperguns** [comment]
Using the browser to reverse engineer the API calls is far from efficient and a painful way to waste time as a developer. Please update the documentation with clear examples with code using common tools, such as Postman.
