### ISSUE TITLE
Impossible to filter empty on json field

### ISSUE THREAD

**Issue by Almorca** [metabase/metabase#12589]
I have a few registries without information on a json field but when I use "is empty" filter option on this field in a postgresql table Metabase don't find any registry.

**To Reproduce**
1. Create a table with a json field
2. Do a simple query on table
3. Filter "is empty" on the json field.

**Expected behavior**
Find all registries without information on json field.

**Information about your Metabase Installation:**
Settings
"metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.2",
      "date": "2020-04-13",
      "branch": "branch-0.37",
    },
    "settings": {
      "report-timezone": null
    }
  }

**Comment by flamber** [comment]
Hi @Almorca 
Metabase currently does not handle JSON or arrays that way.
#708 - upvote by clicking :+1: on the first post
And please verify bugs/functionality in official releases, since it's impossible to know which version you're using.
