### ISSUE TITLE
Dashboard counter displayed even when cards are finished

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12583]
**Describe the bug**
Dashboard query counter (in browser title), is still running if there's a card without permissions or on full dashboard error.
Similar to #11926

**To Reproduce**
Either view a dashboard that contains a card outside of the collection a user has access to (#4576), or have the dashboard break completely (#9299)

**Information about your Metabase Installation:**
Metabase 0.35.3

**Comment by iethree** [comment]
@flamber I've been able to reproduce and fix the no-permission loading error. Do you have any ideas how to reproduce a full dashboard break? It looks like the specific methods linked have been fixed.

**Comment by flamber** [comment]
@iethree I hope we've fixed all problems where entire dashboard breaks, so don't think you can reproduce that anymore.
I think it's likely the same problem as when one of the cards is "broken" (no permissions), then the timer expected it to finish.
So just go with what you can reproduce now, so we can close this issue - if anything else occurs, then we'll create a new issue.
