### ISSUE TITLE
Auto-suggest values for filters in dashboard

### ISSUE THREAD

**Issue by jgavil** [metabase/metabase#12604]
**Describe the bug**
Not sure if this is bug or user configuration error (i.e. my fault).

I have the following
- A question with a bunch of columns like first name, last name, appointment type, species. 
- A dashboard containing this question
- A filter on this dashboard (filter type = category) for the column species
- Note, the column in question is a "name" column looked up via join on a fact table with column ID joined with dimension table via ID.  The column is called "name" in the dimension table.
- In the data model the field type = category, the "filtering on this field" = a list of values

However, in the dashboard, I do not see an auto-suggest list of values when using the filter: 
* From within metabase
* From the public share link of the dashboard

**Expected behavior:**
Per https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html

I would expect a list of values to appear as suggestions when clicking on the filter. 

Per https://discourse.metabase.com/t/how-does-metabase-create-autocomplete-suggestions/9207

I would also expect to have the filter value search based on a statement LIKE '[search term]%'.  
However, searching the start of a string does not produce this.

**Logs**
Here is an example network request when using this filter: 
Request URL:https://reporting.rhapsody.vet/api/card/260/query
Request Method:POST
Params: {"parameters":[{"type":"date/all-options","target":["dimension",["field-id",734]],"value":"past30days"},{"type":"id","target":["dimension",["field-id",739]],"value":[2]},{"type":"category","target":["dimension",["joined-field","Species",["field-id",145]]],"value":"Can"}]}

**To Reproduce**
See above

**Screenshots**

Setting up this filter: 
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/16961227/83160248-f7418a80-a0d4-11ea-9ceb-7d05adde09e4.png">

Trying to use this filter: 
<img width="855" alt="image" src="https://user-images.githubusercontent.com/16961227/83160302-03c5e300-a0d5-11ea-956f-f2653466fa6d.png">

Manually typing value into this filter: 
<img width="641" alt="image" src="https://user-images.githubusercontent.com/16961227/83160325-0f190e80-a0d5-11ea-8962-f1a0e64063c2.png">

Data model configuration:
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/16961227/83160448-38399f00-a0d5-11ea-82f1-6ac7e4169214.png">

**Severity**
Medium

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.138+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-02",
      "tag": "v1.35.1",
      "branch": "enterprise-release-1.35.x",
      "hash": "d57f83d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @jgavil 
Latest release is 1.35.3 - there were some issues with 1.35.1, so it never got an official release.
And in the future, please use the support email with Enterprise Edition.

1. Is it a SQL question or Simple/Custom question?
2. If SQL, are you using a Field Filter?
3. Do you have other cards/questions on the dashboard connected to the same filter?

**Comment by flamber** [comment]
Through support, it was discovered that the issue was the same as #12250, which has milestone 0.36
