### ISSUE TITLE
Object Details breaks if Field Type is "Field containing JSON", but data is not `JSON`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12600]
**Describe the bug**
Object Details (visualization when clicking a primary key) does not work if it contains a field with type "Field is JSON", but the field is returning a non-JSON value.
This can happen if someone accidentally chooses that field type, but it's also a problem for columns that might contain mixed data (like Metabase's application database's table `setting`).

**To Reproduce**
1. Go to Admin > Data Model > Sample Dataset > Reviews
2. Set Field Type for "Body" to "Field containing JSON"
3. Simple question > Sample Dataset > Reviews
4. Click `ID` cell of first row, which should show Object Details, but is showing an error with the Run button as overlay, so it's not possible to see the error (which is only available in frontend):
![image](https://user-images.githubusercontent.com/1447303/83068760-17d3fb00-a069-11ea-9334-aa359fd274c6.png)
5. Inspecting the source, reveals the error is `JSON.parse: unexpected character at line 1 column 1 of the JSON data`, but it's not shown in browser console

**Information about your Metabase Installation:**
Metabase 0.35.3 and `master` with various backends and browsers

**Additional context**
Similar to #12586, but this issue is frontend only (from what I can tell)

**Comment by ghiculescu** [comment]
As per https://github.com/metabase/metabase/issues/13627#issuecomment-718931540, this comes up by default with any field of the `hstore` postgres type, since that defaults to "Field containing JSON".
