### ISSUE TITLE
Cypress smoketests

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#12618]
We want to have a more comprehensive set of tests that we can run prior to releases in order to validate standard functionality. These tests will be longer running and, as such, are only intended to be run on either a manual or scheduled basis. 

Some of them already exist as unit tests, but either only test the admin perspective, or do not test the entire workflow.

I will continue to add use cases to this issue.

## Core Metabase usage

- [x] As an admin, I would like to be able to:
    - [x] Set up Metabase
    - [x] Add a simple summarized question
    - [x] Add a simple JOINed question
    - [x] Add a question with a default line visualization
    - [x] Add a new dashboard with the previous questions
    - [x] Add a new user
- [x] As a new user, I would like to be able to:
    - [x] Login
    - [x] View the different questions that exists in the "Our Analytics" collection
    - [x] View the dashboard that exists in the "Our Analytics" collection
    - [x] Create my own question
    - [x] Create my own dashboard

- [x] As a user, I would like to be able to use all the features of the simple question editor:
    - [x] Header actions like sorting, distribution, etc
    - [x] Ensuring that the header actions are appropriate for different data types
    - [x] Filtering via both the sidebar and the header
    - [x] Summarizing via both the sidebar and the header

- [x] As a user, I would like to be able to use all the features of the notebook editor
    - [x] Custom columns
    - [x] Custom JOINs

## Admin setup

- [ ] As an admin, I would like to be able to:
    - [ ] Add a new database (eventually for every type of supported DB)
    - [x] Setup email (maybe using something like [maildev](https://github.com/maildev/maildev)
    - [x] Setup Slack
    - [x] Create new groups
    - [x] Create new users in different groups
    - [x] Deactivate a user and subsequently not be able to login as that user
    - [x] Set up custom maps

- As an admin, I would like to be able to modify my data models:
    - [x] Rename a table
    - [x] Add a description to a table
    - [x] Change a column name
    - [x] Change a column's visibility (and have it be reflected in notebook editor)
    - [x] Change a columns formatting (and have it be reflected in notebook editor)
    - [x] Configure a foreign key to show the name (and have it be reflected in notebook editor)
    - [x] Hide a table (and have it be reflected in the notebook editor)
- As a user, if my admin has changed data models:
    - [x] I would like to have visibility, formatting, foreign key mapping be reflected for me

- [x] As an admin, I would like to be able to:
    - [x] Modify user permissions for data access and SQL queries, both on a database/schema level as well as at a table level 
    - [x] Modify Collection permissions for top-level collections and sub-collections
- [x] As a user, if the admin changes permissions:
    - [x] I should no longer be able to access tables or questions that have been restricted
    - [x] I should be able to view collections I have access to, but not ones that I don't even if I know the URL

## User --> Table Customization

- [ ] As a user, I would like to be able to:
    - [ ] Remove visible columns by clicking the `Settings` button
    - [ ] Change the column name by clicking the `Settings` button
    - [ ] Reorder the list of visible columns by clicking the `Settings` button
    - [ ] Do all of the above, but with a custom JOINed table
    - [ ] Remove and reorder columns like above but in the custom question editor
    - [ ] Verify that changes made in the custom editor are reflected in the simple editor and vice versa

- [ ] As a user, I should be able to:
    - [ ] Do a bunch of stuff in Metabase as user A
    - [ ] Do a bunch of stuff in Metabase as user B
    - [ ] As either of those users, view the `/activity` page and see other people's activity

- [ ] As a user, I should be able to:
    - [ ] Search for a table, question, dashboard, pulse, segment and have it show up in the search results
    - [ ] _Not_ see a search result if I am not allowed to see the item

_Use cases under here are still being worked on_

- [ ] As an admin, I should be able to:
    - [ ] Change the "Report Timezone" of my Metabase instance

- [ ] As an admin, I should be able to:
    - [ ] Change "Localization" settings in my Metabase instance and have them be reflected throughout the app.

**Comment by Opalevanescence** [comment]
A lot of the user controls found in the header and sidebar are also in the notebook editor, so I added checks of those to the general user tests as well.

**Comment by flamber** [comment]
Closing, as this has more or less been completed and outstanding points have their own separate issues.
