### ISSUE TITLE
Dashboard filters to Nested Question can only be added one way, and cannot be edited (FE bug)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12614]
**Describe the bug**
On `master`, it's now possible (#9802) to connect dashboard filter to columns from a nested question (ex. Custom question that uses a Native question), but it's only possible to add/edit the connection, when going directly from the question via "Add to dashboard".
If you start from dashboard and add the question from there, then you only see `No valid fields`.

**To Reproduce**
1. Native question > Sample Dataset - `SELECT * FROM "ORDERS"` - and save as Q1
2. Simple question > Saved Questions > select Q1 - and save as Q2
3. When it asks "Add to dashboard", click yes (or click pencil-icon next to question title)
4. Q2 is now added to dashboard, click "Add a filter" > Time > All Options, and connect to Q2 card
5. Save dashboard and try using the filter (ie. past 30 months) - works
6. Browser refresh
7. Edit dashboard
   a. Edit filter, notice that the card says `No valid fields`, but the filter is still working
   b. or, Add question Q2 again as another card and edit filter, which also says `No valid fields` for that card, when it's added directly from the dashboard, instead of thru the question (step 3)

**Information about your Metabase Installation:**
`master` commit `81edcd4`

**Severity**
Giving P1, since it makes all the work done in #9802 hard to use.

**Additional context**
There's a separate requests for exposing variable filters, which would allow more advanced filtering, while also allowing filters set to Required, which currently fails with `You'll need to pick a value for 'Filter' before this query can run.` (question) or `There was a problem displaying this chart.` (dashboard)
#6449 and #4367

**Comment by camsaul** [comment]
So this is an FE bug.

I've figured out the root cause.

When adding a Card to a Dashboard by clicking "Add this Card to a Dashboard",

`state.entities.fields` /`metadata.fields` contains stuff like

```javascript
metadata.fields: 
{
...
field-literal,CREATED_AT,type/DateTime: Field {_plainObject: {…}, table_id: "card__624", special_type: "type/CreationTimestamp", name: "CREATED_AT", dimension_options: Array(15), …}
field-literal,DISCOUNT,type/Float: Field {_plainObject: {…}, table_id: "card__624", special_type: "type/Discount", name: "DISCOUNT", dimension_options: Array(5), …}
field-literal,ID,type/BigInteger: Field {_plainObject: {…}, table_id: "card__624", special_type: null, name: "ID", dimension_options: Array(0), …}
field-literal,PRODUCT_ID,type/Integer: Field {_plainObject: {…}, table_id: "card__624", special_type: null, name: "PRODUCT_ID", dimension_options: Array(5), …}
field-literal,QUANTITY,type/Integer: Field {_plainObject: {…}, table_id: "card__624", special_type: "type/Quantity", name: "QUANTITY", dimension_options: Array(5), …}
field-literal,SUBTOTAL,type/Float: Field {_plainObject: {…}, table_id: "card__624", special_type: null, name: "SUBTOTAL", dimension_options: Array(5), …}
field-literal,TAX,type/Float: Field {_plainObject: {…}, table_id: "card__624", special_type: null, name: "TAX", dimension_options: Array(5), …}
field-literal,TOTAL,type/Float: Field {_plainObject: {…}, table_id: "card__624", special_type: null, name: "TOTAL", dimension_options: Array(5), …}
field-literal,USER_ID,type/Integer: Field {_plainObject: {…}, table_id: "card__624", special_type: null, name: "USER_ID", dimension_options: Array(5), …}
...}
```

whereas when you add a Card to a Dashboard via the Dashboard itself it does not contain those same "field-literal" fields in `state.entities.fields` /`metadata.fields`. It looks to me like `Tables.actions.fetchMetadata` is adding those fields to `state.entities`  but I tried adding a call in `DashCardCardParameterMapper` and it's not doing anything.
