### ISSUE TITLE
Human-reable numering not working properly

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#12629]
This is regarding the issue reported [here](https://github.com/metabase/metabase/issues/10716#issuecomment-555198909).
On desktop (checked on Firefox and Chrome) if the browser width is bigger than a certain threshold, big numbers are not shown in human-readable format.

![big numbers](https://user-images.githubusercontent.com/15974735/83446815-38eb7180-a404-11ea-80e5-2daa934a4dbe.png)

It still doesn't work on mobile either (although in the issue mentioned above there is a comment that says "Fixed in #10932")

Metabase Version: v0.35.4 (the issue occurs with previous versions as well)

**Comment by flamber** [comment]
Looks like the "humanized" format was broken. The overflow was also noticed in #10856
Someone created an issue on it, but I misunderstood it as a request to use a specific library - #12057
Related to #6201 and #7039
