### ISSUE TITLE
Sorting columns on Dynamic Table with Timeframe as alphanumeric

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#12639]
When using in a dynamic table a time frame, it is better to use timeframe sorting data pt_BR `[Janeiro, Fevereiro, Março, Abril]`, not the default sorting data that is alphanumeric sorting `[April, February, March, January, May]`.

**Screenshots**
![Screenshot from 2020-06-02 18-00-59](https://user-images.githubusercontent.com/6808348/83569576-15572280-a4fb-11ea-83b6-c3f6415549c4.png)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-8u252-b09-1~deb9u1-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.9.0-6-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @dannyeuu 
I don't understand the issue. Pivot is sorted based on your query. Example sorted reversed:
![image](https://user-images.githubusercontent.com/1447303/83570941-2e75c880-a527-11ea-94b9-05aef291e20b.png)

**Comment by dannyeuu** [comment]
My query that resulted in this miss sorting
![Screenshot from 2020-06-02 19-28-30](https://user-images.githubusercontent.com/6808348/83576244-ac29dc00-a507-11ea-9013-e4330423b9cf.png)

**Comment by dannyeuu** [comment]
Sorry @flamber I saw the problem, my query sort ordering, that was first sorted ordering by sum not the date 
![Screenshot from 2020-06-02 19-36-38](https://user-images.githubusercontent.com/6808348/83576567-6de0ec80-a508-11ea-8796-73a5f1baba4b.png)
