### ISSUE TITLE
Cannot edit BigQuery database configuration after 0.35.4 upgrade

### ISSUE THREAD

**Issue by markberger** [metabase/metabase#12636]
**Describe the bug**
I am unable to edit the database configurations for a BigQuery database. The `Save changes` button is greyed out and does not turn green after editing any of the fields. I do not have this problem when trying to edit a postgres db on the same Metabase instance.

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 83.0.4103.61
- Your operating system: OS X
- Your databases: BigQuery, Postgres
- Metabase version: 0.35.4
- Metabase hosting environment: ubuntu
- Metabase internal database: postgres

**Severity**
Very annoying. I need to disable using the JVM timezone and I am unable to do this.

**Comment by flamber** [comment]
Hi @markberger 
You need to input a new auth code - see #4196 - this will change in 0.36.0 with Service Accounts.
Does that fix it for you - or is this a new problem in 0.35.4 that wasn't there in earlier versions?

**Comment by markberger** [comment]
@flamber that fixes my issue, thanks for your help!
