### ISSUE TITLE
question创建成功但未在界面显示，可通过搜索索引到结果

### ISSUE THREAD

**Issue by zhangfana** [metabase/metabase#12635]
**Describe the bug**

question创建成功但未在界面显示，可通过搜索索引到结果
**Logs**

**To Reproduce**
1、新建问题
2、保存问题
3、集合中查看问题，问题未展示
4、搜索问题，可搜索到结果
5、版本：v0.34.3
**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Hi @zhangfana 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And if you write in English, then it's more likely that you will get a response.
