### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Huntehhh** [metabase/metabase#12630]
I am running into an error where one of my co-workers attempts to go to my metabase dashboard and immediately get's a screen with the words written in the title.

The dashboard works perfectly for me, but does not work for numerous other users i have attempted to send the link to. All of these users have correct access, but for some reason run into this issue no matter where I move the dashboard. I will include a screenshot of the issue.
![image (8)](https://user-images.githubusercontent.com/66277108/83450412-33515400-a423-11ea-83a7-cd31c8eac353.png)

Any help is appreciated thanks!

**Comment by flamber** [comment]
Hi @Huntehhh 
Without any details as we ask for, when creating an issue, then it's really difficult to figure out anything.
Post "Diagnostic Info" from Admin > Troubleshooting.

**Comment by bonnie-bolt** [comment]
I have the same issue mentioned above. Does this issue resolved?

**Comment by flamber** [comment]
@bonnie-bolt Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And remember to provide enough information, so it's possible to understand the problem.
