### ISSUE TITLE
Universal Search hides some items if they have the same name

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12642]
**Describe the bug**
When using the universal search, if a Metric and Segment has the same name, then it doesn't list both in the results. Clicking the right sidebar filter, it's possible to show the items.

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Orders
2. Create a Segment called "Testing" and a Metric called "Testing"
3. Use the global search to find "Testing"
4. It only lists the Metric, but the `/api/search?q=Testing` returns both items:
![image](https://user-images.githubusercontent.com/1447303/83627893-f0fd5380-a597-11ea-9338-2c52f5c535e3.png)
5. Clicking the Segments filter on the right, makes it list the item:
![image](https://user-images.githubusercontent.com/1447303/83628052-315cd180-a598-11ea-9b00-8ded281c8979.png)

**Information about your Metabase Installation:**
Metabase 0.35.4 and 0.34.3

Related #5315

**Comment by tsmacdonald** [comment]
(inadvertently) fixed by #14867

![image](https://user-images.githubusercontent.com/784417/108777441-698eb080-7529-11eb-9503-7ff05062f2c8.png)
