### ISSUE TITLE
How does Caching Works in metabase

### ISSUE THREAD

**Issue by Zen6037** [metabase/metabase#12650]
We are running 2  metabase(0.35.3) nodes in EC2 with PostgreSQL as backend db for querying Redshift warehouse.
We have caching enabled in the metabase.
We are facing an issue When we refresh the dashboard question alternatively show *no result*.

My Questions are

- how does caching works in metabase
- does multiple hit of same time would get hit to warehouse if cache is invalidated.
- How does metabase synchronize in case of the multiple nodes.

**Comment by flamber** [comment]
Hi @Zen6037 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

Latest release is 0.35.4

Cache follows the settings you define:
https://www.metabase.com/docs/latest/administration-guide/14-caching.html

Metabase stores query cache in the table `query_cache` of your application database, which is shared between the nodes that use the same application database.

There's currently an issue, where multiple queries run at the same will not use cache - #11199

> ... we refresh the dashboard question alternatively show no result

Check you log, which will hint if the query is being executed on your datasource or returned from cache. Admin > Troubleshooting > Logs

Related #12556

**Comment by Zen6037** [comment]
Hi @flamber from the [documentation](https://www.metabase.com/docs/latest/administration-guide/14-caching.html) its not clear that if multiple user open the same question at the same when cache is invalidated, what is the metabase behavior.

1. would all query hit the datasource or only  one query would go to datasource
2. When we have more then metabase instance running with same application database,  would there be any sync between metabase instances to check if query is currently being executed on datasource and allow only one instance of query to be executed.

**Comment by Zen6037** [comment]
based on the #11199 it seems like currently multiple query would get executed.

**Comment by flamber** [comment]
@Zen6037 
1. Like I wrote, there's currently an issue (#11199), where multiple queries that run at the same time will not use the cache. Only after one of those complete, then there's a cache, which new queries will use.
2. All instances will check the application database for cache (which is shared between them), but since there's no valid cache until one of the queries finished with a valid cache, then they will all hit the datasource.

Upvote #11199 by clicking :+1: on the first post - and read some of the referenced issues too.

**Comment by rudder-star** [comment]
Thanks @flamber 👍 

Will upvote the #11199.

Any idea on how get it prioritised and fast track the release for it?

**Comment by flamber** [comment]
@rudder-star There's 1700+ other issues - and many with higher priority.
