### ISSUE TITLE
Password reset doesn't work on low-resolution screens

### ISSUE THREAD

**Issue by chrhartm** [metabase/metabase#12658]
**Describe the bug**
When trying to reset password on a low-resultion screen, the visual of the bridge overlays the password reset button and the button cannot be clicked.

**To Reproduce**
1. Have a screen with low resultion (1280x720)
2. Go to password reset link in Email when Admin resets password
3. Try clicking password reset button

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8695608/84030546-8c296b00-a994-11ea-9cf9-47e17b6018a4.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome, but also with Edge
- Your operating system: Windows 10
- Metabase version: v0.35.3

**Severity**
Low

**Additional context**

**Comment by chrhartm** [comment]
Resizing the window works as a workaround

**Comment by chrhartm** [comment]
Thanks for fixing this so quickly ❤️ and congrats to your first metabase contribution 🥳 @nemanjaglumac

**Comment by nemanjaglumac** [comment]
@chrhartm - thank you so much! It feels great :)

Here's to many more... 🥂
