### ISSUE TITLE
Field Filter dropdown not working for users without data permissions in some cases

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12654]
**Describe the bug**
SQL questions with Field Filter that reference a table that the user doesn't have access to does not work, when accessing the question directly (new tab). Filters are non-functional with console errors.

But if the same question exists on a dashboard (without any filters), going to the dashboard and clicking the card title to go to the question, then the filters are working as expected if they are List. If it is a search, then the input isn't broken, but the autocomplete doesn't work.

**To Reproduce**
1. Admin > People > create user "User"
2. Admin > Permissions > Data > revoke data-access from "Sample Dataset" for "All Users"
3. Admin > Permissions > Collection > set view-only "All Users"
4. Native question > Sample Dataset > `SELECT * FROM PRODUCTS WHERE {{Category}} AND {{Vendor}}` and connect as Field Filter to Products.Category (list) and Products.Vendor (search)
5. Save question "Question" and add to dashboard "Dashboard"
6. Login as "User"
7. Go directly to "Question" (or open in new tab) and click any filter - not working - the filters are not even converted to text input, they're completely broken.
The console has a lot of errors like this:
```
Failed to load resource: the server responded with a status of 403 (Forbidden) /api/field/106
Failed to load resource: the server responded with a status of 403 (Forbidden) /api/field/106/values
Request entities,fields,106,fetch failed: "You don't have permissions to do that."
Uncaught TypeError: Cannot read property 'id' of null
```
8. Now go to "Dashboard" and click card title, and click "Category" filter, which now works. Click "Vendor" filter and type `a`, which should autocomplete, but that does not work (loading spinner).
The console still shows a bunch of errors throughout this entire step:
```
Failed to load resource: the server responded with a status of 403 (Forbidden) /api/database/4/metadata
fetchData error: "You don't have permissions to do that."
Uncaught (in promise): "You don't have permissions to do that."
GET /api/field/109/search/109?value=a&limit=100 403 (Forbidden)
```

**Information about your Metabase Installation:**
Metabase 0.35.4 and `master`

**Additional context**
From #8472
Related to #11007

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jparszuto** [comment]
Is there any fix for the above?

**Comment by jparszuto** [comment]
Temporary workaround was to downgrade to x.34.3 - problem still persisted in x.35.3 and x.35.4

**Comment by flamber** [comment]
Changing priority, since it was a regression in 0.35.0, which makes SQL questions with Field Filters almost impossible to use.
Still reproducible on latest `master`.

**Comment by nemanjaglumac** [comment]
It seems that this was already reproduced: https://github.com/metabase/metabase/pull/12852.

I'm adding `.reproduced` label.

**Comment by StephanieField** [comment]
Is there a workaround for this? We're not able to upgrade as it still seems to be an issue in V1.38.2. We're currently still using V1.34.3 in our production environment and would love to be able to use some of the newer features.

**Comment by camsaul** [comment]
The failing call to `/api/database/4/metadata` isn't a regression -- that's never been allowed, the fix for that is that the FE client shouldn't make metadata calls there anyway -- the Dashboard and Card endpoints come back with all the metadata you need IIRC, It's a separate issue from the parameters issue

**Comment by escherize** [comment]
This is out of date, but still related to: #29422.
