### ISSUE TITLE
Global number formatting does not apply to percentages

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#12659]
**Describe the bug**
When setting in the admin a global number format different than the default (e.g. 100 000,00), the formatting is not applied to percentages of pie charts.

**To Reproduce**
1. Go to Admin > Formatting and change the separator style to non-default (e.g. 100 000,00)
2. Exit admin and create a new pie chart question, for example:
3. Table orders, metric = count of rows, group by = product category, viz = pie chart
4. The total number of order in the chart is correctly formatted (18 760) but not the percentages in the legend (21.2%) 

**Expected behavior**
The number format should also apply to percentages (e.g. should be 21,2%)

**Screenshots**
![image](https://user-images.githubusercontent.com/7570541/84037215-8df82c00-a99e-11ea-9000-94f569c0799d.png)

**Information about your Metabase Installation:**

Metabase version: v0.35.2

**Severity**
Low severity, only prevents from displaying metrics consistently and avoiding confusion of users

**Comment by flamber** [comment]
It doesn't respect chart format settings either. Related to #11394

**Comment by flamber** [comment]
Fixed in #14995
