### ISSUE TITLE
field filters unable to use alias

### ISSUE THREAD

**Issue by FelixTx** [metabase/metabase#12666]
**Describe the bug**
Can't use a field filter on a column belonging to an aliased table:
```
select * from table_name table_alias
where stuffs 
[[ AND table_alias.value = {{ variable }} ]]
```
variable being a field filter

**Logs**
`[Amazon](500310) Invalid operation: invalid reference to FROM-clause entry for table "table_name";"`

I reckon the way you get the values for the field filter might use a join on table_name instead of table_alias.

**Information about your Metabase Installation:**
v0.35.3
Amazon redshift

bonus: I notice you changed the way you manage permissions on field filters data : The user needs to have permission on the table used in the field filter to search in filter text box.

**Comment by flamber** [comment]
Hi @FelixTx 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And the syntax for Field Filters are without reference to the column:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type
