### ISSUE TITLE
Edit Dashboard Error on Internet Explorer 11

### ISSUE THREAD

**Issue by salasramos** [metabase/metabase#12672]
**Describe the bug**
When user edits a dashboard and tries to remove one of the questions, after clicking on save button, the message "Save Failed" is displayed.
Adding a question to the Dashboard works. Error happens only when deleting a question and try to save it

**Logs**
Error in debug console: Malformed JSON in request body

**To Reproduce**
Create a dashboard
Add 2 questions to the dashboard
Save it and exit the dashboard
Return to the dashboard and click on edit
Remove 1 question and save
Message "Save Failed" is displayed

**Expected behavior**
Remove a question from dashboards and save it successfully

**Screenshots**
![IE11_SaveFailed](https://user-images.githubusercontent.com/10760522/84280894-8602ce00-aafd-11ea-99cd-3562cdd2880a.PNG)
![IE11_Console](https://user-images.githubusercontent.com/10760522/84280930-9155f980-aafd-11ea-8eb1-5268ec21194e.PNG)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; rv:11.0) like Gecko",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.158-129.185.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "presto"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-29",
      "tag": "v1.35.3",
      "branch": "enterprise-release-1.35.x",
      "hash": "10740ae"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Blocking users that use Internet Explorer from editing dashboards

**Additional context**
Internet Explorer is listed as supported

**Comment by camsaul** [comment]
@flamber aren't we dropping support for IE 11, or are we waiting until the Microsoft EOL in August 2021?

**Comment by flamber** [comment]
@camsaul Yes, IE11 support is being dropped in Metabase version 40, but until then it's still a supported browser.
Microsoft's Mainstream support ends in 4 months - Extended support ends in 4.5 years (!)
Anyone still needing IE11, should upgrade to Edge, which has IE Mode: https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode

**Comment by flamber** [comment]
Closing, since Metabase dropped support for IE11 in version 0.40
https://www.metabase.com/blog/Metabase-0.40/index.html#upgrade-now
