### ISSUE TITLE
Pin Map not showing some rows if they have null value before lat/lon columns

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#12674]
The description of this bug is a bit complicated, couldn't fit it in the title.
Say we have some data as follows:
![bug0](https://user-images.githubusercontent.com/15974735/84304809-f285c900-ab0d-11ea-9181-699a57686cb9.png)
Now if we use Pin Map visualization, we only see 5 pins on the map and a warning sign is shown on the top-right which says **"We filtered out 2 row(s) containing null values."**  
This is weird because the tabular data is showing 7 rows and no row is all null.
 
After trying different configurations of the columns, I concluded that the number of rows filtered out in the pin map visualization equals the number of cells with null value in the first column (from left) which has any null values, and this column needs to be before the lat/lon columns.
E.g. in the above case the first column with null values is the second column and two of its cells are null, so pin map filters out two rows (this shouldn't happen of course, but here I'm just explaining what is happening).  
(Getting back from Pin Map visualization to the tabular view, the warning remains at the top right)
![bug1](https://user-images.githubusercontent.com/15974735/84306626-953f4700-ab10-11ea-9716-d1a32fae46a0.png)

To confirm this, I swapped the second and third columns. In this case the pin map was showing 6 pins and the warning sign saying **"We filtered out 1 row(s) containing null values."**
![bug2](https://user-images.githubusercontent.com/15974735/84307163-5c53a200-ab11-11ea-8e58-53832095cf93.png)

The filtering out of rows in the pin map doesn't happen if the first column with null values is after latitude or longitude column:
![bug3](https://user-images.githubusercontent.com/15974735/84307451-c409ed00-ab11-11ea-853d-f9a2e640e0dd.png)

- Metabase version: ( 0.35.4)
- This happens in both native questions and simple questions.
- The workaround I'm using for now is to put the lat/lon column before any column that may have null value.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by notrom** [comment]
@flamber this one is causing quite a bit of confusion for use here. We're getting the wrong hover popup on pins when there is a null in a number field before the lat long fields. The point is in the right place but both the **hover info and the click through refer to the wrong row**. 

Fortunately it looks like explicitly setting the filed order in the data model (loving this feature) to have the lat/long fields before any fields that may be null works around the issue. It's not ideal as you've got to set it up on each table that has a lat/long, and it's generally not the things that users want to see in the first columns, but it does work.

I've struck a few issues around how null values are processed, as there are no null values in the Sample Data set it makes it tricky to reproduce these without writing a native query, and sometimes native SQL questions behave slightly differently to standard questions in Metabase it doesn't always feel like you're reproducing the same thing. Could we get some nulls added to the Sample Data set please?

**Comment by flamber** [comment]
@notrom There are null values in Sample Dataset - Discount has a large majority of nulls, but correct, there are no any nulls in the lat/long columns. I would like boolean added along with probably one or two other columns, but it's a lot more tricky to modify the Sample Dataset, since we use that for the majority of the tests, so updating the dataset would also require updating a lot of tests.

**Comment by richxrich** [comment]
> @notrom There are null values in Sample Dataset - Discount has a large majority of nulls, but correct, there are no any nulls in the lat/long columns. I would like boolean added along with probably one or two other columns, but it's a lot more tricky to modify the Sample Dataset, since we use that for the majority of the tests, so updating the dataset would also require updating a lot of tests.

Create a test with a join to a table with long and lat with a row that will produce a null for long and lat and you'll be able to reproduce.

**Comment by flamber** [comment]
@richxrich If you know how to do that in QB with Sample Dataset, then please provide an example.

**Comment by richxrich** [comment]
> @richxrich If you know how to do that in QB with Sample Dataset, then please provide an example.

Sure thing... just return something that will give you data with and without long and long for example

```
select top 50 * from orders O

left join people p on
P.id = o.user_id and p.source = 'Twitter'
```

Will reproduce the map error with pin location correct but data in the popup wrong.

**Comment by flamber** [comment]
@richxrich I know it can be done in SQL - the discussion above was about having more diverse Sample Dataset, so it could be done in the GUI.

**Comment by luizarakaki** [comment]
Not possible to repro on 47

**Comment by emyller** [comment]
I also have this issue querying from a SQL-based model. Took me a while to find this GitHub issue but things worked now that I moved all location fields to the top, before any possible nulls. Please let me know how I can help providing information to fix this.
