### ISSUE TITLE
Display and UI/UX issues with multiple joins to the same table / renaming a column renames all with the same name at the same time

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#12685]
**Describe the bug**
If you make more than one join to the same table there are issues around UX. Some of these issues occur if it's a modelled join, some for joins made in the notebook editor.
1. Renaming the "Column title" for fields in one of the joins updates the the title for all instances of that field. (manual joins)
![image](https://user-images.githubusercontent.com/4504437/84442764-5b964980-ac92-11ea-9122-97f3730b130e.png)
2. In the table settings dialog, all instances of the linked table have the same heading making it hard to know which instance you're interacting with (filters and group bys show the join field so are moreuseful). You've got to know the order of the reference columns. (data model joins)
![image](https://user-images.githubusercontent.com/4504437/84443856-98fbd680-ac94-11ea-9f49-9748de956612.png)
3. Filters don't indicate which join instance they're referring to (both manual and modelled)
![image](https://user-images.githubusercontent.com/4504437/84445060-42dc6280-ac97-11ea-8470-5fa12fff888a.png)

**Logs**
No logs

**To Reproduce**
1. In the Sample Data model, change the Product ID in Orders table to link to Users table. There are now 2 modelled links from Orders to Users. 
2. Create a questions based on Orders as indicated above.
For 1, then re-title one of the joined Name fields.
![image](https://user-images.githubusercontent.com/4504437/84446346-63a5b780-ac99-11ea-9cac-52e86e239b3c.png)

For 2, it's just a simple question on the Orders table with a table visualisation.

For 3, apply a filter to either of the above questions.

**Expected behavior**
1. Renaming a title of one field should only impact that one title
2. I'd like to know what instance I'm dealing with, particularly for table with lots of columns, it's easy to get lost.
3. Maybe include the join field in the filter widget, although that would take more screen real estate.

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}

**Severity**
1. is more serious than the other 2, I use this to clean up the presentation for users and if I can't change these independently it gets confusing. 2 and 3 are more personal preference I guess, but 2 can be quite frustrating/confusing.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Probably very related to #10551 and a little to #11452

**Comment by lkraav** [comment]
0.43.0RC-2

Yes, I'm running into this now, trying to build my first Model, that involves a single join to the same table.

Model gets immediately confused in multiple ways.

Can't (un-)select matching columns in editor:
![image](https://user-images.githubusercontent.com/147228/165765956-9b681e85-4587-40c7-a204-4c43c187c5f8.png)

After removing this conflicting column at question level, and converting it back to Model, query builder still fails:
![image](https://user-images.githubusercontent.com/147228/165767445-9ea4b007-df58-4d22-85c1-08e35456f944.png)

This is a showstopper for any Model that does a same table join. Are there workarounds available for 0.43, or do we just have to wait some months with some Models until this same-table stuff is properly patched up?

Other than that, MB is the bees knees.

**Comment by Tony-metabase** [comment]
This is not an issue anymore on the 47 release but this one is still an issue https://github.com/metabase/metabase/issues/32499 which is related to this but only for models
