### ISSUE TITLE
Hidden tables show up in "Our Data" 

### ISSUE THREAD

**Issue by PieterjanMontens** [metabase/metabase#12688]
Browser: Firefox 77.0.1 (64-bit)
OS: Debian bullseye/sid
Databases: Postgres 11.7
Metabase version: 35.0 - 35.4
Metabase hosting env: Official metabase dockers
Steps to reproduce

1. Change visibility of a table to hidden of a data model under admin.
2. It still appears under "Our Data", and can be opened.
3. Changing "Why hide" to technical/cruft or Technical Data does not correct the issue.
4. Issue happens with sample dataset and with our own tables.

edit: We solved it on our side using access permissions, but previous metabase versions did not have this behavior. Our administrators keep seeing all tables, even hidden ones.

**Comment by vgrange** [comment]
Problem solved. We just had to use permissions to restrict access to these tables.

**Comment by PieterjanMontens** [comment]
As a side-note: Metabase version 0.34.x do not have this issue.

**Comment by flamber** [comment]
Duplicate of #9759 - fixed by #12513 in 0.36.0
