### ISSUE TITLE
Frontend load issue: Adding members to groups

### ISSUE THREAD

**Issue by Opalevanescence** [metabase/metabase#12693]
**Describe the bug**
When adding members to a group you need to go to a separate page and then return before it loads the change in the number of members.

**Logs**
Nothing in the logs

**To Reproduce**
1. Go to '/admin/people/groups'
2. Click on one of your groups
3. Click 'Add members'
4. Add someone to the group
5. Click 'Groups'
6. Error: In the members column, Groups is still listing the previous number of people in the group
7. If you click 'People' and click back to 'Group' the page has corrected itself

**Expected behavior**
I expected to see the correct number of people in the group the first time I went onto the group page.

**Screenshots**
Screenshot the first time I click on Groups: 
<img width="1136" alt="Screen Shot 2020-06-12 at 1 45 27 PM" src="https://user-images.githubusercontent.com/58329466/84549960-2a337300-acbe-11ea-88c1-63c55fccf21d.png">

Screenshot the second time I click on Groups:
<img width="1137" alt="Screen Shot 2020-06-12 at 1 45 43 PM" src="https://user-images.githubusercontent.com/58329466/84549988-33bcdb00-acbe-11ea-8e40-09637b90cd78.png">

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1067-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3 (Ubuntu 12.3-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Minor

**Comment by flamber** [comment]
Related to #12294 and many of the referenced in https://github.com/metabase/metabase/issues/10330#issuecomment-610900593
