### ISSUE TITLE
Frontend load issue: SMTP Email

### ISSUE THREAD

**Issue by Opalevanescence** [metabase/metabase#12692]
**Describe the bug**
 When setting up SMTP email as admin, "Save" isn't clickable until you've clicked away from the final item you fill out.

**Logs**
Nothing is logged onto the console until I try to send a test email

**To Reproduce**
1. Go to '/admin/settings/email'
2. Type information into each input
3. Once you finish typing your email, before clicking anywhere, the "Save changes" is greyed out. However, if you click something else on the page, "Save changes" turns blue and is clickable.

**Expected behavior**
When I finish typing my email, before clicking away from the input, I expected to be able to click the "Save changes" button.

**Screenshots**
The page when I've finished my email, but haven't moved away:
<img width="1130" alt="Screen Shot 2020-06-12 at 1 31 26 PM" src="https://user-images.githubusercontent.com/58329466/84549372-ae84f680-acbc-11ea-94bb-19d49cd6b91b.png">

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1067-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3 (Ubuntu 12.3-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Very minor

**Comment by flamber** [comment]
Fixed by #15385
