### ISSUE TITLE
PO File Edit

### ISSUE THREAD

**Issue by alpertungir** [metabase/metabase#12701]
Po file must be extension file to translate words quickly.

After changing on poeditor, we can export the file and import it to our metabase.

That will be more effective for the localization

**Comment by flamber** [comment]
Hi @alpertungir 
I don't understand what you're asking. Can you please explain in more details.

**Comment by alpertungir** [comment]
> Hi @alpertungir
> I don't understand what you're asking. Can you please explain in more details.

i mean, we shouldn't wait the next version for the translation. There should be an option on metabase administration panel to import .po file so that we can import our language file to metabase. (Or we may be copy our .po file on server)

We already can export from POEditor.
https://poeditor.com/kb/importing-and-exporting-strings

That would be perfect if it's possible.

**Comment by flamber** [comment]
@alpertungir So you're asking for the `.po` files to be modular like the drivers.
You can build your own version (look at `./bin/build translations`)
https://www.metabase.com/docs/latest/developers-guide.html

**Comment by alpertungir** [comment]
> @alpertungir So you're asking for the `.po` files to be modular like the drivers.
> You can build your own version (look at `./bin/build translations`)
> https://www.metabase.com/docs/latest/developers-guide.html

Yes, thank you @flamber , I'll check it.
