### ISSUE TITLE
Can't filter on a JSON field in query builder

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#12705]
On our stats instance, I just tried filtering a `Field containing JSON` using `Contains` in the simple query builder. It added the filter, but when the query tried to run, I got this error:

`ERROR: function lower(json) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 1173`

**Comment by flamber** [comment]
@mazameli Isn't it the same as #708 - and not specific to Field Type, but to database column type.

**Comment by mazameli** [comment]
Huh, yep, you're right of course. For some reason I thought `Contains` worked on JSON cols — bummer.
