### ISSUE TITLE
Disable "Your question took too long" message

### ISSUE THREAD

**Issue by yvaa** [metabase/metabase#12706]
Hello!
Is there a way to disable the message "Your question took too long" after 2 minutes of executing?

![Screenshot_20200615_194842](https://user-images.githubusercontent.com/58484982/84684354-39762300-af41-11ea-9cad-7d12bf18094e.png)

I'm working on big queries and the waiting for 3-5 minutes is ok. This check and screen just lock the work.

:arrow_down: **Please click the +1 reaction instead of leaving a `+1` or +1 comment**

**Comment by flamber** [comment]
Hi @yvaa 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Change your proxy, so it doesn't close the connection. See #12423

**Comment by yvaa** [comment]
@flamber Thank you for fast response. I don't clearly understand  while reading #12423 is it will be fixed on Metabase side? Or I should go to devops team with happy issue to change the seetings specially for Metabase.

**Comment by flamber** [comment]
@yvaa Instead of leaving :confused: emojis and deleting your comments, then change your proxy timeout, since that is what is closing the connection, and :+1: the issue, since that's the only way we count reactions. Alternatively, you can downgrade to 0.34.3, which doesn't use the new style of connection handling.

**Comment by yvaa** [comment]
@flamber I have very complex environment where metabase is the part. I can't "just change the proxy settings". Yes I can roll back to 0.34 but now I have 0.35 on production and it is not working as it worked 4 years since I'm using it. Thank you for fast response.
