### ISSUE TITLE
About .po file

### ISSUE THREAD

**Issue by alpertungir** [metabase/metabase#12700]
We need a small modification on po file. It's replaced on POEditor but how can we import the file again to fix translation mistake.

Should we wait next version , how can we handle it?

**Comment by flamber** [comment]
Hi @alpertungir 
The language files (`.po`) are generated from POEditor, so the translation needs to be fixed there and then it will be imported in next (usually major) release.

**Comment by alpertungir** [comment]
> Hi @alpertungir
> The language files (`.po`) are generated from POEditor, so the translation needs to be fixed there and then it will be imported in next (usually major) release.

i see, thank you @flamber
