### ISSUE TITLE
Upgrade to log4j 2.x

### ISSUE THREAD

**Issue by k2n** [metabase/metabase#12719]
I deploy Metabase via helm chart on Kubernetes, and feed the log output to Datadog via Datadog Agent. It is common log collectors prefer JSON layout as it is hard to handle when a stacktrace is captured as multi-line entries. e.g. [Datadog](https://docs.datadoghq.com/logs/log_collection/java) [Logstash](https://github.com/logstash/log4j-jsonevent-layout)

Unfortunately, they are not an option as the jar needs to be included in the classpath, and possibly need to deal with dependency conflicts. As Metabase uses `slf4j`, I also explored the path to emit JSON in `slf4j` layer as described in [Datadog doc](https://docs.datadoghq.com/logs/log_collection/java/?tab=slf4j#json-format) but it also requires swapping the log implementation jar files.

Log4j ver 2.x natively support [JSON layout](https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout). Would you upgrade log4j to support this feature? I see [the TODO comment in project.clj](https://github.com/metabase/metabase/blob/fe10da79b6d5796f9f976c264a00ba3fd8afd5db/project.clj#L103) but cannot find the issue for it.

I think more users will run Metabase on the container environment and this logging issue becomes more important.

**Comment by si14** [comment]
hey @camsaul @flamber, looks like JSON logging doesn't work on the latest metabase:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/FilterProvider
at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:158)
at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:69)
at org.apache.logging.log4j.core.layout.JsonLayout$Builder.build(JsonLayout.java:102)
...
```

…when log4j2.xml is set to the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Appenders>
        <Console name="STDOUT" target="SYSTEM_OUT">
            <JSONLayout compact="true" eventEol="true" properties="true" stacktraceAsString="true">
            </JSONLayout>
        </Console>
    </Appenders>

    <Loggers>
        <Logger name="metabase" level="INFO"/>
        <Logger name="metabase-enterprise" level="INFO"/>
        <Logger name="metabase.plugins" level="DEBUG"/>
        <Logger name="metabase.middleware" level="DEBUG"/>
        <Logger name="metabase.query-processor.async" level="DEBUG"/>
        <Logger name="com.mchange" level="ERROR"/>

        <Root level="WARN">
            <AppenderRef ref="STDOUT"/>
        </Root>
    </Loggers>
</Configuration>
```

should I create a separate issue, or is this an appropriate issue for this?

**Comment by flamber** [comment]
@si14 Please post Metabase and Java version - I'm quite sure that you're using Java 15, which currently isn't supported #13881

**Comment by si14** [comment]
@flamber I'm using the latest docker container roughly as follows:

```
FROM metabase/metabase:v0.37.4

ENV MB_COLORIZE_LOGS="false" MB_EMOJI_IN_LOGS="false"
COPY metabase/log4j2.xml /opt/mel

ENTRYPOINT ["MB_DB_PASS=foobar JAVA_OPTS=-Dlog4j.configuration=file:/opt/mel/log4j2.xml /app/run_metabase.sh\""]
```

I've looked around and it looks like `jackson` dependencies are marked as optional in `log4j2`, so they don't get into the final fat `metabase.jar` unless specifically asked for. I've tried supplying them with class path manually, but it didn't work and I've given up.

**Comment by flamber** [comment]
@si14 It's now like this `log4j.configurationFile=file:/opt/mel/log4j2.xml` - it was `log4j.configuration` with Log4jv1
https://www.metabase.com/docs/latest/operations-guide/log-configuration.html
Latest release is 0.37.5

**Comment by si14** [comment]
@flamber sorry, I removed changes I've made whilst trying to make it work and winged it in the snippet above. The version I was testing was the latest and the parameter was correct, I got the error only when using `JSONAppender` like DataDog documentation https://docs.datadoghq.com/logs/log_collection/java/?tab=log4j2 suggests:

```
<Appenders>
        <Console name="STDOUT" target="SYSTEM_OUT">
            <JSONLayout compact="true" eventEol="true" properties="true" stacktraceAsString="true"/>
        </Console>
    </Appenders>
```

I believe it's a dependency issue that doesn't trigger unless `JSONLayout` is used.

**Comment by flamber** [comment]
@si14 Okay, please open a new issue and provide enough details (not even sure if this is a feature request or a bug).

**Comment by robdaemon** [comment]
It's a bug if this worked before the Log4j 2 upgrade. Log4j 2 doesn't have the same set of hardcoded dependencies that 1 had, this looks like a missing dependency on `com.fasterxml.jackson.core/jackson-databind`

**Comment by si14** [comment]
@robdaemon before log4j2 there was no way to log in JSON. Now there is, but it indeed needs a few dependencies that are missing from the current distribution.

Here https://github.com/metabase/metabase/blob/master/project.clj#L124 is the dependency on log4j2, and here https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j/2.13.3 we can see that log4j2 has its dependency on jackson packages marked as optional. They don't get installed and don't get included, making logging in JSON impossible.

@flamber I agree it's tricky to say if it's a bug or a feature request, as the headline feature of this issue (logging in JSON) doesn't work. Which type of issue would you like to me use?

**Comment by robdaemon** [comment]
I would likely want us to reject a dependency on `jackson-databind` though, it's history of security vulnerabilities is long. https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html

I spent time at a previous job chasing this and trying to keep up, it's not worth it.

**Comment by si14** [comment]
@robdaemon so there is no hope to see JSON logging in metabase for the time being?

**Comment by camsaul** [comment]
Seconding what @robdaemon, unfortunately we're a small team with limited bandwidth and we have to pick and choose which features we can dedicate time to supporting. Bundling this in to Metabase sounds like a nontrivial amount of maintenance overhead for our team, which would detract from our ability to ship other features and bugfixes.

@si14 can you open a separate GitHub issue for this to track it? If we get a lot of 👍s from the community then we'll reconsider.

**Comment by robdaemon** [comment]
@si14 as a workaround, you can start Metabase with this jar yourself (note, this is a non-standard, unsupported configuration - you would be responsible for tracking CVEs on the `jackson-databind` project):

get the jars:

```bash
wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.5/jackson-annotations-2.10.5.jar
wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.10.5.1/jackson-databind-2.10.5.1.jar
```

start the app:

```bash
java -cp ./jackson-annotations-2.10.5.jar:./jackson-databind-2.10.5.1.jar:./metabase.jar -Dlog4j.configurationFile=file:///home/rroland/temp/log4j2.xml metabase.core
```

In this case, I put the `metabase.jar`, the two jackson jars and your `log4j2.xml` file in the same folder. You can also make a `Dockerfile` that uses our Docker image as the `FROM` parameter and override the `ENTRYPOINT` and such to accomplish this.
