### ISSUE TITLE
Improve Invite Email

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1271]
<details><summary>Older version of the email</summary>

![f471ce08-7403-11e5-844c-44fa14a6f7c1](https://cloud.githubusercontent.com/assets/18193/10891326/2ecea494-8152-11e5-81c5-c316f830845b.png)

</details>

v41 looks like this:
![image](https://user-images.githubusercontent.com/1447303/140609075-b730ef64-80c4-4660-9ae8-a7bc96dba370.png)

**Comment by mazameli** [comment]
Yeah, I actually think the design of this email needs to be slightly reviewed: I would propose that the Join Now button should be more obvious, and that the chart should be a secondary visual element. Maybe the vertical positioning of the chart and button need to be swapped, and I think the chart could be greyscale. Button could also be slightly larger, and the chart slightly smaller.

**Comment by kdoh** [comment]
Yeah other than being kinda a fun joke the chart takes up way too much of the email and fails to provide a good sense of what MB is other than "maybe this has something to do with data.?"

**Comment by karthiknadar1204** [comment]
If this issue is still oen,please assign it to me,i would like to work on it
