### ISSUE TITLE
Native query has 2000 limit even for aggregated data

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#12729]
My understanding was that the limit for showing the results is 2,000 without aggregation and 10,000 with aggregation.

While this is true for Custom/Simple questions, for Native Queries I see 2000 limit even for aggregated data.

**To Reproduce**
- Native Question
```sql
select CREATED_AT, avg(quantity)
from orders
group by CREATED_AT
```
![aggregate1](https://user-images.githubusercontent.com/15974735/84844340-f8dcdf00-affe-11ea-878b-ca8ecafa32e4.png)

- Simple Question
Sample Dataset > AVG of Quantity > Group by CREATED_AT (by minute or hour)

![aggregate2](https://user-images.githubusercontent.com/15974735/84844388-13af5380-afff-11ea-993b-b1e8347fd733.png)

- Metabase version:  v0.35.4 (it happens in previous versions as well)
- Metabase internal database: Postgres

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @vvaezian 
Think it would require parsing of the SQL to be able to understand if it is aggregated or not.
Interestingly, if you make the query and then make a new question using the first as base with Saved Question, then it will return based on un/aggregated.

**Comment by vvaezian** [comment]
@flamber Using Saved Question doesn't work for me because my base question has variables:
```sql
SELECT CASE WHEN (SELECT granularity FROM helper_table WHERE {{granularity}}) = 'Yearly' THEN to_char(date, 'YYYY')
            WHEN (SELECT granularity FROM helper_table WHERE {{granularity}}) = 'Monthly' THEN to_char(date, 'YYYY-mm') 
        END AS "Date"
        , avg(col1) "col1"
FROM my_table
group by "Date"
```
To be able to use the above query as the base for a simple question, I added a column for that variable and did UNION ALL for different values of the variable ('Yearly' and 'Monthly'). I used it as a saved question and used a Field Filter on the added column.   The problem is that both values of the variable ('Yearly' and 'Monthly') can be chosen from the drop-down list at the same time. In the original question, choosing both values led to empty result. But now it adds all results together. Is there a workaround?

**Comment by flamber** [comment]
@vvaezian I've been looking at your query for a couple of minutes, thinking, but no, I don't think I have a workaround for this use-case. Which database type are you querying?

**Comment by vvaezian** [comment]
@flamber Yeah, I couldn't find a way either.  
It's Postgres.

**Comment by saifquraishy** [comment]
Hi , 
there is a work around to bypass the 2000 row limit in metabase. For SQL server add  SET ROWCOUNT 0 beginning of your query, please modify it according to your database type.

**Comment by frozen6169** [comment]
Is there a workaround for Amazon Redshift native queries? Thanks!

**Comment by eddyizm** [comment]
If the limit is 2k shouldn't there at least be pagination? Is this a PRO feature? Trying to wrap my head around this.

**Comment by nodesocket** [comment]
This is absurd, I am trying to graph time series data that is updated every 2 minutes for weeks and months and I don't see a way to do this? I'd be happy just showing a data point every hour instead of every 2 minutes (all data points for example). Is there a way to configure this?

**Comment by paoliniluis** [comment]
@ndobbs if you're running Enterprise, please contact us in support, as we not only provide workarounds but also the product team knows that an Enterprise customer needs this

**Comment by nodesocket** [comment]
@paoliniluis how about expose this functionality for all versions? Seems like a simple option in settings with reasonable constraints would work. Also, the issue around auto-y axis _(don't always start from 0)_ needs to be resolved. Use min/max of values.

**Comment by paoliniluis** [comment]
@nodesocket the functionality is not there and it won't be till the team tackles it. The difference is that when an enterprise customer sends us this we can signal it to the product team

**Comment by paoliniluis** [comment]
@luizarakaki is this changed with the new MB_AGGREGATED_... env var? I haven't checked

**Comment by luizarakaki** [comment]
Yes, it should be (I didn't test)

**Comment by ndobbs** [comment]
> @luizarakaki is this changed with the new MB_AGGREGATED_... env var? I haven't checked

Yes, I just tested it:

![image](https://github.com/metabase/metabase/assets/3474164/fa79db43-27c6-4a16-94ba-4fbbce823379)
