### ISSUE TITLE
the formatting of group by time not show right

### ISSUE THREAD

**Issue by endend20000** [metabase/metabase#12743]
the formatting of group by time not show right

1.click "Ask a question"
2.click "custom question"
3.choose a table which has a date field
4.click "pick a column to group by" choose a field which type is date and "count of rows"(this bug show when here ara two field)
5.click "visualize" show row data
6.click row data's  date field and click "Formating"
7. change "data stype" but the row data not change

![bug1](https://user-images.githubusercontent.com/17372268/85105541-9e818f80-b245-11ea-80b1-474c0dd52449.PNG)
![bug2](https://user-images.githubusercontent.com/17372268/85105565-a5100700-b245-11ea-90b1-7d24f4522db6.PNG)

**Comment by flamber** [comment]
Hi @endend20000 
Please include all the information requested, when opening an issue. At lease "Diagnostic Info".
When you click the raw-data-toggle (bottom-center), then it shows without question formatting, but uses the global formatting defined in Admin > Settings > Formatting.

**Comment by endend20000** [comment]
so can you hide the formatting when it is not work?

**Comment by flamber** [comment]
@endend20000 I don't understand the question, but please use the forum for questions and troubleshooting: https://discourse.metabase.com/
