### ISSUE TITLE
Can't use other questions as variable

### ISSUE THREAD

**Issue by fjlenatz** [metabase/metabase#12747]
Hi guys. I'm currently having a situation with Metabase in the latest release (v0.35.4)
The connection I'm using is a Redshift database we use as a data lake.
I've this simple question:

`SELECT
    homologation.code AS pim_code, homologation.homologated_code
FROM
    eiffel_exporter.category_homologation homologation
INNER JOIN eiffel_pim.category pim_category ON pim_category.code = homologation.code
WHERE
homologated_code IN (
    'dprInfRopaNinos',
    'dprInfRopaNinos',
    'lblClmPurificadoresEnfriadores',
    'lblClmPurificadoresEnfriadores',
    'didácticosYRecreativosDisfracesYMáscaras'
)
[[ AND LOWER(homologation.code) LIKE '%' || LOWER({{pimCategory}}) || '%' ]]
[[ AND LOWER(homologation.homologated_code) LIKE '%' || LOWER({{homologatedCategoryCode}}) || '%' ]];`
Question number 408 

I'm trying to reuse it like this:

`SELECT * FROM {{#408}}`

Or with a JOIN

`INNER JOIN ({{#408}}) homologations ON homologations.pim_code = pim.code`

But in the two cases I'm getting the same error:
`[Amazon](500310) Invalid operation: syntax error at end of input Position: 553;`

Have any idea? My guess is that it's not compatible with Redshift, since the error seems to come from there. But I don't know if I'm doing something wrong, if it's not supported or if it's a bug.

Thank you!

**Comment by flamber** [comment]
Hi @fjlenatz 
This is similar to Saved Questions, which doesn't expose the nested filters either.
#6449 - upvote by clicking +1 on the first post
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by fjlenatz** [comment]
But this doesn't seems to be the case. I tried removing the filters and I'm getting the same error.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
