### ISSUE TITLE
Pass filter values to nested questions

### ISSUE THREAD

**Issue by arruzk** [metabase/metabase#12744]
Metabase 0.35.0 introduced a nice feature "Using an existing question as a sub-query" https://www.metabase.com/docs/v0.35.3/users-guide/13-sql-parameters.html#using-an-existing-question-as-a-sub-query
I don't understand how can I pass filter values to the sub-query (sub-question).
If some of the parameters in a sub-question doesn't have default values I get an error `The sub-query from referenced question #848 failed with the following error: Error building query parameter map`.
It would be really nice to be able not to copy-paste filter logic from question to question (especially it's important if you have grouping in a sub-question and it's not possible to filter on the same set of fields).
Thank you!

**Comment by flamber** [comment]
Hi @arruzk 
This is similar to Saved Questions, which doesn't expose the nested filters either.
#6449 - upvote by clicking :+1: on the first post
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
