### ISSUE TITLE
 Include possibility of icons (font-awesome) in columns

### ISSUE THREAD

**Issue by renatofritola** [metabase/metabase#12759]
As well as having several colors, icons in consultations can help a lot in monitoring screens indicating a status, category etc ...

This facilitates the identification of the data and action on it.

**Comment by flamber** [comment]
Hi @renatofritola 
I don't understand what you're looking for, but it sounds like a duplicate of #1903.
You can already apply colors: https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#conditional-table-formatting

**Comment by renatofritola** [comment]
> Hi @renatofritola
> I don't understand what you're looking for, but it sounds like a duplicate of #1903.
> You can already apply colors: https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#conditional-table-formatting

Colors are limited, only 6 options.
It should be possible for me to inform the color I want (Hexadeciaml, RGB) so I can give you a richer visualization to improve decisions.
