### ISSUE TITLE
Enable drilldown for Native sql queries.

### ISSUE THREAD

**Issue by renatofritola** [metabase/metabase#12758]
Depending on the complexity of the queries and the fact that Metabase is still unable to apply functions for some types of data (interval, boolean etc ...), the option of drilldown based on a native query is necessary.

This option will give more freedom for generating more complex and essential data for users.

**Comment by flamber** [comment]
Hi @renatofritola 
Metabase does have drill-through if you use the SQL question via Saved Questions.
It would require parsing of SQL to be able to do it directly in a Native question - #10525
