### ISSUE TITLE
Missing joined tables on `group_by` option (w/o editor).

### ISSUE THREAD

**Issue by lowercase00** [metabase/metabase#12752]
Hi all.

I've been using Metabase for quite a while (thanks a lot btw), but in my last deployment (V0.35.4), I don't know exactly what happened but table joins disappeared. I have an `orders` table and `line_items` table (FK on `order_id`). Usually I would select the `LineItems` table, and then `group_by` `created_at` (which is a column on `orders` table).

For some strange reason I can only see grouping options of the selected table. To be able to see the grouping I have to manually join the tables myself by showing the editor and selecting which table to join. Also, I can't seem to be able to collapse the `group_by` possible tables. Which was something that I used to do a lot. So it became very hard to use group by as fast as I used to.

The only thing I can think of I've changed from these deployment to my last one is that I've hidden a few tables (none of the ones I'm trying to join), but it's clear to me how that would affect to `join` capabilities.

Any ideas on what I might be doing wrong?
Or this is just a change on how the code works?

Thanks a lot.

**Comment by flamber** [comment]
Hi @lowercase00 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
