### ISSUE TITLE
Chinese map,  Can't display

### ISSUE THREAD

**Issue by pphanwang** [metabase/metabase#12765]
i use this  map json  https://geo.datav.aliyun.com/areas_v2/bound/100000_full.json
In the page, Chinese cannot be displayed like this 

pic like this
https://hans3355.oss-cn-shenzhen.aliyuncs.com/11.png

https://hans3355.oss-cn-shenzhen.aliyuncs.com/22.png

**Comment by flamber** [comment]
Hi @pphanwang 
Without knowing how you're running Metabase, or "Diagnostic Info" or all the other information we ask for, it's hard to help.
But it's likely because you're using a different encoding than `utf8`.
Try starting Metabase with `-Dfile.encoding=UTF-8`
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by pphanwang** [comment]
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "GBK",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_251-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_251",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.251-b08",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.4",
      "date": "2020-05-28",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}

**Comment by pphanwang** [comment]
I used the same geojson file in my Ubuntu system. In this system, can Chinese provinces be displayed correctly? What is the reason for this?

**Comment by pphanwang** [comment]
Thank you for solving the problem. If you encounter the same problem, you can use it。 java -Dfile.encoding=UTF-8 -jar metabase.jar
