### ISSUE TITLE
Embedded dashboad preview blocked due to "child-src" when using https

### ISSUE THREAD

**Issue by Tomasvrba** [metabase/metabase#12778]
**Describe the bug**
When metabase is reverse-proxied with nginx on https, the iframe preview for the fully embedded dashboard is queried over http and fails the `Content-Security-Policy: child-src 'self'` header check.

**Logs**
```
Refused to frame 'http://<myURL>' because it violates the following Content Security Policy directive: "child-src 'self' https://accounts.google.com". Note that 'frame-src' was not explicitly set, so 'child-src' is used as a fallback.
```

When I remove the proxied header with nginx:
```
proxy_hide_header Content-Security-Policy;
add_header Content-Security-Policy "child-src *;";
```

The loading of the preview iframe fails due to mixed content warning:
```
Mixed Content: The page at 'https://<myURL>/dashboard/1' was loaded over HTTPS, but requested an insecure frame 'http://<myURL>/embed/dashboard/...#bordered=true&titled=true'. This request has been blocked; the content must be served over HTTPS.
```

**To Reproduce**
1. Serve metabase over https reverse-proxied with nginx
2. Create a dashboard and share it with full embedding
3. The preview of the shared dashboard will fail to load

**Expected behavior**
The iframe content should be requested over https

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox/77.0, Chrome/83.0.4103.106
- Your operating system: Ubuntu
- Your databases: MariaDB
- Metabase version: v0.35.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Very annoying, the only way to see the dashboard preview is to publish it and embed it on a site to test it.

**Comment by flamber** [comment]
Hi @Tomasvrba 
What have you set your Admin > Settings > General > Site URL to? Sounds like it's still `http://...` instead of `https://...`

**Comment by Tomasvrba** [comment]
> Hi @Tomasvrba
> What have you set your Admin > Settings > General > Site URL to? Sounds like it's still `http://...` instead of `https://...`

Great, thanks! I knew there must be a simple solution to this :laughing:

**Comment by ameed-faridi** [comment]
Not able to find Admin > Settings > General > Site URL
