### ISSUE TITLE
Changing "Display values" on field to "Custom Mapping" causes infinite loop

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#12771]
**Describe the bug**
Changing "Display values" on field to "Custom Mapping" causes infinite loop, but only the first time.

**Logs**
n/a

**To Reproduce**
1. Start a new Metabase instance
2. Go to Data Model -> Sample Dataset -> Reviews
3. Click on field settings for "Rating"
4. Toggle "Display values" to "Custom Mapping"
5. Notice that browser freezes and numerous `POST /api/field/14/values` are sent

**Expected behavior**
Browser to render custom mapping UI

**Screenshots**
n/a

**Information about your Metabase Installation:**
Running off of `metabase/metabase-head:latest`

**Severity**
Not too bad - only happens the first time, and a browser refresh will fix it.

**Additional context**
n/a

**Comment by flamber** [comment]
Changing to P1, since it could also result in blocking by firewalls - besides the huge load and possible browser lockup too.
