### ISSUE TITLE
Default Shown Data With Filter for Field Filter

### ISSUE THREAD

**Issue by IrvanFza** [metabase/metabase#12773]
**Is your feature request related to a problem? Please describe.**
Some of my reference/category tables implement soft delete function to keep track of the old data. When I create a field filter in a question variable that old data also show up.

**Describe the solution you'd like**
A possibility to add a default filter when showing data like in Data Model setting or wherever it will be. This feature will help when showing data in field filters or even in a new question so that I don't need to add that specific filter anymore.

**Describe alternatives you've considered**
If it is not possible to add a default filter, maybe you can add a possibility to create some kind of view table that I can use in the field filter.

**How important is this feature to you?**
5/5

**Comment by flamber** [comment]
Hi @IrvanFza 
I don't understand completely what you're looking for, but it sounds like a duplicate of #6820 or #5245. Can you describe more clearly what this request is about?

**Comment by IrvanFza** [comment]
Yes, that's what I mean. Sorry for not properly browse through the issues first. I will close this issue then.

Anyway, so how is the status of the feature going?

**Comment by flamber** [comment]
@IrvanFza There's 1700+ other issue and a lot of them have more upvotes and priority. There's currently no milestone for this.
