### ISSUE TITLE
Distinct, non-empty sequence of Field clauses 

### ISSUE THREAD

**Issue by Adminaccess** [metabase/metabase#12776]
**Describe the bug**
Creating a  table on PSQL, when I sync the Database, then I am not able to view table data on Metabase. The error comes in like "Distinct, non-empty sequence of Field clauses"
**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html). Tried all possible troubleshooting techniques, SSL is not enabled either, which is usually a reason for this issue.

**To Reproduce**
1. Go to Database
2. Sync Database, rescan field values
3. Go to browse data -> go to respective table

**Expected behavior**
Table data should be visible

**Screenshots**
![Annotation 2020-06-25 122941](https://user-images.githubusercontent.com/24634468/85671536-98752e00-b6df-11ea-8c4f-10f5fb5faaf0.png)

**Severity**
Unable to see data, hence unable to draw visualisations.

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.4.0-174-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @Adminaccess 
There has been many changes since 0.33.6 - latest release is 0.35.4, so please try that version.
And if you're still seeing the problem after update, then check the log for errors - Admin > Troubleshooting > Logs.
