### ISSUE TITLE
OAuth2

### ISSUE THREAD

**Issue by SGStino** [metabase/metabase#12777]
**Is your feature request related to a problem? Please describe.**
There are currently 2 external authentication methods available out of the box: LDAP and Google.
But we can't use a local OAuth provider (like keycloak) or any other online provider like Azure AD, Okta, Auth0, ..

**Describe the solution you'd like**
Would it be possible to open up the OAuth configuration of to support the full standard. Allowing any identity provider to work with metabase.

**Describe alternatives you've considered**
LDAP isn't available everywhere, and writing an account password sync tool isn't really suitable or possible either.

**How important is this feature to you?**
This is currently a wall we're hitting into deploying metabase. No OAuth integration means no single sign on. And that means we'll be looking into another application to provide the functionality metabase could offer.

**Additional context**
Typically, an OAuth client would just need the .well-known/oauth-authorization-server document and client-id/secret as settings.

**Comment by flamber** [comment]
Closing, since this is provided as an Enterprise Edition functionality:
https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-saml.html
Related to #3210
