### ISSUE TITLE
Visualization breaks for native queries with multiple numeric outputs when trendline is activated

### ISSUE THREAD

**Issue by mararn1618** [metabase/metabase#12781]
**Describe the bug**
 - I have two nested native questions/queries
 - The outer question returns multiple numeric values
 - Only part of the numeric outputs is selected for visualization on the Y-axis (e.g. show only 2 of 3 available series)
 - Trendline is activated

The trendline does work if ALL numeric values are selected for visualization.
The whole visualization breaks if ONLY PART of the numeric values are selected for visualization.

This happens:
 - In the Preview when editing the Question/Query
 - In the Dashboard

**Logs**
Javascript error when trendline activated
```
app-main.bundle.js?31778b9e3b01ff7193ac:5 TypeError: Cannot read property 'card' of undefined
    at P (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at Object.series (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at app-main.bundle.js?31778b9e3b01ff7193ac:5
    at app-main.bundle.js?31778b9e3b01ff7193ac:5
    at G (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at Object.t.lineRenderer [as renderer] (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at t.value (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at t.value (app-main.bundle.js?31778b9e3b01ff7193ac:5)
    at e.notifyAll (vendor.bundle.js?31778b9e3b01ff7193ac:1)
    at d.close (vendor.bundle.js?31778b9e3b01ff7193ac:1)
```

**To Reproduce**
Inner Query (later referred to as {{# 3}})
```
select  `ShopifyAppInstallation`.ShopifyAppHandle,  `ShopifyAppInstallation`.ShopifyShopName,`ShopifyAppInstallation`.InstallDate, str_to_date(concat(yearweek(`ShopifyAppInstallation`.`InstallDate`), ' Sunday'), '%X%V %W') AS `InstallDateWeekly`,

usv_small.value as `usv_small_value`, usv_big.value as `usv_big_value`,
1 as `AllInstallationCount`,

IF((usv_small.value is not NULL
AND length(usv_small.value)>0
AND usv_big.value is not NULL
AND length(usv_big.value)>0), 1, 0)
AS `FullSetupCount`

from `ShopifyAppInstallation`
join ShopifyApp app on ShopifyAppInstallation.ShopifyAppHandle = app.Handle
join AppSetting setting_small on (setting_small.ShopifyAppHandle = app.Handle AND setting_small.Handle = 'discount_small')
join AppSetting setting_big on (setting_big.ShopifyAppHandle = app.Handle AND setting_big.Handle = 'discount_big')
join UserSettings us on us.ID = `ShopifyAppInstallation`.UserSettingsID

left join UserSettingValue usv_small on (usv_small.UserSettingsID = us.ID AND usv_small.AppSettingID = setting_small.ID)
left join UserSettingValue usv_big on (usv_big.UserSettingsID = us.ID AND usv_big.AppSettingID = setting_big.ID)

where
`ShopifyAppInstallation`.ShopifyAppHandle = 'clawgame'

[[AND {{date}}]]

```

Outer Query
```
select min(completion.`InstallDate`),sum(completion.`AllInstallationCount`),sum(completion.`FullSetupCount`),sum(completion.`FullSetupCount`)/sum(completion.`AllInstallationCount`) as `CompletionRatio`

from {{#3}} as completion

join `ShopifyAppInstallation` on `ShopifyAppInstallation`.ShopifyAppHandle=completion.ShopifyAppHandle AND `ShopifyAppInstallation`.ShopifyShopName=completion.ShopifyShopName

[[WHERE {{date}}]]

group by completion.`InstallDateWeekly`
 
;
```

**Expected behavior**
The visualization should be shown with trendlines.

**Screenshots**
Ok
![image](https://user-images.githubusercontent.com/15421484/85715578-e4c66b00-b6eb-11ea-897e-5a406e289fb6.png)

Not Ok
![image](https://user-images.githubusercontent.com/15421484/85715697-045d9380-b6ec-11ea-996a-4cd5ed9e78b5.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "de",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.4.0-127-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.30"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Medium.

My workaround is to comment out not needed numeric values. However this also means that I have to replicate certain questions a few times. :(

**Workaround**
Do something like this
```
select min(completion.`InstallDate`),
-- sum(completion.`AllInstallationCount`),
-- sum(completion.`FullSetupCount`),
sum(completion.`FullSetupCount`)/sum(completion.`AllInstallationCount`) as `CompletionRatio`
```

**Comment by flamber** [comment]
Reproduce:
1. Simple question > Sample Dataset > Orders
2. Summarize "Average of Subtotal" and "Sum of Total" by CreatedAt:Year
3. Visualization Settings > Display > activate "Trend line"
4. Visualization Settings > Display > Data > remove "Sum of Total" - the chart is gone and browser console has error - clicking "Add another series..." brings the chart back.
![Screencast-2020-06-25_16 54 56](https://user-images.githubusercontent.com/1447303/85744607-51019880-b705-11ea-8831-3bb2c70cd283.gif)
