### ISSUE TITLE
Add Links to dashboard

### ISSUE THREAD

**Issue by abmath** [metabase/metabase#12785]
I want to create clickable hyperlinks using <a href> tags. I am able to add complete URL but I want to give a "click here" link

**Comment by flamber** [comment]
Hi @abmath 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://www.metabase.com/blog/markdown-in-dashboards/index.html
https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#column-formatting-options
