### ISSUE TITLE
Field Filter variables in SQL question don’t show table name when connecting filters in dashboard

### ISSUE THREAD

**Issue by mlm603** [metabase/metabase#12792]
**Describe the bug**
When you create a SQL question with parameters tied to fields that both have the same name (e.g. ID in two different tables), when you go to apply a dashboard filter to the tile, you can't tell which parameter is which.

**To Reproduce**
Build a SQL query joining the Reviews and Products tables from the Sample dataset, with parameters to filter on ID from each table.
<img width="1429" alt="Screen Shot 2020-06-26 at 1 23 59 PM" src="https://user-images.githubusercontent.com/13624950/85884251-549e2980-b7b0-11ea-858c-c9f976fb0fae.png">

Add the question to a dashboard and add an ID filter.

Try to connect the ID filter to the question. Both parameters are called ID.
![Screen Shot 2020-06-26 at 1 20 14 PM](https://user-images.githubusercontent.com/13624950/85884167-31737a00-b7b0-11ea-82dc-308b360fcff7.png)

**Information about your Metabase Installation:**
Metabase v1.35.4

**Severity**
Low severity. It's confusing, but we can figure it out by just looking at the question and seeing which order the parameters were defined in.

**Comment by flamber** [comment]
Fixed by #13427
