### ISSUE TITLE
Metabase Error when Adding a Map

### ISSUE THREAD

**Issue by MTBMike** [metabase/metabase#12796]
I am testing the function to add a map in Metabase and I am running into an error. This is what I have done;

1. Created a GeoJSON file from a shapefile using FME translator
2. Uploaded the .json file to GitHub. The .json file previews in the Github map view correctly
3. Copied the raw link location and used that in in "**URL for the GeoJSON file you want to use**" parameter in the map creation dialogue
4. Click "Load" and then I receive an error "**r.features is undefined**"

So, I am not sure why I am getting the error. The file only contains around 10 records and is very small. It populates correctly in Git. 

For the record, I am running a local install of Metabase using v0.35.4. I'm on Windows 10 and browsing with Firefox 77.0.1.

**Comment by flamber** [comment]
Hi @MTBMike 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Post the map - here's an example of how the structure should look: https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/us-states.json

**Comment by MTBMike** [comment]
flamber, my apologies. It's been a long day. I thought I was typing this up in Discourse and didn't even look to see this is Git. thanks for pointing that out! I'll move it over there.
