### ISSUE TITLE
More powerful pivot function

### ISSUE THREAD

**Issue by willtoth** [metabase/metabase#12800]
**Is your feature request related to a problem? Please describe.**
According to the docs, pivot function today seems to only pivot when there is "one numeric column and two grouping columns". This is fairly limiting when trying to prepare data for visualization. Our data is entered as a discrete action with a 'type' with several pieces of meta-data associated with it. For instance here is the data format:

![image](https://user-images.githubusercontent.com/8404869/85932520-61934980-b892-11ea-9ccb-6eb34a6dc756.png)

With the data as  it is, we can visualize where each action happened, but a pivot would allow us to view things such as 'number of *action-type* performed by *team*'

**Describe the solution you'd like**
Being able to pivot this data with more control would allow us to view and aggregate data by type. The absolute best example in any tool I've ever used is the way it is handled in Spotfire.

![image](https://user-images.githubusercontent.com/8404869/85932553-a8813f00-b892-11ea-8bd3-52533e7a379a.png)

The result of this single action takes our data from 'tall-skinny' to 'short-wide' in a number of customizable ways.

I would see this solution in both the existing data-editor, as well as the ability to use the result of the pivot as a new virtual table https://github.com/metabase/metabase/issues/2214. That way, as a new table it would be easy to start visualizations from the result, as well as utilize the other features existing today with tables such as x-rays (which don't make a lot of sense with the data in its raw format).

![image](https://user-images.githubusercontent.com/8404869/85932649-81773d00-b893-11ea-9d96-5044deb0256d.png)

**Describe alternatives you've considered**
'Write SQL' and trying to pivot that way, but this becomes less accessible to people without SQL knowledge.

![image](https://user-images.githubusercontent.com/8404869/85932700-ed59a580-b893-11ea-92c1-2fdab4b2efa0.png)

**How important is this feature to you?**
For our use-case, the *type* field changes at least yearly, and specifying a type allows us to keep the rest of our tools 'generic' since actions can be recorded with the only change being actually visualizing it. If we pivoted the data before entering it into our database, it would require adding and removing columns and result in overall less flexibility.

**Additional context**

**Comment by flamber** [comment]
Hi @willtoth 
Sounds like a duplicate of #8572 - and #3769 might be interesting too. Do you agree, then please close this and upvote the issues.

**Comment by willtoth** [comment]
I agree, probably closer to number 3769
