### ISSUE TITLE
When adding a dashboard, possibility to add multiple questions at one time

### ISSUE THREAD

**Issue by PetiPandaRou** [metabase/metabase#12809]
**Is your feature request related to a problem? Please describe.**
I have the habit to build all my requests than create a dashboard with all requests I created.

**Describe the solution you'd like**
When you click on the plus icon to add questions, you can select multiple questions to add to the dashboard at one time, instead of doing the Add process multiple times.

**Describe alternatives you've considered**
For now, I don't have any alternatives in mind.

**How important is this feature to you?**
I think it is not a really high priority feature, but it will help a lot in dashboard building.

**Additional context**
You can add an option when multi-selecting questions, in addition of Archive and Move:  
![image](https://user-images.githubusercontent.com/323248/86023374-e36aaa80-ba2b-11ea-9ccc-c4c9089a560e.png)

Or adding the possibility to multi-select questions in the Dashboard (+) button.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related #9777 and #10095
