### ISSUE TITLE
problem connecting to SQL

### ISSUE THREAD

**Issue by rhiggins4** [metabase/metabase#12818]
**Describe the bug**
Trying to create a connection to MS SQL database. I realize this is a common issue that seems to be solved by setting SQL server port to static 1433. Verified port is static and set to 1433. User credentials is a SQL database user account, I have verified via a terminal I can connect to database server but still getting connection errors.

Metabase is running on local machine which is windows 10
SQL server is 11.0.5388.0

**Logs**
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:43:09-05:00 INFO metabase.core Metabase Initialization COMPLETE
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:43:18-05:00 WARN metabase.routes.index Locale 'en' not found.
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:43:18-05:00 INFO metabase.middleware.exceptions Request canceled before finishing.
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:43:18-05:00 INFO metabase.middleware.exceptions Request canceled before finishing.
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:43:20-05:00 DEBUG metabase.middleware.log GET /api/user/current 401 2.7 ms (0 DB calls) 
"Unauthenticated"

[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:43:20-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 7.6 ms (0 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:43:49-05:00 DEBUG metabase.middleware.log POST /api/util/password_check 200 5.8 ms (0 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:43:57-05:00 DEBUG metabase.middleware.log POST /api/util/password_check 200 963.5 µs (0 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:16-05:00 INFO metabase.driver.impl Initializing driver :sqlserver...
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:16-05:00 INFO metabase.plugins.classloader Added URL file:/C:/Users/rhiggins/Downloads/plugins/sqlserver.metabase-driver.jar to classpath
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:16-05:00 DEBUG metabase.plugins.init-steps Loading plugin namespace metabase.driver.sqlserver...
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:16-05:00 INFO metabase.driver.impl Registered driver :sqlserver (parents: [:sql-jdbc]) 
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:16-05:00 DEBUG metabase.plugins.jdbc-proxy Registering JDBC proxy driver for class com.microsoft.sqlserver.jdbc.SQLServerDriver...
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:21-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:21-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:21-05:00 DEBUG metabase.middleware.log POST /api/setup/validate 400 5.0 s (0 DB calls) 
{:errors {:dbname "Timed out after 5.0 s"}}

[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:26-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:26-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:45:26-05:00 DEBUG metabase.middleware.log POST /api/setup/validate 400 5.0 s (0 DB calls) 
{:errors {:dbname "Timed out after 5.0 s"}}

[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: Sync metadata for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: step 'sync-timezone' for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: step 'sync-timezone' for h2 Database 1 'Sample Dataset' (332.5 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: step 'sync-tables' for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: step 'sync-tables' for h2 Database 1 'Sample Dataset' (30.3 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.sync-metadata.tables Updating description for tables: (Table  'PUBLIC.PEOPLE' Table  'PUBLIC.REVIEWS' Table  'PUBLIC.ORDERS' Table  'PUBLIC.PRODUCTS')
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: step 'sync-fields' for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: step 'sync-fields' for h2 Database 1 'Sample Dataset' (56.0 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: step 'sync-fks' for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: step 'sync-fks' for h2 Database 1 'Sample Dataset' (19.0 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: step 'sync-metabase-metadata' for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: step 'sync-metabase-metadata' for h2 Database 1 'Sample Dataset' (66.1 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: Sync metadata for h2 Database 1 'Sample Dataset' (572.5 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: Analyze data for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: step 'fingerprint-fields' for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [*******···········································]    15% Table 3 'PUBLIC.PEOPLE'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [***************···································]    31% Table 4 'PUBLIC.REVIEWS'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: step 'fingerprint-fields' for h2 Database 1 'Sample Dataset' (25.0 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: step 'classify-fields' for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.analyze classify-fields Analyzed [***********************···························]    46% Table 3 'PUBLIC.PEOPLE'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: step 'classify-fields' for h2 Database 1 'Sample Dataset' (5.7 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.analyze classify-fields Analyzed [******************************····················]    62% Table 4 'PUBLIC.REVIEWS'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util STARTING: step 'classify-tables' for h2 Database 1 'Sample Dataset'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.analyze classify-tables Analyzed [**************************************············]    77% Table 3 'PUBLIC.PEOPLE'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: step 'classify-tables' for h2 Database 1 'Sample Dataset' (6.8 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.analyze classify-tables Analyzed [**********************************************····]    92% Table 4 'PUBLIC.REVIEWS'
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:50:00-05:00 INFO metabase.sync.util FINISHED: Analyze data for h2 Database 1 'Sample Dataset' (51.6 ms)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:56:01-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:56:01-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:56:01-05:00 DEBUG metabase.middleware.log POST /api/setup/validate 400 5.0 s (0 DB calls) 
{:errors {:dbname "Timed out after 5.0 s"}}

[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:56:06-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:56:06-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T11:56:06-05:00 DEBUG metabase.middleware.log POST /api/setup/validate 400 5.0 s (0 DB calls) 
{:errors {:dbname "Timed out after 5.0 s"}}

[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:00:00-05:00 INFO metabase.task.send-pulses Sending scheduled pulses...
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:14-05:00 INFO metabase.models.user Adding User 1 to All Users permissions group...
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:14-05:00 INFO metabase.models.user Adding User 1 to Admin permissions group...
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:14-05:00 DEBUG metabase.middleware.log POST /api/setup 200 274.8 ms (34 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:25-05:00 DEBUG metabase.middleware.log GET /api/user/current 200 329.3 ms (7 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:25-05:00 DEBUG metabase.middleware.log GET /api/database 200 23.9 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:25-05:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 156.2 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:25-05:00 DEBUG metabase.middleware.log GET /api/collection/root 200 17.2 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:47-05:00 DEBUG metabase.middleware.log GET /api/setting 200 3.6 ms (0 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:47-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 23.8 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (0 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:03:47-05:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 25.1 ms (13 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (47 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:04:55-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:04:55-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:05:00-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:05:00-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:05:00-05:00 DEBUG metabase.middleware.log POST /api/database/validate 200 10.0 s (0 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:05:30-05:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 3.3 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:13:01-05:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 3.4 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:03-05:00 INFO metabase.middleware.exceptions Request canceled before finishing.
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:03-05:00 INFO metabase.middleware.exceptions Request canceled before finishing.
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:05-05:00 DEBUG metabase.middleware.log GET /api/user/current 200 5.7 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 7/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:05-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 21.1 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:05-05:00 DEBUG metabase.middleware.log GET /api/database 200 7.8 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:05-05:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 11.5 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:05-05:00 DEBUG metabase.middleware.log GET /api/collection/root 200 3.0 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:05-05:00 DEBUG metabase.middleware.log GET /api/database 200 4.9 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:06-05:00 DEBUG metabase.middleware.log GET /api/automagic-dashboards/database/1/candidates 200 430.5 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:14-05:00 DEBUG metabase.middleware.log GET /api/setting 200 1.2 ms (0 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:14-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 15.9 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 7/50 (0 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:14-05:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 9.0 ms (13 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (48 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:15:28-05:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 2.4 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (48 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:18:21-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:18:21-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:18:26-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:18:26-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:18:26-05:00 DEBUG metabase.middleware.log POST /api/database/validate 200 10.0 s (0 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:18:57-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:18:57-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:19:02-05:00 ERROR metabase.driver.util Database connection error
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:19:02-05:00 ERROR metabase.api.database Cannot connect to Database
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:19:02-05:00 DEBUG metabase.middleware.log POST /api/database/validate 200 10.0 s (0 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:19:08-05:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 3.0 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:20:35-05:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 2.3 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:37-05:00 INFO metabase.middleware.exceptions Request canceled before finishing.
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:38-05:00 DEBUG metabase.middleware.log GET /api/user/current 200 4.3 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 7/50 (0 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:38-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 16.4 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:38-05:00 DEBUG metabase.middleware.log GET /api/database 200 5.3 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:38-05:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 10.9 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:38-05:00 DEBUG metabase.middleware.log GET /api/collection/root 200 2.4 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:39-05:00 DEBUG metabase.middleware.log GET /api/database 200 6.8 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:39-05:00 DEBUG metabase.middleware.log GET /api/automagic-dashboards/database/1/candidates 200 17.4 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:44-05:00 DEBUG metabase.middleware.log GET /api/setting 200 1.1 ms (0 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (0 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:44-05:00 DEBUG metabase.middleware.log GET /api/session/properties 200 13.9 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 7/50 (0 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:44-05:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 10.3 ms (13 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (47 total active threads) Queries in flight: 0 (0 queued)
[be8c6f5d-89de-4781-93d4-bfaae55a3140] 2020-06-30T12:23:53-05:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 2.4 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (0 idle, 0 queued) (47 total active threads) Queries in flight: 0 (0 queued)

**Comment by flamber** [comment]
Hi @rhiggins4 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Normally `Timed out after 5.0 s` means wrong host, port or a firewall/antivirus is blocking.

**Comment by TurkerTunali** [comment]
Did you try it with an empty port number? I mean don't enter anything in the port section.

**Comment by rhiggins4** [comment]
Thank you for responding, I know this is stupid but I did not realize that the grayed version of the port number shown on the screen really was there as a sample. I ASSUMED that it was already entered. Once I actually entered 1433 in the port # the connection information it worked. 

Sorry , I feel really dumb, but thanks for responding.

**Comment by TurkerTunali** [comment]
You can't believe what I experienced with that setting. I was demonstrating my BI skills with their live data and suddenly "No connection" :)

**Comment by flamber** [comment]
#12786 is going to make that more clear.

**Comment by rhiggins4** [comment]
Thank you, that is a better UI.
________________________________

**Comment by TurkerTunali** [comment]
This one is definitely better.
