### ISSUE TITLE
Allow admins to set how many hours it takes for an email invite to expire

### ISSUE THREAD

**Issue by markberger** [metabase/metabase#12829]
**Is your feature request related to a problem? Please describe.**
As an admin, I need to reset passwords frequently after setting up user accounts. Right now email invites expire after 48 hours, but this is too fast when:

1.  Setting up accounts on a Friday. These emails will expire before Monday
2. Working with other teams / orgs. I might set up an account for an individual, but this person doesn't need Metabase for their job until 3 or 4 days later.

**Describe the solution you'd like**
I should be able to set how many hours should pass before an invite expires in the admin interface.

**Describe alternatives you've considered**
Having someone else on my team reset passwords for me 😛 

**How important is this feature to you?**
I would be grateful for this feature but it is not high priority.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @markberger 
Was checking if we had an environment variable for it, but it's hardcoded:
https://github.com/metabase/metabase/blob/1f3a7680af380d7b84c3fc5ac545a2656beba610/src/metabase/api/session.clj#L190-L192

**Comment by mazameli** [comment]
I'm adding this to our internal product doc of potential constants to expose via environment variable.

**Comment by abdulazizali77** [comment]
@markberger @flamber @mazameli PTAL https://github.com/metabase/metabase/pull/32132
