### ISSUE TITLE
SAML SSO Configuration aggressively caching

### ISSUE THREAD

**Issue by danlopez** [metabase/metabase#12827]
When configuring SAML SSO, the attribute `SAML Application Name` appears to be cached aggressively. The application does not appear to respect any changes to this attribute until performing an application restart. This makes it challenging to configure SAML, which often requires a lot of trial and error. 

**Logs**
N/A

**To Reproduce**
1. Configure SAML SSO with any value for SAML Application Name. 
2. Change the value for SAML Application Name to something else and use a Chrome plugin to capture the Authn request - you'll note that the Issuer is set to the first value

**Expected behavior**
Each time you change the SAML Application Name attribute, I would expect the value to change in any SP initiated auth request. 

**Information about your Metabase Installation:**

This is Metabase enterprise v1.35.4.1; running in a docker container with a postgres backend.  

**Severity**
We figured this out, but it will definitely bother future users trying to configure SAML

**Comment by flamber** [comment]
Hi @danlopez Please use support mail, when using Enterprise Edition. We have an internal issue tracking this (177).

**Comment by danlopez** [comment]
This isn't an issue for anymore, as we figured this out from some significant speculation, so we didn't want to submit a support ticket. Additionally, I would suggest documenting this somewhere public in case others come across this issue.

**Comment by flamber** [comment]
@danlopez Would this have been enough? #12828
We still need to fix the underlying issue, but just trying to avoid anyone else spending time trying to debug.

**Comment by danlopez** [comment]
I think that this would be great to add - thanks for jumping on this quickly.
