### ISSUE TITLE
Random continuous queries running on MySQL via metabase

### ISSUE THREAD

**Issue by adityamertia** [metabase/metabase#12836]
Problem statement:
We have a few pulses and questions scheduled to run for 2 hours in the morning from 7 am to 9 am. But what we observe is that there are many queries (not scheduled or supposed to run) that are continuously running on MySQL database all day. Even after killing the queries Metabase automatically starts new queries on MySQL. This loads our database instance and is unexpected behavior. The reported timezone is set in admin->general->report timezone is set to Asia/Calcutta

In troubleshooting logs i see the following error statements:
`2020-07-02T12:30:52+05:30 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Calcutta' for :mysql database `

Metabase version: 0.35.4 (latest)
Databse: MySQL 5.7.30
Database and Metabase server timezone: Asia/kolkata (GMT+5:30)
Metabase run command: `java -jar /opt/metabase/metabase.jar`

Troubleshooting diagnostic Info:
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10-post-Ubuntu-2ubuntu218.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10-post-Ubuntu-2ubuntu218.04",
    "os.name": "Linux",
    "os.version": "5.3.0-1019-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

Any help will be appreciated.
Thanks
Aditya

**Comment by sbelak** [comment]
Can you show an example of such a query? With what frequency are they run? Can you check the logs if the sync process encounters any errors?

**Comment by adityamertia** [comment]
So the queries are random and they are consistent. If I kill a running query from Metabase, then another one automatically starts almost immediately, and this way most of the db is occupied all the time.
From the logs i see few sync errors and these tables are also the ones which are seen in running query processlist.

```
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.sync.util Error fingerprinting Table 74 'v_appLogSummary'
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Calcutta' for :mysql database
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.sync.util Error fingerprinting Table 114 'v_appOpeningCustomerDashboard'
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 INFO metabase.sync.analyze fingerprint-fields Analyzed [**********········································] 😞 20% Table 356 'v_app_society'
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Calcutta' for :mysql database
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.sync.util Error fingerprinting Table 94 'v_basketDashboard'
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Calcutta' for :mysql database
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.sync.util Error fingerprinting Table 161 'v_categoryDashboard'
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Calcutta' for :mysql database
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.sync.util Error fingerprinting Table 472 'v_customerCreditDashboard'
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Calcutta' for :mysql database
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.sync.util Error fingerprinting Table 266 'v_customerDashboard'
[a3c35fec-d751-4d5e-aa97-9c9b2ab7f8d2] 2020-07-02T13:47:40+05:30 ERROR metabase.driver.sql-jdbc.execute Failed to set timezone 'Asia/Calcutta' for :mysql database
```

**Comment by sbelak** [comment]
Can you show an example for one of these queries.

**Comment by adityamertia** [comment]
Example query is as below (Btw these are all views):

`SELECT `v_orderSummary`.`id` AS `id`, `v_orderSummary`.`brandId` AS `brandId`, `v_orderSummary`.`brandName` AS `brandName`, `v_orderSummary`.`categoryId` AS `categoryId`, `v_orderSummary`.`categoryName` AS `categoryName`, `v_orderSummary`.`clusterId` AS `clusterId`, `v_orderSummary`.`clusterName` AS `clusterName`, `v_orderSummary`.`customerId` AS `customerId`, `v_orderSummary`.`customerName` AS `customerName`, `v_orderSummary`.`date` AS `date`, `v_orderSummary`.`endDate` AS `endDate`, `v_orderSummary`.`hubId` AS `hubId`, `v_orderSummary`.`hubName` AS `hubName`, `v_orderSummary`.`isBundle` AS `isBundle`, `v_orderSummary`.`modifiedOn` AS `modifiedOn`, `v_orderSummary`.`opHubId` AS `opHubId`, `v_orderSummary`.`phone` AS `phone`, `v_orderSummary`.`product_name` AS `product_name`, `v_orderSummary`.`product_weight` AS `product_weight`, `v_orderSummary`.`productId` AS `productId`, `v_orderSummary`.`quantity` AS `quantity`, `v_orderSummary`.`sheet` AS `sheet`, `v_orderSummary`.`societyId` AS `societyId`, `v_orderSummary`.`societyName` AS `societyName`, `v_orderSummary`.`startDate` AS `startDate`, `v_orderSummary`.`subcategoryId` AS `subcategoryId`, `v_orderSummary`.`subcategoryName` AS `subcategoryName`, `v_orderSummary`.`towerName` AS `towerName`, `v_orderSummary`.`unit` AS `unit`, `v_orderSummary`.`vendorId` AS `vendorId`, `v_orderSummary`.`vendorName` AS `vendorName` FROM `v_orderSummary` LIMIT 2000;`

There are two stacktraces in the attached log, but those are due to the manual killing of the query process and may not be relevant. However i have attached full log file @ [https]://file.io/ZTbKb6Sj.

Apart from this there are no other stack trace. Any clue that you could find with this information?

Thanks

**Comment by flamber** [comment]
Sounds similar to #12567, but you are at least getting `ERROR metabase.sync.util Error fingerprinting`

**Comment by adityamertia** [comment]
These both issues mentioned are in open state. Should we expect this issue to get fixed once #12567 and #9163 get closed?
Till then do you have any suggestions on this? The database is loaded most of the time. Will downgrading to a lower version help?

**Comment by flamber** [comment]
@adityamertia I don't know if Simon is seeing something different here compared to the other issues, but this issue is at least related, if not duplicate, of the other issues. Don't have a workaround and doubt downgrading will make any difference.

**Comment by flamber** [comment]
@adityamertia Can you check your log (not Admin > Troubleshooting > Logs), since it seems like the stacktrace wasn't included.
This might depend on how you're running Metabase, but probably `/var/log/metabase.log`

**Comment by flamber** [comment]
Closing, since without the stacktrace it is not possible to figure out what is going on.

**Comment by adityamertia** [comment]
My /var/log/metabase.log file is empty. But this issue is largely seen on a daily basis. Is there a fix for this yet? Else Metabase is not usable.

**Comment by flamber** [comment]
@adityamertia 

Have you tried 0.36.3?

Since it doesn't seem like you're running Metabase [as a service](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-debian.html), then the stacktrace is posted in the console.
Without proper logging and information, it's really difficult to know what's going on.

If you're saying that the query you posted in https://github.com/metabase/metabase/issues/12836#issuecomment-653512577 is being executed several times a day, then it sounds like someone is viewing that table in Metabase.
You can check `query` and `query_execution` to see who is running those queries.

**Comment by adityamertia** [comment]
@flamber I have upgraded to 0.36.3 and using docker based setup. I still see same issue, the MySQL database is running queries randomly and choking database on IO, cpu and memory. 

I verified no one is checking metabase in that duration. And those queries are being run by metabaseuser itself. Looks like some metabase cron that's continuously running even if i manually kill all metabase queries, instantly there are many more queries automatically started.

**Comment by flamber** [comment]
@adityamertia Can you please post examples of queries that are executed and choking your database?
Metabase runs several queries based on a cron like sync, scan, pulses, etc.
Try starting Metabase with extra debug logging:
```
java -Dlog4j.configuration="https://log4j.us/templates/metabase?trace=metabase.sync,metabase.task" -jar metabase.jar
```
That should make it easier to spot tasks executing routine queries.

**Comment by elaykilla** [comment]
Having the same issue since update. Getting periodic analysis of database Table. Log entry looks like 

`09-15 04:00:24 [1mINFO sync.analyze[0m :: [34mclassify-tables Analyzed [*********************************************·····] 😍 90% Table 93 'T_USER_LOGS'[0m`

![image](https://user-images.githubusercontent.com/5121787/93206452-b63fb580-f759-11ea-80b2-3c32ccb6d769.png)

Database is only chocking when this is done on very large tables (> 50M rows). We have no choice but to shut down server. 

This has only started happening after update to v0.36.5.1.

![image](https://user-images.githubusercontent.com/5121787/93206798-40881980-f75a-11ea-86ae-5499c4736333.png)

**Comment by flamber** [comment]
@elaykilla That's the default hourly sync and daily scan:
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis
Which version were you using before?

**Comment by elaykilla** [comment]
Alright Thanks!! We're going to try and monitor the next days and see how that goes.
We were previously using v0.34.1 from January.
