### ISSUE TITLE
Port remaining e2e tests to Cypress

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#12831]
These are the remaining "old-style" e2e tests. We've ported some to Cypress but not all.

Need to be ported and then deleted
- [x] metabase/home/HomepageApp.e2e.spec.js
   Creates entities that populate the activity feed and check they appear.
- [x] metabase/collection/initial_collection.e2e.spec.js
   Check that collections are created in the correct place by default. Probably doesn't need to be e2e.
- [x] metabase/alert/alert.e2e.spec.js
- [x] metabase/dashboard/dashboard.e2e.spec.js
   Mostly checked in parameters tests, but still need to check the revisions.
- [x] metabase/visualizations/drillthroughs.e2e.spec.js
   Currently marked as pending. It has a thorough list of what needs to be tested, but it's probably too much detail to test in Cypress.
- [x] metabase/redux/metadata.e2e.spec.js
   Should just be deleted rather than ported
- [x] metabase/reference/segments.e2e.spec.js
- [x] metabase/reference/databases.e2e.spec.js
   Cypress test exists, but a few cases need to be ported.
- [x] metabase/reference/metrics.e2e.spec.js
- [x] metabase/selectors/metadata.e2e.spec.js
   Should be converted to a unit or integration test.
- [x] metabase/admin/settings/SettingsAuthenticationOptions.e2e.spec.js
   Should probably be added to existing admin settings cypress test.
- [x] metabase/admin/people/people.e2e.spec.js
   Permissions updating tests need to be ported.

These can just be deleted
- [x] metabase-lib/lib/Question.e2e.spec.js
- [x] metabase/admin/settings/settings.e2e.spec.js
- [x] metabase/query_builder/components/NativeQueryEditor.e2e.spec.js
   It's empty and can we already have cypress tests.
- [x] metabase/visualizations/components/ObjectDetail.e2e.spec.js
- [x] metabase/visualizations/components/Visualization.e2e.spec.js
   No need to be e2e. I'm pretty sure it's already covered elsewhere.
- [x] metabase/modes/components/drill/SortAction.e2e.spec.js
- [x] metabase/modes/components/drill/QuickFilterDrill.e2e.spec.js
- [x] metabase/modes/components/drill/SummarizeColumnByTimeDrill.e2e.spec.js
- [x] metabase/modes/components/drill/TimeseriesPivotDrill.e2e.spec.js
- [x] metabase/modes/components/drill/SummarizeColumnDrill.e2e.spec.js
- [x] metabase/modes/components/drill/PivotByCategoryDrill.e2e.spec.js
   This is the only non-empty drill e2e test. I think they can all be deleted and maybe we can add more unit tests.

cc @dacort

**Comment by Opalevanescence** [comment]
I recommend that someone else port `metadata.e2e.spec.js` and double-check that `PivotByCategoryDrill.e2e.spec.js` is covered with other unit tests, since I haven't written unit or integration tests before. 
The only other test I haven't made a ported PR for is `drillthroughs.e2e.spec.js`, which I will come back to next week.
