### ISSUE TITLE
Snowflake connection submits a lot of ALTER SESSION queries

### ISSUE THREAD

**Issue by HugoManoMano** [metabase/metabase#12864]
Hello,

We just added a Snowflake connection, and we're seeing a lot of meta queries being submitted very frequently, which prevent the virtual warehouse used in the connexion to shut down after period of inactivity defined on Snowflake side (see [documentation](https://docs.snowflake.com/en/user-guide/warehouses-overview.html#auto-suspension-and-auto-resumption)). I identified 3 different type of queries (see screenshot attached - with detailed timestamp of submission) : alter timezone, rollback, alter autocommit.

My question is : is there a way to prevent those queries from being submitted so that our VW typically can auto suspend during the night, as we would have expected ?
![Capture d’écran de 2020-07-08 11-27-25](https://user-images.githubusercontent.com/61005730/86902447-43d5a800-c10e-11ea-8577-17af18fd079e.png)
 
Here is our current setup :
- Metabase v1.34.2
- Database sync : daily at 9pm
- Auto scan set to "never, i'll do this manually"  

Thanks a lot for your help

**Comment by flamber** [comment]
Hi @HugoManoMano 
Please use the support mail, when using the Enterprise Edition.
And can you try 1.35.4.1, since the entire connection handling was changed in 1.35, which probably changes this behavior too?

**Comment by HugoManoMano** [comment]
Hi @flamber thanks for the quick answer.
We used a trial version of Enterprise Edition which expired, so in fact, we do use a Community Edition now I guess, but sorry if I'm not using the proper way of submitting this case.
We'll upgrade the version by the end of today, see if it solves something, and I'll update the issue.

**Comment by flamber** [comment]
@HugoManoMano If your trial has expired and you're not using the EE functionality, then I would suggest using CE.

**Comment by HugoManoMano** [comment]
Hi @flamber we just upgraded to v0.35.4 and we still see all these kind of queries running. Can you advice ?

**Comment by xiekevin** [comment]
Was this ever resolved? I'm seeing a similar issue occurring on metabase 0.45.1

**Comment by paoliniluis** [comment]
This is something that the snowflake driver does by design
