### ISSUE TITLE
Open Source Variant of Auditing in Logs

### ISSUE THREAD

**Issue by peter-mueller** [metabase/metabase#12865]
**Is your feature request related to a problem? Please describe.**
Whenever ciritical data is analysed in metabase, there needs to be known what data was accessed and when. 

**Describe the solution you'd like**
A Log for every SQL command coupled with the username that caused it with the time. 

*Example*:
```log
08-07-2020-12:55:30 AUDIT-LOG User `peter-mueller` caused the following query: SELECT * FORM ORDERS LIMIT 10
```

**Describe alternatives you've considered**
- Forking metabase with a minimal patch for logs 

**How important is this feature to you?**
The Open Source Variant is not usable in production without the minimal auditing. I know the Auditing exists in the Enterprise Version and would cut you off potential paying users. 

>  You'll get total insight into how your organization is using Metabase, and the ability to dig in and investigate exactly who accessed what data when. https://www.metabase.com/enterprise/

The logging variant could be a compromise to enable Open Source Users to track down criminal users in case of an emergency. Enterprise would still be valuable, because it's more usable and can be used on a daily basis by non-programmers.

**Comment by flamber** [comment]
Hi @peter-mueller 
Going to close this, since the Enterprise Edition has this functionality.
Check out https://discourse.metabase.com/t/metabase-metadata-sql/3688 for various ways to get that information from the metadata.

**Comment by peter-mueller** [comment]
Update for Issue-Readers: I've been only able to read explicitly saved queries from the database. No history of all queries (including unsaved ones).

So if the Auditing is a must feature you need to opt into Enterprise.
