### ISSUE TITLE
When env var `MB_SETUP_TOKEN` is set, then interface is always redirected to `/setup`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12874]
**Describe the bug**
When trying to automate setup with a predefined `MB_SETUP_TOKEN`, then after a successful POST to `/api/setup`, it's not possible to login, since the frontend thinks it's still in setup-mode forever until starting the instance without the variable.

**To Reproduce**
1. Start a new instance:
```
java -DMB_SETUP_TOKEN=ad0fb086-351b-4fa5-a17e-76282d2c9753 -jar metabase.jar
```
The following is shown in the log during the initial startup
```
...
07-08 23:34:17 INFO metabase.core :: Looks like this is a new installation ... preparing setup wizard
07-08 23:34:17 INFO metabase.core :: Please use the following URL to setup your Metabase installation:
http://localhost:3000/setup/
...
```
2. Run the setup automated:
```
curl 'http://localhost:3000/api/setup' --compressed -H 'Content-Type: application/json' --data-raw '{"token":"ad0fb086-351b-4fa5-a17e-76282d2c9753","prefs":{"site_name":"Test","allow_tracking":"true"},"database":null,"user":{"first_name":"Meta","last_name":"Base","email":"test@test.test","password":"Testtest1","site_name":"Test"}}'
```
3. Try to login via the browser - it will redirect to `/setup` and `/api/session/properties` will have `setup-token` defined.
4. Restarting the instance with `MB_SETUP_TOKEN` still set, will not have the log lines `Looks like this is a new installation ... preparing setup wizard`, but will still redirect to `/setup` like in step 3.
5. Restarting the instance without `MB_SETUP_TOKEN` will show the login, and allow normal use.

**Expected behavior**
After the setup is completed, then the environment variable should be ignored - without the need to restart the instance without the variable defined.

**Information about your Metabase Installation:**
Metabase 1.35.4.1

**Additional context**
Originally from #12869

**Comment by camsaul** [comment]
Normally after setup we clear out the value, but if the `setup-token` Setting is set via env var we can't clear it out.

Maybe it makes sense to use add an internal `setup-finished` Setting so we can track whether setup is done regardless of whether `setup-token` is set (and you'd be able to force skip Setup by setting the env var `MB_SETUP_FINISHED`

**Comment by stephane-klein** [comment]
Same error shown [here](https://discourse.metabase.com/t/cant-access-to-login-page-after-api-setup-api-call/14505)

**Comment by camsaul** [comment]
This idea came up on Slack: it's probably better to just check whether the instance has a `User` and use that to determine whether we need to run setup. If we have a User, disable the Setup API endpoints and disable the redirect, regardless of whether a setup token setting is set. Then we don't need to worry about clearing the token either.
