### ISSUE TITLE
Crash on startup (0.36.0-rc2)

### ISSUE THREAD

**Issue by alpertungir** [metabase/metabase#12871]
I've been waiting for a long time to start metabase. can't pass the splash screen

**Comment by robdaemon** [comment]
Can you provide the console output and logs from starting the Metabase server startup?

**Comment by alpertungir** [comment]
just APİ connection errors..

"Failed to load resource: the server responded with a status of 503 (Service Unavailable) (api/health:1)"
"Failed to load resource: net::ERR_CONNECTION_REFUSED"
....

**Comment by flamber** [comment]
@alpertungir It would be very helpful if you provided much more information, like where you're hosting and the logs.

**Comment by alpertungir** [comment]
We've been hosting on our company server. Previous versions were working correctly. i am new on this and i dont know how can i see the logs which you want. if you help me, i can send it to you.

**Comment by flamber** [comment]
@alpertungir We don't know how you're running Metabase, so we cannot help you. I would recommend that you revert to your backup.
Going to close this issue, since we cannot do anything without logs.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by alpertungir** [comment]
I solved it by changing java language to en.
Start Metabase java -Duser.language=en -jar metabase.jar

https://github.com/metabase/metabase/issues/12623

**Comment by flamber** [comment]
@alpertungir Then you shouldn't have any problems with the final release of 0.36.0, since it was fixed a few days ago.

**Comment by alpertungir** [comment]
Yes, thank you.

it's ok now but i can't restart the metabase service. If i stop and start service again, it's not initializing second time. i can only start it by using this
 (Start Metabase java -Duser.language=en -jar metabase.jar)

**Comment by flamber** [comment]
@alpertungir Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
