### ISSUE TITLE
Text highlighting on Safari when reordering columns in Data Model tab

### ISSUE THREAD

**Issue by jeff-bruemmer** [metabase/metabase#12870]
**Describe the bug**
When reordering columns on the Admin -> Data Model page, dragging columns inadvertently highlights text in other columns.

![highlighted-text-on-column-reorder](https://user-images.githubusercontent.com/17343328/86959339-800b0780-c112-11ea-8fc4-12be1e9d6bca.gif)

Column reordering works as expected on Chrome, but this text highlighting issue occurs in Safari (and to some extent on Firefox).

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
See gif above. Must be in Safari. Firefox also has some highlighting issues.

**Expected behavior**
As on Chrome, dragging columns does not highlight text on the page.

**Severity**
P3 at most. Just an awkward, unexpected experience.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Mac OS X",
    "os.version": "10.15.5",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "tag": "v0.36.0-snapshot",
      "hash": "8d3500b",
      "branch": "docs-data-model-and-localization",
      "date": "2020-06-23"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
This is the same behavior, when trying to rearrange columns in QB visualization Settings sidebar, or dashboard filters. Haven't checked, but perhaps it's a component that can be fixed globally.
