### ISSUE TITLE
Scatter chart y-axis percent format renders zero

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#12892]
**Describe the bug**
Scatter (bubble) chart y-axis percent format renders zero.

**Logs**
Not applicable

**To Reproduce**
1. SQL native query
2. Y-axis data such as 0.1, 0.2, 0.5... Any data for X-axis, Breakout, Bubble size
3. Scatter options>Y-axis field gear icon>Style=percent (Y-axis renders 0 at this point, increasing Minimum number of decimal place box renders 0.0000... too)
4. Multiply by a number box set to 100 doesn't do anything to fix either
5. Compensate directly in the SQL Y-axis field *100 entering % in Scatter options>Y-axis field gear icon>Add a suffix box 

**Expected behavior**
Y-axis data such as 0.1, 0.2, 0.5 should render 10%, 20%, 50% etc. without having to compensate as above

**Screenshots**
NA

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}

**Severity**
Annoying, can get around it with a bit of poking around.

**Additional context**
Only viz where this % formatting behaviour seen so far, bar, line, etc. seem to work fine.

**Comment by flamber** [comment]
Almost the same as this for row charts #12185

**Comment by flamber** [comment]
I cannot reproduce on 0.41.2
