### ISSUE TITLE
`master` Custom Expression in Summarize-section not available

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12899]
**Describe the bug**
Seems like #12859 somehow removed Custom Expression from Summarize section.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Click "Pick the metric you want to see" of Summarize-section - normally has Custom Expression as bottom option
![image](https://user-images.githubusercontent.com/1447303/87246619-d481f000-c44e-11ea-899e-0e43a348b472.png)

**Information about your Metabase Installation:**
`master` commit `1a9b648` - going back to previous commit `5753ee1`, then it shows up again.

**Comment by nemanjaglumac** [comment]
@flamber - I wrote a cy test for this and I'll probably cover #12651 as well. So, what would be the prefered way to contribute with tests, if I'm not the one who is going to also solve the issue?

- should I simply paste the code snippet with that test in the comment of an issue, or
- should I open PR and mark it as [WIP]? (then the person who **is** going to solve it can either contribute to that same PR, or cherry pick it, or... fill in the blank :))

**Comment by nemanjaglumac** [comment]
Also, I noticed that in my local dev version (up to date with Metabase) "Basic Metrics" title disappears (as well as the "accordion" type of list presentation). It seems that if is it the only collection available (in my case it is), it directly displays its children (`.List-item-title`). Here's what I mean:
![image](https://user-images.githubusercontent.com/31325167/87257704-70d2e380-c49d-11ea-866a-2fbf271e2fff.png)

And here's the (gif) screenshot from the latest Mac OS App:
https://share.getcloudapp.com/X6uojZm0

**Comment by flamber** [comment]
@nemanjaglumac You open a PR. Have a look at what Damon usually does: https://github.com/metabase/metabase/pulls/dacort 
As for the "Basic Metrics" missing the header, pretty sure that's the default behavior, when there's only one accordion.

**Comment by nemanjaglumac** [comment]
@flamber thanks for pointing me to @dacort . It helps on many levels.

Yup, my guess was that it was the default behaviour, as well. I needed to check because it can affect the way tests are composed.
