### ISSUE TITLE
Deprecated viewport meta tag `minimal-ui`

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#12896]
**Describe the bug**
Viewport meta tag `minimal-ui` was deprecated when Apple introduced iOS 8 ([source](https://developer.apple.com/library/archive/releasenotes/General/RN-iOSSDK-8.0/)). Major browsers ignore it, but for some reason console in Metabase OSX App is complaining about it.

**Logs**
See: "Screenshots"

**To Reproduce**
1. Download and install [Metabase for Mac](https://downloads.metabase.com/v0.35.4/Metabase.dmg)
1a. (mine was installed via Homebrew `brew cask install metabase`)
2. Open Metabase application
3. Right click anywhere on the screen and "Inspect element"
4. Check the `console` tab

**Expected behavior**
Console shouldn't complain about this deprecated tag.

**Screenshots**
<img width="1000" alt="minimal-ui-console-log" src="https://user-images.githubusercontent.com/31325167/87201506-0126f200-c2ff-11ea-88f4-89a4bd22fe39.png">

**Information about your Metabase Installation:**

- Your browser and the version: N/A
- Your operating system: OS X 10.15.5
- Your databases: N/A
- Metabase version: v0.35.4
- Metabase hosting environment: Mac app
- Metabase internal database: H2 (default)

**Severity**
P3 at the very best. This will probably go unnoticed and will not affect anyone, but it is still a technical debt that can be easily removed.

**Additional context**
- I couldn't replicate this bug in **any** of the browsers (even Safari) since they just ignore it. It is only visible in Metabase OS X app.
- if you're ok with it, I can easily remove it from `resources/frontend_client/index_template.html` and open quick PR

**Some additional reading material, in case anyone is interested:**
- https://visuellegedanken.de/2014-03-18/a-follow-up-on-the-minimal-ui-viewport-meta-tag/
- https://stackoverflow.com/questions/24889100/ios-8-removed-minimal-ui-viewport-property-are-there-other-soft-fullscreen

**Comment by nemanjaglumac** [comment]
@flamber - is it ok if I open PR and remove this tag?

**Comment by flamber** [comment]
@nemanjaglumac I don't have Mac, but go ahead and open a PR :+1:
