### ISSUE TITLE
Unable to Connect Atlas Data Lake with Metabase

### ISSUE THREAD

**Issue by ankit939** [metabase/metabase#12902]
**Describe the bug**
For development of Data Warehouse System I have created a data lake instance on atlas which I am trying to connect with metabase using MongoDB connect type but getting following error - 

**Logs**
Timed out after 3000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=ak-datalake-dmvlp.a.query.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]

**To Reproduce**
1. Create Data Lake instance on https://cloud.mongodb.com/
2. Try to connect the data lake with metabase using mongodb connect type
3. The above error is given then, tried Option - "Use DNS SRV when connecting" but no help.

**Expected behavior**
The Data Lake instance should be supported to connect with metabase.

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Development progress is struck due to this bug. Please help me out!

**Comment by flamber** [comment]
Hi @ankit939 
Please post "Diagnostic Info" from Admin > Troubleshooting.
Have a look at #9867 and #6678, where people have various workarounds for problems they've had.
If you're using a custom certificate, then that will be possible to use in 0.36.0 - #3877
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by ankit939** [comment]
@flamber I had already visited  #9867 & #6678 threads, I have confirmed srv records are not supported for atlas data lake, so already tried "Use DNS SRV when connecting" option but no help and custom certificate is not configured for the data lake since, I have confirmed the Mongo URI is enough to connect to the data lake in other softwares like - NoSQL Booster & MongoDB Compass.

**Comment by flamber** [comment]
@ankit939 Please post "Diagnostic Info" from Admin > Troubleshooting.

**Comment by flamber** [comment]
Continue debug on forum: https://discourse.metabase.com/t/unable-to-connect-atlas-data-lake-with-metabase/10859
