### ISSUE TITLE
Field filter dosent loads data from column it is mapped to

### ISSUE THREAD

**Issue by bezzil85** [metabase/metabase#12904]
**Describe the bug**
Field filter when field is set up to use keys from other column, while using it used to give advice and select by keys in other field, stopped working like that after last updates. Sometimes they start work as expected, but after refresh, there is again only option to entering ids not names from other column

**Expected behavior**
Expectation
![image](https://user-images.githubusercontent.com/37928405/87298382-c7c6d000-c512-11ea-8831-a4f0f5f63c30.png)
(enter username or ID)
What we get
![image](https://user-images.githubusercontent.com/37928405/87298601-1ffdd200-c513-11ea-951f-d806b29750bc.png)
(enter ID)

{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/83.0.4103.61 Chrome/83.0.4103.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.9.0-6-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Moscow"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Europe/Moscow"
    }
  }
}

- Comium 83.0.4103.61 (noticed on any browser)
- Ubuntu 18 (Noticed on IOS, Windows)
- MySQL
-  0.35.4
- Postgres

**Severity**
Users cant work, they dont keep in ming ID`s, but they remember names that they are searching for

**Comment by flamber** [comment]
Hi @bezzil85 
Which version did it work correctly in?
Can you provide steps-to-reproduce?

**Comment by bezzil85** [comment]
**steps to reproduce**
```
CREATE TABLE `tableA` (
  `a_id` int(11) NOT NULL AUTO_INCREMENT,
  `text` varchar(100) DEFAULT NULL,
  `b_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`a_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tableB` (
  `b_id` int(11) NOT NULL AUTO_INCREMENT,
  `text` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`b_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;


INSERT INTO tableA (`text`,b_id) VALUES 
('a',3)
,('b',3)
,('c',4)
,('d',4)
,('e',5)
,('f',1)
,('g',1)
;

INSERT INTO yourdatabasename.tableB (`text`) VALUES 
('ann')
,('michael')
,('kevin')
,('justin')
,('ken')
,('mark')
,('sven')
;

```

then create set up in adminstration for tableA, 
Field type: Outer key = TableB -> b_id
Field filtration: Search field
Show value: Use outer key -> Text

![image](https://user-images.githubusercontent.com/37928405/87303602-1f1d6e00-c51c-11ea-9d95-9a06f4714ad6.png)


Then create question "test"

```
select * 
from tableA
where 1=1 [[ AND {{name}} ]] 
```

set up filter name as 
Variable type: Field filter
Connected key: TableA->b_id
Widget filter type: ID

![image](https://user-images.githubusercontent.com/37928405/87303889-8fc48a80-c51c-11ea-8b29-38fa1eb8f580.png)


Right after creation filter works as expected

![image](https://user-images.githubusercontent.com/37928405/87304037-d5815300-c51c-11ea-82ec-9802e4e44186.png)

how to brake it , open chrome inspectations tools ( ctrl + shift + i ), then refresh page, 

![image](https://user-images.githubusercontent.com/37928405/87304163-111c1d00-c51d-11ea-870e-6c1b1dfd6590.png)

and possibility to search by name disapears.
On production base on some questions it never returns back.


First time that bug was noticed half year ago, it was not so brutal, cos opening editor and pressing on X button, where filter fileds are setted up, was fixing this, in last version it dosent help any more.

**Comment by flamber** [comment]
This is a frontend state issue - see step 6.

Reproduce:
1. Admin > Data Model > Sample Dataset > Orders > Product ID > "Filtering on this field"=`Search box` and "Display values"=`Use foreign key > Title`
2. Native question > Sample Dataset > `SELECT COUNT(*) FROM ORDERS WHERE {{pid}}` and set "pid" to Field Filter > Orders > Product ID.
3. Click filter widget, it says `Search by Title or enter an ID` and it's possible to search by name:
![image](https://user-images.githubusercontent.com/1447303/87348367-e483f780-c554-11ea-91b0-1739d2750d46.png)
4. Save question as "Test 12904" and refresh browser
5. Click filter widget, now it only says `Enter an ID` and it's not possible to search by name:
![image](https://user-images.githubusercontent.com/1447303/87348607-52302380-c555-11ea-86e9-89cccead9ff5.png)
6. Now go to Admin > Data Model > Sample Dataset - nothing else (this loads `/api/database/:id/metadata?includeHidden=true`) - now go to the saved question via Exit Admin > Search "12904", it now works again, just like in step 3:
![image](https://user-images.githubusercontent.com/1447303/87349461-9ec82e80-c556-11ea-9ca5-98ebed71b762.png)

Related to #7603 #8599 #9490

**Comment by bezzil85** [comment]
Good day, @flamber, is it possible that fix for this issue will be in near future ?

**Comment by flamber** [comment]
@bezzil85 There's 1700+ other issues.

**Comment by bezzil85** [comment]
> @bezzil85 There's 1700+ other issues.

yeap i saw it, just wondering, that thing is essntial for work in our company, no offence =)
