### ISSUE TITLE
Outlook pulse/alert doesn't allow clicking question title to visit link

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12901]
**Describe the bug**
Seems like (newer versions of?) Outlook doesn't support `<a>` around a `<table>`, which means that it's not possible to click the question title in a pulse/alert email to visit the question.

**Expected behavior**
Ability to click question title to visit question.

**Information about your Metabase Installation:**
Metabase 1.34.3 and 0.35.4

**Comment by qnkhuat** [comment]
Tested with outlook 16.79 on mac and it works fine

**Comment by qnkhuat** [comment]
Ok I finally got a Windows device to test on.

So it works on the new outlook app ([link](https://support.microsoft.com/en-us/office/getting-started-with-the-new-outlook-for-windows-656bb8d9-5a60-49b2-a98b-ba7822bc7627))
but not on the old Outlook app.

On the other hand, outlook web client does work.

**Comment by qnkhuat** [comment]
@paoliniluis can we close the issue? or making it work on old Outlook clients is critical?

the fixes might require us to remove the outer <a> tag of the table, instead, we inject a <a> tag in every single <th>  of the table.
