### ISSUE TITLE
can't use SQL queries on MySQL driver with timezone set

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1291]
You just end up seeing this error about read-only connection:

<img width="686" alt="screen shot 2015-10-20 at 6 08 08 pm" src="https://cloud.githubusercontent.com/assets/1987787/10625208/96cf3024-7755-11e5-846d-d0ee3d9cd24e.png">

After a little digging the issue appears to be in the code where we trigger the setting of the connection timezone (`(jdbc/db-do-prepared conn (i/timezone->set-timezone-sql driver timezone))`).  Based on the jdbc docs it sounds like a call to `executeUpdate` is used under the hood which is what is likely triggering the mysql jdbc driver to respond with an error.  other jdbc drivers seem to be fine with this approach though.

in any case, the workaround right now is to leave the report timezone unset and then there is no issue.

**Comment by nattaylor** [comment]
Once it's set, is there a way to unset it?

**Comment by agilliland** [comment]
So this is a confirmed issue with the way MySQL interprets our call to set the connection timezone.  The work around it to simply unset the reporting timezone in the admin settings which is now possible after this fix #1301

**Comment by camsaul** [comment]
Did you guys set up your MySQL DBs properly? You need to run `mysql_tzinfo_to_sql` on your system

![screen shot 2015-10-21 at 3 27 29 pm](https://cloud.githubusercontent.com/assets/1455846/10652073/490a18d2-7808-11e5-9004-bfb1fb406649.png)

**Comment by agilliland** [comment]
yes, I did that but it doesn't resolve this particular problem.

**Comment by tegansnyder** [comment]
Thanks for sharing this. I too ran into the issue. Unsetting the timezone solved it for me.

**Comment by camsaul** [comment]
Fixed by #1426
