### ISSUE TITLE
Can metabase support mysql cluster datasource?

### ISSUE THREAD

**Issue by kurtiswen** [metabase/metabase#12912]
hi everyone, I’m having problem when trying to add a mysql server as new database. the target mysql server is a cluster, and I’m getting error message like: Count not connect to address(host=xxx.64.xxx.41)(port=xxxx)(type=master): UDAL - You have an error in your SQL syntax; check the manual for the right syntax to use set autocommit=1, sql_mode = concat(@@sql_mode,’,STRICT_TRANS_TABLES’) near ‘1’ at line ‘{2}’
anyone know about this, please help, thanks a lot.

**Comment by flamber** [comment]
Hi @kurtiswen 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Check the log in Metabase or MySQL for more details about the error.

**Comment by kurtiswen** [comment]
@flamber thanks for the reply，after further attempt，the problem is like this: 1. using a new deployment of metabase，we succeeded add the mysql database. then our tester deleted the mysql database and tried to add it again, and then this error happened and failed to add the database again. the error message is same as previous: Count not connect to address(host=xxx.64.xxx.41)(port=xxxx)(type=master): UDAL - You have an error in your SQL syntax; check the manual for the right syntax to use set autocommit=1, sql_mode = concat(@@sql_mode,’,STRICT_TRANS_TABLES’) near ‘1’ at line ‘{2}’.

**Comment by kurtiswen** [comment]
@flamber do you have any clue on this, or can anyone help, thanks.

**Comment by flamber** [comment]
@kurtiswen Please use the forum for questions and troubleshooting: https://discourse.metabase.com/t/can-metabase-support-mysql-cluster-datasource/10873
