### ISSUE TITLE
Setting column in one table equal to value in anothe table does not work in MySQL

### ISSUE THREAD

**Issue by mjw00ds** [metabase/metabase#12913]
At the end of each day i want to set yesterdays value = todays closing value so that tomorrow i can calculate the change. In SQL server you can do this...

**update i
set yesterday_theo = t.price
from instruments i inner join
	theoreticals t on i.instrument_id = t.instrument_id
where i.instrument_id = 1;**

but in MySQL i get this error

Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from instruments i inner join  theoreticals t on i.instrument_id = t.instrument_' at line 3	0.000 sec

Is there a better way to do this that works in MySQL?

**Comment by flamber** [comment]
Hi @mjw00ds 
Metabase does not support `UPDATE`/`INSERT`/`DELETE`.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
