### ISSUE TITLE
Maximum number of connections to Metabase reporting databases increase

### ISSUE THREAD

**Issue by ChristineChetty** [metabase/metabase#12924]
We are using our Metabase instance to generate reports for our other web applications and related databases. We are concerned that the maximum number of connections to database being 15 will not be enough to faciliate all our customers making use of tour applications and accessing reports, does Metabase open a single connection to the database for each dashboard or each question on the dashboard? 

Also how would we go about increasing this number significantly as more users connect to our web applications which are embedding metabase dashboards?

I have seen issue response https://github.com/metabase/metabase/issues/2172#issuecomment-559638836 
I want to know if this will solve our problem as I am reluctant to make changes as stated here

**Comment by flamber** [comment]
Hi @ChristineChetty 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://github.com/metabase/metabase/blob/master/docs/operations-guide/environment-variables.md#mb_application_db_max_connection_pool_size
