### ISSUE TITLE
Editing dashboard doesn't cancel running query on cards correctly, when changed or removed

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12926]
**Describe the bug**
When editing dashboards and adding/removing cards, it doesn't cancel the query, which can lead to long-running-queries congestion on the database.

**To Reproduce**
1. Create Native question (this query is Postgres specific and sleeps for 10 minutes), and save question.
`SELECT 1, pg_sleep(600) [[WHERE {{f}}=1]]` - set the filter type to Number.
2. Create dashboard and go into Edit-mode.
3. Add the question from step 1 to the dashboard - this kicks off a query without any filters.
4. Add the question again, as a second card, and then remove it again.
5. Now add a filter (Other categories) and connect it to the new card, and set a default value of the filter to 1.
6. Save dashboard - this kicks off another query with the filter as defined in step 5, but it doesn't cancel the query from step 3+4.

**Information about your Metabase Installation:**
Metabase 1.35.4.1 and `master`.

**Additional context**
Related to #12578 and #11727

**Comment by nemanjaglumac** [comment]
@npretto #32842 says that it's fixing "part" of this issue.
Is the follow-up work known and scheduled already?

Just checking can we close this issue or we still need to work on it?

**Comment by npretto** [comment]
@nemanjaglumac yes work for the other part is ongoing: https://github.com/metabase/metabase/pull/33128
