### ISSUE TITLE
Y-axis is sometimes automatically split when it's not needed

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12939]
**Describe the bug**
When result values are almost the same, then it can cause the Y-axis to automatically split the axis.

Also see https://github.com/metabase/metabase/issues/12939#issuecomment-1047207005 for other examples and notes

**To Reproduce**
1. Native question > Sample Dataset
```SQL
SELECT 1075 AS "media_create_count", 1075 AS "media_create_success_count", 1072 AS "media_process_success_count", '2020-07-02' AS "date" UNION ALL
SELECT 614 AS "media_create_count", 611 AS "media_create_success_count", 608 AS "media_process_success_count", '2020-07-03' AS "date" UNION ALL
SELECT 327 AS "media_create_count", 327 AS "media_create_success_count", 327 AS "media_process_success_count", '2020-07-04' AS "date" UNION ALL
SELECT 421 AS "media_create_count", 421 AS "media_create_success_count", 420 AS "media_process_success_count", '2020-07-05' AS "date" UNION ALL
SELECT 995 AS "media_create_count", 993 AS "media_create_success_count", 981 AS "media_process_success_count", '2020-07-06' AS "date" UNION ALL
SELECT 913 AS "media_create_count", 913 AS "media_create_success_count", 911 AS "media_process_success_count", '2020-07-07' AS "date" UNION ALL
SELECT 1089 AS "media_create_count", 1086 AS "media_create_success_count", 1050 AS "media_process_success_count", '2020-07-08' AS "date" UNION ALL
SELECT 1132 AS "media_create_count", 1131 AS "media_create_success_count", 1065 AS "media_process_success_count", '2020-07-09' AS "date" UNION ALL
SELECT 1432 AS "media_create_count", 1413 AS "media_create_success_count", 1396 AS "media_process_success_count", '2020-07-10' AS "date" UNION ALL
SELECT 433 AS "media_create_count", 433 AS "media_create_success_count", 420 AS "media_process_success_count", '2020-07-11' AS "date" UNION ALL
SELECT 628 AS "media_create_count", 626 AS "media_create_success_count", 624 AS "media_process_success_count", '2020-07-12' AS "date" UNION ALL
SELECT 1020 AS "media_create_count", 1019 AS "media_create_success_count", 1017 AS "media_process_success_count", '2020-07-13' AS "date" UNION ALL
SELECT 1072 AS "media_create_count", 1062 AS "media_create_success_count", 1059 AS "media_process_success_count", '2020-07-14' AS "date" UNION ALL
SELECT 1283 AS "media_create_count", 1283 AS "media_create_success_count", 1278 AS "media_process_success_count", '2020-07-15' AS "date" UNION ALL
SELECT 683 AS "media_create_count", 683 AS "media_create_success_count", 681 AS "media_process_success_count", '2020-07-16' AS "date"
```
2. Visualize as Bar chart - notice it's splitting the Y-axis even when all values are very close to each other and probably doesn't need the split.
![image](https://user-images.githubusercontent.com/1447303/87807411-7db65500-c858-11ea-94f2-1aaf33fb6c48.png)

**Workaround:** Disable split in visualization Settings > Axes > "Use a split y-axis when necessary"

**Information about your Metabase Installation:**
Metabase 0.35.4 thru 0.42.1

**Additional context**
https://discourse.metabase.com/t/graph-plot-inconsistency/10893

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
_This comment has 3 notes_

From @mazameli in #20639:
Question > Sample > Orders - summarize Minimum of Quantity and Average of Quantity, grouped by CreatedAt:Month
![image](https://user-images.githubusercontent.com/1447303/155021869-5f900ed5-31f7-4e57-b55e-48023a827aa6.png)

----

**Important**
The fix for this should continue to split different types/currencies, example:
![image](https://user-images.githubusercontent.com/1447303/155021980-3d4d3052-4f54-47a2-ad72-6115b57925a2.png)

----

Side-note, it seems like it's not really working at all, when combining cards on the dashboard. I have to manually set the added card (Products) from Auto to Right, when going into the dashboard card's visualization settings "Which axis?"
![image](https://user-images.githubusercontent.com/1447303/155022034-ffdc57f1-ce40-4947-b22e-591b785430bd.png)

**Comment by edds** [comment]
Not sure if this is the right place to report this, but the workaround here doesn't work for the slack notification version of graphs. Given those graphs are also reduced size, it makes it even more likely that you'll miss that the axis are different.
