### ISSUE TITLE
Google Bigquery Driver

### ISSUE THREAD

**Issue by thekantian** [metabase/metabase#1294]
Would google's hosted data warehouse called bigquery be a good fit for metabase? The one thing it seems to be missing that might affect things would be foreign keys. That said, there isn't a great frontend for BigQuery yet in the open source world - maybe this is it!

What would the connection manager have to look like - is there any documentation on writing new drivers for DBs for metabase? This is something that we would take a look at implementing to contribute to the community if it made sense...

Thanks!

**Comment by fhoffa** [comment]
See how re:dash implemented BigQuery support: https://github.com/EverythingMe/redash/blob/master/redash/query_runner/big_query.py

**Comment by johnkabler** [comment]
See this article on why BigQuery is probably a very good fit for Metabase's customers as they begin to grow.  

http://www.christoolivier.com/use-google-cloud-platform-and-bigquery-to-deliver-bi-projects-faster-for-a-fraction-of-the-price/

The pricing of BQ, as well as the speed with which it operates, allows for OLAP type performance without dealing with the overhead of designing and maintaining a star schema.

**Comment by spectr** [comment]
Looking forward to BigQuery support.

**Comment by araddon** [comment]
:+1:

**Comment by avnersorek** [comment]
+1

**Comment by avnercompit** [comment]
:+1:

**Comment by compit-ltd** [comment]
+1

**Comment by aitamar** [comment]
+1

**Comment by compit-ltd** [comment]
+1

**Comment by texib** [comment]
+`

**Comment by camsaul** [comment]
:+1:

**Comment by abronte** [comment]
+1
