### ISSUE TITLE
Google oath, named my application "Metabase" but the auth code link told me that "Jarvis would like to access" etc

### ISSUE THREAD

**Issue by smfritzii** [metabase/metabase#12952]
I am trying to set up Metabase with BigQuery. I followed the prompts to create a "Desktop App" & named it Metabase; and got a client ID and client secret which I copied & pasted into the respective boxes. 

Upon clicking the next link to get an auth code, a pop-up from google tells me that "Jarvis" would like to access my BQ data, instead of "Metabase". I don't know where Jarvis would have come from, and I double-checked the client ID.

Is this expected, or is there something wonky? Thanks!

**Comment by flamber** [comment]
Hi @smfritzii 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Click the information box on Google to see what "Jarvis" is - it doesn't come from Metabase.
