### ISSUE TITLE
Maps (data encode is UTF-8) is displayed incorrectly, when Metabase is not using file.encoding=UTF-8

### ISSUE THREAD

**Issue by bestpika** [metabase/metabase#12962]
**Describe the bug**

When I load a geojson encoded with UTF-8 in `admin/settings/maps`, the Chinese data displayed is garbled.

**Logs**

**To Reproduce**

1. Go to 'admin/settings/maps'
1. Click on 'add a map'
1. Fill URL and click on 'load'
1. I see some garbled.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5698157/88019332-25cf6500-cb5c-11ea-9959-5e7c75c805c6.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome/84.0.4147.89
- Your operating system: Windows 10 x64
- Metabase version: 0.35.4
- Metabase hosting environment: .jar (jvm: 1.8.0_261-b12)
- Metabase internal database: H2

**Severity**

This prevents me from displaying the map data in geojson in Chinese, which makes it impossible to continue with future operations.

**Additional context**

The geojson file: [le3.zip](https://github.com/metabase/metabase/files/4951662/le3.zip)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-TW",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "MS950",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_261-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_261",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.261-b12",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "zh",
    "user.timezone": "Asia/Taipei"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.4",
      "date": "2020-05-28",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Asia/Taipei"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @bestpika 
Start Metabase with `java -Dfile.encoding=UTF-8 -jar metabase.jar`.
And migrate away from H2, when using Metabase in production:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

Leaving this open, since I have seen this a few times now and think we might want to revisit if we should be defaulting to `UTF-8`, unless `file.encoding` is defined (if that's even possible). Or perhaps always forcing `UTF-8` and ignoring parameter.

**Comment by 8debug** [comment]
> Hi @bestpika
> 
> Start Metabase with UTF-8 encoding (example) `java -Dfile.encoding=UTF-8 -jar metabase.jar`
> 
> And migrate away from H2, when using Metabase in production:
> https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
> 
> Leaving this open, since I have seen this a few times now and think we might want to revisit if we should be defaulting to `UTF-8`, unless `file.encoding` is defined (if that's even possible). Or perhaps always forcing `UTF-8` and ignoring parameter.

it is still garbled. 
![image](https://user-images.githubusercontent.com/3394927/114800067-92198500-9dcb-11eb-8b17-c7241cae0295.png)

**Comment by noahmoss** [comment]
@flamber Do you know if this is still an issue? I'm not able to repro, even if I manually change the file encoding to `MS950`.

**Comment by flamber** [comment]
@noahmoss Unless you have that encoding on your system, I would guess that Java fall-back to something different, which is likely more Latin-based on your system.
When I try with GBK, then even the log emojis are just showing as a question mark `?`.

I tried starting with `-Dfile.encoding=GBK` on some commit from earlier today (notice the "Sample values" in region name):
![image](https://user-images.githubusercontent.com/1447303/122790031-33cfbd80-d2b8-11eb-8b8a-aa642e11c641.png)
For comparison with UTF-8 on 0.39.4:
![image](https://user-images.githubusercontent.com/1447303/122790368-8b6e2900-d2b8-11eb-8cbb-502667776173.png)

**Comment by noahmoss** [comment]
@flamber Interesting, that makes sense. I still can't repro on my (macOS) computer with GBK, so I'll leave this be for now.

**Comment by paoliniluis** [comment]
Fixed
