### ISSUE TITLE
Metabase Questions are taking longer compared to SQL Client

### ISSUE THREAD

**Issue by CedricLeong** [metabase/metabase#12975]
The card API is taking longer than running the queries on a SQL client. These are native questions running on a PostgreSQL DB.
In the example example below from the logs Metabase had an execution time of 57.3 seconds while running the exact same question with the same filters results in 22 seconds.

This was ran in the middle of the night when there was no users or queries except for this one and all scheduling for all databases were turned off.

**Things I tried to resolve this on my own:**
I've increased the web server instance already to have more resources.
From what I've seen neither the database or the web server is running out of resources such that it's bottlenecking Metabase.
Scheduling and most features on Metabase were turned off in case this is some kind of load issue on Metabase.

**Observations: **
First thing I see is that there are consistently over 100 active threads in the middle of the night when no questions have been ran on Metabase for hours and no Scheduling for Databases are running.
Scheduled Jobs in Metabase says they are all BLOCKED but theres no description to know what this means.

**Logs**
[f1dd5669-1c91-4fd4-99d4-22e02a1f5418] 2020-07-21T22:58:41-04:00 DEBUG metabase.middleware.log POST /api/card/559/query 202 [ASYNC: completed] 57.3 s (17 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (3 idle, 0 queued) (109 total active threads) Queries in flight: 0 (0 queued)

**Metabase:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-8u252-b09-1~18.04-b09",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "5.3.0-1030-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.22-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.4",
      "date": "2020-05-28",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```
**RDS:**
```
Engine version
5.7.22

Instance class
db.t3.micro
vCPU
2
RAM
1 GB
General Purpose (SSD)

Storage
20 GiB
```

**EC2:**
```
Instance type
t3.xlarge


EBS-optimized

Number of vCPUs
4
```

**Comment by flamber** [comment]
Hi @CedricLeong 
Have you looked into enabling debug logging on the Postgres database, so you can see how it's handling the queries.
I'm not sure what you mean about "...running the exact same question with the same filters...". Are you comparing the query from Metabase to exactly the same on Postgres, or are you using variable filters and manually converting between them?
You should test with the same static query.

**Comment by CedricLeong** [comment]
@flamber 
It was just a date filter on Metabase so I put in the equivalent where statement.
I'm not sure how to turn on debugging logs on Postgresql Aurora.

So testing it with the same static query on both metabase and the sql client. I noticed that the one of Metabase takes over 1 minute to return while the one from the SQL client takes 20 seconds. Any idea what would cause this?

**Comment by sbelak** [comment]
Convert the question into SQL and check the generated SQL. It might be that we do something silly when compiling to SQL.

**Comment by flamber** [comment]
Closing in favor of #11837, since I guess that's the problem, but otherwise please post the exact query used both places.
