### ISSUE TITLE
Data Labels / Values needed on Pie charts and Row charts

### ISSUE THREAD

**Issue by exabrial** [metabase/metabase#12977]
**Is your feature request related to a problem? Please describe.**
Pie charts are useless for our users with disabilities and for use on wall-mounted dashboards because there's no way for them to tell what the underlying value is without a mouse-over event.

**Describe the solution you'd like**
Simply being able to display the value or percentage would be a huge boon.

**If there is some kind of hack we could enable this generation with a javascript change or something we'd gladly run a patched version. Any hints on how to do this would be greatly appreciated!**

**How important is this feature to you?**
VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVery important. We're willing to pay for the development right now; pm me a venmo address.

We want our users that have disabilities to have equal access to their metrics. Right now, we just avoid using pie charts which is unfortunate.

We'd love to be able to use Metabase literally everywhere! But, because it can't do a basic item like displaying values on these two chart types, we're being forced off the platform onto Tableau and other Metabase alternatives. 

![Screen Shot 2020-07-22 at 11 08 30 AM](https://user-images.githubusercontent.com/1392297/88201254-da28c400-cc0c-11ea-89c7-3e1924dfb158.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Tagging this with "Completeness" since it's pretty weird that we have labels for line, area, bar, and combo charts, but not Pie, Row, or Scatter.

**Comment by abbosjon-kudratov** [comment]
Please add this option to pie charts. It's no good when the values displayed only while hovering

**Comment by exabrial** [comment]
Indeed. We're still hoping for a solution someday :)

**Comment by BeckerJonathan** [comment]
This feature is very important for us. The pie chart ist not useable for us without this function.

**Comment by raphaelmerx** [comment]
@alxnddr this was added for row charts in 0.45 (thanks!), but it seems pie charts are still missing that option?

**Comment by alxnddr** [comment]
@raphaelmerx you can enable showing percentages on the pie chart using the radio group here:
<img width="1350" alt="Screen Shot 2022-12-07 at 9 24 47 PM" src="https://user-images.githubusercontent.com/14301985/206326124-4d168017-f469-402d-b112-797653a153d3.png">
Please let us know if you need to show data instead of percentages

**Comment by exabrial** [comment]
Guys thank you for implementing the labels on the actual chart! We've been waiting a very very long time for this! It would be super helpful of the names (Doohicky, Gadget, etc( were also there too. Thank you!

**Comment by ekitzing** [comment]
> @raphaelmerx you can enable showing percentages on the pie chart using the radio group here: <img alt="Screen Shot 2022-12-07 at 9 24 47 PM" width="1350" src="https://user-images.githubusercontent.com/14301985/206326124-4d168017-f469-402d-b112-797653a153d3.png"> Please let us know if you need to show data instead of percentages

Yes, it would also be useful to see data/values on the charts. Best would be the option to choose between percentages, values or both. Thanks in advance.
