### ISSUE TITLE
User invitations appear to have expired when using AWS CloudFront

### ISSUE THREAD

**Issue by shinnawy** [metabase/metabase#12976]
**Description**
I have a setup where I have metabase v0.36.0 running on AWS Elastic Beanstalk (Docker). My setup is as follows:

**Metabase (Docker on AWS Elastic Beanstalk)
↓
Load Balancer *[Load balancer's FQDN]*
↓
CloudFront *[mydomain through Route53]***

When I have the site settings point to my user friendly `mydomain` I get the following error. However, replacing the first part of the URL with the `Load balancer's FQDN` works without an issue and I am able to set the user's credentials properly. From that point the user is able to signing using the user friendly `mydomain` and everything works perfectly.

**Logs**
- Server logs
```
[b172ce3e-4f7e-415f-903f-a088f661601c] 2020-07-22T16:08:48+02:00 DEBUG metabase.middleware.log GET /api/user/current 401 193.1 µs (0 DB calls)
"Unauthenticated"
[b172ce3e-4f7e-415f-903f-a088f661601c] 2020-07-22T16:08:48+02:00 DEBUG metabase.middleware.log GET /api/session/properties 200 947.2 µs (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (13 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
[b172ce3e-4f7e-415f-903f-a088f661601c] 2020-07-22T16:08:48+02:00 DEBUG metabase.middleware.log GET /api/session/password_reset_token_valid 400 992.8 µs (0 DB calls)
{:errors {:token "value must be a string."}}
```
- Browser logs
```
GET https://[mydomain]/api/user/current 401
GET https://[mydomain]/api/session/password_reset_token_valid?token=(redacted) 400
error validating token {status: 400, data: {…}, isCancelled: false}data: errors: token: "value must be a string."
```

**Expected behavior**
The user should be able to set their credentials through the link provided in the email that is behind the CloudFront distribution.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.181-140.257.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-21",
      "tag": "v0.36.0",
      "branch": "release-0.36.x",
      "hash": "b31049f"
    },
    "settings": {
      "report-timezone": "Africa/Cairo"
    }
  }
}
```

**Severity**
High

**Comment by flamber** [comment]
Hi @shinnawy 
I'm sure CloudFront is doing something it shouldn't - try disabling any "smart" WAF or whatever CloudFront calls it.
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Comment by shinnawy** [comment]
Thanks a lot @flamber for taking the time to respond. 

I had the WAF disabled and I was still running into the same problem. The solution was to set the following as the default cache behavior settings under the `Behaviors` section for my CloudFront distribution:

- `Cache Based on Selected Request Headers` set to **All**
- `Forward Cookies` set to **All**
- `Query String Forwarding and Caching` set to **Forward all, cache based on all**
