### ISSUE TITLE
AccordionList mismatched prop type and missing keys

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#12989]
**Describe the bug**
React is showing errors for `AccordionList.jsx`component. Namely:
1. invalid prop (type) for `width` (string is provided while number was defined in propTypes)
2. `AccordionListCell`children don't have unique key and React is complaining about it

**Logs**
See screenshots.

**To Reproduce**
1. Go to the home page in your local dev environment (usually `localhost:3000`)
2. Click on "Ask a new question"
3. Click on "Simple question"
4. Click on "Sample dataset"
    - you should see an opened dropdown for "Sample Dataset" (Search, Orders, People, Products, Reviews)
5. Open a console in your preferred browser
    - you should see two mentioned errors (make sure `errors` are checked among the filters)

**Expected behavior**
This component shouldn't produce any errors and React shouldn't complain.
1. `width` should be of a valid prop type
2. each child of `AccordionList` should have unique [key](https://reactjs.org/docs/lists-and-keys.html#keys). 

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/88340604-68e82e80-cd3c-11ea-8556-16a2e93d902d.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Brave Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
_Note: Tested and reproduced on Safari 13.1.1 (15609.2.9.1.2), as well._
- Your operating system: OS X 10.15.5
- Your databases: Sample database
- Metabase version: v0.36.0-snapshot
- Metabase hosting environment: dev build 
- Metabase internal database: H2 (default)

**Severity**
It doesn't affect users.
It represents a tech debt that can be fixed fairly easy.

**Additional context**
I already have a fix prepared locally. If I get an 👍 on this, PR can be up soon.

**Comment by flamber** [comment]
@nemanjaglumac :+1: for a detailed report. I'm fairly sure you only see this error because you're using dev-environment - it shouldn't show anything in releases. But in any case, it would be nice to get rid of some of the "false errors", when debugging on dev-builds.
(PS. For small things like this, you don't need to write such a detailed report - even though it's nice with the extra information :wink:)

**Comment by nemanjaglumac** [comment]
Sorry, it's just a habbit. I'll try to keep it brief next time.

I am actually seeing quite a few of similar errors in dev-environment. As ageneral rule, do you need help with those? In oder words, should I even open issues and PRs for similar stuff or just leave it be?

**Comment by paulrosenzweig** [comment]
> it would be nice to get rid of some of the "false errors", when debugging on dev-builds.

+1

It's probably worth us trying to fix a bunch of these at once since it's hard to worry about tidying these up when it the middle of building or fixing something else. Also, it seems like there's only a few distinct classes of warning (key prop, prop types, invalid props on DOM elements, etc).

It's probably far away, but it would be spectacular if we could fix things up enough and make Cypress or another CI tool fail when these warning occur.

> should I even open issues and PRs for similar stuff or just leave it be?

We probably don't need separate issues, but PRs are great!

**Comment by nemanjaglumac** [comment]
@paulrosenzweig yeah, it would be too much to have a separate issue for every small error.

I can open [WIP] PR as some kind of an accumulator for similar fixes. Even this issue can be renamed into something you guys think would be appropriate (along the lines of "Tech debt/React/cleanup/..."). Afaic, decent PR description with the list of affected components should do the trick.

**Comment by nemanjaglumac** [comment]
What do you do when there is nothing unique to be used as a key? I mean, I can always use the index 
``` javascript
{rows.map((row, index) => (
  <AccordionListCell
    {...this.props}
    key={index}
    row={row}
    sections={sections}
    onChange={this.handleChange}
    searchText={this.state.searchText}
    onChangeSearchText={this.handleChangeSearchText}
    sectionIsExpanded={sectionIsExpanded}
    sectionIsTogglable={sectionIsTogglable}
    toggleSection={this.toggleSection}
  />
))}
```
but that merely removes the warning - it doesn't solve the problem. After all, that's what React itself is using behind the scenes as a fallback, and they advise against using index as a key. So, I was interested if there's some common practice you agreed upon?

**Comment by nemanjaglumac** [comment]
Closing this because it will be addressed in https://github.com/metabase/metabase/pull/15098.
