### ISSUE TITLE
MS SQL Server Driver

### ISSUE THREAD

**Issue by karthikdwarakanath** [metabase/metabase#1298]
Please add ability to connect and use a MS SQL Server db or SQL Express db.

**Comment by ryanaverill** [comment]
+1

**Comment by configX** [comment]
+1

**Comment by adamghill** [comment]
+1

**Comment by duffn** [comment]
+1

**Comment by zvikara** [comment]
+1

**Comment by brenol** [comment]
+1

**Comment by rafael84** [comment]
+1

**Comment by jcolinmurray** [comment]
+1

**Comment by tlrobinson** [comment]
One more +1 from the duplicate issue:

> We are expecting some support to major database software

**Comment by michaelbironneau** [comment]
+1

**Comment by americanmoss** [comment]
+1

**Comment by AndreMommert** [comment]
+1

**Comment by dgomesbr** [comment]
@metabaseops can we push the driver using JTDS?

**Comment by ArthurZ** [comment]
+1

**Comment by lehtomar** [comment]
+1

**Comment by adaofeliz** [comment]
+1

**Comment by iwozzy** [comment]
+1

**Comment by jonasdiel** [comment]
+1

**Comment by boozelclark** [comment]
+1

**Comment by stephlow** [comment]
+1

**Comment by k-yak** [comment]
+1

**Comment by AlgyTaylor** [comment]
+1

**Comment by Tallicia** [comment]
+!

**Comment by terencevs** [comment]
+1

**Comment by thomasfrivold** [comment]
+1

**Comment by SemtexCharlie** [comment]
+1

**Comment by thomasfrivold** [comment]
Not because I particularly like it's SQL standard. Well the MSSQL stack does come with a bunch of nifty stuff. But because all my clients are on MS SQL.

**Comment by agilliland** [comment]
@dgomesbr , or anyone else, is there a specific reason for wanting the JTDS driver over the official Microsoft driver?

**Comment by dgomesbr** [comment]
@agilliland whenever you work within JVM, jTDS is preferred when using MSSQL. Take a time to read http://jtds.sourceforge.net/benchTest.html

**Comment by camsaul** [comment]
those benchmarks were ran on a computer with a 900MHz processor and 512 MB RAM. They look a little out-of-date

**Comment by dgomesbr** [comment]
@camsaul was just a quick pick for @agilliland. If you ever use MSSQL driver there are subtleties on how it works and how that affects performance. jDTS is a de-facto standard on accessing MSSQL.

**Comment by camsaul** [comment]
Are there other reasons to prefer jTDS besides (old) benchmarks? Ie, why else is it the de facto standard?

**Comment by ArthurZ** [comment]
My $0.02 and preference is to have both. Some clients just don't have the JTDS and will not allow it installed. Since the NCL (Native Client) is installed automatically when you install SQL Server it has to be covered. Furthermore, not having the NCL some features are not exposed in the JTDS as using the XML data type that may be required by us, in the data space.

**Comment by agilliland** [comment]
This is completed and merged into master so I'm going to close this issue.

This will be in our next official release which is coming out soon, but if anyone feels like trying a build of Metabase from master we are happy to get a few folks trying out the new MS SQL support and giving us any feedback.

**Comment by camsaul** [comment]
+1

**Comment by mattkrea** [comment]
@agilliland Seeing as all of our legacy databases internally are MSSQL I would *love* to give this a shot

**Comment by billsinc** [comment]
@agilliland was able to build and run just fine...is there no support for stored procs or views at this time?

**Comment by agilliland** [comment]
@billsinc that's great to hear!  views are something that we definitely want to support, so if your views aren't getting picked up and made available go ahead and file an issue on that and we can look into it.

regarding stored procs, how is it that you see those being exposed?  are you trying to call them as part of your querying?  we don't do anything with stored procs at the moment.

**Comment by agilliland** [comment]
@billsinc I think I'm still not getting a clear picture of how you want to use a Stored Proc in Metabase.

We think of Metabase as a read-only interaction layer on top of a database, so things like triggers and stored procs are generally outside the scope of what we are trying to provide access to.

Are you using stored procs with other tools that you've used?  What is an example of what these procs are doing for you?  updating tables?

**Comment by mattkrea** [comment]
@agilliland Don't want to speak for @billsinc a lot of our legacy systems internally have a lot of read only SPs for reports and things like that. In fact I'd say we have more SPs that only read data than those that write.

**Comment by camsaul** [comment]
@agilliland a stored procedure can just as easily be read-only. Here's a quick example:

```sql
CREATE PROCEDURE username_for_id

@user_id int

AS

SELECT "username" FROM "users"
WHERE user_id = @user_id
```

and then:

```sql
exec username_for_user '1'
```


I'm not surprised a lot of legacy SQL Server systems have lots of important logic saved in stored procedures. How to expose this functionality in Metabase is the big question

**Comment by agilliland** [comment]
got it.  so these are really meant to manifest themselves as queries with templated results and are probably not meant to function as tables which we introspect and make available to build queries on top of.

we'll definitely have to noodle on this one a bit and see how it could fit in.

@billsinc @mattkrea I created a new issue specifically for supporting Stored Procedures.  Feel free to vote and weigh in with ongoing discussion here ... https://github.com/metabase/metabase/issues/1532

**Comment by kpkrishnamoorthy** [comment]
I would love to try out Metabase against my company's Azure SQL (managed MSSQL) database.

**Comment by markalanevans** [comment]
+1

**Comment by forest** [comment]
+1

**Comment by salsakran** [comment]
Hey @karthikdwarakanath  @ryanaverill @configX @adamghill  @duffn @zvikara @brenol  @rafael84 @jcolinmurray @michaelbironneau @americanmoss @AndreMommert @dgomesbr @ArthurZ @lehtomar @adaofeliz  @iwozzy  @jonasdiel @boozelclark @stephlow  @k-yak @AlgyTaylor @Tallicia @terencevs @thomasfrivold @SemtexCharlie @billsinc @mattkrea @kpkrishnamoorthy @markalanevans @forest -

Just a heads up that this is live in our newest version (0.13). We don’t have any folks nearby who are running SQL server in production. If you actually have a server set up with realistic schema we would **really** appreciate you grabbing a version of 0.13 and letting us know if it works. We’ve tested it out against our test schema but would love a sanity check on a real workload.

**Comment by dgomesbr** [comment]
Hey @rafael84 and @brenol give it a try on our services and reply back to @salsakran

**Comment by kpkrishnamoorthy** [comment]
Hey @salsakran - I attempted to use version 0.13 to connect to my Azure SQL database, and I get the below in STDOUT while running the metabase.jar file:

2015-12-03 17:58:46,908 [DEBUG] metabase.middleware :: POST /api/setup/validate
2015-12-03 17:58:51,910 [ERROR] metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
2015-12-03 17:58:51,916 [DEBUG] metabase.middleware :: POST /api/setup/validate 400 (5002 ms)
{:message "Timed out after 5000 milliseconds."}

However, I *am* able to connect to the database from the same system using tsql, with the command tsql -H <server_name>.database.windows.net -p 1433 -U <user>@<server_name> -P <password>.

Maybe the sqlserver driver doesn't work with Azure SQL?

**Comment by camsaul** [comment]
@kpkrishnamoorthy did you include `.database.windows.net` in the `host`

**Comment by camsaul** [comment]
It should work but your settings might need to be tweaked. [From what it looks like for Azure](https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-java-simple-windows/)  you'll need to set `Database username` to `user@server_name`

**Comment by kpkrishnamoorthy** [comment]
@camsaul Yes, .database.windows.net is in the hostname I tried to configure metabase with. I tried in the format hostname.database.windows.net - the same string I used while connecting via tsql, where it worked.

Database username was user@server_name, as well, like in the snippet above where I've pasted in the tsql command line. Those were the same settings used in metabase.

Additionally, those same settings are the ones that work on the Rails app that connects to this database.

Thanks for the suggestions!

**Comment by tomashm** [comment]
@salsakran Is it possible to log on to the database when it's configured to use Windows domain authentication?

According to https://msdn.microsoft.com/en-us/library/ms378428(v=sql.110).aspx, the jdbc url should look something like this: jdbc:sqlserver://somehost;integratedSecurity=true;

**Comment by ryanaverill** [comment]
@salsakran  I've tested out version 0.13 and its working great. This was with a real production use database - its absolutely awesome! Two suggestions: 

1. We force protocol encryption to MSSQL and this wasn't supported. I had to disable it in MSSQL in order to get connected from Metabase. This might be related to the same issue that @kpkrishnamoorthy reported.

2. No MSSQL view support.

**Comment by AlgyTaylor** [comment]
> @salsakran Is it possible to log on to the database when it's configured to use Windows domain authentication?

This would be very handy +1

**Comment by iwozzy** [comment]
I've been trying to connect to various SQL Server instances and I am yet to be successful. I'm trying to connect to my local instance, an Azure instance and our production instance (not Azure). For every attempt I get:

`Failed to connect to database: Timed out after 5000 milliseconds`

Is there a way to enable more logging?
Someone mentioned `.database.windows.net` in the `host`, is that something that I should do?

**Comment by NicoJuicy** [comment]
+1 for MS SQL Support

**Comment by mazameli** [comment]
@NicoJuicy, just a heads up that we've had MS SQL support since November of last year. :)
