### ISSUE TITLE
Issue with API call - GET /api/database/XXX/metadata

### ISSUE THREAD

**Issue by gunjansriv86** [metabase/metabase#12991]
Following is the issue i am facing
1.	Metabase loads the dashboard 643 at 11:45 properly (Refer pic-1)
2.	It then call API api/database/322/metabase at 11:46. Database id 322- is a large psotgres database. The API call takes lots of time, post which the dasboard **Snaps!!**  (refer Pic 2). 
3.	After 4 min, at 11:50 , metabase starts reloading and synching timezone. Post this dashboard is visible again (refer Pic 3)

**Pic -1**
 
![image](https://user-images.githubusercontent.com/44700044/88367375-3c1e3080-cda9-11ea-8342-8d36d15cf605.png)

**Pic -2** 
 
![image](https://user-images.githubusercontent.com/44700044/88367400-47715c00-cda9-11ea-9dcf-97440af4cab1.png)

**Pic -3** 

![image](https://user-images.githubusercontent.com/44700044/88367424-535d1e00-cda9-11ea-925c-892d4bf61a2b.png)

https://github.com/metabase/metabase/issues/new/choose

**Comment by gunjansriv86** [comment]
using version https://www.metabase.com/docs/v0.35.4/

**Comment by gunjansriv86** [comment]
Database it hits has 138 schemas and 10k + plus tables. However, the user created on metabase has been given read access only on 1 schema. Even after doing all of this, it the API call of metadata get stuck and crashes the dashboard

**Comment by flamber** [comment]
Hi @gunjansriv86 
Please post "Diagnostic Info" from Admin > Troubleshooting.
Please post the logs in text from Admin > Troubleshooting > Logs - I cannot see much from the very small image.
How many tables does the single schema have, which the user has permissions to?
How much data is is being sent - check the browser developer Network-tab?

**Comment by gunjansriv86** [comment]
Hi @flamber 

Attached are requested details. Hope this helps. Let me know if you need more details.

**_Please post the logs in text from Admin > Troubleshooting > Logs - I cannot see much from the very small image._**
(refer attached log file "Troubleshooting log.txt"

1. Log file
[Troubleshooting log.txt](https://github.com/metabase/metabase/files/4971719/Troubleshooting.log.txt)


Starts with loading dashboard 643. It get stuck when it tries to call metadata API for database 322. (Dashboard 643 fetches data from database 322)
In the log , second last log entry (API call), causes the dashboard page to crash. After this i have to refresh the dashboard everytime. Refer Network data **Pic 4**

_**How much data is is being sent - check the browser developer Network-tab?**_ 
(13.2 MB) (refer pic 4)
**Pic 4**
![image](https://user-images.githubusercontent.com/44700044/88387186-9df19100-cdcf-11ea-8ffc-a6c208470387.png)
 **pic 5**
this also caused 
![image](https://user-images.githubusercontent.com/44700044/88387545-4dc6fe80-cdd0-11ea-9883-5f6639588c7c.png)

_**How many tables does the single schema have, which the user has permissions to?**_
1669 tables

What i also observed was that my troubleshooting log page also snapped and threw not enough memory  exception page
**Pic 6**
![image](https://user-images.githubusercontent.com/44700044/88387471-1eb08d00-cdd0-11ea-9ee8-8e6f12e1538e.png)

**Comment by flamber** [comment]
@gunjansriv86 
1. Post "Diagnostic Info" from Admin > Troubleshooting.
2. How much memory does the client computer have available (where Chrome is running)?

**Comment by gunjansriv86** [comment]
**_Post "Diagnostic Info" from Admin > Troubleshooting._**

[Diagnostic info.txt](https://github.com/metabase/metabase/files/4972486/Diagnostic.info.txt)

**_How much memory does the client computer have available (where Chrome is running)?_**
1. Client computer where chrome is running has 8 GB  (64 bit OS)
2. Metabase server has 16 GB memory, and ran jar with JVM option as -Xmx10g

**Comment by flamber** [comment]
@gunjansriv86 
That does not tell how much memory is available on the client computer, just how much RAM it has installed.
Try loading the dashboard in incognito-mode without any extensions and see if that makes a difference.
On a side-note, Java 10 has been [EOL](https://en.wikipedia.org/wiki/Java_version_history) for a couple of years. We recommend using [AdoptOpenJDK 11](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot).

**Comment by gunjansriv86** [comment]
Hey @flamber 

Client machine (organization's employee) is not allow to open the chrome in incognito mode. However, i logged into the metabase production server and opened dashboard in incognito mode there. It is not crashing in incognito mode. 
But this also caused 85 % RAM consumption on  metabase server (16GB).

What do you suggest if one has open the dashboard without incognito mode ?

PS: i will get my JDK updated to v11

**Comment by flamber** [comment]
@gunjansriv86 There's a lot of improvement in 0.36.0, but I'm not sure how much it would help with this amount of schemas/tables.
Please try that version - remember to backup before upgrading, since you will have to revert to backup if you want to downgrade.

**Comment by gunjansriv86** [comment]
Thanks @flamber . I just tried the latest version 0.36.0. Significant improvement in performance. Dashboards aren't crashing anymore. Like it :) 
Seem like earlier API call of GET database/XXX/metadata after opening dashboards/question was  redundant ( Even after i chose the option of syncing the field when i wanted to )

**Comment by flamber** [comment]
@gunjansriv86 Okay, excellent! I'm going to close this issue. We still have a couple of other open issues you should follow #11806
