### ISSUE TITLE
Dashboards with questions, that user doesn't haven't permissions to, breaks completely

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13005]
**Describe the bug**
If a dashboard contains a single question, which a user does not have permissions to, then the entire dashboard breaks for that user.

**To Reproduce**
1. Create a collection "C1" under root
2. Create dashboard "D1" in "C1"
3. Simple question > Sample Dataset > Orders - save as "Q1" in "C1" and add to "D1"
4. Simple question > Sample Dataset > Orders - save as "Q2" in root (not "C1") and add to "D1"
5. Create a user "U1" that only has permissions to "C1"
6. Login as "U1" and go to "D1" in "C1" - the entire dashboard fails with `e is undefined` (Firefox) or `Cannot read property 'type' of undefined` (Chromium)
![image](https://user-images.githubusercontent.com/1447303/88552808-cde5a200-d024-11ea-8ef3-3e6d0ff4eea0.png)
7. Reverting back to 0.35.4 shows a nice little error for that card `Sorry, you don't have permission to see this card.`
![image](https://user-images.githubusercontent.com/1447303/88553637-ca064f80-d025-11ea-921e-df56a2838702.png)

**Information about your Metabase Installation:**
Metabase 0.36.0

**Comment by paulrosenzweig** [comment]
Fixed in #13010
