### ISSUE TITLE
Filter widget type is none if data column have null values or Arabic letters

### ISSUE THREAD

**Issue by AymanEG** [metabase/metabase#13003]
Hello there,

I am working on a PostgreSQL database with metabase 0.35.4
We have 2 columns for our suppliers
1- Business segment (Cafe, restaurants .. etc).
2- Business name.

Users can choose what segment they are in or leave it blank so stored as null in db. They can fill their official business name which can be English or Arabic or mix of them.

Query example as simple as:

```
select
    id, name
from verticals_branch
[[where {{supplier}}]]
```
then mapping supplier to verticals_branch.name

If I try to create a filter for those columns, the widget always show as none, it works just fine for other columns but not those two.
![image](https://user-images.githubusercontent.com/23207050/88539810-2f504580-d012-11ea-811f-ba981497c95a.png)

**Comment by flamber** [comment]
Hi @AymanEG 
What is the Field Type of `verticals_branch.name` in Admin > Data Model? Make sure it's one of the allowed ones:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type

**Comment by AymanEG** [comment]
Thank you, fixed. I had to set the type manually to Entity name.
