### ISSUE TITLE
When using Google Sign in, an error occurs and you cannot sign in

### ISSUE THREAD

**Issue by evantahler** [metabase/metabase#13012]
**Describe the bug**
When using Google Sign in, an error occurs and you cannot sign in.  The error `The window has been closed before completing Google Authentication` appears

**Logs**
N/A

**To Reproduce**
1. Enable Google Sign In per the instructions
2. Enable your domain users
3. Log out, and try to sign in again

**Expected behavior**
You should be signed in

**Screenshots**
<img width="619" alt="Screen Shot 2020-07-27 at 1 12 47 PM" src="https://user-images.githubusercontent.com/303226/88587586-0082a100-d00b-11ea-8728-ddf8259afd44.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: OSX
- Your databases: N/A
- Metabase version: v0.36.0
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres (Heroku)

**Severity**
Annoying

**Comment by flamber** [comment]
Hi @evantahler 
Please post "Diagnostic Info" from Admin > Troubleshooting.
And check the browser developer console for errors. It might be because you're blocking third-party cookies.

**Comment by evantahler** [comment]
Thanks for the response @flamber!

It looks like it was just Google taking a _very_ long time to propagate the update to our domain list.  

All good!  Thanks for making Metabase!
