### ISSUE TITLE
Environment Variable MB_API_KEY does not work [update documentation]

### ISSUE THREAD

**Issue by jbraganza** [metabase/metabase#13026]
**Describe the bug**
The environment variable MB_API_KEY is described as:

MB_API_KEY
Type: string
Default: null

Middleware that enforces validation of the client via the request header X-Metabase-Apikey. If the header is available, then it’s validated against MB_API_KEY. When it matches, the request continues; otherwise it’s blocked with a 403 Forbidden response.

We have tried using this, but it does not work.

**Logs**
Easily reproducable

**To Reproduce**
1. Setup environment variable for MB_API_KEY
2. Use the API to try to perform any operation.
3. Does not work.

**Expected behavior**
We should get a valid response back from the API if we use the API_KEY as opposed to the session ID.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …) N/A, not browser issue.
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …) N/A not OS issue.
- Your databases: (e.x. MySQL, Postgres, MongoDB, …) Amazon Athena
- Metabase version: (e.x. 0.19.3) v1.35.4
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …) Fargate ECS
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL) Amazon Aurora PostGres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely? Medium, we can work around but ideally this would be the technique we use moving forward.
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
For reference: https://github.com/metabase/metabase/blob/master/docs/operations-guide/environment-variables.md#mb_api_key

**Comment by paoliniluis** [comment]
Just for reference: MB_API_KEY is only for the notify endpoint for now

**Comment by camsaul** [comment]
Yeah. The documentation is completely wrong. We should update the documentation and close this issue out -- as @paoliniluis mentioned it only applies to the notify endpoints.

**Comment by camsaul** [comment]
@paoliniluis can you update the documentation?

**Comment by paoliniluis** [comment]
yup, done @camsaul, I believe that the request is broader (like using the same API key for other endpoints)

**Comment by paoliniluis** [comment]
This was solved with https://github.com/metabase/metabase/pull/15780
