### ISSUE TITLE
Generating metrics description breaks for custom expressions

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#13022]
On working 0.36.0:
1. Admin > Data Model > Metric
2. Create new, table Sample Dataset > Orders, view Custom Expression `Sum([Discount] * [Quantity])`, save the metric
![image](https://user-images.githubusercontent.com/1447303/88684391-19678100-d0f5-11ea-806b-99ce21c06ae9.png)
3. Refresh on Metric overview page, errors with `Unexpected input given to normalize. Expected type to be "object", found "string".`
![image](https://user-images.githubusercontent.com/1447303/88295262-79c57f80-ccfd-11ea-914d-59e9c22b19d9.png)

_Originally posted by @flamber in https://github.com/metabase/metabase/issues/12982#issuecomment-664945290_

**Comment by flamber** [comment]
Fixed by #13030 - will be part of 0.36.1, which should be released in a few days.
