### ISSUE TITLE
table/column names get mangled: e.g. "vertrieb_verlauf" becomes "Vert Ri Eb Ve Rla Uf"

### ISSUE THREAD

**Issue by TjrGithub** [metabase/metabase#13046]
**Describe the bug**
I connected a fresh Metabase container to my Postgres database. Other than that, the settings are entirely the default ones. It shows all of the table and column names, but completely mangled, e.g.:

table_name | metabase shows
vertrieb_verlauf | Vert Ri Eb Ve Rla Uf
dashboard_monatsroller | Dashboard Mo Nats Roller

column_name | metabase shows
bezug_neujahr_datum | Be Zug Neu Ja Hr Datum

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
None of the Firefox menus are called javascript console. This is the "Web-Konsole": https://pastebin.com/JG7wycLB

docker container logs: Contains too much confidential client data

**To Reproduce**

1. start the official postgres and metabase/metabase containers using docker-compose.
2. in psql: create database bnb with encoding = 'utf8'; ..."
3. create a bunch of tables (with dbt run from getdbt.com)
4. create and use a fresh firefox profile
5. Go to http://127.0.0.1:3001/setup/ in Firefox 
6. create a new metabase user, log in, German language
7. go to http://127.0.0.1:3001/reference/databases/2/tables
8. Compare the table names, and column names, with the actual table names

**Expected behavior**
The table and column names should be the same as in the database, i.e. if you connect manually with "psql"

**Screenshots**
https://imgur.com/a/y5xoAHz

**Information about your Metabase Installation:**
$ docker  history metabase/metabase
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
b5a3a4ae2379        19 hours ago        /bin/sh -c #(nop)  ENTRYPOINT ["/app/run_met…   0B                  
<missing>           19 hours ago        /bin/sh -c #(nop)  EXPOSE 3000                  0B             
You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "de",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "5.3.0-55-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-30",
      "tag": "v0.36.1",
      "branch": "release-0.36.x",
      "hash": "55312e4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
Firefox 78.0.2 (64-Bit)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
Ubuntu 19.10

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres:latest from dockerhub

- Metabase version: (e.x. 0.19.3)
 v0.36.1

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
docker

- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)
H2

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

Blocking. I can't show this to my client.

**Additional context**
I deliberately filed as early as possible, with everything out-of-the-box, because most projects will want things to work out of the box. That also means I don't know much about Metabase - I've been using it minutes before running into this bug.

**Comment by flamber** [comment]
Hi @TjrGithub 
Disable "Friendly table and field names": https://www.metabase.com/docs/latest/administration-guide/08-configuration-settings.html#friendly-table-and-field-names
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
