### ISSUE TITLE
Admin-> Data Model -> Metrics Page will not Load

### ISSUE THREAD

**Issue by slickrock22** [metabase/metabase#13055]
I am attempting to load the metrics page so that I can add a new metric but when I click the menu item it just spins attempting to load.

![MetabaseMetric](https://user-images.githubusercontent.com/12418981/89133599-d33e6300-d4e2-11ea-86ca-5f04febb1263.JPG)

**Logs**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-31",
      "tag": "v0.36.2",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

**To Reproduce**
1. Got o Admin 
2. Click on Data Model
3. Click on Metrics

**Additional context**
Interestingly I have two instances of Metabase running. Production and Dev.  I upgraded both to v36.2.  Dev can access metrics without a problem but production just spins.  I noticed there were some minor Postgres version and Docker Linux version difference so I upgraded both so they were identical.  Prod still spins and Dev still works.

**Comment by flamber** [comment]
Hi @slickrock22 
It's probably the same as #12982, which we didn't get enough information on to be able to reproduce.
Can you provide more details - both errors logs and browser console?
And it's probably something to do with a specific Metric on production, which is different than on your dev, so if you can go through these, then it would be very helpful to help tracking this bad boy down.

**Comment by slickrock22** [comment]
Thanks for the response.  They do look like the same issue.  The log is
pretty verbose.  Is there something specific that you are looking for in it?

Console Results
app-main.bundle.js?1e6ba1eae4be22e31f2b:5 Uncaught TypeError: Cannot read
property 'map' of undefined
    at Object.z [as aggregation] (app-main.bundle.js?1e6ba1eae4be22e31f2b:5)
    at app-main.bundle.js?1e6ba1eae4be22e31f2b:5
    at Array.map (<anonymous>)
    at t.formatQueryDescription (app-main.bundle.js?1e6ba1eae4be22e31f2b:5)
    at t.value (app-main.bundle.js?1e6ba1eae4be22e31f2b:5)
    at c._renderValidatedComponentWithoutOwnerOrContext
(vendor.bundle.js?1e6ba1eae4be22e31f2b:1)
    at c._renderValidatedComponent (vendor.bundle.js?1e6ba1eae4be22e31f2b:1)
    at c.performInitialMount (vendor.bundle.js?1e6ba1eae4be22e31f2b:1)
    at c.mountComponent (vendor.bundle.js?1e6ba1eae4be22e31f2b:1)
    at Object.mountComponent (vendor.bundle.js?1e6ba1eae4be22e31f2b:1)

**Comment by flamber** [comment]
@slickrock22 We haven't been able to reproduce, so we don't know what is going wrong.

Are you saying that your prod and dev application database are identical? That makes even less sense on why it would only work on one of them.

What do you see from the `GET /api/metric` request? Please compare the responses between prod and dev.

**Comment by slickrock22** [comment]
The prod and dev environments software versions (Metabase, Docker Linux and
Postgres RDS) are identical.  The metrics on each are not the same.  I just
attempted to access the metric page this morning and the only 8/5/2020
reference with '/api/metric' request is

[8edda125-e024-476c-8a06-7a0a4f821d8b] 2020-08-05T05:29:55-05:00 DEBUG
metabase.middleware.log GET /api/metric 200 8.6 ms (3 DB calls) App DB
connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (115 total active
threads) Queries in flight: 0 (0 queued)

I would have expected to see something referencing '/api/metric' fail in
the log (red).

As far as red log text on 8/5/2020 (today) after an attempt to access the
Metric page.


[8edda125-e024-476c-8a06-7a0a4f821d8b] 2020-08-05T00:09:17-05:00 WARN
metabase.middleware.log POST /api/jsonws/invoke 404 120.4 µs (0 DB calls)
"API endpoint does not exist."

[8edda125-e024-476c-8a06-7a0a4f821d8b] 2020-08-05T05:28:05-05:00 DEBUG
metabase.middleware.log GET /api/field/69 401 143.0 µs (0 DB calls)
"Unauthenticated" [8edda125-e024-476c-8a06-7a0a4f821d8b]
2020-08-05T05:28:05-05:00 DEBUG metabase.middleware.log GET /api/field/80
401 93.0 µs (0 DB calls) "Unauthenticated"

[8edda125-e024-476c-8a06-7a0a4f821d8b] 2020-08-05T05:34:53-05:00 DEBUG
metabase.middleware.log POST /api/dataset 400 1.7 ms (0 DB calls) {:errors
{:database "value must be an integer."}}

We have 4 metrics on Prod so it would not be the end of the world if we had
to delete and recreate.  Where are the metrics stored?  Should I try to
manually modify or delete directly in the DB and see if it loads?  I have
time so can work through.

**Comment by flamber** [comment]
@slickrock22 It would be great if you could help by sending the response from `GET /api/metric` (and/or the table dump from `metric`) to my username @ metabase . com
Otherwise we will not be able to fix the bug - yes, you can delete the metrics, but at some point you're likely going to create similar metric again, and then you're in the same situation.
Metrics are stored in the table `metric` in the application database.

**Comment by paulrosenzweig** [comment]
@slickrock22 thanks for sending that over! I think I see the issue.

We used to allow unnamed custom expressions. Now the name is required, but we're failing on generating descriptions for aggregations without names. Here's an example failing definition: `"{"aggregation":[["*",1,2]],"source-table":123}`

We should fix this crash in the next point release to skip over these aggregations. Separately though, we want to stop requiring the name for custom expressions in metrics. It seems weird to name both the metric and the aggregation within the metric.

As a workaround before we patch this, if you navigate directly to the metric at `/admin/datamodel/metric/[metric id]`, you should be able to add a name to the custom expression.

**Comment by slickrock22** [comment]
I must not fully understand.  Here is an example.  When I click on the
metric, it is named.  Can you review the table dump I provided @flamber and
let me know exactly what I need to modify to test your suggestion?  Thanks!

[image: tempsnip.png]

**Comment by slickrock22** [comment]
Just figured it out.  Was hard to understand by reviewing the table.  It was id=4.  Added Name and it worked.  Thanks!

**Comment by flamber** [comment]
Great you got it working. Closing in favor of #10844
