### ISSUE TITLE
Multiple values in dashboard filter for numeric column not parsed onto drill-through

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13062]
**Describe the bug**
When dashboard filter that is connected to a numeric column has multiple values, then only the first value is parsed on to the question filter, when clicking card title or doing drill-through.

**To Reproduce**
1. Go to Admin > Data Model > Sample Dataset > Reviews > Rating > Field Type: Category
2. Simple question > Sample Dataset > Reviews, save as Q1 and add to dashboard
3. On dashboard, add filter > Category and link to Q1.Rating and save dashboard
4. Input `5` and `4` into the filter:
![image](https://user-images.githubusercontent.com/1447303/89281692-bf157580-d64a-11ea-88b0-9da4a8ed27a4.png)
   a. Do a drill-through on Reviewer=`xavier`, then the question shows "No results" - only filters Rating=`5`:
       ![image](https://user-images.githubusercontent.com/1447303/89282095-4f53ba80-d64b-11ea-9125-809ae379d01d.png)
   b. Click the card title - only filters Rating=`5`:
       ![image](https://user-images.githubusercontent.com/1447303/89281851-f8e67c00-d64a-11ea-835c-f1d5ac23350b.png)

**Information about your Metabase Installation:**
Metabase 1.34.3 and 0.36.2

**Severity**
Can be slightly confusing, but it's fairly easy to adjust the filter after going to the question.

**Additional context**
Related to #11503 and #12496

**Comment by nemanjaglumac** [comment]
This seems to be fixed now.
I am finishing a repro, but it is working locally.
