### ISSUE TITLE
Queries generated using the QB don't run against Postgres tables within a schema

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1306]
See  http://discourse.metabase.com/t/connected-to-rds-postgres-cant-run-queries/21 for more info.

**Comment by rafael84** [comment]
+1

**Comment by brenol** [comment]
+1

**Comment by jonasdiel** [comment]
+1

**Comment by vincentlaucy** [comment]
+1

**Comment by roemhildtg** [comment]
I have the same issue, however, when I go into sql mode and try to run the query it says 

Schema "SCHEMA_NAME" not found. 

`select count(*) from schema_name.building where 1=1 LIMIT 10;`

The sql command does work in psql.exe though. FYI I'm using PostGIS on top of PostgreSQL if it makes a difference.
