### ISSUE TITLE
Switch Presto driver to use JDBC

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#13060]
Presto supports a [JDBC driver](https://prestosql.io/docs/current/installation/jdbc.html) - that would handle parameters like other `sqljdbc` drivers do. We should use it instead of the REST API.

**Comment by flamber** [comment]
Duplicate of #8893 ?

**Comment by robdaemon** [comment]
Hah, yes, you are correct. Your ability to find things in here never ceases to amaze, @flamber :open_mouth:
