### ISSUE TITLE
Distinct, non-empty sequence of Field clauses

### ISSUE THREAD

**Issue by AbdulMoeedfieldforce** [metabase/metabase#13077]
I am getting this issue when I click on View. I Sync dataBase scheme and Rescan field values many times but still getting issues. But when I run the same view as a query in the native query it gives me an accurate result 

class clojure.lang.ExceptionInfo,
:error "Distinct, non-empty sequence of Field clauses",
:stacktrace
("--> query_processor.middleware.add_implicit_clauses$fn__41715$sorted_implicit_fields_for_table__41720.invoke(add_implicit_clauses.clj:48)"
"query_processor.middleware.add_implicit_clauses$fn__41823$add_implicit_fields__41828$fn__41832.invoke(add_implicit_clauses.clj:93)"
"query_processor.middleware.add_implicit_clauses$fn__41823$add_implicit_fields__41828.invoke(add_implicit_clauses.clj:86)"
"query_processor.middleware.add_implicit_clauses$fn__41911$add_implicit_mbql_clauses__41916$fn__41920.invoke(add_implicit_clauses.clj:130)"
"query_processor.middleware.add_implicit_clauses$fn__41911$add_implicit_mbql_clauses__41916.invoke(add_implicit_clauses.clj:126)"
"query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:141)"
"query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invoke(add_implicit_clauses.clj:137)"
"mt.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__40744.invoke(row_level_restrictions.clj:229)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__42348.invoke(add_source_metadata.clj:107)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45220.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__42185.invoke(add_row_count_and_status.clj:16)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__43366.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__44834.invoke(resolve_driver.clj:22)"
"query_processor.middleware.store$initialize_store$fn__47960$fn__47961.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47960.invoke(store.clj:10)"
"query_processor.middleware.async$async__GT_sync$fn__41202.invoke(async.clj:23)"
"query_processor.middleware.async_wait$runnable$fn__42407.invoke(async_wait.clj:89)"),
:query
{:query {:source-table 4723},
:type "query",
:parameters [],
:async? true,
:middleware {:add-default-userland-constraints? true, :userland-query? true},
:info
{:executed-by 99,
:context :ad-hoc,
:card-id nil,
:nested? false,
:query-hash [23, 65, -92, -67, -16, -92, 18, 20, -92, 110, -84, 76, 113, 120, 120, -44, 117, -18, 61, -81, 55, 47, 59, -7, -14, 17, 126, -68, -58, 19, 19, 65]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}},
:preprocessed nil,
:native nil,
:ex-data {:type :schema.core/error, :value (), :error (named (not ("Non-empty" a-clojure.lang.LazySeq)) "Distinct, non-empty sequence of Field clauses")}}

[26e95569-1545-46be-9c97-17d54cf13159] 2020-08-06T23:48:54+05:00 DEBUG metabase.middleware.log POST /api/dataset 202 [ASYNC: completed] 691.8 ms (25 DB calls) Jetty threads: 8/50 (3 idle, 0 queued) (333 total active threads) Queries in flight: 1

**Comment by flamber** [comment]
Hi @AbdulMoeedfieldforce Can we continue the troubleshooting in the support email that Bizzah started?

**Comment by AbdulMoeedfieldforce** [comment]
Yes we can but we Sync DataBase schema and rescan the fields it is not
resolving our issue but same view is running in native query

Abdul Moeed

**Comment by flamber** [comment]
@AbdulMoeedfieldforce Please post
1. "Diagnostic Info" from Admin > Troubleshooting
2. Which database type and version is this?
3. Is it a table or a view?
4. The log from Admin > Troubleshooting > Logs, when you re-sync the problematic database via Admin > Databases
If you don't see any errors during the sync, then you need to start with additional debug logging:
`java -Dlog4j.configuration=https://log4j.us/templates/metabase?trace=metabase.sync -jar metabase.jar`

**Comment by AbdulMoeedfieldforce** [comment]
It is a view  and this is log query when i  browse the view

:class clojure.lang.ExceptionInfo, :error "Distinct, non-empty sequence of
Field clauses", :stacktrace ("-->
query_processor.middleware.add_implicit_clauses$fn__41715$sorted_implicit_fields_for_table__41720.invoke(add_implicit_clauses.clj:48)"
"query_processor.middleware.add_implicit_clauses$fn__41823$add_implicit_fields__41828$fn__41832.invoke(add_implicit_clauses.clj:93)"
"query_processor.middleware.add_implicit_clauses$fn__41823$add_implicit_fields__41828.invoke(add_implicit_clauses.clj:86)"
"query_processor.middleware.add_implicit_clauses$fn__41911$add_implicit_mbql_clauses__41916$fn__41920.invoke(add_implicit_clauses.clj:130)"
"query_processor.middleware.add_implicit_clauses$fn__41911$add_implicit_mbql_clauses__41916.invoke(add_implicit_clauses.clj:126)"
"query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:141)"
"query_processor.middleware.add_implicit_clauses$maybe_add_implicit_clauses.invoke(add_implicit_clauses.clj:137)"
"mt.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__40744.invoke(row_level_restrictions.clj:229)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__42348.invoke(add_source_metadata.clj:107)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45220.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__42185.invoke(add_row_count_and_status.clj:16)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__43366.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__44834.invoke(resolve_driver.clj:22)"
"query_processor.middleware.store$initialize_store$fn__47960$fn__47961.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47960.invoke(store.clj:10)"
"query_processor.middleware.async$async__GT_sync$fn__41202.invoke(async.clj:23)"
"query_processor.middleware.async_wait$runnable$fn__42407.invoke(async_wait.clj:89)"),
:query {:query {:source-table 4721}, :type "query", :parameters [], :async?
true, :middleware {:add-default-userland-constraints? true,
:userland-query? true}, :info {:executed-by 99, :context :ad-hoc, :card-id
nil, :nested? false, :query-hash [-127, 87, -110, -67, 80, -80, -58, 118,
84, -1, -118, -8, 68, -22, -15, 37, 33, -128, 121, 56, 25, -17, -120, -4,
-107, -63, -60, -17, -55, -126, -67, 103]}, :constraints {:max-results
10000, :max-results-bare-rows 2000}}, :preprocessed nil, :native nil,
:ex-data {:type :schema.core/error, :value (), :error (named (not
("Non-empty" a-clojure.lang.LazySeq)) "Distinct, non-empty sequence of
Field clauses")}} [26e95569-1545-46be-9c97-17d54cf13159]
2020-08-07T01:17:59+05:00 DEBUG metabase.middleware.log POST /api/dataset
202 [ASYNC: completed] 85.1 ms (25 DB calls) Jetty threads: 8/50 (2 idle, 0
queued) (331 total active threads) Queries in flight: 1

**Comment by flamber** [comment]
@AbdulMoeedfieldforce I need all the information from the 4 points.
I cannot use the log from when you browse the table, since that's not the root cause of the problem.

**Comment by AbdulMoeedfieldforce** [comment]
I am attaching two images when I browse the same view it gives an error but
with native query, it is working fine

**Comment by flamber** [comment]
@AbdulMoeedfieldforce You cannot attach images via email on Github. Again - can you please use support AT metabase . com ?

**Comment by AbdulMoeedfieldforce** [comment]
1 - Diagnostic INFO
{
"browser-info": {
"language": "en-US",
"platform": "Win32",
"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
"vendor": "Google Inc."
},
"system-info": {
"java.runtime.name": "Java(TM) SE Runtime Environment",
"java.runtime.version": "1.8.0_181-b13",
"java.vendor": "Oracle Corporation",
"java.vendor.url": "http://java.oracle.com/",
"java.version": "1.8.0_181",
"java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
"java.vm.version": "25.181-b13",
"os.name": "Windows Server 2012",
"os.version": "6.2",
"user.language": "en",
"user.timezone": "UTC"
},
"metabase-info": {
"databases": [
"mysql"
],
"hosting-env": "unknown",
"application-database": "h2",
"application-database-details": {
"database": {
"name": "H2",
"version": "1.4.197 (2018-03-18)"
},
"jdbc-driver": {
"name": "H2 JDBC Driver",
"version": "1.4.197 (2018-03-18)"
}
},
"run-mode": "prod",
"version": {
"tag": "v1.34.3",
"date": "2020-02-28",
"branch": "enterprise-release-1.34.x",
"hash": "ab6cc46"
},
"settings": {
"report-timezone": null
}
}
}


2- MySql 5.7 DataBase
3 - I am using View

**Comment by flamber** [comment]
@AbdulMoeedfieldforce 
Without seeing the log, I don't know what the error is, but like I wrote to Bizzah, there has been a lot of fixes to the sync+scan process in 1.35 and 1.36, so I'm very sure that this problem is fixed if you upgraded to the latest release, 1.36.3

Make sure to backup your application database, since you'll have to revert to the backup if you need to downgrade, because of a lot of schema changes in 1.36.

Also, you need to migrate away from H2:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Comment by AbdulMoeedfieldforce** [comment]
We are using VIEWS earlier too but not getting any issue, but
unfortunately, this time we are getting the issue, the view is generated in
Metabase and getting data from another view,

SET  @createqry =CONCAT("CREATE OR REPLACE VIEW
 ",metabasedb,"`",workFlowName, "`  As  " ,
        " SELECT  RowNumberInView() As ID,  ",@SelectionFromView,"  FROM
tickets_timeline_survey_detail ttsd WHERE ttsd.WorkflowId=",workflowId,"");
meta base view is getting data from this view
tickets_timeline_survey_detail .

**Comment by flamber** [comment]
@AbdulMoeedfieldforce Try setting up 1.36.3 on a test machine and connect it to the MySQL database and see if that version can see the view.

**Comment by AbdulMoeedfieldforce** [comment]
In Metabase View can we get data from other databases.
like
Create View MyMetaBaseView  As  Select * from DataBase1.table ;

Here  MyMetaBaseView is a view name that we defined in MetaBase and it is
getting data from a different database table.
