### ISSUE TITLE
Incorrect URL parsing/generation for JWT login page

### ISSUE THREAD

**Issue by ngrigoriev** [metabase/metabase#13078]
**Describe the bug**
Metabase does not generate a valid URL if the base URL contains query parameters

**Logs**
n/a

**To Reproduce**
1. Configure the JWT login page URL as something like "http://myauthserver.mydomain.home:9000/login/to/reports?tenantId=abc"
2. Attempt to log in 
3. The generated URL will be "http://myauthserver.mydomain.home:9000/login/to/reports?tenantId=abc?return_to=/" (note two "?")

**Expected behavior**
The URL is properly parsed, the "return_to" query parameter is added and then the URL is properly serialized, e.g. it should be "http://myauthserver.mydomain.home:9000/login/to/reports?tenantId=abc&return_to=/" instead.

**Information about your Metabase Installation:**

- Safari 13.1.1
- OS X 10.15.5
- Your databases: none configured
- Metabase version: 1.36.3
- Metabase hosting environment: jar-file
- Metabase internal database: H2

**Severity**
somewhat blocking, although another way to pass the argument can be used (path).

**Comment by flamber** [comment]
Hi @ngrigoriev Please use the support email for Enterprise Edition specific problems, so it's easier for us to track.
