### ISSUE TITLE
Is it possible to migrate database from H2 to a Mariadb with SSL?

### ISSUE THREAD

**Issue by tiago-as** [metabase/metabase#13071]
Hi,
I was trying to migrate the H2 default Metabase database to a Mariadb that only accepts SSL connections. I'm wanted to use this database because I already have infrastructure puppet code that easily installs and configures the server with users.

Is there a way to tell the Metabase to use SSL connection and to point to the certificate?
If there is not, I'll use another database, but I was wondering if its possible.

Thanks in advance to any feedback on this.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
