### ISSUE TITLE
Custom Expression with `OR`/`AND` in Segment/Metrics filtered is hidden

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13070]
**Describe the bug**
When creating a Custom Expression in Segment/Metric filter, which contains `AND`/`OR`, then the filter text is hidden and it's not possible to edit that expression.

**To Reproduce** (requires 0.35.4 until #13069 is fixed)
1. Go to Admin > Data Model > Segment/Metric > Create new or edit existing
2. Add Custom Expression to Filtered by: `[ID] > 0 OR [ID] < 9876543210`:
![image](https://user-images.githubusercontent.com/1447303/89396907-7247a280-d70f-11ea-8121-5ee498159ffd.png)
3. Click Done - then the filter text is not shown and it's not possible to edit it, since the `X` will remove it:
![image](https://user-images.githubusercontent.com/1447303/89397118-b9359800-d70f-11ea-901f-b7d0ebf5a42f.png)

**Information about your Metabase Installation:**
Metabase 0.35.4 and 0.36.3

**Additional context**
Related to #3217

**Comment by nemanjaglumac** [comment]
@flamber - in the latest master, I can see "Custom Expression", but I cannot save it. It gives me: `Redundant input, expecting EOF but found  >`

![image](https://user-images.githubusercontent.com/31325167/96770304-9185d000-13e0-11eb-9b2d-871c3f587278.png)

**Comment by flamber** [comment]
@nemanjaglumac Think you're using Custom Expression on "View" instead of "Filtered by"

**Comment by nemanjaglumac** [comment]
OMG, you're right. I was so tired that I totally misread the steps! 😵
