### ISSUE TITLE
Account settings language not used after login - requires browser refresh to fully translate UI

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#13082]
**Describe the bug**
After setting up the language in "Account settings", if you log out and log in back again Metabase remembers your language but shows everything in English (except for the word "table", weirdly enough 👀).

Workaround is to refresh the page and then everything is translated again.

**Logs**
When redirected to the login page, the moment app refreshes into English, this error shows up:
`app-main.bundle.js?d4167a17e88b8bf103b8:5 GET http://localhost:13981/api/user/current 401 (Unauthorized)`

**To Reproduce**
1. Go to "Account settings" (gear icon > Account settings)
2. Choose language other than English
3. Click "Update" button
4. Observe that the interface updated and everything is now translated
5. Click on "gear" icon ("Settings")
6. Choose the last/bottom option ("Sign out")
7. You should be redirected to the login page `/auth/login?redirect=%2F`
8. Observe that after a second or so, the page updates and the translations are gone (it is shown in English again)
9. Log in
10. Everything is shown in English, except the translation in x-rays for the word "table"
11. Go to "Account settings" again and you'll see that your language is still selected
12. Refresh the page and translations for your chosen language are back

**Expected behavior**
Metabase should persist/remember user locale settings across sessions.

**Screenshots**
https://share.getcloudapp.com/kpubdEy6 (video recording)

**Information about your Metabase Installation:**
This happens on local dev (v0.37.0-snapshot), Docker latest (v0.36.3) and Mac app (v0.36.0).

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: any browser
- Your operating system: OS X 10.15.6
- Your databases: N/A
- Metabase version: multiple (see above)
- Metabase hosting environment: multiple (see above)
- Metabase internal database: H2 (default)

**Severity**
Since there is a fairly simple workaround, it's not severe at all, but I can imagine how it can be annoying and/or confusing for users that are not using English as their chosen language.

**Additional context**
Originally documented in #13063

**Comment by karlseguin** [comment]
> Since there is a fairly simple workaround, it's not severe at all

Imagine if every time you logged into Gmail, you got a Russian interface and had to reload it to get English. 

I think it's pretty severe if you aren't techie or don't speak English. It's non-intuitive and it makes any non-English usage feel like a 2nd class citizen (despite the excellent quality of the translations)
