### ISSUE TITLE
Field filter break BigQuery queries

### ISSUE THREAD

**Issue by huyamanotes** [metabase/metabase#13089]
**Describe the bug**
While writing custom-query question. Choosing FIeld filter and map to column renders query wrongly. 

**Screenshots**
Original questions on Metabase
![image](https://user-images.githubusercontent.com/69457450/89768939-8718a180-db26-11ea-9d24-c5aacaf83d2d.png)

Rendered query on BigQuery:
![image](https://user-images.githubusercontent.com/69457450/89769126-d78fff00-db26-11ea-943e-ea3393f867cd.png)

After the WHERE clause, the location of the filter was also rendered (``huy_test.Marketing_dashboard`.`app_id` IN (?) ) and it failed to catch the selected value in the IN () clause

**To Reproduce**
1. Add a custom query question
2. Add a variable with Field Filter type
3. Query a BigQuery database

**Expected behavior**
Filter catch selected variables and render into BigQuery correct syntax

**Information about your Metabase Installation:**
![image](https://user-images.githubusercontent.com/69457450/89768360-b8dd3880-db25-11ea-8dbf-b9a5c60cbe0a.png)

{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-31",
      "tag": "v1.36.2",
      "branch": "enterprise-release-1.36.x",
      "hash": "1c7403c"
    },
    "settings": {
      "report-timezone": "Asia/Bangkok"
    }
  }
}

**Severity**
Blocking users achieving desired behavior on dashboard, delaying Metabase's launch in my company

**Comment by flamber** [comment]
Hi @huyamanotes 
Please use the support email, when using the Enterprise Edition.
Make sure to wrap your FROM-clause in backticks: `` FROM `huy_test.Marketing_dashboard` ``
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type
