### ISSUE TITLE
Multiple metrics with count distinct with MongoDB returns the same result

### ISSUE THREAD

**Issue by manishrc** [metabase/metabase#13097]
### Describe the bug
Specifying multiple "metrics" using "Number of distinct values of ..." does not work with MongoDB and reports _incorrect_ results. This works as expected on Postgres, RedShift.

#### Query: 
Summary [ Distinct values of first_name, Distinct values of last_name ]

#### Postgres

**Data:**
| id | first_name | last_name |
|:--|:--|:--|
| 1 | Jon | Doe |
| 2 | Jon | Snow |
| 3 | Jane | Smith |

**Result:**
| Distinct values of first_name | Distinct values of last_name |
|:--|:--|
| 2 | 3 |

#### MongoDB

**Data:**

```json
[
  {
    "_id": 1,
    "first_name": "Jon",
    "last_name": "Doe"
  },
  {
    "_id": 2,
    "first_name": "Jon",
    "last_name": "Snow"
  },
  {
    "_id": 3,
    "first_name": "Jane",
    "last_name": "Smith"
  }
]
```

**Result:**
| Distinct values of first_name | Distinct values of last_name |
|:--|:--|
| 2 | 2 |

Reversing the query order to:
Summary [ Distinct values of first_name, Distinct values of last_name ]

...results in:
| Distinct values of last_name | Distinct values of first_name |
|:--|:--|
| 3 | 3 |

**Expected behavior**
Expected the results to match the result for both postgres and mongodb.

**Information about your Metabase Installation:**

- version: 0.35.3 (Also on 0.36.3)
- java.vm.version: 11.0.5+10
- os.name: Linux
- jdbc-driver: PostgreSQL JDBC Driver (42.2.8)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

- Requiring us to double-check all metrics that use MongoDB
- We're having to write custom aggregation queries, requiring dev-time and no way to self-service

**Comment by flamber** [comment]
Reproduced on stats ~0.36.3

| Distinct values of City | Distinct values of State |
|-------------------------|--------------------------|
| 16,584 | 16,584 _(should be 51)_ |
```
[{"$group":{"_id":null,"count":{"$addToSet":"$city"},"count_2":{"$addToSet":"$state"}}},{"$sort":{"_id":1}},{"$project":{"_id":false,"count":{"$size":"$count"},"count_2":{"$size":"$count"}}}]
```
Looks like `"count_2":{"$size":"$count"}` in this example should have been `"count_2":{"$size":"$count_2"}`

**Comment by nemanjaglumac** [comment]
@camsaul - FYI this issue is now reproduced in Cypress. Tagging you as an assignee.
