### ISSUE TITLE
Stacked bar - show data values for each bar within a stack

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13096]
**Is your feature request related to a problem? Please describe.**
Since 0.36.0 it is currently possible to show values on data points, and when using a stacked bar, it can display the sum of the stack, but it's not possible to display the individual bar values in the stack:
![image](https://user-images.githubusercontent.com/1447303/89893089-04501f00-dbd8-11ea-95bd-d81e3329b641.png)

**Describe the solution you'd like**
Being able to display data values for the individual bars within a stack:
![image](https://user-images.githubusercontent.com/1447303/89893244-4a0ce780-dbd8-11ea-81ee-9265d7643a7b.png)

**Describe alternatives you've considered**
Not stacking bars, but that's not always an option if there's a lot of data.

**Additional context**
Related to #12977

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by dmitryungurean** [comment]
Very critical feature that slows down adoption of Metabase among business users:( Now they have to send data to excel and drow their stacked charts with labels there.

**Comment by GarretOConnell** [comment]
Agree this feature is a basic among BI tools.

**Comment by meyerovb** [comment]
+1

**Comment by flanwan** [comment]
I support this

I can imagine, that on small bars in the stacks it is not possible to display a value. But a mouse-over tooltip might solve this.

**Comment by FarisSquared** [comment]
+1

**Comment by PadlarGoingFar** [comment]
Please add this feature. Its surely a simple fix? whats the point in having a stacked bar if it only shows the summed value. defeats the purpose of it.
