### ISSUE TITLE
Data point values uses formatting Style of first serie on all series

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13095]
**Describe the bug**
When displaying values on data points for multiple series, then formatting style of the first series is applied to all series.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Summarize by "Sum of Total" and Custom Expression `Average([Quantity]) / 10` as "AvgPct" - grouped by CreatedAt:Year
![image](https://user-images.githubusercontent.com/1447303/89890551-d79a0880-dbd3-11ea-8f62-4971d9c2035d.png)
3. Visualization Settings > Display > Enable "Show values on data points"
4. (this step isn't required to reproduce, but just makes it even more clear) visualization Settings > Data > "AvgPct" :gear: > Style=Percentage
5. Hover one of the data points of AvgPct, notice the tooltip and Y-axis are correct, but the display value is incorrect formatting:
![image](https://user-images.githubusercontent.com/1447303/89890495-c4873880-dbd3-11ea-874c-722113ede88d.png)

**Expected behavior**
It should apply the style for each series independently - and special style formatting should also be applied.

**Information about your Metabase Installation:**
Metabase 1.36.3 and `master`

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by wfjsw** [comment]
Speaking of value gone 0 while one small y-axis lives together with 2 large ones, here's the offending code:

https://github.com/metabase/metabase/blob/9d4b1200222899e00ffcb7ba7ed6e18f4eb423fa/frontend/src/metabase/visualizations/lib/apply_axis.js#L430

I went straight removing it in my case. Not sure if this is the universal fix.

And the styling issue:

https://github.com/metabase/metabase/blob/9d4b1200222899e00ffcb7ba7ed6e18f4eb423fa/frontend/src/metabase/visualizations/lib/apply_axis.js#L427

**Comment by MarcGJA** [comment]
Love the show datapoints feature, not so thrilled with this particular bug though.
