### ISSUE TITLE
Summarizing by Distinct datetime column always sets granularity to Month

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13098]
**Describe the bug**
It is not possible to change granularity of datetime column used in "Number of distinct values of ..."

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Summarize > Number of distinct values > Created At:
![image](https://user-images.githubusercontent.com/1447303/89938905-77c55100-dc17-11ea-9117-9e01b7e79e52.png)

Possible workaround, depending on how advanced the question is - do a double summarize (aggregated):
![image](https://user-images.githubusercontent.com/1447303/89939705-a68ff700-dc18-11ea-9a25-359f39ee6da0.png)

**Information about your Metabase Installation:**
Metabase 1.36.3

**Additional context**
Related to #10924 - slightly to #11439

**Comment by mlm603** [comment]
note: this issue also impacts joins on timestamp columns - e.g. I have 2 tables with `usage_hour` columns. When I join on that field, the SQL query shows that it is actually truncating the hours to months before joining. Temporary workaround is adding a custom filter where `table1.usage_hour = table2.usage_hour`
