### ISSUE TITLE
Sending email from Metabase via Gmail is blocked by Google

### ISSUE THREAD

**Issue by hugosaias** [metabase/metabase#13104]
Hi,

I tried to set up a pulse sent via email and successfully logged to my google account.
But when sending test emails, I receive an alert from google saying they block your app because this one is not "safe".
![Capture d’écran 2020-08-12 à 18 00 41](https://user-images.githubusercontent.com/44919762/90041239-515fee00-dcc9-11ea-9eba-13c6eef6e323.png
![Capture d’écran 2020-08-12 à 18 16 24](https://user-images.githubusercontent.com/44919762/90041264-5ae95600-dcc9-11ea-8de3-066fdfd6843e.png)
![Capture d’écran 2020-08-12 à 18 24 32](https://user-images.githubusercontent.com/44919762/90041268-5cb31980-dcc9-11ea-81f5-96fd55e1d90d.png)
![Capture d’écran 2020-08-12 à 18 24 39](https://user-images.githubusercontent.com/44919762/90041277-5e7cdd00-dcc9-11ea-810f-004564e9eee5.png)
![Capture d’écran 2020-08-12 à 18 24 51](https://user-images.githubusercontent.com/44919762/90041295-650b5480-dcc9-11ea-9f9f-c5753ea8f315.png)

)

**Comment by flamber** [comment]
Hi @hugosaias 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
If you go to the link provided in the error, then you'll get more information about setting up App Password:
https://support.google.com/mail/?p=BadCredentials
