### ISSUE TITLE
The Metabase bot doesn't react on messages in a Slack channel

### ISSUE THREAD

**Issue by RomantsovArtur** [metabase/metabase#13103]
**Describe the bug**
We experience some strange issues regarding integration between Metabase and Slack. Pulses are working fine, but Metabase doesn't react on messages sent to metabot directly

metabot help
\@MetaBot  show 11

and so on.

**To Reproduce**
1. Invite MetaBot to channel
2. Type message metabot help

**Expected behavior**
Any reply from metabot

**Actual behavior**
No reply from metabot

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.9.0-7-amd64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "exasol",
      "postgres",
      "bigquery",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-10",
      "tag": "v0.35.4",
      "branch": "metabase-revolut",
      "hash": "42a2a2a"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Severity**
That is not mission-critical functionality for us, but will be nice to understand what's going on

**Additional context**
If you can point me how can I debug this issue and attach more useful information - will do.

**Comment by flamber** [comment]
Hi @RomantsovArtur 
Check the log for errors - Admin > Troubleshooting > Logs.
There has been fixes to Slack in 0.36.0 #12678, but there's an issue open #12978, which will likely be fixed in 0.36.4
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
