### ISSUE TITLE
In Pulses and Alerts, Tables with fields formatted as Link or Image display as text

### ISSUE THREAD

**Issue by jrosenthal** [metabase/metabase#13116]
**Describe the bug**
Table formatting allows you to set a column as a link or as an image.  This is really useful for dynamically producing sparkline images, or creating a "click for more detail" field.  Unfortunately, when you have an alert or pulse (or slackbot integration - ie: metabot show <questionid>), the image that is sent of the question doesn't show the field as containing an image, or the Link text, but rather the actual URL value.  Unfortunately, the actual url value for both fields is often quite large and this makes the table illegible if shown as url instead of image or Link text

**Logs**
No relevant logs

**To Reproduce**
1. Create and save a query `select 'other field','https://chart.googleapis.com/chart?cht=ls&chs=200x100&chco=FF0000&chxt=y&chds=a&chd=t:1,2,0,5,6,1,6' as image, 'https://www.google.com/search?source=hp&ei=zJE2X8f3H9eqytMPg8WLqAw&q=a+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+url&oq=a+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+urla+really+really+really+long+url&gs_lcp=CgZwc3ktYWIQAzoICAAQsQMQgwE6BQgAELEDOgsILhCxAxDHARCjAjoICC4QxwEQowI6AggAOgUILhCTAjoFCC4QsQM6AgguOgQIABAKOgQILhAKOgcILhANEJMCOgQIABANOgQILhANOggILhDHARCvAToGCAAQFhAeOggIIRAWEB0QHjoFCCEQoAE6BQghEKsCOgcIIRAKEKABUPICWJo-YPRBaANwAHgDgAGUAogBmCSSAQcxNi4yMC4zmAEAoAEBoAECqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwjHjdzR5prrAhVXlXIEHYPiAsUQ4dUDCAk&uact=5' as link`
2. For each column header in results, click on the header and select formatting.  In the "View as link or image", select image for image, and link for link.  For link, enter link text.  Save.
3. Run the question.  Notice that the results include and image and your link text, no URLs
4. Use a pulse or alert to send the query to you by email or by slack
5. In the resulting email or slack message, not that the image of the question shows both fields as the full URL rather than the image or link text.  Note that the long url would make any other fields illegible.

**Expected behavior**
I expect alerts and pulses to display the image or link text rather than the URLs

**Screenshots**
Metabase question showing expected results:
![image](https://user-images.githubusercontent.com/273666/90254708-2e405600-de11-11ea-8e77-40956d94394c.png)

bad formatting in pulse email:
![image](https://user-images.githubusercontent.com/273666/90254851-6cd61080-de11-11ea-9d15-c246455e3a8e.png)

**Information about your Metabase Installation:**
- Your browser and the version: chrome, firefox, but irrelevant to bug
- Your operating system: Win 10, but irrelevant to bug
- Your databases: MySQL, postgres
- Metabase version: 0.36.3
- Metabase hosting environment: Jar file on ubuntu
- Metabase internal database: Postgres

**Severity**
moderately annoying, not blocking

**Additional context**
Possibly related to https://github.com/metabase/metabase/issues/5493, but that ticket and all comments seems focused on chart types that don't work, rather than functions of the default question/table view that don't work.

**Comment by flamber** [comment]
Hi @jrosenthal 
Pulses currently don't support column formatting, which is why it doesn't work as expected.
Closing in favor of #3735
You might be interested in #12396 too
