### ISSUE TITLE
Embedded dark mode bar graph data points unreadable

### ISSUE THREAD

**Issue by MylesKingsnorth** [metabase/metabase#13125]
**Describe the bug**
When embedding a question which is a bar chart using data points and the dark mode option is checked, the data points become unreadable. This doesn't apply to light mode

**Logs**
Not necessary

**To Reproduce**
1. Create a bar graph with data points enabled
2. Click share and then embed
3. Under style on the right click dark

**Expected behavior**
Data points to be clearly visible

**Screenshots**
![Screen Shot 2020-08-17 at 12 13 16](https://user-images.githubusercontent.com/38158908/90390341-13751800-e083-11ea-991b-be80b978ca1e.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.3.0-1023-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Europe/London"
    }
  }
}
```

**Severity**
This issue is annoying but users can hover over each bar and see the value the data point should show.

**Comment by flamber** [comment]
Only happens on individual questions - on dashboards, it's showing as expected:
![image](https://user-images.githubusercontent.com/1447303/90391137-e88fc180-e08c-11ea-96ac-17fe3425f87b.png)
