### ISSUE TITLE
Add SSL support for Mongo

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1312]
A commenter on HN noted that they couldn't get a SSL connection to MongoDB working.

**Comment by agilliland** [comment]
Just to add on to this, I had someone reach out to me directly about supporting Mongo over ssh, which would be cool as well.

**Comment by g-p-g** [comment]
Supporting mongo over ssh seems much less interesting than support mongo with ssl, which is part of a regular mongo configuration. In fact X over ssh is what you should be looking for as there's nothing restricting that to Mongo, but now you simply cannot connect to Mongo if it's configured with SSL.

**Comment by spsaaibi** [comment]
+1 on supporting SSL for mongo.

**Comment by g-p-g** [comment]
@agilliland just saw the 0.2.1 release and it's confusing to an outsider, but just to be sure that wasn't supposed to fix this issue was it?

**Comment by camsaul** [comment]
@g-p-g the 0.12.1 release fixed some issues with SSL support for SQL databases. We're still working on Mongo SSL support.

**Comment by spsaaibi** [comment]
great @camsaul. Super excited with the product so far. Really want to get it connected to our mongoDB. Give me a shoutout if I can help w/ anything in this regard.

**Comment by okpatil4u** [comment]
+1 with this issue, also please curate few tutorials and case studies. Cudos for your work !!!

**Comment by agilliland** [comment]
This is resolved by #1356

**Comment by g-p-g** [comment]
Thanks, do you have any idea when this will be released?
