### ISSUE TITLE
Table widget sorting in dashboards doesn't appear consistent for string columns with nulls

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#13135]
**Describe the bug**
When manually ordering a table question in a dashboard by a column that has null values the ordering doesn't work as expected. I end up with nulls scattered throughout the column, and the non nulls are not sorted.

**Logs**
Not applicable

**To Reproduce**
1. Create new SQL question as a table (or use an existing one that has nulls in string columns)
```SQL
select 'z' as code1, null as descrip
union all
select 'y' as code1, '3' descrip
union all
select null as code1, null descrip
union all
select null as code1, '4' descrip
union all
select 'b' as code1, '09' descrip
```
2. Add it to a dashboard
3. Click the column header of the "code1" field to sort it
4. Note the nulls in the middle, that's not what I expected, and the letters aren't ordered alphabetically
5. Click it again, again note that the order changes, but it's still not correct, it's just wrong in a different way

Note that this happens with questions built using the query builder too, not just native SQL.
Also, number columns appear to behave as expected.

**Expected behavior**
I expect null records to be ordered consistently, either as highest or lowest sort order values (I don't have a strong preference on which one), strings to be ordered alphabetically.

**Screenshots**
Ordered Ascending
![image](https://user-images.githubusercontent.com/4504437/90570022-0aab5000-e203-11ea-97b1-db7069eef655.png)

Ordered Descending
![image](https://user-images.githubusercontent.com/4504437/90570045-14cd4e80-e203-11ea-8e2d-42291c3bb19f.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.2",
      "date": "2020-07-31",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Severity**
It's a frustration. For logged in users they can drill into the question and order there which seems to work. But for users accessing via a shared dashboard they have no way of predictably ordering by these columns.

**Comment by flamber** [comment]
Fairly sure it's handled here: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/components/TableSimple.jsx#L125-L136
