### ISSUE TITLE
Data Model and Object Details shows non-active columns as Foreign Key targets and can cause query breakage if remapped to foreign key

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13130]
**Describe the bug**
When a column is dropped from a table, then the field in Metabase is set to `active=false`, but the field is still shown in Foreign Key target reference selector, causing confusion and will break queries if "Display values"="Use foreign key".

**To Reproduce**
1. Create two tables:
```
create table test_13075_a (
ID int default null,
fkref int default null
);
insert into test_13075_a (ID, fkref) VALUES (1, 1);
create table test_13075_b (
ID int default null,
old_ID int default null,
fkname text default null
);
insert into test_13075_b (ID, old_ID, fkname) VALUES (1, 1, 'test');
```
2. Admin > Databases > (db) > Sync database schema now
3. Admin > Data Model > (db) > test_13075_b > set `old_ID` field to "Entity Key"
4. Admin > Data Model > (db) > test_13075_a > set `fkref` to "Foreign Key" and reference `test_13075_b.old_ID`, :gear: and change "Display values"="Use foreign key".
5. Drop the column
```
alter table test_13075_b drop column old_ID;
```
6. Admin > Databases > (db) > Sync database schema now
7. Now browsing the table `test_13075_a` will break because of "Display values", and going to Data Model will still shown references to `test_13075_b.old_ID` in the Foreign Key selector.

**Expected behavior**
I guess that any Foreign Key references to a non-active column should be set to `null` at sync, so even if the column was added back, then that wouldn't restore the FK references or "Display values".

**Information about your Metabase Installation:**
Metabase 0.36.0, 0.36.4

**Additional context**
Found during debug of https://github.com/metabase/metabase/issues/13075#issuecomment-670100056

**Comment by franccesco** [comment]
Is there any workaround to fix this issue in the meantime? I have the same issue but haven't been able to fix it
![image](https://user-images.githubusercontent.com/6962824/91204565-830d8780-e6c1-11ea-8584-3b7e8bd3d930.png)

**Comment by flamber** [comment]
@franccesco Manually removing `active=false` rows from `metabase_field` would be my guess. Remember to backup first!

**Comment by franccesco** [comment]
That fixed it for me, thank you!
