### ISSUE TITLE
Can't unset Google account email address domain

### ISSUE THREAD

**Issue by ejain** [metabase/metabase#13137]
**Describe the bug**
Once set, the setting that allows any user from a specific Google domain to sign themselves up can't be unset.

**Logs**

    error updating setting 
    {...}
        default: null
        description: "When set, allow users to sign up on their own if their Google account email address is from this domain."
        env_name: "MB_GOOGLE_AUTH_AUTO_CREATE_ACCOUNTS_DOMAIN"
        is_env_setting: false
        key: "google-auth-auto-create-accounts-domain"
        originalValue: "foo.test"
        placeholder: null
        value: null
    {...}
        ​data: ""
        isCancelled: false
        status: 0

**To Reproduce**
1. Set up "Sign in with Google", including the "@" field
2. Clear the "@" field and hit Save Changes
4. See error in browser (no request is sent to the server)

**Information about your Metabase Installation:**

	{
		"browser-info": {
			"language": "en-US",
			"platform": "Win32",
			"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0",
			"vendor": ""
		},
		"system-info": {
			"file.encoding": "UTF-8",
			"java.runtime.name": "OpenJDK Runtime Environment",
			"java.runtime.version": "11.0.8+10",
			"java.vendor": "AdoptOpenJDK",
			"java.vendor.url": "https://adoptopenjdk.net/",
			"java.version": "11.0.8",
			"java.vm.name": "OpenJDK 64-Bit Server VM",
			"java.vm.version": "11.0.8+10",
			"os.name": "Linux",
			"os.version": "4.9.0-8-amd64",
			"user.language": "en",
			"user.timezone": "US/Pacific"
		},
		"metabase-info": {
			"databases": [
			"postgres",
			"h2"
			],
			"hosting-env": "unknown",
			"application-database": "postgres",
			"application-database-details": {
			"database": {
				"name": "PostgreSQL",
				"version": "9.6.16"
			},
			"jdbc-driver": {
				"name": "PostgreSQL JDBC Driver",
				"version": "42.2.8"
			}
			},
			"run-mode": "prod",
			"version": {
			"date": "2020-08-17",
			"tag": "v0.36.4",
			"branch": "release-0.36.x",
			"hash": "196c1f6"
			},
			"settings": {
			"report-timezone": null
			}
		}
	}

**Comment by flamber** [comment]
Related to #11659

**Comment by ejain** [comment]
Just realized the "client ID" can't be updated, either: Clicking "Save Changes", there is a brief "Changes Saved" message, the page reloads, and the original values are shown again. Same message in the browser console, and also no POST/PUT requests to the server.

**Comment by flamber** [comment]
Looks like there's a race-condition between an Ajax request and form submit, so depending on latency, the Ajax requests might be cancelled before page reloads.
You can manually change the values in the application database table `setting` key `google-auth-client-id` and `google-auth-auto-create-accounts-domain`, and then start Metabase.

**Comment by ejain** [comment]
Looks like the page reload is triggered by the call to `reloadSettings()` after catching and logging the "error updating setting" message; unfortunately the error object doesn't seem very informative.
 https://github.com/metabase/metabase/blob/5e0ded2423f7470b76c3175bafd0a7b51cc373c4/frontend/src/metabase/admin/settings/settings.js#L55

**Comment by ejain** [comment]
Can no longer reproduce this in 0.37.6.
