### ISSUE TITLE
Snowflake works not stable sometimes it cannot show all of the tables

### ISSUE THREAD

**Issue by RileyLien** [metabase/metabase#13131]
Please use the issue chooser, when creating a new issue:

https://github.com/metabase/metabase/issues/new/choose

Sorry to write this question here if someone asked before.

I am new user to work on the snowflake and I face some problems in here.

Why the snowflake cannot show the entire or whole tables sometimes and the time period seems not consist?

For instance, I usually works on snowflake around 10 pm to 1 am (GMT + 8 time zone) but suddenly one day the table only shows six tables for me, which is not the entire tables on the snowflake, sometimes I use it and it shows the complete whole tables for me.

I am very curious why this situation happens again and again, and the outage time is not consist, which means sometimes it happens in the morning and sometimes in the afternoon or evening.

This is very annoyed for my team and me to query the data to do the analysis in the business hour.

Can someone please know this situation and give me more hint to deal with this kinds of problem?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
