### ISSUE TITLE
Auth Returns 400 Bad Request instead of 401 Unauthorized upon wrong credentials submission

### ISSUE THREAD

**Issue by mysticaltech** [metabase/metabase#13140]
**Describe the bug**
Hello, this is a minor bug, but I think important enough to correctly use tools like brute-force mitigating fail2ban. 

When using basic auth, and entering wrong credentials, **Metabase returns a 400 Bad Request, but it should be 401 Unauthorized**. 

**To Reproduce**
1. Tail web-server logs with a tool like `less +F access.log`
2. Enter wrong credentials on the  Metabase login page
3. Watch out for the HTTP status code

**Expected behavior**
Auth literature is clear, bad credentials should return a 401 Unauthorized (and correct ones 200 OK).

**Screenshots**
![Screen Shot 2020-08-19 at 11 37 29 AM](https://user-images.githubusercontent.com/518555/90618719-a7c0b580-e210-11ea-9498-b65a18dcad68.png)

**Severity**
Mild

**Comment by ifaisalalam** [comment]
Working on the fix.
