### ISSUE TITLE
Unable to use Pulse with Slack due to size of slack membership

### ISSUE THREAD

**Issue by johnlgardner** [metabase/metabase#13146]
**Describe the bug**
We are unable to select a Slack channel to send a Pulse to. Potentially due to how many members our slack community has. I love Pulses and want to use them more!! See the pic.

We do have a lot of slack users.

This issue was mentioned here but never fixed apparently:

https://github.com/metabase/metabase/issues/8733

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1 Connect a slack with 1000ish users like ours
2 Click add pulse
3 Turn on Slack pulse
4 Try to select a channel - you will only be able to add general

**Expected behavior**
Be able to select a channel!

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

![image](https://user-images.githubusercontent.com/14797336/90713689-e5a2f580-e273-11ea-8b59-5fbf7d714b33.png)

**Comment by lindsay-stevens** [comment]
Looks the same as #12978 which is marked as fixed in the latest release [v0.36.4](https://github.com/metabase/metabase/releases/tag/v0.36.4). Which metabase version are you using? The bug ticket template not filled out.

**Comment by flamber** [comment]
Closing, please provide all information requested if this is still happening on 0.36.4
