### ISSUE TITLE
Run metabase helm chart on a kubernetes cluster which has pod security policy

### ISSUE THREAD

**Issue by mwxxhdb** [metabase/metabase#13147]
**Is your feature request related to a problem? Please describe.**
If a k8s cluster enabled pod security policy, the Metabase deployment cannot be scaled up since the limitation of the cluster is runAsNonRoot, but Metabase not.

**Describe the solution you'd like**
Able to configure securityContext runAsUser runAsGroup

**Describe alternatives you've considered**
Able to configure serviceAccount for Metabase

**How important is this feature to you?**
Since the implementation of my company's requirement is urgent, I will push a modified helm chart into my company's helm repository, just make it can use a serviceAccount claim the permission to run as root.

**Additional context**
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
https://kubernetes.io/docs/concepts/policy/pod-security-policy/

**Comment by flamber** [comment]
Hi @mwxxhdb 
If this something to do with the Helm template, then please provide a PR in that repo:
https://github.com/helm/charts/tree/master/stable/metabase
But I guess it might be because of #9861

**Comment by Tijmen34** [comment]
Any update on this? I am also unable to implement Metabase on K8s due to Pod Security Policy limitations and would love to see a solution as we use Metabase a lot!

**Comment by flamber** [comment]
@Tijmen34 
There's 1700+ other issues, so unless someone creates a PR for this, then it will take some time until it will be looked at.

**Comment by michael-todorovic** [comment]
Hello,
I'll try to provide a MR soon (question of hours/days, depending on how it goes)

**Comment by camsaul** [comment]
Fixed by #13214
