### ISSUE TITLE
Drill through linking to saved question fails when URL contains column reference

### ISSUE THREAD

**Issue by aaron-kahn** [metabase/metabase#13142]
**Describe the bug**
I have a question in which I try to drill down to another question using the URL feature. When I set the URL to `METABASE_URL/question/2386?received_method=Email` the drill through works as expected. However, when I try to use the column replacement feature e.g. `METABASE_URL/question/2386?received_method={{RECEIVED_METHOD}}` I get an error in the console shown below -- and no redirect happens.

**Logs**

> Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at app-main.bundle.js?8eb0a190cef5b32f7cde:formatted:49907
    at app-main.bundle.js?8eb0a190cef5b32f7cde:formatted:49928
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at o (app-main.bundle.js?8eb0a190cef5b32f7cde:formatted:49888)
    at t.renderLinkURLForClick (app-main.bundle.js?8eb0a190cef5b32f7cde:formatted:49852)
    at E (app-main.bundle.js?8eb0a190cef5b32f7cde:formatted:49832)
    at Object.url (app-main.bundle.js?8eb0a190cef5b32f7cde:formatted:73776)
    at l (app-main.bundle.js?8eb0a190cef5b32f7cde:formatted:49129)
    at t.performDefaultAction (app-main.bundle.js?8eb0a190cef5b32f7cde:formatted:49112)

**To Reproduce**
1. Create two questions, both using native sql. 
2. Question 1 joins two tables and summarizes by count of a field
3. Question 2 displays data from the joined table with a filter on the summarized column.
4. Add drill through to Question 1 and link to question 2 filter 

**Expected behavior**
The drill through link in Question 1 should take me to Question 2 with the filter set to the {{COLUMN}} clicked

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.146-119.123.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.22-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-05",
      "tag": "v1.36.3",
      "branch": "enterprise-release-1.36.x",
      "hash": "8d25295"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Severity**
This feature is something that our customers really want and would provide a lot of value to them. As far as I can tell there isn't any other workaround.

**Comment by flamber** [comment]
Hi @aaron-kahn 
Please use the support email, when using the Enterprise Edition.
In Question1, do you have a column called `RECEIVED_METHOD` ?
For reference: https://www.metabase.com/docs/latest/enterprise-guide/customizing-drill-through.html

**Comment by aaron-kahn** [comment]
Hi @flamber, thank you for your quick reply. Yes, the table has a column called RECEIVED_METHOD and is suggested by the UI when linking:

![image](https://user-images.githubusercontent.com/23195930/90638392-48a47600-e1fb-11ea-9831-0ff3832043b4.png)

The question I am linking to has a variable named received_method:

![image](https://user-images.githubusercontent.com/23195930/90638552-7689ba80-e1fb-11ea-939d-27d901cf9b0f.png)

I have looked at the reference you linked and followed those instructions -- which has led to where I am now.

**Comment by flamber** [comment]
@aaron-kahn I'm not sure why it isn't working.
If you don't use custom drill-through, does it show the regular action menu?
Can you provide more detailed steps-to-reproduce?
Again, I would highly recommend that you use the support email, since Enterprise specific functionality is currently tracked in a different repo.

**Comment by flamber** [comment]
@aaron-kahn I have found a bug, when you try to use Pie or Row visualization. I have created an internal issue.

**Comment by aaron-kahn** [comment]
@flamber Thank you for creating an internal issue. Is there any way for me to track this bug further?

**Comment by flamber** [comment]
@aaron-kahn Contact support, then it will be linked to your ticket, so you'll receive updates, when it's fixed.
