### ISSUE TITLE
Filter "Not Empty" is not working

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#13158]
**Bug**
Filter "Not Empty" is not working. "Not Empty"always returns an empty result set.

Filter "Empty" is OK.

**Expected behavior**
The result set should show the rows with the column filled in. The "Empty" filter is OK, showing rows where the column is empty.

**Example**

![image](https://user-images.githubusercontent.com/55719904/90964134-40b33300-e494-11ea-9e92-a8019ed7df54.png)

Empty Filter (working)

![image](https://user-images.githubusercontent.com/55719904/90964143-588ab700-e494-11ea-9726-e3da3aa2c0f0.png)

Not Empty (Not working)

![image](https://user-images.githubusercontent.com/55719904/90964158-6d674a80-e494-11ea-8413-a4aefc09703d.png)

**Diagnostic information**

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.4",
      "date": "2020-08-17",
      "branch": "release-0.36.x",
      "hash": "196c1f6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Misinterpretation of the dataset.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tatusis** [comment]
Hi @flamber,
Oracle version: 12.1.0.2.0.
ojdbc8 most recent for Oracle 12c.
Column of type varchar2.

**Comment by flamber** [comment]
@tatusis Try ojdbc8.jar version 19.7: https://www.metabase.com/docs/latest/administration-guide/databases/oracle.html

**Comment by flamber** [comment]
Reproduced on Oracle11g express (Docker `wnameless/oracle-xe-11g-r2`) with 19.7 on 0.36.4
Filtering OracleDB > HR > Locations > State Province is "not empty" - should return 17/23, since 6/23 is `null`

**Comment by fnoritomi** [comment]
We noticed the same problem here, after upgrading from 0.35.4 to 0.36.2.

Oracle version: 19.0.0.0.0.
ojdbc8 most recent for Oracle 19c.
