### ISSUE TITLE
Receive error Your question took too long when executing a long query 

### ISSUE THREAD

**Issue by wangying0420** [metabase/metabase#13151]
I’m receiving error Your question took too long when executing a long query over a sparksql connection in Metabase
It is worth mentioning that this problem only appeared after I upgraded from 0.33.3 to 0.36.2
I guess it’s because of shortening the timeout that I have no data in many reports.
What can I do

**Comment by flamber** [comment]
Hi @wangying0420 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Adjust your proxy timeout - read this for more details: #12423
