### ISSUE TITLE
Group names not fully visible on screen

### ISSUE THREAD

**Issue by aastha-agrawal-1** [metabase/metabase#13161]
I am running metabase on my local machine but under the permissions option, I cannot see the group names properly. Can anyone suggest me what to do?

It is visible like this:
![Screenshot from 2020-08-23 16-03-32](https://user-images.githubusercontent.com/31098284/91142078-d4237880-e6cd-11ea-9295-813ce391ffad.png)

**Comment by flamber** [comment]
Hi @aastha-agrawal-1 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
If you are reporting a bug, then you need to include much more information, such as version and browser at minimum.
Could it be some zoom setting either in the browser or the OS? What have you configured?
