### ISSUE TITLE
Metrics editor in Data Model shows "Grouped By" section - even though it's not available

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13167]
**Describe the bug**
Metrics editor in Data Model shows "Grouped By" section - even though it's not available.

**To Reproduce**
1. Admin > Data Model > Metrics > New metric - shows "Grouped By" section in QB as if it's disabled or missing a button
![image](https://user-images.githubusercontent.com/1447303/91221922-be8a6f00-e71e-11ea-8ca4-545c2472cd79.png)

**Information about your Metabase Installation:**
Metabase 0.34 thru 0.36.4

**Additional context**
https://discourse.metabase.com/t/cannot-use-grouped-by-in-metrics/11339

**Comment by nemanjaglumac** [comment]
Legacy metrics will be removed in v51.
