### ISSUE TITLE
Make "Embedding Secret Key" available as environment variable

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13160]
**Describe the solution you'd like**
Allow Admin > Settings > Embedding in other Applications > Embedding Secret Key to be defined via environment variable - `MB_EMBEDDING_SECRET_KEY`

**Describe alternatives you've considered**
Set it via the API request `PUT /api/setting/embedding-secret-key` with data `{"value":"YOUR-64CHAR-LONG-EMBEDDING-SECRET"}` - for reference https://www.metabase.com/docs/latest/api/setting.html#put-apisettingkey
Or via Serialization.

**Additional context**
It's defined as `^:private`
https://github.com/metabase/metabase/blob/5e0ded2423f7470b76c3175bafd0a7b51cc373c4/src/metabase/util/embed.clj#L56-L63

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by robert-mccarter** [comment]
This would be great - it's so much easier to use an environment variable with docker-compose and/or Kubernetes than connect to the API.

**Comment by flamber** [comment]
Fixed by #22800
