### ISSUE TITLE
Heroku Memory quota exceeded (R14 error)

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1317]
We are using way more memory than we should be, possibly due to incorrectly configured JVM.

More info here: https://github.com/metabase/metabase-deploy/issues/1

**Comment by camsaul** [comment]
Pass some command line args to Java to set the max heap size.

For example, we have a max heap size of 2GB set here so we don't hit the 4GB limit on Circle for dev + ci:
https://github.com/metabase/metabase/blob/master/project.clj#L82

**Comment by agilliland** [comment]
Lets start with some profiling data to understand this better before jumping to any conclusions.  As a simple starting point to baseline, there are at least 10 Metabase instances that I know of in production use on AWS Elastic Beanstalk using t2.small instances (https://aws.amazon.com/ec2/instance-types/) which top out at 2GB mem for the whole system and they work quite well.

**Comment by camsaul** [comment]
2GB is a lot more than 512MB lulz

**Comment by agilliland** [comment]
Based on info from this PR https://github.com/metabase/metabase-deploy/pull/5 it looks like this isn't really a problem with the app and more with the way we are launching on Heroku.

We've already switched over to using the JVM buildpack and adding this in should fully resolve this ... https://github.com/metabase/metabase-deploy/pull/7

**Comment by agilliland** [comment]
With updates mentioned above combined with code changes in the application I believe this issue should be resolved.  We can reopen if we get ongoing reports that people are still encountering memory limitations on the latest release.
