### ISSUE TITLE
Change authentication method.

### ISSUE THREAD

**Issue by tiago-as** [metabase/metabase#13171]
Hi,

I need to implement metabase in an enterprise environment with Linux machines and I need to be able add users to database in a central manner. From my understanding, metabase as of this moment hashes passwords and authenticates users using blowfish: https://github.com/metabase/metabase/blob/25cee8dc334781f65104648d3f119e6c6acb7f81/src/metabase/util/password.clj#L64

Is there a simple way to change the algorithm used to perform this authentication or authenticate users with Linux PAM modules?

Thanks in advance for any feedback!

**Comment by flamber** [comment]
Hi @tiago-as Please use the support email, when using the Enterprise Edition.

**Comment by tiago-as** [comment]
@flamber sorry if I didn't make myself clear. I'm not using the enterprise edition. I'm using the community one, I was just explaining that I'm running Metabase in a professional environment, not in a personal use one.

Is there any feedback regarding the authentication?

**Comment by flamber** [comment]
@tiago-as 
You would need to developer a new authentication method to make it auth against PAM. Would probably be easier to LDAP.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
