### ISSUE TITLE
Not all columns of nested question available for Dashboard filter

### ISSUE THREAD

**Issue by ferarnoled** [metabase/metabase#13186]
**Describe the bug**
This is not consistent but either
1) When adding a dashboard filter not all columns of nested question are available
or
2) When adding a dashboard filter none of the columns of nested question are available
Basically this: https://github.com/metabase/metabase/issues/9802

**To Reproduce**
1. Native question > Sample Dataset - SELECT * FROM "ORDERS" - and save as Q1
2. Simple question > Saved Questions > select Q1 - and save as Q2
3. When it asks "Add to dashboard", click yes
4. Q2 is now added to dashboard, click "Add a filter" > "Other Categories"
5. Either no columns show up or only some columns show up. In this last case usually only of one of the tables.

**Expected behavior**
All columns of nested question should be available for the filter.

**Screenshots**
I created two questions in the dashboard one using the query builder and the other using a nested question that gives you the same output so is easy to compare.
In the screenshots you see that the native question has a join but have the same issue even if I don't join to any table.

![dashboard](https://user-images.githubusercontent.com/8064032/91674803-00d0f900-eaef-11ea-9dbb-051fdcf11fd2.png)
![nested question (SQL)](https://user-images.githubusercontent.com/8064032/91674806-02022600-eaef-11ea-80ff-1b2d792c2222.png)
![non nested question](https://user-images.githubusercontent.com/8064032/91674808-02022600-eaef-11ea-9eaf-7a3749546cf7.png)
![question using nested question](https://user-images.githubusercontent.com/8064032/91674809-029abc80-eaef-11ea-8b29-a5ddb860d454.png)
![Annotation 2020-08-30 184127](https://user-images.githubusercontent.com/8064032/91675268-93be6300-eaf0-11ea-9a40-1e41b61aa3fd.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.171-105.231.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-17",
      "tag": "v0.36.4",
      "branch": "release-0.36.x",
      "hash": "196c1f6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
I thought this was fixed as part of https://github.com/metabase/metabase/issues/9802. If this is not a regression what was fixed as part of that ticket?

**Additional Context**
This happened to me on much more complex native queries. In that case the only columns showing up were the boolean fields, not sure if that helps. 
If you need more context please let me know, really would like to have dashboard filters working fully for nested questions.
Thanks

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #5594 and #12985

**Comment by ferarnoled** [comment]
still happening for me

**Comment by 8debug** [comment]
> **Steps to reproduce:**
> 
> 1. Native question > Sample Dataset > `SELECT * FROM PRODUCTS` - save as Q1
> 2. Simple question > Saved Questions > Q1 - save as Q2
> 3. Add Q2 to dashboard, add filter "Other categories" and connect to Q2 - it only shows "TITLE" and "VENDOR" columns as options to link, but where is "CATEGORY" column?
>    ![image](https://user-images.githubusercontent.com/1447303/97079307-19dbbf00-15f3-11eb-9f60-838fc9089ac2.png)
> 
> Related to #5594 and #12985

not `SELECT * FROM PRODUCTS`, is `SELECT * FROM ORDERS`

**Comment by jcorrea-tkww** [comment]
I'm having the same issue and I got it reproduced using sample database as well 
The only workaround I found is to duplicate the "master" query based card, aggregate on top for instance using the original query as subquery and then use this new question in the dashboard.  We used snippets as much as possible to avoid maintenance of same query across several cards, but this is only a workaround and I agree that the problem exists and it's expected to have a nested query working in a dashboard for filtering as any non-nested card.
