### ISSUE TITLE
Cannot toggle off 'Automatically run queries when doing simple filtering and summarizing' 

### ISSUE THREAD

**Issue by alextanghk** [metabase/metabase#13187]
**Describe the bug**
'Automatically run queries when doing simple filtering and summarizing' will change back to toggle on after toggle off and save. (Admin -> Databases)

**Logs**
`[120be4ed-6ce4-4854-932e-364ff387dfaf] 2020-08-31T17:08:05+08:00 DEBUG metabase.middleware.log GET /api/database 200 40.3 ms (3 DB calls) App DB connections: 2/13 Jetty threads: 12/50 (0 idle, 0 queued) (53 total active threads) Queries in flight: 0 (0 queued)
[120be4ed-6ce4-4854-932e-364ff387dfaf] 2020-08-31T17:08:05+08:00 DEBUG metabase.middleware.log GET /api/database/98 200 55.8 ms (3 DB calls) App DB connections: 3/13 Jetty threads: 11/50 (0 idle, 0 queued) (57 total active threads) Queries in flight: 0 (0 queued)`

**To Reproduce**
1. Go to 'Admin -> Databases -> Any record'
2. toggle on 'Automatically run queries when doing simple filtering and summarizing'
3. Save
4. Refresh
5. 'Automatically run queries when doing simple filtering and summarizing' become on again

**Expected behavior**
'Automatically run queries when doing simple filtering and summarizing' should be off after save.

**Information about your Metabase Installation:**

- Your browser and the version: Brave 1.12.114
- Your operating system: Windows 10
- Your databases: MsSQL
- Metabase version: 0.36.4
- Metabase hosting environment: Azure DS1V2 Windows Server
- Metabase internal database: MySQL

**Comment by flamber** [comment]
It's actually saving the value correctly, but not displaying it correctly, so if you save with the setting disabled, then it will work as expected in the editor, but it makes it difficult to know if the setting is enabled or disabled.

**Comment by nemanjaglumac** [comment]
Fixed in https://github.com/metabase/metabase/pull/14121 .
