### ISSUE TITLE
Table in multi-schema databsae not selected in Data Model when browsing directly

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#13192]
**Describe the bug**
When navigating to a table in the data model for a database that has multiple schemas, the table is highlighted on the left-hand side (see figure 1). However, when direct browsing to that same table you are presented with the list of schemas (see figure 2).

I would expect for the schema and table to be selected in the left-hand navbar. This is also a regression in v0.36, this worked in v0.35.4.

**Logs**
n/a

**To Reproduce**
1. Go to the Data Model section of Admin in our stats instance
2. Select the "CI Redshift" instance
3. Select the "public" schema
4. Select the "Bird Count" table
5. Note that the table is selected on the left-hand side
6. Reload the browser
7. Note that the list of schemas shows up in the left-hand side

**Expected behavior**
Except to have the table selected on the left-hand side

**Screenshots**
![figure 1](https://user-images.githubusercontent.com/1512/91769261-e6049000-eb93-11ea-95f3-1e1a902ff5f7.png)
![figure 2](https://user-images.githubusercontent.com/1512/91769322-0c2a3000-eb94-11ea-8171-df0d42fd6e3e.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.186-110.268.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "druid",
      "postgres",
      "bigquery",
      "redshift",
      "googleanalytics",
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-29",
      "tag": "v0.37.0-snapshot",
      "branch": "master",
      "hash": "cb7ad5b"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
Annoying, but a regression. 

**Additional context**

**Comment by flamber** [comment]
Also, not a regression, but going into column details :gear: and going back always shows table overview scrolled to top, which is annoying, when editing multiple columns in a table with a lot of columns.
