### ISSUE TITLE
Workplace harassment placeholder text

### ISSUE THREAD

**Issue by JSheadache** [metabase/metabase#13196]
Please delete or replace values of placeholder email (youlooknicetoday@email.com) and password (Shh..) The current values could be construed as workplace harassment and will not be well received by Enterprise customers. 

frontend/src/metabase/auth/components/LdapAndEmailForm.jsx
frontend/src/metabase/entities/users/forms.js
frontend/src/metabase/admin/settings/selectors.js

**Comment by andreychirikba** [comment]
And "Doing science" may be seen as an insult by those who've never done any science.

**Comment by WiNloSt** [comment]
@alxnddr Can this be closed since https://github.com/metabase/metabase/pull/23318 is already merged?
