### ISSUE TITLE
UI has broken when trying to select a column of the second join configuration in the custom question

### ISSUE THREAD

**Issue by raphaelcartaxo** [metabase/metabase#13191]
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to 'Custom Question'
2. Click on 'Columns of the second join configuration'
3. Scroll down to ''

**Expected behavior**

we should scroll up or we should see the top of the columns list.

**Screenshots**

![20200831_metabase](https://user-images.githubusercontent.com/51095960/91752829-519f2b00-eb9d-11ea-80f4-1535be5ee8e1.jpg)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.104+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "presto"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-06-04",
      "tag": "v1.35.4.1",
      "branch": "enterprise-release-1.35.x",
      "hash": "3f408c2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Hi @raphaelcartaxo 
There's a fix for that in 1.36.0 - latest release is 1.36.4.
Please use support email, when using the Enterprise Edition.
Also, you should never use H2 as application database in production:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
