### ISSUE TITLE
Support for more chart colors in white label color palette 

### ISSUE THREAD

**Issue by jgavil** [metabase/metabase#13201]
**Is your feature request related to a problem? Please describe.**
In the current white label settings, there is support for up to 5 "additional chart colors": https://reporting.rhapsody.vet/admin/settings/whitelabel.  This is fairly effective most of the time, however, for many pie charts or stacked bar charts in particular.... if there's any kind of fragmentation, you quickly run out of color settings and you end up with the Metabase default colors taking over.

Here is an example: 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/16961227/91974874-7f46ba00-ecec-11ea-8265-8cccaa4293a0.png">

**Describe the solution you'd like**
The main solution would be simply add more additional color options under the whitelabel settings, enabling perhaps up to 15 colors (versus the 5 today) would really cover the 95% of cases.   

I'm specifically referring to these settings:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/16961227/91975269-21ff3880-eced-11ea-9dbd-87f18b883848.png">

**Describe alternatives you've considered**
Improve some of the default metabase colors.  Certainly it's hard to find colors with enough contrast, but some of the green / brown / pink shades that you get, could be improved for all metabase users.  

Of course, we could also go through each chart and manually set the color options in each chart, but that is not scalable.  This currently impacts dozens of charts. 

**How important is this feature to you?**
This does have a big impact on the look and feel of our whitelabeled dashboards.  It would significantly help our branding and white-labeling of Metabase, to be able to clean this up.

**Comment by flamber** [comment]
Hi @jgavil 
Please use support email, when using the Enterprise Edition. I've made an internal node on our internal request (470).
