### ISSUE TITLE
Add Dockerfile for building Metabase

### ISSUE THREAD

**Issue by sammcj** [metabase/metabase#1320]
I can't find the Dockerfile anywhere - where is it?

**Comment by agilliland** [comment]
It's right here ... https://github.com/metabase/metabase/blob/master/bin/release/dockerhub/Dockerfile

**Comment by tlrobinson** [comment]
We should also consider having a Dockerfile in the root of the project that can be used to build (and run?) the jar.

**Comment by agilliland** [comment]
I agree, that's on my list of things to get to some time in the next couple weeks.

**Comment by agilliland** [comment]
this is done as of #1360
