### ISSUE TITLE
Excel export requires AWT

### ISSUE THREAD

**Issue by antoinep92** [metabase/metabase#13210]
**Describe the bug**
I'm using headless OpenJDK 14. According to #12433, Metabase should run fine except for pulses.
On 0.34 everything is indeed ok for me. On 0.35 metabase doesn't start (#12223). On latest 0.36 release, metabase starts again, but export from table views to XLSX is broken, due du missing AWT classes.

If this is the intended behavior, the doc / java requirements should be updated accordingly (and maybe there are other broken features that I missed when running headless). Or - hopefully - maybe there is a way to make excel work again under headless java ? Non-headless java increases image sizes, build time, dependencies (both compile-time and runtime), and security attack surface, making it undesirable for some use-cases.

**Logs**
Error log: `Fontconfig error: Cannot load default config file`
Downloaded file:

    {"via":[{"type":"java.lang.InternalError","message":"java.lang.reflect.InvocationTargetException","at":["sun.font.FontManagerFactory$1","run",null,-1]},{"type":"java.lang.reflect.InvocationTargetException","at":["jdk.internal.reflect.NativeConstructorAccessorImpl","newInstance0",null,-2]},{"type":"java.lang.NullPointerException","at":["sun.awt.FontConfiguration","getVersion",null,-1]}],"trace":[["sun.awt.FontConfiguration","getVersion",null,-1],["sun.awt.FontConfiguration","readFontConfigFile",null,-1],["sun.awt.FontConfiguration","init",null,-1],["sun.awt.X11FontManager","createFontConfiguration",null,-1],["sun.font.SunFontManager$2","run",null,-1],["java.security.AccessController","doPrivileged",null,-1],["sun.font.SunFontManager","<init>",null,-1],["sun.awt.FcFontManager","<init>",null,-1],["sun.awt.X11FontManager","<init>",null,-1],["jdk.internal.reflect.NativeConstructorAccessorImpl","newInstance0",null,-2],["jdk.internal.reflect.NativeConstructorAccessorImpl","newInstance",null,-1],["jdk.internal.reflect.DelegatingConstructorAccessorImpl","newInstance",null,-1],["java.lang.reflect.Constructor","newInstanceWithCaller",null,-1],["java.lang.reflect.Constructor","newInstance",null,-1],["sun.font.FontManagerFactory$1","run",null,-1],["java.security.AccessController","doPrivileged",null,-1],["sun.font.FontManagerFactory","getInstance",null,-1],["java.awt.Font","getFont2D",null,-1],["java.awt.Font","canDisplayUpTo",null,-1],["java.awt.font.TextLayout","singleFont",null,-1],["java.awt.font.TextLayout","<init>",null,-1],["org.apache.poi.ss.util.SheetUtil","getDefaultCharWidth","SheetUtil.java",275],["org.apache.poi.xssf.streaming.AutoSizeColumnTracker","<init>","AutoSizeColumnTracker.java",117],["org.apache.poi.xssf.streaming.SXSSFSheet","<init>","SXSSFSheet.java",82],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createAndRegisterSXSSFSheet","SXSSFWorkbook.java",658],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createSheet","SXSSFWorkbook.java",679],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createSheet","SXSSFWorkbook.java",90],["dk.ative.docjure.spreadsheet$add_sheet_BANG_","invokeStatic","spreadsheet.clj",283],["dk.ative.docjure.spreadsheet$add_sheet_BANG_","invoke","spreadsheet.clj",279],["metabase.query_processor.streaming.xlsx$fn__35371","invokeStatic","xlsx.clj",39],["metabase.query_processor.streaming.xlsx$fn__35371","invoke","xlsx.clj",36],["clojure.lang.MultiFn","invoke","MultiFn.java",234],["metabase.query_processor.streaming$streaming_context","invokeStatic","streaming.clj",53],["metabase.query_processor.streaming$streaming_context","invoke","streaming.clj",46],["metabase.query_processor.streaming$streaming_context","invokeStatic","streaming.clj",58],["metabase.query_processor.streaming$streaming_context","invoke","streaming.clj",46],["metabase.query_processor.streaming$streaming_response_STAR_$fn__35435$fn__35436","invoke","streaming.clj",73],["metabase.query_processor.streaming$streaming_response_STAR_$fn__35435","invoke","streaming.clj",72],["metabase.async.streaming_response$do_f_STAR_","invokeStatic","streaming_response.clj",66],["metabase.async.streaming_response$do_f_STAR_","invoke","streaming_response.clj",64],["metabase.async.streaming_response$do_f_async$fn__23249","invoke","streaming_response.clj",85],["clojure.lang.AFn","applyToHelper","AFn.java",152],["clojure.lang.AFn","applyTo","AFn.java",144],["clojure.core$apply","invokeStatic","core.clj",665],["clojure.core$with_bindings_STAR_","invokeStatic","core.clj",1973],["clojure.core$with_bindings_STAR_","doInvoke","core.clj",1973],["clojure.lang.RestFn","invoke","RestFn.java",425],["clojure.lang.AFn","applyToHelper","AFn.java",156],["clojure.lang.RestFn","applyTo","RestFn.java",132],["clojure.core$apply","invokeStatic","core.clj",669],["clojure.core$bound_fn_STAR_$fn__5749","doInvoke","core.clj",2003],["clojure.lang.RestFn","invoke","RestFn.java",397],["clojure.lang.AFn","run","AFn.java",22],["java.util.concurrent.Executors$RunnableAdapter","call",null,-1],["java.util.concurrent.FutureTask","run",null,-1],["java.util.concurrent.ThreadPoolExecutor","runWorker",null,-1],["java.util.concurrent.ThreadPoolExecutor$Worker","run",null,-1],["java.lang.Thread","run",null,-1]],"_status":500}

**To Reproduce**
1. Create a table view
2. Click 'download full results' > '.XLSX'
3. Instead of an excel file, the downloaded file contains a json with java errors

**Expected behavior**
Ideally, the excel file should be exported, even in headless.
If not possible, the fact that this feature doesn't work in headless should be documented, and maybe the error handling could be more user-friendly (like show an error message in the webapp instead of downloaded a json with an xlsx extension, that will appear as a broken file for most users)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "14.0.2-internal+0-adhoc.antoine.cache-14.0.2-ga",
    "java.vendor": "N/A",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "14.0.2-internal",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "14.0.2-internal+0-adhoc.antoine.cache-14.0.2-ga",
    "os.name": "Linux",
    "os.version": "5.8.5-arch1-1",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "sqlite"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-17",
      "tag": "v0.36.4",
      "branch": "release-0.36.x",
      "hash": "196c1f6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Blocks upgrades from 0.34

**Comment by flamber** [comment]
The documentation was updated, but didn't make it into 0.36, only on the master (upcoming 0.37):
https://github.com/metabase/metabase/blob/master/docs/operations-guide/java-versions.md
