### ISSUE TITLE
Blank page on public links

### ISSUE THREAD

**Issue by medGoFR** [metabase/metabase#13216]
**Describe the bug**
The bug occurs when I use a public link generated by Metabase when I authorize to sharing of the results. When I enter the link generated on my browser, I can only see a blank window. I can't see the result or any visual.

**Logs**

**To Reproduce**
1. Create a metabase question & run it
2. Click on the Sharing & Embedding button
3. Share
4. Copy the public link
5. Paste it in the browser
6. The page is white and empty

**Expected behavior**
We should see the query results as well as the names, the buttons, etc

**Screenshots**
<img width="1440" alt="Capture d’écran 2020-09-07 à 15 59 29" src="https://user-images.githubusercontent.com/62095920/92395193-3c894580-f123-11ea-8c63-393c5aeb5ac2.png">
<img width="1440" alt="Capture d’écran 2020-09-07 à 15 59 43" src="https://user-images.githubusercontent.com/62095920/92395201-3eeb9f80-f123-11ea-9323-f50cc3cd04c7.png">

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.186-146.268.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "sqlserver"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-17",
      "tag": "v0.36.4",
      "branch": "release-0.36.x",
      "hash": "196c1f6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

- Your browser and the version: Safari Version 13.0.2
- Your operating system: macOS Catalina Version 10.15
- Your databases: Postgres
- Metabase version: 0.36.4
- Metabase hosting environment: ?
- Metabase internal database: Postgres

**Severity**
It is very annoying because our external interlocutors are not autonomous anymore, they need us to get their data and we don't have the ability to compensate...

**Additional context**

**Comment by flamber** [comment]
Hi @medGoFR 
I'm 99.9% sure that it's caused by a proxy: https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html
If you check the browser developer console, then you'll see some errors and might help diagnosing the problem.

**Comment by julesjulesjulesjules** [comment]
Hello @flamber 
Thank you very much for your help. I still can't manage to understand the errors my console is returning. Do you have any clue why is that happening (screenshot attached) ?

<img width="1341" alt="Capture d’écran 2020-09-08 à 11 47 32" src="https://user-images.githubusercontent.com/37187420/92709999-b0ac2f00-f357-11ea-90f0-397e0b79e9dd.png">

Thanks again !

**Comment by flamber** [comment]
@julesjulesjulesjules You are using Cloudflare and probably have something like RocketLoader enabled - disable that.
And you should update the Site URL in Metabase > Admin > Settings > General.

**Comment by julesjulesjulesjules** [comment]
@flamber very clear.
Thank you for your help, much appreciated
