### ISSUE TITLE
LDAP Group Check with non-default membership keys

### ISSUE THREAD

**Issue by emingure** [metabase/metabase#13215]
**Is your feature request related to a problem? Please describe.**
To use LDAP group sync feature, your LDAP system needs to store members of a group with the key 'member', but as my case LDAP system gives members with the key 'uniqueMember'. Hence I cannot use group sync feature.

**Describe the solution you'd like**
In the code below, member keyword can be parametric and defined by settings UI page.
https://github.com/metabase/metabase/blob/f03f3dfec082460510fef22c00c11cb3e035260a/src/metabase/integrations/ldap.clj#L131-L138

And also in the code below, memberof keyword can be parametric and defined by settings UI page.
https://github.com/metabase/metabase/blob/f03f3dfec082460510fef22c00c11cb3e035260a/src/metabase/integrations/ldap.clj#L186-L205

**How important is this feature to you?**
It is very important for big companies to use ldap groups for authorization.

**Comment by flamber** [comment]
Sounds like that is what PR #7098 was trying to fix. Probably related to #11697

**Comment by emingure** [comment]
> Sounds like that is what PR #7098 was trying to fix. Probably related to #11697

It looks like this PR only solves a specific problem. Making those LDAP filters definable by UI makes it fit for all parties, If possible
