### ISSUE TITLE
Run the jar file on a different port

### ISSUE THREAD

**Issue by jgoux** [metabase/metabase#1321]
Hello,
is it possible to set an environment variable to run the jar file on a different port than `3000` ?

**Comment by agilliland** [comment]
yes.  if you set the environment variable `MB_JETTY_PORT` you can launch the app on any port you choose.

**Comment by jgoux** [comment]
@agilliland Awesome, is it anywhere in the doc ?

**Comment by agilliland** [comment]
nope.  needs to be added.

**Comment by jgoux** [comment]
Done. https://github.com/metabase/metabase/pull/1323 :+1:

**Comment by gourav999** [comment]
java -Dserver.port=8888 -jar myApplication.jar
