### ISSUE TITLE
Custom Field `concat` only shows filter options as numeric

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#13217]
I created a string custom expression but I can only filter on number filter for this custom expression

<img width="989" alt="Capture d’écran 2020-09-07 à 18 43 26" src="https://user-images.githubusercontent.com/1840026/92407267-5c783380-f13a-11ea-8673-3398b04d9f70.png">
<img width="945" alt="Capture d’écran 2020-09-07 à 18 50 31" src="https://user-images.githubusercontent.com/1840026/92407496-05269300-f13b-11ea-8d2e-b84bb4a05669.png">

`{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Linux",
    "os.version": "5.8.1+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-31",
      "tag": "v0.36.2",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Workaround: It is probably possible to use a Custom Expression filter to get the filter options needed.
Very related to #13122.

**Comment by lindsay-stevens** [comment]
The workaround seems to kind of work - it is possible to create a custom expression filter and use that to filter for equality to a text value. But after the filter is added, when modifying the filter, it does not accept any other additional values. For example the expression was `custom_col1 = 'value1'` it won't convert that to something like `custom_col1 = 'value1' or custom_col1 = 'value2'`, instead that modified filter needs to be specified in a new custom expression filter. I think this sort of thing affects filters for all of the custom column text functions. I was testing on v.0.35.4.

**Comment by ariya** [comment]
This should be fixed with the work in #15952.
