### ISSUE TITLE
CSS is included twice

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#13219]
@kdoh spotted that we're including styles twice:

![image](https://user-images.githubusercontent.com/691495/92507741-6ef37b00-f1d5-11ea-92b8-dcf85b10e6fe.png)

This issue is happening in production builds and seems to include the same styles in both "app-main" and "styles".

**Comment by iethree** [comment]
Spent some time looking into this. To an unknown extent, certain elements in the application now depend on the double-inclusion of styles.  Most of them are not major: padding, margin, display, etc. But it's hard to determine the surface area.

For a "working" fix that effectively dedupes the styles, but exposes certain elements that rely on duped styles, see https://github.com/metabase/metabase/pull/22165
