### ISSUE TITLE
Make "Friendly Table and Field Names" available as environment variable

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13227]
**Describe the solution you'd like**
Allow Admin > Settings > General > Friendly Table and Field Names to be defined via environment variable - `MB_HUMANIZATION_STRATEGY`

**Describe alternatives you've considered**
Set it via the API with key `humanization-strategy`
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#put-apisettingkey

**Additional context**
Not sure why it's not working, but it's slightly differently formatted compared to other envvars:
https://github.com/metabase/metabase/blob/19957fda6bf1b5e7aad9325b87d9b2fa82f6b599/src/metabase/models/humanization.clj#L111-L118

Related #13160

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by paoliniluis** [comment]
This one already works
