### ISSUE TITLE
JWT Token 400 error when creating a new BigQuery database with service account

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#13228]
First off, thank you all for adding BigQuery service account support! Much appreciated!

**Describe the bug**
I tried creating a new BQ database with a service account just now, and got this error: _400 Bad Request { "error" : "invalid_grant", "error_description" : "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim." }_

Do I maybe have non-default settings somewhere in my Google Cloud project or org that set JWT expiration to 60m, and Metabase is asking for a longer one? https://github.com/metabase/metabase/issues/4634#issuecomment-575210680 seemed related, but the error message is different, and when I looked at the G Suite setting he mentioned in https://admin.google.com/u/1/ac/security/reauth/admin-tools , ours is set to never expire.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/778068/92776017-b7d13e00-f353-11ea-8ae0-68f80ba67412.png">

Thanks in advance...

**Logs**
```
[b443a6cb-5cee-466e-a25a-0e0d50f86867] 2020-09-10T11:13:53-07:00 ERROR metabase.api.database Cannot connect to Database
[b443a6cb-5cee-466e-a25a-0e0d50f86867] 2020-09-10T11:13:53-07:00 ERROR metabase.driver.util Database connection error
[b443a6cb-5cee-466e-a25a-0e0d50f86867] 2020-09-10T11:13:53-07:00 DEBUG metabase.middleware.log POST /api/database 400 267.1 ms (0 DB calls) 
{:valid false,
 :dbname
 "400 Bad Request\n{\n  \"error\" : \"invalid_grant\",\n  \"error_description\" : \"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.\"\n}",
 :message
 "400 Bad Request\n{\n  \"error\" : \"invalid_grant\",\n  \"error_description\" : \"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.\"\n}"}
```

**To Reproduce**
1. Go to 'Admin => Databases
2. Click on Add database
3. Enter BigQuery details and upload a service account JSON key file

**Expected behavior**
No error. 😁 

**Screenshots**

<img width="667" alt="image" src="https://user-images.githubusercontent.com/778068/92775595-6628b380-f353-11ea-8121-e63f22655683.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 80.0
- Your operating system: Mac OS X 10.15.6
- Your databases: BigQuery
- Metabase version: 1.36.3
- Metabase hosting environment: jar file on Ubuntu 18
- Metabase internal database: PostgreSQL 9.6

**Severity**
Right now, just annoying.

**Comment by flamber** [comment]
Hi @snarfed 
What's the time on Ubuntu? Is it off by more than a few minutes? Looking at the log time and when you have posted this, then it seems like your server time has deviated.

**Comment by snarfed** [comment]
@flamber argh, thank you! that was absolutely it. sorry for the trouble!

(might be worth adding that tip to the UI when you see this error message. not important though!)
