### ISSUE TITLE
how to add csv datasource

### ISSUE THREAD

**Issue by Yogashri12** [metabase/metabase#13223]
For help with installation and setup, information on how specific features work, or general questions about Metabase, please use our discussion forum:

https://discourse.metabase.com

The Github issue tracker is intended to collect bug reports and feature requests.
Any issues open for help requests will be closed to keep from clogging up the issue tracker.

Hi,
I am New To metabase.
I just download metabase jar from the official website.--->https://www.metabase.com/start/jar.html

then i was able to access the browser page in the port 3000.during the time of admin account creation i didn't add any database-->i just pressed i'll add my data later.

after that i was able to access home page of metabase.

now i have few csv files in my local machine.but i don't know how to upload csv data into metabase.I couldn't find any option like add datasource in homepage.

can you help me out?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
