### ISSUE TITLE
Revision History shows Revert button when user only has view-only permissions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13229]
**Describe the bug**
Revert button is shown even when the user doesn't have permissions to modify question.

**To Reproduce**
1. Create a question, save as "Q1" to "Our Analytics", make a modification and save again
2. Admin > Permissions > Collections > set "Our Analytics" to view-only
3. Admin > People > create new user "U1"
4. Login as "U1" > Our Analytics > Q1 > click pencil-icon next to question title > View revision history > clicking Revert button will make the button show `Revert failed`:
![image](https://user-images.githubusercontent.com/1447303/92811548-d882ad80-f3be-11ea-87c6-7a4d4e20bff7.png)

**Expected behavior**
Revert button shouldn't be shown, when user doesn't have permissions to modify question.

**Information about your Metabase Installation:**
Metabase 0.36.4

**Comment by mazameli** [comment]
Yikes, this feels higher than a P3 to me. This effectively means that someone without edit access can edit a dashboard, though in a limited way.

**Comment by mazameli** [comment]
Bumped it up to a P2 but could pretty easily be talked into it being a P1.

**Comment by brunobergher** [comment]
It's annoying indeed, but it seems to me that the action actually fails, right?

**Comment by mazameli** [comment]
Mea culpa — I'm guilty of not reading that carefully. I'm inclined to leave it as a P2, though — if I'm an admin and I log in as a more restricted user account to check things out and make sure people have the correct access and then I see this, maybe I get the mistaken impression that View-only users _could_ revert things. Even if I click and see the failure, I still am not clear what Metabase's intention is here — are View-only users _supposed_ to be able to revert, and would they be able to if the revert had not failed?

**Comment by kulyk** [comment]
Fixed by #15654
