### ISSUE TITLE
Joining to the same table multiple times results in incorrect column headings

### ISSUE THREAD

**Issue by landreville** [metabase/metabase#13232]
**Describe the bug**
Create a question that joins to the same table three times with different foreign keys.

![Screenshot_20200911_111755](https://user-images.githubusercontent.com/24076/92943576-f1bc4600-f420-11ea-9652-905e6844ea2e.png)

The results show the same table column heading three times. The data in the columns is correctly from the three different foreign keys, but it's impossible to tell column is from which foreign key.

![Screenshot_20200911_111927](https://user-images.githubusercontent.com/24076/92943680-13b5c880-f421-11ea-971c-70b497177424.png)

**Logs**
Javascript Console:
```
Unknown field format 
(3) […]
​
0: "joined-field"
​
1: "Active Month"
​
2: Array [ "field-id", 3033 ]
​
length: 3
​
<prototype>: [
```

There are no relevant log lines in the server troubleshooting log.

**To Reproduce**
1. Have a table with multiple foreign keys to the same table
2. Create a question and add a join for each foreign key
3. Visualize results

**Expected behavior**
The column headings are "[FK name] -> Select Column"

Actual results: column headings are all using the name of the first foreign key that was joined.

**Screenshots**
![Screenshot_20200911_111755](https://user-images.githubusercontent.com/24076/92943576-f1bc4600-f420-11ea-9652-905e6844ea2e.png)

![Screenshot_20200911_111927](https://user-images.githubusercontent.com/24076/92943680-13b5c880-f421-11ea-971c-70b497177424.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-1127.18.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.18"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.1",
      "date": "2020-07-30",
      "branch": "release-0.36.x",
      "hash": "55312e4"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

**Severity**
It is impossible to determine what the column of data contains.

**Comment by landreville** [comment]
Note this seems similar to #12685, however this is specifically about the table column headings. The visualization settings show the correct foreign key names for the groups of columns.

**Comment by landreville** [comment]
As a workaround:

1. Go to visualize
2. Go to Settings
3. Click the gear icon beside the column with the incorrect table heading label
4. Change the Column Title to something more correct

**Comment by flamber** [comment]
Sounds like #12930
