### ISSUE TITLE
I have tried to download from the question in Metabase for 35k row (in actual) but I only get 25k row after downloading as CSV. I think limit row when we download as CSV or others 1 million right? why did it happen?

### ISSUE THREAD

**Issue by supriyd** [metabase/metabase#13244]
I have an issue when downloading question as CSV, I think we can download the file as CSV max 1 million but actually I only get 25K row with 15 columns. so is this bug or what?

**Comment by supriyd** [comment]
anyone can help? this is a little bit urgent for me

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
