### ISSUE TITLE
Allow setting Project ID manually for BigQuery Service Accounts

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13245]
**Is your feature request related to a problem? Please describe.**
With the new Service Accounts, it's not possible to change Project ID. This could be because of different pricing models.
Previously it was possible to switch between "testing" and "production" Project IDs, while still querying the same dataset.

**Describe the solution you'd like**
Option to manually define Project ID.

**Additional context**
Related to #13181

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by JoaoCarabetta** [comment]
I have a project that shares structured public data with BigQuery. We created a set of public datasets and tables. But, they sit in our `project_id`. If a user/company/gov wants to use Metabase to get this data, they can't. Unless they manually add views of the tables they want to use.

This is the feature that I need to start recommending Metabase to our community :)

**Comment by fernandascovino** [comment]
up!

**Comment by jeff303** [comment]
So in this particular case, the project ID could be settable via the UI, but if not set, it would fall back to the value from the credential JSON?

**Comment by JoaoCarabetta** [comment]
To be more complete, there would be two sets of project ids.

1. `billing_project_id`: which project id to charge. This is usually set up by the credential JSON.
2. `project_ids`: the user might want to connect with several datasets that sit in different project ids. For instance, the user might use their own dataset + our public dataset. Or, the user might have a `prod` and a `dev` env that have different project ids.

Ideally, metabase would allow us to connect to any project_id, but it would use the billing project id specified in the credential JSON

**Comment by jeff303** [comment]
Should be coming as part of #16746

**Comment by jeff303** [comment]
This will be supported in the new BigQuery driver coming in release 41.
