### ISSUE TITLE
Stacked chart with line

### ISSUE THREAD

**Issue by Ruben170** [metabase/metabase#13266]
Hello I am trying to visualise a users activity In a stacked chart like this.

![Screenshot 2020-09-17 at 16 14 54](https://user-images.githubusercontent.com/35116541/93483280-f55c3b00-f900-11ea-8229-97423753de92.png)

Now every user also has a target so I want to plot that in the same graph swell, I tried to do this with a combo chart but then the option to create a stacked bar chart disappears and I get this.

![Screenshot 2020-09-17 at 16 16 21](https://user-images.githubusercontent.com/35116541/93483489-22a8e900-f901-11ea-8366-6cd8e11ffe6a.png)

Is there a way I can get this target line into a stacked bar chart? Thanks in advance!!

**Comment by Ruben170** [comment]
Just saw that there is a forum. will move my question there!

**Comment by flamber** [comment]
Duplicate of #12008 - upvote by clicking :+1: on the first post
