### ISSUE TITLE
Sync crashes with OOM on very large columns/row samples [proposal]

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#13288]
There are 2 possible situations:
1) entire sampled result set (via `metabase.db.metadata-queries/table-rows-sample` doesn't fit in memory, but all individual rows do
2) there exists a row with a single value bigger than available memory.

1 is relatively straightforward to fix: currently we take `:rows` from `metabase.db.metadata-queries/table-rows-sample` and fingerprint those. This is inefficient as we could (and already do for normal query results) fingerprint as we reduce over the results, but not accrue the rows. We already have the majority of machinery to do this in place, would just need to assemble a different transducer for the fingerprinting step.

2 is harder as we can't touch the value in any way. Here we can do two things: 
2.1) not fingerprint blobs & co at all. The only real ramification of this is that we then also can't have field values on fields of those types, but the value of those is questionable anyway. There are probably edge cases where people use an inappropriate field type and we still explode, but at least we shore up the common usages.    
2.2) add some more functionality to each driver and get upper bounds on individual columns from the DB catalogue or with queries that get object size or similar. The former is not exposed in all the DBs we support; the latter has questionable performance and I'm also not sure out of hand that all the DBs have a function for that.

I suggest doing 1 + 2.1. Both will make sync much more performant for everyone.

**Comment by robdaemon** [comment]
> 2.1) not fingerprint blobs & co at all. 

:+1: to this. I mean, using blobs in code is complex usually - they're not meant for quick "load the whole thing in RAM". So, unless we devise a means to stream a blob through for sampling, I can't see that you can really sample it without potential RAM issues, or data loss during sampling.

**Comment by sbelak** [comment]
Possibly related: #11983, #12060, #11392 (unlikely)

**Comment by lindsay-stevens** [comment]
For 2.2 maybe when a column type has an indeterminate length such has Postgres types `text` or `json` etc., grab only the first 100 characters with `substring()` (or similar) for sync - it would avoid loading / cataloguing enormous values, and very long values don't play nicely with field values filter drop-down / search anyway.

**Comment by dpsutton** [comment]
closed by two PRs:

- individual items too large: https://github.com/metabase/metabase/pull/13441
- whole resultset too large: https://github.com/metabase/metabase/pull/13688
