### ISSUE TITLE
SHA512 auth function customization example

### ISSUE THREAD

**Issue by tiago-as** [metabase/metabase#13293]
I needed to authenticate users with passwords hashed with SHA512. So I had to do a custom build of the metabase jar. I just wanted to leave here this example/suggestion, maybe someone also needs something like this.

This was done on a Ubuntu 20.04 machine with a Mariadb as the sql database for metabase.

Install the prerequisites listed: https://www.metabase.com/docs/latest/developers-guide.html#install-prerequisites
A these changes to the **src/metabase/util/password.clj** file:

* In the import areain the top of the file should look like this
```
(ns metabase.util.password
  "Utility functions for checking passwords against hashes and for making sure passwords match complexity requirements."
  (:require [cemerick.friend.credentials :as creds]
            [metabase
             [config :as config]
             [util :as u]]))
  ; these are the imports added
  (require '[clojure.string :as str])
  (require '[clojure.java.shell :as shell])
  ; #######################################
```

* At the end of the file, delete the verify-password function and add this code:

```
; function needed because the shell return has an \n
; char at the end of it that doesnt belong to the password
(defn remove-last [str]
  (.substring (java.lang.String. str) 0 (- (count str) 1))
)          

(defn verify-password
    ^Boolean [password salt hashed-password]

    ( 
        (def my-hashed-password (shell/sh "mkpasswd" "-msha-512" password salt))
        (def cleaned-hash (remove-last (my-hashed-password :out)))
        (= cleaned-hash hashed-password)
    )
)

```

To compile the code run:

```
./bin/build
```

In the end the **metabase.jar** file will be at **target/uberjar/metabase.jar**

To make this work properly, you'll need to have an external way of inserting users into the database to place the correct hash and salt values into the core_user table.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting and good hints: https://discourse.metabase.com/
