### ISSUE TITLE
Add a format button similar to AWS Athena that automatically cleans up the SQL query

### ISSUE THREAD

**Issue by Obsecurus** [metabase/metabase#13291]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A button on the raw SQL editor that allows you to quickly format the query similar to AWS Athena

**Describe alternatives you've considered**
Use a third-party service to do this like https://sqlformat.org/

**How important is this feature to you?**
It makes writing complex queries easier if you don't naturally deal with the spacing/newlines, etc. 

**Additional context**

**Comment by flamber** [comment]
Duplicate of #9142

**Comment by Obsecurus** [comment]
sorry
