### ISSUE TITLE
Unable to use sandboxed access on certain tables. Error: "Found more than one group table access policy for user. "

### ISSUE THREAD

**Issue by duvaldt** [metabase/metabase#13319]
Error thrown when user tries to see table with sandboxed access - "Found more than one group table access policy for user xxx@yyyy". In another schema, with exactly the same setup, user can see the table. Can there be anything in the table definition, references, contraints etc that trigger this behaviour?

I have a table called books, all rows have publisher_id set on each book. 
I have a user Erik belonging to group publishers. Erik has publisher_id = 1 set as attribute.

Group "All users" doesn't have access anywhere to anything.
Group "Publishers" have a sandboxed access to table Books, "where publisher_id = user attribute publisher_id".

When Erik logs in and tries to see table books, an error appears: Found more than one group table access policy for user 'xxx@yyy.com'.

**Workaround**
Erik is now in two groups since he cannot be removed from "All users". **However**, if I remove him from "Publishers" group and set the same sandboxed settings on "All users", that is "where publisher_id = user attribute publisher_id", it works as expected.

This means that the functionality works, but I would like to group my users in their own groups. 

**BUT** it works on some other tables.
Books table is quite big, with many references, indexes etc. It is also in the public schema. If I use a more simple table and try the above scenario, I have sometimes made it work with the Publishers group. For example I have crm.events, where publisher_id is set on all rows. If I add a sandboxed permission for group Publihers, Erik can see the Events table. 

** Logs **
09-26 11:08:20 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 2,
 :started_at #t "2020-09-26T11:08:20.008+02:00[Europe/Stockholm]",
 :error_type :client,
 :json_query {:database 2, :query {:source-table 198}, :type "query", :parameters [], :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$assert_one_gtap_per_table.invokeStatic(row_level_restrictions.clj:61)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$assert_one_gtap_per_table.invoke(row_level_restrictions.clj:56)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$tables__GT_gtaps$fn__50520.invoke(row_level_restrictions.clj:78)"
  "query_processor.store$cached_fn.invokeStatic(store.clj:268)"
  "query_processor.store$cached_fn.invoke(store.clj:257)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$tables__GT_gtaps.invokeStatic(row_level_restrictions.clj:70)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$tables__GT_gtaps.invoke(row_level_restrictions.clj:69)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$query__GT_table_id__GT_gtap.invokeStatic(row_level_restrictions.clj:83)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$query__GT_table_id__GT_gtap.invoke(row_level_restrictions.clj:81)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__50694.invoke(row_level_restrictions.clj:246)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__49952.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__46473.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__48698.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__48723.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__48678.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__48152.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__47174.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__47690.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__46026.invoke(add_dimension_projections.clj:318)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__46229.invoke(add_implicit_clauses.clj:141)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__50694.invoke(row_level_restrictions.clj:247)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46622.invoke(add_source_metadata.clj:105)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__50463.invoke(column_level_perms_check.clj:24)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49617.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__46815.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__47737.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__49402.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__47789.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__48408.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__46631.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50314.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49628$fn__49632.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49628.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48626.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__50323$fn__50324.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__50323.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__47666.invoke(cache.clj:209)"
  "query_processor.middleware.validate$validate_query$fn__50332.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__48750.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__46491.invoke(add_rows_truncated.clj:36)"
  "metabase_enterprise.audit.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__31362.invoke(handle_audit_queries.clj:165)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__50299.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48029.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__49491.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__47972.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___39734$thunk__39735.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___39734.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___39743$fn__39746.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___39743.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:233)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:229)"
  "query_processor$fn__50739$process_query_and_save_execution_BANG___50748$fn__50751.invoke(query_processor.clj:245)"
  "query_processor$fn__50739$process_query_and_save_execution_BANG___50748.invoke(query_processor.clj:237)"
  "query_processor$fn__50783$process_query_and_save_with_max_results_constraints_BANG___50792$fn__50795.invoke(query_processor.clj:257)"
  "query_processor$fn__50783$process_query_and_save_with_max_results_constraints_BANG___50792.invoke(query_processor.clj:250)"
  "api.dataset$fn__61265$fn__61268.invoke(dataset.clj:59)"
  "query_processor.streaming$streaming_response_STAR_$fn__35893$fn__35894.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__35893.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__24453.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error "Found more than one group table access policy for user ''xxx@yyy.com'.'",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data
 {:type :client,
  :table-id 183,
  :gtaps
  [{:id 4, :group_id 1, :table_id 183, :card_id nil, :attribute_remappings {"publisher_id" [:dimension [:field-id 1349]]}}
   {:id 3, :group_id 4, :table_id 183, :card_id nil, :attribute_remappings {"publisher_id" [:dimension [:field-id 1349]]}}],
  :user 3,
  :group-ids (1 4)},
 :data {:rows [], :cols []}}

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_265-8u265-b01-0ubuntu2~20.04-b01",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_265",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.265-b01",
    "os.name": "Linux",
    "os.version": "5.4.0-48-generic",
    "user.language": "en",
    "user.timezone": "Europe/Stockholm"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v1.36.6.1",
      "date": "2020-09-21",
      "branch": "enterprise-release-1.36.x",
      "hash": "5695e2b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
We are trying to install and set up Metabase to see if it can replace or own developed software for analytics. This is a deal-breaker for making this happen. But it's not a production issue.

**Comment by flamber** [comment]
Hi @duvaldt 
Please use support email, when using the Enterprise Edition.
Current workaround is to manually delete the old policy from application database table `group_table_access_policy`
