### ISSUE TITLE
Advanced Permissions of Snippets

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#13316]
**Is your feature request related to a problem? Please describe.**
If I create a snippet of critical business logic, I should be able to make it so that not just anybody can edit that snippet.  Just like the concept of Metrics in the Data Model.

**Describe the solution you'd like**
I'd like to be able to define snippets that can only be edited by certain users (or perhaps admins).  Other people can make use of them, but they can't modify them.

**Describe alternatives you've considered**
Telling people not to edit snippets. (we'll see how well that works)

**How important is this feature to you?**
Not nearly as important as revision tracking on snippets (see #13315) because at least with that I can roll back if someone does edit, but would be a nice addition.

**Comment by flamber** [comment]
That's a functionality of Enterprise Edition: https://www.metabase.com/blog/sql-snippets/index.html#snippet-folders-in-the-enterprise-edition
