### ISSUE TITLE
copy dashboard to other instalment

### ISSUE THREAD

**Issue by Ruben170** [metabase/metabase#13329]
Hello,
I have multiple identical databases (with identical I mean the same tables not the same data) each on their own server. Now I have metabase working on one with the correct dashboard I want. Is there a way I can export this dashboard and import it into another Metabase instalment on one of the other servers? Maybe this is not possible for an entire dashboard but would it then be possible to copy a question with the visualisation settings?

**Comment by flamber** [comment]
Hi @Ruben170 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Duplicate of #2052/#6485
