### ISSUE TITLE
error translation to zh about Clear 

### ISSUE THREAD

**Issue by hnuzhoulin** [metabase/metabase#13327]
https://github.com/metabase/metabase/blob/master/locales/zh.po#L1401

```
#: frontend/src/metabase/admin/settings/components/SettingsEmailForm.jsx:93
msgid "Clear"
msgstr "完成"
```

corrent is "清除" ，
"完成" means “Done”

**Comment by flamber** [comment]
Hi @hnuzhoulin 
Translations are being pulled from our project of POEditor, so please make the suggestion there:
https://poeditor.com/join/project/ynjQmwSsGh
