### ISSUE TITLE
Allow Metabase to use MySQL as the application database

### ISSUE THREAD

**Issue by GuillermoBlasco** [metabase/metabase#1332]
Right now [the documentation](https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-the-metabase-jar-file.md#the-metabase-application-database) reads:

    The default settings use an H2 database, but other options are available.

H2 and Postgresql examples are given, but what about other RDMS vendors? The documentation should one of:

* Metabase only supports H2 and Postgresql, and nothing else

* Metabase supports H2 and Postgresql, but we haven't tested other providers.

* Metabase should support most common RDMS vendors. H2 and Postgresql have been tested.

**Comment by agilliland** [comment]
For the application database itself the more exact response is `Metabase only supports H2 and Postgresql, and nothing else`

**Comment by lukaswelte** [comment]
I updated the documentation to reflect that currently only H2 and Postgres are supported.
But I would love this ticket to be converted into a feature request.
Many people have MySQL running and would prefer having the data stored there instead of a local H2 database.
