### ISSUE TITLE
Unable to update Field via API

### ISSUE THREAD

**Issue by rabbitramen** [metabase/metabase#13326]
Hi,

I have a Python script to sync fields from all tables so I don't have to update the table metadata manually. Currently I'm using `PUT /api/field/:id` call and included the metadata I want to update as json. It has worked for me before, but I've been getting status 500 when I make this call now.

Here's an example of my script:
```
import requests

# test.
base_url = 'http://metabase.domain.com/'
headers = {'X-Metabase-Session': '<METABASE_SESSION_ID>'}

field_id = 12345
field_path = 'api/field/{}'.format(str(field_id))

r = requests.get(
    base_url + field_path,
    headers=headers
)
print(r.status_code, r.reason) # 200 ok.

r = requests.put(
    base_url + field_path,
    headers=headers,
    json={
        'description': 'ID of an account.'
    }
)
print(r.status_code, r.reason) # 500 server error.
```

Wasn't sure if anyone had faced this issue as well.

**Comment by flamber** [comment]
Hi @rabbitramen 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://www.metabase.com/blog/metabase-api/index.html
