### ISSUE TITLE
Run own sql queries and skip query builder UI

### ISSUE THREAD

**Issue by kidambisrinivas** [metabase/metabase#1333]
Is it possible to skip the query builder UI and run own SQL queries as I've complex time-windowed join sql queries based on multiple tables.

Thanks.

**Comment by salsakran** [comment]
Yes! Check out
http://www.metabase.com/docs/v0.12.0/users-guide/03-asking-questions.html#asking-more-advanced-questions-in-sql

**Comment by kidambisrinivas** [comment]
Thanks for the quick response, I initially didnt get the editor switch. Somehow it appeared after a restart.
