### ISSUE TITLE
Cumulative sum using a time dimension and another categorizing group does not show total running per each categorized group correctly

### ISSUE THREAD

**Issue by itai-codefresh** [metabase/metabase#13335]
**Describe the bug**
Using cumulative sum and using 2 groups (time dimension and another categorizing dimension) will not create a separate cumulative sum track, rather will provide wrong results by not segregating the cumulative running on each value of the categorizing dimension.

**Expected behavior**
The expected behavior is to get a line per each group that shows the correct growth on its specific group alone

**Screenshots**
![image](https://user-images.githubusercontent.com/10414627/94813971-602d6c00-0401-11eb-9f62-18f3c379062f.png)
![image](https://user-images.githubusercontent.com/10414627/94814027-720f0f00-0401-11eb-9af2-b25e477b88ab.png)
![image](https://user-images.githubusercontent.com/10414627/94814048-7804f000-0401-11eb-9449-f0887a374282.png)

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-15",
      "tag": "v1.36.6",
      "branch": "enterprise-release-1.36.x",
      "hash": "42541b6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Severity**
This issue is making it hard to be able to draw different segments on a graph that shows total running growth

**Comment by flamber** [comment]
Hi @itai-codefresh 
This is a known limitation - please upvote the issue by clicking :+1: on the first post of #2862

**Comment by rajat20gl** [comment]
This is not fixed Yet
