### ISSUE TITLE
When an "more options" filter is applied, it should be displayed

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1334]
Expected:
<img width="376" alt="screen shot 2015-10-22 at 1 44 58 pm" src="https://cloud.githubusercontent.com/assets/107439/10677969/3d3f9b6e-78c4-11e5-918b-91c6f52c2f89.png">

Actual:
<img width="378" alt="screen shot 2015-10-22 at 1 45 03 pm" src="https://cloud.githubusercontent.com/assets/107439/10677964/3a0784f2-78c4-11e5-8f44-a1e239530e99.png">

**Comment by tlrobinson** [comment]
This is fixed by #1262
