### ISSUE TITLE
Add Swiss number formatting (Localization - Separator Style)

### ISSUE THREAD

**Issue by etoulas** [metabase/metabase#13348]
🤚 _I'm happy to contribute, but I need some pointers (links) where to find the relevant files for l10n / i18n._

**Is your feature request related to a problem? Please describe.**
The Swiss number format is not supported currently. We operate in Switzerland and our numbers on the dashboards are never quite what we expect (pun intended).

Note: even though the examples below include currency symbols, this issue concerns the group and decimal separators.

**Describe the solution you'd like**
Add a new _Separator Style_ in Settings > Localization > Numbers. That's `<Site URL>/admin/settings/localization`.

The Swiss separator style follows this pattern `100’000’000.00`.

**Describe alternatives you've considered**
I'm not familiar with the Metabase architecture, but I assume that there is a frontend part and a backend part to it. First priority would be to address the frontend.

**How important is this feature to you?**
I created an issue and would like to contribute this myself. That important. Help appreciated.

**Additional context**
Example of the Swiss format compared to German and US, taken from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat):
```js
const number = 123456.789;

console.log(new Intl.NumberFormat('de-CH', { style: 'currency', currency: 'CHF' }).format(number));
console.log(new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(number));
console.log(new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(number));

> "CHF 123’456.79"
> "123.456,79 €"
> "$123,456.79"
```

This looks like a good place to look into for the frontend part.
- https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/formatting.js#L52
- https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/formatting.js#L230-L239

**Comment by flamber** [comment]
Related to #8903 and probably #10785

**Comment by etoulas** [comment]
When I look at the [frontend code responsible for the separator style](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/formatting.js#L52), it looks a lot easier to fix just the number format without the currency. I updated the issue description to be more precise that this issue addresses the separator styles.

**Comment by culturedev** [comment]
> it looks a lot easier to fix just the number format without the currency. 

This is an important point. Currency and symbols is not the main issue here. In the case of financial statements, it is rare to find a currency symbol on every single number in that statement. People are accustomed to seeing numbers in the format which is standard in their location. Seeing a different format can be a put-off and hinder the acceptance of this great solution.
I strongly support this issue to provide Swiss number formatting (not currency). Why not just provide a template editor field in the admin, where people can define their format for thousand separator and currency however way they want it (similar to how it can be done in Excel)?
