### ISSUE TITLE
Parameter is missing on query with nested query and filters

### ISSUE THREAD

**Issue by boardmain** [metabase/metabase#13349]
**Describe the bug**
Parameter missing when using filters

if i use the filter i receive the error error
Parameter at position 3 is not set

if i remove the value of the filters the query work correctly ( you can see the query below )

**Logs**
`[7efead41-bfbf-4b82-b0d3-20a01e245caa] 2020-10-02T16:57:00+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Errore elaborazione query: null
{:database_id 3,
:started_at #t "2020-10-02T14:56:58.610634Z[UTC]",
:state "07004",
:json_query
{:type "native",
:native
{:query
"SELECT OggettoTaskSuccessiva ,count(distinct url) AS `count`\n\nFROM ({{#183}}) `source`\n\nWHERE TaskSuccessivaStatus = `Open` \n\n[[ AND DataCreazioneTask >= {{DataCreazioneTaskInizio}} AND DataCreazioneTask < {{DataCreazioneTaskFine}} + INTERVAL 1 DAY]]\n[[ AND DataScadenzaTask >= {{DataScadenzaTaskInizio}} AND DataScadenzaTask < {{DataScadenzaTaskFine}} + INTERVAL 1 DAY]]\n[[ AND DataTaskCompletata >= {{DataTaskCompletataInizio}} AND DataTaskCompletata < {{DataTaskCompletataFine}} + INTERVAL 1 DAY ]]\n[[ AND LeadSource = {{LeadSource}} ]]\n[[ AND EdizioneTour = {{EdizioneTour}} ]]\n\nGroup by OggettoTaskSuccessiva\nORDER BY count DESC",
:template-tags
{:LeadSource {:id "a9047e5b-bf68-5c63-3ab7-3a5cfd515129", :name "LeadSource", :display-name "Leadsource", :type "text"},
:#183 {:id "faa07993-c3b0-1c37-a40c-3d699b028be9", :name "#183", :display-name "#183", :type "card", :card-id 183},
:DataCreazioneTaskFine {:id "b9c0f859-9817-7b0f-cb1e-45d8f994d2c1", :name "DataCreazioneTaskFine", :display-name "DataCreazioneTaskFINE", :type "date"},
:DataScadenzaTaskInizio {:id "af012e0c-bc61-4aee-0cc9-3331fff57273", :name "DataScadenzaTaskInizio", :display-name "DataScadenzaTaskInizio", :type "date", :default nil},
:EdizioneTour {:id "c26c397e-4470-2912-f07b-551b03bc6733", :name "EdizioneTour", :display-name "Edizionetour", :type "text"},
:DataTaskCompletataFine {:id "0605890f-8cd2-a7bb-a81b-074827c09db5", :name "DataTaskCompletataFine", :display-name "DataTaskCompletataFine", :type "date"},
:DataScadenzaTaskFine {:id "ce01e577-0d39-0f00-4dbd-0897cd3bad58", :name "DataScadenzaTaskFine", :display-name "DataScadenzaTaskFine", :type "date", :default nil},
:DataCreazioneTaskInizio {:id "5d328ded-4954-3de7-07c2-65353d9ae81b", :name "DataCreazioneTaskInizio", :display-name "DataCreazioneTaskINIZIO", :type "date"},
:DataTaskCompletataInizio {:id "a855815a-bd1e-9532-5e61-18136ffa6202", :name "DataTaskCompletataInizio", :display-name "DataTaskCompletataInizio", :type "date"}}},
:database 3,
:parameters
[{:type "date/single", :target ["variable" ["template-tag" "DataCreazioneTaskFine"]], :value "2020-10-03"}
{:type "date/single", :target ["variable" ["template-tag" "DataCreazioneTaskInizio"]], :value "2020-09-01"}],
:middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
:status :failed,
:class java.sql.SQLTransientConnectionException,
:stacktrace
["org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)"
"org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:179)"
"org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:195)"
"org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)"
"org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)"
"com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
"--> driver.sql_jdbc.execute$fn__72618.invokeStatic(execute.clj:267)"
"driver.sql_jdbc.execute$fn__72618.invoke(execute.clj:265)"
"driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:389)"
"driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
"driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)"
"driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)"
"query_processor.context$executef.invokeStatic(context.clj:59)"
"query_processor.context$executef.invoke(context.clj:48)"
"query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
"query_processor.context.default$default_runf.invoke(default.clj:67)"
"query_processor.context$runf.invokeStatic(context.clj:45)"
"query_processor.context$runf.invoke(context.clj:39)"
"query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
"query_processor.reducible$pivot.invoke(reducible.clj:31)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)"
"query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
"query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
"query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
"query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
"query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
"query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
"query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
"query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
"query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
"query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
"query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
"query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
"query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
"query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:316)"
"query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
"query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
"query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
"query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
"query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
"query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
"query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
"query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
"query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
"query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
"driver$do_with_driver.invokeStatic(driver.clj:61)"
"driver$do_with_driver.invoke(driver.clj:57)"
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
"query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
"query_processor.store$do_with_store.invokeStatic(store.clj:46)"
"query_processor.store$do_with_store.invoke(store.clj:40)"
"query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
"query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
"query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
"query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:147)"
"query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
"query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
"query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
"query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107)"
"query_processor.reducible$sync_qp$qp_STAR___38083$fn__38086.invoke(reducible.clj:133)"
"query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:132)"
"query_processor$process_userland_query.invokeStatic(query_processor.clj:215)"
"query_processor$process_userland_query.doInvoke(query_processor.clj:211)"
"query_processor$fn__47372$process_query_and_save_execution_BANG___47381$fn__47384.invoke(query_processor.clj:227)"
"query_processor$fn__47372$process_query_and_save_execution_BANG___47381.invoke(query_processor.clj:219)"
"query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425$fn__47428.invoke(query_processor.clj:239)"
"query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425.invoke(query_processor.clj:232)"
"api.dataset$fn__50707$fn__50710.invoke(dataset.clj:55)"
"query_processor.streaming$streaming_response_STAR_$fn__35496$fn__35497.invoke(streaming.clj:73)"
"query_processor.streaming$streaming_response_STAR_$fn__35496.invoke(streaming.clj:72)"
"async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
"async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
"async.streaming_response$do_f_async$fn__23282.invoke(streaming_response.clj:85)"],
:context :ad-hoc,
:error "(conn=2) Parameter at position 3 is not set",
:row_count 0,
:running_time 0,
:data {:rows [], :cols []}}`

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "it-IT",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10-post-Ubuntu-0ubuntu118.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10-post-Ubuntu-0ubuntu118.04.1",
    "os.name": "Linux",
    "os.version": "4.15.0-118-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-15",
      "tag": "v0.36.6",
      "branch": "release-0.36.x",
      "hash": "cb258fb"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

**Severity**
Hight

**Comment by flamber** [comment]
Hi @boardmain 
It’s currently not supported to pass-thru filters from Saved Questions or Sub-Query variables - #4367/#6449
