### ISSUE TITLE
Attempt to use beanstalk recipe in non US-EAST AZ's results in AWS BeanStalk - S3 Moved Permanently

### ISSUE THREAD

**Issue by nodesocket** [metabase/metabase#1336]
Hi guys.

Trying to use AWS BeanStalk, but getting:

> Could not launch environment: https://s3.amazonaws.com/downloads.metabase.com/v0.12.0/metabase-aws-eb.zip (Bucket: downloads.metabase.com Key: v0.12.0/metabase-aws-eb.zip). Reason: Moved Permanently

Using the S3 url recommended in the documentation: 

https://s3.amazonaws.com/downloads.metabase.com/v0.12.0/metabase-aws-eb.zip

**Comment by agilliland** [comment]
Yeah, after poking around a bit it looks like this is a limitation of EB.  It doesn't let you reference an s3 file from a region other than the one you are trying to launch in ...

http://blog.mikebabineau.com/2013/08/21/multi-region-gotcha-on-elastic-beanstalk/

I'm looking at the best way to solve this.  I'm not particularly keen on having to manage a lot of region constrained buckets just for this one file, but that may be what's required.

To work around the issue you can simply download the file at that url and manually upload it in the `Application Version` step when you create your environment in EB.

**Comment by nodesocket** [comment]
:+1: downloading the file now.

**Comment by agilliland** [comment]
I'm going to actually leave this open so that we have a reminder to address the underlying problem and prevent this error from happening in the first place.

I'm assuming that the work around of downloading the file first and uploading it directly in your EB environment worked okay though?

**Comment by shaneog** [comment]
You might be able to use [Cross-Region Replication](https://aws.amazon.com/blogs/aws/new-cross-region-replication-for-amazon-s3/) for this.

**Comment by thedavidprice** [comment]
@agilliland Download and add file just worked fine for me. In the short term could add heads up in the docs install guide? Probably a simple one-liner. Happy to do so if it would help.

**Comment by agilliland** [comment]
@thedavidprice cool, that would be great!

**Comment by madhavc** [comment]
@agilliland I cannot download the file even from the url https://s3.amazonaws.com/downloads.metabase.com/v0.12.0/metabase-aws-eb.zip

Give me the error 
![image](https://user-images.githubusercontent.com/5370479/36621432-e032965c-18ac-11e8-8c34-7dccc44ae938.png)

**Comment by jornh** [comment]
You probably want  latest version (it works for me): https://s3.amazonaws.com/downloads.metabase.com/v0.28.1/metabase-aws-eb.zip

Version 0.12 is now more than two years old.

**Comment by mobedi** [comment]
@jornh could you tell us where you find the latest version?

**Comment by mattarderne** [comment]
Any update on this? Following the docs I bumped into this and had to scratch around to find this issue

**Comment by jornh** [comment]
Simply replacing a later version number in that URL still seems to work, like:

https://s3.amazonaws.com/downloads.metabase.com/v0.32.5/metabase-aws-eb.zip

Unsure if that was what you were asking for?

**Comment by sethia** [comment]
This doesn't work, getting the same error ! 

"Unable to download from S3 location (Bucket: downloads.metabase.com Key: v0.32.8/metabase-aws-eb.zip). Reason: The bucket is in this region: us-east-1. Please use this region to retry the request"

**Comment by flamber** [comment]
@sethia It looks like a different error. Your client is probably trying a different region than `us-east-1`.
A work-around is the manually download the file and upload it as noted in https://github.com/metabase/metabase/issues/1336#issuecomment-150381247

**Comment by sethia** [comment]
Yes the upload workaround is what we finally used, but how is one expected to deploy in another region (non us-east) then?

**Comment by NasreenUstad** [comment]
[https://s3.amazonaws.com/downloads.metabase.com/v0.28.1/metabase-aws-eb.zip] this worked for me

**Comment by flamber** [comment]
@NasreenUstad You should use the latest release, so the URL today would look like this:
https://s3.amazonaws.com/downloads.metabase.com/v0.33.2/metabase-aws-eb.zip

**Comment by paoliniluis** [comment]
Do you think we can close this issue @flamber thanks to this https://github.com/metabase/metabase/pull/14273?

**Comment by flamber** [comment]
@paoliniluis If the new documentation completely deprecates this problem, then yes.
