### ISSUE TITLE
0.37-rc1: after clicking a custom link that passes a value to a param, clicking Back shouldn't bring that value to the original dashboard

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#13380]
@flamber: "When using "Click behavior" with a column from the card to point to another dashboard, then clicking back in the browser to return to the original dashboard, the filter value is also set on the original dashboard if it wasn't already defined. This might have been a feature, when having the same filter names, then going between dashboards would carry the values with, but it doesn't feel correct anymore with this context."

**Comment by paulrosenzweig** [comment]
It looks like this was accidentally fixed when I made command click work to open in a new tab.
