### ISSUE TITLE
Make ssh heartbeat intervals configurable

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#13399]
For ssh tunnel connections to database, we've added an "ssh heartbeat" to try and stop a connection from going idle. Right now, it's defaulted to 180 seconds. This should be a setting in public_settings so we can adjust it later.

**Comment by robdaemon** [comment]
related to changes in https://github.com/metabase/metabase/pull/13391

**Comment by flamber** [comment]
Related to #3941 #6114 #10081

**Comment by jeff303** [comment]
@flamber , where do you envision this setting showing up in the UI?  I suppose General, although this definitely feels very low level compared to the other stuff there.

<img width="927" alt="Screen Shot 2021-02-05 at 9 16 52 AM" src="https://user-images.githubusercontent.com/3521562/107052228-04019c80-6793-11eb-9b7c-6e51658f594f.png">

**Comment by flamber** [comment]
It should "just work" without almost anyone having to change or modify anything, so perhaps 55 seconds would be better, but it should probably just be an envvar - which we need to expose somehow anyway, but that's 4564

**Comment by jeff303** [comment]
My guess is the actual default value will depend a lot on things like network topology, versions of software infrastructure, etc.  If the existing hardcoded value of `180` (or some other hardcoded value we could switch to) is sufficient, then why does this issue exist?

**Comment by robdaemon** [comment]
It's more than just that - it depends on the `sshd_config` - the existing value may not work for every environment.

**Comment by jeff303** [comment]
Done via #14679.
