### ISSUE TITLE
Fixed caching TTL instead of a TTL multiplier to easily cache fast and slow queries

### ISSUE THREAD

**Issue by bfelbo** [metabase/metabase#13396]
**Is your feature request related to a problem? Please describe.**
We have many dashboards with queries that take between 1 second to 1 minute to run. As many users often look at the same dashboards, we'd love to use caching to speed up the user experience and reduce load on our DB.

It's important for us to have real-time data in the dashboards (i.e. max 60 seconds of stale data). As such, we cannot use the caching as currently implemented since the TTL multiplier will have to be high to be relevant for the fast queries, but cannot be high because it would cause the slow queries to have stale data for a long time.

**Describe the solution you'd like**
We'd love an alternative to the caching TTL multiplier, where we simply set a fixed time that queries are cached for. For instance, we'd love to cache all queries above the minimum query duration for 60 seconds.

**Describe alternatives you've considered**
We've done the following:
1. Discussed back and forth what values would make sense for minimum query duration and for the TTL multiplier, but haven't been able to find anything.
2. Considered optimizing our database with some kind of continuous aggregate system, but that would require a major overhaul of our DB/queries and would add a lot of complexity.
3. Increased our DB connections (see https://github.com/metabase/metabase/issues/2172), but there's a limit to how many connections we can have w/o putting too much load on our DB.

(2) and (3) seem a bit silly as users are running identical querys for the exact same dashboards so caching should be able to solve this trivially.

**How important is this feature to you?**
Most of our queries on our dashboards don't load so it's making Metabase essentially unusable.

**Comment by flamber** [comment]
Hej @bfelbo 
It is possible to define TTL on a per-question in the application database (it's not exposed in the UI) - see #9983
Related to #5144

**Comment by bfelbo** [comment]
Tak @flamber! Those issues seem very relevant.

It's nice to hear that there's something we can do. However, we have lots of questions though (and keep adding more) so it would be very hard to do it on a per-question basis.

**Comment by flamber** [comment]
@bfelbo Alt er muligt for den der bærer viljen i sit hjerte ;-)

You can create a script that sets the TTL - and you can find the average execution time in the table `query` or each query's running time in `query_execution`. Not saying it's perfect, but would probably be a good workaround/hack.
But if you need more help in that area, then please use the forum: https://discourse.metabase.com/

**Comment by theoaf** [comment]
@bfelbo did you have any luck with this? we're looking at a similar issue also.

**Comment by bfelbo** [comment]
No, haven't had the bandwidth to try the script approach. If you find a workaround, definitely let me know! :)

**Comment by SetSails** [comment]
it would be great if the -- apparently already available TTL field -- could be made accessible through the UI. We're also facing issues with the unpredictability of data "freshness" due to the current TTL approach. Thanks !

**Comment by theoaf** [comment]
@SetSails if you want to set TTL to be specific to different questions or dashboards I've found a hacky solution

https://discourse.metabase.com/t/dashboard-specific-caching/11937/17

**Comment by mejran** [comment]
This is an issue for us as well. We're just going to publicly fork and remove the relative TTL but it'd be really nice if it was built in.

**Comment by flamber** [comment]
This was implemented in 1.41 - Enterprise Edition - https://github.com/metabase/metabase/releases
It is possible to set a fixed hourly value for question, dashboard and/or database.
