### ISSUE TITLE
Connecting to local H2 database sometimes fails if `;USER=sa` not part of connection string

### ISSUE THREAD

**Issue by ArthurZ** [metabase/metabase#1339]
Hi,
I am running all on localhost. Unable to establish a connection to H2.
Using the following connection string:
file:C:/Users/ArthurZ/mdiperf;AUTO_SERVER=TRUE
Error is
Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == SERIALIZED || fileLockMethod == FS || inMemory)" [50100-189]

**Comment by camsaul** [comment]
Hey @ArthurZ,
For security purposes, we try to make all Metabase DB connections read-only automatically. For H2, we automatically append `READ_ONLY=TRUE` to the connection string. As the error message suggests, you can't have a connection string that's both `READ_ONLY=TRUE` and `AUTO_SERVER=TRUE`. 

If you try connecting to the H2 database without `AUTO_SERVER=TRUE` in the connection string it should work.

**Comment by ArthurZ** [comment]
Then is says Looks like the username or password is incorrect.

**Comment by camsaul** [comment]
Do you have a username or password set on the database ?

**Comment by ArthurZ** [comment]
nope

**Comment by ArthurZ** [comment]
here is the aha moment: @camsaul if I prepend the connection string with ;USER=sa 
it works.

**Comment by camsaul** [comment]
Oh, weird... I thought `;USER=sa` was implied if you didn't specify?

**Comment by ArthurZ** [comment]
Apparently, this is not the case.
Thank you @camsaul !

**Comment by camsaul** [comment]
No problem. Thanks for helping diagnose the problem!

I'm going to look into this a little further. It might make sense for Metabase to try connecting with `;USER=sa` automatically if `USER` isn't set in the connection string.

**Comment by camsaul** [comment]
After doing a lot of research last night and today I don't think it makes sense for Metabase to try to guess the username of an H2 database. It seems that in some cases [`sa` is the default username](http://stackoverflow.com/questions/8695420/what-is-the-default-username-and-password-for-h2-when-theres-nothing-explicit-i) but [in others it's empty](http://stackoverflow.com/questions/28187110/cant-login-to-h2-database-from-h2-console-after-using-jdbc?lq=1). 

Currently if you can connect to an H2 database outside of Metabase it will work in Metabase using the same connection string. By trying to second-guess that behavior I'm almost certain we'll end up breaking H2 for other users.

**Comment by agilliland** [comment]
I agree, this is something that should be put in as part of the connection string when setting up the database :+1:
