### ISSUE TITLE
Filter by foreign MongoDB ID does not seem to work (?)

### ISSUE THREAD

**Issue by nodesocket** [metabase/metabase#1340]
Doing a filter using a foreign MongoDB id, returns 0 results.

**Comment by salsakran** [comment]
What do you mean by foreign MongoDB id in this context? Could you give us an example document and the filter you're trying to add?

**Comment by camsaul** [comment]
See also #1367

**Comment by camsaul** [comment]
Duplicate of #1340

**Comment by camsaul** [comment]
* Duplicate of #1367
