### ISSUE TITLE
0.37-RC2: weird edit state when saving a dashboard with incomplete click behavior

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#13412]
I'm not yet sure if this happens for more cases, but I was trying to set up cross-filtering behavior here for a table card to update a newly added dashboard filter. 

Part of the problem seems to be that Metabase isn't seeing the newly added dashboard filter as an available target, which is itself its own bug (not sure if that's been filed separately yet).

When I then try to save the dashboard with the click behavior in this unfinished state, I exit Edit mode, but the sidebar doesn't close. Not shown here, but importantly, when I then try to edit this dashboard and e.g. remove the click behavior, no buttons work. I can't figure out how to repair a dashboard in this state.

![weird-edit-state](https://user-images.githubusercontent.com/2223916/95495379-3241ad80-0954-11eb-9d40-e95df875c1d5.gif)

**Comment by flamber** [comment]
From #13405 
> Possible to select "Click behavior" option, but not selecting the target dashboard/question/URL, which causes invalid links like `http://localhost:3001/dashboard/undefined` or strange extra menu, which isn't clickable.
