### ISSUE TITLE
Support Docker on Raspberry PI (ARM)

### ISSUE THREAD

**Issue by mikebski** [metabase/metabase#13426]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to run this on a Pi - it appears that the base container does not work on the Pi

**Describe the solution you'd like**

A docker build that would work on the Pi

**Describe alternatives you've considered**

Other systems

**How important is this feature to you?**

Important enough that I've created a working Dockerfile so that I can run Metabase on a Pi 4 in Docker

**Additional context**

Just not sure how to submit a pull request for this, because I'd think it would be maybe a separate Dockerfile? Need some direction on how it could be done and I'll submit a PR

**Comment by flamber** [comment]
Duplicate of #13119
