### ISSUE TITLE
0.37.0-rc2: log4j should not output to file by default

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#13422]
**Describe the bug**
The new default log configuration creates a file at `${logfile.path}/metabase.log` (note the unescaped path) that contains the Metabase log output. Previous versions of Metabase logged to the console by default, but didn't create an output file.

When running in Docker, this also results in `ERROR` level log messages as it can't create the directory.

**Logs**
```
2020-10-09 05:15:23,276 main ERROR Unable to create file ${logfile.path}/metabase.log java.io.IOException: Could not create directory /${logfile.path}
```

**To Reproduce**
1. Start Metabase v0.37.0-rc2 jar or Docker image `metabase/metabase:v0.37.0-rc2`
2. When using the jar, notice a `${logfile.path}/` directory is created with the console log in `metabase.log`
3. When using Docker, notice multiple exceptions.

**Expected behavior**
Metabase logs output to the console and nowhere else.

**Screenshots**
n/a

**Information about your Metabase Installation:**
n/a

**Severity**
Should be fixed before release.

**Additional context**
n/a

**Comment by flamber** [comment]
We still create `${logfile.path}/metabase.log` when starting - it's empty - but that will still fail on Docker
