### ISSUE TITLE
Ability to sort&filter questions

### ISSUE THREAD

**Issue by nborrmann** [metabase/metabase#13435]
As soon as a collection contains more than, say, 20 questions, it becomes hard to find the question you're looking for. 

This could be easier by showing more metadata (eg: created by, created at, last modified, last viewed) for each question instead of just the title. Additionally it would be nice to filter or sort based on these criteria.

We have over 1000 questions and we frequently "lose" the questions that we previously worked on. You have to be really strict about using different collections for everything, or you will have a hard time navigating metabase. I think this feature would greatly improve the situation.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #3497

**Comment by nborrmann** [comment]
I hacked something together yesterday: 
![image](https://user-images.githubusercontent.com/1723176/95970808-aaa2e580-0e10-11eb-8573-cedd8c2cbd80.png)

Can I get some feedback on whether or not this is something that you like and would like to get merged into master? I'm happy to send you a PR. (However, I'm neither a frontend nor a clojure developer - so it will probably need some love from the experts).
