### ISSUE TITLE
Passthrough User Database Source Credentials

### ISSUE THREAD

**Issue by friendofasquid** [metabase/metabase#13449]
**Is your feature request related to a problem? Please describe.**

Different users are authorised differently. Rather than managing auth in Metabase, allow Metabase to pass through credentials from users to the database.

**Describe the solution you'd like**

Prompt the user for their credentials when viewing a report. 

When setting up the "main" credentials used for database sync, include an option of whether to use these credentials or to prompt the user.

**Describe alternatives you've considered**

Manage permissions inside Metabase using existing governance.

Some other tools use some kind of internal logic to manage data access, sometimes with special functions (e.g. Tableau) or SQL templating sugar to check for current user and limit scope of results (e.g. Dremio). 

Some some kind of templating tag that gives group membership could do. For example to limit rows to just the current user:

```
SELECT * FROM table 
WHERE
 {{ fn:is_member('admin') }} -- returns TRUE of FALSE
OR user = '{{ fn:current_user() }}' --returns current username, e.g. 'bob'
```

**How important is this feature to you?**

We'd like a centralised way of governing database access per user. If we can pass through credentials, this will avoid error and allow us to expand Metabase to more sensitive data sources.

**Additional context**

**Comment by flamber** [comment]
Hi @friendofasquid 
It sounds a lot like Sandboxing, which is part of our Enterprise Edition:
https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html
