### ISSUE TITLE
Record DBMS version number on sync

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#13444]
It's hard to make informed decisions about which versions of databases we should support/drop support for because we currently have no metrics on which versions of DBs our customers are using. For most DBMSes this doesn't matter a whole lot -- for example with Postgres we support 9.x+ and use the latest JDBC drivers, which are backwards compatible with older versions such as 9.x. Other DBs like Apache Hive/Spark SQL are not backwards-compatible -- the 3.x JDBC driver isn't backwards-compatible with 1.x databases for example. It's hard to decide what to do about these edge case situations -- do we ship separate 1.x/2.x and 3.x drivers? Do we drop support for 1.x? If we had a sense for which versions of Spark SQL people were using, it would be easier to make these decisions.

It's pretty easy to get the version of a database someone is using, so we should record this on sync and then include this info in the anonymous stats. We already include database *type* (e.g. "postgres") in anonymous stats so I don't think this is really major change to that in that area. I'm not sure whether we'd need to update our privacy policy/etc. to reflect this change but we should double-check.

Even better: I think we should record attempts to connect to a database of a given type and whether the attempt was successful or not. For all we know, we have tons of people trying to connect with Spark SQL 3.x as with 1.x, but if 3.x isn't currently working then we really wouldn't know about it unless people open GitHub issues/Discourse threads/paid support issues. This is a bit of a bigger change than just recording version info.

**Comment by camsaul** [comment]
One other benefit of having version number info is we'd be able to enable/disable certain features based on DBMS version, for example Spark SQL 2.x+ supports a lot of temporal functions not supported in 1.x. We could do something smart here rather than just generating queries that aren't going to work on 1.x

**Comment by sbelak** [comment]
Related: #3136

**Comment by camsaul** [comment]
Steps for tackling:

- [ ] Add a new column to the Database table to record version information. For MySQL/MariaDB this should also include which of those two it is -- or does this belong in a different column? Maybe the column should be JSON so we can have arbitrary keys if we want to store more than just the major/minor/path version.
- [ ] Add a new driver multimethod to `metabase.driver` that can connect to a database to get this information. Sync should call this and record it during `sync-database!`. It's probably okay to do this on every Database sync -- it shouldn't be more expensive than opening a connection. Default method can be `nil` because this won't make sense for some databases, e.g. cloud-based databases like BigQuery or Snowflake
- [ ] Add notes in the [driver changelog](https://github.com/metabase/metabase/blob/master/docs/developers-guide/driver-changelog.md) about the new method for driver authors
- [ ] Add a default implementation for `:sql-jdbc` drivers that uses `DatabaseMetaData`
- [ ] Add implementations for `:mongo` and `:druid`
- [ ] (Optional but nice to have) add this to the anonymous stats 

That should do it

**Comment by camsaul** [comment]
We should also do this for the application database so we can get some information about who is still on older versions like MySQL 5.7 so we can make educated decisions about when to drop support
