### ISSUE TITLE
Cannot edit BigQuery settings without providing service account JSON again

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#13442]
**Describe the bug**

When editing a BigQuery database connection, the UI requires you to provide the service account JSON again before you can save.

**Logs**
N/A

**To Reproduce**
1. Go to 'Admin' / 'Databases'
2. Pick an existing Google BigQuery instance
3. Change the name or whatever
4. Try to save

**Expected behavior**
Service Account JSON files should not be required for existing databases, and should only be necessary if you wish to change it.

**Screenshots**

This is an existing BQ database that I changed the name - the save button should have become active at that point.

![bq-service-account](https://user-images.githubusercontent.com/287213/95780831-7f3dc080-0c81-11eb-8d8f-c087a572c2ed.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "5.8.12-200.fc32.x86_64",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "tag": "v0.36.6",
      "hash": "1561bc0",
      "branch": "do-not-send-some-keys",
      "date": "2020-10-09"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #4196/#6613 and #13181
