### ISSUE TITLE
Changing column order/visibility via visualization Settings sidebar is inconsistent

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13455]
**Describe the bug**
When using the visualization Settings sidebar to reorder column and removing columns, causes some inconsistency. Reordering works, but removing columns will reset the order. And every change will show Play-button instead of just doing the change.

**To Reproduce**
1. Custom question > Sample Dataset > Orders - join table Products
![image](https://user-images.githubusercontent.com/1447303/95859963-abc80a00-0d5f-11eb-937c-66e63c751c3c.png)
2. Click visualization Settings sidebar > drag "Product -> Category" column to beginning of table - it actually moves the column, when looking underneath the overlay, but still shows Play-button (the old "Get answers"):
![image](https://user-images.githubusercontent.com/1447303/95860173-f9447700-0d5f-11eb-8dfc-276e8c52d014.png)
3. Click the Play-button and now remove the column "Subtotal", which will then seem to do it correctly underneath the overlay:
![image](https://user-images.githubusercontent.com/1447303/95860757-c9e23a00-0d60-11eb-8d9f-39c868d951de.png)
4. But after clicking the Play-button, then "Subtotal" is removed, but any column ordering has reverted to default:
![image](https://user-images.githubusercontent.com/1447303/95860865-f0a07080-0d60-11eb-8696-9622a0876007.png)

**Information about your Metabase Installation:**
Metabase 0.35.4, 0.36.7, 0.37.0-rc2

**Additional context**
Related to #12395. And a little to #12044.
This is not a regression, but it's basically some of the same problems as #10466

**Comment by nemanjaglumac** [comment]
Also, when you want to add back some column, it sometimes gets put back in its original place just for a fraction of a second, and then ends up at the very end:
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/04uJWR84/68f16772-0225-40f9-b857-400151a5efd2.gif?source=viewer&v=e73c1422554999d4684adefee7ad6b93)

**Comment by Beeskey** [comment]
I'm still having a very similar problem, my case has been that dragging columns to reorder either in the settings sidebar or the actual column headers on the table themselves will cause all columns from any joined tables to disappear. When I look at the question, all columns have been deselected on these tables. Should I create a new issue?

**Comment by flamber** [comment]
@Beeskey You are likely seeing #22563, if not, then create a new issue with clear steps-to-reproduce.

**Comment by npfitz** [comment]
Should have been fixed by the changes in #27689

**Comment by paoliniluis** [comment]
Similar to https://github.com/metabase/metabase/issues/29287
