### ISSUE TITLE
Settings custom expression like ">" or "<3

### ISSUE THREAD

**Issue by Cohorte7000** [metabase/metabase#13453]
Dear all,

I'm have Metabase V0.34.1, when I try to use custom expression like superior or inferior I can't obtain a result.

For exemple I compare two dates datas and I want to chek if one date is inferior as second date.

Like this Count (Case [datadate1] < [datedate2].

Someone can help me?

Best regards

**Comment by flamber** [comment]
Hi @Cohorte7000 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://www.metabase.com/blog/custom-expressions/index.html
Latest release is 0.36.7
