### ISSUE TITLE
IE11 CSV and XLS exports don't work

### ISSUE THREAD

**Issue by jhackett1** [metabase/metabase#13451]
**Describe the bug**

When I try to export/download any data using IE11, I get an error.

When I try to download a CSV or JSON, I'm asked if I want to open or save it, and then I get IE's "This file couldn't be downloaded" message right away.

When I try to download a XLSX, I am asked for credentials in a browser prompt. Nothing works here, including my metabase username and password.

**To Reproduce**
1. Go to any database table in IE11
2. Try to download full results in any format

**Expected behavior**
I can download things!

**Information about your Metabase Installation:**

- Internet Explorer 11.508.19041.0
- Windows 10
- Metabase v0.35.3

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1078-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4 (Ubuntu 12.4-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-21",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "GMT"
    }
  }
}
```

**Severity**
In a legacy/enterprise environment many users are likely to be using IE11.

**Comment by flamber** [comment]
Hi @jhackett1 
Please try the latest release, 0.36.7 - make sure to backup before upgrading.
There is no browser credential prompts in Metabase, so it sounds like you're using some proxy.
Most enterprise environments have moved to the new Edge (Chromium), since many websites don't work properly in IE11 anymore - even Microsoft's own web services will stop supporting IE11 from November.
