### ISSUE TITLE
Questions with joins causes re-run overlay after first save

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13468]
**Describe the bug**
When creating a question with joins, then after clicking Save, the re-run overlay (Play-button) will be shown.

**To Reproduce**
1. Custom question > Sample Dataset > Orders join People and click Visualize
![image](https://user-images.githubusercontent.com/1447303/95988254-ee094e00-0e28-11eb-880b-5cc0bb16f9f9.png)
2. Save question, anywhere, and click "Not now", when asked if the question should be added to a dashboard
3. Now the re-run overlay is shown, and will run the query again if the Play-button is clicked
![image](https://user-images.githubusercontent.com/1447303/95988046-979c0f80-0e28-11eb-88e5-c3172b9ef840.png)

**Expected behavior**
After clicking Save on a question, it's expected to continue to show that state and not requiring re-run of the query again.

**Information about your Metabase Installation:**
Metabase 0.35.4, 0.36.7, 0.37.0-rc2

**Additional context**

**Comment by kulyk** [comment]
Can also reproduce the problem with filters. Steps to reproduce:
