### ISSUE TITLE
Not able to do MBQL to native conversion using api

### ISSUE THREAD

**Issue by ManaanAnsari** [metabase/metabase#13467]
POST request on "/api/dataset/native" gives a 500 response error
`
query = '{"database": 3, "query": {"source-table": 26}, "type": "query"}'
print(mb.post('/api/dataset/json',params={"query":q}))

`

searched a lot but was not able to find the solution 
but I found this on GitLab [here](https://git.xyser.com/Test/metabase/-/blob/36f4d33a1931ecb9aef6e9f5251accf80beeabcd/src/metabase/api/dataset.clj)
![image](https://user-images.githubusercontent.com/47239133/95984316-a0004480-0e40-11eb-925a-7ea3df665d13.png)

not able to find endpoint "/api/dataset/native" is this endpoint deprecated?

other endpoints of "/api/dataset/" are working fine

**Comment by flamber** [comment]
Hi @ManaanAnsari 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apidatasetnative
