### ISSUE TITLE
Error connecting SSL secured database / "No matchin clause"

### ISSUE THREAD

**Issue by revivepaul** [metabase/metabase#13466]
**Describe the bug**
I am struggling to connect our SSL protected database to metabase. With our testing db (that is not ssl protected) everything works perfectly. The live db does not, however with the same credentials I can connect to it via DBeaver.

**Logs**
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.186-146.268.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-30",
      "tag": "v1.36.6.4",
      "branch": "enterprise-release-1.36.6.x",
      "hash": "4ad7c1c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**To Reproduce**
1. Go to '[user].metabaseapp.com/admin/databases'
2. Click on 'Add database'
3. Enter all asked details, here ours (replace real data with placeholders): https://i.imgur.com/23xbCXo.png
4. See error: https://i.imgur.com/tfGjNLM.png

**Expected behavior**
I would expect the database to be conneted succesfully. It however does not.

**Screenshots**
- See a few screenshots abover
- Maybe this setting is the problem: https://i.imgur.com/2HZKG1f.png (as set in the screenshot we connect via DBeaver. Maybe Metabase is expecting more data?

**Severity**
This is blocking our usage of Metabase entirely, we are not able to get to our live data.

**Additional context**
On our first attemps we assumed it might be due to special chracters in the passwort. We changed it temporarily to only letters and numbers. Error still occured.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.186-146.268.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-30",
      "tag": "v1.36.6.4",
      "branch": "enterprise-release-1.36.6.x",
      "hash": "4ad7c1c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @revivepaul 
Which version of MySQL are you using?
You should be able to see more details in Admin > Troubleshooting > Logs.
Your DBeaver configuration is set to not validate the SSL, which is why it probably works.
Have a look at possible ways of getting access without the certificate: https://github.com/metabase/metabase/issues/12545#issuecomment-629320966
But since you're using Metabase Cloud, then it's currently not possible to upload a certificate, so that would require #1350 to be implemented for that to work.

**Comment by jonasbrenig** [comment]
@flamber Would it be easier to implement the checkbox, so that we can ignore the validation of the server certificate rather than implementing #1350?

**Comment by flamber** [comment]
@jonasbrenig That will likely not be something that will be implemented. There isn't much sense in using SSL if you aren't validating. But you can add `allowPublicKeyRetrieval=true` to Connection String and then it should work.

**Comment by jonasbrenig** [comment]
I see your point, will decide on that shortly.
Maybe we then rather host it ourselves to be secure.

Thank you :)

**Comment by flamber** [comment]
Closing this, since it's covered by other issues.
