### ISSUE TITLE
Labels on Data Visualizations are Cut Off

### ISSUE THREAD

**Issue by cdc1996** [metabase/metabase#13471]
**Describe the bug**
Labels on data visualizations are cut off. Issue on metabase/metabase-enterprise:v1.36.7

**Expected behavior**
Can clearly see the full label.

**Screenshots**
![Screen Shot 2020-10-14 at 8 39 03 AM](https://user-images.githubusercontent.com/4802190/96012616-22651600-0df9-11eb-840b-b5070843d6c7.png)

**Information about your Metabase Installation:**
- Your browser and the version: Chrome/86.0.4240.75
- Your operating system: OS X 10.15.7
- Your databases: Postgresql
- Metabase version: metabase/metabase-enterprise:v1.36.7
- Metabase hosting environment: Docker
- Metabase internal database: Postgresql

**Severity**
Medium severity.

**Comment by flamber** [comment]
Hi @cdc1996 
Please use the support email, when using the Enterprise Edition. I have created an internal issue (592).
