### ISSUE TITLE
Email "Join Now" link is missing protocol (affects HTTPS only)

### ISSUE THREAD

**Issue by shaneog** [metabase/metabase#1348]
When running as HTTPS only, the URL sent to the new user is missing the protocol, and therefore doesn't work at all.
The user needs to manually insert "https://" in front of it in their browser.

Perhaps there should be a setting in the admin which specifies "HTTPS only" and this is checked when building URLs.

*Note: I'm running on Elastic Beanstalk to I can't add a server redirect*

**Comment by agilliland** [comment]
The base url for the application is actually editable on the site administration page.  Just click on the `Admin Panel` link in the dropdown under you initials in the top right and it's on the first page there under `SITE URL`

<img width="888" alt="screen shot 2015-10-23 at 8 16 09 am" src="https://cloud.githubusercontent.com/assets/1987787/10696764/9f2f2304-795e-11e5-81fb-7c95b088227e.png">

We auto detect this value when the instance is first created but after that it needs to be modified manually.  So it's most likely that when you first accessed your new instance you did it over http.  In any case, that's the url that's used when forming the links in the emails.

**Comment by shaneog** [comment]
Awesome, thanks!
