### ISSUE TITLE
Not possible to position Y-axis if there's only one series

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13487]
**Describe the bug**
When there's only a single series, then the "Which axis" is hidden in the visualization Settings > Display.
The workaround is to manually add another series, define the position of the original series, and then remove the added series.

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Summarize > Count by CreatedAt:Year
3. Visualization Settings > Display - it's not possible to change Y-axis position
![image](https://user-images.githubusercontent.com/1447303/96119382-2f633180-0eed-11eb-892f-4d2eaafa193f.png)
4. Summarize > add another metric Average of Discount
5. Visualization Settings > Display - Y-axis can now be set under "Which axis?" by expanding the series - try setting Count to Right
![image](https://user-images.githubusercontent.com/1447303/96118952-8caab300-0eec-11eb-8bea-c76fed9430dd.png)
6. Summarize > remove Average of Discount - it will still show Y-axis on the right side of the chart, but it's not possible to change it back
![image](https://user-images.githubusercontent.com/1447303/96119258-0478dd80-0eed-11eb-8fc9-533e1f49aa18.png)

**Expected behavior**
Allow setting Y-axis position also for single-series, so it can be used on dashboards, where there's a back-to-back line up or certain types of axis should always be shown on a specific side.

**Information about your Metabase Installation:**
Metabase 0.34.3, 0.36.7 and 0.37.0-rc2

**Additional context**
https://discourse.metabase.com/t/place-y-axis-in-the-right-side-of-the-chart/12001
Related to #3897

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/15492
