### ISSUE TITLE
0.37.0-rc2: Linked filter showing all values (not filtering)

### ISSUE THREAD

**Issue by petrusgomes** [metabase/metabase#13491]
**Describe the bug**
The new feature "Linked filters" is returning all values, instead of the filtered ones, when the filtered field is configured to "show a list of all values" in the Admin. The API is called to filter results and the response is correct, with only the filtered values. But the widget shows all values.
Although the admin option is called "show a list of all values", I'd expect the linked filter to override this behaviour.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
Steps to reproduce the behavior (Sample database):
1. Create an SQL query with 2 filters (product and review)
~~~sql
SELECT *
FROM PRODUCTS
    JOIN REVIEWS ON PRODUCTS.ID = REVIEWS.PRODUCT_ID
WHERE {{product}} AND {{location}}
~~~
2. Create a panel with the created query
3. !Important! Configure PRODUCTS.ID and REVIEWS.ID to "show a list of all values" at "Filtering on this field" Admin
4. Add both filters to the panel and set "review" filter as linked to "product"
5. Filter by product 3
6. Click on "review" filter and see all values (should see only a few linked to the product)

**Expected behavior**
Widget should show only filtered values

**Screenshots**
Values shown:
![Captura de Tela 2020-10-15 às 11 15 30](https://user-images.githubusercontent.com/3369552/96141822-c58c5d00-0ed7-11eb-9e10-bbab82c814d4.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 86
- Your operating system: (OS X 10.15
- Your databases: Postgres
- Metabase version: 0.37.rc2
- Metabase hosting environment: Jar-file on Mac OS X
- Metabase internal database: H2 (default)

**Severity**
blocking some users

**Additional context**

**Comment by okcomputerik** [comment]
I've also tried 0.37 rc2 with the Sample Dataset and the filter still shows all values when applying other filters. When I select a State the City values should only display the values corresponding to that State, right? Well, I get the exact same values for all states. Now, I'm no expert in US geography, but I think that points to an issue...

![metabase](https://user-images.githubusercontent.com/3380165/96143471-67756f00-0f03-11eb-8bb3-38525e078b17.gif)

I'm running the jar file on Fedora 32 (5.8.13-200.fc32.x86_64) and Firefox 81.0.1.

Cheers!

**Comment by paulrosenzweig** [comment]
@okcomputerik what's the "Filtering on this field" value for City?

I see the issue for the "A list of all values" option there, but if your City field isn't set that way maybe there's something else going on.

**Comment by okcomputerik** [comment]
@paulrosenzweig I just checked and it seems it was my bad. I had taken for granted that all filters would be linked automatically, not that you had the option to link just some (or all of them), which is way more flexible! I've set up the filters in different ways  now and it all seems to be working properly! 

BTW the new UI is very smooth and more intuitive. Nice work overall!!

Sorry for the false alarm!

**Comment by vitobotta** [comment]
> @paulrosenzweig I just checked and it seems it was my bad. I had taken for granted that all filters would be linked automatically, not that you had the option to link just some (or all of them), which is way more flexible! I've set up the filters in different ways now and it all seems to be working properly!
> 
> BTW the new UI is very smooth and more intuitive. Nice work overall!!
> 
> Sorry for the false alarm!

HI! Can you please clarify how you set up the linked filters? I am new to Metabase and am having the exact same issue right now. Thanks!

**Comment by flamber** [comment]
@vitobotta https://www.metabase.com/learn/dashboards/linking-filters.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by vitobotta** [comment]
> @vitobotta https://www.metabase.com/learn/dashboards/linking-filters.html Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

Apologies, will ask there next time. Thanks :)
