### ISSUE TITLE
Your question took too long - Metabase v0.36.7 on MacOS Catalina against MySQL 8.0.21

### ISSUE THREAD

**Issue by dgindin-cp** [metabase/metabase#13493]
All of my long queries end in "Your question took too long" after 60 seconds.

Metabase log shows:
:status :failed,
:class java.sql.SQLTimeoutException,

I tried setting Mac environment variable, MB_JETTY_ASYNC_RESPONSE_TIMEOUT=1800000, but it is not being honored by Metabase.

Any ideas?

Thanks!

**Comment by flamber** [comment]
Hi @dgindin-cp 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It's probably a reverse-proxy, load-balancer or something else closing the connection. See #12423 for more details.
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Comment by dgindin-cp** [comment]
I am running the MacOS version of Metabase on a MacOS laptop against a locally installed mySQL database via localhost, so there are no networking components involved that could be closing the connection. Any other ideas?

**Comment by flamber** [comment]
@dgindin-cp Make sure that your database doesn't close the connection. Check the connection variable by running this query:
`SHOW VARIABLES LIKE "%timeout%";`

**Comment by dgindin-cp** [comment]
SHOW VARIABLES LIKE "%timeout%";

output below. Would any of these timeout settings cause the 60 second timeout for my Metabase queries?

|Variable_name                                                   |Value                                                                                               |
|----------------------------------------------------------------|----------------------------------------------------------------------------------------------------|
|connect_timeout                                                 |10                                                                                                  |
|delayed_insert_timeout                                          |300                                                                                                 |
|have_statement_timeout                                          |YES                                                                                                 |
|innodb_flush_log_at_timeout                                     |1                                                                                                   |
|innodb_lock_wait_timeout                                        |50                                                                                                  |
|innodb_rollback_on_timeout                                      |OFF                                                                                                 |
|interactive_timeout                                             |28800                                                                                               |
|lock_wait_timeout                                               |31536000                                                                                            |
|mysqlx_connect_timeout                                          |30                                                                                                  |
|mysqlx_idle_worker_thread_timeout                               |60                                                                                                  |
|mysqlx_interactive_timeout                                      |28800                                                                                               |
|mysqlx_port_open_timeout                                        |0                                                                                                   |
|mysqlx_read_timeout                                             |30                                                                                                  |
|mysqlx_wait_timeout                                             |28800                                                                                               |
|mysqlx_write_timeout                                            |60                                                                                                  |
|net_read_timeout                                                |30                                                                                                  |
|net_write_timeout                                               |60                                                                                                  |
|rpl_stop_slave_timeout                                          |31536000                                                                                            |
|slave_net_timeout                                               |60                                                                                                  |
|wait_timeout                                                    |28800                                                                                               |

**Comment by flamber** [comment]
@dgindin-cp There's several that are 60 seconds, so I would guess yes. Try another client with the same queries. You should also have timeouts there.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by dgindin-cp** [comment]
I copied the Metabase-generated SQL script and ran it against the mySQL database using DBeaver database client version 7.2.2.202010041557. It completed successfully in 4.5 minutes. I did not modify any of the mySQL timeout variables.

The timeout appears to be happening within Metabase. I'm guessing within its bundled mysql database client code.

Any more ideas?

Thanks for your help. :)
