### ISSUE TITLE
Cannot drill-through "View these ..." when aggregated results are filtered

### ISSUE THREAD

**Issue by culturedev** [metabase/metabase#13504]
**Describe the bug**
This setup
![image](https://user-images.githubusercontent.com/5941039/96227361-4e68ce80-0f94-11eb-97b8-ec857d8dd055.png)

Throws this error
![image](https://user-images.githubusercontent.com/5941039/96227438-680a1600-0f94-11eb-8b9b-9f767af62e7e.png)

When Viewing (drilling down to) Details:
![image](https://user-images.githubusercontent.com/5941039/96227613-a69fd080-0f94-11eb-971e-a0ce3da01423.png)

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
Value does not match schema: {:query {:filter (named [nil nil nil (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses")] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment")}}

**To Reproduce**
1. Create question as outlined above
2. Drill down with "View these" as shown above

**Expected behavior**
List of detail records If I take away filter in "Filter" section (see above) then it work.s

**Screenshots**
See above

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 86.0.4240.75
- Your operating system: Docker on Debian 10
- Your databases: SQL Server (for source) 
- Metabase version: v0.36.6
- Metabase hosting environment: Docker on Debian 10
- Metabase internal database: MySQL

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Is a show stopper for this application scenario

**Additional context**

**Comment by flamber** [comment]
Hi @culturedev 
Please post the full stacktrace from Admin > Troubleshooting > Logs.
I don't understand the steps-to-reproduce. You say it produces an error, but how are you then using "View these ..." drill-through?
Can you reproduce with Sample Dataset?

**Comment by culturedev** [comment]
Hi @flamber 
Thanks for getting back so quickly. Here is the repro with the Orders table from the Sample Dataset:

1. Build this question:
![image](https://user-images.githubusercontent.com/5941039/96258246-fe9dfd80-0fbb-11eb-85bd-ef0819a8dc32.png)

2. Visualize as Graph
![image](https://user-images.githubusercontent.com/5941039/96258363-360caa00-0fbc-11eb-93bf-15d1cc6d1a7f.png)

3. Click on "View these Orders"

4. This is the result:
![image](https://user-images.githubusercontent.com/5941039/96258454-58062c80-0fbc-11eb-84ca-6864ff60ed5c.png)

Detail of error message:
Value does not match schema: {:query {:filter (named [nil nil nil (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses")] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment")}}

[Issue13504_Stacktrace1.txt](https://github.com/metabase/metabase/files/5391532/Issue13504_Stacktrace1.txt)

**Comment by flamber** [comment]
@culturedev Excellent! Reproduced on 0.34.3, 0.35.4, 0.36.7 and 0.37.0-rc2. Feels a little related to #13289.

It can be simplified even more:
1. Custom question > Sample Dataset > Orders - Summarize Count by CreatedAt:Month and then filter by Count>0
![image](https://user-images.githubusercontent.com/1447303/96271714-7de7fd00-0fcd-11eb-89ac-79312c3fe2d6.png)
2. Click any line point > "View these Orders"
![image](https://user-images.githubusercontent.com/1447303/96271804-9d7f2580-0fcd-11eb-9b95-97126f8eb4ce.png)
3. Errors - **notice** the filter is missing name (which column it is referencing)
![image](https://user-images.githubusercontent.com/1447303/96272024-d9b28600-0fcd-11eb-82aa-447858d40486.png)

**Comment by nemanjaglumac** [comment]
^ This mention was made by mistake (I copy/pasted some PR description from a different PR) and pressed shift+enter by accident:
![image](https://user-images.githubusercontent.com/31325167/96766661-b75ca600-13db-11eb-8269-6aaeeb9ca0c0.png)

Unfortunately, GitHub doesn't remove it even after I edited the description.

**Comment by flamber** [comment]
Since 0.38.0, it's not even possible to click the "View these ..." - nothing happens. I don't know if the underlying query error still happens.
The browser console errors with:
```
Uncaught TypeError: Cannot read properties of null (reading 'field_ref')
    at f (dataset.js:48)
    at he (actions.js:156)
    at pe (actions.js:120)
    at e.value (Question.js:517)
    at Object.question (UnderlyingRecordsDrill.jsx:61)
    at y (action.js:32)
    at ChartClickActions.jsx:114
    at onClick (ChartClickActions.jsx:353)
    at Object.u (react-dom.production.min.js:14)
    at p (react-dom.production.min.js:14)
```

**Comment by ZZChaser** [comment]
Is there any solution？
