### ISSUE TITLE
Remove CSSBox dependency

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#13509]
# Background
[We currently use](https://github.com/metabase/metabase/blob/94218715f76470e1e9fbed772727c44d66098de9/project.clj#L109) a library called [CSSBox](https://github.com/radkovo/CSSBox).

<details>
<summary>It's used in two places:</summary>

```
$ ack cssbox src
src/metabase/pulse/render/image_bundle.clj
9:           org.fit.cssbox.misc.Base64Coder))

src/metabase/pulse/render/png.clj
5:  https://github.com/radkovo/CSSBox/blob/cssbox-4.10/src/main/java/org/fit/cssbox/demo/ImageRenderer.java with
8:  CSSBox JavaDoc is here: http://cssbox.sourceforge.net/api/index.html"
23:           [org.fit.cssbox.css CSSNorm DOMAnalyzer DOMAnalyzer$Origin]
24:           [org.fit.cssbox.io DefaultDOMSource StreamDocumentSource]
25:           org.fit.cssbox.layout.BrowserCanvas

```
</details>

1) Rendering pulses, which are written in HTML but turned into PNGs with CSSBox.
2) Base64-encoding an image ([which can be done with the stdlib in Java 8+](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Base64.Encoder.html#encodeToString(byte%5B%5D)))

# The Problem

There are two main issues. The first is that CSSBox has some rendering issues (such as #12526) and it's very hard to debug them. The second is that we're using Nashorn to doctor some of the HTML with Javascript, and Nashorn [will be removed in Java 15](https://openjdk.java.net/jeps/372).

# A Proposed Solution

We could port all pulse markup from HTML/CSS to SVG, and then use a library like [Apache Batik](https://xmlgraphics.apache.org/batik/) to conver the SVGs to PNGs.

## Upsides
* Saves us from having to fix inscrutable rendering bugs.
* Lets us remove our dependency on Nashron and support Java 15

## Downsides
* Porting all of our charts and tables to SVG is labor-intensive
* There will be less similarity between how charts/tables are rendered on the web and as pulses
* We'd send PNGs instead of HTML to emails, which raises some a11y concerns.

**Comment by robdaemon** [comment]
We can still send the HTML, with the images being PNG, can't we?

**Comment by paoliniluis** [comment]
Related to
https://github.com/metabase/metabase/issues/10749
https://github.com/metabase/metabase/issues/13881

**Comment by flamber** [comment]
Nashorn has been replace with GraalVM in #15708

**Comment by tsmacdonald** [comment]
Talked to @adam-james-v and this isn't planned
