### ISSUE TITLE
Dashboard filters are not refreshed on time with new values

### ISSUE THREAD

**Issue by saarwasserman** [metabase/metabase#13515]
**Describe the bug**
When storing ne data in DB it doesn't show up on the dashboard's filter.
Even when clicking the refresh button. it doesn't show.

I can't tell when the filters actually refreshed at some point. the values of the new data are seen in the filter value options.

**To Reproduce**
1. Store new data
2. click on the relevan filter field.

**Expected behavior**
See the new values of the field immediately  or after a  few seconds on startup or after refresh button click (even after 1 minute refresh duration)

**Information about your Metabase Installation:**
v0.36.4

**Comment by flamber** [comment]
Hi @saarwasserman 
Metabase only scans for field data once every day until a different scheduled:
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
