### ISSUE TITLE
msgfmt seems to be failing on osx

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#13513]
running `bin/build` is failing.

simplest repro: `msgfmt --verbose --java2 -d resources -r metabase.Messages -l es locales/es.po`

```shell
~/p/c/metabase ❯❯❯ msgfmt --verbose --java2 -d resources -r metabase.Messages -l es locales/es.po
msgfmt: Java compiler not found, try installing gcj or set $JAVAC
msgfmt: compilation of Java class failed, please try to set $JAVAC
3531 translated messages.
```
possible red herring: https://lists.gnu.org/archive/html/bug-gnulib/2013-09/msg00042.html  (related to temp files and Windows)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by xu20160924** [comment]
I am the same face to this problem on mac.

**Comment by jeff303** [comment]
Same problem here, too.  OS X Catalina with Homebrew.  Tried all of the following, based on random Googling (increasing order of desperation):

- Switched `JAVA_HOME` and `JAVAC` to Oracle JDK8 (instead of OpenJDK 8)
- Tried exporting `TMPDIR` to an empty value (as per [here](https://lists.gnu.org/archive/html/bug-gettext/2013-09/msg00016.html), although this is for Windows)
- Reinstalled `gettext` through Homebrew as per [here](https://stackoverflow.com/a/58540416/375670)
- Tried installing Oracle JDK 7 for OS X and switching `JAVA_HOME`/`JAVAC` to that

It also seems that neither `-v` nor `--verbose` options actually have any observable impact when running `msgfmt`.  So for now, I just skipped that step in the build process.

**Comment by camsaul** [comment]
@rlotun and I were both running in to this too on macOS. Works fine for me on Windows/WSL2 as well as our Ubuntu and Alpine Linux Docker images we use for CI and DockerHub.

I got it working on macOS by manually building `gettext` from source.

Either way, this isn't a bug with Metabase -- I'd suggest opening an issue with `gettext` or Homebrew

**Comment by jeff303** [comment]
Definitely agreed it's not a Metabase issue. I still wonder if it would be useful to have a wiki page or something similar to document such known vagaries? People on OS X are quite likely to be using homebrew versions of stuff.

**Comment by rumly** [comment]
I have the same problem. Have you solved it now? @camsaul @jeff303

**Comment by ezecruzavila-meli** [comment]
Same problem here. Any fixes?

**Comment by jeff303** [comment]
I haven't figured out how to fix this for OS X yet. There was a suggestion to build gettext from source, but I tried that and it didn't work for me. For now, I'm just skipping this step when it fails in the build. If I figure out a solution then I'll update this issue accordingly.

**Comment by gubatron** [comment]
same problem over here, tried going back to OpenJDK 8 to see if it would help to no avail.
Issue happens in macOS Big Sur 11.1 (0.21), also on Windows 10 (gettext 0.19.8.1 ) and in Ubuntu Linux (gettext 0.19.8.1)

**Comment by camsaul** [comment]
I lost my source code changes but to get it working I think I just commented out the code that attempts to compile a file with `javac`, or maybe I changed it to compile targeting Java 8 instead of Java 5 or whatever it currently targets. Try those changes

**Comment by mizhou901101** [comment]
Here is OS X too. I solved it by executing 
`export JAVAC=/usr/bin/javac`
in the command line which was asked in the error message like below:
```
Step failed: Compiling locales/zh.po for frontend...
msgfmt: Java compiler not found, try installing gcj or set $JAVAC
msgfmt: compilation of Java class failed, please try --verbose or set $JAVAC
```

**Comment by kovzol** [comment]
I updated homebrew's gettext from 0.21 to 0.22.4 and now it works.

**Comment by gubatron** [comment]
WOHOO!!!

**Comment by gubatron** [comment]
worked!
