### ISSUE TITLE
0.37.0-rc2: Monday week start displays incorrectly on bar chart

### ISSUE THREAD

**Issue by dah33** [metabase/metabase#13516]
**Describe the bug**
I set my localization to Monday week start in 0.37.0rc2 (excited about #1779), but I see:

![image](https://user-images.githubusercontent.com/17231347/96422498-fe864380-11ef-11eb-9d2f-50be565e0014.png)

The date range on the tooltip is correct (14th September is a Monday), but the bar has attributed it to Sunday 13th September. I also note the centering is not quite right.

**To Reproduce**
1. Change localization to Monday week start
2. Make a report that groups by Week start

**Expected behavior**
Bar should show 14th September.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_261-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_261",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.261-b12",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.0-rc2",
      "date": "2020-10-07",
      "branch": "master",
      "hash": "1f52afa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
I have a feeling that it's very related to #11319, because it's only the ticks/labels that aren't correct, but the tooltip is. And the workaround of changing "X-axis scale" from Timeseries to Ordinal also works here.

**Steps to reproduce:**
1. Admin > Settings > Localization > Start of week = Monday
2. Simple question > Sample Dataset > Orders
3. Filtering CreatedAt before June 1st 2016
4. Summarize Count by CreatedAt:Week
![image](https://user-images.githubusercontent.com/1447303/96427006-4f9d3400-11fe-11eb-90b3-d82c525db308.png)

**Comment by dah33** [comment]
Confirmed, changing to "Ordinal" works for me, also fixes the centering issue.

**Comment by flamber** [comment]
@dah33 The centering of the text isn't really centering as much as it's showing a tick label for each point. That's unrelated to this issue, but covered in #12684/#12699

**Comment by nemanjaglumac** [comment]
Note:
Cypress repro for this issue has been included directly in the PR that will fix it. This is a bit different workflow than usual - just wanted to make it clear :)
