### ISSUE TITLE
provide an `Admin Email` global setting

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1351]
This would be used as a way to provide a central communication point throughout the application if something goes wrong and the best course of action is for the user to notify the maintainer of the system.  In the short term we can just grab the first admin account we find from the db, but that's fairly limiting.  

Ideally we'd set this automatically at initial setup (to the email of the first user) and then let the admin manually edit it any time after that and put in any email address they want, including aliases or other values which may not map to a user of the system.

**Comment by salsakran** [comment]
:+1:

**Comment by tlrobinson** [comment]
> In the short term we can just grab the first admin account we find from the db

FYI that's what I'm doing here: https://github.com/metabase/metabase/pull/1245/files#diff-4d8c7d86cbdad7c171e856faf99ed1e7R167

**Comment by agilliland** [comment]
yep, that's where that comment came from :wink:

the main point of this issue is to suggest that we should expand upon that approach and allow an admin to specifically pick any email address they want to use as the official `Admin Email` rather that just grabbing the email of some admin user.
