### ISSUE TITLE
UX fixes for database management

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1353]
* [x] On the add/edit database form, when there's already an error message next to the Save button, if the user clicks the Save button again, the old error message should fade out and the new one should fade in, **even if the error message strings are identical**. This will give the user the implicit feedback that Metabase did in fact check the input again.
* [ ] When a user is creating a **new** database and has selected a database type, and then put **any** content into **any** of the other form fields, and then attempts to navigate away from the DB creation page, they should receive a modal warning that says, "Are you sure you want to leave this page? Your changes will be lost. [Yes/No]"
* [ ] When a user is **editing** an **existing** DB, if they make any changes to any of the fields and then attempt to navigate away before clicking Save, then should receive a modal warning that says, "Are you sure you want to leave this page? Your unsaved changes will be lost. [Yes/No]" This string is nearly identical to the one in the above bullet, but with the addition of the word, "unsaved."
* [x] Right now, when a user attempts to delete a database from the list of databases in the admin panel, they are presented with a system default modal. Instead, they should be presented with one of our styled modals that says, "Are you sure you want to delete this database? All saved questions that rely on this dashboard will be lost. **This cannot be undone.** If you're sure, please type **DELETE** in this box. [input field] [Delete / Cancel]" (I'll create a mockup.)
* [x] When a user adds a new database and clicks Save, they should be taken back to the list of databases view and see this modal:

![database_added](https://cloud.githubusercontent.com/assets/2223916/10702037/e82cd872-797b-11e5-92c9-7974092a0bce.png)

**Comment by mazameli** [comment]
Lemme know if all this looks good to you, too, @kdoh.

**Comment by agilliland** [comment]
I've moved the remaining couple of tasks on this over to a separate issue #1477 to be done at a separate time as they are lower priority.  I'm going to go ahead and close this issue as completed.
