### ISSUE TITLE
Export to CSV/XLSX/JSON from dashboard cards

### ISSUE THREAD

**Issue by matheusmorett2** [metabase/metabase#13546]
**Is your feature request related to a problem? Please describe.**
CSV Export

**Describe the solution you'd like**
CSV Export button at dashboard questions

**Additional context**
<img width="550" alt="Screen Shot 2020-10-20 at 20 28 55" src="https://user-images.githubusercontent.com/24697383/96655069-02f74d00-1313-11eb-8f53-e1391bdf59bb.png">

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
This is possible with Embedded dashboards - and there's a request for Public dashboards too #6687
Related to #6369

**Comment by matheusmorett2** [comment]
Ok thanks =)

**Comment by paoliniluis** [comment]
This was introduced in v46
