### ISSUE TITLE
Ability to change the padding around item names

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#13545]
For me the current padding around items is too much and not enough items fit in the display. It would be nice to be able to change this in the admin panel (also be able to change the size of the 3x3 icon to the left of each row).

![padding](https://user-images.githubusercontent.com/15974735/96652360-96b52300-12eb-11eb-9bd5-127fb5f84b1f.png)

**Comment by mazameli** [comment]
It's super unlikely we'd ever provide a setting to precisely customize this spacing, though I suppose I could imagine something along the lines of Gmail's `Default`/`Comfortable`/`Compact` list view setting.

Falling short of that, I thought I'd mention that we're looking at making some revisions to the layout and design of Collections, and the current designs are a bit more compact. You can see in this example that 6 items are now able to fit in the same area as only 5 were able to previously fit (new on left, current on right):

<img width="719" alt="Screen Shot 2020-10-26 at 1 59 02 PM" src="https://user-images.githubusercontent.com/2223916/97227942-6f4ed200-1793-11eb-84fd-411a9db73f36.png">

**Comment by vvaezian** [comment]
I like your idea of having sth like `Default/Comfortable/Compact`. It would be nice if its effect gets applied to permissions tab as well. The boxes are big currently.

![perms](https://user-images.githubusercontent.com/15974735/97488881-13fc1b80-191c-11eb-9741-9d2cd04a475b.png)

**Comment by flamber** [comment]
Closing, since 0.42.0 implemented a might more compact listing:
![image](https://user-images.githubusercontent.com/1447303/164545543-43c05fbc-febc-4a84-b228-0f9356019fd2.png)
