### ISSUE TITLE
Support SSL/TCPS for Oracle database

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13552]
Currently it's not possible to enable SSL for Oracle connections like it is for most other connections.

Having a way to include the certificate instead of using KeyStore is preferable - like what was done on #3877.
Otherwise the full connection string is needed, so it's possible to set `PROTOCOL`, `SECURITY` etc.

Related to #1350 (and perhaps #13431)
https://blogs.oracle.com/dev2dev/ssl-connection-to-oracle-db-using-jdbc,-tlsv12,-jks-or-oracle-wallets

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jeff303** [comment]
There are a lot of different modes and options available for this (full details are available [here](https://www.oracle.com/technetwork/database/enterprise-edition/wp-oracle-jdbc-thin-ssl-130128.pdf)).  We should figure out which of these we want to implement.  "Everything" is a valid answer, but of course it will increase the time required for development.

SSL use cases:

1. Encryption only
2. Encryption + server auth (client authenticates identity of the server)
3. Encryption + mutual auth (client authenticates identity of the server, and vice versa)
4. SSL DB auth (the DB user, not only the client connection, is authenticated by SSL certificate, in lieu of username/password)

Another dimension, in addition to the above, is the type of trust store, which can either be JKS or Oracle Wallet (#13431).
