### ISSUE TITLE
improve Metabase loading page visualization

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1355]
following on from #1212 the goal is to improve on the simple progress bar visualization and do something a bit nicer looking.  @mazameli @kdoh can you guys post your thoughts here on what we should do?

**Comment by mazameli** [comment]
Yeah, thanks for the ping. Chatted with Tom real briefly about this earlier this morning; just need to come up with a design real quickly.

**Comment by mazameli** [comment]
Here's what I came up with.

## CSS for unfilled bar: 
`background: #DBE9FA;
border-radius: 8px;
width: 200px;
height: 5px;`

## Filled bar is the same, with different bg color:
`background: #4A90E2;`

## Positioning:
The logo, bars, and text are all in one box, which as a whole is vertically and horizontally centered.
The bars are 75px below the logo.
The text is 15px below the bars.
The logo is 94px wide by 116px tall.

## Copy:
The text should be chosen randomly from the list below when the loading starts, and should change to a different one from the list randomly after the 50% mark:
* Polishing tables…
* Scaling scalars…
* Straightening columns…
* Embiggening data…
* Reticulating splines…


![heroku_loading_screen](https://cloud.githubusercontent.com/assets/2223916/10741774/a72f281c-7be6-11e5-8444-3d3a2ef74c04.png)

**Comment by kdoh** [comment]
:+1:

**Comment by tlrobinson** [comment]
@mazameli a SimCity fan, I see...
