### ISSUE TITLE
Dashboard Field Filters Don't AutoComplete/Search When Linked to a Question in Native SQL.

### ISSUE THREAD

**Issue by rgaudon** [metabase/metabase#13550]
**Describe the bug**
If a dashboard contains a field filter such as `Name`, and that name is referenced in a native sql query question by means of `{{Name}}`, the field will revert from searching/auto completing to a standard input box which removes the usefulness of the feature. 

**Logs**
N/A

**To Reproduce**
1. Write a native SQL query that uses a field markdown reference {{cat}}
2. Add the question to a dashboard that contains a field filter.
3. Associate the dashboard field filter to a GUI created question.
4. Notice the Search/Autocomplete behaviour.
5. Associate the same dashboard field filter with the Native SQL question.
6. Notice the dashboard field filter no longer has the ability to search / autocomplete.

**Expected behavior**
The field filter would retain the ability to search / auto complete values.

**Screenshots**
N/A

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Browser: Firefox 82.0
- Operating System: Windows 10
- Database: MySQL/MariaDB
- Metabase Version: 0.36.7
- Metabase hosting environment: Elastic Beanstalk/Docker
- Metabase internal database: Default

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
I would classify this `blocking some users` and by extension blocking our usage of metabase as it's maintained for those users. The majority of our metrics are relatively complex to compute and are written in native sql, and linked to from salesforce contacts. In this way, the autocomplete fields can be pre-populated using query params, which is fantastic. The problem is when sales team members want to browse a dashboard (in metabase) of contact specific metrics where by the search parameters are either an email address or an entity name (non-contact based dashboard, other entities). Without autocomplete + the substring matching bug, it be impossible for them to filter the dashboard for the information they are looking for with respect to a specific user or identifying string.

**Additional context**
Nothing at this time

**Comment by flamber** [comment]
Hi @rgaudon 

I cannot reproduce based on your steps, since it's specific to your data instead of Sample Dataset.

Whichever field `{{Name}}` is referencing in the Data Model, the type of widget will depend on what it's set to:
https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#picking-the-filter-user-interface-for-a-column

When you're viewing the field in Data Model, then the URL looks like this `/admin/datamodel/database/4/table/11/83/general`, where the field ID is `83` - change the URL to `/api/field/83` and paste the information here (redact sensitive data where needed).

**Comment by rgaudon** [comment]
I'll post some images depicting the issue, the {{Name}} field in both the native query, and the GUI created query, are the same column.

1. Associating an Email field on a sample Users table whereby Email has been reclassified from type `email` to work with dashboard field filters (existing metabase bug on Emails).
![1](https://user-images.githubusercontent.com/72467826/96715941-e55fcd00-137e-11eb-9824-b8bedf99b20f.png)

2. Autocomplete / Search on field working correctly.
![2](https://user-images.githubusercontent.com/72467826/96716015-0a544000-137f-11eb-823a-6b6b90c15daa.png)

3. Creating a second association to a native users sql query.
![3](https://user-images.githubusercontent.com/72467826/96716039-12ac7b00-137f-11eb-9cd6-d568407ec441.png)
`select users.id, users.email from users where users.email like {{Email}}`

4. As the email is entered, auto-complete and search is no longer present.
![4](https://user-images.githubusercontent.com/72467826/96716132-2d7eef80-137f-11eb-88b1-b7ad987d5878.png)

Perhaps I'm doing something wrong here, and if so I apologize, but this isn't the behavior I was expecting when creating another association for text field from an equivalent GUI created question vs Native.

**Comment by rgaudon** [comment]
`{
  "description": null,
  "database_type": "VARCHAR",
  "table_id": 13,
  "table": {
    "description": "Contains all system users.",
    "entity_type": "entity/UserTable",
    "schema": null,
    "db": {
      "description": null,
      "features": [
        "basic-aggregations",
        "standard-deviation-aggregations",
        "expression-aggregations",
        "foreign-keys",
        "right-join",
        "left-join",
        "native-parameters",
        "nested-queries",
        "expressions",
        "set-timezone",
        "binning",
        "inner-join",
        "advanced-math-expressions"
      ],
      "cache_field_values_schedule": "0 0 0 * * ? *",
      "timezone": "UTC",
      "auto_run_queries": true,
      "metadata_sync_schedule": "0 0 * * * ? *",
      "name": "REDACTED",
      "caveats": null,
      "is_full_sync": true,
      "updated_at": "2020-03-26T22:47:28.58Z",
      "is_sample": false,
      "id": 2,
      "is_on_demand": false,
      "options": null,
      "engine": "mysql",
      "created_at": "2017-10-03T17:00:17.457Z",
      "points_of_interest": null
    },
    "show_in_getting_started": false,
    "name": "users",
    "caveats": null,
    "updated_at": "2020-05-21T04:00:01.034Z",
    "entity_name": null,
    "active": true,
    "id": 13,
    "db_id": 2,
    "visibility_type": null,
    "field_order": "database",
    "display_name": "Users",
    "created_at": "2017-10-03T17:00:17.653Z",
    "points_of_interest": null
  },
  "special_type": "type/Category",
  "name": "email",
  "fingerprint_version": 4,
  "has_field_values": "search",
  "settings": null,
  "caveats": null,
  "fk_target_field_id": null,
  "dimensions": [],
  "updated_at": "2020-10-20T02:32:41.55307Z",
  "custom_position": 0,
  "active": true,
  "parent_id": null,
  "id": 343,
  "last_analyzed": "2019-11-01T13:51:04.196Z",
  "position": 0,
  "visibility_type": "normal",
  "preview_display": true,
  "display_name": "Email",
  "database_position": 1,
  "name_field": null,
  "fingerprint": {
    "global": {
      "distinct-count": 10000,
      "nil%": 0.0
    },
    "type": {
      "type/Text": {
        "percent-json": 0.0,
        "percent-url": 0.0,
        "percent-email": 0.9156,
        "average-length": 29.4635
      }
    }
  },
  "created_at": "2017-10-03T17:00:21.755Z",
  "base_type": "type/Text",
  "points_of_interest": null
}`

**Comment by flamber** [comment]
@rgaudon Okay, you're not using Field Filters, but just a simple Text filter.
Read this: https://www.metabase.com/blog/field-filters/index.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
