### ISSUE TITLE
Auto-redirect http uri to https based on site url in Metabase settings?

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#1356]
Hey there,

I just setup a Metabase instance via AWS ELB with SSL enabled. 
Super straightforward, awesome job!

Just wondering if you folks have considered a setup where:
1. HTTP traffic via port 80 is kept open in addition to HTTPS
2. The application examines the X-Forwarded-Proto header if available (http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html)
3. The application compares this header with the Site URL field in the Metabase settings
4. If there's a protocol mismatch (site url expects https, protocol of request was http) then you send the client a 301 redirect to the https version of the route immediately instead of attempting to handle the request over http.

That way clients could be gracefully redirected to the https version of a metabase instance if they accidentally type http or the bare (sub)domain.

Maybe there are other ways to achieve this, and maybe doing it at the application-level could be ill-advised?

Just wondering what the team's official stance on this is.

Could try to do a PR of an initial implementation if there's interest and it doesn't seem like a potential security vulnerability.

Thanks again,
Ethan

**Comment by brwr** [comment]
In my, admittedly limited, experience it is better to handle these things at the web server (Nginx) level.

**Comment by agilliland** [comment]
This is definitely a case where there's quite a few ways to do it and no specific "right way".  I am generally a fan of having the application be agnostic of things like this which are really infrastructure concerns rather than application concerns.

For Elastic Beanstalk specifically we actually have some code that goes into the `.ebextensions` folder in the EB deployment file which will allow this to be handled completely by nginx on the EB host.  All you will have to do is set an environment variable on your EB environment for `NGINX_FORCE_SSL=1` and it'll all work.

**Comment by sherbondy** [comment]
Awesome, agreed. Was quickly running through the code and didn't notice it was, in fact, already setup to run behind nginx. I think that's a better place to handle this as well. Closing now.

**Comment by tlrobinson** [comment]
I actually think this is a good idea given Metabase will be deployed in a wide variety of scenarios. One example where you don't have control over the infrastructure in front of the application server is Heroku.

At a minimum we should probably have an environment variable to enable this. A GUI setting is a little dangerous since if HTTPS isn't configured you could end up locking yourself (and everyone else) out of the application, but it should be possible to detect whether or not HTTPS is available.

**Comment by brwr** [comment]
Good point about Heroku.

Using an environment variable, as @tlrobinson mentioned, shouldn't introduce any performance penalty. That is, assuming the code reads something to the effect of `if ENVIRONMENT_VARIABLE: enable_https`.

**Comment by sherbondy** [comment]
Hmm, just tried this on EB, and it didn't work out. Feel like I'm missing something. 
Maybe this is just a matter of being new to EB, but @agilliland, do you mean that all I have to do is add an env var to Configuration -> Environment Properties and turn traffic on port 80 back on?

Or do you mean I will need to prepare a new release of Metabase and upload with the proper ebextensions included?

I'm having trouble even finding references to nginx in the entire source tree.
The Dockerfile in `aws-eb-docker` seems to just run run the jar.
Unless there's some base image other than `ubuntu:trusty` that gets pulled into the fold somewhere, maybe referenced by a hash in the source?

Likewise, the file in question: [http_redirect.config](https://github.com/metabase/metabase/blob/master/deploy/aws-eb-docker/.ebextensions/http_redirect.config) doesn't directly refer to the `NGINX_FORCE_SSL` env variable. Is there some intermediate file where I map ENV variables to these ebextension scripts?

**Comment by agilliland** [comment]
@sherbondy sorry to be confusing.  my comment above meant that we have the code but it's not in the repository yet, so it's coming as part of our next release.

**Comment by sherbondy** [comment]
I think this is resolved now!

**Comment by sherbondy** [comment]
One question: Does `NGINX_FORCE_SSL` conflict with the fact that the ELB setup pings an HTTP endpoint on port 80 for health checks?

**Comment by agilliland** [comment]
nope.  we are using this on several of our Metabase production instances and it's working as expected.

**Comment by KazW** [comment]
Just came across this, right now on v0.22.2, I have set the environment variable, then turned port 80 back on in the LB config, but not getting a redirect.

```
* Rebuilt URL to: http://host.something.com/
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to host.something.com (x.x.x.x) port 80 (#0)
> GET / HTTP/1.1
> Host: host.something.com
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: max-age=0, no-cache, must-revalidate, proxy-revalidate
< Content-Security-Policy: default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com js.intercomcdn.com *.intercom.io ; frame-src https://accounts.google.com; style-src 'unsafe-inline' 'self' fonts.googleapis.com; font-src 'self' fonts.gstatic.com themes.googleusercontent.com ; img-src * self data:; connect-src 'self' metabase.us10.list-manage.com *.intercom.io wss://*.intercom.io ;
< Content-Type: text/html; charset=UTF-8
< Date: Mon, 27 Feb 2017 17:23:26 GMT
< Expires: Tue, 03 Jul 2001 06:00:00 GMT
< Last-Modified: Mon, 27 Feb 2017 17:23:26 +0000
< Server: nginx/1.10.1
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Permitted-Cross-Domain-Policies: none
< X-XSS-Protection: 1; mode=block
< Content-Length: 12929
< Connection: keep-alive
<
<!DOCTYPE html>
<html lang="en" ng-app="metabase" class="no-js">
```

**Comment by KazW** [comment]
@sherbondy @agilliland Are there any docs for this? I'm trying to set this up, but am not getting http to redirect to https.

**Comment by txomon** [comment]
@agilliland In my company we just had a downtime because of that. Basically the NGINX_FORCE_SSL also redirects the health checks.

The problem why we didn't detect it the other day is that Environment Configuration changes are not happening once the instance has been launched, and are applied on new instances, making upgrades terrible.

@KazW this may be why. I recommend that after doing your configuration change, you instruct the autoscaling group to create a new instance, and delete the old one, only then you will be sure it gets applied.

**Comment by wvengen** [comment]
Did anyone succeed in doing a redirect from http to https on Heroku (based on the `X-Forwarded-Proto` header)? This [needs to be implemented at](https://kb.heroku.com/how-do-i-force-my-application-to-use-ssl-tls) the app side.

**Comment by wvengen** [comment]
Perhaps [`wrap-force-ssl`](http://stackoverflow.com/questions/30689577/clojure-wrap-ssl-redirect-on-heroku#30697601) (also [in lib-noir](https://github.com/noir-clojure/lib-noir/blob/master/src/noir/util/middleware.clj#L53)) may be of use here.

**Comment by infiniteluke** [comment]
Another option here is to use cloudfront


1. Leave the load balancer settings as is
![screen shot 2018-06-25 at 9 39 44 pm](https://user-images.githubusercontent.com/1127238/41889765-1d5a38fe-78c1-11e8-9447-ab04552f167d.png)
1. Create a new cloudfront distribution and select the load balancer as the orgin domain name
![screen_shot_2018-06-25_at_9_41_50_pm](https://user-images.githubusercontent.com/1127238/41889734-f3a49d6a-78c0-11e8-9dfb-75297582426f.png)
1. Enter the CNAME in the `Alternate Domain Names (CNAMEs)` field
1. Select Redirect HTTP to HTTPS
![screen shot 2018-06-25 at 9 45 10 pm](https://user-images.githubusercontent.com/1127238/41889758-13897e52-78c1-11e8-9bef-810c2bf88929.png)
1. Select the custom SLL Certificate you uploaded into ACM
![aws_cloudfront_management_console](https://user-images.githubusercontent.com/1127238/41889867-b48e79d8-78c1-11e8-8adb-32f675e3bf84.png)
1. Save
