### ISSUE TITLE
Multi-query endpoints for pivot tables

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#13573]
I'm opening this issue to sketch out a possible API extension. I discussed it with @sbelak. It sounds like this should meet our needs for implementing pivot tables and potentially open other interesting possibilities in the future.

## Pivot tables

In 0.38, we're adding pivot tables as a new visualization type. This will allow displaying data with breakout columns pulled into multi-tier row or column headers. It also has optional aggregation rows and columns.

![pivot ui](https://user-images.githubusercontent.com/691495/96902726-e1a57680-1462-11eb-940f-be5db021bd45.png)

The query that will be created by the user to display the above chart is:

```
{
  "aggregation": [["count"], ["sum", TOTAL]],
  "breakout": [STATE, SOURCE, CATEGORY]
}
```

✨ _The Problem_ ✨

The various subtotals make this problematic. To generate the data shown in the screenshot, we need to run four additional queries with the following breakouts:

* `[STATE, SOURCE]`
To show the "Totals for [Source]" rows.
* `[STATE]`
To show the "Grand totals" row on the bottom.
* `[SOURCE, CATEGORY]`
To show the "Row totals" columns on the right
* `[]`
To show the aggregates in the bottom right.

### Computing aggregates on the frontend

It'd be simplest to leave the API untouched and add these as part of the visualization. Unfortunately, this isn't practical.

Computing on these on the client works well for aggregates like "Count of rows" and "Sum of total". It breaks down a bit for "Average of total" where we need the associated count to do a weighted average of sub-averages. It seems likely impossible for aggregates like "95th percentile" or "std dev".

_Unimportant question: Is there a mathematical term for aggregations that can be applied to sub-aggregates?_

Even setting aside aggregates that don't apply over themselves, it'd be tedious and error-prone to have the client duplicate logic in custom expressions. The client might be able to compute aggregates for `3 * (sum(total) - sum(tax))`, but it shouldn't.

## API changes

The current thinking is to allow a single card to include multiple queries and produce multiple result sets. Essentially, we'd want something like the example below adding `additional_queries` and `additional_data`. Please suggest better names or placement within the JSON. 

```
POST /api/card

{
  name: "My Question",
  dataset_query: {
    database: 1,
    query: {source-table: 1},
    additional_queries: [{source-table: 2},  {source-table: 3}],
    type: "query"
  }
}
```

`GET /api/card/:id/query`

returns
```
{
  json_query: {
    database: 1,
    query: {source-table: 1},
    additional_queries: [{source-table: 2},  {source-table: 3}],
    type: "query"
  },
  data: {
    rows: [...],
    cols: [...],
    additional_data: [
      {rows: [...], cols: [...]},
      {rows: [...], cols: [...]}
    ],
  }
}
```

What I wrote out forces additional queries to be against the same database, which is probably desirable, but I think it's open for discussion. 

### Running the additional queries ad-hoc

Again, there's a simpler solution that's been ruled out: It'd be great if we could not change the API and use the ad-hoc querying API to run the additional queries. This approach breaks if the viewer lacks data permissions on the database.

### Other options

* Make this part of MBQL
Simon pointed out that having a single MBQL query split into multiple SQL queries breaks the "compiles to SQL" idea.
* Add an API option more specific to pivot tables
For pivot tables, the need is specific to dropping some breakouts. We could achieve that by adding an option for `alternate_breakouts`.
* Allow permissions for "derived" ad-hoc queries
We could hack around the permissions issues that block us from running these as ad hoc queries. e.g. "run this ad hoc query using my permissions for card 123", that would check that the ad hoc query is a "more aggregated" version of the card's query that matches filters and contains a subset of the breakouts.

**Comment by salsakran** [comment]
One thought -- if we hide this behind MBQL, we can optimize these sets of queries. Eg, for things like Sums, we could potentially construct totals from subtotals.

We'd almost certainly not want to do this for V1, but having the ability to optimize behind the scenes might be worth breaking the single mbql -> single sql abstraction.

**Comment by sbelak** [comment]
In retrospective and for completeness sake: as long as all the constituent queries have the same return shape (which they do in this case), we could just `UNION` them and add a field (eg. `__part`) to tell the rows apart. I don't think it's a particularly good idea though as it feels it will limit us down the line.

I like the multi-query approach as it opens up design space quite a bit. The biggest downside is that it's then on the FE to generate all the needed queries (although such MBQL transformations can easily also be a BE service).  

If we do a new pivot-specific endpoint, I think something like `/api/card/:id/pivot` and the equivalent for ad-hoc (or maybe have a new toplevel endpoint such as `/api/advanced_computation/pivot/card/:id`) is better than adding entries to the request map. 

re terminology: depends on how strict you want to be. Anything that has a single pass formulation, can be made mergeable, but it might need additional data (eg. for average you need count alongside partial count). If that requirement is too much, you are limited to operations with the associative property (but even here it gets messy as for instance no float operation is truly associative).

**Comment by salsakran** [comment]
I'm not a huge fan of the frontend needing to generate multiple queries in the first place. 

Can we move that to the backend somehow or is it just not natural?

**Comment by sbelak** [comment]
We can. We can either do 1) a pivot-specific endpoint which takes a card/ad-hoc question and figures out which queries to issue by introspecting the MBQL and returns all the sub-datasets; or 2) just extract the MBQL introspection/query generation to an endpoint and have a back-and-forth with the FE. Although at this point it's probably cleaner to just do 1).

**Comment by sbelak** [comment]
After giving it some more thought, I think going with `/api/advanced_computation/pivot/card/:id` is the best course of action for now, as it's nicely self-contained & very chill to do. 

Quick sketch of the endpoint:
1) `GET /api/advanced_computation/pivot/card/:id`
`GET /api/advanced_computation/pivot/adhoc/:query`
2) Since in terms of data retrieved this will be a subset of what you get by the source card/question, we check the permissions for that.
3) Returns vector of maps with fields: `:breakouts` (uses `:field_ref` from `:cols`), `:rows` (same as normal query, but only using breakouts from `:breakouts`, but retaining all the `:aggregations`), `:cols` (same as normal query, but only using breakouts from `:breakouts`, but retaining all the `:aggregations`). For the example above that would yield:
```
[{:breakouts [[:field-literal "country"]]
   :cols [...]
   :rows [["AK" 2 2] ["AL" 4 1] ...]}
 {:breakouts [[:field-literal "country"] [field-literal "source"]]
   :cols [...]
   :rows [["AK" "Affiliate" 2 2] ["AK" "Facebook" 2 2] ...]}
 {:breakouts [[field-literal "source"] [field-literal "category"]]
   :cols [...]
   :rows [["Affiliate" "Doohickey" 3 2] ["Affiliate" "Gadget" 4 1] ...]}]
```
(note: I'm using `:field-literal` in the example for readability)

## Questions: 

* if one of the breakout dimensions is a date, do we do anything clever like have partial sums for month/quarter/year, or treat it exactly the same as other breakout dimensions?
* Do we even need `:cols`?
* `advanced_computation` is not a very good name.

**Comment by paulrosenzweig** [comment]
It would be nice to push the query generation to the backend. However, I think it forces the backend to introspect the visualization settings to see what the breakout sets are.

The visualization settings are saved with the card so the saved query endpoint could access them, but we'd need to send them up for adhoc querying. That's certainly possible, but it feels messy to start poking around in the visualization setting on the server.

Generating the ancillary queries from visualization settings isn't too complicated, so if it keeps the query APIs cleaner, it probably makes sense to keep it on the client for now.

**Comment by sbelak** [comment]
Or just generate all of the breakout sets, which would also make changing the settings faster. I doubt you'll often have more than 3-4 breakouts, so it's not that much.

**Comment by paulrosenzweig** [comment]
I like the simplicity, but it's could be pretty slow if things don't parallelize perfectly, right? With four breakouts we'd do 15 ancillary queries rather than just the 5 that are needed. I agree five breakouts are hopefully rare, but if we allowed that we'd have 31 queries.

**Comment by sbelak** [comment]
Or we just add `?breakouts=[...]` (using the same format as `:breakouts` in the response) to the endpoints

**Comment by salsakran** [comment]
@mazameli @kdoh Just to be explicit, we're expecting the entire summary table to be rendered in one go? I.e. if there are a bunch of subtotals that need to be calculated in subqueries, we dont' display the table until they're all done?

**Comment by paulrosenzweig** [comment]
@sbelak `?breakouts=[...]` makes sense, but that's effectively doing the query generation on the client. If we're going that way, do we want to make the normal endpoints fully multi-query rather than doing something specific to breakouts?

**Comment by sbelak** [comment]
@paulrosenzweig I'm misunderstanding something. My reading of above was that you already have this info in the visualization settings (or something similar to it).

**Comment by paulrosenzweig** [comment]
![image](https://user-images.githubusercontent.com/691495/97915009-c407c500-1d1e-11eb-9e16-61df9371a44b.png)

There will be visualization settings for "Fields to use for the table (rows|columns)". We'll use those to generate the list of breakouts. In my mind, that process of going from vis settings to a list of breakouts is when the ancillary queries are generated.

The API could have a `?breakouts=[...]` parameter or it could take a list of entire queries. It seems more general to extend the API to allow multiple queries, but I'm also open to confining the API to only accept breakout variations on a base query. Do you prefer that?

**Comment by sbelak** [comment]
If you can just send the `rows` from above in whatever format, that's fine. I'd start with a simple constrained API for the first iteration. My hunch is that these should be quite black boxy, so we don't have to spread the logic too much between FE & BE, but actual use cases will guide us best.

**Comment by paulrosenzweig** [comment]
That works for me. To confirm, we'll have pivot-specific versions of the following endpoints. The request body sent to both endpoints will include `pivot_cols` and `pivot_rows` at the top level. The responses will include multiple result sets for each breakout.

- `POST /api/card/:id/query`
- `POST /api/dataset`

**Comment by sbelak** [comment]
Yes. Any reason these need to be POST?

**Comment by paulrosenzweig** [comment]
The card and adhoc query endpoints are currently POST requests. I'm not sure why since it seems they're idempotent. The new, pivot table-specific ones should probably match though.

**Comment by paulrosenzweig** [comment]
@robdaemon I think using indexes is cleaner than what I mentioned earlier.

`POST /api/advanced_computation/pivot/dataset`
("advanced_computation" up for renaming)

with this body:
```
{
    "database": 1,
    "query": {
        "source-table": 1,
        "aggregation": [ ["count"], ["sum", ["field-id", 123],
        "breakout": [
            ["datetime-field", ["field-id", 456], "year"],
            ["binning-strategy", ["field-id", 789], "default"],
            ["fk->", ["field-id", 234], ["field-id", 345]],
        ]
    }
    "type": "query",
    "parameters": [],
    "pivot_row_indexes": [2,1],
    "pivot_col_indexes": [3]
}
```

**Comment by sbelak** [comment]
If we use numerical references, just be sure they get refreshed aggressively -- we have a number of bugs where numbered referencing of aggregations/segments break when the user plays around in QB.

**Comment by lindsay-stevens** [comment]
In the a SQL'99 feature set for OLAP there are grouping features `GROUPING SET`, `CUBE` and `ROLLUP`. These address the stated problem - the need to specify and generate the various grouping combinations. The data comes back in 'long and skinny' form which the front-end could re-arrange into the pivot table visualisation.

These SQL features have pretty good support - the ones I checked were Postgres, MSSQL, MySQL, Snowflake, Presto, Oracle; probably many others too. Maybe the more complex approach is only needed for back-ends where these features aren't available or not fully supported? My other suggestion is that maybe the SQL snippets functionality could help generate `UNION`'ed queries so the front-end only needs to deal with one shape of data.

https://www.postgresql.org/docs/10/queries-table-expressions.html#QUERIES-GROUPING-SETS
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-group-by-transact-sql?view=sql-server-ver15
https://dev.mysql.com/doc/refman/8.0/en/group-by-modifiers.html
https://docs.snowflake.com/en/sql-reference/constructs/group-by-grouping-sets.html
https://prestodb.io/docs/current/sql/select.html
https://docs.oracle.com/cd/B19306_01/server.102/b14223/aggreg.htm

**Comment by paulrosenzweig** [comment]
@sbelak good point. I think these indexes won't be persisted at all, the visualization setting will store the field_ref and find the index into the breakout to hit the API.

---

@lindsay-stevens whoa that's awesome! I had no idea that was supported.

Knowing about those grouping features makes me think this should be added to MBQL rather than adding these new pivot table endpoints. Though, if that'll take longer I think we can move ahead with new endpoints. @robdaemon @sbelak @camsaul  thoughts?

**Comment by paulrosenzweig** [comment]
This was implemented. We added pivot table specific endpoints for each existing query endpoint.
