### ISSUE TITLE
Performance issue when using nested questions, which returns ~100k+ results

### ISSUE THREAD

**Issue by Martin-Labenne** [metabase/metabase#13572]
**Describing the issue**
Hello, I'm encountering big performance issues while using saved questions as references in my requests. The computation time explodes compared to the time it would take for the request to be executed without the use of a reference. It is particularly remarkable when I take "big" tables (~100,000 rows, 10 columns). Maybe I'm doing something wrong ...

**To Reproduce**
1. Go to "Write SQL"
2. Simply request to fetch all data from a big table 
```
SELECT * FROM big_table
```
3. Save your question and get the id of this new querry, you'll need it to target this request from another
4. Once again, go to "Write SQL" and open a new editor and simply write 
```
SELECT * FROM {{#xxx}} t
```
With `xxx` the id of your previous request 

5. Wait until you see a result (enventually)
6. You can compare the following request (which is supposed to be the same) 
```
SELECT * FROM (
    SELECT * FROM big_table
) t
```
Obviously, I do not use referenced question to perform such basic operation, but you get the idea. It is really useful to 

**Expected behavior**
The query with metabase's ref takes forever (and eventually goes timeout) while its equivalent (classic nested query) is way more performant 

**Information about your Metabase Installation:**

- Browser and version: Chrome 86
- Operating system: Windows 10
- Databases: MySQL 5.6
- Metabase version: 0.36.2
- Metabase hosting environment: 
```
"system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-8u252-b09-1~16.04-b09",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.4.0-1109-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
```
 
**Nota Bene**
If you need more information, please tell me, I will answer you as soon as possible.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
**Steps to reproduce:**
1. Create 3 SQL questions using Sample Dataset:
   1. Q1
   ```
   SELECT PEOPLE.* FROM PEOPLE
   LEFT JOIN PEOPLE P2 ON P2.STATE=PEOPLE.STATE
   ```
   2. Q2 - replace `123` with the ID of the question created above
   ```
   SELECT * FROM {{#123}} x
   ```
   3. Q3
   ```
   SELECT * FROM (
       SELECT PEOPLE.* FROM PEOPLE
       LEFT JOIN PEOPLE P2 ON P2.STATE=PEOPLE.STATE
   ) x
   ```
2. Execute Q1 (simple select) takes ~1 second on my computer
`2020-10-22 19:58:56,009 DEBUG middleware.log :: POST /api/card/334/query 202 [ASYNC: completed] 783.2 ms (6 DB calls) App DB connections: 1/10 Jetty threads: 3/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)`
3. Execute Q2 (Sub-Query) takes ~38 seconds
`2020-10-22 19:53:00,050 DEBUG middleware.log :: POST /api/card/335/query 202 [ASYNC: completed] 38.8 s (12 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (1 idle, 0 queued) (79 total active threads) Queries in flight: 0 (0 queued)`
4. Execute Q3 (full written query) takes ~1 second
`2020-10-22 19:58:49,894 DEBUG middleware.log :: POST /api/card/336/query 202 [ASYNC: completed] 859.8 ms (6 DB calls) App DB connections: 1/10 Jetty threads: 3/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)`

**Comment by tylerssn** [comment]
Same. Where question #1 = `select * from table`:

* `select * from {{#1}} as source` - well over a minute to return data.
* `select * from (select * from table) as source` - completes almost immediately.

**Comment by jpure14** [comment]
Is there any update on this issue? @flamber Thank you!

**Comment by mlazowik** [comment]
I'm not sure if this is the same issue, but we're seeing a similar problem when using saved sql queries in notebook queries. The slow step that uses a lot of CPU seems to be `middleware.fetch-source-query`. The "View the SQL" popup in notebook opens immediately, but shows a spinner for quite long (even 40s if the cpu is hogged but similar requests). Example log from that: `metabase_1  | 2021-05-25 13:16:35,354 DEBUG middleware.log :: POST /api/dataset/native 200 44.3 s (11 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (41 idle, 0 queued) (231 total active threads) Queries in flight: 5 (0 queued)`

**Comment by mlazowik** [comment]
We're on `0.39.2`, but have seen that on previous versions too. We started from `0.35.x`, and updated a few times since then, but the issue become noticeable only after we had more dashboards/queries, so I don't know if it's a regression or was it always like that.

**Comment by pawit-metabase** [comment]
Preliminary research: The inner query ends up getting ran on its own during when query processor is running the substitution because `query->native` somehow ended up running the query when used with native query.

If we turn qp and driver logging up to TRACE, we can see that when we run the following command in REPL, the query got executed and metabase process all the rows.

```
(metabase.query-processor/query->native {"type" "native","native" {"query" "SELECT PEOPLE.* FROM PEOPLE LEFT JOIN PEOPLE P2 ON P2.STATE=PEOPLE.STATE"},"database" 1})
```
