### ISSUE TITLE
Delete Alerts when the associated Card is deleted

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#13575]
Alerts are basically a special case of Pulses with one Card associated with them and some extra conditions. 

If the associated Card gets deleted, we should delete Alerts associated with it as well. Right now they hang around as orphans. Not sure if this causes any bugs or not

**Comment by flamber** [comment]
@camsaul From what I remember, when a question is archived, then any alerts are deleted, so even if you unarchive the question, then you need to setup the alert again.
Has this changed or are you talking about adding a constraint to ensure it cleans up correctly?

**Comment by camsaul** [comment]
I mean just creating a constraint for this. I guess it really only affects tests since normally we don't delete Cards, we just archive them.

In tests if you actually (permanently) delete a Card, it can leave orphaned Alerts hanging around.

**Comment by robdaemon** [comment]
given that we had that bug where deleted databases still tried to run a sync and spiked CPU usage, this is a really good thing to take care of, as a "just in case" measure.

**Comment by qnkhuat** [comment]
Card is no longer deleted but archived. 

Anw Alerts will now be deleted when you archive a Card
