### ISSUE TITLE
Certain questions have become uneditable

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#13583]
**Describe the bug**

We have a few, but not all, questions in our default "Our analytics" collection which have become uneditable in the past month. As far as I can tell, nothing has changed with permissions for these questions. Editing doesn't work for either admins or regular users.  You can rename the questions, but can't edit any of the query.

I included a screenshot below of what you see if you manually append `/notebook` to the URL.

**Logs**

Javascript logs for viewing the question:

```
app-main.bundle.js?a2e4b9bf6c05874d00a3:5 Failed loading metadata for query TypeError: Cannot read property 'fields' of null
    at app-main.bundle.js?a2e4b9bf6c05874d00a3:5
    at u (vendor.bundle.js?a2e4b9bf6c05874d00a3:1)
    at Generator.g._invoke (vendor.bundle.js?a2e4b9bf6c05874d00a3:1)
    at Generator.e.<computed> [as next] (vendor.bundle.js?a2e4b9bf6c05874d00a3:1)
    at r (app-main.bundle.js?a2e4b9bf6c05874d00a3:5)
    at app-main.bundle.js?a2e4b9bf6c05874d00a3:5
(anonymous) @ app-main.bundle.js?a2e4b9bf6c05874d00a3:5
12app-main.bundle.js?a2e4b9bf6c05874d00a3:5 Warning: can't clean query without metadata!
value @ app-main.bundle.js?a2e4b9bf6c05874d00a3:5
```

Server logs from the request:

```
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/user/current 200 5.6 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/session/properties 200 6.6 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/database 200 7.5 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/database 200 33.7 ms (4 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/card/605 200 12.8 ms (5 DB calls) App DB connections: 1/7 Jetty threads: 3/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/database 200 61.2 ms (11 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/alert/question/605 200 2.3 ms (1 DB calls) App DB connections: 1/7 Jetty threads: 3/50 (4 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/table/255/query_metadata 200 20.6 ms (8 DB calls) App DB connections: 1/7 Jetty threads: 4/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/table/12/query_metadata 200 44.3 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:31-07:00 DEBUG metabase.middleware.log GET /api/collection/root 200 4.3 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:32-07:00 INFO metabase.api.card Question's average execution duration is 871.0 ms; using 'magic' TTL of 9.0 s 💾
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:32-07:00 INFO metabase.query-processor.middleware.cache Query took 690.0 ms to run; minimum for cache eligibility is 60.0 s
[c36c24ae-6473-42a2-b3f1-6a7a39604b05] 2020-10-23T10:33:32-07:00 DEBUG metabase.middleware.log POST /api/card/605/query 202 [ASYNC: completed] 714.7 ms (22 DB calls) App DB connections: 1/7 Jetty threads: 2/50 (4 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued)
```

**To Reproduce**
1. Open question
2. see that you can edit the name but not the query
3. add /notebook, see broken screen

**Expected behavior**

I expect /notebook to show the query builder

**Screenshots**

![image](https://user-images.githubusercontent.com/82608/97037806-af594f00-151e-11eb-80c7-c9d27873030d.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.193-113.317.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres",
      "bigquery"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-22",
      "tag": "v0.37.0",
      "branch": "release-x.37.x",
      "hash": "f435e43"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**

annoying, not totally critical.

**Additional context**

This is happening to some but not all of our questions, and only in the past month or so.

**Comment by flamber** [comment]
Hi @bcherry 
Just to understand completely.
1. This was also a problem before 0.37.0? Which version did you upgrade from?
2. Or did the problem first start on 0.37.0, but with some questions created roughly the past month?
3. Does the problematic questions all try to query the same database/table?
4. Or do the questions have a specific construction compared to working questions?
5. Do you have two questions, which you know are basically the same, but where one is failing? Then I would love to see `report_card.dataset_query` for them (if you don't want them public, then my username AT metabase dot com)

**Comment by bcherry** [comment]
@flamber it was definitely a problem in 0.36.7, which I upgraded to a few days ago. But @ericcj who reported it to me today suggested it existed before that as well.

I don't actually know the queries these questions use, as they are Eric's questions and the notebook editor doesn't work so I can't see the construction. But I do think they're all from the same database/table.

Is there an easy way to get the `report_card.dataset_query`?

I did run into #8420 while trying to debug this, but after reading that I think it's unrelated.

**Comment by flamber** [comment]
@bcherry Okay, let's see what Eric can come up with. Can you make sure that you're not using some weird WAF/proxy - I have seen the strangest visual problems, where it could save some dashboards/questions, but not others:
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html
I'm guessing you're using EBS with RDS? The data is stored in `ebdb` on RDS, think it would be `ebdb.public.report_card.dataset_query` - you setup the application database as any other database source via Metabase.

**Comment by bcherry** [comment]
Yeah as far as I know, we're not using any proxies. We're running Elastic Beanstalk and the database in question here is an RDS database connected to via ssh. I think Metabase runs in the same VPC.

**Comment by flamber** [comment]
@bcherry I was talking about the application database. If you just followed the regular config script, then by default a RDS is created and coupled with EBS, where all the Metabase metadata is stored. That's the application database.

**Comment by flamber** [comment]
@bcherry Now I know what is happening. You're hiding the table in Admin > Data Model.

**Comment by bcherry** [comment]
@flamber thanks! that is correct.  a confusingly-named table was in use :)
