### ISSUE TITLE
"Click behavior" not working on pin maps

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13597]
**Describe the bug**
"Click behavior" not working on pin maps. It does not send the column data.

**To Reproduce**
1. Custom question > Sample Dataset > People - limit 2
![image](https://user-images.githubusercontent.com/1447303/97226755-bdd09080-17d4-11eb-8d75-2c48ef89454d.png)
2. Change visualization to Map (pins), save question and add to dashboard
3. Add filter ID and connect to card
4. Hover dashboard card > click "Click behavior" > select "Update a dashboard filter" > select filter "ID" = column "ID" - save dashboard
![image](https://user-images.githubusercontent.com/1447303/97227299-91694400-17d5-11eb-8db7-181ebe2c50b2.png)
5. Click any of the pins - no value is added to the dashboard filter, no errors in the browser console - but it seems like it's refreshing the map on click.

**Information about your Metabase Installation:**
Metabase 0.37.0.1

**Additional context**
https://discourse.metabase.com/t/try-out-the-new-0-37-release/12048/14?u=flamber

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by marinomaria** [comment]
I'm experiencing the same issue on v0.37.8, click behavior is not working at all for pin map cards. 

Is there an estimation on when it will be fixed?
