### ISSUE TITLE
Inform user that they were inactive when processing password recovery

### ISSUE THREAD

**Issue by shuLhan** [metabase/metabase#13594]
**Is your feature request related to a problem? Please describe.**

If user is set to inactive, any password recovery methods (by email or `reset-password`) is always success but no action triggered. For example, password recovery by email will success but no email send to that user; `reset-password` command generate the token but when submitted to `/auth/reset_password/:token` will return expired link.

**Describe the solution you'd like**

I would like the application to inform user that the user's account is inactive before proceeding to password recovery.

**How important is this feature to you?**

Note that important, but it take me one day to get into a broken metabase installation, even try hard code the password directly into the database, until I realize that the previous user admin that manage the account is set to inactive in `core_user`.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #12987 (and #3245)

**Comment by camsaul** [comment]
If we just told you the account doesn't exist, a bad actor could use that endpoint to enumerate accounts and figure out which accounts *do* exist. Maybe we can send you an email tho telling you the account doesn't exist

**Comment by shuLhan** [comment]
> If we just told you the account doesn't exist when you submit the form, a bad actor could use that endpoint to enumerate accounts and figure out which accounts _do_ exist. Maybe we can send you an email tho telling you the account doesn't exist

I never mention about whether account exist or not. Please read the issue again.

**Comment by noahmoss** [comment]
@shuLhan I think @camsaul's point still stands. We don't want to leak that an account exists before a password has been provided & verified, even if the account is disabled.

We could, however, send an email saying that the account is disabled, rather than the normal  password reset message. I'll take a look and see if I can get something like that to work.
