### ISSUE TITLE
Click Behavior - Link to Dashboard / Question does not respect SITE_URL setting in Admin Panel

### ISSUE THREAD

**Issue by edwinkong** [metabase/metabase#13602]
**Describe the bug**
Click behavior -> Link to a dashboard / question strips the path of the URL. It does not respect the `SITE_URL` settings in Admin page.

For example, with setting `SITE_URL`: http://example.com/metabase, the click behavior brings the user to http://example.com/dashboard/18. However, it should bring the user to http://example.com/metabase/dashboard/18

**To Reproduce**
1. Set up click behavior to a column, Link to any other dashboard or question.
2. Save the dashboard.
3. Click on the column.
3. The dashboard redirects to the URL with the path stripped.

**Expected behavior**
It should append the `/dashboard` to `SITE_URL`.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Metabase version: v0.37.0.2
- Metabase hosting environment: Jar-file on RHEL 7.5, reverse proxied by NGINX at the path /metabase
- Metabase internal database: PostgreSQL 

**Severity**
It causes confusion and complains from users when the functionality was provided but does not work in our case.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #11684 and #12580

**Comment by caarlos0** [comment]
Sorry for the ping, but is this being worked on?

**Comment by hawisizu** [comment]
Hello @flamber , 
not sure to understand your workaround, is it something I can already do directly, or that needs to be implemented by in the next version? 
Thanks, 
Luc

**Comment by flamber** [comment]
@hawisizu The workaround would need to be applied to your reverse-proxy.

**Comment by gustavotrott** [comment]
Alternative workaround using `.htaccess`

```
RewriteEngine On
RewriteRule ^question/(.*)$ /metabase/question/$1 [R=301,NC,L]
```

**Comment by mrhydejc** [comment]
The workaround seems not applicable when running multiple instances of metabase.
We can't guess the instance to redirect to :
```
/metabase/instance1/question
```
or
```
/metabase/instance2/question
```

**Comment by salsakran** [comment]
bumping priority due to customer escalation

**Comment by hal58th** [comment]
I hope this gets fixed soon, but this is my workaround for people using Nginx.
```
# The /metabase directive was my original config, I had to add the /dashboard directive.
    location /metabase {
      rewrite  ^/metabase/(.*) /$1 break;
      proxy_pass http://metabase:3000/;
    }
    location /dashboard {
      rewrite  ^/dashboard/(.*) /metabase/dashboard/$1 permanent;
    }
```
