### ISSUE TITLE
SQL Editor doesn't autocomplete DB-specific functions

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1362]
Eg. `date_trunc` doesn't auto complete in the SQL editor.

Which set of keywords are we using?

**Comment by tlrobinson** [comment]
We're currently just using the `sql

**Comment by tlrobinson** [comment]
We're currently just using the `sql` mode but could also use the `mysql` or `pgsql` modes based on the database type: https://github.com/metabase/metabase/blob/master/frontend/src/query_builder/NativeQueryEditor.jsx#L46

**Comment by camsaul** [comment]
Might as well implement this while we're making the ACE Editor work with Druid (PR #2515) & Mongo.

[List of all ACE modes is here](https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/modelist.js#L45)
