### ISSUE TITLE
React error when loading individual record

### ISSUE THREAD

**Issue by ghiculescu** [metabase/metabase#13627]
**Describe the bug**
We just upgraded to v0.37.0.2, and we are now getting an error when trying to load records by ID for some tables from our postgres DB.

We upgraded because we wanted a fix to https://github.com/metabase/metabase/issues/13263#issuecomment-708085151 - I'm going to downgrade again and check if it's the same error there. Update: getting same error after downgrading :( 

**Logs**
See below for javascript logs/screenshots. This is recorded in the server logs when the error happens:

```
[db136d00-9224-48c7-9a5e-cd1603cbd350] 2020-10-29T12:12:38-05:00 DEBUG metabase.middleware.log POST /api/dataset 202 [ASYNC: completed] 2.3 s (64 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (15 idle, 0 queued) (141 total active threads) Queries in flight: 0 (0 queued)
```

I will note that this response time is a fair bit slower than before upgrading. We were on v0.36.6 prior.

**To Reproduce**
1. Simple Question
2. Choose the relevant table in our postgresql db
3. Filter by 2 IDs -> works fine
4. Filter by a single ID -> error

**Screenshots**

Recording of the error:
![recording](https://user-images.githubusercontent.com/509837/97607402-ea57f880-19de-11eb-87e3-c16df841b810.gif)

Dev tools immediately after the error displays:
![image](https://user-images.githubusercontent.com/509837/97607486-09568a80-19df-11eb-9240-697b564d4973.png)

Dev tools if I click the play icon to re-run the query:
![image](https://user-images.githubusercontent.com/509837/97607528-196e6a00-19df-11eb-9f5e-8f07f22195d2.png)

"Show error details" is unclickable, but I can get the error from the DOM:
![image](https://user-images.githubusercontent.com/509837/97607621-373bcf00-19df-11eb-9081-940f8e346d75.png)

Note that the relevant data is being returned:
![image](https://user-images.githubusercontent.com/509837/97607683-4c186280-19df-11eb-930f-3e26069bc2ab.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.193-149.317.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Blocking an upgrade.

**Comment by flamber** [comment]
Hi @ghiculescu 
Looks like you're seeing #12600, since you don't have an query errors in the log.
Would be helpful to know you table column types and the Field Types in Metabase > Admin > Data Model.

**Comment by ghiculescu** [comment]
Looks like the same error. This table has a _lot_ of columns. Here's the types it uses:

- integer
- character varying(255)
- timestamp without time zone
- boolean
- date
- text
- hstore
- character varying
- bigint
- uuid

**Comment by flamber** [comment]
@ghiculescu But are any of them set as Field Type = `Field containing JSON` in Admin > Data Model ?

**Comment by ghiculescu** [comment]
Yep! The `hstore` one is.

**Comment by flamber** [comment]
Excellent. Closing this in favor of #12600

**Comment by ghiculescu** [comment]
Thanks for the help @flamber 

Do you think #12600 would make a good first PR?

**Comment by flamber** [comment]
@ghiculescu Actually yes, since it seems to only involve frontend, and perhaps "just" needs a `try{}` to avoid blowing up with a regular text-fallback. But I really haven't looked at the code, so you'll have to investigate on your own. And I'm definitely not a React developer, just know my spaghetti javascript enough to be dangerous.
