### ISSUE TITLE
Dashboard filters not showing 'a list of all values' after latest update (v0.37.0.2)

### ISSUE THREAD

**Issue by CharlBrill89** [metabase/metabase#13624]
The Dashboard filters in several dashboards that I created are **not showing** 'a list of all values' after the latest update. Even though Ive changed the settings (Filtering on this field) in the data model in Admin. I know there are quite a few filters in the dashboards and Im not sure if this is influencing the behaviour to change the filtering to 'Plain text' as opposed to the desired 'a list of all values'. Although, it worked perfectly fine prior to the update so I don't think this is an issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/61794265/97583291-6eba7380-19ff-11eb-8679-855066abc2f9.png)

**Severity**
Our users depend on lists of items to filter on (fewer than 100 in most cases) so it's essential that we list all the possible values when clicking on a filter.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.123-86.109.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @CharlBrill89 
Which version did you upgrade from?
The selected dashboard filter - how many cards (questions) is it linked to?
And which type of questions are those cards - Native/SQL or Simple/Custom?
If SQL, then what type of filters are the variables on the question?

**Comment by CharlBrill89** [comment]
Hi @flamber,

We upgraded from v0.36.7 - last week (2020-10-21).
Each filter (there are about 14-16 filters per dashboard) is linked to around 20-25 cards. Those cards are mostly native SQL questions with field filter mappings to fields in selected tables (that aren't that big). As mentioned, it worked perfectly fine with the previous version, but with this version the combination of field filters and showing a list of all values isn't working effectively.

**Comment by CharlBrill89** [comment]
@flamber - It seems like it may be a filter<>dashboard related issue. The filters work fine (list all possible values or at least searches for them as specified in the data model (admin)) when I go into a specific question. But on all the dashboards, the filters don't seem to list all values anymore.
![image](https://user-images.githubusercontent.com/61794265/97666348-1aa6a200-1a86-11eb-89ac-3ec189c515d8.png)

**Comment by flamber** [comment]
@CharlBrill89 I cannot reproduce this.
Can you provide steps-to-reproduce with the least dashboards/questions needed? And preferably with Sample Dataset.

**Comment by CharlBrill89** [comment]
@flamber I actually decided to redevelop all the dashboards as none of the filters were showing a list of all values. Once I redeveloped them, they seemed to work. Not sure if other's had the same issue after upgrading from a previous version of Metabase. 

Thanks for following up!
