### ISSUE TITLE
Docker in production

### ISSUE THREAD

**Issue by danieljacobarcher** [metabase/metabase#1363]
I deployed Metabase via Docker on Cloud66 (a docker cloud service platform) and I'm getting a URL like http://bc248c3a907b:3000/setup/ in the install logs in direction to setup the Metabase installation, but obviously this is not a valid url. Has anyone else run into this issue on setup before? Navigating to the public url (a Cloud 66 generated url that points to the server) does not load Metabase at all.

**Comment by danieljacobarcher** [comment]
It looks like it's not configuring the Embedded Jetty Webserver to run from localhost..

**Comment by salsakran** [comment]
You can disregard the url, as it's using the internal ip in this case. You should be able to hit port 3000 on the host.

**Comment by danieljacobarcher** [comment]
Thanks @salsakran. It must be another problem then.

**Comment by ArnaudD** [comment]
I think I had the same problem @danieljacobarcher. Adding `MB_JETTY_HOST=0.0.0.0` to the docker container environment fixed the issue in my case.
