### ISSUE TITLE
Filter causes the order of returned fields to be swapped

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1364]
Adding a filter sometimes causes the order of the fields in a multi-dimension query to be swapped, breaking charts.

**Correct:**

![screenshot 2015-10-26 13 15 47](https://cloud.githubusercontent.com/assets/18193/10742064/64c64fd0-7be8-11e5-9053-bb6dcc374c3e.png)

![screenshot 2015-10-26 13 16 10](https://cloud.githubusercontent.com/assets/18193/10741284/2a8a0644-7be4-11e5-92a0-0d906c535488.png)

**Incorrect (added "Time is Today" filter):**

![screenshot 2015-10-26 13 16 51](https://cloud.githubusercontent.com/assets/18193/10742068/6b60972e-7be8-11e5-914a-f00d33ebd75a.png)

![screenshot 2015-10-26 13 17 29](https://cloud.githubusercontent.com/assets/18193/10741291/3049e36a-7be4-11e5-9037-5415720abf25.png)

**Comment by camsaul** [comment]
This should be fixed with the reworked column ordering logic. @tlrobinson can you *please* verify this?

**Comment by tlrobinson** [comment]
Actually now it seems to always be returning the columns for that query in the "wrong" order, regardless of whether it has a filter on `time` or not: `http_status`, `time`, `count`. I would expect the order to be `time`, `http_status`, `count` (though I'm also confused by our stacked charts, see #1449). Removing the `http_status` breakout fixes it (`time` then `count`) (this is using our Metabase Downloads / Entries table)

Interestingly similar queries using the sample dataset don't have this problem, e.x. "count of orders by product->rating and created at:day"

**Comment by agilliland** [comment]
@tlrobinson I just merged a fix for this.  you mind doing another check at validating this?  should be g2g now.
