### ISSUE TITLE
Pulse Reports not sent to users (automatic/manual both not working)

### ISSUE THREAD

**Issue by punnumangal** [metabase/metabase#13653]
**Bug**
The scheduled Pulse Reports are not going automatically in Metabase. Even if we click on "Send Email now" button to send a Pulse Report it sometimes takes couple of hours to go (which should be instantaneous ideally) or it would not go at all.

**Screenshots**
<img width="1213" alt="Screenshot 2020-11-02 at 1 54 56 PM" src="https://user-images.githubusercontent.com/22841102/97845761-05927300-1d13-11eb-8af5-f09778ecdd55.png">

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_265-8u265-b01-0ubuntu2~16.04-b01",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_265",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.265-b01",
    "os.name": "Linux",
    "os.version": "4.4.0-1109-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.6",
      "date": "2020-09-15",
      "branch": "release-0.36.x",
      "hash": "cb258fb"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}

**Severity**
This issue is a blocking issue because many people (100+) in our company are dependent on these Pulse reports to take their daily actions. Kindly resolve at the earliest.

**Comment by flamber** [comment]
Hi @punnumangal 
Sounds like it might be an issue with the mail server. Please check the logs of Metabase and the mail server to confirm.
