### ISSUE TITLE
Dashboard filter run query every time

### ISSUE THREAD

**Issue by KEN-LJQ** [metabase/metabase#13651]
**Describe the bug**
For those filter on dashboard, which setting to provice a list of candidate value. Above 0.37.x, when Linking filters feature added, we can see the fiter fire a value query on database when we click and popup, event though we did not link any of them together. Before 0.37.x the candidate value is cached with the field scan operation.
When under database is busy, the value list will show up after a long time, for user they don't know what happening. And we worry if filter field on a huge table, the value query will cause serious performance impact on database.
We know linking filter have to run a query every time, because of the complex condition that can not be cached, but for the common filter, the field cache will be better.

**Screenshots**
![image](https://user-images.githubusercontent.com/16650282/97798643-e4724980-1c62-11eb-84e1-30fa3493c838.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_162-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_162",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.162-b12",
    "os.name": "Linux",
    "os.version": "2.6.32-696.3.1.el6.x86_64",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "presto"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.0.1",
      "date": "",
      "branch": "2020-11-01",
      "hash": "pre-production"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}
```

**Comment by flamber** [comment]
Closing in favor of #13832
