### ISSUE TITLE
Duplicate fields in query builder

### ISSUE THREAD

**Issue by alexanderpublit** [metabase/metabase#1366]
There's a bug in 0.12.1 that lets me select rows multiple times. But the tables doesn't show the data multiple times (and there's only one row, no duplicates).

![monosnap 2015-10-26 23-00-57](https://cloud.githubusercontent.com/assets/12189439/10743780/9d655b9a-7c35-11e5-816a-dff2ba1832e9.png)

**Comment by alexanderpublit** [comment]
It is mitigated if the database is deleted and re-imported.

**Comment by camsaul** [comment]
@alexanderpublit What database were you using? This is probably the same issue as #1633 if the DB was Mongo or MySQL

**Comment by alexanderpublit** [comment]
@camsaul It was a MySQL database.

**Comment by agilliland** [comment]
sounds like this was resolved by #1682 and released in our 0.13.2 patch release.  

@alexanderpublit have you upgraded to 0.13.2?  any chance you could confirm this is no longer an issue for you?

**Comment by agilliland** [comment]
k, lets go ahead and close this as being fixed in #1682 .  I've been doing syncs on quite a few MySQL and Mongo databases lately and I'm not seeing this issue come up.
