### ISSUE TITLE
Ordering by numeric field when grouping by two fields returns order of 1,10,11,...,2,20,21,...

### ISSUE THREAD

**Issue by penelopeatkinson** [metabase/metabase#13679]
**Describe the bug**
In Metabase custom -question builder, when ordering by a numeric and grouping by the same numeric and a string, the order of the numeric is ordered as per the below:
1, 10, 11, ... , 2, 20, 21, ...

This does not happen when only grouping by the numeric alone and then ordering. The order is as expected 1,2,3,4,...,10,11,...

[See this question here.](https://metabase.6mind.de/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo3MiwicXVlcnkiOnsic291cmNlLXRhYmxlIjoyOTEsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZC1pZCIsMjA3MF0sIkxpYnJhcnkgSXRlbSBTZWxlY3RlZCJdXSwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJicmVha291dCI6W1siZmllbGQtaWQiLDUxMTldLFsiZmllbGQtaWQiLDIwODBdXSwib3JkZXItYnkiOltbImFzYyIsWyJmaWVsZC1pZCIsNTExOV1dXX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5Ijoic2NhdHRlciIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJncmFwaC5kaW1lbnNpb25zIjpbIm1lZGl0YXRpb25fdG9waWNfbmFtZSJdLCJncmFwaC5tZXRyaWNzIjpbImNvdW50Il19fQ==)

**To Reproduce**

**Expected behavior**
Numeric ordering of 1,2,3,4,...,10,11

**Screenshots**
![image](https://user-images.githubusercontent.com/69905875/98122726-46c08980-1eb1-11eb-9124-bd2410aad12e.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "druid",
      "presto"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5 (Ubuntu 10.5-1.pgdg18.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Severity**
Blocking some users.

**Comment by flamber** [comment]
Hi @penelopeatkinson 
I'm guessing you're referring to "Meditation Topic Index". That column is a string, not numeric, so it will be sorted alphabetically.
We cannot access your instance, so a link doesn't help in this case.
Without knowing the column type and which database you're querying with, it's harder to reproduce.
