### ISSUE TITLE
convert string literals to BSON IDs in Mongo queries when appropriate

### ISSUE THREAD

**Issue by dariooddenino** [metabase/metabase#1367]
I'm on version 0.12.0.
I've tried with all the references I have in my db, and the result is always the same

**Comment by andrewcurioso** [comment]
:+1: on this.

**Comment by camsaul** [comment]
See also #1340

**Comment by nodesocket** [comment]
Here is an example.

Filtering by `content-type` and `brand-id`, returns 0 results, when there should be results. Confirmed in mongo shell.

![screen shot 2015-11-18 at 2 40 28 pm](https://cloud.githubusercontent.com/assets/523312/11256715/638b2fba-8e02-11e5-95e0-ca97d35a2286.png)

**Comment by camsaul** [comment]
Ahh got it. I think the issue here is that the IDs in the document are BSON IDs but the ones in the query are strings, which makes them completely different objects in the eyes of the Java Mongo driver.

Fix: convert string literals to BSON IDs in Mongo queries when appropriate

**Comment by nodesocket** [comment]
Yeah, the Java Mongo Driver, should parse, and look for things that look like MongoDB ids, if so, then convert it an id.

**Comment by bnetter** [comment]
:+1:

**Comment by sgilroy** [comment]
:+1: Metabase for Mongo has very little value for us without at least basic support for foreign keys.
