### ISSUE TITLE
Scrollbar appears on dashboard textboxes of 1 row height

### ISSUE THREAD

**Issue by bertrandjamin** [metabase/metabase#13676]
**Describe the bug**
On metabase v0.37 , text boxes with 1 row height has a scrollbar ~on Windows (everything is fine on Mac).~ 

**To Reproduce**

On ~a windows PC~  Chrome: 
1. Create a deshboard
2. Click on Edit dashboard
3. Click on Add a text box
4. Add at least one letter in it
4. Set as one row height
5. Close edition
6. Scrollbar is visible on the text box

**Expected behavior**
No scrollbar  

**Screenshots**

![dashboard_textbox](https://user-images.githubusercontent.com/4040743/98099101-71014f80-1e8f-11eb-8ffd-94987197fa30.png)

![dashboard_tetbox_edit](https://user-images.githubusercontent.com/4040743/98099097-7068b900-1e8f-11eb-913a-e6d773e2e464.png)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 86
- Your operating system: Windows 10 (1909)
- Metabase version: v0.37.0.2

**Severity**

This issue breaks several dashboards displays in all our customers Metabase instances. 
It prevent us to upgrade to your latest version to avoid bad UX on their sides. 

As the new capabilities of the last version are really important for us this bug is quiet blocking...

Thanks for your help

**Comment by flamber** [comment]
Hi @bertrandjamin I don't understand how this is blocking? It looks like a visual annoyance. Related to #8333

**Comment by bertrandjamin** [comment]
Hi @flamber,

On our customer instances we have some dashboard which act as portals with several links to other dashboards.
With this bug those "portals" looks weird and not "pro".

It is not technically blocking I agree, but it is more about a "quality brand image".

I haven't mentioned it on the initial report but everything works fine on v0.36.8 version

**Comment by bertrandjamin** [comment]
FYI, after a new test on metabase 0.37.1 and contrary to my first report, the problem is also visible on a combo MacOs (BigSur) + GoogleChrome (86). 

<img width="1332" alt="Screenshot 2020-11-16 at 08 36 21" src="https://user-images.githubusercontent.com/4040743/99224701-1ea52480-27e7-11eb-9cc2-46091a5a065c.png">

I have no issue on Firefox.

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/15623
