### ISSUE TITLE
Configuration to change loglevel in Dockerfile

### ISSUE THREAD

**Issue by 4ndygu** [metabase/metabase#13691]
**Is your feature request related to a problem? Please describe.**
Our deployment of a Dockerized Metabase generates disk pressure over time, as the log level is set to the INFO defaults. 

**Describe the solution you'd like**
It would be nice to have the `/bin/start` binary thread in a default log4j2.xml file in a specific location, which users can mount themselves to adjust logging settings. This can be shunted in on L:108: https://github.com/metabase/metabase/blob/master/bin/start#L108

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by flamber** [comment]
Hi @4ndygu 
Unless I'm misunderstanding what you're asking for, that's already possible with:
`... -e JAVA_OPTS="-Dlog4j.configurationFile=file:/path/to/log4j2.xml" ...`
For reference: https://www.metabase.com/docs/latest/operations-guide/log-configuration.html

**Comment by 4ndygu** [comment]
I'm super silly -- I misread that the JAVA_OPTS picks up the existing variable. So sorry for the bother!
