### ISSUE TITLE
Can I integrate Data Visualation part into my Angular app

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [metabase/metabase#13692]
Data Visualizing:
https://github.com/metabase/metabase/blob/master/docs/users-guide/05-visualizing-results.md

I have a Angular App, inside that I would like to integrate this data visualization part. So that It can allow the user to explore his data by visually. 

Is it possible to integrate into Angular App?

Thank you for your time :+1:

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
