### ISSUE TITLE
Allow collection curators create new questions

### ISSUE THREAD

**Issue by easeev** [metabase/metabase#13707]
It would be great to allow collection curators to create new questions that are based on the existing questions in the collection without data access. Currently, you can only create dashboards and pulses.

**Comment by flamber** [comment]
Hi @easeev 
So you want to be able to allow no-data users to create new question based on existing Saved Questions?
I think this is going to conflict with a lot of permissions. A user might have no-data to one database, but have unrestricted-data to another database. The curate-collection would allow them to edit a dashboard and add questions from the database they have access to, while only being able to view the questions from the database with no-data access.
Sounds like it would require a more thorough description with every existing use-case taken into account. Closing this.
