### ISSUE TITLE
Can I use metabase to analyse data in mysql table with millions of rows.

### ISSUE THREAD

**Issue by decker502** [metabase/metabase#1371]
Analysis is always timeout with  six million rows. The documents are not explain more details, so I don't known if it fit to big datasets. thanks.

**Comment by salsakran** [comment]
How are you running metabase? On heroku there are very tight timeouts we're
working on. On other platforms there can be timeouts at the load balancer
or reverse proxy that cause this.

**Comment by decker502** [comment]
I run it in the docker on my local machine, and then metabase connect to another machine running a mysql instance.

### Docker Machine info:

```
Centos 7
Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz
Memory 24G
```
Mysql machine info:

```
Centos 6.5
Intel(R) Xeon(R) CPU           E5606  @ 2.13GHz
Memory: 64G
```

**Comment by camsaul** [comment]
The data analysis code runs native queries for almost everything it does, and for analysis that takes place on the Metabase server itself it runs against small, lazily-fetched chunks of a subset of all the rows in your DB. You shouldn't have any problems.
