### ISSUE TITLE
MBQL: use field-id where possible and flow metadata better 

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#13712]
There should be no need to use field-literal to refer to what we know is a known field. field-literal should only be used to reference: cols from a native source query; aggregations; and expressions.  

We need to improve how we flow metadata at the same time else we will not be able to correctly generate references to joined fields. 

* [x] switch to `field-id` where possible
* [x] add middleware to update old style MBQL to new
* [x] go through the list of bugs in #13702 and add them as tests (where applicable. ie. where the hypothesis is that this work should fix it) 
* [x] pass along more metadata about source query
* [x] tidy up MBQL->native compiler
* [ ] cleanup tests

**Comment by sbelak** [comment]
Got the basic version working in #13655, however some queries using old-style :feild-literal  now break. In tests this is not the end of the world, as we can just fix them, but it can also impact customer queries. Next step is to figure out if either the new approach can either be extended to work with field-literals (probably rewriting them on the fly), or a sensible migration can be done.

**Comment by sbelak** [comment]
For saved questions (where we have col metadata) automatic upgrade on the fly is not a problem. Tests will need to be slightly altered, but that's not a big deal (and we should probably use idiomatic MBQL regardless). I'll go ahead and fully implement/integrate this and then do some manual testing to see if it also solves for all the places where FE generates MBQL on the fly (drill downs and such).

**Comment by sbelak** [comment]
Going through the list of bugs got me deep into also fixing what is suppose to be #13714. I don't want too big of a PR, so I'll replace these changes with a provisional fix, so that this part can go into review, and then pickup this work.

**Comment by nemanjaglumac** [comment]
Will this PR fix any of the related issues in #13702? Consequently, are there any Cypress tests I need to unskip and confirm they are indeed passing?

**Comment by sbelak** [comment]
This issue is effectively implemented in #14014. I'll close it once it's merged.

**Comment by flamber** [comment]
This was completely revamped in 0.38 and some in later versions.
