### ISSUE TITLE
Run queries in repeatedly every few mins and alert on condition

### ISSUE THREAD

**Issue by kidambisrinivas** [metabase/metabase#1373]
Is it possible to run few queries repeatedly every few minutes in background and alert on a certain condition to email/slack?

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by salsakran** [comment]
Not yet. We are looking at adding alert functionality though. Stay tuned. We'll edit this issue as we scope it out.

**Comment by kidambisrinivas** [comment]
Thanks for getting back to me on this. Is there a timeline all the users could expect this feature to be available by, so that we could plan for it accordingly?

**Comment by salsakran** [comment]
This feature concept is *very* preliminary at this point. 

We're generally going to be prioritizing feature development by community demand. Once it gets critical mass, we'll slot it into the formal roadmap and get an estimate of when it should be expected by.

**Comment by spectr** [comment]
+1

**Comment by hukev** [comment]
I'd like to build an alert that sends ID's of messages that contain certain search terms. The messaging has low turnaround time, so it'd be ideal if we could check as frequently as we are ingesting data, and not send a pulse if there's nothing new (nothing returned by the query, if the query is limited to the time between checks).

**Comment by mamaya881** [comment]
+1

**Comment by Anitha-Vallikunnel** [comment]
Any update on this ?

**Comment by luqmansyauqi** [comment]
Any update? This would be super helpful to alert when certain condition met.

**Comment by taker93** [comment]
+1

**Comment by bacheson** [comment]
+1
This feature would allow me to replace stackdriver's terrible charting...it really changes metabase from a nice to have to a must have

**Comment by igisho** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by vijayvenkatesh** [comment]
👍

**Comment by camsaul** [comment]
@vijayvenkatesh, did you see the comment I left right before yours? 😒 Instead of leaving +1 or 👍 comments, PLEASE just upvote by adding a reaction to the issue description.

😒

**Comment by vijayvenkatesh** [comment]
@camsaul it's all good - was just excited to see this ticket because it's something we're looking for - sorry. fixed.

**Comment by ArghyaSarkar** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by camsaul** [comment]
Implemented by #6278
