### ISSUE TITLE
Dashboards should work if individual cards are broken

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#13736]
Dashboards should be robust to errors in specific visualizations. Cam pointed this out in #13721

The card on the left raised an exception while rendering. Both cards appear stuck loading:

![image](https://user-images.githubusercontent.com/691495/98561003-5efc2400-2276-11eb-949d-5fdcd506109a.png)

**Comment by flamber** [comment]
Very related to #12606

**Comment by flamber** [comment]
Changing to bug, since I have seen this too many times for it to "just" be tech debt. Example #16150 (see Workaround in description)

**Comment by WiNloSt** [comment]
Doesn't seem to happen on `master` at 24f1cc91069341d18650483b6e9fc366c9dc19f1 anymore
![image](https://github.com/metabase/metabase/assets/1937582/d15bf40c-3b1b-4334-b146-d578e2322072)
