### ISSUE TITLE
No time buckets when editing the grouping in the existing question

### ISSUE THREAD

**Issue by easeev** [metabase/metabase#13730]
**Describe the bug**
I cannot choose the time bucket when editing the grouping in the existing question. Looks like regression as it works on v0.36.0 installation.

**To Reproduce**
1. Go to an existing question
2. Go to editor
3. Scroll down to `Summarize` ... `by`
4. See no time buckets

![image](https://user-images.githubusercontent.com/14873170/98498084-d8007900-2280-11eb-875c-f9b47505e0ee.png)

**Expected behavior**

I should be able to see the time grouping bucket:

![image](https://user-images.githubusercontent.com/14873170/98498418-adfb8680-2281-11eb-8416-0ed397f157e2.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-8u272-b10-0+deb9u1-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_272",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "5.4.49+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.0.2",
      "date": "2020-10-26",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": "Asia/Kuala_Lumpur"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @easeev 
Please post response of `/api/field/:id`, where id is what you get from Admin > Data Model > (database) > (table) > (column) :gear:
I cannot reproduce, so it must be something specific to the field or how you have created the question.
If you can reproduce with Sample Dataset, then please post that.

**Comment by easeev** [comment]
>I cannot reproduce, so it must be something specific to the field or how you have created the question.

The same field breaks down in the buckets well if I create a new question with it (see 2nd screenshot). So the issue is definitely in the question itself (which I don't want to re-create as it's quite complicated and I have a few of those). How can we troubleshoot this further?

**Comment by flamber** [comment]
@easeev 
Since it's something specific to your setup, then I don't know what to look for without a lot more information. Not sure why it's not showing the binning/granularity, but I don't know how you have created the question either. Also check the browser console for errors.

**Comment by easeev** [comment]
BTW I noticed that if you clean up all conditions and keep just the original data source, some of the query artifacts are cached which breaks the question:

![image](https://user-images.githubusercontent.com/14873170/98762765-57be4d00-2413-11eb-84a3-efccdbdf4c78.png)

Maybe this behavior contributes to the original problem with time buckets that stop appearing in the editor. Please note that it reproduces only if you **edit the existing saved questions**, for new questions everything works as expected.

We're currently evaluating Metabase Enterprise, so hopefully non-breaking question editing can be addressed, as one would expect it to work in a $10K+/month product.

**Comment by flamber** [comment]
@easeev It's close to impossible to know what's going on without reproducible steps and errors. I'm sure there's a JS error somewhere, which causes problems in the UI and which then doesn't update everything correctly when viewing the query.

**Comment by easeev** [comment]
@flamber any comments on https://github.com/metabase/metabase/issues/13730#issuecomment-725156050? Should I file a new issue on that?

**Comment by flamber** [comment]
@easeev Without steps-to-reproduce or errors, then it will be close to impossible to fix.
https://www.metabase.com/docs/latest/troubleshooting-guide/bugs.html#reporting-a-bug
