### ISSUE TITLE
Login Failing for LDAP if user email isn't lowercase

### ISSUE THREAD

**Issue by bkrn** [metabase/metabase#13739]
**Description**

After upgrade from v0.36.8.1 -> v0.37.0.2 login using LDAP auth fails with the following message

ERROR: duplicate key value violates unique constraint "core_user_email_key" Detail Key (email)= (<user email here>) already exists.

**To Reproduce**

Attempt to login after above migration.

The emails in our DB are all lower case ( presumably caused by migration related to https://github.com/metabase/metabase/issues/3047 ). If we update a core user email to be the same case returned by our LDAP server then login proceeds as normal. This makes me think that, somewhere, just lower casing the email field returned by LDAP solves this.

**Expected behavior**

Metabase shouldn't try to create a new user when logging in via ldap and login should succeed as normal

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.198-152.320.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**

We have a work arounds but they involve either a roll back or editing the production database to change the email field back to the  cases provided by our LDAP server. I think I'd call this severe at least for our environment.

**Additional context**

Just thank you! Let us know if there is anything we can do to help.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Manually updating the `core_user.email` to match the casing of the LDAP will then make the logins work correctly.
For reference: 
https://discourse.metabase.com/t/ladp-login-no-longer-working-due-to-lower-case-email-vs-upper-case-lower-case-ad-email/12197
https://discourse.metabase.com/t/ldap-authentication-issue/12141

**Comment by bkrn** [comment]
For anyone coming through here on postgres, you might be in a position like us where the email column's conversion to citext taking place in migrations 269-272 [here](https://github.com/metabase/metabase/blob/1208f227fd7d221d517dc71e26cecbe60a45731e/resources/migrations/000_migrations.yaml#L7673) failed because the metbase DB user didn't have permission to load the extension. Doing that type switch manually might be a lighter touch fix for you than mapping emails to the casing from LDAP.

**Comment by denis-troyan** [comment]
Dear @bkrn, I tried updating the column to citext, but the login fails anyway. 
![image](https://user-images.githubusercontent.com/30465788/100599681-9f444480-3300-11eb-8e55-09448d30fdb4.png)

![image](https://user-images.githubusercontent.com/30465788/100599720-ad926080-3300-11eb-950a-58b584d8ee94.png)
The email is set as D.Troyan@vtb.eu in LDAP, whereas it appears in lower case in core_user: d.troyan@vtb.eu: 
![image](https://user-images.githubusercontent.com/30465788/100600192-3f9a6900-3301-11eb-946a-776014d05dce.png)

Updating the email in core_user to match with LDAP works correctly. However, new users signing up via LDAP are created in core_user with lower case email, so that I have to perform such update for each newcoming user manually.

**Comment by etoulas** [comment]
Another option is to change the email to lower case in LDAP. That worked for us. Right after that the user could log in again.

**Comment by panpakos** [comment]
Any plans for fixing it?

**Comment by QCaudron** [comment]
We are having the same issue. I first log into a fresh Metabase 0.38.2 with `Quentin.Caudron@xxxx.com`. I'm able to get in, and a new record is added into `public.core_user` with email `quentin.caudron@xxxx.com`. My actual email, per the LDAP system, is `Quentin.CAUDRON@xxxx.com`. The result is that I can't log in a second time, and I need to manually edit my email in `public.core_user` to the last of the three variants here.

I am strongly in favour of making this case-insensitive everywhere.

**Comment by nadilas** [comment]
Can we bump the priority on this one? This is really hurting the so far amazing image of metabase.

**Comment by ProjectCleverWeb** [comment]
Can confirm this is still happening in 38.2

**Comment by nadilas** [comment]
I'm ready to jump in and help fix the issue if you could provide a pointer at which file to begin with

**Comment by camsaul** [comment]
It seems like if we just lowercase the emails when we get them back from LDAP everything should work correctly -- should be an easy fix
