### ISSUE TITLE
Support connecting to MongoDB replica sets / master-slave configurations

### ISSUE THREAD

**Issue by iiSeymour** [metabase/metabase#1374]
Currently when adding a MongoDB database you can only provide a single host. Support for replica set connections would be great.

**Comment by nodesocket** [comment]
We are running a 3 member replica set, and manually point metabase at a slave. This works, because we set a server to have a higher priority than the other two servers, which has the benefit that that server is primary unless it is down.

**Comment by Serfenia** [comment]
Would love to see the support for replica sets. Currently it is not possible to read from secondaries.

**Comment by camsaul** [comment]
Implemented by #4971

**Comment by davidmir** [comment]
But we still can not give him more than a host?

**Comment by j** [comment]
@camsaul how do you specify the list of mongo hosts?   It still supports just one host

**Comment by camsaul** [comment]
@davidmir @j yeah, we haven't added support for that yet. We have an open issue for it: #5084
