### ISSUE TITLE
Incomplete export of data from Edge browser. 

### ISSUE THREAD

**Issue by dylanbstorey** [metabase/metabase#13758]
**Describe the bug**
Data doesn't completely export when using Edge browser.

**Logs**
N/A

**To Reproduce**
1. Open Edge
2. Run a query
3. Click on Export -> save as CSV/Excel
4. Download doesn't contain all data. (well below the export cap)

**Expected behavior**
All data should be available in export.

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely? Annoying - just bringing to your attention.  
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.84-33.70.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "sqlserver",
      "redshift",
      "h2",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-30",
      "tag": "v1.36.6.4",
      "branch": "enterprise-release-1.36.6.x",
      "hash": "4ad7c1c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @dylanbstorey 
Please upgrade to 1.36.8.2 or latest 1.37.0.2, which has a lot of fixes for exports.
And without knowing which database you're exporting from or what you mean by "well below the export cap" it's hard to debug.
