### ISSUE TITLE
metabase date filter

### ISSUE THREAD

**Issue by erma07** [metabase/metabase#13775]
If the field type is date then why is metabase handling it as datetime?

The problem I have is with postgresql and clickhouse_fdw. Need to be able to do a date filter with date string eg date = '2020-11-12' and not datetime eg date = '2020-11-12 22:00:00'.  Is there a special date type for this?

ERROR: clickhouse_fdw:Code: 53, e.displayText() = DB::Exception: Cannot convert string 2020-11-12 22:00:00 to type Date: while executing 'FUNCTION greaterOrEquals(date, '2020-11-12 22:00:00') UInt8 = greaterOrEquals(date, '2020-11-12 22:00:00')' QUERY:SELECT date, title,price n FROM x.clickhouse_y_arch WHERE ((date >= '2020-11-12 22:00:00')) AND ((date < '2020-11-13 22:00:00')) LIMIT 2000

**Comment by flamber** [comment]
Hi @erma07 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Without knowing Metabase or driver versions, then it's difficult to know. Or the column Field Type in Admin > Data Model.
