### ISSUE TITLE
Logging not working in EB 0.37.0.2

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#13776]
After deploying the version 0.37.0.2 (from 0.36.7) using ElasticBeanstalk, the logs are not available. 
In the admin panel, when I go to logs, it shows a spinning wheel only.
I SSHed to the EC2 instance that EB was using, the following are the only logs from docker:
```
Picked up JAVA_TOOL_OPTIONS: -Xmx1500M
ERROR StatusLogger Reconfiguration failed: No configuration found for 'Default' at 'null' in 'null'
ERROR StatusLogger Reconfiguration failed: No configuration found for '22367b8' at 'null' in 'null'
Warning: environ value jdk-11.0.7+10 for key :java-version has been overwritten with 11.0.7
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Load driver :sql took 280.4 ms
Load driver :sql-jdbc took 11.2 ms
Load driver :postgres took 142.8 ms
Database setup took 4.6 s
```
I tried restarting the App server, and even re-deploying, but it didn't change anything.
I've now moved back to v0.36.8.2 and the logging is working fine.

**Comment by flamber** [comment]
Hi @vvaezian 
Please post all environment variables you're setting. I'm guessing you're setting `log4j.configuration`, but that has been deprecated in favor of Log4j version 2 since Metabase 0.37.0, which uses `log4j.configurationFile`.
https://www.metabase.com/docs/latest/operations-guide/log-configuration.html

**Comment by vvaezian** [comment]
Your guess is right. I was using the following config (I had added this a few months ago to troubleshoot an LDAP issue).
`-Dlog4j.configuration=https://log4j.us/templates/metabase?trace=metabase.integrations.ldap,metabase.api.ldap`

I removed this and the logging is working fine now.
