### ISSUE TITLE
Can't undo hide, can't build a model? There's been no response

### ISSUE THREAD

**Issue by liangrui1988** [metabase/metabase#13777]
![image](https://user-images.githubusercontent.com/7435076/99041050-2a190580-25c5-11eb-9e5a-83703a18b99e.png)
取消不了隐藏了，无法建模型了？ 点了一直没反应
Can't undo hide, can't build a model? There's been no response

version  0.37.0.2

**Comment by flamber** [comment]
Hi @liangrui1988 
Post "Diagnostic Info" from Admin > Troubleshooting.
And check the logs for errors - Admin > Troubleshooting > Logs.
