### ISSUE TITLE
In Firefox the scroll bar gets stuck after some operations

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#13773]
**To Reproduce**
- If your screen is really wide, resize your browser window so that in the next steps you see the horizontal scroll bar.
- Sample Dataset > Reviews > Summerize [count] >  Done
- Now press back to see the REVIEWS table again. Try to move the horizontal scroll bar to the right.

I have been seeing this behavior in Firefox since the new release of MB. After some operations the scroll bar gets stuck. I don't use Chrome that often. I tested the above case in Chrome, and there was no issue there. 

Firefox 82.0.3 (64-bit). This is the latest version. 
Metabase v0.37.0.2

**Comment by flamber** [comment]
Hi @vvaezian 
We're a now a few people mainly using Firefox, but I haven't seen the problem you're describing and I cannot reproduce.
Are you able to do a screen recording (or perhaps screenshots are sufficient)?
I have a feeling that it might be related to #10339

**Comment by vvaezian** [comment]
This is the screen capture of the issue mentioned above (now I'm using 0.37.1).

![scroll1](https://user-images.githubusercontent.com/15974735/99103839-0b027f80-2595-11eb-9014-b74084f7415d.gif)

A possibly related issue is that, sometimes when pressing the Back button, nothing happens:

![scroll2](https://user-images.githubusercontent.com/15974735/99103951-2e2d2f00-2595-11eb-91bd-610f9fba65b2.gif)

**Comment by flamber** [comment]
@vvaezian Awesome with videos - makes it much easier to understand.
I'm 99% sure the browser console should have errors, specially on the last problem.
But I have a feeling that one of your browser add-ons is causing the problems - can you try in Private-Window or with add-ons temporarily disabled?

**Comment by vvaezian** [comment]
I tried using a private window, but it didn't work there either.

This is the warning on the console when I try to scroll:
`This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!`

**Comment by flamber** [comment]
@vvaezian I can reproduce the second problem on Firefox with `window.innerWidth=1460`, but only when first column of the table is not Entity Key.
One thing that I'm noticing is that the URL actually changes the base64 request string, when clicking back, but it's not triggering any new request or other visual changes.
Think there might be a race-condition somewhere, which isn't a problem in Chrome (or handled just in time).

**Comment by uladzimirdev** [comment]
I cannot reproduce both issues on the `0.47.1` `a6815ce0f9` and on `0.39.5` on firefox 117
