### ISSUE TITLE
Sometimes Metabase automatically pivots data without the user asking for it

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#13772]
**To Reproduce**
Sample Dataset > Products > Summerize > Number of distinct values of PRICE > group by RATING (don't bin) and TITLE.

![pivot 0](https://user-images.githubusercontent.com/15974735/99003686-5401f780-24f3-11eb-94bf-c39d71ff5748.png)

The automatic pivoting confuses the users. Also on real data, sometimes the automatic pivoting produces an "Unset" column, which adds to the confusion:

![pivot 2](https://user-images.githubusercontent.com/15974735/99004310-b3f89e00-24f3-11eb-9811-054a7581480b.png)

**Expected behaviour** 
It should pivot only when the user asks for it by toggling the "Pivot the table" button in the Settings.

- v0.37.0.2 (but have seen this behavior in previous versions as well)

**Comment by flamber** [comment]
That has always (?) been the default to auto-enable Pivot, when there's 1 metric and 2 groupings:
https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#pivoted-tables
But I can see that people have been confused by the auto-enable in the forums.

**Comment by metamben** [comment]
@paoliniluis I can't seem to reproduce this issue, can you?

**Comment by brunobergher** [comment]
Not reproducible.
