### ISSUE TITLE
Why is database_type OLDDECIMAL？

### ISSUE THREAD

**Issue by songchuangyuan** [metabase/metabase#13802]
For help with installation and setup, information on how specific features work, or general questions about Metabase, please use our discussion forum:

https://discourse.metabase.com

The Github issue tracker is intended to collect bug reports and feature requests.
Any issues open for help requests will be closed to keep from clogging up the issue tracker.

One field in MySQL table is of type decimal. When I execute the SQL statement to get the list and type of fields in my MySQL database, the results are as follows:
           TABLE_CAT: mydb
       TABLE_SCHEM: NULL
        TABLE_NAME: table_hash
       COLUMN_NAME: k2
         **DATA_TYPE: 3**
         TYPE_NAME: NULL
       COLUMN_SIZE: 10
     BUFFER_LENGTH: 65535
    DECIMAL_DIGITS: 2
    NUM_PREC_RADIX: 10
          NULLABLE: 0
           REMARKS: 
        COLUMN_DEF: NULL
     SQL_DATA_TYPE: 0
  SQL_DATETIME_SUB: 0
 CHAR_OCTET_LENGTH: NULL
  ORDINAL_POSITION: 2
       IS_NULLABLE: NO 
     SCOPE_CATALOG: NULL
      SCOPE_SCHEMA: NULL
       SCOPE_TABLE: NULL
  SOURCE_DATA_TYPE: NULL
  IS_AUTOINCREMENT: NO
IS_GENERATEDCOLUMN: NO

However, when I checked in metabase, I found that the type of this field was not recognized as decimal. The 'database_type ' attribute of the field was **OLDDECIMAL**, and the attribute base_type was ‘type / *’ .

Why is that?

**Comment by flamber** [comment]
Hi @songchuangyuan 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
If you're creating a bug report, then please use that template and include all the requested information.
