### ISSUE TITLE
Improve drill-down options for scatter plots of unaggregated data

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#13807]
The options currently available when clicking on a point in a scatter plot of unaggregated data are pretty nonsensical. As an example, here's what I see when plotting Orders by the variables of Quantity and Subtotal, where each point usually only represents a single Order except in cases where the quantity and subtotal are exactly the same.

In this situation, of the actions in the menu, the ones I would actually want to click are:
- Viewing this/these orders
- Maybe filtering, particularly if there were an option to "exclude this"
- X-ray/compare

The rest seem pretty weird — why would I want to see the sum of a single row, and which column am I even summing? Why would I want to sort this, and what would that even do? _Formatting??_

<img width="469" alt="image" src="https://user-images.githubusercontent.com/2223916/99281120-03d2b000-27e7-11eb-9817-27b013b56e19.png">

**Comment by brunobergher** [comment]
Not applicable anymore.
