### ISSUE TITLE
API allows `count(field)` which kills the metrics page

### ISSUE THREAD

**Issue by jankatins** [metabase/metabase#13814]
**Describe the bug**
We had a naive implementation of sending a `count(field)` metric via the API. It didn't throw an error. Looking then at the metrics page lead to error in the console and no metrics showed up.

We posted something like this to http://127.0.0.1:3000/api/metric `{"name": "# whatever Entities", "description": "Number of entities which reached step whatever of the funnel", "table_id": 4, "definition": {"source-table": 4, "aggregation": [["count", ["field-id", 88]]]}, "show_in_getting_started": false, "how_is_this_calculated": "count(onboarding_contract_signed_talent_id)", "revision_message": "Auto schema import"}`

This showed up properly in the metrics table: `{"source-table":4,"aggregation":[["count",["field-id",102]]]}` (different field, same story)

**Logs**

Stepping through this, it seems the endpoint does not send out the aggregation field for all the count(field) defined metrics and that crashed the UI:

```
Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.z [as aggregation] (app-main.bundle.js?23fd7ef5938b75765692:5)
    at app-main.bundle.js?23fd7ef5938b75765692:5
    at Array.map (<anonymous>)
    at t.formatQueryDescription (app-main.bundle.js?23fd7ef5938b75765692:5)
    at t.value (app-main.bundle.js?23fd7ef5938b75765692:5)
    at c._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js?23fd7ef5938b75765692:436)
    at c._renderValidatedComponent (vendor.bundle.js?23fd7ef5938b75765692:436)
    at c.performInitialMount (vendor.bundle.js?23fd7ef5938b75765692:436)
    at c.mountComponent (vendor.bundle.js?23fd7ef5938b75765692:436)
    at Object.mountComponent (vendor.bundle.js?23fd7ef5938b75765692:92)
```

**To Reproduce**

For the metrics page to screw up:

1. define an avg(field) metric in the UI
2. Go to the DB and change the avg to count (or submit such a thing via the API)
3. Go to the Admin -> Data model -> metrics page -> it doesn't load 

for the API accepting bad metrics definitions:
* see above the definition of the request which includes `"aggregation": [["count", ["field-id", 88]]]}`

**Expected behavior**

* The API does not accept malformed metrics 
* The metric page loads even if there is an error in the data model

**Information about your Metabase Installation:**

Both 0.37.1 and 0.36.6 show this

**Severity**

It's highly annoying, but at least now I know why this is happening and I can manually remove the bad metrics via API or DB connections. 

And it's really annoying that there is no `count(field)` aggregator (https://github.com/metabase/metabase/issues/11558).

**Comment by flamber** [comment]
Pretty sure this is because the backend (MBQL) actually supports `count([column])`, so that's why the API doesn't error, but the frontend might be breaking something, since that is not supported yet #11558 #12631.

**Comment by jankatins** [comment]
I can confirm this with 0.37.1: If I summarize a data set which has a api defined count(field), I get the correct SQL when I convert that to it:


```SQL
SELECT 
count(*) AS "count",  -- the default "Count" aggregation
count("datasets"."Whatever"."# Condition Whatever") AS "count_2" -- our API setup count(field) one
FROM "datasets"."Whatever"
```

So this is basically a UI problem only because it breaks the metrics page

**Comment by ranquild** [comment]
Works in master (v50) 
<img width="741" alt="Screenshot 2024-06-26 at 14 55 22" src="https://github.com/metabase/metabase/assets/8542534/d803e603-99d8-4cea-bad6-7918cd618a09">
