### ISSUE TITLE
Cannot map users to Admin group

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13820]
**Describe the bug**
In the UI for group mappings for SAML/JWT/LDAP SSO authentication:
> Membership to the Admin group can be granted through mappings, but will not be automatically removed as a failsafe measure.

But when selecting the Admin group, then it has no effect during the login process, so the user never gets Admin access, only the regular groups are correctly assigned to the user.
![image](https://user-images.githubusercontent.com/1447303/99428343-cf561580-2906-11eb-8ca8-b2d3199debf4.png)

**Expected behavior**
Should have the ability to map users to the Admin group.

**Information about your Metabase Installation:**
Metabase x.37.2
Reference: https://github.com/metabase/metabase-enterprise/issues/445 EE445

**Comment by flamber** [comment]
Fixed by #14993

**Comment by paoliniluis** [comment]
Reopening, issue is happenning again

**Comment by noahmoss** [comment]
I don't think this is actually a regression -- rather, it was never really working properly in the first place.

Prior to #14993, the text on the UI read "Membership to the Admin group can be granted through mappings" but this did not work on the backend for any SSO method.

#14993 added an enterprise-only toggle in the LDAP config form that enables syncing the admin group. This is the current state of the code base.

So basically:
* On EE, admin group sync should work for LDAP _if_ the toggle is enabled. It doesn't work for JWT or SAML.
* On OSS, admin group sync doesn't work for any SSO method.

I think there are a couple of product questions we need to answer before we can close out this issue:
* Should admin group sync still be an EE-only feature?
* Should this still be enabled by a toggle (and disabled by default), or should it work automatically if the admin group is mapped, as the copy on the UI implies?
* Should we keep the policy that the UI currently states of not _removing_ users from the admin group via sync?
* What should the copy on the UI actually say?
