### ISSUE TITLE
Native question "Filter widget type"="None" hides the filter widget even after changing it to something else

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13825]
**Describe the bug**
Changing "Filter widget type" to None, then it's not possible to restore the widget by changing it back again.

**To Reproduce**
1. Native question > Sample Dataset > `SELECT COUNT(*) FROM PRODUCTS WHERE {{cat}}`
2. Set `cat` variable in sidebar to "Variable type" to "Field Filter" and "Field to map to" to "Products.Category"
![image](https://user-images.githubusercontent.com/1447303/99460986-3092de80-2931-11eb-937a-8b67eca9f2c8.png)
3. Change "Filter widget type" to "None", and then set it back to "Category" - notice the filter widget is now gone from top of the editor. Save the question, refreshing the browser, switching "Filter widget type" around makes no difference.
4. To restore the widget, re-select the "Field to map to"

After selecting "None", then it doesn't save `"widget-type"` in `report_card.dataset_query` anymore, until following step 4.

**Information about your Metabase Installation:**
Metabase 0.35.0 thru 0.37.2 (works in 0.34.3)

**Additional context**
Almost P2, since this is really tricky to understand what's going on and I'm sure it adds the the confusion of Field Filters.
https://discourse.metabase.com/t/field-filters-work-correctly-in-dashboard-do-not-appear-in-question-editor/12361

**Comment by nemanjaglumac** [comment]
Even more confusing thing for me was having the ability to set the non-existing "None" filter as required and enter its default value. It's not just weird UI/UX, it also produces different results.

1. Set the filter to "None"
2. Run the query -> Gives you all the rows
3. Mark it as required
4. Run the query -> Gives you an error
5. Enter default value "foo"
6. Run the query -> Shows "No results"

@flamber If we don't have this as an issue already, I'd like to file one.

**Comment by flamber** [comment]
@nemanjaglumac It's actually a feature - albeit confusing. It does everything underneath, just like if the widget was there. Considering how difficult it is to under Field Filters, then I think it's time perhaps remove the "None" completely.

**Comment by mazameli** [comment]
My historical understanding of why there's a `None` option for the filter widget is so you could make the SQL query uninteractive on its question detail view, while allowing it to be filterable when added in a dashboard. I don't know how common or real that scenario is, though, and I trust that @flamber has a much more up-to-date understanding of how important or not that None option is.

At minimum we should fix this bug and let you switch back from None to another widget type. But I agree with @nemanjaglumac that it's confusing to have no widget, then be able to make the variable required — it seems like in that scenario that the user should need to enter a default value so that the query doesn't error.

So, to reiterate — if @flamber doesn't think it'll be problematic to remove the None option, I'm on board.

**Comment by nemanjaglumac** [comment]
If we want to keep "None" for that purpose of linking dashboard filters to the dashboard, does it make sense to at least completely remove this part (label, required toggle and the default value input field)?

![image](https://user-images.githubusercontent.com/31325167/124813360-14e25400-df65-11eb-9946-16a08588a70a.png)

**Comment by flamber** [comment]
@mazameli I have never seen anyone using the "None" (on purpose). But I would need to dig into this a lot more, and how we could handle it gracefully for all types (in-app, public, embedding), since we don't want to show widgets suddenly if someone actually used it explicitly (or at least make an important release note for a major version).

@nemanjaglumac We do not want to remove those. Otherwise you have zero control over questions and would require to always use dashboards. A lot uses single questions during embeds etc.

**Comment by nemanjaglumac** [comment]
> We do not want to remove those. Otherwise you have zero control over questions and would require to always use dashboards. A lot uses single questions during embeds etc.

@flamber I meant removing that part only when someone selects "None". Not removing them in general.
