### ISSUE TITLE
Default Column Order appears to have changed for existing questions created via Notebook editor

### ISSUE THREAD

**Issue by VaiteLR** [metabase/metabase#13828]
**Describe the bug**
I created questions using the Notebook Editor. Default column order used to suit my needs well: it was the same order as in the tables. 
However, when I opened the same requests yesterday and today, column order has been changed and is now alphabetical. This makes it far less user-friendly. 

I had to manually reorder all the columns for the existing questions I had to fix at the time, but couldn't find in Admin settings or anywhere a way to change the default ordering of columns for all other notebook questions. 
As it was a pain to drag all these columns, I've also upvoted https://github.com/metabase/metabase/issues/13455.

This default alphabetical order is also observed for New questions created with the Notebook editor. I can't remember if that was the case before, but what I am 100% certain of is that my existing questions have had their column orders changed. 

**Logs**

**To Reproduce**
1. Go to an existing notebook question. See that all the columns have been reordered alphabetically both in the Visualization and Table mode, in the Visualization parameters menu, in the Notebook editor columns list (and possibly on all related screens).  

**Expected behavior**
I expected the order I had initially used – order of columns in my original tables. The primary key "id" should therefore be the 1st column, not appear in the middle of my Metabase table.

**Screenshots**

**Information about your Metabase Installation:**
0.37.1
Chrome 86.0
Mac OS 11.0.1 Big Sur
Postgres  

**Severity**
Very annoying: If this isn't solved fast, I might need to manually drag about 10 columns per question x200 existing questions...

**Additional context**

**Comment by flamber** [comment]
Hi @VaiteLR 
Did someone perhaps change the column order in Admin > Data Model > (database) > (table) > "Column order" dropdown:
![image](https://user-images.githubusercontent.com/1447303/99514853-80eb5a00-298c-11eb-8915-c5f108f8c66a.png)
