### ISSUE TITLE
Tooltip pie chart not internationalized

### ISSUE THREAD

**Issue by khmDEV** [metabase/metabase#13830]
The word "Percentage" in the tooltip Chart is not internationalized:
![image](https://user-images.githubusercontent.com/1251819/99529482-2bb94380-29a0-11eb-874c-fe1958411539.png)

I assume the problem is in frontend/src/metabase/visualizations/visualizations/PieChart.jsx file (line 352):
`                  {
                    key: "Percentage",
                    value: formatPercent(slice.percentage),
                  },`

But I've never dev for Metabase, and I don't know how internationalization is done in React (if it does, because I can't find any examples in the code).
Thanks

**Comment by flamber** [comment]
Closing in favor of #11542

**Comment by mazameli** [comment]
@khmDEV, in case you were curious, we use [ttag](https://ttag.js.org) for internationalization, and the syntax for this fix looks like this:

```
{
  key: t`Percentage`,
  value: formatPercent(slice.percentage),
}
```
