### ISSUE TITLE
Trigger pulses/ alerts using API

### ISSUE THREAD

**Issue by AntonyLeons** [metabase/metabase#13833]
**Is your feature request related to a problem? Please describe.**

I require pulses to be sent at half an hour intervals, as discussed in #3846. I understand this is complex so i created a separate program to call the api `POST /api/pulse/test`. This is a hack as I have to recreate the pulse I require with api params. this could also resolve automation issues with other systems.

**Describe the solution you'd like**
could I trigger pulses with the api but with pulse ids. 
`GET /api/pulse/trigger/:id`

**Describe alternatives you've considered**
my current work around described above

**How important is this feature to you?**
This has been a long standing issue and i can do the hack workaround

**Comment by flamber** [comment]
Duplicate of #5772
