### ISSUE TITLE
error when fingerprinting json fields

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#13849]
addresses comment https://github.com/metabase/metabase/issues/13767#issuecomment-729834080

Fingerprinting was updated recently to grab only a substring of text fields to prevent high memory usage. The check was to attempt to substring fields with `:base_type :type/Text`. However, postgres JSON/B fields were marked as `:type/Text` and a `:special_type :type/SerializedJSON`. The code did not follow this distinction and would emit calls to `substring(json_column, 0, limit)` causing obvious problems.

There are a few possible ways to address this:
- make the substringing code a bit smarter and aware of older fields which might be labeled as text but are not suitable for substringing
- use liquidbase to update fields which are postgres backed `:database_type "JSON"` to be structural rather than text
- add a way to migrate these in code (i think this is the best way forward overall and have created a separate issue for it for discussion): https://github.com/metabase/metabase/issues/13848

**Comment by sbelak** [comment]
If my understanding is correct, deep down this is either a new sync bug or an instance of #12574: sync should set the new type upon first sync with the new code (see `metabase.sync.sync-metadata.fields.sync-metadata/update-field-metadata-if-needed!`). 

If that is the case, I think the best order (in the sense of effort vs. impact) would be:
1) figure out if this is an instance of of #12574 or a new bug. If new bug, fix that first.
2) Fix #12574 
3) implement #13848

We absolutely should handle JSON and other structured types better, but until we have robust support for that in MBQL as well, the value of such work is limited (things shouldn't blow up of course).
