### ISSUE TITLE
Implement ability to restrict a dashboard filter widget to a single selection

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#13840]
Our categorical dashboard filter widgets allow for multiple selections of values, but sometimes dashboard authors would like to restrict a widget to only accept a single selection.

The proposal here is to add an on/off toggle to the dashboard filter settings sidebar for categorical/state/ID filter widgets to let editors turn multi-select off. The toggle should default to on.

When on, widgets should look and work like they do today. When turned off, users of the widget can only make a single selection, and making a selection should immediately apply the change and close the value selection popover — [see the prototype](https://www.figma.com/proto/rhsr8o9FUSqDGZv8iFpWbL/Single-vs.-Multi-select-Widget?node-id=1%3A30&viewport=-459%2C623%2C0.8564189076423645&scaling=min-zoom). This should work for both List and Searchbox widgets. (I can't recall if input box widgets allow for multiple selections; if they do, e.g. via commas, this toggle could potentially alter that behavior as well.)

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/2223916/99600797-008c1f80-29b3-11eb-9747-f5eff43abe5f.png">

**Links**
- [Design prototype of the single-select widget](https://www.figma.com/proto/rhsr8o9FUSqDGZv8iFpWbL/Single-vs.-Multi-select-Widget?node-id=1%3A30&viewport=-459%2C623%2C0.8564189076423645&scaling=min-zoom)
- eng doc: …
- feature branch: …
- Issue links: https://github.com/metabase/metabase/issues/7605

**Implementation Plan**

**ETA**: MM/DD/YYYY

**Todos**
- [ ] …

**Needs to happen before merge**

- [ ] Design polish
- [ ] String translations
- [ ] Test on case X, Y, Z
- [ ] Write rough pass documents for handoff to customer success

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/25960
