### ISSUE TITLE
Foundational work for handling JSON dicts

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#13848]
This lays out some possible foundational work needed in order to address https://github.com/metabase/metabase/issues/708 "Ability to access fields in JSON Dicts in Postgres driver" (578 upvotes).

Currently we don't have a straight forward way to mark json database fields. Postgres JSON/B fields used to be marked as `:base_type :type/Text`. This led to confusion when attempting to take substrings for fingerprinting and they are now marked as `:type/Structural`, but no migration was made, leaving already-synced fields marked still as `:type/Text`. Mysql has a JSON type but this type is currently totally unrecognized, with `:base_type :type/*` and `:special_type :type/Category`. I suspect lots of other databases behave in a similar manner.

Marking these fields as `:type/Structural` and then a `:special_type` indicating which can help us start to handle JSON values in a proper way in metabase. Alternatively, if we prefer a diffreent structure, being able to change the `base_type` as we like will also help us. Fingeprinters could determine the number which are json dicts vs arrays, capture the top level keys, etc., allowing for more support in the mbql compiler.

It would be nice to implement a way to migrate these `:base_type` properties of Fields, similar to what exists for `:special_type` when fingerprinting. The `fields-to-fingerprinting` function constructs a query based on which fingerprinters have been updated. Some mechanism like this would be helpful to upgrade the types of fields that can be updated.

Proposal
- a way to upgrade field `:base_type` rather than just liquidbase style migrations
- correct all drivers to correctly mark json fields (also xml fields?)
- migrations for the fields from whatever base types they currently have to `:type/Structural`

Extra nice to haves
- field properties history. The special_type is set in the classification namespaces. Sometimes it is unconditionally set. Othertimes it is only set if it is nil. It would be nice to have history so that classifiers could overwrite what a previous version of metabase decided while respecting what a user might have manually set. I consider this almost mandatory but putting this here
- better classification strategy: currently four classifiers are run and they are highly order dependent. If a previous step makes a decision, a later step cannot overwrite this as it can no longer distinguish if the special type was set by the user, by a previous classification run, or by a classifier in this analysis but just in a previous step. It would be nice if there was a way to choose the _best_ special type from all classifiers and resolve conflicts.
- fingerprinters for structural types: mark if maps/vectors. if dicts accumulate top level keys, etc

## Sample mysql json type

```sql
CREATE TABLE t1 (jdoc JSON);
INSERT INTO t1 VALUES('{"key1": "value1", "key2": "value2"}');
```

```clojure
(select-keys (first example-fields) [:database_type :special_type :name :fingerprint :base_type])
#_ ->
{:database_type "JSON",
 :special_type :type/Category,
 :name "jdoc",
 :fingerprint {:global {:distinct-count 1, :nil% 0.0}},
 :base_type :type/*}
```

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jmealo** [comment]
This covers the breadth of the task well, but for a new contributor; it's difficult to gauge the complexity of the core feature relative to the required plumbing and the nice to haves. It sounds like the work surrounding this feature is non-trivial.

Have you considered fleshing this out a bit into a RFC spec and a list of unknowns/research tasks?

I'm interested in what it would take to expose a JSON path field filter with auto-complete to the UI and remove any limitations on JSON fields for PostgreSQL.

**Comment by jeff303** [comment]
Another thing that may be worth mentioning is that this sort of thing can get pretty crazy in Spark.  Have a look at the discussion of Complex types [here](https://spark.apache.org/docs/latest/sql-ref-datatypes.html).  In short:

- `ArrayType` is an array of other types (including other complex types).  Handling would likely need to be similar to #2974.
- `MapType` is a map with homogenous key and value types (and again, other complex types could be used for either the key or value here).
- `StructType` is the basic struct/record type.  Each row in a Spark "table" is this type, and each column is a `StructField`, but additional structs can appear at any level of nesting.

**Comment by kulyk** [comment]
✅ Implemented
