### ISSUE TITLE
Allow questions to save even with no results

### ISSUE THREAD

**Issue by dnmabra12** [metabase/metabase#13861]
SQL questions do not currently allow the user to save if there is no results from the query. This becomes a pain point when I am writing a query that I don't expect to have results, such as a validation query, or something needed for a pulse that uses a relative date filter. There may be no results returned now, but we expect there to be some in the future. 

Although, you can make dummy results, re-write the query, and then save before running the actual query, this is rather frustrating to do. 

Can we allow questions to be saved even when results are not returned?

**Comment by flamber** [comment]
I cannot reproduce on 0.37.2, but this sounds more like a bug than a feature request, so please provide steps-to-reproduce.

**Comment by dnmabra12** [comment]
@flamber  apologies, put it under feature request since it is expected behavior. 

Steps to reproduce:

- Use 'Write SQL' to create query, with no expected output such as: `SELECT id FROM public WHERE id IS NULL`
- Assuming id is not nullable, query should return 'No Results' 
- Click Save. Metabase returns error that 'Save Failed' 

The request was for the above to successfully save, even when no results

**Comment by flamber** [comment]
@dnmabra12 I cannot reproduce. Try 0.37.2, otherwise please open a new issue with full details on how to reproduce.
