### ISSUE TITLE
Question Excel Export does not match the questions result set

### ISSUE THREAD

**Issue by DirkDigglerZa** [metabase/metabase#13870]
Hi there,

I have a question in metabase that is in a dashboard. This dashboard is embedded in 3rd party application.

The question takes in up to 4 parameters and works correctly. We noticed when exporting the results via the metabase export
functionality, that the excel extract did not return the same results that are in the questions result set. The csv and json extract work correctly and return the correct data as per the result set of the question.

I ask if there is perhaps something I am missing, or if this is a known issue.

**Comment by flamber** [comment]
Hi @DirkDigglerZa 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Or file a bug report with complete details and steps-to-reproduce.
