### ISSUE TITLE
Pulse Scheduling Throws "org.quartz.JobPersistenceException: Couldn't store trigger" Error

### ISSUE THREAD

**Issue by VictorGeaGarcia** [metabase/metabase#13880]
**Describe the bug**
Pulse Scheduling is not working. When creating a pulse and clicking on test now (see image below) it works. I receive the pulse in Slack and mail. However, I never get this alert and there are the errors in logs pasted below.

The pulses are correctly created since I can see them in the Questions and in the DB.

I've seen some other related bugs, but I didn't see this exact error mentioned in any of them. 
- Bugs/Issues related to running Java Headless version, which is not my case.
- Bugs/Issues related to Timezones: My Metabase and DB timezones are UTC.

Investigating a bit I see that this "StreamCorruptedException: invalid stream header: EFBFBDEF" could indicate some problem with type conversions..but it wouldn't make much sense that there is any problem fetching and sending the data here since the testing part works.

I've seen some recommendations on upgrading as well, but as mentioned before I didn't see this error in the other bugs, so I'm not sure it would make it.

**Logs**
"""
org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.metabase.task.send-pulses.trigger' for 'DEFAULT.metabase.task.send-pulses.job' job:invalid stream header: EFBFBDEF [See nested exception: java.io.StreamCorruptedException: invalid stream header: EFBFBDEF] at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1212) at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1026) at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:975) at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3174) at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3934) at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3955) Caused by: java.io.StreamCorruptedException: invalid stream header: EFBFBDEF at java.base/java.io.ObjectInputStream.readStreamHeader(Unknown Source) at java.base/java.io.ObjectInputStream.<init>(Unknown Source) at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.getObjectFromBlob(StdJDBCDelegate.java:3154) at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:881) at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1194) ... 
"""

**To Reproduce**
1. Go to Create -> New Pulse
2. Name it / Place it in a collection / Pick a question / Set email &/Or slack

**Expected behavior**
I expect Pulses and Alerts to work as expected.

**Information about your Metabase Installation:**

I'm running Metabase on K8s (currently using image: **metabase/metabase:v0.35.4**) and using a MySQL DB (GCP CloudSQL instance). 
 
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.174+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.25-google-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

(setting report-timezone doesn't have any effect either)

**Severity**
- This is blocking an important/nice feature to be working. 

**Screenshots**
Test button image:
![image](https://user-images.githubusercontent.com/26174942/100060022-49692b80-2e2c-11eb-85ff-9649ca320253.png)

**Comment by flamber** [comment]
Hi @VictorGeaGarcia 
Can you show the output of Admin > Troubleshooting > Jobs > View triggers for "metabase.task.send-pulses.job" ?
I have a feeling that you're seeing #10088 - but I haven't seen those specific errors before.
Can you post the full stacktrace?

**Comment by VictorGeaGarcia** [comment]
Hi @flamber ,

When I go to "Admin > Troubleshooting > Jobs" it takes forever and stays as "Loading". In the logs last call is: "GET /api/task/info 200 ..." and no error.

Anyway from the DB I get the following:
![image](https://user-images.githubusercontent.com/26174942/100101385-77696280-2e62-11eb-954f-d6d8957bb618.png)


![image](https://user-images.githubusercontent.com/26174942/100102022-4d647000-2e63-11eb-9891-4cb4dbd71e7d.png)

So latest occurrences are long ago.

If it's not useful can yo let me know what should I run in the DB to get the needed info? Or which table to look at?

**Comment by flamber** [comment]
@VictorGeaGarcia I guess we have the problem there. Could it be that one of the instances in your load balancer is not working?
Check your browser developer Network-tab to see if the requests matches what you can see in the log.
Please upgrade, since there has been hundreds of other fixes - not specific to the scheduler, but I don't think that's your problem.

**Comment by VictorGeaGarcia** [comment]
@flamber No I don't think this is the case. The other sections of Troubleshooting: task/logs/help are working alright. The browser developer tab requests "/api/task/info", same as logs requests "/api/util/logs". The requests are passing through the ingress correclty... I have actually accessed through port-forwarding to a functioning pod and this still happens.

Anyway, how would this other issue relate to the Pulse not working.
And yes I'll upgrade, just that since I didn't see this error like this reported for the other solved issues, I'm not that sure that just upgrading will fix it. So I wanted to check what else could be going on.

**Comment by flamber** [comment]
@VictorGeaGarcia 
Can you post the full stacktrace?
And what's the output of `/api/task/info`?
I'm fairly sure you're seeing some combination #10088, where scheduler gets in a state, where it stops sending anything.

**Comment by VictorGeaGarcia** [comment]
@flamber You mean the full stacktrace with the quartz error? All I see is:

`[1mERROR jdbcjobstore.JobStoreTX[0m :: MisfireHandler: Error handling misfires: Couldn't store trigger 'DEFAULT.metabase.task.send-pulses.trigger' for 'DEFAULT.metabase.task.send-pulses.job' job:invalid stream header: EFBFBDEF
`
And right after, there is always:
```
"org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.metabase.task.send-pulses.trigger' for 'DEFAULT.metabase.task.send-pulses.job' job:invalid stream header: EFBFBDEF [See nested exception: java.io.StreamCorruptedException: invalid stream header: EFBFBDEF]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1212)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1026)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:975)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3174)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3934)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3955)
Caused by: java.io.StreamCorruptedException: invalid stream header: EFBFBDEF
	at java.base/java.io.ObjectInputStream.readStreamHeader(Unknown Source)
	at java.base/java.io.ObjectInputStream.<init>(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.getObjectFromBlob(StdJDBCDelegate.java:3154)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:881)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1194)
	... 5 more
```

 Is there any way I can see more logging, or can I set it somehow to be more verbose?

The output of /api/task/info is nothing at all. In the browser it keeps showing loading forever, and there is no response at all in developer mode  network tab. Using curl doing port-forwarding to the pod where Metabase is running, I get nothing as well (i'm sure I'm doing the api calls correctly because other calls are working and returning results)

![image](https://user-images.githubusercontent.com/26174942/100128690-e1910000-2e80-11eb-9b3e-50885965e48f.png)

**Comment by flamber** [comment]
@VictorGeaGarcia Looks like the scheduler is completely broken. Have never seen that before. A restart would probably solve it (temporarily) - if it does, then it's the same problem as the other issue, just with a little extra spice.

**Comment by flamber** [comment]
@VictorGeaGarcia Did an upgrade and restart fix the problem (perhaps only temporarily)?

**Comment by VictorGeaGarcia** [comment]
@flamber sorry for the late reply..... No the restart didn't help. I'll try an upgrade later this week or next week and I'll come back with the output

**Comment by VictorGeaGarcia** [comment]
@flamber I upgraded an it didn't solve it, still the same. I'm starting to think it's something with the DB, we were coming from H2 and maybe it has something to do with the migration process... I'll check that
In the meantime, is there anyway you can think of that I can further troubleshoot this? thanks

**Comment by flamber** [comment]
@VictorGeaGarcia Please post "Diagnostic Info" from Admin > Troubleshooting.
I have no idea what's causing this. Have never seen somethings like this before. Perhaps it's an error during migration, perhaps it's GCP MySQL.

Perhaps @masterproper, who upvoted the issue, can provide additional information.

**Comment by VictorGeaGarcia** [comment]
@flamber ok I'll try to use a brand new db but with the environment all the same....with that we could narrow down if it is something with GCP Mysql.

Here it is the diagnostic info:
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.25-google-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-03",
      "tag": "v0.37.3",
      "branch": "release-x.37.x",
      "hash": "2f1e783"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by VictorGeaGarcia** [comment]
@flamber I found where is the issue and fixed it.
 At some point we ran some export/import statements with the DB. We also do so sometimes to keep consistency between our three environments. Looks like when running this export/import processes, columns with BLOB types get corrupted. In particular **JOB_DATA** column in **QRTZ_JOB_DETAILS** table and **JOB_DATA** column in **QRTZ_TRIGGERS** table.
In my case I fixed it by deleting all rows in table:   **QRTZ_JOB_DETAILS**, for which I needed to delete rows in  **QRTZ_TRIGGERS** and **QRTZ_CRON_TRIGGERS** as well. Afterwards I restarted Metabase, and the needed rows in those table got regenerated.

thanks for your help!

**Comment by Handapao-0** [comment]
Whether it is not checked when exporting blob data， ==> option : hex-blob

**Comment by RobbiNespu** [comment]
```
DELETE FROM metabase.qrtz_cron_triggers
DELETE FROM metabase.qrtz_triggers
DELETE FROM metabase.qrtz_job_details
```
Then restart the metabase

This solve same issue #13880 on my side

**Comment by dragonsahead** [comment]
For posterity, the steps to recreate the QRTZ crons:

1) go to <your_metabase_url>/admin/databases/<id> and replace ID for the ID's you see in all the jobs that are named "sync-and-analyze.trigger" on the app DB. Find which of those ID's is the "internal Metabase Database". This is for regenerating the table later

2) go to the database IDE you use and fire the following query (this is MySQL syntax, Postgres might have the same):
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE QRTZ_TRIGGERS;
TRUNCATE TABLE QRTZ_JOB_DETAILS;
TRUNCATE TABLE QRTZ_CRON_TRIGGERS;
TRUNCATE TABLE QRTZ_SIMPLE_TRIGGERS;

4) now reboot Metabase, wait till it restarts

5) now go to each of your databases and configure a sync schedule (settings->admin->database-> select the database-> click on advanced->choose when sync and scan happens-> configure the pattern you want)

6) you'll see that after the previous step, the tables QRTZ_CRON_TRIGGERS and QRTZ_TRIGGERS have a new row that says "metabase.task.sync-and-analyze.trigger.<id>" in the trigger name. Clone that row but in the <id> use the ID of the internal metabase application database that you got from step 1

7) reboot Metabase again, everything should be back to normal now
