### ISSUE TITLE
Unable to access admin/people in 0.37.2 - getting "user->personal-collection does not match schema" error

### ISSUE THREAD

**Issue by sbocinec** [metabase/metabase#13883]
**Describe the bug**
After successful migration to metabase `v0.37.2` i'm not able to access Admin -> People `admin/people` - it throws: 
`Output of user->personal-collection does not match schema: [0;33m (not (instance? metabase.models.collection.CollectionInstance nil)) [0m ` error on the output and does not list users.
Accessing `admin/people/groups` and all other Admin routes works OK.

**Logs**
```
2020-11-24 22:19:40,647 ERROR middleware.log :: GET /api/user 500 18.9 ms (6 DB calls) 
{:value nil,
 :error (not (instance? metabase.models.collection.CollectionInstance nil)),
 :via
 [{:type clojure.lang.ExceptionInfo,
   :message "Output of user->personal-collection does not match schema: \n\n\t   (not (instance? metabase.models.collection.CollectionInstance nil))  \n\n",
   :data {:type :schema.core/error, :schema metabase.models.collection.CollectionInstance, :value nil, :error (not (instance? metabase.models.collection.CollectionInstance nil))},
   :at [metabase.models.collection$fn__33483$user__GT_personal_collection__33488 invoke "collection.clj" 903]}],
```

Full log output: [metabase.log](https://github.com/metabase/metabase/files/5590577/metabase.log)

**To Reproduce**
1. Go to `Settings -> Admin`
2. Click on `People` in the top navigation pane
3. See error

**Expected behavior**
List of users should be displayed

**Screenshots**
Please see the attached log

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.4.0-1021-gcp",
    "user.language": "en",
    "user.timezone": "Asia/Kuala_Lumpur"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-11-16",
      "tag": "v0.37.2",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": "Asia/Kuala_Lumpur"
    }
  }
}
```
- Metabase hosting environment: Running on Docker CE `19.03.12`
- Metabase internal database: H2 1.4.197

**Severity**
High - we can't absolutely manage users

**Additional context**
Can't provide full list of the `collection table, pasting at least `id` & `personal_owner_id` columns: 
```

ID | PERSONAL_OWNER_ID
-- | --
1 | 1
2 | 2
3 | 3
4 | 4
5 | 5
35 | 35
36 | 36
67 | 67
99 | null
100 | null
131 | null
195 | 99
196 | null
227 | null
259 | 131
291 | 163
323 | 195
324 | 196
325 | 197
326 | 198
358 | 230
390 | 262
391 | 263
392 | 264
393 | 265
394 | 266
395 | null
396 | 267
397 | 268
398 | 269
399 | null
400 | 270
401 | 271
163 | null
```

One interesting fact - all the collection table names are similar, though the last entry contains `/` char: `ABCD / EFGH` - can this cause the issue, similar to diacritics issue https://github.com/metabase/metabase/issues/10738 ?

**Comment by flamber** [comment]
Hi @sbocinec 
Not entirely sure if #10738 is in play, but then the problem would have something to do with the information in `core_user`.
You should never use H2 in production. I would highly recommend that you migrate away from H2:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Comment by sbocinec** [comment]
Okay, so I found removing/updating the collection entry name containing the `/` character fixes the issue!

So it appears to be a similar issue to the diacritics one - using the `/` character.

@flamber upgraded from `0.37.1` to `0.37.2`. But the collection has been added after the upgrade, so I suppose what I describe above caused the issue, not the upgraded version.

**Comment by flamber** [comment]
@sbocinec I cannot reproduce that. I have slashes in some collection names.

**Comment by sbocinec** [comment]
@flamber  sorry I was too fast to confirm the hypothesis. What I really did to fix the issue, was to recover from the nighly backup, that was done with the `0.37.2` version. 
Reg. the `/` character - I was mistaken by sorting order of the sql query output - the collection containing this `/` character was created far far ago, so it's not one causing the issue. Sorry for misleading info.

**Comment by flamber** [comment]
@sbocinec Okay, it sounds like you have ended up with a corruption rather than anything to do with the upgrade to 0.37.2.
Please migrate away from H2.

**Comment by sbocinec** [comment]
@flamber everything else except the `admin/people` was working properly. The metabase container nor host VM were restarted and the DB backup was done from the exact same running container. I expect, some UI operation caused the issue. 

I'm requesting info from the colleague who was trying to add a new user, what exactly has happened, but it's apparent, it got not corrupted by itself, but by some manual UI operation. Trying to find the culprit might also help others..

**Comment by flamber** [comment]
@sbocinec Without steps to reproduce, or your data, then it's very difficult to fix, since developers would only have an error message to go by. You can try to compare your H2 data to see the difference between your backup and the non-working.

**Comment by sbocinec** [comment]
@flamber I understand. I have found a way how to replicate the issue on our instance - simply trying to add a user makes `admin/people` starts throwing this error.

Here are the steps to reproduce on our instance:
1. Start `metabase/metabase:0.37.2` container using existing, internal H2 database
2. Go to metabase URL, login succesfully
3. Go to `Settings -> Admin`
4. Click on `People` in the top navigation pane. List of users is properly displayed
5. Click `Add someone` button - enter first/last name, email, Groups (Default).
6. Confirmation window appear for a milisecond informing that `name surname has been added. We've sent an invite to ....`
7. Without any interaction the screen is immediately replaced by the `Output of user->personal-collection does not match schema: [0;33m (not (instance? metabase.models.collection.CollectionInstance nil)) [0m ` message:
![Screenshot from 2020-11-25 12-39-42](https://user-images.githubusercontent.com/4834459/100223160-692b4d00-2f1b-11eb-8c36-76990a2f42aa.png)

Also adding a full log from the app initialization to the failure: 
[metabase.log](https://github.com/metabase/metabase/files/5596421/metabase.log) (note this was only a replica instance started using the same database as production, only with `-Xmx1g`).

Is there anything else I can provide to help to find the culprit? Any H2 DB select prior to the user creation that can tell us the DB is ok? Also as you can see in the log, app starts properly with the DB, so I suspect there is some invisible whitespace/unicode character issue similar to the previously mentioned diacritics issue...

**Comment by flamber** [comment]
@sbocinec Either there's a corruption in the H2 you are using, or some data already in that H2 is causing this problem.
I cannot reproduce on a new or existing H2 instances I have.
But that doesn't change that we do not recommend using H2 in production and you should migrate away.

**Comment by sbocinec** [comment]
@flamber I've just tried to restore previous version of instances with matching backup of the database:
* `0.37.2` - failure to add user
* `0.37.1` - failure to add user
* `0.36.8.2` - everything works properly

Though I understand H2 is discouraged from use, I stil think it would be interesting to try the following scenario to replicate the issue:
1. spawn a fresh metabase `0.36.8.2` instance
2. create a collection, create a user
3. upgrade to metabase `0.37.2`
4. try to create user to see if it breaks

If I will find time, I will try this with both H2 & mysql/pg to see if I can replicate. I suspect `0.37` introduces a bug or some incomplete DB migrations break this. Or yeah, H2... :grimacing:

**Comment by sbocinec** [comment]
Anyway, thanks for spending time on this issue! 

We are staying on `0.36.8.2` fow a while and we will do some other tests prior deciding how to move forward.

**Comment by flamber** [comment]
@sbocinec I have found the problem. You have some users in your existing H2, which uses the same email as someone else, but with different casing (lowercase/uppercase).
The fix is to not have identical (with different casing) emails for multiple users. I will create a new issue for this, when I'm done investigating.

**Comment by flamber** [comment]
@sbocinec That took me down a rabbit hole - #13890

**Comment by sbocinec** [comment]
@flamber thank you very much!!!! Oohhh, I saw this deactived duplicated user, but didn't put my attention to it, as it was working. Also there is no way how to remove users using the web UI. Users can be only deactivated, but not completely removed in case of mistake or whatever. I think, it would be beneficial if we have the option to also remove a user. 

Anyway, thanks for finding the real culprit and I'm going to try to remove the duplicated issue manually by directly connecting to the DB :crossed_fingers:

**Comment by sbocinec** [comment]
Oh, i see in #4936 that it's intentional not to remove users. As I was scared to remove the user manually from the DB, i just reactivated one of the duplicate users, changed email, and deactivated. 

After doing this, and upgrading to `0.37.2`, issue is now resolved and metabase is working like a charm :smile: 

Thanks again for the assistance!

**Comment by flamber** [comment]
@sbocinec There are several reasons why users cannot be completely deleted - audit history among other.
