### ISSUE TITLE
Chained joins changing "Previous results" to the table name

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#13894]
**Describe the bug**
During multiple, chained joins "Previous results" change to the table name after a field is chosen. This brings confusion. Brought it up with @mazameli and he confirmed that this is definitely not a desired UI behavior.

**EDIT:**
When I looked at the source code, I realized that "Previous results" is hard coded when it should be template string included in translations. That also needs to be fixed.

**Logs**
N/A

**To Reproduce**
1. Go to New question > Custom question > Sample dataset > `Orders`
2. Join by `People` (`User ID` = `ID`)
3. Start another join (observe UI says "Previous results" at this point)
4. Join by `Products` (`Product ID` = `ID`)
5. Observe that "Previous results" changed to `Orders` (which isn't technically correct)

- Since there is no way currently to display "Joined Orders" or anything similar, we are using "Previous results".
- One "danger" in this behavior is that it leads user to think that `Orders` can be clicked and changed.

**Expected behavior**
"Previous results" string shouldn't change.

**Screenshots**
_Note: I am using `People` in this screenshot, but it illustrates this bug just the same._
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/QwubWpDD/Screen%20Recording%202020-11-20%20at%2009.10.28%20PM.gif?source=viewer&v=e621d0d5e96caab13c8a18c04fab6b7f)

**Information about your Metabase Installation:**
- local dev, latest master/release branch `x.37.x`

**Severity**
Probably P3 at best. It's just UI weirdness.

**Additional context**
I will try to prepare a fix for this. It seems fairly simple.

**Comment by flamber** [comment]
I don't think I understand. It should change depending on which field is selected. Look at the query that is generated.

**Comment by nemanjaglumac** [comment]
@mazameli seems to think it should ALWAYS say "Previous results". It's purely from the UI perspective. Query will not change by this.

**Comment by mazameli** [comment]
To be very explicit, in the UI, the left-most data token in a join step should read "Previous results" unless the join step comes immediately after the initial "Data" step.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/2223916/100289457-cb8d4900-2f2d-11eb-9123-a5d8d247c311.png">

**Comment by nemanjaglumac** [comment]
I think I understand what @flamber is trying to say. I was poking around the UI and recorded this:

_See how left-most token changes (from `Orders` to `Products`) depending on the field you chose_
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/7KubdErk/Screen%20Recording%202020-11-25%20at%2011.55.57%20PM.gif?source=viewer&v=54b8e7a5cf22ffce315da97e42a735ce)

**Comment by robdaemon** [comment]
So a database join is *always* on previous results, so showing "previous results" makes sense - however, for the column names, it might make sense to show `table.column`

Like, "Previous Results <join type> <Right hand table name> ON <Left hand table name>.<Column> = <Right hand table name>.<Column>`

at least that would match SQL

**Comment by nemanjaglumac** [comment]
Fixed in #13895

**Comment by paulrosenzweig** [comment]
Here's another option for the behavior we could have here.

### Old behavior:

`Previous Results () Pick a table where Pick a column = Pick a column`
becomes
`Orders () Pick a table where ID = Pick a column`

- Confusing to see "Previous Results" change suddenly
- Doesn't accurately reflect that you're always joining to the amalgam of previously joined rows

### Behavior in #13895:

`Previous Results () Pick a table where Pick a column = Pick a column`
becomes
`Previous Results () Pick a table where ID = Pick a column`

- Hides the source of the "ID" column once you've closed the popover

### Another option:

`Previous Results () Pick a table where Pick a column = Pick a column`
becomes
`Previous Results () Pick a table where Orders.ID = Pick a column`

- Maybe this avoids hiding where ID came from while also showing that you're joining to all previous results.

**Comment by nemanjaglumac** [comment]
Reopenning since the "fix" was reverted on a `release` branch (https://github.com/metabase/metabase/pull/13964) and it will be reopened against the `master` for further discussion, before we decide should we implement this (and how).

**Comment by kulyk** [comment]
Closing it as "Won't fix", see the discussion at #17984 for details
