### ISSUE TITLE
Pulses with Conditional Formatting is displayed with black background, when value is above 999

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13892]
**Describe the bug**
When using Conditional Formatting on a table, then column values above 999 (with thousand separator) will show a black background in Pulse.

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Summarize Count by People.Source and Product.Category
3. Change visualization to Table and un-pivot in Settings and set Conditional Formatting on Count with style "Color range"
![image](https://user-images.githubusercontent.com/1447303/100255871-5b3df200-2f44-11eb-8f9d-584a7886fd92.png)
4. Save question and try creating a Pulse, which then shows all values above 999 with black background
![image](https://user-images.githubusercontent.com/1447303/100256026-87597300-2f44-11eb-9c37-bb7dfdbf7d24.png)

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.37.2

**Additional context**
Related to #3735

The backend invokes JS to get a cell color, however, it passes not javascript numbers but objects `toString` of which returns formatted numbers with the following keys:
```
num_str,__meta,__extmap,hasheq,withMeta,meta,assoc,valAt,entryAt,without,getLookupThunk,equiv,remove,get,put,equals,toString,values,hashCode,clear,isEmpty,size,iterator,count,entrySet,putAll,empty,cons,containsKey,keySet,containsValue,seq,to_str,assocEx,spliterator,forEach,replace,replaceAll,merge,putIfAbsent,compute,computeIfAbsent,getOrDefault,computeIfPresent
```
Then d3.scale code checks if the provided value is a number. In case with `999` string gets converted to a number and the check passes but `1,000` string is `NaN`. To fix that, BE should provide numbers instead of objects.  

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by TraviJohnny** [comment]
Hey Everyone using version v0.45.1, when is  a fix for this planned to be available? Is there a known workaround except disabeling conditional formatting?
