### ISSUE TITLE
Data Model column type being overwritten during upgrade from v0.36.2 to v0.37.2

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#13904]
**Describe the bug**
Upgraded from v0.36.2 to v0.37.2. We have a lot of code lookup tables, basically `{id, code, description}` tables (often we prefix them to "ItemTypeDescription" etc.) . I generally set both the code and description to "Category" types in the Data Model so we can do group bys on either depending on the audience. Works great.

In every case I've looked at since the upgrade all the columns that contain the word "description" have had the Data Model type set to "Description" which in turn means that we can't group by those fields and existing charts using those fields no longer work.

**Logs**

**To Reproduce**
1. v0.36.2, setup a table with a column name "ItemDescription", set it to "Category" type
2. Upgrade to v0.37.2
3. "ItemDescription" field now has a type of "Description" and can't be used in groupings etc.

**Expected behavior**
If I manually set a type in Data Model I'd expect this to be retained during upgrades.

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.2",
      "date": "2020-11-16",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Severity**
I'm now having to manually reset all the "description" fields to "Category" type in order for the existing stuff to keep working and to be able to create new charts using these fields as dimensions. And I'm not confident at this point if this will all be reset by the next upgrade. Time consuming and frustrating. No real work arounds but I don't want to roll back versions given the good stuff you've added in v0.37.

**Comment by flamber** [comment]
Closing in favor of #12574. Until we have a way to distinguish between user defined and sync guesstimate, then this can happen.
