### ISSUE TITLE
A lots of Javascript violations on Console

### ISSUE THREAD

**Issue by jonorozcoc** [metabase/metabase#13917]
**Is your feature request related to a problem? Please describe.**
I'm trying to make a simple question. When I open the table settings the app becomes slow and laggy

**Describe the solution you'd like**
One simple solution could be only show root keys as columns and async load "more columns" section by user action

**Describe alternatives you've considered**
Async loading all information. But this doesn't solve the issue with a lot of columns

**How important is this feature to you?**
In order to not affect the UX the table settings has to load straightforward

**Additional context**
Version: v0.37.2
Type: JAR Server
OS: Windows 10
Browser: Chrome 86.0.4240.198

I'm using MongoDB Connector, my database has around 6k entries, the document schema has a lot of keys, about 100 - 200 columns are generated on table settings
![image](https://user-images.githubusercontent.com/8442497/100659912-4cc65080-331f-11eb-8f11-877aa158eaf1.png)
![image](https://user-images.githubusercontent.com/8442497/100659998-6d8ea600-331f-11eb-853c-b93b4627075f.png)

**Comment by flamber** [comment]
Closing in favor of #11806, since it's not a feature request, but a performance bug.
