### ISSUE TITLE
User with VIEW ONLY Permissions can EDIT and DELETE Dashboards 

### ISSUE THREAD

**Issue by culturedev** [metabase/metabase#13912]
**Describe the bug**
Even though a user only has VIEW permissions for a collection, Dashboards in this collection can be **modified, deleted and restored** to a previous version. 

Even though the user only has VIEW permissions for a collection, which **should not allow any changes to any items in a collection**, the following is possible:

1. User can change title and description of a dashboard
2. User can revert to a previous version of dashboard through revision history
3. User can duplicate dashboard
4. User can archive dashboard
5. User can **edit dashboard** by clicking on pencil icon next to title of a question in the collection and selecting "Add to dashboard". After doing this, the user is in **full edit mode** for the selected dashboard and can modify the dashboard in any way he likes, including making changes to the visualisation of individual questions, removing them or adding new ones.

**Logs**
n/a

**To Reproduce**
1. Go to '...' at top right of dashboard and select any of the options to change title, restore a revision, duplicate or archive dashboard
2. Go to any question in the collection, click on the pencil next to title, and select "Add to dashboard". From that point on the user is in full edit mode of the selected dashboard

**Expected behavior**
Users with VIEW permissions should not be able to modify any aspects of existing items in Collection in any way. Only users with "Curate" or "Admin" permissions should be able to modify or archive items in the collection.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.0-11-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.8-MariaDB-1:10.5.8+maria~focal"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-11-16",
      "tag": "v0.37.2",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
I believe that this is an extremely serious bug in the security design. The whole purpose of Metabase is to share data and analytics with decision makers in the company in order to ensure and improve business performance. Dashboards fulfill a key function in this purpose. If the administrators can never be sure what users are looking at, because the integrity of a dashboard can easily be compromised through inadvertent or willful modification/deletion by unauthorized users, this largely defeats the purpose of an otherwise excellent tool. I would hope that these loopholes are closed with the highest priority.

**Additional context**

**Comment by flamber** [comment]
Hi @culturedev 
I cannot reproduce on 0.37.2. And since you think this is a security issue, then I don't understand why you didn't report it as a security issue.
Could it be that you haven't revoked the permissions on "All users" group?
For reference: https://www.metabase.com/blog/collection-permissions/index.html

**Comment by culturedev** [comment]
Hi @flamber 
Sorry for reporting in wrong category. Shall I reopen it under security, or why did you close this issue? I have tried to demonstrate the case with the following screenshots. As you can see, the "All Users" group has no permissions whatsoever. Are my screenshots clear enough, would you like a video, or what additional information can I provide?

### Permissions:
**All Users have NO permssions, the "Management Reporting" Group only has VIEW permissions**
![collections_perm](https://user-images.githubusercontent.com/5941039/100554775-4e4c3600-3297-11eb-9f29-9835ae36b39f.png)
![our_analytics_perm](https://user-images.githubusercontent.com/5941039/100554781-4f7d6300-3297-11eb-95c3-e3fce5fc4a28.png)
![data_perms](https://user-images.githubusercontent.com/5941039/100554780-4ee4cc80-3297-11eb-9d4f-cd364600305c.png)
**Note: The user belongs to the "Management Reporting" group:**
![user_groups](https://user-images.githubusercontent.com/5941039/100554782-4f7d6300-3297-11eb-84bc-c00b432870cf.png)

**This shows that the user has no rights to edit the dashboard initially:**
![dashboard_not_editable_correct](https://user-images.githubusercontent.com/5941039/100554779-4ee4cc80-3297-11eb-9e94-8658ffc1e502.png)

**The user can change title, desc, restore from revision, duplicate and archive the dashboard - this should not be**
![dashboard_changes_possible](https://user-images.githubusercontent.com/5941039/100554777-4e4c3600-3297-11eb-8171-c28799bc950e.png)


**If user now adds a question to dashboard, he can edit it**
![add_to_dashboard_possible](https://user-images.githubusercontent.com/5941039/100554774-4db39f80-3297-11eb-8d85-703a0aa5094a.png)

**now the dashboard can be fully edited, saving is enabled**
![dashboard_in_edit_mode](https://user-images.githubusercontent.com/5941039/100554778-4ee4cc80-3297-11eb-824a-220e98717003.png)

**Comment by flamber** [comment]
@culturedev You are showing some available menu options, but that doesn't mean that the user can use any of them. If you try to do any of the activities, then you will get errors and the log will say `You don't have permissions to do that.`.
There are several issues open that is dealing with the inconsistency of the options available, since they should be hidden, but that's not a security problem, since the user is never getting access to something that they are not allowed to see.
You can duplicate a view-only dashboard, but that's expected - you cannot save that duplicate to a view-only collection.
I cannot reproduce editing or deleting (archiving) any view-only questions/dashboards - that's why I closed the issue.

**Comment by culturedev** [comment]
Hi @flamber , sorry for that, I did not go that far, as I did not want to modify production setup. My bad. Many thanks to you for your great work.
