### ISSUE TITLE
Remove joda time in favor of java time

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#13922]
We use bring in joda time from our cron-parser library

```
 [net.redhogs.cronparser/cron-parser-core "3.4" :exclusions [[org.slf4j/slf4j-api]]]
   [joda-time "2.3"]
```

This has been updated in https://github.com/metabase/metabase/pull/13921 but this outdated version caused some issues (https://github.com/metabase/metabase/issues/13867). The fact is that having two date libraries in use can always cause issues like that linked. Quite easily from differing timezone databases but probably other subtle issues as well.

I think we should get rid of joda.time to the furthest extent possible so that there is only a single date time pathway in our code. Its possible that we won't be able to remove it totally without finding a different cron parsing library, but we can hopefully minimize issues.

**Comment by bshepherdson** [comment]
We've got the separate [second-date](https://github.com/metabase/second-date) library now for some complex cases. For simple cases java-time is sufficient.

There are only a few references to Joda time left in the codebase.
