### ISSUE TITLE
Field not available to select for query group by when editing existing question

### ISSUE THREAD

**Issue by kbwhizz** [metabase/metabase#13926]
I have joined two tables and have a working question. I want to edit the group by to a different field in the second table. All fields except the one I want are listed for selection. The field is called description and is of type longtext in source mysql database.

1. Create a custom question based on 1 table which has a foreign key to a second table
2. Click Summarize and choose (for example) count
3. Click plus sign under "group by"
4. Note field description is not present to select in dropdown

Metabase v 0.37.0.2
Chrome  86.0.4240.198
Windows 10
Source database mysql: 10.1.47-MariaDB-0+deb9u1 Debian 9.13
[Source table from database.pdf](https://github.com/metabase/metabase/files/5621909/Source.table.from.database.pdf)

**Comment by flamber** [comment]
Hi @kbwhizz
Change the Field Type in Admin > Data Model > (database) > (table) > (column), so it's not using "Description", example "Category".
Related to #11721.

**Comment by kbwhizz** [comment]
Hi @flamber 
I tried Comment, Category and No special type but none of these helped. I made sure I clicked rescan field and discard cached field values too before re-testing.

**Comment by kbwhizz** [comment]
Now working. "No special type". Not sure why the pause but thanks anyway.

**Comment by ranquild** [comment]
Can reproduce in `v 0.37.0.2` but not in `0.45` or `master`. It was fixed long time ago.
