### ISSUE TITLE
Cache FE deps separately on CI

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#13937]
@ariya pointed out that installing our frontend dependencies can time out on CircleCI and that the cache is busted when our own code is updated. We should split the cache to cache deps separately since our deps aren't updated frequently.

**Comment by ariya** [comment]
Turn out we already have a dedicated cache for the deps (`fe-deps-v4-{{ checksum "yarn.lock" }}`). I think the cache gets emptied because of some other reason.

In all cases, we still shall make the frontend fetching longer, in case the cache isn't populated.
