### ISSUE TITLE
hide was still area height

### ISSUE THREAD

**Issue by tang-alex** [metabase/metabase#13933]
I’ve hidden the parameters and the title. Take over from outside. But there is still a blank area with height. Who knows how to hide it?
I can’t set the parameter to lock for 2 reasons
First. Customers can click query directly without entering parameters, and all the data will be seen.
Second. The dashboard contains two sub questions, in which the two questions also have a hierarchical relationship, which can be used to drill through queries. If I set the internal parameter to lock as well, clicking on the drillthrough column on the external page has no effect.

https://discourse.metabase.com/uploads/default/original/2X/9/980ed8d896b2e0d1e1e1d5ea9088ec43fe6a852d.png
https://discourse.metabase.com/uploads/default/original/2X/7/769549d7f901998b3de00ee225f84c5077a4a9e9.png

**Comment by flamber** [comment]
I'm going to close this
