### ISSUE TITLE
Embedding with `#titled=false` shows whitespace, when filters are hidden with `hide_parameters=...`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13934]
**Describe the bug**
When embedding/sharing with filters, and defining the title to be hidden, then it still shows a whitespace, when all filters are hidden with `hide_parameters`.

**To Reproduce**
1. Create dashboard and add a filter (eg Category), save dashboard, and enable embedding.
2. Now change border, title and parameter to hidden - the [EmbedFrame-header](https://github.com/metabase/metabase/blob/b16e923eca41ca7d75894779ca5849c9ff73e4c2/frontend/src/metabase/public/components/EmbedFrame.jsx#L90-L112) is still showing about 60px tall whitespace.
`/embed/dashboard/<token>#bordered=false&titled=false&hide_parameters=category`
![image](https://user-images.githubusercontent.com/1447303/100867893-22999d80-349b-11eb-9750-dab0a9d86aeb.png)

**Expected behavior**
Hide the `EmbedFrame-header`, when title is hidden and there are none visible filters.

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.37.2

**Additional context**
Related to #7778

**Comment by tang-alex** [comment]
i can't open you image ,but i sure , we are same. 
hope next version can be fix.
thanks.
