### ISSUE TITLE
Native questions with filters with default values cannot be cleared

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13961]
**Describe the bug**
When viewing a SQL question with a filter with Default Value, then it's not possible to clear the value of the filter.

**To Reproduce**
1. Native question > Sample Dataset - set `category` variable to Field Filter of Category with a default value of "Doohickey", and `prodid` variable to Number filter - save question.
```
SELECT *
FROM PRODUCTS
WHERE 1=1
AND {{category}}
[[AND ID={{prodid}}]]
```
![image](https://user-images.githubusercontent.com/1447303/101178864-c923a100-3649-11eb-8812-1d80c5ebf1f9.png)
2. Refresh page, which now gets the default value added to the URL parameter
![image](https://user-images.githubusercontent.com/1447303/101179010-f8d2a900-3649-11eb-83c8-9f58b79dbd3f.png)
3. Clear Category filter, and input `1` into ID filter, where the expected result would be a single row, but it returns "No results", since it's applying the default value of Category filter anyway.
![image](https://user-images.githubusercontent.com/1447303/101179216-3e8f7180-364a-11eb-8578-0a09e3165e1c.png)
4. The only workaround is to apply all options of Category filter (which might not be possible, or unknown)
![image](https://user-images.githubusercontent.com/1447303/101179483-8f06cf00-364a-11eb-83dd-a603c88291f3.png)

**Expected behavior**
This might be difficult to make backward compatible, and would probably require a bigger change to how the URL parameters are handled, but the expected behavior is that the filters I define also defines the results.

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.37.3 - has probably been the behavior for several years

**Severity**
Only giving P3, but adding Correctness, since this feels wrong and can easy lead to different results than expected. Almost P2.

**Additional context**
Very similar to #13960

**Comment by nemanjaglumac** [comment]
Just to add: Like #13960, this issue also resets the URL on page refresh to `question/4?category=Doohickey&prodid=1`

**Comment by daltojohnso** [comment]
when you remove the Category field filter parameter and run the query, the app sends a request to the `/api/card/:cardId/query` endpoint with a body of...

```
{"ignore_cache":true,"parameters":[{"type":"category","value":"1","target":["variable",["template-tag","prodid"]]}]}
```

So I think the BE must have some logic that causes a parameter with a default value to be applied automatically.

**Comment by smtk1122** [comment]
I'm experiencing the same problem.

**Comment by qnkhuat** [comment]
@daltojohnso you're right, this is currently the intended behavior if we have a default value [ref](https://github.com/metabase/metabase/blob/b519dd8ab45be8cede4d265312d2607604b07a6d/src/metabase/driver/common/parameters/values.clj#L95).

But as of current master(50ab6e5d330e88038400e3b1e5ed9afbca43396c), when I remove the Category field filter 
param, FE send a request to `/api/card/:cardId/query` with this body 

```{"ignore_cache":true,"collection_preview":false,"parameters":[]}```

In order for BE to distinguish 2 use cases:
1. fall back to the default value
2. temporarily remove this filter

WDYT if FE will send parameters with `value=null` when we want to do 2nd case?
sth like this
```json
{
    "ignore_cache": true,
    "collection_preview": false,
    "parameters": [
        {
            "type": "string/=",
            "value": null,
            "target": ["dimension", ["template-tag", "category"]],
            "id": "a90ee17f-2cf3-aa09-438c-93dffe77690b"
        }
    ]
}
```

**Comment by calherries** [comment]
It looks like Dalton fixed this previously with https://github.com/metabase/metabase/pull/17522, but then reversed it with https://github.com/metabase/metabase/pull/17912.

Either way I think this is a combined FE/BE issue.
