### ISSUE TITLE
mysql数据字段 status值无法正常显示

### ISSUE THREAD

**Issue by weifengtang** [metabase/metabase#13977]
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_222-ea-b03",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_222-ea",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.222-b03",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v1.37.0.2",
      "date": "2020-10-26",
      "branch": "release-x.37.x",
      "hash": "7996551"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}
metabase高级查询中



期望：
![企业微信截图_16073434866001](https://user-images.githubusercontent.com/45869985/101350070-54f73080-38c9-11eb-8966-7648dea2488c.png)

```

**Comment by weifengtang** [comment]
metabase高级查询中


![企业微信截图_16073433989064](https://user-images.githubusercontent.com/45869985/101350294-b3241380-38c9-11eb-88bd-00397ad8ff70.png)

**Comment by weifengtang** [comment]
数据库一个表中有一个tinyint类型的字段，值为0或者1，如果取出来的话，0会变成false，1会变成true。

MySQL保存boolean值时用1代表TRUE，0代表FALSE。boolean在MySQL里的类型为tinyint(1)。MySQL里有四个常量：true,false,TRUE,FALSE分别代表1,0,1,0。

场景:

　　字段：status (值为1,2,3)

　　类型：tinyint  长度：1(有符号的)

　　结果：查询出来的数据列表，状态值不管是1还是2还是3，都是"boolean true"

分析并解决：

　　分析：由于MySql中没有boolean类型，所以会用到tinyint[1]类型来表示,在mysql中boolean=tinyint[1]

　　解决：tinyint类型长度的问题，当我把长度改成4时，查询结果就正常了

猜想并使用新的方法解决：

　　如果不改变类型的长度，怎么让查询的结果正确呢？需要在查询语句上面做修改了

　　在你需要执行的sql语句中，把这个状态字段*1，结果就会得到数据库存的值了(注意：记得加别名，不然查询出来的就是status*1 => '1')

复制代码
SELECT
    id,
    name,
    status*1 AS status,
    add_time
FROM
    tableName
WHERE
    play_type = 0
复制代码
总结一下以上的两种解决方法：

　　1.修改tinyint类型的长度

　　2.在查询的sql语句上面做修改 

所以由这里可以看出，当你使用tinyint[1]来存储超过0,1两个值以外的值，比如存储2，那这个2就是脏数据就用tinyint[4]，tinyint[1]只适用于存储0和1两个值，也即真和假，true和false

　　一般的，咱们如果存的是纯数字的话，建议用tinyint，如果是字符串，且是固定长度的，建议用char,而enum的枚举字段，使用的使用需要慎重考虑，避免带来不必要的麻烦

还有一种方式是在连接url上添加 tinyInt1isBit=false ：

url: jdbc:mysql://192.168.17.107:3306/oip_back?useUnicode=true&characterEncoding=utf-8&useSSL=false&tinyInt1isBit=false

**Comment by weifengtang** [comment]
这样解决

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And you are likely going to get more answers if you write in English.
