### ISSUE TITLE
Improvement: Specify column order

### ISSUE THREAD

**Issue by AlgyTaylor** [metabase/metabase#1397]
Would it be possible to allow the a user to specify column order?  I've found sometimes Metabase (which, by the way, is a whole bag full of pure awesome) gets it wrong when you do something like: 

- Table A has foreign key in Table B
- Table A has foreign key in Table C

"fetch all records from table A, grouped by value X in Table B, when the record in Table C contains value Y"

If it'd be possible to say what order those columns are in - or which column represents the X (and potentially Y) axis of a graph - it would make it super-amazing.

**Comment by tlrobinson** [comment]
Related to #612 #1364

**Comment by agilliland** [comment]
I believe this is really the same issue as #1364 which has been fixed.  I added a vote to #612 on your behalf as well.
