### ISSUE TITLE
Can I define certain map colors for certain percentages?

### ISSUE THREAD

**Issue by Mikkopoika** [metabase/metabase#13974]
I'm trying to create a timeline of changes of certain percentages over different regions in Finland. I've got the map working alright, but I'm having trouble with the automatic scaling of colors. For example: 2012 the percentages where 1-20 over different regions and I got Metabase to color them accordingly. However, in 2016 the percentages vary between 1-40. In the first case, the darkest color is allocated to the darkest blue, but in the second case it's the middle blue. This is because Metabase scales the results equally to each color. 

Is there a way to force certain colors for certain percentiles, so I could build a timeline from the maps, where a certain color means a certain thing every time?

For example
![Näyttökuva 2020-12-6 kello 23 23 36](https://user-images.githubusercontent.com/11136336/101292827-86fd8980-381a-11eb-982e-39ecd93c4a33.png)
![Näyttökuva 2020-12-6 kello 23 23 49](https://user-images.githubusercontent.com/11136336/101292829-88c74d00-381a-11eb-9c26-3d24c728292e.png)

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
