### ISSUE TITLE
Snowflake not returning the correct amount of rows

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13995]
I'm just creating this, since we have now multiple reports on different versions of Metabase that Snowflake results are incorrect.
All reports are from today. Everything from 1.36.3 to 0.37.3

Example: Let's say `table` has 18446 rows
`SELECT * FROM table` returns 300 rows.
`SELECT column1 FROM table` returns 394 rows.
`SELECT column2 FROM table` returns 590 rows.
`SELECT * FROM table LIMIT 20000` returns 400 rows.
`SELECT COUNT(*) FROM table` returns 1 row with result 18446.

https://discourse.metabase.com/t/weird-unexplainable-error-when-querying-table-on-metabase/12604
https://discourse.metabase.com/t/limit-of-rows/12606
And tickets.

:arrow_down: Please click the :+1: reaction if you are also seeing this problem

**Comment by AcidFlow** [comment]
We are experiencing the same issue.

As far as I can tell it seems to happen on clients using a JDBC connection. Strangely enough, for us adding a `LIMIT` some of our queries resulted in more data to be fetched.
Running our queries through Snowflake's UI, Snowsight or Snowsql did not have the same issue.

Metabase version: 0.37.2
JDBC driver version: 3.12.13 (from metabase)

Running through DBeaver with JDBC driver 3.12.16 results in the same issue than in Metabase.

Snowflake version: 4.41.0
Snowflake cloud / region: AWS Frankfurt

I also noticed that in Snowflake's query history, Snowflake struggles to access the results of these "truncated" queries, and the export functionality also returns the truncated dataset.

**Comment by flamber** [comment]
Seems like it was a problem in Snowflake, which they have now reverted. The problem should be solved for everyone, but please allow a bit of time to propagate to all regions. If you are still having problems, then please contact Snowflake support, since the problem is on their platform (specifically with their JDBC interface).

**Comment by rgabo** [comment]
Snowflake Support:

> This is the parameter regression that was rolled out. We have rollback the change, can you please verify and let us know if the issue is resolved?

As @flamber just mentioned, the change is now rolled back. Phew!
