### ISSUE TITLE
Enhancement: Organizations

### ISSUE THREAD

**Issue by tomkanjam** [metabase/metabase#1399]
I would like to create organizations, to which users can be added, in order to manage access to databases, queries, dashboards and so on.

**Comment by mazameli** [comment]
This seems like a completely reasonable request, though not an insignificant amount of effort. I think we'll want to revisit this later this year. Any thoughts, @salsakran?

**Comment by salsakran** [comment]
this is being done in #3087

**Comment by camsaul** [comment]
I'm going to go ahead and close this as a duplicate of #3362. @tomkanjam we're working on shipping a permissions framework with groups/roles for our upcoming release.
