### ISSUE TITLE
Password reset email does not show link in some clients

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13998]
**Describe the bug**
Password reset email does not show link in some clients. Example from Outlook Web:
![image](https://user-images.githubusercontent.com/1447303/101521087-9f3de780-3985-11eb-9ff8-b43d46f205b2.png)

This is most likely caused by CSS properties being overwritten:
https://github.com/metabase/metabase/blob/master/src/metabase/email/password_reset.mustache#L10

**Information about your Metabase Installation:**
Metabase 0.37.3 - probably been like this for several years, but perhaps Outlook Web has changed something on their end.

**Additional context**
Giving P2, since Outlook Web is a fairly huge email provider and makes password resets even more complicated.
https://discourse.metabase.com/t/password-reset-button-not-fullly-visable/12618

**Comment by noahmoss** [comment]
I can't repro on my personal Outlook account. The button appears to be normal:
<img width="508" alt="Screen Shot 2021-06-22 at 2 31 27 PM" src="https://user-images.githubusercontent.com/32746338/122980809-160d6180-d367-11eb-9665-80ab5df18368.png">

This is on outlook.live.com; not sure if there's a different Outlook web interface that would still have this issue (maybe for corporate accounts?)

**Comment by flamber** [comment]
@noahmoss It's the self-hosted Exchange, if I remember correctly, so yes, corporate.

But we are pushing multiple `color` and use `background` instead of `background-color`, which I guess is what is triggering it.

The only thing I've learned through the years is that email rendering engine are horrible - and definitely Outlook's more than others, which is use Word as rendering (this will start changing from now on, where they will start moving towards WebView2, which is using Edge-Chromium as render). The only way around it, is to write really simple HTML4-style code and trying to stay at or below CSS2.
