### ISSUE TITLE
Nav bar hover text is cramped

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#14012]
The hover text on the Browse and Ask Questions prompts are being cramped and seem to need some padding. See attached.

Metabase version v0.37.0.2
Built on 2020-11-09
Branch: master
Hash: 5658fc0

Running into this on Chrome 87.0.4280.88

<img width="154" alt="Screen Shot 2020-12-09 at 9 29 19 AM" src="https://user-images.githubusercontent.com/107439/101664785-19f81880-3a01-11eb-9526-67f1cfc6b681.png">

**Comment by mazameli** [comment]
Not seeing this on Chrome 87, or on Safari on our stats instance.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/2223916/101667042-b6231f00-3a03-11eb-9fc3-92016f6b1b20.png">
