### ISSUE TITLE
Reverse proxy reset email should use site URL in email body and not localhost

### ISSUE THREAD

**Issue by richxrich** [metabase/metabase#14028]
**Describe the bug**
Metabase installed behide a reverse proxy the reset password email says:

"Click the button below to reset the password for your Metabase account at **localhost**."

**To Reproduce**
1. Metabase behind a reverse proxy.
2. Click lost password.
3. Enter email address.
4. Wait for email.
5. Read email to see error.

**Expected behavior**
To use the site URL from the admin tool as the URL in the email.

**Screenshots**
![image](https://user-images.githubusercontent.com/140509/101709951-a3344b80-3ae4-11eb-90f4-f3ff5f4b5cc1.png)

**Information about your Metabase Installation:**

Metabase 0.37.2

**Severity**
UX issue but users are confused because they cannot see any familar names or URLs - possibibility for phishing email is a concern.

**Additional context**

**Comment by camsaul** [comment]
It looks like the forgot password endpoint is using the value of `server-name` from the Ring request map (whatever that happens to be). You're right... we should be using `site-url` instead. Trivial fix
