### ISSUE TITLE
Column heading action menu for SQL doesn't look good

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14027]
We overlooked this when restyling the drill/actions menu.

<img width="144" alt="image" src="https://user-images.githubusercontent.com/2223916/101706255-8f81da00-3a3d-11eb-82a7-ee46c9d9764b.png">

**Comment by mazameli** [comment]
Curious if you could give me a nudge in the right direction here, @paulrosenzweig — I think I'm kind of close.

What I'm trying to do is conditionally restyle this action to make it a `horizontal` one, similar to what you did for the `Sum` action in the previous PR. We want this action to be horizontal for SQL query headings, and as a proxy for that I'm checking to see if there is no Filter action group, since all other columns have that except for SQL query columns.

Here's the relevant code I'm trying in `ChartClickActions.jsx`. The second `if` is the new part I'm trying to add in the middle of your code:

```
const groupedClickActions = _.groupBy(clickActions, "section");
    if (groupedClickActions["sum"] && groupedClickActions["sum"].length === 1) {
      // if there's only one "sum" click action, merge it into "summarize" and change its button type and icon
      groupedClickActions["summarize"].push({
        ...groupedClickActions["sum"][0],
        buttonType: "horizontal",
        icon: "number",
      });
      delete groupedClickActions["sum"];
    }
    if (!groupedClickActions["filter"]) {
      // Only SQL column headings do not have filter actions, and we want to restyle the Formatting action for SQL columns
      groupedClickActions["formatting"].push({
        ...groupedClickActions["formatting"][0],
        buttonType: "horizontal",
        icon: "gear",
      });

      groupedClickActions["formatting"][0].pop();
    }
    const sections = _.chain(groupedClickActions)
      .pairs()
      .sortBy(([key]) => (SECTIONS[key] ? SECTIONS[key].index : 99))
      .value();
```

What I was trying to do was push a new action to that formatting group, then pop the previous one out of the array. I don't know if that's right, but my thought was that I didn't want to `delete` the whole formatting group the way we delete the unneeded `sum` group above.

When I try clicking on the column heading with this code, though, I'm getting `TypeError: undefined is not an object (evaluating 'groupedClickActions["formatting"].push')`

Thanks for any guidance you can offer! 🙏

**Comment by paulrosenzweig** [comment]
Does the formatting group always have one action in this situation? If so, you can overwrite that entry:
```js
if (!groupedClickActions["filter"]) {
  // Only SQL column headings do not have filter actions, and we want to restyle the Formatting action for SQL columns
  groupedClickActions["formatting"][0] = {
    ...groupedClickActions["formatting"][0],
    buttonType: "horizontal",
    icon: "gear",
  };
}
```
That will fail if there are no items in the formatting group, but we could add that condition to the `if`. If there might be multiple, we should map over each and update them.

**Comment by mazameli** [comment]
Yeah, there's only ever that one formatting action (until/unless we add another in the future).

Using your code, when I click on any column heading, GUI or SQL, I see these in the console, which I don't see when clicking headings on our stats instance, and the popover doesn't open:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Draggable component.`

`TypeError: undefined is not an object (evaluating 'groupedClickActions["formatting"][0]')`

I'll open a draft PR and take the conversation over there.

**Comment by paulrosenzweig** [comment]
The first error is unrelated. The second is because `groupedClickActions` doesn't have a `formatting` property. To guard against that, I'd update the `if` 

from this

```
if (!groupedClickActions["filter"]) {
```

to this

```
if (!groupedClickActions["filter"] && groupedClickActions["formatting"]) {
```
