### ISSUE TITLE
Localized deployment map tile error

### ISSUE THREAD

**Issue by ljm000** [metabase/metabase#14032]
**Describe the bug**
I have a server with localized deployment.
Unable to access the external network, so I deployed an internal network tile map service.
Use the local map tile service, the map tile is loaded misplaced.

![2020-12-10_164727](https://user-images.githubusercontent.com/12406935/101750519-12706680-3b0a-11eb-953d-d1625467e186.jpg)

**Comment by flamber** [comment]
Hi @ljm000 
That looks like a bug in your tile server. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
