### ISSUE TITLE
avoid "XY is an unaggregated field: if it has more than one value at a point on the x-asis, the values will be summed"

### ISSUE THREAD

**Issue by revivepaul** [metabase/metabase#14033]
Hi,

I am building a sales dashboard.

We have:

- total number of sales per sales person
- calendar week
- sales people (therefore, multiple rows for the same calendar week -> Looking for a graph for each sales person)

Currently metabase is (as per the "error" in the subject) throwing all sales people and their sales into one bucket. 
Instead I wan one graph per sales person in the same question visualization.

How can I change the behavior, so that **he values will be summed** does NOT happen.

Thx

**Comment by flamber** [comment]
Hi @revivepaul 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You should group by week and sales person via the Summarize.
