### ISSUE TITLE
BigQuery relative date filter on timestamp field translated to DATETIME_TRUNC() instead of TIMESTAMP_TRUNC()

### ISSUE THREAD

**Issue by SrancsikAtBitrise** [metabase/metabase#14047]
**Describe the bug**
Relative date filters are broken on BigQuery data sources due to type mismatch. 

**Logs**
```No matching signature for function DATETIME_TRUNC for argument types: TIMESTAMP, DATE_TIME_PART. Supported signature: DATETIME_TRUNC(DATETIME, DATE_TIME_PART) at [22:9]```

**To Reproduce**
1. Add a Google BigQuery data source with a timestamp type field.
2. Add field filter on timestamp type fields
3. Set filter value for `Previous 30 days`

**Expected behavior**
Report should be filtered as TIMESTAMP_TRUNC() function works in BigQuery

**Screenshots**
![image](https://user-images.githubusercontent.com/39155393/101918005-2333e180-3bc9-11eb-8d55-9c447e3ac727.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Your databases: Google BigQuery
- Metabase version: 0.37.3
- Metabase hosting environment: Heroku

**Severity**
High. The latest releases of Metabase brought important bugfixes. Unfortunately, we cannot upgrade due to this error.

**Comment by flamber** [comment]
Hi @SrancsikAtBitrise 
I'm having problems reproducing. Can you please supply a sample schema. And which version are you upgrading from?

**Comment by adventuresnick** [comment]
I'm having the same Issue here!

**Note**: "Este mês" means "This month" in Portuguese.

![image](https://user-images.githubusercontent.com/84153574/118180792-58a95900-b40d-11eb-9a01-943568ba8451.png)

**Comment by flamber** [comment]
@adventuresnick You cannot use Field Filters like that: https://www.metabase.com/learn/building-analytics/sql-templates/field-filters.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by SrancsikAtBitrise** [comment]
In former releases, the default type used to be timestamp when casting datetime, date, or timestamp field filters. This issue still exists in 0.39.1.

If you don't specify timestamp explicitly in the Metabase schema ("creation timestamp", "cancellation timestamp" etc.), the field filter is cast as datetime in BigQuery.

It would be great if Metabase recognized the proper casting based on the type of the source as it used to in e.g. version 0.31. Field filters worked on Postgres datetimes, BigQuery datetimes, and BigQuery timestamps without editing the schema in Metabase.

Again, it is working IF you manually set the timestamp type in Metabase.

**Comment by adventuresnick** [comment]
Thankyou a lot! I'll proceed with the instructions. But I totally agree that would be great if Metabase recognized the proper casting automatically.

**Comment by flamber** [comment]
You are more than welcome to open an issue with clear instructions on how to reproduce.

**Comment by dpsutton** [comment]
I'm trying to recreate this and not having any luck.

In bigquery i've got the following schema:

**Comment by adventuresnick** [comment]
I was doing the entire WHERE clause wrong. 
The way that worked for me was just using the Field Filter Variable in the WHERE clause and getting rid of all the rest.

![image (3)](https://user-images.githubusercontent.com/84153574/118290655-0b7cc400-b4ad-11eb-90d9-0b9625f4154c.png)

**Comment by dpsutton** [comment]
i'm glad that's diagnosed @adventuresnick . Does that mean there seems to be non issue then? Just want to make sure that expectations are correct and there's no lurking issue with a semantic_type.

**Comment by adventuresnick** [comment]
From what I saw debugging on BigQuery's side, no there aren't. It's working properly.

I'm still trying to make the trend visualization to work well with relative dates (what I was doing wen I found the Issue) but that is a completely other problem I think haha. Thanks a lot guys!!
