### ISSUE TITLE
Pivot table Cypress tests

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#14049]
Pivot tables use new endpoints to fetch their data, so it's important that we add Cypress tests around this new FE/BE communication.

Core pivot functionality:
- [x] Creating a pivot table as an ad-hoc question
- [x] Viewing a saved pivot table question
- [x] Moving pivoted columns between the top/left headers
The settings widget is new for pivot tables. If testing drag/drop is a hassle, it's fine to skip for now.
- [x] Switching the visualization type _away_ from pivot
When viewing a pivot table we fetched all the subtotal data alongside the main query data. Switching to another viz type should requery and not display any subtotal data.

Pivot tables in other contexts:
- Pivots on dashboards
- Pivots on public/embedded questions/dashboards

Things we don't need to test e2e:
- Specific pivot queries are better covered with unit tests. e.g. we don't need Cypress coverage of having multiple value columns or having no columns assigned to the top header.

**Comment by nemanjaglumac** [comment]
> When viewing a pivot table we fetched all the subtotal data alongside the main query data. Switching to another viz type should requery and not display any subtotal data.

This is super-helpful. Thank you!

**Comment by nemanjaglumac** [comment]
Forgot to add automatic closing keyword in #14049. Can we close this issue now or would you like to leave it open for some further test ideas?
