### ISSUE TITLE
Database-local and User-local Settings

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14055]
What do we do if we want to let a User override the `site-locale` Setting. If we want to let a Database override the `report-timezone` Setting? If a User wants to override the `report-timezone` Setting? Do we just add more columns every time a situation like this arises?

It's not a sustainable pattern, and we should take advantage of Clojure's dynamic functionality to introduce the concept of "Database-local" and "User-local" Settings. These are values of a Setting that would override the global value for a specific Database (e.g. when processing queries) or for a specific User.

These would be analogous to [buffer-local variables in Emacs Lisp](https://www.gnu.org/software/emacs/manual/html_node/elisp/Intro-to-Buffer_002dLocal.html#Intro-to-Buffer_002dLocal). Consumers of Settings could be completely oblivious to the fact that an override is taking place -- this would all happen behind the scenes. This would simplify a lot of code -- no more separate `user_locale` column, and no more code like 

```clj
(defn user-locale []
  (or (:user-locale @*current-user*)
      (site-locale)))
```

In the future when we wanted to add new flags we could get both a global default and DB-specific option for free.

Notes:

*  I think we could implement this as JSON map in `Database` and `User` specifically
*  We already have a `*current-user*` dynamic variable, so we should add `*current-database*` as well 
*  Like buffer-local variables, we'd want to have the option to disallow Database-local or User-local values for some settings. Probably don't want Users setting their own SMTP credentials under any circumstances
*  I think User-local values would take precedent over Database-local values
*  We should have functionality in place to get the global values even if there is a Database-local or User-local, e.g. if we want to use the system locale for log messages regardless of any User-specific overrides. This would be relatively rare I think
*  Consider whether we could benefit from Table-local or Field-local overrides as well

**Comment by flamber** [comment]
Related to #4284

**Comment by camsaul** [comment]
Assigning this to you @noahmoss so you get credit when #20456 closes it out
