### ISSUE TITLE
Minor MBQL Improvement Proposals

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14057]
MBQL is pretty hairy/wonky at this point, and rewriting the whole thing from scratch would be nice but probably isn't realistic. 

Here are a few small refactors that we have a realistic chance of implementing that would give us a lot of value:

##  Flatten the structure

e.g. 

```clj
{:database 1, :type :query, :source-table 2}
```

instead of 

```clj
{:database 1, :type :query, {:query :source-table 2}}
```

It causes an unbelievable headache with source queries and query processor code in general -- are we currently manipulating the "outer query" (top level with `:database`) or "inner query" (second level with `:source-table`)? Unlimited hairiness.

## ~~Unify Field clauses~~ (Implemented in #14897)

Field clauses are unbelievably hairy when you start adding info and I think we should replace everything with a single clause like

```clj
[:field id-or-name {all-other-info ...}]
```

Here's an example. This is actually a real way to represent a Field in MBQL:

```clj
[:datetime-field [:joined-field "my_join_alias" [:field-literal "my_field" :type/Integer]] :month]
```

This actually makes implementing the MBQL -> SQL compiler really since the shape closely matches what we do when generating SQL, but it's borderline impossible to write by hand. Something like 

```clj
[:field "my_field" {:actual-type :type/Integer, :temporal-unit :month, :join-alias "my_join_alias"}]
```

is a big improvement IMO.

## Make MBQL schema more flexible

This is mostly for generating test queries -- it would be nice to be able to have the equivalent of `honeysql.core/raw` for MBQL queries. Or perhaps something more general like HoneySQL's `ToSQL` protocol. 

## Rename `:type :query` to `:type :mbql` 

It's not obvious what a `:query` type query is. The main reason it's called `:query` is that it predates calling anything "MBQL" by a few years -- in the original product, we called MBQL queries "structured _queries_" (yes, this is as opposed to _S_ tructured _Q_ uery _L_ anguage queries). I actually came up with the name "MBQL" so people would stop calling them structured queries. Now I'd like to put the last nail in the "structured query" coffin

## Add support for a "threaded" or "notebook" query type

For powering notebook queries. Instead of nesting source queries 100 layers deep, why not let people pass in an array of queries and do the source query nesting ourselves?

**Comment by sbelak** [comment]
Big +1 on all 5 points

**Comment by camsaul** [comment]
Also: #14868

**Comment by camsaul** [comment]
#19330 could be considered an MBQL improvement proposal as well

**Comment by camsaul** [comment]
Here's another idea: let's drop `:source-table "card__1000"` and just use `:source-card` or something instead. The whole `card__` thing was just a hack in the first place and a silly one

**Comment by camsaul** [comment]
This is all mostly implemented in MLv2/pMBQL, so closing this as more or less done.
