### ISSUE TITLE
How to get the name of the current login user as query criteria!!!!!! 

### ISSUE THREAD

**Issue by wangpeijin** [metabase/metabase#14060]
How to get the name of the current login user as query criteria!!!!!! 
In other words, is there any way to do more refined permission control.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You can use Sandboxes, which is part of the Enterprise Edition: https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html
