### ISSUE TITLE
Bar charts show really skinny lines when the x-axis is a timeseries

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1406]
<img width="1403" alt="screen shot 2015-10-29 at 8 44 05 pm" src="https://cloud.githubusercontent.com/assets/1987787/10838022/d7882e02-7e7d-11e5-8a24-b7aabe77c4b0.png">

**Comment by tlrobinson** [comment]
(This is basically the same as #1208 but has a better title)

**Comment by agilliland** [comment]
got it.  i'll close this as a dupe and update the title on the other one.
