### ISSUE TITLE
Provide a way for Mac app users to reset their password

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1407]
Currently there is a potential issue if a user of the Mac app forgets their password their is no way to reset it and get back into the instance.

**Comment by salsakran** [comment]
+1

**Comment by tlrobinson** [comment]
Ideally we'd never even require that the user log in on Mac app. We could probably automagically generate a session and set the cookie in the Mac app, or some other approach.

**Comment by agilliland** [comment]
@camsaul Just wanted to make sure the expected approach here is nailed down, so here's a recap of the proposed solution.

* user triggers reset from an item in the application menu bar
* the Mac code does what's need to A) find the first admin user created and B) update their reset token
* the app then navigates to the password reset page where the user has the ability to pick their password

The main clarification is that we want to avoid asking for a users email on the mac app and instead we should just simplify things and always reset the password of the first admin user we find in the db.  This seems natural since most of the time there will only be 1 user in the db anyways.
