### ISSUE TITLE
View total in tooltip for stacked bar chart

### ISSUE THREAD

**Issue by idan-codefresh** [metabase/metabase#14079]
When viewing a stacked bar chart you want to see the individual values but you want to see the value of the stack when you hover over a column (x data point).

It would be great if the tooltip could show the individual value and the sum of the stack. Or even show the value for all parts of the stacked bar.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Very related to #13096

**Comment by alxnddr** [comment]
We will ship this in 46:
<img width="1359" alt="Screen Shot 2023-02-20 at 7 36 26 PM" src="https://user-images.githubusercontent.com/14301985/220208067-cc22b0e1-7bbd-442b-8e34-28792f974c5f.png">

**Comment by fdevillalobos** [comment]
Hey guys, I think this issue has not been solved in 46. I am getting tooltips that are wrong. Just showing the value for one of the breakdowns in the stacked graph (either 100% stacked or stacked).

<img width="1461" alt="Screenshot 2023-05-18 at 19 42 59" src="https://github.com/metabase/metabase/assets/6305634/29a8ed3b-93b5-4548-b551-98ad19014ca9">
These two graphs are the same, one not stacked, and one stacked. And as we can see... in the bottom graph we see a tooltip that adds up to 6k, but should go all the way to 16k. It is showing the value for ONE of the SUM() it is doing inside. 

Am I doing something wrong? I tried a lot of stuff and it doesn't seem to work. Please help or let me know if there is an open issue here. Thanks!
