### ISSUE TITLE
Allow configurable files Slack channel

### ISSUE THREAD

**Issue by trov-madisonhope** [metabase/metabase#14086]
**Is your feature request related to a problem? Please describe.**
As a deployment architect, for the sake of security, I need to segment multiple metabase instances so they can't access each other's Slack files in #metabase_files.

**Describe the solution you'd like**
An environment variable/admin setting to override the default channel.

**Describe alternatives you've considered**
Multiple users, but this still muddies the waters.

**How important is this feature to you?**
Pretty important as we consider data residency restrictions.

**Comment by flamber** [comment]
Duplicate of #5236
