### ISSUE TITLE
Question or dashboard on the landing page

### ISSUE THREAD

**Issue by orenmazor** [metabase/metabase#14083]
**Is your feature request related to a problem? Please describe.**
not a problem, per-se.

I'd like to have the output of one query be shown on the main page of metabase:

![Screen Shot 2020-12-15 at 11 28 05 AM](https://user-images.githubusercontent.com/384279/102242946-9c348100-3ec8-11eb-8c47-812fba4607db.png)

above `Our Analytics`, I'd like to have the output of one question. in my case, my data lake is updated at various times, and I can get the updated at via sql. I'd like the output of that to be at the top.

**Describe the solution you'd like**
could be a dashboard as well. or something else. I'm not picky. just having it automatically there would be good :)

**Comment by flamber** [comment]
Hi @orenmazor 
Sounds like #9585 would solve what you are asking for without adding too much complexity. Also might be of interest: #7266

**Comment by orenmazor** [comment]
nifty! I dig it. both would be very cool
