### ISSUE TITLE
Dots in table names aren't escaped

### ISSUE THREAD

**Issue by lucian1900** [metabase/metabase#1408]
I have a Postgres database with several tables that have "." directly in their name, not as a schema separator. So there are tables like "objects.stuff" and "configs", both in the same schema.

However, the query metabase emits refers to "objects"."stuff", which is incorrect.

**Comment by lucian1900** [comment]
I don't mean to be obnoxious, but that doesn't quite seem like the right fix in the general case. The reason I ended up with dots in table names is that users control the table name. None of my current users use anything odder, but others folks might have the same use-case.

Looking at it now, I believe it's a bug in Korma that it makes assumptions about mangling table names at all. All it should do is quote the name while escaping quotes. Perhaps I should file a bug with them.

**Comment by agilliland** [comment]
@lucian1900 , I agree this is an unfortunate workaround for what is clearly a limitation with Korma.  The solution looks like it should resolve your particular problem when it comes to using Metabase though, so maybe you could expand on why you don't think this is the right fix.

We should definitely file an issue with Korma and if you want to go ahead and do that it would be great because that's where the real issue stems from.

**Comment by camsaul** [comment]
Using dots to separate components of identifiers is one of the core "features" of Korma. We're doing things with it that it is clearly not designed to do, so workarounds are to be expected, not considered "unfortunate".

Their [project moves very slowly from what I've seen](https://github.com/korma/Korma/issues/334) over the last few years; I don't think you'll see them rework their library and change a fundamental assumption to support a tiny edge case unless you submit a PR yourself.

**Comment by lucian1900** [comment]
You're absolutely right that it solves my immediate problem.

I guess i'm just very surprised an SQL library would make such dangerous assumption about naming. In-band signalling like this is quite the liability.
