### ISSUE TITLE
Can't delete databases

### ISSUE THREAD

**Issue by cstavlas** [metabase/metabase#1409]
The delete button appears in the admin panel when I try and remove the Sample Data or a mistakenly added database, but the button is unclickable.

**Comment by tlrobinson** [comment]
Hmm, I haven't seen this before. Could you tell me if you see any errors in the JavaScript console?

Also the version number of your installation (select "About Metabase" in the menu in the top right)

**Comment by agilliland** [comment]
also include your browser + version as this could be something that's browser specific.

**Comment by cstavlas** [comment]
Metabase version number: v0.12.1
This is in the metabase client, but my browser is chrome v46.0.2490.80

**Comment by cstavlas** [comment]
![cant delete](https://cloud.githubusercontent.com/assets/5995159/10898409/ecf91ca2-817e-11e5-8c03-5f22f4edb8f7.png)

**Comment by agilliland** [comment]
I tried to reproduce this a few different times but I'm not seeing this happen in the current v0.13.3 version of Metabase.  I'm going to close this as fixed and we can reopen if it resurfaces.
