### ISSUE TITLE
Update docs with changes to drill-through/actions menus

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14095]
We restyled the drill-through and actions menu for 0.38. Not super important, but just a note that we dropped the `min` and `max` actions from numeric column headings; otherwise the functionality is the same.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/2223916/102290963-e6ccf200-3ef6-11eb-9f86-39b436404881.png">

<img width="270" alt="image" src="https://user-images.githubusercontent.com/2223916/102290971-ecc2d300-3ef6-11eb-9815-2fb01fd6071b.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/2223916/102290991-f64c3b00-3ef6-11eb-9e6b-f6800f508471.png">

<img width="387" alt="image" src="https://user-images.githubusercontent.com/2223916/102291021-05cb8400-3ef7-11eb-871a-a624dbbadda7.png">

**Comment by jeff-bruemmer** [comment]
Closed by #14153
