### ISSUE TITLE
Redshift Error: tried to set timezone to US/Pacific Detail: Not user settable.

### ISSUE THREAD

**Issue by cstavlas** [metabase/metabase#1410]
Error when trying to run a query on Redshift, nothing special about the query, just a select * from a table in the public schema.

**Comment by tlrobinson** [comment]
We don't actually support Redshift yet, but it's on our shortlist: #652 

This particular error *might* be resolved by unsetting the report timezone in /admin/settings, but I believe there are other problems with using our Postgres driver with Redshift.

**Comment by cstavlas** [comment]
the unsetting timezone workaround is "working"

**Comment by camsaul** [comment]
In #1431 I changed the code for setting timezone to run the query without setting it if it fails. So you won't have to do the workaround once that goes live in the next release.

Redshift still [has a lot differences with Postgres](http://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html) however so there's a chance you'll run into other issues until we have a Redshift-specific driver :crying_cat_face:
