### ISSUE TITLE
Add ssl client certificate support for mongo connections

### ISSUE THREAD

**Issue by dnlmengs** [metabase/metabase#14108]
Using client side certificates is not so uncommon and would be great seeing metabase supporting them for everything, but specifically for mongo, in this case.

The form for connecting to mongo databases doesn't take into account some frequently used options (replicasets comes to mind) but offers the option for using uris for this, which is enough most of the time.

In the case of custom certificates (client or otherwise) metabase doesn't honor the connection string options. For example, this doesn't work:
`mongodb://user:pass@my.host:27017/mydb?replicaSet=myrs&authSource=admin&tls=true&tlsCertificateKeyFile=/path/to/client.pem&tlsCAFile=/path/to/ca.crt`

But the documentation for the uri states that neither tlsCertificateKeyFile nor tlsCAFile are supported by all drivers (https://docs.mongodb.com/manual/reference/connection-string/), so this didn't came as a surprise.

**Describe the solution you'd like**
A way to setup with ease (a text box in the form?) client-side certificates for mongo in the metabase ui.

**Describe alternatives you've considered**
Using connection string options and the uri form boxes, but neither of them work:
`mongodb://user:pass@my.host:27017/mydb?replicaSet=myrs&authSource=admin&tls=true&tlsCertificateKeyFile=/path/to/client.pem&tlsCAFile=/path/to/ca.crt`

**How important is this feature to you?**
Would be a super nice to have feature for us, but we will workaround this probably by setting up a separate database with the data. Little Timmy is not going to die of cancer because of this.

For reference: https://discourse.metabase.com/t/connecting-to-mongodb-with-client-side-ssl/6553

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by torras** [comment]
@flamber thanks!!

**Comment by luizarakaki** [comment]
We are currently working on this feature. We are planning to support RSA keys. If you need support for another key type, let us know.

**Comment by RoeiRom** [comment]
Is there any progress/expected release date for this feature. I need it as well

**Comment by flamber** [comment]
@RoeiRom Client certificate was add in 0.44.0, but only for individual fields not full connection string (from what I can tell).
#22889 #22977

**Comment by RoeiRom** [comment]
@flamber but I also need the option for connecting replica sets with ssl certificate

**Comment by flamber** [comment]
@RoeiRom Click "Show advanced options", where you have the "Additional connection string options" to add `replicaSet`
If you need the full connection string, then I guess you'll have to wait for this issue to be solved. I cannot give a timeline.

**Comment by RoeiRom** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/52863381/185312024-02eb15c3-dbc9-4fbe-9fc3-6616e93ab311.png">
Hi There, @flamber I'm not seeing this option running your latest docker image

**Comment by flamber** [comment]
@RoeiRom Click "Full out individual fields". If you need further help then use the forum.

**Comment by luizarakaki** [comment]
Shipped on 44 #22977
