### ISSUE TITLE
Subcollection permissions not working right in sidebar on master

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14114]
This is quite similar to https://github.com/metabase/metabase/issues/14052 but has to do specifically with the new collections sidebar in master.

**To Reproduce**
1. As an admin, create a hierarchy of collections like this:
```
- Our analytics (Revoke permissions to All Users)
- - Parent collection (Revoke permissions to All Users)
- - - Child collection (Give All Users group Curate access)
```

2. Create a non-admin user and log in as that user.

3. You'll find that you can correctly see the Child collection on the homepage:

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/2223916/102529711-27db1880-4055-11eb-96f4-dcf25077deea.png">

… but when you click on "Browse all items" you won't see the Child collection in the sidebar, though you should. (Admin view on left, non-admin on right.)

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/2223916/102529356-9bc8f100-4054-11eb-8ab5-f1be43da2a75.png">

**Comment by nemanjaglumac** [comment]
@mazameli is it expected that you see **only** Child collection as an ordinary user, or you'd still see Parent > Child nesting structure, but be able to access only Child?

I'm going to slightly adjust https://github.com/metabase/metabase/pull/14073 to repro this issue specifically.

**Comment by mazameli** [comment]
> is it expected that you see only Child collection as an ordinary user

@nemanjaglumac, they'd see "Our analytics" and "Child" in the sidebar.

Explanation: Whenever a user has permissions for a sub-collection, but not its parent(s), that collection can be seen by the user in the next top-most folder that the user _can_ see. Also, as far as the root collection goes, based on how things worked up until 0.37, in this scenario the non-admin user should be able to go to the root folder but not see any of its contents except for any sub-collection(s) the user has view/curate permissions for. 

To be super explicit, in the example in the description, the non-admin's sidebar should look like this:

```
- Our analytics (can click on this, but its content area will appear empty)
- Child (it gets "bumped up" so that it appears to be a top-level folder since the user can't see the Parent folder)
- Your personal collection
```
