### ISSUE TITLE
Sub collections under "My Personal Collection" are not available in Save or Move dialogs

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#14122]
**Describe the bug**
Collections created under a persons personal collection are not accessible in the Save or Move dialogs. In order to get things into them you've got to save it somewhere else then drag and drop them into those sub collections.

**Logs**

**To Reproduce**
1. In you personal collection create a child collection
2. Create a new question 
3. Click "Save"
4. Note that there is no ">" to expand "My personal collection" 

**Expected behavior**
Sub collections below personal collections are treated the same as other collections in regards to saving and moving. I expected them to be accessible from the Save and move dialogs

**Screenshots**
Save
![image](https://user-images.githubusercontent.com/4504437/102548273-49083b80-411f-11eb-8b3b-343c6a487ff3.png)

Move (note that is a v0.38-preview but it exists in previous versions, love the new collections in v0.38!)
![image](https://user-images.githubusercontent.com/4504437/102548302-5291a380-411f-11eb-984a-3e206bf531d3.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-08",
      "tag": "v0.38.0-preview",
      "branch": "master",
      "hash": "ae50a80"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}

**Severity**
It's inconsistent, there are ways to work around it by drag and drop but I imagine with the new layout in v0.38 with the improved visibility of these collections it might pop up a bit more.

**Additional context**
I've seen this in all older versions including v0.37.2. Really like the new layout, good work.

**Comment by mazameli** [comment]
Hey, @notrom. This looks like an incomplete issue, and also it is in fact already possible to have sub-collections under your personal collection. So I'm closing this, but we can reopen if you have more details about what you ran into.

**Comment by notrom** [comment]
@mazameli yep sorry, fat fingers managed to submit by accident. I've updated with details.

Thanks

**Comment by flamber** [comment]
No sure why I didn't catch that during #14052, since I actually have sub-collections in my personal collection.

**Comment by rcronin** [comment]
Still seeing this issue on Enterprise V1.40.4. Any update on when this will be resolved?
