### ISSUE TITLE
Cancel button on Delete Database modal is not working

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1413]
Hitting either the `Cancel` button or the `X` in the upper right corner is failing to dismiss the modal for me on Chrome right now.

<img width="774" alt="screen shot 2015-10-30 at 2 52 18 pm" src="https://cloud.githubusercontent.com/assets/1987787/10858941/f6c770aa-7f15-11e5-8369-a736956e2606.png">

**Comment by tlrobinson** [comment]
This is specifically for the delete button on the database listing page, not database detail page, right?

**Comment by agilliland** [comment]
yes
