### ISSUE TITLE
Can't use a binned numeric dimension as a grouping in a pivot table

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14136]
Try summarizing Orders by `Count` and `Subtotal: Binned`, then choosing the pivot table viz. Here's a [sample query if you're running on localhost:3000](http://localhost:3000/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MiwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJicmVha291dCI6W1siYmlubmluZy1zdHJhdGVneSIsWyJmaWVsZC1pZCIsMTRdLCJkZWZhdWx0Il1dfSwiZGF0YWJhc2UiOjF9LCJkaXNwbGF5IjoiYmFyIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319). The query will run indefinitely until you close the sidebar, at which point you'll see an error that there was a problem with the viz.

![pivot-with-binned-dim](https://user-images.githubusercontent.com/2223916/102645850-f5deba80-4117-11eb-8f94-b15869b4d1db.gif)

JS console goodness:

```
Uncaught (in promise) TypeError: Cannot read property 'cols' of undefined
    at column.js:57
    at Array.map (<anonymous>)
    at DEFAULT_GET_COLUMNS (column.js:51)
    at Object.getProps (nested.js:138)
    at getSettingWidget (settings.js:182)
    at settings.js:231
    at Array.map (<anonymous>)
    at getSettingsWidgets (settings.js:230)
    at getSettingsWidgetsForSeries (visualization.js:114)
    at ChartSettings._getWidgets (ChartSettings.jsx:119)
```

**Comment by paulrosenzweig** [comment]
This is fixed on #14096 (which isn't merged yet).
