### ISSUE TITLE
Pivot tables: grouping field settings

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14172]
This is missing functionality per the [product doc](https://docs.google.com/document/d/1ScNpNjjYlsi6syyHFKctTlZ149g5ulTIHFnAmmq6h58/edit#). Pivot tables are supposed to have a way to show settings for a row or column grouping field to allow the user to:
- Turn subtotals off/on
- Change the sort order for that group
- Access the column formatting options for the values in that group

<img width="343" alt="image" src="https://user-images.githubusercontent.com/2223916/102940300-da9be400-4464-11eb-91c6-5e1042bce925.png">

**Comment by paulrosenzweig** [comment]
Implemented in #14621, #14559 and #14464.
