### ISSUE TITLE
Pivot tables should have standard drill-through actions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14173]
If I create a pivot table via one of the GUI query builders, I should see the standard drill-through/actions menus like with regular tables.

- When clicking on values cells, I should see this menu:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/2223916/102940643-a248d580-4465-11eb-9dba-7a6b0574f222.png">

- When clicking on a cell value in a grouping row/column, I should get the filter menu:

<img width="159" alt="image" src="https://user-images.githubusercontent.com/2223916/102940681-bb518680-4465-11eb-86fa-554236c55ffb.png">

- And when clicking on a grouping field _heading_ (i.e., the name of the field), I should get this menu:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/2223916/102940740-dde39f80-4465-11eb-89b1-dd85a70386da.png">

**Comment by camsaul** [comment]
@paulrosenzweig I'm transferring this to you since it sounds like you have it almost all figured out... let me know if you want me to tackle anything else instead
