### ISSUE TITLE
unnecessary column appeared  when do  join from two questions  

### ISSUE THREAD

**Issue by szsuyuji** [metabase/metabase#14200]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1931764/103129798-1210c780-46d5-11eb-9049-8e68633b49de.png)
 "source"."channel_name" and "source"."remark" is not exist in the first query，so i guess they were from the original table

metabase version: 0.37.4

**Comment by flamber** [comment]
Duplicate of #13649
