### ISSUE TITLE
Query errors out when MySQL Date field is set to '0000-00-00'

### ISSUE THREAD

**Issue by kainoa21** [metabase/metabase#1420]
This was specifically happening when getting any results from a query in the QB where aggregation was set to `:rows`.  Setting the values to NULL corrected the problem, but ideally we would handle this case more gracefully.

**Comment by camsaul** [comment]
Do you mean you were trying to use `"0000-00-00"` in a query or the actual data inside your DB had values with `"0000-00-00"`?

**Comment by agilliland** [comment]
The data inside the db had `"0000-00-00"` as the date value instead of NULL
