### ISSUE TITLE
Dashboard subscriptions' titles should link back to the dashboard

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14211]
The title of an email or Slack dashboard subscription should be a link that takes you back to the corresponding dashboard in Metabase, so that you can see all the questions in context, make changes to the subscription, etc. Otherwise you'd have to manually open Metabase, then search for that dashboard.

## Email

<img width="667" alt="image" src="https://user-images.githubusercontent.com/2223916/105522564-45be1d80-5c92-11eb-928d-df809132b149.png">

## Slack

<img width="769" alt="image" src="https://user-images.githubusercontent.com/2223916/105522759-7b630680-5c92-11eb-8ff0-bb71e245ee57.png">

### Note
This issue originally additionally recommended making questions within subscriptions also link back to the dashboard, if you're wondering about the comments below in this issue.

**Comment by kdoh** [comment]
> But with dashboard subscriptions, it makes much more sense to take the user back to that dashboard.

@mazameli I don't know that I'm as convinced this makes sense. It feels a bit odd to me that if I click or tap on a specific question I'd be taken to a dashboard and then potentially have to scroll down to find it.

**Comment by mazameli** [comment]
@kdoh Fair, re: question cards in a subscription, but I still feel quite strongly that it makes absolute sense for the _title_ of the subscription to take you to the dashboard — what if I want to see all the cards together in the curate arrangement and with the correct visualization, or what if I want to make an adjustment to the timing of contents of the subscription, etc.?
