### ISSUE TITLE
Mapped value shows random number for 0 instead of string in chart

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#14218]
**Describe the bug**
After setting up values mapping for a field, when showing a chart aggregating this field, a random number instead of the mapped label for the original value of 0 is shown on bar chart.

**To Reproduce**
1. Set up a mapping with a 0 as one of values.

![image](https://user-images.githubusercontent.com/30152071/103295609-9eccc580-49f4-11eb-9a8c-22e136d2e8ec.png)

2. Open the table and click on "Distribution" in the column title dropdown list to get the following query:

![image](https://user-images.githubusercontent.com/30152071/103295908-4813bb80-49f5-11eb-9f41-55d4c3a7332a.png)

3. Notice the label for 0 is shown as a real number instead of the mapped value.

![image](https://user-images.githubusercontent.com/30152071/103295712-d5a2db80-49f4-11eb-8e00-cb9c529c22d1.png)

**Expected behavior**
The value for 0 should shown the label set.

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.165-103.209.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-11-16",
      "tag": "v0.37.2",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Severity**
A nuisance.

**Additional context**
The pie chart works correctly. I could not reproduce this on the sample set as it doesn't have any suitable columns with a 0.

**Comment by flamber** [comment]
Very related to #13255 - same workaround, changing "X-axis scale" to "Ordinal" shows correct value.

**Comment by flamber** [comment]
Fixed by #21263
