### ISSUE TITLE
Add additional metadata to collections lists

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14213]
It would be useful to have metadata like who originally created a given dashboard or question, when it was created, and when it was last modified. Then users could sort on those attributes in a list, like this:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/2223916/103252163-74193900-4930-11eb-9802-86cf3bfef0d2.png">

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by notrom** [comment]
I know it's not the same kind of metadata but it would be really, really useful show a count of references (with a drilldown to list the details) to each question i.e. how many dashboards, alerts, nested questions each question is used in.

**Comment by mazameli** [comment]
That's great feedback. What problem would that metadata help you solve, primarily? Identifying which saved questions are save to archive so that you can clean up cruft? Identifying which tables/views you might want to prioritize materializing or queries you would want to optimize in order to make the most-used items load faster? Or something else?

**Comment by notrom** [comment]
@mazameli for me it's mostly just for ease of house keeping, I'd like to know what the downstream affects will be if I delete or change a question. I know I can query the Metabase database directly for this info but it's a few extra steps that not everyone knows how to do.

**Comment by flamber** [comment]
Related to #13975 #13139 and #13435 and #11945 #9555

**Comment by kulyk** [comment]
Closing this as [it was shipped in 0.40](https://github.com/metabase/metabase/pull/16510). I believe we can track the requests to show linked entities (e.g. dashboards using a question) in the issues above
