### ISSUE TITLE
List of available databases is empty in setup process

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1421]
When I try to select a database type to add in the setup process I get an empty list.

<img width="946" alt="screen shot 2015-11-01 at 10 26 44 pm" src="https://cloud.githubusercontent.com/assets/107439/10875479/9986c408-80e7-11e5-91da-1e5bf031cdc3.png">

**Comment by kdoh** [comment]
Just tried this on the 0.12.1 Mac app and was able to set up a Postgres db just fine and everything seemed to be working ok. Were there any particulars to your setup process?

**Comment by salsakran** [comment]
This was on master

**Comment by tlrobinson** [comment]
Looks like it was broken when we moved to using `db_form_input` to populate the list/fields.

**Comment by tlrobinson** [comment]
@camsaul I tried fixing this but we currently can't call `form_input` if we're not logged in. Do we need to move it to a route without the `+auth` middleware?

**Comment by camsaul** [comment]
Whoops I overlooked this. I'll fix it this morning
