### ISSUE TITLE
Move the dashboard Add-Data interaction to a sidebar

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14225]
This issue is highly related to https://github.com/metabase/metabase/issues/4202, though it can be done separately from this. The designs in this issue depict a state of things where https://github.com/metabase/metabase/issues/4202 has been implemented, though — i.e., with collections correctly being displayed.

But the core of this proposal is to move the add-data or add-series experience to a sidebar in the dashboard, since we've done that with dashboard interactivity, and plan on doing it for [adding questions to a dashboard](https://github.com/metabase/metabase/issues/13842), and for [dashboard chart visualization settings](https://github.com/metabase/metabase/issues/13864).

**Here's the [prototype](https://www.figma.com/proto/TwnO0YxR4PCXDEunLeEChP/Dashboard-Card-Add-Data-in-Sidebar?node-id=7%3A738&viewport=489%2C748%2C0.5&scaling=min-zoom):**
1. Hover on the line chart
2. Click on the add-data icon
3. The sidebar will open
4. Try clicking on the `Eng` folder to see how you can navigate to a sub-collection if and when https://github.com/metabase/metabase/issues/4202 is implemented.
5. Click on `our analytics` to go back to the top level folder.
6. Click on the `Revenue over time` question to add it to the chart
7. The screen will auto advance after about 1 second to show the added green series. You can click the checkbox again to remove the series, or click Done to close the sidebar.
8. You can reopen the sidebar by hovering over the chart and clicking the add-series icon again, and this demonstrates how you can remove the series.

**Possible improvements**
I think the designs could be improved by exploring ways to make the added series(es) appear at the top of the sidebar right away in situations where you've added more than 1 series from different collections.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/2223916/103322722-2239e700-49f4-11eb-981b-c6764c21e72b.png">

**Comment by brunobergher** [comment]
Not relevant in this shape anymore, lots of work happening in this front around the visualizer, etc, so closing.
