### ISSUE TITLE
Expose additional string filter options in the query builder

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1422]
E.g.:
* Starts With / Doesn't Start With
* Contains / Doesn't Contain
* Ends With / Doesn't End With

This would be really helpful for doing things like filtering out certain email address domains. ("Does not contain '@acme.com'.")

**Comment by camsaul** [comment]
We have these. I implemented them in #839

**Comment by camsaul** [comment]
It appears they disappeared from the QB at some point. But we had them 2 months ago

**Comment by camsaul** [comment]
@tlrobinson @agilliland @kdoh Anybody know what happened to the advanced string filter options?

**Comment by agilliland** [comment]
I'm not sure I recall them ever actually be in the QB, at least not for a long time.  I suspect it was done just as a means to keep the UI concise while we were figuring things out.  Definitely +1 to incorporating this back in.

**Comment by tlrobinson** [comment]
They were definitely in there (not the negated versions IIRC) but we took them out when we redid the filter widget, though I'm not sure why since we simultaneously added the "more options" widget.

**Comment by styts** [comment]
+1 Would like to have this too.

**Comment by infomofo** [comment]
we would like these too- many of our sql query cards are templates using this format so this would let more of us use the query builder directly.

**Comment by m-collins** [comment]
+1 we would like to have this too

**Comment by adamteece** [comment]
+1 will be amazingly helpful

**Comment by mazameli** [comment]
@kdoh Do you have any thoughts or context about the history of this?

**Comment by gppeixoto** [comment]
It might not be the appropriate issue to comment on, but shouldn't `greater_than` and `bigger_than` operations also be supported for strings on query builder? I think this should be a relatively common operation on ISO date strings such as `2018-01-01`

**Comment by cemsbr** [comment]
Yes, @gppeixoto, and using an ISO column is much much faster than the current approach to query a date field in MongoDB. Currently, the index is not used and **all** entries are converted to ISO and compared...
