### ISSUE TITLE
Scrolling doesnt update dragging on Visible Column configuration

### ISSUE THREAD

**Issue by ishwi** [metabase/metabase#14238]
**Describe the bug**
Scroll doesnt behave properly when you try to move a column of the visible column list in the table view configuration.
Happens when there are more columns than fit on a screen so there is a scroll.

**Logs**
Not relevant

**To Reproduce**
1. Go to a question with a visualization type of Table.
2. Press the configuration option
3. On the Visible Column option, Hold and try to drag one column.
4. While dragging it, scroll the page to try to go down or up. The dragged option will move while dragged, but the destination when you drop doesn't update at all.

**Expected behavior**
When you scroll the destination should be updated with the scroll

**Screenshots**

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.7.0-0.bpo.2-cloud-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-17",
      "tag": "v0.37.4",
      "branch": "release-x.37.x",
      "hash": "e0d5287"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Its annoying becuase it makes the sorting of the columns an annoying task.

**Additional context**

https://user-images.githubusercontent.com/24591814/103546887-f3b08600-4ea3-11eb-97c6-0d47ce7ac985.mp4

**Comment by flamber** [comment]
Related to #12870 and #12494 and #3266
