### ISSUE TITLE
We should make bulk-move / bulk-archive in collections more obvious

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14231]
I have heard over and over and over from users (and some of our own team members) that they had no idea you can hover over the icon for an item in a collection to make a checkbox appear so that you can move or archive multiple items at once.

We should make this way more obvious by doing something such as having a checkbox appear to the left of the item when you hover over any part of the item, like this:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/2223916/103387321-d5b7df80-4ab7-11eb-99a2-43a9d08213e8.png">

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Implemented in 0.42
