### ISSUE TITLE
MongoDB使用外键时出现异常

### ISSUE THREAD

**Issue by Aaronwang81** [metabase/metabase#14250]
**Describe the bug**
我使用Metabase连接MongoDB做为数据源，其中有两个表（集合）,分别是UserDetail和User。在UserDetail表中，有一个字段 是UserId，此字段 的值对应为User表中的_id，当我在数据模型中将UserDetail表的UserId类型修改为外键，值为User表的_id后。在查询中可以正常显示这个外键且占击时能正常显示内容。
但当我将UserDetail表的UserId显示值修改为User表中任意一个字段时，查询结果报" [[CreateDate]]星期几"，"CreateDate"是User表中的一个字段。

**Logs**
 :started_at #t "2021-01-05T01:23:01.018008Z[GMT]",
 :error_type :unsupported-feature,
 :json_query {:database 2, :query {:source-table 90}, :type "query", :parameters [], :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> query_processor.middleware.add_implicit_joins$add_implicit_joins_STAR_.invokeStatic(add_implicit_joins.clj:240)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins_STAR_.invoke(add_implicit_joins.clj:236)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__37681.invoke(add_implicit_joins.clj:254)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__44085.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__44110.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__44065.invoke(format_rows.clj:75)"
  "query_processor.middleware.desugar$desugar$fn__43539.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__42560.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__43077.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__37225.invoke(add_dimension_projections.clj:318)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__37432.invoke(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__37830.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__45004.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__42148.invoke(auto_bucket_datetimes.clj:140)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43124.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__44789.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__43176.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__43795.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__37861.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__45725.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__45015$fn__45019.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__45015.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__44013.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__45734$fn__45735.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__45734.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__43053.invoke(cache.clj:214)"
  "query_processor.middleware.validate$validate_query$fn__45743.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__44137.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__37699.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__45710.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__43416.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__44878.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__43359.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___36488$thunk__36489.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___36488.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___36497$fn__36500.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___36497.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
  "query_processor$fn__45901$process_query_and_save_execution_BANG___45910$fn__45913.invoke(query_processor.clj:249)"
  "query_processor$fn__45901$process_query_and_save_execution_BANG___45910.invoke(query_processor.clj:241)"
  "query_processor$fn__45945$process_query_and_save_with_max_results_constraints_BANG___45954$fn__45957.invoke(query_processor.clj:261)"
  "query_processor$fn__45945$process_query_and_save_with_max_results_constraints_BANG___45954.invoke(query_processor.clj:254)"
  "api.dataset$fn__52612$fn__52615.invoke(dataset.clj:59)"
  "query_processor.streaming$streaming_response_STAR_$fn__52593$fn__52594.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__52593.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__24637.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error "[[CreateDate]]按星期几",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data {:driver :mongo, :type :unsupported-feature},
 :data {:rows [], :cols []}}

**To Reproduce**

**Expected behavior**
使用mongodb连接时，关联外键且设置显示值后，出现查询错误。

**Screenshots**
![image](https://user-images.githubusercontent.com/37022191/103598366-5f92fd00-4f3d-11eb-85cf-c09fa7d558a0.png)
![image](https://user-images.githubusercontent.com/37022191/103598402-79344480-4f3d-11eb-8737-acae4cf723ba.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "zh",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.4.0-56-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-17",
      "tag": "v0.37.4",
      "branch": "release-x.37.x",
      "hash": "e0d5287"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Hi @Aaronwang81 
Please create issue in English - otherwise it's really difficult to understand and reproduce.
MongoDB does currently not support remapping: #7462 - upvote by clicking :+1: on the first post
