### ISSUE TITLE
Map visualization & data type for first column

### ISSUE THREAD

**Issue by ArnoldWertfaktor** [metabase/metabase#14254]
In Metabase, the map visualization cannot be selected correctly if the first column is of type Numeric. With a string, on the other hand, it works.

Below is a small code to reproduce. The first variant (see screen) does not work, but the other three ones do (see screen 2 for an example).

For the code example 3 cities with their respective coordinates are used
```
--/*
SELECT 53.543764 AS "latitude", 10.009913 AS "longitude", 'Hamburg' AS "city_name"
UNION
SELECT 52.517037, 13.38886, 'Berlin'
UNION
SELECT 48.137108, 11.575382, 'München'
--*/
---------------------
-- If you want to use map-visualization properly, You have to use a VARCHAR-datatype or NULL for the first column.
---------------------
/*
SELECT 'Hamburg' AS "city_name", 53.543764 AS "latitude", 10.009913 AS "longitude"
UNION
SELECT 'Berlin', 52.517037, 13.38886
UNION
SELECT 'München', 48.137108, 11.575382
*/
---------------------
/*
SELECT 'Static VARCHAR column necessary for metabase to offer map visualization' as "metabase_workaround", 53.543764 AS "latitude", 10.009913 AS "longitude"
UNION
SELECT 'Static VARCHAR column necessary for metabase to offer map visualization' as "metabase_workaround", 52.517037, 13.38886
UNION
SELECT 'Static VARCHAR column necessary for metabase to offer map visualization' as "metabase_workaround", 8.137108, 11.575382
*/
---------------------
/*
SELECT null AS "null", 53.543764 AS "latitude", 10.009913 AS "longitude"
UNION
SELECT null, 52.517037, 13.38886
UNION
SELECT null, 48.137108, 11.575382
*/
```

![Map Visualization _ Numeric ](https://user-images.githubusercontent.com/68851604/103635568-0204ad80-4f49-11eb-99ea-24a6dfab40d1.png)

![Map Visualization _ String](https://user-images.githubusercontent.com/68851604/103635577-0630cb00-4f49-11eb-9d48-1ebef80847e0.png)

```
{
  "browser-info": {
    "language": "de",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-heroku-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_272-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-1081-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10 (Ubuntu 11.10-1.pgdg16.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.2",
      "date": "2020-11-16",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @ArnoldWertfaktor 
You can still select the map visualization even if it is grayed out.
Reproduce with Sample Dataset:
```
SELECT "PUBLIC"."PEOPLE"."LONGITUDE" AS "LONGITUDE", "PUBLIC"."PEOPLE"."LATITUDE" AS "LATITUDE", "PUBLIC"."PEOPLE"."CITY" AS "CITY"
FROM "PUBLIC"."PEOPLE"
LIMIT 10
```

**Comment by ArnoldWertfaktor** [comment]
Hi @flamber,

thats true, the function can be selected despite the graying out, but the map-visualization must then be selected again each time the question is opened. An automatic display of the map does not happen.

**Comment by flamber** [comment]
@ArnoldWertfaktor I cannot reproduce that. When I save the question, open a new tab and go to `/question/123`, then it shows the map initially - and still shows greyed out, when looking in the visualization sidebar, while it's selected.
Perhaps something else is going on.

**Comment by notrom** [comment]
This could be related to #12674 which is also impacting pin maps and is related to the order of columns, data types, and nulls. Maps seem quite picky about the data they consume.

**Comment by ArnoldWertfaktor** [comment]
@flamber: Thanks for testing, you are right, this first code works. 

I have extended the example with a variable (see screenshots). In this case, the version with the coordinates in the first column position now does not allow automatic display of the map and is also grayed out.

If you or someone else can reproduce this, then I would adjust the headline accordingly with a reference to a variable.

PS: In the screenshot you can see the variable setting.


```
SELECT "source"."latitude" , "source"."longitude", "source"."city_name", "source"."amount"
FROM (SELECT 53.543764 AS "latitude", 10.009913 AS "longitude", 'Hamburg' AS "city_name", 4 as "amount"
    UNION
    SELECT 52.517037, 13.38886, 'Berlin', 3
    UNION
    SELECT 48.137108, 11.575382, 'München', 2) "source"
WHERE "amount" > {{amount_value}}


---------------The code below works for the map visualization. The order of the columns is adjusted------------

*/
SELECT "source"."city_name", "source"."latitude" , "source"."longitude", "source"."amount"
FROM (SELECT 53.543764 AS "latitude", 10.009913 AS "longitude", 'Hamburg' AS "city_name", 4 as "amount"
    UNION
    SELECT 52.517037, 13.38886, 'Berlin', 3
    UNION
    SELECT 48.137108, 11.575382, 'München', 2) "source"
WHERE "amount" > {{amount_value}}
*/
```


![image](https://user-images.githubusercontent.com/68851604/103874154-1a073900-50d1-11eb-8870-29f868adec62.png)


![image](https://user-images.githubusercontent.com/68851604/103874050-fba13d80-50d0-11eb-8bb5-45bd28084694.png)

**Comment by flamber** [comment]
@ArnoldWertfaktor That's because of the default filter value causing the question to become "dirty", which means it might try to re-calculate the "auto-viz" (visualization selection) again based on the executed query. I have created a separate issue on that #14302

**Comment by ArnoldWertfaktor** [comment]
@flamber Ok, great, I'll close this issue as the underlying problem is now described in your new issue #14302

**Comment by flamber** [comment]
@ArnoldWertfaktor But this issue is still valid, since you shouldn't have to shuffle columns in a specific order to be able to select Map visualization.

**Comment by nemanjaglumac** [comment]
If you look closely enough, Map visualization **is** actually selected (on question load). Its parent div has an opacity of `0.25` so it looks greyed out.
![image](https://user-images.githubusercontent.com/31325167/103913663-17c0d100-5109-11eb-9d2c-f9f6195ac5f6.png)

Remove that opacity and this is what you'll see:
![image](https://user-images.githubusercontent.com/31325167/103913796-4343bb80-5109-11eb-8726-5dd70ec0932e.png)


Related code lives in: `frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.jsx:90`
```javascript
<Box
  p={1}
  w={1 / 3}
  className="text-centered"
  style={{ opacity: !isSensible ? 0.25 : 1 }}
>
```

`isSensible` prop is calculated on lines 56-61:
```javascript
isSensible={
  result &&
  result.data &&
  visualization.isSensible &&
  visualization.isSensible(result.data)
}
```
