### ISSUE TITLE
Can't see new schema in schema list

### ISSUE THREAD

**Issue by pjadavies** [metabase/metabase#14252]
**Describe the bug**
I have added a new schema (with tables) to my Redshift database. I see the schema (and tables) in the Redshift query console.

**Logs**
I'm not going to post logs with sensitive data here... but I took a look and couldn't find any reference in the logs to the new schema. Nor could I see any obvious errors...

**To Reproduce**
1. Add new schema in redshift
2. Click on Admin, go to Databases
3. Select database, click "Sync database schema"
4. Hard refresh schema list on Data model tab
5. New schema doesn't show (after waiting a while!)

**Expected behavior**
I should see the new schema, be able to choose which tables to show etc.

**Severity**
High! I want to build stuff in the new schema. It's useless without it :)

**Additional context**
I'm not an idiot but maybe I am. I looked through lots of google searches to see if others had experienced this. Couldn't find anything obvious...

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.186-146.268.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-11-16",
      "tag": "v1.37.2",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @pjadavies 
Try upgrading to 1.37.4 - there were several fixes to the sync process. And make sure that the credentials used in Metabase has select-privileges to the schema.
Without the logs, then it's very difficult to figure out what is going wrong and where in the process.
