### ISSUE TITLE
Add ability to change a dashboard filter's type

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14296]
Right now, if you choose the wrong type for a new dashboard filter, you're out of luck, and you just have to delete the filter and create a new one.

Instead, I should be able to change a filter's type from the settings sidebar.

The setting should let me pick from the normal list of dashboard filter types:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/2223916/103836164-1924c780-503d-11eb-817f-45f66a74d453.png">

If I click on the `Time` or `Location` options, which have sub-options, I should be able to go back in the popover:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/2223916/103836208-3c4f7700-503d-11eb-96bf-e0f433dae31a.png">

If I have a filter that's been wired up to cards, or that has filter linking set up (hierarchical filters), those settings should be reset _unless_ I'm changing it from one `Time` widget type to another `Time` widget type. The rationale is that it's very likely that the column connections won't make sense anymore if e.g. it used to be a State filter, and is then changed to a Country filter.

**Links**
- eng doc:…
- feature branch: …
- Issue links: …

**Implementation Plan**

**ETA**: MM/DD/YYYY
- [ ] step 1: …

**Needs to happen before merge**
- [ ] Design polish
- [ ] String translations
- [ ] Test on case X, Y, Z
- [ ] Write rough pass documents for handoff to customer success

**Comment by flamber** [comment]
Related to #5963

**Comment by uladzimirdev** [comment]
implemented https://github.com/metabase/metabase/issues/41037
