### ISSUE TITLE
The "Save question" modal should default to saving in the last collection previously saved in

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14298]
Currently, when saving a new question the `Which collection should this go in?` dropdown defaults to the root collection ("Our analytics") every single dang time. This is really annoying when trying to create a set of new saved questions based on the same data with only slightly different filter or grouping values — you have to navigate to the collection where you want to save it all over again.

It would be really nice if instead, the dropdown defaulted to the last collection you saved something in.

- Should this be constrained to a single session? 
- Should it be the last collection you saved _anything_ in (e.g. a dashboard)? I think so.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/2223916/103839561-8be57100-5044-11eb-862e-12bc58ebb59d.png">

**Comment by flamber** [comment]
Related to #4020

**Comment by noahzweben** [comment]
This would be **amazing**. Currently my single biggest frustration with MB!

**Comment by brunobergher** [comment]
Handled a while ago.
