### ISSUE TITLE
I shouldn't have to scroll to see the add-filter button in the notebook's add-filter popover

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14307]
When trying to filter on a field where you can either select values from a list or via a search box, the add-filter popover seems to have a max-height that causes the add-filter button to get pushed down, requiring you to have to scroll to add the filter, which is annoying.

Dropdown list example:

![have-to-scroll-again](https://user-images.githubusercontent.com/2223916/103926455-cb0bd480-50cd-11eb-8310-3d5f6e08ecea.gif)

Search box example:

![add-filter-have-to-scroll](https://user-images.githubusercontent.com/2223916/103926315-9a2b9f80-50cd-11eb-9e67-a25f728a09e8.gif)

**Comment by flamber** [comment]
I tried to fix that along with many other places in #12756, but every time I messed with it, then it caused a ripple of problems.
