### ISSUE TITLE
When modifying a saved question and then saving it as a new question, the placeholder title should be based on the original question's title

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14306]
In this example, I opened up a saved question titled, `Average of Rating by Category` and then added a filter. When I click save and then select "Save as a new question," the `Name` field should be in the format: `{Original question's title} - modified}, and the name field should be focused with the cursor positioned at the end, so that I can easily and quickly edit the name.

The rationale is that when I'm modifying an existing question, I'm very often doing something small like editing or adding a filter, or changing the granularity of the grouping dimension, and it's likely the name that I want to give the new question is just a permutation of the original question's name.

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/2223916/103923665-3784d480-50ca-11eb-90d9-9d83f0bed80a.png">

**Comment by flamber** [comment]
Related to #3921

**Comment by mazameli** [comment]
@flamber good catch! I'll copy this text and screenshot over to that issue and close this one.
