### ISSUE TITLE
Send User an email when they log in from a new device for the first time

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14313]
easy if we start tracking device info/IP address as part of the login history proposal

example:

![image](https://user-images.githubusercontent.com/1455846/103955121-7df22780-50fa-11eb-94b9-d5727f6e45c0.png)

By the way, that wasn’t me trying to log in! So because of this email I was able to go in and change my password. Without this email I would have had no idea.

**Comment by andreychirikba** [comment]
Can this be made optional? We log in users automatically through API, they don't manage their passwords themselves and don't expect any Metabase-generated authentication mails.

**Comment by camsaul** [comment]
Implemented by #15473

**Comment by camsaul** [comment]
@andreychirikba this is optional by setting `MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE` (see #15473)
