### ISSUE TITLE
Use deny list for known dumb passwords

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14316]
We should at least blacklist common dumb passwords like `123456` or `password1`

Protects against Password spraying: Testing a single weak password against a large number of different accounts. 
https://cheatsheetseries.owasp.org/cheatsheets/Credential_Stuffing_Prevention_Cheat_Sheet.html

OWASP suggests: [Pwned Passwords](https://haveibeenpwned.com/Passwords) is a service where passwords can be checked against previously breached passwords. You can host it yourself or use API.

**Comment by ariya** [comment]
For some additional reference, see also [Section 5.1.1.2 Memorized Secret Verifiers](https://pages.nist.gov/800-63-3/sp800-63b.html#memsecretver) as part of **NIST** Special Publication **800-63B** on Digital Identity Guidelines, _Authentication and Lifecycle Management_. e.g.:

> When processing requests to establish and change memorized secrets, verifiers SHALL compare the prospective secrets against a list that contains values known to be commonly-used, expected, or compromised. For example, the list MAY include, but is not limited to:
Passwords obtained from previous breach corpuses.
Dictionary words.
Repetitive or sequential characters (e.g. ‘aaaaaa’, ‘1234abcd’).
Context-specific words, such as the name of the service, the username, and derivatives thereof.
