### ISSUE TITLE
Allow dashboard users to determine themselves which column of a table they want to "group by"

### ISSUE THREAD

**Issue by fschmifi** [metabase/metabase#14324]
**Is your feature request related to a problem? Please describe.**
No. 

The problem is that stakeholders want to see certain metrics by various different dimensions. KPI1 by market, by product, by user_demographic etc. 

This currently requires us to create multiple graphs with different "group by" columns. This is cumbersome to maintain and heavy on our DWH. 

**Describe the solution you'd like**
Similar to field filters that allow the user to select what's in the "where clause", I'd like to have the capability to select the column from a table that I put e.g. in the select clause. 

select {{dimension_from_table}, count(1) from table group by 1 

**Describe alternatives you've considered**
Unpivot tables in ETL. 

**How important is this feature to you?**
Fairly important. 

**Additional context**

**Comment by flamber** [comment]
Closing in favor of #9875/#4639
