### ISSUE TITLE
Global search should be fuzzy

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14337]
I'm not sure exactly how far we should go with this, but currently our global search is pretty rigid.

One precise example is that you can't omit a word in a multi-word item you're searching for. So if I'm looking for "Anonymous Usage Statistics" but can't remember what it's called _exactly_ and you type "anonymous statistics", you won't get any results, which feels broken:

![fuzzy-search](https://user-images.githubusercontent.com/2223916/104076725-cd545880-51cb-11eb-854b-1e1311487b27.gif)

You also have to get the _order_ right — you won't get results if you type "statistics usage anonymous."

We also don't seem to do partial or similar string search, so in my example above, if i searched for "anon usage stats" I would also not get results.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by andreychirikba** [comment]
It would be really great for it work as autocomplete (suggest as you type).

**Comment by vkambhampati493** [comment]
I would like this to be extended to any search box, including the category filters. The lack of fuzzy search is frustrating.

**Comment by flamber** [comment]
@vkambhampati493 That's #11682 and #8219

**Comment by tsmacdonald** [comment]
Fixed by #14628
