### ISSUE TITLE
"Automatically run queries" setting should default to ON when adding a new database

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14334]
In master I'm seeing a regression where when adding a new database, this setting is incorrectly toggled off by default:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/2223916/104071486-21584080-51be-11eb-939f-ee7d854919d7.png">

In 0.37 it's correctly defaulted on:

<img width="679" alt="Screen Shot 2021-01-08 at 2 29 16 PM" src="https://user-images.githubusercontent.com/2223916/104071506-2ae1a880-51be-11eb-945f-a7272a1ef520.png">

This is a setting that we'd generally prefer to be on so that people have the intended experience with the simple querying mode.

**Comment by nemanjaglumac** [comment]
It might be related to the changes I made in https://github.com/metabase/metabase/pull/14121, but it still feels weird. There is a Cypress test that checks this and it's still green:
![image](https://user-images.githubusercontent.com/31325167/104073414-eda50700-520d-11eb-897d-4b4d14e40af0.png)

Could it be that this is related to backend? The change I proposed **should** simply reflect backend settings in UI.

**Comment by nemanjaglumac** [comment]
This feels weird. I added 3 new databases and then (upon adding) went inside that database to check its settings:

3 cases depending on whether I touched the `auto_run_queries` toggle initially

| Toggle when adding DB            | Visit `/admin/databases/:added_db_id` |
|----------------------------------|------------------------------------- |
| Leave it as it is (visually OFF)        |    Toggle was ON                                   | 
| Click it once (visually ON)             |    Toggle was ON                                    |  
| Click once (ON), then turn it OFF                                  |   Toggle was OFF                                    |

**Comment by dpsutton** [comment]
related: @nemanjaglumac you removed the initial value in https://github.com/metabase/metabase/commit/0a62bd47ebb30affa3d5f1458bd691688473d3c0

in response to https://github.com/metabase/metabase/issues/13187.

Taking it in but wonder if you remember @nemanjaglumac

**Comment by nemanjaglumac** [comment]
@dpsutton Yes, of course. I mentioned it in this comment https://github.com/metabase/metabase/issues/14334#issuecomment-757040439.

To give you more context: that hard-coded initial value was being used on **every** page load everywhere. In other words, it was masking the problem that we're trying to solve now in this issue. The consequence was that users could never tell if they had their `auto_run_query` settings on or off.

**Comment by dpsutton** [comment]
ah ok. that explains it better. i wasn't able to really parse what was going on. thanks. i think its a trivial fix now
