### ISSUE TITLE
Filter by -> Custom Expression Function Popup Broken and Noisy Error Message

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#14341]
**Describe the bug**
The function popup no longer appears by clicking on Filter by -> Custom Expression seems broken in x.37.5 and x.38

**To Reproduce**
1. Go to `Browse Data`
2. Click on `Sample Dataset`
3. Click on `Products`
4. Click on `Filter`
5. Click on `Custom Expression`
6. Enter contains(

**Expected behavior**
I tested on x.36.8.2, see screenshot below
<img width="381" alt="Screen Shot 2021-01-10 at 11 12 17 PM" src="https://user-images.githubusercontent.com/65313/104154876-c891cf00-539a-11eb-803a-5d68ee20de3b.png">
<img width="384" alt="Screen Shot 2021-01-10 at 11 12 33 PM" src="https://user-images.githubusercontent.com/65313/104154895-d47d9100-539a-11eb-9c41-1a5bcfa0c581.png">

**What Actually Happens**
Tested on x.37.5 and master:
<img width="368" alt="Screen Shot 2021-01-10 at 11 14 37 PM" src="https://user-images.githubusercontent.com/65313/104154955-f70faa00-539a-11eb-8c44-2ab185639e04.png">
<img width="371" alt="Screen Shot 2021-01-10 at 11 14 52 PM" src="https://user-images.githubusercontent.com/65313/104154961-fb3bc780-539a-11eb-8ad4-7c9f59c17691.png">

**Information about your Metabase Installation:**

```{
  "browser-info": {
    "language": "en-us",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+9-202002041938",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+9-202002041938",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-05",
      "tag": "v0.37.5",
      "branch": "release-x.37.x",
      "hash": "be537ee"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
It doesn't match the following instructions on Metabase Learn, so it's confusing: https://www.metabase.com/learn/basics/questions/searching-tables.html

**Comment by flamber** [comment]
Likely caused by #13724 - related to #12268

**Comment by nemanjaglumac** [comment]
One more thing:

Note how the whole sidebar is cut-off on the right side. I can see horizontal scroll in Brave browser.
![image](https://user-images.githubusercontent.com/31325167/104209218-b747d180-5431-11eb-8809-71f1c23b3f2f.png)

Should I file a new issue for that specifically?

**Comment by flamber** [comment]
@nemanjaglumac That has always been like that because of min-width of the popover, which only happens in Simple GUI.

**Comment by ariya** [comment]
(Copying my comment from #14345):

This is definitely a regression in 0.37 due to PR #13724. This becomes a problem in master as well since that branch is merged to master.

To demonstrate this, first checkout commit c235432b (this is in `release-x.37.x` branch, **before** PR 13724 is merged):

![image](https://user-images.githubusercontent.com/7288/104265217-f5e58800-5441-11eb-924e-0e6126f7f3be.png)

then do the same for commit b9cebc18 (this is in `release-x.37.x` branch, **after** PR 13724 is merged):

![image](https://user-images.githubusercontent.com/7288/104265051-9be4c280-5441-11eb-9952-438fd1783d84.png)

**Next step**: figure out why the regression happened.

**Comment by rlotun** [comment]
Closed by https://github.com/metabase/metabase/pull/14452
