### ISSUE TITLE
Question links from public dashboards do not work

### ISSUE THREAD

**Issue by emurphy** [metabase/metabase#14358]
**Describe the bug**
Question names on public dashboards render as links on hover. But clicking on the question name does nothing. Previously clicking on the question name opened the public question for viewing and downloading.

The problem may be related to an upgrade to v0.37.3, followed by a downgrade to v0.35.5 (upon encountering issues with public dashboards related to https://github.com/metabase/metabase/issues/13868). But even when creating a new public dashboard strictly on v0.35.5, the question links do not work. We also tried upgrading to v0.37.5, but the links still do not work.

The problem affects all of our public dashboards.

**Logs**
Server logs look normal. Javascript console logs also look normal, showing the following error that also shows on the non-public version of the dashboard (without any noticeable effect on functionality):

vendor.bundle.js?47b35b30a25dd981f60f:1 Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (https://metabase.deliverr.com/app/dist/vendor.bundle.js?47b35b30a25dd981f60f:1:317977)
    at Object.e.exports [as findDOMNode] (https://metabase.deliverr.com/app/dist/vendor.bundle.js?47b35b30a25dd981f60f:1:2527192)
    at d.value (https://metabase.deliverr.com/app/dist/app-public.bundle.js?47b35b30a25dd981f60f:5:936551)
    at n._updateSize (https://metabase.deliverr.com/app/dist/app-public.bundle.js?47b35b30a25dd981f60f:5:935978)

**To Reproduce**
1. Go to a public dashboard that includes public questions.
2. Hover over the name of a public question in the card's upper left corner. The name shows as blue, with the finger icon indicating that it is a clickable link.
3. Click on the link.
4. Nothing happens.

**Expected behavior**
When clicking on a public question's name from a public dashboard, it navigates to the public question.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.203-156.332.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "redshift",
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.19"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-06-08",
      "tag": "v0.36.0-snapshot",
      "branch": "jetty-request-header-size",
      "hash": "27c79d2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**

The bug is a major inconvenience to around 30 of our.partners, as they need to download information from the dashboard in order to conduct hundreds of transactions per day (per partner). 

**Additional context**

**Comment by flamber** [comment]
Hi @emurphy 
As far as I know, it has never been possible to go to a Public question by clicking the card title in Public dashboard.
Could it be that you have made a change to your custom build to allow that? Also, there were no 0.35.5 - last was 0.35.4
If you revert to your backup instead of downgrading, then everything should have returned to how it used to work.
You might interested in #6687 - if you only want to enable download on dashboards, then it's available [embedded dashboards](https://www.metabase.com/docs/latest/administration-guide/13-embedding.html).
I have just created a new install on 0.35.4 and cannot reproduce.
