### ISSUE TITLE
metabase support maxcomputer

### ISSUE THREAD

**Issue by yinlingshishangS** [metabase/metabase#14357]
metabase support maxcomputer 。
Metabase has been successfully used, but maxcomputer is not supported, which is very difficult for Chinese developers

**Comment by flamber** [comment]
Hi @yinlingshishangS It would be helpful with a link or more context on what "maxcomputer" is.

**Comment by yinlingshishangS** [comment]
https://help.aliyun.com/product/27797.html
This is the number one cloud service provider in China and the third in the world. Maxcomputer is a data warehouse service developed by China's Aliyun. He is more in line with the usage scenarios of Chinese companies.

**Comment by camsaul** [comment]
Metabase can be deployed anywhere you can deploy a Docker image!

**Comment by yinlingshishangS** [comment]
If possible, I look forward to supporting it in subsequent versions, which will also be beneficial to the promotion of BI platforms in China

**Comment by yinlingshishangS** [comment]
> Metabase can be deployed anywhere you can deploy a Docker image!
It is similar to Amazon and Google’s big data warehouse services, through jdbc...

**Comment by yinlingshishangS** [comment]
> Hi @yinlingshishangS It would be helpful with a link or more context on what "maxcomputer" is.

Looking forward to your reply

**Comment by camsaul** [comment]
Hi @yinlingshishangS , if MaxCompute works like AWS or GCP and lets you spin up Docker images and databases and gives you JDBC connection info then you can would be able to deploy Metabase to it.

**Comment by camsaul** [comment]
Sounds like MaxCompute is sort of like BigQuery or Redshift

**Comment by paoliniluis** [comment]
Hi @yinlingshishangS, we have currently a feature request for MaxCompute in [this issue](https://github.com/metabase/metabase/issues/12669) so in order to centralize the upvotes (which is one of the factors we use for prioritizing the backlog) I would suggest you to upvote the first comment on that other issue. I will proceed to close this one so we don't have duplicates. Have a great dat!
