### ISSUE TITLE
Pivot tables: numbers in cells should be right-aligned, not left:

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14351]
There is a strong expectation that numbers in spreadsheets should be right-aligned in cells. Right now, they're not:

![](https://user-images.githubusercontent.com/2223916/102946727-57838980-4476-11eb-89ee-93ee15bc43ee.png)

**Comment by rlotun** [comment]
I believe this is fixed in https://github.com/metabase/metabase/commit/fa75632414d526ff17645512621986c9913576d5

**Comment by notrom** [comment]
@rlotun @mazameli I'm personally not hugely bothered by this but in rc3 the right alignment is close but slightly different when there are multiple measures. 
Red lines added by me, note that the % sign appears makes no difference
![image](https://user-images.githubusercontent.com/4504437/106086510-28ec8300-6187-11eb-910c-9ef5adbfcd12.png)

The last column is always fully right aligned as I would expect it, but the prior ones are all a little off that vertical red line.

Loving the pivot tables overall, looking forward to full release so I can share them with my organisation.

**Comment by flamber** [comment]
@notrom Yeah, it seems like it's more clearly, when there's more than two dimensions. This is master `da8fd26`:
![image](https://user-images.githubusercontent.com/1447303/106124482-6b986600-615b-11eb-884c-1bb89ae608c4.png)
Reopening, but it's not a P1 and not sure if it is blocking 38

**Comment by mazameli** [comment]
Ugh, yeah, this doesn't look good:

![image](https://user-images.githubusercontent.com/2223916/106207383-81ffeb00-6176-11eb-9052-fc94ab9dadcb.png)

**Comment by mazameli** [comment]
I'm closing this again and have opened up https://github.com/metabase/metabase/issues/14574 to track this alignment bug.
