### ISSUE TITLE
SQLite Driver

### ISSUE THREAD

**Issue by djbusby** [metabase/metabase#1435]
Sometimes providers of data just send the dumps as sqlite format.  I don't like the step of importing that into some format that is currently supported by metabase.  I wish that this database interface was supported.

**Comment by spectr** [comment]
+1

**Comment by djbusby** [comment]
I'm offering $200 to aid in the completion of this issue.

**Comment by camsaul** [comment]
Implemented in #1497, will be available in our next release.

**Comment by djbusby** [comment]
Awesome! Thanks.  I've pulled the latest master and built it; I see that sqlite is being registered in the build side but when I run the output jar, only H2 is registered and selectable in the attach database list.

**Comment by salsakran** [comment]
did you re-generate the front end assets? I usually do a 
`npm install && ./node_modules/webpack/bin/webpack.js  -w`

after pulling, but there's probably a less paranoid way to rebuilt. @tlrobinson ?

**Comment by tlrobinson** [comment]
`npm install && npm run build` is the "blessed" method, but that works too :)

**Comment by djbusby** [comment]
I did those; manually - but they are also in the `bin/build` script which I've run; I even re-cloned and tried to no avail.

During build I see this:

    Compiling metabase.driver.sqlite
    2015-11-20 18:04:19,639 [DEBUG] metabase.driver :: Registered driver :sqlite.

But when running the freshly built jar I only see this:

    2015-11-20 18:17:18,778 [DEBUG] metabase.driver :: Loading driver ':h2'...
    2015-11-20 18:17:18,822 [DEBUG] metabase.driver :: Registered driver :h2.

**Comment by djbusby** [comment]
Also, I've found that the call to `/api/session/properties` - the return JSON only has h2 in the engines, no other engines are listed

**Comment by camsaul** [comment]
Oops this might be a chicken and egg thing where the drivers don't get loaded unless you have a database that uses them but you can't add a new database from a driver that's not loaded. 😭 I will fix this later today

**Comment by camsaul** [comment]
@djbusby pull the latest and try it again I fixed the issue with the SQLite showing up

**Comment by djbusby** [comment]
Very awesome, where do I send the money?

**Comment by agilliland** [comment]
We appreciate the offer @djbusby but we'd feel bad about taking your money.  Instead we'd encourage a charitable donation to the organization of your choice instead :+1: 

We are fans of the FSF, Apache SF, Linux Foundation, and many more.  And of course you could just donate to your local SPCA :joy_cat:

**Comment by salsakran** [comment]
Hey @djbusby + @spectr
Just a heads up that this is live in our newest version (0.13). Would really appreciate you giving it a whirl and seeing if it works with your database.

**Comment by djbusby** [comment]
@salsakran yea boss; I tried the bits right after @camsaul made them then got a second related fix; it works great here.
