### ISSUE TITLE
Pass info about current version on request to fetch version-info; record this info

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14368]
To make it easy to decide which versions to support/issue hotfixes for going forward. Right now we don't have a great sense of which people are actively deploying which EE versions, for example.

Since active instances periodically fetch `version-info.json` to check for updates maybe we can pass in version info as a query param, e.g.

```
GET http://static.metabase.com/version-info.json?current-version=0.37.5
```

Added bonus: we could make that request smart and return EE version info vs OSS version info at some point in the future (right now EE doesn't do the whole version information/updates are available thing). Since we're actually using the parameter for a legitimate purpose I think we can pass it in even if people disabled anonymous stats.

I think we'd want to set up an AWS lambda to handle this stuff -- or does S3 include query params in the download logs? I think CloudFront lets you specify lambdas for stuff, so this might be a good time to get CloudFront set up for static.metabase.com, since it currently doesn't support HTTPS since we're hitting the S3 bucket directly. (Not super critical because the worst you could do by spoofing this request is mislead people about whether a new version is available or not -- it doesn't include links)

**Comment by salsakran** [comment]
I think we can collect urls from the s3 logs and just parse those directly without introducing lambdas. Let me confirm

**Comment by camsaul** [comment]
No longer relevant since we're getting these stats with Snowplow or something else now
