### ISSUE TITLE
Trying to visualize a SQL query's results as a pivot table locks up the UI

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14363]
![sql-pivot](https://user-images.githubusercontent.com/2223916/104351081-c4a89e80-54b9-11eb-82bd-30eeb83dbe24.gif)

**To reproduce:**
- Create a SQL query and run it. Here's an [example SQL query](http://localhost:3000/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgY291bnQoKiksIHN0YXRlLCBzb3VyY2UgZnJvbSBwZW9wbGUgZ3JvdXAgYnkgc3RhdGUsIHNvdXJjZSIsInRlbXBsYXRlLXRhZ3MiOnt9fSwiZGF0YWJhc2UiOjF9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=)
- Try selecting the Pivot Table visualization
- It tries to re-run the query, which never resolves
- Try clicking around in the UI to pick another visualization and see that nothing happens
- Not shown in the gif, but clicking back in the browser does seem to unlock you

The only useful-looking JS console error I'm seeing is `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 's.data.cols')` when clicking on the Pivot Table button.

The query error on the page says "question.query().breakouts is not a function. (In 'question.query().breakouts()', 'question.query().breakouts' is undefined)"

**Expected behavior**
When selecting the pivot table visualization option in this scenario, I'd expect it to just display the warning message shown here _without_ trying to re-run the query, so that I could pick a different visualization, etc.:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/2223916/104351013-ae9ade00-54b9-11eb-90d4-5304cfac6d39.png">

**Comment by paulrosenzweig** [comment]
Whoops! This is a quick fix. I'll add a test too since I think I handled this earlier but it must have broke as that redux code evolved.
