### ISSUE TITLE
I need a stopwatch time format i.e. 00:01:10 for 70 seconds

### ISSUE THREAD

**Issue by wuarmin** [metabase/metabase#14361]
Hello,
my PostgreSql-Table holds a **time** column with data like that:
00:02:07
00:00:06

I was not able to find a way to visualize this times correctly in Metabase. It looks like that:
![image](https://user-images.githubusercontent.com/9987680/104329070-cb9cd480-54ec-11eb-83d9-5c5d5b0c6ea7.png)

Is it possible to change this behavior?
The screenshot-times should be following:

00:00:03
00:00:05
00:00:04

Thank you

**Comment by flamber** [comment]
Hi @wuarmin 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by wuarmin** [comment]
Hi @flamber,
Alright! Thx
