### ISSUE TITLE
Card PUT/POST API endpoints should not be "streaming"

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14385]
They're streaming because the endpoints will their run query asynchronously the populate the `result_metadata` column if needed if the value of `dataset_query` is set/changes. The endpoint thread is parked (to avoid tying up a precious Jetty thread) until the query gets ran (if needed) at which point the actual result gets returned.

Our code for determining result metadata is a little more sophisticated now and in most cases we can do it without having to run a query at all -- the exception is native queries which we don't have a way to determine type information for. The client is supposed to pass this info in when creating/updating a Card anyway, so this mechanism is a fallback...

I think we should change them so the endpoints return right away and run the result metadata queries on the off chance that we actually need them ~~in a background threadpool~~.

**Comment by bshepherdson** [comment]
This was fixed by #23672 but never marked as such.
