### ISSUE TITLE
Simplify QP cache middleware impl

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14386]
The QP cache middleware is too hairy right now. I wrote the original code and I apologize for my crimes against humanity.

Right now we:

1. Create a `core.async` channel that you send Clojure objects to
2. Create a `(DataOutputStream. (GZIPOutputStream. (BufferedOutputStream. (max-bytes-output-stream (ByteArrayOutputStream.)))))`
2. Create a  `core.async` loop that take values from that channel and writes them to the output stream (on yet another background thread from the `core.async.core/thread` thread pool)
3. Create another `core.async` promise channel that you can use to fetch the actual byte array by calling `(.toByteArray)` on the OS to get the serialized results
4. write the byte array to the cache (asynchronously, of course 😒)
5. close all the core.async channels

There is way too much threading happening here. The only possible benefit to this madness is that caching happens on a separate thread from the one getting the main QP results, which means caching has almost no perceivable overhead, but makes caching stupid-hard to test.

Streaming stuff to `core.async` channels that in turn stream them to `OutputStream`s is ridiculous. Why not just stream them to the `OutputStream` directly and forget about `core.async` entirely? I doubt the performance impact would be noticeable, and it only affects uncached runs anyway. Benefit: code is 5x easier to follow and tests are easier to write

**Comment by camsaul** [comment]
This would actually improve our memory profile because:

1. Objects wouldn't be sitting around in memory waiting for the `core.async` loop to serialize them. 
2. Since this stuff happens in the background, if there is a lot of contention to get access to the application DB we could potentially have hundreds of query results waiting to get serialized... if we did it synchronously we could only have results waiting for queries that were currently running.

**Comment by camsaul** [comment]
A note on why we hold the entire byte array in memory rather than serializing directly to the DB: that would require us to hold a connection open to the application DB/other cache backend for the duration of running the query/streaming the results. Since cache entries have a max size defaulting to 1MB we're only talking about potentially having a max of 15MB of worth of cache entries in memory waiting to get written to the app DB/other cache backend. So not a big deal if you ask me. It's not worth spinning up a separate connection pool for writing to the cache IMO. We do however stream directly from the cache for cached results.

**Comment by camsaul** [comment]
I already have the code that does this mostly written

**Comment by sbelak** [comment]
This makes a lot of sense. It might also fix or at least alleviate #11392

**Comment by camsaul** [comment]
Implemented by #20310
