### ISSUE TITLE
Translate /admin/store

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#14396]
In the enterprise edition, `/admin/store` is mostly missing translations.

![image](https://user-images.githubusercontent.com/784417/104632501-64edf700-5663-11eb-8810-b30fdbc45ae6.png)

**Comment by flamber** [comment]
This was translated 3 months ago, shortly after repo unification, but it seems like certain parts of EE frontend doesn't get converted correctly. Another example:
![image](https://user-images.githubusercontent.com/1447303/104644030-8b388480-56ad-11eb-8be5-e35216e31e56.png)
https://github.com/metabase/metabase/blob/c19daee3b476f5c3d3c29171d9035b81cff7ce8a/locales/es.po#L15655-L15657
