### ISSUE TITLE
Translate "your personal collection" in collections view

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#14398]
This is on `/collection/root`

It *is* translated when saving a card to it, just not when browsing.

![image](https://user-images.githubusercontent.com/784417/104634209-f199b480-5665-11eb-8d99-de42721ebd49.png)

**Comment by flamber** [comment]
I'm seeing correct translation on stats (hash `6cabb3d`) - it was translated a month ago, and imported into Metabase 17 days ago.
![image](https://user-images.githubusercontent.com/1447303/104641443-0f890880-56aa-11eb-944b-56298f6bd0e1.png)
