### ISSUE TITLE
Migration 18 creates VARCHAR column with no length bound

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1439]
[This line which was merged earlier this week](https://github.com/metabase/metabase/blob/master/resources/migrations/018_add_data_migrations_table.yaml#L11) is :crying_cat_face:. `VARCHAR` without a length limit is ok for PG and H2 but not for MySQL. 

Not sure if this breaks migrations on MySQL. Liquibase might be smart enough to give this a default length limit. But still it's probably better safe than sorry :scream_cat: 

We'll want to specify the old migration hash as "valid" [see this page](http://www.liquibase.org/documentation/changeset.html) or Liquibase will complain about the migration hash changing for people that already ran the old version.

On another note, we should *definitely* be testing on CI with MySQL as a backing DB. I will open a separate issue for that

**Comment by agilliland** [comment]
Fixed by #1434
