### ISSUE TITLE
Dashboard subscription emails shouldn't say "Pulse:" in subject line

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14395]
The title in the _body_ of the email looks right, but the subject of the emails still incorrectly say "Pulse."

![image](https://user-images.githubusercontent.com/2223916/104631795-99f14e00-5651-11eb-8003-43de9aa2a80d.png)

**Comment by tsmacdonald** [comment]
Oof, regression of https://github.com/metabase/metabase/pull/14260
