### ISSUE TITLE
Timestamp is always present in dates when exporting to Excel in the embedded application.

### ISSUE THREAD

**Issue by mariyathomasp** [metabase/metabase#14393]
**Describe the bug**
Dates are displayed without timestamp in visualization for native queries, but when exported they include timestamp after I embed Metabase to our application.

**To Reproduce**
1. Create native query with a date and use convert function to have only dd-mm-yyyy
2. Save question (it worked fine if you download at this point) - saw that u have resolved the known issue #12964
3. Add Question in Dashboard
4. Embed the Dashboard to your application website
5. Download the result as Excel from website
6. Open Excel  and see that timestamp is still present

**Expected behavior**
I expect the Excel export to look just like what I am seeing in the table visualization, without the timestamp.

**Screenshots**
![image](https://user-images.githubusercontent.com/77450749/104612639-b6f44400-5686-11eb-954d-4498b2fc1439.png)

**Information about your Metabase Installation:**
```json
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.15.0-1103-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-05",
      "tag": "v0.37.5",
      "branch": "release-x.37.x",
      "hash": "be537ee"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Severity**
Our customers need this data for their analysis. So its really important to fix this.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by SetSails** [comment]
it should be possible to configure a date and date/time format for csv exports

**Comment by flamber** [comment]
@SetSails That's what issue #10879 is for - upvote by clicking :+1: on the first post

**Comment by atanas0** [comment]
In our case the dates values exported in Excel are wrong e.g. 1/25/2021 stored as 1/24/2021 22:00:00.
Confirmed by users across different timezones, file opened with Excel on Mac, Excel on Windows.

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.158-129.185.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-20",
      "tag": "v0.37.7",
      "branch": "release-x.37.x",
      "hash": "2b034aa"
    },
    "settings": {
      "report-timezone": "Europe/Athens"
    }
  }
}

**Comment by flamber** [comment]
@atanas0 That sounds like a different issue, though related. Can you provide steps-to-reproduce?

**Comment by mariyathomasp** [comment]
> it should be possible to configure a date and date/time format for csv exports

can you specify how I can do that?

**Comment by atanas0** [comment]
> @atanas0 That sounds like a different issue, though related. Can you provide steps-to-reproduce?

I opened a new issue: #14507

**Comment by SetSails** [comment]
> > it should be possible to configure a date and date/time format for csv exports
> 
> can you specify how I can do that?

Sorry I meant to express a request for a feature allowing us to specify the format. I have the same issue with csv exports at the moment.

**Comment by mariyathomasp** [comment]
When can I expect a fix for this?

**Comment by jlisyc** [comment]
Metabase 0.36.12
Date format downloaded excel does not respect the date format when chose to show minutes.
For example: for 24 September 2020, with format configuration is D/M/YYYY
, in the downloaded excel shows:
 for a date "with minutes" it change to M/D/YYYY ![image](https://user-images.githubusercontent.com/33416503/114665114-ea358600-9cfc-11eb-80b4-c1329a1a7bd2.png)

, but for date (just day) is ok ![image](https://user-images.githubusercontent.com/33416503/114665014-c83c0380-9cfc-11eb-8879-4e509924c7e5.png)

**Comment by mariyathomasp** [comment]
When can we expect this bug to be resolved?

**Comment by ghiculescu** [comment]
I know this is not a very helpful thing to say, but... I think https://github.com/metabase/metabase/pull/17321 will fix this issue, but I don't feel confident enough with clojure to know how to write a test for it.

**Comment by tprestonwills** [comment]
> Hello, sorry to come back on such an ancient issue, but I've encountered the described issue recently. We have embedded Metabase in our product, and our native exports have fine date formats (YYYY-MM-DD), however the embedded extracts output "YYYY-MM-DDT00:00:00Z" formatted dates. Since I couldn't find a more recent issue on the topic that this one, I thought I'd ask you guys 👋

I am encountering the same issue in version 0.46.2 (currently the latest). The repro steps are exactly the same as described in the bug. Any ideas?

![image](https://user-images.githubusercontent.com/19897230/236647528-8de6a07c-9084-45eb-bc55-8e581a362951.png)



**Diagnostic Info**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.15.0-71-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.0 (Debian 13.0-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-28",
      "tag": "v0.46.2",
      "branch": "release-x.46.x",
      "hash": "8967c94"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
@tprestonwills @VictorWhiteBird full app embed or simple embed ?

**Comment by tprestonwills** [comment]
> @tprestonwills @VictorWhiteBird full app embed or simple embed ?

We are using signed embedding.

**Comment by VictorWhiteBird** [comment]
> @tprestonwills @VictorWhiteBird full app embed or simple embed ?

We're using the signed embedding as well.

**Comment by VictorWhiteBird** [comment]
@paoliniluis Any update on a possible fix for this feature ?

**Comment by paoliniluis** [comment]
@VictorWhiteBird this should be fixed by now; please report if this is not the case with reproducible steps

**Comment by VictorWhiteBird** [comment]
I just tried on our signed embedded app, and I still have data with the following format : 
`2023-02-01T00:00:00Z` 
In Metabase, the data, from the same line is exported as follows : `2023-02-01`

**Comment by tprestonwills** [comment]
@paoliniluis Was it fixed in the 0.46.4 patch release?

**Comment by paoliniluis** [comment]
@tprestonwills no, 2021. If this still happens please post reproduction steps with the sample dataset in the latest version so I can reopen the issue. Or post the repro steps with another data source but with ddl

**Comment by Tony-metabase** [comment]
To Reproduce
Steps to reproduce the behavior:

1) Go to New -> Question -> Sample Database -> Orders -> Save -> Add to Dashboard
2) Enable Sharing -> Go to Dashboard -> Sharing -> Embed in your Application -> Publish
3) Either Download directly from preview or get the Embed URL and Download as XLSX and compare the date:

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/f176e398-73d8-4394-8568-efa83c8c30d0">

I am able to replicate in both 45 and 46
