### ISSUE TITLE
You can draw on funnel charts in Safari 14

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14404]
This is like a p4, but it exists, so 🤷🏼‍♂️. This is on master in Safari 14 on Big Sur 11.2 Beta.

![funnel-drawing](https://user-images.githubusercontent.com/2223916/104640665-a2e81c80-565d-11eb-8464-aecab549a32d.gif)

**Comment by flamber** [comment]
Dupe of #11005, but I like this better

**Comment by mazameli** [comment]
Meh, I'll close mine. :)
