### ISSUE TITLE
We should make the 0 line on the x-axis stand out more when there are negative values present in a chart

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14402]
In a chart like this one, it's hard to see where the values are dipping below 0. I'd expect for the horizontal axis line for 0 to be e.g. a darker color to make it clearer in this scenario.

Specifically for waterfalls, I got momentarily confused which "direction" the total bar was going; i.e., it's pointing "down" towards `-786,844`.

![image](https://user-images.githubusercontent.com/2223916/104636325-0a02d280-5658-11eb-8c86-074474ec55ae.png)

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/41395
![Image](https://github.com/user-attachments/assets/9f7a0497-889d-4649-afd6-5de53868caa5)
