### ISSUE TITLE
Pivot tables can't handle pivoting when there's only a single grouping field

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14403]
As shown in this gif, take [this query](http://localhost:3000/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MiwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJicmVha291dCI6W1siZmstPiIsWyJmaWVsZC1pZCIsMTNdLFsiZmllbGQtaWQiLDRdXV19LCJkYXRhYmFzZSI6MX0sImRpc3BsYXkiOiJwaXZvdCIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJwaXZvdF90YWJsZS5jb2x1bW5fc3BsaXQiOnsicm93cyI6W1siZmstPiIsWyJmaWVsZC1pZCIsMTNdLFsiZmllbGQtaWQiLDRdXV0sImNvbHVtbnMiOltdLCJ2YWx1ZXMiOltbImFnZ3JlZ2F0aW9uIiwwXV19fX0=), visualize it as a pivot table, then trying moving the grouping field from the "rows" section to the "columns" section, and all hell breaks loose. It first will display a jumbled table, but trying to refresh the query locks up the UI:

![single-pivot-column](https://user-images.githubusercontent.com/2223916/104639186-f6f20180-565b-11eb-8707-baa36c965824.gif)

**Comment by paulrosenzweig** [comment]
This will be fixed with #14370. That's waiting on #14389, but will be merged soon.
