### ISSUE TITLE
Pivot table subtotal off by one

### ISSUE THREAD

**Issue by jeff-bruemmer** [metabase/metabase#14400]
**Describe the bug**
Subtotal in pivot table (sometimes) off by one.

**To Reproduce**

Note, the following is copied from “How to Test this Feature” on the implementation issue:

1. Ask a new simple question about Orders from the Sample Dataset.
2. Summarize count and sum of Subtotal, and group by Order.Created_At:Year, User.State, and User.Source.
3. Change visualization to Pivot Table.
4. You should see a sidebar with sections to assign fields to generating table rows, columns, and values. User.State and Order.Created_At should be in the rows; User.Source should be in the columns; and the Count and Sum should be in the values section.
5. In the table itself, you should see columns for User.State and Created_At, with the years repeated for each state. In the settings sidebar, drag the Created_At item up above User.State to switch their grouping order. The table should reload, now showing you the states repeated for each year.

AK sum of subtotals is off by 1 cent. 
- Want: 1,093.72. 
- Got: 1,093.71. 

See screenshot. The next line, however, sums correctly.

**Expected behavior**
AK sum of subtotals should be 1,093.72.

**Screenshots**
![image](https://user-images.githubusercontent.com/17343328/104633702-65cb5c80-5654-11eb-82a5-0f8a43db0948.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1",
    "os.name": "Linux",
    "os.version": "4.19.121-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-14",
      "tag": "v0.39.0-SNAPSHOT",
      "branch": "master",
      "hash": "b2b344a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Unclear. Could be an expected rounding error, but want to flag this as an issue in case it portends a larger underlying problem.

**Comment by flamber** [comment]
This is correct - just like with Excel, you might only show 2 decimals as formatting, but calculations are done based on full number.
Subtotals and Totals have a lot of decimals. The correct value would be `1,093.7063619692906`

**Comment by mazameli** [comment]
Yeah, once we implement formatting settings for the columns in the viz, you should be able to specify the number of decimal places you want for your values.
