### ISSUE TITLE
not loading tables from database

### ISSUE THREAD

**Issue by arielesp** [metabase/metabase#14414]
**Describe the bug**
Metabase was working fine ... but, now, the tables from one database dont want load in system. I can run queries normally.
I reacreate another database with same login and passwd and tables loaded... just in "old" register, I cant
I am using latest docker image, with database h2 mounted in host
I already tried sync database schema.

**Logs**
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util STARTING: Sync metadata for mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util STARTING: passo 'sync-timezone' para mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util FINISHED: passo 'sync-timezone' para mysql Banco de dados 3 'BD Evipes - OLD' (30.6 ms)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util STARTING: passo 'sync-tables' para mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util FINISHED: passo 'sync-tables' para mysql Banco de dados 3 'BD Evipes - OLD' (104.7 ms)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util STARTING: passo 'sync-fields' para mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util FINISHED: passo 'sync-fields' para mysql Banco de dados 3 'BD Evipes - OLD' (1.3 ms)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util STARTING: passo 'sync-fks' para mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util FINISHED: passo 'sync-fks' para mysql Banco de dados 3 'BD Evipes - OLD' (1.1 ms)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util STARTING: passo 'sync-metabase-metadata' para mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util FINISHED: passo 'sync-metabase-metadata' para mysql Banco de dados 3 'BD Evipes - OLD' (92.8 ms)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util FINISHED: Sync metadata for mysql Banco de dados 3 'BD Evipes - OLD' (279.2 ms)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util STARTING: Analyze data for mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:48-03:00 INFO metabase.sync.util STARTING: passo 'fingerprint-fields' para mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:49-03:00 INFO metabase.sync.util FINISHED: passo 'fingerprint-fields' para mysql Banco de dados 3 'BD Evipes - OLD' (1.7 ms)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:49-03:00 INFO metabase.sync.util STARTING: passo 'classify-fields' para mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:49-03:00 INFO metabase.sync.util FINISHED: passo 'classify-fields' para mysql Banco de dados 3 'BD Evipes - OLD' (795.1 µs)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:49-03:00 INFO metabase.sync.util STARTING: passo 'classify-tables' para mysql Banco de dados 3 'BD Evipes - OLD'
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:49-03:00 INFO metabase.sync.util FINISHED: passo 'classify-tables' para mysql Banco de dados 3 'BD Evipes - OLD' (1.4 ms)
[e79f5b82-ade1-43de-a293-81eb12010bd5] 2021-01-14T21:15:49-03:00 INFO metabase.sync.util FINISHED: Analyze data for mysql Banco de dados 3 'BD Evipes - OLD' (11.9 ms)

**To Reproduce**
Ask a question
Simple question
select database
no tables in database for old database register
--
in new database register ( the same ), tables running.

**Severity**
The bigger problem is about all queriers already created, How to move to this anoter database, because if I excluded the old ... I will lose all data created in metabase.

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "3.10.0-1127.19.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-13",
      "tag": "v0.37.6",
      "branch": "release-x.37.x",
      "hash": "344e5e0"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

How to fix it ? thanks

**Comment by flamber** [comment]
Hi @arielesp 

You would need to enable some debug logging, so we can see more details during the sync.
Try adding this environmental variable to the docker run ... command:
...` -e JAVA_OPTS="-Dlog4j.configurationFile=https://log4j.us/v2/templates/metabase?trace=metabase.sync" `...

Which version of MySQL?
And is it regular simple tables, or are they advanced or Views?

Off-topic, I would recommend migrating away from H2 if you are using Metabase in production:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
