### ISSUE TITLE
Remove "Column title" from admin settings

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#14426]
Some wires got crossed here. A visualization-specific setting is in the admin panel:

<img width="1085" src="https://user-images.githubusercontent.com/691495/104763579-207e5c00-5734-11eb-9882-359346c91073.png">

**Comment by flamber** [comment]
It's showing all options - not just "Column title" - while it actually fixes some issue in the current state, it's a bit too much.

master:
![image](https://user-images.githubusercontent.com/1447303/104764051-204b8400-5767-11eb-96f6-6dc0b765ab8e.png)

Should look like this - 0.37.6:
![image](https://user-images.githubusercontent.com/1447303/104764002-09a52d00-5767-11eb-848a-082b5e99c4b5.png)
