### ISSUE TITLE
Embedding Python Example Code is Out of Date

### ISSUE THREAD

**Issue by ellie-metabase** [metabase/metabase#14423]
**Describe the bug**
The python code metabase provides in settings for embedding a dashboard is out of date and does not work on Python 3.7

**To Reproduce**
1. Open Enterprise instance of Metabase
2. Settings > Admin > "Embedding in Other Applications" > Enable > Settings > Exit Admin
3. Navigate to any dashboard in the instance
4. In Dashboard view, click "Sharing & Embedding"  > "Embed this dashboard in an application"
5. Select "Code", from the dropdown select "Python"

**Expected behavior**
The code that we give the user should be up-to-date and run as is.

**Observed behavior**
This code is most likely Python 2.7 - when put in a project with Python 3.7 it doesn't work

**Screenshots**
<img width="1880" alt="Figure 2021-01-15 at 9 52 48 AM" src="https://user-images.githubusercontent.com/74572342/104756499-20249780-5719-11eb-9c7f-a632de7d6e8c.png">

<img width="382" alt="errormsg" src="https://user-images.githubusercontent.com/74572342/104755488-b8ba1800-5717-11eb-8e35-3f4704145ca5.png">

**Information about your Metabase Installation:**
Metabase version v1.37.3

**Severity**
This is annoying for any user trying to set up embedding.

**Additional context**
The easiest fix would be to just remove the .decode from the code snippet. However, we might want to consider specifying which version of Python the code is for in the dropdown, so "Python 3.7" instead of just "Python".  It is conceivable someone might still want to use 2.7 so maybe we should have "Python 2.7" and "Python 3.7" both as options from the Code dropdown selection.

**Comment by paoliniluis** [comment]
Just checked this on my local environment and if instead of pip you do pip3 install, and instead of python... you do python3 ... to execute it works flawlessly

**Comment by ellie-metabase** [comment]
I'm not sure why we're getting different results because I was working with pip3 an python 3.7
