### ISSUE TITLE
I can't connect to Google Analytics

### ISSUE THREAD

**Issue by epaolillo** [metabase/metabase#14421]
**Describe the bug**
When I configure a database in Google Analytics from the database configuration, I receive an error message

**Logs**
Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

**Screenshots**
![Selección_884](https://user-images.githubusercontent.com/2317905/104728600-e4d49980-5715-11eb-9ac3-a9f80459c205.png)

**To Reproduce**
1. Go to settings
2. Add a Google Analytics database
3. Create a Google App, with Desktop Application setting
4. Complete Client ID, Secret Key
5. Generate Auth code
6. Save

**Expected behavior**
The database should be saved

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "es",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.32-0ubuntu0.18.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.6-SNAPSHOT",
      "date": "2021-01-12",
      "branch": "univ",
      "hash": "129a4f9"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Severity**
It is quite important since it does not allow adding the Google Analytics database

**Comment by flamber** [comment]
Hi @epaolillo 
I cannot reproduce latest official release 0.37.6
I would recommend that you have a look at this, which might help you with something that perhaps was overlooked:
https://github.com/metabase/metabase/blob/664467fc6d2bf7c9b2625442506173eba1a1962e/docs/administration-guide/databases/google-analytics.md

**Comment by epaolillo** [comment]
Thanks but did you try creating a new project on Google Platform from scratch?
