### ISSUE TITLE
Pie chart not internationalized for "Other"

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#14420]
**Describe the bug**
Pie chart not internationalized for "Other" 
![image](https://user-images.githubusercontent.com/33416503/104691070-db433580-5705-11eb-86f2-81ae98aa2601.png)

**Information about your Metabase Installation:**

- Your browser and the version: Firefox 84.0.2
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.36.4
- Metabase internal database: Postgres

Related:
https://github.com/metabase/metabase/issues/13830
https://github.com/metabase/metabase/issues/11542

**Comment by flamber** [comment]
This was fixed in 0.37.3

**Comment by jlisyc** [comment]
Great. Thanks a lot for your fast answer.
