### ISSUE TITLE
Return table ID in /api/database/:id/fields

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#14437]
Regarding table info, currently `/api/database/:id/fields` returns only `table_name` (actually this is the display name of the table as discussed in #12419).

It would make API wrappers more robust if this endpoint returns table ID as well.

**Comment by flamber** [comment]
Related to #3663, about having versioned API.

**Comment by paoliniluis** [comment]
@vvaezian https://github.com/metabase/metabase/pull/49206 in case you want to merge it to a local build
