### ISSUE TITLE
Setup UI cant read Service account file for BigQuery - Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'

### ISSUE THREAD

**Issue by Portur** [metabase/metabase#14442]
**Describe the bug**
Going through the setup on the UI, when launched on Google App Engine, an error occurs on the UI: "An error has occurred". Going to the dev console I see an error saying "Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'"

**Logs**
Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at app-main.bundle.js?7f33422c0da5095d441b:5
    at Object.i (vendor.bundle.js?7f33422c0da5095d441b:100)
    at s (vendor.bundle.js?7f33422c0da5095d441b:100)
    at Object.executeDispatchesInOrder (vendor.bundle.js?7f33422c0da5095d441b:100)
    at d (vendor.bundle.js?7f33422c0da5095d441b:98)
    at f (vendor.bundle.js?7f33422c0da5095d441b:98)
    at Array.forEach (<anonymous>)
    at e.exports (vendor.bundle.js?7f33422c0da5095d441b:406)
    at Object.processEventQueue (vendor.bundle.js?7f33422c0da5095d441b:98)
    at vendor.bundle.js?7f33422c0da5095d441b:436

**To Reproduce**
1. Go to /setup
2. Add database type as BigQuery
3. Select service account file
4. Click Next

**Expected behavior**
A connection is made to bigquery

**Screenshots**
![image](https://user-images.githubusercontent.com/24350810/104906551-86fdb700-598c-11eb-8485-bf93665eb8e2.png)
![image](https://user-images.githubusercontent.com/24350810/104906329-3be3a400-598c-11eb-92fe-6fbfbb9d6823.png)

**Information about your Metabase Installation:
Custom installation on Google App Engine (2.3gb ram + 2 cpu)

- Your browser and the version: (Chrome 87.0.4280.141)
- Your operating system: (Windows 10.0.18363)
- Your databases: (BigQUery)
- Metabase version: (Not sure how to check the version as we cant access any pages besides setup. Docket image downloaded on Friday 15 Jan 2021 )
- Metabase hosting environment: (Google App Engine (NGINX))
- Metabase internal database: (BigQuery)

**Severity**
Blocking Usage

**Comment by flamber** [comment]
Hi @Portur 
Please skip setting up database during setup, and do it once logged in from Admin > Databases.
Then you also have access to the log, which might have more detailed error - Admin > Troubleshooting > Logs.
And please include "Diagnostic Info" from Admin > Troubleshooting.

**Comment by Portur** [comment]
I am unable to continue

![image](https://user-images.githubusercontent.com/24350810/104914723-3b510a80-5998-11eb-9628-ac2741b2fdb8.png)

**Comment by flamber** [comment]
@Portur Refresh the page - perhaps the setup was already done - otherwise drop the application database, so you make a new setup

**Comment by Portur** [comment]
Redeployed but got this. Webserver still seems to provide /setup
![image](https://user-images.githubusercontent.com/24350810/104916544-e662c380-599a-11eb-873b-697fcb19250c.png)

I continued without adding a database and completed the setup
![image](https://user-images.githubusercontent.com/24350810/104916751-275ad800-599b-11eb-9cd4-c140c5bf8b27.png)

When I log in with the credentials I created I get immediately redirected to /setup, sometimes a dashboard flashes but quickly redirects back ton login screen

**Comment by Portur** [comment]
going to `/` simply sends me to `/setup`

**Comment by flamber** [comment]
@Portur Sounds like you are using H2 instead of Postgres/MySQL: https://www.metabase.com/docs/latest/operations-guide/configuring-application-database.html
Delete whatever you have spun up and redeploy.
And let's continue in the forum, which is created for questions and troubleshooting: https://discourse.metabase.com/
