### ISSUE TITLE
Allow users to select fields to be displayed in the table

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1445]
Currently we only show the fields in the source table for raw data aggregation, and only show the aggregation and grouped fields for other aggregations, but it would be useful to be able to select fields to display in a table.

For example, you can show the "sum of order totals grouped by user id", but the table would only show the user id and sum, but it would be nice if you could show the user's name instead.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by iwaffles** [comment]
:+1:

**Comment by camsaul** [comment]
This used to be in the UI a few months ago. The QP supports a [`fields` clause](https://github.com/metabase/metabase/wiki/Query-Language-Overview#fields)

**Comment by spectr** [comment]
+1

**Comment by SebastianSzturo** [comment]
:+1:

**Comment by Stayallive** [comment]
This would indeed be very very usefull! I end up writing queries for most table view myself since I cannot add extra columns, like in the example mentioned I most if the time want to add a user name to a row but are unable unless I'm grouping by that field ofcourse.

**Comment by nielsonsantana** [comment]
I missing this feature too. =/

**Comment by MrMauricioLeite** [comment]
Guys, any news about that? Isee it's closed but don't see the feature on metabase

Would really be useful and looks like a quick win on the dev side.

**Comment by mazameli** [comment]
I put together a prototype for this. Feedback welcomed:
https://invis.io/VA7DFNENK

**Comment by iwaffles** [comment]
In addition to @mazameli's cool prototype, it'd b neat if you could save those preferences so if you were generating a report for someone else, you could easily show only what was important without having to tick/untick a bunch of boxes each time you visited the card.

**Comment by MrMauricioLeite** [comment]
WOOOOOOW, Perfect solution.
I'm assuming that I can save a card and it will remember what columns to show, right?

Guys, I'm always overwhelmed with Metabase designs and prototypes. I admire how this feature fits perfectly where you placed it.

Keep up the great work, and know that this is a compliment to all Metabase's Team.

**Comment by camsaul** [comment]
@mazameli I agree that looks pretty cool 😍

**Comment by MrMauricioLeite** [comment]
Is it only a change for the front end? The backend is ready to support it?
I want that so much that I'm taking a course on react and another on clojure. How can I help?
:shipit:

**Comment by camsaul** [comment]
@MrMauricioLeite This is just a frontend thing, the backend already supports it 💻 🌎 😎

**Comment by MrMauricioLeite** [comment]
Ok, I'll try to figure out why I'm not able to run a local copy on my Windows machine and try to play around with the frontend on React to accomplish that. Or is anyone developing it right now?

**Comment by mazameli** [comment]
I like that this is tentatively in 0.19. I think there are only a few small open questions:

* Should this dropdown only be present in Raw Data / table view for now?
  * bias: yes
* Can you aggregate/filter/group with a hidden field? 
  * Bias: this dropdown should strictly be for showing/hiding visible fields in table view. It shouldn't affect whether or not you can aggregate/filter/group.
* Can I include fields in the table from other tables via foreign key?
  * I believe so, provided you haven't aggregated?

**Comment by aguynamedben** [comment]
@tlrobinson I saw [your comment in #2931](https://github.com/metabase/metabase/pull/2931#issuecomment-235430370) about how #2931 doesn't fully resolve the requirements in this ticket. If that's the case, should this issue remain open? Or am I missing something in the UI?

The number one reason I frequently drop to raw SQL is to add a column to the SELECT clause Metabase is generating. Is there a way to generate the following query using the Chart Settings UI?

```sql
-- Get the number of questions per user, with name
SELECT users.id, users.name, COUNT(*)
FROM users
  INNER JOIN questions ON users.id = questions.user_id
GROUP BY users.id
```

Am I missing something in the UI? It seems like the "Customize the chart" popup should allow addition of columns as well. Just making sure. Thanks for the work you're doing on this great project.

**Comment by tlrobinson** [comment]
You are correct, I'll re-open this.

There's a prototype of a way to pull in additional fields at #3043 but it's not complete.

**Comment by aguynamedben** [comment]
Oh, sweet, that's awesome. I'm new to Metabase development, but I'll check out the PR for fun.

**Comment by Nick-Lucas** [comment]
Any chance of getting this in the near future?

**Comment by Vadorequest** [comment]
This feature isn't available yet, right? I could really use this.

**Comment by jornh** [comment]
Hey everyone, one way the core developer team prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍 comments, please just upvote by adding a reaction to the issue description.

**Comment by tlrobinson** [comment]
FYI this is partially resolved, at least for "raw data" queries, since you can add fields linked by FK. However it doesn't work for queries with breakouts.

**Comment by SergeySmile** [comment]
Any updates? Now is the only one way to setup visible columns by using sql. But it's hard for managers.

**Comment by salsakran** [comment]
Closing this since
1) we have column visibility controls since #2391
2) For the specific example @aguynamedben you can do this via our GUI (see attached screenshot)
3) you can use notebook mode joins to do this as well if you want to get in the weeds

![Screen Shot 2020-03-05 at 6 24 52 PM](https://user-images.githubusercontent.com/107439/76044298-cce59400-5f0e-11ea-9d58-76dcfacbc84a.png)

If anyone (include @SergeySmile ) have specific use cases they aren't able to accomplish, please chime in and I'll re-open (or probably open a more specific.
