### ISSUE TITLE
Handle scheduled tasks on deployments that idle (Heroku) or horizontally scale app server

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1446]
Currently we run scheduled tasks (daily database syncing, sending "pulses" hourly/daily/weekly) directly in the Metabase application server, and assume a Metabase deployment is always running exactly one instance. This isn't a safe assumption on PaaSs such as Heroku which will shutdown idle applications, or deployments which run more than one instance of the app server in order to scale out.

We should have some way of running of these tasks separately from the application server, possibly via a separate worker process, or keeping track of which tasks have/haven't been run in the database and periodically processing them.

In the case of Heroku, the free tier allows you to run one web and one worker dyno, however the [worker dyno is idled whenever the web dyno is idled](https://devcenter.heroku.com/articles/dyno-sleeping#sleeping), so you can't assume it is always running. Heroku has a [scheduler](https://devcenter.heroku.com/articles/scheduler) addon, however it is unclear if it can be automatically configured during the one-click "deploy to Heroku" process.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tiwariayush** [comment]
Using separate worker dyno could be helpful in cases of downloading large results as xlsx/csv, which currently gives timeout (as Metabase on heroku uses web dyno which has a timeout limit of 30secs).

**Comment by dayjobtitus** [comment]
Wow this issue still exists 7 years later? Can we get an idea if this is ever intended to be fixed?

**Comment by paoliniluis** [comment]
We don't officially support Heroku anymore, and Metabase runs fine horizontally scaled
