### ISSUE TITLE
Selecting starting data in the Notebook editor is painful

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14467]
Trying to find either the table or saved question you want to use as your starting data in the notebook is too hard:
- You have to click into a database to expose a search bar to then search for a table. But what if you don't know which database or schema the table is in?
- Similarly, if you're trying to start a new question using saved question data, you can't search across all collections; you have to click into a collection to search its contents.
- With the existing saved question/collection search box, when you have many collections and databases, if you start typing into the filter box to search for a saved question, the popover scrolls horribly, making you lose your position.
- https://github.com/metabase/metabase/issues/14178 makes trying to browse for a saved question in the data picker truly awful, as it presents all the collections in a flat list instead of in the correct nested structure.

It seems what I'd want is one search box at the top of this popover that would let me search for tables or saved questions across all databases and collections.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/2223916/105257615-003c0c00-5b3d-11eb-8eb7-38550fb65e70.png">

@salsakran, let me know if I've missed anything from your perspective.

**Comment by mazameli** [comment]
Related: this suggestion to include description/metadata info about the data within the selection flow https://github.com/metabase/metabase/issues/14596

**Comment by flamber** [comment]
The third "if you start typing into the filter box to search for a saved question, the popover scrolls horribly" is #14782

**Comment by flamber** [comment]
This was included in 0.40: https://www.metabase.com/blog/Metabase-0.40/index.html#improved-data-selection
