### ISSUE TITLE
Click Behavior with cross-filter sometimes does not list column options

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14473]
**Describe the bug**
When doing cross filtering on the same dashboard, then it will sometimes not list the columns as available options, but allows updating one filter with another filter.

**To Reproduce**
1. Native question > Sample Dataset > `SELECT COUNT(*) FROM PRODUCTS` as Table viz, save to dashboard
2. Add 4 filters - 2 category, 2 id (doesn't matter if they are connected)
3. Hover card > Click Behavior > select column > "Update a dashboard filter"
4. Clicking "ID 1" option will correctly show the column as option, but also shows the other "ID" dashboard filter.
![image](https://user-images.githubusercontent.com/1447303/105353454-887ae980-5bef-11eb-8b60-7102ce2e0b91.png)
5. Clicking "Category" option will only show the other "Category 1" filter, but not the column.
![image](https://user-images.githubusercontent.com/1447303/105353484-94ff4200-5bef-11eb-999f-b4c65832ee5e.png)

**Expected behavior**
It should allow selecting a numeric column for a category filter.
I don't think you should be able to update the filters with another filter on the same dashboard - only on "Go to a custom destination".

**Information about your Metabase Installation:**
Tested 0.37.0 thru 0.37.7

**Additional context**
https://discourse.metabase.com/t/cross-filtering-not-working/13041

**Comment by paulrosenzweig** [comment]
Fixed in #14668
