### ISSUE TITLE
Pie chart legend or body could show count and/or % value (UI enhancement)

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#1448]
So, pie charts are the blight of informative data visualization.
They are relatively low in signal.
I think just making it so you don't have to hover to see the actual values / percentages for each field in a pie chart would drastically increase their usefulness in dashboards.

Could either include the numeric information in a legend or in the body of the pie chart itself next to the labels for the fields, with an optional show/hide toggle?

If you want to get extra fancy, could humanize the numeric values with std. suffixes (e.g. 125k) or scientific notation to avoid text clipping overflow.

Being forced to hover over each slice to see the percentage/value makes an already inconvenient way to ingest information slightly more painful.

Anyway, just a super low priority enhancement that I thought I'd file away.
More of a rant against pie charts in general :)

Cheers,
Ethan

**Comment by phalgun** [comment]
+1

**Comment by sherbondy** [comment]
May be best to close this silly issue / merge it with #1454. General premise/desire is to level-up chart legends and annotations.
