### ISSUE TITLE
UI should update when a collection changes parent

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#14482]
**Describe the bug**
There are two parts to this issue but both feel related.

## 1. The first part is a follow up from this PR (#14367), and is partially documented in the original issue #14280.

When a collection is moved to a new parent, that parent should be immediately open. #14367 is making sure that child collections gets moved, but the parent collection stays collapsed, making this UX really confusing. Note that the title ("First collection") indicates that the collection is currently open. However, you can't see it in the sidebar.
![image](https://user-images.githubusercontent.com/31325167/105423423-c3a80780-5c45-11eb-9910-aefd4870a3e4.png)

**Logs**
N/A

**To Reproduce**
- Follow the steps from #14280

**Expected behavior**
New parent collection should be immediately open, clearly showing its children (with the focus on a collection that was moved inside of it).

**Screenshots**
Please note the thin dark blue bar above "New collection". It disappears on a click wherever in the page. That leads us to the second part of this issue.
![image](https://user-images.githubusercontent.com/31325167/105423776-72e4de80-5c46-11eb-81eb-c65a9e4563b3.png)

---

## 2. When we move **nested** child collection from an existing parent to the root collection, UI is showing that collection in both places. Clicking on it shows updates in both places as well. That disappears on a page refresh.

**Steps to reproduce:
- Make sure you haveone parent collection with at least two nested children collections
- Move the child to the root (Our analytics)
- Note that you can see it in both places
- Refresh the page and it's going to be clearly visible in the root only

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/E0u4DRGX/54540a88-ac60-4b6e-abdd-53db09d128ee.gif?source=viewer&v=1ebe7d3ea8dfcac69bf2735386fce8f7)

**Information about your Metabase Installation:**
- Your browser and the version: Brave, Chrome, Firefox (doesn't seem to be related)
- Your databases: H2, local dev
- Metabase version: `v0.38.1-SNAPSHOT`

**Severity**
Both issues are really confusing. Not blocking anything, so I'd say it's a P2?

**Comment by camsaul** [comment]
Fixed by #14622
