### ISSUE TITLE
Upgrading React  to 16 makes Custom Expression does not work well

### ISSUE THREAD

**Issue by XKange** [metabase/metabase#14487]
I need add antd dependency in the project , so I upgrade React to 16, but it does not woke well in Fitler's Custon Expression.I debug in Chrome devtools， it looks like something wrong in TokenizedInput.jsx method `componentDidUpdate`.
Did anyone knows how to resolve this ?

```
componentDidUpdate() {
    const inputNode = ReactDOM.findDOMNode(this);
    const restore = saveSelection(inputNode);
    ReactDOM.unmountComponentAtNode(inputNode);
    while (inputNode.firstChild) {
      inputNode.removeChild(inputNode.firstChild);
     }
    ReactDOM.render(
      <TokenizedExpression
        source={this._getValue()}
        syntaxTree={this.props.syntaxTree}
        parserOptions={this.props.parserOptions}
      />,
      inputNode,
    );

    if (document.activeElement === inputNode) {
      restore();
    }
  }
```

here is the Warning:
> Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component.
Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.
    in TokenizedInput (created by ExpressionEditorTextfield)
    in div (created by ExpressionEditorTextfield)

**Comment by flamber** [comment]
Hi @XKange 
We are working on upgrading React (and several other libraries), but that's a bigger process - #14391
And a big part of CE is also being re-written: https://github.com/metabase/metabase/tree/0.39-improve-custom-expression
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
