### ISSUE TITLE
Clarify how stacked bar charts are supposed to work

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#1449]
Hey all,

So I read on the discourse that stacked bar charts are supposedly implemented:
http://discourse.metabase.com/t/advanced-charting-features/57/2

Tried to get one to appear.
Figured it'd involve doing an aggregate by two different columns so I did a:
"count by connected_table_a.field1 and connected_table_b.field2"

What was weird was depending on the "type" of table_b.field2, I got wildly different results, even though the tabular representation remained more-or-less the same.

Fields of the second table that I tried (one with **Entity Key** meta, two with **Category** meta):
<img width="299" alt="screen shot 2015-11-04 at 6 18 48 pm" src="https://cloud.githubusercontent.com/assets/193187/10955347/250869d8-8321-11e5-81bd-7342cd4e500a.png">

##Attempt 1 Table (looks good):
<img width="842" alt="screen shot 2015-11-04 at 6 17 01 pm" src="https://cloud.githubusercontent.com/assets/193187/10955331/15d5364e-8321-11e5-9469-390ad849fb52.png">
##Corresponding Bar Chart:
<img width="840" alt="screen shot 2015-11-04 at 6 18 38 pm" src="https://cloud.githubusercontent.com/assets/193187/10955392/6137e41a-8321-11e5-820a-51ce474a2e98.png">
Completely blank.
Expected Bar Chart: Stacked bar chart with count summed across rows, with each stack corresponding to a distinct slug.

#Attempt2:
Thought I'd try grouping by the ID field instead. Results below:

##Attempt 2 Table (looks good):
<img width="853" alt="screen shot 2015-11-04 at 6 26 51 pm" src="https://cloud.githubusercontent.com/assets/193187/10955433/b68f6f82-8321-11e5-91e2-b6dcbb9cb0f9.png">
##Corresponding Bar Chart:
<img width="856" alt="screen shot 2015-11-04 at 6 18 10 pm" src="https://cloud.githubusercontent.com/assets/193187/10955464/f3b5d0a4-8321-11e5-972f-c02c6557fe2f.png">
Got values, but they are not stacked :(

#Attempt 3:
Tried using the name field for both. Figured this would completely fail because of #1447 
Got something quite surprising.

##Attempt 3 Table:
Guess it decided to split into field_a's category count instead of field_b's category count because of name conflict. Somehow "count" ended up as the title for the first column in the results table.
<img width="1036" alt="screen shot 2015-11-04 at 6 32 22 pm" src="https://cloud.githubusercontent.com/assets/193187/10955546/8b869f58-8322-11e5-829d-092b65e0ad5b.png">
##Corresponding Bar Chart:
<img width="1271" alt="screen shot 2015-11-04 at 6 34 19 pm" src="https://cloud.githubusercontent.com/assets/193187/10955563/bc45185e-8322-11e5-9173-aa1f99a5e2d1.png">

Woohoo! A stacked bar chart. So the unicorn does exist. Except:
1. There are only 2 chunks stacked even though there are 3 distinct fields.
2. The values for the stacks are garbage. In fact, both stacks are the exact same height and are actually just the total for the order count repeated twice.

**Comment by sherbondy** [comment]
Also curious how you get a stacked bar chart out of a sql query :)

**Comment by sherbondy** [comment]
Maybe this is because I need to assign the fields the type "Dimension" as opposed to "Information" in the metadata editor?

<img width="1112" alt="screen shot 2015-11-04 at 6 44 14 pm" src="https://cloud.githubusercontent.com/assets/193187/10955758/308a5b42-8324-11e5-9668-72b8efe55177.png">

A little confused by the description of dimensions because they are referred to as: "numerical string values". Not sure what a numerical string value is.

**Comment by styts** [comment]
For stacked bar charts to work, you need to make sure your query returns:
1) in the first column your x axis values (the bar chart "buckets")
2) in the subsequent columns the numerical values for the individual bar-parts.

An example of an sql query that worked for me in producing a stacked bar chart:

    SELECT counter, column1, column2, RANDOM() from my_table;

In the "raw data" view for your query, you should see numerical values in each field. The stacked bar chart view works for both raw sql and question-gui queries.

**Comment by tlrobinson** [comment]
I agree this is confusing, +1

**Comment by bernardosrulzon** [comment]
+1. Stacked bar charts should be much more flexible than they are today!

**Comment by camsaul** [comment]
Point of order: I think we should recategorize this as something other than "Bug", and perhaps change the title to something more actionable

**Comment by salsakran** [comment]
this should be sorted in the latest version (0.19) with our new charting controls.
