### ISSUE TITLE
Dashboard subscriptions including cards no longer in dashboard

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14497]
I need to verify that this happens with newly created subscriptions, not just with ones that have been around for a while.

A potentially related detail: I found this bug while testing default dashboard filters, so my dashboard had a default value set for my Category filter in case that's relevant.

## To reproduce:

- Create a dashboard with several cards
- Set up an email-based dashboard subscription and save it
- Remove some of the cards on the dashboard
- Send the subscription via the send-email-now button
- See that the subscription email will incorrectly contain the questions that were in the dashboard when the subscription was created.

## The current state of my dashboard:

<img width="1751" alt="image" src="https://user-images.githubusercontent.com/2223916/105530191-4bb8fc00-5c9c-11eb-849a-9605a2f137fd.png">

## The email I got included questions that I had removed:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/2223916/105530150-3e037680-5c9c-11eb-95b4-1dfc0d78c761.png">

**Comment by mazameli** [comment]
It's also including an attachment for the table that used to be in the dashboard but that I removed (the attachment on the far right):

<img width="683" alt="image" src="https://user-images.githubusercontent.com/2223916/105530937-6d66b300-5c9d-11eb-983f-2346c06da750.png">

And in the subscription's settings, it's showing me attachment options for cards that aren't in the dashboard:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/2223916/105530990-7ce5fc00-5c9d-11eb-88dc-4d5cb1260912.png">

**Comment by tsmacdonald** [comment]
@mazameli I can't reproduce this locally, and we did change how card removal works ~2 weeks ago. Is it possible you have stale data?

**Comment by mazameli** [comment]
I'll try to repro with a fresh dashboard.

**Comment by mazameli** [comment]
Couldn't repro with a fresh dashboard, either. Apologies, @tsmacdonald. 😞
