### ISSUE TITLE
Login page should automatically focus on the email input field

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#14505]
Steps:

1. Launch Metabase
2. Go to /auth/login

**Actual**:

The first input field, email address, does not receive the focus:

![image](https://user-images.githubusercontent.com/7288/105654786-950f7400-5e73-11eb-88d4-f13101155c97.png)

**Expected**:

The first input field, email address, **already** has the focus. Thereby the user can start typing their email address right away:

![image](https://user-images.githubusercontent.com/7288/105654842-b53f3300-5e73-11eb-9a14-2835b9f21a4f.png)

**Comment by nemanjaglumac** [comment]
Related (and should be implemented finally): https://github.com/metabase/metabase/issues/2060
