### ISSUE TITLE
Slack-based dashboard subscriptions should have a "Send to Slack now" button

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14515]
To get to feature parity with Pulses, dashboard subscriptions are supposed to have a "Send to Slack now" button like Pulses do when setting up a subscription that pushes to Slack. Here's how it looks in a Pulse:

![image](https://user-images.githubusercontent.com/2223916/105772752-837fa800-5f17-11eb-8d2e-aaf37e7af92d.png)

I've added this to 0.38.1 — it's sort of a new feature, but it's also an existing feature, and it's somewhat of a "bug" since we overlooked this.

**Comment by nemanjaglumac** [comment]
@mazameli I can write a test about this up-front. Can you please give me a few more informations please:
- Do we replace "Done" button with "Send to Slack now"?
- Do we disable that button until a channel has been selected (like we do for the "Done" button)?
- ... feel free to add any info you think is relevant

Thanks

**Comment by mazameli** [comment]
@nemanjaglumac It should behave just as it does in the Slack scheduling box for pulses currently:

- The send to slack now button should go right below the scheduling picker dropdowns (we should _not_ replace the Done button).
- Yes, the button should be disabled until a channel has been selected, just like in the Pulse create/edit form.
