### ISSUE TITLE
Render waterfall charts in pulses/dashboard subscriptions

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#14516]
Waterfall charts are rendered as plain ol' bar charts when sent out as pulses or dashboard subscriptions.

For example, this chart in a dashboard:

![image](https://user-images.githubusercontent.com/784417/105773830-2e00c680-5f2a-11eb-9223-ff67b2bb0ab6.png)

looks like this in an email:

![image](https://user-images.githubusercontent.com/784417/105773850-3822c500-5f2a-11eb-8bf9-6a59da840f10.png)

**Comment by flamber** [comment]
Closing in favor of #18676
