### ISSUE TITLE
More sensible values for 'humanization-strategy' in /api/settings

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#14521]
The item with the key 'humanization-strategy' in the endpoint `/api/settings` corresponds to the value chosen for "Friendly Table and Field Names" in Admin Panel > Settings > General. The values are:
- 'Only replace underscores ...' -> 'simple'
- Enabled -> None
- Disabled -> 'none'

The last two cases would benefit from more meaningful strings.

**Comment by flamber** [comment]
If this is changed, then the values needs to be backward compatible. This is the current values:

- Enabled = `advanced` (or null)
- Disabled = `none`
- Only replace underscores and dashes with spaces = `simple`

Related to #13227

**Comment by flamber** [comment]
Closing this, since from 0.40 the "advanced" functionality has been removed (reference #7606), so it's now:
- Replace underscores and dashes with spaces = `"simple"` (or `null`, default)
- Disabled = `"none"`
