### ISSUE TITLE
Calendar widget jumping up and down when browsing through months

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#14546]
**Describe the bug**
When I try to set a single date in the calendar widget and browse through months, then the calendar jumps up and down on screen depending on the number of weeks in the month.

**To Reproduce**
1. Create a new dashboard.
2. Create a new single-date filter widget.
3. Click "Default value" at the right panel.
4. Browse back through months.
5. Notice the calendar widget jumps up and down the screen to fit the screen space.

**Expected behavior**
I expect calendar to stay at the same place, so I can browse back and forth efficiently.

**Screenshots**
![27 Jan 2021 at 17_00_29](https://user-images.githubusercontent.com/30152071/106018543-ead95b80-60c1-11eb-8765-f81a14f14579.gif)

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "Eclipse OpenJ9 VM",
    "java.vm.version": "openj9-0.18.0",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.32"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-13",
      "tag": "v0.37.6",
      "branch": "release-x.37.x",
      "hash": "344e5e0"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}`

**Severity**
Just a UX issue and can be worked around, but extremely irritating.

**Additional context**
Searched, but couldn't find an issue about this behaviour. Applies to multiple places where there is the calendar widget.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by nemanjaglumac** [comment]
I tried in 4 different browsers, but I can't reproduce this.

**Comment by flamber** [comment]
@nemanjaglumac It depends on browser view height and the position of the popover. I see it constantly with field selectors too.

**Comment by nemanjaglumac** [comment]
cc @kdoh - one more reason to consider [`react-popper`](https://github.com/popperjs/react-popper) or a similar alternative :)

**Comment by brunobergher** [comment]
Doesn't happen with new picker.
