### ISSUE TITLE
Chart annotations and legend

### ISSUE THREAD

**Issue by tomkanjam** [metabase/metabase#1454]
Line and Bar charts need annotations or legends when there are multiple x-axis datasets. Without this information the chart is useless

![image](https://cloud.githubusercontent.com/assets/303566/11001246/48785f96-8474-11e5-8790-7a27daba092a.png)

**Comment by phalgun** [comment]
+1

**Comment by styts** [comment]
+1

**Comment by jornh** [comment]
This seems to be implemented already as of version 0.26.2 (probably much earlier?)

**Comment by mazameli** [comment]
Closing this as it was implemented ages ago.
