### ISSUE TITLE
Serialization: Click Behavior not translating entitiy ID on dump, potentially referencing wrong entities on load

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#14566]
If the link is pointing to a MB entity with an ID, we should preserve that correctly.

**Comment by paulrosenzweig** [comment]
There's some other question data that  references app db ids. We should check that nothing else breaks.

I think dashboard click behavior is the only case where we use dashboard or question ids in visualization settings, but we use field ids frequently for column settings. Are metadata tables also transferred in serialization?

Outside of visualization settings, field filters and dashboard parameters both reference fields by id.

Snippets and nested native questions are similar to that case. They both embed resource ids in template tags like field filters do.

**Comment by salsakran** [comment]
In general, I think we should become increasingly careful about storing anything in a semi-structured field that refers to other tables. We should be able to lean on our application database constraints to guard against problems like this. Let's not re-invent FK constraints badly in JSON.

**Comment by flamber** [comment]
Doesn't this only apply to `click_behavior.tableId` for `click_behavior.linkType=(dashboard|question)` ?
It could become very messy if done on `linkType=url` - aka Custom Destination.

**Comment by sbelak** [comment]
Kind of. We in general do know what urls are pointing back to us, so it's feasable but of questionable sanity.

**Comment by paulrosenzweig** [comment]
Yeah totally agree on moving to keep things structured. In addition to serialization issues, that could enable nice features:
- When someone updates metadata in admin, we can warn them "this will break these 10 questions"
- We can block archiving a question when native questions embed it or change that archive action to archive the whole tree.
- Bundling in click behavior "target entities" with a dashboard request. Currently, we have to trigger those loads separately.

---

Regarding URLs, I think trying to parse/structure those is a step too far. If there are common link destinations to the current MB instance outside of questions and dashboards, we should non-URL destination options to enable that.

**Comment by jeff303** [comment]
This should be fixed by commit 2 under #15858.

**Comment by rlotun** [comment]
fixed by https://github.com/metabase/metabase/pull/15858
