### ISSUE TITLE
details on how to migrate from H2 to postgres or mysql

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1456]
i took a stab at migrating our existing H2 db to postgres today, based on this tease at the bottom of 
http://www.metabase.com/docs/v0.12.1/operations-guide/running-the-metabase-jar-file.html#postgres :

> NOTE: currently Metabase does not support migrating data from one application database to another, so if you start with H2 and then want to move to Postgres you'll have to dump the data from H2 and import it into Postgres before relaunching the application.

...but i didn't get too far. has anyone over there ever tried this?

the [H2 docs](http://h2database.com/) led me to `org.h2.tools.Recover`, which gave me a full SQL dump of my db. it's definitely an H2-specific dialect, though. when i tried to load it into a postgres db with e.g. `psql -v -d metabase -f metabase.db.h2.sql`, pretty much every line errored out.

`org.h2.tools.Script` also claims to dump an H2 db to SQL, but i couldn't get it to even see the H2 db file. e.g. `java -cp metabase-0.12.1.jar org.h2.tools.Script -url jdbc:h2:./metabase.db.h2.db` and variations gave me this `backup.sql` file:

```
;              
CREATE USER IF NOT EXISTS "" SALT '' HASH '' ADMIN;            
```

if i add `;IFEXISTS=TRUE` to the jdb url, e.g. `-url 'jdbc:h2:/Users/ryan/metabase.db.h2.db;IFEXISTS=TRUE'`, i get:

```
Exception in thread "main" java.sql.SQLException: No suitable driver found for jdbc:/Users/ryan/metabase.db.h2.db;IFEXISTS=TRUE
```

even though the file is there.

googling appropriate search terms didn't find much. let me know if you have any tips! otherwise we may have to set up backups etc for the file-based H2 db instead of migrating.

**Comment by agilliland** [comment]
So the short answer is no, we haven't actually done this yet, but I'm sure it will be fairly common so I'll put some time into checking this out and seeing how we can make this as painless as possible.

**Comment by snarfed** [comment]
thank you!

**Comment by styts** [comment]
Just bumping this to let you know that exporting the H2 db to SQL (and a migration to Postgres) would be something I'm also interested in.

**Comment by phalgun** [comment]
+1. Even we at @signeasy are looking into migrating from H2 to Postgres or MySQL.

**Comment by camsaul** [comment]
I'm able to generate the SQL dump like this in the REPL

```clojure
(ns metabase.db)
(jdbc/query (jdbc-details @db-connection-details) ["SCRIPT TO '/Users/camsaul/metabase/dump';"])
```

So now it's a matter of converting the H2 dialect to PG/MySQL. H2 [has compatibility modes for Postgres and MySQL](http://h2database.com/html/features.html) so I'll play around with those and see if they help.

**Comment by BattleBrisket** [comment]
(related) We're using Metabase for a new project, and we automate our projects to the hilt using Salt. Some command line export/import functionality would be super-awesome for us to manage question changes, deploying to new boxes, etc.

**Comment by snarfed** [comment]
woo, thanks all, can't wait to try this!

**Comment by tmr12** [comment]
I am able to generate a sql dump file from h2 using `org.h2.tools.Script.process(Connection con,SQLfile_name,"","")`.
how the generated dump file (from h2)can be uploaded into postgres?
Could you please help on this if you already done the migration from h2db to postegres

**Comment by camsaul** [comment]
@tmr12 You don't need to generate an H2 SQL dump. See [this guide](http://www.metabase.com/docs/v0.14.1/operations-guide/start#migrating-from-using-the-h2-database-to-mysql-or-postgres) which explains how you can have Metabase load data from a H2 database into a Postgres one
