### ISSUE TITLE
Control which groups can. create pulses/dashboard subscriptions.

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#14561]
**Is your feature request related to a problem? Please describe.**
We should add the ability for admins to allow groups to create pulses, alerts or dashboard subscriptions. One of our larger Enterprise requested this.

**Describe the solution you'd like**
There should be a way to mark groups as not able to subscribe to dashboards or create pulses/alerts. The idea is that they would be added to existing subscriptions/pulses by an admin.

**Additional context**
related #6744 #10795

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by luizarakaki** [comment]
This feature is available for Pro/EE plans since 43.
https://www.metabase.com/docs/latest/permissions/introduction#application-permissions
