### ISSUE TITLE
Right alignment of pivot table value cells looks broken

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14574]
Opening up a separate bug issue for this, which was originally reported in https://github.com/metabase/metabase/issues/14351. This seems to occur when there's more than one aggregation/metric:

![](https://user-images.githubusercontent.com/4504437/106086510-28ec8300-6187-11eb-910c-9ef5adbfcd12.png)

![](https://user-images.githubusercontent.com/1447303/106124482-6b986600-615b-11eb-884c-1bb89ae608c4.png)

![](https://user-images.githubusercontent.com/2223916/106207383-81ffeb00-6176-11eb-9052-fc94ab9dadcb.png)

**Comment by flamber** [comment]
@mazameli Grand totals are still skewed in some situations:
![image](https://user-images.githubusercontent.com/1447303/106473420-0a96c800-64a4-11eb-952f-fe76c9f6446f.png)

**Comment by paulrosenzweig** [comment]
🤔 I'm not sure why that row would be different. I'll take a look.

**Comment by flamber** [comment]
Think it might have something to do with the long currency name of Danish Kroner (DKK). But see the overlap, when it's a small pivot:
![image](https://user-images.githubusercontent.com/1447303/106480550-d1faec80-64ab-11eb-806f-23182b8235f7.png)

**Comment by paulrosenzweig** [comment]
@flamber yeah you're right. The aggregated values with the currency code were longer than the fixed cell widths.

As a side note, we could maybe start using compact formatting for this. You rarely need to think about cents when the values are in the millions.

**Comment by flamber** [comment]
@paulrosenzweig Sounds like what we used to have on Trends 12629 - there's a specific request for it in general 12057
