### ISSUE TITLE
Fix placement of dashboard subscription attachment on/off toggle

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14575]
This seems like it will involve pulling the toggle out of the `EmailAttachmentPicker` component. The toggle should be on the same line as its label, "Attach results:"

![image](https://user-images.githubusercontent.com/2223916/106211966-757f9080-617e-11eb-9cc5-6b545f5a90df.png)

**Comment by Toledodev** [comment]
Hey @mazameli, can you show the URL?

**Comment by brunobergher** [comment]
Fixed at some point.
