### ISSUE TITLE
Unable to connect to remote  Presto - Need help 

### ISSUE THREAD

**Issue by TarunTeja333** [metabase/metabase#14582]
Hi , 
I using windows machine ,
With the command on " Java -jar metabase.jar " 
i am able to run the ui metabase in browser at localhost:3000.
Successfully Connected : 
local mysql and Remotemysql 
* Unable to connect **Presto** - which is in  another linux machine . 
* Added all the required connction details .
*
![image](https://user-images.githubusercontent.com/54944469/106263110-f6578e80-6249-11eb-87d6-7c38c5fb6256.png)

can some one help connecting to remote  presto .Our presto consists of mutiple catalogs 
Any suggestion is appreciated , Thanks

**Comment by paoliniluis** [comment]
Hi @TarunTeja333, please head to Discourse for support, you might be facing a network issue. I'll be closing this one
