### ISSUE TITLE
Pivot tables broken on dashboard after resize

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#14591]
Refreshing fixes this.

![resize pivot table on dashboard](https://user-images.githubusercontent.com/691495/106337564-75a38d00-625f-11eb-8e5e-89a23ccd3465.gif)

**Comment by ariya** [comment]
Another way to demonstrate the problem:

1. Ask a question, Simple question.
2. Pick your data: Sample Dataset, Orders table.
3. Summarize, Count. Group by Source and Created At:Year
4. Visualizations, Pivot Table.
5. Field to use for the table rows: User.Source and User.CreatedAt
6. Save
7. Add to a new dashboard
8. Resize the pivot table in the dashboard, Save.
9. Scroll vertically inside pivot table.

**Expected**:

_Grand totals_ row is displayed properly.

**Actual**:

_Grand totals_ row is not invisible.
Also, _Totals for Twitter_ is only half visible.

![image](https://user-images.githubusercontent.com/7288/106512208-27bc9e00-6486-11eb-8744-e28600612ae7.png)

**Comment by ariya** [comment]
Unfortunately, looks like there is no need to have multiple breakouts to demonstrate the problem. Even something like this will clip the bottom part of the pivot table:

![image](https://user-images.githubusercontent.com/7288/106527760-a4f30d80-649c-11eb-83db-68e8b7bfc490.png)

**Comment by ariya** [comment]
Bad news: refresh doesn't always solve the problem.

Good news: seems that this is a matter of adding (or rather, subtracting) a constant number of pixels. Not idea yet what's the reasoning behind it, but if I do this (this is for left header's `Collection`:

```diff
--- a/frontend/src/metabase/visualizations/visualizations/PivotTable.jsx
+++ b/frontend/src/metabase/visualizations/visualizations/PivotTable.jsx
@@ -418,7 +418,7 @@ export default class PivotTable extends Component {
                     leftHeaderCellSizeAndPositionGetter
                   }
                   width={leftHeaderWidth}
-                  height={height - topHeaderHeight - scrollBarOffsetSize()}
+                  height={height - topHeaderHeight - scrollBarOffsetSize() - 40}
                   scrollTop={scrollTop}
                   onScroll={({ scrollTop }) => onScroll({ scrollTop })}
                 />
```
then I can consistently have the last row (`Grand totals`) shown without being clipped (half or completely).

The mysterious thing is that this number `40` does not relate to the browser zoom level: going 100% or 150% yield the same good result. Looks like it indicates that the said number has nothing to do with the text metrics.

Another weird thing is that this number does not relate to the number of rows in that particular column. Look at the following screenshot demonstrating two pivot tables. The left one has 13 rows in the left header (Q2 2016 till Q2 2019), the right now has only 5. Yet, the `Grand totals` row is fully visible thanks to the the `40` offset.

![image](https://user-images.githubusercontent.com/7288/106542419-ab8f7e00-64b8-11eb-861f-b4686c781aca.png)

I still need to understand better how `Collection` in `react-virtualized` behaves, but if this somehow rings a bell @paulrosenzweig, I'm all ears!

**Comment by camsaul** [comment]
@ariya, I'm adding you as the Assignee so other people know you're working on it

**Comment by ariya** [comment]
The size for the Grid (right column, _Count_) seems to be out-of-sync when editing the dashboard (i.e. resizing the card):

![image](https://user-images.githubusercontent.com/7288/106635224-6eb59c80-6535-11eb-9516-4f22c0e3d0e4.png)

Browser refresh resets the Grid size to the correct one (hence why it solves the problem):

![image](https://user-images.githubusercontent.com/7288/106635275-7ffea900-6535-11eb-91df-aed32e9548ef.png)

**Comment by ariya** [comment]
If the Grid's `props.height` is manually changed via React Dev Tools (to match that of the left header's Collection), then the problem disappears: the _Column_ can be scrolled all the way to the bottom to display its total row:

![image](https://user-images.githubusercontent.com/7288/106642418-2dc18600-653d-11eb-970c-474261f45318.png)
