### ISSUE TITLE
Text color on 0.38.0-rc is 10-20% lighter compared to 0.37.8

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14602]
**Describe the bug**
While it might not be a problem for most, the current text color is now 10-20% lighter than previous versions.
Example, default text was `#2E353B` but is now `#4C5773`, and text-medium was `#74838f` is now `#949aab`
It makes it a lot more difficult to distinguish between enabled/disabled elements, and readability in general.
For historians #10485

0.37.8:
![Screenshot_2021-02-01 General · Settings · Admin · Metabase - 0 37 8](https://user-images.githubusercontent.com/1447303/106461921-b7b61400-6495-11eb-90b7-7371c531be17.png)
![Screenshot_2021-02-01 Question · Metabase - 037 8](https://user-images.githubusercontent.com/1447303/106471710-34e78600-64a2-11eb-9218-cdf9aebd8d68.png)

0.38.0-rc4:
![Screenshot_2021-02-01 General · Settings · Admin · Metabase - 0 38 0-rc4](https://user-images.githubusercontent.com/1447303/106461966-c1d81280-6495-11eb-90ca-296a2ba7bf7a.png)
![Screenshot_2021-02-01 Question · Metabase - 038 0-rc4](https://user-images.githubusercontent.com/1447303/106471724-3a44d080-64a2-11eb-91ee-d8dfbedcffd9.png)

Related to #11808

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
I'm relabeling this back to `UX` as @kdoh and I did this intentionally as part of a broader tweaking of our overall colors and typography.

**Comment by brunobergher** [comment]
Effectively a won't fix from Maz above, plus we revised the colors a few times since then.
