### ISSUE TITLE
New Collection modal dialog is very slow, when viewing a collection with many questions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14601]
Update: 0.39 introduced pagination, but the slow input is still a thing - use requestIdleCallback in favor of debounce?

----

**Describe the bug**
When opening/closing or writing in the New Collection modal, while viewing a collection with hundreds of questions, then there's a delay of 1 second between every action (ie. typing each letter). On 0.37.8 it's normal speed (tiny delay).

**To Reproduce**
1. Create hundreds of elements in a collection - example, I have ~500 questions in one collection.
2. Try creating a new collection from that collection - just opening the modal takes almost 2 seconds, and typing the name/description takes ~1 second between each letter.

**Information about your Metabase Installation:**
Tested 0.38.0-rc4

**Comment by mazameli** [comment]
Hmm, we have quite a few orgs that use us that have lots of questions in a single collection. If this makes it nearly impossible to create a new collection in this scenario, this is probably a `P2`, yeah?

**Comment by flamber** [comment]
@mazameli If you only give your collections really really short names, then it's okay :wink:

**Comment by camsaul** [comment]
This should be instantaneous because it doesn't need to make any API requests to show the modal.

I'm guessing maybe it's rerendering the whole collections list component when I click the button, and that's why it takes so long? I'd suggest either fixing the rerendering or showing a spinner while we wait

**Comment by camsaul** [comment]
The collections list is slow in general when you have a lot of Collections... the whole app almost slows to a crawl. Things like search that normally take a second to complete take 10-20 seconds. We need to rethink the API endpoint that powers this... I think we fetch the full Collection object for every collection in the application all at once, and then it tries to render everything. For this page we just need Collection name + ID, and can fetch everything else later... we should page the endpoint too.

**Comment by flamber** [comment]
Closing in favor of #19297
