### ISSUE TITLE
Collection tree loader causes UI jump

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14603]
**Describe the bug**
When going into collections for the first time during a sessions, the loading spinner is shown above the collection elements instead of on the side, which causes the UI to jump. Depending on how slow the load is, or how fast the user is, this might cause the user to click a different element.

**To Reproduce**
1. Go to root collection for the first time during a session, and depending on how many collections are available, it will show the loading-spinner on top of collection elements
![image](https://user-images.githubusercontent.com/1447303/106463311-8a6a6580-6497-11eb-91c8-cc892121efb7.png)
2. ... until the collection tree is loaded in the left side
![image](https://user-images.githubusercontent.com/1447303/106463558-e2a16780-6497-11eb-8bff-db17fe8d3945.png)

**Expected behavior**
Loading spinner should only take up space for the container it's initializing.

**Information about your Metabase Installation:**
Tested 0.38.0-rc4

**Comment by kulyk** [comment]
Fixed by #15719
