### ISSUE TITLE
Advanced Sandboxing using questions that return more/other columns than the sandboxed table is not possible anymore, but the errors are not helpful

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14612]
**Describe the bug**
Advanced Sandboxing using questions that return more/other columns than the sandboxed table is not possible anymore (1.38.0), since it caused an cascade of other problems.
This issue is only about providing helpful errors to admin - not to allow extra columns.

**To Reproduce**
This provides no feedback to the admin, why they cannot select a crazy QB question with extra columns - nothing in the log either.
![image](https://user-images.githubusercontent.com/1447303/106495976-a03e5180-64bc-11eb-925d-38aabdf9a019.png)

Trying to edit a question that is used for sandboxing from
`SELECT ORDERS.* FROM ORDERS WHERE USER_ID={{sandbox}}`
to
`SELECT ORDERS.*, 'x' AS "EXTRACOL" FROM ORDERS WHERE USER_ID={{sandbox}}`
will now not be possible, since the question metadata is checked before saving.
![image](https://user-images.githubusercontent.com/1447303/107055241-5eb9e900-67d1-11eb-87ec-c2a40a792d8b.png)

And it's possible to change a QB question and save - in Notebook without ever seen any errors:
![image](https://user-images.githubusercontent.com/1447303/107057218-81e59800-67d3-11eb-9a52-5a8fce875bbf.png)

And if something like this is setup, when upgrading to 1.38.0 there will be errors when users just tries to access tables.
Example: `Output of gtap->source does not match schema: {:source-metadata [nil nil nil nil nil nil (not (map? nil))]}`
![image](https://user-images.githubusercontent.com/1447303/106498277-720e4100-64bf-11eb-8b72-df2e59b11e5e.png)

**Information about your Metabase Installation:**
Commit `6312927` (~0.38.0-rc4)

**Additional context**
Continuation of https://github.com/metabase/metabase-enterprise/issues/524

**Comment by sbelak** [comment]
For native source queries, can we put in place the constraint that the columns that map to the original table fields, are have to be named the same as those fields. We can relax this requirement once we have our SQL parser.

**Comment by camsaul** [comment]
The error messages part of this at least was fixed by #14673

**Comment by camsaul** [comment]
Fixed by #14735
