### ISSUE TITLE
make it possible to inject driver connection details for any test dataset

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1461]
It would be nice if we could support supplying any possible definition of driver details as input to the connection information of a test dataset when running unit tests.  Currently much of those details are hard coded in the test dataset implementations for each driver.

**Comment by camsaul** [comment]
We have different connection details because the test dataset macros are all about automatically *creating* databases from a database-independent definition and loading data onto them.

If you just want to connect to an existing DB, create a `Database` and give it the details you want and use that.

**Comment by camsaul** [comment]
Here's a macro that would do what you want:

```clojure
(defn do-with-temp-db-with-details [engine details f]
  (let [db     (ins Database
                 :name    "Temp Database"
                 :engine  engine
                 :details details)
        get-id (fn get-id
                 ([]                      (:id db))
                 ([table-name]            (sel :one :id Table, :name (name table-name), :db_id (:id db)))
                 ([table-name field-name] (sel :one :id Field, :name (name field-name), :table_id (get-id table-name))))]
    (driver/sync-database! db)
    (try
      (f get-id)
      (finally (cascade-delete Database :id db-id)))))

(defmacro with-temp-db-with-details [engine details & body]
  `(do-with-temp-db-with-details ~engine ~details
     (fn [~'id]
       ~@body)))
```

Example usage:
```clojure
(with-temp-db-with-details :mysql {:host "localhost", :port 3306, :dbname "Test_Database", :user "camsaul"}
  (println "What's my database id?" (id)))
```

*  Create a new `Database` and sync it
*  Anaphorically bind `id` to a function that can be used to get the ID of the `Database` and its `Tables` and `Fields`
* Wrap `body` in a `try-finally` that destroys temp DB at end of run

If this seems useful we can document it and add it to MB.

**Comment by agilliland** [comment]
I think you are misunderstanding what I was originally suggesting.  I don't actually want to be able to change the connection details on a test by test basis.

The problem I have when I run the current unit tests is that there are hard coded values about the connection details used to connect to the test databases.  So for example when i want to run the unit tests locally against a MySQL database the code is using this ...

```
(merge {:host         "localhost"
          :port         3306
          :timezone     :America/Los_Angeles
          :short-lived? short-lived?
          :user         (if (env :circleci) "ubuntu"
                            "root")}
         (when (= context :db)
           {:db database-name}))
```

Which won't actually connect to my local MySQL database.  So I am simply suggesting that when we launch the unit tests and allow the user to specify that they want to run their tests against various drivers such as postgres, mysql, mongo, and now sqlserver, there should be a way to inject the connection information into the unit testing framework.  You put something in for sqlserver recently which would work fine, i simply think we need to expand that to include all the drivers and allow either env variables or possibly a config file to be used to specify the connection details.

**Comment by camsaul** [comment]
Word. We can easily make it configurable like we do for SQL Server. Meanwhile don't forget you can always just swap out the function in the REPL during dev

```clojure
(let [orig metabase.test.data.mysql/database->connection-details]
  (intern 'metabase.test.data.mysql 'database->connection-details
    (fn [& args]
      (assoc (apply orig args)
             :host "abc"))))
```

**Comment by camsaul** [comment]
Closing since this is old and it's now pretty easy to set appropriate env vars to test against whatever DB you want
