### ISSUE TITLE
Allow usage of PKCS-12 certificates with Postgres connections

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14626]
Metabase is currently using [Postgres JDBC 42.2.8](https://github.com/metabase/metabase/blob/master/project.clj#L137), which only supports PKCS-8, while PKCS-12 was added since [42.2.9](https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.9):
https://jdbc.postgresql.org/documentation/head/ssl-client.html
> As of version 42.2.9 PKCS-12 is also supported. In this archive format the client key and the client certificate are in one file, which needs to be set with the sslkey parameter. For the PKCS-12 format to be recognized, the file extension must be ".p12" (supported since 42.2.9) or ".pfx" (since 42.2.16). (In this case the sslcert parameter is ignored.)

**Additional context**
Related to #13797

**Comment by robdaemon** [comment]
This should be resolved with #13797 in 0.38. I added the driver update yesterday.
