### ISSUE TITLE
Google Analytics updated Credentials aren't used for Connection

### ISSUE THREAD

**Issue by ntbm** [metabase/metabase#14624]
**Describe the bug**
Analytics Token ran into an error. Tried refreshing it, doesn't work. Configuring a new Database does work.

**To Reproduce**
1. Go to 'Databases'
2. Create new Google Analytics Configuration
3. Save it
4. Close the configuration and open it again
5. Put in an invalid Auth-Key
6. Save it. You get an Success-Message

**Expected behavior**
There should be an error, when creating an invalid updated Configuration or success when valid

**Screenshots**
![Bildschirmfoto 2021-02-02 um 12 01 33](https://user-images.githubusercontent.com/5088968/106591931-299e6400-654f-11eb-9e49-be3a31231c30.png)

**Information about your Metabase Installation:**
 ```
{"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.9.1+1-post-Debian-1deb10u2",
 "java.vendor" "Debian",
 "java.vendor.url" "https://tracker.debian.org/openjdk-11",
 "java.version" "11.0.9.1",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.9.1+1-post-Debian-1deb10u2",
 "os.name" "Linux",
 "os.version" "4.19.0-13-amd64",
 "user.language" "en",
 "user.timezone" "Europe/Berlin"}
```

**Severity**
Have many Google Analytics Questions i have to change now, because i see no way of correcting the credentials with this interface. Also Troubleshooting is a mess, when you don't get the correct answers

**Comment by flamber** [comment]
Hi @ntbm 
Please post the entire "Diagnostic Info" from Admin > Troubleshooting.
See #14578 for a workaround.

**Comment by ntbm** [comment]
```
{
  "browser-info": {
    "language": "de-DE",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1-post-Debian-1deb10u2",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1-post-Debian-1deb10u2",
    "os.name": "Linux",
    "os.version": "4.19.0-13-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-26",
      "tag": "v0.37.8",
      "branch": "release-x.37.x",
      "hash": "490cea7"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

I could solve my problem with the workaround. Thanks

**Comment by ntbm** [comment]
Additional Insight, because it happened again, while still using h2 as Database.
I needed to remove the refresh Token in the Table and save the Database again.
From my point of you it seems like there's some problem while updating the refresh Token.
We migrated to mysql as application database now. So i hope the problem doesn't appear again

**Comment by flamber** [comment]
@ntbm Thank you for the update. There shouldn't be a difference with which appdb you're using in regard to this, but still recommended not to use H2 in production.
It's a tricky bug to reproduce. I'm not quite sure what's going on, I'm still investigating.

**Comment by ntbm** [comment]
@flamber It happened again after even after switching to mysql like you guessed.

The `access-token` in the db is something i never put there.
Also i had to restart the metabase yesterday so maybe this relates.

**Comment by flamber** [comment]
@ntbm 
Did someone edit the GA database in Admin > Databases? Any type of edit, name change etc.
Are you talking about the `access-token` in `setting` table or the one in the GUI in Admin > Databases? If GUI, then the actual token will not be shown anymore and what you see is just a placeholder (example text).
So the problem only starts after you have restarted the instance? You are only using 1 instance, right?

**Comment by ntbm** [comment]
@flamber 
> Did someone edit the GA database in Admin > Databases? Any type of edit, name change etc.

No nobody touches this config as long as it works.

>Are you talking about the access-token in setting table or the one in the GUI in Admin > Databases? If GUI, then the actual token will not be shown anymore and what you see is just a placeholder (example text).

I was talking about `metabase_database.details`, but that doesn't seem the issue, because I fixed the issue and the data is again not really recognizeable. So i guess `access-token` in UI and the Database are diferent things

>So the problem only starts after you have restarted the instance? You are only using 1 instance, right?

We are only using one instance. I cannot guarantee that it's only happening in this case, because i think it was happening without restarts earlier?
I'll see if i have some time to try reproducing it that way.

**Comment by flamber** [comment]
@ntbm _Mixup with setting reference, sorry. I meant metabase_database.details._
When you say the data in `details` is unrecognizable, do you mean you cannot read any of it? Because then it sounds like you're using encryption: https://www.metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html

**Comment by ntbm** [comment]
@flamber I can recognize "account-id", "client-id" and "client-secret" as things I configured in the UI. The value of "access-token" is something completely different  than I put in though

**Comment by flamber** [comment]
@ntbm Pretty sure that access-token and refresh-token are cycled automatically behind the scenes:
https://github.com/metabase/metabase/blob/master/modules/drivers/google/src/metabase/driver/google.clj#L71-L91
Do you have logs for the period when it moved from working to not-working? I would guess that there should be something there indicating if token retrieval failed for some reason (perhaps API limit?).
There's no errors/warnings in console.developers.google.com about anything related to this?

**Comment by ntbm** [comment]
@flamber It happened again without a restart
Have logs now. If you tell me want i should grep i'll happily provide this part of the logs

**Comment by ntbm** [comment]
I also checked for API Limit and errors on the console. Nothing there.

**Comment by flamber** [comment]
@ntbm I'm not sure what I'm looking for, so please attach the entire log. Anything that involves that database and somewhere between it working and not working.

**Comment by ntbm** [comment]
[metabase-2021-03-02.ga.fail.log](https://github.com/metabase/metabase/files/6068604/metabase-2021-03-02.ga.fail.log)

I don't know the specific time it happened.

**Comment by ntbm** [comment]
@flamber please ping me, when you got the file. I'd like to not have it public on the web forever :)

**Comment by flamber** [comment]
@ntbm Downloaded it - seeing multiple unrelated problems.
Which database (the ID) is not refreshing the token correctly? I can see multiple GA databases.
I have a feeling that's the issue, where multiple GA databases somehow messes up the token refreshes for each other.

**Comment by flamber** [comment]
@ntbm I'm seeing at least two GA setups - ID 34 and 132 - it's the reference of `metabase_database.id`, which contains all the info you have defined in Admin > Databases. When you go into one of the databases, then the URL is `/admin/databases/321` which is the reference of the ID.

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/14578
