### ISSUE TITLE
Adding custom maps should provide better error handling

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14635]
See comments for workarounds that will likely make it work in all situations (multi-instances, forgot name before URL).
https://github.com/metabase/metabase/issues/14635#issuecomment-805761420

Repro:

1. Go to `admin/settings/maps`
2. Click "Add a map"
3. If you put in a URL that's not good GeoJSON the message is bad:

![image](https://user-images.githubusercontent.com/784417/105745285-bb7cf000-5f03-11eb-857e-aafff66586b7.png)

And if you put in a garbage value it's worse:

![image](https://user-images.githubusercontent.com/784417/105745343-c899df00-5f03-11eb-96a2-4a3b970ebed5.png)

And if you leave out the map name (which is required) it doesn't say anything:

![image](https://user-images.githubusercontent.com/784417/105745422-dbacaf00-5f03-11eb-9740-e6a345ad9a16.png)

_Originally posted by @tsmacdonald in https://github.com/metabase/metabase/issues/4506#issuecomment-766998773_

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
On our internal instance, adding this causes an error first time, but clicking Load again, then it works.
`https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/brazil-states.geojson`
Very likely related to #13270

**Comment by flamber** [comment]
Seems like on some instances (Heroku specific?) that it cannot add any custom maps at all - it also fails with error since 0.37.7 and the logs are not providing enough information on why it fails.

**Comment by flamber** [comment]
Possible workaround for multi-instance behind a load-balancer:

1. Admin > Settings > Maps > Add a map
2. Give it a name and input a URL and click Load - it now errors with "Invalid custom GeoJSON ..."
![image](https://user-images.githubusercontent.com/1447303/112305486-0a929780-8c9f-11eb-8659-fa6958212178.png)
3. Do a browser refresh on the page - do **not** click "Cancel" button
4. It has now added the map even though the identifiers wasn't set - if you don't see the map, then wait 1minute more and do another browser refresh (because of #13270)
![image](https://user-images.githubusercontent.com/1447303/112305738-59d8c800-8c9f-11eb-81fb-f0db6c3403f5.png)
5. Click on the map to open the editing modal - it should load the map now and allow setting the identifiers, but if it doesn't, then try waiting 1 minute and then inputting the URL again and clicking Load/Refresh-button
![image](https://user-images.githubusercontent.com/1447303/112305994-9c020980-8c9f-11eb-8a8b-edbab04ff757.png)

**Comment by LarissaGuder** [comment]
Any prevision?
