### ISSUE TITLE
Troubleshooting Tasks pagination not working anymore

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14636]
**Describe the bug**
Troubleshooting Tasks pagination not working anymore. Regression since 0.37.1

**To Reproduce**
1. Admin > Troubleshooting > Tasks > click the upper-right arrows - nothing happens
![image](https://user-images.githubusercontent.com/1447303/106741348-d6deae00-661b-11eb-8831-ca209202da95.png)
When the page is loaded, then there's three requests:
```
/api/database
/api/task?limit=50&offset=0
/api/database?limit=50&offset=0
```
Viewing the page on 0.37.0.2, there's only two requests and the pagination is working:
```
/api/database
/api/task?limit=50&offset=0
```

**Information about your Metabase Installation:**
Tested 0.37.1 thru 0.38.0-rc4

**Severity**
Giving P2, since I wasted a lot of time trying to debug a pulse problem.

**Comment by nemanjaglumac** [comment]
What I'm seeing in broken version:
_IconWrapper container is getting the `disabled` attribute from somewhere_ 🤨 
![image](https://user-images.githubusercontent.com/31325167/106793097-52118580-6657-11eb-9c59-93c3fb92609b.png)

vs.

How it looked when pagination worked
![image](https://user-images.githubusercontent.com/31325167/106793167-69e90980-6657-11eb-8642-adcb8a8f6f3f.png)

**Comment by flamber** [comment]
Fairly sure it gets disabled because of the extra request, which shouldn't exist, but also has <50 items (at least on my system)
