### ISSUE TITLE
Add a lightweight notify api endpoint

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#14634]
**Is your feature request related to a problem? Please describe.**
Right now we have an endpoint that ETL processes can hit when a table or database has been updated. This triggers a full sync (including field values fetching). For large data warehouses this can be very wasteful.

**Describe the solution you'd like**
For nightly processes that add rows and potentially columns but work with very large tables, we should offer a lightweight version of this that only does a sync.

**Additional context**
https://github.com/metabase/metabase/blob/master/src/metabase/api/notify.clj#L9 is the entry point, and I think having a GET param or a separate endpoint both work.

**Comment by flamber** [comment]
Related to #5500
