### ISSUE TITLE
Using "Reset to defaults" on textbox causes it to become a corrupted card on dashboard

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14644]
**Describe the bug**
Using "Reset to defaults" on textbox causes it to become a corrupted card on dashboard.

**To Reproduce**
1. Go to a dashboard > Edit > Add textbox
2. Hover textbox card > Visualization options (palette-icon) > "Reset to defaults" (already shows a spinner after click) > Done
The card will just show a spinner. And cannot be removed - there's no card hover actions.
![image](https://user-images.githubusercontent.com/1447303/106819844-a712c300-667a-11eb-89a9-1db027530370.png)
3. Save dashboard - do a browser refresh
4. Now the card is shown with a permission error `Sorry, you don't have permission to see this card.`
And cannot be removed - there's no card hover actions.
![image](https://user-images.githubusercontent.com/1447303/106820024-f658f380-667a-11eb-8585-d5a304fa404b.png)

The only way to get rid of the card is to find the card ID in the dashboard request or application database `report_dashboardcard`
And then run the following browser console command - replace host and `:id`s with appropriate dashboard/card ID:
```
await fetch("https://metabase.example.com/api/dashboard/:id/cards?dashcardId=:id", {
    "credentials": "include",
    "headers": { "Content-Type": "application/json" },
    "method": "DELETE",
    "mode": "cors"
});
```

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.38.0-rc4

**Severity**
Giving P2, since it's very difficult to remove the card since 0.37.0, when hover states where removed to avoid other issues, but perhaps remove-card-button should always be there?

A bit related to #14597, since "Reset to defaults" is too aggressive.

**Comment by paulrosenzweig** [comment]
Closed by #14667
