### ISSUE TITLE
Trying to use a pivot action on a scalar in an x-ray results in a broken visualization

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14648]
This is on `master`.

- Do an x-ray on a table in the sample dataset, like orders
- Click on the value `18,760` and select a Category or Time breakout, like `Source`
- You'll arrive at a visualization that has "forgotten" what its breakout should be.

Curiously, if you break out by a location, like State, you won't encounter this behavior. 🤷🏼 

![forgets-breakout](https://user-images.githubusercontent.com/2223916/106827320-7d877680-663d-11eb-8c6d-d93dca4eb6c2.gif)

**Comment by flamber** [comment]
Related to #10493

**Comment by markbastian** [comment]
When you click on the value `18,760` and select the `Source` breakout as @mazameli explains, you are redirected to a view with a single POST to http://localhost:3000/api/dataset with the following payload:

```json
{"database":1,"query":{"aggregation":[["count"]],"breakout":[["field",45,{"source-field":43}]],"source-table":2},"type":"query","parameters":[]}
```

This can be parameterized and evaluated as:

```clojure
(mt/dataset sample-dataset
  (->>
    {:database   (mt/id)
     :query      {:aggregation  [["count"]]
                  :breakout     [["field" 
                                  (mt/id :people :source) 
                                  {:source-field (mt/id :orders :user_id)}]]
                  :source-table (mt/id :orders)}
     :type       "query"
     :parameters []}
    qp/process-query
    :data
    :rows))
;; => [["Affiliate" 3520] ["Facebook" 3906] ["Google" 3798] ["Organic" 3764] ["Twitter" 3772]]
```

As shown in the output, this does return the correct data. Clicking on the visualization gear and "Add series breakout" fixes the UI, but there is no network activity. This leads me to believe that either this is a FE bug unless the response to the `http://localhost:3000/question#stuff` (stuff looks like some base64 encoded data) endpoint specifies some visualization setting that is missing.

**Comment by markbastian** [comment]
The default url ("stuff") above contains the following base-64 encoded data:

```clojure
(def decode-base64-json
  (comp #(json/decode % keyword) codecs/bytes->str codec/base64-decode))

(decode-base64-json
"eyJuYW1lIjoiVG90YWwgdHJhbnNhY3Rpb25zIiwiZGVzY3JpcHRpb24iOm51bGwsImRhdGFzZXRfcXVlcnkiOnsiZGF0YWJhc2UiOjEsInF1ZXJ5Ijp7ImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiw0NSx7InNvdXJjZS1maWVsZCI6NDN9XV0sInNvdXJjZS10YWJsZSI6Mn0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoiYmFyIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOltdLCJncmFwaC5tZXRyaWNzIjpbImNvdW50Il0sImdyYXBoLnNlcmllc19sYWJlbHMiOlsiTnVtYmVyIG9mIG9yZGVycyJdfX0=")

;; This decodes to
{:name "Total transactions",
 :description nil,
 :dataset_query {:database 1,
                 :query {:aggregation [["count"]]
                         :breakout [["field" 45 {:source-field 43}]]
                         :source-table 2},
                 :type "query"},
 :display "bar",
 :displayIsLocked true,
 :visualization_settings {:graph.dimensions []
                          :graph.metrics ["count"]
                          :graph.series_labels ["Number of orders"]}}
```

After clicking on the visualization gear and "Add series breakout" the base 64 encoded string changes, with the following result:

```clojure
(decode-base64-json
"eyJuYW1lIjoiVG90YWwgdHJhbnNhY3Rpb25zIiwiZGVzY3JpcHRpb24iOm51bGwsImRhdGFzZXRfcXVlcnkiOnsiZGF0YWJhc2UiOjEsInF1ZXJ5Ijp7ImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiw0NSx7InNvdXJjZS1maWVsZCI6NDN9XV0sInNvdXJjZS10YWJsZSI6Mn0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoiYmFyIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsiU09VUkNFIl0sImdyYXBoLm1ldHJpY3MiOlsiY291bnQiXSwiZ3JhcGguc2VyaWVzX2xhYmVscyI6WyJOdW1iZXIgb2Ygb3JkZXJzIl0sImdyYXBoLnNlcmllc19vcmRlcl9kaW1lbnNpb24iOm51bGwsImdyYXBoLnNlcmllc19vcmRlciI6bnVsbH19")

{:name "Total transactions",
 :description nil,
 :dataset_query {:database 1,
                 :query {:aggregation [["count"]]
                         :breakout [["field" 45 {:source-field 43}]]
                         :source-table 2},
                 :type "query"},
 :display "bar",
 :displayIsLocked true,
 :visualization_settings {:graph.dimensions ["SOURCE"],
                          :graph.metrics ["count"],
                          :graph.series_labels ["Number of orders"],
                          :graph.series_order_dimension nil,
                          :graph.series_order nil}}
```

The `:visualization_settings` now contain the right dimensions and labels. This change happens in the FE (again, no network activity).

**Comment by markbastian** [comment]
The above leads me to believe this is a FE change and when the reroute to the `/question` page in the application occurs the proper `:graph.dimensions` and `:graph.series_labels` are needed.

**Comment by markbastian** [comment]
Also noticed we get errors in the js console
<img width="1157" alt="image" src="https://github.com/metabase/metabase/assets/8381441/b69f5fe8-42fc-4ccd-857f-f7cde2b5a4ce">

**Comment by markbastian** [comment]
I was able to reproduce this last week, but as of today, it seems to behave as expected on both master and in stats. @ranquild or @mazameli, would either of you mind seeing if you can reproduce this now?

**Comment by markbastian** [comment]
One more recording that reproduces the selection that @mazameli made:
![14648-user-source](https://github.com/metabase/metabase/assets/8381441/4e65214c-3118-429b-b20f-4202ff209fda)

**Comment by oisincoveney** [comment]
Reproduced on v0.38 (which contains the last commit from `git rev-list -1 --before="2021-02-04 12:00" master`).



![Image](https://github.com/metabase/metabase/assets/25306947/2c61e771-495a-48cf-88f8-e05d552c26b9)




Reproduced on the latest version of `metabase/metabase` as well. 
![Image](https://github.com/metabase/metabase/assets/25306947/f3729193-c092-4fee-91cb-93a97bbdb082)

_**However**_ I am not able to reproduce it on a freshly pulled master branch nor stats (to corroborate @markbastian's comments earlier).

**Comment by uladzimirdev** [comment]
@markbastian you'll be surprised, but seems https://github.com/metabase/metabase/pull/34258 fixed the issue
