### ISSUE TITLE
Upgraded to latest docker image (0.37.8) from 0.36.3… Metabase won't start

### ISSUE THREAD

**Issue by mhjb** [metabase/metabase#14657]
Metabase stalls on launch. I've recently added one more MongoDB database, for a total of four now. I started a new Metabase container in the course of attempting to get my reports showing in my timezone.

My docker run command is:

`docker run -d -p 3000:3000 -v ~/metabase-data:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db" -e "JAVA_TIMEZONE=Pacific/Auckland" -e "JAVA_TOOL_OPTIONS=-Xmx1g" --name metabase metabase/metabase`

Metabase stalls at various points, often here:

![image](https://user-images.githubusercontent.com/1380991/106859415-de8b7900-6727-11eb-9947-94d007ec99fe.png)

**Information about your Metabase Installation:**

- Ubuntu 18.04.4 LTS on Digital Ocean
- H2 internal database

**Comment by flamber** [comment]
Hi @mhjb 
The screenshot does not show a stall. Sync+scan are tasks that run after Metabase has started.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by mhjb** [comment]
Sorry for wasting your time, @flamber
