### ISSUE TITLE
Data Model page busted if you visit a database that doesn't exist

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14652]
Probably an edge case, but we should make sure pages don't look insane if there isn't anything to display. It seems like it's not handling 404 (or other error) responses from the backend correctly. 

![image](https://user-images.githubusercontent.com/1455846/106838007-56867000-6650-11eb-80c5-5e5df429bb2c.png)

Steps to repro 

1. Visit data model page in admin panel
2. Delete the database from the REPL or another tab
3. Hit refresh on data model page
4. B R O K E N

**Comment by flamber** [comment]
Related to #11037
