### ISSUE TITLE
Admin user last login date is in the future (timezone error)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14654]
Users last logged in in the future?

![image](https://user-images.githubusercontent.com/1455846/106838577-6d799200-6651-11eb-98e5-672dc9a1b766.png)

Time travel is an enterprise-only feature. I'm guessing this has something to do with `user.last_login` being a `TIMESTAMP` as opposed to a `TIMESTAMP WITH TIME ZONE`... looks like it's off by 8 hours since I'm in PST

**Comment by flamber** [comment]
I'm not sure how to reproduce, but perhaps related to #12379

**Comment by noahmoss** [comment]
Here's a similar bug. Probably the same root cause so not sure if it's worth opening a separate issue.

When you deactivate a user, then switch to the "Deactivated" tab, it shows them as having been deactivated "in 4 hours".

**Comment by qwef** [comment]
See: https://github.com/metabase/metabase/pull/37160
