### ISSUE TITLE
Password reset unit test broken on MySQL backing DB

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1466]
It looks like the password reset code has indeterminate behavior when using a MySQL backing DB.

This test is randomly failing on unrelated branches:

```clojure
failure in (user_test.clj:218) : metabase.api.user-test
(expect
 (let
  [{user-id :id} (sel :one User :last_name user-last-name)]
  (sel
   :one
   :fields
   [Session :id]
   :user_id
   user-id
   (k/order :created_at :desc)))
 (let
  [password
   {:old "password", :new "whateverUP12!!"}
   {:keys [email id], :as user}
   (create-user :password (:old password) :last_name user-last-name)
   creds
   {:old {:password (:old password), :email email},
    :new {:password (:new password), :email email}}]
  (metabase.http-client/client :post 200 "session" (:old creds))
  (metabase.http-client/client
   (:old creds)
   :put
   200
   (format "user/%d/password" id)
   {:password (:new password), :old_password (:old password)})
  (assert
   (=
    (metabase.http-client/client :post 400 "session" (:old creds))
    {:errors {:password "did not match stored password"}}))
  (metabase.http-client/client :post 200 "session" (:new creds))))

           
expected:
 {:id "4a03892a-4bde-43fa-8672-b8eb7fd614cf"}
 
was:
 {:id "c84c717d-a6a5-42e7-8cef-c7ac65be34a6"}
```

MySQL has a bag of shits and isn't giving any of them when it comes to working the way other SQL DBs do. So I'm guessing this is case of MySQL behaving differently than H2 or Postgres in the password reset code. We need to rework that code in a way that can make everybody happy :disappointed:

**Comment by camsaul** [comment]
This is a huge issue. I'm seeing my tests fail on unrelated branches over 50% of the time because of this

**Comment by agilliland** [comment]
sure, i'll take a look at this.  the problem is that MySQL datetimes don't have millisecond granularity, which isn't a practical issue for the code but for the unit test it's a problem because lots of things are all happening within a single second.

this is being compounded by the fact that our unit tests don't run in isolation like i mentioned, so there is other data floating around in the db which is allowing this problem to manifest itself.

**Comment by camsaul** [comment]
Could be something like MySQL using lower resolution timestamps than H2 or Postgres

**Comment by agilliland** [comment]
Just to confirm, this is not an issue with the functionality working, this is only an issue with the unit test.  Going to adjust the title to make that more clear.
