### ISSUE TITLE
Sandbox modal "cancel" doesn't work correctly

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14669]
![sandbox bad FE 2](https://user-images.githubusercontent.com/1455846/106970009-dbc95d80-6700-11eb-9b24-e830391d25ce.gif)

Click cancel, and it still shows that the column is sandboxed, and that changes have been made. Try to edit again, and the context menu pops up and stays there forever.

**Comment by nemanjaglumac** [comment]
This happens because you're still editing tables. It goes away when you click "Cancel" next to the "Save Changes" button in `You've made changes to permissions`.

**Comment by mazameli** [comment]
My strong expectation is that when you click Cancel in that sandboxing modal, any changes you made should be immediately discarded. So if the table was previously set to Unrestricted access, it should revert to that upon Cancel. It should not show up as Sandboxed.
