### ISSUE TITLE
Mysql database connection failed

### ISSUE THREAD

**Issue by Jzow** [metabase/metabase#14677]
I use docker to run，But when I add a database and click the Save button, it prompts me that the connection is abnormal. There is a MySQL database in my docker

```
Could not connect to address=(host=192.168.20.23)(port=3306)(type=master) : Socket fail to connect to host:47.114.1.215, port:3306. No route to host (Host unreachable)
```

**Comment by Jzow** [comment]
I want to know where to read the log

**Comment by Jzow** [comment]
error mesage：Remote host terminated the handshake

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
