### ISSUE TITLE
Clicking away from Sandbox modal breaks perms page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14671]
Click the background, and you're in for a world of pain

![don't click out](https://user-images.githubusercontent.com/1455846/106970236-4a0e2000-6701-11eb-95ea-eced5c040491.gif)

**Comment by flamber** [comment]
Closing sandbox grant modal shows `We're a little lost...` error page, when **not** using "Cancel" button to close it, but with `Esc` key or mouse-click outside of dialog.

**To Reproduce**
1. Go to Admin > Permissions > Sample Dataset (View tables) > Orders > Grant sandboxed access
2. The modal should now be open and the URL is changed to:
`/admin/permissions/databases/:id/schemas/PUBLIC/tables/:id/segmented/group/:id`
3. Hit `Esc` key or mouse-click outside of dialog gives throws `We're a little lost...` error page and the URL is change to:
`/admin/permissions/databases/:id/schemas/PUBLIC/tables/:id/segmented/group`
4. Repeating step 1 and clicking "Cancel" in the modal changes the URL correctly to:
`/admin/permissions/databases/:id/schemas/PUBLIC/tables`
