### ISSUE TITLE
user@password JDBC connection strings for application DB no longer work

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14678]
**Describe the bug**
Startup stalls at "Database setup took ..." when application database JDBC URI uses format like `username:password@host:port` which reads `password@host` as the port, or `username@host:port/db?password=password` which reads `username@host` as the host, but only after migrations has been executed successfully.
Used to work on 0.37.8

**Workaround** Set user and password in the URI parameters - example:
`MB_DB_CONNECTION_URI="mysql://172.17.0.2:3306/metabase?user=myuser&password=mypass"`

**To Reproduce**
1. Start Metabase with something like this (applicable for `postgres://` too) against an empty database:
`MB_DB_CONNECTION_URI="mysql://myuser:mypass@172.17.0.2:3306/metabase"` or
`MB_DB_CONNECTION_URI="mysql://myuser@172.17.0.2:3306/metabase?password=mypass"`
2. It will run through all the migrations, but then it stalls at `Database setup took ...`:
```
...
2021-02-05 12:19:19,224 INFO db.data-migrations :: Running data migration 'migrate-field-types'...
2021-02-05 12:19:19,473 INFO db.data-migrations :: Running data migration 'fix-invalid-field-types'...
2021-02-05 12:19:19,490 INFO db.data-migrations :: Running data migration 'copy-site-url-setting-and-remove-trailing-slashes'...
2021-02-05 12:19:19,503 INFO db.data-migrations :: Running data migration 'ensure-protocol-specified-in-site-url'...
2021-02-05 12:19:19,515 INFO db.data-migrations :: Running data migration 'populate-card-database-id'...
2021-02-05 12:19:19,533 INFO db.data-migrations :: Running data migration 'migrate-humanization-setting'...
2021-02-05 12:19:19,541 INFO db.data-migrations :: Running data migration 'mark-category-fields-as-list'...
2021-02-05 12:19:19,560 INFO db.data-migrations :: Running data migration 'add-legacy-sql-directive-to-bigquery-sql-cards'...
2021-02-05 12:19:19,573 INFO db.data-migrations :: Running data migration 'clear-ldap-user-local-passwords'...
2021-02-05 12:19:19,592 INFO db.data-migrations :: Running data migration 'add-migrated-collections'...
2021-02-05 12:19:19,651 INFO db.data-migrations :: Finished running data migrations.
Database setup took 45.3 s
```
3. After a while it will then fail with the following:
`Caused by: java.sql.SQLException: error parsing url : Incorrect port value : mypass@172.17.0.2` or
`Caused by: java.net.UnknownHostException: myuser@172.17.0.2`

**Information about your Metabase Installation:**
Metabase 0.38.0-rc4

Likely caused by #14275. History #7345. Not exactly related, but similar lack of logging on why it's stalling #10709

**Comment by rlotun** [comment]
this will apparently break a lot of customers using the other style of JDBC URI cc/ @camsaul @robdaemon @kidd. any ideas?

**Comment by camsaul** [comment]
I know a lot of DBs don't actually support `username:password@host:port`, I'm pretty sure Postgres doesn't for example

**Comment by flamber** [comment]
Okay, it works on 0.37.8

**Comment by camsaul** [comment]
< 38 we tried to parse the connection URL ourselves, the problem was that was fragile and didn't support a lot of weird syntax that respective DBs are totally fine with. In 38+ we're not parsing the connection URL ourselves any more. So if you were using one that wasn't actually a valid JDBC URL it might have worked in the past by accident because of the way we parsed it.

I think this is similar to the NonValidatingFactory thing -- maybe we should make people aware of this change, so if they happened to be using `MB_DB_CONNECTION_URI` with an invalid JBDC URL they'll have to fix that? I don't think we'd want to revert the change entirely because I think parsing the URI causes more problems than it's worth. We only parsed it in the first place because MB didn't work with plain JDBC URLs for the application DB at first

**Comment by camsaul** [comment]
I think in the long run it's going to save us a lot of pain if we tell people we support anything that is supported by JDBC or any other application that uses JDBC, as opposed to telling people that (which we were) but actually only supporting whatever it was we could parse from the connection string

**Comment by rlotun** [comment]
Given that it used to work and can cause problems, could we have a special test for this specific condition and emit a warning message to the log indicating "you should set username and password in the MB_CONNECTION_URI like so ..." but just parse one or both of those strings (username and pass) and use them as needed (as long as username and password aren't also in the uri params)?

I think the biggest problem is that metabase fails to start up at all with no information.

**Comment by camsaul** [comment]
Yeah, we should definitely print the warning as a giant banner for cases where that happens, at the very least. We could consider reverting the code that removed the parsing and trying to parse and piece it together ourselves if we detect that format and then print a giant warning telling people we will remove it in the next release?

**Comment by dpsutton** [comment]
I had brought up some kind of notion of "needs attention" before but i've never made an issue for it. But if there was a separate section similar to the logs in the administration area for concrete things that require some action or human intervention. Things like syncs failing because they can't talk to databases, etc.

**Comment by flamber** [comment]
@dpsutton You might be interested in #4350

**Comment by flamber** [comment]
I still don't understand how we're connecting correctly, verifying the connection, running migrations, and then somehow change the connection by re-reading the URI again in a different way, which then fails.
Have a feeling this is related to some "lockups" I have seen, where restarting both Metabase and the appdb fixed their problem.

But in any case, we should also update our docs to not reflect the old behavior: https://github.com/metabase/metabase/blob/release-x.38.x/docs/operations-guide/environment-variables.md#mb_db_connection_uri

**Comment by camsaul** [comment]
> I still don't understand how we're connecting correctly, verifying the connection, running migrations, and then somehow change the connection by re-reading the URI again in a different way, which then fails.

I think `clojure.java.jdbc` itself might also be attempting to parse the connection URL to make `user@password` connection URLs work. That could explain why we're able to connection and run migrations. But then later other stuff that bypasses `clojure.java.jdbc` and passes in the URL directly to JDBC is running in to issues.

**Comment by camsaul** [comment]
https://github.com/metabase/metabase/pull/14275 was the PR where we made the change to stop parsing app DB connection URLs ourselves... to fix this we should definitely log a big warning if we see the `user@password` format and tell people it's unsupported or will be unsupported in the future. I think `clojure.java.jdbc` itself actually parses these URLs so maybe we can leverage that if we see this format so it continues to work for the time being

**Comment by camsaul** [comment]
I think we can just change this code here: https://github.com/metabase/metabase/blob/master/src/metabase/db/env.clj#L53-L59 to handle things correctly and/or log the warning... and that should do it

**Comment by camsaul** [comment]
Our old parsing code is this: https://github.com/metabase/metabase/blob/1f6d5fa35a5e0f2e0a51bc0bfc077c5ccc2da309/src/metabase/db.clj#L53-L88
