### ISSUE TITLE
support postgresql foreign data wrappers

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1468]
specifically, foreign tables. these are provided by extensions like `postgres_fdw` to allow querying remote databases and other data sources. docs: http://www.postgresql.org/docs/9.3/static/postgres-fdw.html

only medium priority for us. we're currently working around it with hand-defined views, which metabase does support. (yay.) this would still be nice though!

**Comment by samgaw** [comment]
+1

**Comment by orlando** [comment]
@snarfed Thanks for the tip on views, I thought this feature was implemented and didn't know why tables weren't showing up

**Comment by tlrobinson** [comment]
I think all we need to do to support this is add the `FOREIGN TABLE` type to this line, or perhaps override it for the postgres driver only: https://github.com/metabase/metabase/blob/f13be5c6ca5c86d171a9a911837df7e2d6875f84/src/metabase/driver/generic_sql.clj#L321

@camsaul does that seem right?

**Comment by orlando** [comment]
@tlrobinson Oh cool, I thought it was a postgres specific thing. I was thinking taking the same approach as https://github.com/metabase/metabase/pull/2559/commits/4e52520a2aa46374f877a1c29fd348b7c9074d75

**Comment by tlrobinson** [comment]
Oh I didn't see that PR. I'm not sure how other dbs behave, but I wonder if adding `MATERIALIZED VIEW` to the `getTables` call would have been an easier solution. Here are the supported types that PG's `getTableTypes` returns, FYI:

```
({:table_type "FOREIGN TABLE"}
 {:table_type "INDEX"}
 {:table_type "MATERIALIZED VIEW"}
 {:table_type "SEQUENCE"}
 {:table_type "SYSTEM INDEX"}
 {:table_type "SYSTEM TABLE"}
 {:table_type "SYSTEM TOAST INDEX"}
 {:table_type "SYSTEM TOAST TABLE"}
 {:table_type "SYSTEM VIEW"}
 {:table_type "TABLE"}
 {:table_type "TEMPORARY INDEX"}
 {:table_type "TEMPORARY SEQUENCE"}
 {:table_type "TEMPORARY TABLE"}
 {:table_type "TEMPORARY VIEW"}
 {:table_type "TYPE"}
 {:table_type "VIEW"})
```

**Comment by orlando** [comment]
@tlrobinson that's neat, if we add that to the generic_sql, in the works case the other databases that don't support `MATERIALIZED VIEW` and/or `FOREIGN TABLE` will return nothing right?.

Or you think it's better to create an interface that returns non generic table types for each driver?

**Comment by camsaul** [comment]
@tlrobinson you're linking to all the possible types that a JDBC driver can return, not what the Postgres JDBC driver supports specifically. Last time I checked the Postgres JDBC driver didn't support materialized views so we have to fetch them in a separate query, here:

https://github.com/metabase/metabase/blob/master/src/metabase/driver/postgres.clj#L181

the query is:

```sql
SELECT schemaname AS "schema", matviewname AS "name" FROM pg_matviews;
```

We could probably do something similar for foreign tables. Do you guys know how a similar query would look?

**Comment by camsaul** [comment]
To be honest I'm not familiar with PG foreign data wrappers other than hearing the phrase a few times so if you guys can give me an idea of what use cases you have for them it would be super-helpful 👍

**Comment by orlando** [comment]
![image](https://cloud.githubusercontent.com/assets/849872/18847200/e350290c-83ee-11e6-893b-f62f747e2137.png)

FOREIGN TABLES are included in the schema (select * from information_schema.tables) (unlike MATERIALIZED VIEWS)

So the easiest way to do it will be adding the `FOREIGN TABLE` to https://github.com/metabase/metabase/blob/f13be5c6ca5c86d171a9a911837df7e2d6875f84/src/metabase/driver/generic_sql.clj#L321

**Comment by orlando** [comment]
@camsaul about the use cases, I'm using them to proxy external databases as local ones. I have multiple databases (one for each microservice), and instead of using ETL scripts, I'm just using foreign data wrappers to connect the "analytics" database to metabase

**Comment by tlrobinson** [comment]
Yeah I tried this out and adding `FOREIGN TABLE` to the `getTables` call **does** work for postgres. I don't think it will hurt to include for other dbs too, and if it does I'm guessing our tests should catch any problems, so I went ahead and created a PR to see if it passes CI at #3397.

**Comment by camsaul** [comment]
👍 
AFAIK it shouldn't cause problems for other databases that don't support them.
