### ISSUE TITLE
Import an Excel as a table into one of the databases;

### ISSUE THREAD

**Issue by AlexSeven77** [metabase/metabase#14700]
Thank you for the Great Meatabase.

Sometimes,  it could be of great convenience to us to import our Excel file as a new table in our databases through metabase directly, instead of creating the table first and then inserting all the data from the excel.

**Comment by flamber** [comment]
Going to close this in favor of #6094, since until something like that is supported, then there's very little chance we'll handle advanced formats like XLSX.
Check the comments, there are several workarounds, but requires the data is available in CSV format.
