### ISSUE TITLE
Publish "latest" OSS JAR

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14707]
We do this for EE. We also have `latest` Docker images. Should be a minor change to the release script

**Comment by flamber** [comment]
This used to work for more than a year - #5252

**Comment by camsaul** [comment]
Yeah, I guess Tom old release script was updating `latest`. I must have missed that part of the build script when I ported it to Clojure

**Comment by rlotun** [comment]
Fixed by https://github.com/metabase/metabase/pull/14737
