### ISSUE TITLE
Select-all button is broken in collections footer

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14705]
When you select one or more items via the checkbox in a collection, you're supposed to be able to click the stacked checkbox icon in the footer that slides up so that you can do a select-all. Something happened in `master` and/or `release-x.38.x` (I tried both) that caused that button to break.

Tried on both Safari and Chrome. No JS console errors.

![select-all-safari](https://user-images.githubusercontent.com/2223916/107249335-20e2dd80-69e8-11eb-981d-b38c79e06e47.gif)

![select-all-chrome](https://user-images.githubusercontent.com/2223916/107249348-24766480-69e8-11eb-808c-a3ac73347270.gif)

**Comment by nemanjaglumac** [comment]
I don't think we have ANY e2e test coverage re: selecting collections using checkboxes.

**Comment by brunobergher** [comment]
Selecting even a single item for me right now is throwing an error on Chrome latest stable on v0.39.0-SNAPSHOT.

Uncaught TypeError: d is not a function at onToggleSelected (app-main.bundle.js:5) at S.c.default.createElement.c.default.createElement.onClick (app-main.bundle.js:5) at Object.<anonymous> (vendor.bundle.js:487) at h (vendor.bundle.js:487) at vendor.bundle.js:487 at g (vendor.bundle.js:487) at ot (vendor.bundle.js:487) at rt (vendor.bundle.js:487) at at (vendor.bundle.js:487) at ht (vendor.bundle.js:487)

Are tests test catching that?
