### ISSUE TITLE
Feature request: ability to easily print charts

### ISSUE THREAD

**Issue by s-boardman** [metabase/metabase#1472]
I've searched through the source, previous issues, and the documentation but can't find a way to print a chart cleanly. Using the browser print function isn't ideal as it often chops charts in half.

**Comment by mazameli** [comment]
@s-boardman sorry for how long it's taken us to reply to this. One way to kill two birds with one stone here would be to allow charts to be exported to PDF, which could then be printed easily.

**Comment by s-boardman** [comment]
@mazameli no problem, thanks for getting back to me, :smile:

PDF export would be a perfect solution!

**Comment by federicokeen** [comment]
Maybe just print to PDF the entire dashboard?

**Comment by jayrbolton** [comment]
Print to PDF doesnt work well. It could be easy to create a media-type "print" CSS version for dashboards: hide nav bar, hide buttons/UI, set layout to "landscape" and be responsive to that width. Then it would work well I think.

**Comment by tlrobinson** [comment]
@mazameli Making charts/dashboards print-friendly is actually a prerequisite for exporting to PDF, not the other way around (alternatively writing a bunch of custom rendering code like we have pusles, but that's a bad idea). Plus we'd have to figure out how to get a modern browser engine running in the backend (which would be awesome for pulse rendering as well, but not easy).

So yeah, I think just creating a print stylesheet is the way to go for now.

@s-boardman @federicokeen  @jayrbolton Just as a workaround and to get an idea of what it could be like, on dashboards if you hold down "option" while clicking fullscreen it hides the header, etc without going into fullscreen. If your browser allows you to disable backgrounds, and you size your browser window just right, you can get something pretty decent:

![screenshot 2016-10-20 17 11 28](https://cloud.githubusercontent.com/assets/18193/19582332/609c95c4-96e8-11e6-8945-4772c5ba9419.png)
<img width="1027" alt="screenshot 2016-10-20 17 12 13" src="https://cloud.githubusercontent.com/assets/18193/19582331/609c2d8c-96e8-11e6-8a8e-fac3645cb04f.png">

I'm thinking just adding a print stylesheet to make it look like this automatically when you try to print, with it automatically sized to fit, background color removed, and top right icons hidden would be a pretty good start. Anything else you'd like to see different?

For bonus points, there are other enhancements we might be able to do, like making sure cards aren't split across pages, or giving you more control over the layout (normal grid layout vs mobile layout, etc)

**Comment by mazameli** [comment]
Makes sense, Tom. 👍

**Comment by kdoh** [comment]
Implemented by #3670
