### ISSUE TITLE
Custom filter expression does not show editor properly on subsequent click

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#14726]
**Describe the bug**
In the notebook query editor, if a Filter is added with a Custom expression, and added, then that clause is clicked again, the editor that appears is not the correct one.

**Logs**
N/A

**To Reproduce**
1. Go to a Notebook question editor
2. Click on the + under Filter, in order to add a new filter clause
3. Select Custom expression from the dropdown, and enter some expression (ex: `between([ID], 96, 97)`); see screenshot 1
4. Click Done to add the clause
5. Click on the clause again (ex: to make a change)
6. Notice the dialog that appears is blank (doesn't show the expression value); see screenshot 2

**Expected behavior**
The same dialog that appears when adding the custom filter expression (ex: from step 3 above) should appear, and the custom expression that was already populated should be prefilled.

As a workaround, you can click the left/back arrow shown in the dialog header, then select Custom expression again, and the expression will again be editable there.

**Screenshots**

1. <img width="495" alt="Screen Shot 2021-02-09 at 1 35 43 PM" src="https://user-images.githubusercontent.com/3521562/107419654-a6948500-6add-11eb-830e-5a509f6f8e1b.png">
2. <img width="332" alt="Screen Shot 2021-02-09 at 1 35 48 PM" src="https://user-images.githubusercontent.com/3521562/107419665-aac0a280-6add-11eb-8737-3f4099df6cd6.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 88.0.4324.150
- Your operating system: OS X 11.1
- Your databases: Redshift
- Metabase version: `0.38.1-SNAPSHOT` (src_hash=`6d77f0992f5f51345554bc34338f05786f26c54b`)
- Metabase hosting environment: N/A
- Metabase internal database: H2

**Severity**
Minor.

**Additional context**
N/A

**Comment by jeff303** [comment]
Should perhaps be lumped in with #14214?

**Comment by flamber** [comment]
Very related to #12492

**Comment by ariya** [comment]
Is it related to the column type? Looks like `ID` is an entity key.

Doing it with a column of the number type seems to be OK:

1. Ask a question, Custom question
2. Sample Databaset, Review table
3. Filter, Custom Expression, and then enter `between([Product → Rating],3,4)`
4. Done
5. Click on the filter

The shown popover (I can't see what's wrong with it):
![image](https://user-images.githubusercontent.com/7288/107598217-02d8d100-6bd2-11eb-92b2-0df7914a1352.png)

**Comment by flamber** [comment]
@ariya It's because all PK/FK are now read as strings. Side-effect of some of the fixes that tried to fix #5816.
But I would very much prefer if a custom expression is being used, then that should be shown again when clicking the widget.

**Comment by rlotun** [comment]
Closed by https://github.com/metabase/metabase/pull/16238
