### ISSUE TITLE
In Settings > Email, “Save changes” button doesn’t enable until onBlur event

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14748]
UX Issue (not a regression): In Settings > Email, “Save changes” button doesn’t enable until `onBlur` event… I sat around confused for a minute or so wondering why I couldn’t save my email settings. This might be an issue with admin forms in general. Consider changing the checks for button enabling to the `onChange` event?

**Comment by flamber** [comment]
Duplicate of #12692
