### ISSUE TITLE
 In Settings > Email, Save Changes is enabled even when there are no changes

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14749]
In Settings > Email, Save Changes is enabled even when there are no changes, even after hitting save when no changes have been made… is this intentional? It seems to make me think the changes weren’t saved? Normally I think we only enable the Save button when there are actual changes to save.

**Comment by flamber** [comment]
Slightly related to #12692

**Comment by nemanjaglumac** [comment]
The same thing happens when you open SQL editor. Save button is there without any change.

**Comment by nemanjaglumac** [comment]
While we're at it, `user/edit_current` has the same behavior:
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/xQunnbZX/db9886dc-8179-4bcd-bf70-b2f0facdd93e.gif?source=viewer&v=77fddeb4ebc1eb34a3d5ad8b2f8ebbef)

It also fires an XHR for every "save".

**Comment by alxnddr** [comment]
Fixed in https://github.com/metabase/metabase/pull/15385
