### ISSUE TITLE
Second summary phase in query builder loses date resolution

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#14744]
**Describe the bug**
Adding another summary phase after a first summary phase, and using the same Group By clause (on a date column), the resolution of that date column is lost in the second phase.

**Logs**
N/A

**To Reproduce**
1. Ask a new question of the Orders table from the Sample Data Set. 
2. Click on Summarize to add a new summary phase
3. For the Summarize option, choose Sum of/Total
4. For the grouping (by) option, choose Created/by Year
5. Click the summarize button again to add a new summary phase after this one
6. For the Summarize option, choose anything (ex: just Count)
7. For the grouping (by) option, choose Created again (this time, there is no ability to select the Year resolution)
8. Click preview after this last summary phase, and notice that `Created At` has turned into day resolution instead of year (in this case, for January 1 of each year)

**Expected behavior**
The resolution of group columns should be preserved through subsequent summary phases.

**Screenshots**

<img width="1094" alt="multiple_summary_stage_issue" src="https://user-images.githubusercontent.com/3521562/107561006-a363cc80-6ba3-11eb-826b-0dfa9e2b081c.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 88.0.4324.150
- Your operating system: OS X 11.1
- Your databases: MySQL 8 (sample data from QA Docker image)
- Metabase version: 0.38-rc5
- Metabase hosting environment: N/A
- Metabase internal database: H2

**Severity**
Likely minor, since this seems like a fairly crazy use case.

**Additional context**

**Comment by flamber** [comment]
Looks like a duplicate of #13764

**Comment by jeff303** [comment]
Hmm, it seems as though saving the question is not a workaround here, as it is in #13764.

**Comment by flamber** [comment]
You need to use the question as a Saved Question - as the base of another question:
![image](https://user-images.githubusercontent.com/1447303/107568858-e5166680-6be7-11eb-950f-734e16d1c412.png)

**Comment by jeff303** [comment]
Closing as duplicate
