### ISSUE TITLE
Allow un-pinning of axis from 0 for automatic y-axis range

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#14742]
Automatic axis ranges can squash the interesting parts of a graph when we include 0 as the bottom of the range.

Manually setting the axis range is helpful, but when there is a filter on the question, it is not possible to predict the appropriate range. 

We should either do a better job of setting the range, or offer a way to toggle 0 pinning as the bottom of the y-axis.

**Comment by flamber** [comment]
Sounds like a duplicate of #7196
