### ISSUE TITLE
In Dashboard Subscription settings, checkboxes can get squished an unrecognizable

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#14754]
**Describe the bug**

**Logs**
N/A

**To Reproduce**
1. Add a question with a long title (eg the default suggested by Metabase) and add it to a dashboard
2. Go to that dashboard
3. Click on the share arrow and create a subscription
4. Turn on "Attach Results"
5. See issue

**Expected behavior**
The checkbox should be square-ish and look clickable.

**Screenshots**
<img src="https://user-images.githubusercontent.com/328388/107570104-f33f9500-6b9d-11eb-95d8-2fb579205e00.png" width="300">

**Information about your Metabase Installation:**
Metabase 0.38.0-rc5
Chrome 88.0.4324.146 (Official Build) (arm64)

**Severity**
P3. The feature is still usable, even if harder to discover and a bad experience.

**Comment by kulyk** [comment]
Can no longer be reproduced
