### ISSUE TITLE
Switching between languages results in mixed-language content

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#14758]
I set up a fresh Metabase in Spanish, then changed my language to English. This resulted in charts showing "Media de" instead of "Average of", even though the rest of the UI was in English:

![media-de-price](https://user-images.githubusercontent.com/784417/107571490-93061e80-6bb0-11eb-97aa-d19d4643145d.png)

I switched back to Spanish and got more weirdness on admin:

![admin](https://user-images.githubusercontent.com/784417/107571547-a9ac7580-6bb0-11eb-95ab-776f3b7386b2.png)

**Comment by flamber** [comment]
I cannot reproduce on a newly setup 0.38.0 in Spanish, creating some questions, then changing instance to English:
![image](https://user-images.githubusercontent.com/1447303/108507781-1ca5a280-72bb-11eb-8e1b-7f068f111a17.png)

And even back to Spanish again:
![image](https://user-images.githubusercontent.com/1447303/108507869-3d6df800-72bb-11eb-8c35-9e41221617f2.png)
