### ISSUE TITLE
Pivot Table cells should have a hover effect

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14751]
Looks like this was an oversight on my part once we implemented drill-through for pivot tables. We should add a hover state just like "normal" tables to indicate that you can click to open the drill-through/actions menu.

![table-hover](https://user-images.githubusercontent.com/2223916/107566359-a8bc1980-6b99-11eb-9891-7a1d879e5038.gif)

**Comment by flamber** [comment]
Related to #13548

**Comment by mazameli** [comment]
Fixed by #14763
