### ISSUE TITLE
LDAP auth errors with "did not match stored password" if `givenName` or `sn` is missing

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#14767]
**Describe the bug**
LDAP authentication currently is expecting `mail`, `givenName` and `sn` parameters when a user tries to log in. If any of those is not present, then the login will be rejected with a ```{:errors {:password "did not match stored password"}}``` error.

**Logs** (environment 2 containers, one Metabase, one OpenLDAP)
Error in application logs
<description>
openldap         | 6025675c conn=1012 fd=21 ACCEPT from IP=172.22.0.4:53188 (IP=0.0.0.0:1389)
openldap         | 6025675c conn=1012 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
openldap         | 6025675c conn=1012 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
openldap         | 6025675c conn=1012 op=0 RESULT tag=97 err=0 text=
openldap         | 6025675c conn=1012 op=1 SRCH base="ou=users,dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson)(|(uid=user01@metabase.com)))"
openldap         | 6025675c conn=1012 op=1 SRCH attr=*
openldap         | 6025675c <= bdb_equality_candidates: (uid) not indexed
openldap         | 6025675c conn=1012 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
openldap         | 6025675c conn=1012 op=2 UNBIND
openldap         | 6025675c conn=1012 fd=21 closed
metabase-ldap    | 2021-02-11 17:20:29,069 DEBUG middleware.log :: POST /api/session 400 88.9 ms (1 DB calls) 
metabase-ldap    | {:errors {:password "did not match stored password"}}
metabase-ldap    | 
</description>

**To Reproduce**
1. Set up a test environment with an LDAP directory, just with users and passwords, without any givenName or sn
2. Connect Metabase with LDAP as stated in the [docs](https://www.metabase.com/docs/latest/administration-guide/10-single-sign-on.html)
3. Try to authenticate

**Expected behavior**
User should be able to log in or be created as the name and surname shouldn't be a limitation for using the product

**Screenshots**
For user user01@metabase.com with the password `Password1!`, that has in the LDAP directory the following object path:
![image](https://user-images.githubusercontent.com/1711649/107672659-ea20f780-6c73-11eb-9804-087b9b303d8d.png)
whenever it tries to log in:
![image](https://user-images.githubusercontent.com/1711649/107673055-5c91d780-6c74-11eb-8ce1-8cf50ed6c13a.png)
**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04
- Your databases: H2
- Metabase version: 0.37.4
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Non-blocking, can be mitigated with proper documentation

**Additional context**
None

**Comment by noahmoss** [comment]
The core problem here is that Metabase expects users to have first and last names set in the DB, so we need some kind of fallback if an LDAP entry doesn't contain `givenName` or `sn`. It seems that for JWT logins we fallback to "Unknown" for both missing fields: https://github.com/metabase/metabase/blob/aad24de711a20676b80802d1f970c9ae48d668cb/enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj#L66-L67

Is this an acceptable workaround for LDAP as well? cc @camsaul
