### ISSUE TITLE
Provide a warning modal when users try to leave Database create/edit page with unsaved changes

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1477]
- [ ] When a user is creating a **new** database and has selected a database type, and then put **any** content into **any** of the other form fields, and then attempts to navigate away from the DB creation page, they should receive a modal warning that says, "Are you sure you want to leave this page? Your changes will be lost. [Yes/No]"
- [ ] When a user is **editing** an **existing** DB, if they make any changes to any of the fields and then attempt to navigate away before clicking Save, then should receive a modal warning that says, "Are you sure you want to leave this page? Your unsaved changes will be lost. [Yes/No]" This string is nearly identical to the one in the above bullet, but with the addition of the word, "unsaved."

This is a continuation from #1353

**Comment by mbvictoria** [comment]
Closing - stale
