### ISSUE TITLE
Custom columns not removed when a join is removed

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#14775]
**Describe the bug**
When using the notebook query editor, if a custom column is defined that uses a joined table, then that join is removed, the custom column remains (although it's invalid).

**Logs**
N/A

**To Reproduce**
1. Click _Ask a question_
2. Click on _Simple question_
3. Pick a database and a table (ex: Sample Data/`Orders`)
4. Click _Join data_, and click some table that has a FK relation to the main table (ex: `Products`)
5. Click _Custom column_ and add some new custom column based on a column from the joined table (ex: `Products -> Rating`)
6. Preview results after the custom column to confirm it's working (first screenshot below)
7. Click the _X_ to remove the join

**Expected behavior**
The custom columns should be removed once the joined table from which they are defined is gone (perhaps with a warning prompt).

**Screenshots**

Valid query with a join and custom column:

<img width="1306" alt="custom_column_results" src="https://user-images.githubusercontent.com/3521562/107706763-70463980-6c86-11eb-9d3a-c204c5e55d6f.png">

After removing the join:

<img width="1177" alt="join_removed" src="https://user-images.githubusercontent.com/3521562/107706806-7f2cec00-6c86-11eb-9bd2-9236b2e5990c.png">

If results are refreshed at this point:

<img width="1178" alt="refresh_results" src="https://user-images.githubusercontent.com/3521562/107706816-8227dc80-6c86-11eb-9b0a-876a1b3fa353.png">

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 88.0.4324.150
- Your operating system: OS X 11.1
- Your databases: Redshift
- Metabase version: `0.38.1-SNAPSHOT` (src_hash=`6d77f0992f5f51345554bc34338f05786f26c54b`)
- Metabase hosting environment: N/A
- Metabase internal database: H2

**Severity**
Minor (can just manually remove the custom columns).

**Additional context**
N/A

**Comment by nemanjaglumac** [comment]
Seems to have been fixed, and the unskipped repro is passing.
Unskipped repro PR is here: https://github.com/metabase/metabase/pull/35484

**Comment by nemanjaglumac** [comment]
Update:
Unskipped E2E reproduction is consistently passing and this issue has been fixed. However, I'm still leaving it open because we want to add lower level (cljs) tests for it.

Once that's done, the issue can be closed and the milestone should be applied.
