### ISSUE TITLE
Native query editor isn't focused automatically

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#14774]
**Describe the bug**
When creating a new native question, the textarea where the query is actually being edited is not focused (despite some visual indication that it might be; see screenshot).  It still has to be clicked before typing (or pasting) works.

**Logs**
N/A

**To Reproduce**
1. Click _Ask a Question_
2. Click on _Native query_
3. Select a database from the dropdown
4. Try to type in the editor

**Expected behavior**
After selecting a database, the query editor should immediately have focus.  There is no reason an extra click should be needed here.

**Screenshots**

(There is some line that looks like it might be the cursor, but it's actually not).

<img width="184" alt="Screen Shot 2021-02-11 at 4 16 06 PM" src="https://user-images.githubusercontent.com/3521562/107705656-ae425e00-6c84-11eb-821a-b0424bef1cbe.png">

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 88.0.4324.150
- Your operating system: OS X 11.1
- Your databases: Redshift
- Metabase version: `0.38.1-SNAPSHOT` (src_hash=`6d77f0992f5f51345554bc34338f05786f26c54b`)
- Metabase hosting environment: N/A
- Metabase internal database: H2

**Severity**
Minor

**Additional context**
N/A

**Comment by flamber** [comment]
Related to #8780
