### ISSUE TITLE
Improvements to row charts

### ISSUE THREAD

**Issue by kp2401075** [metabase/metabase#14785]
**Is your feature request related to a problem? Please describe.**
I need to use row charts to show progress of projects.
as of now they are not well featured.

![image](https://user-images.githubusercontent.com/20717654/107740300-e5853d80-6d5e-11eb-8f43-525ff415363d.png)

**Describe the solution you'd like**
I'd like to see similar options to what bar charts get in row chart.

**Describe alternatives you've considered**
Using Bar chart but it both looks bad and doesn't make sense when tracking multiple projects

**How important is this feature to you?**
I think this is very serious issue with row chart in metabase. If I don't have good solution to issue. I will be forced by client to go with other Option.

**Additional context**
Here is sceenshot of same data being shown as bar chart.

if the axis options that are available in bar chart are also available in row chart this would resolve the issue.

![image](https://user-images.githubusercontent.com/20717654/107740599-a0154000-6d5f-11eb-8684-7ff29769132a.png)

Thanks in advance for looking into this.

Shout out to all metabse devs you guys are awesome :sunglasses:

**Comment by flamber** [comment]
Hi @kp2401075 
Totally agree - we have an issue open for using the same visualization as Bar chart, but just rotated #10967. Related #12523.
