### ISSUE TITLE
Saved Questions search input is super jumpy

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14782]
Watch me try to type the word "Metabase" in the saved questions search widget on Stats:

![jumpy](https://user-images.githubusercontent.com/1455846/107726607-4e58b100-6c9e-11eb-9650-e0e0b9870f6a.gif)

Problems:

1.  After almost every character the list scrolls to the point where I can't see it anymore. (in the GIF I keep trying to scroll back down to see it)
2. The cursor seems to constantly jump to the beginning of the text field all the time. (I'm not clicking anything in this GIF.) I'm typing the word correctly, it's just putting the letters I type in a creative order

**Comment by Terbiy** [comment]
@camsaul, @alxnddr, does this issue still takes place after the https://github.com/metabase/metabase/pull/16808 update?

**Comment by alxnddr** [comment]
@Terbiy you're correct, it is no longer relevant. Thanks for noticing!

**Comment by Terbiy** [comment]
@alxnddr, you are welcome! I used this issue as an example for [my article about debugging](https://hackernoon.com/3-sharpest-instruments-for-debugging-using-the-old-school-mind-mapping-strategy-e3ni35xn).😄
