### ISSUE TITLE
Using "Distribution" on a joined table from a Saved Question creates odd behavior and query

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14787]
**Describe the bug**
Using "Distribution" on a joined table from a Saved Question creates odd behavior and query, since the field name used has double table.column references.

**To Reproduce**
1. Custom question > Sample Dataset > Orders join Products, and save as "Q1"
![image](https://user-images.githubusercontent.com/1447303/107766898-7b57a300-6d34-11eb-9f80-0e54701a8d65.png)
2. Simple question > Saved Questions > "Q1"
3. Click any of the column-title of the joined table (ie Product.Category) and select Distribution
![image](https://user-images.githubusercontent.com/1447303/107767038-acd06e80-6d34-11eb-9b70-7e848fe358eb.png)
4. It will show visualization correctly, but clicking Summarize sidebar will not show the selected breakout
![image](https://user-images.githubusercontent.com/1447303/107767098-c376c580-6d34-11eb-9029-9591b7e8210b.png)
5. Going into Notebook will show the breakout, but it's different from the option available
![image](https://user-images.githubusercontent.com/1447303/107767184-e43f1b00-6d34-11eb-952f-e6603aa12d0f.png)
6. The query generated looks like this:
```
SELECT "source"."Products__CATEGORY" AS "Products__CATEGORY", count(*) AS "count"
FROM (SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY", "Products"."ID" AS "Products__ID", "Products"."EAN" AS "Products__EAN", "Products"."TITLE" AS "Products__TITLE", "Products"."CATEGORY" AS "Products__CATEGORY", "Products"."VENDOR" AS "Products__VENDOR", "Products"."PRICE" AS "Products__PRICE", "Products"."RATING" AS "Products__RATING", "Products"."CREATED_AT" AS "Products__CREATED_AT" FROM "PUBLIC"."ORDERS"
LEFT JOIN "PUBLIC"."PRODUCTS" "Products" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "Products"."ID") "source"
GROUP BY "source"."Products__CATEGORY"
ORDER BY "source"."Products__CATEGORY" ASC
```
Whereas 0.37.9 looks like this:
```
SELECT "source"."CATEGORY" AS "CATEGORY", count(*) AS "count"
FROM (SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY", "Products"."ID" AS "ID_2", "Products"."EAN" AS "EAN", "Products"."TITLE" AS "TITLE", "Products"."CATEGORY" AS "CATEGORY", "Products"."VENDOR" AS "VENDOR", "Products"."PRICE" AS "PRICE", "Products"."RATING" AS "RATING", "Products"."CREATED_AT" AS "CREATED_AT_2" FROM "PUBLIC"."ORDERS"
LEFT JOIN "PUBLIC"."PRODUCTS" "Products" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "Products"."ID") "source"
GROUP BY "source"."CATEGORY"
ORDER BY "source"."CATEGORY" ASC
```

**Information about your Metabase Installation:**
Worked on 0.37.9, but not on latest `release-x.38.x` (commit `b5e2c51`)

**Severity**
Unsure if there are more severe consequences, but it looks like a P3 currently.

**Comment by nemanjaglumac** [comment]
Related: https://github.com/metabase/metabase/issues/16693

**Comment by pawit-metabase** [comment]
The root cause is that the `result_metadata` from `dataset` API returns the `join-alias` for the column's `field_ref` even though it should've been abstracted away by the nested query.

```
field_ref: ["field", 97, {join-alias: "Products"}]
```

When doing a nested query, all the join aliases from the sub-query should be cleared out.

**Comment by camsaul** [comment]
> When doing a nested query, all the join aliases from the sub-query should be cleared out.

Actually they still need to be present. If the source query contains multiple joins to the same table, we won't know which of those joins to use. This is the cause of #14724 and maybe #15863 as well

**Comment by camsaul** [comment]
The differences between the SQL is a red herring

**Comment by camsaul** [comment]
The old backend behavior was actually correct as far as I can tell, but it seems like the fix should have been done on the frontend here -- there's clearly a bug with the frontend not considering the Field ref **with** the `:join-alias` to be the same as the Field it's displaying. Stripping out that information on the backend may have worked around the FE bug, but it ended up causing #17942 as well as partially causing #15578

**Comment by pawit-metabase** [comment]
@camsaul If the original `join-alias` is required, how would any of this work if the saved question is on the right side of the join? Since on the right side of the join the `join-alias` is always going to reference "Question XX" rather than the original table.
