### ISSUE TITLE
UI on/off toggles are not reflected correctly when using environment variable

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#14790]
**Describe the bug**
When using `MB_LDAP_ENABLED` (or `MB_SAML_ENABLED` or `MB_JWT_ENABLED`) in the environment variables, this is not reflected in the frontend which shows as it is disabled

**Logs**
No logs for this one

**To Reproduce**
1. Set up an LDAP environment
2. Set up the admin user in Metabase so you can access the admin settings
3. Go to Admin-->Settings-->Authentication-->LDAP where you can see that there is no green light icon in LDAP, and if you enter LDAP settings it will be shown as disabled

**Expected behavior**
Green light icon and slider in the Enabled state should be there when MB_LDAP_ENABLED=true

**Screenshots**
Env var is enabled so it shows the variables already configured
![image](https://user-images.githubusercontent.com/1711649/107780521-8bb45180-6d25-11eb-901f-a9e02f3da275.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave Latest
- Your operating system: Ubuntu 20.04 LTS
- Your databases: None
- Metabase version: 0.37.8
- Metabase hosting environment: Docker
- Metabase internal database: H2

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Basically anything involving a toggle - related to #13166 and #12272

**Comment by luizarakaki** [comment]
This was solved 
![image](https://github.com/metabase/metabase/assets/32561114/f28ba36c-94ad-4998-9d5f-ebad4f587184)
