### ISSUE TITLE
Upgrade to Webpack 5

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#14803]
We want to upgrade to a newer webpack for the following reasons:
 - we get better splitting of files for the frontend build, which will help embedding a lot since essentially the whole app is included currently
 - general developer ergonomics

**Context**
 Issues: https://github.com/metabase/metabase/issues/6257, https://github.com/metabase/metabase/issues/7170, https://github.com/metabase/metabase/issues/927

**Implementation Plan**

***ETA***: MM/DD/YYYY (TBD)

***Milestone 1***
- [ ] tbd

**How to Test This Feature Out**

This should Just Work

**Comment by paoliniluis** [comment]
For reference https://webpack.js.org/migrate/5/

**Comment by ariya** [comment]
Resolved with PR #16113.
