### ISSUE TITLE
Upgrade to Node 14 LTS

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#14805]
Make sure we use Node 14 LTS everywhere, as it's [supported until Jan 2023](https://nodejs.org/en/about/releases/).

**Implementation Plan**

***ETA***: 03/07/2021 (basically by the time 39 is released)

***Milestone 1***
- [ ] upgrade CircleCI
- [ ] update developer docs, etc
- [ ] anything else? <tbd>

**How to Test This Feature Out**

This should Just Work

**Comment by uladzimirdev** [comment]
we're using node 18, closing
