### ISSUE TITLE
Make it more difficult to change Site URL

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14819]
**Is your feature request related to a problem? Please describe.**
It's too easy to change the Site URL, which can cause a lot of problems in existing SAML configurations and for Pulses, password reset emails and more.
Given how easy it is to accidentally change the Site URL and with all the implications it has, I'm close to calling this a bug.

**Describe the solution you'd like**
:point_down: :point_down: :point_down: 
Show a confirmation popup where the potential impact is explained, so accidental changes to Site URL doesn't happen.
Perhaps with an extra verification in-browser, which shows a bigger warning if current browser URL doesn't match new Site URL.
:point_up: :point_up: :point_up: 

**Describe alternatives you've considered**
Using `MB_SITE_URL` to set the value via environment variables, but there's some problems with that - #13084

**Comment by salsakran** [comment]
@brunobergher this is a common "gun -> foot" situation where folks are changing the site_url without a knowledge of what breaks. We should revisit the messaging and/or error checking

**Comment by salsakran** [comment]
@flamber can you sketch out the SAML consequences here?

**Comment by flamber** [comment]
The consequences have been sketched out in related issue #14820
The actual error might be slightly different, depending on the IdP.

**Comment by brunobergher** [comment]
How is `site_url` used throughout the product? The list I've gathered so far is:
1. Building URLs for emails
2. [Maybe] Building URLs within the UI itself
3. Building URLs for SAML redirects

Anything else?

**Comment by paoliniluis** [comment]
> How is `site_url` used throughout the product? The list I've gathered so far is:
> 
> 1. Building URLs for emails
> 2. [Maybe] Building URLs within the UI itself
> 3. Building URLs for SAML redirects
> 
> Anything else?

hostname for HTTP/HTTPS for JETTY (the web server),

**Comment by flamber** [comment]
@brunobergher Yes to all three, and embedding too.

@paoliniluis That's #13084

**Comment by brunobergher** [comment]
OK let's go with this copy:
> **Only change this if you know what you're doing!** This URL is used for things like creating links in emails, auth redirects, and in some embedding scenarios, so changing it could break functionality or get you locked out of this instance.

And in context:
![image](https://user-images.githubusercontent.com/328388/108913435-cd26e580-75de-11eb-8dc9-90e7e01ca54c.png)
