### ISSUE TITLE
Allow to set the color of e.g. bar in a barchart by a category

### ISSUE THREAD

**Issue by jkbngl** [metabase/metabase#14813]
**Is your feature request related to a problem? Please describe.**
When creating bar charts, I always miss an additional layer to explain the data, I am restricted in the y and the x-axis, 2 dimensions, and I would need a third layer to explain a category. A very common use case is showing the different production facilities, where id like to give the different facilities different colors. 

**Describe the solution you'd like**
I would like to have an additional selection when creating bar charts, which would be called category, I select a field from my data and Metabase then gives the charts the same color for the same categories and a different color for another category. Another solution would be (only possible for scatter charts) to give the different categories different shapes.
![image](https://user-images.githubusercontent.com/32094260/107861890-25285400-6e49-11eb-8160-7ceb2ef1caa2.png)
Attached is an example. I hope this makes it more clear

**Describe alternatives you've considered**
For numerical data I can use the bubble size, I also tried some workarounds to map categorical values to numeric ones, which works to a certain degree.

**How important is this feature to you?**
It would make a lot of charts more self-explaining and allow to create fewer visualizations and show more, so it would be very very helpful. Nothing which will revolutionize Metabase, just a nice little extra layer to make Metabase even better☺

**Additional context**
If the request was unclear or more context is needed, please let me know, I will be more than happy to explain the request in further detail.

**Comment by jkbngl** [comment]
So this is an example of one of my workarounds I have been trying out:
![image](https://user-images.githubusercontent.com/32094260/107862147-fca15980-6e4a-11eb-88f4-9b08f7199524.png)
Not too beautiful, and always good fun to explain to management😁

**Comment by flamber** [comment]
Hi @jkbngl 
Perhaps I don't quite understand what you're trying to do, but you can add another series to the X-axis, as long as you just have one Y-axis.
![image](https://user-images.githubusercontent.com/1447303/107936673-34abb800-6f83-11eb-9c5d-21ea9d10e66d.png)

But it also sounds very related to #11254 and #4114/#2178

**Comment by jkbngl** [comment]
ah thats what I needed, sorry for bothering then😊
