### ISSUE TITLE
Sync task never runs on subsequent databases if one of the databases is down/etc

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14817]
**Describe the bug**
If you have configured 3 databases, where 1st is working, 2nd is inaccessible (down, invalid credentials, wrong certificate, etc), and 3rd is working, then only the 1st database is synced via the task the first time, and then the task scheduler gets into a state `BLOCKED`, which means it will not sync any databases anymore until the instance is restarted, which will then just loop this behavior (depending on when Metabase was started - see step 1, ID vs sync time).

Workaround is to manually sync the database via Admin > Databases > (your-db) > Sync database schema now.

**To Reproduce**
1. Setup 3 databases - the order is important, meaning the ID they get in the database (or the sync time that can be defined by minute from 0.38.0).
1st is MySQL (`metabase/qa-databases:mysql-sample-5.7`), 2nd is Oracle (`wnameless/oracle-xe-11g-r2`), 3rd is MySQL (`metabase/qa-databases:mysql-sample-8`).
All three databases does it's initial sync+fp+scan on setup
I have chosen Oracle as the 2nd database (which is the down-trigger), since it's overly logging a lot during the failed sync and has a bunch of sample data included - any database types can probably be used.
![image](https://user-images.githubusercontent.com/1447303/107955921-b230f180-6f9e-11eb-8463-f31ee23a803d.png)
2. Shutdown Metabase and shutdown the 2nd database (Oracle).
3. Start Metabase and wait for 1 hour (or `faketime` it if you have better things to do)
4. Admin > Troubleshooting > Jobs > metabase.task.sync-and-analyze.job view trigger
![image](https://user-images.githubusercontent.com/1447303/107957922-967b1a80-6fa1-11eb-9649-3765366b6c3b.png)

**Expected behavior**
Skip inaccessible (down, invalid credentials, wrong certificate, etc) databases #7526 and continue syncing - and Quartz Scheduler should never get into a blocked state.

**Information about your Metabase Installation:**
I've only tested 0.37.9, since it takes a long time to reproduce - even with `faketime` or similar commands - but I'm guessing this problem has existed for a long time.

**Additional context**
I can consistently get into blocked state initially on startup, if Metabase starts the sync task scheduler (`INFO metabase.events :: Starting events listener: :metabase.events.sync-database/Sync`), but where the `next_fire_time` has already passed.
I'm triggering that with `faketime -f '+0 x60'` - depending on when it's started, then it might already have passed the event. Change to a higher speed if it difficult to get into this state.

Having a way to completely disable scheduled sync would be very helpful #10398

**Comment by robdaemon** [comment]
Hrm I'm not sure `blocked` is the issue here - blocked is set because the sync job has `DisallowConcurrentExecution` set to true here: https://github.com/metabase/metabase/blob/release-x.38.x/src/metabase/task/sync_databases.clj#L74

Still digging in more to see if I can figure out. This is mainly around our misfire settings - syncs are configured to not retry until the "next fire time" if they fail or are missed. There is no retry until then. If the restart happens after that, we miss another day of syncing. Maybe we need a different misfire setting for this job, so it runs at least once a day.

**Comment by camsaul** [comment]
Fixed by #15043
