### ISSUE TITLE
master/sqlserver: support instance/login issue

### ISSUE THREAD

**Issue by brenol** [metabase/metabase#1481]
I just got the SQLServer build up and running on master and it seems it does not support a specific instance connection. I.e.

jdbc:jtds:sqlserver://localhost:1433\\INSTANCE;user=test;password=test'

It seems it's not recognizing my user (it's trying to connect directly into master instance, which my user does not exist).

Also, when trying to configure any instance during Metabase setup it did not work (kept getting timed out). Adding it directly from administration panel did work, though.

I'll try to assist you guys in answering most questions. Please tell me if I can help.

Thanks!

**Comment by agilliland** [comment]
@brenol how were you inputting your connection details?  it's not clear from your description because you say "Adding it directly from administration panel did work" but then claim something wasn't working.

any screenshots you can provide are also helpful.

**Comment by camsaul** [comment]
Oh I know what this is. JDBC/Korma is expecting the key `:db` for the Database name but the UI is saving it as `:dbname`. Quick fix

**Comment by brenol** [comment]
Hi @camsaul!

I tried with :db instead of :dbname in the frontend and it worked correctly :)

However for the other instance (that I do not have access to master instance) I keep getting invalid username/password.

Its a user with read-access in another instance that is not master and it seems it's unable to connect to that one. Any ideas?

@agilliland 
The request being sent unfortunately does not tell the whole story in this case... as I mentioned, it seems to be a problem that it tries to connect directly into master instance from SQLServer or something.

Changing the parameter in this case from :dbname to :db did not work unfortunately.

Thanks!

**Comment by camsaul** [comment]
@brenol If you grab the latest from master you'll have the option to specify `instance` if you need.

**Comment by brenol** [comment]
perfect! thank you @camsaul! :yum:
