### ISSUE TITLE
Filtering a Custom Column does not give correct results when using "Not equal to"

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14843]
**Describe the bug**
Filtering a Custom Column does not give correct results when using "Not equal to" - the filter has no effect

Workaround is to use a Custom Expression as the filter, but using `NOT` like so:
`NOT [Length] = 12`

**To Reproduce**
1. Custom question > Sample Dataset > People
2. Custom Column `length([Name])` as "Length"
3. Filter "Length" by "Not equal to"=`12`
![image](https://user-images.githubusercontent.com/1447303/108051279-fed20680-704a-11eb-82e8-395f330b7a8a.png)
4. Shows all results - basically the filter has no effect
![image](https://user-images.githubusercontent.com/1447303/108051387-1e692f00-704b-11eb-85e9-77b4916b1ee2.png)

**Information about your Metabase Installation:**
Works in 0.35.0 thru 0.36.11
Fails in 0.37.0 thru 0.38.0-rc3
Works in 0.38.0-rc4 (and latest `release-x.38.x` commit `dc50e8a`)

**Additional information:**
Close when there's a repro test

**Comment by nemanjaglumac** [comment]
Repro confirms it's been fixed.
