### ISSUE TITLE
Metabase displaying "Sorry, we were unable to check for updates at this time." in updates section of admin panel

### ISSUE THREAD

**Issue by Baranton** [metabase/metabase#14863]
Metabase should automatically look for available updates and update itself accordingly. However "Sorry, we were unable to check for updates at this time" is displayed in the update section of the admin panel instead.

![image](https://user-images.githubusercontent.com/38283166/108222341-feb03480-7138-11eb-9193-93ede1c4ab85.png)

**Comment by paoliniluis** [comment]
Hi @Baranton, this happens when Metabase runs on our Metabase Cloud (as we manage the updates) or when it can't access an internet connection. Can you specify where is the instance running? Thanks

**Comment by Baranton** [comment]
Hi @paoliniluis, thank you for your response. We are running on Metabase Cloud indeed. Does this mean that we are on running on the latest version (Metabase v0.38 if I am not mistaken) ?

Thanks !

**Comment by flamber** [comment]
Let's keep the conversation in one place: https://discourse.metabase.com/t/problem-summarizing-personalized-expressions-shares/13435
