### ISSUE TITLE
Add documentation about database limitations for pivot tables

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14876]
Pivot tables don't currently work with every type of database that Metabase supports, but we neglected to document this fact. We should explicitly list these databases in the [pivot tables docs](https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#pivot-table). See [this Discourse thread](https://discourse.metabase.com/t/give-us-your-feedback-on-version-0-38/13474/5) for context.

Maybe @paulrosenzweig can provide the unsupported DBs list, and @jeff-bruemmer could update the website docs as well as the app repo docs? I think some of the unsupported DBs include:

- BigQuery
- Google Analytics
- Mongo?
- others?

**Comment by paulrosenzweig** [comment]
Pivot tables work for GUI queries against DBs with both joins and expressions. Unfortunately, I don't think we have a way to print out a driver feature matrix and quickly see what's supported where.

GA, Mongo, BigQuery, and Druid don't work. I think everything else does, but I haven't checked each.
