### ISSUE TITLE
Allow ObjectId creation from date in native mongodb query

### ISSUE THREAD

**Issue by akprats33** [metabase/metabase#14889]
**Is your feature request related to a problem? Please describe.**
Mongodb ObjectID contains a timestamp. As this timestamp is the time when document/ObjectID was created, we can also use ObjectId when we want to sort or filter based on creation date without needing any additional field. At the moment, though metabase supports querying on ObjectID, it doesn't allow ObjectID comparison based on date using mongodb shell method `ObjectId.fromDate`. 

**Describe the solution you'd like**
Add support for `ObjectId.fromDate` in native query. This would allow us to define variable of date type and query on ObjectID created from that date using this function without needing any additional index on another field.

![image](https://user-images.githubusercontent.com/8426904/108499918-0d335300-72d5-11eb-84ff-e5239877d49b.png)

**Comment by flamber** [comment]
Hi @akprats33 
That wouldn't be possible, since it's not valid JSON syntax - the error you're seeing is coming from MongoDB.
Here's how to do it in Native query vs shell: https://stackoverflow.com/questions/66209470/mongodb-compass-query-with-objectid-in-date-range
