### ISSUE TITLE
Feature Request: LDAP Authentication

### ISSUE THREAD

**Issue by exabrial** [metabase/metabase#1488]
First: Wow. Excellent Product. Metabase is a great idea. The BI space is incredibly complicated, but it generally comes down to having a reports team that knows how to use a complicated BI product, and consumers of said reports whining that the reports team isn't giving them what they want. This is a huge collaboration point for the data scientists and the consumers and understand each other.

I'm already managing quite a few users, and while the admin panel is incredibly well designed and very user friendly, it would be awesome if you could have LDAP integration similar to the way how Gitlab LDAP authentication works in their "community product".

Essentially, and administrator provides a LDAP server url, and a group filter. For us this is:

```
  :host => 'activedirectory',
  :port => 389,
  :method => :plain,
  :base => 'cn=Users,dc=windows,dc=corp,dc=springventuregroup,dc=com',
  :uid => 'sAMAccountName',
  :filter => '(&(sAMAccountName=%{username})(memberOf:1.2.840.113556.1.4.1941:=CN=gitlab_users,OU=Applications,OU=Groups,DC=windows,DC=corp,DC=xxx,DC=com))',
```

So anyone that's a member of 'gitlab_users', or a nested group, is able to sign in. Upon initial sign in, GitLab creates a local user account that with the same UID. When the user authenticates in the future, it simply does a bind against LDAP with the supplied password. This gets you out of the business of having to store password hashes.

Anyway, thanks; Looking forward to watching your product grow!

**Comment by MartinArens** [comment]
+1

**Comment by tomferreira** [comment]
+1

**Comment by seedubyaache** [comment]
+1

**Comment by christiangrassi** [comment]
Is there any update on this issue? It's a big deal for enterprise users not to use their central authentication system.

**Comment by moumny** [comment]
Would be good to make authentication and authorization modular. Each user can adapt it if it doenst fit the systems used in his company.

**Comment by edgardksb** [comment]
+1

**Comment by stefanoeb** [comment]
+1

**Comment by yuri1969** [comment]
+1

**Comment by ericparland** [comment]
+1

**Comment by lpodkalicki** [comment]
+1

**Comment by geoand** [comment]
+1

**Comment by kjad** [comment]
+1

**Comment by Tarekk** [comment]
+1

**Comment by merritts** [comment]
+1

**Comment by orware** [comment]
+10 and I can help test it out

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by green2k** [comment]
So many people are leaving the 👍 reaction; however, this issue is imho blocked by the #3210 issue/request.

**Comment by wwwiiilll** [comment]
@green2k I agree, though in my case I need it "now", refactoring for the modular system later probably won't be that bad, I wouldn't mind volunteering for it when the time comes.

**Comment by salsakran** [comment]
@wwwiiilll thank you for taking this on. We really appreciate it. The core team doesn't really use LDAP anywhere, so you pitching in really helps out on the domain knowledge side. We'd be more than happy to help refactor things once you've captured how the specific case of LDAP should work.

**Comment by dhelland** [comment]
Any update on this?

**Comment by Nyno-Kun** [comment]
@dhelland yes, look at https://github.com/metabase/metabase/pull/4340

**Comment by rakesh1084** [comment]
+1
looking for LDAP Integration

**Comment by camsaul** [comment]
Hey everyone (@rakesh1084), to repeat, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by evilangel-ru** [comment]
+1. I'm hardly need it!

**Comment by camsaul** [comment]
@evilangel-ru, I just said this, but one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

😒

**Comment by edenzik** [comment]
We'd also love LDAP auth. Alternatively, is there a way to make a public passwordless read-only profile?
