### ISSUE TITLE
Negative filter can not be converted to custom expression

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#14880]
### Steps to reproduce:

1. Ask a question, Simple question
2. Sample Dataset, Products
3. Filter, Filter by Title
4. Choose "Does not contain", type `Wallet`, press _Add Filter_
5. Click on the new filter "Title does not contain Wallet"
6. Press the left chevron icon, choose _Custom Expression_

### Actual

Nothing happens, but the JavaScript console shows an error:

```
Unknown MBQL clause ["does-not-contain",["field-id",12],"Wallet",{"case-sensitive":false}]
```

![image](https://user-images.githubusercontent.com/7288/108426336-8016ce00-71f0-11eb-8245-d22030d45e53.png)

### Expected

The filter gets converted to something like `NOT contains([Title], "Wallet")`.

### Additional Note

This problem applies to another negative filter, e.g. "Not empty".

Note that a positive filter, such as "Title contains Wallet" will be **correctly** converted to a filter, i.e.:

```
contains([Title], "Wallet")
```

**Comment by flamber** [comment]
Related to #12225

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/15061
