### ISSUE TITLE
Is there any way to use microsoft azure SSO? 

### ISSUE THREAD

**Issue by alexberd** [metabase/metabase#14892]
The only reference I found was the following but did not mention anything about Microsoft.
https://github.com/metabase/metabase/blob/master/docs/faq/setup/how-do-i-integrate-with-sso.md

**Comment by flamber** [comment]
You can use SAML with Azure in the Enterprise Edition: https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-saml.html
Duplicate of #5915
