### ISSUE TITLE
We should break up the monolithic "Visualizing results" doc page

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14896]
We've talked about this for ages, but this page, https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html, has gotten massively long now that we have 16 distinct visualizations(!).

We should add a new section to the [Users Guide](https://www.metabase.com/docs/latest/users-guide/start.html) with the heading "Visualizing results" and create a separate page for each visualization. I suspect that'll make it easier for folks to find what they're looking for, either when searching or browsing, and will make it simpler to link to articles on specific visualizations.

This will also give us the opportunity to elaborate on documentation for individual chart types, and should fix https://github.com/metabase/metabase/issues/9582 in the process.

**Comment by jeff-bruemmer** [comment]
[Visualization page now has subpages for individual viz types](https://www.metabase.com/docs/latest/questions/sharing/visualizing-results).
