### ISSUE TITLE
Serialization: Snippets are not transferred correctly, leading to incorrect references and broken queries

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14909]
**Describe the bug**
Snippets are not transferred correctly during serialization, which can lead to incorrect references and broken queries.

**To Reproduce**
1. Create a setup for (pre-populated) target (`java -DMB_DB_FILE=target.db -jar metabase.jar`)
   a. Native query > Create a snippet - `SELECT 'this-is-target'` call it "target" - and use it in a question saved as "Q1-target"
   b. Shutdown.
2. Create another setup for source (`java -DMB_DB_FILE=source.db -jar metabase.jar`)
   a. Native query > Create a snippet - `SELECT 'this-is-source'` call it "source" - and use it in a question saved as "Q1-source"
   b. Shutdown
3. Dump source.db into serializedsource: `java -DMB_DB_FILE=source.db -jar metabase.jar dump serializedsource`
   a. Notice the yaml file for "Q1-source" has the hardcoded reference to snippet-id `1` instead of a dynamic reference, which could be changed to the correct question on load. There's also no separate yaml-folder for snippets (cards, pulses, etc), which there probably should be.
4. Load serializedsource into target.db: `java -DMB_DB_FILE=target.db -jar metabase.jar load serializedsource`
5. Start target normally: `java -DMB_DB_FILE=target.db -jar metabase.jar`
   a. Go to "Q1-source" - it will show the result "this-is-target", which is incorrect, and viewing the SQL will show `{{snippet: target}}` instead of what was used in step 2a.
   b. Looking in the application database table `native_query_snippet` will only have the snippet created in step 1a.

**Information about your Metabase Installation:**
Tested 1.36.11, 1.37.9 and 1.38.0

**Severity**
Leads to broken queries in questions, or possibly incorrect results because of bad references. And missing snippets.

**Additional context**
Related to #14566

**Comment by jeff303** [comment]
Commit 5 from #15858 should fix this.

**Comment by jeff303** [comment]
Update: it's mostly commit 12 that will fix this.

**Comment by flamber** [comment]
Fixed by #15858 - will be part of 1.39.3
