### ISSUE TITLE
Better UX for version downgrade

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#14904]
**Describe the bug**
If Metabase is downgraded (i.e. an older version is brought up, pointing to an app DB instance that was previously run with a newer version), then the behavior is weird/bad.  Since this is a scenario we explicitly do not support, we should more clearly show an error or simply refuse to start.

**Logs**
N/A

**To Reproduce**
1. Run Metabase version X, create some questions, etc.
2. Install an older version and point it to the same app DB
3. Start the older version

**Expected behavior**
The older version should not start, or show a very clear error right on the front page explaining what the problem is.

**Screenshots**
This happened when going from 0.39 to 0.37.

<img width="1650" alt="Screen Shot 2021-02-19 at 12 34 17 PM" src="https://user-images.githubusercontent.com/3521562/108573747-027bbc80-72db-11eb-8f20-bcdc34285558.png">

**Severity**
Low

**Additional context**
N/A

**Comment by flamber** [comment]
It's difficult to know when a migration would not be backward compatible. Would probably require another column in the `DATABASECHANGELOG` table, but not sure if that would cause problems by itself too.
Somewhat related to #8420

**Comment by noahmoss** [comment]
Closed by https://github.com/metabase/metabase/pull/37239 and the general introduction of downwards migrations.
