### ISSUE TITLE
Serialization: Nested question references questions in other collection are moved and becomes corrupted

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14914]
**Describe the bug**
When a nested question is based on another question that is in a different collection, then the nested question is moved to that collection and also becomes broken (cannot be opened, loading spinner) because of missing reference.

**To Reproduce**
1. On source:
   a. Create a question "Q1" and save to root
   b. Create a collection "C1"
   c. Create a question "nestedQ1", which is based on "Q1", and save in "C1"
   d. Create a dashboard "D1" and add both "Q1" and "nestedQ1", and save in "C1"
2. Serialization `dump`
   a. "Q1"-yaml looks correct, but "nestedQ1"-yaml is stored in the directory of "Q1" without any indications that it should live in "C1"
3. Serialization `load`
   a. There's no errors/warnings, but the log indicates that it is creating the collection and dashboard before creating the questions.
   b. Going to the dashboard "D1" will show a permission error on the cards - likely #14912
      ![image](https://user-images.githubusercontent.com/1447303/108634134-7a331e00-7478-11eb-9de3-505f3f1bd257.png)
   c. The "nestedQ1" cannot be found in collection "C1", but it's in root instead
   d. Going to "nestedQ1" will show loading spinner forever with browser console error `TypeError: this.query() is undefined`, without any possibility to fix the question in the GUI. And looking in `report_card.dataset_query` is missing `source-table` reference.
   e. Going to "Q1" works as expected.

**Expected behavior**
Dump process should not move the "nestedQ1" to the collection of "Q1" (inside of it's directory).
The "nestedQ1" should work and not become corrupted (not sure why it corrupts, the reference looks correct in yaml).
And the load-process should throw an error/warning that it's adding a card with no question reference on dashboards.

**Information about your Metabase Installation:**
Tested 1.37.9 and `70262c7`

**Additional context**
Very related to #14912

**Comment by kidd** [comment]
Trying to tackle this now but it's not coming out straighforward.

The "workaround" of rerunning load with `--mode update` removes de access permission issue.  The testbed I'm using still doesn't get it solved, but I think it might be due to a path resolution issue:

![sshot--2021-03-01--181346](https://user-images.githubusercontent.com/25607/109540106-f69db080-7ab9-11eb-90ec-715aa70fbaed.png)

...digging more...

**Comment by flamber** [comment]
@kidd Make sure that the manually added databases in `metabase_database` works on your setup.

**Comment by kidd** [comment]
Ah, ok... so the workaround of reruning with --mode 'update' works. I'm going to try to improve it, but it seems clear that a "rerun" in the right moment trimming to the right entities should work.

**Comment by jeff303** [comment]
This should be fixed by commit 1 under #15858.

**Comment by flamber** [comment]
Fixed by #15858 - will be part of 1.39.3
