### ISSUE TITLE
MongoDB attributes named "data" is not accessible in Metabase

### ISSUE THREAD

**Issue by getstuff** [metabase/metabase#14913]
**Describe the bug**
An attribute called "data" in a MongoDB collection doesn't appear in Metabase and is not available for querying.

**To Reproduce**
1. Add a MongoDB database. This database should include a collection with a "data" attribute.
2. Try to query the "data" attribute - you won't be able to
3. try to find the "data" attribute via Admin > Data Model - you won't be able to

**Expected behavior**
A MongoDB attribute named "data" should be queryable like any other attribute.

**Screenshots**

**Information about your Metabase Installation:**

- Your databases: MongoDB (among others)
- Metabase v0.38.0.1
- Metabase hosting environment: Elastic Beanstalk

`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.214-160.339.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "druid",
      "mongo"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-02-19",
      "tag": "v0.38.0.1",
      "branch": "release-x.38.x",
      "hash": "0635914"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
`

**Comment by flamber** [comment]
Hi @getstuff 
Can you supply a sample schema?
Do you see any errors or warnings in Admin > Troubleshooting > Logs, when you run a manual sync via Admin > Databases?

**Comment by flamber** [comment]
I cannot reproduce on 0.38.0.1 with MongoDB 4.0 on an empty collection with one document:
```
{
    "_id" : ObjectId("1234567890f1fc83a15b9db5"),
    "data" : 1
}
```
