### ISSUE TITLE
Serialization: Dashboard cards are corrupted, when questions are outside of dashboard collection

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14912]
**Describe the bug**
When dashboard is referencing questions that hasn't been created yet during the `load`, then the cards are created with `null` reference in `report_dashboardcard.card_id`.

**To Reproduce**
1. On source:
   a. Create a question "Q1" and save to root
   b. Create a collection "C1"
   c. Create a dashboard "D1" and add "Q1" and save dashboard in "C1"
2. Serialization `dump` - notice that everything looks okay, all the right references in yaml-files.
3. Serialization `load`
   a. There's no errors/warnings, but the log indicates that it is creating the collection and dashboard before creating the question.
   b. The question "Q1" works correctly.
   c. Going to the dashboard will show a permission error on the card (likely due to technical reasons with `null` reference):
      ![image](https://user-images.githubusercontent.com/1447303/108633504-d09e5d80-7474-11eb-9e18-f0a3b3d963aa.png)

**Expected behavior**
The load-process should probably create/update all collections, then all questions, then all pulses, and lastly all dashboards.
The load-process should throw an error/warning that it's adding a card with no question reference.

**Information about your Metabase Installation:**
Tested 1.37.9 and `70262c7`

**Severity**
While it's not showing references to other cards, it's a common practice to have questions in other collections that the dashboard.

**Comment by jeff303** [comment]
Fixed via #15842 in x.39.
