### ISSUE TITLE
Report query problem

### ISSUE THREAD

**Issue by Jzow** [metabase/metabase#14917]
How can a shared report jump to another report by clicking a column of data in the graph? Is there any solution we need at present

**Comment by Jzow** [comment]
pls help me

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Have a look at this: https://www.metabase.com/learn/building-analytics/dashboards/custom-destinations.html

**Comment by Jzow** [comment]
@flamber  thanks bro
