### ISSUE TITLE
Serialization: Snippet folders and Collections collide on `dump` because of missing namespace separation

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14910]
**Describe the bug**
If there's a Collection and a Snippet Folder with the same name, then only one of them is created, and the order (ID) in the database will determine which will be overridden, and that causes questions (or potentially snippets) not to be transferred.

**To Reproduce** (very important with the order of when items are created)
1. Create a collection called "Marketing"
2. Create a question and save it inside of "Marketing"-collection
3. Create a snippet folder called "Marketing"
4. Create a snippet and save it inside of "Marketing"-folder
5. Serialization `dump` - notice that the collection-yaml for "Marketing" is `namespace: snippets` and it has the question-yaml inside of it. There's no snippet-yaml, but that's #14909.
6. Serialization `load` will give the following error, which is correct, but there was no errors/warnings during `dump` that different items was overwriting each other:
`ERROR serialization.upsert :: Error inserting metabase.models.card.CardInstance@6b213571 "My Question in Marketing-collection": A Card can only go in Collections in the "default" namespace.

**Expected behavior**
Not sure if `serialization-dump/collections/root/collections` should have a sub-directory for each namespace, or if snippet folders should have it's own parent directory like `serialization-dump/collections/root/snippet-folders`, but they shouldn't overlap.

**Information about your Metabase Installation:**
Only tested 1.37.9 because #14907 made it even more confusing.

**Additional context**
Should probably be fixed together with #14909, since snippets are not transferred at all, and this just leads to more confusion.

**Comment by jeff303** [comment]
Commit 5 under #15858 should fix this one.

**Comment by flamber** [comment]
Fixed by #15858 - will be part of 1.39.3
