### ISSUE TITLE
Serialization: Archived items are included in `dump`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14911]
**Describe the bug**
Archived items (questions etc) are included in Serialization `dump`, which is by itself a P3 or feature dump-flag.
But depending on the IDs of the items, then active items can be overwritten with archived items during `dump`, if the have the same name and in the same collection.

**To Reproduce**
1. On source
   a. Create a question called "Q" (ID=1) and place it in root.
   b. Create a question based on "Q" (ID=1) - let's call it "nestedQ" - this question will get ID=2
   c. Create another question called "Q" (ID=3) and place it in root, which could have been done by someone by accident
   d. Archive the question in step 1c - "Q" (ID=3)
2. Serialize `dump` - notice that the "Q"-yaml file is the step 1c question instead of step 1a question, and the step 1b "nestedQ"-yaml is inside the directory now referencing that "Q"-yaml.

**Expected behavior**
Not include archived items at all.
Otherwise have a dump-flag like `dump --archived true` to include archived items, but that will be difficult without each item having unique hashes as references instead of just the item name, so it avoids overwrite conflicts.

**Information about your Metabase Installation:**
Tested 1.37.9 and 1.38.0 and `70262c7`

**Comment by kidd** [comment]
Fixed as part of #14871

**Comment by camsaul** [comment]
Hopefully this should be an easy fix, although if other things reference archived items this could get a bit hairy... maybe we still want to dump archived stuff, but preserve the `archived` status?

**Comment by flamber** [comment]
This got fixed in 1.39.3, though Snippets might need a special case when archived, since they work different from other objects.
Creating a new issue for Snippets, when I have dug around in it some more.

**Comment by rascasse83** [comment]
Is the root cause of all of this, not the fact that Metabase is allowing more than 1 question with the same name, to be present in the same collection / location (root) ?

if that is the case, why don't we prevent that instead? 

The fact we cannot synchronise archived questions between environments, is a loss of functionality.

**Comment by paoliniluis** [comment]
@rascasse83 will be fixed in 47
