### ISSUE TITLE
need the ability to apply `is empty` and `is not empty` filters on date/time fields

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1493]
in the QB if you are filtering by a date/time field you get the calendar widget which allows for easy filtering by time, but unfortunately that widget does not include the ability to filter by null/not-null values.  those options should be added to that widget or there should be some way to apply the filter definition of `timestamp_col is not null`

**Comment by carterdea** [comment]
I need this for paranoia's `deleted_at` column

**Comment by agilliland** [comment]
Okay, turns out this does actually exist already and I am just blind.  By default the option is collapsed though, so when you go to filter a date/time field the widget will start out as ..

<img width="391" alt="screen shot 2015-11-24 at 8 41 28 am" src="https://cloud.githubusercontent.com/assets/1987787/11373631/fa9e76b2-9287-11e5-90c2-2f4b3bd36ad9.png">

Then you just need to click the `More Options` toggle in grey there and expand it to see what you are looking for ...

<img width="376" alt="screen shot 2015-11-24 at 8 46 06 am" src="https://cloud.githubusercontent.com/assets/1987787/11373655/0e232660-9288-11e5-963b-f68e2013bcb2.png">
