### ISSUE TITLE
Add support for conditional formatting on boolean fields

### ISSUE THREAD

**Issue by andrewmcloughlin** [metabase/metabase#14939]
I am frustrated that I cannot highlight rows in a table according to a boolean field. I should be able to select boolean columns in the conditional formatting side menu and I should have the option to set a colour for the cell or row if the value is true or false.

The workaround is to map true and false to 1 and 0 and to set conditional formatting on this numerical field. However 1 and 0 is confusing to users using the dashboard.

Not hugely important, but a nice to have.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @andrewmcloughlin 
You should be able to "is greater than or equal to 1" for `true` and "is less than or equal to 0" for `false`. It might depend on the database type you're using, but I tested on MySQL/MariaDB.
![image](https://user-images.githubusercontent.com/1447303/108828995-e1abb380-75c7-11eb-9d9a-7de6d47a49bf.png)
Related to #11458

**Comment by andrewmcloughlin** [comment]
@flamber, thanks for the quick response.

The boolean fields don't appear in the dropdown menu under 'Which columns should be affected?'. Could this be because I am using version 0.37.5 ?

![Group 1](https://user-images.githubusercontent.com/12680365/108836484-c8573700-75c8-11eb-8bec-686de1e5a4e0.png)

**Comment by flamber** [comment]
@andrewmcloughlin I don't think so, but please post "Diagnostic Info" from Admin > Troubleshooting, and which database it is, and what you have defined as Field Type for the boolean column in Admin > Data Model

**Comment by andrewmcloughlin** [comment]
@flamber thanks.

Diagnostic Info:
`{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.99 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "3.10.0-862.3.3.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10 (Debian 11.10-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-05",
      "tag": "v0.37.5",
      "branch": "release-x.37.x",
      "hash": "be537ee"
    },
    "settings": {
      "report-timezone": "Europe/London"
    }
  }
}`

Database: Tyto (postgreSQL)
I have tried the following field types: Category, No special type and enum.

FYI I also don't seem to have the option for 'greater than or equal to' (or anything similar) in the conditional formatting menu; the options available to me are shown in this screenshot.
![image](https://user-images.githubusercontent.com/12680365/108845468-5df8c380-75d5-11eb-926c-e51f0dda3323.png)

**Comment by flamber** [comment]
@andrewmcloughlin But you have selected `patient_id`, which I'm guessing is a PK (Entity) or Foreign Key.
The options available will depend on the column selected. Set your boolean column to Field Type = `Number` and refresh the browser, then you should have the option available.

**Comment by andrewmcloughlin** [comment]
@flamber, thanks, that makes sense.

I still can't see the 'boolean' fields in the first dropdown menu even after changing their field type to Number.
![image](https://user-images.githubusercontent.com/12680365/108847545-bc26a600-75d7-11eb-8cda-21cbdeca8749.png)
![Group 2](https://user-images.githubusercontent.com/12680365/108852710-dcf1fa00-75dd-11eb-85ea-2678091be5f5.png)

**Comment by flamber** [comment]
@andrewmcloughlin Okay, then it does work - maybe it does on 0.38.0.

**Comment by darksciencebase** [comment]
When tackling this one, include the issues linked by Flamber to see if they can be fixed together
