### ISSUE TITLE
Dashboard Filter Improvements (to support large-scale rollout)

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#14930]
There are a few improvements that can be made to dashboard filters that would allow larger organizations to roll them out (especially if they are moving off a different system that may have similar use cases).

**Implementation Plan**

***ETA***: MM/DD/YYYY

***Milestone 1***
- [x] Filter using "contains" rather than "begins with" (see #8219)
- [x] More advanced Dashboard filters options like we do have in Questions (no issue currently): String Column starts with / ends with / contains xxx, Number filters

**How to Test This Feature Out**

TBD

**Comment by daltojohnso** [comment]
Testing of "contains" search:

1. Navigate to a dashboard with cards on it
2. Click the pencil icon in the dashboard header to edit the dashboard
3. Click the now visible filter icon on the far right of the dashboard header to add a parameter
4. Add an "other categories" parameter. A parameter widget should have appeared on the dashboard.
5. Click the new "Category" parameter widget and then click on a dropdown in a card on the dashboard to map it to a field with many values, like "Name" from the User table in the Sample Dataset.
6. Save your dashboard
7. Click on the Category widget after the dashboard has saved.
8. Assuming you've mapped to "Name" typing "bb" should trigger a search request that results in "Abbey Satterfield" appearing at the top of the list.
9. Typing "bby k" should show only one option, "Bobby Kessler"
