### ISSUE TITLE
Trying to programmatically create dashboards

### ISSUE THREAD

**Issue by BenjaminPalko** [metabase/metabase#14941]
We are constructing our dashboards programmatically through the metabase API, we have it mostly figured out except for linking Question (card) parameters (filters) to the dashboard.

When a filter is added to a dashboard and linked to a question it is given a `parameter_id` in both the ordered cards 'parameter_mappings' and the dashboards 'parameters' fields. Im trying to found out where these ids are coming from, or if they are being generated, how to generate them.

Any help on this issue would be appreciated

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

The best way to learn the API, is to just use Metabase while having your browser developer network-tab open and looking at the request, and what data is being send/received.
https://www.metabase.com/learn/developing-applications/advanced-metabase/metabase-api.html
