### ISSUE TITLE
Running a SQL question that references a GUI question with a filter fails

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#14949]
**Describe the bug**
Running a SQL question that references a GUI question with a filter fails. I only observed this on Redshift, but I haven't tested other dbs.

The query errors with: `[Amazon][JDBC](10900) Not all parameters have been populated.`

**To Reproduce**
1. Create a GUI question with a filter on a text column. Save it and grab the ID for the next step.
2. Create a new SQL question that references the saved question
e.g. `WITH foo AS {{#[QUESTION ID]}} SELECT * FROM foo`
3. Run that SQL question

Removing the filter from the GUI question will fix the issue.

**Information about your Metabase Installation:**

<details>
  <summary>Instance details</summary>
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.214-118.339.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "bigquery",
      "redshift",
      "druid",
      "mongo",
      "googleanalytics",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.18"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-02-22",
      "tag": "v0.39.0-SNAPSHOT",
      "branch": "master",
      "hash": "1d3ef4f"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
</details>

**Comment by flamber** [comment]
Shouldn't it be `WITH foo as {{#123}} SELECT * FROM foo` ?

I cannot reproduce when I use my syntax, but I'm getting the following error on Redshift, when using your syntax:
`[Amazon](500310) Invalid operation: syntax error at or near "(" Position: 292;`
And very different errors on H2 or MySQL

**Comment by paulrosenzweig** [comment]
@flamber oops good catch. I updated the example code.

I'm still seeing this, but I played around a bit more and realize not all filters trigger the issue. Filtering on two text columns both failed. When instead filtered on an integer or boolean column, it worked fine. Both "is" and "is not" showed the behavior on a text column.

**Comment by flamber** [comment]
Ahhhh, now I understand - that's this bugger #12236
