### ISSUE TITLE
Saving a question before query has been executed can be slow with UI "hanging"

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14957]
**Describe the bug**
When saving a question that has not been executed, then the query will be run during the save process and it looks like it's the UI is hanging. And if the user closes the modal and tries to save again, then it will create multiple questions and run more queries.

**To Reproduce**
1. Native query > MySQL or some db with sleep-function (it's also possible to do via GUI, but needs a slow query).
2. Write query `select sleep(60)` - do **not** run the query.
3. Click Save - give it a name and click Save - the button gets disabled (expected), but the modal does not go away until after the query has executed (60 seconds in this test), and then the "Saved! Add this to a dashboard?" modal is shown.
![image](https://user-images.githubusercontent.com/1447303/109069315-57f80500-76f1-11eb-833e-20234b311a3b.png)
4. The log will indicate that it's missing metadata (for `report_card.result_metadata`)
```
2021-02-24 22:37:02,222 INFO api.card :: Card results metadata passed in to API is MISSING. Running query to fetch correct metadata.
2021-02-24 22:38:02,245 DEBUG middleware.log :: POST /api/card 202 [ASYNC: completed] 1.0 mins (8 DB calls) App DB connections: 1/10 Jetty threads: 3/50 (5 idle, 0 queued) (71 total active threads) Queries in flight: 0 (0 queued)
```

**Expected behavior**
The question should be saved instantly without "hanging" the Save-modal. Or even better if it could fetch the metadata without having to run the full query, but not sure if that would even be possible.

**Information about your Metabase Installation:**
Tested 0.35.4 through 0.38.0

Looks like it might have been fixed long ago, but I'm unsure #6866 - not listing as regression.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by araujo-filipe** [comment]
Hey everyone!
This still happens on v0.42.2.
We used to work around this issue by running something like `SELECT 1`and deleting that line before saving the question but after upgrading this is not working.
Also seems like introducing field filters with no default value makes Metabase run the question with no filter, which just makes it impossible to save the question in some cases.
Is there any known way to mitigate this issue while a fix is not deployed?
Thank you!

**Comment by araujo-filipe** [comment]
@flamber @ariya
> Is there any known way to mitigate this issue while a fix is not deployed?

**Comment by flamber** [comment]
@araujo-filipe No, not as far as I know.

**Comment by mfpinhal** [comment]
This is a real issue on our side. We used to hack our way into saving questions faster, and in long-running questions, this makes it quite a poor experience honestly. IMO, there should be a way to skip the question running in the backend before saving, even if for that we'd have to tick a checkbox or so to make it happen. Either this or a general admin setting to enable one to customize this behavior.
