### ISSUE TITLE
Metabase BigQuery sync: no new tables are imported

### ISSUE THREAD

**Issue by vpoluyaktov** [metabase/metabase#14951]
**Describe the bug**
We are using Metabase with Google BigQuery. Initial setup was fine, we were able to import DB schema containing 46 BigQuery tables. Then we added some new tables (222 tables in BigQuery now), tried to sync DB schema again but we are still seeing only 46 tables imported before. No new tables are shown

**Logs**
Here is a sync log. No errors:
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:16-08:00 INFO metabase.sync.util STARTING: Analyze data for bigquery Database 3 'RhapsodyAnalytics'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:16-08:00 INFO metabase.sync.util STARTING: step 'fingerprint-fields' for bigquery Database 3 'RhapsodyAnalytics'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:16-08:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [*****·············································] 😢   10% Table 646 'log_appointments'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:16-08:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [**********········································] 😞   20% Table 1,342 'facebook_ads_easyvet_all_ads_insights_platform_and_device'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [***************···································] 😕   30% Table 1,387 'facebook_ads_ra_ad_campaigns'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.util FINISHED: step 'fingerprint-fields' for bigquery Database 3 'RhapsodyAnalytics' (148.1 ms)
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.util STARTING: step 'classify-fields' for bigquery Database 3 'RhapsodyAnalytics'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.analyze classify-fields Analyzed [********************······························] 😐   40% Table 645 'log_payments'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.analyze classify-fields Analyzed [*************************·························] 😬   50% Table 1,364 'ga_monticelloah_ga_events'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.analyze classify-fields Analyzed [******************************····················] 😌   60% Table 1,383 'facebook_ads_ra_ad_creative'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.util FINISHED: step 'classify-fields' for bigquery Database 3 'RhapsodyAnalytics' (77.8 ms)
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.util STARTING: step 'classify-tables' for bigquery Database 3 'RhapsodyAnalytics'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.analyze classify-tables Analyzed [***********************************···············] 😏   71% Table 656 'log_google_ads_account_performance'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.analyze classify-tables Analyzed [****************************************··········] 😊   81% Table 658 'log_google_ads_search_query_performance'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.analyze classify-tables Analyzed [*********************************************·····] 😍   91% Table 1,350 'facebook_ads_easyvet_all_ads_insights'
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.util FINISHED: step 'classify-tables' for bigquery Database 3 'RhapsodyAnalytics' (87.5 ms)
[d58c0487-453e-4952-aed3-6824b611db47] 2021-02-23T17:16:17-08:00 INFO metabase.sync.util FINISHED: Analyze data for bigquery Database 3 'RhapsodyAnalytics' (338.0 ms)

**To Reproduce**
1. Go to Admin->Databases and Configure new BigQuery database 
2. Click on Sync Database Schema now
3. Go to Admin -> Data Model and remember imported tables
4. Add some new tables to your BigQuery instance
5. Go to Admin -> Databases and Click on Sync Database Schema now
6. Go to Admin -> Data Model and check if new tables are shown

**Expected behavior**
New tables must be imported to the Data Model and shown in the list

**Actual result** 
No new tables are imported

**Screenshots**

**Severity**
We are blocked with new reports creation 

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.112+",
    "user.language": "en",
    "user.timezone": "US/Central"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-20",
      "tag": "v1.37.7",
      "branch": "release-x.37.x",
      "hash": "2b034aa"
    },
    "settings": {
      "report-timezone": "US/Central"
    }
  }
}
```

**Comment by flamber** [comment]
Closing, replied in ticket - will reopen if this is an (reproducible) issue.
