### ISSUE TITLE
Mongo Variable defined as Field Filter doesn't honour regex

### ISSUE THREAD

**Issue by marksull** [metabase/metabase#14960]
**Describe the bug**

When generating a question using native mongo query, you can define variables that can be classified as a type of `Field Filter`. After selecting the type as `Field Filter` you are required to map it to a document and field.

To use the `Field Filter` you would then create a mongo query as follows. In the example below, my variable is called `branch_name_filter` and is classified as a `Field Filter` and mapped to the field `branch_name`.

`{ "$match": {{branch_name_filter}} }`

Based on trial an error, at the time of query it appears Metabase translates this query into the following format based on the data entered into the field and `Field Filter` mapping. In the example below I typed `my_value` into the filter field before running the query.

`{ "$match": {"branch_name": { "$in" : ["my_value"]} }} `

If any field `branch_name` contains an exact match for `my_value` a result will be returned.

However, the mongo `$in` query type supports regular expressions. For example if I entered `/my_value/` into the filter field, I would expect that I could find any documents where the branch name contained `my_value`. For example:

`{ "$match": {"branch_name": { "$in" : [/my_value/]} }} `

Unfortunately when using any regex a match is never found. The anecdotal evidence suggests that the `Field Filter` feature is always wrapping the query value in quotes so it is interpreted as a plain string value. For example:

`{ "$match": {"branch_name": { "$in" : ["/my_value/"]} }} `

The expected behaviour would be that if a regex value is provided that it not be wrapped in quotes so that it can be interpreted by mongo as a native regex query.

**Logs**
NA

**To Reproduce**
See above

**Expected behavior**
See above

**Screenshots**
NA

**Information about your Metabase Installation:**
Metabase 0.38.0.1

**Severity**
Low

**Additional context**
NA

**Comment by flamber** [comment]
Hi @marksull 
That's how Field Filters are supposed to work. For reference: https://www.metabase.com/learn/building-analytics/sql-templates/field-filters.html
Allowing what you propose could lead to SQL injection (or whatever the equivalent on Mongo is).
There's an issue open for allow more fine grained control like #4639 and #4728
