### ISSUE TITLE
Latest Metabase not starting from docker image

### ISSUE THREAD

**Issue by bitplaio** [metabase/metabase#14983]
**Describe the bug**
I have launched a container with the latest metabase in docker as follows:
`docker run -d -p 3000:3000 \
  -e "MB_DB_TYPE=postgres" \
  -e "MB_DB_DBNAME=metabase" \
  -e "MB_DB_PORT=5432" \
  -e "MB_DB_USER=<username>" \
  -e "MB_DB_PASS=<password>" \
  -e "MB_DB_HOST=my-database-host" \
  --name metabase metabase/metabase`

And after all metabase doesn't seem to be loading.

**Logs**
Here's my server's log output:

`Warning: environ value jdk-11.0.10+9 for key :java-version has been overwritten with 11.0.10
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2021-02-26 16:11:40,599 INFO metabase.util :: Maximum memory available to JVM: 988.0 MB
2021-02-26 16:11:53,259 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html`

And that's it. Nothing else happens.

**To Reproduce**
1. docker pull metabase/metabase:latest
2. docker run with all necessary envs
3. docker logs -f <container_id>
4. See the logs not running.
5. Metabase not starting

**Expected behavior**
Metabase starts running on a specified port.

**Severity**
Blocking my usage of Metabase entirely

**Comment by bitplaio** [comment]
issue resolved. seems like the latest version's installation process takes a lot more time to complete. sorry

**Comment by flamber** [comment]
You're likely running out of entropy - see #10175 for workaround.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
