### ISSUE TITLE
Pivot Table breaks with "Display values" = "Custom mapping" defined in Data Model

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14985]
**Describe the bug**
Pivot Table breaks when creating/editing questions with remapping ("Display values" = "Custom mapping") defined in Data Model.

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Reviews > Rating > "Display values" = "Custom mapping" (it's not important to change the values, but I gave them A,B,C,D,E) and click Save
2. Custom question > Sample Dataset > Reviews - summarize Count by Rating:Unbinned and CreatedAt:Year
![image](https://user-images.githubusercontent.com/1447303/109330145-a7f2db00-785b-11eb-8341-d8c193ba87dc.png)
3. Click Visualization button to try to switch to Pivot Table (which is disabled because of step 1)
![image](https://user-images.githubusercontent.com/1447303/109331535-3e73cc00-785d-11eb-8764-f88caaa04c5d.png)
4. Click Pivot Table (greyed) - the UI now gets into a broken state, where most things are disabled and need to click away from the page a do a browser refresh. Browser console throws `TypeError: e is undefined` and clicking around will just pile on errors.
![image](https://user-images.githubusercontent.com/1447303/109332237-1c2e7e00-785e-11eb-9c0a-3742acd605e5.png)

**Information about your Metabase Installation:**
Tested 0.38.0

**Additional context**
If you already have Pivot Table questions saved, and then do step 1, then those questions still work if not edited. Once the question is "dirty", then it will break similar to step 4.
Related to #15003 and #12586

**Comment by skaboy007** [comment]
Please see that it still persist on 0.38.1

**Comment by flamber** [comment]
This was fixed in 0.41.0, unsure by which PR - unskipping tests to prevent regressions.
![image](https://user-images.githubusercontent.com/1447303/163547053-d647ed23-2d81-462c-8b7a-7b36989c5f25.png)
