### ISSUE TITLE
Collections sidebar makes it impossible to browse the collection on smaller screens (e.g. mobile)

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#15006]
![metabase width issue mobile](https://user-images.githubusercontent.com/15974735/109404004-aa663b00-7916-11eb-9c14-886641706efe.png)

v .38.0.1

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by adventuresnick** [comment]
Same bug here!
Sadly it makes metabase really unusable on mobile phones 😞 

![image](https://user-images.githubusercontent.com/84153574/120035533-25ea8d80-bfd5-11eb-933a-62860ce270fc.png)

**Comment by gusaiani** [comment]
@flamber I've been investigating this issue and could not find a commit that shows it working acceptably.

Once we get to commit ba7be097b, that is tag `v0.37.0.2`, the BE no longer starts.

<details><summary>BE Error Output</summary>

<code>
2021-06-22 22:13:21,287 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.ValidationFailedException: Validation Failed:
     8 change sets check sum
          migrations/000_migrations.yaml::12::agilliland was: 8:e862a199cba5b4ce0cba713110f66cfb but is now: 8:bedbea570e5dfc694b4cf5a8f6a4f445
          migrations/000_migrations.yaml::49::camsaul was: 8:4508e7d5f6d4da3c4a2de3bf5e3c5851 but is now: 8:56dcab086b21de1df002561efeac8bb6
          migrations/000_migrations.yaml::50::camsaul was: 8:98a6ab6428ea7a589507464e34ade58a but is now: 8:388da4c48984aad647709514e4ba9204
          migrations/000_migrations.yaml::55::camsaul was: 8:11bbd199bfa57b908ea3b1a470197de9 but is now: 8:87c4becde5fe208ba2c356128df86fba
          migrations/000_migrations.yaml::60::camsaul was: 8:2141162a1c99a5dd95e5a67c5595e6d7 but is now: 8:4f997b2cd3309882e900493892381f38
          migrations/000_migrations.yaml::68::sbelak was: 8:b4ac06d133dfbdc6567d992c7e18c6ec but is now: 8:ca201aeb20c1719a46c6bcc3fc95c81d
          migrations/000_migrations.yaml::69::senior was: 8:eadbe00e97eb53df4b3df60462f593f6 but is now: 8:97b7768436b9e8d695bae984020d754c
          migrations/000_migrations.yaml::72::senior was: 8:4dc6debdf779ab9273cf2158a84bb154 but is now: 8:ed16046dfa04c139f48e9068eb4faee4
</code>
</details>

Questions: 

Do you remember this working acceptably in mobile?

If so, maybe can you help me get the BE to run in older versions for a `git-bisect`?

**Comment by ariya** [comment]
> Once we get to commit [ba7be09](https://github.com/metabase/metabase/commit/ba7be097be2aa45541f80e10c923392d715740f2), that is tag `v0.37.0.2`, the BE no longer starts.

Try removing the application database (*.db) first.

In all cases, I recommend a fresh clone to a brand new working directory, e.g. `~/work/metabase/37` and then switch to `release-x.37.x` branch (or any 37 tags) and then run the usual e.g. `yarn dev`.

**Comment by flamber** [comment]
@gusaiani This is a regression since 0.38.0 - since there weren't any sidebar until that version. There's nothing to go back and look at in previous versions. We need to handle always-shown sidebar on small screens.

**Comment by gusaiani** [comment]
Thank you @ariya, obvious in retrospect but I was not thinking of doing those last night.

Appreciate it 🙇

**Comment by gusaiani** [comment]
> This is a regression since 0.38.0 - since there weren't any sidebar until that version.

Thank you @flamber.

Sanity check: would you agree that this needs to be sent to design so we know where to place what is this sidebar, how to toggle it open/closed and so forth?

**Comment by flamber** [comment]
@gusaiani If we don't have any other places with sidebars handled on small screens, then I guess it has to go through design.

**Comment by gusaiani** [comment]
Design: 
https://www.figma.com/file/dyN71v3AI1GutWOaSLoxT6/Collections-Mobile-Layout?node-id=0%3A1&viewport=-194%2C254%2C0.4838546812534332

Prototype: 
https://www.figma.com/proto/dyN71v3AI1GutWOaSLoxT6/Collections-Mobile-Layout?page-id=0%3A1&node-id=1%3A88&viewport=-249%2C618%2C1&scaling=min-zoom
