### ISSUE TITLE
Pivot Table doesn't generate error logs, which make it really hard to debug problems

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15003]
**Describe the bug**
Pivot Table doesn't generate error logs, which make it really hard to debug problems. The stacktrace is sometimes included mangled in a browser log message, which is not marked as Error either.

**To Reproduce**
Follow the steps in #14969 and no query error is shown in the log.

**Information about your Metabase Installation:**
x.38.0

Historic: #14148

**Comment by camsaul** [comment]
How is this a regression? 37 didn't even have Pivot Tables

**Comment by flamber** [comment]
@camsaul Regression has a description that says "Bugs that were previously fixed and/or bugs unintentionally shipped with new features"

**Comment by camsaul** [comment]
oh ok. I didn't realize that we were including _new_ bugs in the term "Regression" -- seems like every bug is a Regression by that definition

**Comment by camsaul** [comment]
Fixed by #15019
