### ISSUE TITLE
Description of a `dimension` is confusing

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1501]
*  What's a numerical string value?
*  Why mention that it can be high *or* low-cardinality? Is it not allowed to be medium cardinality?

![screen shot 2015-11-18 at 1 33 56 pm](https://cloud.githubusercontent.com/assets/1455846/11255294/3adece08-8dfa-11e5-845d-2d04e2e190d1.png)

**Comment by tordans** [comment]
+1 for this. 

Also, I would be great if the help text is extended by telling me, what the consequences of the choice are.
- "Non-numerical values that is not meant to be used." => Are those things hidden somewhere? Or what behavior changes with this selection?
- "A number that can be added…" => I guess some of the output options are only available / only work if this is selected?
- Dimension => What behavior in the app changes with this selection? What if I choose a non-string-value, will it break something?
- Sensitive => So this is what I use when I want the column to be hidden from all dropdowns, right? I get that it will not be used in the result views.

**Comment by camsaul** [comment]
This still confuses me :flushed::question: 

> [A dimension is] a high or low-cardinality numerical string value

**Comment by agilliland** [comment]
this is addressed by #2192
