### ISSUE TITLE
If there are no fields available for aggregation of a given type, don't enable that aggregation type

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1502]
I can still choose aggregations like cumulative sum which require a Field even if none are available to me:

![screen shot 2015-11-18 at 1 26 46 pm](https://cloud.githubusercontent.com/assets/1455846/11255356/a6552e2a-8dfa-11e5-8d4e-9114d87a84b9.png)

It would probably be better just to disable the option entirely

**Comment by tlrobinson** [comment]
I'm fairly sure this issue answers the question in this comment...

<img width="1246" alt="screen shot 2016-04-20 at 11 07 09 pm" src="https://cloud.githubusercontent.com/assets/18193/14699449/b919ca90-074c-11e6-8deb-59c6e979b7f0.png">
