### ISSUE TITLE
Metabase does not support text wrap or multiline for dashboard column

### ISSUE THREAD

**Issue by Theo-Lo** [metabase/metabase#15041]
**Is your feature request related to a problem? Please describe.**
When I am using dashboard, I find that some column values will be too long. As I am trying to display the log together with other contents, it is not user-friendly for user to keep scrolling to the right in order to view more contents, especially for those super long logs like stack trace. I have tried to look for solution online and yet can only see people raising this issue and never really have a solution.

**Describe the solution you'd like**
I would like the column to either be able to support text wrap or multiline, or maybe have a pop up window to show the detailed content of a column.

**Describe alternatives you've considered**
I have looked for solution in here as well, I know there are related posts like #6178, #10372, #6826, #14253, etc. However, there don't seem to have a conclusion in those posts, and some of them are just being referenced to other posts only.

**How important is this feature to you?**
It is a very important feature for us, as it directly affects the user experience. User will not be able to see the log easily, especially when stack tracing.

**Comment by flamber** [comment]
Hi @Theo-Lo 
There's already issues open of wrapping or multiline - #10372/#6826/#6178 - and you might be interested in #4392 too.
Upvote the issues you're interested in by clicking :+1: on the first post of each issue.
