### ISSUE TITLE
Display bug in pie chart: mouse over "other" is not working when "other" includes a null value

### ISSUE THREAD

**Issue by MarcSamD** [metabase/metabase#15045]
### **Describe the bug**
Cannot display the details of the values grouped in "Other" in a pie chart when one of the field name in Other is blank.

### **To Reproduce**
1) Create a cumulative count of discount
![image](https://user-images.githubusercontent.com/70358310/109761229-fec92d80-7c2a-11eb-8c60-25690f23a19b.png)

2) Display it as a pie chart. If the pie is splitted enough there is no problem, you can mouse over a blank value (below in blue)
![image](https://user-images.githubusercontent.com/70358310/109762032-4354c900-7c2b-11eb-84e7-69130316a92d.png)

3) Change the Minimum slice percentage to 10, and try to mouse over "Other" will not show anything
![image](https://user-images.githubusercontent.com/70358310/109762600-d68dfe80-7c2b-11eb-9db5-71af7cd08dd2.png)

### **Expected behavior**
We should see the split of Other as it is usually working just with one of the item without name or displayed as "null" and the count of rows beside.
![image](https://user-images.githubusercontent.com/70358310/109763076-7f3c5e00-7c2c-11eb-88ae-bf30ce59a735.png)

### **Severity**
Low

**Comment by flamber** [comment]
Reproduce:
1. Custom question > Sample Dataset > Orders - summarize Count by Discount:50bins
![image](https://user-images.githubusercontent.com/1447303/109820066-f249d280-7c34-11eb-837e-7ea682040689.png)
2. Change visualization to Pie > visualization Settings > Display > Minimum slice percentage = 90
![image](https://user-images.githubusercontent.com/1447303/109820201-14435500-7c35-11eb-8c60-b77ed0ec9e7c.png)
3. Hovering the pie will not show any tooltip and browser console has the following error:
```
app-main.bundle.js?fc344f13f5994a3b4142:5 Uncaught TypeError: Cannot read property 'name' of undefined
    at t.getFriendlyName (app-main.bundle.js?fc344f13f5994a3b4142:5)
    at app-main.bundle.js?fc344f13f5994a3b4142:5
    at Array.map (<anonymous>)
    at t.value (app-main.bundle.js?fc344f13f5994a3b4142:5)
    at t.value (app-main.bundle.js?fc344f13f5994a3b4142:5)
    at c._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js?fc344f13f5994a3b4142:485)
    at c._renderValidatedComponent (vendor.bundle.js?fc344f13f5994a3b4142:485)
    at c._updateRenderedComponent (vendor.bundle.js?fc344f13f5994a3b4142:485)
    at c._performComponentUpdate (vendor.bundle.js?fc344f13f5994a3b4142:485)
    at c.updateComponent (vendor.bundle.js?fc344f13f5994a3b4142:485)
```
