### ISSUE TITLE
Date column 1 day earlier when exporting to xls

### ISSUE THREAD

**Issue by bakkertjebrood** [metabase/metabase#15076]
**Describe the bug**
Date column 1 day earlier when exporting to xls 14-04-2014 becomes 13-04-2014

**Logs**

**To Reproduce**
Export table with date field to xls

**Expected behavior**
Show correct date

**Screenshots**

**Information about your Metabase Installation:**
0.38.1

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
csv works as expected. Would be nice if xls also works

**Additional context**

**Comment by flamber** [comment]
Hi @bakkertjebrood 
Please post "Diagnostic Info" from Admin > Troubleshooting, and which database you are querying.
And if you can reproduce with static SQL, then please include that.
