### ISSUE TITLE
Normalize queries in URL fragments on FE

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15079]
- After we merge #14980 we should migrate the MBQL normalization code over to the shared lib and write some wrapper functions that make it easy to use in JS, then use the normalization code to normalize unsaved queries encoded in Metabase links. This would make sure links that encode legacy MBQL syntax would continue to work even on newer versions of Metabase

**Comment by camsaul** [comment]
didn't mean to close

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/15497
