### ISSUE TITLE
LDAP login fails with Group Sync when user is assigned to 1 group

### ISSUE THREAD

**Issue by JordanAmentco** [metabase/metabase#15073]
Error is as follows:
When logging in with a LDAP linked user that has 1 associated group that is linked to the metabase, an error is thrown and login is rejected due to the groups being returned not being an array (react object iterator error). No error is thrown if a array is returned from the login. Error is only thrown once group linking is set up between a LDAP server and metabase.

Reproduction steps:
1. install Metabase as per normal (h2 backing database, unsure if error is thrown with another backing database).
2. Link Metabase to LDAP server (Active Directory on Windows 2019 Server was used in the original error case).
3. Create links for groups to LDAP groups
4. Create a new user in the Active Directory and assign this user 1 of the LDAP groups that has been linked to a metabase group.
5. Attempt to login with valid username and password for the user.
6. Error is thrown.

Temporary fix:
Assign the user a second junk data group. Having more than 1 group on a user prevents the error. It need **not** be assigned to a group in metabase.

**Comment by flamber** [comment]
Hi @JordanAmentco 
Please include "Diagnostic Info" from Admin > Troubleshooting.
And any errors from Admin > Troubleshooting > Logs, or the LDAP server.

**Comment by JordanAmentco** [comment]
**Chrome Error Log:**
```
app-main.bundle.js?63a7664584485b962be4:5 Setting moment.js start of week for Locale en to sunday
:3000/api/user/current:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
:3000/api/session:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
app-main.bundle.js?63a7664584485b962be4:5 Form submission error Objectdata: error: groups: "schema.utils.ValidationError@688dc8ab"__proto__: Objectvalue: dn: "CN=error error,CN=Users,DC=amentco,DC=local"email: "error@amentco.local"first-name: "error"groups: "CN=Nurses1,CN=Users,DC=amentco,DC=local"last-name: "error"__proto__: Object__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()isCancelled: falsestatus: 400__proto__: Object
(anonymous) @ app-main.bundle.js?63a7664584485b962be4:5
app-main.bundle.js?63a7664584485b962be4:5 Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bvalue%2C%20error%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:21:36139)
    at e (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:448:190001)
    at e.exports (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:448:190096)
    at Object.instantiateChildren (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:485:56617)
    at Z._reconcilerInstantiateChildren (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:485:54005)
    at Z.mountChildren (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:485:54212)
    at Z._createInitialChildren (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:485:43615)
    at Z.mountComponent (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:485:41837)
    at Object.mountComponent (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:92:166199)
    at c.performInitialMount (http://localhost:3000/app/dist/vendor.bundle.js?63a7664584485b962be4:485:60139)
(anonymous) @ app-main.bundle.js?63a7664584485b962be4:5
```

**Logs log file:**
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:25+10:00 INFO metabase.core 
Metabase v0.38.0.1 (0635914 release-x.38.x) 

Copyright © 2021 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:25+10:00 WARN metabase.core WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:25+10:00 INFO metabase.core Starting Metabase in STANDALONE mode
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:25+10:00 INFO metabase.server Launching Embedded Jetty Webserver with config: 
 {:port 3000}

[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:25+10:00 INFO metabase.core Starting Metabase version v0.38.0.1 (0635914 release-x.38.x) ...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:25+10:00 INFO metabase.core System info:
 {"file.encoding" "Cp1252",
 "java.runtime.name" "Java(TM) SE Runtime Environment",
 "java.runtime.version" "1.8.0_281-b09",
 "java.vendor" "Oracle Corporation",
 "java.vendor.url" "http://java.oracle.com/",
 "java.version" "1.8.0_281",
 "java.vm.name" "Java HotSpot(TM) 64-Bit Server VM",
 "java.vm.version" "25.281-b09",
 "os.name" "Windows 10",
 "os.version" "10.0",
 "user.language" "en",
 "user.timezone" "Australia/Brisbane"}

[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:25+10:00 INFO metabase.plugins Loading plugins in C:\Users\Jordan\Desktop\metabase\plugins...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Plugins with unsatisfied deps: ["Metabase BigQuery Driver"]
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :druid...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :druid  
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :google...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered abstract driver :google  
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.initialize Dependencies satisfied; these plugins will now be loaded: ["Metabase BigQuery Driver"]
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 WARN metabase.plugins.lazy-loaded-driver Warning: plugin manifest for :bigquery does not include connection properties
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :bigquery...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered abstract driver :sql  
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :bigquery (parents: [:sql :google]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :googleanalytics...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :googleanalytics (parents: [:google]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :mongo  
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :mongo...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Plugins with unsatisfied deps: ["Metabase Oracle Driver"]
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :presto...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :presto (parents: [:sql]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :redshift...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered abstract driver :sql-jdbc (parents: [:sql]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :postgres (parents: [:sql-jdbc]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :redshift (parents: [:postgres]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :snowflake...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :snowflake (parents: [:sql-jdbc]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :hive-like...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered abstract driver :hive-like (parents: [:sql-jdbc]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :sparksql...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :sparksql (parents: [:hive-like]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :sqlite...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :sqlite (parents: [:sql-jdbc]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 DEBUG metabase.plugins.lazy-loaded-driver Registering lazy loading driver :sqlserver...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :sqlserver (parents: [:sql-jdbc]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.plugins.dependencies Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Vertica Driver"]
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :h2 (parents: [:sql-jdbc]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.driver.impl Registered driver :mysql (parents: [:sql-jdbc]) 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.core Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 WARN metabase.db.env WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.db.setup Verifying h2 Database Connection ...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.db.setup Successfully verified H2 1.4.197 (2018-03-18) application database connection. 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.db.setup Running Database Migrations...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.db.setup Setting up Liquibase...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.db.setup Liquibase is ready.
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:26+10:00 INFO metabase.db.liquibase Checking if Database has unrun migrations...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:27+10:00 INFO metabase.db.setup Database Migrations Current ...  
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:27+10:00 INFO metabase.db.data-migrations Running all necessary data migrations, this may take a minute.
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:27+10:00 INFO metabase.db.data-migrations Finished running data migrations.
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.dependencies/Dependencies 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.activity-feed/ActivityFeed 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.metabot-lifecycle/MetaBotLifecycle 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.last-login/LastLogin 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.notifications/Notifications 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.sync-database/Sync 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.driver-notifications/DriverNotifications 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.revision/Revisions 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.events Starting events listener: :metabase.events.view-log/ViewLog 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.task Initializing task SyncDatabases 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.task.send-pulses Sending scheduled pulses...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.task Initializing task CheckForNewVersions 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.task Initializing task SendAnonymousUsageStats 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.task Initializing task SendAbandomentEmails 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.task Initializing task SendPulses 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.task Initializing task SendFollowUpEmails 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.task Initializing task TaskHistoryCleanup 
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.driver.impl Initializing driver :sql...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.driver.impl Initializing driver :sql-jdbc...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.driver.impl Initializing driver :h2...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:01:28+10:00 INFO metabase.core Metabase Initialization COMPLETE
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:16+10:00 INFO metabase.util.i18n.impl Reading available locales from locales.clj...
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:17+10:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 25.0 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (1 idle, 0 queued) (42 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:17+10:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 258.8 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:17+10:00 DEBUG metabase.server.middleware.log DELETE /api/session 204 10.9 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (0 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:17+10:00 DEBUG metabase.server.middleware.log GET /api/database 200 27.6 ms (4 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:17+10:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 401 562.4 µs (0 DB calls) 
"Unauthenticated"

[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:18+10:00 DEBUG metabase.server.middleware.log GET /api/user/current 401 320.2 µs (0 DB calls) 
"Unauthenticated"

[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:18+10:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 6.3 ms (0 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:02:29+10:00 DEBUG metabase.server.middleware.log POST /api/session 400 79.2 ms (0 DB calls) 
{:value {:dn "CN=error error,CN=Users,DC=amentco,DC=local", :first-name "error", :last-name "error", :email "error@amentco.local", :groups "CN=Nurses1,CN=Users,DC=amentco,DC=local"},
 :error {:groups (not (sequential? a-java.lang.String))}}

[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:26+10:00 DEBUG metabase.server.middleware.log POST /api/session 200 89.4 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (3 idle, 0 queued) (42 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:26+10:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 8.1 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:26+10:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 13.0 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:26+10:00 DEBUG metabase.server.middleware.log GET /api/database 200 12.4 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:26+10:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 141.2 ms (6 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:26+10:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 10.1 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:26+10:00 DEBUG metabase.server.middleware.log GET /api/database 200 10.1 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:27+10:00 DEBUG metabase.server.middleware.log GET /api/automagic-dashboards/database/1/candidates 200 382.1 ms (6 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:30+10:00 DEBUG metabase.server.middleware.log GET /api/setting 200 3.8 ms (0 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:30+10:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 16.2 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (1 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:30+10:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 57.9 ms (13 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
[d5c2e18f-6999-49ab-8011-b9ba533a359c] 2021-03-08T15:05:31+10:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 9.1 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)

**Comment by flamber** [comment]
Metabase currently does not support sync to sub-groups - #6692 upvote by clicking :+1: on the first post

**Comment by JordanAmentco** [comment]
Hi @flamber Please be advised that your closing comment does not reflect the bug at hand, as far as I can tell. This issue is caused when a single entry is in the groups "memberOf" section. Tagging a user with 0, 2 or more groups prevents the issue. The issue is specifically on the 1 entry case. The react error in browser indicates as such also. Can I please request that this case be looked over once more?

**Comment by flamber** [comment]
I would think that #7098 might solve this.
