### ISSUE TITLE
Stacked bars break with negative values

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#15092]
Example query:

```sql
select 'a' as x, 'foo' as breakout, 100 as y
union all
select 'a' as x, 'bar' as breakout, -100 as y
union all
select 'a' as x, 'baz' as breakout, -100 as y
```

Every non-zero value should appear, but "foo" isn't shown. I'm guessing "bar" is drawn over it.

![image](https://user-images.githubusercontent.com/691495/110358127-06f9e200-800a-11eb-8e16-0fccbdc9e319.png)

Turning off stacking displays all the data correctly:

![image](https://user-images.githubusercontent.com/691495/110358153-10834a00-800a-11eb-8365-022d3a34dbd0.png)

**Comment by flamber** [comment]
Duplicate of #5763 :wink:

**Comment by paulrosenzweig** [comment]
@flamber thanks! I searched but somehow missed it.
