### ISSUE TITLE
Add Admin Setting to restrict sending dashboard subscriptions/pulses to given domain(s)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15109]
Right now you can either send Pulses/Dashboard Subscriptions to a Metabase user in the current instance, or to arbitrary email addresses. We want to add a Admin panel Setting to restrict the arbitrary email addresses to a given domain (or possibly domains; TBD).

Example: We don't want users of metabase.example.com to send Dashboard Subscriptions outside of example.com. Cam can send a Dashboard Subscription to anyone@anysite.com. By setting the new Setting to `@example.com`, future Cam can only send Dashboard Subscriptions to email addresses that end in `@example.com`

Open questions:

- Should this apply retroactively to existing Pulses and Dashboard Subscriptions? (ping @salsakran)
- Do we need to support multiple domains? e.g. `@example.com` *or* `@example2.com`
- Should we allow subdomains?

@mazameli, can we get designs (or at least copy) for this? Not sure what the clearest way to describe this is

Part of #15108 and #15084

**Comment by camsaul** [comment]
Duplicate of #15018

**Comment by camsaul** [comment]
I guess this is not really a duplicate of #15018 -- this is a subissue

**Comment by brunobergher** [comment]
Solved in 41, right?

**Comment by flamber** [comment]
Closing, as any other changes can be dealt with in separate issues.
