### ISSUE TITLE
Dashboard Subscriptions: Compliance Controls

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#15108]
- Admins should be able to set controls related to subscriptions:
  - Restrict email recipients to @mycompany.com domains (#15109)
  - Restrict recipients to just the user themselves. (0.40+?)

**Links**
- product doc: https://docs.google.com/document/d/1CmXQKvz30iFGRfA0HFzF9f2KI9mFKo8wzWO6YjP_2SE/edit#bookmark=id.1lao66k5rifa
- feature branch: TBD

**Implementation Plan**

***ETA***: MM/DD/YYYY 

***Milestone 1: Admin Panel Controls***
- [ ] Admin panel global setting to restrict sending email to a domain (e.g. @mycompany.com)
- [ ] tbd

**How to Test This Feature Out**

1. Log into admin panel
2. Navigate to Email tab
3. Choose setting ....
4. Try to send dashboard subscription to another email domain
5. It shouldn't work (error message? silent fail?)

**Comment by paoliniluis** [comment]
@luizarakaki can we close this one?
