### ISSUE TITLE
Serialization `dump` includes Personal Collections

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15120]
**Describe the bug**
Serialization `dump` includes all Personal Collections as of 1.38.1. But 1.37.9 would include the PC of the first admin user, even without the flag `--user` defined.
While this might be wished for some, it should either be documented (since it's currently listed as [will not be included](https://www.metabase.com/docs/latest/enterprise-guide/serialization.html#what-gets-dumped-and-loaded)) and/or behind a dump flag, so it can be chosen if wanted.

**To Reproduce**
1. On 1.38.1 do a `dump`
2. There will be Personal Collection(s) in dump/collections/root/collections (together with other top-level collections)

**Information about your Metabase Installation:**
Tested  1.37.9 thru 1.38.1

**Comment by jeff303** [comment]
Should be fixed by commit 11 under #15858.

**Comment by flamber** [comment]
Fixed by #15858 - will be part of 1.39.3
