### ISSUE TITLE
Maps: Label names not showing when hovering over individual states.

### ISSUE THREAD

**Issue by jiniep** [metabase/metabase#15124]
**Describe the bug**
When hovering over the map, label names are not displaying. For example in the screenshot below, I expect "State" and "Count" to appear before each value when I hover the Texas.

<img width="907" alt="Screen Shot 2021-03-10 at 2 25 16 PM" src="https://user-images.githubusercontent.com/46331880/110706265-727bb500-81ac-11eb-9ed7-b8eb8cc483dc.png">

Query in the editor is 

`WITH job_company_credit_type AS (
    SELECT jpt.created_at, credit_type, job_id
    FROM report_glue_db_prod.job_property_company_transactions jpt
    JOIN report_glue_db_prod.property_company_transactions pt on pt.property_company_transaction_id = jpt.property_company_transaction_id
    UNION
    SELECT jpt.created_at, credit_type, job_id
    FROM report_glue_db_prod.job_property_transactions jpt
    JOIN report_glue_db_prod.property_transactions pt ON pt.property_transaction_id = jpt.property_transaction_id
)

SELECT j.state as "State", COUNT(*) as "count"
FROM job_company_credit_type jt 
JOIN report_glue_db_prod.jobs j on j.job_id = jt.job_id
WHERE jt.created_at >= timestamp '2021-02-01'
GROUP BY j.state`

**Logs**
<img width="1413" alt="Screen Shot 2021-03-10 at 2 27 22 PM" src="https://user-images.githubusercontent.com/46331880/110706461-bc649b00-81ac-11eb-9562-a819336b566d.png">

**To Reproduce**
1. Go to native query
2. create a sample results displaying the states and count of x 
3. Visualisation -> select maps
4. hover over any state and see if labels are displayed. 

**Expected behavior**
From the above example when hovering over a state, the labels "State", "Count" should display prior to the corresponding value to indicate the value.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome Version 88.0.4324.192 )
- Your operating system: (Mac OS Catalina 10.15.17
- Your databases: Presto / Athena
- Metabase version: (e.x. 0.37.3)
- Metabase hosting environment: (Jar-file)
- Metabase internal database: (Postgres)

**Severity**
Its medium severity. When users view the maps and hover, they are not sure what each of the number represent.

**Additional context**
This problem is specific to maps. When changing visualisation to other forms such bar charts, the labels are showing as expected.

**Comment by flamber** [comment]
Fixed in 0.38.0 by #14688
