### ISSUE TITLE
When moving or rearranging dashboard cards, allow a card to be inserted in a place where there isn't currently space for it

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15128]
Right now it's really painful trying to rearrange questions on a very full dashboard, especially when trying to move a newly added question to the top — you have to create space manually by moving every single other card down, one by one, to make room for the new card.

A pretty straightforward solution would be to add an insertion line interaction that would insert rows on mouse-up to make room for the card being dragged, pushing the other cards down.

Here's a [clickable prototype](https://www.figma.com/proto/VPwnlQDLsLdT7j3ThFd2hO/Better-Dashboard-Card-Rearranging?node-id=1%3A8&viewport=834%2C320%2C0.5&scaling=min-zoom) of the concept, and a screenshot that gives you the gist:

![image](https://user-images.githubusercontent.com/2223916/110714916-1f5c2f00-81b9-11eb-8df8-269b60338849.png)

## Possible alternatives
Versus the below, I think the above is better as it feels more direct and intuitive without being overly twitchy.

- Add a control to insert blank space/rows into a dashboard manually.
- Make it possible to select and move multiple cards at once via a click and drag or command/shift+click interaction.
- Bring back the old card reshuffling behavior that was in the early versions of Metabase (this was pretty annoying).

**Comment by flamber** [comment]
Related to #9895
