### ISSUE TITLE
Should be able to run a card with another card as its source query with just perms for the former 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15131]
Suppose we have two Cards, Card 1 and Card 2. Card 2 has a query like `{:query {:source-table "card__1"}}` (i.e., Card 2 uses Card 1 as a source query). Now suppose the current User has permissions to see Card 2, but no perms for Card 1. They should still be able to run Card 2 -- we don't need to check perms for Card 1 as well.

However, we should require perms for Card 1 to save a Card with a query like `{:query {:source-table "card__1"}}`, so people can't give themselves access to arbitrary Cards.

I think this is a regression in `master` (39-SNAPSHOT)

**Comment by camsaul** [comment]
Open question: (from @paulrosenzweig)

> That works, but it feels a bit messy around updates. Can someone edit a question that references 1if they don’t have access to 19331If yes, then you could edit a question but not duplicate it. If not, it’s a weird situation where you can create a question but lose edit access if someone adds `{{#1}}`

**Comment by camsaul** [comment]
This is how it currently works:

You can't save a Card if you don't have permissions to run the query for that Card. Example: I can't create a new Card with `{:query {:source-table "card__1"}}` unless I have permissions for Card 1 itself. This means you can't clone Card 2 in the example above. You also can't currently edit name, description, etc.

The way it currently works can be summed up as 

```
write perms for card = "curate" (write) perms for parent Collection && query perms for Card's query
```

##### Proposed Change

We could tweak this a little, and say you need query perms for the Card's query to be able to update the query, but not the other columns. e.g.: 

```
write perms for card.dataset_query, card.results_metadata = "curate" (write) perms for parent Collection && query perms for Card's query

write perms for other columns = "curate" (write) perms for parent Collection
```

People without Card 1 permissions can update non-query columns (e.g. `:name` or `:description`) for Card 2, but not the query itself (since they don't have perms for Card 1 itself).

We will continue to disallow cloning Card 2 unless you have perms for Card 1.

Thoughts @salsakran @paulrosenzweig

**Comment by salsakran** [comment]
To make explicit an underlying constraint -- 
we're re-running the query on save to generate metadata for the results of a query.
We started doing this so that it could be used in the query builder as a nested query? [is this right?]

**First things first**
I'd like to make sure we don't lose sight of the top level concern for this issue, which is the ability to view a card in a dashboard if I have read access to the collection a dashboard is in (irregardless of what's in that question wrt nested queries, data access permissions, field values, etc). 

**Edit permissions** 
One thing to point out wrt edit permissions is that if you have the edit bit for a collection you also have read (since they're not separate bits), and hence you have the right to view its contents.

Hence you have the right to edit any card, and strip away anything that isn't 
```
select * from {{#1}}
```
Effectively, this means you have the right to view any nested questions that are used in any query in the collection.

The alternative is operationally a nightmare basically what I was dealing with last week -- the inability to give readers access to just a dashboard that was comprised of cards that under the hood use nested queries. Additionally, this means that if someone refactors a card in a collection to strip out a commonly used sub-select, they'll break things upstream.

One alternative makes the granting of an edit bit much bigger of a deal while the other makes an entire class of use cases (I want to give this group access to this dashboard and nothing else) all but operationally impossible if people actually use our SQL organization tools as-designed. The former strikes me as a better world to live, and is at least auditable. 

Where this is all leading me is the need for something similar to the data access permissions "block all usage of this question for this group" that is stronger than a "no access".

**Comment by camsaul** [comment]
@salsakran 

> we're re-running the query on save to generate metadata for the results of a query.
> We started doing this so that it could be used in the query builder as a nested query? [is this right?]

We only do this if 

a) the frontend client doesn't pass in the metadata when you save a Question (it is supposed to do this, and currently does)
b) we need to run the query to determine metadata. For MBQL queries that don't have aggregations we can infer the metadata from the query itself. With aggregations we need to run the query to get proper fingerprints which are required for auto-binning.

So normally we don't actually run the query when you save the Card. Either way, you do have to have ad-hoc query perms to to set the query of a Card, so you should be able to run it regardless. Otherwise you could just set the query of a Card to any random query and then see the results

**Comment by camsaul** [comment]
I'm not really following what you're talking about RE editing:

> Hence you have the right to edit any card, and strip away anything that isn't
>
> ```
> select * from {{#1}}
> ```

are you saying we should parse the SQL and confirm the source query hasn't changed, and allow arbitrary query changes so long as they don't change the source query?

**Comment by camsaul** [comment]
I think everyone is all on the same page WRT how _read_ permissions should work -- that's clear. If you have collection read perms, you should be see all the Cards in the collection. That's how it was always supposed to work -- we can fix the regression mentioned here where it's not working in some cases. It's just how write perms should work that is an open question

**Comment by camsaul** [comment]
See also #15182 -- we should separate out the concepts of "can read [metadata]?" vs "can query?"

**Comment by paulrosenzweig** [comment]
> the ability to view a card in a dashboard if I have read access to the collection a dashboard is in

Even without complications around nested questions, this doesn't currently work. Viewing perms to a dashboard doesn't grant viewing perms on its cards. You see this UI:

![image](https://user-images.githubusercontent.com/691495/112033587-f2424180-8b13-11eb-8830-9b58acb62b08.png)

I agree having dashboard access grant card access is better behavior though. We'll need to nest the query requests within a dashboard's scope like we do for embeds/public. We should also probably nest metadata/field values requests which is related to #13537.

**Comment by perivamsi** [comment]
context: https://metaboat.slack.com/archives/C010L1Z4F9S/p1710344839424839?thread_ts=1710329196.497689&cid=C010L1Z4F9S

**Comment by camsaul** [comment]
So as far as I can tell this is actually working on 50/`master`, this is the test I used to verify it:

```clj
(deftest nested-query-permissions-test
  (testing "Should be able to run a Card with another Card as its source query with just perms for the former (#15131)"
    (mt/with-no-data-perms-for-all-users!
      (mt/with-non-admin-groups-no-root-collection-perms
        (mt/with-temp [:model/Collection allowed-collection    {}
                       :model/Collection disallowed-collection {}
                       :model/Card       parent-card           {:dataset_query {:database (mt/id)
                                                                                :type     :native
                                                                                :native   {:query "SELECT id FROM venues ORDER BY id ASC LIMIT 2;"}}
                                                                :database_id   (mt/id)
                                                                :collection_id (u/the-id disallowed-collection)}
                       :model/Card       child-card            {:dataset_query {:database (mt/id)
                                                                                :type     :query
                                                                                :query    {:source-table (format "card__%d" (u/the-id parent-card))}}
                                                                :collection_id (u/the-id allowed-collection)}]
          (mt/with-test-user :rasta
            (testing "Sanity check: should not be allowed to read root Collection"
              (is (not (mi/can-read? collection/root-collection))))
            (testing "Sanity check: should not be allowed to read Collections before granting permissions"
              (is (not (mi/can-read? allowed-collection)))
              (is (not (mi/can-read? disallowed-collection)))))
          (perms/grant-collection-read-permissions! (perms-group/all-users) allowed-collection)
          (testing "Sanity check: should be allowed to read allowed-collection after granting permission"
            (mt/with-test-user :rasta
              (is (mi/can-read? allowed-collection))))
          (mt/with-test-user :rasta
            (letfn [(process-query-for-card [card]
                      (mt/user-http-request :rasta :post (format "card/%d/query" (u/the-id card)))
                      #_(qp.card/process-query-for-card
                       (u/the-id card) :api
                       :run (fn [query info]
                              (let [info (assoc info :query-hash (byte-array 0))]
                                (qp/process-query (assoc query :info info))))))]
              (testing "Should not be able to run the parent Card"
                (is (not (mi/can-read? parent-card)))
                (is (= "You don't have permissions to do that."
                       (process-query-for-card parent-card))))
              (testing "Should be able to run the query (#15131)"
                (is (not (mi/can-read? parent-card)))
                (is (mi/can-read? child-card))
                (is (= [[1] [2]]
                       (mt/rows (process-query-for-card child-card))))))))))))
```

it passes with no changes to the code. Note that it works with either `user-http-request` or with `qp.card/process-query-for-card`, so either version can be used depending on where we want to put the test `metabase.api.card-test` vs. `metabase.query-processor.card-test` respectively)

I'll follow up and see if I'm just missing something or if this actually works as expected now here https://metaboat.slack.com/archives/C04DN5VRQM6/p1716318808152179

**Comment by camsaul** [comment]
Ok @luizarakaki did a sanity check for me and confirmed he can't repro it either, so I'll get #42972 (tests for this) merged in and close this out as fixed in 50
