### ISSUE TITLE
Pivot table export

### ISSUE THREAD

**Issue by mitesh-b** [metabase/metabase#15132]
**Describe the bug**
I have created pivot table and now when i am trying to export as csv or xlsx, Getting response as **Not Found**

**To Reproduce**
1. Create pivot table 
2. Try to export 

**Expected behavior**
Should be able to export as csv what we can as data in pivot table.

**Screenshots**

**Information about your Metabase Installation:**

Using latest version 0.38.1

**Comment by flamber** [comment]
Cannot reproduce in 0.38.1 - are sure you're not using 0.38.01?
Please post "Diagnostic Info" from Admin > Troubleshooting.
And the full stacktrace from Admin > Troubleshooting > Logs.

**Comment by Ellerden** [comment]
Same here, 0.38.1 — expected to export csv with row totals and grand totals
![image](https://user-images.githubusercontent.com/7187553/111210499-604fab80-85de-11eb-9dc6-d03d8aed28ba.png)
but got plain table without pivoting, which was unexpected: 
![image](https://user-images.githubusercontent.com/7187553/111210772-b290cc80-85de-11eb-8fa1-9450ce878497.png)

Great job on pivot tables by the way — as one more improvement can I also suggest that it would be possible to use pivot table results in another visualization charts – e.g. bars for cohort analysis.

**Comment by flamber** [comment]
@Ellerden There's an issue open about that #2473 - this issue was about an error **Not found** when downloading.
