### ISSUE TITLE
Help, the date filters in question don't work for me

### ISSUE THREAD

**Issue by Kvothe7** [metabase/metabase#15147]
HI

Please help, I'm new to metabase. I ran the metabase from the jar file, swapped the database from H2 to Postgresql, connected the metabase to the data also on postgresql (another server), everything is on ubuntu.
Everything works fine for me, the data is visible in the metabase. All reports work, but if I use the date filter in the question (defined in the query or set with the filter option when viewing the question) I get the message "No results".

If I turn off the date filter, the results are. If I start digging through the data question, the dates work.

The database is the sale of goods /

The problem occurs when, when creating a question, I select the table with the items of orders (1) and join the table with orders where, which includes the creation date (2). I set the filter, e.g. the last 30 days (3), the date filter type does not matter.

![image](https://user-images.githubusercontent.com/80524173/110942466-20689a00-833a-11eb-990e-a108be49f05d.png)

SELECT "public"."mag_pozycje"."jm" AS "jm", sum("public"."mag_pozycje"."wartosc_netto") AS "sum"
FROM "public"."mag_pozycje" FULL JOIN "public"."mag_dokum" "Dokumenty - Mag Do Kum" ON "public"."mag_pozycje"."mag_dokum_id" = "Dokumenty - Mag Do Kum"."id"
WHERE CAST("Dokumenty - Mag Do Kum"."data" AS date) BETWEEN CAST((CAST(now() AS timestamp) + (INTERVAL '-30 day')) AS date)
   AND CAST((CAST(now() AS timestamp) + (INTERVAL '-1 day')) AS date)
GROUP BY "public"."mag_pozycje"."jm"
ORDER BY "public"."mag_pozycje"."jm" ASC

if I do a question only on the order table, the date filter works.

The problem occurs when I have a question for another table and I join the date from another.

With other types of data, I have no problem.

PS. Of course, in the settings, I set all table relationships in accordance with the database model, although metabase did it itself :)

I am begging for help, I have wasted a lot of time to solve the problem :(

**Comment by flamber** [comment]
Hi @Kvothe7 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Without knowing which column type `"public"."mag_dokum"."data"` is or if there's even any data the past 30 days, then it's difficult to know. And what is the Field Type in Admin > Data Model.
