### ISSUE TITLE
LDAP user authorization failed with `$` in password

### ISSUE THREAD

**Issue by tengattack** [metabase/metabase#15145]
**Describe the bug**
LDAP/AD user authorization failed with `$` in password

**Logs**
No need logs

**To Reproduce**
1. Set ldap authorization active
2. Login user with `$` character in password
3. authorization failed

**Expected behavior**
Authorization success with `$` character in password

**Screenshots**

**Information about your Metabase Installation:**
You're on version v0.38.1
Built on 2021-03-03

**Severity**

**Additional context**

**Comment by noahmoss** [comment]
Hi @tengattack, I'm not able to reproduce this issue. Do you have any more context about how this occurred, or any specific errors/logs?
