### ISSUE TITLE
Wrong series label in multiple series scatterplot

### ISSUE THREAD

**Issue by ilyaminati** [metabase/metabase#15150]
**Describe the bug**
I have a PostgreSQL table with one categorical column and four numeric columns. I made a scatterplot with one of the numeric columns as the X axis and the other 3 numerics as separate series.

When hovering over a data point, the pop-up sometimes uses the wrong label. For example, in this screenshot, the series label FNR is shown twice. One the two FNR labels corresponds to a value from the actual FNR series, and the other FNR label corresponds to a value from a different series.

![Screen Shot 2021-03-12 at 11 26 59 AM](https://user-images.githubusercontent.com/199182/110969072-43894e80-8326-11eb-8477-7c1f871adabb.png)

The actual SQL column names are correct and the chart legend is also correct. The labels get confused when hovering on some series, but not others.

This may be related to older closed bugs:
https://github.com/metabase/metabase/issues/3669
https://github.com/metabase/metabase/issues/3599

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.209-160.339.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @ilyaminati 
The first line is the X-axis, second line is the series you are currently hovering, but that might replace whichever field is the first on the Y-axis - that's where the confusion hits, understandably.

**Reproduce:**
1. Custom question > Sample Dataset > Reviews
2. Summarize Count, Sum of Rating, Distinct ProductID by Rating:Unbinned
![image](https://user-images.githubusercontent.com/1447303/110973148-2754d400-835d-11eb-9c62-926bc633dd45.png)
3. Scatter viz > set X-axis = Rating and Y-axis = Count, Sum and Distinct
4. Hover one of the "Sum of Rating" series dots - notice the tooltip displays "Sum of Rating" as the twice, but with different values, and there's no "Count" series:
![image](https://user-images.githubusercontent.com/1447303/110973103-1906b800-835d-11eb-9774-500126ab293f.png)

Very related to #11395

**Comment by alxnddr** [comment]
Fixed in https://github.com/metabase/metabase/pull/15435
