### ISSUE TITLE
Order of charts in Dashboard Subscription seems random

### ISSUE THREAD

**Issue by Curbsid** [metabase/metabase#15168]
**Describe the bug**
When a dashboard subscription is sent, then order of charts/tables does not seem to follow any logic manageable by the user. This leads to unprofessional and confusing emails.

**Expected behavior**
We expect the charts to display in the order they are arrange on the dashboard. LtR and Top to Bottom,

**Severity**
We cannot shift from Pulses to Dashboard subscription until this is corrected.

**Comment by flamber** [comment]
Duplicate of #15030
