### ISSUE TITLE
Click Behavior does not work for ID field of non-numeric type (UUID, etc)

### ISSUE THREAD

**Issue by elawre02** [metabase/metabase#15170]
**Describe the bug**

It appears that cross-filtering doesn't work for all field types on a dashboard. For instance, often there's a need to cross filter a dashboard on an ID (i.e. Account ID, Org ID, etc) and these field types are typically set `entity key` or `foreign key`. When attempting to set up the cross filter, for these types, there's no option for picking that respective ID field. However, if you change that fields, field type to category, then the corresponding field shows up and is accessible for cross filtering. 

There would be great utility in being able to cross filter IDs especially on a dashboard that shows multiple ids so that you can automatically click on one id to update the whole dashboard. 

**Logs**
None. 

**To Reproduce**
1. Create and save a new question with an id field (whose field settings are "entity key")
2. Create a new dashboard adding a filter for the ID field to listen to and the question you just created
2. Click on "click behavior" to add a click behavior for your ID field
3. Click on "update a dashboard filter" 
4. From the available filters list click on your ID field
5. Attempt to add the ID field to the ID available filter (Note, your ID field does not appear) 

**Expected behavior**
The ID field in your question should appear as field that you can link to the available filters. 

**Screenshots**
Happy to provide a screenshot/clip if needed. 

**Information about your Metabase Installation:**

- "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
- "v1.37.7-SNAPSHOT
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
Impediment on user dashboard exploration. Medium. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @elawre02 
I'm guessing that your IDs are non-numeric (UUID etc)? I cannot seem to find any workarounds for this. Tested 0.38.1

**Reproduce**
1. Admin > Data Model > Sample Dataset > Products
   a. Change "ID" field type to "No special type"
   b. Change "EAN" field type to "Entity Key"
   ![image](https://user-images.githubusercontent.com/1447303/111194308-5bc5cb80-85bb-11eb-9051-290279fd3972.png)
2. Simple question > Sample Dataset > Products - save as "Q1" and add to dashboard
3. Add ID filter to dashboard and connect to "Q1", which allows setting it for "EAN"
![image](https://user-images.githubusercontent.com/1447303/111194242-4781ce80-85bb-11eb-8694-faab2a3ed769.png)
4. Try adding "Click Behavior" for EAN column to "Go to custom destination: Dashboard" (with an ID filter) or "Update a dashboard filter" - clicking the ID filter will not allow selecting EAN column
![image](https://user-images.githubusercontent.com/1447303/111194810-dabb0400-85bb-11eb-953e-4fc771f87f00.png)

**Comment by nircelero** [comment]
+1 on fixing it.

**Comment by WiNloSt** [comment]
Since `frontend/src/metabase-lib/lib/parameters/utils/click-behavior.js` which contains the fix was introduced in https://github.com/metabase/metabase/pull/25879. And its [epic](https://github.com/metabase/metabase/issues/25618) has a milestone 0.45 set. I'll set this issue to 0.45 to reflect that as well.
