### ISSUE TITLE
Zero showing as -0.0000...89 in chart x-axis

### ISSUE THREAD

**Issue by mkopinsky** [metabase/metabase#15188]
**Describe the bug**
In a x-axis label for a bar, line, and scatter chart, instead of 0 it's displaying -0.0000000000000000089

**Logs**
The only possibly relevant javascript console error is:

```
vendor.bundle.js?fc344f13f5994a3b4142:130 [re-reselect] Invalid cache key "undefined" has been returned by keySelector function.
```
Although that happens before the data is even loaded (via POST /api/dataset) so I highly doubt it's relevant.

**To Reproduce**
1. Create SQL question in sample database with the following SQL:
```sql
select 0 AS delay, 35 as "count(*)"
union all
select 1 AS delay, 10 as "count(*)"
```
2. Convert to a bar chart, with DELAY as the x axis and count(*) as the y axis

**Expected behavior**
The data legend and x-axis should both show the value as 0. The data legend popover is correct, but the x-axis is doing some funky floating point thing.

**Screenshots**
![image](https://user-images.githubusercontent.com/591435/111368512-5d9b9780-866c-11eb-833c-969475291bd9.png)

This is clearly a client-side thing - the server is returning the values as `[[0,35],[1,10]]`

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.15.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.13-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.0",
      "date": "2021-02-16",
      "branch": "release-x.38.x",
      "hash": "471aa51"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```
We're running metabase in docker with a custom-built docker image.

**Severity**
Annoying

**Comment by flamber** [comment]
Hi @mkopinsky 
Likely the same problem as #14218 - possible workarounds in visualization Settings > Axes:
- Change "X-axis scale" to "Ordinal"
- Or change "Show x-axis line and marks" to "Compact" (but it still shows as `-0` instead of just `0`)

**Comment by mkopinsky** [comment]
Thanks! That workaround works. I'll leave it up to you whether to close this as duplicate or keep it open.
