### ISSUE TITLE
Bar Chart Display Issues when using SQL in IE and Firefox

### ISSUE THREAD

**Issue by TomUssery** [metabase/metabase#15197]
When viewing a results tile that is a bar chart in IE and Firefox, that was written using SQL the width of the bar shrinks to nothing making the chart hard to read. I am able to replicate the issue within Firefox, it didn't work at all on IE 10
it seems to be a Metabase issue - it seems to be caused when using SQL vs the WISIG
Testing the Old Version of Metabase

> - Firefox
> - for the question only with WISIG - http://mazdabi.thejrtagency.com/public/question/d571a356-654d-423c-b197-effb0ad0b75f its fixed and worked fine
> - for the question only with SQL - http://mazdabi.thejrtagency.com/public/question/54d76950-627a-4b8a-b18b-178ed9cbf7e9  not working
> - Dashboard Works for WISIG but Not SQL - http://mazdabi.thejrtagency.com/public/dashboard/c3abfff1-57b9-4660-8551-da04d74609af 

I tested the new version of Metabase - FAILED

> - Firefox
> - for the question only with WISIG - http://bi.thejrtagency.com/public/question/72559c2a-e5ff-4bf3-a094-4343882488eb its fixed and worked fine
> - for the question only with SQL - http://bi.thejrtagency.com/public/question/916d6dac-830d-4695-a1a8-88a6f3c99180  not working
> - Dashboard Works for WISIG but Not SQL - http://bi.thejrtagency.com/public/dashboard/e0b1b88e-2c46-4b3a-93a9-c9651ad5dcfd

Thanks

Tom

**Comment by flamber** [comment]
Hi @TomUssery 
Latest release is 0.38.1 - you are likely seeing #3842, but it's difficult to know without seeing your query.
Metabase has never supported IE10 and we will likely not support IE11 for much longer, like most other web apps are also removing support.
