### ISSUE TITLE
Documentation does not provide the right link to download metabase-aws-eb.zip

### ISSUE THREAD

**Issue by Wirg** [metabase/metabase#15205]
**Describe the bug**
The download link for `metabase-aws-eb.zip` is not the right one in the official documentation. Moreover the description text `Download the Metabase Docker image to upload to Elastic Beanstalk` is misleading

**To Reproduce**
Go to https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#quick-launch and read the first sentence.

**Expected behavior**
I can download the file by clicking the link and know what I am downloading

**Severity**
Probably losing some potential metabase users, at least the one trying to set it up on aws.

**Additional context**
I think https://github.com/metabase/metabase/blame/aa211a57565b8aea4c7d2d0e38e684713f2a1f5a/docs/operations-guide/running-metabase-on-elastic-beanstalk.md#L36  is the line that needs to be changed.

**Comment by paoliniluis** [comment]
Makes sense, what do you think it would be the correct concept?

**Comment by Wirg** [comment]
Hi paoliniluis,

I am not an ebs environmnent user. So I am probably not the best one to provide the proper naming.
I think for most user we can use the corresponding vocabulary on the aws form : `aws source bundle` or something like that.
![image](https://user-images.githubusercontent.com/17848620/111627665-9748db80-87ef-11eb-80e2-f0bd3b7853c6.png)

**Comment by paoliniluis** [comment]
Great! if someone runs into this, the file will always be located in https://downloads.metabase.com/v0.38.2/metabase-aws-eb.zip, changing the version to the one you want to launch

**Comment by flamber** [comment]
Fixed in #15206
