### ISSUE TITLE
Metadata UI: Cannot click element in "select a target"

### ISSUE THREAD

**Issue by tordans** [metabase/metabase#1520]
Hi, I am on the mac app.
I can select "special type": "foreign key" and I see the dropdown in "select a target", but I cannot click on the items / the click is not accepted/used.

This is what I see:
<img width="1049" alt="bildschirmfoto 2015-11-20 um 11 47 40" src="https://cloud.githubusercontent.com/assets/111561/11298220/c775484a-8f7d-11e5-9a1c-69fbf6e732e4.png">

Tobias

**Comment by squiddle** [comment]
the javascript console creates one error message for each click:

    [Error] TypeError: 'null' is not an object (evaluating 'this.state.recentlySavedTimeout') (app.bundle.js, line 40)

Environment: MacOS X Metabase v0.12.1

**Comment by camsaul** [comment]
@agilliland This doesn't look like a Mac App-specific issue, there's JS errors on the console

**Comment by agilliland** [comment]
Can you post those errors here so that we have a reference?

**Comment by camsaul** [comment]
@agilliland Read the comment above mine. Someone posted the JavaScript error

**Comment by agilliland** [comment]
@tordans , @squiddle are you able to confirm if this is still an issue for you on one of the more recent versions of Metabase?

I am trying to reproduce this right now on v0.13.3 and everything is working fine, so hopefully this is fixed and can be closed.

**Comment by tordans** [comment]
Yes it's solved. I just updated to the latest version and could use the element as intended.
