### ISSUE TITLE
Links to docs not working in builds

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#15219]
**Describe the bug**
The "Learn More" link is broken.

**To Reproduce**
1. Use custom expressions anywhere
2. Click on the "Learn More" link
3. Get a 404 (eg https://www.metabase.com/docs/vUNKNOWN/users-guide/expressions.html)

**Expected behavior**
To go the correct page.

**Information about your Metabase Installation:**
Bugbash version 80f984c

**Comment by brunobergher** [comment]
FYI @ariya

**Comment by flamber** [comment]
This is only in the test builds - not in releases.

**Comment by brunobergher** [comment]
Glad to know. Is there a way for us to know that this won't break in releases? Maybe test coverage?

**Comment by ariya** [comment]
A workaround is to use `latest` instead of `vUNKNOWN`. Therefore it falls back nicely since e.g. https://www.metabase.com/docs/latest/ always exist.

**Comment by flamber** [comment]
See #14853 for a quickfix
