### ISSUE TITLE
Custom expressions: UI is too wide when shown in the sidebar

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#15217]
so it causes horizontal scrolling and some items to be inaccessible.

**To Reproduce**
1. Start a simple question
2. Add a filter > Custom Expressions

**Expected behavior**
For it to fit the sidebar.

**Screenshots**
![Example](https://p69.f3.n0.cdn.getcloudapp.com/items/WnuBQqgw/f0a0419f-ba10-4bc2-a47a-367e5c63444a.jpg?v=afcf31a72fec37fcc21bb63445e40cb1)

**Information about your Metabase Installation:**
Bugbash version 80f984c

**Comment by brunobergher** [comment]
FYI @ariya

**Comment by ariya** [comment]
Fixed with PR #15274.
