### ISSUE TITLE
Link filter to column automatically

### ISSUE THREAD

**Issue by janmpeterka** [metabase/metabase#15212]
**My problem**
I have dashboard, adding questions. All questions are based on same base table (`Jobs`), which has column (`demand_created_at`) set as `created at` type.
I have to set filter for each question manually, instead of it connecting automatically if possible.
That's I lot of work (and not forgetting with that) that seems unnecessary

**Possible solutions**
Filter can have set default table->column to link with
- possibly after I connect one, I can in filter setting set it as default?
- or just select it manually from a) all tables or, smarter b) from tables->columns used in my dashboard

It could automatically link cards based on the first one set
- this would only work if I add one question, set filter, and start adding other. Sometimes I want to add all questions before adding filters, but doesn't seem like that big issue to me.

**Alternatives**
It could be smarter and connect based on column types
 -> but that can cause a lot of confusion if I have multiple date fields, so probably not.

**Importance**
It would save considerable frustration and time to me. Time setting filters is not that big problem - it takes few seconds to set it. But I easily forget to set it for one card and then spent a lot of time trying to find out what is wrong with my SQL/query.

**Comment by flamber** [comment]
Hi @janmpeterka Sounds like a duplicate of #4767 ?

**Comment by janmpeterka** [comment]
Oh, thanks @flamber. I was trying to find it (filtering for `filter` and `default`), but didn't find it. Closing then :)
