### ISSUE TITLE
Improve Metadata UI

### ISSUE THREAD

**Issue by tordans** [metabase/metabase#1521]
Hi, here are a few things I notices that could be improved in the metadata UI. #Usability #UserExperience.

# SOLVED ~~Issue A: Left column background~~

The background of the left columns stops before my tables are finished …
Ideally, the left column has its own scroll bar so I can scroll on the left and still see the options like "hide" on the right.

<img width="307" alt="bildschirmfoto 2015-11-20 um 11 45 12" src="https://cloud.githubusercontent.com/assets/111561/11298269/0be592f0-8f7e-11e5-958f-ed4a71fe63ee.png">

# OPEN: Issue B: Explain the "why hide" choises

- What do those options mean? / Where is the difference. Maybe add a tooltipp onmouseover to explain this.
- An more importantly: What is the consequence of my click? Are those tables treated differently? Or is it just for some reporting? Where would that reporting be?

<img width="645" alt="bildschirmfoto 2015-11-20 um 11 43 42" src="https://cloud.githubusercontent.com/assets/111561/11298301/3ee518d8-8f7e-11e5-9d44-c98861cb5f48.png">

# OPEN: Issue C: Explain the small [|_] bar in the left column

- What does it mean? What does it do? Why is it there?
- Maybe add a mouseover tooltipp on the [|_], saying what it is.
- Update: This seems to be the "METADATA STRENGTH".  But what is this. The UI should explain itself without an external documentation. Why do I need this in the overview of the sidebar? What is the UseCase or UsageScenario? And in the details, view: Why no tooltip.

<img width="308" alt="bildschirmfoto 2015-11-20 um 11 43 10" src="https://cloud.githubusercontent.com/assets/111561/11298324/562115e2-8f7e-11e5-9b43-30e9d5fb69bf.png">

# OPEN: Issue D: Improve Discoverability of Database selection

This one: <img width="471" alt="bildschirmfoto 2015-11-20 um 11 42 48" src="https://cloud.githubusercontent.com/assets/111561/11298342/7bc2d254-8f7e-11e5-9b6a-7f37e5c6a9ed.png">

This is not a game of search and catch, I guess,, and its the most important element on the page when you first open it … – and its too hard to find. Maybe move it to the main navigation as a secondary layer of navigation once you click on the "metadata" in the navigation of "people metadata databases"? Or make the design more visible for the element?

**Comment by mazameli** [comment]
Thanks for the feedback! That first issue you pointed out with the left column appears to be a bug with the Mac app, @camsaul.

**Comment by camsaul** [comment]
The Mac app is just a WebKit (i.e., Safari) window; I don't think this is a Mac App-specific issue

**Comment by camsaul** [comment]
I think these are just issues with using an old version of Safari or the Mac App on an out-of-date version of macOS. @tordans are you still seeing these issues?

**Comment by tordans** [comment]
@camsaul I updated the issue. The first one was in fact solved. The other once are usability issues, not technical issues. I think it would be very interesting to watch a new user setting up his stuff. Just like Steve Krug does in those two videos: http://uxzentrisch.de/discount-usability-testing/index.html

**Comment by mazameli** [comment]
The metadata strength and `why hide?` elements are no longer on this page. The only remaining part of this issue that's still relevant is increasing the discoverability of the database switcher, which I'm just going to open as a new issue for clarity's sake.
