### ISSUE TITLE
Search: some results are as being in a folder which doesn't exist in the data reference

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#15216]
**To Reproduce**
1. Search for "orders"
2. It shows up in this PUBLIC folder

**Expected behavior**
To be shown at the root of Sample Dataset

**Screenshots**
![Example](https://p69.f3.n0.cdn.getcloudapp.com/items/v1uNJg0X/b32e8892-9780-4abd-870c-a38400dc5581.jpg?source=viewer&v=37b6d867a37b5da5a913a05ba2f2360a)

**Information about your Metabase Installation:**
Bugbash version 80f984c

**Comment by flamber** [comment]
"PUBLIC" is the schema. The Sample Dataset only has one schema.
It should be shown, when there's more than one schema.

**Comment by brunobergher** [comment]
There wasn't more than one schema in this case. The inconsistency is what is bothering me:

![explore view](https://p69.f3.n0.cdn.getcloudapp.com/items/NQuJy4W1/b0c74ea0-7674-4fe0-b82d-9a012d5bda6c.jpg?v=0a20505d6e7126e0e864ee68fbd55f03)

**Comment by kdoh** [comment]
Yeah I think this is just a matter of us not reflecting the "if there's one schema, don't burden people with having to think about it" stance in the search context. Should be an easy tweak although I wish there was a more centralized place to keep that business logic to prevent this kind of accidental rendering difference.
