### ISSUE TITLE
FE client continues to hit automagic dashboards candidates endpoint once a second forever if it returns no results

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15220]
On the Horror Show instance, the `candidates` endpoint returns `[]`, and the FE client continues to hit the endpoint once a second forever. I'm guessing it's because it's waiting for it to actually return something? 

1. We should have some way to differentiate the states where it's actively trying to create some automagic dashboards and the FE should continue to poll vs. there genuinely being no candidates and the results genuinely being empty.
2. The FE client should use exponential backoff for polling the endpoint. It should also give up after some certain amount of time, maybe a minute or two.

To repo:

1. Visit HorrorShow instance home page. 
2. View network inspector in your browser
3. 1 API request a second forever

**Comment by flamber** [comment]
**Reproduce**
1. Admin > People > create user "U1"
2. Admin > Permissions > revoke access to Sample Dataset
3. Admin > Data Model > Sample Dataset > hide all four tables
4. Login as "U1" - every second there's a request to `/api/automagic-dashboards/database/:id/candidates`

**Comment by ranquild** [comment]
This was fixed in the new homepage https://github.com/metabase/metabase/issues/21322
