### ISSUE TITLE
Add Special Type "Amount"/"Currency"

### ISSUE THREAD

**Issue by tordans** [metabase/metabase#1522]
Hi, this is a feature request.

We use a pattern where we store amounts on "*_in_cents" columns in our database. So a donation of 10 $, 40 cents is not "10.4" but "1040". Example usage in our app: https://github.com/RubyMoney/money#usage

In my custom sql reports I make this more readable by re-formatting the column
- rename it to "amount in €" with an mysql `amount_in_cents as 'amount in €'`
- doing the math like `round(amount_in_cents/100, 2)`

I would be great if the Metadata UI could provide such a feature.
- Maybe by adding a special type "Amount" or "Currency"?
- Maybe even with a "Specifiy currency"-Secondary Select? Or a config in the configuration "Whats the currency symbol?" => "€"?
- And by checking for a *_in_cents postfix wich automatically adds the calculation

<img width="1054" alt="bildschirmfoto 2015-11-20 um 12 11 14" src="https://cloud.githubusercontent.com/assets/111561/11298522/d7d13328-8f7f-11e5-8859-610563f419bc.png">

Best, Tobias

**Comment by javiercr** [comment]
+1 to this, I have the exact same use case (Rails + RubyMoney = columns in cents).

**Comment by adamteece** [comment]
This would be great for our team as well.

**Comment by rmontgomery429** [comment]
I personally would really like this to get fixed :smile: https://api.bountysource.com/badge/issue?issue_id=28453783

**Comment by rafaelveloso** [comment]
+1

**Comment by tordans** [comment]
Hey guys, I will close this request now, since the feature I requested is solved via the "Custom Field" Feature. You can choose the `amount_in_cents` there and then divide it by a number like 100.

**Comment by javiercr** [comment]
@tordans I use the same approach, however I have to say it is not so obvious for not experienced users. I'd love to see proper support for currency fields.

**Comment by salsakran** [comment]
Let's leave it open. We want to be able to handle this  stuff automatically instead of using custom fields all over the place. Things like formatting, symbols, rounding, etc should all be tied to something being a currency.

**Comment by repayjason** [comment]
We need this too!

**Comment by LemonAndroid** [comment]
@tordans Is the issue still open?

**Comment by mazameli** [comment]
Going to close this as we implemented global, per-column, and per-question column formatting settings in version 0.31, which also included a Currency metadata type.

**Comment by antoine-lizee** [comment]
Sorry to reopen this, but now that we do have per-column formatting, I'm just wondering how hard it would be to add a "Currency in cents" format?

It's very common to store amounts in cents, but it's cumbersome (and not super transparent) to use the advanced formatting option to multiply the amount per `0.01`.

**Comment by tlrobinson** [comment]
@antoine-lizee I agree it's not the most obvious way, but I wanted to make sure you knew you could set the multiplier on the underlying field int he data model, which is then used by default for all columns based on that that field, unless overridden per question/column.

![screenshot 2019-02-21 13 09 03](https://user-images.githubusercontent.com/18193/53202187-b8bc4680-35da-11e9-9494-0df947f2373b.png)

It seems to correctly apply to aggregation and breakout columns, however I filter inputs are not scaled, so it's not ideal.

**Comment by reidab** [comment]
@tlrobinson I'm not clear how this actually solves anything…  If I have a number stored in cents that I want to display in dollars, then I need to divide by 100, not multiply.

**Comment by flamber** [comment]
@reidab If you want to divide, then you can use "Multiply by a number" with `0.01`

**Comment by reidab** [comment]
Thanks — somehow my brain forgot basic math this morning. 😥

**Comment by allan-simon** [comment]
@flamber , you can't put decimal values :(

**Comment by flamber** [comment]
@allan-simon Yes you can. Which version are you trying with? It might mark the input red, but you can still continue.

**Comment by allan-simon** [comment]
ah yes I've stopped to the "it's red so I can't do it"
