### ISSUE TITLE
No loading spinner when clicking a Collection on the home page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15221]
To repro:

1.  Go to Horror Show instance main page
2. Click "Browse all items"
3. Page hangs for ~10 seconds with no feedback that something is happening before finally loading the next page
4. Sometimes it just takes you to "Something's gone wrong" if the endpoint takes too long to return
5. If you do make it to the Collections page, it's so slow it basically freezes the whole app and you can't do anything like use search

Related: #14601

**Comment by flamber** [comment]
Related #14603
