### ISSUE TITLE
metabase/metabase-enterprise-head Docker image doesn't have enterprise extensions

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15226]
`metabase-enterprise-head` Docker image does not actually contain enterprise code. Probably a build misconfiguration -- the new image was added this week and we haven't worked out all the kinks yet.

@paoliniluis let's try to figure out what's not working here... either the env var doesn't work, or I set up DockerHub wrong

**Comment by camsaul** [comment]
@paoliniluis have you tried the build locally with the env var to make sure it has EE extensions? I haven't actually tried that yet

**Comment by paoliniluis** [comment]
Sorry for not seeing this eariler, the build with the EE should be "docker build . --build-arg MB_EDITION=ee"

In the original PR I mentioned MB_VERSION, but should be **MB_EDITION**, I'm very sorry about that

**Comment by camsaul** [comment]
Oh yeah that makes sense. I put `MB_VERSION` in DockerHub. I'll try changing it.

**Comment by paoliniluis** [comment]
this one should be closed after the change in the build arg in dockerhub
