### ISSUE TITLE
Permissions tables are not responsive

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15232]
**Describe the bug**
Permissions tables are not responsive. They Get assigned a hard coded width on a page load, and that's it. If you want to resize your browser, tables don't resize.

**Logs**
N/A

**To Reproduce**
1. Go to `/admin/permissions/databases` or `/admin/permissions/collections`
2. Change browser width
3. Observe the tables staying the same size

**Expected behavior**
- Tables should resize and fit the browser width.
- Tables should have some min-width set
- Tables should possibly even have some max-width set because they can look pretty weird on an ultra-wide screens

**Screenshots**
https://share.getcloudapp.com/YEuX7Jr4

**Information about your Metabase Installation:**
N/A

**Severity**
UX, maximum P3.

**Comment by flamber** [comment]
Probably part of the reason for #8165

**Comment by nemanjaglumac** [comment]
Outdated.
We changed the UI a long time ago.
