### ISSUE TITLE
Hitting return when modifying a custom expression incorrectly discards changes

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15241]
[See this GIF example](https://share.getcloudapp.com/v1uNJQKK)

1. Create a filter expression in the notebook editor and click Done
2. Click on the filter token to open up the popup to edit it
3. Make some changes, then hit return/enter
4. Your changes will be discarded instead of being applied.

**Comment by ariya** [comment]
Here's another reproducing step:

1. Ask a question, Custom question
2. Sample dataset, Products table
3. Add filters to narrow your search
4. Choose Price, Greater than 1, click Add Filter
5. Click on the new "Price is greater than 1" filter
6. Click on the left chevron arrow, Custom Expression
7. Complete the expression to `[Price] > 1 AND [Price] < 5`
8. Press Enter

Expected:

There are two filters: "Price is greater than 1" and "Price is less than 5".

Actual:

There is only one filter: "Price is greater than 1".

**Comment by ariya** [comment]
Fixed with PR #15268.
