### ISSUE TITLE
Potentially Useful Questions in data reference produce weird results in query builder

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1524]
If you look at, for example, the Product ID field in the Orders table, and select `All distinct values of Product ID`, I would have expected to see the grouping option in the query builder turn into `Product ID`, instead of just saying `field`. I think this might be happening because Product ID isn't set as a Dimension in the metadata.

![screen shot 2015-11-20 at 2 25 17 pm](https://cloud.githubusercontent.com/assets/2223916/11313566/ae332838-8f92-11e5-9a59-00f89ff62bf2.png)

**Comment by kdoh** [comment]
As far as I can tell this has been fixed.
