### ISSUE TITLE
Custom Expression editor is removing spaces too aggressive

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15243]
**Describe the bug**
When trying to type a Custom Expression, then spaces are aggressively being removed making it harder to create more advanced formulas, since you have to go back and add the spaces manually.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Custom Column - try _typing_ the following:
   a. Typing `[ID] = 1 OR [ID] = 2` is turned into `[ID]=1OR[ID]=2` while typing - onblur will correctly fix it, likely because of the aggressive post-formatting like in #13306
   b. Typing `contains([Title], "yes") or contains([Title], "no")` is turned into `contains([Title],"yes")orcontains([Title],"no")` while typing, which is invalid and you need to manually add spaces around `or` to make the formula work.

**Expected behavior**
Don't remove spaces while typing (or at least not that aggressive) - that can be done in post-formatting.

**Information about your Metabase Installation:**
Tested 0.36.8 thru 0.38.2 and `master`

**Comment by howonlee** [comment]
note for posterity: firefox only

**Comment by howonlee** [comment]
note: this one isn't obviated by the ace refactor, so root cause is something w/ the regexes
