### ISSUE TITLE
The new "contains" behavior for field value lookup doesn't work outside of dashboards

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15240]
Trying to look up a field value when filtering by typing part of the middle of the string doesn't work in the GUI query builders or SQL filter widgets.

Examples:
- GUI: https://share.getcloudapp.com/04uJlQoy
- SQL: https://share.getcloudapp.com/OAugk8nl

**Comment by flamber** [comment]
The GUI question uses "Is" as operator. And if you change to "Contains" then you're likely seeing #7239.
Related to #7231
