### ISSUE TITLE
Custom Expression sometimes shows a big error, when formula is not complete

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15246]
**Describe the bug**
When typing a Custom Expression formula and not finishing the function and blurring the input will show big error message.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Summarize > Custom Expression > type `countif(` and then blur the input
![image](https://user-images.githubusercontent.com/1447303/111769576-ad1ad700-88a9-11eb-8e2c-dc0a8eab6dd6.png)

**Expected behavior**
Custom Expression should not throw Token sequence errors in the UI - perhaps in the console if needed - but more human (and shorter) errors should be displayed.

**Information about your Metabase Installation:**
Tested 0.35.0 thru 0.38.2 and `master`

For historians #12268

**Comment by ariya** [comment]
Unfortunately, this error message is originated from the parser library (Chevrotain) used in the underlying custom expression. To make matter worse, this message is also not translateable.

Until we're ready to swap the parser to something, we need to come up with a different workaround to improve the feedback and to reduce the complexity of the error message.

**Comment by ariya** [comment]
Some of the common ones should be taken care by #15658.
