### ISSUE TITLE
Click Behavior not parsing measure value for first row on Pie chart

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15250]
**Describe the bug**
Click Behavior not parsing measure value(s) for first row on Pie chart

**To Reproduce**
1. Simple question > Sample Dataset > Products
2. Summarize Count by Category, and change visualization to Pie chart
![image](https://user-images.githubusercontent.com/1447303/111789803-d5aecb00-88c1-11eb-9d44-8584e2788fde.png)
3. Add to dashboard and add "Click Behavior" - any type (custom destination/cross filter) - save dashboard
4. Hover the Doohickey slice (which is the first result row) with Count 42 and click - the value `42` is not parsed along.

**Information about your Metabase Installation:**
Tested 0.37.0 thru 0.38.2

Related to #13597

**Comment by MiaPony** [comment]
Great!
