### ISSUE TITLE
"Duplicate" dashboard modal says it "failed", when it actually did duplicate successfully

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15256]
**Describe the bug**
When users with curate access wants to duplicate a dashboard in a collection they are presented with the modal where they can enter new name, description, choose collection and finally click "Duplicate" button. Once that button is clicked, it turns to red-danger button "FAILED", but at the same time you can see bubble with the "Dashboard duplicated - See it" in the lower left corner.

Note, dashboard is indeed duplicated.

**Logs**
No errors.

**To Reproduce**
_As an admin or normal user with collection curate access level_
1. Go to `/collection/root`
2. Click on `...` menu for any dashboard in the collection
3. Choose "Duplicate this item"
4. Modal appears, click "Duplicate" button
5. Notice it says FAILED
    - Notice the bubble with the "Dashboard duplicated - See it" in the lower left corner.
    - Notice the dashboard being duplicated underneath the modal that is still open, btw
6. You can click on the "Duplicate" button in the open modal as many times as you want and it will keep duplicating dashboards ad infinitum
    - Weird thing: you can duplicate the dashboard even when the button says "FAILED"

**Expected behavior**
If users have curate permissions, they should be able to duplicate the dashboard by clicking on the "Duplicate" button in the modal that should then properly close.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/RBu4oY4n/2e77e634-db45-42cf-b307-206f99b4b141.gif?source=viewer&v=ffaae2a2c2a969fba4a5c9f43955cff8)

**Information about your Metabase Installation:**
- Metabase version: v0.38.3-SNAPSHOT
- Metabase hosting environment: local dev, release-x.38.x
- Metabase internal database: H2 (default), sample dataset

**Severity**
P3?

**Additional context**
If you click on "See it" link in the bubble, it will properly take you to the duplicated dashboard.

**Comment by gusaiani** [comment]
At the moment a successful duplication no longer renders `Failed` in the button.

It renders `Success`.

But the modal remains open.

Investigating the logic behind this to be able to close the modal automatically.

**Comment by kulyk** [comment]
Hi @gusaiani, I fixed that while working on the URL slugs at #15989
This issue can be closed as soon as the PR is merged

**Comment by gusaiani** [comment]
Thanks for letting me know, @kulyk.

No urgency, but if you can point me to the changes that fixed it, I will be very grateful to learn that from you.

**Comment by kulyk** [comment]
Sure, [this is it](https://github.com/metabase/metabase/pull/15989/files#r630108086)
