### ISSUE TITLE
Users with collection curate permissions and no data permissions can't unarchive question

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15253]
**Describe the bug**
Users with collection curate permissions and no data permissions can archive a question from any collection (tested root and also user's personal collection!), but when they click on "Undo" they are greeted with "Sorry, you don’t have permission to see that." screen.
Note that this doesn't happen for dashboards.

**Logs**
`PUT /api/card/:id 403 forbidden`

**To Reproduce**
1. Log in as non-admin user with collection curate access **and no data permissions**
2. Go to `/collection/root/` or to user's personal collection
3. Click ellipsis icon next to any question
4. Choose "Archive this item"
5. Notice bubble in the lower left corner saying "Item archived - Undo"
6. Click "Undo"
7. You'll see "Sorry, you don’t have permission to see that." screen
8. Alternatively, if you visit `/archive` you'll notice few things
    - There are no icons to unarchive items (this is a separate issue and probably related to #15080)
    - You can still click the checkbox when you hover question's icon
    - Bottom bar action panel will appear with "Unarchive" option
    - Clicking on it will again result in `403` and "Sorry, you don’t have permission to see that." screen

**Expected behavior**
Users with curate access level should most definitely be able to unarchive the question that they previously were able to see and archive.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/111810855-bff7d080-88d6-11eb-8445-ebf30fd7ce4d.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
- Metabase version: v0.38.3-SNAPSHOT
- Metabase hosting environment: local dev, `release-x.38.x` branch
- Metabase internal database: H2 (default), sample dataset

**Severity**
Probably strong P2. Especially since this happens for questions in user's personal collection. Without admin's help, once you archive them they are effectively lost.

**Comment by flamber** [comment]
This used to work in 0.31.2 - not sure when it stopped working, but it fails on 0.34.3 too.
Related to #5090

**Comment by nemanjaglumac** [comment]
Updated the title to be more specific.
