### ISSUE TITLE
Parameter include_deactivated for /api/user/

### ISSUE THREAD

**Issue by fnk** [metabase/metabase#15278]
**Describe the bug**
The API returns all users, also deactivated ones, when caling `/api/user?include_deactivated=false`.
While the documentation (https://github.com/metabase/metabase/blob/aa211a57565b8aea4c7d2d0e38e684713f2a1f5a/docs/api-documentation.md#get-apiuser) only describes the behaviour where `include_deactivated` is set to `true` i would expect it to also exclude deactivated users when setting it to `false`.
Our current workaround is to not use the parameter `include_deactivated` at all when we need only active users.

**Expected behavior**

The API returns only active users when calling `/api/user?include_deactivated=false`

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.4.0-186-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "... [redacted] ..."
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.0"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-19",
      "tag": "v1.36.4",
      "branch": "enterprise-release-1.36.x",
      "hash": "0324e9c"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}`

**Additional context**

We are using the API to syncronize users and permissions from an external system.

**Comment by GabiAlifraco** [comment]
I have the problem that people NOT superuser can view ALL personal identification only calling /api/user. Is there any solution to restrict this information to normal users?  

We have the same problem that normal users can call /api/database and know what engine is used which is a security risk to the organization.

**Comment by flamber** [comment]
@GabiAlifraco Completely unrelated to this issue. That endpoint is used for subscription emails autocomplete etc.
There's work being done to make more granular permissions: https://www.metabase.com/roadmap/
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
