### ISSUE TITLE
Serialization: allow partial serializations

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15284]
Allow option to be able to specify which artifacts to dump:
- type (eg. all cards)
- type + ID (just a specific card)

In each case all dependent artifacts (collections, DBs, users, ...) should be included as well.

Originally EE221 https://github.com/metabase/metabase-enterprise/issues/221

**Comment by luizarakaki** [comment]
For now we are supporting the following flags:

- `-c`, `--collection` ID Export only specified ID; may occur multiple times
- `-C`, `--no-collections` Do not export any collections or contents; not compatible with -c
- `-D`, `--no-data-model` Do not export any data model entities; useful for subsequent exports
- `-f`, `--include-field-values` Include field values along with field metadata
- `-s`, `--include-database-secrets` Include database connection details (in plain text; use caution)
- `-S`, `--no-settings` Do not export settings.yaml

If someone wants more control, please open an issue with the details.
