### ISSUE TITLE
Users with read permissions are offered to save new dashboard in collections they only have read access to

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15281]
**Describe the bug**
Users with read permissions are offered to save new dashboard in collections they only have read access to. That leads to confusion and an error.
NOTE:
- The UI is initially correct and such users see only "My personal collection" but the error happens when they use a search functionality (see repro steps below)
- However, they can use the search and if type the name of a collection that lives inside a root (that they have read access to)
- The collection will be shown/offered

**Logs**
`403` error in the console.

**To Reproduce**
1. Click on `+` icon in the header and choose "New dashboard"
2. Modal will be shown - enter some name for the dashboard
3. You should see your personal collection 
4. Click on the selection menu - it will open a dropdown
5. Click on the "loupe" icon to be able to search
6. Search for any collection that lives inside the root collection (given that you have read access to it)
7. You will see that collection offered
8. Click on it - it will now be selected as a "go to collection"
9. Click "Create" button
10. Inline error will be shown

**Expected behavior**
Search shouldn't return collections users don't have curate access to

**Screenshots**
Initial UI
![image](https://user-images.githubusercontent.com/31325167/112001440-44d52b00-8b1f-11eb-9525-cdb88ed42bf8.png)

After searching for a collection user has read access to, and trying to save in it
![image](https://user-images.githubusercontent.com/31325167/112001210-093a6100-8b1f-11eb-9577-b0f19b2a8a73.png)

**Information about your Metabase Installation:**
- Metabase version: v0.38.3-SNAPSHOT
- Metabase hosting environment: local dev, release-x.38.x
- Metabase internal database: H2 (default), sample dataset

**Severity**
P3

**Additional context**
Realated to #14052 and to #15280

**Comment by nemanjaglumac** [comment]
This gets even more weird with nested collections. We have the following structure In the test snapshot:
- Our analytics
    - First collection
        - Second collection
            - Third collection

Read only user has READ permissions for ALL these collections. 
1. Notice that initially "First collection" is offered
2. If you click on its name directly, it should be selected but it acts like we clicked `>` icon
3. Now the "Second collection" is offered
4. Click on it, it's still not selected and it again acts like we clicked `>` icon
5. But this time "Third collection" is not shown
6. Go to the search icon and search for "third"
7. "Third collection" is shown and now when you click on it it IS selected as a go to collection
8. Click "Create" and you'll see the error

![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/KoudxZEz/8edc3a38-b915-4f59-adda-08650ca345b4.gif?v=619cce25845a910e60ae9ea7cf2add9a)

**Comment by flamber** [comment]
It's some of the missing stuff on #7881
