### ISSUE TITLE
Spelling Mistake in new_user_invite.mustache

### ISSUE THREAD

**Issue by boyadjisbenoit** [metabase/metabase#15298]
**Description**
In current master of Metabase, in `new_user_invite.mustache` email, `analytics` is spelled wrongly (`analtyics`)

**Severity**
Minor

Thanks !

**Comment by flamber** [comment]
Whoops, that slipped through in #14230, so it was actually part of 0.38.0

**Comment by flamber** [comment]
Fixed by #15300
