### ISSUE TITLE
Localized texts are always in Spanish

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#15302]
Metabase version: 3071de8

When the user switches to a different language than English the UI is always in Spanish.
Screenshots below:

<img width="658" alt="Snímek obrazovky 2021-03-23 v 15 03 21" src="https://user-images.githubusercontent.com/1764151/112158956-f2f8d780-8be8-11eb-9391-22ee5a2c479f.png">
----
<img width="656" alt="Snímek obrazovky 2021-03-23 v 15 03 12" src="https://user-images.githubusercontent.com/1764151/112158969-f5f3c800-8be8-11eb-96c9-1af412ce8c99.png">

**Comment by kounoike** [comment]
I got such situation.
solution: `apt install gettext`

**Comment by flamber** [comment]
`master` does not use `gettext` anymore - it was removed in #15189, which likely also caused this problem.

**Comment by paoliniluis** [comment]
All translation JSONs other than "en" are populated with the "es" locale

**Comment by flamber** [comment]
This:
https://github.com/metabase/metabase/blob/aa211a57565b8aea4c7d2d0e38e684713f2a1f5a/bin/i18n/src/i18n/common.clj#L24
Should have been this:
```
    (.parseCatalog parser (io/file (locale-source-po-filename locale)))))
```
