### ISSUE TITLE
SQL Questions throw syntax error when highlighted

### ISSUE THREAD

**Issue by alxndrsn** [metabase/metabase#15315]
**Describe the bug**

Highlighting text changes the way it's interpreted as SQL:

**Observed**

### not highlighted - working

![Screenshot_2021-03-24_11-05-41](https://user-images.githubusercontent.com/191496/112275894-268f3c80-8c91-11eb-9ea1-7b3d67cdcae8.png)

### highlighted - not working

![Screenshot_2021-03-24_11-05-55](https://user-images.githubusercontent.com/191496/112275907-2a22c380-8c91-11eb-97dc-1f02221e6590.png)

**Expected**

Highlighting text in a SQL statement should have no effect on how the statement is interpreted.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chromium 89.0
- Your operating system: linux
- Your databases: postgres 12.5
- Metabase version: (e.x. 0.19.3): 0.38.1
- Metabase hosting environment: 
- Metabase internal database: postgres 12.5

**Severity**

Annoying and quite surprising

**Comment by flamber** [comment]
Hi @alxndrsn 
It's a feature that allows you to select parts of your SQL and only "Run selected text".
![image](https://user-images.githubusercontent.com/1447303/112289351-8801dc00-8c8e-11eb-8028-d084488bf920.png)

**Comment by alxndrsn** [comment]
:facepalm: oops - that explains that then!

Maybe an interesting note on UX though, as I've been using Metabase very happily for a couple of years now and haven't noticed this before.  I rarely click that button when working on SQL - normally I run by hitting ctrl+enter.  Is there an alternative keyboard shortcut for running the whole statement?

**Comment by flamber** [comment]
@alxndrsn It was changed in 0.34.0 together with a lot of other small things - #11361
But there's currently no command to run the entire query.
