### ISSUE TITLE
Drilling down to detail records from binned results, count doesn't match number of rows returned

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#15324]
**Describe the bug**
Summarise a count by a binned numerical value, then selecting to drill down to "View these X", the number of rows returned doesn't always match the binned count. I think this is due to the edge conditions of the binned range and the filter value being set. The filter values are set to between the bin limits, values that equal the bin limit values are included in both the upper and lower binning drill downs.

**Logs**
Nothing of interest in the logs

**To Reproduce**
1. New simple question on Sample Data
2. "Orders", count by "Quantity", 10 bins
3. Table visualisation
4. Bin "10-20", note the count, for me it was 85
5. Click the count and "View these Orders"
6. A table of 89 rows is returned

**Expected behavior**
The number of rows returned by "View these X" should match the bin count

**Screenshots**
Binned summary:
![image](https://user-images.githubusercontent.com/4504437/112389780-2c048980-8d5a-11eb-92ae-b52cd59b27db.png)
Drilled to 10-20
![image](https://user-images.githubusercontent.com/4504437/112390201-c8c72700-8d5a-11eb-8a1b-41a50a22c58d.png)
Drilled to 20-30
![image](https://user-images.githubusercontent.com/4504437/112390181-c2d14600-8d5a-11eb-9a4f-456ac42d4816.png)

You can see that the highlighted rows are in both drill downs.

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.1",
      "date": "2021-03-03",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Severity**
Inconsistency, leads to confusion and assuming that Metabase is getting it wrong, leads to loss of trust in it.

**Additional context**
Instead of using a between it should probably use the same logic as the binning which I assume is `>=` the lower limit, and `<` the upper. Now I write it out I'm not sure if `between` behaviour is consistent across databases, in SQL Server it's inclusive of both limits.

**Comment by camsaul** [comment]
We definitely treat `between` as inclusive (as it is in SQL), but as you've noticed for binning we use `>=` and `<` rather than between. So using between for the drill-thru behavior here is definitely the wrong behavior
