### ISSUE TITLE
The date format is wrong in the x-axis of the graph

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15328]
# My Settings
![image](https://user-images.githubusercontent.com/3394927/112405171-b9d97800-8d4c-11eb-8949-626659a2277e.png)

# My Question
![image](https://user-images.githubusercontent.com/3394927/112405299-f9a05f80-8d4c-11eb-8041-98e1cb6dda49.png)

**Comment by flamber** [comment]
Duplicate of #11394
