### ISSUE TITLE
Map pin data with blank long / lat cause data shift in consequent tooltip data displaying wrong info on mouseover

### ISSUE THREAD

**Issue by richxrich** [metabase/metabase#15329]
**Describe the bug**
The tooltip popup on a metabase pin map will show the wrong data on mouse over if there is a row with blank long and lat. The tooltip will show a different row of data.

**Logs**
n/a

**To Reproduce**
1. Using a pin map
2. Columns have been setup as long and lat in admin
3. Query with a list of data including columns with long and lat. Make sure one row has blank or null or long and lat
4. Note ALL tool tip data will not be correct for all pins AFTER the row with null for long and lat.
5. Validation of bug: Query an incorrect row directly or remove from the query a row with a null value for long and lat and all pin tool tip data will be correct.

**Expected behavior**
All tooltips to show the correct data for their pin.

Workaround:
Make sure there are no null or blank long and lat (using an isnull for example) and the data wont shift and be correct for ALL pins.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome v89
- Your operating system: Windows 10
- Your databases: MSSQL
- Metabase version: 0.38.2 (but been happening for at least 5 versions prior)
- Metabase hosting environment: Jar-file
- Metabase internal database: H2

**Severity**
Blocking use of pin maps with metabase - but there is workaround as described above.

**Additional context**

**Comment by notrom** [comment]
This one had me confused too, looks related to #12674

**Comment by richxrich** [comment]
> This one had me confused too, looks related to #12674

Sorry I did miss that when reporting the bug, they do look the same... I did come up with a minor workaround by isnull - hopefully sorted soon :)

**Comment by flamber** [comment]
Closing in favor of #12674
