### ISSUE TITLE
Column filters not working for metrics

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15333]
**Describe the bug**
When creating a question summarized by some metrics, then it's not possible to use the filter popover in the column.

**Workaround** Use the filters in the sidebar/modal after clicking the Filters in the upper-right corner, or use the Notebook.

**To Reproduce**
1. Simple question > Sample Dataset > Products
2. Summarize Count by Category, and change visualization to Table
3. Click the "Count" column > "Filter by this column" - it's not possible to use it, since the "Update filter" button is always disabled.
![image](https://user-images.githubusercontent.com/1447303/184364656-98580f14-51e4-4ddc-bf00-836b167f6729.png)

**Expected behavior**
Column filters should behave similar to sidebar/Notebook.

**Information about your Metabase Installation:**
Tested 0.36.8 thru 0.44.0

**Additional context**
Related to #15317

**Comment by ranquild** [comment]
Moved to "Later" because it requires non-existing drill changes

**Comment by snoe** [comment]
I believe this was fixed in the mlv2 drill down work.
