### ISSUE TITLE
Dashboard filters overflow the screen making it not possible to use them on IE11

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15337]
**Describe the bug**
Dashboard filters overflow the screen making it not possible to use them on IE11 - there's no horizontal scrollbar available.

Temporary workaround: Use the page zoom to zoom out (`CTRL`+`-`), set the filters and then reset the zoom level (`CTRL`+`0`)

Recommendation: Use the new Edge browser, which has something called IE Mode to support legacy web application:
https://docs.microsoft.com/en-us/deployedge/edge-ie-mode
That would mean that Metabase could be used with the Edge (modern rendering), while legacy intranet web applications that only works on IE could also be used in the same browser.

----

Seems like removing `align-start` from this line (which is the only place it's used) will make it work correctly in IE11 - not sure if there are any negative side-effects, but looks normal in Firefox:
https://github.com/metabase/metabase/blob/f4d90f688ae6b1d01f556b3f76edbec174ce5c2b/frontend/src/metabase/dashboard/components/Dashboard.jsx#L316

----

**To Reproduce**
1. Create a dashboard and add multiple filters until there are more than screen width
2. On IE11 it looks like this (it also squishes the sidebar, when there is a lot of filter widgets):
![image](https://user-images.githubusercontent.com/1447303/112506185-ca5e1280-8d8d-11eb-9939-d64e6ccc14a2.png)
And depending on the length of the filter name, this can mean that only a few filters are available for usage:
![image](https://user-images.githubusercontent.com/1447303/112507480-f6c65e80-8d8e-11eb-98fa-3c3cfd7eedc3.png)

**Expected behavior**
As close to modern browsers as possible - this is Firefox:
![image](https://user-images.githubusercontent.com/1447303/112506386-faa5b100-8d8d-11eb-8def-1e53944f5d0c.png)

**Information about your Metabase Installation:**
Tested 0.37.0 thru 0.38.2

**Additional context**
Using virtual machine IE11 image via https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by srikanth074** [comment]
Hi Flamber
Thanks for the Update, can we get some ETA around the fix on IE 11?

**Comment by flamber** [comment]
Closing, since Metabase dropped support for IE11 in version 0.40
https://www.metabase.com/blog/Metabase-0.40/index.html#upgrade-now
