### ISSUE TITLE
There is no way for admin to see sub-collections in user's personal collections

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15339]
**Describe the bug**
Admins are supposed to be able to see and manage anyone's personal collection. However, there is currently no way for them to **view** sub-collections in anyone's personal collection (expect their own). Please note that admins can still access such sub-collections directly, using the id.

**To Reproduce**
_As an admin_
1. Go to some user's personal collection
2. Click on `add_folder` icon (create new collection)
3. Give new collection a name
4. Click "Create" button
5. New collection is created inside that user's personal collection but there is no way to see it.

**Expected behavior**
When admin is inside someone's personal collection, that collection should be listed in the sidebar with all sub-collections.

**Severity**
Not sure how important this is for some admins. Seems pretty limiting.

**Additional context**
Quote from the documentation:
> Administrators can see and edit the contents of every user’s personal collection (even those belonging to other Administrators) by clicking on the “All personal collections” link from the “Our analytics” collection.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by kulyk** [comment]
Hi @nemanjaglumac,

There is actually a way right now. Admin users have "Other users' personal collections button" at the bottom of the collection sidebar. Do we also need to display them in the sidebar tree?

(my laptop is a bit lagging, please don't pay attention if the UI doesn't seem as responsive as you're used to)

![2021-04-15 13 24 16](https://user-images.githubusercontent.com/17258145/114855484-b20e7000-9dee-11eb-9cea-6ddae3a59d25.gif)

**Comment by nemanjaglumac** [comment]
> Do we also need to display them in the sidebar tree?

That is a question for @mazameli or @kdoh but I'd say this is already way better than before and probably good to go until we come up with a design.

**Comment by nemanjaglumac** [comment]
> There is actually a way right now. Admin users have "Other users' personal collections button" at the bottom of the collection sidebar. Do we also need to display them in the sidebar tree?

@kulyk  Unless I misunderstood something, this is an old and known behavior. The bug is not that admins can't see other users' personal collections. They can't see personal SUB-collections.

Take a look at repro steps and try it.

**Comment by kulyk** [comment]
@nemanjaglumac yes, you're right, I missed that. Thank you

Made a quick demo of displaying users' collections in the sidebar tree. I'm now thinking if we need the "Other users' personal collections" button 🤔 @mazameli @kdoh please take a look

<img width="1434" alt="Screenshot 2021-04-15 at 14 52 28" src="https://user-images.githubusercontent.com/17258145/114865261-a7f26e80-9dfa-11eb-958a-2afd142965a1.png">

**Comment by nemanjaglumac** [comment]
> Made a quick demo of displaying users' collections in the sidebar tree.

That is one option. The potential issue with this approach could be hundreds or thousands of users.

Alternative that I proposed earlier but would still want @mazameli to confirm is:
- If possible, instead of displaying the tree for ALL users' personal collections, can you somehow display a tree ONLY for the user's personal collection that you're currently in? In this case, that would be "Just User's Personal Collection". That way, we also don't have to remove the bottom button to all other's personal collections and we declutter, imo.

Anyway, those were just my 2c, but let's wait for the pros :)

**Comment by mazameli** [comment]
> can you somehow display a tree ONLY for the user's personal collection that you're currently in? In this case, that would be "Just User's Personal Collection".

This is the most immediately obvious solution I can see, too, provided it's technically possible and easy enough. I'd want the tree to be displayed in the bottom-left, indented under `Other users' personal collections`.

My appetite for this personally is **relatively low** — yes, this is something that admins should be able to do, but my intuition is this isn't a high frequency flow. (I personally have not heard any user complaints about this so far.)

> They can't see personal SUB-collections.

Just to clarify this point, can an admin currently view a subcollection in another user's personal collection if they're given the full URL to it?

**Comment by kulyk** [comment]
@mazameli thank you, I'll share an update here as soon as I have a working solution

> Just to clarify this point, can an admin currently view a subcollection in another user's personal collection if they're given the full URL to it?

Yes (tested locally on `release-x.39.x`)
