### ISSUE TITLE
Displayed results differ from exported results.

### ISSUE THREAD

**Issue by speed144** [metabase/metabase#15341]
**Describe the bug**
The displayed query result set is different than the exported in csv results. This occurs in the write query results, as well as a custom view created table. 

**To Reproduce**
1. Go to write query or view custom view table in browse
2. Execute stored procedure in query or dispay table
3. Scroll down to see results, then download an export 
4. See error where results are different

**Expected behavior**
The results that are displayed in the questions answer should be the same as the results that get exported.

**Screenshots**
See originally displayed results
![image](https://user-images.githubusercontent.com/19546111/112532454-742da700-8d6e-11eb-88ab-d1eddc3bd70d.png)

Export at bottom
![image](https://user-images.githubusercontent.com/19546111/112532555-9293a280-8d6e-11eb-8095-aaa59e5c105d.png)

Exported results are different 
![image](https://user-images.githubusercontent.com/19546111/112532630-aa6b2680-8d6e-11eb-8521-42f007cd84e3.png)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_281-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_281",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.281-b09",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.1",
      "date": "2021-03-03",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```
**Severity**

Critical

Currently the displayed results show inaccurate information compared to the exported result set - as we use our data in public links without the visuals being accurate our teams are unable to view their data without manual intervention.

**Additional context** 

This issue is seen using both the visual result display of a custom view table as well as the results displayed using a stored procedure - both of which are referencing custom views but entirely separate ones.

**Comment by flamber** [comment]
Since this is on SQL Server, and I cannot see the query, but exports are displaying correctly, then I'm fairly sure you're seeing issue #9940, where the display query is limited to 2000 rows, but also for sub-queries, which is where the problem is.
