### ISSUE TITLE
Filter Parameters Allowing for Filtering Text as Field Filter?

### ISSUE THREAD

**Issue by GiacchinoCinque** [metabase/metabase#15347]
**Describe the bug**
I normally use field filters though for some reason I seem to be able to use a field filter on "Aa" text parameter which according to the documentation doesn't seem to be supported... For some reason a particular column of data I am working with seems to not raise any error when I go to use a field filter on it, which mis-leads me to believe, that I can or that it should be working... Or maybe I am misinterpreting the "Aa" and that is just a generic designation for any character string text data structure?

**To Reproduce**
Not even sure what the steps are... It seems to only work on one column that I am working on in a specific table... It categorizes the parameter as "Aa" text... And usually field filters don't work on that kind of text... But for some reason it allows a Field Filter to be created and doesn't give me a widget error. Though, when I go to actually use the filter... It just refreshes the page or doesn't seem to do much other than get rid of a couple of random rows?

I am doing a basic select, join and aggregate query...

**Expected behavior**
I expected the field filter to function just like all other category field filters... But it seems to just not filter anything? Or if it does I'm not sure what it is filtering.

**Screenshots**
<img width="344" alt="Screen Shot 2021-03-25 at 3 02 24 PM" src="https://user-images.githubusercontent.com/70193195/112550146-2ae45400-8d7c-11eb-84a3-ce3bfc28bb2b.png">

Code:
<img width="485" alt="Screen Shot 2021-03-25 at 3 02 49 PM" src="https://user-images.githubusercontent.com/70193195/112550207-40f21480-8d7c-11eb-953b-dd27b6880ac6.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
Browser = Chrome
hardware = Macbook Air 2019
databases = Postgres
Metabase vesion 0.38.2

**Severity**
Not that severe of an issue. I just get around it by using the regular text filter and type in the thing I am trying to filter... But the problem is it doesn't give me an error message saying the field filter won't work for this column "Aa" parameter which seems like a bug.

**Comment by flamber** [comment]
Hi @GiacchinoCinque 
I'm not sure I understand what your problem is, but you are not using Field Filters correctly - you should not include the table/column together with the variable.
Have a look at this article: https://www.metabase.com/learn/building-analytics/sql-templates/field-filters.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
