### ISSUE TITLE
The date format is wrong in the x-axis of the graph   #15328

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15349]
### This is my new SQL statement, the date format displayed by this statement is correct
![image](https://user-images.githubusercontent.com/3394927/112570850-c8459380-8e21-11eb-9bc2-31abcb54a9c8.png)

### #15328 Date formatted as `%Y-%m`，Why is the date formatted according to `%Y-%m` displayed incorrectly in the graph

**Comment by flamber** [comment]
Hi @8debug 

Please fill in all the details that is requested, when opening an issue.

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

Metabase tries to automatically render strings it detects as time/date to allow you to do formatting in the settings. When it cannot detect the type, then it just displays the exact value.
You can prevent some of detection and just show value by changing visualization Settings > Axes > X-axis scale = Ordinal
