### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by kevindump** [metabase/metabase#15350]
**Describe the bug**
i try to add Oracle to Metabase by https://www.metabase.com/docs/latest/administration-guide/databases/oracle.html
but it did not work

**Logs**

[563cef1b-2e2d-4c8a-84e6-7906e4040c07] 2021-03-26T11:07:05+08:00 INFO metabase.plugins.dependencies Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

[563cef1b-2e2d-4c8a-84e6-7906e4040c07] 2021-03-26T11:07:05+08:00 INFO metabase.plugins.dependencies Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
[563cef1b-2e2d-4c8a-84e6-7906e4040c07] 2021-03-26T11:07:05+08:00 INFO metabase.plugins.dependencies Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"]

**To Reproduce**
https://www.metabase.com/docs/latest/administration-guide/databases/oracle.html
i put the ojdbc8.jar to the dir and run again docker

**Expected behavior**
i can add oracle db

**Screenshots**

**Severity**
i hope it can work

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-TW",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.4.0-70-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-17",
      "tag": "v0.38.2",
      "branch": "release-x.38.x",
      "hash": "91f0ed6"
    },
    "settings": {
      "report-timezone": "Asia/Taipei"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @kevindump 
Where did you add the ojdbc8.jar? Did you add the file to the container (then it should be added in `/plugins/`) or are you using [MB_PLUGINS_DIR](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_plugins_dir) with an external volume.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by kevindump** [comment]
> Hi @kevindump
> Where did you add the ojdbc8.jar? Did you add the file to the container (then it should be added in `/plugins/`) or are you using [MB_PLUGINS_DIR](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_plugins_dir) with an external volume.
> Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

i put it in the right path, so ,the logs show it try to load the file
but, i find other way to fix it :chmod 777
