### ISSUE TITLE
Pivot Table: Cannot change name of fields used for "values"

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15353]
**Describe the bug**
It's not possible to change the name of "values" fields on a Pivot Table.

**Workaround** is to use Custom Expression instead of the built-in metrics, which allows giving the expression a custom name.

**To Reproduce**
1. Custom question > Sample Dataset > Orders summarize Count by CreatedAt:Year
![image](https://user-images.githubusercontent.com/1447303/112639341-719b8200-8e40-11eb-8875-4fe7cf2c0ad1.png)
2. Change visualization to Pivot Table > under "Fields to use for the table **values**" expand Count > click Formatting "See options..."
![image](https://user-images.githubusercontent.com/1447303/112639611-bde6c200-8e40-11eb-9448-1d4d402fef34.png)
3. Change "Column title" to `Awesome Count` and blur the field - it does not update the name in the table
![image](https://user-images.githubusercontent.com/1447303/112639789-f1c1e780-8e40-11eb-9cbc-5135b42f6858.png)

**Expected behavior**
Should be possible to change the field name of "values", just like it's possible to do for fields on "rows"

**Information about your Metabase Installation:**
Tested 0.38.0 thru 0.38.2

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camerondavison** [comment]
still broken in `v0.40`
