### ISSUE TITLE
metabase cannot be started

### ISSUE THREAD

**Issue by gubinjie** [metabase/metabase#15351]
![企业微信截图_16167445008441](https://user-images.githubusercontent.com/37869445/112598589-c42d6c00-8e49-11eb-91e4-ac71dd947c10.png)
Through java -jar metabase.jar, it keeps stopping there and does not start. Why is this?

**Comment by flamber** [comment]
Hi @gubinjie 
You are most likely running out of entropy - if you wait 20-30 minutes, then it would likely start - see #10175 for workaround.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
