### ISSUE TITLE
Dashboard Textbox images are 100% width

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15356]
**Describe the bug**
Dashboard Textbox with markdown images are 100% width

**To Reproduce**
1. Go to dashboard and add a textbox, make it full width and input the following in the textbox:
`![](https://avatars.githubusercontent.com/u/1447303?s=120&v=4)`
2. Enjoy the 120x120 image in all it's glory:
![image](https://user-images.githubusercontent.com/1447303/112678810-b25cc080-8e6b-11eb-9098-5cf03d51ee55.png)

**Expected behavior**
Instead of `width: 100%;` it should just be `max-width: 100%;`

**Information about your Metabase Installation:**
Tested 0.36.8 thru 0.38.2

**Additional context**
Seems like it might have been a regression, since #10857 talks about having problems with making the images scale.

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/15646 
Org PR https://github.com/metabase/metabase/pull/15653
