### ISSUE TITLE
Cannot choose granularity of dates on Summarize with Simple question based on SQL question

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15364]
**Describe the bug**
After saving the complex sql statement and referencing it in the "simple question", the grouping by month cannot be selected when grouping by date for the first time

**Logs**

**To Reproduce**
1. Go to 'Write SQL', and write SQL
2. Click on 'save'
3. Go to 'Ask a question', and click on 'Simple question'
4. selected 'Saved Quesions', and use the sql just saved
5. Click on 'Summarize', and Select a field whose data type is date and group by it (You cannot group by month or year at this time), then Show statistics graph
6. Click on 'Summarize', Make the Summarize panel collapsed
7. Click on 'Summarize' again, At this time, you can group by year and month

**Expected behavior**
Click on 'Summarize', and Select a field whose data type is date and group by it (Can always be grouped by year and month)

**Screenshots**
![image](https://user-images.githubusercontent.com/3394927/112819603-55ede100-90b7-11eb-9f7a-e90cb283018a.png)
![image](https://user-images.githubusercontent.com/3394927/112819642-61d9a300-90b7-11eb-9063-865ff8406fab.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Chrome 88.0.4324.104
- Windows 10 Pro
- MySQL 5.7.26
- Metabase version: v0.38.2
- Metabase hosting environment: Windows Server 2016 Datacenter
- Metabase internal database: H2

**Additional context**

https://user-images.githubusercontent.com/3394927/112819525-440c3e00-90b7-11eb-94fc-f43b9e881484.mp4

**Comment by flamber** [comment]
Hi @8debug 
Please provide all the requested details, when opening an issue.
Without knowing version, which question type, which database type, which column type, which field type, then it's impossible to reproduce.

**Comment by flamber** [comment]
Very related to #11439 (fixed in 0.38.0). Workaround is to select the granularity/binning in the Notebook editor.

**Comment by 8debug** [comment]
> Very related to #11439 (fixed in 0.38.0).
> 
> **Reproduce**
> 
> 1. Native query > Sample Dataset > `select * from products` save as "Q1"
> 2. Simple question > Saved Questions > "Q1"
> 3. Click Summarize and try to change granularity of CreatedAt - it's possible, but very well hidden:
>    ![image](https://user-images.githubusercontent.com/1447303/112824830-4e184780-908b-11eb-93eb-de1143d2f462.png)
> 4. Doing it through the Notebook is much easier, but it does not show the default granularity value:
>    ![image](https://user-images.githubusercontent.com/1447303/112825021-8cae0200-908b-11eb-81b6-213f149cc136.png)

yes，you are right. It's very hidden :sweat_smile:

**Comment by nemanjaglumac** [comment]
This has been reproduced with the work in https://github.com/metabase/metabase/issues/16387, and fixed by @ariya but I am not sure exactly in which PR.

@flamber should we close this?
