### ISSUE TITLE
Add search widget to the People Admin List

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#15363]
**Is your feature request related to a problem? Please describe.**
Once you have a few dozen users `/admin/people` becomes hard to navigate, and it's hard to track down specific people (or worse yet, groups of people from a given domain)

**Describe the solution you'd like**
Add a search widget that filters by name, and email. 

**Describe alternatives you've considered**
Scrolling a lot. It sucks.

**How important is this feature to you?**
Fairly important and pretty critical once you get to 100s of users.

related to #14789

**Comment by flamber** [comment]
Very related to #8126
