### ISSUE TITLE
Many pseudo "links" are not real links / accessibility issue, eg right click context menu is broken

### ISSUE THREAD

**Issue by brendanheywood** [metabase/metabase#15395]
**Describe the bug**
Some links, such as the title of each question on a dashboard, are not plain html links which means you cannot right click / middle click / shift click and open the question in a new tab or copy the url to put into somewhere else. You have to open the question, then cut and paste the url, or clone it to a new tab, and then go 'back' in the original tab. I cannot see any compelling reason why the pseudo links were implemented in JavaScript rather than just being a plain link.

**Logs**
n/a this is a pure front end issue.

**To Reproduce**
1. Go to any dashboard
2. Right click on the title of any question
3. You incorrectly see the same context menu as when you right click anywhere on the page eg 'Back', 'Reload', 'Save as'

**Expected behavior**
3. You should see a normal url context menu eg 'Open in new window, Open in new tab, Copy link address'

**Screenshots**
Incorrect context menu:
![image](https://user-images.githubusercontent.com/187449/112984165-49968080-91aa-11eb-88a9-1a97d0b0beb9.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.4.0-194-generic",
    "user.language": "en",
    "user.timezone": "Australia/Melbourne"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.5.25"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-07-31",
      "tag": "v0.36.2",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
It's a daily annoyance. It's a little more annoying as many links do work correctly, and they are visually styled exactly the same, and so it can be hard to predict which are broken and which are not. Very often when I'm working fast I'll quickly right click on a link and choose the first option which should open a new tab, but instead I get taken 'back' instead.

**Additional context**
This is also an accessibility issue. The links are not keyboard focusable, there is no aria markup so these pseudo links cannot be used by screen reader users - this will be a concern for many large business and gov agencies.

**Comment by flamber** [comment]
Closing in favor of #5168 - and #1462
