### ISSUE TITLE
queries that run longer than 30s get infinite "doing science" on heroku

### ISSUE THREAD

**Issue by m1l0sz** [metabase/metabase#15412]
it seems a recent build effectively broke longer-running queries on heroku.

any query that takes longer than 30s to return data now gets an infinite "doing science" screen.

it seems to display query results the app now issues an ajax request to itself (to /api/card/{int}/query). heroku's platform will time out if data is not returned within 30s. older versions appear to have reissued requests until the internal metabase query timeout was hit. this is no longer the case.

the client we have replicated this with is on heroku-20 + redshift.

**Comment by paoliniluis** [comment]
@m1l0sz can you please specify the version you're running so we can identify which commit was the culprit of this happening? also: which version did it work without issues? thanks

**Comment by m1l0sz** [comment]
my apologies -- this is working on another client's install, 0.35.4. i have replicated the issue on 0.37.4 and 0.38.2. it could have been broken prior to 0.37.4.

the working install is calling /api/dataset instead of /api/card/{int}/query

**Comment by paoliniluis** [comment]
@m1l0sz this is a known limitation of Heroku (https://devcenter.heroku.com/articles/request-timeout) which I don't think we can do something about, either you tune the Redshift queries so queries return faster or you move from Heroku to a server

**Comment by m1l0sz** [comment]
lol. ok
