### ISSUE TITLE
12AM timestamps rendered as 24:xx in 24-hour format

### ISSUE THREAD

**Issue by walterl** [metabase/metabase#15413]
**Describe the bug**

Metabase renders the timestamp value `"2018-07-04T00:34:31.322+02:00"` from the back-end, as _July 4, 2018, 24:34_ when the column is configured to display timestamps in 24-hour format:

![image](https://user-images.githubusercontent.com/23798/113077692-e91b3980-91d1-11eb-8101-1ce500d3e77a.png)

The time should be rendered as _00:34_, and not _24:34_.

[This query](http://localhost:3000/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgQ1JFQVRFRF9BVCBGUk9NIE9SREVSUyBXSEVSRSBJRD0zNiIsInRlbXBsYXRlLXRhZ3MiOnt9fSwiZGF0YWJhc2UiOjF9LCJkaXNwbGF5Ijoic2NhbGFyIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJjb2x1bW5fc2V0dGluZ3MiOnsiW1wibmFtZVwiLFwiQ1JFQVRFRF9BVFwiXSI6eyJ0aW1lX3N0eWxlIjoiazptbSJ9fX19) on the sample dataset illustrates the issue.

I noticed that this also happens in locales that use 24-hour format for time values.

Discovered on 0.38.2, but also affects current `master`, using Firefox 88.0b4 and 87.0.

**Comment by paoliniluis** [comment]
yup, same as https://github.com/metabase/metabase/issues/9538
