### ISSUE TITLE
Manual reordering of steps for funnel visualization

### ISSUE THREAD

**Issue by ukritw** [metabase/metabase#15416]
**Is your feature request related to a problem? Please describe.** 
The funnel diagram sort the steps alphabetically by default, which renders the ordering useless most of the time. The current workaround is to rename the steps alphabetically (e.g. a_step1, b_step2, c_step3) such that it can be sorted correctly or to add an additional column for specifying the order of steps in SQL (e.g. 1, 2, 3).

<img width="327" alt="Screen Shot 2021-03-31 at 3 05 12 PM" src="https://user-images.githubusercontent.com/2685753/113111750-b48b9a00-9232-11eb-9f66-a1069789ff65.png">

**Describe the solution you'd like** 
In the sidebar of the visualization menu, the users should be able to click on the gear icon that opens up a "steps ordering" setting. The setting should display the list of all possible steps with the ability move each step up and down the list by drag-and-drop.

**Describe alternatives you've considered** 
The alternative is let the user add one step at a time. Similar to what adding a series is like in the line chart visualization. Without the drag-and-drop functionality, this should be easier to implement.

**How important is this feature to you?**
It almost falls into the category of _must-have feature_ since every user needs to use the workaround to make the ordering of the funnel diagram display correctly.

**Related issues** 
[#13669](https://github.com/metabase/metabase/issues/13669) 
[#5401](https://github.com/metabase/metabase/issues/5401) 
could be useful for bar charts as well [#2339](https://github.com/metabase/metabase/issues/2339)

**Comment by flamber** [comment]
Isn't this a duplicate of the issues you list? Or how is this different?

**Comment by ukritw** [comment]
@flamber It's the same issue but with a proposed solution and more specific to the funnel visualization. 

I don't see any labeling on the other ones, so I thought of posting this one to give more context and surface the problem.

Or should I post it under [#13669](https://github.com/metabase/metabase/issues/13669)?

**Comment by flamber** [comment]
I would just add it to #5401, which is specific about funnels, but from my reading, that is what the issue is asking for already.
Otherwise #13669 perhaps.

**Comment by ukritw** [comment]
Added to [#5401](https://github.com/metabase/metabase/issues/5401).
