### ISSUE TITLE
Login History not recording correct IP address

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15437]
Login History on our internal instance reports "Unknown location" for all of my logins. My IP address is reported as `172.17.0.1` which I'm guessing is one of the reverse proxies we have in front of the instance -- it's definitely not my actual IP address. This is why it cannot determine the location. We need to figure out how to get the actual IP address -- maybe there's a header  similar to `X-Forwarded-For` we can look at to determine this

![image](https://user-images.githubusercontent.com/1455846/113335370-b2c8e180-92d9-11eb-95dd-b5d614fb29ac.png)

**Comment by paoliniluis** [comment]
172.17.0.1 IP "should" be sort of an ingress gw / any gateway that should be in front of a Kubernetes Pod / ECS cluster. So the "X-Forwarded-For" should be sent but whatever is in front of the container is rewriting it. @walterl @robdaemon @kidd if you could provide any info here would be great!

**Comment by walterl** [comment]
Correct, 172.17.0.0/16 is the default Docker network IP range, and 172.17.0.1 the default Docker network interface's gateway. `X-Forwarded-For` should be _configured_ by whatever is in front of the instance, but I can't recall ever having it configured by default. It's one of the few things that usually go into an nginx reverse proxy config in a Docker container. Depending on the setup, there could even be multiple "hops" at which this will need to be forwarded, like at an AWS ALB, and then again at an ECS container running MB.

MB should prefer the `X-Forwarded-For` address over the client IP, but I didn't check to see what it's currently doing.

**Comment by robdaemon** [comment]
Remember that `X-Forwarded-For` can be a chain of addresses.

`X-Forwarded-For: 1.1.1.1.1,2.2.2.2.2,3.3.3.3`

**Comment by camsaul** [comment]
Fixed by #15553
