### ISSUE TITLE
/api/search returns no data 

### ISSUE THREAD

**Issue by ChristineChetty11** [metabase/metabase#15433]
**Describe the bug**
When running metabase v0.39 from source, the /api/search returns no data. The impact can be seen when archiving questions etc, the archive list is always empty..

**To Reproduce**
1. Go to any question you would like to archive, archive this question
2. Click on View Archive
3. List is empty

**Expected behavior**
Archived items are accessed via View Archive option. /api/search?archived=true returns list of archived items

**Severity**
Cannot unarchive items, big problem

**Comment by flamber** [comment]
Duplicate of #15080
