### ISSUE TITLE
Cached query responses incorrectly update query.average_execution_time

### ISSUE THREAD

**Issue by StdCarrot** [metabase/metabase#15432]
It cause by wrong calculation of "query.average_execution_time".
I found that average_execution_time is including cache call time.

For example when I run long query, at the first time, it goes to cache.
And next run, the result comes from the cache and recalculate average_execution_time.
As time series like this(cache threshold is 10 seconds):
1. First run
   - run time: 1min
   - average_execution_time: 1min (this will be cached)
2. Second run
   - run time: 1s (cause it came from cache)
   - average_execution_time: 30.5s
3. Third run
   - run time: 1s (cause it came from cache)
   - average_execution_time: 15.75s
4. Fourth run
   - run time: 1s (cause it came from cache)
   - average_execution_time: 8.375s
5. Fifth run
   - run time: 1min (cause average_execution_time is less than threshold)
   - average_execution_time: 34s (this will be cached again)

This problem makes cache policy useless.
If two or more person sees same dashboard, query executions are goes to nightmare.
"average_execution_time" needs to calculate only actual runs.

**Comment by flamber** [comment]
Related to #7282

**Comment by StdCarrot** [comment]
This is query history on my bowser.

average_execution_time is decreased rapidly when it returned cache.


![image](https://user-images.githubusercontent.com/1968929/113261463-76fa4000-930a-11eb-9698-e6574e5c1e49.png)
![image](https://user-images.githubusercontent.com/1968929/113261497-7f527b00-930a-11eb-9abb-f2d0499afc04.png)
![image](https://user-images.githubusercontent.com/1968929/113261523-85e0f280-930a-11eb-93bd-22f8f4236ac4.png)
![image](https://user-images.githubusercontent.com/1968929/113261548-8ed1c400-930a-11eb-8a7c-17cbe280e2dd.png)

**Comment by flamber** [comment]
@StdCarrot Please fill in all the details requested, when opening an issue, like include "Diagnostic Info" from Admin > Troubleshooting, and providing logs instead of screenshots, since it's much easier to view in this case.

**Comment by camsaul** [comment]
Should be easy enough to not update the average execution time when returning cached results
