### ISSUE TITLE
Getting crashed XLSX file on export 

### ISSUE THREAD

**Issue by caelestis** [metabase/metabase#15434]
When downloading an XLSX file, we get it broken, and if you open it through notepad, you can see the following error:

```json
{"via":[{"type":"java.lang.ClassCastException","message":"class sun.font.CompositeFont cannot be cast to class sun.font.PhysicalFont (sun.font.CompositeFont and sun.font.PhysicalFont are in module java.desktop of loader 'bootstrap')","at":["sun.font.SunFontManager","getDefaultPhysicalFont","SunFontManager.java",1081]}],"trace":[["sun.font.SunFontManager","getDefaultPhysicalFont","SunFontManager.java",1081],["sun.font.SunFontManager","initialiseDeferredFont","SunFontManager.java",966],["sun.font.CompositeFont","doDeferredInitialisation","CompositeFont.java",287],["sun.font.CompositeFont","getSlotFont","CompositeFont.java",376],["sun.font.CompositeGlyphMapper","initMapper","CompositeGlyphMapper.java",81],["sun.font.CompositeGlyphMapper","<init>","CompositeGlyphMapper.java",62],["sun.font.CompositeFont","getMapper","CompositeFont.java",433],["sun.font.CompositeFont","canDisplay","CompositeFont.java",459],["java.awt.Font","canDisplayUpTo","Font.java",2247],["java.awt.font.TextLayout","singleFont","TextLayout.java",469],["java.awt.font.TextLayout","<init>","TextLayout.java",530],["org.apache.poi.ss.util.SheetUtil","getDefaultCharWidth","SheetUtil.java",275],["org.apache.poi.xssf.streaming.AutoSizeColumnTracker","<init>","AutoSizeColumnTracker.java",117],["org.apache.poi.xssf.streaming.SXSSFSheet","<init>","SXSSFSheet.java",82],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createAndRegisterSXSSFSheet","SXSSFWorkbook.java",658],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createSheet","SXSSFWorkbook.java",679],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createSheet","SXSSFWorkbook.java",90],["dk.ative.docjure.spreadsheet$add_sheet_BANG_","invokeStatic","spreadsheet.clj",283],["dk.ative.docjure.spreadsheet$add_sheet_BANG_","invoke","spreadsheet.clj",279],["metabase.query_processor.streaming.xlsx$fn__54276","invokeStatic","xlsx.clj",108],["metabase.query_processor.streaming.xlsx$fn__54276","invoke","xlsx.clj",104],["clojure.lang.MultiFn","invoke","MultiFn.java",234],["metabase.query_processor.streaming$streaming_context","invokeStatic","streaming.clj",52],["metabase.query_processor.streaming$streaming_context","invoke","streaming.clj",45],["metabase.query_processor.streaming$streaming_context","invokeStatic","streaming.clj",57],["metabase.query_processor.streaming$streaming_context","invoke","streaming.clj",45],["metabase.query_processor.streaming$streaming_response_STAR_$fn__54340$fn__54341","invoke","streaming.clj",72],["metabase.query_processor.streaming$streaming_response_STAR_$fn__54340","invoke","streaming.clj",71],["metabase.async.streaming_response$do_f_STAR_","invokeStatic","streaming_response.clj",65],["metabase.async.streaming_response$do_f_STAR_","invoke","streaming_response.clj",63],["metabase.async.streaming_response$do_f_async$fn__16055","invoke","streaming_response.clj",84],["clojure.lang.AFn","applyToHelper","AFn.java",152],["clojure.lang.AFn","applyTo","AFn.java",144],["clojure.core$apply","invokeStatic","core.clj",665],["clojure.core$with_bindings_STAR_","invokeStatic","core.clj",1973],["clojure.core$with_bindings_STAR_","doInvoke","core.clj",1973],["clojure.lang.RestFn","invoke","RestFn.java",425],["clojure.lang.AFn","applyToHelper","AFn.java",156],["clojure.lang.RestFn","applyTo","RestFn.java",132],["clojure.core$apply","invokeStatic","core.clj",669],["clojure.core$bound_fn_STAR_$fn__5749","doInvoke","core.clj",2003],["clojure.lang.RestFn","invoke","RestFn.java",397],["clojure.lang.AFn","run","AFn.java",22],["java.util.concurrent.Executors$RunnableAdapter","call","Executors.java",515],["java.util.concurrent.FutureTask","run","FutureTask.java",264],["java.util.concurrent.ThreadPoolExecutor","runWorker","ThreadPoolExecutor.java",1128],["java.util.concurrent.ThreadPoolExecutor$Worker","run","ThreadPoolExecutor.java",628],["java.lang.Thread","run","Thread.java",830]],"cause":"class sun.font.CompositeFont cannot be cast to class sun.font.PhysicalFont (sun.font.CompositeFont and sun.font.PhysicalFont are in module java.desktop of loader 'bootstrap')","_status":500}
```

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Linux",
    "os.version": "5.4.0-1038-aws",
    "user.language": "en",
    "user.timezone": "Europe/Kiev"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.23"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
You need to use Java 11 and not Java 13. I'll be closing this as we have other issues about supporting newer Java versions

**Comment by caelestis** [comment]
@paoliniluis I change java to 11 and have the same issue.

```json
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "11.0.10+8-LTS-162",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.10",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "11.0.10+8-LTS-162",
    "os.name": "Linux",
    "os.version": "5.4.0-1038-aws",
    "user.language": "en",
    "user.timezone": "Europe/Kiev"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.23"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
Try with AdoptOpenJDK https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Comment by caelestis** [comment]
@paoliniluis I change again Java version and same problem:
``json
{"via":[{"type":"java.lang.InternalError","message":"java.lang.reflect.InvocationTargetException","at":["sun.font.FontManagerFactory$1","run","FontManagerFactory.java",86]},{"type":"java.lang.reflect.InvocationTargetException","at":["jdk.internal.reflect.NativeConstructorAccessorImpl","newInstance0","NativeConstructorAccessorImpl.java",-2]},{"type":"java.lang.NullPointerException","at":["sun.awt.FontConfiguration","getVersion","FontConfiguration.java",1262]}],"trace":[["sun.awt.FontConfiguration","getVersion","FontConfiguration.java",1262],["sun.awt.FontConfiguration","readFontConfigFile","FontConfiguration.java",225],["sun.awt.FontConfiguration","init","FontConfiguration.java",107],["sun.awt.X11FontManager","createFontConfiguration","X11FontManager.java",719],["sun.font.SunFontManager$2","run","SunFontManager.java",379],["java.security.AccessController","doPrivileged","AccessController.java",-2],["sun.font.SunFontManager","<init>","SunFontManager.java",324],["sun.awt.FcFontManager","<init>","FcFontManager.java",35],["sun.awt.X11FontManager","<init>","X11FontManager.java",56],["jdk.internal.reflect.NativeConstructorAccessorImpl","newInstance0","NativeConstructorAccessorImpl.java",-2],["jdk.internal.reflect.NativeConstructorAccessorImpl","newInstance","NativeConstructorAccessorImpl.java",62],["jdk.internal.reflect.DelegatingConstructorAccessorImpl","newInstance","DelegatingConstructorAccessorImpl.java",45],["java.lang.reflect.Constructor","newInstance","Constructor.java",490],["sun.font.FontManagerFactory$1","run","FontManagerFactory.java",84],["java.security.AccessController","doPrivileged","AccessController.java",-2],["sun.font.FontManagerFactory","getInstance","FontManagerFactory.java",74],["java.awt.Font","getFont2D","Font.java",497],["java.awt.Font","canDisplayUpTo","Font.java",2250],["java.awt.font.TextLayout","singleFont","TextLayout.java",469],["java.awt.font.TextLayout","<init>","TextLayout.java",530],["org.apache.poi.ss.util.SheetUtil","getDefaultCharWidth","SheetUtil.java",275],["org.apache.poi.xssf.streaming.AutoSizeColumnTracker","<init>","AutoSizeColumnTracker.java",117],["org.apache.poi.xssf.streaming.SXSSFSheet","<init>","SXSSFSheet.java",82],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createAndRegisterSXSSFSheet","SXSSFWorkbook.java",658],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createSheet","SXSSFWorkbook.java",679],["org.apache.poi.xssf.streaming.SXSSFWorkbook","createSheet","SXSSFWorkbook.java",90],["dk.ative.docjure.spreadsheet$add_sheet_BANG_","invokeStatic","spreadsheet.clj",283],["dk.ative.docjure.spreadsheet$add_sheet_BANG_","invoke","spreadsheet.clj",279],["metabase.query_processor.streaming.xlsx$fn__54276","invokeStatic","xlsx.clj",108],["metabase.query_processor.streaming.xlsx$fn__54276","invoke","xlsx.clj",104],["clojure.lang.MultiFn","invoke","MultiFn.java",234],["metabase.query_processor.streaming$streaming_context","invokeStatic","streaming.clj",52],["metabase.query_processor.streaming$streaming_context","invoke","streaming.clj",45],["metabase.query_processor.streaming$streaming_context","invokeStatic","streaming.clj",57],["metabase.query_processor.streaming$streaming_context","invoke","streaming.clj",45],["metabase.query_processor.streaming$streaming_response_STAR_$fn__54340$fn__54341","invoke","streaming.clj",72],["metabase.query_processor.streaming$streaming_response_STAR_$fn__54340","invoke","streaming.clj",71],["metabase.async.streaming_response$do_f_STAR_","invokeStatic","streaming_response.clj",65],["metabase.async.streaming_response$do_f_STAR_","invoke","streaming_response.clj",63],["metabase.async.streaming_response$do_f_async$fn__16055","invoke","streaming_response.clj",84],["clojure.lang.AFn","applyToHelper","AFn.java",152],["clojure.lang.AFn","applyTo","AFn.java",144],["clojure.core$apply","invokeStatic","core.clj",665],["clojure.core$with_bindings_STAR_","invokeStatic","core.clj",1973],["clojure.core$with_bindings_STAR_","doInvoke","core.clj",1973],["clojure.lang.RestFn","invoke","RestFn.java",425],["clojure.lang.AFn","applyToHelper","AFn.java",156],["clojure.lang.RestFn","applyTo","RestFn.java",132],["clojure.core$apply","invokeStatic","core.clj",669],["clojure.core$bound_fn_STAR_$fn__5749","doInvoke","core.clj",2003],["clojure.lang.RestFn","invoke","RestFn.java",397],["clojure.lang.AFn","run","AFn.java",22],["java.util.concurrent.Executors$RunnableAdapter","call","Executors.java",515],["java.util.concurrent.FutureTask","run","FutureTask.java",264],["java.util.concurrent.ThreadPoolExecutor","runWorker","ThreadPoolExecutor.java",1128],["java.util.concurrent.ThreadPoolExecutor$Worker","run","ThreadPoolExecutor.java",628],["java.lang.Thread","run","Thread.java",834]],"_status":500}
```

Diagnostic info:
```json
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.4.0-1038-aws",
    "user.language": "en",
    "user.timezone": "Europe/Kiev"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.23"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
@caelestis Use the official Docker image - you're having problems with fonts:
https://stackoverflow.com/questions/55791235/pentaho-poi-throws-invocationtargetexception
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
