### ISSUE TITLE
Schemas with slash `/` causes problems in "Browse Data" and Permissions

### ISSUE THREAD

**Issue by harrybiddle** [metabase/metabase#15454]
**Describe the bug**
I get "We're a little lost... The page you asked for couldn't be found" if I visit `/browse/2/schema/<schema_name>` and the schema has a forward-slash in the name.

**Information about your Metabase Installation:**

- Your databases: PostgreSQL database; more specifically the DDN of www.splitgraph.com
- Metabase version: v0.38.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
This is definitely blocking my usability of Metabase with Splitgraph, which otherwise seems like a match made in heaven.

**Additional context**
This comes up because I am trying to add the Splitgraph DDN, whose schemas _always_ have forward-slashes. Would it be possible for us to simply escape the forward-slash in the URL?

Possibly related: #13476

**Comment by flamber** [comment]
This seems like a frontend issue, and only for Browse Data - we seem to handle it correctly everywhere else.

Workaround: Let's say you have a schema called `slash/er`, then the Browse Data URL would be:
`/browse/2/schema/slash/er`
But if you change the schema to `slash%2Fer` (replacing `/` with `%2F`) then it works:
`/browse/2/schema/slash%2Fer`

**Comment by harrybiddle** [comment]
Confirmed the `%2F` trick works :)

**Comment by adamf** [comment]
I think this is the diff we want, checking it now:

```
diff --git a/frontend/src/metabase/browse/containers/SchemaBrowser.jsx b/frontend/src/metabase/browse/containers/SchemaBrowser.jsx
index 428d55dfe..16527dec3 100644
--- a/frontend/src/metabase/browse/containers/SchemaBrowser.jsx
+++ b/frontend/src/metabase/browse/containers/SchemaBrowser.jsx
@@ -49,7 +49,7 @@ function SchemaBrowser(props) {
               {schemas.map(schema => (
                 <GridItem width={ITEM_WIDTHS} key={schema.id}>
                   <Link
-                    to={`/browse/${dbId}/schema/${schema.name}`}
+                    to={`/browse/${dbId}/schema/` + encodeURIComponent(schema.name)}
                     mb={1}
                     hover={{ color: color("accent2") }}
                     data-metabase-event={`${ANALYTICS_CONTEXT};Schema Click`}
diff --git a/frontend/src/metabase/lib/urls.js b/frontend/src/metabase/lib/urls.js
index f08632a19..a29d76e5c 100644
--- a/frontend/src/metabase/lib/urls.js
+++ b/frontend/src/metabase/lib/urls.js
@@ -231,11 +231,11 @@ export function browseDatabase(database) {
 }

 export function browseSchema(table) {
-  return `/browse/${table.db.id}/schema/${table.schema_name}`;
+  return `/browse/${table.db.id}/schema/` + encodeURIComponent(table.schema_name);
 }

 export function browseTable(table) {
-  return `/browse/${table.db.id}/schema/${table.schema_name}`;
+  return `/browse/${table.db.id}/schema/` + encodeURIComponent(table.schema_name);
 }

 export function extractEntityId(slug) {
```

**Comment by adamf** [comment]
(I'm not sure why `browseSchema` and `browseTable` return the same thing)

**Comment by adamf** [comment]
PR for the fix created - https://github.com/metabase/metabase/pull/17723

**Comment by harrybiddle** [comment]
Thank you so much for making the PR. By the way, if you have slashes in schema names, I also noticed another bug: field filters no longer work. I intended to write this up as a ticket, but I didn't get around to it yet.

**Comment by adamf** [comment]
@harrybiddle @flamber updated the PR to fix the admin->permissions issue, and to add some tests. Take a look!

**Comment by adamf** [comment]
Not sure how metabase prioritizes bugs, but if it helps gets this fixed I know have at least 10 customers trying to use metabase and failing due to this issue :(

**Comment by flamber** [comment]
@adamf We're working quite hard on finishing 0.41. While I definitely don't understate the gratitude for your PR or the 10 customers that it likely affects hard, there's more than 30k organizations using Metabase. I have already tried to push this, and it currently looks like we will address several schema-related issues in 0.42, though it could be something that arrived in a minor patch release before (not a guarantee).

**Comment by adamf** [comment]
Oh yeah no problem, and appreciate the work here.

**Comment by flamber** [comment]
Reopening - Testing `2098c23`
1. Frontend - Breadcrumb still fails - and global search too
![image](https://user-images.githubusercontent.com/1447303/164510923-3b47127d-6e46-4476-806f-19fd974e170c.png)
2. Backend (or is it just frontend?) - permissions don't work and the frontend gets into a weird state

https://user-images.githubusercontent.com/1447303/164511573-95bb6057-0adb-49ac-8fc6-07f6e117bb19.mp4

**Comment by alxnddr** [comment]
The problem with permissions is different, I created a separate issue for that https://github.com/metabase/metabase/issues/22047
