### ISSUE TITLE
Show the total count of rows in query editor

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1546]

**Comment by maccman** [comment]
+1

**Comment by kdoh** [comment]
Hey @tlrobinson would you mind adding a bit of specificity to this? Would be useful to know more about specific examples or use cases where we aren't showing it when we should and what exactly we mean by total count (overall for the table, for the current result, etc).

**Comment by tlrobinson** [comment]
Actually I filed this for @maccman so maybe he can clarify. Did you mean when we limit you to 2000 rows you'd like to see how many total rows there are?

**Comment by camsaul** [comment]
Don't we already do this?

![screen shot 2016-10-14 at 3 19 05 pm](https://cloud.githubusercontent.com/assets/1455846/19404281/9d114c14-9221-11e6-852d-0cfc280c63de.png)

**Comment by tlrobinson** [comment]
I'm not sure what @maccman meant initially, but we're currently only showing the row count for the table visualization. Now that we officially support graphing "raw data" queries, which are limited to 2,000 rows, we should probably always show truncation warnings.

**Comment by mazameli** [comment]
It's also confusing/misleading that in the query builder's triple dot menu, you can set the row limit to `none`, but then see the `Showing first 2,000 rows` message when viewing raw data.
