### ISSUE TITLE
SSO created user info should not be editable by the user

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15483]
**Describe the bug**
When a user logs in via SSO, then they should not be able to change name or email via Account Settings.

**To Reproduce**
1. Login via SSO
2. Go to Account Settings (`/user/edit_current`)
3. Edit name or email
4. And for SSO (SAML/JWT) the Password tab is available too, which has no effect (this was removed for LDAP+Google in 0.39)

**Expected behavior**
The user should not be able to edit details provided by the SSO.

Unsure if the admin should be able to edit this via Admin > People, since the information should be synced on every login.
This means that manually applied attributes used for Sandboxing will be wiped on login sync. These attributes should perhaps be read-only or come with a warning.
Or manually created attributes should be preserved - similar to #7571 - but not sure what should happen when there's a conflict.

There are cases where users are created manually by the admin to be able to define the groups before first login in cases where the SSO control is handled by a different department than Metabase. See #7677

**Information about your Metabase Installation:**
Tested 1.34.3 thru 1.38.3

**Additional context**
Originally EE175
If we one day officially allow multi-source login, then this needs to be revisited - #11322

**Comment by mazameli** [comment]
Can we close this as fixed thanks to #23298, @WiNloSt?

**Comment by WiNloSt** [comment]
@mazameli Yeah!
