### ISSUE TITLE
Add feature flag for the new 0.39.0 dashboard filter types

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15488]
Make the new filter types opt-in via an environment variable for the time being until we can lock down the way they should work. There are backend and frontend components to this:

### Backend

1.  Define a new `defsetting` with `:setter :none` (which would make it only settable via env var) and `:visibility :public` (which would mean its value would get passed to the FE automatically) for the feature flag
2. Filter code should look at the new feature flag setting and disallow the new filter types unless the flag is enabled

### Frontend

1.  Look at the new feature flag setting and only present the new options if the flag is enabled

**Comment by camsaul** [comment]
Env var only is fine for now, we don't need this to be present in the admin panel at all

**Comment by camsaul** [comment]
Open question: since this is an "experimental" feature, should we document this?

**Comment by dpsutton** [comment]
This sounds like it would work. I think there are three places it needs to be handled for the backend:
- `metabase.query-processor.middleware.parameters.mbql/build-filter-clause`. there's a cond statement on `(ops/operator? param-type)` The body of this condition could put the check there and throw with some "not enabled" error message. This is the mbql creation for the new operators
- `metabase.driver.sql.parameters.substitution/field-filter->replacement-snippet-info` This is the native emission part for the new operators. Same concept, there's a cond on what kind of filter it is, and throw if `(ops/operator? param-type)` but not enabled
- `metabase.driver.mongo.parameters/substitute-param` same deal, if `ops/operator?` but not enabled

and the error thrown should be
```clojure
(throw (ex-info (tru "New operations not enabled")
                {:type :qp.error-type/invalid-parameter
                 :operator parameter-type}))
```

**Comment by paulrosenzweig** [comment]
> Open question: since this is an "experimental" feature, should we document this?

Discussed with Maz and Jeff and reverted the existing docs here: #15491

They're still in master, which I expect will have the feature enabled fully.

**Comment by dpsutton** [comment]
do we have a good name for the setting/feature?

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/15519
