### ISSUE TITLE
pulse title field should have error state + validation

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1548]
since you can't create a pulse without a title we should use our normal form validation to show that the field needs to be filled in if the user blurs or clicks out.

**Comment by agilliland** [comment]
the "normal form validation" we use right now is that if a required field is not filled out then the form simply can't be submitted.  there is no actual indication on the field when someone skips over a required field right now.

**Comment by tlrobinson** [comment]
Yeah I don't think we actually do validate-on-blur anywhere, do we? We certainly can start, though we should probably standardize our form/validation code a bit.
