### ISSUE TITLE
Single Logout - Support Metabase initiated IDP logout 

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15481]
**Is your feature request related to a problem? Please describe.**
When a user logs out of Metabase, make it possible for Metabase to call the SSO IdP to perform single logout (SLO / single signout).

**Describe the solution you'd like**
Add a toggle to allow sending a request to Metabase `/auth/logout/sso`, which both logs out of the IdP and Metabase.

**Describe alternatives you've considered**
Manually signing out of the IdP.

**How important is this feature to you?**
Difficult to switch users in Metabase, when still authenticated on the IdP. Requires manually signing out of the IdP.

**Additional context**
For technical developer details see https://github.com/metabase/metabase-enterprise/issues/237 EE237

**Comment by albertoperdomo** [comment]
This issue title has been reworded to reflect the actual behavior described. For IdP-initiated logout, see #35107 (related).
