### ISSUE TITLE
Filter dropdown disappears or shows up in the incorrect place

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#15502]
**Describe the bug**
Filter dropdown disappears or shows up in the incorrect place.

**Logs**
No JS logs, which is weird.

**To Reproduce**
1. Go ask a custom question
2. Pick a source
3. Click on "Add filters" (it may already show up in the incorrect position)
4. Click outside of the dropdown then again on "Add filters"

**Expected behavior**
For the dropdown to show by the button.

**Screenshots**
![incorrect dropdown placement 1](https://user-images.githubusercontent.com/328388/113749946-1038a600-96bf-11eb-9f31-75378da107ef.gif)
![incorrect dropdown placement 2](https://user-images.githubusercontent.com/328388/113749952-12026980-96bf-11eb-994b-a943e1fc5b71.gif)

**Information about your Metabase Installation:**
```{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.225-121.362.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "bigquery",
      "redshift",
      "druid",
      "mongo",
      "googleanalytics",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-02",
      "tag": "v0.39.0-SNAPSHOT",
      "branch": "master",
      "hash": "b78dced"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
This may affect every single user trying MB, so it seems pretty high up, even if it doesn't fully prevent 

**Additional context**
Resizing the viewport makes the dropdown show up in the second case. And because picking different database tables in the source affects the behavior, I suspect this is related to the data picker.

**Comment by flamber** [comment]
Looks somewhat similar to #15277, but the disappearing popover is a little narly - I'm not seeing that on Firefox.

**Comment by brunobergher** [comment]
They do seem closely related.

**Comment by ariya** [comment]
Is it related to some Popover tweaks due to React 16 upgrade? @nemanjaglumac @daltojohnso

**Comment by nemanjaglumac** [comment]
It _might_ be related, but I'm pretty sure popovers were acting crazy even before the upgrade. @daltojohnso will have more info probably.

**Comment by flamber** [comment]
I can consistently reproduce on Chrome (worst) and Firefox (slightly better) with a viewport of 1920x720

**Comment by nemanjaglumac** [comment]
It seems that height is important. Try anything x 720 and you'll get the same result. I'm preparing a repro and will push soon.

**Comment by flamber** [comment]
I cannot reproduce on 0.39.0
