### ISSUE TITLE
Option to disable export

### ISSUE THREAD

**Issue by flavsind** [metabase/metabase#15526]
**Is your feature request related to a problem? Please describe.**
Some users from my company could export data I expose to their local machine. Lineage would be broken and GDPR legislation not respected in some case.

**Describe the solution you'd like**
Disable export option for a user group from Admin panel.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #6369
Current workaround is to block requests with a reverse-proxy to all requests with [:export-format](https://www.metabase.com/docs/latest/api-documentation.html), but it would be possible to get some exports via Pulse/Subscription, so those functions would need to be blocked too.

**Comment by flamber** [comment]
Closing in favor of #9264
