### ISSUE TITLE
Row visualization shows incorrect labels when grouped by Hour of day

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#15535]
**Describe the bug**
Row visualization shows incorrect labels when grouped by "hour of day". It shows a specific day, month, and year in labels even though the data contains completely different days.

**To Reproduce**
1. Go to the simple question page
2. Open a table with a timestamp column and summarize count by date binned by "hour of day".
3. Select Row visualization

**Expected behavior**
Labels show only hours on labels

**Actual behavior**
Labels include a specific day, month, year in them.

**Screenshots**
<img width="994" alt="Screen Shot 2021-04-09 at 04 12 26" src="https://user-images.githubusercontent.com/14301985/114116125-c503da80-98ec-11eb-8146-a59a4ae65447.png">

**Comment by flamber** [comment]
Very related to #12523
