### ISSUE TITLE
localization - placeholder displayed instead of the actual string

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#15561]
Metabase version 575714b

![Snímek obrazovky 2021-04-12 v 0 22 29](https://user-images.githubusercontent.com/1764151/114323392-42b22b00-9b25-11eb-9958-cd7879fe4809.png)

**Comment by flamber** [comment]
This is close to a P1, since it's throughout the UI
![image](https://user-images.githubusercontent.com/1447303/114448758-3df88000-9bd4-11eb-85eb-873d775fbe29.png)

**Comment by camsaul** [comment]
this is probably related to the new i18n scripts I did in https://github.com/metabase/metabase/pull/15189 -- I'm guessing the JSON output format is slightly off

**Comment by camsaul** [comment]
Fixed by #15599
