### ISSUE TITLE
SQL question - mapping Field Filter as text

### ISSUE THREAD

**Issue by renatojmsantos** [metabase/metabase#15562]
I have this SQL query:
`
select concept, count(*)
from annotation
where exists (select 1
from annotation a2
where a2.comment_commentid = annotation.comment_commentid and a2.concept = 'Fatigue'
)
group by concept;
`
And I want to replace 'Fatigue' with {{word}}, to do a filter widget, maping to the column from database.
`
select concept, count(*)
from annotation
where exists (select 1
from annotation a2
where a2.comment_commentid = annotation.comment_commentid and a2.concept = {{value}}
)
group by concept;
`
I have the following error in Metabase:

>ERROR: syntax error at or near "=" Position: 307

if I do:
`
select concept, count(*)
from annotation
where exists (select 1
from annotation a2
where a2.comment_commentid = annotation.comment_commentid and {{value}}
)
group by concept;
`
It give {{value}} from annotation and not from a2.... and that is not what I want.

What I need to change to aplly the filter? selecting the available words from that column? Or it is a issue and not possible to do?
With variable type as Text it works... But don't display all the available options, in filter, as variable type Field Filter do...

Thanks

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
