### ISSUE TITLE
Can't create a filter on joined table

### ISSUE THREAD

**Issue by Thomassso** [metabase/metabase#15570]
**Describe the bug**
Report goal: create product list and sold product quantity total and product quantity sold with discount.
I couldn't create filter (filter on order.discount column) on joined table.

**To Reproduce**
1. Create a new Custom question
2. Coose Products as main table
3. Left join the Orders table
4. Try to add filter after the join. Column: order.discount . Filter operator: greater. Filtered value: 0 .
5. The *Add filter* button is always inactive, you can't finish the filter creation.

**Expected behavior**
The *Add filter* button will be active when everything is set in filter creation window.

**Screenshots**
![Filter_modal_window_with_inactive_button](https://user-images.githubusercontent.com/27001370/114414923-894c6780-9baf-11eb-9ddb-fa63fe73a423.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_262-b10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_262",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.262-b10",
    "os.name": "Linux",
    "os.version": "4.15.0-133-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.0-rc1",
      "date": "2021-04-06",
      "branch": "release-x.39.x",
      "hash": "471eda1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Our employees need to filter data based on various categories. Some of categories are in other tables. We use star schema. Joins are present in most of our reports.

**Additional context**
-

**Comment by flamber** [comment]
This seems to apply only for number types - I can filter string and date types, and PK/FK numbers.
And doesn't matter if implicit/explicit - and is in Simple and Notebook

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/15605
