### ISSUE TITLE
Duplicated subdimensions for date/time binning

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#15574]
**To Reproduce**
1. Ask a question, Custom question
2. Sample Dataset, Orders table
3. For _Summarize_, Pick a column to group by
4. Created At click on "by month >" to open a popup

**Expected behavior**
The popup does not have duplicated entries.

**Actual behavior**

The popup contains duplicated entries, e.g. for "Minutes".

![image](https://user-images.githubusercontent.com/7288/114432653-c85dc700-9b75-11eb-9c8e-194b9132a07c.png)

**Comment by camsaul** [comment]
@ariya Please don't forget to check that the GH issues get closed once you've merged a PR to fix them 😉

**Comment by nemanjaglumac** [comment]
@camsaul this issue **wasn't** fixed in 15582. Those are two separate issues, although very related.

**Comment by camsaul** [comment]
Ok. Maybe don't put

> It fixes #15574

in the PR description if it doesn't actually fix it 😉

**Comment by nemanjaglumac** [comment]
I am sorry for the confusion caused by reopening and then closing the issue again. I confused it with the related issue.
