### ISSUE TITLE
Database list order is different in Data Reference and Native query

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15598]
1. Navigate to http://localhost:3000/reference/databases
2. List is unsorted. This makes it hard to find what you're looking for if you have a lot of databases. (I know it looks like I have duplicates as well, but those are actually different databases with the same name, e.g. the Postgres and H2 versions of `test-data`)

![image](https://user-images.githubusercontent.com/1455846/114602685-c0705680-9c4b-11eb-8b25-0a6090c5c7ab.png)

Apologies if this is a duplicate but I couldn't find a matching issue.

**Comment by flamber** [comment]
The list in Data Reference is ordered by ID, whereas the list in Native query database selector is getting ordered with javascript (I think), so the order is different depending on casing. It's currently correct in Browse Data and Simple/Custom database selector.
For historians #10515.
