### ISSUE TITLE
Questions with column aliases cannot be connected with category filter in the dashboard

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15593]
**Describe the bug**
Questions with column aliases cannot be connected with category filter in the dashboard

**Logs**

**To Reproduce**
1. Write four native questions
```sql
# Save as `Q1-1` ( No column alias )
select 
    o.TOTAL, 
    o.CREATED_AT, 
    p.CITY, 
    p.SOURCE, 
    s.TITLE, 
    s.CATEGORY, 
    s.VENDOR, 
    s.RATING 
from ORDERS o, PEOPLE p, PRODUCTS s 
where o.USER_ID = p.ID and o.PRODUCT_ID = s.ID
```

```sql
# Save as `Q1-2` ( All column aliases are Chinese characters )
select 
    o.TOTAL 订单总金额, 
    o.CREATED_AT 订单时间, 
    p.CITY 顾客所在城市, 
    p.SOURCE 顾客来源, 
    s.TITLE 商品名, 
    s.CATEGORY 商品类型, 
    s.VENDOR 生产厂商, 
    s.RATING 评分
from ORDERS o, PEOPLE p, PRODUCTS s 
where o.USER_ID = p.ID and o.PRODUCT_ID = s.ID
```

```sql
# Save as `Q1-3` ( The column alias part is Chinese characters )
select 
    o.TOTAL, 
    o.CREATED_AT my_时间, 
    p.CITY my_城市, 
    p.SOURCE my_来源, 
    s.TITLE my_title, 
    s.CATEGORY my_分类, 
    s.VENDOR my_厂家, 
    s.RATING 
from ORDERS o, PEOPLE p, PRODUCTS s 
where o.USER_ID = p.ID and o.PRODUCT_ID = s.ID
```

```sql
# Save as Q1-4 ( All column aliases are in English )
select 
    o.TOTAL my_total, 
    o.CREATED_AT my_create, 
    p.CITY my_city, 
    p.SOURCE my_source, 
    s.TITLE my_tile, 
    s.CATEGORY my_category, 
    s.VENDOR my_vendor, 
    s.RATING my_rating

from ORDERS o, PEOPLE p, PRODUCTS s 
where o.USER_ID = p.ID and o.PRODUCT_ID = s.ID
```
2. Q1-1, Q1-2, Q1-3, Q1-4 perform the same `metric` operation and `group by` operation, Save as Q2-1, Q2-2, Q2-3, Q2-4
like this 
![image](https://user-images.githubusercontent.com/3394927/114568791-06a6d380-9ca7-11eb-9bb0-f47408132132.png)
3. Add Q2-1, Q2-2, Q2-3, Q2-4 to the same dashboard, Add a category filter to the dashboard, Add a date filter to the dashboard
4. Select the category filter, then I found:
	1) The category filter cannot be connected to some questions
	2) The connectable items shown in some questions are inconsistent
	3) The date filter can be connected to all questions, only the date filter can work

**Expected behavior**
Connected to the category filter, all connected items displayed in the question are the same

**Screenshots**
![录制_20210416083946767](https://user-images.githubusercontent.com/3394927/114955487-63fd7900-9e8f-11eb-9aa2-460dffa7140b.gif)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "GBK",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_101-b13",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_101",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.101-b13",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.4",
      "date": "2021-04-08",
      "branch": "release-x.38.x",
      "hash": "057b6bb"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```
- Chrome 88.0.4324.104
- Windows 10 Pro
- MySQL5.7
- Metabase version: v0.38.4
- Metabase hosting environment: Windows Server 2016 Datacenter、Windows 10 Pro
- Metabase internal database: H2

**Severity**
it is annoying;
Hinder the leader's use;

**Comment by 8debug** [comment]
Can this bug be reproduced?

**Comment by paoliniluis** [comment]
Hi, I just tried to reproduce in latest (v40.1) and couldn't see the issue. When you create a native query you have to pass filters to those so they can be seen from the Dashboard. E.g.:

select 
    o.TOTAL 订单总金额, 
    o.CREATED_AT 订单时间, 
    p.CITY 顾客所在城市, 
    p.SOURCE 顾客来源, 
    s.TITLE 商品名, 
    s.CATEGORY 商品类型, 
    s.VENDOR 生产厂商, 
    s.RATING 评分
from ORDERS o, PEOPLE p, PRODUCTS s 
where o.USER_ID = p.ID and o.PRODUCT_ID = s.ID
and 订单总金额 = {{filter1}}

maybe I missunderstood the issue, but I can't reproduce
