### ISSUE TITLE
Missing empty state for item picker popup (dashboards, collections, questions)

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#15611]
**Description**
When a user is selecting e.g. a dashboard with a picker popup and selects a collection that does not contain any dashboards, the popup is a bit confusing and it's not clear what to do

**To Reproduce**

1. Go to a question page (e.g. `/question/1`)
2. Click the pencil icon in the top left corner
3. Click "Add to dashboard"
4. An item picker popup shows up, open any collection that does not contain any dashboard
5. Nothing is displayed

**Expected behavior**
Would be nice to have a more clear empty state, e.g. a message like "This collection has no dashboards yet, but you can create a new one". There is a button to create a new dashboard already, but the experience is still a bit confusing

**Screenshots**
<img width="1315" alt="item-picker-empty-state" src="https://user-images.githubusercontent.com/17258145/114682148-7d7bb500-9d17-11eb-9107-f88bba19a98f.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Metabase version: v0.39.0-SNAPSHOT
- Metabase hosting environment: local, release-x.39.x
- Metabase internal database: H2 (default), sample dataset

**Severity**
P3 or lower

**Additional context**
The picker is used for dashboards, collections and questions, so the empty state message has to handle that

**Comment by brunobergher** [comment]
Not applicable with the new entity picker.
