### ISSUE TITLE
Configure gauge with two (or more) numbers

### ISSUE THREAD

**Issue by wmonk** [metabase/metabase#15628]
**Is your feature request related to a problem? Please describe.**
We have a target of rows created by a certain date. We have a seven day rolling count of those rows created. Given there is a target, the amount of rows created is variable by day. I.e. 200 users in 100 days = 1 user per day. If I have no users for 10 days, then I require over 2 users per day to hit my target. This is visualised nicely with the milestone graph, **and** the gauge, to see how on track I am.

**Describe the solution you'd like**
Allow a query that returns _n_ numbers to configure the gauge. I.e. you could pick one column as the marker, and then use the other columns in the min/max boxes.

**Describe alternatives you've considered**
A plain and boring table, this just isn't very impactful as a graphic.

**How important is this feature to you?**
Fairly important. Not the end of the world, but makes the gauge a generally more useful graphic.

**Additional context**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/175278/114860299-bbdea600-9de3-11eb-9efb-80833a0a5d8b.png">

vs. 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/175278/114860335-c731d180-9de3-11eb-98a9-19a72c83a647.png">

**Comment by flamber** [comment]
Hi @wmonk 
Sounds like a duplicate of #6514 ?

**Comment by wmonk** [comment]
@flamber think you might be right, apologies I did try searching first but nothing came up under my terms.
