### ISSUE TITLE
Filtering of twice summarized questions does not work in the simple question mode

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#15620]
When a question has nested aggregation in the custom question mode, it is not possible to apply a filter for this question in the simple question mode.

**To Reproduce**
1) Recreate custom question using Products table of the sample dataset and press "Visualize"
2) Try to filter by Category dimension

<img width="1083" alt="Screen Shot 2021-04-15 at 00 20 56" src="https://user-images.githubusercontent.com/14301985/114781213-12ff5f00-9d81-11eb-8838-e5e9f9b77ad9.png">

**Actual behavior**
It is not possible to save the filter with an entered value

**Expected behavior**
Make it possible to add a filter

**Information about your Metabase Installation:**
Latest `release-x.39.x` branch

**Comment by flamber** [comment]
This is a state-problem, and been around since at least 0.36.8.2 (didn't test earlier)
https://user-images.githubusercontent.com/1447303/114861943-3ad8dc00-9dee-11eb-8d3b-37fc1fa233f5.mp4

**Comment by nemanjaglumac** [comment]
The screenshot is showing the custom question mode, not the simple one. Maybe update the title if this happens only for custom mode.

**Comment by flamber** [comment]
@nemanjaglumac See my video (9th second) - it also happens in Simple.

**Comment by nemanjaglumac** [comment]
Do you want me to cover both scenarios? Is there any added benefit in it?
I already pushed a repro for the custom question.

> it also happens in Simple
In that case, title shouldn't contain any of the two modes. It should simply say that Filtering on twice summarized questions doesn't work.

**Comment by flamber** [comment]
@nemanjaglumac It's probably fine with a single test, but it's getting to a point where we might need to test Notebook, sidebar and column-level for all these tests, since the code is not the same.
