### ISSUE TITLE
Cannot set the type of sql custom column to the location in the Data Model

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15625]
**Describe the bug**
Cannot set the type of sql custom column to the location in the Data Model

**To Reproduce**
1. Go to 'Write sql'
2. Click on 'my dataset'
3. Write sql, Similar to the following statement
```sql
select
    u.*, 
    CASE
        WHEN instr(address,   '和平区' ) > 0  THEN 210102
        WHEN instr(address,   '沈河区' ) > 0  THEN 210103
        WHEN instr(address,   '大东区' ) > 0  THEN 210104
        WHEN instr(address,   '皇姑区' ) > 0  THEN 210105
        WHEN instr(address,   '铁西区' ) > 0  THEN 210106
        WHEN instr(address,   '苏家屯区' ) > 0  THEN 210111
        WHEN instr(address,   '浑南区' ) > 0  THEN 210112
        WHEN instr(address,   '沈北新区' ) > 0  THEN 210113
        WHEN instr(address,   '于洪区' ) > 0  THEN 210114
        WHEN instr(address,   '辽中区' ) > 0  THEN 210115
        WHEN instr(address,   '新民市' ) > 0  THEN 210181
        WHEN instr(address,   '康平县' ) > 0  THEN 210123
        WHEN instr(address,   '法库县' ) > 0  THEN 210124
    END STATE
from my_user u
```
4.  Can not use map, As shown below
![image](https://user-images.githubusercontent.com/3394927/114832040-9e6c0500-9e00-11eb-814c-3b2b737053c9.png)

**Expected behavior**
Make custom columns can be applied to `Region map` or `Pin map` or `Grid map`
![image](https://user-images.githubusercontent.com/3394927/114831849-68c71c00-9e00-11eb-9d72-c02e1a08a537.png)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "3.10.0-862.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.2",
      "date": "2021-03-17",
      "branch": "release-x.38.x",
      "hash": "91f0ed6"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```
- Chrome 88.0.4324.104
- Windows 10 Pro
- Oracel 11g
- Metabase version: v0.38.2、v0.38.3、v0.38.4
- Metabase hosting environment: Windows Server 2016 Datacenter、Centos7、Windows 10 Pro
- Metabase internal database: H2

**Comment by flamber** [comment]
@8debug Without knowing your GeoJSON structure, then it's not possible to see if the region identifier is correct.
Please include your custom map.
https://www.metabase.com/docs/latest/administration-guide/20-custom-maps.html

**Comment by 8debug** [comment]
> @8debug Without knowing your GeoJSON structure, then it's not possible to see if the region identifier is correct.
> Please include your custom map.
> https://www.metabase.com/docs/latest/administration-guide/20-custom-maps.html

https://geo.datav.aliyun.com/areas_v2/bound/210100_full.json

**Comment by flamber** [comment]
@8debug It work fine, when the region identifier is set correctly:
![image](https://user-images.githubusercontent.com/1447303/114841930-a57f1d00-9dd8-11eb-8a92-db2547f448e8.png)
![image](https://user-images.githubusercontent.com/1447303/114841876-99935b00-9dd8-11eb-906e-4f72305bcb72.png)
