### ISSUE TITLE
Provide breadcrumb path back to dashboard when drill-through to question

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15624]
**Describe the bug**
Cannot return to the X-ray page from the detail page

**To Reproduce**
1. Go to Home page
2. Click on 'Sample Dataset'
3. Click on 'X-ray this table' into the x-ray page, As shown below
![image](https://user-images.githubusercontent.com/3394927/114804643-34d60180-9dd4-11eb-8304-8bdff39934d3.png)

4. Click on 'Sales per source', As shown below
![image](https://user-images.githubusercontent.com/3394927/114803948-fab83000-9dd2-11eb-8496-2e3876e6ab0a.png)
5. Drag the selected area, As shown below
![image](https://user-images.githubusercontent.com/3394927/114804029-23d8c080-9dd3-11eb-9db2-52396edc549a.png)
6. Go to another details page, As shown below
![image](https://user-images.githubusercontent.com/3394927/114804226-8df16580-9dd3-11eb-92e0-cdde75e6024c.png)
7. Cannot return to the x-ray page directly, only use the browser's back button to go back continuously

**Expected behavior**
Provide an operation that can directly return to the x-ray page

**Screenshots**
![录制_2021041510275510](https://user-images.githubusercontent.com/3394927/114805374-7915d180-9dd5-11eb-98c1-7be29b8089b7.gif)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "GBK",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_101-b13",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_101",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.101-b13",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.4",
      "date": "2021-04-08",
      "branch": "release-x.38.x",
      "hash": "057b6bb"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```
- Chrome 88.0.4324.104
- Windows 10 Pro
- MySQL5.7
- Metabase version: v0.38.4
- Metabase hosting environment: Windows Server 2016 Datacenter、Windows 10 Pro
- Metabase internal database: H2

**Severity**
it is annoying;
Hinder the leader's use;

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by 8debug** [comment]
### The dashboard has the same problem

**Comment by brunobergher** [comment]
Completed alongside #17876
