### ISSUE TITLE
Logging out after changing password is broken

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#15636]
**Describe the bug**
If you change your password, then attempt to log out, the behavior is completely broken.  You have to manually go back to the base URL in your browser to get a fresh login screen.

**Logs**
N/A

**To Reproduce**
1. Log into Metabase
2. Go to Account settings (under gearbox menu)
3. Click Password
4. Enter your current password, and a new one, then click Save
5. Click Sign out (under gearbox menu)
6. A blank screen is shown (with the top bar still in place).  Attempting to do a browser refresh will just show a totally blank viewport.

**Expected behavior**
Upon logging out (even after changing the password), the user should be redirected to the login page as per usual.

**Screenshots**
None

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 89
- Your operating system: OS X 11
- Your databases: None
- Metabase version: 1.39 RC
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Minor

**Additional context**
N/A

**Comment by flamber** [comment]
This is because after changing the password, then the session has been invalidated, so the it's already logged out - clicking the "Sign out" will then not do a proper redirect, which is likely the same reason as #15471, since there's incorrect React routes.
