### ISSUE TITLE
an invalid card id in the query builder just shows a blank screen 

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1563]
to reproduce:

either find a link to a deleted card or add some random number to the ```q/<card-id>``` url and you'll get your very own blank screen.

we should ensure that if a question with the proper ID can't be found we handle this in a more predictable and purposeful way.

**Comment by agilliland** [comment]
+1

**Comment by agilliland** [comment]
@kdoh is the below sufficient?

<img width="1547" alt="screen shot 2016-01-25 at 5 58 43 pm" src="https://cloud.githubusercontent.com/assets/1987787/12570571/91d6af96-c38d-11e5-9556-a01ad9640ad6.png">

**Comment by kdoh** [comment]
:+1:
