### ISSUE TITLE
Strings with placeholders like {0} aren't translating correctly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15642]
I think there's an argument to be made this is a release blocker given that it the UI look broken in many cases for seemingly all our languages.

Anywhere in the product where we have strings like `See this {0}` or `Include {0}` are showing up with the placeholder tag literally displayed instead of being replaced with the correct word. I've tried this with multiple languages, and none seem to be working right.

Here's an example from the Data Reference in Vietnamese:

![image](https://user-images.githubusercontent.com/2223916/114940410-a7f06f80-9df6-11eb-9074-1d0941ca1235.png)

Here's the query builder in Spanish:

![image](https://user-images.githubusercontent.com/2223916/114940618-f30a8280-9df6-11eb-825d-086abec31517.png)

Table conditional formatting settings in Brazillian Portuguese: 

![image](https://user-images.githubusercontent.com/2223916/114941105-9196e380-9df7-11eb-914a-fc8b515ec04a.png)

**Comment by camsaul** [comment]
Duplicate of #15561 -- fixed by #15599

**Comment by mazameli** [comment]
@camsaul Just to double-check — if this is already fixed, why was I seeing it after pulling changes from release-x.39.x and building locally this morning?

**Comment by camsaul** [comment]
Did you rebuild the translation resources, and restart the server?

**Comment by mazameli** [comment]
I built translation resources last night, and started the server this morning.

**Comment by mazameli** [comment]
I'll try again now.

**Comment by mazameli** [comment]
Worked. 🤷🏼 Mea culpa.
