### ISSUE TITLE
After choosing Sum or Average, the field pop-over should always appear

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1564]
Currently it's inconsistent. Specifically, if you already have Sum or Average selected, and then choose Sum or Average, the field pop-over doesn't appear automatically.

**Comment by mazameli** [comment]
![popover](https://cloud.githubusercontent.com/assets/2223916/11411633/b60a6e84-9386-11e5-9732-0fe67326600c.gif)

**Comment by agilliland** [comment]
I would even go one step further and say that ideally it wouldn't be 2 separate selectors.  Seems like there should be a smooth transition within the existing selector which transitions from "Sum" to picking the field you want to sum.

**Comment by kdoh** [comment]
Yeah it might be interesting to explore how this interaction feels using the two stage pattern we have for filter field and value selection.

**Comment by mazameli** [comment]
Well, I think one of the advantages of the current design is that you can independently change the aggregation type or the field selection without having to go through the two-stage pattern. If you know you want to change the aggregation, you just click on it; same with the field selection.

**Comment by agilliland** [comment]
Closing this as being addressed by #1947
