### ISSUE TITLE
Metabase crashes during muti-database query if any database is offline

### ISSUE THREAD

**Issue by JordanAmentco** [metabase/metabase#15647]
Issue is as Follows:
1. Create a metabase setup with more than 1 active connection to different databases. Say 10 active databases in the field in this example.
2. Run the exact same query against all the databases (eg. select * from <database> etc....)
3. Receive Valid Response
4. Bring 1 out of 10 databases offline for maintenance.
5. Run the same query as in step 2.
6. Receive no data back from any of the databases even though they are online.
7. Metabase is now frozen until CMD interaction from a user or it is restarted.

Educated guess is that the query is run in a try catch around a for loop and failure on any of the queries returns nothing for the others because of this.

**Comment by flamber** [comment]
Hi @JordanAmentco 

Please include "Diagnostic Info" from Admin > Troubleshooting, and which database types you're querying.

Can you explain in more details what you're doing in step 2 and 5?
I cannot reproduce following your steps, so it would be very helpful if you could provide more details.

And include logs too - either from console or Admin > Troubleshooting > Logs.

**Comment by JordanAmentco** [comment]
Hi there, My apologies for the delay in response. I have since had more clarity on the issue from the site, the issue is better described as "metabase freezes during multi-step query if one step fails on any database". I am updating the original ticket to reflect this. This is a bug that happens when a single query targets multiple databases in multiple stages then merges the results. Making the CMD GUI the active window releases the freeze.

**Comment by JordanAmentco** [comment]
@flamber Can I please request that this ticket be re-reviewed with the updated information. I am unable to provided logs from the system as I do not have direct access to it.

**Comment by flamber** [comment]
@JordanAmentco 
1. Post "Diagnostic Info" from Admin > Troubleshooting
2. You can find the logs where you launch Metabase from - what you refer to as CMD I guess
3. I cannot reproduce, so please provide much more details.
