### ISSUE TITLE
[Snowflake] Date Filter in Dashboards off by one day

### ISSUE THREAD

**Issue by soltanianalytics** [metabase/metabase#15651]
**Describe the bug**
When using the date filter on a Dashboard and set it to an exact date, somehow the results are off by exactly one day.

**To Reproduce**
1. Go to a dashboard that has a filter on a date column
2. Click on it, and set it to a specific date (e.g. April 13)
3. See that the result is for the next day (e.g. April 14)

Note: Not only is the date of that question off by one; all metrics in the dashboard are calculated for April 14 instead of April 13!

**Expected behavior**
The date should be set correctly and calculations should work correctly.

**Screenshots and SQL queries**
Screenshots:
1. April 13 is selected, but the query shows April 14 (the query 
2. SQL query: when going into the (filtered) question, this is the resulting query (anonymized and beautified) - this query looks correct (!) but in Metabase, the result is incorrect
3. Screenshot of the question's definition

1) ![image](https://user-images.githubusercontent.com/46958547/114995815-8054e200-9e9e-11eb-936e-9741bc224656.png)
2) SQL query as per Metabase UI
```sql
-- This is the query as shown by Metabase in the UI of the question
-- Running this in the Snowflake GUI gives the correct date (April 13) but somehow, Metabase produces the wrong date
-- This cannot just be a visualization issue: all metrics are also calculated for April 14 instead of April 13
SELECT
  date_trunc("day", CAST("source"."BUCHUNGSDATUM" AS timestamp)) AS "BUCHUNGSDATUM"
  , count(*) AS "count"
FROM (
  SELECT ..., "database"."schema"."table"."BUCHUNGSDATUM" AS "BUCHUNGSDATUM"
  FROM "database"."schema"."table"
) "source"
WHERE (
   "source"."BUCHUNGSDATUM" >= timestamp '2021-04-13 00:00 Z'
   AND "source"."BUCHUNGSDATUM" < timestamp '2021-04-14 00:00 Z'
)
GROUP BY date_trunc("day", CAST("source"."BUCHUNGSDATUM" AS timestamp))
ORDER BY date_trunc("day", CAST("source"."BUCHUNGSDATUM" AS timestamp)) ASC
```
3) Metabase UI of the question with the above SQL: 
![image](https://user-images.githubusercontent.com/46958547/114996709-623bb180-9e9f-11eb-8d74-a28682ac4c08.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.15.0-139-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-08",
      "tag": "v0.38.4",
      "branch": "release-x.38.x",
      "hash": "057b6bb"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
**Very annoying** because the data is wrong by a day, and we have significant daily volatility in the results.

**Final Notes**
Setting the date to "yesterday" actually works correctly, interestingly enough.

**Comment by flamber** [comment]
Hi @soltanianalytics 

Just to completely understand this - you're saying that you're getting the correct results when you view the question with similar filter, but only on dashboards with single-date filter, then the results are not correct?

Initially I thought you were seeing issue #8804, but you're using UTC for both Java and Report Timezone.

It would be extremely helpful if you can provide a sample schema, so we have something to reproduce the problem with.

**Comment by soltanianalytics** [comment]
Hey,

Yes, when I use "yesterday", it is correct. In that case, the SQL uses `current_date` instead of fixed timestamps, which is probably why it works. Only when I set a specific date I have the error.

I think it may still be somehow related to #8804.

In terms of sample schema: We changed the type of the column to `date` and now it seems to work correctly - I believe it was `timestamp` previously, although it was always a midnight timestamp.

**Comment by flamber** [comment]
@soltanianalytics Can you include the DDL, so it can be reproduced?
I'm guessing you were using `timestamp` and not `timestamptz` previously, which means that Metabase does not handle the timezone in those cases. There are several issues open about that, but it's likely #8804 in this case, since Snowflake does currently not support Report Timezone: https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html
