### ISSUE TITLE
Some binning option strings are not translated

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15660]
**Describe the bug**
Some binning option strings are not translated anymore. I'm not quite sure what's happening. Seems to be all for languages.

**To Reproduce**
Simple/Custom question > Sample Dataset > Orders - click Summarize and open the binning popover for CreatedAt
Notice "Minute" through "Year" is not translated anymore. But it is translated in the little "selected granularity" when selected.
![image](https://user-images.githubusercontent.com/1447303/115070940-e456c500-9ef5-11eb-804b-6e1ddc765bd4.png)

This is how it looks in 0.38.4
![image](https://user-images.githubusercontent.com/1447303/115070924-dd2fb700-9ef5-11eb-964a-0b428b9ffa8b.png)

**Information about your Metabase Installation:**
release-x.39.x commit `899467c`

**Additional context**
Related to #8964

**Comment by CZvacko** [comment]
My problem is slightly different: in the binning options I have some strings translated and (duplicated) untranslated.
![Binning](https://user-images.githubusercontent.com/66993187/115659395-c5fc2980-a33a-11eb-9b3e-e9bddbfefcbd.jpg)

But this is just a minor problem, the bigger problem is that when I select a binning option, the related field disappears in the result of the produced question (only the default binnning option works). 
And the worst problem is that the question (created in the earlier version) **stopped work** (unable to edit it, move, archive it).
 
In my case, also "activity" page stopped work, the activity list is empty and still showing "Loading". Not sure if its related, but log show error like 
`[f8eb78f4-93d5-4edd-93b5-5558e48cf6f4] 2021-04-22T06:22:01+02:00 ERROR metabase.models.interface Unable to normalize: `
`....a lot of text...`
`[f8eb78f4-93d5-4edd-93b5-5558e48cf6f4] 2021-04-22T06:22:01+02:00 ERROR metabase.mbql.normalize Neplatná klauzule: [:datetime-field [:field-literal RETURN_DATE :type/Date] :minute]`

**Comment by flamber** [comment]
@CZvacko Can you create two issues with steps-to-reproduce and logs. I cannot reproduce and it's unrelated to this issue.

**Comment by ariya** [comment]
Related: #15574 and #15446. Likely cause: the interplay between MBQL field refactoring and subdimensions.

**Comment by ariya** [comment]
Somehow this happens because the back-end does not return a fully translated reponse.

Check by looking at the output of `/api/table/1/query_metadata`. It's a long response but I include a relevant snippet here:

```
    "dimension_options": {
        "9": {
            "name": "Wochentag",
            "mbql": [
                "field",
                null,
                {
                    "temporal-unit": "day-of-week"
                }
            ],
            "type": "type/DateTime"
        },
        "3": {
            "name": "Week",
            "mbql": [
                "field",
                null,
                {
                    "temporal-unit": "week"
                }
            ],
            "type": "type/DateTime"
        },
```
This was with the user language set to German. As you can see, `day-of-week` is correctly assigned the translated phrase _Wochentag_, while `week` stays English _Week_.

I believe all these strings were originated in `src/metabase/api/table.clj` but it's not clear to me how some strings are translated and some aren't.
