### ISSUE TITLE
When loading the dashboard page in metabase might occur error - Error: Minified React error #185

### ISSUE THREAD

**Issue by Theo-Lo** [metabase/metabase#15668]
**Describe the bug**
The bug does not happen everytime. But sometimes when using the dashboard, it will show a crying emoji and the page is simply went into error. We are not sure how it can be triggered. But should be simple usage of the dashboard like clicking the filter widget and choosing some filter. Or de-selecting some filter. When I open the console log, it will have this error:
vendor.bundle.js?3b52aa11921c277ac89f:487 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Which should be about the setState reached limit, however, it seems to be the problem of metabase code instead of something we can alter in the metabase UI. I have checked the troubleshoot log, it is just asking for compulsory parameters that haven't input, which is reasonable as we have not yet chosen all the mandatory filter.

**Logs**
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iu (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at Object.enqueueSetState (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at t.b.setState (vendor.bundle.js?3b52aa11921c277ac89f:448)
    at t.value (app-main.bundle.js?3b52aa11921c277ac89f:5)
    at bo (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at Ia (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at vs (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at vu (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at gu (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at uu (vendor.bundle.js?3b52aa11921c277ac89f:487)
Error caught in <App> Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iu (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at Object.enqueueSetState (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at t.b.setState (vendor.bundle.js?3b52aa11921c277ac89f:448)
    at t.value (app-main.bundle.js?3b52aa11921c277ac89f:5)
    at bo (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at Ia (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at vs (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at vu (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at gu (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at uu (vendor.bundle.js?3b52aa11921c277ac89f:487) {componentStack: "↵    in t↵    in DashboardGrid↵    in div↵    in d…↵    in t↵    in DragDropContextProvider↵    in a"}
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at et (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at vendor.bundle.js?3b52aa11921c277ac89f:487
    at tt (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at Object.t.findDOMNode (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at d.value (app-main.bundle.js?3b52aa11921c277ac89f:5)
    at n._updateSize (app-main.bundle.js?3b52aa11921c277ac89f:5)
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at vendor.bundle.js?3b52aa11921c277ac89f:487
    at tt (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at Object.t.findDOMNode (vendor.bundle.js?3b52aa11921c277ac89f:487)
    at d.value (app-main.bundle.js?3b52aa11921c277ac89f:5)
    at n._updateSize (app-main.bundle.js?3b52aa11921c277ac89f:5)

Logs from troubleshoot log:
[84e2737e-eb71-48e7-bdb9-2f8adb119eeb] 2021-04-19T15:50:15+08:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 2,
 :started_at #t "2021-04-19T07:50:15.594295Z[UTC]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error determining value for parameter",
   :stacktrace
   ["--> driver.common.parameters.values$fn__77861$value_for_tag__77866$fn__77867.invoke(values.clj:313)"
    "driver.common.parameters.values$fn__77861$value_for_tag__77866.invoke(values.clj:306)"
    "driver.common.parameters.values$fn__77885$query__GT_params_map__77890$fn__77894$iter__77896__77900$fn__77901.invoke(values.clj:328)"
    "driver.common.parameters.values$fn__77885$query__GT_params_map__77890$fn__77894.invoke(values.clj:327)"
    "driver.common.parameters.values$fn__77885$query__GT_params_map__77890.invoke(values.clj:318)"
    "driver.sql$fn__79749.invokeStatic(sql.clj:44)"
    "driver.sql$fn__79749.invoke(sql.clj:40)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)"
    "query_processor.middleware.parameters$expand_all$replace_47337__47338.invoke(parameters.clj:59)"
    "mbql.util.match$replace_in_collection$iter__17987__17991$fn__17992.invoke(match.clj:139)"
    "mbql.util.match$replace_in_collection.invokeStatic(match.clj:138)"
    "mbql.util.match$replace_in_collection.invoke(match.clj:133)"
    "query_processor.middleware.parameters$expand_all$replace_47337__47338.invoke(parameters.clj:59)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)"
    "query_processor.middleware.parameters$fn__47353$substitute_parameters_STAR___47358$fn__47359.invoke(parameters.clj:82)"
    "query_processor.middleware.parameters$fn__47353$substitute_parameters_STAR___47358.invoke(parameters.clj:79)"
    "query_processor.middleware.parameters$substitute_parameters$fn__47379.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45647.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__46268.invoke(expand_macros.clj:155)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44393.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48371.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47582$fn__47586.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47582.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46508.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__48380$fn__48381.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__48380.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__48425.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__46643.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44239.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48356.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__405.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__47468.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45829.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___37687$thunk__37688.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___37687$fn__37690.invoke(reducible.clj:108)"],
   :error_type :missing-required-parameter,
   :ex-data
   {:tag
    {:id "3c006fda-0a98-01fe-856f-68a75e86fe27",
     :name "microservice",
     :display-name "Microservice",
     :type :dimension,
     :dimension [:field 5054 nil],
     :widget-type :category,
     :required true},
    :type :missing-required-parameter}}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error building query parameter map",
   :stacktrace
   ["--> driver.common.parameters.values$fn__77885$query__GT_params_map__77890$fn__77894.invoke(values.clj:336)"
    "driver.common.parameters.values$fn__77885$query__GT_params_map__77890.invoke(values.clj:318)"
    "driver.sql$fn__79749.invokeStatic(sql.clj:44)"
    "driver.sql$fn__79749.invoke(sql.clj:40)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)"
    "query_processor.middleware.parameters$expand_all$replace_47337__47338.invoke(parameters.clj:59)"
    "mbql.util.match$replace_in_collection$iter__17987__17991$fn__17992.invoke(match.clj:139)"
    "mbql.util.match$replace_in_collection.invokeStatic(match.clj:138)"
    "mbql.util.match$replace_in_collection.invoke(match.clj:133)"
    "query_processor.middleware.parameters$expand_all$replace_47337__47338.invoke(parameters.clj:59)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)"
    "query_processor.middleware.parameters$fn__47353$substitute_parameters_STAR___47358$fn__47359.invoke(parameters.clj:82)"
    "query_processor.middleware.parameters$fn__47353$substitute_parameters_STAR___47358.invoke(parameters.clj:79)"
    "query_processor.middleware.parameters$substitute_parameters$fn__47379.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45647.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__46268.invoke(expand_macros.clj:155)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44393.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48371.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47582$fn__47586.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47582.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46508.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__48380$fn__48381.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__48380.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__48425.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__46643.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44239.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48356.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__405.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__47468.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45829.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___37687$thunk__37688.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___37687$fn__37690.invoke(reducible.clj:108)"],
   :error_type :missing-required-parameter,
   :ex-data
   {:type :missing-required-parameter,
    :tags
    {"datefilter"
     {:id "58d0d0d4-c61a-5db5-54fb-f873470b362b",
      :name "datefilter",
      :display-name "Date Filter",
      :type :dimension,
      :dimension [:field 5185 nil],
      :widget-type :date/all-options,
      :required true},
     "hour"
     {:id "8a11ed7d-378e-ca14-82b5-e2b0e97e4955",
      :name "hour",
      :display-name "Hour",
      :type :dimension,
      :dimension [:field 5055 nil],
      :widget-type :category,
      :default nil},
     "log" {:id "283b4ec1-b7d6-999a-93e4-54b7b9b00f53", :name "log", :display-name "Log", :type :text},
     "microservice"
     {:id "3c006fda-0a98-01fe-856f-68a75e86fe27",
      :name "microservice",
      :display-name "Microservice",
      :type :dimension,
      :dimension [:field 5054 nil],
      :widget-type :category,
      :required true},
     "clustername"
     {:id "e3e2ed36-1d6d-8d3c-b1fa-47578b22ea68",
      :name "clustername",
      :display-name "Clustername",
      :type :dimension,
      :dimension [:field 5053 nil],
      :widget-type :category,
      :required true},
     "environment"
     {:id "fb04a463-41ce-9ccb-5e1c-20520f3ae194",
      :name "environment",
      :display-name "Environment",
      :type :dimension,
      :dimension [:field 5050 nil],
      :widget-type :category,
      :required true},
     "namespace"
     {:id "b6fc2d72-e2a3-5a3d-113f-a182a7410dc3",
      :name "namespace",
      :display-name "Namespace",
      :type :dimension,
      :dimension [:field 5057 nil],
      :widget-type :category,
      :required true},
     "loglevel"
     {:id "9633dbd8-d670-17ad-049b-879eb3ebb5f0",
      :name "loglevel",
      :display-name "Loglevel",
      :type :dimension,
      :dimension [:field 5101 nil],
      :widget-type :category,
      :default nil},
     "organization"
     {:id "8045ceae-7b28-0611-6e69-ed7cfa7c3d71",
      :name "organization",
      :display-name "Organization",
      :type :dimension,
      :dimension [:field 5052 nil],
      :widget-type :category,
      :required true},
     "projectcode"
     {:id "71b2f318-d0b8-1e48-75fe-4df05627e7b7",
      :name "projectcode",
      :display-name "Projectcode",
      :type :dimension,
      :dimension [:field 5051 nil],
      :widget-type :category,
      :required true}},
    :params [{:type :date/all-options, :target [:dimension [:template-tag "datefilter"]], :value "past0days~"}]}}],
 :error_type :missing-required-parameter,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 10000},
  :type :native,
  :middleware {:js-int-to-string? true},
  :native
  {:query
   "SELECT date_format(from_unixtime(cast(DT.time as int)), '%Y-%m-%d %H:%i:%S') as timestamp, DT.log as \"log(*right click to view details)\",  DT.stream, DT.clustername, DT.organization, DT.projectcode, DT.environment, DT.namespace, DT.microservice\r\nFROM rancher.rancher_app_log DT\r\nLEFT JOIN rancher.rancher_app_log_view ON  \r\n    rancher.rancher_app_log_view.clustername = DT.clustername\r\n    AND rancher.rancher_app_log_view.organization = DT.organization\r\n    AND rancher.rancher_app_log_view.projectcode = DT.projectcode\r\n    AND rancher.rancher_app_log_view.environment = DT.environment\r\n    AND rancher.rancher_app_log_view.namespace = DT.namespace\r\n    AND rancher.rancher_app_log_view.microservice = DT.microservice\r\n    AND rancher.rancher_app_log_view.year = DT.year\r\n    AND rancher.rancher_app_log_view.month = DT.month\r\n    AND rancher.rancher_app_log_view.day = DT.day\r\n    AND rancher.rancher_app_log_view.hour = DT.hour\r\n    AND (TO_DATE(CONCAT(CAST(DT.year as varchar(10)) , '/' , CAST(DT.month as varchar(10)) , '/' , CAST(DT.day as varchar(10))), 'yyyy/mm/dd') = rancher.rancher_app_log_view.formatted_date)\r\nLEFT JOIN rancher.rancher_app_log_loglevel ON\r\n    UPPER(DT.log) LIKE UPPER(CONCAT('% ', rancher.rancher_app_log_loglevel.loglevel,' %'))\r\n    OR UPPER(DT.log) LIKE UPPER(CONCAT('%[', rancher.rancher_app_log_loglevel.loglevel,']%'))\r\n    OR UPPER(DT.log) LIKE UPPER(CONCAT('%[', rancher.rancher_app_log_loglevel.loglevel,'ing]%'))\r\n    OR UPPER(DT.log) LIKE UPPER(CONCAT('%<', rancher.rancher_app_log_loglevel.loglevel,'>%'))\r\nWHERE {{clustername}}\r\n    AND {{organization}}\r\n    AND {{projectcode}}\r\n    AND {{environment}}\r\n    AND {{namespace}}\r\n    AND {{microservice}}\r\n    AND {{datefilter}}\r\n    AND {{hour}}\r\n    [[AND {{loglevel}}]]\r\n    [[AND UPPER(DT.log) LIKE UPPER(CONCAT('%', {{log}},'%'))]]\r\nORDER BY timestamp DESC",
   :template-tags
   {"datefilter"
    {:id "58d0d0d4-c61a-5db5-54fb-f873470b362b",
     :name "datefilter",
     :display-name "Date Filter",
     :type :dimension,
     :dimension [:field 5185 nil],
     :widget-type :date/all-options,
     :required true},
    "hour"
    {:id "8a11ed7d-378e-ca14-82b5-e2b0e97e4955",
     :name "hour",
     :display-name "Hour",
     :type :dimension,
     :dimension [:field 5055 nil],
     :widget-type :category,
     :default nil},
    "log" {:id "283b4ec1-b7d6-999a-93e4-54b7b9b00f53", :name "log", :display-name "Log", :type :text},
    "microservice"
    {:id "3c006fda-0a98-01fe-856f-68a75e86fe27",
     :name "microservice",
     :display-name "Microservice",
     :type :dimension,
     :dimension [:field 5054 nil],
     :widget-type :category,
     :required true},
    "clustername"
    {:id "e3e2ed36-1d6d-8d3c-b1fa-47578b22ea68",
     :name "clustername",
     :display-name "Clustername",
     :type :dimension,
     :dimension [:field 5053 nil],
     :widget-type :category,
     :required true},
    "environment"
    {:id "fb04a463-41ce-9ccb-5e1c-20520f3ae194",
     :name "environment",
     :display-name "Environment",
     :type :dimension,
     :dimension [:field 5050 nil],
     :widget-type :category,
     :required true},
    "namespace"
    {:id "b6fc2d72-e2a3-5a3d-113f-a182a7410dc3",
     :name "namespace",
     :display-name "Namespace",
     :type :dimension,
     :dimension [:field 5057 nil],
     :widget-type :category,
     :required true},
    "loglevel"
    {:id "9633dbd8-d670-17ad-049b-879eb3ebb5f0",
     :name "loglevel",
     :display-name "Loglevel",
     :type :dimension,
     :dimension [:field 5101 nil],
     :widget-type :category,
     :default nil},
    "organization"
    {:id "8045ceae-7b28-0611-6e69-ed7cfa7c3d71",
     :name "organization",
     :display-name "Organization",
     :type :dimension,
     :dimension [:field 5052 nil],
     :widget-type :category,
     :required true},
    "projectcode"
    {:id "71b2f318-d0b8-1e48-75fe-4df05627e7b7",
     :name "projectcode",
     :display-name "Projectcode",
     :type :dimension,
     :dimension [:field 5051 nil],
     :widget-type :category,
     :required true}}},
  :database 2,
  :parameters [{:type "date/all-options", :target ["dimension" ["template-tag" "datefilter"]], :value "past0days~"}],
  :async? true,
  :cache-ttl nil},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> driver.common.parameters.values$missing_required_param_exception.invokeStatic(values.clj:97)"
  "driver.common.parameters.values$missing_required_param_exception.invoke(values.clj:96)"
  "driver.common.parameters.values$fn__77490$default_value_for_field_filter__77495$fn__77496.invoke(values.clj:105)"
  "driver.common.parameters.values$fn__77490$default_value_for_field_filter__77495.invoke(values.clj:101)"
  "driver.common.parameters.values$fn__77542$parse_tag__77535__77547$fn__77551.invoke(values.clj:128)"
  "driver.common.parameters.values$fn__77542$parse_tag__77535__77547.invoke(values.clj:115)"
  "driver.common.parameters.values$fn__77861$value_for_tag__77866$fn__77867.invoke(values.clj:311)"
  "driver.common.parameters.values$fn__77861$value_for_tag__77866.invoke(values.clj:306)"
  "driver.common.parameters.values$fn__77885$query__GT_params_map__77890$fn__77894$iter__77896__77900$fn__77901.invoke(values.clj:328)"
  "driver.common.parameters.values$fn__77885$query__GT_params_map__77890$fn__77894.invoke(values.clj:327)"
  "driver.common.parameters.values$fn__77885$query__GT_params_map__77890.invoke(values.clj:318)"
  "driver.sql$fn__79749.invokeStatic(sql.clj:44)"
  "driver.sql$fn__79749.invoke(sql.clj:40)"
  "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
  "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)"
  "query_processor.middleware.parameters$expand_all$replace_47337__47338.invoke(parameters.clj:59)"
  "mbql.util.match$replace_in_collection$iter__17987__17991$fn__17992.invoke(match.clj:139)"
  "mbql.util.match$replace_in_collection.invokeStatic(match.clj:138)"
  "mbql.util.match$replace_in_collection.invoke(match.clj:133)"
  "query_processor.middleware.parameters$expand_all$replace_47337__47338.invoke(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)"
  "query_processor.middleware.parameters$fn__47353$substitute_parameters_STAR___47358$fn__47359.invoke(parameters.clj:82)"
  "query_processor.middleware.parameters$fn__47353$substitute_parameters_STAR___47358.invoke(parameters.clj:79)"
  "query_processor.middleware.parameters$substitute_parameters$fn__47379.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45647.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__46268.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44393.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48371.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47582$fn__47586.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47582.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46508.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__48380$fn__48381.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__48380.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__48425.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__46643.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44239.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48356.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__405.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__47468.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45829.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___37687$thunk__37688.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___37687$fn__37690.invoke(reducible.clj:108)"],
 :context :question,
 :error "You'll need to pick a value for 'Microservice' before this query can run.",
 :row_count 0,
 :running_time 0,
 :ex-data {:type :missing-required-parameter},
 :data {:rows [], :cols []}}

**To Reproduce**
1. Create a dashboard
2. Add a table question into the dashboard with filter
3. Click on some filter to choose from the dropdown
4. De-select some filter or change the filter
5. The page suddenly refresh and show a crying emoji

**Expected behavior**
Suppose after choosing the filter, then the table dashboard will display the result base on the filter

**Screenshots**
![image](https://user-images.githubusercontent.com/73676188/115202071-94137900-a128-11eb-91a0-e4ba59a153ca.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 90.0.4430.72, Microsoft Edge 88.0.705.63
- Your operating system: Linux 3.10.0-1127.19.1.el7.x86_64
- Your databases: MySQL
- Metabase version: v0.39.0-SNAPSHOT
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
This bug doesn't happen all the time, and we are not sure how we can reproduce it as it seems to happen in random condition for user. However, it is making the use case not user-friendly, and we are not sure how to debug this issue. Thank you
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Hi @Theo-Lo 
Please post "Diagnostic Info" from Admin > Troubleshooting, since I don't know which commit you're using of `v0.39.0-SNAPSHOT`
It sounds like you're using a build that is more than 1 month old, since it should now produce a warning popup #15154

**Comment by Theo-Lo** [comment]
Hi @flamber 
Below is the info. I have git clone the project more than 1 month ago. So I think the metabase I am using doesn't have the warning popup
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "3.10.0-1127.19.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "presto"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.21"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-06",
      "tag": "v0.39.0-SNAPSHOT",
      "branch": "master",
      "hash": "?"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}

**Comment by flamber** [comment]
@Theo-Lo Okay, I cannot see which commit you have based it on, but the `master` branch was quite unstable at the time, so I would guess it's likely fixed if you upgraded to latest `release-x.39.x` branch.

**Comment by Theo-Lo** [comment]
@flamber I see, thank you for the advice, I will take a look in this direction.
