### ISSUE TITLE
Remove 2000 rows limit when pivoting a table

### ISSUE THREAD

**Issue by marcoruggine** [metabase/metabase#15672]
Hi, even if I'm running v.38.4, since Pivots are not enabled for BigQuery yet I'm stuck with the normal toggle that pivots 3 columns of a table. 

Unfortunately this feature has always had a problem connected to the # of rows shown in the table (2000), in fact, the pivot will show data only based on these 2000 rows and not all the dataset.

In my screenshot, I'm trying to pivot by 12 months but it truncates to the first 3 because, ordering by month asc, the last row is in June.

Is this something you could fix? Also, is there any update on Pivots in BigQuery? They are an essential tool. 

Thanks!
<img width="724" alt="Screenshot 2021-04-19 at 17 15 21" src="https://user-images.githubusercontent.com/20041428/115261405-e1491800-a133-11eb-85b5-e4e030eae482.png">

**Comment by flamber** [comment]
Hi @marcoruggine 
There's currently no update on Pivot Table functionality for BigQuery.
If you aggregate the results, then it returns 10,000 rows.
Closing in favor of #15008 (and #4564).

**Comment by marcoruggine** [comment]
Thanks for the quick reply. Is there any way to remove the 10k limit? Apparently it's not enough. Thanks!

**Comment by flamber** [comment]
Currently no - that's why I referenced #4564
