### ISSUE TITLE
Metabase v0.38.2 hangs out on specific snowflake warehouse

### ISSUE THREAD

**Issue by adlymousa** [metabase/metabase#15673]
Hi everyone,

I am getting the log below when connecting to snowflake. When changing the warehouse it get's running for sometime then stuck again .. any idea about the reason of this?

`{:database_id 11,
 :started_at #t "2021-04-19T14:57:13.052478Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__77755.invoke(execute.clj:393)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:390)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:375)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:384)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:375)"
    "driver.sql_jdbc$fn__79191.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__79191.invoke(sql_jdbc.clj:52)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46455.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__45707.invoke(check_features.clj:41)"
    "query_processor.middleware.limit$limit$fn__46441.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__45365.invoke(cache.clj:211)"
    "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46620.invoke(optimize_datetime_filters.clj:133)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44511.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40828.invoke(wrap_value_literals.clj:147)"
    "query_processor.middleware.annotate$add_column_info$fn__40691.invoke(annotate.clj:582)"
    "query_processor.middleware.permissions$check_query_permissions$fn__45582.invoke(permissions.clj:75)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47143.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45780.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47456.invoke(resolve_joined_fields.clj:94)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__47761.invoke(resolve_joins.clj:178)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44105.invoke(add_implicit_joins.clj:181)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__46416.invoke(large_int_id.clj:44)"
    "query_processor.middleware.format_rows$format_rows$fn__46396.invoke(format_rows.clj:74)"
    "query_processor.middleware.desugar$desugar$fn__45846.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__44871.invoke(binning.clj:228)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45389.invoke(resolve_fields.clj:24)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__43735.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43966.invoke(add_implicit_clauses.clj:146)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48191.invoke(upgrade_field_literals.clj:45)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44258.invoke(add_source_metadata.clj:122)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47340.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44458.invoke(auto_bucket_datetimes.clj:139)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45436.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__47125.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45488.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__46102.invoke(expand_macros.clj:155)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44267.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48127.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351$fn__47355.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46342.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__48136$fn__48137.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__48136.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__48198.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__46468.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44123.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48112.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__45723.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__47214.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45666.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___37431$thunk__37432.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___37431$fn__37434.invoke(reducible.clj:108)"],
   :error_type :driver,
   :ex-data
   {:sql
    "-- Metabase:: userID: 30 queryType: native queryHash: 9280dd3f28ed48bc1a2de5a5f59aad5fc6a9d7e1b5b019b352dd636ba3cb944e\nselect\n    corr(Marketing_spend, Users_sent_first_task) as \"to First Real Sent Task Users\"\n    ,corr(Marketing_spend, (Marketing_spend/ Users_sent_first_task) ) as \"to Cost per First Time User\"\n    ,corr(Marketing_spend, Real_sent_first_tasks_pct) as \"to Real Sent Tasks Pct\"\nfrom \n    \nwhere \n    datediff(day, day_id, getdate()) <= 14",
    :params nil,
    :type :driver}}],
 :state "22012",
 :error_type :driver,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :native,
  :middleware {:js-int-to-string? true},
  :native
  {:query
   'query goes here'
   :template-tags {}},
  :database 11,
  :parameters [],
  :async? true,
  :cache-ttl nil},
 :status :failed,
 :class net.snowflake.client.jdbc.SnowflakeSQLException,
 :stacktrace
 ["net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:124)"
  "net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:64)"
  "net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:434)"
  "net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:338)"
  "net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:501)"
  "net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:229)"
  "net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:167)"
  "net.snowflake.client.core.SFStatement.execute(SFStatement.java:749)"
  "net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:245)"
  "net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:117)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
  "--> driver.sql_jdbc.execute$fn__77676.invokeStatic(execute.clj:265)"
  "driver.sql_jdbc.execute$fn__77676.invoke(execute.clj:263)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__77755.invoke(execute.clj:391)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:390)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:375)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:384)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:375)"
  "driver.sql_jdbc$fn__79191.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__79191.invoke(sql_jdbc.clj:52)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46455.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__45707.invoke(check_features.clj:41)"
  "query_processor.middleware.limit$limit$fn__46441.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__45365.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46620.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44511.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40828.invoke(wrap_value_literals.clj:147)"
  "query_processor.middleware.annotate$add_column_info$fn__40691.invoke(annotate.clj:582)"
  "query_processor.middleware.permissions$check_query_permissions$fn__45582.invoke(permissions.clj:75)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47143.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45780.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47456.invoke(resolve_joined_fields.clj:94)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__47761.invoke(resolve_joins.clj:178)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44105.invoke(add_implicit_joins.clj:181)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__46416.invoke(large_int_id.clj:44)"
  "query_processor.middleware.format_rows$format_rows$fn__46396.invoke(format_rows.clj:74)"
  "query_processor.middleware.desugar$desugar$fn__45846.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__44871.invoke(binning.clj:228)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__45389.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__43735.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43966.invoke(add_implicit_clauses.clj:146)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48191.invoke(upgrade_field_literals.clj:45)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44258.invoke(add_source_metadata.clj:122)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47340.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44458.invoke(auto_bucket_datetimes.clj:139)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45436.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__47125.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45488.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__46102.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44267.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48127.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351$fn__47355.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46342.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__48136$fn__48137.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__48136.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__48198.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__46468.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44123.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48112.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__45723.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__47214.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45666.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___37431$thunk__37432.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___37431$fn__37434.invoke(reducible.clj:108)"],
 :context :question,
 :error "Division by zero",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}`

**Comment by flamber** [comment]
Hi @adlymousa 

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Include "Diagnostic Info" from Admin > Troubleshooting.

Try 0.38.4 - the stacktrace you're showing errors with `Division by zero`, so that seems like a legitimate error.

When you say it "hangs" - what does that mean - does the query not execute on the warehouse (please check the query log) or is the problem that you see a spinner in Metabase? If spinner, then an upgrade might fix that, since there was problems in some of the 0.38.x with displaying the query error, so it would just continue to show the spinner.
