### ISSUE TITLE
charting types aren't really meant to be used directly against a raw data grid directly from a given table.

### ISSUE THREAD

**Issue by malditojavi** [metabase/metabase#1567]
Line chart not loading in Mac client even if data is present in other view modes.
![](http://g.recordit.co/s70s16SlZR.gif)

http://recordit.co/s70s16SlZR
Never debugged a mac app, but if I can help somehow, tell me.

**Comment by agilliland** [comment]
Ahhh, so the underlying issue in this case is that the charting types aren't really meant to be used directly against a raw data grid directly from a given table.  It's assumed that you've narrowed your data down to only a couple of columns representing a via X and Y axis.

So for example if you changed your query from `Raw data` to `count` and then picked a column from the table as a grouping (typically a Date/Time field for line charts) then that should work for you.

We could be doing a bit more from a UX standpoint to make it clear that this particular usage pattern isn't designed to work thought.  @mazameli @kdoh

**Comment by agilliland** [comment]
closing this in favor of #2183 which is the same issue.
