### ISSUE TITLE
on 0.39.0 dashboard filters no longer allow multiple selections 

### ISSUE THREAD

**Issue by domparry** [metabase/metabase#15689]
**Describe the bug**
On 0.38.4, we have been able to select multiple values to filter a dashboard on for a text field. After upgrading to 0.39.0, we are only able to select 1 value at a time. New selections replace the previous filter.

**Logs**

**To Reproduce**
1. Create a Dashboard with some visualisations on it
2. Add a dashboard filter for a text field
3. Try to filter for multiple values.

**Expected behavior**
I should be able to filter on multiple values as I could in 0.38.4

**Comment by domparry** [comment]
Rolling back doesn't work, as the old version now prints an error in the UI: ```column metabase_field.special_type does not exist Position: 123```

**Comment by rlotun** [comment]
This should now be fixed in 0.39.0.1
