### ISSUE TITLE
Question not working in Pulse ou send by Dashboard 

### ISSUE THREAD

**Issue by philippe-opendsi** [metabase/metabase#15690]
Hi,

We made a question using two custom expression 
SumIf([llx_facturedet → total_ht], between([Date de facture], "2020-01-01", "2020-12-31"))
who works well alone and in a dashboard.
We are trying to send the Dashboard with a subscription. But it fails. If we remove this question, it works...

**Logs**
When trying to send the Dashboard
GET /api/pulse/preview_card_info/48 500 381,9 ms (14 appels de DB) 
{:via [{:type java.lang.ClassCastException}], :trace [], :message nil}

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_275-8u275-b01-1~deb9u1-b01",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_275",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.275-b01",
    "os.name": "Linux",
    "os.version": "4.15.18-12-pve",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.17-MariaDB-1:10.4.17+maria~stretch"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.0",
      "date": "2021-04-19",
      "branch": "release-x.39.x",
      "hash": "5e40366"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
Hi @philippe-opendsi 
I cannot reproduce. Can you please provide the full stacktrace - and even better if you can reproduce with static SQL.
