### ISSUE TITLE
created new questions (pivot table) and metabase stopped working

### ISSUE THREAD

**Issue by Eden1getstuff** [metabase/metabase#15697]
We created 6 new charts, from pivot table visualisation type, added them to a dashboard and everything in Metabase crashed. We can't see any data points.

UPDATE: After debugging, I am getting ERROR: column metabase_field.special_type does not exist Position: 123 when requesting  https://metabase_dns/api/card/{id}/query

![Screen Shot 2021-04-20 at 18 42 34](https://user-images.githubusercontent.com/82894833/115425296-2d658c80-a208-11eb-93a6-91be25a465a8.png)
![Screen Shot 2021-04-20 at 18 42 53](https://user-images.githubusercontent.com/82894833/115425355-38202180-a208-11eb-8654-024ded873852.png)

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.225-169.362.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "mongo",
      "snowflake"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.15"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-17",
      "tag": "v0.38.2",
      "branch": "release-x.38.x",
      "hash": "91f0ed6"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

**Comment by flamber** [comment]
Hi @Eden1getstuff 
Please check the logs for any errors - Admin > Troubleshooting > Logs.

**Comment by Eden1getstuff** [comment]
@flamber , attaching the logs. 

[83741c73-511b-453c-84a1-18cd1d9102d5] 2021-04-20T18:25:45+03:00 ERROR metabase.server.middleware.log GET /api/dashboard/122 500 577.6 ms (29 DB calls) 
{:via
 [{:type org.postgresql.util.PSQLException,
   :message "ERROR: column metabase_field.special_type does not exist\n  Position: 123",
   :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2553]}],
 :trace
 [[org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2553]
  [org.postgresql.core.v3.QueryExecutorImpl processResults "QueryExecutorImpl.java" 2285]
  [org.postgresql.core.v3.QueryExecutorImpl execute "QueryExecutorImpl.java" 323]
  [org.postgresql.jdbc.PgStatement executeInternal "PgStatement.java" 473]
  [org.postgresql.jdbc.PgStatement execute "PgStatement.java" 393]
  [org.postgresql.jdbc.PgPreparedStatement executeWithFlags "PgPreparedStatement.java" 164]
  [org.postgresql.jdbc.PgPreparedStatement executeQuery "PgPreparedStatement.java" 114]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeQuery "NewProxyPreparedStatement.java" 431]
  [clojure.java.jdbc$execute_query_with_params invokeStatic "jdbc.clj" 1090]
  [clojure.java.jdbc$execute_query_with_params invoke "jdbc.clj" 1084]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invokeStatic "jdbc.clj" 1113]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invoke "jdbc.clj" 1093]
  [clojure.java.jdbc$query invokeStatic "jdbc.clj" 1182]
  [clojure.java.jdbc$query invoke "jdbc.clj" 1144]
  [toucan.db$query invokeStatic "db.clj" 288]
  [toucan.db$query doInvoke "db.clj" 284]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [toucan.db$simple_select invokeStatic "db.clj" 394]
  [toucan.db$simple_select invoke "db.clj" 383]
  [toucan.db$select invokeStatic "db.clj" 662]
  [toucan.db$select doInvoke "db.clj" 656]
  [clojure.lang.RestFn invoke "RestFn.java" 439]
  [metabase.models.params$fn__33923$param_field_ids__GT_fields__33928$fn__33929 invoke "params.clj" 153]
  [metabase.models.params$fn__33923$param_field_ids__GT_fields__33928 invoke "params.clj" 147]
  [metabase.models.params$fn__34047 invokeStatic "params.clj" 215]
  [metabase.models.params$fn__34047 invoke "params.clj" 214]
  [clojure.lang.MultiFn invoke "MultiFn.java" 229]
  [clojure.lang.Var invoke "Var.java" 384]
  [toucan.hydrate$simple_hydrate$iter__33759__33763$fn__33764 invoke "hydrate.clj" 262]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.LazySeq first "LazySeq.java" 73]
  [clojure.lang.RT first "RT.java" 692]
  [clojure.core$first__5384 invokeStatic "core.clj" 55]
  [clojure.core$first__5384 invoke "core.clj" 55]
  [toucan.hydrate$hydrate invokeStatic "hydrate.clj" 433]
  [toucan.hydrate$hydrate doInvoke "hydrate.clj" 343]
  [clojure.lang.RestFn invoke "RestFn.java" 464]
  [metabase.api.dashboard$get_dashboard invokeStatic "dashboard.clj" 211]
  [metabase.api.dashboard$get_dashboard invoke "dashboard.clj" 206]
  [metabase.api.dashboard$fn__58897 invokeStatic "dashboard.clj" 252]
  [metabase.api.dashboard$fn__58897 invoke "dashboard.clj" 249]
  [compojure.core$wrap_response$fn__1993 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1977 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1982 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 151]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__73874 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [metabase.api.routes$fn__73995$fn__73997 invoke "routes.clj" 69]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.server.routes$fn__76228$fn__76229 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [metabase.server.routes$fn__76216$fn__76218 invoke "routes.clj" 41]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73986 invoke "exceptions.clj" 96]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__73983 invoke "exceptions.clj" 84]
  [metabase.server.middleware.log$log_api_call$fn__76144$fn__76145 invoke "log.clj" 195]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__76144 invoke "log.clj" 189]
  [metabase.server.middleware.security$add_security_headers$fn__73949 invoke "security.clj" 142]
  [metabase.server.middleware.json$wrap_json_body$fn__75925 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__75943 invoke "json.clj" 98]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__76485 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__76501 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35084 invoke "misc.clj" 58]
  [metabase.server.middleware.session$bind_current_user$fn__41955$fn__41956 invoke "session.clj" 277]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 258]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 250]
  [metabase.server.middleware.session$bind_current_user$fn__41955 invoke "session.clj" 276]
  [metabase.server.middleware.session$wrap_current_user_info$fn__41942 invoke "session.clj" 236]
  [metabase.server.middleware.session$wrap_session_id$fn__41928 invoke "session.clj" 182]
  [metabase.server.middleware.auth$wrap_api_key$fn__73882 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__76405 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35067 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35092 invoke "misc.clj" 75]
  [ring.middleware.gzip$wrap_gzip$fn__76447 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35095 invoke "misc.clj" 92]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__76161 invoke "ssl.clj" 48]
  [metabase.server$async_proxy_handler$fn__75758 invoke "server.clj" 71]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run nil -1]],
 :cause "ERROR: column metabase_field.special_type does not exist\n  Position: 123",
 :message "ERROR: column metabase_field.special_type does not exist\n  Position: 123",
 :type org.postgresql.util.PSQLException,
 :sql-exception-chain
 ["PSQLException:"
  "Message: ERROR: column metabase_field.special_type does not exist"
  "Position: 123"
  "SQLState: 42703"
  "Error Code: 0"]}

**Comment by flamber** [comment]
@Eden1getstuff That's because you have upgraded to 0.39 and then downgraded to an earlier version. Metabase does not support downgrading - you will have to revert to your backup, or manually rename the column `metabase_field.semantic_type` to `metabase_field.special_type` and then you would have to reverse that if you upgrade to 0.39 again.
