### ISSUE TITLE
How to get :token for api/embed/card/:token/query

### ISSUE THREAD

**Issue by LadyR123** [metabase/metabase#15696]
Hello, I want to use api/embed/card/:token/query

but i cant understand how to get :token
is it allowed for superadmin only?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://www.metabase.com/docs/latest/api-documentation.html#get-apiembedcardtokenquery
https://www.metabase.com/docs/latest/api-documentation.html#get-apisettingkey
