### ISSUE TITLE
Cannot select category Field Filter in Native query on 0.39.0

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15700]
**Describe the bug**
Cannot select category Field Filter in Native query on 0.39.0

**To Reproduce**
1. Native question > Sample Dataset > `{{filter}}` - as Field Filter of Product.Category - notice Filter Widget Type is "None"
![image](https://user-images.githubusercontent.com/1447303/115441095-c39db080-a210-11eb-9b6f-a49ba809724a.png)

**Information about your Metabase Installation:**
0.39.0

**Severity**
P0.5

**Comment by dpsutton** [comment]
I cannot reproduce. on the released 39 and i'm seeing 
<img width="339" alt="image" src="https://user-images.githubusercontent.com/6377293/115446993-9683da80-a1dd-11eb-915f-912bb8e9594b.png">

**Comment by flamber** [comment]
@dpsutton What is the operators-enabled configured to? On the release it's `null`

**Comment by dpsutton** [comment]
oh good point. sorry.

**Comment by dpsutton** [comment]
turning this off it doesn't even seem to recognize that there's a filter there for me:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/6377293/115447885-9cc68680-a1de-11eb-85a0-9c54cfc3ae19.png">

**Comment by flamber** [comment]
@dpsutton Refresh you browser - you're seeing 10927
