### ISSUE TITLE
Login background color always uses "Primary color" when there's a custom logo

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15712]
**Describe the bug**
Currently the whitelabel "Primary color" is used as the background color on the login screen, when the logo is set, which can be a little overwhelming depending on the color.

**To Reproduce**
1. Admin > Settings > Whitelabel
2. Add a custom logo (it doesn't matter if "Primary color" is defined or just the default)
3. Go to login screen
![image](https://user-images.githubusercontent.com/1447303/115542628-c0520580-a2a0-11eb-82d2-0ce7db798c54.png)

**Expected behavior**
Having a background color option, which perhaps could also be used for embedding background (#9856).
Or make it use the "Navigation bar color" instead? Or alternatively just white background?

**Information about your Metabase Installation:**
Tested 1.35.4.1 thru 1.39.0

Originally EE488 https://github.com/metabase/metabase-enterprise/issues/488

**Comment by WiNloSt** [comment]
@flamber Maybe you could help me confirm if this is fixed. I didn't fix anything yet, but I couldn't reproduce this anymore I'm on the commit 4a84dd642af75be2fca82b7b49583aa41313dc40 (current `master` at the time).

### Test steps
1. Create a fresh enterprise instances (default H2)
2. Activate the license
3. Observe the login page
4. Add a logo
5. Observe the login page
6. Change primary color
7. Observe the login page

#### Login page without any settings changed
![Screen Shot 2022-05-03 at 1 32 37 PM](https://user-images.githubusercontent.com/1937582/166413360-9c1bd9f2-0e1c-4965-92a5-7681edc8c4b1.png)

#### Login page after adding a logo
![Screen Shot 2022-05-03 at 1 32 59 PM](https://user-images.githubusercontent.com/1937582/166413182-f5759e4d-8c67-475b-a2c0-a7ad6730eb9a.png)

#### Login page after changing the primary color
![Screen Shot 2022-05-03 at 1 33 13 PM](https://user-images.githubusercontent.com/1937582/166413212-e6d0598c-82a3-4278-8404-f5391200019a.png)

**Comment by flamber** [comment]
@WiNloSt Looks like a lot of things have changed in 42 and specially 43, so this is not a problem anymore.
