### ISSUE TITLE
Login logo is left-aligned on EE, when whitelabel features are enabled

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15713]
**Describe the bug**
Login logo is left-aligned on EE, when whitelabel features are enabled

**To Reproduce**
1. Enable token with whitelabel features - it doesn't matter if custom logo is used or just the default
2. Logout
![image](https://user-images.githubusercontent.com/1447303/115543926-3b67eb80-a2a2-11eb-921f-9567b9e51779.png)

**Expected behavior**
Logo should be centered.

**Information about your Metabase Installation:**
Regression since 1.37.0, when the login dialog was revamped - tested thru 1.39.0

**Comment by nemanjaglumac** [comment]
When whitelabel is turned on, `SVG` is wrappen in a span
![image](https://user-images.githubusercontent.com/31325167/115585379-d5905980-a2cb-11eb-9f84-129afd42b5e0.png)

`enterprise/frontend/src/metabase-enterprise/whitelabel/components/LogoIcon.jsx:122`

When it is turned off, it's using different component without `<span>` wrapper so it inherits the alignment from one of the parents (flex, column, align-items: center).

If we are ALWAYS using central alignment for the logo, I can fix this real quick.

**Comment by nemanjaglumac** [comment]
Fixed by #15755
