### ISSUE TITLE
Whitelabel favicon does not work correctly in all browsers

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15711]
**Describe the bug**
When trying to white label the favicon, it doesn't take effect.
Using a SVG favicon will work in Firefox, but not Chromium-based browsers.

**Workaround**
1. Use a reverse-proxy to hijack the request to `/app/assets/img/favicon.ico` and redirect it to your custom favicon location, or
2. Replace the favicon.ico in the JAR-file (which is just a ZIP archive, and the location is `frontend_client/app/assets/img/favicon.ico`)
Not recommended, since it's easy to do something wrong and this would have to be done on every upgrade.

**To Reproduce**
1. Go to Admin > Whitelabel > change Favicon, example `https://github.githubassets.com/favicons/favicon.png`
2. Refresh browser - remember to clear cache, since favicons are sometimes cached even in Incognito-mode.
3. Favicon is still the Metabase default, and looking at the source, it seems like there's several `icon` references to the default before the custom (pretty sure that HTML doesn't work the same way as CSS):
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <link rel="apple-touch-icon" sizes="180x180" href="/app/assets/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/app/assets/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/app/assets/img/favicon-16x16.png">
    <link rel="manifest" href="/app/assets/img/site.webmanifest">
    <link rel="mask-icon" href="/app/assets/img/safari-pinned-tab.svg" color="#62a8e6">
    <link rel="shortcut icon" href="/app/assets/img/favicon.ico">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="msapplication-config" content="/app/assets/img/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <meta name="apple-mobile-web-app-status-bar-style" content="default" />
    <meta name="base-href" content="/" />
    <meta name="uri" content="/auth/login" />

    <link rel="icon" href="https://github.githubassets.com/favicons/favicon.png" />
...
```
4. And clearing the custom favicon, will set it to `frontend_client/favicon.ico` (which is the placeholder), and looking at the source, this is now the favicon URL too, which errors with `404`.

**Expected behavior**
Show the custom favicon correctly in all browsers for all file types and don't have 404 references.

**Information about your Metabase Installation:**
Tested 1.34.3 thru 1.39.0

**Additional context**
Possibly need to adjust the text or documentation too, since it's easy to misunderstand that a relative path will not work, since Metabase will look inside of the JAR-file, so a reverse-proxy would be needed.

Previously EE439 https://github.com/metabase/metabase-enterprise/issues/439

**Comment by nemanjaglumac** [comment]
Fixed in https://github.com/metabase/metabase/pull/16022
