### ISSUE TITLE
Some columns become hidden from question when custom column is added to visible columns

### ISSUE THREAD

**Issue by nefremov** [metabase/metabase#15720]
**Describe the bug**
Some columns become hidden from question when custom column is added to visible columns

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

https://user-images.githubusercontent.com/16823097/115600734-ad155900-a2e5-11eb-92a8-2370e4869978.mp4

**Expected behavior**
Column visibility and order may be assigned via settings panel

**Screenshots**
6 similar errors in log e.g.
![log](https://user-images.githubusercontent.com/16823097/115601272-40e72500-a2e6-11eb-84ee-8d1e7e1acd3d.png)

**Browser logs**
[1619027128832.log](https://github.com/metabase/metabase/files/6353070/1619027128832.log)

**Information about your Metabase Installation:**
You're on version v1.39.0.1
Built on 2021-04-20
Branch: release-x.39.x
Hash: 47bb5f2

- Your browser and the version:90.0.4430.72 (Official Build) (64-bit)
- Your operating system:  Windows 10

**Comment by flamber** [comment]
Hi @nefremov 
I cannot reproduce. It looks like you already had done several steps before recording the video.
It would be very helpful if you can reproduce with included Sample Dataset.
