### ISSUE TITLE
Strange slugs chosen for database column names

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#15726]
- Using Metabase 0.39.0.1 on MacOS 11.2.3 (Big Sur) with Apple Silicon
- SQLite database in <https://github.com/gvwilson/toronto-covid-analysis>, filename `toronto-covid19.db`
- UI names `covid` table `Cov ID`
![Screen Shot 2021-04-21 at 9 51 31 AM](https://user-images.githubusercontent.com/911566/115613145-0e273780-a2ba-11eb-9152-f6fe0c30ce34.png)
- UI names `intubated_current` column `I Ntu Bated Current`
![Screen Shot 2021-04-21 at 9 51 42 AM](https://user-images.githubusercontent.com/911566/115613214-21d29e00-a2ba-11eb-8e5f-aaed66ea1b90.png)

**Comment by paoliniluis** [comment]
This is the one (sorry for the name of the issue!) https://github.com/metabase/metabase/issues/7606
