### ISSUE TITLE
Contenteditable field can sometimes lose value

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15734]
**Describe the bug**
Contenteditable field (used for custom columns, for example) could sometimes lose value due to the popover flickering. It seems that the issue was fixed most probably in #15608 (on `release-x.39.x` branch). It can still be reproduced on `master` at 43eff56.

**Logs**
N/A

**To Reproduce**
1. Open orders table from a custom question
2. Click on the small grid icon to create custom column
3. Modal will appear and "Field formula" is `contenteditable` field
4. Type `1+1` (without spaces) as a field formula
5. Click on the description field (notice `1+1` got formatted as `1 + 1`) and type "Math" as description
6. Click the field formula field again
    - Depending on  where you clicked*, value might already be gone
    - The moment field value is gone, description also disappears

*Possible options/behavior that results in the field getting reset/erased
1. Click at the very beginning of the field (before the first `1 +...`)
2. Click at the very end of the formula and press left arrow key
3. Click somewhere in the formula (sometimes it can even be the beginning if that doesn't immediately erase the value) and press right arrow key a couple of times

**Expected behavior**
Unless someone explicitly deletes (select all + backspace) the whole formula, navigating with arrows and/or clicking anywhere within contenteditable field shouldn't delete the formula.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/kpuK4xeR/629bf391-0021-4db5-81d6-b38dc135f99e.gif?source=viewer&v=aa4585937325ce00004e3b9b1bc19852)

**Information about your Metabase Installation:**
- Local dev, master, commit 43eff56 

**Severity**
Pretty annoying and undesirable. Imagine typing very long, meticulously crafted custom expression formula only to see it disappear without any reason. P2, I guess. 

**Additional context**
Merging https://github.com/metabase/metabase/pull/15721 will fix this on `master`

**Comment by nemanjaglumac** [comment]
One thing that will NOT be fixed even with the newest changes is as follows:

1. Formula: `1 + 1`
2. Name: "Math"
3. Go back to the formula and delete the last digit `1` leaving the field as `1 + `
4. Click the name again (let's say you wanted to edit a typo or something)
5. Note that formula got erased together with the name of the CC

![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/v1ubgv89/7e38f270-7c36-4652-a871-f3c04c35140f.gif?source=viewer&v=f5bbcae60b23d072c237a0dc7d4b8985)

**Comment by nemanjaglumac** [comment]
Third scenario (also not going to be fixed with the newest changes):

1. Type in perfectly valid formula
2. Type in the name
3. Note that "Done" button is enabled and all is good, but don't yet click the button
4. Resize the window or open the dev tools
5. All your changes are now gone

![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/qGuE7wk1/babc991e-3429-4b23-9753-7b5d0ac065e3.gif?source=viewer&v=17e697a509ce20d8663a64679d6fb191)

**Comment by nemanjaglumac** [comment]
It feels weird that this issue is closed with a lot of the cases where the field still loses value are not solved. That was probably my mistake and I should've opened a separate issue for each of the cases.

In any way, @gusaiani please make sure all related repros are unskipped when you fix the rest of the issues in https://github.com/metabase/metabase/pull/16121 and please let me know if you need any help with that.

**Comment by gusaiani** [comment]
Thanks @nemanjaglumac, agreed.

Issues created:

https://github.com/metabase/metabase/issues/16126
https://github.com/metabase/metabase/issues/16127
