### ISSUE TITLE
Date format downloaded xls does not respect the date format when chose to show minutes

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#15742]
Metabase 0.36.12
Date format downloaded **excel** does not respect the date format when chose to show minutes.
For example: for 24 September 2020, with format configuration is D/M/YYYY
, in the downloaded excel shows:
 for a date "with minutes" it change to M/D/YYYY ![image](https://user-images.githubusercontent.com/33416503/114665114-ea358600-9cfc-11eb-80b4-c1329a1a7bd2.png)

, but for date (just day) is ok ![image](https://user-images.githubusercontent.com/33416503/114665014-c83c0380-9cfc-11eb-8879-4e509924c7e5.png)

**Comment by flamber** [comment]
@jlisyc Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Latest release is 0.39.0.1: https://github.com/metabase/metabase/releases/latest
