### ISSUE TITLE
Custom Expression filter is showing a reference to the field id

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15748]
**Describe the bug**
When using custom expression for a question filter, it shows field id reference instead of a field name.

**Logs**
N/A

**To Reproduce**
1. New question > Custom > Sample Dataset > Orders
2. Add filter > Custom expression
3. `[Total] < [Subtotal]`, click Done
4. Filter shows "Total is less than field,14,"
5. Click on that filter, it doesn't open custom expression modal again (but I think we already have an issue for that)
6. Even in new modal you can still see "field,14,"

**Expected behavior**
- Filters should reference fields by name

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/115734472-05059b80-a38a-11eb-8c67-ee35e03f7f1e.png)

**Information about your Metabase Installation:**
- local dev, `release-x.39.x`, H2

**Severity**
Seems to be UI/frontend thing only, P3. The query _seems_ to be correct at this stage. Not sure if it has any further implications.

**Additional context**
When you delete `field,14,` value it shows that the filter type is "Number", so I am not sure how did it even work with the string.
![image](https://user-images.githubusercontent.com/31325167/115735290-a856b080-a38a-11eb-9a5e-757acf001f6e.png)

### 0.38.4, 0.37.0, 0.36.0 (it seems this goes back long time)
![image](https://user-images.githubusercontent.com/31325167/115735701-f966a480-a38a-11eb-8af2-6d5465137fea.png)

**Comment by flamber** [comment]
Very related to #14726 and #12492

**Comment by flamber** [comment]
https://github.com/metabase/metabase/pull/16174#issuecomment-848020964
