### ISSUE TITLE
Hundreds of Emails: We've noticed a new login on your Metabase account.

### ISSUE THREAD

**Issue by GabeBigBoxVR** [metabase/metabase#15740]
**Describe the bug**
Hello! We use a machine account to login to Metabase and run queries from a spreadsheet, however it logs in a lot and we're getting spammed hundreds of emails with this message:

We've noticed a new login on your Metabase account.

**Logs**
N/A

**To Reproduce**
1. Submit login to https://metabase.bigboxvr.com/api/session with a rest endpoint

![image](https://user-images.githubusercontent.com/22383358/115643569-daf0a280-a2d1-11eb-85b2-bda8dc6bce55.png)

**Expected behavior**
Allow the user to login, but don't send an email for REST API logins or create a setting that allows certain accounts to disable the email on login.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
Metabase Version: v0.39.0.1

**Severity**
Very severe, sending thousands of emails an hour

**Additional context**

**Comment by flamber** [comment]
Hi @GabeBigBoxVR 
Start Metabase with this environment variable set `MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE=FALSE`

**Comment by GabeBigBoxVR** [comment]
That worked, thanks.
