### ISSUE TITLE
Number started with decimal dot (.) is not recognized in custom expression

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#15741]
1. Ask a question, Custom question
2. Sample Dataset, Orders table
3. Custom column, enter `.5 * [Discount]`

![image](https://user-images.githubusercontent.com/7288/115647490-bb10ad00-a2d8-11eb-9695-fe5a2521ba34.png)

**Expected behavior**

`.5` is recognized as a number, just like `0.5`.

**Comment by nemanjaglumac** [comment]
@ariya will you cover this with (unit) test? Or do you want me to create e2e?

**Comment by ariya** [comment]
> @ariya will you cover this with (unit) test? Or do you want me to create e2e?

Would be nice to have an E2E repro/test for this. Thank you @nemanjaglumac!
