### ISSUE TITLE
Dashboard subscription email is missing text boxes of a dashboard

### ISSUE THREAD

**Issue by mtthsbrr** [metabase/metabase#15744]
**Describe the bug**
When sending an email with the dashboard subscription feature, the text box in that dashboard are not in that email.

**Logs**
n/a

**To Reproduce**
1. Go to 'New dashboard' and create one
2. Click on 'Edit dashboard' and 'Add a text box' then 'Add question' (latter is needed because of https://github.com/metabase/metabase/issues/15077) and save the dashboard
3. Click on 'Share dashboard' -> 'Dashboard subscription' and configure the 'Email it' part
4. Click 'Send email now'
5. See only the question showing up in that email but not the text box

**Expected behavior**
Text boxes of a dashboard are present in dashboard subscription emails.

**Screenshots**
Dashboard:
![image](https://user-images.githubusercontent.com/49281986/115683379-abd04480-a356-11eb-9023-78dc4797a79e.png)

Email:
![image](https://user-images.githubusercontent.com/49281986/115683817-1bdeca80-a357-11eb-958c-140a41827fee.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
- Your operating system: Windows 10.20H2
- Your databases: Postgres, ...
- Metabase version: v0.38.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
I would like to add some context to a dashboard when sending it to stakeholders. So it's annoying that people now have to visit the dashboard to actually see and be aware of that context.

**Additional context**
n/a

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
This is essentially the same as #3315

**Comment by mtthsbrr** [comment]
> This is essentially the same as #3315

Partially agreed @flamber. Except that if I subscribe to a dashboard I would expect the subscription email containing everything that's in the dashboard. So for me it's not a new feature because I can already add text boxes to a dashboard.

**Comment by pawit-metabase** [comment]
Looks like this is already fixed by #17781 but the issue wasn't linked.

**Comment by rlotun** [comment]
@noahmoss can you unskip the repro too? thanks!

**Comment by noahmoss** [comment]
Oops, totally forgot this issue existed. Unskipping the repro in #18110.
