### ISSUE TITLE
Issue on building docker image

### ISSUE THREAD

**Issue by ziozec** [metabase/metabase#15752]
Ciao,
I'm generating docker image from source 0.39 but during the build I receive this error:

> [0m[91mDownloading: org/clojure/data.codec/0.1.0/data.codec-0.1.0.jar from central
> [0m[91mDownloading: com/hypirion/io/0.3.1/io-0.3.1.jar from clojars
> [0m[31mStep failed: No matching clause: [0m
> {:via
> [{:type java.lang.IllegalArgumentException,
> :message "No matching clause: ",
> :at [build$edition_from_env_var invokeStatic "build.clj" 11]}],
> :trace
> [[build$edition_from_env_var invokeStatic "build.clj" 11]

Debugging a bit it's on 
Step 24/34 : RUN INTERACTIVE=false MB_EDITION=$MB_EDITION bin/build

Do you know where the issue is? 
Where do I find build.clj file?

Thanks,
Fabio

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by paoliniluis** [comment]
Ciao Fabio, you need to pass a --build-arg MB_EDITION=oss or ee argument on your build, please check the developer documentation for this.
