### ISSUE TITLE
Cannot Clear Metadata Column Details

### ISSUE THREAD

**Issue by djbusby** [metabase/metabase#1575]
When adjusting the Metadata of a database special types can be selected in 'Details'.  If for example one assigns the type to 'Timestamp (seconds)' but then discovers that was incorrect - there is no way to clear this association of Timestamp without selecting a different type.  In this case the correct type would be DateTime String (ISO) but that type doesn't exist so now I'm stuck with the wrong type selected in Details.

**Comment by agilliland** [comment]
Yeah, that's an oversight.  It's not required to pick a special type for a column, so that should be something that can be cleared.
