### ISSUE TITLE
Can't use parentheses as expected in filter expressions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15754]
This was in both `master` and in the 0.39.0.1 jar.

I was trying to create a simple (if goofy) custom filter expression in the notebook which used parentheses to clarify the order in which I wanted the different logical bits to be evaluated. But I hit an error message: `Expected closing parenthesis but found  'OR'`

![image](https://user-images.githubusercontent.com/2223916/115759898-a0304e00-a355-11eb-8990-f1b7e343856a.png)

Here's the expression: `([ID] > 2 OR [Subtotal] = 100) and [Tax] < 4`

My assumption is that parentheses are pretty vital for cases like this, and I validated with @ariya that this is a valid expression that MB should accept.

**Comment by ariya** [comment]
This is fixed with PR #15802.
