### ISSUE TITLE
Fix Serialization P1s

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15756]
Refactoring the serialization code pursuant to fixing these is in scope (target is `39.x` for as many fixes as possible, if there is any major rework required, that will go to 40):

First
- [x] #14914
- [x] #14912  
- [x] #14566

and then:
- [x] #15812
- [x] #15120

stretch goals (not putting with checkboxes since they're stretch):
- #14909
- #15285 
- #15283
- #15051
- #14910
- #15848

**Comment by jeff303** [comment]
Consolidated PR created here: #15858
