### ISSUE TITLE
Add new search to data picker

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15766]
## **Context**

The data picker used to select tables in simple mode and the notebook has never had real search, only the ability to filter long lists of tables / schemas once you've selected a database.

## **Why**

When you’re looking for the right table to start from it can be cumbersome to find what you're looking for, especially if you know the name but can't remember the db or schema where it lives. Adding search in context of this specific task should decrease the amount of effort it takes to find an item, and help users get on to the real work they’d like to do.

## Goals

- Incorporate search without altering the overall structure of the data picker. This is an old and complicated UI component with lots of technical debt and any major changes are likely to have cost associated with them.

## Spec

Add an  input to the top of the data picker list of "databases" that says "Search for a table..." This input will only be present at the top level database list.

![image](https://user-images.githubusercontent.com/1455846/115777158-ccee6080-a369-11eb-95d0-a84284073937.png)

As soon as the user types two or more characters we should use our search loader (to get our default loading and error handling) to make a request to the search endpoint and then present **only** tables or saved questions that are valid starting points as results for the term.

This search result list replaces the list of databases below the input.

![image](https://user-images.githubusercontent.com/1455846/115777194-d37cd800-a369-11eb-9cce-2238fe36cad6.png)

Result items should be shown with the database and schema name if applicable, or the collection name if it's a saved question. Clicking on an item should perform the same action as it would otherwise does now given the context of the picker (Think this should be obvious but want to spell it out to be sure)

- Simple mode → Use the selected item for a new bare rows question
- Notebook → Add the item as a selection for the source or any joined data

If there are no results we'll show a message to that effect.

![image](https://user-images.githubusercontent.com/1455846/115777213-d972b900-a369-11eb-9bd3-68cf9e73c78d.png)

The user can return to the top level database list by clearing out their search term via backspace or via a X icon on the right of the input.

Once a selection is made we should clear out any search state. (The current behavior when you reopen the popover after making a selection in the notebook should be maintained).

We should also remove the "Find..." filter input on the schema or table views in the picker.

**Comment by alxnddr** [comment]
Closed by #15738
