### ISSUE TITLE
Add Special Type: DateTime String (ISO)

### ISSUE THREAD

**Issue by djbusby** [metabase/metabase#1576]
UNIX Timestamp is very handy but it would be awesome to have a few formats supporting datetime strings:  Date, Time, DateTime.  I'm sure there are lots of silly date and time formatting options.  I imagine that support ISO formats only would be a good first step.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by agilliland** [comment]
So in this case you are saying that you have date/time information but it happens to be stored in string values of a varchar/text column instead of being a native DateTime type column for your db?

Can you provide a couple examples of the format your datetime information is stored in right now?

**Comment by camsaul** [comment]
@agilliland SQL DBs are usually pretty flexible with date strings. For example, all of these work in Postgres:
```sql
-- ISO 8601 
CAST('2015-11-30' AS TIMESTAMP),
CAST('2015-11-30T23:48' AS TIMESTAMP),
CAST('2015-11-30T23:48:05Z' AS TIMESTAMP),
CAST('2015-11-30T23:48:05.000Z' AS TIMESTAMP),

-- RFC 822
CAST('Mon Nov 30 2015' AS TIMESTAMP)
```

I'd assume @djbusby means [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) specifically (which works on every SQL DB we support AFAIK), but other formats like [RFC 822 (i.e., HTML)](http://www.w3.org/Protocols/rfc822/#z28) should work as well on most DBs.

Under the hood all we'd need to do is pretend the column is a `DateTimeField`. It would then go through the date bucketing code and get casted automatically.

**Comment by shtam** [comment]
Any update on the scheduling of this one? Our Redshift/Stitch combo automatically stores all dates/timestamps as strings.

**Comment by mysticaltech** [comment]
Also suffering from that issue, I am using Druid through Presto, and date fields are string. Even though I format them as YYYY-MM-DD they are not recognized as dates. Forcing column types would be amazing!

**Comment by flamber** [comment]
@mysticaltech Which other open issues, besides this and the two referenced above, would this fix?

**Comment by mysticaltech** [comment]
@flamber and @mazameli Thanks for considering this. I was referencing to the issues posted above and also a few posts on discourse. It seems that SQLite, Redshift, and Druid users are having similar issues with date-string columns.

Please see:
https://discourse.metabase.com/t/formatting-date-in-sql-native-query/8129
https://discourse.metabase.com/t/how-to-convert-text-field-with-date-yyyy-mm-dd-to-date-datatype/456
https://discourse.metabase.com/t/handling-date-timestamps-in-sqllite/7188/4
https://discourse.metabase.com/t/convert-date-stored-as-varchar-into-other-format/6495

**Comment by mysticaltech** [comment]
For instance, those 2 columns, I cannot use with the GUI to do filtering, spent my whole day, but SQL is a must, and trying to convince my colleague didn't go so well 😢
![Screen Shot 2020-10-14 at 6 42 30 PM](https://user-images.githubusercontent.com/518555/96019751-418d9300-0e4d-11eb-8b96-2ecfcd2deb3c.png)

**Comment by mysticaltech** [comment]
This solution below proposed by @camsaul 5 years ago seems really like a quick fix. 

Now how to identify those, my guess is just adding a checkbox in the Data Model config would be a clean way of doing it. "Consider as DateTime" check / uncheck.

> @agilliland SQL DBs are usually pretty flexible with date strings. For example, all of these work in Postgres:
> 
> ```sql
> -- ISO 8601 
> CAST('2015-11-30' AS TIMESTAMP),
> CAST('2015-11-30T23:48' AS TIMESTAMP),
> CAST('2015-11-30T23:48:05Z' AS TIMESTAMP),
> CAST('2015-11-30T23:48:05.000Z' AS TIMESTAMP),
> 
> -- RFC 822
> CAST('Mon Nov 30 2015' AS TIMESTAMP)
> ```
> 
> I'd assume @djbusby means [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) specifically (which works on every SQL DB we support AFAIK), but other formats like [RFC 822 (i.e., HTML)](http://www.w3.org/Protocols/rfc822/#z28) should work as well on most DBs.
> 
> Under the hood all we'd need to do is pretend the column is a `DateTimeField`. It would then go through the date bucketing code and get casted automatically.

**Comment by mysticaltech** [comment]
@flamber Just to finish my thought, basically, my colleague and I had a "fight" because he wants to move back to DataStudio due to that small limitation, and I want us to stick with Metabase. From the Metabase's perspective, I just think that it's a low hanging fruit that could help a lot of people, not just me. Anyway, thank you for considering it.

**Comment by sbelak** [comment]
Since we already support treating ostensibly numeric fields with the appropriate `:special_type` as `Temporal`s, we could do the same here. Doing so would mean we don't have to change anything in the UI -- setting the type in the existing Data Model would suffice.

**Comment by mysticaltech** [comment]
@sbelak ISO 8601 support in such a way would be fantastic 😍

> Since we already support treating ostensibly numeric fields with the appropriate `:special_type` as `Temporal`s, we could do the same here. Doing so would mean we don't have to change anything in the UI -- setting the type in the existing Data Model would suffice.

**Comment by djbusby** [comment]
Yea, I did mean ISO8601. But now I'd like to add RFC3339 too.

**Comment by mysticaltech** [comment]
Hey folks, I'm really new to closure but I think I've narrowed it down to:
- https://github.com/metabase/metabase/blob/master/src/metabase/sync/analyze/fingerprint/fingerprinters.clj
- https://github.com/metabase/metabase/blob/master/src/metabase/sync/analyze/classifiers/name.clj

And I guess this is the DateTime bucketing code that @camsaul was mentioning:
https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/auto_bucket_datetimes.clj

Last but not least, I don't think that file is involved but referencing it too just in case:
https://github.com/metabase/metabase/blob/master/src/metabase/models/table.clj

The most interesting I think is the fingerprinters.clj file, and there is a section, that seems very interesting:

```
(defprotocol ^:private ITemporalCoerceable
  "Protocol for converting objects in resultset to a `java.time` temporal type."
  (->temporal ^java.time.temporal.Temporal [this]
    "Coerce object to a `java.time` temporal type."))

(extend-protocol ITemporalCoerceable
  nil      (->temporal [_]    nil)
  String   (->temporal [this] (->temporal (u.date/parse this)))
  Long     (->temporal [this] (->temporal (t/instant this)))
  Integer  (->temporal [this] (->temporal (t/instant this)))
  ChronoLocalDateTime (->temporal [this] (.toInstant this (ZoneOffset/UTC)))
  ChronoZonedDateTime (->temporal [this] (.toInstant this))
  Temporal (->temporal [this] this))

(deffingerprinter :type/DateTime
  ((map ->temporal)
   (robust-fuse {:earliest earliest
                 :latest   latest})))
```

Especially this line caught my attention `String   (->temporal [this] (->temporal (u.date/parse this)))`. Any indication folks, I'm ready to write Clojure for the first time in my life and submit PRs. Please give me hints 🙏🏻

**Comment by mysticaltech** [comment]
What seems logical would be to write a classifier, am I correct @sbelak?

**Comment by mysticaltech** [comment]
On second thought, I am thinking:

1. Create a custom type in for String Datetime in the data model.
2. Write custom toucan queries, same as dates but with a cast from string to dates.

Does that make sense? Please help me figure this out.

_Otherwise, I read this https://www.metabase.com/support/sponsorship/, I am willing to try talk to my organization to buy credit hours to try to prioritize this more. I know you have tons of more pressing issues. I really believe that this should be a quick fix. @flamber how many credit for this bug fix and how much per credit?_

**Comment by mysticaltech** [comment]
Just found out about a huge PR that was merged about a year after this issue was opened. It's lays the ground work for this and explains a lot, and **DateTimeField** mentioned by @camsaul is now **type/datetime**. See #1955.

**Comment by mysticaltech** [comment]
There was a actual vision behind this, most was done but this remaining piece, see #2663 😢

![Screen Shot 2020-10-20 at 2 56 24 PM](https://user-images.githubusercontent.com/518555/96588905-7afa4e80-12e4-11eb-8a28-d9eab883e89f.png)

**Comment by mysticaltech** [comment]
@djbusby This seems to be the jackpot, one line in here could do it (hopefully I am not too naïve 🤞) [](https://github.com/metabase/metabase/blob/master/src/metabase/types.clj)
 
![Screen Shot 2020-10-20 at 3 16 06 PM](https://user-images.githubusercontent.com/518555/96591335-71beb100-12e7-11eb-96cb-d9807b9c686d.png)

**Comment by mysticaltech** [comment]
Last but not least, obviously **fields.clj** and **field_values.clj** must also play a big role here:

- https://github.com/metabase/metabase/blob/master/src/metabase/models/fields.clj
- https://github.com/metabase/metabase/blob/master/src/metabase/models/field_values.clj

**Comment by sbelak** [comment]
I don't think this should be a new type. Our types are mostly concerned with semantics not how something was stored. Like I said above, I'm pretty sure we already do most of the correct castings of strings (or can be added where needed like `ITemporalCoerceable`), the biggest limitation is that we dispatch mostly on `:base_type` which in this case is `:type/Text`. The fix should be some combination of a) special casing the `:type/Text` `:base_type' + `:type/Temporal` `:special_type` and/or translate the types correctly in the first place (if they are distinguishable on the DB level) in the driver code.

**Comment by mysticaltech** [comment]
Ok, that clarifies things! So that needs to happen at the driver level, in my case https://github.com/metabase/metabase/blob/master/modules/drivers/presto/src/metabase/driver/presto.clj. In it we can see interesting code like so:

```
(defn- field-type->parser [field-type]
  (letfn [(parse-temporal [s]
            (u.date/parse s (qp.timezone/results-timezone-id)))]
    (condp re-matches field-type
      #"decimal.*"                bigdec
      #"time"                     parse-temporal
      #"time with time zone"      parse-temporal
      #"timestamp"                parse-temporal
      #"timestamp with time zone" parse-temporal
      identity)))
```

**Comment by mysticaltech** [comment]
On thing though @sbelak, there is no mention of **special-type** in the driver's code (at least for Presto), just **base-type**.

**Comment by sbelak** [comment]
Special type is for the most part DB agnostic and we set it during sync (see metabase.sync.analyze.*). If the DB returns text for the field type, it's probably best in the short term, to go with option a) from above; but we should at some point revamp classification to allow driver-specific classifiers (since these would need to be applied to every text column the overhead is too big for DBs that don't need it).

**Comment by mysticaltech** [comment]
@sbelak I'm going to be realistic here, as a quick local patch, if I edit this file https://github.com/metabase/metabase/blob/master/src/metabase/sync/analyze/classifiers/name.clj and match on the column name (I can rename those), it can be done, correct? I guess I will just try this.

`[#"^.*_iso_datetime$"                     text-type        :type/ISO8601DateTime]`

And also edit this https://github.com/metabase/metabase/blob/master/src/metabase/types.clj with:

`(derive :type/ISO8601DateTime :type/DateTime)`

There's a good chance that it works right, or does it get a lot deeper than this?

**Comment by mysticaltech** [comment]
Folks, the [types.clj](https://github.com/metabase/metabase/blob/master/src/metabase/types.clj) file literally tells us what to do:
```
"The Metabase Hierarchical Type System (MHTS). This is a hierarchy where types derive from one or more parent types,
   which in turn derive from their own parents. This makes it possible to add new types without needing to add
   corresponding mappings in the frontend or other places. For example, a Database may want a type called something
   like `:type/CaseInsensitiveText`; we can add this type as a derivative of `:type/Text` and everywhere else can
   continue to treat it as such until further notice.")

;; NOTE: be sure to update frontend/test/metabase-bootstrap.js when updating this
```

Basically 2 lines of code! 😍Could this alone work? Then we could manually select the type in the Data Model settings?

**Comment by sbelak** [comment]
Adding to classifiers will just automate what you otherwise do manually in Data Model. If setting the type there is not sufficient, neither will adding a classifier.

**Comment by mysticaltech** [comment]
@sbelak Ok that I guessed, what about my proposal above, are you familiar with the [types.clj](https://github.com/metabase/metabase/blob/master/src/metabase/types.clj) file? Apparently, it was built for this. So adding the type there and in [metabase-bootstrap.js](https://github.com/metabase/metabase/blob/master/frontend/test/metabase-bootstrap.js) should do it, no?

**Comment by mysticaltech** [comment]
The reason I wanted to add a classifier @sbelak is to specify **text-type**, as I have tried specifying other special-type timestamps manually in the UI, it does picks it up in the UI and parse it correctly in the table, but it fails when you run a run, as it's not doing the casting at query time. So my hope is that when specifiying **text-type** as show below, it will force the casting to happen.

`[#"^.*_iso_datetime$" text-type :type/ISO8601DateTime]`

Also see PR #13541 for the type declaration.

**Comment by mysticaltech** [comment]
Is my logic above correct or am I missing something? Do I invest the time and try it out?

**Comment by sbelak** [comment]
The `base-type` in classifiers is to narrow the scope. The lines should be read as: if the pattern matches the name AND base-type is _____, then set special-type to __________. You can't influence the base type there.

**Comment by mysticaltech** [comment]
@sbelak Ok I see... I'm turning in circles here. So **base-type** needs to be selected at the driver level, but it's already correct, it's **varchar**. So what do I do now? I need to make this work please, if you can think of a way, just tell me and I'll do the coding 😔 🙏🏻  When I enforce special-types in the data model admin UI (with any currently supported DateTime timestamps), it fails at query time... "An error has happened" and I can see that it's not doing the casting with Date()...

**Comment by sbelak** [comment]
On a test instance you can try and change the `base-type` manually. If this works, the scope of the work is pretty limited, because all the code is already there (which I suspect is the case). If not, understand where & why it fails and go from there.

**Comment by mysticaltech** [comment]
Ok, thank you, will try. Really appreciate the guidance.

**Comment by mysticaltech** [comment]
What if we used something similar to the **unix-timestamp?** method in [field.clj](https://github.com/metabase/metabase/blob/master/src/metabase/models/field.clj), but for string iso dates, something like:

(defn iso8601-datetime?
  "Is field of iso8601 formatted datetime?"
  [{:keys [base_type special_type]}]
  (and (isa? base_type :type/Text)
       (isa? special_type :type/Temporal)))

Then plug it everywhere that **unix-timestamp?** is called, how does that sound?

**Comment by mysticaltech** [comment]
Folks, my issue has been fixed by changing all my dates to UNIX Timestamps, so integer. Then choosing the UNIX Timestamps in the Metabase Data Model in the Admin UI. Now it recognizes and fetches correctly. Yes, I circumvented the problem, but needless to say, if it works with UNIX Timestamps, my suggestion above will work for ISO string dates. Those who need it, try it. Thanks again @sbelak for the support and guidance. Hopefully, my research brought this issue a little closer to full resolution.

**Comment by mysticaltech** [comment]
![Screen Shot 2020-10-23 at 1 46 21 PM](https://user-images.githubusercontent.com/518555/97001638-f81e0180-1538-11eb-9db9-3175f3e6d258.png)

**Comment by camsaul** [comment]
I mentioned this in #13860 but I think what we really want separate `DateString`, `TimeString`, and `DateTimeString` types -- possibly with different subtypes to support different formats such as ISO-8601, `YYYYMMDD`, etc. Some databases out there are not going to let us use the same function to parse `2020-11-23`, `2020-11-23T17:49:00`, and `17:49:00`, for example.

**Comment by camsaul** [comment]
@dpsutton I've added this to the 0.38 milestone and tagged you as one who assignee/implementer -- can you make sure this issue is closed once your PR gets merged? Sometimes GitHub does it automatically, sometimes it doesn't

**Comment by mysticaltech** [comment]
Well done folks! 😍 🏆

**Comment by SebastianSzturo** [comment]
I am using metabase 0.42 with a SQLite database and dates queried through the SQL editor formatted as `2015-11-30` or `2015-11-30T23:48` are still only showing up as Strings. Is there something that needs to be configured on fields to support this? 

<img width="295" alt="CleanShot 2022-02-09 at 11 24 41@2x" src="https://user-images.githubusercontent.com/2699745/153110018-a556f5bb-6b68-4a14-91e2-db57a0af2d9f.png">

**Comment by flamber** [comment]
@SebastianSzturo 
SQLite is different from normal databases: https://www.sqlite.org/datatype3.html#date_and_time_datatype - #11703

**Comment by SebastianSzturo** [comment]
Ah I see, so the issue persists in SQLite and there is no special string concatenation workaround (e.g. by attaching `date('2015-11-30') || "T00:00:00ZZ"` to make it work? 
Is the question notebook GUI doing something special to recognize these strings as dates and let you group by them?

**Comment by flamber** [comment]
@SebastianSzturo GUI questions makes use of the Data Model, which fakes the string into a date. You can try using Models in 42, but I would probably just recommend using another database type.
