### ISSUE TITLE
Remove operator suggestions in custom expression editor

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15761]
# Context

Except for the suggestions of the name of functions and fields, the editor for custom expressions gives invalid or incomplete suggestions.

Suggestions can be useful. For example:

1. Ask a question, Custom questions
2. Sample Dataset, Orders table
3. Filter, Custom Expression
4. Type “t”

The suggestions are for the input “t”, i.e. the field names which match (case-insensitive) the typed characters in the editor. So far so good.

![image](https://user-images.githubusercontent.com/1455846/115774818-e6da7400-a366-11eb-8ab5-b94a67b687b9.png)

But then things start to break, as the editor makes not-so-useful or even invalid suggestions.

### A

In this example, the user types “[Tax]” and among the suggestions are **AND** and **OR**. The field [Tax] however is a numeric field and it needs to be compared with another value, e.g. “[Tax] < 100”. Doing a logical comparison either with AND or OR does not make any sense since “[Tax]” is not a segment. If the user insists, they receive an “Unknown Segment: Tax” error message.

![image](https://user-images.githubusercontent.com/1455846/115774834-ecd05500-a366-11eb-87d1-ab8f711bbae3.png)

### B

If you keep going, “10” is a number and doing a logical comparison after that does not make sense.

![image](https://user-images.githubusercontent.com/1455846/115774848-f0fc7280-a366-11eb-8b3e-ff48e67172d0.png)

### C

Meanwhile, assuming the user does really intend to come up with a comparison:

The first choice in the suggestion popover, Subtotal field, is fine. However, the second one, the function substring, is not supposed to be there. The return value of the substring function is always a string, and hence it can not be compared with the numeric field such as Tax.

Note that this is already a reduced set of choices (to match the typed “su”). If the user places the cursor after the operator >, the list of functions suggested by the editor will be rather long and will contain other string functions such as concat, ltrim, rtrim, etc, all of which makes no sense.

![image](https://user-images.githubusercontent.com/1455846/115774868-f6f25380-a366-11eb-9aa2-939079a1735d.png)

### D

When the user is working with a string field, the same misleading choices also occur.

This is with the Reviews table, so [Reviewer] is a text field (of the string type). Some comparison suggested in the popover, such as < (less than), > (greater than), etc will cause an invalid expression. A text field like [Reviewer] can only be compared equally, with either != or = operator. Of course, the problem with the logical operators AND and OR also exists here.

![image](https://user-images.githubusercontent.com/1455846/115774886-fd80cb00-a366-11eb-89c2-59a37a397bab.png)

### E

In other cases, the suggested operators may lead the user to believe that the expression is limited.

In the first screenshot, it looks like there is only a possibility of comparing [Total] with another field or value, with the operator != (not equal), < (less than), etc. However, if the user continues to type to express what they want, they get the expression like in the right screenshot. Apparently it is possible to use “+” (addition) there, even though this + operator was never in the original suggestions to begin with!

![image](https://user-images.githubusercontent.com/1455846/115774894-02457f00-a367-11eb-9e5a-faa64fe81e51.png)

### F

To add insult to injury, the suggestions still insist that there could be comparison operators and logical AND/OR, while the user can still continue the arithmetic operation that they want to achieve, e.g. “[Total] + [Tax] - [Discount]”.

![image](https://user-images.githubusercontent.com/1455846/115774911-08d3f680-a367-11eb-81f0-566108842607.png)

# What

With that, rather than:

- suggesting operators which lead to an invalid expression
- missing the operators which can be perfectly used in the expression

We will **NOT** suggest any operators at all, i.e. keep the suggestion **ONLY** to complete field or function names.

We won't change anything else about suggestions right now. Later on we can consider the implementation of an accurate semantics analysis of the (partial) expression and that can be used to offer a complete and valid suggestions, then this position can be revisited.

**Comment by ariya** [comment]
This is now completed with the merge of PR #15839.
