### ISSUE TITLE
Add Search and Pagination to Admin People List

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15770]
Please feel free to break these into separate issues if that seems more appropriate.

# Context

In the People page in Admin, we just show a list of people. That's fine in our small and mighty team of 25, but when you have 2500 people using Metabase, that page is straight up unusable.

## Goals

1. To reduce the size of each page load for the People page
2. To give admins basic tools to find the people they need to

## Non-Goals

- To add new user-management-related functionality. Editing users continues to work the same way.

# What

We can fix these performance issues through a couple main things.

- In the main `/admin/people` page
    - Search
    - Pagination (10 per page)
- In the `/admin/people/groups/:group-id` page
    - Pagination (15 per page)

**Pagination** should be simple and self-explanatory:

- Total number of entries
- From-to index items on this page (taken from `/admin/troubleshooting/tasks`)
- Next/previous arrows
- Only show up when the total number of entries is above the page size

**Search** should also be fairly simple:

- Search-as-you-type (hitting return does nothing) when query is longer than 2 chars
- Case-insensitive match
- Match on first name, last name or email
- Sort by name

I considered including URL parameters for search query and pagination as a requirement, but since users are edited in a modal, back button behavior doesn't seem necessary, and thus URL parameters aren't needed.

## Designs

I tried to reuse things already in Admin as much as possible and didn't try to make this particularly beautiful. Let's keep a narrow focus.

### Main UI

Please note the count in the footer and the alignment between UI elements and the columns).

![image](https://user-images.githubusercontent.com/1455846/115779580-05436e00-a36d-11eb-9514-487cd266da66.png)

### If no results are found

Please note the footer vanishes. 

![image](https://user-images.githubusercontent.com/1455846/115779632-155b4d80-a36d-11eb-8980-a738daf99f9f.png)

### In the group membership page

Please note the count in the title.

![image](https://user-images.githubusercontent.com/1455846/115779815-49367300-a36d-11eb-836b-4d72118c2ede.png)

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/15687
