### ISSUE TITLE
Tooltip shows incorrect values on unaggregated data with breakout

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#15785]
**Describe the bug**
When there are two or more columns with unaggregated data and breakouts the tooltip shows incorrect values.

**To Reproduce**
1. Open SQL editor and paste the following query
```
select 1 as axis, 5 as value, 9 as breakout union all
select 2 as axis, 6 as value, 10 as breakout union all
select 2 as axis, 6 as value, 10 as breakout
```
2. Create a bar chart with the following settings
<img width="323" alt="Screen Shot 2021-04-23 at 20 37 52" src="https://user-images.githubusercontent.com/14301985/115909157-c815d380-a473-11eb-80c8-b10475aed5f7.png">

** Actual result **
<img width="906" alt="Screen Shot 2021-04-23 at 20 35 55" src="https://user-images.githubusercontent.com/14301985/115909210-e11e8480-a473-11eb-9221-70fe3a7ee63b.png">

**Expected behavior**
The tooltip should show `Value: 12`

**Information about your Metabase Installation:**
0.39, but likely to exist for a long time

It is related to https://github.com/metabase/metabase/issues/11907 but reproduces only with breakouts

**Comment by nemanjaglumac** [comment]
I tried to reproduce locally and this is a screenshot from a Cypress run. I'm seeing the correct value.
![image](https://user-images.githubusercontent.com/31325167/115915175-432aba00-a473-11eb-987f-e21dc5375404.png)

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/15783
