### ISSUE TITLE
Change language to Norwegian Bokmal error

### ISSUE THREAD

**Issue by AL4AL** [metabase/metabase#15782]
I am trying to change language to "Norwegian Bokmal" or "Persian" in user/edit_current but I get this error:
`2021-04-23 10:47:46,078 DEBUG middleware.log :: PUT /api/user/1 400 3.6 ms (0 DB calls) 
{:errors
 {:locale
  "value may be nil, or if non-nil, String must be a valid two-letter ISO language or language-country code e.g. en or en_US."}}
`
No other languages has this problem
Using Mysql: Ver 8.0.22-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
This is the request that has been sent:
![image](https://user-images.githubusercontent.com/22044358/115827496-97a54980-a421-11eb-93da-fe37afe2e1fe.png)

This is the commit I compiled: https://github.com/metabase/metabase/commit/ce939219f8a3e28ecb00deb232154780a1dcfcef

**Comment by flamber** [comment]
Hi @AL4AL 
There were a lot of language changes it the past could of weeks. I cannot reproduce on latest release or master.
