### ISSUE TITLE
Conditionally format rows in tables

### ISSUE THREAD

**Issue by GJMcClintock** [metabase/metabase#15794]
Currently you can only format on columns (unless it's in a pivot table) - it would be nice to apply the conditional formatting across columns at a row level by selecting which columns should be in a range.

If Pivot Tables for BigQuery get fixed, that address my issue, currently I am creating them manually through SQL and displaying them, but have no highlighting in the basic tables.

**Comment by flamber** [comment]
Duplicate of #15523
