### ISSUE TITLE
Scalar result font size is out of control for pieces of text that are more than a couple of words

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1580]
A query that returns a single a decent-size chunk of text is basically impossible to read.

![screen shot 2015-11-30 at 4 33 53 pm](https://cloud.githubusercontent.com/assets/1455846/11489017/3206445c-9780-11e5-997a-b434b7821fcb.png)

**Comment by camsaul** [comment]
preferably we'd use a smaller font size in this situation

**Comment by agilliland** [comment]
Think this is addressed by #2136
