### ISSUE TITLE
"Not something with an ID" on something that looks like an ID

### ISSUE THREAD

**Issue by jerluc** [metabase/metabase#15834]
**Describe the bug**

Currently we are unable to select any "Saved Questions" to start from when creating a new question, as a server error is occurring when clicking on that dropdown menu button (specifically the `/api/database/-1337/schemas` call is failing with a 500).

See screenshots later in the issue for a more visual description of the bug.

**Logs**

Server logs (truncated to the top of the stack trace, since it seems to recurse into Jetty madness toward the end; I'm happy to include more if needed):

```
2021-04-27 11:19:32,786 ERROR middleware.log :: GET /api/database/-1337/schemas 500 25.8 ms (6 DB calls)
{:via
 [{:type java.lang.Exception,
   :message "Not something with an ID: 2",
   :at [metabase.util$the_id invokeStatic "util.clj" 504]}],
 :trace
 [[metabase.util$the_id invokeStatic "util.clj" 504]
  [metabase.util$the_id invoke "util.clj" 495]
  [metabase.driver.util$database__GT_driver_STAR_ invokeStatic "util.clj" 63]
  [metabase.driver.util$database__GT_driver_STAR_ invoke "util.clj" 60]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [clojure.core.memoize$through_STAR_$fn__4821 invoke "memoize.clj" 107]
  [clojure.core.cache$through$fn__4544 invoke "cache.clj" 55]
  [clojure.core.memoize$through_STAR_$fn__4817$fn__4818 invoke "memoize.clj" 106]
  [clojure.core.memoize.RetryingDelay deref "memoize.clj" 47]
  [clojure.core$deref invokeStatic "core.clj" 2320]
  [clojure.core$deref invoke "core.clj" 2306]
  [clojure.core.memoize$cached_function$fn__4885 doInvoke "memoize.clj" 231]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  ...
```

The most confusing part to me here is the error message, which seems to indicate a failure occurring in the [`id` or `the-id` functions](https://github.com/metabase/metabase/blob/v0.38.3/src/metabase/util.clj#L483-L504). I'm not a Clojure guru, but from what I've read here, this code should be succeeding with the input argument `2`, but clearly is failing with the message as indicated in the logs (note that the code linked is to the v0.38.3 version, which is the version we are currently running).

My only thoughts could be if the `2` is actually the string `"2"` or something odd like that which reveals itself ambiguously in the logs?

**To Reproduce**
1. Go to "Ask a question"
2. Choose "Simple Question"
3. Under "Pick your data", click on the "Saved Questions" option
4. See progress circle appear briefly before disappearing again and showing error in browser console

**Expected behavior**

This used to (at least in some prior versions of Metabase) show a drop down of our saved questions and would allow us to create new questions based on prior ones.

**Screenshots**

![Screenshot from 2021-04-27 11-41-09](https://user-images.githubusercontent.com/745427/116295057-8758db80-a74d-11eb-8ede-085bb47ffdf8.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.4.89+",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-01",
      "tag": "v0.38.3",
      "branch": "release-x.38.x",
      "hash": "8332830"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**

Our primary use case for Metabase is to help our less technical colleagues access our data without needing to resort to SQL and to be able to collaborate with our engineers where needed on more complicated questions that cannot be asked via the builder UI. The lack of this feature working inhibits a large chunk of that collaboration as "Saved Questions" were the primary way in which this collaboration existed.

**Additional context**

I'm more than happy to dig deeper into the code as needed to see if I can track this down myself if the maintainers or community at large have other priorities, but I'm completely new to this codebase, my Clojure skills are limited at best, and would otherwise be trying to dig up the whole codebase just to understand what might be a simple issue.

With that said, I'd greatly appreciate any pointers on where I could start the digging process (I suspect it may be in our application database itself) if that would help take a load off of the community's collective shoulders.

**Comment by flamber** [comment]
Hi @jerluc 

When you say "currently" - does that mean you didn't have this problem earlier?
When was the last time you recall using "Saved Questions" and which version were you using?

I think you have a question (see `report_card` table in application database), which has an `database_id=2`, but you don't have any databases with that ID anymore (`metabase_database`), which would be a corruption and would probably cause the "Saved Questions" not to load. It should not be possible to get into this state, since there's a constraint that protects against this, but I have seen some strange corruptions in the H2 databases.

On a side note, you should migrate away from H2 if you're using Metabase in production:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Comment by jerluc** [comment]
Thanks for the quick response @flamber! Yeah we've definitely used this feature in the past, with varying degrees of success. I don't recall any particular version that made this better or worse unfortunately.

Also thanks for the pointers on where to look in the application database! I'll try to double check the `report_card` table as you mentioned to see if there are any weird things going on there. The odd part however is that our main database (the data source we use for some 95% of our working questions) does in fact have an ID of `2`, at least as far as I can tell from the admin UI's URL and the API call `/api/database/2`, which both currently work. Is this sufficient proof that our `database_id=2` exists? Or do you think I still need to dig into the application database?

As for the H2 database, yes this is something that I've been wanting to migrate for a while, but never had the chance to. Understood that corruptions in the embedded database could be causing some weird side effects, especially as I think our H2 database is now at least a few years old and has been through several Metabase upgrades during that time. I'll try to look into the migration documentation you sent over separately to see how difficult it might be to take on so that we can finally be doing things the "right" way for production.

**Comment by flamber** [comment]
@jerluc I'm almost completely sure that you have a question that is using another question (Saved Question/nested) as it's source, and the problem is with the nested question.
I don't know how many questions you have, but I'm sure if you clicked through your questions, you would have one/two that fails.

Then I would need the entire row from `report_card` for both questions, so I can figure out how to reproduce this problem.

The fix for you would be to archive and then delete the questions (which doesn't work anyway).

**Comment by jerluc** [comment]
Thanks @flamber, I managed to get lucky and find a the question that wasn't working, archived it, and now the drop down is working again!

Furthermore, using your provided docs link to the migration guide, I was able to very easily migrate our application data to PostgreSQL, so thanks for your help there too!

Before I close this out, I'm wondering then a couple of things:

1. How can a question get in this state to begin with? And furthermore, are there any "healthchecks" that Metabase could do at boot time to warn of these invalid questions?
2. I'm still a little confused as to why the error message in the logs indicated that "Not something with an ID: 2", despite that I was able to verify in the migrated application database with `SELECT * FROM metabase_database WHERE id = 2`. This seems like a red herring, so I'm curious to know if there's anyway to improve this error message to help others who might experience this in the future.

**Comment by jerluc** [comment]
> I had a long back-and-forth a while ago, but the feedback didn't lead me to a way to reproduce this problem, so I would be very happy if you could provide enough information, so we can reproduce and fix this.
> https://discourse.metabase.com/t/cannot-include-saved-questions-as-starting-data-in-custom-question/13519

Just read through this, and yeah I can see at least some similarities here. I'd be more than happy to provide additional details, especially regarding the "faulty" question that I archived if needed, as I've noted the question ID for this very purpose. Just let me know what information or application DB SQL queries are most helpful for me to provide!

**Comment by flamber** [comment]
@jerluc Without seeing the raw data for the problematic question, then I have absolute zero idea how you ended up here.

I would need the entire row of `report_card` of the problematic question. I'm guessing the problem is in `dataset_query`, but not fully sure about that. So if the corrupted question is 123, then I need `select * from report_card where id=123`.

But since you have archived the question, then I don't know if that has changed something, which means it might not be reproducible.

Like you can see from the forum topic (and a linked topic), I have not received any data, which could help get to the root cause, so people just fixed their problem and left - that's the norm sadly.

**Comment by jerluc** [comment]
No problem @flamber, I'm here to help however possible. I can certainly appreciate (albeit to a much lesser extent) the frustrations in trying to maintain an open source project and community.

This is what the now-archived question looks like in the application database:

```
postgres=# SELECT * FROM report_card WHERE id = 841;
 id  |         created_at         |          updated_at           |         name         | description | display |                                                                                                                                            dataset_query                                                                                                                                            | visualization_settings | creator_id | database_id | table_id | query_type | archived | collection_id | public_uuid | made_public_by_id | enable_embedding | embedding_params | cache_ttl | result_metadata | collection_position
-----+----------------------------+-------------------------------+----------------------+-------------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+------------+-------------+----------+------------+----------+---------------+-------------+-------------------+------------------+------------------+-----------+-----------------+---------------------
 841 | 2020-10-16 11:26:32.576+00 | 2021-04-27 21:11:42.667211+00 | API Status Breakdown |             | table   | {"type":"query","query":{"source-table":78,"aggregation":[["count"]],"breakout":[["field-id",738],["field-id",746],["datetime-field",["field-id",733],"hour"]],"filter":["and",["not-empty",["field-id",746]],["not-null",["field-id",738]],["!=",["field-id",746],"status:read"]]},"database":"2"} | {}                     |         34 |           2 |       78 | query      | t        |               |             |                   | f                |                  |           | []              |              
(1 row)
```

Luckily, I _can_ reproduce the problem simply by toggling the `archived` flag to `FALSE` (still breaks the "Saved Questions" dropdown) and `TRUE` (fixes the dropdown). Hopefully we can use this example to identify the underlying cause.

**Comment by flamber** [comment]
@jerluc No matter how I try, I'm not able to create a corrupted question.
If you unarchive the question and go to `/question/841` which errors are you seeing in log (Admin > Troubleshooting > Logs)?
Do you have any idea what the problem could be with this question (or the table/columns it is querying)?
