### ISSUE TITLE
v0.39.0.1: French localization - "{0}" instead of real values in strings interpolations on the UI

### ISSUE THREAD

**Issue by incyclum** [metabase/metabase#15832]
Hi all!

I noticed "{0}" in strings like in "Showing {0} rows" in question pages
or other multiple uninterpolated places like the reset password strengths requirements.
I'm on french localization.

When I switch to English the problem disappears.

Thank you

**Comment by flamber** [comment]
Duplicate of #15694

**Comment by incyclum** [comment]
Thank you @flamber, I missed it even with searching with "{0}" in issue tab 🤔
