### ISSUE TITLE
Alert window disappears after timeout when created after "unsubscribe"

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#15831]
**Describe the bug**
If you first unsubscribe from an existing alert and then click on "Set up your own alert", then the new alert window closes automatically after a set timeout.

**Logs**
N/A

**To Reproduce**
1. Go to any existing question and create an alert (alternatively, go to any question that already has an alert)
2. Click on the bell icon in the lower right corner
3. Click "Unsubscribe" in the popover (if you don't do anything after this step, popover will disappear after a set timeout)
4. Notice that you can now click on "Set up your own alert" (notice they are crammed together)
5. New alert window appears
6. But it will disappear (possibly interrupting you) after the original timeout from step 3 ends

**Expected behavior**
New alert window should stay on as long as the user is creating an alert and should be closed either upon clicking "Done" or "Cancel". Original timeout shouldn't affect this window/full-screen modal.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/YEuRDQOg/7f112706-057f-4962-a27f-5819b63094b7.gif?v=91d8d86ec9a12e3246739dca5f31312c)

**Information about your Metabase Installation:**
- Local dev, `release-x.39.x`, H2, Sample Dataset

**Severity**
It's annoying but nothing that can't be worked around. P3, I guess.

**Comment by brunobergher** [comment]
Can't repro with the new UI anymore.
