### ISSUE TITLE
The client and server don't support a common SSL protocol version or cipher suite

### ISSUE THREAD

**Issue by maliqiakbar** [metabase/metabase#15853]
Hi Metabase Team,

I am configuring metabase SSL with generated certificate from letsencrypt. I am exporting certificate to CER and importing certificate using keytool as JKS. 

Unfortunately after JETTY configured to have SSL port opened metabase running fine when accessed from HTTP but got error  _"The client and server don't support a common SSL protocol version or cipher suite"_ when accessing through HTTPS.

**Comment by flamber** [comment]
I would highly recommend using a reverse-proxy like Nginx or Caddy to handle certificates instead through Metabase.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
