### ISSUE TITLE
We don't format custom expression filters correctly

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#15855]
![image](https://user-images.githubusercontent.com/691495/116462569-94ea9000-a837-11eb-9052-2961aff897c4.png)

I added a filter with the custom expression `[Tax] > [Total]`. The filter description pill shows the field id and the filter widget selected when I reopen it isn't the custom expression editor. 

Despite this display issue, the correct MBQL was sent to the server.

**Comment by ariya** [comment]
Isn't this the same as #15748?

**Comment by paulrosenzweig** [comment]
@ariya yup! thanks.
