### ISSUE TITLE
Sync settings

### ISSUE THREAD

**Issue by stas** [metabase/metabase#1586]
Running Metabase on a big database creates an unnecessary load when it tries to sync the schema/data.
Having some sort of settings where one could disable or schedule the sync would help a lot.

**Comment by agilliland** [comment]
Hey @stas, thanks for the feedback.  You mind sharing some more general details about your database so that we can have some better understanding of a situation where someone might want to skip some of the sync logic?

I'm thinking things like database type, # of tables, # of columns per table, # of rows (at least in the big tables), and anything else you think would be helpful.  Would also be good to hear some info on how long the sync is taking and if it's getting stuck/slow at any particular parts.

**Comment by stas** [comment]
@agilliland our main frustration would come from the fact that Metabase tries to map column types to special types like category. This is also the main reason why we had to stop it running all the time, and we just start it when we need it.

The sync operations for this kind of _data discovery_ will generate a lot of reads on our servers.
Some of the columns will not have indexes since normally it would not be necessary to maintain those (or it is too expensive to keep those up-to-date all the time). In this specific context, Metabase queries will hit a sequential scan every time a sync is scheduled (we use mainly Postgres/Redshift, some tables have hundreds of millions of records).

Normally Metabase will trigger the scan during the night hours. This is another problem since we schedule our database maintenance operations to run nightly (this means vacuuming, data updates and all kind of operations that require high IOPS). And while we can orchestrate our operations, Metabase does not offer any similar settings/options.

A very particular case would be encrypted data. Running Metabase sync for columns with encrypted data is absolutely unnecessary and we should be able to disable it.

The way I see this feature, is more like an optional, on-demand functionality. And it should be up to the user to decide if they want their data analyzed along with their schema and whenever this needs to be updated on a regular basis.

Personally, I want to thank you and the team for such a great product!

**Comment by agilliland** [comment]
Thanks for the detailed feedback @stas , this is super helpful.  For the most part we've been working with folks that have modest sized databases, so our syncing hasn't been a problem, but I can definitely appreciate that on large datasets the introspection process could create unwanted load.

**Comment by mazameli** [comment]
Here's how this option should look in the three cases where it could be presented to the user: during initial setup, on the add database screen, and on the edit database screen:

![setup](https://cloud.githubusercontent.com/assets/2223916/12403617/f6083592-bde9-11e5-85b2-4b017dd79aed.png)

![add database](https://cloud.githubusercontent.com/assets/2223916/12403620/f8f521c0-bde9-11e5-8ee2-d35862af55fb.png)

![edit_database](https://cloud.githubusercontent.com/assets/2223916/12403664/491b816c-bdea-11e5-9d7b-279e4f86d92a.png)

**Comment by stas** [comment]
@mazameli this looks beautiful! :ok_hand:

**Comment by stas** [comment]
Thank you!
