### ISSUE TITLE
Note about how to pin dashboards to get them to show up on the home page is missing on a fresh install

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15867]
This is on `master`. Not sure when exactly this regression might've gotten introduced exactly, but we used to have a text box at the top of the homepage on a fresh install that would say something like, "Pin dashboards in "Our Analytics" to have them show up here for everyone." It appears that string is still present in `Overworld.jsx`, but I'm not seeing the box render here. This is a jar I built.

![image](https://user-images.githubusercontent.com/2223916/116595017-b733ea80-a8d7-11eb-8caf-ccfaaf00acf7.png)

**Comment by mazameli** [comment]
Here's a screenshot from our docs of how it should look:

![image](https://user-images.githubusercontent.com/2223916/116596730-9cfb0c00-a8d9-11eb-884b-389a3a060870.png)

**Comment by flamber** [comment]
I'm still seeing it on a master commit `6324cef` - check with incognito mode, since that "Start here" section is controlled by cookies instead of settings like everything else.

**Comment by mazameli** [comment]
@flamber + @nemanjaglumac, apologies, yeah, on master (e58df52252877fac1cd9433e1993244a23eda839) **with incognito mode**, it shows up correctly:

![image](https://user-images.githubusercontent.com/2223916/119166133-1f777700-ba13-11eb-88aa-cd83dd38945f.png)
