### ISSUE TITLE
`TIME` are randomly cast with/without timezone depending on millisecond values

### ISSUE THREAD

**Issue by Mapiarz** [metabase/metabase#15876]
When doing a native query to cast a datetime to time, the results are inconsistent. Some of the rows have incorrect time, in my particular case it's -7 hours. See here: https://i.imgur.com/RbKGdTq.png. For sanity, here's the same query ran in PgAdmin: https://i.imgur.com/3KA4bHT.png

Using Metabase cloud, not self hosted.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @Mapiarz 
Does this happen consistently with the same rows, or does it change randomly for every time you run the query?
Please include "Diagnostic Info" from Admin > Troubleshooting.
And the output from `/api/dataset`, when you run the query, since I don't think it's a frontend issue, but a processing/driver issue.

**Comment by flamber** [comment]
Workaround is to use `::time(3)`

I'm not quite sure what's going on - seems like the microseconds causes some strange behavior in frontend, while milliseconds are okay, but no decimals is also wrong (huh!?).
I can reproduce on Postgres, but H2 is giving me a headache, so ignoring it for now, but this issue might apply to all databases.
```
select mytz as "ts", mytz::text as "tsAStext", state, mytz::time as "time - LOOK AT THIS COLUMN", mytz::time::text as "timeAStext", mytz::time(0) as "time(0) - ALL INCORRECT", mytz::time(3) as "time(3) - ALL GOOD" from (
    select '2016-05-04 16:29:59.268160-04:00'::timestamptz as mytz, 'incorrect' AS state union all
    select '2016-05-04 16:29:59.412459-04:00'::timestamptz, 'good' union all
    select '2016-05-08 13:14:58.926221-04:00'::timestamptz, 'incorrect' union all
    select '2016-05-08 13:14:58.132020-04:00'::timestamptz, 'good' union all
    select '2016-05-10 07:38:58.987352-04:00'::timestamptz, 'incorrect' union all
    select '2016-05-10 07:38:58.001001-04:00'::timestamptz, 'good'
)x
```
![image](https://user-images.githubusercontent.com/1447303/116724289-c488cc00-a9e0-11eb-9082-cefc9f447e57.png)

**Comment by MiguelCalatrava** [comment]
Hi!

Any update on this?

The workaround suggested doesn't work in our case either in postgresql or bigquery db so we're a bit blocked with it. Thanks!

**Comment by MiguelCalatrava** [comment]
Thanks @flamber.

This is the exact same query executed on a postgres 9.6 version db. I have added a new row with an additional time which has an "exact" time (.000000), which are the ones that we mainly have in our business data and then it doesn't work.

We were checking the workaround with our own data and it never worked but we were always checking it against this type of times (all 0 in the floating part).

We have the same problem also on bigquery tables.

<img width="1777" alt="Screenshot 2021-05-26 at 12 56 44" src="https://user-images.githubusercontent.com/36237025/119649903-791cde80-be23-11eb-83cd-f04b19ca517d.png">

**Comment by flamber** [comment]
@MiguelCalatrava Okay, so that's the same as when there's no decimals - it's some strange rounding problem. I have updated by steps-to-reproduce to account for that too.

**Comment by MiguelCalatrava** [comment]
Thanks. I hadn't read that you had already mentioned the case of no decimals. Where can I see the steps-to-reproduce report? Is there anything more that we can provide?

**Comment by flamber** [comment]
@MiguelCalatrava The comment that you copied the query from: https://github.com/metabase/metabase/issues/15876#issuecomment-830210005

**Comment by camsaul** [comment]
I think we need to differentiate whether we cast to `TIME`  or `TIME WITH TIME ZONE` based on the whether the original column is `WITH TIME ZONE` or not... I'll investigate

**Comment by camsaul** [comment]
as @flamber mentioned this is actually an FE issue since the data coming back from the backend is ok. Going to unassign myself
