### ISSUE TITLE
Clojure log macros should throw a compile-time exception if you use `tru` inside them

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15886]
We don't want to use the user locale for localizing log messages -- we always want to use the system locale so all logs are in one language. Rather than having to keep this rule in our heads, we can actually have the code enforce it for us at compile time

**Comment by flamber** [comment]
Related to #10764

**Comment by camsaul** [comment]
Probably the best way to do this would be a custom Kondo linter actually
