### ISSUE TITLE
Don't show Custom Expression helper, when input is not in focus

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15891]
**Describe the bug**
Currently the expression helper is shown even when the input is not focused, which is annoying and makes it difficult to finish the expression in some cases.
Perhaps it should be kept if there's an error in the CE, since it might help finishing the CE more correctly.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Custom Column > type `rou` and press enter to autocomplete to `round(|)` and finish it by typing `1.5`, so it looks like this:
(To reproduce on master type `round(1.5)` and then change `5` to `7`, which will leave the cursor inside of the parenthesis)
![image](https://user-images.githubusercontent.com/1447303/116776392-77503d00-aa68-11eb-97bf-d69e9c9eaac7.png)
3. It's now covering the rest of the CE, so it cannot be completed - even when clicking outside the input to blur or hitting tab.
To make the helper go away, you have to move the cursor to the end - after the parenthesis.

It sometimes wanna be my friend too much and hangs around, when I started in the sidebar and go into the Notebook:
![image](https://user-images.githubusercontent.com/1447303/116776604-7ec41600-aa69-11eb-9ef2-ba244560dfa0.png)

**Information about your Metabase Installation:**
It's been like this since 0.35, but newest master now doesn't add closing parenthesis, which makes it less likely to end in this situation, but still very possible.

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/16541
