### ISSUE TITLE
Incorrect `effective_type` after upgrade to 39.x can cause various problems

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15913]
**Describe the bug**
An incorrect value of `metabase_field.effective_type` can cause various problems throughout Metabase - either wrong display values, or filters not working.
Reference #15901 and #15743 and #16177 and https://discourse.metabase.com/t/0-39-1-date-filter-not-working-anymore-in-bigquery/14666

**Logs**
Wildly different depending on the problem - see the referenced issues/forum.

**To Reproduce**
I have no idea how to reproduce, but I guess it's either caused by an incorrect Field Type defined on pre-39, which then gets saved into `effective_type`, or a sync that happens after upgrade, which defines the effective_type, but it's not possible to change the value for users unless editing the application database, which is highly discouraged (unless you know exactly what you're doing).

**Information about your Metabase Installation:**
Upgrade from pre-39 to 39.0/1

Related #15937

**Comment by luizarakaki** [comment]
Closing as outdated
