### ISSUE TITLE
Metabase Report bug 

### ISSUE THREAD

**Issue by loris974** [metabase/metabase#15929]
when upgrading to 0.39, mongo queries don't work anymore. an upgrade to 0.38.5 is ok. it is not possible to downgrade from 0.39 to 0.38.5. a solution is to restore the backup made before the upgrade and to upgrade to 0.38.5.

is there a solution in order to stay in 0.39 ?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
