### ISSUE TITLE
Custom Columns does not accept boolean expression result

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#15922]
**Describe the bug**
When using the isNull function in Custom Columns Metabase returns a "Value does not match Schema" error

**Logs**
Value does not match schema: {:query {:expressions {:discount_test (named (not (some-matching-condition? a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :expression, :field")}}}

**To Reproduce**
1. Build a custom query in the Sample Database -> orders table
2. Add a Custom column with the formula =isnull([Discount])
3. run the query

**Expected behavior**
A query that runs without errors showing the new column with a boolean value

**Screenshots**
No need

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu LTS latest
- Your databases: Sample database
- Metabase version: latest
- Metabase hosting environment: Internal Stats instance
- Metabase internal database: Internal Stats instace

**Severity**
Not severe, but users will have to do native SQL for this (or do transformations outside Metabase)

**Additional context**
Seems to be related to https://github.com/metabase/metabase/issues/13122

**Comment by ariya** [comment]
Very related to #13122.

**Comment by flamber** [comment]
Workaround is to use `case(isnull([Discount]), "true", "false")` or another return like `case(isnull([Discount]), 1, 0)`

**Comment by ariya** [comment]
I stand corrected, this has nothing to do with hard-coded type in custom column (see #15952). It's about the lack of boolean/logical support in custom column.

**Comment by flamber** [comment]
Giving this higher priority, since we're now showing them in the autosuggestion, which just makes it more likely to encounter this.
0.41.6
![image](https://user-images.githubusercontent.com/1447303/161048276-d82ac96c-b825-4c08-b1b2-332b7c96a62e.png)
0.42.3
![image](https://user-images.githubusercontent.com/1447303/161048322-6ab5af31-ff82-487a-aab3-ce3429b59fa0.png)

**Comment by ccaldicott1** [comment]
Hi, I am still experiencing this

**Comment by darksciencebase** [comment]
[internal thread](https://metaboat.slack.com/archives/C04CYTEL9N2/p1702991047628339)

**Comment by likeshumidity** [comment]
same for `isempty` or presumably any returning boolean
