### ISSUE TITLE
Unable to add a `Field filter` for `Category` field in Native SQL Query

### ISSUE THREAD

**Issue by chasleslr** [metabase/metabase#15935]
**Describe the bug**
In a Native SQL Query, adding a variable of type `Field filter` for a field of type `Category` is not possible, even though the [documentation](https://www.metabase.com/docs/v0.39.0/users-guide/13-sql-parameters.html#creating-sql-question-filters-using-field-filter-variables) states that it is.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Create a Native Query
2. Add a variable for a field of type `Category`
3. Choose `Field filter` as the `Variable type`
4. See the error message: `There aren't any filter widgets for this type of field yet. Learn more`

**Expected behavior**
I would expect to be able to add a Field filter

**Screenshots**
<img width="406" alt="Screen Shot 2021-05-05 at 3 25 57 PM" src="https://user-images.githubusercontent.com/54685896/117198119-9a575580-adb6-11eb-9255-0a714a415096.png">
<img width="406" alt="Screen Shot 2021-05-05 at 3 26 06 PM" src="https://user-images.githubusercontent.com/54685896/117198135-9d524600-adb6-11eb-984c-62599a09efe0.png">
<img width="2227" alt="Screen Shot 2021-05-05 at 3 29 31 PM" src="https://user-images.githubusercontent.com/54685896/117198214-bd820500-adb6-11eb-9cd2-48c468d687b6.png">

**Severity**
This prevents any filter filters from being added for category fields.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.203-156.332.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-19",
      "tag": "v0.39.0",
      "branch": "release-x.39.x",
      "hash": "5e40366"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by flamber** [comment]
Upgrade to 0.39.1 - fixed in 0.39.0.1 - #15700
