### ISSUE TITLE
Cannot run native queries against MongoDB unless explicitly selecting the table

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#15946]
I'm unable to run any native queries against mongo. The button is disabled.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/6377293/117257898-ff8c6480-ae11-11eb-9297-3996ae4a7c3b.png">

Reproduce:
Browse a mongo table, click view sql and then convert to native. The run query button is disabled.

Appears in this state on master, release-x.39.x, and on stats.
I have done some initial checking and I think `question.canRun()` is returning undefined for mongo queries.

## Edit

A sharp eye from @flamber points out that you have to select a table. It seems this is pre-selected on queries converted to native on other engines and does not get pre-selected on mongo. The db is preselected to the mongo instance but the table is not. Selecting it allows the query to run.

**Comment by flamber** [comment]
You have to select the table next to the data selector.
