### ISSUE TITLE
add trackEvent to main app nav bar for event enabled MB instances

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1596]
- [x] mb logo clicked
- [x] dashboard dropdown clicked
- [x] dashboard dropdown item clicked
- [x] pulse nav item clicked
- [x] saved question item clicked
- [x] new question item clicked
- [x] user dropdown clicked
- [x] user dropdown -> help clicked
- [x] user dropdown -> admin settings clicked
- [x] user dropdown -> account settings clicked
- [x] user dropdown -> logout clicked
- [x] user dropdown -> about metabase clicked

**Comment by salsakran** [comment]
we should add this (and related issues #1591, #1592 , #1593, #1594, #1595) to
the list of what we're capturing - http://www.metabase.com/docs/v0.13.1/information-collection.html
