### ISSUE TITLE
Sandboxed filters causes a lot of extra queries and is stored in-memory

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15977]
**Describe the bug**
This is probably a feature request, but the current behavior makes it a big performance issue for larger instances.

Since version 1.35.3 all scanned field values on a table that is sandboxed is only shown with respect to the sandbox.
So if a sandboxed user was viewing a dashboard with a filter dropdown, then it will only show a list of values based on what the user has access to based on their sandbox.
The sandboxed values are stored in memory for up to 30 days or until the global field value gets updated via the sync+scan process.

But this means that when the instance is restarted (because of the upgrade etc), then all the values in the memory are lost, so all sandboxed users browsing dashboards with filters will cause a lot of extra queries (almost double the normal amount).
And as a result, dashboards/etc are loading slower until most queries are in-memory again.

**To Reproduce**
- (full sandbox environment with multiple groups and dashboard filters with dropdowns)

**Expected behavior**
- It would probably be smart to cache persistently instead of in-memory.
- The 30 days TTL should probably be configurable (envvar) or perhaps just follow [MB_QUERY_CACHING_MAX_TTL](https://github.com/metabase/metabase/blob/master/docs/operations-guide/environment-variables.md#mb_query_caching_max_ttl).
- Cache hash should be based on sandboxed user ID **and** user attribute **and** attribute value (and possible other?), so changes to any of those could would make sure to never return incorrect values.
- If persistent storage is used, it should still drop caches whenever non-sandboxed field values are updated/refreshed.

**Information about your Metabase Installation:**
Tested 1.35.3 thru 1.39.1

**Additional context**
Related to the new behavior in x.37.0: #13832
Previously EE591 - https://github.com/metabase/metabase-enterprise/issues/591

**Comment by flamber** [comment]
Testing commit `aad24de` (almost 1.39.2) - from https://github.com/metabase/metabase/pull/15943#pullrequestreview-654993149

Right after an instance has been restarted, when going to a dashboard with dropdowns with a sandboxed user, then there are unnecessary requests for all the dropdowns (likely #16101) like this:
``SELECT `source`.`SOURCE` AS `SOURCE` FROM (SELECT `PEOPLE`.`ADDRESS` AS `ADDRESS`, `PEOPLE`.`BIRTH_DATE` AS `BIRTH_DATE`, `PEOPLE`.`CITY` AS `CITY`, `PEOPLE`.`CREATED_AT` AS `CREATED_AT`, `PEOPLE`.`EMAIL` AS `EMAIL`, `PEOPLE`.`ID` AS `ID`, `PEOPLE`.`LATITUDE` AS `LATITUDE`, `PEOPLE`.`LONGITUDE` AS `LONGITUDE`, `PEOPLE`.`NAME` AS `NAME`, `PEOPLE`.`PASSWORD` AS `PASSWORD`, `PEOPLE`.`SOURCE` AS `SOURCE`, `PEOPLE`.`STATE` AS `STATE`, `PEOPLE`.`ZIP` AS `ZIP` FROM `PEOPLE` WHERE `PEOPLE`.`ID` = 1) `source` GROUP BY `source`.`SOURCE` ORDER BY `source`.`SOURCE` ASC LIMIT 5000``
This is memorized on refresh.

But then all dropdowns with less than 300 distinct values does not make queries to the data source. But fields with more than 300 distinct values do - which is likely covered by #16102.

It sends requests every time the filter widgets are opened, but that's #16103.

**Comment by qnkhuat** [comment]
We now saved fieldvalues for sandbox in https://github.com/metabase/metabase/pull/23435
