### ISSUE TITLE
Validate Google sign-in client IDs

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#15975]
Google client IDs have a specific format and are suffixed by `.apps.googleusercontent.com`. We could do basic validation on client IDs (on the frontend and/or backend) and reject IDs with an incorrect format.

**Comment by flamber** [comment]
Changing priority, since I remember this actually causing problems since 0.33.7.3 - https://github.com/metabase/metabase/issues/12258#issuecomment-608996438
