### ISSUE TITLE
Question output downloaded as partial in CSV/Excell - Metabase 0.38.4

### ISSUE THREAD

**Issue by Na-Sathish** [metabase/metabase#15979]
While Downloading entire result of question as csv format getting downloaded as partial data. If i download 30 days data i am getting only 10 days.   

Metabase Version - 0.38.4
Downloaded format - CSV/xlsx

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And you need to include "Diagnostic Info" from Admin > Troubleshooting, and which database you are querying as minimum.
Without more information it would be close to impossible to reproduce and fix. Also, latest release is 0.39.1
