### ISSUE TITLE
Strip whitespace from Google sign-in client IDs

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#15976]
Client IDs that are saved with leading or trailing whitespace result in an OAuth error when trying to log in, even if the ID is otherwise valid.

**Comment by flamber** [comment]
That should have been fixed by #14594/#14616, but probably not on the Google Sign-in page, since it uses old form style (#11659)

**Comment by cdeweyx** [comment]
@noahmoss Is this still an issue or has it been addressed re the above comment?

**Comment by flamber** [comment]
Not fixed on 0.41.2, where it's still storing the spaces. This issue is very related to #15975.
