### ISSUE TITLE
Google sign-in client ID setting regularly fails to save

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#15974]
**Describe the bug**
When trying to set the client ID field for the Google sign-in settings, it fails about half the time. Failures manifest as a page refresh after clicking "save changes", and the old value still being present in the client ID field. This isn't deterministic, since sometimes I'll retry saving a value 2-3 times before it succeeds. It also doesn't have any bearing on whether the value is a valid client ID.

Browser console also logs `error updating setting` every time this form is submitted, regardless of whether saving succeeded or not.

**To Reproduce**
1. Go to the Admin Panel
2. Click on Authentication
3. Under "Sign in with Google" click "Configure"
4. Put any value into the first text box and click "Save Changes"
5. If the value was saved successfully after the page refreshes, retry step 4 with different values

**Expected behavior**
Value should save successfully every time the form is submitted.

**Information about your Metabase Installation:**
Firefox 88.0.1 on MacOS Big Sur, using an H2 database

**Comment by noahmoss** [comment]
On further investigation this appears to be a frontend bug, possibly specific to Firefox. The `PUT` requests seem to be aborted with the message `NS_BINDING_ABORTED` in the network tab. Might be because a page refresh is being triggered which aborts the request if it happens too quickly.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/32746338/117519708-8730bb00-af59-11eb-8e3c-c9cad638a20f.png">

**Comment by flamber** [comment]
Very related to #11659

**Comment by nemanjaglumac** [comment]
From my experience, it accepts the update when you first navigate to the page (also, on page refresh, which is basically the same thing). If you try to update the value without leaving the page, the error occurs.
