### ISSUE TITLE
Visualizations with more than 100 series just shows a blank chart

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16000]
**Describe the bug**
Visualizations with more than 100 series just shows a blank chart.

**To Reproduce**
1. Custom question > Sample Dataset > Products > summarize Count grouped by CreatedAt:Year and Title
2. Visualize and change to Line chart and change CreatedAt to the first field on X-axis, so Title becomes the breakout:
![image](https://user-images.githubusercontent.com/1447303/117843034-c410f080-b27e-11eb-91aa-00d99cc0cf47.png)
3. Blank visualization - only the legend is shown, but all mangled (#11355) - there's the following error in the browser console:
`Error: This chart type doesn't support more than 100 series of data.`

**Expected behavior**
Similar to how it used to be, when the limit was 20 - display an error instead of the visualization:
![image](https://user-images.githubusercontent.com/17504314/50566050-3febed00-0d03-11e9-9d83-1af9a64654b7.png)

**Information about your Metabase Installation:**
Tested 0.36.8 thru 0.39.1 - seems like we might never have handled 100+ series gracefully.

**Severity**
Fairly low chance for adding 100+, so only giving P3.

**Comment by morozovsk** [comment]
>Fairly low chance for adding 100+, so only giving P3.
this is no low chance. 
i can't group by: 
country, 
city, 
mobile carrier, 
device type, 
device manufactor, app version, action, error code, ... etc. now i can group by only by os.
please show just 100 series of data if it is more than 100 series of data.
