### ISSUE TITLE
Shifted chart values on line with ordinal x axis

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#16002]
Chart value labels are shifted left for the line series in the chart below. This only happens when the x axis is ordinal.
![image](https://user-images.githubusercontent.com/691495/117854459-80ef5700-b257-11eb-81cb-4739e62168af.png)

Separately, the labels within the bars look slightly too far to the left.

Repro steps:

1. Count Orders by User.Source and Product.Category
2. Turn on "Show values on data points"
3. Switch one of the series' display from bar to line.

**Comment by nemanjaglumac** [comment]
Ideal case for visual regression testing.
Also, @paulrosenzweig can you please include the query or the steps required for reproducing this?

**Comment by paulrosenzweig** [comment]
Repro steps:
1. Count Orders by User.Source and Product.Category
2. Turn on "Show values on data points"
3. Switch one of the series' display from bar to line.

**Comment by flamber** [comment]
Fixed by #16369 + #16488 - repro in #16513
