### ISSUE TITLE
Dashboard dropdown filters not showing all options

### ISSUE THREAD

**Issue by bulue94** [metabase/metabase#16017]
**Describe the bug**
Dashboard filters don't show all available options

**To Reproduce**
1. Create a question and create variable.
2. Add question to a dashboard and connect filter to variable

**Expected behavior**
Filters on dashboards connected to variables from questions should show the same options on the dropdown to filter.

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "es-419",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "4.19.0-16-cloud-amd64",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.11 (Debian 11.11-0+deb10u1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-27",
      "tag": "v0.39.1",
      "branch": "release-x.39.x",
      "hash": "6beba48"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

**Severity**
We can't apply the filters we need on the dashboards. Gives the impression that dashboard can't be filtered by the values wanted.

**Comment by paoliniluis** [comment]
You haven't made a field filter in the question or you haven't flagged the field which you're filtering as a category, please post this on the discourse forum

**Comment by bulue94** [comment]
I flagged the filed as a category, I can use it and the filter works when I use it on a single question. 

This error happened after we updated to v0.39.1

@paoliniluis
