### ISSUE TITLE
Feature request sign up per email

### ISSUE THREAD

**Issue by hawisizu** [metabase/metabase#16029]
Sorry if that's a duplicate, but I tried to search and didn't find it, although it seems quite an expected feature. 

For now, you can enable users to signup via google OAuth or LDAP, but you cannot chose to authorise users to signup directly with their email. This would be useful in our case, for now we have to ask the users to contact us, then we send them an invite email. We think more users would signup if they could create an account directly on their own. 

Of course this should remain optional as lots of project will want to remain on invite only! 

Thanks!

**Comment by flamber** [comment]
Hi @hawisizu 
When you enable SSO, then users can login by just going to the Metabase site URL and it automatically creates the account.
https://www.metabase.com/docs/latest/administration-guide/10-single-sign-on.html
If you first creates the user manually via Admin > People, then the account is created as password login and an invitation is sent to the email.

**Comment by hawisizu** [comment]
Not sure to follow you, if a user don't have a gmail address (or don't want to use google sign in), how can they create an account?

**Comment by flamber** [comment]
@hawisizu Unless you have enabled SSO, then users cannot create an account themselves - otherwise it would basically be the same as not having any authentication. If that's what you're looking for, then I don't see it as something we're going to implement.

**Comment by hawisizu** [comment]
Yes this is what I'm looking for, that user can register freely by email. I edited the name to make it clearer. I understand it's not the most common use case for Metabase which is likely mostly used as internal tool, but I don't think we are the only ones in this case tbh... Can we reopen the issue and see if this gets +1 ?

**Comment by flamber** [comment]
@hawisizu I would say most uses Metabase internally, but having no authentication could lead to so many security issues, and data privacy problems.
What you are asking for already exists, when using SSO, so connect Metabase to your SAML/JWT/LDAP/Google and then users can login without an account already - it creates the account on first login.

**Comment by hawisizu** [comment]
Sorry, but I'm still not sure you understand: I want private users (any citizen, so not from an organisation, so no SSO, possibly with an email not on google) to be able to register. There is still an authentication via email / psw, just instead of me inviting them, they can register directly.

**Comment by flamber** [comment]
@hawisizu Which means there's no authentication, since anyone can create a user and get a invitation.
You'll be able to create a form that generates users via the API, so they automatically gets an invitation email:
https://www.metabase.com/learn/developing-applications/advanced-metabase/metabase-api.html
But implementing this defeats any security, so I'm not going to reopen. The functionality already exists via SSO, which most companies are using by now.
