### ISSUE TITLE
Compatibility with gravityform for wordpress

### ISSUE THREAD

**Issue by johnfelipe** [metabase/metabase#16025]
https://gfchart.com/
Is something lesser but i think work for now but what about if metabase have in near future compatibility with metabase?
Stay alert

**Comment by paoliniluis** [comment]
Sorry, can you please rephrase your feature request? what do you need specifically?

**Comment by johnfelipe** [comment]
Gravityform is a good addon of WordPress for create forms, and will be good
have compatibility with structure or schematic data in MySQL for example
and create dashboard with questions and pulse in your great webapp
Stay alert.

**Comment by flamber** [comment]
Hi @johnfelipe 
It should work automatically, but every system out there might not being detected perfectly, so you should double check the Data Model: https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html
