### ISSUE TITLE
Change 'Distinct' to 'Count Distinct' in graphical query builder

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16035]
**Is your feature request related to a problem? Please describe.**

The fact that `Distinct` does what `count distinct` does in SQL is confusing: I strongly expected `Distinct` to produce a list of distinct values rather than a count of the number of distinct values, both when choosing it in a Summarize pulldown and (more strongly) when using the function in a custom expression.

**Describe the solution you'd like**

Change the name from `Distinct` to `Count Distinct` or some variation. (I realize this is a breaking change...)

**Describe alternatives you've considered**

Documentation is there, but the name `Distinct` is so suggestive that I assumed I was doing something wrong when it gave me a count instead.

**How important is this feature to you?**

Annoyance-level.

Related #805

**Comment by mazameli** [comment]
Pretty sure we're talking specifically about this case:

![image](https://user-images.githubusercontent.com/2223916/151053345-05e805a4-2f9e-4535-8090-49433e9f84ea.png)

**Comment by astrojuanlu** [comment]
#21108 was merged and this issue was closed, but instead of calling it "Count Distinct", it was called "Distinct Values". Why? I still find "distinct values" confusing (in fact, I was looking for a way to get the values themselves, rather than the count, and I can't find it)

**Comment by astrojuanlu** [comment]
@nimarb unfortunately I didn't, I use raw SQL queries on metabase now a lot.

**Comment by dvirginz** [comment]
We are interested in having unique rows as well.

**Comment by astrojuanlu** [comment]
We'll be more successful opening a new issue I think
