### ISSUE TITLE
Convert React components using `recompose` to functional components and uninstall `recompose`

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16042]
`recompose` is [no longer actively maintained](https://github.com/acdlite/recompose#a-note-from-the-author-acdlite-oct-25-2018), having been made obsolete by React hooks.

## Suggested Steps:
1.  update our components listed below currently using `recompose` to functional components.
2. check if any other component now uses `recompose`
3. once sure `recompose` is not called anywhere, remove it from our dependencies in `package.json` and update the dependency tree. 

Notes:

* A few components are already functional and still use `pure`.
* Consider [React.PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent) and its caveats.

## Components:

- [ ] [CustomGeoJSONWidget.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/settings/components/widgets/CustomGeoJSONWidget.jsx)
- [ ] [QueryButton.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/QueryButton.jsx)
- [ ] [TooltipPopover.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/TooltipPopover.jsx)
- [ ] [SidebarItem.jsx](https://www.github.com/metabase/metabase/blob/master/frontend/src/metabase/components/SidebarItem.jsx)
- [ ] [ListItem.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/ListItem.jsx)
- [ ] [List.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/List.jsx)
- [ ] [TitleAndDescription.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/TitleAndDescription.jsx)
- [ ] [BaseSidebar.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/guide/BaseSidebar.jsx)
- [ ] [MetricSidebar.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/metrics/MetricSidebar.jsx)
- [ ] [FieldSidebar.jsx](https://www.github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/databases/FieldSidebar.jsx)
- [ ] [TableSidebar.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/databases/TableSidebar.jsx)
- [ ] [DatabaseSidebar.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/databases/DatabaseSidebar.jsx)
- [ ] [ReferenceHeader.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/components/ReferenceHeader.jsx)
- [ ] [UsefulQuestions.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/components/UsefulQuestions.jsx)
- [ ] [Detail.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/components/Detail.jsx)
- [ ] [EditableReferenceHeader.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/components/EditableReferenceHeader.jsx)
- [ ] [FieldToGroupBy.jsx](https://www.github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/components/FieldToGroupBy.jsx)
- [ ] [FieldTypeDetail.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/components/FieldTypeDetail.jsx)
- [ ] [EditHeader.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/components/EditHeader.jsx)
- [ ] [Field.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/components/Field.jsx)
- [ ] [SegmentFieldSidebar.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/segments/SegmentFieldSidebar.jsx)
- [ ] [SegmentSidebar.jsx](https://www.github.com/metabase/metabase/blob/master/frontend/src/metabase/reference/segments/SegmentSidebar.jsx)
- [ ] [metadata.js](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/selectors/metadata.js)

**Comment by nemanjaglumac** [comment]
_Disclaimer: I don't fully understand the topic and need to read more about it, so pardon me for possible silly question._

What would be a suggested replacement for `recompose/pure`?
React.PureComponent or React.memo or something else?

**Comment by gusaiani** [comment]
> What would be a suggested replacement for recompose/pure?

@nemanjaglumac, nothing. Just the component. I won't need `pure` any longer.

**Comment by nemanjaglumac** [comment]
While searching for a reason behind `React.createFactory()`, I've stumbled upon multiple topic all leading to `recompose`. Removing it will fix both this issue and #16082.

According to [this article](https://blog.inkdrop.info/some-tips-to-replace-recompose-with-react-hooks-ce99faef6b7f), the replacement for recompose `pure` is `React.memo` and I'm working on a PR to address that. Will push it soon.

All of the listed components use `pure`. Only `metadata.js` is using `shallowEqual`.
