### ISSUE TITLE
Version info and hash missing in 'About Metabase' in master

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#16045]
**Describe the bug**
Clicking on Gear Icon -> About Metabase shows an empty version and git hash.

**Expected behavior**
I expect to see something like "0.40-SNAPSHOT" and a git sha

**Screenshots**
<img width="466" alt="Screen Shot 2021-05-13 at 10 58 16 AM" src="https://user-images.githubusercontent.com/65313/118166620-8b862980-b3da-11eb-8a4a-cac12a1e90b9.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.225-121.362.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "bigquery",
      "redshift",
      "druid",
      "mongo",
      "googleanalytics",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {},
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Comment by flamber** [comment]
Related to #15656 and #15677

**Comment by camsaul** [comment]
How did you build it? Version info is only present if it's built during the build process. If you just did `lein uberjar` it might not be there

**Comment by dpsutton** [comment]
I'm running the ee-uberjar from CI and seeing this:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/6377293/118172354-e1b29700-b3f1-11eb-8921-05da643d6944.png">

```
    "version": {
      "date": "2021-05-13",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "b5f9b61"
    },
```

**Comment by flamber** [comment]
This is stats:
![image](https://user-images.githubusercontent.com/1447303/118172933-40e1cd00-b42d-11eb-92b1-23d299f7433d.png)

**Comment by rlotun** [comment]
I see it on stats and docker (metabase-head)

**Comment by camsaul** [comment]
It seems like it's only happening with multi-stage Dockerfile used to build the head images.

I'm guessing maybe the reason this is happening is because the Docker builder image (first stage of `./Dockerfile`) doesn't have `git` installed (?) so it can't generate version info. Although in that case I'd expect it to fail entirely...

**Comment by camsaul** [comment]
This is a regression introduced with the changes in #15819, on this line: https://github.com/metabase/metabase/blob/master/Dockerfile#L63

We're not running the `version-info` step anymore. When we call `bin/build uberjar` it only runs the `uberjar` step (`bin/build` with no args runs everything). This is only on `master`, not on the release branch.

**Comment by camsaul** [comment]
`translations` is also missing.
