### ISSUE TITLE
Problema no filtro dropdown list

### ISSUE THREAD

**Issue by WeronicaSS** [metabase/metabase#16062]
No Metabase, em uma tabela específica, quando clicamos em filtrar informação de uma coluna, não estamos conseguindo visualizar a listagem de registros na coluna "NOME ETAPA":
![image](https://user-images.githubusercontent.com/33072477/118282308-8a213380-b4a4-11eb-8774-99bdcf068b9f.png)

![image](https://user-images.githubusercontent.com/33072477/118282377-97d6b900-b4a4-11eb-963a-d8455717660c.png)

Porém, para comparativo com outra coluna onde o filtro funciona normalmente - coluna "STATUS", observem que ao clicar em filtrar, é possível visualizar a listagem de registros:
![image](https://user-images.githubusercontent.com/33072477/118283764-15e78f80-b4a6-11eb-92a4-ccd6b2eaeb74.png)

Saberiam como corrigir o filtro na coluna "NOME ETAPA"? Este filtro deveria estar funcionando igual a filtragem da coluna "STATUS".

**Comment by flamber** [comment]
Hi @WeronicaSS 
https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#picking-the-filter-user-interface-for-a-column
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
