### ISSUE TITLE
Viewing schemas in "Browse data" is broken

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#16087]
There's a cosmetic component where the header is missing info:
![image](https://user-images.githubusercontent.com/691495/118325685-cb7c0800-b4d1-11eb-9cd5-87db5d64aea8.png)

More importantly the tables aren't filtered and we display all tables across all dbs!

**Comment by paulrosenzweig** [comment]
@flamber should this be a P1? It's still kinda usable, but with many tables on the instance only barely.

**Comment by flamber** [comment]
Definitely a P1, since it takes 2min before it loads on my computer (got 8k tables) with high CPU. Likely just a frontend issue, since it's requesting `/api/table` instead of previously `/api/database/:id/schema/:name`

**Comment by kulyk** [comment]
Thank you for catching that! Just to make it clear, does it reproduce on `master` or on the release branch?

**Comment by flamber** [comment]
@kulyk master - otherwise it would have been a P0.
