### ISSUE TITLE
Filter field settings grey out for mongodb query

### ISSUE THREAD

**Issue by nevinqj** [metabase/metabase#16098]
I am adding a filter field to a MongoDB query in Metabase. I find that when I add a variable as a filter field `{{variable_name}}`  the variable setting is greyed making it impossible to set a field filter. Below I have attached a screenshot of the issue I am experiencing. I would appreciate any help possible. 

```
[{$match: {
  Mnemonic: {{mnemonic}}
}}, {$sort: {
  Session: -1
}}]
```
![pic](https://user-images.githubusercontent.com/59925306/118375591-97b3e780-b590-11eb-8b7c-eca80d393743.PNG)

**Comment by flamber** [comment]
https://discourse.metabase.com/t/filter-field-settings-greyed-out/14818

**Comment by nevinqj** [comment]
I experience the same issue when I select the table.

![pic2](https://user-images.githubusercontent.com/59925306/118376784-19f3da00-b598-11eb-9e15-48659c1da915.PNG)
