### ISSUE TITLE
Custom expression editor crawls to a halt when the expression is getting longer and longer

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#16094]
**To Reproduce**
1. Ask a question, Custom question
2. Sample Dataset, Reviews table
3. Filter, Custom Expression
4. Type (or better: copy + paste) `contains([Product → Vendor], "Lorem ipsum dolor sit amet") OR` repeatedly

At some point, depending on the machine hardware (I tested at around 40 "copies" of the above subexpression), the editor is noticeably slower. At some further point, it can completely freeze the browser.

![image](https://user-images.githubusercontent.com/7288/118349405-54f8fd80-b505-11eb-912f-f6b7d5cab802.png)

**Expected behavior**

The editor doesn't do any heavy computation. By modern hardware standard, handling the above expression should **not** even break a sweat.

**Comment by flamber** [comment]
On older hardware, you'll even notice slight delays, when adding commas and sometimes quotes just with a small expression with a combination of a couple of functions.
This is not as bad as #12154, so only giving P2 for now, but it makes more advanced expressions difficult (or impossible? #15675)

**Comment by ariya** [comment]
The culprit is that the parser (which needs to produce the syntax tree to infer some typing suggestion and to highlight the expression) exhibits quadratic behavior. When the expression gets longer and longer, it spends way too much time (IMO) for something that should be processed swiftly.

Using the Chrome DevTools Performance Panel to capture the execution samples, while doing the above reproducing steps, yield the following. Note that I'm on a very fast 8-core, 16-thread beefy machine. In most cases, likely the problem is being surfaced much earlier/quicker.

![image](https://user-images.githubusercontent.com/7288/118529077-f647a580-b6f7-11eb-801c-c678336577a4.png)
