### ISSUE TITLE
Filter dropdown sends request for values every time widget is opened

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16103]
**Describe the bug**
From https://github.com/metabase/metabase/pull/15943#pullrequestreview-654993149 - continuation of #13832
When a dashboard has a "A list of all values" filter, every time the dropdown is opened, then it makes a request for values.

**To Reproduce**
1. Simple question > Sample Dataset > People - save as "Q1" to dashboard
2. On dashboard add a category filter and connect to "Q1".Source - save dashboard
3. Refresh the dashboard and click filter widget to open - every click will make a request to get values like this:
```
GET /api/dashboard/:id/params/:paramid/values 200
```

**Expected behavior**
This should probably **not** be fixed until #15977 is fixed, since it could otherwise create a Correctness issue.

The first request is understandable, but subsequent clicks on the dropdown should have stored the results from the first request.
This might be slightly more difficult to do Linked Filters.

**Information about your Metabase Installation:**
Testing commit `aad24de` (almost 0.39.2)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by nemanjaglumac** [comment]
I should probably just rename the repro for 13832 to and reference this issue instead.
