### ISSUE TITLE
Filter dropdown on Embedded dashboard with Locked parameter creates non-sensical queries on data source

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16109]
**Describe the bug**
From https://github.com/metabase/metabase/pull/15943#pullrequestreview-654993149 - continuation of #13832
When an embedded dashboard with Locked parameter has a Editable "A list of all values" filter, then clicking the filter widget will make a query on data source for 100 results every time the dropdown is opened.
But the queries are really strange, like it somehow uses Linked Filters to generate the query.

**To Reproduce**
Using Sample Dataset, but on MariaDB/Postgres, so it's easier to see queries being executed.
1. Simple question > Sample Dataset > People - save as "Q1" to dashboard
2. Simple question > Sample Dataset > Products - save as "Q2" to dashboard
3. On dashboard add a category filter and connect to "Q1".Source, then another category filter connected to "Q2".Category
4. Save dashboard and enabled signed Embedding with Source parameter Locked (set it to e.g. "Facebook"):
![image](https://user-images.githubusercontent.com/1447303/118505031-53f5e500-b72c-11eb-9790-4d476d54886a.png)
5. On the embedded page, click the only filter widget available, Category - it makes queries to the data source every time it's opened - and the query is strange, almost like the filters were Linked Filters
``SELECT `PRODUCTS`.`CATEGORY` AS `CATEGORY` FROM `PRODUCTS` LEFT JOIN `ORDERS` `table_102` ON `PRODUCTS`.`ID` = `table_102`.`PRODUCT_ID` LEFT JOIN `PEOPLE` `table_106` ON `table_102`.`USER_ID` = `table_106`.`ID` WHERE `table_106`.`SOURCE` = 'Facebook' GROUP BY `PRODUCTS`.`CATEGORY` ORDER BY `PRODUCTS`.`CATEGORY` ASC LIMIT 100``

**Expected behavior**
Should use the appdb to get values, which is generally much faster than datasource. And should be memorized.
And should not create such a strange query, when filters aren't Linked Filters.

**Information about your Metabase Installation:**
Testing 0.39.1 and commit `aad24de` (almost 0.39.2)

Related to #16102, but this happens with all dropdowns - and likely friends with #15860 too

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by qnkhuat** [comment]
Fixed in #23699 by storing the list of values in AppDB for locked filters.
