### ISSUE TITLE
Make filter dropdown results consistent across UI and data being scanned

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16104]
**Is your feature request related to a problem? Please describe.**
From https://github.com/metabase/metabase/pull/15943#pullrequestreview-654993149

Currently when Metabase scans a field, it makes a query for 5000 results.
But the UI will maximum show 1000 results (previously 100 #15695 and before that 300? results #7603) on dashboards.

While QB GUI will not show a dropdown, when there's more than 10,000 characters of total distinct values (ex. `select length(string_agg(my_column, '')) from my_table`) are not present in `metabase_fieldvalues` (or if cached field values has never been scanned) - it will display as if the field was "Plain input box"

**Describe the solution you'd like**
1. Decide on a sane value for both scan and UI, which doesn't cause regressions - perhaps 1000 ?
2. If there is more values scanned than what is allowed in the UI, then the UI should use a Search instead of List, since it's otherwise a Correctness issue.

**How important is this feature to you?**
Currently it's a waste to make a query for 5000 results and store those in metabase_fieldvalues and then only use 1000 of those values alphabetically ordered.
And the consistency problem between dashboard filters and QB filters are confusing.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by qnkhuat** [comment]
1. Updated the number of values to scan in BE to 1000 in #23138
2. Should be fixed in #23709. Now when a field exceeds the limit, FE will correctly send a search request to BE upon users input.
