### ISSUE TITLE
Filter dropdown with 10k characters of total distinct values sends query to data source every time dropdown is opened

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16102]
**Describe the bug**
From https://github.com/metabase/metabase/pull/15943#pullrequestreview-654993149 - continuation of #13832
When a dashboard has a "A list of all values" filter, which has more than 10,000 characters of total distinct values (ex. `select length(string_agg(my_column, '')) from my_table`) are not present in `metabase_fieldvalues` (or if cached field values has never been scanned), then clicking a filter widget on a dashboard will make a query on data source for 100 results every time the dropdown is opened.

This happens even if [scanning is disabled](https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#choose-when-metabase-syncs-and-scans) in Admin > Databases > (db) > Scheduling-tab > select "Never, I'll do this manually if I need to" and save.

**Workaround** Admin > Data Model > (db) > (table) > (column) :gear: > change the "Filtering on this field" from "A list of all values" to either "Search box" or "Plain input box"

If you have a lot of tables/fields, then it might be easier to make the change in the application database.
Go to the application database table `metabase_field` and change the column `has_field_values` to `none` or `search`

**To Reproduce**
Using Sample Dataset, but on MariaDB/Postgres, so it's easier to see queries being executed.
1. Admin > Data Model > Sample Dataset > People > City > set as "A list of all values" (dropdown)
2. Simple question > Sample Dataset > People - save as "Q1" to dashboard
3. On dashboard add a category filter and connect to "Q1".City - save dashboard
4. Refresh the dashboard and click filter widget to open - every click will generate a query like this to the data source:
```
SELECT `PEOPLE`.`CITY` AS `CITY` FROM `PEOPLE` GROUP BY `PEOPLE`.`CITY` ORDER BY `PEOPLE`.`CITY` ASC LIMIT 100
```
5. If the instance doesn't have scanned values (e.g. disabled or not scanned yet), then it should make the query to the data source first time, but then the results should be memorized (for disabled) or possibly stored in the appdb `metabase_fieldvalues` table (for not scanned yet), so subsequent requests are faster.

**Expected behavior**
Should use the appdb to get values, which is generally much faster than datasource. And should be memorized.

**Information about your Metabase Installation:**
Testing commit `aad24de` (almost 0.39.2)

Related to #16101 #16104

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
This is indented behavior, that 10k character limit was in the original product designs (I didn't just put it in there for fun). Maybe we should revisit this behavior, but it's currently working as expected.

**Comment by camsaul** [comment]
Ping @brunobergher @mazameli

**Comment by brunobergher** [comment]
If we cached/memorized this in the app DB, is there a predicted schedule we could rely on to refresh it? Upon scan again?
