### ISSUE TITLE
Missing tooltip for sharing individual question

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16108]
**Describe the bug**

Controls in lower right of question have tooltips for everything *except* the arrow for "sharing".

**To Reproduce**

View individual question and mouse over the download icon in the lower right: tooltip appears.
<img width="1440" alt="Screen Shot 2021-05-17 at 10 30 54 AM" src="https://user-images.githubusercontent.com/911566/118506459-5429bc80-b6fb-11eb-9ac2-b11bc7f060fe.png">

Tooltip also appears for "get alerts"
<img width="1440" alt="Screen Shot 2021-05-17 at 10 31 06 AM" src="https://user-images.githubusercontent.com/911566/118506515-60157e80-b6fb-11eb-8cd7-d83a03d658d6.png">

But no tooltip appears for "sharing"
<img width="1440" alt="Screen Shot 2021-05-17 at 10 31 18 AM" src="https://user-images.githubusercontent.com/911566/118506547-686db980-b6fb-11eb-8f8f-5fb390e8ce9a.png">

However, a tooltip appears for sharing entire dashboards
<img width="1440" alt="Screen Shot 2021-05-17 at 10 31 31 AM" src="https://user-images.githubusercontent.com/911566/118506580-702d5e00-b6fb-11eb-8cee-608e80a6dc35.png">

**Expected behavior**

Should be a tooltip for sharing individual questions.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "vUNKNOWN",
      "date": "2021-04-30",
      "branch": "master",
      "hash": "8df9d95"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Chrome Version 90.0.4430.93 (Official Build) (arm64)
- MacOS 11.2.3 (Big Sur) on M1
- Sample database in H2

**Severity**

Annoyance.

**Comment by gusaiani** [comment]
Fixed in #16556
