### ISSUE TITLE
In the Data Model, underlying "real" names for columns/tables should always be visible

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1611]
We should find a subtle way to have the actual underlying schema name for each column and table be accessible/visible even when an admin customizes the label for a given column or table.

**Comment by agilliland** [comment]
@mazameli would you consider this issue resolved by the recent updates to support schemas?

**Comment by mazameli** [comment]
@agilliland I think this is an unfortunately terminology mix up: I don't mean namespaces here, I mean that in the event that you change the display name for a column, you should be able to see what it's actually called in the database's real on-disk schema.

**Comment by agilliland** [comment]
ahhh, yes.  that makes sense.  we definitely need to do that both in the Admin Panel and I would argue in the Data Reference.
