### ISSUE TITLE
ExpressionEditor loses value when user resizes browser window

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16127]
**To Reproduce**

1. Open orders table from a custom question
2. Click on the small grid icon to create custom column
3. Modal will appear and "Field formula" is `contenteditable` field
4. Type `1+1` (without spaces) as a field formula
5. Click on the description field (notice `1+1` got formatted as `1 + 1`) and type "Math" as description
6. Resize the window or open the dev tools
7. All your changes are now gone

**Expected behavior**

Both inputs' values be preserved when window is resized.

**Screenshot:**

![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/qGuE7wk1/babc991e-3429-4b23-9753-7b5d0ac065e3.gif?source=viewer&v=17e697a509ce20d8663a64679d6fb191)

**For more information:**

See https://github.com/metabase/metabase/issues/15734 for related issues and links to adjacent fixes.

**Comment by flamber** [comment]
Fixed by #16157
