### ISSUE TITLE
ExpressionEditor loses value when user clicks away from associated name input

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16126]
**To Reproduce**

1. Open orders table from a custom question
2. Click on the small grid icon to create custom column
3. Modal will appear and "Field formula" is `contenteditable` field
4. Type `1+1` (without spaces) as a field formula
5. Click on the description field (notice `1+1` got formatted as `1 + 1`) and type "Math" as description
6. Go back to the formula and delete the last digit `1` leaving the field as `1 + `
7. Click the name again (let's say you wanted to edit a typo or something)
8. Note that formula got erased together with the name of the CC

**Expected behavior**

Value is preserved when blurring from name input.

**For more information:**

See https://github.com/metabase/metabase/issues/15734 for related issues and links to adjacent fixes.

**Comment by flamber** [comment]
Fixed by #16157
