### ISSUE TITLE
Refreshing an admin page briefly shows 404 message

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16120]
On Firefox 88.0.1 on MacOS, refreshing the page in Metabase Admin causes the "We're a little lost" message to briefly display before the actual page contents load.

https://user-images.githubusercontent.com/32746338/118569097-0da18580-b72e-11eb-9fed-f78bb31a2245.mov

**Comment by nemanjaglumac** [comment]
Happens on Brave as well, so pretty sure it happens on Chrome.
have you tried throttling the network connection to catch it?
