### ISSUE TITLE
Selecting a table from the sidebar in the admin panel metadata page should scroll the content view to the top

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1613]
Right now, when you select a table from a long list of them and you're scrolled far down the page, the scroll position remains static, meaning you have to manually scroll back up. This may mean that the table list and the table detail content section need to scroll _independently_ from each other.

**Comment by salsakran** [comment]
@mazameli do we need to do any specific design here ? Will this add additional chrome in the way of scroll bars to the left pane?

**Comment by mazameli** [comment]
This doesn't need a design, but needs a decision on two possible paths. 

Either:
1. The table list does not scroll independently, but when you click on any table, the browser should scroll to the top of the page. The main downside is that it would mean that if you scroll far down a long list of tables and click on one, you'd have to find your place again if you were trying to riffle through your tables.

Or:
2. The table list does scroll independently from the table detail, and when you click on a table, you'll see the top of the table's details, but the table list will remain in place. The only downside to this would be a scrollbar being added to the list of tables.

FWIW, I personally strongly prefer option 2.

**Comment by flamber** [comment]
I'm not sure when this was changed, but 0.32.9 uses option 1., so clicking a table scrolls to top.

**Comment by mazameli** [comment]
Closing as fixed
