### ISSUE TITLE
Improve usage of Cypress `.type` inside CustomQuestion Popover

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16131]
**Goal, shortly**

To be able to remove or simplify Cypress helper functions `_typeUsingGet` and `_typeUsingPlaceholder`.

**Describe the issue**

At the moment, file 

https://github.com/metabase/metabase/blob/master/frontend/test/metabase/scenarios/question/custom_column.cy.spec.js

relies on workaround helper functions

https://github.com/metabase/metabase/blob/7e69f7444a8540dff400583015aac61555ff1f49/frontend/test/__support__/e2e/cypress.js#L108-L115

and 

https://github.com/metabase/metabase/blob/7e69f7444a8540dff400583015aac61555ff1f49/frontend/test/__support__/e2e/cypress.js#L117-L124

This may be due to the asynchronous nature of ExpressionEditorTextfield, how the value is formatted on the fly and its interactions with the surrounding components.

If we conclude it's possible to change the components so we can use Cypress' `.type` functions directly, even if they require the `delay` option, this may be a significant time-saver for the future — in the future we are certain to misuse multiple person-days testing this feature because we have to chance upon the workaround, or we way invent other workarounds and compound the confusion.

**Comment by nemanjaglumac** [comment]
Fixed in #16164.
