### ISSUE TITLE
Surface table schema names in AP

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1614]
In the admin panel metadata page, we should surface the schema name for a given table to help differentiate them in the case of tables with identical names.

**Comment by pcothenet** [comment]
+1 

(I have 60 tables with the same name. I can only use the raw SQL part)

**Comment by mazameli** [comment]
Pretty sure we can close this with the support we're adding for Redshift/Postgres namespaces, yeah?

**Comment by agilliland** [comment]
agreed.  closing this as resolved in #1759
