### ISSUE TITLE
Metabase: Attempting to call unbound fn

### ISSUE THREAD

**Issue by aalap-jethwa-simform** [metabase/metabase#16147]
Facing below error even if removed cast field:
Attempting to call unbound fn: #'metabase.driver.sql.query-processor/cast-field-if-needed

Initially, we have added cast in sql query by which this error occurred.
But now we have reverted code and removed cast field from sql query and still getting same error.

Does anyone have any idea regarding this issue, please let me know your thoughts.

Thanks

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And provide "Diagnostic Info", which database type you're querying, the query and full stacktrace from Admin > Troubleshooting > Logs.
