### ISSUE TITLE
Blank screen with violating the 'Content Security Policy directive' with another domain

### ISSUE THREAD

**Issue by ohld** [metabase/metabase#16144]
**Describe the bug**

I successfully deployed & used Metabase with test domain for a while. Now I want to migrate Metabase to another domain (for production). I added a domain to Nginx settings and point the traffic to the Metabase docker instance. 

As a result, when I open the new domain I can see the blank screen only. There is an error in browser console logs. I think the old domain is still somewhere inside Metabase config which blocks the new domain functionality. I tried to change "SITE URL" in general Metabase settings but didn't help.

**Logs**
Chrome -> Inspect -> Console logs:
```
Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com  'sha256-lMAh4yjVuDkQ9NqkK4H+YHUga+anpFs5JAuj/uZh0Rs=' 'sha256-sMNbXyc1lLzhHbH/CKs11HIQMnMkZAN2eA99WhJeEC0=' 'sha256-JJa56hyDfUbgNfq+0nq6Qs866JKgZ/+qCq2pkDJED8k='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

Nothing in Metabase logs at that time. 
Nginx logs:
```
162.158.88.207 - - [19/May/2021:11:19:30 +0000] "GET / HTTP/1.1" 200 7763 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.9.760.501 Safari/537.36"
162.158.90.175 - - [19/May/2021:11:19:30 +0000] "GET /app/assets/img/site.webmanifest HTTP/1.1" 200 219 "https://data.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.9.760.501 Safari/537.36"
```
**To Reproduce**

I deployed Metabase via Docker using Dokku PaaS (open-source Heroku) which has an Nginx load balancer under the hood (like Heroku). But I don't think the problem is on Dokku or Nginx side. 

Steps to reproduce:
1. Deploy Metabase, attach the first domain using Nginx
2. Finish the Metabase setup, maybe add some graphs
3. Attach another domain to Metabase instance
4. Open the new domain in the browser  

**Expected behavior**
I want to migrate Metabase to another domain but only the old domain works. 

**Screenshots**
I also tried to replace my old domain with a new domain in General settings but it didn't help.
![image](https://user-images.githubusercontent.com/5613295/118805016-19b45100-b8ae-11eb-98be-03d0daca2fc3.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.506.344 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.0-73-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery",
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6 (Debian 11.6-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v0.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Working on an old test domain is ok for now. But since everyone liked Metabase I need to migrate it to another domain but I failed.

**Comment by flamber** [comment]
Hi @ohld 
You need to disable Rocket Loader - various content-modifying reverse-proxies can causes so many random problems:
https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Comment by ohld** [comment]
@flamber Thanks for the quick reply, but I don't have any browser extensions that modify content. I tried to open a Metabase using several browsers and devices (including mobile) - nothing helped. But If I access a Metabase using the first test domain - everything works fine.

**Comment by ohld** [comment]
Thanks. I found all these settings in domain settings. Thanks.
