### ISSUE TITLE
User avatar font-size resolves to `NaN`

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16148]
**Describe the bug**
User avatar's `font-size` (for user's initials) is busted. Inspecting CSS we can see it's resolved to `NaN`.

**Logs**
N/A

**To Reproduce**
1. Go to `/user/edit_current`
2. Observe that initials inside avatar are really small (visual regression test would've caught this)
3. Inspect it in the dev tools
4. See that the `font-size` is resolved as `NaN`

**Expected behavior**
`font-size` should resolve to the correct value that browser can render.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/118834165-4eca9e80-b8c2-11eb-9dad-07b01a40fb9c.png)

**Information about your Metabase Installation:**
- local dev, both on `master` (can be seen on stats as well) and `release-x39.x` branches, H2, sample dataset

**Severity**
Users are not affected because it eventually falls back to the value that it inherits from the body.

**Additional context**
Tested on 38.4 and 39.0.1 - don't see `NaN`.
To be more precise, I don't see `font-size` being calculated at all
![image](https://user-images.githubusercontent.com/31325167/118833868-17f48880-b8c2-11eb-8b76-d5dea81048b6.png)

I don't get how that's possible since @kdoh added this calculation 2 years ago in #9937
`frontend/src/metabase/components/UserAvatar.jsx`

```javascript
fontSize: ({ size }) => size * 0.75
```

Also, something seems off with the calculation itself. Size resolves (for me) to 5em, which is 70px (since we use 14px as the base font-size). Three quarters of 70 is 52.5px. Try setting font-size to this value manually. It will "stretch" radius of the circle (height/width) will be resolved to more than 200px.

So, has this ever worked correctly?

**Comment by ariya** [comment]
This never worked properly, so we nuked in it #17890.
If it's necessary to have it back (e.g. responsive on mobile form-factor), we need to find a different way to implement it.
