### ISSUE TITLE
Better handling for SSO users without first or last names

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16158]
Currently the `first_name` and `last_name` fields in the MB application db are non-null, and the UI requires both a first and last name when registering a user. However, SSO providers may not provide these fields for a user. This issue is intended for a centralized discussion of how we should handle these cases.

Current behavior: JWT logins use the default `Unknown` for each missing name (so a user with both parts missing is `Unknown Unknown`). LDAP errors, although I have #16139 up right now which changes the behavior to use `Unknown` as well, for consistency w/JWT. Google sign-in also errors according #9418 though I can't repro it as Google accounts now require both first and last names. I haven't investigated SAML yet.

Some options:
* Require first and last name to be provided by SSO, and just surface better error messages for these cases
* Use `Unknown` as a default for all SSO providers for both first and last names (current JWT behavior). Probably confusing for users.
* Store the user's email in `first_name` and store an empty string in `last_name`, so that the frontend displays the user's email in spots that normally show the user's name. Would need to consider what to do if last name is present but first name is not.
* Store empty strings in both fields, and refactor frontend to handle this as a special case wherever a name is expected.
* Make both fields nullable, and refactor both frontend and backend to handle this appropriately.

cc @camsaul @brunobergher @mazameli @kdoh for input

**Comment by brunobergher** [comment]
Thanks for bringing this up. If our goal is to have usable names in the UI, I'm partial to
> Store the user's email in first_name and store an empty string in last_name
which is the closest to accomplishing it.

Overall, I don't think requiring separate first and last names is overall a good idea, but stopping short of removing that requirement, this seems like a good compromise.

I'd like to know from Maz or Kyle if there's more history to this that we should be aware of.
