### ISSUE TITLE
Login blocked till timeout if Metabase can't reach GeoJS API

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#16169]
**Describe the bug**
Slow login longer than 15 seconds

**Logs**
[f6417d0b-8d46-4863-8dfd-e6a8dd6c26c7] 2021-05-20T14:51:23-03:00 ERROR metabase.server.request.util Erro de geocodificação de endereços IP {:url https://get.geojs.io/v1/ip/geo.json?ip=10.3.1.29}
java.net.SocketTimeoutException: connect timed out

**To Reproduce**
1. Go to the login screen
2. Enter credentials
3. Click enter
4. More than 15 seconds to access the home page

**Expected behavior**
The login process used to be instant

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v0.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": "Etc/GMT-3"
    }
  }
}

**Severity**
The user is under the impression that the login screen is not responsive

**Additional context**
>= v0.39

**Comment by paoliniluis** [comment]
It seems to me that Metabase is trying to hit the Geocoding API and can't, so it will wait for the timeout and then allow the login... anyway, the call should be async

**Comment by flamber** [comment]
The slow login can also occur with a slow SMTP.

Scenario. If Metabase instance is hosted internally with a 2Mbit external connection, then the IP lookup could take 2 seconds.
And then if the connection to the external SMTP might take 4 seconds, and the actual SMTP handling could take 2 seconds.
Then a login can take 8+ seconds on unknown devices compared to pre-39.
This brings me back to how internet used to work in Guatemala. Easily reproducible with [tc](https://wiki.linuxfoundation.org/networking/netem#emulating_wide_area_network_delays) and [smtp-sink](http://www.postfix.org/smtp-sink.1.html) on fast connections.

But I'm even seeing 2+ seconds delays sometimes on my test setups, where I login many times every day. On 1Gbit.

Workaround is to disable the lookup (and email notifications) by starting Metabase with the following environment variable:
`MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE=FALSE`
Alternatively is to add `get.geojs.io` to your [hosts](https://en.wikipedia.org/wiki/Hosts_(file)) file, so it points to localhost or another IP that won't answer on https(443). Example line:
```
127.1.2.3       get.geojs.io
```

Related to #15847.
