### ISSUE TITLE
Line Chart not working for mongodb when using Replace Missing Values with nothing or zero

### ISSUE THREAD

**Issue by danimasa** [metabase/metabase#16170]
**Describe the bug**
After updating metabase to v0.39 my Line charts that has X-axis scale set to Timeseries started to present all zero values even if in the data visualization the data is correct. I noticed that it only occurs on data stored in mongo db, I have others charts that gets data from other sources and it was not affected by the problem.

**Logs**
In the server side there is any errors
I noticed the following warnings in the browser console:
![image](https://user-images.githubusercontent.com/6359331/119032338-73864b00-b982-11eb-95ec-093e9f9e3b33.png)

**To Reproduce**
1. Start a new question with data stored in mongo db
2. Sumarize the data from a date column
3. Change the chart type to Line
4. Select "Replace Missing Values" to "Zero" or "Nothing"
5. Every point in the chart goes to zero

**Expected behavior**
The points in the chart that is not zero have to mantain their positions

**Screenshots**
Replace Missing Values = Line Interpolated:
![image](https://user-images.githubusercontent.com/6359331/119032542-ad575180-b982-11eb-9b3f-a8981e36a8a3.png)

Replace Missing Values = Zero:
![image](https://user-images.githubusercontent.com/6359331/119032633-c9f38980-b982-11eb-91ce-1be6b43f3089.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.15.0-143-generic",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "sqlserver",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v0.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
```

- Your browser and the version: Chrome 90.0
- Your operating system: Windows 7 x64
- Your databases: MongoDB 3.6
- Metabase version: v0.39.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
It is a big problem because I lost some important charts for the company that started to present all zero values.

**Comment by flamber** [comment]
Hmmm.... I'm not entirely sure what's going on, but I think it's a field type problem, since Mongo returns `base_type: type/Instant` whereas all(?) other databases returns `base_type: type/Date` - but that was how pre-0.39 did too, but there has been so many field type and dimension changes that I'm unsure if this is frontend or backend issue.

The `xValues missing!` errors in the browser console are strange, since it's clearly getting values.

Regression since 0.39.0

Reproduce:
1. Simple question > Mongo Sample > Orders - summarize Count by CreatedAt:Year (granularity doesn't matter)
![image](https://user-images.githubusercontent.com/1447303/119050974-de577680-b9c2-11eb-8951-238a26517be6.png)
2. Change visualization Settings > Display > "Change missing values with" from "Linear Interpolated" to "Nothing" or "Zero"
![image](https://user-images.githubusercontent.com/1447303/119052348-c08b1100-b9c4-11eb-8852-0a0d73a03499.png)

**Comment by borasy** [comment]
when the data type is instant, we also cannot use it for a click behavior to filter the dashboard as well.

**Comment by camsaul** [comment]
I'm unable to repro this on `master`, so I'm guessing it was inadvertently fixed somewhere else. PR to reenable the test is #17359

**Comment by camsaul** [comment]
Ok, so this is actually still failing... I'll try to figure out how to repro it again.

**Comment by flamber** [comment]
Druid has the same problem, where `base_type` for `type/Instant` gets changed to `type/Text` when binning by i.e. Month or Year.
And when binning by Month, then it's not possible to use Trend visualization either. Trend is possible when binning by Year.
