### ISSUE TITLE
LDAP settings form hitting wrong API endpoint on save

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16173]
It appears that the LDAP settings page is hitting `/api/settings` rather than `/api/ldap/settings`. The latter endpoint validates that a connection to the LDAP server can be established and returns an error if not. This is pretty important to fix since without this validation, it's easy to save invalid LDAP credentials and then only discover the error later. 

We're already trying to map the `updateSettings` prop to `updateLdapSettings` in `SettingsLdapForm.jsx` but this is broken, maybe due to something in `SettingsBatchForm`?
https://github.com/metabase/metabase/blob/f93680ae2be11391e61ebc5a7cdce7f308ef8254/frontend/src/metabase/admin/settings/components/SettingsLdapForm.jsx#L10-L13

I'm comparing this to `SettingsSlackForm.jsx` which does something similar, but doesn't use `SettingsBatchForm`, and it works properly. I don't really know enough about react/redux to diagnose this further.

**To Reproduce**
1. Go to Admin -> Authentication -> LDAP
2. Put in arbitrary settings into the form fields
3. Click "Save changes"
4. Observe in the browser's network tab that `/api/settings` is hit rather than `/api/ldap/settings`

**Expected behavior**
We should be hitting `/api/ldap/settings` and displaying an error if one is returned from the backend

**Comment by noahmoss** [comment]
This actually seems to be true for the email settings component, which also uses `SettingsBatchForm`

**Comment by flamber** [comment]
Very related to #11446 and #13313
