### ISSUE TITLE
Metabase hides existing fields on MongoDB database schema synchronisation 

### ISSUE THREAD

**Issue by icc-romeu** [metabase/metabase#16180]
**Describe the bug**
As it is stated in [the documentation](https://www.metabase.com/docs/latest/administration-guide/databases/mongodb.html#i-added-fields-to-my-database-but-dont-see-them-in-metabase) Metabase only reads the last 200 documents of each collection to get the fields. Metabase synchronises periodically the fields of a MongoDB database. On this synchronisation if the last 200 documents do not include all the fields, Metabase disables the fields.

This happened to me on a big database (30 million documents) with a manual scheduled Database syncing.

**To Reproduce**
1. Add a MongoDB database.
2. Enable "This is a large database, so let me choose when Metabase syncs and scans"
3. Add documents with all the fields to the database. Verify that the data model includes them
4. Add at least 200 documents without some of the fields.
5. Schedule the "Database syncing" 
6. After the Database syncing, the fields not present in the 200 documents are missing from the data model.

**Expected behavior**
Metabase should only add fields, not hide them, at least for MongoDB.

**Information about your Metabase Installation:**

Metabase is installed through a Docker container. This is the troubleshooting info:

```
{
  "browser-info": {
    "language": "en-gb",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.6.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-19",
      "tag": "v0.39.0",
      "branch": "release-x.39.x",
      "hash": "5e40366"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
This prevents new questions to use existing fields in the database, so I have to activate them manually each day

**Comment by flamber** [comment]
Hi @icc-romeu 
This is known limitation with Mongo. You would need to add all the fields to one of the first 10,000 documents (just with null values), then the fields will be kept.
You cannot define manual sync - only scan.
Closing in favor of #4946/#15576

**Comment by icc-romeu** [comment]
Thanks for the fast response @flamber but I did create a document with all the fields with null values with an ObjectID older that ANY of the documents and it keeps occurring. So, any hint of how the field scan sorts documents to search for new fields? Is it a ```sort({_id: -1})```?

BTW: Documentation states "200" documents, not 10,000.

**Comment by flamber** [comment]
@icc-romeu 
There's no sorting during the sync. It's basically just doing `find({})` - it has to be one of the first 10k documents.
Ignore what the documentation says, it's incorrect. https://github.com/metabase/metabase/blob/master/modules/drivers/mongo/src/metabase/driver/mongo.clj#L180-L198
