### ISSUE TITLE
Fix React unsupported style property warning in `NewQueryOption` component

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16188]
**Describe the bug**
React is complaining about unsupported style properties and prints big red console warnings, such as the one in the logs.

**Logs**
```
react_devtools_backend.js:2560 Warning: Unsupported style property min-height. Did you mean minHeight?
```
**To Reproduce**
1. Go to `/question/new`
2. Search console for "min-height" and notice the big red warning

<details>
  <summary>Click to expand the full log</summary>

```
react_devtools_backend.js:2560 Warning: Unsupported style property min-height. Did you mean minHeight?
    in a (created by Link)
    in Link (created by NewQueryOption)
    in NewQueryOption (created by NewQueryOptions)
    in div (created by Clean.div)
    in Clean.div (created by Box)
    in Box (created by GridItem)
    in GridItem (created by NewQueryOptions)
    in div (created by Clean.div)
    in Clean.div (created by Flex)
    in Flex (created by Grid)
    in Grid (created by NewQueryOptions)
    in div (created by Clean.div)
    in Clean.div (created by Box)
    in Box (created by NewQueryOptions)
    in NewQueryOptions (created by Connect(NewQueryOptions))
    in Connect(NewQueryOptions) (created by NewQueryOptions)
    in NewQueryOptions (created by Title[NewQueryOptions])
    in Title[NewQueryOptions] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
```
</details>

**Additional context**
This topic https://github.com/facebook/react/issues/11315 discusses the removal of mentioned warnings and gives a reasoning behind implementing them in the first place.
> even though the blacklist behavior is more lenient React still warns when using the non-canonical names for attributes it recognizes. For example, you can use `class` instead of `className`, but you'll still get a warning because `className` is the canonical name of the attribute.

> We are trying to encourage consistency so that third party components don’t feel obligated to support all kinds of patterns at the same time. This is better for the ecosystem because people don’t have to argue about conventions. We feel that `camelCase` works best because at some point you’re doing to wrap logic in components, or read props before passing them down, or add your own similarly named props, and `camelCase` is the most natural convention for doing this in JS.

**Next steps**
It is up to use to agree upon a convention and use it consistently. If we want to remove all these warnings, we'd have to use the allowed convention which is `camelCase`.

**Comment by gusaiani** [comment]
`camelCase` +1
