### ISSUE TITLE
Dashboard Contains filter doesn't remain when clicking on Question title

### ISSUE THREAD

**Issue by JayJayM** [metabase/metabase#16181]
**Describe the bug**
On the new dashboard string filters options,  when using "contains", when clicking on a Question title (at least for SQL questions) on the dashboard to open it, the filter doesn't remain a "contains" one and switch to "equal" as you can see on this recording, which will lead to different results (or literally no result).

**Logs**
No log

**To Reproduce**
1. Add a String "contains" filter on a dashboard
2. Add a SQL Question as a tile of this dashboard and make it listen to the "contains" filter
3. Add a value to this filter (the tile/Question values will change based on it)
4. Click on the title of the SQL Question from the dashboard
5. You will see that the SQL Question opens with the filter value being an "equal"

**Expected behavior**
The Question should open and the filter should be a "contains"

**Screenshots**
![Screen+Recording+2021-05-18+at+11 26 28+AM](https://user-images.githubusercontent.com/8995276/119111177-1ababf00-ba23-11eb-9443-8bc15da9deec.gif)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1",
    "os.name": "Linux",
    "os.version": "5.4.0-1045-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "redshift",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-07",
      "tag": "v0.38.3-SNAPSHOT",
      "branch": "?",
      "hash": "c70590d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Very annoying: Preventing users from drilling down from a dashboard

**Comment by nemanjaglumac** [comment]
I might be wrong, but from the screenshot it seems you didn't press "Update filter".

**Comment by flamber** [comment]
Requires filter feature flag.

**Reproduce**
1. Native query > Sample Dataset > `select count(*) from products where {{filter}}` and set filter as Field Filter with "Filter widget type"="String" (not contains!) - save as "Q1"
![image](https://user-images.githubusercontent.com/1447303/121079837-f577d000-c7da-11eb-8db5-30b7ea5e81f0.png)
2. Add "Q1" to dashboard, and add filter "Text or Category" > "Contains" and connect to "Q1" - save dashboard
3. Search for `bb` in the filter widget - result should be **12**
![image](https://user-images.githubusercontent.com/1447303/121080473-c1e97580-c7db-11eb-8004-8598e75768a6.png)
4. Click question title to drill-through - it correct sets the filter to `bb` on the question, but result is **0**
![image](https://user-images.githubusercontent.com/1447303/121080359-9cf50280-c7db-11eb-9358-1664ceba2753.png)
