### ISSUE TITLE
Server should exit if it can't be started

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1618]
For example if the port is already in use we get an error message but the process doesn't exit:

```2015-12-02 12:57:14,588 [ERROR] metabase.core :: Metabase Initialization FAILED:  Address already in use```

**Comment by camsaul** [comment]
when you run from `lein ring server` it just picks the next port (e.g. `3001`) and so forth until it finds a free one

Are you launching from the uberjar?

**Comment by tlrobinson** [comment]
Yes, uberjar.

**Comment by agilliland** [comment]
This is likely happening because we start Jetty on a different thread now and then attempt to re-join it later.  My guess is that when Jetty fails to start we re-join a thread that's not doing anything, so we just sit there.

**Comment by camsaul** [comment]
if Metabase initialization fails we can just call `(System/exit -1)` and that will kill the Jetty thread. I was seeing this same problem on tests and added code to do that a while back
