### ISSUE TITLE
Revoking access to users in multiple groups does not correctly cleanup GTAP

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16190]
**Describe the bug**
Revoking access to users in multiple groups does not correctly cleanup GTAP

**To Reproduce**
1. Admin > People > Groups > create two groups, TestGroup1, TestGroup2
2. Admin > People > create TestUser1, and assign the two groups. Also add attribute to user, ex: `user_id` : `1`
3. Admin > Permissions > Sample Dataset > Orders > TestGroup1 > Grant sandboxed access > "User ID" = `user_id`
4. See metadata table `group_table_access_policy` now contains the permission
5. Now, revoke access again for TestGroup1
6. `group_table_access_policy` still contains the permission
7. Repeat step 3, but for TestGroup2
8. `group_table_access_policy` now contains two permissions
9. Login as TestUser1 and try to access Sample Dataset > Orders, results in error:
`Found more than one group table access policy for user 'test1@test.test'`

Current workaround is to manually delete the old policy from `group_table_access_policy`

Example of query that will remove all orphaned GTAPs - make sure to backup before running!
<details>

Written for Postgres - run the query inside of the checker-comment to see what will be remove before running the full delete query.
```sql
DELETE
FROM
  group_table_access_policy
WHERE
  id IN (
    -- checker:begin
    SELECT
      GTAP.id
    FROM
      group_table_access_policy AS GTAP
    WHERE
      0 = (
        SELECT
          count(*)
        FROM
          permissions AS p
        WHERE
          p.group_id = GTAP.group_id
          AND p."object" LIKE concat('%/', GTAP.table_id, '/query/segmented/')
      )
    -- checker:end
  )
```

</details>

**Information about your Metabase Installation:**
Tested 1.34.4 thru 1.39.2

Originally EE249 - https://github.com/metabase/metabase-enterprise/issues/249

**Comment by camsaul** [comment]
Fixed by #16222
