### ISSUE TITLE
No error is reported when adding SQLite database that doesn't exist

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16199]
**Describe the bug**
When adding a SQLite database, if you make a typo in the filename or path and point Metabase to a non-existent database file, no error is reported. Instead, Metabase says "Your database has been added!" but it hangs indefinitely when trying to generate an X-ray.

**To Reproduce**
1. Go Admin -> Databases -> Add database
2. Change database type to SQLite
3. Type in an arbitrary path to a non-existent file, and save changes
4. Click "Explore this data"
5. Observe that Metabase hangs on the loading bar and never generates an X-ray or displays an error 

**Expected behavior**
Metabase should probably be able to detect that a SQLite file doesn't exist and show an error message when trying to add the DB. This stumped me for a solid 15 minutes when I was trying to add a personal SQLite DB to Metabase, until I realized I made a typo in the file path.

**Information about your Metabase Installation:**
v0.39.1 on Firefox with a Postgres application DB

**Comment by flamber** [comment]
Most likely because Metabase creates an empty file with the typo.
