### ISSUE TITLE
Allow configuration of connection hints (like virtual foreign keys)

### ISSUE THREAD

**Issue by squiddle** [metabase/metabase#1619]
Let's say we have two tables which could have foreign key constraints set up but for reasons outside of metabase this cannot be done. It would be nice if there would be a way to set up sth. like connection hints.

That way I (as an administrator) specify that this field has a foreign key relation to another field and it would show up in the connections view to be discoverable for users. 

This could also later be reused in whatever UI/UX is planned for constructing joins.

**Comment by squiddle** [comment]
found it...

**Comment by mazameli** [comment]
It's useful (albeit unfortunate) to know you found this difficult to locate, though.
