### ISSUE TITLE
Adjust vertical positioning beween  'Add a time' button and time pickers in date/time picker

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16211]
⚠️ Not clear to me how to bring in designers to make the call here. Below are my suggestions. Very simple imo.

### Steps to Reproduce

1. Go to http://localhost:3000
2. Click on `Ask a question`
3. Click on `Custom question`
4. Click on `Sample dataset`
5. Click on `People`
6. Click on `Add filters to narrow your search`
7. Click on `Created at`
8. From dropdown defaulted to Previous, select `Between`
9. Click on either of the `Add a time` buttons

My suggestion is to move the time pickers up enough that the visual relationship of the buttons and the pickers is nice.

If we nudge down the `Add a time` button, they will separate too much from the date pickers above, making it less clear visually that they are related.

### Context

![image](https://user-images.githubusercontent.com/380816/119377427-7e4b2380-bc93-11eb-88e3-5dea4a185783.png)

**Comment by brunobergher** [comment]
Got it, it's a different state. Let me think about this one.

**Comment by brunobergher** [comment]
Doesn't happen with the new filter widgets.
