### ISSUE TITLE
Password login on SSO instance drops the redirect URL

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#16216]
I think this is a regression, pretty sure it was working at some point.

To reproduce:

1.  Be logged out on stats
2. Click link to `https://<stats>/dashboard/223-engineering`
3. Login with email
4. You're taken to the home page, rather than the dashboard

**Comment by flamber** [comment]
Related (or perhaps the same as) to #14781.
It's very important to click the "Sign in with email" in step 3, which changes the URL from `/auth/login?redirect=%2Fdashboard%2F223-engineering` to `/auth/login/password` (dropping the `redirect` parameter)
So this is only reproducible with SSO (excluding LDAP) enabled, but logging in through email+password.
