### ISSUE TITLE
LDAP validation doesn't work if top level LDAP authentication is disabled

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16225]
**Describe the bug**
LDAP validation doesn't work if top level LDAP authentication is disabled (toggle is set to `off`). This is extremely weird and bad UX. 

**To Reproduce**
1. Go to `/admin/settings/authentication/ldap`
2. Enter literary anything for the host name
3. Make sure you enter strictly numeric port (validation seems to be working only for port and will fail if port is non-numeric, regardless of the authentication being enabled/disabled)
4. Notice that "Save changes" button is enabled
5. Click it and save the changes
6. You will see "Changes saved" (PUT to the `/api/ldap/settings` request goes through and returns `200`)

```javascript
// response
{
  "ldap-enabled": false,
  "ldap-host": "dqwdw",
  "ldap-port": "342573",
  "ldap-security": null,
  "ldap-bind-dn": "",
  "ldap-password": "",
  "ldap-user-base": null,
  "ldap-user-filter": null,
  "ldap-attribute-email": null,
  "ldap-attribute-firstname": null,
  "ldap-attribute-lastname": null,
  "ldap-group-sync": false,
  "ldap-group-base": null,
  "ldap-group-mappings": {},
  "ldap-sync-admin-group": false,
};
```

7. Toggle the authentication to ON
8. Try to save changes again
9. It will not correctly show errors
![image](https://user-images.githubusercontent.com/31325167/119479034-8917be00-bd50-11eb-8ce9-e94b01c6e0cf.png)
10. The toggle automatically turns authentication off and you can again save non-sensical values without validation

**Expected behavior**
Either completely disable all input fields until toggle (authentication) is enabled, or 
Remove the toggle or
Don't offer to save field values until toggle (authentication) is enabled

**Information about your Metabase Installation:**
local dev, `release-x.39.x` (13768bd) - this includes fixes from #16187

**Severity**
Not sure?

**Additional context**
- https://github.com/metabase/metabase/pull/16187#issuecomment-847243900
- We should move Authentication on/off toggles out of their config forms #5555
- Not sure if this makes #11446 fixed or not?

**Comment by ranquild** [comment]
This issue requires backend changes as specified here https://github.com/metabase/metabase/issues/19428

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/issues/19428
