### ISSUE TITLE
Components using styled components don't always render 

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16221]
Oftentimes, components written using styled-components don't get rendered.

This issue is deterministic: they either are never rendered in a given situation, or they are always rendered.

Having them working as expected will help decouple presentation from logic in our UI components — and arguably increase the overall quality of our codebase by a lot.

## Steps to reproduce the behavior:

Create a new component using `styled-components`, or convert an existing component to use `styled-components`.

Render it on the page.

It won't be long before you see one silently not be rendered.

## Expected behavior

Components using styled-components should reliably get rendered.

**Comment by kulyk** [comment]
Closing since we've migrated from `styled-components` to `emotion` and haven't seen this pop up anymore AFAIK
