### ISSUE TITLE
LDAP/Email settings gets cleared if validation fails

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16226]
**Describe the bug**
Any LDAP setting that comes **after** LDAP port seems to get erased if authentication toggle is off (#16225) and if port validation fails (non numeric value).

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to /admin/settings/authentication/ldap
2. Enter literary anything for the host name
3. Enter some non-numeric value for the port
4. Fill out all subsequent ldap settings
5. Click "Save changes" button
```javascript
// PUT request is fired to /api/ldap/settings but it fails with `500` code
// console log settings.js:140
// error updating LDAP settings
{
  via: [
    {
      type: "java.lang.NumberFormatException",
      message: 'For input string: "dasdas"',
      at: [
        "java.lang.NumberFormatException",
        "forInputString",
        "NumberFormatException.java",
        65,
      ],
    },
  ],
  trace: [/* omitted because of length */],
  cause: 'For input string: "dasdas"',
  message: 'For input string: "dasdas"',
};
```
6. You will see not very helpful error above it (`For input string (whatever you entered in the step 3)`)
7. Notice all input fields expect the host name get erased after this error
8. Error from step 6 persists in the UI until the next save (which also seems wrong)

**Expected behavior**
Errors shouldn't erase already filled out settings.
Ideally, we should have some frontend validation in order to avoid hitting the backend with misconfigured settings.

**Information about your Metabase Installation:**
local dev, release-x.39.x (13768bd) - this includes fixes from #16187

**Severity**
Not sure will this happen when #16225 gets fixed. Probably P3.

**Comment by flamber** [comment]
Changing priority, since this is insanely annoying, when making one tiny typo, then everything is cleared during a new setup.
Also happens in the Email form, so it's not just LDAP, but likely the logic behind the validator introduced in #16187.
