### ISSUE TITLE
Drag functionality not working in dashboard visualization options modal

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16229]
**Describe the bug**
It's not possible to drag element in dashboard visualization options modal. Regression since 0.39.0

**To Reproduce**
1. Simple question > Sample Dataset > Products - save as "Q1" and add to dashboard
2. On dashboard in Edit-mode, hover the card and click :palette: (Visualization options)
3. Under "Visible columns" try to drag any of the columns - nothing happens and no browser console errors.
Same problem under Conditional Formatting with multiple conditionals.
![image](https://user-images.githubusercontent.com/1447303/119508807-57aeea80-bd70-11eb-830d-16cf9e4698ea.png)

**Information about your Metabase Installation:**
Tested 0.38.4 thru 0.39.2 - regression since 0.39.0

**Additional context**
It's still possible to drag columns/conditionals in the question, but depending on permissions, this might not be an option.

**Comment by kulyk** [comment]
Spent a few hours researching the issue. Couldn't find a simple solution yet, so just sharing my findings here. Dashboard visualization options are displayed in a modal. The modal uses [`SandboxedPortal`](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/SandboxedPortal.jsx) component that stops mouse events propagation, and that's the reason why `react-sortable-hoc` can't handle dragging. Still, if you enable mouse events back, they'll propagate to the dashboard itself. In that way, the user's drag will also move dashboard cards as it's in editing mode (see [React docs](https://reactjs.org/docs/portals.html#event-bubbling-through-portals)). Possible workaround is to disable dashboard dragging when the modal is open, but it's not a really solid solution
