### ISSUE TITLE
Tooltip of combined dashboard cards does not show the correct column title

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16249]
**Describe the bug**
When combining two cards on a dashboard, and changing the series name on the dashboard, then it shows the first series name in the tooltip for both series. When using CE, then it doesn't change the name for the second series.
Continuation of #11395, but for dashboard combined cards. Regression since 0.38.3.

Note for developers: Any reason why the tooltip is only showing values for a single question, when combined? Normally with multi-series, it would show all the series values, but perhaps this is a limitation, when combining.

**To Reproduce**
1. Create 4 questions - Custom question > Sample Dataset
   1. Orders - summarize CE `Sum(Total)` called `CE` group by CreatedAt:Year - save as "Q1"
   2. Orders - summarize CE `Average(Subtotal)` called `CE` group by CreatedAt:Year - save as "Q2"
   3. Orders - summarize "Sum of Total" group by CreatedAt:Year - save as "Q3"
   4. Products - summarize "Sum of Price" group by CreatedAt:Year - save as "Q4"
2. On a dashboard. CE-test:
   1. Add "Q1"
   2. Hover the "Q1" card and click "Add series" and add "Q2"
   3. Hover the combined Q1+Q2 card and click "Visualization options"
   4. Change the names of the series to something unique for each series
3. Hover the lines of the Q1+Q2 card
![image](https://user-images.githubusercontent.com/1447303/119690620-2276cb00-be4a-11eb-9c62-62068f394729.png)
4. Do the same as step 2 again, but using Q3 and Q4 instead of Q1 and Q2
5. Hover the lines of the Q3+Q4 card
![image](https://user-images.githubusercontent.com/1447303/119690780-46d2a780-be4a-11eb-833e-893994388b2d.png)

**Information about your Metabase Installation:**
Tested 0.38.2 thru 0.39.2 and commit `0401256` (almost 0.39.3) - regression since 0.38.3

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ranquild** [comment]
@flamber I couldn't reproduce the bug on `0.40.x` with the steps above. Could you please confirm if the issue still exists?

**Comment by flamber** [comment]
@ranquild It only works for the series on the first question, not the series from the second+ question. Likely very related to #13095 (WIP #16659). I can reproduce on 0.40.1 and `master`. You can always run the test #16263 if you think it's fixed.
![image](https://user-images.githubusercontent.com/1447303/126797918-6ec891bb-ca81-4bca-9922-f53447610720.png)
![image](https://user-images.githubusercontent.com/1447303/126798085-774f76ba-c5cb-4ceb-9193-5ad253bdaab7.png)

**Comment by ranquild** [comment]
The fix https://github.com/metabase/metabase/pull/18227 was reverted due to some unforeseen issues, reopening the issue.
