### ISSUE TITLE
Provide "browse to" button when connecting to SQLite database

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16256]
When a user connects Metabase to a SQLite database they are asked to provide the path to the SQLite DB file. Metabase should provide a "browse to" button that launches a file browser so that they can navigate to the file graphically. (Novice users who have downloaded a SQLite dataset for a training course will often not know how to write out the path to their download folder as text.)

This is a low-priority feature, but will make teaching with Metabase slightly easier.

**Comment by flamber** [comment]
That would be quite difficult (if not impossible) and very dependent on how Metabase is hosted. A website cannot receive information about the file's localpath from "browse to", and uploading the SQLite would also be complicated.

**Comment by flamber** [comment]
@ariya So to allow Metabase (the backend) to list directories/files, so the user can select that in the UI? That seems like something that makes my security-senses tingle.
Perhaps we could have X amount of test dbs, which can be downloaded and setup with a single click. The download file would be "stored" in temp (whatever JAVA_TMP is, which is how XLSX exports are delivered too). Still seems like a lot of work.
Another option, a Docker image already pre-filled with a several DBs and already defined dashboards and questions.

**Comment by gvwilson** [comment]
1. Instructors are going to want to be able to distribute their own datasets.
2. Anyone with enough tech chops to use Docker will almost certainly be able to type in a path to a file (i.e., won't need this feature).

As an alternative, if the user enters a URL instead of a file path, can we download the SQLite DB file, put it somewhere other than their Downloads directory, and replace the URL with the filepath?

**Comment by ariya** [comment]
> @ariya So to allow Metabase (the backend) to list directories/files, so the user can select that in the UI?

Probably just front-end tweaks, no need to change the back-end, by using [input type=file](https://html.spec.whatwg.org/multipage/input.html#file-upload-state-(type=file)).
