### ISSUE TITLE
Leftover rows in permissions not being deleted when changing perms -> unrestricted access

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#16253]
From #16222:

> :beach_umbrella: :black_square_button: :broom: 
> 
> Okay, it's much saner now. But it doesn't cleanup this scenario. It doesn't seem to cause any problems, but I'm thinking that you probably don't want to leave left-overs.
> 
> 1. Admin > Permissions > revoke all access to Sample Dataset
> 2. Go to table Orders > "Grant SANDBOXED access" with User ID=user_id and Save and Save Changes, so it creates a row in `gtap` and two in `permissions`
> 3. Now change Orders to "Grant UNRESTRICTED access". It correctly removes the `gtap`, but it leaves two rows in `permissions` and adds another.

This shouldn't cause any problems because it should see the less-restrictive permissions and ignore the more-restrictive ones. But we should still clean up after ourselves... labelling this P3

**Comment by camsaul** [comment]
Going to prioritize fixing this because it's making the new 43 EE perms stuff we're working on hard to implement

**Comment by qnkhuat** [comment]
I can't reproduce this one as of `2bdb06c61c2159e052677e764624aa954a7c9d42`, seems like it's already resolved?

**Comment by flamber** [comment]
Fixed during one of the many changes to permissions in 43 - I cannot reproduce on master, but can reproduce on 1.42.4
