### ISSUE TITLE
Performance got slow after upgrading to 0.39.2

### ISSUE THREAD

**Issue by toan-hf** [metabase/metabase#16257]
**Describe the bug**

We recently upgraded the Metabase to 0.39.2 and immediately encountered the slow response time on every queries. 
Usually those queries consumed less than 30 seconds however now all of them got timeout. 

Beside of several errors related `"Error reducing result rows"`- We also encountered that CPU usage increased dramatically. 
Usually it consumed less than 2 cores but now it has reached to 7 cores (even more if We changed our instance type to higher, it will consume as much as possible)

**Architecture**

Currently, We deployed in K8s (1.19) GKE. 
However due to the performance decreased We have setup dedicated instance and set up the app running under Docker. 

We also using Nginx Ingress as reverse Proxy for Metabase app. With the separated instance (32 cores), All queries now are operational _(even it is still a bit slow comparing to before we did the upgrade)_

**To Reproduce**
Just upgrade to 0.39.2

**Expected behavior**
Better performance for all the queries 

**Screenshots**
![image](https://user-images.githubusercontent.com/57263227/119727174-48b06100-be72-11eb-98c2-454acf83519a.png)

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.89+",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v0.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
This issue blocked our operation actually, We have around 20 peoples used to use MetaBase for their own operation (analysis - statistic - report)

**Comment by flamber** [comment]
@toan-hf You need to specify which version you upgraded from.
Check the logs to see what Metabase is doing - from console or Admin > Troubleshooting > Logs.

**Comment by toan-hf** [comment]
@flamber  we upgraded from 0.38.5 to 0.39.2 . 
fortunately we have a backup before doing the upgrade so We just rolled back and everything work pretty fast now

Thanks a lot for your prompt reply

**Comment by raj-saxena** [comment]
@toan-hf https://github.com/metabase/metabase/issues/13572 seems related for sub-queries
