### ISSUE TITLE
link to database docs from add database 404's

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#16269]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/6377293/119872891-90260400-bee9-11eb-84f6-f7c232524b10.png">

These links 404 for me:
https://www.metabase.com/docs/vUNKNOWN/administration-guide/databases/bigquery.html
https://www.metabase.com/docs/vUNKNOWN/administration-guide/databases/mongodb.html

Running a jar built from the latest commit (here: https://github.com/metabase/metabase/actions/runs/882244861)

Probably low impact as releases won't suffer from this so marking as P2.

**Comment by flamber** [comment]
Duplicate of #15219
