### ISSUE TITLE
Better display values for coercions in dropdown

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#16270]
make coercions display nicer

I.e., UNIX Seconds → Datetime instead of UNIXSeconds->DateTime
And YYYYMMDDHHMMSS String → Datetime instead of `YYYYMMDDHHMMSSString->Temporal

<img width="343" alt="image" src="https://user-images.githubusercontent.com/6377293/119874780-9917d500-beeb-11eb-99e7-42b6be0996bf.png">

**Comment by flamber** [comment]
Closing in favor of #16547
