### ISSUE TITLE
Cannot filter only on longitude/latitude range - UX is forcing user to fill out values for both fields

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16291]
**Describe the bug**
The UX around filtering `inside` longitude or latitude is quite illogical in that it forces you to use both columns to be able to add filter.

**Logs**
N/A

**To Reproduce**
1. New custom question > Sample Dataset > People
2. Click on the **Longitude** header cell
3. Click on "Filter by this column
4. Choose `inside` type of filter
5. You will be presented with the four filters in total (upper/lower latitude, left/right longitude)
6. Without filling out all four fields, it is impossible to add filter

**Expected behavior**
Show only the related filter values.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/120175398-7bf24780-c206-11eb-80f9-81d583ec76b7.png)

**Information about your Metabase Installation:**
local dev > release 39, H2, Sample Dataset

**Severity**
P3, UX

**Comment by flamber** [comment]
I think the "Inside" operator is correct, but perhaps we should include others like "Between", "Greater than", etc.
Workaround is to use Custom Expression
