### ISSUE TITLE
A lot of big queries sent to Druid after create druid connection

### ISSUE THREAD

**Issue by ShineLiu** [metabase/metabase#16300]
**A lot of big queries sent to Druid after create druid connection
After druid connection is created, a lot of big queries are sent to Druid. All of these requests contain 200-years-query (from 1901 to 2100), which will our druid broker can't work withour enough memory.
  Have you encountered this issue?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And remember to include "Diagnostic Info" from Admin > Troubleshooting.
