### ISSUE TITLE
Double binning menu for date fields when using Saved Question (Native)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16327]
**Describe the bug**
This is a reprise of #15446, but specific to when base is a Native question.

**To Reproduce**
1. Native query > Sample Dataset > `select * from products` - save as "Q1"
2. Custom question > Saved Questions > "Q1"
3. Summarize Count by CreatedAt - click the binning menu, notice all options are duplicated (upper and lower).
Selecting any of the options in the upper-part will be dropped when clicking Visualize (similar to #15725)
Had to zoom out a bit to completely show all options.
![image](https://user-images.githubusercontent.com/1447303/120541932-cc29ff00-c3ea-11eb-88ba-739633f6fc3a.png)
4. Select one of the options from the lower-part and click Visualize
![image](https://user-images.githubusercontent.com/1447303/120542393-583c2680-c3eb-11eb-8820-a2c2599e6866.png)
5. On Simple view, it does not mark which option is selected, but also here only the lower-part of options should be used.
Selecting any of the options in the upper-part will cause the same problem as #15397/#15725
![image](https://user-images.githubusercontent.com/1447303/120543012-165fb000-c3ec-11eb-9470-8718d3eb66dd.png)

**Information about your Metabase Installation:**
Tested 0.38.4 thru 0.39.3 - regression since 0.39.0

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by gvaibhavraj2** [comment]
@flamber When is this expected to release?

**Comment by flamber** [comment]
@gvaibhavraj2 I cannot give you a date on that. It is a lot more complicated than expected. Read the referenced issues and PR.
