### ISSUE TITLE
"Custom mapping" is only available, when "A list of all values" is set (and after a browser refresh)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16322]
**Describe the bug**
When trying to set "Display values" = "Custom mapping" on an integer field, then remapping is only available if "Filtering on this field" = "A list of all values" and then doing a browser refresh.

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Reviews > Rating :gear:
2. Set "Filtering on this field" to "Search box" or "Plain text input" and do a browser refresh:
![image](https://user-images.githubusercontent.com/1447303/120476611-0e335080-c3ab-11eb-95ab-d0ca253be58a.png)
3. Now set it to "A list of all values" and do a browser refresh:
![image](https://user-images.githubusercontent.com/1447303/120476483-eba13780-c3aa-11eb-8ac7-17684aba4c9f.png)

**Expected behavior**
"Custom mapping" should available no matter which "Filtering on this field" is used. And no settings should require a browser refresh before showing.

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.39.3

**Severity**
Might be a P3, but giving P2, since it's not very intuitive and combined with "Custom mapping" only supporting integers (#11445), then it can be difficult to understand how to actually set mapping.
And also because it took me almost an hour to figure out what was going on.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by WiNloSt** [comment]
@flamber regarding
> "Custom mapping" should available no matter which "Filtering on this field" is used

I don't think this is can be done only on FE.

See the response from `api/field/31/values` (Rating field) below

#### "A list of all values" is selected
![image](https://user-images.githubusercontent.com/1937582/159926095-6de1662f-f6f0-43db-85a3-0c38127ac124.png)

#### "Search box" or "Plain input box" is selected
![image](https://user-images.githubusercontent.com/1937582/159926470-ebc8b3f5-e996-48f8-ad7d-a12c2d99176c.png)

You can clearly see that they're different and that difference is what influcence whether the `Custom mapping` would be visible
https://github.com/metabase/metabase/blob/b78c9832672446554c0dc52be163a09d97babaf0/frontend/src/metabase/admin/datamodel/components/FieldRemapping.jsx#L65-L71

For this issue, I can only try to make the change take effect immediately without a browser refresh. Should I go ahead with that?

**Comment by flamber** [comment]
@WiNloSt Yes, let's do the refresh fix. I'm guessing that we would need a larger change (and possibly #14676 too) for the other.
