### ISSUE TITLE
Revision history messages aren't human-readable

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#16326]
Some of our revision history entries on saved questions and dashboards read like this:

`changed collection_id from "2" to "201" and changed read_permissions from "[]" to "null".`

That's supposed to represent someone moving the question from one collection to another, but it's not friendly at all. I'm not sure what's going on with the "read_permissions" part precisely, but I'd expect the rest of that entry to read more like this:

`Moved this from "Test Collection" to "Real Great Folder."`

Here's another one:

`changed display from ":table" to ":area".`

That should be:

`Changed the visualization from Table to Area.`

An example from a dashboard:

`removed a card and added some series to card 295.`

What question is "card 295"? We'd prefer:

`Removed a question and added some series to "Daily Active Users".`

I'm not going to list each and every message here, but hopefully this is illustrative enough of the problem and the general shape of the solution.

**Comment by brunobergher** [comment]
I'd call this overall solved, it hasn't come up again in a few years, afaik.
