### ISSUE TITLE
Group by on a `:Coercion/YYYYMMDDHHMMSSBytes->Temporal` postgres column fails

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#16335]
Setup:

postgres table

```sql
create table wut2 (t bytea, ts text);
insert into wut2 (t, ts) values ('20210421164300'::bytea, '20210421164300');
```

In Admin > data model, mark wut2.t as `:Coercion/YYYYMMDDHHMMSSBytes->Temporal` and wut2.t2 as `:Coercion/YYYYMMDDHHMMSSString->Temporal`. A simple question should now work and these appear as date times:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/6377293/120666529-4a6dbc00-c452-11eb-9d23-3dbc5f55f555.png">

Open up the aggregations pane and aggregating by `t2` (the string column should work).

Aggregating by `t` (the byte column) throws an error
<img width="725" alt="image" src="https://user-images.githubusercontent.com/6377293/120666852-8b65d080-c452-11eb-9242-5e55ea0c9b4a.png">

The problem comes from the query generated:

For my column ids, 
```clojure
(-> (qp/process-query {:database 6
                       :query {:source-table 347
                               :aggregation [["count"]]
                               :breakout [["field" 1782 {:temporal-unit "day"}]]}
                       :type "query"
                       :parameters []})
    (update-in [:data :rows] count))
```

throws the error and generates this sql:
```sql
SELECT CAST(to_timestamp(convert_from(\"public\".\"wut\".\"t\", ?), 'YYYYMMDDHH24MISS') AS date) AS \"t\",
       count(*) AS \"count\" FROM \"public\".\"wut\"
GROUP BY CAST(to_timestamp(convert_from(\"public\".\"wut\".\"t\", ?), 'YYYYMMDDHH24MISS') AS date)
ORDER BY CAST(to_timestamp(convert_from(\"public\".\"wut\".\"t\", ?), 'YYYYMMDDHH24MISS') AS date) ASC
-- params are ("UTF8" "UTF8" "UTF8")
```

**Comment by nemanjaglumac** [comment]
Is there a way to create these custom tables and to store them as docker images that we can use for repros?
