### ISSUE TITLE
"Invite someone" button overlaps activate/deactivate radio buttons on small screen widths

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16350]
**To Reproduce**
1. Go to Admin -> People
2. Reduce width of screen

<img width="888" alt="image" src="https://user-images.githubusercontent.com/32746338/120748065-02cd4b80-c4b7-11eb-94f2-1d6ed9c31a25.png">

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by nemanjaglumac** [comment]
@noahmoss please include at least the branch for the issues in the future. The UI is currently different for `master`  and for the `release-x.39.x` branch. It saves some time (spent some time spinning up release, saw that the Ui doesn't match, stopped that, waited for master to build... you get the point).

Always assume that the person reading an issue is seeing Metabase for the first time.

**Comment by noahmoss** [comment]
@nemanjaglumac sorry about that! Will do.
