### ISSUE TITLE
LDAP port FE validation doesn't work properly

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16363]
**Describe the bug**
LDAP port validation **on frontend!** doesn't work properly when LDAP authentication is turned on. The inline error will be shown **only** if the first entered value is a string character. Enter the space of a number first, and it doesn't matter what you enter afterwards - the validation fails to do its job.

**Logs**
N/A

**To Reproduce**
1. Go to `/admin/settings/authentication/ldap`
2. Enable LDAP Authentication by turning the toggle on
3. Enter any string character (but not space)
4. See the error
5. Now delete it and enter _space_ then whatever combination of letters or numbers
6. Validation doesn't show any error
7. Delete it and start with the number followed by the string - validation doesn't work

**Expected behavior**
Inline validation should catch "edge" cases.

**Screenshots**

**Information about your Metabase Installation:**
local dev, `release-x.39.x` (21d532e8f3ec16127a928febe8780915c7f9c766)

**Severity**
Both annoying and incorrect. Probably P3 because clicking on the "Save changes" button will catch invalid config, but it results in all fields getting erased, which is #16226.

**Additional context**
The simplest possible solution for this would be to use `input type="number"` like we already do for the email port number.

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/issues/19428
