### ISSUE TITLE
We should warn when a Pulse might include only partial data

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1636]
Right now, depending on your saved question, it's possible to schedule a Pulse email that will only include partial data if the query includes "today." We should either warn the user that they're only going to see partial data, or we could do something like intelligently crop the query so that it doesn't include a partial day.

**Comment by tlrobinson** [comment]
I think it would be nice to have `dataset-query` check for this and include a flag in the result object so we can use it on the frontend and in pulses.

**Comment by agilliland** [comment]
Can you clarify a bit more what you mean by "partial" data?  As I am interpreting this so far you are saying that when you group something by a time granularity such as `day` it's possible for there to be values which don't include a full 24 hours of data?  And if that's correct then this could be extrapolated to be true for all time granularities (`hour`, `day`, `week`, `month`, `quarter`, `year`)

**Comment by mazameli** [comment]
Yeah, great question and clarification. I'm pretty sure I think that if we're presenting a metric + time label in a pulse, it's weird for it to not be a whole hour/day/week/month/quarter/year. Unless we change the label to something like "Today so far," or "This year so far."

**Comment by tlrobinson** [comment]
@agilliland Yeah I'd say the pseudo logic should be something like "if the last data point in a date/time column is within the current period specified by `:unit`, then show the warning"

**Comment by agilliland** [comment]
sure.  i'm interested in what "show the warning" actually looks like, but in general that makes sense.

from my own experience doing this stuff, most organizations i've seen tend to solve this problem by trying to force complete data points in reports.  e.g. in most reports they end on the last complete day of data.

**Comment by mazameli** [comment]
Yeah, I think ending the report on the last complete day of data is cleaner.

**Comment by agilliland** [comment]
It's great for daily analysis, which is probably the most common, but everything else is just as problematic.  e.g. reporting on the current week when it's friday or reporting on the current month when it's the 26th, they all have the same problem.

this is definitely an interesting UX problem.

**Comment by mazameli** [comment]
"Interesting" is a good euphemism for "headache-inducing." :weary:

**Comment by tlrobinson** [comment]
I think we should display the warning anywhere we display the data, with varying degrees of insensity. e.x. a big warning in "creation" modes like the query editor or pulse create/edit, and subtler warnings in "consuming" modes like pulses and dashboards.

**Comment by agilliland** [comment]
I think that sounds pretty sensible, but I'd still step back and wonder whether it's always relevant to show an indicator of partial data in all of these cases.

For example, let's assume i ask for `count of new users by month for the current year`.  Unless i look at that question at exactly midnight on the last day of a month then it would ALWAYS show a warning about partial data.  Which seems silly to me.

**Comment by camsaul** [comment]
@agilliland If you look at a question at exactly midnight on the last day of a month you'd be on the next month

**Comment by agilliland** [comment]
fair enough.  then i'd have to look at it a few seconds before that.
