### ISSUE TITLE
Cookie Missing When Switch URL in iFrame

### ISSUE THREAD

**Issue by zhezzz** [metabase/metabase#16374]
I am Using  Full App Embedding[https://www.metabase.com/docs/latest/enterprise-guide/full-app-embedding.html](url) in iFrame，When I switch url in iFrame，**metabase.EMBEDDED_SESSION** is missing，require me to log in again。

**Comment by flamber** [comment]
Hi @zhezzz 
Please use the forum for questions and troubleshooting for the open source version: https://discourse.metabase.com/
FullApp Embedding is only available in Enterprise Edition. If you are using that, then contact support via email.
