### ISSUE TITLE
Javascript error when enabling JWT authentication

### ISSUE THREAD

**Issue by rags22489664** [metabase/metabase#16378]
I get the following javascript error when I try to enable JWT auth on metabase v1.39.3.

<img width="1662" alt="Screenshot 2021-06-06 at 6 08 21 PM" src="https://user-images.githubusercontent.com/1449880/120924691-7ad38580-c6f2-11eb-89cd-d546ab72289a.png">

**Comment by flamber** [comment]
Hi @rags22489664 
Use 1.39.2 instead: https://github.com/metabase/metabase/releases/tag/v1.39.2

----

The only thing that I can think of causing this would be #16187
