### ISSUE TITLE
Pulse test endpoint requires admin but is displayed to non-admins

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1637]
Clicking the button results in "Sorry, you are not authorized to view the specified page."

Is it safe to allow normal users to send arbitrary pulses?

**Comment by kdoh** [comment]
Since they can create them, there's no reason in my mind why they couldn't test them. Seems like a vestigial restriction from when it was just an endpoint and not a user action.

**Comment by agilliland** [comment]
why would that endpoint require admin?  didn't realize that was put in there.  the entire pulse api was intended to be open to normal users so i would agree that should be removed.

doesn't seem like something that's a big risk.

**Comment by tlrobinson** [comment]
That's true, and given everything is now public to all users there's no issue with users being able to add cards they don't have access to (but definitely something to keep in mind when we add more fine grained permissions). I was just being overly cautious when I added that endpoint.
