### ISSUE TITLE
Support Windows domain authentication on SQL Server connections

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1638]
As reported by @tomashm in #1298 

According to https://msdn.microsoft.com/en-us/library/ms378428(v=sql.110).aspx, the jdbc url should look something like this: jdbc:sqlserver://somehost;integratedSecurity=true;

**Comment by ThinkFlipp** [comment]
:+1:

**Comment by AlgyTaylor** [comment]
:+1:

**Comment by camsaul** [comment]
Unfortunately it [looks like this isn't supported by jTDS].(http://sourceforge.net/p/jtds/discussion/104388/thread/ee46e233/) 

See also [valid jTDS connection string params](http://jtds.sourceforge.net/faq.html#urlFormat).

**Comment by camsaul** [comment]
I take that back. [This thread seems to suggest that it is theoretically possible](http://blogs.msdn.com/b/alexfeng/archive/2013/07/29/sql-server-connection-failed-with-jtds-jdbc-driver-sspi-handshake-failed-with-error-code-0x80090302-state-14-while-establishing-a-connection-with-integrated-security-the-connection-has-been-closed.aspx)
