### ISSUE TITLE
Re-using "Sample Dataset" database connection for another database type will stop working on restart

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16382]
**Describe the bug**
The default "Sample Dataset" database connection can be changed to any other database, but upon restart of the instance the connection details are lost and the connection will be in limbo between referencing the new database type, but without correct details.
This is caused by `metabase_database.is_sample=true`, which then overwrites `metabase_database.details` on startup.

**To Reproduce**
1. Setup an instance
2. Admin > Databases > "Sample Dataset"
3. Change it to any other database type and fill in the details
4. Validate that it now makes queries to whatever is configured in step 3.
5. Restart the instance
6. Now all questions (for this connection) will stop working, since they're querying the selected database type, but without any details (so it will make queries to defaults like `localhost:3306`) and viewing Admin > Databases > (whatever "Sample Dataset" might have changed to in step 3) > will just show empty information.
![image](https://user-images.githubusercontent.com/1447303/120999340-4ced5000-c789-11eb-8227-da98e9397f02.png)

**Expected behavior**
Either lock the "Sample Dataset", so it cannot be modified to a different type (or the Connection String), or make sure to set `metabase_database.is_sample=false` when the connection is modified (besides if the name is changed)

**Information about your Metabase Installation:**
Only tested 0.39.3, but I believe this has always been a problem, since `is_sample` was introduced.

**Additional context**
This might have been the reason for some obscure problems that people have hit, but I just never connected the dots.

**Comment by camsaul** [comment]
I think we should do two things here:

1. Disallow modifying the `engine` (driver) or `details` properties of any Database that `is_sample` in the model layer of the backend code
1. Gray out these fields in the admin UI for any database that `is_sample`.

I think the first one is the most important and the second one is a nice-to-have.

**Comment by camsaul** [comment]
@nemanjaglumac You definitely could Cypress test this -- try to change the database type of the Sample Dataset, and the page should error
