### ISSUE TITLE
Query date range incorrect for non-UTC timezone (Snowflake)

### ISSUE THREAD

**Issue by gouline** [metabase/metabase#16381]
**Describe the bug**

We have an `EVENTS` table in Snowflake with a `TIMESTAMP_TZ` column called `TS`. It contains timestamps in local time zone `Australia/Sydney` (GMT+10:00), which is also configured as the Snowflake account time zone and Metabase `user.timezone` and `report-timezone` parameters.

When I create a question to only show events for June 4, 2021 (Sydney time), Metabase runs the following SQL:

```sql
SELECT "BUSINESS"."PUBLIC"."EVENTS"."TS" AS "TS"
FROM "BUSINESS"."PUBLIC"."EVENTS"
WHERE ("BUSINESS"."PUBLIC"."EVENTS"."TS" >= timestamp '2021-06-04 00:00 +10:00'
   AND "BUSINESS"."PUBLIC"."EVENTS"."TS" < timestamp '2021-06-05 00:00 +10:00')
LIMIT 1048575
```

The results shown are instead between `2021-06-03 14:00 +10:00` and `2021-06-04 14:00 +10:00` (formatted correctly in Sydney time). This is suspiciously 10 hours off - how far away Sydney is from UTC - but in the opposite direction.

If I set `report-timezone` in Metabase to 'UTC', the following SQL is generated:

```sql
SELECT "BUSINESS"."PUBLIC"."EVENTS"."TS" AS "TS"
FROM "BUSINESS"."PUBLIC"."EVENTS"
WHERE ("BUSINESS"."PUBLIC"."EVENTS"."TS" >= timestamp '2021-06-04 00:00 Z'
   AND "BUSINESS"."PUBLIC"."EVENTS"."TS" < timestamp '2021-06-05 00:00 Z')
LIMIT 1048575
```

The results are between `2021-06-03 14:00 Z` and `2021-06-04 14:00 Z` (formatted correctly in UTC). This range is now correct for Sydney but incorrect for UTC.

In contrast, whenever I run these exact queries directly in Snowflake web console (preceding them with `ALTER SESSION SET TIMEZONE = 'Australia/Sydney'` and `ALTER SESSION SET TIMEZONE = 'Etc/UTC'`, respectively, as I can see Metabase is doing from the session history), I'm getting the correct result ranges and formatting for both.

Unfortunately, I cannot fully verify what values Metabase is passing in these queries, because SQL parameters appear as `?` in Snowflake session history when using the JDBC driver.

**Logs**

Here's what is logged for the UTC example:

```
:query
  "SELECT date_trunc(\"day\", CAST(\"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"TS\" AS timestamp)) AS \"TS\", \"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"TITLE\" AS \"TITLE\", \"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"ID\" AS \"ID\", count(*) AS \"count\" FROM \"BUSINESS\".\"PUBLIC\".\"EVENTS\" WHERE (\"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"TS\" >= ? AND \"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"TS\" < ?) GROUP BY date_trunc(\"day\", CAST(\"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"TS\" AS timestamp)), \"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"TITLE\", \"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"ID\" ORDER BY date_trunc(\"day\", CAST(\"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"TS\" AS timestamp)) ASC, \"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"TITLE\" ASC, \"BUSINESS\".\"PUBLIC\".\"EVENTS\".\"ID\" ASC",
  :params (#t "2021-06-04T00:00+10:00[Australia/Sydney]" #t "2021-06-05T00:00+10:00[Australia/Sydney]")},
```

**To Reproduce**

1. Create a custom question for `EVENTS` table
2. Add filter "TS is June 4, 2021" (no time specified)
3. Observe events returned between June 3, 2021 14:00:00 +10:00 and June 4, 2021 14:00:00 +10:00, formatted in Sydney time

**Expected behavior**

Events returned between June 4, 2021 00:00:00 +10:00 and June 5, 2021 00:00:00 +10:00, formatted in Sydney time.

**Information about your Metabase Installation:**

- Your browser and the version: Chrome/91.0.4472.77
- Your operating system: 5.4.117-58.216.amzn2.x86_64
- Your databases: Snowflake
- Metabase version: 0.39.3
- Metabase hosting environment: Kubernetes (EKS)
- Metabase internal database: PostgreSQL 13.2

```
{
  "browser-info": {
    "language": "en-AU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.117-58.216.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Australia/Sydney"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "Australia/Sydney"
    }
  }
}
```

**Severity**

Medium - blocking some users.

**Comment by flamber** [comment]
Hi @gouline 
Please post "Diagnostic Info" from Admin > Troubleshooting.

**Comment by gouline** [comment]
@flamber Updated the description with diagnostic info ✔️

**Comment by flamber** [comment]
It sounds very related to #8804, but possibly combined with a frontend timezone issue too - likely #10824.
Timezone issues can get really tricky to understand and debug without very precise steps-to-reproduce.

**Comment by gouline** [comment]
Those issues do look related. What kind of details are currently missing? I can post SQL with insert statements containing concrete examples of this bug, would that help?

**Comment by flamber** [comment]
@gouline It was more a general statement I made, but when it comes to timezone issues, then the more specific details you can provide, the easier it is for the developers to reproduce your setup. So the database timezone, column timezone and stuff like that would be helpful. Kinda think of this issue as someone needs all your information, so they can reproduce the problem.

**Comment by gouline** [comment]
Understood. Here's some SQL to create a similar table in Snowflake:

```sql
alter account set timezone = 'Australia/Sydney';
create table events (id number, ts timestamp_tz);
insert into events values 
  (1, '2021-06-03 13:59:00 +10:00'),
  (2, '2021-06-03 14:01:00 +10:00'),
  (3, '2021-06-03 23:59:00 +10:00'),
  (4, '2021-06-04 00:01:00 +10:00'),
  (5, '2021-06-04 13:59:00 +10:00'),
  (6, '2021-06-04 14:01:00 +10:00'),
  (7, '2021-06-04 23:59:00 +10:00'),
  (8, '2021-06-05 00:01:00 +10:00');
```

Once this `events` table is viewable in Metabase, create a custom question with one filter "TS is June 4, 2021" (no time specified). When `report-timezone` is set to `Australia/Sydney`, we expect the following results:

ID | TS
-- | --
4 | June 4, 2021, 00:01
5 | June 4, 2021, 13:59
6 | June 4, 2021, 14:01
7 | June 4, 2021, 23:59

What we actually see in Metabase is the following:

ID | TS
-- | --
2 | June 3, 2021, 14:01
3 | June 3, 2021, 23:59
4 | June 4, 2021, 00:01
5 | June 4, 2021, 13:59

Now let's set `report-timezone` to `Etc/UTC`. We expect the following results:

ID | TS
-- | --
5 | June 4, 2021, 03:59
6 | June 4, 2021, 04:01
7 | June 4, 2021, 13:59
8 | June 4, 2021, 14:01

Instead, we get the following:

ID | TS
-- | --
4 | 3 Jun, 2021, 14:01
5 | 4 Jun, 2021, 03:59
6 | 4 Jun, 2021, 04:01
7 | 4 Jun, 2021, 13:59

Finally, to eliminate Kubernetes, EKS and Amazon Linux as variables, I reproduced everything described here on Metabase for Mac installed on my laptop and pointed to the same table in Snowflake. Here is the diagnostic info, if you need it:

```
{
  "browser-info": {
    "language": "en-au",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+9-202002041938",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+9-202002041938",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "Australia/Sydney"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "snowflake"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "Australia/Sydney"
    }
  }
}
```

**Comment by landm** [comment]
I have had the same issue and spent a fair amount of time changing all the various timezones settings. The metabase snowflake JDBC driver [always overwrites to UTC](https://github.com/metabase/metabase/blob/bbd4f635220b05487de82a18310d4d18fe04174d/modules/drivers/snowflake/src/metabase/driver/snowflake.clj#L65) and unless you have your snowflake session settings correct and/or the value of this JDBC parameter [JDBC_USE_SESSION_TIMEZONE](https://docs.snowflake.com/en/sql-reference/parameters.html#jdbc-use-session-timezone) set to FALSE, you'll end up getting potentially inconsistent results.

**Comment by gouline** [comment]
@landm Looking at Snowflake query history, I do see Metabase setting `ALTER SESSION SET TIMEZONE = 'Australia/Sydney'` before executing the select query, so that would constitute correct session settings, right? Hence, setting `JDBC_USE_SESSION_TIMEZONE` produced the same results as without it, as expected.

**Comment by gouline** [comment]
A little more detail on this one: "on X date" filter that I described above behaves differently to the "previous X days" filter.

Using the same dataset, if today was June 5, 2021 and you filtered by "previous 1 day" with "include today" unchecked (displayed as "TS Yesterday" in the notebook), then the following happens:

- When `report-timezone` is `Etc/UTC`, the results are ID 5-8 (consistent with UTC's "yesterday")
- When `report-timezone` is `Australia/Sydney`, the results are ID 4-7 (consistent with Sydney's "yesterday")

So "previous X days" filter is _consistent_ with the set `report-timezone`, only the "on X date" is not, as described in my original report.

Unfortunately, this means setting `report-timezone` to `Etc/UTC` no longer works as a workaround, because whichever way you set it, either "previous X days" or "on X date" filter will be wrong.

**Comment by gouline** [comment]
Anything I can do to help with this one? Never tried Clojure before, but I know Java and willing to give it a go if pointed in the right direction 😄

**Comment by flamber** [comment]
@gouline Timezone issues are very complicated. And any fix would require tests too.
If a timezone is specific to a database, then have a look in the driver: https://github.com/metabase/metabase/blob/master/modules/drivers/snowflake/src/metabase/driver/snowflake.clj
If the driver is similar to another driver, but those databases don't have the specific timezone problem, then look in those drivers as reference. Here's an [example](https://github.com/metabase/metabase/pull/20023/files) of a Redshift timezone fix.
If the problem is more general in the query processor, then all databases should have this problem, but fixing the QP is even more complex.

Doing your first Clojure work on a timezone issue is not the easiest way to get into that language.

**Comment by qnkhuat** [comment]
Not sure which PR do this but I think it's fixed

![Screenshot 2022-11-29 at 16 36 06](https://user-images.githubusercontent.com/25661381/204493054-71ccf27d-6ead-48cf-aaaf-74d4a884e71e.png)
![Screenshot 2022-11-29 at 16 36 21](https://user-images.githubusercontent.com/25661381/204493063-0b518860-6923-4353-aebf-61f4dccc720a.png)

**Comment by gouline** [comment]
@qnkhuat Just tested 0.45.0-RC3 and I can confirm this works correctly! Our production instance runs 1.44.6 and it's still broken there, so this must be a recent fix in x.45.0. Feel free to close this issue 🎉

**Comment by paoliniluis** [comment]
thanks for confirming @gouline
