### ISSUE TITLE
Make e2e test on setting up Metabase agnostic about user's browser i18n

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16392]
When running Cypress locally, if our computers are not set to English as the default language, account setup tests will fail.

See https://github.com/metabase/metabase/blob/master/frontend/test/metabase/scenarios/onboarding/setup/setup.cy.spec.js#L11, test with title `should allow you to sign up using "${locale}" browser locale`

One or more of the following lines probably should be made more generic. Thus, tests will work with any language set up in the developer's machine. 

```js
cy.findByText("What's your preferred language?");
cy.findByText("English").click();
cy.findByText("Next").click();
```

**To Reproduce**
1. Have your computer use a language other than English as default.
2. Check that headless Chrome uses the language you have set up.
3. Run Cypress tests — you can filter for `onboarding` scenario and `setup` specs.
4. See the test fail.

**Context:**

The screen below is where the tests fail.

<img src="https://user-images.githubusercontent.com/380816/121042646-44e1e000-c78a-11eb-8543-ec8d60a947b4.png" width=400 />

**Comment by flamber** [comment]
Very related to #13051 and #15656
