### ISSUE TITLE
Support using MSSQL views in SQL Server

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1640]
As reported by @ryanaverill in #1298

**Comment by camsaul** [comment]
@ryanaverill what schemas are your views saved in? `dbo`?

**Comment by ryanaverill** [comment]
Yup all dbo

**Comment by LukeAbell** [comment]
+1

**Comment by seedubyaache** [comment]
+1

**Comment by louis-eyond** [comment]
I am happy to see the Views in the latest release.  It helps quite a bit to be able to use a View to limit the rows returned as part of security requirements.  However, we aren't able to do Foreign Key relationships on the Views in the Model screen.  It would be a nice feature addition to be able to FK 2 Views together.

**Comment by agilliland** [comment]
@louis-eyond you can actually describe your FK relationships directly in Metabase and they will be honored, even if they aren't part of the underlying schema.  So for example, go to the `Data Model` page in the admin section, navigate to the table that you want to have an FK, and under the `TYPE` column pick the option for `Foreign Key`, then you will presented with an option to pick the target field your FK points to in the schema.

**Comment by louis-eyond** [comment]
Correct, that is the selector I am referring to -- you can't select another View.  Click "Select a target" and you get a list of only Tables (no Views).  Metabase 0.16.1

An example is dbo.vwContacts.CompanyId -> dbo.vwCompanies.CompanyId .  We are using views here since the base tables have private rows that all users can not have access to.

**Comment by salsakran** [comment]
Is dbo.vwCompanies.CompanyId marked as a primary key in it's entry in the data model? If not, try marking it as such and see if it shows up in the list.

**Comment by louis-eyond** [comment]
Bingo.  Thank you very much.

**Comment by camsaul** [comment]
@louis-eyond @ryanaverill @LukeAbell @seedubyaache I opened PR #5491 (branch `allow-additional-options-for-sqlserver`) which switches the JDBC driver we use under the hood from jTDS to the official Microsoft one. It seems to fix several issues with SQL Server and I have a feeling it might fix this one as well. Is there a chance you could try that branch out and see if it fixes this issue for you?

**Comment by camsaul** [comment]
@louis-eyond @ryanaverill @LukeAbell @seedubyaache ?

**Comment by TurkerTunali** [comment]
I haven't faced any issue by using SQL Server views with 0.29+.

**Comment by flamber** [comment]
Closing this, since I have used views on SQL Server.
