### ISSUE TITLE
Can't sort on grouping field

### ISSUE THREAD

**Issue by kurtosis-color** [metabase/metabase#1641]
When I create "group and count" table I can sort it on the count field but not on the group variable field. (Specifically this is grouping on a timestamp by week, not sure if it's true for all group bys). Thanks!

**Comment by agilliland** [comment]
Confirmed that this is a bug.  To reproduce:  Start a query from the Sample Dataset w/ Orders, count, broken out by Created At: Week (or any other granularity) and then try to sort it.  No sorting options are present other than to sort by "count".

<img width="1320" alt="screen shot 2015-12-04 at 5 22 29 pm" src="https://cloud.githubusercontent.com/assets/1987787/11605104/f7e88b52-9aab-11e5-9fd9-eb48e7170f9c.png">

**Comment by agilliland** [comment]
@tlrobinson can you take a look at this one when you get a chance.  looks like this has been happening for a while, but from what i see it looks like this is likely a limitation happening on the frontend.
