### ISSUE TITLE
website doesn't list that metabase works with sqlite or H2

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1643]
The whole reason I wrote the SQLite driver was because people we asking for it. Seeing how people actually use it in real life it would make sense to put that on the website

![screen shot 2015-12-04 at 5 47 36 pm](https://cloud.githubusercontent.com/assets/1455846/11605226/34053204-9aaf-11e5-8708-c1bb770a30cb.png)

**Comment by salsakran** [comment]
Didn't include SQLlite or H2 for brevity and due to the CSS in the website. 

Taking conversation offline as issues in this repo should be strictly about the actual product.
