### ISSUE TITLE
License activation page has non-admin header on initial page load

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16479]
**Describe the bug**
The normal blue header is shown when you first click "activate a license". If you then refresh, it switches to the purple admin header.

**To Reproduce**
1. Go to Admin -> Enterprise
2. Click on 'Activate a license"
3. Observe blue header
4. Refresh page
5. Observe purple header

**Expected behavior**
Admin header should be used consistently

**Screenshots**

https://user-images.githubusercontent.com/32746338/121098207-373c5280-c7aa-11eb-9162-d7a4f725d0b8.mov

**Information about your Metabase Installation:**

Chrome 91.0.4472.77 and Firefox 89.0 on MacOS on master branch

**Comment by brunobergher** [comment]
Plus that typo, right?

**Comment by noahmoss** [comment]
@brunobergher looks like someone (external) has #16734 up to fix three instances of that exact typo

**Comment by flamber** [comment]
This was completely revamped in v42 #19343 (and some follow-ups).
