### ISSUE TITLE
Dashboard category filter doesn't list all question's joined tables

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#16489]
**Describe the bug**
On a dashboard, when binding a category filter to a question field, not all joined tables with relevant fields are listed.

**To Reproduce**
1. With sample dataset, create a question as follows:
![image](https://user-images.githubusercontent.com/30152071/121201822-1b51b300-c875-11eb-9302-a32400721f9e.png)
2. Save and add to a new dashboard.
3. On the dashboard, create a category filter.
4. Try to bind the filter to a field of the Reviews joined table.
5. Notice the Reviews table is not shown.
![image](https://user-images.githubusercontent.com/30152071/121202009-41775300-c875-11eb-838a-d0ee66c64bee.png)
6. Add the Reviews table (simple question) to the same dashboard.
7. Notice its fields are allowed to be bound to the same category filter.
![image](https://user-images.githubusercontent.com/30152071/121202059-4b00bb00-c875-11eb-883f-343bbf172ef4.png)

**Expected behavior**
All fields (also from joined tables) of the same type should be allowed to be bound to a category filter.

**Information about your Metabase Installation:**
Tested with 0.37.6, 0.38.4, 0.39.3.

**Severity**
Pretty important, as I have no idea about a quick workaround and this doesn't allow us to add the required filters to a dashboard.

**Comment by flamber** [comment]
Hi @andreychirikba 
None of the fields in Reviews table are of one of the required fields:
 https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#creating-sql-question-filters-using-field-filter-variables
