### ISSUE TITLE
HOW TO SINGLE SIGN-ON WITH BUSINESS WECHAT 

### ISSUE THREAD

**Issue by Rxn666** [metabase/metabase#16484]
**I have a mission to do the single sign-on with business wechat, a chiness popular app for company, and metabase. I already know both apps support OAuth2, but I donot know how to do the job.**

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by Rxn666** [comment]
Thank you for your reply! I will try to manage it.
