### ISSUE TITLE
Only GET calls happening on DB, No Posts.  *BLOCKING ISSUE ACCESSING DATA*

### ISSUE THREAD

**Issue by Shayna55** [metabase/metabase#16504]
**Describe the bug**
"Doing Science" on all tables and reports spins forever.  Only "Get" calls, no "Posts"

**Logs**
Setting moment.js start of week for Locale en to sunday
analytics.js:39 Refused to connect to 'https://www.google-analytics.com/j/collect?v=1&_v=j90&a=65086695&t=event&_s=1&dl=https%3A%2F%2Fdevia.metabaseapp.com%2Fbrowse%2F3&ul=en-us&de=UTF-8&dt=Metabase&sd=24-bit&sr=1920x1080&vp=1920x937&je=0&ec=Data%20Browse&ea=Table%20Click&_u=SACAAEABAAAAAC~&jid=&gjid=&cid=150561478.1616430874&tid=UA-60817802-1&_gid=971452402.1623079348&_slc=1&cd1=v1.39.2&z=2028948416' because it violates the following Content Security Policy directive: "connect-src 'self' metabase.us10.list-manage.com".

wd @ analytics.js:39
analytics.js:39 Refused to connect to 'https://www.google-analytics.com/j/collect?v=1&_v=j90&a=65086695&t=pageview&_s=5&dl=https%3A%2F%2Fdevia.metabaseapp.com%2Fbrowse%2F3&dp=%2Fbrowse%2F3&ul=en-us&de=UTF-8&dt=02%3A38%20%C2%B7%20Question%20%C2%B7%20Metabase&sd=24-bit&sr=1920x1080&vp=1920x937&je=0&_u=SACAAEABAAAAAC~&jid=1305768634&gjid=993053431&cid=150561478.1616430874&tid=UA-60817802-1&_gid=971452402.1623079348&_r=1&cd1=v1.39.2&z=1610308759' because it violates the following Content Security Policy directive: "connect-src 'self' metabase.us10.list-manage.com".

wd @ analytics.js:39
pe @ analytics.js:38
Sa @ analytics.js:43
Ha.D @ analytics.js:41
pc.send @ analytics.js:76
X.b.<computed> @ analytics.js:56
Z.v @ analytics.js:92
Z.D @ analytics.js:91
N @ analytics.js:92
trackPageView @ app-main.bundle.js?6b8fa7d43bc126072e37:5
(anonymous) @ app-main.bundle.js?6b8fa7d43bc126072e37:5
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:440
g @ vendor.bundle.js?6b8fa7d43bc126072e37:434
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:440
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:116
(anonymous) @ app-main.bundle.js?6b8fa7d43bc126072e37:5
_ @ vendor.bundle.js?6b8fa7d43bc126072e37:440
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:116
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:116
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:116
_ @ vendor.bundle.js?6b8fa7d43bc126072e37:116
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:116
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:116
c @ vendor.bundle.js?6b8fa7d43bc126072e37:495
t.loopAsync @ vendor.bundle.js?6b8fa7d43bc126072e37:495
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:116
v @ vendor.bundle.js?6b8fa7d43bc126072e37:116
push @ vendor.bundle.js?6b8fa7d43bc126072e37:116
push @ vendor.bundle.js?6b8fa7d43bc126072e37:116
push @ vendor.bundle.js?6b8fa7d43bc126072e37:116
handleClick @ vendor.bundle.js?6b8fa7d43bc126072e37:434
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:487
h @ vendor.bundle.js?6b8fa7d43bc126072e37:487
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:487
g @ vendor.bundle.js?6b8fa7d43bc126072e37:487
ot @ vendor.bundle.js?6b8fa7d43bc126072e37:487
rt @ vendor.bundle.js?6b8fa7d43bc126072e37:487
at @ vendor.bundle.js?6b8fa7d43bc126072e37:487
ht @ vendor.bundle.js?6b8fa7d43bc126072e37:487
j @ vendor.bundle.js?6b8fa7d43bc126072e37:487
F @ vendor.bundle.js?6b8fa7d43bc126072e37:487
Gt @ vendor.bundle.js?6b8fa7d43bc126072e37:487
Xt @ vendor.bundle.js?6b8fa7d43bc126072e37:487
t.unstable_runWithPriority @ vendor.bundle.js?6b8fa7d43bc126072e37:495
Wi @ vendor.bundle.js?6b8fa7d43bc126072e37:487
P @ vendor.bundle.js?6b8fa7d43bc126072e37:487
(anonymous) @ vendor.bundle.js?6b8fa7d43bc126072e37:487
Show 17 more frames
vendor.bundle.js?6b8fa7d43bc126072e37:487 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at vendor.bundle.js?6b8fa7d43bc126072e37:487
    at tt (vendor.bundle.js?6b8fa7d43bc126072e37:487)
    at Object.t.findDOMNode (vendor.bundle.js?6b8fa7d43bc126072e37:487)
    at p.value (app-main.bundle.js?6b8fa7d43bc126072e37:5)
    at app-main.bundle.js?6b8fa7d43bc126072e37:5

**To Reproduce**
1. Go to CAPGMS Delco DB (CAPGMS Marion, and CAPGMS Dev just fine)
2. Click on any of the tables
4. See error, "Doing Science" forever.

**Expected behavior**
The table should pull up.

**Screenshots**

**Severity**
This blocks our usage of metabase completely on the CAPGMS Delco DB which is our main one.  I have a report due to the state of Delaware and the US Treasury that I need to get in by EOD and this is completely blocking me from completing that.

**Additional context**
This happened yesterday 6/7 for about an hour that we noticed and is now down again today for the last hour.  It was working fine until shortly after 11am PST.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.219-164.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v1.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @Shayna55 
Please contact support via https://store.metabase.com/support so we know which instance this relates to.
