### ISSUE TITLE
It is possible to drag move (and undo move) collection item to the collection it's already in

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16518]
**Describe the bug**
It is possible to drag move (and undo move) collection item to the collection it's already in, which results in two `PUT` requests being fired.

**To Reproduce**
1. Go to `/collection/root`
2. Start dragging any item (question/dashboard) and drag it to the sidebar to the same collection it's already in
3. Notice `PUT` request in the console
4. Notice tooltip in the lower left corner telling you that item moved, and offering to UNDO that action
5. Click "Undo"
6. Notice another `PUT` request in the console
7. The item never moved from where it already was

**Expected behavior**
Either block moving items to their own collections or at least don't trigger `PUT` requests.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/4guny0Xn/26caa0c0-ace9-4f97-a739-d352106fe4fb.gif?source=viewer&v=dec5760be63b1900191c8c9a50b16d78)

**Information about your Metabase Installation:**
local dev, master 658a6f761c55f2556114b48b0729d2edbd5f191d

**Severity**
P3

**Comment by kulyk** [comment]
Looks like it got fixed during the sidebar revamp, see the video:

https://user-images.githubusercontent.com/17258145/164243033-7cbb4d49-c47e-4d78-8200-caa3b1b487d3.mp4
