### ISSUE TITLE
Error on large text (or data) fields

### ISSUE THREAD

**Issue by AlgyTaylor** [metabase/metabase#1651]
On SQLServer, with Varchar(MAX) fields, I get the following exception unless I hide them:

> Error: Cannot JSON encode object of class: class net.sourceforge.jtds.jdbc.ClobImpl: net.sourceforge.jtds.jdbc.ClobImpl@10a251fmetabase.models.interface$write_json.invoke(interface.clj:132)metabase.models.field_values$fn__14949.invoke(field_values.clj:10)metabase.models.interface$fn__4741$G__4667__4748.invoke(interface.clj:59)metabase.db$ins.doInvoke(db.clj:325)metabase.models.field_values$create_field_values.doInvoke(field_values.clj:47)metabase.models.field_values$create_field_values_if_needed.doInvoke(field_values.clj:72)metabase.models.field$fn__15116.invoke(field.clj:92)metabase.models.interface$fn__4728$G__4661__4735.invoke(interface.clj:59)metabase.db$upd.doInvoke(db.clj:213)metabase.api.field$fn__18090$fn__18093.invoke(field.clj:44)metabase.api.common.internal$wrap_catch_api_exceptions.invoke(internal.clj:216)metabase.api.field$fn__18090.invoke(field.clj:36)metabase.middleware$enforce_authentication$fn__19700.invoke(middleware.clj:82)metabase.api.routes$fn__19818.invoke(routes.clj:40)metabase.routes$fn__20688.invoke(routes.clj:23)metabase.middleware$log_api_call$fn__19801.invoke(middleware.clj:302)metabase.middleware$add_security_headers$fn__19754.invoke(middleware.clj:192)metabase.middleware$format_response$fn__19766.invoke(middleware.clj:245)metabase.middleware$bind_current_user$fn__19704.invoke(middleware.clj:96)metabase.middleware$wrap_current_user_id$fn__19678.invoke(middleware.clj:64)metabase.middleware$wrap_api_key$fn__19719.invoke(middleware.clj:107)metabase.middleware$wrap_session_id$fn__19671.invoke(middleware.clj:55)

Any chance of a fix for this?  I hold a load of genetic data in a database, and so it's very useful to be able to access long strings of characters ....

**Comment by agilliland** [comment]
Yeah, we should be able to fix that.  I'm assuming the columns are working fine when you use a Varchar with a modest size, e.g. `Varchar(256)`?

**Comment by AlgyTaylor** [comment]
Hi,

Thanks for the reply :)

Yeah. it's perfectly fine with something like that - it's just ``Varchar(MAX)`` it seems to struggle with

**Comment by englishmatt** [comment]
For the sake of completion, this is also the case for `nvarchar(MAX)`.
