### ISSUE TITLE
Add 'Number' to labels of available filter types

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16521]
**Is your feature request related to a problem? Please describe.**

When adding a simple filter to a dashboard, the options are Time, Location, ID, and Other Categories, each of which has subtitles as suggestions. It isn't clear that I should choose 'Other Categories' if I want to add a simple numeric filter.

**Describe the solution you'd like**

Change the label 'Other Categories' or provide text below it to highlight that general numbers go here.

**Describe alternatives you've considered**

Documentation might help, but won't be right in front of people in the UI when they need it.

**How important is this feature to you?**

Easy once you know the trick, but confusing to newcomers.

Screenshot of options available when creating a filter in the SQL editor (note names of available options)
<img width="1421" alt="Screen Shot 2021-06-09 at 11 57 38 AM" src="https://user-images.githubusercontent.com/911566/121389425-65d93b00-c91a-11eb-92d0-40ecdb86405e.png">

Screenshot of options available when adding a filter to a dashboard (note the different naming scheme)
<img width="1422" alt="Screen Shot 2021-06-09 at 11 58 09 AM" src="https://user-images.githubusercontent.com/911566/121389459-6ffb3980-c91a-11eb-9744-e877475100c2.png">

**Comment by flamber** [comment]
Previous issues about Number filter on dashboards were closed in favor of #3035, but that seems like a separate request.

**Comment by flamber** [comment]
Closing in favor #3035
