### ISSUE TITLE
MongoDb queries stopped working completely on 0.13.0

### ISSUE THREAD

**Issue by dariooddenino** [metabase/metabase#1652]
Queries are not working anymore with MongoDb, even ones that were working on 0.12.0.

This is both happening on AWS and with a local instance (it gives an error regarding 'unrecognized field "allowDiskUse' ).

**Comment by agilliland** [comment]
Do you have access to the application log output?  It would be helpful to have some more detailed info to work from.

**Comment by agilliland** [comment]
Also, what version of Mongo are you using?  Metabase is designed to work with Mongo version 3.0 and higher

**Comment by dariooddenino** [comment]
It was indeed a Mongo version issue. Upgrading to 3.0 solved the problem.

Thanks, looking forward to having foreign-keys working on mongo so that I can seriously start using your awesome tool :)

**Comment by agilliland** [comment]
Cool.  glad it was an easy fix.  Let us know how things go and if you run into any additional problems.

**Comment by mapix** [comment]
For those who can not simply upgrade to 3.x, check my mongo2x hack here:

 https://github.com/mapix/metabase

**Comment by lazmo88** [comment]
@mapix - I am exactly in that situation, but out of luck figuring out how to compile your repo into executable .jar... Do you have it compiled somewhere? ;)

**Comment by camsaul** [comment]
@lazmo88, are you using Windows? If so, try using the [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about) which will let you build the JAR with the least amount of hassle.

**Comment by lazmo88** [comment]
@camsaul I was trying to compile with Ubuntu Linux, but sure I have windows as well ;) I will test it out! Thanks!

**Comment by camsaul** [comment]
Oh sorry @lazmo88. I misread your error message. It sounds like you need to make sure `ps` is installed? (Surprised this is not installed by default.) `sudo apt install ps` should do it

**Comment by lazmo88** [comment]
@camsaul ps is actually installed (even reinstalled procps package) and it works from command line, however the script still returns the same error. Also the weird thing was that build won´t start unless nodejs is version 4.4.7 (fixed this with nvm).

If I run the command ps -fp PPID it works fine, it will return the process running.

As said, I am totally lost with this one. Development guide made it sound too easy "./bin/build" 🗡 

Thanks for helping me @camsaul!

**With NodeJs 4.4.7**
`root@scw-283c45:/metabase/metabase# ./bin/build
Tagging uberjar with version 'v0.23.0-snapshot 0576ab4 support_mongo_2x 2017-04-21'...
Running 'yarn' to download javascript dependencies...
yarn install v1.2.1
warning You are using Node "4.4.7" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
$ ps -fp $PPID | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
error Couldn't find the binary ps -fp $PPID | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@scw-283c45:/metabase/metabase#
`
**With NodeJS 4.8.0**
`root@scw-283c45:/metabase/metabase# nvm use 4.8.0
Now using node v4.8.0 (npm v2.15.11)
root@scw-283c45:/metabase/metabase# ./bin/build
Tagging uberjar with version 'v0.23.0-snapshot 0576ab4 support_mongo_2x 2017-04-21'...
Running 'yarn' to download javascript dependencies...
yarn install v1.2.1
$ ps -fp $PPID | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/5] Validating package.json...
error metabase@0.0.0: The engine "node" is incompatible with this module. Expected version "4.4.7".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@scw-283c45:/metabase/metabase#
`
**PS**
`root@scw-283c45:/metabase/metabase# ps
  PID TTY          TIME CMD
 3641 pts/0    00:00:00 bash
 4337 pts/0    00:00:00 ps
root@scw-283c45:/metabase/metabase# ps -fp 3641
UID        PID  PPID  C STIME TTY          TIME CMD
root      3641  3442  0 01:24 pts/0    00:00:00 -bash
`

**Comment by camsaul** [comment]
@lazmo88 maybe try a newer version of node? I'm using `8.2.1` and it works for me
