### ISSUE TITLE
One-line text cards in dashboards are difficult to delete

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#16534]
**Describe the bug**
On a dashboard, when I try to delete a one-line text card, then it's very difficult to point exactly to the delete icon.

**To Reproduce**
1. Create a dashboard.
2. Add a text card spanning one line.
3. Try to point the mouse cursor to the delete icon on the right.
4. Notice the cursor is in "resize" mode. Only a couple of square pixels are the actual delete icon.

**Expected behavior**
I expect the delete button to be easily clickable.

**Screenshots**
![image](https://user-images.githubusercontent.com/30152071/121523239-46174500-c9f6-11eb-867b-91b70b982721.png)

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "Eclipse OpenJ9 VM",
    "java.vm.version": "openj9-0.18.0",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.34"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-08",
      "tag": "v0.38.4",
      "branch": "release-x.38.x",
      "hash": "057b6bb"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
Minor nuisance.

**Comment by flamber** [comment]
That is changed in the upcoming version 0.40.0:
![image](https://user-images.githubusercontent.com/1447303/121524401-917e2300-c9f7-11eb-8731-2481954cfc3b.png)
