### ISSUE TITLE
Logout button brings user back to main page momentarily before logging out

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16532]
**Describe the bug**
When you click the logout button, you're briefly brought back to the main (post-login) screen before being brought to the logout screen. This delay happens on both Firefox and Chrome but is significantly longer on Firefox (see video). It's confusing since you're momentarily unsure whether the logout request took effect.

**Expected behavior**
Redirect should only happen when bringing the user back to the login screen. Maybe a spinner or some other loading indicator should be shown while logout request is being processed. 

**Screenshots**

https://user-images.githubusercontent.com/32746338/121457256-3814e600-c95c-11eb-8391-d5885ac66641.mov

**Information about your Metabase Installation:**

Current master (0.39.4) on Chrome & Firefox on MacOS Big Sur

**Comment by flamber** [comment]
If my memory serves me right, then this was done to make sure that the cookies was deleted. Previous versions (32 I think) would cause a double-reload on logout, which didn't always work (race-condition) and could lead to auto-login again. #10039
Related to #15224 (originally, not the edited version).

**Comment by noahmoss** [comment]
Also, if you're logging out while on an admin page, it says "An error occurred" which is extra confusing.
