### ISSUE TITLE
Keep capitalization if entered into field names

### ISSUE THREAD

**Issue by howonlee** [metabase/metabase#16540]
Maz wanted this, and I have PR up for fix, but no ticket in issue tracker.

Basically, if you enter in `bobID` into field names or something, it should be kept, instead of current behavior, which is titlecasing the capitalized portion into `Bobid`. But we still want `USERS` to be titlecased into `Users` so it doesn't feel angry all the time.

**Comment by mazameli** [comment]
Hmm, `But we still want USERS to be titlecased into Users so it doesn't feel angry all the time` doesn't seem to map to what @brunobergher wrote in the product doc:

> Let's remove the advanced functionality and stick with just:
> - Replacing dashes and underscores with spaces
> - Uppercasing the first letter of each word, **leaving the rest of the words untouched**.

Disgregard if you and he discussed this already.

**Comment by howonlee** [comment]
It makes sample db look SHOUT SHOUT SHOUTY, is the problem

**Comment by brunobergher** [comment]
Why would it look SHOUT?
> - Replacing dashes and underscores with spaces
> - Uppercasing the first letter of each word, leaving the rest of the words untouched.

So:
- `PEOPLE` -> people -> People
- `BIRTH_DATE` -> BIRTH_DATE -> Birth Date

**Comment by brunobergher** [comment]
Ugh, good catch. I don't want to get into a loop and bring back some of the more advanced guessing, where we'll find issues again, etc.

Could we change things in the Sample Dataset?

**Comment by ariya** [comment]
> Could we change things in the Sample Dataset?

Assuming it's done carefully not to break those Cypress tests, I think we could.

**Comment by brunobergher** [comment]
@flamber, @nemanjaglumac, any concerns about this?
