### ISSUE TITLE
Mongo query with date breaks

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1655]
from http://discourse.metabase.com/t/mongo-query-with-date-breaks/128

**Seems like Metabase doesn't like Date fields.**
I'm using mongodb and the mac client.
An entry like {"state" : "deployed", "thedate" : Date( 1435650003708 )}, or even {"state" : "deployed", "thedate" : 1435650003708} returns "We couldn't understand your question." if trying to get the raw data.

I tried explicitly setting the field as Unix time stamp but it still breaks.
Also, changing time zone didn't get.

**Logs show:**
2015-12-08 3:49:47.962 PM Metabase[41265]: [ERROR] metabase.driver :: Query failure: Command failed with error 15999: 'exception: invalid operator '$dateToString'' on server localhost:27017. The full response is { "errmsg" : "exception: invalid operator '$dateToString'", "code" : 15999, "ok" : 0.0 }

**Comment by camsaul** [comment]
Metabase requires MongoDB 3.0 or newer -- `$dateToString` is available on Mongo 3.0+

**Comment by edchan77** [comment]
thanks

**Comment by edchan77** [comment]
probably worthwhile detecting the mongo version and notifying the user it requires 3.0+

**Comment by websirnik** [comment]
+1 about the warning message
