### ISSUE TITLE
Metrics Definitions Tooltip is truncated in Question Editor

### ISSUE THREAD

**Issue by chasleslr** [metabase/metabase#16569]
**Describe the bug**
The metrics definition tooltip in the Question editor view is truncated on the x-axis and does not show the full content (see screenshots). This has been the case ever since I started using Metabase in January 2021.

**Logs**
N/A

**To Reproduce**
1. Create a simple/custom question
2. Click to add a metric in "Common Metrics"
3. Hover over the "?" tooltip.
4. See the truncated tooltip.

**Expected behavior**
The tooltip should not be truncated on the x-axis. 

**Screenshots**
Simple Question view:
<img width="647" alt="Screen Shot 2021-06-14 at 12 52 18 PM" src="https://user-images.githubusercontent.com/54685896/121929712-7c630600-cd0f-11eb-8b92-f84428a84cdc.png">

Custom Question view:
<img width="536" alt="Screen Shot 2021-06-14 at 12 48 34 PM" src="https://user-images.githubusercontent.com/54685896/121929364-21c9aa00-cd0f-11eb-83b6-5b15a0f8a8af.png">

**Severity**
Low

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.203-156.332.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "postgres"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-27",
      "tag": "v0.39.3",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by EvaSchreyer** [comment]
still the same issue in metabase 0.41.4

**Comment by ranquild** [comment]
There is no metric definition at all atm

**Comment by ranquild** [comment]
We decided not to fix this since updated metrics are in the roadmap https://www.metabase.com/roadmap.
