### ISSUE TITLE
Cannot return from custom url to default click behavior in dashboard

### ISSUE THREAD

**Issue by maxschloegl** [metabase/metabase#16573]
**Describe the bug**
It is not possibe to return from custom url to default click behavior in a dashboard.

**To Reproduce**
1. Insert a question as table in a dashboard.
2. Edit the click behavior to "Go to a custom destination" -> "URL"
3. Enter a URL with the a {{variable}}, click Done and save the dashboard
4. Reload the dashboard and edit it again
5. Try to remove the click behavior and go back to Metabase actions menu

**The Done button is light and cannot be clicked for saving. If I click save on the dashboard it is saved, but after reload the click behavoir is still with the "URL"** 

**Expected behavior**
Reset to default click behaviour (action menu)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3726156/121946941-c078f980-cd55-11eb-86d5-66e164e055dd.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 89.0 (64-Bit) & Microsoft Edge Version 91.0.864.48 (Offizielles Build) (64-Bit)
- Your operating system: Windows 10 21H1
- Your databases: Postgres
- Metabase version:  0.39.3
- Metabase hosting environment: Debian
- Metabase internal database:  Postgres

**Severity**
There is no way to go around this bug with some method.

**Comment by flamber** [comment]
Hi @maxschloegl 
It's correct that the "Done" button is disabled. which might be distracting you from the main problem.
But I'm quite sure that you're seeing this issue #13595, which means that the question actually has the information stored, so when you remove the Click Behavior on the dashboard card (restoring the action menu), then it gets the old information from the question, when the dashboard is loaded.

**Comment by brunobergher** [comment]
Can't repro anymore.
