### ISSUE TITLE
"Run selected text" in Native editor does not include filter widget value and can return incorrect results

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16584]
**Describe the bug**
When using filter variables in Native editor and selecting text to use the "Run selected text", then filter variables are not included, which throws an error. But if the filter has a default value, then that is used instead, leading to incorrect results.

**To Reproduce**
1. Native query > Sample Dataset > set mydate to Date filter
```sql
select count(*) from PRODUCTS
where year(CREATED_AT) = year({{mydate}}::date) --empty space
```
2. Set any date (today) in the filter widget and run query - shows **0** results as expected
![image](https://user-images.githubusercontent.com/1447303/122036985-6ec38400-cdd4-11eb-9b55-97e6efc2cbbf.png)
3. Now select the query text and run it - fails with `Cannot run the query: missing required parameters: #{"mydate"}`
![image](https://user-images.githubusercontent.com/1447303/122037038-800c9080-cdd4-11eb-97a5-4eb8677bcbc5.png)
4. Now set "Default filter widget value" to `2019-12-01` and select the query text and run it - returns **18** results, which wrong
![image](https://user-images.githubusercontent.com/1447303/122037341-c530c280-cdd4-11eb-8c5c-30b065987095.png)

**Expected behavior**
"Run selected text" should include the variables selected.

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.39.3 and `master`

**Additional context**
The "Run selected text" is not particular useful via the Run-button and just causes more confusion than good - #15315
There's already a context menu - #13450 - so perhaps let the Run-button and CTRL+Enter always run the entire query.

**Comment by dzcpy** [comment]
Any solutions?

**Comment by gio6776** [comment]
Any solutions on that?
