### ISSUE TITLE
No way to return to SSO login from password login

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16594]
Assumption: SSO is enabled.

## To Reproduce

1. Go to Admin
2. On left menu, click `Authentication`
3. In section titled `Sign in with Google`, click `Configure`
4. Add any string to `Client ID` input
5. Click `Save Changes`
6. Sign Out of Metabase
7. Click on `Sign in with email`

Now if you want to go back to Google authentication, there is no way.

#### Context: 

<img src="https://user-images.githubusercontent.com/380816/122101454-b1905680-cdea-11eb-955a-a3f07f103fef.png" width=300 />

**Comment by flamber** [comment]
Same is true for "Forgot password" page.
