### ISSUE TITLE
How to adjust the image size of a row

### ISSUE THREAD

**Issue by yihongz** [metabase/metabase#16606]
Hi all, thanks for the awesome software!

I've using Metabase for a few days, and now I'm trying to put a image inside a row. Am I able to adjust the image size ? If so, how can I do that ?

![image](https://user-images.githubusercontent.com/4431390/122123135-07252d00-ce04-11eb-9a03-2cdf52529729.png)

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Duplicate of #10260
