### ISSUE TITLE
Column not showing up

### ISSUE THREAD

**Issue by maccman** [metabase/metabase#1661]
I have a column named `disabled` - it's not showing up even with multiple restarts of Metabase. It is definitely present on the table.

**Comment by agilliland** [comment]
Hmmm.  What database is this using and what is the column type?  Any chance you can run a sync on your database and capture the logging output to paste it here?

One other thought, if you go to the administration area, click on `Metadata` at the top, and navigate to the table, does the column show up in the list of columns for that table?

**Comment by camsaul** [comment]
Motion to close since we're unable to reproduce / asked for more info 3 months ago and haven't heard back

**Comment by agilliland** [comment]
:+1:
