### ISSUE TITLE
Archive page shows error for users with collection curate permissions and no data permissions

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#16617]
Users with collection curate permissions and no data permissions see an error when visiting the archive page. Note that they can archive and unarchive items (unarchiving is currently broken, see issue #15253 and PR #16590)

**To Reproduce**
1. Log in as a non-admin user with collection curate access and no data permissions
2. Go to `/collection/archive/`
3. See an error message like `Input to add-table-db-id-clause does not match schema: [0;33m [(named (named (not (instance? clojure.lang.IPersistentMap nil)) "Valid map") query) nil]`

**Expected behavior**
A user should see a list of archived items

**Screenshots**

<img width="1433" alt="Screenshot 2021-06-16 at 11 52 46" src="https://user-images.githubusercontent.com/17258145/122189752-de4f7700-ce99-11eb-86c7-d2b68fdb84f5.png">

**Information about your Metabase Installation:**

Metabase version: latest master ([commit](https://github.com/metabase/metabase/commit/df02ca999bdf0418eb8527ccfdfcfe9fbe8d6505))
Metabase hosting environment: local, master branch
Metabase internal database: H2 (default), sample dataset

**Comment by dpsutton** [comment]
I was trying to reproduce this. 

I have a group called noaccess.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/6377293/125362947-5ee88280-e335-11eb-9d94-7b831a1ec17d.png">

With user `test@test.com` in it
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/6377293/125362988-6c9e0800-e335-11eb-94d6-31047edc233e.png">


That group has curate access to collections
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/6377293/125362839-306aa780-e335-11eb-9f1a-86c5614ab478.png">

But i cannot trigger the bug:
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/6377293/125362922-55f7b100-e335-11eb-93f7-5754cf9e34cf.png">


When that group has no access to collections I also still cannot reproduce
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/6377293/125362787-18932380-e335-11eb-96b4-ba9963a69bf4.png">


I also used a prebuilt db that had some users without data access.
logging in with user `nodata@metabase.test` and password `12341234`
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/6377293/125362451-8e4abf80-e334-11eb-8489-9acf3c79ea03.png">
