### ISSUE TITLE
Auto generated question name breaks and shows [UNKNOWN] when using a time dimension

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1663]
Just noticed that if you break out by a time dimension our auto generated question name shows "UNKNOWN" for the grouped by portion. My guess is this might have occurred after we added time granularities?
<img width="654" alt="screen shot 2015-12-09 at 1 17 01 pm" src="https://cloud.githubusercontent.com/assets/5248953/11699082/38a9b944-9e77-11e5-936e-61798b6efa1c.png">

**Comment by tlrobinson** [comment]
This is actually fixed in the segments branch #1624

**Comment by camsaul** [comment]
Closing since @tlrobinson mentioned it was fixed in #1624
