### ISSUE TITLE
Output of ldap-search-result->user-info does not match schema: [0;33m {:email (not ("有效的邮箱地址" "cuser02"))} [0m

### ISSUE THREAD

**Issue by eeennn** [metabase/metabase#16649]
**Describe the bug**
i get the error when i login metabase using ldap user. the error is "Output of ldap-search-result->user-info does not match schema: \n\n\t   {:email (not (\"valid email address\" \"cuser02\"))}  \n\n"

**Logs**
browser console: 
2021-05-30 19:50:23,333 DEBUG middleware.log :: POST /api/session 400 43.8 ms（0个数据库调用） 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "Output of ldap-search-result->user-info does not match schema: \n\n\t   {:email (not (\"有效的邮箱地址\" \"cuser02\"))}  \n\n",
   :data
   {:type :schema.core/error,
    :schema
    (maybe
     {:dn (constrained Str "Non-blank string"),
      :first-name (constrained Str "Non-blank string"),
      :last-name (constrained Str "Non-blank string"),
      :email (constrained Str "有效的邮箱地址"),
      :groups [(constrained Str "Non-blank string")],
      Keyword Any}),
    :value
    {:dn "cn=cdc user02,cn=Test,dc=passwd.ldap,dc=gdyc",
     :first-name "cuser02",
     :last-name "user02",
     :email "cuser02",
     :groups []},
    :error {:email (not ("有效的邮箱地址" "cuser02"))},
    :status-code 400},
   :at [metabase.api.session$do_http_400_on_error invokeStatic "session.clj" 136]}],
 :trace
 [[metabase.api.session$do_http_400_on_error invokeStatic "session.clj" 136]
  [metabase.api.session$do_http_400_on_error invoke "session.clj" 132]
  [metabase.api.session$fn__73687 invokeStatic "session.clj" 156]
  [metabase.api.session$fn__73687 invoke "session.clj" 144]
  [compojure.core$wrap_response$fn__1996 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1980 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1985 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 151]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.api.session$_PLUS_log_all_request_failures$fn__73817 invoke "session.clj" 355]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.api.routes$fn__75727$fn__75729 invoke "routes.clj" 70]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.server.routes$fn__77998$fn__77999 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.server.routes$fn__77986$fn__77988 invoke "routes.clj" 41]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75718 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__75715 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__77914$fn__77915 invoke "log.clj" 195]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__77914 invoke "log.clj" 189]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__77550 invoke "browser_cookie.clj" 30]
  [metabase.server.middleware.security$add_security_headers$fn__75680 invoke "security.clj" 142]
  [metabase.server.middleware.json$wrap_json_body$fn__77695 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__77713 invoke "json.clj" 98]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__78255 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__78271 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35522 invoke "misc.clj" 58]
  [metabase.server.middleware.session$bind_current_user$fn__42494$fn__42495 invoke "session.clj" 248]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 229]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 221]
  [metabase.server.middleware.session$bind_current_user$fn__42494 invoke "session.clj" 247]
  [metabase.server.middleware.session$wrap_current_user_info$fn__42481 invoke "session.clj" 207]
  [metabase.server.middleware.session$wrap_session_id$fn__42467 invoke "session.clj" 153]
  [metabase.server.middleware.auth$wrap_api_key$fn__75613 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__78175 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35505 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35530 invoke "misc.clj" 75]
  [ring.middleware.gzip$wrap_gzip$fn__78217 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35533 invoke "misc.clj" 92]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__77931 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__77494 invoke "server.clj" 71]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run "Thread.java" 748]],
 :cause
 "Output of ldap-search-result->user-info does not match schema: \n\n\t   {:email (not (\"有效的邮箱地址\" \"cuser02\"))}  \n\n",
 :data
 {:type :schema.core/error,
  :schema
  (maybe
   {:dn (constrained Str "Non-blank string"),
    :first-name (constrained Str "Non-blank string"),
    :last-name (constrained Str "Non-blank string"),
    :email (constrained Str "有效的邮箱地址"),
    :groups [(constrained Str "Non-blank string")],
    Keyword Any}),
  :value
  {:dn "cn=cdc user02,cn=Test,dc=passwd.ldap,dc=gdyc",
   :first-name "cuser02",
   :last-name "user02",
   :email "cuser02",
   :groups []},
  :error {:email (not ("有效的邮箱地址" "cuser02"))},
  :status-code 400},
 :message
 "Output of ldap-search-result->user-info does not match schema: \n\n\t   {:email (not (\"有效的邮箱地址\" \"cuser02\"))}  \n\n",
 :value
 {:dn "cn=cdc user02,cn=Test,dc=passwd.ldap,dc=gdyc",
  :first-name "cuser02",
  :last-name "user02",
  :email "cuser02",
  :groups []},
 :error {:email (not ("有效的邮箱地址" "cuser02"))}}

**Expected behavior**
i should successfully login metabase.

**Screenshots**
![图片](https://user-images.githubusercontent.com/28283487/122351558-d0c0ec80-cf80-11eb-9848-eae3a10148c5.png)
![图片](https://user-images.githubusercontent.com/28283487/122351631-e6cead00-cf80-11eb-96e7-db9333b36d18.png)

**Information about your Metabase Installation:**
 Metabase version: 0.39.3

**Comment by flamber** [comment]
Hi @eeennn 
You need to provide an email in the email attribute.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
