### ISSUE TITLE
API endpoint (/api/card/collections) does not exist

### ISSUE THREAD

**Issue by sergekzhr** [metabase/metabase#16650]
**Describe the bug**
Can't move cards to another collection using [POST /api/card/collections](https://www.metabase.com/docs/latest/api-documentation.html#post-apicardcollections)

**Response from the server**
404 Not Found
"API endpoint does not exist."

**To Reproduce**
1. Send POST ...api/card/collection
2. Body: {"card_ids": [122, 133], "collection_id": 23}

**Expected behavior**
The cards 122, 133 went to collection 23

**Information about your Metabase Installation:**
- Metabase version: 0.39.4

**Comment by flamber** [comment]
Hi @sergekzhr 
I cannot reproduce. It works fine on 0.39.4. Are you sure you are sending a POST? Check Admin > Troubleshooting > Logs.
```
curl 'http://localhost:3000/api/card/collections' --compressed -H 'Content-Type: application/json' -H 'Cookie: metabase.SESSION=...' --data-raw '{"card_ids": [388, 390], "collection_id": 4}'
```
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
