### ISSUE TITLE
Label "weeks" consistently

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1665]
Currently we show "23th - 2015" in the card/dashboard charts, and "Week 23 - 2015" in pulses. We should decide on the best way to represent weeks and use that format everywhere.

In tooltips and other detail views we should also show the actual range, e.x. "June 1, 2015 - June 7, 2015"

**Comment by mazameli** [comment]
I'd tend towards "Week 23, 2015" because I think it's the clearest. WDYT, @kdoh?

**Comment by kdoh** [comment]
In an ideal case I think I'd want to see "23rd week of 2015" (at least from an english speaking point of view).

So effectively the formula becomes <value> <[st, rd, th (etc)]>  week of <year>

**Comment by kdoh** [comment]
@mazameli Did you have any feedback on my proposal here?

**Comment by jaypeedevlin** [comment]
+1 to showing the actual range on tooltips FWIW @tlrobinson

**Comment by mazameli** [comment]
@kdoh I'm replying 3 months later (lolface), but yeah, I actually think we need to change this to the date ranges, like June 1, 2015 – June 7, 2015, because it's a lot of cognitive load to expect the user to reverse engineer the date from "23rd week of 2015." Like, I have no idea when that is off the top of my head. End of May? ¯\_(ツ)_/¯

**Comment by agilliland** [comment]
What about a hybrid that provides the week # combined with the starting date of the week?  Something like `Week 23 - June 1, 2015`

**Comment by tlrobinson** [comment]
I think those are both much to long to use as axis tick labels. We could put the full range in a tooltip though.

**Comment by mazameli** [comment]
Ah, yeah, I was conflating axis labels with tooltips. +1 to Tom's suggestion: keep `Week 23` as axis label, but use `June 1–7, 2015` for tooltips. (I don't think you need to write the year out twice.) Bonus points for using an n-dash (–) instead of a hyphen.

**Comment by mazameli** [comment]
If the week spans months, I guess you'd write, `June 29 – July 5, 2015`

**Comment by tlrobinson** [comment]
I think we can close this as a duplicate of #3449
