### ISSUE TITLE
Boolean filter Popovers show visually chopped `True` and `False` 

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16658]
Related to: #16655

## To reproduce:

1. Ask a question, Native question
2. In the SQL editor, type the following:
```
select 0::integer as "integer", true::boolean AS "boolean"
union all
select 1::integer as "integer", false::boolean AS "boolean"
union all
select null as "integer", true::boolean AS "boolean"
union all
select -1::integer as "integer", null AS "boolean"
```
3. Save question.
4. Click _Explore results_ button (top right)
5. Click on the _boolean_ column, choose Filter by this Column

Note that `True` and `False` get cut off at the bottom.

![image](https://user-images.githubusercontent.com/7288/122453374-22587f80-cf5f-11eb-88bc-1aeb49f5d7ef.png)

**Comment by ariya** [comment]
@gusaiani This is likely caused by PR #16308.

To experiment: revert commit 3e4aa7db and try the repro steps. The popover is correctly rendered:

![image](https://user-images.githubusercontent.com/7288/122850184-a7c29380-d2c1-11eb-94eb-cd621b43939a.png)
