### ISSUE TITLE
Dashboard filters can stay in URL query string after changing dashboards via search dropdown

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#16663]
**Describe the bug**
If you are on a dashboard with filters, then use the global search drop down suggestion to go to another dashboard that doesn't have any filters, the filters of the first dashboard are retained in the URL query string.

**Logs**
Nothing in either log that appears relevant.

**To Reproduce**
1. Go to any dashboard with filters that have default values, note the URL has filters in the query string.
2. Use the global search to locate another dashboard that doesn't have any parameters, **do not press enter** to navigate to the search results page.
3. From the list of suggestions in the dropdown, click that no filters dashboard.
4. Note the dashboard number in the URL has changed, but the URL now incorrectly includes the previous dashboards filters in the query string.

**Expected behavior**
Dashboards with no parameters shouldn't have any in the URL query string.

**Screenshots**
Filters as expected on the first dashboard and in the URL
![image](https://user-images.githubusercontent.com/4504437/122483523-e688ed00-d026-11eb-89e3-0482ada5a4b6.png)

Use global search to find the other dashboard with no filters (1), click it in the dropdown to navigate (2).
![image](https://user-images.githubusercontent.com/4504437/122484191-3a480600-d028-11eb-8a84-d11d2f60dc78.png)

Filters incorrectly retained in the URL of the second dashboard which doesn't have any filters
![image](https://user-images.githubusercontent.com/4504437/122483586-091b0600-d027-11eb-987d-30102ea2b739.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.2",
      "date": "2021-05-17",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```
Same behaviour noted in Chrome.

**Severity**
Doesn't impact functionality at all from what I can see. If you navigate in the same manner to another dashboard with filters the URL is correct and filters are applied as expected.

**Comment by flamber** [comment]
Likely related to #13708, since filter options are preserved in state.

**Comment by uladzimirdev** [comment]
it looks like the problem has been fixed, at least it works fine for me locally https://www.loom.com/share/cee788f2d2bd4a74b6b222afad5071ce
