### ISSUE TITLE
[Binning] UI inconsistencies for bucket display on tables from explicitly joined tables

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16675]
As part of on ongoing process of documenting and covering binning issues (#16387), I noticed a few irregularities that are not strictly bugs, but definitely feel weird.

Binning options (buckets) render differently for the columns on explicitly joined table than they do for any other scenario.

#### To reproduce:
Longitude
1. New Custom question > Sample Dataset > Orders
2. Join with "People" on User ID = ID
3. Summarize, Count of Rows and then click "Pick a column to group by"
4. Under the "People" (can be aliased as "People -> User") choose `Longitude` binning options
5. `Don't bin` doesn't exist - it displays as `Default`
6. Also, there is no Bin every `X` degrees. It displays as `X°`

Number
1. New Cusotm question > Sample Dataset > Orders
2. Join with "Products" on Product ID = ID
3. Summarize, Count of Rows and then click "Pick a column to group by"
4. Under the "Product" (can be aliased as "Products") choose `Price` binning options
5. `Don't bin` doesn't exist - it displays as `Default`

*For both number and longitude, the default "Auto bin" option is displayed as "Auto binned".

![image](https://user-images.githubusercontent.com/31325167/122578627-582b6000-d054-11eb-8150-ba00deb7b093.png)

![image](https://user-images.githubusercontent.com/31325167/122579334-18b14380-d055-11eb-994e-528cd559869d.png)

**Comment by nemanjaglumac** [comment]
While working on the repro for this issue, I realized even the time series options are affected. More precisely, the extended options like "Minute of the Hour", etc.

For regular tables it renders as "Minute of Hour", while for expliocit options it renders as "Minute of hour" (notice the lowercased h).

**Comment by ariya** [comment]
Fun fact: _Auto binned_ came from `frontend/src/metabase-lib/lib/Dimension.js` while _Auto bin_ is originated in `src/metabase/api/table.clj`.
