### ISSUE TITLE
X-ray automatic dashboards don't work when grouped on a custom column

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#16680]
**Describe the bug**
When a question is grouped on a custom column the X-ray and Compare drill-down actions lead to an error page.

**To Reproduce**
Remove the `includesExpressionDimensions` booleans found here https://github.com/metabase/metabase/blob/5c81fcbc7c06d3768e2006da635e41ab9d1e779b/frontend/src/metabase/modes/components/drill/AutomaticDashboardDrill.jsx#L29 and here https://github.com/metabase/metabase/blob/5c81fcbc7c06d3768e2006da635e41ab9d1e779b/frontend/src/metabase/modes/components/drill/CompareToRestDrill.js#L30 so that you can see the X-Ray and Compare options in the drilldown menu.

Then do the following...

1. Custom question > Sample Dataset > Orders
2. Custom Column 1 + 1 as "TestColumn"
3. Summarize Count by "TestColumn" and CreatedAt:Month
![image](https://user-images.githubusercontent.com/1447303/93864319-fe645800-fcc4-11ea-9035-f4ac58993878.png)
4. Click on a point in the series and then click X-Ray or "Compare..." actions beneath the "Automatic explorations" label.
<img width="286" alt="Screen Shot 2021-06-18 at 11 52 54 AM" src="https://user-images.githubusercontent.com/13057258/122607791-f953ef80-d02f-11eb-880f-3a1a225182b4.png">
5. See the next page, which shows an error message: `No method in multimethod 'automagic-analysis' for dispatch value: null`
<img width="642" alt="Screen Shot 2021-06-18 at 11 53 03 AM" src="https://user-images.githubusercontent.com/13057258/122607830-08d33880-d030-11eb-89f6-f2e5a22091b4.png">

**Comment by markbastian** [comment]
Here's a [visual review](https://www.loom.com/share/bc7b157cfb704828a2cc8a56329b1c26?sid=ab8bed8a-8ab7-4fab-a149-4ce5f2c956ef) of the result.
