### ISSUE TITLE
Where is custom sql editor?

### ISSUE THREAD

**Issue by omidfi** [metabase/metabase#1670]
It should be a dumb question, but I can't seem to find the place to insert custom sql for questions! I'm running ht jar files I downloaded yesterday.

**Comment by tlrobinson** [comment]
It's a bit hard to find if you don't know what you're looking for, but there's a toggle button in the top right that's visible when you start a new question (but not on existing questions, or after you start editing the query). It looks like this:

![image](https://cloud.githubusercontent.com/assets/18193/11741810/35578a3e-9fb0-11e5-9cfb-a823602bc093.png)

See "Using SQL" here: http://www.metabase.com/docs/v0.13.1/users-guide/03-asking-questions.html
