### ISSUE TITLE
Reset password email not reflecting updated domain

### ISSUE THREAD

**Issue by sirdmon** [metabase/metabase#16700]
**Describe the bug**
We are running a self hosted metabase instance and updated the domain on the service provider side to one we own. The problem arises when we proceed to reset password in the login screen, and the reset instructions, specifically the reset password link,  points at the wrong domain. 
We've tried to redeploy metabase setting up `MB_SITE_URL`  variable to the updated domain, but we are still seeing that problem.

**Expected behavior**
We expect the reset password link to redirect to the right domain (updated one)

**Information about your Metabase Installation:**

- Metabase version:  0.39.2
- Metabase hosting environment: Platform.sh
- Metabase internal database: psql v13

**Comment by flamber** [comment]
Closing in favor of #13084, which we're working on fixing. Either use the interface, or the environment variable to define a setting, but combining them can cause some confusion.
I would recommend shutting down Metabase, remove the environment variable, change the address in the application database table `setting` (look for the row with the key `site-url`), and then start Metabase again.
