### ISSUE TITLE
Docker tags for the hub repository

### ISSUE THREAD

**Issue by caske33** [metabase/metabase#1671]
It would be nice if there were tags on the docker registry so we can specify which version of metabase we want to deploy, so we can manually control which version is running.

**Comment by agilliland** [comment]
There are tags on the dockerhub repo ... https://hub.docker.com/r/metabase/metabase/tags/

**Comment by caske33** [comment]
Oh sorry, my bad. I never saw the tab before. I always looked for a description at the top of the README :(
