### ISSUE TITLE
The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]

### ISSUE THREAD

**Issue by robinpapa** [metabase/metabase#16718]
Hey awesome developers!

Upgraded to the latest version via Docker and now Metabase won't connect to my Microsoft SQL database. 

`The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]`

It's a MSSQL 2014 one, I believe, so it has no support for TLS higher than 10?
SSL option is turned off, so it's a bit strange it wants to make an SSL-encrypted connection.

Can anyone point me in the right direction? Can't seem to find anything related in closed or open issues.

Thanks!

**Comment by flamber** [comment]
Hi @robinpapa 
TLS1.0 isn't supported much any where. You should be able to upgrade your MSSQL:
https://support.microsoft.com/en-us/topic/kb3135244-tls-1-2-support-for-microsoft-sql-server-e4472ef8-90a9-13c1-e4d8-44aad198cdbe
Or try adding `encrypt=false` to the Connection String in Admin > Databases > (your-db)
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by nm17** [comment]
@flamber it still doesn't make sense, why does Metabase create a TLS connection when it's explicitly told not to do that?

**Comment by flamber** [comment]
@nm17 Metabase always tries to enable a secure connection by default during setup. This is by design to enhance security. If you explicitly need something different, then you'll have to create the connection in the application database table `metabase_database`.

**Comment by paoliniluis** [comment]
DO NOT USE TLS v1 or v1.1, those protocols are considered insecure in 2024
