### ISSUE TITLE
how to config jdbc jar package for different src database?

### ISSUE THREAD

**Issue by suzixin** [metabase/metabase#16711]
Hi, team

I want to add a new database with [opengauss](https://gitee.com/opengauss/openGauss-server)  type, which is developed on the basis of PostgreSQL.
I need to  replace the jar package of the PostgreSQL version with the jar package of the opengauss version, such as https://jdbc.postgresql.org/download.html .
I don't know where can I config this.

thanks

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
