### ISSUE TITLE
"Friendly Errors" should allow a user to pull out the precise error

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1672]
In helping folks debug connection issues or serialization bugs, it would be very useful to be able to pull up the exact error that occurred. While it's helpful to provide a friendly and nonthreatening message we should make it possible to debug this sort of stuff without resorting to looking at network connections in the inspector.

**Comment by mazameli** [comment]
New arrangement for error messages. Clicking on `Details` shows the full error message content.
![new error messages](https://cloud.githubusercontent.com/assets/2223916/12402249/92251e68-bde0-11e5-9b0b-9e4d9f36a338.png)

Expanded error message, smallest size (min height for error message box = 65px). Width of error message box is 500px.
![expanded error](https://cloud.githubusercontent.com/assets/2223916/12402282/b5d86f40-bde0-11e5-99dc-881a95a3a237.png)

Expanded error message, large version. Horizontal and vertical scrolling. Max height of box = 300px.
![expanded error large](https://cloud.githubusercontent.com/assets/2223916/12402316/e395cf18-bde0-11e5-92a2-6d6a1a4178f9.png)
