### ISSUE TITLE
Native editor autocomplete suggestions makes object lookup without `limit`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16736]
**Describe the bug**
Native editor autocomplete suggestions makes object lookup without `limit`, which means it can take several seconds before suggestions are shown on large instances (100k+ tables and fields).
These requests are causing a lot more load on the application database.

https://github.com/metabase/metabase/blob/master/src/metabase/api/database.clj#L310

**To Reproduce**
1. Native query > select a database, which has many tables/columns - example "Horror Show"
2. Type `t` and watch the network traffic for the request `/api/database/:id/autocomplete_suggestions?prefix=t` and monitor the load on the application database.

**Information about your Metabase Installation:**
I think it's always been like this, but only tested 0.39.4 and master.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by vla-figueiredo** [comment]
Same problem here!

**Comment by camsaul** [comment]
We should add a default limit to the API endpoint, @flamber suggested 50 in the Notion thread. I think that sounds reasonable
