### ISSUE TITLE
Confusing text alignment in pivot table

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16752]
**Describe the bug**

Headings and column values in pivot tables are aligned differently which makes the pivot table very hard to understand.

**To Reproduce**

1. Using Sample Data, summarize with Count
2. Group by Quantity, User->State, Product->Category
3. Visualize as pivot table
4. Rearrange so Product->Category and User->State are rows, while Quantity is columns.
5. Result shown below: hard to understand what's supposed to line up with what.

![Screen Shot 2021-06-24 at 8 44 04 AM](https://user-images.githubusercontent.com/911566/123265043-a2836580-d4c8-11eb-841e-189ae48e9ca3.png)

**Expected behavior**

Same alignment for headings and column values would help.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azulsystems.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-LTS",
    "os.name": "Mac OS X",
    "os.version": "11.2.3",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-06-15",
      "tag": "v1.39.4",
      "branch": "release-x.39.x",
      "hash": "f538050"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

Low severity, but came up in a demo.

**Comment by marcoruggine** [comment]
I think my problem with Pivots can relate to this:
- Headers don't get the proper naming
- Columns don't fit all the space assigned in a dashboard (screenshot from query not dashboard)

<img width="1327" alt="Screenshot 2021-11-15 at 14 24 50" src="https://user-images.githubusercontent.com/20041428/141789554-608870bd-a9f1-4084-8462-148d966baaa8.png">

**Comment by flamber** [comment]
@marcoruggine You're looking for #15353 and #14350. Please just click :+1: instead of leaving a `+1` comment.
