### ISSUE TITLE
Adding Pin Map Error: "Can't find variable: google"

### ISSUE THREAD

**Issue by hamin** [metabase/metabase#1675]
I'm trying to add a pin map. I have a Latitude and Longitude field in my table that's properly marked as such. The query runs successfully, but when I try to change the Visualization to 'Pin Map' I'm getting this error: 'Can't find variable: google'. I don't see anywhere in the admin settings to add a Google Maps API key if that's the issue.

**Comment by tlrobinson** [comment]
@hamin I'm not able to reproduce this.

Could you try with the "People" table in the "Sample Dataset" database that's included with Metabase (you can temporarily re-add it at `/admin/databases` if you removed it)

Can you also check the developer tools network panel to see if https://maps.googleapis.com/maps/api/js is being loaded?

**Comment by hamin** [comment]
I'm not sure how I was able to recreate that issue. But this is what I'm trying with the sample data set now.
Take a look at the attached images. I'm actually unable to group by Latitude and Longitude which the pin visualization requires. Am I doing something wrong here?

<img width="988" alt="screen shot 2016-01-25 at 8 08 54 pm" src="https://cloud.githubusercontent.com/assets/28212/12569752/9e00242a-c39f-11e5-8f1a-6792efa4b31f.png">
<img width="901" alt="screen shot 2016-01-25 at 8 09 33 pm" src="https://cloud.githubusercontent.com/assets/28212/12569753/9f9a9108-c39f-11e5-906f-7abdb869f1af.png">

**Comment by tlrobinson** [comment]
You don't need to group by lat/lon, you can plot individual rows. But if you'd like to you can mark the lat/lon field types as "dimensions".
![screenshot 2016-01-25 17 15 18](https://cloud.githubusercontent.com/assets/18193/12569823/38c617d0-c387-11e5-8c51-bb7650b26643.png)

**Comment by hamin** [comment]
@tlrobinson gottya. Still getting google maps errors. Attaching screenshots

<img width="1228" alt="screen shot 2016-01-25 at 8 49 19 pm" src="https://cloud.githubusercontent.com/assets/28212/12570400/47cb5312-c3a5-11e5-8573-cce3ad89fb7e.png">
<img width="1259" alt="screen shot 2016-01-25 at 8 49 54 pm" src="https://cloud.githubusercontent.com/assets/28212/12570402/4ac85e5c-c3a5-11e5-9529-cd7c8afe4eed.png">

**Comment by hamin** [comment]
@tlrobinson Gottya. Getting Google maps issues still. Attaching screenshots

<img width="1228" alt="screen shot 2016-01-25 at 8 49 19 pm" src="https://cloud.githubusercontent.com/assets/28212/12570424/79dc1c42-c3a5-11e5-8ba5-e51fdacaff37.png">
<img width="1022" alt="screen shot 2016-01-25 at 8 51 08 pm" src="https://cloud.githubusercontent.com/assets/28212/12570425/7c068e12-c3a5-11e5-9172-4fff31125bde.png">

**Comment by tlrobinson** [comment]
@hamin Ok thanks, looks like it's due to the Content-Security-Policy headers we added recently. Are you on Safari?

**Comment by hamin** [comment]
@tlrobinson ah yes on Safari. I just tested on Chrome and it seems to be working fine. Anything in particular to make this work in Safari?

**Comment by tlrobinson** [comment]
@hamin Pull Request #1803 will fix this. You'll have to build it from source or wait until the next release, sorry.

**Comment by hamin** [comment]
@tlrobinson that's great...good to know, I don't mind switching to Chrome when I need to do this. But will keep an eye out for the release. Plz close this fix once the release out :). That way I'll know when to update :). Thanks again

**Comment by gavinpoynton** [comment]
Hi. Looks good. Same error in MAC OSx client - "Can't find variable: google" - assume its the same issue.
