### ISSUE TITLE
Site URL can sometimes be incorrectly defined during startup

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16754]
**Describe the bug**
Continuation of #14819
Sometimes during startup (e.g. K8s pods), the `site-url` can incorrectly be detected from a health-checker or another request, which can then set the URL to something incorrect (like the server local IP).
This happens even if it is defined in `setting` table. Seems like it might be a race-condition between establishing an appdb connection and when a request comes in that makes it auto-guess the URL, which is then used instead of the value from appdb.

https://github.com/metabase/metabase/blob/ce939219f8a3e28ecb00deb232154780a1dcfcef/src/metabase/server/middleware/misc.clj#L34-L58

**Expected behavior**
1. Never auto-guess the URL unless Metabase is in setup-mode.
2. Never auto-guess if `MB_SITE_URL` is defined.

**Information about your Metabase Installation:**
Have seen this sporadically happen on many previous versions thru latest 39.4, but I cannot reproduce.

**Severity**
The Site URL is a critical part of a lot of functionality in Metabase.

**Comment by noahmoss** [comment]
For point 2, #16644 fixed the precedence between env variables and db settings, so now if MB_SITE_URL is defined, auto-guessing won't happen. I think this drops the severity of this issue significantly.

I'm working on a PR to limit auto-guessing to only the `/setup` endpoint, and to add some test coverage.
