### ISSUE TITLE
Browser needs to be restarted to pick up code changes in Cypress open environment.

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16775]
When we run Cypress locally using a headless browser, code changes are not updated in the browser.

Right now we need to close the browser and **reclick on Cypress's UI** to run the integration tests.

From then on, the browser does pick up the changes automatically.

## To Reproduce

1. `yarn test-cypress-open`
2. choose one e2e test to run
3. change code in that test or in implementation. Can be something very obvious.

**Expected behavior**
Change should show up in Cypress run of the test the very first time.

**Severity**
Low

**Comment by nemanjaglumac** [comment]
This seems to be fixed by the latest webpack upgrade. Can you please check and confirm this @gusaiani ?

**Comment by gusaiani** [comment]
@nemanjaglumac Yes, confirmed.

It's interesting: seems like the retriggers are quite slow until we close Chrome and use Cypress UI to start some tests again.

But now they do retrigger, yes.

**Comment by gusaiani** [comment]
Fixed by #16113

**Comment by nemanjaglumac** [comment]
I've also noticed it is quite slow.
Once we merge babel upgrade, I'll try to update cypress webpack preprocessor and see how it behaves then.
