### ISSUE TITLE
Pulses should display timeseries sparklines in the correct order

### ISSUE THREAD

**Issue by bernardosrulzon** [metabase/metabase#1677]
I was testing Pulse and got some very weird visualizations when working with a Redshift time series.

**1. SQL looked like this:** `SELECT event_tstamp::date, count(*) as requests FROM events GROUP BY 1`

**2. Chart looks just right:**
![pulse_2](https://cloud.githubusercontent.com/assets/6955526/11768076/0e446732-a1a9-11e5-8839-4f8e8543b339.png)

**3. Pulse looks very weird!**
![pulse](https://cloud.githubusercontent.com/assets/6955526/11768077/0ed0c4d4-a1a9-11e5-820f-94ae91c546b0.png)

**Comment by agilliland** [comment]
The reason that would happen is because the data is out of order.  It's possible that we are fixing up the ordering before we do the charting of the visualization in the browser, but it's not being applied for the pulse data.

Try adding `ORDER BY 1` to the end of your query and that should fix it.

**Comment by bernardosrulzon** [comment]
You're right - it did the trick! Thanks! ;)

**Comment by agilliland** [comment]
This is now being tracked in #2037
