### ISSUE TITLE
Data model setting fields briefly flash old value

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16780]
**Describe the bug**
When you update the name or description of a column in the data model settings, the old value is briefly flashed when you click out of the field.

**To Reproduce**
1. Go to Admin -> Data model
3. Click on a table in any database
4. Type something into the name or description field of a column
5. Click outside the field to save the new value

**Expected behavior**
Should not flash the old value

**Screenshots**

https://user-images.githubusercontent.com/32746338/123498641-466f2d00-d5ff-11eb-8d85-00725676f28a.mov

**Information about your Metabase Installation:**

Current master (`v0.40.0-SNAPSHOT`) on Firefox 89.0.1 on macOS Big Sur

**Comment by flamber** [comment]
Likely the same problem as #15634 - depending on connection latency, this can be a lot more than a "briefly flash".

**Comment by brunobergher** [comment]
Can't repro anymore
