### ISSUE TITLE
Responsive dashboard is too aggressive

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16786]
**Describe the bug**
Responsive dashboard is too aggressive, and changes current dashboards.

**Workaround** Add Textboxes to the dashboard, where empty spaces is needed.

**To Reproduce**
0.39.4:
![image](https://user-images.githubusercontent.com/1447303/123544297-e7223180-d752-11eb-97dd-a600ba9a4d25.png)
master:
![image](https://user-images.githubusercontent.com/1447303/123544303-f4d7b700-d752-11eb-90de-d0858cd8656d.png)

**Expected behavior**
Not to change existing dashboards and allow horizontal row spacing.

**Information about your Metabase Installation:**
Tested `c040f15` (2021-06-25)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
I disagree that this is a bug or a regression. It is a subjective UX change that some users are reporting a preference for, while some others are reporting dissatisfaction.

Please do not "fix" this without checking in with Product — we need to gather more impressions and opinions on this first.

**Comment by brunobergher** [comment]
As Maz said, this is by design and until we build more confidence that it is indeed a problem, it shouldn't be considered a bug to be fixed.

**Comment by flavienSindou** [comment]
Haha I think the good solution you'd have been to create the feature and let the choice to the user thanks to a toggle button. Then usage statistics would have give you the answer to the question "is it helpful or not".

From my point of view, it is a non sense to force people to use a specific view mode.... Hopefully, I can still choose what chart type I display in my cards even though I cannot organize my dashboard the way I want...

**Comment by saeedesmaili** [comment]
Even if it's a feature, not a bug, it's a bad and annoying feature. Everyone in my team wants to design their dashboard in a way that they think it's visually appealing. So they may want to put a text box or a chart somewhere in the middle.

**Comment by lukeman** [comment]
I love the new dashboard layout—adding or rearranging questions is 1000% more intuitive than before and as bold as the reworking is I've been pleased with how natural it has felt to this long-time user.

The only pain-point I've experienced (and had at least one other person mention) is no longer being able to explicitly add vertical spacing, which is something I occasionally use to create distinct visual sections in a dashboard. Most of the time I use text boxes with a header for this, so ultimately it's something I'm not too worried about losing but wanted to offer my use-case. 

Also: I appreciate y'all's continued care in improving the experience and listening to how folks are using these in the wild.

**Comment by tbillington** [comment]
I really like that moving a graph will "push" those in the way, that's a huge UX improvement 🎉

Re-organising all of our dashboards for us and disallowing flexible layout though was quite painful. We lay out our dashboards with spacing & sections to keep them simple and not just a "wall" of graphs that overwhelm viewers.

Can the float-to-top be a setting? It's a very subjective choice. If it was there from the start it wouldn't be such an issue but messing up the layout of hundreds of our existing dashboards is ... an interesting product choice.

We're on enterprise so it just started happening one day which wasn't a great experience.

**Comment by ranquild** [comment]
> I disagree that this is a bug or a regression. It is a subjective UX change that some users are reporting a preference for, while some others are reporting dissatisfaction.
> 
> Please do not "fix" this without checking in with Product — we need to gather more impressions and opinions on this first.

@mazameli what's the current status - should we fix this, and what would be the fix?

**Comment by mlazowik** [comment]
> I disagree that this is a bug or a regression.

@mazameli  changing whether there is a way to make empty space or not – sure, but IMO silently changing the layout of already existing dashboards (and it happened for all of them at once, no need to edit and save) is a bug.

**Comment by brunobergher** [comment]
Thanks for the input, folks. We had tons of internal discussions as to how to determine this behavior, and decided that vertically grouping cards was the way to go, for a variety of reasons. I can see that we could perhaps helped more with the migration, but we chose to prioritize fixing other bugs instead of optimizing this one-time event, sorry to mess up your dashboards.

In any case, going forward, you can add empty text cards and turn off their background to add as much vertical space as you want, and since they're empty they won't affect your experience elsewhere. We may end up with a spacer component in the future, if this becomes important enough.
