### ISSUE TITLE
Do not show Cloud CTA for Enterprise Edition

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16792]
**Describe the bug**
Continuation of #11336. Regression since 1.39.0
Do not show CTA on Enterprise Edition. And do not show update panel at all on Metabase Cloud.

**To Reproduce**
1. Admin > Settings > Updates
![image](https://user-images.githubusercontent.com/1447303/123619480-8144b100-d809-11eb-92a2-ed2dc6f962e6.png)

**Expected behavior**
- [ ] Do not show CTA on Enterprise Edition
- [ ] Do not update panel at all on Metabase Cloud. Show a custom message.

**Information about your Metabase Installation:**
Regression since 1.39.0 (#15517)

**Comment by gusaiani** [comment]
@flamber, if you happen to know details on how to reproduce this one, I will be grateful.

I was able to run Enterprise edition locally, in dev mode, with a demo token.

Then I go to http://localhost:3000/admin/settings/updates

And all I see is this

![image](https://user-images.githubusercontent.com/380816/124678923-eb102b00-de99-11eb-9ddc-afb44d6f247a.png)

**Comment by brunobergher** [comment]
While you're looking into this, Gus, it would be great if we could change that string to read more naturally, maybe

> No successful checks yet.

And if that's too complicated, simply removing the `Last successful check was never.` bit when there have been no checks should make it cleaner.

**Comment by brunobergher** [comment]
On "Do not update panel at all on Metabase Cloud. Show a custom message."
I'd say let's go with a simple message such as:

> Metabase Cloud keeps your instance up to date. Thanks for being a customer!

**Comment by flamber** [comment]
@gusaiani You have to wait up to 12 hours until your instance runs the check (see #11336 for more details). Or manually populate `version-info` and `version-info-last-checked` in the `setting` table.

**Comment by gusaiani** [comment]
@brunobergher @flamber 

> On "Do not update panel at all on Metabase Cloud. Show a custom message."
I'd say let's go with a simple message such as:

To confirm I understand:
in Metabase Cloud, should the toggle not be rendered at all? — implying all instances are always updated, no config involved?

In which case it would look kind of like this:

<img src="https://user-images.githubusercontent.com/380816/124772389-5e558380-df12-11eb-8b91-b2fd937b0b92.png" width=400 />

**Comment by brunobergher** [comment]
Yes, that's a big part of the value proposition of Cloud.

The precise situation on your screenshot wouldn't happen, with the (1) badge by updates and the a Cloud message on the right, though, right? It may be worth ommitting the badge altogether when in Cloud, just to ensure we don't confuse anyone (sometimes it takes a few days for us to upgrade the entire Cloud fleet).

**Comment by gusaiani** [comment]
@brunobergher Got it, and yes, omitting the badge makes complete sense. 
I will look into the badge while at it.

Copying @ariya here so we can align, as our i18n flow currently discourages us from changing (and maybe introducing, idk) copy near releases.

In this particular case, seems to me we could go with just the English string for v40.

Better than not rendering anything at all.
Better than still rendering the toggle which does nothing. 

wdyt?

**Comment by ariya** [comment]
> In this particular case, seems to me we could go with just the English string for v40.

I reckon that'll make the translators rather unhappy (since they'll get the blame), but @mazameli likely has a better opinion here.

**Comment by mazameli** [comment]
@gusaiani asked me to look at https://github.com/metabase/metabase/pull/16920#pullrequestreview-701207764, and my question is, why should we should the `Updates` tab _at all_ for Cloud instances? Unless I'm missing something, I think we should hide it entirely, and if someone tries to navigate to `/admin/settings/updates` on a Cloud instance, we can just redirect them to `/admin/settings/setup`. Any objections to that @flamber?

**Comment by gusaiani** [comment]
@mazameli Great point.

**Comment by gusaiani** [comment]
cc @brunobergher ↑ wdyt?

**Comment by gusaiani** [comment]
@mazameli @brunobergher @flamber 

One possible use for an "updates" link in Cloud:
showing the currently installed version.

Reason: maybe auto-updates fail, and customer has no way of knowing their current version.
Unless of course there is another way to see that.

**Comment by brunobergher** [comment]
My take is that customers coming from Open Source will probably expect to see that panel, or something somewhere about the version they're on and how they should handle upgrades. If we can handle that need elsewhere (eg, in the about screen), we should be fine, but given how close to the release we are, I wanted to keep it tighter.

**Comment by gusaiani** [comment]
@brunobergher @mazameli @flamber 

In this case, how about we use this as a message:

```
Metabase Cloud keeps your instance up to date. You are now on version 0.40.3. Thanks for being a customer!
```

There is still the issue of applying i18n, but would show the version.

**Comment by brunobergher** [comment]
That works for me. @mazameli, would you object to that?

**Comment by mazameli** [comment]
@brunobergher since we under time pressure, I think that's fine in the short-term, with a slight wording tweak:

`Metabase Cloud keeps your instance up-to-date. You're currently on version 0.40.3. Thanks for being a customer!`

Medium-term, I think we should consider either dropping this page and handling the scenario you're describing elsewhere, or possibly including more helpful information here like the current release notes.

**Comment by brunobergher** [comment]
🚀

**Comment by mazameli** [comment]
(Small footnote re: this: "customers coming from Open Source will probably expect to see that panel, or something somewhere about the version they're on and how they should handle upgrades" — I can see that, yet a counter point is that I think that this tab will be slightly confusing or underwhelming if your first experience with Metabase is Metabase Cloud.)

**Comment by brunobergher** [comment]
Agreed

**Comment by gusaiani** [comment]
@mazameli @brunobergher Thank you for replying quite so quickly.

I will add 

`Metabase Cloud keeps your instance up-to-date. You're currently on version 0.40.3. Thanks for being a customer!`

to it.
