### ISSUE TITLE
Trend, aka Smart Number, visualization's alignment looks bad at narrow viewport widths

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#16797]
At around 1300px wide, the change rate text begins wrapping to a second line and aligning left, which looks awkward:

![image](https://user-images.githubusercontent.com/2223916/123670023-9ad9fe80-d7f1-11eb-8385-1f6a01bcfc0a.png)

**Comment by flamber** [comment]
Related to #4648. Seems to be very specific to do with the percentage or amount changed, and likely only on 3x3 cards.
