### ISSUE TITLE
Updating Metabase without losing dashboards and questions

### ISSUE THREAD

**Issue by sladerose** [metabase/metabase#16805]
Hi, we need to update our current Metabase instance running on AWS. It is the JAR version of Metabase. We currently have a PostgreSQL DB with our data and a MySQL DB with our queries and other information connected. We are worried that if we update Metabase that we will lose our data/settings/dashboards that we currently have set up. Could someone please shed some light on how we update without breaking anything? Thank you in advance.

**Comment by flamber** [comment]
Always have a backup before upgrading.
https://www.metabase.com/docs/latest/operations-guide/upgrading-metabase.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
