### ISSUE TITLE
Filter flag causes overlay for required "Number" filter with the default value set

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16811]
**Describe the bug**
When feature flag is enabled, and when Number filter is marked as a required but only the default value has been set, it causes overlay to always be shown unless the editor is expanded.

**Logs**
N/A

**To Reproduce**
_Requires filter feature flag enabled_

1. Ask a question > Native
2. `SELECT * FROM products WHERE products.rating = {{numberFilter}}`
3. Set filter type to be "Number"
4. Make it required (toggle the switch)
5. Enter the default value of `4.3`
6. Click "play" icon to run the query
7. Notice it stays on, meaning the question is dirty
8. If you collapse the editor, the overlay will be always present making it impossible to interact with the results
9. Depending on the user permissions levels, some of them might not even have the option to expand the editor

**Expected behavior**
Running the query should not put question in a "dirty" state and the overlay should not interfere with the results when the editor is collapsed.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/p9uAQXAk/5eda1fe0-33ac-4edb-9476-fd41d3a0096b.gif?source=viewer&v=379c9408ac8bea2aca9e71420fc40e46)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
local dev, x.40.0-snapshot, `master`, 2d890cb

**Severity**
P2?

**Comment by flamber** [comment]
Very related to #16739 - and historically to #15981.
