### ISSUE TITLE
Performance issue with BigQuery

### ISSUE THREAD

**Issue by EvaSchreyer** [metabase/metabase#16827]
using metabase v0.39.3 and several bigQuery databases.

I can´t access the data model of our biggest bigQuery Database anymore to work on the tables. 

Error message: 

```<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>Microsoft-Azure-Application-Gateway/v2</center> </body> </html> ```

We need this access to our tables as there is no other way to change a column within a table to category (or any other column type) within metabase.

As I have access to smaller BigQuery databases via the Data Model I guess its a performance issue with the BigQuery Connection.

**Comment by flamber** [comment]
Hi @EvaSchreyer 
The timeout comes from your proxy (load-balancer likely). You need to adjust the timeout of that.
I'm guessing that the timeout comes from the request to `/api/database/:id/metadata?include_hidden=true`, which loads all tables from a database (the request is to Metabase's application database, not to your BigQuery).

**Comment by EvaSchreyer** [comment]
thanks @flamber that worked!
