### ISSUE TITLE
About mout plugins for Docker

### ISSUE THREAD

**Issue by qiaofeng1227** [metabase/metabase#16824]
We have do some research, found that Metabase container include the below plugins:
```
bigquery.metabase-driver.jar         google.metabase-driver.jar           mongo.metabase-driver.jar            presto.metabase-driver.jar           snowflake.metabase-driver.jar        sqlite.metabase-driver.jar           vertica.metabase-driver.jar
druid.metabase-driver.jar            googleanalytics.metabase-driver.jar  oracle.metabase-driver.jar           redshift.metabase-driver.jar         sparksql.metabase-driver.jar         sqlserver.metabase-driver.jar
```

My question is that if we create container by below command (bind /plugins directory),  Is the default plugin available？
```
  docker run -d -p 3000:3000 \
  --mount type=bind,source=/mypath/to/plugins,destination=/plugins \
  --name metabase metabase/metabase
```

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/123921808-fc4cc980-d9b9-11eb-9866-2fde5498e3ba.png)

**Comment by qiaofeng1227** [comment]
```
[root@iZj6ce283qzyocxruxot1hZ docker-metabase]# docker exec -it metabase bash
bash-5.1# ls
app            dev            home           lib64          metabase-data  opt            proc           run            srv            tmp            var
bin            etc            lib            media          mnt            plugins        root           sbin           sys            usr
bash-5.1# cd plugins/
bash-5.1# ls
bash-5.1# ls -l
total 0
````

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/123921938-1edee280-d9ba-11eb-9b5c-3580ed758c47.png)
![image](https://user-images.githubusercontent.com/43192516/123921973-256d5a00-d9ba-11eb-8a2d-528ae17a5d3b.png)

**Comment by qiaofeng1227** [comment]
```
[root@iZj6ce283qzyocxruxot1hZ plugins]# wget https://github.com/bbenzikry/metabase-neo4j-driver/releases/download/v0.0.7/neo4j.metabase-driver.jar
[root@iZj6ce283qzyocxruxot1hZ plugins]# ls
neo4j.metabase-driver.jar
```
![image](https://user-images.githubusercontent.com/43192516/123922631-d07e1380-d9ba-11eb-8917-034452aaa4b2.png)

**Comment by qiaofeng1227** [comment]
can't add a new plugin

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html#adding-external-dependencies-or-plugins
Make sure that the directory is writable by user/group 2000/2000:
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html#additional-custom-settings

**Comment by qiaofeng1227** [comment]
Sorry，I have konwn how to add a new plugins. I want to get some help for this question:

We have do some research, found that Metabase container include the below plugins:
```
bigquery.metabase-driver.jar         google.metabase-driver.jar           mongo.metabase-driver.jar            presto.metabase-driver.jar           snowflake.metabase-driver.jar        sqlite.metabase-driver.jar           vertica.metabase-driver.jar
druid.metabase-driver.jar            googleanalytics.metabase-driver.jar  oracle.metabase-driver.jar           redshift.metabase-driver.jar         sparksql.metabase-driver.jar         sqlserver.metabase-driver.jar
```

My question is that if we create container by below command (bind /plugins directory),  Is the default plugin available？
```
  docker run -d -p 3000:3000 \
  --mount type=bind,source=/mypath/to/plugins,destination=/plugins \
  --name metabase metabase/metabase
```
