### ISSUE TITLE
metabase v0.39.4 presto engine timezone error!

### ISSUE THREAD

**Issue by archer2012** [metabase/metabase#16826]
**Describe the bug**
whatever REPORT TIMEZONE i choose ,presto engin will use UTC timezone 

**To Reproduce**
1. Go to 'Dashboard Trend'
2. Click on 'categrory '
3. Show editor --> view the SQL

like this:

`SELECT "app"."v_tanan_event"."channelname" AS "channelname", count(distinct "app"."v_tanan_event"."actorid") AS "count"
FROM "app"."v_tanan_event"
WHERE ("app"."v_tanan_event"."dt" >= timestamp '2021-06-29 00:00 UTC'
   AND "app"."v_tanan_event"."dt" < timestamp '2021-06-30 00:00 UTC')
GROUP BY "app"."v_tanan_event"."channelname"
ORDER BY "app"."v_tanan_event"."channelname" ASC
LIMIT 200`

**Comment by archer2012** [comment]
> **Describe the bug**
> whatever REPORT TIMEZONE i choose ,presto engin will use UTC timezone
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'Dashboard Trend'
> 2. Click on 'categrory '
> 3. Show editor --> view the SQL
> 
> like this:
> 
> `SELECT "app"."v_tanan_event"."channelname" AS "channelname", count(distinct "app"."v_tanan_event"."actorid") AS "count" FROM "app"."v_tanan_event" WHERE ("app"."v_tanan_event"."dt" >= timestamp '2021-06-29 00:00 UTC' AND "app"."v_tanan_event"."dt" < timestamp '2021-06-30 00:00 UTC') GROUP BY "app"."v_tanan_event"."channelname" ORDER BY "app"."v_tanan_event"."channelname" ASC LIMIT 200`

![image](https://user-images.githubusercontent.com/3227239/123894326-8ed87300-d990-11eb-9987-26b08dd6a3f9.png)
![image](https://user-images.githubusercontent.com/3227239/123894348-98fa7180-d990-11eb-8819-5d8739a4b326.png)

**Comment by flamber** [comment]
1. Post "Diagnostic Info" from Admin > Troubleshooting.
2. What is the database column type of `"app"."v_tanan_event"."dt"` ?

**Comment by archer2012** [comment]
> 1. Post "Diagnostic Info" from Admin > Troubleshooting.
> 2. What is the database column type of `"app"."v_tanan_event"."dt"` ?
date

![image](https://user-images.githubusercontent.com/3227239/123937721-09bd8000-d9c9-11eb-9079-57f8d21266b6.png)

**Comment by flamber** [comment]
@archer2012 Post "Diagnostic Info" from Admin > Troubleshooting

**Comment by archer2012** [comment]
> @archer2012 Post "Diagnostic Info" from Admin > Troubleshooting

i need the sql like this ,how to setting ?

SELECT "dim"."v_channel"."channelname" AS "channelname", count(*) AS "count"
FROM "dim"."v_channel"
WHERE ("dim"."v_channel"."createtime" >= timestamp '2012-09-03 00:00 '
   AND "dim"."v_channel"."createtime" < timestamp '2012-09-04 00:00 ')
GROUP BY "dim"."v_channel"."channelname"
ORDER BY "dim"."v_channel"."channelname" ASC

**Comment by flamber** [comment]
@archer2012 Copy and paste the "Diagnostic Info" here:
![2021-06-30_12-43](https://user-images.githubusercontent.com/1447303/123947640-e41c8080-d9a0-11eb-9c3e-99ba062a1155.png)

**Comment by archer2012** [comment]
> @archer2012 Copy and paste the "Diagnostic Info" here:
> ![2021-06-30_12-43](https://user-images.githubusercontent.com/1447303/123947640-e41c8080-d9a0-11eb-9c3e-99ba062a1155.png)

{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "11.0.11+9-LTS-194",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.11",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-LTS-194",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.12.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "presto",
      "sqlserver",
      "mysql",
      "postgres",
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.12-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-06-26",
      "tag": "vUNKNOWN",
      "branch": "dev",
      "hash": "22c1ac3"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
@archer2012 You are not using 0.39.4, and you have not defined Report Timezone in Admin > Settings > Localization.
Closing this issue. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
