### ISSUE TITLE
Separator style not applied to scientific notation

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16820]
**Describe the bug**
If a number column is set to display in scientific notation, we don't respect the preferred separator style.

**Expected behavior**
I don't really know what the expected scientific notation format is in countries that use different separator styles. But either we should respect the separator style setting, or not display the option in the column formatting sidebar if scientific notation is being used.

**Screenshots**

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/32746338/123878754-8e8a9a00-d8f4-11eb-9e9f-89842663d0eb.png">

**Information about your Metabase Installation:**

Current master (0.39.5) on Firefox 89.0.1 on macOS Big Sur

**Comment by flamber** [comment]
It should respect the separator style selected. Most European countries uses comma instead of dot as decimal separator.
