### ISSUE TITLE
Rearranging columns produces error (Value does not match schema)

### ISSUE THREAD

**Issue by phiat** [metabase/metabase#16839]
**Describe the bug**
Rearranging columns gives error

**To Reproduce**
I don't have a clean way to reproduce yet.   But I have a saved question used as a base for multiple joins in the UI editor, and when I try to rearrange the columns in the UI (either the sidebar or the top headers), i get the error:
`
Value does not match schema: {:query {:fields (named (not ("distinct" a-clojure.lang.PersistentVector)) "Distinct, non-empty sequence of Field clauses")}}
`

**Expected behavior**
no error, column rearranged.

**Comment by flamber** [comment]
Closing because lack of information. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by phiat** [comment]
What other info would be needed?    Start from a saved question, add multiple joins (lefts and rights), rearrange columns = that error.   First time I've had a bug report dismissed like this.     

https://github.com/metabase/metabase/issues/16229  (similar bug) has a screenshot, so here: 

![image](https://user-images.githubusercontent.com/190444/124126213-71ff7680-da48-11eb-9fb2-943e4e9bcf34.png)

**Comment by flamber** [comment]
@phiat You're welcome to open a new issue and fill in all the requested information: https://github.com/metabase/metabase/issues/new/choose
I will close any issue created without all information filled out. It would be impossible for us to maintain issues lacking information.

**Comment by phiat** [comment]
@flamber  Ok, no problem, sorry to trouble.   This is with a work account, and I can't reproduce yet with sample data/tables.   Will try to either reproduce and sanitize tables/data or recreate with sample tables/data and repost.
