### ISSUE TITLE
Bar Visualization - Bar height is wrong

### ISSUE THREAD

**Issue by andrewler** [metabase/metabase#16844]
**Describe the bug**
1. Bar height does not correspond to y-axis labels
2. Bar height does not logically correspond to the numeric value

**Logs**
javascript console logs: https://pastebin.com/2fzn7jWr

**To Reproduce**
1. Create a pivot table question that summarizes data by year (2020, 2021) and by "month of year"
2. Visualize as pivot table and Bar chart
3. Bar heights do not correspond to y-axis labels and some bar heights are arbitrary

**Expected behavior**
The bar heights should correspond to the y-axis labels.
The bar heights should be accurate

**Screenshots**
Red and blue markup added for emphasis
![image](https://user-images.githubusercontent.com/76549682/124088083-90d42c00-da8d-11eb-87e5-b270588d600b.png)

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-8u282-b08-0ubuntu1~16.04-b08",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-197-generic",
    "user.language": "ko",
    "user.timezone": "Asia/Seoul"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.0",
      "date": "2021-02-16",
      "branch": "release-x.38.x",
      "hash": "471aa51"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

- Your browser and the version: Chrome Version 91.0.4472.124 (Official Build) (64-bit)
- Your operating system: Windows 10 Version 2004 (OS Build 19041.1052) 64-bit

**Severity**
Since we use metabase as an analytical tool to make decisions, data visualization is an important part of the decision-making process.  If the data visualization is wrong (even if the numbers are correct) we cannot rely or trust the other visualization on the platform and we must always second-guess or double-check the visualizations to make sure they are correct.  Because of this, I would rate the severity of this issue as High.

**Additional context**
Maybe there is a separate cache for the bar height data and the numeric values that is causing the issue?

**Comment by flamber** [comment]
Hi @andrewler 
It's not possible to see if you actually have two axis, which I'm guessing you have. You can disable split axis:
![image](https://user-images.githubusercontent.com/1447303/124089935-ac6f1080-da54-11eb-8832-21f8ff4a6b42.png)

**Comment by andrewler** [comment]
@flamber 
Thank you I didn't realize this parameter was enabled on my chart. 🤦🏼‍♂️
