### ISSUE TITLE
Audit logging not able to show ad-hoc native query

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16845]
**Describe the bug**
Audit logging not able to show ad-hoc native query.

**To Reproduce**
1. Native query > Sample Dataset > `select 1` and run it
2. Admin > Audit > Team members > Audit Log > click the top "Ad-hoc"
3. The page refreshes without showing any results.
It just shows "Something went wrong" constantly looping a reload of the frontend. This is a regression since 1.39.0.

https://user-images.githubusercontent.com/1447303/124104258-5e610980-da62-11eb-992f-5cc689b6053b.mp4

**Information about your Metabase Installation:**
Tested 1.40.0-rc1

**Additional context**
Originally EE486 https://github.com/metabase/metabase-enterprise/issues/486

**Comment by kulyk** [comment]
Reproduced by [this test](https://github.com/metabase/metabase/blob/c225ace8e68ea573c7eb33cc5f09a9fa711c0f83/frontend/test/metabase/scenarios/admin/audit/ad-hoc.cy.spec.js#L27)
