### ISSUE TITLE
Use fipp/puget/pp for pretty printing

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1684]
[fipp](https://github.com/brandonbloom/fipp) is 5x as fast as `clojure.pprint/pprint` and a lot more flexible, and since we pretty print queries like they're going out of style this lib is probably worth it

**Comment by camsaul** [comment]
We should use https://github.com/greglook/puget actually

**Comment by escherize** [comment]
It's pretty new, but seems cool, let's at least checkout https://github.com/eerohele/pp

**Comment by dpsutton** [comment]
where do we pretty print things? We have fipp on the classpath already (we should add a top level dep to it if so). Where do we intend to use it. I'm not sure where we are pretty printing anything at the moment.

```
lambdaisland/deep-diff2 2.10.211
  . fipp/fipp 0.6.26
...
methodical/methodical 0.15.1
  X mvxcvi/puget 1.3.2 :superseded
    X mvxcvi/arrangement 2.0.0 :parent-omitted
    X fipp/fipp 0.6.24 :parent-omitted
...
io.github.camsaul/toucan2 1.0.524
  . better-cond/better-cond 2.1.5
  X org.clojure/tools.logging 1.2.4 :use-top
  . mvxcvi/puget 1.3.4 :newer-version
    . mvxcvi/arrangement 2.1.0
    . fipp/fipp 0.6.26
...
metosin/malli 0.11.0
  . fipp/fipp 0.6.26

**Comment by camsaul** [comment]
fipp is on the classpath because Methodical and Toucan use Puget for printing debug info and other stuff

**Comment by camsaul** [comment]
Only downside of `pp` is that it's not Cljc
