### ISSUE TITLE
The pinned items from the main collection are not showed on the front page anymore

### ISSUE THREAD

**Issue by antoine-lizee** [metabase/metabase#16869]
**Describe the bug**
Items that were pinned in the "our analytics" collection (the top level one) used to appear on the top of the welcome page, which was really helpful to surface key dashboards for the whole company. After a recent update, they disappeared.

**Logs**
[not really relevant]

**To Reproduce**
1. Make sure that some items are pinned in your top-level collection
2. Go to the welcome page of your metabase instance
3. See that there is no pinned item that are presented on top

**Expected behavior**
Have the pinned items on the front page.

**Screenshots**
[not applicable]

**Information about your Metabase Installation:**

Below is our current instal, but the bug appeared when updating from 0.38.5 to 0.40.0 rc1

<details> <summary><strong> Details from troubleshooting page </strong></summary>
<p>

They seem surprisingly few - another small bug?

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36",
    "vendor": "Google Inc."
  }
}
```

</p>
</details>

**Severity**
This is "annoying". Mostly, it was very useful to have a way to surface results to the front page (which was the ~only feature of the front page, currently a bit lacking).

**Comment by flamber** [comment]
This is the same problem as #16784, since we're only loading the 50 first objects (alphabetically).
