### ISSUE TITLE
Custom Expression function similar to `datediff`/`date_part`/`extract`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16870]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to get the difference between two timestamp fields easily - and it does not work consistently across all databases.

**Describe the solution you'd like**
Something similar to `datediff`/`date_part`/`extract`, where it's possible to define the difference in minutes/days/months/etc.

**Describe alternatives you've considered**
Currently it's possible to use `[date_col1] - [date_col2]` to get the days between two dates, but that does not work on all databases. Example SQLite will return the years between those dates, other database types might return a range/duration.

And the field suggestion dropdown will not list the second column, so it has to be manually written, which can be difficult.

**Additional context**
Continuation of #11330
Related to #7614

_Note: If you want a different function, then create a separate feature request for that. This issue is only about date difference_

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jalberto** [comment]
what about `[datecol] + '1 day'` ?

**Comment by pushdabutton** [comment]
what @jalberto said, can we finally add days to dates?? seems like a pretty standard operation.

**Comment by rafho1** [comment]
Would be nice if we could genericize the custom fields to allow SQL statements? (e.g. Custom Field = DATEDIFF(NOW(), table.date))

**Comment by likeshumidity** [comment]
@flamber does v0.45 solve this or no?

**Comment by camsaul** [comment]
@calherries @qnkhuat do the `datediff` and date extract stuff you guys have been working on solve this? If so, let's close this out

**Comment by calherries** [comment]
`datetimeDiff` isn't in supported by most drivers in 0.45 ([docs](https://www.metabase.com/docs/latest/questions/query-builder/expressions/datetimediff#limitations)). The date extract functions are covered, but I wouldn't close this yet.

**Comment by brunobergher** [comment]
Solved to completion with the inclusion of `now()` and better driver support in 46.
