### ISSUE TITLE
After embedding to application, records are missing in the drop down filters

### ISSUE THREAD

**Issue by mariyathomasp** [metabase/metabase#16935]
**Describe the bug**
I have created the dashboard with a drop-down filter. While testing it in Metabase, it shows all the records available in the database. But once I embed it on my application, it doesn't show all the records, I found a few are missing.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to Metabase and create a question as in the image ( giving a sample query i am using, note that you can suggestions for container number in the search list dropdown)'
![image](https://user-images.githubusercontent.com/77450749/124931252-5117c200-e002-11eb-838a-787013f43739.png)
2. Add it to your dashboard and a linked filter, you can see that it is showing the numbers correctly
![image](https://user-images.githubusercontent.com/77450749/124931966-f894f480-e002-11eb-870a-ddd760cdce02.png)
![image](https://user-images.githubusercontent.com/77450749/124932910-bf10b900-e003-11eb-88d2-685c823b78fb.png)
3. Embed the dashboard into your application, it shows only one value i.e, 1, even though it should show all the 6 values as in the database.
![image](https://user-images.githubusercontent.com/77450749/124934811-5b878b00-e005-11eb-81d3-76d65c8b16a4.png)

**Expected behavior**
It should display all records with filtering or linking to any other filters.

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.8.0-1036-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-06-15",
      "tag": "v0.39.4",
      "branch": "release-x.39.x",
      "hash": "f538050"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Severity**
We are waiting for this issue to fix to release it to customers, as this issue is there in more filters

**Comment by paoliniluis** [comment]
I'm mostly sure this is related to https://github.com/metabase/metabase/issues/14309, so closing this one in favor of the one I linked
