### ISSUE TITLE
Can't click on entity key cells when "exploring results" from a SQL question to see record detail view

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#16938]
The way that we're visually representing the entity key column here (`ID`), it looks like cells in the column should be clickable, like they are with normal tables, but they ain't.

![image](https://user-images.githubusercontent.com/2223916/124967722-9673c980-dfd9-11eb-9247-c98f729ca4b8.png)

To repro:
- Create a new SQL query that has a column named `ID` or that selects a primary key from a table
- Save it
- Click the Explore Results button in the top right
- Try clicking on a cell in the ID column
- Expectation is that you'd see the single-record detail view, but you instead nothing happens

**Comment by flamber** [comment]
Very related to #5595
