### ISSUE TITLE
[Firefox] Whitespace displayed with strange character

### ISSUE THREAD

**Issue by milgner** [metabase/metabase#1693]
Right after setting up Metabase, when opening it in Firefox, I see a strange character on the page, which can also be seen in the source.

When opening it in Chrome, it shows a whitespace `&nbsp;` in the same place.

![This does not look right](https://cloud.githubusercontent.com/assets/160025/11898873/788dfedc-a59b-11e5-8ff7-04fdd480cabd.png)

**Comment by tlrobinson** [comment]
What operating system is this? Linux?

**Comment by milgner** [comment]
Yes, Firefox 43 on (Arch) Linux running Gnome.

**Comment by mbvictoria** [comment]
Closing - stale/hasn't been reported in recent versions.
