### ISSUE TITLE
Content in notebook step UI can overflow in ugly ways

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#16937]
I can't recall if this problem has been around for a long time or not (@flamber?), but in any case, I'd expect the content to wrap inside of the box to prevent it from overflowing as it's doing here:

![image](https://user-images.githubusercontent.com/2223916/124966907-ab9c2880-dfd8-11eb-82a3-e23fe72c1f19.png)

**Comment by flamber** [comment]
@mazameli Been around since 0.33
