### ISSUE TITLE
pulse creation page has wrong link for dashboard subscription info

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#16953]
**Describe the bug**
Pulses are deprecated in favor of dashboard subscriptions. The page includes a link for information, but this link goes to the wrong page.

<img width="865" alt="image" src="https://user-images.githubusercontent.com/6377293/125098326-87098480-e09c-11eb-818e-6631ddd713d9.png">

Link goes to https://www.metabase.com/docs/latest/users-guide/07-dashboards.html but should link to https://www.metabase.com/docs/latest/users-guide/dashboard-subscriptions.html

**To Reproduce**
1. Click + icon in menu bar and click pulse
2. Get deprecation warning, with link to docs about dashboards, not dashboard filters

### Dashboard doc link
<img width="789" alt="image" src="https://user-images.githubusercontent.com/6377293/125098572-c041f480-e09c-11eb-87cf-4b92b2fc9964.png">

### Dashboard filters doc link
<img width="796" alt="image" src="https://user-images.githubusercontent.com/6377293/125098619-ca63f300-e09c-11eb-9dc3-9b47fa5b3fa7.png">

**Comment by jeff-bruemmer** [comment]
Closed by https://github.com/metabase/metabase/pull/16959.
