### ISSUE TITLE
2 sets of data on the same chart

### ISSUE THREAD

**Issue by bnetter** [metabase/metabase#1695]
Hey guys, first of all: incredible work on Metabase. I discovered it last week, I haven't been excited that much over an open-source product for a while.

Now, most of the time, I'm generating charts with dates on the x-axis and would love to be able to see two different set of data on the same chart. Here's an example.

![Cumulative chart](http://www.presentation-process.com/wp-content/uploads/performance-cumulative-chart-combined.jpg)

It would also solve the problem we all seem to have with bar charts (#1449).

**Comment by agilliland** [comment]
@bnetter We are definitely looking at this, and thanks for providing a detailed example it's super helpful.  We actually have an issue open where this work is being tracked #656 , you mind putting your post over on that issue and closing this one as a dupe?

**Comment by bnetter** [comment]
Sure.

**Comment by bnetter** [comment]
How high is this on your roadmap.

**Comment by bnetter** [comment]
How high is this on your roadmap? To me it's seems mostly a front-end job, I could take a look at it if you want.

**Comment by tlrobinson** [comment]
@bnetter Very high. We're in the process of designing it at the moment.

**Comment by bnetter** [comment]
I'm officially excited.
