### ISSUE TITLE
Snippets not visible to non-admin users

### ISSUE THREAD

**Issue by punnumangal** [metabase/metabase#16961]
We are using Metabase General version (NOT the Enterprise one). We have more than 40 Snippets created and those were visible by the admin and non-admin users of Metabase. Since past 2 weeks, the non-admin users are unable to view the Snippets in the right sidebar (altough we haven't made any changes to the Permissions or Snippets settings).

Request to assist at the earliest.

**Comment by paoliniluis** [comment]
@punnumangal can you specify the version where this is happening? I assume the snippets are not archived right?

**Comment by punnumangal** [comment]
@paoliniluis  Version is 0.39.2 and the snippets are not archived. The only issue that the non admin users are NOT able to see the snippets.

**Comment by flamber** [comment]
@punnumangal 
Please post "Diagnostic Info" from Admin > Troubleshooting.
Did you use the Enterprise Edition at some point?

So what happened 2 weeks ago? Something must have changed - either someone changed something or perhaps you upgraded/downgraded?

Go to the URL `/api/collection?namespace=snippets` both as admin and non-admin, and post the output.
And check that all the snippets has `collection_id: null` when going to `/api/native-query-snippet`

**Comment by punnumangal** [comment]
**Diagnostic info below:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-8u282-b08-0ubuntu1~16.04-b08",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1121-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.2",
      "date": "2021-05-17",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}


**metametabase>native_query_snippet info below**
<img width="376" alt="Screenshot 2021-07-12 at 11 43 35 AM" src="https://user-images.githubusercontent.com/22841102/125239531-67759480-e306-11eb-8c36-19aec0305d98.png">


We keep updating the Metabase regularly but nothing specific was done 2 weeks go. One surprising fact is that I am unable to understand is that the admins are able to see the snippets. The problem is only with non-admins who cannot see the snippets at all (all were able to view and edit the snippets earlier).

**Comment by flamber** [comment]
@punnumangal 
Admins can see everything in Metabase, while non-admin are restricted to specific permissions (stored in various places of the metadata, like `permissions`).
Go to the URL `/api/collection?namespace=snippets` both as admin and non-admin, and post the output.
Check the browser developer console for errors, when accessing as non-admin. And also check Admin > Troubleshooting > Logs.
