### ISSUE TITLE
presto schema option

### ISSUE THREAD

**Issue by utopianet** [metabase/metabase#16973]
Because a Presto data source usually has many databases, especially the pasted source data layer, which may be tens of thousands of tables.

At present, Presto does not provide schema option, which causes great pressure on large databases, especially hive databases, when synchronizing tables and fields.

The result is that after thousands of queries are launched, the hive meta store is out of service and cannot be synchronized at all.

It is suggested to add schema option when adding Presto data source to the source, so that users can select the database with few data tables for synchronization and increase the software availability. Thank you!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Very related to #5500/#6286 and #8956

**Comment by flamber** [comment]
Is implemented by #16194 (and slight fix in #17265). Will be part of 0.41
