### ISSUE TITLE
Does metabase v0.40.0 upgrade consists of any metadata structure change?

### ISSUE THREAD

**Issue by fatin-qa** [metabase/metabase#16977]
We upgraded our metabase from version 0.39.4 to 0.40.0 through aws and afterwards, we noticed that the Elastic Beanstalk environment is still connecting to the previous metadata database. Upon opening metabase, we see the setup page instead our usual dashboard with data
![Screenshot 2021-07-12 122533](https://user-images.githubusercontent.com/81356079/125236873-53865e80-e317-11eb-8466-f03d1b9a32b2.png)

So we assume that it couldn't find the same table due to some metadata structure changes. Can you guys confirm if there is any structure change or if something else is causing this?

Thank you.

**Comment by flamber** [comment]
Hi @fatin-qa 
It has nothing to do with metadata changes, but likely how your setup on EB was coupled with RDS:
https://www.metabase.com/docs/latest/operations-guide/creating-RDS-database-on-AWS.html#decouple-your-rds-database-from-the-elastic-beanstalk-deployment
