### ISSUE TITLE
Force truncate numbers

### ISSUE THREAD

**Issue by bnetter** [metabase/metabase#1698]
Would love to be able to truncate resulting number.

<img width="1363" alt="capture d ecran 2015-12-23 a 10 27 03" src="https://cloud.githubusercontent.com/assets/336674/11973953/d227a7d2-a95f-11e5-9909-3f4735b26dde.png">

**Comment by kdoh** [comment]
We must've missed this issue when we introduced chart settings for scalars. You can set the number of decimal places by clicking the gear icon next to the visualization type when on a question.
