### ISSUE TITLE
Exceeded the maximum depth of an expression tree (1000)

### ISSUE THREAD

**Issue by annisun2020** [metabase/metabase#17003]
when i filter a colunm value more than 1000, i got the error. 
I found that SQL statements executed in the background use a lot of nested expressions:

![lALPDgfLR3Fjqp_NAR_NBUs_1355_287](https://user-images.githubusercontent.com/68275306/125381270-2fce2180-e3c6-11eb-90a6-d8d9093b0cf8.png)

Can this use IN to replace equals? Because some query engines do not support too many expressions

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Or file a bug report and include all the details.
