### ISSUE TITLE
Reduce number of background queries.

### ISSUE THREAD

**Issue by pcothenet** [metabase/metabase#1701]
Hi team,

I was investigating an issue with my Redshift cluster consistently being at 100% CPU on the leader node. I found out 100% of queries consistently running in the background, such as:

```
SELECT AVG(CHAR_LENGTH(CAST("mk_3344_1"."events_raw_stage"."a_channelcounreferring_domain" AS CHAR))) AS "len" FROM "mk_3344_1"."events_raw_stage" 
```

```
SELECT COUNT(*) AS "count" FROM "mk_3337_1"."contacts" WHERE ("mk_3337_1"."contacts"."email" LIKE $1)
```

For every of the 100s of tables in my schema, all coming from my Metabase instance with no one using it.

I assume those are background queries to refresh the metadata. Is there a way to disable those or reduce their number / frequency? 
Redshift has a max concurrency, so having 1000s of queries queued in the background makes the cluster unusable.

Thanks!

**Comment by salsakran** [comment]
looking into this in #1586

Going to be in our next update.
