### ISSUE TITLE
Ability to create custom audit reports

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#17018]
**Is your feature request related to a problem? Please describe.**
Some users would like to build custom audit reports without knowing the ins and outs of the application database. That's why we should provide a simplified way of letting enterprise users build their own audit reports without having to know the underlying schema.

**Describe the solution you'd like**
Adding a question builder inside the Audit feature so admins can use a simplified version of the application database schema to build custom reports

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Very important for Metabase Cloud Enterprise customers

**Additional context**
Requested by a Cloud customer

**Comment by brunobergher** [comment]
Can we close this?

**Comment by brunobergher** [comment]
Shipped with 48
