### ISSUE TITLE
Allow quick search for table in 0.40+ - similar to the schema and column quick search

### ISSUE THREAD

**Issue by JadAbdallah** [metabase/metabase#17011]
**Is your feature request related to a problem? Please describe.**
In the new Metabase version v0.40.0, the data selection feature was refined to allow to search for a table across all databases. This feature removed the ability to search within a database specifically. 

**Describe the solution you'd like**
I would like to explore bringing back that old feature on top of the current one, both are useful. 

**How important is this feature to you?**
With many databases, it makes more sense to search within one than across all. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by dangold1138** [comment]
This also manifests where Joining Data using the query builder. Since it only lets you Join within the same database, no search appear
<img width="521" alt="Screen Shot 2021-07-22 at 10 57 07 AM" src="https://user-images.githubusercontent.com/455849/126686712-28dab4ba-b012-4989-9677-3cce9eaba42b.png">

**Comment by flamber** [comment]
Changing to bug, since it makes no sense that we have quick search for schema and field, but not tables.

**Comment by ghiculescu** [comment]
I think this broke in https://github.com/metabase/metabase/pull/15875, cc @howonlee 

On 0.40.2 (version we are running) there's a `hasFiltering` prop here: https://github.com/metabase/metabase/blob/v0.40.2/frontend/src/metabase/query_builder/components/DataSelector.jsx#L969

It wasn't there pre 0.40: https://github.com/metabase/metabase/blob/v0.39.5/frontend/src/metabase/query_builder/components/DataSelector.jsx#L828..L838

I haven't yet looked into where the prop comes from but hopefully this helps accelerate a fix ❤️
