### ISSUE TITLE
Unable to synchronize Presto metadata to metabase

### ISSUE THREAD

**Issue by utopianet** [metabase/metabase#17038]
We hope to connect hive with Presto data source of metabase software for data display and analysis.

But now we can't complete the metadata synchronization, because we have tens of thousands of tables. In hive, metabase will launch validity queries on each table. Presto can't complete such a large number of queries, which leads to the failure of metadata synchronization.

We hope that for the huge database, we can provide the option of not checking the validity of the table or not, so that we can complete the metadata synchronization.

![Uploading Captura de Tela 2021-07-05 às 18.09.58 (1).png…]()
![Uploading Captura de Tela 2021-07-05 às 18.25.21.png…]()

**Comment by flamber** [comment]
@utopianet Please provide all the information requested, when opening a new issue.
