### ISSUE TITLE
Auto filtering related tables in Dashboard based on foreign key

### ISSUE THREAD

**Issue by richardlewistamr** [metabase/metabase#17037]
**Is your feature request related to a problem? Please describe.**
I would like to build a dashboard with multiple tables (questions) where each table is a different DB table in a relational model. 
I have linked the 2 tables via a foreign key in the Data Model part of the Database admin. 
I have a filter on the dashboard for an attribute present on 1 of the tables.  I would like it if when you filter one table it automatically filters the other table based on the foreign key but this is not currently happening 

**Describe the solution you'd like**
I would like to be able to filter related tables using a single attribute
e.g.  you have 2 tables "Customer" and "Customer Purchases" ,  you filter Customer_Name=Richard  , you now see 1 customer record in the Customer table  say   Customer_Name:Richard, PK:C123
and the Customer_Purchases table will ALSO be filtered  say
PK:  CP456,  FK:  C123,  Item: Apple
PK:  CP789,  FK:  C123,  Item: Orange
So the Customer_Purchases table is filtered even though it doesn't contain the Customer_Name field. 

The relationship filter would go accross many degrees so if we had a 3rd table linked to Customer_Purchases via foreign key,  lets say Customer_Payments,  then this would also be filtered too

**Describe alternatives you've considered**
Was not able to filter by name.  Had to filter by PK in the end.  But this only works for 1st degree.  Didn't work for 2 degrees of separation.  Needed to create a new question where I join the original PK onto the 3rd table so i can filter all 3 tables.  

**How important is this feature to you?**
Building this relational dashboard was my main reason for installing the tool.  Want to build a "360 degree view"  type dashboard where i can search for specific customers by name.   Have built this sort of dashboard before in Power BI quite easily but Metabase's deployment model being a server and webapp fits my needs a lot more.   

**Additional context**
Using version v0.39.4

**Comment by flamber** [comment]
This is would be solved when the following are implemented #1177/#10945/#12789 - upvote by clicking :+1: on the first post of each.
