### ISSUE TITLE
An error occurs when opening a public question with filters having default parameters

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#17033]
**Describe the bug**
When opening a public question that has filters with default values, the result is replaced with the "An error occurred while running the query" message in a couple of seconds.

**NOTE:** if you just refresh the page, it will work as expected

**To Reproduce**

1. Enable public sharing in admin
2. Ask a question > Native question > Sample Dataset
3. Enter `SELECT * FROM PEOPLE WHERE {{birthdate}} AND {{source}}`
4. Configure filters via the right sidebar:
    * `{{ birthdate }}` as a Field Filter mapped to People > BirthDate with a default of "Past 30 Years"
    * `{{ source }}` as a Field Filter mapped to  People > Source with default a of "Affiliate"
5. Save question
6. In the bottom right corner, click the "Sharing" icon (an arrow)
7. Open the share URL
8. You can see a table with results for a couple of seconds, but then it's replaced with the "An error occurred while running the query" message

**Demo**

https://user-images.githubusercontent.com/17258145/125569652-ef6b371c-8853-4eb5-9664-fd7d86bbeb36.mov

**Information about your Metabase Installation:**
Metabase 0.40.0

**Comment by flamber** [comment]
This isn't a regression per-se. We have always loaded questions multiple times, but I think it might just be more likely to hit the race-condition now, since we fixed an issue (#7120) where default filters wasn't applied correctly to Public and Embedding before 0.40.0.
