### ISSUE TITLE
With Whitelabel custom name, `Metabase` name is still shown multiple places in Admin Panel

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17043]
**Describe the bug**
The whitelabel functionality doesn't replace the name `Metabase` everywhere in the Admin Panel.

**To Reproduce**
1. Admin > Settings > Whitelabel > change name to something else - and do a browser refresh
2. Look around in the Admin Panel, there will be many references to `Metabase` instead of the custom name used.
Here are some examples:
![image](https://user-images.githubusercontent.com/1447303/125627120-3af037da-e064-447e-bbff-158095e08838.png)

**Expected behavior**
Change the name references.
There will be some things that cannot be changed (like "Diagnostic Info" attributes, or Troubleshooting Logs, or Slack bot files channel).

**Information about your Metabase Installation:**
All versions thru 1.40.0

**Additional context**
Related to #14994

**Comment by WiNloSt** [comment]
https://github.com/metabase/metabase/pull/21616 fixes some of the Metabase name replacements that should be done on FE. While the other names on other settings should be fixed on BE.

**Comment by calherries** [comment]
@flamber What about instances where the subject is a Metabase version? I'm assuming that should continue to say "Metabase"? e.g.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/39073188/214398522-59cd26d5-bb82-4408-9b37-7d877c2b41bb.png">

**Comment by paoliniluis** [comment]
I can answer that @calherries as I know several customers that use whitelabelling. This specific toggle and mostly everything in the admin section should stay with "Metabase" as it's seen by an Admin that already knows that they're whitelabelling the product

**Comment by tsmacdonald** [comment]
(will be) fixed by #31796
