### ISSUE TITLE
implications of the AGPL

### ISSUE THREAD

**Issue by lsmith77** [metabase/metabase#1705]
I guess most users of metabase will be fine with producing their users access to the source for modifications done to metabase itself. However since the drivers also seem to be AGPL that means that any application written to interface with metabase is also going to have to comply with the AGPL. is that the intention of the license choice you made?

**Comment by lsmith77** [comment]
another question .. do you have any plans to offer dual licensing to enable companies to buy themselves out of the AGPL .. at least for the drivers?

**Comment by salsakran** [comment]
The intention of the APGL is that if you want to embed Metabase in another application, white label it, host it or redistribute it, you should release your source.

We're planning on offering a dual license for things like embedding but don't have a formal process for it yet.

**Comment by lsmith77** [comment]
is there an ETA for the dual licensing?

**Comment by salsakran** [comment]
Mind if I take the conversation to email (the one on your profile)?

**Comment by lsmith77** [comment]
sure ..

**Comment by Alberto258** [comment]
Hi @salsakran, 
based on the agpl, if I embed Metabase in my application, change only the color of the UI and add a new name on top of it:
1. do I have to keep the "powered by Metabase" + URL? or
2. stick to AGPL rules and add the new source code + agpl license, without keeping the "powered by"; or
3. both of them (links to both Metabase source code, and the new source code, together with a copy of the AGPL)?

Thanks
