### ISSUE TITLE
Download full sql for a question (processing snippets and variables)

### ISSUE THREAD

**Issue by nbrustein** [metabase/metabase#17069]
**Is your feature request related to a problem? Please describe.**
I often find it useful to copy sql from metabase into a separate editor (I use DataGrip).  This is difficult, however, when the question in metabase includes snippets or, to a lesser extent, variables.

**Describe the solution you'd like**
I would like a button somewhere in the UI that causes a modal window to popup with the full, processed sql query after processing variables and snippets.

**Describe alternatives you've considered**
I thought about, instead of a modal window, just putting the sql straight into my clipboard.  Sometimes this would be even more convenient than the modal.  But sometimes I really just want to see the full query in metabase, rather than navigating through snippets.

**How important is this feature to you?**
It's a nice-to-have.  Just important enough that I took the time to write out this feature request ;)

**Comment by paoliniluis** [comment]
Hi @nbrustein I'm sure this is a UI twist of [this one](https://github.com/metabase/metabase/issues/6096), I'll be closing this issue in favor of the one I linked for simplicity
