### ISSUE TITLE
Better UI support for Postgres/Redshift Schemas

### ISSUE THREAD

**Issue by rsimpkin** [metabase/metabase#1706]
I've connected Metabase to my Redshift cluster and can see my database, however the metabase UI lists ALL the tables in ALL the schemas in one long list. In my case, I have almost 1000 so that's a very long list. It would be great if the interface could actually support the Schema object in Redshift/PostgreSQL to aid in finding and selecting the desired tables.

Repro steps:
1. Create Redshift cluster with multiple schemas and multiple tables per schema.
2. Connect Metabase to Redshift cluster with user authorized to all schemas and all tables in each schema.
3. In Metabase, Create New Question.
4. In "Data" drop down observe the Database is connected and all tables are listed, but the "Schema" concept is completely missing.

Expected Result:
The Schema object is represented and you can navigate to the desire Table by Schema.

Actual Result:
The Schema object is missing entirely. Instead, all the tables are listed alphabetically with no schema information at all.

**Comment by marcua** [comment]
+1
