### ISSUE TITLE
RestAPI doc

### ISSUE THREAD

**Issue by shammad** [metabase/metabase#1707]
hi all,

How I can generate all services which available in metabase ?

Regards,

**Comment by agilliland** [comment]
We don't have a build process for the api client, so if you want to hit the api for anything right now you'll need to either reuse the existing client code in the frontend app, or setup your own code to generate a client.

https://github.com/metabase/metabase/blob/master/frontend/src/services.js#L263

**Comment by camsaul** [comment]
@shammad your best bet actually is probably just using the [Instant Cheatsheet](https://github.com/camsaul/lein-instant-cheatsheet). 

In the metabase root dir just run

```bash
lein instant-cheatsheet
```

That will spin up a server with documentation for all the Clojure symbols in the project. The API endpoints are all implemented as regular functions so if you filter by `GET`, `POST`, etc. you will see a list of all the endpoints Metabase exposes. e.g.

![screen shot 2016-02-25 at 8 15 43 pm](https://cloud.githubusercontent.com/assets/1455846/13343024/e09fe034-dbfc-11e5-9e3c-8a3e34a518ac.png)

**Comment by camsaul** [comment]
Closing since the question was answered
