### ISSUE TITLE
Filter date field to select first day of each month

### ISSUE THREAD

**Issue by zedidas** [metabase/metabase#17077]
Suppose I have this data in a table:

Day | Some Column
----|--------------
| 2021-01-01 | ... |
| 2021-01-02 | ... |
| 2021-01-03 | ... |
| ... | ... |
| 2021-01-31 | ... |
| 2021-02-01 | ... |
| 2021-02-02 | ... |
| ... | ... |
| 2021-02-28 | ... |
| 2021-03-01 | ... | 
| 2021-03-02 | ... | 
| ... | ... |

Is it possible to use the question builder filter to select the dates which correspond to, let say, the first day of each month? Considering the previous example, I would expect to have the following result:

Day | Some Column
----|--------------
| 2021-01-01 | ... |
| 2021-02-01 | ... |
| 2021-03-01 | ... |
| 2021-03-01 | ... |
| ... | ... |

As an alternative, Is there a custom expression that I can use on the Date field to select such dates?

I've tried to achieve this with regex and a custom column but without any success. I am trying to avoid using an SQL question to solve this.

I'm using Metabase version 0.39.2.

Thanks for you help!

**Comment by paoliniluis** [comment]
Hi @zedidas, please use the forum for these types of questions, you can use a SQL question and from there use a GUI question based on the first SQL question

**Comment by zedidas** [comment]
Ok, noted. Thanks for the suggestion.

Just for reference as this may help someone else, I just found a work around using a Custom Column and a Custom Expression:

First, I create a custom column to convert the date into a string. The custom column expression is `=concat("", [Day])`.

Then, I can filter with the following custom expression, to select the dates that end in '01': `=endsWith([Date Text], "-01")`.

I understand this solution is dependent on the date format, but for now, it solves my problem.
