### ISSUE TITLE
Access of dashboard's without access to the queries / questions themselves

### ISSUE THREAD

**Issue by kp3nguinz** [metabase/metabase#17096]
**Is your feature request related to a problem? Please describe.**
We currently have to give users access to the queries themselves before they can load a dashboard, otherwise they get a permission denied for the card error message.

**Describe the solution you'd like**
Users can be granted permission to view the dashboard, and the results of the queries on those dashboards, but not the queries themselves or the data behind the queries (executives or partner teams for example).

**Describe alternatives you've considered**
Screenshots

**How important is this feature to you?**
There is a concern of exposing sensitive data in the backend data to a wide audience, when we just want them to see the roll up data. We also have to answer a ton of questions relating to the individual queries by our executive teams who get curious. 

**Additional context**
Some of our data sets have sensitive data which we don't expose, but can be drilled into currently. This keeps us from exposing the dashboards wide scale due to these concerns, requiring us to screenshot the dashboards and put them elsewhere as the rollup is what we want publicly (to the company) exposed.

**Comment by paoliniluis** [comment]
Hi @kp3nguinz, you can limit access to data and only make users see saved dashboard or questions (not create, manipulate or view underlying data). Create normal users, remove all data permissions and grant users view only permissions on the collections where the questions and dashboards exists. Please refer to the documentation https://www.metabase.com/learn/permissions/collection-permissions and post the questions in the forum

**Comment by kp3nguinz** [comment]
@paoliniluis  Notice I said without access to the question...
