### ISSUE TITLE
JIT Provisioning of Users into groups using SAML

### ISSUE THREAD

**Issue by kp3nguinz** [metabase/metabase#17094]
**Is your feature request related to a problem? Please describe.**
When new users try to login, they are denied till we add a user and put them in a group

**Describe the solution you'd like**
New user logs in using SAML, user is created, and assigned to groups which match group names in the SAML lookup.

**Describe alternatives you've considered**
GSuite, but there seems to be even less options here.

**How important is this feature to you?**
It's a limiting factor in our expansion of use of Metabase at scale.

**Additional context**

**Comment by paoliniluis** [comment]
Hi, this is the current behaviour on Metabase Enterprise (https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-saml.html), if you're using Metabase Enterprise, please contact support so we can help you. Thanks :)

**Comment by kp3nguinz** [comment]
> Hi, this is the current behaviour on Metabase Enterprise (https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-saml.html), if you're using Metabase Enterprise, please contact support so we can help you. Thanks :)

Ahh, I thought it was just users, it allows for dynamic group assignment too?
