### ISSUE TITLE
Ability to send questions/SQL Queries on a schedule 

### ISSUE THREAD

**Issue by litkej** [metabase/metabase#17097]
**Is your feature request related to a problem? Please describe.**
The sharing capability of dashboards is limited because the email content in a shared dashboard is very unappealing to the user base. You cannot adjust the subject, add any text verbiage, change the subject, etc. 

**Describe the solution you'd like**
It would be great if we had a true scheduler where we could schedule anything (questions are the most important though) and control the to, from, cc, etc. on the email, the subject and the body. I am reminded of the SSRS scheduling capability which allows for all of this info and then the ability to determine the execution schedule as well. 

![image](https://user-images.githubusercontent.com/87543116/125989865-f2195127-c39d-43be-927c-46bf2b042cd2.png)

**Describe alternatives you've considered**
I have looked into using CRON, SMTP from SQL itself, Dashboard sharing and Pulses (but they are set to be discontinued per Metabase).

**How important is this feature to you?**
This is extremely important - we will move away from all other BI toolsets if this were present. 

**Additional context**
Nothing currently.

**Comment by paoliniluis** [comment]
Hi, this is a combination of https://github.com/metabase/metabase/issues/15776 and https://github.com/metabase/metabase/issues/11000 plus more, please upvote those so we can prioritize them better, thanks!
