### ISSUE TITLE
Cannot change column type sometimes

### ISSUE THREAD

**Issue by janmpeterka** [metabase/metabase#17108]
**Describe the bug**
When changing column type in Admin > Data model, sometimes it scrolls page to top (or just some part up), and sometimes it doesn't open dialog to change column type.  

**Logs**
No javascript errors, don't have access to 

**To Reproduce**
1. Go to Admin > Data Model
2. Click on column data type
3. See error

**Expected behavior**
No page scrolling, dialog shows every time.

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.166 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "os.name": "Linux",
    "os.version": "5.4.0-74-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.25"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-14",
      "tag": "v0.40.1",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Cannot change some data types, which slightly limits (or makes more difficult) to correctly work with data

**Comment by paoliniluis** [comment]
I believe you're seeing this issue: https://github.com/metabase/metabase/issues/13805, if that's not the case, please reopen this issue
