### ISSUE TITLE
The new "last edited by/on" label on dashboards should be clickable and open revision history

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#17100]
## Current behavior
The new "Edited {time span} ago by {person}" labels on dashboards don't do anything on click. This is inconsistent from the behavior on saved questions, and defies user expectations in part because there's a hover effect on the badge.

![dashboard-last-edit](https://user-images.githubusercontent.com/2223916/126014514-679200c9-6604-4120-82bb-78f7bdf775a8.gif)

## Desired
1. These labels should be links that open the revision history modal on click.
2. We should _remove_ the "Revision history" menu item from the dashboard `…` menu.

## Future
If I have my druthers, we'll someday implement the same type of info sidebar for dashboards as we now have for questions, and the last-edited-by badge on dashboards would open that sidebar, with the revision history expanded, just as it does for saved questions.

**Comment by mazameli** [comment]
I've updated this issue to reflect that we've fixed the behavior on saved questions, and that the existing issue is only with dashboards now.

**Comment by daltojohnso** [comment]
This was implemented at some point

https://user-images.githubusercontent.com/13057258/166976525-a995d1a0-ce62-4025-bc8a-a541a49c765b.mov
