### ISSUE TITLE
Supporting plugins / extensions

### ISSUE THREAD

**Issue by hokkaido** [metabase/metabase#1710]
I've been wondering whether there are any plans for supporting a plugin system. At the moment, it looks like one has to fork the entire project if they want to add a new database driver. Another point where plugins would help is with the front-end side, i.e. if somebody wants to add new functionality (components / routes / new visualization options etc.) to the UI. 

A plugin system would probably also help with creating a healthy eco-system. I'm certain that there are modifications, ideas and features that do not necessarily belong into metabase core, but that still might be of interest to a segment of the current or future metabase users.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Metabase actually does support 3rd-party drivers as plugins. If you [write a driver](https://github.com/metabase/metabase/wiki/Writing-A-Driver) and and add it to your classpath when launching Metabase it'll be available.

**Comment by MartinArens** [comment]
+1

**Comment by ryanmccoy** [comment]
@camsaul A driver is specifically for writing DB extensions though, unless I understand incorrectly. 

I have to agree with @hokkaido - I absolutely love this product but the one limitation is that, like any open-source tech, it is lacking in features when compared to the behemoth commercial alternatives. This isn't necessarily a knock against it, but what wonderful things one could do if there was a simple system for people already adept at Clojure to share their various enhancements with others easily. 

For example a system for sharing visualisation plugins so one can download say a circular area chart or a multi-level pie chart or a heat map (and I don't mean a geographical map, but rather a distribution of data across a 2-axis series for example visualising the standard deviation of various product's performances over time)

**Comment by borgmark** [comment]
Definitely agree with @ryanmccoy comment, Metabase is an extremely easy to install and easy to use platform. Making such platform extendible through plugins will surely take it to the next level.

**Comment by StephenOTT** [comment]
Any updates on this?

**Comment by beingyash** [comment]
A plugin ecosystem like the one [grafana](https://grafana.com/) has would be great and shall also keep the community stirred in the context of future possibilities it could bring to the platform.

**Comment by flamber** [comment]
Closing this, since modular drivers has been supported since 0.32:
https://www.metabase.com/docs/latest/developers-guide-drivers.html
There's a separate issue for visualization plugins #2318 - upvote by clicking :+1: on the first post of the issue.
