### ISSUE TITLE
Persian localization

### ISSUE THREAD

**Issue by arefhosseini** [metabase/metabase#17107]
Hey there,
I got a problem with changing localization into **Persian**. All languages change but Persian affect nothing.
By the way I use Java server.
Thanks

**Comment by paoliniluis** [comment]
Hi @arefhosseini, I can see that Persian works when you select the language:
![image](https://user-images.githubusercontent.com/1711649/126160344-dfd8c29f-a4d5-4d0d-8819-bf560383b765.png)

please post your questions in the forum :) thanks!
