### ISSUE TITLE
Elastic Beanstalk nginx config is not updated on latest EB docker images

### ISSUE THREAD

**Issue by francesmcmullin** [metabase/metabase#17115]
**Describe the bug**
The script `metabase-setup.sh` relies on the presence of `/etc/nginx/sites-available/` in order to make updates to nginx configuration, but this folder is not present on the latest Elastic Beanstalk docker images (e.g., Docker running on 64bit Amazon Linux 2/3.4.2) do not have this folder.

I'm focused here on the nginx timeout, because that's the functionality I was missing, but there may be other impacts. This may also connect with some of the discussion in #12423 , although timeouts happen for various reasons and this is just one of them.

**Logs**
I found these lines in `cfn-init-cmd.log` after a normal/successful deploy.
```
2021-07-13 05:14:27,474 P3138 [INFO] Config postbuild_0_Uplift_Metabase
2021-07-13 05:14:27,500 P3138 [INFO] ============================================================
2021-07-13 05:14:27,500 P3138 [INFO] Command 01_server_https
2021-07-13 05:14:27,506 P3138 [INFO] -----------------------Command Output-----------------------
2021-07-13 05:14:27,506 P3138 [INFO] 	.ebextensions/metabase_config/metabase-setup.sh: line 36: cd: /etc/nginx/sites-available/: No such file or directory
2021-07-13 05:14:27,506 P3138 [INFO] ------------------------------------------------------------
2021-07-13 05:14:27,506 P3138 [INFO] Completed successfully.
2021-07-13 05:14:27,514 P3138 [INFO] ============================================================
2021-07-13 05:14:27,514 P3138 [INFO] Command 02_log_x_real_ip
2021-07-13 05:14:27,521 P3138 [INFO] -----------------------Command Output-----------------------
2021-07-13 05:14:27,522 P3138 [INFO] 	.ebextensions/metabase_config/metabase-setup.sh: line 160: cd: /etc/nginx/sites-available: No such file or directory
2021-07-13 05:14:27,522 P3138 [INFO] ------------------------------------------------------------
2021-07-13 05:14:27,522 P3138 [INFO] Completed successfully.
```

**To Reproduce**
1. Setup metabase on AWS Elastic Beanstalk using the [published guide](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html)
2. In particular, use the "Docker running on 64bit Amazon Linux 2" platform branch
2. After setup, change your Load Balancer Timeout from 60 seconds to 600 seconds (NB: found under EC2 -> Load Balancers, *not under elastic beanstalk config*)
3. Review your Elastic Beanstalk logs and observe the error above in `var/log/cfn-init-cmd.log`
4. Attempt to load a long-running / slow query. (For testing in Postgres, you could just use `select pg_sleep(70), 1;`. Observe that the query times out at 60 seconds. Checking the network tab, observe the timeout comes from nginx

**Expected behavior**
- No errors in `var/log/cfn-init-cmd.log`
- A default nginx timeout of 600 seconds

**Screenshots**

**Information about your Metabase Installation:**

- Your browser and the version: Chrome / N/A
- Your operating system: MacOS / N/A
- Your databases: Postgres
- Metabase version: 0.40.1
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Annoying (I've found a workaround)

**Workaround**
Based on [Amazon's advice for configuring nginx under the newer docker image (expand "reverse proxy configuration", scroll to nginx)](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html), I opened `metabase-aws-eb.zip` and added `.platform/nginx/conf.d/metabase.conf` with the following content:
```
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;
```
NOTE: This workaround functions fine for my purposes (avoiding timeouts), but it doesn't even attempt to replicate the variety of functionality previously implemented in `metabase-setup.sh`.

**Comment by paoliniluis** [comment]
Frances, great catch, in fact, we are thinking in removing Nginx in the Elastic Beanstalk bundle to simplify the stack.

Related to https://github.com/metabase/metabase/issues/16014

**Comment by francesmcmullin** [comment]
Hi Luis. Thanks for the quick response! I'm especially interested in timeouts as I have several queries running longer than a minute. When you mention removing Nginx, are you thinking of removing that proxy layer entirely (great! no timeouts in a stack we've bypassed!), or removing the custom nginx config (sounds like I would need to continue using my workaround)?

I realise the EB deployment model causes a fair amount of maintenance headaches, so I'm really grateful for any help, thank you.

**Comment by paoliniluis** [comment]
Hi @francesmcmullin, are you able to try this test bundle in order to check if things go smooth? This one replaces the default nginx.conf which a custom one with the timeouts
[metabase-ebs.zip](https://github.com/metabase/metabase/files/6897620/metabase-ebs.zip)

let me know if it works so we can bundle it in the next maintenance release :)

**Comment by francesmcmullin** [comment]
Thanks for that, @paoliniluis . That zip works well from the perspective of timeouts, I can still load slow questions no problem. However, Elastic Beanstalk complains of a "Target.ResponseCodeMismatch" and sets the status to "Severe". I believe this is because the `api/health` endpoint begins giving a response code of 301 instead of 200, I may have time to investigate further next week.
