### ISSUE TITLE
pulse card rendering fails on question with decimal values when using sql

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1714]
not sure if this is specific to SQL usage or not, but this error is being generated when trying to add a card to a pulse when the card has decimal values in the data.

```metabase.pulse :: Pulse card render error:java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.```

**Comment by agilliland** [comment]
did a little more testing on this and it looks like this is limited to SQL queries which result in a timeseries that has decimal values.  i couldn't make this fail when using the GUI query builder.

**Comment by tlrobinson** [comment]
@agilliland Can you give me an example using the Sample Dataset? Couldn't reproduce with this: `SELECT month(created_at), avg(total) FROM orders GROUP BY month(created_at);`

**Comment by agilliland** [comment]
`select "createdAt"::date, avg(guests) from booking group by 1 order by 1`

**Comment by tlrobinson** [comment]
@agilliland I'm not able to reproduce this using the Sample Dataset or a Postgres table I created to match that query (`CREATE TABLE booking (createdAt timestamp, guests int);`). Can you give me some sample data?

**Comment by camsaul** [comment]
@agilliland can you figure out what value is causing the error? Then we can test it with a query like
```sql
SELECT 100.2
```

**Comment by agilliland** [comment]
it needs to be a timeseries, so this results in an error `select now(), CAST(12.44 as float)`

**Comment by camsaul** [comment]
postgres ?

**Comment by agilliland** [comment]
yeah

**Comment by tlrobinson** [comment]
Does this only occur when there's a single row? I still can't reproduce that specific error, though if I have a single row I get `2016-01-26 16:53:40,361 [WARN ] metabase.pulse :: Pulse card render error:java.lang.ArithmeticException: Divide by zero`

**Comment by tlrobinson** [comment]
This, for example, works fine: `SELECT A, B FROM (VALUES (now(), CAST(12.44 as float)), (now() + INTERVAL '1 day', CAST(11.44 as float))) AS foo(A,B);`

**Comment by camsaul** [comment]
![image](https://cloud.githubusercontent.com/assets/1455846/12600323/c5aa7b20-c44d-11e5-813d-3c38382c001d.png)

**Comment by agilliland** [comment]
yeah, the divide by 0 is a new one, just noticed that.

i'm using postgres and the table i'm pulling from has a `created_at` which is a timestamp and a `guests` column which is an integer.  then doing the query i mentioned above which generates a timeseries of the avg guests by day results in the original error

```Pulse card render error:java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.```

**Comment by tlrobinson** [comment]
@agilliland Can you construct a query with inline data (like the one I posted about) that triggers this? Or give me the table you're using?

**Comment by camsaul** [comment]
:+1: I can't produce a query that triggers this either.

**Comment by agilliland** [comment]
Sadly, after applying this fix to some running MB instances I'm still seeing an error ...

```
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:  2016-01-28 22:25:59,620 [ERROR] metabase.middleware :: GET /api/pulse/preview_card_info/928 500 (1 s)
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:  {:message
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:   "Non-terminating decimal expansion; no exact representable decimal result.",
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:   :stacktrace
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:   ["metabase.pulse$render_table$fn__14585.invoke(pulse.clj:245)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.api.pulse$fn__22616$fn__22617.invoke(pulse.clj:99)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.api.common.internal$wrap_catch_api_exceptions.invoke(internal.clj:216)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.api.pulse$fn__22616.invoke(pulse.clj:91)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.middleware$enforce_authentication$fn__23234.invoke(middleware.clj:82)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.api.routes$fn__23354.invoke(routes.clj:49)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.routes$fn__23910.invoke(routes.clj:23)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.middleware$log_api_call$fn__23327.invoke(middleware.clj:256)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.middleware$add_security_headers$fn__23287.invoke(middleware.clj:193)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.middleware$bind_current_user$fn__23238.invoke(middleware.clj:95)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.middleware$wrap_current_user_id$fn__23212.invoke(middleware.clj:64)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.middleware$wrap_api_key$fn__23253.invoke(middleware.clj:106)"
Jan 28 14:25:59 metabase-spot 8c88df003ac6-stdouterr.log:    "metabase.middleware$wrap_session_id$fn__23205.invoke(middleware.clj:55)"]}
```

**Comment by tlrobinson** [comment]
Gah, I fixed it for sparklines, this looks like a similar problem in tables.

Did the query process/drivers recently change to return `BigDecimal`s? I'm not sure why else this would have suddenly broken.

**Comment by AdamLandis** [comment]
I've been running into this problem for a while - will I need to wait until the next release to see the fix?

**Comment by tlrobinson** [comment]
Sorry, this didn't make it into 0.14, but we'll likely be releasing 0.14.1 within a week or so.

**Comment by agilliland** [comment]
Hey @AdamLandis , just a heads up that we are including this in the 0.14.1 patch release that we plan to put out in the next day or two.  So the fix is coming soon.

**Comment by AdamLandis** [comment]
Thanks Allen – your recommendation on forcing the query’s float value have been more than sufficient in the meantime. Thank you.

-AL

**Comment by timabe** [comment]
I am still getting this error. Here's an example with the sample database.

Question
`select created_at::DATE, (subtotal/3.3) as ratio  FROM orders `

Then I save it and go create a pulse. It renders like this:

![screen shot 2016-05-03 at 11 18 37 am](https://cloud.githubusercontent.com/assets/1427277/14993737/1a8016bc-1121-11e6-83fb-e39ab17cd582.png)

I tried casting the ratio as a float, but it didn't change anything. Are there any work arounds to avoid this?

**Comment by timabe** [comment]
If anyone else has this problem, you can fix it by ordering your date.

`SELECT created_at::DATE , (subtotal/3.3) as ratio FROM orders ORDER BY 1;`

Will work!
