### ISSUE TITLE
Blank page when adding user using "invite someone" button

### ISSUE THREAD

**Issue by jcorrea-tkww** [metabase/metabase#17146]
**Describe the bug**
As an admin I tried to add a new user, using the "invite someone" button, like usual.  The issue is that instead of showing the modal with the form a blank page appears so we cannot fill in any form (apparently is behind the blank page)

**Logs**
[metabase.nuptic.com-1626870834991.log](https://github.com/metabase/metabase/files/6855710/metabase.nuptic.com-1626870834991.log)

**To Reproduce**
1. Go to Admin->People
2. Click on 'Invite Someone'
3. Instead of seeing the form in the modal, you see a blank page.

**Expected behavior**
See the invite someone form 

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "es-ES",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "es",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics",
      "bigquery",
      "sqlserver",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.22"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.40.1",
      "date": "2021-07-14",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
**Severity**
We cannot add new users

**Comment by paoliniluis** [comment]
Hi, according to the logs you are using a CDN (Akamai) that is blocking your requests. Where and how are you hosting Metabase?

**Comment by jcorrea-tkww** [comment]
I have been using MEtabase in the same way for years, this only happens after the 0.40.1 release
