### ISSUE TITLE
Cannot use Click Behavior for filters with multiple options selected

### ISSUE THREAD

**Issue by jamundson5** [metabase/metabase#17160]
**Is your feature request related to a problem? Please describe.**
I currently have a public dashboard set up that includes several filters. I want users to be able to click a card on the dashboard and be taken to a public question with some filter values brought over.

This is currently achievable with Click Behavior, but it has some caveats.

I can set up the card to bring filters over to the question if I'm not using the public/shared version. This works well, and is what I will probably have to do in practice. However, I would rather not give users a login even if I restrict the login as much as possible.

I'd much rather send the user to the public version of the question. Now, before you say that I can already do this by using the Custom URL option, I have tried that. And it works. BUT only if each filter has one value.

If a text filter is given multiple values, then it's sent to the question as a comma separated list, which the question cannot understand. No results display.

**Describe the solution you'd like**
It would be nice to have the Question/Dashboard destination default to the public/shared version if starting on a public/shared dashboard.

**Describe alternatives you've considered**
Alternatively, I would simply like the ability to bring over multiple value filters to a public question using the Custom URL option.

**How important is this feature to you?**
Important to prevent unnecessary access to Metabase logins.

**Additional context**
![f243a55d6f73a11810b5cc55789859abc03f8090_2_690x376](https://user-images.githubusercontent.com/41020387/126557398-557e79cf-461c-4ea0-b73f-481884f6bc0b.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #14009

**Comment by bladexxx** [comment]
@flamber  when will this issue be fixed? This issue affects the user experience when we want to switch between multiple dashboards with the same filters.  That will be great if it can be fixed in next release

**Comment by flamber** [comment]
The bug parts of this issue is fixed in upcoming 43.2, while feature functionality will be part of upcoming 44 together with #14009.
