### ISSUE TITLE
Version 0.40.0 displays only 50 users under dashboard subscribers

### ISSUE THREAD

**Issue by stantaov** [metabase/metabase#17164]
Version 0.40.0 displays only 50 users under dashboard subscribers
When I check user XHR  I see these lines added, which prevent displaying complete list of all users. 

.....
  "total": 126,
    "limit": 50,
    "offset": 0
}

The older 0.39 version didn't have it and displays all users to select as a dashboard subscriber.

**Comment by alxnddr** [comment]
@howonlee there are some other places in the app that require to fetch all users, so we should not limit the response unless it is explicitly specified
