### ISSUE TITLE
Dashboard - Adding ‘Click Behavior’ to an image field converts image to URL

### ISSUE THREAD

**Issue by jamundson5** [metabase/metabase#17161]
**Describe the bug**
I am currently looking at version 0.40.1 as we prepare to upgrade from 0.38.0. I'm running into one seemingly small issue that is actually a pretty big issue for us in practice.

I have several dashboards that display book cover art. When users click on the cover, it is supposed to take them to the title in our local catalog. I accomplish this by generating the image's URL with SQL in the question, and then adding click behavior to field on the dashboard to redirect to the entry in our catalog.

However in 0.40.1, when I add click behavior to the image, it reverts itself to the URL of the image.

I need to keep both the click behavior and image for the dashboard.

**To Reproduce**
1. Create a question that contains URL output for an image. Set "View as link or image" to Image so that it displays as an image. (Note that my question was written in native SQL, but I don't know if that is necessary.)
2. Add the question to a dashboard. Note that the image column displays as intended.
3. Add click behavior to the image column to go to a custom URL. I do not think the URL used matters.
4. Note that the column reverts to the URL display. This persists even after confirming the visualization of the question in the dashboard is correctly set to Image.

**Expected behavior**
To retain the image display of the field when adding click behavior. 

**Screenshots**
![d53f6764b615398d9c40227783062bb432e38e73](https://user-images.githubusercontent.com/41020387/126559911-9550c7c6-ed6e-4890-9db9-3d270152e1ec.png)

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-Ubuntu-0ubuntu2.18.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-Ubuntu-0ubuntu2.18.04",
    "os.name": "Linux",
    "os.version": "4.15.0-147-generic",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "7/19/2021",
      "tag": "v0.40.1",
      "branch": "image_code",
      "hash": "?"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

- Your browser and the version: Google Chrome Version 91.0.4472.124
- Your operating system: Windows Version 10.0.19042 Build 19042
- Your databases: Postgres
- Metabase version: 0.40.1
- Metabase hosting environment: Docker (I believe)
- Metabase internal database:  H2

**Severity**
This is blocking our upgrade path from 0.38. It is very important to my installation to have this fixed. I'm excited for many of the quality-of-life improvements I'm seeing in 0.40, but this is a deal breaker because we need to have the cover art clickable.

**Comment by flamber** [comment]
Regression since 0.38.1 - very likely caused by #15015 - since you're already using a custom build, then you should be able to fix that fairly easily until a permanent solution is integrated.
