### ISSUE TITLE
Applying filters over question using saved questions

### ISSUE THREAD

**Issue by federf** [metabase/metabase#17176]
Hi, im doing some tests locally with metabase v0.41.2 and I was testing the following:

https://www.metabase.com/docs/latest/users-guide/referencing-saved-questions-in-queries.html

I created a 3 questions:

- (q1) a total count of elements (i.e. numbers)
- (q2) a total count of elements that meet a condition (i.e. numbers greater than 20)
- (q3) the percentage of elements that meet the condition (i.e. those greater than 20)

I have the following question for (q3):
``
select {{#2}} / {{#1}};
``

My question is:
Is there a way to apply the filters that im applying over q1 and q2 (they have the same filters) over q3 when including them on a dashboard?

**Comment by flamber** [comment]
Hi @federf 
Latest release is 0.40.1. It's currently not possible to pass-thru filters to nested questions without a bit of secondary sub-selects.
See #6449 - upvote by clicking :+1: on the first post
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
