### ISSUE TITLE
Add API Changes to the Release Notes

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#17171]
There has been some changes to Metabase API in v.39 and v.40, but there was no mention of them in the release notes. As a result the packages built on top of the Metabase API (e.g. [Python wrapper for Metabase API](https://github.com/vvaezian/metabase_api_python)) would break.
That would be nice to have these changes documented somewhere and included in the release notes (or adding a link to these changes in the release notes) so that we can make the required changes in our code in a timely manner.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by paoliniluis** [comment]
There's now an api changelog https://www.metabase.com/docs/latest/developers-guide/api-changelog
