### ISSUE TITLE
Support "Add Database" PostgreSQL by Unix Socket

### ISSUE THREAD

**Issue by singpolyma** [metabase/metabase#17183]
**Is your feature request related to a problem? Please describe.**
When I go to `/admin/databases/create` it requires a username and expects to be connecting via TCP to postgresql databases.

**Describe the solution you'd like**
I would like to be able to put in a URI like I can for the app database, then I can specify to use a unix socket with no username.

**Describe alternatives you've considered**
I could enable TCP on my database, but I'd really rather not.

**How important is this feature to you?**
I'm not sure I can use metabase safely without this.

**Comment by flamber** [comment]
Duplicate of #11414
