### ISSUE TITLE
Support PostgreSQL range types

### ISSUE THREAD

**Issue by singpolyma** [metabase/metabase#17184]
**Is your feature request related to a problem? Please describe.**
When I choose a column to type https://www.postgresql.org/docs/9.3/rangetypes.html metabase doesn't really know what to do with it.

**Describe the solution you'd like**
Would be nice if I could at least do things with the range min and max, especially for date ranges.

**Describe alternatives you've considered**
Right now I have to write SQL for everything.

**Comment by flamber** [comment]
Duplicate of #6800
