### ISSUE TITLE
hot reloading doesn't work without local modifications?

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1720]
Looks like running ```npm run build-hot``` breaks due to the CORS policy of the backend and therefore the frontend client doesn't load while in "HOT" mode without locally modifying the list to allow the hot reload server to serve assets.

@tlrobinson do you still use a local workaround for this?

**Comment by agilliland** [comment]
this is already filed as #1669

**Comment by kdoh** [comment]
Closing as a duplicate of #1669
