### ISSUE TITLE
Only 50 groups are displayed

### ISSUE THREAD

**Issue by jcorrea-tkww** [metabase/metabase#17200]
**Describe the bug**
Only first 50 user groups are displayed

**To Reproduce**
1. Go to Admin
2. Click on People->Groups
3. Only fisft 50 groups are displayed.  No pagination exists

**Expected behavior**
Having pagination on Groups page

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "es",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics",
      "bigquery",
      "sqlserver",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.22"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.40.1",
      "date": "2021-07-14",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
- We cannot see all groups to see who is in each group.
- We cannot add members to groups from the group side.

**Comment by flamber** [comment]
Related to #17164

**Comment by alxnddr** [comment]
@howonlee the back end does not return limit: 50, but it limits the results to 50 groups. Can you please take a look?

**Comment by nemanjaglumac** [comment]
This limit seems to be set on the backend, thus I assigned the issue to @howonlee .
While trying to reproduce it, I couldn't stub the response because FE displays whatever BE returns. By first actually creating more than 50 groups and then waiting for the response, one can see that indeed only the first 50 groups are sent.

Unlike #17164, I didn't see `limit: 50 `explicitly anywhere in that response.

@alxnddr thinks we should remove the limit, rather than creating a pagination for this page.
