### ISSUE TITLE
Data value incorrectly shown for Lines with missing value set to Nothing

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17205]
**Describe the bug**
Data point values incorrectly shown at the X-axis for Lines with missing value set to Nothing.
It essentially behaves similar to setting the line missing value to Zero.

**To Reproduce**
1. Native query > Sample Dataset
```
select 1 as "lag", 0.1 as "Jan_2021", 0.2 as "Feb_2021"
union all
select 3, 0.1, null
```
2. Change Visualization to Line chart, with "lag" as X-axis and the two other columns as Y-axis
3. Under Display, enable "Show values on data points" and set "Replace missing values with" to `Nothing`
4. Notice the two data point zeros showing up in the bottom
![image](https://user-images.githubusercontent.com/1447303/127038161-4b12c21e-c166-49d0-8d7b-c88edfa1adc2.png)

**Information about your Metabase Installation:**
Tested 0.38.0 thru 0.40.1

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by EvaSchreyer** [comment]
still a bug in 0.40.5
