### ISSUE TITLE
Question sidebar works noticeably slow

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#17217]
**Describe the bug**
Question sidebar works noticeably slow.

**To Reproduce**
1. Create a simple question with the People table from the Sample Dataset
2. Trigger opening and closing sidebar with settings/visualization settings/question

**Video**
<video src="https://user-images.githubusercontent.com/14301985/127151314-cb7ea4c3-2442-4af4-9c2b-ac522e70be35.mov"></video>

I was able to reproduce it on `0.40` and `0.39`

**Comment by flamber** [comment]
I cannot reproduce on releases nor on the exact question on master. This amount of slowness would have been reported everywhere, so I think it's specific to your browser (extensions perhaps?).

**Comment by alxnddr** [comment]
@flamber thanks for checking, turned out it was a temporary issue with my mac
