### ISSUE TITLE
Not possible to apply dashboard ID filter to a nested QB question

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17212]
**Describe the bug**
It is not possible to apply dashboard ID filter to a nested QB question. If you try that, UI will show "No valid fields" to connect to.

**Logs**
N/A

**To Reproduce**
1. Open "Products" table from the "Sample Dataset" and save it as a question
2. Ask new question > Custom > Saved > Choose previously saved "Products"
3. Save it as "Products nested"
4. When prompted, add nested question to the dashboard
5. Add ID filter to the dashboard
6. Observe that you cannot connect it to any of the fields.
(I was trying to save the dashboard, refresh it... nothing helps)

Here comes the crazy part:
7. Add "regular" `Products` question to this same dashboard
8. All of a sudden, you can connect ID filter to **both** cards!
https://share.getcloudapp.com/rRuj4LO1

**Expected behavior**
It should be possible to use ID filter on a nested QB question

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/127064362-9b3f53b1-e683-46d4-bc66-cd39ffb729d4.png)

**Information about your Metabase Installation:**
local dev, H2, `master`

**Severity**
Feels like a solid P2.

**Comment by flamber** [comment]
Pretty sure it's a race-condition, so it's not always reproducible (note for devs).
Instead of adding the extra card, you can also save the dashboard, browser refresh, then edit the dashboard again.

**Comment by flamber** [comment]
@nemanjaglumac Are you able to reproduce this anymore on 43? There has been so many small changes, which fixed possible race-conditions. But it could still be problems with result_metadata.

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac Are you able to reproduce this anymore on 43? There has been so many small changes, which fixed possible race-conditions. But it could still be problems with result_metadata.

@flamber nope. Just tried it and cannot reproduce.
