### ISSUE TITLE
Search widget on question builder hangs tab, API field search limit not respected

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#17228]
**Describe the bug**
When in the standard query builder and searching for values in a field with many values, the tab can sometimes totally hang and need to be refreshed.

**Logs**
Nothing of interest

**To Reproduce**
Note that this doesn't repro the hang of the tab as I couldn't make it happen in the sample DB, but it does repro what I think is the root cause of the hang I'm seeing on my data sets.
1. Ask a Question > Sample Data > Reviews
2. Open browser dev tools, Network
3. Click the Body column header > Filter by this column
4. Enter "sed" in the search dialogue
5. The api request in the network monitor shows `api/field/33/search/33?value=sed&limit=100`
6. Note the response in the network tab, **321 results are returned**

**Expected behavior**
The search API response should respect the row limit specified. And/or the search widget list should be capable of handling larger result sets without hanging.

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/127248283-6b3d91f4-6b28-4e30-ac32-5679670e6cad.png)

In my live environment this issue leads to a full screen hang when searching some fields.
![image](https://user-images.githubusercontent.com/4504437/127248409-1eb6965a-d571-4389-a5c9-b9526ebd0b9a.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.40.1",
      "date": "2021-07-14",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Severity**
This is making some operations that used to work impossible in the same manner after upgrading to v0.40.1. There are work arounds but they all require people to use the system differently. Note that even when the API request completes and the search widget list populates the screen is still in a frozen state and no clicks register.

**Additional context**
As I said my repro on the sample DB doesn't reproduce the tab hang, but I think it's related to the API issue identified.

**Comment by flamber** [comment]
Hi @notrom 
As usual, excellent debugging :heart: 
Regression since 0.40.0 - on 0.39.4 it returned 100 results.
This might be a close P1, since for fields that is set to Searchbox, it will generate a query without limit (1048575) to the warehouse, which can cause a huge result and the browser will then freeze, while chewing through that.
