### ISSUE TITLE
Cannot start development in VS Code because of missing Node.js

### ISSUE THREAD

**Issue by ChakshuGautam** [metabase/metabase#17233]
**Describe the bug**
The dev container dockerfile is of Java:11 and node is not getting installed by default.

**Logs**
```sh
Executing task: yarn dev <

Yarn requires Node.js 4.0 or higher to be installed.
The terminal process "bash '-c', 'yarn dev'" failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.
```

**To Reproduce**
1. Cloned the repo using `git clone`
2. Opened the repo on VSCode.
2. From the command palette ran - _Remote-Container: Reopen in Container_
3. From the command palette ran - _Tasks: Run Build Task_

**Expected behavior**
Localhost should open

**Information about your Metabase Installation:**
Current master branch - commit (6bcc6b54ddf11041cec9f18aface8b3029bfa17b)
Using OSX - Docker v20.10.7

**Severity**
Low. Need to add a couple of cosmetic features to Metabase.

**Comment by flamber** [comment]
Hi @ChakshuGautam 
I don't understand your steps - is that GitHub Desktop or something like that?
I would recommend that you try the release branches - currently [release-x.40.x](https://github.com/metabase/metabase/tree/release-x.40.x)

**Comment by ChakshuGautam** [comment]
No. Cloned using `git clone` and using the `master` branch.

**Comment by ChakshuGautam** [comment]
Updated the steps.

**Comment by ChakshuGautam** [comment]
https://github.com/metabase/metabase/blob/master/.devcontainer/Dockerfile this should include Node.js right?

**Comment by ChakshuGautam** [comment]
Currently, I have updated the Dockerfile as follows
```Dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/java:11

RUN apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com\
  && apt-get update && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install --no-install-recommends leiningen

RUN apt-get update && apt-get install -y \
  software-properties-common \
  npm
RUN npm install npm@latest -g && \
  npm install n -g && \
  n latest
RUN npm install --global yarn
```

It seems to be working fine. But I am sure I am missing something.
