### ISSUE TITLE
The Notebook's buttons are missing their background colors, and Custom Column button is in wrong place

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#17253]
Here's how the notebook looks on master:

![image](https://user-images.githubusercontent.com/2223916/127532684-263a83e6-bcfb-441f-8c5f-49e636a40f8f.png)

The Filter, Summarize, and Join Data buttons should look like this, and the Custom Column button should come after the Join button:

![image](https://user-images.githubusercontent.com/2223916/127532971-a2a4db38-2ac2-4fdf-82e5-fd9fd30b7e6a.png)

The small Filter and Join buttons should look like this:

![image](https://user-images.githubusercontent.com/2223916/127533073-662e6e89-2242-4fac-b7bf-cac9bb8f577e.png)

**Comment by flamber** [comment]
Fixed by #17313

**Comment by ariya** [comment]
> Fixed by #17313

I believe I haven't fixed the incorrect position of Custom Column button yet.

**Comment by flamber** [comment]
Okay, the button position has always been there:
![image](https://user-images.githubusercontent.com/1447303/128211737-52e0a26f-ce3f-45f4-a6d3-b13661620b8d.png)

**Comment by ariya** [comment]
> Okay, the button position has always been there:

Thanks @flamber!

@mazameli Where's the intended location for the Custom Column button?
From @flamber's screenshot, looks like the order has not changed since v37.

**Comment by mazameli** [comment]
@ariya Huh, I was comparing master against stats or documentation images (can't recall), but turns out I was wrong. The [blog post for 0.33](https://www.metabase.com/blog/0.33/index.html) shows the order was originally intended to be 
1. Sort
2. Row limit
3. Custom column

So please disregard that portion of this issue — the order is already correct.
