### ISSUE TITLE
[BUG] "Sorry, You don't have permission to see that" 

### ISSUE THREAD

**Issue by AliHublo** [metabase/metabase#17288]
**Describe the bug**

When I work on a metabase question, the page refresh itself and show me the message "Sorry, You don't have permission to see that". It happens to several people in my team. My Manager don't understand why this message pops up everytime. 

**Logs**
![Capture d’écran 2021-08-03 à 10 07 07](https://user-images.githubusercontent.com/88371448/127980830-8160b24a-0574-49e5-b2bf-84d1dd793738.png)

**To Reproduce**
1. Go to Metabase
2. Click on Operation, then Support
3. Scroll down to Information on Worker
4. Use the question several times until the bug shows up
5. See error

**Expected behavior**
When I use a question, the page doesn't bug. I have the permission to use it. 
**Screenshots**
![Capture d’écran 2021-08-03 à 10 09 39](https://user-images.githubusercontent.com/88371448/127981160-cc4cf982-11ca-4eb4-878f-2798215f16c2.png)

**Information about your Metabase Installation:**
Metabase has been installed with Hublo company.

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome (Version 92.0.4515.107 (Build official) (x86_64)
- Your operating system: OX Big Sur 11.5
- Your databases: I don't know
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: Mac app
- Metabase internal database: I don't know

**Severity**
Block our daily usage (Support Team)

Note: the more honest and specific you are here, the more we will take you seriously.

**Additional context**
It just happened suddenly and since we have the bug appearing every time. We have to refresh it to suppress it but it gets very annoying.

**Comment by flamber** [comment]
Hi @AliHublo 

Post "Diagnostic Info" from Admin > Troubleshooting.
When you see the error, then post the full detailed stacktrace from Admin > Troubleshooting > Logs.

Your steps to reproduce is impossible to follow, since it's specific to your data, so describe what "Operation", "Support" and "Information on Worker" is (questions, dashboards etc), and what you are doing.

**Comment by flamber** [comment]
@AliHublo You cannot attach images via email on Github.
But you need to provide the following information:
1. Post "Diagnostic Info" from Admin > Troubleshooting.
2. When you see the error, then post the full detailed stacktrace from Admin > Troubleshooting > Logs.
