### ISSUE TITLE
placeholder text for presto details is not defaulted when left out

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#17333]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/6377293/128399539-a3fd2fdc-0868-4757-a76a-77c9e0702430.png">

Placeholder text here is localhost

But when connecting this placeholder text doesn't end up as a default
<img width="644" alt="image" src="https://user-images.githubusercontent.com/6377293/128399613-b7827ece-b81b-4752-9e30-7c3aa316767f.png">

**Comment by noahmoss** [comment]
This is what the Presto connection form looks like now, as of 41:
<img width="672" alt="Screen Shot 2022-03-02 at 10 48 23 AM" src="https://user-images.githubusercontent.com/32746338/156396908-5af7bc9b-ba27-4330-a606-0d82e2d4e90b.png">

I'd argue that the current placeholder `name.database.com` should not be the default if the field is left blank, and returning a "No host specified" error message is correct. So I'm going to close out this issue, but feel free to re-open if anyone objects.
