### ISSUE TITLE
Polish to Official Collections aka Collection Types

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#17336]
## We should include the ribbon icon in the Collections permissions grid

![image](https://user-images.githubusercontent.com/2223916/128409739-7f663e62-8d13-4df5-a103-ee04c0480dbc.png)

## Let's make top-level official collections on the homepage look like this to help them stand out more:

![image](https://user-images.githubusercontent.com/2223916/128402978-5a46abcb-089b-40e3-abd6-cb8366411ffc.png)

## In the sidebar, the arrows are 2px too high up. Desired positioning on the right.
![image](https://user-images.githubusercontent.com/2223916/128405094-35a881dd-54b2-4db9-98e6-30afd4d81fcd.png)

## A couple things we can improve about the toggle in the collection create/edit modal
- Make the selected state for the toggle use blue/yellow as the background color and white for the text
- Make the border color match the inputs: #CED3D7
- Make the unselected toggle text color `text-dark`
- The hover treatment of the unselected toggle should stay the same

![image](https://user-images.githubusercontent.com/2223916/128406703-aff354ca-4d6f-4f2a-9dbc-b4c00021402a.png)

![image](https://user-images.githubusercontent.com/2223916/128407048-d5509d9a-f304-426c-a9c2-af545c46823a.png)

![image](https://user-images.githubusercontent.com/2223916/128407111-ca664ead-d98e-43e6-aba4-306d140d1c29.png)

## We should add tooltips when hovering over the ribbon icon

![image](https://user-images.githubusercontent.com/2223916/128409405-c6dcc342-43ab-49ae-923a-a008f6f383be.png)

![image](https://user-images.githubusercontent.com/2223916/128409432-d47aa6fd-007a-4bf8-8303-fa3c7d38c654.png)

![image](https://user-images.githubusercontent.com/2223916/128409463-2eb594c0-1ced-407c-8cc4-29715eca2f6d.png)

![image](https://user-images.githubusercontent.com/2223916/128409495-903a4893-ff6f-4157-b4e7-5166f5ce43a8.png)

### Slightly different text in the tooltip for a card from an official collection included in an unofficial dashboard

![image](https://user-images.githubusercontent.com/2223916/128409511-9a6696cf-6aa2-4072-b338-fe782eca96d7.png)

## The ribbon icon should be slightly larger in search suggestions and on saved questions detail view

20x24px here:

![image](https://user-images.githubusercontent.com/2223916/128409595-64cc9c0e-9c58-4772-9397-45ab8358315c.png)

14x16px here:

![image](https://user-images.githubusercontent.com/2223916/128409679-3f4a5413-c62f-47d6-90d9-339167afc81d.png)

## The hover state on the text here should be yellow, not blue

![image](https://user-images.githubusercontent.com/2223916/128409807-ebc9a10e-82c4-43a2-8268-43d10efbadf9.png)

**Comment by kulyk** [comment]
@metabase-bot run visual tests

**Comment by kulyk** [comment]
Going to split that into a series of PRs and link them here

- [x] add the ribbon icon to the permissions page (already done by @alxnddr in the feature branch)
- [ ] change how official collections look on the homepage
- [ ] fix collections sidebar icons vertical alignment
- [ ] update collection type input
- [ ] add "Official collection" tooltips
- [ ] fix official collection icon sizes
- [ ] fix collection badge hover text color
