### ISSUE TITLE
Collections aren't correctly expanding and collapsing in the sidebar on master

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#17339]
A collection is supposed to expand in the sidebar when it's clicked, revealing all of its immediate subcollections, and then should collapse when clicked again. I'm seeing this on master and on our Stats instance.

## Current behavior

![no-expansion](https://user-images.githubusercontent.com/2223916/128426396-80014cd0-f2c1-41ff-9975-ea3ac057387c.gif)

## Expected (40.2)

![collapsable](https://user-images.githubusercontent.com/2223916/128426935-a8657c77-9307-4041-a3f9-029e4ce2b7ab.gif)

**Comment by camsaul** [comment]
@gusaiani don't forget to add issues you close to a milestone

**Comment by gusaiani** [comment]
@camsaul Sure, thanks for the reminder. Done.

**Comment by diogormendes** [comment]
@gusaiani , this issue still happening on the Cypress. We can't close the Collection by only clicking on it.

https://user-images.githubusercontent.com/17742979/161972439-e756c741-d45a-4153-8081-0e94d4b58e81.mov

**Comment by kulyk** [comment]
@diogormendes this is caused by changes in the new navigation. At the moment, the first click on a collection will just make it open the collection page, but the second click on an open collection will collapse it in the sidebar. Is this unexpected behavior?

**Comment by diogormendes** [comment]
Not sure @kulyk , used the Cypress Tests and @mazameli video as reference.

**Comment by nemanjaglumac** [comment]
@mazameli can you please take a look at [Anton's comment](https://github.com/metabase/metabase/issues/17339#issuecomment-1090206251) and solve this dilemma? I'd say this is a regression.

**Comment by nemanjaglumac** [comment]
@mazameli thanks for the prompt response.

I'm still seeing the differences from what you originally posted and how it works now. Please take a look at this video:
https://www.loom.com/share/c8b609f59f744df0a9eb9ca32d623fcd

Compare it to your second GIF in the description.

Keep an eye on what happened back in 40.2 when you clicked on "Good" collection name coming from a different collection. It collapsed. That doesn't happen anymore.
