### ISSUE TITLE
I should see the name of a question's verifier in the sidebar

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#17331]
In this context, as a non-admin, I expected to see the name of the verifier, e.g. `Maz A. verified this`

![image](https://user-images.githubusercontent.com/2223916/128396192-8c9eab74-7b96-4e7a-8897-26ad5c546f41.png)

**Comment by daltojohnso** [comment]
I'm seeing the moderator name now -- can you verify that this is fixed, @mazameli?
