### ISSUE TITLE
Can't add user: Input to create-and-invite-user! does not match schema

### ISSUE THREAD

**Issue by EnilPajic** [metabase/metabase#17373]
**Describe the bug**
Hello, I'm trying to create a new user on my metabase instance. I've "inherited" it from my previous coworker.
The setup fails with 
```xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>500 Server Error</title> </head><body> <h1>Server Error</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator, <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="7604191902361a1915171a1e190502">[email&#160;protected]</a> and inform them of the time the error occurred, and anything you might have done that may have caused the error.</p> <p>More information about this error may be available in the server error log.</p> <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script></body></html>
```

(see screenshot bellow)

The logs show this 

```closure
{:value [{:first_name "ABC", :last_name "CDE", :email "abc@company.com", :password "T_R9j85cJAkTbU"} {:email #object[org.postgresql.util.PGobject 0x404e6408 "enil.pajic@company.com"], :ldap_auth false, :first_name "Enil", :last_login #inst "2021-08-09T09:49:27.610000000-00:00", :is_active true, :is_qbnewb false, :updated_at #inst "2021-08-09T09:49:27.610000000-00:00", :is_superuser true, :login_attributes nil, :id 8, :last_name "Pajić", :date_joined #inst "2019-05-13T10:09:24.244000000-00:00", :common_name "Enil Pajić", :google_auth false}], 
:error [nil (named {:email (not (instance? java.lang.String a-org.postgresql.util.PGobject))} invitor)], 
:message "Input to create-and-invite-user! does not match schema: \n\n\t [nil (named {:email (not (instance? java.lang.String a-org.postgresql.util.PGobject))} invitor)] \n\n", :type clojure.lang.ExceptionInfo, :stacktrace ("--> models.user$fn__31924$create_and_invite_user_BANG___31929.invoke(user.clj:204)" "api.user$fn__63679$fn__63682.invoke(user.clj:101)" "api.user$fn__63679.invokeStatic(user.clj:100)" "api.user$fn__63679.invoke(user.clj:89)" "middleware.auth$enforce_authentication$fn__64059.invoke(auth.clj:14)" "routes$fn__65209$fn__65210.doInvoke(routes.clj:56)" "middleware.exceptions$catch_uncaught_exceptions$fn__64158.invoke(exceptions.clj:104)" "middleware.exceptions$catch_api_exceptions$fn__64155.invoke(exceptions.clj:92)" "middleware.log$log_api_call$fn__65583$fn__65584.invoke(log.clj:170)" "middleware.log$log_api_call$fn__65583.invoke(log.clj:164)" "middleware.security$add_security_headers$fn__64121.invoke(security.clj:128)" "middleware.json$wrap_json_body$fn__65288.invoke(json.clj:61)" "middleware.json$wrap_streamed_json_response$fn__65306.invoke(json.clj:97)" "middleware.session$bind_current_user$fn__62021$fn__62022.invoke(session.clj:193)" "middleware.session$do_with_current_user.invokeStatic(session.clj:176)" "middleware.session$do_with_current_user.invoke(session.clj:170)" "middleware.session$bind_current_user$fn__62021.invoke(session.clj:192)" "middleware.session$wrap_current_user_id$fn__62010.invoke(session.clj:161)" "middleware.session$wrap_session_id$fn__61995.invoke(session.clj:123)" "middleware.auth$wrap_api_key$fn__64067.invoke(auth.clj:27)" "middleware.misc$maybe_set_site_url$fn__65610.invoke(misc.clj:56)" "middleware.misc$bind_user_locale$fn__65613.invoke(misc.clj:72)" "middleware.misc$add_content_type$fn__65598.invoke(misc.clj:28)" "middleware.misc$disable_streaming_buffering$fn__65621.invoke(misc.clj:87)")}
```

It looked like CloudFlare is messing with email input (it shoud not, as I have another MB instance behind CF and this works fine). So I thought it is a rare case of CF malfunction, and I disabled [CloudFlare Email Obfuscation](https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-).

The returned HTML is different, but the log is same:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>500 Server Error</title> </head><body> <h1>Server Error</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator, webmaster@HOST and inform them of the time the error occurred, and anything you might have done that may have caused the error.</p> <p>More information about this error may be available in the server error log.</p> </body></html>
```

So, I avoided CloudFlare and all "layers" above metabase, and executed CURL directly at the server, the returned json is same as logs.

```curl

curl 'http://localhost:3000/api/user' \
-X 'POST' \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-H 'Cookie: metabase.SESSION=c8d761b7-d436-109f-b1a9-97991f9ca742' \
-H 'Content-Length: 92' \
-H 'Accept-Language: en-gb' \
-H 'User-Agent: MyUserAgent' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Connection: keep-alive' \
--data-binary '{"first_name":"ABC","last_name":"CDE","email":"abc@company.com","password":"FG0ceGYWbii3pg"}'
```

and response is:

```json
{
  "value": [
    {
      "first_name": "ABC",
      "last_name": "CDE",
      "email": "abc@company.com",
      "password": "FG0ceGYWbii3pg"
    },
    {
      "email": "enil.pajic@company.com",
      "ldap_auth": false,
      "first_name": "Enil",
      "last_login": "2021-08-09T10:25:53.185Z",
      "is_active": true,
      "is_qbnewb": false,
      "updated_at": "2021-08-09T10:25:53.185Z",
      "is_superuser": true,
      "login_attributes": null,
      "id": 8,
      "last_name": "Pajić",
      "date_joined": "2019-05-13T10:09:24.244Z",
      "common_name": "Enil Pajić",
      "google_auth": false
    }
  ],
  "error": [
    null,
    "schema.utils.NamedError@7e2bb25b"
  ],
  "message": "Input to create-and-invite-user! does not match schema: \n\n\t \u001B[0;33m  [nil (named {:email (not (instance? java.lang.String a-org.postgresql.util.PGobject))} invitor)] \u001B[0m \n\n",
  "type": "class clojure.lang.ExceptionInfo",
  "stacktrace": [
    "--> models.user$fn__31924$create_and_invite_user_BANG___31929.invoke(user.clj:204)",
    "api.user$fn__63679$fn__63682.invoke(user.clj:101)",
    "api.user$fn__63679.invokeStatic(user.clj:100)",
    "api.user$fn__63679.invoke(user.clj:89)",
    "middleware.auth$enforce_authentication$fn__64059.invoke(auth.clj:14)",
    "routes$fn__65209$fn__65210.doInvoke(routes.clj:56)",
    "middleware.exceptions$catch_uncaught_exceptions$fn__64158.invoke(exceptions.clj:104)",
    "middleware.exceptions$catch_api_exceptions$fn__64155.invoke(exceptions.clj:92)",
    "middleware.log$log_api_call$fn__65583$fn__65584.invoke(log.clj:170)",
    "middleware.log$log_api_call$fn__65583.invoke(log.clj:164)",
    "middleware.security$add_security_headers$fn__64121.invoke(security.clj:128)",
    "middleware.json$wrap_json_body$fn__65288.invoke(json.clj:61)",
    "middleware.json$wrap_streamed_json_response$fn__65306.invoke(json.clj:97)",
    "middleware.session$bind_current_user$fn__62021$fn__62022.invoke(session.clj:193)",
    "middleware.session$do_with_current_user.invokeStatic(session.clj:176)",
    "middleware.session$do_with_current_user.invoke(session.clj:170)",
    "middleware.session$bind_current_user$fn__62021.invoke(session.clj:192)",
    "middleware.session$wrap_current_user_id$fn__62010.invoke(session.clj:161)",
    "middleware.session$wrap_session_id$fn__61995.invoke(session.clj:123)",
    "middleware.auth$wrap_api_key$fn__64067.invoke(auth.clj:27)",
    "middleware.misc$maybe_set_site_url$fn__65610.invoke(misc.clj:56)",
    "middleware.misc$bind_user_locale$fn__65613.invoke(misc.clj:72)",
    "middleware.misc$add_content_type$fn__65598.invoke(misc.clj:28)",
    "middleware.misc$disable_streaming_buffering$fn__65621.invoke(misc.clj:87)"
  ]
}
```

**Logs**
Metabase logs: already posted above.

Console Logs:

```
[Error] Failed to load resource: the server responded with a status of 500 () (user, line 0)

[Error] Request entities,users,create failed: – {status: 500, data: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">…able↵in the server error log.</p>↵</body></html>↵", isCancelled: false}
{status: 500, data: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">…able↵in the server error log.</p>↵</body></html>↵", isCancelled: false}Object
	(anonymous function) (app-main.bundle.js:5:83743)
	c (vendor.bundle.js:1:777986)
	(anonymous function) (vendor.bundle.js:1:777778)
	r (app-main.bundle.js:5:79335)
	(anonymous function) (app-main.bundle.js:5:79455)
	promiseReactionJob


[Error] Form save failed
Object

data: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">↵<html><head>↵<title>500 Server Error</title>↵</head><body>↵<h1>Server Error</h1>↵<p>Th…"

isCancelled: false

status: 500

Object Prototype
	(anonymous function) (app-main.bundle.js:5:864402)
	c (vendor.bundle.js:1:777986)
	(anonymous function) (vendor.bundle.js:1:777778)
	r (app-main.bundle.js:5:864720)
	(anonymous function) (app-main.bundle.js:5:864840)
	promiseReactionJob
```

**To Reproduce**
1. Log in to your metabase instance as super admin
2. Click on gear icon in the top right corner
3. Click Admin. 
4. Click People
5. Click 'Add someone'
6. Fill data (first and last name, email)
7. Click 'Create'

Or execute cURL from above (with valid cookie!)

**Expected behavior**
To create and save user.

**Screenshots**
<img width="636" alt="image" src="https://user-images.githubusercontent.com/11429744/128691488-647d5376-b223-43bb-81ec-814e145e93f3.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15`
- Your operating system: `CentOS Linux release 7.8.2003 (Core)`
- Your databases: `PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit`
- Metabase version: `0.33.2`
- Metabase hosting environment: Dedicated server, run as JAR file
- Metabase internal database: `PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit` 

No, metabase internal database and 'warehouse' database are not the same database (not even on the same server), but they use same versions.

**Severity**
To be honest this is severe: I cannot add users to my metabase instance, and don't have any workaround to do it. I'll assume that direct manipulation of internal database is out of question.

**Additional context**

There are 28 users on metabase already, so it worked at some point in time.

**Comment by flamber** [comment]
Hi @EnilPajic 
The Cloudflare reverse-proxy has probably modified something at some point. Check your Metabase application database, specifically the table `core_user.email` to make sure that everything in there are actual emails.
Reverse-proxies can cause a lot of strange errors: https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html
And you should upgrade. You are using a version that is two years old - a lot has changed since: https://github.com/metabase/metabase/releases/latest

**Comment by EnilPajic** [comment]
Hi @flamber, thank you for quick response.

As I said in my post, add_user does not even work without cloudflare. I posted cURL request from same server, targeting `localhost:3000`, and same error happened ("Input to create-and-invite-user! does not match schema...").

So, in that case cause of trouble is not CF or any other reverse-proxy, because I targeted metabase directly. Same issue happens if I open an SSH tunel to metabase server, and use it via browser:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/11429744/128698205-813ab3d5-e07c-41e8-96e4-57e7716637d7.png">

Also, I checked `core_user` table (`select first_name, last_name, id, email from core_user;`), and everything is okay, emails included.

As for the "oldness", yes, you're correct. We've been using this metabase instance for over two years. Are there other solutions besides upgrade?

**Comment by flamber** [comment]
@EnilPajic Why is the email input disabled? Try using a different browser without any extensions. I would guess that the problem is not the user you're creating, but the user creating it (invitor), which somehow has become corrupted.
Make sure you have backups: https://www.metabase.com/docs/latest/operations-guide/upgrading-metabase.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by EnilPajic** [comment]
@flamber 

Email input is not disabled, that is the "effect" on mouse hover (Same effect on Safari and Firefox).
I tried different browsers, same error.



>  but the user creating it (invitor), which somehow has become corrupted.

I see what you mean. Thay may be the case. I'l ask another coworker (also superadmin) if they can create new users (now they are not working, night time)

Thank you for quick answers and links. 
Have a great day!
