### ISSUE TITLE
Make category filters a checkbox list

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#17383]
**This feature request is a proposal to see if there is traction on the idea**

**Is your feature request related to a problem? Please describe.**
In our Field Filters or other filters that are tied to category fields users find it hard to know which items are selected and which are  not (as selected items stay on the top, while non selected items are kept on the bottom), so a checkbox list approach might be a good option for this. Also this can have a "select all" button to ease the selection of multiple categories

**Describe the solution you'd like**
Replace current UI component on the filters to a checkbox list

**Describe alternatives you've considered**
None

**How important is this feature to you?**
This is just a proposal to see if the idea has any traction

**Additional context**
Change from
![image](https://user-images.githubusercontent.com/1711649/128773717-98e17dd7-3cac-4ba1-9e15-fdc7cdc0e4b8.png)
to
![image](https://user-images.githubusercontent.com/1711649/128773757-d711b514-9d88-4972-b8ae-366032abb483.png)

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/19467
