### ISSUE TITLE
Enable to unwind a MongoDB type/Array field directly in the editor or in column settings

### ISSUE THREAD

**Issue by urba1n** [metabase/metabase#17389]
**Is your feature request related to a problem? Please describe.**
When a MongoDB type/Array field needs to be unwind, you have to write a native query.

**Describe the solution you'd like**
Be able to unwind a type/Array field directly in the editor or in column settings.

**Describe alternatives you've considered**
Unwind type/Array fields by default.

**How important is this feature to you?**
Nice to have, but very useful for users who are not able to write native queries. 

**Additional context**
-

**Comment by flamber** [comment]
Duplicate of #2974
