### ISSUE TITLE
LDAP Group mapping removes the group

### ISSUE THREAD

**Issue by limousine69** [metabase/metabase#17410]
**Describe the bug**
We are using Okta for LDAP. The login is working but group mapping not. Two months ago we were using Azure AD and the group mappings worked.

We use ldapsearch for debugging and the distinguished names for mapping are correct. The following behaviour occurs:

1. Okta user is member of Group "COYO Internal".
2. ldapsearch shows "memberOf: cn=COYO Internal,ou=groups,dc=coyo,dc=okta,dc=com"
3. We mapped this dn to group "COYO Employee" in Metabase.
4. When logging in the user is still not a member of any group.
5. We add the user to Metabase Group "COYO Emloyee".
6. We add the user to Metabase Group "Dummy Test".
7. User logout
8. User login
9. The user is only member of "Dummy Test".

**Logs**
There is no error or log messages when signing in.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "de-DE",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.238-182.422.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-03",
      "tag": "v0.40.2",
      "branch": "release-x.40.x",
      "hash": "b884d29"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

**Severity**
We are facing a GDPR Audit and need to set this straight asap.

**Comment by limousine69** [comment]
Hey there,

thank you for your answer! Here are some screenshots of my Metabase configuration.
![Screenshot 2021-08-12 at 11 17 10](https://user-images.githubusercontent.com/88783547/129172244-4648b0b8-15a4-4681-8d80-8c6f4e7ceb43.png)
![Screenshot 2021-08-12 at 11 17 17](https://user-images.githubusercontent.com/88783547/129172269-b77ae9dd-5f21-4843-8f80-a7d2751f373c.png)
![Screenshot 2021-08-12 at 11 17 33](https://user-images.githubusercontent.com/88783547/129172278-62dbdaee-3b6c-47a7-bb83-d896395a69ee.png)


We use the LDAP interface by Okta. With ldapsearch the users look legit and are memberof the specified DNs.
![Screenshot 2021-08-12 at 11 23 55](https://user-images.githubusercontent.com/88783547/129173078-434c797e-a36d-4b43-b69b-777ccb848739.png)

But the actual behaviour is that the user doesn't get the groups assigned, but also removed if manually assigned.

**Comment by limousine69** [comment]
I just removed the group mapping for "cn=*" but no change.

The behaviour is still very weird and raise problems in our production environment. I try again:

User is member of "COYO Internal" in Okta.
User is member of "COYO Employee" in Metabase.
Group mapping is activated.
The User logs in.
The user gets removed from the group "COYO Employee".

**Comment by limousine69** [comment]
Also tried to set "Group Search DN" but that makes no difference. The users still get their assigned groups removed instead of added.

please note: the login only unassigns group matching the group mappings. other manually added groups are not removed.

**Comment by noahmoss** [comment]
Actually, @limousine69, by `Group Search DN` did you mean `Group Search Base`?

I see the behavior that you are describing when `Group Search Base` is not set. This makes sense, because the LDAP query is not able to find any groups associated with the user on the LDAP server. (Though we should make it clearer that `Group Search Base` is required).

When I set `Group Search Base` to the root DN on my server, the group mappings work as expected.

Could you double check that this field is being set to an appropriate value?

**Comment by luizarakaki** [comment]
There were several improvements on group mappings since this issue was opened.
If someone can reproduce this, we can open it again.
