### ISSUE TITLE
Conditional Formatting of Table only has 5 colors available and does not respect Whitelabel colors

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17431]
**Describe the bug**
Conditional Formatting of Table only has 5 colors available and does not respect Whitelabel colors.

**To Reproduce**
1. Admin > Settings > Whitelabel - change the default colors to something that matches your mood of the day
![image](https://user-images.githubusercontent.com/1447303/129198431-ae38649b-a64d-4558-93ec-f28231435708.png)
2. Simple question > Sample Dataset > Orders
3. Click Visualization > Table > Conditional Formatting > select Quantity and try to change the color - it will only show 5 options, but it's all the system defaults.
![image](https://user-images.githubusercontent.com/1447303/129198722-9d509062-94e4-47a8-90fa-125e5de37ef0.png)

**Expected behavior**
All 9-10 options that are available elsewhere - and respecting the Whitelabel defined colors - just like in other places:
![image](https://user-images.githubusercontent.com/1447303/129199340-413e8a10-a3c6-420f-b582-cab9c84cc030.png)

**Information about your Metabase Installation:**
Tested 1.37.8 thru 1.40.2 and 0.40.2

**Additional context**
Related #6300

**Comment by luizarakaki** [comment]
Couldn't repro on 46
