### ISSUE TITLE
"Minified React error #188" and other errors in Javascript console on X-Rays in sample database

### ISSUE THREAD

**Issue by depleater** [metabase/metabase#17430]
**Describe the bug**

Background: When trying to create chart visualisations on a test Metabase environment, I noticed sluggish and/or broken behaviour when interacting with a chart, followed by my browser becoming unresponsive… and I eventually had to kill the browser tab to recover.

After I started to investigate, I discovered a *lot* of errors in the Javascript console… and after some experimentation was able to confirm that they appeared on **any** page containing a graph visualisation.

Sometimes the side-effects were minor, sometimes more serious (e.g. the browser tab becoming unresponsive).

However, I'm making this specific bug report just about the Javascript errors that appear from a completely-vanilla Metabase standalone server run with "java -jar metabase.jar" with the sample dataset.

I suspect that once these Javascript errors are fixed, that's likely to fix the other problems. 🤣

The errors (summarised from attached log):

    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting scalar.field TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting scalar.field TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting graph.x_axis._is_timeseries TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting graph.x_axis._is_numeric TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting graph.x_axis._is_histogram TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting graph.x_axis.title_text TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting graph.y_axis.title_text TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.latitude_column TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.longitude_column TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.metric_column TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.pin_type TypeError: Cannot read property 'rows' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.latitude_column TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.longitude_column TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.metric_column TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.type TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.pin_type TypeError: Cannot read property 'rows' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting map.region TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting table.pivot_column TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting table.cell_column TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting table.columns TypeError: Cannot read property 'cols' of undefined
    app-main.bundle.js?d80c22a2f149aa2e8477:5 Error getting setting table._cell_background_getter TypeError: Cannot read property 'rows' of undefined
    vendor.bundle.js?d80c22a2f149aa2e8477:498 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    vendor.bundle.js?d80c22a2f149aa2e8477:498 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    vendor.bundle.js?d80c22a2f149aa2e8477:498 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    vendor.bundle.js?d80c22a2f149aa2e8477:498 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    vendor.bundle.js?d80c22a2f149aa2e8477:498 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Logs**

I've attached a full server log just for reference, but it doesn't appear to contain anything significant. I think this issue is strictly Javascript.

[metabase-server-log.txt](https://github.com/metabase/metabase/files/6975349/metabase-server-log.txt)

Javascript console log:

[metabase-javascript-console-errors--a-look-at-your-People-table.log.txt](https://github.com/metabase/metabase/files/6975199/metabase-javascript-console-errors--a-look-at-your-People-table.log.txt)

Also note the attached screenshot of the Javascript console in the Screenshots section.

**To Reproduce**

1. Download the .jar from https://downloads.metabase.com/v0.40.2/metabase.jar
2. Run with "java -jar metabase.jar"
3. Browse to http://localhost:3000
4. Go through the “Let's get started” signup stage.
5. Choose “I'll add my data later” to use the default sample data.
6. Open up and clear the browser's Javascript console.
7. Click on “A look at your People table”.
8. Behold the unholy flood of Javascript errors (see attached log in Logs, as well as a screenshot in Screenshots).

Note that similar (though not necessarily identical) errors appear for any page that includes a chart visualisation.

Alternative reproduction steps:

1. Choose “Ask a question”.
2. Select “Orders” from the sample dataset.
3. Open up and clear the browser's Javascript console.
4. Select “Visualisation”.
5. Select “Line”.
6. Behold the similar (albeit smaller) flood of Javascript errors.

**Expected behavior**

No errors in the Javascript console.

**Screenshots**

![metabase-javascript-console-errors--a-look-at-your-People-table](https://user-images.githubusercontent.com/1207416/129191735-dbf1c1f3-8c09-44c6-9b39-eb80fe2da356.png)

**Information about your Metabase Installation:**

```json

{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-Ubuntu-0ubuntu2.18.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-Ubuntu-0ubuntu2.18.04",
    "os.name": "Linux",
    "os.version": "4.15.0-126-generic",
    "user.language": "en",
    "user.timezone": "Australia/Melbourne"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-03",
      "tag": "v1.40.2",
      "branch": "release-x.40.x",
      "hash": "b884d29"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**

It was severe enough that I had to discount Metabase in a comparison evaluation between it and Superset and Redash.

As described above, my initial *functionality* issue was that, when trying to create visualisations from my own data, I couldn't interact with charts correctly - and in some cases my browser froze. (Note: that was on a different Linux system with only 8GB of RAM.)

**Additional context**

No other context.

**Comment by flamber** [comment]
Closing in favor of #16065. The warnings and errors are something that we're working on cleaning up, but it does not affect usage.
