### ISSUE TITLE
Dashboard cannot load using url but works when I load it from "collection"

### ISSUE THREAD

**Issue by SeaCedric** [metabase/metabase#17434]
Hello,
I have a strange issu : The dashboard I want consulted cannot be loaded by Safari (or Chrome) if I use url. But when I consult the dashboard passing by the collection it works.
The dashboard has many questions / graphs but it is not long to load.

I really have no idea what happens...

Concretely, the page loads on Metabase and in few seconds it becomes white screen without any Metabase controller.

It is not only on my computer but on all computers I tried !

- Browser and the version: (Safari Version 14.1.1 )
- Operating system: (OS X 11.14)
- Databases: (Postgres)
- Metabase version: (v0.39.2-SNAPSHOT)

This issu is blocking the entire team that depends on the dashboard for work.

**Comment by flamber** [comment]
Hi @SeaCedric You are using a custom build. Please try with a release.
