### ISSUE TITLE
Can't get multiple lines to graph from custom sql

### ISSUE THREAD

**Issue by timonv** [metabase/metabase#1744]
Is it possible to graph multiple lines from a more complex query?

I'm trying to get a simple graph going where it shows the revenue per client over time.

The sql I use for this is:

```sql
SELECT date_trunc('month', orders.created_at) as "Ordered at", email as "Client Account", sum(price) as Revenue
FROM orders
INNER JOIN client_accounts ON orders.client_account_id = client_accounts.id
WHERE orders.price > 0
GROUP BY date_trunc('month',orders.created_at), email
ORDER BY date_trunc('month', orders.created_at)
```

And I would like to see one line per client when hitting 'line'. However, there are no lines at all. Am I missing something? Or isn't this supposed to work?

Example data:
```csv
ordered at,client account,revenue
2013-07-01 00:00:00.0,a_client@company.com,80.77
```

**Comment by camsaul** [comment]
Your resulting data needs to look something like
```
ordered at, client_1_revenue, client_2_revenue, ...
2013-07-01, 80.77, 90.01, ...
2013-08-01, ...
```

Try playing around with this query to get a sense of how multiple lines work.
```postgres
SELECT generate_series, random() "foo", random() "bar"
FROM generate_series(1, 10, 1);
```
