### ISSUE TITLE
X-Ray does not wok for Oracle view containing space in Columns

### ISSUE THREAD

**Issue by shailendratripathi** [metabase/metabase#17463]
I have created Custom question and used sum function from Oracle View, but when i am clicking x-ray option on the bar chart its giving error "Can't create dashboard for number of Vw Cab Wise Cost"

![image](https://user-images.githubusercontent.com/13028444/129487978-35d12e60-4af0-4e62-b0af-0a18b6d6aaa9.png)

![image](https://user-images.githubusercontent.com/13028444/129488004-713b291e-5f8c-41f7-a486-2885308802a4.png)

![image](https://user-images.githubusercontent.com/13028444/129488027-b06cf8da-3b6f-4442-8457-fce241598afc.png)

**Comment by shailendratripathi** [comment]
please help me if anyone know the resolution of this issue

**Comment by flamber** [comment]
Hi @shailendratripathi 
Either use the forum forum for questions and troubleshooting: https://discourse.metabase.com/
Or create a bug report with all the proper details (including Oracle version and ojdbc8.jar version) and errors from Admin > Troubleshooting > Logs.

**Comment by shailendratripathi** [comment]
Hi @flamber,
I am not reporting any bug, i am asking for help, i dont know Oracle Views with space in column name is acceptable in x-ray of Custom Query or not, if some one knows that then that would be great help

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
