### ISSUE TITLE
Allow to make scatter plots with categorical feature for y axis

### ISSUE THREAD

**Issue by soheildsh** [metabase/metabase#17462]
Unfortunately when you want to use the metabase scatter plot for visualization it only accepts numerical data for y axis.

Suppose I want a 2-d plot which x and y axis are my two categorical features and the size of bubble for the number of occurrences.

It is a very common plot but metabase does not support it. You can choose your x axis from one of your categorical columns but y axis must be numerical which is not the case in most of scatter plot usage scenarios.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Can you provide an image or link to how this should look?
Think it would be fairly difficult to implement, since Metabase currently expects the Y-axis to be a numeric value for any chart.

**Comment by soheildsh** [comment]
![Screenshot from 2021-08-15 21-31-50](https://user-images.githubusercontent.com/58361549/129486472-d693fa0d-d884-4361-a91b-cebeb1b4b291.png)


Consider the above picture. Ignore the legend. I am trying to show the 2-d distribution of smokers and non-smokers separating them by gender, and the bubble sizes are number of occurances.

**Comment by flamber** [comment]
If your "smoker" column was an integer, then you could use remapping to get what you're after.
https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#remapping-column-values
Though, it seems like your example would fit better as another visualization.

**Comment by koe-n** [comment]
I have the same struggle with the scatter plot in Metabase. I would like to put a time series on both the x and y axis. 

One of my use cases is that I want to plot the date of the most recent activity of our users on x axis and the date of the first activity on the y axis. And would like to be able to group by week/month/etc.

**Comment by flamber** [comment]
Closing in favor of #11254
