### ISSUE TITLE
Dashboard subscription sidebar goes blank after editing dashboard a few times

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#17479]
**Describe the bug**
If you edit and save a dashboard a couple of times while having the dashboard subscription sidebar open, it will go blank when you click on a subscription.

**To Reproduce**
1. Create a dashboard and set up a subscription
2. Open the dashboard subscription sidebar 
3. Edit and then save the dashboard
4. Click on the subscription
5. Repeat steps 3 and 4 until bug appears

**Expected behavior**
Sidebar should not go blank

**Screenshots**

https://user-images.githubusercontent.com/32746338/129620821-e25b211a-44df-490e-954e-ff32976389ed.mov

**Information about your Metabase Installation:**
Current master

**Comment by flamber** [comment]
This seems to happen if `/api/pulse/form_input` somehow is delayed.
I'm having difficulties reproducing locally, but can reproduce on internal instance.
I think this might be a general problem also on release, so giving P2, since the only way to recover is by doing browser refresh.

**Comment by nemanjaglumac** [comment]
Unfortunately, cannot reproduce neither locally nor using Cypress.
