### ISSUE TITLE
Field Filter variable type cut off by Nav for SQL questions

### ISSUE THREAD

**Issue by zbayoff** [metabase/metabase#17490]
**Describe the bug**
Field filter Popover getting cutoff by nav for SQL questions.

**To Reproduce**
1. Go to 'Write SQL' page.
2. Beging adding a custom variable like `{{ s }}`, the Variables side bar should open. 
3. Change the Variable type to `Field Filter`. 
4. For Datasets with many Databases, this popover gets cut off by the nav. (to reproduce you can add a couple elements in the DOM, see screen video)

Updating the `z-index` of this Popover should solve this. 

**Expected behavior**
No cutoff. 

**Screenshots**

https://user-images.githubusercontent.com/30878344/129753875-46c013ba-7c4a-43d3-b29e-a99008fefe62.mp4

**Information about your Metabase Installation:**

Community Edition
`v0.40.2` 

**Severity**
This is a big issue for us as this bug prevents users from searching and viewing some tables for selection.

**Comment by flamber** [comment]
Hi @zbayoff 
The search has auto-focus, so you can start typing to search, but definitely a not-great experience.

It seems like a general frontend Popover issue, not just specific to SQL editor.

Can reproduce with the appdb on 1920x970 viewport
![image](https://user-images.githubusercontent.com/1447303/129868337-5a2e191a-8a7a-4336-b691-a542b73eca97.png)
![image](https://user-images.githubusercontent.com/1447303/129868509-a8f7263e-21d0-4c01-aff9-fcc92f77ea90.png)
