### ISSUE TITLE
Emoji in SQL question works but cannot be saved

### ISSUE THREAD

**Issue by pklreak** [metabase/metabase#17500]
**Describe the bug**

I'm running a question that is using CASE to convert the results to an emoji

```
SELECT 
CASE WHEN `survey`.`rating` = '1' then '👎'
ELSE '👍'
END AS "Rank", count(*) AS `Amount of users`
```

This works great:
![image](https://user-images.githubusercontent.com/78969224/129883404-a5473226-769f-4469-a414-c4dba0a9052d.png)

But when I try to save this question, I get this error: 
(conn=12) Incorrect string value: '\xF0\x9F\x91\x8D'\...' for column 'dataset_query' at row 1. 
Replacing the emojis with any other character works fine

**To Reproduce**
1. Create a new SQL question.
2. Create a CASE to replace any of the DB values with an emoji.
3. Run the code so see that it actually does that successfully.
4. Save the question.

**Expected behavior**
To save this question to be used as part of a dashboard.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.73",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.4.0-1102-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "mongo",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.35"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-03",
      "tag": "v0.40.2",
      "branch": "release-x.40.x",
      "hash": "b884d29"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
Not high, but I have a CSat survey that is literally 2 buttons - 👎 and 👍
Why would I present the results as anything other than an emoji?
Thanks.

**Comment by flamber** [comment]
Hi @pklreak 
I'm 99% sure that you are not using utf8mb4 charset and collation everywhere in the Metabase application database (MySQL 5.7.35)
Specifically `report_card.dataset_query`

**Comment by pklreak** [comment]
![image](https://user-images.githubusercontent.com/78969224/129898477-daee9c4d-d3e7-4953-a3eb-cb0f17cf5572.png)

**Comment by flamber** [comment]
Check the charset/collation (cannot be executed from Metabase editor):
```SQL
-- Set the database name to the Metabase metadata database - change it to match your db:
USE metabase;
-- Show system variables
SHOW VARIABLES WHERE Variable_name LIKE 'character_set_%' OR Variable_name LIKE 'collation%';
-- Show metadata database/tables/columns
SELECT TABLE_SCHEMA,
       TABLE_NAME,
       CCSA.CHARACTER_SET_NAME AS DEFAULT_CHAR_SET,
       COLUMN_NAME,
       COLUMN_TYPE,
       C.CHARACTER_SET_NAME,
       C.COLLATION_NAME
  FROM information_schema.TABLES AS T
  JOIN information_schema.COLUMNS AS C USING (TABLE_SCHEMA, TABLE_NAME)
  JOIN information_schema.COLLATION_CHARACTER_SET_APPLICABILITY AS CCSA
       ON (T.TABLE_COLLATION = CCSA.COLLATION_NAME)
 WHERE TABLE_SCHEMA=SCHEMA()
   AND C.DATA_TYPE IN ('enum', 'varchar', 'char', 'text', 'mediumtext', 'longtext')
 ORDER BY TABLE_SCHEMA,
          TABLE_NAME,
          COLUMN_NAME;
```

**Comment by pklreak** [comment]
![image](https://user-images.githubusercontent.com/78969224/129908900-e8cb7d9c-093f-4ae5-9b61-57e690b052a1.png)

and the 2nd one:

[tables.csv](https://github.com/metabase/metabase/files/7007684/tables.csv)

**Comment by flamber** [comment]
@pklreak Something has not been set as utf8mb4 initially, otherwise the qrtz-tables would not be just utf8.
I have just tried to setup 0.40.2 with MySQL 5.7.35 as application database, and I can run a query and save as question.
![image](https://user-images.githubusercontent.com/1447303/129918032-efdedb39-bdbe-4670-bb11-dcb27ea9e3aa.png)

It's definitely an encoding problem, but I cannot see where the problem is in your setup.
MySQL's way of handling charset and collation can be such a headache.

**Comment by flamber** [comment]
@pklreak Seems like the problem comes from your MySQL is defaulted to utf8 instead of utf8mb4.
https://stackoverflow.com/questions/47060827/jdbc-and-utf8mb4-encoding-the-emoji-symbol
Try including the following to the connection string `sessionVariables=character_set_server=utf8mb4` or actually just change the configuration on your MySQL database.

**Comment by camsaul** [comment]
@flamber should we include that connection string option for all MySQL application databases by default?

**Comment by flamber** [comment]
@camsaul It's the first time I have seen this problem (with the connection), but as long as it is possible to override, then it's probably okay. It's not the default MySQL configuration from what I can tell, so the OP must have manually changed to a non-recommended charset.
[Everybody else](https://github.com/metabase/metabase/issues?q=is%3Aissue+%22Incorrect+string+value%22+is%3Aclosed) has solved their problems by using `utf8mb4` charset and `utf8mb4_unicode_ci` collation for the database, as noted in the [docs](https://www.metabase.com/docs/latest/operations-guide/configuring-application-database.html#mysql-or-mariadb).
This was usually only a problem a couple of years ago.
