### ISSUE TITLE
Tables in "Browse data" is sorted by `name` instead of `display_name`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17513]
**Describe the bug**
Tables in "Browse data" is sorted by `name` instead of `display_name`

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Products > change table name to something different
2. Browse data > Sample Dataset - it's now in a slightly confusion order instead of alphabetically
![image](https://user-images.githubusercontent.com/1447303/130078448-f8784a97-f3a3-4e44-82d4-61db0a0eb729.png)

**Information about your Metabase Installation:**
Tested 0.40.2

**Comment by peterluba** [comment]
Would love this to be fixed! Our DB titles are super messy, so we've renamed them all in Metabase and it'd be great if they were in alphabetical order by the new name.

**Comment by rubiagatra** [comment]
I am happy to check out this one @flamber, I am a first-time contributor who can code in Clojure and JS, any recommendation to getting this started?

**Comment by flamber** [comment]
My first guess would be this: https://github.com/metabase/metabase/blob/master/src/metabase/api/database.clj#L721
