### ISSUE TITLE
Unable to launch "lein run"

### ISSUE THREAD

**Issue by gianluca-difranco** [metabase/metabase#17525]
I have compiled Metabase on Ubuntu WLS 18.04 without errors. When I try to launch "lein run", I see the following error:

`no :main namespace specified in project.clj`

I searched the file project.clj in the project but I didn't find it.

How can I solve this problem?

**Comment by flamber** [comment]
Hi @gianluca-difranco 
`lein` is not used anymore. Follow the documentation on master: https://github.com/metabase/metabase/blob/master/docs/developers-guide.md
Also worth reading: https://github.com/metabase/metabase/wiki/Migrating-from-Leiningen-to-tools.deps
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
