### ISSUE TITLE
One shouldn't have to scroll in order to click "Create a new dashboard"

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17562]
**Describe the issue**
For users that have many dashboards, the "Create a new dashboard" link/button is hidden at the bottom of a very long scroll. That happens after the question is saved and one is asked to add it to a dashboard. It is then possible to choose among already saved ones or to create a new one.

**To Reproduce**
1. Open any table from the Sample Dataset
2. Save that as a question
3. Modal will appear asking you whether to add that question to the dashboard - click yes
4. Given that the list of the existing dashboards is long, you will not see "Create a new dashboard" and will have to scroll all the way to the bottom in order to click it.

**Expected behavior**
It would be convenient to maybe keep this option "sticky" in some kind of footer in this dialog.

**Severity**
P3

**Additional context**
Talked to @mazameli about this today. There is no strong opinion/push from the product and the design re: this. Depending on the number of upvotes this issue gets, we might decide whether to act on it or not.

**Comment by brunobergher** [comment]
Solved by the new entity picker.
