### ISSUE TITLE
Propagate permissions toggle for currently selected permission

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#17573]
When collection permission is selected there is no convenient way to propagate it. Users have to select another permission, then switch back with the propagation toggle enabled.

Child collection has permission is "No access"
<img width="734" alt="Screen Shot 2021-08-24 at 12 11 01" src="https://user-images.githubusercontent.com/14301985/130590258-a45d00a8-42f6-493c-afe0-040528a25a37.png">

Parent collection has "Curate" permission
<img width="745" alt="Screen Shot 2021-08-24 at 12 11 10" src="https://user-images.githubusercontent.com/14301985/130590231-b6210997-bace-449e-9a59-e3ee5b9733fc.png">

"Curate collection" is not on the list.

**Comment by nemanjaglumac** [comment]
@alxnddr do you think this issue is still relevant after @NevRA 's fix https://github.com/metabase/metabase/pull/30426?

**Comment by alxnddr** [comment]
@nemanjaglumac I think the fix is not really what we need. The toggle should not trigger the instant change because it is a modifier of the change action if it is performed. Now it changes the permission graph right away on the toggle so users can't close the popover without applying the changes. 

I think we should've kept it as a modifier and just add the option to select the current permission with the ability to propagate it if users want it

**Comment by NevRA** [comment]
@alxnddr Let's discuss in person, maybe I'm missing something, but the behavior is the same as it was before, so users can close the popover without applying the changes.

**Comment by nemanjaglumac** [comment]
@alxnddr I am also confused.
Both @NevRA and I checked and you can definitely close the modal and/or cancel the changes without applying them.

**Comment by NevRA** [comment]
We misunderstood the context for using this feature. This is just a selection modifier in the popover by the original idea. Changing this behavior can break current cases. Therefore, in the [PR](https://github.com/metabase/metabase/pull/30531) we rolled back this behavior and made it possible to select the current option for this modifier to resolve the original issue.
And agree with @alxnddr we need a new UX for this feature

**Comment by alxnddr** [comment]
Although UX could be improved further, I believe https://github.com/metabase/metabase/pull/30531 fixed this issue because it works fine in the collections flat view as well as in the admin -> permissions view
