### ISSUE TITLE
Empty filter parameters in the URL causes weird filter state

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17578]
**Describe the bug**
When going to a SQL question with filters, but not defining values in the parameters, then the filters are applied in UI with blanks, while being auto-removed from the URL, and the query uses the blank values, which gives unexpected results and sometimes fails.

**To Reproduce**
1. Native query > Sample Dataset - variables should match filter type, and `category` and `created_at` are Field Filters to their respective columns - save the question.
![image](https://user-images.githubusercontent.com/1447303/130632784-3000f24a-9a0a-4c82-9f1e-46081269a8e7.png)
```
select *
from PRODUCTS
where true
[[and CATEGORY={{text}}]]
[[and RATING>{{number}}]]
[[and CREATED_AT::date<{{date}}]]
[[and {{category}}]]
[[and {{created_at}}]]
limit 1
```
2. If the question ID is `1`, then go to the following URL - note that this will create a failed query:
`/question/1?text=&number=&date=&category=&created_at=`
Going to an URL, which doesn't have the `number` or `created_at` will run the query, but with "No results!".
3. The filters gets marked as filled-out state, but the URL is now auto-corrected to the following:
`/question/1?category=`
![image](https://user-images.githubusercontent.com/1447303/130633363-f7d04424-e063-4b0b-ad61-f8c4467cea3a.png)

**Expected behavior**
If parameters are being auto-corrected in the URL, then they should not be applied to the filter state or the query.

**Information about your Metabase Installation:**
Tested 0.40.2 and master commit `b795f9f`

**Additional context**
Related to #13961 and #15498 and historically to #13960

**Comment by daltojohnso** [comment]
I'm not able to repro the "autocorrecting" portion of this. What URL are you starting from, @flamber?

**Comment by flamber** [comment]
@daltojohnso Create the question, then go to one of the following addresses:
`/question/1?text=&number=&date=&category=&created_at=`
or
`/question/1?text=&date=&category=`

**Comment by daltojohnso** [comment]
Looks like the autocorrecting behavior no longer happens on `master`, probably due to https://github.com/metabase/metabase/pull/17461 and maybe https://github.com/metabase/metabase/pull/17522

Can you verify on latest master?

**Comment by flamber** [comment]
It's still happening on master, but now the parameters are not being removed from the URL, but that's not the root problem.
Perhaps #17579 describes better what is being attempted and the problem it then causes.

Make a Click Behavior on a dashboard with Custom URL as target, and the URL should be something like this:
`/question/1/?category={{dashboard_filter}}`
Now if the dashboard filter is not defined, then URL sent is `/question/1/?category=`, but this causes this issue.

I have tried to simplify everything as much as possible, but I can send you the ticket if you want.
