### ISSUE TITLE
Change the color table with click behavior - version 0.40

### ISSUE THREAD

**Issue by maihmdr** [metabase/metabase#17584]
The latest version all the table was color black, but now when we have a column on-click behavior all the data in this columns presents in blue. Is any way to change that, without taking off the click behavior? 
Thanks 

before
![image](https://user-images.githubusercontent.com/89479749/130668371-2e60d56e-843e-475c-9be2-97713e35d4e3.png)

now 
![image](https://user-images.githubusercontent.com/89479749/130668486-8f93ba48-959e-4448-a5fd-e32c2295245a.png)

**Comment by flamber** [comment]
No, since it wasn't possible to see it was clickable before - #13548
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
