### ISSUE TITLE
Slow global search since 39

### ISSUE THREAD

**Issue by mothas** [metabase/metabase#17631]
**Describe the bug**
We are currently on v37.3 and we are looking to upgrade to v40.2. We have a dev metabase-instance with v40.2 running on it supported by psql server. The search on new v40.2 is really slow compared to v37.3.

When search is done, we see both Postgres and Metabase-app CPU going up significantly. There are only 1 or 2 users using v40.2 right now, as opposed to ~100 users on v37.3. So right now, our search on v40.2 is either very slow OR sometimes leads to Metabase-app crashing (refer log below). 

We have around 13,000 questions on our system. But more importantly, there are many **huge** questions - around 3000-4000 lines in each question. We suspect this is messing up with search performance. While v37.3 did NOT search for query text, v40.2 appears to search query text. 

Is there a way to improve search performance on v40.2 with these huge questions/queries? Or is there a way to configure Metabase such that to skip searching query text? Any help would be appreciated!

**Severity**
This problem is blocking our upgrade plans. If there's no easy solution, sticking to a version that does NOT search query text might be the only solution.

**Logs**

* Metabase server log

```
[9f5ebdda-f494-4d4e-bc07-836051b1fc24] 2021-08-26T22:19:28-07:00 DEBUG metabase.server.middleware.log GET /api/search 200 44.3 s (3 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (4 idle, 0 queued) (62 total active threads) Queries in flight: 0 (0 queued)
[9f5ebdda-f494-4d4e-bc07-836051b1fc24] 2021-08-26T22:20:18-07:00 WARN metabase.models.field Invalid Field :semantic_type :type/Number: falling back to null
[9f5ebdda-f494-4d4e-bc07-836051b1fc24] 2021-08-26T22:20:18-07:00 WARN metabase.models.field Invalid Field :semantic_type :type/Number: falling back to null
[9f5ebdda-f494-4d4e-bc07-836051b1fc24] 2021-08-26T22:23:07-07:00 DEBUG metabase.server.middleware.log GET /api/search 200 46.7 s (3 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (4 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
[6a05c20c-4481-4a08-9005-c9e271b2df60] 2021-08-26T22:27:15-07:00 INFO metabase.core 
Metabase v0.40.2 (b884d29 release-x.40.x) 

Copyright © 2021 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
[6a05c20c-4481-4a08-9005-c9e271b2df60] 2021-08-26T22:27:15-07:00 WARN metabase.core WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
[6a05c20c-4481-4a08-9005-c9e271b2df60] 2021-08-26T22:27:15-07:00 INFO metabase.core Starting Metabase in STANDALONE mode
```

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-us",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.238-182.422.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-03",
      "tag": "v0.40.2",
      "branch": "release-x.40.x",
      "hash": "b884d29"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Comment by anveo** [comment]
I believe I'm running into something similar with an upgrade from 0.39.1 -> 0.40.3.1. The load on the RDS Postgres database being queried went up significantly with almost no active users. RDS Insights show an increase in `buffer_io`. I will try and explore more but I've attached an image showing load during the upgrade and subsequent rollback.

![rds-metabase](https://user-images.githubusercontent.com/33536/131358547-308056ed-86e9-4043-84ef-5475d185d018.png)

**Comment by flamber** [comment]
@anveo You're seeing a different problem. Global search was introduced in 0.39.0.

**Comment by pawit-metabase** [comment]
This is regression from #14583.

There are 2 parts to this:
1) Postgres is doing a full table scan.
2) Metabase will always try to fetch 1000 results from the database and try to score the result in code. This can be slow if there are a lot of results returned with huge query texts.

The first part can be solved with Postgres's trigram extension ([ref](https://www.cybertec-postgresql.com/en/postgresql-more-performance-for-like-and-ilike-statements/)). The index must be created on all 3 searched columns (name, description, dataset_query) otherwise Postgres will fallback to full table scan. In addition, the generated query must be changed from `LOWER(column) LIKE '%search%'` to the Postgres-specific `column ILIKE '%search%'`.

However, since the solution is very Postgres specific and does not solve the issue for MySQL without another set of DB-specific implementations, we may want to consider an alternative solution - re-work search using a full text search system.

**Comment by pawit-metabase** [comment]
In the shorter term, we may be able to improve performance by limiting query search to, perhaps, the first 1000 characters of the query.

@mothas If you don't mind, can you share some statistics about the length of your queries using the below query?

```sql
SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY LENGTH(dataset_query)) AS median,
       percentile_cont(0.9) WITHIN GROUP (ORDER BY LENGTH(dataset_query)) AS p90,
       percentile_cont(0.99) WITHIN GROUP (ORDER BY LENGTH(dataset_query)) AS p99,
       MAX(LENGTH(dataset_query)) AS max
FROM report_card
WHERE query_type = 'native'
```

**Comment by mhkarimi1383** [comment]
Hi

We had lots of problems with metabase search (our data was fully okay)
so, we made https://github.com/basalam/Metabase-Search this will make your metabase search faster and more customizable (metabase internal search does not have any way to make it better)

**Comment by luizarakaki** [comment]
We know search is slow... We have plans to improve it but isn't a "bug"
