### ISSUE TITLE
Mixing bar and line graphs shows labels in wrong positions

### ISSUE THREAD

**Issue by StyvieK** [metabase/metabase#17634]
Using a query like the below:
```
select 'Group1' as "Group", 600 as "Plan" ,500  as "Actual", 65.6 as "Percent"
union all 
select 'Group2', 500, 500, 59.9 
```
Bar graph for "Plan" and "Actual", and selecting the "Percent" column to be a line - the data points are labeled correctly. 

![image](https://user-images.githubusercontent.com/2724634/131133406-a85a3709-5edb-4f6c-bddd-0c8611461493.png)

When the data only has 1 group though... the data point labels don't align with the bars at all.

Using this query to simulate.. 
```
select 'Group1' as "Group", 600 as "Plan" ,500  as "Actual", 65.6 as "Percent"
```
![image](https://user-images.githubusercontent.com/2724634/131133584-7a308cfa-0c4a-45e3-ac1f-da3a655245e4.png)

This only happens when the "Line" is mixed with the bar and there is 1 group. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/41395

<img width="930" alt="Image" src="https://github.com/user-attachments/assets/f3f4f011-7734-41e0-8d73-d2c743865c08" />
