### ISSUE TITLE
Relative date filter for "last week" only result in 6 days

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1763]
Today (1/20), when I use the following filters:

`past 7 days` I get a date range of 1/11 - 1/18. I would expect 1/12-1/19
`last week` I get a date range of 1/9-1/14. I would expect 1/10-1/16

**Comment by camsaul** [comment]
Why DB are you using? What timezone is it set to? What timezone is your MB instance set to use? Can you post the expanded query / korma form / generated SQL from the console? Can you look at the API results and try to whether if this is a timezone-related formatting issue on the frontend?

**Comment by salsakran** [comment]
This is all on stats using the sample DB.

**Comment by agilliland** [comment]
this is a dupe of #1635

**Comment by salsakran** [comment]
there's also the problem that "last week" is only using 6 days.

**Comment by agilliland** [comment]
got it.  lets rename this issue to represent that particular problem then.

the issue with the time being shifted back a day is covered by #1635 already.

**Comment by camsaul** [comment]
So what was the conclusion? Is there data for the 15th

**Comment by salsakran** [comment]
Nope. Think it's just the TZ issue. Closing.
