### ISSUE TITLE
Collections permissions page does not respond

### ISSUE THREAD

**Issue by flavienSindou** [metabase/metabase#17662]
**Describe the bug**
impossible to manage colllection permissions from admin panel .

**Logs**
Request URL: /api/collection/graph
Request Method: GET
Status Code: 500 
Resp : ERROR: relation "collection_revision" does not exist

**To Reproduce**
1. Revert from 0.40.0 to 0.39.4 because of  https://github.com/metabase/metabase/issues/16786
2. Go to /admin/permissions/collections
3. See error : page is not loading

**Expected behavior**
Supposed to have the ability to grant collections access to user group

**Severity**
This blocking your usage of Metabase entirely because I cannot grant needed access to my users.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.78",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.89+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.7 (Debian 10.7-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-06-15",
      "tag": "v0.39.4",
      "branch": "release-x.39.x",
      "hash": "f538050"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flavienSindou** [comment]
![image](https://user-images.githubusercontent.com/62057754/131311761-274f34a1-4a8a-4430-8ef6-e780b25b8166.png)

**Comment by flamber** [comment]
Without errors from the Metabase log, and/or the browser developer console, then it's impossible to know what is going on.
Latest release is 0.40.3.1: https://github.com/metabase/metabase/releases/latest

**Comment by flamber** [comment]
Metabase does not support downgrading. You have to revert to your backup from before you upgraded.
