### ISSUE TITLE
Table question in dashboard keeps resizing even when maximized

### ISSUE THREAD

**Issue by anton-epsagon** [metabase/metabase#17683]
**Describe the bug**
When displaying a table that is enough to reach the bottom of the screen, at some point it starts resizing the wrapper to add a scrollbar, then to remove the scrollbar and just keeps going on

**Logs**
¯\_(ツ)_/¯ got screenshots that could count as

**To Reproduce**
1. Create dashboard with one table question in it
2. Make sure the browser is windowed
3. Resize the browser from the bottom up
4. When reaching a point right before the table expected behavior is found

**Expected behavior**
A stable reactive layout

**Screenshots**
![image](https://user-images.githubusercontent.com/80029864/131473913-21884684-12cd-41dc-862c-fcf10c0ef056.png)
![image](https://user-images.githubusercontent.com/80029864/131473947-43689904-9d55-41e6-ada3-87b60c5399a6.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)
- Your operating system: Windows 10 Pro 20H2
- Your databases: Don't think this is relavent
- Metabase version: v0.39.4
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: H2

**Severity**
I wanna use Metabase in prod, and it ain't a good look (Though I'm sure I can find a workaround given some time)

**Comment by flamber** [comment]
The dashboard got a full revamp in 0.40.0, and got a specific fix for this problem in 0.40.3 #17229
https://github.com/metabase/metabase/releases/latest
