### ISSUE TITLE
Notebook: removing a section can also delete other sections if they have invalid MBQL

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#17712]
**Describe the bug**
Originally described in [this comment](https://github.com/metabase/metabase/pull/17633#issuecomment-908330423) from #17633. On the notebook editor, if there are two incomplete join sections (without table / any field / second field specified), once you remove one of them, the second is also removed.

The issue can be easily reproduced with joins, but most likely it can happen with any other notebook step.
It's just easier to make an "invalid MBQL" join.

**To Reproduce**
1. Ask a question > Custom Question > Sample Dataset > Orders
2. Join the Products table
3. Join the Reviews table
4. Remove only one field from the right side of the Products join section
5. Hover the Reviews join section and click the cross icon in the top-right
6. Both joins are removed

**Expected behavior**
Only the section user removes has to be removed.

**Demo**

https://user-images.githubusercontent.com/17258145/131664455-4e1dffaf-3980-42f5-aab7-95ea83437ddb.mov

**Information about your Metabase Installation:**

Metabase v0.41.0-SNAPSHOT

**Comment by flamber** [comment]
Related #14775, but in reverse
