### ISSUE TITLE
Relative filters in Native queries sometimes uses unnecessary casting

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17711]
**Describe the bug**
Continuation of #11502, but specific to Field Filters in Native questions.
When creating Native query with a Field Filter, then Metabase applies unnecessary casting to `DATE` columns, but also creates very different query syntax compared to GUI processed queries.

And will cause correctness issues like when filtering by Previous X **Hours**, since it's casting as date first.

**To Reproduce**
1. Native query > Sample Dataset - variable as Field Filter connected to Birthdate or Created_at.
   ```
   select count(*) from people where {{fieldfilter}}
   ```
2. Change filter widget to Previous `10000` days and run query:
![image](https://user-images.githubusercontent.com/1447303/131644346-4acd253a-d52e-48d9-97a9-2850e444c0c9.png)
3. The query generated by the Native question with the filter - it's casting the column and using `between`:
   ```
   select count(*) from people where CAST("PUBLIC"."PEOPLE"."BIRTH_DATE" AS date) BETWEEN date '1994-04-16' AND date '2021-08-31'
   ```
4. Doing the similar query via the GUI will generate a query without column casting (since 0.39.0+), but very different syntax:
   ```
   SELECT count(*) AS "count" FROM "PUBLIC"."PEOPLE" WHERE ("PUBLIC"."PEOPLE"."BIRTH_DATE" >= CAST(dateadd('day', CAST(-10000 AS long), now()) AS date) AND "PUBLIC"."PEOPLE"."BIRTH_DATE" < CAST(now() AS date))
   ```
   ![image](https://user-images.githubusercontent.com/1447303/131644985-91aa2f43-ee72-4e70-b1fa-ea8d291d6401.png)

**Information about your Metabase Installation:**
Tested 0.38.4 thru 0.40.3.1 and `master`

**Additional context**
Something makes me think that this could potentially be the cause of some timezone issues (depending on database types).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by caochangshan** [comment]
waiting

**Comment by caochangshan** [comment]
Is there a fix plan?

**Comment by caochangshan** [comment]
Mysql date field filter using date function which seriously affect the performance of sql query.
Any progress on this issue?

**Comment by Alan-66666** [comment]
@flamber  Still no progress on this issue?

**Comment by camsaul** [comment]
Fixed by #19384

**Comment by Alan-66666** [comment]
@camsaul @flamber  version 0.42 not been repaired
![image](https://user-images.githubusercontent.com/62995787/154187193-55c890f5-bacb-49cd-967b-61b10b49b0a2.png)

**Comment by flamber** [comment]
@Alan-66666 This is fixed in for `date` column types.
`select count(*) from PEOPLE where {{ff}}`
![image](https://user-images.githubusercontent.com/1447303/154276382-97e4842d-fbf2-4be4-a65a-e9f396c018d7.png)

0.41.6 generates:
```
select count(*) from PEOPLE where date(`PEOPLE`.`BIRTH_DATE`) BETWEEN '1994-10-01' AND '2022-02-15'
```
0.42.0 generates:
```
select count(*) from PEOPLE where `PEOPLE`.`BIRTH_DATE` BETWEEN '1994-10-01' AND '2022-02-15'
```

**Comment by Alan-66666** [comment]
> @Alan-66666`date`对于列类型，这是固定的。 `select count(*) from PEOPLE where {{ff}}` ![图片](https://user-images.githubusercontent.com/1447303/154276382-97e4842d-fbf2-4be4-a65a-e9f396c018d7.png)
> 
> 0.41.6 生成：
> 
> ```
> select count(*) from PEOPLE where date(`PEOPLE`.`BIRTH_DATE`) BETWEEN '1994-10-01' AND '2022-02-15'
> ```
> 
> 0.42.0 生成：
> 
> ```
> select count(*) from PEOPLE where `PEOPLE`.`BIRTH_DATE` BETWEEN '1994-10-01' AND '2022-02-15'
> ```

**Timestamp** type not fixed?

**Comment by Alan-66666** [comment]
**Timestamp** type not fixed?

**Comment by flamber** [comment]
@Alan-66666 What you have a timestamp, then it will apply casting, since you're only filtering by dates.

**Comment by sebslomski** [comment]
Still no fix for this issue? This broken :-(

**Comment by flamber** [comment]
@sebslomski This issue is closed and fixed in v42.
If you think you have problems, then open a new issue and include all the requested information.
Or use the forum for questions and troubleshooting: https://discourse.metabase.com/
