### ISSUE TITLE
Notebook: joins on multiple fields are removed if contain at least one incomplete condition

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#17710]
**Describe the bug**
Originally described in [this comment](https://github.com/metabase/metabase/pull/17633#issuecomment-908330423) from #17633. In notebook editor, if you have an incomplete join condition (e.g. you specified the left join field, but not the right one), once you click "Visualise" to run the query, the whole join gets removed. [It worked that way earlier](https://github.com/metabase/metabase/pull/17633#issuecomment-908527953), but with joins on multiple fields it became much easier to face the problem.

**To Reproduce**

1. Ask a question > Custom Question > Sample Dataset > Orders
2. Join the Products table, you should see Metabase automatically suggests joining on `PRODUCT_ID` FK
3. Click "Visualize", then open the notebook editor back (with an icon in the top right corner). You should see the join sections
4. Click the "+" icon on the right side of the join section. Two cells with "Pick a column..." labels should appear. Don't touch them or select only one of them.
5. Click "Visualize" again, open the notebook editor back. You can see the whole join section disappeared.

**Expected behavior**
The incomplete conditions should either stay on the UI, but not affect the query. Or only the incomplete conditions have to be removed.

**Demo**

https://user-images.githubusercontent.com/17258145/131648654-ae32b136-6adb-4be0-a739-a33472560016.mov

**Information about your Metabase Installation:**

Metabase v0.41.0-SNAPSHOT

**Comment by camsaul** [comment]
@kulyk should this be added to the 0.41.0 milestone?
