### ISSUE TITLE
Tooltips in admin permissions page are off-center 

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#17737]
**Describe the bug**
Minor, but the tooltips on the permissions page for the Administrators group seems to be computed relative to the table cell, which makes it off-center relative to the text.

**To Reproduce**
1. Go to Admin -> Permissions -> Administrators
2. Hover over the words "Unrestricted" or "Yes" in the table

**Expected behavior**
Tooltip should appear below the center of the text

**Screenshots**
<img width="845" alt="Screen Shot 2021-09-02 at 10 16 15 AM" src="https://user-images.githubusercontent.com/32746338/131889345-6a738e9b-77c1-467b-a864-0b5def716305.png">

**Information about your Metabase Installation:**
Current master

**Comment by nemanjaglumac** [comment]
They are actually not off-center. The container is wider than the text and the tooltip is exactly in the center of container.

![image](https://user-images.githubusercontent.com/31325167/131925804-90ea6827-c704-465d-be76-16c2d94c7ffb.png)

**Comment by noahmoss** [comment]
@nemanjaglumac Yeah, but the container isn't visible, so it looks off-center relative to the text.

It's not so bad for "Unrestricted", but it's weirder when you hover over "Yes" and the tooltip is totally floating to the right of the text.

**Comment by flamber** [comment]
Tooltips are now aligned with the icon
![image](https://user-images.githubusercontent.com/1447303/142175315-f45237f6-8e6d-418d-9e8a-c875e362f4b5.png)
