### ISSUE TITLE
"Native query editing" permission selector is inconsistent between "No self service" and "Block" permissions

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#17738]
When `Data access` permissions for a group is set to `No self service`, the `Native query editing` permission selector is set to `No` but grayed out. But when it's set to `Block`, the `Native query editing` selector is set to `No` but isn't grayed out, and you can change it to `Yes`, which changes the `Data access` permission selector back to `Unrestricted`.

Both these behaviors are valid but we should probably pick one and make it consistent.

 

https://user-images.githubusercontent.com/32746338/131891323-b853eb1f-d71e-48ac-a777-58d8dd2ee6a9.mov

**Comment by brunobergher** [comment]
Thanks for filing this, let's go with the grayed out behavior, please.

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/17757

**Comment by camsaul** [comment]
what milestone should this be added to?
