### ISSUE TITLE
Display icon beside account name in Admin Panel showing possible/recent login types

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#17732]
Metabase sometimes displays an icon in the Admin Panel showing how a person can log in (e.g., for Google Auth). It should display a similar icon (or icons) for other login types (e.g., LDAP, Metabase-hosted credentials, etc.). Since someone could in theory log in via both SAML and LDAP, this may need to be a multi-icon. This will help with troubleshooting when users are having difficulty logging in.

**Comment by flamber** [comment]
Related to #17616 and #11322

**Comment by mazameli** [comment]
Just to clarify in case a PM or designer is reading this, the icon on /admin/people currently shows how that user's account was created, not by which method they last logged in. @flamber identifies a different place where we could show what method they used to last sign in in issue #17616.

**Comment by ixipixi** [comment]
@mazameli I'm going to re-open this one (but let me know if you disagree). The context:

The other issue (https://github.com/metabase/metabase/issues/17616) gives a log in history and the most recent SSO method available - but it doesn't give admins an idea of the current auth methods _available_ to a user. From and audit and compliance perspective this may be necessary to know even if a user always chooses one auth method over another.
