### ISSUE TITLE
QB Tutorial doesn't work properly when sample dataset isn't present

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1774]
The QB Tutorial is dependent on having access to the sample dataset and the current code generates an error if it turns out there is no available Database of sample data.

**Comment by tlrobinson** [comment]
Options:

1. Hide the tutorial buttons when Sample Dataset is not present
2. Show an error prompting the user to re-add the Sample Dataset (or ask an admin to)
3. Soft-delete the Sample Dataset and only show it when running the tutorial (or if it hasn't been "deleted")

**Comment by agilliland** [comment]
@mazameli @salsakran care to weigh in?

my vote would be for option #1

**Comment by salsakran** [comment]
Ugh. 

I think 1 is the sanest approach at the moment, but I think we should explore further once 0.14 is out the door.

I'd add 
4. Inform the admin deleting the sample database that it is used for the query builder tutorial.

**Comment by mazameli** [comment]
Yeah, I think 1 + 4 might make sense for now. There might be some other small, nice things we could do to make the Sample Dataset less obtrusive, such as always showing it last in the list of databases.

**Comment by tlrobinson** [comment]
Ok, so hide the "How do I user this thing?" link, and I assume the 3rd panel of the onboarding? Or change the text to something else?

What sort of warning do we want when removing the Sample Dataset?

**Comment by mazameli** [comment]
* Yep, hide the link
* Yep, skip the 3rd onboarding panel
* The warning could be, "Just a heads up: without the Sample Dataset, the Query Builder tutorial won't work. You can always restore the Sample Dataset, though." [Okay / Cancel]
