### ISSUE TITLE
I can't set permission for user to database view

### ISSUE THREAD

**Issue by coralgol** [metabase/metabase#17744]
**Describe the bug**
Hello,
I have a view (not table but view) on database with a list of employees.
I have a query in metabase which has a variable mapped to this view (used to filter data for a particular employee)
Query works perfecty for administrators. For other users (which do not have access to all tables by default) - they do not see any employees on the list - so it seems that they do not have access to that database view. 
I go to Admin->Data Permissions->View Tables  -- but there are no views on the list (only tables) so I'm not able to grant access to that particular view.

**Logs**
n/a

**To Reproduce**
1. Create view in postgres database
2. go to Admin->Data Permissions->View Tables  
3. see if your view is on the list and you can grant permission to a user

**Expected behavior**
to be able to grant permissions for database views exactly the same like for tables

**Screenshots**
n/a

**Severity**
blocking some users

**Additional context**
n/a

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "pl-PL",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.15.0-136-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.8 (Ubuntu 11.8-1.pgdg18.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-13",
      "tag": "v0.37.6",
      "branch": "release-x.37.x",
      "hash": "344e5e0"
    },
    "settings": {
      "report-timezone": "Europe/Warsaw"
    }
  }
}
```

**Comment by flamber** [comment]
Upgrade you instance, latest release is 0.40.3.1: https://github.com/metabase/metabase/releases/latest
And read this article: https://www.metabase.com/docs/latest/troubleshooting-guide/cant-see-tables.html
