### ISSUE TITLE
Column deduplication too aggressive on fields with different granularity in nested queries

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17769]
**Describe the bug**
When using different granularity for the same timestamp column that is joined twice, then the results gets jumbled for those fields.

**To Reproduce** - *step 1 could have been two different questions, which is then joined, but just used one big for simplicity*
1. Custom question > Sample Dataset > Products, summarize Count, grouped by Category and CreatedAt:**Month of year**
Join Products on Category=Category, summarize Count and Sum of previous Count, grouped by previous Category, previous CreatedAt:**Month of year** and newly join CreatedAt:**Year**
![image](https://user-images.githubusercontent.com/1447303/132098497-df8b45cd-2f08-4fd3-97d5-6254cc0dcd0c.png)
2. Visualizing will show some incorrect granularity and header for the second CreatedAt column:
![image](https://user-images.githubusercontent.com/1447303/132098634-a91b3515-4251-4a98-9bca-a2a963f4ed42.png)
3. Add a Custom Column (`1 + 1`) to the end
![image](https://user-images.githubusercontent.com/1447303/132098750-8d21977b-ce50-4c8e-98b0-7e7198347cb0.png)
4. Now it has removed one of the CreatedAt column, the header is now from the second, while the results are from the first:
![image](https://user-images.githubusercontent.com/1447303/132098845-f67b16ec-843a-49d8-821e-9a6cb85c6448.png)

**Information about your Metabase Installation:**
Tested 0.39.4 thru 0.40.3.1 and master

**Additional context**
Could be a potential workaround for #4726

**Comment by metamben** [comment]
For the first example, the current version generates an invalid query (for PostgreSQL and H2):

```
SELECT "source"."category" AS "category",
       CAST(extract(month from "source"."created_at") AS integer) AS "created_at",
       date_trunc('year', "Products"."created_at") AS "Products__created_at",
       count(*) AS "count",
       sum("source"."count") AS "sum"
  FROM (SELECT "public"."products"."category" AS "category",
               CAST(extract(month from "public"."products"."created_at") AS integer) AS "created_at",
               count(*) AS "count"
          FROM "public"."products"
      GROUP BY "public"."products"."category",
               CAST(extract(month from "public"."products"."created_at") AS integer)
      ORDER BY "public"."products"."category" ASC,
               CAST(extract(month from "public"."products"."created_at") AS integer) ASC) "source"
LEFT JOIN "public"."products" "Products" ON "source"."category" = "Products"."category"
 GROUP BY "source"."category",
          CAST(extract(month from "source"."created_at") AS integer),
          date_trunc('year', "Products"."created_at")
 ORDER BY "source"."category" ASC,
          CAST(extract(month from "source"."created_at") AS integer) ASC
```

This tries to extract month from `"source"."created_at"` which is an integer. (In fact, it should just use `"source"."created_at"`.)

**Comment by metamben** [comment]
@flamber Can you still reproduce this bug? I tried using joins but that worked.

**Comment by luizarakaki** [comment]
Trying another path, it isn't possible to reproduce this bug. Likely fixed by mlibv2.

But there is another bug (the aggregation of month of year not working). I'll close this one and create another bug

**Comment by luizarakaki** [comment]
actually the bug was already reported https://github.com/metabase/metabase/issues/27735
