### ISSUE TITLE
Trying to set "Granular" permissions after "Block" is broken

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17763]
**Describe the bug**
Trying to set "Granular" permissions after "Block" leads to a table view that is greyed out.

**Logs**
N/A

**To Reproduce**
1. Go to `/admin/permissions/data/database/1` (Permissions page for "Sample Dataset")
2. For "All users" group set permission to Block and save
3. Now change permissions to "Granular"
4. It will take you to "All users" group tabular permissions page
5. Note that everything is greyed out and the default values for data permissions are set to "Block"
![image](https://user-images.githubusercontent.com/31325167/132068615-325978a5-9673-4316-93b7-451769cd557d.png)

Refreshing doesn't help.

The workaround is to click on the "Administrators" group in the left sidebar, and then to again click on the "All users" group. This time the page is editable, but it still displays "block".
![image](https://user-images.githubusercontent.com/31325167/132068708-932ac4b5-1df5-4cdc-a22e-1d2375412049.png)

**Expected behavior**
The page should be editable immediately and it probably makes more sense to default the sections to "no self-service".

**Screenshots**
Included above.

**Information about your Metabase Installation:**
local dev, `master, b4a41beef1cdf5e19d14799de4bab97e66dddaea, H2, sample dataset

**Severity**
Since there is a workaround, probably just P3. Would need to wait for an input from the product to figure out what the default permission level for granular tables should be.

**Comment by flamber** [comment]
Permissions are generally already difficult enough by themselves, so this can add a lot more confusion. Giving P2.

**Comment by nemanjaglumac** [comment]
@rlotun this was fixed in https://github.com/metabase/metabase/pull/17757 2 weeks ago and the repro was unskipped. Did you intentionally assign this to Cam for some additional BE work?

If not, we can close it.

**Comment by camsaul** [comment]
@nemanjaglumac I think is entirely an FE thing, Reza just assigned it to me because it was block-permissions-related.

Closing as fixed by #17757

**Comment by camsaul** [comment]
Fixed by #17757
