### ISSUE TITLE
authentication protocol behavior

### ISSUE THREAD

**Issue by bitBac** [metabase/metabase#17772]
**Describe the bug**
I has DigitalOcean database cluster and I can't connect to it.
 Password encryption in my db set to "Legacy – MySQL 5.x" from DO config panel.
 I can connect to my db from metabase server(from console).
 So, many time ago I connect to this db(DO not supported mysql_8 yet), but last time I am getting error in metabase charts "There was a problem displaying this chart." so, I tryed create new DB(connect with new user) but I can't do it due "Could not connect to address=(host=db-mysql-lon1-53957-fork-56102-do-user-8181350-0.b.db.ondigitalocean.com)(port=25060)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'"
 but I can connect with other app that required mysql_native_password, and Metabase syncs working well(any way information on charts is updated every day)
 
 
**Logs**
ON NEW DB ADDING
2021-09-06 06:28:01,513 DEBUG middleware.log :: POST /api/database 400 58.7 ms (0 DB calls) 
{:valid false,
 :dbname
 "Could not connect to address=(host=slave-prod-do-user--0.b.db.ondigitalocean.com)(port=25060)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'",
 :message
 "Could not connect to address=(host=slave-prod-do-user--0.b.db.ondigitalocean.com)(port=25060)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'"}

ON CHARTS LOADING
2021-09-06 06:34:26,685 DEBUG middleware.log :: POST /api/card/361/query 202 [ASYNC: completed] 22.8 s (7 DB calls) App DB connections: 0/15 Jetty threads: 2/50 (6 idle, 0 queued) (111 total active threads) Queries in flight: 5 (0 queued)
2021-09-06 06:34:26,821 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 33,
 :started_at #t "2021-09-06T06:34:03.901076Z[GMT]",
 :via
 [{:status :failed,
   :class java.sql.SQLNonTransientConnectionException,
   :error
   "Could not connect to address=(host=db-mysql-lon1-53957-fork--do-user-0.b.db.ondigitalocean.com)(port=25060)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'",
   :stacktrace
   ["org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)"
    "org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)"
    "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1372)"
    "org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)"
    "org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)"
    "org.mariadb.jdbc.Driver.connect(Driver.java:89)"
    "java.sql/java.sql.DriverManager.getConnection(Unknown Source)"
    "java.sql/java.sql.DriverManager.getConnection(Unknown Source)"
    "--> connection_pool$proxy_data_source$reify__34151.getConnection(connection_pool.clj:29)"],
   :state "08004"}
  {:status :failed,
   :class com.mchange.v2.resourcepool.CannotAcquireResourceException,
   :error "A ResourcePool could not acquire a resource from its primary factory or source.",
   :stacktrace
   ["com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1507)"
    "com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)"
    "com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)"
    "com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)"
    "com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)"
    "com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)"
    "--> driver.sql_jdbc.execute$fn__77344.invokeStatic(execute.clj:154)"
    "driver.sql_jdbc.execute$fn__77344.invoke(execute.clj:152)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:386)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:374)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:383)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:374)"
    "driver.sql_jdbc$fn__78967.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__78967.invoke(sql_jdbc.clj:52)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46313.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__45589.invoke(check_features.clj:41)"
    "query_processor.middleware.limit$limit$fn__46299.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__45240.invoke(cache.clj:211)"
    "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46478.invoke(optimize_datetime_filters.clj:133)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44386.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40767.invoke(wrap_value_literals.clj:147)"
    "query_processor.middleware.annotate$add_column_info$fn__40630.invoke(annotate.clj:582)"
    "query_processor.middleware.permissions$check_query_permissions$fn__45464.invoke(permissions.clj:69)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47001.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45662.invoke(cumulative_aggregations.clj:69)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47314.invoke(resolve_joined_fields.clj:94)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__47619.invoke(resolve_joins.clj:178)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__43976.invoke(add_implicit_joins.clj:181)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__46274.invoke(large_int_id.clj:44)"
    "query_processor.middleware.format_rows$format_rows$fn__46254.invoke(format_rows.clj:74)"
    "query_processor.middleware.desugar$desugar$fn__45728.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__44746.invoke(binning.clj:228)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45264.invoke(resolve_fields.clj:24)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__43606.invoke(add_dimension_projections.clj:316)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43837.invoke(add_implicit_clauses.clj:146)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48049.invoke(upgrade_field_literals.clj:45)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44133.invoke(add_source_metadata.clj:124)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47198.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44333.invoke(auto_bucket_datetimes.clj:139)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45311.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__46983.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45363.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__45984.invoke(expand_macros.clj:155)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44142.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47985.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47209$fn__47213.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47209.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46202.invoke(fetch_source_query.clj:264)"
    "query_processor.middleware.store$initialize_store$fn__47994$fn__47995.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47994.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__48056.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__46326.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__43994.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47970.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__45605.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__47072.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45548.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___37408$thunk__37409.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___37408$fn__37411.invoke(reducible.clj:108)"]}
  {:status :failed,
   :class java.sql.SQLException,
   :error "Connections could not be acquired from the underlying database!",
   :stacktrace
   ["com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)"
    "com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)"
    "com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)"
    "--> driver.sql_jdbc.execute$fn__77344.invokeStatic(execute.clj:154)"
    "driver.sql_jdbc.execute$fn__77344.invoke(execute.clj:152)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:386)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:374)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:383)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:374)"
    "driver.sql_jdbc$fn__78967.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__78967.invoke(sql_jdbc.clj:52)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46313.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__45589.invoke(check_features.clj:41)"
    "query_processor.middleware.limit$limit$fn__46299.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__45240.invoke(cache.clj:211)"
    "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46478.invoke(optimize_datetime_filters.clj:133)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44386.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40767.invoke(wrap_value_literals.clj:147)"
    "query_processor.middleware.annotate$add_column_info$fn__40630.invoke(annotate.clj:582)"
    "query_processor.middleware.permissions$check_query_permissions$fn__45464.invoke(permissions.clj:69)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47001.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45662.invoke(cumulative_aggregations.clj:69)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47314.invoke(resolve_joined_fields.clj:94)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__47619.invoke(resolve_joins.clj:178)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__43976.invoke(add_implicit_joins.clj:181)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__46274.invoke(large_int_id.clj:44)"
    "query_processor.middleware.format_rows$format_rows$fn__46254.invoke(format_rows.clj:74)"
    "query_processor.middleware.desugar$desugar$fn__45728.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__44746.invoke(binning.clj:228)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45264.invoke(resolve_fields.clj:24)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__43606.invoke(add_dimension_projections.clj:316)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43837.invoke(add_implicit_clauses.clj:146)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48049.invoke(upgrade_field_literals.clj:45)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44133.invoke(add_source_metadata.clj:124)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47198.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44333.invoke(auto_bucket_datetimes.clj:139)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45311.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__46983.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45363.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__45984.invoke(expand_macros.clj:155)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44142.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47985.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47209$fn__47213.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47209.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46202.invoke(fetch_source_query.clj:264)"
    "query_processor.middleware.store$initialize_store$fn__47994$fn__47995.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47994.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__48056.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__46326.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__43994.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47970.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__45605.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__47072.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45548.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___37408$thunk__37409.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___37408$fn__37411.invoke(reducible.clj:108)"],
   :state nil}],
 :state "08004",
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :database 33,
  :query {:source-table "card__361", :aggregation [[:cum-sum [:field-literal "expression" :type/Decimal]]], :breakout [[:datetime-field [:field-id 563] :day]]},
  :parameters [{:type "date/month-year", :target ["dimension" ["field-id" 563]], :value "2021-09"}],
  :async? true,
  :cache-ttl nil},
 :native
 {:query
  "SELECT date(`source`.`created_at`) AS `created_at`, sum(`source`.`expression`) AS `sum` FROM (SELECT [i am delete this part] ORDER BY date(`transactions`.`created_at`) ASC) `source` WHERE (`source`.`created_at` >= ? AND `source`.`created_at` < ?) GROUP BY date(`source`.`created_at`) ORDER BY date(`source`.`created_at`) ASC",
  :params (#t "2021-09-01T00:00Z[GMT]" #t "2021-10-01T00:00Z[GMT]")},
 :status :failed,
 :class java.sql.SQLException,
 :stacktrace
 ["org.mariadb.jdbc.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:52)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:727)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:546)"
  "org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1367)"
  "org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)"
  "org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)"
  "org.mariadb.jdbc.Driver.connect(Driver.java:89)"
  "java.sql/java.sql.DriverManager.getConnection(Unknown Source)"
  "java.sql/java.sql.DriverManager.getConnection(Unknown Source)"
  "--> connection_pool$proxy_data_source$reify__34151.getConnection(connection_pool.clj:29)"],
 :context :question,
 :error "Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :user-parameters [{:type :date/month-year, :target [:dimension [:field-id 563]], :value "2021-09"}],
  :info
  {:executed-by 1,
   :context :question,
   :card-id 362,
   :query-hash [-111, -128, 98, 12, -76, -127, 89, 13, -4, 17, -66, -44, -114, 2, -31, -113, -39, 118, 124, -66, 57, -101, 19, 31, -33, -41, -61, 24, 116, 9, -26, -119]},
  :database 33,
  :query
  {:aggregation [[:aggregation-options [:sum [:field-literal "expression" :type/Decimal]] {:name "sum"}]],
   :breakout [[:datetime-field [:field-id 563] :day]],
   :source-metadata
   [{:name "created_at",
     :display_name "Created At",
     :base_type :type/Date,
     :special_type :type/CreationTimestamp,
     :id 563,
     :field_ref [:datetime-field [:field-id 563] :day],
     :unit :day,
     :fingerprint {:global {:distinct-count 9705, :nil% 0.0}, :type {:type/DateTime {:earliest "2020-10-27T14:18:18Z", :latest "2021-01-23T12:45:34Z"}}}}
    {:name "sum-where",
     :display_name "Deposits",
     :base_type :type/Decimal,
     :special_type nil,
     :field_ref [:aggregation 0],
     :fingerprint {:global {:distinct-count 6, :nil% 0.0}, :type {:type/Number {:min 522.19, :q1 9114.26, :q3 16689.08, :max 18471.64, :sd 6695.5431485747795, :avg 12148.796666666667}}}}
    {:name "sum-where_2",
     :display_name "Withdrawns",
     :base_type :type/Decimal,
     :special_type nil,
     :field_ref [:aggregation 1],
     :fingerprint {:global {:distinct-count 6, :nil% 0.0}, :type {:type/Number {:min 0.0, :q1 3959.0, :q3 21116.31, :max 22302.51, :sd 9400.880403670712, :avg 10277.31}}}}
    {:name "expression",
     :display_name "Rough GGR",
     :base_type :type/Decimal,
     :special_type nil,
     :field_ref [:aggregation 2],
     :fingerprint {:global {:distinct-count 6, :nil% 0.0}, :type {:type/Number {:min -5809.29, :q1 -4427.23, :q3 7161.38, :max 8626.61, :sd 6080.89785107649, :avg 1871.4866666666667}}}}
    {:name "sum-where_3",
     :display_name "high roll Dep",
     :base_type :type/Decimal,
     :special_type nil,
     :field_ref [:aggregation 3],
     :fingerprint {:global {:distinct-count 5, :nil% 0.0}, :type {:type/Number {:min 0.0, :q1 771.3319427918517, :q3 4771.74, :max 9075.19, :sd 3391.853972988814, :avg 3388.7700000000004}}}}
    {:name "sum-where_4",
     :display_name "low 500 Dep",
     :base_type :type/Decimal,
     :special_type nil,
     :field_ref [:aggregation 4],
     :fingerprint {:global {:distinct-count 6, :nil% 0.0}, :type {:type/Number {:min 522.19, :q1 7418.03, :q3 13082.04, :max 13699.9, :sd 4751.249388940415, :avg 8760.026666666667}}}}],
   :filter
   [:and
    [:>= [:datetime-field [:field-id 563] :default] [:absolute-datetime #t "2021-09-01T00:00Z[GMT]" :default]]
    [:< [:datetime-field [:field-id 563] :default] [:absolute-datetime #t "2021-10-01T00:00Z[GMT]" :default]]],
   :order-by [[:asc [:datetime-field [:field-id 563] :day]]],
   :source-query
   {:source-table 86,
    :filter
    [:and
     [:or
      [:= [:field-id 559] [:value 0 {:base_type :type/Integer, :special_type :type/Category, :database_type "TINYINT", :name "type"}]]
      [:= [:field-id 559] [:value 1 {:base_type :type/Integer, :special_type :type/Category, :database_type "TINYINT", :name "type"}]]]
     [:= [:field-id 553] [:value 2 {:base_type :type/Boolean, :special_type :type/Number, :database_type "BIT", :name "status"}]]],
    :aggregation
    [[:aggregation-options
      [:sum-where [:field-id 560] [:= [:field-id 559] [:value 0 {:base_type :type/Integer, :special_type :type/Category, :database_type "TINYINT", :name "type"}]]]
      {:display-name "Deposits", :name "sum-where"}]
     [:aggregation-options
      [:sum-where [:field-id 560] [:= [:field-id 559] [:value 1 {:base_type :type/Integer, :special_type :type/Category, :database_type "TINYINT", :name "type"}]]]
      {:display-name "Withdrawns", :name "sum-where_2"}]
     [:aggregation-options
      [:-
       [:sum-where [:field-id 560] [:= [:field-id 559] [:value 0 {:base_type :type/Integer, :special_type :type/Category, :database_type "TINYINT", :name "type"}]]]
       [:sum-where [:field-id 560] [:= [:field-id 559] [:value 1 {:base_type :type/Integer, :special_type :type/Category, :database_type "TINYINT", :name "type"}]]]]
      {:display-name "Rough GGR", :name "expression"}]
     [:aggregation-options
      [:sum-where
       [:field-id 560]
       [:and
        [:> [:field-id 560] [:value 500 {:base_type :type/Decimal, :special_type nil, :database_type "DECIMAL", :name "in_eur"}]]
        [:= [:field-id 559] [:value 0 {:base_type :type/Integer, :special_type :type/Category, :database_type "TINYINT", :name "type"}]]]]
      {:display-name "high roll Dep", :name "sum-where_3"}]
     [:aggregation-options
      [:sum-where
       [:field-id 560]
       [:and
        [:<= [:field-id 560] [:value 500 {:base_type :type/Decimal, :special_type nil, :database_type "DECIMAL", :name "in_eur"}]]
        [:= [:field-id 559] [:value 0 {:base_type :type/Integer, :special_type :type/Category, :database_type "TINYINT", :name "type"}]]]]
      {:display-name "low 500 Dep", :name "sum-where_4"}]],
    :breakout [[:datetime-field [:field-id 563] :day]],
    :order-by [[:asc [:datetime-field [:field-id 563] :day]]]}},
  :async? true},
 :data {:rows [], :cols []}}

**To Reproduce**
1. buy db cluster on DO
2. try add new DB in Metabase
 
 

**Information about your Metabase Installation:**
don't know how to see current version so I just show you that I have latest version on 2021.09.06
sudo docker pull metabase/metabase:latest 
latest: Pulling from metabase/metabase
Digest: sha256:b7101874612ab806073cc22913caee818ccabc4ba380e3be7826ed3bd737eb8d
Status: Image is up to date for metabase/metabase:latest
docker.io/metabase/metabase:latest

 
**Additional context**
problem was fixed when i restar metabase, but i think it will return tommorow.

**Comment by flamber** [comment]
Hi @bitBac 
Create a new MySQL user (or alter the existing) to use the old authentication mode:
https://www.digitalocean.com/community/questions/change-auth-type-of-user-in-do-mysql-managed-database

**Comment by devurandom** [comment]
> Hi @bitBac Create a new MySQL user (or alter the existing) to use the old authentication mode: https://www.digitalocean.com/community/questions/change-auth-type-of-user-in-do-mysql-managed-database

I think he did that already:

> Password encryption in my db set to "Legacy – MySQL 5.x" from DO config panel.

I am hitting the same problem after upgrading to 0.41.0 using the official container images and [@pmint93's Helm chart](https://github.com/pmint93/helm-charts/tree/master/charts/metabase).

Using either "Legacy - MySQL 5.x" or "Default - MySQL 8.x" does not make much difference. Just the failing plugin type changes, always matching my selection in the DigitalOcean UI:
* Client does not support authentication protocol requested by server. plugin type was = 'mysql_native_password'
* Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'"

**Comment by flamber** [comment]
@devurandom So restarting Metabase solves the problem? Sounds like there's a problem with DO's managed database.
If you can consistently reproduce and with logs from both DO and Metabase, then please open a new issue with clear details, since it was quite difficult to understand this issue.
But again, if the problem is only with DO's managed database, then it sounds like it won't be something that we can fix.

**Comment by devurandom** [comment]
> @devurandom So restarting Metabase solves the problem? Sounds like there's a problem with DO's managed database. If you can consistently reproduce and with logs from both DO and Metabase, then please open a new issue with clear details, since it was quite difficult to understand this issue. But again, if the problem is only with DO's managed database, then it sounds like it won't be something that we can fix.

Thank you for your reply. I will open a new issue when/if this happens again. So far it only happened once, after upgrading from 0.41.0-rc1 to 0.41.0.
