### ISSUE TITLE
Metabase stuck after starting event listeners

### ISSUE THREAD

**Issue by vomba** [metabase/metabase#17784]
**Describe the bug**
Basically as the title says, i'm running metabase on a k8s cluster with gitops, it used to be running well, till recently after restarting it got stuck after launching event listeners

**Logs**
<html>
<body>

Warning: environ value jdk-11.0.11+9 for key :java-version has been overwritten with 11.0.11
--
Tue, Sep 7 2021 11:11:20 am | WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Tue, Sep 7 2021 11:11:24 am | 2021-09-07 10:11:24,591 INFO metabase.util :: Maximum memory available to JVM: 247.5 MB
Tue, Sep 7 2021 11:11:45 am | 2021-09-07 10:11:45,990 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
Tue, Sep 7 2021 11:11:45 am | For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
Tue, Sep 7 2021 11:12:02 am | 2021-09-07 10:12:02,045 INFO metabase.core ::
Tue, Sep 7 2021 11:12:02 am | Metabase v0.40.3.1 (0550b86 release-x.40.x)
Tue, Sep 7 2021 11:12:02 am |  
Tue, Sep 7 2021 11:12:02 am | Copyright © 2021 Metabase, Inc.
Tue, Sep 7 2021 11:12:02 am |  
Tue, Sep 7 2021 11:12:02 am | Metabase Enterprise Edition extensions are NOT PRESENT.
Tue, Sep 7 2021 11:12:02 am | 2021-09-07 10:12:02,077 WARN metabase.core :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
Tue, Sep 7 2021 11:12:02 am | 2021-09-07 10:12:02,083 INFO metabase.core :: Starting Metabase in STANDALONE mode
Tue, Sep 7 2021 11:12:02 am | 2021-09-07 10:12:02,248 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
Tue, Sep 7 2021 11:12:02 am | {:port 3000, :host "0.0.0.0"}
Tue, Sep 7 2021 11:12:02 am |  
Tue, Sep 7 2021 11:12:02 am | 2021-09-07 10:12:02,445 INFO metabase.core :: Starting Metabase version v0.40.3.1 (0550b86 release-x.40.x) ...
Tue, Sep 7 2021 11:12:02 am | 2021-09-07 10:12:02,603 INFO metabase.core :: System info:
Tue, Sep 7 2021 11:12:02 am | {"file.encoding" "UTF-8",
Tue, Sep 7 2021 11:12:02 am | "java.runtime.name" "OpenJDK Runtime Environment",
Tue, Sep 7 2021 11:12:02 am | "java.runtime.version" "11.0.11+9",
Tue, Sep 7 2021 11:12:02 am | "java.vendor" "AdoptOpenJDK",
Tue, Sep 7 2021 11:12:02 am | "java.vendor.url" "https://adoptopenjdk.net/",
Tue, Sep 7 2021 11:12:02 am | "java.version" "11.0.11",
Tue, Sep 7 2021 11:12:02 am | "java.vm.name" "OpenJDK 64-Bit Server VM",
Tue, Sep 7 2021 11:12:02 am | "java.vm.version" "11.0.11+9",
Tue, Sep 7 2021 11:12:02 am | "os.name" "Linux",
Tue, Sep 7 2021 11:12:02 am | "os.version" "4.15.0-136-generic",
Tue, Sep 7 2021 11:12:02 am | "user.language" "en",
Tue, Sep 7 2021 11:12:02 am | "user.timezone" "GMT"}
Tue, Sep 7 2021 11:12:02 am |  
Tue, Sep 7 2021 11:12:02 am | 2021-09-07 10:12:02,604 INFO metabase.plugins :: Loading plugins in /plugins...
Tue, Sep 7 2021 11:12:03 am | 2021-09-07 10:12:03,250 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,369 INFO util.files :: Extract file /modules/bigquery.metabase-driver.jar -> /plugins/bigquery.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,399 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,424 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,469 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,476 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,494 INFO util.files :: Extract file /modules/presto.metabase-driver.jar -> /plugins/presto.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,499 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,507 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,596 INFO util.files :: Extract file /modules/google.metabase-driver.jar -> /plugins/google.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,613 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,619 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar
Tue, Sep 7 2021 11:12:04 am | 2021-09-07 10:12:04,957 INFO util.files :: Extract file /modules/googleanalytics.metabase-driver.jar -> /plugins/googleanalytics.metabase-driver.jar
Tue, Sep 7 2021 11:12:05 am | 2021-09-07 10:12:05,461 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
Tue, Sep 7 2021 11:12:05 am | 2021-09-07 10:12:05,479 INFO driver.impl :: Registered driver :mongo 🚚
Tue, Sep 7 2021 11:12:05 am | 2021-09-07 10:12:05,498 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
Tue, Sep 7 2021 11:12:05 am | 2021-09-07 10:12:05,860 INFO driver.impl :: Registered abstract driver :sql 🚚
Tue, Sep 7 2021 11:12:05 am | Load driver :sql took 374.5 ms
Tue, Sep 7 2021 11:12:05 am | 2021-09-07 10:12:05,895 INFO driver.impl :: Registered driver :presto (parents: [:sql]) 🚚
Tue, Sep 7 2021 11:12:05 am | 2021-09-07 10:12:05,938 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,332 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
Tue, Sep 7 2021 11:12:06 am | Load driver :sql-jdbc took 394.1 ms
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,354 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,360 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,366 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,374 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,380 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,383 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Google Analytics Driver"]
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,396 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,398 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,411 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,412 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,414 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Google Analytics Driver" "Metabase BigQuery Driver"]
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,461 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.
Tue, Sep 7 2021 11:12:06 am |  
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,477 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,485 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Google Analytics Driver" "Metabase BigQuery Driver" "Metabase Oracle Driver"]
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,528 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,530 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,531 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,532 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,555 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,577 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
Tue, Sep 7 2021 11:12:06 am | Load driver :postgres took 45.2 ms
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,607 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,658 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,662 INFO driver.impl :: Registered abstract driver :google 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,663 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,664 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,669 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase BigQuery Driver" "Metabase Google Analytics Driver"]
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,673 WARN plugins.lazy-loaded-driver :: Warning: plugin manifest for :bigquery does not include connection properties
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,674 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,678 INFO driver.impl :: Registered driver :bigquery (parents: [:sql :google]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,685 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,688 INFO driver.impl :: Registered driver :googleanalytics (parents: [:google]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,709 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,713 INFO driver.impl :: Registered driver :druid 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,738 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
Tue, Sep 7 2021 11:12:06 am |  
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,738 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,739 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"]
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,745 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,814 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,875 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
Tue, Sep 7 2021 11:12:06 am | 2021-09-07 10:12:06,882 INFO db.setup :: Verifying postgres Database Connection ...
Tue, Sep 7 2021 11:12:07 am | 2021-09-07 10:12:07,960 INFO db.setup :: Successfully verified PostgreSQL 11.6 (Debian 11.6-1.pgdg90+1) application database connection. ✅
Tue, Sep 7 2021 11:12:07 am | 2021-09-07 10:12:07,973 INFO db.setup :: Running Database Migrations...
Tue, Sep 7 2021 11:12:08 am | 2021-09-07 10:12:08,225 INFO db.setup :: Setting up Liquibase...
Tue, Sep 7 2021 11:12:08 am | 2021-09-07 10:12:08,442 INFO db.setup :: Liquibase is ready.
Tue, Sep 7 2021 11:12:08 am | 2021-09-07 10:12:08,442 INFO db.liquibase :: Checking if Database has unrun migrations...
Tue, Sep 7 2021 11:12:13 am | 2021-09-07 10:12:13,023 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
Tue, Sep 7 2021 11:12:13 am | 2021-09-07 10:12:13,065 INFO db.liquibase :: Migration lock is cleared. Running migrations...
Tue, Sep 7 2021 11:12:13 am | 2021-09-07 10:12:13,180 INFO db.setup :: Database Migrations Current ... ✅
Tue, Sep 7 2021 11:12:13 am | 2021-09-07 10:12:13,208 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
Tue, Sep 7 2021 11:12:13 am | 2021-09-07 10:12:13,431 INFO db.data-migrations :: Finished running data migrations.
Tue, Sep 7 2021 11:12:13 am | Database setup took 6.6 s
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,140 INFO metabase.events :: Starting events listener: :metabase.events.dependencies/Dependencies 👂
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,199 INFO metabase.events :: Starting events listener: :metabase.events.activity-feed/ActivityFeed 👂
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,232 INFO metabase.events :: Starting events listener: :metabase.events.metabot-lifecycle/MetaBotLifecycle 👂
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,233 INFO metabase.events :: Starting events listener: :metabase.events.last-login/LastLogin 👂
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,233 INFO metabase.events :: Starting events listener: :metabase.events.notifications/Notifications 👂
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,233 INFO metabase.events :: Starting events listener: :metabase.events.sync-database/Sync 👂
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,234 INFO metabase.events :: Starting events listener: :metabase.events.driver-notifications/DriverNotifications 👂
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,234 INFO metabase.events :: Starting events listener: :metabase.events.revision/Revisions 👂
Tue, Sep 7 2021 11:12:14 am | 2021-09-07 10:12:14,235 INFO metabase.events :: Starting events listener: :metabase.events.view-log/ViewLog 👂

</body>
</html>

**Expected behavior**
Application startup

**Screenshots**
![image](https://user-images.githubusercontent.com/26633077/132329520-7179cfcc-e076-4754-982c-66754956f587.png)

**Comment by flamber** [comment]
I'm guessing that there's now more items in the view log, compared to earlier, and because you are starting Metabase with a maximum of 247MB memory, then it's just too much for it to handle.
`Maximum memory available to JVM: 247.5 MB`
You should give Metabase at least 1GB.
Recommended reading: https://www.metabase.com/learn/administration/metabase-at-scale
