### ISSUE TITLE
How do I subscribe to emails in the dashboard and send them in the specified order？

### ISSUE THREAD

**Issue by PanHywel** [metabase/metabase#17798]
How do I subscribe to emails in the dashboard and send them in the specified order?

For example, I have issue 1, issue 2 and issue 3 in my dashboard and I want to send subscription emails in the order of issue 2, issue 1 and issue 3.

Now the result is not in order.

How do I do this please, thank you very much.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
