### ISSUE TITLE
Allow organizations to determine the start of their week

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1779]
Right now we use Sunday as the start of the week.

http://discourse.metabase.com/t/how-are-mysql-dates-queried-for-this-week-and-last-week/185/2 brings up a case where a company has Monday as the start of the week.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by thoughtgap** [comment]
+1 (Standard in Europe)

**Comment by maliayas** [comment]
:+1:

**Comment by camsaul** [comment]
Support-wise this is very difficult since [Postgres](http://www.postgresql.org/docs/8.1/static/functions-datetime.html) and most other databases we support hardcode Sunday as the first day of the week

**Comment by bnetter** [comment]
:+1:

**Comment by mfreminville** [comment]
:+1:

**Comment by moumny** [comment]
👍  As you can see here: https://en.wikipedia.org/wiki/Week#/media/File:First_Day_of_Week_World_Map.svg
The first day of the week is not Sunday for quite a big part of the population.

Would make sense to make configurable / use locale setting

**Comment by etlweather** [comment]
I would vote for *configurable* instead of *locale setting*. Some business have their own start of week which may be Monday or some other day, different than the standard locale.

**Comment by tlrobinson** [comment]
Related to #3449 #2517

**Comment by j-c-** [comment]
👍

**Comment by rodneykeeling** [comment]
👍

**Comment by MathiasDL** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by 5an1ty** [comment]
Hi @camsaul Added a thumbs up, the current situation is rather annoying for us as business is used to working with weeks that start on monday.

**Comment by atharvai** [comment]
I'm trying to resolve this. and have managed to make changes mentioned in comments from #2517 and  make this configurable. I'm new to clojure and nodejs development. is there any guidance on how I can test (other than lein test) this?

**Comment by atharvai** [comment]
examples:
in config: 
![image](https://cloud.githubusercontent.com/assets/14027470/26060740/dd07842e-397d-11e7-9468-900a4cc7f1ab.png)

Question (with en/default/current behaviour):
![image](https://cloud.githubusercontent.com/assets/14027470/26060793/03d4c274-397e-11e7-8e3f-73c81f54c0e3.png)

Question (with en_gb):
![image](https://cloud.githubusercontent.com/assets/14027470/26060757/f0f446de-397d-11e7-8d63-25420cd6ad41.png)


Before I raise a PR, is this something that's what you are all looking for? This implementation is at least enough for our organisation. assuming I haven't broken anything else or missed anything.

**Comment by 5an1ty** [comment]
@atharvai Does the locale impact anything else? Locale is something that a lot of people also link to number formatting etc.

I would prefer the setting to just be:
First day of week (Sunday, Monday).

Other than that the change looks great to me, it's exactly what we would like.

Hopefully this could be added quick as it's currently the only thing management is really complaining about.

**Comment by atharvai** [comment]
so the locale setting set's `moment.locale(<config value>)` in `formatting.js`. This is global. One thing, I'd like is to make locale consistent across all Metabase. 
Setting day and manually "calculating" just for dates in a specific place seems incorrect and potentially misleading. The current implementation is in an example. It does date add and subtract to force Sunday as first day of week. 

I do wonder if moment.js is used for formatting numbers, currency etc. But a good point. Any pointers would help. I'm new to Clojure and Nodejs so I'm still finding my way around the code. 

When internationalizing applications, it is expected a locale sets all the correct display formats. So a single setting to control all datetime formats would be preferred.

**Comment by atharvai** [comment]
Looks like they use [humanize-plus](https://www.npmjs.com/package/humanize-plus) node module for number formatting. 

I think these are included in moments by default: https://github.com/moment/moment/tree/master/locale 
here's the `ja` (japanese) locale:
![image](https://cloud.githubusercontent.com/assets/14027470/26063147/0672ab52-3985-11e7-8a11-eba9513d773d.png)

One thing to be mindful of is the language is still English so other than the symbols defined in locale files, everything will be in English.

**Comment by mrtus** [comment]
Hi!

Is there any news on this? Is this feature already implemented/released

Or for when exactly is this planned for?

**Comment by mrtus** [comment]
@salsakran Hi! This proposal was made some time ago can you give us an update on this?

**Comment by atharvai** [comment]
I am no longer using Metabase and won't be maintaining any of my code changes. Please copy them to your fork.

**Comment by mokra** [comment]
Can someone please tell me how to change the week order at least hard coded?
I need to make it german - so Monday is the first weekday.

**Comment by lwqcz** [comment]
Hi, any progress regarding this issue? Yes, Sunday as first day in week is an issue for me and my company (most of wolrd is using Monday as first day in week anyway!). And another question - can you implement a mechanism to highlight work days to make them different at first glance? Thank you.

**Comment by luceklucek** [comment]
Hi, this issue is very urgent for us as well. When can you implement the feature of determining that the beginning of the week is Monday?

**Comment by jromero0621** [comment]
Hola, este problema es muy urgente para nosotros también. ¿Cuándo puede implementar la función de determinar que el comienzo de la semana es el lunes?

**Comment by jromero0621** [comment]
Sunday as first day in week is an issue for me and my company (most of company is using Monday as first day in week anyway!).

**Comment by jiremek** [comment]
This option doesn't exist since 0.3.0.
We need it each day....
Possible to schedule it ?

**Comment by wmorin** [comment]
It would be a great addition to Metabase! 👍

**Comment by helene-gloux** [comment]
Hi, it will be even more usefull now that you offer "Smart number" as a visualization type. 
Starting on sunday doesn't fit most of us... 

Would be great to have a schedule (like approximative one: We won't do it / OK, we will do it in 3 months or less / OK, we will do it later) :)

**Comment by CoconutTherapy** [comment]
Can only add my +1 on this. Monday is the standard first business day of the week as is meter for distance calculations.

This is quite mindblowing to go through steps like this:

`(date_trunc('week', CAST((CAST({the_date} AS timestamp) + INTERVAL '1 day') AS timestamp)) - INTERVAL '1 day')`

when all we want is:

`date_trunc('week', {the_date})`

**Comment by stevenleeg** [comment]
Are there any plans to implement this? It would be very helpful for my use case as well.

**Comment by pfeiffer** [comment]
This is really needed!

**Comment by Janepy** [comment]
Is there any update on this (determine start day of week) in the new version? Thanks!

**Comment by jacobr2009** [comment]
Any updates on this? This would be huge for us!

**Comment by jkramp** [comment]
Agreed. This is a must

**Comment by emilythacher** [comment]
Any updates? This would be really valuable for us

**Comment by libinvbabu** [comment]
It's been 3 months in P1. Any updates?

**Comment by lamourj** [comment]
Up, could we please merge this ?

**Comment by apinstein** [comment]
I noticed what I think is a related issue...

I have a dashboard with 2 charts on it, "by week". One of the by-weeks I did in sql with a simple `date_trunc('week', created_at)` and the other was done via the metabase query builder. I noticed that the two are not in agreement on data, and I think that they are off-by-one day. 

This is the sql generated by the metabase by-week:

`SELECT (date_trunc('week', CAST((CAST("source"."created_at" AS timestamp) + INTERVAL '1 day') AS timestamp)) - INTERVAL '1 day') AS "created_at" ...`

Why all of the crazy casting / transformation? Why not just use a simple `date_trunc`?

This query shows the difference between the two methods and does cause the two approaches "week windows" to be off by one day...

```
with d as (select TO_TIMESTAMP('2020-02-17', 'YYYY-MM-DD') as some_monday)
select
	date_trunc('week', some_monday) as date_trunc,
	(date_trunc('week', CAST((CAST(some_monday AS timestamp) + INTERVAL '1 day') AS timestamp)) - INTERVAL '1 day') AS "metabase"
from d

# output
date_trunc: 2020-02-17 00:00:00+00
metabase:   2020-02-16 00:00:00
```

**Comment by donyafoz** [comment]
any updates on this feature?

**Comment by tmaso-tiqueteo** [comment]
Hi all, this is a basic feature for many of locales.
It seems that was in P1 but since 5 months.

Do you have any updates on this feature.

Many thanks in advance,

**Comment by flamber** [comment]
There was an update on March 10th, where this got added to roadmap of 0.37. There's 45 other P1s.
I don't have a timeline for 0.37, but probably 2-3 months after 0.36

**Comment by mazameli** [comment]
We're changing the "Formatting" tab to "Localization" in 0.36, and I think this setting could fit in nicely there among the other date and time options:

![image](https://user-images.githubusercontent.com/2223916/85338203-ad12b580-b496-11ea-8cbe-004b90e0b2c1.png)

**Comment by adbrown101** [comment]
It looks like we can no-longer set locale to en_GB?

**Comment by flamber** [comment]
@adbrown101 Unless you have manually added a `en_GB` translation, then no. Metabase only includes `en_US` of the English-based languages. You can create and update translations here: https://poeditor.com/join/project/ynjQmwSsGh
But it sounds like a different question or problem, so please use the forum: https://discourse.metabase.com/

**Comment by raziel29a** [comment]
Just follow ISO 8601 and we're fine. If you think Sunday is the first day of the week you're just wrong. This is why we have standardisation.

**Comment by flamber** [comment]
This will be part of 0.37.0 - was fixed by PR #13090 - this is how it looks in Admin > Settings > Localization:
![image](https://user-images.githubusercontent.com/1447303/95382406-e5c18800-08e9-11eb-92d8-a95b7d7c899a.png)

**Comment by jacobr2009** [comment]
Woohoo!! Very excited for this!

Jacob Rasmussen

DATA ENGINEER

Cell 540.850.1321

**Comment by dpsutton** [comment]
@jacobr2009 heads up i edited your comment to remove your cell phone number from your signature.

**Comment by jacobr2009** [comment]
@dpsutton much appreciated 😊

**Comment by lubikx** [comment]
Tak od 0.37 bude umet metabase zmenit vychozi den tydne!!!

Akorat se to bude vztahovat jen na ty "klikaci" dotazy, tak pak muzeme
zkusit jak se to zmenilo, az ji vydaji.


Lubor Nosek
NETIUM s.r.o.
m: +420602356969
w: www.netium.cz  e: nosek@netium.cz
