### ISSUE TITLE
Grouping by "Day of week" behaves differently for some drivers depending on "First day of the week" setting

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17801]
**Describe the bug**
There is inconsistency with how "Day of week" is presented depending on the database type and which day Admin > Settings > Localization > "First day of the week" is set to.
Feels like a backend issue, but might be a frontend issue (or combined).

**To Reproduce**
Create a question summarized "Standard deviation of Quantity" grouped by "Created At: Day of week" for the different drivers.
1. "First day of the week" = **Sunday** - all databases matches and are shown correctly, example H2:
![image](https://user-images.githubusercontent.com/1447303/132491975-2a8f26bd-4559-4f86-93e3-08ae12756888.png)
2. "First day of the week" = **Monday**
   1. Postgres is still showing Sunday as starting
   ![image](https://user-images.githubusercontent.com/1447303/132493853-88d1c7b8-8f16-41f2-a7ca-08bda6a8032b.png)
   2. All the other drivers shows correctly, example H2:
   ![image](https://user-images.githubusercontent.com/1447303/132493209-6108bd31-bcc4-469e-a86f-d34e6057fd4c.png)
3. "First day of the week" = **Tuesday** (or changing to any other day in the week)
   1. MySQL, BigQuery and Snowflake makes a mess (and even worse if set to Saturday):
   ![image](https://user-images.githubusercontent.com/1447303/132494539-da660476-3501-4afe-90b3-64d6128c3f9a.png)
   2. H2 and Postgres shows correctly:
   ![image](https://user-images.githubusercontent.com/1447303/132494256-94ecd240-7c4f-45af-b8e7-1ca534a1ad84.png)

**Information about your Metabase Installation:**
Only tested 0.40.3.1, but I would guess this might have been present for a long time (likely since start of week was added)

**Additional context**
This might be a P2 and related to other issues like #8969 and #16114

**Comment by camsaul** [comment]
Hmm. Maybe it's just because the results are coming back in a different order
