### ISSUE TITLE
Joining behavior on datetime columns needs to be clearer

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#17826]
As seen in the demo day today, joining e.g. on `Orders.CreatedAt = Products.CreatedAt` actually evaluates the datetime columns at the month level of granularity, but this isn't clear or obvious at all. 

At minimum, we need to make this behavior explicit. A stretch or future goal is to allow for this granularity to be changed.

## Current behavior

This has evidently been a problem since at least 0.39 as you can see here:

![image](https://user-images.githubusercontent.com/2223916/132736085-c58080df-ee8a-4119-abdf-bdda5575a943.png)

That query above generates this SQL:

```
SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", 
"PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", 
"PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."DISCOUNT" AS 
"DISCOUNT", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY", 
"People"."NAME" AS "People__NAME", "People"."CREATED_AT" AS "People__CREATED_AT"
FROM "PUBLIC"."ORDERS" INNER JOIN "PUBLIC"."PEOPLE" "People" 
ON parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') =
parsedatetime(formatdatetime("People"."CREATED_AT", 'yyyyMM'), 'yyyyMM')
LIMIT 1048575
```

### At minimum, clarify the existing behavior

The minimum we can do is change the labels of datetime columns to show that the granularity is hardcoded to `Month`, like this:

![image](https://user-images.githubusercontent.com/2223916/132738684-236a4c4f-d4d2-4560-924a-3d8174bd68c5.png)

### Stretch / future: make the granularity modifiable

Let's reuse the granularity picker that we have e.g. for group-bys to allow for the granularity of datetime columns here to be selectable.

Whenever the granularity is changed for one datetime column in a join condition pair, **the granularity for the other column should be changed to match**.

![image](https://user-images.githubusercontent.com/2223916/132741374-0fa5301f-bf2b-49c1-af38-3d48c57a4dd8.png)

**Comment by flamber** [comment]
Same as #10924

**Comment by notrom** [comment]
Selectable granularity would be ideal. But the ability to do a straight join would also be hugely useful for me, no converting or "rounding" of dates, just `datetime1 = datetime2`.

If you need to be explicit I'd vastly prefer it to join on the day part of the datetime. That gives heaps more options for reporting than having the join on the Month part. If a granularity is being forced then as low as feasible gives the most flexibility.
