### ISSUE TITLE
Last edited relative time in saved question header shows incorrect time when user is not in same timezone as instance

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#17829]
**Describe the bug**
The relative time shown in a saved question header shows an inaccurate time if you aren't in the same tz as what's set for the instance. This also affects the times in the question history timeline.

**To Reproduce**
1. Create a question and save it
2. See that the relative time in the header of the page shows something like, "Edited a few seconds ago..."
3. Change your computer's timezone
4. Refresh the page
5. See the the relative time in the header is now offset (forward and backward) by a number of hours, depending on which tz you selected

**Expected behavior**
This relative time shouldn't be affected by the timezone you're in.

**Screenshots**
<img width="282" alt="Screen Shot 2021-08-19 at 12 16 49 PM" src="https://user-images.githubusercontent.com/13057258/132761902-a7602d66-4071-4051-84a9-eae0af3009fa.png">

**Information about your Metabase Installation:**
`master` HEAD at `18723639429c572e5749608b02c3ff9f6e9989ce`

**Severity**
P3?

**Additional context**
The value the FE uses is `card["last-edit-info"].timestamp`. The timestamp doesn't have a timezone. Adding one would fix this, I think. Example: `timestamp: "2021-09-09T14:07:52.285"`

**Comment by flamber** [comment]
Likely similar to #15635 and #14654

**Comment by ranquild** [comment]
I believe it's a backend bug since there is no timezone info in `last-edit-info`. There should be timezone information, and currently it's a date in the instance timezone.
