### ISSUE TITLE
Tooltips on bar charts in firefox

### ISSUE THREAD

**Issue by gseva** [metabase/metabase#1783]
I'm experiencing this problem in firefox:
<img width="684" alt="screen shot 2016-01-22 at 5 40 44 pm" src="https://cloud.githubusercontent.com/assets/2244417/12522421/57355712-c12f-11e5-8e71-66149f5a2ce9.png">
<img width="687" alt="screen shot 2016-01-22 at 5 40 39 pm" src="https://cloud.githubusercontent.com/assets/2244417/12522422/5737ae90-c12f-11e5-84ba-a7680714754c.png">

Tooltip is misplaced for bar charts. It keeps appearing in the same place when i move the widget. In chrome it works well.

**Comment by tlrobinson** [comment]
Possibly due to https://github.com/Caged/d3-tip/issues/56
