### ISSUE TITLE
I got error message: User does not have sufficient permissions for this account.

### ISSUE THREAD

**Issue by qqjameqq1** [metabase/metabase#17848]
When i connected google analytics. 
I got error message: User does not have sufficient permissions for this account.
what should i do?

![1631344672798](https://user-images.githubusercontent.com/23302246/132940008-8464a98a-c896-484f-b5ea-22f08c6ad65d.jpg)

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Try following this guide: https://github.com/metabase/metabase/blob/d88e4cc5914dcf4c8f9de367c523aa8971cd7cb5/docs/administration-guide/databases/google-analytics.md
