### ISSUE TITLE
Hide sections of the dashboard on full app embed

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#17884]
**Is your feature request related to a problem? Please describe.**
We have some customers that would like to embed dashboards that have the full Metabase functionality (drilling) but don't want to show the header (title, buttons), just the data.

**Describe the solution you'd like**
The possibility of hiding the header when embedding dashboards in full app embedding, similar to what we have in the signed embedding

**Describe alternatives you've considered**
None

**How important is this feature to you?**
This was a request from some leads

**Additional context**
We should have the same functionalities in all types of embeddings, but that's https://github.com/metabase/metabase/issues/9494

**Comment by rcronin** [comment]
We’re running into this need currently. I’m trying to leverage nginx right now to hide elements of the UI, such as: 

- save button when user changes filter

- Clicking breadcrumbs

- Adding new filters or columns

**Comment by paoliniluis** [comment]
Closing this one as it was included in v44. @rcronin if you need some help from us on this topic let us know :)
