### ISSUE TITLE
400 badMessage error from Jetty

### ISSUE THREAD

**Issue by danieljacobarcher** [metabase/metabase#1789]
Getting this error on a Docker install of Metabase, which is causing the load balancer in front of it to error.

[WARN ] org.eclipse.jetty.http.HttpParser :: badMessage: 400 No Host for HttpChannelOverHttp@52b8a3a7{r=0,c=false,a=IDLE,uri=-}

Is there an update to Jetty that can fix this within Metabase, or anyone else found this issue and fixed it?

**Comment by agilliland** [comment]
Hey @danieljacobarcher , so I haven't seen that particular error come up before when running Metabase, are you able to provide some more details from your logs?

It would also be helpful to get more information about your environment such as your Docker version and what OS you are running on.  And when you got this error was it right after launching Metabase on a new docker container?

For reference, I just launched a container on my MBP using Docker version 1.8.2 with VirtualBox and it came up without any issues.  I'm using this command `docker run -d -p 3000:3000 --name metabase metabase/metabase`

**Comment by danieljacobarcher** [comment]
Hey @agilliland, thanks for testing it out to see what's going on. We're using Docker version 1.9.1, installed on Ubuntu 14.04.3. It's deployed on DigitalOcean via Cloud66.

**Comment by danieljacobarcher** [comment]
@agilliland Any ideas what might be causing this?

**Comment by agilliland** [comment]
I tried out a few things here ... 1) I upgraded my docker version to 1.9.1 on my MBP and did some testing there but everything was working normally, and 2) I got setup on Cloud66 and DigitalOcean and tried deployment Metabase as a stack and everything went smoothly.

So there must be something about the configuration you're using when launching the stack or trying to access it that is triggering this error.  

This stackoverflow post seems the most relevant in explaining the underlying cause of the error http://stackoverflow.com/questions/26898691/jetty-badmessage-400-no-host-for-httpchanneloverhttp , so maybe your loadbalancer or some other network middleware in front of the Metabase Jetty server is stripping the `Host` header?  are you using an nginx reverse proxy in front of the docker container?

Regarding the settings for the Cloud66 stack, here's a quick screenshot of what I used that worked ...
<img width="848" alt="screen shot 2016-01-28 at 5 34 30 pm" src="https://cloud.githubusercontent.com/assets/1987787/12664560/7b85c998-c5e5-11e5-8646-8d8746e83b8c.png">

**Comment by danieljacobarcher** [comment]
Hey @agilliland! Thanks so much for looking more into that. Do you mind sharing your NGINX conf from your setup in C66?

**Comment by danieljacobarcher** [comment]
@agilliland Changed the HAproxy config and it is working now. The health check changed from http to tcp, so now it checks if the server is listening on port 80 it considers it as up.

this is what it used to be like:
--------------
backend www_backend_{{default_http_port}}
mode http
stats enable
stats auth {{ haproxy_username }}:{{ haproxy_password }}
balance {{ balance }}
option forwardfor
cookie LSW_WEB insert
option httpclose
option httpchk {{ httpchk }}
{% if maintenance_mode == true %}
http-check expect status 503
{% endif %}
{% for server in servers %}
server web{{ forloop.index }} {{ server.ext_ipv4 }}:{{default_http_port}} cookie "LSW_WEB{{ forloop.index }}" check
{% endfor %}
-------------------------------
and this is what it is now:
-------------------------------
backend www_backend_{{default_http_port}}
mode http
stats enable
stats auth {{ haproxy_username }}:{{ haproxy_password }}
balance {{ balance }}
option forwardfor
cookie LSW_WEB insert
option httpclose
**#option httpchk {{ httpchk }}**
**option tcp-check**
{% if maintenance_mode == true %}
http-check expect status 503
{% endif %}
{% for server in servers %}
**server web{{ forloop.index }} {{ server.ext_ipv4 }}:80**
**#server web{{ forloop.index }} {{ server.ext_ipv4 }}:{{default_http_port}} cookie "LSW_WEB{{ forloop.index }}" check**
{% endfor %}
-------------------------------

it would probably be better to find the good http check for this.
this line is the problamatic one:

**option httpchk {{ httpchk }}** which converts to:
**option httpchk HEAD / HTTP/1.0**

**Comment by agilliland** [comment]
Yeah, a tcp check is not ideal because it won't actually indicate if the app itself is running properly or not, just that the port is accepting connections.

We have a simple api endpoint that we use to test the health of the application over HTTP normally, so in AWS for example where we use ELB the health check url is configured as `/api/health`.  Try using that.

**Comment by danieljacobarcher** [comment]
Ok great thanks @agilliland.

**Comment by danieljacobarcher** [comment]
Here's the fix for Cloud66 (and maybe other deployment setups)...

In the Manifest.yml, put:
production:
  load_balancer:
    configuration:
      httpchk: HEAD /api/health HTTP/1.1\r\nHost:haproxy

**Comment by agilliland** [comment]
awesome.  thanks for sharing that @danieljacobarcher .  we can put some info about that in our documentation so others can benefit from it.
