### ISSUE TITLE
Visualizations are not always using whitelabel colors by default

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17904]
**Describe the bug**
Visualizations are not always using whitelabel colors by default

**To Reproduce**
1. Admin > Settings > Whitelabel
2. Change "Primary color" (do a browser refresh)
![image](https://user-images.githubusercontent.com/1447303/133474297-ddec6487-7fb8-480b-82bb-9abe1857d4ce.png)
3. Simple question > Sample Dataset > Products - summarize Count by Category - it's using the Metabase default blue
![image](https://user-images.githubusercontent.com/1447303/133474417-7527957f-d42c-40a4-b81a-6c8318b9e424.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/1447303/133474699-917321e8-7fef-42ba-8491-43dc60d1824f.png)

**Additional context**
Related to #17431
Originally EE155 https://github.com/metabase/metabase-enterprise/issues/155

**Comment by noahmoss** [comment]
This should also be fixed in subscriptions/alerts -- currently the static viz code just has a hard-coded list of colors. This part won't be fixed by #17903

**Comment by flamber** [comment]
@noahmoss Think that should be a separate issue.
