### ISSUE TITLE
Revision history does not update until page reload

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#17910]
**Describe the bug**
When you update a saved question, the change is not reflected in the History timeline because the cache of revision history entities is never cleared.

**To Reproduce**
1. Ask a Question > Simple Question > Sample Dataset > People
2. Save the People table as a new question
3. Click the name of the saved question ("People" by default) to open the details sidebar
4. Click on the "History" drawer to see the revision history of the question (since it is a new question, there should only be a single entry)
5. Add a description to the question and save
6. Note that a new entry is not added to the History timeline
7. Refresh the page and return to the History timeline to see a new entry noting the change in description

**Expected behavior**
A new revision history entry should be immediately visible and not require a refresh after editing a question or dashboard.

**Severity**
p3

⚠️ See https://github.com/metabase/metabase/pull/19466. An e2e test was adapted in that PR, and should be reverted once this issue is fixed.

**Comment by gusaiani** [comment]
Reopening.

See https://github.com/metabase/metabase/pull/19466
