### ISSUE TITLE
keep metabase DB (settings) on S3 bucket

### ISSUE THREAD

**Issue by vasyakrg** [metabase/metabase#17915]
i have pgsql instance with main db, but i don't want keep settings from metabase there.
and I don't want to run a separate instance in the Kubernetes cluster with pgsql service or keep the stafefullset with pvc (h2) on disk.

Is it possible to somehow store all the settings in the s3-bucket and whether it is implemented in the future?

**Comment by flamber** [comment]
Hi @vasyakrg 
I'm not entirely sure what you're asking, but the Metabase application database is used for a lot more than just settings.
It is where everything is stored. https://www.metabase.com/docs/latest/operations-guide/configuring-application-database.html
It is not possible to store that information in flat files.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
