### ISSUE TITLE
Removing dashboard filters shows a blank screen

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#17933]
**Describe the bug**
Removing dashboard filters shows a blank screen. Check the video below
https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
- Create a dashboard
- Add one filter and save
- Edit the dashboard and remove the filter

**Expected behavior**
Dashboard to appear without the filter that has just been deleted

**Information about your Metabase Installation:**
Latest `master`

<video src="https://user-images.githubusercontent.com/14301985/133661686-2fec8139-774c-422a-acaf-ae15963830d4.mov" />

**Comment by paoliniluis** [comment]
just did a few edits, great catch!
