### ISSUE TITLE
Screen goes blank after executing query for sometime

### ISSUE THREAD

**Issue by mrveera** [metabase/metabase#17939]
**Describe the bug**
When a user loads a dashboard after sometime screen turns blank 

**Logs**
index.js:108 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at extractRemappedColumns (index.js:108)
    at index.js:100
    at Array.map (<anonymous>)
    at extractRemappings (index.js:95)
    at Visualization.transform (Visualization.jsx:232)
    at Visualization.UNSAFE_componentWillReceiveProps (Visualization.jsx:175)
    at callComponentWillReceiveProps (react-dom.development.js:12976)
    at updateClassInstance (react-dom.development.js:13178)
    at updateClassComponent (react-dom.development.js:17107)
    at beginWork (react-dom.development.js:18620)
extractRemappedColumns @ index.js:108
(anonymous) @ index.js:100
extractRemappings @ index.js:95
transform @ Visualization.jsx:232
UNSAFE_componentWillReceiveProps @ Visualization.jsx:175
callComponentWillReceiveProps @ react-dom.development.js:12976
updateClassInstance @ react-dom.development.js:13178
updateClassComponent @ react-dom.development.js:17107
beginWork @ react-dom.development.js:18620
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
dispatch @ VM612:3856
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:15
dispatch @ applyMiddleware.js:35
_callee3$ @ redux.js:200
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
step @ redux.js:20
(anonymous) @ redux.js:20
Show 10 more frames
react_devtools_backend.js:4049 The above error occurred in the <Visualization> component:
    in Visualization (created by Visualization)
    in Visualization (created by Connect(Visualization))
    in Connect(Visualization) (created by WithVizSettingsData)
    in WithVizSettingsData (created by Connect(WithVizSettingsData))
    in Connect(WithVizSettingsData) (created by DashCard)
    in div (created by DashCard)
    in DashCard (created by GridItem)
    in div (created by GridItem)
    in Resizable (created by GridItem)
    in DraggableCore (created by GridItem)
    in GridItem (created by GridLayout)
    in div (created by GridLayout)
    in GridLayout (created by DashboardGrid)
    in div (created by DashboardGrid)
    in DashboardGrid (created by DashboardGrid)
    in DashboardGrid (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, App.
overrideMethod @ react_devtools_backend.js:4049
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
callback @ react-dom.development.js:20744
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19858
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
dispatch @ VM612:3856
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:15
dispatch @ applyMiddleware.js:35
_callee3$ @ redux.js:200
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
step @ redux.js:20
(anonymous) @ redux.js:20
Show 11 more frames
react_devtools_backend.js:4049 Warning: Setting defaultProps as an instance property on Parameters is not supported and will be ignored. Instead, define defaultProps as a static property on Parameters.
    in Parameters (created by Parameters)
    in Parameters (created by Dashboard)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider

**To Reproduce**
One of the hunch is that it is happening in the event of timeout
1.  Configure timeout 
2.  run a big query which can exceed timeout limit
3. wait for blank screen 

**Expected behavior**
A descriptive error message saying timeout of query happend

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

````json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.109+",
    "user.language": "en",
    "user.timezone": "Asia/Calcutta"
  },
  "metabase-info": {
    "databases": [
      "presto-user-auth",
      "mysql",
      "mongo",
      "postgres",
      "druid"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.34-google-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-13",
      "tag": "v0.39.6-SNAPSHOT",
      "branch": "?",
      "hash": "59acd40"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
````

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

Blocking all MB users and also lack of feedback in certain conditions making teams move away from MB to superset

**Comment by flamber** [comment]
Hi @mrveera 
You are running a custom build. Try using the latest release: https://github.com/metabase/metabase/releases/latest
I don't know which timeout you are referring to, or which database you are querying.
