### ISSUE TITLE
Unable to edit Admin>General Setting

### ISSUE THREAD

**Issue by maymekms** [metabase/metabase#17965]
Hello, 

I am using metabase 38.1. I found that I'm unable to edit General Setting at Admin page. I've no issue in 35.1.  I want to change site URL but it seems unable to auto save and cannot edit anything only at General setting. Anyone happened this issue before? Please kindly advise.

**Comment by flamber** [comment]
Latest release is 0.40.4: https://github.com/metabase/metabase/releases/latest
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
