### ISSUE TITLE
Notebook Join UI display wrong table name with multiple join (master)

### ISSUE THREAD

**Issue by pawit-metabase** [metabase/metabase#17968]
**Describe the bug**
The notebook query builder displays the wrong table name in the join UI

**Logs**
N/A

**To Reproduce**
1. Open Custom question
2. Select Order table
3. Join with Products table (leave default)
4. Join with Reviews table (Products.ID = Reviews.Product ID)

**Expected behavior**
The heading on the join dialog should display "Products" but instead it displays "Orders"

**Screenshots**
<img width="727" alt="Screen Shot 2564-09-20 at 16 55 00" src="https://user-images.githubusercontent.com/88995137/133984501-656fda81-975b-4cc7-a57d-5b1da33f9a7f.png">

**Information about your Metabase Installation:**
`master` (`4dc1ab826aa0f773028c1857b010535a870269d7`)

**Severity**
Can be confusing to the user

**Additional context**
N/A

**Comment by flamber** [comment]
Likely related to #12685 and #12930 even though this is new, since previous versions did not show the table name in the column.
