### ISSUE TITLE
"macOS Big Sur"-style icon

### ISSUE THREAD

**Issue by bennetfabian** [metabase/metabase#17962]
The app icon of Metabase on macOS should have a rework to fit in with all other apps aesthetically and to fit into Apple's icon guidelines.

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by flamber** [comment]
Closing, since we are deprecating the Mac App: https://www.metabase.com/blog/Metabase-0.41/#other-news-at-metabase
