### ISSUE TITLE
Breadcrumb path with multiple joined tables only has a single link to the first table

### ISSUE THREAD

**Issue by MarcSamD** [metabase/metabase#17961]
**Is your feature request related to a problem? Please describe.**
When joining 2 or more tables (or even another existing query), there is text on top of the page (see screenshot) that shows the  different data involved in the join, however the link only redirect to the first table of the list.

**Describe the solution you'd like**
It would be more convenient to have one different link for each underlying table/query.
Current link: [Orders + Products + People](https://www.metabase.com/question#Orders)
Expected link: [Orders](https://www.metabase.com/question#Orders) + [Products](https://www.metabase.com/question#Products) + [People](https://www.metabase.com/question#People)

**How important is this feature to you?**
Quite low but I guess the workload for this request is low too so it would be convenient to have.

**Additional context**
![image](https://user-images.githubusercontent.com/70358310/133871905-30d37632-edb9-4175-aeec-99c820035e73.png)

**Comment by flamber** [comment]
Very related to #12616
