### ISSUE TITLE
On master: new restricted domain list doesn't respect 'Send Now' button

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#17977]
**Describe the bug**
With the new restricted domains list, I can still send dashboard subscription emails using Send Now to an email address whose domain is not on the list.

**To Reproduce**
1. Add a user with an email outside of the domain you want to filter down to - e.g. a persona email address (through Admin)
2. Go to Admin -> General
2. Set a domain in the "Approved Domains for Notifications" box (e.g. metabase.com)
3. Go to a dashboard, click share, and click add an email notification and 'Send Now'.
4. See email sent to account where it shouldn't.

**Expected behavior**
It shouldn't sent, and should probably show an error saying 'Domain not allowed, contact administrator' or something to that effect.

This happens on the current master.

**Comment by jeff303** [comment]
Feature added in #17897.

**Comment by jeff303** [comment]
Added the backend change and test under #18121.

I'm not sure if we'll also want some additional frontend piece to explain what went wrong.  With this, the user will just see the button text temporarily change from _Send email now_ to _Sending failed_ (i.e. the current behavior if anything goes wrong with the test send, I suppose).

**Comment by camsaul** [comment]
Ok, not actually fixed yet. #18122 fixed this for Alerts but not for Dashboard Subscriptions -- this uses a different API endpoint
