### ISSUE TITLE
Possible to have multiple popovers open simultaneously

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1800]
My expectation is that only one popover should be able to be open at a time.

![screen shot 2016-01-25 at 4 56 02 pm](https://cloud.githubusercontent.com/assets/2223916/12569540/a36fac84-c384-11e5-8eb6-5a2bdba44873.png)

**Comment by tlrobinson** [comment]
I thought this used to work correctly.

It's not *quite* as simple as only allowing one popover, since there are a few places where you can have nested popovers, like the query builder sort picker and time granularity picker, but we should be able to handle that.
