### ISSUE TITLE
Close (X) icon for additional filter values looks misaligned

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1801]
Not sure if a design for this specific state (@kdoh?), but methinks the Xs should be centered vertically with the input field maybe 10–20px to the right.

![screen shot 2016-01-25 at 4 51 23 pm](https://cloud.githubusercontent.com/assets/2223916/12569571/0092f6e6-c385-11e5-932c-c4d9f2fa00a2.png)

**Comment by kdoh** [comment]
For reference, the original design was that it would appear on hover and look like this:
<img width="397" alt="screen shot 2016-01-25 at 5 03 10 pm" src="https://cloud.githubusercontent.com/assets/5248953/12569696/134f1f3e-c386-11e5-8578-74ed2e23a304.png">
