### ISSUE TITLE
Post aggregation drill-through by dragging/selecting a portion of a chart results in an error

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#18011]
**Describe the bug**
Post aggregation drill-through by dragging/selecting a portion of a chart results in an error.

**Logs**
```
error Cannot parse "TIMESTAMP" constant "2.7903339503978226"; SQL statement:
-- Metabase:: userID: 1 queryType: MBQL queryHash: 8f33b3fcfe81f4629d2ae1dd45eb6e6463e15bea997e5283df3f79f8602f9393
SELECT
  month("PUBLIC"."PRODUCTS"."CREATED_AT") AS "CREATED_AT",
  "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY",
  count(*) AS "count" FROM "PUBLIC"."PRODUCTS"
WHERE
  "PUBLIC"."PRODUCTS"."CREATED_AT"
BETWEEN 2.7903339503978226 AND 3.368985153673577
GROUP BY
  month("PUBLIC"."PRODUCTS"."CREATED_AT"), "PUBLIC"."PRODUCTS"."CATEGORY" ORDER BY 
  month("PUBLIC"."PRODUCTS"."CREATED_AT") ASC, "PUBLIC"."PRODUCTS"."CATEGORY" ASC [22007-197]
```

**To Reproduce**
1. Custom question > Sample Dataset > Products
2. Summarize Count grouped by CreatedAt:MonthOfYear (or any of the "X of Y") and Category - save as "Q1"
![image](https://user-images.githubusercontent.com/1447303/124751412-e3e32e80-df26-11eb-88d7-6db84075ed24.png)
![image](https://user-images.githubusercontent.com/1447303/124751432-eba2d300-df26-11eb-8c0b-174d31bd2fcd.png)
3. Click anywhere on the chart and drag/select a portion of it in order to 'drill-through'
4. It results in an error, and the filter shows "Created At between [Unknown] [Unknown]"
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/Apu9dBQ2/810e8666-3eda-4efc-a281-aaf1dd2ebcd9.gif?source=viewer&v=e852c01618d7f6d3b24d983337559cdb)

**Expected behavior**
Filter should be applied correctly.

**Information about your Metabase Installation:**
local dev, master, adc985e0b63cf87092b758fd916592719aedc2bb, H2, Sample Dataset

**Severity**
P2?

**Comment by flamber** [comment]
Related to #16981

**Comment by ranquild** [comment]
Requires MLv2

**Comment by shaunlebron** [comment]
Related: we can’t brush-zoom any accumulated time units: https://github.com/metabase/metabase/issues/32450

**Comment by uladzimirdev** [comment]
I unskiped repro test for this issue in https://github.com/metabase/metabase/pull/37293 and it's not failing.

**Comment by uladzimirdev** [comment]
I can't reproduce it on master 926b04a1d5 anymore 
<img width="1908" alt="image" src="https://github.com/metabase/metabase/assets/125459446/b2f5587a-953d-406b-aacd-e61fe8427624">

Moreover, I un-skipped a repro test in https://github.com/metabase/metabase/pull/37295
