### ISSUE TITLE
Send to Slack/Send email now buttons on dashboard subscriptions send the wrong dashboard

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#18019]
I'm not yet sure that this is reliably reproducible, but if it is, this could be very, very bad.

Here's what I did and what I experienced:

- I went to an existing dashboard, "Example KPIs dashboard", in our Stats instance
- I opened up the dashboard subscription sidebar and used both the Send to Slack and Send Email Now buttons to test out the subscriptions — I did **not** save the subscriptions.
- I saw the dashboard correctly appear in my Slack channel and my email inbox.
- I then created a _new_ dashboard, and added some questions to it. It's called "0.41 demo" and is in my personal collection on our Stats instance.
- On this new dashboard, I opened up the dashboard subscriptions sidebar and used the Send to Slack and Send Email Now buttons, again not saving the subscriptions.
- In both Slack and email, I incorrectly received the _first_ dashboard! 😱 

Here is what the _second_, new dashboard looks like:

![image](https://user-images.githubusercontent.com/2223916/134424742-1be9ad1a-acf4-465e-8aa9-25631be3476b.png)

Here is what I incorrectly received in Slack and email:

![image](https://user-images.githubusercontent.com/2223916/134425480-1bf469b0-6ad7-4c46-bdae-3d1c94083d02.png)

![image](https://user-images.githubusercontent.com/2223916/134424846-0fa312c3-dd8d-4e4b-96d3-01e4235415b2.png)

**Comment by mazameli** [comment]
Saving a new subscription on a dashboard and _then_ using the Send to Email Now button seems to resolve the issue, so this seems to be specifically an issue when the subscription hasn't been saved yet.

**Comment by mazameli** [comment]
I'm thinking this might be a related bug: somehow here in my personal account settings under the Notifications tab, it's showing that there's a slack subscription I have to `0.41 demo` (my second dashboard), but clicking on it takes me to that _first_ dashboard, `Example KPIs dashboard`

![subscription-management](https://user-images.githubusercontent.com/2223916/134435935-e2d5a92e-3959-4021-9caa-d3b8cf7492fb.gif)

**Comment by mazameli** [comment]
To make matters weirder, when I went to delete the email subscription on `Example KPIs dashboard` (it's in the `Demo Dashboards` collection), it's showing me _two_ delivery channels, which shouldn't ever happen:

![image](https://user-images.githubusercontent.com/2223916/134560202-f05b5fd4-5632-4a8f-adc7-9c5cc04b179e.png)

I still haven't actually deleted these subscriptions, and when I go back to the list of subscriptions for this dashboard, I only see the email-based on:

![image](https://user-images.githubusercontent.com/2223916/134560356-2920bf5e-ad21-4031-860a-0f41f9a03418.png)

**Comment by noahmoss** [comment]
This might just be an issue with cleaning up state on the frontend -- I've noticed a few cases where stuff I had entered into the subscription sidebar (without saving a subscription) was persisting longer than I'd have expected.
