### ISSUE TITLE
Custom Email attribute in LDAP configuration is not respected

### ISSUE THREAD

**Issue by espro** [metabase/metabase#18013]
**Describe the bug**

This is a new issue tested against the latest Metabase release v0.40.5 (#18012 was slightly different and tested on an older version)

When using a local directory and an LDAP directory, if you set a custom Email attribute in the LDAP configuration the new attribute is not fully respected and logins to local accounts which match the `mail` attribute of an LDAP user will no longer work with the local password.

**Logs**

```
{
    "status": 401,
    "data": {
        "errors": {
            "password": "did not match stored password"
        }
    },
    "isCancelled": false
```

**To Reproduce**

Metabase LDAP settings has Email attribute set to `krbprincipalname`
There is a local user `john@example.com`
There is an LDAP user `jsmith`, email `john@example.com` in `mail` attribute and `jsmith@example.corp` in `krbprincipalname` attribute

Trying to login with `john@example.com` with the local password **fails**
Trying to login with `john@example.com` with the LDAP password succeeds
Trying to login with `jsmith` with the LDAP password succeeds
Trying to login with `jsmith@example.corp` with the LDAP password succeeds

**Expected behavior**

The `mail` attribute from LDAP should never be used for any purpose once a custom Email attribute is set for the LDAP configuration

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7",
    "java.vendor": "Eclipse Foundation",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7",
    "os.name": "Linux",
    "os.version": "4.18.0-305.3.1.el8.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-09-21",
      "tag": "v0.40.5",
      "branch": "release-x.40.x",
      "hash": "042a36e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**

Blocking some users

**Comment by pawit-metabase** [comment]
The mapping is not used during login. The config used to lookup user during login is the "User Filter" on the admin page which has a default value of

```
(&(objectClass=inetOrgPerson)(|(uid={login})(mail={login})))
```

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

---

@flamber one valid UX issue is that the default on the admin page is not copy-pastable so it's really hard to read/modify. It's also not well-explained what it's being used for.

![image](https://user-images.githubusercontent.com/88995137/135017323-7228d365-6b68-4a84-8753-4366741950e8.png)

**Comment by flamber** [comment]
@pawit-metabase We have an issue for the bad UX - #16376

Closing, since it is working as expected - other perhaps @landreville could chime in with more context.

**Comment by espro** [comment]
> The mapping is not used during login. The config used to lookup user during login is the "User Filter" on the admin page which has a default value of

Why can I login with the content of the email attribute mapping then? Once set to `krbprincipal` name, I can login with it.

**Comment by flamber** [comment]
@espro Post your User Filter.

**Comment by espro** [comment]
`(&(memberOf=cn=metabase-users,cn=groups,cn=accounts,dc=example,dc=com)(objectclass=inetorgperson))`

**Comment by espro** [comment]
That won't work because groups don't have a level of users under them and Metabase doesn't seem to be looking at the member attribute

What I'm doing is how LDAP user filters typically work, I don't know why Metabase is putting user supplied data into one - look at any other piece of software. Nextcloud, Atlassian Jira, honestly anything - Google "enable ldap setup user filter".

Your filter is meant to return all valid users. You filter the baseDN based on something (e.g., membership in a group), cache that result locally (usually on a schedule) and then you check your local cache, then test bind against the directory with the user credentials. By not putting user supplied data into the filter, you're able to sync directory info and not rely on a user login to have the user list available to the software.
