### ISSUE TITLE
Custom Email attribute in LDAP configuration is not respected

### ISSUE THREAD

**Issue by espro** [metabase/metabase#18012]
**Describe the bug**

When using a local directory and an LDAP directory, if you set a custom Email attribute in the LDAP configuration the new attribute is not fully respected and logins will begin to fail for any user where a local user account matches the `email` attribute of an LDAP user

If a local user and an LDAP user share the same email in the original `email` attribute, logins will fail for the local user and the LDAP user whether logging in with the local user's email, the LDAP user's uid, or the LDAP user's email in the custom attribute. A duplicate key error will be shown when trying to login **for the second time** containing the email address from the LDAP user's custom attribute.

**Logs**

```
                 "type": "org.postgresql.util.PSQLException",
                 "message": "ERROR: duplicate key value violates unique constraint \"core_user_email_key\"\n  Detail: Key (email)=(jsmith@example.corp) already exists.",
                 "at": [
                     "org.postgresql.core.v3.QueryExecutorImpl",
                     "receiveErrorResponse",
                     "QueryExecutorImpl.java",
                     2497
                 ]
```

[metabase_dkey_ticket20210922.txt](https://github.com/metabase/metabase/files/7212474/metabase_dkey_ticket20210922.txt)

**To Reproduce**

Metabase LDAP settings has Email attribute set to `krbprincipalname`
There is a local user `john@example.com`
There is an LDAP user `jsmith`, email `john@example.com` in `email` attribute and `jsmith@example.corp` in `krbprincipalname` attribute

Trying to login with `john@example.com`, `jsmith` or `jsmith@example.corp` all result in a duplicate key error listing `jsmith@example.corp` after trying to login for a second time.

**Expected behavior**

The `email` attribute from LDAP should never be used for any purpose once a custom Email attribute is set for the LDAP configuration

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_272-b10",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_272",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.272-b10",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.2.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.1",
      "date": "2020-11-12",
      "branch": "release-x.37.x",
      "hash": "ba57ab6"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Severity**

Blocking some users

**Comment by flamber** [comment]
Latest release is 0.40.5 - there has been many changes and fixes since 0.37.1.
https://github.com/metabase/metabase/releases/latest
