### ISSUE TITLE
"Recents" list in search should display the Verified badge

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#18021]
The list of recently viewed items doesn't show the Verified badge next to verified items, though it does show up in search suggestions. The expectation is that the badge should appear in both of these contexts:

![verified-recents](https://user-images.githubusercontent.com/2223916/134432050-9f50d891-62b0-495f-8e2d-a20b38436831.gif)

**Comment by ranquild** [comment]
There is no `moderated_status` field in `/api/activity/recent_views` results. It should be added on the BE first.

**Comment by camsaul** [comment]
@bshepherdson this seems fairly straightforward we just need to include `moderated_status` in the endpoint mentioned above. Our API endpoints follow a naming convention so `/api/activity/recent_views` lives in the `metabase.api.activity` namespace; look for a `(defendpoint GET "/recent_views")` definition somewhere in that namespace.

The Recent Views endpoint can return several different types of objects -- Dashboards, Tables, and Cards (aka Saved Questions) . Both Dashboards and Cards can get ModerationReviews. `moderated_status` is calculated based on entries in ModerationReviews so you'll have to do some joins to get that info. There are a few different places where we calculate that info in the codebase. It would be nice to consolidate and deduplicate them -- I think this could be a good fit for [Toucan _hydration_](https://github.com/metabase/toucan/blob/master/docs/hydration.md). Up to you tho. I'm not an expert of the way the moderation stuff works so post in `#engineering-backend` if you have more questions.

I also think that implementation of the `recent_views` endpoint is a little hairier than it needs to be. You can rework that into a single HoneySQL query if you're in the mood. Please feel free to clean up things or refactor/deduplicate code when you come across anything that you think could be cleaned up a bit

**Comment by bshepherdson** [comment]
<img width="721" alt="Screen Shot 2022-04-19 at 15 28 11" src="https://user-images.githubusercontent.com/157812/164080797-a4e1b781-1117-4b2a-9e97-2088ecc4d76e.png">

We're actually already including `moderation_reviews: [{...}]` (which is different from `moderation_status: "verified"` returned by search) but there's nothing in the [UI](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/nav/components/RecentsList.jsx#L68) to show either field.

I'm sending a PR to add `moderated_status` to `/api/activity/recent_views` as well but it will need frontend work to surface it.

**Comment by bshepherdson** [comment]
This has landed in #21777 and is being backported in #21854 .

Redirecting to Frontend and unassigning myself.

**Comment by nemanjaglumac** [comment]
@daltojohnso - friendly reminder that this issue had a `.Reproduced` label at the time of fixing. The fix was merged without unskipping the repro.
