### ISSUE TITLE
X-ray dashboards crash on first opening

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#18028]
**Describe the bug**
The first time you open an automatic dashboard (suggested while x-raying a database table), it crashes and you see a blank page.

**Logs**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'some')
    at Dashboard.js:253
    at Array.some (<anonymous>)
    at hasMapping (Dashboard.js:252)
    at isDashboardParameterWithoutMapping (Dashboard.js:267)
    at ParameterValueWidget.render (ParameterValueWidget.jsx:166)
```

**To Reproduce**
1. Go to `/browse/1-sample-dataset`
2. Hover the Orders table and click the yellow x-ray button
3. You're navigated to a dashboard based on Orders. Click the "Save this" button in the top right without any edits
4. After the dashboard is saved, you should see a toast message in the bottom left. Click the "See it" link
5. FE crashes and you see a blank page

**Workaround**: refresh the page

**Expected behavior**
You should see the dashboard without a need to refresh

**Screenshots**

https://user-images.githubusercontent.com/17258145/134530463-812d06fc-f421-4e86-bfa8-3a30a94c1f88.mov

**Information about your Metabase Installation:**

Metabase v0.41.0-SNAPSHOT

**Comment by kulyk** [comment]
Hey @daltojohnso, from the browser logs I suppose it's caused by #17956. Can you please take a look?

**Comment by rlotun** [comment]
I'm surprised we don't have an e2e test for this since it's an easy repro - it's probably an opportunity to add one. cc/ @nemanjaglumac

**Comment by nemanjaglumac** [comment]
@rlotun we do have a few different repros around x-rays but we missed this particular scenario of saving an x-ray and then immediately navigating to. I'll add it in a moment. Thanks for bringing it to my attention.
