### ISSUE TITLE
Invalid comparison in custom expression leading to query error

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#18030]
Comparing a number to a string or a boolean should be rejected. Otherwise, the query results in an error.

**To Reproduce**

1. Ask a question, Custom question.
2. Sample Dataset, Orders table.
3. Filter and type `IsEmpty([Tax]) < 42`.
4. Visualize.

![image](https://user-images.githubusercontent.com/7288/134541542-e9802a58-a340-4f17-82c4-a68e89e6b8a0.png)

**Expected behavior**

The filter should be treated as invalid (since comparing the result of `IsEmpty()` which is boolean, with a number `42`, does not make any sense), hence the user can't continue.

Other examples which should be invalid as well: `[Discount] > "XYZ"` (number against string), `LOWER([Name]) > 0` (string against number), etc.

**Note**: This is discovered by @flamber while testing [another PR](https://github.com/metabase/metabase/pull/18017#pullrequestreview-761397685).

**Comment by flamber** [comment]
Giving P2, since that error is not something that humans understand, but it's otherwise possibly closer to P3.
