### ISSUE TITLE
card in dashbord out-of-order

### ISSUE THREAD

**Issue by xueyibing** [metabase/metabase#18043]
**Describe the bug**
![wecom-temp-72ef24c4107f4bd788ccfa52d9f72f1a](https://user-images.githubusercontent.com/13233726/134628775-35f39fd9-5fbc-4b3e-92c1-7e65f67489ac.png)
the third card is out-of-order, this is wrong use the fifth card, but if you refresh the web sometimes it is ok. so this bug is occasionally

my metabase version:
commit num:2bd3d707

**Comment by flamber** [comment]
Hi @xueyibing 
Post "Diagnostic Info" from Admin > Troubleshooting.
Post output of `/api/dashboard/123`, where 123 is the dashboard ID.

**Comment by xueyibing** [comment]
Hi@ flamber 
these are my tests;
first:
post  Request URL: https://m.qiniu.io/api/dashboard/825

**Comment by flamber** [comment]
@xueyibing 
I cannot reproduce this in any way with any databases. Could this be some cache somewhere (like a database cache or reverse-proxy cache)?
1. Please post "Diagnostic Info" from Admin > Troubleshooting, and which Postgres version you are querying.
2. Can you provide a HAR from browser developer Network-tab, when viewing the dashboard, so I can also see each of the card query results?

**Comment by xueyibing** [comment]
@flamber 
this is Diagnostic info:
`{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_292",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.292-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-140-generic",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "presto",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.27-30-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v1.40.1-SNAPSHOT",
      "date": "2021-09-23",
      "branch": "qiniu",
      "hash": "57515ba"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

`Could this be some cache somewhere (like a database cache or reverse-proxy cache)?`
and there is no cache on these question

**Comment by flamber** [comment]
@xueyibing Okay, I have absolute no way of reproducing this, so unless you provide exact steps to reproduce on a build that hasn't any other changes (your commit is different), then it will be close to impossible to know what's wrong or how to fix it.

I have tested with `b557b69` with MySQL 5.7, 8.0, MariaDB 10.4, Postgres 9.6, 12.8 and H2. And cannot reproduce.

If you can reproduce https://hub.docker.com/r/metabase/metabase-head/tags, then great, please describe how and exactly which database+version you are querying by creating a new issue and filling out all the details.
