### ISSUE TITLE
Erroring Questions (`Tools > errors`) loads terribly slow on H2, making it almost unusable

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#18051]
**Describe the bug**
`POST /api/dataset` query is taking forever to finish, making the `Tools` page load for close to a minute on H2. The instance is small and doesn't have more than 70-80 questions total, out of which 11 are "broken" (have errors).

@flamber said that this seems to be working fine when app db is Postgres. I didn't test other DBs.

**Logs**
```
[backend]
2021-09-24 15:53:08,107 DEBUG middleware.log ::
POST /api/dataset 202 [ASYNC: completed] 49.7 s (1 DB calls) App DB connections: 0/15 Jetty threads: 11/50 (0 idle, 0 queued) (96 total active threads) Queries in flight: 0 (0 queued)
```

```json
// POST request's payload
{
  "limit": 50,
  "type": "internal",
  "fn": "metabase-enterprise.audit-app.pages.queries/bad-table",
  "args": [null,null,null,"card_name","asc"],
  "offset": 0,
  "parameters": []
}
```

**To Reproduce**
1. Start with a H2 app db with the Sample Dataset provided
2. You should have 50-100 questions in total and about a dozen broken questions
3. Go to `admin > tools`
4. The page loads for 10s of seconds (in my case close to a minute)
5. If you try using search, it might completely block your app because multiple `POST` requests will be fired async

**Expected behavior**
Querying should be optimized for H2 as well.

**Screenshots**
https://share.getcloudapp.com/P8uGPDKe

**Information about your Metabase Installation:**
local dev, `master`, c225ace, H2, Sample Dataset

**Severity**
We discourage people from using H2 in production. However, people might still want to try out  Metabase first and they might choose to do so using H2. This bug might make that whole experience less than pleasant. If this doesn't happen for any other DB, the severity is not that high. P2, I guess?

**Comment by nemanjaglumac** [comment]
Tbh, not sure how easy this is to reproduce. There could be a bunch of factors contributing to such low performance on my machine.

Until someone else confirms the same thing, I'd take this with a grain of salt.

**Comment by howonlee** [comment]
I can reproduce by just making 20,000 erroring query executions, so this is some H2 query exec shenanigans that can still almost definitely be fixed at query level

**Comment by paoliniluis** [comment]
I think it makes sense to close this. If you have tons of errors and you're still using H2 as the App DB then you have bigger issues
