### ISSUE TITLE
Selected metric should be displayed in popover

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1805]
When you've selected a metric from the View menu, and then run the query, if you then open the View menu again you should see the selected metric rather than the list of "Metabasics." 

In this screenshot, I would have expected the Metabasics menu to be collapsed, the Custom Metrics menu to be open, and the `Count of distinct users` metric to be shown as selected:

![screen shot 2016-01-26 at 9 59 23 am](https://cloud.githubusercontent.com/assets/2223916/12589686/e3fb0930-c413-11e5-8e7c-058129f47384.png)

**Comment by agilliland** [comment]
@tlrobinson can you take a look at this one?
