### ISSUE TITLE
Order of time filters remains after rewriting the query or dragging the filters

### ISSUE THREAD

**Issue by zzzzzj94666** [metabase/metabase#18060]
When using time filters and snippets in the same question, the order of time filters can't be changed.  End_time is always in front of start_time. 

Orders can be changed by dragging or rewriting the query but cannot be saved. After click save bottom, all the changes of time filters disappeared. What should I do to alter order?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
