### ISSUE TITLE
Pin map with `null` locations shows tooltip of the wrong row

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18063]
**Describe the bug**
Tooltips of Pin maps with `null` locations shows information from the wrong results.

**Workaround** Since Metabase will not show pins for `null` locations, then add a filter to not include those rows in results.

**To Reproduce**
1. Native query > Sample Dataset
```
select null "LATITUDE", null "LONGITUDE", null "COUNT", 'NULL ROW' "NAME"
union all select 55.6761, 12.5683, 1, 'Copenhagen'
```
2. Change visualization to Pin map and hover the pin, which shows tooltip information from another row
_The example is simplified, it gets even worse, when there's a mix of null rows in the results_
![image](https://user-images.githubusercontent.com/1447303/134807119-c885ec30-6561-4520-b4eb-6ff97adcd9ab.png)

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.40.5 and master `67470a0`

**Additional context**
Perhaps related to #12674.

**Comment by nemanjaglumac** [comment]
Unrelated to this issue, but related to this UI. A slight annoyance:
Once you choose a "Pin map", both Latitude and Longitude selection menus open at the same time.
![image](https://user-images.githubusercontent.com/31325167/134910379-6999805b-8738-4c6f-8f53-b469402d49ea.png)
