### ISSUE TITLE
Cannot use Click Behavior on boolean columns to other questions boolean columns

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18067]
**Describe the bug**
Cannot use Click Behavior on boolean columns to other questions boolean columns on MySQL/MSSQL/(other?).
This might have something to do with MySQL/MSSQL actually not having a `boolean` data type, but using `tinyint(1)` or `bit(1)` instead, which then confuses the types that Metabase can map Click Behavior to.

**Possible workaround** Instead of linking to a question, then link to a dashboard, which has the question and filters connected to the columns.

**To Reproduce**
_Requires a table on MySQL with a Boolean column_
1. Simple question > **MySQL** > (table with boolean column) - save question as "Q1" and add to dashboard
![image](https://user-images.githubusercontent.com/1447303/134898407-d5ba6fbf-e542-4734-878a-91ae8ce7c305.png)
2. On dashboard, hover "Q1" card > Click Behavior > any column > Go to custom destination > Saved question > select "Q1"
3. It will not display any of the boolean columns
![image](https://user-images.githubusercontent.com/1447303/134898247-c97c5dd2-ee96-4ec9-a3a6-2038645e5351.png)

**Expected behavior**
Allow mapping to boolean columns on the destination question.

**Information about your Metabase Installation:**
Tested 0.40.5 and master `67470a0`

**Additional context**
Related to #15170

**Comment by WiNloSt** [comment]
Can't be reproduced on 46.8
