### ISSUE TITLE
Date filter selection stays on the foreground when switching to notebook

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18079]
**Describe the bug**
When switching from the simple builder to the notebook, if the filter is not completed then the dropdown stays on the foreground

**Logs**
N/A

**To Reproduce**
Using a table that has any kind of date field:
1) Click on filter
2) Select the date field (don't apply the filter)
3) Click on the "show editor" icon

![foreground](https://user-images.githubusercontent.com/1711649/134967701-46df67dd-038f-4916-877d-98e30c6c4d1d.gif)

**Expected behavior**
Dropdown shouldn't be shown

**Screenshots**
Video attached before

**Information about your Metabase Installation:**
- Your browser and the version: Brave 1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)
- Your operating system: Ubuntu latest
- Your databases: Sample DB
- Metabase version: metabase/metabase-enterprise:v1.40.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 13.3

**Severity**
Cosmetic

**Additional context**
N/A

**Comment by nemanjaglumac** [comment]
`z-index` for that "select" dropdown element is set to 3. Dialing it down to 1 does the job, but it's very likely that will cause a regression somewhere else.

I'll check if it's worth bumping the z-index of the notebook UI, instead.

**Comment by iethree** [comment]
> `z-index` for that "select" dropdown element is set to 3. Dialing it down to 1 does the job, but it's very likely that will cause a regression somewhere else.
> 
> I'll check if it's worth bumping the z-index of the notebook UI, instead.

Digging into the blame here, both the "relative" and "z3" classes seem to be leftover from a prior version (from 4 years ago) of this component with some absolutely positioned children. As far as I can tell, removing those classes fixes this bug, and doesn't cause a regression for any of the variants I've been able to trigger.

![Screenshot from 2022-03-21 14-55-04](https://user-images.githubusercontent.com/30528226/159366490-ada02374-f7fe-40bd-8173-62f86fe3d4d4.png)
