### ISSUE TITLE
Incorrect result using custom expression with join to saved question with duplicate column name

### ISSUE THREAD

**Issue by pawit-metabase** [metabase/metabase#18086]
**Describe the bug**
An incorrect result is returned when using custom expression with join to saved question. See reproduction instruction for more details.

**Logs**
N/A

**To Reproduce**
First create a saved question:
![image](https://user-images.githubusercontent.com/88995137/135017888-e109dc75-4248-47ca-af68-a188928bf0f7.png)

Then create a new question which joins to that saved question
![image](https://user-images.githubusercontent.com/88995137/135018332-c335e5d8-d099-48ef-b2fc-d2495704a9e8.png)
The custom expression is `[Question 1 → Count] / [Count]`

**Expected behavior**
`Count` should be 89
`Question 1 → Count` should be 41

**Screenshots**
Without custom expression (correct):
![image](https://user-images.githubusercontent.com/88995137/135018507-a89c1cd2-5348-4b60-8dd3-64d1c9cae948.png)

With custom expression (incorrect):
![image](https://user-images.githubusercontent.com/88995137/135018472-ed2157a4-94e9-43a5-bd52-7ebfd52367d9.png)

**Information about your Metabase Installation:**
v0.40.4, also present on master (`3565136`)

**Severity**
Makes join on saved question not trust-able

**Additional context**
Initially raised in #13649, the bug regarding the expression was fixed, but the issue of the other columns being incorrect remains.

This is actually being covered by the unit test already, but the existing result is wrong

https://github.com/metabase/metabase/blob/25aac414807b228f90bc9063be0e788d8b13dcc2/test/metabase/query_processor_test/explicit_joins_test.clj#L578-L580

The expected result is `[4 89 0.46 41]`

**Comment by flamber** [comment]
Excellent find! Seems like #17769 is related to this.

**Comment by camsaul** [comment]
This will be fixed by #19384

**Comment by camsaul** [comment]
Fixed by #19384
