### ISSUE TITLE
Question table seems to be reloaded 2 or 3 times when filter sidebar is opened or closed

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#18096]
## Steps to reproduce

1. Ask a Question
2. Simple Question
3. Sample Dataset
4. Orders
5. Filter (top right)

Pay attention to the orders table. 
It should flash 3 times.

6. Filter one more time

As the sidebar closes, the orders table should flash twice.

### Video

https://www.loom.com/share/a553a980ad9b4ea792e684211e9bcf93

**Comment by flamber** [comment]
Duplicate of #16704
