### ISSUE TITLE
History of last edited questions

### ISSUE THREAD

**Issue by Dynnammo** [metabase/metabase#18090]
**Is your feature request related to a problem? Please describe.**
As a business analyst, I have dozens of questions saved in Metabase. When I stop to work on some question, I have to find it back when I come back to it. 

**Describe the solution you'd like**
Having an history tab (or something else) that lists last edited questions. Clicking on a question redirects to it.

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Low priority.

**Additional context**

**Comment by flamber** [comment]
It will be available in 0.41 - see screenshots in #17582

**Comment by Dynnammo** [comment]
Thanks @flamber , sorry to annoy. Can't wait to install the last release :smile:
