### ISSUE TITLE
Rename aggregation "Row count" to "Count of rows"

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1809]
In the QB Tutorial on step 4 we tell the user to select "Count of rows" which is the copy for the old label of the count aggregation.  It's been renamed to "Row Count", so we should update the copy.

<img width="456" alt="screen shot 2016-01-26 at 12 18 40 pm" src="https://cloud.githubusercontent.com/assets/1987787/12593683/1e9afa2e-c427-11e5-88dd-0e657dbf0dc6.png">

**Comment by mazameli** [comment]
As @agilliland and I just discussed, this is actually backwards: we talked about changing `Row Count` to `Count of Rows` in the View dropdown to make it stand out more from `Raw Data`, and so that the operative word ("Count") is at the front.
