### ISSUE TITLE
"Save" button shouldn't appear before one selects the source for a native question

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#18148]
**Describe the bug**
Metabase currently displays the option to save a native question even before the source (db) for it is selected.

**Logs**
```
[backend]  "Input to adhoc-native-query-path does not match schema: \n\n\t   [(named (not (matches-some-precondition? nil)) database-or-id)]  \n\n",
[backend]  :value [nil],
[backend]  :error [(named (not (matches-some-precondition? nil)) database-or-id)]}
```

**To Reproduce**
1. Have more than one database (add another H2, for example)
2. New question > Native query
3. Without selecting a source database, note that the "Save" option is offered
4. Click on the "Save" - modal appears
5. Enter the name for your question and click "Save" button within the modal
6. Non-human-readable error appears inline

**Expected behavior**
The original "Save" button shouldn't even appear before it's actually possible to save the question

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/135492074-2fb57574-149a-450b-9d6f-92db00d9175c.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
local dev, `master`, 538a5e6c0a74c99f2ea71cf441d5c1600a13d382, H2, Sample dataset

**Severity**
Although annoying, it's a cosmetic one and the backend handles this. P3.

**Comment by flamber** [comment]
Friends with https://github.com/metabase/metabase/issues/15946#issuecomment-833316911.
