### ISSUE TITLE
Static visualizations does not work for some "X-axis style" types

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#18157]
**Describe the bug**
Static visualizations does not work for native queries

**To Reproduce**

1) Create a simple native query
```
select 10 as a, 1 as b union all
select 30 as a, 2 as b union all
select 15 as a, 5 as b union all
select 40 as a, 6 as b
```
<img width="1439" alt="Screen Shot 2021-09-30 at 20 40 22" src="https://user-images.githubusercontent.com/14301985/135504577-a722fa7b-ba88-49bd-91a8-f2d7e046f797.png">

2) add it on a dashboard and send a subscription notification

**Expected behavior**
It should render the chart

**Actual behavior**
It renders a table

**Screenshots**
<img width="634" alt="Screen Shot 2021-09-30 at 20 41 07" src="https://user-images.githubusercontent.com/14301985/135504798-e871b4be-0342-4548-bf28-82052c8e537f.png">

I'm running Metabase 1.41-RC1

**Comment by flamber** [comment]
I think it's because you are using a "X-axis scale" which is not Timeseries, so it's not specific to Native - here's GUI:
![image](https://user-images.githubusercontent.com/1447303/135505591-2fa3b47d-0692-43a5-bd1b-724d444a25f6.png)

I can reproduce with Linear, Histogram and Ordinal - didn't test Log or Power

**Comment by ranquild** [comment]
I'll add `categorical/line` and `categorical/area` static charts in case we would get some BE support in the future.

**Comment by ranquild** [comment]
The BE should render `categorical/line` where currently `timeseries/line` is rendered, but the reference please have a look at the existing `categorical/bar` and `timeseries/bar` code.
