### ISSUE TITLE
Do we need to update the Admin EE token page?

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#18153]
Now that we have several new groups of EE features, do we need to update this page?

![image](https://user-images.githubusercontent.com/1455846/135501339-703dd85f-f835-4263-9a92-4f4d43f6f4fb.png)

**Comment by ranquild** [comment]
Need mockups or a list of feature names, their descriptions, icons etc.

**Comment by brunobergher** [comment]
Let's do this in 42.

**Comment by brunobergher** [comment]
Let's do this in 42, or maybe 41.1, I don't think it's necessarily a blocker.
