### ISSUE TITLE
Focus being lost after one second after running query

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#18150]
**Describe the bug**
We made the "Name" field in the save modal autofocused, but something triggers the blur or any other mechanism that makes it lose that focus in less than a second. Probably a couple miliseconds.

**To Reproduce**
1. New question > Native query
2. Type `select 0`
3. Run the query
4. Click "Save" - the save modal opens
5. Notice how the "Name" fields starts focused but loses focus after a while without any action on your part

**Expected behavior**
The field should stay focused, unless there's an action on the user's part (clicking anywhere else, pressing `tab`,etc.)

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/d5uRoD55/6fea976c-cc52-46d7-aa83-bcaaf3402bfb.gif?source=viewer&v=7e28770b141b48d0ad80113615eb79c0)

**Information about your Metabase Installation:**
local dev, `master`, 538a5e6c0a74c99f2ea71cf441d5c1600a13d382, H2, Sample dataset

**Severity**
Depending on how much do you rely on the keyboard navigation it can be either P3, or P2. Closer to P2 for the sake of a11y.

**Comment by flamber** [comment]
Giving it P3 for now, but when the Save-modal is open and it loses input focus, then the editor actually gets focus, so if you started to type, then some of the characters will be in the query - most likely causing the query to fail. Could easily become a P2 issue.
