### ISSUE TITLE
In-app doc links point to latest version of docs, instead of the docs for that app's version

### ISSUE THREAD

**Issue by jeff-bruemmer** [metabase/metabase#18159]
**Describe the bug**
In-app documentation links point to latest docs version.

**To Reproduce**
1. Ask a question about the Sample Dataset using the SQL editor.
2. Click on variables sidebar.
3. Scroll down to link at bottom.
4. Inspect link to see it's pointing to latest.

**Expected behavior**
In-app links should point to the version relevant to the app. The RC candidate for the Open Source version does this; the issue seems to only affect the 1.41 release candidate.

**Screenshots**
![image](https://user-images.githubusercontent.com/17343328/135505233-e33c70d3-2fa6-4743-bd45-64342600c44e.png)
**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "US-ASCII",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Mac OS X",
    "os.version": "11.5",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-09-29",
      "tag": "v1.41.0-RC1",
      "branch": "release-x.41.x",
      "hash": "6ff4eda"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Docs will drift from this version as we release future versions, making these links potentially misleading, though how they differ will depend on upstream changes.

**Comment by flamber** [comment]
This should be updated, so we coordinate with how the new docs redirects work on the website too:
https://github.com/metabase/metabase/blob/25179f743eb5249db2ed5fb3e874c64bf6d35eed/frontend/src/metabase/lib/settings.js#L142-L158

**Comment by jeff303** [comment]
@jeff-bruemmer , @flamber ,  you basically want it to point to the non-suffixed version in all cases, right?  So, to clarify...

- `v0.41.0` should (obviously) point to `https://www.metabase.com/docs/v0.41.0/`
- `v1.41.0` should point to `https://www.metabase.com/docs/v0.41.0/` (this is current behavior)
- `v0.41.0-RCX` should point to `https://www.metabase.com/docs/v0.41.0/`
- `v1.41.0-RCX` should point to `https://www.metabase.com/docs/v0.41.0/`

Is that correct or did I misunderstand?

**Comment by jeff-bruemmer** [comment]
Docs are squashed to each major version. See https://www.metabase.com/docs/all/.

So: all examples above should point to `https://www.metabase.com/docs/v0.41/`.

**Comment by jeff303** [comment]
OK, opened #18270 to fix this, hopefully.  It will match any `vN.M.m-SUFFIX` version (where `N` is either 0 or 1, `M` is some major version number, `m` is some minor version number (optional), and `SUFFIX` is some suffix (optional), and in all cases will simply use `v0.M` as the tag.  I think that's the desired behavior?
