### ISSUE TITLE
Static visualizations do not work for queries with multiple metrics

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#18161]
**Describe the bug**
Static visualizations do not work for queries with multiple metrics even though the chart shows a single series

**To Reproduce**
1) Create a simple question with two metrics, but show only one series on the chart
<img width="1436" alt="Screen Shot 2021-09-30 at 20 53 14" src="https://user-images.githubusercontent.com/14301985/135506507-96fee1c2-fe0c-48fc-8ab9-f21fbe5a32b8.png">

2) Create a dashboard with the question and submit a notification to email or Slack

**Expected behavior**
It renders the chart

**Actual behavior**
It renders a table instead

**Screenshots**
<img width="657" alt="Screen Shot 2021-09-30 at 20 54 19" src="https://user-images.githubusercontent.com/14301985/135506620-19995f3d-0773-4bf0-95d5-e22b7044d958.png">

**Information about your Metabase Installation:**

Metabase 1.41-RC1

**Comment by losrebellos** [comment]
@flamber @alxnddr 

Could not replicate using those steps:
1. new question on `orders`
2. `summarize on `count` and `average of total` by `created at`
3. open `Vizualisation` panel
4. select `line`
5. remove `average of total` from y-axis
6. save

__Pulse png preview from API__
![image](https://user-images.githubusercontent.com/348552/157459643-9a814a6e-c721-4793-87dd-68c033f16de4.png)

Is that correct?

**Comment by flamber** [comment]
Fixed in 0.42.0 together with many other static visualization enhancements.
