### ISSUE TITLE
Caching controls do not work for native queries

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#18160]
**Describe the bug**
Caching controls does not seem to work with native queries. 

**To Reproduce**
1. Run Metabase Enterprise
2. Enable caching in Admin Settings.
3. Create a native question with `SELECT NOW()` query.
4. Edit question details and set caching for 2 hours.
5. Add this question to a dashboard
6. Refresh the dashboard multiple times.
7. Notice that the values changes.

**Expected behavior**
The rendered value for the question should not change for 2 hours.

**Screenshots**
<img width="666" alt="Screen Shot 2021-09-30 at 8 54 37 pm" src="https://user-images.githubusercontent.com/8542534/135506416-6ce19fc9-1070-4031-9c32-0a18d6a0c70f.png">

**Information about your Metabase Installation:**
I'm running Metabase 1.41-RC1

**Comment by rlotun** [comment]
fixed by: https://github.com/metabase/metabase/pull/18230
