### ISSUE TITLE
Not clear which of my notifications are alerts vs. subscriptions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#18162]
On the new `/account/notifications` page, there's no distinction between alerts and dashboard subscriptions. The second item in this screenshot is an alert, and while it _check_ for results daily, it does not necessariliy _send_ daily (it won't if there aren't any results).

![image](https://user-images.githubusercontent.com/2223916/135506646-7beed565-cd73-4e36-a7bf-bc5e7b3ce025.png)

I don't think this is a huge deal, since you can click on the item to see what it is (provided you have access to it), and also because the title of the item could potentially help clarify.

**Comment by brunobergher** [comment]
Never came up again, and this UI will be touched soon, closing.
