### ISSUE TITLE
Old visualization doesn't disappear when query is edited, re-ran, and returns an error

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1817]
1.  Write a SQL query. 
2.  Run it, see cool visualization.
3.  Break your query.
4.  Run it .
5.  You can't read the error because it's off screen & the old graph is still there (!) :scream_cat: :scream: 

![screen shot 2016-01-26 at 6 00 21 pm](https://cloud.githubusercontent.com/assets/1455846/12601578/dd9b328e-c456-11e5-9490-507d6dd779ad.png)

**Comment by tlrobinson** [comment]
Note: This is only triggered if the error is due to the shape of the data not working with the chosen visualization type.
