### ISSUE TITLE
Whitelabel Primary color not fully applied in `1.41.0-RC1`

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#18173]
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to `/admin/settings/whitelabel`
2. Change the primary color
3. Note that across many places in the app the old (original) blue color is still shown (see screenshots below)

_Refreshing doesn't help. This doesn't seem to be the state issue._

**Expected behavior**
Primary color should be consistently applied.

**Screenshots**
`master` () - applying primary color correctly
![image](https://user-images.githubusercontent.com/31325167/135525389-a6d8f094-1d75-4d83-a40a-f7be401522a7.png)

![image](https://user-images.githubusercontent.com/31325167/135526031-a852dca4-d7e6-4ed3-9288-45df9517a7e6.png)

vs.

RC1
![image](https://user-images.githubusercontent.com/31325167/135525841-17fdc2f4-e29e-489d-99f6-1f1cdebb1429.png)

![image](https://user-images.githubusercontent.com/31325167/135525972-e6be839f-217c-4edb-ade1-10ef2b104dfb.png)

**Information about your Metabase Installation:**
H2, Sample Dataset, docker image `metabase/metabase-enterprise:v1.41.0-RC1` and also ee uberjar for 1.41.0-RC1 

**Severity**
P3?

**Additional context**
I started with the EE docker image `metabase/metabase-enterprise:v1.41.0-RC1` that uses the old app db (with whitelabeling set). At first I thought that there could be some problems with upgrading, but I could reproduce the same problem using the JAR and starting everything from the scratch.

**Comment by flamber** [comment]
This is a close P1, but I cannot reproduce. Neither with existing instances or new.
Not sure what to ask for, but `GET /api/setting/application-colors` and which features your token has.

**Comment by ranquild** [comment]
Ok, found a way to reproduce it on `release-x.41.x` branch locally:
1. Run Metabase EE locally without whitelabel
2. Open the home page
2. Go to Admin and change the primary color.
3. Exit Admin and come back to the home page
4. Color of the search bar is not changed - it's still blue.

What's important (and makes it worse) is that it's a local issue with the component:

```
import styled from "styled-components";
import { space } from "styled-system";

import { DefaultSearchColor } from "metabase/nav/constants";
import { color, lighten } from "metabase/lib/colors";

const ActiveSearchColor = lighten(color("nav"), 0.1); // <-- this is the issue

export const SearchWrapper = styled.div`
  display: flex;
  position: relative;
  background-color: ${props =>
    props.active ? ActiveSearchColor : DefaultSearchColor};
  border-radius: 6px;
  flex: 1 1 auto;
  max-width: 50em;
  align-items: center;
  color: white;
  transition: background 300ms ease-in;
  &:hover {
    background-color: ${ActiveSearchColor};
  }
`;
```

Colors should be set as constants like that as they are changed by whitelabel. I'll try to find as many places of misusage as possible. @nemanjaglumac

**Comment by nemanjaglumac** [comment]
@ranquild I think what you're seeing is: https://github.com/metabase/metabase/issues/18006

**Comment by ranquild** [comment]
> @ranquild I think what you're seeing is: #18006

I think this is completely the same issue, it's just code import order that have changed.

**Comment by nemanjaglumac** [comment]
If it helps, I cannot fully reproduce the originally reported issue and the screenshots I attached.

Started again from the freshly downloaded uberjar and clean app db. Then used enterprise key that has all these new features enabled, updated the whitelabelling primary color and that's it.

I can still reproduce #18006, but not these issues I listed here.

**Comment by ranquild** [comment]
Related https://github.com/metabase/metabase/pull/18217

**Comment by nemanjaglumac** [comment]
> If it helps, I cannot fully reproduce the originally reported issue and the screenshots I attached.

Oh, wait. I totally can! Finally figured out how to do it consistently.

1. Start with the completely clean Metabase installation (ideally from the [1.41.RC-1 uberjar](https://downloads.metabase.com/enterprise/v1.41.0-RC1/metabase.jar))
2. Set up your profile
3. Go to Enterprise and enter the EE token
4. Go to admin > settings > Whitelabel
5. Change the primary color to something other than the default blue one
6. At this point, all the links in the admin sidebar are applied correctly
7. Go to Localization and change the language to anything other than English
8. Notice the links switched back to the original Metabase blue color and all other issues reported originally are now visible

Take a look at the video for more info:
https://share.getcloudapp.com/bLuq4xwQ

I don't think that the language specifically has anything to do with it. It's more likely that when there is ANY setting update happening, the colors reset.

**Comment by pawit-metabase** [comment]
On x.40, `.css` files were included before `.js` file.

On x.41, `.css` files are being included after the `.js` file - https://github.com/jantimon/html-webpack-plugin/blob/0a6568d587a82d88fd3a0617234ca98d26a1e0a6/index.js#L880

My hypothesis is that if the `.js` file is cached, then the CSS manipulation code is being ran before the CSS is loaded leading to this issue.

**Comment by pawit-metabase** [comment]
Nope, changing the order by itself didn't help, but removing `defer` does. There's probably no point with `defer` anyway as nothing is rendered without JS.
