### ISSUE TITLE
Handle React routes better for unauthenticated and not-setup instance

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18180]
**Describe the bug**
It's currently possible to visit some routes unauthenticated, but there's no redirect to login.
This is almost just a tech debt issue, but given we're showing blank pages or some general pages, then leaving as bug.

**To Reproduce**
1. Logout
2. Try visiting
   1. `/user/edit_current` - blank page - this has been renamed to `/account/profile` in 41, but should have a redirect then
   2. `/_internal` - should this even be included in releases?
   3. `/dash/1` - blank page
   4. `/collections/create` - flashes "modal" and redirects to blank page

**Expected behavior**
Almost everything below line 246 should be part of the previous `MAIN` `IsAuthenticated`
https://github.com/metabase/metabase/blob/d012c89b17e61b9af984c49efed581ca1b4fe1c2/frontend/src/metabase/routes.jsx#L246
I don't think there's a way for an outside (non-user) receiver of alerts/subscriptions to unsubscribe from them via an unauthorized link in the email. I think there once was, but cannot see there's this option anymore, so shouldn't be a problem adding all routes to authenticated.

**Information about your Metabase Installation:**
Tested 0.40.5 and master

**Additional context**
Related to #15471 / #15636 / #15225 / #18155

**Comment by WiNloSt** [comment]
@flamber Since it's quite some time, should the `/user/edit_current` part still be redirected to `/account/profile`?

**Comment by flamber** [comment]
@WiNloSt Yeah, probably fine to leave it. The most important thing is to never show blank pages (entire frontend crashes).
