### ISSUE TITLE
Export in 0.41.0-rc1 does not include aggregated columns

### ISSUE THREAD

**Issue by tvinckier** [metabase/metabase#18181]
Hi,

I would like to report an issue with the newest released RC version.
The export function is not always working as intended.

The new export way doesn't always name the file in the new way.
Somtimes the naming starts with the title off the report, sometimes with Query_result....

I also have a specific report that is always exported as 'empty'. It only gives me the title column. All the data values are gone. CSV, XLSX, JSON they are all empty besides the title.

<img width="483" alt="Schermafbeelding 2021-10-01 om 13 48 48" src="https://user-images.githubusercontent.com/85233111/135615468-ff88ed98-5077-42f9-bd23-2e561ea54ddc.png">
<img width="792" alt="Schermafbeelding 2021-10-01 om 13 48 30" src="https://user-images.githubusercontent.com/85233111/135615469-02cbcac7-5695-412c-955d-c9445ab1e5ac.png">

Diagnostic information:
```
{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "nl",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-09-29",
      "tag": "v0.41.0-RC1",
      "branch": "release-x.41.x",
      "hash": "6ff4eda"

    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @tvinckier 
Seems like this happens for some columns that has conditional formatting, but only while the question is unsaved.

The name of the file is only the question name, unless you have created an ad-hoc query (example changing the filters without saving, and then trying to download those results).

**Comment by noahmoss** [comment]
@flamber not able to repro, I have an unsaved question with conditional formatting on one column and it's still showing up in the export. Is there anything I could be missing?

**Comment by flamber** [comment]
@noahmoss Try question 3308 on stats. Add a filter ID>=0 and download

**Comment by noahmoss** [comment]
Got it, it's actually an issue with aggregations in exports, not the conditional formatting. Working on a fix.
