### ISSUE TITLE
Remove animation from SQL popup when under `reduce-motion`

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#18189]
## Get to the element to remove the animation of

1. Ask a Question
2. Simple Question
3. Sample Dataset
4. People
5. On the top right, click on icon to "Show Editor"
6. On the top right, click on icon to "View the SQL"

![image](https://user-images.githubusercontent.com/380816/135648574-187237c9-e2a8-4877-a7a5-d9a8b2767821.png)

**Comment by ariya** [comment]
This was taken care by PR #18588.
