### ISSUE TITLE
Can "FILTER SAVED QUESTIONS" just not include databases with no questions?

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1818]
On lots of sites when you have the option to filter a set of results you only see "relevant" filter options. On Amazon's product search, for example, you can filter TVs by size / department / etc. You never see the option to only show TVs in the "Kitchen Knives" department because there aren't any.

I have lots of DBs, and most of them don't have any questions. Wouldn't it be nicer not to show the option at all?

![screen shot 2016-01-26 at 6 04 25 pm](https://cloud.githubusercontent.com/assets/1455846/12601618/45642d62-c457-11e5-953c-e79aad77dce8.png)

**Comment by agilliland** [comment]
resolved by #2325
