### ISSUE TITLE
Improve loading spinner visual when under `reduce-motion`

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#18191]
Currently the loading spinner, when `prefers-reduce-motion` is enabled, is the spinner, but frozen.

Users can be confused by that visual.

An alternative that's been mentioned is using an hourglass icon.

**Comment by ariya** [comment]
I like this idea a lot!

@mazameli What do you think? Is it easy/difficult to come up with an hourglass icon and then start using it?

**Comment by mazameli** [comment]
@ariya I think you can add that icon in the same PR that implements the reduced-motion loading. You need to add the svg path to `/frontend/src/metabase/icon_paths.js` — the pattern for how is pretty self-evident in that file, but let me know if I can help.
