### ISSUE TITLE
List of All personal collections is limited to 30 items

### ISSUE THREAD

**Issue by AnatolePledg** [metabase/metabase#18214]
**Bug**
When seeing all personal collections, under xxx.metabaseapp.com/collection/users, the list is limited to 30 items. This is a problem for companies having more than 30 accounts set up.

**To Reproduce**
1. Have more than 30 personal collections
2. Go to xxx.metabaseapp.com/collection/users
3. You only see 30 items

**Expected behavior**
Being able to see all items by scrolling are navigating through pages

**Severity**
High. We cannot administrate all collections due to this

**Additional context**
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7",
    "java.vendor": "Eclipse Foundation",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7",
    "os.name": "Linux",
    "os.version": "4.14.219-164.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-09-21",
      "tag": "v1.40.5",
      "branch": "release-x.40.x",
      "hash": "042a36e"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

**Comment by paoliniluis** [comment]
Hi @AnatolePledg, can you please send a screenshot of the users list and then the list of personal collections? I can't reproduce what you're reporting. Also if you can send the results of the API calls when visiting that URL it would be great. By the way, if you're running on our cloud, please send all this to our support email
