### ISSUE TITLE
Wrong tooltip for grouped bar chart on 1.41.0-RC1

### ISSUE THREAD

**Issue by pawit-metabase** [metabase/metabase#18210]
**Describe the bug**

**Logs**
N/A

**To Reproduce**
1. Create new SQL question on Sample Dataset
2. Use following query `SELECT "CATEGORY", count(*) AS "c", avg("RATING") AS "a" FROM "PRODUCTS" GROUP BY "CATEGORY"`
3. Select "bar" visualization
4. Under "display" option, rename columns to "count" and "average"
5. Hover on the average bar

**Expected behavior**
Should display

```
CATEGORY: Doohickery
count: 42
average: 3.73
```

**Screenshots**
<img width="255" alt="Screen Shot 2564-10-04 at 15 20 40" src="https://user-images.githubusercontent.com/88995137/135817536-b13ac231-fc3c-4502-a71c-28710d74a8ad.png">

**Information about your Metabase Installation:**
Version 1.41.0-RC1

**Severity**
Display incorrect label, can be misleading

**Additional context**
Worked fine in 1.40.5

**Comment by pawit-metabase** [comment]
As identified by @flamber (and verified by me), this is a regression from #17946.

@ranquild can you take a look?

**Comment by rlotun** [comment]
this is fixed by the revert: https://github.com/metabase/metabase/pull/18227
