### ISSUE TITLE
Field alias different for metric and sort, causing invalid query on Snowflake

### ISSUE THREAD

**Issue by UserArn00b** [metabase/metabase#18211]
**Describe the bug**
When I want to sort my question by a metric (defined in the data model > metrics) I have this error:
`SQL compilation error: error line 1 at position 1,535 invalid identifier '"Direct + Influenced Open Rate"'`

My metrics has capital letters "Direct + Influenced Open Rate".
The SQL request sent to my database Snowflake does not include the capital letters in the select statement but include the capital letters in the sort clause causing the invalid identifier issue.
Here the request received by Snowflake from Metabase:
`SELECT date_trunc("quarter", CAST("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."STAT_DATE" AS timestamp)) AS "STAT_DATE", "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."COMPANY_NAME" AS "COMPANY_NAME", "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."APP_NAME" AS "APP_NAME", "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."PLATFORM" AS "PLATFORM", "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."CAMPAIGN_TYPE" AS "CAMPAIGN_TYPE", (CAST(sum(("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."DIRECT_OPEN" + "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."INFLUENCED_OPEN")) AS float) / CASE WHEN sum("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."OPTIN_SENT") = 0 THEN NULL ELSE sum("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."OPTIN_SENT") END) AS "direct + influenced open rate", (CAST(sum("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."DIRECT_OPEN") AS float) / CASE WHEN sum("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."OPTIN_SENT") = 0 THEN NULL ELSE sum("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."OPTIN_SENT") END) AS "direct open rate" FROM "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS" WHERE ("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."COMPANY_NAME" = ? AND "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."STAT_DATE" >= ? AND "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."STAT_DATE" < ?) GROUP BY date_trunc("quarter", CAST("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."STAT_DATE" AS timestamp)), "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."COMPANY_NAME", "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."APP_NAME", "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."PLATFORM", "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."CAMPAIGN_TYPE" ORDER BY "Direct + Influenced Open Rate" DESC, date_trunc("quarter", CAST("BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."STAT_DATE" AS timestamp)) ASC, "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."COMPANY_NAME" ASC, "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."APP_NAME" ASC, "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."PLATFORM" ASC, "BATCH"."PUBLIC"."FACT_DAILY_CAMPAIGNS"."CAMPAIGN_TYPE" ASC`

**Logs**
`[e8ce7813-0f33-40db-8c58-40f02f2ec031] 2021-10-04T10:42:11+02:00 DEBUG metabase.server.middleware.log GET /api/database/5/autocomplete_suggestions 200 8.4 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (7 idle, 0 queued) (121 total active threads) Queries in flight: 0 (0 queued)
[e8ce7813-0f33-40db-8c58-40f02f2ec031] 2021-10-04T10:42:14+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 5,
 :started_at #t "2021-10-04T08:42:13.397499Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__80803.invoke(execute.clj:480)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:477)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:472)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
    "driver.sql_jdbc$fn__82292.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__82292.invoke(sql_jdbc.clj:52)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47903.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__47017.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__47889.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__46469.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__48149.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50081.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45588.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41716.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__41591.invoke(annotate.clj:608)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46889.invoke(permissions.clj:81)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__49010.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__47090.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__49307.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__49620.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__45164.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47853.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__47834.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44458.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__47156.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__45975.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__46692.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__44813.invoke(add_dimension_projections.clj:312)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__45042.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__50030.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__45327.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49182.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45535.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46739.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48992.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46791.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__47540.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__45336.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49983.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49193$fn__49197.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49193.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47780.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__49992$fn__49993.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__49992.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50037.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__47916.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__45182.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49968.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47033.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__49079.invoke(process_userland_query.clj:134)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46973.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___38255$thunk__38256.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___38255.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___38264$fn__38267.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___38264.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__50127$process_query_and_save_execution_BANG___50136$fn__50139.invoke(query_processor.clj:253)"
    "query_processor$fn__50127$process_query_and_save_execution_BANG___50136.invoke(query_processor.clj:245)"
    "query_processor$fn__50171$process_query_and_save_with_max_results_constraints_BANG___50180$fn__50183.invoke(query_processor.clj:265)"
    "query_processor$fn__50171$process_query_and_save_with_max_results_constraints_BANG___50180.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__56418.invoke(dataset.clj:56)"
    "query_processor.streaming$streaming_response_STAR_$fn__56397$fn__56398.invoke(streaming.clj:72)"
    "query_processor.streaming$streaming_response_STAR_$fn__56397.invoke(streaming.clj:71)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__16088.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 6 queryType: native queryHash: a485998d869b9b6f42b1ba2d36aca7534609f12c39a68ffb10a1734f16d3e6e4\nwith daily as(\n    select\n    date_trunc('quarter', stat_date) as quarter\n    ,app_name\n    ,company_name\n    ,platform\n    ,campaign_type\n    ,coalesce(sum(direct_open), 0) as direct_open\n    ,coalesce(sum(influenced_open), 0) as influenced_open\n    ,coalesce(sum(optin_sent), 0) as optin_sent\n    from fact_daily_campaigns\n    where true\n    \n     and \"BATCH\".\"PUBLIC\".\"FACT_DAILY_CAMPAIGNS\".\"COMPANY_NAME\" IN (?)\n    \n    \n    group by 1, 2, 3, 4, 5\n)\n\nselect\nquarter\n,app_name\n,company_name\n,platform\n,campaign_type\n,direct_open / optin_sent as direct_open_rate\n,(direct_open + influenced_open) / optin_sent as direct_influenced_open_rate\nfrom daily\nwhere optin_sent > 0\nqualify row_number() over(partition by quarter, app_name, company_name, platform, campaign_type order by ?) <= ?)",
    :params ["Back Market" "direct_open_rate" "10"],
    :type :invalid-query}}],
 :state "42000",
 :error_type :invalid-query,
 :json_query
 {:database 5,
  :native
  {:template-tags
   {:app_name
    {:id "580454c4-6cae-2081-3172-9d14f49debd7",
     :name "app_name",
     :display-name "App Name",
     :type "dimension",
     :dimension ["field" 1529 nil],
     :widget-type "category"},
    :company_name
    {:id "abf0a1b7-dc62-878c-6761-78cac99b8d23",
     :name "company_name",
     :display-name "Company Name",
     :type "dimension",
     :dimension ["field" 1522 nil],
     :widget-type "category"},
    :platform
    {:id "600d05e0-66f1-15ad-61f3-4a822c643e4a",
     :name "platform",
     :display-name "Platform",
     :type "dimension",
     :dimension ["field" 1525 nil],
     :widget-type "category"},
    :campaign_type
    {:id "cee2a022-fb06-6118-7de1-609f8327fc04",
     :name "campaign_type",
     :display-name "Campaign type",
     :type "dimension",
     :dimension ["field" 1531 nil],
     :widget-type "category"},
    :rank_type
    {:id "46dd005e-815a-8232-b885-8295751a9950",
     :name "rank_type",
     :display-name "Rank Type",
     :type "text",
     :required true,
     :default "direct_open_rate"},
    :rank
    {:id "df771ef3-0a31-11b5-8c81-6755a7658fe3",
     :name "rank",
     :display-name "Rank",
     :type "text",
     :required true,
     :default "10"}},
   :query
   "with daily as(\n    select\n    date_trunc('quarter', stat_date) as quarter\n    ,app_name\n    ,company_name\n    ,platform\n    ,campaign_type\n    ,coalesce(sum(direct_open), 0) as direct_open\n    ,coalesce(sum(influenced_open), 0) as influenced_open\n    ,coalesce(sum(optin_sent), 0) as optin_sent\n    from fact_daily_campaigns\n    where true\n    [[ and {{app_name}}]]\n    [[ and {{company_name}}]]\n    [[ and {{platform}}]]\n    [[ and {{campaign_type}}]]\n    group by 1, 2, 3, 4, 5\n)\n\nselect\nquarter\n,app_name\n,company_name\n,platform\n,campaign_type\n,direct_open / optin_sent as direct_open_rate\n,(direct_open + influenced_open) / optin_sent as direct_influenced_open_rate\nfrom daily\nwhere optin_sent > 0\nqualify row_number() over(partition by quarter, app_name, company_name, platform, campaign_type order by {{rank_type}}) <= {{rank}})"},
  :type "native",
  :parameters [{:type "category", :value ["Back Market"], :target ["dimension" ["template-tag" "company_name"]]}],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class net.snowflake.client.jdbc.SnowflakeSQLException,
 :stacktrace
 ["net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:124)"
  "net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:64)"
  "net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:434)"
  "net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:338)"
  "net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:501)"
  "net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:229)"
  "net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:167)"
  "net.snowflake.client.core.SFStatement.execute(SFStatement.java:749)"
  "net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:245)"
  "net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:117)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
  "--> driver.sql_jdbc.execute$fn__80721.invokeStatic(execute.clj:340)"
  "driver.sql_jdbc.execute$fn__80721.invoke(execute.clj:338)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:353)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:349)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__80803.invoke(execute.clj:478)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:477)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:472)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
  "driver.sql_jdbc$fn__82292.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__82292.invoke(sql_jdbc.clj:52)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47903.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__47017.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47889.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__46469.invoke(cache.clj:204)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__48149.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50081.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45588.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41716.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__41591.invoke(annotate.clj:608)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46889.invoke(permissions.clj:81)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__49010.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__47090.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__49307.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__49620.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__45164.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47853.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__47834.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44458.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__47156.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45975.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46692.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44813.invoke(add_dimension_projections.clj:312)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__45042.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__50030.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__45327.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49182.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45535.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46739.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48992.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46791.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47540.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__45336.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49983.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49193$fn__49197.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49193.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47780.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__49992$fn__49993.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49992.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50037.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47916.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__45182.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49968.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__47033.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__49079.invoke(process_userland_query.clj:134)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46973.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38255$thunk__38256.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38255.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___38264$fn__38267.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___38264.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
  "query_processor$fn__50127$process_query_and_save_execution_BANG___50136$fn__50139.invoke(query_processor.clj:253)"
  "query_processor$fn__50127$process_query_and_save_execution_BANG___50136.invoke(query_processor.clj:245)"
  "query_processor$fn__50171$process_query_and_save_with_max_results_constraints_BANG___50180$fn__50183.invoke(query_processor.clj:265)"
  "query_processor$fn__50171$process_query_and_save_with_max_results_constraints_BANG___50180.invoke(query_processor.clj:258)"
  "api.dataset$run_query_async$fn__56418.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__56397$fn__56398.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__56397.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16088.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error "SQL compilation error:\nsyntax error line 30 at position 112 unexpected ')'.",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}`

**To Reproduce**
1. Create a Metrics with capital letters in the name
2. Use this metric in a question
3. Sort on this metric

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+7",
    "java.vendor": "Eclipse Foundation",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+7",
    "os.name": "Linux",
    "os.version": "4.19.0-16-cloud-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-09-09",
      "tag": "v0.40.4",
      "branch": "release-x.40.x",
      "hash": "16d2e53"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

**Comment by flamber** [comment]
Reproduce:
1. Custom question > **Snowflake** Sample Dataset > Products
2. Summarize Custom Expression `Sum([Rating])` as "MyCE" grouped by Category
3. Sort by "MyCE"
4. Query fails because the aliasing is different for the "MyCE" (lowercased in the select-clause, original in order-clause)
```sql
SELECT
  "v3_sample - dataset"."PUBLIC"."products"."category" AS "category",
  sum("v3_sample - dataset"."PUBLIC"."products"."rating") AS "myce" 
FROM
  "v3_sample - dataset"."PUBLIC"."products" 
GROUP BY
  "v3_sample - dataset"."PUBLIC"."products"."category" 
ORDER BY
  "MyCE" ASC,
  "v3_sample - dataset"."PUBLIC"."products"."category" ASC
```
