### ISSUE TITLE
Trying to use metabase with QuestDb could use some pointers

### ISSUE THREAD

**Issue by LasseJacobs** [metabase/metabase#18224]
I am trying to use metabase with QuestDb. Quest support the Postgres wire protocol and it is this connection I am using to connect to metabase. Quest however does not support schemas. Thus `select * from schema.table` will fail. Currently it is failing on queries such as these: SELECT TRUE AS "_" FROM "public"."people" WHERE 1 <> 1 LIMIT 0. The rest works fine so far.

I would like to try and make this work anyway. But before diving in, could anyone familiar with the project give me some advice? Is there an easy way to disable the automatic use of schemas or is the logic spread all across the program? Any advice on where to look? 

I am using this setup purely for personal usage and really, mostly for fun so I don't mind having it forked. I mostly just want to give metabase a try and my data happens to be in QuestDB.

Any help on this is appreciated but I am not a paying customer so consider this low priority.

**Comment by LasseJacobs** [comment]
I guess there is a big gap between speaking Postgres and having all the pg_ tables. I think it will be too much work to get working...

**Comment by Trolorol** [comment]
Hey @LasseJacobs, did you get somewhere with questdb and metabase? Or your last comment was definitive?

**Comment by LasseJacobs** [comment]
@Trolorol no was not able to get it to work. I switched to Postgres. I have very small amounts of data so postgres can easily handle it; mostly just wanted to test questdb out. 

But I also didn’t try very hard. Maybe it’s possible. I saw that you can extend MB with your own connectors maybe it is possible that way. Maybe there is already a community developed connector… not sure.

**Comment by Trolorol** [comment]
@LasseJacobs Ok, thanks for the update :)
