### ISSUE TITLE
The token is logged in plain text

### ISSUE THREAD

**Issue by tovbinm** [metabase/metabase#18249]
**Describe the bug**
This line - https://github.com/metabase/metabase/blob/master/src/metabase/public_settings/premium_features.clj#L66 - logs the token in plain text.

**Logs**
```
{"timeMillis":1633448622856,"thread":"clojure-agent-send-off-pool-2","level":"INFO","loggerName":"metabase.public-settings.metastore","message":"Using this URL to check token: https://store.metabase.com/api/**redacted**/v2/status","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":54,"threadPriority":5}
```

**To Reproduce**
1. Run Metabase with an enterprise token 
2. Browse the logs and look for `Using this URL to check token`

**Expected behavior**
No token should be leaked to the logs.

**Screenshots**
N/A

**Information about your Metabase Installation:**
v1.39.5

**Severity**
High

**Additional context**
N/A

**Comment by paoliniluis** [comment]
Hi @tovbinm, the only users that can see this token are the server administrators or the application admin. I will flag this as a bug but not critical as the exposure is mitigated

**Comment by tovbinm** [comment]
In the meantime we updated `log4j2.xml` with:
```
<Logger name="metabase.public-settings.metastore" level="WARN"/>
```

**Comment by camsaul** [comment]
I think we should just remove that `Using this URL to check token` log line entirely

**Comment by tovbinm** [comment]
Yay! Thanks @escherize
