### ISSUE TITLE
SQL snippets

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#1825]
PeriscopeData has "sql snippets".  These are essentially re-usable pieces of sql that you can use in any custom sql query.

Example:
Lets say I have a query like so:

```
select C.id, C.name, A.workflowId, GROUP_CONCAT(A.stageNumber), A.complete, A.createDate,
from x2_contacts as C
    inner join x2_actions A ON C.id = A.associationId
where A.associationType = 'contacts'
    and A.type = 'workflow'
    and A.workflowId = 6
group by C.id
order by C.id
```

I'm always joining the same columns so I could create a snippet with the from section: 

```
from x2_contacts as C
    inner join x2_actions A ON C.id = A.associationId
```

Lets call this snippet "Join action to contact".

So in sql I can now do something like: 

```
select C.id, C.name, A.workflowId, GROUP_CONCAT(A.stageNumber), A.complete, A.createDate,
[snippet=Join action to contact]
where A.associationType = 'contacts'
    and A.type = 'workflow'
    and A.workflowId = 6
group by C.id
order by C.id
```

Why do this:
- Great for simple re-usable data that you can use on multiple queries/questiosn
- Great for subqueries
- Allows me to make complex snippets that can be changed once, and it would effect multiple queries/questions/visualizations.

**Comment by agilliland** [comment]
That's definitely an interesting idea.  We are just about to release a couple new features that accomplish something along the same lines #1011 and #1012

**Comment by tlrobinson** [comment]
Also related to #1822. As I note there you can do subqueries with SQL views, but it would be nice to be able to do it within Metabase.

**Comment by salsakran** [comment]
think if we go down the road to SQL templates, this would be a good extension, where you can use Metrics or Segments inside a SQL query

**Comment by hopsoft** [comment]
I have a need to write **segments** using **SQL** so I can ensure the database uses indexes properly. For example, I would love to create a time based segment on a PostgreSQL database like so.

**Comment by salsakran** [comment]
just to re-open this, @tlrobinson + @camsaul - 

This might be a cool additional SQL Template Tag

**Comment by tlrobinson** [comment]
(note: the "template tag" features discussed below is work in progress so don't be confused if you can't find it in Metabase yet)

@salsakran The basic idea is that an admin would create snippets (for a particular?) database (maybe in the data model page?), then people writing SQL cards could use them in their queries via a template tag?

Are you thinking a special syntax (e.x. `{{snippet:Join action to contact}}`) perhaps with autocomplete support, or a "snippet" tag type you select in the tag pane, then select a previously saved snippet?

**Comment by that0n3guy** [comment]
I think your syntax above would work.   It could be used for all kinda of things and make bulk updating a lot of queries easy.

Can we have snippets inside of snippets as well? That might just be asking too much :).

`{{snippet:Get busy season Quotes}}` could equal `select {{snippet:Typical Select for Busy Season}} where {{snippet:Where with busy season dates}}`

**Comment by salsakran** [comment]
@tlrobinson my specific idea was something like:
{{metric:name of metric}} or {{segment: name of segment}}. This would let you re-use canonical definitions of metrics + segments in native queries. 

I'm also open to the idea of a generic SQL snippet of form {{snippet: xxx}} where that snippet is a free-form native query, as @that0n3guy helpfully proposed.  

It would, however, probably need to be specific to a given database dialect. Eg window functions, crosstab, etc aren't consistent across our supported databases. While it's possible few enough people run multiple databases and intend to use snippets with them, it's potentially a source of a really annoying error.

**Comment by tlrobinson** [comment]
@salsakran two things:

`{{segment:...}}` is easy since it's just filters that go in the WHERE clause, but where would you put a `{{metric:...}}` tag? It potentially needs clauses in SELECT, FROM, and WHERE.

Also, segments and metrics aren't currently uniquely named (and could potentially include `}}`).

A think a separate `{{snippet:...}}` tag would be nice. Nested snippets would be nice too (though nesting tags other than other snippets could get complicated)

**Comment by salsakran** [comment]
Good points. Nvm. 

+1 on SQL snippets in some capacity for sure. Ideally in a way that blurs the lines between our GUI queries and SQL, vs create a completely different system for native queries.

**Comment by that0n3guy** [comment]
I should have put this in the op, but here is the docs for Periscope's implementation: https://doc.periscopedata.com/doc/snippets

**Comment by bedeoverend** [comment]
Has there been any update or movement on this? It would be invaluable for us - seeing a lot of SQL duplication.

**Comment by wvengen** [comment]
What about using an existing query as a table, similar to the functionality using the Metabase query interface? This could be implemented as a subquery or [PostgreSQL CTE](https://www.postgresql.org/docs/9.0/static/queries-with.html), and be something like `SELECT * FROM {{card:152}}`. Obviously, this would only work with queries from the same database.

**Comment by ConradIrwin** [comment]
I would much prefer a simple textual substitution, more like variables++, as it can be used for a wider variety of tasks:

```
SELECT * FROM users WHERE {{snippet:user_is_paying}}

WITH paying_users AS ({{snippet:paying_users}})
SELECT * FROM paying_users
```

It would be amazing if they supported arguments, but I do appreciate that that way lies madness:

```
SELECT {{snippet:time_in_pst|created_at}} FROM users
```

I don't think we need to worry too much about the multiple database case (I run with MySQL, Postgres and BigQuery; but usually the snippets will be relevant only to one data source, and if that's not the case I can name my snippets appropriately)

**Comment by mazameli** [comment]
I know that this issue was opened years ago, but for those of you who are keeping tabs on it, we're working on this feature and want to get opinions on one question:

Would you want any user with SQL editor access to be able to create snippets and edit existing ones? Or would you only want _administrators_ to be able to create and edit snippets?

**Comment by ConradIrwin** [comment]
I'd love it for anyone to be able to create snippets – that said, we don't use permissions extensively here yet.

With the new feature around being able to reference existing queries in new queries, some of the need here is solved, though it'd be amazing to be able to pass arguments to those queries.

**Comment by ferarnoled** [comment]
> I know that this issue was opened years ago, but for those of you who are keeping tabs on it, we're working on this feature and want to get opinions on one question:
> 
> Would you want any user with SQL editor access to be able to create snippets and edit existing ones? Or would you only want _administrators_ to be able to create and edit snippets?

I think anyone should with SQL access should be able to create and use. Only administrators can edit. Feels like the safest approach without changing the permission system
