### ISSUE TITLE
Ease the process for upgrading instances from Open Source to Enterprise in Elastic Beanstalk

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18290]
**Is your feature request related to a problem? Please describe.**
The current way of going from Open Source to Enterprise in Elastic Beanstalk is by downloading a specific bundle that we don't expose (https://downloads.metabase.com/enterprise/v1.xx.x/metabase-aws-eb.zip). Simplifying this process might provide Enterprise testers an easier experience

**Describe the solution you'd like**
An automated link for posting this in our documentation, the same way we have the open source one

**Describe alternatives you've considered**
Hardcoding stuff :(

**How important is this feature to you?**
Important

**Additional context**
N/A

**Comment by cbalusek** [comment]
@nllho  - can you follow up on this?

**Comment by SohrabZ** [comment]
I have to use this link format here every time there is a new update. Can we at least change the link to update to a more helpful document?

Document: https://www.metabase.com/docs/latest/operations-guide/upgrading-metabase.html

Update screen: ![Screen Shot 2022-06-28 at 11 23 22 AM](https://user-images.githubusercontent.com/1913404/176255278-3662748e-aad4-40de-b2f1-e17c41abb949.png)

**Comment by paoliniluis** [comment]
We have deprecated shipping the Beanstalk artifacts, so this is no longer relevant. Users will have to build their own beanstalk artifacts from now on
