### ISSUE TITLE
Support SCIM for SSO methods including SAML and others

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18319]
**Is your feature request related to a problem? Please describe.**
Cross Identity Management will let enterprise users provision and deprovision users automatically when tied to their IdP. The only way to do this is by doing API calls programatically to Metabase

**Describe the solution you'd like**
Support SCIM integration

**Describe alternatives you've considered**
Manual API calls to the server

**How important is this feature to you?**
Important for enterprise users who want to keep a consistent user list everywhere

**Additional context**
https://developer.okta.com/docs/concepts/scim/

**Comment by isaacaumni** [comment]
+1 this becomes very important, especially where it concerns role-based access controls.

**Comment by ronrevels** [comment]
We use Entra ID (Azure AD) and this is very important to manage application authorization automatically.
