### ISSUE TITLE
Data reference lists "Saved Questions" as a database

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#18331]
**Describe the bug**
Data reference lists "Saved Questions" as a database

**Logs**
N/A

**To Reproduce**
_Start with having some questions already saved_
1. Go to `/reference/databases`
2. Note that there is a "Sample Dataset", but also "Saved Questions"
![image](https://user-images.githubusercontent.com/31325167/136464189-f8198f17-67c5-49b9-902c-8bb308798494.png)
3. Click on "Saved Questions"
![image](https://user-images.githubusercontent.com/31325167/136464306-bf14c992-bb5c-4753-945b-f6669b2239de.png)
4. You can click on the "Edit" but none of the metadata you enter cannot be saved/preserved
5. "Tables in Saved Questions" is pointless and (obviously) leads to am

**Expected behavior**
"Saved Questions" shouldn't be displayed as a database in the data reference.

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/wbu8oXEO/3a5e1fbc-4d4b-44e4-b542-6abdc946a792.gif?source=viewer&v=ea981f83bd296a28a0566f1bffeb7609)

**Information about your Metabase Installation:**
local dev, `master`, H2, Sample Dataset

**Severity**
P3

**Additional context**
Tested as back as 37.9 and it was still there.

**Comment by escherize** [comment]
I am actually unable to reproduce this one, I have 2 saved questions, and when I head to http://localhost:3000/reference/databases I don't see a "Saved Questions" list item. Maybe it's been fixed?

**Comment by flamber** [comment]
@escherize This might be more tricky than what it looks like. I'm unsure if it might just be frontend or both.
You have to view the Data selector, and then it will show it - same problem happens in Admin > Permissions > Data > Databases

https://user-images.githubusercontent.com/1447303/164305149-f205684e-b8bc-4cf2-9ed1-694053c71ce5.mp4

**Comment by dpsutton** [comment]
I think we are missing some repro steps here.

I'm running `MB_JETTY_PORT=3006 java -jar ~/projects/work/jars/0.37.9.jar` so 37.9, a version you confirmed exhibits the behavior. I saved one of the xrays to have some dashboards and saved questions. When making a new question, I see i have saved questions as the potential query sources:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/6377293/164306739-9018a886-109c-4ce1-8046-e4803ace9759.png">


And I dont see them in the reference section 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/6377293/164306861-f4d9d93f-549c-4ab0-876c-858a030ddf26.png">

BUT: If I go through some specific steps I can recreate this, so it makes me think this is a FE caching issue:
- ask a question
- simple question
- choose saved questions
- click explore data
- click "Learn about our data"

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/6377293/164307103-9aefaf90-c589-4706-9134-a0cc0c96c1f7.png">


So what I think is going on:
- we treat saved questions as "virtual databases"
- the FE caches the list of databases 
- for query sources we include these
- for "Learn about our data" we should not include saved questions virtual database
- it uses the cached value and doesn't think to either:
  - refetch without virtual databases
  - just filter the virtual database

`GET /api/databases&saved=true` returns one db `{"name":"Saved Questions","id":-1337,"features":["basic-aggregations"],"is_saved_questions":true}`

**Comment by escherize** [comment]
Just a guess, but I have a vague suspicion that the cache used to keep track of the databases does not respect the query params. On a fresh load the page makes a request to `/api/database`, but loading the questions makes a request to `/api/database?saved=true`, which contains "Saved Questions".
