### ISSUE TITLE
Support filtering against the values of another field (multiple fields in the same filter)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1834]
e.g. 

> Give me rows where the values of Field 10 are different from the values of Field 11 

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mazameli** [comment]
This would definitely be useful. Would be cool if, after selecting the initial field and the logic operator, you could just type a field name in the input box.

**Comment by camsaul** [comment]
@mazameli I think that could get confusing, 

e.g. if you had a field named `status` and a field named `archived` and then you wanted to find rows where the `status` is literally `archived` (`status = archived`) or something like that

**Comment by mazameli** [comment]
Yeah, with non-numeric fields you wouldn't want to have operators like `>` presented. You'd want string comparison operators instead, like `Is equal to`, `Begins with`, `Ends with`, `Contains` etc.

**Comment by lp-lima** [comment]
I'm pretty sure this would be quite useful, but I'm not sure enough people will see this issue to upvote it so it can be done any time soon :(

**Comment by takaaptech** [comment]
Uo Vote for this feature!
In my case, I need from_date and to_date apply for 2 tables that going to join
In the dashboard editor, I can only map filter with one value only

**Comment by sbelak** [comment]
This is already possible with custom filter expressions. I think that's enough. Thoughts @mazameli ?

**Comment by Raiduster** [comment]
I need it to!

**Comment by flamber** [comment]
Closing, since this has been possible with Custom Expressions since 0.35:
https://www.metabase.com/blog/0.35/index.html
https://www.metabase.com/learn/questions/custom-expressions.html
https://www.metabase.com/docs/latest/users-guide/expressions.html
