### ISSUE TITLE
Slack renders of table results in 0.41.0 include too much right padding

### ISSUE THREAD

**Issue by lukeman** [metabase/metabase#18361]
**Describe the bug**
Pulses with table results render as a very wide image when sent to Slack (static width of 1200px?). Slack further scales this up/down to ~360px when displayed in a message, which makes scanning the contents near impossible without zooming on the attachment. On 0.40.4 our pulses rendered dynamically around the 300px–600px range.

**To Reproduce**
1. Create a card that selects 3–5 columns
2. Add that card to a new dashboard
3. Create a dashboard subscription that sends to Slack
4. Click the 'Send now' button

**Expected behavior**
Tables should try to render at an appropriate width so the text is legible without zooming the image.

**Screenshots**
Full-size render:
![image-5](https://user-images.githubusercontent.com/13008/136612410-7afefeb1-5c87-40f3-a7ee-fd37427b72cf.png)

Further scaled down version in Slack (pretty much illegible until you click through):
![Screen Shot 2021-10-08 at 4 26 42 PM](https://user-images.githubusercontent.com/13008/136621026-e2101c68-bddb-4b40-98ea-8882e040aa32.png)

**Information about your Metabase Installation:**

- Your browser and the version: Latest Safari
- Your operating system: macOS Big Sur
- Your databases: BigQuery
- Metabase version: 0.41.0
- Metabase hosting environment: Self-hosted docker on nomad
- Metabase internal database: Postgres

**Severity**
P2/P3, since it's limited to Slack (important to me since people will have to take an additional action to be able to see the content of alerts, but maybe not as much generally) and technically things still work.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by noahmoss** [comment]
Hmm, I thought this would be an easy fix but I'm not sure if it is. This seems to be a side effect of the SVG rendering engine change in https://github.com/metabase/metabase/pull/15781. The width of every png is defined as 1200 [here](https://github.com/metabase/metabase/blob/05d6aba5c4c47df4720a102ff254824eefaec7da/src/metabase/pulse.clj#L168-L170), but prior to that PR it seems like the width was still being statically defined, but we didn't have the excess whitespace issue.

**Comment by alpertungir** [comment]
So, is there any idea to fix that ?
