### ISSUE TITLE
Reduce payloads on the collection, and data permissions graphs when changing permissions

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18377]
**Describe the bug**
We're sending the whole graph when changing permissions, but we should send only what the user changed.

**Logs**
None

**To Reproduce**
1) create one collection (let's say you have 2 collections total)
2) change one permission to a group in 1 collection
3) see the entire graph being sent over the wire

**Expected behavior**
send only the changes on the payload, which works
![image](https://user-images.githubusercontent.com/1711649/136675525-5ca5903c-ab4f-4d35-b8c6-ae2f59b3ff1d.png)

**Screenshots**
In this example I just changed "all users" permissions from "Curate" to "View"
![image](https://user-images.githubusercontent.com/1711649/136675476-4f2033dd-7284-4026-848d-3dbc0c588a07.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu LTS latest
- Your databases: Sample dataset
- Metabase version: .41
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
None

**Additional context**
Reported by a trialer

**Comment by escherize** [comment]
- [ ] verify that it works
- [ ] add some tests
- [ ] change doc strings to support

**Comment by escherize** [comment]
The backend piece of this is closed by #27665. 

When we send only what the user changed, the rest of the permission graph will be unchanged for `PUT`s on the `/api/permissions/graph` and `/api/collections/graph` routes.

To close this issue, a frontend change to only send updated parts of the graph is needed.
