### ISSUE TITLE
Columns missing from exports, when viz settings are using older field dimensions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18382]
**Describe the bug**
Columns missing from exports, when viz settings are using older field dimensions.
@noahmoss you can likely get a little help from @jeff303, who had so much fun with field dimensions during Serialization fixes.

**To Reproduce**
1. Create a question in older versions of Metabase and modify the columns, so it creates visualization_settings, which uses the old-style field dimensions `field-literal` or `field-id`
2. On 0.41, try to export - the columns will be missing for the export.

Example the following is slimmed down Products, which should return ID, Category and Rating, which it does in the UI, but when exporting, it's only returning Rating.
![image](https://user-images.githubusercontent.com/1447303/136784472-9e553ba4-66b4-4780-a49c-79b80d9f39a6.png)

Can be tested on internal instance by going to `/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6M30sImRhdGFiYXNlIjoxfSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5jb2x1bW5zIjpbeyJuYW1lIjoiSUQiLCJmaWVsZFJlZiI6WyJmaWVsZC1pZCIsMixudWxsXSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiQ0FURUdPUlkiLCJmaWVsZFJlZiI6WyJmaWVsZC1saXRlcmFsIiwiQ0FURUdPUlkiLCJ0eXBlL1RleHQiXSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiUkFUSU5HIiwiZmllbGRSZWYiOlsiZmllbGQiLDI3LG51bGxdLCJlbmFibGVkIjp0cnVlfV19fQ==`
```
{
  "dataset_query": {
    "type": "query",
    "query": {
      "source-table": 3
    },
    "database": 1
  },
  "display": "table",
  "visualization_settings": {
    "table.columns": [
      {
        "name": "ID",
        "fieldRef": [
          "field-id",
          2,
          null
        ],
        "enabled": true
      },
      {
        "name": "CATEGORY",
        "fieldRef": [
          "field-literal",
          "CATEGORY",
          "type/Text"
        ],
        "enabled": true
      },
      {
        "name": "RATING",
        "fieldRef": [
          "field",
          27,
          null
        ],
        "enabled": true
      }
    ]
  }
}
```

**Information about your Metabase Installation:**
0.41.0

**Additional context**
Got enough details via the forum: https://discourse.metabase.com/t/missing-columns-in-xlsx-attachments-and-downloads/17064
Also reported in #18181 and #18342, but not with enough details.

**Comment by noahmoss** [comment]
@flamber Do you know what the easiest way to repro this on a local instance would be? I'm assuming I could set up an old version of MB, create a question, and then migrate it to 41? (What version would I need to use?)
