### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by danieljacobarcher** [metabase/metabase#1840]
Getting a few console errors:

`Refused to load the script 'https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' www.google-analytics.com *.googleapis.com *.gstatic.com js.intercomcdn.com *.intercom.io ".`

`ReferenceError: Can't find variable: WebFont`

Also getting errors related to google maps api for the same Content Security Policy directive.

**Comment by tlrobinson** [comment]
This is related to #1675 and should be fixed in master, however it didn't make it into the 0.14 release, sorry.

**Comment by camsaul** [comment]
@tlrobinson this is fixed by #1803 right?

**Comment by danieljacobarcher** [comment]
Yes, I can confirm it works again.
