### ISSUE TITLE
Navigation bar on tiny mobile is getting cut

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18413]
**Describe the bug**
When navigating Metabase from a mobile browser, the interface gets cut on the right side of the page

**Logs**
NA

**To Reproduce**
1) Start a Metabase instance and navigate it from a mobile browser

**Expected behavior**
See the UI correctly (no cuts)

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/136959729-a8b08f60-5ca2-48f6-861c-d8a886037dd8.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest with Iphone 6/7/8 dimensions
- Your operating system: Ubuntu LTS latest
- Your databases: None
- Metabase version: 40.5
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic

**Additional context**
None

**Comment by brunobergher** [comment]
Not true anymore. We have a lot to improve in terms of mobile UI, but this doesn't happen anymore (we even have a collapsed hamburger menu).
