### ISSUE TITLE
Toggle in mobile when setting up Metabase gets over text

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18414]
**Describe the bug**
When setting up Metabase, the toggle for choosing sending anonymous data is very narrow and seems to get over the text

**Logs**
NA

**To Reproduce**
1) set up Metabase and enter from a mobile browser or enter with any browser and change the dimensions

**Expected behavior**
See the toggle correctly

**Screenshots**
![toggle_mobile](https://user-images.githubusercontent.com/1711649/136960989-3de490c0-5f99-46a4-8729-7945dff9826b.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Brave Latest with iPhone 6/7/8 dimensions
- Your operating system: Ubuntu LTS latest
- Your databases: None
- Metabase version: 40.5
- Metabase hosting environment: Docker
- Metabase internal database: Sample

**Severity**
Cosmetic

**Additional context**
NA

**Comment by enolal826** [comment]
@paoliniluis This PR should fix it https://github.com/metabase/metabase/pull/18871
