### ISSUE TITLE
Last Name field in Setup in Mobile is off the screen

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18411]
**Describe the bug**
When you set up Metabase in a Mobile device, the last name field is off screen

**Logs**
NA

**To Reproduce**
1) set up a new Metabase instance and access it through a mobile device to set it up

**Expected behavior**
Last Name should be under First Name

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/136953828-264cd5ce-fe5e-42bc-9227-27be6ed6d032.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave Latest (with iphone 6/7/8 dimension)
- Your operating system: Ubuntu LTS latest
- Your databases: None
- Metabase version: 40.5
- Metabase hosting environment: Docker
- Metabase internal database: Sample

**Severity**
Cosmetic, but it would be difficult to set up an instance on mobile

**Additional context**
None

**Comment by enolal826** [comment]
@paoliniluis This PR should fix it https://github.com/metabase/metabase/pull/18871
