### ISSUE TITLE
change "state map" visualization title to "US State map" (or similar)

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1842]
Since we're unfortunately a bit US centric right now with our mapping we should more accurately reflect this in the title for clarity. Maybe eventually we might move to a simple "map" option that allows for varying degrees of fidelity based on the data.

**Comment by tlrobinson** [comment]
The United States State map?

**Comment by kdoh** [comment]
@tlrobinson I had the idea while i was at the ATM machine eating a cheese quesadilla.

**Comment by camsaul** [comment]
alternatively we can auto-detect what country we're dealing with and show a map of Mexico / Germany / etc. when appropriate

#magic

**Comment by tlrobinson** [comment]
Yeah, I think ideally we'd just have a single visualization type (the technical term for these is "choropleth map", not sure if we have a better name for it), and attempt to autodetect the region, but have a visualization setting to allow the user to override or even upload their own.

**Comment by kdoh** [comment]
@cam / @tom Yup, thats definitely the direction I'd like to see mapping move.

**Comment by tlrobinson** [comment]
This was resolved in v0.15
