### ISSUE TITLE
Dashboards that overflow available vertical height overlap the title/toolbar

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1843]
![screenshot 2016-01-28 21 38 48](https://cloud.githubusercontent.com/assets/18193/12668035/888c6c60-c607-11e5-8970-56fe8e26e496.png)

**Comment by tlrobinson** [comment]
This will likely be resolved when we revamp dashboards.

**Comment by tlrobinson** [comment]
This appears to be due to a change in Chrome 48.0.2564.97

@metabase/core-developers Could you check to see if this happening for you, and what Chrome version you're using?

**Comment by kdoh** [comment]
@tlrobinson Was just able to repro this as well. 🤔

**Comment by tlrobinson** [comment]
https://code.google.com/p/chromium/issues/detail?id=582212

**Comment by agilliland** [comment]
It looks as if there were merges on fixes for the above reported Chrome issues, i'm curious to see if the stable channel of Chrome gets a release in the next day or two that will completely fix this.

**Comment by tlrobinson** [comment]
Looks like it depends on whether it makes it into a 48 point release, otherwise 49 is estimated to be released in March (https://www.chromium.org/developers/calendar).
