### ISSUE TITLE
Improve our JWT documentation

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18452]
**Is your feature request related to a problem? Please describe.**
We should improve our JWT documentation specifying that we use the Authorization code flow along with the type of keys we use (https://developer.okta.com/docs/concepts/oauth-openid/#authorization-code-flow)

**How important is this feature to you?**
A good idea that some customers/trialers sent us

**Comment by Vossler756** [comment]
specifically it would be very helpful to know up front that Metabase only supports PKCE + Auth Code Flow:

https://developer.okta.com/docs/concepts/oauth-openid/#authorization-code-flow-with-pkce
