### ISSUE TITLE
Trend chart do not show period text on smaller viewports (like Embedding)

### ISSUE THREAD

**Issue by tomasrasymas** [metabase/metabase#18453]
**Describe the bug**
When the trend chart is embedded period text is not displayed.

**Logs**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-Ubuntu-0ubuntu2.20.04",
    "os.name": "Linux",
    "os.version": "5.4.0",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-10-06",
      "tag": "v0.41.0",
      "branch": "release-x.41.x",
      "hash": "c529fe2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a trend chart and save it
2. Go to `Sharing`->`Enable sharing` 
3. Copy `Public embed` content
4. Paste the content into webserver
5. View web page and not period text is displayed 

**Expected behavior**
See same results when viewed from external site and from metabase

**Screenshots**
On metabase period text is shown.
![image](https://user-images.githubusercontent.com/20923703/137281644-8e62dbe1-0307-405b-bbf6-c8fa4c8d1664.png)
On website that embeds the chart period text is not shown.
![image](https://user-images.githubusercontent.com/20923703/137281748-f503e876-b53d-454e-afc2-e5bcbadbef96.png)

**Severity**
It is annoying, cause makes my charts less readable and understandable.

**Comment by flamber** [comment]
Very related to #10786
