### ISSUE TITLE
Caching on 0.41.0 caches results for very long time (does not respect settings defined)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18458]
**Describe the bug**
Caching on 0.41.0 caches results for very long time (does not respect settings defined)

Currently the only workaround is to disable caching.

**To Reproduce**
1. Admin > Settings > Caching > Duration=`4`, Multiplier=`2`
2. Native query > `select current_timestamp, pg_sleep(5)` - run query, save as "Q1" and add to dashboard
3. On dashboard, refresh a couple of times (issue #13262), until the card loads instantly
4. Now wait 10 seconds and refresh the dashboard, where new results are expected. But the cache is still displayed.
5. Looking at the `POST /api/card/123/query`, it contains a `cache_ttl: 36000` (10 hours).

**Information about your Metabase Installation:**
Tested 0.41.0 and master with EE features.

**Comment by Gruek** [comment]
Getting similar issues since 0.41. Queries that only take 1 second to execute have been cached for 5 days.
Even after manually refreshing the query, it doesn't update the chart on the dashboard
