### ISSUE TITLE
Better approach for column ordering in exports

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#18450]
The logic in `export-column-order` in `metabase.query-processor.streaming` has become super complex and brittle, and has been the source of numerous export-related regressions. We should figure out a better, more reliable way to handle column ordering.

[Here is the current function](https://github.com/metabase/metabase/blob/1010ecf9d60417b56dbb2d19ce9535d37e619959/src/metabase/query_processor/streaming.clj#L56), for reference.

### The current approach

`export-column-order` is a function that is run immediately before we stream query result to an XLSX, JSON or CSV file. It takes two arguments: `cols`, the metadata for the columns in the query result, and `table-columns`, which is pulled out of the viz settings for the query. Viz settings are either passed from the frontend for unsaved cards, or pulled from the DB for saved cards.

`cols` contains all of the columns in the table in their original order. `table-columns` lists them in their new order, if the user has reordered them, and also includes a key `table-column-enabled` which indicates whether the column is hidden.

The output is a list of indices that map the enabled columns in `table-columns` to their original positions in `cols`. This allows us to reorder the data in each result row when generating the export, since the data is passed to the streaming code in the same order as in `cols`.

We create this list of indices by reducing over `cols` and building up a map from column -> index. Then we map over `table-columns` and look up each enabled column in the map.

### The current problem

The problem is reliably correlating entries in `table-columns` with entries in `cols`. Each entry in `table-columns` contains a `:field_ref` key, which _should_ be able to be correlated with the `:field-ref` keys in `cols`.

The main issue is that viz settings are passed down from the frontend for unsaved questions, so they have to be parsed from JSON into Clojure. This means that the resulting `:field_ref` data structure might not be exactly the same as the equivalent field in `cols` -- in particular, strings are not converted to keywords. But we can't convert them all to keywords indiscriminately, since field names (and maybe other things?) should be left as strings. I don't think there's an existing utility to convert a JSON field ref to Clojure since the conversion is usually happening in the other direction.

Instead my approach has been to try to construct a more minimal key based on the field ref to uniquely identify each field. But this has required adding code to handle a bunch of different cases and has resulted in several regressions where a fields are dropped because this comparison logic failed. Some of these cases include aggregated fields, native queries w/reordered fields, and self-joined fields that have `:join-alias` in their field ref metadata.

### Questions
1. Is there a reliable way (that I'm not aware of) to convert a JSON field ref back to Clojure so that is it equivalent to field refs in `cols`? If this were possible, would these comparisons be reliable?
2. Is there any other way to order columns in exports that would bypass this whole mess?

This is technically tech debt but I feel like it's a ~P1.5 since the regression potential here will remain really high until we can figure out a better approach. This was essentially the root cause of  #18440, #18382, #18181, and maybe others that I'm forgetting about.

**Comment by flamber** [comment]
Related #17753

**Comment by camsaul** [comment]
> I don't think there's an existing utility to convert a JSON field ref to Clojure since the conversion is usually happening in the other direction.
>
> Is there a reliable way (that I'm not aware of) to convert a JSON field ref back to Clojure so that is it equivalent to field refs in `cols?` If this were possible, would these comparisons be reliable?

We do have some logic to normalize MBQL clauses to their "canonical" Clojure representation, you could leverage that stuff after parsing the JSON. They _should_ be reliable, I think. Otherwise I'm not sure how the frontend would be using them to do the reordering on that side.

> Is there any other way to order columns in exports that would bypass this whole mess?

Not that I can think off the top of my head. Ideally I think column order would be something we'd specify in the MBQL rather viz settings, but we can't currently do that 100% since `:breakout` and `:aggregation` columns are always returned first
