### ISSUE TITLE
Global search results priority can be confusing

### ISSUE THREAD

**Issue by lubikx** [metabase/metabase#18465]
**Describe the bug**
Sorting of found questions/tables/dashboards changed and now it usually doesn't make sense and users need to "think" to actually locate the correct result. In the past, dashboards were always the first. Now they are located somewhere even after data source table names.

**Logs**
No logs necessary.

**To Reproduce**
1. Search for example for string: extern
2. Dashboard with extern contained in the name is shown on 9. place, in the past it was 1. place.

**Expected behavior**
Dashboards are the main thing (containing the most information), they should always be first if any part of the name matches searched string.
Questions should be after them.
Data source table names should always be last - usually no one is searching for those in search.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: Windows 10
- Your databases: MariaDB
- Metabase version: 0.41.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Annoying issue that shows itself when anyone is search for the correct dashboard/question.

**Comment by flamber** [comment]
Hi @lubikx 
Global search was introduced in 0.39: https://www.metabase.com/blog/Metabase-0.39/index.html
There's an algorithm, which prioritizes the results based on what the search term, but also how viewed an object is.
If you visit that dashboard several times, then it will get a higher priority.
