### ISSUE TITLE
Display metric name instead of underlying aggregation name in column header

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1851]
![screenshot 2016-01-29 15 15 11](https://cloud.githubusercontent.com/assets/18193/12690840/3fd6f852-c69b-11e5-8864-63b05de2f4a1.png)

**Comment by salsakran** [comment]
is this a front end or backend concern? I'd say backend, since I'd prefer CSV downloads had the right column heading as well.

**Comment by camsaul** [comment]
This is a backend thing. But this is a pretty involved change a lot of code will need to change

**Comment by salsakran** [comment]
point of clarification: this refers *only* to situations where the aggregation clause is a saved metric. #2725  is the more general case.

**Comment by camsaul** [comment]
Implemented by #10251
