### ISSUE TITLE
Renamed columns in CSV/JSON exports

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#18572]
Renamed columns currently only work for XLSX exports, not for CSV or JSON exports.

There's a bit of a product question here of what to include for each format. There's an old comment [here](https://github.com/metabase/metabase/blob/3617ebd92fba8744ffe66b9612844d7838081c95/src/metabase/query_processor/streaming/json.clj#L28-L29) that posits that JSON output will be likely parsed programmatically, so we should actually keep the original DB column names in the output. Another question is whether we should include currency symbols in column names. These questions are similar to the questions in #17422 about what formatting we should apply.

#18494 should be unskipped once this is fixed for CSVs.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by brunobergher** [comment]
It seems to me that CSVs should follow the same renaming as Excel, since they can be parsed as human strings (different form JSON).

**Comment by paoliniluis** [comment]
@markbastian I added the 49 tag again, is that ok?
