### ISSUE TITLE
allow joining tables on non-primary keys

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1857]
From a discussion in http://discourse.metabase.com/t/foreign-keys/183/4

It would be useful to be able to join tables on a non primary key. Specifically, for two tables: 
Sessions and Transactions with a user_id in each, provide the equivalent of 

```
select platform, count(*)
from sessions join transactions
on sessions.user_id = transactions.user_id
group by platform
```

**Comment by adamthehutt** [comment]
+1

**Comment by marcoruggine** [comment]
+1!

**Comment by Poggen** [comment]
+1

**Comment by captainbob** [comment]
+1!

**Comment by salsakran** [comment]
this is possible in our new notebook mode.
