### ISSUE TITLE
Remapped columns do not use renamed titles in XLSX exports

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#18573]
**Describe the bug**
If a column uses remapped values, and is renamed, an XLSX export will not use the new name 

**To Reproduce**
1. In the data model settings, change a column to use remapped values
2. In a question using a table visualization, rename the remapped column
3. Export as XLSX

**Expected behavior**
Column name should match what is shown in Metabase exactly

**Information about your Metabase Installation:**
Current master

**Comment by nemanjaglumac** [comment]
Related?
https://github.com/metabase/metabase/issues/18440

**Comment by flamber** [comment]
@nemanjaglumac A tiny bit, but that issue was about dropped columns (P1), while this is the column title. It was discussed during fixing of that issue, where a couple of issues were created - see PR #18490.
