### ISSUE TITLE
Names of schemas or namespaces can overflow cards in /Browse

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#18581]
Schemas or namespaces with long names (without spaces I think?) are overflowing on /browse. You can see this in the "Splitgraph" database we have up on our Stats instance currently.

This is causing the Reference/book and X-ray/bolt action icons to get hidden or displayed incorrectly

We should ellipsify titles if they overflow in this context, with the full name visible on hover.

![image](https://user-images.githubusercontent.com/2223916/138174307-2a56bf1f-2399-4038-9deb-0b6d389f67a1.png)

**Comment by gusaiani** [comment]
@flamber, 

1. do you know how to seed or populate so that I can see this layout locally?

2. all the links in stats lead to 404ish urls…do you know anything about that Splitgraph?

**Comment by flamber** [comment]
@gusaiani 
1. Any database, which supports more than single schema (Postgres is likely easiest).
2. That's a separate issue, which is more complicated than it looks #15454
