### ISSUE TITLE
Pivot Table can be almost impossible to use, when darker Whitelabel primary color is used

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18615]
**Describe the bug**
Pivot Table can be almost impossible to use, when darker Whitelabel primary color is used.

**To Reproduce**
1. Admin > Settings > Whitelabel - set primary color to something dark, like `#420000`
2. Custom question > Sample Dataset > Orders - Count and Sum of Total grouped by CreatedAt:Year, People.Source and Products.Category
![image](https://user-images.githubusercontent.com/1447303/138439411-e9d1c08d-62ca-4f80-a6f8-77b1f079865c.png)
3. Change visualization to Pivot Table
![image](https://user-images.githubusercontent.com/1447303/138439514-7766aaf5-72f0-468a-a564-aeed4c214746.png)

**Expected behavior**
Either don't use Whitelabel coloring on Pivot Table, or should be a very light tone of the primary color.
![image](https://user-images.githubusercontent.com/1447303/138440041-567be7b3-e5b6-4ad2-a925-a4e3f4964410.png)

**Information about your Metabase Installation:**
Tested 1.39.4 thru 1.41.1

**Comment by brunobergher** [comment]
Yeah, let's just use white as the background. The customization shouldn't leak through here.
