### ISSUE TITLE
Dashboard crashes (osx client)

### ISSUE THREAD

**Issue by grantstudyblue** [metabase/metabase#1861]
When trying to load a dashboard with 6 graphs it continuously crashes before I can take any action on it. The crashes started occurring after I added the 6th graph. 

I'm running OS El Capitan
Metabase version v0.14.0

**Comment by camsaul** [comment]
@agilliland Why isn't this a bug?

**Comment by agilliland** [comment]
That was actually done by the automation bot, which is currently using one of my GH api tokens :speak_no_evil: 

It looks like the webhook probably fired before the labels were set on the issue.  or some thing problem.  in any case.  just added the labels back.

**Comment by camsaul** [comment]
@grantstudyblue I'm unable to reproduce this. Can you give me a little more information? Are the queries behind the graphs complex or do they otherwise take a long time to run?

**Comment by grantstudyblue** [comment]
@camsaul The queries are not complex and were running perfectly until I added the 6th graph. One of the dashboards is now working but one is still crashing. Is there a way to delete a single dashboard?

**Comment by camsaul** [comment]
@grantstudyblue If you navigate to the dashboard and click the pencil icon you'll see an option to delete the dashboard

**Comment by grantstudyblue** [comment]
@camsaul The dashboard crashes, and takes me back to the home screen before I can click the pencil icon

**Comment by tlrobinson** [comment]
@grantstudyblue Are you seeing any errors in the JavaScript console of the browser's web inspector?

**Comment by camsaul** [comment]
@tlrobinson there's no web inspector on the Mac app :crying_cat_face: 

But that's a good point. @grantstudyblue if you click the link button in the upper-right corner of the Metabase app it will copy a link to the current page to your clipboard. Then you can paste that link into a browser on your computer and look at it there

**Comment by grantstudyblue** [comment]
@camsaul when I load it in the browser the dashboards load without a problem. I was able to update them, and delete the one that was causing the problem. Everything is now working as expected in the app.

**Comment by camsaul** [comment]
Closing since @grantstudyblue was able to work around this
