### ISSUE TITLE
Textbox markdown links on images difficult to click

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18641]
**Describe the bug**
Textbox markdown links on images difficult to click. Regression since 0.40.0

**To Reproduce**
1. Go to dashboard and add Textbox with the following and save dashboard
`[![](https://www.metabase.com/images/twitter/default-share.png)](/question/1)`
2. Try clicking the image - the link is only available in the bottom part
![image](https://user-images.githubusercontent.com/1447303/138668137-000a63bf-dd8e-4efe-bcaa-a58198db380b.png)

**Expected behavior**
Change `.text-card-markdown a {}` to `display: inline-block;`, so it allows wrapping links around images without causing block element. Don't think there would be any problems with doing that.

**Information about your Metabase Installation:**
Tested 0.39.5 thru 0.41.1 - regression since 0.40.0

**Comment by Narayanan-commits** [comment]
@flamber do you know when we will the 0.41.2 released?

**Comment by flamber** [comment]
@Narayanan-commits Hopefully today, but click the milestone, which has expected (not set in stone) release dates attached.
https://github.com/metabase/metabase/milestone/144
