### ISSUE TITLE
Provide progress on initial data sync

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#18675]
**Links**
- product doc: https://www.notion.so/metabase/Provide-progress-on-initial-data-sync-16af8e79312a45ecb715d8e58801c52b?d=b4724d1a2911424e992f3beb9d27a846#1d8f0cf533c1481d81a9e33021143e76

**Implementation Plan**

API changes:

1. Add `initial_sync` flag to `Databases` and `Tables` returned from:
- `/api/database`
- `/api/database/:dbId/metadata`
- `/api/database/:dbId/schema/:schemaName`

2. Add `initial_sync` flag to search endpoints:
- `/api/activity/recent_views` - add `initial_sync` to `model_object` when `model` is `table` or `database`.
- `/api/search` - add `initial_sync` to `data` items returned for `table` and `database`

3. Add `creator` to `Database` returned from:
- `/api/database`

4. Add `enable-database-syncing-modal` setting
- The default value should be `false` for existing instances, `true` otherwise. 
- It should be possible to change this setting from the FE.

**Comment by calherries** [comment]
It looks like the [native query reference pane](https://www.notion.so/metabase/Provide-progress-on-initial-database-sync-16af8e79312a45ecb715d8e58801c52b?pvs=4#5d67f984521843c4818e17a37719a111) part of the spec was never implemented.

I checked out the commit (b99682b) from the last PR that mentioned this epic (https://github.com/metabase/metabase/pull/19925), and tested it out. 

I set `metabase_database.initial_sync_status = "incomplete"` and `metabase_table.initial_sync_status = "incomplete"` but the database and table appeared as normal, and were clickable:
![image](https://github.com/metabase/metabase/assets/39073188/b71364b1-1e9a-4cfc-ac95-1b60b8d6ee7d)

This is the case on master as well.
