### ISSUE TITLE
mac client no longer start

### ISSUE THREAD

**Issue by hansyson** [metabase/metabase#1867]
downloaded the latest mac client on my imac - el capitan os 10.11.3 - 
this no longer works!  symbol just keeps turning -  i deleted and redownloaded it to the same.

**Comment by agilliland** [comment]
Hi @hansyson , do you mind taking a quick look in `/Library/Application Support/Metabase/` and letting me know what files you see there?  You can do that when the Metabase app is closed.

**Comment by camsaul** [comment]
@hansyson @agilliland It's `~/Library/Application Support/Metabase/` (in your home directory)

**Comment by hansyson** [comment]
yup i see a directory there

On Thu, Feb 4, 2016 at 6:52 PM, Cam Saül <notifications@github.com> wrote:

> @hansyson <https://github.com/hansyson> @agilliland
> <https://github.com/agilliland> It's ~/Library/Application
> Support/Metabase/ (in your home directory)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metabase/metabase/issues/1867#issuecomment-180108984>.
>



-- 

*Hans Son*

Data Engineer Lead

W E D D I N G W I R E

301 231 9473 x ext 2364

hson@weddingwire.com <brian@weddingwire.com>

website <http://weddingwire.com/> • blog <http://blog.weddingwire.com/> •
facebook <https://www.facebook.com/WeddingWire> • twitter
<https://twitter.com/WeddingWire>

**Comment by camsaul** [comment]
What files are in it?

**Comment by hansyson** [comment]
a .db file..  deleting it helped

On Fri, Feb 5, 2016 at 1:05 PM, Cam Saül <notifications@github.com> wrote:

> What files are in it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metabase/metabase/issues/1867#issuecomment-180473106>.
>



-- 

*Hans Son*

Data Engineer Lead

W E D D I N G W I R E

301 231 9473 x ext 2364

hson@weddingwire.com <brian@weddingwire.com>

website <http://weddingwire.com/> • blog <http://blog.weddingwire.com/> •
facebook <https://www.facebook.com/WeddingWire> • twitter
<https://twitter.com/WeddingWire>

**Comment by agilliland** [comment]
@hansyson were you able to get this resolved?

**Comment by hansyson** [comment]
yes!  deleting the file, reinstalling, then creating a new login.  the
latter part stinks. but i am good now.

On Mon, Feb 8, 2016 at 3:13 PM, Allen Gilliland <notifications@github.com>
wrote:

> @hansyson <https://github.com/hansyson> were you able to get this
> resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metabase/metabase/issues/1867#issuecomment-181511483>.
>



-- 

*Hans Son*

Data Engineer Lead

W E D D I N G W I R E

301 231 9473 x ext 2364

hson@weddingwire.com <brian@weddingwire.com>

website <http://weddingwire.com/> • blog <http://blog.weddingwire.com/> •
facebook <https://www.facebook.com/WeddingWire> • twitter
<https://twitter.com/WeddingWire>

**Comment by camsaul** [comment]
Closing since @hansyson was able to resolve this :heart:
