### ISSUE TITLE
Make IP addresses visible for firewall Cloud users

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#18670]
**Links**
- product doc: https://www.notion.so/metabase/Make-IP-addresses-visible-for-firewall-Cloud-users-4153069c110140e9bd91a164da103584

**Implementation Plan**

- [x]  BE: Expose cloud IP addresses via a public setting
- [x]  FE: Add cloud ip addresses info to the UI

**How to Test This Feature Out**

- Create a new Metabase Cloud instance
- During the setup process, the block with Cloud IP addresses should be visible

**Comment by noahmoss** [comment]
@ranquild is this epic ready to be closed out?
