### ISSUE TITLE
Detailed view showing connections multiple times

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#1868]
In the detailed view, that is shown when only a single row is viewed as raw data in the query builder, metabase shows on the right hand side to which other tables this row is connected via which keys. That's a nice feautre. However some connections are listed several times.
![image](https://cloud.githubusercontent.com/assets/8144392/12796752/b1a3ba5a-cac0-11e5-943b-dd99636db758.png)

**Comment by agilliland** [comment]
thanks for reporting this.  we have a fix coming for this very shortly.

**Comment by robinfrick** [comment]
Perfect, thank you for your awesome work :+1:
