### ISSUE TITLE
QB sorting widget broken; cannot sort a query

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1870]
This is happening to me on several different databases with the latest build from master. Choose a field to sort by and it doesn't save the choice.

![out](https://cloud.githubusercontent.com/assets/1455846/12799710/2390685c-ca85-11e5-9dc3-fe3433090a1a.gif)

**Comment by camsaul** [comment]
Didn't see anything in the console either

**Comment by tlrobinson** [comment]
By "several" do you mean every one you tried, or does it work for some?

Interestingly clicking the table header still works.

I'll look into it.

**Comment by camsaul** [comment]
every one I tried.
