### ISSUE TITLE
XLSX export of "X of Y" (eg. Month of Year) is formatted as date column

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18729]
**Describe the bug**
XLSX export of "X of Y" (eg. Month of Year) is formatted as date column.

Workaround: In they XLSX viewer (Excel, Numbers, Calc), disable date formatting on the column.

**To Reproduce**
1. Custom question > Sample Dataset > Products
2. Count grouped by CreatedAt:MonthOfYear and Category
![image](https://user-images.githubusercontent.com/1447303/139248650-783a7c7a-9822-40d4-ab31-09d1261cd9c4.png)
3. Export as XLSX
![image](https://user-images.githubusercontent.com/1447303/139248826-2e53252f-7590-48ca-b097-3dc45973f9a5.png)
4. Export as CSV
```
Created At,Category,Count
1,Doohickey,2
1,Gadget,7
1,Gizmo,6
1,Widget,1
2,Doohickey,4
2,Gadget,5
2,Gizmo,4
```

**Expected behavior**
Preferably return the value similar to what is shown in Metabase (this might be tricky, especially with i18n), otherwise return the numeric value without date formatting.

**Information about your Metabase Installation:**
Tested 0.40.5 thru 0.41.1 - regression since 0.41.0

**Additional context**
Lightly related to #18572 and #18219

**Comment by nemanjaglumac** [comment]
@flamber this is what SheetJS sees for `xlsx`. Not sure which assertion would be appropriate because we're still not sure how will this be resolved. Any ideas?

```js
{
  A1: {t: 's', v: 'Created At', h: 'Created At', w: 'Created At'}
  A2: {t: 'n', v: 42461, w: 'April 1, 2016, 12:00 AM'}
  A3: {t: 'n', v: 42491, w: 'May 1, 2016, 12:00 AM'}
  B1: {t: 's', v: 'Product → Category', h: 'Product → Category', w: 'Product → Category'}
  B2: {t: 's', v: 'Gadget', h: 'Gadget', w: 'Gadget'}
  B3: {t: 's', v: 'Doohickey', h: 'Doohickey', w: 'Doohickey'}
  C1: {t: 's', v: 'Count', h: 'Count', w: 'Count'}
  C2: {t: 'n', v: 1, w: '1'}
  C3: {t: 'n', v: 5, w: '5'}
}
```

**Comment by nemanjaglumac** [comment]
Also, please let me know if you'd like this covered for `csv` as well?

**Comment by flamber** [comment]
@nemanjaglumac I'm not sure if we're able to do similar translation as in-app, but otherwise it should return numeric value similar to CSV. And given the regression, then we should also cover CSV, so we don't regress there too.

**Comment by noahmoss** [comment]
Unassigning myself; when I started to dig into this it seemed pretty tricky to get exactly right. More of a mini project than a quick fix IMO
