### ISSUE TITLE
MongoDB date filtering not working for ISO-8601 strings

### ISSUE THREAD

**Issue by mwatermolen** [metabase/metabase#18733]
**Describe the bug**
When using a mongo DB, a casted date field derived from JSON is not filterable by date. It is filterable by if the value exists however.

**Logs**
[Metabase.log](https://github.com/metabase/metabase/files/7435246/Metabase.log)
[console.log](https://github.com/metabase/metabase/files/7435255/console.log)

Please LMK if any other logs would be helpful, not quite sure I see any errors

**To Reproduce**
1. Add a Mongo DB
2. add a Table with an `Info` column
3. add the json below to the column
3. Sync fields, so `Info: started`  is discoved
4. Date Cast as seen in screen shot at bottom
5. Attempt to filter on date
#### JSON being Parsed
```
{
  "started": "2021-10-22 21:33:37",
  "category": "file",
  "package": "exe",
  "source_url": null,
  "ended": "2021-10-22 21:37:35",
  "shrike_refer": null,
  "shrike_msg": null,
  "custom": "",
  "duration": 238,
  "route": "none",
  "shrike_sid": null,
  "shrike_url": null,
  "parent_id": null,
  "id": 1,
  "parent_sample": {
    "source_url": null,
    "md5": "7a456d32d3eb4a1bb245aa77d0a99abf",
    "parent": null,
    "file_type": "Zip archive data, at least v6.3 to extract",
    "file_size": 87934,
    "ssdeep": null,
    "sha1": "8e3a840487b709381ca3d30a30970a44d454905b",
    "sha512": "ed7083892396e9a1429e4eb1a5e7d639fdc06870ce2bf7c22ac8965b03e51ac67c7af6ea4e52efe9ea6ba32bf586275faf6c25405f633486750e9d2a16e02a33",
    "id": 1,
    "crc32": "BD199F57",
    "sha256": "88d363988f58ed1364800ae1000e2d0ae7e630e4bbf87269011ffbb08ef03962"
  },
  "machine": {
    "id": 1,
    "status": "stopping",
    "name": "Biscotti-WIN10",
    "label": "Biscotti-WIN10",
    "manager": "Proxmox",
    "started_on": "2021-10-22 21:33:37",
    "shutdown_on": "2021-10-22 21:37:35"
  },
  "tlp": "",
  "user_id": 0,
  "options": {},
  "timeout": true,
  "version": "2.2-CAPE",
  "has_cents_rules": false
}
```

**Expected behavior**
Expecting results to filter based on date

**Screenshots**

![image](https://user-images.githubusercontent.com/73605619/139280390-f1da1d63-3b96-46cf-99b7-47da04cde65e.png)

![image](https://user-images.githubusercontent.com/73605619/139278855-b593a5bd-3c9a-46ec-a1c3-9fea7ef0c959.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 94.0.4606.81 (Official Build) (64-bit)
- Your operating system: Windows 10
- Your databases:  MongoDB
- Metabase version: 0.41.0
- Metabase hosting environment: Kubernetes
- Metabase internal database: MSQL (AWS RDS)

**Severity**
This is preventing us from making actionable dashboards for our SOC, so it would be very helpful to get this resolved

**Additional context**
Field is set to cast the date ISO 8601 -> Datetime; casting does seem to be working
Database is a CAPE MongoDB, which is a lot of large JSON
![image](https://user-images.githubusercontent.com/73605619/139280221-5dca83b6-f146-400c-aace-3de4a192da6b.png)

**Comment by camsaul** [comment]
@escherize assuming you looked into this can you add a comment about what you discovered

**Comment by qnkhuat** [comment]
I did some debugging and I believe this problem comes from the fact that our Mongo Driver currently does not support Casting from ISO.

The simple fix (AFAIK) is to add 
```clojure
(isa? coercion :Coercion/ISO8601->DateTime)
{"$dateFromString" {:dateString field-name
                    :format "%Y-%m-%dT%H:%M:%S.%LZ"
                    :onError field-name}}
```
into this [function](https://github.com/metabase/metabase/blob/b1689921e91e955eb61dbbec9544125dbb1cdef5/modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj#L120)

But I think we should make it completes by adding support for `:Coercion/ISO8601->Date` and `:Coercion/ISO8601->Time` as well.

**Comment by zanderisrael** [comment]
I think this might be related, I'm unable to sync my mongodb. 

All seems fine, but sync takes forever...
 - Im able to see the collections but not the data itself.
 - the collections are in a disabled state. 
 - 
In the logs I can see this "Error generating fingerprint for Field 20,071 '_updated_at..."
