### ISSUE TITLE
Allow a dashboard to be archived

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1874]
There are times when a dashboard is no longer actively used, but deleting it would be a bit aggressive.  It would be nice if as a user you could archive it so that it doesn't show up in the listing, but if needed it was still available to restore.

**Comment by salsakran** [comment]
@kdoh my understanding is that this is part of the dashboard org project.

**Comment by kdoh** [comment]
Yup, the plan is to keep features like labels and archiving mentioned in #2204 consistent between questions and dashboards.

**Comment by mazameli** [comment]
Resolved by https://github.com/metabase/metabase/pull/4868
