### ISSUE TITLE
Log filled with warnings about deprecated sematic type "Number"

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18754]
**Describe the bug**
When running older instances that made use of the field type `Number`, then newer versions will litter the log with:
```
2021-10-29 15:00:01,401 WARN models.field :: Invalid Field :semantic_type :type/Number: falling back to null
```

Manual workaround: `update metabase_field set semantic_type=null where semantic_type='type/Number';`

**Expected behavior**
Either create a migration, which changes the semantic_type=null or add ignore to this specific warning, so it doesn't show in log.

**Information about your Metabase Installation:**
Tested 0.40.5 and 0.41.1 - regression since 0.40.0 #15994

**Comment by camsaul** [comment]
let's just write a migration to fix this once and for all
