### ISSUE TITLE
Run tests with both MySQL and Postgres as app databases

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18761]
We're running Metabase with H2 on the CI tests, which is not currently a real life use case (or shouldn't be). We should run all tests with all the app databases we support to check for possible issues

**Comment by camsaul** [comment]
We do run tests against MySQL, MariaDB and Postgres as the application DB. Look at the test jobs with `mysql`, `mariadb`, and `postgres` in the names

**Comment by flamber** [comment]
Closing this, since it doesn't make a lot of sense to run all tests on all types of appdb.
