### ISSUE TITLE
The data reference panel in the QB should only show information from the chosen database

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1877]
As a user working on a query in the QB I want to see relevant reference data about the specific set of data that i'm working on and would like to avoid seeing other data that's not related.

**Comment by salsakran** [comment]
There should probably be a way to move "up" the hierarchy to switch DB's or Schema's in the event that you need to, but yes, we should scope the initial data reference to just the DB in question.

@mazameli + @kdoh my bias here is to use the same visual treatment we currently use for the DBs <-> table <-> field tree for a new DB List <-> Table list <-> Table <-> Field tree. Do we need to do anything more on the design?

**Comment by kdoh** [comment]
Implemented by #9459 but wasn't auto closed.
