### ISSUE TITLE
Firebolt Driver

### ISSUE THREAD

**Issue by rankam** [metabase/metabase#18779]
**Is your feature request related to a problem? Please describe.**
Not really - it's a new driver for Firebolt.

**Describe the solution you'd like**
A Metabase driver for Firebolt.

**Describe alternatives you've considered**
I haven't really - we would be open to helping to implement this though (i.e. contributing code). 

**How important is this feature to you?**
Very - we are likely moving away from Snowflake so we will need a BI tool that can connect to Firebolt.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by kevinmarr** [comment]
Hi @rankam, this is currently being worked on by the Firebolt team. In fact, we already have a temporary JAR plugin that you can use if you want to test the alpha. Let me know.

We're still discovering what the merge and release process will look like for us, but tentatively we're looking at a GA within the next month or so.

**Comment by marsellomatt** [comment]
Hi @rankam, is the Firebolt driver ready yet? Thanks

**Comment by paoliniluis** [comment]
Should this one be closed @luizarakaki?
