### ISSUE TITLE
Query executions hitting the cache are not recorded

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18777]
**Describe the bug**
Query executions hitting the cache are not recorded

Regression since 0.40.0, likely caused by #16220
P1 contender.

**To Reproduce**
1. Admin > Settings > Caching > Duration=0.001, TTL=1000000
2. Simple question > Sample Dataset > Orders - save as "Q1"
3. (reload the browser until it's hitting the cache, issue 13262)
4. Then reload the browser again, while it's hitting the cache
5. View `query_execution` (or Admin > Audit > Audit log), it does not have any records of anyone viewing the cached results.
There is however a record in `view_log`, though this does not record what was viewed, nor if viewing from a dashboard.

**Expected behavior**
Queries hitting the cache should always be recorded and should be marked as `cache_hit=true` (column introduced in 0.40.0)

**Information about your Metabase Installation:**
Tested 0.39.5 thru 0.41.1 - regression since 0.40.0

Related to #16517

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by Rayyan98** [comment]
@howonlee Pls fix
