### ISSUE TITLE
Horizontal scroll of tables in email reports should be more discoverable, and apply to the table only

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#18789]
**Describe the bug**
When a table with a large number of columns is rendered for a dashboard subscription email, we make it horizontally scrollable. However the scroll is applied to the entire section, rather than just the table itself, so it also scrolls the pulse title, and the copy above and below the table, which is a bit awkward.

It's also quite difficult to discover the fact that the table is scrollable, particularly on mobile clients where the scroll bar might be hidden by default. We should force the scrollbar to always appear if possible, and maybe add some text to inform the user that they can scroll? cc @brunobergher 

For backend context, the scroll behavior is implemented here: https://github.com/metabase/metabase/blob/master/src/metabase/pulse/render.clj#L150-L153. It should be probably be moved down into `metabase.pulse.render.table` somewhere, but we should be careful to ensure that the link behavior still works as expected (i.e. the entire section links to the question when clicked, and text doesn't underline on hover) and that clicking and dragging the scrollbar in a web mail client still works.

Related to #18755

**To Reproduce**
1. Save a table with a relatively large number of columns as a question (e.g. any of the sample dataset tables)
2. Add the table to a dashboard
3. Send a test dashboard subscription to an email
4. Open the email in a mobile email client, like Gmail for iOS/Android

**Information about your Metabase Installation:**
Current master

**Severity**
I think the discoverability issue is pretty important, but the behavior of the scroll itself (table vs pulse section) is minor.

**Comment by brunobergher** [comment]
@kdoh has been thinking about this the most.
