### ISSUE TITLE
Add Basic Authentication to Druid Queries

### ISSUE THREAD

**Issue by Ray33** [metabase/metabase#18808]
Problem description:
When defining a database from type "Druid", there is no option to set a secure connection via "Basic Authentication".
Hence, it basically eliminates the possibility to use a security option that is supported by the Druid backend and by Druid's native UI, since if we will enable this option, Metabase will not be able to get results, due to missing authentication.

Proposed solution:
On Metabase, in Druid DB settings (Admin panel), add an option (toggle) for "Basic Authentication" . If enabled, it will allow the admin user to add the token. Also, once enabled, all the calls to druid will use the token as a basic authentication header.

**How important is this feature to you?**
Feature is important, as without it, it expose security risk in Druid.

**Additional context**
![druid_ui (1)](https://user-images.githubusercontent.com/7954817/139856963-159d23f9-acaa-4257-a43c-434dbedaa8c1.png)

The development of this feature will be sponsored by Mobitech.io :
https://www.upwork.com/ab/applicants/1455154266814951424/job-details

**Comment by Ray33** [comment]
@flamber Since the design is straightforward and since it will be funded by Mobitech, I would highly appreciate it if you could push the feature forward to " Design Needed" phase or "Help Wanted" phase.

**Comment by Ray33** [comment]
@flamber Since the design is straightforward and since the development will be **funded by Mobitech**, I would highly appreciate it if you could push the feature forward to " Design Needed" phase or "Help Wanted" phase. Please help to promote it.

**Comment by flamber** [comment]
@Ray33 Just add a setting, there's really no design needed or help wanted, since you're doing the work. Though I cannot guarantee that the PR will be accepted into the core project, but if the PR is well-written and has tests, then it's much more likely.

**Comment by Ray33** [comment]
@flamber Can you please assign https://github.com/nbotelhodev for this task? (I don't have permission to do it)

**Comment by flamber** [comment]
@Ray33 I cannot (and would not) assign external people to our issues. You should probably clone Metabase repo into your own repo, so you can manage it however you want.

**Comment by Ray33** [comment]
@flamber The feature is added in: https://github.com/nbotelhodev/metabase/pull/1
It is working and confirmed.

Authentication header config switched off:
![image](https://user-images.githubusercontent.com/7954817/150289023-1e5cf0d5-68e8-4260-ae30-b953e48b0931.png)

Authentication header switched on : 
![image](https://user-images.githubusercontent.com/7954817/150289388-8fc96891-c8be-4355-a0a8-890c82f7d8d3.png)

**Comment by gpodevijn** [comment]
We were looking for exactly this. Without the basic authentication #19830 provides, we couldn't connect Metabase to Druid. 

🤞 that the PR passes the reviews and can get merged in the next Metabase release.

I'm also happy to provide any feedback/help in the PR if necessary.

**Comment by Ray33** [comment]
@gpodevijn Till the pull request will be merged, the compiled jar, with the authentication feature (based on latest metabse version) can be downloaded at:
https://drive.google.com/file/d/17Yvn9Eq6TFC9zqH5eaZMrVoGmVh9nBpc/view

**Comment by gpodevijn** [comment]
Thanks @Ray33 !
