### ISSUE TITLE
only the list of questions in the add to dashboard modal should scroll

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1880]
currently the entire modal scrolls which means the cancel and sort options can be out of view.

<img width="777" alt="screen shot 2016-02-03 at 5 18 39 pm" src="https://cloud.githubusercontent.com/assets/5248953/12802968/949595c0-ca9b-11e5-8a2d-a5c66f58d7c8.png">

**Comment by mbvictoria** [comment]
Closing - more comprehensive list of improvements to this modal are in #10095
