### ISSUE TITLE
Fix type of query_cache.results column in MySQL via new changeSet

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#18815]
In MySQL, The `query_cache.results` column in the app DB needs to be `LONGBLOB` in MySQL.  The #16095 change took care of fixing an old bug in the Liquibase configuration, for changeset ID 97 (which was many releases ago).

The trouble is that this will only take effect for new/blank MySQL app DB instances creates as of 0.42, and will not go back and fix any that are upgrading from older versions.  This issue is to fully close out the problem by creating a new changeset that will always change the column type to `${blob.type}` correctly, even on upgrade.

**Comment by flamber** [comment]
Historic issue reference: #7006, the OP.
