### ISSUE TITLE
Removing a grouping leaves grouping columns partially visible

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18817]
**Describe the bug**
When starting with a saved question, adding 2 groupings and then deleting one, leaves some orphan column names in the top bar, that are even functional

**Logs**
NA

**To Reproduce**
1) With the sample dataset create a new GUI question (Let's say, just click the people table and save it as People).
2) access the saved question (or refresh the page), and then add 2 group by's (name and source). Then remove one of those
3) see the column titles still populated with some groupings still visible

**Expected behavior**
Just see the columns that are in the groupings

**Screenshots**
Stats
![image](https://user-images.githubusercontent.com/1711649/139953279-df92f667-854b-4f35-a148-b91abc43f4a1.png)

On a 40.5 I was testing with:
![image](https://user-images.githubusercontent.com/1711649/139953454-0863d6d8-d729-4173-98de-984fc5a46ac4.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest and Firefox 93
- Your operating system: Ubuntu 21.10
- Your databases: H2
- Metabase version: master branch and 40.5
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic

**Additional context**
Might be a cousin of https://github.com/metabase/metabase/issues/13772, but I'm not very sure

**Comment by flamber** [comment]
This only occurs on pivoted table (old pivot table).
1. Simple question > Sample Dataset > Products - save as "Q1"
2. Refresh browser
3. Notebook - summarize Count by Category and Vendor
4. It should automatically change to pivoted table
5. Click the data toggle in the bottom - it will show the pivoted table underneath.

**Comment by kamilmielnik** [comment]
Reproducible in 0.40.5.
Fixed in `master` ([d35c779](https://github.com/metabase/metabase/commit/d35c779976ae6bd79369e9cc6bec8540908f37d2)).
Marking as fixed in the next version (48).
Closing.

**Comment by metamben** [comment]
@uladzimirdev I'm sorry I didn't notice that you were actively working on this as ticket was closed. I've added some BE tests, but as discussed with @ranquild this might actually need a FE test.

**Comment by uladzimirdev** [comment]
Both FE and BE tests are merged now, I'm closing this issue again
