### ISSUE TITLE
SSO with full-app embedding uses SESSION cookie instead of EMBEDDED_SESSION cookie

### ISSUE THREAD

**Issue by pawit-metabase** [metabase/metabase#18823]
**Describe the bug**
When using full-app embedding, the `EMBEDDED_SESSION` is expected to be used. However, when using SSO, Metabase does not realize that the login is being performed inside embedding and the `SESSION` cookie is used instead.

(This is because Metabase uses `EMBEDDED_SESSION` when there is a `x-metabase-embedded` header in the call. However, SSO login is performed via redirect so the header is not present.)

This prevents cross-domain full-app embedding from working without setting `MB_SESSION_COOKIE_SAMESITE=None` which may reduce the security level.

**Logs**
See screenshot

**To Reproduce**
1. Configure Metabase with full-app embedding and SSO (I've tested with JWT, but we should make sure it work for both JWT and SAML)
2. Do full-app embedding from another domain

**Expected behavior**
 - The `EMBEDDED_SESSION` cookie is used instead of `SESSION` cookie.
 - Cross-domain full-app embedding works without setting `MB_SESSION_COOKIE_SAMESITE=None`

**Screenshots**
<img width="1093" src="https://user-images.githubusercontent.com/88995137/140006758-007515da-2ecb-4a81-aeaa-af006c1f5ad5.png">

**Information about your Metabase Installation:**
Metabase 1.41.1
Chrome 95

**Severity**
Makes it more difficult to setup full-app embedding, especially on cloud.

**Additional context**
#18822 needs to be fixed otherwise embedding will not work after fixing this issue.

After this is fixed, some text in the document will no longer apply

https://github.com/metabase/metabase/blob/ce939219f8a3e28ecb00deb232154780a1dcfcef/docs/enterprise-guide/full-app-embedding.md?plain=1#L37
- Embedding no longer makes use of `MB_SESSION_COOKIE_SAMESITE` so there is no reason to set it. It does require HTTPS to be used though.

https://github.com/metabase/metabase/blob/ce939219f8a3e28ecb00deb232154780a1dcfcef/docs/enterprise-guide/full-app-embedding.md?plain=1#L95
- Embedding always use session cookie so there's no reason to set `MB_SESSION_COOKIES`

**Comment by pawit-metabase** [comment]
There are other issues associated with fixing this. For example, map tiles will not load correctly due to anti-CSRF token not provided for the request. In-depth testing will be required and this should be slated for a major version.

![image](https://user-images.githubusercontent.com/88995137/140300807-27375c26-4dcc-42b4-9e03-fd7a18cde726.png)

**Comment by paoliniluis** [comment]
Check ticket 16015

**Comment by paoliniluis** [comment]
We should be checking here: https://github.com/metabase/metabase/blob/c203040da445e2f4847b463e0f3f2675cb916b0a/src/metabase/server/middleware/session.clj#L187

for the existence of the `X-Metabase-Embedded` cookie https://github.com/metabase/metabase/blob/c203040da445e2f4847b463e0f3f2675cb916b0a/frontend/src/metabase/lib/api.js#L89

Repro steps to check how Metabase reacts
1) set up an nginx proxy with proxy_set_header X-Metabase-Embedded "true";
2) test Metabase

**Comment by paoliniluis** [comment]
To check this issue, use https://embedding-demo.metabase.com/ where you can see we're sending the session cookie

**Comment by albertoperdomo** [comment]
Update:
* no news on the technical front to unlock this. It looks like we'd need changes to the authentication flows to solve this.
* in the meantime we are going to add an admin setting to be able to set `MB_SESSION_COOKIE_SAMESITE` at runtime as a mitigation.

**Comment by albertoperdomo** [comment]
We've now implemented https://github.com/metabase/metabase/issues/35364 via https://github.com/metabase/metabase/pull/35392. 

This is scheduled for the 48 release.

It's now possible to change the samesite setting via admin settings, and we suggest changing it to none when the authorized origin is different from the metabase instance domain. I think with this in place, this issue has less impact, so I am updating it from P1 to P2.

**Comment by albertoperdomo** [comment]
The issue as described talks about internal implementation details that are irrelevant to the user. Closing.
