### ISSUE TITLE
Unsupported expressions should not populate menus in query builder

### ISSUE THREAD

**Issue by jeff-bruemmer** [metabase/metabase#18830]
**Is your feature request related to a problem? Please describe.**
When writing expressions in the query builder, Metabase currently includes expressions that are not (yet) supported by the current data source. E.g., if querying an H2 database, Metabase presents `regexextract` as an option, even though H2 doesn't support it. Instead, the query fails, with the error: `No method in multimethod '->honeysql' for dispatch value: [:h2 :regex-match-first]`.

**Describe the solution you'd like**
When displaying aggregations and functions, only show those relevant to the current data source (i.e., the queried database).

**Describe alternatives you've considered**
We already document these limitations, but it'd be nice not to give false hope in the UI.

**How important is this feature to you?**
Just some polish that would be relatively simple to implement and that could save people some frustration.

**Comment by flamber** [comment]
Related to #12222/#12845
