### ISSUE TITLE
Remove QB code disabling date bucketing for MongoDB

### ISSUE THREAD

**Issue by dylanjha** [metabase/metabase#1885]
Date grouping is only working by day, I don't see the options to group by hours, week, month, etc. like I do with Postgres

I'm also not seeing relative dates as a feature that works with Mongo, although it looks like it was implemented in https://github.com/metabase/metabase/pull/1276 (should have made it in on version 0.13)

I'm fairly new to Mongo, so it's likely this is a problem on my end, but this is an example of how the dates are saved in my mongo db:

```
 timeCreated: ISODate("2016-01-26T01:33:46Z"),
```

Metabase version info:

```
You're on version v0.14.1
built on 2016-02-03
```

Seriously, this tool is amazing. I have it deployed once connected to a Postgres database and once connected to a Mongo database :clap: very nice work by all the contributors.

Please excuse me if this is more of a support issue and not a development issue, if so, what would be the appropriate channel for support?

**Comment by camsaul** [comment]
@tlrobinson are the date bucketing options still hidden for mongo DBs in the query builder?

**Comment by tlrobinson** [comment]
Apparently... https://github.com/metabase/metabase/blob/master/frontend/src/query_builder/FieldList.jsx#L90-L92

**Comment by dylanjha** [comment]
good eye :mag: :eyes:  @tlrobinson
