### ISSUE TITLE
Environment variables that are JSON values are not displayed as defined in Admin > Settings

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18864]
**Describe the bug**
When setting environment variables, which are JSON blobs, then it's correct applied, but the interface shows Metabase defaults instead, which can lead to confusion about which settings are applied. And the input fields are not locked, which makes it even more difficult to understand that the value comes from envvars.

Applies to `MB_APPLICATION_COLORS`, `MB_CUSTOM_FORMATTING`, `MB_JWT_GROUP_MAPPINGS`, `MB_LDAP_GROUP_MAPPINGS` and `MB_SAML_GROUP_MAPPINGS`
And likely `MB_CUSTOM_GEOJSON` too, but it has it's own problems #18862

Workaround: Set it directly in the application database table `setting` or set it via the API with key, eg. `custom-formatting`, with value, eg. `{"type/Currency":{"currency":"DKK"}}`
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#put-apisettingkey

**To Reproduce**
1. Start Metabase:
` java -DMB_APPLICATION_COLORS='{"brand":"#ff0080"}' -DMB_CUSTOM_FORMATTING='{"type/Temporal":{"date_style":"YYYY/M/D","time_style":"HH:mm"},"type/Number":{"number_separators":",."},"type/Currency":{"currency":"DKK"}}' -jar metabase.jar`
2. Go to Admin > Settings > Localization or Whitelabel - it looks like none of the settings apply
![image](https://user-images.githubusercontent.com/1447303/140499387-338bae04-46e8-4f28-8c8a-3df346513dce.png)
![image](https://user-images.githubusercontent.com/1447303/140499483-1f85cf0a-649d-4e1e-ba7d-05a5d0a7d2fa.png)
3. But all the envvar settings are clearly working as expected
![image](https://user-images.githubusercontent.com/1447303/140500183-64fbacd0-12fd-4cdc-b94a-5707f38e4777.png)

**Expected behavior**
The input fields should be locked, similar to defining other non-JSON-blob envvars like `MB_SITE_NAME`, so it's clear that it cannot be modified within Metabase.

**Information about your Metabase Installation:**
Tested 1.41.1 (versions pre-40.0 would not error, but would not apply the envvar, when there was keys in `setting` table)

**Additional context**
Related to #13166 and #14790

**Comment by shaunlebron** [comment]
Fixed by https://github.com/metabase/metabase/pull/25067

![Image](https://github.com/metabase/metabase/assets/116838/890bcd48-0d24-4a1d-91c0-d30512557284)
