### ISSUE TITLE
I am always frustrated whenever I save a new chart in my folder, but when i want to go fetch it in the folder, the order list of charts is always alphabetical. I am creating multiple charts at once and would like to see the Latest charts created in the folder. Please, this is bugging me and frustrates me a lot.

### ISSUE THREAD

**Issue by farahmk** [metabase/metabase#18867]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
