### ISSUE TITLE
Rendering of a 2 dimensional table on dashboards should pivot the same way as it does on the QB

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1887]
Currently if you build a query with 2 breakout clauses on the QB and visualize it as a `table` we pivot the columns against each other.  However, if you then take that question and apply it to a dashboard you see the unpivoted data.

Mentioned here ... http://discourse.metabase.com/t/new-feature-request/188/2

**Comment by hansyson** [comment]
any idea when this will be fixed?

**Comment by hansyson** [comment]
having multiple layers in the column and row headers is a necessity.  control on sorting would also be lovely.
