### ISSUE TITLE
Elevate most popular database options in set up

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#18918]
### Links
- product doc: https://www.notion.so/metabase/Elevate-most-popular-database-options-in-set-up-f989349a690f45e7b2b2576612ceff5f

##### Expose a list of popular engines
Add `elevated-engines` public setting with the list of elevated engines, e.g. `["postgres", "mysql"]`. The order is important.

##### Expose icons for databases we support out of the box
Add `driver-icon` field to each engine returned by `engines` setting. This should be a (relative) url to an icon stored in `resources/frontend_client/app/assets/img/drivers`. Example url `/app/assets/img/drivers/mysql.svg`.

**Comment by noahmoss** [comment]
@ranquild What would you think of just using naming conventions for the SVG paths rather than making them properties on drivers? i.e. just look for `/app/assets/img/drivers/{driver-name}.svg` and use it if it exists, and if it doesn't, use the default icon

**Comment by ranquild** [comment]
Discussed that we would add `official` field to drivers and use it here.
