### ISSUE TITLE
Support parsing multiple links from text

### ISSUE THREAD

**Issue by ansidev** [metabase/metabase#18932]
**Is your feature request related to a problem? Please describe.**
Steps to reproduce the behaviour:
1. Write a SQL likes this:
```
SELECT provider, provider_uid, GROUP_CONCAT(DISTINCT CONCAT('https://metabase.domain.tld/question/123-user-profile?user_id=', user_id)) AS `user_id_list`
FROM social_users
GROUP BY provider, provider_uid
HAVING COUNT(user_id) > 1;
```
2. One of the values of the column user_id_list will look like
```
https://metabase.domain.tld/question/123-user-profile?user_id=1,https://metabase.domain.tld/question/123-user-profile?user_id=2
```

https://metabase.domain.tld/question/123-user-profile?user_id=<user_id> is a Metabase question:
```
SELECT u.*
FROM `user` u
WHERE u.id={{user_id}}
```

Problem
- Only one URL will be displayed and if I click on the URL open link: https://metabase.domain.tld/question/123-user-profile?user_id=1%20https://metabase.domain.tld/question/123-user-profile?user_id=2

**Describe the solution you'd like**
Can click on each URL of each user ID (for example the user has ID=1 and the user has ID=2)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 95.0.4638.69 (x86_64)
- Your operating system: macOS BigSur 11.6
- Your databases: MariaDB 10.5
- Metabase version: 0.40.3.1
- Metabase hosting environment: Docker on Ubuntu 20.04
- Metabase internal database: Postgres 13.3

**How important is this feature to you?**
Normal, but you should support it ASAP.

**Additional context**
Workaround: Copy the link and paste it manually in the new browser tab.

**Comment by flamber** [comment]
Hi @ansidev 
Metabase currently only supports a single link per column.
But there's a request for adding Markdown links, so closing in favor of that: #7188 - upvote by clicking :+1: on the first post
Also, latest release is 0.41.2: https://github.com/metabase/metabase/releases/latest
