### ISSUE TITLE
Embbed a metabase question or dashboard on a HTML page

### ISSUE THREAD

**Issue by brunolnetto** [metabase/metabase#18948]
Hi fellows,

I am new to web development, but got this task of embbeding some results generated on Metabase. There is an iFrame that solves the issue for me without authentication, but the application solution suits for dynamic interaction of the user. Some provided me this github repo: https://github.com/metabase/sso-examples. The html content is at the end of this issue. I do not mind to provide the server URL and secret key.

Description: Embbed a question with locked parameter on HTML page;

Step by step actions: 

- Enable embbed option on settings; 
- Open a question; 
- Click on diagonal arrow on the bottom right side of the page
- Go to 'code' tab to access 'METABASE_SITE_URL' and 'METABASE_SECRET_KEY' 

Blocking situation: Setup on payload object the key params with desired filtered value. 
What have I done sofar: Setup the package.json file with the content below.

```
{
	  "name": "mesa-bi",
	  "version": "0.0",
	  "dependencies": {
		  "browserify": "^17.0.0",
		  "jsonwebtoken": "^8.5.1"
	  }
  }
```

Wrote a .html file with content below.

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Document </title>
        <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
        <meta content="utf-8" http-equiv="encoding">
        <script src="scripts/require.js"> </script>
        <link rel="stylesheet" href="main.css">
    </head>
    <body>
        <script>
            'use strict'

            var jwt = require("jsonwebtoken");

            var METABASE_SITE_URL = "http://3.231.180.105:8080";
            var METABASE_SECRET_KEY = "885f4b7497bfdf8ad6685b62e65af00d61dad2719f268f823865df51a3068b19";
            
            var payload = {
                resource: { dashboard: 1 },
                params: {},
                exp: Math.round(Date.now() / 1000) + (10 * 60) // 10 minute expiration
            };
            
            var token = jwt.sign(payload, METABASE_SECRET_KEY);

            var iframeUrl = METABASE_SITE_URL + "/embed/dashboard/" + token + "#bordered=true&titled=true";
        </script>
        <noscript>You need to enable JavaScript to view the full site.</noscript>
    </body>
</html>



 
```

**Comment by flamber** [comment]
Hi @brunolnetto 

As I have already mentioned, https://github.com/metabase/sso-examples is for the Enterprise Edition.
And you should absolutely not do what you're doing in your example, since you're exposing your secret.
I would recommend that you hire a web developer to help you.

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
