### ISSUE TITLE
...Error building classpath. The following libs must be prepared before use: [metabase/java-deps]

### ISSUE THREAD

**Issue by JustCrazyHeart** [metabase/metabase#18954]
I can't start metabase with docker,the error message is :
[cljs] ...Error building classpath. The following libs must be prepared before use: [metabase/java-deps]
[cljs] .clojure -M:run exited with code 1
--> Sending SIGTERM to other processes..
[cljs] ..yarn build-hot:js exited with code null
[docs] yarn docs exited with code null
[cljs] yarn build-hot:cljs exited with code null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
help me, please.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/t/getting-this-error/16827
