### ISSUE TITLE
SOME EMAILS DOES NOT RECEIVE INVITATION EMAILS WHILE OTHERS RECEIVE

### ISSUE THREAD

**Issue by nelkoecherry** [metabase/metabase#18957]
Please use the issue chooser, when creating a new issue:

https://github.com/metabase/metabase/issues/new/choose
Hi Metabase Team,
I am reaching out on behalf of Carepay LTD,
We are experiencing some challenges while signing up users to Metabase. We have almost 10 accounts that don't receive invitation links on their work emails and we end up inviting them through their personal emails. This is against our privacy policy and we would like to sign up all users using their work emails. Could you be in a position to know what could be blocking these emails? 
Your response will be highly appreciated.
Thnaks.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
