### ISSUE TITLE
Filtering on table columns in dashboard

### ISSUE THREAD

**Issue by kllr** [metabase/metabase#18958]
Hi 

I have a table with 30 columns with a value of them every second. (like voltage1, voltage2, temp1,....)

I want to create a dashboard with 5 graphs and a filter on top. The filter should contain a dropdown with the column names. This so i can select one or more of them that will be shown in the 5 graphs.

Right now it looks like i should create 5 x 30 questions to display the graphs? Is there a way to filter a table on COLUMN?

Thanks in advance

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
