### ISSUE TITLE
Audit -> Team members -> all members returns an error in master

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18961]
**Describe the bug**
Our current internal instance returns an "ERROR: column u.sso_source does not exist Position: 1082" error in the Audit -> Team members -> all members section

**Logs**
N/A

**To Reproduce**
1) go to our internal instance
2) go to audit-> team members-> all members

**Expected behavior**
Show the users table

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/141500068-7d344585-2ee2-4873-81ca-2ec243803c17.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave lates
- Your operating system: Ubuntu 21.10
- Your databases: our internal instance
- Metabase version: master
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: RDS (Postgres)

**Severity**
High

**Additional context**
Maybe it's a temporal error

**Comment by flamber** [comment]
Internal issue
