### ISSUE TITLE
Skinny bar graphs when using SQL editor

### ISSUE THREAD

**Issue by dudleycarr** [metabase/metabase#1896]
Metabase: 0.14.1

Issue: Unlike the bar graphs generated when constructing a query using the Metabase query editor, the SQL editor bar graphs are skinny and not representing all of the values. 
```sql
CREATE TABLE test (
  value INT,
  date DATE
  );
  
INSERT INTO test (value, date) VALUES
  (10, '2015-12-01'),
  (20, '2016-01-01'),
  (30, '2016-02-01')
  ;
```

Query using SQL editor and bar graph visualization:
<img width="944" alt="screenshot 2016-02-06 08 50 34" src="https://cloud.githubusercontent.com/assets/218825/12867894/bffe28a2-ccae-11e5-8fbe-d19133ad8644.png">

**Comment by camsaul** [comment]
@dudleycarr can you try casting the column back to a `DATE` or `TIMESTAMP`?

**Comment by dudleycarr** [comment]
@camsaul I tried both and both render the graph exactly the same.
