### ISSUE TITLE
Stickers on Dashboard 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1897]
I've had what feels like hundreds of people ask me for this. Can we add stickers to dashboards? Similar to the way they work on trello but also including [kimoji](http://m.eonline.com/news/725692/there-s-a-kimoji-for-every-moment-in-your-life-here-are-the-14-best-ways-to-use-them)

**Comment by salsakran** [comment]
Nooooope.

**Comment by camsaul** [comment]
💔  I feel like one day we *will* want this!
