### ISSUE TITLE
Funnel chart showing retained NaN% when all rows from aggregate column are zero

### ISSUE THREAD

**Issue by victorfeijo** [metabase/metabase#18980]
**Describe the bug**
When using a **funnel** as the visualization option for a question result, and all rows from aggregate column are resulting in `0`, the retained percentage will be shown as `NaN%`. 

**To Reproduce**
1. Go to 'Ask a question';
2. Choose any option to write your question;
3. Create a question and make sure you have two columns: the description and the aggregation, where all rows from the aggregation are resulting in `0`;

![image](https://user-images.githubusercontent.com/8865899/141731945-41a01c0c-6198-4f83-9964-3b35192f58d6.png)
4. Change the visualization to funnel;
5. See the retained values as `%NaN` below:

![image](https://user-images.githubusercontent.com/8865899/141732071-c3c7baf7-40f7-4fcd-975d-728c18734ad9.png)

**Expected behavior**
Show all retained values as `%0`, similar to when only the first row result is a positive value:

![image](https://user-images.githubusercontent.com/8865899/141732734-399c6792-57c6-4052-8ca9-79ec9a842b66.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Google Chrome, Version 95.0.4638.69 (Official Build) (arm64)
- Your operating system: macOS Big Sur 11.4 (20F71)
- Your databases: Postgres
- Metabase version: v0.41.2
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

**Severity**
Honestly, I'm not sure if you guys are already aware of this behavior and don't really consider a bug that worth fixing it. In my opinion I don't see many use cases where all the data from the funnel will be 0, so the `NaN%` may be shown in very few cases.

In the other hand, the reason why I came across with this issue is because we're using the funnel as an embedded chart for our main app and there are scenarios where the customer don't have any data. One of the ways of fixing it on our side would be to just show an empty state, which is probably what we will end up doing. Anyway, I think it's worth to communicate to you guys about the bug. Hope this is helpful :)

**Comment by flamber** [comment]
Hi @victorfeijo 
Yeah, dividing with zero is difficult ;-)

Reproduce:
1. Native query
```
select 'a' col1, 0 col2
union all select 'b', 0
union all select 'c', 1
```
2. Change to Funnel
![image](https://user-images.githubusercontent.com/1447303/141747156-8eaf7023-8e07-46fa-a85c-50b2fad51697.png)
