### ISSUE TITLE
Append Card instead of Prepend on Dashboard

### ISSUE THREAD

**Issue by styledev** [metabase/metabase#1898]
When adding a question* to a dashboard it should append to the cards already listed instead of prepending as this severely disrupts the layout of the dashboard which requires relaying out every card.

* only happens when adding to dashboard after saving a new question. Adding from a saved question seems to add it to the bottom left of the layout.

Starting Dashboard:
![1-start](https://cloud.githubusercontent.com/assets/12783/12873252/6641294e-cd6d-11e5-95ac-d2b43bb7a6f3.png)

Dashboard after adding a new question:
![2-add-new-question](https://cloud.githubusercontent.com/assets/12783/12873250/663fe0a2-cd6d-11e5-9e37-0da04f6cf4c2.png)

Dashboard after adding a saved question:
![3-add-saved-question](https://cloud.githubusercontent.com/assets/12783/12873251/66409e48-cd6d-11e5-9f3c-0106036f4fb2.png)

**Comment by tlrobinson** [comment]
This appears to be resolved in 0.15. Can someone else verify?

**Comment by salsakran** [comment]
Tested it against 0.15 and it appended. So looks resolved.
