### ISSUE TITLE
Support additional connection parameters on postgres driver

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1899]
Details provided here ... http://discourse.metabase.com/t/is-it-possible-to-disable-prepared-statements-when-connecting-to-pg/222

> I would like to connect through a connection pool (pgbouncer) in transaction mode but get prepared statement
> "S_1" does not exist errors
> 
> The following jdbc connect option would prevent this
> 
> `prepareThreshold=0`

**Comment by salsakran** [comment]
@camsaul + @agilliland What needs to be done in terms of design or further scoping before this can be worked on?

**Comment by agilliland** [comment]
From a UX perspective we'd just want to have an updated design for the 1) the database add/modify page and 2) setup flow add database step which allows for adding in optional parameters like this.

My recommendation would be that we design 1) so that every database has some "advanced" section which allows for arbitrary input of additional options.  For 2) we can probably just leave that out to keep the setup flow simple, but i'll let Maz and Kyle figure that out.

Once we have a sense for how we want to present this the rest should be actionable right away.

**Comment by camsaul** [comment]
I don't think we want to allow someone to disable prepared statements. All our our QP-generated queries use prepared statements for security (e.g., to prevent SQL injection attacks). Disabling prepared statements would effectively break all queries generated using the query builder.

**Comment by salsakran** [comment]
@camsaul Doh. That makes sense. I hadn't really spent much time looking at the specific parameter but noticed this and I believe some SQL Server params that people wanted to pass as an abstract concept. I think we should rename the issue to match that abstract use case.

**Comment by camsaul** [comment]
There are a lot of settings we want to make sure are set a certain way (e.g. for H2 we set params to make sure only existing files are open, for MySQL we set params to return `nil` instead of `00-00-0000` for `NULL` dates ). Accepting arbitrary params would make it easy for people to put in ones that break something (such as `prepareThreshold=0`), or ones that we'd have to override (which could lead to confusion when the connection string they put in wasn't actually the one we used to connect to the database).

Instead we might consider continuing to add ones that people actually need as they come up. There realistically aren't that many options that people need to specify.

**Comment by agilliland** [comment]
I took a quick look at the Postgres docs and I don't see how `prepareThreshold=0` suggests disabling prepared statements.  This is the definition of that property in their docs ...

> Determine the number of PreparedStatement executions required before switching over to use server side prepared statements. The default is five, meaning start using server side prepared statements on the fifth execution of the same PreparedStatement object.

https://jdbc.postgresql.org/documentation/head/connect.html

In any case, I don't mind forcing certain parameters to be set a certain way if they are part of the way the driver is written and aid in the execution of the queries, but I think we should support the option to let users input the parameters they need without our intervention.  It's a drag to require a GH issue, a code change and a PR every time we want to support a new parameter on a database, and during that time the user who was interested in Metabase may have left and decided to use something else.  

Being flexible on connection parameters allows users with specific connection needs to move forward using the product and if their parameter causes an issue then we can have them report it and we'll deal with it then.

**Comment by camsaul** [comment]
Implemented by #3765
