### ISSUE TITLE
Sort by aggregation show as "[Unknown Field]" in automatic question name

### ISSUE THREAD

**Issue by pawit-metabase** [metabase/metabase#19005]
**Describe the bug**
When a table is sorted by aggregation, the automatic question name shows "[Unknown Field]" instead of the aggregation.

**Logs**
N/A

**To Reproduce**
1. Open sample dataset -> People
2. Summarize -> Category
3. Visualization -> Table
4. Sort by count ascending
5. Click save, you will see the default name is `Products, Count, Grouped by Category, Sorted by [Unknown Field] ascending`

**Expected behavior**
The default name should end with `Sorted by Count ascending`

**Screenshots**
<img width="1207" alt="Screen Shot 2564-11-16 at 16 29 11" src="https://user-images.githubusercontent.com/88995137/141959060-22984197-e70a-4e23-9246-32896d5d780d.png">

**Information about your Metabase Installation:**
Metabase 1.41.1 (also happens on master)
Chrome 95

**Severity**
Does not block anything but makes the product looks unpolished.

**Comment by flamber** [comment]
Related to #3921
