### ISSUE TITLE
Database permissions page crashes if a nested question has been viewed previously

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#19000]
**Describe the bug**
If you've viewed a nested question in the query builder and subsequently go access data permissions without refreshing the browser, you'll get stuck in an infinite rerender loop as some function throws an error.

**Logs**
![Screen Shot 2021-11-15 at 4 58 28 PM](https://user-images.githubusercontent.com/13057258/141876492-5fd9f46f-4b54-4a28-844b-81a6e8d6142a.png)

**To Reproduce**
1. Native Query builder > Sample dataset > `select * from PRODUCTS` query
2. Save the question
3. Click "Explore Results"
4. Click save again to save a nested question
5. Without refreshing, navigate to Admin > Permissions > and click the "Databases" option in the left menu
6. See that the page breaks

**Expected behavior**
The page shouldn't crash -- I'm guessing we need to filter out databases with ids like `card__123`

**Recording**

https://user-images.githubusercontent.com/13057258/141876791-02baf8ea-5e2a-4e2d-9632-1ccbbd97e71d.mov

**Information about your Metabase Installation:**
This is on `master` but I think `41` is also affected by this.

**Severity**
There's a simple workaround (refresh the page before going into permissions stuff). However, it isn't obvious that you're affected by this until it happens, and then your browser tab has crashed, so I think this is fairly severe.

**Comment by flamber** [comment]
I've not been able to reproduce this - neither on 0.41.2 or `71ee1ea`

**Comment by flamber** [comment]
@daltojohnso Is this still a thing?
