### ISSUE TITLE
years sometimes being shown as comma separated integers on x axis of charts

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1901]
Not sure how best to prevent this but in this case we have a column named year being used for a breakout and marked as a category in the data model. The result is that the year 2002 is being shown as 2,002

<img width="1399" alt="screen shot 2016-02-08 at 11 19 38 am" src="https://cloud.githubusercontent.com/assets/5248953/12896386/85ed54d6-ce56-11e5-830e-3c70fd85421b.png">

**Comment by mazameli** [comment]
I thought I'd created an issue a couple of months ago, but I can't find it now — but it was basically a suggestion to include a new metadata type called "Year," for just this purpose.

**Comment by camsaul** [comment]
If it helps I can open an issue to look through the issues for your issue

**Comment by mazameli** [comment]
:trollface:

**Comment by camsaul** [comment]
If there's an issue with finding your issue in the open issues we can find time to open the issue anew so you won't run into a new issue next time you try to find it 💔

**Comment by camsaul** [comment]
Can we just format *all* 4-digit integers without a comma? That's a pretty common styley thing and seems like the easiest fix

> Either group the thousands in a four-digit number or do not, but not mixed use in the same article.

**Comment by tlrobinson** [comment]
If that's an acceptable solution I can go ahead and disable commas for 4 digit numbers (but leave enable for > 4?)

**Comment by kdoh** [comment]
@tlrobinson I think that makes sense. However I'd just clarify we should be doing that in our axis display of 4-digit integers, not everywhere. I'm also wondering if it makes sense to just remove commas on the X axis as its the place where this is most likely to occur. It could be handy to have that comma for Y axis values.

**Comment by tlrobinson** [comment]
Why just axis? We'd still have the same issue in tooltips and tables.

**Comment by camsaul** [comment]
I feel like using commas for some 4-digit numbers but not others would look a bit accidental. :scream:

**Comment by kdoh** [comment]
Fair point. What I was mainly saying was that it makes sense to keep the comma formatting with things like a scalar, or certain types values with specific metadata (currency or other numeric types where the comma helps the user parse) since the main thing here is that the formatting feels wrong when the field name is year but the value is being shown in a non typical year format.

In terms of it looking accidental I'm not sure this is a case where consistency for consistency's sake makes sense. There are definitely times when having commas helps with legibility of values and others where it can make something feel off or ambiguous, so ideally we can use the metadata as much as possible to prevent that.
