### ISSUE TITLE
Allow dashboard filters to apply on custom text columns

### ISSUE THREAD

**Issue by cjwooo** [metabase/metabase#19013]
**Is your feature request related to a problem? Please describe.**
We have multiple dashboards that have questions that contain custom text columns. For example, we have a set of questions that uses a regex to parse a string id from a text column in a dataset. We want to create a dashboard filter that applies to this column. However, when creating a category filter in the dashboard, the custom column is not a selectable choice in the dropdown list of filterable columns for a question.

**Describe the solution you'd like**
We'd like custom text columns to be allowed choices when creating a dashboard filter of the "Other Categories" type.

**Describe alternatives you've considered**
n/a

**How important is this feature to you?**
This is an exact request from one of our customers.

**Additional context**
Create a custom column on a basic question on sample data:
![image](https://user-images.githubusercontent.com/4491213/142079948-0f86a4e8-676f-4cc6-8337-a6ac27a62181.png)

"Custom Tax Column" is not selectable when creating a dashboard filter:
![image](https://user-images.githubusercontent.com/4491213/142080018-cc820563-a2d7-4766-815c-cc28af1f2df0.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Inferred type wasn't available until 0.40, which then made some of this possible, but with some problems #17775
It would likely also depend on #13186

**Comment by amaozhang** [comment]
Any chance I could get some insight on where this falls on the roadmap? I get the dependencies which add to the complexity so if it's not planned for a while, we'll probably just invest in the workaround which is to add the field to our table :)
