### ISSUE TITLE
Emoji's rendered black

### ISSUE THREAD

**Issue by BenjaminGK** [metabase/metabase#19028]
**Describe the bug**
After the latest Chrome update (v96) emoji's used in reports are rendered black instead of being in color.
The problem is probably rather in Chrome than in Metabase, but reporting it regardless

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Update to latest version of Chrome
2. write new sql query
3. add emoji
4. See emoji being rendered black

**Expected behavior**
emojis are still rendered in color

**Screenshots**
![image](https://user-images.githubusercontent.com/23311430/142349488-a986941b-b24a-469a-9cfd-4c2c01f77a71.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.11.0-1021-aws",
    "user.language": "en",
    "user.timezone": "Europe/Stockholm"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.33-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": "Europe/Stockholm"
    }
  }
}
```

**Severity**
Minor issue, but an annoyance for a lot of our users

**Additional context**

**Comment by flamber** [comment]
Hi @BenjaminGK 
I guess it's something specific to Chrome and Windows - likely change of default fonts.
Can you try seeing if https://emojipedia.org/ok-hand/ looks normal? If so, use the browser developer toolkit to try seeing which fonts makes it work or not.
I cannot reproduce on Linux with Chrome 96.0.4664.45: `select '👌'`
![image](https://user-images.githubusercontent.com/1447303/142377596-f97caa0b-e333-4986-9d63-299b2fec5fb0.png)

**Comment by BenjaminGK** [comment]
@flamber Emoji's there look just fine and from what I can see in inspect is that it is using the font color from lato, 
![image](https://user-images.githubusercontent.com/23311430/142386407-e5a9b818-f355-4a83-8a45-b108b93e0449.png)
if I use the same emoji in Google Docs as example, it is shown with color

**Comment by flamber** [comment]
@BenjaminGK Metabase uses an ([older](https://github.com/metabase/metabase/tree/master/resources/frontend_client/app/fonts/lato-v16-latin)) Lato font, if your system doesn't have the font.

I'm wondering if Chrome changed something with their fonts, so it now it defaults to something different.

One thing that I notice is the lowercasing of `"lato"` - it [should be](https://github.com/metabase/metabase/blob/5951e47f7b909e07007d43e6483dd605edf8d5a8/frontend/src/metabase/css/core/base.css#L58-L70) `"Lato"`
Can you try these two families?
`font-family: "Lato", sans-serif;`
`font-family: "Lato", sans-serif, emoji;`

Could you do me a favor and try with Firefox? I doubt we can get some information here, since Firefox of course behaves differently than Chrome. It has this awesome Fonts panel:
![image](https://user-images.githubusercontent.com/1447303/142388239-41cc2d5d-c4ca-409d-be5c-d6dee1319b4a.png)

**Comment by flamber** [comment]
@BenjaminGK And what if you change to `font-family: "Lato", sans-serif, emoji;` ? My guess is that it would be working too.

**Comment by BenjaminGK** [comment]
@flamber On Firefox, that still works, but nothing changes in Chrome.

**Comment by mreloaded** [comment]
Sounds like this bug, is the font bold by any chance? https://bugs.chromium.org/p/chromium/issues/detail?id=1266022

**Comment by BenjaminGK** [comment]
@mreloaded it happens both for bold and regular text - if we have table view with several rows where it is still happening

**Comment by flamber** [comment]
`font-weight: 700;` so that definitely sounds like it's the problem. Metabase is not going to change this. Chrome has to fix it.
