### ISSUE TITLE
Waterfall not showing as waterfall in slack static viz

### ISSUE THREAD

**Issue by howonlee** [metabase/metabase#19025]
We found this in internal MB engineering slack static viz reports from the dashboard sub. Waterfall static viz should now be happening for waterfall cards but are not for slack static viz reports, instead it's happening as table

Repro steps:
1. Make a card with waterfall visualization type
2. Put it in a dashboard
3. Put in a slack dashboard sub for it
4. Trigger slack dashboard sub manually
5. It won't do a waterfall static viz, just a table one

**Comment by flamber** [comment]
Part of #18676

**Comment by rlotun** [comment]
also doesn't show in email (this is from dashboard subscription of Eng dashboard on stats):
![Screen Shot 2021-12-13 at 9 42 37 AM](https://user-images.githubusercontent.com/65313/145861789-fd4e330c-0580-40e0-a44d-5c39763e877a.png)

**Comment by rlotun** [comment]
fixed by https://github.com/metabase/metabase/pull/19563
