### ISSUE TITLE
When filtering by Entity Key, then most options are hidden in Simple GUI

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19031]
**Describe the bug**
When filtering by Entity Key, then it hides all filters and the Filtering/Summarize buttons in Simple GUI.
This can be specially confusing, when accidentally inputting a wrong value, so there's "No results".

**To Reproduce**
1. Simple question > Sample Dataset > Products - Filtering: "Category"=`Gizmo`
![image](https://user-images.githubusercontent.com/1447303/142412156-149731f7-8b1d-45cb-a03e-5a953f94918f.png)
2. Now add another filter (of the Entity Key), "ID"=`2022` (non-existing value) - it quickly flashes the filters before hiding them:
![image](https://user-images.githubusercontent.com/1447303/142412472-3ccb3e50-fc70-4895-a62a-661d2ae7a96c.png)

**Expected behavior**
Do not try to go into ObjectDetail view, when there's no results.
I would prefer to always have the filters shown, but that's a Product call: https://github.com/metabase/metabase/pull/16614#pullrequestreview-685369588

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.41.2

**Comment by brunobergher** [comment]
Not reproducible anymore.
