### ISSUE TITLE
Saving/updating questions can take a very long time (seconds or minutes) on large instances

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19053]
**Describe the bug**
Saving/updating questions can take a very long time (seconds or minutes) on large instances

Workaround - see step 3.

**To Reproduce**
1. Add a few million rows in `query_execution`
<details><summary>10 million row generator</summary>

I got 959 questions on this test instance, but I actually don't think that matter much, though update 959 to match your max report_card.id. Also adjust database_id (4).

**Warning** this query will take a long time to generate all these rows.

```
do $$
begin
for r in 1..10000000 loop

INSERT
  INTO
  public.query_execution
(
    hash
    , started_at
    , running_time
    , result_rows
    , native
    , context
    , error
    , executor_id
    , card_id
    , dashboard_id
    , pulse_id
    , database_id
    , cache_hit
  )
VALUES(
  sha256(concat('select ', floor(random()* (959-1 + 1) + 1)::int::text)::bytea)
  , ( NOW() + ( random() * ( INTERVAL '-730 days' ) ) )
  , floor(random()* (10000-1 + 1) + 1)::int
  , floor(random()* (2000-1 + 1) + 1)::int
  , TRUE
  , 'question'
  , NULL
  , 1
  , floor(random()* (959-1 + 1) + 1)::int
  , NULL
  , NULL
  , 4
  , FALSE
);

end loop;
end;
$$;
```

</details>

2. Native query > `select 1` - save as "Q1" - will take many seconds before the question is saved. On my setup 60+ seconds.
3. Add the following index:
`CREATE INDEX idx_query_execution_card_id_started_at ON public.query_execution USING btree (card_id, started_at);`
4. Native query > `select 2` - save as "Q2", saving will take less than a hundred milliseconds (expected speed on my setup)

**Information about your Metabase Installation:**
Tested 1.41.2 with Postgres appdb

**Comment by camsaul** [comment]
In #18759 we added an index on `query_execution.card_id`... I'm assuming that didn't improve things at all? I'll have to dig in to things and figure out what query is causing the slowness here

**Comment by camsaul** [comment]
Ok, so the problem here is with hydrating `:last_query_start` for the `Card` that gets returned, which is handled by this code: https://github.com/metabase/metabase/blob/master/src/metabase/models/card.clj#L50-L60

It runs a query like this:

```sql
 SELECT max(started_at) 
FROM query_execution 
WHERE card_id = 1413 
  AND cache_hit <> TRUE
  AND running_time IS NOT NULL;
```

The problem here is the we have an index on `started_at` and an index on `card_id` but not an index on both columns. It ends up using the index on `started_at` which is crazy-slow instead of the one on `card_id` which would have been fast:

```
metabase=# EXPLAIN SELECT max(started_at) FROM query_execution WHERE card_id = 1413 AND cache_hit <> TRUE and running_time IS NOT NULL;
                                                              QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------
 Result  (cost=93.39..93.40 rows=1 width=8)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.43..93.39 rows=1 width=8)
           ->  Index Scan Backward using idx_query_execution_started_at on query_execution  (cost=0.43..961737.12 rows=10346 width=8)
                 Index Cond: (started_at IS NOT NULL)
                 Filter: ((NOT cache_hit) AND (running_time IS NOT NULL) AND (card_id = 1413))
```

The main reason this is so slow is that there will be no entries for the Card the first time this is ran which means this will end up scanning thru every QueryExecution row, and will never find an entry.

There wasn't really any sensible way that I could find to rework the query but adding another index as @flamber suggested fixes the problem:

```
metabase=# EXPLAIN SELECT max(started_at) FROM query_execution WHERE card_id = 1413 AND cache_hit <> TRUE and running_time IS NOT NULL;
                                                                 QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------
 Result  (cost=4.34..4.35 rows=1 width=8)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.43..4.34 rows=1 width=8)
           ->  Index Scan Backward using idx_query_execution_card_id_started_at on query_execution  (cost=0.43..40407.30 rows=10346 width=8)
                 Index Cond: ((card_id = 1413) AND (started_at IS NOT NULL))
                 Filter: ((NOT cache_hit) AND (running_time IS NOT NULL))
(6 rows)

metabase=# SELECT max(started_at) FROM query_execution WHERE card_id = 1413 AND cache_hit <> TRUE and running_time IS NOT NULL;
```
