### ISSUE TITLE
deselect all 

### ISSUE THREAD

**Issue by Idreesqbal** [metabase/metabase#19056]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by Idreesqbal** [comment]
If you are working with a table with tons of columns it is a nightmare deselecting columns...currently, there is only 'Select all' but no deselect all... it will awesome to have the 'Deselect all' feature added.

**Comment by flamber** [comment]
Duplicate of #10460
