### ISSUE TITLE
Simplify additional options in set up flow db configuration

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#19057]
**Links**
Product doc: https://www.notion.so/metabase/Simplify-additional-options-in-set-up-flow-db-configuration-574685f825a34f5595011d0680451ea4#fa37841193954649837cc99d092e9365
Engineering doc: https://www.notion.so/metabase/Advanced-database-options-d6d5c8a5f9b4414cab8f8e47858b1b39

**Comment by flamber** [comment]
Duplicate of #19046 ?
