### ISSUE TITLE
When creating a Pivot Table, setting a custom column title does not work.

### ISSUE THREAD

**Issue by arielschvartz** [metabase/metabase#19063]
**Describe the bug**
I'm trying to create a Pivot Table and everything is working fine, but when I try to change the column title to a custom title even though I change it in the settings panel, it still shows the default name like "Sum of count".

**Information about your Metabase Installation:**
Using metabase version 0.41.0.

**Severity**
It is not severe, but would help our users if we could set the right names. Hope it is an easy fix and the Metabase team can fix it easily! =)

**Comment by flamber** [comment]
Duplicate of #15353
