### ISSUE TITLE
CSV downloads are broken on large queries

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1908]
related to #1758 , which has been resolved, but the problem remains for the CSV download links which attempt to encode the entire query as a query parameter in a GET request.  The end result is that if you write a really long SQL query and attempt to download the result you'll get a 414 error from the server.

**Comment by camsaul** [comment]
To save someone else from having to go look this up. 414 = "Request URI too long"

**Comment by earlreyes** [comment]
This still appears to be a problem on 0.15.1.1 I attempt to download the csv locally, I receive a popup that  Your data has been saved, but the file is not created.

**Comment by agilliland** [comment]
@earlreyes before I consider reopening this I'll need some more details to reproduce.  you'll also want to fill out these details ...

*  I am using the ___________ browser.
*  My computer's OS is ___________.
*  I'm running Metabase ___________. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is ___________.
*  My Metabase version is ___________.
