### ISSUE TITLE
Message "No results!" is not translated on Embedded/Public

### ISSUE THREAD

**Issue by lubka272** [metabase/metabase#19107]
**Describe the bug**
I use Slovak language. String "No result!" has translation in
https://github.com/metabase/metabase/blob/master/locales/sk.po but in query of published question or dashboard it is in English "No result!"

In unpublished question it is working fine. In inpublished dashboard its also in english.

**Comment by flamber** [comment]
It works fine:
![image](https://user-images.githubusercontent.com/1447303/143589210-05870ef9-57f2-423d-b980-dae46c0416ad.png)

**Comment by lubka272** [comment]
Yes it works fine, but not in published questions or dashboards. First image is in metabase and second in published question.
![image](https://user-images.githubusercontent.com/66225383/143590086-c65d384c-ce0d-40c3-9230-2924ed124897.png)
![image](https://user-images.githubusercontent.com/66225383/143590124-716737c7-8c02-4def-9e79-c6c1d3898cc0.png)

**Comment by albertoperdomo** [comment]
Can't reproduce on 47.6. Works as expected.
