### ISSUE TITLE
Wrong label display in Chart 

### ISSUE THREAD

**Issue by sleanodlh** [metabase/metabase#19118]
**Describe the bug**
I have "Fiscal Year" and the labels should display "2020","2021" and "2022" respectively. But it's showing differently. Below are screenshots of my data presented in tabular and graphical forms. Fiscal Year is defined as a "Category"
![image](https://user-images.githubusercontent.com/95237076/143903722-65af3339-93ac-4d74-82cd-0a59065b5365.png)

**To Reproduce**
My Native Query
select 2020 as fiscalyear, 200 as Quantity union
select 2021 as fiscalyear, 100 as Quantity union
select 2022 as fiscalyear, 150 as Quantity 

1. Summarize by Calculating the summary of Quantity
2. Grouped by Fiscal Year
3. Change visualization to Bar Graph 

**Expected behavior**
The label should reflect the correct value 

**Screenshots**
![image](https://user-images.githubusercontent.com/95237076/143903318-e1b4b86d-ea0c-43b6-b133-6d9535b47ec8.png)
![image](https://user-images.githubusercontent.com/95237076/143903423-b5d5992c-17bd-4278-8c1d-bcf18633fd19.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.1+9",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.1+9",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.1.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.8-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Our end-user might deemed our report erroneous because of the inaccurate label being displayed and would also make our report unreliable.

**Comment by flamber** [comment]
A workaround is to change the "X-axis style" to anything different than "Timeseries"
![image](https://user-images.githubusercontent.com/1447303/143907705-288acfa7-c753-4c76-8fbd-6267eb4799e8.png)

**Comment by sleanodlh** [comment]
it works. Thanks

**Comment by flamber** [comment]
We still want to fix this issue.
