### ISSUE TITLE
Moderation feature nowhere to be found

### ISSUE THREAD

**Issue by codingjoe** [metabase/metabase#19113]
**Describe the bug**
According to the [v0.41.0 release notes](https://github.com/metabase/metabase/releases/tag/v0.41.0), there is a new official or verified reports feature. However, after reading the announcement email as well as the documentation, the feature is nowhere to be found in the OSS version despite its announcement. I presume this is an error? Either documentation or (preferably) merge error?

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
https://github.com/metabase/metabase/tree/381d2f72dc534a7a97af6e8fa2cf436ccd7c42d8/enterprise/frontend/src/metabase-enterprise/moderation

**Expected behavior**
Well the documentation suggests this is an OSS feature.

**Comment by flamber** [comment]
Hi @codingjoe 
Everything within `/enterprise/` is functionality that is only available on the Pro and Enterprise editions.
https://www.metabase.com/docs/latest/users-guide/06-sharing-answers.html#question-moderation

**Comment by codingjoe** [comment]
Hi @flamber,

Thank you for your swift response. I am sad that this won't be available to the community.
Anyhow, might I suggest adding the feature to the pricing feature matrix and maybe altering the release notes?

Thanks,
Joe

**Comment by flamber** [comment]
@codingjoe We're still working on that, since Pro is quite new too. A lot of places needs to be updated, and we need separated release notes.
