### ISSUE TITLE
Filter not visible in other dashboard when passing filter value

### ISSUE THREAD

**Issue by sleanodlh** [metabase/metabase#19122]
**Describe the bug**
I want to pass my dashboard's filter value to another dashboard but I can't found the filter on the linked dashboard.

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.1+9",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.1+9",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.1.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.8-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**To Reproduce**
1. Create a dashboard (DB1)
2. Put 1 question
3. Put a random table
4. put (2 or more) filters in the dashboard
5. assign the filters to the question
6. Duplicate DB1 as DB2
7. Edit DB1 and change the Questions behavior to 
     "Go to a custom destination" 
     Link to Dashboard
     Choose DB2
8. Under "Pass values to this dashboard's filters (optional)"
    Choose the first filter
9. It should also appear under "Dashboard filters" but it's not
 

**Expected behavior**
All filters in the linked dashboard must be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/95237076/143930684-10d46bad-8313-4779-b1fa-56b15f07980a.png)

Fiscal Year filter is missing
![image](https://user-images.githubusercontent.com/95237076/143931032-fae855df-e1bc-481a-b603-6dcf82b50251.png)

**Severity**
This problem does not maximize the full feature of Metabase. We want to minimize user data entry on filters as much as possible especially when navigating across different dashboards with similar and re-usable filters.

**Comment by flamber** [comment]
Hi @sleanodlh 
I cannot reproduce, but I'm guessing that it might have something to do with your question metadata (or filter types, if you're using SQL).
Can you reproduce using the Sample Dataset?

**Comment by sleanodlh** [comment]
I saw it now. What I did, was just the turn around. I re-created all the filters. But I hope that there is a way for us not to do this and not to also go into report_dashboardcard.parameter_mappings
