### ISSUE TITLE
Sample Dataset needs a tax cut

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1914]
100% sales tax rate is a bit aggressive, don't you think?

![screenshot 2016-02-10 13 24 26](https://cloud.githubusercontent.com/assets/18193/12962274/9fa23be0-cff9-11e5-9c9f-ec601894d543.png)

**Comment by camsaul** [comment]
Yup looks like the logic for generating sales tax looks up the tax rate and then promptly forgets to use it :sweat: 

![screen shot 2016-02-10 at 1 27 19 pm](https://cloud.githubusercontent.com/assets/1455846/12962421/18d3fcf6-cffa-11e5-95c4-410dc5661ca7.png)
