### ISSUE TITLE
In Metabase Api , clojure Keyword :dimension is not identified properly 

### ISSUE THREAD

**Issue by vishal-nagarajan** [metabase/metabase#19155]
**Describe the bug**
Input to value-for-tag does not match schema: [0;33m [(named (named {:type (not (#{:date :number :snippet :card :dimension :text} "dimension"))} "valid template-tags tag") tag) nil] [0m

**To Reproduce**
Try to create a card with dropdown filter of a field which is of Category semantic-type. (Ask a question in Native Query)
The request body with template-tags will have a field type which should be given "dimension" for reproducing the same error.

**Bug**
The bug is that the clojure code in the Api's back end is able to parse and map :date ,:number, :snippet and  :card when passed in the request body but it is not parse :dimension it throws Input to value-for-tag does not match schema.

**Comment by flamber** [comment]
Hi @vishal-nagarajan 
I don't know what you're trying to show, but try using the GUI and look in your browser Network-tab to see the request that Metabase generates and then match that with what you're trying to do in the API.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
