### ISSUE TITLE
clicking on links on the QB initially reloads the same location and requires a second click to actually register

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1917]
This affects: 0.15.0-development
To reproduce: load up the QB via saved question or new question, click on any link in the Navbar.

The initial click does nothing, but if you click the link again you'll get the normal behavior.  I believe this started occurring after the change to the hash based serialized queries in #1856

**Comment by tlrobinson** [comment]
Actually I recall this happening sometimes after integrating the qb tutorial but I wasn't able to reliably reproduce it.
