### ISSUE TITLE
BigQuery and Google Analytics drivers broken on x.41.3

### ISSUE THREAD

**Issue by lucemia** [metabase/metabase#19173]
**Describe the bug**

All BigQuery related query are failed with Error Message
`No method in multimethod 'execute-reducible-query' for dispatch value: :bigquery` 

![截圖 2021-12-02 下午3 47 09](https://user-images.githubusercontent.com/432851/144379507-079cb941-38f5-4f7d-8c50-966b2ae309b2.png)

**Metabase Diagnostic Info**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.4.109+",
    "user.language": "en",
    "user.timezone": "Asia/Taipei"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.36-google-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-01",
      "tag": "v0.41.3",
      "branch": "release-x.41.x",
      "hash": "b0ac6f2"
    },
    "settings": {
      "report-timezone": "Asia/Taipei"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by lucemia** [comment]
downgrade to `metabase/metabase:v0.41.2` fixed this issue

**Comment by flamber** [comment]
@lucemia Try changing to the new BigQuery driver - change it in Admin > Databases > (your-db).

**Comment by lucemia** [comment]
> @lucemia Try changing to the new BigQuery driver - change it in Admin > Databases > (your-db).

I got another Error while chaning the new driver.
`java.lang.NoSuchMethodError: com.google.api.client.http.HttpTransport.isMtls()`

**Comment by flamber** [comment]
@lucemia On 0.41.3 or 0.41.2?

**Comment by lucemia** [comment]
> ```json
> v0.41.3
> ```

v0.41.3

**Comment by lucemia** [comment]
v0.41.2 works with new BigQuery driver.

**Comment by flamber** [comment]
@lucemia Do you have multiple BigQuery databases? And only changed some of them to the new driver?
I think if you change all of them to the new driver and restart Metabase 0.41.3, then it would work.

**Comment by lucemia** [comment]
> @lucemia Do you have multiple BigQuery databases? And only changed some of them to the new driver? I think if you change all of them to the new driver and restart Metabase 0.41.3, then it would work.

- No, I don't have multiple BigQuery database while using 0.41.3
- I only have one BigQuery database, I cannot change it to new driver due to `java.lang.NoSuchMethodError: com.google.api.client.http.HttpTransport.isMtls()` issues on Metabase 0.41.3.
- I cannot add a new database with new BigQuery driver either on Metabase 0.41.3 due to the same `java.lang.NoSuchMethodError: com.google.api.client.http.HttpTransport.isMtls()` issues
- After I downgraded to 0.41.2, I am able to add a new database with new BigQuery driver.

**Comment by jakehobbs** [comment]
I'm getting the same error for GA after updating to the latest version.

```No method in multimethod 'execute-reducible-query' for dispatch value: :googleanalytics```

**Comment by flamber** [comment]
@jakehobbs 
Metabase does not have automatic update unless you have configured some external process for that in your system.
Post "Diagnostic Info" from Admin > Troubleshooting.

**Comment by jakehobbs** [comment]
> @jakehobbs
> Metabase does not have automatic update unless you have configured some external process for that in your system.
> Post "Diagnostic Info" from Admin > Troubleshooting.

Thanks for pointing that out. Our server is set up to pull down the new Docker image whenever one is published. It looks like a new image was published to Docker Hub ~8 hrs ago, which triggered our server to update. That is when the error started occurring.

**Comment by jakehobbs** [comment]
I just rolled back my server to v0.40.6. The issue does not occur in that version.

fyi @flamber

**Comment by janmpeterka** [comment]
Having similar issue - cannot connect to Google Analytics:
`No method in multimethod 'can-connect?' for dispatch value: :googleanalytics` in 0.41.3 (cannot say if worked in previous).

**Comment by jeff303** [comment]
Apologies to everyone affected by this.  There is a new version, `x.41.3.1` that fixes this issue.
