### ISSUE TITLE
Line/Bar/Area charts should support linear X axis scale

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1918]
We support time and ordinal scales on the X axis, but not linear. Showing an ordinal scale for a numeric dimension can be misleading.

The simplest logic would be to use a linear scale if the dimension is numeric. However, if the results are sparse enough it may be better to use an ordinal scale.

**Comment by agilliland** [comment]
It would be good to get a more concrete example of what you mean by a linear scale.  Based on these definitions are you suggesting an interval scale?  https://en.wikipedia.org/wiki/Level_of_measurement

Which would be to say that if the x-axis is a series of numbers such as 5, 25, and 150 that instead of placing 3 tick marks equally spaced apart (which would be an ordinal scale) that instead you feel the scale is now very clearly from 5 - 150 and the value for 25 should be appropriately aligned closer to the 5 on the axis instead of simply right in the middle of the 2 other values?

I believe this is the same scale that time series charts use.  each period of time is an interval on the scale based on its granularity (day, week, month, etc) and thus if your data only includes points for Feb 01, Feb 04, and Feb 21 you'd expect those values to be appropriately spaced out to show their relationship across the time and would not expect them to be event spaced on the axis.

**Comment by salsakran** [comment]
@agilliland example would be a data set:
[[1,100], [5, 124], [100, 154]]

By my understanding, an ordinal scale would have the distance between the first and second point on the axis be the same as the distance from the second and third, A linear scale would have that distance be 1/19th the distance between the second two points?

The real question is are we actually using ordinal scales for integer x-axes right now?!

**Comment by tlrobinson** [comment]
@agilliland I'm using the d3 terminology: https://github.com/mbostock/d3/wiki/Ordinal-Scales https://github.com/mbostock/d3/wiki/Quantitative-Scales but yeah I think "linear" corresponds roughly to "interval". 

> The real question is are we actually using ordinal scales for integer x-axes right now?!

@salsakran Yes, we are using ordinal scales everywhere except timeseries. Take this query for example. Notice 3.6 is filtered out, yet the width between 3.5 and 3.7 is the same as the width between 3.4 and 3.5, or 3.7 and 3.8, etc:

![screenshot 2016-02-11 11 35 11](https://cloud.githubusercontent.com/assets/18193/12988006/a2efc50a-d0b3-11e5-8456-947284371cd9.png)

**Comment by salsakran** [comment]
I'm going to quietly sob in a corner now.

+1000 on this issue.

**Comment by tlrobinson** [comment]
Oh and here's the comment in the code (which has been there at least a year or so): https://github.com/metabase/metabase/blob/master/frontend/src/card/card.charting.js#L832

**Comment by agilliland** [comment]
Generally makes sense to me to use a "linear" x-axis for numerical values.  As a final sanity check though, can we think of any examples where that would NOT make sense?

**Comment by mazameli** [comment]
Yikes. In that example chart above, I would have expected that 3.6 would still be present as a label, and the line would dip down to 0 at that point on the x-axis, before going back up at 3.7.

**Comment by salsakran** [comment]
It would make sense to use an ordinal scale if the numbers aren't actually intended to be treated as numbers but as identifiers, eg Enums or say zipcodes.

**Comment by agilliland** [comment]
@mazameli , what you are describing is realistically a separate issue and deals more with the desire for continuous ranges on the x-axis.  there is an issue for that specifically on time series, but it certainly could make sense to do it for linear axis as well

https://github.com/metabase/metabase/issues/896

**Comment by salsakran** [comment]
this would be a good place to add a `special_type` that signifies a numeric number vs a category number and use it

**Comment by tlrobinson** [comment]
@agilliland I was thinking if you're showing a bar chart and the data is very sparse it might make more sense to use the "ordinal" axis, otherwise you'd have very thin sparse bars. But I like @salsakran's idea of using the column metadata better.

Does it ever make sense to use ordinal axis on line/area charts?

**Comment by camsaul** [comment]
Sometimes charts have logarithmic scales and two I think, right :flushed: 
Maybe this should just be a visualization option for the chart, let people pick how the axis is scaled.

Related: This issue now has more pluses (+'es) than all other issues put together after Sammy did the +1000, is this worth a patch release?

**Comment by tlrobinson** [comment]
@camsaul I think log scales are more common on the Y-axis, but yes, that would be good to support too.

We haven't really been taking advantage of the "visualization settings" code we have in place. I know we should be keeping the UI as simple as possible (but not simpler), but it might be nice to expose more of this stuff to power users through a semi-hidden panel or something.

**Comment by camsaul** [comment]
We could event potentially offer quadratic, exponential, major, minor, pentatonic, and other exotic scales. I think you can do those on Excel

![image](https://cloud.githubusercontent.com/assets/1455846/12990147/98fb0d3e-d0bd-11e5-8445-c882229d18b3.png)

**Comment by spectr** [comment]
+1 This is huge

**Comment by bsellner** [comment]
+1 Agreed.  Our users cried a little (okay, a lot) when they found out about this (and the lack of scatter plots).

**Comment by mazameli** [comment]
So, I know we're looking into exposing axis scale options as part of overall charting improvements, but it still seems we never answered the question if there's a smarter default behavior that doesn't require changing any chart settings. I.e., like @tlrobinson said: 

> Does it ever make sense to use ordinal axis on line/area charts?

**Comment by tlrobinson** [comment]
Implemented in #3149, will be released in v0.20.0
