### ISSUE TITLE
Support private key authentication with Snowflake

### ISSUE THREAD

**Issue by markslater** [metabase/metabase#19191]
**Is your feature request related to a problem? Please describe.**
Metabase currently only supports username/password authentication with Snowflake.  In my experience, many enterprises (mine included) consider this form of authentication insufficiently secure, particularly for accounts that are used by processes rather than people.

Snowflake itself [supports private key authentication](https://docs.snowflake.com/en/user-guide/key-pair-auth.html), using either a key file or a JDBC connection property.  It would be great if private key authentication were made available through Snowflake!

**Describe the solution you'd like**
The simplest solution would appear to be making the password field optional when configuring Snowflake databases.  It's possible to set a private key file using the `Additional JDBC connection string options`, but the password seems to take precedence.  If it were possible to *not* set a password, the private key file setting could be used.

See also [the discussion on this topic](https://discourse.metabase.com/t/authenticating-with-snowflake-using-private-key/17548/3) on the Metabase discussion forum.

Private key file is preferred to supplying a private key literal, because it integrates well with Kubernetes secrets: Kubernetes can be configured to mount the key file so that it's available to Metabase without the value of the key ever being exposed to an administrator.

**Describe alternatives you've considered**
A more complete solution would be explicit support for private keys on Metabase's Snowflake database configuration page.

**How important is this feature to you?**
It's difficult to make the case for adopting Metabase to the security architects at my organisation without an alternative to username/password authentication.

**Additional context**
Based on Metabase 0.41

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by Gerald-Lim-Bose** [comment]
Private key auth was working for me in v 0.38 (at least with a Snowflake AWS deployment) but it broke sometime after. It is no longer working in 0.41.  It times out when the database connection is tested when I hit Save when adding the database. The main difference I see is that in the Snowflake add database screen for 0.41, the Region ID field is no longer available. 

For those who want to try this in v 0.38, there are a couple of things you have to do differently to configure private key auth.

* For account, do not include the region. So if you typically use "foo.us-east-1" as your account identifier, just enter "foo". If you include the region, you will get a timeout. If you include it but leave the Region ID field blank, you will get an invalid JWT error. 
* As the password field is required, enter any value. It will be ignored. (My Snowflake user is only set up for private key auth and does not have a password set. I don't know if that makes a difference in whether the password is ignored.)
* For Region ID, enter the AWS region that was left off from the account (e.g. us-east-1).
* Under additional jdbc connection string options, enter:
`authenticator=snowflake_jwt&private_key_file=<path to key file in p8 format>&private_key_file_pwd=<your passphrase>`

Snowflake requires the private key to be p8 encoded and to be passphrase protected. If you have spaces in your passphrase, you will have to url encode it (using %20) in the jdbc connection string.

**Comment by Gerald-Lim-Bose** [comment]
Upon further experimentation, I managed to get private key auth to work in 0.41.5. I had to switch the Account value from Snowflake's  `<Account Locator>` format to the `<Org name>-<Account name>` format (see https://docs.snowflake.com/en/user-guide/organizations-connect.html).

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/24157
