### ISSUE TITLE
Offer "exotic" chart axis scaling options like logarithmic

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1920]
Presumably as visualization options. We might also consider doing quadratic, exponential, major, minor, pentatonic, and other exotic scales. 

As discussed in #1918

**Comment by camsaul** [comment]
As discussed in #1918

**Comment by tlrobinson** [comment]
Implemented in #3149, will be released in v0.20.0

No major, minor, or pentatonic scales yet, sorry @camsaul.
