### ISSUE TITLE
Dashboard filter to a simple native query

### ISSUE THREAD

**Issue by sleanodlh** [metabase/metabase#19232]
**Describe the bug**
I created a simple native query 
"Select * from where field1 = value". 
I created a filter and supposed to assign to one of the fields but it won't allow me to.

**Logs**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.1+9",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.1+9",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.1.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.8-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-11-09",
      "tag": "v0.41.2",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**To Reproduce**
1. Create a table in your database
        CREATE TABLE tmp (
        FiscalYear VARCHAR(4),
        Mon VARCHAR(50),
        Quantity INT (11)
        );

2.  Insert these values
        INSERT INTO tmp VALUES ('2021','January',100);
        INSERT INTO tmp VALUES ('2021','January',150);
        INSERT INTO tmp VALUES ('2021','February',200);
        INSERT INTO tmp VALUES ('2021','March',150);
        INSERT INTO tmp VALUES ('2020','January',300);
        INSERT INTO tmp VALUES ('2020','February',200);
        INSERT INTO tmp VALUES ('2020','March',100);
        INSERT INTO tmp VALUES ('2020','March',300);

3.  in Metabase, create and save a native query "nativequery"
        select 
        *
        from tmp
        where mon ='January'

4.  create a dashboard
4.1 Add the question
4.2 Add a filter "Fiscal Year"
4.3 Assign it to the question (it won't let you)

**Expected behavior**
As this is is only a simple and not a complex query, it fields should be available to be filtered

**Screenshots**
![image](https://user-images.githubusercontent.com/95237076/144922236-f848c352-3b4c-4eef-8cca-b6c67827d898.png)

**Severity**
If this is solved, a lot of view re-creation will be eliminated on my side. I am currently creating a table/view for a particular user because the top management doesn't want a particular user to see others' data.

**Comment by flamber** [comment]
Hi @sleanodlh 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And read this:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html
https://www.metabase.com/learn/sql-questions/field-filters.html
https://www.metabase.com/learn/sql-questions/sql-variables.html

**Comment by sleanodlh** [comment]
I don't need to set up a parameter at query creation. the filters should be available on the dashboard and will affect the query. 
Just like the questions created from views or tables - they don't have filters at design time but will only be filtered based on the filters in the dashboard.

If I put a filter to my native query at creation time, it will give so many limitations to my data.
example:
select count(*) from table1 

Filters at dashboard will provide me a lot of flexibility esp for filters like Branch, Department, Division, etc

But if I had to do it as suggested, I will created different native queries:
1. count by Branch = Select count(*) from table1 where Branch = {{Branch}}
2. Count by Dept = Select count(*) from table1 where Department = {{Department}}
3. Count by Division = Select count(*) from table1 where Division = {{Division}}

Not much flexibility

**Comment by flamber** [comment]
@sleanodlh That's what the GUI questions are for. It comes with automagic out of the box for filtering.
