### ISSUE TITLE
Clickhouse timezone query is not effective

### ISSUE THREAD

**Issue by fangpeng-lingoace** [metabase/metabase#19263]
metabase version:  0.41.2

![image](https://user-images.githubusercontent.com/93248843/145181092-9b228276-eefe-4486-987e-b525678ad316.png)

metabase REPORT TIMEZONE set `Asia/Shanghai`

![image](https://user-images.githubusercontent.com/93248843/145181544-6ef034d3-a956-41cc-b704-3d766532cab9.png)

using clickhouse CLI query is normal

![image](https://user-images.githubusercontent.com/93248843/145181190-d7c42a1b-a509-42ad-8231-297e3fef3eb4.png)

**Comment by flamber** [comment]
Hi @fangpeng-lingoace 
You'll have to report that to the driver repo. As noted, not all databases support that timezone setting.
