### ISSUE TITLE
When updating to version 0.41.2, the setup wizard appears upon accessing the app

### ISSUE THREAD

**Issue by nick-holaemi** [metabase/metabase#19296]
We updated from 0.38.5 to 0.41.2 running on Elastic Beanstalk and using a Postgres RDS instance for metabase db. However, when the deployment completed and we accessed the app the setup wizard appears. We already had the app running with questions and dashboards so the setup wizard should not be appearing. This did not happen when we upgraded to other versions in the past.

Is there any setup of config that should be additionally added to sort this out?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Make sure you have decoupled RDS and use the environment variable to define the application database.
https://www.metabase.com/docs/latest/operations-guide/creating-RDS-database-on-AWS.html#decouple-your-rds-database-from-the-elastic-beanstalk-deployment
