### ISSUE TITLE
limit/sort widget should stay open until you pick the direction of your sort

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1932]
current behavior is that you click the ellipsis to open the widget, then click the plus button to add a sort field (which defaults to ascending), and the widget automatically closes.  this is a bit frustrating from my observations because most of the time i'm looking to add descending sorts and so i have to open the widget again to do that.

**Comment by mazameli** [comment]
Technically, you actually can change it on the initial pass by clicking the word "ascending" that appears behind/next to the dropdown after you click the button to add a sort. But I agree it's wonky. I think a simple fix would be to make it a two-step selection, like how we do the aggregation selection now.

**Comment by camsaul** [comment]
Looks like this is already fixed, the `...` doesn't automatically close anymore when you add a sort field
