### ISSUE TITLE
Provide a tabbed experience for large dashboards

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#19347]
**Is your feature request related to a problem? Please describe.**
A customer reported that the dashboards that they use are starting to get a bit large and they want to divide those in several "sub dashboards" that can be accessed from the same page, but on tabs. When you click on a tab, you get the same filter selection that you already have, but cards change and get filtered.

**Describe the solution you'd like**
Have tabs on dashboards that keep the filters a user selected but change the cards that are shown.

**Describe alternatives you've considered**
An alternative I offered was using markdown to send the user to other dashboards, but keeping the filter selection is a bit cumbersome

**How important is this feature to you?**
Feature requested by a user with laaaaarge dashboards

**Additional context**
N/A

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Very related to #10873, #7266 and also #12482, #10237

**Comment by ni-ka** [comment]
I second this request - currently as a workaround we use different dashboards but this means that filter selections are not kept across different dashboards, which in our case is a bit of a bummer.

**Comment by Jorg3GF** [comment]
Hello, 

What is the status of this request of having dashboards with multiple tabs? This is key for us too. 
Or you have it already implemented for the enterprise plan? 
The alternative you have suggested of having different dashboards and combine them programatically on our end is not ideal.

**Comment by javieradorno** [comment]
Any news on this request? It's super usefull

**Comment by paoliniluis** [comment]
Coming in 47

**Comment by steven1u** [comment]
@paoliniluis you meant in Week 47 i.e. mid November 2023?

**Comment by paoliniluis** [comment]
No, in our next version, should be shipped soon

**Comment by durgaswaroop** [comment]
Is this feature being released?

**Comment by paoliniluis** [comment]
Was released in v47

**Comment by MarcSamD** [comment]
Discovering this nice feature in v47 and having a lot of dashboards with "duplicated" filters, is there a convenient way to transfer an existing dahboard to another dashboard as a tab, keeping all the filters parameters and graph layout, without having to recreate everything from scratch ? (something like the "Move or Copy..." feature for Excel sheet :)

@paoliniluis  I guess that many customers will also have this request in order ot merge historical small and splitted dashboards to one main dashboard with tabs.

**Comment by paoliniluis** [comment]
That’s another feature that we opened a few days ago
