### ISSUE TITLE
Disable "Nested queries" not honored in GUI data selector search or on SQL questions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19341]
**Describe the bug**
When "Nested queries" is disabled in Admin > Settings > General, then Saved Questions are still listed in the data selector search, and SQL questions has the "Explore results" button.
Regression when data selector search and "Explore results" was introduced, which didn't account for this setting.

**To Reproduce**
1. Admin > Settings > General > disable "Nested queries"
2. Ask a question > Simple/Custom question > type a name of an existing question, it should not list any saved questions:
![image](https://user-images.githubusercontent.com/1447303/145791463-658f704c-b2f0-4b4c-94ce-b8375a476cff.png)
3. Go to a SQL question - shows "Explore results":
![image](https://user-images.githubusercontent.com/1447303/145791364-1025a02e-ea9e-4d94-b262-27f2458c4fe4.png)

**Information about your Metabase Installation:**
Tested 0.41.4

**Comment by dpsutton** [comment]
#19380 is the backend support to throw an error when the nested queries setting is set to false (default value is true).

**Comment by kulyk** [comment]
Added FE fix in #19356
