### ISSUE TITLE
Cannot see logs after upgrade to v0.41.4

### ISSUE THREAD

**Issue by plengSPK** [metabase/metabase#19340]
I upgrade a Metabase from v0.41.2 to v0.41.4 and when I go to `/admin/troubleshooting/logs` to see a log it always loading and when checking the network in dev tools it loops call this API `/api/util/logs` with an empty response. did I need to config something?

![image](https://user-images.githubusercontent.com/5499915/145762153-e68dffe8-8036-4ab8-85a3-3134b0d90cd8.png)

**Comment by flamber** [comment]
Hi @plengSPK 
1. Post "Diagnostic Info" from Admin > Troubleshooting.
2. Post how you're hosting Metabase
3. Post the name of any environment variables you're using

**Comment by plengSPK** [comment]
I run Metabase as a service using .jar file in local Debian server

#### Diagnostic Info
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_201-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_201",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.201-b09",
    "os.name": "Linux",
    "os.version": "4.19.0-13-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.3.22-MariaDB-0+deb10u1-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.41.4",
      "date": "2021-12-10",
      "branch": "release-x.41.4",
      "hash": "471cfb9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

#### environment variables
MAX_SESSION_AGE=480
MB_SESSION_COOKIES=true
MB_ENCRYPTION_SECRET_KEY=
MB_DB_TYPE=mysql
MB_DB_DBNAME=
MB_DB_PORT=
MB_DB_USER=
MB_DB_PASS=
MB_DB_HOST=

**Comment by flamber** [comment]
@plengSPK Upgrade to Java 11: https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Comment by plengSPK** [comment]
@flamber I'll try, thank you
