### ISSUE TITLE
Excel export does not respect number format

### ISSUE THREAD

**Issue by maurociancio** [metabase/metabase#19359]
I upgraded from v0.40.4 to v0.41.4 and when I export a question to excel, I get "10,000" for numbers, when I previously got "10000"

1. Create a simple "select 10000" sql query
2. Export the query as excel. It gets "10,000"
3. Review admin config. I have no separators for thousands.

**Expected behavior**
An excel file with "10000" an not "10,000".

**Information about your Metabase Installation:**
Metabase version: v0.41.4

**Comment by flamber** [comment]
Duplicate of #19006
