### ISSUE TITLE
blank page on direct link of dashboards with filters after upgrade to Metabase 0.41.4

### ISSUE THREAD

**Issue by lakej31** [metabase/metabase#19374]
**Describe the bug**
When we try to reach a dynamic dashboard with filters through a direct link es(https://report.xxx.com/dashboard/29?data_compilazione=2021-12-01~2021-12-31&edizione_tour=Nessuno&lead_source=Report%20SAS%20o%20SRL%20(Ebook)&utm_source=Facebook%20Ads&utm_source=FacebookAds&utm_source=FacebookAdv&utm_source=Facebook_Ads&utm_source=Facebook_Awareness_nov2019&utm_source=Facebook&utm_source=Facebook_Lead&utm_source=Facebook_Messenger1_nov2019)
we get back a blank page, while the same query made through metabase with the same filters is shown correctly in the dashboard, this is occur on every dashboard with filters if we use a direct link copy/paste to browser instead of run the dashboard directly on metabase 

**Logs**
javascript console log:
react-dom.production.min.js:209 TypeError: (e || "").split is not a function
    at mU (DateRangeWidget.jsx:10)
    at Function.format (DateRangeWidget.jsx:30)
    at i.value (ParameterValueWidget.jsx:224)
    at Wa (react-dom.production.min.js:182)
    at Ba (react-dom.production.min.js:181)
    at xs (react-dom.production.min.js:263)
    at vu (react-dom.production.min.js:246)
    at gu (react-dom.production.min.js:246)
    at uu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
os @ react-dom.production.min.js:209
o.componentDidCatch.n.callback @ react-dom.production.min.js:227
yo @ react-dom.production.min.js:131
ls @ react-dom.production.min.js:212
wu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Mu @ react-dom.production.min.js:248
uu @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
ru @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
b.setState @ react.production.min.js:12
u.onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:62
u.onStateChange @ connectAdvanced.js:204
f @ createStore.js:172
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
(anonymous) @ redux.js:204
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
v @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
Promise.then (async)
v @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ redux.js:200
(anonymous) @ store.js:23
(anonymous) @ bindActionCreators.js:3
(anonymous) @ Dashboard.jsx:143
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
C4 @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
i @ app-main.bundle.js?f805570ebb96c141a0d8:2
n.value @ app-main.bundle.js?f805570ebb96c141a0d8:2
value @ Dashboard.jsx:94
ls @ react-dom.production.min.js:212
wu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Mu @ react-dom.production.min.js:248
uu @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
ru @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
b.setState @ react.production.min.js:12
(anonymous) @ Router.js:109
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
(anonymous) @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
(anonymous) @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
v @ AsyncUtils.js:78
k @ getComponents.js:29
l @ createTransitionManager.js:77
c @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
(anonymous) @ TransitionUtils.js:110
(anonymous) @ routes.jsx:166
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
zIt @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
Promise.then (async)
zIt @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ routes.jsx:163
o @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
c @ AsyncUtils.js:34
y @ AsyncUtils.js:51
r @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
r @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
c @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
c @ AsyncUtils.js:41
y @ AsyncUtils.js:51
j @ matchRoutes.js:231
u @ createTransitionManager.js:41
r @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
Lo @ react-dom.production.min.js:137
Ba @ react-dom.production.min.js:176
xs @ react-dom.production.min.js:263
vu @ react-dom.production.min.js:246
gu @ react-dom.production.min.js:246
uu @ react-dom.production.min.js:239
ru @ react-dom.production.min.js:230
Uu @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
lu @ react-dom.production.min.js:240
Zu @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
CN @ app.js:76
(anonymous) @ app.js:118
Show 91 more frames
Dashboard.jsx:154 TypeError: (e || "").split is not a function
    at mU (DateRangeWidget.jsx:10)
    at Function.format (DateRangeWidget.jsx:30)
    at i.value (ParameterValueWidget.jsx:224)
    at Wa (react-dom.production.min.js:182)
    at Ba (react-dom.production.min.js:181)
    at xs (react-dom.production.min.js:263)
    at vu (react-dom.production.min.js:246)
    at gu (react-dom.production.min.js:246)
    at uu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
(anonymous) @ Dashboard.jsx:154
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
C4 @ app-main.bundle.js?f805570ebb96c141a0d8:2
u @ app-main.bundle.js?f805570ebb96c141a0d8:2
Promise.then (async)
C4 @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
i @ app-main.bundle.js?f805570ebb96c141a0d8:2
n.value @ app-main.bundle.js?f805570ebb96c141a0d8:2
value @ Dashboard.jsx:94
ls @ react-dom.production.min.js:212
wu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Mu @ react-dom.production.min.js:248
uu @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
ru @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
b.setState @ react.production.min.js:12
(anonymous) @ Router.js:109
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
(anonymous) @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
(anonymous) @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
v @ AsyncUtils.js:78
k @ getComponents.js:29
l @ createTransitionManager.js:77
c @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
(anonymous) @ TransitionUtils.js:110
(anonymous) @ routes.jsx:166
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
zIt @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
Promise.then (async)
zIt @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ routes.jsx:163
o @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
c @ AsyncUtils.js:34
y @ AsyncUtils.js:51
r @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
r @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
c @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
c @ AsyncUtils.js:41
y @ AsyncUtils.js:51
j @ matchRoutes.js:231
u @ createTransitionManager.js:41
r @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
Lo @ react-dom.production.min.js:137
Ba @ react-dom.production.min.js:176
xs @ react-dom.production.min.js:263
vu @ react-dom.production.min.js:246
gu @ react-dom.production.min.js:246
uu @ react-dom.production.min.js:239
ru @ react-dom.production.min.js:230
Uu @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
lu @ react-dom.production.min.js:240
Zu @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
CN @ app.js:76
(anonymous) @ app.js:118
Show 54 more frames
9XHR finished loading: GET "<URL>".
VM204:1 XHR finished loading: POST "https://www.google-analytics.com/j/collect?v=1&_v=j96&a=1425836257&t=pageview&_s=1&dl=https%3A%2F%2Freports.xxx.com%2Fdashboard%2F29%3Fdata_compilazione%3D2021-12-01~2021-12-31%26edizione_tour%3DNessuno%26lead_source%3DReport%2520SAS%2520o%2520SRL%2520(Ebook)%26utm_source%3DFacebook%2520Ads%26utm_source%3DFacebookAds%26utm_source%3DFacebookAdv%26utm_source%3DFacebook_Ads%26utm_source%3DFacebook_Awareness_nov2019%26utm_source%3DFacebook%26utm_source%3DFacebook_Lead%26utm_source%3DFacebook_Messenger1_nov2019&dp=%2Fdashboard%2F29&ul=it-it&de=UTF-8&dt=Metabase&sd=24-bit&sr=1536x864&vp=1536x160&je=0&_u=SACAAEABAAAAAC~&jid=1417398228&gjid=1088892032&cid=1850028559.1624631226&tid=UA-60817802-1&_gid=1213352443.1639479361&_r=1&_slc=1&cd1=v0.41.4&z=100046559".
(anonymous) @ VM204:1
wd @ analytics.js:44
pe @ analytics.js:43
Sa @ analytics.js:48
Ha.D @ analytics.js:46
pc.send @ analytics.js:81
X.b.<computed> @ analytics.js:61
Z.v @ analytics.js:98
Z.D @ analytics.js:97
N @ analytics.js:98
d @ analytics.js:44
l @ analytics.js:13
(anonymous) @ routes.jsx:165
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
zIt @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
Promise.then (async)
zIt @ app-main.bundle.js?f805570ebb96c141a0d8:2
a @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ app-main.bundle.js?f805570ebb96c141a0d8:2
(anonymous) @ routes.jsx:163
o @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
c @ AsyncUtils.js:34
y @ AsyncUtils.js:51
r @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
r @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
c @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
c @ AsyncUtils.js:41
y @ AsyncUtils.js:51
j @ matchRoutes.js:231
u @ createTransitionManager.js:41
r @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
Lo @ react-dom.production.min.js:137
Ba @ react-dom.production.min.js:176
xs @ react-dom.production.min.js:263
vu @ react-dom.production.min.js:246
gu @ react-dom.production.min.js:246
uu @ react-dom.production.min.js:239
ru @ react-dom.production.min.js:230
Uu @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
lu @ react-dom.production.min.js:240
Zu @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
CN @ app.js:76
(anonymous) @ app.js:118
Show 26 more frames
20XHR failed loading: POST "<URL>".

**To Reproduce**
no error shown, only a blank page

**Expected behavior**
Display the dashboard with the results of the query with filters (that works before the upgrade! and if we make the query directly from metabase with select of the same filters)

**Screenshots**
![Immagine 2021-12-15 144023](https://user-images.githubusercontent.com/96186731/146197033-adc76040-44da-41cc-ba6d-5312423604e7.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 96.0.4664.93 & Firefox 95.0
- Your operating system: Windows 11
- Your databases: MySql
- Metabase version: 0.41.4
- Metabase hosting environment: Ubuntu 18.04.4 LTS
- Metabase internal database: H2 (default)
- 
**Severity**
HIGHER: blocking some users in everyday works

**Comment by flamber** [comment]
Hi @lakej31 
1. Which version did you upgrade from?
2. Post "Diagnostic Info" from Admin > Troubleshooting.
3. It looks like it's failing on a date range filter, but I cannot reproduce. Can you either try to reproduce on a new dashboard with just a single question and add one filter at the time?

**Comment by lakej31** [comment]
1. i've upgraded from 0,38.x to the latest 0.41.4
2. {
  "browser-info": {
    "language": "it-IT",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9-Ubuntu-0ubuntu2.18.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9-Ubuntu-0ubuntu2.18.04",
    "os.name": "Linux",
    "os.version": "4.15.0-163-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-10",
      "tag": "v0.41.4",
      "branch": "release-x.41.4",
      "hash": "471cfb9"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

3. i solve, the blank page problem, but now the issue i think is that without datarange parameters it work fine, but if i set in the url a data range, it will report every time to the standard data range set and not take the datarange parameters passed through url

**Comment by flamber** [comment]
@lakej31 
How did you solve the blank page problem?
Can you please try to reproduce with a completely new dashboard and the Sample Dataset, and then provide steps to reproduce?
I have tried multiple combinations, but I have not been able to reproduce.
Is the field connected to the filter a Unix Timestamp or is it a real `datetime` column in MySQL?
