### ISSUE TITLE
Matabase won't full start in docker on M1 mac

### ISSUE THREAD

**Issue by kristiankostecky** [metabase/metabase#19388]
**Describe the bug**
Metabase won't fully start in docker on M1(apple silicon) mac. It will only display two logs displayed below and hangs there forever. I won't crash, it won't do anything from there.

**Logs**
```
Warning: environ value jdk-11.0.11+9 for key :java-version has been overwritten with 11.0.11

2021-12-16 08:24:20,573 INFO metabase.util :: Maximum memory available to JVM: 1.2 GB
```

**To Reproduce**
`docker run -d --platform linux/amd64 -p 3000:3000 --name metabase metabase/metabase`

**Expected behavior**
Metabase should start and can be accessed on `http://localhost:3000`

**Information about your Metabase Installation:**
- Your operating system: MacOs Big Sur 11.3
- Metabase version: [latest](https://hub.docker.com/layers/metabase/metabase/latest/images/sha256-c5bab50e3b0d2c521a53d05e5d21ed2236dabc2edfa5c2d576c8fa3d2f2addb6?context=explore)
- Metabase hosting environment: Docker version 20.10.7

**Comment by flamber** [comment]
Hi @kristiankostecky 
How long did you let it run? Try leaving it for 20 minutes. My first guess is that you're running out of entropy for some reason.
Try the [JAR](https://www.metabase.com/start/oss/jar.html) instead with a Java environment that supports M1 like Azul: https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jre (scroll to bottom)

**Comment by kristiankostecky** [comment]
Hi @flamber, thanks for quick reply!
It was running for about 2h and still nothing. I've tried it multiple times also on a different machine (with M1) but always the same result. 

The solution with [JAR](https://www.metabase.com/start/oss/jar.html) **is working**! Which is great.

But it would be nice to have it also run in docker. We use it in project inside a docker and have script that set and start everything as needed. This way I would need to modify the script not to run docker and run it from JAR but only for my personal use since not everyone uses the same machine. But still thank you for the solution at least I can run it somehow 🙏.

**Comment by flamber** [comment]
Okay, I'm closing this in favor of #13119
