### ISSUE TITLE
X-ray card links & drill-throughs are broken

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#19405]
**Describe the bug**
If you're viewing an (unsaved) X-ray, and you click on the title of any card, it takes you to the "Ask a question" page with the simple question/custom question/native query prompts, rather than taking you to the specific question that you clicked on.

And if you try to do a drill-through or breakout on any card on the X-ray, it'll take you to a 404 page.

https://user-images.githubusercontent.com/32746338/146579615-1e2108b1-b408-4edc-8bf2-52fe5b209ee7.mov

**To Reproduce**
1. Go to Browse data -> Sample Dataset
2. Click on "X-ray this table" for any table
3. Click on the title of any card in the X-ray, or click on any piece of data in a chart and select any of the options

**Expected behavior**
Links should take you directly to the question you clicked on

**Information about your Metabase Installation:**
Current master (& can repro on stats)

**Comment by flamber** [comment]
Regression on master. Works on 0.41.5.
Wonder if it might be caused by some of the drill-through/filter changes @daltojohnso made recently? Perhaps X-rays are using old-style?

**Comment by daltojohnso** [comment]
Yep, caused by https://github.com/metabase/metabase/pull/19027. X-ray dashcards are a special case that needs to be handled differently.
