### ISSUE TITLE
Metabase whitelist URL to RDS

### ISSUE THREAD

**Issue by vipulJain05** [metabase/metabase#19400]
We are using Metabase's helm chart to install on EKS and want to connect with RDS which is running on a different network.
Can anyone please help which IP I have to use to whitelist the Metabase to RDS using the Metabase admin section

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It would be impossible for anyone to tell which IPs you're using. It depends on if you're NAT'ing outgoing connections.
