### ISSUE TITLE
about card api，How to Use time filter

### ISSUE THREAD

**Issue by feipenghou** [metabase/metabase#19401]
For help with installation and setup, information on how specific features work, or general questions about Metabase, please use our discussion forum:

https://discourse.metabase.com

The Github issue tracker is intended to collect bug reports and feature requests.
Any issues open for help requests will be closed to keep from clogging up the issue tracker.

**Comment by feipenghou** [comment]
about card api，How to Use time filter

**Comment by feipenghou** [comment]
curl -X post \
  -H "Content-Type: application/json" \
  -H "X-Metabase-Session:79922db0-6a75-4f68-8c50-e19f225d434a" \
  http://localhost:3000/api/card/44/query

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
