### ISSUE TITLE
Clicking on the Refresh button on a question page can not replace cache result in db.

### ISSUE THREAD

**Issue by Jakin-Liu** [metabase/metabase#19418]
I request /api/card/:card-id/query
body params : { {
    "ignore_cache": true,
    "parameters": []
} }
it response result is new result.
after that 
I request this card-id data ,it also response old result. so that I think it can not replace old result with new result.
I need very urgent help
![image](https://user-images.githubusercontent.com/65338514/146635360-6ebc14da-3258-4344-afa6-fa2dd5d67a8f.png)

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
