### ISSUE TITLE
Automatically update metabase version numbers in homebrew

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1943]
I saw [this article](http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x) at the top of HN and it made me think

``` bash
brew install metabase
```

would be pretty spiffy

**Comment by kdoh** [comment]
@tlrobinson actually added homebrew cask support a while back. 
<img width="510" alt="screen shot 2016-02-15 at 2 23 46 pm" src="https://cloud.githubusercontent.com/assets/5248953/13061933/d0bbce68-d3ef-11e5-97e8-bd99ed2a8c11.png">

**Comment by camsaul** [comment]
oh, sweet. It looks like it's says the latest version is `0.13.2` tho

**Comment by camsaul** [comment]
```bash
$ brew info metabase
metabase: stable 0.13.2, HEAD
Business intelligence report server
http://www.metabase.com/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/metabase.rb
```

**Comment by tlrobinson** [comment]
Yeah I started on a script to automate it but didn't get around to finishing it.

**Comment by kdoh** [comment]
we should definitely automate this but for now, https://github.com/Homebrew/homebrew/pull/49202

**Comment by camsaul** [comment]
Wel need to bump this to 0.17 

```bash
metabase: stable 0.16.0, HEAD
Business intelligence report server
http://www.metabase.com/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/metabase.rb
``

**Comment by kdoh** [comment]
https://github.com/Homebrew/homebrew-core/pull/938

**Comment by camsaul** [comment]
Since we don't release on Homebrew anymore going to go ahead and close this
