### ISSUE TITLE
Updating log4j to 2.15.0 (v0.37.9)

### ISSUE THREAD

**Issue by emreyavuz369** [metabase/metabase#19432]
I am using v0.37.9. I can not upgrade version because of oracle table long display name https://github.com/metabase/metabase/issues/15978
 
So, i wish that could you upgrade log4j version of v0.37.9

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You would have to do that manually yourself, or remove the JDNI class: https://github.com/metabase/metabase/issues/19371#issuecomment-996169680

**Comment by emreyavuz369** [comment]
Thank you @flamber for [this comment](https://github.com/metabase/metabase/issues/19371#issuecomment-996169680). 
I make dockerfile below.

`FROM metabase/metabase:v0.37.9

RUN apk add zip

RUN zip -q -d /app/metabase.jar org/apache/logging/log4j/core/lookup/JndiLookup.class`

**Comment by flamber** [comment]
@emreyavuz369 Thank you for posting your solution. Just note that it will only remove anything related to JDNI lookups, so any other security updates will not be addressed.
