### ISSUE TITLE
Fix flaky e2e popover tests 

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#19454]
Related to the popovers added in #18738 

The popovers appear on hover, so we must use `trigger("mouseenter")` to make them show up. This is a finicky process and faily frequently. Need to figure out a different way of testing.

**Comment by akiselev** [comment]
Note to self: https://github.com/dmtrKovalenko/cypress-real-events might solve this along with several other e2e issues

**Comment by oleggromov** [comment]
Related to this https://github.com/metabase/metabase/pull/37020 - I might tackle this one too.
