### ISSUE TITLE
Ability to use Null constant in Custom Column/ Custom Expression

### ISSUE THREAD

**Issue by guillaume-chech** [metabase/metabase#19461]
**Is your feature request related to a problem? Please describe.**
It is not possible to use the Null constant in Custom Column/ Custom Expression builder making it hard to work accurately with `Distinct (case(condition,identifier,Null))` or `Sum (case(condition,identifier,Null))` or `Average(case(condition,identifier,Null))` . 

**Describe the solution you'd like**
Make the Null constant usable in Custom Question Builder, it shouldbe possible to use it in join conditions as well

**Describe alternatives you've considered**
An alternative is to return `-1` or `''` but it will not be aggregated correctly but Distinct, Sum or Average

**Screenshot**
<img width="435" alt="Screenshot 2021-12-22 at 16 21 39" src="https://user-images.githubusercontent.com/24913696/147115143-ed4f838e-bfe2-41b9-b9ef-d01e58b6fe88.png">

**How important is this feature to you?**
This is almost critical as it makes data exploration really hacky.

**Comment by flamber** [comment]
Hi @guillaume-chech 
There's `SumIf()` and `CountIf()`: https://www.metabase.com/docs/latest/users-guide/expressions-list.html
`AverageIf` is tracked in #12640
If you don't include anything, then it's automatically `null`

**Comment by guillaume-chech** [comment]
@flamber Indeed, using `Sumif()` or `AverageIf()` Would work however, `Countif()` is not a workaround in case we need to count distinct values that are not the primary key except we have planned a `Distinctif()` for future releases.

**Comment by flamber** [comment]
@guillaume-chech 
Why doesn't this work? `Distinct(case(condition,identifier))`
Please provide the equivalent SQL query that you're trying to do.

**Comment by guillaume-chech** [comment]
@flamber It does work perfectly fine I did not understand what you meant by 
> If you don't include anything, then it's automatically null
For the case statement. I got tricked by the documentation that doesn't specify that the else argument is optional 🙈 
Sorry about that !
