### ISSUE TITLE
Native query "SELECT CONCAT('a', 'b')" results in error 403 "Sorry, you don’t have permission to see that."

### ISSUE THREAD

**Issue by marcalc** [metabase/metabase#19472]
**Describe the bug**
Simply querying "select concat('a','b') on the native query results in error "Sorry, you don’t have permission to see that."

**Logs**
POST request to /api/dataset with payload {type: "native", native: {query: "select concat('a', 'b')", template-tags: {}}, database: 2,…} results in 403 error.

**Browser console error:**

```
react-dom.production.min.js:50 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:50
    at it (react-dom.production.min.js:50)
    at Object.t.findDOMNode (react-dom.production.min.js:289)
    at s.value (ExplicitSize.jsx:31)
    at s.<anonymous> (ExplicitSize.jsx:101)
    at u (throttle.js:16)
```

**Server logs:** there's none relative to this query.

**To Reproduce**
1. Create a native query, input "select concat('a', 'b')"
2. Run the query.

**Expected behavior**
Expected to return a dataset with 1 column with value "ab"

**Screenshots**
Not applicable.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
Chrome  96.0.4664..110
OSX 12.1
MySQL
Metabase 0.41.5
AWS Ubuntu
Internal DB: Postgres

**Severity**
Blocking too many user queries to be useful.

**Additional context**
--

**Comment by flamber** [comment]
Hi @marcalc 
Post "Diagnostic Info" from Admin > Troubleshooting
And the full stacktrace error from Admin > Troubleshooting > Logs.
It is not possible to get a 403 error from the server without there being a log. The browser console error is irrelevant.

**Comment by marcalc** [comment]
Thanks a lot, Flamber. You're absolutely right and Cloudflare's WAF rules were the culprit. Thank you!
