### ISSUE TITLE
Zeros on the graph of the area that do not exist

### ISSUE THREAD

**Issue by sergeymong** [metabase/metabase#19485]
1. I am building a query via SQL (ClickHouse).
2. Selecting Area Chart in the visualizations.
3. I merge (without normalizing to 100%).
4. I select "Display values on the chart".

Waiting:
In the form of values on the graph there will be combined statistics for each group.

Reality:
In addition to these statistics, I see zeros that are not actually in the data. This is confusing to chart users:(

**Screenshots**
![Data](https://user-images.githubusercontent.com/6741089/147442852-109caf23-5153-4bf8-bc41-094171b8ad9c.png)
![Graph](https://user-images.githubusercontent.com/6741089/147442959-8c3b18ad-a236-44e5-8cd8-f04379f22d17.png)

**Information about your Metabase Installation:**
v0.41.3.1
Built 2021-12-02
Branch: release-x.41.x
Hash: 20f9097

You can get this information by going to Admin -> Troubleshooting.

- Browser: Google Chrome, Version 96.0.4664.110 (Official Build) (x86_64)
- Your operating system: MacOS 12.0.1
- Your databases: ClickHouse 21.11.4.14
- Metabase version: (e.x. 0.19.3)

**Comment by flamber** [comment]
You should upgrade to latest release: https://github.com/metabase/metabase/releases/latest

Very related to #17205

Reproduce:
1. Custom question > Sample Dataset > Products - summarize Count by Category and CreatedAt:Month
2. Change to Area chart
3. Set Display > Stacking="Stack" and enable Display > Show values on data points
![image](https://user-images.githubusercontent.com/1447303/147458120-a1e6e5a1-4516-4614-80d5-59fe36f684ca.png)
