### ISSUE TITLE
XLSX exports are leaving temporary files, which can block instance from working

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19480]
**Describe the bug**
XLSX exports that are cancelled (closing browser, or click export again before first request finished) leaves temporary files in `/tmp/poifiles/poi-sxssf-sheet***.xml` until the Metabase process is shut down.

It can not only bring down Metabase, but potentially the entire server, depending on how Metabase is deployed.

P1 contender.

**To Reproduce**
1. Native query > any Postgres database
```
WITH
   L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)) -- 2^1
  ,L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B)       -- 2^2
  ,L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B)       -- 2^4
  ,L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B)       -- 2^8
  ,L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B)       -- 2^16
  ,L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L2 AS B)       -- 2^32

select ROW_NUMBER() OVER (ORDER BY c), case when RIGHT(ROW_NUMBER() OVER (ORDER BY c)::text, 5)='00000' then pg_sleep(5) else null end from L5
```
2. Run this query, which will show 2000 rows and allows export
3. Click Export > XLSX - wait ~10 seconds and close the browser window before it actually starts downloading (you can repeat this a few times)
4. Go to `/tmp/poifiles/` - there should now be XML files
5. Close the Metabase process, now the files are removed

**Expected behavior**
When the request with the browser is closed, then there's a EofException (expected), but the temporary file should also be deleted.
Just like if you let the above query actually start the download, then the XML files are removed.

**Information about your Metabase Installation:**
Tested 0.40.5 and 0.41.5

**Additional context**
This is very likely what caused #13159

**Comment by noahmoss** [comment]
note: for the repro, POI temp files will actually be created at the location of the `java.io.tmpdir` system property, which may not be `/tmp/`
