### ISSUE TITLE
Dashboard filter with default value sends the wrong parameters to all cards of the same questions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19494]
**Describe the bug**
When you have multiple of the same question on a dashboard (e.g to do period comparison), then filter connected to just one of the cards will apply to all the cards of that question. This only happens when the filters have "Default value".

P1 contender. Regression on master.

**To Reproduce**
1. Add a question two times to a dashboard (e.g Products table here)
2. Create two filters, connect filter1 to card1, and filter2 to card2 (e.g Category)
3. The trigger: Set a "Default value" for both filters, but different for each filter (e.g. filter1 "Doohickey" and filter2 "Gadget")
![image](https://user-images.githubusercontent.com/1447303/147593375-c7fbc771-4238-43e4-bde8-eebd51d6eb11.png)
4. Save dashboard - no results will be displayed.
![image](https://user-images.githubusercontent.com/1447303/147592840-f0e211e4-dae9-4189-87a3-626664ca0bb9.png)
5. Even when removing widget values will not give any results
![image](https://user-images.githubusercontent.com/1447303/147592901-0f1e8fd4-5b76-438d-aab6-25a2fc395654.png)
6. Removing filter2 and saving the dashboard (still having filter1 just connected to card1, and with a default value) will clearly show that it's sending the same parameters to card2 even though it's not connected to filter1:
![image](https://user-images.githubusercontent.com/1447303/147593102-b4825265-ea6e-4e65-800c-e237c9cec43d.png)

**Information about your Metabase Installation:**
Tested `33ea417` from Dec. 27th

Noticed by @ukritw

**Comment by camsaul** [comment]
I'm not 100% sure whether this is backend or frontend (would need to look at the actual API requests to confirm one way or the other) but I will investigate and then update

**Comment by daltojohnso** [comment]
Repro'd and looking at queries the FE is sending, they look correct to me. For example, this is a for a card that is the Products table, added to a dashboard twice with different Category filters and getting no rows back:

<img width="1023" alt="Screen Shot 2022-01-04 at 10 36 56 AM" src="https://user-images.githubusercontent.com/13057258/148107420-cfc8fdb2-b4b1-48bb-9cc4-58b7617869d5.png">

**Comment by camsaul** [comment]
Ok the problem here is that the API endpoint is `POST /api/:dashboard-id/card/:card-id/query` so we actually have know way to distinguish between having the same Card on the Dashboard twice.

We need to change the endpoint to include `:dashcard-id` somewhere on both backend and frontend

**Comment by camsaul** [comment]
Backend changes are in #20139. Fronted will have to be updated to use the new endpoints
