### ISSUE TITLE
Field names shouldn't be allowed to be empty string

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#1949]
In the admin panel, you can currently rename a field's name to contain nothing, and it saves just fine. This shouldn't be allowed. If a user clears out the input field and then clicks out of the field, instead of saving the field name as an empty string, it should revert the name back to what it was.

![screen shot 2016-02-16 at 12 09 41 pm](https://cloud.githubusercontent.com/assets/2223916/13089657/869a613e-d4a6-11e5-9907-3837f7df9fdb.png)

**Comment by agilliland** [comment]
@mazameli I just took a look at this and the application is actually preventing this from happening, I think it's just not clear that's the case in the UI.  when i try this with either a table or field there is an error shown at the top of the page and the value is never actually saved, however the the UI still shows an empty text area :cry: 

Let me know how you think this should be handled

**Comment by mazameli** [comment]
Ah, well that's good news. Can we do what I suggested in the comment above? If you clear out the field and then click out of it, instead of spitting an error message, we can revert to what the field was named before.

**Comment by agilliland** [comment]
yep.  that makes sense :+1:   that's what i'll do.
