### ISSUE TITLE
Pivot Table Preview Can not display full Column Name?

### ISSUE THREAD

**Issue by SAMZONG** [metabase/metabase#19497]
**Describe the bug**

- Visualization use  Pivot Table 
- column name is dateime format , like `2021-12-02 23:00:00`   `2021-12-02 23:10:00`   etc.

I use Pivot table style to priview like a week every hour  count(id) 

but ,  it pivot table can not display full column name...

<img width="1204" alt="W12291602" src="https://user-images.githubusercontent.com/13782141/147641569-570894da-41dc-4361-a5f9-6065f8f34a79.png">

**Comment by flamber** [comment]
Duplicate of #14350
