### ISSUE TITLE
Error shown for certain column types when getting results from cache

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19501]
**Describe the bug**
When returning an `interval` column type via cached results, then an error is shown in the frontend instead of the results.

I'm unsure if this is specific to Redshift or generally for unknown column types. I've not been able to reproduce on Postgres, though a similar, but different issue exists for Postgres #11995
Since `interval` is not fully supported (#2656), then that could be it, but then the error should also exist on Postgres ...?

**To Reproduce**
1. Admin > Settings > Caching: Duration=`0.0001` and TTL=`10000`
2. Native query > **Redshift** > `select interval '1 day'` - run query - see results - save question
3. Do browser refresh a couple of time, so it starts returning cached results (or is supposed to)
The returned "result" is:
`{"nippy/unthawable":{"type":"serializable","cause":"quarantined","class-name":"com.amazon.redshift.util.RedshiftInterval","content":"0xACED0005"}}`
And the log only contains the following related to this, no stacktraces or anything real errors:
`WARN metabase.driver.common Don't know how to map class 'class com.amazon.redshift.util.RedshiftInterval' to a Field base_type, falling back to :type/*.`
![image](https://user-images.githubusercontent.com/1447303/147705140-d518edcf-1bd4-4ea2-bce1-84f0ba7c577f.png)

**Expected behavior**
1. Correct results from cache, of course
2. An error or stracktrace in the log.

**Information about your Metabase Installation:**
Tested 1.41.5 and master `b9bee5d`

**Comment by camsaul** [comment]
This sounds like the same MongoDB issue we fixed in #25915, adding to prioritized backlog since this should be a simple/easy fix
