### ISSUE TITLE
Add custom SSL certificate support for Presto without access to the filesystem

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#19514]
**Is your feature request related to a problem? Please describe.**
In the same way we will be adding SSL support for MongoDB in the next phase of secret management, we need Presto support

**Describe the solution you'd like**
A way of using custom SSL certificates in Presto connections if you're not able to access the instance

**Describe alternatives you've considered**
None (or disabling SSL)

**How important is this feature to you?**
Important for Cloud customers

**Additional context**
Requested by a customer

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/23821
