### ISSUE TITLE
How about to realization row permissions for free version

### ISSUE THREAD

**Issue by wanjiawen** [metabase/metabase#19510]
can I add row permissions for free version

for example
On this page, different users filter different data according to row permissions 。

![image](https://user-images.githubusercontent.com/6101523/147934448-8e72662a-cf30-4e58-8c80-84b73af201ad.png)

**Comment by flamber** [comment]
Only the Enterprise and Pro editions has Sandboxing (row level access): https://www.metabase.com/learn/permissions/data-sandboxing-row-permissions.html

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
