### ISSUE TITLE
Value in bar chart does not agree with value in table

### ISSUE THREAD

**Issue by benjaminwy** [metabase/metabase#19522]
I'm running into an issue where the table view of my data displays the correct values, but the bar, line, area, and other visualization types display an unexpected value. The screenshots below should explain the issue more succinctly than I could in words.

Initially I ran across this behavior while following [this guide](https://www.metabase.com/learn/analytics/time-series-comparisons) for creating a time series comparison, but I found that I could reproduce it with a simpler contrived query:

```sql
select 'January' as month, 100 as revenue_2020, 200 as revenue_2021, 15 as revenue_2022
union all
select 'February' as month, 150 as revenue_2020, 300 as revenue_2021, 0 as revenue_2022
union all
select 'March' as month, 200 as revenue_2020, 400 as revenue_2021, 0 as revenue_2022
union all
select 'April' as month, 250 as revenue_2020, 500 as revenue_2021, 0 as revenue_2022
```

Table view, data looks correct:

<img width="1155" alt="table" src="https://user-images.githubusercontent.com/2089521/147990600-86fba3d4-1aed-4008-af8a-84e6eb282758.png">

Bar chart -- 2022 revenue column isn't right:

<img width="1919" alt="bar chart" src="https://user-images.githubusercontent.com/2089521/147990621-e8d880d2-1121-4f61-853e-159e6251c9c2.png">

And here's the tooltip, which shows the correct amounts:

<img width="656" alt="tooltip" src="https://user-images.githubusercontent.com/2089521/147990643-661d41e2-fd5a-463d-881d-05af994070df.png">

Any idea what's going on here? Is this a bug, or am I making a mistake?

**Information about your Metabase Installation:**

- Your browser and the version: Firefox 95.0.2
- Your operating system: OSX 10.15.7
- Your databases: MySQL
- Metabase version: 0.41.5
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Comment by flamber** [comment]
Hi @benjaminwy 
Disable "Use a split y-axis when necessary" under the Axes-tab in the visualization settings

**Comment by benjaminwy** [comment]
Thank you, @flamber! That solves it
