### ISSUE TITLE
Previews and sent data are not the same

### ISSUE THREAD

**Issue by 666dsa666** [metabase/metabase#19535]
**Describe the bug**
Upgraded to 0.41.4 then 0.41.5 from 0.38.4 if I remember correctly the old version.
Pulse were configured and showed no errors, data were sent but were garbage : missing columns and duplicates
Preview show the right info

I recreated each questions with the exact same data and the problem is in the opposite way : preview is garbage and date received are right.

**Logs**
_None_

**To Reproduce**
1. Check question : preview is correct
2. Send and received pulse
3. Data are garbage
4. Recreate said question
5. Check preview : garbage
5. Update pulse
5. Send and received said pulse
6. Date are ok

In edit mode the previews are ok, in view mode they are not.

**Expected behavior**
Upgrade should probably not break existing questions ? Preview should reflect the data that are sent ?

**Screenshots**
Preview of new question - preview is incorrect: 
![image](https://user-images.githubusercontent.com/11072018/148115329-ab13f228-2af7-47ef-997b-a9d938165cb3.png)
Edit mode where preview is ok: 
![image](https://user-images.githubusercontent.com/11072018/148115476-fd8ca813-ac62-4d9c-b515-d2820f83c0dd.png)
Received data are ok : 
![image](https://user-images.githubusercontent.com/11072018/148115609-a2f0712c-b57d-4ad9-b21c-fffce5596bfb.png)

Preview of old question - preview is correct
![image](https://user-images.githubusercontent.com/11072018/148115910-2de821a7-1d88-410a-a292-3ae31ae0b5a1.png)
Edit mode where preview is ok too
![image](https://user-images.githubusercontent.com/11072018/148115984-ba7fdda5-f2ee-46be-a660-9e93ba026f60.png)
Received data are not ok : 
![image](https://user-images.githubusercontent.com/11072018/148116128-f7731670-57ad-4851-99a7-1600557e4f7b.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "fr",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Linux",
    "os.version": "5.11.0-1022-azure",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.3.32-MariaDB-0ubuntu0.20.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-16",
      "tag": "v0.41.5",
      "branch": "release-x.41.x",
      "hash": "fbfffc6"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}

```

**Severity**
Pretty high severity as all questions had to be recreated.

**Additional context**
Update was made when log4j was discovered to 0.41.4, issue was submitted today, upgrade to 0.41.5 was made hoping it could solve the issue.
Pulses were working before upgrade.

All questions were archived but are still available if needed.

Informations in capture were edited as per IT request.

**Comment by flamber** [comment]
Hi @666dsa666 
You will need to provide the metadata of a broken question by going to the URL `/api/card/123`, which 123 is the question ID.
Also, please "upgrade" to Java 11: https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Comment by 666dsa666** [comment]
Here are the metedata of the original question (preview ok, pulse nok) 
`{"description":null,"archived":false,"collection_position":null,"table_id":132,"result_metadata":[{"semantic_type":"type/PK","coercion_strategy":null,"name":"id","field_ref":["field",1587,{"join-alias":"Gl Pi Tickets"}],"effective_type":"type/Integer","id":1587,"display_name":"Gl Pi Tickets → ID","fingerprint":null,"base_type":"type/Integer"},{"semantic_type":"type/Name","coercion_strategy":null,"name":"name","field_ref":["field",1586,{"join-alias":"Gl Pi Tickets"}],"effective_type":"type/Text","id":1586,"display_name":"Gl Pi Tickets → Name","fingerprint":{"global":{"distinct-count":3360,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":2.741228070175439E-4,"percent-state":0.0,"average-length":37.77549342105263}}},"base_type":"type/Text"},{"name":"sum","display_name":"Somme de SecToMin","base_type":"type/Decimal","effective_type":"type/Decimal","field_ref":["aggregation",0],"semantic_type":null,"fingerprint":{"global":{"distinct-count":14,"nil%":0.0},"type":{"type/Number":{"min":5.0,"q1":8.04043009509531,"q3":22.8309518948453,"max":135.0,"sd":19.49604003923346,"avg":19.00862068965517}}}}],"creator":{"email":"hotline@jalix-services.com","first_name":"Hotline","last_login":"2021-06-01T13:29:11","is_qbnewb":false,"is_superuser":true,"id":1,"last_name":"JALIX","date_joined":"2019-11-22T10:57:58","common_name":"Hotline JALIX"},"can_write":true,"database_id":2,"enable_embedding":false,"collection_id":null,"query_type":"query","name":"Temps passé par Jalix sur les demandes","last_query_start":"2022-01-05T15:55:20.428188Z","dashboard_count":0,"average_query_time":160.2500,"creator_id":1,"moderation_reviews":[],"updated_at":"2022-01-05T16:55:20","made_public_by_id":null,"embedding_params":null,"cache_ttl":null,"dataset_query":{"database":2,"type":"query","query":{"source-table":132,"joins":[{"fields":[["field",1587,{"join-alias":"Gl Pi Tickets"}],["field",1586,{"join-alias":"Gl Pi Tickets"}]],"source-table":151,"condition":["=",["field",1348,null],["field",1587,{"join-alias":"Gl Pi Tickets"}]],"alias":"Gl Pi Tickets"}],"filter":["and",["=",["field",1346,null],681,1225,1223,1222,1221,1220],["time-interval",["field",1592,{"join-alias":"Gl Pi Tickets"}],-1,"month"],["=",["field",1560,{"join-alias":"Gl Pi Tickets"}],2]],"expressions":{"SecToMin":["/",["field",1358,null],60]},"aggregation":[["sum",["expression","SecToMin"]]],"breakout":[["field",1587,{"join-alias":"Gl Pi Tickets"}],["field",1586,{"join-alias":"Gl Pi Tickets"}]]}},"id":89,"display":"table","last-edit-info":{"id":1,"email":"hotline@jalix-services.com","first_name":"Hotline","last_name":"JALIX","timestamp":"2022-01-05T16:55:14"},"visualization_settings":{"table.columns":[{"name":"id_2","enabled":true},{"name":"name","enabled":true},{"name":"id","enabled":true},{"name":"SecToMin","enabled":true},{"name":"begin","field_ref":["field",1352,null],"enabled":true},{"name":"content","field_ref":["field",1351,null],"enabled":true},{"name":"date","field_ref":["field",1356,null],"enabled":true},{"name":"date_creation","field_ref":["field",1343,null],"enabled":true},{"name":"date_mod","field_ref":["field",1354,null],"enabled":true},{"name":"end","field_ref":["field",1353,null],"enabled":true},{"name":"groups_id_tech","field_ref":["field",1350,null],"enabled":true},{"name":"is_private","field_ref":["field",1341,null],"enabled":true},{"name":"state","field_ref":["field",1347,null],"enabled":true},{"name":"taskcategories_id","field_ref":["field",1344,null],"enabled":true},{"name":"tasktemplates_id","field_ref":["field",1345,null],"enabled":true},{"name":"tickets_id","field_ref":["field",1348,null],"enabled":true},{"name":"timeline_position","field_ref":["field",1349,null],"enabled":true},{"name":"users_id","field_ref":["field",1346,null],"enabled":true},{"name":"users_id_editor","field_ref":["field",1355,null],"enabled":true},{"name":"users_id_tech","field_ref":["field",1342,null],"enabled":true},{"name":"SecToMin","field_ref":["expression","SecToMin"],"enabled":true},{"name":"id_2","field_ref":["field",1587,{"join-alias":"Gl Pi Tickets"}],"enabled":true},{"name":"SecToMin","field_ref":["expression","SecToMin"],"enabled":true},{"name":"id","field_ref":["field",1587,{"join-alias":"Gl Pi Tickets"}],"enabled":true},{"name":"name","field_ref":["field",1586,{"join-alias":"Gl Pi Tickets"}],"enabled":true}],"table.pivot_column":"id","table.cell_column":"sum","table.pivot":false},"collection":null,"created_at":"2020-12-23T15:09:13","public_uuid":null}`

And from the new question (preview nok, pulse ok) : 
`{"description":null,"archived":false,"collection_position":null,"table_id":132,"result_metadata":[{"semantic_type":"type/PK","coercion_strategy":null,"name":"id","field_ref":["field",1587,{"join-alias":"Gl Pi Tickets"}],"effective_type":"type/Integer","id":1587,"display_name":"Gl Pi Tickets → ID","fingerprint":null,"base_type":"type/Integer"},{"semantic_type":"type/Name","coercion_strategy":null,"name":"name","field_ref":["field",1586,{"join-alias":"Gl Pi Tickets"}],"effective_type":"type/Text","id":1586,"display_name":"Gl Pi Tickets → Name","fingerprint":{"global":{"distinct-count":3360,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":2.741228070175439E-4,"percent-state":0.0,"average-length":37.77549342105263}}},"base_type":"type/Text"},{"name":"sum","display_name":"Somme de Temps passé","base_type":"type/Decimal","effective_type":"type/Decimal","field_ref":["aggregation",0],"semantic_type":null,"fingerprint":{"global":{"distinct-count":14,"nil%":0.0},"type":{"type/Number":{"min":5.0,"q1":8.04043009509531,"q3":22.8309518948453,"max":135.0,"sd":19.49604003923346,"avg":19.00862068965517}}}}],"creator":{"email":"hotline@jalix-services.com","first_name":"Hotline","last_login":"2021-06-01T13:29:11","is_qbnewb":false,"is_superuser":true,"id":1,"last_name":"JALIX","date_joined":"2019-11-22T10:57:58","common_name":"Hotline JALIX"},"can_write":true,"database_id":2,"enable_embedding":false,"collection_id":null,"query_type":"query","name":"Temps passé par Jalix sur les demandes du mois précédent 2022","last_query_start":"2022-01-05T15:56:33.63951Z","dashboard_count":0,"average_query_time":109.3571,"creator_id":1,"moderation_reviews":[],"updated_at":"2022-01-05T16:56:33","made_public_by_id":null,"embedding_params":null,"cache_ttl":null,"dataset_query":{"type":"query","query":{"source-table":132,"joins":[{"fields":[["field",1587,{"join-alias":"Gl Pi Tickets"}],["field",1586,{"join-alias":"Gl Pi Tickets"}]],"source-table":151,"condition":["=",["field",1348,null],["field",1587,{"join-alias":"Gl Pi Tickets"}]],"alias":"Gl Pi Tickets"}],"filter":["and",["=",["field",1346,null],1220,1221,1222,1223,1225,681],["time-interval",["field",1592,{"join-alias":"Gl Pi Tickets"}],-1,"month"],["=",["field",1560,{"join-alias":"Gl Pi Tickets"}],2]],"expressions":{"Temps passé":["/",["field",1358,null],60]},"aggregation":[["sum",["expression","Temps passé"]]],"breakout":[["field",1587,{"join-alias":"Gl Pi Tickets"}],["field",1586,{"join-alias":"Gl Pi Tickets"}]]},"database":2},"id":103,"display":"table","last-edit-info":{"id":1,"email":"hotline@jalix-services.com","first_name":"Hotline","last_name":"JALIX","timestamp":"2022-01-04T20:11:57"},"visualization_settings":{"table.pivot_column":"name","table.cell_column":"sum"},"collection":null,"created_at":"2022-01-04T19:56:11","public_uuid":null}`

Also java is version 13 : 
```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

**Comment by flamber** [comment]
You are either seeing seeing #19465 or #19889, since the problem is with the export.

Java 13 has been EOL for a couple of years: https://endoflife.date/java
