### ISSUE TITLE
Converting SQL based model back into a saved SQL question isn't working as expected

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19548]
**Describe the bug**
Converting SQL based model back into a saved SQL question shows a "New question Started from [saved sql question name]" instead of directly showing an actual saved sql question. The same error appears as in #19546.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to a collection that has sql-based model
2. Open that model
3. Click on an down arrow next to a question's name to reveal a set of possible actions
4. In the sidebar under the "Model management" section, click on "Turn back into a saved question"
5. "Doing science" finishes, the sidebar shows an error from the #19546, and the question is actually "A new question started from the original one" instead of the originally saved question (please see the screenshot)

**Expected behavior**
Reverting back to the saved question should show that saved question.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/148139966-ad71aa61-0430-449a-9772-505962710229.png)

**Information about your Metabase Installation:**
local dev, master, 42a6a4d, H2 Sample Dataset)

**Severity**
WIP, should be fixed before shipping

**Comment by flamber** [comment]
Regression = " Regression that is only present on master, or bug in new upcoming feature " / "  Bugs that were previously fixed and/or bugs unintentionally shipped with new features.  "
