### ISSUE TITLE
Tag 1.41.5 yarn dev error

### ISSUE THREAD

**Issue by babyyage** [metabase/metabase#19567]
when i run 'yarn dev' there are error happened
my environment like this:
nodejs:12
yarn:1.22.17
![1641460012(1)](https://user-images.githubusercontent.com/28697181/148360606-375a5512-8cfe-4672-9528-f1d78793001f.png)

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://www.metabase.com/docs/latest/developers-guide/build.html
