### ISSUE TITLE
Version 0.41.5 download link for Mac - returns 404

### ISSUE THREAD

**Issue by Oiwawa** [metabase/metabase#19569]
**Describe the bug**
The downloading page for the Metabase Mac Application return 404
Code: "NoSuchKey"

**Logs**

**To Reproduce**
1. Go to [Mac Download page](https://www.metabase.com/docs/latest/operations-guide/running-the-metabase-mac-app.html)
2. Click on "Metabase Mac Application" in the second paragraph, this opens the downloading page "https://downloads.metabase.com/v0.41.5/Metabase.dmg"
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/78601126/148391271-bcb09967-94b0-4f6f-9051-3a563740640e.png)

**Severity**
Not severe.

**Comment by flamber** [comment]
You can download the previous version: https://downloads.metabase.com/v0.41.4/Metabase.dmg

**Deprecation notice**
The Mac App will stop being released from 0.42.0, so I would advise you to use one of the other ways of trying out Metabase.
https://www.metabase.com/docs/latest/operations-guide/installing-metabase.html

**Comment by rlotun** [comment]
apologies for the delay in getting 41.5 updated. it should be there now.
