### ISSUE TITLE
Events can be duplicated even when no action is performed

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#1957]
When metabase is heavily used it can get quite slow. In this case an action by the user doesn't looks like it isn't working so some impatient users (like me) hit the button of the desired action several times. So far so normal the problem is that every click creates an event on the timeline where only the first one actually does something.
For example here you can see me trying to delete a question last night: 
![image](https://cloud.githubusercontent.com/assets/8144392/13114317/4bda965c-d593-11e5-9f82-951bfaec245b.png)
Only the first one actually has a name and deleted the questions the other ones are just me mashing a button. Those klicks shouldn't be shown in the activity-timeline in my opinion as they don't reflect any change.

You guys are doing an awesome job by the way. Metabase is a superb tool! Thanks a lot.

**Comment by camsaul** [comment]
This is probably a case where we just need to make sure something actually happened *before* firing the event, or prevent empty events from being created

**Comment by agilliland** [comment]
Yeah.  I'm curious why the write check didn't fail on the subsequent calls to the api, that should have prevented the rest of the endpoint code from executing.  But I agree that we can prevent this with a bit more checking to make sure the delete actually happens before we fire an event suggesting that it did.

**Comment by robinfrick** [comment]
I've also seen this happen with user sign ups. Unfortunately in that case I don't know why and didn't take a screenshot. But there were 4 entries in the activity stream stating the exact same ("User X has joined" or so)

**Comment by camsaul** [comment]
@agilliland It's probably because most of the permissions stuff is set to always return true for a superuser
