### ISSUE TITLE
Table and column metadata popovers don't work in nested questions started from datasets

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19577]
**Describe the bug**
Table and column metadata popovers don't work in nested questions started from datasets. Table metadata isn't showing at all, while column popovers sometimes show but result in an error (dev mode) or a page refresh (production).

**Logs**

**To Reproduce**
1. Open "Orders table" and save it as a question
2. Convert that question to dataset
3. Ask new question > Simple/Custom > Dataset > Choose Orders
4. Save nested question as "Orders from dataset"
5. Try hovering over the table name ("Orders") in the header - nothing happens
6. Try hovering over the column names - you will see popovers with metadata but at some point a big error is shown in the dev mode, while page refresh happens in the production mode
![image](https://user-images.githubusercontent.com/31325167/148459555-2db681d7-04ba-49d7-927a-90749710ced0.png)

**Expected behavior**
Table and column metadata popovers should work in the same manner as they do for the "regular" questions

**Screenshots**
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/o0uZQRr6/2eef2912-0d80-4bae-9f10-d65255793cc4.gif?v=24bc0f108acac5a16de53fbd7efcf1ba)

**Information about your Metabase Installation:**
local dev, master, 7c03e3e, H2, Sample Dataset

**Severity**
Mid to high.

**Additional context**
Please note the source of the question - it's using the "waffle" dataset icon next to "Our analytics/Orders". Two things are weird here.
1. the icon itself
2. the fact that it says "Our analytics / Orders" when it should say "Sample Dataset / Orders". @flamber should I file this as a separate issue?

**Comment by daltojohnso** [comment]
The root cause of the script error was that FKs are evaluated as number types, so I needed to add a bit more logic to safeguard against that in the popover fingerprint ui code.

The lack of a popover for nested card "tables" is a separate issue; more a feature-add than a bug, so @mazameli and I will address separately.
