### ISSUE TITLE
Turning back dataset into a saved GUI question doesn't restore the original visualization type

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19574]
**Describe the bug**
According to the specs, when you turn dataset back to the saved question, it should restore the question's original visualization type. Clicking on the "Undo" button in a notification bubble does that, but explicitly clicking on "Turn back into a saved question" doesn't. It shows the table instead.

**To Reproduce**
1. Save question with line chart visualization (Count of Orders created by Year)
![image](https://user-images.githubusercontent.com/31325167/148421112-1ed92afe-c4ba-44d0-8e71-07bff4c5efa5.png)
2. Convert question into a dataset
    - Click on an down arrow next to a question's name to reveal a set of possible actions
    - Click "Turn this into a dataset" icon
    - Click "Turn this into a dataset" button in a modal that appears
3.  Note that it turned into a table (expected)
4. In the "Dataset management" sidebar, click on "Turn back into a saved question"
5. The question still retains the tabular visualization instead of restoring the original line chart
![image](https://user-images.githubusercontent.com/31325167/148421438-fa3c8154-8da6-490e-a4ab-98dd36ee4fe2.png)

**Expected behavior**
The original visualization should be respected when turning the dataset back into a question.

**Information about your Metabase Installation:**
local dev, `master`, 7c03e3e56afa41822ec69eb172e5e8d52b0f6b4b, H2, Sample Dataset

**Severity**
WIP, should be fixed

**Comment by camsaul** [comment]
I don't think this one is a regression either bc we haven't shipped this feature

**Comment by dpsutton** [comment]
According to the spec, the visualization should remain a table according to the notion product doc:
![image](https://user-images.githubusercontent.com/6377293/148821596-2c5eaf18-8bbb-4676-9b29-f3101132d308.png)

This is not an error according to the spec as far as I can tell

**Comment by nemanjaglumac** [comment]
@dpsutton this was obviously my misreading and/or misunderstanding of the spec. I could've sworn I read somewhere that the question should preserve the initial visualization. Anyway, closing this issue with an apology and one more comment:

- Clicking the Undo button preserves the initial visualization
- Explicitly turning the dataset into a saved question doesn't
- Using the question sidebar history and clicking the revert correctly restores the visualization.

This all seems to be working as expected.
