### ISSUE TITLE
%-sign break all visualizations except pie-chart

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#1958]
As the title says, having a % sign within category names breaks all visualizations except pie charts.
For line and area charts "only" the x-axis labels are broken:
![image](https://cloud.githubusercontent.com/assets/8144392/13118803/4b31bb5a-d5a6-11e5-98ee-39ce4f97e79f.png)
![image](https://cloud.githubusercontent.com/assets/8144392/13118813/553da0dc-d5a6-11e5-8076-69ccb9aa8d65.png)
![image](https://cloud.githubusercontent.com/assets/8144392/13118823/5d944d94-d5a6-11e5-8664-b086af1f49e1.png)
![image](https://cloud.githubusercontent.com/assets/8144392/13118838/6728240c-d5a6-11e5-8d57-49b4d750b250.png)
![image](https://cloud.githubusercontent.com/assets/8144392/13118847/72e990f0-d5a6-11e5-8c0b-c4a4855ff18e.png)

**Comment by tlrobinson** [comment]
This appears to be the same issue as #855. Specifically, "100 %" happens to parse as a date (`new Date("100 %")` => `Fri Jan 01 100 00:00:00 GMT-0800 (PST)`) but `isFinite("100 %")` is false (while `isFinite("100")` is true). This is obviously not correct. We're going to switch to only parsing ISO 8601 dates.
