### ISSUE TITLE
Metabase constantly fails to be up and running due to DB to column relation already exists

### ISSUE THREAD

**Issue by ybakshi** [metabase/metabase#19598]
**Describe the bug**
Metabase fails to come up saying "<column_name>" and "<table_name>" relation already exists. It is looking at migration/000_migrations.yaml. Even if I remove this entire file from there, still somehow it gets it as it shows the same path migration/000_migrations.yaml in the logs. I tried commenting out all the code in yaml where it refers to this field, BUT still Metabase fails to come up due to same field with same message

**Logs**
[Migration-logs.txt](https://github.com/metabase/metabase/files/7834715/Migration-logs.txt)

**To Reproduce**
No idea as to how to reproduce. This issue has occurred suddenly  

> ERROR can be seen at line number 128: 
> ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::38::camsaul failed.  Error: ERROR: column "points_of_interest" of relation "metabase_database" already exists [Failed SQL: ALTER TABLE public.metabase_database ADD points_of_interest TEXT]

**Expected behavior**
Metabase should be up n running

**Information about your Metabase Installation:**
https://nebory-metabase.herokuapp.com/
I am using postgres and not H2

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres 13.5
- Metabase version: (e.x. 0.19.3)
0.41.5
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
Heroku
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)
Postgres

**Severity**
1 - Heighest as the team is blocked, nothing can be done until Metabase comes up.

**Additional context**
Earlier app nebory metabase was not working at all sighting same error, so we created new nebory-metabase app and copied all data to this new app DB, still no luck, same error.

**Comment by flamber** [comment]
Hi @ybakshi 
Which version was the earlier app "nebory" running before you started having problems?
It looks like you have some corruption of the application database.
Attach the output of `SELECT * FROM "public"."databasechangelog"`

**Comment by ybakshi** [comment]
I guess it should be the same as I was using it until I believe up to 27 or 28th of December. Since I was not able to use my account after I enabled MFA and I failed to install Heroku Authenticator I did not use real my account and raised support ticket with Heroku and they immediately helped and my account is working now. BUT I see that my metabase app was not working. So I referred the internet and started finding fix. In that attempt, I executed following:
1. Created new instnance 
2. Ran migration separately as java -jar metabase.jar migrate force
3. Tried allocating more memory 
4. Tried removing /resource/migrations/000_migrations.yaml or even commenting out I'd: 38 change set.  No luck. I don't know but some how it finds the yaml and fails at id: 38 change set.

**Comment by flamber** [comment]
@ybakshi 

I would recommend that you revert to your backup. You've done way too many things now, so you're likely in a more corrupted state.

I asked for the output of `SELECT * FROM "public"."databasechangelog"`, but that doesn't really matter if you have made so many hacks already.

You should absolutely not use `migrate force` unless you know what you are doing.

There's nothing wrong with Metabase, just your installation, so please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by ybakshi** [comment]
So, there is nothing that you can help with? I believe, if you could help with "points_of_interests already exists" error.

**Comment by flamber** [comment]
@ybakshi 
This is a bug tracker. If you need help with your setup, then use the forum: https://discourse.metabase.com/
And include the output of `SELECT * FROM "public"."databasechangelog"`
Metabase is trying to recreate columns, which fails, because you have a corrupted application database.

**Comment by ybakshi** [comment]
You can close this as we have solved the issue. Thanks for your time.

**Comment by flamber** [comment]
@ybakshi It would be very helpful if you explained what the problem was and what you did to fix it, so others can learn from it.

**Comment by ybakshi** [comment]
Sure @flamber, sorry, I should have mentioned earlier. Basically, we reverted back to an older version where we did not see Metabase initialization went errorless and Upgraded only till the version where we did not see migration errors. For our purpose, we do not need to be on latest version. Now, I can see all my data, all queries/dashboards everything and is working fine
