### ISSUE TITLE
[Axis]Axis display bug

### ISSUE THREAD

**Issue by ily52** [metabase/metabase#19601]
record_week is used as the horizontal coordinate. The value must be 0 or 1.
![image](https://user-images.githubusercontent.com/86505209/148711581-36310701-b9a9-4705-be7a-6b313ee13044.png)
However, the coordinates of the line chart drawn by Metabase are abnormal.
![image](https://user-images.githubusercontent.com/86505209/148711632-af99463a-c614-4e68-ac21-94d6b34d8fa2.png)

It seems that there is a problem with linear interpolation on the axis.
Please contact lovelotus52@icloud.com

**Comment by flamber** [comment]
Duplicate of #15188
