### ISSUE TITLE
DashboardApp props.isDirty is true after creating and saving a new dashboard

### ISSUE THREAD

**Issue by zbayoff** [metabase/metabase#19605]
**Describe the bug**
After creating a new dashboard, adding a text tile, and saving, the `isDirty` prop is still `true`. It should be `false`. 

**To Reproduce**
1. Click `Create` -> `New Dashboard`
2. Add a text tile.
3. Save the dashboard
4. See that the `isDirty` prop is `true`, on the `DashboardApp` component.

**Expected behavior**
After saving a dashboard, `isDirty` should be `false`

**Information about your Metabase Installation:**
`v1.41.5`

**Severity**
This is blocking a feature we're implementing to add an unsaved changes confirmation modal when a user makes a change to a dashboard and tries to navigate away.

**Comment by nemanjaglumac** [comment]
FWIW, it stays in that state even after I add a regular question to the dashboard.

Nice catch, @zbayoff

**Comment by zbayoff** [comment]
@nemanjaglumac Wondering if this bug will be addressed soon? It is blocking a feature we're working on. Thanks.

**Comment by nemanjaglumac** [comment]
@zbayoff I am sorry that I missed this message until now.

@npfitz has a PR ready that should fix this 🎉
