### ISSUE TITLE
Archived sub-collections are still showing in Permissions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19603]
**Describe the bug**
Archived sub-collections are still showing in Permissions.
Regression since the new permission hierarchy view in 0.41.0
From all my testing, it doesn't seem to cause any other strange behavior, but it's definitely confusing.

**To Reproduce**
1. Create a collection under "Our analytics" called "Level1"
2. Create another collection under "Level1" called "Level2"
3. Archive the collection "Level2"
4. Admin > Permissions > Collections - it will still show "Level2" collection (even after a browser refresh, so it's not a browser cache)

**Expected behavior**
Archived collections (and it's children) should not show up in Permissions either.

**Information about your Metabase Installation:**
Tested 0.40.5 thru 0.41.5 and master `43eae81`

**Comment by camsaul** [comment]
Assigning to @adam-james-v for now, @dpsutton and @adam-james-v if you decide this isn't a good fit ping me and I will reassign

**Comment by camsaul** [comment]
For this one I think all we would need to do is add `:archived false` somewhere in the queries powering the API endpoint in question and then write a test for it. So this is potentially a one-liner and a relatively easy test
