### ISSUE TITLE
Exported CSV Files are not UTF-8 Encoded

### ISSUE THREAD

**Issue by anthofo** [metabase/metabase#1961]
CSV files generated with the "download this data" button on windows are not encoded with utf-8.
This leads to encoding problems with accentuated character. 

For instance "coupé" becomes "coupÃ©".

**Comment by agilliland** [comment]
@camsaul you mind taking this one?

**Comment by camsaul** [comment]
:+1:

**Comment by camsaul** [comment]
@anthofo was this from a SQL query or did you use the UI to build your query?

**Comment by anthofo** [comment]
I used the ui

**Comment by camsaul** [comment]
On a Mac, I've had data come back as UTF-8 in most cases but it comes back as `ISO-8859-2` when you run a raw SQL query like this (against the sample dataset / H2):

```sql
SELECT 'Conchúr Tihomir'
```

Gives me this CSV file:
```csv
stringdecode('conch\u00far tihomir')
Conch˙r Tihomir
```

Does anybody know what a `stringdecode` is? Is that some sort of Javascript function?

**Comment by anthofo** [comment]
I didn't not try the raw sql. I'll try it tomorrow at work to see the
export result.
I'm wondering if the os default encoding could be the problem when building
query from ui, I'll try to run the metabase jar with the
-Dfile.encoding=utf8 parameter, it could fix the problem

**Comment by camsaul** [comment]
@anthofo I think I figured it out. Including`charset=utf-8` in the `Content-Type` of the CSV download endpoint fixed it for me, see PR #1966

Give that one a show if you get the chance and let me know if it fixes your issue.

**Comment by camsaul** [comment]
Tried this on a windows box as well and it looks like it's working.

**Comment by anthofo** [comment]
Did not work for me, 

for instance for this request : 
02-19 14:56:15 DEBUG generic-sql.native :: SELECT 'coupé'

When downloading I have the new content-type : 
Content-Type:text/csv; charset=utf-8

But the file is still encoded in ANSI. 
The content-type header just indicates that the downloaded file should be utf-8 encoded, but it does not re-encode the content in utf-8 (you can set any string as charset)

**Comment by camsaul** [comment]
@anthofo did you try running with `-Dfile.encoding=utf8`?

**Comment by anthofo** [comment]
Yes I tried but it did not work :(
My database is also in utf-8 and I didn't have any encoding problems with
other tools, so I guess data are written with the default os encoding but I
don't understand why because  the file.encoding setting usually does the
trick with Java apps.
Too bad I didn't learn clojure yet, I could have dig the problem and pr :(

**Comment by camsaul** [comment]
@anthofo what database are you using?

**Comment by anthofo** [comment]
Mysql 5.6

**Comment by camsaul** [comment]
@anthofo Can you try my PR #1998 and see if that fixes your issues?

**Comment by camsaul** [comment]
Ok, this should be fixed now that #1998 is merged. @anthofo pull our latest from master if you get a chance and let me know if  it resolves your problem? :grimacing: #kanye

**Comment by agilliland** [comment]
We need a :kanye: emoji

**Comment by anthofo** [comment]
Thanks it works :) 

But please note that the encoding is UTF-8 without BOM (http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom), that can lead some softwares to not recognize the encoding (e.g. excel... ). But some other softwares does not recognize the BOM >< .

Without BOM is ok for me, it's pretty easy to add a BOM with a text editor.

**Comment by maliayas** [comment]
As @anthofo suggests, MS Excel can't recognize CSV files exported from Metabase. I'm using LibreOffice / OpenOffice to open them. Do you have a plan to add other export types such as XLSX? Not what I'm currently interested in but JSON and HTML export options would be useful as well. If those are not possible in the near future, is it possible to use UTF8 with BOM there?

**Comment by camsaul** [comment]
Hi @maliayas I don't think we have any plans to add `.xlsx` in the near-term future ourselves although we'd be happy to consider any PRs that added support for it.

We can look into making sure CSVs are exported with the byte-order marker so Excel can open them unmodified.

**Comment by maliayas** [comment]
Thanks very much!

**Comment by lmeurer** [comment]
I've did a trick.
I saved my file as json, copied the content and pasted in excel.
When you export to json, the results don't loose the encoding.
After this use the excel to separete the columns by comma.

**Comment by marcoruggine** [comment]
Hi guys, CSV without BOM is a huge setback when exporting-importing into other softwares... do you think you might change this in the future?

**Comment by senior** [comment]
@marcoruggine Could you test out the change I have in https://github.com/metabase/metabase/pull/7029 to see if it fixes the issues you were having?

**Comment by marcoruggine** [comment]
@senior could you generate a docker image so I can install a new issue of metabase?
I only know how to run metabase on docker because I'm not skilled in this field and my guys set up an environment to make me independent on the updates :)
