### ISSUE TITLE
Cannot add more than two group by columns

### ISSUE THREAD

**Issue by anthofo** [metabase/metabase#1962]
I cannot use more than two columns in "group by" expressions. Once I have added a second column, the "add" button disappear : 

![metabase - google chrome_2](https://cloud.githubusercontent.com/assets/3809685/13139152/69c6deee-d62b-11e5-9fdc-78127d5c3934.jpg)

However, I have plenty of "dimension" columns available : 

![metabase - google chrome](https://cloud.githubusercontent.com/assets/3809685/13139117/3ab328d8-d62b-11e5-8ea0-acad303b3cbe.jpg)

**Comment by mazameli** [comment]
Hi, @anthofo. Can I ask what your desired end state is, or what specifically you're trying to accomplish?

**Comment by anthofo** [comment]
Hi,

I'd like to display all the possible combinations of (make,model,category).
I figured out that it was possible to bypass the limitation of 2 columns using the "Data reference" menu on the right, we can add as much group by columns as we want:

![prtscr capture_5](https://cloud.githubusercontent.com/assets/3809685/13171040/c58bb202-d6f0-11e5-85ba-5f3defd7e51a.jpg)
![metabase - google chrome_4](https://cloud.githubusercontent.com/assets/3809685/13171119/491f5d1c-d6f1-11e5-9819-f09ed92a2495.jpg)

But this solution is not very user friendly to simply add a group by column to the existing query

**Comment by mazameli** [comment]
Thanks for the info, @anthofo. Still not sure if you're trying to create a _pivot table_, or if you're just trying to only look at a subset of the columns in your table.

**Comment by anthofo** [comment]
Just the result of the classical sql group by expression : 

Given : 
```
MAKE     MODEL      CATEGORY          OTHER
make1    model1     category1         other1
make1    model1     category1         other2
make2    model2     category1         other5
```

I want to obtain :  
```
MAKE     MODEL      CATEGORY 
make1    model1     category1 
make2    model2     category1
```

**Comment by mazameli** [comment]
Perfect. That's super clear. Thanks man.

**Comment by agilliland** [comment]
@anthofo are you just planning to use that information for display in a table like you show above?  or have you been using that information in other visualizations of any kind?

one of the general reasons why we don't promote 3+ dimensional breakouts is that the ability to visualize data becomes quite difficult.

**Comment by anthofo** [comment]
Just to be displayed in a table as shown, in order to analyse the data, the
table contains millions of lines but most of them can be grouped so that we
can understand and use them

Le ven. 19 févr. 2016 à 20:36, Allen Gilliland <notifications@github.com> a
écrit :

**Comment by jpsfs** [comment]
I have the following use case that this feature will most likely solve, if implemented.

Imagine the following set of tables:

##### Product
```
Id Name     Brand     Description
1  n1         b1           d1
2  n2         b1           d2
3  n3         b2           d3
```

##### Supplier
```
Id Name
1  s1
2  s2
```

##### Pricing
```
ProductId     SupplierId     Date              Price
1                   1         2016/04/16         1.5
1                   2         2016/04/16         1,1
1                   1         2016/04/17         1.4
1                   2         2016/04/17         1.1
2                   1         2016/04/16         5.1
2                   1         2016/04/17         5.1
3                   2         2016/04/16         10.1
3                   2         2016/04/17         10.1
```

#### Goal

The end-user wants to see something like:

```
Product.Brand     Product.Name     Supplier.Name     2016/04/17     2016/04/16
b1                      n1               s1              1.5            1.4
                                         s2              1.1            1.1
                        n2               s1              5.1            5.1
b2                      n3               s2              10.1           10.1
```

Is this possible with metabase?

Best,

**Comment by jesusrtc** [comment]
+1

**Comment by falling-down** [comment]
+1

**Comment by tlrobinson** [comment]
In addition to tables, as of 0.20 it's also now possible to visualize 3 dimensions (and optionally a metric) with a multi-series scatter/bubble chart.

**Comment by jakthom** [comment]
+1

**Comment by tlrobinson** [comment]
@metabase/core-developers Any reason not to go ahead and increase the max number of breakouts to 3? Or more?

@jakthom @falling-down @jesusrtc @jpsfs @gincor @anthofo what is the maximum number of columns you'd like to group by?

**Comment by falling-down** [comment]
It's hard to say exactly. Essentially, the question is how far are you allowing users to "drill" into their questions. I can appreciate that from a visualization perspective it does not make sense to go beyond 2 or 3. But that does put a hindrance on the end-user to dive deeper into the data. Short answer, I think it should be somewhere between 6 to 8 as max.

**Comment by anthofo** [comment]
8 would be great

**Comment by tlrobinson** [comment]
This has been resolved since 0.21 I believe.

**Comment by swaroopksahoo** [comment]
is it resolved now guys?

**Comment by flamber** [comment]
@swaroopksahoo Yes, three years ago.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by airtelbharat** [comment]
@flamber, We did not see multiple column in pivot table. Below is the screen shot
![image](https://user-images.githubusercontent.com/67841054/87800889-9892c480-c86c-11ea-9ed0-57c39b077d20.png)

**Comment by flamber** [comment]
@airtelbharat You need two dimensions and one numeric column:
https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#pivoted-tables
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
There's a request to expand the Pivot to more columns like Excel - #3769 - upvote by clicking :+1: on the first post

**Comment by airtelbharat** [comment]
@flamber , with 2 dimension and 1 measure, its working fine with pivot. But i want to add more than 2 dimension and measures. it is possible?

**Comment by airtelbharat** [comment]
@flamber , I am looking some like this in metabase
![image](https://user-images.githubusercontent.com/67841054/87807893-72722200-c876-11ea-8788-1edee72b3ed6.png)
