### ISSUE TITLE
Duplicating model creates a question

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19631]
**Describe the bug**
According to the internal documentation, one of the ways to create new datasets is by duplicating the existing ones and modifying the copy. When you duplicate the existing dataset, it doesn't produce a copy of it. Instead, it creates a question.

**Logs**
N/a

**To Reproduce**
1. Create a dataset either from a regular question or an SQL
2. Open that dataset's sidebar
3. Click on "duplicate"
4. Note that the popup says "Duplicate this **question** (https://github.com/metabase/metabase/issues/19630)
5. Click on the "Duplicate" button in the modal
6. Note that the new duplicate **question** has just been created instead of a copy of the existing dataset

**Expected behavior**
If I understand the documentation correctly, duplicating the existing dataset should produce new dataset.

**Screenshots**

**Information about your Metabase Installation:**
local dev, `master`, c65c4b904ef354037217c2184b56c8caf1962396, H2, Sample Dataset

**Severity**
WIP, Should be fixed

**Comment by kulyk** [comment]
@dpsutton we use `POST /api/card` to duplicate stuff. I can see the FE sending `dataset: true`, but looks like the BE drops it when it creates a new question. Can you please take a look?

**Comment by dpsutton** [comment]
Fixed in https://github.com/metabase/metabase/pull/19724/commits/e0781bdf2f47f729d7dc6f42632784ca8bd8efea which is on the `dataset-metadata-editor-logic` branch.

**Comment by nemanjaglumac** [comment]
Please do not close issues that do not have the fix merged to the `master` branch.

**Comment by kulyk** [comment]
The fix is on `master` now

**Comment by satodu** [comment]
I still with this problem in version 0.49.1
