### ISSUE TITLE
Column names in queries don't get de-CLOBed

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1967]
Whats a `stringdecode`? This might be a problem with H2 itself.

![screen shot 2016-02-18 at 2 51 15 pm](https://cloud.githubusercontent.com/assets/1455846/13160869/199a2c90-d64f-11e5-9346-dbbe74eab8d7.png)

**Comment by camsaul** [comment]
Ok, so this looks like another limitation of `clojure.java.jdbc`. The `query` function automatically converts column names to string, probably via `str/.toString`, instead of de-clobifying them (like we do values that come back from the DB).

It looks like H2 automatically returns strings with unicode characters as CLOBs.

**Comment by flamber** [comment]
Not sure when this was fixed, but I cannot reproduce on 0.35.3:
`SELECT 'Conchúr Tihomir' AS "Conchúr Tihomir", 1 AS "1"`
![image](https://user-images.githubusercontent.com/1447303/82905256-ea515980-9f63-11ea-8a50-18382d7a9496.png)
