### ISSUE TITLE
Remove `/question/new` route 

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19677]
Once we decided to update and simplify starting points for asking the question, we changed that flow. Please see: https://github.com/metabase/metabase/pull/19572

In that process the route `/question/new` was forgotten. It still leads to the well known page that lets one choose between Simple Question, Custom Question and a Native Query
![image](https://user-images.githubusercontent.com/31325167/149433102-a2ceab57-6e16-4375-be66-51803bd0d5ea.png)

Unless someone manually enters that route, it's not possible anymore to reach it.
Product decided to remove it.

### Gotchas:
- ~~Large number of e2e tests is still relying on this flow and should be updated accordingly~~ (done in #21558 and #21564)

**Comment by kdoh** [comment]
One thing to remember to do when we remove this page is to remove the associated images in `/app/img/`

**Comment by mazameli** [comment]
⚠️ A note for any well-meaning person who comes across this issue: please don't implement this until talking with the Models and Metrics pod — it's quite likely that we're going to repurpose this screen/component for a `Create new model` flow. ⚠️

**Comment by nemanjaglumac** [comment]
@mazameli should we close the issue until we make the final decision?

**Comment by mazameli** [comment]
No, I suspect that we'll still want to remove this specific route (/question/new), but just keep the components and images it used.

**Comment by nemanjaglumac** [comment]
@gusaiani this can now be closed, right?

**Comment by gusaiani** [comment]
Closed by #26392
