### ISSUE TITLE
Dashboard "title" cards show scrollbars when they shouldn't on Firefox

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#19671]
**Describe the bug**
A common pattern we use is to create a text card that's only one "row" high on a dashboard and then use a markdown h1 (#) as a title. This works especially nicely when you turn off the background of the card.  However, if your browser width is less than 1620px you'll often see a scrollbar in this case, which isn't ideal because there isn't more content to actually see.

**To Reproduce**
1. Add a text card to a dashboard with any one line h1 content you choose (e.x. # Hey there).
2. Save the dashboard
3. Set your browser width to be less than 1620px
4. You've got yourself a scroll bar.

**Expected behavior**
No scrollbars. Interestingly this doesn't happen in Safari.

**Screenshots**
![Screen Shot 2022-01-13 at 3 59 12 PM](https://user-images.githubusercontent.com/5248953/149408246-e8d4af8d-9c55-4317-b9ce-b2b13c960388.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox
- Your operating system: MacOS
- Metabase version: 0.41.x 
- Metabase hosting environment: Local / cloud
- Metabase internal database: Repro'd on h2

**Severity**
Annoying cosmetic issue.

** Additional info **
In my quick spelunking my guess is this is because the margins on headings are expanding the inner content of the card causing overflow. Firefox seems to calculate a larger size than Safari etc, hence the scrollbars.

**Comment by flamber** [comment]
This seems like it's an continuing story #13676 #14956
