### ISSUE TITLE
Editing Labels on Bar Chart is Extremely Laggy

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19683]
I have a stacked bar chart like this

<img width="1884" alt="image" src="https://user-images.githubusercontent.com/1455846/149470077-f1b71420-1f0c-49d2-b5c1-d676bdf1c057.png">

and attempting to edit the labels in the left-hand pane is **extremely** slow. It freezes for about a second after every letter I type, and if a type a few words quickly it freezes for 5 or 10 seconds.

I think it's rerendering the entire graph every time I change a character.

**Comment by flamber** [comment]
It should probably be requestIdleCallback/debounced similar to #10462 and #14601.
