### ISSUE TITLE
It's not possible to group by a temporal column WITHOUT using bucketing

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19684]
I have data where the timestamps are a few distinct values, and do NOT want to apply temporal bucketing to them. However it's impossible to "Summarize" by a timestamp column without choosing temporal bucketing.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/1455846/149473578-5b02cb09-0fc5-4640-8a0a-cde54d057ecf.png">

**Comment by flamber** [comment]
Very related to #13098 and #19504.

**Comment by camsaul** [comment]
It turns out that this is a regression. I was trying to follow along with the repro steps for #16839, but I can't due to this

**Comment by npretto** [comment]
Reproduced on metabase/metabase-enterprise:v1.41.5, the UI doesn't allow choosing the field without a bin
<img width="561" alt="image" src="https://github.com/metabase/metabase/assets/1914270/0faf75de-65e2-4e3d-a8a5-4b40500c5423">

Same behaviour on master
