### ISSUE TITLE
Dynamic Default Filters

### ISSUE THREAD

**Issue by linucksrox** [metabase/metabase#19687]
**Is your feature request related to a problem? Please describe.**
I have several dashboards with filters that include fiscal years and months. I would like to use a calculated value to set the default filter values any time the dashboard is loaded, but I only seem to be able to set a default manually which I can then update manually when we move into a new month or fiscal year.

**Describe the solution you'd like**
I'm looking for some way (could be an expression, could be based on data in a table) to set the default dynamically for a filter.

**Describe alternatives you've considered**
I am not sure of any other way to accomplish this, so I have been doing it manually as needed.

**How important is this feature to you?**
This isn't a critical issue for me, but would be extremely helpful for situations where people want to have scheduled reports emailed to them using filters that are updated dynamically. Currently if they don't take action manually to update their dashboard filters, then the automated reports don't provide up to date information which defeats the purpose for that use case.

**Comment by flamber** [comment]
That's already possible using relative Previous or Current instead of specific dates.
https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html

Closing in favor of #3156 and #4083
