### ISSUE TITLE
When creating data, select database types only H2, MySQL and PostgreSQL. no mongoDB

### ISSUE THREAD

**Issue by jiaxing-1994** [metabase/metabase#19694]
1.Pull the code from github and start it locally，version：0.41.5
2.run clojure -M:run and yarn build-hot
3.go to **admin->database->add database**
4.choose **Database type** 
<img width="1928" alt="WeChat6910897f47d6687ddfbf27b2c1386b70" src="https://user-images.githubusercontent.com/26563716/149554671-feff9414-e477-44d9-8d2b-f3d32f3a5ea3.png">

result: Database type is only H5,MySOL,PostgreSQL.

but when I run java -jar metabase.jar from the official，it is like this
<img width="1108" alt="WeChat4920d3cfa4912c8c448aaaa10d199e09" src="https://user-images.githubusercontent.com/26563716/149555529-9d16df48-9f74-4ea8-a31a-9a9bde1511d3.png">

and I want to use mongoDB in my local environment , Do I need to set something? or it is a bug

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Only three drivers are loaded in Clojure: https://github.com/metabase/metabase/wiki/Metabase-Backend-Dev-Secrets
