### ISSUE TITLE
[Epic] Improve basic keyboard accessibility across the product

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#19696]
#### Links
Product doc https://www.notion.so/metabase/Improve-basic-keyboard-accessibility-across-the-product-a98015cb3f6f400dbf88a5b8b7907d82

#### Plan

Forms:
- [x] Button
- [x] Toggle
- [x] CheckBox
- [x] Radio
- [x] ExternalLink
- [x] SelectButton
- [x] Select + AccordionList - https://github.com/metabase/metabase/pull/19858
- [x] FormTextFileWidget

Setup:
- [x] Basic navigation
- [x] Language selection
- [x] Database selection

Home:
- [x] Basic naviagtion

**Comment by mazameli** [comment]
Out of curiosity, are we still planning on adding arrow key navigation to the list of search suggestions that appears immediately when you focus on the main nav's search bar, and the list that appears once you start typing in that search? It looks like lots of this epic is done, but I'm not seeing that behavior on our Stats instance.

**Comment by ranquild** [comment]
@mazameli some time ago we decided to reduce the scope of the keyboard accessibility project to the setup and database forms. I believe that for search on the homepage we should create another issue / project.
