### ISSUE TITLE
Release script needs to create invalidation for version info files

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#19699]
**Describe the bug**
The release script can fail because the version info check fails, in `release.version-info/validate-version-info`.  The trouble is that `upload-version-info!` pushes the updated version info to S3, but does not create a Cloudfront invalidation (like we do for other S3 uploads) against `static.metabase.com`, which happens to be a different Cloudfront instance than `downloads.metabase.com`.

We therefore need to:

- Rename `release.common/cloudfront-distribution-id` to make it clear that is the distribution ID for `downloads.metabase.com` only
- Add another distribution ID for `static.metabase.com` (can get the ID from AWS console)
- Change the code in `upload-version-info!` to also push an invalidation to this distribution ID, similar to the other S3 related operations

**Comment by jeff303** [comment]
#19698 was also masking the problem here

**Comment by camsaul** [comment]
the invalidation should probably happen here

https://github.com/metabase/metabase/blob/3c980639cb3ca9e943bc70925ed48e5a21e12ac0/bin/build/src/release/version_info.clj#L79

after we upload the files

**Comment by camsaul** [comment]
or after the `s3-upload!` calls.

This is an example of a place we are creating cloudfront invalidations. We can use this same function to do the invalidation for the version file

https://github.com/metabase/metabase/blob/5e9b52a32dfeab754d218c758d08fffbacb7c0e7/bin/build/src/release/common/upload.clj#L14
