### ISSUE TITLE
Collection icon inconsistency in dropdowns

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19704]
**Describe the bug**
Collection icon in "New" header button and collection icon in the dropdown menu for creating new collection items are different.

New (route: `/`)
![image](https://user-images.githubusercontent.com/31325167/149598567-956623cf-f188-4890-991c-1efbded9e92a.png)

New collection item (route: `/collection/root`)
![image](https://user-images.githubusercontent.com/31325167/149598646-39f896b1-26e3-4776-8363-c7afeccc62b0.png)

Search filters (route: `/search`)
![image](https://user-images.githubusercontent.com/31325167/149598768-a1a6f0eb-a793-4998-a47c-7d6af6b25c5a.png)

Collections sidebar (route: `/collection/root`)
![image](https://user-images.githubusercontent.com/31325167/149598874-a3aa4175-61d4-4c40-9228-49c63ee18feb.png)

@mazameli which one should we use? :)

**Comment by mazameli** [comment]
Good catch, @nemanjaglumac. We should be using the `folder` icon to represent collections everywhere.
