### ISSUE TITLE
BigQuery Cloud SDK Driver does not verify `Dataset ID`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19709]
1. Add a new database with the BigQuery Cloud SDK driver. Enter some random characters for the `Dataset ID`
2. Save database
3. No error messages

This should probably check that the dataset actually exists in the `can-connect?` method and error if it does not.

Related to #19708. I was trying to change the name of an existing database, I had to re-enter the Dataset ID, and I guessed it (wrong, it turns out). I didn't realize anything was busted until I had a completely empty DB with no Tables anymore and I couldn't run any queries

**Comment by dpsutton** [comment]
I'm not sure I'm following. 

When using the deprecated bigquery driver I see a "Dataset ID".
<img width="723" alt="image" src="https://user-images.githubusercontent.com/6377293/165340348-e0d66a50-3bc1-4a4c-ac6d-4725b4ae372e.png">

But when using the Bigquery Cloud SDK driver I do not see that. I only see project id
<img width="748" alt="image" src="https://user-images.githubusercontent.com/6377293/165340496-0a8d3b4a-c392-4101-ace7-25b24724a5f2.png">

But tracing how we use project id seems kinda crazy. If you set a project id, we:
- update the schema for all existing tables on that database to be whatever you entered for project id
- set an inclusion filter for just that schema

This seems fundamentally broken. Those tables are not in that schema necessarily. On the next sync we will only look for tables in the schema named whatever you put for project id. The tables have their own schema which is entirely unrelated to the project id you entered. I cannot fathom the thought behind this change.

- normalize-db-details looks for `dataset-id` and converts that to a filter [source](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj#L357)
- that updates tables to have that as its schema which seems fundamentally broken [source](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj#L322)

As far as I can tell, we should not ask for a project id. It is broken and is not a project-id functionality at all. It adds schema filters but on a value that is not a schema. The project id comes from the service account json file unambiguously and we do not add any override functionality at all. I'm not sure what it is doing there.

**Comment by flamber** [comment]
@dpsutton You set datasets here:
![image](https://user-images.githubusercontent.com/1447303/165348586-9c126882-a0a6-47b5-aa5b-26094677f724.png)

**Comment by dpsutton** [comment]
@flamber if that's the case I'm not sure I follow this issue. If you type things into the schema filter and no tables come back because none match that filter that doesn't seem to be an error. Is that the actual issue here? I didn't think Cam added a schema filter but thought he had to enter a required dataset id parameter.

**Comment by flamber** [comment]
@dpsutton Try inputting a dataset, which doesn't exist like `random_does_not_exist` - save - there's no validation.
This is mostly a problem if someone does a spelling mistake.
But Cam has to provide more context, if there's something else.
