### ISSUE TITLE
Translation of Dashboards and table names/columns

### ISSUE THREAD

**Issue by pedrokost** [metabase/metabase#19716]
**Is your feature request related to a problem? Please describe.**

Is it possible to provide translation files for Dashboards and Table names, Table columns and Dashboard filters? This is useful when embedding dashboards into other apps.

**Describe the solution you'd like**

The ability to upload a translation file that would apply to embedded dashboards. The wanted language can be provided in the embedded code. 

Optionally, it would be great to be able to export all dashboard/table strings  

**Describe alternatives you've considered**

na

**How important is this feature to you?**

It's not a deal breaker, but would improve the usability of dashboards in our multi-language app. 

**Additional context**

![image](https://user-images.githubusercontent.com/725286/149781449-435aa992-5bed-4cae-8ea8-2ca206e3b425.png)

**Comment by flamber** [comment]
Closing in favor of #9508 and #8490
