### ISSUE TITLE
Wording unprecise for large tables in "data reference"

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#1972]
Very minor thing I noticed:

When browsing the "data reference" help part the entry of tables offers a link to select * from that table: "Show all X rows in TABLE". Where X is the number of rows. But the query builder only shows up to 2000 rows. So I think the wording for large tables with more than 2000 rows should be: "Show the first 2000 rows in TABLE".

![image](https://cloud.githubusercontent.com/assets/8144392/13174670/a16e18a0-d705-11e5-9672-479547fb3b6b.png)

**Comment by mazameli** [comment]
That's good feedback. I'd suggest, "See the raw data for Be Links" and avoid referencing the count of rows at all.

**Comment by kdoh** [comment]
@mazameli I think thats somewhat better but it still doesn't indicate the fact that you're seeing a subset of the rows which I think is important to communicate. I'm inclined to go with something along the lines of "Show a sample of Be Links data" when dealing with tables that have more rows than our cap allows in raw data views.

**Comment by mazameli** [comment]
I don't know if I think that is important in that specific context. We don't do that in the View/aggregation dropdown for the Raw Data option either, you know? The way we specify how much of the raw data you're seeing is by indicating "Showing 2000 rows" in the top-right of the query builder screen.

**Comment by kdoh** [comment]
Thats true. Something about the context of the data reference and those pre-baked queries is making me want to be more explicit and explanatory in the text since its meant to be an aid if you're unfamiliar with the structure, but you're right that we handle the notion of how many you're seeing elsewhere already.
