### ISSUE TITLE
[New question picker] Moved model's collection isn't displayed until page refresh

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19737]
**Describe the bug**
When you move a model to some new collection and then go to the new > question, that new collection is not visible in the data picker until the page refresh. Interestingly, the model itself IS visible and when you click on it, it will show the correct collection in the title (breadcrumbs)

**Logs**
N/A

**To Reproduce**
1. Move a saved model from the root collection to some other collection (for example your private collection)
2. New > Question > Choose "Models" from the data picker
3. You cannot browse that new collection because it's not offered
4. Moved model is still visible as if it's the part of the "Our analytics"

**Expected behavior**
UI should be updated immediately.

**Information about your Metabase Installation:**
local dev, `master`, df15e689652082f538526d338363a56a9814d087, H2, Sample dataset

**Severity**
P3

**Comment by kulyk** [comment]
I can reproduce it for regular saved questions as well. Is there an issue for that, cause the fix should affect both ideally?
