### ISSUE TITLE
database selector is getting squished (max-width?) on data model page

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1973]
not sure why this popover isn't expanding a bit wider.
<img width="462" alt="screen shot 2016-02-19 at 9 37 08 am" src="https://cloud.githubusercontent.com/assets/1987787/13183591/7cfee210-d6ec-11e5-867b-c1ba4d43f6eb.png">

**Comment by kdoh** [comment]
I can't seem to reproduce this issue. Even with some long names and a decently long list of them I still see the modal expand beyond the width your screenshot is showing. 

<img width="759" alt="screen shot 2016-02-19 at 10 25 48 am" src="https://cloud.githubusercontent.com/assets/5248953/13184898/5915dea6-d6f3-11e5-9686-1ae7072bafc5.png">

Actually as far as I can tell we aren't setting an explicit max-width in that popover element (though as you can see from that screenshot, we probably should)

**Comment by kdoh** [comment]
@agilliland can you think of anything special going on with your databases locally that would be causing that?

**Comment by agilliland** [comment]
strange.  nothing i can think of, but it's possible that something about my local dev enviroment is a little different.
