### ISSUE TITLE
Models deleted from the archive show up as "questions" in the `/activity` page

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19741]
**Describe the bug**
When you delete a model from the archive, and then go to the `/activity` page, it still says "Deleted a question".

**Logs**
N/A

**To Reproduce**
1. Archive a model
2. Go to the archive
3. Hover over a model and click on the trash icon
4. Delete a model
5. Go to `/activity`
6. Notice it says "Deleted a question", although the code for that was changed and it should say "Deleted a model"

https://github.com/metabase/metabase/blob/5cf546a5a5da233ce8ab21ffdb6ae724ba19e052/frontend/src/metabase/home/components/Activity.jsx#L176

**Expected behavior**
The message should say "Deleted a model"

**Information about your Metabase Installation:**
local dev, `master`, 46b8df1129e2518b9296fcc26ec60a3a98fe46c9, H2, Sample Dataset

**Severity**
P3 at best

**Comment by kulyk** [comment]
Seems to be a BE thing: for `delete-card` activity item, the `model` is set to`"card"` when `"dataset"` is expected
