### ISSUE TITLE
Dashboard add-question sidebar is limited to showing 50 questions per collection

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19748]
**Describe the bug**
Dashboard add-question sidebar is limited to showing 50 questions per collection, which was done to prevent loading huge slow lists on large instances, but it is not obvious that Metabase is only listing the first 50 questions in the collection alphabetically.
And the search can be confusing and don't prioritize questions in the collection I'm viewing, so it can be difficult to find things #19366

It's a "regression" since 0.40, which introduced pagination on the sidebar to prevent overload on large instances.

**To Reproduce**
1. Create more than 50 questions in a collection
2. On dashboard, open the add-question sidebar and go to that collection
3. It will only show the first 50 questions (alphabetically)

**Expected behavior**
Pagination. Either manual or auto-pagination, when scrolling down.

**Information about your Metabase Installation:**
Tested 0.40.0 thru 0.41.6

**Additional context**
Likely very related to #19366

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by calherries** [comment]
Pagination doesn't work in the main search bar either. Would that be a regression too?
