### ISSUE TITLE
Serialization should allow including archived objects on dump

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#19763]
**Describe the bug**
Serialization process will maintain "archived" status of questions or dashboards on the load

**Logs**
None

**To Reproduce**
Set up a origin and destination Metabase
1) create a question and a dashboard in the origin
2) dump and load to destination
3) archive question or dashboard in origin
4) do a dump and a load in destination with --mode update
5) questions in source are archived, but not in destination

**Expected behavior**
We mention that dumps include the archived questions/dashboards... but maybe this is the intended behavior as we move the questions/dashboards but not the archived state of those? either way, we should update the way this works or the documentation

**Screenshots** (gif to show the result)
![archiving](https://user-images.githubusercontent.com/1711649/150040937-07a75ed9-2e36-4def-96aa-6a7f76472a07.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: Sample dataset
- Metabase version: 1.41.5
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Depends on the use case, but if the feature is needed for consistency, this feature is really needed.

**Additional context**
NA

**Comment by flamber** [comment]
Archived objects are not included in the dump - to prevent #14911.
This should either be closed or changed to feature request for adding a parameter.

**Comment by paoliniluis** [comment]
then it's a change in the documentation. I'll add it to https://github.com/metabase/metabase/pull/19732
