### ISSUE TITLE
Serialization overlaps cards on load

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#19762]
**Describe the bug**
When changing the arrangement of the cards in a dashboard in the source, the load process ends up with a really weird arrangement and even in the DB it seems that the cards are overlapped (according to the row and column values in the table)

**Logs**
No relevant logs

**To Reproduce**
1) Set up a source and destination Metabase
2) Build in the source 2 questions and a dashboard
3) Add the 2 questions in the dashboard in a 2x2 array like (image 1)
![image](https://user-images.githubusercontent.com/1711649/150035512-780e4246-92fb-4ecd-b091-7ecbcb39b3eb.png),
4) dump and load into destination
5) now swap the cards in the second column to (image 2)
![image](https://user-images.githubusercontent.com/1711649/150035847-e606c7ec-8436-418d-b1d7-fb18e4521d8e.png)
6) do a dump and load with --mode update to persist the changes in the destination
7) check the dashboard in the destination, which now has the 4 cards in the same column

Note: if you see what happens in the database, the source has the correct arrangement (check row and column columns):
![image](https://user-images.githubusercontent.com/1711649/150036146-5eb11f7e-2c7c-46a8-a4d1-3a7cab91e876.png)
but the destination is all messed up
![image](https://user-images.githubusercontent.com/1711649/150036184-2895512b-7219-4358-b8aa-413bb77dc2f4.png)

EDIT: so something even more tricky here, if you run the "load" command again after step 6... the cards will be rearrange fine, but if you run once more, it will be overlapped again.
![arrangement](https://user-images.githubusercontent.com/1711649/150039807-d4ad6259-2773-42ff-8d22-7987fa20ab3c.gif)

**Expected behavior**
Have an exact clone of the dashboard in the source

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: Sample dataset
- Metabase version: 1.41.5
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL 14.1

**Severity**
Well... it can make a mess, so users will have to rearrange everything after each load

**Comment by flamber** [comment]
For more context for developers https://github.com/metabase/metabase/pull/17388#issuecomment-900415001
