### ISSUE TITLE
long database names overflow database selector dropdown

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1976]
<img width="501" alt="screen shot 2016-02-19 at 10 59 15 am" src="https://cloud.githubusercontent.com/assets/5248953/13185810/f89e3334-d6f7-11e5-95ab-eee589b30386.png">

**Comment by mazameli** [comment]
So what you're saying is that this will be a problem for German databases, like a DB about laws delegating German beef label monitoring: "Rindfleischetikettierungsueberwachungsaufgabenuebertragungsge."

**Comment by kdoh** [comment]
You are correct in observing we're not umlaut proof at all.
