### ISSUE TITLE
New data picker shows blank after archiving a model

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19776]
**Describe the bug**

**Logs**
```
schemas.js:68 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'collection')
    at reducer (app-main.hot.bundle.js:113032:122)
    at app-main.hot.bundle.js:132488:12
    at combination (vendor.hot.bundle.js:328703:29)
    at combination (vendor.hot.bundle.js:328703:29)
    at dispatch (vendor.hot.bundle.js:328941:22)
    at vendor.hot.bundle.js:296969:18
    at vendor.hot.bundle.js:328437:12
    at app-main.hot.bundle.js:155308:14
    at dispatch (vendor.hot.bundle.js:328492:18)
    at _callee3$ (app-main.hot.bundle.js:132553:21)
```

**To Reproduce**
1. Go to `/collection/root`
2. With the presumption that you have at least one model there, go ahead and archive it
3. Click on the "New" button in the nav bar
4. Select "Question"
5. Data picker doesn't appear and it's impossible to click on "pick your starting data" until refresh

**Expected behavior**
It should be possible to choose the source for the new question immediately without any errors and without refreshing.

**Screenshots**

**Information about your Metabase Installation:**
local dev, `master`, 5789dbe9338a70b5fe21e8b8a9ab84c96c6f70e7, H2, Sample Dataset

**Severity**
P2?

**Additional context**
Probably the same cause as #19742, only the different trigger

**Comment by alxnddr** [comment]
@nemanjaglumac I could not reproduce it:
<video src="https://user-images.githubusercontent.com/14301985/152050556-e1565d32-32fe-429a-ba46-17700e090bbd.mov" />

Are there any other pre-conditions?

**Comment by nemanjaglumac** [comment]
@alxnddr It seems it has been fixed in the meantime. I cannot reproduce it, either. Neither locally, nor in Cypress.
