### ISSUE TITLE
databases without tables are listed and seem clickable in the query builder database selector but do nothing

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1977]
I stumbled into this one as a result of looking into #1973 and creating a bunch of fake databases.

Basically we're being optimistic that someone will add a database with tables but we're not handling the case where that isn't true very well.

There are a couple routes to go here.
1. We could not show databases with no tables in the selector at all. The thinking here is that there's no data for you to interact with so why clutter the list in the first place.
2. We show those databases but show that there are no tables when clicking through to the table listing. This helps reinforce the fact that your addition was successful but might overindex on people adding tables with no data in them (which I'm hoping isn't all that common)

There are probably some follow up "empty states" in the admin panel that are also related to this. In the case of the data reference we're simply not even showing DBs that don't have any tables.

**Comment by mazameli** [comment]
Good catch. Perhaps #2, but display the DB in the list as faded out and unclickable. Maybe append "(empty)" or "(no tables)" to its name?

**Comment by agilliland** [comment]
I'm happy to tackle this when we have a plan for how we want to treat it.

I'd agree with Maz that displaying the Database in the list but making it unclickable is probably the best option, ideally with some indicator like `no tables` included as well.
