### ISSUE TITLE
Custom Question Editor - Distinct rows instead of duplicated rows when user explore

### ISSUE THREAD

**Issue by dolphinxyz** [metabase/metabase#19794]
Ehy Guys,

I created a custom question using the custom editor, having multiple JOIN.

I have been able to select the columns relevant to me for each JOIN.

Now I want to allow users to drill into the data.

My problem is that the generated table has duplicated rows, I would love to have DISTINCT rows.

Is there a way for me to explicitly say that when a user explore the data only DISTINCT rows are displayed?

Many thanks.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
