### ISSUE TITLE
Getting `source cannot be null` error when connecting MongoDB

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#19797]
**Describe the bug**
When connecting local MongoDB (running in Docker), I get an HTTP 400 `source cannot be null` error after clicking "Save" (doing `POST /api/database`.

Not sure if it reproduces with other DBs (worked fine with SQLite). My guess it has something to do with the DB secrets feature ([see `source` usage in `models/datatabase.clj](https://github.com/metabase/metabase/blob/3f08385d72aa27ce49e08e48292b870d3a2a9889/src/metabase/models/database.clj#L113))

**Logs**

![CleanShot 2022-01-20 at 15 22 02@2x](https://user-images.githubusercontent.com/17258145/150347070-736a3797-0e53-40ef-b4f5-494acae150be.png)

**To Reproduce**

1. Spin up Mongo locally
2. Sign in as admin
3. Go to `/admin/databases/create`
4. Fill in basic info: DB name, host, port, DB user, and password
5. Click "Save"
6. `source cannot be null` message is displayed

**Expected behavior**
I can connect MongoDB

**Demo**

https://user-images.githubusercontent.com/17258145/150347341-53ea6474-8ad2-4894-b37b-909f84f811d8.mp4

**Information about your Metabase Installation:**

* running latest `master` ([commit](https://github.com/metabase/metabase/commit/3f08385d72aa27ce49e08e48292b870d3a2a9889))
* trying to connect sample MongoDB from [Metabase QA](https://hub.docker.com/r/metabase/qa-databases) database image

**Comment by jeff303** [comment]
@kulyk , which Docker image for MongoDB are you using?

**Comment by nemanjaglumac** [comment]
@jeff303 I believe Anton meant this one `metabase/qa-databases:mongo-sample-4.0` from https://github.com/metabase/metabase-qa

**Comment by jeff303** [comment]
Thanks, @nemanjaglumac .  I can repro using that one.

I think the underlying cause for the regression here was #19114, but I am still debugging it.

**Comment by nemanjaglumac** [comment]
@kulyk and @jeff303  taking a look at https://github.com/metabase/metabase/blob/b9d69a3cecd720d5d1f7e8b73d0c1ccfb27dbedf/frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js#L22

It's weird that you're able to connect at all without providing an `admin` to the Authentication Database o.O

Even more weird is that Anton succeeded in connecting with the DB name `metabse` when it should be `sample`.

**Comment by kulyk** [comment]
@flamber @nemanjaglumac it seems the issue has returned back. Can you please double-check you can reproduce the issue? I'm getting `source cannot be null` again when trying to connect Mongo

**Comment by flamber** [comment]
@kulyk Can you try in Incognito mode - without browser extensions (password manager)?
When I try with master from yesterday, then I don't get this error.

**Comment by kulyk** [comment]
@flamber weirdly is still doesn't work for me. I've tried Brave in incognito mode and Firefox without any extensions at all, and I'm still getting `source cannot be null`. Tried with the latest `master` at this point ([commit](https://github.com/metabase/metabase/commit/5fce46b3ff95959291d07b124420869620293341))

**Comment by flamber** [comment]
@kulyk Have you rebuild the drivers? I think you might have outdated drivers.
I'm testing with https://github.com/metabase/metabase/actions/runs/2039989184 OSS and it works.

https://user-images.githubusercontent.com/1447303/160124472-c45d3375-0d3d-44f3-85bf-1a9ddf60bd5b.mp4

**Comment by kulyk** [comment]
@flamber yahoo, rebuilding the mongo driver fixed it! Thank you for your help ❤️
