### ISSUE TITLE
`com.mysql.jdbc.PacketTooBigException` error when adding a MySQL database

### ISSUE THREAD

**Issue by tordans** [metabase/metabase#1980]
I try to connect to a bi database where we copy some data especially for bi and I get this error:
```
com.mysql.jdbc.PacketTooBigException: Packet for query is too large (4739923 > 1048576). You can change this value on the server by setting the max_allowed_packet' variable.
```

What is the reason for this exception?

**Comment by camsaul** [comment]
Are you putting files in your database?

http://stackoverflow.com/questions/11320236/com-mysql-jdbc-packettoobigexception

**Comment by tordans** [comment]
@camsaul no, its only numbers, dates and strings.

**Comment by camsaul** [comment]
But this issue is happening when you're putting data into your database? Before you connect it to Metabase?

**Comment by tordans** [comment]
Before connecting it. I am in the 'add database' interface.

**Comment by camsaul** [comment]
Ok, so you're going to "Add Database", then you enter your connection details, and then hit "Save", and that's when you're seeing the error?

**Comment by tordans** [comment]
@camsaul exactly 
<img width="984" alt="bildschirmfoto 2016-02-19 um 21 30 08" src="https://cloud.githubusercontent.com/assets/111561/13188157/fb599e1c-d74f-11e5-9e7e-3bf0bc5587c1.png">

**Comment by camsaul** [comment]
Ok, do you have access to the logs as well?

**Comment by tordans** [comment]
Not personally, I will have to check with my colleagues. I will get back to you.

**Comment by camsaul** [comment]
@tordans any update?

**Comment by tordans** [comment]
We did not manage to look into this yet, @camsaul but its still in our backlog. Probably next week. Will update here as soon as we know more.

**Comment by tordans** [comment]
@camsaul we looked into it and found out that that I used the wrong login information. With the right information the connection works fine. We have no idea why this error appeared but since its gone right now I will close the issue. Should we find it again, I will comment again.
Thanks for you help.
