### ISSUE TITLE
Data picker shows an infinite loader on instances without DBs

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#19809]
**Describe the bug**
Data picker shows an infinite loader on instances without DBs.

**To Reproduce**
1. Remove all databases from an instance
2. Click New -> Question
3. It shows an infinite loader

**Expected behavior**
It should suggest adding a database.

**Screenshots**
<img width="642" alt="Screenshot 2022-01-20 at 18 37 19" src="https://user-images.githubusercontent.com/14301985/150401057-75a96d31-e7d3-4540-b216-10cfd312a315.png">

**Information about your Metabase Installation:**
Latest `master`

**Comment by flamber** [comment]
@alxnddr I'm guessing it's related to #18977/#18978

**Comment by Pencab** [comment]
> **Describe the bug** Data picker shows an infinite loader on instances without DBs.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Remove all databases from an instance
> 2. Click New -> Question
> 3. It shows an infinite loader
> 
> **Expected behavior** It should suggest adding a database.
> 
> **Screenshots** <img alt="Screenshot 2022-01-20 at 18 37 19" width="642" src="https://user-images.githubusercontent.com/14301985/150401057-75a96d31-e7d3-4540-b216-10cfd312a315.png">
> 
> **Information about your Metabase Installation:** Latest `master`
