### ISSUE TITLE
Option to not colorize log output

### ISSUE THREAD

**Issue by jacktasia** [metabase/metabase#1982]
Logs with color codes can be problematic for some log aggregators with web views. Something like `MB_COLORIZE_LOGS` that defaults to `true` but can be changed to `false` via an environment variable.

I have this ready to PR if you'd like, but I saw in your development guide that you prefer to have an issue to discuss and ensure it's something you want first.

**Comment by camsaul** [comment]
@jacktasia Seems like it could be useful for certain cases, why don't you submit the PR so we can discuss the ramifications of it further?

**Comment by tlrobinson** [comment]
Ideally we should only colorize the output if we detect you're running it in an interactive shell.
