### ISSUE TITLE
Token has expired when export dashboard as file like xlsx/csv/json

### ISSUE THREAD

**Issue by ydhnwb** [metabase/metabase#19831]
Everytime I tap export xlsx/csv/json on chart either question or dashboard, the file will be failed to download.
On Android shows "Download Unsuccessful", it doesnt explain anything, So I take a look at metabase log, it shows:

```
"DEBUG metabase.server.middleware.log GET /api/embed/dashboard/......../dashcard/63/card/34/xlsx 400 807.1 µs (0 DB calls) 
"Token is expired (1642762215)" Token is expired (1642761371)"
```

I dont know why it happens, the token is sign every user open/request the chart, the chart is successful to show. But why only happen when export the dashboard/chart?

<img src="https://user-images.githubusercontent.com/26734262/150515512-f7b8be38-e381-4099-8691-b4f3ce46de32.png" alt="drawing" width="360" height="800"/>

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Then extend the token expiration, since clicking download makes an interaction after the visualization is shown, which might be after the expiration.
