### ISSUE TITLE
BigQuery some tables don't show Columns

### ISSUE THREAD

**Issue by Jonovono** [metabase/metabase#1984]
Hi. I just built from master and am trying to set up Bigquery.

Everything seemed to go fine, however only one of my tables show the columns with it.

Most of my tables have lot's of columns and the one that does show only has a couple. Is there a known issue with showing many columns?

The table is also fairly large. 800 000 + rows.

When I click "add filters to narrow answer' I just see one non clickable thing that is the same name as the data dropdown.

Thanks.

**Comment by tlrobinson** [comment]
@Jonovono did you mean to close this issue?

It's possible if you tried a query immediately after adding the database it hadn't finished syncing the metadata. Try reloading Metabase and see if it has more tables/columns now.

If not then can you reopen this issue? Thanks.

**Comment by mazameli** [comment]
@kdoh, this is a good reminder that we should provide some indication in the query builder, etc., that a database is still be synced.
