### ISSUE TITLE
Erreur à l'insertion d'un filtre sur une question personnalisée

### ISSUE THREAD

**Issue by harrysbeke** [metabase/metabase#19863]
**Describe the bug**
I can't insert a filter on a custom question. When I add this question in a dashboard, there is no more result on the question.

**Logs**
N/A

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85237530/150745597-611cc657-cc9b-4851-a917-6452b2a2c989.png)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_302-8u302-b08-1~deb9u1-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_302",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.302-b08",
    "os.name": "Linux",
    "os.version": "4.9.0-6-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.23"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.3",
      "date": "2020-08-04",
      "branch": "release-0.36.x",
      "hash": "a792f14"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @harrysbeke 
You should upgrade to latest release: https://github.com/metabase/metabase/releases/latest
And without exact steps-to-reproduce, then it's impossible to know what the problem could be.
