### ISSUE TITLE
Closing Drop-down in Join column selector causes non-drop-down columns to disapper

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19894]
To repro:

**To Reproduce**
1. Simple question > Sample Dataset > Products - summarize Count group by Category - save as "Q1"
2. Simple question > Sample Dataset > Products - summarize Sum of Price group by Category - save as "Q2"
3. Simple question > Sample Dataset > Products - summarize Average of Rating group by Category - save as "Q3"
4a. Custom question > Saved Questions > "Q1" - join "Q2" on Category
4b. Add another join against "Q3" on Category. When selecting the columns expand the `Question ___` dropdown. Other columns are no longer visible. Close the dropdown. No columns are visible at all.

![bye](https://user-images.githubusercontent.com/1455846/150880355-606ff3da-322e-42a0-b412-d5f728cdbff3.gif)

**Comment by flamber** [comment]
Related to #12930
