### ISSUE TITLE
Field Filters are always hidden for Questions using browser on mobile devices

### ISSUE THREAD

**Issue by dataedgeseattle** [metabase/metabase#19903]
On a mobile device Field Filters are always hidden in Questions using a browser. They are shown on dashboard, but are always hidden on questions for mobile view or when you resize any browser to under 400 px on a laptop or workstation the Field Filter will also become hidden. In addition, if you turn phone horizontally the Field Filter appears, but the graph is not resized correctly and has a height of near 0.

1. Click on any Question from a browser on a mobile phone and the Field Filter is hidden
2. if you turn mobile phone horizontally you can see the Field Filter again, but the graph is not resized correctly and the height goes to near 0

Expected behavior:
When you click on a Question with Field Filters in a browser on a mobile device you are able to see the Field Filters and use them  and if you turn phone horizontally the graph is resized for horizontal view on a mobile phone

Information about your Metabase Installation:
v0.41.2 on any mobile phone in any browser

**Comment by flamber** [comment]
Duplicate of #13726
I would strongly suggest that your upgrade immediately to latest release: https://github.com/metabase/metabase/releases/latest

**Comment by dataedgeseattle** [comment]
@flamber This is still a blaring bug in the latest release... I just pushed the latest version, questions aka cards do not display field filters (the custom dropdowns/search boxes you create in metabase) are hidden on mobile devices or when you resize any browser to under 400 pxx. I just pushed the latest release and this is still the case and when you turn mobile phone horizontally the graphs are resized incorrectly and the dropdown field filter reappears

**Comment by flamber** [comment]
@dataedgeseattle Issue #13726 is still open. The upgrade was for https://github.com/metabase/metabase/security/advisories/GHSA-vmm4-cwrm-38rj

**Comment by dataedgeseattle** [comment]
ok thank you @flamber sorry didn't see it was still opened
