### ISSUE TITLE
For Snowflake database, Metabase 0.41.6 shows server time and not UTC time

### ISSUE THREAD

**Issue by santosh-gorale** [metabase/metabase#19914]
**Describe the bug**
Select current_timestamp” from Snowflake returns current time in either Metabase server time zone or Metabase Reporting time zone if it is set up

**Expected behavior**
Metabase 0.41.6 should show UTC time instead of server time for Snowflake

**Additional context**
**The query** - "select current_timestamp"
**Returns** - Local Server Time. Not database UTC time

**Comment by flamber** [comment]
Duplicate of #8804
