### ISSUE TITLE
Data mismatch between custom question and raw sql query with Redshift 

### ISSUE THREAD

**Issue by pratik-fampay** [metabase/metabase#19910]
**Describe the bug**
Data mismatch when using Redshift custom Query VS Raw SQL query.

![Screenshot 2022-01-25 at 6 33 34 PM](https://user-images.githubusercontent.com/88657324/150981945-11a637d2-f690-440a-84b5-5e7c10dee0fa.png)

**Logs**
- Not needed

**To Reproduce**
1. Connect Redshift DB
2. Create table which has timestamp with timezone column 
3. Set time zone in settings to Asia/Culcutta
4. Ask question via Custom question, add date filter like date_created < "something"  and check count of rows
5. Convert same custom question to SQL query and execute 
![Screenshot 2022-01-25 at 6 41 18 PM](https://user-images.githubusercontent.com/88657324/150983003-b37c5b66-81ae-4aa7-b735-e77b6c3fe215.png)

6. Check count of rows, you will find mismatch 

**Expected behavior**
Ideally when we convert "Custom Question" to SQL query it should return same results. 

**Screenshots**

![Screenshot 2022-01-25 at 6 45 05 PM](https://user-images.githubusercontent.com/88657324/150983585-f997c06e-3a36-4b79-8a98-2c52d5ee6011.png)
![Screenshot 2022-01-25 at 6 45 43 PM](https://user-images.githubusercontent.com/88657324/150983749-e859a692-3c8e-4632-b6bc-f33e8baac472.png)

**Severity**
Annoying & Misleading, our analytics team can't rely on data when we query via Custom question.

**Additional context**
I tried debugging the problem found out due to certain reason default question makes query in GMT timezone but when we convert it to SQL question it has timezone data in it so it shows different but correct and expected data.

I tired setting timezone at user level and still it didn't work, because somehow queries made by custom question overrides that.  
```sql
ALTER USER dbuser SET timezone to 'America/New_York';
```

Also checked Metabase connector code, it seems its setting timezone there - [perm link](https://github.com/metabase/metabase/blob/912c76962808bdce4159263ce195a27620861f28/modules/drivers/redshift/src/metabase/driver/redshift.clj#L119)
```
(defmethod sql-jdbc.execute/set-timezone-sql :redshift
  [_]
  "SET TIMEZONE TO %s;")
```

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.252-131.483.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-16",
      "tag": "v0.41.5",
      "branch": "release-x.41.x",
      "hash": "fbfffc6"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
I guess it's related to #10824 and probably some other timezone issues. Not sure if this is specific to Redshift, don't think so.

Reproduced with CI Redshift on master - schema 187: Sample Dataset Orders - the CreatedAt column is timestamptz
Running a query in GUI produces 2 rows:
![image](https://user-images.githubusercontent.com/1447303/151010534-2451af95-cc87-469f-8cf4-18e640b74c9f.png)
Running the query in SQL produces 3 rows:
![image](https://user-images.githubusercontent.com/1447303/151010793-f2aa9647-8c39-45a9-afe2-e06b23e3e0ef.png)
```
SELECT "schema_187"."sample_dataset_orders"."id" AS "id", "schema_187"."sample_dataset_orders"."user_id" AS "user_id", "schema_187"."sample_dataset_orders"."product_id" AS "product_id", "schema_187"."sample_dataset_orders"."subtotal" AS "subtotal", "schema_187"."sample_dataset_orders"."tax" AS "tax", "schema_187"."sample_dataset_orders"."total" AS "total", "schema_187"."sample_dataset_orders"."discount" AS "discount", "schema_187"."sample_dataset_orders"."created_at" AS "created_at", "schema_187"."sample_dataset_orders"."quantity" AS "quantity"
FROM "schema_187"."sample_dataset_orders"
WHERE ("schema_187"."sample_dataset_orders"."created_at" >= timestamp with time zone '2016-06-21 00:00:00.000-07:00'
   AND "schema_187"."sample_dataset_orders"."created_at" < timestamp with time zone '2016-06-22 00:00:00.000-07:00')
ORDER BY "schema_187"."sample_dataset_orders"."created_at" ASC
LIMIT 1048575
```

**Comment by pratik-fampay** [comment]
@flamber We have same data stored in postgres as well and it works there as expected.

**Comment by flamber** [comment]
@pratik-fampay Timezones are tricky, and can hard to debug. There's a lot of different things in play, so it's strange that Postgres does not present this problem, since it does the same thing:
https://github.com/metabase/metabase/blob/master/src/metabase/driver/postgres.clj#L420-L422
Are you sure that all the column types and database timezones are the same between the Postgres and Redshift?

**Comment by pratik-fampay** [comment]
@flamber Yes, I am sure db column types and timezones are the same. 

Redshift Schema - via - [ddl](https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_tbl_ddl.sql)
```sql
date_joined TIMESTAMP WITH TIME ZONE   ENCODE az64
```
Postgres schema 
```sql
SELECT
   table_name,
   column_name,
   data_type
FROM
   information_schema.columns where table_name = 'core_user';
#####
 core_user  | date_joined            | timestamp with time zone
```

From [blog post](https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html)

> Go to the Admin Panel, select the Localization tab, and check the Report Time Zone setting, which controls the timezone Metabase uses when connecting to the database. This setting is currently supported on:

    Druid
    MySQL
    Oracle
    PostgreSQL
    Presto
    Vertica

Reshfit isn't mentioned here, can this be the reason it's using GMT always ?

**Comment by flamber** [comment]
@pratik-fampay Okay, I'll try to play around with Postgres too. Our docs are not fully updated. Think BigQuery now also supports timezones, but Redshift should support, when I look at the driver code.

**Comment by pratik-fampay** [comment]
Yes, both uses same SQL engine so it should work. 

I am trying to log queries made by Metabase and see what's the differences. I tried playing with log4j config but didn't have luck in making Metabase print Full SQL logs. 

So checked postgres logs found one difference at least with postgres db. When we use UI it seems Metabase is using SQL injection proof method to run query while for SQL it's as it is. 

Query argument is same in both query which means it should return same data. 

I want to test this for Redshift DB - I am pretty sure date arg would be different because that's the only logical reason for it to return different data. 

I can connect to Redshift DB via local tunnel but I can't check redshift logs like I did for postgres container. Can you help me make Metabase print SQL logs so I can verify that.

Query logs when using UI

```bash
postgres_1  | 2022-01-25 17:49:48.354 UTC [30] LOG:  execute <unnamed>: SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
postgres_1  | 2022-01-25 17:49:48.359 UTC [30] LOG:  execute <unnamed>: SET SESSION TIMEZONE TO 'Asia/Calcutta'
postgres_1  | 2022-01-25 17:49:48.381 UTC [30] LOG:  execute <unnamed>: BEGIN READ ONLY
postgres_1  | 2022-01-25 17:49:48.387 UTC [30] LOG:  execute <unnamed>/C_1: -- Metabase:: userID: 1 queryType: MBQL queryHash: 7261afc1b855f7f4bebc28fd8455716d954dc804436adede1808f04ef683d40b
postgres_1  | 	SELECT count(*) AS "count" FROM "public"."core_user" WHERE "public"."core_user"."date_joined" < $1
postgres_1  | 2022-01-25 17:49:48.387 UTC [30] DETAIL:  parameters: $1 = '2022-01-17 00:00:00+05:30'
```

Query logs when using RAW
```bash
postgres_1  | 2022-01-25 17:50:50.559 UTC [30] LOG:  execute <unnamed>: SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
postgres_1  | 2022-01-25 17:50:50.561 UTC [30] LOG:  execute <unnamed>: SET SESSION TIMEZONE TO 'Asia/Calcutta'
postgres_1  | 2022-01-25 17:50:50.565 UTC [30] LOG:  execute <unnamed>: BEGIN READ ONLY
postgres_1  | 2022-01-25 17:50:50.567 UTC [30] LOG:  execute <unnamed>/C_3: -- Metabase:: userID: 1 queryType: native queryHash: 6fdf16c832bdf15b5eece9ff16485744425e3efcb7fca860a686c6c7bdc3bab7
postgres_1  | 	SELECT count(*) AS "count"
postgres_1  | 	FROM "public"."core_user"
postgres_1  | 	WHERE "public"."core_user"."date_joined" < timestamp with time zone '2022-01-17 00:00:00.000+05:30'
```

**Comment by flamber** [comment]
@pratik-fampay Are you ready to drown in logs, then try this:
`-Dlog4j.configurationFile=https://log4j.us/v2/templates/metabase?trace=metabase.driver`

**Comment by pratik-fampay** [comment]
Drowned in logs and alive but disappointed.  

It seems its passing timezone aware date time string when we use UI query builder but they are returning different results postgres vs redshift. 

Good thing about this issue is it's easily reproducible, thank god for that.  

Doubt : When we execute raw SQL query why logger isn't printing them ?

Let me know what are your thoughts and how we can solve this. 

### Postgres

#### UI
```bash
metabase_1  | 2022-01-25 19:25:21,341 TRACE sql.query-processor ::
metabase_1  | HoneySQL Form: 🍯
metabase_1  | {:from ((hx/identifier :table "public" "core_user")),
metabase_1  |  :select ([:%count.* (hx/identifier :field-alias "count")]),
metabase_1  |  :where
metabase_1  |  [:<
metabase_1  |   (metabase.util.honeysql-extensions/with-type-info
metabase_1  |    (hx/identifier :field "public" "core_user" "date_joined")
metabase_1  |    {:metabase.util.honeysql-extensions/database-type "timestamptz"})
metabase_1  |   #t "2022-01-17T00:00+05:30[Asia/Calcutta]"]}
metabase_1  |
metabase_1  | 2022-01-25 19:25:21,343 TRACE sql-jdbc.execute :: Set transaction isolation level for postgres database to :read-uncommitted
metabase_1  | 2022-01-25 19:25:21,344 DEBUG sql-jdbc.execute :: Setting :postgres database timezone with statement: "SET SESSION TIMEZONE TO 'Asia/Calcutta';"
metabase_1  | 2022-01-25 19:25:21,346 TRACE sql-jdbc.execute :: Successfully set timezone for :postgres database to Asia/Calcutta
metabase_1  | 2022-01-25 19:25:21,346 TRACE sql-jdbc.execute :: Set param 1 -> #t "2022-01-17T00:00+05:30[Asia/Calcutta]"
metabase_1  | 2022-01-25 19:25:21,348 TRACE sql-jdbc.execute :: (set-object prepared-statement 1 ^java.time.OffsetDateTime #t "2022-01-17T00:00+05:30" java.sql.Types/TIMESTAMP_WITH_TIMEZONE)
metabase_1  | 2022-01-25 19:25:21,350 TRACE sql-jdbc.execute :: Column 1 'count' is a int8 which is mapped to base type :type/BigInteger for driver :postgres
metabase_1  |
metabase_1  | 2022-01-25 19:25:21,350 TRACE sql-jdbc.execute :: Reading :postgres column 1 "count" (JDBC type: BIGINT, DB type: int8) with metabase.driver.postgres$fn__56644$fn__56645@68915b53
metabase_1  | 2022-01-25 19:25:21,357 TRACE util.unprepare :: Splice #t "2022-01-17T00:00+05:30[Asia/Calcutta]" as "timestamp with time zone '2022-01-17 00:00:00.000+05:30'"
metabase_1  | 2022-01-25 19:25:21,358 TRACE util.unprepare :: Spliced "SELECT count(*) AS \"count\" FROM \"public\".\"core_user\" WHERE \"public\".\"core_user\".\"date_joined\" < ?"
metabase_1  | -> "SELECT count(*) AS \"count\" FROM \"public\".\"core_user\" WHERE \"public\".\"core_user\".\"date_joined\" < timestamp with time zone '2022-01-17 00:00:00.000+05:30'"
metabase_1  | 2022-01-25 19:25:21,374 DEBUG middleware.log :: POST /api/card/1/query 202 [ASYNC: completed] 89.7 ms (14 DB calls) App DB connections: 2/4 Jetty threads: 4/50 (2 idle, 0 queued) (59 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/2 (0 threads blocked)
```
#### Raw SQL
```bash
metabase_1  | 2022-01-25 19:24:17,245 TRACE parameters.values :: Building params map out of tags {} and params nil
metabase_1  | 2022-01-25 19:24:17,255 TRACE sql-jdbc.execute :: Set transaction isolation level for postgres database to :read-uncommitted
metabase_1  | 2022-01-25 19:24:17,256 DEBUG sql-jdbc.execute :: Setting :postgres database timezone with statement: "SET SESSION TIMEZONE TO 'Asia/Calcutta';"
metabase_1  | 2022-01-25 19:24:17,258 TRACE sql-jdbc.execute :: Successfully set timezone for :postgres database to Asia/Calcutta
metabase_1  | 2022-01-25 19:24:17,260 TRACE sql-jdbc.execute :: Column 1 'count' is a int8 which is mapped to base type :type/BigInteger for driver :postgres
metabase_1  |
metabase_1  | 2022-01-25 19:24:17,262 TRACE sql-jdbc.execute :: Reading :postgres column 1 "count" (JDBC type: BIGINT, DB type: int8) with metabase.driver.postgres$fn__56644$fn__56645@7a1137d2
metabase_1  | 2022-01-25 19:24:17,275 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 54.9 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 4/50 (2 idle, 0 queued) (57 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/2 (0 threads blocked)
```
### Redshift

#### UI
```bash
metabase_1  | 2022-01-25 20:37:23,821 TRACE sql.query-processor ::
metabase_1  | HoneySQL Form: 🍯
metabase_1  | {:from ((hx/identifier :table "REDACTED" "core_user")),
metabase_1  |  :select ([:%count.* (hx/identifier :field-alias "count")]),
metabase_1  |  :where
metabase_1  |  [:<
metabase_1  |   (metabase.util.honeysql-extensions/with-type-info
metabase_1  |    (hx/identifier :field "REDACTED" "core_user" "date_joined")
metabase_1  |    {:metabase.util.honeysql-extensions/database-type "timestamptz"})
metabase_1  |   #t "2022-01-23T00:00+05:30[Asia/Calcutta]"]}
metabase_1  |
metabase_1  | 2022-01-25 20:37:23,968 DEBUG sql-jdbc.execute :: Setting :redshift database timezone with statement: "SET TIMEZONE TO 'Asia/Calcutta';"
metabase_1  | 2022-01-25 20:37:24,229 TRACE sql-jdbc.execute :: Successfully set timezone for :redshift database to Asia/Calcutta
metabase_1  | 2022-01-25 20:37:24,297 TRACE sql-jdbc.execute :: Set param 1 -> #t "2022-01-23T00:00+05:30[Asia/Calcutta]"
metabase_1  | 2022-01-25 20:37:24,298 TRACE execute.legacy-impl :: (.setTimestamp 1 ^java.sql.Timestamp #inst "2022-01-23T00:00:00.000000000-00:00" <Asia/Calcutta Calendar>)
metabase_1  | 2022-01-25 20:37:24,421 TRACE sql-jdbc.execute :: Column 1 'count' is a int8 which is mapped to base type :type/BigInteger for driver :redshift
metabase_1  |
metabase_1  | 2022-01-25 20:37:24,424 TRACE sql-jdbc.execute :: Reading :redshift column 1 "count" (JDBC type: BIGINT, DB type: int8) with metabase.driver.postgres$fn__56644$fn__56645@3cf9c74c
metabase_1  | 2022-01-25 20:37:24,428 TRACE util.unprepare :: Splice #t "2022-01-23T00:00+05:30[Asia/Calcutta]" as "timestamp with time zone '2022-01-23 00:00:00.000+05:30'"
metabase_1  | 2022-01-25 20:37:24,428 TRACE util.unprepare :: Spliced "SELECT count(*) AS \"count\" FROM \"REDACTED\".\"core_user\" WHERE \"REDACTED\".\"core_user\".\"date_joined\" < ?"
metabase_1  | -> "SELECT count(*) AS \"count\" FROM \"REDACTED\".\"core_user\" WHERE \"REDACTED\".\"core_user\".\"date_joined\" < timestamp with time zone '2022-01-23 00:00:00.000+05:30'"
metabase_1  | 2022-01-25 20:37:24,499 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 710.7 ms (11 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (4 idle, 0 queued) (68 total active threads) Queries in flight: 0 (0 queued); redshift DB 3 connections: 0/2 (0 threads blocked)
```
#### Raw SQL
```bash
metabase_1  | 2022-01-25 20:38:46,224 DEBUG sql-jdbc.execute :: Setting :redshift database timezone with statement: "SET TIMEZONE TO 'Asia/Calcutta';"
metabase_1  | 2022-01-25 20:38:46,352 TRACE sql-jdbc.execute :: Successfully set timezone for :redshift database to Asia/Calcutta
metabase_1  | 2022-01-25 20:38:46,568 TRACE sql-jdbc.execute :: Column 1 'count' is a int8 which is mapped to base type :type/BigInteger for driver :redshift
metabase_1  |
metabase_1  | 2022-01-25 20:38:46,569 TRACE sql-jdbc.execute :: Reading :redshift column 1 "count" (JDBC type: BIGINT, DB type: int8) with metabase.driver.postgres$fn__56644$fn__56645@248a8576
metabase_1  | 2022-01-25 20:38:46,703 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 617.5 ms (4 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (71 total active threads) Queries in flight: 0 (0 queued); redshift DB 3 connections: 0/2 (0 threads blocked)
```

**Comment by flamber** [comment]
@pratik-fampay I would always use the query log from the database as source-of-truth compared to what the client says, since things might happen in the driver, which the client doesn't know about.

But I think the interesting part is:
```
# Postgres
metabase_1  | 2022-01-25 19:25:21,346 TRACE sql-jdbc.execute :: Set param 1 -> #t "2022-01-17T00:00+05:30[Asia/Calcutta]"
metabase_1  | 2022-01-25 19:25:21,348 TRACE sql-jdbc.execute :: (set-object prepared-statement 1 ^java.time.OffsetDateTime #t "2022-01-17T00:00+05:30" java.sql.Types/TIMESTAMP_WITH_TIMEZONE)
# Redshift
metabase_1  | 2022-01-25 20:37:24,297 TRACE sql-jdbc.execute :: Set param 1 -> #t "2022-01-23T00:00+05:30[Asia/Calcutta]"
metabase_1  | 2022-01-25 20:37:24,298 TRACE execute.legacy-impl :: (.setTimestamp 1 ^java.sql.Timestamp #inst "2022-01-23T00:00:00.000000000-00:00" <Asia/Calcutta Calendar>)
```
So perhaps the legacy implementation might be causing the problem. I don't understand the code well enough to tell.
I think the old Redshift driver might not originally have support java.time, but I think the newer versions does.

**Comment by pratik-fampay** [comment]
Hi @flamber 

This is quite shocking that we can't rely on logs what db query it's making coming from Python/Django world. 

How long does it take to fix such issue in most cases, do you have any number on mind ?

Can you think of quick fix / alternatives on that we can use that to avoid this problem ?

**Comment by pratik-fampay** [comment]
I was able to setup Metabase in local but this is my first time working in clojure or JVM based lang so any help would be appreciated fixing this issue.

**Comment by flamber** [comment]
@pratik-fampay You would have to try building the driver without `metabase.driver.sql-jdbc.execute.legacy-impl`, so it matches Postgres more. I don't know Clojure, nor if that is actually the right way to fix the problem.
As you can see there are more than 600+ other bugs, and 40+ timezone issues.

**Comment by pratik-fampay** [comment]
I have tested manually this [PR](https://github.com/metabase/metabase/pull/20023)

Wanted to wait for automated tests to run and see if any of them fails so I can fix code / test cases when I add new test case for this. I need to learn clojure for that I guess 😅  

```bash
2022-01-28 23:28:29,520 DEBUG sql.query-processor ::
HoneySQL Form: 🍯
{:from ((metabase.util.honeysql-extensions/identifier :table "REDACTED" "core_user")),
 :select ([:%count.* (metabase.util.honeysql-extensions/identifier :field-alias "count")]),
 :where
 [:<
  (metabase.util.honeysql-extensions/with-type-info
   (metabase.util.honeysql-extensions/identifier :field "REDACTED" "core_user" "date_joined")
   {:metabase.util.honeysql-extensions/database-type "timestamptz"})
  #t "2022-01-27T00:00+05:30[Asia/Kolkata]"]}

2022-01-28 23:28:30,408 TRACE sql-jdbc.execute :: Set param 1 -> #t "2022-01-27T00:00+05:30[Asia/Kolkata]"
2022-01-28 23:28:30,409 TRACE sql-jdbc.execute :: (set-object prepared-statement 1 ^java.time.OffsetDateTime #t "2022-01-27T00:00+05:30" java.sql.Types/TIMESTAMP_WITH_TIMEZONE)
2022-01-28 23:28:30,884 TRACE sql-jdbc.execute :: Column 1 'count' is a int8 which is mapped to base type :type/BigInteger for driver :redshift

2022-01-28 23:28:30,885 TRACE sql-jdbc.execute :: Reading :redshift column 1 "count" (JDBC type: BIGINT, DB type: int8) with metabase.driver.postgres$eval71056$fn__71057$fn__71058@742373cf
2022-01-28 23:28:30,887 TRACE util.unprepare :: Splice #t "2022-01-27T00:00+05:30[Asia/Kolkata]" as "timestamp with time zone '2022-01-27 00:00:00.000+05:30'"
2022-01-28 23:28:30,887 TRACE util.unprepare :: Spliced "SELECT count(*) AS \"count\" FROM \"REDACTED\".\"core_user\" WHERE \"REDACTED\".\"core_user\".\"date_joined\" < ?"
-> "SELECT count(*) AS \"count\" FROM \"REDACTED\".\"core_user\" WHERE \"REDACTED\".\"core_user\".\"date_joined\" < timestamp with time zone '2022-01-27 00:00:00.000+05:30'"
```

**Comment by felici1b** [comment]
Hello @pratik-fampay have you found any workaround? Do you use your PR in production?
Thx !

**Comment by pratikgajjar** [comment]
Hi, @felici1b Yes, we are using this PR in production 
```
docker pull fampay/metabase:v0.43.3-hotfix 
```
docker hub - [link](https://hub.docker.com/repository/docker/fampay/metabase/tags?page=1&ordering=last_updated)

**Comment by davidfromtandym** [comment]
I'm assuming the answer is no, but any way to get this fix into the Cloud hosted version of Metabase?

**Comment by pratikgajjar** [comment]
Hi, @davidfromtandym ; Need to write test cases and submit test results via running them locally with redshift. Both of them requires significant effort as I am not familiar with clojure and need to setup redshift in test org.

I can't promise but will try finish in next 2-3 weeks. That might make it easy for metabase team to merge and release. 
 
https://github.com/metabase/metabase/pull/20023#pullrequestreview-872299343

**Comment by techtangents** [comment]
Sorry to "me too", but it appears that I am affected by this issue as well. My use case is that I have Metabase locale set to Sydney time, and a "month" drop-down in a custom SQL query, filtering on a "datetime with time zone" field. The drop-down appears to filter in UTC time, rather than in Sydney time.

**Comment by Tony-metabase** [comment]
Adding this to P2 since if you are using a field filter into the Native Query you end up with similar behaviour

**Comment by Eliagandolfi** [comment]
@camsaul i still have the exact same issue when working with Postgres through Cube Cloud integration
