### ISSUE TITLE
Pie or donut charts summary option switch at open center

### ISSUE THREAD

**Issue by snycc15** [metabase/metabase#19936]
It is recommended to provide a central summary function configuration switch for visual plug-ins such as pie or donut charts
![a1](https://user-images.githubusercontent.com/67908124/151087925-0cb3171d-0b3a-47ef-9820-0d83d0aacef8.png)

**Comment by flamber** [comment]
Please stop creating new issues for something that I've already marked as duplicate #19656 #19904
