### ISSUE TITLE
Don't parse MB_DB_CONNECTION_URI

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19961]
Currently you can specify application DB connection details either with broken-out details or a single `MB_DB_CONNECTION_URI` with a JDBC connection string.

For purely historical reasons if you use `MB_DB_CONNECTION_URI` we attempt to parse it out into the broken-out details map which mostly works ok but doesn't work in every weird edge case which leads to a number of bugs/issues. I think we'd definitely be able to close out ALL of the following issues if we made this TINY change:

- https://github.com/metabase/metabase/issues/16106
- https://github.com/metabase/metabase/issues/9948
- #11414

Ones I think we can close out once this is in place:

- https://github.com/metabase/metabase/issues/9629 (if you can't connect using `MB_DB_CONNECTION_URI`, which we are no longer parsing, then it's out of our hands really, since we're passing that string directly to `java.sql.DriverManager/getConnection`. Something is wrong with either the connection string or the JDBC driver at that point.)
- https://github.com/metabase/metabase/issues/6622 (we should close as won't implement since you can use `MB_DB_CONNECTION_URI` to do this if you need it)

And possibly close out some of these issues as well:

- https://github.com/metabase/metabase/issues/6095 (I think we should close this as won't implement. If you want special things outside of what we offer with the split-out details, just use `MB_DB_CONNECTION_URI`)

Issues that would be easier to address in the future:

- https://github.com/metabase/metabase/issues/3852
- https://github.com/metabase/metabase/issues/5750

**Comment by dpsutton** [comment]
I went down this rabbit hole recent-ish. And I remember we ran into a blocker. Let me see if i can dig up that information so we can have that front and center when going into this

**Comment by camsaul** [comment]
Cool, thanks for this. I'm going to feed the connection URI directly into a `javax.sql.DataSource` so `clojure.java.jdbc` never even gets the chance to do something kooky with it

**Comment by camsaul** [comment]
@dpsutton RE URL-decoding parameters -- if we don't parse `MB_DB_CONNECTION_URI`, that's not something we need to be concerned with, right? That's the driver's responsibility, or not, right? i.e. either you pass us a working JDBC connection string or not, if it doesn't works we're not going to fix it for you

**Comment by camsaul** [comment]
I was thinking about this and the main use case we'd probably have for URL-decoding stuff anyway is for `password` so it would be easy enough to support `MB_DB_CONNECTION_URI` in combination with `MB_DB_PASS` and/or `MB_DB_USER` if that would be something that's useful. It closely mirrors what `java.sql.DriverManager` supports anyway

**Comment by camsaul** [comment]
RE URL-decoding things, AFAIK we don't need to do it. #14836 was the original issue, but it was only a problem because `clojure.java.jdbc` was parsing the connection string itself. Since we don't do that anymore it's not a problem anymore
