### ISSUE TITLE
Typo in src/metabase/models/permissions.clj

### ISSUE THREAD

**Issue by Dynnammo** [metabase/metabase#19977]
Doubled single quote in that sentence "Can''t use block permissions without having the advanced-permissions premium feature"

https://github.com/metabase/metabase/blob/efc6173f04a25cd0163949876977fc53a0a78fc1/src/metabase/models/permissions.clj#L867

**Comment by flamber** [comment]
Double single-quotes are needed for escaping, since it otherwise causes some strange problems. See #19971

**Comment by Dynnammo** [comment]
I should have checked issues before talking :man_facepalming:. Sorry for the trouble, have a nice day.
