### ISSUE TITLE
Horizontal scroll of pinned table doesn't work on Firefox

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#19997]
**Describe the bug**
If you pin a table in a collection, then try to click and drag the horizontal scrollbar in the table preview when using Firefox, it starts dragging the item rather than letting you scroll. Doesn't repro in Chrome; didn't test in other browsers.

**To Reproduce**
1. Open Metabase in Firefox
2. Create and save a card using a table visualization
3. Go to the collection the saved card is in and pin it
4. Click the horizontal scrollbar in the table preview and try to drag it

**Expected behavior**
Should scroll the table and not start dragging the card

**Screenshots**

https://user-images.githubusercontent.com/32746338/151423532-bdd35c89-b201-4639-a58e-ff1501cdb6cc.mov

**Information about your Metabase Installation:**

Current master, Firefox 96.0.2 on MacOS

**Comment by daltojohnso** [comment]
This will get fixed by https://github.com/metabase/metabase/pull/19966

https://user-images.githubusercontent.com/13057258/151618738-05b919f3-4c51-487f-9363-a8564ea94043.mov
