### ISSUE TITLE
When unchecking an item in a collection, icon briefly appears squashed

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#20008]
**Describe the bug**
When you check and then uncheck an item in a collection, the icon animation is such that it briefly appears "squashed", and then it snaps back to its normal state.

**To Reproduce**
1. Go to a collection with at least one item
2. Click the checkbox for an item
3. Click the checkbox again to uncheck it, then move your cursor away from the item

**Expected behavior**
Animation should look the same as if you hover over an item and then move your cursor away, without clicking the checkbox it.

**Screenshots**

https://user-images.githubusercontent.com/32746338/151484828-cac392be-9f9b-487e-9da9-bf708b3b0e14.mov

**Information about your Metabase Installation:**

Current master

**Comment by MatheusBeniniF** [comment]
Hey @flamber, i reproduced the steps and this is no more one issue
https://www.loom.com/share/55a06b019faf46a6863d1e385bebae5f
