### ISSUE TITLE
Changing viz settings will make serialization add another card on load

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20024]
**Describe the bug**
This was discussed here: https://github.com/metabase/metabase/pull/17388#issuecomment-900415001, but if you do a dump, load, then change the viz settings on the origin and dump and load again, the charts on the destination will not be replaced but rather added, as the visualization settings seem to be outside of the identity condition

**Logs**
NA

**To Reproduce**
With 2 Metabase instances, origin and destination:
1) create 2 cards on the origin and a dashboard
2) dump and load
3) go to the origin and change any viz setting in a card on the dashboard
4) dump and load with --update
5) you now get 3 cards on the destination

**Expected behavior**
Have only 2 cards, as the original card only had viz settings changed

**Screenshots**
Origin
![image](https://user-images.githubusercontent.com/1711649/151603762-69337451-b986-4f0f-b9e9-8935961c4817.png)

Destination
![image](https://user-images.githubusercontent.com/1711649/151603794-25717530-5e18-4bc6-a444-0429b3e704a1.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu
- Your databases: H2
- Metabase version: 1.41.5
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Low

**Additional context**
NA

**Comment by flamber** [comment]
Likely the same as #19762
