### ISSUE TITLE
Native editor resizer gets stuck and requires browser refresh to fix it

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20046]
**Describe the bug**
Native editor resizer gets stuck and requires browser refresh to fix it

**To Reproduce**
1. Native query > Sample Dataset
2. Change the size of the editor - it doesn't release
![image](https://user-images.githubusercontent.com/1447303/151660520-62779745-50a7-4a3d-a2a8-9e7070b2000c.png)

**Information about your Metabase Installation:**
Tested "rc2" commit `a29860c`

**Comment by nemanjaglumac** [comment]
This regression was introduced in https://github.com/metabase/metabase/pull/19774

https://github.com/metabase/metabase/blob/dd300077a8a7135ad195db6e9ebec456438c3668/frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx#L468
