### ISSUE TITLE
Database replication for performance improvement

### ISSUE THREAD

**Issue by brunolnetto** [metabase/metabase#20047]
**Is your feature request related to a problem? Please describe.**
An issue for some databases is its size. Oftentimes some necessary and basic queries like counting take more than the timeout of 60 seconds.

**Describe the solution you'd like**
After some research, I found the platform panoply.io, which allows the developer to replicate his database on Google database service BigQuery. It would be wonderful to Metabase to offer the same feature.

**Describe alternatives you've considered**
Only querying with filters is an alternative. No performance expectation is also an alternative. However, there must be some chunking and parallel processing techniques for situations like this.

**How important is this feature to you?**
Essential for system monitoring.

**Comment by flamber** [comment]
This is really not the functionality of Metabase. You would have to select the right database platform for your data.
Metabase will connect to that data as a client and make it possible for users to easily get answers about the data.

There's Audit functionality, which provides insights into query time: https://www.metabase.com/docs/latest/enterprise-guide/audit.html
