### ISSUE TITLE
Dashboard Subscription Displaying AM rather than PM

### ISSUE THREAD

**Issue by elliotnfi** [metabase/metabase#20073]
Dashboard subscription for 12:00 PM incorrectly displaying as 12:00 AM

**To Reproduce**
1. Go to a dashboard
2. Click on Sharing->Dashboard Subscriptions
3. Edit the posting time to 12:00 PM
4. See error: subscription shows as 12:00 AM **although it sends correctly.**

**Expected behavior**
Expect 12:00 PM, display shows 12:00 AM

**Screenshots**
![CleanShot 2022-01-31 at 13 11 06](https://user-images.githubusercontent.com/59617047/151857277-63123e35-52e2-49e3-b1ad-72c9d65f2117.gif)

**Information about your Metabase Installation:**

- Brave Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)
- Your operating system: macOS Monterey v 12.2
- Your databases: Postgres
- Metabase version: v0.38.0.1

**Severity**
How severe an issue is this bug to you? 
 - minor UI bug

**Comment by flamber** [comment]
@elliotnfi You should upgrade immediately to a newer release: https://github.com/metabase/metabase/releases/latest
But I cannot reproduce on latest release.

**Comment by elliotnfi** [comment]
@flamber will do, tyvm
