### ISSUE TITLE
Field filters with BigQuery when indexing multiple datasets are broken

### ISSUE THREAD

**Issue by avinashak** [metabase/metabase#20081]
**Describe the bug**
Applying field filters towards BigQuery tables in Metabase 0.42.0-rc1 include the BigQuery dataset name incorrectly when inserting the template values

**Logs**
From BigQuery

```
-- Metabase:: userID: 1 queryType: native queryHash: ff59b5d9491b6efdec50dde55d78f46652e69a04200c8c7d1491629468c83fb0
select count(*) from events.test_event where timestamp_trunc(`events.test_event`.`timestamp`, day) BETWEEN ? AND ?
```

**To Reproduce**
1. Connect a BigQuery data source 
2. Register multiple datasets to be scanned by Metabase
3. Insert a `Field Filter` 
4. See rendered SQL

**Expected behavior**

The `Field Filter` needs to correctly reference the variable it is templating. The immediate option that comes to mind is to not include the dataset name in the variable reference. 
e.g.
`select count(*) from events.test_event where timestamp_trunc(`test_event`.`timestamp`, day) BETWEEN ? AND ?` is a valid query 

**Screenshots**
not included

**Information about your Metabase Installation:**

Release 0.42-rc1

**Severity**
Blocking some users / impeding adoption of Metabase

**Comment by flamber** [comment]
Hi @avinashak 
It's working fine, when you enclose the from-clause in ticks, as also noted in the docs:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#some-databases-require-the-schema-in-the-from-clause

This fails:
```select * from v3_sample_dataset.products where {{cat}}```
While this works:
```select * from `v3_sample_dataset.products` where {{cat}}```
