### ISSUE TITLE
Models - can't unmap column from a database column

### ISSUE THREAD

**Issue by jeff-bruemmer** [metabase/metabase#20110]
**Describe the bug**
If you map a model column to a database column, you can map it to another db column, but you cannot unmap the column completely.

**To Reproduce**
1. Create a new question: `select * from orders`.
2. Turn that question into a model.
3. Map a column to a database model.
4. Try to unmap it.

![image](https://user-images.githubusercontent.com/17343328/152007334-9365aede-74ea-44c4-bb4d-cdbf42c1f1ab.png)

**Expected behavior**
You should be able to unmap (i.e., "cancel") the column mapping from any/all database columns.

**Severity**
Annoying. If you accidentally map a column to db column, the only way to remove that mapping is to turn the model back into a question and recreate the model from scratch.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.256-197.484.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "redshift",
      "druid",
      "googleanalytics",
      "bigquery-cloud-sdk",
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.22"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-01",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "ef9a0ac"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Comment by mazameli** [comment]
I think we can reuse our token kind of component here with the X to remove the selection. So clicking anywhere on this _except_ for the X would let you choose another column; and the x would clear the selection.

![image](https://user-images.githubusercontent.com/2223916/152264917-3c6624d8-f467-4568-8a40-401e3d450f37.png)
