### ISSUE TITLE
Fix `MB_DB_CONNECTION_URI` with format like `postgres://dan:password@localhost:5432/metabase`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20121]
Regression in `master` (43)
Regression of #14678

`postgres://dan:password@localhost:5432/metabase` isn't a valid JDBC connection string. Postgres wants `postgresql://localhost:5432/metabase?user=dan&password=password`. This used to work prior to #19970 when we parsed `MB_DB_CONNECTION_URI` but stopped working now that we no longer parse it (we do still however correct `postgres:` to `postgresql:`).

We should detect this one specific case and fix it with as little parsing as humanly possible. Since `java.sql.DriverManager` supports passing in `user` and `password` separately from the rest of the connection string (either as a pair of strings or inside a `java.util.Properties`) we should make sure we do that so we don't have to tack on `?user=` or `&user=`.

**Comment by dpsutton** [comment]
Ah good call on not trying to reformat it to include it as query params.
