### ISSUE TITLE
Recents list should not return archived items

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#20133]
**Describe the bug**
We should hide archived questions from recently viewed items to avoid user-facing errors

**To Reproduce**
1. Open any question
2. Archive it
3. Click on the search bar in the navigation

It shows the question and error after you click on it

**Expected behavior**
There is no the archived question

**Screenshots**
<img width="769" alt="Screenshot 2022-02-01 at 20 34 22" src="https://user-images.githubusercontent.com/14301985/152046749-9847822a-6e9a-4c99-a112-6b84b5d0dfe5.png">

**Version**
Latest master

**Comment by flamber** [comment]
It should show the "This question has been archived" page, so this seems to indicate a larger problem besides being listed in the search.

**Comment by noahmoss** [comment]
Just tried to repro this on master and wasn't able to. Any specific steps I'm missing? 🤔

**Comment by dpsutton** [comment]
I can repro this on master. Made a question visited it, archived it. put cursor in the search box, the archived question is the first item in the list. Click it and see
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/6377293/152381185-3274d71d-68cc-4fc1-890a-a2fac7a0772b.png">

But what I'm seeing is that on master any archived question presents this behavior. So maybe there are two distinct issues here:
- archived items should be in the recent list
- cannot view archived questions

Its not clear to me if the second one is actually an issue though. Perhaps that is a deliberate choice? I made a question in my personal collection, archived it, and then went to its url again and got the same behavior. Seems pretty deliberate.
