### ISSUE TITLE
Metabase offsetting yearly summary by one year using timestamp_trunc in big query

### ISSUE THREAD

**Issue by jjaves** [metabase/metabase#20144]
**Describe the bug**
When aggregating timestamp data into year from bigquery source, metabase returns the years offset by 1. 
I pulled the exact query from what metabase producde and put it directly into bigquery. 

Bigquery returned correct years.
![image](https://user-images.githubusercontent.com/17890441/152068276-80730a7c-ac18-4042-b084-1d62f2108bcc.png)

Metabase showing years offset by one
![image](https://user-images.githubusercontent.com/17890441/152068329-7d9ae568-c2e9-441d-a794-cc9daa9fb859.png)

**To Reproduce**
Using timestamp datetime in bigquery, use timestamp_trunc with year to aggregate and summarize values.

**Expected behavior**
Show years that align with data in the database.

**Screenshots**
See above

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Attempted on Chrome and Firefox
- Your operating system: macos 12 
- Your databases: google Big Query
- Metabase version: v0.41.4
- Metabase hosting environment: Heroku
- Metabase internal database: postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely? Very annoying. Reports are usable but users need to understand the underlying data to read correctly.

**Additional context**

**Comment by flamber** [comment]
Hi @jjaves 
Post "Diagnostic Info" from Admin > Troubleshooting, and your BigQuery connection settings.
That clearly looks like a timezone issue, it's not offset by a year, but by 8 hours.
Read this: https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html

**Comment by lukeman** [comment]
Looks like you just need to specify a timezone value (the tz that your Metabase instance is using) as a third argument to timestamp_trunc to get the localized timestamp of when the year started.

General MB+BigQuery advice: you'll want to be very explicit with timezones on all datetime parts, as there are other "nuances" with the BigQuery drivers like columns of the DATE type getting interpreted as a UTC midnight timestamp. Unless your reporting tz is set to UTC a straight group on day will leave your tables and viz dates off by one.
