### ISSUE TITLE
Trends don't post normally to the slack

### ISSUE THREAD

**Issue by podlyakov** [metabase/metabase#20157]
**Describe the bug**
I have made a simple dashboard with two trends on it. Made a subscription to slack - one time per day. But metabase post dashboard to slack without graphic, only text. It both happens with manually or automatically posting.
We tried new pre pre-release 0.42.0-rc1  also, because i have seen that you changed integration with slack.

**Expected behavior**
I expect to see the same pictures in slack, not text message.

**Screenshots**
How it looks in Metabase
![image](https://user-images.githubusercontent.com/15142348/152122243-c0da3d5d-b4dd-47ac-ac29-7cf9bc44e187.png)

How it looks in Slack
![image](https://user-images.githubusercontent.com/15142348/152122161-07eb9e3b-91fb-4a40-bd0b-d0957a1f5988.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome  97.0.4692.99
- Your databases: Oracle
- Metabase version:  v0.42.0-rc1
- Metabase hosting environment: Docker
- Metabase internal database:  Postgres 

**Severity**
We cannot use several dashbords :(

**Comment by flamber** [comment]
That's intended behavior for Number and Trend visualization.
