### ISSUE TITLE
"By coordinates" map in People X-ray shows a nonsensical pin map

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#20182]
**Describe the bug**
When you go to the X-ray for the People table in the Sample Database, it includes this map:
<img width="267" alt="Screen Shot 2022-02-02 at 10 46 13 AM" src="https://user-images.githubusercontent.com/32746338/152187707-4d5ecc10-2a8e-430d-a975-ab88dd460f14.png">

**To Reproduce**
1. Go to Browse Data -> Sample Database
2. Click on "X-ray this table" for the People table
3. Scroll down to "Where these People are"
4. See the "By coordinates" map

**Expected behavior**
I think this should either be a grid map, or it should be a pin map that's not binned  by latitude/longitude.

**Information about your Metabase Installation:**

Current master

**Comment by dpsutton** [comment]
Great catch.

the query it is coming up with is a strange one
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/6377293/152189054-37abfc60-d4c2-4ddc-9e58-c85ccf7f01b6.png">

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/6377293/152189089-38ef0492-3577-4c8c-b231-b9086e274edc.png">

**Comment by noahmoss** [comment]
@dpsutton Just ran `git bisect`; seems that this is also caused by #18912

**Comment by noahmoss** [comment]
Poked around a bit and discovered a couple of interesting things.
* This doesn't appear to be an X-ray issue. The query in the X-ray is the same before and after the commit that caused this; it's just the visualization of the query that has changed.
* When you zoom into the map, the pins migrate towards their correct locations.

**Comment by noahmoss** [comment]
Another discovery:
It doesn't seem that the `:fields` clause [here](https://github.com/metabase/metabase/blob/5196d0bf76af67653245d8aa32ebb749bc407821/src/metabase/api/tiles.clj#L161) is behaving correctly.

The rows in one example tile query are:
```
[[-106.6800018 44.4656923 1]
 [-106.673704 44.755191 1]
 [-106.662583 44.805811 1]
 [-106.5450203 43.7176676 1]
 [-106.4562194 43.7022358 1]
 [-106.2157111 44.5315223 1]
 [-105.634956 44.9507935 1]
 [-105.4554265 43.4571255 1]
 [-105.1429957 44.7139688 1]
 [-105.019411 43.153337 1]
 [-104.7325072 44.0269598 1]
 [-104.1529969 44.1185313 1]]
```

This indicates that the results are being returned as `[longitude, latitude, count]`, and not properly selecting just `[latitude, longitude]` as expected. This causes the lat and long coordinates to be swapped when the destructuring happens [here](https://github.com/metabase/metabase/blob/5196d0bf76af67653245d8aa32ebb749bc407821/src/metabase/api/tiles.clj#L79), thus causing the strange map.

**Comment by flamber** [comment]
Definitely multiple regressions going on
0.41.6
![image](https://user-images.githubusercontent.com/1447303/152334212-583aa61a-3ea9-4e71-a7a0-7acdacd28a1e.png)
"rc2" commit `a29860c`
![image](https://user-images.githubusercontent.com/1447303/152334270-d6d6404d-3d22-49e1-9c10-b3e4fbc88d4b.png)
master commit `e7c5dd7`
![image](https://user-images.githubusercontent.com/1447303/152334336-c56cfaf6-3b55-49df-8388-3a37372e5a4f.png)

**Comment by noahmoss** [comment]
@flamber 0.41.6 is showing what the map is supposed to look like. rc2 is issue #20090 which is now fixed on master (and the 42 branch).

**Comment by noahmoss** [comment]
@dpsutton Ok, finally root-caused this: the `:fields` clause is entirely stripped from the MBQL during the normalize step, since both fields are already specified in the `:breakout` clause. https://github.com/metabase/metabase/blob/a2f6076856b9d71f2ea326cc7f9a930258583152/shared/src/metabase/mbql/normalize.cljc#L715-L739

Not totally sure what the best fix for this is. Maybe continue passing the lat/long index info down from the frontend, but only use it to select the fields if the query contains `:breakout`? Not sure if this could be brittle in other cases. Or just determine the indexes of the lat/long fields in the result using info from `cols`? Might be the best approach, but then we're dealing with field ref comparison stuff again.
