### ISSUE TITLE
FullApp Embedding with SSO not working on Safari even with SameSite=None

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20196]
**Describe the bug**
When doing Full App Embedding in an iFrame, with SameSite=None, and JWT login will not work in Safari and iOS (as all browsers uses the Safari engine under the hood). Seems like Safari requires the use of Storage Access API.

**To Reproduce**
1. Metabase at `https://metabase.example.com` with embedding URL `https://app.example.com`
2. App at `https://app.example.com` with an iFrame
```
<iframe height="100%" width="100%" src="https://jwt.otherdomain.example?return_to=/">
```
3. JWT at `https://jwt.otherdomain.example`
4. Viewing 2) with the iFrame will cause infinite login loop. Viewing the iFrame src URL directly in the browser correctly logs in.
5. Start with environment variable `MB_SESSION_COOKIE_SAMESITE=None`
6. Viewing 2) with the iFrame will now work, but not in Safari.

**Additional context**
https://bugs.webkit.org/show_bug.cgi?id=198181

Originally EE590 https://github.com/metabase/metabase-enterprise/issues/590

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by paoliniluis** [comment]
We couldn't reproduce this again. @losrebellos can we remove all logic that captures Apple devices and tells that webkit is not supported from embedding-demo.metabase.com so we can test against that environment?

**Comment by paoliniluis** [comment]
To put context into this issue: the fact that doesn't work in Safari (or anything that uses webkit) is that Safari won't let cookies from 3rd party sites work on the browser. Moving Metabase and the embedding application to the same TLD should fix this

**Comment by paoliniluis** [comment]
For anyone that reads about this issue: confirmed that using the embedded application and the Metabase server under the same TLD will fix the issue

**Comment by paoliniluis** [comment]
@nllho we should add that to the documentation, if you use the samesite=none modifier it will work in non Safari/mac browsers and in different TLD's, but it you move both Metabase and the embedding app to the same TLD, everything will work without any modifier and in any browser :)

**Comment by bernardworthy** [comment]
@paoliniluis Does this mean that Safari embed support is not possible using the Cloud version of Metabase?

**Comment by paoliniluis** [comment]
@bernardworthy it is, but you need to move to Pro to set up Metabase with a custom domain so it's everything under the same domain

**Comment by albertoperdomo** [comment]
Just a note that it does work if “prevent cross-site tracking” option is disabled in Safari settings. Not suggesting that is a great implementation path since you probably can't control the browser settings of your end-users, but it does unblock working locally with Safari, e.g. for development.
