### ISSUE TITLE
Active state of notebook editor icon should be white inside blue box

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#20203]
This notebook icon should be white, not `text-dark`:

![image](https://user-images.githubusercontent.com/2223916/152264003-75e65f81-a2b8-4b57-8e1f-d6ddfc947146.png)

**Comment by mazameli** [comment]
@ranquild, do you think this could've been introduced in the header changes?

**Comment by kulyk** [comment]
Seems to be fixed 👍

**Comment by kulyk** [comment]
Seems to be fixed 👍
