### ISSUE TITLE
Pinning questions in a collection changes the "last edited at" datetime on that question, also that date displays incorrectly

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#20244]
**Describe the bug**
Just trying out the new question pinning format in collections for v0.42-rc2 (that's going to take some users by surprise and I couldn't find it in the release notes) and noticed that the "last edited at" datetime and user for the question gets updated when the question is pinned.

Also the date time shown on the update appears to be UTC not the local time.

**Logs**
Nothing of note

**To Reproduce**
1. Go to existing collection with existing questions (old "last edited at" date)
2. Note last edited datetime on question 
3. Click to pin the question
4. Visit that pinned question and note that the edited text now says something like "Edited a few seconds ago by you"
5. Back to collection
6. Click ellipsis on pinned question and unpin
7. Note the date of the question has been updated to today. Hover that date.
8. The date tooltip does not match the current local time (or the time of the change), it appears to be the UTC time of the change

**Expected behavior**
Pinning a question doesn't feel like you're editing it, just highlighting it from outside the question, I did not expect the modified date to change.

Whether or not pinning should change the modified date, I expected it to show that date correctly in my local time, not UTC.

**Screenshots**
Before pinning:
![image](https://user-images.githubusercontent.com/4504437/152463094-d99821d2-ab5f-4e0e-9ce3-ed62c77fa9ab.png)

After pinning (and unpinning):
![image](https://user-images.githubusercontent.com/4504437/152463142-7b34d449-f279-4c68-a58c-ecc3363fb9f6.png)

In the question:
![image](https://user-images.githubusercontent.com/4504437/152463595-8f8b3bdc-4c99-499c-b3b4-b69439b05b54.png)

Modified date doesn't match local time:
![image](https://user-images.githubusercontent.com/4504437/152463219-680d849e-4de8-443f-95ce-7b6ccd2d449f.png)
This was a few minutes after the pinning and I didn't notice immediately, ignore the minutes difference.

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "clickhouse",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-03",
      "tag": "v0.42.0-rc2",
      "branch": "release-x.42.x",
      "hash": "e119430"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Minor for me but if you're trying to monitor changes to question really closely this might generate extra noise.

**Additional context**
Exists in both v0.41.6 and v0.42-rc2.

Running Metabase locally, server is in same timezone as browser.

**Comment by flamber** [comment]
Hi @notrom 
We probably shouldn't update the card on (un)pinning, but might be slightly more complicated, since it's a `PUT /api/card/:id` request.

Timezone - I cannot reproduce, but something makes me think that your date formatting might be old, so can you go and try to re-set everything in Admin > Settings > Localization?

PS - please change Java to either 11 or 17, 13 is EOL: https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Comment by notrom** [comment]
@flamber I setup a new vanilla install of v0.42.0-rc2 and the display of the last edited date is using the correct timezone and showing local time. So it looks like it is related to my settings/instance.

On my existing Metabase testing instance, manually resetting the settings in Admin > Settings > Localization seems to have no impact on the display timezone (but the format changed as expected), it's still showing the wrong timezone. Restarted Metabase, still no change.

Thanks for the Java reminder.

**Comment by flamber** [comment]
@notrom Hmmm... interesting. Can you include your original data from `"setting"."key"='custom-formatting'` - I'm quite sure the problem is somewhere there.

**Comment by notrom** [comment]
On the instance that's having the issue (i.e. not the vanilla one):
```
{
   "type/Currency":{
      "currency":"USD"
   },
   "type/DateTime":{
      "time_style":"k:mm",
      "date_abbreviate":true,
      "date_style":"D/M/YYYY"
   },
   "type/Temporal":{
      "date_separator":"/",
      "date_style":"MMMM D, YYYY"
   },
   "type/Number":{
      "number_separators":".,"
   }
}
```

**Comment by flamber** [comment]
@notrom Okay, so the problem comes the duplicate settings `type/DateTime` and `type/Temporal`.
`type/DateTime` seems to be old style, while `type/Temporal` is the new style. Perhaps half legacy from #9538
So if you manually go an change all the settings in Admin > Settings > Localization from something different and then back to what you want, then it should work correctly.
