### ISSUE TITLE
Databases shows sync-spinner and doesn't allow to remove it or do a forced sync

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20283]
**Describe the bug**
Databases shows sync-spinner and doesn't allow to remove it or do a forced sync.

**To Reproduce**
1. Setup a database on source
2. Do Serialization dump+load
3. On the target, it will show forever sync-spinner even though everything is working correctly
![image](https://user-images.githubusercontent.com/1447303/152678049-4691e530-5381-4264-9dd4-0ccffd496673.png)
![image](https://user-images.githubusercontent.com/1447303/152678083-b71979a7-eaf7-4530-a51c-468c2dbc81e8.png)
![image](https://user-images.githubusercontent.com/1447303/152678067-203700e4-7d32-4224-9c21-012dc4f7c23a.png)

**Expected behavior**
It should not remove the sync buttons, or at least allow removal of the sync-spinner.
I'm sure that this problem exists outside of Serialization universe.

**Information about your Metabase Installation:**
1.42.0-rc2

**Comment by noahmoss** [comment]
I don't know much about serialization, but maybe this is because the DB wasn't done syncing when the dump was created. So `initial_sync_status` is stuck at `incomplete` until the next sync occurs.

@flamber do you know if this happens for databases that have totally finished their first sync prior to serialization?

**Comment by flamber** [comment]
@noahmoss It's really not a Serialization issue. It's a frontend issue that I'm not able to stop this spinner, nor trigger another sync again if something failed (or there isn't any initial_sync_status data).

**Comment by noahmoss** [comment]
I see. cc @cdeweyx @ranquild

I agree that we should allow the ability to kick off a new sync if we get stuck in a bad state like this, rather than disabling the sync button entirely.

**Comment by daltojohnso** [comment]
I'm not super familiar with this stuff, but is the solution here simply to show the "Sync database schema now" button regardless of sync status?
