### ISSUE TITLE
Data Point values not always shown depending on viz size and number of series

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20290]
**Describe the bug**
When there's a lot of series, or the visualization is small width, then not all data points are shown if there isn't enough room within a bar.

**Reproduce 1**
1. Native query > Sample Dataset
```
select 'a' c1, 'a' c2, 40 c3
union all select 'a', 'b', 60
union all select 'a', 'c', 100
union all select 'a', 'e', 200
union all select 'b', 'a', 400
union all select 'b', 'b', 600
union all select 'b', 'c', 100
union all select 'c', 'a', 400
union all select 'c', 'b', 600
union all select 'c', 'c', 100
union all select 'd', 'a', 400
union all select 'd', 'b', 600
union all select 'd', 'c', 100
union all select 'e', 'a', 400
union all select 'e', 'b', 600
union all select 'e', 'c', 100
union all select 'e', 'd', 90
union all select 'e', 'e', 80
union all select 'e', 'f', 70
```
2. Change to Bar visualization, with X-axis C1 and C2, Y-axis C3 - enable "Show values on data points" (doesn't matter if "All" is selected)
![image](https://user-images.githubusercontent.com/1447303/152834108-ad1d8a80-7fca-40ed-ae98-4a7f6f580d15.png)
3. Closing the sidebar or removing the entire "e" series of C1 will show all the data points above the bars
![image](https://user-images.githubusercontent.com/1447303/152834199-e38d5518-1007-419e-9e4b-aed351f6b047.png)

**Reproduce 2**
1. Native query > Sample Dataset
```
select r1.x::float/5 as c1, case when (r2.x=1) then 'A' when (r2.x=2) then 'B' else null end as c2, case when (r1.x=3 and r2.x=1) then 12 when (r1.x=6 and r2.x=1) then 100 when (r1.x=6 and r2.x=2) then 110 else null end c3
from system_range(1, 50) r1, system_range(1, 2) r2
```
2. Change to Bar visualization, with X-axis C1 and C2, Y-axis C3 - enable "Show values on data points" and "Values to show"=All
![image](https://user-images.githubusercontent.com/1447303/162969546-8fbd1972-912a-489a-8668-8a45b89898e5.png)
3. Changing Axes > X-axis scale to Ordinal or Histogram makes the data point values slightly more readable
![image](https://user-images.githubusercontent.com/1447303/162970050-56b3c3ce-a816-4df2-934c-1501b746572f.png)

**Expected behavior**
When there isn't enough space within, then it should likely show the data point above, when "All" is defined.
Also, the look is so different between the black-above and the white-rotated-within.

**Information about your Metabase Installation:**
Tested 0.38.4 thru 0.42.4

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/41395
