### ISSUE TITLE
Waterfall static viz default settings

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#20332]
- When waterfall colors didn't set explicitly it renders bars black
- When waterfall "show total" didn't set explicitly it does not show the "Total" bar

<img width="695" alt="Screenshot 2022-02-08 at 16 24 13" src="https://user-images.githubusercontent.com/14301985/153031995-42c836b6-1b72-444e-b8f5-6d8f46f6e4fb.png">

**Comment by rlotun** [comment]
fixed by: https://github.com/metabase/metabase/pull/20334
