### ISSUE TITLE
Date values in queries are not being interpreted in the appropriate timezone (clojure jdbc)

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2035]
database is `all` (i think, could be driver specific), Metabase version is `0.15.0`

When using the report timezone in the database to get date values (e.g. grouping by day) the values that are returned are not being interpreted in the report timezone and instead are interpreted using the Metabase instances local timezone.

To reproduce: Set the report timezone to `Asia/Tokyo` and run the following query (on postgres) `select * from (values (timestamp with time zone '1999-01-08 11:05:06 -8:00', (timestamp with time zone '1999-01-08 11:05:06 -8:00'::date)))`  The resulting value in column 2, which is just a date, is `"1999-01-09T08:00:00.000Z"` (note that my Metabase instance is running in US/Pacific).  The proper value should be `"1999-01-09T00:00:00.000+0900"` which represents the start of the following day in the `Asia/Tokyo` timezone.

From a bit of digging I believe the reason the value is incorrect in this situation, which is specific to Date handling vs Timestamps, is because either the date value coming back from the database doesn't contain the proper timezone information or the database driver is improperly interpreting the date and ignoring the timezone.  The end result is that the database returns a value such as `1999-01-09` and the application has no idea what timezone to interpret it as, so it defaults to using the local timezone set when the Java application launches, which in my case is US/Pacific.  So the value of `"1999-01-09T08:00:00.000Z"` is indicative of the start of the 9th in US/Pacific time formatted in UTC.  The problem is that's not correct and what was actually returned was the start of the 9th in Asia/Tokyo :scream:

**Comment by camsaul** [comment]
This definitely can't apply to all databases since all databases don't support timezones. Looks like you're using postgres though?

**Comment by agilliland** [comment]
Correct.  This specific example is from Postgres and I agree, if a database clearly doesn't have any support for timezones then it's not subject to this specific issue.  It'll be a PITA, but we'll need to go through each database and test this out.

**Comment by maliayas** [comment]
Don't know if the same issue but I have this bug:

If I group by `created_at: hour of the day`, returned hour is in correct timezone but the same query groupped by `created_at: hour` the returned hours are added 2 more hours. I live in +02:00 and set Metabase to Europe/Athens. Also I'm using the H2 database for Metabase v0.15.0.

**Comment by manurana** [comment]
I can verify what @maliayas is seeing. Using v0.16.0. Data DB is mySQL

**Comment by agilliland** [comment]
@maliayas we made a couple updates to the timezone handling in 0.16.0 so I'd be curious if anything changes for you after upgrading.

@manurana can you provide some more details about your example?  i'd be curious to know what timezone you set Metabase to use, what timezone your computer is running in (that's running Metabase), and what timezone settings are applied on your database.

**Comment by manurana** [comment]
Hi @agilliland : Metabase is running on a EC2 with UTC. I am in IST (+5.30). Metabase is set to use India/Calcutta as the timezone. The mySQL DB is on UTC.

Here are some screenshots to show whats happening. Should be self explanatory. The first image is when you are grouping by Date+Hour. This is the correct result. The second is when you are grouping by Hour Of Day. The second shows a clear 5.30 hour difference in the results.

Interestingly, the grouping numbers are correct, even with the 30 min diff in zones. It seems that just the display needs to be adjusted.

![image](https://cloud.githubusercontent.com/assets/1749522/14165459/bfe8eddc-f726-11e5-8ed2-b62d4b50edc4.png)

![image](https://cloud.githubusercontent.com/assets/1749522/14165487/0848924e-f727-11e5-8e9f-de5fc18cb46c.png)

**Comment by manurana** [comment]
Apologies. There is more to this. I am attaching another set of images which shows that the data is not being grouped according to the exact time zone

Here is the equivalent query that needs to be run

`select HOUR(convert_tz(appointment_dt,"+00:00","+05:30")) AS `Hour of the day`, 
count(1) as total_trips
from appointment
WHERE ((DATE(convert_tz(appointment_dt,"+00:00","+05:30")) = DATE(NOW()))
AND (`appointment`.`status` IN (9)))
GROUP BY HOUR(convert_tz(appointment_dt,"+00:00","+05:30"))
ORDER BY HOUR(convert_tz(appointment_dt,"+00:00","+05:30")) ASC`

This is the result it gives

![image](https://cloud.githubusercontent.com/assets/1749522/14165690/5a23cabe-f729-11e5-89af-3cf8b84a832d.png)

Now this is what the MB questions are showing
Note the discrepancy in numbers between the actual query and both the MB questions

![image](https://cloud.githubusercontent.com/assets/1749522/14165713/80caef44-f729-11e5-950f-b560b0093e4e.png)

![image](https://cloud.githubusercontent.com/assets/1749522/14165718/8bf7545c-f729-11e5-82b9-b8d4a4784915.png)

**Comment by hden** [comment]
Here is a short list of possible solution for some of the supported databases:
* MySQL [CONVERT_TZ()](http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_convert-tz)
* PostgreSQL [AT TIME ZONE](http://www.postgresql.org/docs/current/static/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT)
* Redshift [CONVERT_TIMEZONE()](http://docs.aws.amazon.com/redshift/latest/dg/CONVERT_TIMEZONE.html)
* BigQuery [FORMAT_TIMESTAMP()](https://cloud.google.com/bigquery/sql-reference/functions-and-operators#format-functions)

**Comment by key88sf** [comment]
I'm seeing the same issue using group by hour of day as well (on Postgres). It's displaying the hours in UTC instead of the reporting timezone of EST.

**Comment by jongyonkim** [comment]
I'm having similar issues with the line chart x-axis timestamp/timezone labels

- My data is in ```UTC``` in Redshift
- Metabase (v0.17.1) setting is ```Database Default```
- In my SQL query I apply ```CONVERT_TIMEZONE()``` to convert ```t_stamp``` from ```UTC``` to ```PST```

If I hover my mouse cursor over the data, it shows converted ```PST``` timezone, but the x-axis of the line chart is 7 hours _behind_ (which is weird, because if x-axis stayed at ```UTC``` it should actually indicate 7 hours _ahead_...). See attachment:
![metabase timestamp issue](https://cloud.githubusercontent.com/assets/8485196/16132988/773c570a-33ca-11e6-8c91-5e0b06abc62e.png)

The x-axis should follow what the data indicates (```PST```).

**Comment by pdiniz13** [comment]
We're getting a similar issue where if a table is saved datetime in MYSQL then metabase is failing to treat it as timezone utc.

**Comment by senior** [comment]
This issue should now be resolved, it was fixed in https://github.com/metabase/metabase/pull/5729 and released with 0.26 RC1. More information can be found on the [0.26.RC1 release page](https://github.com/metabase/metabase/releases/tag/v0.26.0.RC1). Would be great to get some validation on the fix if anyone is still experiencing the problem.
