### ISSUE TITLE
Migrated dashboards with "locked" parameters can't be changed

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20360]
**Describe the bug**
If you upgrade from any version to 42, any dashboard with locked parameters can't be changed as https://github.com/metabase/metabase/issues/20357, so the only option is to recreate the dashboard

**Logs**
Same logs as https://github.com/metabase/metabase/issues/20357

**To Reproduce**
1) Create a dashboard with a question in 41.6 and lock a parameter
2) move to 42
3) try to change the config of the embedded dashboard

**Expected behavior**
Change the config of the embedding

**Screenshots**
![Peek 2022-02-08 23-11](https://user-images.githubusercontent.com/1711649/153108673-a2a74b12-1870-4c5e-b063-fe510d296ca4.gif)

**Information about your Metabase Installation:**
Same as https://github.com/metabase/metabase/issues/20357

**Severity**
Severe

**Additional context**
NA

**Comment by flamber** [comment]
Same problem as #20357
