### ISSUE TITLE
Question drops the groupings and custom metrics upon Save

### ISSUE THREAD

**Issue by thomasantonakis** [metabase/metabase#20368]
**Describe the bug**
Saving a custom Question drops the groupings and custom metrics

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

[20a5a07b-0e0d-4a0a-bac3-cae5510bd53d] 2022-02-09T14:32:45+02:00 INFO metabase.api.card Card results metadata passed in to API is MISSING. Running query to fetch correct metadata.
[20a5a07b-0e0d-4a0a-bac3-cae5510bd53d] 2022-02-09T14:32:45+02:00 DEBUG metabase.server.middleware.log POST /api/card 202 [ASYNC: completed] 104.9 ms (27 DB calls) App DB connections: 5/13 Jetty threads: 4/50 (2 idle, 0 queued) (94 total active threads) Queries in flight: 0 (0 queued)
[20a5a07b-0e0d-4a0a-bac3-cae5510bd53d] 2022-02-09T14:32:55+02:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 5.9 ms (1 DB calls) App DB connections: 1/13 Jetty threads: 5/50 (3 idle, 0 queued) (92 total active threads) Queries in flight: 0 (0 queued)

**To Reproduce**
1. Go to Create a new Question 
2. Select Custom Question
3. Select, Database and primary table
4. Click on Join and select the second table, join type and join clause
5. Add as a metric a custom Aggregation using Sum on a numeric field of the secondary table
6. Add as grouppings two categorical fields of the primary table
7. Click on Save Question add name and click OK/Save

**Expected behavior**
Custom metrics and Groups should remain, but they do not.

**Screenshots**
Before saving
![image](https://user-images.githubusercontent.com/7755542/153203032-30d16126-8660-4bcd-93b0-6cd022fb007a.png)
After Saving
![image](https://user-images.githubusercontent.com/7755542/153203147-287dc49f-c545-4c8e-abd7-34153ee1a675.png)
Console logs
![image](https://user-images.githubusercontent.com/7755542/153202425-ffe427ab-abc7-4ad8-8446-8c39ddec6313.png)

**Severity**
Using the no-code question editor is one of the main perks of using Metabase, This is blocking users from using Metabase

**Additional context**
I cannot reproduce this in the Sample Database, I fear this may be something that relates to the DataModel information

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_312-heroku-b05",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_312-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.312-b05",
    "os.name": "Linux",
    "os.version": "4.4.0-1097-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.5 (Ubuntu 13.5-2.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.41.2",
      "date": "2021-11-09",
      "branch": "release-x.41.x",
      "hash": "ad599fd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
You should upgrade immediately to a newer release: https://github.com/metabase/metabase/releases
Why are you using a Custom Expression instead of just using the basic metric Sum - something tells me that the problem is somewhere related to that, which could likely be caused by incorrect Data Model or wrong column types, so you'll need to look into that, but it's not possible to reproduce with the steps that you provide, since it requires your data/setup.
