### ISSUE TITLE
Crappy dashboard card error message 💩

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2036]
This error message on my dashboard card sucks because, A) it doesn’t give me the saved question title so I can’t click through and investigate what’s happening and B) what’s actually going on with this question is that it has 0 rows in the result, so it’s actually a misleading/wrong error message.

![screen shot 2016-02-26 at 10 11 19 am](https://cloud.githubusercontent.com/assets/2223916/13361176/fc3f9b8e-dc71-11e5-8aaf-4fea3ebe5118.png)

**Comment by mazameli** [comment]
I would expect something more like this:

![dashboard-no-results](https://cloud.githubusercontent.com/assets/2223916/13361285/97fbe064-dc72-11e5-8a0c-f62069a9eb92.png)

**Comment by jadedevincabatlao** [comment]
+1

**Comment by robinfrick** [comment]
+1

**Comment by MrMauricioLeite** [comment]
+1
