### ISSUE TITLE
Field filters limited to 2 (filters 3+ disappear from filter selection)

### ISSUE THREAD

**Issue by ewenra** [metabase/metabase#20378]
**Describe the bug**
Filters on new queries are currently limited at 2. Anything over 2 breaks and is removed from the filter bar. You can still add date or text filters, but field filters are broken.

**To Reproduce**
1. Write a native query
2. Add 5 filters

**Severity**
This is extremely limiting functionality to a fundamental feature of the platform.

**Comment by flamber** [comment]
I cannot reproduce, but try the latest release: https://github.com/metabase/metabase/releases/latest
Otherwise provide more detailed information and screenshots, as well as "Diagnostic Info" from Admin > Troubleshooting.

**Comment by ewenra** [comment]
@flamber We're on the latest. This is a bug in the new version.

Screenshot:
<img width="1236" alt="Screen Shot 2022-02-09 at 11 13 32 AM" src="https://user-images.githubusercontent.com/77791446/153253763-9f1822ed-0a5f-492a-847d-52939cb81ffd.png">


Diagnostic info:

`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.252-195.483.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-01-10",
      "tag": "v0.41.6",
      "branch": "release-x.41.x",
      "hash": "296635f"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}`

**Comment by flamber** [comment]
@ewenra Latest release is 0.42.0, but never mind that.

Your screenshot does not show enough information. What exactly is the problem? How does it manifest? How to reproduce?

Since you say it's bug in 0.41.6, then I guess it's not a bug in 0.41.5 - or maybe you upgraded from a different version, again, it's hard to tell, when you don't provide enough information.

**Comment by ewenra** [comment]
The problem is that there are 3 field filters, and only 2 display. The 3rd field filter will not display as an option at the top of the query. If you need more information, please ask for it specifically.

**Comment by ewenra** [comment]
More specifically, in the screenshot, "Market" is not visible as a filter option even though it has been mapped to a field and should be displaying. This occurs in all newly written queries and is not specific to a single database.

**Comment by ewenra** [comment]
<img width="1502" alt="Screen Shot 2022-02-09 at 2 01 44 PM" src="https://user-images.githubusercontent.com/77791446/153280898-1d844c7c-0681-40df-9835-4109763409aa.png">
