### ISSUE TITLE
Add / remove bookmarks for Questions and Models

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#20388]
Ensure we are hydrating Questions and Models with the `bookmark` status.

**Comment by adam-james-v** [comment]
This can be done with
`POST/DELETE /api/bookmark/:item_type/:item_id`

For example, if you have a card with id 25, you can create a bookmark for it using:
`POST /api/bookmark/card/25`

**Comment by dpsutton** [comment]
I'm also torn about this. I'm of the opinion we should not hydrate collections/cards/dashboards with the bookmark info and just have the frontend consult the user's bookmarks in memory for this state.

**Comment by gusaiani** [comment]
> I'm also torn about this. I'm of the opinion we should not hydrate collections/cards/dashboards with the bookmark info and just have the frontend consult the user's bookmarks in memory for this state.

Ok, great. That's not how I've been going about it but I'll change the approach.
