### ISSUE TITLE
Update code for favoriting Dashboards to use the verb `bookmark`

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#20386]
As we implement bookmarking, and since we already have endpoints, documentation and the like for adding and removing `favorite`s, let's update the verb to `bookmark` in the context of Dashboards.

[Our API documentation](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md) has references to POST and DELETE actions for it.

Ensure we are hydrating Dashboards with the bookmark status.

**Comment by adam-james-v** [comment]
Handled in #20790 

Brief NOTE:
There is no verb for bookmark on `/api/dashboard/:id`
Instead, to add/remove dashboard bookmarks, use:

`POST/DELETE /api/bookmark/dashboard/:dashboard_id`
