### ISSUE TITLE
Update logic for favoriting Cards to say `bookmark`

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#20384]
As we implement bookmarks for other entities, let's take the opportunity to remove logic, endpoints and documentation for favoriting cards. 

[Our API documentation](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md) has references to POST and DELETE actions for it.

**Comment by adam-james-v** [comment]
NOTE: will handle documentation changes elsewhere. Adding as a TODO to the epic.

Handled in #20790 

Brief NOTE:
There is no verb for bookmark (or favorite) on `/api/card/:id`
Instead, to add/remove card bookmarks, use:

`POST/DELETE /api/bookmark/card/:card_id`
