### ISSUE TITLE
Error when filter list of values in metamodel

### ISSUE THREAD

**Issue by Olga-par** [metabase/metabase#20392]
Hello!

We have used metabase version v0.41.6 Built on 2022-01-10.
We created metamodel in this metabase and filtered list of values. 
![image](https://user-images.githubusercontent.com/75472069/153281561-e6d2dd78-be32-4ec4-98fb-a8e7c5e4c757.png)
We got error.
![image](https://user-images.githubusercontent.com/75472069/153281746-2b9fbc2a-a0c1-4ed0-8e7d-f0817d3f3b2e.png)

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
