### ISSUE TITLE
Using search in "Add series" on dashboard can be slow on big instances

### ISSUE THREAD

**Issue by szsuyuji** [metabase/metabase#20408]
![image](https://user-images.githubusercontent.com/1931764/153317975-d32c8b50-85e2-4756-b540-fef816bdc00f.png)

the list loading is very slowly ,browser page would lost response

metabase version 0.42.0

**Comment by flamber** [comment]
@szsuyuji
1. Post "Diagnostic Info" from Admin > Troubleshooting
2. Provide more details, when you open an issue - there's a reason why we have a template
3. Provide logs - depending on the issue - either Metabase or browser console

There's already been work in this area to limit performance problems #13100
