### ISSUE TITLE
Really high-number IDs getting interpreted as unix timestamps

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2041]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac [Dre].
*  My database is BigQuery.
*  My Metabase version is 15.0

The Query Processor never returns datetimes as unix timestamps, so we shouldn't be trying to automagically convert large integers to datetimes. 

![screen shot 2016-02-26 at 4 37 02 pm](https://cloud.githubusercontent.com/assets/1455846/13369243/60e3c148-dca7-11e5-81a4-3e01cedbc7a1.png)

**Comment by tlrobinson** [comment]
Apparently I fixed one overzealous date detection routine and broke another... moment.js will parse ISO-8601 dates even without punctuation ¯\_(ツ)_/¯

https://github.com/metabase/metabase/blob/master/frontend/src/lib/formatting.js#L86

If we're sure the column metadata will be accurate in every case we care about (e.x. it's not Date/Time for something like `select '2016-02-27T03:06:52.000Z';`) we should replace that second clause with `isDate()` from the `schema_metadata` module. If we still want auto-detection on the client to catch those edge cases we should stop relying on `new Date()` or `moment` for detection and just use a regex for the formats we care about.

**Comment by agilliland** [comment]
@tlrobinson I was just going to change that isValid() call to `moment(value, ["YYYY-MM-DD'T'HH:mm:ss.SSSZ"], true).isValid()`

For now that feels reasonable because that's a very specific format meant for timestamps and it includes TZ information so we can safely parse it.
