### ISSUE TITLE
Model metadata name for multiple mapped Entity Keys is not always shown

### ISSUE THREAD

**Issue by janpeterka** [metabase/metabase#20419]
v0.42.0

I edited metadata of Model, and it's not reflected in notebook (one column is, others are not).
If I use those presented, I get error.

![Screenshot from 2022-02-10 13-58-11](https://user-images.githubusercontent.com/6343648/153413130-d2415e27-2ebb-45f8-90ec-4ca3f0a20468.png)
![Screenshot from 2022-02-10 13-58-25](https://user-images.githubusercontent.com/6343648/153413128-1c2c569b-9280-4134-8954-faf2c0e0fedb.png)
![Screenshot from 2022-02-10 14-00-25](https://user-images.githubusercontent.com/6343648/153413392-4eeef55a-ade6-4828-8331-9f7814476d74.png)

**Comment by flamber** [comment]
Reproduce:
1. Native > Sample > `select ID, USER_ID, PRODUCT_ID, QUANTITY AS REVIEWS_ID from ORDERS limit 2` - save as "Q1"
2. Change to Model
3. Edit metadata and map each column to the respective table.id, so they become Entity Key and rename the display name
![image](https://user-images.githubusercontent.com/1447303/155146298-84e11b39-3ee0-4bc3-9ae4-c987251b8717.png)
4. Now use the Model as the base for a new question and make a join - it will only show the correct display name for the first two columns
![image](https://user-images.githubusercontent.com/1447303/155146989-b73624f1-5f07-443d-a03e-da4cfeeefecf.png)
5. Selecting one of the bottom "ID" will actually show the correct table (here select the third field, `Products.ID`)
![image](https://user-images.githubusercontent.com/1447303/155167395-9f362e40-fe5a-4ebd-8b3c-be42b184fe8e.png)

**Comment by kulyk** [comment]
@flamber I'm not sure I can reproduce this issue, guess something else fixed it

**Comment by flamber** [comment]
@kulyk I can still reproduce on master, and even on stats. In step 3, it's important to map each column to their respective table and with Entity Key.
![image](https://user-images.githubusercontent.com/1447303/166224604-78a31eb6-990d-4652-ae10-6a6342389c1a.png)

**Comment by daltojohnso** [comment]
Did a bit of digging on this. Here's a rough description of what's going on

- Selecting the model as the data source triggers a request for the underlying card object, including the card's `result_metadata`, which contains the fields founder on the card and includes some model-specific metadata such as the set display name. We store this metadata in the `metadata` object in a map of fields, keyed by the `id` prop.
- Selecting a specific table in the join step triggers a request for that table's metadata, including the table's fields. These fields are also stored in the `metadata` object, keyed by id. The ID field of this table will clobber the preexisting field that originated from the card's metadata, so we lose the model-specific metadata in the field list.

The fields coming from `result_metadata`, which they contain a virtual table id like `card__123`, shouldn't get stored by `id` alone as `id` is not sufficiently unique. A simple solution to avoid clobbering is to store these fields by id AND virtual table id, but I'm sure that'll have plenty of consequences elsewhere. Will see if it is a feasible solution.

**Comment by daltojohnso** [comment]
Have a fix https://github.com/metabase/metabase/pull/24645 that solves the issue by doing what I mention last in my previous comment -- by always looking at `result_metadata` of the underlying card when building a new question based on a card.

**Comment by daltojohnso** [comment]
This bug has cropped back up already 💀 -- I'm guessing something in my fix for https://github.com/metabase/metabase/issues/22715 is causing more metadata clobbering issues, as I encountered a number of frustrating issues whenever a Dimension's `field_ref` contains a `"join-alias"`. Will investigate.

**Comment by daltojohnso** [comment]
https://github.com/metabase/metabase/pull/25109 fixes this
