### ISSUE TITLE
Programmatically adjust visualization settings

### ISSUE THREAD

**Issue by OnlineChampion** [metabase/metabase#20428]
Is there a way to programmatically adjust/override some visualizations settings?

For example: I have a graph that needs the y-axis min/max to be adjusted according to the dynamic recordset being plotted. And I don't want to use the auto y-axis as this starts at 0.

Another example: It would be great if there was a way I could, in code, override a Visualization's color for a particular data series.

**Comment by flamber** [comment]
Hi @OnlineChampion 
Yes, using the API: https://www.metabase.com/learn/administration/metabase-api
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
