### ISSUE TITLE
Custom expression - Count needs parentheses, but deletes them afterwards

### ISSUE THREAD

**Issue by janpeterka** [metabase/metabase#20420]
v0.24.0

When I add custom expression with Count, it requires `Count()`.
When I save it and again edit, parentheses are gone, so it's shown in invalid format.

It's irritating, but in no way critical.

![Screenshot from 2022-02-10 15-47-19](https://user-images.githubusercontent.com/6343648/153432002-6872bf5d-d134-4aba-b4c4-09a5ccc3e9f9.png)

**Comment by flamber** [comment]
@janpeterka I hope you're not using 0.25.0 ;-)
`Count` function is different that others, since it's without parenthesis, but it seems to be causing problems between the validator and the cleanup.

**Comment by janpeterka** [comment]
@flamber Haha, got confused by numbers 😅

Thanks for looking into this.
And just want to say - 0.42 is really big update in my opinion, you really improved many thing (I'm soo happy with how much faster Custom expressions are, and thank you for adding option to deselect all columns in first datasource!), so it's not surprising there are few new bugs. Thanks for your hard work, thanks for how fast you reply and offer help. I really love Metabase and all interactions with team behind it.
