### ISSUE TITLE
Integrate Firebolt driver to the main repo

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#20430]
[Firebolt](https://www.firebolt.io/) is an analytics-optimized data warehouse.

They have a team of engineers developing a Metabase driver. The goal is to develop a driver to serve cloud customers, so it should live in the main Metabase repo.

They added the test suite and most tests are passing, they are in the final stages of passing all tests. This [spreadsheet](https://docs.google.com/spreadsheets/d/1OuHzQqNZVixRk3Aod1yz7Mzfj5-03PgnZrQPbsRmSd8/edit?usp=sharing) tracks the tests.

The driver code is in the `develop` branch of [this repo](https://github.com/raghavSharmaCode/metabase-firebolt-driver/tree/develop). I asked them to add everyone from the Stormchasers pod to the repo. But if you don't have access yet, the last version of the code as 2022/02/10 is here: [metabase-firebolt-driver-develop.zip](https://github.com/metabase/metabase/files/8043650/metabase-firebolt-driver-develop.1.zip)

Now, there are 3 issues. Two that they are solving and one that we need to work on our side:

**Firebolt** issues:
- Nested expressions in CASE operator fails
- SUM(CASE WHEN .. 0 END) evaluates to NULL

**Metabase** issues:
- Assertions are failing due to time data type is not supported by Firebolt (issue 12 in the spreadsheet)

On our side, we need to
- [ ] Add :firebolt keyword to assertions that need time support (like [this](https://github.com/metabase/metabase/blob/master/test/metabase/query_processor_test/alternative_date_test.clj#L277-L302)).
- [ ] Integrate the driver to our main repo and add the necessary parameters to CI. Firebolt is a cloud database and we have our own cloud credentials. It is the 1Password vault.

**Comment by camsaul** [comment]
👎 on integrating drivers for any more Cloud-based databases into the core repo... they're way to hard to test and hack on locally and the extra support burden for them makes shipping new features a lot slower. We could ship a thousand database drivers but we'd never be able to add any new features ever again, it would take us the rest of our lives to update 1000 drivers.
