### ISSUE TITLE
Pulse Question Alert to Slack sending cropped images

### ISSUE THREAD

**Issue by cbellinz** [metabase/metabase#20444]
**Describe the bug**

We are sending a bunch of alerts based on questions to Slack through the usual configuration. As of the above Metabase version, we are now seeing the images being cropped in Slack to squares, cutting off the majority of the content that we previously saw.

**Logs**

I cannot see any logs on the server side that suggest an issue.

**To Reproduce**
1. Setup Slack integration as per standard instructions
2. Create tabular question with a number of columns
3. Create an Action, include Slack as delivery mechanism
4. When pulse runs on the hour, view message in Slack.
5. Image is cropped square, losing some of the data on the right

![after](https://user-images.githubusercontent.com/44439476/153591725-a8a1606e-9dbe-48ee-9de1-8bcf2fb81df5.jpg)

**Expected behavior**

Image is not cropped square (this was prior to release of 0.42.0)

![before](https://user-images.githubusercontent.com/44439476/153591765-29ac78dd-a95f-431e-a512-f7c9670456cb.jpg)

**Screenshots**
Added inline above

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: N/A
- Your operating system: Mac OSX 12.2
- Your databases: Postgres
- Metabase version: v0.42.0
- Metabase hosting environment: AWS ECS Docker
- Metabase internal database: Postgres

**Severity**
Annoying

**Additional context**
I cannot guarantee that this is a Metabase problem v a Slack problem. I have raised issue with Slack in case it is something at their end. Irrespective, if a Slack issue, it is useful for everyone to be aware... Therefore, i will update if i find out anything from that side.

**Comment by flamber** [comment]
@noahmoss Caused by #20032, seems like it would likely be better to revert to previous problem instead.

**Comment by noahmoss** [comment]
Ugh. Let me take a minute and see if there's any quick way to fix this. If not I'll revert.
