### ISSUE TITLE
Multiple Goal Lines

### ISSUE THREAD

**Issue by mpingo** [metabase/metabase#20440]
I have always wondered if it would be possible to have multiple goal lines on the line and bar charts. So after some tinkering, I managed to have that as shown. Would it be possible to add it to be part of Metabase? How does one do so if it is possible?

![image](https://user-images.githubusercontent.com/3973540/153571466-486a6a4c-2f06-40df-a040-366d9f2cca82.png)

**Comment by flamber** [comment]
Duplicate of #9653
