### ISSUE TITLE
Replace Clojure-land data migrations with Liquibase migrations

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#20449]
This is to track all the replacement to Liquibase migrations:

* [x] #20399
* [x] #20400 
* [x] #20401
* [x] #20402 
* [x] #20403 
* [x] #20404 
* [x] #20405
* [x] #20407
* [x] #20574

Also related: #20409.

**Comment by camsaul** [comment]
Closing this out for now. There's one last Clojure-land data migration to migrate but it's unlikely we'll be able to do so until #20599 is resolved
