### ISSUE TITLE
Cannot use Data Selector when going directly to a question in new tab (or browser refresh)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20459]
**Describe the bug**
When going directly to a question in a new tab (or browser refresh), then the Data Selector is not working.
Regression since 0.41.1/0.41.0, but parts of this are very similar to #10927, which has gotten worse too.

Workaround: When on a non-working loader, go to "Ask a question" > Notebook, then it will initialize the browser state, and then click browser Back-button twice, so you return to the question, now it's possible to select a different table.

**To Reproduce**
1. Create a question on a table inside of a schema (e.g. Postgres) - save question
2. Do a browser refresh (or go to the question directly in a new tab) - **notice** there's no schema information in the breadcrumb
![image](https://user-images.githubusercontent.com/1447303/153648703-32363857-3fbc-4f04-b498-8cf02ec09c2a.png)
3. Go to Notebook to try to change to a different table - it will show forever spinner - and note that it's showing the schema
![image](https://user-images.githubusercontent.com/1447303/153648989-407517fa-4c76-4746-9d9b-24e555bf86ed.png)
4. There seems to be a second regression. Even if I follow the workaround, then when I try to change me table, then the data selector will show my database list instead of already being inside of the schema. Smaller problem than previous. And there's an extra tail on this if using 0.42+ because of [#20406](https://github.com/metabase/metabase/issues/20406)
![image](https://user-images.githubusercontent.com/1447303/153649937-feeb082f-a666-4f92-be11-5bb64c3db780.png)

**Information about your Metabase Installation:**
Tested 0.40.5 thru 0.42.0, regression since 0.41.1/0.41.0 (there were some browser state issue with schemas and data selector)

**Comment by nemanjaglumac** [comment]
Since we don't have a sample database with schemas (other than the default one "public"), I can't test this using Cypress for now.
