### ISSUE TITLE
Metadata/document the App DB

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20467]
**Is your feature request related to a problem? Please describe.**
Providing table and column descriptions of our App DB would be a nice addition for users that use the DB for custom reports or any addition to the data model

**Describe the solution you'd like**
In the same way we provide metadata of the H2 sample database, we could do the same for the app db

**Describe alternatives you've considered**
None

**How important is this feature to you?**
A customer requested the DB model, as they needed to do custom reports and we have the data model in docs, but we could provide this in the product

**Additional context**
NA

**Comment by flamber** [comment]
Slightly outdated version: https://github.com/metabase/metabase/wiki/Metabase-Database-Models
Duplicate of #3389
