### ISSUE TITLE
Ugly error state in Admin > Databases

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20471]
<img width="1887" alt="image" src="https://user-images.githubusercontent.com/1455846/153684471-d01ddcba-1bde-4ad3-a7d5-ada96a7900fe.png">

When the `GET /api/databases` endpoint returns an error you get a page that makes your eyes bleed.

1. Tweak the endpoint so it fails e.g. #20470 
2. Admin > Databases
3. Eyes bleeding

See also #20469

**Comment by WiNloSt** [comment]
@flamber do you think doing something similar to https://github.com/metabase/metabase/pull/20824 would be ok i.e. Wrap those errors into a collapsible UI component.

**Comment by flamber** [comment]
@WiNloSt Yes, that would probably be good to show a nice error with the option to expand the actually returned error message.
