### ISSUE TITLE
Custom SQL Too much recursion and Unresponsive Script

### ISSUE THREAD

**Issue by jadedevincabatlao** [metabase/metabase#2047]
![screenshot from 2016-02-23 11 59 55](https://cloud.githubusercontent.com/assets/17507008/13371040/ba80c25e-dd57-11e5-92e6-4888d7c72cbc.png)
![screenshot from 2016-02-27 09 49 04](https://cloud.githubusercontent.com/assets/17507008/13371041/baadc736-dd57-11e5-86c4-24a6f3b44134.png)

*  I am using the Firefox browser.
*  My computer's OS is Ubuntu 14.04.
*  My database is MySQL.
*  My Metabase version is 0.14.1.

**Comment by jadedevin13** [comment]
I'll try this again on 0.15.1.

**Comment by agilliland** [comment]
@jadedevin13 any updates on this?  did v0.15.1 resolve this for you?

**Comment by camsaul** [comment]
![image](https://cloud.githubusercontent.com/assets/1455846/14399225/6ce492ce-fd9f-11e5-823c-865fe78bc8c9.png)

**Comment by camsaul** [comment]
@jadedevin13 have you had a chance to see if this is resolved in a newer version of Metabase? v0.16.1 is out so there's a chance the issue has been resolved since then.

**Comment by camsaul** [comment]
Motion to close since this was opened against 0.14.1, unable to repro and haven't heard back from OP since Feb.

**Comment by agilliland** [comment]
Lets give it one more week and then we can close this.

**Comment by snarfed** [comment]
i'm seeing this pretty regularly now too. v0.20.1 on ubuntu, client is firefox 49.0.2 on mac os x 10.11.6. usually happens after firefox has been hung and pegged at 100% CPU for at least 30s or so.

here's some stuff i pulled out of the JS console and dev tools that i don't fully understand. :P

Stack trace:
```
[object Object]1app.bundle.js:105:29794
n/<()app.bundle.js:105
r()vendor.bundle.js:27
h/<()vendor.bundle.js:27
c/</e[t]()vendor.bundle.js:27
r()app.bundle.js:105
r/<()app.bundle.js:105
T/</s()vendor.bundle.js:26
T/<()vendor.bundle.js:26
e.exports/l()vendor.bundle.js:1
```

JS InternalError is https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c line 149, message "too much recursion," stack trace below. (looks like it got truncated. i also added newlines that may or may not be right. 🐶 🔬 :P)

```
h.Mixin._updateDOMProperties@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:149:25326
h.Mixin.updateComponent@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:149:24520
h.Mixin.receiveComponent@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:149:24037
o<.receiveComponent@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:40:7393
E._updateRenderedComponent@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:149:15179
E._performComponentUpdate@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:149:14933
E.updateComponent@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:149:14211
E.receiveComponent@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:149:13322
o<.receiveComponent@https://metabase.getcolor.com/app/dist/app.bundle.js?a6110a2992dd7c39752c:40:7393
l<.updateChildren@https://metabase.getco
```

**Comment by csawyerYumaed** [comment]
We see unresponsive script in FF fairly often as well, using PG database using metabase version v0.25.2

![script](https://user-images.githubusercontent.com/3818302/30705218-b706e210-9ea9-11e7-980d-ed27e7ba1001.png)
