### ISSUE TITLE
Run metabase Uberjar failed

### ISSUE THREAD

**Issue by jiaxing-1994** [metabase/metabase#20486]
1. download metabase code from github, version is v1.41.5
2. run `clojure -M:run` and  `yarn build-hot` successful!
3. run `./bin/build` to build myself metabase uberjar.
4. run `java -jar metabase.jar` failed,  the error is 
>     ERROR metabase.core :: Metabase Initialization FAILED
>     liquibase.exception.UnexpectedLiquibaseException: Cannot find ChangeLogHistoryService for unsupported

my java version:
>     java version "1.8.0_161"
>    Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
>    Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

the full log:
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> 
> 2022-02-14 15:07:25,691 INFO metabase.util :: Maximum memory available to JVM: 4.0 GB
> 
> 2022-02-14 15:07:31,488 WARN servicelocator.DefaultPackageScanClassResolver :: Cannot search jar file '/Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/metabase.jar' for classes due to an IOException: invalid code lengths set
> 
> java.util.zip.ZipException: invalid code lengths set
> 
> at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:165)
> 
> at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
> 
> at java.base/java.util.jar.JarInputStream.read(JarInputStream.java:207)
> 
> at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:143)
> 
> at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121)
> 
> at java.base/java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142)
> 
> at java.base/java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179)
> 
> at liquibase.servicelocator.DefaultPackageScanClassResolver.loadImplementationsInJar(DefaultPackageScanClassResolver.java:433)
> 
> at liquibase.servicelocator.DefaultPackageScanClassResolver.findAllClasses(DefaultPackageScanClassResolver.java:231)
> 
> at liquibase.servicelocator.DefaultPackageScanClassResolver.find(DefaultPackageScanClassResolver.java:121)
> 
> at liquibase.servicelocator.DefaultPackageScanClassResolver.findImplementations(DefaultPackageScanClassResolver.java:89)
> 
> at liquibase.servicelocator.ServiceLocator.findClassesImpl(ServiceLocator.java:226)
> 
> at liquibase.servicelocator.ServiceLocator.findClasses(ServiceLocator.java:201)
> 
> at liquibase.sqlgenerator.SqlGeneratorFactory.<init>(SqlGeneratorFactory.java:35)
> 
> at liquibase.sqlgenerator.SqlGeneratorFactory.getInstance(SqlGeneratorFactory.java:50)
> 
> at metabase.db.liquibase__init.load(Unknown Source)
> 
> at metabase.db.liquibase__init.<clinit>(Unknown Source)
> 
> at java.base/java.lang.Class.forName0(Native Method)
> 
> at java.base/java.lang.Class.forName(Class.java:398)
> 
> at clojure.lang.RT.classForName(RT.java:2212)
> 
> at clojure.lang.RT.classForName(RT.java:2221)
> 
> at clojure.lang.RT.loadClassForName(RT.java:2240)
> 
> at clojure.lang.RT.load(RT.java:449)
> 
> at clojure.lang.RT.load(RT.java:424)
> 
> at clojure.core$load$fn__6856.invoke(core.clj:6115)
> 
> at clojure.core$load.invokeStatic(core.clj:6114)
> 
> at clojure.core$load.doInvoke(core.clj:6098)
> 
> at clojure.lang.RestFn.invoke(RestFn.java:408)
> 
> at clojure.core$load_one.invokeStatic(core.clj:5897)
> 
> at clojure.core$load_one.invoke(core.clj:5892)
> 
> at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
> 
> at clojure.core$load_lib.invokeStatic(core.clj:5936)
> 
> at clojure.core$load_lib.doInvoke(core.clj:5917)
> 
> at clojure.lang.RestFn.applyTo(RestFn.java:142)
> 
> at clojure.core$apply.invokeStatic(core.clj:669)
> 
> at clojure.core$load_libs.invokeStatic(core.clj:5974)
> 
> at clojure.core$load_libs.doInvoke(core.clj:5958)
> 
> at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 
> at clojure.core$apply.invokeStatic(core.clj:669)
> 
> at clojure.core$require.invokeStatic(core.clj:5996)
> 
> at clojure.core$require.doInvoke(core.clj:5996)
> 
> at clojure.lang.RestFn.invoke(RestFn.java:1096)
> 
> at metabase.db.setup$loading__6737__auto____34049.invoke(setup.clj:1)
> 
> at metabase.db.setup__init.load(Unknown Source)
> 
> at metabase.db.setup__init.<clinit>(Unknown Source)
> 
> at java.base/java.lang.Class.forName0(Native Method)
> 
> at java.base/java.lang.Class.forName(Class.java:398)
> 
> at clojure.lang.RT.classForName(RT.java:2212)
> 
> at clojure.lang.RT.classForName(RT.java:2221)
> 
> at clojure.lang.RT.loadClassForName(RT.java:2240)
> 
> at clojure.lang.RT.load(RT.java:449)
> 
> at clojure.lang.RT.load(RT.java:424)
> 
> at clojure.core$load$fn__6856.invoke(core.clj:6115)
> 
> at clojure.core$load.invokeStatic(core.clj:6114)
> 
> at clojure.core$load.doInvoke(core.clj:6098)
> 
> at clojure.lang.RestFn.invoke(RestFn.java:408)
> 
> at clojure.core$load_one.invokeStatic(core.clj:5897)
> 
> at clojure.core$load_one.invoke(core.clj:5892)
> 
> at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
> 
> at clojure.core$load_lib.invokeStatic(core.clj:5936)
> 
> at clojure.core$load_lib.doInvoke(core.clj:5917)
> 
> at clojure.lang.RestFn.applyTo(RestFn.java:142)
> 
> at clojure.core$apply.invokeStatic(core.clj:669)
> 
> at clojure.core$load_libs.invokeStatic(core.clj:5974)
> 
> at clojure.core$load_libs.doInvoke(core.clj:5958)
> 
> at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 
> at clojure.core$apply.invokeStatic(core.clj:669)
> 
> at clojure.core$require.invokeStatic(core.clj:5996)
> 
> at clojure.core$require.doInvoke(core.clj:5996)
> 
> at clojure.lang.RestFn.invoke(RestFn.java:482)
> 
> at metabase.db$loading__6737__auto____34208.invoke(db.clj:1)
> 
> at metabase.db__init.load(Unknown Source)
> 
> at metabase.db__init.<clinit>(Unknown Source)
> 
> at java.base/java.lang.Class.forName0(Native Method)
> 
> at java.base/java.lang.Class.forName(Class.java:398)
> 
> at clojure.lang.RT.classForName(RT.java:2212)
> 
> at clojure.lang.RT.classForName(RT.java:2221)
> 
> at clojure.lang.RT.loadClassForName(RT.java:2240)
> 
> at clojure.lang.RT.load(RT.java:449)
> 
> at clojure.lang.RT.load(RT.java:424)
> 
> at clojure.core$load$fn__6856.invoke(core.clj:6115)
> 
> at clojure.core$load.invokeStatic(core.clj:6114)
> 
> at clojure.core$load.doInvoke(core.clj:6098)
> 
> at clojure.lang.RestFn.invoke(RestFn.java:408)
> 
> at clojure.core$load_one.invokeStatic(core.clj:5897)
> 
> at clojure.core$load_one.invoke(core.clj:5892)
> 
> at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
> 
> at clojure.core$load_lib.invokeStatic(core.clj:5936)
> 
> at clojure.core$load_lib.doInvoke(core.clj:5917)
> 
> at clojure.lang.RestFn.applyTo(RestFn.java:142)
> 
> at clojure.core$apply.invokeStatic(core.clj:669)
> 
> at clojure.core$load_libs.invokeStatic(core.clj:5974)
> 
> at clojure.core$load_libs.doInvoke(core.clj:5958)
> 
> at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 
> at clojure.core$apply.invokeStatic(core.clj:669)
> 
> at clojure.core$require.invokeStatic(core.clj:5996)
> 
> at clojure.core$require.doInvoke(core.clj:5996)
> 
> at clojure.lang.RestFn.invoke(RestFn.java:3894)
> 
> at metabase.core$loading__6737__auto____80676.invoke(core.clj:1)
> 
> at metabase.core__init.load(Unknown Source)
> 
> at metabase.core__init.<clinit>(Unknown Source)
> 
> at java.base/java.lang.Class.forName0(Native Method)
> 
> at java.base/java.lang.Class.forName(Class.java:398)
> 
> at clojure.lang.RT.classForName(RT.java:2212)
> 
> at clojure.lang.RT.classForName(RT.java:2221)
> 
> at clojure.lang.RT.loadClassForName(RT.java:2240)
> 
> at clojure.lang.RT.load(RT.java:449)
> 
> at clojure.lang.RT.load(RT.java:424)
> 
> at clojure.core$load$fn__6856.invoke(core.clj:6115)
> 
> at clojure.core$load.invokeStatic(core.clj:6114)
> 
> at clojure.core$load.doInvoke(core.clj:6098)
> 
> at clojure.lang.RestFn.invoke(RestFn.java:408)
> 
> at clojure.lang.Var.invoke(Var.java:384)
> 
> at clojure.lang.Util.loadWithClass(Util.java:251)
> 
> at metabase.core.<clinit>(Unknown Source)
> 
> 2022-02-14 15:07:34,986 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
> 
> For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
> 
> 2022-02-14 15:07:37,588 INFO driver.impl :: Registered abstract driver :sql 🚚
> 
> ⮦ Load driver :sql took 427.3 ms
> 
> 2022-02-14 15:07:37,606 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
> 
> Load driver :sql-jdbc took 448.9 ms
> 
> 2022-02-14 15:07:37,609 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
> 
> 2022-02-14 15:07:37,625 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
> 
> 2022-02-14 15:07:37,636 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
> 
> 2022-02-14 15:07:39,710 INFO metabase.core ::
> 
> Metabase vUNKNOWN (? ?)
> 
> Copyright © 2022 Metabase, Inc.
> 
> Metabase Enterprise Edition extensions are NOT PRESENT.
> 
> 2022-02-14 15:07:39,729 INFO metabase.core :: Starting Metabase in STANDALONE mode
> 
> 2022-02-14 15:07:39,806 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
> 
> {:port 3000}
> 
> 2022-02-14 15:07:39,852 INFO metabase.core :: Starting Metabase version vUNKNOWN (? ?) ...
> 
> 2022-02-14 15:07:39,954 INFO metabase.core :: System info:
> 
> {"file.encoding" "UTF-8",
> 
> "java.runtime.name" "Java(TM) SE Runtime Environment",
> 
> "java.runtime.version" "11.0.14+8-LTS-263",
> 
> "java.vendor" "Oracle Corporation",
> 
> "java.vendor.url" "https://openjdk.java.net/",
> 
> "java.version" "11.0.14",
> 
> "java.vm.name" "Java HotSpot(TM) 64-Bit Server VM",
> 
> "java.vm.version" "11.0.14+8-LTS-263",
> 
> "os.name" "Mac OS X",
> 
> "os.version" "12.1",
> 
> "user.language" "zh",
> 
> "user.timezone" "Asia/Shanghai"}
> 
> 2022-02-14 15:07:39,956 INFO metabase.plugins :: Loading plugins in /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins...
> 
> 2022-02-14 15:07:40,153 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/sparksql.metabase-driver.jar
> 
> 2022-02-14 15:07:40,469 INFO util.files :: Extract file /modules/bigquery.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/bigquery.metabase-driver.jar
> 
> 2022-02-14 15:07:40,477 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/sqlserver.metabase-driver.jar
> 
> 2022-02-14 15:07:40,488 INFO util.files :: Extract file /modules/presto-jdbc.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/presto-jdbc.metabase-driver.jar
> 
> 2022-02-14 15:07:40,535 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/sqlite.metabase-driver.jar
> 
> 2022-02-14 15:07:40,593 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/vertica.metabase-driver.jar
> 
> 2022-02-14 15:07:40,594 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/redshift.metabase-driver.jar
> 
> 2022-02-14 15:07:40,599 INFO util.files :: Extract file /modules/presto.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/presto.metabase-driver.jar
> 
> 2022-02-14 15:07:40,600 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/druid.metabase-driver.jar
> 
> 2022-02-14 15:07:40,603 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/mongo.metabase-driver.jar
> 
> 2022-02-14 15:07:40,617 INFO util.files :: Extract file /modules/google.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/google.metabase-driver.jar
> 
> 2022-02-14 15:07:40,625 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/oracle.metabase-driver.jar
> 
> 2022-02-14 15:07:40,627 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/snowflake.metabase-driver.jar
> 
> 2022-02-14 15:07:40,752 INFO util.files :: Extract file /modules/googleanalytics.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/googleanalytics.metabase-driver.jar
> 
> 2022-02-14 15:07:40,757 INFO util.files :: Extract file /modules/bigquery-cloud-sdk.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/bigquery-cloud-sdk.metabase-driver.jar
> 
> 2022-02-14 15:07:40,792 INFO util.files :: Extract file /modules/presto-common.metabase-driver.jar -> /Users/huangjiaxing/works/wk/bi/metabase-1.42.0/target/uberjar/plugins/presto-common.metabase-driver.jar
> 
> 2022-02-14 15:07:40,934 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-common...
> 
> 2022-02-14 15:07:40,937 INFO driver.impl :: Registered abstract driver :presto-common 🚚
> 
> 2022-02-14 15:07:40,964 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery-cloud-sdk...
> 
> 2022-02-14 15:07:40,969 INFO driver.impl :: Registered driver :bigquery-cloud-sdk (parents: [:sql]) 🚚
> 
> 2022-02-14 15:07:40,980 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
> 
> 2022-02-14 15:07:40,981 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
> 
> 2022-02-14 15:07:40,982 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Google Analytics Driver"]
> 
> 2022-02-14 15:07:41,002 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
> 
> 2022-02-14 15:07:41,004 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
> 
> 2022-02-14 15:07:41,024 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.
> 
> 2022-02-14 15:07:41,025 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
> 
> 2022-02-14 15:07:41,025 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Google Analytics Driver"]
> 
> 2022-02-14 15:07:41,042 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
> 
> 2022-02-14 15:07:41,043 INFO driver.impl :: Registered abstract driver :google 🚚
> 
> 2022-02-14 15:07:41,044 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
> 
> 2022-02-14 15:07:41,045 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase Google Analytics Driver"]
> 
> 2022-02-14 15:07:41,046 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
> 
> 2022-02-14 15:07:41,047 INFO driver.impl :: Registered driver :googleanalytics (parents: [:google]) 🚚
> 
> 2022-02-14 15:07:41,057 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
> 
> 2022-02-14 15:07:41,057 INFO driver.impl :: Registered driver :mongo 🚚
> 
> 2022-02-14 15:07:41,067 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
> 
> 2022-02-14 15:07:41,068 INFO driver.impl :: Registered driver :druid 🚚
> 
> 2022-02-14 15:07:41,073 INFO plugins.dependencies :: Plugin 'Metabase Presto Driver' depends on plugin 'Presto Common Driver'
> 
> 2022-02-14 15:07:41,074 INFO plugins.dependencies :: Metabase Presto Driver dependency {:plugin Presto Common Driver} satisfied? true
> 
> 2022-02-14 15:07:41,074 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
> 
> 2022-02-14 15:07:41,075 INFO driver.impl :: Registered driver :presto (parents: [:presto-common]) 🚚
> 
> 2022-02-14 15:07:41,079 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
> 
> 2022-02-14 15:07:41,080 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
> 
> 2022-02-14 15:07:41,083 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
> 
> 2022-02-14 15:07:41,083 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
> 
> 2022-02-14 15:07:41,084 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Vertica Driver"]
> 
> 2022-02-14 15:07:41,087 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
> 
> 2022-02-14 15:07:41,088 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
> 
> 2022-02-14 15:07:41,095 INFO plugins.dependencies :: Plugin 'Metabase Presto JDBC Driver' depends on plugin 'Presto Common Driver'
> 
> 2022-02-14 15:07:41,096 INFO plugins.dependencies :: Metabase Presto JDBC Driver dependency {:plugin Presto Common Driver} satisfied? true
> 
> 2022-02-14 15:07:41,096 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-jdbc...
> 
> 2022-02-14 15:07:41,097 INFO driver.impl :: Registered driver :presto-jdbc (parents: [:presto-common]) 🚚
> 
> 2022-02-14 15:07:41,109 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
> 
> 2022-02-14 15:07:41,110 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
> 
> 2022-02-14 15:07:41,116 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
> 
> 2022-02-14 15:07:41,116 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
> 
> 2022-02-14 15:07:41,116 WARN plugins.lazy-loaded-driver :: Warning: plugin manifest for :bigquery does not include connection properties
> 
> 2022-02-14 15:07:41,116 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
> 
> 2022-02-14 15:07:41,117 INFO driver.impl :: Registered driver :bigquery (parents: [:sql :google]) 🚚
> 
> 2022-02-14 15:07:41,131 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
> 
> 2022-02-14 15:07:41,132 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
> 
> 2022-02-14 15:07:41,132 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
> 
> 2022-02-14 15:07:41,132 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
> 
> 2022-02-14 15:07:41,134 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
> 
> 2022-02-14 15:07:41,138 WARN db.env :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html
> 
> 2022-02-14 15:07:41,145 INFO db.setup :: Verifying h2 Database Connection ...
> 
> 2022-02-14 15:07:41,289 INFO db.setup :: Successfully verified H2 1.4.197 (2018-03-18) application database connection. ✅
> 
> 2022-02-14 15:07:41,291 INFO db.setup :: Running Database Migrations...
> 
> 2022-02-14 15:07:41,295 INFO db.setup :: Setting up Liquibase...
> 
> 2022-02-14 15:07:41,299 WARN database.DatabaseFactory :: Unknown database: H2
> 
> 2022-02-14 15:07:41,340 INFO db.setup :: Liquibase is ready.
> 
> 2022-02-14 15:07:41,342 INFO db.liquibase :: Checking if Database has unrun migrations...
> 
> 2022-02-14 15:07:41,346 ERROR metabase.core :: Metabase Initialization FAILED
> 
> liquibase.exception.UnexpectedLiquibaseException: Cannot find ChangeLogHistoryService for unsupported
> 
> at liquibase.changelog.ChangeLogHistoryServiceFactory.getChangeLogService(ChangeLogHistoryServiceFactory.java:73)
> 
> at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1217)
> 
> at liquibase.Liquibase.listLocks(Liquibase.java:1240)
> 
> at metabase.db.liquibase$migration_lock_exists_QMARK_.invokeStatic(liquibase.clj:98)
> 
> at metabase.db.liquibase$migration_lock_exists_QMARK_.invoke(liquibase.clj:95)
> 
> at metabase.db.liquibase$release_lock_if_needed_BANG_.invokeStatic(liquibase.clj:188)
> 
> at metabase.db.liquibase$release_lock_if_needed_BANG_.invoke(liquibase.clj:184)
> 
> at metabase.db.setup$migrate_BANG_$fn__34055$fn__34056.invoke(setup.clj:91)
> 
> at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:38)
> 
> at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:30)
> 
> at metabase.db.setup$migrate_BANG_$fn__34055.invoke(setup.clj:63)
> 
> at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
> 
> at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
> 
> at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
> 
> at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
> 
> at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
> 
> at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
> 
> at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:54)
> 
> at metabase.db.setup$migrate_BANG_.invoke(setup.clj:40)
> 
> at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:119)
> 
> at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:115)
> 
> at metabase.db.setup$setup_db_BANG_$fn__34106$fn__34107.invoke(setup.clj:143)
> 
> at metabase.util$do_with_us_locale.invokeStatic(util.clj:692)
> 
> at metabase.util$do_with_us_locale.invoke(util.clj:678)
> 
> at metabase.db.setup$setup_db_BANG_$fn__34106.invoke(setup.clj:141)
> 
> at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
> 
> at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
> 
> at metabase.db$setup_db_BANG_$fn__34216.invoke(db.clj:61)
> 
> at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
> 
> at metabase.db$setup_db_BANG_.invoke(db.clj:51)
> 
> at metabase.core$init_BANG_.invokeStatic(core.clj:90)
> 
> at metabase.core$init_BANG_.invoke(core.clj:73)
> 
> at metabase.core$start_normally.invokeStatic(core.clj:131)
> 
> at metabase.core$start_normally.invoke(core.clj:125)
> 
> at metabase.core$_main.invokeStatic(core.clj:164)
> 
> at metabase.core$_main.doInvoke(core.clj:158)
> 
> at clojure.lang.RestFn.invoke(RestFn.java:397)
> 
> at clojure.lang.AFn.applyToHelper(AFn.java:152)
> 
> at clojure.lang.RestFn.applyTo(RestFn.java:132)
> 
> at metabase.core.main(Unknown Source)
> 
> 2022-02-14 15:07:41,364 INFO metabase.core :: Metabase Shutting Down ...
> 
> 2022-02-14 15:07:41,421 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
> 
> 2022-02-14 15:07:41,443 INFO metabase.core :: Metabase Shutdown COMPLETE

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
