### ISSUE TITLE
"SQL Query" in UI for MongoDB/Druid/GA native queries

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20499]
There's a reason the old UI used "Native query" and not "SQL query".

<img width="196" alt="image" src="https://user-images.githubusercontent.com/1455846/153927961-b8d17c9e-c3d8-442d-9cd4-1d8dad505e4d.png">

We don't support SQL for MongoDB (etc.) and not every native query is a SQL query.

**Comment by mazameli** [comment]
To my knowledge, we don't have evidence yet that this is a problem, and it was done intentionally: most folks are writing SQL queries, and "SQL query" is a more recognizable term than "Native query." Also, if you're the sort of person who's writing native Mongo queries, are you going to get tripped up by the "SQL query" label?

Having said that, there are a couple things we could consider if we find evidence that this is tripping people up:
- Sidestepping this and changing it from `SQL query` to just `Query` (as distinct from a `Question`).
- Conditionally displaying `Native query` instead if the instance has at least one noSQL DB connected which the user has query-writing perms for.

**Comment by flamber** [comment]
There's quite a lot of people in the forum, who tries to write SQL for those three databases, where of course fails with strange errors, and then they don't quite know how to write the native query for the specific type of database, since it's a strange format.

**Comment by nemanjaglumac** [comment]
The fix is ready to go.
Just let me know what is the final decision.

**Comment by mazameli** [comment]
> There's quite a lot of people in the forum, who tries to write SQL for those three databases, where of course fails with strange errors, and then they don't quite know how to write the native query for the specific type of database, since it's a strange format.

@flamber Do we think they weren't having that problem when the label was "Native query?" Are these forum posts from folks using 0.42?

My perception is that what you're calling out here is a relevant problem, but that we're misidentifying the solution. E.g., to address what you're describing, what if instead we did something like look and see if they're querying a noSQL DB, and if their query fails, check and see if it had a `SELECT` in it at all, and if so display a link to docs on how to query Mongo/GA/etc.

**Comment by flamber** [comment]
It was more generally what people hit - not specific to 42, but that change will likely bite us. But it's somewhat separate from this issue. It should probably be added together with other error handling in future versions.

**Comment by mazameli** [comment]
My proposed resolution:

- Continue displaying `SQL query` in this menu by default.
- If the current user has SQL/native query editor permissions for at least one connected database which is a noSQL type (Mongo, GA, any others?) then this label should say `Native query` instead.

If that sounds sane to @flamber, then @nemanjaglumac I think we should either close https://github.com/metabase/metabase/pull/20506, or modify it to match what I'm proposing here once that behavior is implemented.
