### ISSUE TITLE
Unable to lock param on embed

### ISSUE THREAD

**Issue by reediculous456** [metabase/metabase#20494]
**Describe the bug**
I am unable to set a parameter on an embed to locked on a question or dashboard. When I do, the embed screen crashes and takes me back to the question view page

**Logs**
No backend logs present

https://reactjs.org/docs/error-decoder.html/?invariant=188
![Screen Shot 2022-02-14 at 12 15 30 PM](https://user-images.githubusercontent.com/24629474/153913236-0ce128b8-c725-467d-a3e8-37220239ff1b.png)

**To Reproduce**
1. Go to any question or dashboard with parameters
2. Click on the share button
3. Choose Embed this in an application
4. Change any parameter to "Locked" 
5. See the issue

**Expected behavior**
I am able to set the parameter as locked as mentioned in the [documentation for embedding](https://www.metabase.com/docs/latest/administration-guide/13-embedding.html#embedding-charts-and-dashboards-with-locked-parameters)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 98.0.4758.80
- Your operating system: MacOS 12.1
- Your databases: Postgres
- Metabase hosting environment: Docker

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14+9",
    "os.name": "Linux",
    "os.version": "5.10.76-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-08",
      "tag": "v0.42.0",
      "branch": "release-x.42.x",
      "hash": "de1264e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Critical. I am unable to publish questions to my application without the ability to lock parameters

**Comment by reediculous456** [comment]
Thanks @flamber, I missed the original because it had already been closed. Any idea when that PR will get released?

**Comment by flamber** [comment]
Maybe today, maybe tomorrow.

**Comment by dgrijuela** [comment]
thanks @flamber, any update on the release?
