### ISSUE TITLE
Removing or adding column descriptions to metadata of Models results in "failed save"

### ISSUE THREAD

**Issue by smoens** [metabase/metabase#20517]
**Describe the bug**
Removing or adding column descriptions to metadata of Models results in "failed save"

**To Reproduce**
Error can be reproduced in Sample Database
1. Go to Metabase home page
2. Click on 'New' > 'Question'
3. Click on 'Raw Data'
4. Click on 'Sample Database' > Select 'People' > Click 'Save' to Personal Collection
5. Turn this question into a model
6. Click 'Customize metadata'
7. 'Remove Address description'
8. Click 'Save'

A similar problem occurs when adding Descriptions to columns that didn't have any description to begin with. When adding a description to one column, save succeeds, but the description is propagated across all the columns. Trying to modify descriptions the second time, results in a "Save failed" error.

**Expected behavior**
I expect a succesfull "Save" resulting in an empty description.

**Screenshots**
![image](https://user-images.githubusercontent.com/1371244/154039611-92c4d46c-0dbe-406c-ace5-4e56e147238c.png)

**Information about your Metabase Installation:**

See for metabase specifics the attached file
[diagnostic-information.txt](https://github.com/metabase/metabase/files/8068075/diagnostic-information.txt)

- Your browser and the version: Firefox 97.0
- Your operating system: Windows

**Severity**
The bug mostly is annoying, definitely when you have updated a bunch of descriptions and it fails to save, but it isn't blocking the usage of Metabase, it just prevents leveraging this functionality. It seemed interesting to be able to provide users additional context for the field this way.

**Comment by flamber** [comment]
The backend throws:
```
2022-02-15 16:44:33,248 DEBUG middleware.log :: PUT /api/card/790 400 13.2 ms (0 DB calls) 
{:errors
 {:result_metadata "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."}}
```

Workaround is to just type one character (example `-`), then it can save.

Feels very related to #11097

**Comment by smoens** [comment]
Apologies, thank you for your feedback. I did a search but didn't found a similar issue. There's another related issue (cfr.  changing the description propagates the same description across all the columns), but I can't replicate it in the sample database, so might be database specific. I'll check if a similar issue exists and if not create a new own.

**Comment by flamber** [comment]
I don't think it's a duplicate, since it's a slightly different error and different API endpoint, so let's keep this open.
