### ISSUE TITLE
Preconfigure Metabase / Support Config Files

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2052]
There have been a number of people who are launching MB instances on behalf of others. 

It would make it easier for them to be able to spin up a MB instance with database connections, questions, dashboards, pulses and perhaps user accounts preconfigured rather than needing to do it via the UI

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
How would the preconfigure it? With a config file?

**Comment by tlrobinson** [comment]
We do have a HTTP API they could use.

**Comment by Addvilz** [comment]
You can pre-configure it all once and then just clone the database.

**Comment by saidimu** [comment]
@camsaul It is standard to use environment variables for configuration in cloud deployments (see Heroku's [12 Factor App](http://12factor.net/config) guidelines.

**Comment by camsaul** [comment]
@saidimu from your link:

> Another approach to config is the use of config files which are not checked into revision control

**Comment by deitch** [comment]
Aha! I have been looking for this.

We deploy via docker containers, but either way, starting up an instance and requiring user Web UI interaction to get started is restricting. Would be far better to be able to pre-configure the options we want in a config file (databases, connections, admin user(s), etc.) and then have it run according to that.

**Comment by deitch** [comment]
> We do have a HTTP API they could use.

@tlrobinson is that documented anywhere?

**Comment by camsaul** [comment]
@deitch see https://github.com/metabase/metabase/wiki/Using-the-REST-API

**Comment by deitch** [comment]
Thanks @camsaul . I ended up running once, configuring, shutting down, saving the h2 files, might convert to Postgres to run in RDS. This really does not an ability to have a "seed file" with basic config (or env vars), where you can tell it what to start with.

**Comment by Krever** [comment]
This feature is exactly what I would like to have. I'm creating lightweight tool for managing some data, but in the end this that have to be visualized. My tool is backed by sqlite, so all I need to do is to create user, setup db path and load some dashboards. I will try to go with REST api, just letting you know that this is a valid business use-case for someone :)

**Comment by ConradIrwin** [comment]
I also would like this. We run on kubernetes, and it's really nice to be able to boot up a new cluster with no human interaction.

Kubernetes has good support for creating and using environment variables.

(I have a related request, which is to get rid of authorization completely. We run everything behind an authentication proxy similar to Google IAP; so it's tedious for users to have to log in twice).

**Comment by dttg** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by dyfrgi** [comment]
I'm thinking about implementing this during an internal hackathon we're having next week. Here's my current thinking about what's needed to make this good.

1. Deploy a basic configuration. Auth configuration (LDAP, in our case), database, etc.
2. Deploy questions and dashboards based on the contents of some files. Probably one question or dashboard per file.
3. Extract questions and dashboards from a dev instance in the right format for (2). Then the repo used for deployment can be managed by git, with questions/dashboards added via pull requests.

There are a couple other object types that matter some, but not to me, so they may not be in my initial version. I think the hardest part of adding types will be handling dependencies between object types if they aren't based on natural keys. Need to study the API.

**Comment by nathanpalmer** [comment]
Just to throw another thought into the pile here. We have several databases where the credentials are fully configured through Vault and the docker container that is running metabase has access to dynamically created credentials. If I could somehow pre-configure these connections using the most current credentials it would fit in perfectly with our infrastructure. As it is right now we have to manually configure credentials just for metabase with an unlimited expiration (all of our creds get rotated on a regular basis normally.)

**Comment by stevepeak** [comment]
I agree with many of the comment above. Having your database(s) predefined in environment variables can help distribution of Metabase.

I would love to see a way to pre-fill database connection details, dashboards,

postgres://postgres:@postgres:5432/postgres#name=Foobar

**Comment by nathanpalmer** [comment]
@manugarri We use the [database provider with Vault](https://www.vaultproject.io/docs/secrets/databases/index.html)

**Comment by soobrosa** [comment]
Is that correct that all connection data etc is held in the application database? I mean if there's a doc on that structure we could load a full DB dump to the application database.

**Comment by LucaPrete** [comment]
Hello everyone.

The last updates on this thread are from 2018. Did anything move forward since then?
We're struggling as well to create a proper kubernetes deployment for metabase, and working with rest api or guis after the container has started would be a real nightmare.

I'm wondering, if everything in Linux is a file, where all the configs that somebody injects through REST APIs end up in the container?
Could it be a solution to find that/those files and mount them as a volumes/configmaps when the container gets created?

Thanks

**Comment by sbelak** [comment]
We now have something along these lines as part of our Enterprise Offering: https://www.metabase.com/docs/latest/enterprise-guide/serialization 

It's still work in progress and somewhat experimental so we'd love feedback on it (it's also not final whether and/or which parts will remain EE-only).

**Comment by anki-code** [comment]
> working with rest api or guis after the container has started would be a real nightmare.

That`s damn right! Here is https://github.com/metabase/metabase/issues/6485 - the related thread with many links to discussions.

**Comment by anki-code** [comment]
I've solved this issue for me by this workflow/workaround:

1. I the fix version of metabase (for now it's v0.34.1)

2. I have a script witch get the `metabase.db.mv.db` file and clean it and convert it to sql file:

**metabase-db-to-sql.sh**:
```
#!/bin/bash
set -eu -o pipefail

H2_VERSION=2019-03-13

echo [Get H2]
wget https://h2database.com/h2-$H2_VERSION.zip
unzip h2-$H2_VERSION.zip
cp h2/bin/h2-*.jar ./
rm -r h2 h2*.zip

echo [Clean DB]
java -cp h2*.jar org.h2.tools.RunScript -url jdbc:h2:./metabase.db -script metabase-db-clean.sql

echo [DB to sql file]
java -cp h2-*.jar org.h2.tools.Script -url jdbc:h2:./metabase.db -script metabase.db.sql

echo DONE
```

**metabase-db-clean.sql**:
```
SET DB_CLOSE_DELAY -1;
DELETE FROM "PUBLIC"."TASK_HISTORY";
DELETE FROM "PUBLIC"."ACTIVITY" WHERE "TOPIC" != 'install';
DELETE FROM "PUBLIC"."QUERY_EXECUTION";
```

3. After it I commit metabase.db.sql to the repo

4. When I need to up metabase from docker I just create database from sql like this:

**Dockerfile** (`docker build . -t local/metabase`)
```
FROM metabase/metabase:v0.34.1

# H2_VERSION is related to metabase version!
# In case of update Metabase version and get the error "NonTransientError: Unable to read the page at position”
# increase or decrease H2 version.
ARG H2_VERSION=2019-03-13

RUN mkdir -p /data
ADD metabase.db.sql /data
RUN cd /data \
  && wget https://h2database.com/h2-$H2_VERSION.zip \
  && unzip h2-$H2_VERSION.zip \
  && cp h2/bin/h2-*.jar ./ \
  && rm -r h2 h2*.zip \
  && java -cp h2*.jar org.h2.tools.RunScript -url jdbc:h2:./metabase.db -script metabase.db.sql

```
**docker-compose.yml**:
```
version: '3'
services:
  metabase:
    image: local/metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /data/metabase.db
```
It works perfect :)

**Comment by wherget** [comment]
As an addendum to @anki-code 's workaround, there's not even a need to download h2, as all the tools are already included in the `metabase.jar` in the docker image. There's also a provision (as of me writing this) to automatically initialize from an `/app/initial.mv.db` H2 on startup. I have a writeup of preliminary support for `/docker-entrypoint-initdb.d/`, but I'd have to clear whether I can publish/PR that. This is pretty much the gist of it:

```sh
cat /docker-entrypoint-initdb.d/*.sql | \
  java -cp /app/metabase.jar org.h2.tools.RunScript -url jdbc:h2:/app/initial -script "/dev/stdin"
```

However, initializing from H2 feels very inelegant. You can't update an already running instance from it, only overwrite it. It's not really human-readable let alone editable even in SQL-serialized form. The enterprise serialization feature seems to go in the right direction from what I can tell (although an example export somewhere might be nice to see if it's worth the 10 grand a year...).

What I would like to do with such a feature is to describe the schema of the underlying database in a human-editable form. Especially foreign key configuration, which is usually only tracked on the application layer (via ORM or somesuch) and not in the database where I rearely see `FOREIGN KEY` constraints in the schema. Column visibility and Column naming would be another thing. These are items which are application-specific, and I think metabase could benefit a lot from the ability to import such "application profiles". You just additionally supply a database connection string and hey presto, instant analytics. (Or maybe an error along the lines of "Hey, that doesn't look like it fits the application profile...")

**Comment by anki-code** [comment]
@wherget JFYU I've made docker file that saves/restores the database to/from SQL-file automatically - [metabase-sql-wrapper](https://github.com/anki-code/metabase-sql-wrapper) 🎉

**Comment by kp2401075** [comment]
I'm currently facing issue where metabolise is not displaying data correctly from MongoDB for specific Table.
If this options was present I would have exported the configuration replaced old table name with new table name and imported it back in.

This would specially be help full when running met abase  in docker where getting into container and diagnosing is bit more involved.


Here is link to my other issue.
https://github.com/metabase/metabase/issues/14916
if any of you have encountered and managed to resolve this sort of issue. please help

**Comment by camsaul** [comment]
Discussed today, we'll probably go with a YAML config file with some sort of `{{template}}` syntax that will support using env vars as well, perhaps like the way they're done in [`dbt` config files](https://docs.getdbt.com/reference/dbt-jinja-functions/config):

```yaml
target: dev
  outputs:
    dev:
      type: snowflake
      account: hra02712.us-east-1

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
```

**Comment by camsaul** [comment]
Also under consideration: supporting specifying Settings in a YAML file as well. Whether this is the same YAML file as the first user/data warehouses or not is an open question -- TBD
