### ISSUE TITLE
which branch or tags match the lastest version of metabase.jar which is 0.42

### ISSUE THREAD

**Issue by tuoqiao** [metabase/metabase#20546]
For help with installation and setup, information on how specific features work, or general questions about Metabase, please use our discussion forum:

https://discourse.metabase.com

The Github issue tracker is intended to collect bug reports and feature requests.
Any issues open for help requests will be closed to keep from clogging up the issue tracker.

**Comment by tuoqiao** [comment]
if the tags 0.42 is the lastest version of metabase.jar ,then why not 1.42

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

https://github.com/metabase/metabase/tree/v0.42.0 and https://github.com/metabase/metabase/tree/release-x.42.x
