### ISSUE TITLE
Upgrade Liquibase

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20600]
I think we need to tackle this first before we can tackle #20599. There are a few issues making upgrading hard:

1. Upstream changes in H2 that mean unquoted `TABLE` and `VALUES` can't be used anymore as identifiers in CREATE TABLE statements. See https://github.com/h2database/h2database/issues/1719#issuecomment-474762002 
2. The version of Liquibase we were using did not quote these newly-reserved keywords when using the `LEGACY` quoting strategy -- this was (somewhat) fixed in https://github.com/liquibase/liquibase/pull/949
3. We can't use the `QUOTE_ALL_OBJECTS` strategy with H2 because it doesn't quote 
table names when adding foreign keys -- see upstream Liquibase bug https://liquibase.jira.com/browse/CORE-3073 (also tracked at https://github.com/liquibase/liquibase/issues/1982)
4. Using the latest version of Liquibase to get the fix in # 2 breaks other things for us because what was once the `VALUES` column is now created as `values` (the case has changed) -- see my comment here https://github.com/liquibase/liquibase/pull/949#issuecomment-896308521
5. Liquibase 4.x also doesn't work with Log4j so just spams log messages everywhere (see https://github.com/apache/logging-log4j2/pull/503)

See #16086 for an attempt at this.

I think we need to write a custom Liquibase quoting strategy that upper-cases and then quotes all H2 identifiers... not sure this is even possible but if it was it would solve our problems I think.

**Comment by camsaul** [comment]
Implementing this has been a journey to say the least.

- I ran in to https://github.com/liquibase/liquibase/issues/1982, and fixed this by rewriting most if not all of our migrations
- I ran in to https://github.com/apache/logging-log4j2/pull/503, and worked around this like this https://github.com/metabase/metabase/pull/20611/files#diff-7b84b53f388126bbf994fbdb5b705a6eefeaf0999da00dc45a40a6559f85ac30R23-R28
- I wrote a custom `H2Database` implementation to work around so we could uppercase-and-quote all H2 identifiers
- I ran in to https://github.com/liquibase/liquibase/issues/2396, and worked around it with https://github.com/liquibase/liquibase/issues/2396#issuecomment-1064430955
- I ran in to https://github.com/liquibase/liquibase/issues/2633, and worked around it like this https://github.com/liquibase/liquibase/issues/2633#issuecomment-1065343648
- I ran in to https://github.com/liquibase/liquibase/issues/2634, and still haven't figured out how to work around it

At this point I'm starting to wonder if updating Liquibase is actually a good idea after all

**Comment by kflorian** [comment]
I ran into the same problem with quoted H2 keywords in column names. In our case, hibernate was using the unquoted names, so quoting everything in Liquibase was not an option.
My solution was also a custom H2Database implementation:
```java
package com.mycorp.liquibase;

import java.util.Locale;
import java.util.Set;

import liquibase.database.core.H2Database;

public class CustomH2Database extends H2Database {
    private static final Set<String> NON_KEYWORDS = Set.of("VALUE", "KEY");

    @Override
    public boolean isReservedWord(final String objectName) {
        if (NON_KEYWORDS.contains(objectName.toUpperCase(Locale.US))) {
            return false;
        }
        return super.isReservedWord(objectName);
    }

    @Override
    public int getPriority() {
        return super.getPriority() + 1;
    }
}
```

This needs then to be referenced in META-INF/services/liquibase.database.Database:
```
com.mycorp.liquibase.CustomH2Database
```

We also disabled special-handling of those keywords in the H2 library (version 2.x) via the JDBC URL:
```
jdbc:h2:file:./target/h2-db/mydb;NON_KEYWORDS=KEY,VALUE
```

Hope that helps!
