### ISSUE TITLE
Need 2x1 width card in dashboard

### ISSUE THREAD

**Issue by chendanli** [metabase/metabase#20612]
**Is your feature request related to a problem? Please describe.**
Now text card in dashboard are restricted to 4x1，2x1 will be ideal.

**Describe the solution you'd like**
Free to use a column width that is smaller than 4x1.

**Additional context**
![1MicrosoftTeams-image](https://user-images.githubusercontent.com/92294741/154615396-0f5091b8-75f4-4543-a39b-626a2937d1f3.png)

**Comment by flamber** [comment]
Duplicate of #8475
