### ISSUE TITLE
Deletion/Retiring UX should be more consistent

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2061]
We have several different UIs for deleting or retiring objects:
- Database: type "DELETE", click "Delete" or "Cancel"
- Card/Dashboard: Click "Yes"/"No"
- Pulse: checkbox to confirm each channel it will no longer be sent to, click "Delete this pulse"
- Metric/Segment: provide a written reason, click "Retire"

**Comment by tlrobinson** [comment]
Also the pulse delete modal (`DeleteModalWithConfirm`) is currently squished:
<img width="697" alt="screenshot 2016-02-29 21 47 55" src="https://cloud.githubusercontent.com/assets/18193/13418970/4ebc1f44-df2f-11e5-9241-c380e1036d1c.png">

**Comment by brunobergher** [comment]
I think most of these (all?) are out of date, closing.
