### ISSUE TITLE
Autocomplete suggestions are not working for most of the database tables

### ISSUE THREAD

**Issue by bonaventura-elder** [metabase/metabase#20625]
**Describe the bug**
Since updating to v0.42, the autocomplete suggestions have stopped working for the great majority of the tables. 

Only a limited number of tables are suggested by the autocomplete, ignoring tables with a closer match to the typed-in letters.

This behaviour only seems to affect the autocomplete functionality. In fact all tables are accessible if the table name is typed in full and they are displayed correctly in the "learn about your data" tab.

**Logs**
There is no indication in the logs that anything is behaving different than normal.

**To Reproduce**

1. Go to Metabase
2. Start typing the name of a table
3. Waiting for the (partially) matched table name to show up in the autocomplete window
4. Not seeing the table name (or similar table names) appear

**Expected behaviour**

Start typing the table name and getting suggestions that match the partial table name. 

**Screenshots**
See the screenshot below

**Information about your Metabase Installation:**

Metabase version: 0.42, self hosted under Docker / Kubernetes

**Severity**
Currently slowing down company workflows, as table names have to be looked up each time.

![Screenshot 2022-02-18 at 12 50 25](https://user-images.githubusercontent.com/80323492/154686384-cf265f24-30a7-4e98-b37a-460c470d1370.png)

**Comment by flamber** [comment]
Hi @bonaventura-elder 
There weren't any changes to the autocomplete in 0.42.0, though there were changes in 0.41.3 #16736
Easily reproducible with Oracle 11g's massive default APEX

0.41.2:

https://user-images.githubusercontent.com/1447303/154711132-1c650a67-3bcb-43d2-bac2-cb3943b214be.mp4

0.41.3:

https://user-images.githubusercontent.com/1447303/154711171-4f1e7efd-05e4-4606-bce0-1cd266ce01f2.mp4
