### ISSUE TITLE
Static waterfall default colors are invalid

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#20621]
**Describe the bug**
Default colors of the static waterfall chart are invalid.

**To Reproduce**
1. Create a waterfall chart without explicitly specifying colors 
2. Add it on a dashboard and send a subscription

**Screenshots**
<img width="641" alt="Screenshot 2022-02-18 at 11 44 25" src="https://user-images.githubusercontent.com/14301985/154677196-6780f3a3-d780-4d45-850c-ca8866e4f83a.png">

**Information about your Metabase Installation:**

Latest `master`

**Comment by nemanjaglumac** [comment]
Would you expect greens and reds, like this:
![image](https://user-images.githubusercontent.com/31325167/154695869-f005ce2c-1f9d-4bf9-88e5-af556d6f3f0e.png)

**Comment by losrebellos** [comment]
@alxnddr 

What are the expected colors?
Following your instructions, I ended with:
![image](https://user-images.githubusercontent.com/348552/156782660-7d8aef26-fadd-4e17-9aab-065218c3a93c.png)

**Comment by alxnddr** [comment]
@losrebellos, these are the correct colors. Also, negative bars should look like on Nemanja's screenshot. Maybe @howonlee has already fixed this bug? It was a back-end problem

**Comment by WiNloSt** [comment]
This is what I got, so I don't think the problem has been fixed yet.

#### Dashboard
![image](https://user-images.githubusercontent.com/1937582/183061690-ab13b06b-e518-4d19-bc74-1f27c389243a.png)

#### Email
![image](https://user-images.githubusercontent.com/1937582/183061750-80bb46e4-a235-40cd-b170-a0809f455e36.png)
