### ISSUE TITLE
Creating a new dashboard from the New button in a collection should take me to that dashboard

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#20638]
- Go to a collection
- Click the plus button, then choose Dashboard
- Name your dashboard and create it
- You should end up on the new dashboard in its edit mode, but you incorrectly stay in the collection

Reproduced here:
https://www.loom.com/share/91072a7309b044e19c76e9f46fdc16dc

Calling it a P2 since it's likely a very common action, and and is quite confusing and annoying. But I'd understand if we downgrade it to a P3, as this behavior doesn't happen from the New menu in the top nav, and doesn't block dashboards from being created.

**Comment by flamber** [comment]
Should the same thing happen when creating a new collection, which has similar behavior on :heavy_plus_sign: vs New?

**Comment by mazameli** [comment]
> Should the same thing happen when creating a new collection, which has similar behavior on ➕ vs New?

I think the current behavior when creating a new collection from the `New` menu in the top nav makes sense, because you could be anywhere in the app — so it feels right to go to that new collection.

But when using the + button in the collection, my instinct is that you're often creating that new collection with the intent of moving items in the _current_ collection into that new one, and you get the immediate feedback of seeing the new collection appearing in the sidebar — so I don't think it feels right to take you to the new collection in that scenario. I have conviction of maybe 75% on that.
