### ISSUE TITLE
Auto split y-axis setting is way too aggressive

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#20639]
Explanation: https://www.loom.com/share/0e21c389f1a5473ba8fafd80ecdd7d9e

To repro:
- New question, Orders
- Summarize, and pick the Minimum of Quantity and the Average of Quantity, broken out by Created At: Month
- Visualize
- See that the y-axis is unnecessarily split automatically

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/2223916/154770568-9fa0f897-8ba0-4d9c-9616-48914fe447c2.png">

## What should we do about this?

This behavior of automatically splitting the axis feels like it's only really useful if the metrics' maximum values are at least 1 order of magnitude apart, e.g. 10 vs 100

Even then, I'm not sure I'm convinced that this setting should be on by default. See https://github.com/metabase/metabase/issues/3897 for at least one user saying that this setting is confusing.

This is like a P1.5 to me: it doesn't block functionality, but it's more than annoying: it legitimately caused me to misinterpret results on an important chart on our Stats instance for a whole week.

**Comment by flamber** [comment]
Just for searchability, the setting name is `Use a split y-axis when necessary`
Same as #12939

The fix for this should continue to split different types/currencies, example:
![image](https://user-images.githubusercontent.com/1447303/154799153-039641c4-ed51-421e-b6bc-c5afdcbea23e.png)

**Comment by mazameli** [comment]
Thanks, @flamber. We can close this as a duplicate if you want to then.

**Comment by flamber** [comment]
Copied everything over and updated #12939

**Comment by atygl** [comment]
We started to experience this issue in 0.47.0 again. 
Can you please reopen the ticket?

**Comment by Limess** [comment]
We've also started seeing this since upgrading to 0.47.0
