### ISSUE TITLE
Metabase on heroku production database, data safety

### ISSUE THREAD

**Issue by eoinmurray** [metabase/metabase#2063]
I have a production database on Heroku with daily backups.

Since the backups are not connected to a live database, metabase cannot connect to them. 
Am I able to connect metabase to my live database, but make the metabase-db connection read only?
I want it to be that I cannot execute a delete or drop statement on the database from the metabase sql editor.

I am unsure from the documentation if this is possible.

**Comment by agilliland** [comment]
Yes, you can use a read-only connection with Metabase just fine.  The application doesn't have any code which attempts to write to a database or modify any of its contents, it's purely used for pulling data via queries right now.

**Comment by eoinmurray** [comment]
Is there a way to specify the read only connection within Metabase itself, or would I need to specify the user role in postgres?

**Comment by agilliland** [comment]
You should do that via the postgres user role.
