### ISSUE TITLE
"Compare to the rest" action in drill-through menu looks busted

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#20641]
Repro:
- New question, Orders
- Count of rows by anything — let's use Product.Category
- Click on a bar to open the drill-down menu
- Observe how "Compare to the rest" looks like a sliced kielbasa sausage:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/2223916/154779558-e8145491-22ee-44d1-a7d7-e914d5ac3ad0.png">

P2 because it makes things look broken and unreliable in a high-traffic area.

**Comment by kulyk** [comment]
Most likely a regression since #20101
