### ISSUE TITLE
Metabase Dashboard Layout

### ISSUE THREAD

**Issue by xxyjoel** [metabase/metabase#2064]
If this is a bug report, please fill in the blanks:

*  I am using the chrome, edge, firefox and IE browser.
*  My computer's OS is Windows 10 on Surface pro 3.
*  My database is AWS.
*  My Metabase version is 0.14.01.

When selecting any dashboard overview, I am not able to reformat the cells/tables/graphs/etc. (his include re-sizing and re-positioning) rendering the dashboard view seemingly useless.

**Comment by tlrobinson** [comment]
@xxyjoel Could you give 0.15 a try and see if this is still an issue?

**Comment by xxyjoel** [comment]
Success! :)
