### ISSUE TITLE
Admin Permissions page not showing scrollbars

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20655]
**Describe the bug**
Only on master.
Admin Permissions page not showing scrollbars, which makes it difficult to work with.

**To Reproduce**
1. Admin > People > Groups - create 100 groups
2. Go to Admin > Permissions
![image](https://user-images.githubusercontent.com/1447303/154846434-cc2948cc-a237-4fea-9ac3-d609e7a4e0c9.png)

**Expected behavior**
0.42.1 shows scrollbars
![image](https://user-images.githubusercontent.com/1447303/154846508-de26bf37-5853-4951-99ee-00b0242614cb.png)

**Information about your Metabase Installation:**
Tested master `f5062ad`

**Comment by nemanjaglumac** [comment]
Can't reproduce this locally.
I'm also on `master` and I tried both with a fresh instance of app db, and with the existing one I had from before. I can see the scrollbar in Brave, Chrome and Firefox. It's there also when I run Cypress.

**Comment by flamber** [comment]
Fixed by #20640
