### ISSUE TITLE
Provide an option to encrypt unencrypted settings

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20658]
**Is your feature request related to a problem? Please describe.**
Many users start their deployments with just the bare basics and after some time they realize that they can encrypt data at rest with MB_ENCRYPTION_SECRET_KEY but it's now late, as what's in unencrypted will remain like that forever (you could do some open heart surgery at the DB level replacing references but that's not recommended at all).

**Describe the solution you'd like**
Provide an option to encrypt what's unencrypted with the MB_ENCRYPTION_SECRET_KEY once the env var is enabled.

**Describe alternatives you've considered**
Add the DB again and change references in the DB, which is not recommended at all

**How important is this feature to you?**
Important for sysadmins

**Additional context**
NA

**Comment by paoliniluis** [comment]
Another workaround: use serialization to dump and load into the same instance but with different names (databases, questions, dashboards) so Metabase writes the values encrypted this time

**Comment by flamber** [comment]
This is already supported: https://www.metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html#key-rotation

Also if you don't do rotation, then the existing unencrypted values will not remain like that forever, but until the setting or database are re-saved, then Metabase will replace the unencrypted value with an encrypted value.
So an alternative to doing rotation would be to re-save all settings and database connections.
