### ISSUE TITLE
Serialization dumps and loads questions with invalid references

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20657]
**Describe the bug**
If you save a question in a personal collection and then use that question as the base for another one which is included in a shared collection, then serialization will error with
```
Unresolved references found for cards in collection null; will reload after first pass
"People, Count, Grouped by Source" (inserted as ID 1) missing:
  at :dataset_query/:query/:source-table -> /collections/root/collections/a b%27s Personal Collection/cards/People
```
as personal collections aren't dumped,

It will create the questions in the end, but empty and just with a nice comment which is "-- DUMMY QUERY FOR SERIALIZATION FIRST PASS INSERT"

**Logs**
<details>
2022-02-21 00:50:32,523 WARN serialization.names :: #error {
 :cause Value does not match schema: {:card (not (integer? nil))}
 :data {:type :schema.core/error, :value {:collection 1, :card nil}, :error {:card (not (integer? nil))}}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Can't resolve collection, card in fully qualified name /collections/root/collections/a b%27s Personal Collection/cards/People
   :data {:fully-qualified-name /collections/root/collections/a b%27s Personal Collection/cards/People, :resolve-name-failed? true, :context {:collection 1, :card nil}}
   :at [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invokeStatic names.clj 325]}
  {:type clojure.lang.ExceptionInfo
   :message Value does not match schema: {:card (not (integer? nil))}
   :data {:type :schema.core/error, :value {:collection 1, :card nil}, :error {:card (not (integer? nil))}}
   :at [metabase.util.schema$schema_core_validator$fn__18071 invoke schema.clj 29]}]
 :trace
 [[metabase.util.schema$schema_core_validator$fn__18071 invoke schema.clj 29]
  [schema.core$validate invokeStatic core.clj 164]
  [schema.core$validate invoke core.clj 159]
  [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invokeStatic names.clj 321]
  [metabase_enterprise.serialization.names$fully_qualified_name__GT_context invoke names.clj 299]
  [metabase_enterprise.serialization.load$source_table invokeStatic load.clj 67]
  [metabase_enterprise.serialization.load$source_table invoke load.clj 63]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invokeStatic core.clj 669]
  [clojure.core$apply invoke core.clj 662]
  [medley.core$update_existing_in$up__5519 invoke core.cljc 73]
  [medley.core$update_existing_in invokeStatic core.cljc 75]
  [medley.core$update_existing_in doInvoke core.cljc 63]
  [clojure.lang.RestFn invoke RestFn.java 445]
  [metabase_enterprise.serialization.load$update_capture_missing_STAR_ invokeStatic load.clj 81]
  [metabase_enterprise.serialization.load$update_capture_missing_STAR_ invoke load.clj 78]
  [metabase_enterprise.serialization.load$update_existing_capture_missing invokeStatic load.clj 97]
  [metabase_enterprise.serialization.load$update_existing_capture_missing invoke load.clj 95]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437$fn__82450$fn__82451$fn__82452$fn__82455 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437$fn__82450$fn__82451$fn__82452 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437$fn__82450$fn__82451 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437$fn__82450 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437 invoke load.clj 152]
  [metabase.mbql.util.match.impl$replace_in_collection$iter__27406__27410$fn__27411 invoke impl.cljc 44]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.Cons next Cons.java 39]
  [clojure.lang.RT next RT.java 713]
  [clojure.core$next__5403 invokeStatic core.clj 64]
  [clojure.core.protocols$fn__8181 invokeStatic protocols.clj 169]
  [clojure.core.protocols$fn__8181 invoke protocols.clj 124]
  [clojure.core.protocols$fn__8136$G__8131__8145 invoke protocols.clj 19]
  [clojure.core.protocols$seq_reduce invokeStatic protocols.clj 31]
  [clojure.core.protocols$fn__8168 invokeStatic protocols.clj 75]
  [clojure.core.protocols$fn__8168 invoke protocols.clj 75]
  [clojure.core.protocols$fn__8110$G__8105__8123 invoke protocols.clj 13]
  [clojure.core$reduce invokeStatic core.clj 6830]
  [clojure.core$into invokeStatic core.clj 6897]
  [clojure.core$into invoke core.clj 6889]
  [metabase.mbql.util.match.impl$replace_in_collection invokeStatic impl.cljc 43]
  [metabase.mbql.util.match.impl$replace_in_collection invoke impl.cljc 38]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437$fn__82450$fn__82451$fn__82452$fn__82455 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437$fn__82450$fn__82451$fn__82452 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437$fn__82450$fn__82451 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437$fn__82450 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_$replace_82436__82437 invoke load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_ invokeStatic load.clj 152]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids_STAR_ invoke load.clj 150]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids invokeStatic load.clj 180]
  [metabase_enterprise.serialization.load$mbql_fully_qualified_names__GT_ids invoke load.clj 178]
  [clojure.core$update invokeStatic core.clj 6185]
  [clojure.core$update invoke core.clj 6177]
  [metabase_enterprise.serialization.load$resolve_card invokeStatic load.clj 598]
  [metabase_enterprise.serialization.load$resolve_card invoke load.clj 594]
  [metabase_enterprise.serialization.load$load_cards$iter__82875__82879$fn__82880$fn__82881 invoke load.clj 632]
  [metabase_enterprise.serialization.load$load_cards$iter__82875__82879$fn__82880 invoke load.clj 631]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.lang.LazilyPersistentVector create LazilyPersistentVector.java 44]
  [clojure.core$vec invokeStatic core.clj 379]
  [clojure.core$vec invoke core.clj 369]
  [metabase_enterprise.serialization.load$load_cards invokeStatic load.clj 641]
  [metabase_enterprise.serialization.load$load_cards invoke load.clj 624]
  [metabase_enterprise.serialization.load$load_cards$fn__82902 invoke load.clj 660]
  [metabase_enterprise.serialization.load$make_reload_fn$fn__82931$iter__82932__82936$fn__82937$fn__82938 invoke load.clj 715]
  [metabase_enterprise.serialization.load$make_reload_fn$fn__82931$iter__82932__82936$fn__82937 invoke load.clj 714]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.core$seq__5419 invokeStatic core.clj 139]
  [clojure.core$filter$fn__5911 invoke core.clj 2813]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.core$seq__5419 invokeStatic core.clj 139]
  [clojure.core$seq__5419 invoke core.clj 139]
  [metabase_enterprise.serialization.load$make_reload_fn invokeStatic load.clj 711]
  [metabase_enterprise.serialization.load$make_reload_fn invoke load.clj 709]
  [metabase_enterprise.serialization.load$make_reload_fn$fn__82931 invoke load.clj 714]
  [metabase_enterprise.serialization.cmd$fn__86713$load__86718$fn__86719 invoke cmd.clj 61]
  [metabase_enterprise.serialization.cmd$fn__86713$load__86718 invoke cmd.clj 39]
  [clojure.lang.Var invoke Var.java 388]
  [metabase.cmd$load invokeStatic cmd.clj 149]
  [metabase.cmd$load doInvoke cmd.clj 140]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [metabase.cmd$load invokeStatic cmd.clj 144]
  [metabase.cmd$load invoke cmd.clj 140]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.RestFn applyTo RestFn.java 132]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$apply invoke core.clj 662]
  [metabase.cmd$run_cmd$fn__83228 invoke cmd.clj 190]
  [metabase.cmd$run_cmd invokeStatic cmd.clj 190]
  [metabase.cmd$run_cmd invoke cmd.clj 186]
  [clojure.lang.Var invoke Var.java 388]
  [metabase.core$run_cmd invokeStatic core.clj 141]
  [metabase.core$run_cmd invoke core.clj 139]
  [metabase.core$_main invokeStatic core.clj 163]
  [metabase.core$_main doInvoke core.clj 158]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [metabase.core main nil -1]]}
2022-02-21 00:50:32,530 INFO serialization.upsert :: Updating Card "People, Count, Grouped by Source" (ID 1)
2022-02-21 00:50:32,537 INFO serialization.load :: Unresolved references found for cards in collection null; will reload after first pass
"People, Count, Grouped by Source" (inserted as ID 1) missing:
  at :dataset_query/:query/:source-table -> /collections/root/collections/a b%27s Personal Collection/cards/People
</details>

**To Reproduce**
1. Have a source and destination Metabase instances
2. Create a question in the source and save it on the personal collection then create a question based on the first question but save it on a shared collection
3. dump on the source and load on destination, see the error

**Expected behavior**
At least capture the error nicely in the logs and maybe also change the comment in the code so the users see what happened. We could also add the behavior of not updating objects that don't have a valid reference.

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: H2
- Metabase version: 1.41.2
- Metabase hosting environment: Docker
- Metabase internal database: H1

**Severity**
Non severe

**Additional context**
NA

**Comment by paoliniluis** [comment]
Includes cards that use archived cards as well

**Comment by camsaul** [comment]
This is SerDes v1 related, we can close this out once we sunset SerDes v1 if it's not closed out by then
