### ISSUE TITLE
MongoDB driver syncs databases with a deprecated/non-existent collection. Update the MongoDB method used for sync

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20664]
**Describe the bug**
In the driver we use [system.indexes](https://github.com/metabase/metabase/blob/92d10d406503e1004c2b62f8f26b9ed7f6ef10fa/modules/drivers/mongo/src/metabase/driver/mongo.clj#L178) to describe the database, but that's deprecated according to [MongoDB documentation](https://docs.mongodb.com/manual/reference/system-collections/#mongodb-data--database-.system.indexes)

**Logs**
Metabase does not return any logs there, for unknown reasons

**To Reproduce**
NA

**Expected behavior**
Use a supported method for describing databases

**Screenshots**
NA

**Information about your Metabase Installation:**
NA

**Severity**
NA

**Additional context**
NA

**Comment by camsaul** [comment]
The dox mention that this was removed in MongoDB 4.2, but we've been testing against MongoDB 5.0 for years now -- so it's not clear why this still works. Either way, we should switch to a method that isn't deprecated, since there is no telling when this will stop working in the future.

**Comment by snoe** [comment]
@paoliniluis the linked [line of code](https://github.com/metabase/metabase/blob/92d10d406503e1004c2b62f8f26b9ed7f6ef10fa/modules/drivers/mongo/src/metabase/driver/mongo.clj#L178) in OP is actually making sure we do NOT sync `system.indexes` (`disj` removes it from the collection names mongo returns). So I believe it is doing the correct thing here.

**Comment by snoe** [comment]
confirmed with @paoliniluis
