### ISSUE TITLE
Ability to filter JSON field in Postgres with text cast

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#20669]
Currently, it's impossible to filter json field.
Before json driver implementation #708 can you cast json fields to text (ex: `"data"::TEXT ILIKE '%test%'`) to allow a first filter of json fields ?
[Postico](https://eggerapps.at/postico/) use this trick and it's a good first option to take charge json fileds

**Comment by flamber** [comment]
You can use Custom Column `concat([json_field], "")`. https://www.metabase.com/docs/latest/users-guide/expressions.html
But we're working on JSON support: https://www.metabase.com/roadmap/
Closing in favor of #708
