### ISSUE TITLE
Error when filtering date by current quarter in Postgres

### ISSUE THREAD

**Issue by stijnbe** [metabase/metabase#20683]
**Describe the bug**
When filtering by current quarter on a Postgres database the following error appears:
`ERROR: invalid input syntax for type interval: "1 quarter" Position: 1550`

**Logs**
[metabase.log](https://github.com/metabase/metabase/files/8119658/metabase.log)

**To Reproduce**
1. Create any regular question 
2. Create a filter using a date and filter by current quarter

**Expected behavior**
Filter by current quarter is actually filtering instead of giving an error

**Screenshots**
<img width="486" alt="image" src="https://user-images.githubusercontent.com/159423/155204725-6acc9ae0-3c18-4970-8b7a-04bb77719bf0.png">

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.9.43-17.39.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-17",
      "tag": "v0.42.1",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
Only way to work around this right now is to create native queries. We use quarterly queries quite often.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by paoliniluis** [comment]
Cannot reproduce with sample dataset (H2) or MySQL, but I can with Postgres

**Comment by rcronin** [comment]
It's currently generating this:

`WHERE ("date" >= date_trunc('quarter', CAST((CAST(now() AS timestamp) + (INTERVAL '-3 quarter')) AS timestamp))
   AND "date" < date_trunc('quarter', CAST(now() AS timestamp)))`

**Comment by flamber** [comment]
Postgres doesn't support quarters in intervals, so it would require some manual processing: https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT
