### ISSUE TITLE
Filter by time in addition to date

### ISSUE THREAD

**Issue by etlweather** [metabase/metabase#2069]
I have a few fields in a PostgreSQL database table which are `timestamp without time zone`. Metabase detected them as DateTime in the data model. However, when I create a question, I can only filter this field by Date, I can't specify a time.

**Comment by etlweather** [comment]
Nice tool by the way!

**Comment by salsakran** [comment]
@etlweather are you thinking in terms of time of day, or something like "everything since 5pm on 12/12/2012"?

**Comment by etlweather** [comment]
Here are various queries my users would want to run:

 - Count of X with date between Monday 5PM and Tuesday 5PM.
 - Count of X in the last hour.
 - Count of X grouped by hour, today.

**Comment by salsakran** [comment]
this has been made possible in #3750
