### ISSUE TITLE
Data missing in downloaded xlsx or csv or json file

### ISSUE THREAD

**Issue by mustaqansari** [metabase/metabase#20719]
Some people using metabase are facing issues with downloading the questions.

They do not get any data in the downloaded files
![Screenshot 2022-02-24 at 4 19 45 PM](https://user-images.githubusercontent.com/65239076/155537592-b53aa598-db2e-4914-9c46-34bb4e68ce06.png)
.

**Comment by flamber** [comment]
Make sure you're using latest release: https://github.com/metabase/metabase/releases/latest
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
