### ISSUE TITLE
"Our analytics" can be confusing when user does not have access to that collection

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20716]
**Describe the bug**
"Our analytics" can be confusing when user does not have access to that collection.

**To Reproduce**
1. Admin > Permissions > Collections - set "Our analytics" to `No access` for All Users
2. Login as user
3. The homepage should probably not show the `Your teams’ most important dashboards go here` (this is new in 0.42) and perhaps not show the text `Access dashboards, questions, and collections in "Our analytics"`
![image](https://user-images.githubusercontent.com/1447303/155518298-b317bcca-5563-4f28-9a69-5ad6a10666fa.png)
4. Click "Browse all items" - that will take you to collections hierarchy page, but it should probably hide the "Our analytics" in the sidebar and auto-select the first available collection by default:
![image](https://user-images.githubusercontent.com/1447303/155518684-7e517dda-d80e-4c61-af94-c9ac3e285a14.png)
Example with a few collections available to the user:
![image](https://user-images.githubusercontent.com/1447303/155518929-24b64288-db1c-41d4-95a9-6f8a13c3ea04.png)

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.1

**Additional context**
Related to #19070 and #8747

**Comment by kulyk** [comment]
This requires both frontend and backend work. For non-root collections, the BE responds with `403` on `GET /api/collection/:id`. However, it returns `200` for `GET /api/collection/root` even if a user doesn't have permission to it at all (aka "No access" permission). At the same time, the FE can't distinguish the "View" and "No access" permissions for the root collection. Perhaps we should better do #19070 and close this issue together with it

**Comment by nemanjaglumac** [comment]
This issue became much worse with the addition of some features from v43.
The existence of "Our analytics" is not only confusing, but it also leads user to some dead-end pages and it prompts one to perform actions which they are not allowed to.

This is how `/collection/root` looks for a user with no access now:
![image](https://user-images.githubusercontent.com/31325167/178264314-ec1fa44c-8ebd-42fa-84e0-bfea49a08d21.png)

1. It prompts you to click on events (which is not allowed) and only leads to weird errors and empty modals
2. It also completely unnecessarily sends requesst to:
    - `/api/collection/root/timelines` - returns 200 (wrong)
    - `api/timeline/1?include=events`which (correctly) returns 403
3. It prompts you to create new:
    - Dashboard (ok)
    - Collection (can result in a weird state error and a blank page in production!)
    
This is how it looks like in the local dev environment:
![image](https://user-images.githubusercontent.com/31325167/178265424-e62944d5-427b-4608-87bc-f8d1b1f2bbbc.png)

Clicking on events:
![image](https://user-images.githubusercontent.com/31325167/178265637-39592b3a-5bf8-462a-bd9d-b3550a4de1e0.png)

**Comment by calherries** [comment]
I've closed this PR and created a separate issue for the last screenshot in my comment above.

**Comment by nemanjaglumac** [comment]
Note to @calherries and probably to @luizarakaki or @brunobergher 

This issue was planned for the end of 43 cycle. We're already in the next cycle and will most likely not issue another 43.x release.
Should this be moved to the 44 cycle Project? If so, https://github.com/metabase/metabase/issues/23981 needs to be backported.

**Comment by calherries** [comment]
@nemanjaglumac Yes, it should have been backported to 44. Here's the backport PR https://github.com/metabase/metabase/pull/24048
