### ISSUE TITLE
Enhance serialization logs

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20725]
**Describe the bug**
Some lines of the serialization process don't give information to see what's going on. E.g:
1) Inserting FieldValues: which field is this line refererred to?
2) Inserting field and FieldValues: can this be linked in order to reduce lines?
3) Inserting DashboardCard: which card, on which position?
4) Inserting Dependency: which dependency?

Some items give more info than needed. E.g:
- If the process can't resolve a collection, we not only get the exception and the via, but also the trace. We only need the :via, and maybe the trace to be enabled via log4j parameters

On any other error: which object are we talking about? 

**Logs**
NA, will try to annotate them and then share it

**To Reproduce**
NA

**Expected behavior**
Have a better error logging 

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your operating system: Ubuntu 21.10
- Your databases: Postgres 10
- Metabase version: 1.41.2
- Metabase hosting environment: Ubuntu
- Metabase internal database: Postgres 14

**Severity**
For people using serialization everyday, this is serious

**Additional context**
NA

**Comment by luizarakaki** [comment]
Improvements to Serdes v2 logs:

Currently, the `dump` and `load` commands are silent. We can add:

- We can have a nice progress bar. From the `dump` and `load` start, we know how many files we need to process, so we can evaluate progress.
- A description of what is being dumped/loaded.
- Error messages: dependency not found, invalid file, etc
