### ISSUE TITLE
Allow Native Queries for Mongo

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2072]
Right now we only allow native SQL queries. This was initially because hand rolling druid or mongo query dictionaries didn't seem like something people would do. 

This issue is meant to gauge community interest in being able to paste and reuse raw mongo/druid queries. Please chime in if this is something you would actually use, and if possible give us a sense of the use case and why the query builder wasn't doing it for you!

**Comment by dcoueron** [comment]
+1 on this.
Or even better : it would be great if could write SQL-like queries for Druid using libraries like [PlyQL](https://github.com/implydata/plyql)

**Comment by toszter** [comment]
Please include the ability to run custom MongoDB queries in Metabase....OR at the least, point me in the right direction on any implementation notes/requirements/PRD you have on the subject, and I'll take a stab at it and contribute back.  We have a deep need for this in our business. Thanks for creating metabase!  It's wonderful.

**Comment by lukemcintyre** [comment]
+1 for this. Any idea on timeframes? Mongo support is really great so far guys, good stuff!

**Comment by edmarriner** [comment]
This would be huge for us!

**Comment by agilliland** [comment]
@edmarriner which database specifically?

**Comment by agilliland** [comment]
For folks using Mongo, what is your expected format for inputting the queries?  We are looking at doing this via Mongo Aggregation Pipelines, would that work?  https://docs.mongodb.org/manual/core/aggregation-pipeline/

So this would be a JSON based input.  Thoughts?

**Comment by toszter** [comment]
YES! to aggregation pipelines. They're the best solution for generating
derived tables that we can then just plug back into metabase.  You could
just accept an array of stages as input.

--
Bartosz Solowiej

*Senior Software Engineer*
*Olio Devices*

www.oliodevices.com
1-650-360-2278

CONFIDENTIALITY NOTICE: This transmission may contain information which is
Olio confidential and/or legally privileged. The information is intended
only for the use of the individual or entity named on this transmission. If
you are not the intended recipient, you are hereby notified that any
disclosure, copying, or distribution of the contents of this transmission
is strictly prohibited. If you have received this transmission in error,
please immediately notify me by return e-mail and destroy all copies of the
original message.

**Comment by edmarriner** [comment]
The aggregation pipeline would be well suited to this I think!
Yep, a JSON based approach seems logical to me :+1:

**Comment by toszter** [comment]
Uuuuuhhh, why on Earth did this get closed w/o an explanation or reference to an ongoing path toward resolution.  MongoDB is a valuable part of big data analytics.  Supporting it in Metabase is prudent, and you've gotten quite a few thumbs in the air for this... so, please.

**Comment by olmaga** [comment]
+1

**Comment by camsaul** [comment]
@olmaga this will ship as part of our upcoming 0.18 release.

**Comment by bmurzeau** [comment]
+1

**Comment by camsaul** [comment]
@bmurzeau this will ship as part of our upcoming 0.18 release.
