### ISSUE TITLE
`/api/setting/:key` endpoint errors when accessing a setting with a numerical value

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#20735]
**Describe the bug**
Settings with `:type :integer` and non-default values will generate a Ring error when accessing via `/api/setting/:key` 

**To Reproduce**

You can repro by changing the value of any integer setting on the backend or in the DB, then accessing it via the above endpoint. There aren't that many though, so here's a specific way to repro via the UI.

1. Log in to an EE instance as an admin user
2. Go to Admin Settings -> Caching
3. Change the value of `Max Cache Entry Size` to a non-default value and save
4. Hit the endpoint `/api/setting/query-caching-max-kb` (in your browser, on the command line, etc)
5. See an error with the following message: `"No implementation of method: :write-body-to-stream of protocol: #'ring.core.protocols/StreamableResponseBody found for class: java.lang.Long"`

**Expected behavior**
Should return the value (I guess serialized as a string?) and not error

**Information about your Metabase Installation:**
Current master

**Severity**
No current user impact since we don't seem to be using the `/api/setting/:key` endpoint anywhere on the frontend. But might bite us in the future if we do. Could be considered tech debt instead of a bug because of this.

**Comment by flamber** [comment]
Leaving as bug, since it can make using the API slightly more difficult for outsiders. It has at least existed since 0.38

**Comment by escherize** [comment]
Didn't notice that this needed to work with keywords, getting out a PR for that right away.
