### ISSUE TITLE
Field type not respected in $datetostring

### ISSUE THREAD

**Issue by chadhuber** [metabase/metabase#2073]
*  My server's OS is Debian 8.2 jessie
*  My database is Mongo 3.2.1
*  My Metabase version is v0.14.0

I've declared a Date field type as a Unix Datestamp (in seconds) yet when I run a query, I'm getting the following error:

`Command failed with error 18537: '$dateToString is only defined on year 0-9999, tried to use year 292278994' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "$dateToString is only defined on year 0-9999, tried to use year 292278994", "code" : 18537 }`

It's using the entire Unix Datestamp as the year.

The following relevant part is in the aggregation pipeline:

`{:$let
    {:vars
     {:field
      {"$add"
       [#inst "1970-01-01T00:00:00.000-00:00"
        {"$multiply" ["$date" 1000]}]}},
     :in
     {:___date
      {:$dateToString {:format "%Y-%m-%d", :date :$$field}}}}},`

**Comment by camsaul** [comment]
Are you sure the field is in seconds?

**Comment by chadhuber** [comment]
Indeed. Appears it's a 9 character datestamp
