### ISSUE TITLE
SSO group mapping doesn't work if IdP sends group membership in different attributes

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20744]
**Describe the bug**
SSO group mapping not working correctly depending on the order of group response from the IdP.

This might be the same problem as https://github.com/metabase/metabase/issues/17410#issuecomment-896922782, and might apply to JWT too.

**To Reproduce**
1. On the SAML IdP, assign multiple groups to a user - example, in KeyCloak it's called "roles"
![image](https://user-images.githubusercontent.com/1447303/155717261-0e5be33b-bf91-4662-928a-a1a80b6043a6.png)
2. Now setup SAML in Metabase and verify that it's possible to login with SAML user. The response should look like this - **note** the order of the groups
```
...
    <saml:AttributeStatement>
      <saml:Attribute FriendlyName="email" Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">user1@saml.test</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute FriendlyName="surname" Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">SAML</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute FriendlyName="givenName" Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">User1</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">test-group1</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">test-group2</saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>
...
```
3. Setup group sync in Metabase, but only create a sync for the **first** group according to the response:
![image](https://user-images.githubusercontent.com/1447303/155719218-bf83a6ec-3b3a-4e5b-b179-2957db29c2c4.png)
4. Login with SAML user - it will not have assigned the user to any groups:
![image](https://user-images.githubusercontent.com/1447303/155719366-df7438d8-ae82-400f-925b-e4d51cad430c.png)
5. Change the group sync to the **second** group
![image](https://user-images.githubusercontent.com/1447303/155719619-ec2a2862-c678-47b8-ad83-74aa94ee5fb5.png)
6. Login with SAML user - it will now correctly assign the group
![image](https://user-images.githubusercontent.com/1447303/155719839-48ff6459-a730-40cd-84a3-07f5bd8936a3.png)
7. Change the group sync to include both groups
![image](https://user-images.githubusercontent.com/1447303/155720035-4e63451d-655d-4399-88d2-a2ebab3dd61c.png)
8. Login with SAML user - it will only assign the last group
![image](https://user-images.githubusercontent.com/1447303/155720408-92159945-06b1-4f40-a7e5-20bf6827e0e5.png)
9. Now change the mapping order
![image](https://user-images.githubusercontent.com/1447303/155720597-b9438083-b541-44e5-829b-2e316f81bb87.png)
10. Login with SAML user - it still only assign the last group according to the response
![image](https://user-images.githubusercontent.com/1447303/155720806-71dc218f-e9d2-43d0-b879-5b1f3221294b.png)

**Expected behavior**
1. Should assign user to group no matter the order of the response from IdP.
2. Should assign all mapped groups that a user is member of according to the IdP.
So in step7 and step9, it should assign the user to both groups.

**Information about your Metabase Installation:**
Only tested 1.41.6 with SAML (KeyCloak), since it takes a lot of time, but I have a feeling that this might have been a problem forever or a very long time.

**Additional context**
Could perhaps also be the reason for #13820 not working correctly even though there's tests passing.

**Comment by paoliniluis** [comment]
Just did a local test on my end to verify this due to a customer report. The way in which the assertion should come in the SAML response is the following:
```
<saml:Attribute FriendlyName="memberOf" Name="memberOf" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
   <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">a_group</saml:AttributeValue>
   <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">c_group</saml:AttributeValue>
</saml:Attribute>
```

If you pass to Metabase the groups in a structure like this one (an attribute that contains several attribute values), the mapping will work.

The correct way to configure this in Keycloak is the following:
1) create a few groups in Manage->Groups and then assign a user to a few groups
2) In the client->mappers section, create a mapper of the group list type
![image](https://user-images.githubusercontent.com/1711649/156047699-c04d51ab-b49e-464c-9418-ddc6a56bc352.png)
You have to enable "single group attribute" so all groups come together in the same attribute rather than on different ones
3) create the group mappings in Metabase and then authenticate the user with SSO

E.g: I created a user and assigned 2 groups (/a_group, /c_group), property came like:
![image](https://user-images.githubusercontent.com/1711649/156048465-46af2c26-cecc-4e35-a309-33e6262b5b52.png)

User was assigned automatically to two groups:
![Uploading image.png…]()

I still have to check why this fails on the customer side

**Comment by flamber** [comment]
We should create logging, so it's clear that there's several attributes, which overrides each other and only a single attribute with multiple values is supported.

**Comment by brendanheywood** [comment]
While we are now up and running, I still don't see any downside to supporting both formats out of the box. That seems like less work and better UX than adding logging and more documentation.
