### ISSUE TITLE
Pin Map keeps zooming on San Francisco

### ISSUE THREAD

**Issue by bvirlet** [metabase/metabase#2075]
I have a pin map added to my dashboard. By default the pin map shows the San Francisco area. Even if I change it to display the world, it resets to SF. Is there a way to make it display the entire world by default.

If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac OS
*  My database is Postgres
*  My Metabase version is v0.15.0 built on 2016-02-29

**Comment by mazameli** [comment]
Hey, @bvirlet. Seems like you solved your problem, but was the solution challenging to find for you?

**Comment by bvirlet** [comment]
Hey @mazameli ! Sorry I should have marked this as a duplicate from https://github.com/metabase/metabase/issues/2076, created by mistake.
