### ISSUE TITLE
Pin Map keeps zooming on San Francisco

### ISSUE THREAD

**Issue by bvirlet** [metabase/metabase#2076]
I have a pin map added to my dashboard. By default the pin map shows the San Francisco area. Even if I change it to display the world, it resets to SF. Is there a way to make it display the entire world by default.

*  I am using the Chrome browser.
*  My computer's OS is Mac OS
*  My database is Postgres
*  My Metabase version is v0.15.0 built on 2016-02-29

**Comment by tlrobinson** [comment]
I'm fixing this as part of our visualizations revamp in v0.16, but if it's urgent and you're willing to build from source I can do a quick fix.

**Comment by bvirlet** [comment]
No hurry, v0.16 will be good enough. :bow:
