### ISSUE TITLE
Name of tables in filters with foreign keys

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#20760]
Hello,

In the GUI when creating a question, in filters and grouping. In the case of a table linked by a foreign key to another. The name of the "destination" table does not appear. This makes it difficult to understand for someone who does not know the structure of the database.

In this example the "Commande - quantités" table is linked by "Numéro de commande" to the "Commande - entête" table and the "Num. commande" field

![image](https://user-images.githubusercontent.com/4558101/155959685-10df4b73-2044-4f0c-82d8-26f7df7ae032.png)

![image](https://user-images.githubusercontent.com/4558101/155959890-1d8f3961-f23d-4ffc-9245-2967e76401bf.png)

![image](https://user-images.githubusercontent.com/4558101/155960041-2ecd3f3b-1ef7-431c-a197-19f4849c4469.png)

Thank's

**Comment by flamber** [comment]
Duplicate of #8599
