### ISSUE TITLE
Client-side sorting on PK/FK uses alpha instead of numeric ordering

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#20781]
**Describe the bug**
When you try to sort numeric fields (I've tried on PK and FK fields), then sorting doesn't work properly because it doesn't account for tens, hundreds, thousands, etc.

For example, it would sort like this: `1, 10, 100, 1000, 2, 3, 4...`

**Logs**
N/A

**To Reproduce**
1. Save Orders table as a question
2. Embed it and either observe the embedding preview, or go to an actual link for the iframe
3. Click on the header for Orders ID (PK) or a user ID (FK)
4. Note that it doesn't show the popup with possible actions like it does in Metabase app (this is expected) - the only action that's possible is sorting and it happens automatically when you click the header
5. If it sorts the column in ascending order, it puts 10s and 100s immediately after 1

**Expected behavior**
Single digit numbers should always go before two digit numbers, etc. The ascending order should be `1, 2, 3, 4, 5., 10, 20, 100..`

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/156175009-7c83992f-cb98-444b-9642-87c22940fe22.png)

**Information about your Metabase Installation:**
local dev, `master`, c7573b2bce188946ebcb0685b14b52baf9ffea31, H2, Sample database

**Severity**
P3?

**Comment by flamber** [comment]
Caused by #13107. Likely not worth fixing before addressing #5816, which might automatically fix it.
