### ISSUE TITLE
We shouldn't make a user pick a DB if they only have a single one

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2078]
This is what it looks like currently, but we could just "auto-select" the DB for them and show the list of schemas in the DB if there are any, and if not, just show the list of tables within the DB.

![screen shot 2016-02-16 at 2 13 05 pm](https://cloud.githubusercontent.com/assets/2223916/13503405/12d614d4-e124-11e5-9b50-0c6e5484f16b.png)

**Comment by kdoh** [comment]
:+1:

**Comment by salsakran** [comment]
This doesn't seem like it needs any design, so I'm going to label it "designed"

**Comment by tlrobinson** [comment]
Just a note to remind us to update the query builder tutorial when we do this. We'll need a way to skip the db selection step if they haven't added any other databases.
