### ISSUE TITLE
Serialization does not remove cards from dashboard even with --mode update

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20786]
**Describe the bug**
Serialization will not remove cards that are not present in the yaml files even with --mode update

**Logs**
No errors at all in the serialization process (it says "nothing to update" even if the dashboard changed)

**To Reproduce**
1) set up Metabase source and destination
2) create 2 questions in the source and add them to a dashboard
3) dump in source and load into destination
4) remove one of the questions in the source's dashboard
5) dump and load again, with --mode update, the destination dashboard will still have 2 questions

**Expected behavior**
It's expected that the --mode update will replace everything on destination

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: H2
- Metabase version: 1.42.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Well... this seems to cripple the serialization process a lot

**Additional context**
This can easily lead to https://github.com/metabase/metabase/issues/19762, which ends up with a database with lots of things that shouln't be there

**Comment by flamber** [comment]
It's basically the same as #19762 and #20024. More context https://github.com/metabase/metabase/pull/17388#issuecomment-900415001

**Comment by brunobergher** [comment]
My read is that the ultimate solution for this is to have stable, unique identifiers for entities across the instances involved in the dump/load process, no? If entities in Metabase had UUIDs or user-defined identifiers (with uniqueness constraints), we wouldn't have to try and be smart about it.

**Comment by paoliniluis** [comment]
> My read is that the ultimate solution for this is to have stable, unique identifiers for entities across the instances involved in the dump/load process, no? If entities in Metabase had UUIDs or user-defined identifiers (with uniqueness constraints), we wouldn't have to try and be smart about it.

+10000 on this. It will also ease single object serialization and more
