### ISSUE TITLE
Static viz for a question with no results generates a blank white square

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#20796]
**Describe the bug**
If you create a dashboard subscription that includes a question with no results and send it to Slack, the question is displayed as a blank white square.

**Expected behavior**
It's not obvious that a white square means "no results". I think we should have some text here indicating that there were no results, or use the same "empty drawer" image we use in actual dashboards, or _something_.

**Screenshots**
<img width="334" alt="Screen Shot 2022-03-01 at 2 01 43 PM" src="https://user-images.githubusercontent.com/32746338/156232137-b4bee161-043b-440b-9f66-aa7fc6d685fb.png">

**Information about your Metabase Installation:**
Current master

**Severity**
Mild but a bit confusing

**Comment by losrebellos** [comment]
@flamber @howonlee

After some investigations, when there is no data, the rendering of the png is skipped by the BE (hardcoded).
This needs to be removed before we can push forwards with more tests on the `no results` SVG.

**Comment by flamber** [comment]
@alexmearns I think we could just send a text string instead of an image, just like we do with Number visualizations, then it should be quite easy to spot visualizations with results.
