### ISSUE TITLE
"Axes" and "Labels" for Row Charts

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#20791]
Not having "Axes" tab, for instance we cannot define axis-scale (Linear/Power/Log).

![row and bar](https://user-images.githubusercontent.com/15974735/156221585-0bd073f6-a5d2-41c5-8bf1-b81971731a14.png)

Related to [#12977](https://github.com/metabase/metabase/issues/12977) (but there the focus is on "Labels" tab).

v .42.1

**Comment by flamber** [comment]
This is difficult to implement with how the current Row chart is coded. Think it would be better to use the current Line/Bar code, just shifted, which would give all options that Line/Bar current has. #10967
