### ISSUE TITLE
Static visualization ignores granularity in X-axis ticks in some cases

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20807]
**Describe the bug**
Static visualization uses a different X-axis ticks in some cases. Example when grouping by Month and there's only 3 ticks in-app, then static will show the X-axis as Week.

**To Reproduce**
1. Question > Sample > Products
2. Filter CreatedAt after `01/31/2019`, summarize Count grouped by CreatedAt:Month
![image](https://user-images.githubusercontent.com/1447303/156357210-b15809ef-1c47-440d-a6cb-3ed77edcf16c.png)
3. Save question, add to dashboard, Sharing > Subscriptions > Email > Send email now
![image](https://user-images.githubusercontent.com/1447303/156357456-fe0f957d-80f4-4a4b-9975-e84780058ad3.png)
4. The received image
![image](https://user-images.githubusercontent.com/1447303/156355812-8bd6def0-c9af-49cd-9fb3-6aa26c8f1e5a.png)

**Expected behavior**
Should show similar ticks as in-app. This is how it looks, when there's 4 months:
![image](https://user-images.githubusercontent.com/1447303/156356149-bd8ffd0b-c9fb-4c7d-a75c-439dafc58206.png)

**Information about your Metabase Installation:**
Tested 0.40.5 thru 0.42.2

**Additional context**
#5493

**Comment by losrebellos** [comment]
Bug is replicable with `timeseries/area` too.
