### ISSUE TITLE
Static visualization not respecting order

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20808]
**Describe the bug**
Static visualization not respecting order and sorts by alphabetical.
Regression since 0.42

**To Reproduce**
1. Question > Sample > Reviews
2. Summarize Count grouped by Reviewer
3. Sort by Count descending, limit 4 rows
![image](https://user-images.githubusercontent.com/1447303/156359039-791f6744-afaa-4062-886d-4f44269f3ac9.png)
4. Add question to dashboard, Sharing > Subscription > Send email now
![image](https://user-images.githubusercontent.com/1447303/156359271-bf5d9d18-161e-49fb-ae5c-beec81bd5cdf.png)
5. Received image
![image](https://user-images.githubusercontent.com/1447303/156359230-af258efb-7c31-4867-84fc-65d16f46eca7.png)

**Expected behavior**
Same as 0.41.6, respecting the order chosen similar to in-app
![image](https://user-images.githubusercontent.com/1447303/156359339-0ceacfb9-a5fc-476e-9a9f-2741bd97ebd6.png)

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.2

**Comment by losrebellos** [comment]
After some investigations, it seems that the FE code is [not reordering](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/static-viz/components/CategoricalBarChart/CategoricalBarChart.jsx#L129-L131) the data in any way.

That being said, @howonlee pointed out that the BE code is reordering the data in [single-x-axis-combo-series](https://github.com/metabase/metabase/blob/master/src/metabase/pulse/render/body.clj#L567) and [double-x-axis-combo-series](https://github.com/metabase/metabase/blob/master/src/metabase/pulse/render/body.clj#L587) making use of `clojure` builtin `sort-by`.

It was add to fix a bug with `time series` where the rows will reorder completely randomly.
