### ISSUE TITLE
BigQuery: Aggregating by a datetime in a saved question fails because of bad aliasing

### ISSUE THREAD

**Issue by cdlethem** [metabase/metabase#20806]
**Describe the bug**
There's a bug in the way that backticks are placed around table aliases and field names that's causing saved questions to fail with BigQuery when you try to group by a datetime field using the query builder. 

**To Reproduce**
1. Write SQL, save a question as the following:
```
select
    date 
from
    unnest(generate_date_array('2021-01-01', '2022-01-01')) date
```
2. Click Explore results, open editor
3.  Summarize count and group by date:week

This is the output SQL:

```
SELECT datetime_trunc(CAST(`source.date` AS datetime), week(monday)) AS `date`, count(*) AS `count`
FROM (select
    date 
from
    unnest(generate_date_array('2021-01-01', '2022-01-01')) date) `source`
GROUP BY `date`
ORDER BY `date` ASC
```

The error is because BigQuery expects the table alias and field to be backticked separately, so instead of ``` `source.date` ```, it should be ``` `source`.`date` ```

**Severity**

Honestly, this has been a pretty annoying blocker for me over the past couple weeks. I got my company upgraded to 0.42, excited to make more use of the new models feature. However, I've been reverting back to writing SQL and pre-building dbt models just to get things done on time, rather than using joins or saved questions. I'd like to do more data modelling within metabase as one might with Looker, but little bugs like this while working with joined, nested and saved questions are preventing me from doing so

**Comment by flamber** [comment]
Regression since 0.42.1 - worked on 0.42.0, did not work on 0.41.6
