### ISSUE TITLE
Models should not be embeddable

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#20815]
**Describe the bug**
Talking with the product and @brunobergher specifically, it turns out that models should not be embeddable objects. They currently are but that should change.

**Logs**
N/A

**To Reproduce**
1. Turn any saved question into a model
2. Notice the share icon in the lower right corner
    - If you click on it, it's possible to embed and share that model
 
**Expected behavior**
Share icon shouldn't exist for models in the first place.

**Screenshots**
N/A

**Information about your Metabase Installation:**
- local dev, `master`, 0b06f460344afdefd3b127140cc96aa58a404e25, H2, Sample database
- also release x.42.2

**Severity**
?

**Comment by paoliniluis** [comment]
also, should we able to turn a model into a chart? if not, then that's another issue

**Comment by brunobergher** [comment]
I don't understand that question, Luis. A model is a data source, like a table. How can you "turn" a table into a chart? You need to first create a query (even if it's `SELECT *`),  no?

**Comment by paoliniluis** [comment]
Completely forget what I wrote, I'm sleepy today

**Comment by WiNloSt** [comment]
@nemanjaglumac @brunobergher After digging around in the code. It seems that the share icon/button could be enabled on 2 conditions
1. Public sharing is enabled or
2. Embedding in other Applications is enabled

There's also *Public embed* option inside Public sharing settings, so I'm not entirely sure how I should interpret
> models should not be embeddable objects

1. Should it not be embedded in other applications only which will present another challenge that the share icon/button is the only entry point to both public sharing and embedding in other applications options.
2. Disable share icon/button entirely for models so users won't be able to even share it via a public link.

#### After clicking the share icon/button there'll be this modal popped up.
![image](https://user-images.githubusercontent.com/1937582/158531179-6e8c2e5b-2a5e-42a1-bf9a-53cfa62864f1.png)

The change I made in #21025 is that the share icon/button will not show for Models.
