### ISSUE TITLE
Block permissions behave strangly after losing advanced permissions feature flag or switching to OSS

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#20813]
**Describe the bug**
If you set block permissions on an EE instance of Metabase and then either lose the `advanced-permissions` feature flag, or switch to running an OSS instance, the behavior is inconsistent and there are some clear bugs.

**To Reproduce**
I haven't figured out all the possible weirdness here, but here's steps to reproduce some of it, at least: 

1. Run an EE version of Metabase with a token containing the `advanced-permissions` feature flag, and log in as an admin
2. Go to Admin -> Permissions -> All users
3. Change "Data access" for a database to "Block", and save changes
4. Clear the enterprise token (while still running the EE code), or switch to running an OSS version of Metabase using the same app DB
5. Go back to the permissions page for "All users", and see that the cell in the permissions grid is now empty, where the block permission was previously set:
<img width="772" alt="Screen Shot 2022-03-02 at 1 46 01 PM" src="https://user-images.githubusercontent.com/32746338/156430643-a3861c95-fd96-4ece-8dc8-0daf7ed1da7d.png">

6. As an admin, create and save a question based on the DB that had block permissions set, and add it to a dashboard
7. Log in as a non-admin. Observe that:
   * The DB that had block permissions set doesn't show up in "Our data" on the homepage, or in the "Browse data" page
   * If you view the dashboard, you _can_ see the card, and you can click on the card title to view the full question
   * When viewing the full question, you can't run any filters or aggregations or create any new questions based on the data

**Expected behavior**
My gut instinct is that if you have block permissions defined, and you lose the advanced permissions feature flag, any data with block permissions set should be converted to "No self-service" and the app should behave accordingly.

I'm _not_ sure what should happen if you switch back to having the advanced permissions feature flag after that. Maybe this is a rare enough case that we don't need to make any guarantees.

**Information about your Metabase Installation:**
Current master

**Comment by flamber** [comment]
The expected behavior should be if you lose `advanced-permissions`:
- On Admin > Permissions, you'll have the option to set it to something different, but not being able to set it back to Blocked.
- Any questions should still be blocked (if that's the current setting in Admin > Permissions)

This does not apply to switching to OSS, only if the feature flag expires for whatever reason. Basically similar behavior to losing Sandboxing shouldn't allow the users to see more data than what the permissions were initially configured to.

**Comment by noahmoss** [comment]
@flamber What do you think the behavior should be when switching to OSS?

I think the core issue is that we don't migrate any data in the app DB when feature flags change, or when you switch to OSS from EE. So EE code can only write data to the app DB that is fully backwards-compatible with OSS code. In this case, the OSS code doesn't know how to handle block permission paths, resulting in inconsistent behavior.

**Comment by flamber** [comment]
@noahmoss It would require including the code in the OSS, so it would likely become a licensing issue. If someone switches to OSS, then it's a manual action and none of the features would be available there (like SSO etc). But someone at the higher levels should answer this.

**Comment by noahmoss** [comment]
Fixed in 50
