### ISSUE TITLE
Using X-Ray from pivot table causes the X-ray page to go into a reload loop

### ISSUE THREAD

**Issue by apinco** [metabase/metabase#20816]
**Describe the bug**
When I try to use x-ray on one of the cells in a Pivot table, the X-Ray page starts to load and I can see the information, then it goes into a constant reload of the page.  

Here is a screenshot of me clicking on the X-ray:
![image](https://user-images.githubusercontent.com/11303977/156454872-283a81e4-c75b-4bcb-a6cb-ba9f0f80c70d.png)

Here is the page before it tries to reload:
![image](https://user-images.githubusercontent.com/11303977/156454980-0ee77c17-e815-41aa-a073-6c0afb09f28b.png)

It switches between the above screen and this screen repeatedly:
  
![image](https://user-images.githubusercontent.com/11303977/156455071-99514e75-b096-4959-bfa5-6c3981fc3b8e.png)

**Logs**
Javascript Logs (best I could get with the constant reloading):
`

</body>
</html>
`

**Expected behavior**
I expect that it doesn't go into a reload cycle

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.4.0-91-generic",
    "user.language": "en",
    "user.timezone": "America/Denver"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.5 (Ubuntu 13.5-2.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-17",
      "tag": "v0.42.1",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": "America/Denver"
    }
  }
}

- Your browser and the version: Chrome 98.0.4758.102
- Your operating system:Windows 10
- Your databases: Postgresql
- Metabase version: .0.42.1
- Metabase hosting environment: Local deployment on Ubuntu 20.04
- Metabase internal database: Postgresql

**Severity**
It is just annoying, but not critical as we can  just not run x-ray in that manner for n ow.

**Comment by apinco** [comment]
I am attaching the chrome console logs as a .txt file as it is large due to the constant reloads:


[chrome_console_log.txt](https://github.com/metabase/metabase/files/8173603/chrome_console_log.txt)

**Comment by flamber** [comment]
Hi @apinco 
I cannot reproduce this. I doubt the problem is related to the Pivot Table, but more likely the underlying question construction.
Can you include the metadata output of `/api/card/123`, where 123 is the question ID (of the Pivot Table).
