### ISSUE TITLE
Reduce the size of visuals in alert emails

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#20836]
It's too big!

![alert too big](https://user-images.githubusercontent.com/15974735/156653322-0de58395-56f7-4d8e-9d8b-e11e294a339a.png)

v .42.1

**Comment by notrom** [comment]
@vvaezian Is that in desktop Outlook? I have the same sort of issues, all my alerts and subscriptions look pretty bad with the new Metabase email format when viewed in Outlook. Something to do with Outlook not using a standard html renderer.

If you view the same email in the gmail app or even Outlook for Android they look much more reasonable. Unfortunately I don't control the client people use to view emails and in our organisation it's primarily desktop Outlook so I'm kind of stick with ugly subscriptions for now.

**Comment by vvaezian** [comment]
@notrom Yes, the image is showing Desktop Outlook.

**Comment by flamber** [comment]
Closing in favor of #6874 and will try to push it.
