### ISSUE TITLE
Parameters positions not saved then there are more than 8

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#20830]
**Describe the bug**
When building a question with many parameters, you can rearrange the filter parameters when you have <= 8, more than that goes haywire

**Logs**
Incredibly no bugs here, maybe some state stuff in the FE? 

**To Reproduce**
1) Go to our internal instance and do a SQL query with the sample database:
```
select * from people 
[[where 
    id = {{id}} 
    and address = {{address}} 
    and email = {{email}} 
    and password = {{password}} 
    and name = {{name}} 
    and city = {{city}} 
    and longitude = {{longitude}} 
    and state ={{state}} 
    and source = {{source}}]]
limit 1
```
2) try reordering a parameter and see that it doesn't work
3) now remove one parameter
4) try reordering again, now it works

**Expected behavior**
Make all parameters sortable

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: H2
- Metabase version: master

**Severity**
Non-severe

**Additional context**
Reported by a customer

**Comment by noahmoss** [comment]
Seems like this is a duplicate of https://github.com/metabase/metabase/issues/5136?

**Comment by paoliniluis** [comment]
Oh thanks! couldn't find it! (and didn't know it existed!)
