### ISSUE TITLE
[E2E] Integration with Currents.dev

### ISSUE THREAD

**Issue by diogormendes** [metabase/metabase#20831]
Epic to enable Currents.dev as the Dashboard for analysis 

Docs: https://www.notion.so/metabase/Currents-dev-Analysis-555ead56ce6946c0b0a1535ae6cfe606

**Comment by nemanjaglumac** [comment]
Can this be closed now or do we wait until we integrate GHA with currents?

**Comment by diogormendes** [comment]
This can be closed.
