### ISSUE TITLE
Embedding with Locked parameters does not allow numeric values

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20845]
**Describe the bug**
Embedding with Locked parameters does not allow numeric values.
Regression in 0.42

**To Reproduce**
1. Question > Sample > `select count(*) from orders where quantity={{qty_locked}}` - set variable as Number
2. Enable embedding and set parameter to **Locked**
3. Generate JWT token with locked parameter as **numeric** value (even though the example preview recommends a string value):
```
{
  "resource": {
    "question": 853
  },
  "params": {
    "qty_locked": 1
  }
}
```
4. Go to the URL - errors
![image](https://user-images.githubusercontent.com/1447303/156785091-e37f5c74-975b-422c-b4ae-8dc419151ee2.png)

Backend only has this unhelpful error:
```
2022-03-04 15:52:31,029 DEBUG middleware.log :: GET /api/session/properties 200 18.8 ms (2 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (71 total active threads) Queries in flight: 0 (0 queued)
2022-03-04 15:52:34,723 DEBUG middleware.log :: GET /api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6ODUzfSwicGFyYW1zIjp7InF0eV9sb2NrZWQiOjF9fQ.n2zsOej1QYV3603wHZJXEHIcnq8QxgniYOclB6f7tMI 200 3.4 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
2022-03-04 15:52:34,756 DEBUG middleware.log :: GET /api/session/properties 200 12.5 ms (2 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
2022-03-04 15:52:34,909 DEBUG middleware.log :: GET /api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6ODUzfSwicGFyYW1zIjp7InF0eV9sb2NrZWQiOjF9fQ.n2zsOej1QYV3603wHZJXEHIcnq8QxgniYOclB6f7tMI/query 400 5.9 ms (3 DB calls) 
"Don't know how to create ISeq from: java.lang.Integer"
```

**Expected behavior**
Allow numeric parameters.
While we're at it, would be nice if we allowed the resource as string, since I see that as a common mistake as well.

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.2

**Comment by mvelebit** [comment]
Just a note, this happens without locked variables for me as well. Can provide more info if needed.

**Comment by flamber** [comment]
@mvelebit Please provide "Diagnostic Info" from Admin > Troubleshooting, and steps-to-reproduce.

**Comment by mvelebit** [comment]
Diagnostic info:
`{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.14.262-135.489.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": "US/Mountain"
    }
  }
}`

Steps to reproduce: 
1. Create a custom question with a number variable (see [picture](https://ibb.co/dsZZSmC) for more details)
2. Try embed it in an app using JWT (as described in the sharing > application section of a question)
3. Receive `Don't know how to create ISeq from: java.lang.Integer` error.

This wasn't happening until our recent version upgrade to 42.1 (currently at 42.2).

**Comment by mvelebit** [comment]
Thanks for your replies, here's the JWT payload that I'm sending

 ```
 {
  "resource": {
    "question": 3168
  },
  "params": {
    "hours": 24
  },
  "iat": 1646750149
}
```
The entire request URL is the following: 
`https://metabase-env.xxxxx.com/embed/question/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6MzE2OH0sInBhcmFtcyI6eyJob3VycyI6MjR9LCJpYXQiOjE2NDY3NTAxNDl9.GgMLeyrD7RxGdv0iSvI10O9dxY4vLDCHQawLg7ECAks.json`

The crux of the report-fetching code:
```
const params = JSON.parse(stringifiedParams);
const token = generateMetabaseToken(id, params);
const queryString = `${config.metabaseSiteUrl}/embed/question/${token}.json`;
const response = await fetch(queryString);
  ```
Is that sufficient?
