### ISSUE TITLE
Hiding table in Admin Panel not possible

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#2084]
When trying to hide a table through the Admin Panel I get an error message that says that the request entity is too large.

There is clearly one bug here: The error message is not displayed correctly.

But more importantly I'd like to know what it means that the "request entity" is too large, and how I can hide that table. As we can't hide schemas (yet?) I'm hiding every table within the schemas I don't want in order to save users from having to know what schema they have to click on. If all tables in all schemas are hidden but one they don't have to choose a schema. Therefore I need to hide this table or explain to everyone which schema they find the tables they are used to.
![image](https://cloud.githubusercontent.com/assets/8144392/13525746/6c44d6f6-e203-11e5-8101-54685c575705.png)

> `Error: <html> <head><title>413 Request Entity Too Large</title></head> <body bgcolor="white"> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.8.0</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac OS X.
*  My database is Postgres.
*  My Metabase version is v0.15.0.

**Comment by agilliland** [comment]
Interesting.  So you are getting this error when you click the `hidden` button for visibility on that table?

The error does indeed look very strange there in this case.  Normally the error should be very short and concise and show up on a single line next to the toggle switch.  I think what's happening is that you appear to have an nginx in front of the Metabase application server and something that's happening when the api call is being made to hide the table is triggering this error with nginx which is responding with this large HTML page response.

I'll have to poke around and see why that error might be getting called in this situation.  Have you seen this happen on any other table or page in the application?

**Comment by camsaul** [comment]
The request isn't even reaching Metabase, nginx is killing it.

The 413 was the same thing we were seeing with the `Referer` header in #1758. The request probably contains some crazy-long header. @robinfrick can you look in the Web Inspector and look at the actual request being made and see if any of the headers are crazy-long?

**Comment by robinfrick** [comment]
I have no idea about web development, so I hope this is the correct data. If not please provide idiot-proof instructions on how to get it ;-)

![image](https://cloud.githubusercontent.com/assets/8144392/13565981/96fc1c40-e453-11e5-97fe-b19d9b5396df.png)

"Copy Request Headers":
> PUT /api/table/3246 HTTP/1.1
> Host: datafrontend.---.de
> Connection: keep-alive
> Content-Length: 1972276
> Accept: application/json, text/plain, */*
> Origin: https://datafrontend.---.de
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
> Content-Type: application/json;charset=UTF-8
> Referer: https://datafrontend.---.de/admin/datamodel/database/6/table/3246
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: en-US,en;q=0.8,de;q=0.6
> Cookie: metabase.SESSION_ID=91d90ec9-c00d-454c-a0aa-36d1fe9cd3cb; _ga=GA1.2.1343521795.1454350749; _gat=1

**Comment by agilliland** [comment]
yeah, `Content-Length: 1972276` that is much bigger than it should be and is likely what's causing the problem.  I'll take a look.

**Comment by agilliland** [comment]
okay, having tested this out it appears to be something specific to safari.  there is some data on the table object that we use locally for the application logic which is meant to be stripped before making the api call, but somehow that doesn't appear to be working properly in Safari.

**Comment by robinfrick** [comment]
I'm using Chrome, so it's not only Safari.

**Comment by agilliland** [comment]
Can you tell me what version of Chrome you are running?

**Comment by robinfrick** [comment]
Tomorrow (CET), when I'm back in the office.

**Comment by robinfrick** [comment]
Chrome Version 49.0.2623.75 (64-bit) on OS X 10.10.5

**Comment by agilliland** [comment]
This is fixed and will be part of our upcoming patch release.

**Comment by Germanaz0** [comment]
@agilliland do you know when will be that patch release ?

**Comment by tlrobinson** [comment]
@Germanaz0 It's in v0.15.1 which we released yesterday: https://github.com/metabase/metabase/releases/tag/v0.15.1

**Comment by Germanaz0** [comment]
@tlrobinson is not the same release as it is on https://github.com/metabase/metabase-deploy ?

**Comment by tlrobinson** [comment]
@Germanaz0 Yes, `metabase-deploy` has v0.15.1 (look at the latest commit), and I just confirmed clicking the deploy button on that page deploys v0.15.1

**Comment by Germanaz0** [comment]
The thing is that I deployed that version and hidden tables is not fixed I think

**Comment by robinfrick** [comment]
On my end v0.15.1 fixed it. Thanks.

One suggestion though: A Metabase upgrade should force the user to refresh. When I first tested it, it still didn't work. I looked at about Metabase and noticed it's still on v0.15. I was in a tab that I had opened before upgrading Metabase yesterday. The session just never got the upgrade.
