### ISSUE TITLE
Visualization overwrites column ordering with A-Z order

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#2085]
If I arrange table rows for visualization in a particular order before v0.15.0 the order was kept when I switched from table to a visualization. Now visualized they are re-ordered:
![image](https://cloud.githubusercontent.com/assets/8144392/13529824/720ff1f4-e21e-11e5-8a53-a5daa7a8d3d3.png)
is visualized as: 
![image](https://cloud.githubusercontent.com/assets/8144392/13529847/8f30567a-e21e-11e5-80c0-37f1362b7ff8.png)

**Comment by tlrobinson** [comment]
+1 I just noticed this as well.

**Comment by maliayas** [comment]
This happens to me with SQL questions. I order by a numeric column and it shows fine in table view. However when I switch to bar chart or other charts, ordering looks like random; neither the same nor the opposite of what I want, just arbitrary.

**Comment by robinfrick** [comment]
@tlrobinson after upgrading to v0.17.1 this is happening again :(

**Comment by salsakran** [comment]
reproduced this on the sample data set, and reopening =(

**Comment by salsakran** [comment]
I'm seeing alphabetical ordering on bar charts regardless of the sort order of the underlying table.

**Comment by tlrobinson** [comment]
This was broken here https://github.com/metabase/metabase/commit/4c1ba6b0709e76ae986a1506a142cfb8b8d4dcb5 in order to fix a different case where line charts were being crazy. Obviously the problem is a little more nuanced...

**Comment by Coqueiro** [comment]
+1 Having the same issue here
