### ISSUE TITLE
Button to hide-all/show-all tables in a given database or schema in the data model

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2086]
As mentioned in #2084, in the admin panel, we should add the ability for an admin to mark an entire schema as Hidden.

Designs for a `hide all/show all` tables button in the data model are [here](https://github.com/metabase/metabase/issues/2146#issuecomment-364292788).

https://github.com/metabase/metabase/issues/2146 is very related, and maybe is a duplicate.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by MrMauricioLeite** [comment]
+1

and after that we can turn just a few tables visible.

**Comment by timclipsham** [comment]
+1

I'm using segment.com's warehousing functionality and I don't want to expose all the schemas it creates (within the same database) into Metabase.

**Comment by crissyw** [comment]
+1

**Comment by mk8ef** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by ismailsimsek** [comment]
+1

**Comment by VikramTiwari** [comment]
I just love how people don't read the comment just above and still leave plus ones. Maybe GitHub did not do a good job at UX.

**Comment by ismailsimsek** [comment]
my mistake :) added my vote using reactions  👍

**Comment by camsaul** [comment]
Thanks @ismailsimsek 👍

**Comment by mazameli** [comment]
As Sameer pointed out, this issue has come up again: http://discourse.metabase.com/t/toggle-data-model-visibility-for-entire-database-schemas-at-once-instead-of-table-by-table/1307

**Comment by doodlebro** [comment]
Ever going to get this functionality added? Issue has been open over a year.

**Comment by jhaip** [comment]
+1

**Comment by camsaul** [comment]
@jhaip I already mentioned this above, but one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by camsaul** [comment]
@key88sf unfortunately we're a small team, so this isn't something we're going to have time to do in the near future, but PRs are always welcome :)

**Comment by hansyson** [comment]
would like to be able to hide tables as well on the native query window as well... and for only certain groups and users.

**Comment by ryrobes** [comment]
Just closed a dupe I made of this. But being able to explicitly call out a "default" schema for a database connection would possibly solve some of these issues as well.

**Comment by mark-uscbi** [comment]
147 reactions as of this post. Can this be prioritized at some point?

**Comment by taneishamitchell** [comment]
is there no movement on this topic?
👍 +1

**Comment by flamber** [comment]
@taneishamitchell As noted right above your comment, it has been added to the 0.36 roadmap. That's not a guarantee it will make it for that release, but we'll try.

**Comment by mazameli** [comment]
We finally did this, folks. It'll be in version 0.36.

**Comment by mtthsbrr** [comment]
Nice one. It actually does not solve the origin problem "Admins should be able to hide schemas/namespaces" though. We have a lot of schemas in the DB which the Metabase user does not even have access to but they are all shown by Metabase when browsing the DB. Any plans to also fix this in the future?

**Comment by flamber** [comment]
@mtthsbrr That wasn't the origin problem. Not sure where you were reading that from. There's several related issues open https://github.com/metabase/metabase/issues/2146#issuecomment-631995455, so probably one of those is similar to what you're looking for otherwise open a new issue.

**Comment by dacort** [comment]
That was part of the original comment. :) 
> we should add the ability for an admin to mark an entire schema as Hidden.

But alas, the title/intent was renamed in 2019. @mtthsbrr You may be interested in #10139 which will prevent schemas the user doesn't have access to from showing up in Metabase.

**Comment by mtthsbrr** [comment]
> That was part of the original comment. :)
> 
> > we should add the ability for an admin to mark an entire schema as Hidden.
> 
> But alas, the title/intent was renamed in 2019. @mtthsbrr You may be interested in #10139 which will prevent schemas the user doesn't have access to from showing up in Metabase.

@dacort Thanks for clarifying and pointing me to the right direction 👍
