### ISSUE TITLE
Use check marks and cross marks in place of "true", "false" or "null"

### ISSUE THREAD

**Issue by ccalby** [metabase/metabase#20866]
To make the reports very user friendly, implementing alternatives when viewing table values would be useful. 
Rather than "true", "false" or "null", allow the question creator to specify alternative working for boolean values.
Such as:
true = Yes
false = No
null = Unknown

To go one step further and really make the table visualisation stand out, allow question creators to specify an image in place of boolean values.
Such as:
true = green checkmark
false = red cross mark
null = grey question mark

**Comment by flamber** [comment]
It's already possible with remapping: https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#remapping-column-values
Though, with some limitations. Closing in favor of #6102
