### ISSUE TITLE
Cannot dismiss sync-spinner

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20863]
**Describe the bug**
Repeat of #20283.
Some databases, seems like it's mostly Mongo, doesn't correctly update `initial_sync_status`, so it will always show the insanely annoying spinners, and causes requests every second to `/api/database/:id/metadata`, which can be very heavy #21985.

**Workaround:**
Go to the Metabase application database and set the status from `incomplete` to `complete` on the tables `metabase_database` and `metabase_table`.
Make a backup before making any manual changes to your application database!
```
update metabase_database set initial_sync_status='complete' where initial_sync_status='incomplete';
update metabase_table set initial_sync_status='complete' where initial_sync_status='incomplete';
```

**Expected behavior**
Give an option to completely dismiss loading spinner. Just set `initial_sync_status='complete'`

**Information about your Metabase Installation:**
0.42

**Comment by paoliniluis** [comment]
Adding to this problem: the app will keep calling /api/database endpoint forever till the sync is complete

**Comment by flamber** [comment]
Seems like one of the problems comes from doing this check, at least on one Postgres setup, so it's not unique to Mongo.
https://github.com/metabase/metabase/blob/491dbdc0e9e2293f041553a284265d95794ae067/src/metabase/sync/sync_metadata/metabase_metadata.clj#L88

It's fine if we want to fix all sync issues, but until that time, let's either disable this functionality or give an option to disable it.

**Comment by gonchik** [comment]
Looks like need to put also entity_type value, it was null for us
```update metabase_table mt
set  initial_sync_status = 'complete',  entity_type = 'entity/GenericTable'
where initial_sync_status = 'incomplete';```
