### ISSUE TITLE
Cannot connect Google Analytics because of deprecated OAuth OOB

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20876]
Seems like Google decided to make a change, where they deprecated their OAuth OOB be 2022-02-28 for new clients/setups.
This was announced on 2022-02-16 (thanks Google): https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html

I only think this will affect GA currently, since BigQuery uses Service Accounts.
But I wonder if this also causes problems for new Google Sign-In setups?

Trying to setup a new Google Analytics will fail with:
```
Authorization Error

Error 400: invalid_request

If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob
```
![image](https://user-images.githubusercontent.com/1447303/157075405-e6295b8d-2368-4ed9-b4a5-a7b031fe761f.png)

While we're at it, let's look at #17429 too.

**Comment by camsaul** [comment]
The page seems to suggest you can add `ack_oob_shutdown=2022-10-03` to the request URL as a temporary workaround but it doesn't seem to work for me

**Comment by camsaul** [comment]
#17429 looks like it doesn't affect Google Analytics. Only Google Auth

**Comment by ds-clearago** [comment]
Adding a link to https://www.metabase.com/docs/latest/databases/connections/google-analytics#google-cloud-platform-creating-a-service-account-and-json-file here for users who got the deprecation email from Google, are wondering what to do end end up on this PR
