### ISSUE TITLE
Cannot Filter Custom Column from Database View

### ISSUE THREAD

**Issue by ccalby** [metabase/metabase#20881]
**Describe the bug**
After creating a custom view merging 'first_name' and 'last_name' together to form 'whole_name', I am unable to filter this column through a Dashboard. I can filter the 'whole_name' column through the Question, however.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
Create a custom view in the database with a custom column (i.e. concat first name & last name of users to create 'whole name'). 
Create a question with the view. You will be able to filter by your 'whole name' custom column within the question.
On adding the question to a Dashboard, you will be unable to filter your custom 'whole name' column.

What should happen is the filter can be mapped to your 'whole_name' column. 

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.19.0-18-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.21-0ubuntu0.20.04.4"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Additional context**
Filtering the column is allowed through data models. Set to 'category' or 'user'. Makes no difference.

**Comment by flamber** [comment]
Hi @ccalby 
I cannot reproduce.
But have a look at https://www.metabase.com/docs/latest/troubleshooting-guide/filters.html
And include the output of `/api/field/123`, where 123 is the ID of the field, which you can find in the URL by going to Admin > Data Model > (db) > (table) > (field) :gear: > look in the URL `.../123/general`
