### ISSUE TITLE
Subdimensions/binnings do not exist for time column

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#20882]
For a column of the `time` type, there is no subdimensions. This is unlike `timestamp`.

**To Reproduce**

First create a table in e.g. PostgreSQL that contains some columns with `time`, e.g.

```
CREATE TABLE test.test (
	"time" time NULL,
	"timestamp" timestamp NULL,
	count integer NULL
);
```

and the populate it with some data.

1. New, Question
2. Choose the above database and table
3. Summarize, Number of distinct values of
4. Highlight `Timestamp` and we got several choices of subdimensions (correctly, as expected)

![image](https://user-images.githubusercontent.com/7288/157150438-c5cb1eff-cb95-4d43-a12c-6631d7ff8cc4.png)

5. **However**, try to choose `Time` and there is **no way** to choose a subdimension

![image](https://user-images.githubusercontent.com/7288/157150531-00ac6644-bbcb-4ee2-805d-3c7035625d4c.png)

**Expected behavior**

In Step 5, there should be a choice of dimensions for `Time` column, just like it is for Step 4 (for `Timestamp` column).

**Comment by ariya** [comment]
The potential source for the restriction is in here: https://github.com/metabase/metabase/blob/v0.42.2/src/metabase/api/table.clj#L216

**Comment by flamber** [comment]
Very related to #17598. The UI should probably not default to binning by Month if there's no bucketing info.
