### ISSUE TITLE
Reassign dashboards from an inactive  user

### ISSUE THREAD

**Issue by sandeshkumar07** [metabase/metabase#20906]
We are trying to re-gain access to this dashboard which was previously owned by a presently inactive user. The queries are broken currently. Is there a way to revive this dashboard and all related queries?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Unarchive the dashboard: https://www.metabase.com/docs/latest/users-guide/collections.html#archiving-items
