### ISSUE TITLE
When changing collection permissions "include subcollections" doesn't work

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#20911]
**Describe the bug**
I was adding a group to having the "curate" permission on a folder (collection #399 in our status instance)
I clicked on "include subcollections", but it didn't propagate.

**Logs**
N/A

**To Reproduce**
1. Go to collection 
2. Click on permissions
3. Scroll down to group in question, add curate bit, select "include subcollections" toggle
4. Click Save
5. Reload and there's no change

**Expected behavior**
Collection + subfolders would have permissions set 

**Screenshots**
N/A

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome Version 98.0.4758.109
- Your operating system: OS X 11.6
- Your databases: Postgres
- Metabase version: latest master, hash 8b7971b
- Metabase internal database:Postgres

**Severity**
Pretty annoying as manually adding permissions to a bunch of folders is a lot of tedious work

**Comment by salsakran** [comment]
this seems to work from the admin panel version of collection permissions

**Comment by flamber** [comment]
From what I can tell, it's because you selected "Curate" **before** enabling "Also change sub-collections".
If you first enable "Also change sub-collections" and then select the permission level you want, then it will work as intended.

Not a very intuitive behavior. Likely related #17573

**Comment by nemanjaglumac** [comment]
I can confirm what Flamber said, and have explained the mechanism in detail in https://github.com/metabase/metabase/issues/24355.

**Comment by nemanjaglumac** [comment]
Didn't want to open a new issue for this.
But when one tries to edit collection permissions from the collection page (not from the admin permissions page), it's not even possible to do it because the "Save" button never gets enabled
![image](https://user-images.githubusercontent.com/31325167/234852684-8a58e8d2-0fb8-452b-8325-961f8d5679f1.png)
