### ISSUE TITLE
Embedding Preview of questions does not limit the results in visualization, which can freeze the browser

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20938]
**Describe the bug**
Embedding Preview of questions (not dashboards) does not limit the results in visualization, which can freeze the browser, if there's a million results. This only affects the Preview, not the actual embed.

This means it can become difficult to even enable ("Publish") embedding for a question unless manually limiting the amount of rows of the question, saving, then enable embedding, then remove the manual limit.

Regression since 0.38.0

**To Reproduce**
1. Question > Sample > Orders - save as "Q1"
2. Sharing > Embed - notice the preview takes a bit longer and it has all the rows instead of the hardcoded 2000
![image](https://user-images.githubusercontent.com/1447303/157681873-fb5d594a-de9e-41d8-ae51-a2e299d486e5.png)

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.42.2 - regression since 0.38.0

**Additional context**
There seems to be some inconsistencies with the endpoints of Preview, as noted in #14309

**Comment by nemanjaglumac** [comment]
I can't test this using Cypress for two reasons:
1. iframe limitation
2. for whatever reason, I'm seeing the 2000 row limit using Cypress, but I can clearly reproduce the issue manually in my local dev environment

Cypress screenshot
![image](https://user-images.githubusercontent.com/31325167/158362346-bfc1743b-7212-4e72-b7fa-5be322cf67f0.png)
