### ISSUE TITLE
JOINs not working with filters in a multi-schema DB setup?

### ISSUE THREAD

**Issue by jhdavids8** [metabase/metabase#2093]
Hey all, I just deployed the latest version of Metabase to Heroku and connected it into my multi-schema Postgres DB. In the Question creator, once I select a schema and my initial table, adding any filters on a JOINed table results in 0 results.

For example, if I do a simple count of comments created in the "test" schema, I get back a logical number. If I add a filter on any user column, say one to only consider users with an activated account, I'm told there are no results. That's certainly not the case.

I wonder if this has anything to do with #1583?

**Comment by agilliland** [comment]
I'm not sure I completely follow the example you gave.  Are you saying you have 2 tables in a schema called `test` and joining them is not working?  Or are you saying that the tables are themselves in different schemas?  Such as trying to join `test.comments` with `other.users`?

**Comment by jhdavids8** [comment]
The former. I have a multi-tenanted setup that leverages schemas and thus I primarily work in a single schema at all times. So in the question creator, I'm first asked to select a schema, so I do (``test``). I then select a table (``test.comments``) and ask for a count of rows. All good to this point. But then, if I add a filter and ``JOIN`` on another table (``test.users``, or the users that left the comments), I'm always told the count is 0. Filters on the original selected table (``test.comments``) work fine, but venturing outside ``comments`` leads to these issues.

**Comment by jhdavids8** [comment]
I'm working around it by writing raw SQL, which is giving me correct results. But the question creator is largely useless beyond the simplest queries in my setup

I can provide more info about my setup if you need it and am happy to help however I can, beyond actually helping debug the code (Clojure is not in my toolbox) :smile:

**Comment by agilliland** [comment]
I'm not able to reproduce this.  I've just tried creating a query where all the tables are together in a specific schema and it worked just fine.  For example ...

<img width="867" alt="screen shot 2016-03-06 at 8 31 56 am" src="https://cloud.githubusercontent.com/assets/1987787/13555481/56f88e04-e376-11e5-8ad8-aaa0e61e6d94.png">

What version of Metabase are you using and what version did you first start using Metabase?  We started out the first couple versions of the product with no real support for schemas so it's possible that if you started with an early version you'll need to fix up some of your metadata.

**Comment by jhdavids8** [comment]
I deployed this yesterday to Heroku from the deploy button at http://www.metabase.com/start/heroku.html, so I should certainly be on the latest version....

**Comment by jhdavids8** [comment]
One sec, I'll see if I can get you a screenshot that doesn't give too much away about my setup :)

**Comment by jhdavids8** [comment]
Ok, see the below. Here's the total comments in a test schema:
![total_comments](https://cloud.githubusercontent.com/assets/811258/13555526/4a68a3da-e390-11e5-8dee-9a4720d8bca1.png)

I then filter on users on a boolean flag that is non-nullable, so every row should have this set to true or false. Regardless of the filter, I get 0:
![total_activated_comments](https://cloud.githubusercontent.com/assets/811258/13555524/4a66c7fe-e390-11e5-8f73-93d63018e33f.png)

![total_non_deactivated_comments](https://cloud.githubusercontent.com/assets/811258/13555525/4a678108-e390-11e5-8349-22a5383b3d6f.png)

**Comment by jhdavids8** [comment]
FYI, I can seemingly reproduce this for every table and filter type (boolean, integer, etc). So the only common pattern I can identify is the fact the filter is on a JOINed table....

**Comment by jhdavids8** [comment]
Ok, I was able to actually get this working on a local (development) version of my database, so there's something about my production metadata that is causing this. My development version follows the same schema but is certainly less robust than my production schema (development has 5 schemas and significantly less rows vs several dozens of schemas for production).

Any ideas on how I can debug further?

FYI, I was able to verify the same behavior in both the deployed Heroku version and the Metabase Mac app.

**Comment by agilliland** [comment]
The number of schemas shouldn't actually matter, but I suppose that could somehow be related.

When you run these queries do you see any errors at all in the application logs?  I'm assuming no since it appears the queries are actually returning a 0 result, but it's worth checking.

After that the next thing to check is the configuration of the metadata.  If you go to the `Data Model` section in the admin panel and pick your database and then navigate to one of your Comments tables, what do you see for the foreign key specified columns.  Here's an example of what we want to be looking for ...

<img width="1096" alt="screen shot 2016-03-07 at 9 21 33 am" src="https://cloud.githubusercontent.com/assets/1987787/13577301/a6f6285a-e446-11e5-9578-c66c30dc3781.png">

In specific we are looking for what field the foreign keys are targeting, which is the second dropdown.

**Comment by jhdavids8** [comment]
I'll check the application logs shortly, but sadly, my Data Model page won't load though. On Heroku, it exceeds the 30 second timeout limit. Locally, in the Mac app, the app actually prevents me from viewing the Data Model, as it simply forces me back to the dashboard before it fully loads. 

But yeah, something about our production schema is obviously not playing well with Metabase given this and the above issues. Another issue to note - I deployed Metabase to Elastic Beanstalk originally actually. It was up and running for awhile, but after about an hour or so, the entire Beanstalk application completely crashed, and I found no way to get it back up (I had made no changes to cause the crash - I was actually away from my computer when I got the notification that it was down from AWS). I tried a few things - increasing the size of the plan, rebuilding the environment from scratch, etc - but it seemed permanently 'dead'.

Anyways, I'll check the app logs a bit later and will try to do some other digging. I can also try to dig into the DB to see if foreign keys appear to be set correctly. Any pointers on where I should look?

**Comment by agilliland** [comment]
Hmm .. 30 seconds is a really long time.  I can't imagine why it would be that slow unless you really had a ton of tables & fields for some reason.  

If we can't get that information from the UI then we'd have to go directly to the database to get it.  Can you login to your Heroku database directly and run this query?

```
select ot.schema, ot.name, of.name, dt.schema, dt.name, df.name 
from metabase_foreignkey fk 
join metabase_field of on fk.origin_id = of.id 
join metabase_table ot on of.table_id = ot.id 
join metabase_field df on fk.destination_id = df.id 
join metabase_table dt on df.table_id = dt.id;
```

This will produce a table like this which contains all the information we need to understand how the system is describing your FK relationships.  feel free to prune the list as you see fit because you'll probably have a lot in it, but having at least a handful of examples would help me figure this out.

```
+--------+---------------+--------------+--------+-----------+-------------+
| schema | name          | name         | schema | name      | name        |
+--------+---------------+--------------+--------+-----------+-------------+
| PUBLIC | ORDERS        | USER_ID      | PUBLIC | PEOPLE    | ID          |
| PUBLIC | ORDERS        | PRODUCT_ID   | PUBLIC | PRODUCTS  | ID          |
| PUBLIC | REVIEWS       | PRODUCT_ID   | PUBLIC | PRODUCTS  | ID          |
+--------+---------------+--------------+--------+-----------+-------------+
```

Regarding the Elastic Beanstalk deployment, that's the first I've heard of anything like that.  We run our own set of Metabase instances (15+) on AWS and I've never once had a problem with them.  It has been a very simple and reliable setup.

**Comment by jhdavids8** [comment]
Thanks for the help! What I've found is....well, interesting.

Something is *way off* with how Metabase interprets my schema. For every foreign key listed in this table, there is a row for the target table in each schema! Thus, for my ``comments`` and ``user_id`` example, there are dozens of rows, one for each ``users`` table in each schema. In fact, the entire table is 70,000 rows, so no wonder Heroku was timing out!

````
+--------+---------------+--------------+--------+-----------+-------------+
| schema | name          | name         | schema | name      | name        |
+--------+---------------+--------------+--------+-----------+-------------+
| test   | comments      | event_id     | test1  | events    | ID          |
| test   | comments      | event_id     | test2  | events    | ID          |
| test   | comments      | event_id     | test3  | events    | ID          |
+--------+---------------+--------------+--------+-----------+-------------+
````

Also, remember how I said this wasn't happening with a development version of my database I plugged into the Mac app? I was actually wrong there. It is happening there too, but with the single example I tested and the fact there were significantly fewer schemas, it just so happened that the schema chosen was the right one, so it appeared to work. But looking at the Data Model for that database, I often see rows like this. This was a screenshot taken for a table in the ``pg`` schema that has foreign keys referencing totally different schemas.

![screen shot 2016-03-07 at 10 05 47 pm](https://cloud.githubusercontent.com/assets/811258/13590798/f8aacf10-e4b0-11e5-85b2-b8b10fa6192a.png)

And, as if we needed more proof, looking at the app logs as I build questions does show it trying to JOIN across schemas.

To sanity check myself, I opened up ``psql`` and had it list out foreign keys, and everything looks normally there. ``SELECT * FROM information_schema.table_constraints WHERE constraint_type = 'FOREIGN KEY';`` only has 1 row for each foreign key, with no cross-schema references. So whereas Metabase created 70,000+ rows for our foreign keys, the above listed only a couple thousand rows. If I do the math with the number of schemas we have, i can make sense of the 70,000 number now.

Please let me know how I can help further guys! Would love to help get this fixed :smile:

**Comment by agilliland** [comment]
Did you create this Metabase instance starting from the latest release (v0.15.0)?  or had you installed a previous version and upgraded?

**Comment by jhdavids8** [comment]
Yep. I created it on Saturday via [the Heroku deploy button](http://www.metabase.com/start/heroku.html)

**Comment by agilliland** [comment]
okay, I've found the problem and fixed it as part of our upcoming patch release.

the issue was a bug in the function which describes the FK relationships for a given table and that function wasn't properly filtering the returned list by schema.  Unfortunately the behavior of the jdbc code in this situation is to return all tables that match by name.

**Comment by jhdavids8** [comment]
Excellent! Thanks for digging into that so quickly.

**Comment by agilliland** [comment]
okay @jhdavids8 , the new release is out and the bug you were experiencing should be fixed.  

You'll need to do one thing to tidy up the old mess though.  Just login to your db and execute `delete from metabase_foreignkey;`  This will clear out the old mess of broken FK relationships described on your database right now.  After doing that you just need to sync your database again and Metabase will pick up the proper FK relationships scoped by schema and things should work as expected.

**Comment by jhdavids8** [comment]
Looks good thus far! Again, really appreciate the quick turnaround.

**Comment by agilliland** [comment]
good to hear!  and n/p.  thanks for filing issues and helping us find things that are broken.
