### ISSUE TITLE
Remove entry from Bookmark list when it is archived in a collection page

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#20934]
### Steps to Reproduce

1. Create a question
2. Bookmark it
3. Go to http://localhost:3000/collection/root
4. Archive the question you've created using the kebab menu

## Current outcome

Question is removed from main list, but not from the bookmarks

## Desired outcome

Question is removed from main list as well as from the bookmarks.

**Comment by qwef** [comment]
Works now on msater
