### ISSUE TITLE
Field Filter Not Working Metabase - BigQuery

### ISSUE THREAD

**Issue by raghebsalma** [metabase/metabase#20957]
I'm trying to use the filed filter but it throws me this error in Metabase.
PS: I'm using BigQuery and I removed the aliases as said by the Metabase user guide about field filters in BQ
Here is the code: (The two back ticks before and after the path are counted as one in the query)

`SELECT ``database.dataset.table``.column
FROM ``database.dataset.table``
WHERE [[{{column}}]]`

**Here is the error message:** 

400 Bad Request POST xxxxxxxxxx { "code" : 400, "errors" : [ { "domain" : "global", "location" : "q", "locationType" : "parameter", "message" : "Unrecognized name: `database.table` at [8:13]", "reason" : "invalidQuery" } ], "message" : "Unrecognized name: `database.table` at [8:13]", "status" : "INVALID_ARGUMENT" }

**Comment by flamber** [comment]
Hi @raghebsalma 
There's no "database" in BigQuery. There are projects, datasets and tables. Do this:
```
SELECT column FROM `dataset.table` WHERE {{fieldfilter}}
```
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#some-databases-require-the-schema-in-the-from-clause
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
