### ISSUE TITLE
Cannot convert SQL question with Snippet to Model

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20963]
**Describe the bug**
Cannot convert SQL question with Snippet to Model

Workaround - remove the snippets, save the question, then convert to Model, then edit the query definition and add the snippets.

**To Reproduce**
1. Native > Sample > Snippets sidebar, create a snippet like `'test'` and add it to the editor, so the query is something like this:
`select {{snippet: String 'test'}}`
![image](https://user-images.githubusercontent.com/1447303/157881178-25dfbe54-26f9-43b8-b428-0994015e104b.png)
2. Save question and try to convert to Model - is being blocked by the message `Variables in models aren't supported yet`, and says that snippets are allowed
![image](https://user-images.githubusercontent.com/1447303/157881397-578be3e0-4642-4204-a478-6d5ad9bf6107.png)

**Information about your Metabase Installation:**
Tested 0.42.0 thru 0.42.2

**Comment by matdgz** [comment]
Hey,
Actually it works sometimes, even with snippets. But I cannot say when it works and when it does not.

**Comment by WiNloSt** [comment]
@flamber I forgot what's the solution we want for this? Is it that
1. We allow converting questions with static snippets (no variables) to models or
2. We change the error message to reflect that we don't allow snippets when converting to models

But based on the workaround you described
> Workaround - remove the snippets, save the question, then convert to Model, then edit the query definition and add the snippets.

I assume it's 1. As the end result of the workaround is like allowing creating a model with static snippets.

**Comment by flamber** [comment]
@WiNloSt Yes, if it is technically possible to use [Snippets](https://www.metabase.com/docs/latest/users-guide/sql-snippets.html) on Models, then we should allow that. If there are problems (aka technical limitations like with Variables), then change the error message.

**Comment by amorrissey-veho** [comment]
I am getting this error when I am not using snippets. Is there another thread on that issue somewhere?

**Comment by flamber** [comment]
@amorrissey-veho If you aren't using snippets, then you are likely using other variables. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
