### ISSUE TITLE
Metabase filters are not functioning properly after upgrade

### ISSUE THREAD

**Issue by lehagere** [metabase/metabase#20962]
I use a free version of Metabase and my filters used to have a dropdown as a recommendation and I could pick one and then it will all work smoothly. But as you can see on the image, all inputs except the date range are not functioning as they used to. I can only type my entries without any recommendation.

![image](https://user-images.githubusercontent.com/4033890/157876514-27395243-facf-4497-a4a9-389c1343b5d6.png)

My version is v0.41.6 and I have made an update to the latest version because of the log4j issue.

I don't see any error on the Metabase log.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1-post-Debian-1deb10u2",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1-post-Debian-1deb10u2",
    "os.name": "Linux",
    "os.version": "5.7.0-0.bpo.2-amd64",
    "user.language": "en",
    "user.timezone": "Africa/Addis_Ababa"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-01-10",
      "tag": "v0.41.6",
      "branch": "release-x.41.x",
      "hash": "296635f"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
Hi @lehagere 
Which version did you upgrade from? Latest release is 0.42.2: https://github.com/metabase/metabase/releases/latest
It is not clear from your screenshot what is happening, and there's no steps-to-reproduce.
Have a look here: https://www.metabase.com/docs/latest/troubleshooting-guide/filters.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
