### ISSUE TITLE
Allow showing the absolute time of a question "last edited" date

### ISSUE THREAD

**Issue by Caerbannog** [metabase/metabase#20973]
**Is your feature request related to a problem? Please describe.**
The "last edited" date of a question is displayed as relative time (ex: "20 days ago").
There is no way to show a more precise value in the UI.

When you are trying to understand past changes, it can be painful.
You can't tell if Question 1 was modified before Question 2 if both are shown as "last edited: 1 year ago".

**Describe the solution you'd like**
A simple solution would be to show the absolute time ("2022-03-11 23:04:55") in a tooltip, like a lot of website do.
[Here is a rationale for this UX pattern.](https://uxmovement.com/content/absolute-vs-relative-timestamps-when-to-use-which/#:~:text=use%20tooltip%20timestamps)

**Describe alternatives you've considered**
I've looked at the page source in the browser, the absolute time was not around.

**How important is this feature to you?**
It has low impact, but it's probably an easy fix. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Sounds very reasonable. We kinda already do it on the collection list. Should account for timezone too #17829.
