### ISSUE TITLE
PostgreSQL as Metabase Application Database 

### ISSUE THREAD

**Issue by haytastan** [metabase/metabase#20985]
**Describe the bug**
Though I can list the users (i.e. accounts) of my Metabase Application Database (MAD) in PostgreSQL (v14) environment by means of metabase API (https://mydomain/api/user?status=active), I can't see those users in the core_user table in the public schema of the MAD (namely "metabase") using pgAdmin connected to the ubuntu server at , as shown below.
![image](https://user-images.githubusercontent.com/7123870/158165479-fac3a57b-f050-4655-9166-4aacdb4a6447.png)

**Logs**

**To Reproduce**

**Expected behavior**
core_user table should show the accounts of Metabase Application Database just as like metabase API (https://mydomain/api/user?status=active) shows.

**Screenshots**

**Severity**
low

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "tr-TR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.4.0-58-generic",
    "user.language": "en",
    "user.timezone": "Europe/Istanbul"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-08",
      "tag": "v0.42.0",
      "branch": "release-x.42.x",
      "hash": "de1264e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Use the forum: https://discourse.metabase.com/t/postgresql-as-metabase-application-database/19155
