### ISSUE TITLE
Metabase fails to run on Java 7

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2098]
This happened after the introduction of the [`aleph`](https://github.com/ztellman/aleph) package in #2088

**Comment by agilliland** [comment]
@camsaul I'm assigning this to you to be part of the Metabot tweaks when you get to them.  simple end goal is that we want Metabase to work on Java 7 which is currently not possible due to the `aleph` dependency.

**Comment by camsaul** [comment]
Any more details on *why* it won't run on Java 7? (Any specific errors, etc. would be helpful; there might be a way to keep `aleph` and work around whatever problem it's causing)

**Comment by agilliland** [comment]
I don't have the error still, but I'm pretty sure it was a ClassNotFoundException for a class that was new in Java8

**Comment by camsaul** [comment]
```java
java.lang.ClassNotFoundException: java.util.concurrent.CompletableFuture
```

**Comment by camsaul** [comment]
https://github.com/ztellman/manifold#java-8-extensions
