### ISSUE TITLE
First Day of Week Setting off by one in Snowflake

### ISSUE THREAD

**Issue by AndrewLWilson** [metabase/metabase#20999]
**Describe the bug**
When grouping by week in the question editor, the date ranges start on the day of the week **one day after**  what is set in the Localization Settings.  For instance, when we set our "First Day of Week" setting set to Sunday, the date ranges start on Monday.  We are not setting any JDBC connection string options in the database connection settings. We do have our Snowflake account WEEK_START parameter set to 1 on the account level, however changing it does not affect the issue.

Also to note, the Metabase SQL editor is not affected by the "First Day of Week" setting.  It is being correctly controlled by our Snowflake account and session WEEK_START parameter.

First Day of Week set to Sunday:
<img width="630" alt="Screen Shot 2022-03-14 at 1 49 45 PM" src="https://user-images.githubusercontent.com/83972010/158258855-2cc4551b-092b-4c1f-9f19-23e13e2fed6d.png">

In the Question Editor, week groups start on Mondays (this is the issue):
<img width="274" alt="Screen Shot 2022-03-14 at 1 42 52 PM" src="https://user-images.githubusercontent.com/83972010/158257888-f4920796-a95c-48be-ab3c-b5c1dadaadc8.png">

**Logs**

```
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:12-07:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 9.1 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (14 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:12-07:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 14.8 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (14 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:12-07:00 DEBUG metabase.server.middleware.log GET /api/table/3393/query_metadata 200 17.7 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (14 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:12-07:00 DEBUG metabase.server.middleware.log GET /api/database 200 9.8 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (14 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:13-07:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 644.1 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 2/50 (15 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued); snowflake DB 9 connections: 0/1 (0 threads blocked)
```

**To Reproduce**
1. Using a Snowflake database, group a timestamp or date column by week in the question editor.
2. Notice that the date ranges all start 1 day after the "First Day of Week" Localization setting is set to.

**Expected behavior**
When grouping by week in the Question editor, the date ranges should start on whatever is set for "First Day of Week".

**Screenshots**

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.14.262-200.489.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

This is annoying verging on blocking at our organization.  We have both Snowflake and Postgres databases set up in Metabase, and having to pick which one has the correct week_start is causing a big headache.

**Additional context**
I know that PR #19375 was supposed to address the "First Day of Week" setting in Snowflake, but we are still having this off by one problem.

**Comment by flamber** [comment]
Hi @AndrewLWilson 
Try setting the connection string in Admin > Databases > (your-db) > Advanced to `WEEK_START=1` otherwise Metabase will automatically used WEEK_START=7

**Comment by AndrewLWilson** [comment]
> Hi @AndrewLWilson
Try setting the connection string in Admin > Databases > (your-db) > Advanced to WEEK_START=1 otherwise Metabase will automatically used WEEK_START=7

I just tried and it made no difference, the date ranges still show up one day after they are set to.

**Comment by flamber** [comment]
Feels like #17801 is involved too, but this is a regression since 0.42.0

Reproduce:
1. Admin > Settings > Localization > First day of the week = "Monday"
2. Question > **Snowflake** v3_sample-dataset > People - filter Birth Date = "12/12/1986" - summarize Count by BirthDate:DayOfWeek
![image](https://user-images.githubusercontent.com/1447303/160480637-a25ea7ba-b45b-4466-ae90-44e9a7b21feb.png)
3. Admin > Databases > (snowflake) > Connection String `WEEK_START=7` (yes, Sunday, even though we want Monday)
Redo step 2:
![image](https://user-images.githubusercontent.com/1447303/160482028-4d064dd6-0f1b-4acb-a3d3-1747e17add28.png)

**Comment by escherize** [comment]
This bug is trickier than I originally thought, but I did find some things about it.

This happens only when the WEEK<sub>START</sub> parameter (<https://docs.snowflake.com/en/sql-reference/parameters.html#week-start>) is set (either on Account, Session, or Object modes).

Some observations:

-   removing [this](https://github.com/metabase/metabase/blob/slack-startup-updated-at-can-be-nil/modules/drivers/snowflake/src/metabase/driver/snowflake.clj#L52) `inc` doesn&rsquo;t fix it.
    -   (this inc is used to convert from metabase&rsquo;s internal day of week integers):
    -   in metabase: 0 is :monday, &#x2026; 6 is :sunday
    -   in snowflake: 1 is :monday, &#x2026; 7 is :sunday
-   also to note, in snowflake setting `WEEK_START` to 0 will make it behave differently (<https://docs.snowflake.com/en/sql-reference/functions-date-time.html#first-day-of-the-week>)
    -   which is why we send 1-7, and not 0.
-   <https://github.com/metabase/metabase/blob/master/modules/drivers/snowflake/src/metabase/driver/snowflake.clj#L89>
    -   handle-additional-options is suspect.
    -   the first arg has a lot of processing (including `maybe-set-week-start`), but the second one is the raw `opts`. and the 2nd arg is used to set the additional properties. Changing it alone didn&rsquo;t seem to fix anything, though

Server side values / settings to watch:

-   `start-of-week` defsetting
-   `(driver.common/start-of-week-setting->int)`
-   `(driver/db-start-of-week :snowflake)`
    -   this is always `:sunday`
-   `:week_start` value in details.additional-options
    -   the client can pass us a desired week<sub>start</sub> value (an integer) that we pass to snowflake as a session parameter.

**Comment by camsaul** [comment]
SQL generated when start of week is Sunday (and we get correct results)

```sql
SELECT 
  date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) AS "birth_date",
  count(*) AS "count" 
FROM 
  "v3_sample-dataset"."PUBLIC"."people" 
WHERE ("PUBLIC"."people"."birth_date" >= ? AND "PUBLIC"."people"."birth_date" < ?) 
GROUP BY 
  date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) 
ORDER BY 
  date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) ASC
```

SQL generated when start of week is Monday (and we get incorrect results)

```sql
SELECT 
  CASE WHEN ((date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) + -1) % 7) = 0 THEN 7 ELSE ((date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) + -1) % 7) END AS "birth_date",
  count(*) AS "count" 
FROM 
  "v3_sample-dataset"."PUBLIC"."people" 
WHERE ("PUBLIC"."people"."birth_date" >= ? AND "PUBLIC"."people"."birth_date" < ?) 
GROUP BY 
  CASE WHEN ((date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) + -1) % 7) = 0 THEN 7 ELSE ((date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) + -1) % 7) END 
ORDER BY 
  CASE WHEN ((date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) + -1) % 7) = 0 THEN 7 ELSE ((date_part("dayofweek", CAST("PUBLIC"."people"."birth_date" AS timestamp)) + -1) % 7) END ASC
```

I think maybe the issue is that we're setting both `WEEK_START` on the connection AND adjusting the start of week in the SQL which is why everything is off

**Comment by camsaul** [comment]
To make this a little easier to think about

| Day of Week | Metabase Integer | Snowflake Integer |
| - | - | - |
| :monday | 0 | 1 |
| :tuesday | 1 | 2 |
| :wednesday | 2 | 3 |
| :thursday | 3 | 4 |
| :friday | 4 | 5 |
| :saturday | 5 | 6 |
| :sunday | 6 | 0 |
