### ISSUE TITLE
Document the "APPROVED DOMAINS FOR NOTIFICATIONS" setting

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21014]
We missed that setting on the new launch, right now it defaults to blank, but it could make a great difference for admins
![image](https://user-images.githubusercontent.com/1711649/158444312-a36bb452-df02-47cc-a1ee-03a6ea208bc4.png)

**Comment by jspencerhopkins** [comment]
@paoliniluis thanks for posting this.  Just encountered an snag on my end of how to add multiple domains in the "APPROVED DOMAINS FOR NOTIFICATIONS" field.   I've tried delimiting by semicolon and comma -- however using either of them issues a warning when trying to set up a new Dashboard subscription.  Would you happen to know what the proper syntax for delimiting domains in that specific field?

**Comment by flamber** [comment]
@jspencerhopkins The description string has been updated in the upcoming v43 to this:
> Allowed email address domain(s) for new Dashboard Subscriptions and Alerts. To specify multiple domains, separate each domain with a comma, with no space in between (e.g., `domain1,domain2`). To allow all domains, leave the field empty. This setting doesn't affect existing subscriptions
