### ISSUE TITLE
Do we still use the LimitWidget component?

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2102]
I'm less familiar with the query builder code than I used to be but it seems like we have a ```LimitWidget``` component at /frontend/src/query_builder/LimitWidget.jsx that I can't seem to find a callsite for. There's also a ```renderLimit()``` function in GuiQueryEditor that seems to be doing the same thing. Seems like a potential opportunity to consolidate / dead code eliminate.

**Comment by tlrobinson** [comment]
Doesn't look like it. BTW now that we use JS modules you can just try removing the file and if webpack doesn't complain then it's not used (this isn't true for the remaining Angular code though)
