### ISSUE TITLE
async.ThreadPoolAsynchronousRunner deadlock

### ISSUE THREAD

**Issue by hden** [metabase/metabase#2104]
*  I am using the no browser.
*  My computer's OS is Debian 3.2.46-1+deb7u1 x86_64.
*  My database is MySQL 5.6.19.
*  My Metabase version is 0.15.0.

A series of error message were raised along with high CPU usage e.g.

```
WARN async.ThreadPoolAsynchronousRunner :: com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@49a63401 -- APPARENT DEADLOCK!!! Creating emergency threads for unassigned pending tasks!
```

Details can be found here:
https://gist.github.com/hden/df727a18effeaa0245bc

**Comment by agilliland** [comment]
This is just a warning from the connection pool software, so it's not a problem per se.  In this instance I suspect this is tied together with the `java.lang.OutOfMemoryError` that is further down your stack trace.  most likely some operation was performed which tied up the db connection and consumed more memory than your instance has available, which then led to the warning you saw.
