### ISSUE TITLE
Combining question modal does not wrap long question names

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21056]
**Describe the bug**
When adding series to a dashboard card, the names of the questions get cropped if they are long, so you can't see the full name and you might not know what you're adding

**Logs**
No logs

**To Reproduce**
1) create a dashboard
2) create 2 questions, one with a short name and another with a long long long name
3) add the first question to a dashboard and then add click the "add series" button on the first card to add the second one overlapped
4) see the long name being cropped

**Expected behavior**
Have a wrapping at least, or the famous "..." to see the full name as a tooltip

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/158816237-a900aff3-9cda-4fe2-ab3f-13736319d874.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: NA
- Your databases: Postgres
- Metabase version: master
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic

**Additional context**
NA

**Comment by flamber** [comment]
Regression since 0.41.0

**Comment by losrebellos** [comment]
@paoliniluis

As we can have 10k questions in the add series modal, we need to virtualized the dom to make sure we do not bring back the previous [performance issue](https://github.com/metabase/metabase/issues/13100).
The React virtualization library we are using needs the row heights which is incompatible with having long names wrapping as it will change the row height based on the number of lines for a title.
So, as discussed with @flamber, we now have an ellipsis for long question names with a popover (only present for question with an ellipsis) so we retain the performance optimization.

__Before__

![image](https://user-images.githubusercontent.com/348552/161769946-0fb39136-bfd5-4a6b-a0c1-540373670c73.png)

__After__

![image](https://user-images.githubusercontent.com/348552/161769076-7ac263a7-0173-4820-b4c3-1928db9903b8.png)
