### ISSUE TITLE
Downloads (metabase.jar, Metabase.app) should be served over HTTPS

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2107]

**Comment by agilliland** [comment]
I'm going to close this issue because it's captured in the other repository where the metabase website code lives.

**Comment by gardner** [comment]
@agilliland can you link me to that repo? thanks

**Comment by naggie** [comment]
I came here to report the same issue. The chain of trust is important! Thanks.

**Comment by camsaul** [comment]
For anyone interested all Metabase downloads are now served over HTTPS.
