### ISSUE TITLE
Ignore timescaledb tables when syncing postgres tables

### ISSUE THREAD

**Issue by 34code** [metabase/metabase#21120]
**Is your feature request related to a problem? Please describe.**
I think metabase is syncing timescaledb tables like the following which are really slowing things down while syncing for the first time..

- _timescaledb_catalog
- _timescaledb_config
- _timescaledb_internal
- timescaledb_experimental
- timescaledb_information

**Describe the solution you'd like**
Ignore the above tables upon initial sync

**Describe alternatives you've considered**
UI for removing those tables from metabase

**How important is this feature to you?**
Cannot use product without this

**Additional context**

**Comment by flamber** [comment]
Duplicate of #5500
