### ISSUE TITLE
Metabase field filter casts timestamp column instead of casting queried date

### ISSUE THREAD

**Issue by djdylan2000** [metabase/metabase#21133]
**Describe the bug**

Say I have an expense table in Postgres

```
CREATE TABLE expense (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL,
    performed timestamp with time zone NOT NULL,
    amount json NOT NULL,
);
```

And I create a metabase question to allow other people to query this easily for a user for some period of time.
In metabase, I could do something like

```
SELECT * from "expense" where 1 = 1 [[AND "user_id" = uuid({{user_id}} [[AND {{performed}}]]
```

where user_id is a text field and performed is a field filter (widget type - month and year)

If a userId is typed in and a the field filter is used to pick Feb 2022 for example, metabase generates a query like

```
SELECT * from \"expense\" where 1 = 1 AND \"user_id" = 'xyz' AND CAST(\"public\".\"expense\".\"performed\" AS date) BETWEEN timestamp with time zone '2022-02-01 00:00:00.000+01:00' AND timestamp with time zone '2022-02-28 00:00:00.000+01:00
```

If I have a multi column index on (user_id, performed), unfortunately only user_id part of the index can be used because of the cast as date function. 

IMO this is a performance bug -metabase should cast the arguments of the field filter to match the column type rather than the other way round, so that table indexes can be used efficiently.

I'm running the latest metabase as of today - v0.42.2

Using a function based index is not a workaround because casting a timestamp with timezone to date is not an immutable function.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Create a table in postgres with a timestamp with timezone column
2. Create a metabase question with that column used as a field filter with year and month
3. Create an index on the timestamp column
4. Run a postgres query filing in a month and year
5. Postgres casts the column in the where clause, causing the index to be useless

**Expected behavior**
Postgres should avoid casting the database column wherever possible and instead cast the query arguments to match the column datatype, so that indexes can be used efficiently

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.4.181-99.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
It is very annoying at present since we have a lot of queries that depend on this. It is not a major bottleneck now, but as our data grows we would have to consider other options as not having a date index used to cut down the search space would cause more and more inefficiency

**Additional context**

**Comment by Jarvis1Tube** [comment]
This behavior with `CAST`ing timestamps to dates makes query on column with index several times more slowly.
I think that the better solution is to give a user just to variables `{{<user_prefix>_start}}` and `{{<user_prefix>_end}}` or at least remove type casting.

**Comment by jonathanasquier** [comment]
Hello, I feel that I'm getting the same issue:
I have a timestamptz column un postgres
It is correctly interpreted as a date in the metabase datamodel
I'm using a date filter on the field
The redacted query is:
```
CAST("public"."my_table"."my_date" AS date) BETWEEN timestamp with time zone '2023-05-08 00:00:00.000+02:00'
```
=> takes 40s (seq scan, no index)

whereas
```
"public"."my_table"."my_date" BETWEEN timestamp with time zone '2023-05-08 00:00:00.000+02:00'
```
=> takes 7s (use of index, but costy conversion of timestamp with time zone
and
```
"public"."my_table"."my_date" BETWEEN '2023-05-08 00:00:00.000+02:00')
```
=> 56ms

Is there any work around that would prevent those extra casting ?
thanks !

**Comment by EliW** [comment]
Just ran into this issue myself when trying to debug some queries and found that the cast to (date) is killing the performance on my queries.  Obviously we still want to use the nice variable/filter/fields that exist here in metabase.   But having it cast the timestamps to dates, especially when there is no reason.  Is painful.

Example, the following is how one might write this query normally (created_on is a timestamp) ... this uses an index that we have, and comes up with a cost of just over 4000
```
explain
select count(DISTINCT uniq_hash)
from site_events
where category = 'analytics' AND event = 'pageView'
  AND created_on >= '2023-07-12' AND created_on <= '2023-07-18'
```

The following is (roughly, there's some extra ((('s in metabase's version) how metabase ends up creating this query.  This on our data switches from a cast of 4000, to over 700k making queries unusable
```
explain
select count(DISTINCT uniq_hash)
from wordpress_st_site_events
where category = 'analytics' AND event = 'pageView'
AND created_on::date >= '2023-07-12'::date AND created_on::date <= '2023-07-18'::date
```

**Comment by slvrtrn** [comment]
This one prevents the "Last X Minutes/Hours" FieldFilter from working with variables in ClickHouse driver. Under the hood, the `sql.qp/date [:driver :day]` method is called, which truncates DateTime columns to Date, effectively removing `hh:MM:ss` part from it, and it is unclear how it is supposed to work with minute/hour precision this way.

[This is the part where this happens.](https://github.com/metabase/metabase/blob/v0.47.2/src/metabase/driver/sql/parameters/substitution.clj#L238-L239)

`params.dates/date-type?` always yields true for `date/all-options`, and `date/all-options` is set as a `param-type` when we use date field filters via variables, and, as a result, the explicit cast from any Date*-related type to just `Date` is enforced.

Considering this Postgres scenario, it costs performance as the index is ignored, but the query still _somehow_ works. With ClickHouse specifically, the right-hand implicit upcast simply does not work: it is prohibited to compare a column of type `Date` with a string that represents _`DateTime`_.

I wrote [some tests](https://github.com/ClickHouse/metabase-clickhouse-driver/blob/982e0be30c8acef1e9329a11d6f5d4122ce30f5a/test/metabase/driver/clickhouse_substitution_test.clj) for this behavior that started to work when I changed this
```clj
:temporal-unit (when (params.dates/date-type? param-type) :day)
```
to this
```clj
:temporal-unit nil
```

To fix it on the driver level, at a glance, it is required to copy-paste a significant amount of code, as everything called by the default implementation of [`->replacement-snippet-info [:sql FieldFilter]`](https://github.com/metabase/metabase/blob/v0.47.2/src/metabase/driver/sql/parameters/substitution.clj#L297-L311) method is private and there is a significant amount of logic involved there.

**Comment by jwrascoe** [comment]
> Just ran into this issue myself when trying to debug some queries and found that the cast to (date) is killing the performance on my queries. Obviously we still want to use the nice variable/filter/fields that exist here in metabase. But having it cast the timestamps to dates, especially when there is no reason. Is painful.
> 
> Example, the following is how one might write this query normally (created_on is a timestamp) ... this uses an index that we have, and comes up with a cost of just over 4000
> 
> ```
> explain
> select count(DISTINCT uniq_hash)
> from site_events
> where category = 'analytics' AND event = 'pageView'
>   AND created_on >= '2023-07-12' AND created_on <= '2023-07-18'
> ```
> 
> The following is (roughly, there's some extra ((('s in metabase's version) how metabase ends up creating this query. This on our data switches from a cast of 4000, to over 700k making queries unusable
> 
> ```
> explain
> select count(DISTINCT uniq_hash)
> from wordpress_st_site_events
> where category = 'analytics' AND event = 'pageView'
> AND created_on::date >= '2023-07-12'::date AND created_on::date <= '2023-07-18'::date
> ```

@flamber  @EliW @jonathanasquier I am still seeing the date cast (on a pg datasource) in metabase:v0.49.7 ... is this issue supposed to be resolved?

**Comment by paoliniluis** [comment]
@jwrascoe no

**Comment by jwrascoe** [comment]
@paoliniluis any idea when this may be resolved?

**Comment by paoliniluis** [comment]
@jwrascoe probably very very soon

**Comment by jwrascoe** [comment]
@paoliniluis  That's fantastic, thanks for the update

**Comment by mayanala-coxauto** [comment]
We are also seeing the same issue where CASTing is killing the performance in metabase and our users will soon stop using metabase and run queries in Athena directly.

**Comment by jwrascoe** [comment]
@mayanala-coxauto hopefully it will come out soon.. there is a PR for it and @paoliniluis said its in the works.

**Comment by staal** [comment]
Our dashboards are heavily dependent on date filtering and are suffering a lot from this as we cannot utilize our most useful indexes optimally.

**Comment by mayanala-coxauto** [comment]
Can you please let us know why this is closed ? Even in the latest version 1.50.21, casting is needed if the field filter is of string type on the database. In this case queries are taking longer as casting has to happen to every row. We are looking for option on CASTing to happen on Right hand side instead so that queries are faster. 

Example:
Instead of this that runs long time if your data in the magnitude of Terabytes and p_date_hour column is string on Athena table. 
CAST("p_date_hour" AS timestamp) >= timestamp '2024-08-09 09:00:00.000' AND 
CAST("p_date_hour" AS timestamp) < timestamp '2024-08-09 10:00:00.000'

We are looking for an option where we Don't cast in the metadata for column p_date_hour and casting happens on right hand side. 

p_date_hour  >= CAST(timestamp '2024-08-09 09:00:00.000' as varchar) AND
p_date_hour < CAST(timestamp '2024-08-09 10:00:00.000' as varchar)

**Comment by mngr** [comment]
@lbrdnk could you please comment on this https://github.com/metabase/metabase/issues/21133#issuecomment-2319830308

**Comment by paoliniluis** [comment]
@djdylan2000 @Jarvis1Tube @jonathanasquier @EliW @jwrascoe @staal was the issue fixed for you? the case of @mayanala-coxauto is a specific case of partition pruning in Athena that we need to solve separately and we're discussing internally how we're going to make it

**Comment by ArthurNGN** [comment]
hello, I can confirm that it works for us as well (postgres 9.6 🦖)

**Comment by jwrascoe** [comment]
@ArthurNGN not sure about PG 9.6 we run PostgreSQL 16.1
