### ISSUE TITLE
Elastic Beanstalk: make reported CloudWatch metrics configurable

### ISSUE THREAD

**Issue by berlix** [metabase/metabase#21140]
**Is your feature request related to a problem? Please describe.**

Metabase in its default Elastic Beanstalk configuration reports ~329 CloudWatch metrics. This more than doubles the cost of operating Metabase, since each metric cost 0.3 USD/month. At our organisation, we actually don't need most of these metrics, so it would be good to be able to disable them somehow.

**Describe the solution you'd like**

Ideally, we'd be able to configure the set of reported metrics in some way that is persistent across re-deployments and upgrades of Metabase. I am not sure what would be the best way to technically achieve that.

**Describe alternatives you've considered**

What we're doing currently is to remove the metrics manually from the ZIP file's `.ebextensions/metabase_config/cloudwatch/config.json` before deployment. This is an error-prone process that needs to be repeated every time we update Metabase.

Another alternative could be to just cut down the set of metrics reported by default, to perhaps the 20 most important ones.

**How important is this feature to you?**

_Somewhat_ important? :-D

We upgrade Metabase frequently and are on a tight budget, so this is a bit of an annoyance.

**Additional context**

I hope it's clear, please ask for any additional context if necessary.

**Comment by paoliniluis** [comment]
We have deprecated shipping the Beanstalk artifacts, so this is no longer relevant. Users will have to build their own beanstalk artifacts from now on
