### ISSUE TITLE
Line Chart labels are incorrect

### ISSUE THREAD

**Issue by ejoncas-rivalbet** [metabase/metabase#21150]
## Context
Browser and the version: [Version 1.36.117 Chromium: 99.0.4844.74 (Official Build) (arm64)](https://brave.com/latest/)
Operating system: OS X 12.1
DB: PostgreSQL 14.x
Metabase internal database: Postgres 14.x
Metabase version 0.42.2
Metabase hosting environment: Docker on ECS

## Description

I'm confused with this behaviour but something is wrong. This is how my data looks like:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/72950483/159400054-e45fed53-c0d3-4cee-a221-f105b2ca62bf.png">

then when I visualize as a LINE chart there are no problems on hover, although I want the colored dots to show the legend. See that sent>received>opened

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/72950483/159400131-463bf307-4722-4019-b040-20d71b18d7e8.png">

Now after adding the "names" to the labels under the "Display" tab, see what happens:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/72950483/159400251-c8a33244-8c98-40b1-8929-e324d656929d.png">

## Test Case

With this query it can be replicated
```
select d, sent, received, open
from (
    values 
    (now(), 90, 80, 10), 
    (now()- interval '1 day', 120, 94, 23),
    (now() - interval '2 day', 40, 30, 15)
) s(d, sent, received, open);
```
See how I'm hovering on top of the lowest value (opened) and the tooltip shows correctly but the highlighted color shows a different label. Value `23` is for `opened` although the chart highlights `received`
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/72950483/159400681-9425d70b-d33c-45eb-8c65-e31c09386efb.png">

**Comment by flamber** [comment]
Hi @ejoncas-rivalbet 
I'm not quite sure what is going on, but try including the question metadata by going to `/api/card/123`, where 123 is the question ID. Think there's some corrupted settings somewhere.
I cannot reproduce with your test case, but I think you are getting confused by the split Y-axis, which you can disable in visualization Settings > Axes > disable "Use a split y-axis when necessary" - upvote #12939

**Comment by ejoncas-rivalbet** [comment]
@flamber yes you're correct, that setting was making it look incorrect. See

## Setting OFF
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/72950483/159588609-eacd9456-48e7-4cc7-9aa0-1b6f807984eb.png">

## Setting ON
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/72950483/159588643-c2ff00f2-6b42-4dda-9d97-ca615e065025.png">

I understand what the setting is doing now. Although I don't think any user would want that by default, it's quite confusing (i didn't know that setting existed to be honest). 

Maybe in this example the numbers are not so close to each other but having a separate axis makes the line cross each other when the values do not really overlap in the dataset.

The feature is good, it just needs more clarity, maybe the numbers on the y-axis need to match the color of the line that it represents.

I'm closing this ticket there is nothing to fix, my confusion. Thanks for the help!
