### ISSUE TITLE
Trend appears to calculates % between last month and month prior to that completely wrong

### ISSUE THREAD

**Issue by OnFormLimited** [metabase/metabase#21153]
**Describe the bug**
Trend calculates % between last month and month prior to that completely wrong

**To Reproduce**
Run report!

**Expected behavior**
66% or similar

**Screenshots**
![image](https://user-images.githubusercontent.com/87531080/159463962-7b55b23d-3e7c-4930-b185-84223a5bb26c.png)

**Severity**
Failure of basic functionality is concerning

**Additional context**
I need to be sure of what the calculation is actually doing to ensure this is a bug.

So - if in filter I have stipulated a date 'At Previous 2 Months' (as below)
![image](https://user-images.githubusercontent.com/87531080/159464807-d3c278cb-f8b7-4d4c-a84b-ce8e004d864e.png)
am I to presume it is comparing those 2 months for the trend? 
OR
Is it comparing the current month -v- the sum of those 2 prior months?

**Comment by flamber** [comment]
Hi @OnFormLimited 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It is impossible to reproduce the bugs you create, since it requires access to your data, which only you have.
