### ISSUE TITLE
Add more than one metric on the same output

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2121]
When using Metabase, we usually have created separated charts for targets and real values. Thats just because we can't add both metrics on the same question, like 'sum of target sales' + 'sum of sales'.

This kind of option would be great if possible.

A ugly example with the good old Excel: (red is the second metric)
![image](https://cloud.githubusercontent.com/assets/1953457/13656716/131e199a-e648-11e5-8425-c64c22b17732.png)

**Comment by MrMauricioLeite** [comment]
Added an ugly example

**Comment by camsaul** [comment]
By "metric" do you mean the various aggregations from this menu?

![screen shot 2016-03-09 at 5 45 13 pm](https://cloud.githubusercontent.com/assets/1455846/13656763/b2da7e9e-e61e-11e5-97ba-ef140625bacf.png)

**Comment by camsaul** [comment]
(i.e. you'd like to be able to select more than one of those)

**Comment by salsakran** [comment]
Also note that you can do this in a dashboard - 
http://www.metabase.com/docs/v0.15.1/users-guide/09-multi-series-charting.html

The query builder is currently optimized for quick one-off analyses.

**Comment by MrMauricioLeite** [comment]
I've just readed this on the documentation. Please ignore this post, it seems I overlooked the docs..
http://www.metabase.com/docs/v0.15.0/users-guide/09-multi-series-charting

Sorry guys.
