### ISSUE TITLE
Allow to resize or give extra space to specific card

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2122]
When adding cars to a dashboard, very often I want to let a card take up the entire first row or split in two columns.

If there is any way to add some control for that, would be nice.

**Comment by camsaul** [comment]
Hi @MrMauricioLeite, if you click the edit icon on a dashboard (this pencil in the upper-right corner), you'll be able to resize cards in your dashboard.

**Comment by MrMauricioLeite** [comment]
Sorry @camsaul I just saw that by hovering the lower right corner I can resize the card, I'll open a new issue to make use of an Icon on that corner or something to make obvious that there you can resize the card. Ok?
