### ISSUE TITLE
regression: autocomplete in dashboard filters does not work

### ISSUE THREAD

**Issue by codingjoe** [metabase/metabase#21248]
**Describe the bug**

**Logs**
No special warnings or errors in the JS or Java console :(

We got user reports about this behavior about 2 weeks ago. We usually update to new releases immediately.

**To Reproduce**
1. Go to a dashboard with a filter on some category or title field.
2. Type a couple of characters
3. Autocomplete does not work, now values are suggested.

**Expected behavior**
You type and get suggestions based on the database values.

**Screenshots**
<img width="575" alt="Screenshot 2022-03-25 at 14 27 40" src="https://user-images.githubusercontent.com/1772890/160129482-643f5afc-3002-40ec-b96e-991de6168136.png">
help explain your problem.

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "de",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_322-heroku-b06",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_322-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.322-b06",
    "os.name": "Linux",
    "os.version": "4.4.0-1101-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.6 (Ubuntu 13.6-1.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.42.3",
      "date": "2022-03-23",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
It does make using Dashboards fairly hard to use. It's impossible to remember all possible values perfectly.

**Comment by paoliniluis** [comment]
Hi @codingjoe, we will need you to post this issue on Discourse as there's not enough information about how the questions were generated, if you're using models or not, etc. I'm going to close this issue in the meantime till we have all the info to generate the issue to be reproduced by our engineers.
