### ISSUE TITLE
Incorrect query when choosing a temporal bucket for time column (type/Time)

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#21269]
**Note**: try this on `master` (or any point after PR #20902 was merged).

First create a table in e.g. PostgreSQL that contains some columns with `time`, e.g.

```
CREATE TABLE test.test (
	"time" time NULL,
	"timestamp" timestamp NULL,
	count integer NULL
);
```

and the populate it with some data:

![image](https://user-images.githubusercontent.com/7288/160225478-8beea2a4-5398-4d07-b492-0df6574f1cc1.png)

and the follow these steps:

1. New, Question
2. Choose the above database and table
3. Summarize, Number of distinct values of `Time` (by hour), group by `Count` (Don't bin)
4. Visualize

### Actual

The query failed, with the full error message:

> ERROR: cannot cast type time without time zone to timestamp without time zone Position: 192

![image](https://user-images.githubusercontent.com/7288/160225443-79a2a1ac-3149-479b-a22f-51611a067983.png)

### Expected

A successful query.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ariya** [comment]
See #20902 for some more context.

The issue seems to be originated from the incorrect treatment of the `time` column, i.e. the generated SQL for the above test case is:

```sql
SELECT "test"."test"."count" AS "count",
  count(distinct date_trunc('hour', CAST("test"."test"."time" AS timestamp))) AS "count_2"
FROM "test"."test"
GROUP BY "test"."test"."count"
ORDER BY "test"."test"."count" ASC
```

in particular:

* the casting, i.e. `CAST("test"."test"."time" AS timestamp))`
* the use of `date_trunc`

**Comment by ariya** [comment]
The likely more proper way to get e.g. the hour is to use `extract`. The following SQL returns the expected answer (`2`):

```sql
SELECT count(distinct extract(HOUR from test.test.time))
FROM test.test
```

Or, as illustrated here:

```sql
SELECT extract(HOUR from test.test.time) as hour
FROM test.test
```

![image](https://user-images.githubusercontent.com/7288/160225756-5e17c441-ecc2-4ad1-8b97-17fc751a3e3b.png)

**Comment by ariya** [comment]
The incorrect casting seems to be gone when I apply the following change:


```diff
diff --git a/src/metabase/driver/postgres.clj b/src/metabase/driver/postgres.clj
index 690f7bbdd0..7c1b1e5206 100644
--- a/src/metabase/driver/postgres.clj
+++ b/src/metabase/driver/postgres.clj
@@ -41,7 +41,7 @@
 (defmethod driver/display-name :postgres [_] "PostgreSQL")
 
 (defn- ->timestamp [honeysql-form]
-  (hx/cast-unless-type-in "timestamp" #{"timestamp" "timestamptz" "date"} honeysql-form))
+  (hx/cast-unless-type-in "timestamp" #{"timestamp" "timestamptz" "date" "time"} honeysql-form))
 
 (defmethod sql.qp/add-interval-honeysql-form :postgres
   [driver hsql-form amount unit]
```

**Comment by flamber** [comment]
Can be reproduced without having to create a table - related to #17598
1. SQL > Postgres: `select current_time::time "time", current_timestamp::timestamp "timestamp", 1 "count"`
2. Save question > Explore results
3. Summarize "Number of distinct values" of Time (or Summarize Count grouped by Time:Hour)
![image](https://user-images.githubusercontent.com/1447303/160231140-c2365889-fd1b-492a-873e-7f555fbe27f3.png)
![image](https://user-images.githubusercontent.com/1447303/160231185-1c0fe7f3-ec53-44dd-b78d-4d45451d690c.png)

**Comment by phuhl** [comment]
Hi, we are facing this issue, too. Is there an ETA for this? Thanks :+1:

**Comment by ranquild** [comment]
I could reproduce in 0.45 (PG only) but in `master` it's fixed.

**Comment by snoe** [comment]
This is not fixed on `master` - it must be reproduced against a postgres db

**Comment by camsaul** [comment]
I don't think any binning is actually involved here

**Comment by camsaul** [comment]
This seems to work with the attempted murders dataset on H2

<img width="829" alt="image" src="https://github.com/metabase/metabase/assets/1455846/9027a8cc-780e-42d8-95b6-4d045c65645d">

**Comment by camsaul** [comment]
Confirmed that this fails on Postgres.

Test to reproduce

```clj
;; metabase.query-processor-test.time-field-test

(deftest ^:parallel temporal-bucket-time-column-test
  (mt/test-drivers (normal-drivers-that-support-time-type)
    (mt/dataset attempted-murders
      (qp.store/with-metadata-provider (mt/id)
        (let [attempts  (lib.metadata/table (qp.store/metadata-provider) (mt/id :attempts))
              time      (lib.metadata/field (qp.store/metadata-provider) (mt/id :attempts :time))
              num-crows (lib.metadata/field (qp.store/metadata-provider) (mt/id :attempts :num_crows))
              query     (-> (lib/query (qp.store/metadata-provider) attempts)
                            (lib/aggregate (lib/distinct (lib/with-temporal-bucket time :hour)))
                            (lib/breakout num-crows))]
          (is (= [[1 3]
                  [2 1]
                  [3 3]
                  [4 2]
                  [5 2]
                  [6 3]
                  [7 3]
                  [8 2]
                  [9 1]]
                 (mt/formatted-rows [long long]
                   (qp/process-query query)))))))))
```
