### ISSUE TITLE
contributing guidelines's Style Guide link broken

### ISSUE THREAD

**Issue by efcjunior** [metabase/metabase#21271]
The Style Guide link into of doc [contributing guidelines](https://github.com/metabase/metabase/blob/64508900a527dd5f04be2ed04483059620ced89f/docs/contributing.md). Its target is the URL https://localhost:3000/_internal

**Comment by flamber** [comment]
@efcjunior Storybook is a better place to see the style guide: `yarn storybook`
_internal is still available on development builds.
