### ISSUE TITLE
Can the database analyze just the visible tables (and tables connected to them)

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2127]
I've a huge schema from witch only 3 tables are visible. When I sync my database to update the metadata it takes too long because it's syncing the hidden tables too. 

The best for performance maybe is to sync the visible tables and the tables connected to them so there is no waste of time.

**Comment by agilliland** [comment]
Just to make sure I am clear, you are talking about tables that you marked as `hidden` inside of Metabase correct?

**Comment by MrMauricioLeite** [comment]
Exact @agilliland. If they are marked as hidden in metabase metadata, we do not need to sync it (unless a visible table references it)

**Comment by etlweather** [comment]
Same issue here, I have several hundred tables and views in the database (Postgres), but the user only has access to 2 views (the user used to connect to the database) but Metabase reads the schema of the entire database constantly. The user used to connect to the database doesn't even have read access on those tables.

**Comment by salsakran** [comment]
To break down the implications a bit:
1. Hidden tables shouldn't be sync'd
2. When a table is unhidden, it should be sync'd
3. New tables still get sync'd and displayed

Pro-
* Lower performance hit

Cons-
* When unhiding a table, there will be a lag between unhiding the table and the information being accurate

Am I missing anything? @agilliland I think this is probably a good idea, despite the con.

**Comment by agilliland** [comment]
Sure.  We can probably have an even better compromise though, which is that we can skip the detailed table analysis when the table is hidden, which certainly makes sense, but we can still do the basic schema introspection work which is designed to be fast and lightweight.

That should give us the best of both worlds.

**Comment by crissyw** [comment]
Is there an update to this issue? We're experiencing the same performance issue (huge schema, lots of hidden tables). When the syncs happen it takes down our entire Metabase portal for our business users during peak hours.

**Comment by LukeAbell** [comment]
Would love this. Updating schemas with the analysis turned on takes forever for us because of all the hidden tables.

**Comment by thearthur** [comment]
Should this also sync on transition from visible to hidden? (my initial thought is no)

**Comment by salsakran** [comment]
@thearthur probably not. the user is saying that they don't want to let people query on that table. No need to spend cycles analyzing it.
