### ISSUE TITLE
Document Google SAML configuration

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21290]
We don't have a Google SAML documentation, which might be useful for Enterprise customers

**Comment by flamber** [comment]
Metabase SAML | Google SAML
-- | --
URL the IdP should redirect back to | ACS    URL (Google Service Provider Details - should be the same as Metabase    defines, which is the Site URL for Metabase with /auth/sso suffixed)
Users email attribute | (what you have defined in Google SAML Attribute Mapping)
Users first name attribute | (what you have defined in Google SAML Attribute Mapping)
Users last name attribute | (what you have defined in Google SAML Attribute Mapping)
SAML Identity Provider URL | SSO URL (available by clicking Download Metadata button)
SAML Identity Provider Certificate | Certificate (available by clicking Download Metadata button)
SAML Application Name | Entity ID (what you have defined in Google Service Provider Details)
SAML Identity Provider Issuer | Entity ID (available by clicking Download Metadata button)

**Comment by jeff-bruemmer** [comment]
[SAML Google configuration docs](https://www.metabase.com/docs/latest/people-and-groups/saml-google).
