### ISSUE TITLE
Graph lines are not visible

### ISSUE THREAD

**Issue by mzeeshanid** [metabase/metabase#2129]
Bug Report:

*  I am using the Safari(Version 9.0.3 (10601.4.4)) and Chrome(Version 48.0.2564.116 (64-bit)) browser.
*  My computer's OS is OS X 10.10.5.
*  My database is MySQL.
*  My Metabase version is v0.15.1.

![screen shot 2016-03-10 at 11 50 43 am](https://cloud.githubusercontent.com/assets/2767152/13661680/992f47f2-e6b6-11e5-93ee-e8c1ce5961f0.png)

**Comment by tlrobinson** [comment]
You need to pick an aggregation, like count or sum (for the Y axis) and a grouping, like "created at" (for the X axis) in the "View" section in order to view a 2D chart.

However we should also do a better job of detecting queries that aren't suitable for graphing.

**Comment by mzeeshanid** [comment]
Got it.
Thanks
