### ISSUE TITLE
how to change field effective_type, admin ui  only change semantic_type  

### ISSUE THREAD

**Issue by szsuyuji** [metabase/metabase#21306]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1931764/160518498-60b0e31e-7108-4ad9-b231-a7b063a04b85.png)
timestamp type has not group options
field metadata in database 
![image](https://user-images.githubusercontent.com/1931764/160518707-205ce1e8-e410-4c1d-a60e-2ab16e535469.png)

another field has the group options after i change the effective_type to "Type/DateTime" in the database
![image](https://user-images.githubusercontent.com/1931764/160518655-0d0cecc5-848b-483c-a42f-2b28a349467a.png)

field metadata in database
![image](https://user-images.githubusercontent.com/1931764/160519025-9dcdf5f7-96af-47bc-9f3e-fdcda3380869.png)

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.18.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "presto",
      "impala",
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.18-txsql-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-03-23",
      "tag": "v0.42.3",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome  87.0.4280.88
- Your operating system: windows10
- Your databases: presto
- Metabase version: v0.42.3
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database:Mysql

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Hi @szsuyuji 
You cannot set `effective_type`, that is handled by Metabase based on the type returned from the database and how it's being cast, and how the driver parses the column.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by szsuyuji** [comment]
> Hi @szsuyuji You cannot set `effective_type`, that is handled by Metabase based on the type returned from the database and how it's being cast, and how the driver parses the column. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

  why  `database_type` is timestamp(3)  but  `effective_type`  is type/*

**Comment by szsuyuji** [comment]
![image](https://user-images.githubusercontent.com/1931764/167347479-24eaa571-ab08-44f2-bfc8-3eb0ba162c27.png)

**Comment by flamber** [comment]
@szsuyuji Because it's up to the driver to correlate types.

**Comment by szsuyuji** [comment]
@flamber after i replace the presto.metabase.driver.jar module with old version ,it works well. effective_type now becomes the 
 'type/DateTime' type

**Comment by flamber** [comment]
@szsuyuji 
You were already using the old Presto driver.
Which version of Presto database do you have?
And which "old version" are you replacing it with?

**Comment by szsuyuji** [comment]
replace with 
![image](https://user-images.githubusercontent.com/1931764/167808850-0eb1f324-6902-4885-af0d-0dc3a0a0028e.png)

my presto engine is  the last version 350 named prestosql of trino ,not the facebook version
![image](https://user-images.githubusercontent.com/1931764/167810727-ff846c6c-ccfe-43fe-8d8b-3ed9de6acaa4.png)
