### ISSUE TITLE
New question tab opening from a Dashboard start loading after dashboard's collection information finish or stop loading

### ISSUE THREAD

**Issue by chompimcha** [metabase/metabase#21315]
**Describe the bug**
When we openned a question in **a new tab** from the dashboard that  many components/ contents inside was still loading, the new tab question didn't start loading until the dashboard collection's information finish loading or if we just stop the dashboard loading by refreshing, then the new question tab start loading.
In this case, we know that the dashboard contained many questions and it caused the collection's information step slow started as this past case >> https://github.com/metabase/metabase/issues/16836.

**Logs**
> {
   "browser-info":{
      "language":"en-US",
      "platform":"Win32",
      "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36",
      "vendor":"Google Inc."
   },
   "system-info":{
      "file.encoding":"UTF-8",
      "java.runtime.name":"OpenJDK Runtime Environment",
      "java.runtime.version":"1.8.0_252-b09",
      "java.vendor":"Oracle Corporation",
      "java.vendor.url":"http://java.oracle.com/",
      "java.version":"1.8.0_252",
      "java.vm.name":"OpenJDK 64-Bit Server VM",
      "java.vm.version":"25.252-b09",
      "os.name":"Linux",
      "os.version":"3.10.0-1127.el7.x86_64",
      "user.language":"en",
      "user.timezone":"Asia/Bangkok"
   },
   "metabase-info":{
      "databases":[
         "postgres",
         "sqlserver",
         "impala",
         "vertica"
      ],
      "hosting-env":"unknown",
      "application-database":"postgres",
      "application-database-details":{
         "database":{
            "name":"PostgreSQL",
            "version":"13.5"
         },
         "jdbc-driver":{
            "name":"PostgreSQL JDBC Driver",
            "version":"42.2.23"
         }
      },
      "run-mode":"prod",
      "version":{
         "tag":"vUNKNOWN",
         "date":"2022-03-21",
         "branch":"main",
         "hash":"c926b01"
      },
      "settings":{
         "report-timezone":"Asia/Bangkok"
      }
   }
}

**To Reproduce**
1. Open the dashboard that has many questions with network console so we can see the running transaction.
2. Open question in the dashboard in new tab (e.g. window, we press window and click at question name)
3. New question tab start loading after the dashboard collection's information finish/stop loading
(This step happen to every dashboard, but the effect can be obvious when there's many question/components in the dashboard to be loaded.)

**Expected behavior**
New question tab start loading question content without waiting for dashboard collection's information loading in the previous dashboard tab.

**Screenshots**
New question tab opening from dashboard started loading after the dashboard collection's information in yellow box finished loading  or stooped loading by refreshing the dashboard page  or going to other page
![image](https://user-images.githubusercontent.com/47517178/160604166-c807aeda-67e8-4bde-9ef6-65ee94266223.png)

**Information about your Metabase Installation:**
Metabase 0.41.v
Happen to any browser

**Severity**
We did asked user to reduce number of question from the dashboard and give user some workarounds that we found.
For example, view question by not opening new tab, or refresh the dashboard tab if user opens new question tab from the dashboard.
, but we still would like to see of new question tab can ignore the previous dashboard's collection loading. Not sure if it need to be related.

**Additional context**

**Comment by flamber** [comment]
Hi @chompimcha 
You are using some custom build. Try with an official release: https://github.com/metabase/metabase/releases/latest
And upgrade to Java 11: https://www.metabase.com/docs/latest/operations-guide/java-versions.html
And read this article on scaling: https://www.metabase.com/learn/administration/metabase-at-scale.html

**Comment by chompimcha** [comment]
@flamber  I understand the information that you replied. Thank you for your fast respone anf or the information. 
For scaling, we've applied it to our Metabase and user and we will continue scaling following the document you provided.
For upgrading to the official relase, Is this mean to upgrade to the latest version? 0.41.4 version is called as the custom build in your menaing, right? 

May I ask a few more question?
- Just would like to understand the reason why when we open question in the dashboard via new tab, it need to wait for the dashboard's collection information from the primary dashboard tab to finish downloading?
- The dashboard collection's information API is called to just show the collection name under dashboard name or it's for other purposes too?
- Is it possible that when we open the question via new tab from the dashboard, it should not wait for any loading from previous page?

**Comment by flamber** [comment]
@chompimcha 
I have no idea which version you're on, but you are custom build:
```
"tag":"vUNKNOWN",
"date":"2022-03-21",
"branch":"main",
"hash":"c926b01"
```
And yes, always try with the latest official release.

Different tabs cannot block each others requests, since browsers don't allow that, but if you are using http instead of https, then you'll hit the max requests per host, which is around 6. Read the scaling guide.

**Comment by chompimcha** [comment]
@flamber  We are on 0.41.4, but we have some little development per our use, but not relate to the main feature. 
This may cause our logs show like that. Also, we always use https for our Metabase in our company.
We will considering upgrade our Metabase to the latest version as soon as possible per your suggestion.

But, for only the case that the main tab's request  block the new tab's request, _I think upgrade version will not fix this because it's seem to be some logics that happen to every dashboard, but it's obvious when we process from the dashboard have many questions and the dashboard collection's inofrmation can slow start._ I have informed our user to reduce the number of the question from the dashboard already.

And, as you mentioned that it should not happen, I agree with that. Currently, we detected it and we can reproduce that, so we reported. if it should not happen, this mean the case, "new tab question opening from the dashboard Ashould not wait for the dashboard A collection's information loading" it need to be fixed.

**Comment by chompimcha** [comment]
@flamber More information, we have just tested this case on 0.42.3 on our testing environment. The case seem not to be fixed as expectation.

**Comment by flamber** [comment]
@chompimcha Okay, I cannot reproduce.
It is not possible to requests from other tabs to show in the Network tab.
Either I'm completely misunderstanding your problem or it's something in your setup/browser.
But provide logs from Admin > Troubleshooting > Logs.

**Comment by chompimcha** [comment]
@flamber I have discuss with in my internal team. This case can happen but it will be rarely and it's worth/better to force our user to follow scaling best practice. Thank you for you help.
