### ISSUE TITLE
Don't show sort/filter affordances for SQL Questions

### ISSUE THREAD

**Issue by kurtosis** [metabase/metabase#2131]
When I generate a table from a raw SQL query I can't sort or filter by a field.  However the UI still shows the sort and filter icons on hover/click which makes this a bit confusing.

**Comment by tlrobinson** [comment]
We aren't able to easily modify a SQL query to affect the sort order in the query, but we could do client-side sorting. However, this would be inconsistent with query builder queries, so I don't think that's a good idea. Probably best to just hide the sort indicators.

@camsaul I wouldn't consider this a data correctness issue. The UI suggests clicking a column header would sort the data but if you click it nothing happens.

**Comment by salsakran** [comment]
+1 on hiding the sort indicators for SQL questions

**Comment by mazameli** [comment]
> we could do client-side sorting. However, this would be inconsistent with query builder queries, so I don't think that's a good idea.

The main concern is that this would bifurcate the way that the FE handles sorting? Just to speak up for the other side, we'd be trading code consistency for UX consistency ("why can I sort table A but not table B?").

**Comment by MaxSavenkov** [comment]
Couldn't variables be used to implement this to everyone's satisfaction? I.e. if SQL question includes "ORDER BY {{ordering}}" then allow sorting by columns. This, of course, would only work for the outer-most clause, but this is what most users would want, isn't it?

**Comment by amywtlin** [comment]
Hey there, 

I'm currently out of office with limited access to email. I will be back on Jun 5. If your inquiry can wait a little, great - I'll get back to you as soon as possible after I get back! 


If it's urgent and related to a live class or a video course, please forward the email to my colleague Kara: kara@codementor.io; she will be able to help you with it. 


if it's not related to a live class or a video course but still urgent, please forward it to our wonderful support team: support@codementor.io


Thanks, and talk to you later!
Amy

**Comment by flamber** [comment]
There's a request open for client-side sorting #11329 - upvote by clicking :+1: on the first post.
On 0.33.5.1 there are no sort/filter icons shown, so I guess this issue can be closed:
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/68976145-bfb76480-07ba-11ea-86cb-679883da50c8.png)
