### ISSUE TITLE
Receiving email subscriptions for archived dashboards

### ISSUE THREAD

**Issue by andrewler** [metabase/metabase#21339]
**Describe the bug**
Randomly started to receive email subscriptions for archived dashboards after some period of time of not receiving the email subscriptions.

**Logs**

**To Reproduce**
1. Create some dashboards with active email subscriptions
2. Archive the dashboards
3. The email subscriptions stopped for around a month
4. After a month the "ghost" subscriptions started to be sent again.

**Expected behavior**
Once the dashboard is archived the email subscriptions should stop unless the dashboard is restored.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14+9",
    "os.name": "Linux",
    "os.version": "5.11.0-41-generic",
    "user.language": "en",
    "user.timezone": "Asia/Seoul"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.35"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-08",
      "tag": "v0.42.0",
      "branch": "release-x.42.x",
      "hash": "de1264e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
This is low severity but really unexpected an annoying.

**Additional context**
It is very strange that the dashboard subscriptions of the archived dashboard did indeed stop being sent out for around a month and then the "zombie" subscriptions of the archived dashboards started to be sent again.  There is no identifiable logic to the behavior.

**Comment by flamber** [comment]
Hi @andrewler 
This should not have been possible anymore since 0.41.2, when Subscriptions would not be sent for archived dashboards #17487
We cannot wait around for a month to test something that seems to happen randomly, so you will need to provide data from the `pulse*` tables in the application database, so it is possible to understand how this can occur.
