### ISSUE TITLE
table values not showing in dashboard

### ISSUE THREAD

**Issue by kurtosis-color** [metabase/metabase#2133]
I'm creating a table  by selecting "Count of rows by [a boolean column]". In the Question view this shows counts for true and false but when I add to a dashboard the "true" and "false" labels do not display. Verified that this occurs for multiple tables.

*  I am using the Chrome browser.
*  My computer's OS is Mac OS X.
*  My database is PostgreSQL.
*  My Metabase version is v0.14.1.

**Comment by camsaul** [comment]
Hi @kurtosis-color, a lot of changes and improvements have been made to dashboards in `v0.15.0` and `v0.15.1`. Any chance you can upgrade to the latest version of Metabase and see if you're still seeing the bug?

**Comment by kurtosis-color** [comment]
yep, fixed!
