### ISSUE TITLE
Expose ability to sort by multiple columns

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2134]
Right now you can only sort by a single column at a time.

[MBQL / the QP supports multiple columns in the `order_by` clause](https://github.com/metabase/metabase/wiki/Query-Language-'98#order-by). An example use case would be sorting a list of customers, first by last name, then by first name.

**Comment by camsaul** [comment]
The code looks like it's already set up to handle multiple clauses in `order_by` as well, this might be as simple as keeping the `+ Add sort` button visible after the first clause has been added

**Comment by joevandyk** [comment]
This would be very awesome to have.

**Comment by flamber** [comment]
Hi @camsaul 
Isn't this already implemented in the Additional Options? Or is this a request for adding another menu option, when clicking the column? Not sure when it was added to Additional Options, but this is 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/53275452-c946ec80-36c0-11e9-9c91-9338e6feffa1.png)

**Comment by mazameli** [comment]
Yep, this is exposed in the UI. It's not very discoverable right now, but we're working on a number of UI/IX improvements to query builder elements like this one.
