### ISSUE TITLE
Add filtering options to Archive page

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21341]
**Is your feature request related to a problem? Please describe.**
This is partially a bug, but don't see a way of fixing the bug without adding functionality.

Currently `/archive` uses the `/api/search?archived=true` to list objects on the page, but several problems with that:
- it is limited to 1000 results, which makes it impossible/difficult to unarchive objects if they are not available in those results
- extremely difficult to find objects because of lack of filtering/search options

**Describe the solution you'd like**
1. Filtering options for types similar to Search
2. Show archived timestamp, and possibility to order by that column
3. Option to search by name or id.

An alternative would be to make Search able to deal with archived objects and only have that page. That would also be a very welcomed feature to be able to do a normal search and checkbox multiple results to move/archive/duplicate.

**Describe alternatives you've considered**
Use the API's hidden search feature `GET /api/search?archived=true&q=search%20string` to find what I'm looking for, then send `PUT /api/card/123` with `{"archived":false}` body to unarchive for example a question.

**How important is this feature to you?**
If you have a larger instance, or have been using Metabase for several years, then the Archive page is insufficient.

**Additional context**
While addressing this, it would likely be possible to address #4013 and #9555 and #16499 too.

**Comment by camsaul** [comment]
@flamber to clarify are you asking for a new endpoint as well here? Or is this just for some frontend changes to use existing search endpoint features

@bshepherdson I would hold off on starting on this one until we can clarify a bit more what it is we want to do here. You'll probably need to coordinate with someone to do the FE stuff as part of this as well

**Comment by likeshumidity** [comment]
Workaround: users must make an API call to list questions and to unarchive. This approach is not user friendly. Affects larger installs with more than 1000 archived objects.

**Comment by jangelcompara** [comment]
Can we show the last 1000 archive items? I think that is an easy workaround to make this feature usable while the full functionalities arrive

**Comment by paoliniluis** [comment]
@jangelcompara we're working on this as we speak

**Comment by luizarakaki** [comment]
It is now possible to search trashed items in normal search (there is a filter in the full-page search feature).
We also handle this as a normal collection now. So all items are displayed.

**Comment by sarahmccuan** [comment]
@luizarakaki Exciting news! thank you for this fix. Any idea when it'll make it to a cloud release?

**Comment by luizarakaki** [comment]
We are releasing the v50 preview today. It usually takes ~4 weeks from preview to Cloud deployment. But these vary quite a bit.

**Comment by sarahmccuan** [comment]
Hey @luizarakaki did this functionality get cut from the cloud deployment? We recently updated to v50 (specifically 1.50.23) but the archive / search functionality don't seem to have changed.

**Comment by luizarakaki** [comment]
We had to postpone the release of the new Archive to 51. It will be released soon.
