### ISSUE TITLE
Dashboard's "text/contains" filter is case-sensitive

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#21359]
**Describe the bug**

Trying to filter dashboard's card results using "text/contains" filter can be confusing since it's case-sensitive.

**To Reproduce**

1. Save sample database's People table as a GUI question
2. Add the question to a dashboard
3. Create a "text/contains" dashboard filter and connected it to "People — Name"
4. Save changes
5. Try to search for "Hudson" and for "hudson"
6. "Hudson" has results and querying "hudson" has no results

**Expected behavior**

"text/contains" should be case insensitive or there should be a way to manage to control the behavior.

**Demo**

https://user-images.githubusercontent.com/17258145/160895870-ccef4da0-4b39-4061-bb55-a917980dbe3e.mp4

**Comment by losrebellos** [comment]
It seems to be a backend issue as the search text is passed to the API as expected:

- `hudson` filtering has no results

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/348552/163585231-1aa458ff-35c6-45d1-9616-cdedc48e2b97.png">

- `Hudson` filtering has results

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/348552/163585334-74dcf217-9db9-4983-bc28-e3b9519248c6.png">
