### ISSUE TITLE
Can't connect a MongoDB replica set with SSL

### ISSUE THREAD

**Issue by OpsDev8** [metabase/metabase#21350]
**Describe the bug**
We're having trouble connecting our MongoDB replica sets with ssl certificates to our Metabase instance.

**Logs**
Unfortunately we can't upload our logs because we are running the application on a separate network. We copied the relevant logs from our efforts when using separate fields with one host our of 3 from the replica set:

ERROR driver.util :: Database connection error
com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@296b280d. Client view of cluster state is {type=REPLICA_SET, servers=[{address=replicaSetAddress1:port, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed}, caused by {sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed}, caused by {java.security.cert.CertPathValidator0Exception: signature check failed}, caused by {java.security.SignatureException: Signature does not match.}}]
at ...
ERROR api.database  :: Cannot connect to database
java.land.Exception: Hmm, we couldn't connect to the database. Make sure your host and port settings are correct

When trying to use a connection string, we keep getting warnings about unsupported flags relating to ssl, and this results in getting a timeout error.

**To Reproduce**
1. Run a new Metabase instance as a docker image
2. Go to admin area and choose "Add a new database"
3. Try to connect a MongoDB Replica Set that uses ssl certificates using separate values and entering one host / several hosts
4. Try to connect to the same database using a connection string and entering all hosts and ssl flags

**Expected behavior**
The database will connect to the application.

**Screenshots**
We are unable to provide screenshots. The UI presents the final error of the log.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
- Your browser and the version: Chrome 90.0.4430.212
- Your operating system: Linux 4.18.0-193.56.1.el8_2.x86_64
- Your databases: Postgres, MongoDB
- Metabase version: 0.40.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
This issue is blocking us from connecting our MongoDB databases and monitoring them. This is an integral part of our work and is needed for our team.

**Additional context**
According to the Metabase documentation, you can't use the connection string option and use ssl certificates at the same time. But from what we've seen, you need to use the connection string option in order to connect to a replica set, since you can't list more than one host when using the normal separate fields option.

We tried to connect a keystore with the certificates but it seemed like it still didn't work.

We still tried many times using both the separate fields method and the connection string method. Tried using one host or all hosts of the replica set. Tried several flags to enter the ssl certificate route.

We'd like to know if there's something we're missing. Thank you very much!

**Comment by flamber** [comment]
Hi @OpsDev8 
You should upgrade immediately to a newer release: https://github.com/metabase/metabase/releases/latest
And provide full logs, since I don't know which errors you are seeing with "we keep getting warnings about unsupported flags relating to ssl".

**Comment by OpsDev8** [comment]
I've upgraded my Metabase instance to the latest version (0.42.3) and I still can't get it to work. Now I seem to get a regular timeout error, no more information in the logs.

The warning I talked about is this:
WARN driver.api :: Connection string contains unsupported option 'sslrootcert'.

This is happening for every ssl flag I'm trying to insert in the additional connection string options. Just replace "sslrootcert" with the options I've tried: sslroot, sslkey, sslmode, sslpemkeyfile...

I'm entering these options:
host: <one host of replica set / several hosts seperated with a comma>
database name: <mongoDB database name>
port: <default port>
username: <database username> (we're using x509 for authentication so not sure if this is necesarry)
password: <either a placeholder or $external since there is no password but the field is required>
authentication database: <$external / admin>
server SSL certificate chain: <our SSL certificate chain>
additional connection string options:
authSource=$external&replicaSet=<replicasetname>&ssl=true&authMechanism=MONGODB-X509&readPreference=<secondary/primary/nearest>&sslrootcert=</path/to/pemfile.pem>

I've attached the updated logs we get with these options here
![metabase mongo log 1](https://user-images.githubusercontent.com/102604814/161430710-6984b00d-3429-4f59-a79b-f65bcf74db05.jpg)
![metabase mongo log 2](https://user-images.githubusercontent.com/102604814/161430712-b99d2416-b6bb-4ffa-aa9e-a8560fba9927.jpg)
![metabase mongo log 3](https://user-images.githubusercontent.com/102604814/161430716-9b68dc92-021e-4a9d-8efd-152f049e4e8b.jpg)
![metabase mongo log 4](https://user-images.githubusercontent.com/102604814/161430719-ba0d7c36-b150-47b6-8364-6eaeae2f0bb6.jpg)
.

**Comment by paoliniluis** [comment]
@OpsDev8 the error seems like a timeout more than an authentication error, this points me to a firewall issue rather than a certificate issue. Can you take a look at the firewall rules?

**Comment by flamber** [comment]
@OpsDev8 Try posting the full logs instead of screenshots.
These are the valid connection string options for Mongo: https://www.mongodb.com/docs/manual/reference/connection-string/

**Comment by flamber** [comment]
@OpsDev8 Guess you are looking for this: #14108 - upvote by clicking :+1: on the first post
