### ISSUE TITLE
Sometimes when there is a query error on a dashboard card the card title doesn't display

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2135]
*  I am using the Chrome browser.
*  My computer's OS is Mac.
*  My database is postgres.
*  My Metabase version is v0.15.0.

![screen shot 2016-03-10 at 2 37 14 pm](https://cloud.githubusercontent.com/assets/1987787/13687873/e6921058-e6d2-11e5-9a73-8307f2c4d743.png)

With the card title missing there is no easy way to link directly to the card and fix it.

**Comment by tlrobinson** [comment]
Duplicate of #2036?

**Comment by agilliland** [comment]
indeed!
