### ISSUE TITLE
Support column & table names with slashes in them

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2137]
This came up while working on calculated columns:

The SQL generated looks like this;

``` sql
SELECT ("PUBLIC"."ORDERS"."TOTAL" - "PUBLIC"."ORDERS"."TAX") AS "TOTAL - TAX",
       ("PUBLIC"."ORDERS"."TAX" / "PUBLIC"."ORDERS"."TOTAL") AS "TAX / TOTAL"
FROM "PUBLIC"."ORDERS"
LIMIT 2000
```

What ends up happening is we're converting column names to keywords, and since it has a slash in it it effectively becomes a namespace-qualified keyword; calling `name` on a keyword only returns the last part.

``` clojure
(name :bird/toucan) -> "toucan"
(name (keyword "TAX / TOTAL")) -> " TOTAL"
```

The result is slightly annoying:

![screen shot 2016-03-10 at 4 20 06 pm](https://cloud.githubusercontent.com/assets/1455846/13689199/1c4d1dd8-e6dc-11e5-8955-334de1aef8c2.png)

Hopefully too many people don't have slashes in their column names IRL, but if they did this issue would affect them whether they "calculated" that column or not.
###### Tables with Slashes in Their Names

As noted in #2295 tables with slashes in the name have been spotted in the wild, and effectively prevent correct queries from being generated.

**Comment by agilliland** [comment]
This is similar to #1786 in the sense that the mapping of db column names to dictionary key names is causing an issue.

**Comment by camsaul** [comment]
This isn't really an issue with using column names as dictionary keys, but one with how we're serializing keywords.

**Comment by eladeyal-intel** [comment]
@camsaul is there a workaround for this? I have slashes in MySQL View Coloumn Names. thanks
