### ISSUE TITLE
Clicking "New Question" blocks while re-running previous query before resetting QB

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2138]
To repro:
1.  Click `New Question`
2.  Create a query
3.  Run it. Screen switches to `Doing Science...`
4.  See results. Nice! :+1: 
5.  Click `New Question` again
6.  Can't do anything, we're `Doing Science...` again. Query runs a second time.
7.  Results of old query are displayed for a fraction of a second
8.  QB resets to an empty state

This adds a second or more of unresponsiveness between when I click `New Question` and when I can start working on it. This would be especially bad if the original query was long-running, e.g. 15 seconds or more.

If this is a bug report, please fill in the blanks:
-  I am using the Chrome browser.
-  My computer's OS is OS X.
-  My database is all.
-  My Metabase version is 16.0-SNAPSHOT (?)

**Comment by salsakran** [comment]
this was fixed in 20 or 21 as it no longer occurs for me.
