### ISSUE TITLE
Some strings not being translated in setup page

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21404]
**Describe the bug**
Setup page has many strings without translation like "First name", "Last name", "Email", "Company or team name", "Create a password", "Confirm your password"

**Logs**
None

**To Reproduce**
Change language to another one on setup and see the strings without translation

**Expected behavior**
Have the strings translated to its language

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/161166860-07f66866-0727-45ce-8b37-e2bf3ac8528d.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04
- Your databases: H2
- Metabase version: 42.3
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic?

**Additional context**
NA

**Comment by ranquild** [comment]
@paoliniluis @mazameli while the root cause on the frontend is fixed, some i18n strings are missing and should be translated.
