### ISSUE TITLE
Empty row causes pie chart to be incorrect.

### ISSUE THREAD

**Issue by elliotthill** [metabase/metabase#2141]
I am using the mac standalone app.
My computer's OS is OSX El Capitan.
My database is Mysql 5.6.1.
My Metabase version is 0.15.1.1.

![screen shot 2016-03-11 at 13 00 59](https://cloud.githubusercontent.com/assets/6547849/13702840/5c1d4fc0-e789-11e5-9cd2-710590097a11.png)
![screen shot 2016-03-11 at 13 01 10](https://cloud.githubusercontent.com/assets/6547849/13702841/5dec0d3c-e789-11e5-9d26-fd81c84ac2ff.png)

**Comment by agilliland** [comment]
Confirmed.  You can reproduce this by using this query and setting the visualization to `pie`

```select *
from (values (null, 1234), ('abc', 1234)) a```

**Comment by tlrobinson** [comment]
This will be resolved by #2136
![screenshot 2016-03-11 10 37 07](https://cloud.githubusercontent.com/assets/18193/13711789/48ede93c-e775-11e5-81df-21803463e33d.png)
