### ISSUE TITLE
How To debug Frontend in Visual Code [Break point]

### ISSUE THREAD

**Issue by mmiftahululum** [metabase/metabase#21443]
i try to debug frontend in visual code, but the break point not active, after i played to debug with chrome.

![image](https://user-images.githubusercontent.com/20709636/161518887-358463af-46c5-4bef-846d-e90019e549bb.png)

please, help me !

**Comment by flamber** [comment]
https://docs.microsoft.com/en-us/visualstudio/javascript/debug-nodejs?view=vs-2022
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
