### ISSUE TITLE
`partial=` should error on only one argument

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#21454]
```clojure
timeline-test=> (is (partial= {:a "bob"} {:b :extra :a "bo"}))

FAIL in () (NO_SOURCE_FILE:161)
expected: {:a "bob"}
  actual: {:b :extra, :a "bo"}
    diff: - {:a "bob"}
          + {:a "bo"}
nil
timeline-test=> (is (partial= {:a "bob"}))
nil
timeline-test=> 
```

It is great one two arguments. But when given one argument it silently accepts. `=` in Clojure allows for this but we have no need to support the weirder arities of `=`. this should just throw/error whatever.

**Comment by camsaul** [comment]
@bshepherdson the part of the code you need to edit is https://github.com/metabase/metabase/blob/master/test/metabase/test_runner/assert_exprs.clj#L120-L124

Currently it looks like the code actually accepts any number of args but I think @dpsutton might be right here that we should rework it to accept two and only two args. I can go either way on this. The important thing is that it doesn't allow one (or zero) args
