### ISSUE TITLE
POST firing on each keystroke when changing series display name on cumulative calculations

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21452]
**Describe the bug**
Change a series label name using cumulative calculations, will make POST request for each keystroke that leads to the UI not being responsive enough to capture all the changes (and in the meantime you'll be hammering the API, of course)

**Logs**
NA

**To Reproduce**
1) new->question-> select orders as your starting data
2) Do a cumulative sum of quantity per created_at (month) - you can achieve the same with cumulative count of rows
![image](https://user-images.githubusercontent.com/1711649/161607528-4f853027-bde5-4695-8d27-afeaa4130702.png)
3) go to chart settings and change the text on the series name to "let's change this", 
4) see yourself hammering the /api/dataset endpoint
![image](https://user-images.githubusercontent.com/1711649/161607747-0d5bc3ce-6050-4e82-a1ee-a7136a45b62a.png)

**Expected behavior**
This should behave in the same way we behave with other calculations (only happens with cumulative count of rows and cumulative sum)

**Screenshots**
Above

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: H2
- Metabase version: 42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2'ish

**Additional context**
Seems like a regression from 40
Also: why do we do a GET request on each keystroke to the favicon? is that React doing its thing?

**Comment by flamber** [comment]
Not a regression, tested back to 0.37.8.
Related to #19683, which might or might not contain cumulative metrics, but generally updating some settings are slow to render.
