### ISSUE TITLE
Duplicating a pinned question also pins the duplicate

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#21483]
**Describe the bug**
If a question that is pinned in a collection is duplicated using the "Duplicate this question" button in the question editor, the new copy is also pinned in the collection.

This may be by design and not specifically a bug, but it doesn't **feel** like the intended behaviour.

**Logs**
Nothing relevant.

**To Reproduce**
1. In any collection pin a question
2. Open that question
3. Use the "Duplicate this question" button and save in the same collection (that's  the default location)
4. Go back to the collection and note that the duplicate is also pinned and rendered

**Expected behavior**
The duplicate not to be pinned. Given the new UI for pins, pinning a question now has more impact on performance so it should be more carefully considered. Pinning is now a heavy operation that shouldn't be applied by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/4504437/161893780-7401ca22-115d-45df-b10c-9d9ea23cb41b.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-03-23",
      "tag": "v0.42.3",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": "NZ"
    }
  }
}
```

**Severity**
Minimal impact. It feels inconsistent but is simple to unpin so not a big deal. I tend not to pin items with the new UI anyway. 

**Additional context**
It will also pin the question if you choose to save the duplicate into a different collection.

Edit: duplicating dashboards behaves as I would expect, the new duplicate is not automatically pinned.

**Comment by camsaul** [comment]
@bshepherdson 

I believe the API endpoint that gets used is this one

https://github.com/metabase/metabase/blob/master/src/metabase/api/card.clj#L312-L320

I think the column that is responsible for a Saved Question (aka Card) being pinned is `report_card.collection_position` -- don't quote me on that tho. You can create a Saved Question and look at it in `psql` or whatever and then pin it and confirm that's what changed. If that's the case then all you probably need to do here is `(dissoc ... :collection_position)` so it's not copied over to the new Card and then write a test for it.

When you get the first part done and confirm it's working by testing it manually in the browser ping me and I can help you write a test for it

**Comment by bshepherdson** [comment]
Hm, that's actually not the API in use. The FE is doing a direct `POST /api/card` with `collection_position` set:

<img width="919" alt="Screen Shot 2022-04-18 at 18 49 52" src="https://user-images.githubusercontent.com/157812/163889618-16e2c107-38ce-48d7-bf16-2070d7132e36.png">

**Comment by bshepherdson** [comment]
Reassigning to frontend.

The `collection_position` field is the right one; it should be dropped when duplicating.
(Also maybe `archived`?)
