### ISSUE TITLE
when reboots metabase, it cleans up configuration in postgres

### ISSUE THREAD

**Issue by triyes** [metabase/metabase#21507]
**Describe the bug**
when reboots metabase, it cleans up configuration in postgres

**Logs**
Looks like this is a new installation ... preparing setup wizard

**To Reproduce**
1. configue metabase in postgres
2. reboot metabase
3. open metabase in web brawser, shows setup site
4. metabase logs show Looks like this is a new installation ... preparing setup wizard

**Expected behavior**
use the configuration in postgres, not setup again

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 100.0.4896.75
- Your operating system: Ubuntu 16.04
- Your databases: Postgres 12.6
- Metabase version: 0.41.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Comment by flamber** [comment]
Make sure you have configured your container to use the application database:
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html#production-installation
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
