### ISSUE TITLE
Pie chart series are not displayed correctly in the config (using timestamp instead of short date)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21504]
**Describe the bug**
When building a pie chart with a timestamp as series, the series will be displayed in the chart config with a different format than the one that is being used in the chart itself. E.g. "August, 2017" is shown in the chart, but the series in the chart config will be "2017-08-01T00:00:00Z"

**Logs**
No logs

**To Reproduce**
1) Build a pie chart with the following: Orders-> sum of quantity per Created_at (month)
2) go to the settings of the chart -> Display tab
3) see the dates being rendered as "YYYY-MM-DD with timezone"

**Expected behavior**
Show the exact same series name as you see in the chart, so "August, 2017" in the chart should be "August, 2017" in the series name

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/162103647-18bc5666-a3d9-4a99-aa9b-0accdbabb48f.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
Cosmetic

**Additional context**
NA

**Comment by nemanjaglumac** [comment]
Please don't forget to add `.Reproduced` label when you add a repro for an issue.
