### ISSUE TITLE
Cumulative operations are not named correctly in the series config

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21502]
**Describe the bug**
When using a cumulative operation (Cumulative count of rows or cumulative sum of ...), the display name of the series is not built correctly, so for "Cumulative count of rows" we show "Count" and for "Cumulative sum of..." we show "Sum of ..." which confuses the users on multi-series charts.

**Logs**
There are no logs here

**To Reproduce**
1) Build a question with a cumulative operation like Orders -> Cumulative count of rows per created_at
2) Go to the settings of the chart and check the Display tab. You will see just "Count"

**Expected behavior**
Name the series as it should be: Cumulative count or Cumulative sum

**Screenshots**
This is for Cumulative count of rows
![image](https://user-images.githubusercontent.com/1711649/162098605-06bfe1b0-6684-4471-98c3-16a194ca576b.png)

This is for Cumulative sum
![image](https://user-images.githubusercontent.com/1711649/162098673-acc65007-5f43-42b8-acbf-363fc305ecd0.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
It's cosmetic but it can lead to confusion

**Additional context**
NA

**Comment by iethree** [comment]
Looks like column titles for cumulative sum operations are generated on the backend.
![Screen Shot 2023-08-14 at 10 36 38 AM](https://github.com/metabase/metabase/assets/30528226/265e0237-02b7-4b4b-9c2e-4f9e93a9164d)

![Screen Shot 2023-08-14 at 10 30 07 AM](https://github.com/metabase/metabase/assets/30528226/f7df769d-aec3-4768-91ac-f835402b273f)
