### ISSUE TITLE
Custom Expression validator too strict when field name is the same as a function

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21513]
**Describe the bug**
Custom Expression validator does not allow field names that are the same as functions e.g `[Count] * 2`
Regression since 0.42

Workaround: For metrics, create a Custom Expression with a custom name (e.g. MyCount). For fields, change the name in the Data Model.

**To Reproduce**
1. Question > Sample > Products
2. Summarize Count grouped by Category
3. Custom Column `[Count] * 2` as "CC" - errors with `Expecting number but found function Count returning aggregation`
![image](https://user-images.githubusercontent.com/1447303/162183951-6f86c742-7d8f-4bfe-8a6a-6f9710989915.png)

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.3/4 and master

**Comment by camsaul** [comment]
Ran into the same thing today on `master`, but my column name is `count`

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/1455846/163092461-ed8c4e89-83eb-4c80-be55-7058e9769b14.png">
