### ISSUE TITLE
Data selector not working in FullApp embedding if going directly from location that hasn't loaded `/api/database` yet

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21511]
**Describe the bug**
If FullApp embedding directly to e.g `/collection/root`, then it is not possible to click the :heavy_plus_sign: (New...) menu to start a question, because there hasn't been any calls to `/api/database` yet.

**Possible workaround:**
Create a button outside the iframe, similar to pre-42, which changes the URL to `/question/new` or `/question/notebook#eyJjcmVhdGlvblR5cGUiOiJjdXN0b21fcXVlc3Rpb24iLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjpudWxsLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOm51bGx9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319`
Or use the homepage as starting point, which loads the databases.

**Reproduce 1**
1. Setup an instance. Might need to adjust allowed embed URLs or just `*`
2. Create a page that has an iframe like (some path that doesn't load the `/api/database` endpoint, which the homepage does by default)
`<iframe src="https://metabase.example.com/collection/root">`
3. Click :heavy_plus_sign: (New...) > Question
![image](https://user-images.githubusercontent.com/1447303/162176810-68cf7e96-04b6-46a0-a6fd-72f6bf8d9085.png)
4. Data selector just shows: `To pick some data, you'll need to add some first`
![image](https://user-images.githubusercontent.com/1447303/162176929-459823b0-8d05-43f2-b724-558172ebe562.png)

**Reproduce 2**
1. Setup an instance. Might need to adjust allowed embed URLs or just `*`
2. Create a page that has an iframe like (some path that doesn't load the `/api/database` endpoint, which the homepage does by default)
`<iframe src="https://metabase.example.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgMSIsInRlbXBsYXRlLXRhZ3MiOnt9fSwiZGF0YWJhc2UiOjF9LCJkaXNwbGF5Ijoic2NhbGFyIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319">`
3. It will not show the database selector
![image](https://user-images.githubusercontent.com/1447303/195065874-af79d1f6-c4e0-4926-9fb3-8dc7b8ab08be.png)
4. Clicking the Reference (Learn about your data) opens the sidebar and makes a request to `/api/database`, which then updates everything correctly
![image](https://user-images.githubusercontent.com/1447303/195066157-a5f423b0-ce7e-4555-8fff-5c6160080f0b.png)

**Reproduce X**
There's likely multiple other ways of reproducing this problem, not going through all of them.

**Information about your Metabase Installation:**
Tested 1.42.3

**Additional context**
Historically related to #18552 and #21055, and likely also related to #10927

**Comment by kulyk** [comment]
@flamber I guess we got that fixed when adding the new nav:

https://user-images.githubusercontent.com/17258145/165733390-315f4cc1-abe9-4860-940a-1596a008d083.mp4

**Comment by flamber** [comment]
@kulyk Still seems like it's problematic in 1.43.0-rc2 if you have a Model in the collection.

https://user-images.githubusercontent.com/1447303/166209613-2218f01d-f78d-43ce-9594-cddec2892cd8.mp4

**Comment by losrebellos** [comment]
This bug can be replicated with full app embedding:
1. Embed a collection with the `top_nav` + `new_button` parameters set to true
2. When viewing the collection, click on `New`
3. `Question` is not present in the list

It does not happen when `side_nav` is set:
1. Embed a collection with the `top_nav` + `new_button` + `side_nav` parameters set to true
2. When viewing the collection, click on `New`
3. `Question` is present in the list
