### ISSUE TITLE
URL being set to date after saving.

### ISSUE THREAD

**Issue by adjenks** [metabase/metabase#21535]
**Describe the bug**
After saving a question, it goes to a not found url, specifically a date in a date filter: 
![image](https://user-images.githubusercontent.com/10687569/162328272-18cccb24-fcf7-4e89-8988-4d48c9c0c41e.png)

**Logs**
JS console says this many times: https://reactjs.org/docs/error-decoder.html?invariant=188

**To Reproduce**
I can't reproduce it outside of this one question and I'd rather not show all the code.

**Expected behavior**
To just save the question

**Screenshots**
![image](https://user-images.githubusercontent.com/10687569/162330392-f33f88d6-ec0c-4ef4-810e-078d001ef5fb.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.59.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "oracle",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-03-23",
      "tag": "v0.42.3",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Not too bad

**Additional context**
It still saves the question after I say "yes, save and replace", which is why it's not a severe problem, it's just strange. it just navigates to a bad url after I save and I have to navigate elsewhere.

**Comment by paoliniluis** [comment]
Hi @adjenks, as you can imagine, it's impossible to debug something that we can't reproduce internally. If you can't share the steps of what you're doing, then this issue has to be closed and we won't be able to help you out.
