### ISSUE TITLE
Back button doesn't work after entering admin settings

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#21532]
**To Reproduce**
1. On the Metabase home page, click on the settings icon, and click "Admin settings"
2. Click the back button on your browser

**Screenshots**

https://user-images.githubusercontent.com/32746338/162299311-c9365672-c64a-48a7-aca7-035a49b4944a.mov

**Information about your Metabase Installation:**
Current master, testing on Firefox 98.0.2

**Comment by noahmoss** [comment]
Ran a bisect and found #20979 to be the commit that introduces this; FYI @alxnddr

**Comment by alxnddr** [comment]
@noahmoss good catch, thanks. I will take a look.
