### ISSUE TITLE
Issue: Error 400: invalid_request when getting the Auth Code (redirect_uri: urn:ietf:wg:oauth:2.0:oob)

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#21539]
Redirection error when I try to get the auth code for google analytics. Already followed the doc in adding service accounts, enabling API, using desktop app as application type, etc.

This is when I try to add Google Analytics database

- Your browser and the version: Mozilla/5.0
- Your operating system: Windows 10
- Metabase version: 0.34.1
- Metabase hosting environment: Ubuntu
- Metabase internal database: H2

**Comment by flamber** [comment]
You should upgrade immediately to a newer release of Metabase. Google Analytics requires a newer authentication method.
https://github.com/metabase/metabase/releases
