### ISSUE TITLE
Update Metabot Syntax

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2154]
Right now the Metabot syntax is a little too verbose. 

Let's streamline it down to:
`show` : same as the current `show card`
`list` : same as the current `list cards`
`dashboards` : same as the current `list dashboards` (or kill this entirely)

The rationale here:

* Dashboards aren't really going to be consumed in-channel, so there's probably not going to be a "show dashboard any time soon
* We don't use the word "card" anywhere else in the product for saved questions
* We have too few commands to start having 2-deep command heirarchies. The goal is to keep Metabot simple, sleek, and terse.

**Comment by camsaul** [comment]
That makes sense. I only made things 2-deep to begin with because I thought we'd end up with a lot more commands than we actually did
