### ISSUE TITLE
Bar chart created from scalars in a dashboard is set as a scalar in subscription

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21559]
**Describe the bug**
When you add a scalar to a dashboard and then add series to the scalar, the card is transformed into a bar chart (or funnel). If you send a subscription of this dashboard, then we send a number rather than a bar chart or a funnel, when both of them are supported.

**Logs**
No logs for this

**To Reproduce**
1) build 2 questions: sum of products filtered by doohickie, and sum of products filtered by gadget
2) add one of them to the dashboard and then add the other one as a series of the dashboard card (see a bar chart being created)
3) subscribe to the dashboard, now see the number being sent instead of a bar chart

[Or Flamber's repro
](https://github.com/metabase/metabase/issues/21559#issuecomment-1095190220)

**Expected behavior**
if we support the chart as a static viz, we should send it!

**Screenshots**
Dashboard
![image](https://user-images.githubusercontent.com/1711649/162535612-1cb277a5-e08b-42ad-af26-165e7c46e115.png)

Subscription (it will only send the first series as well, so keep this in mind for the fix)
![image](https://user-images.githubusercontent.com/1711649/162535648-f9b7fc2a-1a4a-45e7-abf6-afaec77201f2.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14.2
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
None

**Additional context**
Customer that reported this mentioned that they were using this feature to do barcharts as they couldn't get the data into the same database to build a barchart viz

**Comment by flamber** [comment]
@nemanjaglumac 
Reproduce:
1. Question > Sample > Orders - summarize Average of Total - save question as "Q1"
2. Question > Sample > Products - summarize Average of Price - save question as "Q2"
3. Dashboard - add "Q1", hover card "Add series" and select "Q2"

**Comment by nemanjaglumac** [comment]
Thank you, @flamber .
Always so concise and spot on!

**Comment by paoliniluis** [comment]
sorry @nemanjaglumac, I usually do this last thing in the day when my brain doesn't work anymore
