### ISSUE TITLE
Normal users can't create first snippet in Enterprise version

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21581]
**Describe the bug**
On a brand new Enterprise install, users don't have the ability to create snippets by default.
In addition, in order to grant access, an admin has to first create a snippet, then change the root permissions.

**Logs**
NA

**To Reproduce**
1) Set up a new instance on Enterprise
2) create a normal user
3) logged in as the normal user, try to create the first snippet, see the error

**Expected behavior**
Unless there's an explicit permission set by an administrator, normal users should be able to create a snippet

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/162749728-ce278e5d-e539-43e5-8bbe-f487319d6cf9.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
Annoying

**Additional context**
NA

**Comment by nemanjaglumac** [comment]
@paoliniluis and @flamber this was labeled as `Type:New Feature` back in the EE days. There is even a test that made sure this behavior is currently expected.
https://github.com/metabase/metabase/blob/master/frontend/test/metabase/scenarios/native/snippets/snippet-permissions.cy.spec.js#L32:L51

Also, look at the comment in this spec:
https://github.com/metabase/metabase/blob/master/frontend/test/metabase/scenarios/native/snippets/snippets.cy.spec.js
