### ISSUE TITLE
Query Build Card Save modal does not properly show errors from API

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#21597]
I ran into this while fixing #14145.

After PR #21598, the API returns a 400 error response (actually 202 with `_status` since the endpoint is async, but still effectively a 400):

```json
{"message":"Invalid Field Filter: Field 164574 \"PRODUCTS\".\"CATEGORY\" belongs to Database 2276 \"sample-dataset\", but the query is against Database 2275 \"test-data\"","_status":400}
```

But the Save Card modal just shows a Type Error:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1455846/162819328-e8a59843-ab96-48a2-abe9-77e226823f76.png">

Console logs:

```
Form.jsx:216 Form submission error TypeError: Cannot read properties of undefined (reading 'collection')
    at reducer (schemas.js:56:1)
    at redux.js:163:1
    at combination (combineReducers.js:120:1)
    at combination (combineReducers.js:120:1)
    at dispatch (createStore.js:165:1)
    at middleware.js:22:1
    at index.js:28:1
    at store.js:25:1
    at dispatch (applyMiddleware.js:35:1)
    at _callee3$ (redux.js:210:1)
```

It should show the actual error message here.

Note that #14145 is a custom success escalation so this should probably be considered one as well

**Comment by flamber** [comment]
Reproduce with PR #21598:
1. Admin > Databases > create another H2 database pointing to the sample dataset
2. Native > Sample Database > `SELECT COUNT(*) FROM PRODUCTS WHERE {{FILTER}}`
3. Change variable to Field Filter and connect to Products.Category
4. Run query - works
5. Change database (above the editor) to the second H2
6. Run query - fails with kinda understandable error
7. Save question - fails without understandable error

https://user-images.githubusercontent.com/1447303/163141717-d0824e81-9015-4d1a-bd43-799e9395148c.mp4
