### ISSUE TITLE
Add "Select All" on filter dropdowns

### ISSUE THREAD

**Issue by nunoyuzoreis** [metabase/metabase#21600]
**Is your feature request related to a problem? Please describe.**
When selecting all values in a question filter (with a bunch of items) I have to select them one by one, instead of just clicking on a "select all" option.

**Describe the solution you'd like**
A fixed first item on the dropdown menu would fit perfectly! (or a button next to the text input)

**How important is this feature to you?**
It would improve a lot the UX when having too many items on the list

![image](https://user-images.githubusercontent.com/2849384/162835492-e3140590-0bb3-4e44-a19b-6de823cf730b.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mngr** [comment]
Selecting all the values is equivalent to just not filtering at all. This is achieved my making sure the filter is optional and clearing the value.

**Comment by mf-chrisburchhardt** [comment]
> Selecting all the values is equivalent to just not filtering at all. This is achieved by making sure the filter is optional and clearing the value.

I think the use case is more to be able to "Select All" values from a huge list, then deselect a few that you want to exclude

**Comment by mngr** [comment]
> I think the use case is more to be able to "Select All" values from a huge list, then deselect a few that you want to exclude

I see, this makes sense, but the solution then should be something like a checkbox or a toggle to exclude selected values.
Thanks, I'll take this to my backlog.

**Comment by dbachet** [comment]
Our workaround is to select values by default on backend. In our case we always want the same to be selected (~55 out ~60).

I think it's a common pattern to have a "select all" checkbox and unselect.

**Comment by mngr** [comment]
> I think the use case is more to be able to "Select All" values from a huge list, then deselect a few that you want to exclude
<img width="383" alt="Captura de ecrã 2024-08-19, às 09 16 26" src="https://github.com/user-attachments/assets/fb4d11aa-545d-4acf-b2da-62ebbd3888f2">

Just to double check, we have "Does not contain" operator for text filters, doesn't it solve this problem?

**Comment by mf-chrisburchhardt** [comment]
It technically does, but definitely isn't as user-friendly and accessible, especially to the less-technical users we're working on adopting. That also makes the UX even worse if they _do_ only want to select a few options. Google Sheets and most tools they use let them select-all/clear-all options.

**Comment by willcroft** [comment]
> I think the use case is more to be able to "Select All" values from a huge list, then deselect a few that you want to exclude

That, or typing the first few letters in the filter search bar to get a matched subset from a long list, and then "select all" to include all the visible matches

**Comment by mngr** [comment]
> What would help unblock this @mngr? Is it as simple as rebasing the existing PR on the current state of `master` to ease review, or was there a deeper issue with the original suggested approach? Happy to contribute!

There is a deeper issue with how we cache and fetch field values. Basically when your field has like thousands of distinct values we are not loading them all, so even if we add a checkbox to "Select All" values shown in the list it will not in fact select all the (matching) values.

**Comment by willcroft** [comment]
Ah understood! When you type to narrow down the filter values, are all values fetched, or is that a subset as well?

**Comment by mngr** [comment]
> Ah understood! When you type to narrow down the filter values, are all values fetched, or is that a subset as well?

We fetch all the values when there are not many of them.
Yeah, I think we could show "Select all" in this case. We'll evaluate this idea.

**Comment by harshpatil273** [comment]
Do you have any planned release or rollout date for this feature?

**Comment by mngr** [comment]
> Do you have any planned release or rollout date for this feature?

We might release it in the 51st version which is coming soon

**Comment by mngr** [comment]
#48086
