### ISSUE TITLE
[Epic] Booleans as Literals in Custom Expressions

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#21622]
Project Doc: https://www.notion.so/metabase/Add-Booleans-as-literals-to-Custom-Expressions-879fbde51ab14a5abae0f040a1f4d3b0

Steps:
 - [x] booleans as literals in custom expressions filters (https://github.com/metabase/metabase/pull/21342)

**Comment by luizarakaki** [comment]
Merged to master
