### ISSUE TITLE
Field is not showing up in "View" dropdown

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#2164]
If this is a bug report, please fill in the blanks:

*  I am using the ___________ browser.
*  My computer's OS is ___________.
*  I'm running Metabase ___________. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is ___________.
*  My Metabase version is ___________.

I'm trying to select a field but it's not showing up in the view dropdown.

![image](https://cloud.githubusercontent.com/assets/539599/13823817/af4f15c4-eb81-11e5-82c4-67133c85832e.png)

I'm trying to select the field "media url" which seems like I should be able to select it according to my admin panel.

![image](https://cloud.githubusercontent.com/assets/539599/13823837/c571b334-eb81-11e5-8a10-53d6ea109c4c.png)

**Comment by camsaul** [comment]
Hi @infomofo, any chance you can "fill in the blanks"? It will help us determine the cause of your issue and whether it's one that's already been fixed

**Comment by mazameli** [comment]
@infomofo I believe this is a UX bug we've run into before: in the admin panel, try changing the `Information` dropdown to `Dimension`. Metabase does some automatic heuristics-based filtering of fields to keep from presenting each and every field in a table as a choice for groupings, but it still gets it wrong a bit too often. Let me know if this fixes it for you.

**Comment by infomofo** [comment]
@mazameli that worked- i'm still a little confused on what those columns mean to be honest

@camsaul sorry bout that I'll fill them in next time for sure.

**Comment by mazameli** [comment]
@infomofo I'm glad that worked, and I'm sorry about the confusion. The team here definitely agrees that those columns in the admin panel are confusing, and we're discussing some ways to simplify those options. Appreciate your feedback.
