### ISSUE TITLE
Three users (out of ~140) getting blank screen on chrome after update to 0.42.4

### ISSUE THREAD

**Issue by AndrewLWilson** [metabase/metabase#21656]
**Describe the bug**
Three of our users are getting a blank white page in chrome when trying to access Metabase since we updated to 0.42.4 yesterday.  We host on Elastic Beanstalk and the issue persists when they use the EB url directly (we have a CNAME set up in Cloudfront).  When an affected user viewed the page source they got this:
```
if (actualRoot !== configuredRoot) {
    console.warn("Warning: the Metabase site URL basename \"" + configuredRoot + "\" does not match the actual basename \"" + actualRoot + "\".");
    console.warn("You probably want to update the Site URL setting to \"" + window.location.origin + actualRoot + "\"");
    document.getElementsByTagName("base")[0].href = actualRoot;
  }
  window.MetabaseRoot = actualRoot;
```
Not sure what to make of that.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
I haven' t been able to reproduce myself.

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.14.268-205.500.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Since only three of our users are affected I would categorize this as a moderate bug.

**Additional context**

**Comment by flamber** [comment]
Hi @AndrewLWilson 
It's impossible to know what is going on, but most likely a browser extension causing problems for the three users.
Or some antivirus function: https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Comment by AndrewLWilson** [comment]
> Hi @AndrewLWilson It's impossible to know what is going on, but most likely a browser extension causing problems for the three users. Or some antivirus function: https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

Thanks for the quick response, I'll push harder on the users about triple checking that they don't have any antivirus/browser extensions enabled.

**Comment by AndrewLWilson** [comment]
I have updates!

### Things I tried that didn't work:
 - reset the user's password
 - restarted their browser and computer
 - disabled all their chrome extensions
 - cleared their cookies (ouch)
 - disabled and reenabled their Metabase users
 
## What worked:
 - I rolled back from v0.42.4 to v0.42.3, and it resolved the issue for 1 of 3 affected users.  
 - Then I rolled back from v0.42.3 to v0.42.2 and it resolved the issue for the remaining 2 users.

Note: the last two affected users both reside in Austin TX, but that is _probably_ a coincidence.

**Comment by flamber** [comment]
@AndrewLWilson Reset their password and then you can try to login from your machine. If it works, then you know 100% it's a client problem. Check the browser developer console for errors. And read https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html
