### ISSUE TITLE
SAML Identity Provider URL won't show as configured when passed as env var

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21677]
**Describe the bug**
All other env vars show "using value of...", not this one when it's configured

**Logs**
No logs

**To Reproduce**
1) set up Metabase Enterprise and pass:
MB_SAML_IDENTITY_PROVIDER_ISSUER
MB_SAML_IDENTITY_PROVIDER_URI
MB_SAML_ENABLED
MB_SAML_ATTRIBUTE_EMAIL
MB_SAML_ATTRIBUTE_FIRSTNAME
MB_SAML_ATTRIBUTE_LASTNAME
MB_SAML_APPLICATION_NAME
2) If you go to admin->settings->authentication->saml, you'll see all other env vars populated, not this one

**Expected behavior**
see the same message to indicate the admin that the env var is populated

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/163461890-5b26576b-ddaf-42c8-907e-760f461934f0.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgre
- Metabase version: 14
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
Cosmetic

**Additional context**
NA

**Comment by flamber** [comment]
Likely caused by `placeholder` attribute - also, why does it have `autoFocus`:
https://github.com/metabase/metabase/blob/1b520c8871bf088adcd9eb61fc9f72ab01df2d31/enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm.jsx#L108-L110
Related to #20773

**Comment by daltojohnso** [comment]
I'm guessing we're doing this for the same reason as https://github.com/metabase/metabase/issues/20773#issuecomment-1101667258

**Comment by flamber** [comment]
@daltojohnso Yes, it's the same for all envvars - they should not be displayed in-app, just the default message:
https://github.com/metabase/metabase/blob/0708ce0a0f7ce75d3007504fdb40969a8f5e24a2/src/metabase/models/setting.clj#L1012
