### ISSUE TITLE
Pivot Table query optimization

### ISSUE THREAD

**Issue by prigal** [metabase/metabase#21688]
@luizarakaki comment:

We should improve the Pivot Table query in two ways:

- [ ] Move filtering clauses to the inner query (so it actually use indexes).
- [ ] Select only relevant fields in the inner query. If the table has more fields than used for breakouts, we should get only the necessary to build the pivot.

---
_Original issue_
Hello metabase team,

I'm playing with pivot table and found them extremely slow. 

After some digging, I'm not alone : 
- https://discourse.metabase.com/t/pivot-tables-extremely-slow/13694
- https://discourse.metabase.com/t/how-to-improve-performance-in-data-present-in-pivod-table/16350/8
- https://discourse.metabase.com/t/pivot-table-is-just-running/16602

I did some research on how table are pivoted looking at queries generated on my database and I probably found an optimization with filters. 

**Example source query :** 

 ```
SELECT `REQUEST`.`REQ_ID` AS `REQ_ID`,
 		`REQUEST`.`REQ_DATETIME` AS `REQ_DATETIME`,
          `Agence`.`AG_NOM` AS `Agence__AG_NOM`,
          `Marque`.`LIBELLE` AS `Marque__LIBELLE`,
          `Status`.`STA_NAME` AS `Status__STA_NAME`
   FROM `REQUEST`
   LEFT JOIN `AGENCE` `Agence` ON `REQUEST`.`AG_ID` = `Agence`.`AG_ID`
   LEFT JOIN `REF_SOCIETE` `Marque` ON `Agence`.`SOC_ID` = `Marque`.`SOC_ID`
   LEFT JOIN `STATUS` `Status` ON `REQUEST`.`REQ_LAST_STATUS` = `Status`.`STA_ID`
   LEFT JOIN `AGENCE` `AGENCE__via__AG_ID` ON `REQUEST`.`AG_ID` = `AGENCE__via__AG_ID`.`AG_ID`
   WHERE (`REQUEST`.`REQ_DATETIME` >= date(now(6))
       AND `REQUEST`.`REQ_DATETIME` < date(date_add(now(6), INTERVAL 1 DAY)))
```

Result : 145 row(s) fetched - 39ms (4ms fetch), on avr. 15, 09:39:30

**Pivoted one :** 

```
SELECT `source`.`Marque__LIBELLE` AS `Marque__LIBELLE`,
       `source`.`Agence__AG_NOM` AS `Agence__AG_NOM`,
       `source`.`Status__STA_NAME` AS `Status__STA_NAME`,
       `source`.`pivot-grouping` AS `pivot-grouping`,
       count(DISTINCT `source`.`REQ_ID`) AS `count`
FROM
  (SELECT `REQUEST`.`REQ_ID` AS `REQ_ID`,
  		   `REQUEST`.`REQ_DATETIME` AS `REQ_DATETIME`,
          abs(0) AS `pivot-grouping`,
          `Agence`.`AG_NOM` AS `Agence__AG_NOM`,
          `Marque`.`LIBELLE` AS `Marque__LIBELLE`,
          `Status`.`STA_NAME` AS `Status__STA_NAME`
   FROM `REQUEST`
   LEFT JOIN `AGENCE` `Agence` ON `REQUEST`.`AG_ID` = `Agence`.`AG_ID`
   LEFT JOIN `REF_SOCIETE` `Marque` ON `Agence`.`SOC_ID` = `Marque`.`SOC_ID`
   LEFT JOIN `STATUS` `Status` ON `REQUEST`.`REQ_LAST_STATUS` = `Status`.`STA_ID`
   LEFT JOIN `AGENCE` `AGENCE__via__AG_ID` ON `REQUEST`.`AG_ID` = `AGENCE__via__AG_ID`.`AG_ID`) `source`
WHERE (`source`.`REQ_DATETIME` >= date(now(6))
       AND `source`.`REQ_DATETIME` < date(date_add(now(6), INTERVAL 1 DAY)))
GROUP BY `source`.`Marque__LIBELLE`,
         `source`.`Agence__AG_NOM`,
         `source`.`Status__STA_NAME`,
         `source`.`pivot-grouping`
ORDER BY `source`.`Marque__LIBELLE` ASC,
         `source`.`Agence__AG_NOM` ASC,
         `source`.`Status__STA_NAME` ASC,
         `source`.`pivot-grouping` ASC
```

Result : 16 row(s) fetched - 10.524s (1ms fetch), on avr. 15, 09:45:33

Problem : the "source" sub query is not filtered as asked in initial query, only the pivot is filtered. 

**Optimized pivot** (where clause on source, not on pivot) : 

```
SELECT `source`.`Marque__LIBELLE` AS `Marque__LIBELLE`,
       `source`.`Agence__AG_NOM` AS `Agence__AG_NOM`,
       `source`.`Status__STA_NAME` AS `Status__STA_NAME`,
       `source`.`pivot-grouping` AS `pivot-grouping`,
       count(DISTINCT `source`.`REQ_ID`) AS `count`
FROM
  (SELECT `REQUEST`.`REQ_ID` AS `REQ_ID`,
  		   `REQUEST`.`REQ_DATETIME` AS `REQ_DATETIME`,
          abs(0) AS `pivot-grouping`,
          `Agence`.`AG_NOM` AS `Agence__AG_NOM`,
          `Marque`.`LIBELLE` AS `Marque__LIBELLE`,
          `Status`.`STA_NAME` AS `Status__STA_NAME`
   FROM `REQUEST`
   LEFT JOIN `AGENCE` `Agence` ON `REQUEST`.`AG_ID` = `Agence`.`AG_ID`
   LEFT JOIN `REF_SOCIETE` `Marque` ON `Agence`.`SOC_ID` = `Marque`.`SOC_ID`
   LEFT JOIN `STATUS` `Status` ON `REQUEST`.`REQ_LAST_STATUS` = `Status`.`STA_ID`
   LEFT JOIN `AGENCE` `AGENCE__via__AG_ID` ON `REQUEST`.`AG_ID` = `AGENCE__via__AG_ID`.`AG_ID`
   WHERE (`REQUEST`.`REQ_DATETIME` >= date(now(6))
       AND `REQUEST`.`REQ_DATETIME` < date(date_add(now(6), INTERVAL 1 DAY))) ) `source`
GROUP BY `source`.`Marque__LIBELLE`,
         `source`.`Agence__AG_NOM`,
         `source`.`Status__STA_NAME`,
         `source`.`pivot-grouping`
ORDER BY `source`.`Marque__LIBELLE` ASC,
         `source`.`Agence__AG_NOM` ASC,
         `source`.`Status__STA_NAME` ASC,
         `source`.`pivot-grouping` ASC
```

16 row(s) fetched - 20ms, on avr. 15, 09:47:26

From 10.524s to 20ms, it's 99.8% better. 

Do you think this can be implemented ? 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by rcronin** [comment]
Would definitely love to see this one fixed. Number one complaint from our end user.

**Comment by prigal** [comment]
Hello @flamber, I would like to know if it's something that is actually under investigation ? 

Pivot table is the main reason why my direction would like to migrate to PowerBI :-( 

Thank you.

**Comment by flamber** [comment]
@prigal I cannot give you a timeline on this, or any of the 600 other bugs. The roadmap says Pivot Tables are being looked at in the upcoming major release, but I cannot say if this issue will be addressed: https://www.metabase.com/roadmap/

**Comment by prigal** [comment]
I understand. Thanks for your feedback and your work.
