### ISSUE TITLE
Grant Collection-only access that respects data sandboxing

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21703]
**Is your feature request related to a problem? Please describe.**
Right now if you give sandboxed access to users, it will allow self serve permissions, so normal users will be able to browse the tables they are sandboxed to. Some customers would like to give users a "view-only" experience and only to collections, while keeping the sandboxing.

**Describe the solution you'd like**
A middle ground permission between the "No self-service" and "Sandboxed", so Sandboxed users can't browse the data, but can see pre-defined reports

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Some customers requested this specific permission

**Additional context**
NA

**Comment by luizarakaki** [comment]
Will be resolved by #26918
