### ISSUE TITLE
Incorrect conditional formatting in dashboard subscription

### ISSUE THREAD

**Issue by Rmonik** [metabase/metabase#21747]
**Describe the bug**

When sending an email from a dashboard subscription, the conditional formatting based on range doesn't behave as expected.

**Logs**
n/a

**To Reproduce**
1. Create a dashboard 
2. Add a question which is visualized as a table with conditional formatting on a column
3. Send an email through dashboard subcriptions

**Expected behavior**

The conditional formatting shows in the same fashion in the email as it does in browser

**Screenshots**

The email:

<img width="595" alt="Screenshot 2022-04-19 at 14 53 46" src="https://user-images.githubusercontent.com/16976971/164010056-d36e96de-ccc4-4b52-8dbd-18bae5b1c1d6.png">

The dashboard:

<img width="688" alt="Screenshot 2022-04-19 at 15 02 28" src="https://user-images.githubusercontent.com/16976971/164010115-cfc17c99-3851-4b33-9546-065aaba87c26.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Metabase version: 0.42.1
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**

Low -- The conditional formatting only provides visual clarity and ease of use.

**Additional context**

n/a

**Comment by Rmonik** [comment]
As an aside, I'm aware that we're not running the most recent version, but this doesn't seem to be in the patch notes for the more recent ones.

**Comment by flamber** [comment]
Hi @Rmonik 
It looks very similar to #13892, but I cannot reproduce this for decimal numbers.
How exactly are you creating the columns? Can you provide steps-to-reproduce with Sample Database.
There are several other reasons to upgrade to 0.42.4
Please post "Diagnostic Info" from Admin > Troubleshooting.

**Comment by Rmonik** [comment]
Hi @flamber 
I don't se anything particular in the logs after resending the emails: 
[logsmetabase.txt](https://github.com/metabase/metabase/files/8530286/logsmetabase.txt)
These are constructed as a percentage via the visualization screen:

![Screenshot 2022-04-21 at 12 52 02](https://user-images.githubusercontent.com/16976971/164443157-1daa7f0e-e699-48e1-8f7b-15436c7e8ebb.png)

It does look extremely similar to #13892 indeed.

**Comment by flamber** [comment]
@Rmonik I cannot reproduce.
Please post "Diagnostic Info" from Admin > Troubleshooting.
