### ISSUE TITLE
Can I plot a couple of columns from a table without grouping or aggregating?

### ISSUE THREAD

**Issue by ashrowty** [metabase/metabase#2174]
i am not grouping or aggregating, but simply want to plot a couple of columns from a very wide table in my datasource. this should be pretty easy to do, i imagine?

thanks,
ashish

**Comment by agilliland** [comment]
Sadly, no.  At present that's not a use case we are optimized for.  We have a proposal in place to support that though, so I expect that ability to be coming shortly.

As a possible workaround you can still go ahead and group by whatever dimension you want to chart and simply sum() the metric you are using.  That should produce just the 2 columns from your table that you are looking for without actually changing the data.  Hokey, but at least it'll allow you to move forward.
