### ISSUE TITLE
There was a problem displaying this chart

### ISSUE THREAD

**Issue by oconway** [metabase/metabase#21745]
**Describe the bug**
Error message 'There was a problem displaying this chart' when viewing 'VAC084 Diary Dashboard' - Solicted AEs.
Data is accessible via filter but not displaying like the other dashboard tables.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to 'Malaria'
2. Click on 'VAC084'
3. Click on 'VAC084 dashboards'
4. Click on 'VAC084 Diary Dashboard'
5. 5. See 'VAC084 Diary Solicited AEs'

**Expected behavior**
Dashboard table to display on opening.

**Screenshots**
![image](https://user-images.githubusercontent.com/104007558/164007010-b783bb61-3179-454c-a9a1-be445568e96b.png)
**Severity**
Not a major issue as users can filter for specific ID's to make dashboard work. 

**Metabase Diagnostic Info**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.39",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.49.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "oc-insight-mbpg-driver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-10",
      "tag": "v1.40.7",
      "branch": "release-x.40.x",
      "hash": "07fdc71"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
Hi @oconway 
The error comes from the custom driver `oc-insight-mbpg-driver`, so open an issue in that repo.
Your steps-to-reproduce are impossible to follow for anyone who doesn't have access to your data, which only you have.
If you are an Enterprise customer, then please contact Metabase support via email.
