### ISSUE TITLE
MySQL should use sample standard deviation

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2175]
MySQL's `stddev()`is an alias of `stddev_pop()`, i.e. a population standard deviation. All of our other databases that support standard deviations do sample ones, which is available in MySQL as `stddev_samp()`. We should use this function instead to bring MySQL's behavior in line with our other databases.

This would probably let us eliminate some of the special-casing in the unit tests around sample deviation aggregations where MySQL returns slightly different results from the other DBs.

**Comment by MrMauricioLeite** [comment]
Cant we have both options for aggregation on all databases? 
The sampled one and the unsampled.

**Comment by camsaul** [comment]
@MrMauricioLeite issue #2176 considers whether we should expose both. 

Do you have any real-world use cases for one vs. the other?

**Comment by MrMauricioLeite** [comment]
Not really @camsaul, I just though that if a power user run a query via SQL using avg in Mysql he can receive a different value from the question builder. So it would be nice to let the user know witch of the avg-functions we are using.

**Comment by camsaul** [comment]
@MrMauricioLeite you mean `stddev`, right? There's only one `avg` function. 

In SQL queries people can use either standard deviation function so we should clarify which one the query builder uses (mentioned in #2176) so there's no confusion.

**Comment by agilliland** [comment]
I think we should resolve #2176 as a proposal before moving forward with this issue.  It may turn out this issue isn't really relevant if we decide to support both types of `stddev`.

I'm glad we have this as a reminder this issue though, so thanks for creating it @camsaul

**Comment by camsaul** [comment]
If we decide to support both types, for backwards-compatibility with existing cards we'll probably want to keep sample as `stddev` and call population `stddev-pop` or something like that. So in that case I think we would still want to switch the MySQL behavior of `stddev` over to keep things consistent

**Comment by agilliland** [comment]
Yeah, that definitely makes sense.

**Comment by salsakran** [comment]
closing this until someone in the community cares.
