### ISSUE TITLE
Foreign Key Relationships in Object Detail View incorrectly default to first foreign key 

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#21757]
**Describe the bug**
Often (but not always, I haven't been able to figure out the cause here), clicking the foreign-key relationship links in an object detail component links to the first foreign key for the foreign table, instead of the desired foreign key.

**To Reproduce**
In the sample db:
1. Brows the products table
2. Click on id 6 to view details for that product
3. See that it's linked to 93 orders
4. Click on the 93 orders linked
5. See that you're taken to a detail item linked to product id 1 instead of 6.

**Expected behavior**
We should get a new question filtered by the correct foreign key instead of the first foreign key and/or taken to a detail record with the correct foreign key.

**Screenshots**

https://user-images.githubusercontent.com/30528226/164042872-82b24177-b5b1-4572-a103-058d176bbcfe.mp4

https://user-images.githubusercontent.com/30528226/164042876-230123e9-7ef8-42fe-b7f3-d175d1d3b02a.mp4

**Information about your Metabase Installation:**

Your browser and the version: Google Chrome Version 100.0.4896.127 (Official Build) (64-bit)
Your operating system: Ubutntu 20.04
Your databases: Postgres 14.2
Metabase version: master branch - 2022-04-19 - v0.42.1-SNAPSHOT"
Metabase hosting environment: local development
Metabase internal database: H2

**Severity**

Makes the relationships links useless in many situations

**Comment by flamber** [comment]
This is kinda a repeat of #13717
