### ISSUE TITLE
Consider whether to expose both sample and population standard deviations

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2176]
All the DBs we support support both types.

<table>
  <tr>
    <th>Database</th><th>population</th><th>sample</th>
  </tr>
  <tr>
    <th>BigQuery</th>
    <td><tt>stddev_pop()</tt></td>
    <td><tt><b>stddev()</b></tt>
            <tt>stddev_samp()</tt></td>
  </tr>
  <tr>
    <th>H2</th>
    <td><tt>stddev_pop()</tt></td>
    <td>
      <tt><b>stddev()</tt></b>
      <tt>stddev_samp()</tt>
    </td>
  </tr>
  <tr>
    <th>MySQL</th>
    <td><tt><b>stddev()</b></tt>
        <tt>stddev_pop()</tt></td>
    <td><tt>stddev_samp()</tt></td>
  </tr>
  <tr>
    <th>Postgres / Redshift</th>
    <td><tt>stddev_pop()</tt></td>
    <td><tt><b>stddev()</b></tt> <tt>stddev_samp()</tt></td>
  </tr>
  <tr>
    <th>SQLServer</th>
    <td><tt>stdevp()</tt></td>
    <td><tt><b>stdev()</b></tt></td>
  </tr>
  <tr>
    <th>MongoDB</th>
    <td><tt>$stdDevPop</tt></td>
    <td><tt>$stdDevSamp</tt></td>
  </tr>
</table>
Currently used functions in bold. 

It would be nice to hear from someone who actually uses standard deviation aggregations IRL and see whether they want both, neither, or one or the other. At any rate, we should clarify in the description which type of standard deviation we offer.

Related: #2175

**Comment by agilliland** [comment]
My vote would be to include them both and let users choose.

**Comment by camsaul** [comment]
Every new option makes MB more confusing and our code harder to maintain, so we should be certain people actually want these first and that their benefits outweigh their costs. I think it makes the most sense to get the opinion of one or two people who actually use these IRL. It may well be the case that one type of std dev is nothing but a needless extra knob that no one will ever use.

**Comment by MrMauricioLeite** [comment]
What do you think @kdoh and @mazameli ?

**Comment by salsakran** [comment]
Both of these are technically measuring the same thing. Most people just want to "know the std dev". It takes a fair bit of statistical understanding to know the difference and I think if we include both, we're just leaking complexity.

The choice of an exact or sampled method is an optimization. I think we should expose a single exposed `standard deviation` and have it do whatever the database in question thinks should be the default. Lots of other statistical functions are going to have similar concerns (eg, iterative approximation, vs exact calculation across all rows, etc) and I don't want to have a 10 level deep Choose Your Own Adventure for each of them. 

I think it's very much against the Zen of Metabase to leak details about implementation of aggregates, and this falls smack dab in the the center.

**Comment by salsakran** [comment]
closing this until someone in the community cares.
