### ISSUE TITLE
If a user has data model access only to one table and this table has FKs, the target is key is empty

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#21762]
The user shouldn't see the field name, but the current state looks like the FK is not assigned.

Ideally, we should communicate that the field is assigned to a foreign key, but the user doesn't have access to that field.

`Field access denied` is a good text short and explicit

![image](https://user-images.githubusercontent.com/32561114/164059473-ebd7fc34-c572-484d-b7c4-a1da6865d1c0.png)

**Comment by nemanjaglumac** [comment]
Why do we show Orders -> ID as a "foreign" key and allow user to select it for "Orders" table?
