### ISSUE TITLE
The date filter isn't resetting the state when closed

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#21779]
Reproduce:
- Sample Database > Orders > Filter
- Filter by `Created At`
- Specific dates > After
- Back button and back button again
- Click `Created At`
- It goes directly to the After tab

Expected
- It should go to the first list of date filter options (today, yesterday, last week, ...)

**Comment by nemanjaglumac** [comment]
@luizarakaki saying "back button" can be confusing. At least it confused me at first, until I realized what you meant. I was trying the **browser** back button.

It really helps if repro steps have a screenshot or two and if steps are numbered (that way we can point to the specific step). Basically ANY issue that @flamber creates is a bright example and an ideal we should all strive to emulate when creating issues (no matter how simple they might seem at first).
