### ISSUE TITLE
Consider adding variance / other statistical aggregation functions :cherries:

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2177]
_Population & sample variance_ are offered by almost every DB we support. In addition, Postgres & BigQuery have _covariance_ and _correlation coefficient_ options. Should we expose them as aggregation options?

<table>
 <tr>
   <th>Database</th>
   <th>population variance</th>
   <th>sample variance</th>
   <th>population covariance</th>
   <th>sample covariance</th>
   <th>Pearson correlation coefficient</th>
 </tr>
  <tr>
    <th><a href="https://cloud.google.com/bigquery/query-reference#aggfunctions">BigQuery</a></th>
    <td><tt>var_pop()</tt></td>
    <td><tt>variance()</tt> <tt>var_samp()</tt></td>
    <td><tt>covar_pop()</tt></td>
    <td><tt>covar_samp()</tt></td>
    <td><tt>corr()</tt></td>
  </tr>
  <tr>
    <th><a href="http://h2database.com/html/functions.html#selectivity">H2</a></th>
    <td><tt>var_pop()</tt></td>
    <td><tt>var_samp()</tt></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th><a href="http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html">MySQL</a></th>
    <td><tt>var_pop()</tt> <tt>variance()</tt></td>
    <td><tt>var_samp()</tt></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th><a href="http://www.postgresql.org/docs/9.5/static/functions-aggregate.html">Postgres</a></th>
    <td><tt>var_pop()</tt></td>
    <td><tt>variance()</tt> <tt>var_samp()</tt></td>
    <td><tt>covar_pop()</tt></td>
    <td><tt>covar_samp()</tt></td>
    <td><tt>corr()</tt></td>
  </tr>
  <tr>
    <th><a href="http://docs.aws.amazon.com/redshift/latest/dg/c_Aggregate_Functions.html">Redshift</a></th>
    <td><tt>var_pop()</tt></td>
    <td><tt>variance()</tt> <tt>var_samp()</tt></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th><a href="https://technet.microsoft.com/en-us/library/aa258901(v=sql.80).aspx">SQL Server</a></th>
    <td><tt>varp()</tt></td>
    <td><tt>var()</tt></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

Someone must use these, otherwise their support wouldn't be ubiquitous. It would be nice to hear from one of those people and gauge their interest. Is this BASIC need for all users? Should we embrace the complexity?

**Comment by agilliland** [comment]
nice work on that grid.  super useful :+1:

**Comment by sbelak** [comment]
Implemented in #12096
