### ISSUE TITLE
When moving a collection, invalid choices should just be disabled

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#21786]
If Metabase doesn't want me to get all wacky and try to move a collection into itself, or to move a parent collection into one of its sub-collections, those collections should just be disabled/unselectable in the picker. 

It shouldn't be possible for me to ever see this error:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2223916/164117485-91893ec2-9106-4a45-84ef-e1687c2fef7d.png">

This straddles the line between bug and UX to me.

**Comment by iethree** [comment]
should be addressed by https://github.com/metabase/metabase/issues/35564
