### ISSUE TITLE
Sort pivot tables by clicking on headers

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21787]
**Is your feature request related to a problem? Please describe.**
In the same way we offer sorting in normal tables by clicking on headers, we should offer the same feature on pivot tables.

**Describe the solution you'd like**
Provide sorting features on pivot tables by clicking on the headers

**Describe alternatives you've considered**
Right now you have to edit the pivot table, sort on the fields, and then save it. Normal users (users with no permissions to edit) can't do this

**How important is this feature to you?**
Important (provide consistency across viz's)

**Additional context**
Reported by a customer

**Comment by flamber** [comment]
Sounds like a duplicate of #14970

**Comment by paoliniluis** [comment]
> Sounds like a duplicate of #14970

Yup
