### ISSUE TITLE
Allow for pulse cards to be reordered

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#2179]
If this is a bug report, please fill in the blanks:
-  I am using the Chrome browser.
-  My computer's OS is OSX.
-  I'm running Metabase 0.15.0. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is psql.
-  My Metabase version is 0.15.0.

I am editing a pulse with 5 cards in it.  I realize that the card I have selected in the second slot is not really what I want.  My options are either to delete that card and add the one I want at the end, or to delete cards 2-5 and readd all of them.  It would be cool if I could reorder the cards. The pulse I'm trying to create is a funnel of 5 events, so the order is important.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by kdoh** [comment]
Heya @infomofo. Unfortunately not at the moment without doing it in the kinda gross manual fashion like you described. :( Thanks for letting us know its something you'd like.

**Comment by MrMauricioLeite** [comment]
+1 This would be awesome and seems fairly easy.
Maybe I can get this to solve as an test of my programming skills for contributing to metabase. (I'll at least try)

**Comment by ActionHank** [comment]
Awaiting implementation of this feature.

**Comment by tashiritzy** [comment]
Awaiting this feature too.

**Comment by flamber** [comment]
Closing, since this is now implemented in Dashboard Subscriptions: https://www.metabase.com/docs/latest/users-guide/dashboard-subscriptions.html
