### ISSUE TITLE
Remove the max-width on QB title element

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2180]
Seeing this happen when there is really no reason for wrapping.

<img width="705" alt="screen shot 2016-03-17 at 1 29 09 pm" src="https://cloud.githubusercontent.com/assets/1987787/13860193/5b6eda66-ec44-11e5-8538-cf777eb19ee1.png">

**Comment by agilliland** [comment]
@kdoh any concerns about this?  I'm basically thinking this element should be setup such that it can consume most of the available space leading over to the icon bar, and we can control the buffer between them with padding.

**Comment by kdoh** [comment]
Do we have a max length on validation on question titles? The main reason the max width is there is to make sure the title wraps at a semi readable line length and doesn't crowd the actions.

**Comment by agilliland** [comment]
No, we don't.  The screenshot is perhaps a little cut off, but this felt odd because the wrapping occurred at roughly 1/3rd of the screen width, leaving a ton of unused white space between the action buttons and the title which very reasonably could have been used.

It's up to you if we want to change anything here or just leave it, but my vote would probably be for one or both of ... A) allow the length to extend further, likely being controlled by some kind of fixed padding from the action buttons like `paddingRight: "100px"` and/or B) consider ellipsifying the title instead of wrapping it and then using a tooltip on hover to give the full title if needed.

My take is that the wrapping looks strange, so we should try to prevent it.

**Comment by tlrobinson** [comment]
This is fixed.
![screenshot 2017-02-07 17 55 44](https://cloud.githubusercontent.com/assets/18193/22720278/aee4789c-ed5e-11e6-98d2-6a909e2cdf0a.png)
