### ISSUE TITLE
Relative quarter filter not working in Postgres

### ISSUE THREAD

**Issue by Despairs** [metabase/metabase#21802]
**Describe the bug**
When using relative filter by quarter on a Postgres database the following error appears:
`ERROR: invalid input syntax for type interval: "1 quarter" Position: 1546`

**Logs**
[quarter.log](https://github.com/metabase/metabase/files/8522671/quarter.log)

**To Reproduce**

1. Create question
2. Add question to
3. Create a filter using a date and filter by current quarter

**Expected behavior**
Filter by current quarter is actually filtering instead of giving an error

**Screenshots**
![image](https://user-images.githubusercontent.com/4972418/164260860-24ca1c51-6972-45b3-8844-0f6754be1005.png)

**Severity**
Relative filter can be replaced with Quarter-Year Date filter, but it not so convenient

**Additional context**
Expected that it was fixed at #20683 in 0.42.4 but still present

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.59.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
The backport was never completed. Sorry about that.
It will be part of 0.43 (it's working in 0.43.0-rc1). Closing this and changing milestone on #20683
