### ISSUE TITLE
Allow users to edit & re-run a query before the previous query finishes

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#2181]
I wrote a bad query- it took too long.  I had to wait a minute until I got the "Your question took too long" screen.  

I realized while it was running that it was poorly written and fixed it in the minute before it timed out

After that, there was no "retry" button.  If I make superficial changes to the query the retry button came back, but it seems to be comparing my query to the contents of the editor as of the last time the query timed out, not the actual query that ran

**Comment by infomofo** [comment]
Also- I wish I could just cancel a query while it's running too long so I can try again.

**Comment by MrMauricioLeite** [comment]
Can we prevent edits on the query while it is running?
Can we cancel the running query if something changes on the client side?

Can we check if the query changed against the one metabase just received the results, to enable the button os run query again?

**Comment by infomofo** [comment]
1) I don't like the idea of preventing edits while it's running.  It limits its usefulness as an editor.
2) I think that canceling it automatically seems extreme
3) I think the query should be saved client side at the time of execution and that is what can be compared against to prevent re-execution (if that is really necessary)

**Comment by MrMauricioLeite** [comment]
@infomofo I agree, maybe just hash the command that was sent and give it back to the browser to check back against a hash of what is on the editor right now (at the end of query execution)

**Comment by agilliland** [comment]
If someone feels strongly that actively canceling a query is a desirable feature then that should be added as a separate issue.

There is certainly merit in the idea of not blocking the UI when a query is being run and instead allowing the query to be modified and re-run before the previous execution finishes.
