### ISSUE TITLE
Is there a nightly build for beta testing

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2182]
I really love how metabase works and how active you guys are in development. But I sometimes can't help to debug something or I'm excited to test something and can't have a version builded on last night.

Is there such a thing? Do you mind opening it up to public? 

Just an idea, feel free to ignore me.

**Comment by camsaul** [comment]
Hi @MrMauricioLeite, we don't have any nightly builds at the moment but you can clone the git repo and run Metabase locally. See [the developers' guide](http://www.metabase.com/docs/v0.15.1/developers-guide.html) for more details.

**Comment by tlrobinson** [comment]
We actually do Docker builds for master, but it's been broken for awhile https://hub.docker.com/r/metabase/metabase-head/

**Comment by MrMauricioLeite** [comment]
Thanks @tlrobinson and @camsaul I'll take a look at the docker builds. has I'm on a windows machine I'll have trouble building metabase locally. But I'll try that too.
