### ISSUE TITLE
Show better warnings when unsuitable chart types are selected

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2183]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is OS X.
*  I'm running Metabase on AWS.
*  My database is H2 (Sample Dataset).
*  My Metabase version is 0.16.0-SNAPSHOT (on staging).

I asked a new question, then switched the visualization type to Line. The line was invisible (maybe this shouldn't have been a line chart?) but if I moved the mouse around at random if I got close enough to an invisible dot it would appear. It looks look the dates might be getting parsed incorrectly again because they were all hovering around December 31st, 1969. These dates come back as timestamps so I'm guessing maybe code is parsing them as numbers and treating them as UNIX timestamps...

When I save the card, it immediately switches back to Table visualization. The card in question [is here](https://staging.metabase.com/card/86). I'm also seeing the following error pop up in the browser console:

```javascript
Unhandled promise rejection TypeError: t.isMounted is not a function(…)
```

**Comment by tlrobinson** [comment]
This card is a raw data query. What would you expect a line chart to show?

That said, we could definitely be doing better validation / errors.

I'm also getting a different error:

```
GuiQueryEditor.jsx:273Uncaught TypeError: Cannot read property 'breakout' of undefined
```

**Comment by agilliland** [comment]
Yeah, it doesn't sound like this is actually a Bug.  There has never been an expectation that selecting a line chart when the query was raw data would produce the desired result.

**Comment by camsaul** [comment]
It picked `timeseries` and `id` from the results as the axes, which seemed reasonable. 

Either way if line charts aren't supposed to work with raw data queries we should communicate this somehow, maybe by graying out the option like we do for the other visualization types when they're inappropriate? I can imagine it giving users the wrong impression, thinking Metabase broke when they chose a different visualization (that there was no way to know they weren't supposed to select).

That aside, visualization types not saving is still an issue.

**Comment by tlrobinson** [comment]
FYI this is due to this bit of code (which is only run when you run a query) metabase/metabase/blob/master/frontend/src/card/card.controllers.js#L500-L507
