### ISSUE TITLE
Can we have several variables of type "Field filter" with the same name?

### ISSUE THREAD

**Issue by guillaumemillot** [metabase/metabase#21849]
Hey team!

It seems I can't have several variables of type "Field filter" with the same name.

Say I'm joining 2 tables A and B. Each table has a field "name", and I'd like to define 2 variables based on these 2 fields having the same name. Is that possible?

Looking at your docs, it seems it's not, or I would have to do the following, which obviously doesn't work:

select * 
from table_A join table_B on A.id = B.a_id
where {{name}} and {{name}}

Can you please help?

Thanks a lot.

**Comment by flamber** [comment]
Hi @guillaumemillot 
How is this supposed to function? You connect the Field Filter to a specific table.column reference in the sidebar.
I'm guessing you want to be able to have a single filter widget with a dropdown with the values from two different table, which is currently not possible.
Closing in favor of #5245/#6820

**Comment by guillaumemillot** [comment]
Not at all.

I have the following query joining 2 tables:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/10330584/164445978-bed8a55d-6576-4a43-a8dc-64063c53a153.png">

`name` is a field in each table.

I just want to have 2 filters, one on `name` of the first table, the other on `name` of the second table.

**Comment by guillaumemillot** [comment]
Arg, I'm gonna create a new issue, as it can't be reopened :)
