### ISSUE TITLE
MariaDB "POINT" type incorrectly interpreted and converted to a hex code. Field type change has no effect

### ISSUE THREAD

**Issue by gitnik** [metabase/metabase#21844]
**Describe the bug**
When you have a field type `POINT` in your MariaDB, which is connected to Metabase, and you try to read that field, Metabase shows it as a hex code (`0x00000000`). A change in field type in the Metabase Admin has no effect on this. Even after rescanning the field and discarding cached field values.

**To Reproduce**
1. Have a field type `POINT` in your MariaDB database
1. Fill it with some data (e.g. `POINT(-81.515754 27.664827)`)
1. Observe Metabase showing `0x00000000` 
1. Try to change the Field Type in Metabase to something that resembles a string (e.g. category, description, title)
1. Observe no change to the output. Metabase still shows `0x00000000`

**Expected behavior**
I would expect Metabase to interpret the `POINT` type as a `POINT` type and show it accordingly. At the very least, it should just be treated as a string.

**Screenshots**
MariaDB type:
<img width="204" alt="Screenshot 2022-04-21 at 09 36 50" src="https://user-images.githubusercontent.com/996623/164403994-6ae68097-54a5-4825-82e4-6a5450155a1f.png">

MariaDB data:
<img width="215" alt="Screenshot 2022-04-21 at 09 36 58" src="https://user-images.githubusercontent.com/996623/164404043-c3d9529c-b0d4-4413-adeb-1e317a1c3956.png">

Metabase type (Also tried many others):
<img width="170" alt="Screenshot 2022-04-21 at 09 37 13" src="https://user-images.githubusercontent.com/996623/164404080-d6ff3629-eddf-434b-82dc-6296b1d5528f.png">

Metabase data:
<img width="116" alt="Screenshot 2022-04-21 at 09 37 04" src="https://user-images.githubusercontent.com/996623/164404131-36a84d29-8c11-44ef-b4b6-fe72e14bb059.png">

**Troubleshooting information**
- Your databases: MariaDB 10.2
- Metabase version: 0.42.4
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Blocking some users from using Metabase

**Comment by flamber** [comment]
Metabase currently don't support geodata types. Related to #2327

**Comment by gitnik** [comment]
I saw that ticket and that makes sense to me, but shouldn't setting the field type to e.g. Category at least show the original value?

**Comment by flamber** [comment]
@gitnik No, since the type isn't even recognized by Metabase, so it would need conversion to even be shown to humans: https://github.com/metabase/metabase/blob/master/src/metabase/driver/mysql.clj#L274

**Comment by gitnik** [comment]
Sorry that's what I meant. Until the "proper" solution (parsing it as an actual geo-type) is implemented, wouldn't it make sense to at least treat it as a `type/Text` in the meantime.

**Comment by flamber** [comment]
@gitnik It would still require conversion, since the data is stored as a binary in MariaDB if I remember correctly.
Anyways, Metabase does not support what you are looking for and you would have to do manual conversion in a View or a Metabase Model using `ST_X(col_point)` and `ST_Y(col_point)` to convert it into separate columns just like #2327

**Comment by gitnik** [comment]
Understood. Thanks a lot for the swift help. I'll close this in favor of the older issue.
