### ISSUE TITLE
Can we have several variables of type "Field filter" with the same name?

### ISSUE THREAD

**Issue by guillaumemillot** [metabase/metabase#21850]
I have the following query joining 2 tables:
```
select *
from workspaces
left join "plans" on workspaces.plan_id = "plans".id 
```
`name` is a field in each table. I'm trying to use "field filter" variables.

I'd like to have 2 filters, one on `name` in the first table, the other on `name` in the second table, so trying to do this if I follow your docs:
```
select *
from workspaces
left join "plans" on workspaces.plan_id = "plans".id 
where {{name}} and {{name}};
```

However, I can only see one "field filter" variable in the right pane.

Can I have two field filter variables with the same name?

**Comment by flamber** [comment]
This cannot be done #21849. The Field Filter variables are tied to a column in each. Closing as WON'T FIX
Use `where {{workspace_name}} and {{plan_name}};`
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
