### ISSUE TITLE
Auto-refresh once set it only works for 30 seconds intervals

### ISSUE THREAD

**Issue by sergiyova** [metabase/metabase#21864]
**Describe the bug**

We are using the self-hosted free version of Metabase (metabase/metabase:v0.42.4). Since the last update, we realized we had huge load of requests to our "replica PostgreSQL" database. We could not think of any reason why suddenly the DB had so much stress. 

After some research, one of our analysts reported that one of his dashboards, with auto-refresh, was refreshing every 30s instead of 60min as he initially set it up. He also commented he could not turn off the auto-refresh.

After testing it out, I could confirm that once you set auto-refresh in a dashboard:

- Independently the time, it will always refresh every 30s
- You cannot turn auto-refresh off, once it was already on
- The huge load in the Db was coming from this dashboard with auto-refresh being opened in the browser.

**Logs**

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.4.170+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**To Reproduce**
1. Go to your metabase instance
2. Create a dashboard with different questions
3. Set auto-refresh every hour

**Expected behavior**

You should be able to turn off the auto-refresh, and if you set a time of 60min it should not refresh every 30s.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Metabase version: (e.g., 0.19.3)
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
This is a really severe issue as now we are not able to use all dashboards with auto-refresh, which our business analysis relies on. The only solution is to re-do all the dashboards we made for the last 4 years, which is neither a viable solution.

**Comment by flamber** [comment]
Hi @sergiyova 

I cannot reproduce. Which version did you upgrade from?

Auto-refresh is not turned on by default on dashboards, and the setting is not stored, so it require manually activating it or creating URLs with the value in seconds `...#refresh=3600`
So either you have a browser extension doing something it shouldn't or a reverse-proxy misbehaving.

There is a known bug in the auto-refresh, which can cause load on the database #12578, but that's not what you are describing.

**Comment by flamber** [comment]
@sergiyova You don't have to upgrade one-by-one - the migration script takes care of the version jumps in almost all cases.

I cannot reproduce - and I'm sure that we would have seen several other reports about this if this was widespread.
Ignore that type error - that's unrelated technical debt.

https://user-images.githubusercontent.com/1447303/164491706-4f7b72ac-e206-43f7-8140-b53725522181.mp4
