### ISSUE TITLE
Cannot bring up Question Edit Menu on Dashboard (OS X Client)

### ISSUE THREAD

**Issue by rodjager** [metabase/metabase#2186]
If this is a bug report, please fill in the blanks:
-  I am using the Safari browser.
-  My computer's OS is OS X El Capitan (10.11.3).
-  I'm running Metabase via OS X app installed from dmg. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is mySQL.
-  My Metabase version is 0.15.1.

I am running the OS X Client (0.15.1) in on El Capitan (10.11.1).

When editing a dashboard, the Edit Menu on a Question allows me to click on it but nothing happens.

For reference I am also experiencing an issue with the option to delete Questions from Dashboards not working either.
[Metabase Console Log.log.zip](https://github.com/metabase/metabase/files/179118/Metabase.Console.Log.log.zip)

**Comment by salsakran** [comment]
does the log end right after you try to hit "edit" or is it midway?

**Comment by rodjager** [comment]
The log ends before I click Edit. When I click on Edit nothing else appears to go into the log (not against Metabase anyway) so there is nothing else to show.

**Comment by camsaul** [comment]
@rodjager are you still seeing this issue?

**Comment by camsaul** [comment]
@rodjager ?

**Comment by rodjager** [comment]
Thanks for the follow up @camsaul.

I upgraded within the app to the latest release and now I am getting an issue with the app constantly crashing.  I tried cleaning up the profile files as per the Metabase website but this has not corrected the error for me.

At this stage I can't give you an update as to whether this issue has been resolved.

**Comment by camsaul** [comment]
@rodjager try the latest Metabase Mac App, we fixed a lot of the issues where it crashed on launch
