### ISSUE TITLE
Empty Schema and NullPointerException

### ISSUE THREAD

**Issue by pschupp01** [metabase/metabase#2188]
*  My computer's OS is Mac.
*  I'm running Metabase  locally from the JAR / locally with the Mac App / on Heroku 
*  My database is MongoDB, hosted at mongolab
*  My Metabase version is recent as downloaded yesterday

Hi,
I'm trying to set up Metabase to query my MongoDB.
The database seems linked as it appears un /admin/databases.
The tables seems to be well retrieved as they appear in /admin/datamodel/...

But no schema is found for every table. There is no columns displayed.

My database is hosted at mongolab.
DB size is around 22GB.
Mongo version is 3.0.10
It is highly possible than all the rows of the tables does not follow the exact same schema.
And this is the logs when i use the console app and try to sync my database
```

03-17 19:59:06 DEBUG metabase.middleware :: POST /api/database/2/sync 200 (5 ms)
03-17 19:59:06 DEBUG db.internal :: DB CALL: User [:id :email :date_joined :first_name :last_name :last_login :is_superuser :is_qbnewb :is_active :is_staff] (where (limit (select* ENTITY24489) 1) {:id current-user-id})
03-17 19:59:06 DEBUG db.internal :: DB CALL: Database * (where (limit (select* ENTITY29138) 1) {:id (events/object->model-id topic object)})
03-17 19:59:06 DEBUG mongo.util :: << OPENED NEW MONGODB CONNECTION >>
03-17 19:59:06 INFO driver.sync :: Syncing MongoDB database 'Preprod'...
03-17 19:59:16 ERROR events.sync-database :: Error syncing Database: 2 #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by agilliland** [comment]
Metabase is currently supporting Mongo version 3.2 and above.  I'm guessing that's what's causing the NullPointerException you're seeing.

**Comment by camsaul** [comment]
@agilliland [We support version 3.0 and above](http://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html) so that's probably not the issue

**Comment by agilliland** [comment]
@pschupp01 we'll need to find a way to get some more information about what's going on in order to reproduce this reliably.  any chance you can share more details about what's actually inside your mongo collections?

does that NullPointer error only occur once?  or does it repeat?

**Comment by pschupp01** [comment]
Hello,
I’ve made some tests to get more infos.
I restored one table after another, syncing with metabase for each table added.
One particular table seems to throw an error while syncing.
Here’s a more explicit stacktrace than the one posted above.

`03-25 10:03:47 ERROR events.sync-database :: Error syncing Database: 2 #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [java.util.regex.Matcher getTextLength Matcher.java 1283]}]
 :trace
 [[java.util.regex.Matcher getTextLength Matcher.java 1283]
  [java.util.regex.Matcher reset Matcher.java 309]
  [java.util.regex.Matcher <init> Matcher.java 229]
  [java.util.regex.Pattern matcher Pattern.java 1093]
  [clojure.core$re_matcher invokeStatic core.clj 4674]
  [clojure.core$re_matches invokeStatic core.clj 4704]
  [clojure.core$re_matches invoke core.clj 4704]
  [metabase.util$is_url_QMARK_ invokeStatic util.clj 335]
  [metabase.util$is_url_QMARK_ invoke util.clj 327]
  [metabase.driver.mongo$val__GT_special_type invokeStatic mongo.clj 68]
  [metabase.driver.mongo$val__GT_special_type invoke mongo.clj 64]
  [metabase.driver.mongo$update_field_attrs$fn__28689 invoke mongo.clj 94]
  [clojure.core$update invokeStatic core.clj 5960]
  [clojure.core$update invoke core.clj 5952]
  [metabase.driver.mongo$update_field_attrs invokeStatic mongo.clj 93]
  [metabase.driver.mongo$update_field_attrs invoke mongo.clj 84]
  [clojure.core$partial$fn__4759 invoke core.clj 2515]
  [clojure.core$update invokeStatic core.clj 5960]
  [clojure.core$update invoke core.clj 5952]
  [metabase.driver.mongo$describe_table$f__28170__auto____28732$fn__28733 invoke mongo.clj 135]
  [clojure.core.protocols$fn__6755 invokeStatic protocols.clj 167]
  [clojure.core.protocols$fn__6755 invoke protocols.clj 124]
  [clojure.core.protocols$fn__6710$G__6705__6719 invoke protocols.clj 19]
  [clojure.core.protocols$seq_reduce invokeStatic protocols.clj 31]
  [clojure.core.protocols$fn__6738 invokeStatic protocols.clj 75]
  [clojure.core.protocols$fn__6738 invoke protocols.clj 75]
  [clojure.core.protocols$fn__6684$G__6679__6697 invoke protocols.clj 13]
  [clojure.core$reduce invokeStatic core.clj 6545]
  [clojure.core$reduce invoke core.clj 6527]
  [metabase.driver.mongo$describe_table$f__28170__auto____28732 invoke mongo.clj 129]
  [metabase.driver.mongo$describe_table invokeStatic mongo.clj 125]
  [metabase.driver.mongo$describe_table invoke mongo.clj 124]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invokeStatic core.clj 646]
  [clojure.core$apply invoke core.clj 641]
  [clojure.core$partial$fn__4759 invoke core.clj 2515]
  [clojure.core$comp$fn__4727 invoke core.clj 2460]
  [clojure.core$comp$fn__4727 invoke core.clj 2461]
  [metabase.driver$fn__18453$G__18304__18460 invoke driver.clj 82]
  [metabase.driver.sync$sync_database_active_table_BANG_ invokeStatic sync.clj 163]
  [metabase.driver.sync$sync_database_active_table_BANG_ doInvoke sync.clj 158]
  [clojure.lang.RestFn invoke RestFn.java 464]
  [metabase.driver.sync$sync_database_active_tables_BANG_ invokeStatic sync.clj 206]
  [metabase.driver.sync$sync_database_active_tables_BANG_ doInvoke sync.clj 197]
  [clojure.lang.RestFn invoke RestFn.java 464]
  [metabase.driver.sync$sync_database_with_tracking_BANG_ invokeStatic sync.clj 265]
  [metabase.driver.sync$sync_database_with_tracking_BANG_ invoke sync.clj 249]
  [clojure.core$partial$fn__4763 invoke core.clj 2528]
  [metabase.driver.mongo$sync_in_context$f__28170__auto____28664 invoke mongo.clj 62]
  [metabase.driver.mongo.util$_with_mongo_connection invokeStatic util.clj 68]
  [metabase.driver.mongo.util$_with_mongo_connection invoke util.clj 43]
  [metabase.driver.mongo$sync_in_context invokeStatic mongo.clj 61]
  [metabase.driver.mongo$sync_in_context invoke mongo.clj 60]
  [metabase.driver$fn__18494$G__18298__18503 invoke driver.clj 82]
  [metabase.driver.sync$sync_database_BANG_ invokeStatic sync.clj 60]
  [metabase.driver.sync$sync_database_BANG_ doInvoke sync.clj 49]
  [clojure.lang.RestFn invoke RestFn.java 464]
  [metabase.driver$sync_database_BANG_ invokeStatic driver.clj 386]
  [metabase.driver$sync_database_BANG_ doInvoke driver.clj 379]
  [clojure.lang.RestFn invoke RestFn.java 410]
  [metabase.events.sync_database$process_sync_database_event$fn__29146 invoke sync_database.clj 32]
  [clojure.core$binding_conveyor_fn$fn__4676 invoke core.clj 1938]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}`

It happens once while syncing the table, and totally interrupt the syncing process.
I hope it will help.

**Comment by agilliland** [comment]
Awesome.  That's perfect.  I can see where the exception is being thrown from now and have a fix for that.
