### ISSUE TITLE
Cleanup card error handling (query builder, dashboards, pulses)

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2190]
Our frontend query error handling code has become inconsistent and fragmented. We should try to consolidate it and clean it up.

Query Builder:

![screenshot 2016-03-18 11 43 22](https://cloud.githubusercontent.com/assets/18193/13888603/7d230144-ecff-11e5-9751-575b0e09a05c.png)

Dashboard:

![screenshot 2016-03-18 11 44 36](https://cloud.githubusercontent.com/assets/18193/13888601/7d224b5a-ecff-11e5-925f-2a36a58073c8.png)

Pulses:

![screenshot 2016-03-18 11 46 17](https://cloud.githubusercontent.com/assets/18193/13888602/7d22be46-ecff-11e5-8ea4-8f33e50c121f.png)

Partially completed matrix of what we currently show for each error type:

| Error | Query Builder | Dashboard | Pulse |
| --- | --- | --- | --- |
| No results | "No results!" | varied depending on chart type | "No results" |
| Query took too long | "Your question took too long" | "Card took longer than 60 seconds to load." | no timeouts? |
| Invalid query (gui) | "There was a problem with your question" | RAW ERROR |  |
| Invalid query (native) | RAW ERROR | RAW ERROR | "No results" |
| Server error | "We're experiencing server issues" |  |  |
| Unsuitable chart | various | not possible? |  |
| Unknown "display" type |  |  |  |
| Card render error |  |  |  |

Where the erorr handling logic is currently implemented:
- Dashboards: https://github.com/metabase/metabase/blob/master/frontend/src/dashboard/components/DashCard.jsx#L67-L83
- Query Builder: https://github.com/metabase/metabase/blob/master/frontend/src/query_builder/QueryVisualization.jsx#L238-L322
- Unsuitable charts: https://github.com/metabase/metabase/blob/master/frontend/src/visualizations/lib/errors.js
- Card render error: https://github.com/metabase/metabase/blob/master/frontend/src/visualizations/components/Visualization.jsx#L79-L95
- Pulses: https://github.com/metabase/metabase/blob/master/src/metabase/pulse.clj#L417-L433

Related:
- #625: Provide error line number information for Native SQL queries
- #1121: Provide a clear error message on QB for case when database connection failed
- #2036: Crappy dashboard card error message
- #2148: Pulse cards with errors should retain titles 
- #2183: Show better warnings when unsuitable chart types are selected

**Comment by flamber** [comment]
Closing in favor of #1121 - a lot has changed, so most of this is outdated.
