### ISSUE TITLE
Cannot select unix timestamp as type of field

### ISSUE THREAD

**Issue by gseva** [metabase/metabase#2191]
I have a sqlite database with some columns with unix timestamp values (in seconds).
In the new version of metabase (0.15.1) i cannot chose them as unix timestamp field anymore. This option just does not appear.
I noticed that if i select "Number" as type of field, and then open the dropdown - unix timpestamps appear as field types (seconds and microseconds), but when i select any of them, an error message appear: "Error: Invalid Request."

My metabase is running with docker.

**Comment by camsaul** [comment]
@gseva does anything appear in the server logs when that happens?

**Comment by gseva** [comment]
@camsaul 
These are the logs when i enter the Data Model page for my table:

```
metabase | 03-18 19:41:24 DEBUG metabase.middleware :: GET /api/session/properties 200 (1 ms)
metabase | 03-18 19:41:24 DEBUG db.internal :: DB CALL: User [:id :email :date_joined :first_name :last_name :last_login :is_superuser :is_qbnewb :is_active :is_staff] (where (limit (select* ENTITY24489) 1) {:id current-user-id})
metabase | 03-18 19:41:24 DEBUG metabase.middleware :: GET /api/user/current 200 (2 ms)
metabase | 03-18 19:41:24 DEBUG metabase.middleware :: GET /api/database 200 (1 ms)
metabase | 03-18 19:41:24 DEBUG db.internal :: DB CALL: Database * (k/order (select* ENTITY18650) :name)
metabase | 03-18 19:41:24 DEBUG db.internal :: DB CALL: User [:id :email :date_joined :first_name :last_name :last_login :is_superuser :is_qbnewb :is_active :is_staff] (where (limit (select* ENTITY24489) 1) {:id current-user-id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: Dashboard * (k/where (select* ENTITY16550) (or {:creator_id *current-user-id*} {:public_perms [> common/perms-none]}))
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: User [:id :email :date_joined :first_name :last_name :last_login :is_superuser :is_qbnewb] (where (select* ENTITY13355) {:id [in ids]})
metabase | 03-18 19:41:25 DEBUG metabase.middleware :: GET /api/dashboard 200 (3 ms)
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: Table [:id] (where (select* ENTITY18777) {:db_id id, :active true})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: Field * (where (select* ENTITY18787) {:table_id [in table_ids], :special_type "id"})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: Table * (where (select* ENTITY13355) {:id [in ids]})
metabase | 03-18 19:41:25 DEBUG metabase.middleware :: GET /api/database/4/idfields 200 (4 ms)
metabase | 03-18 19:41:25 DEBUG models.interface :: DB CALL: Database 4
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: Table * (where (k/order (select* ENTITY15450) :display_name :ASC) {:db_id id, :active true})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: Field * (where (k/order (k/order (select* ENTITY16135) :position :ASC) :name :ASC) {:table_id id, :active true})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: Segment * (where (k/order (select* ENTITY15867) :name :ASC) {:table_id table-id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: Metric * (where (k/order (select* ENTITY15501) :name :ASC) {:table_id table-id})
metabase | 03-18 19:41:25 DEBUG metabase.middleware :: GET /api/database/4/metadata 200 (14 ms)
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: User [:id :email :date_joined :first_name :last_name :last_login :is_superuser :is_qbnewb :is_active :is_staff] (where (limit (select* ENTITY24489) 1) {:id current-user-id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
metabase | 03-18 19:41:25 DEBUG db.internal :: DB CALL: FieldValues [:field_id :values] (where (select* ENTITY16043) {:field_id id})
```

Here are the logs when i have a field as Number and i select it to be a Unix Timestamp:

```
metabase | 03-18 19:44:55 DEBUG models.interface :: DB CALL: Field 131
metabase | 03-18 19:44:55 DEBUG metabase.middleware :: PUT /api/field/131 400 (3 ms)
metabase | "Invalid Request."
metabase |
metabase | 03-18 19:44:55 DEBUG db.internal :: DB CALL: User [:id :email :date_joined :first_name :last_name :last_login :is_superuser :is_qbnewb :is_active :is_staff] (where (limit (select* ENTITY24489) 1) {:id current-user-id})
```

**Comment by agilliland** [comment]
My guess is that the update is failing here ... https://github.com/metabase/metabase/blob/master/src/metabase/api/field.clj#L45

What's the column type in the sqllite database?

**Comment by gseva** [comment]
@agilliland 
I tried with different types with the same result: Integer, Datetime and without type.

**Comment by agilliland** [comment]
I'm not sure I follow.  The special-type for "UNIX Timestamp" is specifically meant for allowing the conversion of BigInteger values such as `1458578036940` into a normal database DateTime type so that all the normal date and time operations can be used.  So the only situation where this currently makes sense is if the original column type on the database table is a BigInteger or similar.

So I'm not sure what type you were changing, but I am talking about the actual column type in the database.

**Comment by gseva** [comment]
@agilliland 
What i am doing is a preprocessing to my datetimes to convert them to a Unix timestamp in seconds and save them in sqlite database. In previous versions of Metabase (<= 0.14.1) they had no type in sqlite, that is i didn't specify the type for these columns explicitly. This approach worked fine for me - i changed the column's metadata  from Metabase admin panel to be treated as Unix timestamp and the things worked out.

With the update i found the behaviour described in this issue, and one of the things i tried was changing the way i generate the sqlite database, and particularly the type of the columns with unix timestamp data. I tried to create them as datetime (which seems to be wrong) and integer (which seems to be the right column type for unix timestamps, due to the [integer affinity](http://stackoverflow.com/questions/2583783/sqlite-column-format-for-unix-timestamp-integer-types)), but the issue persisted - i still could not select the "Unix timestamp" as field type.

Now i did a rollback to 0.14.1, and i'm saving the timestamps as integers in sqlite and it's working fine - i can select these columns to be unix timestamps.

**Comment by agilliland** [comment]
I tried out a few things here and so far everything is working as expected for me, so I'm guessing that the issue has something to do with the structure of your SQLite database.  In specific, my guess would be that the column type for column you are trying to use as a unix timestamp in Metabase is not actually a numerical type according to Metabase.

To add a little code to the discussion, we use this as a mapping of SQLite column types -> Metabase types ...

```
(def ^:private ^:const pattern->type
  [[#"BIGINT"   :BigIntegerField]
   [#"BIG INT"  :BigIntegerField]
   [#"INT"      :IntegerField]
   [#"CHAR"     :TextField]
   [#"TEXT"     :TextField]
   [#"CLOB"     :TextField]
   [#"BLOB"     :UnknownField]
   [#"REAL"     :FloatField]
   [#"DOUB"     :FloatField]
   [#"FLOA"     :FloatField]
   [#"NUMERIC"  :FloatField]
   [#"DECIMAL"  :DecimalField]
   [#"BOOLEAN"  :BooleanField]
   [#"DATETIME" :DateTimeField]
   [#"DATE"     :DateField]])
```

then when building the UI we check that the column is of an appropriate type using `base: ["IntegerField", "DecimalField", "FloatField", "BigIntegerField"]` so that users are only allowed to assign the unix timestamp type on columns that are actually numbers because that's the way the feature is meant to work.

for Metabase to properly use the unix timestamp conversion the original column type must be numeric.  so my recommendation would be to look at the SQLite database and make sure the columns you are trying to use are some form of numeric column type.

**Comment by gseva** [comment]
@agilliland Thanks for clearing this

I tried running a metabase locally with sqlite with integer columns and could select them correctly as timestamps. Then i updated my working metabase back to the new version, and it worked too (with sqlite integer columns), so seems like i was doing something wrong. I'll try to figure out what it was, but it seems like i messed up with column types in sqlite. I'm sorry for bothering you with this issue.

Aside from that, in case of sqlite maybe it would be better to not to restrict metabase field types based on column types, as any column can store value of any type, excepting the primary keys.

**Comment by agilliland** [comment]
Cool.  Glad you were able to get that sorted out.

I'll make a note to look into our handling of column types on SQLite at some point and see if there is an opportunity to make things a bit easier.
