### ISSUE TITLE
Cannot create another filter value if it starts with the same value as an existing value

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21915]
**Describe the bug**
When adding different filter values, where second value starts with the same value as the first, then it removes the first value.
Very similar to #16621, but now it only happens to numeric inputs

Workaround: Input the values in reverse order. Or copy-paste the values from somewhere else.

**To Reproduce**
1. Question > Sample > Orders
2. Filter ID - try to input `1` `10` `100` (use comma between each input) - it will remove the first value

https://user-images.githubusercontent.com/1447303/164682336-9b95171b-7b57-478c-af87-050f17d354dc.mp4

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.43.0-rc1

**Comment by npfitz** [comment]
This appears to be related to the the `updateOnInputChange` property in `TokenField.jsx`. I tried removing that flag where we set it in `FieldValuesWidget.jsx` but that caused multiple tests to fail
