### ISSUE TITLE
Filtering "Exclude" shows wrong weekday

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21979]
**Describe the bug**
Filtering "Exclude" shows wrong weekend - though, the actual query is correct - took me a while to understand what was going on.

**To Reproduce**
1. Question > Sample > Products
2. Filter CreatedAt > Exclude > "Days of the week" > uncheck Monday - Add filter
3. Incorrectly shows the wrong day - it is filtering correctly in the query
![image](https://user-images.githubusercontent.com/1447303/164937736-110182f0-fb15-4f48-9f59-42dd1e1df931.png)
4. Edit the filter and select Monday again, now it's not possible the save the filter changes (Update filter)
![image](https://user-images.githubusercontent.com/1447303/164938705-caf62de7-fa2d-45e5-8ba5-7f4658351590.png)

**Expected behavior**
While I'm fine with the order of the weekdays, then in a perfect world, it should order depending on Admin > Settings > Localization > First day of the week

**Information about your Metabase Installation:**
0.43.0-rc1 and master `b9cedcc`

**Comment by flamber** [comment]
@akiselev I would expect to be able to deselect and select something again.
If it should remove the filter or now, perhaps, I'm not sure.

**Comment by akiselev** [comment]
@flamber Only `["!=", ["field", ...], null]` works without removing the filter altogether but I'm not sure about the semantics. Does setting 'temporal-unit' along with `!= null` result in a `field is not null`?

**Comment by akiselev** [comment]
@flamber is `extract(day_of_week FROM my_field) IS NOT NULL` acceptable semantics here when nothing is excluded? Otherwise I think we'll have to remove the filter

**Comment by flamber** [comment]
@akiselev If it makes more sense to remove the filter, then do that. You should ask someone who has been part of the team working on this feature, since I don't know what the intention was, but perhaps it's somewhere in Notion.
