### ISSUE TITLE
Max/Min functions on strings incorrectly inferred as numeric

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21973]
**Describe the bug**
When using Max/Min on string-based columns, then the frontend infers as numeric field, which limits filter options.
Possibly applies to other functions, didn't go through everything.

**To Reproduce**
1. Question > Sample > People
2. Summarize Maximum of ID, Name, Latitude and CreatedAt, grouped by Source
![image](https://user-images.githubusercontent.com/1447303/164892690-7568dd65-5e63-4343-a0cc-b84d1cdcb330.png)
3. Filtering by "Max of Name" is not possible, because it's inferred as a number by the frontend even though dataset returns as type/Text.
![image](https://user-images.githubusercontent.com/1447303/164892768-088bdbcf-b9de-4ae8-ae56-4b132cbf8893.png)

**Possible workaround**
- Add a Custom Column `trim([Max of Name])` after the aggregation
![image](https://user-images.githubusercontent.com/1447303/164892828-da0f100e-8e36-442a-88ca-3dd0eae2f842.png)
![image](https://user-images.githubusercontent.com/1447303/164892919-d943a473-615e-4c1f-a762-e898379d8b19.png)
- Or create a SQL question, which can then be used as a Model or Saved Question as the base for other questions, which adds filtering.

**Expected behavior**
Generally use the inferred type from dataset

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.43.0-rc1

**Additional context**
History #18207 and #4482

**Comment by ariya** [comment]
The problem already appears while still in the notebook mode, i.e. trying to filter on `Max of Name`:

![image](https://user-images.githubusercontent.com/7288/164999869-1cc74cba-9850-43a3-95cf-0c2226d18bba.png)
