### ISSUE TITLE
Large databases can be very slow to view in Data Model

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21985]
**Describe the bug**
When viewing large databases (many tables and fields) in Data Model, then it can take a very long time to load.
It can even take more than one minute to fetch the request, which might fail depending on reverse-proxy settings, but this can mean that it's almost impossible to edit the Data Model.

This is probably just a FE issue, since it could request data similar to how it's done in the data selector in QB.
But if we need to keep `/api/database/:id/metadata` as is, then the BE needs to optimize the appDB queries to avoid making a query for each field, which is very inefficient on large databases.

**To Reproduce**
1. Connect a large database like Horror Show
2. Go to Admin > Data Model > select large database
3. After it has loaded the list of (schemas and) tables, then select a table, which will cause another request

https://user-images.githubusercontent.com/1447303/164973941-815d043d-0050-41d0-ac70-98b9b2e2e4e5.mp4

**Expected behavior**
Similar quick like QB has become since 39/40/41.

**Information about your Metabase Installation:**
Tested 0.39.5 thru 0.43.0-rc1 and master `485b83e`

**Additional context**
Historically related to #11806

**Comment by florian-ernst-alan** [comment]
This is especially annoying when your Metabase instance is behind Cloudflare, who cuts all requests after 100s. We can't access our Data Models tab anymore because of this, and are wondering why there's not a more optimal process available.

How could we at least cache those results, or compute them async?

**Comment by ranquild** [comment]
Closed by https://github.com/metabase/metabase/issues/30190
