### ISSUE TITLE
Embedding/Public sharing of questions does not show download button in the footer

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21993]
**Describe the bug**
Embedding/Public sharing of questions does not show download button in the footer.
Regression since 0.43.0-rc1

**To Reproduce**
1. Native > Sample > `select 0` - save question
2. Click Sharing (:arrow_upper_right:)
3. Go to Public Sharing or Embedding
![image](https://user-images.githubusercontent.com/1447303/165072162-6caa68cb-facf-442f-be36-da4364059d54.png)
![image](https://user-images.githubusercontent.com/1447303/165072590-8b2b4609-e56c-4eef-9ba5-2996c686780e.png)

**Expected behavior**
0.42.4
![image](https://user-images.githubusercontent.com/1447303/165071771-9a0f99eb-23c6-4263-8051-052a654e16e7.png)
![image](https://user-images.githubusercontent.com/1447303/165072674-18dd01a1-5842-4473-b071-7993e9237c03.png)

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.43.0-rc1 and master `485b83e`

**Comment by alxnddr** [comment]
@flamber this was intentional https://metaboat.slack.com/archives/C0312QQCHLP/p1645816847443499?thread_ts=1645809456.524589&cid=C0312QQCHLP

**Comment by flamber** [comment]
Someone needs to comment with details here. This has to be highest note in our release notes. I know a lot who won't upgrade.

**Comment by alxnddr** [comment]
While working on the new download permission, we intentionally removed the ability to download data from publicly shared questions for security concerns. Please let us know if it was important for you.
