### ISSUE TITLE
Dashboard filter

### ISSUE THREAD

**Issue by gincor** [metabase/metabase#2203]
Hi, 

we have a few dashboards in multiple versions to enable quick analysis of the same KPIs filtered for different dimensions. Think Logins per hour on Weekday 1 vs Weekday 2 etc... or Users / Transactions / Volume in region 1, 2, 3 etc. 

We could reduce the amount of dashboards needed and the time it takes to create them a lot if there was a possibility to use filters for the whole dashboard.

**Comment by MrMauricioLeite** [comment]
Related to #1543.

**Comment by gincor** [comment]
thanks for pointing that out, didn't find that issue before. Closing this one

**Comment by mazameli** [comment]
@gincor, yeah, as Mauricio noted, we have a discussion about this feature going on in #1543, and I'm actively working on designs for this feature this week as my top priority.
