### ISSUE TITLE
Remove card `display` property validation on the server

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2205]
It's now relatively easy to add new visualization types on the frontend, but the backend has a [hard-coded list of allowed `display` values](https://github.com/metabase/metabase/blob/master/src/metabase/models/card.clj#L11-L22). We should remove [that check](https://github.com/metabase/metabase/blob/master/src/metabase/api/card.clj#L22), but ensure we show an appropriate error if the user tries to load a card with an unknown `display` type.

**Comment by camsaul** [comment]
Or maybe just update the list on the backend to include new options when they're added the frontend?

**Comment by agilliland** [comment]
In this case I'm in agreement with Tom that there is no reason for there to be any fixed set of display options on cards which are enforced or managed on the backend.

**Comment by camsaul** [comment]
They're enforced on the backend to make sure bugs aren't introduced and that we don't accidentally save people's cards with an invalid display type. Same reason we have any kind of database constraints or invariants.

**Comment by agilliland** [comment]
The application is now designed to handle a more extensible set of visualizations and since the overwhelming majority of the visualization related code is handled by the frontend I think we should follow through on Tom's suggestion and remove any backend constraints.

**Comment by camsaul** [comment]
It might be the case that it's not useful directly on the backend but it's still stored in the database... taking out data validation that's already there and making Metabase less robust just for convenience sounds like a bad idea.
