### ISSUE TITLE
Date Move Forward for One day to the Given Date in Metabase BIRT Tool Report

### ISSUE THREAD

**Issue by dbaarchitect** [metabase/metabase#22056]
**Describe the bug**
I am facing an issue while fetching report at Metabase BIRT tool. When I put filter against data like 4/7/2022 - 4/11/2022 using between operator, It shows me result from 4/8/2022 - 4/12/2022. I verified to fetch data using SQL query from desired database which is giving me correct results. Along with that, I also verified that DB Server & APP Server has same timezone settings mean both are running with US/Eastern time with First day of Week (Sunday).
Apart from this, I also set timezone in metabase application navigating to Admin settings to US/Eastern but it is still fetching same result set as described above.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
