### ISSUE TITLE
Textbox on dashboards are difficult move and missing options

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22061]
**Describe the bug**
Textbox on dashboards are difficult rearrange.
Regression since 0.43.

Workaround: Hover the Textbox > click Preview > now it's possible to move the Textbox

**To Reproduce**
1. Go to dashboard, edit, add a Textbox
2. Try to move the Textbox

https://user-images.githubusercontent.com/1447303/165263501-09cc419b-0824-48de-8cf9-d9dac1700ed1.mp4

**Screenshots**
Previous versions of Metabase had a larger border:
![image](https://user-images.githubusercontent.com/1447303/165263323-cdd38436-81a7-4df8-8d88-a1252b256521.png)

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.43.0-rc1 and master `7cccd06`

**Additional context**
@ukritw

**Comment by ukritw** [comment]
Possibly related, there’s no longer an option to show the pop-up to do things like: remove background color, adjust alignment, etc.

**Comment by ukritw** [comment]
Seems like we're still missing the options icon. 
Has that been moved/changed by any chance?
