### ISSUE TITLE
dashboard cards with errors should still show title w/ link

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2208]
If for some reason a card doesn't rendering properly due to a query execution error there is no title/link which allows the user to go to the QB and fix it.

<img width="900" alt="screen shot 2016-03-22 at 2 10 53 pm" src="https://cloud.githubusercontent.com/assets/1987787/13968117/14ec2c4a-f038-11e5-85bc-3602e69f284e.png">

<img width="218" alt="screen shot 2016-03-22 at 2 10 42 pm" src="https://cloud.githubusercontent.com/assets/1987787/13968119/183ce4c0-f038-11e5-9051-fdb7aa7b48ee.png">

I'm assuming the desired behavior is that the title still exists, so going to classify this as a bug.

**Comment by tlrobinson** [comment]
Related #2190
