### ISSUE TITLE
Make sure that Metabase JS/CSS isn't cached by browser

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2210]
Seen a couple reports of cases where the app was updated and the index.html page served by the metabase frontend had changed, but the user's browser was continuing to use an older version of the page until a hard page refresh was done.

**Comment by camsaul** [comment]
A normal refresh didn't do it?

**Comment by agilliland** [comment]
nope.  had to be a hard refresh.

**Comment by camsaul** [comment]
Here's the headersthat come back with `index.html`. Something must be off here

![screen shot 2016-03-22 at 3 47 04 pm](https://cloud.githubusercontent.com/assets/1455846/13970346/5fed20e8-f045-11e5-9c8b-e4511a6d98bc.png)

Also, what browser were you using?

**Comment by tlrobinson** [comment]
FWIW we don't actually know if it was the `index.html` or the js/css that was being cached, do we? In theory we have a cache busting set up for anything loaded by webpack, but it's possible it's not working.

**Comment by agilliland** [comment]
Correct.  I filed this because we saw a user run into this problem and a refresh was the solution, but we don't know the exact cause.

**Comment by agilliland** [comment]
Just a quick update that we'd had several other people report running into this issue on the latest 0.16.0 release candidate, so it's definitely happening.  Here's a screenshot of the problem in action on the QB ...

![screen shot 2016-03-23 at 2 20 31 pm](https://cloud.githubusercontent.com/assets/1987787/14001526/965b62ca-f103-11e5-9f0d-71ddf660fa68.png)

**Comment by camsaul** [comment]
I think @tlrobinson is right about the JS / CSS being the issue here. The cache-busting headers are only added to `index.html` and API calls. 

###### `app.bundle.js`
![screen shot 2016-03-23 at 2 36 31 pm](https://cloud.githubusercontent.com/assets/1455846/14001700/ad0166e0-f104-11e5-8308-4eb1eb86fd77.png)


####### relevant code:
```clojure
(defn add-security-headers
  "Add HTTP headers to tell browsers not to cache API responses."
  [handler]
  (fn [request]
    (let [response (handler request)]
      (update response :headers merge (cond
                                        (api-call? request) (api-security-headers)
                                        (index? request)    (index-page-security-headers))))))
```

**Comment by agilliland** [comment]
The cache busting for the JS/CSS should be happening due to the fact that we append a randomized hash on those urls right?

In any case, given that we've seen several folks run into this since deploying 0.16.0 can we address this somehow before the release goes out?

**Comment by tlrobinson** [comment]
@agilliland correct, JS and CSS files _should_ be aggressively cached, then "cache busted" by changing the hash in the query string when re-built. AFAIK Webpack is doing this correctly, so I'm pretty stumped why this is happening. I'll keep poking at it.

**Comment by camsaul** [comment]
I don't think the randomized hash is working correctly. I'm looking at the network inspector and when I soft reload a page it fetches `vendor.bundle.js` with the exact same hash as the last time.

**Comment by camsaul** [comment]
Why can't we just add cache-prevention headers to the JS and CSS files like normal people and skip this random hash stuff?

**Comment by tlrobinson** [comment]
Because we have like 2MB of JS/CSS that we don't want to reload every time unless it actually changes. This is a pretty common practice.

**Comment by tlrobinson** [comment]
Ok so I'm pretty sure I figured it out... it wasn't index.html, css, or js being cached, it was...

![screen shot 2016-03-25 at 10 48 50 am](https://cloud.githubusercontent.com/assets/18193/14050162/42642aec-f277-11e5-9a1e-95c7067a51a3.png)

One of the last few Angular HTML partials, hooray!

Changing the headers for partials won't fix this for people who already have the partial cached. A couple options:

1. Easier: manually add a cache-busting query string here: https://github.com/metabase/metabase/blob/master/frontend/src/card/card.module.js#L13
2. Better: set up partials to be loaded through Webpack's file-loader (doesn't bundle them, but can do cache busting I think)

**Comment by agilliland** [comment]
I'm fine with taking the easy approach here and calling it done.  The real fix can come when we move this stuff over to redux and don't have any other external templates to load.
