### ISSUE TITLE
JDBC connection error with AWS Aurora, JDBC 2.7.5, Metabase 0.42.3 upwards

### ISSUE THREAD

**Issue by gingerkid77** [metabase/metabase#22126]
We're using Metabase with an AWS Aurora DB. I'm aware that is not officially supported, but up until now it has worked fine. 

As of 0.42.3 we're seeing errors on startup

> Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=myaurorainstance.rds.amazonaws.com)(port=3306)(type=master) : (conn=49989) could not load system variables

Metabase fails to start. Reverting to version 0.42.2 works, so my assumption at this point is that it is the bump in JDBC driver in 0.42.3. I'm looking into it, but if anyone else has experienced this or has any suggestions on a config fix I'd appreciate it.

**Comment by flamber** [comment]
Have a look here: https://discourse.metabase.com/t/rds-mysql-aurora-issue-solution/19568

**Comment by gingerkid77** [comment]
@flamber  thank you!
