### ISSUE TITLE
Editing dashboard filters on small devices blocked the screen

### ISSUE THREAD

**Issue by losrebellos** [metabase/metabase#22137]
When editing a dashboard with a lot of filters on a small screen devices, it is sticky and blocking the dashboard content.
Very similar to #20879 but in editing mode and it was not fixed in the related issue as it might require a different approach as the HTML hierarchy in edit mode is not the same.

**To Reproduce**
1. Create a dashboard with 15 filters and some graphs
2. Access this dashboard on mobile or simulate it on browser
3. Edit the dashboard
4. Try to scroll down
5. The filter panel is fixed, covering all dashboard content

**Expected behavior**
We could implement something similar to the fix for #20879, where on small devices, when there is more than 6 filters, the filters container won't not sticky.

**Screenshots**

- iPhone SE
![image](https://user-images.githubusercontent.com/348552/165536533-58c69d7e-7405-452e-a8b6-d283fb62a249.png)

- Galaxy S8
![image](https://user-images.githubusercontent.com/348552/165536875-c227a050-e6c0-4aab-a9b0-7d0d8baee8b7.png)

**Information about your Metabase Installation:**
- Metabase version: v0.43.1

**Severity**
Blocking all mobile users from editing their dashboard.

**Comment by gitstart** [comment]
Hi! We followed the steps and think that the issue is not happening anymore:

https://www.loom.com/share/90c1c9e939bb4d42a66119f4c700024a

**Comment by flamber** [comment]
@gitstart It's still happening on 0.44.0-rc1, but it's mostly on small screens with a lot of filters

https://user-images.githubusercontent.com/1447303/180211871-a2fb91db-444e-42df-87e6-107ce5b76c86.mp4

**Comment by uladzimirdev** [comment]
Alright, I got a confirmation that we do not encourage using "edit" mode on mobile screens, even the edit button is removed, so the issue will not be fixed
