### ISSUE TITLE
Snowflake alternative hostname implementation

### ISSUE THREAD

**Issue by BenSatori** [metabase/metabase#22133]
**Is your feature request related to a problem? Please describe.**
Snowflake supports using an alternative hostname (e.g. not <ACCOUNT>.snowflakecomputing.com). Without setting it, in environments such as with privatelink or custom hostnames (such as proxied), it's not possible to configure Snowflake.

**Describe the solution you'd like**
Adding an advanced settings field of "alternative hostname", which if present will override the existing hostname (<account>.snowflakecomputing.com). Note that the account itself needs to be sent with the "account" JDBC parameter.

**How important is this feature to you?**
For us this is specifically important, as we proxy traffic to Snowflake accounts.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by likeshumidity** [comment]
Metabase users are unable to connect to Snowflake via PrivateLink until this is resolved.
