### ISSUE TITLE
Virtual Tables

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2214]
Goals: Allow users to make improvements to the basic structure of their schema in order to present a model of the data more useful to daily tasks.

User Stories:
- Remove extra tables from highly normalized schemas by joining them together and presenting just the denormalized table.
- Provide columns on a table which are the result of simple calculations such as adding/subtracting two columns in a row.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by agilliland** [comment]
Here's the UX design for this new feature https://invis.io/PM67KRLF8

**Comment by LukeAbell** [comment]
This looks amazing! Can't wait!!

**Comment by soilforlifeforms** [comment]
How long to you think this feature is going to take to implement?

**Comment by nielsonsantana** [comment]
+1

**Comment by agilliland** [comment]
Regarding timing, we do our best to assign issues to Milestones (which have target dates) and stick to that.  Sometimes when a feature is large and difficult it doesn't get done in time and it may slip back one release.

**Comment by yalisassoon** [comment]
+1

**Comment by simopaasisalo** [comment]
Any update on the schedule? This would be a killer feature

**Comment by MrMauricioLeite** [comment]
There is a PR with virtual tables but have no update for a long time... 
see: #2144

**Comment by MrMauricioLeite** [comment]
Guys, is this a possible 0.19.0 feature?

**Comment by federicokeen** [comment]
Is there any update on this issue?

**Comment by vinothgovindarajan** [comment]
+1

**Comment by bardusco** [comment]
+1

**Comment by aswinkp** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by killertiger** [comment]
+1

**Comment by mazameli** [comment]
For those of you who are interested in this feature, I just wanted to point out that we've merged  [nested or sub-queries](https://github.com/metabase/metabase/pull/4613), which allows you to [use the results of a query as a starting table for a new query](https://github.com/metabase/metabase/issues/1822). One extra benefit of this feature is that it will allow you to use the [new drill-through and actions features](http://www.metabase.com/blog/Metabase-0.24) with tables that were generated from a SQL/native query (by opening them as a source table in the GUI query builder). Nested queries will be included in Metabase 0.25, which will be shipped very soon.

**Comment by brunobergher** [comment]
[Models](https://www.metabase.com/learn/data-modeling/models) do effectively all of this, so closing this issue.
If there are other needs not handled by models, we can create specific ussues.
