### ISSUE TITLE
"Gauge" visualization image does not appear in slack/email pulses

### ISSUE THREAD

**Issue by gintermaggio-am** [metabase/metabase#22151]
**Describe the bug**
Certain data visualizations appear fine when alerting via email or slack, but images of the "gauge" visualization and perhaps others don't appear.

**Logs**
NOTE: at 12:00, the "scheduled pulses" were an email of both the nps distribution and the nps gauge metrics.
https://gist.github.com/gintermaggio-am/5212afb09bf0a1997179944e7fa682c4

**To Reproduce**
1. Create a bar graph visualization for a metric
2. Create a guage visualization for a metric
3. Set up email and/or slack alerts for each

**Expected behavior**
I should receive emails/slack messages including an image of the visualization

**Actual Behavior**
I see the image of the bar graph, but the NPS gauge doesn't include an image.

**Screenshots**
NOTE: the screenshots were taken at different times, hence the variation in numbers. The number variation is expected/not the issue here.
![image](https://user-images.githubusercontent.com/97045741/165592202-b5284141-dc50-44f2-8adf-21e6a8267a08.png)
<img width="422" alt="image" src="https://user-images.githubusercontent.com/97045741/165592300-5e18eae0-2a40-4fd7-9d65-483868d398bb.png">
![image](https://user-images.githubusercontent.com/97045741/165592458-e8218813-d611-4a51-a744-9dd7951c1f67.png)
![image](https://user-images.githubusercontent.com/97045741/165592518-ef502634-1ef9-4baf-a293-c65a7fa32ee2.png)
![image](https://user-images.githubusercontent.com/97045741/165592575-ea1ec868-284f-4055-9b78-4eec029455dc.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.11.0-1019-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-10",
      "tag": "v0.41.4",
      "branch": "release-x.41.4",
      "hash": "471cfb9"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

**Severity**
Minor- completely blocks a "nice-to-have" feature.

**Additional context**
I haven't tested other visualizations.

**Comment by adam-james-v** [comment]
The gauge chart static-viz was added in 45, so this issue can be closed :)
