### ISSUE TITLE
Trino/Presto sql for timestamp is wrong

### ISSUE THREAD

**Issue by mrveera** [metabase/metabase#22157]
https://github.com/metabase/metabase/blob/8f9b5957fdf7d849e1be05927c2687ef4cf1bf58/modules/drivers/presto-common/src/metabase/driver/presto_common.clj#L145

https://prestodb.io/docs/current/functions/datetime.html

**Comment by flamber** [comment]
Metabase does not support Trino currently: #17532

**Comment by flamber** [comment]
@mrveera Okay, then please open a new issue describe clearly what the problem is.
