### ISSUE TITLE
MAX/MIN aggregation on categories incorrectly inferred as numbers

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#22154]
To reproduce:
1. New, Question, Sample Database, Products
2. Summarize, Maximum of Vendor, group by Category
3. Filter, Max of Vendor

### Actual

Can't filter properly since Max of Vendor is treated as a number.

![image](https://user-images.githubusercontent.com/7288/165609119-63c91f11-d7a8-4195-b29f-0193514ed4eb.png)

### Expected

Max of Vendor should be treated as text.

**Comment by flamber** [comment]
Continuation of #21973
