### ISSUE TITLE
Dashboard/question causes frontend reload loop, when browser Notification API cannot be read

### ISSUE THREAD

**Issue by briangonzalez** [metabase/metabase#22172]
**Describe the bug**
Metabase v0.43.0-rc1 refreshes nearly every second on Mobile Safari.

**Logs**
N/A

**To Reproduce**
1. Open mobile safari
2. Open MB
3. Open a dashboard
4. Notice MB refreshing on it's own. (Video below may look like I am "pulling to refresh", but I am not.)

**Expected behavior**
No refreshing.

**Screenshots**

https://user-images.githubusercontent.com/659829/165672442-97698a7e-9fde-4db9-be02-a95d66a599d5.MP4

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "iPhone",
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.4.181-99.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-18",
      "tag": "v0.43.0-rc1",
      "branch": "release-x.43.x",
      "hash": "2cab453"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
Pretty severe, but this is an RC so you know.

**Additional context**
Metabase is awesome?

**Comment by flamber** [comment]
Hi @briangonzalez 

I cannot reproduce, but I don't have an iPhone. It's hard to tell what is going on in the video, but I'm guessing there's a frontend reload because of some javascript error.
Can you reproduce with a new dashboard or does this problem only exists on existing dashboards?

There has been many changes since rc1, so please try rc2:
https://github.com/metabase/metabase/releases/tag/v0.43.0-rc2

**Comment by marksull** [comment]
Seeing this too in the  0.43.0 which makes it unusable. I created a new dashboard and added a single gauge and viewed the dashboard on the iphone and it just constantly reloads.

**Comment by flamber** [comment]
@marksull That was helpful. It's caused by the new notification handler #21247

**Comment by apostoltego** [comment]
Adding here that this appears to affect mobile chrome & mozilla too - alongside safari on iOS only but not on Android.
