### ISSUE TITLE
New field in a mongodb collection not showing even after re-scan 

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#22177]
**Describe the bug**
The new field is not showing on metabase even after numerous re-scan of DB

**To Reproduce**
1. Add new field for new entries in a mongodb collection
2. Check data model
3. Go to the collection name
4. Check new field created, it will not be shown

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1077-azure",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2020-01-13",
      "tag": "v0.34.1",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}

**Comment by flamber** [comment]
Latest release is 0.42.4: https://github.com/metabase/metabase/releases/latest
https://www.metabase.com/docs/latest/administration-guide/databases/mongodb.html#i-added-fields-to-my-database-but-dont-see-them-in-metabase

**Comment by jrca025** [comment]
@flamber is this fixed on the latest version?

**Comment by flamber** [comment]
@jrca025 There has been a lot of changes, but there's still a limitation, where only the first 10,000 documents in a collection is synced, so you need to put your fields (nulled) in one of the first documents.
