### ISSUE TITLE
i18n.js mapToMomentLocale  there is a bug in this method,

### ISSUE THREAD

**Issue by wxdx** [metabase/metabase#22171]
browser version: Chrome 100.0.4896.127
operating system: OS X 12.0.1  M1
databases: h2
Metabase version: 1.42.4
Metabase hosting environment: OS X 12.0.1
Metabase internal database: H2

i18n.js  mapToMomentLocale  

I'm Chinese, sorry for my bad English

When the language pack is Chinese, there is a bug in this method, it is zh in metabase, but zh-cn in moment

The browser console 

（索引）:247 Uncaught Error: Cannot find module './zh'
      at webpackContextResolve (（索引）:247:1)
      at webpackContext (（索引）:242:1)
      at updateMomentLocale (i18n.js:84:1)
      at setLocalization (i18n.js:77:1)
      at Module../lib/i18n.js (i18n.js:121:1)
      at __webpack_require__ (bootstrap:24:1)
      at fn (hot module replacement:61:1)
      at Module../app.js (app-main.js:48:1)
      at __webpack_require__ (bootstrap:24:1)
      at fn (hot module replacement:61:1)

The code try to fix

```js
function mapToMomentLocale(locale = "") {
  switch (locale) {
    case "zh-Hans":
      return "zh-cn";
    case "zh":
      return "zh-cn";
    default:
      return locale.toLowerCase();
  }
}
```

**Comment by wxdx** [comment]
When I modify it, the Chinese cannot be displayed

**Comment by flamber** [comment]
We should make sure there isn't others, which can cause problems: https://github.com/moment/moment/tree/develop/locale

**Comment by wxdx** [comment]
@ranquild 
I tested it and still can't display Chinese correctly, only English

**Comment by flamber** [comment]
@wxdx You need to provide more information - or at least screenshots, so it's possible to understand the problem.

**Comment by wxdx** [comment]
@flamber  
ok, see my action
- I cloned the master branch code and it worked successfully
- Set the language to Chinese in the settings，please see the picture below
![1](https://metabase-1305269037.cos.na-ashburn.myqcloud.com/1.jpg)
- I modified the code based on @ranquild 's commit and debugger
![2](https://metabase-1305269037.cos.na-ashburn.myqcloud.com/2.jpg)
- Skip the debugger, the main page is still in English 
![3](https://metabase-1305269037.cos.na-ashburn.myqcloud.com/3.jpg)
- Please see the picture for the console display
![4](https://metabase-1305269037.cos.na-ashburn.myqcloud.com/4.png)

**Comment by flamber** [comment]
@wxdx Something is wrong with your custom build of Metabase. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

Post "Diagnostic Info" from Admin > Troubleshooting.

This is how the official 0.43.0 looks like, when you change language:
![image](https://user-images.githubusercontent.com/1447303/167104673-b644e71a-b715-4bf5-b6cf-bf48ce76ee04.png)
![image](https://user-images.githubusercontent.com/1447303/167104723-e2efa290-5ff2-4456-8446-1065cb42d256.png)

**Comment by wxdx** [comment]
@flamber Ok, I'll try again later with version 0.43.0, thank you.

**Comment by WSYProject** [comment]
@wxdx 请问一下，代码里面怎么设置默认语言，我设置了src/metabse/public_settings.clj文件中的“site-locale”默认值为'zh'，最后后端运行的时候说是找不到'zh'，想问下你最后是怎么解决的
