### ISSUE TITLE
Summarize labels with issues

### ISSUE THREAD

**Issue by Drconstantino** [metabase/metabase#22188]
**Describe the bug**
Summarize by two dimensions (first timeline and then category), performs the aggregation well, however when using visualizations such as charts, the category dimensions is labeled all with the first value.

**Screenshots**
![image](https://user-images.githubusercontent.com/88409782/165747616-9943a661-2741-46f3-85b0-a7f7b779bb19.png)
Same content but on table
![image](https://user-images.githubusercontent.com/88409782/165747669-562ba28f-9ae7-42f1-8f3a-2e1a7a0dc0c6.png)

**Information about your Metabase Installation:**

Using  0.43.0-rc1 to test the new functionalities

**Comment by flamber** [comment]
Hi @Drconstantino 
I cannot reproduce.
Please try reproducing using Sample Database and provide full steps-to-reproduce.
And post "Diagnostic Info" from Admin > Troubleshooting.
