### ISSUE TITLE
Incorrect handling of relative date "Today" / "Yesterday" for Druid 

### ISSUE THREAD

**Issue by Digma** [metabase/metabase#2218]
When querying "today" and "yesterday" from Metabase, the results return are not correct. The date in not truncated to midnight. "Today" returns results from now() to midnight and "Yesterday" returns results from 00:00 the previous day until now().

<img width="948" alt="screen shot 2016-03-23 at 17 51 37" src="https://cloud.githubusercontent.com/assets/3279847/13993375/6e737dd4-f120-11e5-83f3-b4041728ca9d.png">

<img width="1440" alt="screen shot 2016-03-23 at 17 52 24" src="https://cloud.githubusercontent.com/assets/3279847/13993376/7442ad02-f120-11e5-9c64-ad6adbbf8347.png">

<img width="488" alt="screen shot 2016-03-23 at 17 52 12" src="https://cloud.githubusercontent.com/assets/3279847/13993387/7dcd643e-f120-11e5-96bd-eb0c7fdcd67e.png">

If this is a bug report, please fill in the blanks:
*  I am using Chrome browser.
*  My computer's OS is Red Hat Enterprise Linux .
*  I'm running Metabase locally from the JAR
*  My database is Druid.
*  My Metabase version is the latest from master (23.03.2016).

**Comment by camsaul** [comment]
@Digma good catch.

**Comment by Digma** [comment]
I think I found a fix by modifying the logic of RelativeDateTimeValue in Druid driver. I will make a pull-request tomorrow after some more checks

**Comment by camsaul** [comment]
@Digma that would be great :+1:
