### ISSUE TITLE
Selecting language Indonesian causes error

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#22192]
Setting a users language to Indonesian throws an error that the user cannot recover from

**Logs**
Can be seen in the gif below, but it appears that Moment is attempting to load the locale `in`. The locale for Indonesian that we use is `id`.

**To Reproduce**
On a Fresh install of metabase
1. Complete initial setup screen. Select english as your language
2. Go to account settings
3. Select Indonesian as the language
4. Click update

**Expected behavior**
Page to be refreshed and displayed in Indonesian

**Screenshots**
![chrome_HMnzAeRFuz](https://user-images.githubusercontent.com/1328979/165773394-ffd64388-8b60-41a4-b8ab-64f44eb749ff.gif)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.10.16.3-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "America/Halifax"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-04-27",
      "src_hash": "8878eded49230b44f9d94c8d7d86a32ab910ce4d",
      "tag": "v0.43.1-SNAPSHOT",
      "branch": "revision-history-not-updating-after-revert",
      "hash": "614127d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Seems to put us in an irrecoverable state. Potential P1

**Additional context**
@flamber @diegmonti 
We have confirmed that we call `PUT /api/user/:id` with the correct locale, but it appears to be set incorrectly in `window.MetabaseLocalization`. The terminal console will display `Locale 'in' not found`, which suggests that maybe something is happening [here](https://github.com/metabase/metabase/blob/master/src/metabase/server/routes/index.clj#L50)

**Comment by ranquild** [comment]
Refreshing the page won't help, the user is completely locked out.

**Comment by adam-james-v** [comment]
We’ve tracked things down to this:
In java 17:
```
metabase.util.i18n> (map locale ["id" "in"])
(#locale "id" #locale "id")
```

But in java 11:
```
metabase.util.i18n> (map locale ["id" "in"])
(#locale "in" #locale "in")
```

Because of this difference, everything works fine in Java 17 land -> the `id.edn` file can be found and translations to Indonesian work.
But, in Java 11 land, `id.edn` exists, but the system is looking for `in.edn`, which does not exist.

**Comment by adam-james-v** [comment]
Superseded by: #22226, which solves the problem in a cleaner way -> use the string passed by the FE without coercing to a locale at all. Since the frontend was sending "id" properly the whole time, and both the frontend and backend rely on the list of valid locales being derived from our translation resource files, we can rely on them being valid. We just take away the problem of Java coercing something to what we don't expect.
