### ISSUE TITLE
Allow pulses to be temporarily turned off

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2219]
We should give the user a way to temporarily turn off a pulse without deleting it. Simplest way with no UI changes would be to relax the >= 1 pulse channel requirement for existing pulses.

**Comment by tlrobinson** [comment]
For anyone currently running into this, a workaround is to use the email channel with no email addresses.

**Comment by mazameli** [comment]
Also, in this new world where you can turn off your last channel, we shouldn't delete the list of email recipients. Currently, if you turn off your email channel, and then turn it back on, you have to reenter all the recipients, which majorly blows 😤, and is an anti-pattern for the use case where you're just trying to turn it off temporarily with the intention of turning it back on and having the same recipient list.

**Comment by kdoh** [comment]
Ick yeah this is an unfortunate oversight on my part. Ideally we'd save the active status on a channel as a boolean separate from the recipients so you can update one without affecting the other.

**Comment by salsakran** [comment]
Is there anything that needs to be discussed or are we ready to just go with @tlrobinson's suggested change in the original description?

**Comment by kdoh** [comment]
Not as far as I'm concerned

**Comment by mazameli** [comment]
Ship it 🚀
