### ISSUE TITLE
Bookmark a dashboard or question with parameters

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#22207]
**Is your feature request related to a problem? Please describe.**
A customer told me that it would be great if the bookmark feature had parameters, so different people could bookmark the same dashboard or question with parameters pre-defined. This is a good idea when you have, for example, a dashboard that shows the sales for every country in the world and that you can filter by country, so the general manager of Brasil can bookmark the dashboard with Brasil as a filter value already pre-set and the GM of Germany can do the same with its country.

**Describe the solution you'd like**
Give users the possibility of bookmarking dashboards or questions with pre-set filter values

**Describe alternatives you've considered**
Use the browser bookmarks (which provide this feature as the entire URL with the query params is saved)

**How important is this feature to you?**
Important for a customer

**Additional context**
Reported by a customer when showing 43

**Comment by flamber** [comment]
Basically a duplicate of #16004

**Comment by paoliniluis** [comment]
closing this one in favor of the old one. I'll add the question use case
