### ISSUE TITLE
We should cut the "Navigation bar color" option from /admin/settings/whitelabel

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#22221]
The new redesign of Metabase's UI removes the old top blue bar, which was what the "Navigation bar color" option affected. I.e., once the new nav ships, this whitelabeling setting won't do anything

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2223916/165849754-f026ae2f-66ca-4ee3-9253-b2a0eee69cd9.png">

**Comment by gusaiani** [comment]
Fixed by https://github.com/metabase/metabase/pull/22406
