### ISSUE TITLE
Unable to properly filter on an aggregation

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#22230]
In the notebook, when filtering an aggregation (e.g. `Max` of something) that is not a number, the widget is useless.

**To Reproduce**

1. New, Question, Sample Database, People
2. Summarize, Maximum of Name, group by Source
3. Filter, Max of Name

Regardless what is being typed in the text box, the `Add filter` button remains disabled.

![image](https://user-images.githubusercontent.com/7288/165863907-ea73a3b2-848a-4906-aa39-90356d7a6c2e.png)

Also, looking at the network, there are 404 calls to `http://localhost:3000/api/field//values` (clearly, the field is is missing).

**Workaround**

Create a custom column, `trim([Max of Name])`, name it as e.g. `MaxName`, and filter on that instead.

![image](https://user-images.githubusercontent.com/7288/165863737-7ec6ed90-acfd-4aba-9ff4-eb9e58ebaa19.png)

**Expected behavior**

Filtering some aggregation like `Max of Name` above should be easy and pleasant.

**Comment by ariya** [comment]
Previously: #21973.

**Comment by nemanjaglumac** [comment]
If you choose "Not empty", then "Add filter" becomes enabled but the query fails with the non-existing endpoint.

`GET /api/field//values` (notice two //)
