### ISSUE TITLE
Date filter in the chart footer shows "Previous" filter type when "All Time" is selected

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#22247]
**Describe the bug**
Date filter in the chart footer shows "Previous" filter type when "All Time" is selected

https://user-images.githubusercontent.com/14301985/165942897-f90e6aa7-b3ad-4a0f-a0dc-1491bb97796e.mov

**To Reproduce**
1. New question -> Sample database -> Orders -> Visualize
2. Open Summarize sidebar -> Created At (by month)
3. In the chart footer ensure "All Time" is selected and click on it
4. It shows "Previous" filter

**Expected behavior**
It shows "All time" filter selected

**Information about your Metabase Installation:**
`release-x.43.x`

**Comment by ariya** [comment]
Random trivia: it's such a coincidence that the issue is about _All Time_ and the issue's last digits are `24/7`.
