### ISSUE TITLE
`More options...` button in a boolean filter is not aligned with the previous options

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#22253]
When filtering booleans, the `More options...` button is not aligned:
![image](https://user-images.githubusercontent.com/32561114/165965383-d2f9f499-2a5f-487d-bddb-f78e4191d8ce.png)

**Expected behavior**
It should be aligned with the previous options.

**Comment by flamber** [comment]
Because someone thought they weren't common options, but then it should probably just be a CE. Related to #5123

**Comment by MatheusBeniniF** [comment]
Hey @luizarakaki can you give me the steps to follow?

**Comment by luizarakaki** [comment]
Hi @MatheusBeniniF steps to follow what? To repo this, you can filter by any boolean column. If there are no boolean columns, you can create one using custom expressions or native sql.

**Comment by MatheusBeniniF** [comment]
> Hi @MatheusBeniniF steps to follow what? To repo this, you can filter by any boolean column. If there are no boolean columns, you can create one using custom expressions or native sql.

Now I find the place of this issue.

**Comment by iethree** [comment]
I think this is actually meant to be aligned with the text, right?

**Comment by luizarakaki** [comment]
@iethree yes!

**Comment by ranquild** [comment]
Aligned atm 
<img width="388" alt="Screenshot 2023-11-08 at 14 03 01" src="https://github.com/metabase/metabase/assets/8542534/8ae499b0-ee3b-4530-8635-a0546ff728ce">
