### ISSUE TITLE
best ways to keep Metabase documentation screenshots up to date.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2226]
as Metabase continues to evolve we're likely to run into the perennial problem of the product out pacing the documentation screenshots of said. 

would love to use this issue as a way to discuss possibilities for trying to automate as much of this process as possible from release to release. (although until we figure something out we'll try our best to do so manually).

**Comment by tlrobinson** [comment]
We could automate it with Selenium or something. Might make for a nice sort of smoke test as well.

**Comment by camsaul** [comment]
Do a lot of screenshots need to be updated every release?

**Comment by kdoh** [comment]
@camsaul Not every release necessarily. The point is when screenshots do drift (a fair portion of ours date back to our initial release) its a pretty laborious manual process to get them up to date and it'd be nice to be able to find ways to automate it if possible.

@tlrobinson https://github.com/facebookarchive/huxley seems like a possible solution but it seems like it's been EOL'd.

**Comment by camsaul** [comment]
Might be possible to use the Mac app and applescript some of it (e.g. do `Cmd-Shift-4` and capture `Metabase.app` automatiicaly)

**Comment by Addvilz** [comment]
phantom.js or casper.js could be used to automate this. Both can be put in Docker against dockerized Metabase and be run from there. 

Will require some coding to get to the screenshotting part (like, navigate there, click this, scroll there) done, but hey, definitely less effort than cropping print screens.

**Comment by jeff-bruemmer** [comment]
Closing this issue, as this isn't something we're likely to pursue any time soon.
