### ISSUE TITLE
Query Builder data picker can "forget" about multiple schemas

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#22285]
I have a bigquery project with two schemas: properati_ar and google_trends.
when using the query builder and choosing a data source, it is aware that this project has two schemas to choose from:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/6377293/166007650-62cc882c-93b3-490f-b18f-5920f28d2174.png">
I click on "google_trends" but change my mind and hit the back arrow:
![image](https://user-images.githubusercontent.com/6377293/166007759-f5830d28-84a9-40ad-9825-007f60fa80ed.png)
Then if i choose the bigquery project again, it immediately takes me back to "google_trends" with no option to choose the properati_ar schema
<img width="869" alt="image" src="https://user-images.githubusercontent.com/6377293/166007856-ef81e7e1-6fba-40be-81b7-1cf3d128bbd7.png">

https://user-images.githubusercontent.com/6377293/166008155-6b9a480e-a46b-4b84-80e7-7451629779bd.mp4

## Regression since:
I tried in 0.40.0 and cannot reproduce. It is always aware of the other schemas (note this is with pg but same behavior):
<img width="503" alt="image" src="https://user-images.githubusercontent.com/6377293/166009224-ccb1d6da-fde3-4933-b912-6a29db5738dc.png">

Also tried in 0.42.4 our last release and all schemas remain present:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/6377293/166017367-f3e5c8ea-bd46-4d69-880b-d6dfb735d77a.png">

## Workaround
I have tried navigating around in the app and then coming back to start a new query and I still cannot see the other schemas. The only way to see the schemas again is to refresh the app.

**Comment by flamber** [comment]
This has happened multiple times. #19451 #18349
