### ISSUE TITLE
relative filters for "current" have popovers which obscure choices

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#22283]
All choices
<img width="436" alt="image" src="https://user-images.githubusercontent.com/6377293/166003637-3f7e4148-8614-4822-9869-6883cee32e5e.png">

If you hover over "Week" for a very short amount of time, you get a popover over the choices on the bottom row. 
<img width="530" alt="image" src="https://user-images.githubusercontent.com/6377293/166003838-69df36ed-cc1d-4a98-b250-a674a8fdeca6.png">

Makes it quite annoying to select anything on the bottom row because the popover appears even when quickly mousing through "Week" towards "Quarter"

**Comment by mazameli** [comment]
Maybe we could add a 500ms delay before displaying those tooltips. But I think this is UX issue and not a bug, @dpsutton.

**Comment by flamber** [comment]
We could control positioning of tooltips, or implement a delay #11830
