### ISSUE TITLE
Allow hidden and static filters in public dashboards

### ISSUE THREAD

**Issue by jeansoula** [metabase/metabase#22312]
**Is your feature request related to a problem? Please describe.**
I'm allways frustrated to duplicate dashboard and questions to send each dashboard for each of my client.
The dashboard are the same for each of my client.
The questions which compose the dashboard are different from only one argument : the `client_id`

**Describe the solution you'd like**
I would like to create one dashboard where I could set a `client_id` that is not possible to modify with query param.

**How important is this feature to you?**
Important, cause I have 10 clients for the moment and maybe 100 in one month.
The operation take so long to duplicate dashboard and questions any time I have a new client.

**Comment by flamber** [comment]
It's already possible with "Locked" parameters in Embedding:
https://www.metabase.com/docs/latest/administration-guide/13-embedding.html

**Comment by jeansoula** [comment]
Perfect, I did it :)
