### ISSUE TITLE
[Admin > Databases] Disable "Save changes" button when there are no changes

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#22314]
**Describe the bug**
This is a low hanging fruit. When you navigate to `/admin/databases/:id`, the "Save changes" button is always enabled and it is possible to click on it and send the `PUT` request.

**Logs**
N/A

**To Reproduce**
1. Go to `/admin/databases/:id` where id is the id of any of your databases
2. Notice that you can immediately click on "Save changes" button
3. Click on it (it changes to "Success") and observe the `PUT` request in the network tab
4. After a few seconds, "Save changes" button is clickable again

**Expected behavior**
Disable the button when there are no changes. This should apply to **any** page throughout the app.

**Screenshots**
N/A

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
local dev, master, 0d9bf3126c22fbc0a806fbebd65ffe49fc330db3, H2, Sample Database

**Severity**
P3 at best.

**Comment by flamber** [comment]
I'm going to close this, since it's absolutely critical that you can click "Save" without making changes, which then kills all existing connections. This is heavy used to fix stalled/hanging connections - several P1 issues - instead of restarting the instance.

**Comment by nemanjaglumac** [comment]
> I'm going to close this, since it's absolutely critical that you can click "Save" without making changes, which then kills all existing connections. This is heavy used to fix stalled/hanging connections - several P1 issues - instead of restarting the instance.

Oh wow.
I didn't know about that. Thanks.

Is that documented anywhere, btw?

**Comment by flamber** [comment]
No, it's something I got Jeff to implement, when he was working on #14906, which we were trying to troubleshooting several other connection issues that required restarts to fix problems.
