### ISSUE TITLE
Add query tag to Snowflake

### ISSUE THREAD

**Issue by kevinneville** [metabase/metabase#22360]
**Is your feature request related to a problem? Please describe.**
Metabase questions should be easy to track in the SQL engine logs. Today we need to search by query text in order to find a query in the logs. However, if we would use query tags this would be easy to track. Tableau for example does this. In Snowflake it is straightforward by setting a query tag to each sql-query.

**Describe the solution you'd like**
Query tag which refers to what triggered it, like question, dashboard is added to every query. Prefarably for all sql enignes, but Snowflake can be a good start.

**Describe alternatives you've considered**
Match logs by text.

**How important is this feature to you?**
With decentralised ways of working and more self-service, we see the cost increase is significant. We would like to monitor the costs and this is how we do it for other tools like Tableau and dbt.

**Additional context**
I am not sure where to add it but https://github.com/metabase/metabase/blob/master/modules/drivers/snowflake/src/metabase/driver/snowflake.clj#L85 seems to be a good start.

**Comment by flamber** [comment]
This looks like a duplicate of the more generic #9514.

**Comment by kevinneville** [comment]
@flamber Yes, looks like it. I will upvote it and close this issue.
Thank you!
