### ISSUE TITLE
New "Relative dates ..." broken, when non english language is used

### ISSUE THREAD

**Issue by ryrun** [metabase/metabase#22361]
**Describe the bug**
When you click on "Relative dates ...", it will jump back to the column selection. A javascript error is thrown. Only happens, when german is the current language of the current user.

**Logs**
```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at a (DateUnitSelector.tsx:7:27)
    at DateUnitSelector.tsx:40:10
    at Array.map (<anonymous>)
    at t.Z (DateUnitSelector.tsx:38:14)
    at Qo (react-dom.production.min.js:153:146)
    at xs (react-dom.production.min.js:261:496)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
os @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
vo @ react-dom.production.min.js:131
us @ react-dom.production.min.js:212
Ml @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:248
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
react-dom.production.min.js:123 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at a (DateUnitSelector.tsx:7:27)
    at DateUnitSelector.tsx:40:10
    at Array.map (<anonymous>)
    at t.Z (DateUnitSelector.tsx:38:14)
    at Qo (react-dom.production.min.js:153:146)
    at xs (react-dom.production.min.js:261:496)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```

**To Reproduce**
1. Change language to "German" or "Frensh"
2. Create a simple question, where date columns are available
3. Select a date column and choose "Relative Daumswerte ..." / "Relative dates ..."
4. It jumps back to column selection and a javascript error is thrown

**Expected behavior**
Should show me the new "Relative dates ..."-controls / dialog.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 100.0.4896.127 (Offizieller Build) (64-Bit), Firefox 99.0.1 (64-Bit)
- Your operating system: Windows 10
- Your databases: MySQL
- Metabase version: 0.43.0
- Metabase hosting environment: Jar-file on Ubunt
- Metabase internal database: Postgres

**Severity**
Is this annoying, blocking some users.

**Comment by BertrandToulas** [comment]
Can confirm, using Metabase in French here, and I have the exact same issue.

**Comment by ranquild** [comment]
@flamber I've tried everything and I'm unable to reproduce this. Could you outline the exact steps? 

<img width="554" alt="Screenshot 2022-05-03 at 17 13 55" src="https://user-images.githubusercontent.com/8542534/166470304-4d781387-4418-4c01-ba4b-2fdad76a3319.png">
<img width="448" alt="Screenshot 2022-05-03 at 17 14 32" src="https://user-images.githubusercontent.com/8542534/166470319-65dce80d-c490-47c5-8294-3077e141833b.png">
<img width="358" alt="Screenshot 2022-05-03 at 17 14 42" src="https://user-images.githubusercontent.com/8542534/166470321-b2b7c7fa-e48c-43c7-b081-71f57b8d1272.png">

**Comment by flamber** [comment]
@ranquild Just go to a plain table like Orders > click CreatedAt > Filter this column > try clicking Relative dates...

https://user-images.githubusercontent.com/1447303/166471046-3894ccc2-be10-42c7-810d-f681f7848f68.mp4
