### ISSUE TITLE
Duplicate breakout fields can appear in a table under certain circumstances

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#22382]
**To Reproduce**
1. Go to Sample Database -> Orders -> Summarize
2. Add a grouping for 'Created At'
3. Go to Visualization -> click Table
4. Hide the 'Count' column
5. Go back to Summarize and clear the 'Created At' grouping, then add it again
6. You should now see two "Created At: Month" columns
7. Repeat step 5 ad nauseum to keep accumulating duplicate columns

**Screenshots**

https://user-images.githubusercontent.com/32746338/166496232-ee0c0562-d390-48aa-9496-a56d1cb81846.mp4

**Information about your Metabase Installation:**
Current master

**Comment by flamber** [comment]
Can reproduce back to at least 0.37.8. Feels very related to #20548.
