### ISSUE TITLE
Cookie session while log out

### ISSUE THREAD

**Issue by dschacon288** [metabase/metabase#22384]
**Describe the bug**
Its posible to continue using the session cookie even if the user is logged out

**Logs**
I dont have

**To Reproduce**
1. Log in
2. View some dashboard and safe de cookie session or the request
3. Log out
4. Send again the petition of view dashboard

**Expected behavior**
Once the user logs out, he should delete the session cookie and it should not be valid to make a request

**Screenshots**
We have a gif 
![bug-metabase](https://user-images.githubusercontent.com/31111885/166503275-61891de5-9eab-4987-b5b4-0970701115e0.gif)

**Information about your Metabase Installation:**
It is an old version but I did not see in the new version a documentation where I solved it
You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: safari last version
- Your operating system:  macOS 12.3
- Your databases: Postgres
- Metabase version: (e.g., 0.19.3)
- Metabase hosting environment: docker
- Metabase internal database: H2

**Severity**
medium, its a vulnerability secure

**Comment by flamber** [comment]
Hi @dschacon288 
Post "Diagnostic Info" from Admin > Troubleshooting.
You are using a reverse-proxy, so if that intercepts the logout process, then perhaps Metabase is not clearing the session.
Each session is valid until you logout, so if you just close the browser (or your reverse-proxy blocks the request), then the session is still valid.
