### ISSUE TITLE
[Permissions > Data] Users without data permissions are still offered database tables which leads to errors

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#22381]
**Describe the bug**
This regression has multiple effects in our UI.

For users with "No self-service" data permissions we are showing:
1. Browse data in the new homepage/collection sidebar
![image](https://user-images.githubusercontent.com/31325167/166488875-d003b107-bd78-4862-8000-675fe36001d9.png)

2. New > Question
![image](https://user-images.githubusercontent.com/31325167/166488982-447125c7-0645-427f-856c-5ebbae8121a7.png)

For users with "Block" data permissions we are showing:
1. Browse data in the new homepage/collection sidebar, but when you click on it, no tables are shown
![image](https://user-images.githubusercontent.com/31325167/166487674-d8ac9ed0-18bf-4f6b-b947-0177eea84407.png)

2. New > Question, but random (I cannot reproduce it always)
![image](https://user-images.githubusercontent.com/31325167/166487756-c6dbaab4-58d1-4704-8bf3-cb8510d086ff.png)

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
There are multiple issues that would require multiple steps. @flamber do you want me to break down this issue into multiple separate issues if it makes it easier to cover every single case?

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**
local dev, master, https://github.com/metabase/metabase/commit/6c9dbd7baaec36e45e2dc1ecbc2484661415c790, H2, Sample Database

**Severity**
P1 because it can also expose the info certain database tables which should be completely out of reach for some users

**Additional context**
New button inside collections can also create some problems. This goes deep and is not so easy to cover in one issue.

**Comment by luizarakaki** [comment]
More details:

What is happening:
- The user has Block / No self-service access to a database
- - If the user has Manage database access, they can see the database in Browse data, even if they can’t query anything. Expected behavior: it should be hidden
- - If the user has Manage database and Manage data model, they can see both the database and the tables. Expected behavior: both should be hidden
- - If the user has only Manage data model (no manage database), they can’t see anything (it is the expected behavior)

**Comment by alxnddr** [comment]
@noahmoss `/api/database` returns databases with "No self-service" but with "Manage database" permission even when `exclude_uneditable_details` parameter is not specified. 
`/api/database/1/schemas` and `/api/database/1/schema/:schemaName` (and maybe other endpoints) return data similarly without data access but with "Data Model" permission.

Seems like it should be fixed on the BE side, what do you think?
