### ISSUE TITLE
Users with `block` permissions see ambiguous error message when they open a dashboard

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#22395]
**Describe the bug**
IF a user with `block` permissions has collection permissions they can see a list of questions and dashboards. However, they are not even allowed to run the queries against the database so they will be greeted with an error when they open a question/dashboard.

The error displayed in dashboards is a bit misleading and says "There was a problem displaying this chart."

**Logs**
N/A

**To Reproduce**
_Applies to an EE instance_
1. Set `block` data permissions to "All users" but make sure they have `view` or `curate` collection permissions
2. Create a GUI question ("Orders") and it to a dashboard ("Orders in a dashboard")
3. Log in as normal (non-admin) user
4. Go to the root collection and you should see both the question and the dashboard
5. Click on a question to open it
6. The error is not helpful at first, but at least there is a "Show error details" button which reveals the true cause and correctly notifies the user with `Blocked: you are not allowed to run queries against Database 1.`
![image](https://user-images.githubusercontent.com/31325167/166558842-419353e8-e3c1-4ed7-bb02-1cbc63556c21.png)

8. Go back to the root collection
9. Click to open a dashboard
10. The message only says "There was a problem displaying this chart." without the real cause
![image](https://user-images.githubusercontent.com/31325167/166559031-a5085b5e-aff7-426a-8110-70828d8d51f6.png)

**Expected behavior**
Ideally, we shouldn't even let users open those questions and dashboards because it's pointless.

But if we already do, then at least display the correct error message in the dashboard.

**Information about your Metabase Installation:**
local dev, `master`, 2ad14a2d12a5cee40d22bd6ed6d6e367fa9553ae, H2, Sample Database

**Severity**
P3

**Additional context**
Tested on v1.42.1, so this is not a regression. It goes back to the time when we added `block` permissions in x.42

**Comment by flamber** [comment]
Until the question returns a permission error instead of a query error, then it will show an error like that, but it's confusing and not very helpful.
