### ISSUE TITLE
Able to download while shouldn't 

### ISSUE THREAD

**Issue by SokratisKouvaras** [metabase/metabase#22408]
**Describe the bug**
I am creating a new user group and adding a user to it (as Member, and its the only user in the group without a Manager). After i set the permissions of the group for a database (BQ dataset) with unrestricted data access , enabled NQ editiing, and blocked download permissions, the user can still download results from the db tables.
Permissions for 'All Users' are blocked on everything to prevent having higher permissions from there.
**Logs**
No logs 

**To Reproduce**
1. Create a security group
2. Add a user to it (as a Member, no other User in the group)
3. Block all permissions for 'All Users'
4. Give full data access to a sg, NQ editing enabled, disabled download permissions
5. User can still download 

**Expected behavior**
The user should not be able to download anything.

**Severity**
It's blocking me from creating the necessary permissions per User group.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "el",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.170+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v1.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @SokratisKouvaras 
I cannot reproduce, but the permissions can be a little confusing, since they are not showing the warning #22330

1. I remove permissions for All Users
![image](https://user-images.githubusercontent.com/1447303/166674024-e86f438e-d0f3-4ed9-a730-23a20eddf730.png)
2. Then add permissions for the group
![image](https://user-images.githubusercontent.com/1447303/166674227-02acc64d-4f67-4c69-baab-50fae5864963.png)
3. Login as a user in that group - does not have download permissions
![image](https://user-images.githubusercontent.com/1447303/166674422-3ed982b6-50f1-475c-b209-3adc757146a4.png)

**Comment by noahmoss** [comment]
Ah, I can repro this. The key is to change the All Users data perms to `Block` without changing the download perms.

For the time being, a workaround can be to change download perms first to `No`, then change data perms to `Block`.

Will fix shortly.

**Comment by nemanjaglumac** [comment]
> The key is to change the All Users data perms to Block without changing the download perms.

@noahmoss Isn't changing to `Block` automatically setting download permissions to `No`?

**Comment by noahmoss** [comment]
@nemanjaglumac This is the issue we chatted about on Slack yesterday... currently, setting `Block` doesn't actually clear download permissions on the backend. I thought that it was fine, but I had a slightly skewed understanding of how block permissions interact between groups, so it actually leads to an unexpected result in this case.

The workaround for now is to _first_ change download permissions for All Users to _No_, then change data permissions to `Block`.

**Comment by nemanjaglumac** [comment]
> This is the issue we chatted about on Slack yesterday... currently, setting Block doesn't actually clear download permissions on the backend.

Gotcha. I actually wanted to ask if that mechanism was behind this.
Thanks for clearing that up now.

**Comment by SokratisKouvaras** [comment]
Thank you for your immediate response!
