### ISSUE TITLE
Question with "No self-service" data sources can be saved after changing visualization type

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#22447]
**Describe the bug**
When a question uses a "No self-service" permission level data source it is possible to change visualization type and then save the question.

https://github.com/metabase/metabase/pull/22433#issuecomment-1117802949

**To Reproduce**
1. As an admin create a question available for test user and block its data source on the permissions page
2. As the test user open the question and change visualization type 
3. It is possible to save the question now

**Expected behavior**
It should not be possible to save the question after changing its visualization type

**Information about your Metabase Installation:**

Metabase EE

**Comment by nemanjaglumac** [comment]
Just to remove possible confusion in the future: "No self-service" doesn't require EE version.
