### ISSUE TITLE
Should we hide the "Find a table" search widget when there's only a single table?

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2246]
Or maybe when there some other small number of tables.

![screen shot 2016-03-25 at 12 19 11 pm](https://cloud.githubusercontent.com/assets/1455846/14051970/d98344a6-f283-11e5-9c3e-ad4391091303.png)

**Comment by agilliland** [comment]
@mazameli and I discussed this before adding that feature and ultimately felt it was simplest to leave it in place for visual consistency.  when the list of tables is short it's easy to just not use the search box and pick the table you want, so it's not really harming anything.
