### ISSUE TITLE
Can't compare boolean values

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#22462]
1. New Question, Sample Database, Products table
2. Filter, Custom Expression, enter `([Rating] > 2) AND startsWith([Vendor], "S")`
3. Preview, the filter works as expected:

![image](https://user-images.githubusercontent.com/7288/166964997-1b78ee46-6509-48ec-bf34-18bd7c1e9dd4.png)

4. Remove the filters and change it to `([Rating] > 2) = startsWith([Vendor], "S")`. Note the **equality** comparison.

### Actual

The filter is rejected:

> Expecting expression but found function startsWith returning boolean

![image](https://user-images.githubusercontent.com/7288/166964708-1006e5b7-83f7-4378-a340-e1070c0cab0d.png)

### Expected

The filter should work:

* `[Rating] > 2` results in a boolean value
* the return value of `startsWith` function is a boolean value
* It should be possible to compare both of them with `=` or even `!=`

**Comment by uladzimirdev** [comment]
I think it's properly handled on FE 

![Image](https://github.com/metabase/metabase/assets/125459446/275b5057-0309-421f-99e4-c981b6277a78)
