### ISSUE TITLE
[Permissions > Application] Users without collection permission cannot manage notifications from their account page

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#22473]
**Describe the bug**
If a user belonging to a group that doesn't have collection permissions, but has "Subscriptions & Alerts" permissions is subscribed to any dashboard subscriptions and/or alerts, they cannot manage their own notifications.

They can see the "Notifications" tab, but it's empty.

**Logs**
N/A

**To Reproduce**
_EE version_
1. As an admin, make sure "All users" don't have access to root collection
<img width="357" alt="image" src="https://user-images.githubusercontent.com/31325167/167015524-1eb14958-1b7b-471a-b843-f5fe27e6f7f6.png">
2. Also, make sure they have "Subscriptions & Alerts" permissions
<img width="819" alt="image" src="https://user-images.githubusercontent.com/31325167/167015561-d59f4d5f-787c-479e-b79b-5d8fee7ee736.png">
3. Create at least one alert and one dashboard subscription and assign them to the non-admin user
4. Log in as non-admin user
5. Go to `Account settings > Notifications`
6. You will not see any subscription there so you cannot unsubscribe which renders "Subscriptions & Alerts" permissions rather pointless
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/31325167/167015621-f0f7f4ec-beed-4c60-892d-22397239ff98.png">

**Expected behavior**
Allow users to manage their own notifications from the Account page if they have "Subscriptions & Alerts" permissions

**Information about your Metabase Installation:**
local dev, `master, `v1.43.0`, f85c6b7bf1630e32610081a742782c27496700e3, H2, Sample Database

**Severity**
P2 at least, because the new feature that's been implemented in v43 doesn't work as expected

**Comment by luizarakaki** [comment]
- Regardless of ANY permissions, a user should always be able to manage their own notifications
- “Subscriptions & Alerts” permissions make sense only if one has collections view or curate permissions

More at context at [Slack thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1651785420753669?thread_ts=1651779672.515859&cid=C01LQQ2UW03)
