### ISSUE TITLE
X-ray charts don't seem to respect whitelabel colors

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22476]
**Describe the bug**
X-ray charts don't seem to respect white label colors.

**To Reproduce**
1. Admin > Settings > Whitelabel
![image](https://user-images.githubusercontent.com/1447303/133608351-dcc93396-d9a8-47bc-9559-7d54b3e677bd.png)
2. Browse data > Sample > click X-rays for Reviews table
![image](https://user-images.githubusercontent.com/1447303/133608377-913bb0f1-28d8-4f0f-8096-dd2116be0918.png)

**Information about your Metabase Installation:**
Tested 1.34.4 thru 1.42.4

**Additional context**
Colors are hardcoded:
https://github.com/metabase/metabase/blob/89382bae965cb1340129e4d6c57ff7d491c692bd/src/metabase/automagic_dashboards/populate.clj#L46-L48

Previously EE139 https://github.com/metabase/metabase-enterprise/issues/139

**Comment by WiNloSt** [comment]
@flamber Forgot to ask you if do you think this should be backported?

**Comment by flamber** [comment]
@WiNloSt If you are comfortable with it, and the PR does add new features or translations, then generally yes. Looking at the code, it seems safe to backport.

**Comment by WiNloSt** [comment]
I decided not to backport this. As the PR would conflict with https://github.com/metabase/metabase/pull/21738 which contains a lot of changes.
