### ISSUE TITLE
Relative date filter in dashboard filter does not round period like in question filter

### ISSUE THREAD

**Issue by lephuongbg** [metabase/metabase#22482]
**Describe the bug**
It seems that the dashboard filter's relative date does not round the period like it does in question filter.

**To Reproduce**
1. Make date filter in dashboard
2. Try to set the date filter to past 9 months

**Expected behavior**
The period should be rounded like in question filter. (i.e, the period start from first day of the first month in the period, and end at the last day of the last month, excluding current month).  This is how the filter looks like in a question.

![image](https://user-images.githubusercontent.com/1001176/167045510-11e1b727-fdc0-473c-90c9-0ede3bbd5bc5.png)

**Current behavior**

The date filter in dashboard does not round the period. It looks like this currently:

![image](https://user-images.githubusercontent.com/1001176/167045732-eb732f96-2b2b-4945-a8f0-687201cc12bf.png)

**Information about your Metabase Installation:**

<details>
  <summary>Click to expand!</summary>

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "4.14.275-207.503.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.18"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": "Asia/Singapore"
    }
  }
}
```

</details>

**Severity**

Normal. It looks like that this is a UI display issue (data returned is fine), though it does confuse our sales analysts.

**Comment by flamber** [comment]
Same as #22225, but just for dashboards and native filter widgets.
