### ISSUE TITLE
Non-admin user with DB detail permissions always is shown "Bring the sample database back" link

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#22504]
**Describe the bug**
A non-admin user with DB detail editing permissions for at least one database is shown the button to restore the Sample DB, even if a Sample Database already exists (and even if they have permission to edit it). Clicking on the button returns a 403 in all cases.

**Expected behavior**
This button should be hidden for all users who are not full admins.

**Screenshots**
<img width="823" alt="image" src="https://user-images.githubusercontent.com/32746338/167201987-12aa946d-7edd-43c7-822a-1f02ee05672e.png">

**Information about your Metabase Installation:**
Current master

**Severity**
Minor

**Comment by noahmoss** [comment]
@alxnddr FYI, just found this minor issue. I think it's just a frontend change needed.

**Comment by flamber** [comment]
Very much in line with https://github.com/metabase/metabase/pull/22339#discussion_r867143598
