### ISSUE TITLE
Hand written query fails on Field Filter for field with timestamp

### ISSUE THREAD

**Issue by phuhl** [metabase/metabase#22503]
**Describe the bug**
A Field Filter for a date that is stored as timestamp (and mapped via the Admin -> Data Model Setting, as shown in screenshot below) can not be used in a hand written query.

Example Query:
```sql
SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT"
FROM "PUBLIC"."ORDERS"
[[ WHERE {{created}} ]]
LIMIT 1048575
```

Works on a normal date column, does not work on a column with a bigint that should be interpreted as a timestamp. It shows an error message.

**Logs**
Javascript Console Log:
```
error Input to date-string->range does not match schema: 

	 �[0;33m  [(named (not (instance? java.lang.String 2022)) date-string) nil] �[0m 
```

**To Reproduce**
1. Create table with bigint column "CREATED_AT"
2. In Admin-settings adjust the Field Type of "CREATED_AT" to "Creation Timestamp"
3. Run above query on that table

**Expected behavior**
The result should be filtered according to the variable instead of crashing.

**Screenshots**

Casting of column:
![image](https://user-images.githubusercontent.com/16835755/167195092-49c51918-7c4c-4164-b065-42dbd3337627.png)

Variable definition:
![image](https://user-images.githubusercontent.com/16835755/167195676-f03f5606-a2e6-4cee-aeca-c33fd98d3bc5.png)

Error message:
![image](https://user-images.githubusercontent.com/16835755/167195232-817772c5-af23-45e2-8728-580f08c7faa4.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (Firefox 98.0.2)
- Your operating system: (Arch Linux)
- Your databases: (Postgres)
- Metabase version: (0.43.0 )
- Metabase hosting environment: (Elastic Beanstalk)
- Metabase internal database: (Postgres)

**Severity**
Blocking certain dashboards to be shown by month. Hence, blocking some of our use-cases.

**Comment by flamber** [comment]
Hi @phuhl 

Your screenshots are not from 0.43.0.
Post "Diagnostic Info" from Admin > Troubleshooting.

You are not showing what you are casting the column as:
https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#casting-to-a-specific-data-type

And you say your database column is a `bigint`, but the little error snippet says something different.
Post the entire stacktrace from Admin > Troubleshooting > Logs.

**Comment by phuhl** [comment]
Hi @flamber,

> You are not showing what you are casting the column as

I checked and the table I ran this on seems to be the only one, where I did not set any casting.
After setting the correct casting, the error is gone. 

Sorry for the inconvenience.

Anyways, if someone still needs this info:

I made the screenshots on 0.43.2 and then noticed, that I had an update pending. I applied the update and validated that the error persists (which it did).

Diagnostic Infos:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "4.14.268-205.500.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
