### ISSUE TITLE
'DateFromParts' is not a recognized built-in function name.

### ISSUE THREAD

**Issue by angeljanne** [metabase/metabase#22514]
'DateFromParts' is not a built-in function in SQL Server 2008.

This function is just supported in SQL Server 2012 and after.

![image](https://user-images.githubusercontent.com/33130107/167237808-5d26526c-5971-4d19-a6cd-9e276ec45e70.png)

**Comment by flamber** [comment]
Hi @angeljanne 
Metabase does not support MSSQL 2008 anymore, which is not supported by Microsoft either.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
