### ISSUE TITLE
Models does not respect the column visibility setting

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22520]
**Describe the bug**
When changing a Model's column visibility to "Detail views only", then the column is still being shown regardless.
Not sure if this is FE or BE - feels like FE problem.

Potential workaround: Change the visibility in Admin > Data Model.

**To Reproduce**
1. Question > Sample > Reviews - save as "Q1"
2. Turn into a Model
![image](https://user-images.githubusercontent.com/1447303/167292999-5d7ecba5-d1dc-4296-a633-7a276223c833.png)
3. Click "Customize metadata" - select "Body" column and set "This column should appear in…"=`Detail views only`
![image](https://user-images.githubusercontent.com/1447303/167293143-f245c1d2-7374-4c59-822a-bbe7d3cf4ed5.png)
4. Save changes - "Body" is still present
![image](https://user-images.githubusercontent.com/1447303/167293200-0234e802-665a-4522-a308-fcb544145269.png)
5. And going back to "Customize metadata" looks like it has not saved any changes
![image](https://user-images.githubusercontent.com/1447303/167293253-2a498ce8-81f1-435b-bafd-3e4c2138a041.png)
6. Going to Admin > Data Model > Sample > Reviews > and changing the visibility of Body there will be reflected on the Model, but that feels incorrect, and also means it cannot be overridden.

**Expected behavior**
Either respect the setting or remove the setting.

**Information about your Metabase Installation:**
Tested 0.42.0 thru 0.43.0

**Additional context**
Seems like it might be related to #20624.

**Comment by gusaiani** [comment]
Thanks for the detailed issue description, as always, @flamber.

A set-up question: how do I go into a "detail view" for a question?

**Comment by flamber** [comment]
@gusaiani I'm not sure which "detail view" you are referring to.

**Comment by flamber** [comment]
@gusaiani See step3 the circled place in the right sidebar. You can control field visibility in Admin > Data Model.
This is likely not an easy issue to fix.

**Comment by gusaiani** [comment]
Yup, thanks @flamber.
