### ISSUE TITLE
Model becomes confusing, when Data Model column visibility is used

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22521]
**Describe the bug**
Model becomes confusing, when Data Model column visibility is used. And makes it impossible to edit metadata correctly.
Not sure if this is both BE or FE.

**To Reproduce**
1. Question > Sample > Products - save as "Q1"
2. Question > Sample > Orders - join with Saved Question "Q1" - save as "Q2"
3. Admin > Data Model > Products > change visibility of Vendor to "Only in detail views"
4. Turn in a Model
5. Go back to the model > click "Edit query definition" - it looks like Vendor is included, but is not shown anywhere
![image](https://user-images.githubusercontent.com/1447303/167295962-5645584d-ba8f-4477-90c6-e3f7f86b8e4d.png)
6. Clicking Metadata and trying to select any of the last columns (eg. Rating) will mark the next column as selected.
![image](https://user-images.githubusercontent.com/1447303/167296228-c1024a98-3834-4995-9df1-d8804f353ee6.png)

Addition to step 6: It seems like this can sometimes cause the metadata sidebar to become blank in some situations, but I haven't been able to reproduce that consistently (only on some of my test setups):

https://user-images.githubusercontent.com/1447303/170826729-bbc20f3e-9582-42cb-838a-1ecdc68dbcac.mp4

**Information about your Metabase Installation:**
Tested 0.42.0 thru 0.43.0

**Additional context**
Likely very related to #22520

**Comment by WiNloSt** [comment]
@flamber Not sure what I did wrong, but I need to swap steps 3 and 4 on the repro to reproduce this bug. Maybe the repro steps could need an update?

**Comment by flamber** [comment]
@WiNloSt This issue has had several other problems, which were difficult to reproduce, and there has been a lot of changes since the issue was created.
