### ISSUE TITLE
No dropdown options when dashboard filter is mapped to question with double aggregation

### ISSUE THREAD

**Issue by apostoltego** [metabase/metabase#22528]
**Describe the bug**
On 0.43.0 when mapping a dropdown filter to a question with double aggregation (2 layers) dashboard filters no longer show dropdown options. This was working on 0.42.x
To be clear - the categorical column for which the filter is needed is present in the 1st level of aggregation.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Create question with 2 levels of aggregations. The first level must contain the categorical filter for which you're interested in.
2. Add the question to a dashboard
3. Map filter to question
4. Dropdown no longer behaves as it should.

**Expected behavior**
Dropdown of values should show

**Screenshots**

![Screenshot 2022-05-09 at 11 17 08](https://user-images.githubusercontent.com/16501677/167390305-e03f64f8-b3c3-458b-a4d2-b600fe1ad418.png)
![Screenshot 2022-05-09 at 11 21 26](https://user-images.githubusercontent.com/16501677/167391233-9867861d-47f0-4e50-b559-addbbfb733de.png)
![Screenshot 2022-05-09 at 11 22 26](https://user-images.githubusercontent.com/16501677/167391246-295bb84f-cc37-4dbe-8a59-1137aabef62f.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "4.14.231-173.361.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Metabase version: (e.g., 0.19.3)
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.
This is breaking existing dashboards for end users and is affecting 20-30% of our content (10+ dashboards)

**Additional context**

**Comment by flamber** [comment]
Hi @apostoltego 
I'm not sure how you got the dropdown to show previously. There's an old issue about problems with the dropdown on questions with nested queries (double aggregation etc) #12985.
I cannot reproduce on 0.42.4/0.43.0, meaning I do not get a dropdown, because of #12985:
1. Create a simple question like this:
![image](https://user-images.githubusercontent.com/1447303/168466611-1045fc40-186c-4abb-8c7f-50ddc677dbd1.png)
2. Adding to a dashboard and add Text filter and connect to "Category" field
![image](https://user-images.githubusercontent.com/1447303/168466653-39ce74a5-7ae4-4424-86d5-a7c7d4799b3a.png)
3. The dropdown does not show anything but a plain text input - similar when upgrading to 0.43.0
