### ISSUE TITLE
[Epic] Embedding: Allow parameters to override selected full-app components

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#22529]
A way to hide certain parts of the UI for embedding.

**Links**
- Product doc https://www.notion.so/metabase/Embedding-Allow-parameters-to-override-select-full-app-components-3eda7f2d08c343cdb59928ca721d2c6d

**Implementation Plan**
- [x] Add options for app navigation
- [x] Add options for questions and dashboards

**How to Test This Feature Out**

- Use https://github.com/metabase/sso-examples/tree/master/app-embed-example
- Modify the root url here https://github.com/metabase/sso-examples/blob/master/app-embed-example/src/index.js#L39 and here https://github.com/metabase/sso-examples/blob/master/app-embed-example/src/index.js#L44 to pass query string params

**Comment by rcronin** [comment]
Is there a way with this functionality to hide everything in the action bar but the filter button?

**Comment by npfitz** [comment]
@rcronin Not currently. This will allow you to hide all action buttons, but that's as granular as it is at the moment
