### ISSUE TITLE
Delete table records from table view

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#22547]
Related to #22542

Add a button for deleting a table row to the table view (maybe a similar one to the button opening the object detail view that appears on row hover). Maybe add a simple way to confirm the action (guess the browser `alert` will work perfectly for now).

Note: the button should only show up when:

1. Writeback's global feature flag is enabled (see #22551)
2. Writeback is enabled for a particular DB (see #22545)

**Comment by kdoh** [comment]
Completed
