### ISSUE TITLE
Updating an enterprise instance with custom colors doesn't show up correctly in 1.43

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#22558]
**Describe the bug**
I updated an internal test instance (ee stats) that has some custom colors set up to 1.43 and it doesn't show up quite right - see screen shots:

Login page:
![Screen Shot 2022-05-09 at 12 57 33 PM](https://user-images.githubusercontent.com/65313/167488022-5a13f662-98e8-48c2-8a57-7a847c997161.png)

App home page:
![Screen Shot 2022-05-09 at 12 57 53 PM](https://user-images.githubusercontent.com/65313/167488057-17e7f17a-e0eb-4d04-9ecc-6441c24e5332.png)

Custom color set up:
![Screen Shot 2022-05-09 at 12 58 25 PM](https://user-images.githubusercontent.com/65313/167488139-a428b58c-0647-4f69-a52e-493d762e0da6.png)

**Comment by flamber** [comment]
Duplicate of #22221
