### ISSUE TITLE
Actions: Add Global feature flag for enabling actions (backend)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#22551]
Part of https://github.com/metabase/metabase/issues/22542

We should add a global public Setting for enabling the Actions features as a whole. It should be disabled by default. I don't think we need to have it be settable from the admin panel -- maybe this is settable via env var only?

Not sure where this should go, `metabase.public-settings` is probably fine for now or maybe a new `metabase.actions` namespace could work as well, as long as that namespace gets loaded. Or maybe `metabase.api.actions`. TBD

**Comment by kulyk** [comment]
@camsaul do you have a name for the setting in mind already? Asking so the FE can use it right away

**Comment by camsaul** [comment]
Sounds like we want to call this Setting `enable-actions`
