### ISSUE TITLE
We should hide advanced aggregation types under a click

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2257]
There are a lot of aggregation options now:

![screen shot 2016-03-28 at 1 04 57 pm](https://cloud.githubusercontent.com/assets/2223916/14089183/700537f2-f4e8-11e5-9e31-3634f14b314f.png)

This is a little bit of a undo/redo, but maybe we should only present the most common options, and have the user click `More` to see the rest:

![screen shot 2016-03-28 at 1 09 36 pm](https://cloud.githubusercontent.com/assets/2223916/14089210/91c49194-f4e8-11e5-8ad9-c73bc7a07016.png)

![screen shot 2016-03-28 at 1 11 16 pm](https://cloud.githubusercontent.com/assets/2223916/14089212/9525d456-f4e8-11e5-906e-5f8edf6b3a5f.png)

The popover should reset if the user closes it or if the Common Metrics menu item is selected.

**Comment by agilliland** [comment]
@mazameli can you enumerate the set of aggregations that should go under the `more ...` expansion?

**Comment by mazameli** [comment]
Sure. As the second image in the comment depicts, my thinking was that only Raw Data, Count of Rows, Sum of, and Average Of should be exposed by default.

**Comment by mazameli** [comment]
But let's have a conversation about this, because I'm starting to wonder how much we should try to optimize the QB right now for novice users.

**Comment by brunobergher** [comment]
Not applicable anymore.
