### ISSUE TITLE
Fullscreen dashboard mode shouldn't cause obscured cards to be faded out

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2258]
(On v16 snapshot on Chrome)

I went to fullscreen mode on a dashboard, and one of the cards faded back. You can barely see it in the bottom-right of this screenshot:
![faded-card](https://cloud.githubusercontent.com/assets/2223916/14090096/46aefba4-f4ed-11e5-8a00-07bbb8902d82.png)

When I scrolled down, it popped back in, but then scrolling back up made it fade out again:
![card](https://cloud.githubusercontent.com/assets/2223916/14090099/4cae546e-f4ed-11e5-9435-607abde3b97a.png)

**Comment by tlrobinson** [comment]
This is a "feature" I added so you wouldn't get partially obscured cards on your nice dashboard. If it's undesirable I can remove it.

**Comment by kdoh** [comment]
FWIW I've personally found this useful, but I had some context from Tom on why it was doing this in the first place. @mazameli it seems like this behavior was unexpected to you?

**Comment by camsaul** [comment]
I think this is an UNEXPECTED behavior for some users.

**Comment by mazameli** [comment]
Gotcha. Like Cam said, this was unexpected for me and confused me, probably in part because this was a worst-case scenario because the card was _barely_ obscured. Personally, I think this is a little too unpredictable — I would expect people to curate and tweak a fullscreen dashboard themselves so that it looks exactly right when they put it up on a TV. I.e., I'd almost expect them to remove a partially obscured card if they didn't want it, or they'd just leave it up there if enough of it was visible to satisfy them. The latter is actually exactly what we were doing with that GA dashboard we had up on the TV for a while.

**Comment by tlrobinson** [comment]
I think if it's a desirable feature it could use some tweaks, like fading in/out over ~500ms to make it clear it's intentional, and perhaps if a card is only barely obscured then just shrinking it vertically to fit on screen.

**Comment by mazameli** [comment]
My bias would be to not do the fade out at all, especially with an eye towards how we're planning on fading out cards that can't be affected by a currently active dashboard filter.

**Comment by mazameli** [comment]
I still feel the same about this as I did over a year ago! 😆

**Comment by TheSeanBrady** [comment]
This behavior makes the dashboard unusable for display on a large screen, and therefore negates the need for this application for this customer. I just can't get it to work in a way that is predictable enough for a dashboard to work, as the table changes in height daily. Sure it make look weird when it's obscured, but at least it's partially usable instead of seemingly blank. 

I would strongly suggest that you reconsider. This is a blocker for us.

**Comment by mazameli** [comment]
@TheSeanBrady Yep, I think we're all on the same page, and #4877 should fix this behavior.
