### ISSUE TITLE
Slow text fade when going from night to day colors

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2259]
(0.16 snapshot on Chrome)

In fullscreen dashboard mode, toggling from night colors to day colors, most things on the screen fade back in at the same speed, but some elements come in a second or two later in a weird way, so that this is what you see for about three or four seconds **after** the fade transition (notice that card titles and table text are missing):

![screen shot 2016-03-28 at 1 52 55 pm](https://cloud.githubusercontent.com/assets/2223916/14090179/b55b2668-f4ed-11e5-96bd-b763fabb4232.png)

**Comment by tlrobinson** [comment]
Yeah, I've seen this happen, and it's super weird and I don't understand why and I hate CSS.

**Comment by kdoh** [comment]
I can try and take a look at this.
