### ISSUE TITLE
Mondodb, filter previous 30 days gives "There was a problem with your question"

### ISSUE THREAD

**Issue by cyberneid** [metabase/metabase#22616]
**Describe the bug**
I updated metabase to the last version 0.43. I imported a mongodb 3.0 database but when I try to filter between two dates or the previous 30 days I got "There was a problem with your question"
With the previous version it worked like a charm.

**Logs**
Command failed with error 16810: 'exception: bad query: BadValue unknown top level operator: $expr' on server mongodb.back4app.com:27017. The full response is { "code" : 16810, "ok" : 0.0, "errmsg" : "exception: bad query: BadValue unknown top level operator: $expr" }

**To Reproduce**
1) Load a MongoDB database with a table that contains a field of type Date
2. Create a query by filtering between two dates
3. See the error

**Expected behavior**
A view with the correct filter, as it worked in a previous version

**Screenshots**

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "it-IT",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10-Ubuntu-0ubuntu0.20.04.1",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10-Ubuntu-0ubuntu0.20.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-91-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2 (Ubuntu 14.2-1.pgdg20.04+1+b1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
We cannot analyze our data

**Comment by flamber** [comment]
Hi @cyberneid 
I cannot reproduce. Please include:
- MongoDB version
- Example of a document
- And the full stacktrace from Admin > Troubleshooting > Logs.

**Comment by cyberneid** [comment]
MongoDB version: 3.0
Example of a document: 
{
    "objectId": "OVsLgD6Rzc",
    "type": "ScanMRZ",
    "createdAt": "2020-10-14T21:23:11.394Z",
    "updatedAt": "2020-10-14T21:23:11.394Z"
  },

Logs: I'm not able to collect logs. When I open Admin > Troubleshooting > Logs a wheel appears rotating indefinitely

**Comment by cyberneid** [comment]
Just tried with v0.36.10 and it worked.
on more recent versions it doesn't work any more

**Comment by flamber** [comment]
@cyberneid Metabase follows the life-cycle of MongoDB: https://www.mongodb.com/support-policy/lifecycles
We are not going to create a fix for older MongoDB versions, since it's difficult enough to handle the difference between MongoDB 4 and 5 already.

Install the following Java 11 to have functional logs: https://www.metabase.com/docs/latest/operations-guide/java-versions.html
