### ISSUE TITLE
Frontend incorrectly shows empty boolean values as `false`

### ISSUE THREAD

**Issue by astrojuanlu** [metabase/metabase#22621]
**Describe the bug**
Empty boolean columns from PostgreSQL display a value of `false`. All the columns in the screenshot are empty, but boolean ones display a misleading "false":

![Screenshot 2022-05-11 at 12-11-26 Question · Metabase](https://user-images.githubusercontent.com/316517/167826265-1acb09af-ba67-49a3-84d7-b42faa1c6070.png)

Metabase knows this, because "distribution" says that they're all empty, and both "filter -> false" and "filter -> not empty" give "No results!", as expected.

**Logs**
[TBC]

**To Reproduce**
[TBC]

**Expected behavior**
If the column is empty, don't display anything, regardless of type.

**Severity**
Not blocking, just annoying and confusing.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.13.0-1022-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Regression since 0.43.0

Reproduce on H2, Postgres, etc:
```
select 'TRUE' "Text", true::boolean "Boolean", 1::bit(1) "Bit"
union all select 'FALSE', false::boolean, 0::bit(1)
union all select 'NULL', null::boolean, null::bit(1)
```
![image](https://user-images.githubusercontent.com/1447303/167840614-03b43620-a0a6-47ed-9962-9b483319d32d.png)

0.42.4 shows correctly:
![image](https://user-images.githubusercontent.com/1447303/167840532-912f504e-d6e8-4a5f-9e12-3d3686db82ab.png)

**Comment by chipach** [comment]
This seems independent of database.  Snowflake 

```
select 'TRUE' "Text", true::boolean "Boolean"
union all select 'FALSE', false::boolean
union all select 'NULL', null::boolean
```

shows the same as [flamber](https://github.com/flamber)'s result above against Postgres.

**Comment by gusaiani** [comment]
Currently we have a case where Custom Expressions returning false will actually return null.

This case clashes with the case we're trying to solve.

Bumping difficulty to Medium.
