### ISSUE TITLE
Logo gets crushed in whitelabelling

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#22631]
**Describe the bug**
When you upload a custom logo in v43, it will get crushed even if it's symmetric

**Logs**
NA

**To Reproduce**
1) setup Metabase Enterprise
2) head to settings->admin->whitelabel
4) upload a custom logo. E.g.
![logo3](https://user-images.githubusercontent.com/1711649/167887074-eaf6ebe5-c5e0-47b6-9d44-31fea9792852.png)
5) compare the uploaded logo in Metabase vs what you see in the home page

**Expected behavior**
See the logo correctly

**Screenshots**
correct
![image](https://user-images.githubusercontent.com/1711649/167886466-722e7ccb-8419-4b20-acad-eb7a8994521a.png)

incorrect
![image](https://user-images.githubusercontent.com/1711649/167886531-43641fb1-0a1a-4ee6-a6ba-74bda899e842.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-os latest
- Your databases: Postgres 14
- Metabase version: 1.43.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Cosmetically severe

**Additional context**
NA

**Comment by flamber** [comment]
There's a difference between PNG and SVG. PNG doesn't respect the aspect, while SVG means the logo can be tiny.
