### ISSUE TITLE
New questions are not saving the arrows from our custom generated titles properly.

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2265]
When saving a new question which uses an FK.

Starts as ...

<img width="479" alt="screen shot 2016-03-28 at 6 35 05 pm" src="https://cloud.githubusercontent.com/assets/1987787/14095341/228bccb2-f514-11e5-80c6-7ab873c8e698.png">

Ends as ...

<img width="383" alt="screen shot 2016-03-28 at 6 34 47 pm" src="https://cloud.githubusercontent.com/assets/1987787/14095343/29a88936-f514-11e5-8f03-c8ce14936d4c.png">

**Comment by agilliland** [comment]
@tlrobinson do have a chance to take a quick look at this one?  just noticed it and i'm about to head out for a couple hours.

**Comment by tlrobinson** [comment]
Will do within an hour or two.

**Comment by tlrobinson** [comment]
@agilliland I actually can't reproduce this. Is it happening in a particular browser or page of the application?

**Comment by agilliland** [comment]
sorry about that.  must be something to do with my local dev environment.  going to close this.
