### ISSUE TITLE
Default value picker for dashboard filter appears in top-left corner of screen

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#22678]
**Describe the bug**
If you create a dashboard filter, save it, and then go back to edit the default value, the widget appears in the top-left corner of the screen. Occurs at least with text and number filters, but doesn't occur with date filters. 

**To Reproduce**
1. Create a dashboard with at least one question
2. Go to "Edit dashboard" -> "Add a filter" -> "Text or category" -> "Dropdown"
3. Link the filter to any text field on a question and click "Done"
4. Click the gear icon next to the filter and click the "Default value" box
5. The default value picker should appear in the top-left corner of the screen

**Expected behavior**
The default value picker should appear in the appropriate place in the sidebar.

**Screenshots**

https://user-images.githubusercontent.com/32746338/168149912-a30074f2-4697-469e-b3c1-5ebc891425af.mov

**Information about your Metabase Installation:**
Current master on Firefox

**Comment by alxnddr** [comment]
@noahmoss which version of Firefox on which OS do you use? I could not reproduce it on my machine yet

**Comment by noahmoss** [comment]
Interesting, I just tested again and I can't reproduce it either

**Comment by flamber** [comment]
A lot has changed the past two months, so we can reopen or create a new issue if it occurs again. I cannot reproduce anymore.
