### ISSUE TITLE
The new date filter popover overflows browser viewport

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#22681]
**To Reproduce**
1. Create a dashboard
2. Go to "Edit dashboard" -> "Add a filter" -> "Time" -> "All options"
3. Make your browser window relatively short -- i.e. there shouldn't be much white space below the "Default value" selector
4. Click the default value selector to choose a default
5. The popup will open above where you clicked, and the top values will be cut off by the top of the page

**Expected behavior**
All values should be viewable and clickable regardless of window size

**Screenshots**
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/32746338/168156375-bec123fc-fdb7-4acb-a10c-d98240cded06.png">

**Information about your Metabase Installation:**
Current master on Firefox

**Severity**
Minor; if you expand the browser window vertically and reopen the selector, it will open below where you click and you can scroll see all the values.

**Comment by flamber** [comment]
It's even causing overflow of the app container:
![image](https://user-images.githubusercontent.com/1447303/168237549-4926b3f8-c830-4696-8a63-48034dd7b504.png)
And horizontal scrollbars:
![image](https://user-images.githubusercontent.com/1447303/168237728-7c84f941-4f23-4ede-86f3-f271de1c42c9.png)
