### ISSUE TITLE
Some dropdown selectors are 100% width

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22699]
**Describe the bug**
Some dropdown selectors are 100% width - haven't checked everywhere, but guessing it's a bug in the component.

**To Reproduce**
1. Go to Admin > Settings > Localization
![image](https://user-images.githubusercontent.com/1447303/168273146-1a967153-bdb8-4765-8f45-0c03e81b2ee6.png)

**Expected behavior**
0.43.0 for reference
![image](https://user-images.githubusercontent.com/1447303/168273350-4e8a1eb7-bd55-47d8-b2f7-1a7a73484b04.png)

**Information about your Metabase Installation:**
Tested master `f3f9c62`

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/23163
