### ISSUE TITLE
Databases with no permission are still shown as search results

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#22695]
**Describe the bug**
Even if the user does not have access to a database, it is still shown in the search results from the main screen search widget.

**Logs**
N/A

**To Reproduce**
1. Go to the home screen
2. Search for a database that you known you don't have permission for
3. Notice it in the results (screenshot 1)
4. Click the result
5. Notice the URL is like `/browse/N-database-name`
6. Observe permission error is shown (screenshot 2)

**Expected behavior**
This database shouldn't be shown as a search result since there are no permissions for it

**Screenshots**

<img width="648" alt="1-search_result" src="https://user-images.githubusercontent.com/3521562/168203164-e9d1f085-e7cd-414f-bd11-199d9bc1d17e.png">

<img width="1099" alt="2-click_result" src="https://user-images.githubusercontent.com/3521562/168203193-2320bef6-f325-412b-8b80-f782bcbb9c41.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 101.0.4951.54 
- Your operating system: OS X 12.3.1
- Your databases: N/A
- Metabase version: `v1.41.7`
- Metabase hosting environment: self-hosted (I believe)
- Metabase internal database: Unknown

**Severity**

Low - no permission escalation, but even names might be sensitive?

**Additional context**

**Comment by flamber** [comment]
Regression since 0.40.0
