### ISSUE TITLE
Custom Expression aggregation in Metrics does not work

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22700]
**Describe the bug**
Custom Expression aggregation in Metrics does not work. Cannot create or edit existing expression.
Regression since 0.43.0

**To Reproduce**
1. Admin > Data Model > Metrics > Create > Sample > Orders
2. Click "View" > Custom Expression
   1. The modal is too small
   2. There is no formula validation, so incorrect things can be input - ex. `Count / Distinct([BLAHBLAHBLAH])`
   ![image](https://user-images.githubusercontent.com/1447303/168277390-fc1028ec-b6ef-4f88-ac73-27218bcf7117.png)
   3. Inputting something like `Count / Distinct([Product ID])` and clicking Done
   ![image](https://user-images.githubusercontent.com/1447303/168278550-645474f5-57a9-4e0a-93c0-b38485da72b5.png)
   Will look like it's saving the expression, but the results are incorrect (should be `93.8`) and opening the expression again will not show the formula that was inputted
   ![image](https://user-images.githubusercontent.com/1447303/168278861-5ed537fb-7dfd-4165-993c-39a26ca8e8cb.png)

**Expected behavior**
Similar to Custom Expression aggregation in normal Notebook

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.43.0 - regression since 0.43.0

**Comment by nemanjaglumac** [comment]
Nitpick:
Notice how after the step 1 when you select "Orders" the result incorrectly shows `1`.
![image](https://user-images.githubusercontent.com/31325167/168340537-9c2fb0d1-5134-45a7-8d84-cbdfbd893885.png)

If you click on the "Count" to open a popover and then select a "Count of rows", then the result updates to the correct value of `18760`.
