### ISSUE TITLE
Should show connection error message during setup

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2271]
This is a BASIC need for users who can't figure out why they can't connect to their DB.
###### What The API Returns :evergreen_tree:

![screen shot 2016-03-29 at 3 46 29 pm](https://cloud.githubusercontent.com/assets/1455846/14126498/31c9a1c4-f5c6-11e5-9da8-63ddfaee5ded.png)
###### What I See in the Browser

![screen shot 2016-03-29 at 3 52 06 pm](https://cloud.githubusercontent.com/assets/1455846/14126504/3651d824-f5c6-11e5-9724-2700e68a9454.png)

**Comment by agilliland** [comment]
is that error not shown next to the field itself?  the structure of the error suggests it's a field level error, which generally means it's meant to be displayed next to the field.

**Comment by camsaul** [comment]
Nope not shown by the field :cry:

**Comment by camsaul** [comment]
It looks like some messages are displayed correctly when the come back from the API keyed by `:message` but ones like this are not.

**Comment by salsakran** [comment]
this seems to be getting displayed now, though the error messages are a bit cryptic.
