### ISSUE TITLE
"Save Changes" Button doesn't get enabled on admin panel after changing "Slackbot Enabled"

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2272]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is OS X Mavericks.
*  I'm running Metabase™ Enterprise 16.0 via `lein ring server`
*  My database is Oracle :scream_cat: 

When I go to the admin panel and toggle the disabled/enabled switch for METABOT nothing happens. The "Save changes" button stays disabled, and no API calls are made according to backend LOGS :deciduous_tree: 

![oh-no](https://cloud.githubusercontent.com/assets/1455846/14126802/6dc2b9ac-f5c8-11e5-8c1a-3eb8610f5456.gif)
.

**Comment by camsaul** [comment]
We should probably change that

**Comment by kdoh** [comment]
Yeah it doesn't seem to make a lot of sense that you can enable / disable metabot if you aren't connected to Slack. My thinking is it should default to disabled and be inactive in the case that no token / slack connection exists.
