### ISSUE TITLE
Duplicate question button missing, when question is in a view-only collection

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22726]
**Describe the bug**
Duplicate question button missing, when question is in a view-only collection, but the user has data permissions.

**To Reproduce**
1. Admin: Question > Sample > Orders - save as "Q1" to "Our analytics"
2. User: go to "Q1" - click the title to expand the sidebar, which shows "Duplicate this question"
![image](https://user-images.githubusercontent.com/1447303/168420735-72769cb5-0a95-442c-bb01-44553fd9bf5a.png)
3. Admin: Admin > Permissions > Collections > set "Our analytics" to `View` for "All users"
4. User: go to "Q1" - click the title to expand the sidebar, which does not show duplicate button
![image](https://user-images.githubusercontent.com/1447303/168420948-1c77f741-ca55-4a77-9cd6-8b9125dc3e2d.png)

**Expected behavior**
It should be possible to use duplicate button if the user has the sufficient data permissions.
If the user does not have data permissions (eg. no SQL write), then it should not show this button.

**Information about your Metabase Installation:**
Tested 0.42.4 and 0.43.0

**Additional context**
Related to #15255

**Comment by gusaiani** [comment]
@paoliniluis suggests:

```
You have to duplicate the question but save it in a collection you have access to. So there should be a modal in that operation.
```

Indeed there is a modal.

And it includes a `select` where you can pick the collection you will save it in.

But as default, it will show you the collection it's in — which in the case of this issue, the user cannot write to.

If offer the duplicate button, click it, then we manually pick another collection, it gets saved.

So we can implement this partially by omitting the current collection from the select box.

**Comment by flamber** [comment]
This is a bug. And there's a separate issue for saving to a view-only collection #22727
