### ISSUE TITLE
Unable to edit field name and description in Field page

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#22742]
**Describe the bug**
The autosave make it's impossible to edit Field name and description in Field view page

**To Reproduce**
1. Admin > Data Model
2. Click `Orders` table and choose Edit `ID` column by clicking the ⚙️ icon
3. Try Edit the name or description, do some delete then insert for a few times

**Expected behavior**
Autosave should be less aggressive.

**Screenshots**

**Information about your Metabase Installation:**

- Your browser and the version: tried on both latest safari and firefox
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Metabase version: current master (dfa35462398f1cb2e45b845e6e1c2e7e44a02f9b)

**Severity**

**Additional context**

https://user-images.githubusercontent.com/25661381/168601617-325fd792-cb44-483e-9e66-fc520e07c46d.mov

**Comment by flamber** [comment]
Very related to #10462 and #16780

**Comment by killakalle** [comment]
@flamber is this fix also included in the Enterprise version?

I believe we are still experiencing this issue as described above. See a recording
https://user-images.githubusercontent.com/30682796/185362791-cd57aa7a-8541-41e8-9182-fce5cfed93b0.mp4

Our version is `1.44.1`

![image](https://user-images.githubusercontent.com/30682796/185362595-e9885bd4-7601-47bf-bd97-c48c1405789b.png)

**Comment by flamber** [comment]
@killakalle All editions contains the same fixes. Please use the support email when using the Pro/Enterprise plans.

I cannot reproduce. Either you have a browser extension interfering (try a different browser or incognito without extensions), or there's other requests being made which triggers blur/bounce (check your browser developer Network-tab)
