### ISSUE TITLE
Multi-series SQL line and area charts plot incorrect values

### ISSUE THREAD

**Issue by UnicycleJonathan** [metabase/metabase#2274]
When you write a SQL query that results in a multi-series chart, the line and area charts plot the values incorrectly. It appears that these charts are being treated like stacked bar charts, with each line containing the sum of the values for all lines below it at that position on the x-axis. This is completely wrong for a multi-series line chart: each series line should simply render its actual values, no summing is required.

A sample Postgres queries that demonstrates the bug, with screenshot attached. For example, at day 10, the lines should be at 20 and 30 on the y-axis, yet they are at 20 and 50 instead.
![screen shot 2016-03-29 at 6 49 50 pm](https://cloud.githubusercontent.com/assets/4969406/14129567/e97e7e48-f5df-11e5-81a3-5a967a2be8f4.png)

```
WITH days AS (SELECT GENERATE_SERIES(1, 10) AS day)
SELECT
  day,
  day * 2 AS y1,
  day * 3 AS y2
FROM days
ORDER BY DAY;
```

Also, I'm a little perplexed why there's no ability to rename the series lines, and manually adjust the x- and y-axis scales and labels.

I'm using Postgres on a local Mac installation, version 0.16.

**Comment by MartinArens** [comment]
+1

**Comment by tlrobinson** [comment]
@UnicycleJonathan @MartinArens I agree this is definitely broken for line charts, however in the past we have always stacked area charts, and I think we will continue to do so by default (but may consider introducing a setting to allow unstacked area charts)

Does this make sense, or do you feel strongly that area charts should never be stacked?

**Comment by UnicycleJonathan** [comment]
Thanks for looking at this. Yeah I think you're right, area charts can continue to be stacked.

Separate issue, but can/should multi-series line charts render a legend, since the y-axis only gets the label of the first series?

**Comment by tlrobinson** [comment]
Yeah, they will get legends when it's fixed (just posted PR #2276). We had all this working correctly at one point, but it broke recently. Here's what line, area, and bar charts will look like in the fixed version, using the query you posted (let me know if they don't seem right to you):

![screen shot 2016-03-30 at 12 28 00 pm](https://cloud.githubusercontent.com/assets/18193/14154752/13b2f368-f673-11e5-91b5-fab7e1accd80.png)
![screen shot 2016-03-30 at 12 28 09 pm](https://cloud.githubusercontent.com/assets/18193/14154753/13b32d1a-f673-11e5-82b7-4ff90033a666.png)
![screen shot 2016-03-30 at 12 28 13 pm](https://cloud.githubusercontent.com/assets/18193/14154754/13b53e0c-f673-11e5-88b0-2fc41ab68c8c.png)

**Comment by UnicycleJonathan** [comment]
This looks correct to me. Thank you!

**Comment by erickreutz** [comment]
> but may consider introducing a setting to allow unstacked area charts

+1!
