### ISSUE TITLE
Cannot view Object Detail of non-numeric IDs

### ISSUE THREAD

**Issue by ehsanm94** [metabase/metabase#22768]
**Describe the bug**
By clicking on ID (_id) field of a MongoDB question result; "We're a little lost...".
The H2 sample database behaves as expected, also this issue was not exist in v0.37.4 which I recently upgrade it to v0.43.0.

**To Reproduce**
1. Create a new question on a MongoDB instance without an ID filter.
2. Click on ID value of any found documents.
3. You will getting lost!

**Expected behavior**
The expected behavior is opening the specific document's page that was clicked.

**Information about your Metabase Installation:**

- Browser and the version: Chrome 101, Firefox 100
- Operating system: Fedora 29
- Databases: MongoDB
- Metabase version: v0.43.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Comment by flamber** [comment]
Reproduce:
1. Admin > Data Model > Sample > Products - set ID=No semantic type, and Title=Entity key
![image](https://user-images.githubusercontent.com/1447303/168798180-655447c2-913e-4fd1-adb7-0af87a9a110c.png)
2. Question > Sample > Products - click "Rustic Paper Wallet"
![image](https://user-images.githubusercontent.com/1447303/168798347-319ebbad-0bb5-4641-b522-ceaece8e3d55.png)
3. URL changes to `/question?objectId=Rustic%20Paper%20Wallet#eyJk...` with the error "We're a little lost..."
![image](https://user-images.githubusercontent.com/1447303/168798489-a912f247-e928-496f-ad8b-f0a523220d74.png)

**Comment by alxnddr** [comment]
Probably, it has been partially fixed:
<img width="1363" alt="Screenshot 2022-05-20 at 01 31 10" src="https://user-images.githubusercontent.com/14301985/169407993-6c3ccc0a-67bf-4402-a1a5-23fef457b896.png">

However, it does not show relations
