### ISSUE TITLE
Collection name under dashboard title wraps weirdly when viewport is narrow

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#22776]
The collection name wraps at individual characters, leading to a very strange UI when you make the window narrow.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/32746338/168833823-f0fae52f-6f00-4b01-8569-cfa0f5da625c.png">

**Information about your Metabase Installation:**
Current master on Firefox

**Comment by flamber** [comment]
Almost a repeat of #17354, but just with sidebar open.
