### ISSUE TITLE
"Pick your starting data" motion starts before the sidebar finished collapsing / misaligns

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#22783]
**Describe the bug**
Our "Pick your starting data" component fires when you click the new question button, but when the sidebar is still expanded, the box starts where the sidebar finishes and then corrects to the left when the sidebar finished collapsing.

Also, if you do the following:
1) (from the home screen) New question
2) expand the sidebar
3) new-> question

the component gets stuck misaligned

**Logs**
NA

**To Reproduce**
Premature start:
1) From home page -> New -> question
2) see the component firing first and then accomodating

Misaligned component:
1) (from the home screen) New -> question
2) expand the sidebar
3) with the sidebar expanded, again new-> question
4) see the component misaligned

**Expected behavior**
If sidebar is expanded and you are in the home screen, click on new question first colapses the sidebar and then pick your data box gets expanded

If you're in the new question view and side bar is expanded, align the component

**Screenshots**
Premature firing

https://user-images.githubusercontent.com/1711649/168860765-6b5a1b47-d656-4682-862e-7d18ee24f903.mp4

Misaligned component

https://user-images.githubusercontent.com/1711649/168860905-00d687bf-7925-41f7-9fe4-fdd454931dc4.mp4

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.43.1
- Metabase hosting environment: Docker
- Metabase internal database: Posgres 14.2

**Severity**
Cosmetic

**Additional context**
NA

**Comment by nemanjaglumac** [comment]
We changed the new question flow that now includes the entity picker so this is not reproducible anymore neither in master @ https://github.com/metabase/metabase/commit/c7e2a0078a0866af913a99c26ca39b545ef42244, nor in the latest release 50.7.
