### ISSUE TITLE
Segments and Metrics should be documented in the Data Model Reference

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2278]
Right now they are in the Query Builder but not in the data model reference.

The descriptions and info about them should be listed.

**Comment by mazameli** [comment]
This is a WIP prototype with a tour through my thinking:

https://invis.io/3J76VUQB9#/155943411_Tables_List

**Comment by tlrobinson** [comment]
I believe this has everything except a replacement for "connections". I wasn't sure if we had decided on solution for that.

**Comment by mazameli** [comment]
I've updated the prototype and gotten feedback from @salsakran. I think this is more straightforward and should be good to go for implementation now:

https://invis.io/3J76VUQB9#/156665048_No_Segments_Or_Metrics
