### ISSUE TITLE
Click behavior not working well

### ISSUE THREAD

**Issue by armetiz** [metabase/metabase#22807]
**Describe the bug**
On dashboard, I configured an on-click on "orderId" column to update 3 filters.
But when clicking on it, it update only 2 filters.

**Logs**
Error getting setting table.columns TypeError: Cannot read properties of undefined (reading 'cols')
Error getting setting table._cell_background_getter TypeError: Cannot read properties of undefined (reading 'rows')
Error getting setting table.columns TypeError: Cannot read properties of undefined (reading 'cols')
Error getting setting table._cell_background_getter TypeError: Cannot read properties of undefined (reading 'rows')

**To Reproduce**
I'm using some other few "on-click behavior to update filter" configuration, but I have not understand how to reproduce with some other column or filter.

**Scree
<img width="377" alt="Capture d’écran 2022-05-18 à 14 44 28" src="https://user-images.githubusercontent.com/1119250/169041616-90805950-e307-466a-a775-54ec000c60d5.png">
<img width="793" alt="Capture d’écran 2022-05-18 à 14 44 53" src="https://user-images.githubusercontent.com/1119250/169041629-cdfd0f86-25e5-4858-8bad-caebb5eb2052.png">
nshots**

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36    ",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.10.93-87.444.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.27"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-16",
      "tag": "v0.43.1",
      "branch": "release-x.43.x",
      "hash": "7f1a1c4"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

- Your browser and the version: Brave 1.35.104 Chromium: 98.0.4758.109
- Your operating system: macOS 12.3.1
- Your databases: MySQL
- Metabase version: v0.43.1
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
This is annoying for our metabase users.

**Comment by flamber** [comment]
Hi @armetiz 
I cannot reproduce. Since you are not able to reproduce with different combinations, then I'm guessing it's something specific with how you've made the setup of the dashboard.
Can you include the metadata of your entire dashboard? Go to the URL `/api/dashboard/123`, where 123 is the dashboard ID.

**Comment by flamber** [comment]
@armetiz The only thing strange I see is "Début de vente" has `hasOnlyFieldTargets: true` - otherwise everything looks normal.
I have not been able to reproduce based on the dashboard metadata you provided.
Try recreating everything on a new dashboard.
