### ISSUE TITLE
X-Ray a Model

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#22825]
**Is your feature request related to a problem? Please describe.**
Currently we can only do X-rays in data sources, but not on models. It would be a good addition to the product if we can make X-Rays to those in the same way we do to databases so users can find insights automatically from them.

**Describe the solution you'd like**
"x-ray this model" function when you click on a model

**Describe alternatives you've considered**
If you define the model as a view in the DB, Metabase will see it as a table and will allow you to x-ray it

**How important is this feature to you?**
Requested by a lead

**Additional context**
NA

**Comment by flamber** [comment]
There's a hidden (unsupported) function, where it is possible to X-ray Saved Questions and Models by going to the URL:
`/auto/dashboard/question/123`, where 123 is the question or model ID - the URL path is still called "question" even for Models

**Comment by paoliniluis** [comment]
Shipped in v48
