### ISSUE TITLE
无法可视化任何MySQL数据表

### ISSUE THREAD

**Issue by Mrzhuhanxin** [metabase/metabase#22830]
**Describe the bug**
无法可视化任何MySQL数据库表

**Logs**
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/43130589/169243446-c6d6a5f1-870f-4872-9e95-cee907a29979.png">

**To Reproduce**
1. 新的->问题->选择数据库->选择表->视觉化

**Expected behavior**
应该显示该数据表的所有属性信息

**Screenshots**
<img width="959" alt="image" src="https://user-images.githubusercontent.com/43130589/169244519-f48fa099-df1c-498a-95c0-65c3cbbdc4dc.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (Chrome/101.0.4951.64 Safari/537.36)
- Your operating system: (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) )
- Your databases: (MySQL)
- Metabase version: (0.43.1)
- Metabase hosting environment: (Docker)
- Metabase internal database: ( Postgres)

**Severity**
这个Bug非常严重，导致我们数据分析人员无法查看数据，被迫回退到上一个版本，还望能尽快修复，谢谢🙏

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
