### ISSUE TITLE
Public share links wrong domain

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#22833]
After upgrading from v0.42.4 to v0.43.1 all my public share links are wrong.
The metabase domain is replaced with an encoding string.

![Capture d’écran 2022-05-19 à 12 04 09](https://user-images.githubusercontent.com/1840026/169269350-ee35b954-7f67-451e-a868-ec01d3639724.png)

**Comment by flamber** [comment]
Change your Site URL in Admin > Settings > General. Duplicate of #19487
