### ISSUE TITLE
Aggregations on multiple fields showing datetimes as results with PostgreSQL?

### ISSUE THREAD

**Issue by underyx** [metabase/metabase#2283]
*  I am using the Chrome browser.
*  My computer's OS is OS X El Capitan.
*  I'm running Metabase with the Docker image.
*  My database is PostgreSQL.
*  My Metabase version is 0.16.0.

Let's say I have the following data
```
CREATE TABLE sale (
    timestamp TIMESTAMP WITH TIME ZONE,
    region TEXT
);
```

I would like to get a line chart with time on the X axis, row count on the Y axis, and one line per region.

In the table view I'd expect this to be represented as one row per day and one column per region, with the cells containing the DB row counts. Here, it works perfectly with the included sample data:

![](https://i.imgur.com/OtqdrcB.png)

But with PostgreSQL, I'm seeing this instead:

![](https://i.imgur.com/AoSmpRW.png)

Oh dear! :see_no_evil:

**Comment by tlrobinson** [comment]
Hmm I tried reproducing this on Postgres 9.4 with the schema and query you posted and a few data points:

```
insert into sale values (now() + '-1 day', 'foo'), (now() + '-1 day', 'bar'), (now() + '-2 days', 'foo');
```

and it seems to work fine:

<img width="757" alt="screen shot 2016-03-31 at 3 53 34 pm" src="https://cloud.githubusercontent.com/assets/18193/14193338/cb65142e-f758-11e5-94b2-cde7c77b62d5.png">

Did you change anything in the admin metadata page?

**Comment by agilliland** [comment]
@tlrobinson what happens if the pivoting is flipped so that the timestamps end up as the smaller dimension?

**Comment by agilliland** [comment]
in fact, it almost looks like we are parsing the cell value as a datetime in that scenario, instead of the header values.

**Comment by tlrobinson** [comment]
@agilliland Yup, that did it:
<img width="754" alt="screen shot 2016-03-31 at 3 59 32 pm" src="https://cloud.githubusercontent.com/assets/18193/14193449/a101e940-f759-11e5-9d7f-eed139db8ca8.png">

**Comment by tlrobinson** [comment]
It seems like there are two things we should fix:

1. We're not pivoting `cols` correctly.
2. If there's a date/time column it should probably always use that as the row label.

**Comment by tlrobinson** [comment]
I fixed # 1 in #2284. Do we also want to do # 2?

**Comment by agilliland** [comment]
So 1) gets the value displaying properly and 2) formats the column header?  if that's the case then i agree that we should do 2) as well.

**Comment by underyx** [comment]
Oh wow, I can't believe you guys were seriously this quick with the fix. You two are amazing! :astonished:

**Comment by salsakran** [comment]
@underyx tell your friends ;)

**Comment by tlrobinson** [comment]
@agilliland No, I meant # 1 fixes both of things you mentioned, # 2 would also put the date/time column in the first column regardless of the cardinality compared to the other column. Not sure if that's desired or not.

**Comment by agilliland** [comment]
Ahh, yeah, lets skip that and we can decide a bit later if we think that's really the best thing to do.  The fix in the current PR is all we need to close out this issue.
