### ISSUE TITLE
Metabase v0.43.1 does not start - "[Failed SQL: (0) DELETE FROM permissions_group WHERE name = 'MetaBot']"

### ISSUE THREAD

**Issue by elements92** [metabase/metabase#22837]
**Key data:**
- Current version: 0.42.3
- Updated to: 0.43.1
- With PostgreSQL DB 11
- OS: Windows Server 2012 R2/6.3/amd64
- 
Hello,
when I perform an update (the same also occurs from version 0.42.4), then metabase no longer starts.

**Logs**
INFO|15212/5|Service yajsw|22-05-19 14:20:12|2022-05-19 14:20:12,905 INFO metabase.core :: 
INFO|15212/5|Service yajsw|22-05-19 14:20:12|Metabase v0.43.1 (7f1a1c4 release-x.43.x) 
INFO|15212/5|Service yajsw|22-05-19 14:20:12|
INFO|15212/5|Service yajsw|22-05-19 14:20:12|Copyright © 2022 Metabase, Inc. 
INFO|15212/5|Service yajsw|22-05-19 14:20:12|
INFO|15212/5|Service yajsw|22-05-19 14:20:12|Metabase Enterprise Edition extensions are NOT PRESENT.
INFO|15212/5|Service yajsw|22-05-19 14:20:12|2022-05-19 14:20:12,921 INFO metabase.core :: Starting Metabase in STANDALONE mode
INFO|15212/5|Service yajsw|22-05-19 14:20:12|2022-05-19 14:20:12,952 INFO metabase.server :: Launching Embedded Jetty Webserver with config: 
INFO|15212/5|Service yajsw|22-05-19 14:20:12| {:port 3000}
INFO|15212/5|Service yajsw|22-05-19 14:20:12|
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:12,999 INFO metabase.core :: Starting Metabase version v0.43.1 (7f1a1c4 release-x.43.x) ...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,014 INFO metabase.core :: System info:
INFO|15212/5|Service yajsw|22-05-19 14:20:13| {"file.encoding" "Cp1252",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "java.runtime.name" "OpenJDK Runtime Environment",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "java.runtime.version" "1.8.0_265-b01",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "java.vendor" "AdoptOpenJDK",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "java.vendor.url" "http://java.oracle.com/",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "java.version" "1.8.0_265",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "java.vm.name" "OpenJDK 64-Bit Server VM",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "java.vm.version" "25.265-b01",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "os.name" "Windows Server 2012 R2",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "os.version" "6.3",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "user.language" "de",
INFO|15212/5|Service yajsw|22-05-19 14:20:13| "user.timezone" "Europe/Berlin"}
INFO|15212/5|Service yajsw|22-05-19 14:20:13|
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,030 INFO metabase.plugins :: Loading plugins in C:\Metabase\plugins...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,389 INFO plugins.classloader :: Added URL file:/C:/Metabase/plugins/ifxjdbc.jar to classpath
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,389 INFO plugins.classloader :: Added URL file:/C:/Metabase/plugins/ojdbc8.jar to classpath
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,468 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery-cloud-sdk...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,468 INFO driver.impl :: Registered driver :bigquery-cloud-sdk (parents: [:sql]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,483 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,483 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,483 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver"]
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,499 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :csv...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,499 INFO driver.impl :: Registered driver :csv (parents: [:sql-jdbc]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,499 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,499 INFO driver.impl :: Registered driver :druid  
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 INFO driver.impl :: Registered abstract driver :google  
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase BigQuery Driver"]
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 WARN plugins.lazy-loaded-driver :: Warning: plugin manifest for :bigquery does not include connection properties
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 INFO driver.impl :: Registered driver :bigquery (parents: [:sql :google]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,514 INFO driver.impl :: Registered driver :googleanalytics  
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,530 INFO plugins.dependencies :: Metabase Informix Driver dependency {:class com.informix.jdbc.IfxDriver} satisfied? true
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,530 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :ibminformix...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,530 INFO driver.impl :: Registered driver :ibminformix (parents: [:sql-jdbc]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,530 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,530 INFO driver.impl :: Registered driver :mongo  
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,546 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? true
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,546 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :oracle...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,546 INFO driver.impl :: Registered driver :oracle (parents: [:sql-jdbc]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,546 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-common...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,546 INFO driver.impl :: Registered abstract driver :presto-common  
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 INFO plugins.dependencies :: Plugin 'Metabase Presto JDBC Driver' depends on plugin 'Presto Common Driver'
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 INFO plugins.dependencies :: Metabase Presto JDBC Driver dependency {:plugin Presto Common Driver} satisfied? true
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-jdbc...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 INFO driver.impl :: Registered driver :presto-jdbc (parents: [:presto-common]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 INFO plugins.dependencies :: Plugin 'Metabase Presto Driver' depends on plugin 'Presto Common Driver'
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 INFO plugins.dependencies :: Metabase Presto Driver dependency {:plugin Presto Common Driver} satisfied? true
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 INFO driver.impl :: Registered driver :presto (parents: [:presto-common]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,561 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,577 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,577 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
INFO|15212/5|Service yajsw|22-05-19 14:20:13|
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver"]
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,593 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,608 INFO db.setup :: Verifying postgres Database Connection ...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,796 INFO db.setup :: Successfully verified PostgreSQL 11.3 application database connection. 
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,796 INFO db.setup :: Running Database Migrations...
INFO|15212/5|Service yajsw|22-05-19 14:20:13|2022-05-19 14:20:13,796 INFO db.setup :: Setting up Liquibase...
INFO|15212/5|Service yajsw|22-05-19 14:20:14|2022-05-19 14:20:14,030 INFO db.setup :: Liquibase is ready.
INFO|15212/5|Service yajsw|22-05-19 14:20:14|2022-05-19 14:20:14,030 INFO db.liquibase :: Checking if Database has unrun migrations...
INFO|15212/5|Service yajsw|22-05-19 14:20:15|2022-05-19 14:20:15,421 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
INFO|15212/5|Service yajsw|22-05-19 14:20:15|2022-05-19 14:20:15,530 INFO db.liquibase :: Migration lock is cleared. Running migrations...
INFO|15212/5|Service yajsw|22-05-19 14:20:15|2022-05-19 14:20:15,702 ERROR metabase.core :: Metabase Initialization FAILED
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::v43.00-044::noahmoss:
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|     Reason: liquibase.exception.DatabaseException: FEHLER: could not open relation with OID 17210 [Failed SQL: (0) DELETE FROM permissions_group WHERE name = 'MetaBot']
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Liquibase.lambda$null$0(Liquibase.java:265)
INFO|wrapper|Service yajsw|22-05-19 14:20:15|executed script: scripts/trayMessage.gv 1
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.lambda$child$0(Scope.java:180)
INFO|wrapper|Service yajsw|22-05-19 14:20:15|executed script: scripts/trayMessage.gv 1
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:189)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:179)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:158)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:243)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Liquibase.lambda$update$1(Liquibase.java:264)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.lambda$child$0(Scope.java:180)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:189)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:179)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:158)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Liquibase.runInScope(Liquibase.java:2405)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Liquibase.update(Liquibase.java:211)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Liquibase.update(Liquibase.java:197)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Liquibase.update(Liquibase.java:193)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:142)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:130)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34832$migrate_BANG___34837$fn__34838$fn__34839.invoke(setup.clj:68)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.liquibase$fn__30491$do_with_liquibase__30496$fn__30497.invoke(liquibase.clj:59)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.liquibase$fn__30491$do_with_liquibase__30496.invoke(liquibase.clj:51)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34832$migrate_BANG___34837$fn__34838.invoke(setup.clj:63)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34832$migrate_BANG___34837.invoke(setup.clj:40)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34891$run_schema_migrations_BANG___34896$fn__34897.invoke(setup.clj:121)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34891$run_schema_migrations_BANG___34896.invoke(setup.clj:115)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34943$setup_db_BANG___34948$fn__34949$fn__34952$fn__34953.invoke(setup.clj:147)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.util$do_with_us_locale.invokeStatic(util.clj:715)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.util$do_with_us_locale.invoke(util.clj:701)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34943$setup_db_BANG___34948$fn__34949$fn__34952.invoke(setup.clj:145)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34943$setup_db_BANG___34948$fn__34949.invoke(setup.clj:144)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db.setup$fn__34943$setup_db_BANG___34948.invoke(setup.clj:138)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db$setup_db_BANG_$fn__34978.invoke(db.clj:65)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:60)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.db$setup_db_BANG_.invoke(db.clj:51)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:98)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core$init_BANG__STAR_.invoke(core.clj:81)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core$init_BANG_.invokeStatic(core.clj:138)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core$init_BANG_.invoke(core.clj:133)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core$start_normally.invokeStatic(core.clj:150)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core$start_normally.invoke(core.clj:144)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core$_main.invokeStatic(core.clj:183)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core$_main.doInvoke(core.clj:177)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at clojure.lang.RestFn.invoke(RestFn.java:397)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at clojure.lang.AFn.applyToHelper(AFn.java:152)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at clojure.lang.RestFn.applyTo(RestFn.java:132)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at metabase.core.main(Unknown Source)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at java.lang.reflect.Method.invoke(Method.java:498)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::v43.00-044::noahmoss:
**FINEST|15212/5|Service yajsw|22-05-19 14:20:15|     Reason: liquibase.exception.DatabaseException: FEHLER: could not open relation with OID 17210 [Failed SQL: (0) DELETE FROM permissions_group WHERE name = 'MetaBot']**
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:696)
INFO|wrapper|Service yajsw|22-05-19 14:20:15|executed script: scripts/trayMessage.gv 1
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56)
INFO|wrapper|Service yajsw|22-05-19 14:20:15|executed script: scripts/trayMessage.gv 1
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.lambda$child$0(Scope.java:180)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:189)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:179)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:158)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.lambda$child$0(Scope.java:180)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:189)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:179)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:158)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:243)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.lambda$child$0(Scope.java:180)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:189)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:179)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:158)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:243)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.Scope.child(Scope.java:247)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	... 51 more
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|Caused by: liquibase.exception.DatabaseException: FEHLER: could not open relation with OID 17210 [Failed SQL: (0) DELETE FROM permissions_group WHERE name = 'MetaBot']
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:397)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83)
INFO|wrapper|Service yajsw|22-05-19 14:20:15|executed script: scripts/trayMessage.gv 1
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:151)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1279)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1261)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:661)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	... 71 more
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|Caused by: org.postgresql.util.PSQLException: FEHLER: could not open relation with OID 17210
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
INFO|wrapper|Service yajsw|22-05-19 14:20:15|executed script: scripts/trayMessage.gv 1
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|	... 76 more
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|2022-05-19 14:20:15,718 INFO metabase.core :: Metabase Shutting Down ...
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|2022-05-19 14:20:15,718 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
FINEST|15212/5|Service yajsw|22-05-19 14:20:15|2022-05-19 14:20:15,718 INFO metabase.core :: Metabase Shutdown COMPLETE
INFO|wrapper|Service yajsw|22-05-19 14:20:16|too many restarts 
INFO|wrapper|Service yajsw|22-05-19 14:20:16|too many restarts 
INFO|wrapper|Service yajsw|22-05-19 14:20:16|calling onStop
INFO|wrapper|Service yajsw|22-05-19 14:20:16|Win service stop - timeout: 30000
INFO|wrapper|Service yajsw|22-05-19 14:20:16|Win service wrapper.control -> stopping application
INFO|wrapper|Service yajsw|22-05-19 14:20:16|Win service stop - after shutdown
INFO|wrapper|Service yajsw|22-05-19 14:20:16|Win service stop - before notify
INFO|wrapper|Service yajsw|22-05-19 14:20:16|Win service terminated

Can anyone spot the problem?
**Thanks!**

**Comment by elements92** [comment]
Hi @flamber ,
when I execute the statement, I don't get an entry.
How can I solve the problem?

**Comment by flamber** [comment]
@elements92 Are you sure you are querying against the database that Metabase uses?
Then try to manually run this query on Postgres:
```
DELETE FROM permissions_group WHERE name = 'MetaBot'
```

**Comment by elements92** [comment]
@flamber : Yes it is the Metabase-DB. In the permissions_group there is a group "MetaBot" (Where does this come from?), but unfortunately I can't delete it:
Error message:
ERROR:  FEHLER:  could not open relation with OID 17210
SQL state: XX000

Is the connection in another table? Do you have another idea?

**Comment by flamber** [comment]
The "MetaBot" is group was a special system group tied to an old Slack feature, which was hidden in 0.42 and the last parts of it was removed in 0.43.

The error you are seeing is because your Postgres database is corrupted - otherwise it should error with some constraint message if there's relations blocking the delete:
https://dba.stackexchange.com/questions/246618/getting-error-could-not-open-relation-with-oid-6701547-while-performing-vacuum

You should really fix your Postgres, but if you are unable to do that, you might be able to get it working by doing this:
Go to the table `databasechangelog.id='v43.00-044'` and set `exectype='MARK_RAN'` (or EXECUTED)
Alternatively start Metabase with without auto-migration, which will tell you all the queries that needs to be executed:
https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_db_automigrate
It's important to note that having an application database that does not match what Metabase expects can lead to more trouble.

Closing this, since there isn't anything Metabase can do to fix problems in Postgres.

**Comment by elements92** [comment]
@flamber: Last question: I can't find the entry v43.00-044 in the database. For me it only writes up to version v43.00-043 in the table. Can I somehow delete this in the jar file so that the user "Metabot" simply remains?
Thx

**Comment by flamber** [comment]
@elements92 I would recommend that you dump your Postgres database to SQL. Delete the database. Then restore from SQL.
Make sure you have backups.
Otherwise setup Metabase on a new application database and copy the migration row, or do the alternative approach like I mentioned previously https://github.com/metabase/metabase/issues/22837#issuecomment-1131830767

But you database is corrupted - you should fix that.

**Comment by elements92** [comment]
Okay Thx!
