### ISSUE TITLE
I18N: links on managing alerts not localized

### ISSUE THREAD

**Issue by FeaRiTail** [metabase/metabase#22835]
**Describe the bug**
On any given dashboard click on the "manage alerts" (for receiving mails/slack-messages).
The area which slides in contains 2 links which are only "partially" localized.
The part before the A-tag is localized correctly, the link itself is not.

**Logs**
Not applicable as it´s GUI related.

**To Reproduce**
See above: When viewing a dashboard click on "manage alerts/mails".

**Expected behavior**
Also the label of the link should be localized.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1950101/169279353-bc79c4e3-4926-4b1c-8697-2bb904ef7c46.png)

**Information about your Metabase Installation:**
- Metabase version: 0.43.1, resp. 1.43.1
- Metabase hosting environment:  Jar-file

**Severity**
Cosmetical/consistency, not really "critical" in sense of "system breaks", obviously.

**Comment by mazameli** [comment]
Thanks for filing this, @FeaRiTail. I've merged a fix, which will ship in the next version of Metabase.
