### ISSUE TITLE
[Actions] Add support for Card `is_write` to API endpoints

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#22845]
Part of #22542 

Once #22844 is in place we need to add the new `is_write` column to Saved Question endpoints as described in https://github.com/metabase/eng-tech-designs/blob/custom-actions/docs/custom-actions.md#is_write

1. Add support for `is_write` to Saved Question endpoints:
   1. `GET /api/card/:id` should return `is_write`. Other endpoints may need to return this as well
   1. `POST /api/card` and `PUT /api/card/:id` should be updated to handle `is_write`
      1. Only admins should be allowed to set this for the time being
      1. Setting this for a Saved Question belonging to a Database that does not support the `:actions/custom` feature
         should result in an error
      1. Only native questions should be allowed to be `is_write` for the foreseeable future. Setting this for a
         non-native query should result in an error.
      1. When a card is set to `is_write` an associated `QueryAction` and `Action` should be inserted. When `is_write` is set to false, any associated `QueryAction` or `Action` should be deleted.

**Comment by snoe** [comment]
@camsaul Should we disallow readwrite on models (`dataset=true`)? I'm not sure why we would make have a readwrite model and persistence would throw a big wrench in this.

**Comment by camsaul** [comment]
@snoe yeah I think we should disallow readwrite on models. That makes sense

**Comment by camsaul** [comment]
Implemented by #22904
