### ISSUE TITLE
[Actions] Add Emitter CRUD Endpoints and Models

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#22851]
Part of #22542

   For convenience for this first pass I think we can go ahead and define CUD endpoints that create/edit/delete an
   Emitter and EmitterAction at the same time and make the fact that they're separate objects transparent to the frontend
   client. For this first prototype I think it's ok to pretend that Emitter:Action is a 1:1 relationship for the time
   being. In the future when we want to support better action reuse we can make this a little more complicated in
   whatever way is appropriate.

   I think a shape like this for `POST` and `PUT` should work for now.

   ```clj
{:card_id            10
    :action_id          4
    :parameter_mappings {"id" [:template-tag "id"]}
    :viz_settings       {:title "Extend Trial"
                                  :color "#009900"}}
   ```

   1. `POST /api/emitter` to create a new Emitter and associated EmitterAction. This should create the new  Emitter mapping (either `card_emitter` or `dashboard_emitter`, as well as `emitter` and
      `emitter_action`).
   1. `PUT /api/emitter/:emitter-id` to update an existing Emitter/EmitterAction pair as appropriate.
   1. `DELETE /api/emitter/:emitter-id` to delete an existing Emitter (delete `emitter_action`, `emitter`, and `dashboard_emitter` or `card_emitter` rows)

**Comment by snoe** [comment]
Fixed by https://github.com/metabase/metabase/pull/22876
