### ISSUE TITLE
[Actions] Add a toggle in the frontend Saved Questions UI for enabling or disabling `is_write`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#22856]
Part of #22542

Issue to add support on the backend to API endpoints is #22845

1. Add a toggle in the frontend Saved Questions UI for enabling or disabling `is_write`.
   1. `is_write` toggle should only be visible when the global `experimental-enable-actions` flag is enabled and
      when the Database in question has the `database-enable-actions` flag

**Comment by kdoh** [comment]
Closed by #22952
