### ISSUE TITLE
Some properties are not showing on Google Analytics.

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#22884]
Properties encircled below are not showing on Metabase

![image](https://user-images.githubusercontent.com/89201548/169814001-19513464-a64f-48eb-8339-0dd87fa4b797.png)

Here is my config for the Google Analytics
![image](https://user-images.githubusercontent.com/89201548/169814947-09ea1632-5d04-4e3b-8f88-8e0dc77bce97.png)

I already set the permission of the service account to "Viewer" but it is still not showing.

**Expected behavior**
It should show all properties.

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1078-azure",
    "user.language": "en",
    "user.timezone": "Asia/Manila"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": "Asia/Manila"
    }
  }
}

**Comment by flamber** [comment]
Metabase currently only supports GAv3 and Web properties. Closing in favor of #11396 and #12905
