### ISSUE TITLE
12th week repeated on x-axis

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2288]
*  I am using the Chrome browser.
*  My computer's OS is El Capitan.
*  My database is PostgreSQL.
*  My Metabase version is v0.16.0.

When graphing a line or bar time series for This Year, grouped by week, if the browser window is larger than 1370px, the 12th week label is incorrectly duplicated on the x-axis:

![screen shot 2016-04-01 at 11 44 34 am](https://cloud.githubusercontent.com/assets/2223916/14216775/7088b400-f7ff-11e5-960f-4759f21fc0b0.png)

![screen shot 2016-04-01 at 11 44 15 am](https://cloud.githubusercontent.com/assets/2223916/14216798/82c794c4-f7ff-11e5-8a6a-bf182746d7fd.png)

![screen shot 2016-04-01 at 9 19 45 am](https://cloud.githubusercontent.com/assets/2223916/14216680/effbea3c-f7fe-11e5-82bd-e18ef2cc6679.png)

**Comment by tlrobinson** [comment]
@mazameli Having trouble reproducing this. Can you give me more details or link to a saved question on one of our instances?

**Comment by tlrobinson** [comment]
Seems like this is related to timezones as I can't reproduce on the sample dataset on H2 and it goes away if I change the report timezone to UTC.

**Comment by mazameli** [comment]
![timezones](https://cloud.githubusercontent.com/assets/2223916/14222092/7f6bd106-f821-11e5-9e7c-b3b4f13af143.png)
