### ISSUE TITLE
Quick filter applies incorrect week range to query

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2289]
*  I am using the Chrome browser.
*  My computer's OS is El Capitan.
*  My database is PostgreSQL.
*  My Metabase version is 0.16.0

Starting from a time series query that had the This Year filter applied and was grouped by week, in Raw Data mode I clicked on one of the weeks to try to apply a time filter to narrow my data down to just that week.

![screen shot 2016-04-01 at 11 59 31 am](https://cloud.githubusercontent.com/assets/2223916/14217302/10fe7652-f802-11e5-9fd9-6dc14e22e817.png)

![screen shot 2016-04-01 at 12 04 00 pm](https://cloud.githubusercontent.com/assets/2223916/14217303/142f0e72-f802-11e5-89c3-c9ef93ef52f7.png)

When I clicked `=`, the filter that was applied was this:
![screen shot 2016-04-01 at 11 59 50 am](https://cloud.githubusercontent.com/assets/2223916/14217317/2261e5be-f802-11e5-897d-8b23cda2fc29.png)

What I expected was this:
![screen shot 2016-04-01 at 12 00 40 pm](https://cloud.githubusercontent.com/assets/2223916/14217331/2e907ee0-f802-11e5-82de-fa0c985b87a6.png)

**Comment by tlrobinson** [comment]
I'd call this more of a limitation. The quick filter needs an overhaul. It was a prototype that got included because it was useful enough as is, but there are a bunch of cases like this it doesn't handle well.

**Comment by mazameli** [comment]
Hmm, I'd still classify it as a bug because it seems to promise to do one thing, but does a different, unexpected thing. If it's a feature that hasn't been built, then I'd propose we shouldn't show the quick filter menu in situations where we can't yet apply the filter correctly, like with weeks it seems.

**Comment by salsakran** [comment]
I'd classify this as a bug we should fix as part of a systemic overhaul rather than a one-off

**Comment by mazameli** [comment]
Cool. Where's the overhaul label…? 👹

**Comment by camsaul** [comment]
This might be a Correctness issue.
