### ISSUE TITLE
Better approach for long strings in deferred translation macros

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#22897]
The `deferred-tru` and `deferred-trs` translation macros aren't easy to use for long strings that don't fit nicely on a single line. Our current approach on the backend is to break a string into multiple parts, call `deferred-*` on each one, and then concatenate the parts using `str`. For example, this is done in a couple of setting descriptions, like `site-locale`: https://github.com/metabase/metabase/blob/5e1037eadf8bb57d86079da06a6ae0857db2a560/src/metabase/public_settings.clj#L139-L141

However, this causes the translation to happen immediately when the code is executed, defeating the point of a deferred translation. This manifests as a bug: if you start up Metabase, then change your language, the description for this setting in the admin panel won't be changed. It also means that the text is sent to translators in chunks, which might not work well for certain pieces of text, which require the surrounding text for context.

We should adjust these macros to have some capability to support splitting long strings over multiple lines, while keeping the deferred translation mechanism intact.

**Comment by flamber** [comment]
Isn't this a duplicate of #10770?

**Comment by noahmoss** [comment]
@flamber yep, hadn't seen that one, thanks
