### ISSUE TITLE
Blank data when in dashboard, but if the question is selected the supposed to be chart is showing.

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#22908]
Here is my question when viewing in dashboard.

![image](https://user-images.githubusercontent.com/89201548/169999418-ae1c9dce-256f-40f8-a7f9-d0d0e55adc63.png)

But when the question is opened here is my view:

![image](https://user-images.githubusercontent.com/89201548/169999690-b85f2feb-b8b6-4856-94bc-d8185f5892d0.png)

Another issue is some questions are not showing on bar chart.

![image](https://user-images.githubusercontent.com/89201548/170008302-ce601d30-be6c-48f0-bb2b-b32d9ebdf56b.png)

When I try to select row chart, below is my view:

![image](https://user-images.githubusercontent.com/89201548/170008512-436d6ea2-2db5-43a2-9795-d3adc5fcfa26.png)

Aside from that, there is also alignment issue (the one encircled). 
DB used: MongoDB

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10-Ubuntu-0ubuntu0.18.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1078-azure",
    "user.language": "en",
    "user.timezone": "Asia/Manila"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": "Asia/Manila"
    }
  }
}

**Comment by flamber** [comment]
Hi @jrca025 

It's not possible to reproduce anything with the limited information you are providing.
You would need to include the question metadata `/api/card/:id` and the question results `/api/card/:id/query`, and also on the dashboard. Look in your browser developer Network tab to see the requests.

Try resetting the dashboard card to defaults. Edit the dashboard, hover the card, select visualization options, reset to defaults.

How did you end up with empty bars on questions you created 4 months ago? Your underlying data must have changed, so it does not return values for the dates.

Your row chart looks like it doesn't have an X-axis column selected.

You should migrate away from H2 if you are using Metabase in production: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Comment by jrca025** [comment]
Hi @flamber 
It is now resolved after upgrading to latest version.
