### ISSUE TITLE
metabot websocket closing / getting rate-limited

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#2292]
Testing out the new metabot integration in metabase 0.16 today.

Love it so far, but it seems to be very unreliable - I think the reason for this is because the token that is generated per the documentation is:

1. Just a test token, so not tied to a Bot User
2. Is actually a user token so conflicts with desktop app and causes disconnects

In terms of the unreliability, upon enabling metabot integration I receive these error messages in the log over and over every second.
```
04-01 22:41:22 ERROR metabase.metabot :: Error connecting websocket: Read timed out
04-01 22:41:23 DEBUG metabase.metabot :: MetaBot WebSocket is closed.  Reconnecting now.
```

Eventually, I also got rate-limited by Slack due to the reconnects:
```
04-01 22:14:46 ERROR metabase.metabot :: Error connecting websocket: clj-http: status 429
04-01 22:14:47 DEBUG metabase.metabot :: MetaBot WebSocket is closed.  Reconnecting now.
```

I think the integration needs to be an official [bot user](https://api.slack.com/bot-users) set up at this link: https://my.slack.com/services/new/bot

I did this and used the token provided during that process. But in doing so, I noticed that metabot didn't respond to `@metabot: ` mentions, only `metabot` without the @ mention.

**Comment by salsakran** [comment]
@camsaul what's our reconnect frequency? We should definitely have an exponential backoff to keep from getting slapped by rate-limits.

**Comment by camsaul** [comment]
Ya we're not doing any kind of exponential backoff. There's a supervisor thread that monitors the websocket connection every second and attempts to open it if it's closed, pretty simple

I haven't seen it run into cases where we get rate-limited, usually it succeeds in opening the websocket connection and only needs to periodically re-open it

**Comment by agilliland** [comment]
@dacort Where are you running your Metabase instance when you are seeing this behavior?  In development we've been running this off servers in AWS as well as off some laptops and we've been able to keep the websockets open without too much issue.

**Comment by dacort** [comment]
@agilliland This is on an AWS instance. I'm not sure what the reason for the disconnect was, possibly because I'm using the same token as my personal account? Once I created a specific "bot" account per Slack documentation, the issue stopped happening as much.

**Comment by jasonmadrid** [comment]
We're experience this 100% of the time.  The metabot integration will work in Slack for a short time, but eventually we're blocked.

**Comment by salsakran** [comment]
@dacort + @jasonmadrid are you using a bot token or a test token?

**Comment by dacort** [comment]
@salsakran Initially I was using a test token, but then I switched over to a bot token and it's been working just fine ever since.

**Comment by salsakran** [comment]
cool, #3257 makes that the official Party Line.

**Comment by salsakran** [comment]
I'm pretty sure this is alleviated by #3257, @jasonmadrid if you find otherwise, please re-open this.

**Comment by timiyay** [comment]
We're having similar issues causing the Slackbot to drop out, though I'm uncertain whether this issue is the cause. I've jumped onto https://github.com/metabase/metabase/issues/3965 for now, to chase it up
