### ISSUE TITLE
3rd dimension on graphs

### ISSUE THREAD

**Issue by marcos-pratikos** [metabase/metabase#2293]
Is there a way of having a 3rd dimension on graphs, like this example from Tableau?
![metabase_3dimension](https://cloud.githubusercontent.com/assets/18106370/14227719/2ab6cd64-f8da-11e5-8160-ac3c403352b0.png)

There's 3 dimensions, 1 for row, 1 for column and 1 for color.

**Comment by agilliland** [comment]
Yes, this is a stacked bar chart and this is possible in Metabase right now if you write a SQL question that outputs 3 columns.

For example something like ...

```
SELECT created_at::date as day, count(*) as count, count(distinct id) as uniques
FROM user
GROUP BY day
ORDER BY day
```

**Comment by MrMauricioLeite** [comment]
Is there a way for the end user do the same without any SQL?
