### ISSUE TITLE
handle table names with / in them (postgres)

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#2295]
we have tables in one database with slashes in their names, eg `foo/bar_baz` (no clue why, legacy, ¯\\\_(ツ)\_/¯), which metabase doesn't like. when i try to query them, it complains:

```
ERROR: missing FROM-clause entry for table "bar_baz" Position: 8
```

looking at the log, the query is eg:
```
SELECT "bar_baz"."value" AS "value", "bar_baz"."table_key" AS "table_key", "bar_baz"."scope_key" AS "scope_key", "bar_baz"."id" AS "id"
FROM "public"."foo/bar_baz"
```

metabase 0.16.1 from jar on AWS, ubuntu 14.04, against postgres 9.3.10 on RDS. browser is firefox 45 on mac os x.

**Comment by agilliland** [comment]
related to #2137

**Comment by camsaul** [comment]
This is basically the same issue as #2137 so I'm going to close this as a duplicate and add the info from this ticket to that one.

**Comment by snarfed** [comment]
sgtm, thanks!
