### ISSUE TITLE
Exploring the first row using the link on the PK (uuid) with postgres does not work.

### ISSUE THREAD

**Issue by sebasortiz-dev** [metabase/metabase#22960]
**Describe the bug**
When you click the link on the PK in the first row to the result, (we're using UUIDs as PK) fails with message.

We're a little lost...
The page you asked for couldn't be found.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to any table
2. Click on the PK of the first row

I also was able to reproduce the same error when clicking on the "pk" of foreing keys from the "detail" a row.

**Expected behavior**
Show the detail of the row

**Screenshots**

Navigate to first row using UUID pk

![2022-05-25-155239_1349x279_scrot](https://user-images.githubusercontent.com/74673391/170365444-77af88f9-8ad3-41b3-a46c-79ce97d872c1.png)

See error

![2022-05-25-155245_1947x1333_scrot](https://user-images.githubusercontent.com/74673391/170365485-8e9eb554-dfa2-41c7-88b9-af572f8f9cf6.png)

The link on the browser is this.  `.../question?objectId=538ec3d4-35d9-4902-8522-0ef0a7ebe9bb#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjQ2fX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==`

The same behaviour when navigatin using the FK links, in this case the "origin_account ID"

![2022-05-25-160004_1940x660_scrot](https://user-images.githubusercontent.com/74673391/170366368-cd3edd54-4739-41b3-b57b-bd36a3eb10c9.png)

The link `..../question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzQsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsNzEsbnVsbF0sIjI5NjUxMzg1LTRlMDMtNDQ0MS1hOWM0LTRhMDg1Yzc1NzVkOSJdXX0sInR5cGUiOiJxdWVyeSIsImRhdGFiYXNlIjoyfSwiZGlzcGxheSI6Im9iamVjdCIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==`

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 100
- Your operating system: Linux
- Your databases: Postgres
- Metabase version: 0.43.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Is really annoying not being able to navigate the data using the PK links. I'd say this bug is really important, but is not "critical"

**Additional context**
I think it started happening in the 0.43.0 update.

**Comment by paoliniluis** [comment]
You're seeing https://github.com/metabase/metabase/issues/22768

**Comment by sebasortiz-dev** [comment]
@paoliniluis just updated to 0.43.2 and the issue is still there.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "4.14.256-197.484.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-31",
      "tag": "v0.43.2",
      "branch": "release-x.43.x",
      "hash": "433d533"
    },
    "settings": {
      "report-timezone": "America/Bogota"
    }
  }
}
```

**Comment by flamber** [comment]
@sebasortiz-dev #22768 is still open. It has not been fixed yet. When that issue is fixed, then it will be closed with a milestone.
