### ISSUE TITLE
Date filter selection from the chart footer is glitchy and results in wrong selection

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#22973]
**Describe the bug**
Selecting a date filter from the footer date selector can result is "misclick" and the wrong selection.

**Logs**
N/A

**To Reproduce**
1. Open Products table
2. Summarize > Created At (by month)
3. The chart will show "All Time by Month" in the footer
4. Popover appears with the "All Time" filter in the `select` menu (correct behavior which was fixed in #22308)
5. Click on the select menu and choose "Previous" from the list of filters
![image](https://user-images.githubusercontent.com/31325167/170509261-bbea6577-7a0a-437b-aaed-355e528e733c.png)
6. The selection should now say "Previous 30 days"
7. Click Apply
8. The footer is updated to "Previous 30 Days by Month"
9. Click on the "Previous 30 Days" in the footer
10. Click on the "Previous" `select` menu
![image](https://user-images.githubusercontent.com/31325167/170509812-5f284cfb-f0f7-4503-b7be-4712c888146d.png)
11. Choose "All Time" from the list of all filters
12. The selection changes from "All time" back to "Previous 30 days"

**Expected behavior**
1. Popover shouldn't be visibly "jumping" around while it renders into its final position (this is aside) but the main thing is
2. Whichever filter one selects it should be applied

**Screenshots**
Video recording:
https://user-images.githubusercontent.com/31325167/170510522-6fab57c6-b3cc-4b00-b372-6f5daf04e489.mov

**Information about your Metabase Installation:**
local dev, `master, abe3a3f1031a642bb58ee6a2d98d12aa696823cf, H2, Sample Database

**Severity**
P3 but really annoying and it makes Cypress tests flaky as a side-effect

**Additional context**
[Slack thread](https://metaboat.slack.com/archives/C01RFQL2KPC/p1653480082723269)

Related to #22247, and in more broader sense to #18951

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/pull/35718/files
