### ISSUE TITLE
Adding attributes manually remove users from groups

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#22983]
**Describe the bug**
When adding attributes manually to a user, the user gets removed from all groups

**Logs**
No BE logs

API calls:
Create a user (it will get a user id of 2)
1) Add user to group (POST /api/permissions/membership) with {"user_id":2,"group_id":3} as the payload
2) Then add the properties (PUT to /api/user/2) that goes with the following payload: {"first_name":"bb","last_name":"aa","email":"b@c.om","user_group_memberships":[{"id":1,"is_group_manager":false}],"login_attributes":{"somekey":"somevalue"}} 
3) then there's a get immediately to /api/permissions/membership but the permission are gone
{"1":[{"membership_id":1,"group_id":1,"user_id":1,"is_group_manager":false},{"membership_id":2,"group_id":2,"user_id":1,"is_group_manager":false}],"2":[{"membership_id":3,"group_id":1,"user_id":2,"is_group_manager":false}]}

**To Reproduce**
1) Settings->admin settings->people -> groups
2) create a group
3) go to people and invite a user
4) add the user to a group
5) then go to the user details and add an attribute. See the error

**Expected behavior**
Group permissions should be kept when adding or modifying a user property

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.43.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
Don't think that many people assign attributes manually

**Additional context**
NA

**Comment by flamber** [comment]
I cannot reproduce following the steps or doing browser refreshes in case it's there's some frontend state issue.
Either the steps are not exact or some local browser caching is involved.

**Comment by paoliniluis** [comment]
Issue was the disable caching was enabled 
![image](https://user-images.githubusercontent.com/1711649/172263408-63ae24b3-bac9-435a-bcd3-b4961effbaba.png)
