### ISSUE TITLE
After filtering a model once, subsequent filters in notebook mode doesn't respect display names

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#22987]
**Describe the bug**
When filtering a model, the display names and FK are respected.
![image](https://user-images.githubusercontent.com/32561114/170553688-aae647a6-49ae-40f0-b8e6-317e3beb9c14.png)

After adding one filter, the metadata is ignored (it doesn't use display names and disable FK filters)
![image](https://user-images.githubusercontent.com/32561114/170553865-547cb7a6-9fa1-4848-abe2-a6bec56e2de9.png)

**To Reproduce**
1. Open any model with metadata like [this](https://stats.metabase.com/model/4694-hosting-insights-users)
2. Filter `is_active` = `true`
3. Filter again anything
4. See the bug

**Expected behavior**
Use metadata always

**Information about your Metabase Installation:**
Stats on master

**Severity**
This makes models less useful and annoying

**Comment by flamber** [comment]
I cannot reproduce. I'm guessing you didn't refresh #22518.
