### ISSUE TITLE
Unexpected behavior when reordering columns in models

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#22988]
**Describe the bug**
When ordering columns, the column doesn't stay where it is expected

https://www.loom.com/share/7625857b914a4c32bb43a73fc653caf4

**Expected behavior**
Keep the order that the user defines

**Severity**
Annoying to reorder columns

**Comment by flamber** [comment]
I'm guessing that #22521 is in play, since the columns seems to be selected/reordered based on index instead of field reference.

**Comment by dpsutton** [comment]
@luizarakaki the posted loom video is just a blank white screen for me.
