### ISSUE TITLE
Updating data permissions counts questions as tables

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#22984]
**Describe the bug**
Helpful modal that asks are you sure you want to edit data permissions for a certain group apparently counts all saved questions as tables.

**Logs**
N/A

**To Reproduce**
1. Have at least a few saved questions first
2. Go to data permissions for all users `/admin/permissions/data/group/1`
3. Change permissions for Sample Database from Unrestricted to No Self-service
4. Modal appears and it warns you that you are about to give/revoke access to 4 + x tables in the Sample Database (where x is the number of your saved questions)

![image](https://user-images.githubusercontent.com/31325167/170549600-1ed4b1a2-5d9d-4aab-bee7-3793292c9442.png)

**Expected behavior**
It should count only the actual tables, which in the case of the Sample Database is only 4

**Information about your Metabase Installation:**
local dev, `master`, abe3a3f1031a642bb58ee6a2d98d12aa696823cf, H2, Sample Database

**Severity**
P3 if this is only a UI thing.

**Comment by flamber** [comment]
Sounds similar to #22071
