### ISSUE TITLE
Notifications: Webhook channel

### ISSUE THREAD

**Issue by Addvilz** [metabase/metabase#2298]
Would be nice to have a Pulse endpoint that is a simple POST request on preset URL (many preconfigured in admin, one could be chosen per pulse). This way we could integrate custom stuff all over the place and really expand the ecosystem allowing for non-official pulse endpoints.

Advanced version: URL's set in Admin with placeholders. In Pulse setup, whoever is creating the pulse can fill out placeholders, if any.

Data: Base64 encoded image wrapped in JSON along with all the metadata available? Perhaps, raw data used to render the graph as well?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment]
Yeah a "webhook" pulse integration would be great, and not too difficult.

**Comment by FesonX** [comment]
Is there any development guide for webhook plugins like community drivers?(Take Sentry as a [example](https://docs.sentry.io/product/integrations/integration-platform/)) OR expose more detail information in API like Alert, so we can pull the data to implement the feature we want.

**Comment by JohannesFerner** [comment]
Is there a possibility to sponsor / set bounty on the resolution of this issue or https://github.com/metabase/metabase/issues/9966?

**Comment by hendinejad** [comment]
Is there any update regarding this question?

**Comment by YaoWang-Pony** [comment]
Any updates about this?

**Comment by lawrencegs** [comment]
> Is there a possibility to sponsor / set bounty on the resolution of this issue or #9966?

Ditto on this. Is there a possibility to sponsor / set bounty on the resolution of this issue or https://github.com/metabase/metabase/issues/7298

**Comment by aindong** [comment]
looking forward into this

**Comment by Avey777** [comment]
Will webhook functionality be planned? Or will it only be available in the enterprise version?

**Comment by pseudostave** [comment]
We'd also be v keen to see this done and/or MS Teams integration.

**Comment by qnkhuat** [comment]
This is planned to be shipped in 51. Stay tuned!
Epic: https://github.com/metabase/metabase/issues/43822
