### ISSUE TITLE
Permission error before finishing referencing a question in the native query

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#22991]
**Describe the bug**
If I don't have permission to access question 469 and I do have permission to access question 4696, I get a permission error before having the chance to type the entire question number.

https://www.loom.com/share/8340b103094241238380f5b6952c675f

It is possible to just paste the full reference and keep going.

**To Reproduce**
In the Loom video

**Expected behavior**
The user should be able to continue typing the full question number.

**Screenshots**

**Information about your Metabase Installation:**
Stats on master

**Severity**
Not too severe, as there is a workaround

**Comment by uladzimirdev** [comment]
I cannot reproduce the issue in 49.18 and lastest master 2c8bf0f8aa

**Comment by ranquild** [comment]
@uladzimirdev this issue was fixed here https://github.com/metabase/metabase/pull/40785/files#diff-b9a99116808513e348f328c0aca0ef57bb0e4dd295e54d0e9bf20c8dd0e32eeeR20 by making sure we pass `noEvent` to RTK query
