### ISSUE TITLE
[Bulk Filters] Weird behavior on nested questions

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#22992]
**Describe the bug**
Bulk filters work really nice on basic tables, but the things get a bit confusing when we start applying them on the nested questions. The initial picker shows fields from the base table but the "tab" is not highlighted. If you switch to any of the implicitly joined tables, it is then impossible to choose any of the fields from the base table.

**Logs**
N/A

**To Reproduce**
1. Open Orders table and save it as a question "Q1"
2. New question > Saved Questions > Q1
3. Click "Visualize" to go to the simple mode
4. Click `...` next to the Filter which will open a bulk filter editor
5. Notice that no tab is selected, although all fields listed belong to the "Orders" table
![image](https://user-images.githubusercontent.com/31325167/170567111-8f4245d0-ddbd-4764-87e4-45c331dcba1f.png)
6. Click on any of the implicitly joined tables (User, Product)
7. It is now impossible to filter "Orders" directly from this modal
![image](https://user-images.githubusercontent.com/31325167/170567687-29ccd085-7a98-49b5-bd43-c36f0e9ea80f.png)

Close the modal and repeat the step 4. again to be able to apply filters to "Orders"

**Expected behavior**
It can be tricky to "mark" the base table in the nested question, but at least provide the "Default" or the "Base" tab so that it's possible to:
1. know which fields do you filter on
2. come back to the base table filters

**Information about your Metabase Installation:**
local dev, `master`, adacc7ed5866e33df88aba381580028cc5cb0991, H2, Sample Database

**Severity**
P3

**Comment by iethree** [comment]
resolved by https://github.com/metabase/metabase/pull/23216
