### ISSUE TITLE
Filters are taking 100% viewport width on mobile/tablet in v.43.1

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#22996]
After upgrading to v1.43.1, I noticed each filter is taking 100% width of the viewport on mobile/table (tested on iPhone and iPad):

**Before:**

![Metabase](https://user-images.githubusercontent.com/15974735/170773394-f4da2676-bde5-4c73-b69a-826a0dd34c7e.jpg)

**After:**

![sfdc2](https://user-images.githubusercontent.com/15974735/170779985-7a7610a3-3c0c-48cb-9ecf-18c2f982099b.jpg)

Our business users mostly use iPad/mobile for viewing data in Salesforce (where we have sign-embedded Metabase), and this new change makes it hard for them to see the data.

I suggest the "100% width" gets applied only if the viewport cannot fit more than one filter. 

v1.43.1

**Comment by flamber** [comment]
It's not really a bug. It was the design choice to fix other issues #21848. But sticky filters are not optimal anymore #22229.

**Comment by vvaezian** [comment]
I see. This has negative impact on user experience though, as it would take a big portion of the screen when the filters are more than a few (we usually have around 8 filters).

**Comment by vvaezian** [comment]
@flamber Updated the ticket.
