### ISSUE TITLE
Filter Sidebar Persists Filter Values across fields

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#23002]
**Describe the bug**
When creating a filter from the filter sidebar, filter values persist even when the user doesn't "add" that filter - leading to some nonsensical inputs

**To Reproduce**
1. Go to the products table
2. open the filter sidebar
3. select category field
4. select "doohickey"
5. don't "add filter", instead just click back
6. select ID field
7. see that "doohickey" is a pre-filled value for the ID column

**Expected behavior**

I would expect that an unapplied filter would be cleared out when pressing back

**Screenshots**

https://user-images.githubusercontent.com/30528226/170730297-03e5233f-6fca-4866-a9fc-701e4847e3f8.mov

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Mobile Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "18.0.1+0",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "18.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "18.0.1+0",
    "os.name": "Mac OS X",
    "os.version": "12.4",
    "user.language": "en",
    "user.timezone": "America/Denver"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-05-25",
      "src_hash": "f1237962a4f60fb975e8ec1d8f869b349ecc3327",
      "tag": "v0.43.1-SNAPSHOT",
      "branch": "smart-field-order",
      "hash": "fccd58b"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Annoying, but easy to work around.

**Comment by flamber** [comment]
As far as I know, this is a feature, so you could easily switch between columns with the value being carried over.

**Comment by iethree** [comment]
closing this 
1) because the filter sidebar doesn't exist anymore and
2) we're addressing this in another way here: https://github.com/metabase/metabase/issues/34960#issuecomment-1776208539
