### ISSUE TITLE
Models does not respect the Metadata column name, but shows the underlying Data Model name instead

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23019]
**Describe the bug**
Models does not respect the Metadata column name, but shows the underlying Data Model name instead.
Seems to also occur on drill-through and a couple of other places. This can make it very confusing, when there's 4 different ID or Name columns.

**To Reproduce**
1. Question > Sample > Reviews - join Products
![image](https://user-images.githubusercontent.com/1447303/170824729-b2171205-d8c5-4e0b-a6a3-dda8197ae591.png)
2. Save question and turn into Model (customize the Metadata column names if you want of the Products table)
3. Add the Model to dashboard and add a filter (ex Number) and show the card connections
![image](https://user-images.githubusercontent.com/1447303/170824836-b842395d-2214-4edc-9ddc-432fca157339.png)
4. Save the dashboard, do a browser refresh
5. Edit the dashboard and try to connect the filter again - it now shows the Data Model (not Models Metadata) name
![image](https://user-images.githubusercontent.com/1447303/170824912-c063a0d1-d1bf-4779-91dc-7d79c539cbbf.png)

**Expected behavior**
Respect the Model Metadata column name.

**Information about your Metabase Installation:**
Tested 0.43.1

**Additional context**
Very likely related to #20624 and #20419. And perhaps to #22518 too, since it seems like a browser state, which is resolved on refresh.

**Comment by qnkhuat** [comment]
Hi @gusaiani, I'm trying to debug this and I'm still seeing the `GET /api/card/:id` API returns the metadata for models correctly.

I also see FE call 2 queries to get metadata for 2 tables separately, I'm not sure what FE uses this for but hopefully, this is a pointer.
<img width="2125" alt="Screen Shot 2022-08-15 at 23 49 38" src="https://user-images.githubusercontent.com/25661381/184679398-f80d285d-8804-4d91-9e38-9074ed7def6a.png">

Could you help me check if this could be fixed entirely on FE?
I'm happy to help if BE is needed.

**Comment by daltojohnso** [comment]
Fixed by https://github.com/metabase/metabase/pull/25109
