### ISSUE TITLE
Models with explicit joins shows duplicates of all fields in sidebar and selectors

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23018]
**Describe the bug**
Models with explicit joins shows duplicates of all fields in sidebar and selectors.

**To Reproduce**
1. Question > Sample > Reviews - join Products
![image](https://user-images.githubusercontent.com/1447303/170824648-26458b25-fbc1-4e0c-909f-bfa186835265.png)
2. Save question and turn into a Model
3. Do a browser refresh #22518
4. On the Model, open sidebar Filter or Summarize, or go to Notebook
![image](https://user-images.githubusercontent.com/1447303/170824618-f8adaad8-d3ae-4849-9ff1-bb9055ea40c4.png)

**Expected behavior**
Do not show duplicate fields.
Not sure how Models should handle implicit joins, but I'm guessing it should be similar to normal tables.

**Information about your Metabase Installation:**
Tested 0.43.1

**Comment by qnkhuat** [comment]
This looks like a FE bug, I created a question and a model with the exact query, their result_metdata are pretty much the same.

Tried to flip the dataset flag on the model and it works just fine.

**Comment by daltojohnso** [comment]
I suppose the solution here is to hide the dimensions from implicit joins if the query already contains the join.
