### ISSUE TITLE
Trend Zero Data Misleading

### ISSUE THREAD

**Issue by kav** [metabase/metabase#23029]
**Describe the bug**
When using the trend visualization on a series over time the trend box continues to show the last value rather than 0. 

**To Reproduce**
In a data source create a table with

| Created  |
| :-----------|
| 5/1/2022   | 
| 5/8/2022  |
| 5/9/2022  |
| 5/15/2022 | 
| 5/16/2022 | 
| 5/16/2022 | 

and then visualize with a Trend over count of created at by week

Trend will show 3 even though we'd expect zero.

**Severity**
It's not that bad as we know what's happening but it does make our dashboards feel a untrustworthy. The reality is I'd prefer we solve it by not having periods with zeros in my dataset but some things we can control, and some we can't... I can probably work around it by tweaking the query as well but it seems like the general untrustworthiness is worth addressing

**Comment by flamber** [comment]
Hi @kav 
Include "Diagnostic Info" from Admin > Troubleshooting, so it is possible to know which database you are using.
I cannot reproduce. I'm guessing it's a timezone or start-of-week problem, but without more details, then it's difficult to tell.

**Comment by kav** [comment]
If it helps my data is timestamp with tz in postgres. I'd assume the same, the metabase server is UTC and the report timezone is null, except I'm seeing it over multiple week boundaries.

Most telling is that the table view shows the last row as 

| Created | count |
| ----------| -----:|
| May 8 2022 - May 14 2022 |  5| 

and the Trend shows

> 5
> Nothing to compare for the previous week.

Which seems like maybe I'm just missing a zero fill option? Like if I just join to weeks ending in today and coalesce in zeros for nulls I'll get what I expect.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.3+6-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "17.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.3+6-LTS",
    "os.name": "Linux",
    "os.version": "4.14.275-207.503.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-16",
      "tag": "v0.43.1",
      "branch": "release-x.43.x",
      "hash": "7f1a1c4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
@kav I think you need to provide the DDL and data, since I cannot reproduce and don't understand what the problem is.
You say `Trend will show 3` in the first post and then `the Trend shows 5` in the second post.

**Comment by kav** [comment]
The bug I'm seeing is; when using trend visualization over a count of records grouped by created week if no records were created in the last several weeks the trend shows the count of the last week for which the value wasn't zero (unexpected) rather than zero (expected).

Sorry for the confusion on count; it's three in the initial example because that's the last non-zero count in the simplified example I gave. It's five in my actual data because that, in my actual data, is the last non-zero count of records for a week.

Are you seeing differently in attempting to reproduce? Your trend number is showing zero when the count of records created this week is zero?

I can provide the ddl and relevant data or build out a min repro somewhere accessible but I see it when using the trend visualization over count of records over a Postgres `time stamped with tz` field grouped by week where the current week count is zero.

**Comment by flamber** [comment]
Okay, so this is #8919. The problem is "last" should be "previous".

**Comment by Bilbottom** [comment]
If I understand this correctly, I don't think this is a Metabase problem -- in fact, I'm glad that Metabase _doesn't_ assume what the 'current' time is and instead determines is from the result set, otherwise that could lead to other bugs and issues

In this case, the solution is to just set up a date axis that adds a row for the missing intervals. This is good practise anyway, not just the 'fix' for the Metabase trend option

Not sure how easy it would be for you to set up a date axis with the Metabase UI (you might need to create a calendar table to help with this), but the SQL alternative is easy:
```
WITH
    RECURSIVE dates AS (
            SELECT CAST('2022-05-02' AS DATE) AS report_date
        UNION ALL
            SELECT CAST(report_date + INTERVAL '1 week' AS DATE)
            FROM dates
            WHERE report_date < '2022-05-23'  /* This would be `CURRENT_DATE` in a production query */
    ),
    raw_data AS (
        SELECT
            create_date::DATE AS create_date,
            DATE_TRUNC('WEEK', create_date::DATE + INTERVAL '1 day') AS week_date
        FROM (VALUES
            ('2022-05-01'),
            ('2022-05-08'),
            ('2022-05-09'),
            ('2022-05-15'),
            ('2022-05-16'),
            ('2022-05-16')
        ) AS v(create_date)
    )

SELECT
    report_date,
    COUNT(raw_data.create_date) AS volume
FROM dates
    LEFT JOIN raw_data
        ON dates.report_date = raw_data.create_date
GROUP BY dates.report_date
;
```

**Comment by kav** [comment]
Yes except the metabase query is actually an aggregation over database data so I could manually join in zeros as suggested but the correct fill will vary based on the generated analytics metric. So yes it is "just" a manual edit of the generated metric query. But why? Why not join or coalesce the zero in in the default generated query? It's less work for users and doesn't yield invalid statements in the visualizations.

I believe I mentioned that above but it seems like "a count of x over date" metric in meta base should appropriately zero fill which as noted above is the issue.
