### ISSUE TITLE
Most graphs in dashboards not loading when using custom certs because connection pool is rotated constantly

### ISSUE THREAD

**Issue by phuhl** [metabase/metabase#23034]
**Describe the bug**
When building a dashboard with more than two graphs with my own postgresql DB (not happening on sample DB), the dashboard most of the time only successfully loads one graph. The other ones keep loading forever.

**Logs**

[metabase js logs](https://github.com/metabase/metabase/files/8797822/metabase-log.txt)
[metabase-server-logs.txt](https://github.com/metabase/metabase/files/8797838/metabase-server-logs.txt) (extract, if more needed, let me know)

**To Reproduce**
Not sure what exactly is the issue but in general for us:
1. Create two questions for our own DB
2. Create Dashboard
3. Add the two questions
4. Save
5. Load dashboard
6. See it is not loading

**Expected behavior**
The dashboard should load or show an actionable error message.

**Screenshots**
Forever loading dashboard:
![image](https://user-images.githubusercontent.com/16835755/170980461-55433182-097f-4cd2-914c-5f48be25c499.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 100.0.1 (64-bit)
- Your operating system: Arch Linux
- Your databases: Postgres
- Metabase version: Metabase v0.43.1 (7f1a1c4 release-x.43.x) 
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Pretty severe: Brakes all our dashboards.

**Additional context**
This problem occured with Metabase version 0.43. We did not have the issue with 0.42.

We had the issue with, both, 0.43.0 and 0.43.1

**Comment by flamber** [comment]
Hi @phuhl 
Something is causing the pool to become invalidated constantly:
`WARN metabase.driver.sql-jdbc.connection Hash of database 2 details changed; marking pool invalid to reopen it`

This should normally only happen, when someone edit the data source (Admin > Databases > your-db), but can also occur, when there's a change in the application database table `metabase_database.details`
Not quite sure what is going on with your setup.
Could you post the content of `metabase_database.details`, while only redacting host, user and password? It's important that you don't redact too much, since it would otherwise make it difficult to reproduce.

You are saying that this happens only on dashboards? If you try to view the question directly, then it works? And if you try to make a new question, then it works?

A possible workaround, go to Admin > Databases > your-db and click "Save changes" without making changes. This should re-save everything again.

**Comment by phuhl** [comment]
Hi @flamber,

sorry for the late response, I needed to find a time window where I could reapply the update.

This is the content of `metabase_database.details`. I also redacted the dbname, but it is just a few lower case letters, not any reserved name (let's say it is "mydbname").

```
{"ssl-use-client-auth":false,"ssl":true,"password":"***","ssl-root-cert-options":"uploaded","port":5432,"advanced-options":false,"dbname":"***","ssl-root-cert-creator-id":null,"host":"***","tunnel-enabled":false,"ssl-root-cert-source":null,"ssl-root-cert-id":1,"ssl-root-cert-created-at":"2022-04-25T19:15:50.285291Z","user":"***","ssl-mode":"verify-ca"}

{"db":"zip:/app/metabase.jar!/sample-database.db;USER=GUEST;PASSWORD=guest"}

```

> You are saying that this happens only on dashboards? If you try to view the question directly, then it works? And if you try to make a new question, then it works?

It only happens on dashboards. All questions run without any issue on their own (I checked all of them). I also can make new questions without issue. They work, too. Also: As described above, one question usually does work on the dashboard. But it is not always the same question that works. But the one question that eventually loads does feel considerably slower that when they all worked.

> A possible workaround, go to Admin > Databases > your-db and click "Save changes" without making changes. This should re-save everything again.

I did this. It still does not work, but the `metabase_database.details` entry changed:

```
{"db":"zip:/app/metabase.jar!/sample-database.db;USER=GUEST;PASSWORD=guest"}

{"ssl-use-client-auth":false,"ssl":true,"password":"***","ssl-root-cert-options":"uploaded","port":5432,"advanced-options":false,"schema-filters-type":"all","dbname":"***","ssl-root-cert-creator-id":1,"host":"***","tunnel-enabled":false,"ssl-root-cert-source":null,"ssl-root-cert-id":1,"ssl-root-cert-created-at":"2022-06-01T07:12:22.502316Z","user":"***","ssl-mode":"verify-ca"}
```

**Comment by flamber** [comment]
@phuhl Thank you for the details - I'll try to reproduce. Not quite sure what is going on yet.

**Comment by dpsutton** [comment]
I see in the details the `ssl-root-cert-created-at` has changed
`"ssl-root-cert-created-at":"2022-06-01T07:12:22.502316Z"`
`"ssl-root-cert-created-at":"2022-06-01T07:26:06.490452Z"`

If this keeps changing it will consider the details "changed" and want to reconfigure the pool with new details. I'm still trying to verify if this attribute is considered when we get the details to hash them to see but that's the thread I'm going to investigate.

**Comment by phuhl** [comment]
Hey, just wanted to share one more pice of info, I just found out:

As you could see, I had the database SSL settings like this (apparently a setting, seldomly used, as no one else seems to face the issue):

![image](https://user-images.githubusercontent.com/16835755/172683365-479dbcbd-2e59-47d3-970b-0ed9571640a6.png)

When changing the setting to this:

![image](https://user-images.githubusercontent.com/16835755/172683067-d72c5e16-5cbc-4b3f-b44d-f6cc3a968364.png)

it all works.

While I'd prefer to have the certificate checked, I will use this workaround for now :+1:

**Comment by flamber** [comment]
@phuhl I've reproduced and know several others hitting this, so we want to fix this. Still not sure what triggered the problem on 43, but there were a lot of connection changes since 42.
Nice to know you got a workaround, but that might not work for others that require a custom root cert (for compliance reasons).

**Comment by dpsutton** [comment]
So this has to do with out handling of secrets. We hash the database details and if the hashes differ, we consider the details changed so we have to restart the connection pool. The annoying bit is that the `details` are identical:

```clojure
connection=> (= x y)
true
```

Our issue is that we include secrets (like `java.io.File`s in here):
```clojure
connection=> (take 2
                   (clojure.data/diff (connection-details->spec :postgres (:details x))
                                      (connection-details->spec :postgres (:details y))))
({:sslkey
  #object[java.io.File 0x141b0f09 "/var/folders/1d/3ns5s1gs7xjgb09bh1yb6wpc0000gn/T/metabase-secret_1388256635324085910.tmp"],
  :sslrootcert
  #object[java.io.File 0x6f443fac "/var/folders/1d/3ns5s1gs7xjgb09bh1yb6wpc0000gn/T/metabase-secret_9248342447139746747.tmp"],
  :sslcert
  #object[java.io.File 0xbb13300 "/var/folders/1d/3ns5s1gs7xjgb09bh1yb6wpc0000gn/T/metabase-secret_17076432929457451876.tmp"]}
 {:sslkey
  #object[java.io.File 0x6fbb3b7b "/var/folders/1d/3ns5s1gs7xjgb09bh1yb6wpc0000gn/T/metabase-secret_18336254363340056265.tmp"],
  :sslrootcert
  #object[java.io.File 0x6ba4c390 "/var/folders/1d/3ns5s1gs7xjgb09bh1yb6wpc0000gn/T/metabase-secret_11775804023700307206.tmp"],
  :sslcert
  #object[java.io.File 0x320184a0 "/var/folders/1d/3ns5s1gs7xjgb09bh1yb6wpc0000gn/T/metabase-secret_10098480793225259237.tmp"]})
```
