### ISSUE TITLE
Filter values in dropdown are not showing up for model based dashboard

### ISSUE THREAD

**Issue by gajanand-jm** [metabase/metabase#23055]
**Describe the bug**
We're using a Metabase model (based on a SQL query) to create a dashboard. After updating the metadata, we're able to use fields as dropdown filters but we've to manually type the filter values (also for that one needs to know the correct values). Ideally, Metabase should show all values in the dropdown.

**To Reproduce**
1. build a model based on a SQL query (no field filter in the query)
2. use the above model to create a dropdown category filter on a dashboard (even for the field that has 3 unique values only)
3. we don't see any values but have to manually type the whole value

**Expected behavior**
The dropdown filter should show all values the field has - users should be able to select one or more values

**Screenshots**
![image](https://user-images.githubusercontent.com/91305327/171204427-bc457a42-fe4f-4c4e-a2c8-68a58f7216ed.png)

**Severity**
It's medium I'd say since users aren't even able to use a basic filter which is one of the basic requirements for most dashboards if not all. It's blocking us from using the dashboard in quite a few cases and forcing us to create multiple questions/reports for different filers which is not scalable and the right way to build dashboards

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_111-internal-alpine-r0-b14",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_111-internal",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.111-b14",
    "os.name": "Linux",
    "os.version": "5.4.149-73.259.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "presto-jdbc",
      "h2",
      "athena",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.42.3",
      "date": "2022-03-23",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}
```

**Comment by johnmaxwell** [comment]
We are having this issue too. 

We've built a SQL-based model of our transaction history. This model has a field called "segment" that is assigned by some complex logic in the model's SQL and doesn't map cleanly to a column in a table.  Segment will be either A or B. 

<img width="347" alt="image" src="https://user-images.githubusercontent.com/13686/186756264-432999a7-f990-4324-8a05-f3f13fa15846.png">

We've got question based on this model that that summarizes the sums the transaction history month-over-month. We've added this question to a dashboard.

We've added a segment dashboard filter filter to this dashboard. This filter _does_ work to filter the the results as expected, but it requires the the user type in A and/or B to work. What we'd expect is to have a way to populate A and B as unchecked options in the select dropdown that the user can optionally engage.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/13686/186757419-4623a59b-6675-439c-820b-7467d7e5c384.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/13686/186757521-2643667a-547b-4ac9-8af0-ade7b496102d.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/13686/186757152-f3fbb1a6-e7fd-4545-8fef-3c0283c5f389.png">

Any ideas? Is this supported and we're not doing it right or is it just not supported?

One alternative is to manually input A and B as defaults in the filter field that can be de-selected. But once removed, the user will need to add them back.

Is there another way to accomplish this? That is, provide a visible list of selectable/deselectable list of options for the users that is user-friendly.

**Comment by flamber** [comment]
@johnmaxwell You need to map the field in the model metadata, otherwise Metabase doesn't know how to show a dropdown. See the issues I already referenced or #5245

**Comment by johnmaxwell** [comment]
Thanks @flamber ! Are you saying that I should use this field in our metabase model? 

<img width="332" alt="image" src="https://user-images.githubusercontent.com/13686/187291999-cb129d15-305d-4b75-8a2c-236f80c0cf3c.png">

If so, I'm confused about what I would put here. The value of "segment" doesn't map to a particular column. Instead a segment is assigned by conditional logic within the SQL query that Metabase model is based on. In other words, it is a synthesis of the underlying data that the model abstracts; there is no segment A or segment B coming from a column in a table.

Is it accurate to say that what I'm trying to do isn't supported right now?

**Comment by flamber** [comment]
@johnmaxwell It's not supported currently, it would require some of the issues that I have referenced.

**Comment by johnmaxwell** [comment]
Thank you @flamber !
