### ISSUE TITLE
White background in pivot tables

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#23072]
Hello,

When a pivot table is added to a dashboard displayed in full screen in night mode then the background of the pivot table remains white and makes reading the data unreadable.

- Metabase 0.43.2
- Firefox 100
- Chromium 92

![image](https://user-images.githubusercontent.com/4558101/171339510-190913da-f05d-4441-8ea3-e1f2ef2cfd6f.png)

**Comment by flamber** [comment]
Historically fixed #14364, but something must have broken it again.
