### ISSUE TITLE
Frontend incorrectly sustitutes datetime field incorrect in Pivot Table

### ISSUE THREAD

**Issue by amureki** [metabase/metabase#23076]
**Describe the bug**

Pivot-table summarization is changing the month from May to January when you switch to German locale.
So, for example, in English locale, I see "**Totals for May, 2022**".
German locale will show me "**Summen für Jan., 2022**", which is clearly wrong.

**Logs**
I think, logs are not related here, but I am putting suspect code lines:

https://github.com/metabase/metabase/blob/6ee3474c32affb75089c612850df11703c0dcb16/locales/de.po#L17792-L17794
https://github.com/metabase/metabase/blob/6ee3474c32affb75089c612850df11703c0dcb16/frontend/src/metabase/lib/data_grid.js#L386-L396

**To Reproduce**
1. Create a report with pivot-table visualization that uses datetime field as one of the rows and has May as a value
2. Switch locale to German in the user settings
3. See error

**Expected behavior**
Line should be saying "Summen für Mai., 2022"

**Screenshots**

English version:
![CleanShot 2022-06-01 at 15 44 01](https://user-images.githubusercontent.com/627183/171419267-60478280-a11f-486e-a445-7dea0afe44c6.png)

German version:
![CleanShot 2022-06-01 at 15 42 30](https://user-images.githubusercontent.com/627183/171418930-d65ae81e-cca2-4d17-8860-be41edcb4109.png)
**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_332-heroku-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_332-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.332-b09",
    "os.name": "Linux",
    "os.version": "4.4.0-1103-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2 (Ubuntu 14.2-1.pgdg20.04+1+b1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.43.2",
      "date": "2022-05-31",
      "branch": "release-x.43.x",
      "hash": "433d533"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**

This is affecting our reports, as the main working language for us is German (majority of our Metabase users see the reports in German language)

**Additional context**

I am happy to try to provide a patch if I'd be pointed to a right direction on how this could be solved. If you experienced similar issues, maybe showing the PRs etc. would be also helpful if you are open to external contributions!

Best,
Rust

**Comment by flamber** [comment]
@amureki Makes it a lot easier, when it's reproducible in Sample, thank you for that.

Okay, so this is some javascript rendering problem, which only applies to Chrome-based browsers.
I have a feeling that it's not just Pivot Table, but likely more general.

Some languages are even worse. Tested 0.41.7 thru 0.43.2, which all causes the same problem.

Firefox - everything is correct
![image](https://user-images.githubusercontent.com/1447303/171863888-e5d0bbe6-0de9-4e6f-8642-d4ea42903306.png)

Chrome German
![image](https://user-images.githubusercontent.com/1447303/171864056-ba1e581a-85d7-4be5-a57b-0e9af2645bbd.png)
Chrome French
![image](https://user-images.githubusercontent.com/1447303/171864590-e7c4f721-1062-495f-8bc6-1fef9ccc6cdc.png)

**Comment by amureki** [comment]
@flamber @nemanjaglumac @ranquild thank you for the great work over here! Looking forward to the next release! 👍 👍
