### ISSUE TITLE
Long values in Number visualization is cut off

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23093]
**Describe the bug**
Long values in Number visualization is cut off. It's mostly a problem on smaller screens.
Regression since 0.43.0 by #21003 (#2552) - historically #12629

**To Reproduce**
1. Native > Sample > `select {{text}}` with Text variable, input `abc` in filter widget and run - save as "Q1"
2. Native > Sample > `select {{number}}` with Number variable, input `123` in filter widget and run - save as "Q2"
3. Add Q1 (18x3), and Q2 twice (5x3 and 5x5) to the dashboard.
4. Add three filters (Q1 Text:Dropdown, Q2a Number:Equal and Q2b Number:Equal) and connect to cards
5. Text `Awesome dymanic title, which shows the most awesome thing`, Number `123456789` and Number2 `123456789012345`
1920x1080
![image](https://user-images.githubusercontent.com/1447303/171494295-67cce8b6-33b3-4f49-91e2-06797f3276cf.png)
Mobile
![image](https://user-images.githubusercontent.com/1447303/171495228-fecf0af4-bc45-439a-9c80-02738da18305.png)

**Expected behavior**
This is 0.42.4 - it should always show the number, or create the humanize
![image](https://user-images.githubusercontent.com/1447303/171495497-6730add3-00f6-4f91-adb1-a5773510ed9e.png)
![image](https://user-images.githubusercontent.com/1447303/171495643-620419e8-4c51-4b01-a990-93ef089b840f.png)

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.43.2

**Comment by burgoyn1** [comment]
I'd like to add to this, under visualization options it would be awesome to have a "size" option with "auto" as the default, then a custom option which allows to select set our own sizes in either px or em.
