### ISSUE TITLE
Reverting model back to the saved question results in an error (displayed on page)

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#23108]
**Describe the bug**
Reverting model back to the saved question results in an error. This is especially problematic since "An error occurred" is displayed on page which we should never ever do.

**Logs**
The error is `id: 'value must be an integer.'` and it's shown in three places in the console.

1. api.js, line 199
`GET /api/revision?entity=card` responds with status code 400 and `errors: {id: 'value must be an integer.'}`

2. `react_devtools_backend.js:4026 Request entities,revisions_list,{"model_type":"card"},fetch failed: {status: 400, data: {…}, isCancelled: false}`

3.
```
EntityLink.jsx:35 Uncaught (in promise) 
{status: 400, data: {…}, isCancelled: false}
data: {errors: {…}}
isCancelled: false
status: 400
[[Prototype]]: Object
```

**To Reproduce**
1. Open "Products" table
2. Save as a question
3. Convert to a model
4. Revert back to the saved question
5. "An error occurred" is now displayed in the sidebar and the console shows the revision history error
![image](https://user-images.githubusercontent.com/31325167/171643570-7c8323fd-26d7-42df-99b9-9daccf2890ed.png)
6. It seems that the model was indeed turned into a question, which we can confirm opening it (`dataset` is set to `false`)
7. However, trying to turn this question back into a model will only result in more errors

**The problem is that I cannot reproduce this reliably neither locally, nor on stats. Not sure why but this non-deterministic behavior makes the problem even worse, imo.**

These alternative steps to reproduce seem to be more reliable.
1. Open "Products" table
2. Save as a question
3. Convert to a model
4. Edit the query and add Filter (e.g. Rating is equal to 3) > Save the changes
5. Now turn the model back into a saved question
6. No error (yet) and the filter is still applied
![image](https://user-images.githubusercontent.com/31325167/171645384-5bb2a433-9ab3-4f24-90cc-5af279cf6d6a.png)
7. Click on `X` to remove the filter or update the filter in any other way (change the value, change it to "Less than")
8. Now the error appears
![image](https://user-images.githubusercontent.com/31325167/171645967-b992b030-f559-4ead-a428-8cd64e7b083b.png)

**Expected behavior**
1. It should always be possible to convert the model back to a saved question without any errors
2. We should never display an error message on the screen

**Information about your Metabase Installation:**
local dev, master, https://github.com/metabase/metabase/commit/97026720e5b3fba31843af0125646a0a293616e3, H2, Sample Database

**Severity**
Probably a P1 since the core functionality of a feature is broken.

**Comment by iethree** [comment]
I believe this was fixed by sidebar work in 44.0 https://github.com/metabase/metabase/pull/24520

@npfitz can you confirm?
