### ISSUE TITLE
Build metabase from the source

### ISSUE THREAD

**Issue by rohit-guitar** [metabase/metabase#2311]
I want to build the release 0.16.1 from the github branch. can I get instructions on it ?. As 0.16.1 have the fixes for the sql server. 

Thanks

**Comment by agilliland** [comment]
You can take a look at our contributors guid, which has information about building from source .. https://github.com/metabase/metabase/blob/master/docs/developers-guide.md

**Comment by rohit-guitar** [comment]
Thanks let me look into it and start working on it.

**Comment by camsaul** [comment]
@rohit-guitar if you just want 0.16.1 for the SQL Server fixes, like previous versions [it is available for download from metabase.com](http://www.metabase.com/start/). Downloading the pre-built Mac App or JAR is the easiest route unless you have specific reasons necessitating building from source.

**Comment by rohit-guitar** [comment]
Got it Thanks
