### ISSUE TITLE
Archived cards and dashboards still appear in the "Pick up where you left off" homepage section

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#23114]
**Describe the bug**
If you create a dashboard/card, view it, and then archive it, it'll still show up on the homepage under "Pick up where you left off" and you can click on it to access its contents.

**Expected behavior**
I assume that if a question/dashboard is archived, it's not useful to still suggest that someone visit it from the homepage. 

I also _think_ that there's no any other direct way to access an archived entity via the UI, so this seems like it shouldn't be allowed either.

**Information about your Metabase Installation:**
Current master

**Severity**
Mild

**Comment by calherries** [comment]
Noah and I cannot reproduce this anymore, so I'm closing this as fixed
