### ISSUE TITLE
Admin Alert Panel

### ISSUE THREAD

**Issue by cam-working** [metabase/metabase#23121]
**Is your feature request related to a problem? Please describe.**
I cannot easily find all questions that have alerts set on them from all users.

**Describe the solution you'd like**
In the admin section, a panel showing all alerts with simple actions like delete or edit.

**Describe alternatives you've considered**
Current workaround is creating questions with naming convention attached, sometimes these are duplicates of existing dashboard questions for ease of use.
 
**How important is this feature to you?**
As we scale the size of our data it is highly important to be able to efficiently manage and edit alerts.

**Comment by flamber** [comment]
It is implemented in Audit: https://www.metabase.com/docs/latest/enterprise-guide/audit.html#subscriptions--alerts
