### ISSUE TITLE
[Actions] Return column specific error messages when possible from CRUD and Emitter actions

### ISSUE THREAD

**Issue by snoe** [metabase/metabase#23126]
Part of #22542 

It’d be awesome if the BE could follow a similar response structure we have for other POST/PUT endpoints. For instance:
```
POST /api/actions/row/create

400: Bad Request

{
  "data": {
    "message": "Some problem that's not related to a specific field",
    "errors": {
      "password": "Should be longer than 6 characters",
      "full_name": "Is required"
    }
  }
}
```

Not sure if it’s an easy thing to do, I guess atm the BE just returns the whole error string coming from the driver (example below), so I’d appreciate your feedback on that one
`ERROR: null value in column \"id\" violates not-null constraint\n  Detail: Failing row contains (null, hello, null, null, null, null, null, null, null, null, null, null, null, null).`

- [ ] CRUD actions
- [ ] Emitter actions

**Comment by kulyk** [comment]
@escherize I suppose we can close that one now?
