### ISSUE TITLE
Click Behavior not working for Gauge or Progress

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23137]
**Describe the bug**
This might be a closer to a feature request, but since we're allowing to set Click Behavior for Gauge and Progress (others?) visualizations on the dashboard, then this makes it a bug.

**To Reproduce**
1. Question > Sample > Orders - summarize Count - change to Gauge visualization - save as "Q1"
2. Question > Sample > Orders - summarize Count - change to Progress visualization - save as "Q2"
3. Add both questions to a dashboard, hover the cards > Click Behavior > set some destination (not important where), save dashboard
4. Click anywhere (expect the title) of Q1 Gauge - nothing happens
5. Click anywhere (expect the title) of Q2 Progress - it shows normal drill-through actions
![image](https://user-images.githubusercontent.com/1447303/171847177-d94304f2-2ac6-4e39-98fe-e7a28868b605.png)

**Information about your Metabase Installation:**
Tested 0.41.7 thru 0.43.2

**Additional context**
Related to #9549 and #14760

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by RedTiger26** [comment]
Is there any estimate possible when this issue will be fixed? We are currently setting up several nested dashboards for our sales reps and key account managers and do need that functionality.
