### ISSUE TITLE
Column description feature does not work as expected.

### ISSUE THREAD

**Issue by diesel-yh-lee** [metabase/metabase#23133]
**Describe the bug**
Hi! team. I filled column comments at `Admin > Data model > my_table` and confirm that displayed at `Home > Browse data > my_table`. But when I defined `my_table` using question as table visualization, any descriptions where not displayed right place. 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/33506430/171778408-074e7fbd-e255-4338-8c3e-1261b600326c.png">

After track server response via chrome `dev tool>network` traffic monitor, I noticed that response body is not identical for each scenario as attached below(See screenshot of **Logs** section).

**Logs**
For security reason, I masked and attached screenshot of each cases.

**Case 1** : Response JSON body screenshot of table style pannel. Description attribute does not exists.
<img width="622" alt="image" src="https://user-images.githubusercontent.com/33506430/171778863-99bf7f8f-d2fb-47c0-8c85-7a4113bd93e8.png">

**Case 2** : Response JSON body screenshot of `Home > Browse data > my_table`. Description attribute exists. 
<img width="532" alt="image" src="https://user-images.githubusercontent.com/33506430/171778818-c79bf936-4713-4b17-b424-943cef1ca475.png">

**To Reproduce**
1. Give comment for some table field.
2. Confirm that comment are displayed at `Admin > Data model > my_table` and `Home > Browse data > my_table` and `question that visualized as table`

**Expected behavior**
Column comments must displayed expected place if user defined comment for column.

**Screenshots**
-

**Information about your Metabase Installation:**
- Chrome 102.0.5005.61
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: MySQL
- Metabase version: 0.43.2
- Metabase hosting environment: AWS EKS
- Metabase internal database: MySQL

**Severity**
Low

**Additional context**
- Display_name attribute matters too. but I skipped screenshots for that.

**Comment by flamber** [comment]
Hi @diesel-yh-lee 
The Data Model will only reflect on GUI based questions, or if using Models with a mapped field.
Your "case 1" shows it's a SQL query.
There's a Sample Database, which you should use if you don't want to disclose your own metadata or results.
