### ISSUE TITLE
Relative filter preview dates does not account for Start of Week setting

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23142]
**Describe the bug**
Relative filter preview dates does not account for Start of Week setting. Confusing. The results are correct.

**To Reproduce**
1. Admin > Settings > Localization > First day of the week = Monday
2. _we don't have any current data, but this is a frontend issue, the correct data is filtered, so just open a filter "Past 1 week"_
![image](https://user-images.githubusercontent.com/1447303/171875053-dd1608fe-2c17-4a31-b3e0-28e437cf1ccf.png)

**Information about your Metabase Installation:**
Only tested 0.43.2, since there were other problems previously with the relative preview.

**Comment by gitstart** [comment]
@gusaiani Pushed a [PR](https://github.com/metabase/metabase/pull/24088) with fix. Could you please review?
