### ISSUE TITLE
Pagination appears and then disappears when using the filter

### ISSUE THREAD

**Issue by LinQian173** [metabase/metabase#23161]
**Describe the bug**
Pagination appears and then disappears when using the filter

**To Reproduce**
1. view all the data in the table and can see the "Rows..." on the bottom right
2. filter one field
3. check the pagination

**Expected behavior**
show the total of rows without displaying the pagination when all data can be displayed on one page.

**Screenshots**
![QQ20220606-162151-HD](https://user-images.githubusercontent.com/68947140/172129764-8c9f240d-41d7-465c-99da-34c42da97239.gif)
<img width="609" alt="image" src="https://user-images.githubusercontent.com/68947140/172135860-f422fc5d-56ed-44ad-aaf3-82d65b3d5c5c.png">
<img width="608" alt="image" src="https://user-images.githubusercontent.com/68947140/172135900-e5d767c8-da7a-4685-97f8-a6ff80ef9e2c.png">
<img width="605" alt="image" src="https://user-images.githubusercontent.com/68947140/172135938-dace04da-cd14-4efa-ac06-21f733413a9a.png">

**Information about your Metabase Installation:**

- browser and the version: chrome, Version 101.0.4951.64 (Official Build) (x86_64)
- Your operating system: MacBook Pro (16-inch, 2019)
- Metabase version:  v0.43.1

**Comment by flamber** [comment]
Hi @LinQian173 
Post "Diagnostic Info" from Admin > Troubleshooting.
And use the Sample Database to provide steps-to-reproduce with sample data.

**Comment by LinQian173** [comment]
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.11.0-1028-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by LinQian173** [comment]
https://user-images.githubusercontent.com/68947140/172347024-190e60ac-6183-4c47-80e2-0641cd292963.mp4

**Comment by flamber** [comment]
Metabase will not show pagination, when there's less results than can fit into the table size

https://user-images.githubusercontent.com/1447303/172362696-16f1afac-5e08-4023-87eb-0fd46376e729.mp4
