### ISSUE TITLE
[Actions] Support click thru from column to specific "detail view" Dashboard

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#23174]
Part of #22542

We want to be able to use specific Dashboards as the "detail view" for a particular column rather then the current detail view. 

We should be able to click thru from a column to a specific "detail view" Dashboard, passing the value of that column as a parameter. Example: 

1. I create a "User Detail" Dashboard with a User ID parameter
2. I go in to a particular Saved Question somewhere and edit viz settings to map the User ID column to this Dashboard
3. When I click a specific User ID in the results it should take me to the "User Detail" Dashboard and set that User ID as the Dashboard's User ID parameter

I don't know what exactly this entails but it sounds like we already support custom targets as click thru actions for specific columns and we just need to extend that stuff to be able to take the value of a column and pass it as a parameter to the custom target (?)

**Comment by salsakran** [comment]
This doesn't quite capture what I was saying, 
the idea was that instead of there being a single "detail view", we'd use [customer destinations](https://www.metabase.com/learn/dashboards/custom-destinations) to decorate an ID column to send the user to a dashboard

**Comment by salsakran** [comment]
☝ @camsaul @kulyk @kdoh
