### ISSUE TITLE
Question white screen

### ISSUE THREAD

**Issue by DavyChang** [metabase/metabase#23191]
**Describe the bug**
After clicking on a question, the entire page is blank. Just one question, nothing else

**Logs**
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/22284587/172341604-2ab50a7f-dc74-4fb0-83e7-82bdab56258a.png">
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/22284587/172341667-7599d7c9-c6e8-46d3-9899-704d95b83dda.png">

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
