### ISSUE TITLE
Building from source 

### ISSUE THREAD

**Issue by rohit-guitar** [metabase/metabase#2320]
If this is a bug report, please fill in the blanks:

*  I am using the __chrome v49_________ browser.
*  My computer's OS is ___Mac OSX_10.11_______.
*  I'm running Metabase __Jar 0.16.1_________. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is __SQL server_________.
*  My Metabase version is __0.16.1_________.

I want to compile the source of metabase. It is getting stuck at this point. I am using mac osx 10.11. Please refer to the attached screenshot.
![snip20160405_1](https://cloud.githubusercontent.com/assets/5105736/14303550/9f1ad352-fb79-11e5-8c1d-cbf7f6d5c808.png)

I have just cloned the master and start doing the compilation. 

Thanks

**Comment by tlrobinson** [comment]
Is it actually stuck, or just taking a really long time? While npm v3 should work, it's about twice as slow as npm v2, and I believe all of our team is still using v2.

If it's really stuck I'd try using npm 2. You should be able to do `npm install -g npm@2`.

For reference, here are the versions of node and npm I'm currently using (but you shouldn't need these exact versions):

```
$ node -v
v5.9.1
$ npm -v
2.15.1
```

**Comment by rohit-guitar** [comment]
Excellent let me try that

**Comment by camsaul** [comment]
I'm using npm 3 and it's been working ok for me on days with no major unpublishing incidents

**Comment by agilliland** [comment]
@rohit-guitar were you able to get this resolved?

**Comment by rohit-guitar** [comment]
@agilliland :- I can build it. 
Thanks
