### ISSUE TITLE
i cant view data view in mysql with latest version

### ISSUE THREAD

**Issue by johnfelipe** [metabase/metabase#23219]
Pls review this video

https://drive.google.com/file/d/1jwXWOCKFWHqWgVdRzG1c8nmyNMESQMv7/view?usp=drivesdk

script sql used

https://gist.github.com/johnfelipe/13bfe26e7588ad92353e2bbf0e3f8554

**Comment by paoliniluis** [comment]
Hi @johnfelipe,
1) you're using an unsupported version of Metabase (0.44-SNAPSHOT is a still unreleased version, as it's the master branch that can have many errors and might be broken)
2) you haven't included any info about your environment, so we don't know how you're running Metabase, which App DB you're using or even which version is that MySQL you're trying to connect
3) we don't have any logs

I'll have to close this as we're lacking most of the info to identify the issue, please post all the info in our forums

**Comment by johnfelipe** [comment]
wich version in git pull is stable?
