### ISSUE TITLE
Cast and ceil/floor are available ?

### ISSUE THREAD

**Issue by siscia** [metabase/metabase#2321]
*  I am using the _Firefox_ browser.
*  My computer's OS is _Linux_.
*  I'm running Metabase _Docker_. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is _SQLite_.
*  My Metabase version is _v0.16.1_.

I am in the condition of aggregate some float values around some integer.

Number such 3.6,4.7,5.41,6.3 should go to 5, stuff like 23.3, 26.8, 27.1 -> 25

Usually I divide the number by an integer (the number depends on the grain of the scale, in the example above would be something like 5), i ceil (or floor) the number and I recast to integer.

Such are all operation permitted on most DBMS but I wasn't able to replicate on metabase, what I am looking for are function such `cast` and `floor` or `ceil`, are there available ?

**Comment by agilliland** [comment]
@siscia would you mind sharing an example of the SQL you would normally write to accomplish this?  that would help us understand the use case a bit better.

**Comment by camsaul** [comment]
@siscia [it doesn't look like SQLite understands the `cast`, `floor`, or `ceil` functions](http://www.sqlite.org/lang_corefunc.html).

**Comment by siscia** [comment]
@camsaul cast should be cover: https://www.sqlite.org/lang_expr.html#castexpr
With cast, then, you can cover both ceil and floor.
So the important one is cast

@agilliland , sorry for not replying as quickly as I would have liked, but we change data structure and the problem solve by itself bringing other priorities.
As camsaul pointed out there are not ceil and floor in sqlite nor are particularly necessary.

**Comment by camsaul** [comment]
@siscia are you talking about writing SQL queries or using the GUI query builder? Not every function available on every database is exposed in the query builder.

**Comment by camsaul** [comment]
Motion to close because this can't be implemented (:scream_cat:)

**Comment by camsaul** [comment]
Closing since ceil/floor aren't available on SQLite so we can't use them even if we wanted to
