### ISSUE TITLE
New Slack setup not working, because App isn't joining the files channel

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23229]
**Describe the bug**
Metabase is using the files channel name (ex `metabase_files`) in the request to Slack `/api/conversations.join`, but it needs to use the channel **ID** instead.
Seems like Slack might have changed something. Not even going to look in their changelog, since last time they didn't post anything.

**To Reproduce**
1. Do a new Slack setup on a workspace that doesn't have the App invited into the files channel already
The backend will error with:
```
clojure.lang.ExceptionInfo: Slack API error: channel_not_found {:error-code "channel_not_found", :message "Slack API error: channel_not_found", :response {:ok false, :error "channel_not_found"}, :url "https://slack.com/api/conversations.join", :request {:headers {:authorization "Bearer\n<SLACKTOKEN>"}, :as :stream, :conn-timeout 10000, :socket-timeout 10000, :form-params {:channel "metabase_files"}}}
    	at metabase.integrations.slack$do_slack_request.invokeStatic(slack.clj:125)
    	at metabase.integrations.slack$do_slack_request.invoke(slack.clj:106)
    	at metabase.integrations.slack$POST.invokeStatic(slack.clj:135)
    	at metabase.integrations.slack$POST.invoke(slack.clj:132)
    	at metabase.integrations.slack$fn__63385$join_channel_BANG___63390$fn__63391.invoke(slack.clj:267)
    	at metabase.integrations.slack$fn__63385$join_channel_BANG___63390.invoke(slack.clj:263)
    	at metabase.integrations.slack$fn__63410$upload_file_BANG___63415$fn__63416$fn__63417.invoke(slack.clj:282)
    	at metabase.integrations.slack$fn__63410$upload_file_BANG___63415$fn__63416.invoke(slack.clj:276)
    	at metabase.integrations.slack$fn__63410$upload_file_BANG___63415.invoke(slack.clj:269)
```

Doing a lookup on https://api.slack.com/methods/conversations.list/test and finding the files channel and using its ID (ex. `C1JPNN7RF`), then it's possible to fix it via https://api.slack.com/methods/conversations.join/test

**Information about your Metabase Installation:**
Seeing a lot of problems about this the past couple of days on multiple different versions including 43.2

**Comment by Nikhil1Raina** [comment]
> This was recently hit by @gusaiani while he was working on the private channel stuff for #23232. I've started to look into it, but essentially, my suspicion is also that Slack changed the `conversations.json` API to only accept channel ID, not name.
> 
> A temporary workaround: in your files channel, type `/` to open the Slack shortcuts menu and search for `Add apps to this channel`. Use this to add the Metabase app to the channel. After that, messages should be able to be sent with no issues.
> 
> @flamber potentially a p1? This basically means new Slack apps are broken unless admins use this workaround.

I find it pretty funny that despite integrating a bot or the Slack App in a channel, we kinda have to explicitly go out of the way to add it again as a "legitimate" member. Might as well remove the automation step and add it in the documentation to add it in a specific channel and then use its ID accordingly... 🤷🏼‍♂️
