### ISSUE TITLE
Custom Expression field is not respecting the modal size

### ISSUE THREAD

**Issue by diogormendes** [metabase/metabase#23223]
**Describe the bug**
The input field is bigger than the modal

**To Reproduce**
1. Go to 'new'
2. Click on 'question'
4. Choose a DB
5. Click on 'Pick the metric you want to see' over 'Summarize'
6. Click on 'Custom Expression'
7. See the error

**Expected behavior**
The input field should be within the modal borders

**Screenshots**

https://user-images.githubusercontent.com/17742979/172617443-84b36e76-6506-4e7f-b9b7-08db653cd968.mov

**The error is reproducible on:**

- Master branch '8eec37'
- x.43.2

**Comment by flamber** [comment]
Regression since 0.43.2 - likely caused by #23045
