### ISSUE TITLE
Ordering by timestamp in Querybuilder only orders by date not time

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#2323]
![image](https://cloud.githubusercontent.com/assets/8144392/14325678/ab22482c-fc2a-11e5-9185-158e36b89697.png)

The title and screenshot should say it all.

If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac.
*  I'm running Metabase AWS. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is Postgres.
*  My Metabase version is v0.16.1.

**Comment by agilliland** [comment]
Just to expand on this a little bit, the problem is that for a `:rows` type query the timestamp values are being cast to dates, which shouldn't be happening.

For example:  using the sample dataset if you select `Orders` the resulting SQL will be ...

```
SELECT "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."ID" AS "ID", CAST("PUBLIC"."ORDERS"."CREATED_AT" AS DATE) AS "CREATED_AT"
FROM "PUBLIC"."ORDERS"
LIMIT 2000
```

And this cast statement shouldn't be happening `CAST("PUBLIC"."ORDERS"."CREATED_AT" AS DATE) AS "CREATED_AT"`

**Comment by camsaul** [comment]
@agilliland is this on master? I changed that last week in #2306

**Comment by agilliland** [comment]
looks like it's working on staging and I remember you making that fix.  I know I just saw it happen in the last couple days, but that could have been me using an older branch that wasn't up to date.

In any case, I can't reproduce this right now, nor can I reproduce it on our v0.16.1 build.  

@robinfrick can you verify this again and confirm you are actually using the v0.16.1 release?  I'm having trouble reproducing this and we included a bug fix which should have resolved this in #2306

**Comment by robinfrick** [comment]
@agilliland yes. I'm running v0.16.1 and it's not working: In this example I order by the created column descending, and the date is fine but the times aren't in order.
![image](https://cloud.githubusercontent.com/assets/8144392/14486875/a7bbff5e-015f-11e6-8196-eb9245afac96.png)

**Comment by agilliland** [comment]
Hey @robinfrick so I've tried reproducing this a few times now and I'm still not able to get the same result that you are seeing.  I have a postgres db with hundreds of records per day and when I sort them by the datetime column they are coming back in the proper order without any issues.

Can you look in the application logs after running your query and paste in any other details?

I specific, right after running your query you should see the full query execution details enumerated including a section with ...

```
QUERY: 😎
{:type "query", :database 48, :query {:filter ["AND" ["TIME_INTERVAL" 5035 -7 "day"] [">" 5036 0] [">" 5040 0]], :source_table 442, :aggregation ["count"]}, :constraints {:max-results 10000, :max-results-bare-rows 2000}}
```

... and then a bit further down after that you should be given the exact SQL that's generated from the query and sent to your database, such as ...

```
SQL: 😈
SELECT COUNT(*) AS "count"
FROM "PUBLIC"."ORDERS"
WHERE (((CAST("PUBLIC"."ORDERS"."CREATED_AT" AS DATE) BETWEEN CAST(DATEADD('DAY', ?, NOW()) AS DATE)
   AND CAST(DATEADD('DAY', ?, NOW()) AS DATE)))
   AND ("PUBLIC"."ORDERS"."ID" > ?)
   AND ("PUBLIC"."ORDERS"."TOTAL" > ?))
```

**Comment by robinfrick** [comment]
Finally got around to do this: 

```
QUERY: ?
{:database 6, :type "query", :query {:source_table 1373, :aggregation ["rows"], :breakout [], :filter [], :order_by [[44777 "descending"]], :limit 10}, :constraints {:max-results 10000, :max-results-bare-rows 2000}}
```
(...)
```
SQL: ?
SELECT "public"."xxtablexx"."xxcolumn1xx" AS "xxcolumn1xx", "public"."xxtablexx"."xxcolumn2xx" AS "xxcolumn2xx", CAST("public"."xxtablexx"."created" AS TIMESTAMP) AS "created"
FROM "public"."xxtablexx"
ORDER BY CAST("public"."xxtablexx"."created" AS DATE) DESC
LIMIT 10

```
(I anonymized the table name and the other two columns)

As you can see it is casting the order by as date whereas the output is as timestamp. Very interesting that it doesn't happen at your end.
