### ISSUE TITLE
Aggregation in Models causes the column name to incorrectly be parsed down to questions based on that Model

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23248]
**Describe the bug**
Aggregation in Models causes the column name to incorrectly be parsed down to questions based on that Model.

Workaround is to not use Models, but just use a Saved Question instead.

**To Reproduce**
1. Question > Sample > Orders - summarize Distinct ProductID and Sum of Quantity, grouped by CreatedAt:Month
![image](https://user-images.githubusercontent.com/1447303/172833076-0483054a-1957-4a12-a464-a796a0611b40.png)
2. Save question and turn into Model - do a browser refresh
3. Go to Notebook to create a question based on the Model - summarize by three metrics, the first two metrics have incorrect column title
![image](https://user-images.githubusercontent.com/1447303/172834233-8f81ea22-f2e1-46b1-b719-750e7fe89904.png)

**Information about your Metabase Installation:**
Tested 0.43.2

**Additional context**
Likely related to #20624 and #23019.

**Comment by daltojohnso** [comment]
Left a comment here that is relevant: https://github.com/metabase/metabase/issues/24839#issuecomment-1241024840

Seems like if I remove the `field.isDimension()` part of this line, things work when based on top of https://github.com/metabase/metabase/pull/25109.

Should I open aggregation fields up to this behavior? As I mentioned in the above, linked comment, it seems like they were intentionally filtered out several years ago.

**Comment by daltojohnso** [comment]
FYI/BTW -- the FE pulls this name directly from the query results -- whatever's in the `results.data.results_metadata.columns` entries
