### ISSUE TITLE
Not able to create model using snippets

### ISSUE THREAD

**Issue by gajanand-jm** [metabase/metabase#23242]
**Describe the bug**
I've saved two SQL snippet that has SQL queries and no other snippets within them. But now I'm not able to convert the saved query/question into a model. I'm not using any variables in these snippets. Please see the screenshot.

**To Reproduce**
1. create two snippets
2. create a new SQL query using above snippets
3. turn this into model

**Expected behavior**
The error shown says that snippets can be used in a model, so one should be able to convert a SQL query using any number of snippets into a model.

**Screenshots**
<img width="1454" alt="Screenshot 2022-06-09 at 2 45 56 AM" src="https://user-images.githubusercontent.com/91305327/172719674-5b86be70-a608-4555-8125-8c688bacd304.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_111-internal-alpine-r0-b14",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_111-internal",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.111-b14",
    "os.name": "Linux",
    "os.version": "5.4.149-73.259.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "presto-jdbc",
      "h2",
      "athena",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.42.3",
      "date": "2022-03-23",
      "branch": "release-x.42.x",
      "hash": "33fb268"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}
```

**Severity**
Low

**Comment by paoliniluis** [comment]
This has been fixed in a more recent version https://github.com/metabase/metabase/pull/21210
