### ISSUE TITLE
Slack setup doesn't work if channels cache was recently cleared

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#23251]
**Describe the bug**
A slack channels cache was added in #20570 to improve performance. The cache is only refreshed if it was not refreshed within the last 10 minutes. It is also cleared whenever a Slack token is deleted. This means that if you've deleted a Slack app within the last 10 minutes, you can't add a new one, because the cache will be empty and the check that the files channel exists will fail.

**To Reproduce**
1. Create a new Slack integration in Metabase using the instructions in the admin panel
2. Delete the Slack integration
3. Add the Slack integration again
4. See a "channel not found" error on save, even though the files channel exists

**Information about your Metabase Installation:**
Current master

**Severity**
p1/2? only workaround is to wait 10 minutes and try again

**Comment by dpsutton** [comment]
@noahmoss Do we not populate the channel cache when saving a new token? The empty cache remains empty until its scheduled refresh?

**Comment by noahmoss** [comment]
@dpsutton The issue is that there's a [function](https://github.com/metabase/metabase/blob/master/src/metabase/integrations/slack.clj#L217-L220) that checks whether the cache was updated within the last 10 minutes. We try to update it when a new token is saved, but if that check returns `false`, we skip it.
