### ISSUE TITLE
UI - Select component with search causes the search to focus on scroll-up

### ISSUE THREAD

**Issue by diogormendes** [metabase/metabase#23252]
**Describe the bug**
When scrolling through the selection of database it autosuggest to return to the top position

**To Reproduce**
1. Go to 'Admin Settings'
2. Click on 'Data Model'
3. Select 'Orders'
4. Select 'Tax'
5. Scroll down
6. See error

**Expected behavior**
Should scroll without returning to the top position

**Screenshots**

https://user-images.githubusercontent.com/17742979/172878594-b8ff4194-c86b-440b-8f7f-b29073b2d1c8.mov

**Information about your Metabase Installation:**

Latest `master` 9f41e1

`NOT` happening on x.43.2

**Additional context**
Tested on Chome and Brave

**Comment by flamber** [comment]
Return of #13805, but seems to be Chrome specific. Wonder if we made a change or if Chromium changed something.

**Comment by diogormendes** [comment]
Just for the record, I'm Crome 102.0.5005.61

**Comment by gusaiani** [comment]
I couldn't reproduce it.

macOS 12.4
Versione 102.0.5005.61 (arm64)

**Comment by diogormendes** [comment]
As pointed out by @flamber it can be an extension/config issue. Trying on incognito without anything is working. 
So, closing this one.
