### ISSUE TITLE
[Actions] Unify API endpoints for executing actions/emitters [nice to have]

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#23275]
Part of #22542

Right now we have three custom action execution endpoints 

- The "Row action" endpoint for executing `DELETE`/`UPDATE`
- The "Table action" endpoint for executing `INSERT`
- The custom emitter endpoint for executing custom emitters (currently only QueryActions are supported)

We should think about whether we can unify these so there's only one endpoint for executing any sort of Action/Emitter and if they can all share a common parameters format. Not sure what this should look like so let's brainstorm a bit. If it turns out to be ugly we don't have to do this -- this is more of a nice to have than a requirement.

**Comment by camsaul** [comment]
The "row action" and "table action" endpoints were unified as part of #23922, and the new bulk stuff is using that lone endpoint as well. 

But emitters are executed via a different pathway still.

**Comment by snoe** [comment]
All execution is now done through the dashboard/dashcard/execute endpoint
