### ISSUE TITLE
execute trino query error

### ISSUE THREAD

**Issue by jimomiaomiao** [metabase/metabase#23276]
**Describe the bug**
I configured trino database and executed some query. And I found the following statement execution failed, trino WebUI show this statement failed because of **EXTERNAL ERROR — USER_CANCELED**. When I executed this statement in the trino client, it succeed.

query statement: 
`SELECT sum(CASE WHEN "device_total_memory" > 2000 THEN 1.00 ELSE 0.0 END) AS "test" FROM table`

My metabase version is v0.43.0, and trino version is trino-367

database configuration
<img width="755" alt="image" src="https://user-images.githubusercontent.com/45960684/172987011-152cbe38-0330-49ad-9e30-5d827604aab6.png">

metabase execute screenshot
<img width="801" alt="image" src="https://user-images.githubusercontent.com/45960684/172987256-b18fd027-37e2-4570-bdf6-4dfc3b4ecdbd.png">

trino WebUI screenshot
<img width="755" alt="image" src="https://user-images.githubusercontent.com/45960684/172987340-2e54f047-b7fa-4544-888b-8d5a8ae98c11.png">

I guess it may be due to jdbc driver.

**Comment by flamber** [comment]
The Presto driver is for PrestoDB. You will need a custom driver for Trino https://github.com/metabase/metabase/issues/17532#issuecomment-1149906975
