### ISSUE TITLE
Feature : Configurable default limit

### ISSUE THREAD

**Issue by anthofo** [metabase/metabase#2328]
It would be great to be able to configure the default limit for pulses in the settings. 
2000 is too much for me, and on large tables with a lot a columns it makes the ui freezing

**Comment by agilliland** [comment]
You are talking about the # of rows shown in the data table after running a query for `Raw data` correct?

Can I ask how many columns you have in the table you are viewing?

**Comment by anthofo** [comment]
Yes that's correct. The table has 86 columns :s (

**Comment by agilliland** [comment]
Okay, that makes a lot of sense then.  The 2000 row limit is likely not the problem in this case.  We are using a data grid component for rendering tables which is generally pretty solid, but it is not very well optimized for tables with a large number of columns :disappointed:   So it sounds like what you really want is to vote for this issue ... https://github.com/metabase/metabase/issues/664

**Comment by anthofo** [comment]
done :)

**Comment by mknippen** [comment]
Is this still a possible feature? +1

**Comment by sorrell** [comment]
I would also love to see the row limit exposed to the user.

**Comment by knes1** [comment]
Hi, I'm also voting for row limit exposed to the user for slightly different reason. My DB is highly normalized and we don't have OLAP database or ETL setup yet so we're using views for answering questions on joined data. If I give these views to my non-sql savvy users, they often run queries with all columns without any filters when exploring the data which are then slow to them. Limiting results to something like 300 might speed things up a bit in this case.
