### ISSUE TITLE
iFrameResizer resizer already defined when used inside a HTML page with frames

### ISSUE THREAD

**Issue by brailateo** [metabase/metabase#23301]
**Describe the bug**
Links to another dashboard from a Metabase dashboard inside a frame are not working, a blank dashboard appears.

**Logs**
iFrameResizer resizer already defined.   at dom.js (402)

**To Reproduce**
1. create a dashboard with card that have a click behaviour a link to another dashboard
2. use that page inside a frame (frameset, 2 frames, menu and dashboard)
3. click on a link
4. See a blank dashboard with nothing inside and the Javascript consoler shows error iFrameResizer resizer already defined.

**Expected behavior**
Dashboard displayed corectly inside the rame

**Screenshots**
none

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_292",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.292-b10",
    "os.name": "Linux",
    "os.version": "4.15.0-142-generic",
    "user.language": "en",
    "user.timezone": "Europe/Bucharest"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.43.2",
      "date": "2022-05-31",
      "branch": "release-x.43.x",
      "hash": "433d533"
    },
    "settings": {
      "report-timezone": "Europe/Athens"
    }
  }
}

**Severity**
major

**Additional context**
none

**Comment by flamber** [comment]
Hi @brailateo 
You need to provide more details about step 1 (the exist type of Click Behavior) and the HTML in step 2, so it's possible to understand what you are doing.
Sounds like it has nothing to do with the iframe-resizer, but more likely #22702/#23132

**Comment by brailateo** [comment]
![image](https://user-images.githubusercontent.com/602966/173348799-9a36ea99-6bd1-425c-95d7-4a6922aa78ad.png)

**Comment by flamber** [comment]
@brailateo You are not linking to another dashboard, but another question. But I cannot reproduce on 0.43.2 with the details you provide.
Use the H2 Sample Database and create detailed steps-to-reproduce.

**Comment by brailateo** [comment]
@flamber , I just upgraded to Metabase 0.43.3 and the problem is now solved, I'll close the issue.
I saw in "_What's changed_": **Click Behavior not redirecting in some cases**
Thanks!
