### ISSUE TITLE
Month & Quarter date groupings don't work on SQL Server 2008

### ISSUE THREAD

**Issue by louis-eyond** [metabase/metabase#2330]
In the New Question builder, running into an error when using the group by Month and by Quarter selections.  The error message is:

'FORMAT' is not a recognized built-in function name.

by Day, by Week, by Year do work; just the by Month and by Quarter do not.  The date is sum of a dollar amount column, aggregated on a DateTime column.  The data is valid and present (no nulls or incorrect date formats).  I've also tried on multiple  DateTime columns with the same result.

If this is a bug report, please fill in the blanks:
-  I am using the Chrome browser.
-  My computer is Windows Server 2008 R2.
-  I'm running Metabase locally from the JAR.
-  My database is SQL Server 2008 R2.
-  My Metabase version is 0.16.1.

**Comment by camsaul** [comment]
Unfortunately [it looks like the `FORMAT` function isn't available in SQL Server 2008](http://stackoverflow.com/a/11499496/1198455), so you won't be able to use month and quarter date groupings with Metabase unless you upgrade to a newer version of SQL Server.

**Comment by louis-eyond** [comment]
I agree the FORMAT function has a clean look to it: select format(getdate(),'yyyy-MM-01')

However, the 3 places (hour, month, and quarter) where it looks like the FORMAT function is being used in sqlserver.clj could be replaced with a CONVERT, such as:
select convert(varchar(11),dateadd(day, -datepart(day, getdate())+1, getdate()),20)

This would allow Metabase to support all versions of SQL Server for all of the groupings.  Since months and quarters are such important aggregates when working with financial numbers, this change could avoid a lot of support requests going forward.  I appreciate your consideration of this change.

**Comment by camsaul** [comment]
@louis-eyond sounds like you know what changes need to be made, can you submit a PR with those changes?

**Comment by agilliland** [comment]
@louis-eyond after looking into this a bit more closely we feel that SQL Server 2008 is a bit too dated for us to be testing against and supporting.  We are happy to take a look at any PRs if you feel like taking a stab though.

**Comment by camsaul** [comment]
Closing this out as Won't Fix since we have no plans in the future for supporting SQL Server 2008 or older.
