### ISSUE TITLE
Can not delete card or add multiseries in Chrome

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#2334]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser version Version 49.0.2623.110 m.
*  My computer's OS is Windows 10.
*  I'm running Metabase docker on aws. 
*  My database is mysql.
*  My Metabase version is version v0.16.1 built on 2016-04-05.

In chrome I can not delete cards (or add multi-series to card) from a dashboard.  
It works just fine in firefox.

See the video here: https://goo.gl/uoWRqB

**Comment by that0n3guy** [comment]
I should note,  I tried this a home (windows 7 w/ chrome) and it worked fine.   So when I got into work I updated my chrome (still didn't work) then tried it in an incognito window.  It works.

So I guessed this means its probably some chrome extension I have that is doing it to me.... so I disabled all extensions and restarted chrome... still doesn't work.

So then I cleared all  my cache/cookies.  Still doesn't work.    Any ideas?

**Comment by agilliland** [comment]
Yeah, that's bizarre.  I'm using Chrome 49.0.2623.87 and everything works fine and I know that in general the team all uses Chrome as their primary browser during development.

I'll try upgrading to the latest version later today and see if I can reproduce.  @tlrobinson or @kdoh may already be on that version, are you guys seeing this issue?

**Comment by that0n3guy** [comment]
2 posts up I never said what I updated too: 49.0.2623.112 m

**Comment by that0n3guy** [comment]
Ok, sooo, I walk into work today and now in the same browser windows I now have zero issues with this.  No idea why.  I didn't even close chrome when I left on Friday, just refreshed the page this morning.

**Comment by agilliland** [comment]
Alright, well I'm going to close this then and chalk this one up to a :ghost: in your computer.

**Comment by that0n3guy** [comment]
Yeah, its scary.

**Comment by damienchee** [comment]
This is happening to me now. I can't delete cards (or add multi-series to card) from a dashboard. It worked fine on Chrome incognito and Microsoft Edge.

- I am using the Chrome browser version 56.0.2924.87.
- My computer's OS is Windows 10.
- I'm running Metabase docker on aws.
- My database is H2.
- My Metabase version is version v0.23.1 Built on 2017-03-30

I tried clearing cookies for the domain Metabase is installed at but it doesn't help.
