### ISSUE TITLE
Click Behaviour with a hidden column from a Row chart does not send the filter value

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#23359]
**Describe the bug**
When creating a row chart from a question that returns (row_label, row_id, row_value), and setting up a click behavior that goes to a dashboard with a filter set to the value of row_id, the generated dashboard URL does not have the filter parameter at all.

**Logs**
When clicking on the row, the console displays "Opening https://my.metabase.instance/dashboard/42". We can see that the query parameter for the filter is missing.

**To Reproduce**
Steps to reproduce the behavior with Sample Dataset:
1. Create a question Q1 that displays the name of people
2. Create a dashboard D1 with an ID filter, add Q1 and link the filter to the id column of people table
3. Create a row chart Q2 that displays the number of orders per people. Group by people name (to display it on the chart) and by people id (so that it is available in the click behavior set-up)
4. Create a dashboard D2, add Q2, and set up a click behavior that sends to dashboard D1 with the ID filter set with the people ID.
5. Click on a chart row from D2. You are send to D1, **but the filter is not set**.

**Expected behavior**
In the steps above, the user should be sent to a URL such as https://my.metabase.instance/dashboard/42?id=xxx

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox
- Your operating system: Linux Mint
- Your databases: MySQL
- Metabase version: 0.42.3
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
Not severe but quite annoying, cannot be easily worked around because the id is not displayed on the chart so end users cannot manually enter it in the dashboard filter.

**Additional context**
We are not running the latest version, but I couldn't find a similar issue that was fixed in 0.43
It sounds similar to #13927 that was fixed a while ago.

**Comment by flamber** [comment]
The Row chart uses different underlying code that other visualizations, which is also the reason for some of the other problems with Row chart in general.

Possible workarounds: Not using hidden columns. Or use a different visualization type.

Reproduce:
1. Question > Sample > Orders - summarize Count by ID and ProductID, limit 5
![image](https://user-images.githubusercontent.com/1447303/174302927-9615f53f-578e-4137-bda4-d3944c580155.png)
2. Change visualization type to Row and only have "ID" column in the Y-axis
![image](https://user-images.githubusercontent.com/1447303/174303059-1f04aa95-f2ce-42ba-b30a-9fdb584a3d9b.png)
3. Add to dashboard and add a filter ID connected to card Orders.ProductID
4. Hover card > Click Behavior > Update a dashboard filter > ID connected to ProductID
![image](https://user-images.githubusercontent.com/1447303/174303472-ec05e876-422a-4d85-be1b-09d3344d8e7b.png)
5. Save dashboard. Clicking on any of the row bars will not change the filter, but a history push is being send
