### ISSUE TITLE
Archive icon too small in the pinned item context menu

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#23383]
**Describe the bug**
As of `https://github.com/metabase/metabase/pull/23315`, the archive icon in the pinned item context menu looks too small compared to all other icons.

**Logs**
N/A

**To Reproduce**
1. Go to the root collection
2. Pin any item (e.g. question)
3. Click on the ellipsis icon in the pinned item
4. See the squished archive icon

**Expected behavior**
The icon size should be uniform in the whole menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/174068838-b44e879c-22a2-440d-8a19-c2776a85ea0f.png)

**Severity**
P3, visual.

**Additional context**
Regression since https://github.com/metabase/metabase/pull/23315. This change has not yet been backported and is targeted for v44.

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/23391

<img width="730" alt="image" src="https://user-images.githubusercontent.com/2223916/177394547-49e72d31-1a3b-4b74-b137-0bdbd132b8cf.png">
