### ISSUE TITLE
Table x/y axes change depending on number of rows columns

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#2338]
If this is a bug report, please fill in the blanks:

*  I am using the chrome browser.
*  My computer's OS is window 10.
*  I'm running Metabase docker on aws
*  My database is mysql.
*  My Metabase version is v0.16.1 built on 2016-04-05.

This one is hard to explain w/o a video.   https://goo.gl/7ExkM6

Word description: If there are more columns than rows in a table, it dynamically switches them.  Here is 2 columns (categories) and 4 months (this is correct):

![image](https://cloud.githubusercontent.com/assets/113870/14385433/1fd494ea-fd66-11e5-95cc-96210e1530c8.png)

Here is 5 columns (categories) and still 4 months (this is wrong):
![image](https://cloud.githubusercontent.com/assets/113870/14385427/16f35fbe-fd66-11e5-8856-5a7c511b8bf4.png)

**Comment by agilliland** [comment]
Yeah, we've discussed setting it such that if one of the dimensions is time then it should be placed on the x-axis.  Currently I believe we always put the largest dimension on the x-axis, which is not ideal in this situation.

**Comment by that0n3guy** [comment]
Could also do a dropdown select next to the "visualization" selector.

**Comment by tlrobinson** [comment]
Postgres test case:

```
SELECT a, b, c
FROM (VALUES
  (now(), 'a', 1),
  (now() + INTERVAL '1 day', 'a', 2.2),
  (now(), 'b', 2.6),
  (now() + INTERVAL '1 day', 'b', 1.2),
  (now(), 'c', 0.5),
  (now() + INTERVAL '1 day', 'c', 1)
) AS t(a,b,c);
```

**Comment by agilliland** [comment]
Lets move forward and set the default behavior to always put the Date/Time dimension on the x-axis.  Beyond that fix we can track a separate issue to consider making this fully configurable by the user via #2371
