### ISSUE TITLE
Row Level Security in Open Source Version of Metabase.

### ISSUE THREAD

**Issue by Deepak656** [metabase/metabase#23420]
Put a thumbs up, if you also want to see it in open-source version of metabase.

This feature would bring Metabase to a **new level**. It's a fairly **basic requirement for anyone** with a serious use case for Metabase. It enables repeatability when Metabase is used in a multi-client or even multi-user environment.

Thanks for the v0.43 loving it.

**Comment by flamber** [comment]
Sounds great, but unless you figure out a way for us to pay our bills, then we cannot make every feature free.
https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html
