### ISSUE TITLE
Support unicode (emoji, Chinese characters, etc.) in pulses

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2342]
The pulse rendering engine doesn't handle emoji. It should.

![screenshot 2016-04-08 13 06 41](https://cloud.githubusercontent.com/assets/18193/14396196/08fd0ac0-fd8b-11e5-9e39-4164fdafce6e.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Since the text is rendered server-side as images we'll have to do something fancy to support emoji and make sure it's GPL-compatible / redistributable. We might be stuck with ugly open source emoji :cry:

**Comment by mazameli** [comment]
I hope the open source ones look as awesome as the original DoCoMo emoji:
![image](https://cloud.githubusercontent.com/assets/2223916/14396272/7ffb0032-fd8b-11e5-8b59-fd8dedf81cad.png)

**Comment by camsaul** [comment]
they'll probably just look like the ugly android or twitter ones

**Comment by tlrobinson** [comment]
There's some decent ones:

http://emojione.com/

https://twitter.github.io/twemoji/

**Comment by camsaul** [comment]
![image](https://cloud.githubusercontent.com/assets/1455846/14397376/cf8e0ca6-fd91-11e5-8bbf-5e7cabe851ea.png)
vs.
:smiling_imp: 

just not the same

**Comment by on99** [comment]
Please note that Chinese characters are also not rendered correctly.

![image](https://user-images.githubusercontent.com/13196393/31581179-0bc13d46-b197-11e7-91b5-d114a37f1120.png)

**Comment by camsaul** [comment]
(Moving this conversation over from duplicate issue #6174)

@nickhudkins if you still want to try tweaking the font list and find something that works as expected we'd love a PR for that. Thanks!

**Comment by nickhudkins** [comment]
@camsaul unfortunately we would need a font that's subset to only support emojii or something fun like that :\ I can look deeper into it because that would be the quickest solution I suspect. I suspect the fastest solution is going to be pulling `Lato` from the font stack, but I'll do some testing and find out. I may be able to get a font with only emojii subset that at least let's us fall back to `Lato`. As far as supporting other character sets goes, we're in for a much larger undertaking.

**Comment by salsakran** [comment]
@nickhudkins thank you for taking this on!

Just as a heads up, Lato is our font across the application. Dropping it from the stack is not going to be a quick-fix PR we merge unless it's really the only way out of this.

**Comment by camsaul** [comment]
@nickhudkins @salsakran I think you can (for example) refer to Apple's emoji font in CSS, right? `Apple Color Emoji` or something like that. So my understanding is we'd just need to figure out an emoji-only font stack to make every OS happy and then stick that in front of `Lato`

**Comment by nickhudkins** [comment]
@salsakran totally understood. and yes @camsaul I believe that should do the trick. I don't have anything running locally just been digging through the code to try to figure out what in the world is going. Perhaps a more useful PR would be getting this to stop rendering images, and use slack attachments

**Comment by camsaul** [comment]
@nickhudkins unfortunately we use that code for sending emails too so Slack attachments isn't a fix for that case

**Comment by camsaul** [comment]
Since we're rendering server-side we might also be able to bundle our own font and use that. (Not sure how easy that is.) Something like https://github.com/MorbZ/OpenSansEmoji could be a viable option.

**Comment by camsaul** [comment]
However that still wouldn't fix Chinese characters and the like

**Comment by salsakran** [comment]
Imo chinese is more important to support than emoji ;)

**Comment by nickhudkins** [comment]
@camsaul bit of a roadblock, is development on OS X supported? Attempting to build a local docker image and getting a webpack build failure, and running lein ring server and getting a TLS warning.

The docs regarding the TLS warning indicate I can add a snippet of clojure to the `project.clj` but I seem to receive the same error repeatedly. Perhaps it is a version mismatch of lein or something?

**Comment by nickhudkins** [comment]
@on99 could you provide me the characters that you were seeing rendering improperly? It appears that I have been able to render some Chinese characters successfully.
<img width="219" alt="screen shot 2017-10-20 at 11 25 27 pm" src="https://user-images.githubusercontent.com/299126/31852689-0b78ffce-b64a-11e7-8973-0b98b7d76861.png">

**Comment by nickhudkins** [comment]
So, changing fonts is not going to do the trick. I'll need to dig into how CSSBox is rendering the image.

**Comment by camsaul** [comment]
@nickhudkins we just discovered the leiningen 2.8 issue yesterday. We're still figuring out a fix

**Comment by nickhudkins** [comment]
Ask amazon to host redshift repo on https? Lol

**Comment by on99** [comment]
@nickhudkins What you rendered are **Traditional Chinese** characters XD

The **Simplified Chinese** characters I used are:
国家, 中国, 亚太地区, 实际收入.

**Comment by nickhudkins** [comment]
Ah. Thank you :)

**Comment by nickhudkins** [comment]
@camsaul so... I have absolutely NO IDEA what I am doing when it comes to clojure and have limited time to invest in learning it. But, I have done some research in HTML -> Image processing and what provides the most expected results. Using headless chrome, or phantomjs both result in the most consistent rendering of webpages (unicode and all!). 

Digging into the libraries out there for clojure, I came across: https://github.com/igrishaev/etaoin which seemed to be the simplest API. I also was able to successfully render a page full of emojii and chinese characters using the library with both phantomjs and chrome. 

This would remove the renderer that was borrowed from CSSBox, but introduce `phantomjs` or `chrome` as a dependency. Does that seem like an acceptable tradeoff knowing that you'd be able to reliably get rid of strange HTML -> Image bugs in one fell swoop?

**Comment by camsaul** [comment]
@nickhudkins doing something like that would be nice. Especially if we could reuse the same JS code we use to render client-side instead of having a separate, less-sophisticated set of code to render server-side. I do have a feeling a project like that would take quite a bit of effort however

**Comment by salsakran** [comment]
imo shipping phantomjs or chrome as a dependency is tricky. It's a non-jvm dependecy we'd need to be able to install across a wide variety of platforms. We'd also need to be careful about the extra memory footprint, as we're starting to get a little ... big boned on that front.

Not a fan.

**Comment by nickhudkins** [comment]
@salsakran totally understood regarding shipping phantomjs or chrome, which is why I asked. Unfortunately I don't know that you have many options without either finding a JVM based HTML-> Image renderer that doesn't have problems with unicode, or, rolling your own which sounds like a nightmare with phantomjs being standard and headless chrome chipping away rapidly at this space. 

The alternative would be to go ahead and render HTML for emails and use slack's API more fully to be able to use non image attachments to get rich messaging. From a dependency standpoint, this would likely be the lesser of two evils, but introduces quite a lot of service specific code.

**Comment by hden** [comment]
Provide options to use [Google Noto](https://www.google.com/get/noto/) fonts will likely solve the issue. Users who need extra fonts can install manually so the bundle size does not increase significantly.

The other options is to use [quil](https://github.com/quil/quil) which works in cljs as well.

**Comment by Microsheep** [comment]
Any updates on this going to be implemented or not?

Currently using metabase in the NPO for almost a year and loved what it can do.
Saved a lot of precious time for the engineers and get the organization to access the data easier.
Would be nice if this can be solved so we can use pulses for helping us with delivering important metrics!

**Comment by hehachris** [comment]
Any updates on this?

**Comment by slowcore** [comment]
Any updates? I guess most of Japanese users are waiting...

**Comment by citizen-seven** [comment]
Hi, it appears that in the new Metabase version (35.3) the cyrillic font isn't loading (russian, for example).
<img width="660" alt="image" src="https://user-images.githubusercontent.com/14357228/80733204-d4987200-8b26-11ea-97b0-ddcdd1339d4a.png">

**Comment by citizen-seven** [comment]
Any updates here?

**Comment by flamber** [comment]
@citizen-seven There's 47 other P1s, so the only workaround currently would be to downgrade.

**Comment by citizen-seven** [comment]
@flamber any way for this issue to get into 0.36 release? We need an update because there is PostgreSQL filter error, which was fixed later, but we cannot update because pulses don't work.

**Comment by flamber** [comment]
@citizen-seven I understand the problem, but it's not a simple fix, so I doubt it will make it for 0.36.0

**Comment by jinfagang** [comment]
Does any body knows a font which contains Chinese and emoji at the sametime?

**Comment by citizen-seven** [comment]
@jinfagang https://www.google.com/get/noto google has some free fonts with lots of supported languages

**Comment by jinfagang** [comment]
@citizen-seven thanks, I know it, but I need fonts contains both Chinese charactors and emojis in a single font.

**Comment by citizen-seven** [comment]
No updates here? I have to use 34.3 because of the issue, it blocks me from updating

**Comment by dmeremyanin** [comment]
@flamber any chance to get this fixed in 0.37? 🙏

**Comment by flamber** [comment]
I don't think this will make it. It's not an easy fix. There's no timeline for a fix.

**Comment by citizen-seven** [comment]
@flamber any updates here?

**Comment by flamber** [comment]
@citizen-seven We now have more developers and we're digging into several Pulse issues, but I don't have a timeline for this.

**Comment by citizen-seven** [comment]
@flamber any updates here? Maybe we can fix it for us by using another font in the docker container?

**Comment by flamber** [comment]
@citizen-seven You can try.

**Comment by kounoike** [comment]
I made quick fix for our(Japanese) team. But I can't create docker image which uses noto-color-emoji font.
https://github.com/blue-agency/metabase/tree/font-cjk-quick-fix

**Comment by devxoul** [comment]
@kounoike Do you have any plan to make a pull request?

**Comment by kounoike** [comment]
@devxoul no plan. CJK fonts have a very large file size. It does not benefit anyone except CJK users.

**Comment by ypresto** [comment]
I'm wondering if we can load Google Fonts in pulse renderer.
It'll only load small chunks of glyphs which contains CJK characters used in the html.

**Comment by devxoul** [comment]
What about giving an option like `MB_INCLUDE_CJK_FONTS` to include CJK fonts in docker build?

**Comment by tuoqiao** [comment]
Chinese can refer to this
https://www.cnblogs.com/ntestoc/p/10968541.html

**Comment by chomu1219** [comment]
Please note that Korean characters are also not rendered correctly!
![metabase2slack1](https://user-images.githubusercontent.com/86768424/164194396-3e99226f-e483-4acf-ad93-014c2e52e708.png)

**Comment by vbezl** [comment]
I've fixed it by installing the full lato fonts on my Ubuntu server:
sudo apt-get install -y fonts-lato

(metabase restart needed after installation)

**Comment by camsaul** [comment]
If it's just a matter of installing an extra package, we can do that in our Docker image. Definitely worth a try

**Comment by YRM2** [comment]
> I've fixed it by installing the full lato fonts on my Ubuntu server: sudo apt-get install -y fonts-lato
> 
> (metabase restart needed after installation)
Hello, can you solve the problem of Chinese garbled code in pulses？
I have the same issue, the Chinese garbled code displayed in the email
![image](https://github.com/metabase/metabase/assets/43648673/949663b0-24cb-43eb-a9ca-e33f167c1310)

**Comment by paoliniluis** [comment]
As lato is not available in alpine I think that noto fonts should work, I’ll prepare a pr

**Comment by YRM2** [comment]
Thank you, looking forward to it

**Comment by paoliniluis** [comment]
@YRM2 can you provide some example, or maybe build https://github.com/metabase/metabase/pull/31764 with docker and test?

**Comment by YRM2** [comment]
@paoliniluis Thank you , You are right。I have installed font logo on my system (centos7.9), `sudo yum install google-noto-*` and  restart metabase by`java -jar metabase.jar` , Now it can be displayed normally in the email。
![image](https://github.com/metabase/metabase/assets/43648673/e64fd3af-63ef-4a01-8df8-6119db67b9f2)

**Comment by paoliniluis** [comment]
I did some tests in my machine and seems like it works 
![image](https://github.com/metabase/metabase/assets/1711649/6bbf7f21-c7f2-42f9-84b6-e33892c6eae6)

**Comment by luolovehk** [comment]
After installing the Chinese font, export the picture of SLACK, the histogram can display Chinese, but the data table cannot be displayed.

![Screenshot_2023-07-11-23-33-51-793_com Slack](https://github.com/metabase/metabase/assets/61071476/e85c79d0-25fe-49c0-9a93-a0f0b9c3bed8)
![Screenshot_2023-07-11-23-34-07-423_com Slack](https://github.com/metabase/metabase/assets/61071476/80a08cf8-44a2-4e89-ad9d-5b1bfe02e400)
![image](https://github.com/metabase/metabase/assets/61071476/198c0556-ea47-47f7-8928-0038bd47c7ec)
![image-1](https://github.com/metabase/metabase/assets/61071476/00a40c12-b0ff-4fef-969a-ab663f03b346)
![image-2](https://github.com/metabase/metabase/assets/61071476/8ecbf9d8-401d-4e74-852b-f5c42233f019)

**Comment by paoliniluis** [comment]
Alright! seems we're going to support unicode in pulses at last! @luolovehk can you provide us some example?

**Comment by nemanjaglumac** [comment]
Reopening as #31764 introduced breaking changes and failures in the build job.
