### ISSUE TITLE
The field name of downloaded pivot table is not updated

### ISSUE THREAD

**Issue by yinshangwei** [metabase/metabase#23428]
If I rename the field name of the pivot table in the dashboard from **"Sum of Column A"** to **"Column A",** when I choose to download the pivot table, the field name will still be "Sum of Column A" in the downloaded file. I hope the field name can also be changed to **"Column A"** in the downloaded file.

**Comment by flamber** [comment]
Hi @yinshangwei 
Post "Diagnostic Info" from Admin > Troubleshooting.
Which type of export are you doing, CSV or XLSX?
And how are you downloading the pivot table from the dashboard?

**Comment by yinshangwei** [comment]
@flamber 
Both CSV and XLSX.
It's an embedded dashboard, and I download the pivot table from the embedded dashboard, not from the **question**.

**Comment by yinshangwei** [comment]
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.13.0-1025-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-31",
      "tag": "v0.43.2",
      "branch": "release-x.43.x",
      "hash": "433d533"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
Closing in favor of #17753
