### ISSUE TITLE
Native query editor should handle unicode/emoji correctly.

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2344]
Two probably related issues:

First, if you paste an emoji in a native query then hit delete it turns into an unknown "box" character. It seems like it's treating it as multiple characters or something.

Before:

![screenshot 2016-04-08 14 01 27](https://cloud.githubusercontent.com/assets/18193/14397484/6e8998ca-fd92-11e5-9d30-d44ac5a6f6a0.png)

After:
![screenshot 2016-04-08 14 00 41](https://cloud.githubusercontent.com/assets/18193/14397481/6ad1c22a-fd92-11e5-8541-6c94bc99ce6e.png)

Second, the spacing seems to be off. In this screenshot the cursor at the end of the line, directly after the comma (hitting delete will delete the comma), but it appears shifted to the right several characters:

![screenshot 2016-04-08 13 58 37](https://cloud.githubusercontent.com/assets/18193/14397434/34f03524-fd92-11e5-9bf3-b25c43af243a.png)

**Comment by camsaul** [comment]
probably because emoji are mutlibyte unicode character points

**Comment by camsaul** [comment]
this problem likely isn't emoji specific and likely affects other unicode characters as well

**Comment by tlrobinson** [comment]
Yeah, that's what I figured. There's a bunch of open issues on Ace editor, so this probably isn't an easy fix: https://github.com/ajaxorg/ace/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unicode

**Comment by agilliland** [comment]
If this truly an issue with Ace and not specific to anything in the Metabase code handling this input then lets mark this as a Limitation instead of a Bug.

**Comment by tlrobinson** [comment]
http://blog.jonnew.com/posts/poo-dot-length-equals-two

**Comment by flamber** [comment]
Hi @tlrobinson 
I cannot reproduce this issue in 0.31.2 on Firefox 65
```SQL
SELECT NAME
FROM
  (VALUES
    ('Louis''s 🧀'),
    ('Multi 🧀🧀🧀'),
    ('Some 🧀 Equals 🧀'),
    ('The best 🧀 of all the 🧀 in the world')
  ) AS t(NAME)
ORDER BY random()
LIMIT 1
```

**Comment by tlrobinson** [comment]
@flamber You are correct, it looks like this was fixed at some point.
