### ISSUE TITLE
Cannot add new geojson files

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#23450]
I'm unable to add new geojson files.

#### Before in 0.43.2
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/6377293/174686423-c7066327-1742-49e6-afda-e85533e92e88.png">

#### After on master
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/6377293/174686447-a0c797c6-c0db-4513-bbe0-b6e314e4d65c.png">

This fails here at this stage. When running a dev version of Metabase `resources` is on the classpath so you can reach to the built-in us states map automatically. Add a map based on the file `frontend_client/app/assets/geojson/us-states.json`. Using a query against this map gives:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/6377293/174686702-dfbf29bb-eb35-4e23-aa3f-bd6d8301f93e.png">

But it still works against the built-in us maps (this is an identical copy. seems so strange to me)
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/6377293/174686729-89d38cdb-7c13-41d5-892a-d9848c11f2f4.png">

**Comment by dpsutton** [comment]
some investigations in slack point to https://github.com/metabase/metabase/pull/22427 as a possible commit the bug first appeared.

**Comment by iethree** [comment]
> some investigations in slack point to #22427 as a possible commit the bug first appeared.

This seems to be the offending line: 

https://github.com/metabase/metabase/blob/ccac9d9af9addbc8eb689a802b5d5ccb92b1638a/frontend/src/metabase/visualizations/components/LeafletChoropleth.jsx#L103

**Comment by dpsutton** [comment]
amazing find @iethree . thanks
