### ISSUE TITLE
Report timezone in date filter - exclude hours of day

### ISSUE THREAD

**Issue by mzecov** [metabase/metabase#23461]
**Describe the bug**
Issue when using filter "exclude..." -> "hours of day" on timezone aware column in query builder, when reporting timezone is not UTC.

My database is PostgreSQL, datetime column to filter is timezone aware, and reporting timezone is CET/CEST.
I filter the data in query builder with: "hour of day = 6am", and get results with hour = 8am (in CET/CEST)
Check on Metabase 0.43.1, 0.43.3

Generated SQL request is like:
```
CAST(extract(hour from <timezone aware> ) AS integer) <> CAST(extract(hour from CAST(timestamp with time zone '2022-06-21 07:00:00.000Z' AS timestamp)) AS integer)
```
Input filter hour seems defined in UTC and cast to reporting timezone before filtering. But the expected behavior should be to take directly input hour in reporting timezone.

**To Reproduce**
1. Change reporting timezone to anything but UTC
2. Filter (with GUI) a timezone aware datetime column: using "Exclude" > "Hour of day" > uncheck every hour but 6am for instance
4. Result dataset (displayed in reporting timezone) doesn't match input hour of day (6am)

**Expected behavior**
Results should match input hour of day in reporting timezone.

For instance, when filtering with "Specific dates..." > "On", Metabase generates request like:
```
( {timezone aware column} >= timestamp with time zone '2022-05-30 00:00:00.000+02:00'
AND {timezone aware column}  < timestamp with time zone '2022-06-07 00:00:00.000+02:00')
```
which give expected results (see timezone in input dates)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "fr",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.170+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.7 (Debian 10.7-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-16",
      "tag": "v0.43.1",
      "branch": "release-x.43.x",
      "hash": "7f1a1c4"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```
From this page ([Handling Timezone](https://www.metabase.com/docs/latest/operations-guide/handling-timezones.html)), I tried to set JVM timezone to reporting timezone but it doesn't change anything.

**Severity**
Annoying

**Comment by calherries** [comment]
Following flamber's steps above, I can see that the issue is caused by the FE creating a filter where the timestamp values have a timezone.

For example following steps 1, 2, 3 above, I get this filter in redux devtools:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/39073188/175266680-fd7fb535-4d51-4fbf-8881-bf6cfbb18155.png">

The value is a timestamp with a timezone. As mzecov mentioned in the OP, this clause translates into 
`CAST(extract(hour from CAST(timestamp with time zone '2022-06-23 08:00:00.000Z' AS timestamp)) AS integer)`, which is not 8 if the reporting timezone differs from UTC. But we want it to be 8.

I've created a draft PR [here](https://github.com/metabase/metabase/pull/23500) with a potential solution sketched out.
