### ISSUE TITLE
Support parameters for Saved SQL Questions

### ISSUE THREAD

**Issue by egsukhanov** [metabase/metabase#2348]
I use metabase to provide reports. Though most of the times i need this data to be restricted by specific value (e.g. user or other id), so report on specific user e.g.
As most queries are rather heavy (e.g. with a couple of UNIONs) - there is no easy way to tell colleagues if I wanna share report with them "Open sql and change number in the first line", especially as Metabase supports only one statement, so I can't write SET @userid = X; in the first line and then select statement.

Please for SQL-based cards add an option to set value of parameter in interface (I guess it's more convenient to introduce parameters which you will replace in SQL before pushing it to DBMS, than coming up for solution similar to SET in mysql for each database or multi-statement query), so this parameter will be replaced with the defined value inside SQL query.

Would be also nice not to round decimals when displaying results (if i wanna crop decimals - i will do it inside SQL), as currently I have to transform value into text so it's not cropped by metabase...

**Comment by tlrobinson** [comment]
@egsukhanov Does #1543 cover what you're asking for?

**Comment by egsukhanov** [comment]
If it's applied also to SQL-created questions - then yes (initial request is not highlighting it, but comments on the issue also focus on SQL questions).

**Comment by MartinArens** [comment]
+1

**Comment by jflatter** [comment]
+1 Would also love this for Metabot

**Comment by salsakran** [comment]
fixed via #2795
