### ISSUE TITLE
Aggregation labels/headers should include the aggregated column name or be editable

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2349]
Currently we only show "sum" (etc) in table column headers and axis labels for aggregations. It would be better if it included the name of the column being aggregated, or allow the user to edit the displayed name.

<img width="295" alt="screen shot 2016-04-10 at 11 04 18 pm" src="https://cloud.githubusercontent.com/assets/18193/14418118/d25b4eae-ff70-11e5-955e-e795ee384bbf.png">

**Comment by camsaul** [comment]
Duplicate of #1851.

**Comment by mazameli** [comment]
Tom just feels passionate about it, evidently. :)
