### ISSUE TITLE
Viewing archived questions causes bad error

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23501]
**Describe the bug**
Viewing archived questions causes bad error.
P2 contender.

**To Reproduce**
1. Native > Sample > `select 'archived'` - save question
2. Archive question (or the question could also be placed in a collection that was archived)
3. Then go to the URL of the question - shows the error `Something's gone wrong - We've run into an error. You can try refreshing the page, or just go back.`
![image](https://user-images.githubusercontent.com/1447303/175267447-9f45c21c-4f51-4638-ba3a-48788aad354c.png)

**Workaround:** - just adding these for history
If it is a single archived question:
- Unarchive the question by going to the archive page (URL `/archive`)
- Or send a request like this to unarchive the question (you will have to know the archived question ID). Change the URL and `123`
```
await fetch("https://metabase.example.com/api/card/123", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": "{\"archived\":false}", "method": "PUT", "mode": "cors" });
```
- Or edit the application database table `report_card.archived=false` for the question, and possibly move the question to the root collection temporarily (`report_card.collection_id=null`) if the collection is archived.

If it is an archived collection:
- Unarchive the collection by going to the archive page (URL `/archive`)
- Or send a request like this to unarchive the collection (you will have to know the archived collection ID). Change the URL and `123`
```
await fetch("https://metabase.example.com/api/collection/123", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": "{\"archived\":false}", "method": "PUT", "mode": "cors" });
```
- Or edit the application database table `collection.archived=false` for the collection (remember to unarchive parent collections if it was part of a hierarchy), and then unarchive questions (`report_card.archived=false`) and dashboards (`report_dashboard.archived=false`) belonging to that/those collections.

**Expected behavior**
Display similar error as 41.7 - `This question has been archived`
![image](https://user-images.githubusercontent.com/1447303/175273256-9ae30dcc-f891-49ed-bb91-793788cf2d62.png)

**Information about your Metabase Installation:**
Tested 0.41.7 thru 0.43.3 - regression since 0.42

Very related to #10987 and #21341

**Comment by gusaiani** [comment]
@flamber, I haven't been able to reproduce.

On `master` branch, I am seeing the page we want, both after archiving a question directly, and after archiving a collection and then visiting a question that was in it.

I get the "This question has been archived" page.

Would you be willing to try again from latest master, please?

**Comment by flamber** [comment]
Seems to have been fixed, which the warrants a test @nemanjaglumac

**Comment by gusaiani** [comment]
@flamber @nemanjaglumac, 

I can write a test for this, doing it now.
