### ISSUE TITLE
Druid driver defaults to interval of +/-5000, which can cause exceptions

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2351]
When testing out the Druid driver recently on a large cluster the default interval value of +/-5000 caused an exception every time a query was run.  We need to have more practical defaults which don't cause a query error.

To work around the problem you could manually input a filter on time, but that's impractical in some situations.

This is on Metabase v0.16.1 using the Mac App.

**Comment by camsaul** [comment]
Do you have the logs?

Druid requires an interval for queries so if the MBQL query isn't filtering by the date that's the fallback interval we use. I haven't seen any problems with it so far so without more specific info it will be hard to fix this.

**Comment by agilliland** [comment]
Yeah, I'll try to get the exact logs, but this was clearly a problem.  I would recommend we try using actual dates instead of numbers.  When we were troubleshooting this the solution was to actually put in value dates.  e.g. why are we not using `1900-01-01/2100-01-01` or something like that?

The error was something to do with invalid integer for intervals.

**Comment by camsaul** [comment]
Because Druid understands years as dates just fine? See if you can find out what version of Druid they're using. It might be the case that they're on a older version that doesn't support some things we do.
