### ISSUE TITLE
Running a timeseries query on Druid failed

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2352]
When trying to produce a simple timeseries query which summed a column and grouped by time daily the query failed due to Druid syntax issues. 

This is on Metabase v0.16.1 using the Mac App.

**Comment by camsaul** [comment]
Do you have the logs?

**Comment by agilliland** [comment]
Sadly no :crying_cat_face: 

This was being executed on another computer which I didn't have access to.  I'll work on getting the information, but I'm thinking it should be fairly easy to reproduce this because it was literally just a query against a table with a sum(colum1) as the aggregation and a breakout by the Druid datetime column.

**Comment by camsaul** [comment]
@agilliland What ever happened with this? I remember you were spending a few day with Druid last month, did you figure out what's wrong?

**Comment by moumny** [comment]
This type of queries work fine for us (at least with druid 0.9) but i did a quick benchmark with 100 queries it takes 12s using topn and 1.8s using timeseries.

**Comment by camsaul** [comment]
motion to close since we may we never get enough info to investigate this

**Comment by camsaul** [comment]
Closing since there's not enough info to look into this.
