### ISSUE TITLE
Data point value style missing stroke, which makes it hard to read sometimes

### ISSUE THREAD

**Issue by Javalover93** [metabase/metabase#23529]
**Describe the bug**
I recently updated metabase from v0.41.3.1 to v0.43.3. All things good. But I find it that values diaplyed on the chart is not readable as it was on  v0.41.3.1, bacause of the color. More details provided below.

On v0.41.3.1, numbers have white surround colors making them easy to recognize.
![image](https://user-images.githubusercontent.com/21034094/175471776-6cdf8b57-b328-4bdd-97d4-82d0e8ade778.png)

While on v0.43.3, numbers don't have white surround colors.
![image](https://user-images.githubusercontent.com/21034094/175472066-1234f902-5f59-427d-bb93-9ab063a5ee75.png)

**Comment by flamber** [comment]
Regression since 0.43.0, likely by #22208, where the double SVG elements were removed, but without keeping the stroke.
