### ISSUE TITLE
Set a minimum threshold for counts appearing in grouped results

### ISSUE THREAD

**Issue by rthrfrd** [metabase/metabase#2358]
It would be nice to be able to set a minimum threshold (particularly for example when using a count grouping + pie chart) so we could say "only show in results if count > N".

Sorry if has already been requested, couldn't see it after searching.

**Comment by agilliland** [comment]
I believe the issue you were looking for is this one ... https://github.com/metabase/metabase/issues/1207

**Comment by rthrfrd** [comment]
@agilliland Thank you, should have searched for "HAVING"!
