### ISSUE TITLE
Access dashboard without an logged in user

### ISSUE THREAD

**Issue by kassyuz** [metabase/metabase#2359]
If this is a bug report, please fill in the blanks:

*  I am using the **Chrome** browser.
*  My computer's OS is **Win7**.
*  I'm running Metabase **locally from the JAR**.
*  My database is **SQL Server/H2**.
*  My Metabase version is **v0.16.1**.

**Comment by salsakran** [comment]
Hey @kassyuz are you thinking of doing this for internal or external use? I.e. will this be a dashboard for people in your company/organization or for the broader interwebs to consume?

**Comment by kassyuz** [comment]
Hey @salsakran, I would use just for internal purpose. I will put the chart at TV screen for our manager. This will share in our company too, but people just access througth a local network.

This item is difficult to solve?

**Comment by salsakran** [comment]
We typically create a user account for large format monitors/TVs around the office with dashboards. We'd recommend that.

For your folks inside the company, we STRONGLY recommend they have user accounts. It should be easy to use, and generally allows them to sign up for pulses on their own, etc.

I'll leave this issue open to see if there's interest. In general, for features, we like to see some amount of community support for things before we do them.

**Comment by jflatter** [comment]
I would love this feature. We currently use Chromebits and TV Monitors to show dashboards pointed at a URL with a Leftronic dashboard.

This would potentially replace the need for a service like Leftronic.

**Comment by jflatter** [comment]
Is it possible to simply pass user/pw in the url?

**Comment by kassyuz** [comment]
@jflatter I think it isn't possible, because in my opinion to pass user/pw in url is a security fail.

When you pass any parammeter in an url, the method invoked need be GET. Because security rules, login pages needs to use method POST, even if use HTTPS protocol.

**Comment by tarundelhivery** [comment]
This is what even I am looking for. I want to operations to see dashboard they needed but dont want to change queries. 
Reason - If they are allowed to query on server they may access confidential data from database , Which we dont want them to see

**Comment by dylburger** [comment]
I volunteer for the Code for San Francisco organization, and we're currently reviewing ad hoc analysis tools like Metabase to support analysis of city data by non-technical users and data scientists alike.

Our use case would be to expose a wealth of San Francisco data publicly, and need to protect no data behind a login. Ideally, we'd just point citizens to Metabase and have them query at will.

Ideally, we'd be able to permission tables and dashboards for public view to help satisfy these use cases.

Let me know if this makes sense or if you need any more detail to support such a feature!

**Comment by ebocher** [comment]
We are in the same use case to expose urban climate indicators for end-users.

By the way, let me inform the metabase team that there is a spatial extension, called  [H2GIS]( http://www.h2gis.org/) available for H2 database.  

Hope it may be useful for metabase community.

Cheers from [Vannes](http://osm.org/go/eq1QyUUg-?layers=T)

**Comment by mazameli** [comment]
A very similar feature request is being tracked in this issue now: https://github.com/metabase/metabase/issues/3681

**Comment by ajkosasih** [comment]
For users who use metabase to analyse private data of a company, sharing a dashboard with a public link will be risky. There should be user access restrictions in place for security reasons.

I think the solution @salsakran suggested is best. Users should be invited to a specific dashboard for a Read-Only access, then people should only be able to access it after they have logged in.

I also noticed a discussion in this thread:
https://discourse.metabase.com/t/allow-user-to-view-dashboard-only/939

"We're also considering dashboard-level permissions for user groups, which would let you set a group's access for a given dashboard to Read+Write, Read-only, or No Access."

I think this will solve the problem, I would only need the Read-only.

Any ideas when this feature will be released? Any issues related to this for tracking?

**Comment by fkoehne** [comment]
+1 for a public board feature.

**Comment by mazameli** [comment]
@fkoehne public dashboards were [implemented in Metabase version 0.23](http://www.metabase.com/blog/Metabase-0.23).

**Comment by fkoehne** [comment]
Awesome! Thanks for the pointer.
