### ISSUE TITLE
Misleading breakout on bar graphs

### ISSUE THREAD

**Issue by voroninman** [metabase/metabase#23627]
**Describe the bug**
The bar graph reports subcategory of a numerical aggregation when it is not included in the grouping.

**To Reproduce**
1. Run this query:

```sql
SELECT category, beauty, n
FROM (VALUES ('cats', 'cute', 100), ('cats', 'ugly', 1)) AS t(category, beauty, n)
```

2. Pick bar visualisation.
3. Remove the beauty column.

**Expected behavior**

The graph should show that there are 101 cats (both cute and ugly) but actually it reports that there are 101 cute ones which is wrong.

**Screenshots**

<img width="996" alt="Screen Shot 2022-06-30 at 10 16 25" src="https://user-images.githubusercontent.com/399059/176628024-cb1cc66c-0bb3-4a9f-9558-4003749c4815.png">

**Information about your Metabase Installation:**

- Metabase version: v0.43.2

**Severity**

Misleading analysis.

**Comment by flamber** [comment]
Hi @voroninman 
There's a warning being shown in top-right corner:
![image](https://gcdnb.pbrd.co/images/uKtmdhrX9pLg.png?o=1)

**Comment by voroninman** [comment]
Hi @flamber. Thanks for the quick response! Very much appriciated. 🙌

> There's a warning being shown in top-right corner:

Fair. With the warning in mind it's not a bug. 

So Metabase does its best 🌟 and sums the values (doing aggregation) on the columns in the X-axis list, right? Would you agree that it would be a great improvment to hide the columns that aren't part of the aggregation?

**Comment by voroninman** [comment]
@flamber I agree that solution to my problem is to remove the column that isn't part of the columns in X-axis.

It's not a forum for seeking knowleadge but excuse me to ask one more question. Is it the case, that people who depend on the extra columns in the tooltip will be misguided by any value that happened to the first unless the values in the grouped on column (`category` in this case) and the extra column (`beauty`) are equal? Do people proactively use this to put extra info for the bars?

**Comment by flamber** [comment]
@voroninman Metabase does everything correctly with the example you provided. Yes, extra columns in tooltips are used by a lot.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
