### ISSUE TITLE
JSON unfolding not working for any columns in a table if one column as more than 100 keys

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23635]
**Describe the bug**
JSON unfolding not working for any columns in a table if one column as more than 100 keys.
Likely the cause for why some in #708 were not seeing unfolding and no errors in their logs.

**To Reproduce**
1. Create a table like this:
```
INSERT INTO x_json_sync (id, jsoncol1, jsoncol2) VALUES
(
1,
'{"tiny":"column"}',
'{"a1":1,"a2":2,"a3":3,"a4":4,"a5":5,"a6":6,"a7":7,"a8":8,"a9":9,"a10":10,"a11":11,"a12":12,"a13":13,"a14":14,"a15":15,"a16":16,"a17":17,"a18":18,"a19":19,"a20":20,"a21":21,"a22":22,"a23":23,"a24":24,"a25":25,"a26":26,"a27":27,"a28":28,"a29":29,"a30":30,"a31":31,"a32":32,"a33":33,"a34":34,"a35":35,"a36":36,"a37":37,"a38":38,"a39":39,"a40":40,"a41":41,"a42":42,"a43":43,"a44":44,"a45":45,"a46":46,"a47":47,"a48":48,"a49":49,"a50":50,"a51":51,"a52":52,"a53":53,"a54":54,"a55":55,"a56":56,"a57":57,"a58":58,"a59":59,"a60":60,"a61":61,"a62":62,"a63":63,"a64":64,"a65":65,"a66":66,"a67":67,"a68":68,"a69":69,"a70":70,"a71":71,"a72":72,"a73":73,"a74":74,"a75":75,"a76":76,"a77":77,"a78":78,"a79":79,"a80":80,"a81":81,"a82":82,"a83":83,"a84":84,"a85":85,"a86":86,"a87":87,"a88":88,"a89":89,"a90":90,"a91":91,"a92":92,"a93":93,"a94":94,"a95":95,"a96":96,"a97":97,"a98":98,"a99":99,"a100":100,"a101":101}'
)
```
2. Admin > Databases > (pg) > Sync database schema now
3. Admin > Data Model > (pg) > x_json_sync (do a browser refresh, just to make sure it's not showing browser cache)

**Expected behavior**
1. Unfolding should be done at column-level, so I should see jsoncol1 unfolded
2. Log should tell what is going on
3. It should log why it is not unfolding a specific column (like more than 100 key limit)
4. It should unfold the first 100 keys, so it behaves more like Mongo, which has several issues open about it like the ones [I've referenced](https://github.com/metabase/metabase/issues/15576#issuecomment-845798189). If we do this, then there should be an easier way of managing the unfolded columns, since it's currently extremely difficult if you have a table with 10-20 JSON columns, which each might produce 50 unfolds, making the Data Model page 500-1,000 items.

**Information about your Metabase Installation:**
Tested 0.43.4

**Comment by maximepvrt** [comment]
Can you add an expression to get an unreferenced json field to fix this issue for json column with more 100 keys.

![Capture d’écran 2022-07-20 à 16 04 19](https://user-images.githubusercontent.com/1840026/180003123-d7341cfb-1d64-4c31-a7cc-0a1671af1467.png)

**Comment by flamber** [comment]
@maximepvrt There's a request of adding JSON expression #10217
