### ISSUE TITLE
Can't connect to Amazon Redshift from Linux (including Elastic Beanstalk installation)

### ISSUE THREAD

**Issue by MaxSavenkov** [metabase/metabase#2365]
From my Windows machine, I can connect Metabase to my Redshift instance without problems. However, when I tried installing it on my Linux server, I always got Timeout error when trying to connect. Frustrated, I tried to run Metabase on Amazon Elastic Beanstalk, as described in documentation, but got the same timeout! It seems like there is some Linux-specific bug here, though I'm not sure what could it be...

OS: Windows (works OK), Linux (timeouts)
Metabase: JAR 0.16.1 on Windows, JAR 0.16.1 on Linux, Docker 0.16.1 on AWS.
Database: Amazon Redshift

**Comment by MaxSavenkov** [comment]
Oops, sorry, was misconfigured VPC

**Comment by g33klord** [comment]
@MaxSavenkov How did you solve this issue. I am new to Amazon's ecosystem.
