### ISSUE TITLE
Remove deprecated and unused `color` key from the `collection` API

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#23663]
It is still possible to pass the key `color` to the POST and PUT requests to the `/api/collection` endpoint. That key is a relic of the past that has not been used for at least 10-15 major versions.

Either mark it as deprecated or completely remove it.

**Comment by tsmacdonald** [comment]
Per Maz and others ([Slack link](https://metaboat.slack.com/archives/C01LQQ2UW03/p1676982382962659)), `collections.color` is totally obsolete and so we should do a full removal—DB column, API endpoints, the default color for new personal collections, etc.
