### ISSUE TITLE
Interrupted table scrolling on Chrome

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#23676]
**Describe the bug**

Scrolling on the question table view gets instantly interrupted. Check the attached video.

**To Reproduce**
1. New -> Question -> Sample Database -> Orders
2. Try scrolling the table constantly for a few seconds with a trackpad

**Expected behavior**
Scrolling should not be interrupted

**Information about your Metabase Installation:**
Checked starting from 42 release until the latest master. We did not have such issue back then, so I assume something from the latest chromium changes broke the scrolling.

**Additional context**
If you set `pointer-events: none` to the table root then the scrolling works correctly.
I noticed that people report similar issues in other virtual scrolling libs or grid components that use them:
https://github.com/TanStack/virtual/issues/292
https://github.com/SAP/ui5-webcomponents-react/issues/3024

**Scrolling: Chrome vs Safari**
<video src="https://user-images.githubusercontent.com/14301985/177007493-3a5b563c-f2c5-4179-90f6-114281e21c76.mov" />

**Comment by jjromary** [comment]
I will work on this issue, ok?

**Comment by alxnddr** [comment]
Could not reproduce anymore on various browsers. This got broken around v102 of Chrome and got fixed later
