### ISSUE TITLE
Changing the Database from H2 to SQL server

### ISSUE THREAD

**Issue by rohit-guitar** [metabase/metabase#2368]
Hello ,

By default Metabase utilizes the H2 DB. Is it possible to change it to SQL server or some other DB.

**Comment by agilliland** [comment]
Yep ...

http://www.metabase.com/docs/v0.16.1/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

**Comment by rohit-guitar** [comment]
@agilliland :- So can i add the support for apache cassandra to connect it to the metabase.

**Comment by agilliland** [comment]
Hi @rohit-guitar , I'm going to go ahead and close this at this point since your question has been answered.  If you are interested in Cassandra support it's best to vote for that here ... #2049
