### ISSUE TITLE
Duplicating the dashboard duplicates the question in it

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#23684]
**Describe the bug**
When question is added to the dashboard and that dashboard gets duplicated, the questions in the dashboard is duplicated as well.

**Logs**

**To Reproduce**
1. Save a question or open a saved one
2. Click on a carret icon next to the question name (in v43) or ellipsis menu in v44 to open a question context menu
3. Click on "Add this question to the dashboard"
4. The modal appears where you should "Create a new dashboard"
5. Give it a name, and save it
6. Immediately afterwards duplicate that dashboard
7. The new dashboard will have two questions in it. Refresh doesn't help and you can see two cards in a dashboard query.

**Expected behavior**
Duplicating a dashboard should not duplicate the number of cards in it.

**Screenshots**
Original dashboard
![image](https://user-images.githubusercontent.com/31325167/177200657-588c3573-44d2-4ca6-a139-bd8775acd36e.png)

Duplicated dashboard
![image](https://user-images.githubusercontent.com/31325167/177200682-ff735ba2-52c3-4d13-902d-ba48b7248e19.png)

**Information about your Metabase Installation:**
local dev, `master`, H2, Sample Database but also tested in a `release` branch on the latest commit d0ec669ff1b904b295b18e6e42d3aa2ca78da4c1 and using the latest 0.43.4 JAR [from the release page](https://github.com/metabase/metabase/releases/tag/v0.43.4)

**Severity**
I defer this to @flamber 

**Additional context**
Regression in a current release

**Comment by ranquild** [comment]
@nemanjaglumac could you double check the issue exists? I couldn't reproduce it in master (0.47-RC)

**Comment by nemanjaglumac** [comment]
Couldn't replicate, either.
Seems to be fixed.
