### ISSUE TITLE
Permission issue with custom fields with formula

### ISSUE THREAD

**Issue by sandrica89** [metabase/metabase#23682]
**Describe the bug**
Blank page when using custom fields with formula

**Logs**
```
WARN middleware.log :: GET /api/table/8/query_metadata 403 3.8 ms (3 appels de DB)
"Vous navez pas les permissions requises."
```

"Vous n'avez pas les permissions requises" means "You don't have the required permissions".

**To Reproduce**
1. Create a question with custom field with following formula: `case(isnull([field1]), [field2], [field1])`
2. Create a collection, a group and a user
3. Put the question in the new collection
4. Put the user in the new group
5. Change the group permissions to be able to view only this new collection
6. As the user, try to access the question 

**Expected behavior**
User should access the question

**Severity**
It was blocking some users to access this question. For now, we removed the custom fields to unblock them but we are losing some information.

**Additional context**
It is working properly : 
* if the user has read and write permissions on the collection
* or if the custom fields with formula are removed

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_312-heroku-b05",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_312-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.312-b05",
    "os.name": "Linux",
    "os.version": "5.4.0-107-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.11 (Debian 12.11-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.41.4",
      "date": "2021-12-10",
      "branch": "release-x.41.4",
      "hash": "471cfb9"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @sandrica89 
Please upgrade. I cannot reproduce on latest release 0.43.4: https://github.com/metabase/metabase/releases/latest
The permission error doesn't make sense that it is related to collection permissions, since it is a data permission error.
And the English error would be `You don't have permissions to do that.`

**Comment by sandrica89** [comment]
Hello @flamber, thanks for your reply.

We upgraded and still have the issue.

New diagnostic info : 

```
{
  "browser-info": {
    "language": "fr",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_312-heroku-b05",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_312-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.312-b05",
    "os.name": "Linux",
    "os.version": "5.4.0-107-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.11 (Debian 12.11-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.43.4",
      "date": "2022-06-27",
      "branch": "release-x.43.x",
      "hash": "61cc28e"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

What do you mean by "data permission"? Is there a location where we set permission per data?

**Comment by flamber** [comment]
@sandrica89 The log snippet you provided is referencing data permissions, not collection permissions.
You can set permissions in Admin > Permissions > select Data or Collection respectively.
https://www.metabase.com/learn/permissions/data-permissions.html
https://www.metabase.com/learn/permissions/collection-permissions.html

Please provide more clear steps-to-reproduce, and provide much more logs.
