### ISSUE TITLE
Date filter not working in v0.42.4

### ISSUE THREAD

**Issue by jannikbuscha** [metabase/metabase#23680]
When I search the data everything is displayed, but as soon as a data filter is on (no matter which one), the view is empty.

![image](https://user-images.githubusercontent.com/74017697/177166936-2221eee1-6b3e-455a-868e-fe126e31b829.png)
![image](https://user-images.githubusercontent.com/74017697/177167451-b61f5044-f6ff-43ba-b31c-425a6165ad18.png)

**Comment by flamber** [comment]
Hi @jannikbuscha 
It is completely impossible for us to know what is going on without errors and complete information as requested, when you open an issue.
Provide full stacktrace from Admin > Troubleshooting > Logs.
Try the latest version: https://github.com/metabase/metabase/releases/latest
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by jannikbuscha** [comment]
the error comes from mongodb 3
