### ISSUE TITLE
Keyboard interaction with tables filter

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2369]
When using the filter for the tables list in the query builder, I wish I could use the up/down arrows on my keyboard to go down to the table I want and press enter to select it instead of having to switch back to the mouse to click on it.

![screen shot 2016-04-18 at 12 51 55 pm](https://cloud.githubusercontent.com/assets/2223916/14617783/753c42ba-0564-11e6-864c-2d8e85455365.png)

**Comment by MrMauricioLeite** [comment]
Great idea!
I think TAB to select would look like a good alternative to ENTER (that may submit the query)

**Comment by mazameli** [comment]
Closing in favor of #5686 which is a more general issue with these kinds of menus.
