### ISSUE TITLE
`/field/values` endpoint contains `[object Object]` in the URL

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#23707]
**Describe the bug**
When opening a filter modal or a filter popover a `GET` request is fired to get the field values, but it has a suspiciously weird shape. I discovered this accidentally while working on https://github.com/metabase/metabase/pull/23698. Now I'm thinking that this malformed request _could be_ the reason behind all those `models` test failures.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Create a native question `select * from orders`
2. Convert it to a model
3. Click on the `Filter` to open a filter bulk modal
4. Select any of the offered fields to filter on and change the filter type (let's take a `DISCOUNT` for example)
5. Take a look at the `network` tab in dev tools and you'll see this request
`GET /api/field/field%2CDISCOUNT%2C%5Bobject%20Object%5D/values`

Here's the response
```json
{"values":[]}
```

**Expected behavior**
Not sure how this should work but it definitely looks weird and wrong. @iethree seems to agree.

**Information about your Metabase Installation:**
local dev, `master`, efafd4da2a817779c90556782a71ad2d9235bd96, H2, Sample Database

**Severity**
?

**Additional context**
@iethree found out that the same thing happens if you click on the header cell for any of the aggregated fields. Not sure how many other ways there are to reproduce it.

Tested on `42.4` and couldn't reproduce so it was most likely introduced in the 43 cycle.

**Comment by iethree** [comment]
The javascript stringification ouput was likely introduced in https://github.com/metabase/metabase/issues/23083. However, In 42.4, we still get malformed requests on fields without ids, but they're empty.

![Screen Shot 2022-07-05 at 10 21 46 AM](https://user-images.githubusercontent.com/30528226/177379720-e5b73ccd-4ebc-4eda-8022-25f663c40db3.png)

**Comment by nemanjaglumac** [comment]
Just for the reference, that is this endpoint:
https://www.metabase.com/docs/latest/api/field.html#get-apifieldfield2cfield-name2coptionsvalues

**Comment by uladzimirdev** [comment]
I was able to reproduce it in 46.6, but 47.0, 48 and 50.6 doesn't have such problem anymore, so I believe we can try to ditch old and not used code and close the issue
