### ISSUE TITLE
Make starts-with, ends-with, and contains filters case-insensitive

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2370]
#I tried creating a filter in the QB using the contains filter, and also tried it with the starts-with filter, and neither of them worked until I exactly matched the case of the substring I was looking for. This was unclear and frustrating, though I'm guessing there's an argument to be made that "sfn" isn't the same as "SFN." I think we should default to case-insensitive, and maybe put an option to make it case sensitive in the More Options area.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by camsaul** [comment]
this is case-sensitive because a lot of databases don't support case-insensitive string comparisons out-of-the-box :/

**Comment by mazameli** [comment]
So would working around those limitations be pretty costly from a time perspective?

**Comment by camsaul** [comment]
We might be able to fake it by using DB functions to lowercase the values. How to do that differs with each DB though so it isn't a quick fix.

**Comment by agilliland** [comment]
I'm not convinced that we should use case-insensitive search comparison here.

**Comment by camsaul** [comment]
Why? I originally wanted to do case-insensitive but didn't because it didn't seem feasible at the time. I seems more user-friendly.

In fact if it were possible I would want to do accent-insensitve as well, e.g. `Café` == `Cafe` or `Cam Saul` == `Cam Saül`

**Comment by camsaul** [comment]
I know Postgres/MySQL/H2 all have a function called `lower()` to lowercase text values. Not sure if it's called the same thing (or if it exists) for Crate/SQL Server/SQLite/Redshift/BigQuery but if so we could just call that on the values being compared to make this case-insensitive

**Comment by witwall** [comment]
@camsaul 
I have checked document, Crate/SQL Server/SQLite/Redshift/BigQuery supports ```lower()``` function.

I only tested Crate, SQL Server, [SQLite](https://sqlite.org/lang_corefunc.html#lower).

[Redsift](http://docs.aws.amazon.com/redshift/latest/dg/r_LOWER.html) bases on PostgreSQL

**Comment by vitorbaptista** [comment]
Any plans on implementing this?

**Comment by mazameli** [comment]
This would be helpful in lots of areas of the product, including the ID search widgets Tom's implementing in #4241.

**Comment by Globegitter** [comment]
Agreed, I think ideally there should be an option to choose, but I think default to case insensitive makes more sense.

**Comment by bertvh** [comment]
I think this is SUPER important. Upper/lowercase almost never has any meaning in a business context IMHO. I just made a huge mistake assuming the search was case insensitive.

**Comment by mazameli** [comment]
@metabase/core-developers I still want to implement this. As we're starting to spin up the conversation about autocomplete in category filter search boxes, it might be relevant to include this issue in that conversation.

**Comment by Tim-The-Third** [comment]
@mazameli is there a rough ETA on that ? As for us this is going to be pretty important part of the Dash's with no workaround other than giving everyone a list to copy and paste from..

**Comment by camsaul** [comment]
Implemented by #6864
