### ISSUE TITLE
Database settings not getting updated in metabase setup on AWS

### ISSUE THREAD

**Issue by k-akarsh** [metabase/metabase#2374]
I changed the database settings in my metabase setup running on AWS. But it still queries the database from the old settings in addition to the new database. The EC2 instance needs a restart then only it updates the db settings. 
 
*  I am using the _chrome_ browser.
*  I'm running Metabase on AWS .
*  My database is postgres.
*  My Metabase version is 0.14.1.

**Comment by agilliland** [comment]
Hi @k-akarsh , what database settings did you change and where did you change them?  Any chance you could provide a quick screenshot?

Also, we've made several updates to the way database connections work in our more recent versions of Metabase, so I recommend upgrading and seeing if you issue is resolved.
