### ISSUE TITLE
Static viz and App disagree in bar charts

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#23743]
Make a sql query that selects some values for a bar chart, but make them have labels that coincide 

```sql
SELECT * FROM (VALUES (60, 'label1'), (75, 'label2'), (40, 'label1'), (25, 'label3')) AS t (val,label);
```

The in-app visualization will stack the two 'label1' values into a single value of 100
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/6377293/177618941-db6492c8-e053-4e2c-bba0-d5d226051f49.png">

When sending in subscription (static-viz) these seem to be just stacked with the 60 value dominating (presumably the 40 is painted underneath it?)
![image](https://user-images.githubusercontent.com/6377293/177619218-3fc7be2b-788c-45e2-97f3-3eb760894bcf.png)

#### Impact
This can be quite severe. This came up because a "utilization" graph in the app had several entries above 100 but the image sent to slack had all values near 50. It turns out we had some duplicated names of the resources which were combined in the app but left independent in static viz.

**Comment by flamber** [comment]
Stacking is not supported #20752
