### ISSUE TITLE
Column order not preserved when Question is build on SQL View

### ISSUE THREAD

**Issue by twarogowski-dts** [metabase/metabase#2375]
When I use SQL View (Postgres) as a data source for Question, all columns get ordered by name (A-Z order). I need those columns to appear in order as it was defined in SQL view. Can I somehow control order of columns, either in Metadata editor or Question editor?  

*  I am using the Chrome 49 browser.
*  My computer's OS is Windows 2008.
*  I'm running Metabase 0.16.1. on Docker
*  My database is  Postgres 9.4.
*  My Metabase version is 0.16.1.

**Comment by agilliland** [comment]
Any chance you can provide a screenshot of what you are seeing?  I'm curious what kind of query you are running.
