### ISSUE TITLE
Dark primary color in data visualization makes icons almost disappear.

### ISSUE THREAD

**Issue by andre-sca** [metabase/metabase#23759]
**Describe the bug**
When using dark primary color in whitelabel, it becomes hard to see the visualization icon when creating a new question.

![image](https://user-images.githubusercontent.com/33433178/177787892-18467a7c-5d13-4403-8f14-ab4d0ee99156.png)

Only the selected one becomes white. 

**Logs**
None

**To Reproduce**
Set the primary color in the whitelabelling section to a dark color. Mine is (#021D49)

**Expected behavior**
lighter color for icons when primary color is dark.

**Screenshots**
None

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Opera GX 88.0.4412.75
- Your operating system: Linux 5.4.196-108.356.amzn2.x86_64
- Your databases: PostgreSQL
- Metabase version: v1.42.4
- Metabase hosting environment: unknown (Cloud Pro)
- Metabase internal database: PostgreSQL

**Severity**
Low. Annoying.

**Additional context**
None

**Comment by flamber** [comment]
Related to #23751
