### ISSUE TITLE
Filtering on empty cells by clicking on table is adding incorrect filter type

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#23796]
**Describe the bug**
Clicking on an empty cell and filtering on this value adds an incorrect type of filter. This has a couple side effects, the biggest being that the Save button will not be visible, and refreshing the page will simply redirect you to the original question you started from because the filter is not included in the serialized url.

**To Reproduce**
1. Go to a question that has a column with null/empty values
2. Click on a null / empty cell
3. Click the = to filter on this value
4. See the filter that is created will say "[Column] is equal to". This is implying we're checking `= null`

**Expected behavior**
I expect to see a filter where "[Column] is empty"

**Screenshots**
![chrome_tiJRPhJl9D](https://user-images.githubusercontent.com/1328979/178010855-9d486f8b-6891-430d-9787-b5260b5c8c7d.gif)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.10.16.3-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "America/Halifax"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-07-06",
      "src_hash": "16572ac7e6eeb0fa5e2986f3c30b1092f351d425",
      "tag": "v1.43.1-SNAPSHOT",
      "branch": "fixing-flaky-cypress-tests",
      "hash": "03d2884"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by oisincoveney** [comment]
Reproduced on `0.43.1`:

![Image](https://github.com/metabase/metabase/assets/25306947/7fce2c9a-86be-4b3c-aab4-7da4f88b0a30)


Unable to reproduce on `master`:


![Image](https://github.com/metabase/metabase/assets/25306947/26ffec94-649a-4e16-8a15-cc9d2b3c219a)

**Comment by snoe** [comment]
Tested for different types, e.g. here:
https://github.com/metabase/metabase/blob/master/test/metabase/lib/filter_test.cljc#L573-L574
