### ISSUE TITLE
DATABASECHANGELOG has no key

### ISSUE THREAD

**Issue by Albertsaab** [metabase/metabase#23818]
**Describe the bug**
DATABASECHANGELOG has no key and that prevent intallation on a DB with replication

**Logs**
java.sql.SQLTransientConnectionException: (conn=601448) Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

**To Reproduce**
Run migration on mysql db with sql_require_primary_key is set to true

**Expected behavior**
A generick autoincrement key can be added to prevent this problem

**Comment by flamber** [comment]
Duplicate of #7561
