### ISSUE TITLE
[Actions]  - BE Bulk Crud Create 

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#23848]
Let's focus on getting the bulk crud create json api working.

So for a table with first_name and last_name columns, both with type text, an api call like

 ``` json
    POST api/action/bulk/create/:source-table-id

    [{"first_name": "Tony", "last_name": "Shaw"},
     ...
     {"first_name": "Mary", "last_name": "Shaw"}]
 ```

Should insert n rows, and return how many rows were inserted.

Wrap a transaction around a doseq over the rows, `(actions/row-action! :create driver create-map)` on each one in the same transaction. If there's an error record which indexes had which errors, and continue to the end. Once completed roll back the whole operation, and return the errors.

- Quick sketch, happy path:
<img width="464" alt="Screen Shot 2022-07-11 at 6 18 51 PM" src="https://user-images.githubusercontent.com/343288/178380119-3c640fc4-9efa-4d15-aebd-bcd423db3dde.png">

- Quick sketch, with 2 rows that produce errors:
<img width="809" alt="Screen Shot 2022-07-11 at 6 19 10 PM" src="https://user-images.githubusercontent.com/343288/178380174-dc3cefc7-fb5d-48ab-abd8-471853e701cc.png">

**Comment by camsaul** [comment]
Implemented by #23878
