### ISSUE TITLE
Allow Filtering in Models

### ISSUE THREAD

**Issue by Markenson** [metabase/metabase#23846]
**Is your feature request related to a problem? Please describe.**

- Yes. A **MODEL** doesn't allow filtering data (or other operations) when user doesn't have autoservice permission.

**Describe the solution you'd like**

- Access control for models guided by collection permission. If a user can access model in collection, he could access all data in collection.

- Enable on each column header same commands and options available when querying a database directly.

**Describe alternatives you've considered**

- To be honest, if objective is to limit filtering capabilities by autoservice permissions, download XLS file and apply filters is already possible. But this is impractical from users view point.

**How important is this feature to you?**

- Models are powerful tool, but by using them we lost relevant features: filtering and other beautiful metabase things

**Additional context**

- A simple model made from query (no custom columns, no metadata descriptions, etc.)

![image](https://user-images.githubusercontent.com/2985140/178367060-7fd9fabd-e9e4-44a7-8edf-7fbb801beac8.png)

- We cannot filtering model (or take other actions on columns) directly on interface, but data could be downloaded and manipulated on excel for example.

![image](https://user-images.githubusercontent.com/2985140/178367138-c7e0eb36-ac57-4b65-b156-67c3afb56629.png)

- Maybe this is related to #22423

Thanks on advance!

**Comment by paoliniluis** [comment]
Hi @Markenson, the request is super similar to 22423. It's about giving users self-service analytics permissions to models, but not to the entire data source right? if that's the case, let me know so I can close this one

**Comment by Markenson** [comment]
Hi @paoliniluis! Thank you for feedback. 

"(...) giving users self-service analytics permissions to models" is the perfect definition.

Can close this one.

**Comment by flamber** [comment]
Duplicate of #22423
