### ISSUE TITLE
[Actions]  - BE Bulk Crud Update

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#23852]
Let's focus on getting the bulk crud create json api working. 

So for a table with id PK, name text, with entries for ids 1-100:

- JSON Endpoint
 ``` json
    POST api/action/bulk/update/:source-table-id

    [{"id": 1, "name": "Orange"},
     ...
     {"id": 100, "name": "Green"}]
 ```

Each map needs to cover all PK columns, or that is an error. (This is detected by `(actions/row-action! :update driver update-map)`.)

Should update n rows with the given columns and values. It should return how many rows were updated on success, and reuse the error handling code 

Wrap a transaction around a doseq over the rows, `(actions/row-action! :update driver update-map)` on each one in the same transaction. If there are errors: record which indexes had errors, continue to the end, rollback the wrapped transaction, and return the errors for the user to fix.

<details><summary>happy path</summary>
<p>
<img width="464" alt="Screen Shot 2022-07-11 at 6 18 51 PM" src="https://user-images.githubusercontent.com/343288/178380119-3c640fc4-9efa-4d15-aebd-bcd423db3dde.png">
</p>
</details>

<details><summary>2 rows that produce errors</summary>
<p>
<img width="809" alt="Screen Shot 2022-07-11 at 6 19 10 PM" src="https://user-images.githubusercontent.com/343288/178380174-dc3cefc7-fb5d-48ab-abd8-471853e701cc.png">
</p>
</details>

**Comment by camsaul** [comment]
Implemented by #24036
