### ISSUE TITLE
"Last 12 months" filter uses < date_trunc('month', now()), which omits results from the last month

### ISSUE THREAD

**Issue by KonnikPahoni** [metabase/metabase#23854]
**Describe the bug**

A question like this:

![image](https://user-images.githubusercontent.com/13286998/178483365-e0e3a893-6e68-492d-b415-c4b991548dd4.png)

will produce the following SQL:

```
SELECT date_trunc('week', "public"."analytics_jobad"."created_at") AS "created_at", count(*) AS "count"
FROM "public"."analytics_jobad"
WHERE ("public"."analytics_jobad"."created_at" >= date_trunc('month', (now() + (INTERVAL '-12 month')))
   AND "public"."analytics_jobad"."created_at" < date_trunc('month', now()))
GROUP BY date_trunc('week', "public"."analytics_jobad"."created_at")
ORDER BY date_trunc('week', "public"."analytics_jobad"."created_at") ASC
```

**To Reproduce**
1. Go to a model with timestastamp value (e.g. created_at)
2. Create a groupby table (grouping over the created_at)
3. See that because of `AND "public"."analytics_jobad"."created_at" < date_trunc('month', now())`, results for objects created within the last month are omitted.

**Expected behavior**

It should be `< date_trunc('second', now())` or something instead

**Information about your Metabase Installation:**

Version 0.43.2. Version 0.43.4 has the same bug.

**Severity**

**Quite serious as it distorts results!**

**Comment by paoliniluis** [comment]
Hi, I just added a few results in the sample dataset from last month and it worked
![image](https://user-images.githubusercontent.com/1711649/178490492-ea3a4ea6-f412-4e0a-9449-e3e354041ac5.png)

Can you provide more details about the database engine you're using? the data that you don't see?

**Comment by KonnikPahoni** [comment]
I am using PostgreSQL.

Please, send me the full groupby query as described in the ticket.

**Comment by flamber** [comment]
@KonnikPahoni The previous/future filter has always been without current period unless you specifically select it:
![image](https://user-images.githubusercontent.com/1447303/180204425-ed1613cd-10a2-46ed-831a-b02a9136bde7.png)

**Comment by KonnikPahoni** [comment]
@flamber oh! Thank for pointing out! Then it is not a bug from technical prospective. Rather a bug in the logic. Of course if I want to get TWELVE last months, most probably I want 12 months from now().
