### ISSUE TITLE
Metabot shouldn't require quotes around card names

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2385]
Eg in the below `metabot show Downloads by Type` should render card 2 as it is a direct match
![Uploading Screen Shot 2016-04-19 at 6.30.27 PM.png…]()

Adding quotes is a pain in the ass, and I've watched myself and most other people get it wrong.

**Comment by salsakran** [comment]
@camsaul what would we need to do for quotes to not be required?

**Comment by camsaul** [comment]
This should be doable with some minor tweaks.
