### ISSUE TITLE
Error message misplaced when duplicating question if user is under `no self-serve` permission.

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#23861]
### Steps to reproduce:

1. In test question-management.cy.spec.js, run any test with user "nodata" and signing in with `cy.signIn("nodata")`.
2. After test is done, and it may pass, duplicate the question.

You should see the misplaced error message like below.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/380816/178528664-5026e998-9e50-4b14-bd43-ea6020f56ea2.png">

**Comment by nemanjaglumac** [comment]
I've noticed this error when duplicating dashboards as well. Not too long ago (maybe 2-3 weeks) the error was presented within the modal.
