### ISSUE TITLE
Add option to view the raw SQL created by the query builder

### ISSUE THREAD

**Issue by hopsoft** [metabase/metabase#2387]
It would be great if there was an option to view the built SQL so we can hand it off to our DBAs for performance tuning. It would also make the query builder more portable & useful in supporting other tools & use cases.

**Comment by salsakran** [comment]
would #607 work for you?

**Comment by camsaul** [comment]
@hopsoft the generated SQL is printed to the console logs whenever a query is ran

**Comment by that0n3guy** [comment]
@camsaul I don't see anything printing to the console... where do you see this?

**Comment by camsaul** [comment]
not the browser console, the terminal you used to launch Metabase

**Comment by hopsoft** [comment]
I was hoping for something more accessible to the casual user, but I can pull the queries from the logs for now.
