### ISSUE TITLE
Decouple UI and backend Server

### ISSUE THREAD

**Issue by rohit-guitar** [metabase/metabase#2388]
Hello ,

I was looking into to build UI project and backend server separately intead of making one fat jar file. 
Is there any documentation i can follow ?

**Comment by salsakran** [comment]
What are you trying to accomplish with this?

We ship it as an uberjar to keep deployments simple and reduce the chances of bad deploys or misconfigurations.

**Comment by rohit-guitar** [comment]
I want to add the UI to an existing project(angular) and that UI has a running backend which is decopuled from the fat jar.

**Comment by salsakran** [comment]
are you planning on open sourcing your project?

**Comment by rohit-guitar** [comment]
I might do it but i have to see the other aspects before making any decisions

**Comment by rohit-guitar** [comment]
But decoupling is also good so we can embedd it anywhere

**Comment by salsakran** [comment]
Practically speaking, we will not be decoupling the build artifacts or generalizing the front end to be accessible to other backends.

Please read and respect the license we've released our code under - https://github.com/metabase/metabase/blob/master/LICENSE.txt

**Comment by rohit-guitar** [comment]
@salsakran :- Thanks Got it.
