### ISSUE TITLE
Could not initialize class com.google.cloud.bigquery.BigQueryOptions (0.44.0 RC1)

### ISSUE THREAD

**Issue by klemenb** [metabase/metabase#23895]
**Describe the bug**

Databases using the "BigQuery" engine are failing with "Could not initialize class com.google.cloud.bigquery.BigQueryOptions".

**To Reproduce**
1. Have a working Metabase 0.43.4 installation
2. Upgrade Metabase to 0.44.0 RC1
3. All questions using a BigQuery database are failing

**Expected behavior**

BigQuery databases work as they did before.

**Information about your Metabase Installation:**

- Your browser and the version: Edge 103
- Your operating system: Windows
- Your databases: BigQuery, MySQL
- Metabase version: 0.44.0 RC1
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**

Blocking issue for all our BigQuery data.

**Comment by paoliniluis** [comment]
Hi, which driver were you using? can you include the diagnostic info of 43.4?

**Comment by klemenb** [comment]
I am using what I assume is the latest BigQuery driver as I was doing a migration from the old one a few releases ago.

Diagnostic info (for 0.44.0 RC1):

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.49",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.181-99.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "bigquery-cloud-sdk",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.20-11"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-07-12",
      "tag": "v0.44.0-RC1",
      "branch": "master",
      "hash": "bc74316"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
RC versions are not meant for production instances, just for testing
