### ISSUE TITLE
Saved Questions tweaks

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2389]
Follow up to #2325 

- [x] selecting a question shifts the whole page a bit
- [ ] unarchive icon
- [x] scrollbar space still showing on hover even if the sidebar doesn't need to scroll
- [x] emoji in sidebar misalgined
- [x] labels with long names can wrap strangely ([example](https://www.dropbox.com/s/y0qy219lga3v2pj/Screenshot%202016-04-20%2015.26.21.png?dl=0))
- [x] label vertical rhythm can get out of hand with a ton of labels ([example](https://www.dropbox.com/s/4apb2jbk9dnho3e/Screenshot%202016-04-20%2015.27.00.png?dl=0))
- [x] alignment of the search box with the rest of the listing is triggering OCD angst
- [ ] archive icon missing in IE - 11
- [x] If you archive all your questions, the `All questions` tab should present the empty state
- [x] Empty state content for `Recently Viewed` seems to be missing its icon

Tom

- [x] remove all the JS console logging
- [x] when switching routes the search box should clear.  aka you shouldn't search for something in "all" questions, then click on favorites and have the search retained
- [x] when switching routes the questions listing should scroll to the top
- [x] remove legacy `/card` UI, redirect to `/questions`

**Comment by mazameli** [comment]
If you enter in a search term in the filter field when you're looking at `All Questions` and then go to any other section (Label editing, Saved by Me, etc.), the search term persists. I'm not sure that that's expected. I would have expected the filter to get cleared out when I left the current view.
