### ISSUE TITLE
something goes wrong with filter

### ISSUE THREAD

**Issue by tw-Xiangfei** [metabase/metabase#23939]
**Describe the bug**
I have apply a field filter for my report
when I type anything in the filter and press Return, what I type will be add to filter field. Details are shown as below.
![image](https://user-images.githubusercontent.com/106570521/178878019-13589063-d171-4729-8f18-8937ec776981.png)
![image](https://user-images.githubusercontent.com/106570521/178879500-8ede7a05-5151-4765-964c-2b2acf725b93.png)

**To Reproduce**
1. Go to any question or dashboard with field filter
2. Click on filter, type any words and press "return" on keyboard
3. The words will be added to filter field.

**Expected behavior**
Search for results in field related to the content I input, or show no data.

**Comment by paoliniluis** [comment]
Can you send Diagnostic info?

**Comment by flamber** [comment]
That's on purpose, so you can include values, which might not exist in your database yet or haven't been picked up by scan.
