### ISSUE TITLE
`metabase.driver.ddl.postgres` should be named `metabase.driver.postgres.ddl`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#23938]
Postgres implementations should all live in `metabase.driver.postgres.*` -- everything should live in the `postgres` folder. That way if we every wanted to move the Postgres driver somewhere else we just need to move `src/metabase/driver/postgres.clj` and `src/metabase/driver/postgres/` instead of moving stuff from a bunch of places in the codebase. (It's also the pattern we've used for everything else in the codebase)

Same goes for `sql` and `mysql.`

Ping @snoe since you added this in #23443 and @escherize since you reviewed it. No worries -- it's an easy fix -- but I just wanted to make sure you guys knew the pattern in case this comes up again

**Comment by dpsutton** [comment]
@snoe @escherize I can tackle this tomorrow if yall want more time on actions. But also this is a very mechanical fix so if you want some mindless work to take a break from actions that's fine to. But I can help if needed.
