### ISSUE TITLE
Column type gets converted to string from numeric when using as a filter while framing question

### ISSUE THREAD

**Issue by Eizone** [metabase/metabase#23945]
**Describe the bug**
A column in our DB is of type numeric(28, 8), it reflects in the Metabase data store as a Decimal (when opening the table available in the data source it identifies as a decimal value with options for conditions). But when I try to create a question by pulling that table and using that decimal column in the filters, it is identified as a String. It has only conditions to check if it's equal (=) not equal (!=) and also the column doesn't have a '#' in front of it, instead has a circle 'O' which says its string. 

**Screenshots**
The below image shows that when looking at the data store it's identified as a Decimal:
![image](https://user-images.githubusercontent.com/13060361/178782313-a152101e-3a22-4f92-9c3f-4f6e722b2b49.png)
The below image shows when used as a filter it's considered as a string:
![image](https://user-images.githubusercontent.com/13060361/178782606-8ef289e0-42ed-4a6f-a979-43c270d2d715.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Look for a column that is of type Numeric in your DB.
2. Verify that it's of type decimal in the Metabase Data store.
3. Try to use the column as a filter while framing a question.

**Expected behavior**
The column should appear as a decimal and not as a string.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 102.0
- Your operating system: Pop!_OS 22.04 LTS
- Your databases: Redshift
- Metabase version: Metabase v0.43.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
It's blocking some users from framing visualisations to make decisions.

**Comment by flamber** [comment]
Hi @Eizone 
Please upgrade to 0.43.4: https://github.com/metabase/metabase/releases/latest
I don't know what "Metabase Data store" is - the application database or Data Model?
Please include the field metadata by going to the URL `/api/field/123`, where 123 is the field ID, which you can see by going to Admin > Data Model > (db) > (table) > (column) :gear: > the browser URL will be `.../123/general`

**Comment by Eizone** [comment]
![image](https://user-images.githubusercontent.com/13060361/185004168-21d295f9-2732-434d-8dc9-3cb6e669ce54.png)
I think we are on x.43.x
Also, sorry I meant the application database. Below I have attached the screenshot of the field. 
![image](https://user-images.githubusercontent.com/13060361/185004445-583ba5a6-6503-4a94-bca0-44b7850a49d7.png)
The `Data type` is `type/Decimal`
The `Field type` is `No field type`

So when being used in filter the type is taken as string/text for this field but it should be a Decimal as the data type is Decimal.

**Comment by flamber** [comment]
@Eizone So you've moved from self-hosting to Metabase Cloud during the past month.
Post "Diagnostic Info" from Admin > Troubleshooting.
And go to the URL `/api/field/72160` and include the output (you can redact sensitive information with `REDACTED`, but don't change the structure of the output).

**Comment by Eizone** [comment]
@flamber 
Diagnostic Info:
{
 "browser-info": {
 "language": "en-US",
 "platform": "Linux x86_64",
 "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0",
 "vendor": ""
 },
 "system-info": {
 "file.encoding": "UTF-8",
 "java.runtime.name": "OpenJDK Runtime Environment",
 "java.runtime.version": "11.0.16+8",
 "java.vendor": "Eclipse Adoptium",
 "java.vendor.url": "https://adoptium.net/",
 "java.version": "11.0.16",
 "java.vm.name": "OpenJDK 64-Bit Server VM",
 "java.vm.version": "11.0.16+8",
 "os.name": "Linux",
 "os.version": "5.4.196-108.356.amzn2.x86_64",
 "user.language": "en",
 "user.timezone": "GMT"
 },
 "metabase-info": {
 "databases": [
 "redshift"
 ],
 "hosting-env": "unknown",
 "application-database": "postgres",
 "application-database-details": {
 "database": {
 "name": "PostgreSQL",
 "version": "11.13"
 },
 "jdbc-driver": {
 "name": "PostgreSQL JDBC Driver",
 "version": "42.3.2"
 }
 },
 "run-mode": "prod",
 "version": {
 "date": "2022-07-29",
 "tag": "v1.43.4.2",
 "branch": "release-x.43.x",
 "hash": "7809f82"
 },
 "settings": {
 "report-timezone": null
 }
 }
}

URL Info:

{"description":null,"database_type":"numeric(28,8)","semantic_type":null,"table_id":1171,"coercion_strategy":null,"table":{"description":null,"entity_type":"entity/GenericTable","schema":"dbt","db":{"description":null,"features":["full-join","basic-aggregations","nested-field-columns","standard-deviation-aggregations","expression-aggregations","percentile-aggregations","foreign-keys","right-join","left-join","native-parameters","nested-queries","expressions","set-timezone","regex","case-sensitivity-string-filter-options","binning","inner-join","advanced-math-expressions"],"cache_field_values_schedule":"0 0 21 * * ? *","timezone":"UTC","auto_run_queries":false,"metadata_sync_schedule":"0 0 * * * ? *","name":"Analytics Warehouse","settings":null,"caveats":null,"creator_id":null,"is_full_sync":true,"updated_at":"2022-08-16T23:29:28.947582Z","cache_ttl":null,"details":{"additional-options":null,"cloud-ip-address-info":null,"db":`REDACTED`,"password":`REDACTED`,"tunnel-host":`REDACTED`,"let-user-control-scheduling":true,"port":`REDACTED`,"advanced-options":true,"schema-filters-type":"all","host":`REDACTED`,"tunnel-enabled":true,"tunnel-auth-option":`REDACTED`,"tunnel-port":`REDACTED`,"tunnel-private-key":`REDACTED`,"user":`REDACTED`,"tunnel-user":`REDACTED`,"tunnel-private-key-passphrase":`REDACTED`},"is_sample":false,"id":2,"is_on_demand":false,"options":null,"engine":"redshift","initial_sync_status":"complete","refingerprint":null,"created_at":"2019-09-27T21:53:27.645Z","points_of_interest":null},"show_in_getting_started":false,"name":"_processingrequest_enriched","caveats":null,"updated_at":"2021-10-31T09:23:23.339333Z","active":true,"id":1171,"db_id":2,"visibility_type":null,"field_order":"database","initial_sync_status":"complete","display_name":"Processing Request Enriched","created_at":"2019-09-27T21:53:40.23Z","points_of_interest":null},"name":"first_processing_duration_h","fingerprint_version":4,"has_field_values":"none","settings":null,"caveats":null,"fk_target_field_id":null,"dimensions":[],"updated_at":"2021-09-24T04:41:48.319076Z","custom_position":0,"effective_type":"type/*","active":true,"nfc_path":null,"parent_id":null,"id":72160,"last_analyzed":"2020-07-10T11:13:29.992278Z","position":0,"visibility_type":"normal","preview_display":true,"display_name":"First Processing Duration H","database_position":89,"name_field":null,"fingerprint":{"global":{"distinct-count":8928,"nil%":0.1068}},"created_at":"2020-05-22T06:21:52.843448Z","base_type":"type/Decimal","points_of_interest":null}

Thanks!

**Comment by flamber** [comment]
The Redshift documentation says that the maximum precision you can use is 19: https://docs.aws.amazon.com/redshift/latest/dg/r_Numeric_types201.html#r_Numeric_types201-decimal-or-numeric-type
Try using a different column type or precision.

**Comment by Eizone** [comment]
The Redshift documentation says the **maximum precision you can use is 38**. and the recommended for **positive is 19**. But that should still recognise as Decimal irrespective of the precision mentioned. 

Other tools that we use like redash, recognise this field as a decimal, so Metabase should too. This doesn't seem to be an issue with redshift.

**Comment by Eizone** [comment]
@flamber is there anything else you can think of that could help?

**Comment by flamber** [comment]
@Eizone No matter what I do, then when I create a `ALTER TABLE public.my_table ADD high_precision numeric(28, 8) NULL`, then Metabase detects it as `database_type: numeric` and sets it as `effective_type: type/Decimal`.
But somehow your column is `database_type: numeric(28,8)` with an invalid `effective_type: type/`.

Try going to Admin > Data Model > (redshift) > (table) > click Visibility=Hidden on the table, then back to Queryable.
Wait 10 seconds (it's doing sync in the background).
Then change the Field Type of `first_processing_duration_h` from "No special type" to "Share" and change it back "No special type".
Now if you go to `/api/field/72160`, then it should have corrected everything (database_type, effective_type and fingerprint).

**Comment by Eizone** [comment]
@flamber  Thank you!! that worked. Cheers.
