### ISSUE TITLE
Dashboard filter mappings can't be edited on mobile

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#23962]
**Describe the bug**
On mobile, if you edit a dashboard and click on a parameter, it opens the sidebar and fills the entire screen with it, blocking the dashboard contents. This means you can't set any new parameter mappings.

**Expected behavior**
Not sure; seems pretty challenging design-wise to get this to work nicely. But if you can create and edit the parameters themselves on mobile, it seems like you should also be able to create mappings.

**Screenshots**
<img width="367" alt="image" src="https://user-images.githubusercontent.com/32746338/179021347-910deb9a-785b-432c-8442-663fb8d5a2a3.png">

**Comment by Toledodev** [comment]
Hey @noahmoss, I still don't understand the problem, when clicking on made a filtering happen and it shows what is filtered. Wouldn't that be the expected behavior?

**Comment by WiNloSt** [comment]
[We discussed that](https://metaboat.slack.com/archives/C057T1QTB3L/p1689971581589849) the fix is to prevent dashboards from being editable on mobile.
