### ISSUE TITLE
"Our analytics" appears on "Save question" collection search header even when user doesn't have access to it

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#23981]
**Describe the bug**

A user without read permissions to "Our analytics" collection still sees "Our analytics" on the collection search header when saving a question for the first time. Perhaps this copy should be removed, since "our analytics" is simply the root collection for the organisation, and these users don't see our analytics anywhere else. So it doesn't need to be named here.

You can see it in the screenshot below of react devtools that our "Our analytics" appears as part of the Breadcrumbs component.

![image](https://user-images.githubusercontent.com/39073188/179126101-d3e90d85-fff2-4e36-b993-79e419d47773.png)

The same applies when you try to move a question:
![image](https://user-images.githubusercontent.com/39073188/179130313-580ce1ba-1db3-40d2-ab99-a3ea34c6c75e.png)

**To Reproduce**

1. Admin > Permissions > Collections - set "Our analytics" to No access for All Users
2. Login as user
3. Create a new question, click "Save".
4. Open the collection drop-down

Related to https://github.com/metabase/metabase/issues/20716

**Comment by Toledodev** [comment]
Hey @calherries , "our analytics" was supposed to appear in the sidebar if I login as a user?
![Screenshot from 2022-07-15 10-08-35](https://user-images.githubusercontent.com/87545086/179229410-a173a04f-6b57-4744-a2dc-1240d792370c.png)

**Comment by nemanjaglumac** [comment]
@Toledodev if you log in as **which** user? What kind of permissions does that user have?
1. curate
2. view
3. no access

?

**Comment by Toledodev** [comment]
@nemanjaglumac no access
