### ISSUE TITLE
There is no space in the screen of a mobile device to show data when a Question has several filters

### ISSUE THREAD

**Issue by AlvaroNortes** [metabase/metabase#23983]
**Describe the bug**
Since we updated to the version v0.43.4 (Built on 2022-06-27) on Elastic Beanstalk, if you go to your mobile we tried with Iphone at least, you can't see questions with several filters because the filters are fixed on the screen and there are not space to show the data.

**To Reproduce**
1. Go to your mobile phone
2. Click on any question with several filters
The data does not appear in the screen because the filter are fixed in the screen and there are not space for the data

**Expected behavior**
When you scroll down, filters stay up, and you can show the tables with data

**Screenshots**
![image](https://user-images.githubusercontent.com/42941129/179159947-1df4d589-8b23-4d53-8cd3-0b9357d715fb.png)

**Information about your Metabase Installation:**
v0.43.4 (Built on 2022-06-27) on Elastic Beanstalk

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
Safari/Chrome
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
Iphone 11 pro
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
Snowflake
- Metabase version: (e.g., 0.19.3)
v0.43.4 
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
Elastic Beanstalk
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)
Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

Honestly I think that the whole mobile UI is not usable since this bug is happening

**Comment by flamber** [comment]
Very related to #22137, historically to #20879
