### ISSUE TITLE
Do not offer "bulk" selection from the archive page to readonly users

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#24018]
**Describe the bug**
Users with read only permissions to a certain collection can see that collection items. We show those items even in the archive. However, when readonly user visits the archive, they are offered "bulk" selection mode (hover over the icon and select by clicking the checkbox). That's pointless and leads to permission errors being displayed on the screen because such users are not allowed to unarchive, nor to delete such questions (which are the options they are presented).

**Logs**
`403` responses (backend is correctly handling requests) - this is a FE thing

**To Reproduce**
1. As admin, set "View" access to "Our analytics" for all users
2. From the root collection, archive at least one question/dashboard
3. Log in as normal user
4. Go directly to the archive `/archive`
5. You are able to "bulk select" archived items and footer appears with "Unarchive" and "Delete" buttons
![image](https://user-images.githubusercontent.com/31325167/179288786-dce23025-36fa-4981-bceb-7747a30a57fe.png)

6a. Click "Unarchive" and you'll end up with the permission error
![image](https://user-images.githubusercontent.com/31325167/179288875-e1c23032-587e-495b-a93d-f8caaf9c15f9.png)

6b. Click on "Delete" - nothing happens in UI but the console shows `403` for a `DELETE` request, followed by **two** (why two?) `GET requests` to the same endpoint `/api/search?archived=true`
![image](https://user-images.githubusercontent.com/31325167/179289300-11330a88-7f94-49c1-9b04-09443bdaa8c9.png)

Btw, delete request has extremely weird and long url params:
```
/api/card/1?_dispatch=&description=&archived=true&collection_position=&table_id=&bookmark=false&database_id=&name=Orders&table_schema=&collection_authority_level=&updated_at=2022-07-15T20%3A26%3A56.052&moderated_status=&dataset_query=&table_description=&dashboardcard_count=0&context=&scores=&scores=&scores=&scores=&scores=&scores=&initial_sync_status=&table_name=&collection=&model=card
```

**Expected behavior**
Do not offer "bulk" selection mode at all to readonly users since they cannot do anything with the archived items.

**Information about your Metabase Installation:**
local dev, master, https://github.com/metabase/metabase/commit/e7b4dc62729c30dcc58512ebf156d6182b51f3ae, H2, Sample Database

**Severity**
P3 since backend correctly handles requests and fe doesn't break

**Comment by gusaiani** [comment]
@nemanjaglumac, I was looking at this one before I saw the mention of @kulyk 

Maybe for clarification: the non-admin user should have bulk actions for their own archived entities, correct?
If the above is true, then this is a bit more fine-grained than what's currently in the issue description?
Just making sure.

**Comment by nemanjaglumac** [comment]
@gusaiani the user should have bulk action control for items that live in any collection that user can curate.

**Comment by gusaiani** [comment]
@nemanjaglumac Yes.

Should they even see an archived question that had lived in a collection they can't curate? 🤔

And how come you're replying on Friday at like 10PM your time? xD <3

**Comment by nemanjaglumac** [comment]
> Should they even see an archived question that had lived in a collection they can't curate? 🤔

That is a good question for the product. Personally, I don't think there's much sense in even showing them such **items** (not just questions, remember). 

> And how come you're replying on Friday at like 10PM your time? xD <3
Try 11PM.
I'm always on the lookout 👀

**Comment by kulyk** [comment]
This would probably need some backend work too. Currently, the FE doesn't have any info to figure out if a user has permission to unarchive or permanently delete an item. Attaching a sample JSON retrieved from `GET /api/search?archived=true`. I'd expect `collection` to have the `is_write` flag. Going to also add the "Backend" label to the issue

<img width="736" alt="CleanShot 2022-07-18 at 18 29 51@2x" src="https://user-images.githubusercontent.com/17258145/179568947-cc302589-4e60-4df4-a2e4-0bb1664a26de.png">

**Comment by luizarakaki** [comment]
1. Users should see archived items from collections they have view-only access.
If we didn't show them, it would be confusing as they know something is in the archive but can't find.

2. I think we should just remove the selection box of items the user can't unarchive/delete. If the user clicks on "select all" it selects only items they can archive/delete. If they can't archive or delete anything, they don't see the select all button.

**Comment by luizarakaki** [comment]
I don't think we need a visual representation of what they can do. It follows the same pattern of the rest of the product (if the user can't do something, they don't see the button that performs the action)

**Comment by JesseSDevaney** [comment]
This issue will now require back-end work.

Some archived items returned by the network request to `/search?archived=true` are not being labeled as writable or not - no `can_write` property is being attached to the item. This is an issue because we do not want to show an archived item with buttons to act upon it if they do not have the permissions to do so in the first place.

The proposed solution options are: 
1. return all items from `/search?archived=true` with their `can_write` attribute attached in the network request directly, or
2. all collections (including archived ones) should return with a valid `can_write` attribute (to assess whether or not the user can do anything with that archived collection or archived item belonging to an archived collection)

---
Full Dicussion: https://metaboat.slack.com/archives/C010L1Z4F9S/p1696008216754639
