### ISSUE TITLE
"Our analytics" still shown as a first choice when creating new collection for users without curate permissions

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#24015]
**Describe the bug**
After https://github.com/metabase/metabase/pull/23887 we are now one step closer to properly handling users without permissions to the root collection. However, there's one more issue that needs to be solved.

If a user with `view` or `no access` permissions to the root collection navigates to the `/collection/root` they can still click on the `...` menu in the sidebar where they are offered to create new collection.

If they click that, the first collection offered is "Our analytics" which completely breaks frontend. It results in a warning in the dev mode and can result in a blank screen in production.
![image](https://user-images.githubusercontent.com/31325167/179280367-c1206b5f-7b16-45fb-9586-df22a60a55db.png)

> **Note**
> This happens only the first time!
> If you discard the warning and repeat all steps again, it will properly filter out the root collection and user's personal collection will be the only choice
![image](https://user-images.githubusercontent.com/31325167/179281123-4d7f2efc-5c56-4dc1-8583-d0fdaa9d754e.png)

**Logs**
N/A

**To Reproduce**
**READONLY**
1. As admin set "View" permissions for All users to "Our analytics"
2. Log in as normal user - you will be redirected to the home page `/`
- scenario a
    3. Click on the "New" button in the app top bar
    4. Click on "Collection"
    5. Modal will appear with "Our analytics" as the first choice and shortly after that frontend will break (blank screen in production)
![image](https://user-images.githubusercontent.com/31325167/179282075-1ac381f7-13d2-42a6-bbf1-66ed94c1767e.png)

-scenario b
    3. Click on the `...` menu next to the word "Collections" in the sidebar
    4. Two options will be suggested - "New collection" and "View archive"; Click on "New collection"
    5. Modal will appear with "Our analytics" as the first choice and shortly after that frontend will break (blank screen in production)
![image](https://user-images.githubusercontent.com/31325167/179282075-1ac381f7-13d2-42a6-bbf1-66ed94c1767e.png)

**USER WITHOUT ACCESS**
1. As admin set "No access" permissions for All users to "Our analytics"
Both scenarios "a" and "b" from above still stand and will result in same errors
2. If you navigate to the root collection by pasting `/collection/root` you should now see "You don't have permissions to do that"
3. But you'll still be offered "Our analytics" from both `...` menu in the sidebar and from the "New" button in the top bar

**Expected behavior**
Do not offer "Our analytics" to users without "curate" access and most certainly under no circumstances do not end up in a blank screen.

**Information about your Metabase Installation:**
local dev, `master`, e7b4dc62729c30dcc58512ebf156d6182b51f3ae, H2, Sample Database

**Severity**
Although it happens only the first time when you attempt to create new collection, I'm gonna give this P2 because of the blank screen. 

**Additional context**
Note to developers - this happens if user is either in:
1. Our analytics or
2. Home page

This is an important bit.
We handle this correctly if user attempts this same action from within their own personal collection or any other collection they have curate permissions for.

**Comment by calherries** [comment]
I tested on `master`, `72885b788f`, so this bug preceded the latest changes in https://github.com/metabase/metabase/issues/23981.
