### ISSUE TITLE
MongoDB No fields found for table "levels".

### ISSUE THREAD

**Issue by k2xl** [metabase/metabase#24039]
Tried today with latest dockerfile deploy. Connected to MongoDB via connection string - yet I'm seeing this error pop up that it can't find fields. The table names do show up however.

**Comment by paoliniluis** [comment]
I'm guessing this is a duplicate of https://github.com/metabase/metabase/issues/10343

**Comment by k2xl** [comment]
Aye most likely it is that. Thanks
