### ISSUE TITLE
"Custom..." model refresh setting does not work on first request

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24053]
**Describe the bug**
The "custom" model refresh option does not work, it just refreshes the page if you try to move the sync on the first try from 6 hours to custom as soon as you set up the instance

**Logs**
NA

**To Reproduce**
1) set up a new Metabase instance
2) go to settings->admin->caching->enable model caching-> change to "Custom"
3) see how the page gets refreshed without doing nothing

But, if you change to, e.g. hour, and then to "Custom..." it works

**Expected behavior**
Make it work on the first shot :)

**Screenshots**
![custom_caching](https://user-images.githubusercontent.com/1711649/179523933-fb049c3f-0e2d-4964-80f4-c23aed0b6391.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.44.0-RC1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
Cosmetic

**Additional context**
NA

**Comment by MuriloAmarals** [comment]
Hey @paoliniluis , I'm already working on this issue!
