### ISSUE TITLE
Can't scroll to see all changes in revision history items

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2406]
A scrollbar appears here, but it's not scrollable. 
![screen shot 2016-04-22 at 10 59 24 am](https://cloud.githubusercontent.com/assets/2223916/14750732/2900021e-087b-11e6-8747-e9b92037ec6e.png)

I think instead of scrolling at all, we should just have the list of items wrap to the next line.

**Comment by tlrobinson** [comment]
Duplicate of #2313?

**Comment by mazameli** [comment]
Yes, sorry!
