### ISSUE TITLE
Ellipses icon is super small in admin panel

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2409]
The dot dot dot (ellipses) menu icon is super small in the segments and metrics list. You can barely see it:
![screen shot 2016-04-22 at 12 24 30 pm](https://cloud.githubusercontent.com/assets/2223916/14752617/2fd19f94-0885-11e6-9563-f700d0a89d18.png)

Also in the People list:
![screen shot 2016-04-22 at 12 18 26 pm](https://cloud.githubusercontent.com/assets/2223916/14752601/0cb843c8-0885-11e6-868b-455ef889dc69.png)

I feel like this happened recently. Here's the design and expected appearance. It should be the same as the dot dot dot icon in the query builder:
![screen shot 2016-04-22 at 12 23 58 pm](https://cloud.githubusercontent.com/assets/2223916/14752649/5d1c230c-0885-11e6-9e1d-137347c20290.png)

*  I am using the Chrome browser.
*  My computer's OS is OS X 10.11.4 (El Capitan).
*  I'm running Metabase on our stats instance. 
*  My Metabase version is whatever's on stats.

**Comment by tlrobinson** [comment]
Looks like it broke between v0.15.0 and v0.15.1

**Comment by tlrobinson** [comment]
This is due to the addition of default size of 16 in v0.15.1: https://github.com/metabase/metabase/blob/master/frontend/src/components/Icon.jsx#L21-L24

I suppose we should just make an EllipsisIcon with the standard default size (32?)
