### ISSUE TITLE
Selected DB isn't maintained when switching to Raw SQL mode if table isn't selected

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2410]
Selected DB isn't maintained when switching to Raw SQL mode. I suppose this is because I haven't selected a Table:

![out](https://cloud.githubusercontent.com/assets/1455846/14753100/eb3740a2-0887-11e6-998f-e7614dce8c90.gif)

But if I select a Table, I can't switch to SQL mode. 

![out](https://cloud.githubusercontent.com/assets/1455846/14753179/6853e50e-0888-11e6-87de-aa1dec4c6c91.gif)

The database selection menu calls the user to action when "New Question" is pressed, but it is too easy to fall in the trap of selecting a DB, then a Table, then being stuck in Query Builder mode. I find myself having to go back and press "New Question" a second time because I keep forgetting I need to ignore the call to action if I want to write a raw SQL query.

I posit that if a person arguably very familiar with the product is confused by this interaction a novice user may struggle even more. Should we consider ways to make this less confusing?

**Comment by tlrobinson** [comment]
Related #1757

**Comment by mazameli** [comment]
This should be made irrelevant by #4642.

**Comment by flamber** [comment]
@camsaul 
I cannot reproduce this in 0.31.2 - neither of the two.
That was cool to see how it used to work in a very early version - blast from the past :-)

**Comment by flamber** [comment]
Closing issue because the new query browser in 0.33.0 changed how "View the SQL" works.
