### ISSUE TITLE
Clear out existing Sessions on password reset

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#24130]
In 

- https://github.com/metabase/metabase/issues/14313
- https://github.com/metabase/metabase/pull/15473

We added code to send users an email the first time they log in from a new device. The emails say

> If this was you, you can safely disregard this email. If this wasn't you, you should change your password immediately.

I was thinking about this. If someone changes that password because they were worried about a bad actor logging in to their account, that doesn't keep the bad actor from continuing to cause trouble until their session expires and they have to log in again. On password reset we should immediately clear all existing sessions for the user that reset their password so everyone is forced to log in again with the new password.

**Comment by flamber** [comment]
Unless we've just changed something, then this already happens on password change, which causes #5063.

**Comment by qwef** [comment]
I think this already happens, tested it out locally. The reset_password endpoint https://github.com/metabase/metabase/blob/master/src/metabase/api/session.clj#L254 calls `user/set-password!` which kills existing sessions, https://github.com/metabase/metabase/blob/master/src/metabase/models/user.clj#L358.
