### ISSUE TITLE
"Delete this alert" button is not translated, and not centered in button

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#24156]
**Describe the bug**
In the alert editing modal in the query builder, the section for deleting an alert looks a bit weird when the user language is German. The "Delete this Alert" text is not translated, and the button is stretched vertically but the text is not centered.

**To Reproduce**
1. Log in as an admin
2. Change your user language to German (I'm assuming this is an issue for other languages too but I haven't checked)
3. Create an alert for a question
4. Open the alert modal and scroll down to the "Danger Zone"

**Screenshots**
<img width="605" alt="image" src="https://user-images.githubusercontent.com/32746338/180048417-03f9cd52-36c1-49a0-a2aa-4d960dd1b0e2.png">

**Information about your Metabase Installation:**
Current master

**Severity**
Mild

**Comment by usmailaabdoul** [comment]
Hi @noahmoss please can you provide a loom video on how to get to this alert modal?

**Comment by flamber** [comment]
@usmailaabdoul Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
https://www.metabase.com/docs/latest/users-guide/15-alerts.html
