### ISSUE TITLE
Automatically hide Django framework tables

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2419]
We should automatically hide things like migration tables, and other framework/orm cruft. 

- [ ] build out the list of standard django tables that we can safely consider cruft.
- [x] add code to sync process which automatically matches these table names and marks them as hidden when first encountered.

**Comment by camsaul** [comment]
I've got these so far:

*  `django_admin_log`
*  `django_content_type`
*  `django_session`
*  `django_site`
*  `south_migrationhistory`

As well as these which aren't Django but I think we should hide as well:
*  `nginx_access_log`
*  `spatial_ref_sys`

@salsakran Can you think of anything else?

**Comment by camsaul** [comment]
Also might as well hide these for Liquibase:

*  `databasechangelog`
*  `databasechangeloglock`

**Comment by camsaul** [comment]
Ok hopefully someone on SO can chime in

http://stackoverflow.com/questions/37083409/what-internal-tables-are-automatically-created-by-django

**Comment by camsaul** [comment]
success! I got this list

*  `auth_group`
*  `auth_group_premissions`
*  `auth_permission`
*  `django_content_type`
*  `django_migrations`
*  `django_session`
*  `django_site`
*  `user`
*  `user_groups`
*  `user_user_permissions`

I don't think we want to hide tables called `user`, though

**Comment by salsakran** [comment]
yeah, Id say all of those except `user` are cruft though.

**Comment by camsaul** [comment]
Implemented by #2560
