### ISSUE TITLE
Time Range Filtering is not supported in AWS Document DB

### ISSUE THREAD

**Issue by shtengel** [metabase/metabase#24191]
**Describe the bug**

I'm using AWS Document DB (which is MongoDB Compatible) as my Database and as my Source to Metabase dashboards.

in my Database, for each document in my collection i have a field "timestampISO" which is an ISO String of the creation date of the document .
I Opened the Admin Settings and in Data Model under Columns i've set that field to "Cast" ISO8601 -> Datetime.
Now when i view my collection in Metabase's explore i can see the timestamp formatted and it works great.

The problem arises when i'm trying to add Date Filter (such as "Yesterday" or "Today") to my Dashboard.. it shows an error:
Command failed with error 303: 'Feature not supported' on server -docdb.cluster-*.ap-southeast-1.docdb.amazonaws.com:27017. The full response is { "ok" : 0.0, "code" : 303, "errmsg" : "Feature not supported", "operationTime" : { "$timestamp" : { "t" : 1658084363, "i" : 1 } } }

AWS Document DB is a fork of MongoDB, but not all functions are available.
here is a list of the functions: https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html

Can you fix the query when the database is AWS Document DB ?

**Logs**
Command failed with error 303: 'Feature not supported' on server docdb.cluster-*.ap-southeast-1.docdb.amazonaws.com:27017. The full response is { "ok" : 0.0, "code" : 303, "errmsg" : "Feature not supported", "operationTime" : { "$timestamp" : { "t" : 1658084363, "i" : 1 } } }

**To Reproduce**
1. Create a new "Question" on an AWS Document DB Database
2. Add time range filter
3. See error

**Expected behavior**
Results of the query should be filtered

**Screenshots**
<img width="736" alt="Screen Shot 2022-07-21 at 20 12 48" src="https://user-images.githubusercontent.com/7889699/180274093-8f878a3e-2cdd-4535-8092-7cde8f68baab.png">

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.10.102-99.473.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-27",
      "tag": "v0.43.4",
      "branch": "release-x.43.x",
      "hash": "61cc28e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
DocumentDB is related to Mongo, but not fully compatible. It would likely require a separate driver #10943
There's also known issues with cast #18733
