### ISSUE TITLE
Automatically generate a dashboard and pulse to show Metabase features

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2420]
It can be overwhelming to understand all the possible features metabase provides.

We should identify core tables (either automagically or via user input) as well as main dimensions on each table and automatically generate a dashboard and pulse as starting points.
- [ ] Determine heuristics to create interesting cards 
- [ ] Create a step in the setup process to ask questions that feed into the heuristics

**Dashboard should show**
- [ ] Scalar card 
- [ ] Time series card
- [ ] Bar chart
- [ ] US Map
- [ ] World Map
- [ ] Bar chart made up of multiple scalars
- [ ] Line chart with multiple time series plotted against it

**Pulse should show**
- [ ] Scalar
- [ ] Time series 
- [ ] Top N table
- [ ] Bar Chart

**Comment by salsakran** [comment]
Also, at a minimum, we should create a sample dashboard + pulse for the sample data set.

**Comment by agilliland** [comment]
Yeah, doing this for the sample dataset sounds like the best place to start because then we can ensure the output is something sensible.

Pulse is pretty tough BTW because until we are certain the admin has input a slack token or email details then pulses can't actually be sent.

**Comment by salsakran** [comment]
I've got a sample dashboard + pulse set up. 

@mazameli @kdoh how do you guys feel about this just being auto-created on installation and named "Sample Dashboard" and "Sample Pulse"?
