### ISSUE TITLE
Revert buttons shown on dashboard revision history for users without edit permissions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#24210]
**Describe the bug**
Revert buttons shown on dashboard revision history for users without edit permissions.
Regression since 0.42

**To Reproduce**
1. Admin: Create a dashboard, save, edit again and add a Textbox, so there's multiple revisions
2. Login with user (`readonly`) with view-only collection permissions
3. Go to dashboard > three-dots > Revision history - Revert button is shown and clickable, but nothing happens and no errors, just keeps showing "Reverting".
![image](https://user-images.githubusercontent.com/1447303/180416043-07b567ed-e3e2-47b4-a5f4-11e4ab18dd66.png)

**Expected behavior**
0.41
![image](https://user-images.githubusercontent.com/1447303/180415384-05ef41c9-b9bb-4665-8988-35e4b7572637.png)

**Information about your Metabase Installation:**
Tested 0.41.7 thru 0.43.4

**Comment by gitstart** [comment]
@flamber We would like to contribute to this issue but need some clarification on this. The current implementation differs from this (please check [this](https://www.loom.com/share/3a19efe96ada449aae402249f61f864d) out). If this is a fix for any particular version, how can we reproduce this issue?

**Comment by flamber** [comment]
Fixed by #23590
