### ISSUE TITLE
"Exclude" filter on dashboard doesn't show any value in filter widget when nothing is excluded 

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#24235]
**Describe the bug**
If you have a `date/all-options` filter on a dashboard, and you set it to "Exclude" but don't exclude anything, the filter widget is blank.

**To Reproduce**
1. Create a dashboard with a question with a temporal field, or a markdown card with a variable
2. Add a filter to the dashboard with the `date/all-options` type
3. Connect the filter to the question/card and save the dashboard
4. Click on the filter widget > click "Excludes..."  > click any granularity
5. Click "Update filter" without unchecking anything
6. Filter widget will be blank

**Expected behavior**
Filter widget should not be blank. Maybe it should say `Exclude nothing` or similar.

**Screenshots**

https://user-images.githubusercontent.com/32746338/180511357-63298c0f-15f9-4657-983b-f3d01c2c270b.mov

**Information about your Metabase Installation:**
Current master

**Comment by KlingerMatheus** [comment]
@noahmoss do you think `No selections` would be good?

Demo : https://www.loom.com/share/3594e075bc14447085179f6e806bd581

**Comment by noahmoss** [comment]
@KlingerMatheus I just discussed with one of our PMs. We should actually show the empty filter in this case, i.e.:

![image](https://user-images.githubusercontent.com/32746338/180829318-c0dc271c-a2bb-4e41-b557-5495fd463aa7.png)

**Comment by KlingerMatheus** [comment]
> @KlingerMatheus I just discussed with one of our PMs. We should actually show the empty filter in this case, i.e.:
> 
> ![image](https://user-images.githubusercontent.com/32746338/180829318-c0dc271c-a2bb-4e41-b557-5495fd463aa7.png)

Got it! I thought about it too, i will provide the change.
