### ISSUE TITLE
Using snippets in mongodb native queries caused error

### ISSUE THREAD

**Issue by ehsanm94** [metabase/metabase#24294]
**Describe the bug**
Using snippets in native queries caused "JSON reader was expecting a value but found '('." error

**Logs**
`ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 2,
 :started_at #t "2022-07-26T06:55:20.122293Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Unable to parse query: JSON reader was expecting a value but found '('.",
   :stacktrace
   ["--> driver.mongo.execute$parse_query_string.invokeStatic(execute.clj:152)"
    "driver.mongo.execute$parse_query_string.invoke(execute.clj:145)"
    "driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:161)"
    "driver.mongo.execute$execute_reducible_query.invoke(execute.clj:157)"
    "driver.mongo$fn__94610$f__92891__auto____94611.invoke(mongo.clj:234)"
    "driver.mongo.util$do_with_mongo_connection$fn__92882.invoke(util.clj:218)"
    "util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:134)"
    "util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:123)"
    "driver.mongo.util$do_with_mongo_connection.invokeStatic(util.clj:212)"
    "driver.mongo.util$do_with_mongo_connection.invoke(util.clj:207)"
    "driver.mongo$fn__94610.invokeStatic(mongo.clj:233)"
    "driver.mongo$fn__94610.invoke(mongo.clj:231)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51446.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__47229.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50387.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__52919$combined_post_process__52924$combined_post_process_STAR___52925.invoke(query_processor.clj:207)"
    "query_processor$fn__52919$combined_pre_process__52920$combined_pre_process_STAR___52921.invoke(query_processor.clj:204)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51367$fn__51372.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51367.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47472.invoke(fetch_source_query.clj:281)"
    "query_processor.middleware.store$initialize_store$fn__47660$fn__47661.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47660.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__51639.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48729.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__51578.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51950.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___44199$thunk__44201.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___44199.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___44199.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___44210.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
    "query_processor$fn__52966$process_query_and_save_execution_BANG___52975$fn__52978.invoke(query_processor.clj:337)"
    "query_processor$fn__52966$process_query_and_save_execution_BANG___52975.invoke(query_processor.clj:330)"
    "query_processor$fn__53010$process_query_and_save_with_max_results_constraints_BANG___53019$fn__53022.invoke(query_processor.clj:349)"
    "query_processor$fn__53010$process_query_and_save_with_max_results_constraints_BANG___53019.invoke(query_processor.clj:342)"
    "api.dataset$run_query_async$fn__66700.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__39322$fn__39323.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__39322.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :query
    "[(metabase.driver.common.parameters/map->ReferencedQuerySnippet {:snippet-id 4, :content \"{\\\"$match\\\": {}}\"})]"}}],
 :error_type :invalid-query,
 :json_query
 {:database 2,
  :native
  {:template-tags
   {:snippet: test
    {:id "eadfbf8e-8a0a-af3b-6293-db34dbbe19c4",
     :name "snippet: test",
     :display-name "Snippet: test",
     :type "snippet",
     :snippet-name "test",
     :snippet-id 4}},
   :query "[{{snippet: test}}]",
   :collection "test_collection"},
  :type "native",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class org.bson.json.JsonParseException,
 :stacktrace
 ["org.bson.json.JsonReader.readBsonType(JsonReader.java:251)"
  "org.bson.codecs.BsonArrayCodec.decode(BsonArrayCodec.java:66)"
  "org.bson.BsonArray.parse(BsonArray.java:75)"
  "--> driver.mongo.execute$parse_query_string.invokeStatic(execute.clj:149)"
  "driver.mongo.execute$parse_query_string.invoke(execute.clj:145)"
  "driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:161)"
  "driver.mongo.execute$execute_reducible_query.invoke(execute.clj:157)"
  "driver.mongo$fn__94610$f__92891__auto____94611.invoke(mongo.clj:234)"
  "driver.mongo.util$do_with_mongo_connection$fn__92882.invoke(util.clj:218)"
  "util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:134)"
  "util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:123)"
  "driver.mongo.util$do_with_mongo_connection.invokeStatic(util.clj:212)"
  "driver.mongo.util$do_with_mongo_connection.invoke(util.clj:207)"
  "driver.mongo$fn__94610.invokeStatic(mongo.clj:233)"
  "driver.mongo$fn__94610.invoke(mongo.clj:231)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
  "query_processor.context.default$default_runf.invoke(default.clj:65)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51446.invoke(cache.clj:220)"
  "query_processor.middleware.permissions$check_query_permissions$fn__47229.invoke(permissions.clj:109)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50387.invoke(mbql_to_native.clj:23)"
  "query_processor$fn__52919$combined_post_process__52924$combined_post_process_STAR___52925.invoke(query_processor.clj:207)"
  "query_processor$fn__52919$combined_pre_process__52920$combined_pre_process_STAR___52921.invoke(query_processor.clj:204)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51367$fn__51372.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:75)"
  "driver$do_with_driver.invoke(driver.clj:71)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51367.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47472.invoke(fetch_source_query.clj:281)"
  "query_processor.middleware.store$initialize_store$fn__47660$fn__47661.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__47660.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__51639.invoke(normalize_query.clj:22)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48729.invoke(constraints.clj:53)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__51578.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51950.invoke(catch_exceptions.clj:162)"
  "query_processor.reducible$async_qp$qp_STAR___44199$thunk__44201.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___44199.invoke(reducible.clj:106)"
  "query_processor.reducible$async_qp$qp_STAR___44199.invoke(reducible.clj:91)"
  "query_processor.reducible$sync_qp$qp_STAR___44210.doInvoke(reducible.clj:126)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
  "query_processor$fn__52966$process_query_and_save_execution_BANG___52975$fn__52978.invoke(query_processor.clj:337)"
  "query_processor$fn__52966$process_query_and_save_execution_BANG___52975.invoke(query_processor.clj:330)"
  "query_processor$fn__53010$process_query_and_save_with_max_results_constraints_BANG___53019$fn__53022.invoke(query_processor.clj:349)"
  "query_processor$fn__53010$process_query_and_save_with_max_results_constraints_BANG___53019.invoke(query_processor.clj:342)"
  "api.dataset$run_query_async$fn__66700.invoke(dataset.clj:68)"
  "query_processor.streaming$streaming_response_STAR_$fn__39322$fn__39323.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__39322.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
 :card_id nil,
 :context :ad-hoc,
 :error "JSON reader was expecting a value but found '('.",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}`

**To Reproduce**
Create and run a native question with some simple snippet and see the error.
Query: [{{snippet: test}}]
Snippet: {"$match": {}}

**Information about your Metabase Installation:**
- database: MongoDB
- Metabase version: v0.43.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Comment by qnkhuat** [comment]
Implemented in #24656

**Comment by moeinrahimi** [comment]
when we share a native query on running the query we get "JSON reader was expecting a value but found '('." error. we are using version 0.44.6 of metabase

**Comment by flamber** [comment]
@moeinrahimi Then it's likely a different issue. This issue has been fixed in the upcoming v45.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
