### ISSUE TITLE
UI performance regression between 42.4 and 43.4

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24291]
**Describe the bug**
Some customers reported feeling 43 slower than 42 so I did a few tests and here's what I found:
1) 43.4 does not keep the spinners till the moment it renders the charts, it renders a white frame for a few ms and then it renders the chart. 42.4 kept the spinner till the moment before the rendering.
2) 43.4 renders one chart after another, while 42.4 did this faster (2 charts after another)
3) 42.4 rendered the first chart faster (around 1000ms after everything started, while 43.4 made it 1500ms after everything started)

Note: 44.0-RC1 is a little bit slower, but not much than 43.4

**Logs**
Unfortunately uploading Chromium profiling info is limited (cannot upload >25MB)

**To Reproduce**
1) New->question->Orders. Summarize: sum of total, average of quantity, sum of tax. Group by Product->vendor and Product->category. Save the question
2) Create a new dashboard
3) Add the newly created question 20 times to the dashboard
4) Profile it

**Expected behavior**
Keep Metabase smooth

**Screenshots**
One example, a frame with all charts with a white background since the spinner is not there but the chart has not yet rendered
![image](https://user-images.githubusercontent.com/1711649/180896976-a6d0df2f-90e5-4bb9-987b-c52c8a9a79c7.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-OS 22.04
- Your databases: Postgres 14.3
- Metabase version: 42.4, 43.4, 44.0-RC1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.3

**Severity**
P2'ish

**Additional context**
Reported by 2 customers

**Comment by alxnddr** [comment]
Intentionally slowed down rendering in the scope of https://github.com/metabase/metabase/pull/22094
Trying to find a better solution
