### ISSUE TITLE
V1.43.4 upgrade to V1.44.0RC1 abnormal

### ISSUE THREAD

**Issue by Avey777** [metabase/metabase#24313]
Upgrade from V1.43.4 to V1.44.0RC1 version. When the metabase is accessed after the service is started, the metabase service will automatically stop. When downgrading to V1.43.4, the original data cannot start the metabase normally; later I use the backed up data to return to normal

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Include logs, since it's impossible to know what is going on otherwise.
