### ISSUE TITLE
Sorting by Custom Columns on MongoDB does not work

### ISSUE THREAD

**Issue by k2xl** [metabase/metabase#24315]
**Describe the bug**
![image](https://user-images.githubusercontent.com/965260/181052314-d0fa751c-2c65-477e-affb-01bc22347c5f.png)
![image](https://user-images.githubusercontent.com/965260/181052344-1d0cbf83-05c8-43dc-bd25-f3ad8e02686f.png)

Database used: MongoDB

Metabase v0.43.4.

**Severity**
Somewhat problematic - We were planning to use this combined with alerts to get us a sense of the top values for this query. If we can't resolve this we'll have to figure out some other way.

**Comment by jjromary** [comment]
I will work on this issue, ok?

**Comment by jjromary** [comment]
Hi, @k2xl. Do you need this order of values to always be acs when creating a custom column?

**Comment by k2xl** [comment]
@jjromary Can you clarify what you mean by acs? Did you mean asc? I just want to be able to sort either direction

**Comment by jjromary** [comment]
Yes! asc 😅.

**Comment by jjromary** [comment]
@k2xl  So that I can better understand your request. Do you want to be able to sort in any direction when building the formula?

**Comment by flamber** [comment]
This is caused by Metabase creating `$sort` before `$project` that holds the computed field, which essentially means it's not applying sorting. Currently the workaround is to use Native query in Metabase or create a View with the Custom Column on Mongo so Metabase just sees a regular "table".

**Comment by metamben** [comment]
It seems to me this has been fixed in #27176. The following question works as expected.

![Image](https://user-images.githubusercontent.com/103100869/209717712-0fc1eebe-d192-4ea9-a819-c389e7add565.png)
