### ISSUE TITLE
Default `/api/collection/tree` call brings all users personal collections for admins

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24330]
**Describe the bug**
In the home screen, the api call brings all personal collections, which doesn't make any sense in that screen as the list of personal collections is in a separate view

**To Reproduce**
1) set up metabase
2) create 1 user
3) authenticate with the other user
4) as an admin, see the api call in the home screen

**Expected behavior**
Don't bring personal collections in the default api call, as it can cause performance issues

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/181126368-487e940b-9ec2-41ad-8a96-bacfe234b776.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres
- Metabase version: 1.43.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2 ish

**Additional context**
Reported by a customer

**Comment by markbastian** [comment]
The key logic here in this route (BTW, I expect the same behavior for the non-treed (i.e. /) route as this one) is in `(collection/permissions-set->visible-collection-ids @api/*current-user-permissions-set*)`. Per the docs, "For those with *root* permissions (e.g., an admin), this function will return `:all`, signifying that you are allowed to view all Collections." This explains the behavior.

Is the desired behavior to only return your own collections? Is there another case (e.g. you have some set of permissions that isn't you but isn't admin -- like a shared collection)? I am assuming not, but still new to things.

**Comment by paoliniluis** [comment]
This problem needs to be tackled also in the frontend, as we currently hit that endpoint (if you're an admin) in the main view to get paths to user collections that are used in another view (/collection/users).

So in the main view, we shouldn't get all the paths for all the users collections, but if the admin visits /collection/users, we should do it

**Comment by nemanjaglumac** [comment]
Reopening as the initial fix introduced regressions and was reverted.
This fix for this issue will most likely need to involve both BE and FE. It's quite possible that it requires some product input as well.

**Comment by markbastian** [comment]
The initial PR for this conformed to the request that admins no longer receive personal collections that aren't their own. However, this is problematic because there are cases where an admin does want to view and edit all collections. In the attached screen capture you can see both the individual user's collections and their ability to see all collections (this user is an admin).

We can add a flag to the above PR so that you can request only collections visible to you as a user or all collections as an admin, but this will require FE work to do a second call when the "Other users' personal collections" option is selected to get the full dataset.

![collections](https://user-images.githubusercontent.com/8381441/217311704-2f2bd5f8-7c01-43b3-9219-3b4a858a0e41.gif)

**Comment by markbastian** [comment]
This is under test, but to further demonstrate that it works, I have the following script:

```clojure
(defn wrap-ok [handler]
  (fn [request]
    (let [{:keys [body status]} (handler request)]
      (when (< 199 status 300)
        body))))

(defn wrap-defaults [handler]
  (fn [request]
    (handler (merge
              {:throw-exceptions false
               :as               :json
               :accept           :json
               :cookie-policy    :standard}
              request))))

(def client (-> client/request wrap-ok wrap-defaults))

(comment
  (let [cs (clj-http.cookies/cookie-store)]
    (client
     {:method       :post
      :url          "http://localhost:3000/auth/login"
      :form-params  {:password "..."
                     :remember true
                     :username "mark@metabase.com"}
      :content-type :json
      :cookie-store cs})
    (client
     {:method        :post
      :url           "http://localhost:3000/api/session"
      :form-params   {:password "..."
                      :remember true
                      :username "mark@metabase.com"}
      :content-type  :json
      :cookie-policy :standard
      :cookie-store  cs})
    [(time
      (count
       (client
        {:method       :get
         :url          "http://localhost:3000/api/collection/tree"
         :query-params {:exclude-other-user-collections true}
         :cookie-store cs})))

     (time
      (count
       (client
        {:method       :get
         :url          "http://localhost:3000/api/collection/tree"
         :query-params {:exclude-other-user-collections false}
         :cookie-store cs})))]))
```

In this case, I've added a lot of sample collections, so the return values for the excluded vs. nonexcluded are 78 and 3239, respectively.

WRT BE performance, the round trip for each call is shown here:

"Elapsed time: 2711.568917 msecs"
"Elapsed time: 2342.51525 msecs"
=> [78 3239]

The elapsed times always seem a bit higher for the excluded case. Seems odd to me since in the console the times are nearly indistinguishable.

**Comment by markbastian** [comment]
Update: I modified the tree code so that we get a substantial performance improvement. Example:

```clojure
"Elapsed time: 1454.570917 msecs"
"Elapsed time: 67.290375 msecs"
=> [1506 2]
```
So, with the flag enabled `exclude-other-user-collections` we get a nearly 3 order of magnitude improvement in performance.

**Comment by markbastian** [comment]
To incorporate this, we need to make two changes:

- On metabase load, add `?exclude-other-user-collections=true` to the `/collections/tree` (also works with `/collections`) api calls.
- Where we need to see all personal collections we will need to make the full call.

This happens in two locations that I am aware of:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/8381441/219462292-c14f7fd4-bb0e-46d4-a1a9-c985edf54efc.png">
and
<img width="753" alt="image" src="https://user-images.githubusercontent.com/8381441/219462436-31f4406d-8f30-4405-8108-ddaa7e0b60ba.png">

In the first case, it looks like `/collections` is already called, so I don't think we need any changes there. In the second case, I know the api is _sometimes_ called. IDK exactly what the FE trigger is for this, but we would need to ensure it gets called in here if we only had the subset.

As an aside, if we want to see improvement in collection loading (the first screen shot case) we should add paging to the `/collections` endpoint.

**Comment by markbastian** [comment]
@paoliniluis - We good to close this guy?

**Comment by paoliniluis** [comment]
If the BE changes are there, we're good to go, yes
