### ISSUE TITLE
Remember sidebar state on refresh

### ISSUE THREAD

**Issue by MuriloAmarals** [metabase/metabase#24338]
**Describe the bug**
When you are in a database section when refreshing the page the sidebar closes automatically

**To Reproduce**
1. Go to Our analytics
2. Click on any that have
3. Keep the sidebar open
4. Refresh the page
5. See error

**Expected behavior**
The sidebar should remain as it was before, by default

**Screenshots**
https://www.loom.com/share/b89fc33300ba4085ad0f17cbd0f22183

**Severity**
Minor

- Your operating system: Windows 10
- Your databases: MySQL

**Comment by flamber** [comment]
The sidebar does not have a browser state, which is remembered on refresh. It was never built like that. Related to #24110

**Comment by Toledodev** [comment]
I will take a look on it :+1:

**Comment by MuriloAmarals** [comment]
@flamber thanks for the comment
