### ISSUE TITLE
Provide a different unarchive icon

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2433]

**Comment by agilliland** [comment]
@kdoh what needs to be done with this one?  i pulled this off the previous checklist we had going but there wasn't any more information about it.

**Comment by kdoh** [comment]
The original issue was just referring to an icon update. When you've archived a question it'd be a nice affordance to use a slightly different icon to un-archive it. I have an icon drawn, just some having trouble getting it to render nicely. So this is less a bug and more of an enhancement.

**Comment by agilliland** [comment]
got it.
