### ISSUE TITLE
Scalars show short number before showing the full number

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24332]
**Describe the bug**
Some weird behavior where the scalar will first show a short number and then the full number on dashboards

**Logs**
NA

**To Reproduce**
1) New->question->orders->sum of total. Save it
2) add it to a new dashboard
3) see the issue

**Expected behavior**
Show the definitive number and not something in the middle (should be the full number

**Screenshots**
![scalar](https://user-images.githubusercontent.com/1711649/181128904-a33d512f-c82b-41dd-9934-9ed4678cf286.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your databases: Postgres
- Metabase version: 1.44.0-RC2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P3

**Additional context**
NA

**Comment by MuriloAmarals** [comment]
I will take a look on this

**Comment by MuriloAmarals** [comment]
this bug is not appearing on my localhost, could you try to reproduce it again or send me a video on how I can reproduce it correctly?

https://www.loom.com/share/5ab7b43523254151b7797c1087e13699

**Comment by flamber** [comment]
@MuriloAmarals You are missing step 2. And Github allows you to upload videos directly in comments.

**Comment by MuriloAmarals** [comment]
@flamber I did all the steps now and the visualization is different

![image](https://user-images.githubusercontent.com/87545137/181246873-bb07aa4d-50b0-48e3-b758-393371a04f12.png)

**Comment by flamber** [comment]
@MuriloAmarals You need to do step 1 again, which will create a Number visualization, save it, add it to a dashboard.
If you cannot reproduce an issue, then don't comment, just leave it for someone else to tackle it - then there's less comment noise.

**Comment by alxnddr** [comment]
Caused by https://github.com/metabase/metabase/pull/24028 but the problem is that the card does not receive the size initially due to debouncing of the ExplicitSize and throttling of UI updates from https://github.com/metabase/metabase/pull/22094

**Comment by paoliniluis** [comment]
Reopening as it keeps happenning on 44
![Peek 2022-09-26 09-46](https://user-images.githubusercontent.com/1711649/192280107-89edc1ab-0463-4c54-9c20-75dab0ecd83b.gif)

**Comment by kdoh** [comment]
Seems fixed by #24591. Can't reproduce this anymore.

**Comment by paoliniluis** [comment]
confirmed, no longer there
