### ISSUE TITLE
V1.43.4 failed to upgrade to V1.44.0RC2（Win10）

### ISSUE THREAD

**Issue by Avey777** [metabase/metabase#24344]
**Describe the bug**
V1.43.4 failed to upgrade to V1.44.0RC2

**Logs**
![image](https://user-images.githubusercontent.com/35259040/181267392-064fc275-4118-44a7-aa75-d66f51b18fd7.png)
![image](https://user-images.githubusercontent.com/35259040/181267562-fa6cdacb-4178-41e7-8873-4eb704506ce6.png)
![image](https://user-images.githubusercontent.com/35259040/181267789-5897ee88-0571-4752-a800-9f1da33a0d03.png)
![image](https://user-images.githubusercontent.com/35259040/181267782-5c730138-eeff-490a-9dc7-0ef56617a1d7.png)

Logs link：https://tmp.link/f/62e148ff60422

**video link**
https://tmp.link/f/62e147c7ac94b

**Tips**
The database updated with V1.44.0RC2, V1.43.4 cannot be used again

**Comment by paoliniluis** [comment]
You're running Java 8, which cannot be used anymore in Metabase starting from 44. You need Java 11

**Comment by Avey777** [comment]
ok！  I try it.
