### ISSUE TITLE
`Ctrl-A + Backspace` broken in text boxes in Dashboard filter widgets

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#24359]
I was playing around with https://metabase-public.metabaseapp.com/public/dashboard/4455f327-80c2-42df-8c86-3bec97ee5c47?menu=Big%20Mac&activity=Tennis%2C%20singles&weight_(kg)=70 and tried to change the activity filter and ran into this bug.

![filter](https://user-images.githubusercontent.com/1455846/181346630-43ee4b99-a2b3-4d92-bfe9-d84a123a98a3.gif)

1. Open the filter widget and start typing something e.g. `running`.
2. Press `Ctrl-A` to select the entire text or `Command-A` if you're on a Mac
3. Press `Backspace` to delete the entire text or `Delete` if you're on a Mac
4. Now here is where things get weird. It looks like it just deselected your text and moved the cursor to the end without deleting anything. **However** the filter value has clearly actually been deleted internally because if you click away to save the value the way you'd normally do it doesn't save anything. 

Clearly what's happening is that the text did indeed get deleted but the UI is not properly reflecting this when you delete it in this manner.

**Comment by iethree** [comment]
I believe this was fixed by https://github.com/metabase/metabase/pull/24367

![backspace](https://user-images.githubusercontent.com/30528226/182957289-d7beedd2-bef7-4f1a-ab3b-7a9cb78f71ca.gif)
