### ISSUE TITLE
Applying collection permissions to sub-collections doesn't work if it wasn't initially selected

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#24355]
**Describe the bug**
If you don't immediately click on the toggle that says "Also change sub-collections" and then set a collection permission (without saving), clicking that toggle is useless afterwards. Whichever collection permission you set for the parent collection will not be applied to its children.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
_Make sure you have at least one collection saved in "Our analytics" or manually create "Parent/Child" collections_
1. As admin go to collection permissions (in our scenario `/admin/permissions/collections/root`)
2. Try to set "No access" to Our analytics for All users **without clicking on "Also change sub-collections** (don't click save yet)
3. Helpful exclamation mark in a triangle appears saying that sub-collection has a greater access level
![image](https://user-images.githubusercontent.com/31325167/181307006-1ac5266d-7790-401c-afd0-5ef1c49f22b8.png)
4. Great! This was a close call. Let's go and fix it.
5. Click on "No access" or on that helpful icon to open a dropdown menu and click on "Also change sub-collections"
![image](https://user-images.githubusercontent.com/31325167/181307264-164a48c3-5763-42aa-8c7b-b99064954213.png) ![image](https://user-images.githubusercontent.com/31325167/181307297-c1ae3e79-3cee-4d6c-9308-cd69b7b71711.png)
6. The warning sign is still there, although it should've been gone now
7. Click save
8. Go to the sub-collection and notice that the permission you set to the parent hasn't been applied
![image](https://user-images.githubusercontent.com/31325167/181307662-3d93b19d-cb44-4bfa-8092-afaa66a73440.png)

**Expected behavior**
Helpful warning is great!
Expected behavior is that it serves its purpose so when a user goes back and includes sub-collections, that action should have an effect.

**Information about your Metabase Installation:**
local dev, `master`, a897ec322e23424c7eeb3a8ee58ee14b70dd1b50, H2, Sample Database

**Severity**
Can be pretty serious if admin isn't aware of this mechanism. It's misleading and setting the wrong expectation.

**Comment by flamber** [comment]
Closing in favor of #20911, which is likely related to #17573
