### ISSUE TITLE
Update MBQL Wiki Documentation to add info about expressions

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2439]
When we do this we should also add a separate page or section to the docs which details out the expanded & resolved form of the queries since this is the primary resource that writers of database drivers should be using.

**Comment by camsaul** [comment]
Wiki has been updated to add [info about expressions](https://github.com/metabase/metabase/wiki/Query-Language-'98#expressions).

**Comment by tlrobinson** [comment]
It would be nice if we had a changelog for MBQL as well. I don't think the frontend has kept up with some of the changes, e.x. #2443

**Comment by camsaul** [comment]
@tlrobinson The wiki pages are their own GH repo. You can clone that and look at the history

**Comment by agilliland** [comment]
@camsaul did we add any docs about the expanded/resolved form of a query?

**Comment by camsaul** [comment]
No, those are internal implementation details that are subject to change in the near future since Metabase is pre-1.0

**Comment by agilliland** [comment]
It still makes sense to document them though, specifically in the context of writing database drivers.  When writing a driver the expanded/resolved form of a query is what is actually passed into the IDriver query processing functions, which makes it a really important piece of information.
