### ISSUE TITLE
Pivot table redering crashes when dimension value is null

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2440]
This is on 0.17.0-snapshot using Chrome

![screen shot 2016-04-27 at 11 03 39 am](https://cloud.githubusercontent.com/assets/1987787/14862818/f1ed8c1a-0c67-11e6-884f-b9b06338a25b.png)

unclear what about the response is causing this issue, but here's the columns from the query result ...

![screen shot 2016-04-27 at 11 06 41 am](https://cloud.githubusercontent.com/assets/1987787/14862892/3aee51e2-0c68-11e6-9c3a-dd7470ac6a1b.png)

**Comment by tlrobinson** [comment]
Likely has something to due with pivoting, though it's not obvious looking at the code.
