### ISSUE TITLE
Error even if service-account-json is set in BigQuery database details

### ISSUE THREAD

**Issue by rogerzwingli** [metabase/metabase#24423]
I have the problem that an error is logged although the service account JSON is already stored. I've also replaced the key but that doesn't solve the problem. 

Error in Google Cloud Explorer:

`2022-07-29 06:16:28,266 ERROR driver.bigquery-cloud-sdk :: Database ID 2, which was migrated from the legacy :bigquery driver to :bigquery-cloud-sdk, has one or more OAuth style authentication scheme parameters saved to db-details, which cannot be automatically migrated to the newer driver (since it *requires* service-account-json intead); this database must therefore be updated by an administrator (by adding a service-account-json) before sync and queries will work again
`

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.188+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-31",
      "tag": "v1.43.2",
      "branch": "release-x.43.x",
      "hash": "433d533"
    },
    "settings": {
      "report-timezone": "Europe/Zurich"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @rogerzwingli 
Please use the support email, when using Pro/Enterprise plans.
I don't understand what you mean by "I've also replaced the key". If you edit (or have edited previously) the `metabase_database.details` manually, then it's easy to break something. Use the UI via Admin > Databases > (your-db).
The log should also include more information from when it switched the driver. Admin > Troubleshooting > Logs.

**Comment by ericcj** [comment]
i think this was a bug in metabase that didn't remove those but complains they are still there but it didn't appear to actually cause a problem for ours.  i manually edited them out of metabase_database.details to silence the warning for us

**Comment by huynguyn2000** [comment]
Hey I meet this error in version 0.60.4.4, how do we resolve it ?
