### ISSUE TITLE
Click behavior to another dashboard/question makes the browser open the destination on a new window

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24451]
**Describe the bug**
If Metabase runs on a different subdomain/domain of the parent application, then the click behavior pointing to another dashboard or question will make the browser open a new tab taking the user to the Metabase URL

**Logs**
NA

**To Reproduce**
1) set up Metabase in a domain/subdomain and the parent application in a different domain/subdomain
2) set up 2 dashboards, one with a card in Metabase and link them via click behavior on the card
3) now go to the parent app and click on the card that should take you to the second dashboard, see metabase opening up on a new tab

**Expected behavior**
When we do full app embed, we should keep everything on the same iframe

**Screenshots**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.43.4

**Severity**
P1

**Additional context**
Reported by a customer, couldn't reproduce as I use the demo that deploys metabase and the parent app in the same server but different ports, but I'm guessing that this is the reason why this is happenning

**Comment by chalenge** [comment]
@flamber @alxnddr 
Been testing this out in v44.1 and drill-through behavior for charts to a custom destination of a dashboard or question no longer works at all. The UI doesn't respond at all and nothing happens, no networks or anything. This is following the steps defined in this 
When running locally this works fine but when the app is embedded nothing happens. Is there some new additional setting introduced we need for this?

**Comment by flamber** [comment]
@chalenge Sounds like a completely different issue. This issue is about Click Behavior opening in new tab.
I cannot reproduce what you are saying. There should be console errors.

**Comment by chalenge** [comment]
To close the loop. Yeah, you're absolutely right. Ended up being some misconfiguration of the site URL which was throwing a `Mixed content` error in the console 🤦🏽 . Works as expected
