### ISSUE TITLE
Improve the autocomplete query

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#24452]
**Describe the bug**
The [autocomplete query](https://github.com/metabase/metabase/blob/2f216e72f6e335d3048c5a93bfa8b5bd8d389e86/src/metabase/api/database.clj#L415) can cause performance issues on databases with massive amount of fields, so we should take some measures for improving it

**Logs**
See ticket 11024 on our ticket system

**To Reproduce**
Can't easily reproduce unless we build some massive tables

**Expected behavior**
Don't hammer the DB on each keystroke, or enhance the query by either:
- dropping the order by
- not using a %%, between the keyword, and just use a % after the keyword
- put some delay between the keyword and the query, as users will type several letters before searching for the entity they want

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your databases: ?
- Metabase version: 1.43.4, but this is historic
- Metabase internal database: Postgres 11

**Severity**
P2

**Additional context**
Workaround: block the autocomplete API, but you lose the autocomplete functionality

**Comment by flamber** [comment]
For dev history #21887
