### ISSUE TITLE
Native questions with parameters created on 44 do not work on 43

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#24497]
**Describe the bug**
Native questions with parameters created on 44 do not work on 43

**To Reproduce**
1. On version 44 create a native question `select {{number}}`
2. Downgrade to version 43 and open the question
3. The page does not open, there are errors in the console

**Expected behavior**
Questions from 44 work on 43

**Severity**
Definitely major

**Comment by qnkhuat** [comment]
Should be fixed by #24501
