### ISSUE TITLE
Corrupted dashboard filter makes it impossible to view the question (unless removed)

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#24500]
**Describe the bug**
This is basically a duplicate of #15279, but that issue was created when we were still using the old syntax. Unfortunately, the E2E repro for this was more of a placeholder and it wasn't updated when the syntax changed so we didn't catch this regression.

**Logs**
```
POST /api/dashboard/*/dashcard/*/card/*/query results in

Output of dashboard->resolved-params does not match schema: 
	 [0;33m  {"af72ce9c" {:name (not ("Non-blank string" ""))}} [0m 
```

**To Reproduce**
1. Admin > Data Model > Sample Database > People > make sure to set **Source as "list of values"** and **Name as "search box"**
2. Simple question > Sample Dataset > People, and save as "Q1" and add to dashboard "D1"
3. On dashboard "D1", create two Text/Categories filters (both dropdown) - first connected (let's call it `List filter`) to Q1.Source, second (`Search filter`) connected to Q1.Name, save dashboard.
4. Question will not render and will display `There was a problem displaying this chart.`
5. `List filter` will not show a dropdown but "Enter some text" input field
6. `Search filter` will show "Search by name" but it doesn't seem it can find any value
7. Thanks to #16582 we can now remove the corrupted filter, so let's edit dashboard
8. Click on the gear icon next to the corrupted filter
![image](https://user-images.githubusercontent.com/31325167/182349851-2cdb7c39-7c04-4909-8023-9802a4e03132.png)
9. You will notice it is possible to select question fields and to connect the filter to it (not sure if this should even be possible or should we just say "No fields available")
![image](https://user-images.githubusercontent.com/31325167/182350152-cffae81b-a007-4b83-93d1-2bfe34692cbc.png)
10. Remove filter from the sidebar (notice the question still doesn't display correctly) and save the dashboard
![image](https://user-images.githubusercontent.com/31325167/182350396-a9d6884f-ea93-46e9-9e43-53fb64e965ef.png)
11. Either refresh or click on any of the working filters and set them, which will reset the corrupted question query
![image](https://user-images.githubusercontent.com/31325167/182350581-c58b0c7f-ae46-404f-9e96-dc9f82cfe82d.png)

**Expected behavior**
Either the backend should make `name` required (and prevent adding a corrupted filter in the first place) or frontend should handle corrupted filter gracefully. @daltojohnso already made it possible to remove such filter in #16582. However, we should display the underlying question, especially since corrupted filter isn't even connected to the question.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/182346202-306ecca2-f954-4a51-b5db-d674f72d6c82.png)

**Information about your Metabase Installation:**
local dev, `master`, 3fc791200659436eadee74e2f2b12adc58f1dd9c, H2, Sample Database

**Severity**
I am not aware of the possibility to end up with a corrupted filter using the UI. It can only affect people trying to add filters via API and then forgetting to set the `name`.

**Additional context**
If filter cannot work without `name`, doesn't it make sense then to make that parameter required on the backend?

Why is it possible to send this payload (this adds corrupted filter to the dashboard)?
`PUT /api/dashboard/:id`
```json
{
  "name": "",
  "slug": "",
  "id": "af72ce9c",
  "type": "string/=",
  "sectionId": "string"
}
```

**Comment by flamber** [comment]
Only giving P3 for now, since it's been a long time since I've seen anyone hitting this issue.

**Comment by camsaul** [comment]
@qnkhuat why is this blocked? Can't we just filter out invalid params when they come out of the DB, or just ignore them? We definitely shouldn't be breaking the entire saved question.

**Comment by qnkhuat** [comment]
@camsaul the sequencing is a bit complicated, there is another issue that covers this issue: https://github.com/metabase/metabase/issues/27653.

The TLDR is that we should require `parameter.name` and enforce it to be unique.

But I think we should only do this on FE, because doing this in BE might breaks existing dashboards.
I had a PR for that but decided to close it. more info [here](https://github.com/metabase/metabase/issues/27653)

**Comment by camsaul** [comment]
How about we make names required going forward, and for old ones just ignore unnamed ones or use their `:id` as their name or something like that.

We shouldn't be erroring with a schema error for something that people created with the GUI in the past
