### ISSUE TITLE
Multiple Models of same underlying Table conflict

### ISSUE THREAD

**Issue by dariusj18** [metabase/metabase#24515]
**Describe the bug**
If I am joining two models to a table in the same query, the metadata for one of the models is all that is used in the UI

**To Reproduce**

1. Create two models form the same table, in my case I have a table `Tag` and I create models `Market` and `Region` (where each is limited by a `TagType` field in the table)
2. Ask a question and join each model

**Expected behavior**
The JOIN's ON comparison box shows the proper model name

**Screenshots**

One model

![image](https://user-images.githubusercontent.com/10720/182397953-fe53b038-d573-45ee-9cab-27851025afe8.png)

The other model

![image](https://user-images.githubusercontent.com/10720/182397864-47332a02-35ec-4f08-bd7b-2be77f1181bb.png)

The query using the models

![image](https://user-images.githubusercontent.com/10720/182397715-f63a47cc-d259-420d-9b5c-b3ffda533a98.png)

Above says that both joins are joining to Markets.  This seems to be random, as sometimes it will say both are joined to Regions.  This does not seem to affect the query.

```sql
SELECT
	"public"."Property"."id" AS "id",
	"public"."Property"."propertyName" AS "propertyName",
	"Question 34"."title" AS "Question 34__title",
	"Question 35"."title" AS "Question 35__title"
FROM
	"public"."Property"
	LEFT JOIN (
		SELECT
			"public"."Tag"."id" AS "id",
			"public"."Tag"."title" AS "title",
			"PropertyTag"."propertyId" AS "PropertyTag__propertyId"
		FROM
			"public"."Tag"
			LEFT JOIN "public"."PropertyTag" "PropertyTag" ON "public"."Tag"."id" = "PropertyTag"."tagId"
		WHERE
			"public"."Tag"."tagType" = CAST('MARKET' AS "TagType")
	) "Question 34" ON "public"."Property"."id" = "Question 34"."PropertyTag__propertyId"
	LEFT JOIN (
		SELECT
			"public"."Tag"."id" AS "id",
			"public"."Tag"."title" AS "title",
			"PropertyTag"."propertyId" AS "PropertyTag__propertyId"
		FROM
			"public"."Tag"
			LEFT JOIN "public"."PropertyTag" "PropertyTag" ON "public"."Tag"."id" = "PropertyTag"."tagId"
		WHERE
			"public"."Tag"."tagType" = CAST('REGION' AS "TagType")
	) "Question 35" ON "public"."Property"."id" = "Question 35"."PropertyTag__propertyId"
LIMIT
	1048575
```
however on the visualization, both table column headers show the same value as well

![image](https://user-images.githubusercontent.com/10720/182400205-d3a3f85c-f8e2-43bb-af7b-ad314cdd9c2a.png)

and even if I had set the Model's "Title" metadata to something else, it still shows "Question 34 -> Title" as the header.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 103.0.5060.134
- Your operating system: Windows 11
- Your databases: Postgres
- Metabase version: v0.43.4.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Annoying and possibly confusing.  Maybe shows an underlying breaking issue that I have not encountered yet.

**Comment by flamber** [comment]
You are seeing #19893 on "The query using the models" and #23019/#12685 on "Question 34 -> Title"
