### ISSUE TITLE
Document the MBQL expanded/resolved structure in the Metabase wiki

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2457]
This should be similar to the docs in https://github.com/metabase/metabase/wiki/Query-Language-'98 but focused specifically on the data structures after they have been expanded & resolved such as the examples here https://github.com/metabase/metabase/blob/master/test/metabase/query_processor/expand_resolve_test.clj

This is an important reference for anyone trying to write a Metabase database driver.

**Comment by salsakran** [comment]
Did this get done? If not, why is it closed?

**Comment by camsaul** [comment]
yes it did

**Comment by salsakran** [comment]
which PR? Trying to get my bearings on the current state of things

**Comment by camsaul** [comment]
it's in the wiki. No PR

**Comment by salsakran** [comment]
👍
