### ISSUE TITLE
Automatically hide Rails framework tables

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2459]
We should automatically hide things like migration tables, and other framework/orm cruft.

Rails and Django would be good starting points since they tend to have very consistent cruft and we see them fairly often.

Blacklist is implemented in #2560 so we just need to add the names to 
```
metabase.sync-database.sync/blacklisted-table-names
```

**Comment by camsaul** [comment]
Posted SO question

http://stackoverflow.com/questions/37083424/what-internal-tables-are-automatically-created-by-rails

**Comment by camsaul** [comment]
A couple people on SO both said `schema_migrations` is the only thing we need to look for

**Comment by kdoh** [comment]
It might be worth a quick look at whether popular rails gems like Devise or Paperclip also generate tables that are good candidates for hiding by default, but we can also circle back to that down the road.

**Comment by kdoh** [comment]
Or better yet, crowd source it.

**Comment by camsaul** [comment]
Implemented by #2560
