### ISSUE TITLE
Make be-tests-java checks required

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#24603]
[Slack conversation](https://metaboat.slack.com/archives/C5XHN8GLW/p1659540647126419)

## Context

Some of backend CI checks are not required due to frequent flaking. We need to make them required not to miss potential bugs but firstly we have to eliminate flakiness. 

The list of flaky jobs:
```
be-tests-java-11-oss
be-tests-java-17-oss
be-tests-java-11-ee
be-tests-java-17-ee
```

After flaky tests are fixed and the PR is backported, ask `engineering-ci` to mark these as required ones.

**Comment by camsaul** [comment]
No longer relevant, they are required
