### ISSUE TITLE
Support foreign keys in calculated columns

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2460]
Right now only the main table columns are available in calculated columns

**Comment by salsakran** [comment]
@camsaul + @tlrobinson is this a backend issue, backend issue or both?

**Comment by camsaul** [comment]
This should already work on the backend we just need to rework the widget to handle syntax for foreign columns and show them in the suggestions. That's a little tricky though since the expression parser / autocomplete logic is a little involved

**Comment by sharedphysics** [comment]
Was this ever resolved? I'm trying to write a really basic custom expression on data brought in through a foreign key and it's not being found by the editor. Is there another way to write it the custom expression besides SQL?

![image](https://user-images.githubusercontent.com/5796884/49664219-3bdbf080-fa1f-11e8-912a-112eac820e27.png)

**Comment by flamber** [comment]
Hi @sharedphysics 
Looks like you're seeing #7291 - upvote :+1: - write the expression somewhere else and paste it.

**Comment by salsakran** [comment]
fixed in #10981
