### ISSUE TITLE
The "Browse data" in navigation sidebar is hidden in FullApp embedding

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#24610]
**Describe the bug**
The "Browse data" in navigation sidebar is hidden in FullApp embedding.

**To Reproduce**
1. Normal login - has "Browse data" in nav sidebar
![image](https://user-images.githubusercontent.com/1447303/182922727-c57c3815-055c-4040-8a80-78c20f0cd305.png)
2. Do FullApp embedding, then it doesn't include the "Browse data"
![image](https://user-images.githubusercontent.com/1447303/182922901-68c9195f-6cd9-47f8-9e74-59de575e530f.png)

https://github.com/metabase/metabase/blob/73e7b9658b35b964194c42afef456d649e5ae7b4/frontend/src/metabase/nav/containers/MainNavbar/MainNavbarView.tsx#L131

**Expected behavior**
"Browse data" should also be available in FullApp.

**Information about your Metabase Installation:**
Tested 1.43.4.2 and 1.44.0 - regression since 43.

**Comment by Toledodev** [comment]
I will take a look on this

**Comment by flamber** [comment]
@Toledodev Please just create a PR, if you want, no need to comment on issues, since it just adds notification noise.

**Comment by Toledodev** [comment]
Hey @flamber, when trying to reproduce the issue I realized that to enable "full-app embedding" I must have the PRO version of the metabase. How can I do this on localhost?

**Comment by flamber** [comment]
@Toledodev If you cannot reproduce an issue, then move on to something else and leave it for someone else to fix.
