### ISSUE TITLE
0.44 not working on Heroku because deploy script is using Java 8, which Metabase 0.44 does not support anymore

### ISSUE THREAD

**Issue by sebslomski** [metabase/metabase#24619]
**Describe the bug**
Upgraded on heroku results in application error during startup

**Logs**
<img width="971" alt="Screenshot 2022-08-04 at 21 58 01" src="https://user-images.githubusercontent.com/739310/182941648-1e8caff4-a88f-49aa-83ae-4f05b366ede9.png">

**Information about your Metabase Installation:**

- Your databases: Postgres
- Metabase version: 0.44 (previously 0.43)
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

**Severity**
Critical, downtime

**Comment by sebslomski** [comment]
Seems to be linked to https://github.com/metabase/metabase/issues/23948

**Comment by sebslomski** [comment]
Needs merging of:
* https://github.com/metabase/metabase-deploy/pull/30
* https://github.com/metabase/metabase-deploy/pull/28

**Comment by mehlah** [comment]
I confirm this is happening on Heroku for an upgrade or a new install.

2 reasons:
- Heroku20 stack doesn't run Java 11 by default (now deprecated but still the default when a new app is created). Setting the runtime to Java 11 should be useful, or to 17 as suggested by https://github.com/metabase/metabase-deploy/pull/28
- Heroku22 runs Java 11 by default but the current options in the start script prevents the app from starting. I suggest a fix for the removed option (tested on a new app and an upgrade) at https://github.com/metabase/metabase-deploy/pull/30.

**Comment by paoliniluis** [comment]
Just merged the fixes. Have a nice weekend!
