### ISSUE TITLE
New filter modal is showing custom mapped values next to their original values

### ISSUE THREAD

**Issue by tvinckier** [metabase/metabase#24626]
**Describe the bug**
In the new filter modal, with columns that have custom mapping in the data model, they are showing their original data value + de custom mapped value.

**To Reproduce**
1. Go to 'datamodel
2. Put custom keymapping on a column
3. Open the table and the filter modal

**Expected behavior**
You should see duplicate values (original value and the custom mapped)

**Screenshots**
![image](https://user-images.githubusercontent.com/85233111/183025104-70479428-1aa5-4f4c-b8a9-ce819b973757.png)
![image](https://user-images.githubusercontent.com/85233111/183025196-81a72560-c6b5-495f-86f1-57884196273a.png)

**Information about your Metabase Installation:**
I'm running the latest 0.44 version.
{
  "browser-info": {
    "language": "nl-NL",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Windows 11",
    "os.version": "10.0",
    "user.language": "nl",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-04",
      "tag": "v0.44.0",
      "branch": "release-x.44.x",
      "hash": "d3700f5"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}

**Comment by flamber** [comment]
Reproduce:
1. Admin > Data Model > Sample > Reviews > Rating - "List of all values" and "Display values"="Custom mapping":
![image](https://user-images.githubusercontent.com/1447303/183634313-57a75d20-af07-4a73-a29b-cdea8e604f21.png)
2. Question > Sample > Reviews - column filter and Notebook works as expected:
![image](https://user-images.githubusercontent.com/1447303/183634489-23b73f05-ee8e-4a6a-a111-0bd9b326964c.png)
3. But the new filter modal shows real values and remapped, and errors query if selecting any of the mappings (ex. "A")
`Error filtering against :type/Integer Field: unable to parse String \"A\" to a :type/Integer`
![image](https://user-images.githubusercontent.com/1447303/183634653-4bbcf20b-3743-4e08-88bb-8884333c3db8.png)
