### ISSUE TITLE
Download icon colliding with frame in single record view

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2463]
Seen on our stats instance.

When looking at a single record, the download action icon is incorrectly overlapping with the frame of the record:

![download-icon](https://cloud.githubusercontent.com/assets/2223916/14902308/00a32304-0d4f-11e6-8e5e-396127d5c0b5.png)

**Comment by agilliland** [comment]
@tlrobinson can you take a look at this one and reproduce?

**Comment by tlrobinson** [comment]
I can reproduce it. Is it even worth showing in the object detail view? It just downloads a 1 line CSV at the moment.

**Comment by agilliland** [comment]
To my knowledge it's not meant to be showing that.

**Comment by kdoh** [comment]
Do we want to hide the icon? It seems like its still useful to be able to download the data you're seeing even if its only just one row / record.

**Comment by tlrobinson** [comment]
It doesn't seem particularly useful to me, and I feel like putting the icon in there without the visualization settings and "Get Answer" button would feel pretty unbalanced (unless you have another idea where to put it)
