### ISSUE TITLE
Cannot set caching duration to less than a second

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#24657]
**Describe the bug**
Cannot set caching duration to less than a second. I use `0.0001` to test several caching issues with databases, where I cannot control the query speed.
Regression in 0.44.0

**To Reproduce**
1. Go to Admin > Settings > Caching > set "Minimum Query Duration" to decimal less than a second, eg. `0.0001`
2. The frontend changes to a `0` during the PUT request, which is then changed to `null` in the response, so the field become empty with just a placeholder (60)

**Expected behavior**
Allow decimal duration
![image](https://user-images.githubusercontent.com/1447303/183394087-0b2a4c6a-2ea7-47ad-8e96-a5629ca3ef64.png)

**Information about your Metabase Installation:**
Tested 0.44.0

**Comment by dpsutton** [comment]
Seems to be a FE issue. It is truncating the number: 2.9 -> 2, 1.2 -> 1, 0.0001 -> 0. Using the backend to set the value manually `(query-caching-min-ttl! 0.0001)` allows the value to show up in the UI. But editing it in the UI again truncates the value.
