### ISSUE TITLE
Dashboard card filter connection hides filter disconnect button until hovered

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#24650]
**Describe the bug**
Dashboard card filter connection hides filter disconnect button until hovered. Don't know if it is on purpose, but it feels like a bug.

**To Reproduce**
1. Dashboard > add a question and add a filter and connect it, then it doesn't show the disconnect button until hovering the X

https://user-images.githubusercontent.com/1447303/183246641-e416f6a3-d86a-4e9c-b8b8-be7834a29e98.mp4

**Information about your Metabase Installation:**
Tested 0.44.0

**Comment by mazameli** [comment]
Below is the style for this UI that I thought we were still using. Not sure when/why this was changed. 

![image](https://user-images.githubusercontent.com/2223916/183520420-a6a3def5-4eff-46b3-8ebc-127eff97299e.png)
