### ISSUE TITLE
Pivot Table does not have horizontal scroll bar

### ISSUE THREAD

**Issue by mikeromankiewicz** [metabase/metabase#24678]
If a pivot table is larger than the dashboard card it is displayed in, or if the user's display window does not accommodate the width of the dashboard card/pivot table (as might be the case when resizing the browser window or when going from desktop to laptop, etc), there does not appear to a horizontal scroll bar to be able to see the cut-off contents of the pivot table. 

And perhaps relatedly, there does not appear to be a way to expand/resize column widths to accommodate longer column names in a pivot table, so these are cut-off and can only be viewed in full via hovering over the column name. 

**Expected behavior**
A horizontal scroll bar should be present on pivot tables when the pivot table is wider than the card/window it is in.
And an ability to set the column width/resize through the GUI to accommodate longer column names would be a big plus.

**Screenshots**
Example pivot table on full dashboard card; all contents are visible (minus the longer column name headers):
![image](https://user-images.githubusercontent.com/9580354/183534461-d95eeddb-a0b3-4850-ae25-2ba5444d90b7.png)

Same pivot table, as it appears on a laptop with a smaller screen size; no horizontal scroll bar is present (table can still be scrolled vertically when hovering over table and scrolling with a mouse- just not horizontally):
![image](https://user-images.githubusercontent.com/9580354/183534836-0e5cbb9e-bb83-4aaf-b91d-17ae445ccfff.png)

Here is the info from Admin --> Troubleshooting
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_321-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_321",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.321-b07",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.42.2",
      "date": "2022-02-28",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
This is a moderately severe issue, as we are beginning to use pivot tables in our MetaBase deployment and some of the data cannot be accessed as expected from different devices, creating issues with our user base.

**Comment by flamber** [comment]
Only happens for "rows" fields, since they are frozen. Slightly related to #14743.
![image](https://user-images.githubusercontent.com/1447303/183604149-d01fb768-204c-4cbd-8c33-52f74e9dd77c.png)
![image](https://user-images.githubusercontent.com/1447303/183604236-764ef774-f16e-42a5-9fcc-248c43fe590f.png)

@mikeromankiewicz Off topic: You should [migrate away from H2](https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html) if you're using Metabase in production, and [upgrade to Java 11](https://www.metabase.com/docs/latest/operations-guide/java-versions.html). Latest [release is 0.44.0](https://github.com/metabase/metabase/releases/latest).

**Comment by EmmadUsmani** [comment]
Spent a while trying to fix this but couldn't make much progress. Going to mark this on our board as "waiting until we broadly tackle this area" since we have plans to improve tables/pivots, and it may be better to wait for us to implement a better table component.
