### ISSUE TITLE
Slack integration not working with 10k+ larger workspaces

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#24673]
**Describe the bug**
Slack integration not working with 10k+ larger workspaces

**To Reproduce**
Have more than 10k channels and then try to setup Slack. For more info: https://discourse.metabase.com/t/issue-setting-up-slack-integration/21343

Any reason why we're [limiting to 10k channels](https://github.com/metabase/metabase/blob/f25b61154b5cf90a91d895ecbf459775827cee5e/src/metabase/integrations/slack.clj#L142-L145) after pagination was added, including the async channel getter? 20k?

**Information about your Metabase Installation:**
0.44.0

**Comment by escherize** [comment]
This should have been closed by https://github.com/metabase/metabase/pull/20570 a little while ago.
