### ISSUE TITLE
Use combo-chart type for single series Line/Area/Bar charts

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#24671]
## Context

In the past static viz improvements cycle we’ve implemented universal line/area/bar chart which has type `combo-chart` in the code. It supports series of various types, multiple series, goal line, etc. Previously used duplicated charts such as `categorical/area` , `categorical/bar` , … , should be removed in favor of the `combo-chart` to avoid the code duplication. Otherwise, we will need to copy-paste for instance Goal Line code which is not great.

By itself it will fix "[Reflect fill option for line charts](https://www.notion.so/Reflect-fill-option-for-line-charts-285a1cc0903f449b9ad01f4e06eff5ae)" right away

## Implementation

**BE**
- for all line/area/bar static charts use `combo-chart`

**FE**
- clean up the code by removing the old charts

## Estimates

**BE:**
**FE:** 0 days

**Comment by howonlee** [comment]
Looks like we can't do donut with combo, btw
