### ISSUE TITLE
Refreshing URL with filter containing empty value removes the filter

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#24681]
**Describe the bug**

If a dashboard has a filter with a selected empty value, the generated URL looks like this:

http://localhost:3000/dashboard/6-tony-test?model=

Once you hit the refresh button the filter gets removed:

http://localhost:3000/dashboard/6-tony-test

This causes the dashboard to default the filter which is wrong since we need to keep filters even if their values are empty.

**To Reproduce**

1. Create a dummy table and some dummy data in Postgres:

```
create table test
(
    id          integer generated by default as identity primary key,
    topic       varchar(32)              not null,
    timestamp   timestamp with time zone not null,
    model       varchar(16),
    model_id    integer,
    database_id integer,
    table_id    integer,
    custom_id   varchar(48),
    details     text                     not null
);
```

```
INSERT INTO public.test (id, topic, timestamp, model, model_id, database_id, table_id, custom_id, details) VALUES (1, 't', '2022-08-09 13:11:02.359000 +00:00', 'test', 1, 1, 1, '1', 'test');
INSERT INTO public.test (id, topic, timestamp, model, model_id, database_id, table_id, custom_id, details) VALUES (2, 'p', '2022-08-09 13:11:20.996000 +00:00', '', 2, 2, 2, '2', 'prod');
```

2. Go to Question and select your test table (you will notice two rows) then save this question:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/110378427/183646319-7b3d2d29-6807-48e4-9a4b-7252bc0fc25b.png">

3. Create a Dashboard with this new Question

4. Create a Filter (Text & Category -> Drop Down) and Attach it to the column **Model**

5. You will have two option a test or empty string '' ... Select the empty string:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/110378427/183647027-8a4682c5-9c8c-45ed-958c-e4b023a6c6f7.png">

6. Hit the refresh button:

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/110378427/183647218-2bf8ff4b-89bc-4ed2-a1f2-e70b0217b839.png">

You will notice the filter was removed and now i end up with the full list. The same doesn't happen if chose the other value, it only happens when there is an empty value 

**Expected behavior**
The filter remains as it was before refresh:

http://localhost:3000/dashboard/7-test-missing-filter?text=

Refresh website

http://localhost:3000/dashboard/7-test-missing-filter?text=

**Information about your Metabase Installation:**

I tested this issue on both 43.5 & 44

**Severity**
This is blocking some

**Comment by flamber** [comment]
It was likely created this way because of #17578 and #13960.
Seems like it's difficult to keep the parameter and also know that it should be searching for empty string at the same time.

**Comment by calherries** [comment]
This should be fixed by https://github.com/metabase/metabase/pull/31891

**Comment by calherries** [comment]
Fixed by https://github.com/metabase/metabase/pull/31891

**Comment by calherries** [comment]
This should have been closed before
