### ISSUE TITLE
Bubble X objective

### ISSUE THREAD

**Issue by prigal** [metabase/metabase#24697]
**Is your feature request related to a problem? Please describe.**
We can actually add an objective on the Y axis but not an X axis. 

**Describe the solution you'd like**
I would like to add an objective on the X axis.

**Describe alternatives you've considered**
N/A

**How important is this feature to you?**
This is a chart with 2 dimensions, we should have objective on each dimensions. 

**Additional context**
N/A

**Comment by flamber** [comment]
Hi @prigal 
I don't understand what you're asking for. What is "objective"? Please be more descriptive, include screenshot, so it's easier to understand.
Sounds like you're looking for #11254

**Comment by prigal** [comment]
Sorry, I mean "goal line". We can define a goal line for Y axis, but not for X one. 

![image](https://user-images.githubusercontent.com/895267/183868542-f543cfcd-6eef-4e88-98dd-f3b351c4330a.png)

**Comment by flamber** [comment]
@prigal Okay, closing in favor of #8496
