### ISSUE TITLE
Goal line with decimal value

### ISSUE THREAD

**Issue by willbryant** [metabase/metabase#24694]
**Is your feature request related to a problem? Please describe.**
We'd like to set a goal line on our gross margin. This is a rate (type/Share), so its values are <1.0. We want to set a goal, but it only accepts integer inputs.

**Describe the solution you'd like**
We'd like to be able to set a goal of 0.15, so we want decimal goals with at least 2dp precision, preferrably 3dp.

**Describe alternatives you've considered**
Creating a pre-multiplied column and using that; but, then the Percent formatting won't do what we expect.

**How important is this feature to you?**
Annoyance, no-one's going to stop using the product because we can't set goals.

**Comment by flamber** [comment]
Hi @willbryant 
Am I missing something, or could it be something in your browser not allowing you to input decimals?
![image](https://user-images.githubusercontent.com/1447303/183841119-c785cf3c-5bfd-414f-ba1c-def75464213a.png)

**Comment by willbryant** [comment]
Hmm let me try and repro with the sample dataset.

It might be because we had the column set to Percent display. Actually, I would prefer 0-100 entry for percents, but that didn't work either - 1 was interpreted as 100%. So if the intended behavior was that the goal input is in percentage points, then *that's* the bug?

**Comment by flamber** [comment]
@willbryant Please open a bug with steps-to-reproduce if something is not working, but decimals are working fine for me.

**Comment by willbryant** [comment]
I think it was just fixed by 5422664e5f :).

**Comment by flamber** [comment]
No, that was only for admin settings:
![image](https://user-images.githubusercontent.com/1447303/184127573-5b3b7986-58af-4396-90fc-36f6bf58c102.png)
