### ISSUE TITLE
Ability to inject custom usage tracking code

### ISSUE THREAD

**Issue by maliayas** [metabase/metabase#2470]
I've searched through issues and docs but couldn't find a method to integrate custom analytics code (e.g. Google Analytics) to the app. Is this possible? Thanks in advance.

**Comment by tlrobinson** [comment]
This is a good idea, but we don't have an easy way to do it yet. In the meantime you can edit the `index.html` template in the jar:

```
jar xf metabase.jar frontend_client/index.html
# edit frontend_client/index.html in your text editor of choice
jar uf metabase.jar frontend_client/index.html
```

Or if you're compiling from source you should edit `resources/frontend_client/index_template.html`

**Comment by maliayas** [comment]
I'll try it. Thanks very much.

**Comment by agilliland** [comment]
Are you more interested in something that would be truly custom?  Or something like Google Analytics where it's a known integration and you just supply your own tracking token?

**Comment by maliayas** [comment]
Thanks for asking. The first one. I imagine it as two text areas for -any- code. One for head bottom and one for body bottom.

29 Nisan 2016 18:59:01 EEST, Allen Gilliland <notifications@github.com> yazdı:

**Comment by maliayas** [comment]
@tlrobinson Do you have a recipe for the Docker method? `jar` command doesn't seem to be available there.

**Comment by marktheunissen** [comment]
@maliayas Did you figure out how to do it with the docker method? I am also looking to edit this file. Thanks!

**Comment by marktheunissen** [comment]
@tlrobinson I managed to find the jar command but then ran into this problem: http://discourse.metabase.com/t/jar-wont-run-after-modification/529

The jar doesn't run after being modified. Is there a way around this without rebuilding? Would be nice to modify the html.

**Comment by tomkanjam** [comment]
@marktheunissen You can "unsign" the Jar like this:

# Remove 2 files:
zip -d metabase.jar 'META-INF/*.SF' 'META-INF/*.RSA'

# Edit the Jar in Vim:
vim metabase.jar

# Edit the Jar manifest file
/META-INF/MANIFEST.MF

# Move cursor below “Main-Class: metabase.core” and delete the rest of the file content with:
gD

# Save and exit
:wq

**Comment by marktheunissen** [comment]
Thanks I'll give it a try! :D

**Comment by hden** [comment]
@agilliland We would like to supply our own tracking token for Google Analytics, any way we can enable that in the configuration?

**Comment by flamber** [comment]
Closing in favor of #5462, which is a request for being able to add manual GA code for own tracking.
