### ISSUE TITLE
"Remember Me" functionality doesn't work

### ISSUE THREAD

**Issue by arlampin** [metabase/metabase#24715]
**Describe the bug**
On Metabase Open Source version, self-hosted, "Remember Me" checkbox doesn't seem to work after 0.43.xx => 0.44.0 upgrade.

Looking at browser's network console, the checkbox value is sent to backend, but cookies are still marked as session cookies (see screenshot).
<img width="1543" alt="Screenshot 2022-08-10 at 22 06 00" src="https://user-images.githubusercontent.com/1737104/183999036-49577c5e-9ecb-4c28-baab-786487e49a66.png">

The installation doesn't have any customizations related to authentication. Only env variables are related to DB setup (MB_DB_ prefix)

**To Reproduce**
1. Ensure "Remember Me" checkbox is checked
2. Login using email + password
3. Fully close the browser
4. Go back to Metabase => redirected back to login page

**Expected behavior**
Metabase should remember login if corresponding checkbox has been checked

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 104.0.5112.79
- Your operating system: MacOS 12.5
- Your databases: Postgres 14
- Metabase version: 0.44.0
- Metabase hosting environment: Docker/K8s cluster
- Metabase internal database: Postgres 14

**Severity**
How severe an issue is this bug to you? 
Very annoying

**Comment by samuelT2** [comment]
According to flamber, this will be fixed in v0.45.

https://discourse.metabase.com/t/solved-re-login-required-every-couple-of-minutes/22145/4
