### ISSUE TITLE
Metrics Suggests invalid grouping fields.

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#24716]
**Describe the bug**
The Metrics Data reference suggests grouping by fields that we can't actually group by: namely JSON (proably arrays too).

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Create a metric on a table with a json or array column
2. visit `/reference/metrics/`
3. Metabase will suggest that you can group on the json field
4. but you can't

**Expected behavior**
Metabase only suggests fields that you can actually group by.

**Screenshots**

![Screen Shot 2022-08-10 at 1 46 52 PM](https://user-images.githubusercontent.com/30528226/184007011-9441aa7f-9ab4-41f2-8902-9f600e0ceb61.png)
![Screen Shot 2022-08-10 at 1 48 37 PM](https://user-images.githubusercontent.com/30528226/184007026-8b1ee6b0-2bc9-4847-918f-cda0307b2c74.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "18.0.1+0",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "18.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "18.0.1+0",
    "os.name": "Mac OS X",
    "os.version": "12.4",
    "user.language": "en",
    "user.timezone": "America/Denver"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-08-05",
      "tag": "v0.44.1-SNAPSHOT",
      "branch": "pod-writeback",
      "hash": "b0c7a36"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Minor annoyance

**Comment by mngr** [comment]
It seems there is no such page anymore
