### ISSUE TITLE
[BigQuery driver] foreign-keys is not supported by this driver.

### ISSUE THREAD

**Issue by hden** [metabase/metabase#2472]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is OSX 10.11.04.
*  I'm running Metabase AWS from the JAR. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is BigQuery.
*  My Metabase version is v0.16.1.

When filtering data by foreign column, an error `foreign-keys is not supported by this driver` was shown. AFAIK joins are available for BigQuery. Also, `join each` is available for larger datasets.

-- edit
server-side error message:
`05-05 11:12:45 ERROR metabase.query-processor :: Query failure: foreign-keys is not supported by this driver.`

**Comment by agilliland** [comment]
Hmmm, foreign keys and joining should be working when using BigQuery.  @camsaul any reason why this error is coming up?

**Comment by hden** [comment]
@agilliland @camsaul  Any update on this? Anything I can help with?

**Comment by agilliland** [comment]
@camsaul looks like the `features` for the bigquery driver are `nil`

**Comment by camsaul** [comment]
As mentioned in the original issue for the BigQuery driver, #1294, BigQuery doesn't support foreign keys:

> Would google's hosted data warehouse called bigquery be a good fit for metabase? The one thing it seems to be missing that might affect things would be foreign keys. That said, there isn't a great frontend for BigQuery yet in the open source world - maybe this is it!

That being said people can still manually set up FKs in the admin data reference and do joins that way, I'll make the tweaks to enable that.

**Comment by salsakran** [comment]
Hmm - https://cloud.google.com/bigquery/query-reference#joins

**Comment by camsaul** [comment]
@salsakran that's what I was saying. Joins are allowed but there is no notion of foreign keys.

**Comment by agilliland** [comment]
Supporting FKs as a form of referential integrity is not all that big of a deal, it's joins that we are clearly after.  I think that part of the issue is that we are intertwining the two things since we only let a structured query to express a join by first describing a FK relationship which can be followed.

I was thinking that the easiest thing to do here was just to add `:foreign-keys` to the features for this driver and call it done.  I don't think that should cause any issues.

We won't ever get back any FKs from the introspection of the bigquery schema, but that's fine.  Users will just have to map the relationships themselves.

**Comment by camsaul** [comment]
@agilliland yup, that's what I was saying. There is no notion of FKs in Big Query but if people go set them up in admin they will still be able to do joins.

**Comment by agilliland** [comment]
cool.  that sounds fine with me 👍

**Comment by camsaul** [comment]
Implemented by #2569.

**Comment by hden** [comment]
@camsaul Thanks for the quick response!!

Somehow columns are inverted when grouped by foreign-keys.

Warning message:
```
05-10 15:52:03 WARN query-processor.annotate :: There are fields we weren't expecting in the results: #{:doh_restaurants_name}
Expected: #{:name :count}
Actual: #{:doh_restaurants_name :count}
```

![screen shot 2016-05-10 at 3 54 14 pm](https://cloud.githubusercontent.com/assets/1910549/15139279/c109f326-16c7-11e6-819a-d8c7bbdc2620.png)

**Comment by asafeilam** [comment]
I encountered a problem when I set a foreign key to point over another table.
I'm using metabase with bigquery and when I set a foreign key and try to join between two tables the system return a bug.
**Field 'phytech_dw.crops__via__crop_id.id' not found on either side of the JOIN**
I did it exactly as it is shown at the example!
what to do ?

**Comment by salsakran** [comment]
@asafeilam you'll need to provide a bit more information if you need help, eg the scheme and the query you're trying to run as well as any FKs you've set. I'd also suggest you take this to discourse.metabase.com unless it's a specific bug report.

**Comment by asafeilam** [comment]
![image](https://cloud.githubusercontent.com/assets/15614269/21515160/d0e8336a-ccd5-11e6-8c0e-5903204ac4c1.png)
this figure show the setup of the column crop_id to point to the id of crops table.
when I try to do the join at the web UI the error pops up (shown in the next figure)
![image](https://cloud.githubusercontent.com/assets/15614269/21515224/51a99214-ccd6-11e6-89db-951447b5a4a8.png)

**Comment by asafeilam** [comment]
hi sameer,
i updated my qustion and gave more details on the webpage.
did you see it?
if yes,  do you know what is the source for this mismatch?
best,
asi.

בתאריך 28 בדצמ׳ 2016 2:15 לפנה״צ,‏ "Sameer Al-Sakran" <
notifications@github.com> כתב:

**Comment by asafeilam** [comment]
Dear friends,

does anyone have a clue why I experienced this problem?

asi.
