### ISSUE TITLE
MySQL unfolding of JSON fails for `boolean` and `bigint` attributes

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#24720]
**Describe the bug**
MySQL unfolding of JSON fails for `boolean` and `bigint` attributes - and perhaps other types too.

Workaround is the same as described in https://github.com/metabase/metabase/issues/22732#issuecomment-1127424455, disable JSON unfolding.

**To Reproduce**
1. Create a MySQL 8 table like this:
```
CREATE TABLE `x_jsontest` (`jsoncol` json DEFAULT NULL) ENGINE=InnoDB;
INSERT INTO `x_jsontest` (`jsoncol`) VALUES ('{"mybool": true, "myint": 1234567890123456}');
```
2. Metabase > Admin > Databases > (mysql) > Sync database schema now - there's be errors during fingerprinting
3. New question > (mysql) > (x_jsontest) - cannot view the table, it fails with:
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BIGINT)`... or ...`near 'BOOLEAN)`...

**Expected behavior**
Don't break existing tables if they contain JSON. It's now possible to disable unfolding, but then you'll have to manually set that, do a sync, and then manually go through all tables in Data Model, since the JSON columns has been set to Visibility="Only in detail view".

**Information about your Metabase Installation:**
Tested 0.44.0 with MySQL 8 data source

**Comment by HillReywer** [comment]
We have a similar bug after the last update. Application version 0.44.1

**Comment by erfantkerfan** [comment]
is there any update on this issue?
it is breaking some of out dashboard
