### ISSUE TITLE
Run clj-kondo against `test/` code in CI

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#24727]
Using kondo to do our linting for `test/` would let us remove the separate bespoke namespace linter since kondo can do that for us now.

Related: #20306

It will be a bit of work tho.

```
clj-kondo --parallel --lint test
...
linting took 14101ms, errors: 711, warnings: 725
```

There are a lot of errors and warnings in the test code using the config we use for `src/`. A lot of stuff looks pretty simple, like it could be fixed without too much ceremony, but it will take a while to do it.

Open questions:
- Do we want to create a separate config for test code because some things we care about in `src/` aren't important in tests, such as public vars with no docstrings? 
   - If we do want different configs, can we keep the single config file, but disable some linters for test namespaces? Not sure about this. It would be nice tho so we didn't have to update two files every time we need to tell Kondo how to lint a macro or things like that
   - I think linters like
   
      ```
      error: #'metabase.sync.sync-metadata.fks/mark-fk! is private
      ```
      should be disabled for `test/` but keep enabled for `src/`.
- Can we start with a config that only makes unsorted namespaces an error, and makes other stuff warnings, so we can remove the separate namespace linter immediately? And then fix the warnings and change them to errors in a piecemeal fashion?

##### TODO

- [ ] Create a Kondo config for `test/` namespaces -- maybe call this something like `.clj-kondo/test-config.edn` if we go with a separate file?
- [ ] Fix errors
- [ ] Add job to GitHub actions -- see https://github.com/metabase/metabase/blob/master/.github/workflows/backend.yml#L23 for the current job

**Comment by borkdude** [comment]
As discussed with @dpsutton I'm taking an initial look at this now.
