### ISSUE TITLE
Add clj-kondo to scripts in `bin/` namespace

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#24735]
Need to lint everything! At the very least, it will help us catch silly errors and keep style consistent.

Related:
- #20306 
- #24727

**Comment by camsaul** [comment]
To clarify a bit, we have the `./bin/kondo.sh` script for running Kondo against everything we want to run it against. This issue is that we should be running Kondo against the Clojure code inside the `./bin` directory -- our migrations file linter, code for building Metabase and for building drivers, and the release script, and their associated tests. We should add the appropriate directories to the `./bin/kondo.sh` script and to CI (or maybe CI should just use `./bin/kondo.sh` itself?) and fix any failures that might be present.

**Comment by kienstra** [comment]
Hi @camsaul,
Could you use PR https://github.com/metabase/metabase/pull/34268 for this issue?

Thanks!
