### ISSUE TITLE
The CSV/XLSX download for a pivot table should be pivoted

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2473]
-  I am using the Chrome browser.
-  My computer's OS is Mac OSX.
-  My Metabase version is v0.17.0

Currently if you run a query which displays a pivoted table of data in the browser then go to download the file you get a different set of results.  This is confusing and inconsistent for users.  If a table is going to be pivoted it should be that way in the CSV as well.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by rafaelveloso** [comment]
Even better, there should be an option when exporting a pivot table to CSV allowing to choose raw or pivoted data before exporting.

**Comment by tlrobinson** [comment]
Now that we support arbitrary column selections and reordering it should probably also match that.

**Comment by josteinaj** [comment]
Also an issue when exporting XLSX. This, combined with #7902, makes it difficult to use Metabase for creating the reports we need.

**Comment by PISA93** [comment]
Is this feature in the works? I did hear that it would be implemented but couldn't find any progress updates?

**Comment by lea-sheets** [comment]
Can you please update on the priority/road map of this issue?

**Comment by cdeweyx** [comment]
CSV is merged for 50 here: https://github.com/metabase/metabase/pull/41668/

Reframing this issue around XLSX

**Comment by lea-sheets** [comment]
> CSV is merged for 50 here: #41668
> 
> Reframing this issue around XLSX

Awesome!! I just checked ability to do this in our instance and it doesn't seem available yet. Do you know when this will be rolled out?

**Comment by adam-james-v** [comment]
Reopened as we want to adjust how this feature is introduced into existing downloads.

**Comment by Tony-metabase** [comment]
Hi @adam-james-v can I remove the milestone from the issue? Cause it might confuse people into thinking this is fixed for 50.7

**Comment by davidjmorris** [comment]
Any news on this happening? I have customers who want a report from me for usage last month. The report needs to be in a cross tab format / pivot table. If met base doesn't want to export it in the pivotable format, because they want to keep customers "in" met abase, that seems a bit defeatist to me. That's not very customer focused.

**Comment by cdeweyx** [comment]
> Any news on this happening? I have customers who want a report from me for usage last month. The report needs to be in a cross tab format / pivot table. If met base doesn't want to export it in the pivotable format, because they want to keep customers "in" met abase, that seems a bit defeatist to me. That's not very customer focused.

What version are you on? As of [v51](https://www.metabase.com/releases/metabase-51) you should see a "Keep pivoted" option on downloads. We are iterating on the performance of this features for very large datasets, but in most cases it should work well.

![Image](https://github.com/user-attachments/assets/d4bbee6b-e9dd-4403-8b94-5208ddc1d06a)

**Comment by mmarcoux09** [comment]
Hi! I might be dumb... but I don't see the option :( @cdeweyx 

Using docker image Metabase 0.55.4

<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/2b7cf19f-f6a5-41ea-a5b2-1484f8d1a3bc" />

**Comment by badsector998** [comment]
> Hi! I might be dumb... but I don't see the option :( [@cdeweyx](https://github.com/cdeweyx)
> 
> Using docker image Metabase 0.55.4
> 
> <img alt="Image" width="1469" src="https://private-user-images.githubusercontent.com/83434552/457179682-2b7cf19f-f6a5-41ea-a5b2-1484f8d1a3bc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM0NDYxOTgsIm5iZiI6MTc3MzQ0NTg5OCwicGF0aCI6Ii84MzQzNDU1Mi80NTcxNzk2ODItMmI3Y2YxOWYtZjZhNS00MWVhLWE1YjItMTQ4NGY4ZDFhM2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzEzVDIzNTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMjFjYTI5OTUwNDkxOGFkYjk4YzZkNjQ3MjMxYjMzMmFjYzliYjI3ZjNlZmIzNGE4ZGY2OWU1ZWNkNmFiMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YgAeQpQvcE1xYgiCkdpIgvn9Fz6gScNjP-wG9oyacrU">

try check Visualization beside cog icon. Then choose pivot table instead of normal table. I just fixed it this way.
