### ISSUE TITLE
The base-type/data-type should be shown on the data model editing pages

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2474]
There is currently no indication on the data model edit pages that Metabase understands the actual type of each column because we don't show the underlying base-types assigned to the columns.  When talking to a couple of users recently this was confusing because they were not confident how Metabase was treating the data.

| Column       | Database type | Base type       | Semantic type          | Effective type |
|--------------|---------------|-----------------|------------------------|----------------|
| id           | uuid          | type/UUID       | type/PK                | type/UUID      |
| categories   | text          | type/Text       | type/Category          | type/Text      |
| created_at   | int8          | type/BigInteger | type/CreationTimestamp | type/Instant   |
| is_processed | bit           | type/*          | _null_                 | type/*         |

Related to #1611

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by brunobergher** [comment]
This is shown in "original schema"
