### ISSUE TITLE
[SerDes 45] Support offline "full" serialization for data model: include fingerprints, FieldValues, etc.

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#24769]
Part of #24795

Follow-on to:

- #24767

## Serialization

We should add support for a new SerDes option to do a "complete" serialization of all metadata for a data warehouse that gets generated during the normal sync process. This means adding stuff that is not currently serialized: FieldValues, Field fingerprints, etc.

What exactly needs to be synced is an open question, but the end goal is that we should be able to serialize all of the metadata for a data warehouse generated by the "normal" sync process.

I _think_ we should also be syncing user-generated metadata like custom FieldValues, descriptions, etc. I'm not sure to what degree we need to do this (do we sync Models, Metrics, Segments, etc. as well?) -- that's an open question we'll have to discuss with product. In the short term we should start with the stuff that is not an open question however.

This might end up being a large project so please break it out into smaller sub issues if appropriate and add them to #24766. 

## Deserialization

Depending on what approach we go with in #24772 it might not be necessary to add deserialization support for the new stuff we add here. If we decide to hook in to and leverage existing sync code we would not necessarily need to add separate deserialization support on top of that. Example:

1. New complete serialization code serializes full data model including fingerprints
2. New sync code from #24772 can read the info from YAML files and provide it in a format understood by existing sync code
3. Existing sync code does the appropriate thing with fingerprints, etc.

**Comment by bshepherdson** [comment]
On deserialization: it won't be hard to deserialize these properly using the normal system. If we want to override the final step (upsert to the database) and do some new sync-like process instead, that's one of the multimethods and we can override it.
