### ISSUE TITLE
When using saved questions as the source of models we should remove the row limit

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#24793]
**Is your feature request related to a problem? Please describe.**
The query processor has a global row limit of [1048575](https://github.com/metabase/metabase/blob/edd687a9ea2ab1584a2dfff9a1bd3415e23918a5/src/metabase/query_processor/interface.clj#L7-L15).

If we use a saved question as the source of the model, when the saved question query runs, we add the global limit.

There are many use cases when users want to cache models with more than 1M rows. 

**Describe the solution you'd like**
Two options;
1. Remove the limit for model cache
2. Change it to 1B (minimum), ideally 10B.

**How important is this feature to you?**
This is important for model cache, as the feature was designed for large models.

**Comment by dpsutton** [comment]
`select count(*) from dbt_models.page_view` -> 7,868,389
`select count(*) from metabase_cache_134ba_48.model_3367_page_views` -> 1,048,575

**Comment by luizarakaki** [comment]
Extra context
[Slack thread 1](https://metaboat.slack.com/archives/C03SHMZ266R/p1660594649545689)
[Slack thread 2](https://metaboat.slack.com/archives/C01LQQ2UW03/p1660550923631759)

**Comment by calherries** [comment]
Probably related: the row limit applies when a saved question is used as a source in native SQL.

Reproduced in stats: `select count(*) from {{#3367}}` -> 1,048,575

But, it's only in native SQL. Using the query builder to create a count on the Page View model yields 7,868,389.
