### ISSUE TITLE
Object detail page's "connected" punctuation is.

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2480]
weird.

Should be a colon instead of period?

![screenshot 2016-04-29 10 12 03](https://cloud.githubusercontent.com/assets/18193/14923589/e0d97c40-0df2-11e6-8064-bf9ac057e02e.png)

**Comment by kdoh** [comment]
I'd say it should probably be ```:```

**Comment by camsaul** [comment]
fixed by #2904
