### ISSUE TITLE
Allow hiding the whole JSON field at once

### ISSUE THREAD

**Issue by udit-001** [metabase/metabase#24801]
**Is your feature request related to a problem? Please describe.**
There is a json field in my database that I do not want to be queryable by user, it is only used for internal purposes on our db. But if I try to hide the json field, I still have to hide the keys of json separately. Also, the structure of that raw json field keeps changing for us, so that means we have to come back to data model again and hide those keys separately too, which is a lot of work given the structure keeps changing very often.

**Describe the solution you'd like**
Being able to hide the json field itself and all it's nested fields at once, since they all fall under the same json column, there should be a way to hide all descendant fields shown by just one toggle.

**How important is this feature to you?**
This is important for me because the internal json field we have in our database has lots of keys present, and not being able to hide them all causes a lot of clutter in all the data that is retrieved through the questions as well as the filter interface.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tsmacdonald** [comment]
@udit-001 I don't think I'm reproducing this correctly. I created a table with a `json` column and am able to set the visibility to `Do not include` from Admin > Data Model.

![image](https://user-images.githubusercontent.com/784417/220366896-f4c8b228-9e37-4e64-b5d6-687784d8668b.png)

**Comment by udit-001** [comment]
Hey, so it looks like I had JSON unfolding turned on in my database configuration, hence all the fields were shown in the data model separately as well, and turning off the json field wouldn't hide the rest either.

**Comment by tsmacdonald** [comment]
@udit-001 is it reasonable to turn off JSON unfolding for the database? I did that, cleared the saved field values, and rescanned and now the individual JSON columns don't appear. Based on your use case I don't think JSON unfolding is useful to you.
