### ISSUE TITLE
Query builder exclude function is empty/is not empty is mixed up

### ISSUE THREAD

**Issue by EvaSchreyer** [metabase/metabase#24806]
Hi, we use metabase in version 0.44.0.
When I use the is empty/is not empty filter in the query builder, the other value appears in the query settings.
See here the example: I select is not empty, but the filter on top shows is empty.
<img width="233" alt="grafik" src="https://user-images.githubusercontent.com/28557318/184845720-f56df2b9-de66-412a-9b25-3e0d5de7a974.png">

**Comment by flamber** [comment]
Hi @EvaSchreyer 
You select "Exclude", so it's opposite. This was changed in #23677, since it was incorrect previously.

**Comment by EvaSchreyer** [comment]
🤯 ok it somehow makes sense but right now it blows my mind

**Comment by flamber** [comment]
I hope we can clean up the selector, so we can add not/empty to the main options instead of hiding under exclude.

**Comment by coisnepe** [comment]
@flamber Thanks for your reply. When you say "I hope we can clean up the selector", is it something that's actually been scheduled or simply something you might do in the future, but equally might not? I have to take a second every time I need to use this selector, and some people with less experience that I need to help sometimes get really confused.
