### ISSUE TITLE
[Epic] Models bugfixes and improvements

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#24815]
##### Product Docs
[Make model editing faster and easier](https://www.notion.so/metabase/Make-model-editing-faster-and-easier-ee31edef605c486e8f9c0fbe70fa3af2)
[Models GUI question bugs](https://www.notion.so/Models-GUI-question-bugs-c26c653ffd9d4aed80689874d02817ca)

##### High Priority

* https://github.com/metabase/metabase/issues/26046
* https://github.com/metabase/metabase/issues/25458
* #22517
* #23248
* #23018
* #23449
* #23019
* #22715
* #22518 
* #23505
* #23091
* #16674 
* #16675
* https://github.com/metabase/metabase/issues/25437

##### Low Priority

* #25113 (Backend, needs QP work)
* #25601
* #23021
* #24878
* #22521
* #22520 

#### Improvements

* #24823 
* #24821
* #24822
* #24825
* #24824

**Comment by mazameli** [comment]
@daltojohnso and @gusaiani, we can talk about it Monday, but it doesn't seem likely to me that we're going to get to the last two remaining items in this epic, since 1 touches the QP, and the other seems like it might be a fair bit of work without much time left. Agree/disagree?

**Comment by mazameli** [comment]
I'm calling this done and am including a callout in the weekly update about the two items we couldn't get to.
