### ISSUE TITLE
[Models] Adding a new column without rerunning the query in editor mode makes the new column disappear

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#24822]
If the user adds a new column in the query, but doesn’t run the query again in the editor. The new column disappears and don’t show up again, even refreshing the page.

More details here: https://www.notion.so/metabase/Make-model-editing-faster-and-easier-ee31edef605c486e8f9c0fbe70fa3af2

**Comment by paoliniluis** [comment]
I haven't seen this one in 44.2, or maybe I don't have the correct reproduction steps @gusaiani
