### ISSUE TITLE
Incorrect SHA-256 hash for 0.44.1 release

### ISSUE THREAD

**Issue by dsferruzza** [metabase/metabase#24837]
Hi!

Release [0.44.1](https://github.com/metabase/metabase/releases/tag/v0.44.1) states that the SHA-256 for https://downloads.metabase.com/v0.44.1/metabase.jar is expected to be `41855b5fb44d0ad33f7699211b5f92a3ff61cf2c541ec6992c110ba2e9c40e8c`.

But when I download the JAR and compute its hash, I always get `4c842b9b374b0ffa7031b7757722e1dddd9b6aebbb5afe82d82b6eb9730d3791`.

Any idea why?
Did something go wrong in the release process?

**Comment by alxnddr** [comment]
@dsferruzza thanks for pointing out. By accident, I published a wrong release notes draft from an unsuccessful build attempt in which I had the hash mismatch. I fixed it now.
