### ISSUE TITLE
Issue with Reports Dashboard and Recents never loading. 

### ISSUE THREAD

**Issue by JoshHoldenBuildOps** [metabase/metabase#24835]
**Describe the bug**
Recent items and main reports dashboard just keeps spinning. States error HTTP500 within the browser developer tools

**Logs**
[adab97ad-8923-401c-8641-f7748f7e20c9] 2022-08-16T19:51:08-06:00 ERROR metabase.server.middleware.log GET /api/activity/recent_views 500 144.6 ms (2 DB calls) 
{:via
 [{:type java.lang.ClassCastException,
   :message
   "class java.time.OffsetDateTime cannot be cast to class java.time.chrono.ChronoLocalDateTime (java.time.OffsetDateTime and java.time.chrono.ChronoLocalDateTime are in module java.base of loader 'bootstrap')",
   :at [java.time.LocalDateTime compareTo nil -1]}],
 :trace
 [[java.time.LocalDateTime compareTo nil -1]
  [clojure.lang.Util compare "Util.java" 153]
  [clojure.core$compare invokeStatic "core.clj" 842]
  [clojure.core$compare invoke "core.clj" 833]
  [clojure.lang.AFunction compare "AFunction.java" 51]
  [clojure.core$sort_by$fn__6045 invoke "core.clj" 3132]
  [clojure.lang.AFunction compare "AFunction.java" 51]
  [java.util.TimSort countRunAndMakeAscending nil -1]
  [java.util.TimSort sort nil -1]
  [java.util.Arrays sort nil -1]
  [clojure.core$sort invokeStatic "core.clj" 3116]
  [clojure.core$sort_by invokeStatic "core.clj" 3120]
  [clojure.core$sort_by invokeStatic "core.clj" 3120]
  [clojure.core$sort_by invoke "core.clj" 3120]
  [metabase.api.activity$views_and_runs invokeStatic "activity.clj" 176]
  [metabase.api.activity$views_and_runs invoke "activity.clj" 134]
  [metabase.api.activity$fn__79197 invokeStatic "activity.clj" 185]
  [metabase.api.activity$fn__79197 invoke "activity.clj" 182]
  [compojure.core$wrap_response$fn__28102 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__28086 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__28091 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 151]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__69452 invoke "auth.clj" 14]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28142 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 299]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 199]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 199]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 199]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [metabase.api.routes$fn__80435$fn__80436 invoke "routes.clj" 58]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__80590$fn__80591 doInvoke "routes.clj" 67]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28142 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 299]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 199]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77325 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__77322 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__82590$fn__82591$fn__82592 invoke "log.clj" 211]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__82590$fn__82591 invoke "log.clj" 203]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 236]
  [toucan.db$_do_with_call_counting invoke "db.clj" 229]
  [metabase.server.middleware.log$log_api_call$fn__82590 invoke "log.clj" 202]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__88165 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__62859 invoke "security.clj" 149]
  [metabase.server.middleware.json$wrap_json_body$fn__85227 invoke "json.clj" 63]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__85245 invoke "json.clj" 99]
  [metabase.server.middleware.offset_paging$handle_paging$fn__62883 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__88432 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__88451 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35776 invoke "misc.clj" 59]
  [metabase.server.middleware.session$reset_session_timeout$fn__47265 invoke "session.clj" 377]
  [metabase.server.middleware.session$bind_current_user$fn__47248$fn__47249 invoke "session.clj" 313]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 292]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 281]
  [metabase.server.middleware.session$bind_current_user$fn__47248 invoke "session.clj" 312]
  [metabase.server.middleware.session$wrap_current_user_info$fn__47230 invoke "session.clj" 262]
  [metabase.server.middleware.session$wrap_session_id$fn__47214 invoke "session.clj" 195]
  [metabase.server.middleware.auth$wrap_api_key$fn__69460 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__88352 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35759 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35784 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__88394 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35787 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__88181 invoke "ssl.clj" 48]
  [metabase.server$async_proxy_handler$fn__82362 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 487]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 732]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 479]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 409]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run nil -1]],
 :cause
 "class java.time.OffsetDateTime cannot be cast to class java.time.chrono.ChronoLocalDateTime (java.time.OffsetDateTime and java.time.chrono.ChronoLocalDateTime are in module java.base of loader 'bootstrap')",
 :message
 "class java.time.OffsetDateTime cannot be cast to class java.time.chrono.ChronoLocalDateTime (java.time.OffsetDateTime and java.time.chrono.ChronoLocalDateTime are in module java.base of loader 'bootstrap')"}

[adab97ad-8923-401c-8641-f7748f7e20c9] 2022-08-16T19:51:08-06:00 ERROR metabase.server.middleware.log GET /api/activity/popular_items 500 144.0 ms (2 DB calls) 
{:via
 [{:type java.lang.ClassCastException,
   :message
   "class java.time.OffsetDateTime cannot be cast to class java.time.chrono.ChronoLocalDateTime (java.time.OffsetDateTime and java.time.chrono.ChronoLocalDateTime are in module java.base of loader 'bootstrap')",
   :at [java.time.LocalDateTime compareTo nil -1]}],
 :trace
 [[java.time.LocalDateTime compareTo nil -1]
  [clojure.lang.Util compare "Util.java" 153]
  [clojure.core$compare invokeStatic "core.clj" 842]
  [clojure.core$compare invoke "core.clj" 833]
  [clojure.lang.AFunction compare "AFunction.java" 51]
  [clojure.core$sort_by$fn__6045 invoke "core.clj" 3132]
  [clojure.lang.AFunction compare "AFunction.java" 51]
  [java.util.TimSort countRunAndMakeAscending nil -1]
  [java.util.TimSort sort nil -1]
  [java.util.Arrays sort nil -1]
  [clojure.core$sort invokeStatic "core.clj" 3116]
  [clojure.core$sort_by invokeStatic "core.clj" 3120]
  [clojure.core$sort_by invokeStatic "core.clj" 3120]
  [clojure.core$sort_by invoke "core.clj" 3120]
  [metabase.api.activity$views_and_runs invokeStatic "activity.clj" 176]
  [metabase.api.activity$views_and_runs invoke "activity.clj" 134]
  [metabase.api.activity$fn__79257 invokeStatic "activity.clj" 252]
  [metabase.api.activity$fn__79257 invoke "activity.clj" 244]
  [compojure.core$wrap_response$fn__28102 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__28086 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__28091 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 151]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__69452 invoke "auth.clj" 14]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28142 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 299]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 199]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 199]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 199]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [metabase.api.routes$fn__80435$fn__80436 invoke "routes.clj" 58]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__80590$fn__80591 doInvoke "routes.clj" 67]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28142 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 299]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 199]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 300]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77325 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__77322 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__82590$fn__82591$fn__82592 invoke "log.clj" 211]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__82590$fn__82591 invoke "log.clj" 203]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 236]
  [toucan.db$_do_with_call_counting invoke "db.clj" 229]
  [metabase.server.middleware.log$log_api_call$fn__82590 invoke "log.clj" 202]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__88165 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__62859 invoke "security.clj" 149]
  [metabase.server.middleware.json$wrap_json_body$fn__85227 invoke "json.clj" 63]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__85245 invoke "json.clj" 99]
  [metabase.server.middleware.offset_paging$handle_paging$fn__62883 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__88432 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__88451 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35776 invoke "misc.clj" 59]
  [metabase.server.middleware.session$reset_session_timeout$fn__47265 invoke "session.clj" 377]
  [metabase.server.middleware.session$bind_current_user$fn__47248$fn__47249 invoke "session.clj" 313]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 292]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 281]
  [metabase.server.middleware.session$bind_current_user$fn__47248 invoke "session.clj" 312]
  [metabase.server.middleware.session$wrap_current_user_info$fn__47230 invoke "session.clj" 262]
  [metabase.server.middleware.session$wrap_session_id$fn__47214 invoke "session.clj" 195]
  [metabase.server.middleware.auth$wrap_api_key$fn__69460 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__88352 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35759 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35784 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__88394 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35787 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__88181 invoke "ssl.clj" 48]
  [metabase.server$async_proxy_handler$fn__82362 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 487]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 732]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 479]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run nil -1]],
 :cause
 "class java.time.OffsetDateTime cannot be cast to class java.time.chrono.ChronoLocalDateTime (java.time.OffsetDateTime and java.time.chrono.ChronoLocalDateTime are in module java.base of loader 'bootstrap')",
 :message
 "class java.time.OffsetDateTime cannot be cast to class java.time.chrono.ChronoLocalDateTime (java.time.OffsetDateTime and java.time.chrono.ChronoLocalDateTime are in module java.base of loader 'bootstrap')"}
**To Reproduce**
1. Go to metabase.staging.buildops.com
2. Just load page it will never finish spinning circle
3. No need it is right on the main page

**Expected behavior**
Reports tiles should load and webpage should finish loading.

**Screenshots**
<img width="1404" alt="Screenshot 2022-08-16 at 10 05 09 PM" src="https://user-images.githubusercontent.com/93621276/185032415-9781a2a4-3341-4ca4-bcea-0b3d6d6ad3c4.png">

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: Blocker for weekly testing on updates. We cannot tell during our weekly application update if this issue will have any affect on our live.metabase.com

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "4.14.281-212.502.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.23"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-04",
      "tag": "v1.44.0",
      "branch": "release-x.44.x",
      "hash": "d3700f5"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @JoshHoldenBuildOps 

Please use the support email, when using the Pro/Enterprise.

I can see you are testing upgrading from 1.42.2. Is this the first test you have done with a newer version where it fails?

Everything is point to something in this query returning something that it didn't expect:
https://github.com/metabase/metabase/blob/master/src/metabase/api/activity.clj#L134
But I have not been able to reproduce, so it must be something fairly specific to your setup.
Are you able to check the MySQL query debug log of the Metabase application database, where you should be able to see the query used.
