### ISSUE TITLE
Date filed does not get aggregated to 'day/week/month'

### ISSUE THREAD

**Issue by shivaGhandi** [metabase/metabase#24868]
**Describe the bug**
there is a 'Date' field which also is 'Date' in Model, but  is different form other 'Date' fields,  granularity of 'day'. 'Month', 'week' and 'year' are not available in aggregates just for this field.

**To Reproduce**
Please look at the screenshots.

**Expected behavior**
it is supposed to show this granularity by 'date' fields.
![image](https://user-images.githubusercontent.com/111515280/185423582-003728d1-0605-48cb-9b31-450d6245070d.png)

**Screenshots**
here is the way this specific Data field looks like:
![image](https://user-images.githubusercontent.com/111515280/185419449-d3b4b367-888a-4eee-b2e1-7b137fc084f6.png)
![image](https://user-images.githubusercontent.com/111515280/185419673-ec5a5bb5-5a71-4a8f-b91d-75db2bc8f218.png)

here is the model for this field:
![image](https://user-images.githubusercontent.com/111515280/185420988-0b4c2a12-b674-4d1c-a13e-53968c6f4f07.png)

and the data itself of this field:
![image](https://user-images.githubusercontent.com/111515280/185422114-46052899-9ed6-49be-9f1b-fb9a39c47dac.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version:  Chrome Version 104.0.5112.81
- Your operating system: Windows 10 Home version20H2
- Your databases: redshift
- Metabase version:  0.44.0 
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: redshift

**Severity**
sometimes on some fields it happens, and it blocks the user and he can't do anything! but when it does not happen, that's fine

[log (2).txt](https://github.com/metabase/metabase/files/9374848/log.2.txt)

**Comment by shivaGhandi** [comment]
@flamber thank you very much for your fast reply:

**Comment by flamber** [comment]
@shivaGhandi You need to go to this address https://metabase.yourstorebox.com/api/field/13305 and include the output here. It's only you who can access that URL.

**Comment by shivaGhandi** [comment]
Hi @flamber,

**Comment by flamber** [comment]
@shivaGhandi Your database says it's a `varchar` column type, so that's why. You will need change that on your database or cast the field: https://www.metabase.com/docs/latest/data-modeling/metadata-editing.html#casting-to-a-specific-data-type
