### ISSUE TITLE
Newly created Model not an option when creating a new question

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#24878]
Probably related to #25144
 
tl;dr: We currently can't create a question from a freshly created model unless we reload the app.

Likewise when moving a model from one collection to another, the changes are not reflected in the model picker when creating a new question.

### To reproduce

1. Create a model
2. Reload the page
3. Create another model
2. Without refreshing the browser, create a question and choose Models as the source.

You will not see the newly created model.

If you reload the page and retry a new question, you will see the model.

**Comment by flamber** [comment]
Sounds like a repeat of #19737
