### ISSUE TITLE
Data changes upon refresh 

### ISSUE THREAD

**Issue by christinavavoulis** [metabase/metabase#24883]
**Describe the bug**
When I refresh the screen, the data (including historical data that should not be changing at all) changes. 
**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**
I expect to see the same data when I refresh, unless it is new data from the current month 
**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (Chrome/104.0.0.0)
- Your operating system: (Intel Mac OS X 10_15_7)
- Your databases: (postgres, snowflake)
- Metabase version: (0.40.2)
- Metabase hosting environment: ()
- Metabase internal database: ( Postgres)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely? Blocking my usage of Metabase - if we cannot trust the data, then we cannot use metabase at all for any analysis. 
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
I have a 10 second video but the file is too big to attach here.

**Comment by flamber** [comment]
You should upgrade immediately to a newer release: https://github.com/metabase/metabase/releases/latest
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And upload your video to somewhere and link it.
