### ISSUE TITLE
Adjusting SITE URL has no effect / white screen

### ISSUE THREAD

**Issue by ildar-shamilov-clearscale** [metabase/metabase#24899]
**Describe the bug**
I deployed latest version of metabase docker image & mapped to my domain.
Entered SITE url in settings like: https://domain.com/reports
When i open the page i see metabase caption on tab and i see in browser logs that page trying to load scripts/styles from two locations: first /reports and the second is the root of my domain.
Then on the page i only see white screen.

**Expected behavior**
Probably it should not load anything from the root, b/c there is nothing to load.

**Screenshots**
![image](https://user-images.githubusercontent.com/56872613/185638008-fba1a483-f540-46fe-a63e-ed1a2821801d.png)

**Information about your Metabase Installation:**
Docker:latest

And same happens locally:
![image](https://user-images.githubusercontent.com/56872613/185641031-e72e0033-b519-4050-8e00-f5872c933be6.png)
But it works locally b/c files are in the root, even if i set URL to localhost:3000/reports

**Comment by flamber** [comment]
Hi @ildar-shamilov-clearscale 
You need to provide the reverse-proxy config you're using. The problem is somewhere in that.

**Comment by ildar-shamilov-clearscale** [comment]
Hi @flamber, thanks.

At the bottom screenshot from my local machine, i am using plain docker without ant proxy,
and still see 4 requests to /reports and 4 requests to the root.
If i clean Site URL setting, then there is only 4 requests to the root.
What kind of config can i provide?

**Comment by flamber** [comment]
@ildar-shamilov-clearscale You cannot just change the URL to something different. You'll need to use a reverse-proxy like Nginx to handle non-root paths, which would also allow you to handle SSL certificates etc more easily.

Example Nginx config:
```
server {
  listen 80;
  server_name www.example.com;
  location /reports/ {
    proxy_http_version 1.1;
    proxy_read_timeout 600;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:3000/;
  }
}
```
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-debian.html

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
