### ISSUE TITLE
Be smarter about humanizing table and field names

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2490]
Currently when "humanizing" table and field names we only split words on underscores and hyphens, e.x. `dashboard-card` and `dashboard_card` become `Dashboard Card`, but `dashboardcard`, `DashboardCard`, `dashboard card`, etc, do not. https://github.com/metabase/metabase/blob/master/src/metabase/models/common.clj#L109

At a minimum we should split on whitespace and probably lower-to-uppercase boundaries (e.x. `CamelCase` becomes `Camel Case`).

We could also attempt to detect individual words even within an all lowercase string with no delimiting characters using an algorithm such as http://stackoverflow.com/a/11642687 I tried that algorithm on a few of Metabase's own tables and it seems to work quite well:

```
dashboardcard
dashboard card

dashboardcardsubscription
dashboard card subscription

emailreport
email report

emailreportexecutions
email report executions
```

**Comment by MartinArens** [comment]
it's broken for me :(
v0.27.1

![selection_225](https://user-images.githubusercontent.com/7610680/33711810-91430d28-db45-11e7-8721-83ed941f8fa6.png)

**Comment by mazameli** [comment]
Hey, @MartinArens. I think you're actually running into this issue: https://github.com/metabase/metabase/issues/5751
