### ISSUE TITLE
Google Sign In fails after upgrading from 0.43.4 -> 0.44.* (both 0.44.0 and 0.44.1)

### ISSUE THREAD

**Issue by alexterray** [metabase/metabase#24911]
**Describe the bug**
Previously set up Google Sign In which worked great up til 0.43.4. We tried upgrading from 0.44.1 and Google Sign In no longer worked. I noticed in the Console that it went from the legacy approach to the updated gsi flow, but I see the following in the Chrome dev console when running 0.44.0 or 0.44.1:

```
client:131          GET https://accounts.google.com/gsi/status?client_id={obfuscated}&as=oJ8nPECcdmpZcEm2lwry7g 403
GSI_LOGGER]: The given origin is not allowed for the given client ID.
```

This is with no changes to either the Metabase GSI admin config nor on Google Cloud. Reverting back to 0.43.4 shows the following console message, and I am able to sign in with Google with no issues.

```
cb=gapi.loaded_0?le=scs:587 Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.
```

**Severity**
Moderate. We can get by on 0.43.4 but our whole organization registers and logs in with Google Sign In, so this is preventing us from upgrading and getting new features. I imagine this would be a big blocker for other orgs in a similar situation.

**Comment by flamber** [comment]
Hi @alexterray 
The only way I can reproduce this is by not including the URL used to access Metabase in the Google Cloud Console's https://console.cloud.google.com/apis/credentials for the OAuth 2.0 Client ID's Authorized JavaScript origins.
https://www.metabase.com/docs/latest/people-and-groups/google-and-ldap.html#enabling-google-sign-in

If my Metabase is accessed on `https://metabase.example.com`, but GCC is defined as `http://metabase.example.com` (http instead of https) or `https://metabase.other.com`, then you'll see a blank popup screen on login (thanks Google for being so helpful) with that error in the console.

**Comment by santhoshnarayanan** [comment]
@flamber  - I faced the same issue today and all members in my organisation were unable to use metabase. We had to downgrade to the old version to enable SSO. Please help to prioritise the issue. 

Latest Metabase version where Google SSO would work is **0.43.4**

**Comment by flamber** [comment]
@santhoshnarayanan There's nothing I can prioritize without given exact steps-to-reproduce and enough logs.

**Comment by alexterray** [comment]
@flamber the only output I see on the metabase side is when I hit the login splash page:
```
2022-08-23 21:54:41,982 DEBUG middleware.log :: GET /api/user/current 401 12.8 ms (0 DB calls) 
"Unauthenticated"

2022-08-23 21:54:42,185 DEBUG middleware.log :: GET /api/session/properties 200 103.1 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (45 total active threads) Queries in flight: 0 (0 queued)
```
Beyond that, I posted everything that was present in the JS console. I can tell you that my OAuth origins are set properly as Google Sign in still works without any config change when I revert back to v0.43.4. 

Steps to reproduce:
1. Configure Google Sign In on Metabase using v0.43.4
2. Re-run metabase using v0.44.0 or v0.44.1 pointed to the same app DB
3. Attempt to sign in with Google. You should see similar output to what I posted in the JS console.

Not sure what else I can provide here... FWIW I'd be happy to jump on a zoom call or similar to screenshare what I'm seeing

**Comment by soymsk** [comment]
I also met this issue today, after upgrading to v0.44.1.
I did the same steps with @alexterray. 

I found a discussion about some problems in google OAuth library that is used in Metabase frontend. Using different ports may cause this problem? (In my case, I used <domain>:3002)
https://github.com/metabase/metabase/pull/22868#issuecomment-1144043271

**Comment by flamber** [comment]
@alexterray I cannot reproduce. I have multiple instances with multiple different GCC setups. Try setting up a new OAuth.

@soymsk If you are accessing Metabase via `http://example.com:3002`, then that would be the URL you need to input into GCC's Authorized JavaScript origins. And then make sure that your Site URL is defined correctly too in Admin > Settings > General.

**Comment by alexterray** [comment]
@flamber I tried creating a new OAuth Client ID and it's the exact same behavior: on 0.43.4 it works no problem, 0.44.1 hangs after login. I tried spinning up fresh instances pointing to the default H2 DB, and same story. 0.43.4 worked, 0.44.1 did not.

**Comment by zxpower** [comment]
We're running Metabase 0.43.5 and Google Sign-in works, but I'm getting notifications from Google that this type of OAuth is Out-of-band and should be migrated (https://developers.google.com/identity/protocols/oauth2/resources/oob-migration).

**Comment by flamber** [comment]
There's now many hundreds of instances on v44, where Google Sign-in is working as expected. The only places where I have seen this problem is when the "Authorized JavaScript origins" is not defined correctly.
