### ISSUE TITLE
Click-and-Drag filtering in dashboards has an offset if card is not touching the left wall

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#24912]
The amount of offset equals the distance of the card from the left wall.

![mb_dynamic_issue](https://user-images.githubusercontent.com/15974735/185729113-e867f7f4-0509-4cea-aad5-654d942ff24f.gif)

v .44.1

**Comment by vvaezian** [comment]
@flamber Please triage.

**Comment by flamber** [comment]
Regression since 0.40.0

**Comment by ranquild** [comment]
Firefox only
