### ISSUE TITLE
Is it possible to track usage on Metabase

### ISSUE THREAD

**Issue by poffo** [metabase/metabase#24932]
Hello,

I would like to know if I can get metrics on which users and how frequently the users are consuming specific dashboards.

It would be great if I could connect with Google Analytics somehow to get metrics.

Thank you.

**Comment by santhoshnarayanan** [comment]
@poffo - you can have the information from metabase internal database tables. One can have info on pulses, dashboards, visitors, usage and much more from them.

**Comment by poffo** [comment]
@santhoshnarayanan 
Do we have documentation available to understand the tables with this information?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
