### ISSUE TITLE
Bubble size not consistent across multiple series

### ISSUE THREAD

**Issue by nil-nil** [metabase/metabase#24936]
**Describe the bug**
When creating a scatter plot with a series breakout, the bubble size is calculated relative to the other values in the series, not to the values of all series.

**To Reproduce**
1. Create a sql query
```
select 1 x, 1 y, 20 size, 'a' breakout
union all  select 2 x, 10 y, 10 size, 'a' breakout
union all  select 3 x, -9 y, 6 size, 'a' breakout
union all  select 4 x, 100 y, 30 size, 'a' breakout
union all  select 5 x, -20 y, 70 size, 'a' breakout
union all  select 1.5 x, 1 y, 20000000 size, 'b' breakout
union all  select 2.5 x, 10 y, 10000000 size, 'b' breakout
union all  select 3.5 x, -9 y, 6000000 size, 'b' breakout
union all  select 4.5 x, 100 y, 30000000 size, 'b' breakout
union all  select 5.5 x, -20 y, 70000000 size, 'b' breakout
```
2. Visualization: scatter - without breakout, then it looks correct
![image](https://user-images.githubusercontent.com/1447303/186670281-aedacc66-4911-4370-bf25-ade45cda3a3b.png)
3. Add breakout, then the bubbles becomes the same size
![image](https://user-images.githubusercontent.com/1447303/186670497-d7a8824a-8a2d-4b0a-a971-768085f0217d.png)

**Expected behavior**
I would expect the bubbles for series b to be larger than for series a. The same scaling factor should apply across all values in both series like they do if you turn off the breakout. I only want the breakout to affect colours.

**Information about your Metabase Installation:**
- Browser: Chrome 104.0.5112.101
- OS: macOS 12.4
- Databases: Postgres
- Metabase version: v0.44.0
- Metabase hosting environment: k8s
- Metabase internal database: Postgres

**Severity**
It's annoying.

**Comment by flamber** [comment]
Regression since 0.44.0, likely caused by #24099. Though there's been several problems before like 23977, 22929, 22527.
