### ISSUE TITLE
Remove Angular

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2495]
Port pages to React and use main React router + Redux store:

TODO:

- [ ] Figure out what to replace Angular Resource with
- [x] Port remaining bits of AppState etc to Redux

Completed:

- [x] `/questions/`
- [x] `/questions/:section`
- [x] `/questions/:section/:slug`
- [x] `/questions/edit/:section`
- [x] `/admin/datamodel/metric`
- [x] `/admin/datamodel/metric/:metricId`
- [x] `/admin/datamodel/segment`
- [x] `/admin/datamodel/segment/:metricId`
- [x] `/admin/datamodel/:objectType/:objectId/revisions`
- [x] `/`
- [x] `/admin/databases`
- [x] `/admin/databases/:databaseId`
- [x] `/admin/databases/create`
- [x] `/admin/datamodel/database`
- [x] `/admin/datamodel/database/:databaseId`
- [x] `/admin/datamodel/database/:databaseId/:mode`
- [x] `/admin/datamodel/database/:databaseId/:mode/:tableId`
- [x] `/admin/people`
- [x] `/admin/settings`
- [x] `/dash/:dashId`
- [x] `/pulse`
- [x] `/pulse/create`
- [x] `/pulse/:pulseId`
- [x] `/setup`
- [x] `/user/edit_current`
- [x] `/q`
- [x] `/q/:serializedCard`
- [x] `/card/:cardId/:serializedCard`
- [x] `/auth/login`
- [x] `/auth/logout`
- [x] `/auth/forgot_password`
- [x] `/auth/reset_password/:token`
- [x] `/auth/password_reset_token_expired`
- [x] `/unauthorized`
- [x] `not_found`

**Comment by camsaul** [comment]
🚿

**Comment by tlrobinson** [comment]
Updated with the current state of things.

**Comment by lewisl9029** [comment]
RE: Figure out what to replace Angular Resource with

I think cashay looks really promising. It's basically a simple GraphQL client that works well with Redux.

https://medium.com/@matt.krick/replacing-relay-with-redux-2990c81aa807#.8edf7ki1c

Although how feasible that is depends on if we want to buy into GraphQL on the server side.

**Comment by camsaul** [comment]
Why would we want a GraphQL client when we're not doing GraphQL

**Comment by salsakran** [comment]
Yeaaaaaaaah. I think we're doing pretty well on dev hipster points. I'd strongly lean towards something that doesn't require changes on the backend for this.

**Comment by camsaul** [comment]
Just because facebook is pushing it doesn't make it cool! *cough* HipHop *cough*

**Comment by lewisl9029** [comment]
In that case I'm not sure what options we have other than just ripping out Angular Resource and replacing it with a bunch of fetch calls. =/

**Comment by tlrobinson** [comment]
I like GraphQL and it's something I think we should explore more (and I like what I've read about Cashay), but we've got a lot of boring old REST endpoints already and it would be easiest to just be able to use those as-is in the meantime.

**Comment by camsaul** [comment]
maybe we can find a way to make our REST endpoints less boring? I'm thinking rename them all different appropriate emoji, e.g.

> GET /api/🎶

**Comment by salsakran** [comment]
closed in #3626
