### ISSUE TITLE
Add option to include today's data when filtering date fields

### ISSUE THREAD

**Issue by MaxSavenkov** [metabase/metabase#2496]
I'd like to be able to view data for last 30 days, including today's most recent data. Currently, Query Builder provides no way to do that: "This month" includes today's data, but stops on month boundaries, and "Past 30 days" does not include today. Perhaps this options could be added as a checkbox below "Past 7" and "Past 30" days?

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by timiyay** [comment]
I support this feature request. We ran afoul of this on day 1 of using Metabase, as our business users intuitively expect "today" to be part of "past 30 days".

**Comment by zaiddabaeen** [comment]
This is one of the reasons I go back to writing SQLs rather than using Metabase editor.

**Comment by mazameli** [comment]
Closing as duplicate of #4749. Favoring the more recent issue because it has more recent activity as well as designs in it.
