### ISSUE TITLE
Charts should allow to use non-zero base

### ISSUE THREAD

**Issue by vkovalskiy** [metabase/metabase#2497]
Most of the time when we start tracking some stats we with Metabase we are already at some level of the system usage. So we do not need to see the 0 to initial value span at all. Because it kills dynamics monitoring. All graphs that have Y-axis should allow to set axis base on the lowest value in the series. So we won't get almost plane lines.

![metabase](https://cloud.githubusercontent.com/assets/564016/14942393/6a15e0ac-0fc4-11e6-968a-5311f5f85357.png)

**Comment by salsakran** [comment]
this was added in v0.20
