### ISSUE TITLE
ERROR metabase.core :: Metabase Initialization FAILED java.lang.NumberFormatException

### ISSUE THREAD

**Issue by travis5491811** [metabase/metabase#25013]
**Describe the bug**
Running fresh install of metabase on fresh ubuntu 22.04 LTS machine with the docs "recommend the latest LTS version of JRE from [Eclipse Temurin](https://adoptium.net/) with HotSpot JVM and x64 architecture" fails with error `java.lang.NumberFormatException` 

**Logs**
```
ug 25 10:52:19 metabase metabase[1324]: 2022-08-25 10:52:19,435 INFO metabase.core ::
Aug 25 10:52:19 metabase metabase[1324]: Metabase v0.44.1 (112f5aa release-x.44.x)
Aug 25 10:52:19 metabase metabase[1324]: Copyright © 2022 Metabase, Inc.
Aug 25 10:52:19 metabase metabase[1324]: Metabase Enterprise Edition extensions are NOT PRESENT.
Aug 25 10:52:19 metabase metabase[1324]: 2022-08-25 10:52:19,445 INFO metabase.core :: Starting Metabase in STANDALONE mode
Aug 25 10:52:19 metabase metabase[1324]: 2022-08-25 10:52:19,446 ERROR metabase.core :: Metabase Initialization FAILED
Aug 25 10:52:19 metabase metabase[1324]: java.lang.NumberFormatException: For input string: "<12345>"
Aug 25 10:52:19 metabase metabase[1324]:         at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
Aug 25 10:52:19 metabase metabase[1324]:         at java.base/java.lang.Integer.parseInt(Integer.java:668)
Aug 25 10:52:19 metabase metabase[1324]:         at java.base/java.lang.Integer.parseInt(Integer.java:786)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.config$config_int.invokeStatic(config.clj:71)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.config$config_int.invoke(config.clj:71)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.server$jetty_config.invokeStatic(server.clj:32)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.server$jetty_config.invoke(server.clj:29)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.server$start_web_server_BANG_.invokeStatic(server.clj:110)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.server$start_web_server_BANG_.invoke(server.clj:102)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.core$start_normally.invokeStatic(core.clj:148)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.core$start_normally.invoke(core.clj:144)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.core$_main.invokeStatic(core.clj:183)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.core$_main.doInvoke(core.clj:177)
Aug 25 10:52:19 metabase metabase[1324]:         at clojure.lang.RestFn.invoke(RestFn.java:397)
Aug 25 10:52:19 metabase metabase[1324]:         at clojure.lang.AFn.applyToHelper(AFn.java:152)
Aug 25 10:52:19 metabase metabase[1324]:         at clojure.lang.RestFn.applyTo(RestFn.java:132)
Aug 25 10:52:19 metabase metabase[1324]:         at metabase.core.main(Unknown Source)
Aug 25 10:52:19 metabase systemd[1]: metabase.service: Main process exited, code=exited, status=1/FAILURE
```

**To Reproduce**
1. Spin up fresh Ubuntu 22.04 LTS server and install dependencies.
2. Download and install Metabase v0.44.1 (112f5aa release-x.44.x) 
3. Install the recommended latest LTS version of JRE from [Eclipse Temurin](https://adoptium.net/) with HotSpot JVM and x64 architecture
4. Run metabase manually or follow docs for running as service https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-debian.html
5. See error

**Expected behavior**
Should be able to start experimenting with metabase

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: n/a
- Your operating system: Ubuntu Server 22.04
- Your databases: n/a
- Metabase version: Metabase v0.44.1 (112f5aa release-x.44.x)
- Metabase hosting environment: Jar-file on Ubuntu
- Metabase internal database: MySQL
- Java Version:

```
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
```

**Severity**
blocking usage of metabase

**Additional context**
Could be related to or regression of https://github.com/metabase/metabase/issues/8282

**Comment by travis5491811** [comment]
added java version info

**Comment by flamber** [comment]
Hi @travis5491811 
Looks like you are including some environment variables, which are incorrectly defined.
From what I can tell, `MB_JETTY_PORT=<12345>`
You need to replace everything within the brackets with values, example `MB_JETTY_PORT=3000`
