### ISSUE TITLE
Pinning a native question that references another question will fail to render

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25022]
**Describe the bug**
When creating a native question that references another question (no matter if native or GUI), the question won't render and will show a "open this question and fill in its variables to see it". If you open the question, everything is fine.

**Logs**
No logs on the BE, as there's no error

**To Reproduce**
1) create a gui question (like new->question->orders->visualize->save it as orders). It should have ID 1
2) create a native question (`select * from {{#1}} as pepe`). Save it
3) Pin the second (native) question to the collection. See it fail when it shouldn't, doesn't have any params

**Expected behavior**
Only fail when there are questions that need params, or when there are questions based on questions that need params and don't have a default param

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your databases: Postgres
- Metabase version: 44.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2

**Additional context**
Reported by a customer

**Comment by iethree** [comment]
I think this is a backend issue. On the frontend, we only show visualizations for pinned questions that have `fully_parametrized` set to true, which comes directly from the backend endpoint:
```
/api/collection/:id/items?pinned_state=is_pinned&sort_column=name&sort_direction=asc
```

On the frontend, the visualization looks fine if we bypass this check. I suspect that the backend is misinterpreting a reference to a saved question as a parameter when it calculates the `fully_parametrized` flag. Is there a way to make that smarter and not treat question references as parameters?

example query: 
```sql
SELECT type1 as "Primary Type", count(*) as Count
from {{#184-pokedex-with-images-gui-question}}  as pokemon
    GROUP BY type1
    ORDER BY count DESC
```
