### ISSUE TITLE
Cannot change email From-name and Reply-to-address when environment variables are used for other settings

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#25057]
**Describe the bug**
It is not possible to change the new From-name and Reply-to-address fields in Admin > Settings > Email when other settings (like SMTP host etc) are set via environment variables. Followup on #22540.

Feels like mixed BE/FE issue, where BE needs to use the environment variables (and ignore input where there's an envvar) when testing/saving the settings, and FE should allow saving when required fields are using envvar.

**To Reproduce**
1. Since I don't know how to mock a Cloud setup, then I just start Metabase with following envvars defined:
`MB_EMAIL_SMTP_HOST`, `MB_EMAIL_SMTP_PORT`, `MB_EMAIL_SMTP_SECURITY`, `MB_EMAIL_SMTP_USERNAME`, `MB_EMAIL_SMTP_PASSWORD`, `MB_EMAIL_FROM_ADDRESS`
2. Admin > Settings > Email - the fields are correctly showing as defined by envvar (**note** on Cloud, most of these fields are not shown)
![image](https://user-images.githubusercontent.com/1447303/187027466-501f3898-a1b4-4192-956e-f1e43727ac20.png)
3. Trying to input something in From-name or Reply-to-address will not allow to save (**note** on Cloud, it will allow you to save, which fails with `Input to test-smtp-connection does not match schema: [(named {:host missing-required-key, :port missing-required-key} details)]`)
![image](https://user-images.githubusercontent.com/1447303/187027506-039d9311-45cc-439e-a53a-1ab278568ae7.png)
4. If I manually input Host, Port and From-address, then I'm allowed to save, but that would fail unless I also included Username and Password.

**Expected behavior**
- On Cloud, allow changing From-name and Reply-to-address without any other inputs
- On other instances using envvar, allow changing fields which are not locked by envvar.

**Information about your Metabase Installation:**
Tested 0.44.1

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/pull/25067
