### ISSUE TITLE
I wish Label and Archive actions were 

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2506]
If this is a bug report, please fill in the blanks:

*  I am using the ___________ browser.
*  My computer's OS is ___________.
*  I'm running Metabase ___________. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is ___________.
*  My Metabase version is ___________.

**Comment by camsaul** [comment]
wish they were ________ ?
