### ISSUE TITLE
MYSQL disable JSON unfolding doesn't work

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#25068]
**Describe the bug**
By default MySQL unfolds JSON contents but it doesn't fold them back when disabling the setting. Also if it fails for instance due to boolean and bigint attributes - and perhaps other types too. There is no way for the client to revert back the unfolding and ends up with a broken table

Only Workaround to remove the json columns is to manually go through each column in the Data Model and set it as 'Do Not Include'

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/110378427/187251431-567d54ff-b05e-455e-a01f-06e37d6ff699.png">

**To Reproduce**

1) Create a MySQL 8 table like this:

```
CREATE TABLE `x_jsontest` (`jsoncol` json DEFAULT NULL) ENGINE=InnoDB;
INSERT INTO `x_jsontest` (`jsoncol`) VALUES ('{"string1": "true", "string2": "123490123456"}');
```

2) Metabase > Admin > Databases > Add the mysql database with the above table
3) Go to Data -> Browse Data -> Select newly connected mysql database -> select x_jsontest table -> Observe unfolded columns
5) Go back to Metabase > Admin > Databases -> mysql database
6) Disable Unfold JSON Columns -> Sync database schema now -> Wait for sync to complete
7) Go to Data -> Browse Data -> Select synced newly connected mysql database -> select x_jsontest table -> Observe again unfolded columns

**Expected behavior**
If Unfold JSON Columns is disabled the database should re-sync the database without the unfolded columns and only view the json as a column

**Information about your Metabase Installation:**

Tested 0.44.1 with MySQL 8 data source

**Severity**
If table contains 100 json keys the client has to manually go through each column in the Data Model and set the unfolded columns (which shouldn't even be there) to 'Do Not Include'. 

**Additional context**
Doesn't happen on PostgreSQL

**Comment by flamber** [comment]
I'm guessing that this might have an easy fix, since it seems like the logic for MySQL is different from Postgres
https://github.com/metabase/metabase/blob/cc632e8193b460edfe13a758eb25d19e927c1c20/src/metabase/driver/mysql.clj#L43-L44
https://github.com/metabase/metabase/blob/0eb5813a179422eb413fafee0bb364f0a14aef49/src/metabase/driver/postgres.clj#L47-L51
