### ISSUE TITLE
Ad-hoc questions never get cached (documentation or actual bug?)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25071]
**Describe the bug**
Maybe this is a feature and we have to document it, but let's say that you save a question and that question gets cached, then if you do an ad-hoc question that has the same syntax as a saved question, nothing gets cached even the query hash should be the same

**Logs**
NA

**To Reproduce**
1) enable caching of questions that take more than 1 second
2) create a native question: "select pg_sleep(5), '1'" (should run in 5 seconds)
3) save it and run it a few times till the cache kicks in
4) one it kicks in, go to create another new native question with the same SQL. See that the cache won't work

**Expected behavior**
Is this something we need to add to the documentation since it was designed like this? or is it a bug?

**Screenshots**

**Information about your Metabase Installation:**
- Your operating system: Pop 22.04
- Your databases: Postgres
- Metabase version: 44.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P3

**Additional context**
NA

**Comment by flamber** [comment]
This is not a bug.
All requests to `/api/dataset` are not using cache.
And requests to `/api/card/:id/query` are not using cache if clicking the Run/Refresh-button, which includes `ignore_cache: true` in the request.

**Comment by paoliniluis** [comment]
So this needs to go on the documentation
