### ISSUE TITLE
I wish Label and Archive actions were sticky at top of saved questions page

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2508]
It's kind of a bummer to select several questions, some of which might be towards the bottom of a long list, and then have to scroll all the way back to the top to apply a label or archive the questions. I wish those actions remained at the top of the screen while I scrolled.

<img width="989" alt="screen shot 2016-05-02 at 2 12 51 pm" src="https://cloud.githubusercontent.com/assets/2223916/14968163/50cd0146-1070-11e6-9f9b-d044fe8aa8e5.png">

**Comment by camsaul** [comment]
related: #2506 :trollface:
