### ISSUE TITLE
Label action on Questions page should have a tooltip

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2509]
All the other cool kids do (i.e. Archive and Favorite).

<img width="876" alt="screen shot 2016-05-02 at 2 09 32 pm" src="https://cloud.githubusercontent.com/assets/2223916/14968365/3042aede-1071-11e6-8a7a-5d72d8ee63b8.png">

**Comment by agilliland** [comment]
@tlrobinson can you take a look at this one?
