### ISSUE TITLE
Interval not working as expected

### ISSUE THREAD

**Issue by iggups** [metabase/metabase#25095]
**Describe the bug**
Create a custom expression like `SumIf([revenue], interval([date_day], -3, "year"))`. The SQL generated looks like:

```
SUM(CASE
               WHEN DATE_TRUNC('year', "dbt"."revenue_daily"."date_day") BETWEEN DATE_TRUNC('year',
                                                                                                     CAST(DATEADD('year', -3, CAST(GETDATE() AS timestamp)) AS timestamp))
                   AND DATE_TRUNC('year', CAST(DATEADD('year', -1, CAST(GETDATE() AS timestamp)) AS timestamp))
                   THEN "dbt"."revenue_daily"."revenue"
               ELSE 0.0 END)             
```

Which means it takes all dates of 2019, 2020 and 2021 but expected is 2019 only.

If the expression is `SumIf([revenue], interval([date_day], -1, "year"))`, metabase generates:

```
SUM(CASE
               WHEN DATE_TRUNC('year', "dbt"."revenue_daily"."date_day") =
                    DATE_TRUNC('year', CAST(DATEADD('year', -1, CAST(GETDATE() AS timestamp)) AS timestamp))
                   THEN "dbt"."revenue_daily"."revenue"
               ELSE 0.0 END)  
```

This is correct and works as expected. Only dates with interval <= -2 don't work. For example -3, -4 and so on.

**To Reproduce**
1. Create custom expression `SumIf([revenue], interval([date_day], -3, "year"))`
2. Look at the question as SQL
3. See wrong behavior

**Expected behavior**
Interval -3 should be the same SQL as Interval -1

**Information about your Metabase Installation:**

- Metabase Version: v0.44.1
- Your databases: Amazon Redshift

**Severity**
Annoying, workaround with absolute dates works.

**Comment by flamber** [comment]
Hi @iggups 
When you input an interval of -3, then Metabase gets results from -3 thru -1. That is how it works.
You would have to do this if you only want 2019:
`SumIf([revenue], interval([date_day], -3, "year") AND NOT interval([date_day], -2, "year"))`
For reference: https://www.metabase.com/docs/latest/questions/query-builder/expressions-list#interval and https://www.metabase.com/learn/dashboards/compare-times
