### ISSUE TITLE
Removed values of enum custom mapping

### ISSUE THREAD

**Issue by AdriMenendezM** [metabase/metabase#25128]
**Describe the bug**
The custom mapping of an enum is deleted when the field is rescanned.

**To Reproduce**
1. Set a custom mapping of an enum
2. Rescan the field
3. Check the custom mapping values

**Expected behavior**
The custom values shouldn't be override

**Screenshots**

https://user-images.githubusercontent.com/16835012/187632022-c0980bd9-bd8d-4d64-bcc4-45d33dad9056.webm

**Severity**
Annoying

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "4.19.0-16-amd64",
    "user.language": "es",
    "user.timezone": "Europe/Madrid"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver",
      "mysql",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.34"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-04",
      "tag": "v0.44.0",
      "branch": "release-x.44.x",
      "hash": "d3700f5"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Comment by ccasado-asac** [comment]
Without a doubt, "Severity: Annoying" is pinpoint accurate.
I feel the same every time. In the end, I make a model (in SQL) with the static values and use a Join with that model to project the serializable value.

It's a low level workaround, but useful.

**Comment by flamber** [comment]
I'm not able to reproduce this, but I'm having difficulties understanding which database type and column type you're using, since it's not an `ENUM` column type, because you would then handle such remapping directly on the database instead of in Metabase.

Can you include field metadata by going to the URL `/api/field/123`, where 123 is the field ID that you can see in the URL, when going to Admin > Data Model > (db) > (table) > (field) :gear: > the browser URL should end with `.../123/general`
