### ISSUE TITLE
First created question not in Saved Questions inside Data Selector until page reload

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#25144]
Probably related to #24878 

tl;dr: We currently can't create a question from a freshly created question (if the saved question is the first one) unless we reload the app.

### To reproduce

1. Have no questions or models saved.
2. Create and save a question
3. Do not reload the page
4. `+New` › `Question`

You will *not* see `Saved Questions` as an option in the Data Selector. 

If you reload the page and retry a new question, you will see Saved Questions as an option.

**Comment by flamber** [comment]
Sounds like a repeat of #9027
