### ISSUE TITLE
our schema identifies fields by `id` alone, so the fields on virtual card tables get clobbered by the fields from concrete tables

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#25141]
**Describe the bug**
- the metadata on a Table coming from a `/api/table/card__123/query_metadata` GET may be specific to the given card if the card is a Model or based on a Model
- our normalizr `FieldSchema` identifies field objects via their `id` property, so fields shared between card__123 tables and concrete tables are seen as identical
- these fields clobber each other in our store, depending on the order of the requests we make for table metadata

**To Reproduce**
1. Created a question (Q1) based on the Products table.
2. Make it a Model and change the names of columns
3. Create a question (Q2) based on the model
4. Refresh the page
5. Using Redux dev tools, inspect how entities are stored and see that we store the Fields for Model tables in the same location as the Fields coming from concrete Tables.

**Expected behavior**
We should hold onto both fields somehow. Or at least hold onto the metadata that is unique to a given nested card table.

**Severity**
P2 -- it is the root cause for a number of the Models bugs we are seeing.

**Comment by flamber** [comment]
I'm guessing it's specifically #23019, but probably other Models issues too.
