### ISSUE TITLE
Changing X-axis breaks, when an invalid "X-axis scale" is defined can cause blank visualization or error

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#25156]
**Describe the bug**
Changing X-axis breaks, when an invalid "X-axis scale" is defined can cause blank visualization or error.

**To Reproduce**
1. Question > Sample > Reviews
2. Count grouped by CreatedAt:Year and Rating:Unbinned - visualize and change to Bar viz (triggers step 6, where Line doesn't)
![image](https://user-images.githubusercontent.com/1447303/187764215-48c68534-a2de-42c4-a458-f6434f86543a.png)
3. Visualization Settings > Data > change the X-axis, so Rating is first
![image](https://user-images.githubusercontent.com/1447303/187766472-95e9dc1c-d716-4b0f-b151-cce5b739e1c1.png)
4. Go to Axes > change "X-axis scale" to "Linear" (manually re-select it, so the setting gets saved)
![image](https://user-images.githubusercontent.com/1447303/187766615-10d87bf9-9b27-4628-b6dc-0fe57071ad3a.png)
5. Then back to Data > change the X-axis, so CreatedAt is first - now the visualization becomes blank with only the legend shown
![image](https://user-images.githubusercontent.com/1447303/187766688-138e0ec1-4857-4769-a8c4-b7ddb3bbdfd3.png)
6. Go to Display > enabled "Show values on data points" - now it shows an unhelpful error (Firefox `e.svg().select(...)[0][0] is null` and Chrome `Cannot read properties of null (reading 'getAttribute')`)
![image](https://user-images.githubusercontent.com/1447303/187766864-a33ae92c-c06e-4d9d-9c61-7cb49d2d2862.png)
7. Go to Axes > "X-axis scale", it is blank, but changing it to one of the available options will make the visualization work again
![image](https://user-images.githubusercontent.com/1447303/187767194-32e22203-b76f-463b-a005-57c2c9f106bb.png)
![image](https://user-images.githubusercontent.com/1447303/187767283-287f486b-57b0-4e39-837e-2c48a49d4101.png)

**Expected behavior**
When the scale option isn't available, then unset the current selection, so it defaults to the first available option.

**Information about your Metabase Installation:**
Tested 0.41.7 thru 0.44.2

**Comment by perivamsi** [comment]
Still a bug, can repro in master. Changing the x-axis from a non-timeseries column to numeric should reset the scale and pick `Timeseries` as the new scale.
