### ISSUE TITLE
Allow analysts to sync database schema

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#25151]
**Is your feature request related to a problem? Please describe.**

As an analyst using dbt, I create new schemas and tables frequently and want to be able to test them in Metabase. Right now, the only place to sync schema is in database settings that only admins can perform.  

**Describe the solution you'd like**

It would be very convenience to have this feature enabled for everyone (or select user groups, such as analysts) when browsing data. When browsing a database, there should be an option to sync schema for the entire database. When browsing a schema, there should be an option to sync the list of tables. When browsing a table, there should be an option to sync the list of fields. 

**Describe alternatives you've considered**

No other alternative aside from asking admin or having admin permission to sync schema for db. 

**How important is this feature to you?**

It's inconvenient even when you are an admin. For most analysts, they won't have admin permission and would require asking admins to sync the schema or wait an hour for auto-sync, and that would be very inconvenient when developing changes. 

**Additional context**
n/a

**Comment by flamber** [comment]
Very related to #13091 and #6799
