### ISSUE TITLE
start-of-week setting not changing when updating in the UI

### ISSUE THREAD

**Issue by sevaho** [metabase/metabase#25166]
**Describe the bug**

When updating the start-of-week I get the following:

![metabase-settings-not-working](https://user-images.githubusercontent.com/10941956/187889754-401d3447-28a1-44f6-ba72-7a1142756832.gif)

However the API call is done correctly.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

Server logs:

```
Sep 01 10:16:31 ip-10-20-5-143 metabase[11042]: 2022-09-01 10:16:31,381 DEBUG middleware.log :: PUT /api/setting/start-of-week 204 119.2 ms (4 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
Sep 01 10:16:31 ip-10-20-5-143 metabase[11042]: 2022-09-01 10:16:31,461 DEBUG middleware.log :: GET /api/setting 200 29.4 ms (4 DB calls) App DB connections: 1/7 Jetty threads: 4/50 (3 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
Sep 01 10:16:31 ip-10-20-5-143 metabase[11042]: 2022-09-01 10:16:31,464 DEBUG middleware.log :: GET /api/session/properties 200 23.8 ms (5 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
```

Browser logs

![image](https://user-images.githubusercontent.com/10941956/187890137-e76a9355-e4c0-4ec1-af0d-67330fcb6db0.png)

![image](https://user-images.githubusercontent.com/10941956/187890200-8c09de25-5e0a-45ff-926e-cd07d832879c.png)

**To Reproduce**

**Expected behavior**

That it updates correctly.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: Linux 5.17.1
- Your databases: Postgres 12
- Metabase version: 0.44.2
- Metabase hosting environment: AWS EC2
- Metabase internal database:  Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

This blocks the usage of Metabase entirely.

**Additional context**

**Comment by flamber** [comment]
Hi @sevaho 
You are defining it via environment variable, which is why it cannot be changed in the GUI: https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_start_of_week

**Comment by sevaho** [comment]
Hi @flamber Indeed I had had the following:

```
MB_START_OF_WEEK=Monday
```

which did not work as expected, thx!

**Comment by iethree** [comment]
maybe we should disable the GUI for items changed via environment variable?

**Comment by qwef** [comment]
@iethree It looks like we already do this, see:
<img width="678" alt="image" src="https://github.com/metabase/metabase/assets/34140255/d4866f78-8432-466f-b15e-2614ceeb5e48">
