### ISSUE TITLE
Clicking on "View details" for a table row when editing model metadata throws 404

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#25181]
**To Reproduce**

1. In a Model, `Edit Metadata`
2. To the left of any table row, click on "View Details"

We get the "We're a little lost" output.

![image](https://user-images.githubusercontent.com/380816/187967188-bd01b24a-8c18-4411-98b6-1249b77550eb.png)

**Comment by gusaiani** [comment]
@luizarakaki @mazameli,

should we not render this `View Details` button while editing Metadata?

Or what'd be a good behavior?

**Comment by gusaiani** [comment]
> but what would take to fix it?

No idea atm, I can timebox an hour or two to understand it better.

**Comment by luizarakaki** [comment]
Right. I think it would be nice to know what is going on. But if it is too complicated to solve, I think it is fine to just remove the feature when editing metadata.
