### ISSUE TITLE
Metabase reset setup or delete setup admin user

### ISSUE THREAD

**Issue by jonathanprior** [metabase/metabase#25186]
I am looking to reset Metabase after the setup page has been complete so that I can re-start the setup process.

I found https://github.com/metabase/metabase/issues/2826 for reference, which talked about a `metabase.db.h2.db` file, but the only files I find on my Docker instance of Metabase are:

![image](https://user-images.githubusercontent.com/103525107/187979650-1371fb57-e50f-44f5-8aa1-853a8ceeb2fc.png)

Is there any updated way of resetting the setup page?

Using Metabase version `0.44.1`

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Delete the application database (however you have configured it): https://www.metabase.com/docs/latest/installation-and-operation/configuring-application-database
