### ISSUE TITLE
Not able to get complete data in csv/excel while trying to download from embedded iframe 

### ISSUE THREAD

**Issue by dhavals23** [metabase/metabase#25201]
The issue over here is that from one of the widget if we try to download the data from metabase question it is give full downloaded result but the same when embedded in web gives half or less then half downloaded result.

Go to Sharing and embedding -> Embed this dashboard in app -> In preview tab try to download any dashboard data 

For Iframe -> embedded the dashboard in app -> click on download button next to it -> download as excel

**Expected behavior**
The data download from metabase and iframe should be same in excel or csv 

**Severity**
This bug is very annoying as the developer and user are not able to download same data in excel

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "5.11.0-1022-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.1 (Debian 14.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-04",
      "tag": "v0.44.0",
      "branch": "release-x.44.x",
      "hash": "d3700f5"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}
```

**Comment by paoliniluis** [comment]
Can you check in permissions if the users have different row limit for downloads?

**Comment by dhavals23** [comment]
Hi @paoliniluis there is not different row limit set for each users.
https://discourse.metabase.com/t/not-able-to-download-complete-data-in-excel-from-iframe/21710

**Comment by flamber** [comment]
Continuing in the forum topic
