### ISSUE TITLE
Custom column goes wrong when i use presto data

### ISSUE THREAD

**Issue by aCrazyOnion** [metabase/metabase#25200]
1、description
when i edit a question and use metabase's Custom column,it goes wrong.The metabase is the latest vesion v0.44.2 and the presto
version is 0.275.
2、how to reproduction:
![image](https://user-images.githubusercontent.com/40635300/188040305-fc0f4ec4-1518-4a89-8a79-67ae1ebd06fa.png)
![image](https://user-images.githubusercontent.com/40635300/188040334-c30697c8-d208-4c17-9e62-eef236134982.png)
![image](https://user-images.githubusercontent.com/40635300/188040349-14201c06-3279-4362-92e9-3ad5aef12798.png)
3、diagnostic Info
{ "browser-info": { "language": "zh-CN", "platform": "MacIntel", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36", "vendor": "Google Inc." }, "system-info": { "file.encoding": "UTF-8", "java.runtime.name": "OpenJDK Runtime Environment", "java.runtime.version": "11.0.16.1+1", "java.vendor": "Eclipse Adoptium", "java.vendor.url": "https://adoptium.net/", "java.version": "11.0.16.1", "java.vm.name": "OpenJDK 64-Bit Server VM", "java.vm.version": "11.0.16.1+1", "os.name": "Linux", "os.version": "5.10.76-linuxkit", "user.language": "en", "user.timezone": "GMT" }, "metabase-info": { "databases": [ "h2", "bigquery-cloud-sdk", "presto-jdbc", "presto" ], "hosting-env": "unknown", "application-database": "h2", "application-database-details": { "database": { "name": "H2", "version": "1.4.197 (2018-03-18)" }, "jdbc-driver": { "name": "H2 JDBC Driver", "version": "1.4.197 (2018-03-18)" } }, "run-mode": "prod", "version": { "date": "2022-08-31", "tag": "v0.44.2", "branch": "release-x.44.x", "hash": "8d9de8a" }, "settings": { "report-timezone": "Asia/Shanghai" } } }
4、stacktrace
{:type "query", :query {:source-table 1443, :expressions {:dd-sku ["case" [[[">" ["field" 18201 nil] ""] ["field" 18173 nil]]] nil]}}, :database 34, :parameters [], :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}}, :native {:query "SELECT \"source\".\"good_sn\" AS \"good_sn\", \"source\".\"pipeline_code\" AS \"pipeline_code\", \"source\".\"channel_code\" AS \"channel_code\", \"source\".\"platform_code\" AS \"platform_code\", \"source\".\"platform_name\" AS \"platform_name\", \"source\".\"goods_spu\" AS \"goods_spu\", \"source\".\"spu_title\" AS \"spu_title\", \"source\".\"leveli_category_name\" AS \"leveli_category_name\", \"source\".\"levelii_category_name\" AS \"levelii_category_name\", \"source\".\"leveliii_category_name\" AS \"leveliii_category_name\", \"source\".\"business_group\" AS \"business_group\", \"source\".\"business_division\" AS \"business_division\", \"source\".\"goods_cn_name\" AS \"goods_cn_name\", \"source\".\"main_image_url\" AS \"main_image_url\", \"source\".\"keyword\" AS \"keyword\", \"source\".\"lifecycle\" AS \"lifecycle\", \"source\".\"lifecycle_ch\" AS \"lifecycle_ch\", \"source\".\"market_price\" AS \"market_price\", \"source\".\"shop_price\" AS \"shop_price\", \"source\".\"rate\" AS \"rate\", \"source\".\"first_up_time\" AS \"first_up_time\", \"source\".\"currency_code\" AS \"currency_code\", \"source\".\"status\" AS \"status\", \"source\".\"status_ch\" AS \"status_ch\", \"source\".\"is_new_good\" AS \"is_new_good\", \"source\".\"is_inventory\" AS \"is_inventory\", \"source\".\"leveli_category_name_lang\" AS \"leveli_category_name_lang\", \"source\".\"levelii_category_name_lang\" AS \"levelii_category_name_lang\", \"source\".\"leveliii_category_name_lang\" AS \"leveliii_category_name_lang\", \"source\".\"is_history_new_good\" AS \"is_history_new_good\", \"source\".\"leveliii_category_pc_url\" AS \"leveliii_category_pc_url\", \"source\".\"leveliii_category_m_url\" AS \"leveliii_category_m_url\", \"source\".\"m_week_th\" AS \"m_week_th\", \"source\".\"pv\" AS \"pv\", \"source\".\"pv_hb\" AS \"pv_hb\", \"source\".\"uv\" AS \"uv\", \"source\".\"uv_hb\" AS \"uv_hb\", \"source\".\"trd_pay_user_cnt_1d_pct\" AS \"trd_pay_user_cnt_1d_pct\", \"source\".\"trd_pay_user_cnt_1d_pct_hb\" AS \"trd_pay_user_cnt_1d_pct_hb\", \"source\".\"trd_pay_ord_cnt_1d_pct\" AS \"trd_pay_ord_cnt_1d_pct\", \"source\".\"trd_pay_ord_qty_1d_pct\" AS \"trd_pay_ord_qty_1d_pct\", \"source\".\"trd_pay_ord_qty_1d_pct_hb\" AS \"trd_pay_ord_qty_1d_pct_hb\", \"source\".\"trd_pay_ord_amt_1d_pct\" AS \"trd_pay_ord_amt_1d_pct\", \"source\".\"trd_pay_ord_amt_1d_pct_hb\" AS \"trd_pay_ord_amt_1d_pct_hb\", \"source\".\"trd_pay_cur_ord_amt_1d_pct\" AS \"trd_pay_cur_ord_amt_1d_pct\", \"source\".\"trd_pay_ord_amt_1d_pctandscp\" AS \"trd_pay_ord_amt_1d_pctandscp\", \"source\".\"trd_pay_ord_qty_1d_pctandnet\" AS \"trd_pay_ord_qty_1d_pctandnet\", \"source\".\"trd_pay_ord_amt_1d_pctandnet\" AS \"trd_pay_ord_amt_1d_pctandnet\", \"source\".\"trd_ctr_ord_cnt_1d\" AS \"trd_ctr_ord_cnt_1d\", \"source\".\"trd_ctr_ord_user_cnt_1d\" AS \"trd_ctr_ord_user_cnt_1d\", \"source\".\"trd_crt_ord_amt_1d\" AS \"trd_crt_ord_amt_1d\", \"source\".\"sale_stk_qty_1d_qc\" AS \"sale_stk_qty_1d_qc\", \"source\".\"days_30d_hvstk\" AS \"days_30d_hvstk\", \"source\".\"sale_qty_net30d\" AS \"sale_qty_net30d\", \"source\".\"sale_loss_qty_net30d\" AS \"sale_loss_qty_net30d\", \"source\".\"sale_loss_amt_net30d\" AS \"sale_loss_amt_net30d\", \"source\".\"dd\" AS \"dd\", \"source\".\"dd_sku\" AS \"dd_sku\", \"source\".\"ds\" AS \"ds\", \"source\".\"dd-sku\" AS \"dd-sku\" FROM (SELECT \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"good_sn\" AS \"good_sn\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"pipeline_code\" AS \"pipeline_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"channel_code\" AS \"channel_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"platform_code\" AS \"platform_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"platform_name\" AS \"platform_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"goods_spu\" AS \"goods_spu\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"spu_title\" AS \"spu_title\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveli_category_name\" AS \"leveli_category_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"levelii_category_name\" AS \"levelii_category_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveliii_category_name\" AS \"leveliii_category_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"business_group\" AS \"business_group\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"business_division\" AS \"business_division\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"goods_cn_name\" AS \"goods_cn_name\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"main_image_url\" AS \"main_image_url\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"keyword\" AS \"keyword\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"lifecycle\" AS \"lifecycle\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"lifecycle_ch\" AS \"lifecycle_ch\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"market_price\" AS \"market_price\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"shop_price\" AS \"shop_price\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"rate\" AS \"rate\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"first_up_time\" AS \"first_up_time\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"currency_code\" AS \"currency_code\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"status\" AS \"status\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"status_ch\" AS \"status_ch\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"is_new_good\" AS \"is_new_good\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"is_inventory\" AS \"is_inventory\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveli_category_name_lang\" AS \"leveli_category_name_lang\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"levelii_category_name_lang\" AS \"levelii_category_name_lang\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveliii_category_name_lang\" AS \"leveliii_category_name_lang\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"is_history_new_good\" AS \"is_history_new_good\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveliii_category_pc_url\" AS \"leveliii_category_pc_url\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"leveliii_category_m_url\" AS \"leveliii_category_m_url\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"m_week_th\" AS \"m_week_th\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"pv\" AS \"pv\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"pv_hb\" AS \"pv_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"uv\" AS \"uv\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"uv_hb\" AS \"uv_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_user_cnt_1d_pct\" AS \"trd_pay_user_cnt_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_user_cnt_1d_pct_hb\" AS \"trd_pay_user_cnt_1d_pct_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_cnt_1d_pct\" AS \"trd_pay_ord_cnt_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_qty_1d_pct\" AS \"trd_pay_ord_qty_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_qty_1d_pct_hb\" AS \"trd_pay_ord_qty_1d_pct_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_amt_1d_pct\" AS \"trd_pay_ord_amt_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_amt_1d_pct_hb\" AS \"trd_pay_ord_amt_1d_pct_hb\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_cur_ord_amt_1d_pct\" AS \"trd_pay_cur_ord_amt_1d_pct\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_amt_1d_pctandscp\" AS \"trd_pay_ord_amt_1d_pctandscp\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_qty_1d_pctandnet\" AS \"trd_pay_ord_qty_1d_pctandnet\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_pay_ord_amt_1d_pctandnet\" AS \"trd_pay_ord_amt_1d_pctandnet\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_ctr_ord_cnt_1d\" AS \"trd_ctr_ord_cnt_1d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_ctr_ord_user_cnt_1d\" AS \"trd_ctr_ord_user_cnt_1d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"trd_crt_ord_amt_1d\" AS \"trd_crt_ord_amt_1d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"sale_stk_qty_1d_qc\" AS \"sale_stk_qty_1d_qc\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"days_30d_hvstk\" AS \"days_30d_hvstk\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"sale_qty_net30d\" AS \"sale_qty_net30d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"sale_loss_qty_net30d\" AS \"sale_loss_qty_net30d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"sale_loss_amt_net30d\" AS \"sale_loss_amt_net30d\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"dd\" AS \"dd\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"dd_sku\" AS \"dd_sku\", \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"ds\" AS \"ds\", CASE WHEN \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"good_sn\" > ? THEN \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\".\"dd\" END AS \"dd-sku\" FROM \"ads\".\"ads_sap_pipe_goods_plat_channel_analysis_df\") \"source\" LIMIT 1048575", :params ("")}, :status :failed, :class java.lang.RuntimeException, :stacktrace ["com.facebook.presto.jdbc.internal.client.StatementClientV1.requestFailedException(StatementClientV1.java:497)" "com.facebook.presto.jdbc.internal.client.StatementClientV1.advance(StatementClientV1.java:420)" "com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1743)" "com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:121)" "com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:272)" "com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:230)" "com.facebook.presto.jdbc.PrestoPreparedStatement.<init>(PrestoPreparedStatement.java:84)" "com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:142)" "com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:329)" "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:385)" "--> driver.presto_jdbc$fn__91712.invokeStatic(presto_jdbc.clj:393)" "driver.presto_jdbc$fn__91712.invoke(presto_jdbc.clj:389)" "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:335)" "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:332)" "driver.sql_jdbc.execute$statement_or_prepared_statement.invokeStatic(execute.clj:359)" "driver.sql_jdbc.execute$statement_or_prepared_statement.invoke(execute.clj:356)" "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)" "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)" "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)" "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)" "driver.sql_jdbc$fn__85194.invokeStatic(sql_jdbc.clj:54)" "driver.sql_jdbc$fn__85194.invoke(sql_jdbc.clj:52)" "query_processor.context$executef.invokeStatic(context.clj:59)" "query_processor.context$executef.invoke(context.clj:48)" "query_processor.context.default$default_runf.invokeStatic(default.clj:67)" "query_processor.context.default$default_runf.invoke(default.clj:65)" "query_processor.context$runf.invokeStatic(context.clj:45)" "query_processor.context$runf.invoke(context.clj:39)" "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)" "query_processor.reducible$identity_qp.invoke(reducible.clj:9)" "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___52607.invoke(cache.clj:220)" "query_processor.middleware.permissions$check_query_permissions$fn__48131.invoke(permissions.clj:109)" "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__51552.invoke(mbql_to_native.clj:23)" "query_processor$fn__54083$combined_post_process__54088$combined_post_process_STAR___54089.invoke(query_processor.clj:212)" "query_processor$fn__54083$combined_pre_process__54084$combined_pre_process_STAR___54085.invoke(query_processor.clj:209)" "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52528$fn__52533.invoke(resolve_database_and_driver.clj:35)" "driver$do_with_driver.invokeStatic(driver.clj:75)" "driver$do_with_driver.invoke(driver.clj:71)" "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52528.invoke(resolve_database_and_driver.clj:34)" "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48563.invoke(fetch_source_query.clj:346)" "query_processor.middleware.store$initialize_store$fn__48751$fn__48752.invoke(store.clj:11)" "query_processor.store$do_with_store.invokeStatic(store.clj:44)" "query_processor.store$do_with_store.invoke(store.clj:38)" "query_processor.middleware.store$initialize_store$fn__48751.invoke(store.clj:10)" "query_processor.middleware.normalize_query$normalize$fn__52800.invoke(normalize_query.clj:22)" "query_processor.middleware.constraints$add_default_userland_constraints$fn__49833.invoke(constraints.clj:53)" "query_processor.middleware.process_userland_query$process_userland_query$fn__52739.invoke(process_userland_query.clj:145)" "query_processor.middleware.catch_exceptions$catch_exceptions$fn__53111.invoke(catch_exceptions.clj:167)" "query_processor.reducible$async_qp$qp_STAR___44972$thunk__44974.invoke(reducible.clj:100)" "query_processor.reducible$async_qp$qp_STAR___44972.invoke(reducible.clj:106)" "query_processor.reducible$async_qp$qp_STAR___44972.invoke(reducible.clj:91)" "query_processor.reducible$sync_qp$qp_STAR___44983.doInvoke(reducible.clj:126)" "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)" "query_processor$process_userland_query.doInvoke(query_processor.clj:327)" "query_processor$fn__54130$process_query_and_save_execution_BANG___54139$fn__54142.invoke(query_processor.clj:342)" "query_processor$fn__54130$process_query_and_save_execution_BANG___54139.invoke(query_processor.clj:335)" "query_processor$fn__54174$process_query_and_save_with_max_results_constraints_BANG___54183$fn__54186.invoke(query_processor.clj:354)" "query_processor$fn__54174$process_query_and_save_with_max_results_constraints_BANG___54183.invoke(query_processor.clj:347)" "api.dataset$run_query_async$fn__68858.invoke(dataset.clj:69)" "query_processor.streaming$streaming_response_STAR_$fn__40090$fn__40091.invoke(streaming.clj:162)" "query_processor.streaming$streaming_response_STAR_$fn__40090.invoke(streaming.clj:161)" "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)" "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)" "async.streaming_response$do_f_async$task__19006.invoke(streaming_response.clj:84)"], :card_id nil, :context :ad-hoc, :error "Error executing query", :row_count 0, :running_time 0, :preprocessed

**Comment by flamber** [comment]
@aCrazyOnion I don't think we're going to be able to help you. I would recommend that you find someone who can help you debug what is going on by looking in the full stacktrace, as well as the log on the Presto server.
I don't know what type of column `good_sn` is, but the expressions does not look correct. Try converting it to SQL.
I cannot reproduce.
