### ISSUE TITLE
Metabase info "built on" date is off by a day

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2523]
Today is the 3rd, but both the Mac App 0.17.0 which I built earlier today and my local `lein ring server` instance say Metabase was built on the 2nd.

 ![screen shot 2016-05-03 at 2 05 14 pm](https://cloud.githubusercontent.com/assets/1455846/14998308/288f1d2c-1138-11e6-89fc-db3e61904003.png)
![screen shot 2016-05-03 at 2 05 10 pm](https://cloud.githubusercontent.com/assets/1455846/14998309/28a31b60-1138-11e6-8ed4-a02ad686a13f.png)

Obviously not a deal-breaker but it would be interesting to figure out why this bug is occurring at some point.

**Comment by agilliland** [comment]
`DATE=$(git log -1 --pretty=%ad --date=short)`

it uses the date of the last commit

**Comment by camsaul** [comment]
Probably makes more sense to do something like

```bash
DATE=$(date --iso-8601)
```

which gives us today's date in the same format

**Comment by agilliland** [comment]
Or we could just leave it.

**Comment by salsakran** [comment]
I'm neutral, and down with either option. 

The purpose of the timestamp is to let the end user know they have a recent version (or not in the event their administrator hasn't been updating). People outside the core team or administrators who follow us are unlikely to know which version is most recent, how far behind they are, etc. 

A one day swing or ambiguity in commit vs build time is completely acceptable for that purpose.

**Comment by camsaul** [comment]
I was just thinking it makes sense to have the "built on" date be accurate in case we want to differentiate between the official "0.17, built on May 2nd" vs "0.17, vs something like a custom "0.17, built on May 10th" done by a 3rd-party. Their own customizations wouldn't be reflected in the latest commit date if they some clever rebasing or didn't commit their own changes.

**Comment by salsakran** [comment]
I think the logic is sound, I just don't feel strongly. If you do, go for it

**Comment by camsaul** [comment]
Fixed by #2555
