### ISSUE TITLE
Saved Questions on Safari 7.0 are positioned very peculiarly 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2524]
This is with Mac App 0.17 from earlier today. 

![screen shot 2016-05-03 at 2 09 02 pm](https://cloud.githubusercontent.com/assets/1455846/14998422/b16716cc-1138-11e6-9d4d-7fdeef9601a2.png)

**Comment by camsaul** [comment]
This is happening on Safari on my box as well

![screen shot 2016-05-03 at 2 10 57 pm](https://cloud.githubusercontent.com/assets/1455846/14998461/e0a3ebe0-1138-11e6-9f20-d7701e1291db.png)

**Comment by camsaul** [comment]
@kdoh is on a newer version of Safari (9.0?) / OS X and isn't seeing these issues. So it might just be an older-version-of-Safari bug.

**Comment by kdoh** [comment]
Yeah I can't reproduce this in the mac app or safari (v 9.1). From what I can tell I think this is a Safari 7.0 specific issue.

**Comment by agilliland** [comment]
I'm not seeing it on my mac either, which is Safari 9.0

**Comment by agilliland** [comment]
@kdoh / @salsakran , can you decide if Safari 7.x is important for us to support.  if not then lets downgrade this to a limitation and remove it from 0.17.1

**Comment by kdoh** [comment]
Lets do that for sure. I want to dig into this more because if the rest of the app is working in Safari 7.x as it appears to be according to @camsaul then its fixable, but based on browser usage we don't need to make this a priority at the moment.

**Comment by mazameli** [comment]
This year, 0.05% of our sessions have been on Safari 7.x

**Comment by camsaul** [comment]
we still don't know whether is affects Safari 8.0, right? @salsakran are you still on Safari 8?

**Comment by salsakran** [comment]
I'm on 9. =(

**Comment by camsaul** [comment]
Do we know how many people are on 8 💻  🎱

**Comment by agilliland** [comment]
<img width="354" alt="screen shot 2016-05-03 at 2 33 45 pm" src="https://cloud.githubusercontent.com/assets/1987787/15025277/53ab3e9a-11ed-11e6-8efb-0b18c8685205.png">

**Comment by agilliland** [comment]
7.x + 8.x is approximately 5%, 6.x is oddly enough 3.5%, and everything else 92% is 9.x

**Comment by camsaul** [comment]
we should look at this on other browsers (like IE) and see if it's happening anywhere else. Obviously if it's only an older-Safari-only thing it's not a huge deal but right now we're not really sure what the scope of this bug is 😢

**Comment by kdoh** [comment]
When we were building this out I didn't encounter this specific issue in any of our supported browsers. Right now our definition of "browsers we support" is basically browsers that support flexbox. http://caniuse.com/#feat=flexbox

That's why I'm curious that you're seeing this issue but everything else in MB looks ok. If that's true then it's something unrelated to flexbox which was my gut guess after seeing this. Either way I'll assign this to me and take a look when possible, but I don't think this HAS to be part of 0.17.1

**Comment by camsaul** [comment]
ya. Besides being positioned "peculiarly" it works fine, so it's not a deal-breaker.

**Comment by camsaul** [comment]
I'm going to go ahead and close this because I'm probably the only person still on Mavericks these days, I need to upgrade my computer so this is more of a me problem than a Metabase problem
