### ISSUE TITLE
Support for API Key generation for the current user

### ISSUE THREAD

**Issue by paulinobruno** [metabase/metabase#25279]
**Describe the solution you'd like**
I would like to be able to generate an Api Key (or a Developer Token, if you like) to be able to invoke Metabase APIs. The solution I see is to have a zone in `Account settings` where I can provide a name and the system would create me an Api Key labeled with the provided name. Datadog calls it "Application Keys". Github calls it "Personal access tokens". The thing is: once I generate it, I can use it "as an actual session" (aka same permissions) of my user and interact with the APIs.

**Describe alternatives you've considered**
Maybe the Api Key the interface generates could be used in a Client Credentials way. In other words, for generating a Metabase Session Token, instead of running the following cURL:
```shell
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"username": "person@metabase.com", "password": "fakepassword"}' \
  http://localhost:3000/api/session
```
One could rather:
```shell
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"username": "person@metabase.com", "api_key": "e3364ee3-c9c6-40a8-a546-1328185d5510"}' \
  http://localhost:3000/api/session
```
And that in turn would generate the same response payload `{"id":"38f4939c-ad7f-4cbe-ae54-30946daf8593"}` containing the Session Id to be further used in the `X-Metabase-Session` header.

**How important is this feature to you?**
We work with OKRs and KPIs, and I implemented a ceremony to weekly collect and discuss the rolling measures with the team. The dynamic to understand how optimistic are the team members towards being successful in that Key Results.

So, every Monday, the first thing I do is to open every KR/KPI's Metabase Question link to manually collect the current measure and update in the spreadsheet. What I was willing to do is to automate this by using API calls. This would release me to increase my impact elsewhere.

**Additional context**
I use the same approach for collecting Engineering KPIs every Friday, but for this I automated with App Scripts in Google Spreadsheets. The issue is that the way we implemented Metabase internally, it requires to authenticate with SSO (which means I cannot generate a Session token through API call). What I do is to inspect the current Session Token while I navigate Metabase and use it for my scripts. But that doesn't scale, as every time my session expires (which happens often due to internal security policies), I need to go and generate another token.

**Comment by flamber** [comment]
@paulinobruno This is so close to #2699, so what do you think about closing it in favor of that issue? Then you can add a comment on that issue

**Comment by paulinobruno** [comment]
> @paulinobruno This is so close to #2699, so what do you think about closing it in favor of that issue? Then you can add a comment on that issue

Thank you for your input @flamber . In fact, I tried to query for any related issue, but there's a lot 😅. I just did it.

**Comment by paulinobruno** [comment]
Closed since it duplicates https://github.com/metabase/metabase/issues/2699.
