### ISSUE TITLE
Problem with line graphs when using text labels

### ISSUE THREAD

**Issue by ixeous** [metabase/metabase#2527]
If this is a bug report, please fill in the blanks:

*  I am using the Firefox/Safari browser.
*  My computer's OS is Linux or OSX.
*  I'm running Metabase JAR. 
*  My database is H2 for Metabase & MySQL for data
*  My Metabase version is 0.16.1.

Line graphs (and area graphs) are not drawn correctly when using text labels.  It draws the points in alphabetical order of the labels regardless of order of the table.  This is true even if the order along the axis is correctly ordered.  See the 2 screenshots attached to see the query and graphs.

![line-good](https://cloud.githubusercontent.com/assets/17748243/15004241/84d089be-1182-11e6-87b8-769df7b79704.png)

![line-bad](https://cloud.githubusercontent.com/assets/17748243/15004244/9020fc72-1182-11e6-8326-0cc8c9203925.png)

**Comment by salsakran** [comment]
In talking with @tlrobinson this is due to our graphing library DC.js sorting the points on a line graph internally when it plots them. Might be a bit tricky to fix, but we're looking into it.

**Comment by tlrobinson** [comment]
I think this is the relevant dc.js bug. https://github.com/dc-js/dc.js/issues/598

There are some workarounds I'll give a try.
