### ISSUE TITLE
Add ability to replace the lighthouse image with a custom image

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#25276]
While we can disable showing the lighthouse image, we cannot replace it with a custom image in the UI.

![lighthouse](https://user-images.githubusercontent.com/15974735/188760251-53c259e8-472a-4c4d-b338-2adc876273ac.png)

v1.44.2

**Comment by albertoperdomo** [comment]
This was implemented in https://github.com/metabase/metabase/issues/39246. It ships in Metabase v50.
