### ISSUE TITLE
Pie chart does not show the total value till hover (or a long time passes)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25272]
**Describe the bug**
When adding a pie chart to the dashboard, it won't show the total value till you hover over it (or you leave it be for many seconds)

**Logs**
NA

**To Reproduce**
1) new->question->orders->sum of total by product category
2) viz type->pie chart
3) add to dashboard, save dashboard and refresh, see the value not appearing
4) see the error, now hover over the pie chart

**Expected behavior**
see the total value from the beginning

**Screenshots**
![pieslow](https://user-images.githubusercontent.com/1711649/188754572-d025bcad-1578-43c6-9b5b-e0022ff21cf8.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Sample H2
- Metabase version: 1.44.2
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic?

**Additional context**
NA

**Comment by flamber** [comment]
For history #12506

**Comment by JesseSDevaney** [comment]
Cannot be reproduced:

https://github.com/metabase/metabase/assets/22608765/a0d98d6d-2efc-45e4-8862-5a8b24ecc706
