### ISSUE TITLE
Pulse not sending on 1st of Month

### ISSUE THREAD

**Issue by HelmiRifai** [metabase/metabase#2528]
Pulse was sent on April 30th
Pulse did **not** send on May 1st
Pulse was sent on May 2nd

*  I am using the Chrome browser.
*  My computer's OS is Mac.
*  I'm running Metabase Docker on AWS EC2 Instance. 
*  My database is Redshift.
*  My Metabase version is 0.16.1

Thanks

**Comment by agilliland** [comment]
This was fixed in https://github.com/metabase/metabase/pull/2427 and released as part of 0.17.0

**Comment by HelmiRifai** [comment]
Thanks!
