### ISSUE TITLE
Synchronized tables that were initially marked as `cruft` has their `initial_sync_status` as `incomplete`

### ISSUE THREAD

**Issue by Maiquu** [metabase/metabase#25291]
**Describe the bug**
Updating tables to be visible that were initially marked as `cruft` are not having their `initial_sync_status` property set to `completed` even after their post-update synchronization completes. Due to not being `completed`, these tables are grayed out in Data Model page, making it impossible to edit their fields. Might be related to #20863.

**To Reproduce**
1. Add a database that contains a table with `cruft` name (according to [crufty-table-patterns](https://github.com/metabase/metabase/blob/v0.44.2/src/metabase/sync/sync_metadata/tables.clj#L24))
2. Go to Admin Settings -> Data Model
3. Click Hide All and then Unhide All (Since its currently not possible to individually unhide `cruft` tables)
3.1. Or use  [`PUT /api/table`](https://www.metabase.com/docs/latest/api/table#put-apitable) endpoint to manually update `visibility_type`
4. Synchronization completes but `initial_sync_status` is still `incomplete`

**Expected behavior**
`initial_sync_status` should be `complete`.

**Information about your Metabase Installation:**

- Metabase version: 0.44.0

**Severity**
Annoying. Most likely it could be worked around via a full database sync since `initial_database_sync` becomes `completed` after quite a long time.

**Comment by flamber** [comment]
Basically the same as #24900. This is a backend issue.

**Comment by ranquild** [comment]
This is already fixed by https://github.com/metabase/metabase/pull/25061. @Maiquu the fix should become available in 0.44.3.

**Comment by Maiquu** [comment]
@ranquild Provided fix only works around the issue in front-end. I'm more interested in the backend fix of the issue since I'm polling `initial_database_sync` field of previously cruft tables as part of the automation process I'm working on. Triggering a full database schema sync seems to be the only way set `initial_database_sync` to `complete` at the moment.
