### ISSUE TITLE
Give admins ability to create a Getting Started guide for their users

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2530]
We've talked to lots of users who have a common problem: as easy as Metabase is to use to ask your own questions, it can be hard for users to understand what the data in a given database means. They don't know where to look to find the answers they want.

One possible feature we're exploring to address this problem is an admin-created Getting Started guide, which would provide a walkthrough for your users to highlight the most important data that you have inside Metabase, and give you the opportunity to explain caveats, gotchas, and the like.

This is a WIP prototype, but we'd love your feedback:
https://invis.io/6473X9SQK

@snarfed, we'd especially love to hear what you and Kurt think, since you have a larger team using MB, and we see this feature being especially helpful to teams that are trying to expand Metabase out to a broader set of users.

**Comment by snarfed** [comment]
cc @kurtosis-color

> as easy as Metabase is to use to ask your own questions, it can be hard for users to understand what the data in a given database means. They don't know where to look to find the answers they want.

yes! this is arguably the single hardest problem in this space, at least if you're trying to empower arbitrary people who haven't learned the schema beforehand, the hard way. i don't know what the ideal solution is, or if there even is one, but i love that you all are tackling it.

i like the invision sketch you linked, it's a great tool for onboarding. we'd definitely use it.

the bigger problem for us is helping our users learn the *schema* they know what data exists and which metrics they want, but they don't know how to map that mental model onto our complicated, mostly normalized OLAP schema. they're not sure which table to start in, how to join two or three tables away, what technical-sounding enum values mean, etc.

the standard approach here is to ETL into a data warehouse and have people go through dedicated analysts/data scientists.  we may bite the bullet and do the ETL eventually, but it's a big investment of both time and $, so we're trying to push it down the road as far as possible. as for empowering people and skipping the specialists, that may be the bigger open problem...?

regardless, this should definitely help! thank you!

**Comment by salsakran** [comment]
@snarfed  awesome! we'll be showing it around internally, but I think we can call this (almost) ready for implementation. we'll figure out when we can ship it and assign it a milestone soon!

**Comment by camsaul** [comment]
@metabase/core-developers is anyone working on the frontend for this feature?

**Comment by kdoh** [comment]
@camsaul Yeah this is happening in #3150

**Comment by camsaul** [comment]
Ok cool I'm trying to make sure the assignees list for this issue makes sense now that lewy isn't working on it anymore
