### ISSUE TITLE
Why metabase auto generate query to my db(mysql)?

### ISSUE THREAD

**Issue by Duanjax** [metabase/metabase#25303]
I finished the connection from metabase to my DB(Mysql), just find it will  automatically generate a query to db even I didn't start a query and IOPS got 100%?
![image](https://user-images.githubusercontent.com/86959085/189079343-b74213a6-7e0a-4188-9759-b9baffc0fa97.png)

![image](https://user-images.githubusercontent.com/86959085/189078450-3be480a7-93d8-4255-99a8-b0cfb30880f9.png)

When I killed the query, it will be created again!

Anyone encounter the same issue?

**Comment by Duanjax** [comment]
![image](https://user-images.githubusercontent.com/86959085/189080581-4e6e8355-a780-4c9c-bcf1-a685934c9b67.png)

**Comment by flamber** [comment]
Because Metabase syncs, fingerprints and scans the database: https://www.metabase.com/docs/latest/troubleshooting-guide/sync-fingerprint-scan
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by 2015WUJI01** [comment]
![image](https://github.com/metabase/metabase/assets/24295778/920072df-8ec4-45de-83cf-ca54a15804eb)
啊哈，遇到了相同的情况，按照 @flamber 的说法，把同步改为 Never 就好啦
