### ISSUE TITLE
Reset dashboard filter on click

### ISSUE THREAD

**Issue by a-meledin** [metabase/metabase#25306]
When there are several cards on dashboard, sometimes it is useful to have ability to reset one or several dashboard filters on click.

Example: 
- One card1 with overall statistics does not react on some filter, because this filter drills down card2 only. 
- When user returns to card1 and choses another summarized values to detail, specific filters on card2 should be flashed.

**Comment by flamber** [comment]
Hi @a-meledin 
I don't understand what you are looking for. Can you be a little more descriptive, use screenshots if it helps?
