### ISSUE TITLE
Missing dynamic columns from csv/xlsx export

### ISSUE THREAD

**Issue by Rmonik** [metabase/metabase#25302]
**Describe the bug**
We sometimes do some SQL magic to include a column only when a specific variable is filled in (see example below). This column is perfectly visible in Metabase, but is missing from the excel/csv export.

**Logs**
[metabaselogs.txt](https://github.com/metabase/metabase/files/9524576/metabaselogs.txt)

**To Reproduce**
1. Create a query where the inclusion of a column is dependent of the existence of an optional variable. Example: 
`SELECT [[field, -- {{myVariable}} is included in comment]] otherfield FROM table;
`
3. Run the query
4. View the results -> The field is included
5. Click the download button and download as CSV/Excel
6. The field is not included in the CSV/Excel

**Expected behavior**
The field is also included in CSV/Excel

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome v105
- Your operating system: MacOS 12.4
- Your databases: MySQL
- Metabase version: 0.44.2
- Metabase hosting environment: Local
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
Medium -- Our business uses these frequently, and can now no longer filter further via excel. This used to be working.

**Diagnostics** 

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.19.0-6-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Brussels"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-31",
      "tag": "v0.44.2",
      "branch": "release-x.44.x",
      "hash": "8d9de8a"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Comment by Rmonik** [comment]
Hi @flamber 
Correct, the square brackets need to be on the next line for this to work. I've tried the following, which works:
<img width="361" alt="Screenshot 2022-09-08 at 14 27 51" src="https://user-images.githubusercontent.com/16976971/189121843-5e95e397-af79-42b9-9b5d-43ca8f9f2a07.png">
<img width="407" alt="Screenshot 2022-09-08 at 14 27 45" src="https://user-images.githubusercontent.com/16976971/189121848-26ee227e-4169-4ecf-b9e4-d383d4d1ce59.png">
Interestingly, exporting these to CSV WILL include the third column, so I'm not sure why my other queries won't work.
This is the full query with which I encouter this issue. The issue is the "afstand" column.

```
select concat(users.id) as "ID", 
users.firstname, users.lastname, users.created as "registration date", users.email, users.phone, users.language, timestampdiff(year, candidates.dateofbirth, now()) as "age",
case 
    when candidates.statute = "F" then "flexi"
    when candidates.statute in ("S", "W") then "student"
    when candidates.statute in ("H", "Z") then "werkstudent"
    when candidates.statute in ("N", "L") then "regulier"
end as "statuut", 
    if(lastsuccessfulupdate >= now() - interval 2 month, studenthours, "") as "Student hours",
    profiles.ready as "contractready",
    users.seen as "laatst ingelogd",
    h.maxat as "laatste contr",
    h.cnt as "aantal contr"
    [[, round(min(st_distance_sphere(point(degrees(candidate_locations.longitude), degrees(candidate_locations.latitude)), 
    point(zipavg.lon, zipavg.lat))/1000),2) as "afstand" -- {{afstand}}
    ]],
    group_concat(
    case
        when candidate_locations.kind != "O" then null
        when candidate_locations.kind = "O" and candidate_locations.country != "BE" then "other"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 1000 and candidate_locations.zip < 1300 then "Brussels"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 1300 and candidate_locations.zip < 1500 then "Walloon Brabant"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 1500 and candidate_locations.zip < 2000 then "Flemish Brabant"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 2000 and candidate_locations.zip < 3000 then "Antwerp"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 3000 and candidate_locations.zip < 3500 then "Flemish Brabant"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 3500 and candidate_locations.zip < 4000 then "Limburg"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 4000 and candidate_locations.zip < 5000 then "Liege"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 5000 and candidate_locations.zip < 6000 then "Namur"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 6000 and candidate_locations.zip < 6600 then "Hainaut"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 6600 and candidate_locations.zip < 7000 then "Luxembourg"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 7000 and candidate_locations.zip < 8000 then "Hainaut"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 8000 and candidate_locations.zip < 9000 then "West Flanders"
        when candidate_locations.kind = "O" and candidate_locations.zip >= 9000 and candidate_locations.zip < 10000 then "East Flanders"
        else "other"
    end) as "Province official location"
        

from candidates


join users on candidates.id = users.id and users.country = "BE"
join profiles on profiles.user = users.id
left join candidates_be_studenthours on candidates_be_studenthours.candidate = candidates.id
join candidate_locations on candidate_locations.candidate = candidates.id
[[
    join candidate_licences on candidate_licences.candidate = candidates.id
    join server_translations stl on stl.table = "licences" and stl.id = candidate_licences.licence and stl.language = "nl_BE"
        and stl.value = {{licence}}
]]
left join (select candidate, max(hires.at) as maxat, count(hires.negotiation) as cnt from hires where status != "X" group by candidate) h on h.candidate = candidates.id 
[[join (select degrees(avg(longitude)) as lon, degrees(avg(latitude)) as lat from candidate_locations where zip = {{zip}} and country = "BE" and longitude != 0) zipavg]]
[[join candidate_functions on candidate_functions.candidate = candidates.id and candidate_functions.function = {{fct}} and candidate_functions.own >= {{fctscore}}]]


where true [[and canSMS = {{cansmsemail}} and canemail = {{cansmsemail}}]] 
[[and {{statute}}]]
[[and hires.at >= now() - interval {{nrofmonths}} month]]
[[and {{language}}]]
[[and timestampdiff(year, dateofbirth, now()) >= {{minage}}]]
[[and ({{afstand}} = 0 or st_distance_sphere(point(degrees(candidate_locations.longitude), degrees(candidate_locations.latitude)), 
    point(zipavg.lon, zipavg.lat))/1000 < {{afstand}})]]
group by candidates.id, users.id, profiles.id
```

**Comment by flamber** [comment]
@Rmonik It's not about the new line, but your example would exclude ` otherfield FROM table;` because the comment syntax will exclude anything on that specific line.

Include the output from `/api/card/123`, where 123 is the question ID. Redact sensitive parts. I'm mostly interested in the visualization_settings (historically #19889  #18382).

Try taking your query, make a new question with the query and setup the filters again. I have a feeling that it would work.

**Comment by Rmonik** [comment]
Hi @flamber ,
This is the content from the api/card/ endpoint:

`{"description":"Alle kandidaten, met optie om te filteren op afstand, statuut, laatste contract, etc","archived":false,"collection_position":null,"table_id":null,"result_metadata":[{"display_name":"ID","field_ref":["field","ID",{"base-type":"type/Text"}],"name":"ID","base_type":"type/Text","effective_type":"type/Text","semantic_type":"type/PK","fingerprint":null},{"display_name":"firstname","field_ref":["field","firstname",{"base-type":"type/Text"}],"name":"firstname","base_type":"type/Text","effective_type":"type/Text","semantic_type":"type/Name","fingerprint":{"global":{"distinct-count":1127,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":5.74}}}},{"display_name":"lastname","field_ref":["field","lastname",{"base-type":"type/Text"}],"name":"lastname","base_type":"type/Text","effective_type":"type/Text","semantic_type":"type/Name","fingerprint":{"global":{"distinct-count":1730,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.001,"average-length":7.992}}}},{"display_name":"registration date","field_ref":["field","registration date",{"base-type":"type/DateTimeWithLocalTZ"}],"name":"registration date","base_type":"type/DateTimeWithLocalTZ","effective_type":"type/DateTimeWithLocalTZ","semantic_type":null,"fingerprint":{"global":{"distinct-count":1982,"nil%":0.0},"type":{"type/DateTime":{"earliest":"2017-03-27T20:28:21+02:00","latest":"2017-05-26T21:38:20+02:00"}}}},{"display_name":"email","field_ref":["field","email",{"base-type":"type/Text"}],"name":"email","base_type":"type/Text","effective_type":"type/Text","semantic_type":null,"fingerprint":{"global":{"distinct-count":2000,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":1.0,"percent-state":0.0,"average-length":24.0485}}}},{"display_name":"phone","field_ref":["field","phone",{"base-type":"type/Text"}],"name":"phone","base_type":"type/Text","effective_type":"type/Text","semantic_type":null,"fingerprint":{"global":{"distinct-count":1974,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":15.85}}}},{"display_name":"language","field_ref":["field","language",{"base-type":"type/Text"}],"name":"language","base_type":"type/Text","effective_type":"type/Text","semantic_type":null,"fingerprint":{"global":{"distinct-count":3,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":5.0}}}},{"display_name":"age","field_ref":["field","age",{"base-type":"type/BigInteger"}],"name":"age","base_type":"type/BigInteger","effective_type":"type/BigInteger","semantic_type":null,"fingerprint":{"global":{"distinct-count":53,"nil%":0.0025},"type":{"type/Number":{"min":5.0,"q1":24.265776699029125,"q3":31.412937813713416,"max":121.0,"sd":8.350297125582097,"avg":29.309774436090226}}}},{"display_name":"statuut","field_ref":["field","statuut",{"base-type":"type/Text"}],"name":"statuut","base_type":"type/Text","effective_type":"type/Text","semantic_type":null,"fingerprint":{"global":{"distinct-count":4,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":7.08}}}},{"display_name":"Student hours","field_ref":["field","Student hours",{"base-type":"type/Text"}],"name":"Student hours","base_type":"type/Text","effective_type":"type/Text","semantic_type":null,"fingerprint":{"global":{"distinct-count":43,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":0.091}}}},{"display_name":"contractready","field_ref":["field","contractready",{"base-type":"type/Text"}],"name":"contractready","base_type":"type/Text","effective_type":"type/Text","semantic_type":null,"fingerprint":{"global":{"distinct-count":2,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":1.0}}}},{"display_name":"laatst ingelogd","field_ref":["field","laatst ingelogd",{"base-type":"type/DateTime"}],"name":"laatst ingelogd","base_type":"type/DateTime","effective_type":"type/DateTime","semantic_type":null,"fingerprint":{"global":{"distinct-count":977,"nil%":0.512},"type":{"type/DateTime":{"earliest":"2018-04-26T17:49:45+02:00","latest":"2022-09-08T14:29:00+02:00"}}}},{"display_name":"laatste contr","field_ref":["field","laatste contr",{"base-type":"type/Date"}],"name":"laatste contr","base_type":"type/Date","effective_type":"type/Date","semantic_type":null,"fingerprint":{"global":{"distinct-count":261,"nil%":0.8495},"type":{"type/DateTime":{"earliest":"2017-04-07T00:00:00+02:00","latest":"2022-12-08T00:00:00+01:00"}}}},{"display_name":"aantal contr","field_ref":["field","aantal contr",{"base-type":"type/BigInteger"}],"name":"aantal contr","base_type":"type/BigInteger","effective_type":"type/BigInteger","semantic_type":null,"fingerprint":{"global":{"distinct-count":65,"nil%":0.8495},"type":{"type/Number":{"min":1.0,"q1":1.7129769498460563,"q3":13.391164991562635,"max":557.0,"sd":44.22792246012045,"avg":17.591362126245848}}}},{"display_name":"Province official location","field_ref":["field","Province official location",{"base-type":"type/Text"}],"name":"Province official location","base_type":"type/Text","effective_type":"type/Text","semantic_type":null,"fingerprint":{"global":{"distinct-count":12,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":11.0055}}}}],"creator":{"email":"milan@nowjobs.com","first_name":"Milan","last_login":"2022-09-05T10:37:24","is_qbnewb":false,"is_superuser":true,"id":83,"last_name":"Claeys","date_joined":"2019-10-01T17:19:48","common_name":"Milan Claeys"},"can_write":true,"database_id":2,"enable_embedding":false,"collection_id":553,"query_type":"native","name":"CAN BE -- All candidates","last_query_start":"2022-09-08T12:29:55.615442Z","dashboard_count":0,"average_query_time":25023.3646,"creator_id":83,"moderation_reviews":[],"updated_at":"2022-09-08T14:30:52","made_public_by_id":null,"embedding_params":null,"cache_ttl":null,"dataset_query":{"native":{"query":"select concat(users.id) as \"ID\", \nusers.firstname, users.lastname, users.created as \"registration date\", users.email, users.phone, users.language, timestampdiff(year, candidates.dateofbirth, now()) as \"age\",\ncase \n    when candidates.statute = \"F\" then \"flexi\"\n    when candidates.statute in (\"S\", \"W\") then \"student\"\n    when candidates.statute in (\"H\", \"Z\") then \"werkstudent\"\n    when candidates.statute in (\"N\", \"L\") then \"regulier\"\nend as \"statuut\", \n    if(lastsuccessfulupdate >= now() - interval 2 month, studenthours, \"\") as \"Student hours\",\n    profiles.ready as \"contractready\",\n    users.seen as \"laatst ingelogd\",\n    h.maxat as \"laatste contr\",\n    h.cnt as \"aantal contr\"\n    [[, round(min(st_distance_sphere(point(degrees(candidate_locations.longitude), degrees(candidate_locations.latitude)), \n    point(zipavg.lon, zipavg.lat))/1000),2) as \"afstand\" -- {{afstand}}\n    ]],\n    group_concat(\n    case\n        when candidate_locations.kind != \"O\" then null\n        when candidate_locations.kind = \"O\" and candidate_locations.country != \"BE\" then \"other\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 1000 and candidate_locations.zip < 1300 then \"Brussels\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 1300 and candidate_locations.zip < 1500 then \"Walloon Brabant\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 1500 and candidate_locations.zip < 2000 then \"Flemish Brabant\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 2000 and candidate_locations.zip < 3000 then \"Antwerp\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 3000 and candidate_locations.zip < 3500 then \"Flemish Brabant\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 3500 and candidate_locations.zip < 4000 then \"Limburg\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 4000 and candidate_locations.zip < 5000 then \"Liege\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 5000 and candidate_locations.zip < 6000 then \"Namur\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 6000 and candidate_locations.zip < 6600 then \"Hainaut\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 6600 and candidate_locations.zip < 7000 then \"Luxembourg\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 7000 and candidate_locations.zip < 8000 then \"Hainaut\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 8000 and candidate_locations.zip < 9000 then \"West Flanders\"\n        when candidate_locations.kind = \"O\" and candidate_locations.zip >= 9000 and candidate_locations.zip < 10000 then \"East Flanders\"\n        else \"other\"\n    end) as \"Province official location\"\n        \n\nfrom candidates\n\n\njoin users on candidates.id = users.id and users.country = \"BE\"\njoin profiles on profiles.user = users.id\nleft join candidates_be_studenthours on candidates_be_studenthours.candidate = candidates.id\njoin candidate_locations on candidate_locations.candidate = candidates.id\n[[\n    join candidate_licences on candidate_licences.candidate = candidates.id\n    join server_translations stl on stl.table = \"licences\" and stl.id = candidate_licences.licence and stl.language = \"nl_BE\"\n        and stl.value = {{licence}}\n]]\nleft join (select candidate, max(hires.at) as maxat, count(hires.negotiation) as cnt from hires where status != \"X\" group by candidate) h on h.candidate = candidates.id \n[[join (select degrees(avg(longitude)) as lon, degrees(avg(latitude)) as lat from candidate_locations where zip = {{zip}} and country = \"BE\" and longitude != 0) zipavg]]\n[[join candidate_functions on candidate_functions.candidate = candidates.id and candidate_functions.function = {{fct}} and candidate_functions.own >= {{fctscore}}]]\n\n\nwhere true [[and canSMS = {{cansmsemail}} and canemail = {{cansmsemail}}]] \n[[and {{statute}}]]\n[[and hires.at >= now() - interval {{nrofmonths}} month]]\n[[and {{language}}]]\n[[and timestampdiff(year, dateofbirth, now()) >= {{minage}}]]\n[[and ({{afstand}} = 0 or st_distance_sphere(point(degrees(candidate_locations.longitude), degrees(candidate_locations.latitude)), \n    point(zipavg.lon, zipavg.lat))/1000 < {{afstand}})]]\ngroup by candidates.id, users.id, profiles.id","template-tags":{"afstand":{"id":"1ff278c6-1874-be7e-c9bd-c8f739f1f3f2","name":"afstand","display-name":"Afstand (km)","type":"number","required":false},"nrofmonths":{"id":"dcd9dba8-24e1-beab-a44a-4c1168708c69","name":"nrofmonths","display-name":"Contr in laatste x maand","type":"number"},"fct":{"id":"ca1c49af-642a-9e34-638b-436af3be859b","name":"fct","display-name":"Function NR","type":"number"},"licence":{"id":"d9c3af03-3b33-d19b-f7df-990002b56d63","name":"licence","display-name":"Licence","type":"text"},"fctscore":{"id":"c0f2d353-d18f-abab-b8b5-438a3a64ff99","name":"fctscore","display-name":"Function score","type":"number"},"cansmsemail":{"id":"f079f6d7-635b-eb29-64f1-2e67d0c89ed8","name":"cansmsemail","display-name":"Can SMS/Email","type":"text"},"minage":{"id":"7179ab45-f425-ce9d-eef2-3073991b1893","name":"minage","display-name":"Minimum age","type":"number","default":null},"language":{"id":"4d9da1e2-22d9-87dd-13c9-505e83d7d51e","name":"language","display-name":"Language","type":"dimension","dimension":["field",2193,null],"widget-type":"category"},"zip":{"id":"28e77322-aed3-bf8e-828a-1bab67da10e7","name":"zip","display-name":"Postcode","type":"number"},"statute":{"id":"2a4ddd17-e1a9-8502-c629-277ed47ce507","name":"statute","display-name":"Statuut","type":"dimension","dimension":["field",148,null],"widget-type":"category"}}},"type":"native","database":2},"id":1273,"parameter_mappings":null,"display":"table","entity_id":null,"collection_preview":true,"last-edit-info":{"id":83,"email":"milan@nowjobs.com","first_name":"Milan","last_name":"Claeys","timestamp":"2022-08-03T12:44:34Z"},"visualization_settings":{"table.pivot_column":"language","table.cell_column":"id","table.columns":[{"name":"ID","fieldRef":["field","ID",{"base-type":"type/Text"}],"enabled":true},{"name":"firstname","fieldRef":["field-literal","firstname","type/Text"],"enabled":true},{"name":"lastname","fieldRef":["field-literal","lastname","type/Text"],"enabled":true},{"name":"email","fieldRef":["field-literal","email","type/Text"],"enabled":true},{"name":"phone","fieldRef":["field-literal","phone","type/Text"],"enabled":true},{"name":"language","fieldRef":["field-literal","language","type/Text"],"enabled":true},{"name":"age","fieldRef":["field-literal","age","type/BigInteger"],"enabled":true},{"name":"statuut","fieldRef":["field-literal","statuut","type/Text"],"enabled":true},{"name":"Student hours","fieldRef":["field-literal","Student hours","type/Text"],"enabled":true},{"name":"laatste contr","fieldRef":["field-literal","laatste contr","type/Date"],"enabled":true},{"name":"firstname","fieldRef":["field","firstname",{"base-type":"type/Text"}],"enabled":true},{"name":"aantal contr","fieldRef":["field-literal","aantal contr","type/BigInteger"],"enabled":true},{"name":"lastname","fieldRef":["field","lastname",{"base-type":"type/Text"}],"enabled":true},{"name":"email","fieldRef":["field","email",{"base-type":"type/Text"}],"enabled":true},{"name":"phone","fieldRef":["field","phone",{"base-type":"type/Text"}],"enabled":true},{"name":"language","fieldRef":["field","language",{"base-type":"type/Text"}],"enabled":true},{"name":"age","fieldRef":["field","age",{"base-type":"type/BigInteger"}],"enabled":true},{"name":"statuut","fieldRef":["field","statuut",{"base-type":"type/Text"}],"enabled":true},{"name":"Student hours","fieldRef":["field","Student hours",{"base-type":"type/Text"}],"enabled":true},{"name":"contractready","fieldRef":["field","contractready",{"base-type":"type/Text"}],"enabled":true},{"name":"laatst ingelogd","fieldRef":["field","laatst ingelogd",{"base-type":"type/DateTime"}],"enabled":true},{"name":"laatste contr","fieldRef":["field","laatste contr",{"base-type":"type/Date"}],"enabled":true},{"name":"aantal contr","fieldRef":["field","aantal contr",{"base-type":"type/BigInteger"}],"enabled":true},{"name":"Province official location","fieldRef":["field","Province official location",{"base-type":"type/Text"}],"enabled":true},{"name":"registration date","fieldRef":["field","registration date",{"base-type":"type/DateTimeWithLocalTZ"}],"enabled":true}],"column_settings":{"[\"name\",\"laatste contr\"]":{"time_enabled":null}}},"collection":{"authority_level":null,"description":"In this top level folder, you'll find general useful queries that will answer most questions already. If you require more specific information, you may find them in the subfolders for your team.","archived":false,"slug":"belgium","color":"#509EE3","name":"Belgium","personal_owner_id":null,"id":553,"entity_id":null,"location":"/","namespace":null},"parameters":null,"dataset":false,"created_at":"2020-02-05T15:03:31","public_uuid":null}`

I'll try to copy the query in a minute, but it's fairly extensive so it may take a while.

**Comment by flamber** [comment]
I can see you have a lot of visualization_settings from pre-38 versions mixed together with newer field dimensions. I'm guessing that some of that is causing the problems, but I've not been able to reproduce.

Try opening your browser developer console and run this - adjust the URL to your Metabase instance (I can see it's question ID 1273).
```
await fetch("https://metabase.example.com/api/card/1273", {
    "credentials": "include",
    "headers": { "Content-Type": "application/json" },
    "body": "{\"visualization_settings\":{}}",
    "method": "PUT",
    "mode": "cors"
});
```
This will clear the visualization settings for the question, because there's no way to do it in the app anymore (#13968).
After running the command, then you need to refresh the browser on the question to see changes.
If you have made some customization that you wanted to keep, then you need to redo those again.

**Comment by k-popov** [comment]
Simple script to reset visualization settings for all cards. Works sequentially so not too fast but should work as soon as this action is only required once.
```python
#!/usr/bin/env python3

import requests
import json
import os
import sys

mb_url = os.environ['MB_URL']
mb_user = os.environ['MB_USER']
mb_pass = os.environ['MB_PASS']

session = requests.Session()
print('Getting session token', file=sys.stderr)
token = session.post(
    f'{mb_url}/api/session',
    headers = {'Content-Type': 'application/json'},
    data=json.dumps({'username': mb_user, 'password': mb_pass})
    )
token.raise_for_status()

print('Getting cards list', file=sys.stderr)
cards_list = session.get(
    f'{mb_url}/api/card/',
    headers={'X-Metabase-Session': token.json()['id'], 'Content-Type': 'application/json'}
    )

for card in cards_list.json():
    print(f'Processing card {card["id"]}', file=sys.stderr)
    vis_reset = session.put(
        f'{mb_url}/api/card/{card["id"]}',
        headers={'X-Metabase-Session': token.json()['id'], 'Content-Type': 'application/json'},
        data=json.dumps({'visualization_settings': {}})
        )
    vis_reset.raise_for_status()
    print(f'{card["id"]} - OK')
    print(f'{card["id"]} - OK', file=sys.stderr)
```
