### ISSUE TITLE
Stacked bar graph not rendered correctly when posted to Slack

### ISSUE THREAD

**Issue by SimonSG123** [metabase/metabase#25321]
**Describe the bug**
We added a stacked bar graph to a dashboard which we publish to Slack daily via a subscription. When posted to Slack, the stacked bar graph gets rendered as a grouped bar graph instead, which defeats the purpose of the visualization.

**Logs**
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:03-06:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 13.8 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (4 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:03-06:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 44.2 ms (5 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:04-06:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 43.3 ms (2 DB calls) App DB connections: 3/15 Jetty threads: 7/50 (1 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:04-06:00 DEBUG metabase.server.middleware.log GET /api/database 200 38.7 ms (3 DB calls) App DB connections: 3/15 Jetty threads: 6/50 (1 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:04-06:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 40.0 ms (1 DB calls) App DB connections: 3/15 Jetty threads: 6/50 (1 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:04-06:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 77.1 ms (18 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:04-06:00 DEBUG metabase.server.middleware.log GET /api/dashboard/23 200 113.7 ms (15 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (4 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:04-06:00 DEBUG metabase.server.middleware.log GET /api/collection/33 200 3.0 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (5 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:04-06:00 DEBUG metabase.server.middleware.log GET /api/collection/29 200 10.3 ms (3 DB calls) App DB connections: 8/15 Jetty threads: 5/50 (4 idle, 0 queued) (103 total active threads) Queries in flight: 4 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:06-06:00 DEBUG metabase.server.middleware.log GET /api/pulse/form_input 200 1.1 ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (108 total active threads) Queries in flight: 6 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:06-06:00 INFO metabase.integrations.slack Refreshing slack channels and usernames.
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:06-06:00 DEBUG metabase.server.middleware.log GET /api/user 200 20.6 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (5 idle, 0 queued) (109 total active threads) Queries in flight: 6 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:06-06:00 DEBUG metabase.server.middleware.log GET /api/pulse 200 20.1 ms (7 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (110 total active threads) Queries in flight: 6 (0 queued)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:10-06:00 DEBUG metabase.server.middleware.log POST /api/dashboard/23/dashcard/133/card/195/query 202 [ASYNC: completed] 6.4 s (16 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (6 idle, 0 queued) (113 total active threads) Queries in flight: 5 (0 queued); postgres DB 2 connections: 1/1 (0 threads blocked)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:10-06:00 DEBUG metabase.server.middleware.log POST /api/dashboard/23/dashcard/143/card/216/query 202 [ASYNC: completed] 6.6 s (15 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 4 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:11-06:00 DEBUG metabase.server.middleware.log POST /api/dashboard/23/dashcard/134/card/193/query 202 [ASYNC: completed] 6.8 s (16 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 3 (0 queued); postgres DB 2 connections: 3/3 (1 threads blocked)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:11-06:00 DEBUG metabase.server.middleware.log POST /api/dashboard/23/dashcard/132/card/207/query 202 [ASYNC: completed] 7.0 s (15 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 2 (0 queued); postgres DB 2 connections: 1/1 (2 threads blocked)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:11-06:00 DEBUG metabase.server.middleware.log POST /api/dashboard/23/dashcard/142/card/211/query 202 [ASYNC: completed] 7.1 s (15 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 1 (0 queued); postgres DB 2 connections: 1/1 (1 threads blocked)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:11-06:00 DEBUG metabase.server.middleware.log POST /api/dashboard/23/dashcard/135/card/201/query 202 [ASYNC: completed] 7.1 s (15 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 4/4 (1 threads blocked)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:22-06:00 DEBUG metabase.server.middleware.log POST /api/pulse/test 200 12.2 s (121 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (5 idle, 0 queued) (113 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/7 (0 threads blocked)
[e128388c-4204-4586-a0f0-9bdea1cfd64d] 2022-09-08T18:51:48-06:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 1.5 ms (1 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (6 idle, 0 queued) (113 total active threads) Queries in flight: 0 (0 queued)

**To Reproduce**
1. Created a stacked bar graph visualization
2. Add it to a dashboard
3. Create a subscription to post to Slack
4. Click on "Send to Slack now" button

**Expected behavior**
Stacked bar graph gets rendered as such when posted to Slack.

**Screenshots**

<img width="1189" alt="Screen Shot 2022-09-08 at 6 43 11 PM" src="https://user-images.githubusercontent.com/98771369/189250566-582e2e05-ad69-4033-9912-ac4e881b9810.png">
<img width="1004" alt="Screen Shot 2022-09-08 at 6 43 37 PM" src="https://user-images.githubusercontent.com/98771369/189250564-6f0075d8-5b3b-4499-9fc6-69ab359e70cf.png">

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "5.13.0-1029-aws",
    "user.language": "en",
    "user.timezone": "US/Mountain"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-16",
      "tag": "v0.44.1",
      "branch": "release-x.44.x",
      "hash": "112f5aa"
    },
    "settings": {
      "report-timezone": "US/Mountain"
    }
  }
}

**Severity**
Being able to post dashboards directly to Slack where our entire company can see them is essential to us since we do not want to give everyone access to Metabase and make things more complicated for them. It's a dashboard intended for people that are not necessarily data people or even "computer"/office people. The graphic makes no sense when grouped instead of stacked, so the dashboard becomes much less valuable.

**Additional context**
The same issue occurs when test sending an email subscription.

**Comment by paoliniluis** [comment]
Hi, you're seeing https://github.com/metabase/metabase/issues/20752. We are working on this for 45
