### ISSUE TITLE
v.0.44.2 variables in text cards, how to use?

### ISSUE THREAD

**Issue by a-meledin** [metabase/metabase#25357]
When adding text card on a dashboard, there is a help message:
![image](https://user-images.githubusercontent.com/98175818/189674836-d6fc9823-1d55-4728-aff3-8e84ce5ebab2.png)

I've tried to put filter variable, saved question formatted as a Number visual... nothing work. Is there any documentation on the feature? 

UPDATED:
1. Found https://github.com/metabase/metabase/issues/23543 and https://github.com/metabase/metabase/pull/24491 and recognized that it is required to link the variable to a filter. Works, but no doc on the feature still.
2. And how to display saved question values? Referenced here https://github.com/metabase/metabase/issues/9080, but still no docs.

**Problem:** We have a lot of pre-calculated statistical data and I want to show user when this data was last updated. The idea was to display text box like "Data 1 updated on <date/time>; Data 2 updated on <date/time>". Now I'm using table visual for this, but it takes too much space on the dashboard.

**Comment by flamber** [comment]
Have a look here: https://www.metabase.com/docs/latest/dashboards/introduction#including-variables-in-text-cards
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
