### ISSUE TITLE
Question Mark ? char breaking syntax when using variable in Custom SQL

### ISSUE THREAD

**Issue by ashston3** [metabase/metabase#25351]
**Describe the bug**
When using variable in SQL statement which contains question character (**?**) gives error as it does not parse it correctelly. When removing (**?**) from sql statement works as expected (although forces to change the query). Not a big deal.

Just in case, query does not make sense at all, just maintained the essentials.

Query with (**?**) : breaks (see error bellow)

```
SELECT distinct 
    SUM(
        CASE WHEN 
            url not like 'http//...site..?query=&%' --> here is the (**?**) char
        END 
    ) OVER (PARTITION BY id, DATE(date_field)) as flag_user_searched
FROM schema.table
WHERE 
   DATE(date_field) >= [[ {{date_from}}--]] DATE(DATE_TRUNC('month', NOW())) 

```

Query with out (**?**) : Works

```
SELECT distinct 
    SUM(
        CASE WHEN 
            url not like 'http//...site..%query=&%' --> change it to wildcard
        END 
    ) OVER (PARTITION BY id, DATE(date_field)) as flag_user_searched
FROM schema.table
WHERE 
   DATE(date_field) >= [[ {{date_from}}--]] DATE(DATE_TRUNC('month', NOW())) 

```

**Logs**
Console

```
"ex-data": {
                "sql": "-- Metabase:: userID: 112 queryType: native queryHash: e0e3eca84558fee83fea9982eeaf9ba93f92dea9418729a71e8694f0eb93ffc0\nSELECT distinct \n    SUM(\n        CASE WHEN \n            url not like 'http//...site..date '2022-09-10'query=&%'\n        END \n    ) OVER (PARTITION BY id, DATE(date_field)) as flag_user_searched\nFROM schema.table\nWHERE \n   DATE(date_field) >=  ?-- DATE(DATE_TRUNC('month', NOW()))",
                "params": null,
                "type": "invalid-query"
            }
```

.
To make it legible it replaces the variable where the **?** is.

`url not like 'http//...site..date '2022-09-10'query=&`

**To Reproduce**
1. Create a new sql question
2. Add the snippet replacing  schema, table, fields of your environment (any will suffice)
5. See error

**Expected behaviour**
Should parse correctly.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Safari Version 15.6.1 (17613.3.9.1.16)
- MacOS Monterrey Version 12.5.1 
- Metabase version: v0.40.5
- Metabase hosting environment: AWS Cloud
- Metabase internal database: Athena

**Severity**
Annoying, took time to figure it out. Still do not know how people can get notice if they face the same issue as error **description is too generic**. Please do change the title of this issue to what ever you consider be more helpful.

**Additional context**
really cool so far!

**Comment by flamber** [comment]
You need to upgrade immediately: https://github.com/metabase/metabase/security/advisories/GHSA-vmm4-cwrm-38rj
Make sure you're using a compatible Athena driver version.
Duplicate of #10257
