### ISSUE TITLE
Cannot use filter relative interval on breakout fields

### ISSUE THREAD

**Issue by MerzDaniel** [metabase/metabase#25378]
**Describe the bug**
I set up a line diagram with monthly numbers. When trying to filter out the current month I see an error

**Logs**
```
Input to update-field-options does not match schema: [0;33m [(named (named (not (some-matching-condition? a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :expression, :field") arg0) nil nil nil] [0m 
```

**To Reproduce**
- set up a line diagram with monthly numbers (the data from the table already is by month)
- filter out the current month (Filter -> Relative Dates -> Last X months starting from last 1 month)

**Expected behavior**
Current month should not be shown 

**Screenshots**
![image](https://user-images.githubusercontent.com/16895137/189873078-0f876e77-2971-4c27-8c8d-ecd39f899c7f.png)

![image](https://user-images.githubusercontent.com/16895137/189872267-b28cdfae-5083-4160-814e-fa42c41ef2a6.png)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.4.188+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-31",
      "tag": "v0.44.2",
      "branch": "release-x.44.x",
      "hash": "8d9de8a"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
Annoying. I can circumvent by converting to SQL

**Comment by flamber** [comment]
@MerzDaniel Just move your filter to before the aggregation, click the little purple filter icon below the join section
![image](https://user-images.githubusercontent.com/1447303/189877770-759c6f48-3ae0-4948-92c2-30c695bda663.png)

**Comment by WiNloSt** [comment]
Looks like a BE issue to me.

Some tests:
1. **Products** summarized **count** by **Create At: Month**. Filter **Created At** previous 12 months starting 3 months ago. ❌ doesn't work
2. **Products** summarized **count** by **Create At: Month**. Filter **Created At** previous 12 weeks starting 3 weeks ago. ✅ works
3. **Products** summarized **count** by **Create At: Month**. Filter **Created At** previous 12 months. ✅ works
4. **Products** summarized **count** by **Create At: Week**. Filter **Created At** previous 12 months starting 3 months ago. ✅ works
5. **Products** summarized **count** by **Create At: Week**. Filter **Created At** previous 12 weeks starting 3 weeks ago. ❌ doesn't work
6. **Products** summarized **count** by **Create At: Week**. Filter **Created At** previous 12 weeks. ✅ works

From the observation, it seems like if we filter the same time unit as the input data plus **starting from** filter, it will not work. It will only work if we filter different time unit than the input data or we don't include the **starting from** filter
