### ISSUE TITLE
metabot should fall back to showing card with closest name when no matches are found

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2538]
If no matching cards are found (ostensibly due to a typo) find the card whose name most closely matches what was typed and show that. E.g. if I type `metabase show ordrs` it can show me my `orders` card.

We can do this by comparing their [Levenshtein distances](https://en.wikipedia.org/wiki/Levenshtein_distance). I suppose we'd have to fetch the card names and do this clojure-side (Postgres supports it but only as an extension). 

The algo is actually fairly easy to do [here's a wacky one I did in C a while back](https://github.com/camsaul/bird-kit-x/blob/master/XPlatform/Categories/NSString%2BX.m#L21-L71).

**Comment by salsakran** [comment]
We can also use a "keyboard distance" measure like http://search.cpan.org/~krburton/String-KeyboardDistance-1.01/KeyboardDistance.pm

**Comment by camsaul** [comment]
that sounds even better 👍  🎹 📏

**Comment by salsakran** [comment]
and I'd probably cap it at some max distance, and start relatively low there. I wouldn't want something like
`metabot show ball` to end up match a card named `gaol`

**Comment by flamber** [comment]
Closing as MetaBot is deprecated as of v0.42 #19435
