### ISSUE TITLE
 Metabase map of the world, the mapping relationship between country and abbreviation

### ISSUE THREAD

**Issue by zys2017** [metabase/metabase#25381]
Hi! Where can i find the mapping relationship between country and abbreviation when visualizing data with maps? 
For example, It seems that UK does not represent Britain.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Use `GB`: https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/world.json
