### ISSUE TITLE
Upgrade google-cloud-bigquery dependency to 2.x

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25385]
**Is your feature request related to a problem? Please describe.**
We're still running the old version of the driver, where the new version supports new features like Google BI engine (in memory analytics). This new version has breaking changes, so there might be a lot of work for refactoring

**Describe the solution you'd like**
Upgrade the driver to the latest version

**Describe alternatives you've considered**
NA

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by sockpapi** [comment]
any updates on this?

**Comment by markbastian** [comment]
This has been updated to [2.23.2](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery-cloud-sdk/deps.edn#L6). All tests are passing. Assuming it soaks in OK, we should be good to go.

**Comment by paoliniluis** [comment]
yup!
