### ISSUE TITLE
Interval and DataAdd functions not working as expected on Metabase

### ISSUE THREAD

**Issue by Shaunom19** [metabase/metabase#25430]
Hi i'm trying to add 60 years to members Date of Birth field so that i can get to their year of retirement. I tried date_add (dob, INTERVAL 60 YEAR) as retirement_date but it didn't work. 

![image](https://user-images.githubusercontent.com/113582881/190338069-5e3a7b90-bf3b-474c-bfbe-446b4f1266c0.png)

Also tried what you can see in the attached image but there is an error message that pops up.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You cannot use `interval()` on a Custom Column like that, it's a boolean function used for filtering.
You are looking for #19274 - upvote by clicking :+1: on the first post
