### ISSUE TITLE
Blank Model metadata sidebar

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#25437]
**Describe the bug**
The model metadata sidebar can sometimes show up as blank. Here's a related slack thread: https://metaboat.slack.com/archives/C03SHMZ266R/p1663183843362779

Under the hood, it is because we are passing the wrong `mode` object to the `Visualization` component.

**To Reproduce**
1. Open up the Orders table, save as a Question, then convert it into a Model
2. Open up yer dev tools and look at console warnings
3. Edit the Model's metadata
4. See that there are many console warnings triggered:

![Screen Shot 2022-09-15 at 1 54 58 PM](https://user-images.githubusercontent.com/13057258/190476487-4c9af667-a05c-40dd-b108-ae2e4d2cce21.png)

**Expected behavior**
This warning shouldn't happen. And the sidebar shouldn't show up blank (note: this doesn't happen in dev)

**Severity**
P2

**Comment by flamber** [comment]
Basically the same as #22521 step 6+.
