### ISSUE TITLE
The Model notebook query editor shows the model itself as the data source

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#25458]
**Describe the bug**
When you go to edit the query definition for a notebook mode model, the first step (the one labeled "Data") shows the model's name instead of the underlying table. Additionally, you cannot see any columns that were hidden as part of the original creation of the question.

**To Reproduce**
1. Create a question based on the Orders table
2. Hide the Total column
3. Save as Q1
4. Convert Q1 into a model
5. Edit the model's query definition
6. Observe that "Q1" shows up in the first step and that you cannot re-add the Total column via the picker

**Expected behavior**
You should see what you saw when you created the question originally -- the Orders table

**Screenshots**
![Screen Shot 2022-09-16 at 9 39 01 AM](https://user-images.githubusercontent.com/13057258/190652225-86585189-ee6e-47cb-a2de-50496ea8f99b.png)

**Severity**
P2/regression since it prevents you from properly reediting the model's query.

**Additional context**
This was caused by https://github.com/metabase/metabase/pull/25109 so it is only on `master` currently. Questions that have been converted to models are a bit special in that we frequently treat them as if they were already being used in a new query with the model itself as the source table id (eg a source table id like "card__123"). This makes lots of things easier to deal with, but the downside is that we can't forget to treat Model questions like they _aren't_ models when we are editing its query, otherwise we hit confusing bugs like this.

**Comment by flamber** [comment]
Sounds related to #20624

**Comment by daltojohnso** [comment]
That bug seems pretty different to me. This one is a direct consequence of a recent change (https://github.com/metabase/metabase/pull/25109)
