### ISSUE TITLE
Simplify API use for database permissions (or use sane defaults)

### ISSUE THREAD

**Issue by Drugoy** [metabase/metabase#25471]
**Is your feature request related to a problem? Please describe.**
The problem: we programmatically create new database connections, but these connections are permitted to be used by ALL USERS in metabase and there's no easy way to change these permissions programmatically, have to resort to manual labor to change them.

**Describe the solution you'd like**
Change default behavior somehow: we would like new database connections to be restricted for 'All Users' built-in special group that every metabase user is always part of.

**Describe alternatives you've considered**
tl;dr: simplify API down to a very simple request to solve the problem.

<a href="https://www.metabase.com/docs/latest/api/permissions#put-apipermissionsgraph">The docs on metabase API</a> basically tell to send a `PUT` request to `/api/permissions/graph` with... some map as a body.
To get this map - one needs to first send a `GET` request to the same endpoint, capture response and make necessary modifications to it and then send it as body in above mentioned `PUT`.
The graph grows longer and longer if one's metabase keeps getting new and new connections added to it and every time we need to modify just some tiny part of it.
The problem is that it is not an easy task to automate, especially given that docs don't give any examples.
I've tried just inspecting the client query's body when I do the same modification via web UI, but failed to decipher the contents to figure out what needs to be modified. I made a guess + tried to reduce the body just down to the part I make my change in - this results into the server responding with an error (that I don't even bother to paste here, as such use is not documented and thus not permitted).

**How important is this feature to you?**
Very important, because if someone running the automatics forgets to do the manual part afterwards - we basically have a data leak.

**Additional context**
The docs lack examples on usage.

**Comment by Drugoy** [comment]
Just figured out an even simpler solution!
Just add an optional field for `POST /api/database` API that'd allow specifying User Group IDs for whom to permit access for the newly created database connection.

**Comment by Drugoy** [comment]
@paoliniluis any comments on why you closed this ticket?

**Comment by flamber** [comment]
Duplicate of #6735
