### ISSUE TITLE
Text filter over a custom column in simple embedding expects a number

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25473]
**Describe the bug**
When there's a text filter on a custom column in signed embedding, it will request for a number instead of a string

**Logs**
NA, seems like a FE error

**To Reproduce**
1) enable embedding
2) new->question->people>custom colum-> concat([Email], [Name]), save it with any name
3) add question to dashboard
4) add text filters (text contains, text does not contain, text starts with, text ends with)
5) click to embed it, enable the filters as editable
6) click on the filters to see all requesting a number

**Expected behavior**
Text filter should expect strings

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/190832656-c8c7788d-8322-41e6-b69c-d1d52d952f78.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14
- Metabase version: 1.44.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2

**Additional context**
Workaround: use a view in the DB to build the custom column

**Comment by flamber** [comment]
Related to #22788
