### ISSUE TITLE
I want the result of this query to be filtered by date using {{}} mapping , how can I do it ?

### ISSUE THREAD

**Issue by Mohammad-Al-Mashwakhi** [metabase/metabase#25476]
SELECT(SELECT b.count('status') 
from bookings b
join
booking_ratings_users r 
on b.id = r.booking_id
where (b.status = 'collect_payment'
and r.rating in(4,5)
AND {{created_at}}))
/
(SELECT count('status') 
from bookings
where status in('cancel_admin','collect_payment','cancel_client') 
AND {{created_at}});

**Comment by flamber** [comment]
https://www.metabase.com/learn/sql-questions/field-filters and https://www.metabase.com/docs/latest/questions/native-editor/sql-parameters
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
