### ISSUE TITLE
Whitelabel landing page string allows whitespace which leads to "page not found"

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#25482]
**Describe the bug**
It is currently possible to enter a simple whitespace for a custom landing page string, which leads to "Page not found". The problem is that this is hard to notice/fix.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Run EE version
2. Go to `/admin/settings/whitelabel`
3. For the "landing page" setting, enter a whitespace or `/   ` folowed by a few whitespaces, then click outside the input field to blur it
4. Exit admin and see that the page cannot be found with the message "We're a little lost...
The page you asked for couldn't be found."

**Expected behavior**
We should trim the whitespace because there's probably no scenario in which a URL would have it and be valid.

**Information about your Metabase Installation:**
local dev EE, `master`, 2c7178eac84f8edf6d7c9ffaa45675aa131d3a93, H2, Sample Database

**Severity**
P3 but it can get hard to figure out what's going on.

**Comment by flamber** [comment]
Very related to #18004

**Comment by nemanjaglumac** [comment]
FWIW, there is no validation for "Application name", nor for the favicon either. They both accept whitespace.
