### ISSUE TITLE
Untranslated strings in BulkFilterModal

### ISSUE THREAD

**Issue by Dynnammo** [metabase/metabase#25484]
**Describe the bug**
Many strings included in the modal used to filter graphical questions aren't included in translations files.

**Logs**

**To Reproduce**
0. Select a user inferface language different from english
1. Create a graphical question
2. Click on 'Visualize'
3. Click on Filter
4. See that `Filter ... by`, `Apply Filters`, `Search for a column name`, `Clear all filters`, are still in english despite current language selection.

**Expected behavior**
Having the translated string available for translators in POEditor

**Screenshots**
![image](https://user-images.githubusercontent.com/33259633/191040046-4f23d176-40cc-4a1b-9616-fc15ae9084b2.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (64-bit)]
- Your operating system: Linux Manjaro
- Your databases: yPostgresy
- Metabase version: 0.44.0
- Metabase hosting environment: Jar-file on Ubuntu
- Metabase internal database: Postgres 

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Not very annoying

**Additional context**

**Comment by flamber** [comment]
This looks like a problem with source strings not getting updated in POEditor, because the strings are translate-able in Metabase:
https://github.com/metabase/metabase/blob/4e4a1243771731f4650d7d591a34589344746971/frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.tsx#L143-L150

**Comment by Dynnammo** [comment]
That's what seemed weird to me. Can't find them in *.po files, so I think the same

**Comment by noahmoss** [comment]
Closing as this appears to be fixed on the current master

**Comment by Dynnammo** [comment]
Confirmed on my Metabase instance !
