### ISSUE TITLE
Untranslated `resource_type` in SharingPane.tsx

### ISSUE THREAD

**Issue by Dynnammo** [metabase/metabase#25485]
**Describe the bug**
When wanting to share a question or a dashboard, we have a sharing pane in which words `dashboards` or `question` aren't translated

The string responsible for such translation is located in SharingPane file
https://github.com/metabase/metabase/blob/00530c98afa02e753a78efba8494c533854d71dc/frontend/src/metabase/public/components/widgets/SharingPane.tsx#L116

**Logs**

**To Reproduce**
1. Go to a question or dashbaord
2. Click on share
3. See error

**Expected behavior**
Having `dashboard` or `question` translated in the user language

**Screenshots**
![image](https://user-images.githubusercontent.com/33259633/191044967-1976e084-14d3-4546-a8ce-7f52586c9260.png)
![image](https://user-images.githubusercontent.com/33259633/191045086-acc037f2-5241-4e0a-ba5d-b5dab4fa68a1.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (64-bit)
- Your operating system: Linux Manjaro
- Your databases: Postgres
- Metabase version: 0.44.0
- Metabase hosting environment: Jar-file on Ubuntu
- Metabase internal database: Postgres 

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Not very annoying

**Additional context**

**Comment by qwef** [comment]
Now seeing:


![Image](https://github.com/metabase/metabase/assets/34140255/12ba9429-449d-4815-82da-12b94ee3711d)

**Comment by sloansparger** [comment]
@qwef @iethree I don't think this is an issue any longer. It looks like this UI was deprecated in favor of a new SharePane design. You can see the file removed in this PR (https://github.com/metabase/metabase/pull/36170) merged 3 weeks ago.
