### ISSUE TITLE
Typing {{# in the native query editor sometimes freezes typing more characters

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#25492]
If you type `{{#` in the native query editor, the variables pane opens in the sidebar.

You should be able to keep typing in the editor when this happens.

If the variables pane covers part of the results table when it opens, the bug happens. If it doesn't cover any part of the results table, the bug doesn't happen.

### Steps to Reproduce

1. `+ New`
2. SQL Query
3. `select * from {{#...}}` and autocomplete with a model 
4. (make sure model has columns enough to cover the width of the monitor)
5. Run the query
6. Edit the query so that you delete the `{{#}}`
7. Go for the autocomplete again, but type fairly slowly `{{#`
8. Typing should freeze

In Firefox this doesn't happen.

Same issue happens if you start the parameter with a number, say `{{3}}` and then try to type further.

Not rendering the right-hand sidebar that opens up in these cases solves the typing issue.

![image](https://user-images.githubusercontent.com/39073188/191084952-e5a101da-cfc1-4d28-b9fb-c7b310087984.png)

See this loom for a full demo:
https://www.loom.com/share/0f67d31d39d9468bbc2a4d474f9079d0

**Comment by oleggromov** [comment]
Possibly this is no longer the case as I cannot reproduce either `{{#` or `{{3}}` case on the current master 926b04a1d5377798b0bbb98ef6b28ddac3210c89

**Comment by romeovs** [comment]
I am also unable to reproduce this bug
