### ISSUE TITLE
How to integrate metabase dashboard code to directus

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [metabase/metabase#25490]
How to integrate Metabase dashboard code to directus

![image](https://user-images.githubusercontent.com/36895131/190700135-0cb52584-0f86-46d5-a862-68268f081c08.png)

1. Compiled a extension module using npm extension build

![image](https://user-images.githubusercontent.com/36895131/190840539-fa510167-7235-4bc8-a8dc-41c38667e7bf.png)

2. Updated Vue Js and index.js with the metabase code like below

![image](https://user-images.githubusercontent.com/36895131/190840596-f4ade6eb-5fb8-4cab-ad23-c5b3e624c7b4.png)

![image](https://user-images.githubusercontent.com/36895131/190840605-121bb9b9-c0e4-4aeb-ac7b-29c59249aad8.png)

3. then again compiled the module using 

![image](https://user-images.githubusercontent.com/36895131/190840637-75f21db8-bf65-4323-9b7a-62dcf76ebfee.png)

4. Then uploaded index,js file to respective extension folder

![image](https://user-images.githubusercontent.com/36895131/190840693-65ef3ccb-1925-4452-86cc-8343eb91b2f1.png)

5. Validated directus log if any error but not getting any error

![image](https://user-images.githubusercontent.com/36895131/190840759-c3b2aa12-0b6f-4b55-897f-b3183240848e.png)

I supposed to get the icon in my left side menu correct but not getting it

https://github.com/directus/directus/discussions/15615

**Comment by flamber** [comment]
There's currently the following reference example apps: https://github.com/metabase/embedding-reference-apps
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Also, you posted your URL and JWT secret, so you need to change it immediately.
