### ISSUE TITLE
Alerts/notifications not working

### ISSUE THREAD

**Issue by pcothenet** [metabase/metabase#25499]
**Describe the bug**

We have been happily running metabase in our current configuration for a year+ but have never been able to get notifications/alerts during that time.

- We are running Open Source, deployed on ElasticBeanstalk
- On latest version (but has never worked on any prior)
- Encryption is on

- The email setup is working fine. The user even receives the confirmation that the alert has been created, but nothing after that
- Alerts created correctly appear in Account Settings

**What we've tried**

- Re-creating the Slack app
- Trying with just email, or just Slack
- Upgrading the version

We're not completely sure what we're looking for, but looking at the troubleshooting section, we can't find anything in the logs that indicates an error.

It seems more likely that the background task is just never running at all.

**Expected behavior**

- Alerts are sent daily / hourly, as expected

**Severity**

We've used metabase for two years without alerts, but our team and usage has grown sufficiently that people are starting to try to build workflows around alerts.

**Screenshots**

<img width="562" alt="Screen Shot 2022-09-19 at 5 08 01 PM" src="https://user-images.githubusercontent.com/1460006/191140062-26657f15-bc71-4f6d-bdba-34e3835a9e9c.png">

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "4.14.290-217.505.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-02",
      "tag": "v0.44.3",
      "branch": "release-x.44.x",
      "hash": "7d50282"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Comment by pcothenet** [comment]
Additional information:

- Sending a dashboard to email immediately works
- Sending a dashboard to Slack immediately works

**Comment by pcothenet** [comment]
Not sure if related, but I'm also seeing nothing here:

<img width="1484" alt="Screen Shot 2022-09-19 at 5 28 22 PM" src="https://user-images.githubusercontent.com/1460006/191141765-3fb47579-528d-4af7-8ef4-2c5149da512e.png">

**Comment by flamber** [comment]
Hi @pcothenet 
Do a dump of all `qrtz_*` tables in the application database and share that. There's something wrong.
Also include the logs from when Metabase is starting up, so it is possible to see if it errors/warns about anything.
I have no idea what could have caused this, but the Quartz triggers are not working as expected.

**Comment by pcothenet** [comment]
@flamber 

Looking at `qrtz_cron_triggers`, there's no records related to pulses:

<img width="1072" alt="Screen Shot 2022-09-20 at 10 42 39 AM" src="https://user-images.githubusercontent.com/1460006/191330977-4270d1b3-3a08-4411-8fc5-b5db861f0fdf.png">

Thinking back, I think this table may have been emptied by a migration of the DB about a year ago. It seems like it's missing the cron record for pulses. Any way to easily add it back?

**Comment by pcothenet** [comment]
@flamber the second tactic worked (I spawned up a new instance, identify what was there and did some surgery). Thanks for your help!
