### ISSUE TITLE
Snippets with filter support

### ISSUE THREAD

**Issue by a-meledin** [metabase/metabase#25509]
Hello, 

Is there any way to save and use snippets with filters? It's really required when several cards in one or several dashboards use the same filtering pattern. Currently, I have to duplicate SQL code in every place where the same filtering pattern is used. Often such snippets use Field Filter referencing the same table and column and having the same name across  multiple questions and dashboards.

Thanks in advance, Aleksei.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
