### ISSUE TITLE
Referencing a model in a SQL query won't use the persisted model

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25516]
**Describe the bug**
When referencing the model in a SQL query ( {{# ..}} ), then the query won't use the persisted model but rather will go to the actual table

**Logs**
NA

**To Reproduce**
1) Enable model caching (ensure that the model is being cached by checking the DB)
2) create a model (e.g. select * from people), cache it
3) then create a new GUI question and use the model, see that Metabase pulls the data from the cache (even when using the /dataset endpoint)
4) now create a SQL question, and reference the model as it would be a saved question with its id (e.g. select * from {{ # x }}, being x the id of the model), save it and run it. See that the model is pulled from the source tables rather than from the cache

**Expected behavior**
Cached models should always be pulled from the cache

**Screenshots**
Using GUI question
![image](https://user-images.githubusercontent.com/1711649/191291047-2f7521f7-457c-4262-ba14-8ff835f35458.png)
![image](https://user-images.githubusercontent.com/1711649/191291103-220db439-36c5-43d7-973f-3e410b498159.png)

Using SQL question
![image](https://user-images.githubusercontent.com/1711649/191291274-ce7302cb-dd12-44b3-84f7-2e96699ba110.png)
![image](https://user-images.githubusercontent.com/1711649/191291320-cbf48969-29a2-4eba-a09d-461c73a005ec.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres
- Metabase version: 1.44.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2?

**Additional context**
Reported by a customer

**Comment by Mohammad-Rahmati** [comment]
Hi @dpsutton ,
I think the problem remains unsolved. Take a look at the following screen shots. The first image is a question referencing a model, and the second image is the model loading performance.

![image](https://user-images.githubusercontent.com/22165051/192463773-c1d8d7a9-5101-4658-a212-23696d01ae5b.png)
![image](https://user-images.githubusercontent.com/22165051/192463858-95bd1a81-99a0-40fa-bc7c-ee8878b4e09a.png)

**Comment by flamber** [comment]
@Mohammad-Rahmati Your screenshots are showing you're running v44.2. The issue is fixed in upcoming v45.0

**Comment by Mohammad-Rahmati** [comment]
@flamber Thanks for the prompt reply! When do you think the new update goes live?

**Comment by flamber** [comment]
@Mohammad-Rahmati I don't know. Within a couple of months.
