### ISSUE TITLE
Google Analytics integration instructions are no longer valid (February 28, 2022 - new OAuth usage blocked for the OOB flow)

### ISSUE THREAD

**Issue by tyrauber** [metabase/metabase#25528]
**Describe the bug**
The [Google Analytics integration instructions](https://www.metabase.com/docs/latest/databases/connections/google-analytics) appear to be no longer valid.  After creating your service worker, assigning the user in Google Analytics, and configuring metabase with the new OAuth client and secret, the link to get an Auth token fails.

```
Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow Migration Guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
```

**To Reproduce**
1. Follow the Google Metabase instructions here:
https://www.metabase.com/docs/latest/databases/connections/google-analytics
2. Attempt to configure Google Analytics as a Metabase datyabase.

**Expected behavior**
Expect to get auth code and begin configuring charts with Google Analytics data.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version:  Chrome/105.0.0.0
- Your operating system: Intel Mac OS X 10_15_7)
- Your databases: Postgres
- Metabase version: v0.41.2
- Metabase hosting environment: Heroku
- Metabase internal database: postgres

**Severity**
Blocking some uses. It would be great to be able to pull in web statistics into a dashboard to provide context with database statistics.

**Additional context**

This may be resolvable by modifying the Oauth command to get the Auth token.
```
Add an ack_oob_shutdown parameter with a value of the enforcement date: 2022-10-03 to your redirect flow request. Example:

ack_oob_shutdown=2022-10-03
```

**Comment by paoliniluis** [comment]
Hi, we changed a lot regarding OAuth between 41 and 44, please upgrade to the latest version
