### ISSUE TITLE
Increase the font size of large scalar cards

### ISSUE THREAD

**Issue by cagiraudo** [metabase/metabase#2552]
Hi,

I am new with MetaBase. First of all i want to congratulate the whole team

I have the same problem that this issue that was supposedly fixed in v0.16 https://github.com/metabase/metabase/issues/2125

I want to make a dashboards with big numbers to be seen from far in a office, but even if i make the card very big, the font-size of the number doesn't scale
![seleccion_072](https://cloud.githubusercontent.com/assets/19225821/15076376/be069b0c-137f-11e6-8ee4-bdb8ddcf723b.png)

Thanks
-  I am using the Chrome browser.
-  My computer's OS is Ubuntu.
-  I'm running Metabase in ubuntu server
-  My database is MySQL.
-  My Metabase version is v0.17.0.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by kdoh** [comment]
Hey there @cagiraudo! Have you tried putting the dashboard in fullscreen mode?. We bump the type size on scalars a bit in that mode to help with longer distance viewing like the use case you're describing.

**Comment by cagiraudo** [comment]
Hi @kdoh 

I tried in fullscreen and it's the same. The number is tiny in the center of the card. 

If you need a screen print or more info ask me

**Comment by mazameli** [comment]
@cagiraudo so technically this is working as intended, but it seems, @kdoh, that we're hearing that people want to have even larger font sizes when they make a scalar card super wide. Any reason why we wouldn't want to do that?

**Comment by kdoh** [comment]
@mazameli Let me do a bit of testing and confirm @cagiraudo's not hitting some kind of bug / unintended state with a wide scalar in fullscreen. In fullscreen we should definitely make the size reasonably large and I was under the impression it was doing that.

**Comment by mazameli** [comment]
Ah, maybe my mistake. I had interpreted it as there was a disconnect around what "big" means/should mean.

**Comment by cagiraudo** [comment]
To make it a litlle more clear.

This is what i have when i make a big number card

![seleccion_075](https://cloud.githubusercontent.com/assets/19225821/15079880/7d821d60-1391-11e6-8590-c61dc8ce57f4.png)

And this is what i would expect to see if i make a big number card to display in a LCD

![seleccion_074](https://cloud.githubusercontent.com/assets/19225821/15079916/bf1f70ba-1391-11e6-9886-22934d9ee3a2.png)

Hope that make it a little more clear

**Comment by MrMauricioLeite** [comment]
I guess I opened a issue long ago about this.... but apparently did not made it's way to a change in code.

Please, notice that as a dashboard designer we know that the number is going to be super-sized if we get the card to be too big. We expected that. But Metabase forces us to use what it think that is the 'max font size'. 

Please make this the default behaviour.

**Comment by MrMauricioLeite** [comment]
https://github.com/metabase/metabase/issues/2125

**Comment by imsky** [comment]
+1 would be great to have intelligent font sizing/word wrapping

**Comment by ASochat** [comment]
I don't know if you guys are still working on it, but that would be a wonderful feature! Thanks for the great work

**Comment by SharmilaNadesan** [comment]
Are you guys working on this. This feature would be really great. Font size is really small when projected in TV.

**Comment by flamber** [comment]
There's currently no way to do this with CSS - well, not in a way, where it doesn't mess up the label.
Solutions are JavaScript or SVG: https://css-tricks.com/fitting-text-to-a-container/

**Comment by mickdee** [comment]
+1, I'm using metabase as an information display mounted on a wall and the text in big number cards is very hard to see beyond just a few feet away. Is there no way to customize the type size still?

**Comment by kevinsimper** [comment]
What are the code that needs to be changed for this feature? I tried looking at the frontend code but I could not easily find it.

Also, would it be a setting or just changing the default behavior?

**Comment by flamber** [comment]
@kevinsimper We're currently working on this - have a look at #21003

**Comment by kevinsimper** [comment]
@flamber Nice, I added a comment. I think the fontsize either needs to user defined or use a algorithm similar to https://brorlandi.github.io/big-text.js/
