### ISSUE TITLE
Filters in dashboards allow an empty value

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25533]
**Describe the bug**
When using dropdown filters, if you don't select a value and click on the button, then the filter will populate but with an empty value. No effect at all, but seems like the queries run

**Logs**
NA

**To Reproduce**
1) Build a question (people table)
2) add it to a dashboard
3) add a dropdown filter to a dashboard and connect it with source
4) save the dashboard and pop up the filter, don't select any value but click the button
5) see the error

**Expected behavior**
If there's no value, you can't confirm

**Screenshots**
![empty-value](https://user-images.githubusercontent.com/1711649/191378118-24c8867e-0884-4084-93e2-a7ab9bb548cc.gif)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: pop 22.04
- Your databases: postgres
- Metabase version: 1.44.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P3

**Additional context**
NA

**Comment by flamber** [comment]
Related to #15462

**Comment by collinewait** [comment]
Fixed in this PR #25865
