### ISSUE TITLE
Background of tables list not extending properly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2553]
With a long list of tables that exceeds the height of the browser window, the background of the table list looks wrong:

![screen shot 2016-05-06 at 9 20 15 am](https://cloud.githubusercontent.com/assets/2223916/15079206/0292712e-136c-11e6-8e31-6b7b84038ee1.png)

*  I am using the Chrome browser.
*  My computer's OS is El Capitan.
*  I'm running Metabase on our Stats instanc.
*  My database is Postgres.
*  My Metabase version is 0.17

**Comment by mazameli** [comment]
Is this an easy fix, @kdoh ?

**Comment by kdoh** [comment]
So making the background element enclose its contents seems pretty doable. I think the larger problem here is really that the pattern doesn't scale well. to long lists of tables / schemas.
