### ISSUE TITLE
404 on loading models when instance is configured in another language

### ISSUE THREAD

**Issue by nikolap** [metabase/metabase#25537]
**Describe the bug**
When you try to create a question using a model on an instance configured in german, the UI returns 404

**Logs**
2022-09-21 12:30:18,511 WARN middleware.log :: GET /api/database/-1337/datasets/Alles%20andere 404 2.0 ms (1 DB calls) 
"Not found."

**To Reproduce**
1) Start a new Metabase instance and configure it in german
2) create a model (new question->people table->save it->click on 3 dots on the upper right corner-> turn into model)
3) try to create a question now by using the model
see the 404

Screenshots
![image](https://user-images.githubusercontent.com/1711649/191508563-e0917f88-eef0-4824-ad6a-6e74b5f3426b.png)

**Information about your Metabase Installation:**
metabase version v1.44.3

**Severity**
This blocks functionality of models for our use case. Analysts cannot create new questions using the models in Metabase.

NOTE: tried only in German, but maybe it happens with other languages

**Comment by paoliniluis** [comment]
Please write to our support mailbox with the name of the instance and the name of the model
