### ISSUE TITLE
Map visualization in an X-ray results in card title not linking properly

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#25566]
**To Reproduce**
1. Go to 'Browse Data' -> 'Sample Database'
2. Click on 'X-ray this table' for the People table
3. Scroll down to the US map under 'Where these People are'
4. Try to click on 'Per state' (the title of the card). Only the top border of the text is clickable, not the entire text.

**Expected behavior**
Should link normally.

**Information about your Metabase Installation:**
Current master (can repro on stats)

**Severity**
Minor

**Comment by flamber** [comment]
I guess it has either been fixed or specific to browser? Cannot reproduce on Firefox or Chrome.
The title for region maps shouldn't be different from many others viz, so not sure why it only happens on that.

**Comment by noahmoss** [comment]
Huh, I can't repro it anymore either. Maybe it was inadvertently fixed because I could definitely repro it on Firefox last week.
