### ISSUE TITLE
Metabase is using legacy Google Sign-In JavaScript library

### ISSUE THREAD

**Issue by caleb15** [metabase/metabase#25564]
I got an alert from google that Metabase is using the legacy Google Sign-In JavaScript library. The Client ID they reported corresponds to Metabase. We are running a recent version of MB. I looked through the changelog but didn't see any updates addressing the issue. Here is the email:

<div align="center" style="font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Arial; padding: 20px 0px; color: rgb(38, 50, 56); font-size: 18px; line-height: 26px;"><em>One or more of your web applications uses the legacy Google Sign-In JavaScript library. Please migrate your project(s) to the new Google Identity Services SDK before March 31, 2023.</em></div><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Hello Google Developer,</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">You are receiving this message as a reminder that one or more of your web applications uses the<span> </span><a href="https://notifications.google.com/g/p/AKWoLQheHUN-nVyFUbahCXL5IEA7pBEjrACxUgyQSgePfO3qQAhRU6h0uB24yrrC0sVsbtN7-iTkX1cz8bxrw2jP57xPpmcPobuVBjQXO3FNevGWJ2FxFUagC1otDBGivMiSXMNzvgc6vgNQ" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AKWoLQheHUN-nVyFUbahCXL5IEA7pBEjrACxUgyQSgePfO3qQAhRU6h0uB24yrrC0sVsbtN7-iTkX1cz8bxrw2jP57xPpmcPobuVBjQXO3FNevGWJ2FxFUagC1otDBGivMiSXMNzvgc6vgNQ&amp;source=gmail&amp;ust=1663874585136000&amp;usg=AOvVaw0hbnDC-ULctlRUBHdTZzvn" style="color: rgb(17, 85, 204);">legacy Google Sign-In web solution</a>. Our<span> </span><a href="https://notifications.google.com/g/p/AKWoLQi-viTjZNtUA15RQgKD1BViYZbRN1mIPGH6oQWPvqZ7_edEh87Kmy30PrrVbsnsK6fmQHtTaEzDiK-6qJ26V4nvF23UUqFshKuGkpTHBdmHKNVs--0LQ2YbOhrLlVR3W9cixbn6HeQY0wdIOcpn27UgCA" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AKWoLQi-viTjZNtUA15RQgKD1BViYZbRN1mIPGH6oQWPvqZ7_edEh87Kmy30PrrVbsnsK6fmQHtTaEzDiK-6qJ26V4nvF23UUqFshKuGkpTHBdmHKNVs--0LQ2YbOhrLlVR3W9cixbn6HeQY0wdIOcpn27UgCA&amp;source=gmail&amp;ust=1663874585136000&amp;usg=AOvVaw3QHr9dpoGOvSd8Fhh5tdce" style="color: rgb(17, 85, 204);">announced plan</a><span> </span>stated that authentication support for the<span> </span><strong>Google Sign-In JavaScript</strong><span> </span>platform library will no longer be supported after<span> </span><strong>March 31, 2023</strong>.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">After<span> </span><strong>March 31, 2023</strong>, migration to the new<span> </span><a href="https://notifications.google.com/g/p/AKWoLQibp6H1GCKv4SQG2ul4luj-6DeynjxGtUBOl2sTS8kda0OpXBtUiNJ8AfR-FM16iYP8JuKqEUNsYPDRc9qLnNw2LiSzONVhM0r5eX7VEh3jrGiGp79kwJY-Z0lb5OpE" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AKWoLQibp6H1GCKv4SQG2ul4luj-6DeynjxGtUBOl2sTS8kda0OpXBtUiNJ8AfR-FM16iYP8JuKqEUNsYPDRc9qLnNw2LiSzONVhM0r5eX7VEh3jrGiGp79kwJY-Z0lb5OpE&amp;source=gmail&amp;ust=1663874585136000&amp;usg=AOvVaw2EIEDv6BW2a3WuitzR6xat" style="color: rgb(17, 85, 204);">Google Identity Services</a><span> </span>will be necessary to sign in customers using their Google Account to your platform. The SDK will use the new Sign In With Google client library.</p><h3 style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What do I need to know?</h3><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">To help you find out which of your web apps or environments are affected, we’re sharing a list of your client ID(s) that use the legacy Google Sign-In web solution. This list should help you evaluate user impact and prioritize the migration work more efficiently:</p>

App Name | Client ID
-- | --
CENSORED | CENSORED

<h3 style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What do I need to do?</h3><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">At your earliest convenience,<span> </span><strong>migrate to the new Google Identity Services by following the<span> </span><a href="https://notifications.google.com/g/p/AKWoLQhWgCHj05g03CtlOdMIYKgbScFGlpGsVbvBHVMip9Fem9N5vUuHSu2oPESheCXHTrRFyBHNbiEqREaRIRe6ETqPP7oAVlASILrZJNJnU5_1VkYltWkMR14KNHnqNerGn6CkArZUtlEclL60wcI" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AKWoLQhWgCHj05g03CtlOdMIYKgbScFGlpGsVbvBHVMip9Fem9N5vUuHSu2oPESheCXHTrRFyBHNbiEqREaRIRe6ETqPP7oAVlASILrZJNJnU5_1VkYltWkMR14KNHnqNerGn6CkArZUtlEclL60wcI&amp;source=gmail&amp;ust=1663874585136000&amp;usg=AOvVaw0gCfpaFnTTFKAc_BXRHhCW" style="color: rgb(17, 85, 204);">migration guide</a>.</strong></p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Be sure to read through the<span> </span><a href="https://notifications.google.com/g/p/AKWoLQhbd_SGFXn0ux3TQ2G61Llg-wLn7w9BAroSI8v1SBJ-sPV4vOLN4yaGu-vyXG-D5ZnmcINC2rAotL1QLiRiFFfmkdFDWJsYA0GZ4i7Bj4tqfDUmbjU7lchxrYGm3ASeLF7NA97XHBnm9WqJsg" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AKWoLQhbd_SGFXn0ux3TQ2G61Llg-wLn7w9BAroSI8v1SBJ-sPV4vOLN4yaGu-vyXG-D5ZnmcINC2rAotL1QLiRiFFfmkdFDWJsYA0GZ4i7Bj4tqfDUmbjU7lchxrYGm3ASeLF7NA97XHBnm9WqJsg&amp;source=gmail&amp;ust=1663874585136000&amp;usg=AOvVaw39p1IbJHyc0YZloLDHc8vo" style="color: rgb(17, 85, 204);">Sign-In With Google resources</a><span> </span>guide. If you have migration specific feedback to share, send an email to<span> </span><a href="mailto:gis-migration-feedback@google.com" target="_blank" style="color: rgb(17, 85, 204);">gis-migration-feedback@google.<wbr>com</a>.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Thanks for choosing Google Identity Services.</p><p style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>–The Google Identity Services Team</strong></p><div style="font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 10px; color: rgb(102, 102, 102); padding-top: 8px; border-top: 1px solid rgb(220, 220, 220);"><br class="Apple-interchange-newline">

**Comment by caleb15** [comment]
@zxpower I saw that you commented about this, I just opened up a issue for it FYI

**Comment by paoliniluis** [comment]
which version of Metabase are you using?, please post diagnostic info

**Comment by flynfish** [comment]
We are using 0.44.2 and also received the same message.

**Comment by paoliniluis** [comment]
I just went through the packages and we're using the new Google Identity Services SDK
https://github.com/metabase/metabase/blob/affe217249446e76af41bbcf3dc7551536936f92/package.json#L15
https://www.npmjs.com/package/@react-oauth/google

This seems like a false alarm probably coming from the fact that we used the previous library till 43.4

**Comment by caleb15** [comment]
Okay, thanks!

**Comment by flamber** [comment]
For reference:
- #17429 - temporary fix in 0.43.4, fully migrated in 0.44.0
