### ISSUE TITLE
Support dashboard level filters

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2556]
Creators will be able to connect global filters to cards in a dashboard. See the below invision prototype.

https://projects.invisionapp.com/share/9R6WIXBEQ#/screens/146004909_1_-_Empty_DB

This will work in conjunction with #1543 (which includes just questions) and #2348 . Specifically the intention is to allow dashboards to link filters to SQL cards when #2348 is completed.

**Comment by fimpfimp** [comment]
+1
