### ISSUE TITLE
Data Model keeps resetting input fields while editing

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#25570]
**Describe the bug**
Data Model keeps resetting input fields while editing depending on connection speed, and how fast responses to GET requests are.
And also resets if you start editing another input before the toast has closed.

Adding regression, since the toast seems like a new-ish problem, and we have tried to address this multiple times.

**Important** The reproduction only shows field names on the table overview page, but it's important to make sure the fix applies to any input (including the table name/description), and all inputs on the fields detail page :gear:. I'm not going to create an issue for every single input in the entire Data Model, then there's something wrong in our Form component.

**To Reproduce**
1. Admin > Data Model > Sample Database
2. Throttle browser to 2G to similar various connection slowness
3. Try editing fields

https://user-images.githubusercontent.com/1447303/191710821-17c5d692-ee03-48ac-ba96-dc4b2131eb1c.mp4

4. Then try no throttle and just edit multiple input before the toast has gone away

https://user-images.githubusercontent.com/1447303/191711001-a8e45564-80cc-457b-934a-0ff6217aad97.mp4

**Information about your Metabase Installation:**
Tested 0.44.3

**Additional context**
Related to #10462 and #16780 and #24955, historically to #19710 and #22742

**Comment by iethree** [comment]
When the toaster updates, it resets redux state.

![toastDataRefBug](https://user-images.githubusercontent.com/30528226/197240011-ca9df7bb-d923-4691-b4d2-fe62410b6c2f.gif)
