### ISSUE TITLE
Add page to create Model without a Question using Notebook Editor

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#25598]
##### 1

User lands on `/model/notebook`.

Base64 hash will be added to url.

<hr>

##### 2

User selects data source

<img width="400" alt="image" src="https://user-images.githubusercontent.com/380816/192010009-eef2024a-a95e-4087-bc8b-6e5fa9db6410.png">

User can choose the same data sources she would be able to if she was creating a new Question.

<hr>

##### 3

After user chooses a data source, page will look much like a new Question page. Top blue picker will show the data source, with the option to change it and to pick columns on the right-side dropdown button.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/380816/192011704-448dbc22-1795-4aaa-add3-69edb933aacb.png">

<hr>

##### 4

Once user clicks on Save, we save this as a Model.

**Comment by mazameli** [comment]
> User lands on /model/notebook

I'm not at all sure what the best course for implementation was, but I think my assumption for both this and https://github.com/metabase/metabase/issues/25600 that we'd reuse `/model/:id/query`, i.e., the existing query editing mode that we have for models.

**Comment by gusaiani** [comment]
@mazameli 

> my assumption for both this and https://github.com/metabase/metabase/issues/25600 that we'd reuse /model/:id/query

Yes, that's also the first idea in my mind for this.

**Comment by daltojohnso** [comment]
@mazameli there's no `id` in this scenario, so how about `/model/query#hash` (and `/model/metadata#hash`) where `hash` is the encoded card object?
