### ISSUE TITLE
Waterfall charts with non-aggregated data improperly calculate y-offsets

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#25597]
**Describe the bug**
Plotting waterfall charts with non-aggregated data (multiple data points have the same x-axis coordinate/label) leads to the invisible support [`beams`](https://github.com/metabase/metabase/blob/12c5b6ea74f7354ed54ca68a962dc39efa9c31b4/frontend/src/metabase/visualizations/lib/renderer_utils.js#L272-L280) also being [aggregated per non-aggregated category](https://github.com/metabase/metabase/blob/12c5b6ea74f7354ed54ca68a962dc39efa9c31b4/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js#L197-L201). This leads to the waterfall chart points being plotted with non-meaningful y-axis offsets (aka 'beams').

**To Reproduce**
1. New -> Question -> Orders
2. Summarize `Count`, Group by `Created At: Year`, `Product -> Category`
    - i.e. create a dataset with non-aggregated data
4. Visualize, and select waterfall.
5. In Viz Settings, Remove `Product -> Category` from X-axis

The chart that is rendered won't make much sense, as you can see in the screenshot it starts around 26000. The total is correct though.

![image](https://user-images.githubusercontent.com/1328979/191977146-91730cf7-bb1b-428a-8a8a-fe2e88bfdb4c.png)

**Expected behavior**
Calculate the invisible support [`beams`](https://github.com/metabase/metabase/blob/12c5b6ea74f7354ed54ca68a962dc39efa9c31b4/frontend/src/metabase/visualizations/lib/renderer_utils.js#L272-L280) after aggregating the data.

**Screenshots**

**Information about your Metabase Installation:**
Pulled from Master

**Severity**
Likely low priority, since it's fixable if you adjust your query. Only concern is that someone might not realize that the chart isn't what they think it is.,

**Comment by flamber** [comment]
This feels like we regressed at some point, since we visited something similar in #15152
