### ISSUE TITLE
Add journey to create fresh Model using New button

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#25602]
Layouts: https://www.figma.com/file/HnmVcvIUPOx4vam9hRmtjl/Create-New-Model-flow?node-id=2%3A356

##### 1

Add link to bottom of `New` dropdown

<img width="400" alt="image" src="https://user-images.githubusercontent.com/380816/192025895-be3dad92-c7b5-49d8-9aef-eca2d18d5313.png">

##### 2

User can click and choose to:

a. create a Model using Notebook editor › will go to `/model/notebook`, issue https://github.com/metabase/metabase/issues/25598
b. create a Model using Query editor › will go to `/model`, issue https://github.com/metabase/metabase/issues/25600
c. cancel › back to home page

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/380816/192025992-f2949621-5636-4507-9e01-d36be72b0c01.png">

**Comment by mazameli** [comment]
@gusaiani, I think you know this, but just to be sure: the boxes in the "create a new model" page can still be found in the product at `/question/new` so we can grab them from there.

**Comment by gusaiani** [comment]
@mazameli 

> the boxes in the "create a new model" page can still be found in the product at /question/new

Yes, but thank you for reminding me.
