### ISSUE TITLE
SmartScalars should aggregate the same way as Scalars

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25637]
**Is your feature request related to a problem? Please describe.**
A customer has requested that the smart scalars should aggregate when the viewport is narrow in the same way scalars do.

Check out how they both behave, one aggregates while the other doesn't
![smart_scalars_cohesion](https://user-images.githubusercontent.com/1711649/192366497-807a9832-c585-4c50-9254-7f23065f3e74.gif)

**Describe the solution you'd like**
Same behavior on both viz's.

**Describe alternatives you've considered**
Currently there's none

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by flamber** [comment]
Similar to #23093, but specific to Trend viz.
