### ISSUE TITLE
case sensitivity problem when rescan a table

### ISSUE THREAD

**Issue by Andres-Peng** [metabase/metabase#25641]
I got a table that has a field named "Inbound_date".
For some reason, I changed the name to "Inbound_Date".
However, it never updates the name.
I guess the code might just ignore the case sensitivity.

I changed the name value in the "metabase_field" table, at the end.

thanks

    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Windows Server 2019",
    "os.version": "10.0",
    "user.language": "zh",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}

**Comment by flamber** [comment]
You should upgrade immediately to a newer release of Metabase: https://github.com/metabase/metabase/releases/latest

**Comment by Andres-Peng** [comment]
> You should upgrade immediately to a newer release of Metabase: https://github.com/metabase/metabase/releases/latest

Thanks
