### ISSUE TITLE
GH actions workflow shouldn't build uberjar, just use the Clojure CLI to run SerDes commands

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#25659]
**Is your feature request related to a problem? Please describe.**
We currently spin up an entire Metabase instance to run serialization commands. We can optimize it by selective loading the necessary namespaces.

**Comment by camsaul** [comment]
I'll take a look at this but I'm not 100% sure we actually do load everything

**Comment by luizarakaki** [comment]
Hey @camsaul, does this [PR](https://github.com/metabase/serialization-playground/pull/3/files) closes it?
