### ISSUE TITLE
Trend text not translated correctly depending on period

### ISSUE THREAD

**Issue by sbsrouteur** [metabase/metabase#25670]
**Describe the bug**
The trend label states "était 11dernier année" it should be "était 11 l'année dernière".

This is related to #8389 as year, month, day, week have different genders, and require different spelling on the adjective.

**To Reproduce**
- Create a yearly trend indicator on a French locale system.
- Using languages like German causes the period to be [force lower-case](https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase/visualizations/visualizations/SmartScalar.jsx#L117)

**Screenshots**
Sample screenshot:
![image](https://user-images.githubusercontent.com/11095871/192705335-187c663b-715c-4014-a75d-409ed26e670f.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Opera 90
- Your operating system: Win10 
- Your databases: SqlServer2016
- Metabase version: v0.44.3
- Metabase hosting environment: docker
- Metabase internal database: H2

**Severity**

Cosmetic

**Comment by flamber** [comment]
Similar to #13188 (which is related to #8389)

**Comment by flamber** [comment]
@adrien-chinour Translations are done via https://poeditor.com/join/project/ynjQmwSsGh, but this would require much more extensive work to handle full strings. It requires likely both frontend and backend work. Not simple.

**Comment by adrien-chinour** [comment]
I understand, thank you.
