### ISSUE TITLE
[Models] Not possible to edit metadata of column from join with saved question

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#25682]
**Describe the bug**
The metadata edition sidebar is blank when selecting a column that comes from a join with a saved question.

**To Reproduce**
1. Open https://stats.metabase.com/model/5464-dashboards/metadata
2. Try to edit metadata from the last column: `Question 5465 -> Count`
4. The sidebar is empty

**Expected behavior**
It should open the normal sidebar.

**Screenshots**
![image](https://user-images.githubusercontent.com/32561114/192852399-64271075-89e5-420a-9252-6542f442549f.png)

**Information about your Metabase Installation:**
Stats

**Comment by flamber** [comment]
Similar to #25437 and #22521

**Comment by nemanjaglumac** [comment]
The sidebar is not empty anymore, but I'm now experiencing https://github.com/metabase/metabase/issues/25885 on that question.
