### ISSUE TITLE
"One of your alerts has stopped working" email should provide more detail

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25693]
**Is your feature request related to a problem? Please describe.**
If someone deletes a question that had alerts, an email gets triggered to the alert creator nothing than the text in the title and who deleted the question.

**Describe the solution you'd like**
Add info about which is the question that was deleted to the email. We should also add to the archived list the ID's of the question as names can be confusing if there are many questions with the same name.

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by flamber** [comment]
Basically a repeat of #8535.

**Comment by qnkhuat** [comment]
@paoliniluis how about 

"Alerts about Accounts question(id=3) have stopped because the question was archived by Crowberto Corv"
