### ISSUE TITLE
Undo move dashboard doesn't always work in v44

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#25705]
**Describe the bug**
When you move a dashboard there is a toast popup in the lower left corner of the window saying to which collection was dashboard moved. That popup also provides the option to "Undo" that action. It seems that this functionality has been broken in the v44.

**Logs**
The `PUT` request when you hit the "Undo" button is empty `{}`

**To Reproduce**
1. Have a dashboard with a question in "Our analytics" and have at least one more collection (let's call it "Other collection")
2. Open a dashboard by pasting a link to it rather then clicking on it from the root collection (not sure why but this step is crucial and is the only way to reproduce this issue)
3. Click on the `...` menu and choose "Move"
4. Choose "Other collection" and then click "Move"
5. In the lower left corner, click "Undo"
6. Note that the breadcrumb still says "Other collection" instead of "Our analytics" and note that the dashboard actually didn't move

**Expected behavior**
Undo button should move the dashboard back to the original collection.

**Information about your Metabase Installation:**
local dev, `release-x.44.x` branch, bdd15015054cd75736dba7de67343efbbbb1d90d, H2, Sample Database

**Severity**
P3

**Additional context**
- Doesn't seem to happen on `master` (v45)`
- This was caught by Cypress because the test for moving and undo moving the dashboard is failing consistently. At first I thought it's some weird race condition but then I could reproduce it manually.

**Comment by WiNloSt** [comment]
This doesn't seem to happen in `master` @ 8d366f210c04d847bb5011c249e10b9b64510421
