### ISSUE TITLE
`POST /api/util/password_check` called way too often during setup

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#25712]
This is on `master` (pre-45.0)

Every time you type any character in *any* Field it hits the `POST /api/util/password_check` endpoint... even if you haven't gotten to the password field yet.

![password check](https://user-images.githubusercontent.com/1455846/193115142-8dbe4b14-cb13-4447-8210-f8ce88eca0e8.gif)

Suggestions:

1. Only trigger the API call when updating the password field, not when other stuff gets updated
2. Don't do the API call when the password field is blank

**Comment by camsaul** [comment]
Is this a regression?

**Comment by nemanjaglumac** [comment]
Cannot be reproduced neither in `master` @c7e2a00, nor in the latest release 50.7.
