### ISSUE TITLE
authentication with active directory

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#25725]
Hello,

Is it planned in the future to extend the authentication methods to other directories? For example Active Directory or Metabase being able to communicate with Radius?

Thanks.

**Comment by flamber** [comment]
AD is already supported: https://www.metabase.com/docs/latest/people-and-groups/saml-azure
Any other SSO methods would only be available in the Pro/Enterprise editions.

**Comment by Philippe-M** [comment]
@flamber Thank you for your reply. I did not specify that my AD uses Samba 4 in DC mode without openldap. So, unless I'm mistaken, it's not possible to have identical behavior using Azure.

**Comment by flamber** [comment]
@Philippe-M Then you can create your own [JWT authentication](https://www.metabase.com/docs/latest/people-and-groups/authenticating-with-jwt), since it's very unlikely that we will make a direct integration of Samba without LDAP.
