### ISSUE TITLE
JSON unfolded field always uses type from original schema

### ISSUE THREAD

**Issue by kbrownlees** [metabase/metabase#25744]
**Describe the bug**
We have a number of JSON fields which can have different types, the two basic situations where this occurs are:

* they can have different values in our application - eg. something that can be a boolean or an object
* the value has changed over time (eg. an integer has become a float)

It looks like when extracting the data out of the JSON blobs it always try to cast the result as what it detected in the 'original schema'. Even if the actual DB field is set not to cast.

**Logs**

For our table (load_count_cycles), if I try and open it directly I get this page:

![image](https://user-images.githubusercontent.com/641520/193481919-61c32785-2b04-42f1-8c24-a0d350df3a15.png)

If I change the sort I can get this error instead:

![image](https://user-images.githubusercontent.com/641520/193482059-59e1697c-fdc3-424a-bb37-d49f8ef849a8.png)

Which relates to a value of 'dumped_at` in one of blobs, which has no value of casted:

![image](https://user-images.githubusercontent.com/641520/193482128-0d02d519-d789-4304-8391-837f5c478fa2.png)

In the original schema it was detected as an integer, which makes me think it is actually being casted based on the original detected value?

![image](https://user-images.githubusercontent.com/641520/193482138-901966a7-f4f1-4374-82cd-9034b21cf760.png)

**To Reproduce**

We have this issue many of our tables, so presumably it will happen for any mixed type json values in a postgres database.

**Expected behavior**
I expect to be able to see my table.

If it is limited to a single type, I would also be expect to be able to manage this type. It seems to detect one 'at random' (two different DBs have detected different types for the same field). 

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "4.14.287-215.504.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Australia/Sydney"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": "Australia/Sydney"
    }
  }
}
```

**Severity**

This is currently blocking our upgrade to 0.44, since many of tables do not work anymore. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @kbrownlees 
You should disable JSON unfolding in Admin > Databases > (db) > Show advanced options > disable "Unfold JSON columns", click "Save changes", then click "Sync database schema now".
It would become quite difficult to handle mixed columns, so we will likely end up excluding them.
Metabase tries to detect the attribute type during sync and fingerprinting, which only goes through the first 500 rows.

**Comment by kbrownlees** [comment]
@qnkhuat thats for the update! That will be very useful and solve some of our issues.

A toggle which allows you set a type for the field is probably the other missing piece here for us. I managed to fix a few issues by hacking around in the DB and updating the types, but that is not really managable.

**Comment by camsaul** [comment]
We implemented something similar for MongoDB in https://github.com/metabase/metabase/issues/27045 and https://github.com/metabase/metabase/pull/27838

**Comment by qnkhuat** [comment]
sample 250 first rows + 250 last rows for json columns is implemented in https://github.com/metabase/metabase/pull/32215
