### ISSUE TITLE
Scheduled (cached) Reports

### ISSUE THREAD

**Issue by kotso** [metabase/metabase#2575]
Is there any way to make scheduled question?

I have very big database (around 20GB with lots of user and transaction data) and generating some queries that take more then 10-15 min per execution but I need them on daily bases (for example analyze past 7,14,30 days)

If Metabase does not support it it would be excellent feature request I guess.

**Comment by agilliland** [comment]
Check out Pulses http://www.metabase.com/docs/v0.17.0/users-guide/07-pulses.html

**Comment by tlrobinson** [comment]
Duplicate of #1666?

**Comment by salsakran** [comment]
@kotso when you say scheduled reports do you mean sending a report out (aka Pulses) every night? Or precomputing expensive queries?

If the latter, have you looked into materialized views?

**Comment by kotso** [comment]
@salsakran I mean precomputing expensive queries.

**Comment by camsaul** [comment]
Closing as duplicate of #1666

**Comment by salsakran** [comment]
this isn't quite the same as #1666 . 

What @kotso is describing is a pre-computation, not a caching. Not sure it's in scope, but it's different at least =)

**Comment by camsaul** [comment]
if you compute it once and then *cache* the results for later...

**Comment by flamber** [comment]
Related to #4967

**Comment by flamber** [comment]
Closing in favor of #4967, which has a lot more upvotes.
There's more advanced caching options in 0.41: https://www.metabase.com/docs/latest/enterprise-guide/cache.html
