### ISSUE TITLE
Dropdown filters will be empty if a table in BigQuery is requiring a filter on the partitioning field

### ISSUE THREAD

**Issue by marcoruggine** [metabase/metabase#25752]
**Describe the bug**
We need to impose filters on partitioning columns otherwise our costs are sky-rocketing.
Unfortunately, after running some deep debugging using Google Audit Logs, we have discovered that Metabase when scanning a field to create 'A list of all values' is not optimized at all:
1. If the table requires a partitioning filter, Metabase won't pass it and the query will result in a fail
2. The query itself is not optimized at all because it sets a LIMIT 1000 that actually in BigQuery is totally useless
3. The query itself is wasting a lot of resources because is using an unnecessary ORDER BY

This is the error as shown in Google Audit Logs
`Cannot query over table '03_final_models.model_registrations' without a filter over column(s) 'start_date' that can be used for partition elimination`

and this is the query that Metabase ran as part of the job
`SELECT `03_final_models.model_registrations`.`visibility` AS `visibility` FROM `03_final_models.model_registrations` GROUP BY `visibility` ORDER BY `visibility` ASC LIMIT 1000`

**Comment by flamber** [comment]
Until #5904 is supported, then you'll be hitting #14490 and #19470.
See https://github.com/metabase/metabase/issues/5904#issuecomment-1048386825 for workaround.
Or disable scans https://www.metabase.com/docs/latest/databases/connecting#choose-when-metabase-syncs-and-scans

**Comment by luizarakaki** [comment]
@marcoruggine What would be a good approach in this case? The list of all values should have all values, we shouldn't filter the result set. Should we add a filter like `partition_time > 1900-01-01`?

**Comment by marcoruggine** [comment]
@luizarakaki I'm so sorry for the late reply, I missed your message.

In our case, the best scenario would be to have the following config options from Metabase Admin UI:

- Possibility to identify the partitioning column and prevent any type of query without a filter being applied on it
- Possibility to set a default filter for Metabase scanning, in either forms: `partition_time > 0001-01-01 00:00:00` or `partition_time >= timestamp_sub(current_date, {{INTERVAL}})` where it its possible to specify something like "past 12 months"
- Possibility to set a default filter for Users questions created from the editor. Eg: default = "yesterday"

The last one is very important because, no matter how hard you try, users will always run a preliminary query that pulls up the table to see what's inside and then decide how to aggregate / slice / dice. 
Or, even if already creating aggregates with the editor, simply to check if the result corresponds to expectations.

By applying a default filter that considers a very small period, we can move from 100GBs to < 1 MB queries
