### ISSUE TITLE
The values is repeated two times in the date feature

### ISSUE THREAD

**Issue by Chrissroman** [metabase/metabase#25786]
**Describe the bug**
For a side, the data is grouped correctly (table), for the other side, when I graphic in the X Axis, the date of 2 october is repeated 2 times

**Screenshots**
![example 1](https://user-images.githubusercontent.com/66497502/193912074-1936c9aa-a422-4465-9882-f73275c9ab45.jpg)
![example 2](https://user-images.githubusercontent.com/66497502/193912179-ff848cc8-9a5e-4c13-be06-ec9be9f7335e.jpg)

**Comment by flamber** [comment]
https://discourse.metabase.com/t/date-for-day-in-x-axis/22116
