### ISSUE TITLE
Error loading shared library with DuckDB driver

### ISSUE THREAD

**Issue by seajhawk** [metabase/metabase#25789]
**Describe the bug**
Opening issue per @flamber in this thread which has more details: https://discourse.metabase.com/t/duckdb-support/20092/2

I'm trying to use the DuckDB driver but running into issues.
I'm running in a linux docker container.
I've tried with a single duckdb file, and I've tried with no file specified.

Both return this error in the UI:
![image](https://user-images.githubusercontent.com/18316676/193950948-4ae27128-53dc-4d6f-9121-76c24fa4cf82.png)

**Logs**
`[b44c25d9-af89-4e2d-b840-64218b2c0d0c] 2022-09-28T16:32:33-07:00 DEBUG metabase.server.middleware.log POST /api/database 400 1.6 s (0 DB calls) {:message "/tmp/libduckdb_java16810484802722090474.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libduckdb_java16810484802722090474.so)"}`

**To Reproduce**
1. Install the DuckDB driver with Metabase in a docker container per https://github.com//AlexR2D2/metabase_duckdb_driver
2. Connect to a new DuckDB database (can be just a folder path)
3. See error

**Expected behavior**
I expect Metabase to connect to the DuckDB database and allow me to query it.

**Information about your Metabase Installation:**
- Your browser and the version: Microsoft Edge Version 106.0.1370.34 (Official build) (64-bit)
- Your operating system: Windows 11 22H2
- Your databases: DuckDB
- Metabase version: v0.44.4
- Metabase hosting environment: Local Docker
- Metabase internal database: H2

**Severity**
This is a complete blocker on moving my Metabase-based solution from incubation to the next phase. I'm building a free solution to be used by non-tech folks as cheaply and easily as possible. I need the simplicity and performance of DuckDB and its columnar data storage so I can provide both Metabase and the database in a single performant container.

I have a number of folks who are already using the solution, but currently it's Postgres-based and it's too expensive for them to run hosted Postgres and they are not technical enough to install and manage their own Postgres server.

**Additional context**

**Comment by flamber** [comment]
You need to open the issue in https://github.com//AlexR2D2/metabase_duckdb_driver
