### ISSUE TITLE
MariaDB Support (note: this is already supported, just use "MySQL")

### ISSUE THREAD

**Issue by rNianios** [metabase/metabase#2581]
Is there any chance that you will add support for MariaDB? As we know MariaDB is a cousin if not sister RDB to MySQL, so I don't believe it would be so much of a work to add it. From the other hand I don't know your backend so my previous statement may be wrong. 

Anyway is there any chance to add it?

Google and other big companies have moved to MariaDB as well.

http://www.theregister.co.uk/2013/09/12/google_mariadb_mysql_migration/

Thanks for your time,

Romanos

**Comment by agilliland** [comment]
Have you tried just adding the db as a MySQL database in Metabase?  it's likely that will work.

**Comment by rNianios** [comment]
No I haven't to be honest, I don't have a MariaDB yet(!) but I am looking to transfer/create a few and I was wondering if Metabase was going to support MariaDB.

**Comment by marketingnerds** [comment]
I'm using MariaDB with Database Type set to MySQL on AWS RDS ... no issues.

**Comment by rNianios** [comment]
Thanks for confirming, I guess my ticket can be closed!

On 12 May 2016 at 14:24, Gilbert <notifications@github.com> wrote:

> I'm using MariaDB with Database Type set to MySQL on AWS RDS ... no issues.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/metabase/metabase/issues/2581#issuecomment-218755741>
>



-- 
Με εκτίμηση, / Yours,

Νιάνιος Ρωμανός / Nianios Romanos
 http://romanos.nianios.gr

**Comment by salsakran** [comment]
As per @agilliland 's suggestion, to reduce the chances of confusion, we should probably add an entry for MariaDB's but use MySQL under the hood. It's meant to be driver compatible, but not everyone knows that.

**Comment by camsaul** [comment]
I would just vote we change the driver's nice name to "MySQL / MariaDB". That way if somebody switches their DB from one to the other they don't need to reconfigure the DB in the admin panel

**Comment by camsaul** [comment]
AWS now supports Maria [Carey] DB on RDS so maybe we should seriously consider the PR submitted by @MrMauricioLeite https://aws.amazon.com/about-aws/whats-new/2016/06/amazon-rds-now-supports-mariadb-10-1/. That seems like a good solution for the time being.

**Comment by agilliland** [comment]
I'm still of the opinion that the better solution is to create a driver for MariaDB which is separate from MySQL but shares the same implementation.

**Comment by joshuashort** [comment]
I get the following error when I try to use MariaDB (with a mariadb:latest Docker container) as the backend for Metabase (but it works with mysql:latest and postgres:latest):

```
sign-metabase-app | com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows INT NULL, description TEXT NULL, entity_name VARCHAR(254) NULL, entity_type' at line 1
sign-metabase-app | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sign-metabase-app | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sign-metabase-app | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
sign-metabase-app | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
sign-metabase-app | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
sign-metabase-app | 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
sign-metabase-app | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
sign-metabase-app | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
sign-metabase-app | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
sign-metabase-app | 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
sign-metabase-app | 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
sign-metabase-app | 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
sign-metabase-app | 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
sign-metabase-app | 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
sign-metabase-app | 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
sign-metabase-app | 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
sign-metabase-app | 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
sign-metabase-app | 	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__10865.invoke(jdbc.clj:784)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
sign-metabase-app | 	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:783)
sign-metabase-app | 	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
sign-metabase-app | 	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
sign-metabase-app | 	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
sign-metabase-app | 	at clojure.java.jdbc$execute_BANG_$execute_helper__10908.invoke(jdbc.clj:961)
sign-metabase-app | 	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:963)
sign-metabase-app | 	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:943)
sign-metabase-app | 	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:954)
sign-metabase-app | 	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:943)
sign-metabase-app | 	at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:164)
sign-metabase-app | 	at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:151)
sign-metabase-app | 	at metabase.db$migrate_BANG_$fn__19440.invoke(db.clj:247)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:629)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
sign-metabase-app | 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
sign-metabase-app | 	at metabase.db$migrate_BANG_.invokeStatic(db.clj:235)
sign-metabase-app | 	at metabase.db$migrate_BANG_.invoke(db.clj:218)
sign-metabase-app | 	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:365)
sign-metabase-app | 	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:360)
sign-metabase-app | 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:383)
sign-metabase-app | 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
sign-metabase-app | 	at clojure.lang.RestFn.invoke(RestFn.java:421)
sign-metabase-app | 	at metabase.core$init_BANG_.invokeStatic(core.clj:103)
sign-metabase-app | 	at metabase.core$init_BANG_.invoke(core.clj:82)
sign-metabase-app | 	at metabase.core$start_normally.invokeStatic(core.clj:187)
sign-metabase-app | 	at metabase.core$start_normally.invoke(core.clj:181)
sign-metabase-app | 	at metabase.core$_main.invokeStatic(core.clj:279)
sign-metabase-app | 	at metabase.core$_main.doInvoke(core.clj:274)
sign-metabase-app | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
sign-metabase-app | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
sign-metabase-app | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
sign-metabase-app | 	at metabase.core.main(Unknown Source)
sign-metabase-app | 07-12 06:47:07 ERROR metabase.core :: Metabase Initialization FAILED:  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows INT NULL, description TEXT NULL, entity_name VARCHAR(254) NULL, entity_type' at line 1
```

**Comment by camsaul** [comment]
@joshuashort does anything look wrong about that SQL statement to you? Or do you know of any breaking changes to MariaDB that break compatibility with MySQL?

**Comment by joshuashort** [comment]
I don't know what statement it's trying to execute, but what stands out about the fragment at the end of the error message is that `entity_type` doesn't have a field type like the rest do; I'm not sure if it's just a truncated view, or what. As far as I know, the basics between MariaDB and MySQL should work..

How can I find out more about what's being executed?

**Comment by bmoore29** [comment]
Sorry for tagging an old thread, but I think Joshua's problem is that the word "ROWS" became a reserved keyword in MariaDB 10.2.4, so the CREATE TABLE statement is failing:

```
CREATE TABLE metabase.metabase_table(
  id            INT AUTO_INCREMENT NOT NULL,
  created_at    datetime NOT NULL,
  updated_at    datetime NOT NULL,
  name          VARCHAR(254) NOT NULL,
  rows          INT NULL,
  description   TEXT NULL,
  entity_name   VARCHAR(254) NULL,
  entity_type   VARCHAR(254) NULL,
  active        BIT(1) NOT NULL,
  db_id         INT NOT NULL,
  CONSTRAINT PK_METABASE_TABLE PRIMARY KEY(id),
  CONSTRAINT fk_table_ref_database_id FOREIGN KEY
    (db_id)
     REFERENCES metabase.metabase_database(id));
```

What I did was set MB_DB_AUTOMIGRATE=false, which dumped the SQL script out, then I put backticks around the column in the CREATE statement and an ALTER statement further down in the script:

```
CREATE TABLE metabase.metabase_table(
  id            INT AUTO_INCREMENT NOT NULL,
  created_at    datetime NOT NULL,
  updated_at    datetime NOT NULL,
  name          VARCHAR(254) NOT NULL,
  `rows`        INT NULL,
  description   TEXT NULL,
  entity_name   VARCHAR(254) NULL,
  entity_type   VARCHAR(254) NULL,
  active        BIT(1) NOT NULL,
  db_id         INT NOT NULL,
  CONSTRAINT PK_METABASE_TABLE PRIMARY KEY(id),
  CONSTRAINT fk_table_ref_database_id FOREIGN KEY
    (db_id)
     REFERENCES metabase.metabase_database(id));

--  Changeset migrations/000_migrations.yaml::23::agilliland
ALTER TABLE metabase.metabase_table MODIFY `rows` BIGINT;
```

Then I restarted normally.  I'm still crunching through my metadata gathering, but it appears to be working without an issue at the moment.

**Comment by joshuashort** [comment]
Awesome insight @bmoore29! I ended up going with a Postgres database, but it'd still be nice to get this working for both MySQL/MariaDB.

Maybe the generated SQL should use quoted identifiers? Maybe `rows` should be `row_count`?

And what's with the `ALTER` statement you're using? `INT` doesn't work?

**Comment by bmoore29** [comment]
> Maybe the generated SQL should use quoted identifiers? Maybe rows should be row_count?

I would guess either would be the appropriate change, but only someone smarter than me knows the downstream implications of that.

> And what's with the ALTER statement you're using? INT doesn't work?

I was just working with the script that Metabase gave me.  I'm assuming it's the accumulated set of database upgrades to bring the system to current standing given I was starting from a fresh install.

**Comment by joshuashort** [comment]
Oh, I see -- the `ALTER` statement was generated as part of a migration and you quoted it because of the database system 'feature' of reserving `ROWS`.

**Comment by camsaul** [comment]
We've supported MariaDB for a while now so I'm going to go ahead and close this out
