### ISSUE TITLE
Connection reset by peer (Write failed)

### ISSUE THREAD

**Issue by luciangruiaro** [metabase/metabase#25866]
**Describe the bug**
After migrating to MySQL from H2, I sometimes, randomly encounter this issue.
`Connection reset by peer (Write failed)`

I did not observe any pattern - sometimes happens when I create a query, other times suddenly when I do nothing. 

**Logs**
`[b933a1f0-9a34-446a-b958-863cd0516190] 2022-10-10T21:58:04+03:00 ERROR metabase.server.middleware.log GET /api/activity/recent_views 500 7.6 ms (1 DB calls) 
{:via
 [{:type java.sql.SQLNonTransientConnectionException,
   :message "(conn=3095) Connection reset by peer (Write failed)",
   :at [org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory createException "ExceptionFactory.java" 73]}
  {:type org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException,
   :message "Connection reset by peer (Write failed)",
   :at [org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException of "MariaDbSqlException.java" 34]}
  {:type java.sql.SQLNonTransientConnectionException,
   :message "Connection reset by peer (Write failed)",
   :at [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol handleIoException "AbstractQueryProtocol.java" 2091]}
  {:type java.net.SocketException,
   :message "Connection reset by peer (Write failed)",
   :at [java.net.SocketOutputStream socketWrite0 nil -2]}],
 :trace
 [[java.net.SocketOutputStream socketWrite0 nil -2]
  [java.net.SocketOutputStream socketWrite nil -1]
  [java.net.SocketOutputStream write nil -1]
  [org.mariadb.jdbc.internal.io.output.StandardPacketOutputStream flushBuffer "StandardPacketOutputStream.java" 111]
  [org.mariadb.jdbc.internal.io.output.AbstractPacketOutputStream flush "AbstractPacketOutputStream.java" 186]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol executeQuery "AbstractQueryProtocol.java" 316]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeInternal "ClientSidePreparedStatement.java" 220]
  [org.mariadb.jdbc.ClientSidePreparedStatement execute "ClientSidePreparedStatement.java" 149]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeQuery "ClientSidePreparedStatement.java" 163]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeQuery "NewProxyPreparedStatement.java" 1471]
  [clojure.java.jdbc$execute_query_with_params invokeStatic "jdbc.clj" 1090]
  [clojure.java.jdbc$execute_query_with_params invoke "jdbc.clj" 1084]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invokeStatic "jdbc.clj" 1113]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invoke "jdbc.clj" 1093]
  [clojure.java.jdbc$query invokeStatic "jdbc.clj" 1182]
  [clojure.java.jdbc$query invoke "jdbc.clj" 1144]
  [toucan.db$query invokeStatic "db.clj" 308]
  [toucan.db$query doInvoke "db.clj" 304]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [toucan.db$simple_select invokeStatic "db.clj" 414]
  [toucan.db$simple_select invoke "db.clj" 403]
  [toucan.db$select invokeStatic "db.clj" 708]
  [toucan.db$select doInvoke "db.clj" 702]
  [clojure.lang.RestFn invoke "RestFn.java" 423]
  [metabase.api.activity$views_and_runs invokeStatic "activity.clj" 146]
  [metabase.api.activity$views_and_runs invoke "activity.clj" 134]
  [metabase.api.activity$fn__78707 invokeStatic "activity.clj" 185]
  [metabase.api.activity$fn__78707 invoke "activity.clj" 182]
  [compojure.core$wrap_response$fn__28102 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__28086 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__28091 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 151]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__68961 invoke "auth.clj" 14]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28142 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 299]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [metabase.api.routes$fn__79946$fn__79949 invoke "routes.clj" 60]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__80101$fn__80102 doInvoke "routes.clj" 67]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28142 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28146 invoke "core.clj" 299]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28095 invoke "core.clj" 152]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114$f__28115$respond_SINGLEQUOTE___28116 invoke "core.clj" 197]
  [metabase.server.routes$fn__80087$fn__80089 invoke "routes.clj" 45]
  [compojure.core$routes$fn__28114$f__28115 invoke "core.clj" 198]
  [compojure.core$routes$fn__28114 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__76838 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__76835 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__81513$fn__81514$fn__81515 invoke "log.clj" 211]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__81513$fn__81514 invoke "log.clj" 203]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 236]
  [toucan.db$_do_with_call_counting invoke "db.clj" 229]
  [metabase.server.middleware.log$log_api_call$fn__81513 invoke "log.clj" 202]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__84613 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__62353 invoke "security.clj" 149]
  [metabase.server.middleware.json$wrap_json_body$fn__83571 invoke "json.clj" 63]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__83589 invoke "json.clj" 99]
  [metabase.server.middleware.offset_paging$handle_paging$fn__62377 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__84880 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__84899 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35782 invoke "misc.clj" 59]
  [metabase.server.middleware.session$reset_session_timeout$fn__47474 invoke "session.clj" 377]
  [metabase.server.middleware.session$bind_current_user$fn__47457$fn__47458 invoke "session.clj" 313]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 292]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 281]
  [metabase.server.middleware.session$bind_current_user$fn__47457 invoke "session.clj" 312]
  [metabase.server.middleware.session$wrap_current_user_info$fn__47439 invoke "session.clj" 262]
  [metabase.server.middleware.session$wrap_session_id$fn__47423 invoke "session.clj" 195]
  [metabase.server.middleware.auth$wrap_api_key$fn__68969 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__84800 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35765 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35790 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__84842 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35793 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__84629 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__80309 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 181]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 487]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 732]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 479]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 409]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run nil -1]],
 :cause "Connection reset by peer (Write failed)",
 :message "(conn=3095) Connection reset by peer (Write failed)",
 :sql-exception-chain
 ["SQLNonTransientConnectionException:"
  "Message: (conn=3095) Connection reset by peer (Write failed)"
  "SQLState: 08000"
  "Error Code: 0"]}`

**To Reproduce**
Happens randomly and suddenly. Sometimes after a longer period, other times after few moments.

**Expected behavior**
The app should work smoothly as with H2.

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.45.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.3.36-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

- Your browser and the version: (Chrome Version 105.0.5195.127 (Official Build) (64-bit))
- Your operating system: (Windows 10 Pro)
- Your databases: (MariaDB 10.3)
- Metabase version: (v0.44.4)
- Metabase hosting environment: (CentOS - Docker)
- Metabase internal database: (MariaDB)

**Severity**
I am currently not sure if I can rely on creating stats for my app using Metabase, because of this issue related to write to DB.

**Comment by flamber** [comment]
Hi @luciangruiaro 
The error is coming from your MariaDB server or the network connection between Metabase and MariaDB, not Metabase itself.
https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean
There's many thousands of Metabase running without errors, so this is very likely something specific to your setup.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by flamber** [comment]
@luciangruiaro I don't know if your MariaDB is using non-default timeouts, since I've never seen this error before, and there are many many thousands of Metabase installations. Otherwise try with Postgres instead.
Check your session variables `show variables where variable_name like '%timeout%'`
You can set connection parameters in Metabase Admin > Databases > (db) > Show advanced options > Additional JDBC connection string, example: `sessionVariables=wait_timeout=12345`
