### ISSUE TITLE
Area graph stacked in dashboard subscription email but unstacked in question

### ISSUE THREAD

**Issue by Rmonik** [metabase/metabase#25896]
**Describe the bug**
A question that is sent in email by a daily dashboard subscription is shown differently in the email. The email's version shows both data sets stacked, whereas the actual question is configured unstacked.

**Logs**
[metabaseissue12oct.txt](https://github.com/metabase/metabase/files/9765947/metabaseissue12oct.txt)

**To Reproduce**
1. Create a line graph with two lines
2. Add it to a dashboard
3. Create a dashboard subscription email

**Expected behavior**
The graph should be displayed according to the same configuration as the question

**Screenshots**

<img width="583" alt="Screenshot 2022-10-12 at 09 01 31" src="https://user-images.githubusercontent.com/16976971/195365397-bd2f4efd-0ec5-462d-9a08-567f9b838466.png">
<img width="689" alt="Screenshot 2022-10-12 at 09 01 12" src="https://user-images.githubusercontent.com/16976971/195365399-0dabcc65-276b-4c23-b26a-cd158fbf8e95.png">
In other cases, it displays correctly, but it changes the Y-axis scale for one of the series to the right:
<img width="587" alt="Screenshot 2022-10-12 at 16 34 58" src="https://user-images.githubusercontent.com/16976971/195371892-438f5f7a-ed7e-4bee-8af1-99eca780702f.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …) n/a
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …) n/a
- Your databases: MySQL
- Metabase version: (e.g., 0.19.3) 0.44.2
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
Medium -- This query is rendered useless in the email, so the user needs to open the dashboard every time. (the question takes a few minutes to run, so this is suboptimal)

**Additional context**

**Comment by flamber** [comment]
I have no idea how you're getting a stacked visualization, since that is not supported #23743 #20752. The two Y-axis is #20559.

I'm not able to reproduce what you're seeing. Can you include the question by going to the URL `/api/card/123`, where 123 is the question ID of "Evolution of hours per week"?

**Comment by Rmonik** [comment]
Hi @flamber 
The result of this is the following:
`{"description":null,"archived":false,"collection_position":null,"table_id":null,"result_metadata":[{"display_name":"Week","field_ref":["field","Week",{"base-type":"type/Date"}],"name":"Week","base_type":"type/Date","effective_type":"type/Date","semantic_type":null,"fingerprint":{"global":{"distinct-count":19,"nil%":0.0},"type":{"type/DateTime":{"earliest":"2022-05-23T00:00:00+02:00","latest":"2022-10-03T00:00:00+02:00"}}}},{"display_name":"Hours","field_ref":["field","Hours",{"base-type":"type/Decimal"}],"name":"Hours","base_type":"type/Decimal","effective_type":"type/Decimal","semantic_type":null,"fingerprint":{"global":{"distinct-count":19,"nil%":0.0},"type":{"type/Number":{"min":877.2,"q1":1003.625,"q3":1979.2,"max":2872.2,"sd":569.8437478972143,"avg":1537.4578947368423}}}},{"display_name":"Last Year","field_ref":["field","Last Year",{"base-type":"type/Decimal"}],"name":"Last Year","base_type":"type/Decimal","effective_type":"type/Decimal","semantic_type":null,"fingerprint":{"global":{"distinct-count":19,"nil%":0.0},"type":{"type/Number":{"min":3.0,"q1":125.15,"q3":255.4,"max":378.3,"sd":98.87631472721405,"avg":182.16842105263157}}}},{"display_name":"Change from last year","field_ref":["field","Change from last year",{"base-type":"type/Decimal"}],"name":"Change from last year","base_type":"type/Decimal","effective_type":"type/Decimal","semantic_type":null,"fingerprint":{"global":{"distinct-count":19,"nil%":0.0},"type":{"type/Number":{"min":1.76334,"q1":4.4716325,"q3":12.43224,"max":678.76667,"sd":155.28906642705766,"avg":49.770920526315784}}}}],"creator":{"email":"milan@nowjobs.com","first_name":"Milan","last_login":"2022-09-30T16:33:13","is_qbnewb":false,"is_superuser":true,"id":83,"last_name":"Claeys","date_joined":"2019-10-01T17:19:48","common_name":"Milan Claeys"},"can_write":true,"database_id":2,"enable_embedding":false,"collection_id":1438,"query_type":"native","name":"Evolution of hours per week","last_query_start":"2022-10-14T04:31:03.629228Z","dashboard_count":5,"average_query_time":31922.4579,"creator_id":83,"moderation_reviews":[],"updated_at":"2022-10-14T06:31:14","made_public_by_id":null,"embedding_params":null,"cache_ttl":null,"dataset_query":{"database":2,"native":{"template-tags":{"cntry":{"id":"aa11f6c4-9c4e-530f-f7bd-8fdf5fb62fac","name":"cntry","display-name":"Country","type":"dimension","dimension":["field",2190,null],"widget-type":"category"}},"query":"select\n    hnow.Week,\n    hnow.Hours,\n    hlastyear.Hours as \"Last Year\",\n    (hnow.Hours / hlastyear.Hours - 1) as \"Change from last year\"\n\nfrom \n(select\n    hires.at - interval weekday(hires.at) day as Week,\n    -- users.country as Country,\n    round(ifnull(sum(durationParts(hires.parts)),0)/60,1) as Hours \nfrom hires\njoin negotiations on negotiations.id = hires.negotiation \njoin users on hires.customer = users.id [[and {{cntry}}]]\nwhere \n    negotiations.status = 'A' \n    and hires.at >= now() - interval 1 year\n    and hires.at < date(now() - interval weekday(now()) day)\ngroup by Week -- , Country\norder by Week) hnow\njoin (select\n    hires.at - interval weekday(hires.at) day as Week,\n    -- users.country as Country,\n    round(ifnull(sum(durationParts(hires.parts)),0)/60,1) as Hours \nfrom hires\njoin negotiations on negotiations.id = hires.negotiation \njoin users on hires.customer = users.id [[and {{cntry}}]]\nwhere \n    negotiations.status = 'A' \n    and hires.at >= now() - interval 2 year\n    and hires.at < now() - interval 1 year\n    and hires.at < date(now() - interval weekday(now()) day)\ngroup by Week -- , Country\norder by Week) hlastyear on yearweek(hlastyear.Week, 3) = yearweek(hnow.Week - interval 1 year, 3)"},"type":"native"},"id":5406,"parameter_mappings":null,"display":"line","entity_id":null,"collection_preview":true,"last-edit-info":{"id":83,"email":"milan@nowjobs.com","first_name":"Milan","last_name":"Claeys","timestamp":"2022-10-10T07:59:32Z"},"visualization_settings":{"graph.show_values":true,"graph.x_axis.labels_enabled":true,"table.cell_column":"forecasted hours","graph.y_axis.max":2,"graph.x_axis.axis_enabled":true,"stackable.stack_display":"area","graph.y_axis.auto_split":true,"graph.label_value_frequency":"fit","graph.metrics":["Hours","Last Year"],"graph.y_axis.axis_enabled":true,"table.column_formatting":[{"columns":["Gain/Loss"],"type":"single","operator":"<","value":0,"color":"#EF8C8C","highlight_row":true},{"columns":["Gain/Loss"],"type":"single","operator":">=","value":0,"color":"#88BF4D","highlight_row":true}],"graph.label_value_formatting":"compact","table.pivot_column":"Joint Committeee","column_settings":{"[\"name\",\"Gain/Loss\"]":{"number_style":"percent"},"[\"name\",\"Change from last year\"]":{"number_style":"percent"}},"series_settings":{"BE":{"line.marker_enabled":false,"color":"#509EE3","display":"area"},"NL":{"line.marker_enabled":false},"FR":{"line.marker_enabled":false},"Hours":{"line.marker_enabled":false,"display":"area","axis":"left","color":"#509EE3"},"Last Year":{"display":"area","axis":"left","line.marker_enabled":false,"color":"#F7C4C4","show_series_values":false},"Change from last year":{"axis":"right","color":"#A7D07C"}},"graph.y_axis.auto_range":true,"graph.dimensions":["Week"],"stackable.stack_type":"stacked","graph.y_axis.min":0},"collection":{"authority_level":null,"description":"All questions that are on the pinned hours forecast","archived":false,"slug":"dashboard_questions____hours_forecast","color":"#509EE3","name":"Dashboard questions -- Hours forecast","personal_owner_id":null,"id":1438,"entity_id":null,"location":"/586/","namespace":null},"parameters":[{"id":"aa11f6c4-9c4e-530f-f7bd-8fdf5fb62fac","type":"category","target":["dimension",["template-tag","cntry"]],"name":"Country","slug":"cntry"}],"dataset":false,"created_at":"2022-01-14T12:22:34","public_uuid":null}`

**Comment by flamber** [comment]
So this is caused by the slightly confusing visualization_settings that can be applied. So the chart is Line, but each series are area and there's also some stacking settings, because the viz was an Area at one point.

Workaround: Changing to a Area visualization (without stacking) will show the same in Metabase and static viz.

Reproduce:
1. Question > Sample > Orders
2. Summarize "Sum of Quantity" and "Sum of Discount", grouped by CreatedAt:Year
3. Change viz to Area, in settings Display > manually change to "Don't stack" and back to "Stack" (this is to store settings)
![image](https://user-images.githubusercontent.com/1447303/195843338-e25ff171-3ec5-4d66-bcc9-e93942e9bc5f.png)
4. Change viz to Line, in settings Display > change each series to Area - save question
![image](https://user-images.githubusercontent.com/1447303/195843129-462bbad3-e8c6-421d-ac15-dd20b91bb4d3.png)
5. Static viz will look like this
![image](https://user-images.githubusercontent.com/1447303/195843258-32bb818f-5591-4914-ba4a-507742f527b2.png)

Related to #10790

**Comment by Rmonik** [comment]
@flamber Nice! Changing it to an actual area graph did fix the stacking issue, however the Y-axis is still split as described in #20559 

Is there any workaround for this?

**Comment by flamber** [comment]
@Rmonik No, otherwise I try to write that in the issues I create.
