### ISSUE TITLE
Column must appear in the GROUP BY clause or be used in an aggregate function, when trying to build a custom column on aggregated metrics

### ISSUE THREAD

**Issue by Eliagandolfi** [metabase/metabase#25899]
**Describe the bug**
Whenever I try to create a custom column using two aggregated metrics, I keep having the error
_Column must appear in the GROUP BY clause or be used in an aggregate function_

**Example**
I want to know which % of clients are women, by country. From the client table
1. I create a custom column with 0=man, 1=woman
2. I summarize by country, and aggregate by count of rows (all clients) and sum of women
3. I build a custom colum "% women" = sum of women / count 
4. When visualizing, I got the above error

**Expected behavior**
A column indicating the %

**Screenshot**
<img width="580" alt="Screenshot 2022-10-12 at 16 37 12" src="https://user-images.githubusercontent.com/47365996/195399669-d7bb6b9c-f7c1-40e4-b8e2-840bf7fe3915.png">

<img width="680" alt="Screenshot 2022-10-12 at 16 37 01" src="https://user-images.githubusercontent.com/47365996/195399709-fcab46ba-7fea-43d6-a675-c0b59a54c098.png">

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.14.281-212.502.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Upgrade to a newer release: https://github.com/metabase/metabase/releases/latest
