### ISSUE TITLE
Option to limit tables/fields that are synced to specific schemas

### ISSUE THREAD

**Issue by parkotron** [metabase/metabase#2591]
We're working on a relatively small system in redshift that uses a shared redshift cluster. There are lots of schemas most of which are not ours (and we don't have permission to read) but our local postgres is becoming unnecessarily heavy due to the automatic caching of fields in all schemas into metabase_field (it would likely be a few hundred rows, but is getting towards a hundred thousand).

A possible enhancement would be to have the option to limit field caching to schemas that have been viewed rather than crawling all schemas up front.

**Comment by rafaelveloso** [comment]
Being able to configure which schemas we want to be scanned by metabase would be very helpful. In PostgreSQL we can define permissions per schemas but that doesn't prevent any role from seeing all schemas tables structure. If we have multiple schemas in one database and create a specific role (to be used by metabase) with read permissions in one schema, it won't be able to pull data from any schema other then the one it has permissions to, but metabase will still sync metadata for all of them.

**Comment by MrMauricioLeite** [comment]
Same problem here. Our redshift schemas show up but I can only run querys on my schema.

Other thing that sucks is that all those schemas have lots of tables and we have to hide one by one, since there is no "Hide All" option anywere.

**Comment by robinfrick** [comment]
+1 this would be taking #2086 a step further. For me hiding would already be a great step forward. Completely disabling the syncing of the schema is even better 👍

**Comment by justin-yan** [comment]
Would love to see this as well.  We create a new schema when we load data into our warehouse so that we can atomically publish the new day's data all at once by doing an `ALTER SCHEMA RENAME TO`.  We then keep the old schemas around for a few days with a date suffixed so that we have an audit trail in case some changes result in unexpected data errors.

Hiding would actually not solve our problem, since each audit schema has a unique suffix, but being able to limit imports to specific schema names would be a big usability win for us!

**Comment by chandraonline** [comment]
I found it under Databases and it was turned on already.

![image](https://cloud.githubusercontent.com/assets/933276/24118826/636046b6-0d6c-11e7-82fb-c05b17839b0d.png)

**Comment by toybaelescione** [comment]
An option to pick which schema to be scanned by metabase will be very helpful for us as well. We have Oracle for our Data Warehouse and we have hundreds of schema and hundred thousands of tables, and not tables are used for analysis.

**Comment by camsaul** [comment]
Fixed by #10139
