### ISSUE TITLE
Avoid updating dashboard cards unless filter changes

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#25914]
**Describe the bug**
Continuation of #8030. Avoid updating dashboard cards unless filter changes.
Important that the behavior in-app dashboard is also reflected on Public and Embedding, so it doesn't divert in behavior.

**To Reproduce**
1. Question > Sample > Orders - summarize by Count - save as "Q1"
2. Add "Q1" three times to a dashboard, then add two filters and connect first filter to first card, second filter to second card
![image](https://user-images.githubusercontent.com/1447303/195640061-04984906-6f0d-4bec-ad00-7ffb067e184d.png)
3. Set a value in first filter, only first card is updated - as expected
4. Set a value in second filter (while there's a value in first filter), now both first and second card is updated - instead of just the second card

https://user-images.githubusercontent.com/1447303/195641046-cb9c37bd-8606-4b2f-b995-dae2962ab5e8.mp4

**Information about your Metabase Installation:**
Tested 0.44.4

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mhkarimi1383** [comment]
Same here...

**Comment by gusaiani** [comment]
Fixed by #27490
