### ISSUE TITLE
Mongo failed to connect over SSL

### ISSUE THREAD

**Issue by maximecorbeau** [metabase/metabase#2592]
I'm running the Metebase setup, and when at step 2 (Add your data), connection to `MongoDB` fails with the below error:

`05-12 13:15:54 ERROR metabase.driver :: Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='admin', source='github', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }}}]
05-12 13:16:30 ERROR metabase.driver :: Failed to connect to database: java.lang.IllegalArgumentException: Password can not be null when the authentication mechanism is unspecified`

However 3000ms seconds before, the `metabase` logs show this:

`05-12 13:15:51 ERROR metabase.driver :: Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}]`

So it looks like it's an SSL error.

I'm new to `MongoDB` and `Metabase` so I'm not sure it's something I should fix on the `MongoDB` or `Metabase` side (whatever is faster)

**Comment by camsaul** [comment]
We added SSL support for Mongo last year in #1369. That should all be working correctly so I suspect it's something else.

@maximecorbeau It looks like you're trying to connect to `localhost`, right? You probably want to disable SSL for that.

**Comment by maximecorbeau** [comment]
@camsaul : can you give me some directions (is it on Mongo or Metabase side? Mongo came out of the box, sorry if I am a bit clueless)

**Comment by agilliland** [comment]
This looks like a credentials issue of some sort `Failed to connect to database: java.lang.IllegalArgumentException: Password can not be null when the authentication mechanism is unspecified`.  Sounds like you aren't supplying a password when Mongo things you should be.

The first error about SSL is not likely to be your issue.  Metabase always defaults to trying SSL connections first when connecting to new databases, but if you aren't using SSL then it's fine for that to fail and since you are using Mongo on localhost it sounds like you aren't using SSL.  So I would focus on the other error.

**Comment by maximecorbeau** [comment]
@agilliland Never mind, I messed up. Created new admin users which solved the issue:
http://stackoverflow.com/questions/22638258/create-superuser-in-mongo

**Comment by MbF-Sathya** [comment]
[](url)
