### ISSUE TITLE
Column filters not working on Questions using custom columns

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#25927]
**Describe the bug**
When creating a question with Custom Column, then it's not possible to add filters via column.

Workaround: Use Notebook editor to set/change filters

**To Reproduce**
1. Question > Sample > Orders
2. Summerize -> Count grouped by CreatedAt:Month
3. Custom Column -> = [Count] * 100

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/110378427/195843503-aa06bc80-bdd9-4b45-ad83-e70c42d802dc.png">

4. Choose Table Viz -> Click the Created At column > Filter by this column > Last 12 months > Click back on filter > the "Add filter" button is disabled

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/110378427/195844005-a42d41f8-7a6a-4091-a473-de264046a33b.png">

**Information about your Metabase Installation:**

Tested on 44

**Comment by flamber** [comment]
Very similar to #25016, and likely very related to #15333
