### ISSUE TITLE
event driven pulses a.k.a. alerting

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#2594]
pulses feature is fantastic, however the query result is delivered every time even when result is empty

- allow even driven pulses this could be as simple as execute pulse every x minutes/hours/days (reuses same schedule pattern) and the actual delivery result only if a column selected column fits specific condition e.g. myColumnABC == True

- enable (via toggle) suppressing of sending empty pulses (if there is no result, do not send the pulse)

**Comment by tlrobinson** [comment]
Duplicates of #1373 and #2430
