### ISSUE TITLE
allow parametrized questions via URL

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#2595]
I would like to call question via URL and supply a parameter to it

for example 

`http://metabase.mycompany.com/card/3?myparemeter=123`

where SQL for the question would be

```
SELECT * FROM MyTable WHERE myField = {myparemeter}
```

this would allow referencing metabase in other applications for example helpdesk tickets "for details go to `http://metabase.mycompany.com/card/3?myparemeter=123` " where 123 would be for example customer ID supplied by the issue system like OpsGenie

**Comment by salsakran** [comment]
we currently have 2 open issues that cover this:
#2348  for SQL backed questions and #1543 for questions build using the GUI. Closing as a dupe, but we're working hard on this front and might have something to show as soon as our next milestone 0.18.0!

**Comment by CzechJiri** [comment]
none of these tickets mention URL which is the key to be able to reference a question via URL with a parameter "how look at this invoice http://blabla...."

**Comment by salsakran** [comment]
Gotcha. We'd assumed they would work that way, but I can re-open this and we'll treat it as a functional aspect to the other two issues.

**Comment by CzechJiri** [comment]
very open to merge them, the other ticket seem more like a drop-down/inputbox parameter on the question page, which is interesting use case as well

**Comment by tlrobinson** [comment]
@CzechJiri The idea is the URL parameters would reflect the values in the drop-down/input boxes and vice versa, so a user can use the UI to apply a parameter, then bookmark or share that question/dashboard with the parameters applied. Or you could link to it from another system like you suggested.

**Comment by dacort** [comment]
Running into this a lot as well. Many "reports" I pass around are actually just tables that the person needs to download in order to do further analysis. Because download functionality doesn't yet exist on dashboards, and I can't link directly to a parameterized question, the current workflow is "go to this card, paste in the ID, and then download." Not too bad, but not my ideal.

**Comment by tlrobinson** [comment]
FYI this will be resolved by #4123
