### ISSUE TITLE
Password reset link always show "token expired" (even if clicked within a minute)

### ISSUE THREAD

**Issue by benmod** [metabase/metabase#25957]
**Describe the bug**
Password reset link always show "token expired" (even if clicked within a minute). 

**Logs**
The console logs shows: 
`app-main.bundle.js?60cd75ae7f110e862c03:2          GET https://xxx.com/datatool/api/session/password_reset_token_valid?token=2_715dba1e-5cf2-45fe-a695-xxxxxx 400`

When going to `https://xxx.com/datatool/api/session/password_reset_token_valid?token=2_715dba1e-5cf2-45fe-a695-xxxxxx` we see the following error: `{"errors":{"token":"value must be a string."}}`

**To Reproduce**
1. Go to the admin section on the platform
2. Go to the "people" section
3. Click on the "..." on a user, select "reset password" and confirm on clicking the "reset password" button
4. Go to the email box, and click the "reset password" blue button link
5. See a message saying "Whoops, that's an expired link" even though it was clicked within a few seconds of requesting the password reset

**Expected behavior**
The user is able to choose a new password. 

**Screenshots**
N/A

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "4.4.0-210-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.3 (Debian 14.3-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": "Africa/Nairobi"
    }
  }
}`

**Severity**
It is quite annoying as we need to create the new password and handle all of those request manually which takes quite a lot of our time. We can live with the issue for a few days but it's costing us significant resources. 

**Additional context**
- We have 6 Metabase instances, all have the same issue. 
- We use NGINX and Cloudflare but have disabled all security options in Cloudflare for the Metabase route, and have tried bypassing Cloudflare and the issue persists

**Comment by flamber** [comment]
Hi @benmod 
Check your Nginx debug logs to figure out if you are accidentally stripping something during the proxy_pass, since that would be the only way for Metabase to show such error. To validate this, go directly to Metabase without the Nginx reverse-proxy.
Without seeing your Nginx config, then it's difficult to tell where the problematic configuration is.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
