### ISSUE TITLE
Click Behavior cannot handle absolute URLs outside of Metabase

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#25953]
**Describe the bug**
If you have Metabase running on `/mb/` and want a Click Behavior to `/myapp/`, then Metabase thinks those URLs are internal and uses history.push, which shows a "We're a little lost..." error.

This issue might be tricky to fix without causing problems for some. Some history https://github.com/metabase/metabase/pull/20568#pullrequestreview-888035996

**To Reproduce**
1. Setup Metabase on a non-root with a reverse-proxy - example a Site URL like `/mb/`. Note: This step is actually not needed to reproduce the issue, but just to have some real-world context.
2. On a dashboard, add a question and create a Click Behavior with Custom URL to `/myapp/` - save
![image](https://user-images.githubusercontent.com/1447303/196030159-86f5b0b8-fc33-4c8c-8a86-510c42bf36f8.png)
3. Clicking on the link will change the browser URL to `/mb/myapp/` via history.push instead of handling it as an external link and shows a Metabase styled not found page.
![image](https://user-images.githubusercontent.com/1447303/196030282-063d73bf-6371-474d-a400-4f19d0c3f3d5.png)

**Expected behavior**
Absolute URLs should not be relative to Metabase's Site URL.
If the URL is outside the routes handled in Metabase, then it should essentially be an external-link, which opens a new tab (which is currently not configurable #10370)

**Information about your Metabase Installation:**
Tested 0.44.4

**Comment by iserikov-x** [comment]
I faced with the same issue after I've upgraded dev environment to 0.44.4. For production I'm still using 0.43.0 and everything work fine with reverse-proxy before metabase-app

**Comment by iserikov-x** [comment]
That's strange, but looks like I've just figure out how to fix it. I've changed the site url setting and remove reverse-proxy path /metabase.

**Comment by udit-001** [comment]
Facing a similar issue to this, where the metabase instance is running under `site.example.com/mb/` and site url in metabase settings is set to `site.example.com/mb`, I was trying to link another dashboard from custom click behavior configured on a single column, however the url it points to is instead `site.example.com/mb/mb/dashboard/13-test-dashboard?id=31` which shows the 404 page similar to one you posted. Will open a separate issue if you feel this is an unrelated issue I'm facing

**Comment by udit-001** [comment]
Hey @flamber any thoughts on this?

**Comment by paoliniluis** [comment]
@udit-001 I would suggest that, while we fix this issue that might take some time, you deploy a reverse proxy on top of Metabase so you can do the URL rewriting needed to solve this problem

**Comment by paoliniluis** [comment]
Just raised the priority on this one as one of our customers needs this to move to the most recent versions

**Comment by siraj-iconcile** [comment]
The issue is still here. I am running version  0.54.9 and I can't point to absolute URLs, it automatically pointing to /metabase/app rather than just /app. Can anybody suggest here the fix?

**Comment by siraj-iconcile** [comment]
I tried the following URLs:

https://domain.com/app/some-place
/app/some-place

It is taking me to 

https://domain.com/metabase/app/some-place
in both cases.
