### ISSUE TITLE
Don't offer "App" in "New" menu if there is no data source connected

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#25989]
**Describe the bug**
When all data sources are removed, we shouldn't offer to create a new App.

**To Reproduce**
1. Remove all databases
2. Go to the home page
3. Click "New"
4. Note that there is "App" in the menu although it doesn't make sense
5. Click on "App" and you'll see this window
![image](https://user-images.githubusercontent.com/31325167/196414367-24fac809-54df-47ca-8d35-c7c4064a01c9.png)

**Expected behavior**
Remove "App" as a choice from the "New" menu when there are no connected databases.

**Information about your Metabase Installation:**
local dev, `master`, 236665163e45d404c16af907a5876e6f550c2c5d, H2, Sample Database

**Severity**
P3

**Comment by kulyk** [comment]
Closing as apps are currently on pause and not on `master`
