### ISSUE TITLE
[Chinese Translation] the chinese of 'unpin' is '取消置顶' rather than '拔掉插头'

### ISSUE THREAD

**Issue by 2015WUJI01** [metabase/metabase#25987]
**Describe the bug**
The chinese of 'unpin' is '取消置顶' rather than '拔掉插头'.

**Information about your Metabase Installation:**
v0.44.2 - v0.44.4

**Severity**
Not serious, but it'll be better if you can fix it soon~

**Additional context**
I would like to help metabase to check chinese translation as much as I can~

**Comment by 2015WUJI01** [comment]
I was going to submit a PR, but found that it can be modified on the website. https://poeditor.com/join/project/ynjQmwSsGh

The latest data on the website has been fixed 5 months ago, so when will the correct translation data be merged into new version?

**Comment by flamber** [comment]
Translations will be updated in 0.44.5 - #25738
