### ISSUE TITLE
metabase version 0.42 connects to clickhouse to query data in the wrong time zone

### ISSUE THREAD

**Issue by CharesLee** [metabase/metabase#26007]
metabase info
`{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.15.0-144-generic",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }

> }`

clickhouse timezone
<img width="386" alt="image" src="https://user-images.githubusercontent.com/23518280/196643400-c7f2b4fd-4287-4d64-869f-66f0312d2adf.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/23518280/196645187-13408e22-7220-4c72-8c9b-178072a6dc5e.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/23518280/196643254-9c16109a-049a-4c66-a717-d50c084c164d.png">
<img width="758" alt="image" src="https://user-images.githubusercontent.com/23518280/196643579-9e749ad8-7e35-484b-bec0-220adb24daff.png">

metabase timezone
<img width="269" alt="image" src="https://user-images.githubusercontent.com/23518280/196643734-affafa98-eb75-4413-a6fb-830071c1fa85.png">
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/23518280/196643794-6ba0614c-f7a0-4375-83e9-2a58a540e9be.png">
metabase env
<img width="495" alt="image" src="https://user-images.githubusercontent.com/23518280/196643957-eec1adf9-ebb8-4bca-96a4-35a4635d748f.png">

That's the basic information，The following is the metabase UI page configuration

<img width="757" alt="image" src="https://user-images.githubusercontent.com/23518280/196644256-1dc81533-7044-4973-b99a-1a53a9d602a0.png">

It looks fine ！
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23518280/196644629-33d2cf0b-9d35-4e34-a526-0c34b2eed028.png">

But the time returned by querying select now () is 8 hours out of my local time
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/23518280/196644899-c3a0a78a-8f86-4b88-90ab-24a6bd4fd00f.png">

How can I solve this problem，Thanks

**Comment by flamber** [comment]
Look at issues in the driver repo: https://github.com/enqueue/metabase-clickhouse-driver/issues/81
