### ISSUE TITLE
Pulse slack post broken on latest Slack update

### ISSUE THREAD

**Issue by erickreutz** [metabase/metabase#2601]
Pulse images in Slack seem to be broken on the latest update of their app. The formatting of attachments seems to have changes. 

![img_1316](https://cloud.githubusercontent.com/assets/59875/15238640/48c82ef4-188f-11e6-8910-c9ada986ebbc.PNG)

*  I am using the Slack app on iOS.
*  My computer's OS is iOS 9.3.
*  I'm running Metabase on Heroku.
*  My database is Postgres.
*  My Metabase version is version v0.17.0 built on 2016-05-02.

**Comment by agilliland** [comment]
Hmmm, I just tried posting a couple of our teams pulses into a Slack channel and everything worked as usual.  Do you mind doing a couple more tests and verifying that this is happening consistently?

**Comment by erickreutz** [comment]
This has happened for the past 4-5 days. Do you know if you are on the latest Slack update on iOS?

**Comment by salsakran** [comment]
looks like an update to the slack iOS app is causing this.

we tested against a phone with the updated app and are seeing the same thing.

**Comment by erickreutz** [comment]
Per Slack's release notes.

> A little sprucing up means prettier formatting of unfurls, attachments, etc.

**Comment by agilliland** [comment]
I have an older version of the Slack app on my phone and everything is still working fine, so I'm assuming this was a mistake on their part, but we'll try to find out more.  You haven't noticed the images missing when you view them anywhere else right?

**Comment by erickreutz** [comment]
Nope just iOS. Everything is working on desktop for us.

**Comment by salsakran** [comment]
We've been in contact with Slack and they rolled out an update that should fix this. 

@erickreutz could you try looking at the pulse with the latest version of the slack ios app?

**Comment by erickreutz** [comment]
@salsakran is the new Slack update in the app store already?

**Comment by erickreutz** [comment]
I got the latest TestFlight build of Slack installed and it seems to be working now. Thanks for reaching out to Slack!
