### ISSUE TITLE
Unable to Group By Specific Field

### ISSUE THREAD

**Issue by ChrisIrvine63** [metabase/metabase#26014]
**Describe the bug**
A specific field (varchar) is not appearing in the group by selection menu. I have attempted to change the Type in the Admin settings>Data Model but whether it is description, category, or no semantic type, it is not showing up under the group by list. I am able to group by the field in the SQL editor but unfortunately I am attempting the make a pivot table using this field so that is not an option. Other similar problems all suggested changing the type but this has not helped.

**Screenshots**
![image](https://user-images.githubusercontent.com/96491959/196748021-67632550-7094-4b33-8d25-15a569c10c72.png)
![image](https://user-images.githubusercontent.com/96491959/196748199-5031cb5b-7f4b-43ef-a14e-bc929af283a4.png)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10-Ubuntu-0ubuntu0.20.04.1",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10-Ubuntu-0ubuntu0.20.04.1",
    "os.name": "Linux",
    "os.version": "5.13.0-1029-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "athena",
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.30-0ubuntu0.20.04.2"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-13",
      "tag": "v0.43.3",
      "branch": "release-x.43.x",
      "hash": "c9c7ef0"
    },
    "settings": {
      "report-timezone": "US/Arizona"
    }
  }
}
```

**Comment by flamber** [comment]
Upgrade to latest release: https://github.com/metabase/metabase/releases/latest
Make sure to do a browser refresh after changing the field type.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
