### ISSUE TITLE
Pivot Table taking too long to load

### ISSUE THREAD

**Issue by Varinderr** [metabase/metabase#26029]
I am using metabase for quite some time and started with pivot table just recently. I am doing data modelling on dbt and for some reason my pivot table is taking too long to load (about 1 minute). When i click on the pivo table question in my dashboard, it opens up more quickly. Can anybody please help identifying the cause of this? Also when the opened the separate question from collection, it takes longer.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
