### ISSUE TITLE
Unable to connect to SQLServer with special characters in DB password

### ISSUE THREAD

**Issue by nosh** [metabase/metabase#2604]
Hi,

I'm unable to connect to my SQL Server database in Azure with Metabase. The log gives me this message:
05-13 16:21:52 ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
05-13 16:21:52 ERROR metabase.driver :: Failed to connect to database: java.sql.SQLException: Login failed for user 

This is the same error message as in https://github.com/metabase/metabase/issues/1854
However, I'm using the latest version of metabase, so it looks like a different issue.

I'm able to connect with other tools (a python script using the pymssql module) from my machine with no problem, so there doesn't seem to be any connectivity issues with the machine I'm trying to connect from 

The settings I'm using in metabase are:
Host: xxxxx.database.windows.net
Port: 1433
Database name: yyyyy
Database user name: zzzz@xxxxx
database password: mypassword
I'm not specifying an instance name or windows domain

The Azure portal for the database provides this as the JDBC connection string to use:
jdbc:sqlserver://xxxxx.database.windows.net:1433;database=yyyyyyy;user=zzzzz@xxxxxx;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
where xxxx is the servername
yyyy is the database name
zzzz is the username
I can't compare this to what Metabase is doing, as the connection string it is using is not logged anywhere that I can see. 

Any help you could give me would be great!

The details of my Metabase installation are:
-  I am using the _chrome__________ browser.
-  My computer's OS is _____OSX10.10.5_____.
-  I'm running Metabase version __ from the JAR
-  My database is **_SQLServer on Azure_**_.
-  My Metabase version is **_v0.17.1 (e1376ea release-0.17.1)_____**_.

**Comment by agilliland** [comment]
The two errors you are seeing are 1) a first failed attempt to connect over SSL and 2) a second failed attempt without SSL which appears to be failing due to credentials.  Are you sure you're using the right login/password?

**Comment by nosh** [comment]
For the username, I've tried both the format of 'user@host' and just 'user'. Neither of them work.
I've re-typed (and copy-pasted) the password a few times to double check - and I get the same errors.
As I mentioned - I have a python script using pymssql that uses the same credentials and is able to connect from my machine.
There are a couple of things to note - the database name has a mix of upper case and lower case characters in it. Also, the password has a number of punctuation/special characters such as ],@,> etc in it. Is it possible that something is getting mangled either while parsing through the web UI or while building the connection string?

**Comment by camsaul** [comment]
@nosh did you ever have any luck with this?

**Comment by camsaul** [comment]
After reading the description of this and #2676 again it sounds like they're the same issue. Connecting to SQL Server when the password has lots of special characters doesn't seem to work. We're just using the jTDS JDBC driver and a normal JDBC connection string so if anyone knows the appropriate thing to do here let me know and I'll make the changes 😓

**Comment by camsaul** [comment]
@nosh this just occured to me. Have you tried [URL-encoding the password](http://stackoverflow.com/a/34308709/1198455)? The JDBC connection string is a URL so it sounds like you need escape special characters appropriately.

**Comment by camsaul** [comment]
@nosh can you try manually URL-encoding your password and let me know if it works? If so I think we could add some logic to automatically URL-encode the password

**Comment by camsaul** [comment]
@nosh?

**Comment by camsaul** [comment]
@nosh?

**Comment by camsaul** [comment]
@nosh?

**Comment by camsaul** [comment]
@nosh?

**Comment by camsaul** [comment]
@nosh?

**Comment by camsaul** [comment]
@mazameli or @salsakran if you're looking for bugs to try and repro this would be helpful to me, I've never heard back from the original poster

**Comment by mazameli** [comment]
Cool, I'll take a look.

**Comment by camsaul** [comment]
you'll probably have to find/create a SQL Server DB with special characters in the password to verify this 😳

**Comment by mazameli** [comment]
Yep, I'll see if I can do that.

**Comment by mazameli** [comment]
This is definitely more complicated and involved than I realized. I found [a sample DB here](https://github.com/Microsoft/sql-server-samples/tree/master/samples/databases/wide-world-importers), but I'm not sure how or if I could make it have a password with special characters without using [SQL Server express](https://www.microsoft.com/en-us/sql-server/sql-server-editions-express), since I'm on a Mac.

**Comment by camsaul** [comment]
@mazameli you'll either have to use the Windows laptop 🙀 💻  or set up an instance on RDS 😱
