### ISSUE TITLE
Opening data reference when editing saved model query definition ends up in "API endpoint not found"

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#26046]
### To reproduce

1. Open a model derived from a written query.
2. Edit query definition
3. Click on Data Reference (book icon)

Data reference lands on step below. 
Clicking "back" takes us back to the first step of data reference.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/380816/197065934-ce45c137-f968-487c-b88d-e711bf77021d.png">

**Comment by calherries** [comment]
I can't reproduce this following just these instructions. Can you record a loom showing the error in the network tab?

**Comment by gusaiani** [comment]
This is not happening on master branch, I've been living in a feature branch for a while and the mistake is mine.
