### ISSUE TITLE
Snowflake sync is consuming more resources than necessary

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#26054]
**Describe the bug**
There are a few issues with Snowflake sync leading to unneeded credit consumption.

**To Reproduce**
1. Connect our Snowflake dev instance as a data source. Credentials [here](https://start.1password.com/open/i?a=AEO4BXOSHNFCJLK26XA7AD522E&v=fbhwdxcon6hj77du2c5cc7wvaa&i=kzp4a5bx4pnhv4z6pabmbn5awa&h=my.1password.com).
2. Wait for the automatic sync or trigger it manually.
3. Go to https://ls10467.us-east-2.aws.snowflakecomputing.com/console#/monitoring/queries to see query logs

**Identified issues**
1. describe-database: The heavy `SHOW OBJECTS IN DATABASE "v3_sample-dataset"` ran twice. After this query, we run `SELECT TRUE AS "_" FROM "v3_sample-dataset"."PUBLIC"."reviews" WHERE 1 <> 1 LIMIT 0` for each table, so these are also duplicated.
2. add-table-pks: Instead of getting primary keys for each table, we are running `show /* JDBC:DatabaseMetaData.getPrimaryKeys() */ primary keys in account`. This scans the entire account for primary keys. We should scan a single table or scan the database (not account) once.
3. describe-table: One of our users reported that instead of running `show /* JDBC:DatabaseMetaData.getColumns() */ columns in table "v3_sample-dataset"."PUBLIC"."reviews"` for each table, we are running `show /* JDBC:DatabaseMetaData.getColumns() */ columns in database "DB_NAME"` for each table (scanning the entire db multiple times). _I couldn't repro this._

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Tested on 44 and 45. The behavior on each version is a bit different, but the issues are the same.
- For reference, this user reported the `sync` task is taking 4.8 hours (`sync-fields` accounts for 3.5 hours and `sync-fks` for 1.1) 

**Severity**
P1 - it significantly increases costs for Snowflake users with larger databases.
Related to #24319 and #24862

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
RE point number 2 (`add-table-pks`):

`getPrimaryKeys(catalog, schema, table)` has three parameters that are effectively optional (you can pass `nil` to include everything, or pass a string to filter by that catalog/schema/table) https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getPrimaryKeys-java.lang.String-java.lang.String-java.lang.String and we do pass the `table` name when we call `.getPrimaryKeys` -- see https://github.com/metabase/metabase/blob/e5638895172185d81331485f91e80b5caeaf30d0/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L181

So it should already be restricting results to just the current table. It's entirely possible that this is an upstream bug in the Snowflake JDBC driver, and it's ignoring the table name. We'll have to investigate a little more to confirm.

One thing  we might want do is tweak `add-table-pks` to include `(:schema table)` when it's present -- that should improve performance for all the SQL JDBC drivers

**Comment by escherize** [comment]
I'll add in the schema, good idea. I need to pass in the "catalog" (aka db ?) too.


The snowflake driver will search the [entire account when the catalog is `null`]( 
https://github.com/snowflakedb/snowflake-jdbc/blob/master/src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java#L1985), and that's what we are seeing. It needs all 3 to look at a table, which makes sense.

**Comment by luizarakaki** [comment]
@flamber should we ship this on 45.2?

**Comment by flamber** [comment]
I don't know how safe this is, so that would be up to the developer (and to remember to add `backport` label on the PR if so).

**Comment by luizarakaki** [comment]
@escherize how do you feel about backporting this and shipping with 45.2? From a product perspective, it would be valuable to ship this asap, since it is severely impacting sync performance.

**Comment by escherize** [comment]
This code passed tests that ran against all dbs, and wasn't a huge change to the way we do things. It can bypass a couple of (unlikely to occur) edge cases as well. so I think it'd be good to get it backported.
