### ISSUE TITLE
Snowflake Key Pair Authentication doesn't work

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#26078]
**Describe the bug**
Even though I am able to connect to Snowflake using user and password. I am not able to connect via Key Pair Authentication

**Logs**

`Caused by: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: Private key provided is invalid or not supported: /tmp/metabase-secret_6089391108929381806.tmp: null`

**To Reproduce**

Before you start, make sure you go through snowflake official documentation https://docs.snowflake.com/en/user-guide/key-pair-auth.html to generate a Public and Private key, and assign the Public Key to a Snowflake User

1. Go to Admin -> Databases -> Add Database -> Snowflake 
2. Fill in the connection details except for the password 
3. See error

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/110378427/197484505-f776848b-8712-4dab-aeae-aecabfefca7c.png">

**Expected behavior**
If I am not using the password and only the RSA private key I should still be able to connect to Snowflake

**Information about your Metabase Installation:**

1.44.0 up to 1.44.4

**Additional context**

The following ticket https://github.com/metabase/metabase/issues/19191 should have enabled Snowflake Key Pair Authentication in 44 but I tested on 1.44 and it doesn't work either.

I also found reference online that the issue could be the inability of the javax.crypto libraries to decrypt an encrypted private key file in windows and ubuntu environments on the latest OpenSSL 1.1.1g version​. 

https://knowledge.informatica.com/s/article/000138783?language=en_US
 
https://community.snowflake.com/s/article/Private-key-provided-is-invalid-or-not-supported-rsa-key-p8--data-isn-t-an-object-ID

Nonetheless I tested on different openssl versions https://www.openssl.org/source/old/ (1.0, 1.0.2, 1.1.1, 3.0) nothing seem to work

**Comment by escherize** [comment]
Hi, @Tony-metabase -- I've been looking into this. Were you using an encrypted or an unencrypted key pair? I assume encrypted since you mention:

> I also found reference online that the issue could be the inability of the javax.crypto libraries to decrypt an encrypted private key file in windows and ubuntu environments on the latest OpenSSL 1.1.1g version​.

But does this report indicate that you noticed this behavior with both sorts of keypairs, or jut encrypted?

**Comment by Tony-metabase** [comment]
Hi @escherize I experienced the same issue with both encrypted & decrypted key pair. I also tried different OpenSSL versions and all had the same outcome of:

`Private key provided is invalid or not supported`

I mentioned that reference because that might be the only issue (i managed to find) that should cause disturbance to Metabase connecting to Snowflake when we use key pairs.

**Comment by flamber** [comment]
Only unencrypted key pair is supported on the Snowflake JDBC driver as far as I know, which is what we have tried to implement #24157

**Comment by escherize** [comment]
This has been closed by #26304.
