### ISSUE TITLE
Document question and dashboard revisions

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#26076]
I don't see any documentation about question and dashboard revisions, which might be useful for some users. I just discovered that we have a limit of 15 versions of questions and dashboards and after that everything will be deleted

**Comment by jeff-bruemmer** [comment]
We have it documented in [History](https://www.metabase.com/docs/latest/exploration-and-organization/history), but it's pretty spare. I'll submit a PR with some elaboration and connective tissue so people can find it when reading about dashboards, questions, and models.
