### ISSUE TITLE
Model list appears empty when creating new question, even though models exist

### ISSUE THREAD

**Issue by tjmurray** [metabase/metabase#26091]
When creating a new Question, then selecting Model as starting point, the Model list appears empty, even though Models exist.

**To Reproduce**
1. Create one or more Models and save in "our analytics"
2. Start creating a new Question, via the " + New" button in the top-right in the menu bar.
3. Click "Models" from the list of "Models, Raw Data, Saved Questions"
4. Observe that the list of Models is empty.

The models were recently created (30 mins ago), so perhaps there is a time delay in them being visible here? But even if this is the case then this is highly undesirable behaviour.

**Expected behavior**
Would have expected the saved models to be accessible here. Otherwise how are you supposed to use them to build questions?

**Screenshots**
Here is the empty list:
<img width="1180" alt="Screenshot 2022-10-24 at 20 56 20" src="https://user-images.githubusercontent.com/30073348/197628140-04079ed8-e651-46d2-8f66-09c675428ada.png">

Here is the "our analytics" page showing that Models exist:
<img width="437" alt="Screenshot 2022-10-24 at 20 56 38" src="https://user-images.githubusercontent.com/30073348/197628164-98573c88-6920-49a6-b901-970bf74fe990.png">

**Information about your Metabase Installation:**
Running v0.44.4

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-post-Ubuntu-0ubuntu118.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-post-Ubuntu-0ubuntu118.04",
    "os.name": "Linux",
    "os.version": "5.4.0-1088-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.38-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Fairly severe. Cannot create questions on top of the complex models which have been painstakingly created as the bedrock of this project's analytics

**Comment by tjmurray** [comment]
Okay so I'm fairly confident this is a caching issue. After doing a force page reload (reload from origin without any browser caching), then the models now appears in the list, but this is quite annoying behaviour and average users won't know how to force reload, let alone to even think of doing it. And even for users who know how to do this, it's a pain to do it every time you create a new model.

**Comment by flamber** [comment]
Caused by browser cache, repeat of #24878.

**Comment by ranquild** [comment]
@flamber did you manage to reproduce that? I can't do it by following the steps from the description

**Comment by flamber** [comment]
@ranquild Historically similar to #9027
1. New question > select Models in the data selector
2. New native > `select 1, 2` - save - turn in a model
3. New question > select Models in the data selector - it won't show the new model until you browser refresh
