### ISSUE TITLE
Misleading error message when creating admin account

### ISSUE THREAD

**Issue by eeriksp** [metabase/metabase#26094]
**Describe the bug**
When opening up the web interface to create the admin account, when the "last name" field is left empty, no errors are shown immediately, but the message `value may be nil, or if non-nil, value must be a non-blank string.` will be shown in the very end.

**To Reproduce**
1.open up the metabase web interface for the first time
2. create a user leaving the "last name" field blank
3. continue until the end of the setup wizard

**Expected behavior**
Error regarding the last name to be shown immediately next to the field.

**Screenshots**
![image](https://user-images.githubusercontent.com/35540617/197644586-a0f9809e-4fe9-47b1-877f-32fb22ef998f.png)

**Severity**
This might be a deal breaker, because if I cannot figure out that the error is caused by the last name field, I am unable to continue with the setup wizard. I found the cause of the error by observing the browser console, but the UI itself provided no clues.

**Comment by flamber** [comment]
I cannot reproduce on latest 0.44.5 release.
