### ISSUE TITLE
Allow search for card to add to a dashboard

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2610]
Once you get a lot of cards in a dashboard, it's hard to get to the card you want to add. We should add the ability to search for a specific card by name to the add card modal.

<img width="630" alt="screen shot 2016-05-16 at 11 32 42 am" src="https://cloud.githubusercontent.com/assets/107439/15299554/c64dbe9e-1b59-11e6-963f-ba66d6518579.png">

**Comment by mazameli** [comment]
Related, using labels in add-card-to-dashboard UI: #2589

**Comment by mazameli** [comment]
This got resolved along the way; I think when we implemented Collections.
