### ISSUE TITLE
Databases link broken in Readme

### ISSUE THREAD

**Issue by toddas90** [metabase/metabase#26126]
**Describe the bug**
When you click either of the links inside the "Supported Databases" section, the links go nowhere.

**To Reproduce**
1. Go to the Readme.
2. Scroll down to "Supported Databases"
3. Click one of the links

**Expected behavior**
The link should take you to the correct location

**Severity**
This could be a huge turnoff for potential users of this application.

**Additional context**
The content that the links point to seems to have been moved into a docs folder, so the links in the Readme just need to be updated. Should be an easy fix, I was just too lazy to create a PR.

**Comment by flamber** [comment]
Will be fixed by #25961 - use https://www.metabase.com/docs/latest/databases/connecting
