### ISSUE TITLE
Archive a Question used by another Question still keeps loading data from archived Question 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#26148]
**Describe the bug**
When I archive a Question that is being used by another question, I am still able to load the data from the archived question by loading the Question that is joined with the archived question.

**To Reproduce**
1. Go to New Question -> Sample Database -> Orders -> Save as orders_v1
2. Go to New Question -> Sample Database -> Orders -> Join with orders_v1 on ID -> Save as orders_v2
2. Archive question order_v1
4. View order_v2, notice the join still reference the archived quest and I am able to load the data of order_v1

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/110378427/198570824-eca348b7-6e3a-4f59-9cd4-11bb306392ee.png">

**Expected behavior**
I would expect some kind of error saying `orders_v1 doesn't exist` or some other kind of failure. If i archived the question then I am expecting that no one is able to load the data of that archived question

**Information about your Metabase Installation:**

Metabase 44

**Comment by npfitz** [comment]
@luizarakaki Any idea on how we should handle this, or if this is a proper bug? Archiving the question really just keeps it from showing up in collections, but any question that use it as a source will still work. Deleting the question does cause errors though.

**Comment by ranquild** [comment]
Archived doesn't mean your question is unavailable. Closing.
