### ISSUE TITLE
Pie Chart Display Freezes Tab

### ISSUE THREAD

**Issue by pedro-pupo** [metabase/metabase#2614]
Hello,

I'm running a simple query on Redshift on our store's data (last month's gross revenue grouped by state) and displaying it on a pie chart completely freezes the tab Metabase is being displayed on. The data displays fine on other modes and there's only 27 groupings. I'm not sure whether this is a server side or client side issue. 

If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser, version 50.0.2661.102
*  My computer's OS is Windows 8.
*  I'm running Metabase on Elastic Beanstalk.
*  My database is AWS Redshift.
*  My Metabase version is You're on version v0.17.0.

**Comment by tlrobinson** [comment]
@pedro-pupo Are there any error or warning messages in the browser's JavaScript console? 

If possible, after running the query could you run `dumpQueryBuilderState()` (`copy(JSON.stringify(dumpQueryBuilderState()))` in Chrome will copy to the clipboard) in the JavaScript console and post/email me the results? Feel free to anonymize it or email it directly to me (tom@metabase.com). You can leave the visualization setting as a table if switching to pie totally freezes your browser, I just need to the data.

@MrMauricioLeite Does your 👍  indicate you are able to reproduce this too?

**Comment by MrMauricioLeite** [comment]
Yes, and I can provide the data on monday morning if Pedro can't.



[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-05-27 14:30 GMT-03:00 Tom Robinson <notifications@github.com>:

**Comment by lewisl9029** [comment]
@pedro-pupo, @MrMauricioLeite I'm trying to debug this but having a hard time reproducing the issue. If you could take a look at the steps mentioned in @tlrobinson's reply and post/email the results, that would definitely help speed things along. Thanks!

**Comment by camsaul** [comment]
@pedro-pupo @MrMauricioLeite are you still seeing this error?

**Comment by MrMauricioLeite** [comment]
The error is gone guys, sorry I forgot to tell you here.

@pedro-pupo or anyone, close the issue. It's not relevant anymore.

[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-07-13 18:06 GMT-03:00 Cam Saül <notifications@github.com>:

**Comment by camsaul** [comment]
@MrMauricioLeite I'll go ahead and close this. Glad it's working now 👍
