### ISSUE TITLE
Editor in Question doesn't let me alter/remove filters and summarize

### ISSUE THREAD

**Issue by marcelommm** [metabase/metabase#26159]
**Describe the bug**
Not able to alter/remove filters and summarize in Editor.
A few minor extra bugs.

**Logs**
[diagnostic_info.txt](https://github.com/metabase/metabase/files/9891009/diagnostic_info.txt)
[Logs.txt](https://github.com/metabase/metabase/files/9891006/Logs.txt)

**To Reproduce**
1) If i go directly to "Show Editor" in a Question, it doesn't let me alter/remove anything in Filters and Summarize.  It only works if I pre-visualize a result set.

2) This one possibly more difficult to recreate, when going back and forward pages using browser, all icons hide and nothing is shown on screen, but if I roll over mouse a floating pop up appears with the object name, although it's invisible

P.S All those issues were tested on both Chrome and Edge.

**Expected behavior**
1) It should let me alter/remove filters and summarize

2) It shouldn't do that

**Screenshots**

**Information about your Metabase Installation:**
AWS EC2 machine running Metabase as a Docker container. Latest version ().
Database: AWS RDS Postgresql 

- Your browser and the version: Chrome 105.0.5195.125,  Firefox 106.0.2 (64-bit),   also tested on MacOS Edge and Chrome
- Your operating system: Ubuntu 22.04.1 LTS,  although it was tested also on MacOS
- Your databases: Postgres
- Metabase version: v0.44.5
- Metabase hosting environment: AWS EC2 machine
- Metabase internal database: AWS RDS Postgres

**Severity**
Our Data Analysts are being impacted and not able to create new reports.
How severe an issue is this bug to you? Blocking data analysts

**Additional context**

**Comment by flamber** [comment]
Hi @marcelommm 
Please post "Diagnostic Info" from Admin > Troubleshooting.
I think you need to provide screenshots or video showing the problem, since it it's difficult to understand how to reproduce.
The second problem sounds like #25785

**Comment by marcelommm** [comment]
Hi @flamber thanks for your quick input,

[Diagnostic info ](https://github.com/metabase/metabase/files/9891009/diagnostic_info.txt)
https://github.com/metabase/metabase/files/9891006/Logs.txt

Videos:
https://user-images.githubusercontent.com/112194436/198714573-01519cc5-2839-47ae-9aec-e8545bf93543.mp4
https://user-images.githubusercontent.com/112194436/198714590-f5739869-5b15-414f-9ab1-57b3a8deb97b.mp4

**Comment by flamber** [comment]
@marcelommm Video 1. I don't know what the problem is, have not seen that before.
Check your browser developer console, when trying to remove a filter/group.
I think some problem has occurred earlier, which has caused this problem.
Try starting without any browser extensions (or Incognito mode) to see if it is caused by a browser extension.

Okay, video 2 where things are blank is #25785. It happens only in newer Chromium browsers, when trying to drag-and-drop the columns/rows in a Pivot Table. After dragging, when everything turns blank, then you can click on the moved column/row, which makes it reappear again - or do a browser refresh

**Comment by marcelommm** [comment]
Thanks for your valuable input flamber.

Looping @pelucchia our Sales Data Analyst who experienced the issues

**Comment by marcelommm** [comment]
When double-checking with colleagues, they aren't experiencing glitches anymore.  Closing the ticket for now.  Thank you flamber
