### ISSUE TITLE
I want to select what comes out of raw data for each question

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2615]
Guys, I searched for a issue about this but could not find one open.

When extracting raw data from my datawarehouse I know that there is 100 columns on table factA and only want to create a table showing 10 columns from table factA and 1 column from table dimensionB.

I would like raw data extraction to let me select what columns to show. And if possible add columns from dimension tables to the mix too.

Do you think that's possible?
@camsaul @tlrobinson @mazameli 

> Possible applications:
- Show tables with few columns on questions.
- Allow users to extract simples csv files from the datawarehouse easily
- Give a way to visualize data before you start to dig deep in it.

**Comment by agilliland** [comment]
I assume you were looking for this https://github.com/metabase/metabase/issues/1445

Also, as a point of process you don't need to directly mention Metabase team members when creating issues.  Everyone who is on the team is notified of all new issues.

**Comment by MrMauricioLeite** [comment]
Sure @agilliland, I'll remember that is not needed to mention the team members.

About issue #1445, apparently I confused it for closed without any outcome but was mistaken.
Sorry about the Dupe, all close this.
