### ISSUE TITLE
Discrepency in the unarchive UI between admins and non-admins

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#26169]
**Describe the bug**
As an admin, if you go to the list of archived content, you can hover over any single entry and see an "Unarchive this" button. You can also select content by clicking its icon and then use "Unarchive" and "Delete" buttons that appear at the bottom of the screen.

As a non-admin, the buttons don't appear on hover, but you can still unarchive things from the bottom of the screen. There's no reason the buttons on hover should be hidden if we're allowing the functionality regardless, so this is a weird discrepancy.

**Information about your Metabase Installation:**
Master

**Severity**
Very minor

**Comment by flamber** [comment]
Related to #24018
