### ISSUE TITLE
App crashing after database upgrade on Heroku

### ISSUE THREAD

**Issue by bsiddiqui** [metabase/metabase#2616]
I update to the standard Postgres tier on Heroku and now the app is stuck on this screen

<img width="582" alt="screenshot 2016-05-17 12 42 07" src="https://cloud.githubusercontent.com/assets/2721959/15336734/c5ee6178-1c2c-11e6-8293-e9025a917ff5.png">

and logs just show it constantly crashing 

<img width="698" alt="screenshot 2016-05-17 12 42 58" src="https://cloud.githubusercontent.com/assets/2721959/15336752/e3dfe10c-1c2c-11e6-81ff-82fce4c5cf1d.png">

It was a fresh DB so I just followed provisioned the standard postgres addon and promoted it following the upgrade docs.

**Comment by tlrobinson** [comment]
@bsiddiqui can you run `heroku ps:restart` and post the resulting logs? The logs from `app[web.1]` in particular are what we need, e.x.

```
2016-05-17T19:45:12.352107+00:00 heroku[web.1]: State changed from down to starting
2016-05-17T19:45:20.861407+00:00 heroku[web.1]: Starting process with command `./bin/start`
2016-05-17T19:45:22.697019+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2016-05-17T19:45:22.707705+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx350m -Xss512k -Dfile.encoding=UTF-8
2016-05-17T19:45:33.233131+00:00 app[web.1]: 05-17 19:45:33 INFO metabase.core :: Starting Metabase in STANDALONE mode
2016-05-17T19:45:33.266206+00:00 app[web.1]: 05-17 19:45:33 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
2016-05-17T19:45:33.266220+00:00 app[web.1]:  {:port 57871}
2016-05-17T19:45:33.266227+00:00 app[web.1]:
2016-05-17T19:45:33.320416+00:00 app[web.1]: 05-17 19:45:33 INFO metabase.core :: Starting Metabase version v0.18.0-snapshot ( ) ...
...
```

**Comment by bsiddiqui** [comment]
@tlrobinson 

<img width="1680" alt="screenshot 2016-05-17 14 08 25" src="https://cloud.githubusercontent.com/assets/2721959/15339347/db34d466-1c38-11e6-9d99-0e4197e97ffb.png">

**Comment by tlrobinson** [comment]
@bsiddiqui That's odd, it looks like it's not using SSL to connect to postgres, which should be fine if both the database and application are running on Heroku. Did you manually configure the database?

**Comment by bsiddiqui** [comment]
@tlrobinson nope. 

Added the standard db
`heroku addons:create heroku-postgresql:standard-0`

Promoted the new db
` heroku pg:promote HEROKU_POSTGRESQL_COLOR`

**Comment by bsiddiqui** [comment]
@tlrobinson actually just tested something for good measure. Found that just doing a heroku deploy and not doing and DB upgrade leads to an issue as well, albeit a different one (didn't have this issue deploying in past)

<img width="1676" alt="screenshot 2016-05-17 17 16 16" src="https://cloud.githubusercontent.com/assets/2721959/15343621/219cb968-1c53-11e6-9e24-4b2752215188.png">

**Comment by tlrobinson** [comment]
@bsiddiqui I don't see anything wrong in that last screenshot, the 503s are expected while Metabase is starting up.

I have verified that Metabase seems to be having trouble connecting to promoted databases, but I'm not sure why yet.

**Comment by tlrobinson** [comment]
Ok it looks like Heroku recently changed to require SSL "for all connections on some newer databases on -0 and -2 plans": https://devcenter.heroku.com/articles/postgres-logs-errors#fatal-no-pg_hba-conf-entry-for-host-user-u-database-d-ssl-off

I tried doing `heroku addons:detach DATABASE` then manually adding `?sslmode=require` to the connection string with `heroku config:set DATABASE_URL=postgres://.../?sslmode=require` (https://devcenter.heroku.com/articles/heroku-postgresql#heroku-postgres-ssl) but that didn't seem to work either.

I'll keep looking into it.

**Comment by tlrobinson** [comment]
Alright I was just missing some of the other required parameters.

A temporary workaround is to detach `DATABASE_URL` with `heroku addons:detach DATABASE` then manually set the environment variable using `heroku config:set DATABASE_URL=...` with the following appended: `?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory`

This obviously isn't ideal. I'll work on a more permanent solution.

**Comment by kapso** [comment]
Running into a similar issue. In our case, the follower DB that we are using for data analysis was assigned a new host name (due to Heroku maintenance) and now we are seeing the following.

Is there a way to provide the new DB URL via Heroku config to Metabase? I would hate to reset the Metabase database, since it will erase all our saved reports.

![](https://d17oy1vhnax1f7.cloudfront.net/items/0x141k2z1W282j1y0F0m/Screen%20Shot%202016-11-01%20at%2012.46.30%20AM.png?v=a1d72f84)

**Comment by tlrobinson** [comment]
@kapso did you try the workaround above to manually set the DATABASE_URL?

**Comment by kapso** [comment]
@tlrobinson well the DATABASE_URL is pointing to the Heroku's app local DB that stores Metabase's metadata (users, passwords, stored queries and related metadata). If I point DATABASE_URL to our follower DB (that contains our customer info etc), I would think Metabase will have to no way to boot up, no??

**Comment by tlrobinson** [comment]
@kapso Oh sorry I was confused. The databases you add to Metabase aren't configured by environment variables, they're configured in the admin panel at `/admin/databases`.

I'm not sure why that's preventing Metabase from booting though. Can you look at the Heroku logs to see where it's failing/hanging?

**Comment by kapso** [comment]
@tlrobinson So I just restarted the Heroku server and tried accessing Metabase, see the same endless "Reticulating splines…" page

Here's the log https://gist.github.com/kapso/80b0ae3ad85bb458ee5c39802755462a

But why not externalize the DB configuration, that way switching DB host is easy.

**Comment by tlrobinson** [comment]
@kapso I'd recommend backing up your application database and upgrading to 0.20 since we fixed some issues related to this. Give it plenty of time to start up and if you still get the `liquibase.exception.LockException` error then try releasing the lock using the command listed here: http://www.metabase.com/docs/v0.13.0/operations-guide/start#troubleshooting-common-problems

```
heroku ps:scale web=0
heroku run java -jar metabase.jar migrate release-locks
heroku ps:scale web=1
heroku logs -t
```

**Comment by kapso** [comment]
@tlrobinson cool thanks. Any docs or upgrade steps I can look at?

**Comment by tlrobinson** [comment]
@kapso http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku

**Comment by kapso** [comment]
@tlrobinson getting this error when I run `heroku run java -jar metabase.jar migrate release-locks`

```
$ heroku run java -jar metabase.jar migrate release-locks -a doorman-metabase
Running java -jar metabase.jar migrate release-locks on ⬢ doorman-metabase... up, run.2185 (Standard-1X)
Error: Unable to access jarfile metabase.jar
```

**Comment by kapso** [comment]
@tlrobinson 

So I was able to get this to run ok (it needed the correct path for the jar)

`heroku run java -jar target/uberjar/metabase.jar migrate release-locks -a doorman-metabase`

...BUT still seeing the migration issue.

```
java.lang.Exception: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2016-11-01T23:22:31.509418+00:00 app[web.1]: 	at metabase.db$wait_for_migration_lock_to_be_cleared$fn__6220.invoke(db.clj:149)
2016-11-01T23:22:31.509472+00:00 app[web.1]: 	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:668)
2016-11-01T23:22:31.509511+00:00 app[web.1]: 	at metabase.util$do_with_auto_retries.invoke(util.clj:660)
2016-11-01T23:22:31.509559+00:00 app[web.1]: 	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:672)
2016-11-01T23:22:31.509606+00:00 app[web.1]: 	at metabase.util$do_with_auto_retries.invoke(util.clj:660)
```

FYI.. we migrated to v0.20.3 
`INFO metabase.core :: Starting Metabase version v0.20.3 (2a54427 release-0.20.3)`

**Comment by camsaul** [comment]
@kapso what's the `-a doorman-metabase` for?

**Comment by kapso** [comment]
@camsaul its our Heroku app

**Comment by camsaul** [comment]
Ok... 

@kapso it doesn't look like it's handling the `migrate release-locks` the way I'd expect. If it did, you wouldn't be seeing an error there. What happens when you do

```bash
java -jar target/uberjar/metabase.jar version
```

**Comment by kapso** [comment]
@camsaul 

```
Running java -jar target/uberjar/metabase.jar version on ⬢ doorman-metabase... up, run.2532 (Standard-1X)
11-02 00:39:52 INFO metabase.util :: Loading Metabase...
Metabase version: {:tag v0.20.3, :date 2016-10-26, :branch release-0.20.3, :hash 2a54427}

OS: Linux 3.13.0-100-generic amd64

Java version: OpenJDK 64-Bit Server VM 1.8.0_102-cedar14

Country: US
System timezone: Etc/UTC
Language: en
File encoding: ANSI_X3.4-1968
```

**Comment by camsaul** [comment]
How peculiar. 

What do you see when you do

```bash
java -jar target/uberjar/metabase.jar migrate print
```

**Comment by kapso** [comment]
@camsaul 

```
$ heroku run java -jar target/uberjar/metabase.jar migrate print -a doorman-metabase
Running java -jar target/uberjar/metabase.jar migrate print on ⬢ doorman-metabase... up, run.6762 (Standard-1X)
11-02 00:48:51 INFO metabase.util :: Loading Metabase...
11-02 00:50:52 INFO metabase.db :: Setting up Liquibase...
11-02 00:50:53 INFO metabase.db :: Liquibase is ready.
```

BTW, if it helps - when this was running Heroku logs was showing...

```
2016-11-02T00:48:32.224238+00:00 heroku[run.6762]: Awaiting client
2016-11-02T00:48:32.281280+00:00 heroku[run.6762]: Starting process with command `java -jar target/uberjar/metabase.jar migrate print`
2016-11-02T00:48:32.359289+00:00 heroku[run.6762]: State changed from starting to up
2016-11-02T00:48:56.947489+00:00 heroku[run.6762]: Process running mem=597M(116.8%)
2016-11-02T00:48:56.947580+00:00 heroku[run.6762]: Error R14 (Memory quota exceeded)
2016-11-02T00:49:18.914003+00:00 heroku[run.6762]: Process running mem=888M(173.5%)
2016-11-02T00:49:18.914003+00:00 heroku[run.6762]: Error R14 (Memory quota exceeded)
2016-11-02T00:49:40.793596+00:00 heroku[run.6762]: Process running mem=902M(176.2%)
2016-11-02T00:49:40.793791+00:00 heroku[run.6762]: Error R14 (Memory quota exceeded)
2016-11-02T00:50:02.782887+00:00 heroku[run.6762]: Process running mem=953M(186.2%)
2016-11-02T00:50:02.783747+00:00 heroku[run.6762]: Error R14 (Memory quota exceeded)
2016-11-02T00:50:24.884095+00:00 heroku[run.6762]: Process running mem=957M(187.1%)
2016-11-02T00:50:24.884149+00:00 heroku[run.6762]: Error R14 (Memory quota exceeded)
2016-11-02T00:50:46.971098+00:00 heroku[run.6762]: Process running mem=1013M(198.0%)
2016-11-02T00:50:46.971098+00:00 heroku[run.6762]: Error R14 (Memory quota exceeded)
2016-11-02T00:51:08.599977+00:00 heroku[run.6762]: Process running mem=1017M(198.6%)
2016-11-02T00:51:08.600130+00:00 heroku[run.6762]: Error R14 (Memory quota exceeded)
2016-11-02T00:51:30.708360+00:00 heroku[run.6762]: Process running mem=1113M(217.4%)
2016-11-02T00:51:30.708475+00:00 heroku[run.6762]: Error R15 (Memory quota vastly exceeded)
2016-11-02T00:51:30.708583+00:00 heroku[run.6762]: Stopping process with SIGKILL
2016-11-02T00:51:31.593113+00:00 heroku[run.6762]: State changed from up to complete
2016-11-02T00:51:31.585712+00:00 heroku[run.6762]: Process exited with status 137
```

**Comment by camsaul** [comment]
that's it? Nothing after the `Liquibase is ready.` message?

**Comment by kapso** [comment]
@camsaul Here's the complete Heroku log https://gist.github.com/kapso/f86380d54e34c9a316af006613242100

**Comment by camsaul** [comment]
That's from when you ran `migrate print`?

**Comment by kapso** [comment]
Well I think migrate run print ended at `Liquibase is ready.`

**Comment by camsaul** [comment]
@kapso that doesn't seem like the case if you look at the logs you sent me 😓

**Comment by kapso** [comment]
@camsaul so yea, when `migrate print` is running  Heroku logs ends with memory warning and then dyno restarts I am guessing and then you see rest of the logs.

**Comment by kapso** [comment]
BTW I just ran `migrate print` again and the one-off Heroku process ended like this

```
$ heroku run java -jar target/uberjar/metabase.jar migrate print -a doorman-metabase
Running java -jar target/uberjar/metabase.jar migrate print on ⬢ doorman-metabase... up, run.3412 (Standard-1X)
11-02 01:24:40 INFO metabase.util :: Loading Metabase...
```

**Comment by kapso** [comment]
Guys, any update on this issue?

**Comment by camsaul** [comment]
@kapso try this

```bash
java -jar target/uberjar/metabase.jar migrate force
```

**Comment by kapso** [comment]
@camsaul still seeing the same exception.

**Comment by camsaul** [comment]
@kapso it seems like it's ignoring the arguments to `migrate` because when I do `migrate print` I get:

```
$ java -jar target/uberjar/metabase.jar migrate print
11-02 14:10:49 INFO metabase.util :: Loading Metabase...
11-02 14:10:54 INFO metabase.db :: Setting up Liquibase...
11-02 14:10:54 INFO metabase.db :: Liquibase is ready.
-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: liquibase.yaml
-- Ran at: 11/2/16 2:10 PM
-- Against: camsaul@jdbc:postgresql://localhost:5432/metabase
-- Liquibase version: 3.5.2
-- *********************************************************************

-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = '10.10.40.9 (10.10.40.9)', LOCKGRANTED = '2016-11-02 14:10:54.225' WHERE ID = 1 AND LOCKED = FALSE;

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;
```

And `migrate force` does:

```
$ java -jar target/uberjar/metabase.jar migrate force
11-02 14:10:20 INFO metabase.util :: Loading Metabase...
11-02 14:10:24 INFO metabase.db :: Setting up Liquibase...
11-02 14:10:24 INFO metabase.db :: Liquibase is ready.
```

**Comment by kapso** [comment]
@camsaul I guess I can run the SQL manually in the Metabase DB?

**Comment by camsaul** [comment]
@kapso Yeah you can try

```sql
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL;
```

**Comment by kapso** [comment]
Yea that works, phew, thanks!

**Comment by camsaul** [comment]
🎉

**Comment by pfeiffer** [comment]
Hi guys! Sorry to re-open this, but I'm seeing this error resurfaced in 0.30 on Heroku.

After upgrading to 0.30 I'm seeing this error in console on Heroku:

```
Aug 09, 2018 6:50:02 AM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: SQLException occurred while connecting to ec2-54-76-233-110.eu-west-1.compute.amazonaws.com:5432
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "...", user "...", database "....", SSL off
```

I've checked and `MB_DB_CONNECTION_URI` **does** contain the `?sslmode=require..` string by adding this to the startup script:

`echo "Using this MB_DB_CONNECTION_URI: ${MB_DB_CONNECTION_URI}"`

Running the migrations tool manually, I get the following output (notice the **SSL off** in last line):

```
08-09 06:49:21 INFO metabase.util :: Loading Metabase...
08-09 06:49:31 INFO util.encryption :: Saved credentials encryption is ENABLED for this Metabase instance. 🔐 
For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
08-09 06:49:42 INFO metabase.core :: Starting Metabase in STANDALONE mode
08-09 06:49:42 INFO metabase.core :: Launching Embedded Jetty Webserver with config: 
 {:port 44749}

08-09 06:49:42 INFO metabase.core :: Starting Metabase version v0.30.0 (04836dc release-0.30.0) ...
08-09 06:49:42 INFO metabase.core :: System timezone is 'GMT' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
08-09 06:49:45 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
08-09 06:49:45 INFO metabase.db :: Verifying postgres Database Connection ...
08-09 06:49:48 INFO metabase.db :: Verify Database Connection ...  ✅
08-09 06:49:48 INFO metabase.db :: Running Database Migrations...
08-09 06:49:48 INFO metabase.db :: Setting up Liquibase...
08-09 06:49:48 INFO metabase.db :: Liquibase is ready.
08-09 06:49:48 INFO metabase.db :: Checking if Database has unrun migrations...
08-09 06:50:01 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
08-09 06:50:01 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
08-09 06:50:02 INFO db.migrations :: Finished running data migrations.
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.notifications 👂
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle 👂
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.dependencies 👂
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.last-login 👂
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.revision 👂
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.sync-database 👂
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.view-log 👂
08-09 06:50:02 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications 👂
Aug 09, 2018 6:50:02 AM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: SQLException occurred while connecting to ....
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "...", user "....", database "...", SSL off
```
