### ISSUE TITLE
Objects that are unarchived without parent collection being unarchived are orphaned

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#26168]
**Describe the bug**
When you archive a collection, all of its sub-content (collections, cards, dashboards, etc) is also archived automatically. But if you unarchive any object within the collection individually, without unarchiving the parent collection, that object is now orphaned: it can be accessed via search but it won't show up anywhere in the collection sidebar. 

**Expected behavior**
If you unarchive an object that has an archived collection anywhere above it in the collection hierarchy, we should prompt the user to choose a new location for it, [per this Slack discussion](https://metaboat.slack.com/archives/C01LQQ2UW03/p1666902132539809). 

**Information about your Metabase Installation:**
Current master

**Comment by flamber** [comment]
Very related to #4013

**Comment by CarolynMooney** [comment]
This is also a problem for unarchiving the entire collection afterwards; the previously orphaned questions are not put back in dashboards. 

A nice feature would be for, when unarchiving a question, a message to let you know that the collection is archived - do you want to unarchive the entire collection? If yes, then the entire collection gets unarchived as it was before.
If no, then it would be okay to drop the question in the "Our Analytics" collection.

**Comment by CZvacko** [comment]
If you don't plan to fix it, you can temporarily add a note like "if you restore an item, make sure you restore the associated collection if it has been deleted" to the top of the archive page? This can save valuable time wasted by users (and admins) while debugging such unexpected behavior.

Another solution could be to change sort order the items in the archive list. Like by "archive time", the expectation is that the archived collection will be directly below the archived item, then the user may notice this. Currently the archived collection is at the end of the (loooong) list.
