### ISSUE TITLE
Today filter not working

### ISSUE THREAD

**Issue by scboffspring** [metabase/metabase#2617]
Hi,

General info first :
*  I am using the chrome browser.
*  My computer's OS is Windows 10.
*  I'm running Metabase on AWS with Docker, and locally with the last docker images available. 
*  My database is druid.
*  My Metabase version is the last docker images available (installed today)

When trying to use the Timestamp filter to select "Today", the following error occurs in the console : 
`Uncaught TypeError: Cannot read property 'toLowerCase' of null`

Happens only with "Today" filter, not with Yesterday or any other one.
After this, I need to refresh the whole question page, because nothing is saved correctly. Getting some :
`Uncaught TypeError: Cannot read property '_currentElement' of null` for every filters I add

Thank you

**Comment by jpagand** [comment]
Exactly the same error but with MongoDB

**Comment by dhirenpratap** [comment]
Same Error with Mysqldb

**Comment by key88sf** [comment]
Same error with Postgres. Had to revert to 0.17.0 to fix.

**Comment by scboffspring** [comment]
I apparently have some issues with other relatives date, like this week/this month/this year that returns the same data (apparently it seems to be the current day data). If I do the current year manually using the date filter, I am getting the correct result. Not error in the console though.

**Comment by camsaul** [comment]
I'm able to repro this on `0.18-SNAPSHOT` with the Sample dataset. If you try to filter by "Today" the filter widget stops working entirely until the page is refreshed 😢 

Here's the stacktrace:

![screen shot 2016-05-23 at 3 11 28 pm](https://cloud.githubusercontent.com/assets/1455846/15486198/c6340e96-20f8-11e6-8a33-361c79bd1b8a.png)
