### ISSUE TITLE
Google Sign-in fails because of unannounced change by Google

### ISSUE THREAD

**Issue by wildsonc** [metabase/metabase#26184]
**Describe the bug**
I've been using google authentication for over a year, and today it just stopped, I don't know what it could be.

**Logs**
No errors appear in logs or browser console.

**To Reproduce**
1. Go to login page
2. Click on login with google
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/72408418/199102876-643dc6b0-36d0-4dcf-80fb-33da7f6b584d.png)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome/106.0.0.0 Safari/537.36
- Your operating system: Mac OS X 10_15_7
- Your databases: Postgres
- Metabase version: 0.44.5
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
95% of my users authenticate through google, so it's pretty critical for me.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by almando** [comment]
i have the same problem. How to debug on docker container?

**Comment by yuriburk** [comment]
Relates to https://github.com/MomenSherif/react-oauth/issues/118

**Comment by ronaldobernardi** [comment]
Hello, I have the same problem:

Your browser and the version: Google Chrome Version 107.0.5304.88 (Official Build) (64-bit)
Your operating system: Windows 11 Pro - version: 22H2
Your databases: Postgres
Metabase version: v0.44.5
Metabase hosting environment: ECS - Fargate
Metabase internal database: Postgres

**Comment by ronanknob** [comment]
We are having the same problem here.

**Comment by jeancmsantana** [comment]
Up

Same problem here.

**Comment by btsperes** [comment]
Exactly the same issue here....

**Comment by cidraljunior** [comment]
Up. Same problem here.

**Comment by jeancmsantana** [comment]
@yuriburk I think the client_id return is only "wrong" in logins made in Brazil, for logins made in Portugal and USA it's working just fine.

**Comment by btsperes** [comment]
We've made some tests using NordVPN and in some regions it's working fine (e.g. Portugal and US). Maybe there's already a solution in place and we (hopefully) only need to wait to spread this fix to other regions....

**Comment by dggmsa** [comment]
Same problem here!

**Comment by yuriburk** [comment]
> Fixed [MomenSherif/react-oauth#119](https://github.com/MomenSherif/react-oauth/pull/119)

New https://github.com/MomenSherif/react-oauth/pull/121

**Comment by paoliniluis** [comment]
hi everyone, this seems to be a Google issue that either:
- Google needs to solve or,
- Google needs to officially communicate that they renamed a parameter so we can move forward and push the fix to the product

We'll be checking with the team tomorrow to see what's the best way forward, but according to this report, this is something that the Google team needs to solve ASAP. I'll be leaving this issue open so everyone is aware that this is going on

**Comment by rubenssoto** [comment]
Is there any workaround? Rollback metabase version could be an option?

**Comment by flamber** [comment]
From what I know the only workarounds would be to use a VPN, so you're in a different region, or use regular password logins https://github.com/metabase/metabase/issues/26184#issuecomment-1297884920, or create a custom build of Metabase with the patch applied https://github.com/metabase/metabase/issues/26184#issuecomment-1297918096.

**Comment by paoliniluis** [comment]
@rubenssoto, please be aware that this is NOT a Metabase issue but rather unilateral change from Google which is affecting us since we provide Google SSO as an option.

**Comment by marceldegraaf** [comment]
Same issue started occurring for us a few hours ago, in The Netherlands.

**Comment by apostoltego** [comment]
We're seeing the same in the UK

**Comment by dannyeuu** [comment]
@paoliniluis we understand that is a Google issue, but to work until Google fix it, how to keep Metabase running? Our firsts users created were created with user/pass can now can access and the others with Google SSO only cannot even create or reset a password.
- Can we update something on user table that can allow user to create a password?
- You feel that the Metabase workaround on v0.44.6 can be released soon?

**Comment by cidraljunior** [comment]
@dannyeuu look at my comment https://github.com/metabase/metabase/issues/26184#issuecomment-1297884920

i got around this problem using this

**Comment by kikocastro** [comment]
Expanding on https://github.com/metabase/metabase/issues/26184#issuecomment-1298483828, here's the temp solution, until google fixes it:

1. Remove your google client_id at Metabase > Admin > Google Sign In
2. run `update core_user set google_auth = false where is_active=true;` to remove the flag on the database (otherwise, the recover password won't work)

**Comment by dannyeuu** [comment]
Great, works for me too, BTW to keep secuty only allow user by user that needs with emergency 

Vi que temos vários brasileiros aqui, temos o grupo de Metabase Brasil https://web.telegram.org/k/#@metabasebrasil

**Comment by flamber** [comment]
Fix implemented and 44.6 coming in a few hours (#26198).

**Comment by AlejandroGCorzo** [comment]
> Expanding on [#26184 (comment)](https://github.com/metabase/metabase/issues/26184#issuecomment-1298483828), here's the temp solution, until google fixes it:
> 
> 1. Remove your google client_id at Metabase > Admin > Google Sign In
> 2. run `update core_user set google_auth = false where is_active=true;` to remove the flag on the database (otherwise, the recover password won't work)

Can you explain more how to do that? for a newbie hehe

**Comment by dannyeuu** [comment]
> > Expanding on [#26184 (comment)](https://github.com/metabase/metabase/issues/26184#issuecomment-1298483828), here's the temp solution, until google fixes it:
> > 
> > 1. Remove your google client_id at Metabase > Admin > Google Sign In
> > 2. run `update core_user set google_auth = false where is_active=true;` to remove the flag on the database (otherwise, the recover password won't work)
> 
> Can you explain more how to do that? for a newbie hehe

Run an update on Metabase database for a specific user:
```sql
update
	public.core_user
set
	google_auth = false,
	updated_at = current_timestamp at time zone 'utc'
where
	google_auth = true
	and email = 'user@domain.com'
```

**Comment by paoliniluis** [comment]
We have just finished the release process, if you run Metabase self hosted, please upgrade to 44.6 that contains the fix
