### ISSUE TITLE
Unecessary get values call

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#26190]
**Describe the bug**
When selecting a filter with an `hour` expression, FE make a 404 API call.

**To Reproduce**
1. Open the Network tab
2. New question
3. Sample Dataset -> Orders
4. Custom column `hour of created at  = hour([Created At])
5. Click on filter, select the `hour of created at` expresison.
6. Notice FE make a call that result in a 404 status.

**Expected behavior**
I think FE shouldn't make this call at all

**Screenshots**
![Screen Shot 2022-11-01 at 17 58 06](https://user-images.githubusercontent.com/25661381/199218426-924ed8cf-75e2-441c-87b9-b69588358883.png)

**Information about your Metabase Installation:**
master(a0f6a8c5ec3e54592b52b9848eeb9fceb300d34d)

**Severity**
Minor

**Additional context**

**Comment by uladzimirdev** [comment]
even version 47 is not affected, most likely the same as https://github.com/metabase/metabase/issues/23707

endpoint itself is removed https://github.com/metabase/metabase/pull/44629

closing for now, works as expected in master e5e0c2ccd0 and 50.6
