### ISSUE TITLE
Metabase query status pending, never resolving

### ISSUE THREAD

**Issue by dustinm800** [metabase/metabase#26205]
**Describe the bug**
Metabase not sending query to database in one of our environments.   Running select 1; network status is (pending), query never finishes.  No questions or dashboards are working in this environment.  Issue started Nov 1st midday CST.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to New Question and select my us-prod environment
2. Enter query "select 1;"
3. wait, forever

**Expected behavior**
This query should return the value 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/10855792/199332096-c9bbce10-4ab7-4cc3-aa13-a847bc22dfd6.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
- Chrome Version 106.0.5249.119 (Official Build) (x86_64)
- macOS Big Sur v11.7
- Postgres
- Metabase version: (You're on version v1.44.5 Built on 2022-10-17

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: Blocking.  The is affecting dashboards in our production environment

**Additional context**
This is affect ALL dashboards etc. using our us-prod database.  They all worked this morning and now all never resolve.  I can connect directly to the database with the same role and run the same queries and they execute in the expected amount of time.

**Comment by flamber** [comment]
Hi @dustinm800 Please use the support email, when using Metabase Cloud, since this is connection issue specific to your instance or database.
If it has happened only for a specific database, then try going to Admin > Databases > (db) > without changing anything, click "Save changes", which tries to renew all connections. If that doesn't work, then use the support email.

**Comment by dustinm800** [comment]
Will do thanks!
