### ISSUE TITLE
Custom region maps only shows partial map visualization

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#26213]
**Describe the bug**
Custom region maps only shows partial map visualization.
Regression since 0.44.0. History #23450 and #15560.

**To Reproduce**
1. Admin > Settings > Maps > Add a map > example:
`https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/world.json`
2. Native > Sample > `select 'US' region, 5 val`
3. Change visualization to Map > select "Region map", then the custom map
![image](https://user-images.githubusercontent.com/1447303/199487692-6d131fbf-55db-400a-8ccf-aaaa4ed675e0.png)

**Information about your Metabase Installation:**
Tested 0.43.5 thru 0.44.6. Regression since 0.44.0, where previously it would show duplicated maps as #15560.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by denics** [comment]
Any news on this?

**Comment by iethree** [comment]
Here's maybe a better repro: it has something to do with the shape of the map. here are 2 different GEOJSONs

world: `https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/world.json`
california: `https://raw.githubusercontent.com/codeforgermany/click_that_hood/main/public/data/california-counties.geojson`

![Screen Shot 2022-12-22 at 12 38 05 PM](https://user-images.githubusercontent.com/30528226/209213243-c3d56dd0-bb32-41ae-afbe-73fa3bd83d4a.png)

https://github.com/metabase/metabase/blob/ccac9d9af9addbc8eb689a802b5d5ccb92b1638a/frontend/src/metabase/visualizations/components/LeafletChoropleth.jsx#L103

Replacing this line that was deleted in https://github.com/metabase/metabase/pull/23454 gives us

![Screen Shot 2022-12-22 at 12 40 39 PM](https://user-images.githubusercontent.com/30528226/209213516-be7e2457-5c7a-4ad1-9e2d-e43070938cc6.png)

so i guess it's time to do some geometry 😁

**Comment by kevngzc** [comment]
@iethree Do you know when this issue could be solved and delivered in a next version of Metabase ?

Regards,

**Comment by iethree** [comment]
> @iethree Do you know when this issue could be solved and delivered in a next version of Metabase ?
> 
> Regards,

@kevngzc this fix is merged and should make it into metabase 0.45.2
