### ISSUE TITLE
Cannot show metabase properly only on windows

### ISSUE THREAD

**Issue by crawfordma** [metabase/metabase#26225]
**Describe the bug**
Cannot show metabase container correctly with nginx on windows.

**Logs**
On mac OS(firefox):

<img width="1617" alt="截屏2022-11-03 11 06 11" src="https://user-images.githubusercontent.com/110077073/199640350-f2701470-d36f-4509-9b7a-0ff23cb644c8.png">
<img width="1430" alt="截屏2022-11-03 11 07 43" src="https://user-images.githubusercontent.com/110077073/199640520-51079038-d156-4bce-97b4-8ca4e7d0d956.png">

On windows(firefox):
Found same issue on IE, edge, chrome.
<img width="1572" alt="截屏2022-11-03 11 06 50" src="https://user-images.githubusercontent.com/110077073/199640451-d8ca3f43-7b49-4b22-a71c-1100dd8ef004.png">
<img width="1286" alt="截屏2022-11-03 11 07 09" src="https://user-images.githubusercontent.com/110077073/199640482-dc29e556-6872-4cdc-8d45-5b0027668fc4.png">

1. Setup metabase container
2. Setup nginx and redirct http://metbase:3000 to my host
3. linked my mongodb to metabase
4. Observed the difference between macOS and windows with same browser

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- windows:
- 106.0.3 (64-bit)
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- mongodb
- Metabase version: (e.g., 0.19.3)
- 0.44.4
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- RedHat
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by flamber** [comment]
Hi @crawfordma 
You have problem with some CSS files not correctly handled in your reverse-proxy. Check your browser developer Network-tab and your Nginx logs.

**Comment by crawfordma** [comment]
Hi Flamber,
I overwrite the volume of /assests, that's why metabase cannot show properly. But I wonder how it only affects windows?
