### ISSUE TITLE
On Questions with Joined Tables, Reordering Column Deselects all columns from secondary table [BigQuery]

### ISSUE THREAD

**Issue by GJMcClintock** [metabase/metabase#26222]
**Describe the bug**
Using the query editor, if you select any number of tables and join them together - after reordering any of the columns, all tables from all but the base table are deselected.

**Logs**
Cloud

**To Reproduce**
1. Go to New
2. Click on Question
3. Select primary table
4. Join data and match keys
5. Click visualize
6. Reorder and column from joined table
7. Click visualize again to refresh, all columns missing.

**Expected behavior**
The columns should appear as named/ordered in the visualization panel. 

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 106.03, Chrome , Safari 16.1 all tested
- Your operating system: OS X Ventura 13.0
- Your databases: BigQuery
- Metabase version: Cloud
- Metabase hosting environment: Cloud

**Severity**
This is annoying and blocking as it breaks reporting by not being able to create viz.

**Additional context**

**Comment by flamber** [comment]
Hi @GJMcClintock 
It very much sounds like https://github.com/metabase/metabase/issues/22563#issuecomment-1126924971, but your steps-to-reproduce indicates you are seeing this problem with much less specifics.

**Comment by GJMcClintock** [comment]
> Hi @GJMcClintock It very much sounds like [#22563 (comment)](https://github.com/metabase/metabase/issues/22563#issuecomment-1126924971), but your steps-to-reproduce indicates you are seeing this problem with much less specifics. Is this a duplicate of #22563 or just very related? If not a duplicate, then I cannot reproduce with the steps you have provided.

Yes - similar it seems. But without needing to group by or do any aggregations. Simply reordering columns after joining tables drops all the joined columns. Also does not happen if selecting from a single table.

This does not happen after converting to a model or a SQL question. only through the question editor.

**Comment by flamber** [comment]
@GJMcClintock Okay, I'm not able to reproduce with the steps you have provided. Can you provide steps to reproduce with Sample Database?

**Comment by GJMcClintock** [comment]
@flamber  - The Sample DB in our cloud instance has been deleted, is there a way to restore it?

**Comment by GJMcClintock** [comment]
@flamber - can I get an update on this?

A couple people on the dbt slack have mentioned they are experiencing the same issues as well. If I can get my sample db restored I can try to recreate it. Or If I have a contact method I can send you a scrubbed video showing it.

**Comment by flamber** [comment]
@GJMcClintock 
You can get the Sample Database back by going to Admin > Databases > scroll to the bottom and click the gray link.
If other people are experiencing problems, then they should open issues for it or use the forum: https://discourse.metabase.com/

**Comment by GJMcClintock** [comment]
@flamber Any update on this? Or a way to reach out to customer support? This is for a client that is on a paid cloud plan.

**Comment by flamber** [comment]
@GJMcClintock I've created an issue for this: #27464 - upvote by clicking :+1: on the first post
