### ISSUE TITLE
Ability to kill a running query/question

### ISSUE THREAD

**Issue by key88sf** [metabase/metabase#2622]
Sometimes we run a question that is not finished yet or where the user selected the wrong filters. This can result in a query that takes a VERY long time to finish or timeout (even with the proposed timeout feature).

It would be nice I think to have an ability to kill the query, so the user can edit it instead of having to wait forever for it to finish or timeout before editing.  What do you think?

**Comment by camsaul** [comment]
Duplicate of #2181.

@key88sf this has been implemented and will ship with the next release

**Comment by key88sf** [comment]
Thanks :)
