### ISSUE TITLE
Autosuggestion rate is too high

### ISSUE THREAD

**Issue by fabioaraujopt** [metabase/metabase#26237]
**Describe the bug**
We are using metabase to connect to a huge datalake, this is used by several people in parallel. Most of them are using the "SQL Query" question. This is producing several calls on the `api/database/XX/autocomplete_suggestions`, which have a huge overhead to our datalake turning most of the time in restarts and 503 for a few moments. 

**Expected behavior**
There should exist a way to limit this queries or to disable this feature entirely.

**Screenshots**
[image](https://ibb.co/R0ZKr7p)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Metabase version: v0.44.2

**Severity**
Creates down time on our systems.

**Additional context**
The workaround for this was to disable this route on the ingress level.

**Comment by flamber** [comment]
Hi @fabioaraujopt 
The autosuggestion is making queries against the Metabase application database, not your data sources.
So if your data sources are crashing, then it's a separate problem, but without logs it's difficult to tell.
You change the query type or disable it: https://github.com/metabase/metabase/issues/24452#issuecomment-1200376628

**Comment by fabioaraujopt** [comment]
After reviewing your comment I noticed that the problem is in fact the metabase database and not the data source. We have here some suggestions taking as long as 9 minutes. 

`GET /api/database/11/autocomplete_suggestions 200 9.2 mins`

**Comment by flamber** [comment]
The follow the workaround as listed in https://github.com/metabase/metabase/issues/24452#issuecomment-1200376628
