### ISSUE TITLE
Attach full table CSV to pulse?

### ISSUE THREAD

**Issue by key88sf** [metabase/metabase#2623]
Feature request:  Ability to send the entire query results as a CSV (or maybe inlined table in email) on an email pulse.  Many of our users want the report data but don't actually use (or need to use) Metabase itself. It would be great to just have the pulse send the entire set of results as a CSV for them to look at, instead of just linking back to the metabase card.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by solomongifford** [comment]
We need this as well.

**Comment by zwalden** [comment]
Would love this over here; with the limited role management (so far? am I missing something?) it would be absolutely great to send a CSV to a user, or maybe even random email. It would prevent the need for them to have access, and still get analytics/data sent to them.

**Comment by tlrobinson** [comment]
Perhaps we could add a little ".csv" button on the right of each item the pulse card picker, similar to the date grouping picker in the query builder.

**Comment by salsakran** [comment]
big +1 on this from my conversation with a heavy user (@HelmiRifai )

**Comment by calleo** [comment]
+1

**Comment by martinlee556** [comment]
+1 too.

**Comment by JonatanRoose** [comment]
+1

**Comment by alenave** [comment]
I am not able to locate the button, please help me out 
Thanks

**Comment by davidjhpgcc** [comment]
+1 This is highly needed

**Comment by vsreddy1602** [comment]
+1

**Comment by anthonysexton** [comment]
+1

**Comment by salsakran** [comment]
Hey, could everyone who's +1'd chime in with a bit of color around what they're planning on using this for? 

We're looking into this, and the specific questions are --

* Would you still need this if you could give the people you'd send the csv a locked down account?
* Would you still need this if you could mark a question or dashboard as "public" and have the user login?
* Are you sending these CSVs to people inside or outside your company?

paging @anthonysexton @vsreddy1602 @davidjhpgcc @alenave @JonatanRoose @marketingnerds @calleo @zwalden @solomongifford

**Comment by key88sf** [comment]
@salsakran :
Would you still need this if you could give the people you'd send the csv a locked down account?
==> Yes. We don't want most of these people to deal with ever logging in.

Would you still need this if you could mark a question or dashboard as "public" and have the user login?
==> Yes. Same as above.

Are you sending these CSVs to people inside or outside your company?
==> Currently only inside.

**Comment by salsakran** [comment]
Can you elaborate a bit on what kinds of reports you're thinking of? Size of csv, etc? Just trying to get a handle on the underly business process/info handoff this automates.

**Comment by key88sf** [comment]
@salsakran Similar to my original description at the start of this request. We have a lot of "non-tech" users who have a tough time understanding Metabase itself, and really just need to get some weekly/daily report data which they plug into Excel or Google Sheets.

Typically these are relatively small sized CSVs....on the order of 10-100 rows, though occasionally they might be larger. I could see having a "max-row-size" or "max-file-size" limit to this feature as well if that could help.

**Comment by davidjhpgcc** [comment]
1a. Yes because the users at our company demand an email.  They are not willing to login to anything.  They want the information to simply show up in their email when there is work to do.  

1b. Trying to remember a login and password is asking for too much for those employees.

1c. Every time a new employee is hired or leaves there is too much login and password maintenance for IT.  It is far easier to send one email email to one group email address vs creating and removing logins.

1d. The email serves as a reminder that there is work.  It is like an alarm clock.

3. Inside

Re size, it would be ideal if you can allow as large as possible.  Some of our reports are 10MB csv or xls attachments with 100,000 rows.

**Comment by davidjhpgcc** [comment]
One more thing, also needed is an option to only send that email when rows>0.  Some users want an email when there are 0 results, some do not.

**Comment by anthonysexton** [comment]
For us, these are daily reports for teams like finance who get different extracts at points in time for various reconciliations etc. 

Would you still need this if you could give the people you'd send the csv a locked down account?
--> Yes. 

Would you still need this if you could mark a question or dashboard as "public" and have the user login?
--> Yes

Are you sending these CSVs to people inside or outside your company?
--> Inside

We don't want them to have to log into another system just to get what they are after. Another option might be a link in the email to click and download but if the link expired etc. then they'd probably end up needing a login to Metabase anyway which would defeat the purpose of what we're trying to achieve here. 

Re. Size - Sometimes they can be pretty big. Maybe a file size cap would be useful here to stop it from junking up inboxes but this would need to fall back to something should a report be bigger than what's allowed.

Historically have used Pentaho for things like this which become set and forget and make it easy to satisfy new raw data reporting requirements for different teams as they arise.

**Comment by JonatanRoose** [comment]
_Would you still need this if you could give the people you'd send the csv a locked down account?_
Yes, we are sending them to external people. We are using the SSO of Google with our domain. Therefore we need to be able to send specific information to outsiders without them having access to our dashboards.

_Would you still need this if you could mark a question or dashboard as "public" and have the user login?_
Yes

_Are you sending these CSVs to people inside or outside your company?_
Most of the time outside.

**Comment by pdiniz13** [comment]
+1
Hey, could everyone who's +1'd chime in with a bit of color around what they're planning on using this for?

We're looking into this, and the specific questions are --

Would you still need this if you could give the people you'd send the csv a locked down account?
Yes

Would you still need this if you could mark a question or dashboard as "public" and have the recipient access the csv without a Metabase user account?
Yes

Are you sending these CSVs to people inside or outside your company?
Both

If you still need this for non-permissions related reasons, could you elaborate a bit about the use case?
Would be using this to send out weekly/monthly reports that user can just download and view in excel or google sheets.

**Comment by rafaelveloso** [comment]
+1

**Comment by Alexanderbez** [comment]
+1

**Comment by edmarriner** [comment]
+1

**Comment by t1ag0** [comment]
>> Would you still need this if you could give the people you'd send the csv a locked down account?
yes 
>>Would you still need this if you could mark a question or dashboard as "public" and have the 
yes
>>recipient access the csv without a Metabase user account?
yes
>>Are you sending these CSVs to people inside or outside your company?
both.


Most business user do not want to deal with external tools, they just want a CSV to work it on Excel on their laptop. I offer them very complete Tableau Dashboards and most of them ignores them.

**Comment by noamgat** [comment]
+1

**Comment by dsmegha** [comment]
+1

**Comment by MathiasDL** [comment]
+1

**Comment by OnShiftJT** [comment]
+1 especially around emailing or saving the full results in a shared folder

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by brnt** [comment]
+1

* We, too, want to send reports to folks with no access to our Metabase dashboards.
* Lots of people copy-paste data into spreadsheets for integration into their own reports. Having that data waiting for them on Monday morning (without admin intervention) would be a huge win.

**Comment by camsaul** [comment]
@brnt, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by brnt** [comment]
Already did. There was a request in the thread for details about how people would use the feature, so I commented with my specific details. Just trying to be helpful, not obnoxious.

**Comment by orware** [comment]
I was also a bit surprised by the lack of functionality here when trying it a few minutes ago for a question I had created which had maybe 7-10 fields in it.

The email only included the first 3 columns (all of which did not include the key information needed) even after I made some adjustments to the question itself and sent another test email.

Currently on our campus we use the evisions' Argos Reporting tool for most of our reporting needs, plus we also have iDashboards, though it has limited usage at the moment. Argos has good functionality for sending data via email so having a bit more functionality in this regard would definitely be handy for Enterprise groups using the software. Also, there didn't seem to be an option to provide a required param when I tried including a test question I had created that had one (it simply didn't work at all for including into the Pulse). Having the option to include an end date for the pulse might be useful for those pulse that are time sensitive and then the organization moves on to something else.

**Comment by dsmegha** [comment]
👍

**Comment by key88sf** [comment]
@salsakran What is the status of this? Can this be done for next version? 🙏

**Comment by dsmegha** [comment]
Would love to have this in the next version.

**Comment by doodlebro** [comment]
This is over a year old, any update on this functionality being added?

**Comment by dannyeuu** [comment]
There is someone that can do this with Clojure? It not my ability.

**Comment by mokra** [comment]
will it be possible to format the CSV file?

**Comment by dannyeuu** [comment]
Thanks @senior

**Comment by rodolfoviolac** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by mazameli** [comment]
@rodolfoviolac this was implemented by https://github.com/metabase/metabase/pull/6556 and will be included in our next release, which will be coming out very soon.

**Comment by pygeek** [comment]
+1

**Comment by mazameli** [comment]
In case anyone missed the memo, this feature has been built and is available for use in the latest version of Metabase which just came out yesterday!

https://metabase.com/blog/Metabase-0.28/

**Comment by ozombo** [comment]
> Can you elaborate a bit on what kinds of reports you're thinking of? Size of csv, etc? Just trying to get a handle on the underlying business process/info handoff this automates.

In my scenario I'd like to send reports (as is) at 11:00PM on the last calendar day of the month, if a user accesses the question  say 12:01AM the next day, my report becomes invalid as the tables might have been updated.
