### ISSUE TITLE
Dashboard sticky filter incorrectly positioned, when moving between dashboards

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#26230]
**Describe the bug**
Dashboard sticky filter incorrectly positioned, when moving between dashboards that contains vertical scroll.
The more filters there are, the more problematic the sticky becomes, since it will start covering top card titles/visualizations.
Combined with #26229, it can become quite confusing.

**To Reproduce**
1. On a dashboard, add a filter (doesn't matter if it's connected) and a Textbox that should be resized, so it causes vertical scroll
![image](https://user-images.githubusercontent.com/1447303/199724401-a0f0c485-eff4-46fe-b6fc-80f27b375568.png)
2. Duplicate that dashboard
3. Let's bookmark both dashboards for easier reproduction, but alternatively cards would be added to each dashboard with Click Behavior to another dashboard, which causes the same behavior
4. On a dashboard, scroll to bottom, which will make the filter sticky (as expected)
![image](https://user-images.githubusercontent.com/1447303/199725165-540c9530-14d6-41ea-a943-232f65784265.png)
5. Now go to the other dashboard by clicking the other dashboard bookmark.
The scroll position is correct (top), but sticky filters are incorrectly applied, which covers the dashboard title.
![image](https://user-images.githubusercontent.com/1447303/199725866-2e2fae7d-7ece-4b41-92ca-1b3d76c5f862.png)

**Expected behavior**
Moving between dashboards should set scroll position to top and not have sticky filters. Same behavior no matter how moving between dashboards are done (bookmark, search suggest, Click Behavior, etc).

**Information about your Metabase Installation:**
Tested 0.44.6

**Comment by Tony-metabase** [comment]
I am able to replicate this on 45.1
