### ISSUE TITLE
Connection Pools Details Link doesn't respect site url

### ISSUE THREAD

**Issue by udit-001** [metabase/metabase#26243]
**Describe the bug**
I have my metabase instance running on `site.example.com/mb/` and I was on the page `site.example.com/mb/admin/troubleshooting/help` where I clicked on connection pool details section which linked me to `https://site.example.com/api/util/diagnostic_info/connection_pool_info`

![image](https://user-images.githubusercontent.com/23015406/199861657-9369bdf8-bde9-4266-913c-faabcfb652d6.png)

**Expected behavior**
`https://site.example.com/api/util/diagnostic_info/connection_pool_info` should instead link to `https://site.example.com/mb/api/util/diagnostic_info/connection_pool_info` as per what the site url is configured to.

**Information about your Metabase Installation:**
Metabase version: 0.44.6

**Comment by paoliniluis** [comment]
This is an issue with Metabase running in sub paths https://github.com/metabase/metabase/issues/30895
