### ISSUE TITLE
Patch file 0.44.6 not on the website

### ISSUE THREAD

**Issue by trsilva32** [metabase/metabase#26246]
Morning, Folk,
The file to update the EB 0.44.5 on the [Metabase](https://www.metabase.com/docs/v0.44/installation-and-operation/running-metabase-on-elastic-beanstalk#deploying-new-versions-of-metabase-on-elastic-beanstalk) website still showing 0.44.5.
Can you please help me on that?
Thanks

**Comment by flamber** [comment]
We'll get the website updated soon.
https://downloads.metabase.com/v0.44.6/metabase-aws-eb.zip
