### ISSUE TITLE
Add dashboard caching to the documentation + caching prevalence

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#26254]
We have now dashboard level caching, we should add what that means to the documentation. 

Also, we should add how caching works in case:
- there's question level caching set up and then from a dashboard where that question is you change the caching ttl
- if there's a question in 2 dashboards, and you define in those different caching ttl's, which is the one that the question will end up having

**Comment by flamber** [comment]
For reference:
https://www.metabase.com/docs/latest/questions/sharing/answers#caching-results
https://www.metabase.com/docs/latest/dashboards/introduction#caching-dashboards

**Comment by paoliniluis** [comment]
Seems like if a dashboard has a living ttl the question will pull from the cache,but if you to to the question and the ttl has expired it will be retrieved from the db.

**Comment by Tony-metabase** [comment]
When we are adding the documentation we should also consider this fact:

https://github.com/metabase/metabase/issues/29075

Since right now the docs are a bit misleading
