### ISSUE TITLE
Columns sizeX and sizeY does not exist in report_dashboardcard

### ISSUE THREAD

**Issue by fhziliotti** [metabase/metabase#26258]
**Describe the bug**
When we change or create a dashboard and click save, it shows error 500 with the logs below:

**Logs**
{"via":[{"type":"org.postgresql.util.PSQLException","message":"ERROR: column \"sizeY\" of relation \"report_dashboardcard\" does not exist\n  Position: 169","at":["org.postgresql.core.v3.QueryExecutorImpl","receiveErrorResponse","QueryExecutorImpl.java",2676]}],"trace":[["org.postgresql.core.v3.QueryExecutorImpl","receiveErrorResponse","QueryExecutorImpl.java",2676],["org.postgresql.core.v3.QueryExecutorImpl","processResults","QueryExecutorImpl.java",2366],["org.postgresql.core.v3.QueryExecutorI
....

{"via":[{"type":"org.postgresql.util.PSQLException","message":"ERROR: column \"sizeX\" of relation \"report_dashboardcard\" does not exist\n  Position: 169","at":["org.postgresql.core.v3.QueryExecutorImpl","receiveErrorResponse","QueryExecutorImpl.java",2676]}],"trace":[["org.postgresql.core.v3.QueryExecutorImpl","receiveErrorResponse","QueryExecutorImpl.java",2676],["org.postgresql.core.v3.QueryExecutorImpl","processResults","QueryExecutorImpl.java",2366],["org.postgresql.core.v3.QueryExecutorI

**To Reproduce**
1. Go to create new Dashboard
2. Add question and Click on Save
3. See error

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 107
- Your operating system: Any
- Your databases: Postgres
- Metabase version: 0.44.6
- Metabase hosting environment: K8S GCP
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
High impact.

**Additional context**
When accessing the metabase database, we identified that in the table "report_dashboardcard" there are the fields "size_x" and "size_y" but in the most recent versions they were changed by SizeX and SizeY, and there was no database migration changing these columns .
We made the change manually, and it worked.
Could you check?

**Comment by flamber** [comment]
Hi @fhziliotti 
That's because you have tried out the release candicate of v45 and then downgraded instead of reverting to a backup.
For reference: https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml#L12725-L12765

You need run the following query on your application database if you don't have an option to revert to a backup.
```
-- Postgres
ALTER TABLE report_dashboardcard RENAME COLUMN size_x TO "sizeX";
ALTER TABLE report_dashboardcard RENAME COLUMN size_y TO "sizeY";
DELETE FROM databasechangelog WHERE id IN ('v45.00-028', 'v45.00-029');
```

**Comment by fhziliotti** [comment]
@flamber thanks

**Comment by enapupe** [comment]
FYI I also had issues with the above (slightly different query fixed it). I'm currently running metabase as a docker service without 
a pinned version, one or twice a year I get a similar migration-related issue.
