### ISSUE TITLE
Change Metabase label to BigQuery connections

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2627]
We've gotten a request to change our format from G in relation to our testing credits. 

Current: 
Metabase v0.18.0-snapshot (7cbdd7e master)
Requested format: 
Metabase/v0.18.0-snapshot (GPN:Metabase; 7cbdd7e master)

**Comment by camsaul** [comment]
![screen shot 2016-05-19 at 11 33 46 am](https://cloud.githubusercontent.com/assets/1455846/15405148/9465bca2-1db5-11e6-902e-862587ac0db4.png)
?

**Comment by salsakran** [comment]
oh. cool.

**Comment by camsaul** [comment]
closing since we're already doing this

**Comment by salsakran** [comment]
Updated + re-opening to reflect a request from the partner's folks at Google
