### ISSUE TITLE
Snowflake connection using Federated Authentication SSO with Okta fails to connect because of incorrect `account` parameter

### ISSUE THREAD

**Issue by cabarria** [metabase/metabase#26272]
When authenticating with Okta using the `authenticator=https://myidp.okta.com` in the advanced options, the driver fails to connect to snowflake. https://docs.snowflake.com/en/user-guide/jdbc-parameters.html#authenticator

The issue as confirmed by Snowflake support is the incorrect configuration of the account parameter.

As can be seen in the log entries below, the account parameter has been set to `account=mycomp.us-east-1`, but it should be set to `account=mycomp` instead.
Please keep in mind that the account name on the form is correctly entered as `mycomp.us-east-1` as that's needed to properly establish the endpoint for the connection string as `https://mycomp.us-east-1.snowflakecomputing.com`.

However, the `account` parameter that must be passed to the driver needs to drop the region `us-east-1` and only use `mycomp`.

**Logs**
```
2022-11-01 18:24:27.267 n.s.c.core.SFSession FINE open:369 - input: server=https://mycomp.us-east-1.snowflakecomputing.com:443/, account=mycomp.us-east-1, user=first.last@mycomp.com, password=***, role=, database=MY_DATABASE, schema=, warehouse=MY_WAREHOUSE, validate_default_parameters=null, authenticator=https://myidp.okta.com, ocsp_mode=FAIL_OPEN, passcode_in_password=null, passcode=****  private_key=(null), disable_socks_proxy=null, application=null, app_id=JDBC, app_version=3.13.21, login_timeout=null, network_timeout=null, query_timeout=null, tracing=all, private_key_file=null, private_key_file_pwd=****  session_parameters: client_store_temporary_credential=null
2022-11-01 18:24:29.332 n.s.c.core.SessionUtil FINE federatedFlowStep1:1230 - authenticator-request response: {
  "data" : null,
  "code" : "390400",
  "message" : "Bad request; operation not supported.",
  "success" : false,
  "headers" : null
}
2022-11-01 18:24:29.335 n.s.c.core.SessionUtil FINE federatedFlowStep1:1235 - response = {
  "data" : null,
  "code" : "390400",
  "message" : "Bad request; operation not supported.",
  "success" : false,
  "headers" : null
}
2022-11-01 18:24:29.339 n.s.c.jdbc.SnowflakeSQLException FINE <init>:44 - Snowflake exception: Bad request; operation not supported., sqlState:08001, vendorCode:390,400, queryId:
```

This is an example of the driver successfully connecting using the correct parameters as shown through SQLWorkbench:
```
2022-11-01 00:20:00.875 n.s.c.core.SFSession FINE open:369 - input: server=https://mycomp.us-east-1.snowflakecomputing.com:443/, account=mycomp, user=first.last@mycomp.com, password=***, role=null, database=null, schema=null, warehouse=null, validate_default_parameters=null, authenticator=https://myidp.okta.com, ocsp_mode=FAIL_OPEN, passcode_in_password=null, passcode=****  private_key=(null), disable_socks_proxy=null, application=null, app_id=JDBC, app_version=3.13.21, login_timeout=null, network_timeout=null, query_timeout=null, tracing=ALL, private_key_file=null, private_key_file_pwd=****  session_parameters: client_store_temporary_credential=null
2022-11-01 00:20:02.565 n.s.c.core.SessionUtil FINE federatedFlowStep1:1230 - authenticator-request response: {
  "data" : {
  "tokenUrl" : "https://myidp.okta.com/api/v1/sessions?additionalFields=cookieToken",
  "ssoUrl" : "https://myidp.okta.com/app/snowflake/exk1h5nt7snJPsOQP0h8/sso/saml",
  "proofKey" : null
},
  "code" : null,
  "message" : null,
  "success" : true
}
```

**To Reproduce**
Add a Snowflake database with the following parameters:
![image](https://user-images.githubusercontent.com/18726993/200350417-ce6b3458-fa49-4521-a3b1-0d146945d663.png)

**Expected behavior**
Metabase should connect to the snowflake database

**Information about your Metabase Installation:**
{
"browser-info": {
"language": "en-US",
"platform": "Win32",
"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.52",
"vendor": "Google Inc."
},
"system-info": {
"file.encoding": "Cp1252",
"java.runtime.name": "OpenJDK Runtime Environment",
"java.runtime.version": "11.0.16.1+1-LTS",
"java.vendor": "Microsoft",
"java.vendor.url": "https://www.microsoft.com/",
"java.version": "11.0.16.1",
"java.vm.name": "OpenJDK 64-Bit Server VM",
"java.vm.version": "11.0.16.1+1-LTS",
"os.name": "Windows 10",
"os.version": "10.0",
"user.language": "en",
"user.timezone": "America/New_York"
},
"metabase-info": {
"databases": [
"h2"
],
"hosting-env": "unknown",
"application-database": "h2",
"application-database-details": {
"database": {
"name": "H2",
"version": "1.4.197 (2018-03-18)"
},
"jdbc-driver": {
"name": "H2 JDBC Driver",
"version": "1.4.197 (2018-03-18)"
}
},
"run-mode": "prod",
"version": {
"date": "2022-10-17",
"tag": "v0.44.5",
"branch": "release-x.44.x",
"hash": "29fab4d"
},
"settings": {
"report-timezone": null
}
}
}

**Severity**
This is blocking our usage of Metabase for Snowflake. We've been using Metabase for Athena and Postgresql without issues, but our Data Warehouse is in Snowflake.

[meta-snowflake-debug-11012022.log](https://github.com/metabase/metabase/files/9953181/meta-snowflake-debug-11012022.log)

Previous issue #26155

**Comment by cabarria** [comment]
Here is some additional information from Snowflake support:

The only documentation we have is concerning the account identifier:
https://docs.snowflake.com/en/user-guide/admin-account-identifier.html

The account identifier you're using is the correct one:
mycomp.us-east-1

The issue you run into, is that you provided a server name of:
mycomp.us-east-1.snowflakecomputing.com:443

combined with the account parameter:
mycomp.us-east-1

That combination seems to cause an issue, and I have been able to reproduce your problem. I'm not sure how you're creating the connection, but in my case, I am explicitly creating a JDBC connection string, and then I passed the account parameter simultaneously. I assume you're doing the same.

If you're creating the connection string, then it's redundant to provide the account parameter. It's possible mainly for historical reasons related to the fact that we allow accounts with underscore characters, while a lot of other services prohibited the use of hostnames with underscores. To workaround that issue, we allowed users to connect to the hostname directly that had the underscore characters in them, but provide a different account name using the account parameter. That would contain the account name replacing the underscores with dashes.

Snowflake then ensured that users can reach their accounts using the form account_name.snowflakecomputing.com or account-name.snowflakecomputing.com. Also, historically, using the regional (AKA legacy) URL was the only method of connecting to Snowflake, that was before the Organization feature was rolled out. 

Once that feature went GA, Snowflake allowed users to connect to their account using the legacy format for backward compatibility and a new format referred to as "regionless." The new regionless format helped remove a lot of the confusion around when to include the cloud provider and cloud region ID to the account, by simply using the format org-accountname.snowflakecomputing.com.

For example, in your case, you can simply just use:
myorg-mycomp.snowflakecomputing.com

Where myorg-mycomp is your account name.

I ran a few more tests and found that when you use the regionless format (myorg-mycomp.snowflakecomputing.com) in the connection string, that works regardless of the format you use when passing an account parameter simultaneously. 

My advice then is to simply stick to one method for providing your account identifier. If you're creating a connection string and you're providing the hostname and port, then there's no need to provide an account parameter. If you're passing your Snowflake JDBC configurations as a HashMap and use that to create a connection instead, then pass the account parameter with the account identifier as the value, preferably the regionless format.

**Comment by cabarria** [comment]
Any updates on this? I've been trying to fix the issue by bringing back the region-id parameter, but I don't work with clojure. I keep getting an exception:
clojure.lang.ExceptionInfo: Attempting to call unbound fn: #'metabase.driver.sql-jdbc.connection/do-with-connection-spec-for-testing-connection {:message "Attempting to call unbound fn: #'metabase.driver.sql-jdbc.connection/do-with-connection-spec-for-testing-connection"}

I'll be happy to build the driver and test if I can get the updated files.

**Comment by cerupcat** [comment]
Any update on this issue? I'm running into the same thing.

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/22133, we should allow users to insert the full hostname

**Comment by cerupcat** [comment]
Thanks @paoliniluis. Is there a temporary or hack workaround? Is there a place in the existing codebase we can edit this for our use-case? It seems like it would be a simple change to separate out the account field to not include the full URL.

**Comment by paoliniluis** [comment]
you need to tweak this defmethod https://github.com/metabase/metabase/blob/a99fba84cf3c2c4fc18b5b7869b8aecfd9bdef99/modules/drivers/snowflake/src/metabase/driver/snowflake.clj#L109

**Comment by cerupcat** [comment]
Thanks @paoliniluis.

Do you know which line in particular is the issue? I tried to find it, but from I can tell we're already stripping the account.

`(assoc :account (first (str/split account #"\."))))))`

https://github.com/metabase/metabase/blob/a99fba84cf3c2c4fc18b5b7869b8aecfd9bdef99/modules/drivers/snowflake/src/metabase/driver/snowflake.clj#L80

**Comment by cabarria** [comment]
> #22133

You can look at what I did here: https://discourse.metabase.com/t/error-adding-snowflake-attempting-to-call-unbound-fn-metabase-driver-sql-jdbc-connection-do-with-connection-spec-for-testing-connection/23088/4

**Comment by cabarria** [comment]
It looks like this has been fixed. I'm running "v0.47.8" and was able to successfully configure a Snowflake connection using Okta as the IDP and the org.us-east-1 format for the account.
