### ISSUE TITLE
`Delete` button in question edit mode should be `Archive`

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2628]
We are allowing users to `archive` questions from the saved questions page but `delete` them while in edit mode on a saved question. 

We should probably settle on one thing, archiving, and update the language and behavior in the card edit mode to reflect this.

**Comment by mazameli** [comment]
Oh holy hell I can't believe this is still true.

**Comment by camsaul** [comment]
Don't delete a question! 💔
