### ISSUE TITLE
Editing dashboard freezes when adding series to a chart

### ISSUE THREAD

**Issue by hukev** [metabase/metabase#2630]
*  I am using the Google Chrome browser.
*  My computer's OS is Mac OSX 10.11.4.
*  I'm running Metabase on the webapp.
*  My database is operator-new.
*  My Metabase version is v0.17.0-snapshot.

When I add a card to a dashboard and then try to add new cards in order to display multiple series (on a bar chart), while trying to search for the new cards, the page freezes. I can scroll up and down in the background (the dash), but I can't navigate the card search or exit out. Refreshing does nothing; I have to close the tab and reopen, and usually adding the cards works at that point.

**Comment by agilliland** [comment]
This is the only error I see in the javascript console when this is happening ...

![screen shot 2016-05-25 at 3 16 38 pm](https://cloud.githubusercontent.com/assets/1987787/15558035/e033e4b2-228b-11e6-861e-e763e9ab0fdd.png)

**Comment by camsaul** [comment]
@hukev are you still seeing this problem?

**Comment by hukev** [comment]
I haven't run into this problem recently. Thanks!

**Comment by camsaul** [comment]
Awesome 👍
