### ISSUE TITLE
Liveness probe continually failing

### ISSUE THREAD

**Issue by jonathanprior** [metabase/metabase#26305]
We have a Metabase client being run on k8s via Terraform. This is how the `liveness_probe` is configured.

```
liveness_probe {
  exec {
    command = [
      "wget",
      "localhost:3000/api/health",
      "-q",
      "-O",
      "-"
    ]
  }
  initial_delay_seconds = 300
  period_seconds        = 10
  failure_threshold     = 30
  timeout_seconds       = 10
}
```

And the resources are set like this:

```
resources {
  limits = {
    memory = "12.0Gi"
    cpu    = "2.0"
  }
  requests = {
    memory = "12.0Gi"
    cpu    = "2.0"
  }
}
```

However, every 30 mintes to an hour, a random failure occurs:

> Warning   Unhealthy                pod/metabase-deployment-dfawdada-9wagaw        Liveness probe failed:

This error is not very descriptive and we can't figure out exactly what is causing this crash. Do the `liveness_probe` settings need to be adjusted?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
