### ISSUE TITLE
X - Internal Use - Feature/Project X Implementation

### ISSUE THREAD

**Issue by purposebuiltscott** [metabase/metabase#26312]
Request to add a configuration option the specifies the database time-out related to model caching.  Metabase currently implements a hardcoded 10 minute timeout for model caching. One goal in caching a model is to reduce the occurrence of time consuming queries, including those that take more than 10 minutes to complete. Instead of a hardcoded limit, this timeout could be a configuration option.

Location of hardcoded timeout: https://github.com/metabase/metabase/blob/master/src/metabase/driver/mysql/ddl.clj#L56-L67

**Links**
- product doc: _link to product doc_
- eng doc: _link to technical design doc_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- Issue links: _list of issues this should close when this is delivered_

**Implementation Plan**

***Milestone 1*** )_(note, each milestone should correspond to a point at which product/design can jump in to apply polish, evaluate changes, etc)_
- [x] step 1: #somePRnumber
- [ ] step 2
- [ ] step 3

***Milestone 2***
- [ ] etc

***Mileston N*** _(we can put stuff like translations, docs, testing, etc)_
- [ ] String translations
- [ ] Write rough pass documents for handoff to customer success

**How to Test This Feature Out**

- configure timeout to defined duration
- run query that processes longer than specified duration
  - validate that process is terminated
- run query that processes shorter than specified duration
  - validate that query terminated successfully 
- don't configure timeout
  - validate that query longer than reasonable default (10mins) is terminated
  - validate that query shorter than reasonable default succeeds

**Comment by flamber** [comment]
Please don't use "Internal Use". Create a new issue: https://github.com/metabase/metabase/issues/new/choose
