### ISSUE TITLE
Figure out when to drop support for MySQL 5.7

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#26328]
This is not a matter of if, it's a matter of when. 

[Wikipedia says MySQL 5.7 is going to be EOL'ed by Oracle in October 2023](https://en.wikipedia.org/wiki/MySQL#Project_forks). So once it's EOL'ed upstream we can comfortably drop support for in in the next major release of Metabase after that.

It's an open question about whether we can drop it sooner or not -- we'll need to get some metrics first.

Reasons for dropping MySQL 5.7 support:

- default values on text columns are not supported
- `CHECK` constraints are not supported -- maybe that's a good thing, but it doesn't hurt to have more options, does it?
- `TEXT` columns, etc. do not support default values
- length limits on indecies and other gotchas
- 5.7 doesn't support `regexp_replace` which we **really** want

**Comment by markbastian** [comment]
There's also no support for CTEs.

**Comment by camsaul** [comment]
I think the answer is October 2023

**Comment by camsaul** [comment]
For anyone curious we don't officially support MySQL < 8.0 in Metabase 0.48.0 and above. Use at your own risk
