### ISSUE TITLE
[P2] Reconcile the page header and page content padding and apps viewport responsiveness

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26358]
The header is centered with wide padding, while the page itself (including filters) stretches all the way to the right, which looks really off.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/328388/201137298-2c00e67b-8e15-485d-be99-6fd3203451c2.png">

**Comment by agnes-pinhanelli** [comment]
All components should be aligned to the left, where the list component and filters and buttons are. This should be applied to pages, detail views and the edit mode itself.

**Comment by iethree** [comment]
relates to changes in https://github.com/metabase/metabase/pull/25930

**Comment by brunobergher** [comment]
Renamed to reflect the conversations on Slack and looped @kdoh in, since he's been involved. What you showed on Slack seems like a major improvement, and probably enough for now.
