### ISSUE TITLE
[P1D] Make it clear the text input for categories is searchable

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26356]
[Will assign to Agnes]

Right now all text inputs look the same, but category ones allow you to search for possible values. We should make it clear that is possible, and potentially have a spinner/loading state while the values are being loaded, if it's a long list.

We may already have a component for this elsewhere in the product, in which case reusing would be nice.

**Comment by agnes-pinhanelli** [comment]
I'll work on this now

**Comment by agnes-pinhanelli** [comment]
[Here's the Notion doc](https://www.notion.so/metabase/Searchable-text-input-for-categories-275aab5a68cb448681182346a4d67b36)

**Comment by brunobergher** [comment]
Not relevant anymore.
