### ISSUE TITLE
Filtering applied to wrong join table when filter and group by applied to same table via different foreign key fields

### ISSUE THREAD

**Issue by mattdoran** [metabase/metabase#2635]
*  I am using the Chrome browser.
*  My computer's OS is Mac El Cap
*  I'm running Metabase on Google Cloud Kubernetes cluster
*  My database is MySQL.
*  My Metabase version is 0.17.1.

Loving metabase. :)    But I've found an issue with the filtering being applied to the wrong foreign key relationship.   We're querying a table with 2 fields referencing the same foreign key table.   If I filter by field A, and group by field B, the filter is being applied to field B incorrectly.  

Hard to explain clearly ... so I've provided a replication.

See the attachments:
* metabase-bug.sql.txt - this creates the table and test data
* raw-data - shows the data we've inserted
* filtering-dim-a-but-no-results - we're filtering results from "dim_a" containing "L1" that should return results, but get none.
* filtering-dim-a-but-results-from-dim-b - we're filtering "dim_a" containing "L2" that should get nothing , but getting results matching dim_b incorrectly.

raw-data
![raw-data](https://cloud.githubusercontent.com/assets/577779/15424919/86a7cbfa-1ec8-11e6-9fb5-f2a9dc76fe60.png)

filtering-dim-a-but-no-results
![filtering-dim-a-but-no-results](https://cloud.githubusercontent.com/assets/577779/15424820/015f1b42-1ec8-11e6-95b2-55722eddc0fe.png)

filtering-dim-a-but-results-from-dim-b
![filtering-dim-a-but-results-from-dim-b](https://cloud.githubusercontent.com/assets/577779/15424821/0160a5d4-1ec8-11e6-955c-42d0aec8058e.png)

[metabase-bug.sql.txt](https://github.com/metabase/metabase/files/274357/metabase-bug.sql.txt)

**Comment by agilliland** [comment]
Thanks for the detailed report on this @mattdoran , I could use help with one additional bit of information.  If you were to write the query you are actually trying to express using SQL, what would it look like?

**Comment by salsakran** [comment]
My interpretation of this is that the correct sql should be:

```
SELECT count(*) AS count
FROM fact_test ft 
  JOIN dim_test AS da ON ft.DimA = da.code 
  JOIN dim_test AS db ON ft.DimB = da.code 
WHERE db.code LIKE "%L2%" 
GROUP by da.code 
ORDER BY da.code
```

@camsaul what is the query processor generating here?

**Comment by camsaul** [comment]
My guess is that what's happening here is the generated SQL just contains a single left join against the table. I'll have to look at this a bit more.

**Comment by camsaul** [comment]
K for the first it looks like the SQL generated is 
```sql
SELECT `fact_test`.`number` AS `number`, `fact_test`.`id` AS `id`, 
  `fact_test`.`dim_b` AS `dim_b`, `fact_test`.`dim_a` AS `dim_a` 
FROM `fact_test` 
  LEFT JOIN `dim_test` ON `fact_test`.`dim_a` = `dim_test`.`code` 
WHERE (`dim_test`.`code` LIKE '%L1%') 
LIMIT 2000
```

For the 2nd case we're generating
```sql
SELECT COUNT(*) AS `count`, `dim_test`.`code` AS `code` 
FROM `fact_test` 
  LEFT JOIN `dim_test` ON `fact_test`.`dim_b` = `dim_test`.`code` 
WHERE (`dim_test`.`code` LIKE '%L2') 
GROUP BY `dim_test`.`code` 
ORDER BY `dim_test`.`code` ASC
```

**Comment by camsaul** [comment]
So I think the problem here is that things aren't really set up to handle multiple foreign keys to the same table the way we'd expect. I'll write some tests and figure out a fix for this. It will be a lot easier to fix once we merge #2633 so it probably makes sense to merge that in first

**Comment by camsaul** [comment]
Not 100% what the desired SQL would look like here. A query like this, which is probably closer to what we'd expect for the first example, still produces no results:

```sql
SELECT count(*) AS count, db.code as code
FROM fact_test ft 
  JOIN dim_test AS da ON ft.dim_a = da.code 
  JOIN dim_test AS db ON ft.dim_b = da.code 
WHERE da.code LIKE '%L1%' 
GROUP by db.code 
ORDER BY db.code;
```

If I switch to using `LEFT JOINS` for both I get a single row like:

![screen shot 2016-05-23 at 2 13 03 pm](https://cloud.githubusercontent.com/assets/1455846/15484753/7cc4af3e-20f0-11e6-9d23-78513aaa4e4f.png)

@mattdoran what do you expect to see as the results of your first example?

**Comment by MrMauricioLeite** [comment]
That seems to solve the problem from where I'm seeing it.

**Comment by mattdoran** [comment]
@camsaul that's exactly right.   If metabase is doing a single join, that is not the intention of the query.   The query filters on dim_a join and groups on the dim b join..... it needs to do 2 joins.

Your join is what I would expect, but you had a mistake in the 2nd join "ON" clause .... you were joining on `ft.dim_b = da.code` instead of `ft.dim_b = db.code`.

```sql
SELECT count(*) AS count, db.code as code
FROM fact_test ft 
   JOIN dim_test AS da ON ft.dim_a = da.code 
   JOIN dim_test AS db ON ft.dim_b = db.code 
WHERE da.code LIKE '%L1%' 
GROUP by db.code 
ORDER BY db.code;
```

Given the ability to query tables of this type, without the ability to have multiple joins to the same table it can result to very unexpected results.

If multiple joins to the same table are not allowed, maybe it would be better to warn of the issue instead of running with unexpected results.   I only noticed this when I was demoing metabase to one of our staff and couldn't explain what I was seeing.

**Comment by camsaul** [comment]
Yeah. I think there's just a bug in the join logic. It should be an easy fix.
