### ISSUE TITLE
[P3D] Make empty detail view more compelling

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26359]
The "no results" bee illustration makes little sense in an app context.
Bonus if we can figure out how to handle actual empty views and the edit mode view, which is not technically empty. There was an idea of showing {parameterized} strings as a way to illustrate how things work which I found promising.

**Comment by agnes-pinhanelli** [comment]
**Design:** WIP

**Comment by brunobergher** [comment]
I think we can close this for now and pick it up again if it feels like a priority.
