### ISSUE TITLE
[P1] Make content of list view smoother and more contextualized

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26351]
Needs to be designed. Main points to cover:
- Allow for optional prefixes for each label (instead of just the value)
- Improve padding and type sizes
- More app-specific empty/no-results state

**Comment by agnes-pinhanelli** [comment]
Please follow [this doc, in the section "Phase 2"](https://www.notion.so/metabase/List-View-fixes-0be4ade0f4bb4915bcd4ddce14e0dc47#5bcee2af64e04e45bd274b69e8ebdc10)

**Comment by brunobergher** [comment]
Closing as "not that big of an issue for now"
