### ISSUE TITLE
[P2] Update App icon to the new one

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26366]
Will provide an SVG soon

**Comment by agnes-pinhanelli** [comment]
[Here's an svg of the default app icon.](https://drive.google.com/file/d/1RMPlyzw0gF5aoAzcptZ5z8TfV-RTb5oH/view?usp=share_link) The preview looks weird in that fold but the icon itself is working. I'll upload the rest of the set in a minute

**Comment by kdoh** [comment]
Thanks @agnes-pinhanelli. I ended up exporting it myself earlier before your day got started :)
