### ISSUE TITLE
[P1] Make it possible to launch the app from the contents/collection view

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26363]
We used to have a "Launch App" button, which got lost. Now if I go into the apps contents, I can only launch it again from the sidebar or directly via a URL, which is annoying.

**Comment by agnes-pinhanelli** [comment]
We can bring the button back. For reference,[ this is where it should go](https://www.figma.com/file/rbjE1U9kb6IhJQNBY08PAz/Data-Apps-Exploration?node-id=1996%3A29200)

**Comment by kulyk** [comment]
Figured we don't want it back for now — it's possible to get back to the launched app experience by clicking a page title in the nav bar
