### ISSUE TITLE
Documentation bug on link - Live website

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2637]
Guys, I just found a bug on the live website but can't find it on any branch.

Take a look at the link for Developers Guide on http://www.metabase.com/docs/v0.17.1/

**Comment by camsaul** [comment]
Yup that link is certainly broken. @kdoh @mazameli @salsakran where's this link supposed to go?

http://www.metabase.com/docs/v0.17.1/v0.17.1/developers-guide

**Comment by camsaul** [comment]
Good find @MrMauricioLeite 👍

**Comment by camsaul** [comment]
This is the right link I think, right?

http://www.metabase.com/docs/v0.17.1/developers-guide.html

**Comment by MrMauricioLeite** [comment]
Yep, that looks right. But have you found on the source where is the error?! I found this link but it was correct, so I don't know where to fix.

**Comment by camsaul** [comment]
@metabase/core-developers I can't figure out how the link got broken from the source code. The source file in question is https://github.com/metabase/metabase/blob/master/docs/README.md , and the link works fine on GitHub. Is there a bug with a script we're using to generate the HTML files?

**Comment by salsakran** [comment]
fixed.
