### ISSUE TITLE
embedding applications参数问题

### ISSUE THREAD

**Issue by yjynipyg** [metabase/metabase#26401]
![image](https://user-images.githubusercontent.com/12541278/201315549-77b7d0df-e2ce-4485-b42a-4f2cc3f2b657.png)

在一个应用嵌入这个dashboard的时候，参数无法选中锁定选项，导致无法自定义传参数，请问这个是什么原因呢，Metabase 版本： v0.42.0

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
