### ISSUE TITLE
Can't filter by binary values in MySQL

### ISSUE THREAD

**Issue by arabold** [metabase/metabase#2641]
We're using `BINARY` data types for our primary keys and foreign key relationships. Basically those are UUIDs but hexed into their binary form (this happens internally in our framework using MySQL's `UNHEX()` function). Unfortunately `BINARY` columns that doesn't seem to be well supported in Metabase. The values are actually cut off after 8 characters. Here's how that look like in Metabase:
![image](https://cloud.githubusercontent.com/assets/1548229/15458238/1e35254c-204c-11e6-9650-f149411660da.png)

The first value for example should be `0x00011717F79511E5B7CD12E00F998A0F` instead of just `0x00011717`. Due to this issue other features of Metabase aren't working either. I cannot navigate between foreign key relationships, I cannot even filter for a specific ID - neither querying for `0x00011717` nor for the full `0x00011717F79511E5B7CD12E00F998A0F` yields any results.

I'm using Metabase 0.17.1 with a MySQL 5.6 (AWS Aurora) database.

**Comment by camsaul** [comment]
@arabold we truncate binary columns at 8 hex characters to avoid cluttering up results with huge binary strings. 

Related: #1367

**Comment by salsakran** [comment]
Are we truncating at the query? might it make sense to do this query side?

**Comment by camsaul** [comment]
This actually happens at the JSON-serialization stage. The objects come back from the databases as Java Byte arrays so we have the JSON encoder take just the first four bytes and encode them as hex.

**Comment by arabold** [comment]
Thanks for the explanation @camsaul. However, even if the display is truncated, I would still expect primary and foreign keys to work properly. Right now none of that works. Maybe, as a workaround, the supported length of binary data should be increased to hold at least a UUID?

**Comment by camsaul** [comment]
@arabold agreed. We currently don't have any logic to convert strings from API requests to binary types. (Actually, outside of UUIDs, Metabase doesn't yet support filtering by binary types).

Support for UUIDs however is limited to Postgres, which has a native `uuid` data type. I'd imagine that you'd want to see and enter UUIDs in the normal dashed format, instead of unbroken hex.

**Comment by arabold** [comment]
Unfortunately I cannot change the column type in MySQL, as this would be an architectural change of the database. So I'll have to come up with a workaround here. I can see two possible solutions:
1. Increase the length of a binary string representation from 4 bytes to 32 bytes (to hold a full-length UUID/GUID-like hex value). This is probably easy and hopefully without side effects?!
2. Do a special handling for primary and foreign keys (or any indexed field) to never truncate them. If there's an index on a BINARY field, then it's certainly not a random blob but fulfills a certain purpose. So it should be _okay_ to use the full-length string/hex representation of the field rather than the truncated one.

Does that make sense and is either one of these solutions practical in your eyes?

**Comment by camsaul** [comment]
I've just noticed we already have an open issue for filtering by binary columns in MySQL, #1723.

Closing this as a duplicate.

**Comment by devcenter** [comment]
I got a workaround by casting binary to string by using this 
cast(`p`.`category` as char charset utf8) AS `category`
