### ISSUE TITLE
[P2D] Make implicit action name Title Case

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26436]

**Comment by metamben** [comment]
These are generated at the backend at the moment, I think.

**Comment by kulyk** [comment]
@metamben I think we'll just do the formatting on the FE. AFAIR for implicit actions, we just use a slug instead of a title; title-casing a slug on the BE feels off

**Comment by brunobergher** [comment]
@kulyk Please keep i18n in mind. "Insert", "Update", "Delete" should be localized.
