### ISSUE TITLE
[P1D] Make list views sortable (at least by creators, if not users)

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26443]
Sorting a list view right now involves either:
- Editing the originating model and setting a sort order
- Editing the view itself (often scaffolded) and setting a sort order

That feels like too much of a loop for something basic. Even if the effective change is to update the sort of the underlying query of the list view, a shortcut at the page level seems worthwhile.

**Comment by iethree** [comment]
https://metaboat.slack.com/archives/C03SX8EDNC9/p1668623484774109

**Comment by agnes-pinhanelli** [comment]
**Design:** WIP
