### ISSUE TITLE
SQL not syntax highlighted after clicking "convert this question to SQL"

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2644]
This is on 0.18-SNAPSHOT. Looks like the ACE Editor isn't getting loaded.

When I click "convert this question to SQL", I see:

![screen shot 2016-05-23 at 1 47 14 pm](https://cloud.githubusercontent.com/assets/1455846/15484065/e237ddae-20ec-11e6-9ba8-d56101829dd1.png)

Now If I switch the database to something else and back again the SQL is highlighted as we'd expect:

![screen shot 2016-05-23 at 1 48 18 pm](https://cloud.githubusercontent.com/assets/1455846/15484086/041a1d9c-20ed-11e6-89a1-fbe4083cf109.png)

**Comment by camsaul** [comment]
I saw this happen for MySQL but curiously not for Postgres.

**Comment by agilliland** [comment]
I've tried to reproduce this a few times and haven't been able to make this happen.  It's working for me on MySQL, Postgres, and H2 and on multiple environments.

**Comment by camsaul** [comment]
i guess my box must have just gotten in some weird state 😰
