### ISSUE TITLE
[P1D] Pill category picked in forms doesn't allow for new values to be added

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26441]
We either need to evolve the pill picket to have an "add option" button, or switch to some other way of displaying these (like a text-input with a dropdown). @iethree has more context.

**Comment by agnes-pinhanelli** [comment]
Let's switch it to the style we use for filters today. [These changes can be seeing on this issue and the screens linked in there as well. ](https://github.com/metabase/metabase/issues/26356)

**Comment by iethree** [comment]
because we're no longer exposing model query metadata via the api, this component never shows up in the app
