### ISSUE TITLE
[P2N] Custom actions show up as saved questions in search, and the query opens in the read-only BI editor leading to much confusion

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26452]
This may actually be two issues:
- How to represent actions globally in the product (search, collections)
- Opening the right editor when they're selected

**Comment by kdoh** [comment]
@brunobergher Do we think these need to show up in search yet? My guess is they should eventually, but my vote would be to punt on this for now since it seems like it's not the most useful surface to be focusing on just yet.

**Comment by brunobergher** [comment]
Should we hide them?

**Comment by brunobergher** [comment]
Will this be solved by the query action migration?

**Comment by kulyk** [comment]
Fixed by #26717
