### ISSUE TITLE
[P1N] Make how to filter the content of a list view for a given page obvious

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26457]

**Comment by kdoh** [comment]
@brunobergher Not sure I have enough context to go off of here.

**Comment by kdoh** [comment]
Leaving the [video](https://metaboat.slack.com/archives/C03SX8EDNC9/p1668545009176629) and [figma](https://www.figma.com/file/rbjE1U9kb6IhJQNBY08PAz/Data-Apps-Exploration?node-id=2138%3A30028&t=5FgXU2sdl3v3zfpM-1) links here for posterity.
