### ISSUE TITLE
[P1N] Make it obvious how to edit a button's action from the button itself

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26458]

**Comment by iethree** [comment]
https://metaboat.slack.com/archives/C03SX8EDNC9/p1668716493375199

**Comment by kdoh** [comment]
Should be ready to be worked on. Figma is [here](https://www.figma.com/file/rbjE1U9kb6IhJQNBY08PAz/Data-Apps-Exploration?node-id=2182%3A30328&t=GEKPEEUuWqkt6zzl-1) for reference, and Ryan's got a link to my voice over up above there.
