### ISSUE TITLE
[P1D] Make it way more obvious how to manage the content of an app (overflow menu is too hidden)

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26455]
It's too much expect someone to open the overflow menu and pick "manage contents" in order to find the models, views, etc that make up an app. We need a more obvious way to get there.

**Comment by agnes-pinhanelli** [comment]
Let's move the icon from the menu to the nav bar. [Please follow this screen. ](https://www.figma.com/file/rbjE1U9kb6IhJQNBY08PAz/Data-Apps-Exploration?node-id=2123%3A29621&t=LcOTpNU9gGWdsmhh-4)

**For documentation**
More comments & other explorations on [this thread.](https://metaboat.slack.com/archives/C03SX8EDNC9/p1668443104228359)
