### ISSUE TITLE
Object details links don't respond to command-clicks to open in a new window

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2647]
I've been using MB a fair bit to manage ListOfInboundThings and have been drilling into individual entries a lot. 

Going from a list to an item is a bit of a pain for two reasons. Once is that "back" doesn't return me to the scroll position in the list, and the 2k rows makes this more annoying with time. Second, is that I can't open up individual details in other tabs. 

Common tricks like cmd-click or right clicking don't work. I'm guessing this is due to the QuickFilter.

**Comment by mazameli** [comment]
This was fixed by https://github.com/metabase/metabase/pull/8860.
