### ISSUE TITLE
Can't log in through Google

### ISSUE THREAD

**Issue by wdossett** [metabase/metabase#26473]
**Describe the bug**
When I try to log into Metabase through my workplace google account on my work computer, the login window opens but remains completely blank. I can't log in with my email because my Metabase account is through my company, through Google. Other browsers and incognito mode also do not work on my work computer. However, I can log in on my personal computer (using my work google account) but not my phone.

**Expected behavior**
The login window should have shown the space to enter an email and password. 

**Screenshots**
![image](https://user-images.githubusercontent.com/115732513/201670734-f93261b6-3806-44dc-8af7-1991b908ac5d.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 107.0.5304.107, also doesn't work on Microsoft Edge 107.0.1418.42
- Your operating system: Windows 10 Version 21H2

**Severity**
Obviously this is a major issue. I can't use Metabase at all as long as this persists.

**Comment by flamber** [comment]
Hi @wdossett 

Upgrade to latest release: https://github.com/metabase/metabase/releases/latest

Make sure the Site URL in Admin > Settings > General is correctly defined (http vs https is important too) and that you have configured that as Allowed Javascript Origins in your Google Console: https://www.metabase.com/docs/latest/people-and-groups/google-and-ldap#working-in-the-google-developer-console

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by wdossett** [comment]
Hi @flamber , thanks for your response. It's up to date, but it's not a systems issue because every other user in my team is using Metabase w/o any problems. 

I've tried every combination of other browsers, VPNs, incognito, restarting, changing the DNS, etc. that I or my teammates could think of. Nothing works.
