### ISSUE TITLE
API method GET /api/session/password_reset_token_valid 

### ISSUE THREAD

**Issue by michalprzybylik** [metabase/metabase#26503]
I have a question about parameter "token" sent in GET /api/session/password_reset_token_valid API method. Is it not a "secret" parameter? Why is this parameter sent by the GET method in the URL query?

https://github.com/metabase/metabase/blob/master/docs/api/session.md

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
