### ISSUE TITLE
New interface Laggy and slow 

### ISSUE THREAD

**Issue by skaboy007** [metabase/metabase#26534]
**Describe the bug**
It's not really a bug but no other topic was suitable for this. 
we are using 44.5 for a while now. and were not updating to it till it was absolutely necessary to update due to the fact of the new interface being slow and laggy. 
I'm talking about mainly dashboards and the left menu. they are loading getting stuck in the middle and continuing. 

i love Metabase, the fact that the interface is laggy is just running the experience Metabase was loved for. exploring data and feeling very comfortable in the process 
this issue happens on all device types. strong PC's flagship last gen androids and co. 

**Logs**
no relevent logs 

**To Reproduce**
1. build a decent-sized dashboard, 
2. go to that dashboard 
3. enjoy the lags 

**Expected behavior**
snappy user experience with no laggs 

**Screenshots**
not applicable 

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7-Ubuntu-1ubuntu218.04.1",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7-Ubuntu-1ubuntu218.04.1",
    "os.name": "Linux",
    "os.version": "4.15.0-34-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "sqlserver",
      "h2",
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-0ubuntu0.18.04.1-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-10-17",
      "tag": "v0.44.5",
      "branch": "release-x.44.x",
      "hash": "29fab4d"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Severity**
obviously its not Sever yet i notice that users and myself are using Metabase less 

**Additional context**

**Comment by camsaul** [comment]
When they say "left menu" I'm guessing they mean the Database/Table selection menu in the Query Builder -- since we make a separate API request to fetch the Tables in the Database after you click it there is now a bit of lag there compared to previous versions where we fetched all Databases + all Tables in a single enormous API call. It still seems reasonably snappy to me tho almost all of the time. If your server is slammed or network connection is slow or you have a trillion tables then you might see that loading spinner after clicking a database for a few seconds which is definitely laggy. I have ran into that once or twice. That's just my guess tho. A video demonstrating the lag would be super helpful.

**Comment by skaboy007** [comment]
hi, all thanks for the comments I wish I could help out with a video but I have sensitive data attached to MB, I won't be able to do so. but ill try to be as clear as possible 

PS: right now I'm on an excellent PC running chrome 
AMD reason 3900X 12 cores and 32GB of ram and a 2070 GTX
and the latest android flagship with chrome. one plus 10 pro 

By the left menu, I mean the collection menu. a few words about it 

1. on the PC when pressing the logo to toggle the menu on and off it has a significant lag. Mainly in a dashboard scenario,  after the mouse press, and before the animation, there is a noticeable lag. 
2. out of the dashboard scenario everything is a lot more snappy.
3. on a mobile phone I get the same thing 

Dashboard. context I limit my dashboards to 14 days of data and give the ability to play with it. when a user or myself do something dumb like remove the time filter for obvious reasons everything starts to lag, but that is not bagging anyone that is well understood. the main issue is that I use 14 days of data and have the following the dashboard 

1. 5 single value widgets 
2. 4 bar charts day by day 
3. and 12 pie charts 
that's a decent-sized dashboard
i got a few other dashes more simple but the issues I'm experiencing are the same 

the issues 

1. When it loads on a PC or mobile the whole thing gets seriously stuck for a few seconds. and it seems to me it's not the data load but the animation of when the widgets are created, there is some sort of widget scaling animation at the render or load of the page. the interesting thing is when we were using the 0.3x.xx everything was lightning fast. and it was so cool to browse data. It was an experience on its own for me 
2. Scroll, the scroll is awful, tested it on PC and mobile. on the pc, it's just not smooth as if I'm trying to run a crisis in a browser. on the smartphone it's worse, the moment I start to scroll I see widgets that did not render at all look blank, and beneath them widgets that do that scaling tin-to-place animation that I can see 3 frames off. the widget is struggling to get into place.

I personally decided to stay with the latest 0.3x.xx version till the vulnerability update, then I decided that its time to move. every user using Metabase reported the same thing, it's just not fun browsing data no more. in 0.3x.xx the speed of things interested the user to explore do deep dives to date from the dash. now I open the dash only when I really need it. 

that's my user journey. 

off-topic love Metabase. it would be awsome to get some love for the mobile interface for example make the filters in the dashboard collapsable so you can see data on the first fold and not have to scroll all the way to the data. 

-

**Comment by Dreckr** [comment]
Hi, guys!

I think I'm expericing this same behavior. One of my dashboards has a ton of questions and a few of those questions have a ton of data points. I've noticed that it is responsive while hovering bar and pie charts and doesn't take too long to load, but it feels veeeeery sluggish when scrolling. I profiled what is happening with Chrome Dev Tools and it seems that there's a handler for the scroll event that is taking a lot of time do process (almost half a second) and it is blocking the next frame from being rendered.

Here's a link for the profile I recorded. It has screenshots and everything, but I'll only share:

**Comment by Dreckr** [comment]
Digging a little deeper and debugging through Chrome Dev Tools (while running production code), it seems [stickyParameters.js#checkIfShouldToggleStickiness](https://github.com/metabase/metabase/blob/2d6a779949c7da62841abde79fa306130fd392be/frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js#L32) always returns true and stickyParameters.js sets Dashboard.jsx state to `{ isParametersWidgetSticky: shouldBeSticky }` at every (throttled) scroll event, even though  Dashboard already has the right state. This state change triggers a ton of subsequent function calls that keep the next frame from being rendered.

This does not happen when the dashboard is in edit mode.

I hope this helps

**Comment by ojjj13** [comment]
Sorry for taking a picture of the screen in advanced due to company's policy I am not allowed to take screenshots of the computer.

![f94e2050-98a9-461f-8f12-969e6314f3dc](https://github.com/metabase/metabase/assets/29124436/82d0ed70-d561-4991-8d9c-68fc71e123f0)

I am experiencing the same issue as @Dreckr using the newest version of metabase v0.46.3(jar), the dashboard only contains a few tables with very few data and it's less than 10 cards, I can reproduce this even with only a few blank cards as long as it takes up more than one page(i.e. you have to scroll to get bottom cards, like the width of two monitors height), however it's perfectly smooth in the editing mode.

Plus, I work in an offline environment so I can imagine it could be a JS issue due to not able to take advantage of Vue/React as they probably need to cache some of the elements. (I know very little of JS/ReactDOM etc.)

Looking forward to some answers, thanks in advanced.

**Comment by Dreckr** [comment]
@paoliniluis I saw that you created issue #29913 implying that these problems are a result of heavy operations happening. They are **not**.

As I reported on my last comment, there is a **bug** in [stickyParameters.js#checkIfShouldToggleStickiness](https://github.com/metabase/metabase/blob/2d6a779949c7da62841abde79fa306130fd392be/frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js#L32) that causes a reactive cascade of needless operations at every scroll event and causing massive jank.

Just wanted to clarify this point as to avoid anyone working on #29913 thinking that it would solve this issue.

**Comment by paoliniluis** [comment]
Moving to a P1, as many may customers are seeing the same. We need to improve the rendering speed of the charts and the speed of the UI entirely

**Comment by skaboy007** [comment]
@paoliniluis Thank you for listening!

**Comment by paoliniluis** [comment]
@skaboy007 we listen to all users and see every single comment. The problem is that we have very limited resources and we need to be extremely picky about the problems we tackle

**Comment by skaboy007** [comment]
I appreciate the ongoing work on Metabase's UI. It's the smooth, responsive interface that truly invites exploration and makes Metabase a pleasure to use. this is why I think this issue is very important.

**Comment by luizarakaki** [comment]
We have a preliminary fix with https://github.com/metabase/metabase/pull/31963 and tried hard to reproduce this but we couldn't get much further.

This maybe a local issue (OS, browser, hardware). If someone has better reproduction steps, we are happy to try it again.

**Comment by Dreckr** [comment]
Well, guys.... as it seemed that this was not going to be solved anytime soon, I took a few moments to investigate and create a fix. It was a pretty evident problem that happened with every dashboard that didn't have filters.

I created a PR at https://github.com/metabase/metabase/pull/32245 with the fix
