### ISSUE TITLE
Fail to connect to SQL server with trusted_connection / Integrated Security

### ISSUE THREAD

**Issue by johndrummond** [metabase/metabase#2654]
If this is a bug report, please fill in the blanks:
-  I am using the **Firefox_____** browser.
-  My computer's OS is ____windows7_______.
-  I'm running Metabase ______locally_____. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is ____MS SQL Server _2008 r2______.
-  My Metabase version is ____ v0.17.1_____.
  This may be me just missing what to do, but I can't find from the application or documentation anywhere how to set up Metabase to connect to SQL Server with Integrated Security - I can't find anything other than where one enters a domain, password and id - blank or the windows ones there I get
  05-24 15:16:30 ←[1mERROR metabase.driver←[0m :: Failed to connect to database: j
  ava.sql.SQLException: Login failed. The login is from an untrusted domain and ca
  nnot be used with Windows authentication.

I can connect happily with clients like toad etc. Otherwise it looks as though Metabase could be really useful - thanks for your work.

**Comment by camsaul** [comment]
@johndrummond are you able to connect to the DB without using Windows auth (if it's set up to allow it?)

**Comment by johndrummond** [comment]
Ah. It's not set up for that and I don't control it.
I'll set up a local one tomorrow and see what happens

**Comment by camsaul** [comment]
@johndrummond any luck?

**Comment by camsaul** [comment]
@johndrummond ?

**Comment by johndrummond** [comment]
The central databases I connect to are all integrated authentication /windows authentication, - it turned out  to be complicated to set up another one in mixed mode. Sorry about that. 
John.

**Comment by kenny-evitt** [comment]
@camsaul Is integrated/Windows authentication supported?

**Comment by camsaul** [comment]
@kenny-evitt it's supposed to be working but a few have had issues with it, hence this issue :) 

Unfortunately I don't have a ton of experience with integrated Windows Auth for SQL Server so this is going to be a tricky bug to fix. If you or anyone else on the thread has experience getting it working in Clojure or Java let me know! 👍

**Comment by kenny-evitt** [comment]
@camsaul Integrated security seems to be working for me (now that I've fixed my stupid mistake regarding connecting via TCP/IP).

**Comment by camsaul** [comment]
What if ou just put your username as `kenny`?

**Comment by kenny-evitt** [comment]
@camsaul No luck. I've also tried leaving *Host* blank or explicitly setting it to my computer's name (both with and without the domain suffix).

I've seen mention of a jTDS driver setting "USENTLMV2" that might be relevant.

**Comment by camsaul** [comment]
Interesting. With some of our other drivers we added a field to let you add extra connection options so I can do that for SQL Server as well which would let you add that option, which might fix the issue. Microsoft also open-sourced their JDBC driver last year so when I get more free time (when the rush to ship new features slows down a bit) I was planning on looking at switching to using that instead of jTDS. I seems like it works better and supports more features

**Comment by camsaul** [comment]
(We might have an easier time getting this to work correctly with the official driver instead of jTDS)

**Comment by kenny-evitt** [comment]
@camsaul I'm using jTDS in one of my own Clojure projects so it certainly works; but that project uses SQL authentication so I don't have any insights to share about getting integrated security working. Luckily for me, I was able to enable mixed mode on my SQL Server instance, so this isn't critical for me at this moment.

I'll also gladly help test any changes you make in the future and, if I get a chance, I'll try looking into this myself too.

**Comment by camsaul** [comment]
@kenny-evitt if you'd like to take a look at the code for our SQL Server driver to make sure I didn't do something stupid I'd really appreciate that. I'd love to figure out what's going on here to get this working for you and everyone else 😎

**Comment by camsaul** [comment]
@kenny-evitt if you have a sense of what needs to be done to support this (and it sounds like you might given you have Clojure+jTDS experience), we'd love to have you as a contributor and would welcome a PR to support this 👍

**Comment by camsaul** [comment]
@johndrummond @kenny-evitt I just opened PR #5491 (branch `allow-additional-options-for-sqlserver`) which might fix this issue. Mind trying it out and seeing if it does?

**Comment by kenny-evitt** [comment]
@camsaul I just tried to build the *master* branch of Metabase (not your PR), on a Windows computer, and I'm getting the same error in both Git Bash and Cygwin when I run `bin/build`:

```
√ /cygdrive/d/@GitHub/metabase [master|√]
15:46 $ bin/build
Tagging uberjar with version 'v0.26.0-snapshot 8029bf9 master 2017-08-08'...
Running 'yarn' to download javascript dependencies...
yarn install v0.27.5
$ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
'\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.77s.
Running 'webpack' with NODE_ENV=production assemble and minify frontend assets...
Error
    at D:\@GitHub\metabase\node_modules\webpack\lib\Compilation.js:229:38
    at onDoneResolving (D:\@GitHub\metabase\node_modules\webpack\lib\NormalModuleFactory.js:29:20)
    at D:\@GitHub\metabase\node_modules\webpack\lib\NormalModuleFactory.js:85:20
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:726:13
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:52:16
    at done (D:\@GitHub\metabase\node_modules\async\lib\async.js:241:17)
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:44:16
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:723:17
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:167:37
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:52:16
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:361:13
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:52:16
    at done (D:\@GitHub\metabase\node_modules\async\lib\async.js:241:17)
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:44:16
    at D:\@GitHub\metabase\node_modules\async\lib\async.js:358:17
    at D:\@GitHub\metabase\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19
    at onResolved (D:\@GitHub\metabase\node_modules\enhanced-resolve\lib\Resolver.js:38:18)
    at D:\@GitHub\metabase\node_modules\enhanced-resolve\lib\Resolver.js:127:10
    at D:\@GitHub\metabase\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (D:\@GitHub\metabase\node_modules\enhanced-resolve\lib\Resolver.js:110:4)
    at loggingCallbackWrapper (D:\@GitHub\metabase\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at D:\@GitHub\metabase\node_modules\tapable\lib\Tapable.js:134:6
    at Resolver.<anonymous> (D:\@GitHub\metabase\node_modules\enhanced-resolve\lib\DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (D:\@GitHub\metabase\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (D:\@GitHub\metabase\node_modules\graceful-fs\graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
resolve file
  D:\..\node_modules\css-loader\index.js doesn't exist
  D:\..\node_modules\css-loader\index.js.web-loader.js doesn't exist
  D:\..\node_modules\css-loader\index.js.webpack-loader.js doesn't exist
  D:\..\node_modules\css-loader\index.js.js doesn't exist
  D:\..\node_modules\css-loader\index.js.loader.js doesn't exist
resolve directory
  D:\..\node_modules\css-loader\index.js doesn't exist (directory default file)
  D:\..\node_modules\css-loader\index.js\package.json doesn't exist (directory description file)
```

I checked the Circle CI build on the PR but there are no artifacts (e.g. JAR files). Should I be able to build Metabase on Windows? Or is there an alternative means by which you can distribute a build with the changes in your PR?

**Comment by camsaul** [comment]
@kenny-evitt thanks for taking the time to check if this branch fixes your issues. Unfortunately we have some issues building locally on Windows. However, I've already heard that the branch fixes a few other SQL Server problems so I'm planning on merging it into 0.26.0, which we should be releasing fairly soon (within the next month I believe). So when that's getting closer to release and we build a release candidate JAR I'll be sure to let you know if you still want to give it a try. Thanks again

**Comment by kenny-evitt** [comment]
@camsaul No worries; thanks for your help!

**Comment by camsaul** [comment]
This should be fixed by #5491. Will keep open until we push out a release candidate for 0.26 so community can verify before I close

**Comment by senior** [comment]
@camsaul looks like we can close this one since we've release an 0.26 RC

**Comment by camsaul** [comment]
Yeah. @kenny-evitt if you want to give this a try we have a release candidate [here](https://github.com/metabase/metabase/releases/tag/v0.26.0.RC1), otherwise we should be releasing v0.26.0 in the next week or so.

**Comment by mazameli** [comment]
@kenny-evitt just a heads up that [version 0.26 just shipped](http://www.metabase.com/blog/Metabase-0.26).
