### ISSUE TITLE
X-Ray Features cannot be disabled

### ISSUE THREAD

**Issue by Maiquu** [metabase/metabase#26571]
**Describe the bug**
Disabling X-Ray features in 'Admin Settings > General' does not remove exploration options from homepage.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 106.0
- Your operating system: Ubuntu 20.04
- Metabase version: v0.44.6
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Since resources are limited, explorations being visible would allow less knowledgeable users to consume resources carelessly.

**Comment by paoliniluis** [comment]
Thanks for reporting, I just reproduced and you're absolutely right
