### ISSUE TITLE
[P0] Scaffolded form is sending all fields and not only changed ones

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#26577]
Case ran into this during the demo on 11/17.

**Comment by iethree** [comment]
I think the "has the value changed" logic breaks on some of the stranger column types case was using like `jsonb`

**Comment by iethree** [comment]
It looks like this is a result of the form components themselves casting `null` to either `""` or `0`.  I believe planned work around migrating to our new forms framework will fix this, but need to confirm with @ranquild next week.

see https://metaboat.slack.com/archives/C049USTRF60/p1667930159006639
