### ISSUE TITLE
Question with required prompt(s)

### ISSUE THREAD

**Issue by BattleBrisket** [metabase/metabase#2658]
I have a series of Questions that all ask the same thing, with a single variable that changes between them (U.S. state, in this case). 

It would be awesome if questions had a _placeholder_ concept: a prompt that must be filled in order for the question to run. It would exponentially reduce the number of questions I maintain.

**Comment by tlrobinson** [comment]
Sounds like you're looking for something like #1543 and/or #2556?

**Comment by BattleBrisket** [comment]
Definitely #1543.
