### ISSUE TITLE
[P1D] We shouldn’t require changes to hit save (implicit parameter error)

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#26580]
From the demo on 11/17.

**Comment by iethree** [comment]
this looks like a backend error, if we make no form changes on the frontend, it gives us this error 

![Screen Shot 2022-11-21 at 10 11 53 AM](https://user-images.githubusercontent.com/30528226/203118339-3279437a-ccde-4118-aac1-d9a8b94ca3a2.png)

**Comment by iethree** [comment]
@snoe do you think this is easily deferrable?

**Comment by snoe** [comment]
Definitely deferrable, but what's being saved here? Personally, it feels like the frontend shouldn't be sending the request.
