### ISSUE TITLE
How to always show x-axis in line graph

### ISSUE THREAD

**Issue by ftpyz** [metabase/metabase#26599]
I create new line bar and add my dashboard but same screen size x-axis not show and  this creates some confusion
<img width="1095" alt="Ekran Resmi 2022-11-18 09 15 46" src="https://user-images.githubusercontent.com/38686/202634010-8eadf059-261a-442e-b43f-afc14a3e0777.png">

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
