### ISSUE TITLE
How can I show zero when there is no data in the question? 

### ISSUE THREAD

**Issue by ftpyz** [metabase/metabase#26598]
How can I show zero when there is no data in the question? 
I create one google analytics question (e-commerce rate). I want to use if not conversation i show zero number but metabase question said 

No results!
This may be the answer you’re looking for. If not, try removing or changing your filters to make them less specific.
 

how to change it
<img width="247" alt="Ekran Resmi 2022-11-18 09 06 51" src="https://user-images.githubusercontent.com/38686/202633254-21443647-6b0a-4b7d-869a-3409264d89e4.png">
<img width="547" alt="Ekran Resmi 2022-11-18 09 10 58" src="https://user-images.githubusercontent.com/38686/202633296-f2f94b02-7f69-4912-be2e-3d2daafd6830.png">

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
