### ISSUE TITLE
Applying filter to table visualization causes duplicate columns

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#26609]
**Describe the bug**
When working with a table visualization, if you apply a filter then you end up with duplicates of your columns

**To Reproduce**
1. Create a new question
2. Select the Orders table. 
3. Summarize by count, Group by User -> source, Product -> Category
4. Click visualize
5. Change to Table Visualization with Pivot option disabled
6. Select Filter, and Filter by count > 0
7. You will now be in a bad state, where your columns are also listed under "More Columns"

**Expected behavior**
I wouldn't expect my columns to be re-listed under more columns

**Screenshots**
![image](https://user-images.githubusercontent.com/1328979/202742026-608af073-b5fc-4294-9a05-fffef5807944.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.10.16.3-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "America/Halifax"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-10-28",
      "src_hash": "d106677379763d7f89a00c05699c4b2736a5d45d",
      "tag": "v1.44.1-SNAPSHOT",
      "branch": "25453-Viz-Settings-Series-Formatting",
      "hash": "bc6585b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
**Severity**
Likely not too Severe, but would be good to fix

**Comment by flamber** [comment]
Likely the same as #22563, related to #13455

**Comment by ranquild** [comment]
@npfitz could you please also double check that the issue no longer exists in `master`?

**Comment by uladzimirdev** [comment]
Related issue was fixed https://github.com/metabase/metabase/issues/22563#issuecomment-1802783774
repro test was added https://github.com/metabase/metabase/pull/32872
