### ISSUE TITLE
Exports of Pivot Table excludes some columns when question is unsaved

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#26614]
**Describe the bug**
Exports of Pivot Table excludes some columns when question is unsaved.
Regression since 0.43.x

**To Reproduce**
1. Question > Sample > Products - summarize Count by Category and CreatedAt:Year
![image](https://user-images.githubusercontent.com/1447303/202747108-e7af39ff-9587-402f-8c1f-6a75ef2a1d06.png)
2. Change visualization to Pivot Table
![image](https://user-images.githubusercontent.com/1447303/202747344-a8542e95-763f-4d93-979f-f8cf71173fa1.png)
3. Export as CSV (while the question is unsaved/dirty) - this is the entire content, so it's basically dropping the "columns" column from aggregation
```csv
Created At,pivot-grouping,Count
2016-01-01,1,54
2017-01-01,1,75
2018-01-01,1,53
2019-01-01,1,18
```
4. Click the Save button to save question and export again - expected results
```csv
Category,Created At,Count
Doohickey,2016-01-01,13
Doohickey,2017-01-01,17
Doohickey,2018-01-01,8
Doohickey,2019-01-01,4
Gadget,2016-01-01,13
Gadget,2017-01-01,19
Gadget,2018-01-01,14
Gadget,2019-01-01,7
Gizmo,2016-01-01,9
Gizmo,2017-01-01,21
Gizmo,2018-01-01,17
Gizmo,2019-01-01,4
Widget,2016-01-01,19
Widget,2017-01-01,18
Widget,2018-01-01,14
Widget,2019-01-01,3
```

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.44.6 - regression since 0.43.x

**Additional context**
Very related to #15034

**Comment by danield-catalyst** [comment]
Slight variation to the above issue but probably the same cause as I'm seeing it drop the Rows field instead of the Columns.

Saved base pivot table
```
Zone,Block,Month Start,Block Sort,Std Dev,Std Dev Percentage,NP Load Stdev,NP Load Stdev 1
A,2x16,2023-02-01,2,15.1665813333,0.03803215646667,-3.9035597189,-3.1926262188
A,2x16,2023-03-01,2,15.9642640000,0.04176844043333,-6.8315218126,-6.0831969375
```

Filters changed on dashboard, click on pivot, download
```
Zone,Block Sort,Block,pivot-grouping,Std Dev,Std Dev Percentage,NP Load Stdev,NP Load Stdev 1
A,1,5x16,4,80.1419434940,0.04869627468214,-816.2013008963,-737.2248631370
A,2,2x16,4,30.7145360536,0.05433801866012,-654.6749789794,-584.2777500582
```

For me Month Start is the only Rows field so without that the download is useless as it drops Month Start from the group by and creates a dateless summary version of the data so its 2982 rows down to 42. Saving the filtered pivot table does result in a working download but makes having a dashboard with filters kind of redundant and/or useless.

**Comment by darksciencebase** [comment]
related https://github.com/metabase/metabase/issues/26564

**Comment by cdeweyx** [comment]
I can no longer reproduce this. @adam-james-v can you?

**Comment by adam-james-v** [comment]
@cdeweyx I cannot repro this one either. I'll close it.

**Comment by natashamathur** [comment]
For https://github.com/metabase/metabase/issues/46561 this is appearing on **saved** questions too

**Comment by perivamsi** [comment]
This is unrelated to https://github.com/metabase/metabase/issues/46561
