### ISSUE TITLE
Figure out a way of moving to Jetty 10+

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#26613]
Right now our ring-core dependency is not prepared for Jetty 9+ (https://github.com/ring-clojure/ring/issues/439). If we want to move to Jetty 10/11/12 then we will need to find a way out of that dependency.

**Comment by The-Alchemist** [comment]
https://github.com/sunng87/ring-jetty9-adapter is available.  Despite the name, it supports Jetty 9+

**Comment by camsaul** [comment]
we're already using Ring 9 -- see https://github.com/metabase/metabase/blob/98fecd3e2f2bad60a9fade86b481d8acf59350e6/deps.edn#L129. I'm guessing you mean you want to upgrade to Ring 10+? Is there a specific reason that you think we should upgrade? I think Ring 9 is still getting security updates

**Comment by paoliniluis** [comment]
@camsaul we don't know when Jetty will be EOL'd, but the project announced end of community support now https://github.com/eclipse/jetty.project/issues/7958.

I don't think that the Jetty maintainers will keep putting focus on Jetty 9
