### ISSUE TITLE
Support nested records in BigQuery

### ISSUE THREAD

**Issue by gad2103** [metabase/metabase#2662]
@luizarakaki edit (Aug 2024):

```[tasklist]
### Tasklist
- [ ] https://github.com/metabase/metabase/issues/46977
- [ ] https://github.com/metabase/metabase/issues/46978
```

@luizarakaki edit (Dec 2022):
BigQuery differs from other databases as nested fields are part of the table definition. We don't need to parse JSON fields to get the schema, it is defined in the table schema. https://cloud.google.com/bigquery/docs/information-schema-tables

So, instead of using the standard SQL JDBC driver implementation [`describe-nested-field-columns`](https://github.com/metabase/metabase/blob/d8486fccb407b4ef936e04198b97a077ba896990/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L374), we can get the schema from the table metadata.

The syntax to query nested fields is also different: it uses the dot notation:
```
SELECT
   nested.field_1,
   nested.field_2
FROM table
```
https://scosco.github.io/learn-bigquery/foundation/structs.html

**This issue DOESN'T entail supporting arrays (aka repeated). It also doesn't entail working with the new [BigQuery JSON support](https://cloud.google.com/bigquery/docs/release-notes#January_06_2022), this totally unstructured JSON support is new and not frequent (yet).**

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Hi @gad2103, currently the questions interface doesn't support nested fields 😿 

Related (Mongo) #1328

**Comment by camsaul** [comment]
Also related: #708 (same issue for Postgres)

**Comment by gad2103** [comment]
Is there a technical barrier to this? Or is it just a matter of resources
to add this feature?

**Comment by salsakran** [comment]
@gad2103 largely engineering bandwidth. wanna help? ;)

**Comment by gad2103** [comment]
Could you point me in the right direction? Where in the code should I look?

**Comment by camsaul** [comment]
@salsakran do we have any designs for exposing nested fields in the QB?

**Comment by gad2103** [comment]
if you guys point me in the right direction, i'm happy to try my hand at this. i've never worked in clojure but it would be fun to try it out. and we would really like to have this at my company.

**Comment by salsakran** [comment]
they should look and feel the same as the FK relations do.

eg, whether I have a foreign key to a "user" table or a dictionary that has those denormalized there, it's the same from an end users perspective. the fact they've been denormalized is a "physical schema" level detail. 

@gad2103 I'd recommend digging into the query builder code at https://github.com/metabase/metabase/tree/master/frontend/src/query_builder to understand how the front end UI works wrt to foreign keys. It's in react/js so it won't be as strange. Once you've wrapped your head around it, we can talk over (in this issue) how best to expose things, and if we need design assets we can whip some up for you.

**Comment by salsakran** [comment]
@camsaul remind me - are we ever introspecting JSON blobs to figure out which keys are in them?

**Comment by camsaul** [comment]
@salsakran that's open as #708 for Postgres

**Comment by camsaul** [comment]
It's probably not super useful to do much with JSON that is just serialized as a string because DBs have no way to query against them. But for DBs that have a native nested record / `json` type we can do interesting things

**Comment by salsakran** [comment]
Gotcha, so it sounds like we'd need:
* some way to introspect json fields that didn't nuke a data warehouse in the event of big tables. 
* some way to make sure we get a good enough sample of all the rows so that we have all the fields used in dicts, not just our current first N rows, as nested field shapes tend to change with time
* some place to store these keys
* a way to expose them in the query builder in the same visual style as the current foreign keys.

Am I missing anything?

**Comment by camsaul** [comment]
We already more or less have the middle two. That's how we support nested fields in Mongo. The first point has to be done on a driver-by-driver basis; thus far we've only implented it for Mongo. The last point just has to be done once for the new QB. The old QB had it at some point so we just need to bring it back

**Comment by Dwar3xwar** [comment]
Any updates on this PR?

**Comment by camsaul** [comment]
@Dwar3xwar I don't think I've seen a PR for this

**Comment by lukabirsa** [comment]
I'd love to have this supported in Metabase, as this would enable our non-programmer users to query Google BigQuery. Right now BigQuery integration is mostly unusable.

**Comment by txomon** [comment]
In our case, we are starting to see aggregated reports that try to make use of this feature. In our case, just having repeated simple fields like arrays of basic types would solve a lot.

**Comment by davidfurlong** [comment]
Is there a way to omit these fields so that bigQuery tables with nested fields can still be used, but without using those fields? I'm getting errors when trying to list Raw Data, but not when doing a count. Thx

**Comment by thangbn** [comment]
same idea with @davidfurlong

**Comment by tuaris** [comment]
Would it be possible to just 'flatten' those nested field?  For example if you have the field `client` with nested fields `port` and `ip` could Metabase have a column for each like `client.ip` and `client.port`? Or if the period is the problem convert it to `client_ip` and `client_port?

**Comment by VikramTiwari** [comment]
Seems like now you can use the table which have nested fields.

@camsaul Flattening/snake_casing seems like an easier solution to this problem. There is no way to visualize any JSON data right now since it adds a lot of extra java metadata to the values. One example:

```
{"f":[{"v":{"f":[{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"debug"},{"v":"anonymous"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"78.0"},{"v":"index.js"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":[]},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"},{"v":"java.lang.Object@4b6c9f0e"}]}},{"v":"Sample log text"}]}
```

This is the value of one column which is of `RECORD` type in bigquery.

**Comment by allan-simon** [comment]
Am i wrong to say it's a little different from postgres issue and mongodb, in the sense that bigquery does expose the schema with the nested fields ? (so that you don't have to parse any records to get it) 

Also right now metabase for bigquery (at the opposite of the behaviour with postgres) does return this confusing `f` `v` values that do not correspond to the actual fields names  (and it also transform `null` into a java.lang.Object )

**Comment by shafy** [comment]
Wanted to add that support for nested fields from BigQuery would also be amazing for us. The easiest way would be just to handle it as proposed by @tuaris by flattening the fields - it's not the most beautiful thing but it helps to avoid writing SQL for non-techies :-)

Any update on the progress would be appreciated.

**Comment by allan-simon** [comment]
I've asked for guidance in order to tackle this issue on their gitter, but I got no reply :(

**Comment by allan-simon** [comment]
https://github.com/metabase/metabase/issues/10185 for my proposal

**Comment by marcoruggine** [comment]
Hi! any update on this? We're using BigQuery and I'm trying to push for data democratization via Metabase but unfortunately this issue blocks all non-coders to use it. Having Metabase Notebook access these fields would be a game changer

**Comment by marcoruggine** [comment]
Hi! 
is it possible to simply show the nested structures in a cell? 

It would be a great improvement getting rid of the whole `"FieldValue{attribute=PRIMITIVE, value=`

thanks

<img width="1116" alt="Screenshot 2022-10-20 at 12 24 22" src="https://user-images.githubusercontent.com/20041428/196924099-15b2482d-34b2-41a5-90c7-bbfad5c66896.png">

**Comment by jamesgreenblue** [comment]
I'm also grappling with this issue @flamber – have opened a discussion on the forum https://discourse.metabase.com/t/firestore-bigquery-metabase-issue-with-joining-and-displaying-foreign-key-name-value/24051?u=jamesgreenblue

Is creating views in BigQuery the solution? Or should we be focusing our efforts into improvements to the Metabase BigQuery driver?

**Comment by cbeauch** [comment]
I tried this in the beta. So yeah, Metabase now supports STRUCT data types but you can't filter or anything with them. Is that a bug or am I missing the use case for this? 

```
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Cannot access field label_name on a value with type ARRAY<STRUCT<label_name STRING>> at [2:817]",
      "reason": "invalidQuery"
    }
  ],
  "message": "Cannot access field label_name on a value with type ARRAY<STRUCT<label_name STRING>> at [2:817]",
  "status": "INVALID_ARGUMENT"
}
```

**Comment by z3z1ma** [comment]
> This issue DOESN'T entail supporting arrays (aka repeated). It also doesn't entail working with the new [BigQuery JSON support](https://cloud.google.com/bigquery/docs/release-notes#January_06_2022), this totally unstructured JSON support is new and not frequent (yet).

@cbeauch you are working with an ARRAY there, see note above from the issue description
