### ISSUE TITLE
Whitelabel the "no results" image

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#26623]
**Is your feature request related to a problem? Please describe.**
If there are no results, we show an image, but this should be replaced in whitelabelling

**Describe the solution you'd like**
The possibility of uploading a custom image of no-results when using whitelabelling

**Describe alternatives you've considered**
nginx-ing

**Additional context**
Related to #23826

**Comment by bertrandjamin** [comment]
+1 here since 1.47 the boat is really a nice illustration but a bit to "Metabase design oriented" notably in embedded environnement. 

Our customers do not understand why they see a boat as their activities have nothing to do with it ^^

**Comment by albertoperdomo** [comment]
Would hiding the image do it for you @bertrandjamin ?

**Comment by bertrandjamin** [comment]
It could be an acceptable quick fix, yes 👍

To go further, for embedded pro-environnement it could be really powerful to allow more personnalization on those component :) 

Thanks

**Comment by albertoperdomo** [comment]
Duplicate. Closing in favor of https://github.com/metabase/metabase/issues/23826, which has more upvotes.

**Comment by albertoperdomo** [comment]
We implemented customization of the no results image via https://github.com/metabase/metabase/issues/39246. This ships in Metabase v50.
