### ISSUE TITLE
Implement hierarchical field type system

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2663]
I've proposed a few times in the past (most recently in PR #1955) but our current Field type system makes supporting new DB-specific types much harder than it should be.

Take #2656 (Postgres interval support), for example. Suppose we wanted to add support for Postgres intervals and treat them just like integers on the frontend, but do some special casting on the backend in the generated SQL. 

Currently, we have to change as many as two dozen files to add support for a new type, including the frontend; there'd be a lot less to do if we could just say an `Interval` "inherited" from an `Integer`. 

I think it makes sense to address this issue sooner rather than later because we're paying high-APR interest on this tech debt every day we stick with the status quo. Here's a probably-incomplete list of type-support related issues that would possible (for some) or much easier (for others) to address if we had a more flexible type system:

*  #659 add the ability to mark a Field as nullable in schema info
*  #708 Ability to access fields in JSON Dicts in Postgres driver
*  #1324 Add support for "yyyymmddhhmmss" formatted datetime strings
*  #1367 convert string literals to BSON IDs in Mongo queries when appropriate
*  #1522 Add Special Type "Amount"/"Currency"
*  #1576 Add Special Type: DateTime String (ISO)
*  #1687 Support arrays of foreign keys and embedded foreign keys in MongoDB databases
*  #1698 Force truncate numbers
*  #1723 Support filtering by byte array / binary fields
*  #1858 Allow metrics to have special types and custom formating
*  #1889 Support unix timestamps in microseconds (µs)
*  #1891 Support inet (ip address) type columns in Postgres
*  #2069 Filter by time in addition to date
*  #2327 Support Postgres POINT type
*  #2477 Support an "obfuscated" visibility type for fields
*  #2656 Postgres interval support
*  #2662 Support nested records in BigQuery
*  #2811 Multiseries should allow mixing cards broken out by DateTime and numeric timestamps
*  #2947 MongoDB error: can't convert from BSON type Object to Date
*  #2974 Support MongoDB Arrays
*  #2987 Use ObjectID as DateTime for MongoDB
*  #3138 Support Druid "Theta Sketch" type (?)
*  #3321 Add Unit (Time, Volume, Etc.) Formatting in Chart Settings (?)

**Comment by salsakran** [comment]
yup, @agilliland had a really good overview of our current type system plus a proposal for v.Next of it. I think we should revisit it and make time to go forward with it

**Comment by camsaul** [comment]
I don't remember seeing any other proposals besides #1955 (?)

**Comment by puhrez** [comment]
These is an incredibly interesting problem, where could I get started to understand the current type system?

**Comment by camsaul** [comment]
@puhrez This issue is open specifically because the current type system is hard to wrap your head around. Our current types are *listed* [here](https://github.com/metabase/metabase/blob/master/src/metabase/models/field.clj#L33-L48) but used all over the place, willy-nilly.

**Comment by camsaul** [comment]
To keep the scope of this reasonable I propose breaking this out into a few different PRs:

#### Proposed PRs

-  [ ] Remove `field_type` (`info`/`dimension`) / other cleanup (#3319)
-  [ ] Focus the definition of `special_type`. Right now, it's used to keep track of several things, not all of which are type-related; to fix this, I propose the following:
    -  [ ] Remove `:category` special type; add new `is_category` (`is_low_cardinality`?) column.

        Whether or not something is a category is a product of the cardinality of the field; e.g. something can be a `:city` and may or may not be a category. Our current system of making category a special type doesn't make a ton of sense, IMO.
    -  [ ] Remove `:id` special type; add new `is_pk` column.

        Again, whether or not a field is a primary key isn't a product its type. It's possible, for example, for a Field to be a `:name` (special type) and a primary key at the same time. Or a field might be low-cardinality (a category) and be a primary key at the same time.

    -  [ ] Remove `:fk` special type. Fields that are foreign keys are ones that have non-nil`fk_target_field_id`.

        Again, whether a field is a foreign key has nothing to do with its type, so it doesn't really make sense to make `:fk` a special type.
-  [ ] Introduce new Field `actual_type` and `effective_type` columns, which replace `base_type` and `special_type`. Actual type will be used to track the actual type of the column in the database and won't be editable; `effective_type` can be changed by the user. See below for examples of how this will all fit together.
-  [ ] Finally, introduce the new hierarchical types.


#### Examples

Once everything is wrapped up, here are a few examples of how it will all fit together:

*  A field with a `actual_type` of `Integer` and a `effective_type` of `UNIXTimestampMilliseconds`. 

  The frontend will know `UNIXTimestampMilliseconds` derives from `DateTime`, and can display an appropriate widget. The backend will know that we want to treat what is actually an integer like a date and can perform the necessary conversions. 

*  A field with an `actual_type` of `Text` and a `effective_type` of `Number`. 

  This would let the frontend know it's appropriate to show a numeric widget and let the backend know it needs to convert that number to text going in and back to numbers coming out.

*  A field with an `actual_type` of `MongoBSONID`. 

  `MongoBSONID` derives from `Text`, and that's all the frontend needs to know about it. The backend however can convert the string that comes in to the appropriate Java type when running a query (#1367). This is an example of how the new type system will make it a lot easier to add support for DB-specific types in the future.

*  A field with an `actual_type` of `Float` and an `effective_type` of `Latitude`. 

  Here the backend doesn't care about `Latitude` at all. It knows `Latitude` is a type of `Float`, so it doesn't need to do any conversions. The frontend however might display a special widget to pick it from a map. In the future, either party might extend tweak its handling of the `Latitude` type to make sure the values are between `-90.0` and `90.0`, inclusive.

*  A field with an `actual_type` of `BigDecimal` and an `effective_type` of `Currency`.

  Again, the backend doesn't have to care about what a `Currency` is. But the frontend can format values with this type in an appropriate way. (#1522)


##### Etc.

@salsakran @tlrobinson do these proposed changes make sense?

**Comment by salsakran** [comment]
regarding the iscategory thing, I think the whole exactly 40 values being the cutoff is a bit silly.

I think we should just keep track of the cardinality of a field, and DoSmartThings based on that.

**Comment by salsakran** [comment]
otherwise, things mostly make sense to me.

**Comment by camsaul** [comment]
Sure.

**Comment by camsaul** [comment]
That will definitely add some work to this project, since it's not super easy to make all these changes to start looking at cardinality instead of a simple `:is_category` flag.

**Comment by salsakran** [comment]
Or we can add a cardinality field, and have the isCategory be a computed field.

**Comment by camsaul** [comment]
Yeah, I'll figure it out

**Comment by salsakran** [comment]
@camsaul one thought that comes to me is whether it might make sense to separate the `effective_type` concept (i.e. how the bytes on disk should be interpreted) from a `semantic_type`. Eg, things like `name` don't feel like na effective type to me, and the mixing of meat/logical space meaning from what effectively is a type casting target (eg a string -> utc timestamp in milliseconds) to higher order info

**Comment by camsaul** [comment]
That's a good point. It would probably make sense to split things out like that.

I'm trying to split things out into bite-sized chunks so I'm thinking it might make sense to convert `base_type` to the new type hierarchy first and migrate `special_type` to a hierarchical `effective_type`/`semantic_type` (as well as adding the new `is_pk` and `cardinality` columns) as next steps after that.

**Comment by camsaul** [comment]
On second thought...

How do you see a separate `effective_type` and `semantic_type` working? Would semantic types like `URL`/`Name`/`Currency` still derive from types like `Text` and `Float`?  I would assume they would have to in order to keep the main benefit of the type hierarchy, i.e. being able to add new types that automatically default to the behavior of their parent types. But if we do that is there really a point to having a separate `effective_type` and `semantic_type`? What if someone does something like this:

base_type | effective_type | semantic_type 
--- | --- | ---
Text | Text | Currency

I agree that semantic types are a different concept from the casting operation, but in all the cases we have a given semantic type requires a given casting operation so I'm not sure it makes sense to decouple the two.

**Comment by salsakran** [comment]
using price in usd stored as a string , I'd say
base_type = "text"
effective_type = "number"
semantic_type = "currency"
--> how do we denote things like USD, or for times Timezone info?
(Note I'm not asking for that in this issue/set of PRs, but rather how will the shape of the choice we make here make that easy or hard)

**Comment by salsakran** [comment]
or maybe `effective_type` above should be "currency", which is derived from "number". and USD is in the `semantic_type`? That feels muddy as well, however.

**Comment by camsaul** [comment]
I was thinking originally `Currency` would be derived from `Number`, and something like `CurrencyUSD` would be derived from `Currency`. That would all be part of one single column, `effective_type`.

The backend would know it needs to cast to `Number` and not care about what a `Currency` or `CurrencyUSD` is. The frontend can display it appropriately given this extra info.

**Comment by salsakran** [comment]
Something about `CurrencyUSD` makes me violently itchy. It means that the base level of semantic types would explode in number -- i.e. we'd have an entry for every currency, timezone, etc.

**Comment by camsaul** [comment]
Things like `USD` would only be allowed for `Currency`, right? So one might say that `USD` is a *subtype* of `Currency`, right? I think the thing we have to accept here its that separating things `Currency` and `USD` into two separate columns doesn't change the number of type combinations that would be possible. It would make things a lot more hairy IMO trying to figure out which combinations are allowed, enforcing constraints, and handling them appropriately in different places that might not know about them.

At any rate, I don't think having few hundred different types will be a problem as long as they're organized nicely on the frontend. The main benefit of introducing this type hierarchy is to allow us to define lots of specialized types to support special behavior without the rest of the app caring or knowing about them

**Comment by camsaul** [comment]
Implemented by #3327

**Comment by mysticaltech** [comment]
@camsaul you had a real vision here, too bad it is not yet reflected in the UI almost 5 years later. My colleagues are threatening to move back to DataStudio because we can't get a simple ISO Date String column work as a Date.

**Comment by camsaul** [comment]
Hi @mysticaltech, we're actively looking at implementing support for temporal literal strings, see for example PR #13860

**Comment by mysticaltech** [comment]
Hi @camsaul, makes sense, with such a large number of databases you have to support, what you folks are doing is truly amazing. My issue was solved by just switching to Unix timestamps integer and using the corresponding special type in the data model settings, I actually understood how this worked by going through types.clj with the hope of finding a way to make ISO-8601 work. I'm using Druid through Presto (to have SQL), so only one date column supported there.
