### ISSUE TITLE
Hidden table, unavailable filters

### ISSUE THREAD

**Issue by OnFormLimited** [metabase/metabase#26632]
When a custom SQL statement is written against a hidden table that includes field filter variables - drop down filters in a dashboard are not invoked. The table has to be unhidden for those drop downs to work.

 - Your browser and the version: (Edge)
- Your operating system: (Windows 10)
- Your databases: (Postgres,)
- Metabase version: Latest cloud version

**Severity**
Compromises security and functionality

**Comment by flamber** [comment]
Hi @OnFormLimited 
If you hide a table, then the table and fields will not be functional as normal. This is expected.
You should not use hide functionality if these tables/fields contain truly sensitive information, then you should use permissions. And perhaps create a separate table/view that only includes the column of the dropdown you want.
