### ISSUE TITLE
Migrate to the new Google Identity Services library

### ISSUE THREAD

**Issue by hanxiang01** [metabase/metabase#26663]
Received an email from google that metabase uses the legacy Google Sign-In web solution. google announced plans stating that after March 31, 2023, authentication support for the Google Sign-In JavaScript platform library will no longer be supported.

After 31 March 2023, migration to the new Google Identity service will be necessary for customers using Google Accounts to sign in to your platform. The SDK will use the new Sign In With Google client library.

Is there an upgrade for the latest version of metabase and how do I go about migrating it?

thank you

**Comment by flamber** [comment]
Already done #17429. Latest release is 0.44.6: https://github.com/metabase/metabase/releases/latest
