### ISSUE TITLE
Error running query : Out of no where after latest update

### ISSUE THREAD

**Issue by omkar-work** [metabase/metabase#26698]
**Describe the bug**
This question was working properly before I updated the metabase. Now there is this weird error with out any specific context.
If I comment out line no 130-134 then the question is working fine. But there is nothing extra in these lines, it's same as its previous lines of code.
However if I run this query in athena directly it runs correctly without any chage. But metabase is not even running it in athena, it's failing that prior to that.
**Screenshots**
![image](https://user-images.githubusercontent.com/86356654/203551672-1ccb0355-0aa0-4bd7-8ef2-5cb14543bd6c.png)

**Logs**

[logs.txt](https://github.com/metabase/metabase/files/10075690/logs.txt)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
Response from the get request of the question:
[response.txt](https://github.com/metabase/metabase/files/10075686/response.txt)

**Comment by flamber** [comment]
Hi @omkar-work 
Which version of Metabase were you using previously?
And which version of the Athena driver are you using?
Were you also using Java 17 before? Can you try with Java 11?

**Comment by omkar-work** [comment]
Metabase was 0.44.0 and Athena was same as now athena engine 2.
This is Diagnostic info as of now.
{
  "browser-info": {
    "language": "en-IN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.4+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.4+8",
    "os.name": "Linux",
    "os.version": "4.14.104-95.84.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.12-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-11-01",
      "tag": "v0.44.6",
      "branch": "release-x.44.x",
      "hash": "5c6ae21"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}

**Comment by flamber** [comment]
@omkar-work I'm not asking which Athena engine you are using, I'm asking which version you are using https://github.com/dacort/metabase-athena-driver
Revert to 0.44.0 and try again, then upgrade to 0.44.1 and try, and so on, so you can figure out which version was the last on working.

**Comment by omkar-work** [comment]
Java runtime didn't change but the athena version changed to 1.5.1 (latest)

**Comment by flamber** [comment]
@omkar-work Then try with the old Athena driver you were using on 0.44.0. If the problem is in the driver, then you'll need to open an issue against the driver repo.
