### ISSUE TITLE
Unable to connect to SQL Server with special characters in DB password

### ISSUE THREAD

**Issue by marcbarbosa** [metabase/metabase#2676]
We are unable to connect to our MSSQL database with a specific password.

Steps to reproduce:
1) Create a database login `metabase_user` with password `968$5hfeN$[0}ro`
2) Try to `ADD DATABASE` on Metabase with the previous credentials.

Results: `java.sql.SQLException: Login failed for user 'metabase_user'.`

The solution was change the password by one with no special chars, like `normalpassword`

*  I am using the Chrome 49.0.2623.112 browser.
*  My computer's OS is OSX 10.11.5.
*  I'm running Metabase on AWS Beanstalk.
*  My database is SQL Server 2014.
*  My Metabase version is v0.17.1.

Maybe those issues are related: https://github.com/metabase/metabase/issues/2604 and https://github.com/metabase/metabase/issues/1854

**Comment by camsaul** [comment]
The password ends up as part of a JDBC connection string so I'm guessing it doesn't like one of the characters being in the string. It probably needs to be escaped somehow

**Comment by camsaul** [comment]
@marcbarbosa you're right, this is the same issue as #2604 after all, so I'm going to close this as a duplicate. As mentioned on that thread we're just using the jTDS JDBC driver and a normal JDBC connection string so if you knows the appropriate thing to do here to escape the special characters let me know and I'll make the changes 😓
