### ISSUE TITLE
TypeError: can't access property "features", e is null

### ISSUE THREAD

**Issue by geoHeil** [metabase/metabase#26762]
For a choropleth map (after recent metabase releaes) I get the following error:

```
TypeError: can't access property "features", e is null
value ChoroplethMap.jsx:152
    value ChoroplethMap.jsx:58
    setTimeout handler*11966/value/< ChoroplethMap.jsx:56
    value ChoroplethMap.jsx:61
    value ChoroplethMap.jsx:124

```

and can no longer render the map in the browser.

Other visualizations (i.e. bar chart) work fine though.

**Comment by geoHeil** [comment]
Metabase claims that: https://drive.google.com/uc?export=download&id=1XTqNMXnLS3xWdLJ5YVSDMvVoQm4VC_XJ (Geo JSON of Austria) is unparsable.

However:

1. QGIS can parse and open that file nicely
2. Older version of Metabase did load this file nicely as well

**Comment by paoliniluis** [comment]
This seems to be similar to https://github.com/metabase/metabase/issues/26213

**Comment by paoliniluis** [comment]
@geoHeil can you post diagnostic info?

**Comment by geoHeil** [comment]
```
{
  "browser-info": {
    "language": "de",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.4.0-131-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.6 (Debian 14.6-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-11-01",
      "tag": "v0.44.6",
      "branch": "release-x.44.x",
      "hash": "5c6ae21"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by geoHeil** [comment]
also for 0.45.0-RC2 the smae failure can be observed.

I tried to downgrade - but this is not super easy as the liquibase migrations are clashing.

**Comment by flamber** [comment]
Hi @geoHeil 
What does "an older version of Metabase" exactly mean? The Google driver URL has redirects, which are no longer being followed for security reasons https://github.com/metabase/metabase/security/advisories/GHSA-w5j7-4mgm-77f4
Your GeoJSON is 37MB, which is way too much to deliver to the browser #6343
Try simplifying the map with https://mapshaper.org/ which can get the file down to a couple of MB.

**Comment by geoHeil** [comment]
@flamber would hosting the file on github work without redirects?  What is the maximal size you support?

**Comment by geoHeil** [comment]
Thanks @flamber Will it also be possible to serve the raw files from a private repository? Do you have an example?

I can confirm that the proposed suggestion works fine for a public repository.
