### ISSUE TITLE
Pie chart show percentage radio group instead of toggles

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#26776]
[Notion doc](https://www.notion.so/metabase/Maz-notes-on-viz-settings-67aed0e4ddcc4d4a83028992c4301820#d898bc3443334b008c5d0071a3057bd6)

## Summary 

Instead of having two toggles for showing slice percentages, we want to have a radio group.

#### Current
<img width="364" alt="Screen Shot 2022-11-24 at 1 40 31 AM" src="https://user-images.githubusercontent.com/14301985/203657980-79a49386-e61f-427c-854f-8d540c194fa3.png">

#### Desired
<img width="367" alt="Screen Shot 2022-11-24 at 1 38 18 AM" src="https://user-images.githubusercontent.com/14301985/203657722-ff743680-e98c-4d11-9c83-e02b1b2c259c.png">

## Tech details

Since we had two separate settings, we need to write a migration to use `pie.percent_visibility` settings which can be one of the following values:
- `off`: percentages are not shown
- `legend`: percentages are shown in the legend
- `inside`: percentages are shown inside slices

The migration logic:

if `pie.show_legend_perecent is not defined, pie.show_data_labels is not defined` -> do not write anything
else if `pie.show_data_labels is true` -> update `pie.percent_visibility` to `inside`
else if `pie.show_legend_perecent is true` -> update `pie.percent_visibility` to `legend`

**Comment by flamber** [comment]
Would likely fix #7127 as well

**Comment by ignacio-mb** [comment]
Should this be closed? (doing cleanup)

**Comment by tsmacdonald** [comment]
Good catch; fixed by #26721
