### ISSUE TITLE
ability to disable Google Analytics tracking

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#2677]
There should be an option under admin setting to disable Google Analytics automated tracking.

https://github.com/metabase/metabase/blob/master/docs/information-collection.md

**Comment by kdoh** [comment]
Hey there @CzechJiri. This option already exists as part of the admin settings. If you scroll to the bottom you should see this option.
<img width="624" alt="screenshot 2016-05-26 13 42 06" src="https://cloud.githubusercontent.com/assets/5248953/15589438/bbe29be6-2347-11e6-9f11-f5d0da1ada7c.png">

You can disable this at any time to stop sending anonymous events.

**Comment by CzechJiri** [comment]
how the heck did I miss it....

please close the ticket

thank you

**Comment by kdoh** [comment]
No problem. We understand privacy is a concern and we care a lot about it too.

**Comment by markscoin** [comment]
I cant find this option? where exactly is it? I noticed is was making requests to google analytics on my local environment but I do not see that option in the app settings.

**Comment by mazameli** [comment]
Here's more information about what exactly we do and don't anonymously track:
http://www.metabase.com/docs/latest/information-collection.html

**Comment by dumoulinj** [comment]
Even if anonymous tracking is disabled, the script "analytics.js" is downloaded anyway. Would not it make more sense to disable its download in this case? I get that this script will not be called by Metabase later (since the anonymous tracking is disabled), but just its download can still represent a security concern for some companies (like mine).

**Comment by flamber** [comment]
@dumoulinj 
I would say that you're right - the script shouldn't even be loaded, when the function is disabled.
I'm using the Nginx `sub_filter` function to remove the GA when reverse-proxing, since our company doesn't allow GA to be used on internal systems:
```
location / {
  sub_filter "})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');" "});";
  sub_filter "ga('create', ga_code, 'auto');" "function ga(){return false;};";
  sub_filter_once on;
  proxy_pass       http://mb_servers;
}
```

**Comment by dumoulinj** [comment]
@flamber 
Thanks for this input. I guess I will go for a similar solution (we are using Apache, so I guess mod_substitute should do the trick).

**Comment by dumoulinj** [comment]
Could the Metabase team comment on this topic and if they plan to change this behavior in the future? Thanks in advance

**Comment by flamber** [comment]
@dumoulinj This issue was closed almost 3 years ago. Please create a new issue, list your privacy concerns or company policies, and you can reference this issue.
