### ISSUE TITLE
Search for a saved question related to a specific table/collection name

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#26785]
Is there a way to filter questions based on what table/collection it is pointing to? Like if I search "Table1" it will show question1, question2, etc. (which are using this particular table/collection)

I'm having trouble finding a query that came from metabase that is making our secondary member of a replica set slow.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8-post-Ubuntu-1ubuntu218.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8-post-Ubuntu-1ubuntu218.04",
    "os.name": "Linux",
    "os.version": "5.4.0-1095-azure",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-11-01",
      "tag": "v0.44.6",
      "branch": "release-x.44.x",
      "hash": "5c6ae21"
    },
    "settings": {
      "report-timezone": "Asia/Manila"
    }
  }
}

**Comment by paoliniluis** [comment]
Please post in our Discourse (https://discourse.metabase.com/) forum, this is our issue tracker thanks!
