### ISSUE TITLE
"Invalid request" on changing visibility of some foreign key fields

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#2678]
hi all! when we try to change the visibility of a few foreign key integer columns, we get an "Invalid request" error. doesn't seem to matter what we're changing it from or to. only happens on a few columns; others are fine. cc @kurtosis-color.

looking at the HTTP request, it's `PUT /api/field/484` that returns 400 with body `Invalid request`. i'll include a redacted copy of the request body at the bottom here. i checked the log, but metabase doesn't seem to write anything to it for this error.

thanks in advance!

*  I am using the Firefox 46.0.1 browser.
*  My computer's OS is Mac OS X El Capitan.
*  I'm running Metabase locally from the JAR, on AWS, Ubuntu 14.
*  My database is H2 for Metabase, Postgres for data.
*  My Metabase version is 0.17.1.

example request:
```json
{
  "base_type": "IntegerField",
  "created_at": "2015-09-09T19:43:51.869Z",
  "display_name": "Kit Order Id",
  "preview_display": true,
  "target": {
    "table": {
      "fields_lookup": {
        "..."
      },
      "breakout_options": {
        "validFieldsFilters": [
          null
        ],
        "fields": [
          "..."
        ],
        "advanced": false,
        "description": "",
        "short": "breakout",
        "name": "Break out by dimension"
      },
      "aggregation_options": [
        "..."
      ],
      "created_at": "2015-09-09T19:43:39.776Z",
      "metrics": [],
      "display_name": "Kit order",
      "field_values": {
        "..."
      },
      "visibility_type": null,
      "db_id": 3,
      "id": 72,
      "active": true,
      "entity_name": null,
      "updated_at": "2016-05-19T00:00:02.013Z",
      "rows": 6026,
      "segments": [],
      "fields": [
        "..."
      ],
      "name": "kit_orders_kitorder",
      "db": {
        "created_at": "2015-09-09T19:43:39.639Z",
        "engine": "postgres",
        "id": 3,
        "is_sample": false,
        "details": {
          "port": 5432,
          "ssl": true,
          "engine": "postgres",
          "dbname": "...",
          "host": "...",
          "password": "...",
          "user": "..."
        },
        "updated_at": "2015-09-25T23:40:06.656Z",
        "is_full_sync": true,
        "name": "Users",
        "organization_id": null,
        "features": [
          "standard-deviation-aggregations",
          "foreign-keys",
          "expressions",
          "set-timezone"
        ],
        "description": null
      },
      "raw_table_id": 32,
      "schema": "public",
      "entity_type": null,
      "description": null
    },
    "base_type": "IntegerField",
    "created_at": "2015-09-09T19:43:50.448Z",
    "display_name": "Id",
    "preview_display": true,
    "visibility_type": "normal",
    "position": 0,
    "field_type": "info",
    "last_analyzed": "2016-05-19T21:34:00.596Z",
    "raw_column_id": 427,
    "id": 459,
    "parent_id": null,
    "active": true,
    "updated_at": "2015-09-09T19:43:54.795Z",
    "fk_target_field_id": null,
    "name": "id",
    "special_type": "id",
    "table_id": 72,
    "description": null
  },
  "visibility_type": "details-only",
  "position": 0,
  "field_type": "sensitive",
  "last_analyzed": "2016-05-19T21:34:00.545Z",
  "raw_column_id": 421,
  "id": 484,
  "parent_id": null,
  "active": true,
  "updated_at": "2016-05-26T22:31:08.080Z",
  "fk_target_field_id": 459,
  "name": "kit_order_id",
  "special_type": "fk",
  "table_id": 79,
  "description": null
}
```

**Comment by snarfed** [comment]
hey all! this has been gradually getting more and more painful for us. anything we can do to help debug? or any workarounds you can recommend in the meantime? i'm not too proud to poke around in metabase's internal db, if i can avoid shooting myself in the foot. :P

**Comment by salsakran** [comment]
ack. Not sure why this was labeled an "error" 

This sounds like a clear bug.

**Comment by salsakran** [comment]
is there any pattern to which fields it works on and which it doesn't?

**Comment by snarfed** [comment]
not that i can tell. happy to send parts of the schema if you want!

**Comment by salsakran** [comment]
yup, fire it this way via carrier pigeon.

**Comment by camsaul** [comment]
Ok I figured out the issue here. `sensitive` used to be an option for `field_type`, but a few releases ago Allen added the `visibility_type` column and made `sensitive` an option for that while removing it from `field_type`. The data migration he wrote for this change set `visibility_type` to `sensitive` where appropriate, but didn't fix `field_type`.

This shouldn't have been an issue but the API endpoint has logic that validates the *existing* values of the Field in the database, or otherwise throws a generic 400 exception.

I'll have a PR to fix this behavior shortly
