### ISSUE TITLE
Cannot login when I redirect metabase service to nginx non-root path

### ISSUE THREAD

**Issue by crawfordma** [metabase/metabase#26786]
Hello team, here is my nginx config:
![截屏2022-11-29 18 31 33](https://user-images.githubusercontent.com/110077073/204505950-35755796-4556-4dec-8ac2-eb7801b83310.png)

I can login metabase when I use root path like: location /

but now it's failed when I set path location /metabase
![截屏2022-11-29 18 32 59](https://user-images.githubusercontent.com/110077073/204506304-ed1faf09-b4f4-4ede-acd0-680f6d01910c.png)

Please let me if you need any further information.

**Comment by crawfordma** [comment]
I think the reason is login page is redirect to https://hostname/auth/login? and there is no setting for this path.
So How can I resolve this and why it has no error when I use "location /" in nginx conf

**Comment by flamber** [comment]
You need to add slash (`/`) as suffix when using non-root path.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
