### ISSUE TITLE
Fix all tests that hardcode driver names and prevent regressions with a Kondo linter

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#26807]
Third-party driver authors who want to run our test suite often cannot get it to pass because we have stuff like this

https://github.com/metabase/metabase/blob/c7fe601b91b2a5c2442ed7690a92a01677dc49f0/test/metabase/query_processor_test/date_bucketing_test.clj#L279

in tests where we hardcode specific driver names to specific test results, or even skip specific tests for certain drivers (e.g. we skip `TIME` tests for drivers that do not have a `TIME` data type).

~The current "right way" to go about these cases is to add methods to `metabase.test.data.interface`, for example `sorts-nil-first?`, and check that method rather than hardcoding driver names. Then drivers can implement those methods as needed to get the correct version of the tests.~

~https://github.com/metabase/metabase/blob/master/test/metabase/test/data/interface.clj#L348-L357~

~We need to go in and add more methods to `metabase.test.data.interface` to cover other variations in driver behavior and eliminate the need to hardcode driver names in any tests altogether. We should enforce a ban on this practice in the future; I think removing `normal-drivers-except` is a start, and adding a custom Kondo linter to keep people from using driver name keywords inside of `deftest` forms would be a good idea as well (to prevent `case` and `(disj (mt/normal-drivers) ...)` and stuff like that).~

### Thoughts

Instead of adding a bunch of new methods to `metabase.test.data.interface`, maybe we should try to just treat all these things as features so we can use `driver/supports?` or `driver/database-supports?`. There's no reason `:sorts-nil-first` or maybe `:test/sorts-nil-first` could not be a feature. We have a lot of helper functions around checking features and only testing drivers with certain features so this would likely lead to a nicer developer experience than writing a ton of new one-off methods in `metabase.test.data.interface`. If we go this route going forward, we should probably convert existing stuff like the `sorts-nil-first?` method to features so we don't have multiple patterns for accomplishing the same thing.

**Comment by camsaul** [comment]
Maybe a good way to start this project would be to write the linter first and add `#_{:clj-kondo/ignore ...}` for existing hardcodings. That would prevent any new ones from popping up. Then we could fix the old ones at our leisure.

**Comment by bshepherdson** [comment]
At least the initial stage of this, adding the linter and `:clj-kondo/ignore`-ing all the existing violations, is straightforward.

**Comment by slvrtrn** [comment]
I'd like to bump this one: currently, these hardcoded test branches are holding back the ClickHouse driver from implementing timezone support "properly" without disabling the entire feature for the test run and re-implementing some of the tests in the driver code - despite Metabase assertions differing only slightly and, most of the time, insignificantly, that still counts as a failed test.

**Comment by camsaul** [comment]
I think 

https://github.com/metabase/metabase/blob/856b449/test/metabase/query_processor_test/timezones_test.clj#L250-L263

is the best way to tackle this going forward
