### ISSUE TITLE
Improve API documents

### ISSUE THREAD

**Issue by Attsun1031** [metabase/metabase#26812]
**Is your feature request related to a problem? Please describe.**
It is a bit difficult to use API cause [current API documents](https://www.metabase.com/docs/latest/api-documentation.html) doesn't have enough information such as:
- Specifications of request query parameters
- Specifications of request JSON bodies
- Specifications of response JSON bodies

Although we can inspect these specs by looking metabase requests with developer console, it would be nicer if documents has enough and reliable information.

**Describe the solution you'd like**
Improve API documents.
OpenAPI style will be good (e.g. [superset API docs](https://superset.apache.org/docs/api/))

**Describe alternatives you've considered**
I thought of creating official client libraries, but it needs more development and maintenance than just improving docs. Improving docs is enough.

**How important is this feature to you?**
Since my team has to use API to manage metabase resources as code, reliable API documents are important.

**Additional context**
Nothing

**Comment by paoliniluis** [comment]
Thanks! this is a duplicate of https://github.com/metabase/metabase/issues/9033

**Comment by Attsun1031** [comment]
Sorry, I missed the issue. Thanks!
