### ISSUE TITLE
Ability to zoom within charts by dragging a rectangle?

### ISSUE THREAD

**Issue by jongyonkim** [metabase/metabase#2681]
It would help a lot if there is a way to zoom in/out by dragging a rectangle (and reset view) for charts (line).

I'm currently using SQL `where` to manually set the timestamp range every time I want to "zoom" for time series data.

This feature alone would make us consider Metabase strongly over traditional BI visualization tools.

**Comment by Leen15** [comment]
+1

**Comment by salsakran** [comment]
this works in our query builder and has for years now.
