### ISSUE TITLE
Dashboard opens in editing state with added card

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#26826]
**Describe the bug**
After creating a dashboard, saving it, and navigating to another one it opens the dashboard in the editing mode with a card added.

**To Reproduce**
1. Create a dashboard D1 with any card
2. Create a question Q1, save and add on a dashboard D2, save the dashboard
3. In search find D1 and open it

**Actual behavior**
D1 has been opened in the editing mode with a Q1 card added

**Expected behavior**
It opens the D1 dashboard in the view mode, without any cards added

**Video**
<video src="https://user-images.githubusercontent.com/14301985/204849076-c44a772d-e20d-45a5-ab29-28a62505f947.mov" />

**Comment by flamber** [comment]
Remember similar problem was fixed a long time ago and fixed, but might have returned around the dashboard overhaul ~39.
Related to #23684
