### ISSUE TITLE
Fine-grained dashboard, question, and querying permissions

### ISSUE THREAD

**Issue by Leen15** [metabase/metabase#2682]
Hi, is it possible to have a rule for access only to dashboard? 
We have a big database and we would like to allow some not technician people to view metabase queries without possibility to edit or create a new one.

Thanks!

**Comment by tlrobinson** [comment]
Not currently.

Related to #1175

**Comment by salsakran** [comment]
You can do this now, via collection permissions + data access permissions. Just give them read permissions to a collection of dashboards and turn off all self-service data access permissions.
