### ISSUE TITLE
Sharable question results (public links)

### ISSUE THREAD

**Issue by Leen15** [metabase/metabase#2683]
We are trying to move from heroku dataclips to metabase.
Best of feature of dataclips is the possibility to share a link with query result in JSON format.

Is there a way for do it with metabase?

Thanks

**Comment by tlrobinson** [comment]
Not currently.

Would you expect the link to work only for logged in users, or anyone with the link?

BTW, it would be pretty easy to hack something together using the API (which isn't yet documented, see #2689)

**Comment by Leen15** [comment]
In dataclips there are two possibilities: 
- only for authenticated users
- anyone with the link (for us, the most used)

I've already saw that issue for API use, but it's too complicated use SESSION COOKIE for authenticate user from an external service and we don't want to pass SQL query in payload because there is the possibility that who see the payload can edit the query and have full access to the DB.

**Comment by salsakran** [comment]
So thinking through a few possibilities, I think we'd need to generate a token for each question or a instance-wide salt + a one-way hash. 

I think having this be done on a per-question basis would be too messy UX wise, so it'd need to be a site-wide setting. 

I'm assuming this would strictly be an API endpoint.

**Comment by Leen15** [comment]
This is an example of the link generated from dataclips:

![image](https://cloud.githubusercontent.com/assets/3629071/15787841/cade4e32-29c4-11e6-9ec8-a2a01856a499.png)

original link:
https://dataclips.heroku.com/sphjbjbmon**********.json

redirect to:
https://dataclips.s3.amazonaws.com/******.json?response-content-type=application/json&X-Amz-Expires=600&X-Amz-Date=20160603T174702Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJYMGOQOF*****/20160603/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=8cdc4d1bb35ee77d8f464dc57227cc5ec2****

There is also a cache on the original link, so the query is not made at every request (bad for some cases).

**Comment by Leen15** [comment]
Could be greate to have something like:

https://metabase.domain.com/card/21/share?type=json

:)

**Comment by salsakran** [comment]
Would it still be great if anyone on the internet that found your metabase instance hostname could do the below? ;)

```
#!/bin/bash
        for i in  `seq 1 1000`; do
            wget https://metabase.yourdomain.com/card/$i/share?type=json
        done
```

**Comment by Leen15** [comment]
of course should exist a setting for this at question level:

![image](https://cloud.githubusercontent.com/assets/3629071/15788107/0d39e57e-29c6-11e6-819d-bdfedd03ac13.png)

:P

Also I just noticed that dataclips generate a random string for every question, so not a incremental index, i think for avoid bulk request as you suggest :D

**Comment by tlrobinson** [comment]
@Leen15 I was actually thinking you could set up a simple web app that hits the Metabase API and returns the resulting JSON, so the credentials wouldn't be exposed. It's really easy to deploy simple endpoints these days with services like Amazon Lambda and [Tonic Endpoint](https://tonicdev.com/docs/endpoint).

Here's an example using a Tonic Endpoint:

```
const rp = require("request-promise");

exports.tonicEndpoint = function(request, response) {
    rp({
        method: "POST",
        uri: "https://mymetabase.com/api/dataset",
        headers: {
            "Cookie": "metabase.SESSION_ID=XXXXXXX"
        },
        body: {
            "database":1,
            "type":"query",
            "query":{  "source_table":1,  "aggregation":["count"], "breakout": [["datetime_field",28,"as","month"]], "filter":[]
            }
        },
        json: true
    }).then((res) => {
        response.end(JSON.stringify(res.data.rows));
    }).catch((err) => {
        response.end("Oh uh, something went wrong: " + err);
    });
}
```

You could make this generic by taking in a card id as a parameter, making a request to `/api/card/CARD_ID`, then say, checking that the card name has "[public]" in it or something (obviously a hack), then doing the dataset query if it does.

**Comment by Leen15** [comment]
is it possible to pass in body the card ID instead of the query?
if i change the query in the card i've also to change the query in the request, it has no sense.

Is possible to use an API token instead of a cookie session?

**Comment by camsaul** [comment]
You can pass in the session token as an HTTP header instead. `X-METABASE-SESSION`

**Comment by salsakran** [comment]
Also, (for posterity), I think this should be cached however we will end up caching things in #1666 
Specific card level permissions should be considered in #1175 + #2682 

All-in-all, I think this could be a relatively tightly scoped feature with minimal UX work required other than adding a global setting somewhere in the admin.

**Comment by tlrobinson** [comment]
@Leen15 Here's a version that lets you specify a card ID, and requires the card title contain `[public]`:

Note that the session key will unfortunately expire after 2 weeks. See #2699

```
const rp = require("request-promise");
const url = require("url");

const BASE_URL = "https://mymetabase.com";
const SESSION_ID = "XXXXXXXXX";

function mb(path, options = {}) {
    return rp({
        ...options,
        uri: BASE_URL + path,
        headers: {
            ...options.headers,
            "Cookie": "metabase.SESSION_ID=" + SESSION_ID
        },
        json: true
    });
}

exports.tonicEndpoint = async function(request, response) {
    const cardId = url.parse(request.url, true).query.card;
    try {
        let card = await mb("/api/card/" + cardId);
        if (card.name.toLowerCase().indexOf("[public]") < 0) {
            throw new Error("not authorized");
        }
        let dataset = await mb("/api/dataset", {
            method: "POST",
            body: card.dataset_query
        });
        response.end(JSON.stringify(dataset.data.rows));
    } catch (err) {
        response.end("Oh uh, something went wrong: " + err);
    }
}
```

**Comment by Leen15** [comment]
I tried to call /api/session for have a new session ID for every request.
if i made more than one request within 10-30 seconds it return 400 Bad Request, is it normal?

**Comment by camsaul** [comment]
yes that's a security feature the session endpoint is rate-limited

**Comment by Leen15** [comment]
I just wrote a simple php script (need some work, but it works) for expose metabase datasets based on a label "IS_PUBLIC".

[https://gist.github.com/Leen15/5b0556e0c68c9543939ccbbd8af01560](https://gist.github.com/Leen15/5b0556e0c68c9543939ccbbd8af01560)

maybe could be useful for someone.

**Comment by agilliland** [comment]
My belief on this issue is that the best thing to do is setup a part of the app which provides obfuscated urls for the few things that tend to be embedded, shared, or downloaded outside of the main app (Dashboards, Cards, Query Results) and then simply provide a mechanism for users to get those urls when they want them.

So urls like this might exist ...
```
https://my.metabase/ext/card/5b0556e0c68c9543939ccbbd8af015609/
https://my.metabase/ext/card/f3197ad81ac143c6990896d30ca156a9/result/csv
https://my.metabase/ext/dash/c6137c466d664bccb9746cbbbfdacfcf/
```

I would expect that for any of these urls the output would be an embeddable static rendering of the contents.  So for a card it would be just the visualization.  For a dashboard it would be the full layout of the dash with its various visualizations.  And for card results they can be just the data in standard formats like CSV, JSON, etc.

From a security perspective these urls wouldn't be protected other than through the obfuscation of the long hash that is used in the url.  Not ideal, but I'm not sure there is another way really.  And of course there can be an app level setting which controls whether or not these urls are made available, so if the owner of the app doesn't need to use them they can be disabled.

**Comment by tlrobinson** [comment]
I think that approach is fine, though it feels a little dangerous to expose every card/dashboard, even if the URL is long and random. I'd propose one or both of these extensions:

1. A global admin setting to enable this feature
2. A boolean flag on each card/dashboard that would be enabled when you click the share widget to get the link (similar to Google Docs share panel, but the only option is "Anyone with the link")

By "static" do you mean an image, a pre-rendered HTML page, or a subset of React components with the data inlined in the page? Would tooltips, etc work?

**Comment by agilliland** [comment]
Yeah, I agree that exposing all entities could be overkill (and certainly less secure), so it could certainly be the kind of thing that is done on a per item basis so that only the things that users want to share are exposed.  I like the idea of a "shared" toggle that exists on the Card/Dashboard.

By "static" I mainly meant that it shouldn't require loading our full JS based single page app in order to work, so something more lightweight than that.  So most likely the response should be just a single HTML page and I think that ideally these pages wouldn't require any XHR calls, so everything needed would be returned in one shot.  Dashboard rendering could be tricky in that regard, so we'd have to look into that one.

Ideally the architecture would allow for a bit of flexibility in the rendering so that different needs could be satisfied.  I like the idea of supporting a simple image rendering in addition to an HTML rendering.  The idea of using a pre-rendered HTML page is also a neat possibility, but I was thinking of just rendering the subset of React components needed to start with.

**Comment by salsakran** [comment]
Hey @Leen15, mind filling out a survey we're doing regarding how folks want to embed Metabase  - https://docs.google.com/a/metabase.com/forms/d/11eZ5mwDy8IZaLZYlOUMyjCLXzJXKsGLaI1_xzi8TFD8/viewform

**Comment by Leen15** [comment]
@salsakran done, thanks for your work!

**Comment by mazameli** [comment]
@salsakran, couple small questions:
1. You mention a global setting a few times: are you talking about the need to have a setting in the admin to turn on link sharing _at all_, or just to toggle globally between making shared links publicly viewable vs. only to authenticated users?
2. Do we need the ability for users to choose what the link is going to display? I.e. JSON, .csv, HTML, etc.
3. Do we want the ability to "delete" a link? I'm assuming yes.
4. Does the user need to click a button to create the link, or does it get generated automatically when the question is saved?

**Comment by salsakran** [comment]
In my mind there are two separate things going on:

A) the ability to mark some cards or dashboards as public
B) the ability of users to fetch the underlying data of a card as JSON, CSV, etc

I think there should be a global setting for A. Many installations will chose to not allow any un-authenticated access. Once an admin has allowed any data to escape the building, individual dashboards/cards should have a "public" (or similar) toggle that provides a non-guessable url that displays the card or dashboard without unnecessary chrome.

For B), I think there should be the orthogonal capability to get JSON or CSV of the underlying data of a given card. If "public" is not on, then you need to be logged in and auth'd. If it's also public, then @Leen15's usecase is fully met.

**Comment by mazameli** [comment]
Cool, so I'm thinking we'd need:

- A new setting in the General settings section of the Admin Panel that's titled something like, "PUBLIC LINK SHARING" with an on/off toggle defaulted to Off, with a description paragraph: "Turn this on to allow your users to create links to individual questions and dashboards that don't require authentication to view."

- Add a popout menu to the current download button (and maybe change the download button icon to a share icon), with a default state like this:
![1-no-link](https://cloud.githubusercontent.com/assets/2223916/19668554/74bac01c-9a0d-11e6-9cd5-6ee043391a6f.png)

If the setting in the admin panel is turned off, then of course the "Shareable Link" section should not be displayed at all.

- Once the link is created, the popover should look like this:
![2-link](https://cloud.githubusercontent.com/assets/2223916/19668569/900cfeca-9a0d-11e6-8f27-05dbb89b1b3d.png)

When a public link is clicked on, my presumption is they'd see a view of the saved question or dashboard that doesn't have the main Metabase navigation (or maybe has the branding, but none of the links?), the query builder, or other actions, with the exception of things like sorting if the saved question is a table. Should they be able to use dashboard filters (I'd say yes)? Change the chart visualization (I'd say no)?

Thoughts?

**Comment by tlrobinson** [comment]
👍 

I don't think we want to allow changing the sort order since that would modify the query itself, which the user may not want to allow (e.x. "top 10 salespeople" could become "10 worst salespeople"). We could do client-side sorting but that's a non-trivial change.

Bonus points if the sharable link supports `.json` and `.csv` extensions to get the raw data.

**Comment by salsakran** [comment]
yeah, in the example above, I'd like to be able to do
https://metabase.acme.com/a9uav02/json or https://metabase.acme.com/a9uav02.json for the raw data. 

Re: sorting, I don't think any operations that can change the underlying query should be allowed for cards, with the exception of dashboard filters should work.

**Comment by mazameli** [comment]
Yeah, I get the sorting thing. It would just be hard to explain to laypeople why you could use dashboard filters, but you couldn't reorder a list of users by last name Z --> A instead of A --> Z. Not the end of the world, especially if they can then download the csv if they need to move things around.

**Comment by mazameli** [comment]
Here's some updated thinking.

Let's keep the downloading actions separate from the sharing actions. If the global setting to allow public links is turned on, then a new sharing icon will appear next to the download icon. (Open question: should all users be able to use the link sharing, or only admins? My bias is all users.)

Here's the icon plus tooltip:
![tooltip](https://cloud.githubusercontent.com/assets/2223916/19708388/14c9ef68-9ad3-11e6-86e3-84281740a368.png)

Clicking on the button shows this state if no link has been created. I think it's okay for this to be a two-click process, just to make sure the user's intending on creating the link.
![no link](https://cloud.githubusercontent.com/assets/2223916/19708812/38b9b48c-9ad6-11e6-9839-0908d291e18c.png)

When the user clicks `create public link`, then they'll see this:
![links](https://cloud.githubusercontent.com/assets/2223916/19708451/771fc1ec-9ad3-11e6-97f4-bbd67bfb5606.png)

If they click `copy link`, we could show a confirmation like this, which would fade out after a second or two:
![copied](https://cloud.githubusercontent.com/assets/2223916/19708457/8ce98b20-9ad3-11e6-89a7-26408c4d63d1.png)

If they click `disable links`, they'll be asked to confirm:
![disable links](https://cloud.githubusercontent.com/assets/2223916/19708787/0adf850a-9ad6-11e6-8690-106b0c3c0520.png)

A public question link should look something like this:
![public-question-link](https://cloud.githubusercontent.com/assets/2223916/19708767/e79c18ce-9ad5-11e6-9967-796a0dd2ee99.png)

A public dashboard link should look something like this:
![public-dashboard-link](https://cloud.githubusercontent.com/assets/2223916/19708771/eff5df6e-9ad5-11e6-9343-1c9b69738804.png)

Would love feedback on any of this!

**Comment by salsakran** [comment]
broke this out into 3 separate tickets  #3680, #3681 and #3682

**Comment by moumny** [comment]
Wow looks really nice :) ! 
Ideally it would be possible give to only select users the right to share a dashboard.
I find that the Metabase logo looks like the title of the dashboard or the question. 
In any case im quite excited about this !

**Comment by Sarrae1406** [comment]
Hello All, 
I am confused and want to know if there is any way I can have a sharable link from the Metabase Dashboards or widgets individually ?

**Comment by camsaul** [comment]
The conversation here is a little unwieldy with the unrelated discussion of using the REST API. Since @salsakran already broke this out into 3 separate issues I'm going to go ahead and close this in favor of the new ones.

I'll move the relevant things like designs over to the respective issues

**Comment by krismp** [comment]
@mazameli awesome, when it will be available?
