### ISSUE TITLE
Can't see materialized views in Data list (Postgres)

### ISSUE THREAD

**Issue by deegros** [metabase/metabase#2684]
Hello. Looks like I can't see materialized views in Data list. I see tables and views only. My DB is Postgres. http://screencast.com/t/6EJz9HuAXZYB

SQL Query to materialized view works well – http://screencast.com/t/Dvcda7EyNu

If this is a bug report, please fill in the blanks:

*  I am using the Mac app.
*  My computer's OS is Mac OS.
*  I'm running Metabase with Mac App. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is PostgreSQL.
*  My Metabase version is 0.17.1.0.

**Comment by tlrobinson** [comment]
@deegros It's certainly possible this isn't working, but just to check, if you recently added the materialized view did you manually sync the database in the admin page after doing so?

**Comment by deegros** [comment]
@tlrobinson thanks for the answer. this materialized views was added a long time ago. i have tried to manually sync the database in the admin page, but it was not helpful.

**Comment by camsaul** [comment]
Materialized views (issue #2355) haven't been shipped yet. Support for them was added a few weeks ago and will be part of the upcoming 0.18.0 release.

Closing as duplicate.
