### ISSUE TITLE
`assert-test-is-not-parallel` does not work inside fixtures

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#26843]
We have logic to make sure you don't do things like `with-redefs` inside `^:parallel` tests. We do this by swapping out `clojure.core/test-var` with a version that binds a `*parallel?` dynamic var, and that's what `assert-test-is-not-parallel` checks. However, this doesn't affect `:each` fixtures, since the each fixture logic happens before `test-var` ever gets called...

I think we need to intercept `clojure.test/test-vars` as well and maybe wrap the `:each` fixtures to bind `*parallel?*` to get it to work properly... I tried this but it's a little tricky because the `:each` fixtures don't get passed the vars themselves, but get passed the test function (`:test` metadata on the var). Figuring out how to do this will be a little tricky, but ultimately doable I think

**Comment by bshepherdson** [comment]
Perhaps we can check this in both directions - keep the `test-var` logic we have, plus cause parallel-unsafe things like `with-redefs` to set another dynamic var that gets checked on the way in to a `test-var`. Then if a fixture has already done something unsafe, but we're starting a parallel test, we can assert.

**Comment by camsaul** [comment]
Since this is a problem with Hawk and not with MB now that we moved this stuff into Hawk I've opened https://github.com/metabase/hawk/issues/26 to track this instead
