### ISSUE TITLE
 Migration Failed

### ISSUE THREAD

**Issue by fanspace** [metabase/metabase#26852]
**Describe the bug**

Migration Failed

**Logs**
ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::1::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=931072) Table 'core_organization' already exists [Failed SQL: CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`)) ENGINE InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci]

version:  metabase/metabase:latest

describe:  deploy in k8s cluster,  via proxysql to connection mysql8 mgr

i resolved it by setup it on standlone mysql server,  and output/import the database's sql.  but i think it's a not good solution.

**Comment by paoliniluis** [comment]
Hi @fanspace, you're not including diagnostic info, what you were doing when this error happened, etc. I'll proceed to close the issue. Thanks
