### ISSUE TITLE
"Exclude" field filter on Native Query breaks if you select a value to exclude

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#26861]
**Describe the bug**

 The “Exclude” time filter in SQL Native queries doesn't seem to work. It only works when the whole selection is present, the moment you deselect any granularity it breaks

**To Reproduce**

1. Go to New SQL Query and write a query with a date field filter

```
Select * 
from orders
Where {{date}}
```

2. Setup the variable as a Field Filter (Date Filter) on Created At:

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/110378427/205079623-9ebbcfae-61aa-454d-97eb-54c4e4643ff8.png">

5. Click on the filter widget > click "Excludes..." >  De-select any granularity

<img width="521" alt="image" src="https://user-images.githubusercontent.com/110378427/205080368-7f380a37-bdec-4b4e-9e3d-45f0c0716dc2.png">

6. See error

`Don't know how to parse date param 'exclude-days-Mon-Tue-Wed-Thu-Fri-Sat-Sun' — invalid format`

**Expected behavior**
Query excludes my selected options

**Information about your Metabase Installation:**

- Metabase version: 44.6 

**Additional context**
Could be related to https://github.com/metabase/metabase/issues/24236 since it doesn't replicate on the GUI Editor only on Native SQL

**Comment by nemanjaglumac** [comment]
If it helps, this is where we throw this error in backend:
https://github.com/metabase/metabase/blob/master/src/metabase/driver/common/parameters/dates.clj#L397

**Comment by uladzimirdev** [comment]
Accordingly with [discussion in slack](https://metaboat.slack.com/archives/CKZEMT1MJ/p1680822159544859?thread_ts=1680790366.133929&cid=CKZEMT1MJ) this bug seems to be backend only and we have nothing to do on frontend with it.

0.44.2 (and seems older versions as well) are affected

**Comment by calherries** [comment]
Based on the code it looks like exclude filters never worked with native query parameters.

**Comment by calherries** [comment]
The same error happens if a native query is added to a dashboard. The stacktrace in the response to POST `/api/dashboard/1/dashcard/:id/card/:id/query` contains the same error: 
`Don't know how to parse date param 'exclude-days-Mon-Tue-Wed-Thu-Fri-Sat-Sun' — invalid format`

And the dashcard will display an error:
<img width="736" alt="image" src="https://github.com/metabase/metabase/assets/39073188/a39e38cc-e34a-4b95-9a08-5218df05d39b">
