### ISSUE TITLE
Foreign key mapping between models

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#26866]
# Context
Product doc: [Foreign key mapping between models](https://www.notion.so/metabase/Foreign-key-mapping-between-models-1764637ef82c478db9c09a6a11a07140)

# Requirements
- Users should have the option to assigning other models as PK/FK relationship in the model metadata settings.

**Comment by camsaul** [comment]
In terms of sequencing this should be done after we come up with a technical design for this and #26862

**Comment by paoliniluis** [comment]
please @cdeweyx 🙏🏻
