### ISSUE TITLE
Add a GET and PUT endpoints to edit single group permissions

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#26872]
# Context
Product doc: [Improve permissions API](https://www.notion.so/metabase/Improve-permissions-API-d02f4d357b844c9a9ddaa6646b29496e)
Today, we support only get and put the entire permission graph (for all groups). When users are configuring permissions through the API, they frequently want to edit a single group. Adding an endpoint to configure a single group will make it easier for them and also reduce the payload.

# Requirements
- Add a GET endpoint to retrieve the permission graph of a single group.
- Add a PUT endpoint to edit the permission graph of a single group.
  - We need to define what to do with the `revision_number`. We don't need to support parallel edits at this point.

**Comment by noahmoss** [comment]
Quick thoughts
* Rather than exposing a new PUT API, we can just make the existing one accept partial graphs and update the frontend to send partial graphs. This already sort of works by accident but isn't officially supported or tested so that would be the main lift.
* Should we formalize API support in some way?

**Comment by camsaul** [comment]
Until we commit to officially supporting our API for uses like this I don't think it makes sense to start writing little endpoints like this that we aren't using ourselves. We're currently pretty explicit about the REST API being "use at your own risk" and "subject to change between versions", and having the flexibility to change things is a key factor in helping us ship new features quickly. Our policy has always been not to devote our limited engineering resources to having an official API until we put a "v1" on it
