### ISSUE TITLE
Make block permissions additive

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#26882]
# Context
Product doc: [Make block permission additive](https://www.notion.so/metabase/Make-block-permission-additive-676ff75e6e704a62a2cda962ffd0cca8)
This project interacts with [Split data access and query builder access](https://www.notion.so/metabase/Split-data-access-and-query-builder-access-f18185f2c2954127bdfcb2864ef5c13f)

# Requirements
- If a user has `Blocked` data access on one group and `Sandboxed` or `Unrestricted` in any other group, the more permissive permission prevails.
- If a user has `Unrestricted` in any other group and `View` collection access, they should be able to view native query results.

#21695

**Comment by noahmoss** [comment]
This will essentially happen as a side effect of the permissions refactor in #26918, so it can be considered part of that project.
