### ISSUE TITLE
Release script should check that the current Git commit exists on the branch upstream

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#26910]
We had an issue where 0.45.0-RC2 was built from a local `release-x.45.x` branch that was branched from `master`. So despite the name being the same, it was not the same branch as the upstream `release-x.45.x` branch in GitHub.

The release script should detect this situation and warn or error about it to prevent it from happening in the future.

I don't think we want to just do something like `git pull` or `git pull --force`, because it's totally valid to be building the release from what is not the newest commit upstream. Example: suppose we are cutting an RC. We start by building the OSS version of the release; at some point in the build and release process, somebody merges a backport PR into the release branch. When we build the EE version of the release, if we did `git pull`, it would be on a different commit than the same OSS version of the RC. This is going to be a big bug triage headache. We want both releases to be on the same commit; so let's continue to let people do `git pull` manually when they deem it to be appropriate.

We can however make sure that the current commit we're building from is actually present at some point in the upstream branch history.

**Comment by shravan20** [comment]
Can i pick this up?

**Comment by nemanjaglumac** [comment]
I think this should be closed because @iethree 's release automation handles it now.
Reopen if I'm mistaken.
