### ISSUE TITLE
If the indicator field of the visual configuration is deleted, the format of other indicators is incorrect

### ISSUE THREAD

**Issue by bigicy** [metabase/metabase#26914]
My indicator is configured with many names, such as sum, sum_2, sum_3, sum_4... When I delete one of the middle ones, such as sum_2, sum_3 and sum_4, the format of the indicator fields will be messed up, and the format of the indicator fields in the visual configuration will be messed up

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
