### ISSUE TITLE
Pie chart does not display does not allow custom configuration of the display of values (compact values)

### ISSUE THREAD

**Issue by dionesvfreitas** [metabase/metabase#26916]
**Is your feature request related to a problem? Please describe.**
When the chart is embedded together with others in a dashboard and has very large values, the visualization is impaired because the value of the series is below the chart.

**Describe the solution you'd like**
I think that if there was the possibility of configuring the display of the series value between automatic, compact and full (as some allow) or the font automatically reduced the visualization it would not be so bad

**Describe alternatives you've considered**
I increased the embedded chart card size, but that wasn't an elegant solution.

**How important is this feature to you?**
I consider it important because the visualization of information in an elegant way brings value to the use of the solution.

**Additional context**
This is a print of how it is now.
![image](https://user-images.githubusercontent.com/7488405/205300856-9803650e-e630-42b4-a568-dfe91b3fb9d4.png)

It could be displayed as 16.6M or the font automatically adjusted by reducing its size. But I think shrinking the font might not be the best solution.

**Comment by EmmadUsmani** [comment]
Confirmed with @cdeweyx on [slack](https://metaboat.slack.com/archives/C064QMXEV9N/p1720464983705209?thread_ts=1720464556.131809&cid=C064QMXEV9N) that this is a feature request instead of a bug.
