### ISSUE TITLE
Metabot : Card (Query) Parameters

### ISSUE THREAD

**Issue by FinnBorge** [metabase/metabase#2692]
I love Metabase!  Would it be possible to allow the metabase slackbot to accept parameters?  e.g. metabot show 10:Q1 (for card 10 with the Q1 parameter).  Would require the explicit definition of syntax and the acceptable parameters.

https://github.com/metabase/metabase/issues/1543 is similar, but since this is specifically for the metabase slack integration I figured it should be a separate issue!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
@FinnBorge bit of a blast from the past, but what kinds of questions are you using with this? SQL or GUI? Also, how would you expect validation to work in this situation?

**Comment by FinnBorge** [comment]
Hi Sameer, 

I intended for this to flexibly be for either.  You'd draft a question with a parameter placeholder.  e.g. `select * from users where user_id = {param(:id, int(11))}`, set a default value for the param and the expected char type.  The actual GUI could utilize drop-down selectors.

Does that make sense?  Would be glad to discuss further.  Wish I knew enough Clojure to contribute :)

**Comment by salsakran** [comment]
we already have parameters for sql - 
http://www.metabase.com/docs/v0.19.3/users-guide/12-sql-parameters.html
with gui cards, it's a bit more work to figure out what to parameterize and how.

Are you currently using metabot in real life or is this primarily an item on a wishlist?

**Comment by FinnBorge** [comment]
Excellent, I wasn't aware of that when I first pitched the use of Metabase back in June.  Definitely interested in this via the gui, but especially via the metabase slackbot.  We can easily write the param responsive SQL query, but calling it from a slack conversation would be very empowering.  The desire would be to expose specific queries to the whole team while limiting access to the full app.

I have been setting some team-members up on Metabase sporadically across the last few months.  We're still figuring out how much (and what kinds) information we wish to make accessible.

**Comment by Kelindar** [comment]
Is this still planned? We have a very large number of Slack users & channels (10K+) in our organisation and having the ability to ask parametrised questions using MetaBot for CE & OnCall.

**Comment by yanivgold** [comment]
This is indeed something that we would love to see metabase support. We have a very large amount of people using it, and the demand for having params as part of metabot keeps coming back, any plans for this?
@salsakran

**Comment by amit777** [comment]
something like
metabot show 5 email=foo@example.com,startdate=2010-01-10

This would run question 5  with email and startdate parameters passed to the question template.

**Comment by Alexkane** [comment]
Being able to add parameters to metabot questions would be extremely useful for us as well

**Comment by Stephenjhayes** [comment]
Same would be great as most of our dashboard and questions use filters. Great work on this tool guys.

**Comment by mobula9** [comment]
+1

**Comment by flamber** [comment]
Closing as MetaBot is deprecated as of v0.42 #19435
