### ISSUE TITLE
Editing a model's metadata bricks the question when mapping to an underlying DB column that has an enum mapping

### ISSUE THREAD

**Issue by apinstein** [metabase/metabase#26935]
**Describe the bug**
I have a postgres db table with an INT column `fee_unit`, which is an ENUM.
In the Data Model admin, I've decorated that column as an ENUM and added mappings.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/34889/205384983-187c8e2f-2641-4d57-baa2-c84bf738deca.png">

If I then build a native query which selects `fee_unit`, and then edit the metadata in `fee_unit` to map to the "database column this maps to", and save it:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/34889/205386068-4fb01724-f81f-48e4-97b6-e9434e9648aa.png">

...the query UX goes blank and the question is no longer editable. The model itself can be reloaded to see the RESULT, but if you edit the query or the metadata the UX goes blank.

**Logs**
JS console logs include 3 errors that show up depending on if you "Edit Query" or "Edit Metadata":

<img width="823" alt="image" src="https://user-images.githubusercontent.com/34889/205385601-0f1ca777-9140-4be9-b936-08e85209da49.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/34889/205385634-b82d3494-6a37-4a5c-b533-59969b36524e.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/34889/205385666-0b95de8a-953f-4e06-abfd-5a6928803fe5.png">

**To Reproduce**
See above...

**Expected behavior**
The underlying data field setup (the mapped enums) should work properly, and the model should be editable.

**Screenshots**

**Information about your Metabase Installation:**

> You're running Metabase 0.44.6 which is the latest and greatest!

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "5.4.202+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.24"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-11-01",
      "tag": "v0.44.6",
      "branch": "release-x.44.x",
      "hash": "5c6ae21"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

It blocks the ability to use this feature, but I can avoid using this feature to prevent it from breaking metabase. That said, it's a really cool feature :) 

**Additional context**

**Comment by flamber** [comment]
Very related to #23449. I can reproduce on 44.6, but not on 0.45.0-rc3. Closing as fixed.
