### ISSUE TITLE
Pulse cannot be sent to Private Channel

### ISSUE THREAD

**Issue by FinnBorge** [metabase/metabase#2694]
Seems as though a pulse cannot be sent to a private channel despite the presence of Metabot in that channel.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by tlrobinson** [comment]
I'm guessing this is because we're using what Slack now calls ["test tokens"](https://api.slack.com/docs/oauth-test-tokens), which I believe have the same level of authorization as whichever user created the token. If that user happens to be in the private channel it *might* work, but obviously that's not good enough.

**Comment by FinnBorge** [comment]
Cannot send to private channel despite being a member of it.  Thank you for your attention!

**Comment by anthonylau** [comment]
Private channel not shown on the list even invited the bot.

**Comment by wagnerads** [comment]
I have the same problem. I tested my token in other applications and works normally, it may be a problem in the list of channels.

**Comment by wagnerads** [comment]
The slack list private groups at another end point. https://api.slack.com/methods/groups.list
I created a pull request with correction.

**Comment by federicokeen** [comment]
Any chance to include this fix in next release?

**Comment by ArtursO** [comment]
This would be pretty awesome
+1

**Comment by ulucaydin** [comment]
+1

**Comment by MiBaDK** [comment]
This keeps us from using the feature. To send financial updates to the management we need to be able to send to private channels. The "temp" folder as well needs to be private.

**Comment by scova0731** [comment]
+1

**Comment by michaelkuty** [comment]
+1

**Comment by fedorocko** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by rabichan** [comment]
+1

**Comment by sandboxws** [comment]
+1

**Comment by omegasoft7** [comment]
+1

**Comment by petar777** [comment]
Any results? Has that been updated or something?

**Comment by ansidev** [comment]
I need this feature.

**Comment by raymondhuang1200** [comment]
Need to feature +1

**Comment by smithcoin** [comment]
+1

**Comment by mohit091** [comment]
Is this issue resolved need to send the metabase pulses to private slack channels

**Comment by futurekill** [comment]
We need this too. It'd be great to be able to use Metabase with slack but until we can send the pulses to private channels it's a no go...

**Comment by andrewkslv** [comment]
There is an API method in Slack which returns all channel like conversations plus privet. Probably it could be helpful. https://api.slack.com/methods/conversations.list

**Comment by todddickerson** [comment]
👍 Also need this, prevents this from being very useful in a large org with private data

**Comment by sean-lawfully** [comment]
Any chance this can be implemented soon? My execs are asking for it and I might need to use another BI tool just because of this one feature.

**Comment by NicoBerthoz** [comment]
Temporary solution: I send it to a public channel and make a zap with Zapier to send it back to the right channels. Not really convenient if anyone joins this public channel...

**Comment by Dave0404** [comment]
Hi all, I'm assuming this is not a supported change but I've had luck posting to a private channel by going into the metabase database table pulse_channel and updating the field "details" to point to the private channel. Once catch is that when you setup the Pulse you have to select a public channel to save it and then update after the fact. I've also found that anytime you make changes to this pulse and hit save it will point back to the originally selected slack channel.

**Comment by rsoaress** [comment]
@Dave0404 how can I find the "metabase database table pulse_channel" ?

**Comment by flamber** [comment]
@rsoaress You would need to migrate from H2 to Postgres or MariaDB/MySQL:
https://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

**Comment by uptownnickbrown** [comment]
Redirecting this question from Gitter:

Does anyone know if there has been any work done towards the ability to post to a private Slack channel per this ticket?

From a little digging in the codebase and the Slack API docs, it looks like moving from gathering users and channels separately with Slack's `users.list` and `channels.list` calls (per https://github.com/metabase/metabase/blob/master/src/metabase/integrations/slack.clj#L55-L61) to their new `conversations.list` endpoint would get the job done - `conversations.list` includes user IM's, public channels and private channels all in one response.

Metabot already does a fine job posting to a private channel if you do something like `metabot show blah` in the channel - so I don't think we have a blocker on pushing data to a private channel, it just isn't putting them in the dropdown list when creating a pulse.

Worth noting `channels.list` is deprecated per https://api.slack.com/methods/channels.list which might add some urgency to a fix here:

> Don't use this method. Use conversations.list instead.
> 
> This legacy method returns a list of all channels in the team. This includes channels the caller is in, channels they are not currently in, and archived channels but does not include private channels. The number of (non-deactivated) members in each channel is also returned.
> 
> To retrieve a list of private channels, use conversations.list.

**Comment by uptownnickbrown** [comment]
Following up - I received this in an email from Slack today (**Slack API changelog: February 2019**):

> Another gentle reminder about the Conversations API
> We are deprecating all `channels.*`, `groups.*`, `im.*`, and `mpim.*` Web API methods in favor of their Conversations API replacements. Migrate to `conversations.*` as soon as possible, as these deprecated methods will retire on November 25, 2020. Read more [here](https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api).

I'd maybe take this on but haven't written a line of Clojure in my life 😉. If anyone more familiar with the project has bandwidth to look at the migration, it would likely be a quick win - add private channel support and get out in front of a hard API deprecation later this year. I'd be happy to volunteer test/QA time...

**Comment by orlando** [comment]
> Hi all, I'm assuming this is not a supported change but I've had luck posting to a private channel by going into the metabase database table pulse_channel and updating the field "details" to point to the private channel. Once catch is that when you setup the Pulse you have to select a public channel to save it and then update after the fact. I've also found that anytime you make changes to this pulse and hit save it will point back to the originally selected slack channel.

@Dave0404 suggestion works, you have to:

1. Create the pulse and select your username for now (this is for testing)
1. Add metabot user to the private channel you want to use for notifications
1. In the metabase database, go to the table `pulse_channel` and modify the column `details` for the record you to the private channel (ex. `{"channel":"#membership-notifications"}`)
1. Reload the pulse and click on "Send to Slack now", you should receive a message from metabot on the private Slack channel.

**Comment by uhrohraggy** [comment]
For what it's worth, https://github.com/metabase/metabase/issues/2694#issuecomment-653202849 's suggestion is working when the creator has permissions, so it seems more of the ability of the API to load the list of private channels for selection. Could a possible workaround be to allow free-form typing, like a typeahead that populates the list of channels/DMs, but you can add your own value if it's not found?
