### ISSUE TITLE
Customize scalar title (separate from question name)

### ISSUE THREAD

**Issue by snapeuh** [metabase/metabase#2695]
Hello,

We started using Metabase today at work and we love it so far. 

However we quickly ran into an UX issue. For example I was trying to get the list of our domains that will expire this month and the title of my question was : "How many domains will expire this month?". Great so far. But Metabase displayed that question title under the count when added to a dashboard and I couldn't find a way to personalize the text to something else so I updated my question title with "Domains expiring this month".

It could be OK for that specific case but would be a nightmare as soon as we'll get "xxx to process" with many questions that would be named "To process" (and we already have some).

For now we are using labels to filter similar questions but this is not a durable solution.

Do you plan to add a feature to personalize the text that will be used on the dashboard for a question?

Thanks,

Keep up the good work,

Romain.

**Comment by bobey** [comment]
Would love to see a way to customize labels included in one of the next releases.

By the way, thanks for this yet awesome tool!

**Comment by salsakran** [comment]
@mazameli  does this fit into your worldview re: the new viz settings?

**Comment by mazameli** [comment]
I feel a little obtuse, but I'm not totally sure I get the use case. You're wanting a different label underneath the number than the title of the question? And many of your questions have the same name?

**Comment by flamber** [comment]
Closing this, since there has been the option to change title of cards on the dashboard for a long time.
Go to the dashboard, hover the card/question and click the gear-icon (:gear:)
![image](https://user-images.githubusercontent.com/1447303/75097552-49da4a80-55ac-11ea-9ce5-c5097139b4c5.png)
