### ISSUE TITLE
[Epic] Migrate formatting to cljs

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#26961]
- [x] #27180
- [x] #27181

**Comment by nemanjaglumac** [comment]
Just a reminder that we have another formatNumber utility in the static-viz code:
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/static-viz/lib/numbers.ts

and another set of unit tests related to it:
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/static-viz/lib/numbers.unit.spec.js

**Comment by bshepherdson** [comment]
First glance at the notes from `format_date`:
- On locales: both platforms have a sense of default locale; it still makes sense to pass it as a parameter ~everywhere and fill in the parameter at the outer surface if it's not given.
- "Would it be okay to pass a date as a timestamp (= number)?" OK in what sense? Clojure integers are `long`s, so they can hold (milli)second timestamps safely, as can JS doubles. Did you mean something else?

**Comment by bshepherdson** [comment]
I'm closing this initial epic, since number and date formatting are ported.

Porting more of metabase-lib will follow in a separate epic.
