### ISSUE TITLE
Counters on last data point of line graphs

### ISSUE THREAD

**Issue by rNianios** [metabase/metabase#2696]
Is there any plans to always show the chart counter without the need to hover over the chart? 
Below it's a bad representation.

Having these charts showing on a TV 50+ inch it's not easy/convenient to login to the computer every few minutes to look at the counter.

From:
![chart1](https://cloud.githubusercontent.com/assets/1166321/15752863/fcc083f8-28e7-11e6-886e-f22331472275.png)

To:
![chart2](https://cloud.githubusercontent.com/assets/1166321/15752868/ff7d1b10-28e7-11e6-986b-53438f0381f3.png)

**Comment by mariosergioti** [comment]
rNianios as a workaround to add this feature, you can put two type Number objects informing the dimensions with legend title of this chart

**Comment by flamber** [comment]
Data values was added in 0.34.0, but only for single series. There's a request for multi series.
Even though this is the OG, I'm closing it as duplicate of #11585, since this has fewer upvotes.
