### ISSUE TITLE
Upgrade Metabase Athena Driver to 2.0.34

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#26975]
Athena recently (2022-11-24) released a new version of the driver (2.0.34) that addresses two open issues in my old repo.

- https://github.com/dacort/metabase-athena-driver/issues/106
- https://github.com/dacort/metabase-athena-driver/issues/118

Full release notes are [here](https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.34.1000/docs/release-notes.txt).

**Comment by takuyawww** [comment]
@dacort 

Nice to meet you, dacort

Thank you for all the great contributions to making metabase and athena work together, including the metabase-athena-driver.

I would like to integrate metabase and athena in a project I am currently involved in.

Any chance of announcing a release version that supports athena query result reuse in the near future?

**Comment by dacort** [comment]
@takuyawww Thank you, much appreciated. :) 

I would subscribe to this issue for updates. The Metabase team is working on some follow-on functionality for the Athena driver (as seen in #27012 ) and the updated driver is part of that. Once the driver is updated, you should be able to enable query result reuse by adding some parameters to your Athena connection. _However_ note that Metabase sends the user ID as part of the Athena query, so results will only be reused for queries by the same Metabase user.

**Comment by camsaul** [comment]
As part of this we should probably move the S3 bucket as @dpsutton suggested and strip out the `log4j2.properties` file from the JAR e.g.

```
zip -d athena-jdbc-2.0.33.jar log4j2.properties
```
