### ISSUE TITLE
New Subscriptions and Alerts permissions: send only to same group members

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#27000]
Product doc: [New Subscriptions and Alerts permissions: send only to same group members](https://www.notion.so/metabase/New-Subscriptions-and-Alerts-permissions-send-only-to-same-group-members-7bd5fe0dfea54a87a914c3d71b59a414)

**Comment by paoliniluis** [comment]
Duplicate of https://github.com/metabase/metabase/issues/10795

**Comment by luizarakaki** [comment]
Closing this in favor of #10795
