### ISSUE TITLE
Style changes in signed embeddings don't apply till unpublish->publish

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#27029]
**Describe the bug**
When changing the style settings for the embeddings, they won't get applied till you unpublish and then publish again the changes as those changes don't trigger the appearance of the "publish" button as it does when changing a parameter.

**To Reproduce**
1) set up metabase, enable embedding
2) create a question (new->question->people->visualize). Save the question with any name
3) go to sharing and choose the last option (embed in your application)
4) publish the chart first, then change the styling (e.g. unselect the border). You won't get the button to publish the change, so you need to unpublish, change the setting and then click again on publish

**Expected behavior**
Any selector change should pop the "publish" button, in the same way as it's with the filters

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Metabase version: 1.45.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 15.1

**Severity**
Cosmetic, ergonomics

**Additional context**
NA

**Comment by flamber** [comment]
It does not change the embedding, it's anchor parameters, so they are never stored anywhere.

**Comment by albertoperdomo** [comment]
@flamber is correct. The changes are previsualized in the preview but need to be appended as query params to the embed URL, e.g. `?bordered=false`. They are not persisted in any way. I think the UI is confusing and we are addressing this soon.

Closing.
