### ISSUE TITLE
unable to manually reset the password of the "setup user" in the admin panel

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2702]
Tested on latest dev snapshot (0.18.0) and 0.17.1 on Heroku.
This doesn't appear to be browser specific but for what it's worth I was using Chrome.

To repro:
- Deploy a new instance, and go through set up.
- Reset own password, log out and attempt to log in with that password. This will not work.
- Login with your original password (which still works)
- Be confused, and test again by creating a new user and make them an admin.
- Log in as that new user and reset the original admin's password.
- Try to log in as the original admin with the new password. This will also not work.
- Log in as the original admin using your original password which still works.
- Contemplate the meaning of life, have a sip of coffee, and proceed to file a bug.

**Comment by agilliland** [comment]
How exactly are you attempting to reset the password here?

**Comment by agilliland** [comment]
So, at least one part of the issue here is that it's not actually intended for the active user to reset their own password on the People admin page.  We have the account settings page which allows the currently active user to modify their password.  So unless there is an objection, I'm going to remove the `Reset Password` option from the actions list on the People admin page just for the currently active user.

**Comment by agilliland** [comment]
In fact, a better solution may be to remove all of the options under the ellipses because none of them actually make sense for the currently active user to do.

**Comment by kdoh** [comment]
@agilliland. Aha. So I kinda wondered if that might be what's happening but I wasn't sure if that was the intention since the button was there. So for the currently active user I do agree that we probably don't want them to delete their own account. I could see two sides of whether they should be able to reset their own password or not. To me its not a common action but its also not a ridiculous action.

One of the other issues I ran into that I'm not sure if you were able to replicate or not was that after subsequently creating another admin user I still wasn't able to reset the originally created "setup" or admin user's password from the admin interface which I do think is intended behavior.

**Comment by mazameli** [comment]
Could the `Reset Password` action take the user to the account settings page if they click that action for their own account? The action could read `Change Password` when clicking on one's own account from this list.

As for the other ellipses actions, it does seem weird to let them remove themselves, so I'd be in favor of hiding that action, but don't you think the `Edit Details` action is okay?

**Comment by agilliland** [comment]
I'm good any way to you want to do it.  The PR I just created simply removes the entire ellipses only for the currently active user, which seems like the cleanest way to deal with the situation.

It's not quite as accommodating, but it seems clear enough.

**Comment by agilliland** [comment]
And just to be clear, editing a password or editing personal details are both handled under the `Account Settings` page for the currently active user.  So by removing the ellipses we are mainly just saying you aren't supposed to admin yourself on that People admin page.

**Comment by mazameli** [comment]
Could just replace the list of actions within the ellipses menu for the current user with a link to Account Settings.

**Comment by agilliland** [comment]
Okay, following from conversation with @kdoh the agreed upon approach was to leave the ellipses in place and maintain the normal functionality, so an admin can reset their own password and edit their account details from the page just like any other user.

We did remove the option to `Remove User` since that seems unsafe to allow a person to do on themselves.
