### ISSUE TITLE
Update token check URL

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#27036]
We moved our token check service to a static IP, with a new domain, so customers can allow-list it in tighter environments.

Some people may have white-listed the old one, so in order to prevent disruption, this should entail:
- First trying the token check with the new domain (`token-check.metabase.com`)
- If that fails, try the old one (`store.metabase.com`) as a backup

That's it.

**Comment by flamber** [comment]
This can have major impact if we don't automatically handle fall-back.
