### ISSUE TITLE
Mongo sync should read more recent and fewer documents

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#27045]
# Context
Currently, we read the first 10k documents of each MongoDB collection to infer the schema and data types.
There are two problems with this approach:

1. As expected, a collection schema evolves over time. Most of the time, only newer documents reflect the new schema, developers don't update old documents if not needed. In large collections with +10k documents, it is possible that the schema evolves, but our sync process doesn't capture it. Related to #10484, #15576 and #11983
2. If the collection contains documents with many keys, 10k documents is possibly too much, leading to long sync durantion and OOM errors.

# Proposal
- We should read only the latest documents in a collection. The latest documents should reflect better the collection schema than the oldest. We can use the special `_id` column to sort documents. All MongoDB collections have a `_id` column, indexed that represents the document creation timestamp (so it can be sorted desc to get the latest).
- We should scan fewer documents. Possibly 500 is good and consistent with our Postgres nested field strategy. ([code link](https://github.com/metabase/metabase/blob/d8486fccb407b4ef936e04198b97a077ba896990/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L227-L229))

# Proposal update
- We should also scan the first 500 docs from the collection, so users have a reliable workaround to add more keys to the table.

**Comment by metamben** [comment]
@luizarakaki is the implementation expected to actually respect `nested-field-sample-limit` or is that just an example?

**Comment by luizarakaki** [comment]
It is not a product requirement, but makes sense imo. If you believe we should use `nested-field-sample-limit` let's go for it

**Comment by metamben** [comment]
Some users manually add columns to the first document to make Metabase notice them. To support this use case, we should not only look at the recent records but the oldest ones too.
