### ISSUE TITLE
How to add a MySQL database connection via socket?

### ISSUE THREAD

**Issue by devaxel** [metabase/metabase#27070]
Hi all.
I'm running metabase on a local Ubuntu-Server. In the Administration-Menu of metabase I added a new database connection to a external hosted MySQL-Database via SSH-Tunnel.
Until today everythings works fine.

Due to changes of my Hosting-Provider, they don't support external MySQL-Connections through SSH anymore. Instead I have to use a socket connection to access the MySQL-Database.

But how do I add a new databse connection to an external MySQL-Database via socket?

Any suggestions?

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
