### ISSUE TITLE
Links for the IDs are showing wrong objects when table join is in place

### ISSUE THREAD

**Issue by marek-leszczynski** [metabase/metabase#27094]
**Describe the bug**
After creating a question that includes table joins, Links in the result table are referencing the wrong objects or the objects that do not exist.

This is reproducible in both our deployments (staging and prod)

**Logs**
There is no error in the javascript console.

**To Reproduce**
1. Create a new question that includes table joins
2. Click on the ID of the object to see its details
3. See the error

**Expected behavior**
After clicking on the object ID to see its details, proper object details are shown.

**Screenshots**
![1](https://user-images.githubusercontent.com/7427754/206586381-ada16a5b-4e53-4f10-922c-a6ce634864f6.png)
![Notification_Center-2](https://user-images.githubusercontent.com/7427754/206586384-92e37672-b12c-42dc-9d28-ab71c7680ef9.png)
On clicking on the another ID
![Zrzut ekranu 2022-12-8 o 23 15 14](https://user-images.githubusercontent.com/7427754/206586438-6ce12e7a-978e-4081-970f-9b4c1609a84c.png)
Used question
![Zrzut ekranu 2022-12-8 o 23 53 56](https://user-images.githubusercontent.com/7427754/206586441-dd1ac3c6-6165-4b85-b939-a42eeb98e9e2.png)

**Information about your Metabase Installation:**
Hosted in AWS ECS using Fargate
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "4.14.294-220.533.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v0.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": "US/Central"
    }
  }
}
```

**Severity**
This issue is annoying to people who are working on the reporting, and it makes research harder. This tool is used mostly by non-technical staff, and they've started complaining about that tool, and they are asking for a replacement.

**Additional context**
This issue has been observed in version 0.44.x, which we started from.

**Comment by flamber** [comment]
Almost a repeat of #5837. Related #13165. It would also be great if the browser Back-button didn't require clicking twice when the modal is open.

https://user-images.githubusercontent.com/1447303/206734359-e8224ec0-8807-439a-a685-331fa309e7ec.mp4

**Comment by gusaiani** [comment]
### To reproduce

1. Unzip the attached sql file.
2. Execute it in Postgres to create a database.
3. Go to  Metabase
4. Add this database in Admin
4. `+ New`
5. Question
6. This database
7. Table 1
8. Join to Table 2 (Table 1 › id, Table 2 › table1_id)
9. Visualize
10. In results table, click on id of table 1

<img src=https://user-images.githubusercontent.com/380816/214155017-279e13d2-b57b-47d7-b515-f2b577c7d339.png width=400 />

[repro.zip](https://github.com/metabase/metabase/files/10483769/repro.zip)
