### ISSUE TITLE
Generalize product-triggered survey emails

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#27098]
## Context
One of the main ways we get feedback from customers is through our product-triggered survey emails. We currently have two versions of this email based on usage: one [general follow-up](https://github.com/metabase/metabase/blob/e734526e0fe8c76a0417de73085e9eaf899ac591/src/metabase/email/messages.clj#L112) and one that assumes the user [has abandoned](https://github.com/metabase/metabase/blob/e734526e0fe8c76a0417de73085e9eaf899ac591/src/metabase/email/messages.clj#L105) Metabase.

This doesn't work that well though. We often hear from users in the "abandoned" bucket that they haven't really abandoned the product, and were instead just working on other projects. The surveys linked from each email are also the same now, so forking this email doesn't provide any sort of differentiated responses.

 ## What
As far as what this means: 
- [ ] Let's remove the [abandonment](https://github.com/metabase/metabase/blob/e734526e0fe8c76a0417de73085e9eaf899ac591/src/metabase/email/messages.clj#L105) version of this email and send the general follow-up regardless of usage patterns. 
- [ ] We should also update the [call to action](https://github.com/metabase/metabase/blob/e734526e0fe8c76a0417de73085e9eaf899ac591/src/metabase/email/messages.clj#L114) in the general follow-up (which will now be used on all cases) to "Would you mind taking a quick 5-min survey to tell us how it’s going?" since the exact number of survey questions has changed and will likely change again in the future.

**Comment by calherries** [comment]
@cdeweyx Confirming: What should be the subject of the general follow up email? Should we stick with "Tell us how things are going."?

Relevant code:
https://github.com/metabase/metabase/blob/e734526e0fe8c76a0417de73085e9eaf899ac591/src/metabase/email/messages.clj#L288

**Comment by cdeweyx** [comment]
@calherries Yeah that can stay the same

**Comment by cdeweyx** [comment]
> We're now likely sending it twice to some users.

@calherries why are we now sending it twice to some users?

**Comment by calherries** [comment]
@cdeweyx Currently we send the 2-week follow up email if it's been 2+ weeks from instance creation and we haven't sent the 2-week follow up email before

We send the abandonment follow up email if it's been 4+ weeks from instance creation and it hasn't had any use in 2+ weeks and we haven't sent the _abandonment_ follow up email.

If we use the same content for both, from the users perspective we could send the same email twice.

**Comment by cdeweyx** [comment]
@calherries Can we just do this:

> We send the 2-week follow up email if it's been 2+ weeks from instance creation and we haven't sent the 2-week follow up email before

And remove the abandonment email (and logic associated with the email). That way there's only one email being sent, and it wouldn't be sent twice to the same person.

**Comment by calherries** [comment]
Yeah, we can. 👍
