### ISSUE TITLE
Update the data picker starting point when working with Models

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#27101]
## Context
When starting I'm already using a Metabase model in the notebook editor and go to join data, the current default is to show the "Raw Data" group in the data picker. But this doesn't feel quite right, because if someone is already using a Model there's a good chance that the data they are joining to is also a Model.

## What
Let's make this interaction a bit smarter:
- [ ] If someone is using a Model in their query already then update the data picker starting point for joins to be "Models" instead of the "Raw Data" group. 
- [ ] Bonus points if we can start them in the same collection as the initial Model selected, that is if that collection indeed has other Models in it.

### Current behavior
![Image](https://user-images.githubusercontent.com/16455495/206611929-b886e6ff-0435-4687-b1e4-c990b4a939f9.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/16455495/206612501-01abefb9-aa68-4eff-bb57-d85cb9784845.png)

**Comment by flamber** [comment]
DataSelect related #20406
