### ISSUE TITLE
No colored cirlce icon in legend, single series

### ISSUE THREAD

**Issue by marketingnerds** [metabase/metabase#2715]
Affecting visualization on both dash and card pages.

![image](https://cloud.githubusercontent.com/assets/15113386/15907057/85174c00-2d89-11e6-82e8-d6d977efb4a7.png)

If this is a bug report, please fill in the blanks:
-  I am using the **_chromium_____**_ browser.
-  My computer's OS is **linux_______**.
-  I'm running Metabase **AWS_______**. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is **_MariaDB_____**_.
-  My Metabase version is **_0.17.1_____**_.

**Comment by salsakran** [comment]
For single series we don't use an icon, as there is only a single possible label for the series.

Is this causing confusion with your users?

**Comment by marketingnerds** [comment]
@salsakran no, just with me :)

I think the legend should either include the dot and the label or simply be removed for single series.

**Comment by mazameli** [comment]
No longer relevant — we hide the label for single series now.
