### ISSUE TITLE
Login page & activity feed weirdness on Safari 7 / Mac App

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2716]
This is 0.18.0-SNAPSHOT / Safari 7.0

I haven't seen this before but hopefully it's limited to older versions of Safari like mine. Either way, we should take a look at this page on other browsers and make sure it looks ok ?? 

![screen shot 2016-06-08 at 1 41 22 pm](https://cloud.githubusercontent.com/assets/1455846/15910248/de4e4914-2d7e-11e6-9dbe-5af5ff7ff8e4.png)

**Comment by camsaul** [comment]
Another bit of weirdness is the activity feed (in the Mac App). The activity dates aren't lined up and the "Recently Viewed" sidebar is forced off-screen with a horizontal scroll bar

![screen shot 2016-06-08 at 1 44 11 pm](https://cloud.githubusercontent.com/assets/1455846/15910329/384da018-2d7f-11e6-99eb-98ff69ec5a87.png)

**Comment by camsaul** [comment]
also the admin drop-down is all the way off-screen and invisible 🙀 
![screen shot 2016-06-08 at 1 46 16 pm](https://cloud.githubusercontent.com/assets/1455846/15910403/8391dc7e-2d7f-11e6-9510-39fcc533d79b.png)

**Comment by agilliland** [comment]
If the fix is easy then great, but Safari 7.x is not considered one of our supported browser versions

**Comment by camsaul** [comment]
like I said we should check and see if this affects any other browsers

**Comment by kdoh** [comment]
@camsaul Looks like your screenshots are from the Mac App. Do you know if the Mac App webkit version is tied to the system Safari webkit version or is it its own little sandbox?

**Comment by camsaul** [comment]
it's the system webkit version. The first screenshot was Safari on my computer.

**Comment by camsaul** [comment]
Same as #2524. I've came to accept the fact that we don't really support ancient Safari anymore so I will just have to upgrade my computer one of these days. Closing as No Longer Relevant
