### ISSUE TITLE
[Epic] Time zone metadata improvements for 46

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#27178]
A handful of improvements to the way we we deal with time zones in the Query Processor.

### Shovel-Ready

- [ ] #14056
- [ ] #27177
- [x] ~#6439~

### Details Being Hashed Out 

- [ ] #4284
- [ ] Support per-Query overrides

### Related

- [ ] #5927

### Internal Documents
[Brain dump](https://www.notion.so/metabase/Sameer-s-brain-dump-on-timezones-7e5c4fce1f78482faa00a59638b3e53d)
[Open questions](https://www.notion.so/metabase/Splitting-report-timezone-open-questions-2511e67e45e448e6bbc21a8cba158f41)
[Timezone snapshot](https://www.notion.so/metabase/Timezones-snapshot-6124cdfba58447feadc69b53d7a38787)
[Product doc](https://www.notion.so/metabase/Unlock-advanced-date-time-manipulation-038f5cf80f364d7cb93341784169743c)
[Learnings from trying to split display timezone](https://www.notion.so/metabase/Splitting-report-timezone-open-questions-2511e67e45e448e6bbc21a8cba158f41#b340c45e058a4f58848a21903f0d9d24)

**Comment by snoe** [comment]
Moving to Not Planned
Spent time on https://github.com/metabase/metabase/issues/14056, with findings in comments. tldr splitting out display-timezone probably should never happen, splitting out implicit-timezone is less important with a more detailed understanding of session timezone.
My conclusion with https://github.com/metabase/metabase/issues/27177 is that it should be split out to specific drivers. Drivers that DO have session timezone, apply it no matter what, so inlining would still result in it taking over. `AT TIME ZONE` is a cast that goes back and forth between local timestamps and timestamp with time zone. If we want to support local temporal values better, it's a whole different project to remove a lot of the localization that we force (probably through the user/query/database specified timezones).
