### ISSUE TITLE
warning icon on add/edit multi-series modal is ending up at different sizes

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2718]
All of these icons should be the same size ...

<img width="124" alt="screen shot 2016-06-08 at 3 14 02 pm" src="https://cloud.githubusercontent.com/assets/1987787/15912970/6ed2c016-2d8c-11e6-8e58-76af3faf869e.png">

**Comment by kdoh** [comment]
Well this seems fun. Any idea how to reproduce it or if there's anything special about the case where you encountered it?

**Comment by tlrobinson** [comment]
Probably just needs a `flex-no-shrink` or something.

**Comment by kdoh** [comment]
@tlrobinson But if ``flex align-center`` is on the element than nothing can possibly go wrong.

**Comment by tlrobinson** [comment]
👍
