### ISSUE TITLE
[`metabase-lib`] Migrate `format_date` to cljs

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#27181]
Source:
- Implementation https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase/lib/formatting/date.tsx#L253
- Unit tests https://github.com/metabase/metabase/blob/058c31e1889efe8858ee5fd31da9880047a75e31/frontend/test/metabase/lib/formatting.unit.spec.js#L517

Signature:
```
format_date(value: number, options: DateOptions): string;

interface DateOptions { 
  unit?: DateUnit
  compact?: boolean
  date_style?: DateStyle
  time_style?: TimeStyle
  time_enabled?: boolean
  date_abbreviate?: boolean
  date_separator?: string
}

type DateUnit =
  | "default"
  | "minute"
  | "minute-of-hour"
  | "hour"
  | "hour-of-day"
  | "day"
  | "day-of-week"
  | "day-of-month"
  | "day-of-year"
  | "week"
  | "week-of-year"
  | "month"
  | "month-of-year"
  | "quarter"
  | "quarter-of-year"
  | "year";

type DateStyle = 
  | "MMMM D, YYYY"
  | "D MMMM, YYYY"
  | "dddd, MMMM D, YYYY"
  | "M/D/YYYY"
  | "D/M/YYYY"
  | "YYYY/M/D";

type TimeStyle =
  | "HH:MM"
  | "HH:MM:SS"
  | "HH:MM:SS.MS";
```

Notes:
- This is locale-dependent. Should we pass it as a parameter? 
- Would it be ok to pass a date as a timestamp (= number)?
- We need to think about how to handle `isExclude` on the FE without putting it inside the function.
- The same for `type = cell` and automatic expanding of weeks into ranges. We would later add a separate function to format date ranges, maybe it should go there.
- I believe we sometimes call this function with format strings outside of the list (?)

**Comment by camsaul** [comment]
Braden's notes from https://github.com/metabase/metabase/issues/26961#issuecomment-1346550025

> First glance at the notes from `format_date`:
> - On locales: both platforms have a sense of default locale; it still makes sense to pass it as a parameter ~everywhere and fill in the parameter at the outer surface if it's not given.
> - "Would it be okay to pass a date as a timestamp (= number)?" OK in what sense? Clojure integers are `long`s, so they can hold (milli)second timestamps safely, as can JS doubles. Did you mean something else?

**Comment by bshepherdson** [comment]
The more I've dug into the functions in `formatting/date.tsx` the more I'm concerned about how actionable this is.

Many of the the call sites for these functions look like this ([`metabase-lib/queries/utils/query-time.js`](https://github.com/metabase/metabase/blob/master/frontend/src/metabase-lib/queries/utils/query-time.js#L182)):
```js
export function generateTimeValueDescription(value, bucketing, isExclude) {
  if (typeof value === "number" && bucketing === "hour-of-day") {
    return moment().hour(value).format("h A");
  } else if (typeof value === "string") {
    const m = parseTimestamp(value, bucketing);
    if (bucketing) {
      return formatDateTimeWithUnit(value, bucketing, { isExclude });
    } else if (m.hours() || m.minutes()) {
      return m.format("MMMM D, YYYY hh:mm a");
    } else {
      return m.format("MMMM D, YYYY");
    }
  } else if (isRelativeDatetime(value)) {
    let n = value[1];
    let unit = value[2];

    if (n === "current") {
      n = 0;
      unit = bucketing;
    }

    if (bucketing === unit) {
      return generateTimeIntervalDescription(n, unit);
    } else {
      // FIXME: what to do if the bucketing and unit don't match?
      if (n === 0) {
        return t`Now`;
      } else {
        return n < 0
          ? t`${-n} ${formatBucketing(unit, -n).toLowerCase()} ago`
          : t`${n} ${formatBucketing(unit, n).toLowerCase()} from now`;
      }
    }
  } else {
    console.warn("Unknown datetime format", value);
    return `[${t`Unknown`}]`;
  }
}
```
which mixes together
- complex business logic about how to handle different kinds of date-like things (relative dates, a number is interpreted as an hour-of-day, strings are expected to parse as ISO-format date strings, moment values, js `Date` objects)
- direct calls to moment, including its `format()` functionality.
- calls to this date library
- parsing of timestamps as strings into moment values

I acknowledge that date/time things are always complex but it feels like a CLJS port may not be a practical next step here. It feels like we want to design and build a more consistent approach for handling dates and times in the FE (in CLJS I guess) and gradually migrate things onto it.

Thoughts?
