### ISSUE TITLE
Postgres "specific dates" filter errors with datetime custom expression functions

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#27185]
When using a Postgres database, applying a "specific dates" filter with a custom expression function results in an error:

`ERROR: operator does not exist: timestamp with time zone >= character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts.`

<img width="569" alt="image" src="https://user-images.githubusercontent.com/39073188/207144175-cf8cb190-4638-4bcc-9d25-23e117039bf7.png">

Steps to reproduce: 
1. Create a new question, selecting `Orders`
2. Create a custom expression with the formula `datetimeAdd([Created At], 1, "month")`
3. Create a filter on the custom expression column, selecting "specific dates"
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/39073188/207143154-05ba8378-7fcc-420c-8ace-7d3523abdbe7.png">
4. Observe the error.

`ERROR: operator does not exist: timestamp with time zone >= character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 1091`

Can replicate with `now`, `datetimeSubtract`, or `convertTimezone` by changing step 2.

- Your databases: Postgres
- Metabase version: 0.45.1

The problem might exist for other DBMS other than Postgres.

**Comment by flamber** [comment]
Seems related to #25994, but that's FE, whereas this feels like BE.

**Comment by imiskolee** [comment]
how about this issue, I still faced this too.

**Comment by ranquild** [comment]
You can create the filter in the UI but the backend throws

<img width="1728" alt="Screenshot 2023-11-08 at 14 11 36" src="https://github.com/metabase/metabase/assets/8542534/01b813a5-08e1-4f95-a79f-ab24f08b3ef1">

**Comment by bshepherdson** [comment]
This is still happening, at least with Postgres.

Here's the error message I got:
```
ERROR: operator does not exist: timestamp without time zone >= character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 820
```
presumably missing a type cast or conversion somewhere that applies to date-valued real columns but not to expressions.
