### ISSUE TITLE
FE - Split data access and query builder access and merge GUI and SQL permissions

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#27200]
This issue entails the FE part of the project: [Split data access and query builder access, merge GUI and SQL permission](https://www.notion.so/metabase/Split-data-access-and-query-builder-access-merge-GUI-and-SQL-permission-f18185f2c2954127bdfcb2864ef5c13f)

**Comment by cdeweyx** [comment]
Closing in favor of https://github.com/metabase/metabase/issues/26918 since we can have multi-team epics now.
