### ISSUE TITLE
FE - Foreign key mapping between models

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#27201]
This issue entails the FE part of [Foreign key mapping between models](https://www.notion.so/metabase/Foreign-key-mapping-between-models-1764637ef82c478db9c09a6a11a07140). This project is scheduled for the QP/Drivers team.

[Design link](https://www.figma.com/file/f4u0Jr5Y2w6y2XXVDWtVla/Foreign-key-mapping-between-models?node-id=2%3A264&t=PWN5i2gDQu16OGgC-4)

**Comment by cdeweyx** [comment]
Closing in favor of https://github.com/metabase/metabase/issues/25052
