### ISSUE TITLE
Ability to change X-Frame-Options

### ISSUE THREAD

**Issue by andreialbu** [metabase/metabase#2721]
Hi, we're using Metabase heavily and really like it, but we would like to integrate it into our internal portal through an iframe and for this we need to be able to change the X-Frame-Options.

For now we're building our customized jar, but it would be great to have it out of the box. Thanks!

**Comment by salsakran** [comment]
Hey @andreialbu , mind filling out a survey regarding the integration you mentioned? https://docs.google.com/a/metabase.com/forms/d/11eZ5mwDy8IZaLZYlOUMyjCLXzJXKsGLaI1_xzi8TFD8/viewform

**Comment by salsakran** [comment]
Whatever we do wrt to this should keep clickjacking attacks in mind - 
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet

**Comment by justnom** [comment]
@andreialbu 

Just as a stop gap, I've put nginx in front of metabase and used the nginx configuration:
```
more_set_headers 'X-Frame-Options: ALLOWALL';
```

**Comment by noamgat** [comment]
+1

**Comment by salsakran** [comment]
realistically, we're not going to open up a clickjacking vector, so closing this.

**Comment by clouless** [comment]
Just for anyone stumbling upon this, here is my Nginx config for an SSL Proxy with enabled `X-Frame-Options`

```
server {
   listen 443;
   ssl on;
   ssl_certificate /etc/nginx/sites-enabled/metabase.myhost.crt;
   ssl_certificate_key /etc/nginx/sites-enabled/metabase.myhost.key;
   ssl_session_timeout 5m;
   ssl_session_cache shared:SSL:10m;
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
   ssl_prefer_server_ciphers on;
   add_header Strict-Transport-Security 'max-age=63072000; includeSubdomains; ';
   add_header X-Frame-Options 'DENY';
   server_name metabase.myhost;
   access_log /var/log/nginx/access_metabase.log;
   error_log /var/log/nginx/error_metabase.log;

   location ^~ / {
      proxy_headers_hash_bucket_size 128;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
      client_max_body_size 20M;
      sendfile off;
      add_header X-Frame-Options ALLOWALL;
      proxy_pass http://metabase.myhost:32622;
   }
}
```

**Comment by SemStu** [comment]
> Just for anyone stumbling upon this, here is my Nginx config for an SSL Proxy with enabled `X-Frame-Options`
> 
> ```
> server {
>    listen 443;
>    ssl on;
>    ssl_certificate /etc/nginx/sites-enabled/metabase.myhost.crt;
>    ssl_certificate_key /etc/nginx/sites-enabled/metabase.myhost.key;
>    ssl_session_timeout 5m;
>    ssl_session_cache shared:SSL:10m;
>    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
>    ssl_prefer_server_ciphers on;
>    add_header Strict-Transport-Security 'max-age=63072000; includeSubdomains; ';
>    add_header X-Frame-Options 'DENY';
>    server_name metabase.myhost;
>    access_log /var/log/nginx/access_metabase.log;
>    error_log /var/log/nginx/error_metabase.log;
> 
>    location ^~ / {
>       proxy_headers_hash_bucket_size 128;
>       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>       proxy_set_header Host $http_host;
>       proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
>       client_max_body_size 20M;
>       sendfile off;
>       add_header X-Frame-Options ALLOWALL;
>       proxy_pass http://metabase.myhost:32622;
>    }
> }
> ```

Tried this solution. I'm able now to iFrame Metabase in my application however I can't get past the Metabase login window now. It just accepts my input and then shows the login window again. Tested in multiple browsers. Have you had the same issue? If so, how were you able to solve this?

**Comment by clouless** [comment]
The only magic thing is `add_header X-Frame-Options ALLOWALL;` and that metabase itself has a correct baseUrl pointing to the NGINX Server e.g.

<img width="1024" alt="Bildschirmfoto 2020-05-07 um 12 21 26" src="https://user-images.githubusercontent.com/12599965/81283709-5aec1100-905d-11ea-9eb2-4c2fe70b1292.png">
