### ISSUE TITLE
Show percentage change in tooltips for funnel charts

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#27236]
## Proposed
When I mouse over a step in funnel visualizations, if it's not the first step, then show me the percentage change (relative to the previous step) in the tooltip alongside the metrics themselves.

<img width="482" alt="Screenshot 2022-12-14 at 11 42 11" src="https://user-images.githubusercontent.com/16455495/207655455-9184e90a-cd50-446a-890b-de0c8404ed8c.png">

**Comment by cdeweyx** [comment]
Notes for design: 
- How should we show this change?
- How should we convince a negative change?

**Comment by colax94** [comment]
This would be very helpful, it would even be nicer if we could switch between the percentages relative to the previous step or to the first step.

**Comment by ignacio-mb** [comment]
@cdeweyx was this merged for 50?

**Comment by cdeweyx** [comment]
@ignacio-mb Yep correct
