### ISSUE TITLE
Choropleth visualizations crash on null values

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2724]
This is in the `dashboard-filters` branch.

Seeing this error in the JS console.  Happens both on a dashboard and in the QB for the same card.

![screen shot 2016-06-09 at 11 36 12 am](https://cloud.githubusercontent.com/assets/1987787/15941781/8a7cf160-2e36-11e6-8c55-3303a40ccef2.png)

**Comment by salsakran** [comment]
also seeing this in v 0.17.1

**Comment by tlrobinson** [comment]
I'm not seeing this on `dashboard-filters` or v0.17.1. Do you have steps to reproduce it?

**Comment by tlrobinson** [comment]
Looks like it's `null` values causing this.
