### ISSUE TITLE
Hot reloading of backend development

### ISSUE THREAD

**Issue by dannyknight327** [metabase/metabase#27240]
Hello.
Hope everyone is doing well.

For client 's need, I have to develop custom codes in api and model of metabase backend.
Documentation says that use "clojure -M:run" command to run development server.

The trouble is that backend code is not hot reloading.
Hence, I have to restart backend server on every code update.

I have read [12181](https://github.com/metabase/metabase/issues/12181) and [18801](https://github.com/metabase/metabase/pull/18801).

First, I am confused which one the right solution is.
Secondly, what is the right command to start backend server for hot reloading?

Furthermore, [18801](https://github.com/metabase/metabase/pull/18801) says that it only works on "api" update.
So...  Are there no solutions for "model" update now ?

Sorry for bothering you with repeated issue.
Looking forward to your kind consideration.

Best regards.

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
