### ISSUE TITLE
Mongo does not handle nested limit

### ISSUE THREAD

**Issue by snoe** [metabase/metabase#27249]
As part of https://github.com/metabase/metabase/issues/23422 we discovered that 
`metabase.query-processor-test.expressions-test/expression-using-aggregation-test` was failing (partly) because the `:limit 3` inside source query was being ignored.

**Comment by metamben** [comment]
This has been fixed (in the course of implementing nested queries, I think).

**Comment by paoliniluis** [comment]
If that’s the case @metamben , feel free to close this issue

**Comment by metamben** [comment]
> If that’s the case @metamben , feel free to close this issue

#27955 should close it when it gets merged.
