### ISSUE TITLE
Update Kondo config to ban `str/upper-case` and `str/lower-case` and fix remaining usages

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#27250]
Using Metabase with your system locale set to Turkish is like walking thru a minefield: sooner or later, something will explode. For example:

- #9011
- #9073
- #9177
- #12171
- #12623
- #13102
- https://github.com/dm3/clojure.java-time/pull/60
- https://github.com/seancorfield/honeysql/issues/236

The root cause of all these problems is that `(str/lower-case "TIME")` is `"tıme"`. Note the `ı` instead of an `i`. The lower-cased version of the string is dependent on the system Locale.

To fix this problem, we have `u/lower-case-en`, and we're supposed to be using that everywhere for everything.

We have mostly followed that approach, and things are working now, but it is way too easy to forget that you need to do this. See #27237 for example where @calherries fixed a handful of places that weren't following the rule.

We should make it impossible to shoot yourself in the foot. Let's configure Kondo to ban `str/upper-case` and `str/lower-case` altogether in our codebase and solve this problem once and for all. It looks like with the latest version of Kondo you can use `:discouraged-var` to do this without even writing a custom linter:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#discouraged-var

Let's add that to our Kondo config and fix any remaining usages.

**Comment by camsaul** [comment]
@calherries, yes, if people really have a legitimate reason to use them they can write a `:clj-kondo/ignore` comment (with another comment explaining why this is a legitimate reason to use it). But even if you did want to format something in Turkish, you probably don't want to rely on the JVM system locale -- we should be using the `user-locale` or `site-locale` Setting, which we let you change at runtime; they may be something completely different from the system locale. In that case, you'd want to use `(.lowerCase ^String s ^Locale locale)` or whatever it's called directly

**Comment by weyj4** [comment]
@camsaul I went ahead and updated [https://github.com/metabase/metabase/blob/master/.clj-kondo/config.edn](https://github.com/metabase/metabase/blob/master/.clj-kondo/config.edn) with the two bans via `discouraged-var`. If nobody else is working on this issue I'm happy to go through and manually update all occurrences of `str/lower-case` and `str-upper-case`! I'm new here, hope this is helpful!

**Comment by camsaul** [comment]
@weyj4 that would be very helpful, PRs are welcome!
