### ISSUE TITLE
Number filter with `0` (zero) as default value shows as empty in the widget

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#27257]
**Describe the bug**
Number filter with `0` (zero) as value shows as empty in the widget.
Regression since 0.44.0

**To Reproduce**
Can be reproduced on dashboard and native number filters.
1. Native > Sample > `select {{number}}` with Number variable
2. Input `0` (zero) into the filter widget - run query
![image](https://user-images.githubusercontent.com/1447303/207839297-7e43fd91-7531-4f20-b6b1-dd1cc31e39dd.png)
3. Do a browser refresh - the filter widget shows as blank, but it correctly applied.
![image](https://user-images.githubusercontent.com/1447303/207839406-15ee70fe-c675-40fd-b5bb-c1f3c49ab171.png)

**Information about your Metabase Installation:**
Tested 0.43.5 thru 0.45.1. Regression since 0.44.0

**Comment by nemanjaglumac** [comment]
@flamber, not sure how did you get the `0` to still display as the ScalarValue in the step 3 after a refresh?
For me it always shows "Here's where your results will appear" (both in Cypress and locally).
![image](https://user-images.githubusercontent.com/31325167/208454759-b8ac33f1-d9b7-4b73-bd23-c406c7d0bd77.png)

https://github.com/metabase/metabase/pull/27324/files#diff-9c8149b4a5f04f7f70e511c0f7d83548d20e55f5caef5b781af1bc116734b47bR40

**Comment by flamber** [comment]
@nemanjaglumac Automatic execution of unsaved SQL queries have been disabled in 0.44.5

**Comment by iethree** [comment]
> Initially, the widget value is `0`. After the refresh, it's `[0]`.
> 
> ~"Normalization" seems to happen here: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/components/ParameterValueWidget.jsx#L213:L215~
> 
> ~And then the `NumberinputWidget` is using `normalizedValue`: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/components/ParameterValueWidget.jsx#L238~
> 
> Edit: Actually, something else feels wrong here. It seems that this is `TextWidget` instead of `NumberInputWidget` !

I also though that not using `NumberInputWidget` seemed like the culprit - but that component is not what we want here at all. The issue is that we started parsing parameter values as numbers a while ago that caused this regression.
