### ISSUE TITLE
Native queries for Mongo in v0.18

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#2726]
@camsaul or @agilliland, could you please tell me more about solution which realised in #2072? I've built the JAR 0.18 version from master. Can I try to use a custom requests for the MongoDB? Please, give me more examples.

**Comment by agilliland** [comment]
Sure.  If you are using the latest code then you can simply start a new question as usual, then click the little icon in the top right which looks like a cmd prompt which will switch the question over to "native" editing mode and will just give you a large textarea to work with.

For mongo you'll need to pick your your database and a collection to execute your query against, then you'll want to fill out the query.  The system expects you to define your native mongo queries in JSON using the Mongo Aggregation Pipeline https://docs.mongodb.com/manual/core/aggregation-pipeline/

**Comment by anki-code** [comment]
Thank you! Solved.

Example for other users.
In mongo:
```
> db.Users.aggregate( [ { $group : { _id : "$EntityCreatedAt", count: { $sum: 1 } } } ] )
{ "_id" : ISODate("2016-06-08T14:03:22.104Z"), "count" : 1 }
{ "_id" : ISODate("2016-06-08T15:27:28.003Z"), "count" : 1 }
```

In metabase: `[ { "$group" : { "_id" : "$EntityCreatedAt", "count": { "$sum": 1 } } } ]`

Quotes for all keys!

**Comment by FerJmnz** [comment]
Please help me.

I want to use a native mongodb query in Metabase, but i have problems with this. In my case i need to use a find statement to select some fields as a general question. 

I don't need aggregation

Thanks!!

**Comment by camsaul** [comment]
@FerJmnz Metabase currently only supports native Mongo queries written using the [aggregation pipeline](https://docs.mongodb.com/manual/core/aggregation-pipeline/) so you'll have to write it that way.

**Comment by FerJmnz** [comment]
@camsaul thanks for your answer.

In "**New question**" section we have **Customize this table** option. This option allows select the fields to include in the question. In my case i have a nested objects in json (documents) but i can't select nested properties. Metabase work with first level properties only ??

Thanks!!

**Comment by camsaul** [comment]
At this moment, yes.

**Comment by FerJmnz** [comment]
@camsaul thanks for your help.

**Comment by FerJmnz** [comment]
Hi, @camsaul 

Please, do you know any online course or training for Metabase?

Thanks!!

**Comment by camsaul** [comment]
@FerJmnz a good starting place is [this wonderful introduction to Metabase](http://www.metabase.com/blog/Analytics_in_1_hour) and these [video tutorials](https://www.youtube.com/watch?v=wmJ02K8LIFk)

**Comment by FerJmnz** [comment]
Thanks @camsaul. Your help is very important.
