### ISSUE TITLE
Detect if the DB has migrations from a future Metabase version and print a warning

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#27273]
Now that we have support for reverse migrations, we should be able to detect on startup if there are migrations that have been run from a Metabase version higher than the current one, and print a big warning that the rollback command needs to be run or else stuff might be broken.

cc @camsaul

**Comment by flamber** [comment]
Would "resolve" #24909 #14904 ...

**Comment by noahmoss** [comment]
Duplicate of https://github.com/metabase/metabase/issues/27906 which has now been closed
