### ISSUE TITLE
Color picker not working for region map question visualization 

### ISSUE THREAD

**Issue by TLazarevic** [metabase/metabase#27278]
**Describe the bug**
Color picker for 'Map' question visualisation is not updating map color when different color is selected.

**To Reproduce**
1. Go to question with region map visualisation
2. Click on 'Visualisation' button
3. Click on 'Map' option
4. Click on 'Color' color picker 
5. Select different color option
6. Nothing happens

**Expected behavior**
Map visualisation should change color to selected color picker option.

**Information about your Metabase Installation:**
- Browser: Brave v1.46.144 
- Metabase version: v0.45.0

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Yeah, it's not very obvious that you have to click the preview color bar to make it change. Regression since 0.44.0.
![image](https://user-images.githubusercontent.com/1447303/208088597-5ffa3405-324b-4ba2-bd5a-c663828a9091.png)

**Comment by TLazarevic** [comment]
Thanks for the quick response

**Comment by mickaelandrieu** [comment]
Thanks ! It's not obvious at all ...
