### ISSUE TITLE
MongoDB does not support expressions inside aggregations

### ISSUE THREAD

**Issue by snoe** [metabase/metabase#27275]
As part of https://github.com/metabase/metabase/issues/23422 we discovered that `metabase.query-processor-test.sum-where-test/sum-where-inside-expressions-test` was failing.

An example mbql query which will ignore the `:+` and `:/` 

```clojure
{:aggregation 
 [[:+
   [:/
    [:sum-where
     [:field (mt/id :venues :price) nil]
     [:< [:field (mt/id :venues :price) nil] 4]]
    2]
   1]]}
```

**Comment by metamben** [comment]
This case has been fixed in #27176.
