### ISSUE TITLE
Wrong website url, will not be able to open the "General" menu

### ISSUE THREAD

**Issue by Avey777** [metabase/metabase#27282]
**Describe the bug**
If you set the wrong website url, you will not be able to open the "General" menu

**Screenshots**
![image](https://user-images.githubusercontent.com/35259040/208110714-5b7d6358-4b9a-4e57-93c8-6a4ed1686103.png)

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
