### ISSUE TITLE
Offer a new full-app embedding url param for logo

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#27293]
## Context
We offer several several url parameters for customers in full-app embedding to configure how their Metabase instance looks in the embedded iFrame. We recently made the `top_nav` default visible and added `breadcrumbs` as an option in https://github.com/metabase/metabase/pull/26977. 

With this new behavior, there's a new twist of "I want breadcrumbs so that my users can navigate the instance, but I already show a logo in my app, so having the logo in the top nav as well is duplicative and looks bad." Example below.

Let's offer a new `logo` sub-param for `top_nav` that is default on. When it's disabled, breadcrumbs should be scooted over to be left-aligned. Same logic as before if all sub-params are disabled, the whole top-nav is disabled as it serves no purpose.

![Image](https://user-images.githubusercontent.com/16455495/208149955-8054ff1a-4b32-4f01-abf3-5b29cdbe4adc.png)

**Comment by bunnymatt** [comment]
We got creative and changed the logo to be the sidebar icon :) 

![Screen Shot 2022-12-16 at 11 29 45 AM](https://user-images.githubusercontent.com/103591073/208165526-9f79d2cd-cd62-47fc-8cb3-2962bcc727fb.png)

**Comment by brunobergher** [comment]
Here's the spec we agreed to on Slack.

**Param**
The parameter is called `logo`, default `true`.

**States**
If `logo: true` and `sidenav: true`, it looks like regular Metabase
If `logo: true` and `sidenav: false`, just don’t show the sidenav hover icon on the logo.
If `logo: false` and `sidenav: true`, we always show the sidenav icon, as in the comment above, but with the usual color.
If `logo: false` and `sidenav: false`, the breadcrumbs move all the way to the left.
