### ISSUE TITLE
Remove the non-JDBC Presto driver

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#27296]
Our first version of a Presto driver (#4294) (`:presto`) ran queries via HTTP API endpoints. At the time, there was no JDBC driver available for Presto, or at least not one that we knew about. Soon thereafter we realized a JDBC driver was available, and made plans to switch to it (#8893). Eventually in #16194 we implemented a JDBC-based Presto driver (`:presto-jdbc`) with the intention that we'd deprecate the original `:presto` driver and encourage everyone to move over to `:presto-jdbc` and eventually remove it entirely. This is similar to what we did with the original `:bigquery` driver which we eventually replaced with our `:bigquery-cloud-sdk` driver.

We've already renamed the old `:presto` driver to `Presto (Deprecated Driver)` -- I'm not sure if we show people a warning or anything else, which I think we might have done for `:bigquery`; I don't know if we announced this deprecation at any point (or if we need/want to). So step one is determining whether we've advertised the deprecation adequately or not. If we haven't, we should do whatever we need to do to be comfortable removing the legacy driver in a future release.

- [ ] Investigate and confirm that we've adequately announced the deprecation of the legacy driver. 
- [ ] If we haven't properly announced the deprecation yet, do so.

If/when we are satisfied with our communications regarding the deprecation of the legacy driver, we should remove the legacy driver entirely:

- [ ] Remove the `modules/drivers/presto` directory and references to it or the `:presto` driver in `deps.edn` and the GH Actions CI config files
- [ ] Merge `modules/drivers/presto-common` (and `:presto-common` abstract parent driver) into the `modules/drivers/presto-jdbc` directory/`:presto-jdbc` driver
- [ ] Write a migration to migrate Databases with `engine = 'presto'` to `engine = 'presto-jdbc'`. I don't know if we can feasibly migrate `details` or not, since things are somewhat different. If we can't migrate the details, clearing them out and requiring people who didn't migrate when they had the chance to go update their connection details in the admin panel is an acceptable outcome.

**Comment by luizarakaki** [comment]
The only comms I could find about Presto are:
- A notice of the new driver release in 41 (no mention about a deprecation).
- If you are using the old Presto driver, there is a warning in the database page.

It is not possible to connect using the old driver for a long time (since 41).

I'm 👍 for total migration + removal in 45.

**Comment by luizarakaki** [comment]
Adding some info: we have a large customer still using this driver. There are blockers that are preventing them to upgrade to the new driver and we should check their status.

**Comment by camsaul** [comment]
We should tackle #7742 first because the aforementioned customer is blocked on it -- the legacy Presto driver does not support parameterized (as in `?` JDBC parameters) so #7742 was not a problem there
