### ISSUE TITLE
Write V2 permission paths alongside V1 paths whenever permissions are updated

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#27300]
This is a task within milestone 2 of https://github.com/metabase/metabase/issues/26918. For this task, whenever data permissions are updated, we should write both the current permission paths as well as v2 paths to the database. V2 paths will not yet be used for enforcement or displayed to users.

The mapping from v1 to v2 paths is deterministic and should be the same logic used for the one-time migration of existing paths.

TODO:
- [x] Determine whether we're using a different table, or the same table, for the new paths
- [x] Determine whether we want to change the table schema

**Comment by escherize** [comment]
Looks like we can a) reuse the same table, and b) make no updates to the table's schema.

There might be a benefit to putting in a more structured interpretation of the data that is in the paths. But that can also be computed (with some effort), so it is unneccessary
