### ISSUE TITLE
Return V2 permission paths when fetching permissions graph

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#27302]
This is a task for the backend part of milestone 4 of https://github.com/metabase/metabase/issues/26918. This task involves exposing the new permission paths in the API, so that they can be consumed by the frontend. Should be worked on in conjunction with https://github.com/metabase/metabase/issues/27200

**Comment by escherize** [comment]
This adds a v2 perm graph endpoint, which returns the v2 graph shape.

**Comment by escherize** [comment]
closed by #28072
