### ISSUE TITLE
Lost all data when upgrading - my fault but could be clearer

### ISSUE THREAD

**Issue by nfarina** [metabase/metabase#27331]
**Is your feature request related to a problem? Please describe.**

I set up Metabase on Google Cloud using the official container image running on GCE with a google load balancer in front. I assumed, incorrectly, that my data (dashboards, questions) would persist when I went about upgrading my container image. Not so!

Should I have backed up my data? Hell yes! But, you know, I didn't. "Just a minor upgrade" I thought.

Now that it's too late, I see this fine print on the [Docker container page](https://hub.docker.com/r/metabase/metabase/):

> NOTE: this will run Metabase without any persistent storage for the application. if you plan to run Metabase continually we recommend establishing a way to keep the application data outside of the docker container

I also found, again too late, this helpful blurb on a [Metabase blog post](https://www.metabase.com/blog/why-metabase-cloud):

> Why not use the embedded H2 database and just run one server? Because the embedded H2 database will ruin your life. We included the embedded H2 application database as a party favor so people could just download the Metabase JAR or Docker image and be able to start querying data in minutes. The H2 database is intended for demos, not production. It will get corrupted at some point, and you will suffer.

Here's me suffering!

**Describe the solution you'd like**

I totally get that you want people to get from Zero to Metabase as quickly as possible. Setting up all the Google Cloud stuff was a PITA and took a million clicks, and it was _really nice_ that Metabase itself just started up and let me _do stuff_ right away without thinking about data storage.

However—to help avoid future pain for others, and since H2 seems to be Very Bad for production anyway, I would humbly suggest flying a banner at the top of _every Metabase page_ that says:

`Your Metabase data is stored in H2. We recommend migrating to a reliable storage layer. (Link somewhere)`

This would be distracting and annoying to first-time users so I'd suggest making it appear after some threshold, like after a week of using Metabase, or after saving 10 questions.

It would have really saved Past Me's butt!

**Comment by flamber** [comment]
Closing in favor of #12695

**Comment by nfarina** [comment]
Ouch
