### ISSUE TITLE
Absence of translation for some parameters in visualisation parameters

### ISSUE THREAD

**Issue by Dynnammo** [metabase/metabase#27350]
**Describe the bug**
When wanting to choose how to visualize numbers (normal, scientific, percentage, or currency)
on a curve diagram, options aren't displayed in my language.

As far as I investigated, these are the lines that are implicated

https://github.com/metabase/metabase/blob/f8c734f9dd1acbcc75a88019c35c66d5516371c1/frontend/src/metabase/visualizations/lib/settings/column.js#L283-L286

**To Reproduce**
1. As a user, choose a non-english language for the frontend
2.  Create a curve diagramm
3. Go to Settings (bottom left) > Curve > Data
4. Click on the 3 dots for more parameters for the y-axis
5. Click on "Style"
6. See error

**Expected behavior**
Option of number display choice should be translatable. 

**Screenshots**
Below the pane displayed as a french user
![image](https://user-images.githubusercontent.com/33259633/208712865-75a268ea-d1af-444a-90b8-0e00631ac5cf.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Version 1.46.144 Chromium: 108.0.5359.128 
- Your operating system: Debian 12
- Your databases: Postgres
- Metabase version: 0.45.0
- Metabase hosting environment: Jar-file on Debian
- Metabase internal database: Postgres

**Severity**
Annoying, but certainly not critical

**Comment by npfitz** [comment]
Looks like this was addressed in https://github.com/metabase/metabase/pull/28526
