### ISSUE TITLE
Models aren't showing in recently viewed list of Search bar

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#27359]
**Is your feature request related to a problem? Please describe.**
When clicking on the Search bar on the top right, it shows a list of recently viewed tables, but not Metabase models. 

**Describe the solution you'd like**
As models are treated like tables, they should show where a table does. 

**Describe alternatives you've considered**
I have to search for the model again

**How important is this feature to you?**
Just convenience when switching between a few models

**Additional context**
n/a

**Comment by ranquild** [comment]
@maxzheng unable to reproduce, can you double check it again?

<img width="691" alt="Screenshot 2023-07-06 at 16 32 50" src="https://github.com/metabase/metabase/assets/8542534/101fc02a-011e-473f-8877-599acecf7809">
<img width="885" alt="Screenshot 2023-07-06 at 16 32 57" src="https://github.com/metabase/metabase/assets/8542534/13cc390f-5951-436e-a884-5a2ce4fdc755">

**Comment by iethree** [comment]
unable to reproduce. 

![Image](https://github.com/metabase/metabase/assets/30528226/ad6d33e1-2a24-4a5d-a179-4f2d7df723ba)
