### ISSUE TITLE
We should be smarter about marking State fields

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2735]
Currently, according to @tlrobinson, we're marking any field with a name of `State` as being a geographical state, even though many tables may have fields where `State` represents a qualitative or temporal state (like "Ready," "Approved," "Declined," etc.). 

A naïve thought would be to check the table for other indications that `State` refers to a location, like whether or not the table also includes a `City,` `Zip`, `Country`, etc.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mazameli** [comment]
Relevant code:
https://github.com/metabase/metabase/blob/master/src/metabase/models/field.clj#L180

**Comment by tlrobinson** [comment]
We could also look at the field's values to see if they match known state codes.

**Comment by salsakran** [comment]
yeah, I think "state" might be too broad a term to actually mark. Curious how often it's being mislabeled.

**Comment by imightbeamy** [comment]
Being smarter about this would be great 👍 Almost all my tables have a "state" that's not a location. Stuff like "Open", "Pending", "Completed", etc. I went through my important tables and changed their type to "Category", but for me, there are way more that are not locations than are locations.

**Comment by matstevenson** [comment]
Having this issue open helped clarify what that field is actually for.  It's definitely confusing as a new user!

More often then not (for us), `state` is an enum with values such as "active", "canceled", "pending" etc.

**Comment by mbvictoria** [comment]
The new summary view sort of exacerbates this issue, because when you try to summarize by State it automatically switches to a map visualization, which is a confusing experience.

**Comment by mazameli** [comment]
> The new summary view sort of exacerbates this issue, because when you try to summarize by State it automatically switches to a map visualization, which is a confusing experience.

This is a great point. It would be cool if we could address this in 0.33.1 or 0.34, @sbelak. Maybe we can sample the contents of the field to see if it contains e.g. `CA`, `NY`, etc. or if it contains `pass` `fail` `purchased` etc.

**Comment by nikolasrieble** [comment]
The simplest solution would just be to delete the line. 
As the other comments also mention, state being a location is the edge case and not the standard.  I have all sorts of states, not a single one is a location.
