### ISSUE TITLE
Dashboard parameter without field mapping have double borders

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#27365]
**Describe the bug**
When you add a dashboard parameter that will result in an input widget and don't map that filter to any card, there will be a rectangle border visible.

**To Reproduce**
1. Create a new dashboard
2. Add a "text contains" filter
3. Click the "Save" button
4. Click on the "text contains" filter

**Expected behavior**
There should be no rectangle border, only a rounded border.

**Screenshots**
<img width="381" alt="image" src="https://user-images.githubusercontent.com/1937582/208908009-84d5fa30-34eb-4143-8622-d716bcaa49d9.png">

**Information about your Metabase Installation:**
Metabase build commit 19a9693d2bbf9d6bf8a8d06d226331de24545db1 and also happens on Stats

**Additional context**
Found the screenshot in this PR https://github.com/metabase/metabase/pull/23418 which looks exactly like the problem I found.

**Comment by oleggromov** [comment]
The version this bug was reproduced on is `v0.45`
