### ISSUE TITLE
Document the supported versions of node/npm for developers

### ISSUE THREAD

**Issue by Mavlarn** [metabase/metabase#2736]
If this is a bug report, please fill in the blanks:
-  I am using the _____chrome______ browser.
-  My computer's OS is _____Mac OSX______.
-  I'm running Metabase ______master head_____. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is _____H2______.
-  My Metabase version is ___________.

I got the latest version of code and try to build the front end with npm as said in dev guide.  
When I run `npm run build` there is error starting with:

```
./metabase/~/css-loader?{"localIdentName":"[hash:base64:5]","restructuring":false,"compatibility":true,"importLoaders":1}!/Users/mavlarn/MyDev/learn/clojure/metabase/~/postcss-loader!./css/index.css
Module build failed: Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:337:15)
    ....
```

And same error when I run `npm run build-watch` too. 

My node version is 5.0.0 and npm 3.3.6.

**Comment by anki-code** [comment]
Try to look #2723

**Comment by Mavlarn** [comment]
It works, thanks.   
And, I am very interested in this project, is there any document about dev in deeps about this project?

**Comment by tlrobinson** [comment]
We do have some developer documentation, but it looks like we're not specifying the versions of node/npm we recommend. I'm going to change the title of this issue to suggest we do that.

* https://github.com/metabase/metabase/blob/master/docs/developers-guide.md
* https://github.com/metabase/metabase/blob/master/docs/developers-guide-osx.md
* https://github.com/metabase/metabase/blob/master/docs/contributing.md
* https://github.com/metabase/metabase/blob/master/docs/code-reviews.md

**Comment by tlrobinson** [comment]
Also I try to keep everyone on the `node` and `npm` versions listed in our `package.json`, so that's a good place to start. Currently:

```
    "node": "4.4.7",
    "npm": "2.15.9"
```

**Comment by paoliniluis** [comment]
Closing this as we have this already documented in https://github.com/metabase/metabase/blob/master/docs/developers-guide.md
