### ISSUE TITLE
Downloading a model doesn't respect viz settings 

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#27374]
**Describe the bug**
If you change the viz setting of the model after you saved it, then the downloads won't respect the viz setting config.

**Logs**
NA

**To Reproduce**
1) build a model (e.g. orders table), save it
2) change the model metadata, go to the subtotal column and multiply it by 0.01
3) now download the model, you'll see that it will not respect the viz setting

**Expected behavior**
Make the download respect the viz setting

**Screenshots**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.45.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P1'sh

**Additional context**
Comeback of https://github.com/metabase/metabase/issues/23017

**Comment by flamber** [comment]
When is this a regression from? Caused by how metadata is handled for Models (since v42), so it's getting the formatting from a different level (the Data Model, then global settings). Very related to #17753.
