### ISSUE TITLE
Doing "Zoom in" from dashboard drops fields from joined tables

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#27380]
**Describe the bug**
Doing "Zoom in" drill from dashboard drops fields from joined tables used in the group-by. This does not happen when using drag-to-zoom.

Possible workaround is to click the question title on the dashboard, or use drag-to-zoom on the dashboard.

**To Reproduce**
1. Question > Sample > Orders
2. Summarize Count grouped by **Products**.CreatedAt:Month (doesn't matter if Products is implicit or explicit joined).
3. Save question and add to dashboard
4. Click one of the line points and "Zoom in" - shows invalid chart (not a very helpful error) and looking in Notebook will show that it has dropped the group-by field.

https://user-images.githubusercontent.com/1447303/209137652-a4aaa6de-a293-49d7-acf4-675995ba35d3.mp4

**Information about your Metabase Installation:**
Tested 0.45.1

**Additional context**
Feels related to #23293

**Comment by nemanjaglumac** [comment]
The fix has been reverted. Reopening.
