### ISSUE TITLE
Pre-existing category filters were not migrated to new ones

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#27393]
**Describe the bug**
We seem to have forgotten migrating the old filters (<=41) in a dashboard to the new ones, as categorical filters that are inherited from old versions don't offer single/multi option in 45

**Logs**
NA

**To Reproduce**
1) spin up a 41 version
2) create a gui question (people table), save it
3) create a new dashboard and add the question
4) add a category filter, connect it with the source field
5) save the dashboard
6) move to 45.1, see that the filter won't offer the new options

![image](https://user-images.githubusercontent.com/1711649/209239934-b3c8c4fb-94ce-4ca0-beb9-86472a536f38.png)

**Expected behavior**
The filter should offer the new single/multi select options

**Screenshots**
NA

**Information about your Metabase Installation:**
- Metabase version: 41.5 and then 45.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2

**Additional context**
Reported by a customer

**Comment by tsmacdonald** [comment]
@paoliniluis I'm surely just misunderstanding something, but I can't repro this. I made a filter as described on 41, then I moved to 45 and the values are showing up okay:

![image](https://user-images.githubusercontent.com/784417/216067998-0f50d6fe-cd23-4072-a514-f9a904e1b417.png)


![image](https://user-images.githubusercontent.com/784417/216068416-cad1fc90-5d1b-4ae9-a58c-b1fa7abeb942.png)


![image](https://user-images.githubusercontent.com/784417/216068553-4a26b02d-40b4-43c4-8d38-c4a7a813a056.png)

**Comment by tsmacdonald** [comment]
I've reproed this locally, and have one parameter from 41 (id: `3fda3238`) and one parameter from 45 (id: `6a61940a`) like so:

```
 select parameters from report_dashboard;
                                                                           parameters                                                                           
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 [{"name":"Category","slug":"category","id":"3fda3238","type":"category"},{"name":"Text","slug":"text","id":"6a61940a","type":"string/=","sectionId":"string"}]
(1 row)
```

The issue is that the 41 parameter type (`category`) doesn't have a subtype. The code handling that was massively changed in commit `ead4844106e` in October 2022 and tbh I haven't looked into how it worked beforehand. Anyway, multi-select logic is now handled by this logic:

```typescript
// metabase/parameters/utils/parameter-type.ts
export function isSingleOrMultiSelectable(parameter: Parameter): boolean {
  const type: string = getParameterType(parameter);
  const subType: string = getParameterSubType(parameter);

  if (!SINGLE_OR_MULTI_SELECTABLE_TYPES[type]) {
    return false;
  }
  if (SINGLE_OR_MULTI_SELECTABLE_TYPES[type] === "any") {
    return true;
  }
  return SINGLE_OR_MULTI_SELECTABLE_TYPES[type].includes(subType);
}

// metabase-lib/parameters/constants.ts
export const SINGLE_OR_MULTI_SELECTABLE_TYPES: Record<
  string,
  string | string[]
> = {
  string: ["=", "!="],
  category: ["=", "!="],
  id: "any",
  location: ["=", "!="],
};
```

and so obviously with no subtype then `type: "category"` will be render as single-selectable.

There are cheeky fixes to this, such as:

```diff

diff --git a/frontend/src/metabase/parameters/utils/parameter-type.ts b/frontend/src/metabase/parameters/utils/parameter-type.ts
index 9d1642edf2..b1905c0f4b 100644
--- a/frontend/src/metabase/parameters/utils/parameter-type.ts
+++ b/frontend/src/metabase/parameters/utils/parameter-type.ts
@@ -12,7 +12,7 @@ export function isSingleOrMultiSelectable(parameter: Parameter): boolean {
   if (!SINGLE_OR_MULTI_SELECTABLE_TYPES[type]) {
     return false;
   }
-  if (SINGLE_OR_MULTI_SELECTABLE_TYPES[type] === "any") {
+  if (SINGLE_OR_MULTI_SELECTABLE_TYPES[type] === "any" || !subType) {
     return true;
   }
   return SINGLE_OR_MULTI_SELECTABLE_TYPES[type].includes(subType);
```

but I'm sure that has unforeseen consequences. Any FE folks want to chime in?

**Comment by tsmacdonald** [comment]
Will be fixed in 46 and the next 45 point release
