### ISSUE TITLE
Handle non-integer values consistently for all scalar visualizations

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#27395]
**Describe the bug**
Handle non-integer values consistently for all scalar visualizations

**To Reproduce**
1. Example use the following query to see types like `NaN` or `Infinity` or `null`
```
select case
  when {{type}}='0' then 0
  when {{type}}='1' then 1
  when {{type}}='null' then null
  when {{type}}='infinity' then 'Infinity'::real
  when {{type}}='nan' then 'NaN'::real
  end as val
from dual
where 1 = case when {{type}}='nothing' then 0 else 1 end
```

https://user-images.githubusercontent.com/1447303/209827694-caddad51-724a-4d00-8ac4-519bff6b6a3a.mp4

**Expected behavior**
Handle non-integer values consistently for all scalar visualizations. Currently the Number visualizations seems like the most correct one, where the Process Bar is most wrong.

**Information about your Metabase Installation:**
Tested 0.45.1

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by iethree** [comment]
@cdeweyx I'm not 100% sure what we expect to see in these cases. Here's my best guess. can you confirm/correct?

  | number | gauge | progress
-- | -- | -- | --
0 | 0 | 0 | 0
null | null | 0 | 0
NaN | NaN | 0 | 0
infinity | infinity | max? | max?

**Comment by cdeweyx** [comment]
@iethree Agreed with the matrix above. Personally I think the giant null isn't too bad, at the very least it's super clear what's going on.
