### ISSUE TITLE
Bar Chart - Having more than 2 Y-Axis showing incorrect chart

### ISSUE THREAD

**Issue by ShirishPatel** [metabase/metabase#27421]
Please use the issue chooser, when creating a new issue:

https://github.com/metabase/metabase/issues/new/choose

Bar Chart - Having more than 2 Y-Axis showing incorrect chart

Please see the screenshot attached
![Bar Chart Issue](https://user-images.githubusercontent.com/11343680/209532155-441b9560-bdab-493b-97cb-da5556938027.png)

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
