### ISSUE TITLE
Unable to Find Custom Filter v0.44.2

### ISSUE THREAD

**Issue by jyk4100** [metabase/metabase#27430]
I cannot find option to add custom filter for a question on a summarize UI since v0.44.2 update

I need to visualize a table with many dimensions into groups of dimensions and customer filter was very useful for this but it is not to be found anywhere? Has custom filter been dropped in v0.44.2?

**Comment by flamber** [comment]
Upgrade to a newer release: https://github.com/metabase/metabase/releases/latest
And please use the forum for questions and troubleshooting: https://discourse.metabase.com/
