### ISSUE TITLE
Cannot select fields for double aggregated metrics, and existing sections gets removed on change

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#27462]
**Describe the bug**
It's not possible to select fields for double aggregation, and existing questions will drop the double aggregation metrics on modification.
Regression since 0.45.0

**To Reproduce**
1. Question > Sample > Products
2. Summarize Count by Category
3. Double aggregation summarize, try selecting Sum of Count, no metrics will be available
![image](https://user-images.githubusercontent.com/1447303/209953672-9a3e3897-8f26-441f-995a-936c282b4791.png)

For already existing questions, just viewing the question will show several browser console logs `Removing invalid MBQL clause 
Array [ "sum", (3) […] ]`, and making question changes (example add sort or changing a filter) will drop the second summarize section.
Note, for the existing test question, there's 15 `Warning: can't clean query without metadata!` in 44.6, while there's only a single in 45.1, which seems to indicate that there's too much cleanup going on in the frontend.

**Information about your Metabase Installation:**
Tested 0.44.6 thru 0.45.1. Regression since 0.45.0

Seems related to #24839, as it causes the same problem.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by WiNloSt** [comment]
This commit 223708bd7bc5726f65a5e20e099e2d9d0f3663bf caused the error. I'll continue investigating tomorrow.
