### ISSUE TITLE
The user geojson is not working properly

### ISSUE THREAD

**Issue by stm32repo** [metabase/metabase#27477]
The map is strongly shifted to the right. Only a small piece is visible. It's like the center is in the US even though I uploaded a map of Russia.

Metabase: v.045.1, Browser: chrome
java.runtime.version: "11.0.16+8-post-Debian-1deb11u1"
![image](https://user-images.githubusercontent.com/38454920/210172531-bf3400c2-131e-4cf7-a609-984ae1c15b7c.png)

**Comment by flamber** [comment]
Duplicate of #26213
