### ISSUE TITLE
field filter cause SQL error db clickhouse

### ISSUE THREAD

**Issue by IraRedRose** [metabase/metabase#27472]
When I do all the same but filter type 'text' it works. When I change to 'field filter' and choose from table column same value I get error.
SQL query is simle, no subquery, no alias. Why it is trying to convert string?
Error:
Code: 53. DB::Exception: Cannot convert string 01.12.2020 К-2 to type UInt8: while executing 'FUNCTION equals(equals(activity_name, activity_name) : 16, '01.12.2020 К-2' : 15) -> equals(equals(activity_name, activity_name), '01.12.2020 К-2') UInt8 : 17'. (TYPE_MISMATCH) (version 22.11.2.30 (official build)) .

**Comment by flamber** [comment]
Use the driver repo to report issues specific to a driver: https://github.com/enqueue/metabase-clickhouse-driver
