### ISSUE TITLE
Metabase exit 139 with docker image metabase/metabase:v0.45.1

### ISSUE THREAD

**Issue by sebglon** [metabase/metabase#27470]
**Describe the bug**
We have a metabase crash with exit code 139 multiple time per day

**Logs**
[Log export.csv](https://github.com/metabase/metabase/files/10323932/Untitled.discover.search.csv)

<img width="1727" alt="Capture d’écran 2022-12-30 à 10 43 17" src="https://user-images.githubusercontent.com/3148666/210056397-b6855d67-2be4-47b7-b24d-5e9ddb883d64.png">

**To Reproduce**
We have no idea about the why

**Expected behavior**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your operating system: Docker on kubernetes
- Your databases: POstgres
- Metabase version: 0.45.1
- Metabase hosting environment: docker
- Metabase internal database: postgres

**Severity**
We use metabase to have a realtime app monitoring on the business to manage our 24/7 operator team.

**Comment by flamber** [comment]
Hi @sebglon 

Seems like the problems occurs when loading dashboard 81
`"Dec 30, 2022 @ 09:59:38.900","-","2022-12-30 08:59:38,900 DEBUG middleware.log :: [32mGET /api/dashboard/81 null 3.1 mins (32 DB calls) App DB connections: 6/15 Jetty threads: 50/50 (0 idle, 37 queued) (206 total active threads) Queries in flight: 1 (0 queued)[0m","-","metabase-944d7d675-8mmq6"`

Which then causes all Jetty threads to be consumed, which means that there isn't available thread for the `/api/health` health check, which causes your Kubernetes setup to restart the instance.

I cannot tell what is happening with that dashboard, perhaps there's a loop somewhere.

**Comment by sebglon** [comment]
We refresh this dahboard every hour without issue. And i try to understand why sometime it crash.
All our restart are not related to this specific dashboard

**Comment by flamber** [comment]
@sebglon Okay, the log you have provided is specifically #26666.
I'm guessing that you are unfolding JSON, which can cause #25331, which can the cause #26266.
