### ISSUE TITLE
Snowflake overwhelming log output

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#27484]
Not a bug per se, but my terminal is drowning in logs 

> 2023-01-03 15:28:04,710 WARN jdbc.SnowflakeConnectString :: Connect strings must start with jdbc:snowflake://
2023-01-03 15:28:05,725 WARN jdbc.SnowflakeConnectString :: Connect strings must start with jdbc:snowflake://

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/6377293/210388224-791538bd-812c-4c7c-adb0-35dfd0006a98.png">

Strangest bit is that I do not have a snowflake db connected:
```sql
clean=# select engine, count(*) from metabase_database group by engine;
  engine  | count
----------+-------
 postgres |     1
 h2       |     2
(2 rows)
```

**Comment by dpsutton** [comment]
follow up. I was trying to git bisect and ran into checksum issues. I dropped by app db to carry on and the issue seems to have gone away. Confusing because I did not have any snowflake dbs before the drop though.

**Comment by flamber** [comment]
I've never seen this error before, coming from [upstream driver](https://github.com/snowflakedb/snowflake-jdbc/blob/master/src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java#L39). Since it seems to have been resolved by new appdb, then it might just have been something in your build/setup. Closing for now.

**Comment by flamber** [comment]
I'm seeing this on master with one of my instances, which has a Snowflake connection.

**Comment by luizarakaki** [comment]
I'm seeing this on 46.0. I have a Snowflake db connected.

![image](https://user-images.githubusercontent.com/32561114/228241615-8105e0c1-c08b-4866-8e49-04c727c32cd7.png)

**Comment by camsaul** [comment]
95% sure this is an upstream bug in the Snowflake driver.

The way the JDBC `DriverManager` works is you pass in a connection string like `jdbc:postgresql://...` and then it asks all the registered drivers whether they can handle that connection string, and then they're supposed to just return false so it can try the next driver, but Snowflake is being dumb and logging an error in this situation. 

It looks like they changed this from WARN to DEBUG 2 weeks ago in https://github.com/snowflakedb/snowflake-jdbc/pull/1313, so maybe all we need to do is bump our dep version.

**Comment by camsaul** [comment]
Oh, this is the upstream bug https://github.com/snowflakedb/snowflake-jdbc/issues/1268

**Comment by luizarakaki** [comment]
Good, thanks for the investigation. I'll keep an eye on the snowflake repo and we can bump when they release a new version
