### ISSUE TITLE
x-axis label needs more space above it when there's only one x value

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2748]
On both stats.mb as well as proto.mb, if there's only a single x point on the axis (like if you group by year, and all the values are contained within one year), then the x-axis label is too close to the chart. This is particularly noticeable with bar charts:

![screen shot 2016-06-13 at 3 17 04 pm](https://cloud.githubusercontent.com/assets/2223916/16025123/5e939ff8-317a-11e6-8c5b-787c86ffa803.png)

**Comment by kdoh** [comment]
No longer able to reproduce this.
