### ISSUE TITLE
Support PrestoDB

### ISSUE THREAD

**Issue by vineet-rh** [metabase/metabase#2749]
Support Facebook's [PrestoDB](https://prestodb.io/). This can currently be supported using a workaround by using Prestogres (https://github.com/treasure-data/prestogres) and treating the presto db as a postgresql db, but would be nice to have direct support for presto.

**Comment by salsakran** [comment]
@vineet-robinhood are you using Metabase and/or Presto in production?

**Comment by yank1** [comment]
+1

**Comment by camsaul** [comment]
Hi @vineet-rh and @yank1, we're adding support for various DBs based on community demand. Since you're the only people who've asked for PrestoDB thus far, that might be a while 😉 

If you're feeling adventurous you can try [writing a driver yourself](https://github.com/metabase/metabase/wiki/Writing-A-Driver). I'm available to help with any questions you might run into.

**Comment by damiencarol** [comment]
@camsaul we are using PrestoDB in production. want to test it with Metabase without success

**Comment by jwills** [comment]
We're testing out metabase at Slack, and we are heavy users of Presto. Would love official support for it.

**Comment by salsakran** [comment]
@jwills do you have access to a presto test cluster? Would you (or anyone else on this issue) be able to help us?

**Comment by jwills** [comment]
I have access to our prod Presto clusters; what sort of assistance do you need?

**Comment by salsakran** [comment]
all kinds of help =)

to get orientated, check out https://github.com/metabase/metabase/wiki/Writing-A-Driver and https://github.com/metabase/metabase/blob/master/src/metabase/driver/mysql.clj

we'd need help wiring up a test cluster for CI. We also tend to have all kinds of questions regarding how the specific sql dialect deals with types, times and introspection.

**Comment by laloyd** [comment]
@vineet-rh  I keep getting an error :  
    ERROR:  Parse: Prestogres doesn't support extended query    
when trying to connect to prestogres from metabase via the addDatabase admin.  Did you have to work around that error ?  What version of metabase/postgres are you using?

**Comment by wwwiiilll** [comment]
I've actually started working on this a little while ago, however I was counting on the JDBC driver to ease this out, but prestodb/presto#6158 kinda got in the way.

So now I'm in a dilemma between waiting for the feature in the upstream driver or rewriting this similarly to the BigQuery driver by using the client library directly.

Should I open the PR now or do I wait until I know how I'm addressing this?

**Comment by futurekill** [comment]
This is something I would love to see implemented. Currently we're trying to work around the absence of a presto connector by using prestogres but it's not working so out so well.

**Comment by davidmann4** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.
