### ISSUE TITLE
Document MB_MAX_RESULTS_BARE_ROWS

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#27491]
Just going through the code I found that 
https://github.com/metabase/metabase/blob/d2f10e9ff4c498d7cff361996a3433020647fd18/src/metabase/query_processor/middleware/constraints.clj#L13

is not documented while being ultra important (at least for me that I lower the number to make Metabase UI faster!)

**Comment by jeff-bruemmer** [comment]
Closing: see https://github.com/metabase/metabase/pull/27507
