### ISSUE TITLE
Column settings are duplicated when fields have the same id-or-name, but different join-alias

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#27504]
If you change any settings in a card's `visualization_settings.column_settings` JSON map (e.g. a column title) all columns with the same field ref excluding the join-alias will update. This means two columns with the same field ID but from different joins get their settings updated together.

This is what causes part 1 of https://github.com/metabase/metabase/issues/12685, and part 4 of https://github.com/metabase/metabase/issues/27494

Here's a minimal example:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/39073188/210610768-2d0bfc87-f437-4f31-9e25-220c5565349d.png">

Changing any of the settings shown in the popup below for the "Orders -> Total" column will update the "Total" column too, when should only update the "Orders -> Total" column.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/39073188/210610712-b19964c6-eb77-4e9b-8462-70b9982987b8.png">

**Comment by calherries** [comment]
cc @flamber This is overlaps with https://github.com/metabase/metabase/issues/12685 and https://github.com/metabase/metabase/issues/27494, but targets a common underlying cause with both of them

**Comment by camsaul** [comment]
@calherries if you're working on #27494 please make sure to assign yourself to it so someone else doesn't try to pick it up. I almost started working on it today before I realized this PR targets it
