### ISSUE TITLE
Attach card ids to dataset query executions

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2750]
For things like #609, and #2743 it would be very useful to be able to link a card to its executions.

**Comment by tlrobinson** [comment]
Possibly also the associated dashboard.

**Comment by camsaul** [comment]
`card_id` would be pretty simple because we're already passing it to the Query Processor for checking permissions (if the Card is in a Collection). All we'd need to do is add a column to QueryExecution and start recording the ID

**Comment by camsaul** [comment]
Implemented by #4351
