### ISSUE TITLE
Add Kondo linter to disallow `println` (instead of `log/`)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#27511]
You're always supposed to use stuff like `log/info` so we can configure it (e.g. disable it, especially in tests) -- but currently this is a rule that you just have to know (and PR reviewers have to catch it if you didn't know the rule). This is something we can easily have Kondo enforce for us. 

Not sure if this should only apply to `src` and the like and not apply to `test/`, or if there are good reasons to be doing `println` in tests (I think maybe we're currently doing it for some test runner init messages?) but we can always add`#{:clj-kondo/ignore ...}` in places where we have legitimate reasons to use it.

If we decide it should only apply to non-test directories we can create a namespace group in Kondo and only apply it to certain namespaces.

More ideas: maybe we should also make sure error messages inside `ex-info` and the like are i18n'ed; or messages inside `log/` statements higher than the `:debug` level are i18n'ed with `trs` (the site locale). Writing linters for these rules would be a little more complicated since we'd probably have to write a custom hook but it would be nice if Kondo could catch this rather than people having to know or PR reviewers having to look out for it

Related: #27250

**Comment by markbastian** [comment]
Should this apply to the `src/metabase/cmd/*` family of functions? That seems to be the main location `println` is used.

**Comment by markbastian** [comment]
Would it make sense to split this into two tickets? The second one being:

> More ideas: maybe we should also make sure error messages inside ex-info and the like are i18n'ed; or messages inside log/ statements higher than the :debug level are i18n'ed with trs (the site locale). Writing linters for these rules would be a little more complicated since we'd probably have to write a custom hook but it would be nice if Kondo could catch this rather than people having to know or PR reviewers having to look out for it

**Comment by markbastian** [comment]
Created #27998 to split this into two tickets.
