### ISSUE TITLE
Calendar icon in breakout picker is off-position

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#27523]
**To Reproduce**

1. `+ New`
2. Question
3. Sample Database
4. Orders
5. Join to Products
6. Summarize with Count to Created At: Month and Products → Category
7. Visualize
8. Open View All Time dropdown
9. Choose `On`

<img src=https://user-images.githubusercontent.com/380816/210811728-9f29a71b-42ff-4a52-8c3d-fe3ac787a461.png width=600 />

**Comment by flamber** [comment]
Likely caused by #27242

**Comment by uladzimirdev** [comment]
after https://github.com/metabase/metabase/pull/34191 we started using Mantine's DateInput, which doesn't have an icon in the input.
