### ISSUE TITLE
Make Athena CI test data/loading more robust

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#27534]
With the normal S3 data store we can't delete data from Athena itself, so if data gets loaded more than once things are completely broken.

We need to put some code in our Athena test extensions to make sure it doesn't load duplicate data -- somehow this happened today and broke CI. Or maybe just put some logic in there to check that the test data is the right size and create something new if it's not.

Can we delete test data by hitting AWS directly automatically? (S3 bucket and Glue Console)

**Comment by paoliniluis** [comment]
There's an action to configure credentials:
https://github.com/aws-actions/configure-aws-credentials

and also AWS CLI is installed on ubuntu runner images, you can make a call with the CLI and wipe the bucket if needed (be careful about parallel runs)

**Comment by camsaul** [comment]
Yup, wouldn't want to do that on every run because it's super slow to load all the data again and it would break parallel runs
