### ISSUE TITLE
Admin checklist should correctly check off the "Organize Questions" item

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2753]
On Proto:

The new admin checklist feature is rad, but it's telling me I should create labels…

![screen shot 2016-06-13 at 5 34 21 pm](https://cloud.githubusercontent.com/assets/2223916/16027723/27502c10-318d-11e6-8b6c-55d3724a8ac5.png)

…even though I already have a ton of them:

![screen shot 2016-06-13 at 5 34 31 pm](https://cloud.githubusercontent.com/assets/2223916/16027726/2f3ba918-318d-11e6-90b5-6e10e9af3635.png)

I tried creating a new label to see if it would clear out the tip, but it didn't.

![screen shot 2016-06-13 at 5 37 20 pm](https://cloud.githubusercontent.com/assets/2223916/16027764/82cbbece-318d-11e6-9436-1e21712d1948.png)

**Comment by tlrobinson** [comment]
We've also got a TODO in one of the descriptions: https://github.com/metabase/metabase/blob/master/src/metabase/api/setup.clj#L107

**Comment by camsaul** [comment]
Also we have the checklist item for making a getting started guide but there is no way to do that yet 😰
