### ISSUE TITLE
Static viz does not respect the pie chart color

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#27547]
**Describe the bug**
We fixed all colors in https://github.com/metabase/metabase/pull/26211, but pie charts

**To Reproduce**
1) Build a question like Orders->Sum of quantity per created_at (month), make a pie chart
2) Add the question to a dashboard, and then do a subscription with it, send a test email.
3) see the pie chart with different colors

**Expected behavior**
Reproduce the same colors in the pie chart

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/211028052-343e1f0b-2bfb-4b85-86a1-bccd19f69537.png)

**Information about your Metabase Installation:**
- Metabase version: 1.45.1

**Severity**
Cosmetic

**Additional context**

How to solve:
Instead of passing `legendColors` to JS donut rendering function provide instance colors (example: waterfall chart). This will make `getColor` prop function return the right instance colors even for EE with reconfigured color settings. Similarly, provide the overridden colors from viz settings. At this point, the static pie chart js code has everything needed to pick the correct segment colors.
After that, implement the pie chart legend in JS instead of the current one in clojure just to make it use the right colors. Use `frontend/src/metabase/static-viz/components/Legend/Legend.tsx` component to do so.

**Comment by gusaiani** [comment]
For a technical discussion about this: https://metaboat.slack.com/archives/C04D0E4837E/p1673315927263989?thread_ts=1673307602.409799&cid=C04D0E4837E
