### ISSUE TITLE
Grouping by custom convertTimezone date column doesn't work

### ISSUE THREAD

**Issue by mnort9** [metabase/metabase#27549]
**Describe the bug**
When using convertTimezone in a custom column and grouping by that column by day/month/etc (see screenshots), the result is not grouped. It looks like there isn't a grouping function being generated in the sql: 

```
SELECT "source"."Created At EST" AS "Created At EST", count(*) AS "count"
FROM (SELECT timezone('America/New_York', timezone('UTC', "public"."leads"."created_at")) AS "Created At EST" FROM "public"."leads") "source"
GROUP BY "source"."Created At EST"
ORDER BY "source"."Created At EST" ASC
```

**Screenshots**
<img width="725" alt="Screen Shot 2023-01-06 at 9 20 44 AM" src="https://user-images.githubusercontent.com/1610579/211030475-dc09aacd-6f05-4be6-93cd-553f4f8b4e59.png">

<img width="742" alt="Screen Shot 2023-01-06 at 9 13 19 AM" src="https://user-images.githubusercontent.com/1610579/211030605-92bd2746-9b11-4492-8bd4-e0323657a6bb.png">

Metabase v0.45.0 & Postgres

**Comment by flamber** [comment]
Binning/granularity/bucketing options does not currently work on Custom Columns, #11371, but it seems like we might have introduced a bug in the frontend showing this as an option.

**Comment by snoe** [comment]
Tested here:
https://github.com/metabase/metabase/blob/master/test/metabase/lib/temporal_bucket_test.cljc#L161-L167
