### ISSUE TITLE
We should put dashboard descriptions in a tooltip

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2755]
In an effort to save space and clean up the UI, I'm proposing we should hide dashboard descriptions in a tooltip when viewing a dashboard. Many of our users barely use descriptions, and if they do use them, they tend to be fewer than a dozen words long.

Here's a height comparison between what's currently in the product vs. what the design proposes:

![comparison](https://cloud.githubusercontent.com/assets/2223916/16053561/363e06b6-321e-11e6-8fe9-56e037d711e8.png)

If there isn't a dashboard description, then no tooltip appears next to the dashboard name:

![start](https://cloud.githubusercontent.com/assets/2223916/16053570/3d2cac02-321e-11e6-9423-7a80e8234491.png)

Let's edit the dashboard…

![no description yet](https://cloud.githubusercontent.com/assets/2223916/16053603/55d40df4-321e-11e6-9e2a-4c6b97f5b438.png)

…and add a description:

![added description](https://cloud.githubusercontent.com/assets/2223916/16053609/5a4b00cc-321e-11e6-97bb-5374902169fc.png)

Now a tooltip appears next to the dashboard's name:

![description added](https://cloud.githubusercontent.com/assets/2223916/16053612/5ee08c4c-321e-11e6-918d-6229ae75b50a.png)

And hovering over it displays the description:

![dashboard tooltip](https://cloud.githubusercontent.com/assets/2223916/16053622/67c29382-321e-11e6-8099-07bf09b884a8.png)

**Comment by agilliland** [comment]
On a separate but similar note, I believe the same could apply to Questions in the QB as well.
