### ISSUE TITLE
Mysql query with where in not working 

### ISSUE THREAD

**Issue by sadeghtkd** [metabase/metabase#27565]
Hi,
this MySql query not working in Metabase but when I replace the field filter variable with raw data it works:

```
SELECT domain,createDate,sum(count) as count from (
SELECT domain,createDate,count FROM `nsinsight` WHERE domain in ({{domains}}) and tld='com'
union 
SELECT domain,createDate,count(*) as count FROM `nsinsight` WHERE domain in ({{domains}}) and tld!='com' group by domain,createDate
) ggg group by domain,createDate having sum(count) > 10
```

**Logs**

> {:database_id 34,
>  :started_at #t "2023-01-09T10:52:49.230814Z[GMT]",
>  :via
>  [{:status :failed,
>    :class clojure.lang.ExceptionInfo,
>    :error "Error executing query: (conn=6151) Query execution was interrupted",
>    :stacktrace
>    ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__56023.invoke(execute.clj:501)"
>     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"
>     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
>     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:493)"
>     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
>     "driver.sql_jdbc$fn__88395.invokeStatic(sql_jdbc.clj:58)"
>     "driver.sql_jdbc$fn__88395.invoke(sql_jdbc.clj:56)"
>     "query_processor.context$executef.invokeStatic(context.clj:59)"
>     "query_processor.context$executef.invoke(context.clj:48)"
>     "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
>     "query_processor.context.default$default_runf.invoke(default.clj:65)"
>     "query_processor.context$runf.invokeStatic(context.clj:45)"
>     "query_processor.context$runf.invoke(context.clj:39)"
>     "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
>     "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
>     "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___53529.invoke(cache.clj:220)"
>     "query_processor.middleware.permissions$check_query_permissions$fn__49184.invoke(permissions.clj:109)"
>     "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__52474.invoke(mbql_to_native.clj:23)"
>     "query_processor$fn__55005$combined_post_process__55010$combined_post_process_STAR___55011.invoke(query_processor.clj:212)"
>     "query_processor$fn__55005$combined_pre_process__55006$combined_pre_process_STAR___55007.invoke(query_processor.clj:209)"
>     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450$fn__53455.invoke(resolve_database_and_driver.clj:35)"
>     "driver$do_with_driver.invokeStatic(driver.clj:76)"
>     "driver$do_with_driver.invoke(driver.clj:72)"
>     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450.invoke(resolve_database_and_driver.clj:34)"
>     "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49450.invoke(fetch_source_query.clj:314)"
>     "query_processor.middleware.store$initialize_store$fn__49640$fn__49641.invoke(store.clj:11)"
>     "query_processor.store$do_with_store.invokeStatic(store.clj:45)"
>     "query_processor.store$do_with_store.invoke(store.clj:39)"
>     "query_processor.middleware.store$initialize_store$fn__49640.invoke(store.clj:10)"
>     "query_processor.middleware.normalize_query$normalize$fn__53722.invoke(normalize_query.clj:22)"
>     "query_processor.middleware.constraints$add_default_userland_constraints$fn__50728.invoke(constraints.clj:53)"
>     "query_processor.middleware.process_userland_query$process_userland_query$fn__53661.invoke(process_userland_query.clj:145)"
>     "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54033.invoke(catch_exceptions.clj:167)"
>     "query_processor.reducible$async_qp$qp_STAR___45482$thunk__45484.invoke(reducible.clj:100)"
>     "query_processor.reducible$async_qp$qp_STAR___45482.invoke(reducible.clj:106)"
>     "query_processor.reducible$async_qp$qp_STAR___45482.invoke(reducible.clj:91)"
>     "query_processor.reducible$sync_qp$qp_STAR___45493.doInvoke(reducible.clj:126)"
>     "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"
>     "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"
>     "query_processor$fn__55052$process_query_and_save_execution_BANG___55061$fn__55064.invoke(query_processor.clj:342)"
>     "query_processor$fn__55052$process_query_and_save_execution_BANG___55061.invoke(query_processor.clj:335)"
>     "query_processor$fn__55096$process_query_and_save_with_max_results_constraints_BANG___55105$fn__55108.invoke(query_processor.clj:354)"
>     "query_processor$fn__55096$process_query_and_save_with_max_results_constraints_BANG___55105.invoke(query_processor.clj:347)"
>     "api.dataset$run_query_async$fn__70403.invoke(dataset.clj:69)"
>     "query_processor.streaming$streaming_response_STAR_$fn__40578$fn__40579.invoke(streaming.clj:162)"
>     "query_processor.streaming$streaming_response_STAR_$fn__40578.invoke(streaming.clj:161)"
>     "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
>     "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
>     "async.streaming_response$do_f_async$task__20017.invoke(streaming_response.clj:84)"],
>    :error_type :invalid-query,
>    :ex-data
>    {:sql
>     "-- Metabase:: userID: 1 queryType: native queryHash: 7220c7b868d4682601c49aac738ab1a8672a5800982336ee342996451bfb7c7a\nSELECT domain,createDate,sum(count) as count from (\nSELECT domain,createDate,count FROM `nsinsight` WHERE domain in (`nsinsight`.`domain` = ?) and tld='com'\nunion \nSELECT domain,createDate,count(*) as count FROM `nsinsight` WHERE domain in (`nsinsight`.`domain` = ?) and tld!='com' group by domain,createDate\n) ggg group by domain,createDate having sum(count) > 10",
>     :params ["f95.com" "f95.com"],
>     :type :invalid-query}}],
>  :state "70100",
>  :error_type :invalid-query,
>  :json_query
>  {:database 34,
>   :native
>   {:template-tags
>    {:domains
>     {:id "55bbed88-099e-2900-e775-ba0c28af5570",
>      :name "domains",
>      :display-name "Domains",
>      :type "dimension",
>      :dimension ["field" 7315 nil],
>      :widget-type "string/=",
>      :default ["f95.com"]}},
>    :query
>    "SELECT domain,createDate,sum(count) as count from (\nSELECT domain,createDate,count FROM `nsinsight` WHERE domain in ({{domains}}) and tld='com'\nunion \nSELECT domain,createDate,count(*) as count FROM `nsinsight` WHERE domain in ({{domains}}) and tld!='com' group by domain,createDate\n) ggg group by domain,createDate having sum(count) > 10"},
>   :type "native",
>   :parameters [],
>   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
>  :status :failed,
>  :class java.sql.SQLTimeoutException,
>  :stacktrace
>  ["org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:47)"
>   "org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)"
>   "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)"
>   "org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)"
>   "org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)"
>   "org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)"
>   "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)"
>   "--> driver.sql_jdbc.execute$fn__55941.invokeStatic(execute.clj:362)"
>   "driver.sql_jdbc.execute$fn__55941.invoke(execute.clj:360)"
>   "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:375)"
>   "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:371)"
>   "driver.sql_jdbc.execute$execute_reducible_query$fn__56023.invoke(execute.clj:499)"
>   "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"
>   "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
>   "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:493)"
>   "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
>   "driver.sql_jdbc$fn__88395.invokeStatic(sql_jdbc.clj:58)"
>   "driver.sql_jdbc$fn__88395.invoke(sql_jdbc.clj:56)"
>   "query_processor.context$executef.invokeStatic(context.clj:59)"
>   "query_processor.context$executef.invoke(context.clj:48)"
>   "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
>   "query_processor.context.default$default_runf.invoke(default.clj:65)"
>   "query_processor.context$runf.invokeStatic(context.clj:45)"
>   "query_processor.context$runf.invoke(context.clj:39)"
>   "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
>   "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
>   "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___53529.invoke(cache.clj:220)"
>   "query_processor.middleware.permissions$check_query_permissions$fn__49184.invoke(permissions.clj:109)"
>   "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__52474.invoke(mbql_to_native.clj:23)"
>   "query_processor$fn__55005$combined_post_process__55010$combined_post_process_STAR___55011.invoke(query_processor.clj:212)"
>   "query_processor$fn__55005$combined_pre_process__55006$combined_pre_process_STAR___55007.invoke(query_processor.clj:209)"
>   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450$fn__53455.invoke(resolve_database_and_driver.clj:35)"
>   "driver$do_with_driver.invokeStatic(driver.clj:76)"
>   "driver$do_with_driver.invoke(driver.clj:72)"
>   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450.invoke(resolve_database_and_driver.clj:34)"
>   "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49450.invoke(fetch_source_query.clj:314)"
>   "query_processor.middleware.store$initialize_store$fn__49640$fn__49641.invoke(store.clj:11)"
>   "query_processor.store$do_with_store.invokeStatic(store.clj:45)"
>   "query_processor.store$do_with_store.invoke(store.clj:39)"
>   "query_processor.middleware.store$initialize_store$fn__49640.invoke(store.clj:10)"
>   "query_processor.middleware.normalize_query$normalize$fn__53722.invoke(normalize_query.clj:22)"
>   "query_processor.middleware.constraints$add_default_userland_constraints$fn__50728.invoke(constraints.clj:53)"
>   "query_processor.middleware.process_userland_query$process_userland_query$fn__53661.invoke(process_userland_query.clj:145)"
>   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54033.invoke(catch_exceptions.clj:167)"
>   "query_processor.reducible$async_qp$qp_STAR___45482$thunk__45484.invoke(reducible.clj:100)"
>   "query_processor.reducible$async_qp$qp_STAR___45482.invoke(reducible.clj:106)"
>   "query_processor.reducible$async_qp$qp_STAR___45482.invoke(reducible.clj:91)"
>   "query_processor.reducible$sync_qp$qp_STAR___45493.doInvoke(reducible.clj:126)"
>   "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"
>   "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"
>   "query_processor$fn__55052$process_query_and_save_execution_BANG___55061$fn__55064.invoke(query_processor.clj:342)"
>   "query_processor$fn__55052$process_query_and_save_execution_BANG___55061.invoke(query_processor.clj:335)"
>   "query_processor$fn__55096$process_query_and_save_with_max_results_constraints_BANG___55105$fn__55108.invoke(query_processor.clj:354)"
>   "query_processor$fn__55096$process_query_and_save_with_max_results_constraints_BANG___55105.invoke(query_processor.clj:347)"
>   "api.dataset$run_query_async$fn__70403.invoke(dataset.clj:69)"
>   "query_processor.streaming$streaming_response_STAR_$fn__40578$fn__40579.invoke(streaming.clj:162)"
>   "query_processor.streaming$streaming_response_STAR_$fn__40578.invoke(streaming.clj:161)"
>   "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
>   "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
>   "async.streaming_response$do_f_async$task__20017.invoke(streaming_response.clj:84)"],
>  :card_id nil,
>  :context :ad-hoc,
>  :error "(conn=6151) Query execution was interrupted",
>  :row_count 0,
>  :running_time 0,
>  :data {:rows [], :cols []}}
> 

![image](https://user-images.githubusercontent.com/5601781/211294274-41ed99b9-7f99-4c6b-aa3b-cf555f8d8aed.png)

Please Help me to resolve the problem.

**Comment by flamber** [comment]
The query is timing out on the database. Optimize your query.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by flamber** [comment]
@sadeghtkd You are using a Field Filter instead of a Text - please read this to understand the syntax difference: https://www.metabase.com/learn/sql-questions/field-filters

**Comment by sadeghtkd** [comment]
Thank you.
You were right the correct syntax for Field Filter is this : 
`Where {{domain}}`
No need to use the IN keyword.
