### ISSUE TITLE
SAML group mapping not working for Admin group only

### ISSUE THREAD

**Issue by liapengpony** [metabase/metabase#27564]
**Describe the bug**
SAML group mapping is not working for Admin group only. It works for all other user groups.

We connected Metabase to Keycloak as an IDP using SAML protocol. We manage group memberships on Keycloak, and configured group mapping on Metabase. The group mapping works for all other groups except for the Admin group.

**To Reproduce**
1. Go to 'Admin Settings'
2. Go to 'Authentication'
3. Go to 'SAML'
4. Enable and edit mappings
5. Add mapping to 'Admin' group
6. Re-login Metabase with an new admin account

**Expected behavior**
Logged in as Metabase admin.

**Severity**
Non-blocking issue.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "5.4.0-45-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "sparksql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-10",
      "tag": "v1.41.4",
      "branch": "release-x.41.4",
      "hash": "471cfb9"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @liapengpony 
Please use the support email when using the Pro/Enterprise plans.
Upgrade to a newer release, https://github.com/metabase/metabase/releases/latest, this was fixed in v43: #13820
