### ISSUE TITLE
Selecting Exclude Hours of the day from Date Filter doesn't give the option to deselect 12:00 am

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#27579]
**Describe the bug**
When you choose Exclude -> Hours of the day the 12:00 AM stays checked, and cannot be unchecked by any means.

**To Reproduce**
1. Go to New -> Dashboard
3. Edit -> Add Filter -> Time -> All Options -> Save
4. Select Filter -> Exclude... -> Hours of the day -> Try to deselct the 12:00 AM option

<img width="541" alt="image" src="https://user-images.githubusercontent.com/110378427/211362919-651d06b8-cc1a-4ce1-913e-36d463bbb941.png">

**Expected behavior**
All input checkmarks are unchecked

**Information about your Metabase Installation:**

Metabase version 44.6 ... I cannot test this on 45 since there is the following issue https://github.com/metabase/metabase/issues/27123 which doesn't give the option to select Hours of the day but I assume once 27123 is fixed 45 will still have this issue

**Comment by nemanjaglumac** [comment]
How do you even get to the "Hours of the day" in the first place?

https://github.com/metabase/metabase/issues/27123

**Comment by nemanjaglumac** [comment]
Just to explicitly say it (because I missed it during the first reading), this issue is blocked by https://github.com/metabase/metabase/issues/27123.
