### ISSUE TITLE
Can't update/change column settings 

### ISSUE THREAD

**Issue by bubbaspaarx** [metabase/metabase#27573]
**Describe the bug**
When viewing the data after a question has been created, I am unable to change the column header settings. They are unresponsive, or change back immediately to their initial state. 

**Logs**
There are no logs being generated at the time of the issue. No network requests happen when attempting to change the values either. 
There are a few logs when refreshing the page, these may or may not be linked 
<img width="506" alt="Screenshot 2023-01-09 at 14 43 21" src="https://user-images.githubusercontent.com/22352499/211334895-6d958095-2515-4317-962a-4db9192d9eb6.png">

**To Reproduce**
1. Generate a question
2. Click 'Visualize'
3. Try and change a column header title or any other column information

https://user-images.githubusercontent.com/22352499/211334305-1702cbc2-406c-47ef-bb4d-171848355bb6.mov

**Information about your Metabase Installation:**

```sql
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8-LTS",
    "os.name": "Linux",
    "os.version": "4.4.0-1104-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.9 (Ubuntu 13.9-1.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v0.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

- Chome 108
- OS Monterey

**Comment by paoliniluis** [comment]
Hi! I can't replicate this, are you able to replicate this on a new instance?

**Comment by alxnddr** [comment]
I reproduced the behavior on `v0.45.1`. We by a mistake showed table column settings in the header in the underlying data view which is shown by clicking on this toggle. The column settings button was removed from there in newer versions.
<img width="1243" alt="Screenshot 2024-06-28 at 3 46 16 PM" src="https://github.com/metabase/metabase/assets/14301985/4c09b1aa-7c0d-452b-8d3a-d8d03bec3328">

@bubbaspaarx to configure table columns you can switch to the Table visualization type which will allow you to change column names and other settings
