### ISSUE TITLE
Last Login times appear to be in the future when server is UTC and my browser is behind UTC (UTC - 5:00)

### ISSUE THREAD

**Issue by mstralka** [metabase/metabase#27575]
**Describe the bug**
Our Metabase server (v0.45.1) is hosted at AWS and is configured to use UTC for the time zone on the server and the database. 

I am located in the US Eastern Timezone (UTC - 5:00), and my mac's timezone is US Eastern Time.
![image](https://user-images.githubusercontent.com/439680/211341651-19cbd75f-87e0-4d32-8ed7-2bace437a683.png)

When I go to my Metabase server > Admin > People screen, someone who just logged in within the last few minutes appears to have a Last Login of "in 5 hours" like this:
![image](https://user-images.githubusercontent.com/439680/211340269-df538d84-96d7-471e-a678-e0484970672c.png)

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Configure your Metabase server and database to use UTC and set the `MB-REPORT_TIMEZONE` environment variable to `UTC`.
2. Configure your computer to use the US Eastern Time zone or any time zone behind UTC.
3. Log in to Metabase
4. Go to Admin > People and search for yourself. Your "Last Login" will appear as "In X hours."

**Expected behavior**

Metabase should display the "Last Login" in my browser's time zone, so it should appear as "Just now" or "X minutes ago".

**Screenshots**
![image](https://user-images.githubusercontent.com/439680/211340269-df538d84-96d7-471e-a678-e0484970672c.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 108.0.5359.124 (latest)
- Your operating system: macOS 12.6.1, Apple M1 Max
- Your databases: MySQL 5.7.12 - AWS Aurora
- Metabase version: 0.45.1
- Metabase hosting environment: AWS - Ubuntu 18.04
- Metabase internal database: MySQL 5.7.12 - AWS Aurora

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Low severity

**Additional context**

**Comment by mstralka** [comment]
This may be related to #14654

**Comment by paoliniluis** [comment]
Thanks @mstralka, why don't you say it's a duplicate?

**Comment by paoliniluis** [comment]
As there was no answer, I'm closing this one in favor of 14654
