### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2757]
Our CI has gotten really slow, like 20-30 minutes. It's annoying.

**Comment by tlrobinson** [comment]
A few ideas:

* Drivers are read-only so we should be able to load data into the databases once and reuse it. Just create a new table if the database needs to change.
* Mock databases for most tests?
* Cache queries in a faster/more reliable local database?
* Detect if a branch hasn't modified the frontend or backend, and don't run those tests (always run integration tests that span the frontend/backend though).

**Comment by camsaul** [comment]
They're really just slow because the BigQuery tests (for some reason I haven't been able to deduce) are slower than dirt. If we can speed those up we won't need to worry about anything else IMO

**Comment by tlrobinson** [comment]
The total time (without running in parallel) is still something like 50 minutes, which seems pretty extreme.

It would be nice if we could reduce that since we only have 7 containers on Circle and if multiple people push around the same time it will still take a long time.

**Comment by camsaul** [comment]
A big chunk of that (probably 5 minutes or so for *every* box) is the time it takes for each container to run `npm install`, and `apt-get` for mongo3 & crate, restart the Mongo server, change the system timezone, install some Python dependencies (?) and all sorts of other nonsense. So it wouldn't take 50 minutes to run everything serially. I run tests against all the drivers on my own box all the time and with the exception of BigQuery it's generally pretty fast.

But it might make sense to run the tests on 4 containers and add an 8th so we can run two sets of tests at once.

**Comment by camsaul** [comment]
Installing Mongo3 & Crate takes over a minute when all the steps are done, if we switch the CI boxes to Trusty (#2333) they come with Mongo3 pre-installed. So that's worth working toward but I ran into some MySQL timezone-related test failures when I tried that

**Comment by camsaul** [comment]
I think the slowest part of the BQ tests is loading the data so like you said @tlrobinson it probably makes sense to just manually load the data once and reuse the same data for every test. It's an extra step when we add new test datasets but I think the hassle is worth it if it speeds up CI significantly

**Comment by tlrobinson** [comment]
Then I guess the question is how do we get circle to cache stuff that rarely changes.

With a Dockerfile you can do something like 

```
ADD package.json npm-shrinkwrap.json /src/
RUN npm install
ADD . /src
RUN ./build
```

And if package.json or npm-shrinkwrap.json haven't changed it will use the cache for everything up to `ADD . /src`. Not sure if there's something similar for Circle.

**Comment by camsaul** [comment]
We might be able to better parallelize some of the data loading code too

**Comment by tlrobinson** [comment]
Some info on Circle's caching https://circleci.com/docs/how-cache-works/

**Comment by camsaul** [comment]
I think we can go ahead and close this now that our CI is back down to ~10 minutes (down from 20-30 in the dark ages of a few months ago). I don't realistically see it getting too much faster than that. @metabase/core-developers, thoughts?

**Comment by camsaul** [comment]
So Circle does actually give us a lot of info as env vars:

`CIRCLECI=true`
`CI=true`
`DISPLAY=:99`
`CIRCLE_BRANCH`
The name of the branch being tested, such as 'master'
`CIRCLE_SHA1`
The SHA1 of the commit being tested
`CIRCLE_BUILD_NUM`
The build number, same as in circleci.com/gh/foo/bar/123
`CIRCLE_PROJECT_USERNAME`
The username of the github repo, 'foo' in github.com/foo/bar
`CIRCLE_PROJECT_REPONAME`
The repo name of the github repo, 'bar' in github.com/foo/bar
`CIRCLE_USERNAME`
The github login of the user who triggered the build

Since we have the git hash we could probably call git to see which files have and then only run appropriate tests, e.g. frontend tests if `.js` files have changed

**Comment by salsakran** [comment]
I still really like the idea of not running the entire test suite for branches other than `master`. This goes double for frontend integration tests once those get merged in.

**Comment by camsaul** [comment]
Related: #3091

**Comment by camsaul** [comment]
Going to go ahead and close this out since the era of CI regularly taking 30 minutes has long since passed.
