### ISSUE TITLE
Downloading CSV results from bigger queries fails

### ISSUE THREAD

**Issue by FlorianHoevelmann** [metabase/metabase#2761]
Hey,
I tried to download the result of a query that takes about 2 mins, but when i clicked on the download button it gave me this error "{"message":"Java heap space","stacktrace":[]}". For querys with a shorter runtime it perfectly workes.
This is nothing urgent we have a workaround for this but i just want you to be aware of that.

Regards,
Florian

**Comment by samcheng** [comment]
Any recommendations as to workarounds for this?  We're on Elastic Beanstalk and would be happy to pay for bigger VMs if that would help.

**Comment by salsakran** [comment]
It'll be fixed in our next release. I'll try to get you a PR that you can build + deploy before then.

**Comment by samcheng** [comment]
Thanks for the attention, Sameer!  I've convinced my users to add some additional filters for now.

**Comment by camsaul** [comment]
@salsakran which PR fixes this?

**Comment by camsaul** [comment]
@salsakran RE your comment

> It'll be fixed in our next release.

There's no PR referenced here. Was this indeed fixed?

**Comment by salsakran** [comment]
closing this in favor of #5187 where there's more commentary.

**Comment by thucnc** [comment]
Hello @salsakran, I found this issue is closed, so is it fixed now ? this issue is critical to us, thanks.
