### ISSUE TITLE
Full-app embedding drill-through popover appearing in wrong place

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#27629]
## Description
If I click on a segment of a chart in full-app embedding, occasionally the drill-through popover pops up in a seemingly random location. [Video from a prospect](https://share.vidyard.com/watch/jGPCypoBDSGK8jBRwjj9q6?).

<img width="1654" alt="Screenshot 2023-01-11 at 10 37 26" src="https://user-images.githubusercontent.com/16455495/211849219-63e11282-8205-4cce-986d-7da62972e3b2.png">

## Expected behavior
In the screenshot above, I would expect the popover to appear closer to the segment being clicked on, indicated by the mouse location in this case.

**Comment by nemanjaglumac** [comment]
Related: https://github.com/metabase/metabase/issues/15502, https://github.com/metabase/metabase/issues/10448, https://github.com/metabase/metabase/issues/15277, https://github.com/metabase/metabase/issues/7647

**Comment by nemanjaglumac** [comment]
To provide a bit more context, there was this [initiative to replace our popover with a 3rd party library](https://github.com/metabase/metabase/issues/18951). Until we unify all popover instances and find a lasting solution, I'm afraid things like this will continue to happen.

Looking back at the amount of issues with the popover we had, the situation is 100x better today.

@WiNloSt mentioned that [tippyjs/react](https://github.com/atomiks/tippyjs-react) lib (that we're migrating to) had the last commit about a year ago.

**Comment by albertoperdomo** [comment]
This seems to be resolved now. Closing.
