### ISSUE TITLE
Unable to search within query when using the SQL editor

### ISSUE THREAD

**Issue by aarthi-subramanian** [metabase/metabase#27636]
**Is your feature request related to a problem? Please describe.**

I often use the SQL Editor of metabase. Especially when the queries are long, we are unable to search within the query! You can `ctrl+F` and search the page, but this will only search the block currently in view and will not search in the whole query box :(. It's very frustrating. 

**Describe the solution you'd like**
Ability to search within the query box in the SQL editor view of Metabase.

**Describe alternatives you've considered**
I tried clicking outside the box and hitting `ctrl+F`, i tried clicking within the box and hitting `ctrl+F` but no luck. I will just need to scroll thru the query and manually read thru.

**How important is this feature to you?**
Pretty important! I feel like itd save minuites every day and add up over time!

**Additional context**

**Comment by alxnddr** [comment]
This has been fixed in 45:
<img width="712" alt="Screen Shot 2023-02-20 at 7 27 23 PM" src="https://user-images.githubusercontent.com/14301985/220207254-989999e5-caf3-4deb-8be4-63c6e690a38c.png">

**Comment by aarthi-subramanian** [comment]
Hi @alxnddr , just upping this comment! ^

**Comment by alxnddr** [comment]
@aarthi-subramanian we shipped it in 45, which version of Metabase are you using? You also need to click inside the code editor and then press `ctrl + F (cmd + F)`

https://user-images.githubusercontent.com/14301985/222201723-d56d6c8d-58be-4166-b514-8eff2755cd94.mov

**Comment by aarthi-subramanian** [comment]
Hi @alxnddr , thanks!
* How can i find out which version metabase im on?
* Unable to click inside editor and `cmd+f` 🙏 . So maybe im on a previous version? Video - https://user-images.githubusercontent.com/47357846/222212136-be546ac2-5893-4789-b5ea-b9bca733a1ab.mov

**Comment by aarthi-subramanian** [comment]
Hi we just updated our metabase version and this is working. THank u !!
