### ISSUE TITLE
Having multiple `unnamed` dashboard filters drops all set filters except the last one

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#27653]
**Describe the bug**
As the title suggests, when there are multiple "unnamed" dashboard filters on a dashboard and the user sets the values for them, a refresh or a subsequent visit to that dashboard will drop every single filter value except the last one. Additionally, ALL such filters will "inherit" the value of the last one.

It's a bit confusing but repro steps will help clarify this further.

**To Reproduce**
_Note: This can be reproduced with an empty dashboard with two filters but I'll stick to the more likely real-world scenario_
1. Save "Orders" table as a question and add to new dashboard when prompted to do so
2. Add the first filter (ID) and delete its "Label" (notice FE automatically sets it to "unnamed"); connect the filter to Orders.ID
![image](https://user-images.githubusercontent.com/31325167/212132971-92f16563-eda0-43b7-9070-58c451f27cd7.png)
3. Add the second filter (number, greater than or equal to) and delete its "Label" as well; connect the filter to Orders.TAX
![image](https://user-images.githubusercontent.com/31325167/212133079-053097f9-5570-491d-b479-56471633d054.png)
4. Save the dashboard
5. Input `3` in the ID filter (the first one - it's hard to say which one is which without the label)
6. Query params will now be `?unnamed=3`
![image](https://user-images.githubusercontent.com/31325167/212133856-5e35bef6-b1f1-4a00-9d19-47e96b33440d.png)
7. Input `0` in the number filter
8. Query params now incorrectly turn into `?unnamed=0` (it dropped the ID part because it cannot distinguish between multiple filters if the slug is the same)
![image](https://user-images.githubusercontent.com/31325167/212133811-064aa1f5-f5e4-487d-bdc5-07217408472c.png)

9. If you look at the UI at this point, everything still looks correct
10. Refresh the dashboard and notice the last filter being applied to ALL unnamed filters
![image](https://user-images.githubusercontent.com/31325167/212134263-cffde605-f58c-45ca-ad9b-79e446a45d35.png)

**Expected behavior**
Not clear what to do. This is probably a product question.
My hunch would be to not allow filters without a name, because we derive the slug using the name and slug is the only way to differentiate between multiple filters in the query params.
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/utils/dashboards.ts#L56:L69

**Information about your Metabase Installation:**
- local dev, `master`, https://github.com/metabase/metabase/commit/f53f2f79b7790511dadb2e8c129e894805ec1ff1, Sample database, H2

**Severity**
One could say that people rarely (if ever) leave the filter unnamed. In that case it's P3.
But things get a bit more complicated if we take https://github.com/metabase/metabase/issues/24500 into account.

**Additional context**
We stopped hiding broken dashboard filters (in order to be able to remove it) in https://github.com/metabase/metabase/pull/16582.

@qnkhuat 's [approach](https://github.com/metabase/metabase/pull/27623) to fixing #24500 was to make the backend schema even more loose and to allow filters without a `name`.  This leads to even bigger problems because then the query param becomes `?=foo` and it gets dropped on dashboard refresh.

**Comment by qnkhuat** [comment]
Waiting for Product's input. [Here](https://metaboat.slack.com/archives/C010L1Z4F9S/p1673545876892039) is the discussion on slack

**Comment by brunobergher** [comment]
What you described sounds right to me.

**Comment by nemanjaglumac** [comment]
Please keep in mind it's not enough to only have a filter name. Multiple filters on a single dashboard must have **UNIQUE** names to prevent problems.

**Comment by qnkhuat** [comment]
In order to fix this we need to require the parameter's name and enforce unique names on both FE and BE.

we should be careful about enforcing uniqueness, we probably don't want the existing dashboard suddenly stop working if it contains duplicated parameter name.

So let's make sure the unique rule is applied on create/update, but the existing dashboard/card with duplicated parameters should work as it is.

**Comment by qnkhuat** [comment]
The more I think about this, I believe we shouldn't enforce this at the API level because we can break existing stuff.
more [here](https://github.com/metabase/metabase/pull/28110#issuecomment-1422033134).

I think we can stop at enforcing this on FE for now.

**Comment by cdeweyx** [comment]
### Issue 1
> If you’re editing that name field, then leave it blank and unfocus the input box, I’d expect it to revert back to the name it had before.

Yeah, we should pull trigger on this.

### Issue 2
> 2i) looks a lot like Maz's suggestion in Issue 1 - we'd have to validate the filter label input and revert if it doesn't match our criteria. Should we kill two birds with one stone?

This feels right to me, and two birds with one stone is always good. I say we go this route.

**Comment by calherries** [comment]
Okay, confirming I'll tackle this in two steps:

1. If you’re editing the label field, then leave it blank, show an error state. When you unfocus the input box in the error state, it should revert back to the label it had before.

2. If you’re editing the label field, then give it a label with a duplicate slug with another filter, show an error state. When you unfocus the input box in the error state, it should revert back to the label it had before.
