### ISSUE TITLE
metabase.db.metadata-queries-test failing randomly for Redshift/Crate

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2767]
This is on master for 0.18.0-SNAPSHOT.

The recently added tests in `metabase.db.metadata-queries-test` are failing around 1/3 of the time for Redshift/Crate (e.g. https://circleci.com/gh/metabase/metabase/6843 (Redshift) & https://circleci.com/gh/metabase/metabase/6844 (Crate)). Investigate why and fix this issue.

**Comment by camsaul** [comment]
This is probably just some weird race condition with the way the test data gets automatically loaded since it doesn't always happen. So this is probably an issue with that and not the drivers themselves

**Comment by dacort** [comment]
I just upgraded to 0.18.1 from 0.17.1 and now some of the query_metadata API calls on the new question page are failing. I'm not sure if it's related to this or not. This is the error message that gets returned:

`"Syntax error in SQL statement \"SELECT \"\"METABASE_FIELDVALUES\"\".\"\"FIELD_ID\"\", \"\"METABASE_FIELDVALUES\"\".\"\"VALUES\"\" FROM \"\"METABASE_FIELDVALUES\"\" WHERE (\"\"FIELD_ID\"\" IN NULL[*]) \"; expected \"(\"; SQL statement:\nSELECT \"METABASE_FIELDVALUES\".\"FIELD_ID\", \"METABASE_FIELDVALUES\".\"VALUES\" FROM \"METABASE_FIELDVALUES\" WHERE (\"FIELD_ID\" in NULL) [42001-191]"`

**Comment by dacort** [comment]
After digging in a little more, it looks like the query_metadata api call throws an error on tables that are not active. So possibly unrelated to this - let me know if I should open a new issue.

**Comment by camsaul** [comment]
@dacort your issue is different, I've opened it as #2922

**Comment by camsaul** [comment]
I haven't seen this happen on CI in a few months so I'm guessing it might have been inadvertently fixed. Going to close this, I'll reöpen it if I ever see it again
