### ISSUE TITLE
It's not possible to have boolean dropdown filter anymore

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#27683]
**Describe the bug**
It's not possible to have boolean dropdown filter anymore on `master`. It still works on the release branch, though.

**To Reproduce**
1. Sample database > Accounts > save as question and add to dashboard when prompted to do so
2. Add filter to the dashboard
3. First of all, notice there is no boolean filter type (will follow up with a separate issue for this)
![image](https://user-images.githubusercontent.com/31325167/212371582-38e8614e-0e0c-4131-82bb-51fbbddef515.png)
4. Choose "Text or Category"
5. Our best bet currently is to choose `Is` filter type so do that
![image](https://user-images.githubusercontent.com/31325167/212371929-fcac291f-0ee0-4393-9443-b04c1ef11695.png)
6. Leave the "Dropdown" option selected and connect the filter to the "Active subscription" column
![image](https://user-images.githubusercontent.com/31325167/212372227-cccdc203-6880-4fab-a61a-a0b1202ed9f4.png)
7. Save the dashboard
8. It gives you only the input field option instead of true/false options to choose from
![image](https://user-images.githubusercontent.com/31325167/212372535-670ffb8c-a973-478e-b55f-1943a5a4ccec.png)

**Expected behavior**
Looking at the 45.1 and the latest release-x.45.x branch, it should give you the boolean options to choose from:
![image](https://user-images.githubusercontent.com/31325167/212372877-096f3bc4-cd87-41e4-96c0-25df8cb21890.png)

**Information about your Metabase Installation:**
local dev, `master`, f395e2f28beade9dccc4d5936d7292adc6b84289, H2, Sample Database

**Severity**
"Only" P2 because it is still possible to manually type "true" or "false" in the input field and the filter will work, but even this feels wrong. How/why do we accept the string in place of a boolean?

**Additional context**
- Currently not even able to reproduce #27643 on `master` because of this issue. 
- Related to (and caused by) this refactor https://github.com/metabase/metabase/issues/26898

**Comment by nemanjaglumac** [comment]
For the completeness sake, here are different parts of the UI where this IS working as expected even in `master`:

notebook editor
![image](https://user-images.githubusercontent.com/31325167/212397372-c76ac240-7925-4937-aa62-309ae4f34491.png)

Column popover
![image](https://user-images.githubusercontent.com/31325167/212397466-73e16cbc-8e16-4bf8-80b8-7d31f25381fe.png)

Bulk filter modal
![image](https://user-images.githubusercontent.com/31325167/212398002-cf84f704-214d-4fd9-a546-410a2796ae0b.png)

**Comment by markbastian** [comment]
Just tried this on the latest master branch and see the radio buttons:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/8381441/213819787-574071a2-08ff-41ca-b469-a56866b0851c.png">

**Comment by calherries** [comment]
Closing since this is fixed already.

**Comment by nemanjaglumac** [comment]
Context:
Nobody can reproduce this anymore. @qnkhuat was able to confirm that if `values` comes back empty this problem will emerge and thinks this might be a sync problem.
![image](https://user-images.githubusercontent.com/31325167/214818609-caa73d1c-ce22-44a2-a1be-4cab99938999.png)
