### ISSUE TITLE
[Epic] Add buttons that trigger actions to dashboards

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#27700]
[Product doc](https://www.notion.so/metabase/Add-buttons-that-trigger-actions-to-dashboards-495ea6b6eabf47fe86f7bb9adcbc57b1)

- [x] #27738
- [x] #27823 
- [x] #27842
- [x] #27899
- [x] #27841
- [x] #27916

~~make URL/action choice a top level radio option~~

**Comment by iethree** [comment]
![giphy-4](https://user-images.githubusercontent.com/30528226/218877037-32ab742d-1a4d-4b33-8680-2657ac8a93ae.gif)
