### ISSUE TITLE
[Epic] Prevent users from accidentally deleting all their saved questions

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#27702]
[Product doc](https://www.notion.so/metabase/Prevent-users-from-accidentally-deleting-all-their-saved-questions-76b21366eb3744ec81b6a0a707571daf)

### Steps

- [ ] https://github.com/metabase/metabase/pull/27646
- [ ] https://github.com/metabase/metabase/pull/27847

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/27644
