### ISSUE TITLE
problem in hive metastore start

### ISSUE THREAD

**Issue by sushmagoravar** [metabase/metabase#27710]
https://github.com/metabase/metabase/issues/new/choose

i did all configuration in hive to connect mysql as metastore 

but 

hive --service metastore, not starting metastore

logs are like

2023-01-16 23:35:00: Starting Hive Metastore Server

**Comment by paoliniluis** [comment]
Hi, you're confusing Metastore with Metabase

**Comment by sushmagoravar** [comment]
> 

could you please explain briefly?i dont understand
