### ISSUE TITLE
stacked area charts plots 0 for missing values

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#2771]
This is not an error per say, but more an formatting question/discussion

lets assume I have chart (sample below) and one of the categories is missing, then suddenly shows up (see green), it shows zero value for the whole history, I would assume this category would be missing and would show from the time it actually exists.

![image](https://cloud.githubusercontent.com/assets/6222611/16098918/481503d4-330a-11e6-9c41-cf8a166c7424.png)

**Comment by tlrobinson** [comment]
Duplicate of #896?

**Comment by agilliland** [comment]
This looks more like nulls being treated as 0's?

**Comment by tlrobinson** [comment]
Err yeah, actually "related to", not "duplicate of"
