### ISSUE TITLE
Missing summarize operations after creation of numeric custom column

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#27745]
**Describe the bug**
I created a query that is based on dimension table and created a custom column. The Dimension table has timestamps, IDs and strings column types but no numeric column types. When trying to use the summarize option in the query builder, option like sum, cumulative sum or average are not shown there is no numeric field to use these functions on.

However when adding a custom column that is a numeric field,
e.g.   case([ID] = "1", 5, 3)
or      datetimeDiff([Create Time], [Update Time] , "minute")

the options for sums, avg and so on are still not shown.

**To Reproduce**
1. Create a query with a table that has no numeric columns in the query builder
2. Create a numeric custom column like the examples above
3. Click on summarize and then on "Pick metric you want to see"
4. See that the sum/avg options are missing

**Optional Steps**
5. Try to create a custom expression instead on the created custom column
6. Click visualize
7. Summarize breaks and is kicked out of query builder, you return to after Step 2

**Expected behavior**
When a custom column is created that is numeric, the options should show. Also the custom summarize should not break.

**Screenshots**
<img width="850" alt="Screenshot 2023-01-18 at 09 59 22" src="https://user-images.githubusercontent.com/113892067/213155147-8730ec35-170e-4f26-b9fb-61c178809cf5.png">
<img width="376" alt="Screenshot 2023-01-18 at 09 59 27" src="https://user-images.githubusercontent.com/113892067/213155156-bfb6734c-3043-4d57-b1a0-fd092465c558.png">

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "5.4.202+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-17",
      "tag": "v0.45.2",
      "branch": "release-x.45.x",
      "hash": "819ce29"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
High. Regular users cannot create queries on dimension tables. Only SQL-Editor would work in that scenario.

**Comment by carstenkadmos** [comment]
@nemanjaglumac I am not sure if you missed this:

`The Dimension table has timestamps, IDs and strings column types but no numeric column types`

I assume that this is the reason that no sum option is shown. However I expect this to be changed when I add a numeric custom column. The table you use is called orders, and I am pretty sure that it contains numeric values.

**Comment by nemanjaglumac** [comment]
@carstenkadmos this is even a bit worse because it can result in a blank screen.

1. Click on a custom numeric column header cell
2. Click on `Sum` or `Avg`
3. Although the result is correct, "Summarize by" doesn't have a proper option shown ("Sum of [field]")
![image](https://user-images.githubusercontent.com/31325167/214580074-2797fc37-3a6d-47d1-9c51-87369ac90a81.png)
4. Click on the green "ballon" button
5. You end up in "Something's gone wrong" screen in testing/dev environment (not sure if it's the blank screen in production) - there is definitely a frontend involved in this part at least

![image](https://user-images.githubusercontent.com/31325167/214579902-391aa3f6-dc44-4d32-899d-17a24d0f9a51.png)

console error:
`(uncaught exception)TypeError: Cannot read properties of undefined (reading 'name')`
