### ISSUE TITLE
Question on Backing up Metabase with AWS?

### ISSUE THREAD

**Issue by loganfrederick** [metabase/metabase#2776]
I set up Metabase via the AWS Elastic Beanstalk quickstart launcher on this page: http://www.metabase.com/start/aws.html

It's been working really well, but then I had an issue with my AWS instance which crashed. When I restarted my instance, I lost my dashboards.

Does anyone here/on staff have a recommended way for backing up and restoring the Metabase data or Docker container that's created from the "Launch Metabase on AWS" page?

Any help would be greatly appreciated!

**Comment by salsakran** [comment]
Did you restart the instance from the ec2 or the elastic beanstalk portion of the AWS Console.

Was it just the dashboards that were missing or was anything else missing?

**Comment by loganfrederick** [comment]
I restarted the instance from the Elastic Beanstalk portion of the AWS Console.

![screen shot 2016-06-15 at 6 30 39 pm](https://cloud.githubusercontent.com/assets/138125/16100918/4eca1f26-3327-11e6-906d-fa2510f29aa7.png)

**Comment by loganfrederick** [comment]
I ended up spinning up a whole new Metabase instance, as when I restarted, Metabase went into Setup mode.

**Comment by loganfrederick** [comment]
I haven't used Elastic Beanstalk before so definitely let me know if I should be restarting instances and doing backups from another part of AWS.

**Comment by camsaul** [comment]
@loganfrederick were you using MySQL or Postgres as the Metabase backing DB?

**Comment by loganfrederick** [comment]
I've tried to track that down but it's not obvious to me where this information is in the console/Elastic Beanstalk/Docker configs in AWS. 

@camsaul 

I used the Elastic Beanstalk launch URL linked to from here to do the setup: http://www.metabase.com/start/aws.html

And attached below some screenshots from the Elastic Beanstalk configuration screen and startup events. I don't see anything that indicates what database is behind the Metabase dashboards. Does the team know what might be configured as part of your Elastic Beanstalk launch script?

<img width="1026" alt="screen shot 2016-06-15 at 7 37 08 pm" src="https://cloud.githubusercontent.com/assets/138125/16101986/d8df2f54-3330-11e6-933c-bc3102046575.png">

<img width="1048" alt="screen shot 2016-06-15 at 7 37 41 pm" src="https://cloud.githubusercontent.com/assets/138125/16101987/d8dfdd46-3330-11e6-915b-ee6164e19dd2.png">

**Comment by camsaul** [comment]
on the bottom of your screenshot there's

> You do not have a database.

So I'm guessing all your data vanished because it used a local H2 database which got wiped along everything else when it restarted. Check out the [RDS Configuration](http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#rds-configuration) section of the setup guide and make sure you add a database. 👍 

@metabase/core-developers: maybe we should clarify this a bit more in the documentation?

**Comment by loganfrederick** [comment]
@camsaul Thank you very much for your help!

Yeah I noticed that "no database" message in the AWS console. The RDS configuration link you sent makes sense and I'll give those configurations a try shortly.

I think my suggestion for clarifying would be to add the RDS config link (or the page's general http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#rds-configuration) to the Run Metabase on AWS page (http://www.metabase.com/start/aws.html).

Let me try out the RDS configuration steps and get back to you that it worked before closing out this issue.

**Comment by camsaul** [comment]
Clicking the "Launch Metabase on AWS" button takes me to the RDS Configuration page and prompts me to set up a database. Did it skip that page for you?

**Comment by loganfrederick** [comment]
It did not skip that page but I recall clicking through the defaults and did not set up a separate RDS from there before. 

I also just realized that you do link to the Operations Guide from that page via the bolded "AWS Elastic Beanstalk install guide" text. My bad for missing that it was a link. Maybe add a hover effect on it?

**Comment by loganfrederick** [comment]
@camsaul I am going to close this issue, you guys did a great job answering questions and pointing me in the right direction. The RDS configs should work. Metabase is a great app!

**Comment by Hennisa** [comment]
Hi! I have a question related to this topic. I'm running Metabase on AWS Elastic Beanstalk and the connection to AWS Redshift (my data source for dashboards etc.) is set up as a local H2 database file on my Metabase application server since when I deployed the application to AWS Elastic Beanstalk it seemed like Elastic Beanstalk only supports RDS for independent database server connections, not AWS Redshift. Is there any way I could set up my AWS Redshift Database as an independent database server for Metabase in AWS Elastic Beanstalk or should I consider hosting it somewhere else? I'd guess I'm not the only Metabase user running it on AWS Elastic Beanstalk & using Redshift as data source but I haven't yet find a way to solve this. I do not want to lose all my dashboards, setup etc. in case I want to upgrade Metabase version, restart application server etc. which in the case of local H2 will happen.

**Comment by camsaul** [comment]
@Hennisa Metabase doesn't support using Redshift as an application database, only H2, Postgres, or MySQL. (You wouldn't want to use the same database that contains your data anyway). Almost everyone running Metabase on Elastic Beanstalk is using Postgres, and that's what I'd recommend. Take a look at our [guide to running Metabase on Elastic Beanstalk](http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html).

**Comment by VinayLeaf** [comment]
@camsaul can u help me with this http://stackoverflow.com/questions/40647337/how-to-run-metabase-on-ec2-instance-without-elastic-beanstalk

**Comment by camsaul** [comment]
@VinayLeaf I've never tried to run Metabase on AWS without using Elastic Beanstalk so I'm probably not going to be much help here. Let us know if you get it working and maybe we can add some documentation for anyone else who wants to run it that way.

**Comment by VinayLeaf** [comment]
If u know someone who can help me, plz let me know i am finding solution
from last 3 days.

**Comment by Glathrop** [comment]
Note that you cannot use 'admin' as a Postgres username. AWS will silently fail the DB creation and the instance will spin up....with no db. We learned the hard way on this.

**Comment by Glathrop** [comment]
We are still struggling with restoring correctly. I've managed to go through a sequence of killing instances then rebuilding the beanstalk environment that has maintained a proper link to our RDS but something in my latest attempt screwed the pooch and did not connection to my previous RDS instance. 

Would any kind souls here be willing to share the aws cli instructions for linking a prior RDS snapshot to a new elastic beanstalk environment?

From my understanding the steps are
#1 - Make sure you have a snapshot!
#2 aws rds delete --db-instance-identifier <value>
#3 aws rds restore-db-instance-from-db-snapshot --db-instance-identifier <value> --db-snapshot-identifier <value>

at this poing the db should be restored but I simply cannot get the Metabase EB environment to connect to the new db. Restarting the instance seems to crash everything, rebuilding environment makes a new RDS where the process would need to be repeated. Any assistance would be very helpful. I feel as if I’m simply missing a final step to force a db connection.
