### ISSUE TITLE
Dashboard filter connected to a custom column appears as if it was never connected

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#27768]
**Describe the bug**
You can create a Question with a Custom Column. The problem arises when this question is added to a Dashboard and a filter connected to this custom column. It shows that you are able to connect the filter to the column but after you press save and back to edit the filter shows as gone. Even though you are still able to filter.

**To Reproduce**
1. Go to New Question -> Sample Database -> Products -> Add Custom Column ` = [Category] ` -> Save 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/110378427/213468744-8a665e7f-e690-4abe-9ba5-57410d732d9b.png">

2. Go to Dashboard -> Add this question to Dashboard -> Add Filter -> Text or Category -> Connect to Custom Column -> Save

<img width="857" alt="image" src="https://user-images.githubusercontent.com/110378427/213469169-714db946-2923-464b-a13d-e49ff86dfa69.png">

3. Check that you can actually filter:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/110378427/213469357-ecf93a02-4e42-4987-ba30-2b1c4dfc0418.png">

4. Go back to Edit the Dashboard -> You will see the filter is not connected anymore 

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/110378427/213469549-d22388b1-f2c1-49d9-878a-fa5d1f3c034e.png">

5. Even though visually it's not connected and you can either Save or Cancel from Edit mode you are still able to filter

<img width="923" alt="image" src="https://user-images.githubusercontent.com/110378427/213470533-20abe5bb-9076-47ef-8c5a-58917fc4ba5b.png">

**Expected behavior**
The GUI shows that the filter is connected

**Information about your Metabase Installation:**

Tested this on both **Master and 45.2**

**Additional context**
This is very misleading when you are dealing with categories and dropdown. Since Custom column will not give the option of a dropdown and you are just prompted with a search box people would think that the filter is not connected

**Comment by nemanjaglumac** [comment]
Tested back on `x.43.4`.
It wasn't working even back then, so probably not a (recent) regression.

**Comment by ranquild** [comment]
When I call `/api/dashboard/2/params/b3b436dd/values` I get  
```
Parameter \"b3b436dd\" does not have any Fields associated with it
```
which is wrong. The endpoint should be fixed first.

**Comment by WiNloSt** [comment]
Doesn't happen with
- `x.46.0`
- `x.46.7`

Confirm it's happening with
- `x.45.0`
- `x.45.4.3` (The latest 45 version at the time of posting this comment)
