### ISSUE TITLE
Improved `card-view` event

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#27782]
## Context
This is the most important event. It describes who saw what when.

Today, this event in the `view_log` table contains the following properties:
- model_id (card_id)
- user_id
- timestamp
- cached? ignore_cache?

This event is triggered in three occasions: card creation, card view (get /api/card), and query execution. And there are some issues related to duplication: #25847, #25848

### The goal of this task is to:
1. Define clear triggers
2. Enrich the event with new properties

## Triggers
This event should be triggered whenever the user *sees* a question (regardless of showing or not results). In practice, when the user:
- Visits a question page (through a collection, dashboard, search, homepage, direct link)
- Sees a pinned question with visualization enabled
- Sees a question in a dashboard

*Notes*
- It shouldn't be triggered when a card is created (there is another event to track creation). But as the user sees the question right after it is created, we should log this view.
- It shouldn't be triggered on subscriptions and alerts (we will have other events for this purpose).

New `view_log` schema:
- id
- user_id
- model (`card`, `dashboard`, or `table`) // we will add actions in the future
- model_id
- context (card, dashboard, collection_pin) -- only for cards
- timestamp
- has_access (true if user has access, false if blocked by any permission check)
- error_message (error string if any)

We can likely drop the metadata field with cached and ignore cache as this is query_execution concern

**Comment by likeshumidity** [comment]
Apologies if covered elsewhere or if I am misunderstanding, but why would we not track parallel to API calls? Or another way of asking: Shouldn't there be a 1:1 relationship between API calls and logged access/view events?

"shouldn't be triggered when a card is created", I am curious if this includes when a card is viewed after it is created? That is there is a natural separation between created event and view event if following along API in parallel. The POST event would be the create event, and the GET event would be the view.

Would the front-end have any involvement in logging or is this purely backend? Can avoid some security pitfalls by making entirely back-end and tracking API calls.

**Comment by luizarakaki** [comment]
This is purely backend. But yes, with this proposal, there is a 1:1 relationship with `card` GET API calls. The problem is that the API call is not sufficient because the event depends also on the query execution that is async. So we need to update the event with the query result metadata (that is another API call `dataset`)

**Comment by luizarakaki** [comment]
This should close:
- #25848
- #25847 
- #16517
