### ISSUE TITLE
Object detail doesn't always show up when clicking on primary key

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2780]
Steps to reproduce:

Using the sample dataset, select the orders table, show `bare rows`, click on an order id.

You end up with a list of a single row. 

If you click on a FK (eg, the user id), you'll get to the object detail correctly.

This works correctly in version 0.17, so it's a regression.

If this is a bug report, please fill in the blanks:
*  I am using the _Chrome_ browser.
*  My computer's OS is OS X.
*  I'm running Metabase on AWS. 
*  My database is Postgres.
*  My Metabase version is 0.18-rc

**Comment by camsaul** [comment]
Fixed by #2781
