### ISSUE TITLE
Review Clickhouse partner driver

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#27829]
# Context
The Clickhouse team talked to the developer of the community [Clickhouse driver,](https://github.com/ClickHouse/metabase-clickhouse-driver) improved it, and submitted it to our [technology partner program](https://www.notion.so/metabase/Partner-driver-guide-48114609634d4ba691e6e5702f4cb6bf).

# Follow ups
Before we add the new driver to our Cloud offerings, we need to:
- [x] Review the failing tests and figure out a solution (fix or skip)
- [x] A high-level code review. Look if the code follows our guidelines and doesn't expose any security issue.

With this done, I'll add the driver code to our Cloud CI.

**Comment by metamben** [comment]
@luizarakaki my second [PR]([2594838715](https://us02web.zoom.us/j/2594838715)) for skipping some tests (that are skipped for a bunch of other drivers too) has not been merged yet, but otherwise I think we are done with the review.

**Comment by luizarakaki** [comment]
Great, good to know. I'll proceed to add it to Cloud then.

Which PR is this? I couldn't find a related open PR. You can link to this issue so it closes the issue when merged
