### ISSUE TITLE
Cannot connect to MongoDB without providing a connection string

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#27890]
**Describe the bug**
After the recent forms refactoring, the UI in `/admin/databases/create` won't let you connect to MongoDB without a connection string. That field is marked as required.

[The documentation suggests that the field is optional](https://www.metabase.com/docs/latest/databases/connections/mongodb#using-a-connection-string).

**To Reproduce**
1. Go to Admin > Databases > Add database
2. Select MongoDB
3. Fill out all the necessary details like port, username, password, database...
4. Notice that "Save" button is disabled and the "Connection string" field is marked as required
![image](https://user-images.githubusercontent.com/31325167/214822956-e81d5bee-a4cc-4d41-afc6-1913c330c9e0.png)

**Expected behavior**
The form should either let you connect without a connection string, or it should behave like it does on 45 - offering either/or UI.
Either you want to enter connection details manually
![image](https://user-images.githubusercontent.com/31325167/214822767-4e3079e7-e49e-45b5-9977-e2c0d51f3bc0.png)

or you want to connect using the connection string
![image](https://user-images.githubusercontent.com/31325167/214822916-e3bed937-23d8-4406-ba78-5abddfb14c60.png)

**Information about your Metabase Installation:**
local dev, `master`, b788bc1e917d8de6755db2b92435448445cc5483, H2, Sample Database

**Severity**
P1. Must be fixed before 46.
Although the API works, many users are relying on UI to connect and this is a complete blocker for them.

**Comment by ranquild** [comment]
This works fine if you rebuild drivers.

**Comment by nemanjaglumac** [comment]
Thank you, @ranquild 
I can confirm everything works fine after the drivers rebuild.

Context for anyone experiencing this or similar issue in the future and searching for a solution:
- Rebuild drivers using `./bin/build-drivers.sh`
