### ISSUE TITLE
Warn that a Liquibase rollback may need to be run when downgrading Metabase versions

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#27906]
**Is your feature request related to a problem? Please describe.**
If a user runs Metabase on one version and then wants to downgrade to the previous version (without relying on a backup), they should first run a command to rollback schema migrations per the instructions in https://github.com/metabase/metabase/pull/26429. But it might not be obvious that this step needs to happen.

**Describe the solution you'd like**
We should be able to automatically detect that a downgrade has happened and print a big warning about this on startup.

**Describe alternatives you've considered**
Just put it in the docs

**Comment by camsaul** [comment]
Should we print a warning, or maybe error out and refuse to run? There's a huge chance something is going to be broken anyway, so erroring and forcing the issue would probably ultimately save a lot of heartaches and pain. Maybe we can have an env var to `FORCE_RUN_ANYWAY` or something

**Comment by noahmoss** [comment]
Erroring makes sense to me if we're fully committing to the idea that each release will have some amount of breaking schema changes.
