### ISSUE TITLE
Allow HTML Tags in Results?

### ISSUE THREAD

**Issue by MartinArens** [metabase/metabase#2791]
Hi,

Is it possible to allow HTML Tags in Results?

Example:

`select
concat('<a href="https://domain.tld/crm/', cast(customerId as char), '">', cast(customerId as char), '</a>') as customerId
from customers`

![metabase](https://cloud.githubusercontent.com/assets/7610680/16145895/8caaa6c6-347b-11e6-9659-b98928a27271.png)

It would help us alot.

We use metabase in production:

users created: 45
users with activity: 29
users with actions: 24
reports: 85
report creators: 6
dashboards: 20
labels: 23
favorites: 2
pulses: 3
databases: 19
tables: 310
query executions: 6498
revisions: 306

We love it! Thanks for your great work!

Regards
Martin

**Comment by tlrobinson** [comment]
@MartinArens I think it's unlikely we'll allow arbitrary HTML to be injected as that's a pretty big security risk. Are you just trying to get a clickable link?

We recently started "linkifying" columns marked as Link in the datamodal, but that doesn't apply to SQL questions. We should add a way to set metadata on the resulting columns in a SQL query, and possibly try to auto-detect things like URLs.

**Comment by anki-code** [comment]
>a way to set metadata on the resulting columns in a SQL query
I'm waiting for this feature too.

**Comment by astathis** [comment]
It will help us too. At least, we need a way to customize the display of a query result as someone could do with pure css.

**Comment by astathis** [comment]
Again Thanks for your great work.

**Comment by manjeshpv** [comment]
@astathis  @tlrobinson temporarily I'm using a chrome extesion, extension will detect the raw html and render it.

I feel it can be done in using javascript at in UI instead in server

```js
document
.querySelectorAll('span')
.forEach(x => {
    if(x.textContent.includes('drilldown')) {
      x.outerHTML = x.textContent.replace(/&gt;/g, '>').replace(/&lt;/g, '<');
    }
})
```

https://github.com/metabase/metabase/issues/5601#issuecomment-318564857

**Comment by nicolas-f** [comment]
This issue is fixed https://github.com/metabase/metabase/issues/4493#issuecomment-380891151 you can close it now. Thank you for the feature

**Comment by flamber** [comment]
Closing, since we're likely not going to allow arbitrary HTML, and because links have been supported since 0.30
Related #7188

**Comment by rodrigoGA** [comment]
rendering the html of a query is not showing links.
I think this feature request was not made and it would be really useful

Regarding the security risk, I don't think it is expensive to add an option to sanitize the html before rendering it.

**Comment by flamber** [comment]
@rodrigoGA It has been possible since version 0.30 to link of a full column - the Markdown request in #7188 would allow partial.
Trying to sanitize HTML is complicated - a lot more than people think, which is why Markdown is preferred.
![image](https://user-images.githubusercontent.com/1447303/142248483-5cc6afa0-ce77-4b5a-acbc-51bbcbeb77ed.png)

**Comment by rodrigoGA** [comment]
Thank you very much for your prompt response. But from 0.30 is only for links and # 7188 is from 2018 :(
In my particular case I want to generate a panel that is an html (or a markdown) of the result of a query.
I think that having this feature would enable the possibility to do a lot of things.

**Comment by flamber** [comment]
@rodrigoGA You are looking for a completely different thing - upvote this issue: #4392

**Comment by rodrigoGA** [comment]
thank you very much! 2017? Hope is very good for breakfast but very bad for dinner.

**Comment by richxrich** [comment]
What about rendering HTML inside an iframe and sandboxing it? The content would have no access to metabase.

https://www.w3schools.com/tags/att_iframe_sandbox.asp

**Comment by exetico** [comment]
@richxrich  Did you find your answer?

I'll guess that the answer is:

> [Enterprise Edition](https://www.metabase.com/enterprise/) with [Custom Drill-through](https://www.metabase.com/docs/latest/enterprise-guide/customizing-drill-through.html)

https://github.com/metabase/metabase/issues/12925#issuecomment-659448959

**Comment by richxrich** [comment]
@exetico thanks for the reply but it's doesn't because I want to render the HTML outside of dashboards and in tables (links). This customer isn't very large and at this point wants to "see what is possible" so can't afford the enterprise edition anyway. Unfortunately we will go with redash as it has this feature from what I read here (as much as I don't really like redash)

**Comment by exetico** [comment]
Fair :-) Redash looks interesting, too!
