### ISSUE TITLE
Dashboard cross-filtering

### ISSUE THREAD

**Issue by mdespriee** [metabase/metabase#2792]
Hi folks,
I'm just discovering metabase and this looks very promising !
Any plan about adding cross-filtering in the dashboard ?

**Comment by tlrobinson** [comment]
Related to #1884

**Comment by salsakran** [comment]
@mdespriee what do you mean by "cross-filtering"?

**Comment by mazameli** [comment]
I think we can close this unless @mdespriee wants to chime in with more details about what this means.

**Comment by camsaul** [comment]
I agree @mazameli, since we haven't heard back in almost a year and a half let's go ahead and close this out

**Comment by woraperth** [comment]
Hello @mazameli @camsaul @salsakran 

I would like to know the answer to this question too. Crossfilter is when you select some parts of the data on one plot to filter, and the other plots on the same page got filtered with the same data as well.

For example, there is a library to do that with D3.js: https://dc-js.github.io/dc.js/. For the BI tool, I think Qlik can do it.
