### ISSUE TITLE
Upgrade styled-system to latest version

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#27920]
We're using a dep that is many years old (2.2.5) and the latest version is 5.1.5. The only problem is that "hover" was removed in v3 and we use it on
/components/Icon.tsx
/core/components/Link/Link.styled.tsx

**Comment by gusaiani** [comment]
@paoliniluis duplicate of https://github.com/metabase/metabase/issues/16469

I believe we have an issue for each outdated js lib.

Your detailing on hover is very helpful, so if you'd rather close that other one, I'm all in favor.
