### ISSUE TITLE
Pivot table with the filter on a date column breaks dashboard sending

### ISSUE THREAD

**Issue by gorbunovav** [metabase/metabase#27941]
**Describe the bug**
Create a query, which summarize values by date and some other metric (e.g. sum of hours by developer, by date).
Use the `Pivot Table` visualization.
Dates go into columns, other metric into rows (not sure if it is important).
Add question to some dashboard and try to send it by email - should work.

Now edit the question and in column settings for the date field enable sorting.
Try to send the dashboard again - it will fail.
Check server logs - there will be a `NullPointerException` exception.

**Screenshots**
Question setup: 
![Screenshot 2023-01-28 195442](https://user-images.githubusercontent.com/2665015/215279040-4bff4153-a1d9-43cb-a41b-1df0f4503f84.jpg)
![Screenshot 2023-01-28 200432](https://user-images.githubusercontent.com/2665015/215279351-46e89e4d-f461-4373-bec8-c47f1d758794.jpg)

**Logs**
[server.log](https://github.com/metabase/metabase/files/10527790/server.log)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 09.0.5414.120 (Official Build) (64-bit)
- Your operating system: Windows 11
- Your databases: Postgres
- Metabase version: 0.45.2.1
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: H2 (probably)

**Comment by markbastian** [comment]
Love the explanation ns. Makes it so much easier to follow!

I'm curious, what happens if you change normalize-keys from:
```clojure
(defn normalize-keys
  "Update map keys to remove namespaces from keywords and convert from snake to kebab case."
  [m]
  (update-keys m (fn [k] (-> k name (str/replace #"_" "-") keyword))))
```
to
```clojure
(defn normalize-keys
  "Update map keys to remove namespaces from keywords and convert from snake to kebab case."
  [m]
  (update-keys m (fn [k] (some-> k name (str/replace #"_" "-") keyword))))
```

If that works I think it would an even smaller change that accomplishes the same thing.
