### ISSUE TITLE
Metabase subscription email not correct graphs

### ISSUE THREAD

**Issue by davidvirgilnaranjo** [metabase/metabase#27963]
When two questions are being inline in the same graph, the results in metabase are good, but in the email the result is super misleading:

email:
<img width="497" alt="Screenshot 2023-01-30 at 22 37 40" src="https://user-images.githubusercontent.com/107469028/215612122-bfd77c4f-afe1-496b-8a0f-548e0bb85ede.png">

vs in metabase website:
<img width="510" alt="Screenshot 2023-01-30 at 22 14 19" src="https://user-images.githubusercontent.com/107469028/215607842-5d8321c5-41a0-450d-9e93-10cb5027fd2c.png">

**Comment by paoliniluis** [comment]
Hey! @davidvirgilnaranjo, the first picture is a slack or email subscription with a multi-series card?

**Comment by davidvirgilnaranjo** [comment]
email subscription @paoliniluis 

The email subscriptions in general are displayed very differently than the website dashboards.

I am attaching how the x-axis values (when there is a date) are overlapped. In the metabase website questions, they are displayed fine.
<img width="553" alt="Screenshot 2023-02-03 at 11 17 08" src="https://user-images.githubusercontent.com/107469028/216590609-ad231ae4-25af-4702-b3b9-85a90c0ead45.png">
<img width="506" alt="Screenshot 2023-02-03 at 11 17 01" src="https://user-images.githubusercontent.com/107469028/216590616-09f2936e-5d22-47c6-9ed6-d8d3def8fc37.png">

**Comment by davidvirgilnaranjo** [comment]
At the moment I am not enabling email subscriptions to users, as  although they are asking me, they do not look good.

**Comment by davidvirgilnaranjo** [comment]
In general I see many problems:
x-axis are overlapped
Amounts being overlapped
the y-axis values as well are overlapped
There are 2 y-axis what makes the graph difficult to understand. The left y-axis is for one of the lines, and the other y-axis is for the other second series. What it would make sense is just to have one y-axis for both, as what you want to do is to compare both of them.
