### ISSUE TITLE
disable debug logging on api call paths

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2796]
Doesn't seem all that useful to have logs full of things like this ...

<img width="1048" alt="screen shot 2016-06-17 at 12 13 19 pm" src="https://cloud.githubusercontent.com/assets/1987787/16161973/291f94ae-3485-11e6-9652-aaf87c0386db.png">

**Comment by camsaul** [comment]
Probably makes more sense just to skip logging the health and logs endpoints but still log other API calls
