### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by sempervictus** [metabase/metabase#27972]
**Describe the bug**
Builds with `hydrogen` and `gallium` fail on Arch Linux with `HookWebpackError: error:0308010C:digital envelope routines::unsupported`

**Logs**
```clojure
   "[webpack-cli] HookWebpackError: error:0308010C:digital envelope routines::unsupported"
   "    at makeWebpackError (/build/metabase-git-sv/src/metabase/node_modules/webpack/lib/HookWebpackError.js:48:9)"
   "    at /build/metabase-git-sv/src/metabase/node_modules/webpack/lib/Compilation.js:3060:12"
   "    at eval (eval at create (/build/metabase-git-sv/src/metabase/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:88:1)"
   "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
   "-- inner error --"
   "Error: error:0308010C:digital envelope routines::unsupported"
   "    at new Hash (node:internal/crypto/hash:71:19)"
   "    at Object.createHash (node:crypto:133:10)"
   "    at module.exports (/build/metabase-git-sv/src/metabase/node_modules/terser-webpack-plugin/node_modules/webpack/lib/util/createHash.js:135:53)"
   "    at /build/metabase-git-sv/src/metabase/node_modules/terser-webpack-plugin/dist/index.js:262:40"
   "    at /build/metabase-git-sv/src/metabase/node_modules/p-limit/index.js:23:31"
   "    at run (/build/metabase-git-sv/src/metabase/node_modules/p-limit/index.js:23:43)"
   "    at /build/metabase-git-sv/src/metabase/node_modules/p-limit/index.js:45:20"
   "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
   "caused by plugins in Compilation.hooks.processAssets"
   "Error: error:0308010C:digital envelope routines::unsupported"
   "    at new Hash (node:internal/crypto/hash:71:19)"
   "    at Object.createHash (node:crypto:133:10)"
   "    at module.exports (/build/metabase-git-sv/src/metabase/node_modules/terser-webpack-plugin/node_modules/webpack/lib/util/createHash.js:135:53)"
   "    at /build/metabase-git-sv/src/metabase/node_modules/terser-webpack-plugin/dist/index.js:262:40"
   "    at /build/metabase-git-sv/src/metabase/node_modules/p-limit/index.js:23:31"
   "    at run (/build/metabase-git-sv/src/metabase/node_modules/p-limit/index.js:23:43)"
   "    at /build/metabase-git-sv/src/metabase/node_modules/p-limit/index.js:45:20"
   "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
   "error Command failed with exit code 2."
   "error Command failed with exit code 2."]}}
```

**To Reproduce**
1. Deploy dependencies:
```
makedepends=('git' 'npm' 'clojure')
depends=('jdk11-openjdk' 'nodejs-lts-hydrogen' 'yarn' 'openssl-1.1')
```
2. Build the uberjar:
```
build() {
  cd "${srcdir}/${_pkgrname}"
  export NODE_OPTIONS=--openssl-legacy-provider
  bin/build
}
```
3. See error

**Expected behavior**
Built jar
**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Metabase version: master
- Metabase hosting environment: Arch Linux
- Metabase internal database: None - build process fails
- Relevant packages:
```
Name            : yarn
Version         : 1.22.19-1

Name            : nodejs-lts-gallium
Version         : 16.19.0-1

Name            : openssl-1.1
Version         : 1.1.1.s-4

Name            : clojure
Version         : 1.11.1.1208-1
```

**Severity**
Blocking testing/use/adoption

**Comment by paoliniluis** [comment]
@sempervictus why are you building Metabase from scratch rather than using the JAR or the release container? If the build fails, you can use the Dockerfile in the root folder to build the project.

This issue is due to an TLS stuff in Node.js, I think you need to build with NODE_OPTIONS=--openssl-legacy-provider

**Comment by sempervictus** [comment]
@paoliniluis - as i stated in my issue description i _am_ building with `export NODE_OPTIONS=--openssl-legacy-provider`, using the `bin/build` mechanism described in the documentation.
The reason i am doing this is to create a PKGBUILD for Arch to maintain the platform in our repos for rapid deployment to our own servers. Not a big fan of Docker - fine for testing, but not so great for production (especially on Arch where OCI can change underfoot pretty quick).

**Comment by sempervictus** [comment]
@paoliniluis - why did you close the issue as completed? I appreciate the reply and all, but no new information was included and no remedy provided to the problem at hand (using docker side-steps the problem by leveraging another distribution's userspace, doesn't actually fix it).
