### ISSUE TITLE
CSV export broken for native SQL questions/queries

### ISSUE THREAD

**Issue by Steff81** [metabase/metabase#2799]
CSV export broken for native SQL questions/queries

*  I am using no browser.
*  My computer's OS is ElCaptian 10.11.1.
*  I'm running Metabase locally with the Mac App.
*  My database is MySQL.
*  My Metabase version is 0.17.1.

CSV Export seems not to work for a native SQL query. I have a query with 20 results and 8 columns. Nothing special so. When I try to download the CSV from the result,there is only generated a cvs file with the following content: 
{"errors":{"query":"field is a required param."}}

Normal questions/queries without native SQL can be exported as cvs without any problems.

**Comment by agilliland** [comment]
I've just tried reproducing this on the pending 0.18.0 release branch and downloading a CSV from a SQL query worked without issue, so I am assuming that this is something more specific to your particular installation or it's already been fixed.

0.18.0 is set to come out very soon, so I'll leave this open and you can verify that it's fixed after you upgrade.

**Comment by Steff81** [comment]
Thanks, maybe you can give it another try without saving the question. So create a new question with a sql, execute it and export the query without saving it.  If this also works for you I have no idea what causes the problem on my side.

**Comment by camsaul** [comment]
I haven't been able to reproduce this. @Steff81 are you still seeing this issue?

**Comment by camsaul** [comment]
@Steff81 are you still seeing this?

**Comment by Steff81** [comment]
@camsaul  No It seems to look fine with the latest version . Thanks.
