### ISSUE TITLE
"Week" aggregation is inconsistent with setting "Start of the week" is set to "Monday"

### ISSUE THREAD

**Issue by kaklakariada** [metabase/metabase#28018]
A user created [an issue](https://github.com/exasol/metabase-driver/issues/59) for our Exasol driver. I could reproduce the issue with both the Exasol and the MySQL driver, so I assume this is a problem in the core Metabase.

**Describe the bug**
When setting "Start-of-the-week" is set to "Monday" and we use a query builder then a weekly aggregation query gets wrong result - the first day of the aggregation is the Tuesday of previous week.
If setting "Start-of-the-week" is set to "Sunday" all works correct.

**Logs**
(no logs where generated)

**To Reproduce**
1. In MySQL or Exasol create the following test data

<details>
<summary>SQL Script</summary>

```sql
create schema bd;
create table bd.TAB (col TIMESTAMP);
insert into bd.TAB VALUES
('2023-12-01 00:00:00.000'),
('2023-12-02 00:00:00.000'),
('2023-12-03 00:00:00.000'),
('2023-12-04 00:00:00.000'),
('2023-12-05 00:00:00.000'),
('2023-12-06 00:00:00.000'),
('2023-12-07 00:00:00.000'),
('2023-12-08 00:00:00.000'),
('2023-12-09 00:00:00.000'),
('2023-12-10 00:00:00.000'),
('2023-12-11 00:00:00.000'),
('2023-12-12 00:00:00.000'),
('2023-12-13 00:00:00.000'),
('2023-12-14 00:00:00.000'),
('2023-12-15 00:00:00.000'),
('2023-12-16 00:00:00.000'),
('2023-12-17 00:00:00.000'),
('2023-12-18 00:00:00.000'),
('2023-12-19 00:00:00.000'),
('2023-12-20 00:00:00.000'),
('2023-12-21 00:00:00.000'),
('2023-12-22 00:00:00.000'),
('2023-12-23 00:00:00.000'),
('2023-12-24 00:00:00.000'),
('2023-12-25 00:00:00.000'),
('2023-12-26 00:00:00.000'),
('2023-12-27 00:00:00.000'),
('2023-12-28 00:00:00.000'),
('2023-12-29 00:00:00.000'),
('2023-12-30 00:00:00.000'),
('2023-12-31 00:00:00.000'),
('2023-01-02 00:00:00.000'),
('2023-01-02 01:00:00.000'),
('2023-01-02 02:00:00.000'),
('2023-01-03 03:00:00.000'),
('2023-01-04 04:00:00.000'),
('2023-01-05 05:00:00.000'),
('2023-01-06 05:00:00.000'),
('2023-01-07 05:00:00.000'),
('2023-01-08 05:00:00.000'),
('2023-01-09 05:00:00.000'),
('2023-01-10 05:00:00.000'),
('2023-01-11 05:00:00.000'),
('2023-01-12 05:00:00.000'),
('2023-01-13 05:00:00.000'),
('2023-01-14 05:00:00.000'),
('2023-01-15 05:00:00.000'),
('2023-01-16 05:00:00.000'),
('2023-01-17 05:00:00.000'),
('2023-01-18 05:00:00.000'),
('2023-01-19 05:00:00.000'),
('2023-01-20 05:00:00.000'),
('2023-01-21 00:00:00.000');
```

</details>

2. Select "Monday" as "Start of the week" in Admin settings.
3. Aggregate data on "Week"
4. Find data belonging to previous week with Tuesday as first day of week.

**Expected behavior**
Data from previous week is not included in the result and first day of week is Monday.

**Example**
1. Prepare a query in the query builder with filter on date field
![image](https://user-images.githubusercontent.com/41777379/214798248-3c0b9153-c6f7-45c2-9060-ef2510a1fa2d.png)
2. Get results from previous week with wrong first day (27.12, 03.01 and 10.01 are Tuesdays) 
![image](https://user-images.githubusercontent.com/41777379/214798089-d5b638d7-73f5-4f5e-8bf1-b024aab51f09.png)

Here is the query that MB generates for Exasol:
```
SELECT (CAST(truncate(CAST(("BD"."TABLE"."COLUMN" + numtodsinterval(-1, 'day')) AS date), 'day') AS date) + numtodsinterval(1, 'day')) AS "COLUMN"
FROM "BD"."TABLE"
WHERE ("BD"."TABLE"."COLUMN" >= timestamp '2023-01-02 00:00:00.000'
   AND "BD"."TABLE"."COLUMN" < timestamp '2023-01-16 00:00:00.000')
GROUP BY (CAST(truncate(CAST(("BD"."TABLE"."COLUMN" + numtodsinterval(-1, 'day')) AS date), 'day') AS date) + numtodsinterval(1, 'day'))
ORDER BY (CAST(truncate(CAST(("BD"."TABLE"."COLUMN" + numtodsinterval(-1, 'day')) AS date), 'day') AS date) + numtodsinterval(1, 'day')) ASC
```
And executing this query without MB gives the same result.

**Setup**
* Metabase 0.45.2, 0.45.2.1
* Exasol-metabase-driver 1.0.3, 1.0.4

**Severity**
@ppavlov39 Please describe the impact of this issue for you.
(How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.)

**Additional context**
The original issue contains details about the queries generated for Exasol and MySQL: https://github.com/exasol/metabase-driver/issues/59#issuecomment-1410011096

**Comment by kaklakariada** [comment]
This might be related to https://github.com/metabase/metabase/issues/25356. I will investigate if this is an issue with the Exasol driver.

**Comment by ppavlov39** [comment]
Hi @kaklakariada!
This issue block nothing. But it can confuse users and get wrong results when they use week-aggregation in Metabase query-builder. So in order to rely on query results in Metabase, this should be fixed.

**Comment by kaklakariada** [comment]
The root cause for this problem was a non-default value for the Exasol database parameter `NLS_FIRST_DAY_OF_WEEK`, see [this comment](https://github.com/exasol/metabase-driver/issues/59#issuecomment-1413663763) for details.

To avoid issues like this in the future please consider implementing https://github.com/metabase/metabase/issues/13496.
