### ISSUE TITLE
Send "threads blocked" via Prometheus exporter

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28014]
**Is your feature request related to a problem? Please describe.**
We need this parameter https://github.com/metabase/metabase/blob/79b08ee8627ad2b3d4d7703e9aeb1a48db5d3493/src/metabase/server/middleware/log.clj#L82 to be exposed in Prometheus as a new metric so we can use it for alarms

**Describe the solution you'd like**
Expose the threads blocked parameter as a metric in Prometheus

**Describe alternatives you've considered**
Parse that from log lines

**How important is this feature to you?**
extremely important to detect instance issues

**Additional context**
NA

**Comment by dpsutton** [comment]
prior art for prometheus logging:
https://github.com/metabase/metabase/blob/master/src/metabase/analytics/prometheus.clj#L128 makes a few gauges for the c3p0 stats. we can make one more for this.
