### ISSUE TITLE
Error when exporting data in a public query

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#28027]
**Describe the bug**
When exporting data from a public query, the request displays an error and download does not start

The error doesn't always happen

**Logs**
DownloadButton.jsx:60 Refused to connect to '[http://bi.tre-rj.jus.br:3000/public/question/b94355aa-f09e-4cf7-8e6c-50a85c2236a7.xlsx?parameters=[{"type"%3A"category"%2C"value"%3A["119ª+ZE"]%2C"target"%3A["variable"%2C["template-tag"%2C"CAMINHO_UNIDADE"]]%2C"id"%3A"86a16a9c-7036-a5b0-20d6-8ccc09ab2c80"}]](http://bi.tre-rj.jus.br:3000/public/question/b94355aa-f09e-4cf7-8e6c-50a85c2236a7.xlsx?parameters=%5B%7B%22type%22%3A%22category%22%2C%22value%22%3A%5B%22119%C2%AA+ZE%22%5D%2C%22target%22%3A%5B%22variable%22%2C%5B%22template-tag%22%2C%22CAMINHO_UNIDADE%22%5D%5D%2C%22id%22%3A%2286a16a9c-7036-a5b0-20d6-8ccc09ab2c80%22%7D%5D)' because it violates the following Content Security Policy directive: "connect-src 'self' **https://accounts.google.com/ [metabase.us10.list-manage.com](http://metabase.us10.list-manage.com/)".**

DownloadButton.jsx:60 Refused to connect to '[http://bi.tre-rj.jus.br:3000/public/question/b94355aa-f09e-4cf7-8e6c-50a85c2236a7.xlsx?parameters=[{"type"%3A"category"%2C"value"%3A["119ª+ZE"]%2C"target"%3A["variable"%2C["template-tag"%2C"CAMINHO_UNIDADE"]]%2C"id"%3A"86a16a9c-7036-a5b0-20d6-8ccc09ab2c80"}]](http://bi.tre-rj.jus.br:3000/public/question/b94355aa-f09e-4cf7-8e6c-50a85c2236a7.xlsx?parameters=%5B%7B%22type%22%3A%22category%22%2C%22value%22%3A%5B%22119%C2%AA+ZE%22%5D%2C%22target%22%3A%5B%22variable%22%2C%5B%22template-tag%22%2C%22CAMINHO_UNIDADE%22%5D%5D%2C%22id%22%3A%2286a16a9c-7036-a5b0-20d6-8ccc09ab2c80%22%7D%5D)' because it violates the document's Content Security Policy.

The metabase is not being accessed through a proxy.

**To Reproduce**
1. Go to any question
2. Click on download and choose extension
3. See error (the error doesn't always happen)

**Expected behavior**
The download is expected to start without errors

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
"browser-info": {
"language": "pt-BR",
"platform": "Win32",
"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55",
"vendor": "Google Inc."
},
"system-info": {
"file.encoding": "Cp1252",
"java.runtime.name": "OpenJDK Runtime Environment",
"java.runtime.version": "17.0.4.1+1",
"java.vendor": "Eclipse Adoptium",
"java.vendor.url": "https://adoptium.net/",
"java.version": "17.0.4.1",
"java.vm.name": "OpenJDK 64-Bit Server VM",
"java.vm.version": "17.0.4.1+1",
"os.name": "Windows Server 2012 R2",
"os.version": "6.3",
"user.language": "pt",
"user.timezone": "GMT-3"
},
"metabase-info": {
"databases": [
"oracle",
"postgres",
"h2"
],
"hosting-env": "unknown",
"application-database": "postgres",
"application-database-details": {
"database": {
"name": "PostgreSQL",
"version": "9.6.14"
},
"jdbc-driver": {
"name": "PostgreSQL JDBC Driver",
"version": "42.5.0"
}
},
"run-mode": "prod",
"version": {
"date": "2022-12-07",
"tag": "v0.45.1",
"branch": "release-x.45.x",
"hash": "019d31c"
},
"settings": {
"report-timezone": null
}
}
}

**Severity**
The error has high severity, as it prevents the download of query results

**Comment by paoliniluis** [comment]
You need to use Java 11 ad Java 17 is not yet supported. Also, do you have the anonymous stats sending enabled?

**Comment by tatusis** [comment]
It's disabled. We have been using java 17 for some time now.

**Comment by tatusis** [comment]
I tested and the problem persists.

**Comment by paoliniluis** [comment]
Do you use Cloudfront/Cloudflare or any CDN in front of Metabase?

**Comment by tatusis** [comment]
No. We don't.

**Comment by joekohlsdorf** [comment]
Exactly the same problem here, only affects downloads on public dashboards.
I have a proxy in front of Metabase which does HTTPS termination, no CDN.

Using Metabase v0.45.2.1

**Comment by mattiloh** [comment]
We encounter the same problem. Everything works fine except downloading exports from public questions.
We have an Elastic Beanstalk Docker setup with Cloudfront for SSL. Worked fine until we updated to the latest version  `0.45.2.1` last week.

**Comment by paoliniluis** [comment]
Do you have in the site url config (settings->admin->general->site url) the same url and protocol you see in the browser when you try to download an export?

**Comment by mattiloh** [comment]
> Do you have in the site url config (settings->admin->general->site url) the same url and protocol you see in the browser when you try to download an export?

Thanks @paoliniluis! That fixed the issue. I somehow missed that setting. I searched for it in the env variables, but having it in the settings panel is of course much more convenient 😅

**Comment by tatusis** [comment]
> Do you have in the site url config (settings->admin->general->site url) the same url and protocol you see in the browser when you try to download an export?

Yes. In our configuration the urls are identical. I would like to remind you that the error is intermittent, and sometimes the error does not appear.

**Comment by paoliniluis** [comment]
@tatusis what about any reverse proxy?

**Comment by paoliniluis** [comment]
@tatusis can you post the stack here? there's something going on with the CSP here which should be either a reverse proxy or a CDN manipulating things

**Comment by paoliniluis** [comment]
no more activity
