### ISSUE TITLE
Dashboard Email Subscription doesn't allow me which Questions to attach but sends all Questions

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#28033]
**Describe the bug**
Email Subscription doesn't allow me to select which Questions to attach but ends up sending all Questions within a dashboard

**To Reproduce**
1. Go to New Question -> People -> Save
2. Go to New Question -> Orders -> Save
3. Go to New Dashboard -> Add these 2 questions in the Dashboard
4. Select Subscription -> Email it -> Select your e-mail -> Attach results 

Now you will notice two issues

5) Issue 1 - You will notice that when you click Attach Results. The attachments are not selected but clicking the `Send Now` button will still sent two attachments

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/110378427/216396401-1b16fa51-d31b-4c20-aec8-ddf9ff66f041.png">

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/110378427/216397453-37728ae0-643e-45a4-a1fc-6a51fc9fed84.png">

6) Issue 2 - Click one of the attachments and click  `Send Now` button will also still sent two attachments

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/110378427/216397864-2fcd26d2-1c68-4325-848e-d26de52451fb.png">

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/110378427/216399256-11eea37a-61de-4595-965e-2095c9ccb442.png">

**Expected behavior**
I am able to select which attachment to send via e-mail if i am given the option

**Information about your Metabase Installation:**

Replicated on 1.45.2.1 and `Master`

**Comment by nemanjaglumac** [comment]
What happens if you select `.xlsx` with one question only?

**Comment by Tony-metabase** [comment]
That's very odd cause. I would say it's working since just the Orders was send as `.xlsx` the other was send as csv

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/110378427/216558693-a66f602f-3450-40bd-9ffd-cfd1e2f0d3be.png">

**Comment by luizarakaki** [comment]
@Tony-metabase 
We always attach results from all table visualizations that exceed 10 rows. Regardless of what the user chooses.
It is an inconvenient that it isn't well communicated and it is not consistent with the user choice, but there is a reason.

I'm keeping the bug tag but moving to P3

**Comment by Tony-metabase** [comment]
@paoliniluis you are right ... Closing in favour of https://github.com/metabase/metabase/issues/18981
