### ISSUE TITLE
Improve applicability of Metabase to applications with lower time intervals

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2803]
In chatting with the Crate folks, they mentioned that they were seeing a number of people interested in using Metabase on top of a Crate cluster containing sensor data. 

In these situations, there is a desire to dig into tight time granularities. I think we can make it much more useful to this kinds of situations with two simple additions. 
- [ ] Add smaller time intervals in the grouping menu
- [ ] Add a "nuke your database" dashboard autorefresh setting where as soon as one update finishes, we start another one.

The latter will be pretty cheap for Druid + Crate, though I'm not a huge fan of people using it on redshift or bigger MySQL/PostgreSQL DBs.

@kdoh + @mazameli thoughts on the first item? This gets dangerously close to every-option-ever vomited into userland for me

**Comment by camsaul** [comment]
The "smaller time intervals in the grouping menu" part of this was implemented by #14512. Since we have a separate issue for Dashboard autorefresh settings (#7133) I'm going to close this out 

Implemented by #14512
