### ISSUE TITLE
Formatting column as link using another column with full url doesn't work

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#28043]
**Describe the bug**
I have 2 columns: name and url. When I format name to display as a link using the value of {{url}} in Link URL, it is creating a relative url  instead of absolute, which won't work as it would prefix the url with the Metabase instance. If I do prefix with https://{{url}}, then it does create an absolute url, but the {{url}} column already has that and won't work if I prefix it again. 

**Logs**
n/a

**To Reproduce**
1. Find table with 2 columns -- one that's a name and another that contains an absolute/full url. 
2. Format name column as link with Link URL of {{url}} column. 
3. Click on linked name column value
4. Browser goes to bad link

**Expected behavior**
If {{url}} contains http:// or https:// then it should be treated as absolute/full url instead of relative and it should open {{url}} without prefixing with Metabase instance's current url. It seems existing code is checking the pre-rendered value, so perhaps just check the rendered value? If that's not easy, alternatively check for string that starts with "{{" along existing check for http:/https:.  

**Screenshots**
n/a

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (Chrome
- Your operating system: OS X
- Your databases: Postgres
- Metabase version: master
- Metabase hosting environment: Metabase Cloud Dev
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
I can work around it by re-constructing the url using https:// and another column instead of the {{url}} column with full url. I could also format url as a link with link text of {{name}}. But it's just better if I can format name as link. 

**Additional context**
n/a

**Comment by Nicolasvegam** [comment]
same problem here!

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/42438
