### ISSUE TITLE
Add a search box for foreign key target dropdown in Data Model

### ISSUE THREAD

**Issue by CaliLuke** [metabase/metabase#2805]
When mapping Foreign Keys in the schema editor the user is presented with a list of tables which can be very long in some cases. I propose to make a simple change and add a filtering option or at least a way to jump to a certain alphabetic group by using the keyboard. See an example of the problem:

![2016-06-20_17-20-31](https://cloud.githubusercontent.com/assets/73209/16210979/ea70c4be-370c-11e6-9956-c7bd3b400b22.png)

**Comment by CaliLuke** [comment]
Here is a quick mock I made from the previous screenshot, excuse the crudeness.

![2016-06-20_17-20-31](https://cloud.githubusercontent.com/assets/73209/16211059/4be13008-370d-11e6-9bbf-cf46e69cb419.png)

**Comment by mazameli** [comment]
Implemented in https://github.com/metabase/metabase/pull/11912 and will be included in 0.35.
