### ISSUE TITLE
Admins seeing "All personal collections" in New question data picker can lead to performance issues

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#28068]
**Describe the bug**
Admins have the option to start a new question based on any question saved in any of the (potentially hundreds and thousands) other users' personal collections. This is sub-optimal for large instances.

**To Reproduce**
_Log in as admin_
1. Create several additional users 
2. Have at least one saved question in ANY collection
3. Create new question with "New > Question" and then
4. Click on "Saved questions" in the data picker
![image](https://user-images.githubusercontent.com/31325167/216704283-2ac2caf9-82b5-497e-ab79-5c07dc9198b2.png)

Notice two things:
1. UI displays "All personal collections"
2. Network tab reveals that the call to `GET /api/collection/tree?tree=true` has been made

**Expected behavior**
Not an easy thing to say because this behavior was in the product for a very long time.
- One approach would be to completely remove "All personal collections" from the question picker, but that would most likely break flows and expectations for many people
- Another approach would be to not show empty personal collections
- One more approach would be to introduce pagination or something similar, but that requires new design

**Information about your Metabase Installation:**
local dev, `master`, 52df7fcaef74f6e068d670c886287e6b4f49a561, H2, Sample database

**Severity**
P1 performance.
On large instances with hundreds or even thousands of users, this can lead to performance penalties.

**Additional context**
This is a sister issue of https://github.com/metabase/metabase/issues/24330.

Related: https://github.com/metabase/metabase/issues/15339

**Comment by markbastian** [comment]
I'm trying to reproduce this (see the recording). I do see the pause on expansion of the "All personal collections" node, but there is no additional network traffic when this happens.

![28068-1](https://user-images.githubusercontent.com/8381441/219121762-bd25f058-be97-44a0-9628-2afce3be2b63.gif)

**Comment by markbastian** [comment]
Not the issue that is reported, but adjacent -- when I choose "Raw Data" from the data source drop down the app just spins on the collection list, seemingly forever.

![28068](https://user-images.githubusercontent.com/8381441/219122776-f90ffe70-1868-4da2-98f7-de4da65650f1.gif)

**Comment by nemanjaglumac** [comment]
Dialing down the P-level of this issue because @markbastian did an amazing job at testing the application with 1500 generated users and didn't see significant delays.

If we get concrete feedback with the specific time or a screenshot/video recording of a real-world application that suffers because of this, we can re-consider making this issue a higher priority.
