### ISSUE TITLE
Allow for nested fields to be accessed in MongoDB collections

### ISSUE THREAD

**Issue by aelanic** [metabase/metabase#2807]
If this is a bug report, please fill in the blanks:

*  I am using the Google Chrome browser.
*  My computer's OS is Mac OSX.
*  I'm running Metabase locally with the Mac App. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is MongoDB.
*  My Metabase version is 0.17.1.

**Comment by aelanic** [comment]
Nested fields are not accessible for MongoDB in Metabase. I think this is a critical functionality for Metabase to be adopted amongst MongoDB developers.

**Comment by camsaul** [comment]
Duplicate of #1328
