### ISSUE TITLE
Disallow robots

### ISSUE THREAD

**Issue by martinbohman** [metabase/metabase#2808]
It would be useful with a setting for disallowing robots / search engine indexing.
I imagine many use Metabase for internal statistics and there is no need for that to be indexed, even if it's just the login page.

**Comment by salsakran** [comment]
@MartinBohman that sounds like a reasonable idea. Want to help out by creating a robots file and adding it to our routes? =)

**Comment by raphamotta** [comment]
Hi guys. Any news about it?

**Comment by ipeevski** [comment]
Happy to try to help.

The file needs to be 
robots.txt
```
User-agent: *
Disallow: /
```

Any tips on how to modify the routes?

**Comment by ipeevski** [comment]
In addition to that, there is a meta tag that can be added to the header
`<meta name="robots" content="noindex">`
as per Google's recommendation: https://support.google.com/webmasters/answer/93710

**Comment by flamber** [comment]
Fixed by #11862
