### ISSUE TITLE
Scrolling up on schema list jumps to the top when creating a new question

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#28106]
**Describe the bug**
When creating a new question, I selected Raw Data and then clicked on a database (Postgres) that shows a list of schema -- it has at least 30 schemas. When scrolling down to view the list of schema, it seems fine, but as soon as you try scrolling up, it jumps to the top of the list instead of scrolling smoothly. 

**Logs**
n/a

**To Reproduce**
1. Create a database with at least 30 schemas. A small # like 2 won't surface the issue. 
2. Create a new question and browse to the database to show the list of schemas
3. Scroll down to view the end of the schema list
4. Scroll up and it will jump to the top of the list instantly. 

**Expected behavior**
When scrolling up, it should scroll up smoothly just like scrolling down. 

**Screenshots**
n/a

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: OS X
- Your databases: Postgres
- Metabase version: master
- Metabase hosting environment: Metabase Cloud Dev
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It's a bit annoying and also makes it harder to find what you are looking for if you didn't find it when scrolling down. 

**Additional context**
n/a

**Comment by kamilmielnik** [comment]
I can reproduce the issue in v48 ([recording](https://github.com/metabase/metabase/assets/6830683/20aaabe2-3ab3-42dd-9c05-d2a3e12cd5c2)).

We have a new Data Picker since v50.
The old schema list component is not used anymore and the new one does not have any issues like this.
