### ISSUE TITLE
Column name with question mark makes filter fail

### ISSUE THREAD

**Issue by remilepriol** [metabase/metabase#28112]
**Describe the bug**
A table booking has a field `client` and a field `referral?`. When I filter on `client='someone'`, the query fails because Metabase sent the following query 
```sql
-- Metabase:: userID: 49 queryType: MBQL queryHash: 1f4705
SELECT "booking"."booking id" AS "booking id",
	"booking"."referral'someone'" AS "referral?",
	"booking"."client" AS "client"
FROM "booking"
WHERE "booking"."client" = ?
LIMIT 2000
```
so it seems that this metabase is replacing the first question mark it finds with the filtered value here.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

Error message
```
[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. SYNTAX_ERROR: line 2:1: Incorrect number of parameters: expected 1 but found 0 [Execution ID: 699236f4-7f63-4837-9c3b-7cff14afb980]
```

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-16",
      "tag": "v0.43.1",
      "branch": "release-x.43.x",
      "hash": "7f1a1c4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

This is a light issue, slightly annoying as I do not have full control over these column names since they are meant for being exported to another client facing app. 

**To Reproduce**
This may be reproducible on the sample database but I did not try it.

**Expected behavior**

**Comment by paoliniluis** [comment]
Hi, please upgrade Metabase to the latest version and try again, we included the Athena version in the latest version. If upgrading to 45.2.1 didn't fix the issue please feel free to reopen the issue again. I just tried with Postgres and everything works

**Comment by remilepriol** [comment]
So it turns out that upgrading to v0.45.3 did not solve this issue.
