### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by hanxiang01** [metabase/metabase#28113]
When I upgrade from 0.37.0.2 to the latest version and then reboot, it keeps reporting an error and I can't find a solution for it in the forum.
The error message is as follows:

[2023-02-07 09:19:10,212 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. ? 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2023-02-07 09:19:26,407 INFO metabase.util :: Maximum memory available to JVM: 1.7 GB]

thank you.

**Comment by Tony-metabase** [comment]
What error? those are INFO logs one is saying you have encryption disabled and the other the Maximum memory available to JVM

**Comment by hanxiang01** [comment]
thank you for reply.
error:
【Exception in thread "main" java.lang.UnsupportedClassVersionError: com/vladsch/flexmark/ast/HtmlInlineComment has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0】

But I've upgraded my jdk version：
【java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)】

Which is the correct version of jdk to use?
thank you

**Comment by paoliniluis** [comment]
You're running an unsopported version of Java. We only support Java 11 https://www.metabase.com/docs/latest/installation-and-operation/java-versions
