### ISSUE TITLE
Do not offer Move or Archive for personal collections

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#28127]
**Describe the bug**
As of https://github.com/metabase/metabase/pull/28023, we display subcollections in a parent collection view. For root collection ("Our analytics"), those are admin's own and everyone else's personal collections. That alone can be problematic for instances with large number of users, but that's a separate problem. (Related #24330)

If we already display personal collections, we shouldn't offer neither "Move", nor "Archive" actions for them.
This goes both for the `...` menu next to the item, and for when we select the item and then have the bulk edit collection actions at the bottom of the screen.

**To Reproduce**
_Log in as an admin_
1. Go to `/collections/root`
2. See your own personal collection in the list of collection items
(nit: Why is it called "Your personal collection" in the sidebar but not here?)
3. Click on the ellipsis menu `...` and notice "Move" and "Archive", which will not have any effect and are just confusing
![image](https://user-images.githubusercontent.com/31325167/217351771-48ecc867-7684-4145-a180-342b38981e92.png)
4. The same thing happens if you click on the icon to select this collection (see the bottom bulk action toolbar)
![image](https://user-images.githubusercontent.com/31325167/217352253-cc098744-b191-4ac8-8dc5-df28c22727a6.png)

```js
`PUT /api/collection/:id`

// responds with
`500 Server Error`
```

**Expected behavior**
Do not offer Move or Archive for personal collections

**Information about your Metabase Installation:**
local dev, `master`, ffa0362, H2, Sample Database

**Severity**
P3, only because it's not possible to execute the action.

**Comment by ranquild** [comment]
Fixing this would require adding `personal_owner_id` to `/api/collection/root/items` and `/api/collection/:id/items` endpoints.

**Comment by markbastian** [comment]
On a related note, should archived collections be visible in the move dialog (as shown here)?

![moves](https://user-images.githubusercontent.com/8381441/217849705-873962eb-de59-4f1a-97c2-dd265623ecb7.gif)

**Comment by markbastian** [comment]
> Fixing this would require adding personal_owner_id to /api/collection/root/items and /api/collection/:id/items endpoints.

To be sure I understand, you just need `personal_owner_id` returned from those two endpoints for this to work?

**Comment by ranquild** [comment]
@markbastian I believe it should be enough, I'll double check and post an update
