### ISSUE TITLE
Add documentation on how to upgrade your Metabase instance

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2812]
Can't find anything in the docs, and the question has come up a few times.

**Comment by rNianios** [comment]
Yes I second that. I just came to look for it! Please add how we can stop the current metabase instance without losing any data and replace the old version with the new one.

**Comment by marketingnerds** [comment]
Assuming you're not using EBS but for those who are:

http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#deploying-new-versions-of-metabase

**Comment by salsakran** [comment]
also for posterity, if you're using heroku - http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html#deploying-new-versions-of-metabase

**Comment by key88sf** [comment]
Version number for the EB upgrade is wrong.

Web page:
http://www.metabase.com/docs/v0.18.0/operations-guide/running-metabase-on-elastic-beanstalk.html#deploying-new-versions-of-metabase

Error:  The download link on that page is pointing to the 0.17.1 ZIP file.
