### ISSUE TITLE
Metabase doesn't realize that Redshift aborts a query

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28136]
**Describe the bug**
Just checked on a customer instance that Metabase won't know that Redshift has aborted a query and will keep the spinner going round. This one is a tricky one to debug as I cannot come up with a reproduction environment

**Logs**
When Redshift aborts, Metabase prints the stack trace, but it won't stop the spinner or cut the connection. The log from redshift seems to be something like :

```
{:type "native",
--
  |   | 2023-02-07 19:11:41 | :json_query
  |   | 2023-02-07 19:11:41 | :error_type :invalid-query,
  |   | 2023-02-07 19:11:41 | :state "XX000",
  |   | 2023-02-07 19:11:41 | :type :invalid-query}}],
  |   | 2023-02-07 19:11:41 | :params nil,
```
```
:class clojure.lang.ExceptionInfo,
--
  |   | 2023-02-07 19:11:41 | [{:status :failed,
  |   | 2023-02-07 19:11:41 | :via
  |   | 2023-02-07 19:11:41 | :started_at #t "2023-02-07T22:05:29.639839Z[GMT]",
  |   | 2023-02-07 19:11:41 | {:database_id 2,
  |   | 2023-02-07 19:11:41 |  
  |   | 2023-02-07 19:11:41 | -----------------------------------------------
  |   | 2023-02-07 19:11:41 | process:   padbmaster [pid=30679]
  |   | 2023-02-07 19:11:41 | location:  queryabort.hpp:83
  |   | 2023-02-07 19:11:41 | query:     397994178
  |   | 2023-02-07 19:11:41 | context:   system requested abort
  |   | 2023-02-07 19:11:41 | code:      1020
  |   | 2023-02-07 19:11:41 | error:  abort query
  |   | 2023-02-07 19:11:41 | -----------------------------------------------
  |   | 2023-02-07 19:11:41 | Detail:
  |   | 2023-02-07 19:11:41 | 2023-02-07 22:11:41,671 ERROR middleware.catch-exceptions :: Error processing query: ERROR: abort query
```

**To Reproduce**
I can't make a reproduction, but it will be something like:
1) build a query in Metabase that takes a long long time
2) get the PID of that query and cancel it (https://docs.aws.amazon.com/redshift/latest/gsg/cancel_query.html)

**Expected behavior**
We should know that and cut the connections, also expose this on the FE

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your databases: Redshift
- Metabase version: 1.45.2.1

**Severity**
P1

**Additional context**
Seen in a customer instance

**Comment by camsaul** [comment]
Closing as already fixed, PR #44726 proves that it's fixed but it's a bit flaky so I'm going to hold off on merging it in until I figure out how to make the test more reliable.
