### ISSUE TITLE
Dashboard filters for SQL questions

### ISSUE THREAD

**Issue by spinx** [metabase/metabase#2813]
Hey,

I'm very excited to see dashboard filters in Metabase, thank you all, I saw it was a huge effort!

I can't seem to have them work for SQL questions though, even if I convert a normal question to an SQL one. Was this not implemented or am I a tool ?

Thanks!

**Comment by salsakran** [comment]
SQL question support is coming! 
We have a PR open (#2795) but we're still ironing out a few UX concerns. 
dupe of #2348 

Expect it soon!
