### ISSUE TITLE
World map choropleth should recognize country names, not only two-letter ISO country codes

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#28139]
If you have a result that looks like this, with ISO country codes, our world map choropleth visualization will happily make the US, Brazil, and Argentina blue:

| Country code | Count |
|--------------|--------|
|US | 10|
| BR | 5 |
| AR | 3 |

But this data will get you a completely gray map:

| Country code | Count |
|--------------|--------|
|United States | 10|
| Brazil | 5 |
| Argentina | 3 |

Our world map visualization should be smart enough to recognize at least English representations of country names.

For an example of this problem, look up our "World map of Metabase employees" in our own Stats instance.

**Comment by EmmadUsmani** [comment]
@mazameli Should be working on master now
