### ISSUE TITLE
Save changes button in greyed out once making a changes in model

### ISSUE THREAD

**Issue by rocky57** [metabase/metabase#28147]
When I am making a changes in model (removing joins, adding new filters). Save changes button is greyed out.
My workaround is to go to Metadata tab and put fake description in column description area, then Save changes is avialable.
However bottom most view data still shows columns which I've for example removed from grouping - is it intendent behaviour?

I am using latest docker image.
Kind regards,
Piotr

**Comment by paoliniluis** [comment]
This is a question for Discourse (discourse.metabase.com) as we don't have enough information to see what's going on since you didn't follow the template
