### ISSUE TITLE
Dashboard level timezone setting

### ISSUE THREAD

**Issue by imiskolee** [metabase/metabase#28141]
Hi,team:

If our services support anywhere and want to make some dashboards with different time zone. just LIKE

* Sales - US
* Sales - CN
* Sales - JPY

**Comment by brunobergher** [comment]
@imiskolee mind expanding on this? Do you want the questions in the dashboard to adjust to these different timezones? Or to have multiple tabs, one of each with different questions for that team's territory?

**Comment by paoliniluis** [comment]
You should be able to achieve this with Sandboxing, users have a timezone associated and when they log in, that's passed to Metabase that renders the timestamps in different timezones
