### ISSUE TITLE
Incorrect SQL generated in docker image

### ISSUE THREAD

**Issue by rocky57** [metabase/metabase#28146]
Hello, 
I've get latest version of metabase docker container and I found couple of issues.
When I am trying to group by Month number it generates incorrect SQL:

SELECT TOP 1048575 "source"."DimProduct - ProductKey__ProductCategory" AS "DimProduct - ProductKey__ProductCategory"
	,"source"."DimDate - OperationDateKey__MonthYear" AS "DimDate - OperationDateKey__MonthYear"
	,"source"."DimDate - OperationDateKey__MonthName" AS "DimDate - OperationDateKey__MonthName"
	,"source"."DimDate - OperationDateKey__Month" AS "DimDate - OperationDateKey__Month"
	,"source"."sum" AS "sum"
FROM (
	SELECT TOP 1048575 "DimProduct - ProductKey"."ProductCategory" AS "DimProduct - ProductKey__ProductCategory"
		,"DimDate - OperationDateKey"."MonthYear" AS "DimDate - OperationDateKey__MonthYear"
		,"DimDate - OperationDateKey"."MonthName" AS "DimDate - OperationDateKey__MonthName"
		,((floor((("DimDate - OperationDateKey"."Month" - 0.0) / 2)) * 2) + 0.0) AS "DimDate - OperationDateKey__Month"
		,sum("dbo"."FactDocumentLineItems"."TotalGrossPrice") AS "sum"
	FROM "dbo"."FactDocumentLineItems"
	INNER JOIN "dbo"."DimProduct" "DimProduct - ProductKey" ON "dbo"."FactDocumentLineItems"."ProductKey" = "DimProduct - ProductKey"."ProductKey"
	INNER JOIN "dbo"."DimDate" "DimDate - OperationDateKey" ON "dbo"."FactDocumentLineItems"."OperationDateKey" = "DimDate - OperationDateKey"."DateKey"
	WHERE (
			"DimProduct - ProductKey"."ProductCategory" = 'źródła światła'
			AND (
				"DimDate - OperationDateKey"."MonthYear" = '2020APR'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020AUG'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020DEC'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020FEB'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020JAN'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020JUL'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020JUN'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020MAR'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020MAY'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020NOV'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020OCT'
				OR "DimDate - OperationDateKey"."MonthYear" = '2020SEP'
				)
			)
	GROUP BY "DimProduct - ProductKey"."ProductCategory"
		,"DimDate - OperationDateKey"."MonthYear"
		,"DimDate - OperationDateKey"."MonthName"
		,((floor((("DimDate - OperationDateKey"."Month" - 0.0) / 2)) * 2) + 0.0)
	ORDER BY ((floor((("DimDate - OperationDateKey"."Month" - 0.0) / 2)) * 2) + 0.0) ASC
		,"DimProduct - ProductKey"."ProductCategory" ASC
		,"DimDate - OperationDateKey"."MonthYear" ASC
		,"DimDate - OperationDateKey"."MonthName" ASC
	) "source"

I don't know why it is adding floor function to month number, which i causing below results:
![image](https://user-images.githubusercontent.com/4228063/217535672-8166249e-a44d-4415-ae5f-a5a47bb2b276.png)

I am starting with Metabase, could it be an issue with data model (in administration settings)

**Comment by paoliniluis** [comment]
This is a question for Discourse (discourse.metabase.com) as we don't have enough information to see what's going on since you didn't follow the template
