### ISSUE TITLE
Improve UX for displaying archived cards on dashboards

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2815]
Current behavior: if I've archived a question but it's still present on a dashboard, this is how it's rendered:

![screen shot 2016-06-22 at 10 03 01 am](https://cloud.githubusercontent.com/assets/2223916/16275844/b0390b08-3860-11e6-86cb-2b5b61c0159a.png)

This message is unclear, and I think we should be more helpful in the error message and say "This question has been archived" with a link that says "see archived questions." (Or possibly a button to unarchive it?)

**Comment by flamber** [comment]
I cannot reproduce this on 0.31.2
- Create question, save to Personal Collection
- Create dashboard, add above question, save to Personal Collection
- Archive question and result: Question is removed from dashboard.
