### ISSUE TITLE
Log scale doesn't show y-axis values when data points are close to each other

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#28186]
**Describe the bug**
Log scale doesn't show y-axis values when data points are close to each other

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to New -> Question -> Sample Database -> Orders -> Sum(Total) grouped by Month(Created Date)
2. Visualisation Settings -> Line -> Axis -> Y-axis Log Scale ... Note that values are visible

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/110378427/217815885-571a647e-88e5-4c93-966d-d76e7bee2fc9.png">

3. Now go back to GUI Editor -> Filter where Sum of Tax > 45506 ... Notice there are no y-axis visible anymore

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/110378427/217816311-aa6da2bd-8766-4072-aa1a-1b49062b306e.png">

**Expected behavior**
y-axis should be visible

**Information about your Metabase Installation:**

Able to replicate this on 45.2.1 and `master`

**Additional context**
Works if I select power or linear

**Comment by JesseSDevaney** [comment]
Could not reproduce:


https://github.com/metabase/metabase/assets/22608765/d23001e3-bef0-4c0f-baa2-f2f0ac89e382

**Comment by Tony-metabase** [comment]
Confirmed it works as expected on Master now
