### ISSUE TITLE
Maintain user-level state in dashboards for filters

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28181]
**Is your feature request related to a problem? Please describe.**
If a user uses a dashboard and picks some filters, it would be a good idea to maintain that state if the filters don't have a default value, so when the user comes back to the dashboard, it opens with the values the user picked before

**Describe the solution you'd like**
Maintain state of the filters at the dashboard level per user. Also a "reset" button could be useful so a user can reset the dashboard state to the initial one

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by uladzimirdev** [comment]
we need more information about the expected use cases

**Comment by uladzimirdev** [comment]
implemented https://github.com/metabase/metabase/issues/39809
