### ISSUE TITLE
Hour-of-day line charts ordered incorrectly

### ISSUE THREAD

**Issue by akita-ken** [metabase/metabase#2819]
*  I am using the Google Chrome (v51.0.2704 - x86-64) browser.
*  My computer's OS is Mac OS X 10.11.5.
*  I'm running Metabase locally from the JAR.
*  My database is H2.
*  My Metabase version is 0.18.0.

I'm trying to plot simple 'count by hour' data, but it seems that 2AM is being inserted in between 7PM and 8PM resulting in some strange looking charts. Please let me know if you require more information :)

![screenshot at jun 23 16-49-46](https://cloud.githubusercontent.com/assets/7211065/16297274/c29570ea-3962-11e6-9734-fb61f3be33cb.png)
![screenshot at jun 23 16-50-01](https://cloud.githubusercontent.com/assets/7211065/16297245/9c6df70c-3962-11e6-90bd-b3cc340a270e.png)
![screenshot at jun 23 16-50-19](https://cloud.githubusercontent.com/assets/7211065/16297255/a3a92f3c-3962-11e6-9fb9-f3094ce7d96b.png)

**Comment by luqmansyauqi** [comment]
same issue here, it was fine in 0.17 version (chart sorted by type of data especially for integer and time), but in 0.18 the chart is sorted by string (even if it's integer).

**Comment by thekantian** [comment]
We're also seeing column ordering change from 0.17.1 to 0.18.0 - now it seems that columns are returned in ABC order instead of as specified by the query. Going to attempt a downgrade until we have more of an idea of exactly what's up, but wanted to add that info here in case it helps.

**Comment by tlrobinson** [comment]
Likely due to #2733

Related to #2821

**Comment by key88sf** [comment]
This is a pretty major bug for people using metabase in a "real" company :)  Is there any way to get a point release out quickly which fixes this?

**Comment by tlrobinson** [comment]
@key88sf Yeah, sorry about this, we'll be releasing 0.18.1 in the next couple days (fix for this is in #2830), in meantime you should be able to temporarily downgrade to 0.17.1 without any issues.

**Comment by tlrobinson** [comment]
(That said, I always recommending backing up your Metabase application database before doing an upgrade/downgrade, just in case)

**Comment by tlrobinson** [comment]
@akita-ken @key88sf @luqmansyauqi We just released [0.18.1](https://github.com/metabase/metabase/releases/tag/v0.18.1) which should fix this. Thanks for reporting it.

**Comment by key88sf** [comment]
👍

**Comment by akita-ken** [comment]
@tlrobinson Thanks!

**Comment by luqmansyauqi** [comment]
@tlrobinson thanks!
