### ISSUE TITLE
BE - Add a flag to `/api/collection/tree` endpoint to remove other users' personal collections

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#28199]
BE - Add a flag to `/api/collection/tree` endpoint. It should be false by default. When set, it should remove personal collections of other users from the response

**Comment by markbastian** [comment]
What's left on the BE for this? https://github.com/metabase/metabase/pull/28204 should resolve it. We do need some FE work done to use the flag, but that should be covered in https://github.com/metabase/metabase/issues/28190.

**Comment by qnkhuat** [comment]
Resolved by https://github.com/metabase/metabase/pull/28204
