### ISSUE TITLE
Typo in the documentation 

### ISSUE THREAD

**Issue by dhilst** [metabase/metabase#28217]
**Describe the bug**
There is a typo in the documentation 

**Logs**
No logs

**To Reproduce**
1. Go to https://www.metabase.com/learn/customer-facing-analytics/embedding-charts-and-dashboards
2. Search for `reqire`

**Expected behavior**
It should be require

Great project BTW!!!

**Comment by jeff-bruemmer** [comment]
Fix should deploy soon. Thanks, @dhilst!
