### ISSUE TITLE
Row Level Security

### ISSUE THREAD

**Issue by devbhosale** [metabase/metabase#2824]
Is there any way to include Row Level Security with Metabase. That is, showing different slices of the data from a table to different users depending on some attribute values.
For example User A sees Department Sales
User B sees Department Accounting

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by salsakran** [comment]
We don't have current plans, however, we'd love to hear more about your usage scenario. Specifically, how would you want to define the slices you refer to above.

Depending on how much the community requests it, this might be something we can include in the future.

**Comment by benvogan** [comment]
We at shopkick are currently looking at open source dashboarding tools in general and at the moment looking at metabase.  One thing we would like to do is author a dashboard for our retail or brand partners that are dimensioned by partner id.  Each partner would only have access however to data with their partner id.  This would be great because we could author something once and re-use it for every partner, and reduces the likelihood of someone accidentally sharing a visualization exposing another partner's data.

**Comment by skiplyfrance** [comment]
This feature would bring Metabase to a new level. Today, it is only suitable for organization where everybody has the same access level to data. But in my daily work, this is clearly not the main problem we have to solve. What we need is a tool to share data with our customer, based on a similar template.
This is my usage scenario:
My customer own small counters
Each counter send data on daily basis in a SQL database
I have 130 customers
I want to provide the same dashboard to all off them, but for their counters only
What I need is to set a dashboard, with questions including all the data. But if I can tell Metabase : this customer should read only the counter with ID X, Y or Z (row with fiel ID containing X, Y or Z), when this user will collect to the dashboard, he will see data related to its own counters.
I'm not sure if it is clear, but this could potentially make Metabase a very powerfull tool, able to compete with other BI tools like Bime.

**Comment by mazameli** [comment]
Just as an update, our current plan is to break out permissions features into several phases. The initial phase is #3087, which includes database and table permissions per user group. Subsequent phases will likely include artifact permissions (i.e. dashboards, questions, etc.), column-level permissions (to hide specific sensitive columns from certain user groups), and potentially row-level permissions.

**Comment by arachmiel** [comment]
We have very similar requirements to those above.  We are interested in having security by user, where User A is always filtered on ID = ABC.  User B can also see ID=ABC.  User C can only see ID = BCD, etc.

This is pretty simple security in that it just ties a user to one global filter that is applied.

**Comment by salsakran** [comment]
@arachmiel are you expecting to manually create the filter "ID=ABC" for each table/user combination?

"pretty simple" doesn't really apply to row level permissions ;)

**Comment by arachmiel** [comment]
Let me clarify. I know the implementation is not simple.  Just the concept of the security I need ;)  Basically we have one database storing data on multiple companies.  Every user from any given company can see all of the data for their company.  Each company may have a few users.

One idea is to limit the tables or views that the user can see.  If we can do that, I can create views for each company.  It's not ideal, but I could then limit the users to that view which in the database is already filtered.

A second idea is to apply a global filter for each user.  When user A logs in, every query he or she runs automatically has a filter for company_id = 1234.

**Comment by marcusos** [comment]
I am using the metabase to generate internal dashboards for our team and to our B2b customers to, but for each customer we have to build a specific dashboard for them. It would be great feature to us if We could create a filter or access control based on the B2B customer ID: All customers access the same dashboard but they can only see the information/rows filtered by their respective ID. Sorry for my english =D

**Comment by mazameli** [comment]
@marcusos If the dashboard is the same for all of your B2B customers, just filtered by their respective IDs, one way you could do this is to use our new [application embedding](http://www.metabase.com/docs/latest/administration-guide/13-embedding.html) feature to embed this dashboard into a separate web app. 

The dashboard would just need to include a signed parameter, mapped to each of the dashboard's cards, which would accept a customer ID that your app would provide. The dashboard would be filtered by that ID. (Signed parameters on dashboards are not exposed to users.) 

This would mean you wouldn't give Metabase accounts to your customers, but instead they'd have to have an account with the web app in which you embed your Metabase dashboard. I know this doesn't solve the use case of giving more full Metabase access to partners/customers, but if all you're trying to do is reuse a single dashboard or report, this is a way you could do it now.

**Comment by marcusos** [comment]
@mazameli  Great solution, I only tried the shared dashboard. I will build a simple web application and try the embedding feature. Thank you, and keep the great work!

**Comment by adamjseed** [comment]
I have been working as a BI consultant for many years and this is a common requirement for internal and external reporting. Having the data filtered and potentially locked to your perspective is not only useful but necessary in a muli tenancy system. Most applications (Looker, Tablu etc) have the concept of user session variables which can be coded into a filter. eg sales_region = ${user.region}

A common downstream use of this is report bursting where you can send a single dashboard to a group of people and ticket the 'Run as Recipient' option so they get their bespoke view of data. 

Right now its the single limiting feature which is stopping me from using a really good open source application.

**Comment by JAC2703** [comment]
It's a shame this isn't available - I'd say it's a fairly basic requirement for anyone with a serious use case for Metabase. It enables repeatability when Metabase is used in a multi-client or even multi-user environment. 

I use Metabase personally for various uses, but they are generally low key monitoring type uses. Using Metabase for my clients is just a non-starter due to seemingly small missing functionality that would be 'relatively' easy to implement. This is absolutely one of them!

**Comment by mamsden** [comment]
We love Metabase, but can only use it in very limited situations because we need row level security given the environment we work within (clinical trials). Each location needs access to data only for their location.  For security, privacy (and thus regulatory) reasons, they can't have access to anything else. 

We'd definitely standardize on Metabase if there was an option for row level security. Without it, unfortunately, we have to look at other solutions.

**Comment by littlegoblin9876** [comment]
Is there anyway to get the priority of this feature bumped?

**Comment by littlegoblin9876** [comment]
Sorry to nag, but was wondering if there has been any more thought on this issue?

**Comment by bmyrtil** [comment]
Hey guys, we are really wanting to use Metabase as well but the RLS is a show stopper. I was thinking an "easy" solution would be to allow custom attributes for the user. These custom attributes could be used as query variables like

`SELECT count(*)
FROM orders
[[WHERE user_id = {{user.id}}]]`

**Comment by bengohkiat** [comment]
Hey everyone, perhaps you guys would like to try out Holistics.io row based access control. They just had a webinar few months back on this topic [https://www.holistics.io/blog/webinar-permissions/] which I think was pretty good.

**Comment by littlegoblin9876** [comment]
@lindsay-stevens thank you for your suggestion. I wonder what the ramifications would be regarding connection overhead and connection poling performance in the application? I do like the idea of managing row access at the database level but would be concerned about performance and maintenance. I would gravitate more to @bmyrtil suggestion though maybe take it a step further and cross reference to metabase security group definitions. This could be a good first step, then get more sophisticated with correlating row access to groups potentially via the use of a "semi-virtual column" added to the underlying query/table at run time.

**Comment by bmyrtil** [comment]
Yea, definitely thinking it would be a huge first step and comparatively simpler to implement. Would 100% love to contribute but -100% time to assist during this time of year.

**Comment by fetanchaud** [comment]
Hi, The last commits are about a Enterprise Version of Metabase, with sandboxed tables. Will it be the the resolution of this row level security issue ? Is it possible to have more information ?
Thank you !

**Comment by brennoflavio** [comment]
Is there any updates or way to contribute on this topic? RLS would be amazing on this amazing tool!

**Comment by denis-troyan** [comment]
This is literally the only thing that stops me from suggesting this wonderful tool to our business customers. We have a lot of Sales desks, and each desk should have access only to its own data. This could be achieved by adding some WHERE conditions to every query that a User belonging to a certain group performs.
The only obstacle I could think of was that each table should have its own set of filters. E.g. let's say there are two tables: deposits and clients, and we have a Cyprus desk who should have access only to Cyprus clients and their deposits. This means, that Client table should be filtered by Country, whereas Deposits field should be filtered by Country of the Clients who made deposits.
So, to me it seems like every Security Group should allow you to do two things: 
- configure different pre-filters for each table 
- use linked (via FK) tables' columns for filters. E.g. use Clients Country to filter Deposits which only have client_id.

**Comment by jortilles** [comment]
Well .... this is an EE Features as far as i can see in https://metabase.com/docs/latest/enterprise-guide/data-sandboxes.html

**Comment by dfx413** [comment]
For 10.000 USD per year. That's one hell of a price :-|

**Comment by initd3v** [comment]
The enterprise feature works quite a bit different: You set a individual parameter for the user and assign this parameter later to the question / query: [Showcase](https://youtu.be/BEmtJ7kk2GA?t=246). What is not shown is if it is possible to map a LDAP attribute to the generated parameter. 
Furthermore in my opinion this request also includes a approach for bypassing global parameters like the username to a question. This is slighty different to a manually configured parameter.

**Comment by archongum** [comment]
> As far as I can see the enterprise feature works as follows: You set a individual parameter as a key-value-pair for the user and pass this parameter later to the question / query

That is what I want. I would like to implement this feature if I know how to code with Clojure😂

**Comment by mazameli** [comment]
As has already been mentioned by others in this thread, this feature is available in our enterprise edition. As such, I'm going to go ahead and close this issue.

**Comment by dnk8n** [comment]
I don't think Metabase wouldn't need to re-implement RLS themselves, they would just need to allow a mechanism for each account to be defined a role by an admin.

The database connection could be configured with a role (that doesn't inherit from roles granted to it), that has no permissions to do anything other than `SET role "my-admin-predefined-role"` (potentially the local equivalent before each query) before continuing with queries.

RLS can be applied by Postgres to the role. Metabase doesn't have to do anything.

A product that does something like this is [postgREST](https://postgrest.org). They haven't duplicated postgres features in order to support complex permissions.

I am sure there is a simple solution in here somewhere.

**Comment by paoliniluis** [comment]
@dnk8n this has been a feature in the product since 2019

**Comment by aamaterasu91** [comment]
RLS only works for query builder, which is very limiting. Can anyone share if there are plans to let us query using user.email to get the current logged in user? This will be incredibly powerful to let us control who can see what.
