### ISSUE TITLE
Some improvements to the api notify endpoint.

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#28259]
**Is your feature request related to a problem? Please describe.**
Ideally, a scripts would be able know the db ID ahead of time without human intervention, or be able to determine it runtime. This is a bit problematic if I have Google SSO enabled and  to get this data I would need to get a session token form a user's username/password to auth to the API. 

**Describe the solution you'd like**

Some suggestions:

1. Allow a db name in the notify endpoint, but fail if there are two with the same name.
2. Allow a db name in the notify endpoint, but sync both if two have the same name.
3. Add an endpoint like /api/notify-all, that notifies all databases.

**Comment by paoliniluis** [comment]
@Tony-metabase if you can dissect this issue in atomic ones and close this, it would be awesome! thanks

**Comment by Tony-metabase** [comment]
Closing this in favor of:

https://github.com/metabase/metabase/issues/28373
https://github.com/metabase/metabase/issues/28374
