### ISSUE TITLE
Relative Hours

### ISSUE THREAD

**Issue by jordanbenkov** [metabase/metabase#2828]
I am wanting to run relative hour questions so I can see the status of events for the past hour as well as the past day. Can't seem to find that in the filters right now.

**Comment by flamber** [comment]
Closing this, since it's been possible to do for a very long time.
![image](https://user-images.githubusercontent.com/1447303/75097087-c407d080-55a6-11ea-97e6-89e0d5803476.png)
If I've misunderstood the issue, then please comment and I will re-open.
