### ISSUE TITLE
[metabase-lib] Port `ValidationError/`

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#28290]
This one is small.

**Comment by john-metabase** [comment]
Taking this as an intro to metabase-lib work.

**Comment by john-metabase** [comment]
🤔 after taking a look at it, it's not clear to me what should change in ValidationError. Is this possibly not a candidate for metabase-lib?

**Comment by bshepherdson** [comment]
Hm. There may actually be nothing to do. The only function is the `toString`. Also it's a subclass of `Error` so we shouldn't meddle with it.
