### ISSUE TITLE
Hour of Day is being sorted incorrectly in line charts

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2829]
If this is a bug report, please fill in the blanks:

*  I am using the Safari browser.
*  My computer's OS is OSX.
*  I'm running Metabase via Mac App
*  My database is the sample database.
*  My Metabase version is 0.18.

I think this is related to https://github.com/metabase/metabase/issues/2819 and should probably be merged. But there might be an issue with what the backend is returning in this case.

<img width="1434" alt="screen shot 2016-06-24 at 10 54 00 am" src="https://cloud.githubusercontent.com/assets/107439/16346000/e1424a26-39f9-11e6-9543-050ad4d827aa.png">

**Comment by tlrobinson** [comment]
I think this is the exact same as #2819.

**Comment by salsakran** [comment]
oops.

**Comment by mazameli** [comment]
We should just make this a new chart type: Constellation

![bigbear](https://cloud.githubusercontent.com/assets/2223916/16346643/3e6f70e0-39fd-11e6-84c5-e53813d07875.jpg)
