### ISSUE TITLE
Card resizing does not always work

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#28294]
**Describe the bug**
Resizing a dashboard can result in cards content not resized to the latest dimensions of cards

**To Reproduce**
1. Create a dashboard with line/area/bar charts
2. Try resize it fast & short

**Expected behavior**
Cards' content is resized to fit inside the cards nicely

**Actual behavior**
Sometimes the content is cut off or does not fill the card

**Screenshots**

<img width="606" alt="Screen Shot 2023-02-13 at 7 39 01 PM" src="https://user-images.githubusercontent.com/14301985/218590508-1a1a974c-d0d4-4023-8386-f22d75323659.png">

**Comment by EmmadUsmani** [comment]
Similar to https://github.com/metabase/metabase/issues/29226

**Comment by alxnddr** [comment]
@WiNloSt fit is ixed by https://github.com/metabase/metabase/pull/31963
