### ISSUE TITLE
In a dashboard, Dropdown list doesn't work through application sharing

### ISSUE THREAD

**Issue by Alexandre42Antoine** [metabase/metabase#28301]
**Describe the bug**
In a dashboard Dropdown list doesn't work through application sharing. 
But the Dropdown list works when I'm sharing through public link and public integration

**To Reproduce**
1. Create a dashboard with dropdown list
2. Then try to share through private application
3. Test the previsualisation step of the dropdown
4. the dropdown list turn in input text -> not expected

**Expected behavior**
the dropdown list turn should works and be a dropdown list

**Screenshots**
![image](https://user-images.githubusercontent.com/85684311/218763249-c9a3a925-72c6-4ee1-9978-3811ae5da55d.png)
![image](https://user-images.githubusercontent.com/85684311/218763315-9e093f6a-925b-402f-81ff-bc06f893cce7.png)

- Your browser and the version: all version of all navigator
- Your operating system: Windows 10 and 11
- Your databases: Postgresql
- Metabase version: v0.45.2
- Metabase hosting environment: scalingo
- Metabase internal database: Postgres

**Severity**
The dropdownlist doesn't work so the dashboard can be used. So for me it's significant issue because my dashboard is useless.

**Comment by paoliniluis** [comment]
@Alexandre42Antoine I'm using the demo in https://github.com/metabase/embedding-reference-apps and I'm able to see categorical fields in the embedding, can you please provide us with reproduction steps following that demo?
![image](https://user-images.githubusercontent.com/1711649/219138064-efa3d513-f547-4b1c-a966-bb4da505e063.png)

**Comment by romeovs** [comment]
I also cannot reproduce this issue on 45.2 or on 50, neither with a public or and embedded dashboard.

@Alexandre42Antoine please update the issue if you are still running into this issue, or close otherwise.
