### ISSUE TITLE
Changing column order doesn't always work 

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#28311]
Sometimes you need to drag a column more than once to have it stay where you want

1. Go to New Question -> Orders -> Visualize
2. Open Viz settings and select Add or remove columns. Click select all for People, then after the query completes click deselect All for people.
3. Return to the settings menu, and try to drag a column to a new position. It will snap back to where it was originally

**Expected behavior**
Ordering should work the first time

**Comment by nil0x42** [comment]
I have the same issue. I use metabase since 1year and never noticed this before today, so it might be a recent regression

**Comment by npfitz** [comment]
This issue was born from some updates we were doing to the Table Columns picker, and is no longer technically possible to do. I've done the closest thing that I can, which is add some columns from another table, remove those same columns, and then try re-ordering, which works fine on https://github.com/metabase/metabase/tree/13455-column-order-after-removal (set to be merged soon). But since the repro steps above are no longer possible, I'm going to close this issue off
