### ISSUE TITLE
Could not find artifact methodical:methodical:jar:0.15.1 in central 

### ISSUE THREAD

**Issue by wzhiqing** [metabase/metabase#28324]
Error building classpath. Could not find artifact methodical:methodical:jar:0.15.1 in central (http://insecure.repo1.maven.org/maven2/)
Does anyone else have this problem?

**Comment by wzhiqing** [comment]
(https://user-images.githubusercontent.com/10972543/219014890-9316fbe3-9e03-40a0-9391-f8bbb40c4930.jpg)

**Comment by paoliniluis** [comment]
this is a network error, please post the issues in Discourse forum
