### ISSUE TITLE
Dashboards in 0.18.0.2 are non-responsive in the OS X app.

### ISSUE THREAD

**Issue by ablerman** [metabase/metabase#2833]
*  I am using the os x app.
*  My computer's OS is Yosemite.
*  I'm running Metabase locally with the Mac App. 
*  My database is built into the mac app?
*  My Metabase version is 0.18.02.

When I go to any dashboard. (Existing or create a new one.) There is a single button at the top that says "Done". Nothing happens when I click it. I'm not sure if I don't know how to use the new dashboard features or if they're non-functional.

**Comment by camsaul** [comment]
@ablerman do you see the same thing if you open the page in Safari? You can get a link to the current page in the Mac App by clicking the link button in the upper-right corner of the window, and then paste it into the address bar in Safari.

**Comment by ablerman** [comment]
@camsaul It seems to have gone away in the app. Could it have been a css caching issue?

**Comment by camsaul** [comment]
hard to say, it could be one of those random errors that can only be attributed to the phase of the moon. Glad it's working now 😅

**Comment by camsaul** [comment]
Closing since @ablerman isn't seeing this issue any more
