### ISSUE TITLE
We should pretty-print Mongo & Druid JSON queries when converting MBQL -> native 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2834]
When I convert to a native query I see

![screen shot 2016-06-24 at 1 00 40 pm](https://cloud.githubusercontent.com/assets/1455846/16349116/b10fb0e8-3a0b-11e6-9dc6-481d50297bbb.png)

I would prefer to see something more like

![screen shot 2016-06-24 at 1 01 17 pm](https://cloud.githubusercontent.com/assets/1455846/16349131/c669b498-3a0b-11e6-9d3f-174f94cdf48c.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by denisesenguel** [comment]
YES PLEASE!

**Comment by flamber** [comment]
Related to #9142
