### ISSUE TITLE
Auto join doesn't work sometimes

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#28349]
**Describe the bug**
I have two tables -- let's say A and B. A has a foreign key that maps to B. When I start a question with A and try to join to B, it will automatically populate the join keys -- which is nice. But if I start the question with B and try to join to A, it doesn't populate the join keys automatically and I have to select them manually. Since B doesn't have foreign keys defined to A, then it should use the same ones from A to B. 

**Logs**
n/a

**To Reproduce**
1. Create two tables with one that has a foreign key that maps to the other table -- defined in data model. 
2. Start question by joining first and second table, join keys are populated automatically. 
3. Restart question with second table and try to join with first table, join keys are NOT populated automatically. 

**Expected behavior**
Join keys should automatically populate when defined on either table as foreign key. 

**Screenshots**
n/a

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: OS X
- Your databases: Postgres
- Metabase version:  master
- Metabase hosting environment: Metabase Cloud Dev
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by paoliniluis** [comment]
I think the issue is https://github.com/metabase/metabase/issues/1177
