### ISSUE TITLE
forbidden 403 before even getting to the login page

### ISSUE THREAD

**Issue by NickeZ** [metabase/metabase#28359]
**Describe the bug**
When accessing our instance, we are presented with "whitelabel error page" and a "403 forbidden" error 90% of the time. Sometimes we get the normal login window and can login. Any users that are logged in can use metabase without problem.

**Logs**
This is what is looks like in the logs when the users try to open metabase. (Before even attempting to authenticate)

[9d3432dc-3e83-4cae-b82c-b1b6500a30ff] 2023-02-16T11:27:47+01:00 DEBUG metabase.server.middleware.log GET /api/user/current 401 208.2 µs (0 DB calls) 
"Unauthenticated"

**To Reproduce**
1. Go to metabase

**Screenshots**

![Skärmavbild 2023-02-16 kl  10 47 23](https://user-images.githubusercontent.com/492753/219343372-f061b1a9-297c-4a4f-beef-aa27073b5251.png)

**Information about your Metabase Installation:**

```
You can get this information by going to Admin -> Troubleshooting.
[9d3432dc-3e83-4cae-b82c-b1b6500a30ff] 2023-02-16T11:11:53+01:00 INFO metabase.core Starting Metabase version v0.45.2.1 (1a59de7 release-x.45.2.x) ...
[9d3432dc-3e83-4cae-b82c-b1b6500a30ff] 2023-02-16T11:11:53+01:00 INFO metabase.core System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.18+10",
 "java.vendor" "Eclipse Adoptium",
 "java.vendor.url" "https://adoptium.net/",
 "java.version" "11.0.18",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.18+10",
 "os.name" "Linux",
 "os.version" "4.14.301-224.520.amzn2.x86_64",
 "user.language" "en",
 "user.timezone" "GMT"}
```

**Severity**
Critical, we cannot use metabase.

**Additional context**

**Comment by paoliniluis** [comment]
This is a post for Discourse rather than github. Your problem seems to indicate you have a reverse proxy in the middle doing nasty things, remove that reverse proxy and start over

**Comment by NickeZ** [comment]
We do have a load balancer (AWS ALB) in between, but that doesn't cause any issues for any of our other services. What "nasty things" do you suggest that the reverse proxy does?
