### ISSUE TITLE
Add and Delete buttons not working

### ISSUE THREAD

**Issue by genepool99** [metabase/metabase#2836]
Since the upgrade to 0.18 the add and delete buttons no longer work when editing a dashboard. When I hover over them and the pointer changes to the finger but clicking changes it back to the drag cursor. There are no messages in the Chrome developers console. 

![image](https://cloud.githubusercontent.com/assets/3596229/16350782/d0dcfdcc-3a15-11e6-949e-339e3deaa51a.png)

*  I am using the Chrome browser.
*  My computer's OS is Windows 7.
*  I'm running Metabase remotely from the JAR on Ubuntu 16.04
*  My database is MySQL.
*  My Metabase version is 0.18.

**Comment by salsakran** [comment]
Can you check any other browsers on your computer? I.e. is it a problem just in chrome on windows 7 or does it affect all browsers?

**Comment by camsaul** [comment]
@genepool99 were you able to check any other browsers?

**Comment by camsaul** [comment]
@genepool99 ?

**Comment by camsaul** [comment]
I'm unable to reproduce this on Chrome on 0.18.1

**Comment by tlrobinson** [comment]
@genepool99 We can't seem to reproduce this. Perhaps you were accidentally dragging slightly while clicking? If you start dragging the card we ignore click events. We may want to put a threshold of more than 1px in.

**Comment by genepool99** [comment]
Problem seems fixed in the current version

**Comment by salsakran** [comment]
glad to hear it.
