### ISSUE TITLE
Duplicate columns

### ISSUE THREAD

**Issue by websirnik** [metabase/metabase#2837]
I've just installed a fresh metabase and connected my MongoDb. Seeing duplicate columns to choose from. This is true not only ID, for some other fields as well(not all though).
![screen shot 2016-06-27 at 17 27 36](https://cloud.githubusercontent.com/assets/282871/16387425/a7ecafba-3c8c-11e6-91f5-1e1baedc74c4.png)
Let me know how can I debug it futher.
-  I am using the Chrome browser.
-  My computer's OS is Mac.
-  I'm running Metabase locally with the Mac App
-  My database is MongoDb 2.6.
-  My Metabase version is 0.18.0.

**Comment by camsaul** [comment]
@websirnik is 0.18 the first version of metabase you used? Or have you used a previous version on the same computer? This is a bug we saw before (#1366 & #1633) but it was fixed a few months ago.

**Comment by websirnik** [comment]
@camsaul yes, this is the first version that I've used. I've noticed that Metabase list Mongo 3.0+ as a supported DB. Mine is 2.6. I'll be upgrading in next few weeks, and let you know if the issue persists.

**Comment by camsaul** [comment]
@websirnik are you still seeing this issue?

**Comment by camsaul** [comment]
In hindsight I think this issue wouldn't have been possible if we #669

**Comment by websirnik** [comment]
Haven't got a chance to update the MongoDb deployment yet and re-test. Will ping you once done.

**Comment by camsaul** [comment]
@websirnik did you get a chance to try this again?

**Comment by websirnik** [comment]
@camsaul I've just upgraded MongoDb to 3.2.10 and Metabase to 0.20.3. Still experiencing the very same issue. Is there any way I can debug it for you?

**Comment by websirnik** [comment]
Hm, not every collection has duplications, only the largest ones.

**Comment by websirnik** [comment]
Can this be related that I have embedded documents that have similar fields with the core document?
```
{
    "_id" : ObjectId("58136cd6a7e80e13218b4723"), 
    "width" : NumberLong(1000), 
    "height" : NumberLong(1000),
    "url" : "image.png", 
    "thumbnail" : {
        "_id" : ObjectId("58136cd6a7e80e13218b4724"), 
        "url" : "image-thumb.png", 
        "width" : NumberLong(180), 
        "height" : NumberLong(180)
    }
}
```
My assumption is that would result in `id`,`width`, `height`, `url` columns being duplicated. What do you think?

**Comment by camsaul** [comment]
@websirnik is that what happened? (Are those the ones that were duplicated?)

**Comment by websirnik** [comment]
That's the only explanation I have at the moment. I have multiple different columns duplicated, not only `id`.

**Comment by camsaul** [comment]
I figured out that what's going on here is that was just showing the final part of all of the nested columns. E.g. both `id` and `thumbnail.id` will show up in the columns drop-down menu as `id`. We had issue #3173 open to address that, and it was fixed by PR #3738 which we shipped as part of version 0.21.0.

@websirnik upgrading to the latest version of Metabase should fix your issue. Feel free to reöpen this if you're still having problems after upgrading.

**Comment by davidmir** [comment]
Hi,

I'm experiencing this problem. I am using the version of metabase found in docker.

![screen shot 2017-01-10 at 17 47 20](https://cloud.githubusercontent.com/assets/4657051/21817786/562fb02a-d75d-11e6-915e-ef9021b9e10d.png)

**Comment by camsaul** [comment]
@davidmir what kind of Database are you using?

**Comment by davidmir** [comment]
@camsaul MongoDB 3.2.0

**Comment by camsaul** [comment]
Are those any of those columns inside of objects (i.e., are they *not* top-level columns?)

What version of Metabase are you using? (You can check in "About Metabase" the menu in top-right corner)

**Comment by davidmir** [comment]
Metabase version is v0.21.1. All the documents are at top-level columns.

**Comment by websirnik** [comment]
Upgrade to v0.21.1 solved my issue. @camsaul thanks!

**Comment by davidmir** [comment]
I still can not solve this problem. My version of the metabase is v0.21.1 and the problem persists.

Any tips?

**Comment by davidmir** [comment]
Upgrade to v0.22.2 solved my issue.
