### ISSUE TITLE
Add Metabase version to card definition

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28387]
**Is your feature request related to a problem? Please describe.**
If we could know which version the card was created, we might better luck to reproduce some issues that we see, as the properties in dataset_query, visualization_settings and result_metadata change over time.

**Describe the solution you'd like**
Add the version the card was created and last edited in the dataset_query, visualization_settings and result_metadata fields, so we can have more knowledge about those definitions for reproductions.

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Important to reproduce stuff

**Additional context**
NA

**Comment by likeshumidity** [comment]
Would be super helpful for Success to troubleshoot questions where Metabase is having trouble interpreting their visualization settings or MBQL.
