### ISSUE TITLE
Sync column index, partition, clustering information

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#28382]
Update Nov/23

We should sync index, partition, distribution, clustering etc information. Each database has slighly different approaches.

For [databases in tier 1 and 2](https://www.notion.so/metabase/Database-Tiers-for-Feature-Development-fabba4d2bbfb4c729029f5e77d585f61), sync index information:

It is worth having the information in two places:
- In `metabase_field`. Know if a field is indexed.
- In `metabase_table`. Know what indexes are available for a given table.

### Transactional DBs (Postgres, MySQL, MariaDB, H2)
- [ ] Get it from the [JDBC method](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getIndexInfo-java.lang.String-java.lang.String-java.lang.String-boolean-boolean-).

### BigQuery
BigQuery has two types of optmized columns: partition (only one column) and clustering (multiple columns).
- [ ] Get partition keys and clustering keys from the [information_schema.columns](https://cloud.google.com/bigquery/docs/information-schema-columns).
- [ ] Get if a filter is required on the partition from the [information_schema.table_options](https://cloud.google.com/bigquery/docs/information-schema-table-options). This should be saved at the table level.

### Redshift
Stores Sort keys
- [ ] Get sort keys from [svv_table_info](https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_TABLE_INFO.html)

### Snowflake
Store Clustering keys
- [ ] Get clustering keys [docs](https://docs.snowflake.com/en/user-guide/tables-clustering-keys)

### Mongo
Store single-column indexes
- [ ] Get indexes from [getIndexes()](https://www.mongodb.com/docs/manual/tutorial/manage-indexes/#view-existing-indexes)

---

JDBC has a method for getting index info

https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getIndexInfo-java.lang.String-java.lang.String-java.lang.String-boolean-boolean-

We should sync this and possibly do cool or useful stuff with it in the future. 

- Try to hit indexes more often when generating queries
- All things being equal, a column with an index is probably more important than a similar column without an index

**Comment by camsaul** [comment]
We should try this out and look at the shape to see what we might be able to do with it

**Comment by camsaul** [comment]
This information could be useful for X-Rays, we could do something useful with it

**Comment by dpsutton** [comment]
```clojure
  (let [spec (metabase.driver.sql-jdbc.connection/db->pooled-connection-spec 4)]
    (with-open [conn (clojure.java.jdbc/get-connection spec)]
      (with-open [index-info (.getIndexInfo (.getMetaData conn)
                                            nil            ;; category
                                            "public"       ;; schema
                                            "task_history" ;; table
                                            false          ;; when true, return only indices for unique values when
                                                           ;; false, return indices regardless of whether unique or
                                                           ;; not
                                            true ;; when true, result is allowed to reflect approximate or out of data
                                                 ;; values; when false, results are requested to be accurate
                                            )]
        (into [] (clojure.java.jdbc/result-set-seq index-info)))))

[{:index_name "task_history_pkey",
  :type 3,
  :filter_condition nil,
  :pages 4,
  :asc_or_desc "A",
  :table_schem "public",
  :index_qualifier nil,
  :non_unique false,
  :column_name "id",
  :cardinality 549.0,
  :table_name "task_history",
  :table_cat nil,
  :ordinal_position 1}
 {:index_name "idx_task_history_db_id",
  :type 3,
  :filter_condition nil,
  :pages 2,
  :asc_or_desc "A",
  :table_schem "public",
  :index_qualifier nil,
  :non_unique true,
  :column_name "db_id",
  :cardinality 549.0,
  :table_name "task_history",
  :table_cat nil,
  :ordinal_position 1}
 {:index_name "idx_task_history_end_time",
  :type 3,
  :filter_condition nil,
  :pages 4,
  :asc_or_desc "A",
  :table_schem "public",
  :index_qualifier nil,
  :non_unique true,
  :column_name "ended_at",
  :cardinality 549.0,
  :table_name "task_history",
  :table_cat nil,
  :ordinal_position 1}]
```

From this we can see we have an index on "ended_at". I think we'd still have to use the inferred semantic types or base_types (creation_date style, or just the timestampiness of it) to know we should use that column as a sort when snapshotting tables

**Comment by paoliniluis** [comment]
can't we flag the indexes in the frontend? @luizarakaki, I would make indexes more relevant in the entire frontend to help analysts pick these fields over others when doing SQL or GUI questions. I would also all these to the models and the data catalog so we can do some nudges on users

**Comment by paoliniluis** [comment]
I'm wondering if we could identify in the same way partition keys/sort keys in Redshift/bigquery sort of engines

**Comment by luizarakaki** [comment]
Yeah, there are ways of identifying partition keys in some DWs.

This would complement this project [Make better use of partition keys](https://www.notion.so/metabase/Make-better-use-of-partition-keys-indexes-clustering-keys-735a6829e6c44ec3bb45e208f18b255d).

**Comment by camsaul** [comment]
Dan typed up a proposal in https://www.notion.so/metabase/Sync-db-indexes-ae13269005934e99837c77fe355ec9ab

**Comment by qnkhuat** [comment]
@camsaul I have 2 questions:
- what about composite indexes?
- regarding storing indexing information in `metabase_table`, what exactly do you want to store here? the list of all field ids that has an index?

**Comment by qnkhuat** [comment]
Epic for indexing https://github.com/metabase/metabase/issues/36452

**Comment by camsaul** [comment]
We started syncing index information in 49 (see #36452), I don't know if partition and cluster information is actually useful, so closing as not planned
