### ISSUE TITLE
Safari Browser doesn't allow input of decimal numbers in multiply by a number formatting field

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#28402]
**Describe the bug**
Safari Browser doesn't allow input of decimal numbers in multiply by a number formatting 

**To Reproduce**
Make sure you are on Safari Browser:

1. Go to New -> Question -> Orders -> Visualize
2. Click on Total Column -> Column Formatting

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/110378427/219633479-cafc557f-cfe9-40cc-bda6-e9a4aedc1b7e.png">

3. Try to add a decimal value to the `Multiply by a number` field:

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/110378427/219633787-8cc2b2f3-a01a-44e5-9504-ef15214cad1a.png">

**Expected behavior**
I am able to insert decimal values like `0.10`

**Information about your Metabase Installation:**

Able to replicate on both 1.45.2.1 and `master`

**Comment by paoliniluis** [comment]
@Tony-metabase this does work on Chrome right?

**Comment by Tony-metabase** [comment]
Yes correct!
