### ISSUE TITLE
Stop telling H2 to use legacy storage engine

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2840]
H2 introduced its new better/faster/stronger ["MVStore"](http://h2database.com/html/mvstore.html) file format a few years ago and made it the default storage engine in a release that came out a month or so after we started work on secret project "Clojurey Corv".

The new file format changed the extension of the DB file, which someone didn't like (if I remember correctly) because they had to add a new entry in `.gitignore`; they added `;MV_STORE=FALSE` to the H2 connection string to force use of the legacy storage engine.

Anyways, we can take `;MV_STORE=FALSE` out of the connection string; H2 will continue to use the legacy format for DBs that already exist, and use the new-and-improved MVStore for new databases.

**Comment by salsakran** [comment]
is there a way to migrate from the old version to the new version?

**Comment by camsaul** [comment]
Not that I know of. But at least new instances would benefit from it even if older instances still use the older "PageStore" engine.

Either way you give H2 a filename like `/path/to/metabase.db`; for PageStore the actual file it creates is called `metabase.db.h2.db`, and for MVStore `metabase.db.mv.db`. So things like the H2 console command will still work for both formats.

**Comment by JiriKacirek** [comment]
I completely don't like it because that MV_STORE=TRUE doesn't support isolation of READ UNCOMMITED which is mentioned in the H2 documentation as supported. Use MV_STORE=FALSE was the only hope to upgrade the databse together with don't need for the complete refactoring of my legacy test suite!

**Comment by camsaul** [comment]
> Use MV_STORE=FALSE was the only hope to upgrade the databse together with don't need for the complete refactoring of my legacy test suite!

@JiriKacirek Huh? We merged this almost 3 years ago. You have your own test suite for Metabase?
