### ISSUE TITLE
Can't create a dashboard subscription to a dashboard with link cards or actions

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#28426]
Create a dashboard with either an action or a link card (or both). Add a dashboard subscription and save.

The save will fail. It's hard to tell because the UI doesn't really show any response.

```
2023-02-17 23:26:04,387 DEBUG middleware.log :: POST /api/pulse 400 18.6 ms (0 DB calls)
{:errors
 {:cards
  "value must be an array. Each value must satisfy one of the following requirements: 1) value must be a map with the following keys `(collection_id, description, display, id, include_csv, include_xls, name, dashboard_id, parameter_mappings)` 2) value must be a map with the keys `id`, `include_csv`, `include_xls`, and `dashboard_card_id`. The array cannot be empty."}}
```

The FE is sending the action or the link card and the BE validation fails the transaction.

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/6377293/219818680-8d49ab74-0b1c-432c-8970-227885aff574.png">

This is related to, but not identical to https://github.com/metabase/metabase/issues/28424 . It's possible the same fix fixes both. But it's also possible the other is fixed and this pathway is forgotten about.
The reason it is similar is because we need to figure out what to do with these new cards. At the moment we don't render them in static viz, so we just need to know who is actually supposed to filter them out.
- should they never end up in pulse cards? If so, if we ever want to render them we'd have to make sure they get added into pulse cards in the right order
- should they end up in pulse cards but be skipped by some spot in the pulse render?

And this impacts this particular bug. If they should never be pulse cards, this is a FE bug and it should not send these cards over, or we could fix on the BE by accepting these inputs but ignoring them. If we accept them, the (bizarre) `CoercibleToCardRef` spec needs to allow them and we need to filter appropriately in the right spot (possibly `metabase.pulse/execute-dashboard`)

**Comment by qnkhuat** [comment]
As explained here: https://github.com/metabase/metabase/issues/28424#issuecomment-1437993958, the fix should be FE filter out `actions, linkcards` from the `cards` parameters.
