### ISSUE TITLE
Non-admin users can't run actions

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#28425]
**Describe the bug**
Non-admin users with full permissions can't run actions

**To Reproduce**
1. Run an instance with a DB with actions
2. Create a dashboard with any valid action
3. Log in as a non-admin user with full permissions
4. Open the dashboard and try to run any action
5. Backend replies with 403 "You don't have permissions to do that."

**Expected behavior**
Non-admin users should be able to run actions

**Information about your Metabase Installation:**

`master` branch

**Comment by tsmacdonald** [comment]
@kulyk is still seeing this
