### ISSUE TITLE
Make NodeJS LTS (v18) officially supported version for Metabase

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#28433]
NodeJS 16 EOL is due soon-ish (September 11th, 2023).
https://nodejs.org/en/blog/announcements/nodejs16-eol/

We need to:
1. make sure all parts of the system work without any problems with the LTS (`Hydrogen`) NodeJS version and then
2. set it as the official minimum supported version in Metabase
    - update the `engines` section in our `package.json` to reflect this

@metabase/frontend-developers we have the opportunity to do this at the beginning of the 46 cycle. If we encounter problems, we can postpone it for the 47 cycle, but no longer than that.

Tangentially related:
NodeJS 18 in combination with outdated `babel-loader` was breaking the static-viz bundle. See: https://github.com/metabase/metabase/pull/28430

**Comment by WiNloSt** [comment]
Semi-related. Just want to keep this tracked too. In https://github.com/metabase/metabase/pull/27970, we upgraded our GitHub actions node runner from Node v14.x to v16.10.0.

Ideally, we should have our CI and our development environment using the same Node version, but as of #27970, we still need to stick to Node v16.10.0 on CI until there's a fix for that.
