### ISSUE TITLE
Padding on Refresh button + Object detail is off

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2844]
The bottom+top padding on the refresh button is a bit off.
Using Chrome on MB v0.18.1

See below 

![screen shot 2016-06-27 at 4 35 21 pm](https://cloud.githubusercontent.com/assets/107439/16399157/dd222726-3c84-11e6-900b-ebf58ec9fb02.png)

**Comment by mazameli** [comment]
This appears to be fixed on master (viewing raw data):
![screen shot 2016-08-11 at 3 17 08 pm](https://cloud.githubusercontent.com/assets/2223916/17606873/bb03bfc2-5fd6-11e6-9215-35f1b5272a9d.png)

Motion to close?

**Comment by salsakran** [comment]
still off for me. click into an id for the object detail, not the raw data view.

**Comment by mazameli** [comment]
Yep, I'm an idiot and didn't read the full title of this issue.
