### ISSUE TITLE
Cannot find an archived collection in the archives

### ISSUE THREAD

**Issue by capmann** [metabase/metabase#28444]
I archived one question inside a a collection, and it seems like this archived the whole collection (because it disappeared from its place), but I cannot find the collection in the archives. 

Could you please help? A whole collection with dashboards and questions disappears, and that is going to be very painful for my team.

Thanks a lot!

**Comment by paoliniluis** [comment]
It’s a duplicate of https://github.com/metabase/metabase/issues/21341. Please post your question in the forum
