### ISSUE TITLE
Timeouts not being displayed in dashboard errors

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2845]
Gateway timeouts errors aren't being shown in dashboard cards

If this is a bug report, please fill in the blanks:

*  I am using the _Chrome_ browser.
*  My computer's OS is _Mac OS X_.
*  I'm running Metabase _on elastic beanstalk_. 
*  My database is _PostgeSQL_.
*  My Metabase version is _0.18.1_.

![screen shot 2016-06-27 at 5 40 14 pm](https://cloud.githubusercontent.com/assets/107439/16400192/0eb8f0e0-3c8e-11e6-9c2f-dd5f4f9757d4.png)

**Comment by lewisl9029** [comment]
Looks like this issue might be a symptom of a larger problem. There seems to be just a general lack of error handling for async functions in large parts of the codebase. There isn't a single try-catch block in https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/dashboard.js for instance, even though it has over a dozen await statements. 

Is error handling being done somewhere else downstream? Or maybe there is something else that I'm missing? If not, we might want to open another issue to keep note of this as technical debt to be addressed eventually.
