### ISSUE TITLE
Nested questions get confused around custom columns that are just columns

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#28451]
Gist: make a card that selects a custom column which is just another column. Save the question. Make a question based on this question. Error.

Fleshed out:
New mbql question: Sample Dataset > Orders. Select just Total. Add a custom column who's definition is just `[Tax]` and a limit of 2. (selecting few columns and limit of 2 is not required, just makes viewing metadata waaay easier)
```clojure
{:source-table 2,
 :fields [[:field 40 nil] [:expression "custom"]],
 :expressions {"custom" [:field 37 nil]},
 :limit 2}
```
Make a new question based on this saved question.
<img width="933" alt="image" src="https://user-images.githubusercontent.com/6377293/220141629-46f8059e-238a-4454-884c-7bdce70c3fe9.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/6377293/220141678-414f2c9d-d700-4996-b952-66d3897c330c.png">

> Column "source.TAX" not found; SQL statement:

generated sql:

```sql
SELECT "source"."TOTAL" AS "TOTAL",
       "source"."TAX" AS "TAX" -- selecting TAX not custom
FROM (SELECT "source"."TOTAL" AS "TOTAL",
             "source"."custom" AS "custom" -- no TAX here
      FROM (SELECT "PUBLIC"."ORDERS"."ID" AS "ID",
                   "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID",
                   "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID",
                   "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL",
                   "PUBLIC"."ORDERS"."TAX" AS "TAX",
                   "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL",
                   "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT",
                   "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT",
                   "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY",
                   "PUBLIC"."ORDERS"."TAX" AS "custom"
            FROM "PUBLIC"."ORDERS")
      "source" LIMIT 2)
"source" LIMIT 1048575
```

I think the issue is that the custom-column has an id on it and the query processor ignores the analysis in favor of "oh, an id. i know this field. it is TAX".

```clojure
  (db/select-one-field :result_metadata 'Card :id 4)
  ({:name "TOTAL",
    :settings nil,
    :field_ref [:field 40 nil],
    :effective_type :type/Float,
    :id 40,
    :display_name "Total",
    :base_type :type/Float}
   {:name "custom",
    :settings nil,
    :field_ref [:expression "custom"],
    :effective_type :type/Float,
    :id 37,  ;; reaches out to "TAX" instead of "custom"
    :display_name "custom",
    :base_type :type/Float})
```

**Comment by tsmacdonald** [comment]
@dpsutton should we close #28193 in favor of this issue? I don't see a reason to keep them distinct

**Comment by dpsutton** [comment]
Yeah I kinda wondered about that. Maybe closing that one and copying over their observed strange behavior to make sure it is fixed. But there was lots of noise so I opened this one with a minimal reproduction here.

**Comment by tsmacdonald** [comment]
Another reproduction to test for, courtesy of @nemanjaglumac :


Alternative repro steps:
1. New question > Sample Database > Orders
2. Add custom column
![image](https://user-images.githubusercontent.com/31325167/219044535-808ba59d-b949-4b11-ae65-41a1af13f46d.png)
3. Save question
4. Turn it into a model (originally CC is still there)
![image](https://user-images.githubusercontent.com/31325167/219044720-8b89bf80-cf65-4a3a-88ce-cdfd74049575.png)
5. Refresh and see the custom column dropped
![image](https://user-images.githubusercontent.com/31325167/219044811-cfa67330-11f0-47f5-a5fe-43358894ee61.png)

**Comment by tsmacdonald** [comment]
(Copied the labels from the old issue over, including the `P1` classification from Nemanja)
