### ISSUE TITLE
FE - Add ability to launch Model X-Rays from "Our Analytics" -> "Our Data"

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#28469]
Shown below is the x-ray hover ability for databases in the "Our Tables" view.
![Image](https://user-images.githubusercontent.com/8381441/220170447-1b093235-89ff-4135-83d8-d23c1cd27442.png)

We want to add a button to x-ray models from the collection detail page.
![Image](https://user-images.githubusercontent.com/8381441/220170361-b95e4875-6eea-4ec8-a33c-e98f249df277.png)

The endpoint to make this happen is `/auto/dashboard/question/:id`, where `:id` is the id of the model. For reference, the corresponding table behavior uses the endpoint `/auto/dashboard/table/:id`. I would expect the hover to show "X-ray this model."

**Comment by markbastian** [comment]
Shown below is the x-ray hover ability for databases in the "Our Tables" view.
![Image](https://user-images.githubusercontent.com/8381441/220170447-1b093235-89ff-4135-83d8-d23c1cd27442.png)

We want to reproduce this behavior for models displayed on the "Our Analytics" view, as shown here:
![Image](https://user-images.githubusercontent.com/8381441/220170361-b95e4875-6eea-4ec8-a33c-e98f249df277.png)

The endpoint to make this happen is `/auto/dashboard/question/:id`, where `:id` is the id of the model. For reference, the corresponding table behavior uses the endpoint `/auto/dashboard/table/:id`. I would expect the hover to show "X-ray this model."

**Comment by ranquild** [comment]
Closed as it was never a planned change.
