### ISSUE TITLE
BE - Determine and implement correct behavior with broken "count" aggregates in x-ray

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#28471]
Note that count is a dimensionless measure and so this aggregate doesn't really make sense in the first place.

**Comment by markbastian** [comment]
In some circumstances, x-rays generated cards that show the error "There was a problem displaying this chart."

To reproduce (Probably could be simplified):
1. Create individual models on orders, people, and products
2. Union the above via their FKs in a new model
3. Show the x-ray by plugging in the model to this url: http://localhost:3000/auto/dashboard/question/180#show=all (Note that 180 is my model ID, yours will almost certainly be a different value)

You should see something like the attached.

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/8381441/220200348-3c844f6a-198c-413b-b799-64c7bb986414.png">

Further info:

The dataset call can be sniffed out from the network panel of your browser, but it ends up calling something like this under the covers:

```clojure
(qp/process-query
 {:type       "query",
  :database   2,
  :query      {:source-table "card__177",
               :breakout     [["field" 74 {:binning {:strategy "default"}}]],
               :aggregation  [["count"]]},
  :parameters []})
```

This eventually bottoms out as:

```clojure
(let [field-id          74
      fingerprint nil
      field-id->filters {}]
  (#'metabase.query-processor.middleware.binning/extract-bounds
   field-id
   fingerprint
   field-id->filters))
```

In either case, we get the error "Unable to bin Field without a min/max value." There is no fingerprint data for these fields.

**Comment by qnkhuat** [comment]
I can't reproduce this.

This is my Order models, which is unioned of 3 other models:
![Screenshot 2023-02-27 at 17 48 05](https://user-images.githubusercontent.com/25661381/221543950-0d33f86a-7e01-4fb5-8c42-cd3d9c8426a2.png)

Here is what I got when I X-ray it
![Screenshot 2023-02-27 at 17 48 42](https://user-images.githubusercontent.com/25661381/221544084-055839fe-f957-429a-b8c3-6d418cdb2331.png)

**Comment by markbastian** [comment]
I think this was a consequence of behavior prior to the current solution to model x-rays and is now fixed. @cdeweyx -- I think we can just close it. Ok with that?

**Comment by markbastian** [comment]
This is not likely an issue and we should close unless we see it again.
