### ISSUE TITLE
FE - Add ability to launch Question X-Rays from the "Our Analytics" table

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#28472]
Relates closely to #28469

Shown below is the x-ray hover ability for databases in the "Our Tables" view.
![Image](https://user-images.githubusercontent.com/8381441/220170447-1b093235-89ff-4135-83d8-d23c1cd27442.png)

We want to reproduce this behavior for questions displayed on the collection detail tabular view, as shown here:
![Image](https://user-images.githubusercontent.com/8381441/220171458-32ff88b7-6389-4adc-9eaa-ff9a2a5e3ee5.png)

A context menu item on the ... menu could show "X-ray this question". The endpoint to make this happen is `/auto/dashboard/question/:id`, where `:id` is the id of the model. For reference, the corresponding table behavior uses the endpoint `/auto/dashboard/table/:id`.

**Comment by markbastian** [comment]
Relates closely to #28469

Shown below is the x-ray hover ability for databases in the "Our Tables" view.
![Image](https://user-images.githubusercontent.com/8381441/220170447-1b093235-89ff-4135-83d8-d23c1cd27442.png)

We want to reproduce this behavior for questions displayed on the "Our Analytics" tabular view, as shown here:
![Image](https://user-images.githubusercontent.com/8381441/220171458-32ff88b7-6389-4adc-9eaa-ff9a2a5e3ee5.png)

A context menu item on the ... menu could show "X-ray this question". The endpoint to make this happen is `/auto/dashboard/question/:id`, where `:id` is the id of the model. For reference, the corresponding table behavior uses the endpoint `/auto/dashboard/table/:id`.

**Comment by ranquild** [comment]
Closed as it was never a planned change.
