### ISSUE TITLE
HTTP response code with wrong embed token

### ISSUE THREAD

**Issue by dricoco** [metabase/metabase#28485]
**Describe the bug**
If you use a wrong token when you try to embed metabase in an iframe you will get the message 'Message seems corrupt or manipulated.' which is ok but the http response code is 200. I think it should be 400 bad request

**Logs**
No logs necessary just use firefox or chrome console

**To Reproduce**
Use a working embed url for metabase, change one character in the url token.
you will get the 'Message seems corrupt or manipulated.'
check the http response code

**Expected behavior**
You should get a 400 bad request 

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/6524436/220379382-d5353069-d1cb-4191-b8b3-77cf8f4c561f.png)

**Information about your Metabase Installation:**

chrome Version 110.0.5481.96 (Build officiel) (64 bits)
Windows 10

**Severity**
I need to purge some varnish cache based on the response code of an outdated token.

**Comment by dricoco** [comment]
Just to add to this message the json from metabase 

` {   "browser-info": {     "language": "en-US",     "platform": "MacIntel",     "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0",     "vendor": ""   },   "system-info": {     "file.encoding": "UTF-8",     "java.runtime.name": "OpenJDK Runtime Environment",     "java.runtime.version": "11.0.15+10-post-Debian-1deb11u1",     "java.vendor": "Debian",     "java.vendor.url": "https://tracker.debian.org/openjdk-11",     "java.version": "11.0.15",     "java.vm.name": "OpenJDK 64-Bit Server VM",     "java.vm.version": "11.0.15+10-post-Debian-1deb11u1",     "os.name": "Linux",     "os.version": "5.10.0-14-amd64",     "user.language": "en",     "user.timezone": "Europe/Paris"   },   "metabase-info": {     "databases": [       "mysql"     ],     "hosting-env": "unknown",     "application-database": "mysql",     "application-database-details": {       "database": {         "name": "MariaDB",         "version": "10.5.15-MariaDB-0+deb11u1"       },       "jdbc-driver": {         "name": "MariaDB Connector/J",         "version": "2.7.6"       }     },     "run-mode": "prod",     "version": {       "date": "2023-01-27",       "tag": "v1.45.2.1",       "branch": "release-x.45.2.x",       "hash": "1a59de7"     },     "settings": {       "report-timezone": "Europe/Paris"     }   } }`

**Comment by paoliniluis** [comment]
Just tested this and I get an error 400:
![image](https://user-images.githubusercontent.com/1711649/220930639-ba4eb5e7-7bb7-4f77-931d-f03652678c8a.png)

This seems to be your reverse proxy rewriting the response code
