### ISSUE TITLE
Dashboard Filters Category Lookup

### ISSUE THREAD

**Issue by vkovalskiy** [metabase/metabase#2848]
-  I am using the Chrome browser.
-  My computer's OS is OS X.
-  I'm running Metabase on AWS
-  My database is Postgres.
-  My Metabase version is 0.18.

In your blog post about filters there is a lookup / dropdown in the category filter. But we do not see that ability in our Metabase 0.18 - just plain input fields. Is this feature already released ?

**Comment by tlrobinson** [comment]
@vkovalskiy It will only show up as a category picker if the underlying fields that are mapped to that parameter have less than 40 distinct values. The same behavior occurs in the query builder, so if you see a category picker when adding a filter on that field then you should also see it in the dashboard filters.

We plan on adding a "typeahead" search for ID filters (#2739) and could possibly do the same for categories.

**Comment by MrMauricioLeite** [comment]
Great idea @tlrobinson 
A "typeahead" search would be awesome for filters

**Comment by vkovalskiy** [comment]
@tlrobinson yes - typeahead would be a real saver! We are building dashboard with metrics of the customer and their dynamics. So we expected to use filter to switch between customers and there are much more than 40 of them. I would also suppose an ability to enter short SQL query for ID lookup when we could provide metabase with the table of ID and NAME properties. So that it would use NAME as the value for lookup (probably with typeahead) and ID for the actual filtering.

p.s. Are there any plans to link filters with card with manual SQL queries ? There many cases we use them and they are great for displaying key numbers.

**Comment by vkovalskiy** [comment]
ref #1543

**Comment by solomongifford** [comment]
Our major use case is a key-value store that are associated with objects.  There are more than 40 objects and way more than 40 keys, so the filtering only on columns with fewer than 40 essentially makes this feature out of reach for us.  I would even take it without the typeahead if I could just be able to type in the string to filter by.

**Comment by tlrobinson** [comment]
Related to issues #2739 and #3215, and PR #4147

**Comment by jornh** [comment]
@vkovalskiy you’re the OP of this issue. With v0.29 out the door now and reference to https://github.com/metabase/metabase/issues/2739#issuecomment-365671378 thread do you still see anything actionable here or can you close this issue now?

**Comment by fbiz-datatech** [comment]
I am Using ther version 0.34.1 and In my question has 37 distinct values and Metabase does not permit to I use category filters.
