### ISSUE TITLE
Cleanup build/deploy/release process

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2849]
- Script as much of release process as possible
  - started in https://github.com/metabase/metabase-release
- Builds (especially releases) should use the `Dockerfile` for a more consistent build environment  
- Ensure the build (`./Dockerfile`) and deploy (`./bin/docker/Dockerfile`) Dockerfiles are using the expected versions of Alpine, JVM, Node, NPM, etc.
- Slim down both Docker images as much as possible
  - more aggressive `.dockerignore`
  - more conservative `ADD . /app/source`
  - remove extraneous files and compact image if possible?
- `./bin/start` and `bin/docker/run_metabase.sh` are similar and can probably be merged
- ~Is the `./deploy` directory still used?~
- Standarize build script languages on JavaScript, Clojure, and Bash

**Comment by tlrobinson** [comment]
Now that the root `./Dockerfile` is a multi-stage `Dockerfile` that produces a fairly slim Docker image we can probably remove `./bin/docker` directory entirely, if we merge `bin/docker/run_metabase.sh` into `bin/start` and update the `metabase-deploy` scripts (started working on that here https://github.com/metabase/metabase-release/pull/1). 

Alternatively we could have `./bin/start-docker` and `./bin/start-heroku`, which maybe call a generic `./bin/start`.

This assumes we will continue to no longer sign jars, or figure out a way to sign the jar in the Dockerfile (without compromising the signing key). Discussion in #9639

**Comment by camsaul** [comment]
We should switch our base Docker image to `adoptopenjdk/openjdk11:alpine-slim` IMO, WRT the `-slim` variant: 

> These are stripped down JDK builds that remove functionality not typically needed while running in a cloud.

**Comment by salsakran** [comment]
closing since this has had a fair bit of work done to automate our deployment process, and keeping this open doesn't serve much purpose. we'll be actively tweaking that as we go and don't need a tracking issue
