### ISSUE TITLE
standardize admin settings update patterns / code

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2850]
As @camsaul pointed out while working on #2818 our patterns for updating the various parts of the general admin settings have drifted over time. We should move the save changes pattern found in the Slack, Email and SSO sections across the board to standardize the experience for users and developers.

Tasks:
- [ ] Move general settings to submit pattern

**Comment by camsaul** [comment]
@kdoh I feel like I remember you doing this a few months ago?

**Comment by flamber** [comment]
This has been done across multiple versions, example #16506 #12691 #12415 #12283
