### ISSUE TITLE
[CI FLAKE] Tests pass but job fails with Unexpected end of JSON input

### ISSUE THREAD

**Issue by snoe** [metabase/metabase#28509]
Tests pass, but something fails around the junit artefact:

This seems to be the culprit
`Warning: Test report summary exceeded limit of 65535 bytes and will be trimmed`

Examples:
https://github.com/metabase/metabase/actions/runs/4236814643/jobs/7362071063
https://github.com/metabase/metabase/actions/runs/4236814643/jobs/7362069759

**Comment by nemanjaglumac** [comment]
Haven't seen this in a while.
Seems like #28584 fixed it.
