### ISSUE TITLE
Tracking Auto-refresh

### ISSUE THREAD

**Issue by christophe-lanternier-cko** [metabase/metabase#28520]
Hi there, 

I am currently trying to regulate usage of Metabase. We get way to many queries that aren't really justified. Many of them seem to come from auto-refresh that have been put in place and then forgotten, so here is my question:
is there a way to track which users have set which auto-refresh in the metabase database? 

Thanks a lot for the help! 

Christophe

**Comment by paoliniluis** [comment]
You mean the refresh of the cached models? Or refresh of the dashboard in the browser?

**Comment by paoliniluis** [comment]
Hi @christophe-lanternier-cko , we need more context or we will close the feature request. Thanks !
