### ISSUE TITLE
[Feature] Dataset level permissions?

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#2856]
Sample use case: Dev Team vs Sales Team working on different datasets. I understand the whole concept of this being transparency in org, still.

PS: Great project! Keep up the good work.

**Comment by VikramTiwari** [comment]
I would like to work on this. Overall concept is:
- During user signup/addition, assign a team to user
- Activities, dashboard, questions, pulses and datasets and any other individual elements get an additional field `team`
- While getting data out during query, read user's team and filter every other dataset based on that user
- Can save configurations for email/slack based on teams as well

Can someone help me to get started with this? Right now trying to understand if this should be the strategy or modification is needed.

**Comment by salsakran** [comment]
@VikramTiwari we're actually in the middle of designing a permissions system. Would you like to be included in the discussions and perhaps take on some of the work? It's a touch different than what you're describing but not far off.

It will involve a fair bit of backend + frontend work. We're still a bit away from getting the visual design finalized but more than happy to include you in the process.

**Comment by VikramTiwari** [comment]
@salsakran Count me in! 👍

**Comment by salsakran** [comment]
give us a day or so. we're planning out the various stages of permissions we'd like to fold in. Based on that, we'll talk out an architecture with you =)

In the meantime, I'd play around with our build process and make sure you can build the jar, run tests, etc.

**Comment by VikramTiwari** [comment]
Nice, will be waiting to hear back. I have been trying my hands on the deployment processes and issues regarding that.

**Comment by nishikant** [comment]
Any Idea by when this will be released?

**Comment by camsaul** [comment]
This was implemented as part of #3376
