### ISSUE TITLE
Full App Embedded Metabase logsout on refreshing any page and asks user to login again

### ISSUE THREAD

**Issue by yasergsi** [metabase/metabase#28561]
**Describe the bug**
Enterprise Full App Embedding logout on refreshing any page and ask s user to login again

Type:Bug

**Logs**
None

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Go to your-full-app-embedded-url
2. Signin / Login
3. Refresh the Page

**Expected behavior**
Page should refresh and not logout

**Screenshots/videos**
not required I suppose

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

- Your browser and the version: Safari 16.3
- Your operating system: OS X 13.2.1
- Your databases: MySQL
- Metabase version: 1.45.3
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

**Severity**
Very Severe, it's irritating our clients using Full App Embedding to re-login every time they refresh.

**Comment by paoliniluis** [comment]
When using full app embedding users should not be asked for login, this seems to be a misconfiguration of full app embedding to which I recommend checking https://github.com/metabase/sso-examples

**Comment by paoliniluis** [comment]
Also, if testing full app embedding you can email support 😀
