### ISSUE TITLE
Add ability to remove columns from column header settings

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#28608]
## What
You can add and remove columns from the viz settings sidebar today, but in many cases, it feels more intuitive and nicer to simply remove one column from the "column header > column settings popover" instead. Let's add a  "hide column" option here. [Slack context](https://metaboat.slack.com/archives/C01MS7DQKR6/p1677167225148309).

![Image](https://user-images.githubusercontent.com/16455495/221211478-8bade6da-21de-4bc3-936b-78f4306d518d.png)

**Comment by mazameli** [comment]
[Here are the mockups](https://www.figma.com/file/JHfakVa132vASEKPsSByQi/Hide-column-action-from-column-heading?node-id=2%3A734&t=GpPeP2AHSkhOLJjC-11).

**Comment by EmmadUsmani** [comment]
I ended up abandoning work on the drag and drop prototype due to it not being easy to implement. There were CSS issues with the horizontal scrolling in the Table visualization not working.

**Comment by npfitz** [comment]
Resolved in https://github.com/metabase/metabase/issues/33841
