### ISSUE TITLE
Make it easier to clear the measure in "Summarize" without losing your dimensions

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#28609]
## What
When you are in the query builder, and add a "Summarization" then you select your measure, and the dimensions that you want to break out your measure with. Let's say you want to change the measure that your using. If you click the measure directly, you can switch it out without losing your dimensions. But if you remove the measure, then you lose all your dimensions. Let's keep them around in this case.

https://www.loom.com/share/bbaf48ca98fe46488219b3e5997f7e5b

## Reproductions steps

1. New GUI Question > Sample Database > Orders
2. Summarize "Count of rows" by "User ID" and "Created At"
3. Remove the "Count" metric in "Summarize" step

**Expected result**: "User ID" and "Created At" stay selected in the editor. You can choose a new metric for them.
**Actual result**: the entire "Summarize" step disappears.

**Comment by kamilmielnik** [comment]
Reproducible in 0.45.1.
Done in `master` ([d35c779](https://github.com/metabase/metabase/commit/d35c779976ae6bd79369e9cc6bec8540908f37d2)) - [screenshot](https://github.com/metabase/metabase/assets/6830683/7deaf50d-13a7-41a4-b3fa-9f2c29ba3147).
Marking as done in the next version (48).
Closing.

**Comment by snoe** [comment]
Reopen to land test
