### ISSUE TITLE
Custom column errors when custom columns exist in different nested queries

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#28610]
**Describe the bug**
In a nested query with multiple custom columns in different levels of the query the query breaks and it shows the following error:
<img width="423" alt="Screenshot 2023-02-24 at 16 45 19" src="https://user-images.githubusercontent.com/113892067/221222456-e39e403c-bfc0-44ad-8d08-c8f834031dde.png">

This is the query builder view:
<img width="1763" alt="Screenshot 2023-02-24 at 16 44 18" src="https://user-images.githubusercontent.com/113892067/221222221-74a22c3a-76b5-4c76-826f-e78198001c85.png">

When removing the last custom query (not the one addressed in the error, then the query runs again)

**To Reproduce**
1. Create a question with a custom column
2. Use join to add another table
3. Create another custom column
4. Click visualise
5. See error

**Severity**
Rather low, quite a rare case. Can also work around by filtering with custom expression in the first query instead of using the custom column.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "5.4.202+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
Hi @carstenkadmos , can you try 46.3 and tell us if this issue keeps happening ?
