### ISSUE TITLE
Page not found error randomly appears while using SQL query editor.

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#28624]
**Describe the bug**
While inputting a query in the SQL editor I randomly received an unrelated error about a page not being found as I typed my query.

**To Reproduce**
Note: this bug was hard to reproduce consistently.
1. +New
2. SQL Query
3. Start typing query in editor

**Expected behavior**
There should have been no errors that were unrelated to my query.

**Screenshots/videos**

https://user-images.githubusercontent.com/37751258/221316159-092b827f-d1d7-4c60-a635-c01fe1bc150f.mov

**Information about your Metabase Installation:**

Local dev env, master branch, commit `0c56664819`

**Severity**
Mildly annoying visual bug that made it hard to input a query, but otherwise not severe.

**Comment by paoliniluis** [comment]
If you're able to reproduce at some point in the future, please post browser console logs and networking logs

**Comment by EmmadUsmani** [comment]
Closing as duplicate of https://github.com/metabase/metabase/issues/30039
