### ISSUE TITLE
Parameterized SQL cards

### ISSUE THREAD

**Issue by tomkanjam** [metabase/metabase#2863]
Dashboard filters are awesome but they would be spectacularly awesome if they could be applied to cards that were created with SQL.

**Comment by tlrobinson** [comment]
This is actually in progress in PR #2795 but I don't think we have an issue for it so I'll leave this open.

**Comment by federicokeen** [comment]
This would be an amazing feature to have. Glad to hear that its in process. Related to this issue, could it be possible to use SEGMENTS in sql queries? To provide an example, on a table that has a status column with 10 different possible values, 6 of those are considered ACTIVE for our business. We still use the other 4, but they can't access a lot of functionality. So i defined an ACTIVE segment on that table, that filters by those 6 status. It would be awesome to be able to use SEGMENTS as SQL variables somehow.

**Comment by camsaul** [comment]
@tomkanjam and @federicokeen this feature actually shipped as part of our last release. Check out our [documentation about using SQL parameters.](http://www.metabase.com/docs/latest/users-guide/12-sql-parameters.html)

Implemented by #2795.
