### ISSUE TITLE
Audit Log should also allow statistics for Public/Embedding - including downloads

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28633]
Is your feature request related to a problem? Please describe.
Audit Log currently doesn't show any information about Public//Embedding activity (not sure if this is more of a bug than feature)

Describe the solution you'd like
Audit Log should also allow statistics for Public/Embedding - including downloads

Describe alternatives you've considered
Nginx log and some tool to analyze those logs

Related https://github.com/metabase/metabase/issues/11909 and https://github.com/metabase/metabase/issues/18758

NOTE, also adding comments from @salsakran 
A user asked for the ability to track usage of embeds, especially

- the clicks on 'download data' underneath graphs
- the clicks on additional pages on graphs (ie when there are multiple pages to view below the tables)

In general, having an "embeds" section of the audit app might be useful.

**Comment by albertoperdomo** [comment]
This could be addressed by audit v2. We should revisit this when it ships.
