### ISSUE TITLE
Feature Request: Adaptive x-axis labels on time series

### ISSUE THREAD

**Issue by spectr** [metabase/metabase#2864]
Here is a chart that shows event counts grouped by hour for the last 7 days:

![image](https://cloud.githubusercontent.com/assets/303566/16529220/7f3215d2-3f76-11e6-8fdb-9cc66ececd3d.png)

There's not enough space to show a label for each hour but it would still be very helpful to have labels for days. The x-axis labels should adapt based on available space as happens in most charting libraries.

**Comment by tlrobinson** [comment]
@spectr We do adaptive X axis labels, however it looks like that particular card is at a minimum height, in which case we automatically hide the X axis labels. If you view the card in the query builder, or make the card taller, do you see the axis?

**Comment by spectr** [comment]
I tried that before creating the issue and the labels didn't show up.

I went back and refreshed the page again and they are now showing up. Thanks for the the response!
