### ISSUE TITLE
JWT admin panel section shows same buttons+modal for embedding

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28644]
Describe the bug
The JWT auth section in Admin Panel references "embedding", which doesn't apply here and causes confusion.

To Reproduce

Admin > Settings > Authentication > JWT

Clicking "Regenerate key" shows the modal for "Regenerate embedding key?" - huh?
![image](https://user-images.githubusercontent.com/1711649/221381180-f61762b0-df18-4d91-b05d-41c0c0ae8a6c.png)

Product edit:
When clicking on `Regenerate key` the modal should have this copy:

Title: Regenerate JWT signing key?
Text: This will cause existing tokens to stop working until the identity provider is updated with the new key.
Are you sure you want to do this?

Information about your Metabase Installation:
Metabase 1.36.6.1

Additional context
ticket 2507

**Comment by luizarakaki** [comment]
Moving this to P2 as this can be misleading
