### ISSUE TITLE
Return zero-value counts for time groupings when using query builder

### ISSUE THREAD

**Issue by spectr** [metabase/metabase#2865]
The lack of zero-value counts causes line charts to look misleading. Example(Using Metabase Sample data):

Records are only returned for hours where count > 0
![image](https://cloud.githubusercontent.com/assets/303566/16530070/018bb958-3f7b-11e6-84a9-4dfc7527f982.png)

The resulting chart is misleading.
![image](https://cloud.githubusercontent.com/assets/303566/16530146/5ed5df58-3f7b-11e6-88b0-c0a8f2650cc0.png)

### Real-data example

Query builder:
![image](https://cloud.githubusercontent.com/assets/303566/16530368/a41655a6-3f7c-11e6-8476-da79293789e7.png)

SQL query that includes zero-counts:
![image](https://cloud.githubusercontent.com/assets/303566/16530557/89c3da38-3f7d-11e6-8799-295f2113e969.png)

**Comment by tlrobinson** [comment]
Duplicate of #896?

**Comment by spectr** [comment]
@tlrobinson  Yes, it's a duplicate. Thanks.
