### ISSUE TITLE
Cannot re-order columns

### ISSUE THREAD

**Issue by ccalby** [metabase/metabase#28651]
**Describe the bug**
Unable to order columns on questions.
Database column ordering is correct, but Metabase returns an abnormal order.

Cannot reorder using the Metabase UI. Dragging columns fails to reorder questions.
Cannot use side menu settings when viewing a question to re-order. Drag and drop just returns the column to previous position.
Think possibly due to GROUP BY clauses??

**Expected behavior**
Should be able to reorder via UI.
By default, Metabase should follow database schema.

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.15.0-56-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.32-0ubuntu0.22.04.2"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Comment by paoliniluis** [comment]
Please send repro steps with the sample database

**Comment by paoliniluis** [comment]
Closing as this should be fixed in 46
