### ISSUE TITLE
Upgrade the H2 DB

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#28682]
The current version of H2 DB used in Metabase is 1.4.197. This version doesn't support `ROW_NUMBER` and some other window functions (the support was added in v1.4.198. Currently the latest version is 2.1.214). 
The sample dataset is used for unittests (among other usages) and it's desirable that a version of H2 be used that supports the common operations as other major RDBMSs.

v0.45.2

**Comment by paoliniluis** [comment]
This was upgraded in v46 :)

**Comment by vvaezian** [comment]
@paoliniluis I see. Any estimate for when v46 will be released?
