### ISSUE TITLE
[MLv2] Implement `remove` and `replace`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#28718]
### Related PRs

- https://github.com/metabase/metabase/pull/29625
- https://github.com/metabase/metabase/pull/29657
- https://github.com/metabase/metabase/pull/29775
- https://github.com/metabase/metabase/pull/29777
- https://github.com/metabase/metabase/pull/29803
- https://github.com/metabase/metabase/pull/29841
- https://github.com/metabase/metabase/pull/30002
- https://github.com/metabase/metabase/pull/30074
- https://github.com/metabase/metabase/pull/30373
- https://github.com/metabase/metabase/pull/30775

### `remove`

takes a clause and removes it. I think this should probably take `stage-number` as an optional parameter, defaulting to `-1` (last stage of the query) if not explicitly specified, the same way literally everything else does. Since we have UUIDs (see below) I guess it would be possible to walk all the stages and find something to remove, but this seems more complicated than we need right now

```clj
(let [my-order-by (first (order-bys query -1))]
  (remove query my-order-by))
```

or 

```js
const orderBy = query.orderBys()?.[0];
query = query.remove(orderBy);
```

The whole reason we added `:lib/uuid` in the options in the first place was to facilitate this sort of stuff, so we should obviously leverage this info. 

I think we'll want to have some sort of underlying `remove*` multimethod that we can implement to handle various MBQL clauses and maps. e.g. we'd have an `:asc` method which would then go look in `:order-by` and find the matching `:asc` with the same `:lib/uuid` and remove that from the query. Some stuff like `:field` clauses would probably have to look in multiple places, e.g. both `:fields` and `:breakout`. On that note, if we're not already doing it, we should enforce a rule against duplicate UUIDs in a query stage (ignoring metadata)

Removal methods that affect the columns that will be in the response should update `:lib/stage-metadata` for the affected and subsequent stages, e.g. if I remove something from `:fields` or `:breakout` the `:lib/stage-metadata` should reflect this.

Open question: should we "clean" the query and remove orphaned references? E.g. if I have a join and add a filter against a joined field, then remove the join, should we do a "cascading delete" and remove the filter as well? I am about 95% sure the answer should be yes here. So let's implement that too. 

This will have to be done on a case-by-case basis for different `remove*` impls

### `replace`

This is basically the same as `remove`, but instead of removing it just replaces the clause in that location with a different clause

```clj
(let [my-order-by (first (lib/order-bys query -1))
       new-order-by (lib/order-by-clause (lib/field whatever))]
  (lib/replace query my-order-by new-order-by))
```

I guess this should probably be implemented with an underlying multimethod as well. This also needs to update metadata and "clean" the query where appropriate. 

Question: can we be smart and instead of removing stuff, update it to the equivalent when possible? E.g. if I join table X and have a filter where X.ID = 1, and I replace the join with one against Table Y, which also has ID, can we update the filter to be Y.ID = 1? That would be **smart AF**. I think we should try to do that as a best-effort thing.

**Comment by camsaul** [comment]
The designs above are rough drafts and if we want to go a different direction with things then that is 👍

**Comment by snoe** [comment]
Future improvements could try simplifying clauses instead of whole removal.
