### ISSUE TITLE
Dashboards don't show up after creating them until you refresh the page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2871]
If this is a bug report, please fill in the blanks:
-  I am using the Chrome browser.
-  My computer's OS is OS X
-  I'm running Metabase locally via `lein ring server`
-  My database is H2 Sample Dataset
-  My Metabase version is 0.19.0-SNAPSHOT

Basically the dashboards dropdown doesn't update until you refresh the page.
1.  Have no dashboards
2.  Create a new dashboard
3.  Dashboard doesn't show up in menu

![screen shot 2016-07-01 at 6 22 15 pm](https://cloud.githubusercontent.com/assets/1455846/16537529/75209f94-3fb9-11e6-8b27-8af7aad52dc2.png)

**Comment by tlrobinson** [comment]
This probably broke in the conversion to Redux (which is pretty ironic, actually)

**Comment by tlrobinson** [comment]
This will be fixed by #3067 so I'm going to move it to 0.20

**Comment by camsaul** [comment]
I'm still seeing this in master (`0.21.0-SNAPSHOT`)

![screen shot 2016-10-18 at 12 24 50 pm](https://cloud.githubusercontent.com/assets/1455846/19493041/e6476260-952d-11e6-92ab-223514854cd2.png)

**Comment by tlrobinson** [comment]
This happens when creating dashboards from the qb "add question to dashboard" modal but not from the dashboard menu.

**Comment by attekei** [comment]
Doesn't happen anymore with the new dashboard list page so I will close this issue.
