### ISSUE TITLE
Step previews in notebook editor are not working

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#28726]
**Describe the bug**
The question preview shows a blank table

**Logs**
no error logs from both console log and backend

**To Reproduce**
1. New question on any table
2. Click on the :arrow_forward:  button to preview the table

**Expected behavior**
Should show the table result

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/25661381/221785431-d2ee33a2-e784-4a2b-86d8-58b389606785.png)

**Information about your Metabase Installation:**
current master(ee44d788ea2bad9a491aa93528cbbba4516ef3d6)

**Severity**
Regression

**Comment by nemanjaglumac** [comment]
Works on 45.
This is a regression on `master`. Giving it P1 only because it's a basic feature that's not working.

Visualize, filters, aggregations and all other aspects of the Notebook are still working.

**Comment by npfitz** [comment]
Is being caused by the table component not being passed a proper height. This appears to be due to some recent wrapping inside the `Visualization` component that assists with previews. PR incoming.
