### ISSUE TITLE
Column values disappear when using Summarize 

### ISSUE THREAD

**Issue by sirren123** [metabase/metabase#28729]
Hey,

I am experiencing that the figures of some columns are hidden. They are shown until I set a Summarize function on them. See picture below. I figure this is a bugg and I need help solving it. Thank you! :) 

![Bugg lime Bi](https://user-images.githubusercontent.com/89836586/221834178-69efb4db-6ff7-44aa-86cd-efab52051a52.png)

**Comment by paoliniluis** [comment]
We need a reproduction and also diagnostic info to see if this is a bug or not

**Comment by sirren123** [comment]
Do you mean a reproduction of the diagram, if yes, where do I place the reproduction? Where do I find the diagnostics info?

**Comment by sirren123** [comment]
![image](https://user-images.githubusercontent.com/89836586/222732949-e94fe128-5dd6-4fe5-835f-6a63a736c9de.png)

Here is the Javascript Console report. I have reproduced the question and placed in on my personal collection. Thanks!

**Comment by paoliniluis** [comment]
Please post steps for reproducing this error, also post diagnostic info

**Comment by ranquild** [comment]
Can't repro.
