### ISSUE TITLE
It should be possible to resend a pulse

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2873]
It is very useful to be able to send out a pulse manually. This comes up in situations like temporary email outages, etl failures, etc.

**Comment by salsakran** [comment]
or possibly rename "send test pulse" to signify what it actually does, which is "send now"?

**Comment by mazameli** [comment]
I'm all about changing the text on the buttons and calling it a day, since the functionality is already there:

`Send email now` and `Send to Slack now`
