### ISSUE TITLE
Hour-of-day formatting is wrong on Druid

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#2874]
As you can see, the formatting only works for hours till 12pm.

<img width="261" alt="screen shot 2016-07-03 at 22 13 10" src="https://cloud.githubusercontent.com/assets/1543669/16547364/680cdcec-416b-11e6-8218-4e87ec7173bb.png">

If this is a bug report, please fill in the blanks:

*  I am using the chrome browser.
*  My computer's OS is macosX
*  I'm running Metabase 0.18 locally from the JAR .
*  My database is druid/h2.

**Comment by camsaul** [comment]
@tlrobinson so this would be fixed if the druid driver returned hours as integers instead of strings?

**Comment by tlrobinson** [comment]
@camsaul correct
