### ISSUE TITLE
PNG downloads of gauge charts are clipped

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#28743]
**Describe the bug**
PNG downloads of gauge charts are clipped.

**To Reproduce**
1. Create a gauge chart
2. Download it (be it from the question or a dashnoard)

**Expected behavior**
For it to appear entirely.

**Screenshots/videos**
![NPS Gauge-2_28_2023, 3_47_26 PM](https://user-images.githubusercontent.com/328388/221905142-8912cf04-b8d4-4427-acee-19f2f3db4578.png)

**Information about your Metabase Installation:**
Master on Feb 28 2023 15:45 GMT
Chrome 110.0.5481.177 on MacOS Ventura 13.2 (22D49)

**Comment by paoliniluis** [comment]
browser?

**Comment by brunobergher** [comment]
Sorry, included
