### ISSUE TITLE
[Epic] Bring Markdown to descriptions of collections, questions, dashboards

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#28754]
We currently support autolinking link-like strings (e.g. [google.com](http://google.com/), https://google.com/, [a@google.com](mailto:a@google.com)) in Markdown on dashboard text cards, but not in descriptions (collections, questions, dashboards), which are just plain text. We should add markdown support for these entities.

**Implementation Plan**
We already have a `Markdown` component used to render descriptions of timelines and timeline events: https://github.com/metabase/metabase/blob/6426f366da599dca80f0165da1e7dc040f9d2d4c/frontend/src/metabase/timelines/collections/components/TimelineCard/TimelineCard.tsx#L39 https://github.com/metabase/metabase/blob/24c7832edfa440793d0ddc5b36f29ecbdd9bf84e/frontend/src/metabase/timelines/collections/components/TimelineCard/TimelineCard.styled.tsx#L29 We could reuse it to render the description of other entities. And we could continue editing the description with a plain `TextArea` component as we do for timelines.

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/29753
- [ ] https://github.com/metabase/metabase/pull/29624
- [ ] https://github.com/metabase/metabase/pull/29624
```

**How to Test This Feature Out**

- Add a link with the markdown syntax to collection/question/dashboard description.
- Make sure it is rendered as a link.

**Comment by nathanjones4323** [comment]
Would love to be able to use markdown in descriptions.

This is a related issue on being able to use markdown inside of the descriptions for columns and tables
[#27803](https://github.com/metabase/metabase/issues/27803)
