### ISSUE TITLE
Unable to Query Across MongoDB Collections

### ISSUE THREAD

**Issue by pygeek** [metabase/metabase#2876]
I need to be able to query across multiple collections in MongoDB either through the GUI or the custom query editor. It is currently not possible to do this via either interfaces.

The GUI returns an error stating that it's not supported by the driver.
Although the custom query editor now supports MongoDB, it only allows query through the aggregation pipeline within scope of a single collection.

Has this been addressed in another issue or pull request? If not, are there any plans to support this in either the GUI or custom query editor in the near future?

**Comment by salsakran** [comment]
what sorts of things across collections are you trying to do? Can you give us an example or two?

**Comment by pygeek** [comment]
Here is an example model:
```
accounts: [{
  _id: ...
  name: "Test Account"
  meta:
    uniqueAccountAttribute: "SomeRandomString"
}]
contracts: [{
  _id: ...
  amount: "200.00"
  meta:
    uniqueAccountAttribute: "SomeRandomString"
}]
```

Some things I'd like to do with that model:

#get all the contracts for an account
#get contract spend by account
#get highest contract spends by account

**Comment by pygeek** [comment]
Any feedback on the additional information I added?

**Comment by camsaul** [comment]
Unfortunately Metabase is subject to the same limitations as Mongo aggregation pipeline queries themselves; if what you want to do isn't possible with a custom query there's not much we can do -- unfortunately we cannot extend the capabilities of MongoDB itself 💔

**Comment by camsaul** [comment]
@pygeek does my explanation make sense? If so, feel free to close this issue 😉

**Comment by camsaul** [comment]
@pygeek let me know if that explanation makes sense 😉

**Comment by camsaul** [comment]
@pygeek, I'm hoping that explanation makes sense. Since there hasn't been any activity on this thread since July I'm going to go ahead and close it out. Feel free to open a new issue if you are still having issues like these.
