### ISSUE TITLE
v0.18.1 isn't tagged as latest on Docker

### ISSUE THREAD

**Issue by dlackty** [metabase/metabase#2877]
As you can see [on Docker Hub](https://hub.docker.com/r/metabase/metabase/tags/):

<img width="1204" alt="screen shot 2016-07-04 at 9 55 33 pm" src="https://cloud.githubusercontent.com/assets/14349/16562963/1d20ba06-4232-11e6-9a4a-ea9860285eb8.png">

**Comment by salsakran** [comment]
good catch! fixed!
