### ISSUE TITLE
Viz Charts don't support customisation of series with more than 20 groups

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#28796]
**Is your feature request related to a problem? Please describe.**
The ability to customize which values/colours appear in a Viz chart is limited to when there are less than 20 values in the series.

In the picture below, when there are less than 20 Titles, you can individually determine which ones to display in the series:

![image](https://user-images.githubusercontent.com/110378427/222206046-b5d467df-c2b1-45cf-81f9-4e8fc74ba814.png)

Once you have more than 20, the option is no longer available:

![image](https://user-images.githubusercontent.com/110378427/222206311-4b65aa89-d5ff-4a42-954c-e2f1b549ad7d.png)

**Describe the solution you'd like**

Remove the limit of 20 and make it consistent with the chart series limit. For example a line chart only supports a series of 100

![image](https://user-images.githubusercontent.com/110378427/222206621-4a4fd048-e4b8-4869-b901-d856ecb2d1f3.png)

So make the limit consistent with the how much the chart support

**Comment by cdeweyx** [comment]
Fix here is to remove the 20-series limit in viz settings. [Slack thread](https://metaboat.slack.com/archives/C04D0E4837E/p1677681109390559).
