### ISSUE TITLE
Display Generated SQL in a nicely formatted, ideally syntax-colored way

### ISSUE THREAD

**Issue by nina-metabase** [metabase/metabase#28801]
When you click on "convert question to SQL", the default sql is not formatted and creates one long line. This makes it very difficult to parse and understand the question when you need to be in SQL to modify. It would be nice if it were nicely formatted.

Seems like something where we could slap a library and call it a day.

**How important is this feature to you?**
It would make it a lot easier to understand the generated SQL, sanity check it, and debug it for SQL writers, who are an influential and important bunch.

**Comment by dpsutton** [comment]
How to implement this:
We already have a great lib that pretty prints sql: https://github.com/vertical-blank/sql-formatter
and it is already hooked up and ready to go: https://github.com/metabase/metabase/blob/master/src/metabase/db/query.clj#L36

When you convert an mbql query to a native query, the FE gets the query from `POST api/dataset/native`. I propose that we augment this endpoint to return a new optional key of `:pretty`. This key, if set, will include the pretty printed sql.

#### Unformatted sql
```sql
SELECT "PUBLIC"."PRODUCTS"."ID" AS "ID", "PUBLIC"."PRODUCTS"."TITLE" AS "TITLE", "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", "Orders"."TOTAL" AS "Orders__TOTAL", "Orders"."QUANTITY" AS "Orders__QUANTITY", "People - User"."NAME" AS "People - User__NAME", "People - User"."STATE" AS "People - User__STATE" FROM "PUBLIC"."PRODUCTS" LEFT JOIN "PUBLIC"."ORDERS" AS "Orders" ON "PUBLIC"."PRODUCTS"."ID" = "Orders"."PRODUCT_ID" LEFT JOIN "PUBLIC"."PEOPLE" AS "People - User" ON "Orders"."USER_ID" = "People - User"."ID" LIMIT 5
```

#### Formatted sql
```sql
SELECT
  "PUBLIC"."PRODUCTS"."ID" AS "ID",
  "PUBLIC"."PRODUCTS"."TITLE" AS "TITLE",
  "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY",
  "Orders"."TOTAL" AS "Orders__TOTAL",
  "Orders"."QUANTITY" AS "Orders__QUANTITY",
  "People - User"."NAME" AS "People - User__NAME",
  "People - User"."STATE" AS "People - User__STATE"
FROM
  "PUBLIC"."PRODUCTS"
  LEFT JOIN "PUBLIC"."ORDERS" AS "Orders" ON "PUBLIC"."PRODUCTS"."ID" = "Orders"."PRODUCT_ID"
  LEFT JOIN "PUBLIC"."PEOPLE" AS "People - User" ON "Orders"."USER_ID" = "People - User"."ID"
LIMIT
  5
```

#### Endpoint
Couple ways to proceed:
- return both regular query and pretty query and let the FE remove the regular and substitute with pretty when appropriate. This lets consumers of this decide to opt in to the new pretty query. And hopefully the extra key is benign to other callers who aren't updated for this
- Have the BE substitute the pretty query for the regular query. My worry here is that what if the lib doesn't produce valid code in some circumstances.
- Have the route check for a query param which can indicate to substitute the pretty query. This lets consumers decide to opt in to the new functionality. This might be preferred and if we end up with issues with the pretty code not emitting correct sql we can offer in the UI to not prettify it.

```
# endpoint hooked up with the first option listed above. Not necessarily my preferred solution
❯ echo '{"database":1,"query":{"source-table":1,"joins":[{"fields":[["field",40,{"join-alias":"Orders"}],["field",39,{"join-alias":"Orders"}]],"source-table":2,"condition":["=",["field",60,null],["field",36,{"join-alias":"Orders"}]],"alias":"Orders"},{"fields":[["field",53,{"join-alias":"People - User"}],["field",47,{"join-alias":"People - User"}]],"source-table":5,"condition":["=",["field",42,{"join-alias":"Orders"}],["field",46,{"join-alias":"People - User"}]],"alias":"People - User"}],"fields":[["field",60,null],["field",65,null],["field",58,null]],"limit":5},"type":"query","parameters":[]}' | http POST localhost:3000/api/dataset/native Cookie:$SESSION -pb
{
    "params": null,
    "pretty": "SELECT\n  \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\",\n  \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\",\n  \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\",\n  \"Orders\".\"TOTAL\" AS \"Orders__TOTAL\",\n  \"Orders\".\"QUANTITY\" AS \"Orders__QUANTITY\",\n  \"People - User\".\"NAME\" AS \"People - User__NAME\",\n  \"People - User\".\"STATE\" AS \"People - User__STATE\"\nFROM\n  \"PUBLIC\".\"PRODUCTS\"\n  LEFT JOIN \"PUBLIC\".\"ORDERS\" AS \"Orders\" ON \"PUBLIC\".\"PRODUCTS\".\"ID\" = \"Orders\".\"PRODUCT_ID\"\n  LEFT JOIN \"PUBLIC\".\"PEOPLE\" AS \"People - User\" ON \"Orders\".\"USER_ID\" = \"People - User\".\"ID\"\nLIMIT\n  5",
    "query": "SELECT \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\", \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", \"Orders\".\"TOTAL\" AS \"Orders__TOTAL\", \"Orders\".\"QUANTITY\" AS \"Orders__QUANTITY\", \"People - User\".\"NAME\" AS \"People - User__NAME\", \"People - User\".\"STATE\" AS \"People - User__STATE\" FROM \"PUBLIC\".\"PRODUCTS\" LEFT JOIN \"PUBLIC\".\"ORDERS\" AS \"Orders\" ON \"PUBLIC\".\"PRODUCTS\".\"ID\" = \"Orders\".\"PRODUCT_ID\" LEFT JOIN \"PUBLIC\".\"PEOPLE\" AS \"People - User\" ON \"Orders\".\"USER_ID\" = \"People - User\".\"ID\" LIMIT 5"
}
```

#### Route changes
```clojure
#_{:clj-kondo/ignore [:deprecated-var]}
(api/defendpoint-schema POST "/native"
  "Fetch a native version of an MBQL query."
  [:as {query :body}]
  (binding [persisted-info/*allow-persisted-substitution* false]
    (qp.perms/check-current-user-has-adhoc-native-query-perms query)
    (let [{q :query :as compiled} (qp/compile-and-splice-parameters query)
          driver                  (driver.u/database->driver (:database query))
          pretty                  (try (mdb.query/format-sql q driver)
                                       (catch Exception _e nil))]
      (cond-> compiled
        pretty (assoc :pretty pretty)))))
```

**Comment by markbastian** [comment]
My preference is a hybrid of options 2 and 3: We can pretty the query and if the prettification fails, we just return the original unprettified query. One question: Should we default prettificaiton on or off? I would think under most cases you'd want it on, so I'd recommend a flag `pretty?` that defaults to true. To be clear, here's what I am suggesting:

- Change the current `/native` endpoint to return prettified SQL when prettification works and the raw SQL if for some reason prettification fails.
- If `pretty? true` is passed in the body of the request, default to the above behavior.
- If `pretty? false` is passed in the body of the request, do not prettify the query.

**Comment by markbastian** [comment]
After chatting with @dpsutton we're going to change the above to default not-pretty, but if any of you product folks would rather default pretty we can go that way. A downside we can think of for default pretty is that there _may_ be some quoting or other issues related to different SQL dialects that might be problematic.

**Comment by markbastian** [comment]
https://github.com/metabase/metabase/pull/29336 contains the BE PR for this feature. If we want this on, we'll need the FE to pass in the `pretty? true` in the body of the `POST api/dataset/native` call. There are a few potential paths moving forward:

- I can change the BE flag to default true (currently is default false). This will require no additional FE or other work, but there _might_ be downstream consequences (E.g. someone doesn't want formatted output and they are used to that).
- The FE can be changed so that the default call to `POST api/dataset/native contains `pretty? true` in the request body. This has the same effect as above. I am assuming the level of effort for this is quite small.
- The FE could have a flag set in user or global preferences to to set the flag. I'm assuming the level of effort for this is medium.

@dpsutton, @nina-metabase, @brunobergher -- LMK how you'd like to move forward.

**Comment by paoliniluis** [comment]
sorry, maybe I'm not understanding well the solution, but why are we going to do this on the backend when, I think, it should be a frontend task exclusively?

**Comment by dpsutton** [comment]
@paoliniluis we saw an easy win for the BE while the FE team is more constrained right now. We already have a library that seems to do a great job of formatting sql. To get the sql at all the FE asks the BE. So it made sense that we could provide some nicer formatted sql for the FE.

Is there a reason that the FE should be in charge of this conceptually if it's asking the BE for the sql in the first place? If it has to ask the server for the sql, the server can easily format it, why not just have it returned the nicely formatted sql?

**Comment by dpsutton** [comment]
if we want to allow the FE to continually reformat their queries while they write then we don't need to do this at all and we can let them take this. I can take it off our board in that case. (not doing that yet, just wondering which way we prefer)

**Comment by markbastian** [comment]
I think I see a few cases here:
- When you get the SQL for the first time, do you want it to arrive formatted? We can do this for you on the BE.
- As you are editing, you want some sort of "format my SQL for me button." In an IDE this would be like a "Reformat this file" button.
- As you are editing, you want automatic formatting. You press enter to go to a new line and you want the right tabbing to occur automatically.

These last two cases are FE, but we can give you the first case right away. Case 2 can take care of Case 1 IF the capability exists by formatting the SQL upon arrival, but IDK the status of that ATM.

**Comment by markbastian** [comment]
The initial request is.

> When you click on "convert question to SQL", the default sql is not formatted and creates one long line....It would be nice if it were nicely formatted.

If this is the case, I would think the current PR meets this requirement and we should default formatting to on. Thoughts?

**Comment by brunobergher** [comment]
Yes, what @markbastian said in the last comment.
Reformatting it in the editor is a different feature. Also nice, but different from this, and I'd love to take the win.

**Comment by markbastian** [comment]
FYI, here would be the before/after experience:

![sqlnotformatted](https://user-images.githubusercontent.com/8381441/226400031-e42f9e2f-44e1-4d68-9643-d09201c974a3.gif)

![sqlformatted](https://user-images.githubusercontent.com/8381441/226400059-9b8ec8df-c3ba-4e91-921c-8d27322513d3.gif)
