### ISSUE TITLE
Make the "save" modal context-aware

### ISSUE THREAD

**Issue by nina-metabase** [metabase/metabase#28802]
**Is your feature request related to a problem? Please describe.**
When I save a new question/model/visualization by default it suggests the root folder of metabase. If the folder you are currently working on is very nested, it makes it difficult to put the new saved question in the same place. This is especially hard for questions you are not sure of their original location. 

**Describe the solution you'd like**
I would like the default suggested location to be the folder the question originally belonged in. 

**How important is this feature to you?**
I don't think this feature is table stakes, I think it is a nice to have that would save me time and works with our mission of enabling laziness. It would also decrease the # of rogue questions since I currently sometimes automatically save which just places it in "Our analytics" 

**Additional context**

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/14298

**Comment by cdeweyx** [comment]
For clarification:
* There are some cases in which we do this already (if I navigate to a question, edit, and save it as a new one, it remembers what collection the original question was in)
* But if I go New > Notebook Editor and create a question, it defaults to Our Analytics. In those cases let's remember the last collection you saved something in and make that the default.
