### ISSUE TITLE
Sustained 50 to 100% CPU - Error processing query: write beyond end of stream

### ISSUE THREAD

**Issue by marcelommm** [metabase/metabase#28839]
**Describe the bug**
- We have a big org (around 200 users) using MB daily.  
- Metabase running as a docker container in a EC2 server.
- CPU usage is usually very low, < 5%. 

Rarely, we have an issue where CPU usage gets stuck at 50 to 100% for 30min or more. Attached, the Logs.  I'm suspecting it has something to do with Pivot tables. Please note we're running version 0.45.2.

**Logs**
[logs.txt](https://github.com/metabase/metabase/files/10871872/logs.txt)

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Open a report with pivot tables
2. It gets stuck in "Doing Science", or takes ages to load. (Data Source has only 40k rows)

**Expected behavior**
Reports should open

**Screenshots/videos**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

```
{
  "browser-info": {
    "language": "pt-PT",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "4.14.281-212.502.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-17",
      "tag": "v0.45.2",
      "branch": "release-x.45.x",
      "hash": "819ce29"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

Whenever a user randomly open few reports the issue seem to happen.

**Additional context**
_Seems like_ didn't have those issues previous to upgrading to 0.45.2

**Comment by paoliniluis** [comment]
I'll leave this issue here as we're going to launch a very interesting redesign of how we run the pivot table queries. If this keeps happening after 46, please let us know. BTW: how big is your Metabase server and your app db in terms of cpu,ram, etc

**Comment by paoliniluis** [comment]
IMHO, 2GB of RAM is very low for 200 users... I would strongly suggest you up that to 3GB or 4 to be fine.

In fact, those CPU spikes might be garbage collection or even swapping, do you see something on the disk IOPs?

**Comment by marcelommm** [comment]
Thanks for the suggestion, I'll bring to the team.

On disk data, unfortunately it's not currently being collected:
![image](https://user-images.githubusercontent.com/112194436/222521638-d40ed375-4239-4bdd-a253-91b8c477995a.png)

**Comment by paoliniluis** [comment]
Ok thanks, I'll be closing this one. You need to install the cloudwatch agent to monitor the memory
