### ISSUE TITLE
Results and download availability for SQL queries should be synced

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#28834]
**Describe the bug**
When a user modifies a SQL query, even if just one character, we consider it to have changed. This leads to making the download button unavailable. This makes strict sense in that "the query has changed", but we don't make the results unavailable. 

The behavior should ideally be synched – we either prevent results _and_ downloads from being used, or we leave them both available. I suspect this may be tricky because the download button would make an API call for the new, edited query, so there's a product decision to be made there as to whether to make downloads bound to the displayed results or the query definition.

**Screenshots/videos**
https://user-images.githubusercontent.com/328388/222416787-96abab44-f740-4ce2-951f-26e2094b857d.mov

**Information about your Metabase Installation:**
Metabase 1.45.3

**Severity**
Not a bit deal, but annoying. Reported by a customer.

**Comment by WiNloSt** [comment]
We should unit test:
- Public question `PublicQuestion.jsx`
- Embedding `PublicQuestion.jsx`
- App and full-app embedding `QueryBuilder.jsx`
