### ISSUE TITLE
Metabase cannot connect to h2 DB

### ISSUE THREAD

**Issue by thekantian** [metabase/metabase#2884]
*  I am using the Chrome browser.
*  My computer's OS is Mac OS X.
*  I'm running Metabase using docker on Google Cloud VM.
*  My database is h2.
*  My Metabase version is 0.18.1.

We've been using Metabase successfully for about 3 months and love it. Last week we updated to 0.18.1 and everything was working properly.

This morning our Metabase server restarted and I'm getting an error in the logs that says:
```
ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB.
...
ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
INFO metabase.core :: Metabase Shutting Down ...
INFO metabase.core :: Metabase Shutdown COMPLETE
```

I've seen some other threads here that maybe the .lock file was the issue, deleted that and restarted and still getting the same error.

Initially I suspected file corruption of the .db file, but I am able to successfully connect to the db using `java -classpath metabase.jar org.h2.tools.Shell` as the same user metabase runs under, and can select data from relevant tables and see my data correctly, so I don't think that the file is corrupted at this point.

Any ideas for what else to try here? Thanks! Any insight much appreciated...

**Comment by camsaul** [comment]
You can try copying the DB file and using the copy instead. Not sure if it will fix it but it's worth a shot.

```bash
cp /path/to/metabase.db.h2.db /path/to/metabase2.db.h2.db
MB_DB_FILE=/path/to/metabase2.db java -jar metabase.jar
```

**Comment by thekantian** [comment]
@camsaul interestingly that seems to have fixed the issue for us. It's odd because we're starting a new instance of the docker container with that file mounted in a volume, so I can't imagine what state is persisting across restarts relevant to that filename. Thanks for the help here, happy to provide any more info it it helps debug the issue more for you guys.

**Comment by camsaul** [comment]
Glad it worked @thekantian.

**Comment by ashokayengar** [comment]
adding system property solved the issue

java -Dh2.bindAddress=localhost -jar metabase.jar

**Comment by omiadgaonkar** [comment]
For me it was metabase.db.lock.db file. I guess due to abrupt shutdown of metabase, 'metabase.db.lock.db' file was not deleted. I deleted the file and started it.  Then, metabase started fine.

Renaming of database file was not needed.

**Comment by camsaul** [comment]
^ @salsakran this is another candidate for something to go in the troubleshooting guide. Deleting the lockfile

**Comment by cepix** [comment]
I solved this error by erasing the .lock file

**Comment by camsaul** [comment]
^ @salsakran sounds like deleting the `.lock` file worked for someone else too. Did you add it to the troubleshooting guide? I don't see it there

**Comment by toybaelescione** [comment]
Solved by try to connect to h2 shell, then disconnect.
OS is Centos 7
`java -cp metabase.jar org.h2.tools.Shell -url jdbc:h2:/opt/metabase/metabase.db`
