### ISSUE TITLE
"Pick a table" in the GUI builder is not correct

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28854]
**Describe the bug**
You can join against questions or models, so picking a table is not correct. We might be biasing our users to think a table is their only option

**Logs**
NA

**To Reproduce**
1) create a saved question
2) create a new question and then pick a join, it says "pick a table", when we have models and saved questions

**Expected behavior**
Change the wording

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/1711649/222518984-ef318815-d435-4601-8ba8-954fa46c77cc.png)

BTW: we're defaulting to raw data... is that correct?

**Information about your Metabase Installation:**
NA

**Severity**
We should be nudging users to use the full potential of the tool

**Additional context**
NA

**Comment by cdeweyx** [comment]
"Pick data" would work here. It's similar to how we frame this elsewhere: 
<img width="395" alt="Screenshot 2023-06-28 at 09 25 52" src="https://github.com/metabase/metabase/assets/16455495/73e74eb4-a61e-4dce-8268-af2223a970e8">
