### ISSUE TITLE
"Undo" does not work for moving collections

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#28860]
**Describe the bug**
Clicking "undo" after moving a collection does not do anything.

**To Reproduce**
1. Open a collection.
2. Select one or more collections.
3. Click "move" and move them to another collection.
4. Press "undo"
5. Collections will not be moved back to original collection.

**Expected behavior**
After pressing "undo" the collections should be moved back to their original collection.

**Screenshots/videos**

https://user-images.githubusercontent.com/37751258/222532567-5682a55d-e576-444e-b7f7-6266bc66a757.mov

**Information about your Metabase Installation:**
Running dev environment on `master` branch, commit `2d9c6eb9e8`
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.6+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.6+10",
    "os.name": "Mac OS X",
    "os.version": "13.0",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-03-02",
      "src_hash": "d42a0436bfe2cf0145472fcb8bcda68c7808eaa9",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "collection-bulk-actions",
      "hash": "1bfb58f"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**
Minor UX annoyance.

**Comment by EmmadUsmani** [comment]
I've identified the root cause of this bug to be a missing `parent_id` field on collection entities coming from the backend response for the `/api/collection/:collection/items` endpoint. [See my abandoned frontend PR for full details.](https://github.com/metabase/metabase/pull/28910)

I think the best solution would be to add that field to the backend response (rather than trying to graft it on in the FE as I did in my PR).

**Comment by qwef** [comment]
I'm unable to reproduce, does this still happen to you? @EmmadUsmani

**Comment by EmmadUsmani** [comment]
@qwef Nope, looks like it's working fine on stats now
