### ISSUE TITLE
Base docker image causes reporting timezone setting on PG to break

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2887]
If this is a bug report, please fill in the blanks:

*  I am using the _Chrome_ browser.
*  My computer's OS is _Mac OS X_.
*  I'm running Metabase _On Elastic Beanstalk_. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is _Postgres_.
*  My Metabase version is _HEAD_.

The root docker image causes all queries against PG to break if the reporting timezone is set.

Could this be an openJDK 7 problem?

**Comment by camsaul** [comment]
@salsakran This sounds like the issue I fixed in #2984 . Are we still seeing this?

**Comment by salsakran** [comment]
looks fixed to me. closing.
