### ISSUE TITLE
Disabled "Nested Queries" setting is not always respected

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#28908]
**Describe the bug**
Admins can disable nested queries in `Admin > Settings > General`.

That can happen either:
1. on a fresh instance or
2. on an instance that already has a bunch of questions, potentially nested questions and/or models

Having models but being unable to create new questions based on them is kind of pointless, but that's rather design/philosophical problem to solve. We currently don't have a good answer for that situation.

However, models are exposing some parts of UI that prompt users to create nested questions even with this option explicitly disabled. Unfortunately, backend will accept nested questions, and that is a real bug here.

For the reference, a nested question is any question/query with `source-table: card__id`

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. As an admin, go to Admin > Settings > General and disable nested queries
2. If your instance already has saved Models in it, open a model (otherwise, create it)
3. Click on the "More info" icon and then click on "Model details" (`/model/id/detail/usage`)
![image](https://user-images.githubusercontent.com/31325167/222769240-b869462e-03b2-4fc2-9fc5-463252e2ebc4.png)
4. If that model isn't already used by any questions, you will be prompted to create one (which is by definition nested)
![image](https://user-images.githubusercontent.com/31325167/222769320-2ba4c97b-cf2a-4b6b-a319-552ab802b25e.png)
5. Click on "Create new question" and you'll see an error in the dataset that's generated (btw, `POST /api/dataset` returns `202` even though it contains an error)
![image](https://user-images.githubusercontent.com/31325167/222769659-51e61236-384d-4014-b8fe-59757e9f4688.png)

Interesting thing here is that FE/UI doesn't offer to "Save" this new question (which is correct), BUT...
6. Change anything about the query (filter, summarize, limit) and you'll see "Save" all of a sudden (very incorrect)
7. Click on "Save" and you'll be prompted to save **new** question
![image](https://user-images.githubusercontent.com/31325167/222770374-8e97cc6b-59ab-4bc5-b093-07c99a07aa9a.png)
8. Backend happily accepts the query and the question gets saved 😮 
`POST /api/card` responds with `200`

> **Warning**
> 1. It is possible to execute actions on a broken nested model
> 2. It is possible to add saved nested question to a dashboard AND to connect filter to any of its valid fields
>
> In both cases, UI will constantly display an error but all requests will go through!

**Expected behavior**
If nested queries are disabled:
- frontend shouldn't offer to save a new nested question
- backend shouldn't accept nested query 
- models usage page shouldn't offer to "Create a new question"

Everything else is up for the product/design discussion is ultimately their decision:
- Should it be possible to disable nested queries on instances with models/saved questions?
- Should we display a warning if someone attempts to disable nested queries?
    - Should we archive all nested questions if someone proceeds?
- etc.

**Information about your Metabase Installation:**
local dev, `master, 814fa219b1f1964545e75474f3dae38522f97f2f, H2, Sample Database

**Severity**
Because backend accepts nested queries, it seems like a P2.

**Additional context**
I am not exactly sure when did we introduce the option to disable nested queries, but I'd offer an uneducated guess and say it's been a part of Metabase since forever.

**Comment by nemanjaglumac** [comment]
Another way to reproduce this:
1. Disable nested queries
2. Either open an existing model or create and save a new one
3. Click on `...` icon
4. Duplicate model 
![image](https://user-images.githubusercontent.com/31325167/222773590-be575d6e-11ed-4cb1-951e-bd5f4e0e1d12.png)
5. New question gets automatically saved but the UI shows the "dirty" state
![image](https://user-images.githubusercontent.com/31325167/222773835-d12a1569-960a-462d-bfb3-cb56d88afa63.png)
6. Click "play" icon to run the query
7. And we're back to the error displayed in UI
![image](https://user-images.githubusercontent.com/31325167/222774040-235d5d15-f514-4c10-a976-89aef2755fa1.png)

**Comment by ranquild** [comment]
For the backend please take a look at item number 5 where 202 is returned with an error.

**Comment by ranquild** [comment]
The backend changes seem to be related to QP https://github.com/metabase/metabase/issues/28676

**Comment by nemanjaglumac** [comment]
The original issue is still (d35c779976ae6bd79369e9cc6bec8540908f37d2) very much relevant, but [duplicating a model](https://github.com/metabase/metabase/issues/28908#issuecomment-1453783041) doesn't result in a dirty state anymore.

**Comment by kamilmielnik** [comment]
Slack discussion for reference: https://metaboat.slack.com/archives/C01LQQ2UW03/p1699454495848059
