### ISSUE TITLE
Models missing from join in GUI

### ISSUE THREAD

**Issue by JadAbdallah** [metabase/metabase#28904]
**Read this before creating a bug report**
- if any of the sections are incomplete, we might close the bug report since we won't be able to reproduce it
- have you checked if the bug has already been reported? As we close duplicate reports, please search on the issue tracker if the problem has been reported before
- use as many screenshots or videos as possible to describe what you're seeing, all visual representations speak for themselves

**Describe the bug**
I am attempting to join models to each other but models are not appearing in list of models when joining in GUI. Models are created and available but cannot be searched or found when trying to perform join. 

**Logs**
Please include JavaScript console logs (open the browser dev tools and check the "console" tab) as well as the server logs (Metabase logs that you can get from Settings -> Admin -> Troubleshooting -> Logs) around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):

**Expected behavior**
Would expect model to appear as it exists. 

**Screenshots/videos**
Model:
![Screenshot 2023-03-03 at 9 10 12 AM](https://user-images.githubusercontent.com/73364552/222741885-ea8fe884-a1a8-4d45-a59f-db4bf6f0de52.png)

Missing model in join: 
![Screenshot 2023-03-03 at 9 09 38 AM](https://user-images.githubusercontent.com/73364552/222741761-b4be44a6-36fe-4b2c-84bb-bcadb41916ba.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-03",
      "tag": "v0.45.0",
      "branch": "release-x.45.x",
      "hash": "4e41d76"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Blocking usage of Metabase

**Additional context**

**Comment by paoliniluis** [comment]
I'm pretty sure you're seeing https://github.com/metabase/metabase/issues/28105 which is https://github.com/metabase/metabase/issues/24660

**Comment by JadAbdallah** [comment]
Thanks @paoliniluis . Can you confirm those are still open tickets? Can't seem to find an answer in either
