### ISSUE TITLE
Option to disable the Table Name Formating

### ISSUE THREAD

**Issue by cagiraudo** [metabase/metabase#2892]
Hi,

I am having the problem that metabase tries to understand the table names and format them very wrong.
It's very frustrating for tables in other languages, for example i have the table "administradores" wich mean administrators and it is converted to "Admin Is Tr Adores"

It will be awesome that you add a option to turn this feature off becouse it's driving me crazy finding my tables since i can't search them and i have a lot

*  I am using the chrome browser.
*  My computer's OS is ubuntu server 14.04.
*  I'm running Metabase locally from JAR. 
*  My database is MySQL.
*  My Metabase version is 0.18.

**Comment by katylava** [comment]
Same here. We have namespaced fields like `abcd__field_name` and it changes it to "Ab Cd Field Name", which is really annoying when ~80% of the fields have that namespace.

**Comment by tlrobinson** [comment]
Related to #2660

**Comment by camsaul** [comment]
This was implemented in #3024
