### ISSUE TITLE
After two months of operation, the average CPU has reached 700%, just restart

### ISSUE THREAD

**Issue by lindadadada1** [metabase/metabase#28938]
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_65-b17",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_65",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.65-b01",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.53.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "clickhouse",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.32-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.42.0",
      "date": "2022-02-08",
      "branch": "release-x.42.x",
      "hash": "de1264e"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```

**Comment by lindadadada1** [comment]
2023-03-06 15:40:01,373 DEBUG middleware.log :: ESC[32mPOST /api/dashboard/1247/dashcard/11731/card/10303/query 202 [异步: canceled] 5.0 mins（21个数据库调用） 应用数据库连接：1 / 15 码头线程：5 / 50（21空闲
，0排队） （269个活动线程总数） 进行中的查询：50 （68已排队）; clickhouse DB 6 connections: 15/15 (28 threads blocked)ESC[0m
2023-03-06 15:40:01,374 DEBUG middleware.log :: ESC[32mPOST /api/dashboard/1247/dashcard/11724/card/10296/query 202 [异步: canceled] 5.0 mins（23个数据库调用） 应用数据库连接：1 / 15 码头线程：5 / 50（21空闲
，0排队） （269个活动线程总数） 进行中的查询：50 （68已排队）; clickhouse DB 6 connections: 15/15 (30 threads blocked)ESC[0m

**Comment by paoliniluis** [comment]
you're running an extremely old and unsupported metabase version, it's impossible to debug this without having reproduction steps and also with such an old version.

You should upgrade Metabase, clickhouse driver and also post reproduction steps

I'm also sure you have big dashboards which you should trim
