### ISSUE TITLE
How metabase prevents from editing data

### ISSUE THREAD

**Issue by ni-todo-spot** [metabase/metabase#28933]
I've been using metabase for a while now and was wondering how it prevents me from editing the data via sql query I try to execute?

(I'm using postgresql for my project but the question is for any other db metabase supports).

For example - when trying to eecute

```sql
delete from my_table where id = 123
```

I get: `ERROR: cannot execute DELETE in a read-only transaction`

I'm asking since I need to implement something similar in my project and perhaps I can take reference from it

**Comment by paoliniluis** [comment]
Use a read only db user

**Comment by ni-todo-spot** [comment]
Can I do that for other databases such as snowflake, redshift or athena?

**Comment by brunobergher** [comment]
Yes, usually you can configure a read-only connection in the connection string or the DB driver you're using ([example](https://www.ibm.com/support/pages/creating-readonly-jdbc-connection)).
