### ISSUE TITLE
Should Metabase have specific JVM supported versions?

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2893]
There seems to be a bug with Oracle's Java 1.7
http://discourse.metabase.com/t/my-cpu-usage-increases-to-249-and-the-dbug-log-showing-permgen-space-exception/490/7

that goes away when upgrading to 1.8.

Given my current understanding of the licensing situation for the Oracle JVM, it seems wisest to standardize on Open JDK 8, and consider all other java versions "best effort" in terms of support or bug triage. 

Thoughts? @camsaul @michaelshobbs @tlrobinson

**Comment by camsaul** [comment]
If I remember correctly Java < version 1.8 doesn't GC the PermGen by default which would explain the OOM. 1.7 would probably work fine with a few JVM options

**Comment by salsakran** [comment]
Random other bits of info:

My understanding is that Java 8 no longer has a PermGen heap but rather a "Metaspace" that is unbounded by default. So it's possible we were leaking class definitions (or strings, or whatever goes in PermGen space), and with Java 8 it's still happening but takes longer to bring things down. (https://www.infoq.com/news/2013/03/java-8-permgen-metaspace)

Another possibility is that we'd been running with too small a PermGen size and setting a sensible default for Java 7 would make this ok.

**Comment by camsaul** [comment]
We have long since made sure to set PermGen options for Java 7 and documented that in the troubleshooting guide so I'm going to go ahead and close this out
