### ISSUE TITLE
unable to create metrics or segments

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2894]
When attempting to create metrics or segments the data source in the builder is blank and unable to be selected and as a result no segments or metrics can be created.

If this is a bug report, please fill in the blanks:

*  I am using the [all of the] browsers.
*  My computer's OS is OSX.
*  I'm running Metabase on AWS. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is multiple.
*  My Metabase version is 0.18.1.

**Comment by lewisl9029** [comment]
Thanks for filing this @kdoh. This issue is currently blocking progress on the segments/lists sections of the data reference feature. I can mock the data for now but it'd be great if someone could take a look at this.
