### ISSUE TITLE
Basic actions become unusable if clauses are added to the model later

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#28949]
**Describe the bug**
Currently we don't allow to create **basic** actions for "non-raw" models, e.g. models with any clauses defined (joins, filters, aggregations). But it's possible to create basic actions for a model and then change its definition, and afterwards its basic actions start to work weirdly. 

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Make sure actions are enabled for you database. You can do it via Admin -> Databases
2. New -> Model -> Orders -> Save
3. Info panel -> Model details -> Actions -> Create basic actions
4. Edit definition -> Add summary by count, breakout by Created At (month) -> Save
5.  Info panel -> Model details -> Actions -> Try running an action
6. You get a weird form based on the latest stage of the query

**Expected behavior**
As discussed: 
  - Disable basic actions if the updated query include clauses (expression, limit, filter ...)

**Screenshots/videos**
<img width="1324" alt="Screenshot 2023-03-06 at 15 29 13" src="https://user-images.githubusercontent.com/8542534/223126736-f5ffffe4-a571-466c-ba90-14a9b1eee96c.png">
<img width="679" alt="Screenshot 2023-03-06 at 15 29 50" src="https://user-images.githubusercontent.com/8542534/223126755-43524737-a132-41f0-9325-28e98e06ea92.png">

**Information about your Metabase Installation:**
`v0.46.0-RC2`

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Metabase version: (e.g., 0.19.3)
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Comment by joeledwardson** [comment]
This is not clear when you change a model, as suddenly basic actions disappear with no warning. 

I think a popup or warning notifying the user that basic actions will be removed when they edit would be useful
