### ISSUE TITLE
Tests failing on Redshift due to maximum tables limit exceeded

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#28941]
We currently create tables on redshift to test without deleting them and it can reach a limit of maximum tables.

> Detail: Maximum tables limit exceeded. The maximum number of tables per cluster is 9900 for this instance type. The limit includes permanent and temporary tables

Failed run: https://github.com/metabase/metabase/actions/runs/4340992162/jobs/7580085026#logs

**Comment by qnkhuat** [comment]
While we're on this, we should also fix [Tests failing on Redshift due to Out of Memory errors](https://github.com/metabase/metabase/issues/18834) if we can.

**Comment by calherries** [comment]
@qnkhuat Is this still happening?

**Comment by qnkhuat** [comment]
looks like it was fixed by https://github.com/metabase/metabase/pull/29613
