### ISSUE TITLE
Change default string behavior for filter operators to contains

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#28954]
## What
When I'm using filter operators for string columns, the current default operator is "Is" which requires another click out of the user in the common case where they want to specify multiple values.

## Expected Behavior
Let's change the default filter operator for strings to "Contains" instead. Bonus points if we can do this only when there are 10+ distinct values in the column.

[Slack context](https://metaboat.slack.com/archives/C01MS7DQKR6/p1677765300623519).

**Comment by paoliniluis** [comment]
Is this the same as https://github.com/metabase/metabase/issues/11369?

**Comment by cdeweyx** [comment]
Yeah, I'll close as dupe
