### ISSUE TITLE
Basic actions don't take metadata overrides into account

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#28988]
**Describe the bug**
When a basic action is created for a model, the action form doesn't use custom names or types for model fields.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create a model based on a table in the sample database (e.g. Orders)
2. Edit metadata -> Change the name of a column (e.g. Quantity)
3. Create basic actions for this model and try to run the action from the model detail page
4. See the field labels are not affected by the metadata change

**Expected behavior**
Basic actions field names should match what's in the model metadata. But it's not clear whether we should use overridden custom column types.

**Screenshots/videos**
<img width="1728" alt="Screenshot 2023-03-07 at 16 15 34" src="https://user-images.githubusercontent.com/8542534/223461770-417ac66b-cbfa-4ceb-8120-054a8f675635.png">
<img width="1239" alt="Screenshot 2023-03-07 at 16 16 18" src="https://user-images.githubusercontent.com/8542534/223461804-f7038ca9-630d-4e3f-8ef8-a7b4f08aa887.png">

**Information about your Metabase Installation:**

46 RC2

**Comment by cdeweyx** [comment]
Scope from Slack discussion:
- [ ] `field_ID`
- [ ] `base_type`
- [ ] `semantic_type`
- [ ] `effective_type`

**Comment by dpsutton** [comment]
Can you explain more about changing the column type? The only way to do this is to use the coercions (like interpreting a number as epoch milliseconds or a string as a date). In these cases we actually want to use the string base type and not the date effective type. Some validation would be good but otherwise we don't want to use the effective type. What other scenarios are you considering for a "custom type"?

**Comment by dpsutton** [comment]
And I'm not seeing how `semantic_type` affects any of this in any way. Semantic type is a way to add a semantic meaning to a datatype, not change it. Examples are indicating that a datetime is a "creation" datetime, or a number is a quantity or a cost. In no scenarios can a semantic_type affect the type of a column.

**Comment by calherries** [comment]
Yeah, I'd like some concrete examples of how this data is going to be used on the FE before we add this metadata to the implicit action parameters. 

One `semantic_type` I thought that might be useful is `type/Category`, if we want to add a dropdown to the action form.

**Comment by calherries** [comment]
@ranquild @cdeweyx https://github.com/metabase/metabase/pull/30356 makes actions use the "display name" metadata. Using the rest of the metadata seems less like a bug and more of a feature. Should we close this issue and create separate issues for features that use other metadata?

**Comment by cdeweyx** [comment]
@calherries I agree with that assessment, seems smart
