### ISSUE TITLE
Allow n x 1 Table Card

### ISSUE THREAD

**Issue by e-gaulue** [metabase/metabase#29026]
**Is your feature request related to a problem? Please describe.**
Should we say a problem? We are a lot requesting for more freedom on the way to deal with cards. So I could linked it to: #8475, #7516, #5662, #20612

**Describe the solution you'd like**
To be able to show a table on one line (especially when they return one row). If too small the designer will always be able to enlarge it. The easier solution would just be to allow it (see discussion below).

**Describe alternatives you've considered**
Showing table result in column instead of line (like "details"), but it's not possible yet. In the same idea, building a text card based on a question result limit to one row, but not possible yet too.

**How important is this feature to you?**
Well nobody will die if not present. It would just help. And this one look easily doable (see discussion below).

**Additional context**
Presently, regarding "Table":
- If I change the size of the card (or the size of the navigator) => the font size in the table stays the same
- If I set the width to be smaller than what is needed => I get an horizontal scrollbar
- If I set the width to be bigger than what is needed => I get empty space on the right
- If I set the height to 3 (the minimum) => I get few lines and a tool to navigate through the records at the bottom of the card
- If I set the height to be bigger than what is needed => I get empty space at the bottom of the card

If I fake the page and request the div that contains the table to be 1/3 of the size requested in the div.DashCard (I test it with a 912x545 screen), it works (height is then around 50px). Of course the result is to small (I just get the tittle and the pagination tool), but I can enlarge it to 2 rows if I want.

In the real life, I know my users won't use 912x545 screens (https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide) and I can remove the title if needed to gain space. Well that's the dashboard designer decision.

<img width="1238" alt="Capture d’écran 2023-03-08 à 15 55 58" src="https://user-images.githubusercontent.com/4291874/223750949-da419f48-17f8-4990-97ce-b9d4ba421532.png">

**Comment by paoliniluis** [comment]
what you're asking is that we wrap always the table so scrollbars aren't shown?

**Comment by e-gaulue** [comment]
No, no trouble with scrollbars.

What I request is to be able to draw a table card which is one row grid height, even if I can't see column names or data. I mean, if it's the case, the dashboard designer should be clever enough to make it two rows grid height or more. It's a good idea to give it a default value of 3 rows grid height at the beginning, but I don't understand why you don't let the user minimize it to one row. If the dashboard designer knows there will be only one row in the resultset because of a "LIMIT 1" in the question, 3 rows grid height is quite two much (that the example shown in the above image).

The horizontal scrollbar works like a charm according to me. A vertical scrollbar doesn't seem to be the good way to go. When you play with the div.DashCard height, you understand everything is calculated depending on this height. So keep it as is should be good. Just allow the card to be reduce to n X 1 and leave the dashboard designer decide what is the best height for him.

**Comment by paoliniluis** [comment]
We will allow 1x1 cards soon, will that suffice?

**Comment by e-gaulue** [comment]
Here is a trick in the meanwhile (I wouldn't say a workaround): you can change size_y in the `report_dashboardcard` table of the `metabase` database.

**Comment by e-gaulue** [comment]
@paoliniluis yes that's it!
