### ISSUE TITLE
Switching between bar and area visualization once stacking does nothing

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#29030]
**Describe the bug**
In a bar or area visualization, once stacking is enabled in the "display" tab of the left-hand sidebar, switching between the bar and area visualizations in the visualization menu does nothing. The only way to to switch is through the setting in the "display" tab.

**Logs**
No JS console logs and no BE requests sent.

**To Reproduce**
1. Create a bar chart visualization. A simple question from the sample database to do this from is "Count by Category and Created At: Month".
2. Gear icon -> display -> Stacking -> Stack (or Stack - 100%).
3. Visualization -> Area. Switching between bar and area now does nothing.

**Expected behavior**
Clicking on area and bar in the visualization menu should change the visualization.

**Screenshots/videos**

https://user-images.githubusercontent.com/37751258/223756430-57e259fe-6626-4ae6-8ca2-ebef61ebcc35.mov

**Information about your Metabase Installation:**
Locally running `master` branch commit `d75966f206`

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.6+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.6+10",
    "os.name": "Mac OS X",
    "os.version": "13.0",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-03-06",
      "src_hash": "6ddc8e7aad21d588610529a3f7a3cb8ef0c6e0f7",
      "tag": "v0.46.0-SNAPSHOT",
      "branch": "master",
      "hash": "fa405e0"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Minor annoyance, doesn't prevent any functionality and has an easy workaround.

**Comment by paoliniluis** [comment]
I would say it's a P2 since it seems that you have to re-do the entire chart for this to work

**Comment by EmmadUsmani** [comment]
> I would say it's a P2 since it seems that you have to re-do the entire chart for this to work

I don't think you need to re-do the whole chart. You can still switch between area and bar, but through the `Stacked chart type` setting in the `Display` tab.


https://user-images.githubusercontent.com/37751258/223767069-5916a189-1852-4d21-a9a7-c9daccd2e943.mov
