### ISSUE TITLE
[SerDes] Changing the name of a dashboard will create a new one instead of making the update

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29041]
**Describe the bug**
If you change the name of a dashboard in the deserialized yamls, the process will create a new one when the dashboard is loaded instead of replacing the name of it

**Logs**
None

**To Reproduce**
1) create a dashboard
2) dump and load
3) now change the name in the dashboard.yaml (the key "name", not the file name)
4) load again in destination.

Metabase has created a new dashboard instead of replacing the old one

**Expected behavior**
Objects in Metabase shouldn't be handled by the name, but rather through immutable keys

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.45.3

**Severity**
P1

**Additional context**
NA

**Comment by john-metabase** [comment]
Isn't this is a known limitation of serdes v1? Ignoring this issue and rewriting v2 with `entity_id` was the solution. Backporting it to v1 would be a significant change and make v2 a bit redundant.

ping @luizarakaki

**Comment by luizarakaki** [comment]
Yes, this is a Serdes v1 limitation and is fixed on v2.
