### ISSUE TITLE
Major version update: org.mariadb.jdbc/mariadb-java-client 2.7.6 -> 3.1.2

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#29064]

**Comment by paoliniluis** [comment]
Does this upgrade still supports MySQL?

**Comment by markbastian** [comment]
The latest driver appears to [only support the `jdbc:mariadb` protocol](https://mariadb.com/kb/en/about-mariadb-connector-j/#using-drivermanager), so this may not be worth it ATM.
