### ISSUE TITLE
Getting set up steps don't route

### ISSUE THREAD

**Issue by puhrez** [metabase/metabase#2906]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac OS X Yosemite.
*  I'm running Metabase via `lein ring server`. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is Postgres.
*  My Metabase version is 19.0-snapshot.

Getting set up "Next steps"  `email` and `slack` don't seem to route correctly until I click another step and then hit "back"

![screen shot 2016-07-06 at 6 27 49 pm](https://cloud.githubusercontent.com/assets/6732397/16636658/7e9d4a8a-43a7-11e6-8090-a55a81ebf872.png)

**Comment by tlrobinson** [comment]
This should be fixed by #2902
