### ISSUE TITLE
Can't save question if I started a question from a saved question

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29083]
**Describe the bug**
If you start a question from the display of a saved question, you can't save the later when changing the filters

**Logs**
NA

**To Reproduce**
1) Go to orders, save as a question
2) now change a filter, you should get the save button, as you changed the filter
3) there's no save button anywhere

**Expected behavior**
If I change the filters and I have permissions on any collection, I should be able to save the question

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave
- Metabase version: master

**Severity**
P1

**Additional context**
NA

**Comment by alxnddr** [comment]
@paoliniluis can you please share more details about the repro steps? I tried it on the latest master and it worked for me:

<video src="https://user-images.githubusercontent.com/14301985/224434960-caf3f29a-03a9-4521-aaf9-48d78d46abd6.mov" />

**Comment by paoliniluis** [comment]
Seems it's no longer there, we hit this issue together with @cbalusek on Thursday
