### ISSUE TITLE
Notebook filter field allows non boolean custom expressions

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#29094]
**Describe the bug**
Notebook filter field allows non boolean custom expressions

**To Reproduce**

1. Start a new question based on Orders table
2. Add a filter with Custom Expression `[Tax] * 22`
3. Click "Done"

**Expected behavior**
Non-boolean expression is not allowed

**Comment by kamilmielnik** [comment]
Can reproduce in 0.48.0.
Can partially reproduce in 0.49.0-RC1 (invalid filter is not added).
Can't reproduce in `master` at bfceeebf16 (error is shown when adding the filter).
