### ISSUE TITLE
Error in upgrading Metabase v0.46.0-RC2

### ISSUE THREAD

**Issue by Mrshanyan** [metabase/metabase#29109]
The following error occurred during the [metabase.jar ](https://downloads.metabase.com/v0.46.0-RC2/metabase.jar) package upgrade：
url:https://downloads.metabase.com/v0.46.0-RC2/metabase.jar

**Logs**

2023-03-10 09:46:18,071 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2023-03-10 09:46:18,074 INFO db.setup :: [36mVerifying h2 Database Connection ...[0m
2023-03-10 09:46:18,102 INFO db.update-h2 :: H2 v1 database detected, updating...
2023-03-10 09:46:18,103 INFO db.update-h2 :: Downloading https://repo1.maven.org/maven2/com/h2database/h2/1.4.197/h2-1.4.197.jar
2023-03-10 09:46:18,249 ERROR db.update-h2 :: Failed to update H2 database: #error {
 :cause repo1.maven.org: 域名解析暂时失败
 :via
 [{:type java.net.UnknownHostException
   :message repo1.maven.org: 域名解析暂时失败
   :at [java.net.Inet4AddressImpl lookupAllHostAddr Inet4AddressImpl.java -2]}]
 :trace
 [[java.net.Inet4AddressImpl lookupAllHostAddr Inet4AddressImpl.java -2]
  [java.net.InetAddress$PlatformNameService lookupAllHostAddr InetAddress.java 933]
  [java.net.InetAddress getAddressesFromNameService InetAddress.java 1519]
  [java.net.InetAddress$NameServiceAddresses get InetAddress.java 852]
  [java.net.InetAddress getAllByName0 InetAddress.java 1509]
  [java.net.InetAddress getAllByName InetAddress.java 1367]
  [java.net.InetAddress getAllByName InetAddress.java 1301]
  [org.apache.http.impl.conn.SystemDefaultDnsResolver resolve SystemDefaultDnsResolver.java 45]
  [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator connect DefaultHttpClientConnectionOperator.java 112]
  [org.apache.http.impl.conn.BasicHttpClientConnectionManager connect BasicHttpClientConnectionManager.java 313]
  [org.apache.http.impl.execchain.MainClientExec establishRoute MainClientExec.java 393]
  [org.apache.http.impl.execchain.MainClientExec execute MainClientExec.java 236]
  [org.apache.http.impl.execchain.ProtocolExec execute ProtocolExec.java 186]
  [org.apache.http.impl.execchain.RetryExec execute RetryExec.java 89]
  [org.apache.http.impl.execchain.RedirectExec execute RedirectExec.java 110]
  [org.apache.http.impl.client.InternalHttpClient doExecute InternalHttpClient.java 185]
  [org.apache.http.impl.client.CloseableHttpClient execute CloseableHttpClient.java 83]
  [clj_http.core$request invokeStatic core.clj 621]
  [clj_http.core$request invoke core.clj 546]
  [clj_http.core$request invokeStatic core.clj 547]
  [clj_http.core$request invoke core.clj 546]
  [clojure.lang.Var invoke Var.java 384]
  [clj_http.client$wrap_request_timing$fn__17492 invoke client.clj 1083]
  [clj_http.headers$wrap_header_map$fn__16586 invoke headers.clj 152]
  [clj_http.client$wrap_query_params$fn__17382 invoke client.clj 817]
  [clj_http.client$wrap_basic_auth$fn__17388 invoke client.clj 840]
  [clj_http.client$wrap_oauth$fn__17393 invoke client.clj 857]
  [clj_http.client$wrap_user_info$fn__17402 invoke client.clj 877]
  [clj_http.client$wrap_url$fn__17474 invoke client.clj 1035]
  [clj_http.client$wrap_decompression$fn__17169 invoke client.clj 416]
  [clj_http.client$wrap_input_coercion$fn__17294 invoke client.clj 630]
  [clj_http.client$wrap_additional_header_parsing$fn__17319 invoke client.clj 685]
  [clj_http.client$wrap_output_coercion$fn__17281 invoke client.clj 574]
  [clj_http.client$wrap_exceptions$fn__17122 invoke client.clj 250]
  [clj_http.client$wrap_accept$fn__17334 invoke client.clj 728]
  [clj_http.client$wrap_accept_encoding$fn__17341 invoke client.clj 750]
  [clj_http.client$wrap_content_type$fn__17328 invoke client.clj 711]
  [clj_http.client$wrap_form_params$fn__17439 invoke client.clj 959]
  [clj_http.client$wrap_nested_params$fn__17460 invoke client.clj 993]
  [clj_http.client$wrap_flatten_nested_params$fn__17469 invoke client.clj 1017]
  [clj_http.client$wrap_method$fn__17407 invoke client.clj 893]
  [clj_http.cookies$wrap_cookies$fn__16498 invoke cookies.clj 128]
  [clj_http.links$wrap_links$fn__16926 invoke links.clj 63]
  [clj_http.client$wrap_unknown_host$fn__17477 invoke client.clj 1046]
  [clj_http.client$request_STAR_ invokeStatic client.clj 1174]
  [clj_http.client$request_STAR_ invoke client.clj 1167]
  [clj_http.client$get invokeStatic client.clj 1180]
  [clj_http.client$get doInvoke client.clj 1176]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [metabase.db.update_h2$update_BANG_ invokeStatic update_h2.clj 73]
  [metabase.db.update_h2$update_BANG_ invoke update_h2.clj 68]
  [metabase.db.update_h2$update_if_needed invokeStatic update_h2.clj 98]
  [metabase.db.update_h2$update_if_needed invoke update_h2.clj 90]
  [metabase.db.data_source.DataSource getConnection data_source.clj 29]
  [com.mchange.v2.c3p0.WrapperConnectionPoolDataSource getPooledConnection WrapperConnectionPoolDataSource.java 161]
  [com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager acquireResource C3P0PooledConnectionPool.java 213]
  [com.mchange.v2.resourcepool.BasicResourcePool doAcquire BasicResourcePool.java 1176]
  [com.mchange.v2.resourcepool.BasicResourcePool doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess BasicResourcePool.java 1163]
  [com.mchange.v2.resourcepool.BasicResourcePool access$700 BasicResourcePool.java 44]
  [com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask run BasicResourcePool.java 1908]
  [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread run ThreadPoolAsynchronousRunner.java 696]]}

**Comment by paoliniluis** [comment]
Seems like Metabase couldn’t connect to the internet to download some dependencies

**Comment by Mrshanyan** [comment]
> Seems like Metabase couldn’t connect to the internet to download some dependencies

If I need to update offline, please tell me how to do it？

**Comment by paoliniluis** [comment]
Do the following:
1) connect Metabase to a Postgres DB
2) then upgrade

**Comment by john-metabase** [comment]
@Mrshanyan assuming you have access to both the old and new metabase JAR files, you could do this offline using the following example script. You will need to fill in `oldMetabase` and possibly `newMetabase` with the appropriate paths, or use this as an example and execute the commands manually. You should back up your current `.mv.db` file before attempting to upgrade.

This script assumes that `metabase.db.mv.db` is in the current directory.

```bash
oldMetabase=...
newMetabase=metabase.jar

java -cp $oldMetabase org.h2.tools.Script -url jdbc:h2:./metabase.db -script /tmp/metabase-migration.sql
mv metabase.db.mv.db metabase.db.v1-backup
java -cp $newMetabase org.h2.tools.RunScript -script /tmp/metabase-migration.sql -url jdbc:h2:./metabase.db -options FROM_1X
```
