### ISSUE TITLE
Re-ordering of columns in Table visualization broken in 0.45.3

### ISSUE THREAD

**Issue by wallin** [metabase/metabase#29115]
**Describe the bug**
This is a regression from the previous version, 0.43.6, I was using. When trying to re-order columns in a Table visualization, this doesn't work. See attached GIF

**Logs**
Dragging the column items doesn't produce any errors in the dev console

**To Reproduce**
1. Create a SQL query with a few columns in the SELECT statement
2. Pick the table visualization
3. Go to settings → columns and try to re-order the columns by dragging
4. Once the column item is released, it snaps back to the first position 

**Expected behavior**
When dragging the columns, they are expected to change order, and not snap back to where they were.

**Screenshots/videos**
![2023-03-10 09 43 17](https://user-images.githubusercontent.com/268917/224268866-733aaf8f-3cbe-4a7b-87f0-9998a1390bf1.gif)

**Information about your Metabase Installation:**

<details><summary>JSON</summary>

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.0-1088-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```
</details>

**Severity**
Annoying

**Comment by paoliniluis** [comment]
We should have fixed this in version 46
