### ISSUE TITLE
Cannot deactivate Models Caching

### ISSUE THREAD

**Issue by pablomatchspace** [metabase/metabase#29116]
**Describe the bug**
I activated Models Caching. Now I click to deactivate, refresh page, but nothing happens. Models Caching still appears activated.
Additionally, when clicking on Tools, it appears empty, only see URL: https://matchspace.metabaseapp.com/admin/tools/model-caching

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to ['...'](https://matchspace.metabaseapp.com/admin/settings/caching)
2. Click to deactivate Models Caching

**Screenshots**

![image](https://user-images.githubusercontent.com/101109337/224290137-fa9b7f71-25d4-4628-985c-0699e0da476d.png)
![image](https://user-images.githubusercontent.com/101109337/224290182-9895b0b8-00c8-46e4-8c30-5bb0487362f4.png)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-18",
      "tag": "v1.45.2.1",
      "branch": "release-x.45.2.x",
      "hash": "3f73d30"
    },
    "settings": {
      "report-timezone": "Europe/Zurich"
    }
  }
}
```

**Comment by paoliniluis** [comment]
Please write to the support email, you have included support in your plan
