### ISSUE TITLE
Postgres Custom Query Actions require explicit CAST() for date fields

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#29126]
**Describe the bug**

This is half way between a bug and a feature request, but when you make a custom action on a postgres DB, you have to explicitly CAST your timestamp fields in your query to timestamp: e.g.

```sql
INSERT INTO invoices( 
  id ,account_id ,payment ,plan ,date_received
) VALUES ( 
  {{ id }}, 
  {{ account_id }},
  {{ payment }},
  {{ plan }},
  CAST ({{date_received }} AS timestamp)
);
```

The frontend sends a datetime string to the backend, MySQL has no problem casting this to a timestamp for timestamp fields, but Postgres throws an error if you don't cast the value.

![image (2)](https://user-images.githubusercontent.com/30528226/224356182-f9522e07-a595-4c9e-9337-d0e4efdfdc3b.png)

At some level, we need to detect the combination of datetime + postgres and explicitly cast it. Ideally this is at the driver level, but that might require some restructuring of how we designate field types.

**To Reproduce**
1. create a custom INSERT query action on a model with a postgres table behind it and a timestamp column
2. try to populate the datetime field in the custom action
3. see an error

**Severity**

Annoying and causes poor UX, but has a workaround.

**Comment by tsmacdonald** [comment]
I think we're not in the business of modifying raw SQL directly, so our hands are a little tied here. Any user writing raw SQL should be ~aware of this.

Only possible workaround I can think of is if we formatted the timestamp to be something Postgres can parse without casting, like so:

```
> \d hello_ryan
                                              Table "public.hello_ryan"
        Column         |            Type             | Collation | Nullable |                Default                 
-----------------------+-----------------------------+-----------+----------+----------------------------------------
 id                    | integer                     |           | not null | nextval('hello_ryan_id_seq'::regclass)
 name                  | character varying(255)      |           |          | 
 mario_kart_wins       | integer                     |           |          | 
 avg_margin_of_victory | numeric                     |           |          | 
 created_at            | timestamp without time zone |           | not null | now()
 date_received         | timestamp without time zone |           |          | 

> insert into hello_ryan (name, date_received) values ('foo', '2023-03-27 11:21:00');
INSERT 0 1

> select * from hello_ryan where name = 'foo';
 id | name | mario_kart_wins | avg_margin_of_victory |         created_at         |    date_received    
----+------+-----------------+-----------------------+----------------------------+---------------------
  6 | foo  |                 |                       | 2023-08-15 12:37:07.540513 | 2023-03-27 11:21:00
```

but I don't know if that would have unintended consequences with the rest of the QP. CCing @luizarakaki for input / possible take-over by the QPD team.

**Comment by calherries** [comment]
This is happening because the type of the template tags in the `dataset_query` have type "text", even when they're set in the UI to "Date".

It's because there are two places where data about parameters are stored. The query processor uses the template tags under the `dataset_query` key, but the action editor displays the type from the `parameters` key.

If you create action with a variable of type "Date" in the UI the parameters in the POST request to save it will have `type="Date"` under `parameters`

![image](https://github.com/metabase/metabase/assets/39073188/9c70c94b-e28f-46be-a2d2-89204d1e20c2)

but type="text" under `dataset_query`'s `template_tags`:

![image](https://github.com/metabase/metabase/assets/39073188/ab91f9f4-1027-4025-a312-d8dbbb4dee82)
