### ISSUE TITLE
Serialization doesn't take into account viz settings from custom columns

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29134]
**Describe the bug**
If you add a custom column to a question and then use a viz setting on that custom column (e.g. adding semaphores to a case statement and display these semaphores as images), the dump won't take this viz setting into account

**Logs**
NA

**To Reproduce**
1) add a question
2) add a custom column that does a case with images, and then display these links as images
3) dump and load

you'll see the links in the load, not the images

**Expected behavior**
Viz settings need to be respected

**Screenshots/videos**
Origin
![image](https://user-images.githubusercontent.com/1711649/224381501-9acf0491-060f-4d5c-989b-73e97e0b9a50.png)

Destination
![image](https://user-images.githubusercontent.com/1711649/224381544-d5f56dc7-4b18-4427-bd05-2672e9fc5dde.png)

**Information about your Metabase Installation:**
- Metabase version: 1.45.3

**Severity**
P3

**Additional context**
NA

**Comment by luizarakaki** [comment]
@paoliniluis which image URL do you use? Anything that I try here becomes this 
![image](https://user-images.githubusercontent.com/32561114/234111802-5fc3f51a-2424-449f-83dc-bdd92dea1b00.png)

**Comment by paoliniluis** [comment]
@luizarakaki check ticket https://metabase.zendesk.com/agent/tickets/16037
