### ISSUE TITLE
Support for Google Identity Services library

### ISSUE THREAD

**Issue by dlucasintouch** [metabase/metabase#29136]
**Is your feature request related to a problem? Please describe.**
Yes. We are running an older version of metabase (v0.29.1) and use the "Sign in with Google" feature.  We were notified by google that the **Google Sign-In JavaScript** platform library will be deprecated after **March 31, 2023**

**Describe the solution you'd like**
Update metabase, and its documentation, to migrate to [Google Identity Services](https://developers.googleblog.com/2021/07/launching-our-new-google-identity-services-apis.html). Google have a [migration guide](https://developers.google.com/identity/gsi/web/guides/migration) on the subject.

**Describe alternatives you've considered**
N/A

**How important is this feature to you?**
Most our users login via this functionality.  It is of primary importance.

**Additional context**
N/A

**Comment by paoliniluis** [comment]
We fixed this very recently, we’re not going to backport this to old Metabase version
