### ISSUE TITLE
Points with the same X value are being added together in the line graph

### ISSUE THREAD

**Issue by jobevers** [metabase/metabase#2913]
Line chart:

![screen shot 2016-07-07 at 11 34 11 am](https://cloud.githubusercontent.com/assets/2380127/16661094/ea974436-4436-11e6-8835-7ed25f952943.png)

Table:

![screen shot 2016-07-07 at 11 36 04 am](https://cloud.githubusercontent.com/assets/2380127/16661126/16b3d4d0-4437-11e6-9861-267b6a4b9e47.png)

The rise in the line chart shouldn't be there.
-  I am using the Chrome browser.
-  My computer's OS is macOS.
-  I'm running Metabase AWS. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is postgres.
-  My Metabase version is 0.18.1.

**Comment by tlrobinson** [comment]
For linear or timeseries x-axis line charts I think it makes sense to just plot every data point. I'm not sure how we should handle ordinal x-axis or bar charts though.

Related to #2708

**Comment by tlrobinson** [comment]
@salsakran How do you propose handling this? We've been doing an implicit sum aggregation of duplicate X values since forever, and there are likely people relying on that behavior, whether or not they should be (e.x. #2708).

**Comment by salsakran** [comment]
I'm not sure we know enough to get this right.

The main issue I have is that there are two scenarios
1. The value at that point in time is a measurement, eg think a temperature sensor that spits out a time, temperature pair. If a measurement doubles up, we shouldn't add them. Valid options would be using the first value, using last value, averaging the values.
2. The value at that point in time is an aggregation or a counter, something lopped off too much of the timestamp. Eg, we have an event counter, and we get two counters for a given time slot. The correct thing to do here is what we're doing (add them). 
2a. Arguably if we have an aggregation by time, multiple values for a given slot should be considered an error. 

@jobevers in your specific example, what would you consider the "correct" outcome?

**Comment by tlrobinson** [comment]
@salsakran Did we come to any conclusions on changes to make here?

**Comment by salsakran** [comment]
Not really. There are three possibilities:
1. sum them
2. avg them
3. only use the last one.

Is this something that dc.js gives us any control over, or is it something that will need to be done in the code that generates the series?

**Comment by tlrobinson** [comment]
I think we could just change the crossfilter reducer (though average might be tricky, can't really compute that in a reducer, can you?)

**Comment by tlrobinson** [comment]
@jobevers Are there cases where you can't use an aggregation in the query to resolve this? Assuming we added sufficiently granular time groupings like minute, second, etc, e.x. #2680

**Comment by jobevers** [comment]
The ability to choose the aggregation, instead of being stuck on only sum, would be a solution.  In this case, I'd average over values in a minute.

**Comment by tlrobinson** [comment]
@jobevers So to be clear, if we added the "minute" granularity, you could do what you want with our existing query builder, and this issue could be closed?

**Comment by tlrobinson** [comment]
The client-side summing behavior that's resulting in this is not really the intended way to use Metabase. We definitely expect you to aggregate using the query builder, a SQL query, or a pre-aggregated table/view, so we'd like to make sure that's possible for as many use-cases as possible.

I'm trying to figure out if there are cases where it's not possible / desirable to aggregate in the query. If so then we should think more about what the right behavior is, and perhaps if we should provide control over the behavior.

**Comment by tlrobinson** [comment]
I think we can close this issue. Awhile ago we added a warning when this occurs:
![screen shot 2018-03-09 at 3 02 29 pm](https://user-images.githubusercontent.com/18193/37229820-edf468fc-23aa-11e8-96b6-2f6cf939f031.png)

**Comment by jornh** [comment]
I have a few times experienced the ⚠️ sign shown above. Mostly in initial phases of exploring the shape of a dataset new to me. It was first after reading through the reasoning in this issue and in particular:

> The client-side summing behavior that's resulting in this is not really the intended way to use Metabase. We definitely expect you to aggregate using the query builder, a SQL query, or a pre-aggregated table/view.

... that it became super-obvious to me what the (very reasonable) expectation to the user is. 

**Suggestion**: Some way to *even more* clearly educate the user in what they should do (and maybe even why it’s not taken care of by zen but is upon them) 

![compsaysno](https://media1.tenor.com/images/9c8ecfc4ea245379ba2c41efe7eab92f/tenor.gif?itemid=4987618)


@mazameli I was reading through the user guide from the top to see if this was already pointed out there, it wasn’t, and now I also think that it shouldn’t, as it would then read as something very dull. The explanation should probably just be in the Metabase UI.

Sidenode: I *did* enjoy reading through the very “teaching style” initial section on database tables, data types etc. though (something I until now always skipped).
