### ISSUE TITLE
[License]: Is it possible to provide metabase as bi facility to users in my sql data lakehouse cloud service?

### ISSUE THREAD

**Issue by cloudcheflabs** [metabase/metabase#29153]
I am going to launch a SQL Data Lakehouse Cloud Service based on trino.
As BI facility, we provide metabase to users to query and explor data in my sql data lakehouse cloud service.
Metabase will be deployed on kubernetes with helm chart. The jar file of metabase from https://downloads.metabase.com/v0.44.3/metabase.jar is used currently which is packaged as docker image. No code modification of Metabase is done.
Is there any license problem to provide Metabase just as bi facility to customers in my sql data lakehouse cloud service?

**Comment by paoliniluis** [comment]
First of all, use the latest metabase version. Second, AGPL allows you to use Metabase in your service but you can't make any modifications.

**Comment by cloudcheflabs** [comment]
Thank you for your clarification, Luis.

2023년 3월 12일 (일) 오전 10:30, Luis Paolini ***@***.***>님이 작성:
