### ISSUE TITLE
Unable to Reference a Saved Model/Question in Another Native Query

### ISSUE THREAD

**Issue by ngapuileung** [metabase/metabase#29158]
**Describe the bug**
When I create a saved question/model under my personal collection, I am unable to reference it in another native query. I need to create a **duplicate** of the question/model in order to reference it.

**Logs**
n/a

**To Reproduce**
1. Create and save a question within your personal collection.
2. Reference the saved question in a native query with the code snippet "select * from {{#<question_number_and_name>}} q".
3. See an error message saying: "ERROR: syntax error at end of input Position: X".
4. This error does not occur when I reference a copy of the saved question.

**Expected behavior**
Ability to reference a saved question/model as stated in the "[Referencing models and saved questions](https://www.metabase.com/docs/latest/questions/native-editor/referencing-saved-questions-in-queries#referencing-models-and-saved-questions)" documentation page.

**Screenshots/videos**
![Screenshot 2023-03-13 at 5 34 44 PM (2)](https://user-images.githubusercontent.com/10627150/224663079-fa0e2131-810d-4667-b1b6-a6af25ecddd2.png)
![Screenshot 2023-03-13 at 5 35 32 PM (2)](https://user-images.githubusercontent.com/10627150/224663088-efcd55b1-c746-4e0f-b05b-35793fc330a1.png)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
This issue creates a very negative user experience because every time I update the original question/model, I need to recreate another duplicate of the question/model to reflect the changes and then update all of the questions downstream that was referencing the old duplicate to reference the new one.

**Additional context**
n/a

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/25988 Coming back again? Looping @metamben

**Comment by metamben** [comment]
This doesn't seem to be related to #25988. Considering the error message, I can imagine that the behavior depends on the  DW being queried. I could run such a query on stats (and a query with `Analytics Data Warehouse > dbt_models_stripe > Stripe Customer` worked too):

![image](https://user-images.githubusercontent.com/103100869/225116198-e9e3027c-90e0-425e-b65a-7357fe79a604.png)

@paoliniluis @ngapuileung I need more detailed instructions to reproduce.

**Comment by qnkhuat** [comment]
I checked with @ngapuileung and the root cause is that the source query has a trailing comment, It's a different bug for which I created an issue [here](https://github.com/metabase/metabase/issues/29158).
