### ISSUE TITLE
Allow Field Filters to Map to Transformed Fields in Saved Questions/Models

### ISSUE THREAD

**Issue by ngapuileung** [metabase/metabase#29152]
When I build a dashboard that is based on a saved question or model, I need to create Field Filters in order to filter the results based on multiple values. However, the current Field Filter feature requires me to map the variable to a field in a table in the database.

If users can map the variable to a **transformed** field in their saved models/questions that the dashboard is referencing rather than the original field in the raw data, it would make the Field Filter feature more powerful and convenient.

_An example of a field transformation is aggregating values into broader categories or breaking down existing values into more granular categories._

**Comment by paoliniluis** [comment]
Yup! I think that what you need is https://github.com/metabase/metabase/issues/25337, let me know if that's the case so we can close this one

**Comment by ngapuileung** [comment]
Yes, I think that would fix/address this. Thanks!
