### ISSUE TITLE
Nested query with comment at the end fails to execute

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#29168]
**Describe the bug**
A nested query with the source query contains a comment at the end will fail.

**Logs**
> Syntax error in SQL statement "-- Metabase:: userID: 3 queryType: native queryHash: a8ac92961789109a2b80fa3e7091477bd71118a2d8a1ba04a1f38c506d137e8c\000aselect * from (select * from orders[*];\000a-- a)"; expected "., TABLE (, (, USE, AS, RIGHT, LEFT, INNER, JOIN, CROSS, NATURAL, ,, WHERE, GROUP BY, HAVING, WINDOW, QUALIFY, INTERSECT, UNION, EXCEPT, MINUS, ORDER BY, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement: select * from (select * from orders; -- a) [42001-214]

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. New Native query : 
  ```
select * from orders;
-- a comment
```
2. Save it as Q1
3. New native query ```select * from {{#id-Q1}}```
4. The query will be failed to execute

**Expected behavior**

The query should ignore the comment and execute successfully

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Information about your Metabase Installation:**
current master(06599e646c3e03462402474b5fc17cd2bf25cb79)

**Severity**
Data people ran into this problem quite often

**Additional context**
Exception data

```clojure
{:driver :h2,
    :sql
    ["-- Metabase:: userID: 3 queryType: native queryHash: a8ac92961789109a2b80fa3e7091477bd71118a2d8a1ba04a1f38c506d137e8c"
     "select"
     "  *"
     "from"
     "  ("
     "    select"
     "      *"
     "    from"
     "      orders;"
     "-- a comment)"],
    :params [],
    :type :invalid-query}}]
```

**Comment by lbrdnk** [comment]
This issue is probably related to #30334.
