### ISSUE TITLE
Add Metabase version to revision history

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#29167]
**Is your feature request related to a problem? Please describe.**
- When viewing a question or a question's revision history, it is not currently possible to tell exactly and without forensic analysis which version of Metabase was used to create or modify the question/dashboard/etc. When Metabase schemas are changed in the application database, they are not always backwards compatible. Troubleshooting this is extremely difficult as it requires forensic analysis or familiarity with the application database schema change history which is not clearly recorded anywhere.

**Describe the solution you'd like**
- Add a field for `"metabase_version"` to all revision history objects (going forward), such that querying a revision history will list not just who made the change, when and what change they made, but also the Metabase version used to make the change.

**Describe alternatives you've considered**
- Versioned API - likely a significant effort, need ability to troubleshoot these issues sooner

**How important is this feature to you?**
- Would significantly improve Success ability to troubleshoot record compatibility issues that crop up most of the times the application database schema has non-backwards compatible changes (often times caused by changes to frontend schema changes).
- Would allow for finding fixing other compatibility issues pro-actively instead of relying on the question/dashboard to break before fixing. (i.e. If we identify an issue in a version, we can query the app db for records matching those parameters to correct).

**Comment by paoliniluis** [comment]
I think this is the same as https://github.com/metabase/metabase/issues/28387?

**Comment by likeshumidity** [comment]
@paoliniluis a bit different, save on every edit vs on last edit, but I would be happy to have either or both. Would be very helpful either way.
