### ISSUE TITLE
[Epic] Add a dashboard card setting to display/hide conditionally

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#29175]
[Product doc](https://www.notion.so/metabase/Add-a-dashboard-card-setting-to-display-hide-conditionally-caaab489d9964a8a8b5c257a453d1a89?pvs=4#2b2a8e67133b42689e1b833956a86654)
[Next steps outlined here](https://www.notion.so/metabase/Add-a-dashboard-card-setting-to-display-hide-conditionally-caaab489d9964a8a8b5c257a453d1a89?pvs=4#7ff990453a1c4200b0dac873973d1487)

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/30630
- [x] BE: Hide cards in email/slack subscriptions
```

**Comment by e-gaulue** [comment]
I totally agree #29035
