### ISSUE TITLE
Question's column title rename issue. 

### ISSUE THREAD

**Issue by xoxmono** [metabase/metabase#29202]
**Issue Details**
- I can not rename columns that join to the same table. When i rename only one column.  All columns that joined to the same table will change automatically. 

**Example**
- I have column "location_1","location_2" the both  joined to "locations" table, when i rename "location_1" to "first_location" column  "location_2" will change to "first_location" name

**Expectation** 
 - i want to rename "location_1" to "first_location" and rename  "location_2" to  "current_location"

**Comment by paoliniluis** [comment]
troubleshooting info?

**Comment by notrom** [comment]
I keep banging into this issue too #12685

**Comment by paoliniluis** [comment]
So this one is a dupe of that one
