### ISSUE TITLE
line and bar charts don't resize properly with window in dashboard

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#29226]
**Describe the bug**
When resizing the window, line and bar chart visualizations in a dashboard don't resize properly. For example, when growing the window width the visualization does not grow in size, it leaves a lot of empty white space in the card.

**Logs**
No logs.

**To Reproduce**
1. Open a dashboard with line charts and bar charts.
2. Resize the window.

**Expected behavior**
The visualizations in the cards should resize properly.

**Screenshots/videos**

https://user-images.githubusercontent.com/37751258/225146542-cb9aff9a-ee11-4b55-b460-3920d3709a49.mov

**Information about your Metabase Installation:**

Master branch commit `5389aee506`

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.6+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.6+10",
    "os.name": "Mac OS X",
    "os.version": "13.0",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-03-08",
      "src_hash": "5b2936dc350df411dc567059489c9ff8ef59f0f3",
      "tag": "v0.46.0-SNAPSHOT",
      "branch": "master",
      "hash": "4e30153"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Not severe, minor UI nitpick.

**Comment by brunobergher** [comment]
I think this at least a P2, it affects one of the very core user journeys.

**Comment by EmmadUsmani** [comment]
This is similar to https://github.com/metabase/metabase/issues/28294
