### ISSUE TITLE
query_metadata API endpoint fails on rare occasion

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2922]
As mentioned by @dacort in #2767. Pretty much the same issue as #2915 but this is in `metabase.table/field-values`.

**Comment by dacort** [comment]
I have this failing consistently for me and it prevents the New Question filters/groupings from rendering at all. Looks like you've got a potential fix, happy to test!

**Comment by dacort** [comment]
Verified working, thanks @camsaul!
