### ISSUE TITLE
Issues with multiple entity keys - same value being used for both relationships

### ISSUE THREAD

**Issue by vinothgopi** [metabase/metabase#2925]
If this is a bug report, please fill in the blanks:
-  I am using the Safari browser.
-  My computer's OS is Mac El Capitan.
-  I'm running Metabase 0.18.1jar file
-  My database is postgres.

I had a particular table that has 2 "entity keys". When clicking through the data viewer once I get the results for a query, I go to a row which has links to 2 different tables based on the 2 entity keys. But both tables seems to use the same entity key as the value when clicking through.

For illustration:
Table A has ID and App ID as 2 entity keys.
Table B is the Logs DB that uses App ID as the foreign key
Table C is the users table which uses ID as the foreign key.

When I look up an entry on table A, I see links to go to both B and C. But the values used for linking are both the ID and not the App ID (when linking to table B)

**Comment by salsakran** [comment]
We assume that an "entity key" is effectively a primary key. I.e. there is a single unique key for the row or document. 

Your schema breaks a couple of our assumptions.  Don't have a quick fix for this, as we use entity keys widely.

**Comment by flamber** [comment]
Closing in favor of #5648, which has more details and a PR

**Comment by devurandom** [comment]
#13798 is another duplicate.
