### ISSUE TITLE
Displaying percentages while combining multiple similar charts together to form a funnel

### ISSUE THREAD

**Issue by subodhpareek18** [metabase/metabase#2926]
So I have a very specific requirement and not sure how to be able to achieve it. I have N column headers all of which represent multiple stages of a product funnel (like how many people came to page1, how many people did thingA, how many did thingB...), so I'm able to make a rudimentary funnel by making individual bar charts of each data point by first filtering the true values then fetching the count of rows grouped by the same column header. Then I go on to the edit dashboard mode and add all those bar charts to the first bar chart to make a combined bar chart that correctly displays the numerical value with a combined y axis scale. Though this is completely functional, but given the requirement I want to be able to also display what % is every step compared to the first and not just the number.

Do you think something like this will be achievable? If not do you have plans to support a proper funnel chart that can combine multiple column headers together to created the required data visualization?

Attaching couple of images to better illustrate my current process.

**Comment by zusamann** [comment]
This would be one of the individual bar charts
![untitled-1](https://cloud.githubusercontent.com/assets/12589797/16744812/73fe146a-47d0-11e6-8b2d-0c49d69d62e9.png)

Here is the combined bar chart to make sort of a funnel
![untitled-2](https://cloud.githubusercontent.com/assets/12589797/16744915/fdd0db82-47d0-11e6-8a6f-136e6736048c.png)

**Comment by mavimo** [comment]
@zusamann take a look to https://github.com/metabase/metabase/pull/3144

**Comment by flamber** [comment]
Funnel visualization has been available for many years, since 0.23 if I remember correctly:
https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#funnel
