### ISSUE TITLE
Google Sheets IMPORTDATA fails to import data from a public question URL

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#29273]
**Describe the bug**
When I try to import data into from a public URL into Google Sheets, this error happens over time:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/110378427/225618373-dfcb260b-9fcf-4592-973e-ba322ee0780e.png">

The URL is similar to this `https://<-metabase-url->/api/public/card/<-unique-id->/query/csv`

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Go to Admin Setting -> Public Sharing -> Enable
2. Click on New Question -> Sample Database -> Orders -> Visualize as a Table -> Save
3. Click on Sharing -> Enable Sharing -> Make a copy of the Public link
5. Go to google sheets and insert the following in one of the cells:

`=IMPORTDATA("https:/<-metabase-cloud-url->/api/public/card/42dsds-efad-4718-9fdssd-cs8a7a579207e/query/csv")`

7. Wait a couple of hours and go to refresh the URL it will fail to load the data. Refreshing the page doesn't even help and you have to create a new sheet to be able to refresh the data

**Expected behavior**
The IMPORTDATA loads data eveytime.

**Information about your Metabase Installation:**

Able to replicate on 1.45.3 and `master`

**Additional context**
I am not sure if this is a metabase issue or a Google Sheets Issue. The problem seems to be on Google Sheets since other users have experienced this on different tools:

https://issuetracker.google.com/u/0/issues/175144626

On the other hand we can confirm that on tools such as Trevor this doesn't happen. So there is something that Trevor is doing that might be bypassing some google sheet errors.

**Comment by Tony-metabase** [comment]
@paoliniluis had a hunch on what could be the issue and that being Google blocking the Metabase cloud IP's on it's WAF. 

I created a local instance and setup http, URL and everything was working fine. Kept the google sheet for almost a week and the error never popped out ... I am not sure what is the reason but I am 100% sure that Metabase customers that self-host don't encounter this and only customers on the Cloud hit this.

There are many theories here that Google might be rate limiting what comes from ip addresses or it has some WAF that evaluates traffic via ip reputation. But this is only happening on Cloud so needs to be replicated there

**Comment by MiguelitoES** [comment]
I'm the customer affected by this trouble. If WAF is the issue, could you update the public-facing IPs?

I've tried it all, including deployment of a custom function internally, but I have timeouts everywhere.

 @Tony-metabase @paoliniluis

**Comment by albertoperdomo** [comment]
Is this still an issue with recent versions, @Tony-metabase @MiguelitoES ?

**Comment by Tony-metabase** [comment]
It's still an issue yes but I believe it's more directly related to Google Sheets when you think about it and a lot os users there are hitting the same issue

https://issuetracker.google.com/u/0/issues/175144626?pli=1

I believe @MiguelitoES managed to find a workaround (on Google Sheets since it's a GS issue per se) ... I am fine with this being closed since internally it was only flagged once.

**Comment by albertoperdomo** [comment]
Sounds good. Thanks @Tony-metabase.
