### ISSUE TITLE
y-axis is unnecessarily split in static visualizations 

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#29281]
**Describe the bug**
This essentially the same issue as [#12939](https://github.com/metabase/metabase/issues/12939) but for static visualizations generated for email/slack subscriptions.

When the `Split y-axis when necessary` setting is enabled on a question, the y-axis will be split in many situations where it is not necessary.

**Logs**
No logs

**To Reproduce**
1. Create a question with a line or bar chart visualization, where the values are close enough to where you wouldn't expect the y-axis to be split.
2. Setup an email or slack subscription and test it to see the static visualization (or just go to `http://localhost:3000/api/pulse/preview_card_png/<card_id>`)

**Expected behavior**
The y-axis should not be split.

**Screenshots/videos**

![27](https://user-images.githubusercontent.com/37751258/225656406-0db205d0-0b54-4143-8b23-be863519e9cb.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.6+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.6+10",
    "os.name": "Mac OS X",
    "os.version": "13.0",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-03-14",
      "src_hash": "44a39228b8b0bc137fdac234191433c494d8c2e6",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "y-split",
      "hash": "13acba8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Somewhat severe, it can make visualizations look very misleading like in the screenshot I provided.

**Comment by paoliniluis** [comment]
why are you running 45.1?

**Comment by EmmadUsmani** [comment]
@paoliniluis Pretty sure I was on the latest commit on master, I'm not sure why the metadata lists it as 45.1

**Comment by Tim-Thomas** [comment]
+1 on this issue, we're running into it as well
