### ISSUE TITLE
Setting `MB_PREMIUM_EMBEDDING_TOKEN` in environment makes startup take six minutes

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#29280]
From CI:

oss: (about 30 seconds)
```
Thu, 16 Mar 2023 12:11:37 GMT   Starting backend
Thu, 16 Mar 2023 12:12:10 GMT   Backend ready
```

ee:  6 minutes
```
Thu, 16 Mar 2023 11:27:23 GMT   Starting backend
Thu, 16 Mar 2023 11:33:55 GMT   Backend ready
```

This seems to only happen when running the jar, not with `clj` and running from source.

---

### Additional context
- This seems to affect only artifacts produced since the `1.46.0-RC1` (couldn't reproduce it on `1.45.3`
- The token check fails and after that it takes a long time until Metabase starts (depending on the machine)
```
2023-03-16 15:52:35,588 ERROR public-settings.premium-features :: Error validating token : Timed out after 5.0 s
```

**Comment by qnkhuat** [comment]
Might relate to this PR that changes how we do token check: https://github.com/metabase/metabase/pull/28251

**Comment by dpsutton** [comment]
closed by https://github.com/metabase/metabase/pull/29330
