### ISSUE TITLE
Error Applying All-Time Filter to a question

### ISSUE THREAD

**Issue by udit-001** [metabase/metabase#29301]
**Describe the bug**
We are unable to apply the all-time filter to a time series question. The error appears to be on the client side, as it only occurs when attempting to apply the filter. However, any existing questions with the all-time filter applied seem to be working fine. We did not encounter this issue before updating to the latest version.

**Logs**
![image](https://user-images.githubusercontent.com/23015406/225778845-66d91579-4d87-4d5b-97ef-681b946bf004.png)

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Open any time series question with some filters such as:
![image](https://user-images.githubusercontent.com/23015406/225779049-39bbe9e0-4162-4308-b987-daf35d935039.png)
2. Select All time filter from it:
![image](https://user-images.githubusercontent.com/23015406/225779136-5a8df77f-d28e-460a-a939-28387f163761.png)
3. See error
![image](https://user-images.githubusercontent.com/23015406/225779181-841a775b-0872-46dd-b834-7d3c816438e1.png)

**Expected behavior**
All time filter should be applied

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

- Your browser and the version: All browsers
- Your operating system: All OS (Windows 10/Fedora 37/Ubuntu 22/MacOS)
- Your databases: PostgreSQL
- Metabase version:  v0.45.3
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It is currently impossible to view data for all time. Only questions that had the all-time filter applied before seem to work. However, after making any changes, it becomes impossible to revert back to the all-time filter.

**Comment by paoliniluis** [comment]
Hi, are you able to reproduce when creating a new question?

**Comment by udit-001** [comment]
> Hi, are you able to reproduce when creating a new question?

Yes, I can create questions using the visual editor, which initially include the all-time filter. However, when I switch to a different filter and attempt to reapply the all-time filter, it fails once again.

**Comment by paoliniluis** [comment]
Thanks, can you post a step by step reproduction? as I tried to do what you mention but I couldn't hit the error
