### ISSUE TITLE
Crate tests broken

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2932]
Crate tests have ceased to work for all versions of Metabase. I've tried 3 different versions of Crate against Metabase releases all the way back to May and am still seeing the same error.

PR to disable crate tests: #2933 (we can reverse it when the tests are fixed)

**Comment by camsaul** [comment]
Open issue on Crate's GH https://github.com/crate/crate/issues/3786

**Comment by mikethebeer** [comment]
@camsaul https://github.com/metabase/metabase/pull/2934

**Comment by camsaul** [comment]
Fixed
