### ISSUE TITLE
Fix model x-ray title

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#29339]
When a model x-ray is shown, the text "question" is shown in the title and tab, as shown here:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/8381441/226046400-ab676936-3bc2-4513-be0e-3c9ff06f15c2.png">

For context, see [this thread](https://metaboat.slack.com/archives/C04TW1NRJA2/p1678981665609339). Per this thread, we could just drop the "question" text, but we should get clarification first.

Before doing development on this, we need to resolve the correct behavior for questions and models. Options:

Correct the labels as:
- `Here's a quick look at your "Mark's Question" question` for the question
- `Here's a quick look at your "Mark's Model" model` for the model

Drop the question/model text altogether:
- `Here's a quick look at your "Mark's Question"` for the question
- `Here's a quick look at your "Mark's Model"` for the model

**Comment by darksciencebase** [comment]
Clarification from the thread:

> we could just go with:
> `Here's a quick look at "Mark's Question"`
> `Here's a quick look at "Mark's Model"`
> Or more realistically:
> `Here's a quick look at "Surveys, past 60 days"`
> `Here's a quick look at "Subscriptions"`
> Note that I’m proposing we also drop the `your`

**Comment by darksciencebase** [comment]
Seems like a low hanging fruit, so I'm moving it to Up Next. If that assumption is wrong, move it somewhere else.

**Comment by darksciencebase** [comment]
closing as duplicate

**Comment by markbastian** [comment]
This is done. Double checked that it works today.
