### ISSUE TITLE
Field custom mappings not working on (public) embedding

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29346]
**Describe the bug**
If you do a custom mapping over a field, the field will display remapped in filters in normal dashboards, but it won't work in public embeddings

It seems that in public dashboards we're not considering that the field is remapped, and although the API call brings the remapped values, we don't show those in the FE:
![image](https://user-images.githubusercontent.com/1711649/226204149-ab4209dd-6d21-42c9-ba11-0c863ed86bdd.png)

**Logs**
NA

**To Reproduce**
1) go to settings->data model->orders-> change the data type to category and click on the gear on "quantity" field
2) remap a few quantities to words
3) create a new question with the orders table, add it to a dashboard
4) create a dropdown filter and connect it to quantity field
5) see the remapped values

6) now go to settings->admin and enable public sharing
7) go to sharing in the dashboard and use a public share, open the dashboard and see that the values are not remapped

**Expected behavior**
If a field is remapped we should see that as well

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Metabase version: 1.44.6+

**Severity**
P2

**Additional context**
NA

**Comment by qnkhuat** [comment]
Fixed by https://github.com/metabase/metabase/pull/30217
