### ISSUE TITLE
CSV reports missing records on GCP

### ISSUE THREAD

**Issue by pradeep-eatfit** [metabase/metabase#29344]
**Read this before creating a bug report**
- if any of the sections are incomplete, we might close the bug report since we won't be able to reproduce it
- have you checked if the bug has already been reported? As we close duplicate reports, please search on the issue tracker if the problem has been reported before
- use as many screenshots or videos as possible to describe what you're seeing, all visual representations speak for themselves

**Describe the bug**
The downloaded CSV reports have lesser records than they should actually have on GCP. Data source is GBQ

**Logs**
Please include JavaScript console logs (open the browser dev tools and check the "console" tab) as well as the server logs (Metabase logs that you can get from Settings -> Admin -> Troubleshooting -> Logs) around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Go to any question
2. Click on download reports. The number of rows should be greater than at least 80K
3. Check the reports
4. The number of rows will be lesser than what it should be

Ensure you are connected to GBQ

**Expected behavior**
All the records should be recorded in CSV

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Information about your Metabase Installation:**.
Using on prem installation. Tried with version 04.3.3 and even the latest version

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Ubuntu-0ubuntu118.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Ubuntu-0ubuntu118.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1101-gcp",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.39-google-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-13",
      "tag": "v0.43.3",
      "branch": "release-x.43.x",
      "hash": "c9c7ef0"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
High. All our teams use Metabase for daily operations.

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by paoliniluis** [comment]
you're running an old version of metabase that might have plenty of bugs, ensure you're running the latest one

**Comment by pradeep-eatfit** [comment]
We did try 0.45 its the same. It works on AWS but not working on GCP

**Comment by paoliniluis** [comment]
That’s not possible, it’s an app that runs in the jvm so it shouldn’t have any difference wherever you run it

**Comment by pradeep-eatfit** [comment]
It is happening

**Comment by pradeep-eatfit** [comment]
I can show you if we can get on a call
