### ISSUE TITLE
Export/Import dumps without database schemas.

### ISSUE THREAD

**Issue by veschin** [metabase/metabase#29355]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to export Collections, Dashboards, and Cards, excluding database schemas (Table/Field/Database).
**The main reason is the speed of exporting**. I think it's not always important to export schemas. 

- For example, in a situation where multiple metabase instances on different hosts have access to the same data source, why not allow the user to export only entities?
- If there is a situation where one of the data sources is unavailable for technical reasons, then the export time increases dramatically.

``` clojure
  (require '[criterium.core :refer [bench]]
           'metabase.cmd)

  (def test-path "/tmp/test-path")

  ;; TRUNCATED EXPORT
  (bench
   (with-truncated-export
     (metabase.cmd/export test-path)))
  ;; Evaluation count : 6480 in 60 samples of 108 calls.
       Execution time mean : 9.306404 ms
  ;;   Execution time std-deviation : 233.757617 µs
  ;;   Execution time lower quantile : 8.856533 ms ( 2.5%)
  ;;   Execution time upper quantile : 9.747622 ms (97.5%)
  ;;   Overhead used : 1.982410 ns

  ;; DEFAULT
  (bench (metabase.cmd/export test-path))
  ;; Evaluation count : 420 in 60 samples of 7 calls.
       Execution time mean : 157.048828 ms
  ;;   Execution time std-deviation : 2.589874 ms
  ;;   Execution time lower quantile : 154.284784 ms ( 2.5%)
  ;;   Execution time upper quantile : 163.660487 ms (97.5%)
  ;;   Overhead used : 1.982410 ns

```

**Describe the solution you'd like**
I think the team will come up with a concise solution. But for the prototype, I just turned off the schemas from the export.

``` clojure
  (require '[metabase-enterprise.serialization.v2.ingest :as v2.ingest]
           '[metabase-enterprise.serialization.v2.models :as v2.models])

  (def test-path "/tmp/test-path")

  (defmacro with-truncated-export
    [& body]
    `(with-redefs [v2.ingest/legal-top-level-paths #{"collections" "snippets"}
                   v2.models/exported-models       ["Card"
                                                    "Collection"
                                                    "Dashboard"
                                                    "NativeQuerySnippet"
                                                    "Setting"]]
       ~@body))

  (with-truncated-export
    (metabase.cmd/export test-path))
```

**Describe alternatives you've considered**
Add to the export pipeline an option to select entities for export.

**How important is this feature to you?**
That would be a lovely addition to the existing export/import pipeline.

Referring to this issue
https://github.com/metabase/metabase/issues/29275

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/15284

**Comment by luizarakaki** [comment]
Shipped on 47
