### ISSUE TITLE
x-axis label spacing

### ISSUE THREAD

**Issue by tomkanjam** [metabase/metabase#2935]
X-axis labels seem to adapt up to a certain point after which they look bad. 
### Example of good x-axis spacing.

Actually even this is not that great because the x-axis is made up of categories. The user can't fill in the blanks just by glancing at the chart. Having sparse labels like this is only really helpful if you have linear data where you could fill in the blanks in your head, like dates.

![image](https://cloud.githubusercontent.com/assets/303566/16776428/27c330cc-481a-11e6-8f46-ae63eee7ea34.png)
### Bad x-axis label spacing.

![image](https://cloud.githubusercontent.com/assets/303566/16776056/62b7d662-4818-11e6-85cf-4acd0c0b7a99.png)

**Comment by mazameli** [comment]
Fixed by #7103
