### ISSUE TITLE
Cannot run standalone JAR built from master on AWS

### ISSUE THREAD

**Issue by Germanaz0** [metabase/metabase#2936]
If this is a bug report, please fill in the blanks:

*  I am using chrome browser.
*  My computer's OS is Ubuntu 14.04
*  I'm running Metabase on AWS using JAR [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is H2.
*  My Metabase version is master.

- I have the lein file and also Node 4.4.7
- Java version:

> java version "1.7.0_101"
> OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
> OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Problem**: I am trying to run standalone jar into an Ubuntu machine on an AWS instance.

When I execute the command "`java -jar metabase.jar`" I get the following error

> java.lang.NoClassDefFoundError: metabase/driver/bigquery$?s__GT_str
> 	at metabase.driver.bigquery__init.load(Unknown Source)
> 	at metabase.driver.bigquery__init.<clinit>(Unknown Source)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:278)
> 	at clojure.lang.RT.classForName(RT.java:2168)
> 	at clojure.lang.RT.classForName(RT.java:2177)
> 	at clojure.lang.RT.loadClassForName(RT.java:2196)
> 	at clojure.lang.RT.load(RT.java:443)
> 	at clojure.lang.RT.load(RT.java:419)
> 	at clojure.core$load$fn__5677.invoke(core.clj:5893)
> 	at clojure.core$load.invokeStatic(core.clj:5892)
> 	at clojure.core$load.doInvoke(core.clj:5876)
> 	at clojure.lang.RestFn.invoke(RestFn.java:408)
> 	at clojure.core$load_one.invokeStatic(core.clj:5697)
> 	at clojure.core$load_one.invoke(core.clj:5692)
> 	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
> 	at clojure.core$load_lib.invokeStatic(core.clj:5736)
> 	at clojure.core$load_lib.doInvoke(core.clj:5717)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:142)
> 	at clojure.core$apply.invokeStatic(core.clj:648)
> 	at clojure.core$load_libs.invokeStatic(core.clj:5774)
> 	at clojure.core$load_libs.doInvoke(core.clj:5758)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.core$apply.invokeStatic(core.clj:648)
> 	at clojure.core$require.invokeStatic(core.clj:5796)
> 	at clojure.core$require.doInvoke(core.clj:5796)
> 	at clojure.lang.RestFn.invoke(RestFn.java:408)
> 	at metabase.driver$find_and_load_drivers_BANG_.invokeStatic(driver.clj:276)
> 	at metabase.driver$find_and_load_drivers_BANG_.invoke(driver.clj:270)
> 	at metabase.core$init_BANG_.invokeStatic(core.clj:126)
> 	at metabase.core$init_BANG_.invoke(core.clj:114)
> 	at metabase.core$start_normally.invokeStatic(core.clj:214)
> 	at metabase.core$start_normally.invoke(core.clj:208)
> 	at metabase.core$_main.invokeStatic(core.clj:248)
> 	at metabase.core$_main.doInvoke(core.clj:243)
> 	at clojure.lang.RestFn.invoke(RestFn.java:397)
> 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
> 	at metabase.core.main(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: metabase.driver.bigquery$?s__GT_str
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 	... 39 more
> 07-12 17:24:29 ERROR metabase.core :: Metabase Initialization FAILED:  metabase/driver/bigquery$?s__GT_str
> 07-12 17:24:29 INFO metabase.core :: Metabase Shutting Down ...
> 07-12 17:24:29 INFO metabase.core :: Metabase Shutdown COMPLETE

**Comment by Germanaz0** [comment]
Update: 
 - Just updated java version to oracle one.

> java version "1.8.0_91"
> Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

And I am still having the same issue

**Comment by camsaul** [comment]
@Germanaz0 what version of Metabase are you using?

**Comment by camsaul** [comment]
@Germanaz0 are you still seeing this issue?

**Comment by camsaul** [comment]
@Germanaz0 you said you were running Metabase from the `master` branch via the JAR, correct? How did you build the JAR? I suspect this is just an issue with how the JAR was built or even with that particular commit. 

While we try to keep `master` always working, occasional issues like the one you're seeing can pop up from time to time. [As mentioned in our README](https://github.com/metabase/metabase#danger-zone), we *do not* recommend using `master` builds for production; please use the latest stable build instead from  http://metabase.com/start.

**Comment by camsaul** [comment]
@Germanaz0 ?

**Comment by camsaul** [comment]
@Germanaz0 ?

**Comment by camsaul** [comment]
@Germanaz0 ?

**Comment by camsaul** [comment]
@Germanaz0 since we haven't heard back since July I'm going to go ahead and close out this issue. It sounds like a temporary problem with the `master` branch that was causing the custom JAR you built to fail to launch. 

Feel free to open a new issue if you run into further problems.
