### ISSUE TITLE
Dropdown List Filter and SQL Based Dropdown List Filter

### ISSUE THREAD

**Issue by bun4uk** [metabase/metabase#29361]
**Is your feature request related to a problem? Please describe.**
There is no possibility to add filter by few values in complex SQL-question. There is a `Field Filter`, but it will not work if I have a very big table or I want to filter a complex SQL-question.

**Describe the solution you'd like**
Handwritten or SQL-based dropdown filters would be a great solution for this issue. 

**Describe alternatives you've considered**
There is a great solution you can watch in redash.  

**How important is this feature to you?**
I'ts really important feature. The thing is that we have a data lake and a big number of tables and usually our queries are very complex so Field Filters doesn't work for this approach. 

**Additional context**
Examples from Redash:
<img width="728" alt="CleanShot 2023-03-20 at 17 43 53@2x" src="https://user-images.githubusercontent.com/14631690/226393375-ecf5f599-7543-4221-9d80-e19478a0667b.png">
<img width="687" alt="CleanShot 2023-03-20 at 17 44 25@2x" src="https://user-images.githubusercontent.com/14631690/226393391-aee61849-e44c-478d-856c-03e5d86dd019.png">
![CleanShot 2023-03-20 at 17 44 56@2x](https://user-images.githubusercontent.com/14631690/226393401-4f7b8bd6-7b3f-47e0-8a76-3162e0f3e67a.png)
![CleanShot 2023-03-20 at 17 45 30@2x](https://user-images.githubusercontent.com/14631690/226393413-d988dcc3-5db6-437a-9ec3-27111522d070.png)
![CleanShot 2023-03-20 at 17 45 56@2x](https://user-images.githubusercontent.com/14631690/226393436-c64a381b-2ee3-4e9f-8dd3-fcdb1b229899.png)

**Comment by paoliniluis** [comment]
This was added in 46
