### ISSUE TITLE
Frontend does not render contents of a column

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29374]
**Describe the bug**
There seems to be a case where the frontend does not render a column although the backend brings the data

**Logs**
NA

**To Reproduce**
I really don't know how to reproduce this, but check question 7326 in our internal Metabase instance, the column Title doesn't have any content (if you convert the question to SQL it will work)

**Expected behavior**
Title column has data, so it should be rendered

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Metabase version: master, stats

**Severity**
P1

**Additional context**
NA

**Comment by nina-metabase** [comment]
Update: The issue was fixed. There was an issue with the metadata formatting. I fixed it and the column now shows up
