### ISSUE TITLE
metabot changes a line graph to table

### ISSUE THREAD

**Issue by jobevers** [metabase/metabase#2937]
When showing a card that is a line graph on the website, metabot switches the chart type to table and shows the table instead.
-  I am using the chrome browser.
-  My computer's OS is OSX.
-  I'm running Metabase on AWS EBS. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is postgres.
-  My Metabase version is 0.18.1.

**Comment by tlrobinson** [comment]
Currently pulses work with a limited set of queries/visualizations. The logic for determining which visualization to show is here: https://github.com/metabase/metabase/blob/8f1a287496899250d89a20ec57ac8477cd20bce5/src/metabase/pulse/render.clj#L385-L397

**Comment by jobevers** [comment]
Ah.  My dataset has integers for column 1 so it fails the sparkline test but it has two columns and the second column is a number.  Not sure why it didn't return a bar graph at least.

It does seem that if the card is configured to be displayed as a line - it should be displayable as a sparkline, but maybe I'm missing something.

**Comment by thucnc** [comment]
I got the same problem. My pulse shows 'table' for a simple bar chart as attachment, not sure what's wrong here. 
[http://imgur.com/a/ixVXt](http://imgur.com/a/ixVXt)

Please help

**Comment by flamber** [comment]
Closing in favor of #5493
