### ISSUE TITLE
Dashboard save button throwing TypeError, showing save failed

### ISSUE THREAD

**Issue by sarina-dd** [metabase/metabase#29412]
**Describe the bug**
I created a dashboard in my personal collection and added saved questions to the dashboard. I clicked save, and the save failed. It seems similar to past [issue 20517](https://github.com/metabase/metabase/issues/20517).

I waited over the weekend to see if the issue would resolve, tried again today, and it's still persisting. Another person internally had a similar issue, but in a team collection. It seems like the error may persists across personal and team collections. DM me for internal thread on the issue if needed for additional context.

**Logs**

Chrome console:

```
ActionButton.jsx:80 TypeError: Cannot read properties of undefined (reading 'length')
    at rn (utils.ts:13:59)
    at save.js:36:37
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at cn (app-main.bundle.js?fa9b8ac1a8eb34198c44:2:891753)
    at a (app-main.bundle.js?fa9b8ac1a8eb34198c44:2:891957)
    at app-main.bundle.js?fa9b8ac1a8eb34198c44:2:892018
    at new Promise (<anonymous>)
    at app-main.bundle.js?fa9b8ac1a8eb34198c44:2:891897
```

_Don't have access to Metabase logs, only have access to Settings -> Admin Settings w/o troubleshooting or logs options_

**To Reproduce**
1. Go to your personal collection, create a new dashboard
2. Choose any saved question to add to the dashboard
3. Click save
4. "Save failed" error shows in the save button, error is thrown in console

**Expected behavior**
Dashboard should save when clicking save.

**Screenshots/videos**
<img width="410" alt="Screenshot 2023-03-21 at 3 16 03 PM" src="https://user-images.githubusercontent.com/57639676/226734470-d12015a0-c9c0-4b00-88f5-e575c558f3da.png">

<img width="545" alt="Screenshot 2023-03-21 at 2 54 36 PM" src="https://user-images.githubusercontent.com/57639676/226734612-64df559e-4bb0-434d-b0d8-6bc744b3e404.png">

**Information about your Metabase Installation:**

- Browser: Chrome Version 111.0.5563.64 (Official Build) (arm64)
- OS: Ventura 13.2.1
- Your databases: Unknown (internal)
- Metabase version: It says vUNKNOWN

<img width="475" alt="Screenshot 2023-03-21 at 3 30 43 PM" src="https://user-images.githubusercontent.com/57639676/226735439-a6558d9a-3ec2-4471-b2ab-9dfa973cad45.png">

**Severity**

How severe an issue is this bug to you? It's blocking me from saving a dashboard to analyze blog traffic.

**Comment by paoliniluis** [comment]
Is this a local Metabase? is it our internal metabase instance?

**Comment by sarina-dd** [comment]
Internal

**Comment by paoliniluis** [comment]
Only seems to happen on MacOS

**Comment by uladzimirdev** [comment]
I wasn't able to reproduce the issue. @paoliniluis any tips on it?

**Comment by uladzimirdev** [comment]
@sarina-dd may I ask you to double check if the issue still persists? if so, I'd ask you about more detailed steps

**Comment by sarina-dd** [comment]
It looks like the issue had resolved with the other ticket! Closing out this issue.
