### ISSUE TITLE
:has_question_and_dashboard from `api/user/current` is always false

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#29438]
This query
https://github.com/metabase/metabase/blob/67bfd4dd62838ee45e895a42948ca78186c4ae06/src/metabase/api/user.clj#L207
is always returns false because `perms-query` is a map and `(perms-query user) => nil)`

**Comment by noahmoss** [comment]
@qnkhuat Does this actually manifest as a bug in the product or is it just tech debt?

**Comment by qnkhuat** [comment]
Sorry but I don’t, found this while browsing through the code.

**Comment by alxnddr** [comment]
FE uses it in `frontend/src/metabase/home/components/HomeContent/HomeContent.tsx`
