### ISSUE TITLE
There is no possibility to use model or saved query as a dropdown list source for non-Admin users

### ISSUE THREAD

**Issue by bun4uk** [metabase/metabase#29446]
**Describe the bug**
There is no possibility to use model or saved query as a dropdown list source for non-Admin users. Got 403 error and message that `"You don't have permissions to do that."`

**Logs**
Please include JavaScript console logs (open the browser dev tools and check the "console" tab) as well as the server logs (Metabase logs that you can get from Settings -> Admin -> Troubleshooting -> Logs) around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
Server Log: ```[12309828-1262-4b07-b33e-71a7328172ca] 2023-03-22T18:44:36+02:00 WARN metabase.server.middleware.log GET /api/collection/root 403 6.0 ms (3 DB calls) 
"You don't have permissions to do that."```
Browser Log:
<img width="1512" alt="CleanShot 2023-03-22 at 18 54 46@2x" src="https://user-images.githubusercontent.com/14631690/226979899-f25c4b12-7386-42b5-832f-45b1f520521f.png">

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Go to New SQL Query using non-admin user.
2. Write any SQL with variable. For example `select * from ACCOUNTS where FIRST_NAME = {{FIRST_NAME}}` 
3. Chose Dropdown List –> Edit -> From another model or question -> Pick a model or question...
4. Wait for a moment and see error `You don't have permissions to do that.`

**Expected behavior**
Possibility to see and chose one of saved queries or models as a source for the dropdown list filter

**Screenshots/videos**
![CleanShot 2023-03-22 at 19 05 03@2x](https://user-images.githubusercontent.com/14631690/226982832-59a3c63c-a0fa-4e4c-95e7-011404cdb954.png)
![CleanShot 2023-03-22 at 19 07 42@2x](https://user-images.githubusercontent.com/14631690/226983357-50043a6e-1539-4a4d-9e48-f4539dc29fbf.png)
<img width="1512" alt="CleanShot 2023-03-22 at 19 07 59@2x" src="https://user-images.githubusercontent.com/14631690/226983366-db1de080-2917-4c9f-8ac1-8a441994914f.png">

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "uk-UA",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.228-131.415.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-14",
      "tag": "v0.46.0-RC3",
      "branch": "release-x.46.x",
      "hash": "cd8708d"
    },
    "settings": {
      "report-timezone": "Europe/Kyiv"
    }
  }
}
```

**Severity**
It will simplify our work and unblock the work of many analysts because not only admins could use saved queries and models as dropdown list filter source.

**Comment by paoliniluis** [comment]
Thanks @bun4uk , have you tried this in 46.1?

**Comment by paoliniluis** [comment]
@bun4uk pinging

**Comment by bun4uk** [comment]
@paoliniluis checked for 47.2
Everything works well
Thanks!
