### ISSUE TITLE
Cannot connect to BigQuery datasource with > 10000 tables

### ISSUE THREAD

**Issue by akita-ken** [metabase/metabase#2946]
- I am using the Google Chrome (v51.0.2704 - x86-64) browser.
- My computer's OS is Mac OS X 10.11.5.
- I'm running Metabase locally from the JAR.
- My database is H2.
- My Metabase version is 0.18.1.

I am receiving this message on the server console, in addition to the red text indicating 'Timed out after 5000 milliseconds.' on the web UI. I have tried using the 0.18.0 JAR and it is able to connect fine, but I'm not ruling out network issues as yet. Is there some way I can view a more descriptive log to troubleshoot the problem?

`07-13 10:08:20 ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.`
`07-13 10:08:20 DEBUG metabase.middleware :: POST /api/setup/validate 400 (5 s)
{:message "Timed out after 5000 milliseconds."}`

**Comment by camsaul** [comment]
@akita-ken to clarify you've tried both the 0.18.0 JAR and the 0.18.1 JAR on the same computer and tried to connect with the same DB details?

**Comment by akita-ken** [comment]
@camsaul Hi, I have narrowed down the timeout issue to being caused by our dataset having too many tables. I tried the 0.18.1 JAR with a dataset that had the entirety of our data in one giant table and it was able to connect fine. Is there any way that I can tweak the timeout setting?

**Comment by camsaul** [comment]
@akita-ken sorry for the long delay before replying. It shouldn't make a difference how many tables are in your database when it checks to see if it can connect. Are you still seeing this issue?

**Comment by camsaul** [comment]
@akita-ken ?

**Comment by akita-ken** [comment]
@camsaul Apologies for the delay, I had forgotten about the issue!

I will test with the 0.19.3 JAR to see if I can reproduce the problem and report back shortly.

**Comment by akita-ken** [comment]
@camsaul Hi, can confirm that the issue still occurs. I am able to connect to a BigQuery dataset with around 400 tables, but when I try one with 10000< tables, I receive the red text indicating 'Timed out after 5000 milliseconds.'

**Comment by cosenal** [comment]
I can reproduce it too on version v0.20.0 (Built on 2016-10-11)

**Comment by edwardchuang** [comment]
bump. I can reproduce this here with v0.20.3
wonder if just simply raise the timeout limit ...

**Comment by camsaul** [comment]
Hi @edwardchuang, if you want to try raising the timeout limit [it's defined here](https://github.com/metabase/metabase/blob/master/src/metabase/driver.clj#L348); I'd be interesting in seeing if that actually fixes this problem.

TBH I'm not sure I understand why it would take BigQuery longer to test a connection to a dataset with thousands of tables, but it's something we can investigate. The only plausible theory I can think of is that it's for one reason or another fetching a sequence of tables in the dataset while testing the connection. Thus I don't think raising the connection timeout past 5-seconds is a good solution to the problem; we ought to address the root cause of the issue rather than slap a Band-Aid™ on it.

Anyway, let me know if you have any success with that.

**Comment by edwardchuang** [comment]
@camsaul thanks, I'll give it a try now. But I can't find any instruction for building own jar from the source code, am I missing something ?

**Comment by camsaul** [comment]
Hi @edwardchuang, our [Developers' Guide](https://github.com/metabase/metabase/blob/master/docs/developers-guide.md) explains how to build Metabase. Let me know if you have any questions.

**Comment by edwardchuang** [comment]
@camsaul it's seems everything is fine with tune-up the timeout limit, success to hook up the bigquery now.

```
12-13 03:28:20 INFO driver.bigquery :: Fetching BigQuery access/refresh tokens with auth-code 'CENSORED'...
12-13 03:30:18 DEBUG metabase.middleware :: POST /api/setup/validate 200 (2 mins) (0 DB calls)
```
(took 2 minutes!)

and it spent a very long time to find the new tables ...

```
12-13 03:35:21 DEBUG sync-database.introspect :: Found new table: BLAHBLAH_20161009
12-13 03:35:21 INFO sync-database.introspect :: [**················································] 😢    4% Synced table 'BLAHBLAH_20161009'.
12-13 03:35:21 DEBUG sync-database.introspect :: Found new table: BLAHFOO_20161204
12-13 03:35:21 INFO sync-database.introspect :: [**················································] 😢    4% Synced table 'BLAHFOO_20161204'.
```

IMHO, it's a very common and even a best-practics that bigquery is storing logs with date partitioning. it will lead to thousand of tables in single bigquery dataset.

**Comment by camsaul** [comment]
@edwardchuang I'm not questioning the your reasons for having thousands of tables, I just don't know why it's making the connection slow 😉 . What did you raise the timeout limit to?

**Comment by edwardchuang** [comment]
I bump to 500000 and wanna make sure it's enough to be timeout :-)
And syncing the table is another nightmare, maybe a separate issue ?

**Comment by camsaul** [comment]
Cool, glad it works. Unfortunately I don't think it's a good idea to make people wait 8 minutes to see if their database connection failed 😥 I'll look into other ways to address this 😞

**Comment by cdruxerman** [comment]
@camsaul I am running into the same problem. Did you have a further update on how to address this. Also, how would I increase the timeout limit in the meantime?
