### ISSUE TITLE
Allow reordering of aggregations in notebook mode

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#29473]
**Is your feature request related to a problem? Please describe.**
When creating a query in the editor and having multiple filters, multiple metrics in a summarize oder multiple group by's in a summarize it is very painful to reorder them. It would be purely cosmetic (only change row order for summarize) but it would elevate the UI to the next level and speed up the process of querying.

<img width="1462" alt="Screenshot 2023-03-23 at 11 38 37" src="https://user-images.githubusercontent.com/113892067/227178125-2745aac8-bfab-41c6-acb2-ae3da74feed5.png">

**Describe the solution you'd like**
I want to be able to drag and drop reorder items in their respective buckets. In the example I would like to be able to take the User ID card from the group by and drag it behind the currency and drop it there. Same should be possible in the metrics / filter section.

**Comment by paoliniluis** [comment]
closing this one for https://github.com/metabase/metabase/issues/38862
