### ISSUE TITLE
Be able to set users to only see some dashboards

### ISSUE THREAD

**Issue by cagiraudo** [metabase/metabase#2949]
I don't know if this was already proposed

I have a company where i have some dashboards that are financial and only few peoples should see and some others that are more public

It will be awesome if i could make users that can only see some dashboards so i can give that permisson to some employees.

If that's hard to do maybe you could add an option to make public a dashboard, so anyone that has that link can see that without login, becouse if they log they will be able to see all the dashboards

That's it. i hope this suggestion can help improving Metabase that is already awesome.

If you need more help or information ask

**Comment by kdoh** [comment]
Thanks for the suggestion @cagiraudo. We're looking at tackling scenarios like this with a more robust permission system. Discussion on that is happening over in #1175 so I'm going to close this issue so we can consolidate the conversation in one spot.
