### ISSUE TITLE
[Epic] Support JWT and other SSO methods at the same time

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#29492]
Product doc: [Enable multiple SSO methods in the same instance](https://www.notion.so/metabase/Enable-multiple-SSO-methods-in-the-same-instance-7e3d1917b1104b1085ad8f87329fce63?pvs=4)

![image](https://github.com/metabase/metabase/assets/32561114/dc55e736-e272-4d92-ae34-ae826438496a)

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/18554

**Comment by paoliniluis** [comment]
I think that JWT and others work perfectly fine. The issue is JWT and SAML which use the same endpoints. @Tony-metabase

**Comment by Tony-metabase** [comment]
Correct, LDAP uses the same endpoint as username & password

<img width="508" alt="image" src="https://github.com/metabase/metabase/assets/110378427/279648ef-4307-42e1-97d6-056e04c7178a">

**Comment by likeshumidity** [comment]
https://github.com/metabase/metabase/issues/18644

**Comment by paoliniluis** [comment]
It would make a lot of sense if we tell the admin on the application that if they enable SAML, we will disable JWT and the other way round, so we make this issue explicit in the product for the time being. Right now, we allow the admin to enable this, while this doesn't work

**Comment by FilmonK** [comment]
Please feel free to correct anything I’m overlooking.
Currently using a staging cloud environment running 1.49.6 for this test.
Azure AD for SAML auth.
Two different local node instances for JWT auth, including the [sample repo](https://github.com/metabase/metabase-nodejs-express-interactive-embedding-sample) we provide.

If I have both SAML and JWT auth enabled and I'm using JWT for authentication, I see the call for JWT and a valid token with the url is sent. However, I immediately see a call to SAML (Azure in this case), and the prompt for authentication into Azure AD appears.

Network calls withJWT and SAML enabled in Admin Settings.
<img width="876" alt="JWT_and_SAML" src="https://github.com/metabase/metabase/assets/17398657/90717ed2-85cf-4b55-98f4-e2cd017383af">

<br>
<br>

If I have either auth method enabled individually, they function as expected.
Network calls with just JWT enabled in Admin Settings
<img width="877" alt="JWT" src="https://github.com/metabase/metabase/assets/17398657/66fae58e-7f4c-4915-b5d8-07c0c72a4f4e">

<br>
<br>

I am working with a customer that is experiencing the same issue.
Let me know if you need anything from me whether it’s a Loom recording, access to Azure test account, etc.
