### ISSUE TITLE
Improve frontend unit test speed

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2950]
It'd be nice to not have to spin up a browser and compile the whole frontend app to run the JS unit tests, especially while in watch mode.

**Comment by tlrobinson** [comment]
The unit tests _are_ run in the browser by Karma. Is running `npm run test-watch` in a separate terminal not sufficient?

We may be able to speed up the startup time. I haven't looked at the Karma config in awhile.

**Comment by kdoh** [comment]
Ah derp yeah now I remember. I'm thinking we might want to reevaluate that. It looks like none of the current unit tests need the DOM, and for testing react components you don't necessarily need the DOM either depending on what you're testing.

I mostly opened this to see if we can get a faster tighter feedback loop for frontend testing so we're inclined to write more of them.

**Comment by lewisl9029** [comment]
I haven't tried it out yet personally, but it should be possible to replace Karma with jsdom for unit tests.

Here's one post about using jsdom with Mocha and cutting 10s off the overall test duration: https://medium.com/podio-engineering-blog/from-karma-to-mocha-with-a-taste-of-jsdom-c9c703a06b21#.ccezaqz6g

Here's another about using jsdom with Jasmine: http://www.nfriedly.com/techblog/2013/02/automatically-unit-testing-client-side-javascript-with-jasmine-and-node-js/

Definitely worth looking into IMO.

**Comment by camsaul** [comment]
could try a scantron, quick way to get test scores

**Comment by tlrobinson** [comment]
Whatever we use will likely need some sort of Webpack integration, so I'm not sure switching away from Karma will help that much, but it's worth a try if anyone feels like playing around with other solutions.

**Comment by kdoh** [comment]
Going to close this since we've since added Jest and in general the testing feedback loop has gotten better.
