### ISSUE TITLE
Metabase error while replacing question

### ISSUE THREAD

**Issue by adithcraft** [metabase/metabase#29509]
**Describe the bug**
Errors while replacing question from outside server: Unexpected input given to normalize. Expected type to be "object", found "string"

**Logs**
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
Error: Unexpected input given to normalize. Expected type to be "object", found "string".
    x normalizr.es.js:521
    normalize entities.js:175
    r entities.js:246
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    E engine.js:116
    a engine.js:116
    promise callback*E engine.js:116
ActionButton.jsx:80:18

**To Reproduce**
1. Go to any saved question
2. Change visualization
3. Click Done
4. Click Save
5. Choose replace existing question
6. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9067911/227416173-319493ca-b03f-46fd-8bd5-9af32759f339.png)

**Severity**
blocking usage of Metabase entirely

**Additional context**
Metabase is deployed on IIS using reverse proxy. 
There is no problem while using from local server, many error happens while accessing from internet

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Windows Server 2019",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.18"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-11-01",
      "tag": "v0.44.6",
      "branch": "release-x.44.x",
      "hash": "5c6ae21"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
Are you use using a reverse proxy?

**Comment by paoliniluis** [comment]
Also, upgrade to the latest version first

**Comment by adithcraft** [comment]
> Are you use using a reverse proxy?

Yes I am using IIS reverse proxy

**Comment by paoliniluis** [comment]
This seems to be a reverse proxy error that is doing things on the requesr
