### ISSUE TITLE
Action menu does not open for dashboards/questions in certain collections

### ISSUE THREAD

**Issue by ekroymann** [metabase/metabase#29522]
**Describe the bug**

In one of our collections the action menu does not open on any chart / question (default on-click behavior).
We get the following error traceback in the chrome dev tools.

**Logs**
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
    at drilldown.js:412:58
    at J (drilldown.js:431:16)
    at question (zoom-drill.js:9:21)
    at Se.drills (ZoomDrill.jsx:8:8)
    at Mode.ts:33:50
    at Array.flatMap (<anonymous>)
    at e.value (Mode.ts:33:33)
    at s.value (Visualization.jsx:243:14)
    at Visualization.jsx:282:12
    at SVGRectElement.t (apply_tooltips.js:353:11)
(anonymous) @ drilldown.js:412
J @ drilldown.js:431
question @ zoom-drill.js:9
Se.drills @ ZoomDrill.jsx:8
(anonymous) @ Mode.ts:33
value @ Mode.ts:33
value @ Visualization.jsx:243
(anonymous) @ Visualization.jsx:282
t @ apply_tooltips.js:353
(anonymous) @ d3.js:1120

Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
Only happens for dashboards / questions in one of our collections. Don't know what is the difference to our other collections.

**Expected behavior**
Action menu opens on click.

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "de-DE",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.10.162-141.675.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
I think you’re seeing https://github.com/metabase/metabase/issues/29517

**Comment by paoliniluis** [comment]
I think you’re seeing https://github.com/metabase/metabase/issues/29517
