### ISSUE TITLE
Detection of Redshift foreign keys automatically in the metabase UI

### ISSUE THREAD

**Issue by jugaldb** [metabase/metabase#29548]
I have a data pipeline running which brings in data from multiple data sources to AWS redshift.
All the data within redshift have their own foreign key mappings done and then the data is added.
When I go to the connected metabase instance, all the data loads upon reloading the database from redshift, but the foreign key mappings are not shown at all.
A workaround to this is manually going to the settings in metabase ui and setting foreign keys from there.
The problem is this is a very manual task and I need to do the same for 100s of tables and even more keys, is there any way of automating the detection of foreign keys that exist in redshift.

If not automating, is there anyway in which metabase would automatically pick up these changes upon refresh?

What I did: add foreign key relations manually via ui

What i expected: metabase to automatically pick up foreign key relations.

**Comment by paoliniluis** [comment]
Hi, I did the following:
![image](https://user-images.githubusercontent.com/1711649/232255057-41fee951-b45e-410f-bf17-7232f431da81.png)

And I got
![image](https://user-images.githubusercontent.com/1711649/232255039-4f6a1a3c-9ef7-4740-80d0-2d89492882ac.png)

so it seems we're doing that already if the FK's are defined in the tables
