### ISSUE TITLE
Trend Line Feature not available (anymore?)

### ISSUE THREAD

**Issue by mrryf** [metabase/metabase#29552]
**Describe the bug**
- Feature "add trend line" is gone for our entire metabase installation. 
- All documentation links from metabase indicate, that the feature exists.
- Different data have been used - no success using the trend line (short time frames, long time frames, different granularity etc.)

Indicated documentation:
Source: https://www.metabase.com/learn/visualization/line-charts

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Go to https://dashboard.liip.ch/question/101-production-chargeability-and-rate-evolution-since-2018
2. Click on Settings, klick through all possible options (axes, display, data)
3. see missing feature

**Expected behavior**
as soon as I have a itme series chart I expect the option to have a line chart

**Screenshots/videos**
![Screenshot 2023-03-27 at 11 34 13](https://user-images.githubusercontent.com/16573045/227903038-cbdc54c4-7292-42f5-83f3-266645954525.png)
![Screenshot 2023-03-27 at 11 34 27](https://user-images.githubusercontent.com/16573045/227903041-6c9cb7e4-7292-4df2-9c3c-9403eafd93c6.png)
![Screenshot 2023-03-27 at 11 34 08](https://user-images.githubusercontent.com/16573045/227903031-b65bdd6a-c3f4-4966-8a17-095333b466d9.png)

**Information about your Metabase Installation:**

 ```
 "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.0-144-generic",
    "user.language": "en",
    "user.timezone": "Europe/Zurich"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.5 (Debian 14.5-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": "Europe/Zurich"
    }
  }
}
```

- Your browser and the version: Google Chrome (Version 111.0.5563.110 (Official Build) (arm64))
- Your operating system: OSX 12.3.1 (21E258)
- Your databases: Postgres, MySQL
- Metabase version: 0.45.3
- Metabase hosting environment: Kubernetes
- Metabase internal database: hosted in K8s, with a crossplane PostgreSQL DB

**Severity**
It's rather unfortunate, as we can't see any systematic trend indicaton. As the feature is mentioned in detail, and we tested it throughout with different data, we assume this is a bug. We also  take into consideration that it is a user problem if so - we would like to see a step by step guide on how to achieve the trend line. In the screenshots mentioned in the bug report - we couldn't find it.

**Additional context**
-

**Comment by paoliniluis** [comment]
Closing this one in favor of https://github.com/metabase/metabase/issues/29836
