### ISSUE TITLE
Combine `sample-dataset` and `test-data` data in backend tests

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#29573]
Roll the `sample-dataset` tables into the `test-data` definition, so they're the same database. This will make things a little more convenient when writing tests and increase performance slightly in tests

- [ ] Move definitions from `sample-dataset.edn` into `test-data.edn`; 
- [ ] Remove all the usages of `(mt/dataset sample-dataset ...)` in tests
- [ ] Cycle the `v3_` key for BigQuery (if we're still prefixing it that way; we may change it in the near future) or any other Cloud databases that cache test dataset data loading. Athena will have to be done manually from a REPL. 
- [ ] We will probably need to update a few tests

**Comment by arvinDarmawan** [comment]
Hi @camsaul , may I try this card ?
