### ISSUE TITLE
[Epic] Offer PDF exports for dashboards

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#29584]
[Product doc](https://www.notion.so/metabase/Offer-PDF-exports-for-dashboards-3ea8d17538524deb924e9d7e8e8ecd96)
[Next steps outlined here](https://www.notion.so/metabase/Offer-PDF-exports-for-dashboards-3ea8d17538524deb924e9d7e8e8ecd96?pvs=4#8b5f94e8ce434c648b8c5b82ec67b68b)

- [x] #30199

**Comment by paoliniluis** [comment]
Part of https://github.com/metabase/metabase/issues/28547
