### ISSUE TITLE
Fail to view dashboard after edit with click behavior

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#29588]
**Describe the bug**
When editing dashboard, if you click onto "click behavior" of a dashboard then save, it'll show "something's gone wrong"

**To Reproduce**
1. new dashboard
2. add a card
3. click on the “click behavior”
4. save the dashboard

**Expected behavior**
Able to view the dashboard

**Screenshots/videos**
![Screenshot 2023-03-28 at 13 33 00](https://user-images.githubusercontent.com/25661381/228148532-6679362a-1f54-48bb-a4a3-ec1a876c26e1.png)

**Information about your Metabase Installation:**
master(8abce7995b64d7faf5c6738a6a5eb25b2ee4335c)

**Severity**
not sure but definitely not a blocker

**Comment by uladzimirdev** [comment]
@qnkhuat https://www.loom.com/share/3bf93197286242e1918a31c92000f5ec I'm not able to reproduce it

**Comment by qnkhuat** [comment]
Yea I confirmed this is no longer a bug as of b66a520d2ea0083ca745799949bc341274644b42
