### ISSUE TITLE
Admin > Tools shows up in Metabase OSS admin navbar

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#29595]
**Describe the bug**
Tools (to fix erroring questions) that is a paid-plan feature is showing up as a link in Metabase OSS version admin navbar. It doesn't lead anywhere, but it shouldn't even appear in the navbar.

**To Reproduce**
_Assumes you're using OSS version_
1. Go to admin settings
2. Notice "Tools" appearing in the navbar when they shouldn't
3. Click on it and you'll see nothing happens

**Expected behavior**
"Tools" shouldn't exist in OSS version.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/31325167/228203350-2c7d7036-9be4-4c67-92b3-3ce37484da99.png)

**Information about your Metabase Installation:**
OSS uberjar, `v0.46.0`

**Severity**
P3

**Comment by abhishek-superk** [comment]
[Model caching logs](https://www.metabase.com/docs/latest/data-modeling/models#view-model-caching-logs) are supposed to be shown there - so the expected behaviour should be that it exists only when at least one option is to be shown?

**Comment by npfitz** [comment]
This appears to have been fixed as of `362ef924a0e5d27d5a4a8fd298bd119c4df417f3`
