### ISSUE TITLE
Custom mapping for display values not persisting

### ISSUE THREAD

**Issue by wulffZ** [metabase/metabase#29600]
Mapping original values to mapped values don't seem to persist. They're incorrect in dashboard filters and revert in the admin dashboard.

Occasionally they work and persist. If this is the case, after some time has passed / refreshes the original values are displayed again.

**To Reproduce**
1. Go to admin settings
2. Navigate to table / database 
3. Click on column you want to map values for
4. Enter custom values for original values
5. Save
6. Navigate to dashboard
7. Create dashboard filter for said column
8. Observe original values, not mapped values

**Expected behavior**
Expect to see a set of mapped values, but I see the original values in the dashboard filter.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/45457638/228257076-81d504c5-266c-4ca0-bdbd-1fe446ee5c66.png)
![image](https://user-images.githubusercontent.com/45457638/228257303-8e2fbcb7-60eb-4717-9c62-56453785ea9d.png)

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "18.0.2.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "18.0.2.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "18.0.2.1+1",
    "os.name": "Windows 11",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.10.2-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
P2

**Additional context**
Also tested this on Chrome and Edge but no such luck.

**Comment by paoliniluis** [comment]
you might be seeing https://github.com/metabase/metabase/issues/29347

**Comment by wulffZ** [comment]
Thanks. Didn't find this, but I should have googled more extensively.
