### ISSUE TITLE
Selecting Pin Map visualisation crashes Mac OSX app

### ISSUE THREAD

**Issue by joshhopkins** [metabase/metabase#2960]
-  I am using the Safari browser.
-  My computer's OS is 10.11.5 (15F34).
-  I'm running Metabase locally on Mac OSX.
-  My database is the sample data provider.
-  My Metabase version is 0.18.1.1.

When plotting lat/lng on Pin Map, app either hangs or redirects to the Dashboard.

**Comment by camsaul** [comment]
What version on OS X / Safari are you using?

**Comment by joshhopkins** [comment]
Safari Version 9.1.1 (11601.6.17)
MacOS is 10.11.5 (15F34).

To clarify – I'm referring to the Mac app crashing.

**Comment by camsaul** [comment]
As with #2999 this should be fixed in 0.20 by 4c2f9f74524202796084399b24069d4378fb3cf9

**Comment by camsaul** [comment]
This was fixed by #6116 but I forgot to close it
