### ISSUE TITLE
Query metadata within comments leads to cache misses in AWS Athena

### ISSUE THREAD

**Issue by gytsvetkov** [metabase/metabase#29615]
```sql
-- Metabase:: userID: 5 queryType: native queryHash: ce6b9b0a85cf2f65a347f1fe10de417d9eeca4bf05f1562a3c9f0437e795e84f
```
I'm experiencing a similar issue as described in issue #9275, but with AWS Athena. It would be greatly appreciated if an option to disable the userID and/or queryHash could be provided

**Comment by nscavell** [comment]
We are seeing the same thing, would be nice to just have an option to turn this off for any connection created in Metabase rather than specific connections like Athena and BigQuery.

**Comment by paoliniluis** [comment]
We should just clone https://github.com/metabase/metabase/pull/13923 but on the athena driver
