### ISSUE TITLE
46 regression: `datetimeAdd` is apparently supposed to allow non-integer amounts

### ISSUE THREAD

**Issue by arladmin** [metabase/metabase#29638]
**Describe the bug**
Ever since the update to the latest version, a custom column (`formula = datetimeAdd([CreatedAt: Default period], 5.5, "hour")`) is malfunctioning which is resulting in the data not being rendered at all. Just an error is being displayed:
`Assert failed: (int? amount)`

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/64059154/228441509-7c02da86-6178-4c01-9fd6-46a8ce8af7f5.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Ubuntu-0ubuntu122.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Ubuntu-0ubuntu122.04",
    "os.name": "Linux",
    "os.version": "5.15.0-67-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.12 (Ubuntu 12.12-1.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

**Severity**
As the issue is happening in a root-level query, all the Questions and Dashboards have stopped working!

**Comment by camsaul** [comment]
I believe this restriction was always meant to be in place, if it worked in 0.45 it was accidental. 5.5 hours might make sense, but with other units like months, or quarters it doesn't, so the restriction is that that amount has to be a whole number. Can you change it to 330 minutes?

**Comment by arladmin** [comment]
> Yup, if you look at the documentation for `datetimeAdd`:
> 
> https://www.metabase.com/docs/latest/questions/query-builder/expressions/datetimeadd
> 
> > `amount`
> > A whole number or a decimal number.
> 
> This was the same in [v.045.0](https://www.metabase.com/docs/v0.45/questions/query-builder/expressions/datetimeadd). The fact that it previously worked was an accident.

A 'decimal number' implies that '5.5' is an acceptable value.

**Comment by arladmin** [comment]
Kindly update the documentation to correct this new requirement.

**Comment by camsaul** [comment]
Oops, you're right. I totally missed the part where it said `or a decimal number`. I'll reopen

**Comment by john-metabase** [comment]
Digging into this issue a bit, we currently enforce `int?` on the `amount` arg when generating a Postgres interval expression. We can easily change `int?` to `number?` and allow decimal values. I'll create a PR to do this to alleviate this specific case.

It looks like any driver that creates interval expressions the same way, e.g. Postgres and MySQL at least, has a general problem where any valid expression in the UI other than a literal number, like a function call or a reference to another column, passed as the `amount` arg to `datetimeAdd` causes an error.

This should be addressed in a follow-up PR by updating drivers to implement interval compilation to multiply the amount expression by the interval to avoid interpolating the amount into the interval string, e.g. (pseudo-SQL):

```sql
    -- current approach:
    INTERVAL '$amount $unit'
    -- new approach:
    $amount * '1 $unit'::INTERVAL
```
