### ISSUE TITLE
Use float labels on dashboard filters to save space for great justice

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2963]
Currently, labels float to the left of the filter dropdowns, taking up a lot of horizontal space. The placeholder text in inactive filters is also pretty useless:
![current](https://cloud.githubusercontent.com/assets/2223916/16856391/b167dc28-49ce-11e6-9087-c890accb0f7d.png)

Instead, we could put the filter labels inside of inactive filters, and then have them float above when a value for a filter is chosen:
![proposed](https://cloud.githubusercontent.com/assets/2223916/16856395/b7a5539a-49ce-11e6-80c5-2351fbd1e6da.png)

**Comment by tomkanjam** [comment]
+1

**Comment by mazameli** [comment]
It would be great to use some CSS transitions to move the label, a la [this example](https://codepen.io/simoberny/pen/gpddYQ)

We'll have to change the position, color, font-size, and slap on a `text-transform: uppercase`

**Comment by attekei** [comment]
This was implemented in #4543 and is already live in release 0.23.0.
