### ISSUE TITLE
Pulse create - save failed

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#2964]
While creating a pulse, it's throwing error in console. Nothing related to slack seems broken, but can't create new pulse.

```ActionButton.jsx:68 TypeError: Cannot read property 'id' of undefined(…)(anonymous function) @ ActionButton.jsx:68```

If this is a bug report, please fill in the blanks:

*  I am using the chrome browser.
*  My computer's OS is macOS.
*  I'm running Metabase locally built from master branch
*  My database is h2 sample dataset.
*  My Metabase version is latest from master

**Comment by tlrobinson** [comment]
Reproduced. Thanks for reporting.

**Comment by wihodges** [comment]
Not sure if my issue is related, just spun up fresh Docker instance of metabase but I cannot save pulse. Getting some console errors not loading pulse/form_input. Clicking on email or slack results in "Uncaught TypeError: Cannot read property 'email' of undefined"

**Comment by StaymanHou** [comment]
I encountered same issue here after upgrading to 0.2.20

**Comment by LarryZhang** [comment]
I have also got 'api/pulse/form_input' 500 error  {"message":"slack.com: unknown error","stacktrace":["integrations.slack$do_slack_request.invokeStatic(slack.clj:33)","integrations.slack$do_slack_request.doInvoke(slack.clj:31)","api.pulse$fn__30859$fn__30860.invoke(pulse.clj:88)","api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:222)","api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:219)","api.pulse$fn__30859.invokeStatic(pulse.clj:78)","api.pulse$fn__30859.invoke(pulse.clj:78)","middleware$enforce_authentication$fn__31538.invoke(middleware.clj:84)","api.routes$fn__31666.invokeStatic(routes.clj:57)","api.routes$fn__31666.invoke(routes.clj:57)","routes$fn__32636.invokeStatic(routes.clj:24)","routes$fn__32636.invoke(routes.clj:24)","middleware$log_api_call$fn__31626$fn__31628.invoke(middleware.clj:275)","db$_do_with_call_counting.invokeStatic(db.clj:470)","db$_do_with_call_counting.invoke(db.clj:464)","middleware$log_api_call$fn__31626.invoke(middleware.clj:274)","middleware$add_security_headers$fn__31585.invoke(middleware.clj:209)","middleware$bind_current_user$fn__31542.invoke(middleware.clj:104)"]}

**Comment by StaymanHou** [comment]
I also resolved the issue by cleaning up the slack setting.
