### ISSUE TITLE
Optional SQL parameter in custom actions is initially marked as required

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#29653]
**Describe the bug**
Optional SQL parameter in custom actions is marked as required initially

**To Reproduce**
_Create a custom `invoices` action [following the official documentation example](https://www.metabase.com/docs/latest/actions/custom.html)_
1. Click on the ellipsis menu next to an action name and then click on "Edit"
2. Click on the "cog" icon for the "Payment" parameter
3. Notice that it's being marked as required even though the SQL syntax suggests it should be optional `[[, payment = {{ payment }}]]`
![image](https://user-images.githubusercontent.com/31325167/228596479-a1097614-bed8-4ea7-a197-51c8659eaa7e.png)

**Expected behavior**
It would be nice if we can find a way to parse the syntax and the determine which parameters are (not) required.

**Information about your Metabase Installation:**
Metabase `x.46.0`

**Severity**
Nice to have.

**Comment by ranquild** [comment]
@nemanjaglumac we don't do that in the native query editor and I don't think we could/want to do it here

**Comment by nemanjaglumac** [comment]
@ranquild feel free to close the issue if it doesn't make sense or remove the "bug" label and make it a request for a new feature.

Both work for me.

**Comment by ranquild** [comment]
Closed we don't parse the SQL for native queries and that's why we can't proactively detect truly optional parameters
