### ISSUE TITLE
Crashing when trying to select sort fields

### ISSUE THREAD

**Issue by HelmiRifai** [metabase/metabase#2966]
When I expand the question builder to select sort options and click on the sort box it freezes my tab.
*  I am using the Chrome browser.
*  My computer's OS is Mac OSX El Captain.
*  I'm running Metabase [AWS Docker]
*  My database is Redshift.
*  My Metabase version is 0.18.1 .

**Comment by tlrobinson** [comment]
duplicate of #2859
