### ISSUE TITLE
Env var to disable SNI check in Jetty

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29660]
**Is your feature request related to a problem? Please describe.**
When we switched to Jetty 11, now you can't test a single HTTPS Metabase deployment locally, as SNI checks are not allowed for localhost. If we can disable all SNI checks https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html#og-protocols-ssl-sni via an env var, that would allow us to keep testing HTTPS on a localhost

**Describe the solution you'd like**
Add an env var like MB_JETTY_INSECURE that allows us to use HTTPS with SNI checks disabled in localhost

**Describe alternatives you've considered**
Tried to do this via JAVA_OPTS but it didn't work

**How important is this feature to you?**
Wanted to do some tests locally

**Additional context**
NA

**Comment by paoliniluis** [comment]
now that we're in Jetty 11, I think we can do HTTP2 from there closing https://github.com/metabase/metabase/issues/6385

**Comment by paoliniluis** [comment]
we didn't break anything here, you need to take care when generating the cert to match the uri

**Comment by paoliniluis** [comment]
@djuarezg the problem in the end is the certificates that don’t match the host name, have you checked this?

**Comment by djuarezg** [comment]
@paoliniluis Yes, but that is intentional, this is a docker instance, running in a machine with a hostname cert and then there is a HAproxy in front that handles the correct certificate. Basically without this flag, the previous behaviour is broken as there is no way of disabling this SNI check.

**Comment by djuarezg** [comment]
For reference, the keystore is created this way:

```
/bin/keytool -importkeystore -noprompt -destkeystore $JAVA_CERTS_FOLDER/$JAVA_APP_NAME/keystore.jks -srcstoretype PKCS12 -deststorepass $KEYSTORE_PASSWORD -destkeypass $KEYSTORE_PASSWORD -srckeystore $JAVA_CERTS_FOLDER/$JAVA_APP_NAME/{{ ansible_hostname }}.p12 -srcstorepass $KEY_P12_PASSWORD -srcalias {{ ansible_hostname }} -destalias {{ ansible_hostname }} -storetype PKCS12
```

And then used for `MB_JETTY_SSL_KEYSTORE`

Or was, as after updating this no longer works. See https://discourse.metabase.com/t/http-error-400-invalid-sni-when-upgrading-from-0-45-3-to-0-46-0/24599/13

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Same as @djuarezg, our Metabase is running in a docker instance with **localhost** healthcheck.
We should be able to disable SNI check for special cases.
