### ISSUE TITLE
run metabase frontend on win11 failed

### ISSUE THREAD

**Issue by gtrgeg** [metabase/metabase#29672]
I have installed yarn globally and configured environment variables, but when I run metabase, I still get an error message:

['cljs] ''yarn' is not recognized as an internal or external command,
['cljs] operable program or batch file.
[js'] The filename, directory name, or volume label syntax is incorrect.
[] ''yarn' is not recognized as an internal or external command,
[] operable program or batch file.
[] The filename, directory name, or volume label syntax is incorrect.
['cljs] 'yarn exited with code 1

why? How can I solve this problem?  Looking forward to your reply](javascript:;)💕

<img width="673" alt="wdaw" src="https://user-images.githubusercontent.com/47472797/228705359-fdad7d37-3ab2-4ffe-ac69-ac43699d572e.png">

**Comment by gtrgeg** [comment]
I have reinstalled yarn, and refreshenv

**Comment by paoliniluis** [comment]
Please try using wsl
