### ISSUE TITLE
Mongodb won’t work if version does fall into the “semantic-version-gte” pattern (Percona)

### ISSUE THREAD

**Issue by theyough** [metabase/metabase#29678]
**Describe the bug**
After upgrading to metabase version 0.46, I can't access to any mongodb databases.
From what I've seen, in metabase database, table `metabase_database`, the dbms_version is wrong, because mongodb doest not follow semantic version.

What i get from the `dbms_version` => {"version":"5.0.14-12","semantic-version":[5,0,15,-100]}  

**Logs**

```
2023-03-30 10:07:39,751 INFO driver.impl :: Initializing driver :mongo...
2023-03-30 10:07:39,753 INFO plugins.classloader :: Added URL file:/plugins/mongo.metabase-driver.jar to classpath
2023-03-30 10:07:39,755 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.mongo...
WARNING: random-uuid already refers to: #'clojure.core/random-uuid in namespace: monger.util, being replaced by: #'monger.util/random-uuid
2023-03-30 10:07:41,857 INFO driver.impl :: Registered driver :mongo  🚚
2023-03-30 10:07:41,897 INFO metabase.util :: Load lazy loading driver :mongo took 2.1 s
2023-03-30 10:07:41,916 ERROR metabase.task :: Error initializing task :metabase.task.persist-refresh/PersistRefresh
clojure.lang.ExceptionInfo: Input to semantic-version-gte does not match schema: 

	   [(named [nil nil nil (not ("Integer greater than or equal to zero" -100))] xv) nil]  

 {:type :schema.core/error, :schema [#schema.core.One{:schema [(constrained Int "Integer greater than or equal to zero")], :optional? false, :name xv} #schema.core.One{:schema [(constrained Int "Integer greater than or equal to zero")], :optional? false, :name yv}], :value [[5 0 15 -100] [4 2]], :error [(named [nil nil nil (not ("Integer greater than or equal to zero" -100))] xv) nil], :toucan2/context-trace [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection" {:toucan2.jdbc.query/sql-args ["SELECT * FROM \"metabase_database\""]}] ["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}] ["resolve connection" {:toucan2.connection/connectable :default}] ["resolve connection" {:toucan2.connection/connectable nil}] {:toucan2.pipeline/rf #object[clojure.core$map$fn__5931$fn__5932 0x658e0f88 "clojure.core$map$fn__5931$fn__5932@658e0f88"]} ["with compiled query" {:toucan2.pipeline/compiled-query ["SELECT * FROM \"metabase_database\""]}] ["with built query" {:toucan2.pipeline/built-query {:select [:*], :from [[:metabase_database]]}}] ["with resolved query" {:toucan2.pipeline/resolved-query {}}] ["with parsed args" {:toucan2.pipeline/query-type :toucan.query-type/select.instances, :toucan2.pipeline/parsed-args {:queryable {}}}] ["with model" {:toucan2.pipeline/model :metabase.models.database/Database}] ["with unparsed args" {:toucan2.pipeline/query-type :toucan.query-type/select.instances, :toucan2.pipeline/unparsed-args (:metabase.models.database/Database)}]]}
	at metabase.driver.util$fn__46893$semantic_version_gte__46898.invoke(util.clj:209)
	at metabase.driver.mongo$fn__120574.invokeStatic(mongo.clj:295)
	at metabase.driver.mongo$fn__120574.invoke(mongo.clj:290)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.util$features$iter__46856__46860$fn__46861.invoke(util.clj:199)
```

**To Reproduce**

**Expected behavior**

We should have a semantic version correct in `metabase_database` table
```
{"version":"5.0.14-12","semantic-version":[5,0,14]}
```

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  }
}
- Your databases: MongoDB
- Metabase version: 0.46
- Metabase hosting environment: Kubernetes / Docker
- Metabase internal database: postgre

**Severity**
Critical

**Additional context**

**Comment by theyough** [comment]
It seems, that only percona has this issue
![image](https://user-images.githubusercontent.com/7110516/228838965-d06cd1c2-ec7b-40f1-b96c-f9d0daf27001.png)

**Comment by paoliniluis** [comment]
so you're using a Percona MongoDB version? is that correct?

**Comment by marksull** [comment]
I surprised more people are not jumping up and down about this because it is a major issue.

I upgraded from 0.43.4 to 0.46.1 and within an hour, Metabase is unusable. Once Metabase scans a Mongo 5+ Database, nearly all features within Metabase are broken (see screenshot when I try and access Admin -> Database). Sidebar and most menus are broken.

![Screenshot 2023-04-18 at 2 47 34 pm](https://user-images.githubusercontent.com/1705633/232684710-9c4831e3-c9b8-4180-9348-e96ec272fc5a.png)

I restored from backup, upgraded to 0.46.1 again, and then manually performed an Admin -> Database -> Select DB -> Sync Database schema now. If I perform a sync on MongoDB 4.4.11 database, there is no issue. If I perform a sync on a MongoDB 5.0.13.11 Database, Metabase is dead.

I restored from backup again, upgraded to 0.45.3.1, and performed the same steps as in the previous step. There were no issues after a sync on either. I also performed a Rescan of the field values on both databases and had no issue.

So this issue is with MongoDB Databases (these are NOT Percona) above 5+ and is only evident in 0.46+ and it makes Metabase unusable and a restore is required.

**Comment by paoliniluis** [comment]
The problem then seem to be the builds (e.g. mongo 5.0.15-100  —> that “-100” is not an integer and that’s why it fails) we would never have caught it since we test with docker containers and their releases (5.0.15). Where can we get a mongodb to test those special releases? I cannot find those on their dockerhub cc @marksull @theyough

**Comment by marksull** [comment]
I don't know where the -100 is coming from. But in my case, the mongo being used that is creating the issue is MongoDB 5.0.13-11 Community

**Comment by marksull** [comment]
Maybe I lied above. Maybe the database I am connecting to is Percona, I don't know. Based on the version it looks like it might be: https://docs.percona.com/percona-server-for-mongodb/5.0/release_notes/index.html. But after connecting with MongoDB Compass it is reporting the version as "MongoDB 5.0.13-11 Community"

**Comment by theyough** [comment]
> The problem then seem to be the builds (e.g. mongo 5.0.15-100 —> that “-100” is not an integer and that’s why it fails) we would never have caught it since we test with docker containers and their releases (5.0.15). Where can we get a mongodb to test those special releases? I cannot find those on their dockerhub cc @marksull @theyough

@paoliniluis you can find the docker image here https://hub.docker.com/r/percona/percona-server-mongodb

**Comment by jbiel** [comment]
We hit this bug today in Metabase 0.46.2.

Docker image: `percona/percona-server-mongodb:4.0.28`
dbms_version: `{"version":"4.0.28-23","semantic-version":[4,0,29,-100]}`

**Comment by nateSias** [comment]
This is affecting my org as well, same Integer error.

I don't know clojure, but it seems to me that the feature switches are only comparing major and minor version numbers. Patching mongo.clj such that it only returns the first to elements of the versionArray might make sense. That said, I don't have any context for if the remaining elements are being leveraged elsewhere.

mongo.clj 183-188:
`(defmethod driver/dbms-version :mongo
  [_ database]
  (with-mongo-connection [^com.mongodb.DB conn database]
    (let [build-info (mg/command conn {:buildInfo 1})]
      {:version (get build-info "version")
       :semantic-version (get build-info "versionArray")})))
`

**Comment by jbiel** [comment]
We worked around this with a [single line change](https://github.com/jbiel/metabase/commit/d6f024ee3e25968789d5f07173d489f59a2cf66e) for now. This works in our environment (running Percona) but it may not work with other configurations.
