### ISSUE TITLE
Filter values no longer work inside single quoted strings

### ISSUE THREAD

**Issue by dsmith-digitalmint** [metabase/metabase#29690]
**Describe the bug**

After upgrading to version v0.46 queries that worked before are returning SQL errors that the shouldn't.

**To Reproduce**
A question with a simple SQL query:

`select replace(replace(phone, ' ', ''), '-', '') from phone_numbers where active=true and preferred=true and phone LIKE '+1 312%' limit 1;`

now returns the following error `error: The column index is out of range: 1, number of columns: 0`

note there have been no schema changes. When I take the "preview" SQL and paste it directly into psql I get a result.

**Expected behavior**

After upgrading the results should remain the same.

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/31456567/228886280-8159998d-61ea-4307-9713-4cffe869182a.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.9.0-11-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5 (Debian 11.5-3.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

I rolled back to v0.45.3 in the meantime

**Additional context**

**Comment by paoliniluis** [comment]
Thanks, can you provide the DDL and a sample row to test? seems you're using a filter there

**Comment by dsmith-digitalmint** [comment]
Sample row:
```
-[ RECORD 1 ]-------------+-------------------------------------
id                        | 54975
account_id                | 47122
phone                     | +1 800-603-6259
active                    | t
preferred                 | t
confirm_code              |
hash                      | 31fd6ee8-2be3-43d4-96ae-c815131d8633
created_at                | 2020-03-09 17:26:47.756648
updated_at                | 2020-03-09 17:26:47.756648
failed_deliveries         | 0
carrier                   |
carrier_type              | 0
subscriber                |
mcc                       | 0
mnc                       | 0
sms_marketing_opt_in      | f
sms_marketing_opt_in_date |
```

DDL:
```
 Table "public.phone_numbers"
          Column           |            Type             | Collation | Nullable |                  Default
---------------------------+-----------------------------+-----------+----------+-------------------------------------------
 id                        | integer                     |           | not null | nextval('phone_numbers_id_seq'::regclass)
 account_id                | bigint                      |           | not null |
 phone                     | character varying           |           | not null |
 active                    | boolean                     |           | not null | true
 preferred                 | boolean                     |           | not null | false
 confirm_code              | text                        |           |          |
 hash                      | uuid                        |           | not null | gen_random_uuid()
 created_at                | timestamp without time zone |           |          | now()
 updated_at                | timestamp without time zone |           |          | now()
 failed_deliveries         | integer                     |           |          | 0
 carrier                   | character varying           |           |          |
 carrier_type              | integer                     |           |          | 0
 subscriber                | character varying           |           |          |
 mcc                       | integer                     |           |          | 0
 mnc                       | integer                     |           |          | 0
 sms_marketing_opt_in      | boolean                     |           |          | false
 sms_marketing_opt_in_date | timestamp without time zone |           |          |
Indexes:
    "phone_numbers_pkey" PRIMARY KEY, btree (id)
    "phone_number_fk_unq" UNIQUE CONSTRAINT, btree (account_id, id)
    "phone_numbers_hash_key" UNIQUE CONSTRAINT, btree (hash)
    "phone_unq_acct_idx" UNIQUE, btree (phone, account_id)
    "phone_unq_active_idx" UNIQUE, btree (phone) WHERE active = true
    "phone_unq_preferred_idx" UNIQUE, btree (account_id, preferred, active) WHERE preferred = true AND active = true
Check constraints:
    "phone_number_preferred_active" CHECK (preferred = false OR preferred = true AND active = true)
Foreign-key constraints:
    "phone_numbers_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE
Referenced by:
    TABLE "accounts" CONSTRAINT "active_phone_number_fkey" FOREIGN KEY (phone_number_id) REFERENCES phone_numbers(id) ON UPDATE
CASCADE ON DELETE CASCADE
Triggers:
    tg_phone_numbers_updated_at BEFORE UPDATE ON phone_numbers FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column()
```

**Comment by dsmith-digitalmint** [comment]
Is there any other data I can provide to help? It seems like I have quite a few saved queries that are getting this error.

**Comment by mhkarimi1383** [comment]
I'm having the same problem, after upgrading to the latest version.

**Comment by fasaravi** [comment]
+1

**Comment by paoliniluis** [comment]
@dsmith-digitalmint the
```
select replace(replace(phone, ' ', ''), '-', '') from phone_numbers where active=true and preferred=true and phone LIKE '+1 312%' limit 1
```
query you sent and the screenshot don't make sense, the screenshot has a filter but the query doesn't, is that possible?

**Comment by mhkarimi1383** [comment]
> @dsmith-digitalmint the
> ```
> select replace(replace(phone, ' ', ''), '-', '') from phone_numbers where active=true and preferred=true and phone LIKE '+1 312%' limit 1
> ```
> query you sent and the screenshot don't make sense, the screenshot has a filter but the query doesn't, is that possible?

@paoliniluis 
I'm having the same problem with my questions with filters, and they will get fixed when I remove the usage of filters in queries. I actually did some testing by just working around with the quoting of the filters  but nothing changes

**Comment by dsmith-digitalmint** [comment]
> @dsmith-digitalmint the
> 
> ```
> select replace(replace(phone, ' ', ''), '-', '') from phone_numbers where active=true and preferred=true and phone LIKE '+1 312%' limit 1
> ```
> 
> query you sent and the screenshot don't make sense, the screenshot has a filter but the query doesn't, is that possible?

Here is the query: 

<img width="2233" alt="Screenshot 2023-04-17 at 8 26 19 AM" src="https://user-images.githubusercontent.com/31456567/232498265-f14e0bf0-9137-4e08-b95f-48d995e42312.png">

With the arrows I am calling attention to the variable/filter being used. The box in the image displays the SQL error. I copy pasted the query from metabase verbatim into my database and as you can see (black window) the query worked.

**Comment by tommaybe** [comment]
Seems I am suffering from the same issue with multiple questions. In my case its:
`select * from trades where created_at > current_timestamp at time zone 'UTC' - interval '{{MinutesAgo}}' minute`

This is reproducible with a simple table with just a timestamp column, so I will spare you the DDL.

As with @dsmith-digitalmint the generated SQL in GUI looks to be correct and executes when run manually:

![image](https://user-images.githubusercontent.com/657574/232771174-14e62cb3-901c-44fc-81d3-c6daf3f275b5.png)

**Comment by mhkarimi1383** [comment]
> Seems I am suffering from the same issue with multiple questions vs postgres. In my case its: `select * from trades where created_at > current_timestamp at time zone 'UTC' - interval '{{MinutesAgo}}' minute`
> 
> This is reproducible with a simple table with just a timestamp column, so I will spare you the DDL.
> 
> As with @dsmith-digitalmint the generated SQL in GUI looks to be correct and executes when run manually:
> 
> ![image](https://user-images.githubusercontent.com/657574/232771174-14e62cb3-901c-44fc-81d3-c6daf3f275b5.png)

me too, I'm having problem with some simple queries
(e.g. `SELECT * FROM user where name = '{{name}}'` this query is also getting errors)

What is going on?

**Comment by paoliniluis** [comment]
repro steps:
- create a SQL question (select * from people where created_at > now() - interval '{{some}} year')
- set up the filter as an integer
- try running it

**Comment by mhkarimi1383** [comment]
> @mhkarimi1383 your query is wrong, you need to do `SELECT * FROM user where name = {{name}}` and Metabase will add the single quotes

What about double quotes I think I'm having problem with them too, I will check and verify that again

**Comment by paoliniluis** [comment]
Double quotes are for column names in postgres

**Comment by mhkarimi1383** [comment]
> Double quotes are for column names in postgres

Oh I See :)
