### ISSUE TITLE
Incorrect data types for numeric values in text fields exported to Excel via subscription attachment

### ISSUE THREAD

**Issue by diegolabonia** [metabase/metabase#29708]
**Describe the bug**
Tables with numeric values in text fields, sometimes are using the incorrect data types when exported to Excel, but only in the subscription attachment. If the same table is exported manually, it works fine.

**Logs**
No errors in the log.
![image](https://user-images.githubusercontent.com/8793704/228978302-87534c73-2adb-46a4-9fc3-6b56feb80135.png)

**To Reproduce**
1. Create a new SQL Query. I've tested against a postgresql server, and the H2 sample database.
2. Use the following query:
`select
    '0001' as "this_is_not_-1",
    '4161' as "this_is_not_a_date",
    '02' as "this_is_not_an_hour"`

4. Export the result to Excel. The 'number format' is General, and the text shows as expected.
![image](https://user-images.githubusercontent.com/8793704/228981666-711cfbf1-f952-4a94-b530-df68d11957ee.png)

6. Save the query, and add it to a new dashboard.
7. Once in the dashboard click Save -> Subscriptions -> Email
8.  Add your user in the 'To:' field, and select to attach the result table in .xlsx format.
9. Click on 'Send email now', get email and check the attachment.
10. The 'number format' is not General, and the text has been converted to some other format.
![image](https://user-images.githubusercontent.com/8793704/228981716-08e1ef9e-1769-443b-a90a-70bf04c171b5.png)

**Expected behavior**
Both results should be the same, treating the numeric strings as text.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.15.0-56-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres",
      "csv",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
For us, it's just annoying. As a workaround, we are sending csv files in the subscriptions. It requires some extra steps from our users, but the format is ok.

**Comment by paoliniluis** [comment]
interesting, thanks, this is a derivative of https://github.com/metabase/metabase/issues/17753

**Comment by paoliniluis** [comment]
Raising the priority as, in case you're sandboxed, you can't change the base type (e.g. some tenants might have text id's, others number id's)
