### ISSUE TITLE
Can't set up alert on the first try

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29703]
**Describe the bug**
If you try to configure an alert on the first try when a query returns data, it won't work. You need to refresh the page to set it up

**Logs**
POST /api/alert 400 693.6 µs (0 DB calls) 
metabase-postgres      | {:errors {:card "value must be a map with the keys `id`, `include_csv`, `include_xls`, and `dashboard_card_id`."}}

**To Reproduce**
1) new->question->select the people table-> before saving click on the bell to set up the question, click on save and then set up the alarm. It will fail (as the POST to save the question hasn't been made)
2) refresh the page
3) set up the alarm, now it will work

Seems to be a state bug (we can't configure the alarm as the question hasn't been saved)

**Expected behavior**
I should be able to set up the alarm on the first try

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave
- Metabase version: 1.46.0

**Severity**
P3

**Additional context**
NA

**Comment by tanguyantoine** [comment]
That looks like a UI issue. 

If you setup the email configuration then the alerting screen becomes visible (allowing people to send to Slack or send email)

**Comment by oskhar1099** [comment]
> That looks like a UI issue.
> 
> If you setup the email configuration then the alerting screen becomes visible (allowing people to send to Slack or send email)

Hi, I cannot replicate what you are saying, can you explain with images please? I keep refreshing and I get the same error every time. Thanks
