### ISSUE TITLE
login doesn't redirect to original location

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2971]
If someone sends me a link to something like `https://metabase.my-website.com/dash/22` and I'm not logged in, clicking the link will take me to the login page. After I log in it takes me to the activity feed instead of redirecting to `/dash/22` as I would expect.

**Comment by tlrobinson** [comment]
Unless you guys consider this critical I'm going to move this one to 0.20.0 since we'd be fixing obsolete Angular routing code.
