### ISSUE TITLE
SSO mapping: users are removed from groups that are not mapped

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#29718]
**Describe the bug**
Users are being removed from groups that are not mapped.
We only ever add or remove people from Metabase groups that are mapped. If the Metabase group is not mapped to any SAML group, we shouldn't add or remove people.

**To Reproduce**
1. Setup SSO (SAML).
2. Create a group (not the admin group) and map it to a SAML group.
3. Add the user to the SAML group and also to the Metabase admin group.
4. When the user logs in, they are removed from the Metabase admin group.

**Expected behavior**
The user shouldn't be removed from the admin group (and any group that is not mapped)

**Screenshots/videos**
Behavior on 45.3
https://files.slack.com/files-pri/T078VCLCR-F050QU9QKFH/45.3.gif
Behavior on 46.0
https://files.slack.com/files-pri/T078VCLCR-F0517ULV8CU/46.0.gif

**Severity**
P0

**Comment by noahmoss** [comment]
Introduced by https://github.com/metabase/metabase/pull/27688
