### ISSUE TITLE
`Create` type of actions allows negative integers for the PK

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#29725]
**Describe the bug**
It is possible to enter negative integer to a row ID (primary key). Different things will happen based on the action type, but in both cases the API request is accepted.

**To Reproduce**
- Create a custom `invoices` action [following the official documentation example](https://www.metabase.com/docs/latest/actions/custom.html)
- Create basic actions in that same model

## **Scenario 1 - Simple (basic) actions**
1. Click on "Create" action
2. Enter `-2` for the row ID
3. Optionally enter some additional details for the additional fields
4. Click "Save"
5. The `POST` request goes through and the feedback message bubble shows up in the lower left corner
![image](https://user-images.githubusercontent.com/31325167/228603528-15cb0b93-d851-4925-ae1a-0855333375b7.png)

`POST /api/action/:id/execute`
```
// payload
{
  "parameters": {
    "date_received": null,
    "plan": null,
    "expected_invoice": false,
    "payment": 523,
    "account_id": null,
    "id": -2
  }
}

// response
{
  "created-row": {
    "ID": -2,
    "ACCOUNT_ID": null,
    "PAYMENT": 523,
    "EXPECTED_INVOICE": false,
    "PLAN": null,
    "DATE_RECEIVED": null
  }
}
```
6. Open the model and see that the row has actually been created
![image](https://user-images.githubusercontent.com/31325167/228604519-893f6dcc-172e-4cd7-85cd-e4925f58249d.png)

## Scenario 2 - Custom actions
1. Click the "play" icon to run the custom action
2. Enter some negative value in the `id` field and fill out the rest of the fields
3. Click on the blue button to submit/send/fire this action
4. The `POST` request goes through
5. You will see weird toaster message in the lower left corner that says "rows affected: 0"
![image](https://user-images.githubusercontent.com/31325167/229164229-e04bf1ea-ce7c-486f-956f-ec15c1496330.png)

`POST /api/action/:id/execute`
```
// payload
{
  "parameters": {
    "54c1cd9b-bec2-e589-3ff1-14b81582754e": "Foo",
    "5debc5e1-7ca2-597c-d93f-b415b8b4a375": "0",
    "f4a74817-ac7a-aab2-6cc9-afa1636c4a8f": "-15" // this is `id` (primary key)
  }
}

// response
{"rows-affected":0}
```

**Expected behavior**
Hard to tell.
Some databases accept unsinged integers as PK, some don't. The product team will come up with the desired behavior.

But we should (at the very least) NOT display `{"rows-affected":0}` in the success message in UI.

**Information about your Metabase Installation:**
Metabase `x.46.0`

**Comment by tsmacdonald** [comment]
@cdeweyx looks like this needs a bit more product input?

> Expected behavior
Hard to tell.
Some databases accept unsinged integers as PK, some don't. The product team will come up with the desired behavior.

**Comment by cdeweyx** [comment]
> But we should (at the very least) NOT display {"rows-affected":0} in the success message in UI.
This is a correctness issue, so the fix here as I see it is to just make sure we're not saying `rows-affected:0` when that's not the case.

> Some databases accept unsigned integers as PK, some don't. The product team will come up with the desired behavior.
This is a weird case, but I don't see a reason to block negative PKs for actions if the db supports it.

**Comment by tsmacdonald** [comment]
@nemanjaglumac I think this bug is outdated?

Here's what I'm getting:

![image](https://github.com/metabase/metabase/assets/784417/b85fa3ba-135f-4f6b-8dc5-6c56c6d2d636)

with this custom action:

![image](https://github.com/metabase/metabase/assets/784417/c99ef74e-f267-42e6-a5a4-5832224214fc)

and these values:

![image](https://github.com/metabase/metabase/assets/784417/e240c1a9-a9f0-4c6c-bbb3-32297388fdcc)

**Comment by tsmacdonald** [comment]
Just ran it from the model details page as well and it's the same: 
![image](https://github.com/metabase/metabase/assets/784417/b985c8a3-9772-45a3-bfa7-58b60f4bfbcb)
