### ISSUE TITLE
正在使用Honey SQL 1。这个方法在0.46.0中被废弃，并将在未来的版本中被删除。

### ISSUE THREAD

**Issue by niudecao1988** [metabase/metabase#29743]
[d46d0422-e6ad-4083-951c-ed6179e2d672] 2023-04-01T05:02:20+08:00 WARN metabase.driver.sql.query-processor.deprecated 警告。驱动程序:sqlserver正在使用Honey SQL 1。这个方法在0.46.0中被废弃，并将在未来的版本中被删除。
[d46d0422-e6ad-4083-951c-ed6179e2d672] 2023-04-01T05:02:20+08:00 WARN metabase.driver.sql.query-processor.deprecated 警告。驱动程序:sqlserver正在使用Honey SQL 1。这个方法在0.46.0中被废弃，并将在未来的版本中被删除。
[d46d0422-e6ad-4083-951c-ed6179e2d672] 2023-04-01T05:02:20+08:00 WARN metabase.driver.sql.query-processor.deprecated 警告。驱动程序:sqlserver正在使用Honey SQL 1。这个方法在0.46.0中被废弃，并将在未来的版本中被删除。
[d46d0422-e6ad-4083-951c-ed6179e2d672] 2023-04-01T05:02:20+08:00 WARN metabase.driver.sql.query-processor.deprecated 警告。驱动程序:sqlserver正在使用Honey SQL 1。这个方法在0.46.0中被废弃，并将在未来的版本中被删除。
[d46d0422-e6ad-4083-951c-ed6179e2d672] 2023-04-01T05:02:20+08:00 WARN metabase.driver.sql.query-processor.deprecated 警告。驱动程序:sqlserver正在使用Honey SQL 1。这个方法在0.46.0中被废弃，并将在未来的版本中被删除。
[d46d0422-e6ad-4083-951c-ed6179e2d672] 2023-04-01T05:02:20+08:00 WARN metabase.driver.sql.query-processor.deprecated 警告。驱动程序:sqlserver正在使用Honey SQL 1。这个方法在0.46.0中被废弃，并将在未来的版本中被删除。

**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.54",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "18.0.2-ea+9-Ubuntu-222.04",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "18.0.2-ea",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "18.0.2-ea+9-Ubuntu-222.04",
    "os.name": "Linux",
    "os.version": "5.19.0-35-generic",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.32-0ubuntu0.22.04.2"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```

**Comment by paoliniluis** [comment]
It's impossible to understand what the problem is here, please post on the discourse forum
