### ISSUE TITLE
Clicking Saved Questions option in data selector when instance have no questions leads to Raw Data option instead

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#29760]
**Describe the bug**
First, I think this bug rarely surfaces since it only appears when a Metabase instance doesn't have any saved questions, but have at least one model.

When that happens, if you try to create a new question, there'll be an option to select saved questions. After you click that it'll lead to Raw Data option instead (since there's no saved question at this point).

**To Reproduce**
Create a fresh Metabase instance.
1. Create a model
2. Click `+ New` -> `Question`
3. Click `Saved Question` option

**Expected behavior**
There is no **Saved Questions** option since there's no save question at this point.

**Screenshots/videos**
![bug no question then click question picker](https://user-images.githubusercontent.com/1937582/229558189-cf97a3d9-6892-4788-ae47-0be33aee33c4.gif)

**Information about your Metabase Installation:**

Metabase version: 7837070b4000c73d213615f7ab58752761d0c6c0

<details>
<summary>Diagnostic Info</summary>

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "13.3",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-03-31",
      "src_hash": "7d4e7684afe846f84b911658485c6b803ca383aa",
      "tag": "v1.45.1-SNAPSHOT",
      "branch": "29267-preserve-dashboard-parameter-values-when-saving-dashboards",
      "hash": "8aa6f38"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
</details>

**Severity**
Minor, it just makes new users confused.

**Comment by kamilmielnik** [comment]
It turns out there are 2 issues here:
1. the "saved questions" option should not be visible - that's what I'm working on
2. broken navigation within the data picker - I extracted it as a separate issue: #32225
