### ISSUE TITLE
[High Severity] date filters not working properly on Metabase post 0.46 update

### ISSUE THREAD

**Issue by gajanand-jm** [metabase/metabase#29783]
**Describe the bug**
After updating to 0.46, date filters in Metabase show -1 day data. Please refer to screenshot attached.

**To Reproduce**
1. Go to any data table
2. Use any date field to filter for specific dates
3. See data

**Expected behavior**
Should show correct data

**Screenshots**
<img width="627" alt="Screenshot 2023-04-04 at 12 53 09 PM" src="https://user-images.githubusercontent.com/91305327/229718272-3436ca50-2fa2-42b1-a077-5256fe6f19ac.png">

**Severity**
Extremely high - we use Metabase for day-to-day business reporting, impacting all those reports across multiple business units and stakeholders. It breaks the trust.

**Additional context**
We upgraded to v0.46 yesterday.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "athena",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}
```

**Comment by paoliniluis** [comment]
Please post the table DDL, I'm guessing this is an issue with the timezone, also post the SQL that Metabase generates

**Comment by gajanand-jm** [comment]
SQL generated by Metabase -

`SELECT "dwh_onboarding"."fact_savings_account_created"."user_id" AS "user_id", "dwh_onboarding"."fact_savings_account_created"."savings_account_created_at" AS "savings_account_created_at", "dwh_onboarding"."fact_savings_account_created"."savings_account_created_date_sk" AS "savings_account_created_date_sk", "dwh_onboarding"."fact_savings_account_created"."hour_of_the_day_sk" AS "hour_of_the_day_sk", "dwh_onboarding"."fact_savings_account_created"."etb_account_sk" AS "etb_account_sk"
FROM "dwh_onboarding"."fact_savings_account_created"
WHERE ("dwh_onboarding"."fact_savings_account_created"."savings_account_created_at" >= timestamp with time zone '2023-04-03 00:00:00.000+05:30')
   AND ("dwh_onboarding"."fact_savings_account_created"."savings_account_created_at" < timestamp with time zone '2023-04-04 00:00:00.000+05:30')
LIMIT 1048575`


We're converting all timestamps to IST in our data pipeline and using the same timezone in Metabase -

<img width="883" alt="Screenshot 2023-04-04 at 7 14 20 PM" src="https://user-images.githubusercontent.com/91305327/229812356-58c8703e-a5ca-42a3-9f15-2362fe90f28d.png">

**Comment by paoliniluis** [comment]
So you're doing double conversions, both in your data pipelines and then Metabase adds +5:30 hours to that. Check the SQL. Either remove the conversion on your data pipelines or in Metabase
