### ISSUE TITLE
Adding more than one field filter blows up the frontend in Mongo and MySQL

### ISSUE THREAD

**Issue by kayumuzzaman** [metabase/metabase#29786]
**Describe the bug**
When we write a native query by connecting a database table, we can use variable option inside our query. We can connect it to a variable by selecting values from dropdown of Variable type (ex: Text, Number, Field Filter). When I select the Field Filter to map this variable with a table field, got error. Also, if there is any previous query which is already connected to a table field with `Field Filter` variable type, if I want to change that field, error occured.

**Logs**
`Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
    at s.value (NativeQueryEditor.jsx:442:29)
    at s.value (NativeQueryEditor.jsx:457:12)
    at c (debounce.js:17:37)
react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at t.findDOMNode (react-dom.production.min.js:289:336)
    at h.value (ExplicitSize.jsx:39:25)
    at ExplicitSize.jsx:126:30
    at c (debounce.js:17:37)
VM1943 react_devtools_backend.js:2655 TypeError: Cannot read properties of null (reading 'toLowerCase')
    at Object.humanize (inflection.js:828:17)
    at s (strings.ts:34:10)
    at i.value (Schema.ts:18:21)
    at DataSelectorSchemaPicker.tsx:33:22
    at Array.map (<anonymous>)
    at Ke (DataSelectorSchemaPicker.tsx:32:22)
    at Jo (react-dom.production.min.js:153:146)
    at ya (react-dom.production.min.js:261:496)
    at mc (react-dom.production.min.js:246:265)
    at bc (react-dom.production.min.js:246:194)`

**To Reproduce**

1. Make a native query with a variable
2. Go to variable type to connect the variable with table field
3. Click on drop down & select field filter
5. See error

**Expected behavior**
Should work without error.

**Screenshots/videos**

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.15.0-46-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Severity**
It's blocking development with metabase, kinda stuck on it.

EDIT, repro steps:
- using 46, connect Mongo or MySQL sample databases
- New->SQL question
- in MySQL: 
```
select * from people where {{ one }} and {{ two }}
``` 
make both filters as field filters, when connecting the second the FE will blow up
- in MongoDB, selecting the people collection: 
```
[
  {
    "$match": {
      "$and": [
        {
          "state": {{ one }}
        },
        {
          "source": {{ two }}
        }
      ]
    }
  },
  {
    "$project": {
      "_id": "$_id",
      "address": "$address",
      "email": "$email",
      "password": "$password",
      "name": "$name",
      "city": "$city",
      "longitude": "$longitude",
      "state": "$state",
      "source": "$source",
      "birth_date": "$birth_date",
      "zip": "$zip",
      "id": "$id",
      "latitude": "$latitude",
      "created_at": "$created_at"
    }
  },
  {
    "$limit": 1048575
  }
]
```

**Comment by paoliniluis** [comment]
I just tried to reproduce but couldn't, can you try with the sample database? 
![image](https://user-images.githubusercontent.com/1711649/229786840-bd7480a3-166a-4fcf-b554-f69966e1f604.png)

**Comment by kayumuzzaman** [comment]
yeah, it works in sample database. can you provide some info how should I debug this issue for my case?

**Comment by EliasReuter** [comment]
Same problem here with v0.46.0 :/
It definitely happens when you try to add a second Filter of type "Field Filter"
<img width="911" alt="image" src="https://user-images.githubusercontent.com/40266095/229824568-ffe870d0-2a2d-407f-97d2-aef9748377b6.png">

**Comment by EliasReuter** [comment]
@paoliniluis can we reopen this issue?

**Comment by paoliniluis** [comment]
I can reopen this issue but if we can’t reproduce it will never be taken by our devs. I need you to identify what is the issue so we can reproduce it on our end

**Comment by paoliniluis** [comment]
Just tested with 2 field filters and the issue is not there 
![image](https://user-images.githubusercontent.com/1711649/230084108-59899cb1-bdf5-4ae8-9347-0dbdf0dd311a.png)

**Comment by 0123hoang** [comment]
My case may be related, non-root user cannot use fill filter, it say not have permissions.
When I pick model/question for filter:
![image](https://user-images.githubusercontent.com/43545058/230333385-9dcc6328-2de5-4b1f-8533-b14c669ee4fa.png)
It show error
![image](https://user-images.githubusercontent.com/43545058/230333600-ff2fee31-e606-464a-85b9-6661b6100ce6.png)
The log below
```
metabase_1  | 2023-04-06 16:17:36,326 WARN middleware.log :: GET /api/collection/root 403 10.6 ms (3 DB calls) 
metabase_1  | "You don't have permissions to do that."
```

**Comment by prigal** [comment]
0.46.1 Same problem.

**Comment by paoliniluis** [comment]
@prigal can you provide reproduction steps ?

**Comment by sfinity** [comment]
0.46.1 Same problem.
I'm using Maria DB (version 10.11.2).

**Comment by kayumuzzaman** [comment]
@paoliniluis I think you may need another dataset instead of sample dataset to produce it. I've tried to reproduce it in sample dataset, but can't. Whereas, it's happening in custom dataset.

**Comment by andyhernandez** [comment]
This has been driving me nuts since upgrading to 0.46.x - We have the issue on 0.46.0 and 0.46.1 only when using a native query with field filters.

**Replication steps:**

1. Select native query from menu

![image](https://user-images.githubusercontent.com/260001/231166149-a9ce45b2-7e51-402f-8d0a-d8fdd8d9daa3.png)

2. Write your desired query with a where clause, with 2+ conditions
![image](https://user-images.githubusercontent.com/260001/231166549-66c9ca6a-b5fe-41e1-ad17-b8636f1331f1.png)

3. For either one of the variables, select "Field Filter" and choose any table/field
4. For the remaining variable, select "Field Filter" and you will immediately see the following error:
![image](https://user-images.githubusercontent.com/260001/231167239-16fd068c-6200-4c6e-af16-2c1fb142f51a.png)

It happens 90%+ of the occurrences.  I've only been able to get around it by switching to another variable type prior to selecting Field Filter (rarely works).

**Comment by pushindm** [comment]
I'd like to confirm. Everything was fine before upgrading to 0.46.x versions. The reproductions steps are similar to others. Chrome error: `act-dom.production.min.js:209 TypeError: Cannot read properties of null (reading 'toLowerCase')`

**Diagnostic info**
`{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Ubuntu-0ubuntu120.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Ubuntu-0ubuntu120.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-125-generic",
    "user.language": "en"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.32-0ubuntu0.20.04.2"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-05",
      "tag": "v0.46.1",
      "branch": "release-x.46.x",
      "hash": "12a6e1d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Comment by paoliniluis** [comment]
Just reproduced, saw this issue with MySQL and Mongo, might happen with other databases

**Comment by sfaut** [comment]
Any news for the 0.46.2 release ? This bug terribly impacts our activity.

Thx !
