### ISSUE TITLE
Metadata is required when trying join on an SQL based questions

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#29795]
**Describe the bug**
I am getting mixed errors when i try to JOIN on the GUI with an SQL based question

**To Reproduce**

Example 1

1. Go to New -> SQL query -> `Select * FROM "PUBLIC"."ORDERS"` -> Save
2. Go to New -> Question -> Orders -> Join with above SQL question -> On ID = User ID

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/110378427/229807207-48e5e366-374a-4d0d-a287-0c13d0e552be.png">

Errors with `Cannot update binned field: query is missing source-metadata`

**Expected behavior**
I know this example doesn't make sense since the result should return an empty dataset but there are other usecases which should return results but we get the above error. So i tried to find the simplest example to replicate,

**Information about your Metabase Installation:**

Able to replicate on 1.45.3 and `master`

**Additional context**
It works when you turn into a model and add the required metadata:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/110378427/229808739-cdf295c8-efe9-45dc-819a-34bb1cd85d29.png">

**Comment by WiNloSt** [comment]
I think this is a FE issue.

1. Following the reproduction described in this issue will result in this query.
    ```json
    {
      "type": "query",
      "database": 1,
      "query": {
        "source-table": 2,
        "joins": [
          {
            "fields": "all",
            "condition": [
              "=",
              ["field", 37, null],
              [
                "field",
                "USER_ID",
                {
                  "binning": { "strategy": "default" },
                  "base-type": "type/Integer",
                  "join-alias": "Question 6"
                }
              ]
            ],
            "alias": "Question 6",
            "source-table": "card__6"
          }
        ]
      },
      "parameters": []
    }
   ```
2. Change from joining a native question to joining a GUI question based on Orders table results in this query.
     ```json
    {
      "type": "query",
      "database": 1,
      "query": {
        "source-table": 2,
        "joins": [
          {
            "fields": "all",
            "condition": ["=", ["field", 37, null], ["field", 43, { "join-alias": "Question 8" }]],
            "alias": "Question 8",
            "source-table": "card__8"
          }
        ]
      },
      "parameters": []
    }
    ```

We can see that there's no `binning` option in the second query. After manually removing the `binning` from the first query, the API returns a result as expected.
