### ISSUE TITLE
Error adding any summary fields to an existing aggregate questions

### ISSUE THREAD

**Issue by urkle** [metabase/metabase#29806]
**Read this before creating a bug report**
- if any of the sections are incomplete, we might close the bug report since we won't be able to reproduce it
- have you checked if the bug has already been reported? As we close duplicate reports, please search on the issue tracker if the problem has been reported before
- use as many screenshots or videos as possible to describe what you're seeing, all visual representations speak for themselves

**Describe the bug**
I have several questions based on another saved question. And when I first build the question it goes fine, however sometimes when editing the question (e.g. to add a new aggregate or grouping field) the UI fails to add the options.

e.g. selecting a new grouping field does not add the grouping field.
e.g. adding a new custom aggregate and clicking "done" does not add the custom aggregate.

Instead what I get is errors in the console
**Logs**
```
Uncaught (in promise) TypeError: t is null
    e icepick.min.js:1
    t updateQuestion.ts:175
    u runtime.js:63
    _invoke runtime.js:293
    A runtime.js:118
    an utils.ts:27
    a utils.ts:27
    ln utils.ts:27
    ln utils.ts:27
    dn updateQuestion.ts:121
[icepick.min.js:1:2124](webpack:///node_modules/icepick/icepick.min.js)
    pY steps.js:232
    l NotebookSteps.jsx:54
    (Async: promise callback)
    pY steps.js:232
    a NotebookSteps.jsx:54
    r NotebookSteps.jsx:54
    r NotebookSteps.jsx:54
    r NotebookSteps.jsx:54
    onChangeAggregation AggregateStep.jsx:39
    xZ AggregationPopover.jsx:87
    onDone AggregationPopover.jsx:346
    onClick ExpressionPopover.jsx:85
    React 12
    bind_applyFunctionN self-hosted:1686
    Qt self-hosted:1643
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    bind_applyFunctionN self-hosted:1686
    Zt self-hosted:1643
    React 9
    cc self-hosted:1409
    Zi React
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    _unlisten Router.js:109
    r createTransitionManager.js:228
    u createTransitionManager.js:83
    M AsyncUtils.js:74
    M AsyncUtils.js:80
    x getComponents.js:6
    x getComponents.js:30
    M AsyncUtils.js:79
    forEach self-hosted:203
    M AsyncUtils.js:78
    x getComponents.js:29
    u createTransitionManager.js:77
```

No log entries are added to the server log when I do this UI action.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Go open an existing query (that was based against another saved query or model)
2. Click on the show editor icon
3. Scroll down to the summarize section
4. click add new summarize field and choose custom.
5. enter "Sum([SomeField])" as the expression and enter a name (e.g. ARR)
6. click done.
7. the popup dialog dismisses and no new field is added, and the console shows the above error.

**Expected behavior**
The field to be added.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/101123/229859925-8e12cc3d-e64e-4e61-b94e-0f4ab690c2a4.png)
(after no new field)
![image](https://user-images.githubusercontent.com/101123/229859965-90c5221f-2ab1-4a3c-b37b-1af6f11a6622.png)
(only error in console)
![image](https://user-images.githubusercontent.com/101123/229860060-d0ab2355-dc10-42ef-86d1-94db1947b837.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

- Your browser and the version: Firefox 111.01
- Your operating system: macOS 12.6
- Your databases: Postgres
- Metabase version: 0.45.3 (has been happening since at least 0.44.0
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
It is pretty dang annoying.  The only work around so far is to
1. Remove the entire summarization
2. add in all the summary fields I want (this now works)
3. add the grouping fields, WHICH sometimes does not work (same behavior as above)
4. IF step 3 fails I then visualize the query and use the summary dropdown to add the grouping (Which surprisingly works)

Actually in all these cases adding summarization via the dropdown in the result view nearly always works, howevever that dropdown LACKS the "Custom expression" option.

**Additional context**

**Comment by paoliniluis** [comment]
Hi, I did the following:
1) create a question
2) create a question based on the previous question
3) in the second question add a custom expression on the summarization

but I didn't hit the issue, neither with firefox or chrome.

am I doing something wrong?

**Comment by ranquild** [comment]
Was fixed here https://github.com/metabase/metabase/pull/28945, with the repro test added. 

See line 175 in the affected version:
<img width="925" alt="Screenshot 2024-06-26 at 12 23 33" src="https://github.com/metabase/metabase/assets/8542534/723762a5-5aec-4dc8-9db0-3123028eccd1">
