### ISSUE TITLE
Show other series values on the tooltip even when unstacked

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#29816]
### Context
We recently shipped a new tooltip in visualizations, which included a view for stacked bar / pie / area charts with automated percentages. Now we're finding that the visibility of other series in a multi-series chart is pretty cool in general. Let's expand this more informative tooltip for all multi-series charts. Even if percentages aren't applicable, we just show the different series values for that point.

### Existing behavior

![Image](https://user-images.githubusercontent.com/16455495/229917395-3c356522-fa51-4882-8eed-3d2e123824e8.png)

### Proposed behavior

![Image](https://user-images.githubusercontent.com/16455495/229917443-323e63a2-4ba7-435b-8f0c-df4059638898.png)

### Questions
- For Design: Is there an elegant way to do this while not discarding other column values associated with the data point?

**Comment by zig** [comment]
Please at least make it configurable so that the existing behaviour remain an option. Showing non graphed values in the toolpip is a very useful feature in many cases.
