### ISSUE TITLE
Formatting issue in detail visualisation

### ISSUE THREAD

**Issue by gajanand-jm** [metabase/metabase#29827]
<img width="790" alt="Screenshot 2023-04-05 at 3 30 24 PM" src="https://user-images.githubusercontent.com/91305327/230048509-bfc89bf1-6947-4718-8951-2adce3160b4f.png">

**Comment by ignacio-mb** [comment]
Hi @gajanand-jm. I'm closing this issue as there is no other description that will help us find the issue and fix.

Please, feel free to create a new issue and use the [Bug Report template ](https://github.com/metabase/metabase/issues/new?assignees=&labels=.Needs+Triage%2CType%3ABug&projects=&template=bug_report.yml)
