### ISSUE TITLE
Export only content and appearance-related Settings

### ISSUE THREAD

**Issue by john-metabase** [metabase/metabase#29837]
Many Settings entities are inappropriate for transfer between instances of Metabase and should not be exported. We need to go through all settings and identify which ones should be exported explicitly.

**Comment by john-metabase** [comment]
@luizarakaki these settings seem like the candidates. I think some of these may still be inappropriate. Can you review this list?

```
humanization-strategy
native-query-autocomplete-match-style
site-locale
report-timezone-short
report-timezone-long
application-name
enable-xrays
admin-email
show-homepage-pin-message
source-address-header
enable-nested-queries
custom-geojson-enabled
start-of-week
custom-geojson
available-timezones
max-results-bare-rows
hide-embed-branding?
search-typeahead-enabled
enable-sandboxes?
application-font
available-locales
landing-page
enable-embedding
application-colors
application-logo-url
application-favicon-url
show-homepage-xrays
show-metabot
enable-whitelabeling?
show-homepage-data
map-tile-server-url
site-name
application-font-files
loading-message
report-timezone
show-lighthouse-illustration
persisted-models-enabled
enable-content-management?
subscription-allowed-domains
breakout-bins-num
available-fonts
custom-formatting
```

**Comment by luizarakaki** [comment]
I think these are fine... It is easy to generate a list of what we are not serializing?

**Comment by john-metabase** [comment]
That would be a much longer list, since we have about 160 settings. It may be tedious but maybe it would be a good idea to go through them all together.

**Comment by paoliniluis** [comment]
Why would you leave settings out? This should be picked by customers imho

**Comment by luizarakaki** [comment]
I agree that at some point we will let them decide what to transfer or not, but now we want to create the minimum version that works. We will get back to this when we have v2 ready
