### ISSUE TITLE
regenerate sample dataset

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#2985]
So I accidently deleted the sample dataset *oops*, how do I regenerate it without removing `metabase.db.h2.db`. Don't wanna lose all the queries/settings etc I have saved.

**Comment by camsaul** [comment]
Go to Admin > Databases and click "Bring the sample dataset back" (pictured below).

![screen shot 2016-07-19 at 6 29 00 pm](https://cloud.githubusercontent.com/assets/1455846/16972250/c79988f2-4dde-11e6-983f-fd1082b968f9.png)

**Comment by VikramTiwari** [comment]
hahaha My bad! Awesome thought to just add it there in the UI. 👍  Was rummaging through the code and found the task in project file. But this is perfect.
