### ISSUE TITLE
v46 version does not support the Date type in Oracle

### ISSUE THREAD

**Issue by Mrshanyan** [metabase/metabase#29853]
The v46 version does not support the Date type in Oracle. It is necessary to change the Date type in Oracle to TIMESTAMP

**Comment by paoliniluis** [comment]
Hi, I created a date type field in Oracle and I can see it:
![image](https://user-images.githubusercontent.com/1711649/230507925-8cc88b2e-3b66-41c2-a7ab-2bf841cd26c6.png)

same with aggregations
![image](https://user-images.githubusercontent.com/1711649/230507957-60ba2d02-3172-48ce-a11e-b1322de65ce1.png)

**Comment by Mrshanyan** [comment]
Cannot group statistics by hour
