### ISSUE TITLE
[Epic] Metabot v2

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#29859]
LLM based metabot.

**Links**
- product doc: https://docs.google.com/document/d/1kknBaY8ZoiFNsj3dI3d4Jo1xlD_s8Vq83PFXzi53NZI/edit#
- figma: https://www.figma.com/file/p3hH4w0JfhJ2Ipi1PzwxcR/Metabot-2.0?node-id=220-2966&t=4u7w3O1gFcWNwdIx-0

**Implementation Plan**

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/29646
- [ ] https://github.com/metabase/metabase/pull/29835
- [ ] https://github.com/metabase/metabase/pull/29843
- [ ] https://github.com/metabase/metabase/pull/29844
```

**Comment by transistormuncher** [comment]
Hi, this is an awesome feature and I would like to try it. I am running the docker image recommended in the email, but I cannot find the metabot feature. also I do not find a way to set my API credentials. Can you please give me some pointers to et started? or is this feature not available in the open source version? 

Thank you
