### ISSUE TITLE
 [MLv2] Remove or improve the "external op" representation

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#29867]
We all initially decided that the "external op" representation made sense but after seeing it in action the general consensus seems to be that it's really just a backdoor way to let the FE manipulate MBQL clauses directly and it's causing more problems than it solves. See these Slack threads for more information:

- https://metaboat.slack.com/archives/C04DN5VRQM6/p1680040079064039
- https://metaboat.slack.com/archives/C04DN5VRQM6/p1680306167604489

**Comment by camsaul** [comment]
As discussed here https://metaboat.slack.com/archives/C04DN5VRQM6/p1681035578274869?thread_ts=1680040079.064039&cid=C04DN5VRQM6 maybe we don't want/need to remove it entirely, but just need to define it's boundaries a little better

**Comment by metamben** [comment]
@camsaul should we close this ticket or is there something specific that should be done right now?

**Comment by camsaul** [comment]
@metamben let's go ahead and close it out for now, we can open a new issue if we decide we want to make further changes.
