### ISSUE TITLE
No date scope picker when grouping by custom date column in editor

### ISSUE THREAD

**Issue by BertrandToulas** [metabase/metabase#29864]
**Describe the bug**
When creating a custom column with a case() with an output that's a date from different columns (i.e. "if {condition}, then take date from this column, else take date from that column instead"), aggregating data by that column doesn't give me the date scope picker (day, month...), even though the entire column contains only dates. 

**To Reproduce**
1. Create a question with the editor
2. Pick a table from the Sample Database with at least 2 date columns
3. Create a custom column with a case() that outputs the value of one date column or the other depending on a condtion (see example below)
4. Create an aggregation based on that custom column

The grouping will work, but there will be no option to choose the date scope. See example below.

**Expected behavior**
A custom column with dates should have the same group by options as a standard date column.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/71009735/230425786-eea2c253-85fc-4fa3-8d8d-d189e5e7e30f.png)

Case 1 (MAIN ISSUE):
The `test_date_custom_column` returns a date from either of two date columns, but...
![image](https://user-images.githubusercontent.com/71009735/230425957-e2e6dd35-0feb-4879-8895-4b1717db3c8f.png)

![image](https://user-images.githubusercontent.com/71009735/230426878-3f167829-19d4-4f16-87ca-5e9bb653e75c.png)

There's no date scope picker at all here.

Case 2 (minor visual issue):
The `test` column returns either a date or nothing, but...
![image](https://user-images.githubusercontent.com/71009735/230429527-f03a2ef4-10c2-4814-bffc-c06a50204b5c.png)

![image](https://user-images.githubusercontent.com/71009735/230427376-0010f9e7-8887-46f2-99a5-d124d66d138f.png)

There is a date picker (and it is functional), but it doesn't display the currently selected date scope, only the arrow.

**Information about your Metabase Installation:**
Your browser and the version: Firefox 108.0.1
Your operating system: Windows 11 22H2 22621.963
Databases: BigQuery, Postgres, H2
Metabase version: 0.45.2

**Severity**
Some of our questions become impossible to do with the editor because of this issue.

**Comment by paoliniluis** [comment]
You're seeing https://github.com/metabase/metabase/issues/11371
