### ISSUE TITLE
[BE] Add more tests around resetting password and password complexity

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#29884]
We have [these two environment variables](https://www.metabase.com/docs/latest/people-and-groups/changing-password-complexity) that control the password complexity.

`MB_PASSWORD_COMLPEXITY` and `MB_PASSWORD_LENGTH`

I wanted to make sure those are respected in the UI when we reset someone’s password (without email being set up), and the good news is - they are! :tada:
Example:
```
MB_PASSWORD_COMLPEXITY=strong
MB_PASSWORD_LENGTH=25

;; Password that was generated on reset
BENairMpd2S90Boaa?S4p67Z7
```

- However, I couldn’t find any BE test that takes `MB_PASSWORD_LENGTH` into account.
- Furthermore, it seems that we're only checking for the `weak` option override [here](https://github.com/metabase/metabase/blob/master/test/metabase/util/password_test.clj#L72).
    - We should add a test for the `strong` option as well

- I saw the following warning that is related to the schema validation that is related to the password complexity (strong) and the special characters
```
[backend] 2023-04-07 12:26:45,091 WARN api.common :: Unexpected parameters at [:put "/:id/password"]: [:password]
[backend] Please add them to the schema or remove them from the API client
[backend] 2023-04-07 12:26:45,212 DEBUG middleware.log :: PUT /api/user/3/password 200 126.2 ms (6 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (3 idle, 0 queued) (48 total active threads) Queries in flight: 0 (0 queued)
```

**Comment by camsaul** [comment]
> However, I couldn’t find any BE test that takes MB_PASSWORD_LENGTH into account.

```sh
ack password-complexity -- test

test/metabase/util/password_test.clj
75:    (mt/with-temp-env-var-value [:mb-password-complexity "weak"]
```
