### ISSUE TITLE
Gauge chart?

### ISSUE THREAD

**Issue by rNianios** [metabase/metabase#2989]
Could I ask for you to add, if possible a gauge chart option?

Gauge charts are quite useful especially when you know a limit and they are being used in many dashboard systems.

Eg. I have 400 used licenses out of 600 usable. 

I know you could work around with pie charts and others as well but cauge I believe is the best representation.

![](http://docs.oracle.com/cd/E23943_01/bi.1111/e22254/img/xdo11g_le_gauge_ex1.gif)

**Comment by salsakran** [comment]
This is similar to #745

**Comment by mnlbox** [comment]
This issue is for more than 2 years later. Are you any plan to add gauge chart?
