### ISSUE TITLE
hosting on domain.com/metabase

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#2990]
How to reproduce:

- run metabase in docker container with port bindings
- run nginx's reverse proxy on top to bind `domin.com/metabase` to port exposed by container

Issue: App is available and starts serving requests. But nothing gets served since its looking for resources at `domain.com/app/*`

Not Sure: Could be the same for `/api` routes as well.

**Comment by camsaul** [comment]
Duplicate of #2090
