### ISSUE TITLE
Queries return unexpected results when CTE table contains column named 'user'.

### ISSUE THREAD

**Issue by TLazarevic** [metabase/metabase#29900]
**Describe the bug**
When query contains CTE with column with name 'user', query returns unexpected results. Changing the CTE column name yields expected results. Minimal reproducible example below.

**To Reproduce**
1. Start a new Native Query
2. Enter following SQL:
```
WITH results AS (

    SELECT
        'test' AS user
)

SELECT 
    user

FROM results
```
3. Run the query
4. Query returns 'metabase' as a result and displays 'current_user' as resulting column name

**Expected behavior**
'user' column with 'test' as value is returned by the query

**Screenshots/videos**

<img width="648" alt="Screenshot 2023-04-08 at 00 40 37" src="https://user-images.githubusercontent.com/18078190/230687641-b6721d14-95be-4beb-8e4e-2e5ce7dd671d.png">

<img width="648" alt="Screenshot 2023-04-08 at 00 40 52" src="https://user-images.githubusercontent.com/18078190/230688044-fcb5d573-0a66-4f6c-91f0-8dd753cefb71.png">

**Information about your Metabase Installation:**
Metabase: Version v0.46.1
Browser: Brave version 1.49.120

**Severity**
Not severe.

**Comment by paoliniluis** [comment]
you're missing the double quotes:
```
WITH results AS (
    SELECT
        'test' AS user
)

SELECT 
    "user"
FROM results
```

if you get the the user from a SQL query, it'll return you the user that's actually connected to the database, which is in fact the user you connected via settings->admin->databases
