### ISSUE TITLE
Allow stacked bar to have extra data on tooltip

### ISSUE THREAD

**Issue by nposystems** [metabase/metabase#29924]
**Is your feature request related to a problem? Please describe.**
I want to display extra data on the bar chart tooltip

**Describe the solution you'd like**
Allow choosing between the stacked bar tooltip style and the bar tooltip style (which displays all columns data)

**Describe alternatives you've considered**

**How important is this feature to you?**
It worked like that in the previous version of Metabase, and now customers are complaining that they are missing data in the tooltip.

**Additional context**
Example query which allows a bar chart:
`select 'Step 1' "location",'AD500' "P/N",'1000,1001' "Serials", 10 as value
union
select 'Step 2' "location",'AD500' "P/N",'1000,1001' "Serials", 7 as value
union
select 'Step 2' "location",'AD501' "P/N",'1006,1005' "Serials", 5 as value
union
select 'Step 3' "location",'AD500' "P/N",'1000,1001' "Serials", 4 as value
`

The "Serials" data is missing when viewing in stacked mode:
![image](https://user-images.githubusercontent.com/125442360/230886621-433ee093-2704-44f4-8784-e82f59ff374c.png)

The "Serials" data is visible when viewing in "Don't stack" mode:
![image](https://user-images.githubusercontent.com/125442360/230886716-9a3b8cb1-bbba-4da4-9066-4df863a8a003.png)

**Comment by zig** [comment]
It seemed possible in metabase version 0.45.4 (and actually was the only option). 

Is there any plan to put back this kind of tooltip for stacked bar ? It would only require to decorelate the tooltip type from the stacking style. In my case, it prevents me from upgrading metabase, since that was one of the most important feature (being able to see details when hovering on each area)

**Comment by asaf050** [comment]
HI @paoliniluis ,
This is not a duplicate of https://github.com/metabase/metabase/issues/29816 as this issue pertains to stacked bars, while the other concerns unstacked bars.
