### ISSUE TITLE
Getting a misleading 404 in the UI when running an action

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#29931]
While trying to execute an action that had a missing `,` in its definition, error I got back in the UI was `404 not found` instead of `ERROR: INSERT has more target columns than expressions\n Position: 88”,` that was present in the logs (and what you'd expect if the action definition is messed up and the server tries to run it). My gut says we're dropping the original error somehow.

<img width="862" alt="Screen Shot 2023-04-10 at 12 10 47 PM" src="https://user-images.githubusercontent.com/5248953/230954942-7a384fc7-66c9-42d0-971b-0fe55d241546.png">

**Comment by iethree** [comment]
I just experienced this on stats when uploading a CSV 🤔  I've never seen this, even with the exact same CSV locally.

![Screen Shot 2023-04-27 at 1 27 19 PM](https://user-images.githubusercontent.com/30528226/234970988-9616ebad-f09b-4436-b704-eb9f03ab4c8e.png)

**Comment by calherries** [comment]
@kdoh Do you have the exact query and driver you used? I can't repro this from your instructions. Tried on Postgres and H2.

**Comment by kdoh** [comment]
@calherries Yup hitting this on the postgres driver (our data apps specific db if that helps) 

I was able to [repro this just now with the following query.](https://stats.metabase.com/model/7106-access-requests/detail/actions/247) 
```sql
insert into blah (a, b, c,) values ({{a}}, {{b}}, {{c}})
```

You'll note the extra `,` and the fact that I'm referencing a non existent table. Both things should result in something other than a 404 not found message.

<img width="739" alt="Screen Shot 2023-05-24 at 10 24 41 AM" src="https://github.com/metabase/metabase/assets/5248953/70c775df-60d9-4862-8b62-1efa6c5c8224">

**Comment by calherries** [comment]
Looks like "404 page not found" happens on stats for any error that happens when executing a query action, for any database.

**Comment by calherries** [comment]
This was an issue effecting all cloud instances. 500 error details were hidden from users. 500 errors aren't excluded anymore after this change https://github.com/metabase/helm-charts/pull/48/files
