### ISSUE TITLE
Wrong field highlighted when editing model metadata if custom column added to left of column

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#29943]
**Describe the bug**
When editing model metadata on a model with a custom column in front of the non-custom columns, clicking a column name highlights the wrong column (seems to be offset by the number of custom columns).

**Logs**
<img width="311" alt="image" src="https://user-images.githubusercontent.com/8808703/230987894-8c999281-6b52-4f72-b6e4-3ace1ad2b90e.png">

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create and save a question from Accounts table in Sample Database with all columns.
2. Turn the question into a model
3. Edit query definition, add custom column "Seating type" with `CASE([Seats] = 1, "Single", [Seats] = 2, "Double", "Other")`
4. Move new column to be the first column
5. Save model
6. Edit metadata, select any column name, notice that the column 1 to the left is highlighted instead of the column selected.

**Expected behavior**
- clicked column is expected to be highlighted

**Screenshots/videos**
- After clicking "Seats" at the top, "Source" is highlighted instead:
- Have tried with 2 custom columns, and the offset is 2 instead of 1 column off

<img width="910" alt="image" src="https://user-images.githubusercontent.com/8808703/230988345-311040f7-7719-4ccc-b1e3-48f4224227e6.png">

**Information about your Metabase Installation:**
- Your browser and the version: Chrome
- Your operating system: MacOS
- Your databases: H2
- Metabase version: master (as of 2023-04-10) and 45.3.1

**Severity**
- Confusing user experience

**Comment by kamilmielnik** [comment]
In step 5 question stops being a model?

----

If in step 4 instead I edit metadata and then move the "seating type" column I get this:

![image](https://github.com/metabase/metabase/assets/6830683/25ea47be-7b34-4b94-945c-c3112c1f0613)

or this

![image](https://github.com/metabase/metabase/assets/6830683/74cb62aa-46e3-4069-a56f-a9a42c56d14d)

**Comment by kamilmielnik** [comment]
# Scenarios

I got all of the [above scenarios](https://github.com/metabase/metabase/issues/29943#issuecomment-1617930620) on video.

## Scenario 1

### Scenario 1 A - Question stops being a model

<details>
<summary>Video</summary>

https://github.com/metabase/metabase/assets/6830683/94a87387-6c61-4064-b815-612f051a4401

</details>


<details>
<summary>Reproduction steps</summary>

1. Create a question to query all data from Accounts table in Sample Database.
2. Visualize it.
3. Save it.
4. Turn the question into a model.
5. Click "Show editor" button
7. Add custom column called `Seating type` with `CASE([Seats] = 1, "Single", [Seats] = 2, "Double", "Other")`
8. Visualize it
9. Save
10. "Save new question" modal opens
11. Save it
14. The question is not a model

</details>

**Is this expected?**

### Scenario 1 B  - Question stops being a model

<details>
<summary>Video</summary>

https://github.com/metabase/metabase/assets/6830683/94a87387-6c61-4064-b815-612f051a4401

</details>

<details>
<summary>Reproduction steps</summary>

1. Create a question to query all data from Accounts table in Sample Database.
2. **Do not** visualize it.
3. Save it.
4. Visualize it.
5. Turn the question into a model.
6. Edit query definition.
7. Add custom column called `Seating type` with `CASE([Seats] = 1, "Single", [Seats] = 2, "Double", "Other")`
8. Save model
9. Move new column in between "Trial Converted" and "Active Subscription"
10. Click the play icon to reload results
11. Save
12. "Save new question" modal opens
15. Save it
16. The question is not a model

</details>

**Is this expected?**

## Scenario 2 - Error: "Cannot determine the source table"

<details>
<summary>Video</summary>

https://github.com/metabase/metabase/assets/6830683/30e89cbc-1bdf-4846-ada4-0d43f00a989b

</details>

<details>
<summary>Reproduction steps</summary>

1. Create a question to query all data from Accounts table in Sample Database.
2. Visualize it.
3. Save it.
4. Turn the question into a model.
5. Edit query definition
6. Add custom column called `Seating type` with `CASE([Seats] = 1, "Single", [Seats] = 2, "Double", "Other")`
7. Save model
8. Edit metadata
9. Move new column in between "Trial Converted" and "Active Subscription"
10. Click the play icon to reload results
11. Error - [screenshot](https://github.com/metabase/metabase/assets/6830683/2b90b851-37a6-41ea-9009-2c4e2b6bb3b6)
```
Cannot determine the source table or query for Field clause [:field "seating type" {:base-type :type/Text}]
```

</details>

## Scenario 3 - Error: "Column "source.Seating type" not found"

<details>
<summary>Video</summary>

https://github.com/metabase/metabase/assets/6830683/cbd90cc9-0ec5-4e6b-b727-fdd9a0fc4fdb

</details>

<details>
<summary>Reproduction steps</summary>

1. Create a question to query all data from Accounts table in Sample Database.
2. **Do not** visualize it.
3. Save it.
4. Turn the question into a model.
5. In the notebook editor add custom column called `Seating type` with `CASE([Seats] = 1, "Single", [Seats] = 2, "Double", "Other")`
7. Save as a new question (is this expected to save this as a new question? see scenario 3)
8. Turn the question into a model.
9. Edit metadata
10. Move new column in between "Trial Converted" and "Active Subscription"
11. Click the play icon to reload results
12. Error - [screenshot](https://github.com/metabase/metabase/assets/6830683/9251ac5b-641f-4ba2-9d27-6e5531028b5a)

```
Column "source.Seating type" not found; SQL statement:
SELECT "source"."ID" AS "ID", "source"."EMAIL" AS "EMAIL", "source"."FIRST_NAME" AS "FIRST_NAME", "source"."LAST_NAME" AS "LAST_NAME", "source"."PLAN" AS "PLAN", "source"."SOURCE" AS "SOURCE", "source"."SEATS" AS "SEATS", "source"."CREATED_AT" AS "CREATED_AT", "source"."TRIAL_ENDS_AT" AS "TRIAL_ENDS_AT", "source"."CANCELED_AT" AS "CANCELED_AT", "source"."TRIAL_CONVERTED" AS "TRIAL_CONVERTED", "source"."Seating type" AS "Seating type", "source"."ACTIVE_SUBSCRIPTION" AS "ACTIVE_SUBSCRIPTION", "source"."LEGACY_PLAN" AS "LEGACY_PLAN", "source"."LATITUDE" AS "LATITUDE", "source"."LONGITUDE" AS "LONGITUDE", "source"."COUNTRY" AS "COUNTRY" FROM (SELECT "source"."ID" AS "ID", "source"."EMAIL" AS "EMAIL", "source"."FIRST_NAME" AS "FIRST_NAME", "source"."LAST_NAME" AS "LAST_NAME", "source"."PLAN" AS "PLAN", "source"."SOURCE" AS "SOURCE", "source"."SEATS" AS "SEATS", "source"."CREATED_AT" AS "CREATED_AT", "source"."TRIAL_ENDS_AT" AS "TRIAL_ENDS_AT", "source"."CANCELED_AT" AS "CANCELED_AT", "source"."TRIAL_CONVERTED" AS "TRIAL_CONVERTED", "source"."ACTIVE_SUBSCRIPTION" AS "ACTIVE_SUBSCRIPTION", "source"."LEGACY_PLAN" AS "LEGACY_PLAN", "source"."LATITUDE" AS "LATITUDE", "source"."LONGITUDE" AS "LONGITUDE", "source"."COUNTRY" AS "COUNTRY" FROM (SELECT "PUBLIC"."ACCOUNTS"."ID" AS "ID", "PUBLIC"."ACCOUNTS"."EMAIL" AS "EMAIL", "PUBLIC"."ACCOUNTS"."FIRST_NAME" AS "FIRST_NAME", "PUBLIC"."ACCOUNTS"."LAST_NAME" AS "LAST_NAME", "PUBLIC"."ACCOUNTS"."PLAN" AS "PLAN", "PUBLIC"."ACCOUNTS"."SOURCE" AS "SOURCE", "PUBLIC"."ACCOUNTS"."SEATS" AS "SEATS", "PUBLIC"."ACCOUNTS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ACCOUNTS"."TRIAL_ENDS_AT" AS "TRIAL_ENDS_AT", "PUBLIC"."ACCOUNTS"."CANCELED_AT" AS "CANCELED_AT", "PUBLIC"."ACCOUNTS"."TRIAL_CONVERTED" AS "TRIAL_CONVERTED", "PUBLIC"."ACCOUNTS"."ACTIVE_SUBSCRIPTION" AS "ACTIVE_SUBSCRIPTION", "PUBLIC"."ACCOUNTS"."LEGACY_PLAN" AS "LEGACY_PLAN", "PUBLIC"."ACCOUNTS"."LATITUDE" AS "LATITUDE", "PUBLIC"."ACCOUNTS"."LONGITUDE" AS "LONGITUDE", "PUBLIC"."ACCOUNTS"."COUNTRY" AS "COUNTRY" FROM "PUBLIC"."ACCOUNTS") AS "source") AS "source" LIMIT 2000 [42122-214]
```
</details>

**Comment by kamilmielnik** [comment]
I'm not sure but it might a backend issue. 
If not, then it looks like `metabase-lib` issue ([might require loosening data matching logic](https://github.com/metabase/metabase/blob/271e237/frontend/src/metabase-lib/metadata/utils/models.ts#L169-L172)).

### Reproduction

Once the question gets to that state, the bug is 100% reproducible after refreshing the page.

https://github.com/metabase/metabase/assets/6830683/e1600df7-e47a-4d1c-a9dc-026161a07993

----

GET `/api/table/card__117/query_metadata` gives `fields[0].field_ref` equal to (1:04 in the video):
```json
["field", "seating type"]
``` 

POST `/api/dataset` gives `data.cols[0].field_ref` equal to (1:13 in the video):
```json
["field", "seating type", {"base-type": "type/Text"}]
```


_Note: `fields[0].id` is equal to `["field", "seating type", {"base-type": "type/Text"}]`_

If aforementioned objects were the same, frontend would properly [match data from both endpoints](https://github.com/metabase/metabase/blob/271e237/frontend/src/metabase-lib/metadata/utils/models.ts#L169-L172).

**Comment by qnkhuat** [comment]
Not an expert on MLv2 but I think field matching problems in general will be easily fixed using MLv2. @ranquild Could you take a look at this issue?

**Comment by kamilmielnik** [comment]
Reproducible in 0.48.7.
Cannot reproduce in `master` at da96c24f80.
Cannot reproduce in 0.49.0-RC2.

I can reproduce a different bug using similar reproduction steps: #39993
