### ISSUE TITLE
How to change fonts, colors, etc (CSS?)

### ISSUE THREAD

**Issue by rabit1** [metabase/metabase#2996]
Hi,

First, thank you for creating such a cool product. 

I can't seem to find any information on how to change Dashboard appearance. Is there anyway (preferably thru CSS) we can change the fonts, colors for Dashboard?  I need to change the size and color certain numbers based on their values.  Any tricks to do that?

Also, is the metabase server currently production ready?

Thanks again,
Regards,

**Comment by salsakran** [comment]
Hey @rabit1 -

Product ready is a loaded term. We're using it in production for a number of companies, and lots of others are using it as well.

We're still pre-1.0 and might do things that break compatibility if we need to to improve the product. 

Regarding Fonts/Colors, etc, not really. We spend a lot of time dialing in the visual design of the product and are going out of our way to make sure the design looks good on a variety of formats. You are, of course, welcome to compile your own build and change anything you want. We'd ask that you open source your changes if you decide to distribute them as per our license.
