### ISSUE TITLE
Mongo Data Models Not Working

### ISSUE THREAD

**Issue by rsatoor0** [metabase/metabase#29960]
**Describe the bug**
We are noticing issues with our Data Models in Metabase. Last week I noticed some java errors when I tried to click into the data model, today I am seeing the message "Data apps are not enabled." Further, when trying to create new questions or models, we are no longer seeing the option to join data this week.

These pieces of functionality were very important and useful for us and it greatly limits what we can do with Metabase not having them functioning as expected.
**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to the Pathway Collection at: https://pathway.metabaseapp.com/collection/6-pathway
2. Click on the "Absent Hours by Day" Model that is pinned
4. Clicking the Model itself gives empty data while clicking "Model Details" gives the "Data apps are not enabled" message
5. See error

**Expected behavior**
- Clicking Model Details should take me to a page where I can edit the model or visualize the results, I no longer see either
- Click the Model should show me data (for some reason I can still see data in the dashboard)
**Screenshots**
<img width="866" alt="image" src="https://user-images.githubusercontent.com/95401799/231020028-bebbb479-3ca1-421c-9a90-5c458fc73d2a.png">

<img width="416" alt="image" src="https://user-images.githubusercontent.com/95401799/231020059-326034b7-ba3b-426f-8896-a61772290710.png">

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
We recently started using Metabase to solve reporting/analytics. The hope is that this will move the needle on sales which has unfortunately stalled. Not being able to use Metabase's more advanced query features with Mongo greatly reduces Metabase's value for us. One of the primary reasons we went with Metabase early on was that there was a direct connection to Mongo. Other BI tools such as Quill do not have that functionality.

**Additional context**
Data is coming from Mongo

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-29",
      "tag": "v1.45.3.1",
      "branch": "release-x.45.x",
      "hash": "3b3097d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
Please send us an email to help at metabase dot com, as it seems you're a cloud customer
