### ISSUE TITLE
Use scientific notation on frontend multipliers

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29974]
**Is your feature request related to a problem? Please describe.**
When you need to modify numbers in the frontend, sometimes writing "1e11" is easier than writing "100000000000"

**Describe the solution you'd like**
support scientific notation in the numbers in the frontend

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by luizarakaki** [comment]
Is this a bug? Looks like a feature request

**Comment by sasher** [comment]
Hello!  This is a regression - this worked back v43.  Was broken in v45

**Comment by sasher** [comment]
Hello! This has gotten worse in v48.  Now we can't even copy-paste scientific notation in, which we could do previously in v46.

**Comment by paoliniluis** [comment]
@ignacio-mb

**Comment by Tony-metabase** [comment]
Closed with https://github.com/metabase/metabase/pull/41755
