### ISSUE TITLE
[MLv2] Implement function for breakoutable columns

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#29996]
`breakoutableColumns()`? Need to workshop the name a bit.

We need a function to power this UI:

![Image](https://user-images.githubusercontent.com/1455846/231246695-8db88d54-2e22-4614-8797-6d99b8d0996a.png)

This is mostly similar to `orderableColumns` with the following differences:

1. orderableColumns filters out columns that you're not allowed to order by, e.g. boolean columns; don't do that here
2. We need to support picking binning options and temporal breakouts (see below). I'm not entirely sure how we want this to work in this case. We already have some methods for applying temporal bucketing, but some more work still needs to be done (see #29704); binning is not yet implemented (#29705). But we'll also need some way for the FE to know that it can apply binning or temporal bucketing in the first place, in addition to the functions for applying it.

![Image](https://user-images.githubusercontent.com/1455846/231246989-df461184-9546-4b5e-97c2-46a033fc1491.png)

![Image](https://user-images.githubusercontent.com/1455846/231247045-2a64f587-7daa-4803-8631-8783b36bd891.png)

**Comment by camsaul** [comment]
`breakoutableColumns()`? Need to workshop the name a bit.

We need a function to power this UI:

![Image](https://user-images.githubusercontent.com/1455846/231246695-8db88d54-2e22-4614-8797-6d99b8d0996a.png)

This is mostly similar to `orderableColumns` with the following differences:

1. orderableColumns filters out columns that you're not allowed to order by, e.g. boolean columns; don't do that here
2. We need to support picking binning options and temporal breakouts (see below). I'm not entirely sure how we want this to work in this case. We already have some methods for applying temporal bucketing, but some more work still needs to be done (see #29704); binning is not yet implemented (#29705). But we'll also need some way for the FE to know that it can apply binning or temporal bucketing in the first place, in addition to the functions for applying it.


![Image](https://user-images.githubusercontent.com/1455846/231246989-df461184-9546-4b5e-97c2-46a033fc1491.png)



![Image](https://user-images.githubusercontent.com/1455846/231247045-2a64f587-7daa-4803-8631-8783b36bd891.png)

**Comment by camsaul** [comment]
discussion of how the API should look in Slack thread https://metaboat.slack.com/archives/C04DN5VRQM6/p1681235828658919

**Comment by metamben** [comment]
Fixed in #30316.
