### ISSUE TITLE
Displaying bar graph value totals

### ISSUE THREAD

**Issue by aleccostanza** [metabase/metabase#30006]
**Describe the bug**
Values displayed on bar graph on hover are incorrect. I suspect that because I am grouping on a multiple columns but only intend to display the total - Metabase is picking a value from the table instead of aggregating the intended column. Given the example query:
```
select
month
,utm_source
,count(*)
from table
group by 1,2

```
The graph (should and does) displays the aggregate of all utm_source count per month. On hover it seems to show a single (random) utm_source count value rather than the total. 

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/108759285/231273773-34990bba-48ac-4612-80e4-634902f52ade.png)

**Comment by brunobergher** [comment]
When hovering a specific series, the tooltip shows the value for that series up top, with the other values for that point in the X axis below the line. How else should this work?

Or did you expect to the a "total" line below the last series ("INVITE", in this case)?

**Comment by aleccostanza** [comment]
The 'Total' is >27k. The sum of all these is obviously not 27k. The blue value, 'Contribution's, on the graph is actually closer to 15k but it is showing a value of 70. It should show the actual total no?

**Comment by luizarakaki** [comment]
@aleccostanza can you give us reproduction steps using the sample database? I wasn't able to reproduce this issue.

**Comment by luizarakaki** [comment]
Not possible to reproduce on 47. If someone has reproduction steps, please let us know and we will try again
