### ISSUE TITLE
Sporadic "we're a little lost..." pop-up when scrolling up and down my query after expanding a row

### ISSUE THREAD

**Issue by aarthi-subramanian** [metabase/metabase#30039]
**Describe the bug**
Random bug where if you scroll up and down (using arrow keys) in the query editor on your query, a `we're a little lost...` pop-up comes. Im just trying to scroll, im not hitting "run".

**Logs**
Couldn't get JS frontend console in time. 

**To Reproduce**
1) create a new sql query (select * from people)
2) run it
3) expand the first row
4) click on the sql query and press the up arrow

**Expected behavior**
When you write a sql query and hit run, and go back to refine the query. You are allowed and no interruption by this weird modal.

**Screenshots/videos**
https://user-images.githubusercontent.com/47357846/231531682-db62837a-edfd-4e5a-be2a-92d49daee0f7.mov

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+0-adhoc..source",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+0-adhoc..source",
    "os.name": "Linux",
    "os.version": "5.4.84",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-07",
      "tag": "v0.46.1-SNAPSHOT",
      "branch": "release-x.46.metabot-alpha",
      "hash": "b96b662"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

THis is just very annoying and messing up screenshares during meetings with the team.

**Additional context**

**Comment by paoliniluis** [comment]
Hi, what's the browser? does this happen on incognito?

**Comment by aarthi-subramanian** [comment]
Hi! 
* Browser is chrome
* I just tried and not happening in incognito mode, but i mentioned above also that unsure what the trigger is/ seems to happen sporadically.
* Ive also seen this issue happen to others during their screenshares

Hope this helps!

**Comment by luizarakaki** [comment]
This happened to me too only after I expand a single record.
https://www.loom.com/share/642206966717455194ecd578e5b99137

**Comment by EmmadUsmani** [comment]
The same thing happened to me as well a couple of months ago, I filed an issue https://github.com/metabase/metabase/issues/28624

**Comment by paoliniluis** [comment]
@luizarakaki you made my day, thanks for giving us the tip to reproduce this

**Comment by wulffZ** [comment]
I also have this issue rarely, perhaps some more diagnostic info can uncover a pattern.

`{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.6+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.6+10",
    "os.name": "Windows Server 2019",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.11.2-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-28",
      "tag": "v0.46.2",
      "branch": "release-x.46.x",
      "hash": "8967c94"
    },
    "settings": {
      "report-timezone": "Europe/Amsterdam"
    }
  }
}`

**Comment by sicarul** [comment]
I'm getting the same issue and the console complains about autocomplete:
<img width="1904" alt="image" src="https://github.com/metabase/metabase/assets/4952116/20d8fe55-60d8-4f3d-95bd-0a5bd78abded">

Seems like the editor is trying to load an empty autocomplete with this url:
`https://<hostname>/api/database/2/autocomplete_suggestions?substring=`

**Comment by cughi** [comment]
Also happens when you highlight a part of your query to run it independently. Thanks in advance.

**Comment by shirleymercury** [comment]
This also happens to me whenever I use my up/down arrow keys to text edit.

**Comment by likeshumidity** [comment]
Something similar happens in `master` on hash: `c45c9be` where using the up or down arrow keys in Native SQL editor brings up the row detail modal, but its indexes are sometimes out of sync so it searches for a row not in its cache.
