### ISSUE TITLE
Filtering Error MongoDB

### ISSUE THREAD

**Issue by RColaco11** [metabase/metabase#3004]
If this is a bug report, please fill in the blanks:
-  I am using the Chrome browser.
-  My computer's OS is Windows 8.1.
-  I'm running Metabase on Herkou 
-  My data is in a mongoDB 3.2v database. 
-  My Metabase version is the newest.

I understand I need to convert My string fields into BSON Ids inorder to filter based on an Id but i am undable to succesfully do so. 

```json
[{
        "$project": {
            "company_id": "$company_id",
            "sign_in_count": "$sign_in_count"
        }
    }, {
        "$match": {
            "sign_in_count": {
                "$gt": 0
            },
            "company_id": "56b5ba3d8a2d7028d7000002"
        }
    }, {
        "$project": {
            "_id": "$_id",
            "group": {
                "company_id": "$company_id",
                "sign_in_count": "$sign_in_count"
            }
        }
    }, {
        "$group": {
            "_id": "$group"
        }
    }, {
        "$sort": {
            "_id": 1
        }
    }, {
        "$project": {
            "_id": "$_id.fname",
            "company_id": "$_id.company_id",
            "sign_in_count": "$_id.sign_in_count"
        }
    }, {
        "$sort": {
            "sign_in_count": -1,
            "company_id": 1
        }
    },



    {
        "$lookup": {
            "from": "companies",
            "localField": "company_id",
            "foreignField": "_id",
            "as": "company_array"
        }
    }, {
        "$unwind": "$company_array"
    }, {
        "$project": {
            "Name": "$company_array.name",
            "sign_in_count": "$sign_in_count"
        }
    }
]
```

Here is my code, I can figure out where to change the code so that the fields are filterable by company ID

Thanks.

**Comment by camsaul** [comment]
@RColaco11 I would assume you need to do [something like](https://docs.mongodb.com/manual/reference/method/ObjectId/)

```json
ObjectID(""56b5ba3d8a2d7028d7000002")
```

in your query.

That being said, figuring out the right way to write a MongoDB query isn't really a Metabase issue.

**Comment by camsaul** [comment]
@RColaco11 did that answer your question?

**Comment by camsaul** [comment]
@RColaco11 as mentioned above using `ObjectId(...)` should do what you need. Feel free to reöpen this issue if you have any further questions.
