### ISSUE TITLE
Adding filter of summarized field grouped by latitude and longitude on a map breaks breadcrumbs

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#30056]
**Describe the bug**
- Filtering on aggregate column after binning on a map breaks the Database > Table breadcrumbs

**Logs**
<img width="741" alt="image" src="https://user-images.githubusercontent.com/8808703/231587277-a9817d6b-9527-4ba2-b2c9-6c291e385fba.png">

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Use People from Sample Dataset to create a map with count of rows summary grouped by latitude and longitude (binned)
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/8808703/231585380-95ef33f9-8b5d-4b7c-8f20-0396b4742496.png">

2. Add a filter on Count > 2
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/8808703/231585467-30090bda-6133-44ca-80e5-39081f464527.png">

3. Even after saving question and refreshing page the table name "People" still does not appear on top left after database name:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/8808703/231586350-57734db4-b06a-4cb9-9c6d-69198ed9d46f.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/8808703/231586309-162c63bf-80dc-4321-863a-00f8d6f18261.png">

**Expected behavior**
- Expect Database and Table breadcrumbs under question name to continue working.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

- Metabase version: 45.3.1, 46.1, and master (as of 2023-04-12)

**Severity**
- customer reported issue

**Comment by likeshumidity** [comment]
Related to:
- https://github.com/metabase/metabase/issues/30057
- https://github.com/metabase/metabase/issues/30058

**Comment by kamilmielnik** [comment]
This is not in progress. I'm working on #30057.

**Comment by kamilmielnik** [comment]
Note: the metric is being set to longitude/latitude here: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/lib/settings/utils.js#L43
