### ISSUE TITLE
Pin Map not working - MissingKeyMapError 

### ISSUE THREAD

**Issue by asenyshyn** [metabase/metabase#3005]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Windows 10.
*  I'm running Metabase 0.18.1 running on dev server in docker metabase/metabse and it is using the Postgres.
*  My data is in a Postgres database.
*  My Metabase version is 0.18.1.

I got Metabase up and running in docker on my dev server, and I have a problem with the pin map.
If I connect to the Metabase locally with ssh tunnel - pin map is working just fine. 
However when I use the Metabase from dev.myapp.com(which is the same instance as from ssh tunnel) I get:

```
Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIt0ABEAAAABQDwAAQABAAAAAAAAAAAAAAAAAAAAA…CwKGBmIIpVWLACJWGwAUVjI2KwAiNEswkKAwIrswsQAwIrsxEWAwIrWbIEKAZFUkSzCxAEAisA' because it violates the following Content Security Policy directive: "font-src 'self' fonts.gstatic.com themes.googleusercontent.com ".

Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
```

I cannot find where should I configure Google API key. Could anyone please suggest how to fix this?

**Comment by camsaul** [comment]
@tlrobinson why would we get a [MissingKeyMapError](https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error)?

**Comment by camsaul** [comment]
related: #3034 (documentation says we need to configure Google Maps API Key, which is no longer true)

**Comment by tlrobinson** [comment]
I'm not sure, I've never seen that error, just this warning https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

It's possible Google has a quota for API calls based on your domain.

We're planning on replacing Google Maps with Leaflet/OpenStreetMaps (#2737) soon. In the meantime if you're having trouble with this you'll need to add an API key here https://github.com/metabase/metabase/blob/279b614dc9002f6ac748ac86bc70cd0e11ab3457/resources/frontend_client/index_template.html#L36

This will require you either build from source or edit the jar (in which case you'll need to remove our signature, e.x. `zip -d metabase.jar 'META-INF/*.SF' 'META-INF/*.RSA'`)

**Comment by tlrobinson** [comment]
Yeah, looks like Google Maps recently removed keyless access entirely, I just haven't run into it because I usually use localhost which they apparently allow. :( https://googlegeodevelopers.blogspot.com.au/2016/06/building-for-scale-updates-to-google.html

We'll look into adding an API key setting.

**Comment by asenyshyn** [comment]
Wow, that was fast! Thank you!
