### ISSUE TITLE
Adding filter of summarized field grouped by latitude and longitude on a map changes selected metric

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#30057]
**Describe the bug**
- Filtering on aggregate column after binning on a map breaks the map and changes selected metric, can be fixed by changing back to a map and editing the selected metric to reselect aggregate column

**Logs**
<img width="741" alt="image" src="https://user-images.githubusercontent.com/8808703/231587277-a9817d6b-9527-4ba2-b2c9-6c291e385fba.png">

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Use People from Sample Dataset to create a map with count of rows summary grouped by latitude and longitude (binned)
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/8808703/231585380-95ef33f9-8b5d-4b7c-8f20-0396b4742496.png">

2. Add a filter on Count > 2
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/8808703/231585467-30090bda-6133-44ca-80e5-39081f464527.png">

3. Map disappears, Source Table name disappears (top left), and clicking gear to edit visualization shows 3 columns to add that already exist.
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/8808703/231585687-bed1d30b-7634-4a22-bf60-a2fbd24b098a.png">

4. Reselect Map as the visualization type, but then the tooltips no longer show Count as the metric, they show Latitude or Longitude (depending on which was added to the group by first)
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/8808703/231585829-8ce90e6c-ea5f-4f5f-80f3-bd2d3227cb69.png">

**Expected behavior**
- Expect filter of summarized field not to change the metric setting of the visualization.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

- Metabase version: 45.3.1, 46.1, and master (as of 2023-04-12)

**Severity**
- customer reported issue

**Comment by likeshumidity** [comment]
related to:
- https://github.com/metabase/metabase/issues/30056
- https://github.com/metabase/metabase/issues/30058

**Comment by kamilmielnik** [comment]
I have investigated this issue, and what happens is that after adding a filter, `data.cols[0].source` and `data.cols[1].source` (the longitude and latitude columns) will change from `"breakout"` to `"fields"` (coming from POST `/api/card/:id/query`). Because of this the [default metric detection logic](https://github.com/metabase/metabase/blob/fa76af8/frontend/src/metabase/visualizations/lib/settings/utils.js#L43) will [accept](https://github.com/metabase/metabase/blob/fa76af8/frontend/src/metabase-lib/types/utils/isa.js#L117-L118) latitude and longitude columns as metrics.

**Comment by kamilmielnik** [comment]
> 3. Map disappears

That particular issue has been extracted as a separate one: #32075. That's the one I was actually working on, so I will unnasign myself here.

It also turns out that this issue is [a Pixel Police issue](https://metaboat.slack.com/archives/C057T1QTB3L/p1688374951631179), so adding back to the inbox.
