### ISSUE TITLE
[MLv2] Keep `effective_type` and `semantic_type` opaque and add helper functions like `isPK`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#30054]
@ranquild suggested this, see this thread for more info https://metaboat.slack.com/archives/C04DN5VRQM6/p1681320908628419

Right now `display-info` includes `:semantic_type` and `:effective_type`: 

https://github.com/metabase/metabase/blob/9d0d93225ff8f075541e25fa74b6a28aac00754d/src/metabase/lib/metadata/calculation.cljc#L226-L227

and these get converted to Strings in the JS version, `displayInfo()`; as @ranquild noted, this encourages people to do stuff like

```js
col.semantic_type === "type/some_type"
```

instead of using `isa()`:

https://github.com/metabase/metabase/blob/473758e3d20b0db14af712a4168c6ffec601b604/shared/src/metabase/types.cljc#L363-L375

e.g.

```js
import * as Types from "cljs/metabase.types";

Types.isa(someType, "type/Text"); 
```

So at the very least we should leave these two columns as Cljs Keywords so you have to use `isa()` and can't treat them like normal strings.

Better still I think would be to stop returning those in `displayInfo` at all, and just have helper functions that operate directly on the opaque columns, e.g.

```js
isPK(opaqueColumn)
```

Then the FE doesn't even need to know that `semantic_type` or `effective_type` or anything like that exist **at all**. This would for example unlock the refactor to add a new `relation_type` column we've been discussing for years:

- https://github.com/metabase/metabase/issues/14054
- https://github.com/metabase/metabase/issues/15486

> add relation_type and migrate type/FK and type/PK over to this. this gets into a lot of front end stuff.

# Functions to add

In the short term, something like `Lib.isa(opaqueColumn, Type.PK)` would be a good start. Note that this would need to be able to be smart about `effective_type` vs `semantic_type`: something with a semantic type of `:type/Address` but an effective type of `:type/Text` should still return `true` for `isa(col, Type.TEXT)`.

In terms of more-specific helper functions, I think porting all of the stuff from 

https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase-lib/types/utils/isa.js

would cover most of our bases, there is also 

https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase/query_builder/components/filters/modals/BulkFilterList/utils.ts#L6

but the purposes of that is not entirely clear to me.

**Comment by metamben** [comment]
Done in #30146.
