### ISSUE TITLE
[Epic] Offer option to display all data labels within stacked charts

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#30051]
[Product doc](https://www.notion.so/metabase/Offer-option-to-display-all-data-labels-within-stacked-charts-d89e678e9c204d2cb03eb5132c3e5131)

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/13096

**Comment by Torx999** [comment]
Hi all, is there any planned release date for this feature?

**Comment by cdeweyx** [comment]
> Hi all, is there any planned release date for this feature?

Thanks for checking in! No planned date as of now but this is on our radar for the next release or two. You can see more generally how we're thinking about things on the [public roadmap](https://www.metabase.com/roadmap).

**Comment by cdeweyx** [comment]
Dupe of #41980
