### ISSUE TITLE
[MLv2] We need to validate that references you're adding to a query are actually valid for that stage

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#30084]
See also: #30083

Right now pMBQL is pretty forgiving and lets you add almost any sort of reference to a query as long as the type information is correct; You can do something like 

```clj
{:lib/type :mbql/query
 :stages [{:source-table 1, :filter [:= {...} [:field {..., :join-alias "X"} 2] 3]}]}
```

even tho there is no join `X`, or use a `[:field {...} <string-name>]` reference in the first stage of a query, or use `[:aggregation {...} 0]` in a query with no aggregations, etc. 

We should disallow as much of these things as we can in the stage schemas themselves. Some more advanced validation will require a metadata provider, but I suppose we should be able to do those checks against the query as a whole if it has `:lib/metadata`, right? If it's not feasible to do these checks in the actual schemas then maybe we can do them in some other way. 

Maybe some sort of general `(valid-reference-for-stage? query stage-number reference)` function would make sense for implementing this. TBD

**Comment by snoe** [comment]
To me this describes two problems.

1. Existing, persisted queries that are in some way invalid.
2. Keeping a query valid as it is changed.

I think 1 queries just explode when run? But in v2 we'd be unable to even render it for them to fix.

I think the clean for 1 should be as simple as dropping any invalid particular filter in :filters etc - many things could get dropped from the persisted query but this should be doable [after](https://github.com/metabase/metabase/issues/30084)

**Comment by camsaul** [comment]
See also https://github.com/metabase/metabase/issues/29612
