### ISSUE TITLE
Rename "Dimension" in the SQL Template Variable type dropdown

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3009]
As per @metabase/core-developers conversation, we should rename it a "field filter" instead to more accurately describe what it is.

**Comment by camsaul** [comment]
is this supposed to be part of 19?

**Comment by salsakran** [comment]
yes.

**Comment by salsakran** [comment]
better than re-writing a bunch of docs, etc after we launch and people are using the feature.

**Comment by salsakran** [comment]
imo, this is primarily related to the contents of the dropdown, not necessarily everything behind the hood.
