### ISSUE TITLE
[MLv2] Use foreign key column names for group names coming from `group_columns`

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#30109]
Right now, `group_columns` uses the table display name as a group name. This behavior is different from what we have on `master` right now. As an example, the sample Orders table has foreign keys for the Products and People tables. The column picker on `master` groups columns into Order, Product, and User (notice it's not People or Person):

<img src="https://user-images.githubusercontent.com/17258145/232041069-41d7c239-5970-4e7f-96cc-8440b604a7d5.png" alt="Notebook editor's column picker" width="360px" />

@mazameli explained the reason behind that:

> This was a really intentional decision: we’re precisely showing the foreign key column’s name, with “ID” stripped out. This is so that if e.g. your “People” table e.g. contains both customers as well as suppliers, and the Orders table had FK columns to both of those (Customer ID, Supplier ID), then this list here would show you both Customer as well as Supplier so that you could e.g. filter to find orders with customers from california but with suppliers from new york (and, notably, it would not list the name of the table, People). 

We should make `group_columns` follow that approach as well. Perhaps that should better be another property of the column group; I'm pretty sure we'd need the actual table display name anyway. On the other hand, maybe the FK column based name should actually be a display name, and the table display name should live in another property. Feedback is very welcome

**Comment by bshepherdson** [comment]
`metabase-lib/DimensionOptions/DimensionOptions.ts` line 55 is the heart of the logic - each foreign key on the table of interest creates a column group (a "section" in the v1 parlance). `fk.field.targetObjectName()` is the magic that strips off the ID. I'll add that logic into the v2 implementation.
