### ISSUE TITLE
Expanding the sidebar causes crashes and slow performance with large numbers of collections.

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#30115]
**Describe the bug**
When we try to expand a collection on the sidebar with ~70k child collections, the application freezes and crashes. When clicking the sidebar, it either eventually loads after 3-4 minutes or crashes entirely. 

**To Reproduce**
1) Loaded ~75k collections into my local environment using 
```
for i in {1..100000}
do
curl --location '[http://localhost:3000/api/collection](http://localhost:3000/api/collection)' \
--header 'X-Metabase-Session: '<USER KEY>' \
--header 'Content-Type: application/json' \
--data '{
"parent_id": 13,
"authority_level": null,
"color": "#509EE3",
"description": null,
"name": "big boi '$i'"
}'
done
```
2) Open the parent folder containing the large number of collections in the sidebar

**Expected behavior**
It should quickly load all collections in the sidebar, and not crash the application.

**Screenshots/videos**

https://user-images.githubusercontent.com/25306947/232072608-407b2859-0fca-444e-85ef-c42886786523.mov

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20+36",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20+36",
    "os.name": "Mac OS X",
    "os.version": "13.2.1",
    "user.language": "en",
    "user.timezone": "Europe/Tallinn"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-04-12",
      "src_hash": "79fe0a9a6ab5333c2a36a273e169222fe5c3f19b",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "29971-fe-editing-a-dashboard",
      "hash": "18e97ea"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Could be really severe depending on the size of the datasets

**Additional context**

**Comment by tsmacdonald** [comment]
@cdeweyx what's the solution here?

1. I don't think it's close to possible to create 75k child collections through the UI. Never mind the human time, I think the UI to create the child collections would freeze up.

2. I wouldn't want to use a Metabase that had 75k collections expanded

3. I'd be surprised if a browser could handle displaying that.


Should collections be paginated? Or should there be a maximum number of children for a collection? Or something else? If somebody has tens of thousands of collections, what problem are they actually trying to solve and what's a better way of doing it?

**Comment by oisincoveney** [comment]
@tsmacdonald @cdeweyx I remember this was one of the first issues I opened here, where I noticed that opening a large collection (>25 or so) was slowing down the app in a big way, but that seems to have been solved. @calherries and I took a look at some larger collections and it seems like things are working smoothly on the sidebar and the collections page (for realistic sizes of collections) and a 75k child collection may be unrealistic. 

What do y'all think? I'm happy to close this if y'all agree with that

**Comment by cdeweyx** [comment]
I'm on board

**Comment by paoliniluis** [comment]
@cdeweyx I agree that having 75K collections is completely unrealistic, but there's a clear performance impact when there are many collections in place. I think we should check this as it will impact the performance of large metabase implementations. Here is a sample of a trace that shows how the larger amount of collections can peg the rendering of the frontend https://drive.google.com/file/d/1pjzIB0CfBcHGDI2PhjBGE86yBSLE0IC_/view?usp=drive_link
