### ISSUE TITLE
Unable to summarize models

### ISSUE THREAD

**Issue by pranayat** [metabase/metabase#30112]
**Describe the bug**
Trying to do a simple summarization on a model results in the error - `Input to trim-sql-query does not match schema: [0;33m [nil (named (not (instance? java.lang.String a-clojure.lang.PersistentArrayMap)) query-str)] [0m`

The error does not go away even after removing the summarization and I have to go to the 'edit query definition' view and rerun the query to see the model data again.

**To Reproduce**
Create a native MongoDB query as below
```
[
  {
    "$project": {
      "location": "$location",
      "name": "$name",
      "restaurantType": "$restaurantType"
    }
  },
  {
      "$addFields": {
          "lng": { "$arrayElemAt": [ "$location.coordinates", 0 ] },
          "lat": { "$arrayElemAt": [ "$location.coordinates", 1 ] }
      }
  },
  {
    "$limit": 1048575
  }
]
```
Convert this to a model.
Do a simple summarization on this model. Eg. counts by restaurantType

**Screenshots/videos**

https://user-images.githubusercontent.com/6952713/232070835-7fd53c91-380c-4c23-90df-8c305ceef095.mov

![image](https://user-images.githubusercontent.com/6952713/232071362-c408d651-8247-406e-af6b-9ac14329b708.png)

Information about your Metabase Installation:
v0.46.1
Browser - Google Chrome Version 112.0.5615.49 (Official Build) (arm64)

**Severity**
Unable to summarize any models

**Comment by IvanClementino** [comment]
Same issue when using this query:
`[
  {
    $project:
      {
        created: {
          $toDate: "$_id",
        },
      },
  },
]`

![image](https://user-images.githubusercontent.com/71457970/233207209-3b2a2d15-d42b-4b81-b280-749e865958dc.png)

**Comment by venkatar-huma** [comment]
Another similar issue reported [here](https://discourse.metabase.com/t/error-while-referring-mongodb-native-query-in-another-question/24978).

**Comment by sairayapureddy** [comment]
Another similar issue [Error while referring mongodb native query in another question](https://discourse.metabase.com/t/error-while-referring-mongodb-native-query-in-another-question/24978)

**Comment by alxsbn** [comment]
Hi ! we have the same issue with mysql and MB 0.46.1

**Comment by vladanpaunovic** [comment]
I can also confirm that this is happening with **any MongoDB native query**.

I created a very simple question for which summarisation worked fine. After converting it to a native query it started throwing the error. This leads me to an assumption that this error is **affecting all MongoDB users**.

## Steps to reproduce

### 1. Create a simple MongoDB question
<img width="985" alt="Screenshot 2023-05-16 at 07 51 17" src="https://github.com/metabase/metabase/assets/29886766/919cc58f-de8b-4a8f-aefc-fbf3c4797fc4">

### 2. Convert it to a native query
<img width="653" alt="Screenshot 2023-05-16 at 07 51 59" src="https://github.com/metabase/metabase/assets/29886766/a24fa781-df20-4946-9d73-5684c4734131">

### 3. Click on _"Explore results"_
<img width="1170" alt="Screenshot 2023-05-16 at 07 53 54" src="https://github.com/metabase/metabase/assets/29886766/4b581304-71e2-4a6f-af4a-7a7e5959c3e1">

### 4. Error
```
Input to trim-sql-query does not match schema: 
[0;33m [nil (named (not (instance? java.lang.String a-clojure.lang.PersistentArrayMap)) query-str)] [0m
```

<img width="1176" alt="Screenshot 2023-05-16 at 07 54 02" src="https://github.com/metabase/metabase/assets/29886766/77e13444-d4b3-40a1-96c9-9fe24cdd4e8c">


Hope this helps. Cheers!
