### ISSUE TITLE
Search on large collections can be slow (>4-5 seconds)

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#30116]
**Describe the bug**
In the search bar, we aren’t cancelling search requests when the user types in new characters in the search string. Search requests are taking about 6 seconds each on large collections.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1) Loaded ~75k collections into my local environment using 
```
for i in {1..100000}
do
curl --location '[http://localhost:3000/api/collection](http://localhost:3000/api/collection)' \
--header 'X-Metabase-Session: '<USER KEY>' \
--header 'Content-Type: application/json' \
--data '{
"parent_id": 13,
"authority_level": null,
"color": "#509EE3",
"description": null,
"name": "big boi '$i'"
}'
done
```

2) Try to search for a collection in the search bar, and examine the network tab in the dev tools to see how long the search (using the `/search` endpoint takes.

**Expected behavior**
Search should load more quickly (ideally, instantaneously) with any size of collection set

**Screenshots/videos**
https://user-images.githubusercontent.com/25306947/232075869-b36c72fe-021b-4e3d-aa87-9077049a2ae5.mov

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20+36",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20+36",
    "os.name": "Mac OS X",
    "os.version": "13.2.1",
    "user.language": "en",
    "user.timezone": "Europe/Tallinn"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-04-12",
      "src_hash": "79fe0a9a6ab5333c2a36a273e169222fe5c3f19b",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "29971-fe-editing-a-dashboard",
      "hash": "18e97ea"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**
Could be pretty severe depending on the number of collections that the average user has. For larger companies this could be a big problem quickly.

**Additional context**

**Comment by calherries** [comment]
@oisincoveney, can we close this?

**Comment by oisincoveney** [comment]
Yep, we can close this for now. If it becomes an issue in the future then we can always open this up again.
