### ISSUE TITLE
Serialization won't respect column sorting in pivot tables

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30134]
**Describe the bug**
We don't seem to respect the column orders (viz settings) defined in the pivot tables when loading them in another instance

**Logs**
NA

**To Reproduce**
Using https://github.com/paoliniluis/metabase-serialization as the base
1) create a pivot table like 
![image](https://user-images.githubusercontent.com/1711649/232174494-3e7cc868-b99d-442a-8156-d3b9691b22bb.png)
2) then go to the viz settings and change the order of the source column
![image](https://user-images.githubusercontent.com/1711649/232174520-fc304b2b-5696-41b0-9a61-0eebf6167aa5.png)
3) now dump and load
4) go to the destination and see that the order was not respected
![image](https://user-images.githubusercontent.com/1711649/232174542-1938d04c-8b91-4646-ac65-1d6149de296f.png)

**Expected behavior**
We should respect the order that the users defined when loading the cards in the destination

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Metabase version: 1.46.1

**Severity**
P2

**Additional context**
NA

**Comment by laura-radaelli** [comment]
We are experiencing this issue and a related one: the pivoting column is not respected. 

The same seems to happen in the example reported here: after import (step 4.), "Product -> Category" is listed under Rows, even though, at the source, it was listed under Columns.
