### ISSUE TITLE
not all modals respond to click out or esc key close fn calls.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#3013]
in working on #3008 I noticed that some modals aren't properly closing when expected when events from the ``OnClickOutsideWrapper`` are called. One note, this seems specific to modals and not popovers.

a partial list so far:

- [ ] user edit modal in admin
- [ ] post save "would you like to add this to a dashboard"
- [ ] add to dashboard modal
- [ ] about metabase

... more to come

**Comment by tlrobinson** [comment]
This is due to not providing an `onClose` prop to those modals. When you use `ModalWithTrigger` or `PopoverWithTrigger` that is handled for you, but not when you use `Modal` or `Popover` directly.
