### ISSUE TITLE
Resizing columns in pivot tables in serialization breaks the card on load

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30130]
**Describe the bug**
Seems like the new column width in the pivot table card breaks the metadata on the load with
"Error: Invalid metadata returned for cell 2:
        x:255, y:0, width:NaN, height:30"

**Logs**
Frontend error
Error: Invalid metadata returned for cell 2:
        x:255, y:0, width:NaN, height:30

**To Reproduce**
Using https://github.com/paoliniluis/metabase-serialization as the base
1) create a pivot table on the origin
2) resize one column
3) dump and load
4) see the card breaking on destination

**Expected behavior**
We shouldn't break the cards :(

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.46.1

**Severity**
P1

**Additional context**
NA

**Comment by paoliniluis** [comment]
Compared both viz settings in origin and destination, both are the same
Compared the API responses in origin and destination, both are the same...

clearly there's something I'm not seeing here

**Comment by AG-Teammate** [comment]
Having the same issue

**Comment by npfitz** [comment]
As far as I can tell, this is happening because when we load the data to the destination, we our field references in visualization settings end up being paths rather than field IDs. This causes [udateValueWithCurrentColumns](https://github.com/metabase/metabase/blob/1490fd9cc8d3b7a9ea97aabb49eccb9547dc073a/frontend/src/metabase/visualizations/visualizations/PivotTable/settings.ts#L129) to strip out the settings and all the columns end up in the `rows` partition (rather than 1 column being in `columns`)

**Comment by npfitz** [comment]
From what I can tell, on loading the serialized data we need to resolve the field IDs in the `pivot_table.column_split` map. We already do this for `table.columns` and `column_settings` properties in viz settings [here](https://github.com/metabase/metabase/blob/eb3a42f6cd9655eed51870e22e7aca362e1d6346/enterprise/backend/src/metabase_enterprise/serialization/load.clj#L417) Example of `pivot_table.column_split` below 
```
{
    "rows": [
        [
            "field",
            "/databases/Sample Database/schemas/PUBLIC/tables/PEOPLE/fields/SOURCE",
            {
                "source-field": "/databases/Sample Database/schemas/PUBLIC/tables/ORDERS/fks/USER_ID"
            }
        ],
        [
            "field",
            "/databases/Sample Database/schemas/PUBLIC/tables/ORDERS/fields/CREATED_AT",
            {
                "temporal-unit": "year"
            }
        ]
    ],
    "columns": [
        [
            "field",
            "/databases/Sample Database/schemas/PUBLIC/tables/PRODUCTS/fields/CATEGORY",
            {
                "source-field": "/databases/Sample Database/schemas/PUBLIC/tables/ORDERS/fks/PRODUCT_ID"
            }
        ]
    ],
    "values": [
        [
            "aggregation",
            0
        ]
    ]
}
```
