### ISSUE TITLE
Pivot table with 2 group by's gets loaded incorrectly on serialization

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30133]
**Describe the bug**

**Logs**
Please include JavaScript console logs (open the browser dev tools and check the "console" tab) as well as the server logs (Metabase logs that you can get from Settings -> Admin -> Troubleshooting -> Logs) around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
Using https://github.com/paoliniluis/metabase-serialization as the base
1) create a question like the following:
![image](https://user-images.githubusercontent.com/1711649/232173743-dc046390-d2c4-4fdf-b08c-8f7ccf4f765e.png)
2) view it as a pivot table and make sure it's configured like
![image](https://user-images.githubusercontent.com/1711649/232173845-6a26a359-a2e5-4003-895c-e1d668172337.png)
3) now dump and load in destination
4) see that it changed
![image](https://user-images.githubusercontent.com/1711649/232173874-3d163d31-43cd-441c-8251-9cd3a0b8de46.png)

**Expected behavior**
It should be loaded in the same way as it was saved in the origin

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Metabase version: 1.46.1

**Severity**
P2

**Additional context**
NA

**Comment by piranha** [comment]
Same as #30134, looks fine to me now.
