### ISSUE TITLE
Extend `/recent_views` endpoint with search functionality or create a new one

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#30140]
**Is your feature request related to a problem? Please describe.**
For https://github.com/metabase/metabase/issues/29666 FE needs to know the last visited dashboard within last 24 hours for current user. I can imagine BE doesn't store `last_visited` flag per model as it doesn't make sense, but I discovered another endpoint `GET /api/activity/recent_views` which contains the recent activities of the user. The problem is: endpoint returns only 5 most recent visited entities and dashboards can be missed.

**Describe the solution you'd like**
Add additional parameters to the `/api/activity/recent_views` endpoint (or create a new one with this functionality), endpoint should be able to return the recently viewed dashboard (having search parameters like `model` and `limit` will make this component flexible for further requirements if any). For this particular epic I need to get dashboards visited during last 24hrs only, it can be calculated on frontend, but if it's easy to add such parameter to BE endpoint, we can do it as well (thoughts are welcome)

Example

```
GET /api/activity/recent_views?model=dashboard&limit=1
```

**Describe alternatives you've considered**
probably we can reuse `/search`

**How important is this feature to you?**
It's a requirement for the epic for 47 release

**Additional context**
No

**Comment by paoliniluis** [comment]
Related to https://github.com/metabase/metabase/issues/27216

**Comment by paoliniluis** [comment]
⚠️  https://github.com/metabase/metabase/pull/29631 ⚠️

**Comment by calherries** [comment]
Closed by https://github.com/metabase/metabase/pull/30323
