### ISSUE TITLE
Ability to disable the sidebar for users in Admin settings

### ISSUE THREAD

**Issue by marshallsteeves** [metabase/metabase#30145]
**Is your feature request related to a problem? Please describe.**
Users would like the ability to disable the sidebar at the admin-level based around permissions. This would allow more direct control to which content is viewable to third parties.

**Describe the solution you'd like**
Ability to disable the sidebar at the permissions level in the Admin panel 

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by customer 

**Additional context**
N/A

**Comment by brunobergher** [comment]
What sidebar? Is this about embedding? Very unclear, closing.
