### ISSUE TITLE
Race condition after deleting the Sample Database

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#30152]
We've noticed very high level of flakiness in an E2E test that makes sure you can 1. delete the Sample Database and 2. Restore it afterwards. Upon some investigation and internal discussion @ranquild thinks this might be a frontend-related issue.

For the reference, this is how to delete the database: https://www.metabase.com/docs/latest/databases/connecting#deleting-databases
It should be possible to restore the Sample Database even when it gets deleted, and the UI should look like this:
![image](https://user-images.githubusercontent.com/31325167/232476002-85b73a80-cbef-42d3-9cb4-c3b938c8987b.png)

Once you confirm you want to remove the Sample Database, a `DELETE` request is fired. It's followed (stragely) by two `GET` requests.
- One is `GET /api/database?exclude_uneditable_details=true` and
- The other one is `GET /api/database`

![image](https://user-images.githubusercontent.com/31325167/232559938-7878eeef-fec8-4bb3-8e44-4e9126c54369.png)

However, if we take a look at this screenshot from a failed Cypress E2E test, we can see that the order of these `GET` requests is reversed.
![image](https://user-images.githubusercontent.com/31325167/232475480-a9f980e4-e7e1-468b-912d-9879b2bef63c.png)

This results in a Sample Database not actually being deleted, even though the `DELETE` request happened.

**Comment by iethree** [comment]
found the problem: often, the DELETE api request doesn't resolve until AFTER the first GET request is fired

![Screen Shot 2023-04-18 at 11 10 55 AM](https://user-images.githubusercontent.com/30528226/232853198-2a66c484-1421-477f-8a43-91e2dae85b40.png)
