### ISSUE TITLE
Add LIMIT to get metadata of native queries

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30170]
**Describe the bug**
Tracking another bug I found that when you do a native query like `select * from people` (don't run it, just save it), we send that query to the DB to get the metadata, but we should send the query with a LIMIT of 1 at least

**Logs**
E.g. I'm using Trino to get the query statistics (BTW: this query was never run, it was only saved):
![image](https://user-images.githubusercontent.com/1711649/232632358-963086f4-9f43-4847-8b1e-f269c6b830a9.png)

Look at the input and output rows
![image](https://user-images.githubusercontent.com/1711649/232632398-2b4507c3-a0c8-4740-98c8-881a635754c7.png)

the same happens in postgres if you run it with "log_statement=all" to see the queries

**To Reproduce**
1) run postgres with the sample database with log_statement=all and connect it to Metabase
2) new->native query-> select * from people -> don't run it, just save it so Metabase gets the metadata
3) see that we're sending the full query to the DB without limit

**Expected behavior**
We should limit those queries as we don't need the full results to get the metadata

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.46

**Severity**
P2

**Additional context**
NA

**Comment by luizarakaki** [comment]
@paoliniluis The metadata we gather depends on the data too. We collect `result_metadata` that contains the "question fingerprint", so we need to know what data returns from the question.

**Comment by paoliniluis** [comment]
Agree @luizarakaki, but all data? why don't we send to the DB a "limit 1" so the query planner knows that it will need to get just 1 row instead of all the rows

**Comment by dpsutton** [comment]
i think this whole issue goes away when we implement https://github.com/metabase/metabase/issues/28195. We can just ask the db for the result_metadata for a query and be done with it.

**Comment by paoliniluis** [comment]
Thanks @dpsutton, does result_metadata works with all dbs?

**Comment by dpsutton** [comment]
that method linked in #28195 works with all jdbc based dbs. For non jdbc we'll have to continue with the current approach. Others like bigquery have similar mechanisms to what is linked in 28195.

**Comment by camsaul** [comment]
We're already setting LIMIT via the JDBC method for doing so; closing this in favor of #28195 since that's a better way to fix the problem anyway

**Comment by camsaul** [comment]
Actually I think we can reopen this for now and investigate adding another MBQL stage with `LIMIT 1` to the query or otherwise be smarter about how we do this for non-JDBC databases
