### ISSUE TITLE
Do not enable "Update" button if there were no changes in "Edit user" modal

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#30195]
**Describe the bug**
When an admin tries to edit the user details, the "Update" button is enabled by default even thought there hasn't been any changes.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. As an admin, to the "People" settings
2. Click on '....' next to any user and click on "Edit user"
3. Modal opens and the "Update button" is enabled
4. You can click on this button, which results in three requests (`PUT` and 2x `GET`) but no changes have been made

**Expected behavior**
Disable the button until there are some changes to commit.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/31325167/232858354-02d14ebf-7657-49bd-a4ad-6350598f7941.png)

**Information about your Metabase Installation:**
master, local dev, 40e85fa61a8470c3153a0d35b3db0f5e98554a84, H2, Sample Database

**Severity**
P3

**Comment by npfitz** [comment]
This was addressed in https://github.com/metabase/metabase/pull/35892
