### ISSUE TITLE
Typo: "Your question took to long" 

### ISSUE THREAD

**Issue by hukev** [metabase/metabase#3019]
*  I am using the Chrome browser.
*  My computer's OS is Mac OS.
*  I'm running Metabase on AWS and it is using the Postgres database.
*  My data is in a MySQL database. [Postgres / MySQL / Redshift / BigQuery / MongoDB / SQLite / SQL Server / etc.]
*  My Metabase version is v0.19.0-snapshot.

<img width="526" alt="screen shot 2016-07-25 at 4 10 04 pm" src="https://cloud.githubusercontent.com/assets/5407426/17120691/f22302bc-5282-11e6-8acc-7b172afc7f89.png">

**Comment by salsakran** [comment]
@hukev good catch!
