### ISSUE TITLE
Google Analytics driver

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#3020]
It's not really a database, but there's no reason we couldn't treat it as one.

**Comment by kdoh** [comment]
#542 had a janky but working implementation of this for reference.

**Comment by marketingnerds** [comment]
Not sure if you guys are following the rollout of GA Data Studio but this feature would be huge for non-enterprise companies who don't have access to the GA 360 Suite. 

GA data is key for my business so it would be great not to have to pole the API and store all the data ourselves.

**Comment by Poggen** [comment]
+1

**Comment by tlrobinson** [comment]
I looked into this a bit and think it would work pretty well.

To get an idea of how the GA data API works check out https://ga-dev-tools.appspot.com/query-explorer/

Most of these fields would map nicely to our UI/query language:

Account = database
Property = schema
View = table
start-date/end-date: we’d need a required date filter clause that can't be removed?
metrics = pre-populated read-only Metabase "metrics" that correspond to GA metrics. Can't do arbitrary aggregations? Metric is required, can't do "raw data"
dimensions = breakouts
filter = filters
segments = similar to metrics, we could have pre-populated read-only segments that correspond to the built in GA segments
sort = order-by
max-results = limit
start-index = page (currently not in UI)

**Comment by mazameli** [comment]
At first I thought we could put folders/groupings in the filter and aggregations/metrics dropdowns that just map 1:1 to the GA groupings, but there are a crap ton of them (33 listed on this page https://developers.google.com/analytics/devguides/reporting/core/dimsmets ), which would be pretty awful in a dropdown. Maybe higher-level conceptual buckets with the GA folders inside them?
