### ISSUE TITLE
It's possible to create an official collection that lives in a personal collection

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#30236]
**Describe the bug**
It's possible to create an official collection that lives in a private collection, even though the UI makes you think that it's not possible.

**To Reproduce**
_EE edition, admin role_
1. Go to the root collection 
2. Click on `+ New` and then click "Collection"
3. Give it a name "Official Private Collection"
4. Mark it as official in the modal
![image](https://user-images.githubusercontent.com/31325167/233161710-65772213-e96f-4162-9329-ff4eef17623c.png)
5. Then change the parent collection from the root to your personal collection
6. Notice that the option to choose between Regular and Official collections disappeared from UI
![image](https://user-images.githubusercontent.com/31325167/233161873-2169924e-616d-4e3e-874e-03ac3bf3ca3f.png)
7. Click "Create"
8. The collection was saved as an Official one
![image](https://user-images.githubusercontent.com/31325167/233162191-58bee2cb-4f47-4f7a-9654-09927da41554.png)

If we examine the payload and the response from the `POST /api/collection` you'll see that the `authority` is set to `official` in both cases
```js
// request payload
{
"authority_level": "official",
"color": "#509EE3",
"description": null,
"name": "Official Private Collection",
"parent_id": 1
}

// response
{
  "authority_level": "official",
  "description": null,
  "archived": false,
  "slug": "official_private_collection",
  "color": "#509EE3",
  "name": "Official Private Collection",
  "personal_owner_id": null,
  "id": 12,
  "entity_id": "tbp29OzkwD5t1NeHzAFUo",
  "location": "/1/",
  "namespace": null,
  "created_at": "2023-04-19T20:05:34.883359+02:00"
}
```

**Expected behavior**
According to the product, this shouldn't be possible. The UI seems to correctly suggest that you can't choose between "Regular" and the "Official" collections if you chose a Personal collection for its parent. But then we should respect that in the code and override the `authority` field.

**Information about your Metabase Installation:**
local dev, master, https://github.com/metabase/metabase/commit/ae0d9c62dc2b33d22b791f09ba4f7f04ca14d666, H2, Sample Database

**Severity**
🤷‍♂️ 

**Additional context**
Keep in mind it is also possible to move the official collection from a root collection to a personal collection and it will still retain the "Official" status. Maybe we need to handle that case as well and just say that any collection living in a personal collection loses it's official status?

**Comment by ranquild** [comment]
Frontend shouldn't send `official` and the backend shouldn't allow this value to be saved for a collection within a personal collection.

**Comment by dpsutton** [comment]
We can lock this down on the BE. Not sure if you can move/copy to a personal collection but we'll have to strip the official status there as well

**Comment by luizarakaki** [comment]
We discussed this in the product team and the conclusion is that it should be possible to create official collections in personal collections.

So the fix here is to show the regular/official collection selector when creating collections inside personal collections.
