### ISSUE TITLE
Popovers inside modals should close when you click outside of them

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#3023]
e.x. Chart settings

I believe `OnClickOut` doesn't work with nested components, i.e. if the click is outside of one but inside the other neither is closed.

**Comment by kdoh** [comment]
I'd be curious if some aspect of this behavior is related to #3013. It seems like certain modals aren't responding to their onCloseFn from OnClickOut and I would imagine its possible that same issue is happening with popovers.

**Comment by salsakran** [comment]
holy shit this is annoying.
