### ISSUE TITLE
"Table 'metabase.app' doesn't exist" after try to upgrade from version 0.45.3 to  0.46.1 

### ISSUE THREAD

**Issue by bparmind** [metabase/metabase#30243]
**Describe the bug**
We try to upgrade our metabase jar file from 0.45.3 to 0.46.1  but it got stuck at running the **Migration lock is cleared. Running migrations...** when we revert back to previous version of working metabase.jar file we started getting Table 'metabase.app' doesn't exist",

**Logs**
[bf44500a-0313-473b-a3a2-4dd7e4446085] 2023-04-19T13:38:48-07:00 ERROR metabase.server.middleware.log GET /api/bookmark 500 944.8 ms (1 DB calls) 
{:via
 [{:type java.sql.SQLSyntaxErrorException,
   :message "(conn=53109896) Table 'metabase.app' doesn't exist",
   :at [org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory createException "ExceptionFactory.java" 62]}
  {:type org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException,
   :message "Table 'metabase.app' doesn't exist",
   :at [org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException of "MariaDbSqlException.java" 34]}
  {:type java.sql.SQLException,
   :message "Table 'metabase.app' doesn't exist",
   :at [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket "AbstractQueryProtocol.java" 1695]}],
 :trace
 [[org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket "AbstractQueryProtocol.java" 1695]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readPacket "AbstractQueryProtocol.java" 1557]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol getResult "AbstractQueryProtocol.java" 1520]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol executeQuery "AbstractQueryProtocol.java" 318]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeInternal "ClientSidePreparedStatement.java" 220]
  [org.mariadb.jdbc.ClientSidePreparedStatement execute "ClientSidePreparedStatement.java" 149]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeQuery "ClientSidePreparedStatement.java" 163]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeQuery "NewProxyPreparedStatement.java" 1471]
  [clojure.java.jdbc$execute_query_with_params invokeStatic "jdbc.clj" 1090]
  [clojure.java.jdbc$execute_query_with_params invoke "jdbc.clj" 1084]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invokeStatic "jdbc.clj" 1113]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invoke "jdbc.clj" 1093]
  [clojure.java.jdbc$query invokeStatic "jdbc.clj" 1182]
  [clojure.java.jdbc$query invoke "jdbc.clj" 1144]
  [toucan.db$query invokeStatic "db.clj" 308]
  [toucan.db$query doInvoke "db.clj" 304]

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**This is blocking our usage of Metabase entirely**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Ubuntu-0ubuntu118.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Ubuntu-0ubuntu118.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1083-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.41-0ubuntu0.18.04.1-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by bparmind** [comment]
If we are running the latest jar, we get stuck at Migration lock is cleared. Running migrations...

See logs below. 

Apr 19 21:49:20 metabase-us metabase[1002]: ..instrumented #'metabase.models.permissions/generate-graph
Apr 19 21:49:20 metabase-us metabase[1002]: ..instrumented #'metabase.models.permissions/->v2-path
Apr 19 21:49:20 metabase-us metabase[1002]: ..instrumented #'metabase.models.permissions/update-db-data-access-permissions!
Apr 19 21:49:20 metabase-us metabase[1002]: ..instrumented #'metabase.models.permissions/update-group-permissions!
Apr 19 21:49:20 metabase-us metabase[1002]: ..instrumented #'metabase.models.permissions/update-data-perms-graph!
Apr 19 21:49:23 metabase-us metabase[1002]: ..instrumented #'metabase.models.parameter-card/upsert-or-delete-from-parameters!
Apr 19 21:49:23 metabase-us metabase[1002]: WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.math, being replaced by: #'kixi.stats.math/abs
Apr 19 21:49:23 metabase-us metabase[1002]: WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.test, being replaced by: #'kixi.stats.math/abs
Apr 19 21:49:23 metabase-us metabase[1002]: WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.distribution, being replaced by: #'kixi.stats.math/abs
Apr 19 21:49:24 metabase-us metabase[1002]: ..instrumented #'metabase.query-processor.middleware.permissions/check-query-permissions*
Apr 19 21:49:25 metabase-us metabase[1002]: ..instrumented #'metabase.driver.sql-jdbc.sync.describe-database/simple-select-probe-query
Apr 19 21:49:25 metabase-us metabase[1002]: 2023-04-19 21:49:25,923 INFO driver.impl :: #033[34mRegistered abstract driver :sql#033[0m  🚚
Apr 19 21:49:25 metabase-us metabase[1002]: 2023-04-19 21:49:25,927 INFO metabase.util :: #033[36m ⮦ Load driver :sql took 89.8 ms#033[0m
Apr 19 21:49:25 metabase-us metabase[1002]: 2023-04-19 21:49:25,932 INFO driver.impl :: #033[34mRegistered abstract driver :sql-jdbc#033[0m (parents: [:sql]) 🚚
Apr 19 21:49:25 metabase-us metabase[1002]: 2023-04-19 21:49:25,935 INFO metabase.util :: #033[32mLoad driver :sql-jdbc took 101.3 ms#033[0m
Apr 19 21:49:25 metabase-us metabase[1002]: 2023-04-19 21:49:25,935 INFO driver.impl :: #033[34mRegistered driver :h2#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:25 metabase-us metabase[1002]: ..instrumented #'metabase.driver.h2/classify-query
Apr 19 21:49:25 metabase-us metabase[1002]: 2023-04-19 21:49:25,977 INFO driver.impl :: #033[34mRegistered driver :mysql#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:26 metabase-us metabase[1002]: 2023-04-19 21:49:26,004 INFO driver.impl :: #033[34mRegistered driver :postgres#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:26 metabase-us metabase[1002]: ..instrumented #'metabase.models.params.custom-values/values-from-card
Apr 19 21:49:26 metabase-us metabase[1002]: ..instrumented #'metabase.api.card/param-values
Apr 19 21:49:27 metabase-us metabase[1002]: ..instrumented #'metabase.api.dashboard/chain-filter
Apr 19 21:49:27 metabase-us metabase[1002]: 2023-04-19 21:49:27,959 INFO metabase.core ::
Apr 19 21:49:27 metabase-us metabase[1002]: Metabase v0.46.1 (12a6e1d release-x.46.x)
Apr 19 21:49:27 metabase-us metabase[1002]: Copyright © 2023 Metabase, Inc.
Apr 19 21:49:27 metabase-us metabase[1002]: Metabase Enterprise Edition extensions are NOT PRESENT.
Apr 19 21:49:27 metabase-us metabase[1002]: 2023-04-19 21:49:27,967 INFO metabase.core :: Starting Metabase in STANDALONE mode
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,035 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
Apr 19 21:49:28 metabase-us metabase[1002]:  {:port 3000}
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,109 INFO metabase.core :: Starting Metabase version v0.46.1 (12a6e1d release-x.46.x) ...
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,141 INFO metabase.core :: System info:
Apr 19 21:49:28 metabase-us metabase[1002]:  {"file.encoding" "UTF-8",
Apr 19 21:49:28 metabase-us metabase[1002]:  "java.runtime.name" "OpenJDK Runtime Environment",
Apr 19 21:49:28 metabase-us metabase[1002]:  "java.runtime.version" "11.0.18+10-post-Ubuntu-0ubuntu118.04.1",
Apr 19 21:49:28 metabase-us metabase[1002]:  "java.vendor" "Ubuntu",
Apr 19 21:49:28 metabase-us metabase[1002]:  "java.vendor.url" "https://ubuntu.com/",
Apr 19 21:49:28 metabase-us metabase[1002]:  "java.version" "11.0.18",
Apr 19 21:49:28 metabase-us metabase[1002]:  "java.vm.name" "OpenJDK 64-Bit Server VM",
Apr 19 21:49:28 metabase-us metabase[1002]:  "java.vm.version" "11.0.18+10-post-Ubuntu-0ubuntu118.04.1",
Apr 19 21:49:28 metabase-us metabase[1002]:  "os.name" "Linux",
Apr 19 21:49:28 metabase-us metabase[1002]:  "os.version" "5.4.0-1100-aws",
Apr 19 21:49:28 metabase-us metabase[1002]:  "user.language" "en",
Apr 19 21:49:28 metabase-us metabase[1002]:  "user.timezone" "Etc/UTC"}
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,143 INFO metabase.plugins :: Loading plugins in /home/ubuntu/metabase-installables/plugins...
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,380 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/sparksql.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,462 INFO util.files :: Extract file /modules/athena.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/athena.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,587 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/sqlserver.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,603 INFO util.files :: Extract file /modules/presto-jdbc.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/presto-jdbc.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,696 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/sqlite.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,786 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/vertica.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,790 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/redshift.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,803 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/druid.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,811 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/mongo.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,838 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/oracle.metabase-driver.jar
Apr 19 21:49:28 metabase-us metabase[1002]: 2023-04-19 21:49:28,842 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/snowflake.metabase-driver.jar
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,119 INFO util.files :: Extract file /modules/googleanalytics.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/googleanalytics.metabase-driver.jar
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,141 INFO util.files :: Extract file /modules/bigquery-cloud-sdk.metabase-driver.jar -> /home/ubuntu/metabase-installables/plugins/bigquery-cloud-sdk.metabase-driver.jar
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,394 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :sqlserver...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,395 INFO driver.impl :: #033[34mRegistered driver :sqlserver#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,400 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :sqlite...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,401 INFO driver.impl :: #033[34mRegistered driver :sqlite#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,413 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :mongo...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,414 INFO driver.impl :: #033[34mRegistered driver :mongo#033[0m  🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,421 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :redshift...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,422 INFO driver.impl :: #033[34mRegistered driver :redshift#033[0m (parents: [:postgres]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,426 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :google...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,427 INFO driver.impl :: #033[34mRegistered abstract driver :google#033[0m  🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,432 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,434 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,434 WARN plugins.lazy-loaded-driver :: #033[31mWarning: plugin manifest for :bigquery does not include connection properties#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,435 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :bigquery...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,435 INFO driver.impl :: #033[34mRegistered driver :bigquery#033[0m (parents: [:sql :google]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,441 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :googleanalytics...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,442 INFO driver.impl :: #033[34mRegistered driver :googleanalytics#033[0m  🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,446 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :druid...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,446 INFO driver.impl :: #033[34mRegistered driver :druid#033[0m  🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,469 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :snowflake...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,469 INFO driver.impl :: #033[34mRegistered driver :snowflake#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,473 INFO plugins.dependencies :: #033[31mMetabase cannot initialize plugin Metabase Vertica Driver due to required dependencies.#033[0m Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,473 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,474 INFO plugins.dependencies :: #033[33mPlugins with unsatisfied deps: ["Metabase Vertica Driver"]#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,485 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :athena...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,486 INFO driver.impl :: #033[34mRegistered driver :athena#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,491 INFO plugins.dependencies :: Plugin 'Metabase Presto Driver' depends on plugin 'Presto Common Driver'
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,492 INFO plugins.dependencies :: Metabase Presto Driver dependency {:plugin Presto Common Driver} satisfied? false
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,493 INFO plugins.dependencies :: #033[33mPlugins with unsatisfied deps: ["Metabase Presto Driver" "Metabase Vertica Driver"]#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,500 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :bigquery-cloud-sdk...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,501 INFO driver.impl :: #033[34mRegistered driver :bigquery-cloud-sdk#033[0m (parents: [:sql]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,509 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :hive-like...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,510 INFO driver.impl :: #033[34mRegistered abstract driver :hive-like#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,510 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :sparksql...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,511 INFO driver.impl :: #033[34mRegistered driver :sparksql#033[0m (parents: [:hive-like]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,516 INFO plugins.dependencies :: #033[31mMetabase cannot initialize plugin Metabase Oracle Driver due to required dependencies.#033[0m Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,517 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,517 INFO plugins.dependencies :: #033[33mPlugins with unsatisfied deps: ["Metabase Presto Driver" "Metabase Oracle Driver" "Metabase Vertica Driver"]#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,521 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :presto-common...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,522 INFO driver.impl :: #033[34mRegistered abstract driver :presto-common#033[0m  🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,522 INFO plugins.dependencies :: Metabase Presto Driver dependency {:plugin Presto Common Driver} satisfied? true
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,523 DEBUG plugins.initialize :: #033[33mDependencies satisfied; these plugins will now be loaded: ["Metabase Presto Driver"]#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,524 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :presto...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,524 INFO driver.impl :: #033[34mRegistered driver :presto#033[0m (parents: [:presto-common]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,537 DEBUG plugins.lazy-loaded-driver :: #033[35mRegistering lazy loading driver :presto-jdbc...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,537 INFO driver.impl :: #033[34mRegistered driver :presto-jdbc#033[0m (parents: [:sql-jdbc]) 🚚
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,538 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,541 INFO db.setup :: #033[36mVerifying mysql Database Connection ...#033[0m
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,705 INFO db.setup :: Successfully verified MySQL 5.7.41-0ubuntu0.18.04.1-log application database connection. ✅
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,707 INFO db.setup :: Running Database Migrations...
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,709 INFO db.setup :: Setting up Liquibase...
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,984 INFO db.setup :: Liquibase is ready.
Apr 19 21:49:29 metabase-us metabase[1002]: 2023-04-19 21:49:29,984 INFO db.liquibase :: Checking if Database has unrun migrations...
Apr 19 21:49:31 metabase-us metabase[1002]: 2023-04-19 21:49:31,025 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
Apr 19 21:49:31 metabase-us metabase[1002]: 2023-04-19 21:49:31,102 INFO db.liquibase :: Migration lock is cleared. Running migrations...

**Comment by paoliniluis** [comment]
Go for the latest JAR as there's no way you can downgrade without reverting to a database backup (major versions in Metabase do schema changes).

Regarding the migration: what's the sizing of your DB? MySQL takes a long long time to do the changes in the migration

**Comment by bparmind** [comment]
@paoliniluis I'm back at latest Jar, mysql db size is just 936.0 MiB and when I'm running migrate force command, i'm getting below error 

**java -jar metabase.jar migrate force**

HERE "ID" = 1 AND "LOCKED" = FALSE;
2023-04-19 22:09:22,079 INFO db.liquibase :: [SUCCESS]
2023-04-19 22:09:22,079 INFO db.liquibase :: DROP TABLE "PUBLIC"."QUERY_QUERYEXECUTION";
org.h2.jdbc.JdbcSQLNonTransientException: Savepoint is invalid: "SYSTEM_SAVEPOINT_1"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_1 [90063-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.SessionLocal.rollbackToSavepoint(SessionLocal.java:1106)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:68)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:958)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1007)
	at metabase.db.liquibase$fn__46117$force_migrate_up_if_needed_BANG___46122$fn__46123$fn__46128.invoke(liquibase.clj:176)
	at metabase.db.liquibase$fn__46117$force_migrate_up_if_needed_BANG___46122$fn__46123.invoke(liquibase.clj:172)
	at metabase.db.liquibase$fn__46117$force_migrate_up_if_needed_BANG___46122.invoke(liquibase.clj:151)
	at metabase.db.setup$fn__50118$migrate_BANG___50123$fn__50124$fn__50125.invoke(setup.clj:80)
	at metabase.db.liquibase$fn__46055$do_with_liquibase__46060$fn__46061.invoke(liquibase.clj:64)
	at metabase.db.liquibase$fn__46055$do_with_liquibase__46060.invoke(liquibase.clj:56)
	at metabase.db.setup$fn__50118$migrate_BANG___50123$fn__50124.invoke(setup.clj:74)
	at metabase.db.setup$fn__50118$migrate_BANG___50123.doInvoke(setup.clj:52)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.cmd.migrate$migrate_BANG_.invokeStatic(migrate.clj:9)
	at metabase.cmd.migrate$migrate_BANG_.invoke(migrate.clj:6)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$migrate.invokeStatic(cmd.clj:40)
	at metabase.cmd$migrate.invoke(cmd.clj:36)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__103015.invoke(cmd.clj:262)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:262)
	at metabase.cmd$run_cmd.invoke(cmd.clj:253)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:166)
	at metabase.core$run_cmd.invoke(core.clj:164)
	at metabase.core$_main.invokeStatic(core.clj:188)
	at metabase.core$_main.doInvoke(core.clj:183)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Command failed with exception: Savepoint is invalid: "SYSTEM_SAVEPOINT_1"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_1 [90063-212]


Do you think i messed up metabase.db.mv.db file?

**Comment by paoliniluis** [comment]
If you're running MySQL then the metabase.db.mv.db are not relevant. For this issue it seems that MySQL messed up so I would suggest you try to recover your database to a working point and then start with the upgrade again

**Comment by bparmind** [comment]
@paoliniluis do you know which table is used to determine if database has unrun migrations? 

-  Checking if Database has unrun migrations...
-  Database has unrun migrations. Waiting for migration lock to be cleared...
-  Migration lock is cleared. Running migrations...

**Comment by bparmind** [comment]
we finally manage to resolve it using https://github.com/metabase/metabase/pull/3295
