### ISSUE TITLE
Unable to pass some columns as variable to question while configuring click through behaviour

### ISSUE THREAD

**Issue by pranayat** [metabase/metabase#30251]
Describe the bug
Unable to pass some columns as variable to a destination question while configuring click through behaviour.

Screenshots/videos
Only 3 columns are available whereas the source question has 6 columns. I want to pass the 'Restuarant___id' column which is not available the in the dropdown below.
![image](https://user-images.githubusercontent.com/6952713/233330888-7a47ba7c-a704-4e89-adb8-1109baf64c00.png)

This is my source question
![image](https://user-images.githubusercontent.com/6952713/233331188-6a13d554-0e63-4ea9-8604-88f7f7b73442.png)

Information about your Metabase Installation:
v0.46.1
Browser - Google Chrome Version 112.0.5615.49 (Official Build) (arm64)

Severity
Severe

**Comment by ranquild** [comment]
For SQL queries, it's only possible to pass values for configured parameters. The attached screenshots shows a SQL query with 3 parameters, so it's expected that only 3 parameters are available for custom click behavior.

**Comment by brunobergher** [comment]
Yes, confirming this is working as intended – the only filters shown as possible destinations for values are the ones explicitly defined in the SQL query. @pranayat, [you can read more about it here](https://www.metabase.com/docs/latest/dashboards/interactive#passing-values-to-the-destination).
