### ISSUE TITLE
Database schema outdated for tables without full access

### ISSUE THREAD

**Issue by araujo-filipe** [metabase/metabase#30264]
**Describe the bug**
If the database role metabase uses starts by having access to all columns of a table and then loses access to some of the table's columns, metabase can't refresh that table's schema correctly.
Besides the issue of having outdated metadata for tables in this scenario, it also breaks the query builder for that table, since it will throw the `ERROR: column ... does not exist` error.
I found this issue with a Postgresql source, not sure about other types of databases.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create a test table. The database role used by metabase has access to all the table's columns.
2. Sync database schema.
3. Change the grants of the metabase role to only have access to some columns in the database.
4. Drop one of the columns that metabase doesn't have access to.
5. Sync database schema.
6. Try to use the table in the query builder.

**Expected behavior**
At least for postgres, I guess there are ways of updating metadata without needing to have access to all columns of all tables. I expected metabase to show the schema it has access to, up to date.

**Information about your Metabase Installation:**
- Your databases: Postgres
- Metabase version: 0.45.2

**Severity**
Not a blocking issue, the table can still be used in native queries. The outdated metadata is the most "annoying" part.

**Comment by paoliniluis** [comment]
I think your issue is the same as https://github.com/metabase/metabase/issues/12721, please correct me if I'm wrong

**Comment by paoliniluis** [comment]
closing as it seems to be the same
