### ISSUE TITLE
Our Databases are stuck in the sync state for days with no clear indication what's going on. 

### ISSUE THREAD

**Issue by ArjaaAine** [metabase/metabase#30282]
**Describe the bug**
Databases stuck in the sync state. (Since last week, new databases being created are stuck in the sync state and never completing). This seems very specific to our environment. 

**Logs**
The bug is ongoing and there are no real logs to help us understand what's going on. 

**To Reproduce**
1. Go to Admin
2. Add Database
3. Fill out information
4. Save to trigger a sync.

**Expected behavior**
Normally syncing new database takes 5-10minutes.. This time longest we have seen is 6 days before we manually cancelled. 

**Screenshots**
You can see here how it just shows loading. It has been like that for days. 
![image](https://user-images.githubusercontent.com/5263570/233519903-81845b30-bde1-4d31-aefb-2d95c0f8073e.png)

**Severity**
Medium - High? Some users are not able to use it and we aren't able to connect new databases. 

**Additional context**
Seems specific to our environment. I have tried cancelling the sync and restarting it (but nothing happens after I try to restart it and nothing jumps out in the troubleshooting logs either. 

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-29",
      "tag": "v1.45.3.1",
      "branch": "release-x.45.x",
      "hash": "3b3097d"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by ArjaaAine** [comment]
Hi just wanted to follow up on this.

**Comment by paoliniluis** [comment]
Are you an enterprise customer? Or a cloud customer?

**Comment by ArjaaAine** [comment]
@paoliniluis We are a cloud customer

**Comment by paoliniluis** [comment]
Ok please write to our help email so we can see what’s going on
