### ISSUE TITLE
Adding a row limit when there is a filter with a contains clause causes the filter to disappear

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#30280]
**Describe the bug**
When adding a Row Limit when there is a filter with a contains clause, the filter will disappear.
Additionally, if you remove the Row Limit, the filter will also disappear

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1.  Start by Browsing Data, Sample Database
2. Choose Analytics Events table.
3. In the Notebook Editor, create a filter with a "contains" or "does not contain" option. I chose  Page URL does not contain "invite"
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/22856340/233501071-5d3c4934-a74f-4976-a2d2-49f34c93750a.png">
4.  Add a Row Limit.  I did a Row Limit of 3.
5.  Notice how the entire filters section disappears.
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/22856340/233501178-fcf45f90-2a74-4549-856d-4ae2c9dbe5b8.png">

**Expected behavior**
Filters should not disappear

**Information about your Metabase Installation:**

Seeing this on master Built on 2023-04-20
Does not happen in 45.3 or 46.1

**Severity**
It's pretty annoying  I had to add back filters.

**Additional context**

**Comment by nemanjaglumac** [comment]
> Seeing this on master Built on 2023-04-20
Does not happen in 45.3 or 46.1

Removed `.Regression` label and applied `.Regression/master` due to this.

**Comment by NevRA** [comment]
@kulyk it seems it's related to the latest MLibv2 changes, could you look into it? If so can you move to the QP team?
