### ISSUE TITLE
Can't "View Details" on a Binary field in Snowflake

### ISSUE THREAD

**Issue by sicarul** [metabase/metabase#30308]
### Describe the bug

I can't filter any binary fields on a Snowflake table, e.g.:

![image](https://user-images.githubusercontent.com/4952116/233819377-4d2a1169-4bd4-4bbb-bda7-69096418324b.png)

### To Reproduce

1. Create a binary field in Snowflake
2. Try to filter by that field
3. See error

### Expected behavior

We should be able to filter on Binary fields

### Logs

[d358b98e-632a-4c5d-9b15-3541de25b29f] 2023-04-23T01:08:42-03:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: SQL compilation error:
Can not convert parameter '?' of type [VARCHAR(10)] into expected type [BINARY(32)]
{:database_id 4,
 :started_at #t "2023-04-22T21:08:41.342913-07:00[US/Pacific]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: SQL compilation error:\nCan not convert parameter '?' of type [VARCHAR(10)] into expected type [BINARY(32)]",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__71786.invoke(execute.clj:505)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:502)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:489)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:497)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:489)"
    "driver.sql_jdbc$fn__105090.invokeStatic(sql_jdbc.clj:63)"
    "driver.sql_jdbc$fn__105090.invoke(sql_jdbc.clj:61)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:12)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___69171.invoke(cache.clj:224)"
    "query_processor.middleware.permissions$check_query_permissions$fn__64643.invoke(permissions.clj:126)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__68062.invoke(mbql_to_native.clj:24)"
    "query_processor$fn__70690$combined_post_process__70695$combined_post_process_STAR___70696.invoke(query_processor.clj:243)"
    "query_processor$fn__70690$combined_pre_process__70691$combined_pre_process_STAR___70692.invoke(query_processor.clj:240)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69082$fn__69087.invoke(resolve_database_and_driver.clj:36)"
    "driver$do_with_driver.invokeStatic(driver.clj:90)"
    "driver$do_with_driver.invoke(driver.clj:86)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69082.invoke(resolve_database_and_driver.clj:35)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__64952.invoke(fetch_source_query.clj:310)"
    "query_processor.middleware.store$initialize_store$fn__65130$fn__65131.invoke(store.clj:12)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:47)"
    "query_processor.store$do_with_store.invoke(store.clj:41)"
    "query_processor.middleware.store$initialize_store$fn__65130.invoke(store.clj:11)"
    "query_processor.middleware.normalize_query$normalize$fn__69371.invoke(normalize_query.clj:25)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__66308.invoke(constraints.clj:54)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__69307.invoke(process_userland_query.clj:150)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__69684.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___59455$thunk__59457.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___59455.invoke(reducible.clj:109)"
    "query_processor.reducible$async_qp$qp_STAR___59455.invoke(reducible.clj:94)"
    "query_processor.reducible$sync_qp$qp_STAR___59467.doInvoke(reducible.clj:129)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:362)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:358)"
    "query_processor$fn__70738$process_query_and_save_execution_BANG___70747$fn__70750.invoke(query_processor.clj:373)"
    "query_processor$fn__70738$process_query_and_save_execution_BANG___70747.invoke(query_processor.clj:366)"
    "query_processor$fn__70783$process_query_and_save_with_max_results_constraints_BANG___70792$fn__70795.invoke(query_processor.clj:385)"
    "query_processor$fn__70783$process_query_and_save_with_max_results_constraints_BANG___70792.invoke(query_processor.clj:378)"
    "api.dataset$run_query_async$fn__86539.invoke(dataset.clj:73)"
    "query_processor.streaming$streaming_response_STAR_$fn__54305$fn__54306.invoke(streaming.clj:166)"
    "query_processor.streaming$streaming_response_STAR_$fn__54305.invoke(streaming.clj:165)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__36922.invoke(streaming_response.clj:88)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :snowflake,
    :sql
    ["-- Metabase:: userID: 142 queryType: MBQL queryHash: ac782918f83abf8cf79019142c2a5a6d8d0cce9eea40ec0c2270eca53bf09d1d"
     "SELECT"
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"REPOSITORY_HK\" AS \"REPOSITORY_HK\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"REPOSITORY_ID\" AS \"REPOSITORY_ID\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"REPOSITORY_KEY\" AS \"REPOSITORY_KEY\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"ORG\" AS \"ORG\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"NAME\" AS \"NAME\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"ARCHIVED\" AS \"ARCHIVED\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"CLONE_URL\" AS \"CLONE_URL\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"CREATED_AT\" AS \"CREATED_AT\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"DEFAULT_BRANCH\" AS \"DEFAULT_BRANCH\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"DESCRIPTION\" AS \"DESCRIPTION\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"DISABLED\" AS \"DISABLED\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"FORK\" AS \"FORK\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"FORKS_COUNT\" AS \"FORKS_COUNT\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"GIT_URL\" AS \"GIT_URL\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"HOMEPAGE\" AS \"HOMEPAGE\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"HTML_URL\" AS \"HTML_URL\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"LANGUAGE\" AS \"LANGUAGE\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"LICENSE\" AS \"LICENSE\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"LICENSE_KEY\" AS \"LICENSE_KEY\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"NODE_ID\" AS \"NODE_ID\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"OPEN_ISSUES\" AS \"OPEN_ISSUES\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"OPEN_ISSUES_COUNT\" AS \"OPEN_ISSUES_COUNT\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"PRIVATE\" AS \"PRIVATE\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"PUSHED_AT\" AS \"PUSHED_AT\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"SIZE\" AS \"SIZE\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"SSH_URL\" AS \"SSH_URL\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"STARGAZERS_COUNT\" AS \"STARGAZERS_COUNT\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"TOPICS\" AS \"TOPICS\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"VISIBILITY\" AS \"VISIBILITY\","
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"LAST_UPDATED_AT\" AS \"LAST_UPDATED_AT\""
     "FROM"
     "  \"INFORMATION_MARTS\".\"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\""
     "WHERE"
     "  \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"REPOSITORY_HK\" = ?"
     "LIMIT"
     "  2000"],
    :params ("0x00B658AB"),
    :type :invalid-query}}],
 :state "22023",
 :error_type :invalid-query,
 :json_query
 {:query {:source-table 1499, :filter ["=" ["field" 36150 nil] "0x00B658AB"]},
  :type "query",
  :database 4,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"REPOSITORY_HK\" AS \"REPOSITORY_HK\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"REPOSITORY_ID\" AS \"REPOSITORY_ID\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"REPOSITORY_KEY\" AS \"REPOSITORY_KEY\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"ORG\" AS \"ORG\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"NAME\" AS \"NAME\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"ARCHIVED\" AS \"ARCHIVED\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"CLONE_URL\" AS \"CLONE_URL\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"CREATED_AT\" AS \"CREATED_AT\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"DEFAULT_BRANCH\" AS \"DEFAULT_BRANCH\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"DESCRIPTION\" AS \"DESCRIPTION\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"DISABLED\" AS \"DISABLED\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"FORK\" AS \"FORK\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"FORKS_COUNT\" AS \"FORKS_COUNT\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"GIT_URL\" AS \"GIT_URL\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"HOMEPAGE\" AS \"HOMEPAGE\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"HTML_URL\" AS \"HTML_URL\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"LANGUAGE\" AS \"LANGUAGE\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"LICENSE\" AS \"LICENSE\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"LICENSE_KEY\" AS \"LICENSE_KEY\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"NODE_ID\" AS \"NODE_ID\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"OPEN_ISSUES\" AS \"OPEN_ISSUES\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"OPEN_ISSUES_COUNT\" AS \"OPEN_ISSUES_COUNT\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"PRIVATE\" AS \"PRIVATE\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"PUSHED_AT\" AS \"PUSHED_AT\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"SIZE\" AS \"SIZE\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"SSH_URL\" AS \"SSH_URL\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"STARGAZERS_COUNT\" AS \"STARGAZERS_COUNT\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"TOPICS\" AS \"TOPICS\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"VISIBILITY\" AS \"VISIBILITY\", \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"LAST_UPDATED_AT\" AS \"LAST_UPDATED_AT\" FROM \"INFORMATION_MARTS\".\"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\" WHERE \"COMMUNITY\".\"DIM_GITHUB_REPOSITORY\".\"REPOSITORY_HK\" = ? LIMIT 1048575",
  :params ("0x00B658AB")},
 :status :failed,
 :class net.snowflake.client.jdbc.SnowflakeSQLException,
 :stacktrace
 ["net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)"
  "net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)"
  "net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:456)"
  "net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:366)"
  "net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:464)"
  "net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:192)"
  "net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:129)"
  "net.snowflake.client.core.SFStatement.execute(SFStatement.java:742)"
  "net.snowflake.client.core.SFStatement.execute(SFStatement.java:652)"
  "net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:236)"
  "net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:118)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)"
  "--> driver.sql_jdbc.execute$fn__71709.invokeStatic(execute.clj:380)"
  "driver.sql_jdbc.execute$fn__71709.invoke(execute.clj:378)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:393)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:389)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__71786.invoke(execute.clj:503)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:502)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:489)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:497)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:489)"
  "driver.sql_jdbc$fn__105090.invokeStatic(sql_jdbc.clj:63)"
  "driver.sql_jdbc$fn__105090.invoke(sql_jdbc.clj:61)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:12)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___69171.invoke(cache.clj:224)"
  "query_processor.middleware.permissions$check_query_permissions$fn__64643.invoke(permissions.clj:126)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__68062.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__70690$combined_post_process__70695$combined_post_process_STAR___70696.invoke(query_processor.clj:243)"
  "query_processor$fn__70690$combined_pre_process__70691$combined_pre_process_STAR___70692.invoke(query_processor.clj:240)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69082$fn__69087.invoke(resolve_database_and_driver.clj:36)"
  "driver$do_with_driver.invokeStatic(driver.clj:90)"
  "driver$do_with_driver.invoke(driver.clj:86)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69082.invoke(resolve_database_and_driver.clj:35)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__64952.invoke(fetch_source_query.clj:310)"
  "query_processor.middleware.store$initialize_store$fn__65130$fn__65131.invoke(store.clj:12)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:47)"
  "query_processor.store$do_with_store.invoke(store.clj:41)"
  "query_processor.middleware.store$initialize_store$fn__65130.invoke(store.clj:11)"
  "query_processor.middleware.normalize_query$normalize$fn__69371.invoke(normalize_query.clj:25)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__66308.invoke(constraints.clj:54)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__69307.invoke(process_userland_query.clj:150)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__69684.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___59455$thunk__59457.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___59455.invoke(reducible.clj:109)"
  "query_processor.reducible$async_qp$qp_STAR___59455.invoke(reducible.clj:94)"
  "query_processor.reducible$sync_qp$qp_STAR___59467.doInvoke(reducible.clj:129)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:362)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:358)"
  "query_processor$fn__70738$process_query_and_save_execution_BANG___70747$fn__70750.invoke(query_processor.clj:373)"
  "query_processor$fn__70738$process_query_and_save_execution_BANG___70747.invoke(query_processor.clj:366)"
  "query_processor$fn__70783$process_query_and_save_with_max_results_constraints_BANG___70792$fn__70795.invoke(query_processor.clj:385)"
  "query_processor$fn__70783$process_query_and_save_with_max_results_constraints_BANG___70792.invoke(query_processor.clj:378)"
  "api.dataset$run_query_async$fn__86539.invoke(dataset.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__54305$fn__54306.invoke(streaming.clj:166)"
  "query_processor.streaming$streaming_response_STAR_$fn__54305.invoke(streaming.clj:165)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__36922.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error "SQL compilation error:\nCan not convert parameter '?' of type [VARCHAR(10)] into expected type [BINARY(32)]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:query
  {:source-table 1499,
   :filter
   [:=
    [:field 36150 nil]
    [:value
     "0x00B658AB"
     {:base_type :type/*,
      :effective_type :type/*,
      :coercion_strategy nil,
      :semantic_type :type/PK,
      :database_type "BINARY",
      :name "REPOSITORY_HK"}]],
   :fields
   [[:field 36150 nil]
    [:field 36179 nil]
    [:field 36176 nil]
    [:field 36166 nil]
    [:field 36158 nil]
    [:field 36153 nil]
    [:field 36180 nil]
    [:field 36154 {:temporal-unit :default}]
    [:field 36164 nil]
    [:field 36165 nil]
    [:field 36182 nil]
    [:field 36171 nil]
    [:field 36181 nil]
    [:field 36167 nil]
    [:field 36156 nil]
    [:field 36177 nil]
    [:field 36163 nil]
    [:field 36162 nil]
    [:field 36174 nil]
    [:field 36151 nil]
    [:field 36172 nil]
    [:field 36157 nil]
    [:field 36152 nil]
    [:field 36175 {:temporal-unit :default}]
    [:field 36159 nil]
    [:field 36173 nil]
    [:field 36155 nil]
    [:field 36161 nil]
    [:field 36168 nil]
    [:field 36169 {:temporal-unit :default}]],
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :type :query,
  :database 4,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 142, :context :ad-hoc}},
 :data {:rows [], :cols []}}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.10.173-154.642.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.12"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-05",
      "tag": "v0.46.1",
      "branch": "release-x.46.x",
      "hash": "12a6e1d"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

### Severity

Moderate

### Additional context

Moderate severity, because it forces me to either tell users to not use this, or to modify all binary keys to be strings in dbt, neither of which are good solutions.

**Comment by paoliniluis** [comment]
Seems this is for all databases https://github.com/metabase/metabase/issues/1723
