### ISSUE TITLE
Cannot filter directly from table column header when Question is Summarized 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#30312]
### Describe the bug

There is no option to add a filter directly from table column header. 

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/110378427/233952393-a6a433a4-2c57-46ea-91c3-ec599ed00a4d.png">

### To Reproduce

1. Go to New Question -> Orders -> Count and Grouped by Created_at: Month

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/110378427/233952746-b057ba96-b2a6-41b9-b726-d3878408e42f.png">

2. Visualize as Table -> Click on Count Header -> Filter by this Column -> Equal to 10 -> the Add Filter is Faded

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/110378427/233953072-5dc3005f-bf9c-4737-9c40-21a9d649adbf.png">

### Expected behavior

Able to filter via the Column Header

### Logs

None pop up

### Information about your Metabase installation

```JSON
Able to replicate this on 1.45.3.1 and `master`
```

### Severity

There is a workaround in which you filter from the Editor

**Comment by nemanjaglumac** [comment]
Have you checked the JS console?

```
GET http://localhost:3000/api/field//values 400 (Bad Request)

Missing uniqueId: {remappings: Array(0)}

Request entities,fields,,values failed:
{
  status: 400,
  data: '<h1>Bad Message 400</h1><pre>reason: Ambiguous URI empty segment</pre>',
  isCancelled: false
}
```

Coming from https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/FieldSet/index.jsx

**Comment by Tony-metabase** [comment]
Didn't check the console, thanks Nemanja ... Should we change the form to have Console Logs and normal Metabase Logs?

**Comment by kamilmielnik** [comment]
Can reproduce in 0.47.0, 0.48.0,
Can't reproduce in 0.49.0-RC1.
Can't reproduce in `master` at bfceeebf16.
