### ISSUE TITLE
Link for Cloud firewall docs renders incorrectly

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#30317]
### Describe the bug

The copy below looks like markdown, but is not interpolated properly _and_ the URL is a bit off. The it should be a link like this: [Metabase Cloud](https://www.metabase.com/docs/latest/cloud/ip-addresses-to-whitelist), pointing at `https://www.metabase.com/docs/latest/cloud/ip-addresses-to-whitelist`

![image](https://user-images.githubusercontent.com/328388/234003538-69478dbc-ab23-4372-9af8-dea5178d57d9.png)

### To Reproduce

1. Run a Cloud instance
2. Go to Admin -> Databases -> add a new connection
3. You'll see this

### Expected behavior

Explained above.

### Logs

N/A

### Information about your Metabase installation

```JSON
45.3.1 on Cloud.
```

### Severity

Cosmetic, there's a workaround

**Comment by jeff-bruemmer** [comment]
That above link should work (thanks to a redirect), but **we should use the current link for this page:** 

https://www.metabase.com/docs/latest/cloud/ip-addresses-to-whitelist

**Comment by brunobergher** [comment]
Isn't that what's in the description? 🤔

**Comment by dpsutton** [comment]
It is a regression: https://github.com/metabase/metabase/pull/23767
