### ISSUE TITLE
Druid driver should return integers for distinct count

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3031]
At the moment if you query a distinct count in a druid database you get a floating point value such as 4.01 or 14.9874. This is because Druid uses HyperLogLog algorithm to compute the cardinality. While it makes sense for the API to return the floating point value, I believe the UI should display rounded values. 

Many users do not understand the concept of approximate user count and its generally annoying to read "35.2 users".  Other "official Druid projects" also round the value before displaying it.

**Comment by Digma** [comment]
Any update on a decision about this? It would be a good improvement

**Comment by camsaul** [comment]
@moummy @digma this fix and the PR seem reasonable so I'll take a look in the next few days
