### ISSUE TITLE
Allow no-self-service users to upload CSVs

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#30322]
Since the frontend cannot detect the difference between a user with no-self-service db permissions and one with "block" permissions - we need the backend to check whether the current user has at least no-self-service permissions on the uploads-enabled DB.

One possible implementation of this is a `can_upload` flag on the collection that also checks if the user has editing permissions on it - but there might be a better solution.

[discussion](https://metaboat.slack.com/archives/C04S696LRUM/p1681418036100589)
[more discussion](https://metaboat.slack.com/archives/C04S696LRUM/p1686151054039889)

**Comment by iethree** [comment]
Decided to only allow uploads to users with unrestricted access to the db, so the current behavior is what we will ship.

https://metaboat.slack.com/archives/C04S696LRUM/p1686157638684039?thread_ts=1686151054.039889&cid=C04S696LRUM

**Comment by tsmacdonald** [comment]
Upload button is still visible for users with these permissions:

![image](https://github.com/metabase/metabase/assets/784417/b223644f-bcdd-41de-a310-42e59930b162)

and the BE is throwing a 500 about not being able to acquire a connection1
