### ISSUE TITLE
Error message `Ambiguous column name 'x'` does not specify line number so very hard to debug

### ISSUE THREAD

**Issue by aarthi-subramanian** [metabase/metabase#30333]
### Describe the bug

Sometimes we get an error message `Ambiguous column name 'x'`. Other error messages specify the line number so you can figure out how to debug your query. This specific error message does not specify the line number so it's very hard to debug what went wrong in your query. Takes an hour sometimes if the query is long! Can you please add this in so consistent with other error logging to customer?

### To Reproduce

1. Write a long sql query with a join and select a column that is named the same across both tables
2. See this error message, `Ambiguous column name 'x'`. Dont see the line number so dont know which line in the select statement is problematic

### Expected behavior

When receiving this error message, `Ambiguous column name 'x'`, also specify the line number in the query responsible for this error message.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+0-adhoc..source",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+0-adhoc..source",
    "os.name": "Linux",
    "os.version": "5.4.84",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-07",
      "tag": "v0.46.1-SNAPSHOT",
      "branch": "release-x.46.metabot-alpha",
      "hash": "b96b662"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying, time consuming

### Additional context
<img width="644" alt="Screen Shot 2023-04-24 at 1 22 59 PM" src="https://user-images.githubusercontent.com/47357846/234074630-7466094f-84ae-4557-9554-a5a326244ddd.png">

**Comment by paoliniluis** [comment]
we return what the DW tells us, I guess this error does not have a line, can you check with a SQL client?

**Comment by aarthi-subramanian** [comment]
Hi, what is DW? Yes i can check my code using another editor but shouldnt have to right? Should be able to see in metabase right?

**Comment by paoliniluis** [comment]
DW = data warehouse

please check if you receive the error line from snowflake, if you do, we can return that line here, otherwise we cannot

**Comment by paoliniluis** [comment]
I think we should replace this one for https://github.com/metabase/metabase/issues/625
