### ISSUE TITLE
I often get a ~"unexpected '<EOF>'" error message when trying to reference another query

### ISSUE THREAD

**Issue by aarthi-subramanian** [metabase/metabase#30334]
### Describe the bug

Say i have a base query saved in metabase and it is #1212. If i open a new tab and query and try to reference this query via e.g. `SELECT * FROM {{ #1212 }} LIMIT 10`, i am getting an error message `SQL Compilation Error: syntax error line 257 position 8 unexpected '<EOF>'.` But i dont understand what this error message is? I get this often.

### To Reproduce

1. Create some base query and save it
2. Open a new tab and new query and try to reference the query from 1
3. Receive an EOF error message

### Expected behavior

I should be able to successfully reference another query with simple syntax OR i should receive a more helpful error message.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+0-adhoc..source",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+0-adhoc..source",
    "os.name": "Linux",
    "os.version": "5.4.84",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-07",
      "tag": "v0.46.1-SNAPSHOT",
      "branch": "release-x.46.metabot-alpha",
      "hash": "b96b662"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking

### Additional context

<img width="1077" alt="Screen Shot 2023-04-24 at 1 34 53 PM" src="https://user-images.githubusercontent.com/47357846/234075153-9d9855eb-ddc6-40df-b634-90793d1e819c.png">

**Comment by paoliniluis** [comment]
Is this v46.1 final? or you're running a specific branch?

**Comment by paoliniluis** [comment]
Just tried this with the sample dataset and I can do it without issues 
![image](https://user-images.githubusercontent.com/1711649/234122687-f82fee4b-d441-4f86-a924-22c4554bf0b2.png)

**Comment by aarthi-subramanian** [comment]
Wow i think i found it. 
* This is the end of my og query: <img width="606" alt="image" src="https://user-images.githubusercontent.com/47357846/235487292-9f13f5bd-439c-4e50-88b7-4546747f6100.png">
* This is my second query: <img width="908" alt="image" src="https://user-images.githubusercontent.com/47357846/235487566-5e5d49b0-012d-4c07-9b66-3009858ded4c.png">



If i REMOVE the comments at the end of the og query (remove lines 246-249), then the second query runs without error (no EOF error) 🤦 . Wow does this makes sense to us??

**Comment by aarthi-subramanian** [comment]
Also ^ does it make sense that the error message says line 251? Any way to clarify this/ write line 2 instead?

**Comment by aarthi-subramanian** [comment]
@paoliniluis anything we can do about this comment i made above? When referencing another query and you get an error message, the line number is not v helpful (it is counting the lines in the base query + new query). It should be line number within the current query. I can create a separate issue ticket if needed.

> Also ^ does it make sense that the error message says line 251? Any way to clarify this/ write line 2 instead?

**Comment by paoliniluis** [comment]
@aarthi-subramanian sure, thanks
