### ISSUE TITLE
Users with No Access to the Collection Our Analytics are not able to define a dropdown list from models/questions

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#30355]
### Describe the bug

Users with No Access to Collection Our Analytics are not able to define a dropdown list from models ... The reason seems to be that the first call 

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/110378427/234236540-f612291f-c64e-4e38-8420-b17877dc445e.png">

If you check the underlying calls the first call is a request to `api/collection/root` which will automatically load the Our Analytics. Failing with a permission error:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/110378427/234237196-ff2b333f-5e10-4470-befb-e35c52bb6976.png">

 

### To Reproduce

1. Go to New -> Collection -> New Collection
2. Go to People -> Groups -> New Group -> Name it Test and Save
3. Go to People -> People -> Invite Someone -> Add it to Group Test

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/110378427/234237618-aec60d16-7b62-4d34-8824-e15db63a6d85.png">

4. Go to Permissions -> Collections -> Give No Access to Test and All Users to Our Analytics -> Give Curate Access to Test Group for New Collection

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/110378427/234238703-3c368c73-b200-4585-8216-79ec977f9e61.png">

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/110378427/234238636-7e07a8a4-5d0d-48af-a045-a83169068f05.png">

5. Login As User -> New Dashboard -> Add a Text Filter -> Go to Edit Dropdown list -> From another model or Question -> Click on Pick a Model

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/110378427/234239473-43c7493c-5a38-4d5d-89bc-dd55911bd60f.png">

6. Notice it fails with a permission error:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/110378427/234239765-f8bda0d9-1679-40f6-bc32-7d2219007b2d.png">

### Expected behavior

Models or Questions are loaded from other collections 

### Logs

`WARN metabase.server.middleware.log GET /api/collection/root 403 16.1 ms (2 DB calls) 
"You don't have permissions to do that."`

### Information about your Metabase installation

```JSON
Able to replicate on 1.46.1 and master
```

### Severity

Will cause a lot of trouble for normal users trying this new feature

**Comment by gajanand-jm** [comment]
Just FYI - they can't access snippets as well
