### ISSUE TITLE
Support filtering by number/range on dashboard

### ISSUE THREAD

**Issue by stelio** [metabase/metabase#3035]
Dashboard filters are great!

Time, Location, ID and Other Categories already provide great functionality, but how about adding a simple range selector for integers and floats. Simple min and max inputs would do.

![screen shot 2016-07-26 at 11 51 54 pm](https://cloud.githubusercontent.com/assets/588196/17157234/5d24f5d2-538e-11e6-8273-47e4ea0af187.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by philip-n** [comment]
+1

This would be extremely useful for my use case too. Set up a general dashboard with various visualizations, then filter for things with a certain quantity (e.g. successful on the 1st, 2nd, 3rd, ... attempt). Or is this possible already in a different way?

**Comment by Rohith6215** [comment]
Do we have any update on this ? @stelio 

can you please help if there is any work around . @agilliland @tlrobinson

**Comment by az1611** [comment]
The filter is already available in the question editor and in the create segments/metrics in the data-model admin page, would be great to have it available as a widget for native query and dashboard too

**Comment by norbertbede** [comment]
Same here. My use case: I would like filter table customers by margin range then filter turnover  eg. > 10000 -> user can change it depends on requirement.

**Comment by fangjiangz** [comment]
is there any update for "Filter int/float range" feature?

**Comment by mauhcs** [comment]
bump
