### ISSUE TITLE
[MLv2] Let the FE find out default temporal bucket for a given column

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#30368]
Right now, people don't need to explicitly select temporal bucketing breakout columns. It's possible to click a column in the picker, and Metabase would use a default bucket. See the screenshot, "Created At" is not yet selected, but we can see we'll be using the "Month" bucket by default.

<img width="320" alt="CleanShot 2023-04-25 at 18 49 11@2x" src="https://user-images.githubusercontent.com/17258145/234360446-f318dc84-62c9-410f-86a9-a4ad0ca7785f.png">

The FE needs a way to retrieve the default bucket (could be a function or e.g. an `is_default` flag on temporal bucket objects)

AFAIK, it's driven by table metadata we retrieve via the `GET /api/table/:id/query_metadata` endpoint. E.g. see a JSON for Order's "Created At" column from the screenshot above:

<img width="620" alt="Dimension option properties in 'created at' field" src="https://user-images.githubusercontent.com/17258145/234361361-987ea823-df7c-4155-961f-111b0cfb6fa6.png">

<img width="620" alt="Dimension options in query metadata response" src="https://user-images.githubusercontent.com/17258145/234361370-4cba9d8a-8353-4e09-8fca-bc1e134b90d7.png">

**Comment by metamben** [comment]
@kulyk I've noticed that although option 13 ("Day") is returned as the default by the BE, the FE shows "by month". Why is that?
