### ISSUE TITLE
Some Oracle database tables are not synchronizing

### ISSUE THREAD

**Issue by tatusis** [metabase/metabase#30375]
**Describe the bug**
Some Oracle database tables are not synchronizing

We have a schema with 17 tables, 10 have synchronized and 7 have not. Synchronization ends successfully, but the tables do not load and do not appear in the error log.

We noticed that in the **metabase_table** table these tables are getting the entity_type field null.

**Expected behavior**
All tables granted to the connecting metabase user should be synchronized.

**Severity**
High

**Additional context**
Forcing the sync did not resolve the issue.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "pt",
    "user.timezone": "GMT-3"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "oracle",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-29",
      "tag": "v0.45.3.1",
      "branch": "release-x.45.x",
      "hash": "3b3097d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
What’s the name of those tables? Are they hidden? Or they simply don’t sync?

**Comment by calherries** [comment]
@tatusis I appreciate your patience on this. It is only possible to try re-sync a database from scratch by adding it as a new database with a different name. That might help you diagnose the issue but won't help you swap over all your questions.

Can you confirm whether or not you're still facing the issue? And have you noticed any pattern in which tables sync correctly and which tables don't?

**Comment by tatusis** [comment]
Hello, thanks for getting in touch. We are already using the latest version of Metabase v0.50. We are currently no longer experiencing this issue. If no one else has reported this issue, you can consider it resolved.

**Comment by calherries** [comment]
That's great news. Closing as resolved then
