### ISSUE TITLE
Markdown support in the pinned items

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#30381]
### Describe the bug

Markdown in the pinned items in the collection is rendered as a plain text

### To Reproduce

1. Create a modal with markdown in the description `Awesome description ## header [link](https://metabase.com)`
2. pin this model
3. check how description is rendered

![image](https://user-images.githubusercontent.com/125459446/234522675-0efc3ab3-d556-4220-8a5f-12be50ae343f.png)

### Desired behaviour

- Markdown in description is rendered correctly, but only the first line is shown with ellipses. e.g. `Awesome description…`
- tooltip with the rendered markdown is shown on hover over description

![image](https://user-images.githubusercontent.com/125459446/234523313-d3bbcbff-1501-4617-9a09-ce73476ff867.png)

**Comment by kamilmielnik** [comment]
Related conversation: https://metaboat.slack.com/archives/C04DAKFDTCZ/p1682377929948169?thread_ts=1682070352.558319&cid=C04DAKFDTCZ
