### ISSUE TITLE
Performance issue when using nested query based on question using variables

### ISSUE THREAD

**Issue by MarcSamD** [metabase/metabase#30411]
### Describe the bug

I have a SQL question using 2 Field Filter variables, one is mapped to a String field and the other is mapped to a Date field.
The fields are not required, and have no default value (so that it can be used in a nested query). Below the code used:
```
WHERE (
`source`.`fieldstring` IN (SELECT `table`.`fieldstring` FROM `table` WHERE {{VARNAME}} )
AND `source`.`fielddate` IN (SELECT `table`.`fielddate` FROM `table` WHERE {{MONTH}} )
)
```
Using this SQL question in a nested query makes the result very slow. When we look at the SQL code generated, we can see that Metabase is replacing the filters clauses using variables by 1=1:
```
WHERE (
`source`.`fieldstring` IN (SELECT `table`.`fieldstring` FROM `table` WHERE 1=1 )
AND `source`.`fielddate` IN (SELECT `table`.`fielddate` FROM `table` WHERE 1=1 )
)
```
Removing these useless filters will greatly improved the performance of the query:
![image](https://user-images.githubusercontent.com/70358310/234754837-409c983b-e306-4ffd-ae21-08ab61426e58.png)

### To Reproduce

1. Create a complex query with variables
2. Create a nested query based on it
3. Check the code of the nested query for "1=1" filters and observe the performance difference when removing them

### Expected behavior

Faster :)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "4.14.309-231.529.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-05",
      "tag": "v0.46.1",
      "branch": "release-x.46.x",
      "hash": "12a6e1d"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}
```

### Severity

Annoying

### Additional context

I understand that replacing a variable by 1=1 is much easier than removing all the clauses it is included in, and honestly I don't know with what kind of regexp or other way it could be done...

As a workaround, I guess that I could duplicate my initial query to use one with variables for end-users, and one without variables for all the nested queries. But the problem with duplicates is always the double work to maintain any change in the query.

**Comment by paoliniluis** [comment]
the "where 1=1" is generated when there are no values selected for those field filters, do you say that you would want the entire line to be removed?

also, can you check the query plans?

**Comment by MarcSamD** [comment]
Hi @paoliniluis 
> the "where 1=1" is generated when there are no values selected for those field filters, do you say that you would want the entire line to be removed?

Yes, as it seems that this "virtual filter" as significant performance impact on heavy queries compared to removing them or even to a query without filter at all. In my case, it uses 118s instead of 25s for 18665 rows and 62s instead of 17s for 461 rows.

I guess that it is because mysql will check for each rows if the field equal "1=1" (which obviously is true), and the cost will be multiplied for each unused variables you have.

> also, can you check the query plans?

I put the 2 query plans (type 1EQ1 with metabase "1=1" filters, and type "no filter" when I have commented these 2 lines).
So it is the very beginning of the query plan that is different, with 3 primary tables when using "1=1" filters, not sure if it helps.

Type | Order | id | select_type | partitions | type | key_len | rows | filtered | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
no filter | 1 | 1 | PRIMARY | NULL | ALL | NULL | 1.84467E+19 | 100 | Using filesort
no filter | 2 | 5 | DERIVED | NULL | ALL | NULL | 35443 | 33.33 | Using where; Using temporary
no filter | 3 | 5 | DERIVED | NULL | eq_ref | 4 | 1 | 79.01 | Using where
no filter | 4 | 5 | DERIVED | NULL | eq_ref | 4 | 1 | 100 | NULL
no filter | 5 | 5 | DERIVED | NULL | eq_ref | 4 | 1 | 88.89 | Using where
no filter | 6 | 5 | DERIVED | NULL | ref | 5 | 10 | 100 | Using where
no filter | 7 | 5 | DERIVED | NULL | ref | 5 | 18 | 100 | Using where
no filter | 8 | 5 | DERIVED | NULL | ref | 5 | 18 | 100 | Using where
no filter | 9 | 5 | DERIVED | NULL | ref | 5 | 194 | 100 | Using where
no filter | 10 | 5 | DERIVED | NULL | ref | 5 | 194 | 100 | Using where
no filter | 11 | 5 | DERIVED | NULL | ref | 5 | 194 | 100 | Using where
no filter | 12 | 5 | DERIVED | NULL | ALL | NULL | 90 | 100 | Using where; Using join buffer (hash join)
no filter | 13 | 5 | DERIVED | NULL | ALL | NULL | 185 | 100 | Using where; Using join buffer (hash join)
no filter | 14 | 5 | DERIVED | NULL | ref | 5 | 194 | 100 | Using where
no filter | 15 | 21 | SUBQUERY | NULL | ALL | NULL | 25425 | 1 | Using where; Using temporary
no filter | 16 | 19 | DERIVED | NULL | ALL | NULL | 975 | 19 | Using where; Using temporary
no filter | 17 | 17 | SUBQUERY | NULL | ALL | NULL | 25425 | 1 | Using where; Using temporary
no filter | 18 | 15 | SUBQUERY | NULL | ALL | NULL | 25425 | 1 | Using where; Using temporary
no filter | 19 | 13 | SUBQUERY | NULL | ALL | NULL | 25425 | 1 | Using where; Using temporary
no filter | 20 | 11 | DERIVED | NULL | ref | 4 | 12712 | 1.11 | Using where; Using temporary
no filter | 21 | 10 | DERIVED | NULL | ref | 4 | 10007 | 1.11 | Using where; Using temporary
no filter | 22 | 6 | DERIVED | NULL | ALL | NULL | 693 | 100 | Using temporary; Using filesort
no filter | 23 | 7 | DERIVED | NULL | ALL | NULL | 520 | 100 | NULL
no filter | 24 | 8 | UNION | NULL | ALL | NULL | 520 | 33.33 | Recursive; Using where
1EQ1 | 1 | 1 | **PRIMARY** | NULL | ALL | NULL | 14 | 100 | Using temporary; Using filesort; Start temporary
1EQ1 | 2 | 1 | **PRIMARY** | NULL | index | 4 | 35443 | 100 | Using index; Using join buffer (hash join)
1EQ1 | 3 | 1 | **PRIMARY** | NULL | ref | 4 | 5.20462E+14 | 10 | Using where; End temporary
1EQ1 | 4 | 5 | DERIVED | NULL | ALL | NULL | 35443 | 33.33 | Using where; Using temporary
1EQ1 | 5 | 5 | DERIVED | NULL | eq_ref | 4 | 1 | 79.01 | Using where
1EQ1 | 6 | 5 | DERIVED | NULL | eq_ref | 4 | 1 | 100 | NULL
1EQ1 | 7 | 5 | DERIVED | NULL | eq_ref | 4 | 1 | 88.89 | Using where
1EQ1 | 8 | 5 | DERIVED | NULL | ref | 5 | 10 | 100 | Using where
1EQ1 | 9 | 5 | DERIVED | NULL | ref | 5 | 18 | 100 | Using where
1EQ1 | 10 | 5 | DERIVED | NULL | ref | 5 | 18 | 100 | Using where
1EQ1 | 11 | 5 | DERIVED | NULL | ref | 5 | 194 | 100 | Using where
1EQ1 | 12 | 5 | DERIVED | NULL | ref | 5 | 194 | 100 | Using where
1EQ1 | 13 | 5 | DERIVED | NULL | ref | 5 | 194 | 100 | Using where
1EQ1 | 14 | 5 | DERIVED | NULL | ALL | NULL | 90 | 100 | Using where; Using join buffer (hash join)
1EQ1 | 15 | 5 | DERIVED | NULL | ALL | NULL | 185 | 100 | Using where; Using join buffer (hash join)
1EQ1 | 16 | 5 | DERIVED | NULL | ref | 5 | 194 | 100 | Using where
1EQ1 | 17 | 21 | SUBQUERY | NULL | ALL | NULL | 25426 | 1 | Using where; Using temporary
1EQ1 | 18 | 19 | DERIVED | NULL | ALL | NULL | 975 | 19 | Using where; Using temporary
1EQ1 | 19 | 17 | SUBQUERY | NULL | ALL | NULL | 25426 | 1 | Using where; Using temporary
1EQ1 | 20 | 15 | SUBQUERY | NULL | ALL | NULL | 25426 | 1 | Using where; Using temporary
1EQ1 | 21 | 13 | SUBQUERY | NULL | ALL | NULL | 25426 | 1 | Using where; Using temporary
1EQ1 | 22 | 11 | DERIVED | NULL | ref | 4 | 12713 | 1.11 | Using where; Using temporary
1EQ1 | 23 | 10 | DERIVED | NULL | ref | 4 | 10007 | 1.11 | Using where; Using temporary
1EQ1 | 24 | 6 | DERIVED | NULL | ALL | NULL | 697 | 100 | Using temporary; Using filesort
1EQ1 | 25 | 7 | DERIVED | NULL | ALL | NULL | 523 | 100 | NULL
1EQ1 | 26 | 8 | UNION | NULL | ALL | NULL | 523 | 33.33 | Recursive; Using where

**Comment by paoliniluis** [comment]
Ok, try changing your query to the following:
```
WHERE ( 1=1 AND
[[`source`.`fieldstring` IN (SELECT `table`.`fieldstring` FROM `table` WHERE {{VARNAME}} )]]
[[AND `source`.`fielddate` IN (SELECT `table`.`fielddate` FROM `table` WHERE {{MONTH}} )]]
)
```

**Comment by MarcSamD** [comment]
Hi @paoliniluis 
Sorry for the late reply, it was May 1st holiday, hopefully you can re-open this ticket.

I cannot run your query, it doesn't like the bracket and throws a SQL syntax error.
Note that the underlying DB is MySQL 8.

**Comment by MarcSamD** [comment]
@paoliniluis 

Thank you for your help, indeed it greatly increased the speed of the nested query and the 1=1 is not present anymore as all the optional clauses are directly removed from the nested query. A great feature to learn !

In details and for future reference, I changed a bit your code to:

> WHERE ( "_other existing filters so no need for 1=1_"
> [[**AND** `source`.`fieldstring` IN (SELECT `table`.`fieldstring` FROM `table` WHERE {{VARNAME}} )]]
> [[AND `source`.`fielddate` IN (SELECT `table`.`fielddate` FROM `table` WHERE {{MONTH}} )]]
> )
