### ISSUE TITLE
Google sign in not working when upgraded metabase from v0.42.0 to v0.46.1

### ISSUE THREAD

**Issue by siddhant-deepsource** [metabase/metabase#30430]
### Describe the bug

We have a self hosted version of Metabase deployed on our Kubernetes cluster using the [helm chart](https://github.com/deliveryhero/helm-charts/tree/master/stable/metabase). We earlier had the `v0.42.0` version of Metabase running internally but on upgrading it to `v0.46.1` the Google Sign in has stopped working. It shows a blank page on clicking on `Sign in with Google` and the following error can be found on console:
```
[GSI_LOGGER]: The given origin is not allowed for the given client ID.
```
Also, the request gets a ` 403 Forbidden` response.

FYI, metabase is deployed on `http` and not `https`.

### To Reproduce

1. Go to 'http://metabase.domain.xyz'
2. Click on 'Sign in with Google'
3. A blank page opens up with the error in console: `[GSI_LOGGER]: The given origin is not allowed for the given client ID.`

### Expected behavior

Google sign in should have worked.

### Logs

There's an error in the log but I am not sure if it should be related:
```
2023-04-28 07:04:00,018 ERROR driver.bigquery-cloud-sdk :: Database ID 12, which was migrated from the legacy :bigquery driver to :bigquery-cloud-sdk, has one or more OAuth style authentication scheme parameters saved to db-details, which cannot be automatically migrated to the newer driver (since it *requires* service-account-json intead); this database must therefore be updated by an administrator (by adding a service-account-json) before sync and queries will work again
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.170+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-05",
      "tag": "v0.46.1",
      "branch": "release-x.46.x",
      "hash": "12a6e1d"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

### Severity

High

### Additional context

Would be great if you can help us find out the cause and to solve it while keeping it on `http` and not `https`

**Comment by luizarakaki** [comment]
You should post this on the forum.

Never upgrade that many versions at once. You should upgrade one at a time. 42 > 43 > 44 > 45 > 46.
Google Sign In works fine on 46.

I believe there was a related bug that was fixed on 43.

So I suggest you restoring your backup on 42 and upgrade one version at a time.

**Comment by siddhant-deepsource** [comment]
@luizarakaki thanks for the response. Will keep in mind to post any queries further on the forum instead.

However, had one doubt that since I upgraded Metabase from v0.42 to v0.46 so in that case won't the migrations or changes would already be there in place? Would be great if you can help by sharing what I am missing here.

Thanks for all the amazing work y'all do on Metabase. Its a really helpful tool.

**Comment by paoliniluis** [comment]
You can upgrade many versions at a time, this issue is because we changed the Google OAuth2 client in v43 or 44 as the react component was changed. You need to review the Google Client ID that you set up and fix it

**Comment by vishesh-deepsource** [comment]
Hey @paoliniluis, thanks for getting back to us! Regarding the Google Client ID, we've tried:
- Deactivating and reactivating Google Authentication from Metabase
- Creating a new OAuth2 app on GCloud and using a fresh Client ID

But unfortunately that hasn't worked either. We're still stuck with the original error that was reported. Anything else you recommend we can give a go?

**Comment by vishesh-deepsource** [comment]
Does the new client by any chance require HTTPS? We're currently using an internal domain without TLS, and "Authorized JavaScript origins" section on the GCloud OAuth Application is set to reflect the same.

**Comment by Piccirello** [comment]
I'm receiving this error as well when using Firefox with Metabase. This is currently happening on v0.46.1, though this has been occurring for at least the last 3 months (I'm not sure if it ever worked in Firefox; that's just when we switched to using Google OAuth). I do not receive this error when using Safari or Brave, so I believe this is Firefox-specific.

<img width="1505" alt="metabase-firefox" src="https://user-images.githubusercontent.com/8296030/235803918-2e4eaadd-595d-4367-a71a-de3437ff1ed1.png">

**Comment by vishesh-deepsource** [comment]
We receive the error on all browsers unfortunately.
