### ISSUE TITLE
Empty schema aren't included in list of schema for CSV uploads

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#30459]
context: https://metaboat.slack.com/archives/C04S696LRUM/p1682689168952949

Currently, read-only metabase ignores empty schema (or schema that have tables without columns, I think), which makes a lot of sense from a UX perspective when you're browsing for tables. However, if you have created a new schema for CSV uploads (our most-likely user path), metabase doesn't know it exists, and we can't let users select it as an upload destination in settings. 

Also, I think even if you set it manually, metabase still thinks it doesn't exist and gives a `404 page not found` error for inserting a table into the schema it thinks doesn't exist.

Somehow, we need to create an awareness of all schema in metabase, without messing up the UX for situations where you actually do want to ignore empty schema.

One approach is to serve empty schema only when an API flag is set, e.g. `/api/database/{id}/schemas?include_empty=true`

**Comment by iethree** [comment]
This is likely related to https://github.com/metabase/metabase/issues/29931, and the solution could possibly address both issues.

**Comment by dpsutton** [comment]
We can list schemas like the following:

```clojure
describe-database=> (for [{:keys [id engine]} [{:id 1 :engine :h2}
                                               {:id 499 :engine :pg}
                                               {:id 352 :engine :mysql}]]
                      (with-open [conn (jdbc/get-connection (sql-jdbc.conn/db->pooled-connection-spec id))]
                        {:engine engine :schemas (into [] (all-schemas (.getMetaData conn)))}))
({:engine :h2, :schemas ["INFORMATION_SCHEMA" "PUBLIC"]}
 {:engine :pg,
  :schemas ["alt"
            "github_raw"
            "information_schema"
            "mb_models"
            "metabase_cache_084ac_2"
            "metabase_cache_1e483_19"
            "metabase_cache_1e483_225"
            "metabase_cache_4b4bb_3"
            "metabase_cache_54493_4"
            "metabase_cache_8f498_2"
            "metabase_cache_e449f_19"
            "pg_catalog"
            "public"]}
 {:engine :mysql, :schemas []})
```

Some obvious things to call out:
- mysql doesn't have schemas
- we need to remove metabase_cache schemas. These are owned by metabase and should not have user generated tables in them
- this only works for traditional sql jdbc drivers. Bigquery will need a custom solution

I think we can easily move forward on this. We should give the qp-drivers team a heads up on what we intend to do and see if they have objections/pointers and then get them to approve the ultimate PR. It's possible they will want to take it themselves (if it requires a new driver multimethod and they have to add the interface to documentation, driver developer mailing list, etc, don't like this approach, etc).
