### ISSUE TITLE
Date filters giving inconsistent results, depends on filter mode 

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#30454]
### Describe the bug

If I use the date filter mode "After" for the first day in the month I get what looks like the data I expect. However if I use "Between" with the same start date I'm getting records from the day before the start of that month. I've only seen this in data from our MSSQL data sources. 

This is likely timezone related, we're at GMT+12/13 which has confused Metabase before, but what I don't understand is why it's inconsistent.

Using "After":
![image](https://user-images.githubusercontent.com/4504437/235387387-f669c1a9-ceaf-4af8-a465-c7e853a5e63d.png)

Using "Between:
![image](https://user-images.githubusercontent.com/4504437/235387406-3067acce-0f0a-4781-b926-2ffdf0ef4a7f.png)

Note that the second image above includes a count from June.

Regardless of which filter mode I use above, clicking on the "View these XXX" from clicking on the July count bar takes me to this screen which includes the single record from June.
![image](https://user-images.githubusercontent.com/4504437/235387548-2a189771-e8db-49df-9b60-a6ae1c01d2be.png)

### To Reproduce

I don't have a good repro on the sample database as I think this may be an MS SQL Server specific issue. For a SQL Server connection this is a repro ...

1. Ensure you have data within the GMT offset hours prior to the start of a month e.g. 30 June, 23:00 if filter date will be 1 July.
2. Create a question counting rows per month using the between filter starting on the first day of the month used above, e.g. 1 July
3. You'll get at least one count reported in June

### Expected behavior

Date filters should be consistent and correctly applied.

### Logs

Nothing in the logs but these are the generated SQL queries (redacted, only relevant date specific parts)

Using After:
```sql
SELECT DateFromParts(year("xxx"."xxx"."DateReceived"), month("xxx"."xxx"."DateReceived"), 1) AS "DateReceived", count(*) AS "count"
FROM "xxx"."xxx"
LEFT JOIN "yyy"."yyy" 
WHERE (qqq
   AND "xxx"."xxx"."DateReceived" >= DateTimeOffsetFromParts(2022, 7, 2, 0, 0, 0, 0, 12, 0, 7))
GROUP BY year("xxx"."xxx"."DateReceived"), month("xxx"."xxx"."DateReceived")
ORDER BY year("xxx"."xxx"."DateReceived") ASC, month("xxx"."xxx"."DateReceived") ASC
```

Using "Between":
```sql
SELECT DateFromParts(year("xxx"."xxx"."DateReceived"), month("xxx"."xxx"."DateReceived"), 1) AS "DateReceived", count(*) AS "count"
FROM "xxx"."xxx"
LEFT JOIN "yyy"."yyy"
WHERE (qqq
   AND "xxx"."xxx"."DateReceived" >= DateTimeOffsetFromParts(2022, 7, 1, 0, 0, 0, 0, 12, 0, 7) AND "xxx"."xxx"."DateReceived" < DateTimeOffsetFromParts(2023, 5, 2, 0, 0, 0, 0, 12, 0, 7))
GROUP BY year("xxx"."xxx"."DateReceived"), month("xxx"."xxx"."DateReceived")
ORDER BY year("xxx"."xxx"."DateReceived") ASC, month("xxx"."xxx"."DateReceived") ASC
```

And for the drill through detail table:
```sql
SELECT TOP 1048575 "xxx"."xxx"."DateReceived" AS "DateReceived"
FROM "xxx"."xxx"
WHERE (qqq
   AND "xxx"."xxx"."DateReceived" >= DateTimeOffsetFromParts(2022, 7, 1, 0, 0, 0, 0, 12, 0, 7) AND "xxx"."xxx"."DateReceived" < DateTimeOffsetFromParts(2022, 8, 1, 0, 0, 0, 0, 12, 0, 7)) 
```

You can see these use a mixture of `DateTimeOffsetFromParts(2022, 7, 1, 0, 0, 0, 0, 12, 0, 7)` and `DateTimeOffsetFromParts(2022, 7, 2, 0, 0, 0, 0, 12, 0, 7)`.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

### Severity

This is blocking some users or causing them to have to double check data. It's giving inconsistent data, sometimes applying filters incorrectly.

### Additional context

This may be a regression but I can't find specific issues relating to this.

**Comment by notrom** [comment]
Also having issues with "Specific date" between filters and "Relative date".

Relative previous 2 months as at May 2023:
```sql
WHERE ("source"."DateReceived" >= DateFromParts(year(dateadd(month, -2, getdate())), month(dateadd(month, -2, getdate())), 1)
   AND "source"."DateReceived" < DateFromParts(year(getdate()), month(getdate()), 1)
```
Specific dates between 1st March 2023 - 30th April 2023:
```sql
WHERE ("source"."DateReceived" >= DateTimeOffsetFromParts(2023, 3, 1, 0, 0, 0, 0, 13, 0, 7)
   AND "source"."DateReceived" < DateTimeOffsetFromParts(2023, 5, 1, 0, 0, 0, 0, 12, 0, 7)
```

The latter incorrectly gives me records from the last few hours of Feb 28th. It's giving me the wrong answers.

I'd really love for this to at least be triaged. @flamber

**Comment by notrom** [comment]
Still broken in v0.47:
![image](https://github.com/metabase/metabase/assets/4504437/7a5c56b3-1bc6-40fe-97a1-e17c4c677211)

Anyone from Metabase want to take a look? I've provided quite a bit of info, not sure what more I can do here.

Pretty sure I just need the between filter to use `DateFromParts()` without the offset. I think "before" and "after" filters are working as expected.

**Comment by paoliniluis** [comment]
Context: https://github.com/metabase/metabase/issues/26947

**Comment by ignacio-mb** [comment]
Changing to P1 as this is confusing users showing wrong results. 

More context: I reproduced in SQL server with a Date field without a timezone, and the DateTimeOffsetFromParts function is grabbing by reporting timezone to run the query (GUI, not happening in SQL), and as I'm in timezone -3 and the Date without timezone is interpreted as 00:00:00, if I filter by the exact date those dates will not appear. 

For reference:
 
<img width="483" alt="Screenshot 2023-11-14 at 4 04 47 PM" src="https://github.com/metabase/metabase/assets/132273646/5894c221-524b-4cb8-8c7d-e78cfa0bdd5a">

<img width="501" alt="Screenshot 2023-11-14 at 4 04 59 PM" src="https://github.com/metabase/metabase/assets/132273646/8ef0b67d-c2d1-4894-b0c5-a88568358eda">

Showing no results when filtering by using a date that should bring results
<img width="868" alt="Screenshot 2023-11-14 at 4 05 35 PM" src="https://github.com/metabase/metabase/assets/132273646/b3107640-d67b-4326-bd11-4cae945fd8ed">

**Comment by luizarakaki** [comment]
related? #37065

**Comment by robswanLL** [comment]
Still broken in v0.48.5 as per [discourse discussion updates](https://discourse.metabase.com/t/date-filter-between-is-incorrectly-giving-me-data-outside-of-the-date-range/35407/7)

**Comment by Felipe-Hub** [comment]
I also have a similar issue, where if I filter by previous month I get some data from the last the of the month before the previous month (the timezone between clickhouse db and metabase instance are different)

<img width="332" height="662" alt="Image" src="https://github.com/user-attachments/assets/4b416f65-89e0-43f2-b55c-9ec4fe201028" />
