### ISSUE TITLE
[MLv2] Add a function to get a list of columns referenced by a clause

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#30466]
The FE needs a way to find out which columns are used by a clause. For instance, when opening a query with a breakout, we'd like to highlight the column used by the breakout clause. Example:

```ts
import * as Lib from "metabase-lib"

const [breakout] = Lib.breakouts(query);

// I didn't put a lot of thought into the name here,
// please use whatever makes more sense
const [column] = Lib.clauseColumns(query, breakout);
```

**Comment by metamben** [comment]
We have solved the problem in a different way, implemented in #30573.
