### ISSUE TITLE
Reverting a revert of a dashboard leaves dashcards displaying permissions errors

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#30524]
### Describe the bug

Text boxes or link cards on a dashboard are cleared and show permissions error messages if you revert a revert on the dashboard's history.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/39073188/235935557-b319b744-78ca-4288-8d3a-1012fc4bb890.png">

### To Reproduce

1. Create a new dashboard. Save it without adding anything.
2. Edit the dashboard, adding a text box or link card to the dashboard. Save.
3. Click on the "More info" button, and revert to the first history entry, "You created this". The card in step 2 should disappear.
4. Revert to the "You added a card" history entry. The card in step 2 should appear again, but showing the permissions error.

Opening the network tab and inspect the requests for `GET /api/dashboard/:id` after step 2 and step 4. You'll notice after step 2 has the `ordered_cards` in the response has a `visualization_settings` map with data about the card, but the response after step 4 doesn't. 

e.g. 
Before:
![image](https://user-images.githubusercontent.com/39073188/235936695-cf5db9d9-7458-4436-a49c-3b95b575d927.png)

After:
![image](https://user-images.githubusercontent.com/39073188/235936727-9a140e5d-1079-4037-922a-477a2b808415.png)

### Expected behavior

Reverting a revert should bring the dashboard to exactly the same state as before.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-LTS",
    "os.name": "Mac OS X",
    "os.version": "12.5.1",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.5 (Homebrew)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-04-28",
      "src_hash": "c4679e338017fdf94a6e7fe2a3cd0b864713c8d8",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "use-model-metadata-for-implicit-actions",
      "hash": "990fc8e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Able to be worked around, but annoying

**Comment by qnkhuat** [comment]
fixed by https://github.com/metabase/metabase/pull/31118
