### ISSUE TITLE
Adding columns with More Columns stops working after columns hidden on Saved Question datasets (missing join warning)

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#30546]
### Describe the bug

- If a user joins two tables and then saves as a question, and then uses that save question to make a new question, the columns from the right side of the join show up in Table Visualization Settings > More Columns even after they are added.
- If the columns are then hidden, they show up twice in the list of Table Visualization Settings > More Columns
- Attempts to add the columns back do not work through Table Visualization Settings > More Columns

Workaround is to add the columns back through the query editor.

### To Reproduce

1. Create a saved question joining People to Accounts on ID = ID in the Sample Database called `Accounts + People`
2. Create a new question using the saved question `Accounts + People`, click Visualize to see the resulting table.
3. Click ⚙️ Settings to see the initial problem, More columns in the left panel shows columns that are already in the list of Columns
![image](https://user-images.githubusercontent.com/8808703/236037683-8c2b6423-a85e-4149-98f7-f82e1bfd1559.png)

4. Hide some of the columns prefixed with "People" by clicking 👁️‍🗨️  icon, and notice that they show up twice in the list of More columns below.
![image](https://user-images.githubusercontent.com/8808703/236037966-57a47240-16bc-4b61-b5de-8ea1ccb00294.png)

5. Click the Preview button (the More columns list shortens, removing the new elements added by hiding in the prior step)
![image](https://user-images.githubusercontent.com/8808703/236038484-0054f173-da4f-44db-a447-1ca57d8e43d4.png)

6. Try to add back some of the columns that were hidden by clicking + in the list of More columns, they are not added back, and there is a console error:
- in 1.45.3.1:
![image](https://user-images.githubusercontent.com/8808703/236038646-47460bf0-6dae-44ff-b260-69d7630b1c08.png)

- in `master` as of 2023-05-03:
![image](https://user-images.githubusercontent.com/8808703/236039870-08a2bb00-f9d0-4371-b0f0-5fe7c7479708.png)

### Expected behavior

- Expect More columns not to list columns that are already shown, expect it to not list elements twice when hidden, expect it to add columns back when + is clicked.

### Information about your Metabase installation
- Metabase version: 1.45.3.1 and `master` as of 2023-05-03

### Severity

P2

**Comment by garrrychan** [comment]
I'm also experiencing this on 1.46.6 (July 2023)

**Comment by likeshumidity** [comment]
Similar to https://github.com/metabase/metabase/issues/31321

**Comment by likeshumidity** [comment]
Appears to be fixed in v1.46.6, reproduction steps no loner produce issue.

**Comment by likeshumidity** [comment]
Occurring again in x.47.4

**Comment by kamilmielnik** [comment]
Reproducible in 0.45.3.1.
Fixed in `master` ([d35c779](https://github.com/metabase/metabase/commit/d35c779976ae6bd79369e9cc6bec8540908f37d2)):
- there is no "more columns" section anymore
- there is no need to click "preview" anymore

Marking as fixed in the next version (48).
Closing.

**Comment by snoe** [comment]
I believe this test will cover the use case even if the gui no longer breaks fields out in this way.
https://github.com/metabase/metabase/blob/869ec6951bdf604cf17b878c7d3a18c22daaa225/test/metabase/lib/card_test.cljc#L199-L214
