### ISSUE TITLE
static viz: Stacked area charts with 100% stacking show up in alerts/subscriptions as regular stacking

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#30551]
### Describe the bug

- Area charts with 100% Stacking show in alerts/subscriptions as regular Stacked.

Saved Question:
![image](https://user-images.githubusercontent.com/8808703/236072979-702eac49-2a34-45a6-8d77-6be48d66fc75.png)

Alert/Subscription generated image:
![image](https://user-images.githubusercontent.com/8808703/236073000-2317a83c-57a5-4078-b2b7-722a86928795.png)

### To Reproduce

1. Create a saved question from Analytic Events in the Sample Database summarized with Count grouped by Timestamp (binned by Day) and Event
2. Call  `GET /api/pulse/preview_card_png/:id` for that card to see the image generated for alerts/subscriptions

### Expected behavior

Expect appearance to retain the 100% stacked setting

### Logs

#N/A

### Information about your Metabase installation

```JSON
- Metabase version: 1.46.2 and `master` as of 2023-05-03
```

### Severity

P3

### Additional context

related to:
- https://github.com/metabase/metabase/issues/26769

**Comment by zbodi74** [comment]
Raised the priority as there are multiple customers affected.
