### ISSUE TITLE
Multiple consecutive spaces are condensed into a single space in UI

### ISSUE THREAD

**Issue by jmaslin** [metabase/metabase#30555]
### Describe the bug

Multiple consecutive spaces in a string are being condensed into a single space when displayed in the user interface. This can lead to confusion and incorrect data representation, especially when dealing with queries that search for specific patterns, such as a specific number of spaces between words.

### To Reproduce

1. Create a table with a column containing strings with multiple consecutive spaces. Example: `John   Smith` (with three spaces between "John" and "Smith")
2. Run a query to select rows from the table.
3. View the results in Metabase's UI. It will display as `John Smith` (with one space between "John" and "Smith")

### Expected behavior

The UI should display the string with the correct number of consecutive spaces, preserving the original data representation.

### Information about your Metabase installation

```JSON
Metabase version: v0.46.1
Browser: Chrome 112.0.5615.49
Operating System: macOS Ventura Version 13.2.1 (22D68)
Database: Postgres 14.7
```

### Severity

Low

**Comment by paoliniluis** [comment]
I think this is the same as https://github.com/metabase/metabase/issues/30351
