### ISSUE TITLE
BigQuery Connection issue with Date Parameter

### ISSUE THREAD

**Issue by nhatquangtn** [metabase/metabase#30602]
### Describe the bug

When using DATE parameter in BigQuery connection, Metabase automatically adds timezone as REPORT TIMEZONE (we chose Asia/Saigon), so with BigQuery DATE default function convert it to UTC and it is not correct date for end users.
Example: 
current_date: 08 May 2023 18:00:00
DATE filter: 08-05-2023
BigQuery query: select {{date}}, DATE({{date}}), DATE({{date}}, 'Asia/Saigon')
=> the result: 
May 8, 2023, 00:00
May 7, 2023
May 8, 2023

Note: metabase version v0.46.1

Attachment files: 
![image](https://user-images.githubusercontent.com/44966383/236815132-1be49175-f80d-49fa-a4f2-875bb7dd1b99.png)

### To Reproduce

When using DATE parameter in BigQuery connection, Metabase automatically adds timezone as REPORT TIMEZONE (we chose Asia/Saigon), so with BigQuery DATE default function convert it to UTC and it is not correct date for end users.
Example: 
current_date: 08 May 2023 18:00:00
DATE filter: 08-05-2023
BigQuery query: select {{date}}, DATE({{date}}), DATE({{date}}, 'Asia/Saigon')
=> the result: 
May 8, 2023, 00:00
May 7, 2023
May 8, 2023

Note: metabase version v0.46.1

Attachment files: 
![image](https://user-images.githubusercontent.com/44966383/236815132-1be49175-f80d-49fa-a4f2-875bb7dd1b99.png)

### Expected behavior

Correct date with config timezone. We did not see this issue in older version (v0.43.4)

### Information about your Metabase installation

```JSON
- Chrome
- MacOS
- BigQuery connection
- Metabase version v0.46.1
- Metabase hosting env: Docker container in Ubuntu server
- Metabase internal database: Postgresql
```

### Severity

Blocking users when using parameter with BigQuery connection

### Additional context

Please review and fix it asap, thank you  <3

**Comment by thoaih** [comment]
I have the same issue

**Comment by luizarakaki** [comment]
I can repro

Redshift, the date filter is created as `date`. It creates a timestamp only if a time is added.
![image](https://github.com/user-attachments/assets/44bd5bfe-0787-49ed-a2c0-29e7390957cf)

BigQuery always create timestamps
![image](https://github.com/user-attachments/assets/5ef8d569-adbd-4115-93ee-ee181212d06d)
