### ISSUE TITLE
Events *created* outside of the date filter aren't shown

### ISSUE THREAD

**Issue by JonCrawford** [metabase/metabase#30638]
### Describe the bug

There appears to be a bug where an event's _creation_ date is used to decide if it's shown on a report whereas the _occurred_ date should be used. It is displayed on the correct date when it's not filtered out by the _creation_ date.

### To Reproduce

1. Create an Event for a past date
2. Create a date-filtered line graph that excludes today's date.
4. You'll see that the event does not show on the graph.

### Information about your Metabase installation

```JSON
- Metabase version: v1.46.2
```

### Severity

Low

**Comment by paoliniluis** [comment]
Hi Jon, events appear only if what's on the y-axis is on the same time frame as the event, have you checked that?

**Comment by JonCrawford** [comment]
Yes for instance, our Event was 4/20/23. The date range was “last 6 months”. The event did not appear until I removed the date filter.

**Comment by paoliniluis** [comment]
Sorry, closing this one, I triaged it by mistake. I just tested and it works as it should
