### ISSUE TITLE
Make it easier to deploy Metebase in real production environments (allow configuration via file, allow configuration of logging to file, add startup scripts)

### ISSUE THREAD

**Issue by alexis-via** [metabase/metabase#3063]
Metabase seems a really great software with a nice documentation, but I'm having a hard time deploying it in production on a Linux server. It's very easy to run Metabase from the command line with logs on stdout, but, when you deploy Metabase in production, you need a startup script, the ability to log to a file and the ability to start the process in the background. This is not explained in the installation documentation. In the github repo, there are some startup scripts docker/heroku, but not for a regular Linux server.

Moreover, I think that, for production deployments, it would be easier to have a configuration file that could be used instead of only the environment variables, because it is not possible to see/verify the value of the environment variables when Metabase is run in the background.

**Comment by tlrobinson** [comment]
@alexis-via thanks for the feedback.

Ease of deployment is definitely one of the things we care a lot about.

Some of the decisions like logging to stdout and using environment variables for configuration are based on "12 factor" app methodology http://12factor.net/

Regarding configuration file and logging, a simple way to accomplish that is with a simple wrapper shell script, e.x.

```
#!/bin/sh

export LOGFILE = metabase.log
export MB_DATABASE_URL = "...";
export MB-JETTY_PORT = 5000;

exec java -jar metabase.jar > "$LOGFILE"
```

**Comment by tlrobinson** [comment]
A list of things I think we *could* (but not necessarily *should*) do:

* document recommendations for deploying to "bare" Linux servers (i.e. if you don't have Docker or a Java servlet container or whatever)
* have a configuration file
* allow (or just document?) configuring logging to files etc via log4j
* provide init/upstart/whatever scripts for common Linux distributions
* daemonization?

**Comment by salsakran** [comment]
@alexis-via we've generally encapsulated our idea of what a "production" deployment looks like in our docker image. It's what we run internally, and has been pretty stable over the last 12-18 months of running it in production for multiple companies.

The ElasticBeanstalk recipe is exactly what we use internally, and while ElasticBeanstalk is not without its quirks, it does what it says on the tin.

With respect to specifics of daemonization, logging, etc, we don't really have a specific opinion and figure if you want to do that you have your own opinions on how things should be run anyway. We're more than happy to include an init or upstart script if you're willing to contribute one. It's really just a question of how much surface area we want to make part of the product deployment scripts.

**Comment by alexis-via** [comment]
Thanks to all of you for your answers. I was not aware of the "12 factor" app methodology. After reading your answers, I think that the issue I raise is mainly a documentation issue ; we need to explain that logging to stdout, reading the config in environment variable, the missing daemon mode is an explicit strategy, even if it can be very surprising to good old sys admins.

I'll try to start Metabase via a simple script similar to the one suggested by @tlrobinson.

**Comment by poblin-orange** [comment]
Agreed. A simple list of available properties would be helpful for packaging and understand the operation level available config. Hopefully the properties can bypass the interactive first boot setup ?

**Comment by camsaul** [comment]
We already have an open issue for letting someone configure Metabase via a file: #2052.

You can configure logging any way you like by specifying a custom log4j properties file:

```bash
java -Dlog4j.configuration=file:/path/to/custom/log4j.properties -jar metabase.jar
```
Our log4j properties file is [here](https://github.com/metabase/metabase/blob/master/resources/log4j.properties); you can use that as a starting-off point.

**Comment by camsaul** [comment]
As mentioned elsewhere in this issue, it could be helpful to have a list somewhere documenting all available configuration options; I've opened this as a separate issue: #3294
