### ISSUE TITLE
Full-app embedding using iframe-resizer shrinks iframe height to 150-300px and does not resize larger

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#30634]
### Describe the bug

- When using [iframe-resizer](https://github.com/davidjbradshaw/iframe-resizer) or [iframe-resizer-react](https://github.com/davidjbradshaw/iframe-resizer-react) with full-app embedding, the iframe height is 150-200px and does not resize to full height of application

### To Reproduce

1. Start with [app-embed-example from sso-examples](https://github.com/metabase/sso-examples/tree/master/app-embed-example).
2. Update Enterprise token in `/app-embed-example/docker-compose.yaml`
3. Run `npm install iframe-resizer-react`
4. Run `docker compose up -d`
5. Edit `/app-embed-example/src/MetabaseAppEmbed.js` to add the following:
```diff
diff --git a/app-embed-example/src/MetabaseAppEmbed.js b/app-embed-example/src/MetabaseAppEmbed.js
index 8ec1b7d..da5bbf8 100644
--- a/app-embed-example/src/MetabaseAppEmbed.js
+++ b/app-embed-example/src/MetabaseAppEmbed.js
@@ -1,4 +1,5 @@
 import React, { useEffect, useRef, useState } from "react";
+import IframeResizer from "iframe-resizer-react";
 
 const MetabaseAppEmbed = ({
   title = "Metabase",
 
@@ -78,13 +79,21 @@ const MetabaseAppEmbed = ({
       ? fitHeight
       : undefined;
 
+  const safeOrigins = [
+    "http://localhost:3000",
+    "http://localhost:3001",
+    "http://localhost:3002",
+  ];
+
   return (
-    <iframe
-      ref={iframeEl}
+    <IframeResizer
+      forwardRef={iframeEl}
+      heightCalculationMethod={"max"}
+      log
+      checkOrigin={safeOrigins}
+      autoResize={true}
       src={src.current}
-      title={title}
-      className={className}
-      style={{ border: "none", width: "100%", height: height, ...style }}
+      style={{ border: "none", width: "1px", minWidth: "100%", ...style }}
     />
   );
 };

```
6. Run `npm run dev` and open the resulting app (for me at localhost:3001)
7. Open the embedded Metabase page like http://localhost:3001/analytics
8. See the iframe height is 150px
![image](https://github.com/metabase/metabase/assets/8808703/1adbd2f1-6690-403e-8985-d8b9d0b0634e)

9. Click New Question in the navigation and refresh the page, click Accounts and the page will resize to 278px of height.
![image](https://github.com/metabase/metabase/assets/8808703/47173271-9f5f-497c-ba0b-2ca08cc35dda)

### Expected behavior

Expect height to be larger so that more of the Metabase interface is visible

### Logs

![image](https://github.com/metabase/metabase/assets/8808703/d976d515-820c-4620-babb-eb53046edeed)
![image](https://github.com/metabase/metabase/assets/8808703/c7450176-a885-40cf-9f43-adbba9761944)
...
![image](https://github.com/metabase/metabase/assets/8808703/becca890-8bf7-4cc7-9159-622904eac4da)

### Information about your Metabase installation

- Metabase versions: v1.46.2 and v1.46.1

### Severity

- unable to use supported iframe-resizer to set height dynamically, blocking a customer embed scenario where they are switching from signed embedding (where this works) to full-app embedding (where this does not work)

**Comment by paoliniluis** [comment]
@likeshumidity if you leave the attributes as they are, shouldn't iframe-resizer to the resizing completely automatically? asking this as I think this is an implementation error rather than an error on our end

**Comment by albertoperdomo** [comment]
Did this work for you @likeshumidity ? Can this be closed?

**Comment by albertoperdomo** [comment]
The way to handle resizing with interactive embedding is not using iframe-resizer, but using postMessage. See [docs](https://www.metabase.com/docs/latest/embedding/interactive-embedding#supported-postmessage-messages-from-embedded-metabase).
