### ISSUE TITLE
Remove "your" from x-ray templates

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#30647]
Per [this conversation](https://metaboat.slack.com/archives/C04TW1NRJA2/p1678981665609339), we want to remove colloquial "your X" type language from x-ray templates.

Approach: Where "your" has no added meaning (E.g. `A look at your X`), just drop your (E.g. `A look at X`). Where "your" can't just be dropped, replace it in favor of a concise, correct, descriptive template (E.g. `Where most of your sessions originate from` to `Where most sessions originate`).

This is probably the most relevant portion of the convo:

![Image](https://user-images.githubusercontent.com/8381441/237205891-4098ba44-0e60-4199-9061-1a2f85e1f006.png)

**Comment by darksciencebase** [comment]
closing as https://github.com/metabase/metabase/pull/30713 is merged
