### ISSUE TITLE
Extra left property on the floating filter with FullApp embedding when visiting dashboards via in-app navigation

### ISSUE THREAD

**Issue by ewu5** [metabase/metabase#30645]
### Describe the bug

We do FullApp embedding with `top_nav`, `search` and `new_button` set to `true`.
On a  dashboard page with vertical scroll, filters are floating on the top with extra left property, so the floating filters are not fully occupied the width and left a weird space on the left side.

### To Reproduce

1) set up the embedding demo with `top_nav`, `search` and `new_button` set to `true`.
2) create a question and save it, add it to a dashboard  lotsa times till you have a scrollbar and then add a few filters (no need to connect those)
3) enter via the embedding and click on the dashboard, you should be seeing the filters going to the right

### Expected behavior

The filters should float on the top with no gap on the left

### Information about your Metabase installation

```JSON
- Browser: Chrome Version 112.0.5615.137
- Metabase version: v1.46.1
- FullApp embedding with `top_nav`, `search` and `new_button` set to `true`
```

EDIT: a comeback from https://github.com/metabase/metabase/issues/26229 but now with the filters on the other side :D

![image](https://github.com/metabase/metabase/assets/1711649/8064c164-007f-4205-a210-5c8bcba67169)

**Comment by chetan-habu** [comment]
1)![image](https://github.com/metabase/metabase/assets/107653462/70e7ce4e-f4c1-46cd-ac8d-319f1af78b89)
screenshot 1 is when you open the dashboard.
2)![image](https://github.com/metabase/metabase/assets/107653462/109bb31c-3a0f-4c94-a4f1-8da64bfa5799)
screenshot 2 is when you scroll down

**Comment by WiNloSt** [comment]
This PR fixes the issue on 46 https://github.com/metabase/metabase/pull/32881. And the fix is already included in version *.46.7
