### ISSUE TITLE
Datetime with MongoDB

### ISSUE THREAD

**Issue by hoangtrongphuc** [metabase/metabase#3064]
I use metabase to query MongoDB, but I cannot get filter by date with Datetime field.
Example : I have record "createdAt" : "2012-12-30 12:22:21", when I filter with createAt, I cannot filter by Past 7 Day, ToDay, Past30 Day... I only can filter by Isnot, NotEmpty.
So what is format Date in mongo to metabase can filter by Date ?

**Comment by camsaul** [comment]
Is `createdAt` a string or an actual [MongoDB Date](https://docs.mongodb.com/manual/reference/method/Date/)??

**Comment by hoangtrongphuc** [comment]
I use deployd, createdAt is object field, I use dashboard to edit record with value "2012-12-30 12:22:21".
But when query with metabase, I cannot filter by Date, I only use filter by String

**Comment by camsaul** [comment]
@hoangtrongphuc When you put in in Mongo did you put it in as just a plain string 

```
"2012-12-30 12:22:21"
```

or did you put it in as [an actual `Date`](https://docs.mongodb.com/manual/reference/method/Date/)?

```
new Date("2012-12-30 12:22:21")
```

**Comment by hoangtrongphuc** [comment]
I put in plain string because I update directly in database dashboard, not API.

**Comment by camsaul** [comment]
Unfortunately Metabase doesn't currently support converting strings to dates, only using the native MongoDB Date type. We have an issue open to address this: #1576

**Comment by camsaul** [comment]
Closing as duplicate  of #1576
