### ISSUE TITLE
Invalid query generated in v46 with BigQuery

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30648]
### Describe the bug

I hit the issue that a customer was seeing with BigQuery in 46 (not seen in v45), but I'm not still sure what's the issue and the relationship with https://github.com/metabase/metabase/issues/30610

### To Reproduce

Check question 9514 and all dependencies

### Expected behavior

Query should be generated correctly

### Information about your Metabase installation

```JSON
Mb: Master
Brave
```

### Severity

P1

**Comment by darksciencebase** [comment]
https://stats.metabase.com/question/9514-a-repro-bik-card-413

It loads for a while, then fails with an error

`400 Bad Request POST https://www.googleapis.com/bigquery/v2/projects/metabase-bigquery-driver/queries { "code": 400, "errors": [ { "domain": "global", "location": "q", "locationType": "parameter", "message": "Name address not found inside source at [2:1167]", "reason": "invalidQuery" } ], "message": "Name address not found inside source at [2:1167]", "status": "INVALID_ARGUMENT" }`

**Comment by john-metabase** [comment]
It looks like something is adding spaces inside of quoted identifiers in the generated native query, e.g.:

```
SELECT
  ` source `.` category ` AS ` category `
```
