### ISSUE TITLE
Activity Feed not loading

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3065]
Building master locally and using Chrome.

When loading the app, I see this, and get the error: `Cannot read property 'attrs' of undefined`
![screen shot 2016-07-28 at 10 47 17 am](https://cloud.githubusercontent.com/assets/2223916/17223304/d26e08ba-54b0-11e6-8857-cd20b89419cd.png)

If I navigate to another section of the app and then try clicking on the logo to go to the Activity Feed, nothing happens.

**Comment by mazameli** [comment]
If I load the app using Safari, I get: `undefined is not an object (evaluating 'icon.attrs')`

Firefox says `icon is undefined`

**Comment by camsaul** [comment]
@mazameli @tlrobinson was this fixed by #3066 ?

**Comment by tlrobinson** [comment]
yes
