### ISSUE TITLE
Show dependent Questions based on saved Questions

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#30679]
**Is your feature request related to a problem? Please describe.**
If I build a saved question called `user_churn_events`, is there a good way to see all future questions that depend on `user_churn_events`?

This would be a great way for me as the manager of our data-warehouse to understand which questions to move into our dbt warehouse.

**Describe the solution you'd like**
- I think a really powerful feature would be a dependency graph for metabase questions. Can we see for a given question/sql query, what the downstream queries are that query against the saved question?

**Describe alternatives you've considered**
- Manually constructing and running queries against Metabase application database.

**How important is this feature to you?**
- Helpful for data infrastructure maintenance

**Additional context**
- Customer request

**Comment by paoliniluis** [comment]
Is this the same as https://github.com/metabase/metabase/issues/27106 or https://github.com/metabase/metabase/issues/13139 or https://github.com/metabase/metabase/issues/7569?

**Comment by brunobergher** [comment]
Yeah, aeems kike a dupe. And whole not complete, you can see a list of questions based off of a model in the model detail page. It doesn't keep going downstream (or up stream), but is a first step in providing this kind of insight.

**Comment by likeshumidity** [comment]
Duplicate of [#27106](https://github.com/metabase/metabase/issues/27106)
