### ISSUE TITLE
Whitespaces getting into the SQL

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30676]
### Describe the bug

Between 45 and 46 we seem to have introduced a regression where we enter whitespaces in schema/table references.

E.g. 46
SELECT
  ` source `.` id ` AS ` id `,

vs 45
SELECT
  `source`.`id` AS `id`,

### To Reproduce

Just build a query with a BQ db both in 45 and 46

### Expected behavior

Whitespaces shouldn't be there

### Information about your Metabase installation

```JSON
MB 46
```

### Severity

P3

**Comment by luizarakaki** [comment]
Moving this to a P2 as this is very annoying for BigQuery users
