### ISSUE TITLE
Can't enable model action

### ISSUE THREAD

**Issue by Eliagandolfi** [metabase/metabase#30684]
**Describe the bug**
After updating to v0.46.2, the button to enable model action ion PostgreSQL is blanked out, and I can't enable them. 

**To Reproduce**
1. A `metabase` role exist with usage privileges on all schemas and select privileges on all tables in schema
2. A metabase_action role with write privileges on a given schema is created, and granted to `metabase`
```
CREATE ROLE metabase_actions WITH LOGIN;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO metabase_actions;
GRANT metabase_actions TO metabase;
```

4. In the Metabase admin panel- > databases, I manually sync the database schema
5. The button is still blanked out

**Expected behavior**
Database actions can be enabled for my PostgreSQL dabatase

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "4.14.281-212.502.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-28",
      "tag": "v0.46.2",
      "branch": "release-x.46.x",
      "hash": "8967c94"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by Tony-metabase** [comment]
Hey!

If you try to Enable/Disable Model Actions from the sample Database does it work there?

<img width="1206" alt="image" src="https://github.com/metabase/metabase/assets/110378427/03c0a655-5fc8-425c-8fa4-64add372f87a">

**Comment by Tony-metabase** [comment]
That is a good question! I doubt it's permission issue cause i would expect an error on that + you are granting almost everything to the user:

`GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO metabase_actions`

I believe both users of those DBs where granted the same Roles right? ... Is the version the same? anything distinctive between the two which you can point out

**Comment by Eliagandolfi** [comment]
Hi Tony

- I confirm it's definitely not permissions, as I tried to connect with the db superuser and still doesn't work
- The db settings from the metabase side are exactly the same
- The only difference I noticed
```
# PRODUCTION DB (actions not working)
psql (14.1, server 13.7)
SSL connection (protocol: TLSv1.2)
Host: RDS (AWS)

# APP DB (actions working)
psql (14.1, server 12.14 (Ubuntu 12.14-1.pgdg20.04+1))
SSL connection (protocol: TLSv1.3)
Host: Heroku
```

Can it be due to any of the differences above?

**Comment by Tony-metabase** [comment]
Hmmm shouldn't be the case but i will test that as well ... I believe you have access to the application Database right? Can you compare the entries of the two Database the one that enables model and the one that doesn't ... Is it possible to share the output here? (off course removing any sensitive info)

<img width="1171" alt="image" src="https://github.com/metabase/metabase/assets/110378427/9fe55526-af41-452e-a721-54bdf765b6a9">

**Comment by paoliniluis** [comment]
@Eliagandolfi do you have any frontend logs or backend logs you can share? also anything you see in the database that might be worth mentioning?

**Comment by Eliagandolfi** [comment]
@Tony-metabase the only different in the two database is exactly in the settings columns. And, the database not working has `unfolding:True` in the description columns
<img width="756" alt="Screenshot 2023-05-11 at 15 58 51" src="https://github.com/metabase/metabase/assets/47365996/00647596-efd8-4dad-8b4e-5ab05e766e88">

@paoliniluis sorry, which logs do you mean? The metabase machine? Or all the database logs?

**Comment by Tony-metabase** [comment]
@Eliagandolfi i believe you are hitting this https://github.com/metabase/metabase/issues/30699 can you confirm?

**Comment by Eliagandolfi** [comment]
oh that's it, good catch @Tony-metabase

**Comment by Tony-metabase** [comment]
Thanks! :D ... Glad I was able to help
