### ISSUE TITLE
Export settings: users, databases, questions, dashboards

### ISSUE THREAD

**Issue by imsky** [metabase/metabase#3074]
Is there a way to export settings like users, databases, questions, and dashboards, so that another Metabase instance could be recreated with the same settings?

**Comment by camsaul** [comment]
@imsky You can just do a SQL dump of the Metabase database and then load that into another DB. Are you using Postgres, MySQL, or the default H2 database to run Metabase?

**Comment by imsky** [comment]
using Postgres while running Metabase on Elastic Beanstalk. i've had issues with pg_dump/pg_restore being unpredictable, so it'd be great if there was a short guide on best practices of exporting/importing Metabase databases.

**Comment by Slayr** [comment]
+1 to that! We plan to use multiple metabase deployments on elastic beanstalk with a similar set of users and this would be a great feature to have. 

Also helps us recover in the event the eb environment needs to be rebuilt, which happened while I was upgrading to v18.1

**Comment by mazameli** [comment]
What's the main use case you guys have for running multiple instances? One for testing, one for real? Or as a substitute for a permission system due to the current lack of one in MB?

**Comment by Slayr** [comment]
Yes, primarily as a substitute for the permission system - one each for senior management, dept heads and analysts.

**Comment by Slayr** [comment]
Another use case would be the ability to recover in case a deployment/ upgrade goes awry, imagine every time we rebuild, having to start inviting users and create database connections and questions all over again.

**Comment by mazameli** [comment]
Thanks for the info!

**Comment by linusl** [comment]
Another use case is this:
I've been testing out the app with a local database and now I want to move those questions to a production instance. It would be great if I wouldn't have to rewrite all the questions and instead just export/import them.

**Comment by camsaul** [comment]
@linusl, we actually implemented a feature that lets you migrate from a local H2 database to Postgres or MySQL a while back: http://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

As mentioned for Postgres -> Postgres or MySQL -> MySQL you should just use their respective dump and restore commands.

**Comment by efron** [comment]
Hi @camsaul how do we run those parameters you mentioned from an AWS Elastic Beanstalk Container Deployment?

> @linusl, we actually implemented a feature that lets you migrate from a local H2 database to Postgres or MySQL a while back: http://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres
> 
> As mentioned for Postgres -> Postgres or MySQL -> MySQL you should just use their respective dump and restore commands.

**Comment by camsaul** [comment]
@efron are you using H2 in your elastic beanstalk deployment?

**Comment by efron** [comment]
yes @camsaul, it was installed by default when we launched it in the wizard. H2 contains both the demo database as well as the configs to be exported like users, databases, questions, dashboards, right?

**Comment by camsaul** [comment]
By default it uses Postgres for the application DB. The demo database is H2 but it's contained within `metabase.jar` so you don't need to migrate that

**Comment by efron** [comment]
oh, I see. But where in Metabase we find the application Postgres DB? @camsaul 

It was made a while ago by another person and as we have other postgres databases we are not finding which one is Metabase's database and how to access it.

**Comment by camsaul** [comment]
Check in your RDS panel

**Comment by efron** [comment]
Yes, we found that Postgres database, but is there any kind of default password or something to access it? because its weird we don't have any register of it.. Is that password set by the Metabase deployment script? @camsaul

**Comment by camsaul** [comment]
Hey @efron sorry but I am super busy getting out 0.29 release ready so I recommend you ask on our Discourse site here for help http://discourse.metabase.com/

**Comment by efron** [comment]
I understand @camsaul , I'm really sorry to bother you, I apologize for that... we also have some urgency on migrating that configs because we need to generate some reports that couldn't be generated in Elastic Beanstalk due to some timeouts there we couldn't fix, even after having invested a lot of time trying to make it work. Then we deployed Metabase in a normal EC2 instance and it's working fine in that server, no timeouts, however we're still struggling to migrate to that EBS obscure deploy to the EC2 server deploy...

**Comment by sameersegal** [comment]
We are planning to use Metabase as a multitenant solution to complete our multitenant enterprise product. Users have access to only their database instance.

**Comment by leekocytes** [comment]
@sameersegal Do you have any update on how you are managing this today? Would love it if you could share how you are setting this up as I am trying to figure out the architecture pattern for multitenant with metabase as well with the proper security separation between tenant's data but using common metrics, etc for all tenants. Thanks for any guidance!

**Comment by sethia** [comment]
Has there been any update on this feature? We were looking to start another instance of metabase and retain users and settings etc

**Comment by flamber** [comment]
@sethia 
You can duplicate the database and use the [API](https://github.com/metabase/metabase/wiki/Using-the-REST-API) to make further changes.
There's a third part project about export/import: https://github.com/elevate/elevate.metabase.tools

**Comment by sbelak** [comment]
Note that we're also experimenting with a feature along these lines in our Enterprise Edition: https://github.com/metabase/metabase/blob/master/docs/enterprise-guide/serialization.md

**Comment by KidA001** [comment]
To be honest I'm a bit disappointed that there is no supported way to export/import or move config across environments. We want to replicate our dashboards in our QA and Production environments and it's cumbersome to keep both in sync or use thrid-party tools. Multiple environments is pretty standard.

**Comment by mazameli** [comment]
@KidA001, for a while now we've had an Enterprise Edition feature, serialization, which sounds like what you might be looking for: https://www.metabase.com/docs/latest/enterprise-guide/serialization.html 

Hope that helps.
