### ISSUE TITLE
Update admin settings activation checklist items

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#30765]
## Context
Follow-up to [this project](https://www.notion.so/metabase/Guide-people-away-from-H2-and-more-7084fa0559d04b66978c1d155327abc8?d=1f622765fcf64e1ebe8860911f0984e8).

Let’s take the opportunity to clean up the checklist by:

- Removing “Create Metrics” and “Create Segments”
- Adding
    -  **Create a Model**
    - Set up friendly starting points for your team to explore data
    - Link to `/model/new`, which shows an educational modal.
    - Shown when there are zero models in the instance

**Comment by calherries** [comment]
@cdeweyx Double checking - the title should be "Create a model", not "Create a Model" I think. All other titles have no capitalization after the first letter, e.g. "Create segments" and "Organize questions".

**Comment by cdeweyx** [comment]
> the title should be "Create a model"
Yeah that's correct, nice catch
