### ISSUE TITLE
Support Table Scanning for Partitioned Tables

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#30767]
**Is your feature request related to a problem? Please describe.**
We run Metabase on BigQuery with a mandatory filter on the date column. This leads to the issue that Metabase cannot scan the tables to retrieve values for a category for easy filtering.

When clicking on a column on a table view or in trying to filter in the Query Builder everything has to be typed and this takes a lot of time and create a lot of room for error.

**Describe the solution you'd like**
Support partitioned tables so this is fixed

**How important is this feature to you?**
Very important, impacts me daily.

**Comment by paoliniluis** [comment]
Is this the same as https://github.com/metabase/metabase/issues/26627?
