### ISSUE TITLE
The "it's okay to play around with saved questions" message is appearing when it shouldn't

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3078]
This is on `release-0.19.0`.

The behavior of the message should be that you only ever see it the **very first time** you ever go to a saved question detail page. What's happening instead is that during the initial session after you log in to a new account (or maybe when you first initialize an instance?) you see this message every time you go to _any_ saved question. It stops happening if you close the window and relaunch the app.

![screen shot 2016-07-29 at 3 07 48 pm](https://cloud.githubusercontent.com/assets/2223916/17264877/eea10b6a-559e-11e6-9e61-2f2754839811.png)

**Comment by salsakran** [comment]
is #3119 ready to merge? I'm seeing this in 0.19.2

**Comment by salsakran** [comment]
This is still occurring. The message goes away if the session is ended and restarted.

**Comment by mazameli** [comment]
Did we verify that #3484 fixes this? Shall I close?

**Comment by tlrobinson** [comment]
Yeah
