### ISSUE TITLE
When modifying the type of fields in MySQL view tables, BI does not synchronize.

### ISSUE THREAD

**Issue by dashi6174** [metabase/metabase#30783]
**Describe the bug**
When modifying the type of fields in MySQL view tables, BI does not synchronize.

**Logs**
none

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Ubuntu-0ubuntu120.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Ubuntu-0ubuntu120.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-135-generic",
    "user.language": "zh",
    "user.timezone": "Asia/Chongqing"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.33-0ubuntu0.20.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-29",
      "tag": "v0.45.3.1",
      "branch": "release-x.45.x",
      "hash": "3b3097d"
    },
    "settings": {
      "report-timezone": "Asia/Chongqing"
    }
  }
}
```

**Comment by calherries** [comment]
Hi @dashi6174, can you add more information to help diagnose the issue? 
1. Are you talking about modifying the type of the column in the MySQL database, or the "Field Type" in Metabase's Admin Settings?
2. Is this a problem for only certain types of fields, or all fields in a view? 
3. Can you share the full schema of the view? The output of `SHOW CREATE VIEW view_name` would be very helpful
4. If you can, please share the logs that happen during sync. You can find them by clicking "Sync database schema now" on the database page and go to Admin Settings > Troubleshooting > Logs.

**Comment by calherries** [comment]
Closing this in the absence of more details. @dashi6174 feel free to open it again if you have more information to help us diagnose the issue
