### ISSUE TITLE
Snowplow: Creating and deleting dashboard tabs

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#30791]
Details linked below:
- [ ] [Dashboard tab created](https://www.notion.so/metabase/Dashboard-tab-created-efd196c90d694efeb1b594f308f29fd5?pvs=4)
- [ ] [Dashboard tab deleted](https://www.notion.so/metabase/Dashboard-tab-deleted-60efb251281441fe8c0820cf70ee6236?pvs=4)

**Comment by qnkhuat** [comment]
maybe this should be done in BE instead?

**Comment by cdeweyx** [comment]
> maybe this should be done in BE instead?

Yeah, actually you're right. This is probably easier on the BE. I'll update the epic.

**Comment by qnkhuat** [comment]
Implemented in https://github.com/metabase/metabase/pull/30844
