### ISSUE TITLE
Snowplow: Index model entities

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#30794]
Details linked below:
- [ ] [Index model entities enabled](https://www.notion.so/metabase/Index-model-entities-enabled-15c56cbe632342968a4cfca41021d5a3?pvs=4)

**Comment by iethree** [comment]
While this is triggered on the front end, it actually happens on the backend. Seems like the event should happen there?

https://www.notion.so/metabase/Snowplow-integration-5da1f874beda4153b4fccfa6c1e77caa

anyway, depends on https://github.com/metabase/metabase/pull/30487 getting merged
