### ISSUE TITLE
Bar visualization x axis with numbers tried to convert to date

### ISSUE THREAD

**Issue by davidvirgilnaranjo** [metabase/metabase#30842]
### Describe the bug

The  bar visualization fails when grouping with one column that is a string column, but if the first row from the result set contains in that column a number then it fails with this error:
![Screenshot 2023-05-18 at 07 51 03](https://github.com/metabase/metabase/assets/107469028/4fd88067-9856-4898-bb23-26c79f0413fe)

Here you can see the results displayed as a table:
![Screenshot 2023-05-18 at 07 56 50](https://github.com/metabase/metabase/assets/107469028/97b53e2a-8912-468f-a961-d0884b1441e1)

This is the question:
![Screenshot 2023-05-18 at 07 51 53](https://github.com/metabase/metabase/assets/107469028/a2e32b46-bab0-4b1e-9072-d35f2ba1180a)

If we ignore the values that are numbers then it displays correctly the results:
![Screenshot 2023-05-18 at 07 59 01](https://github.com/metabase/metabase/assets/107469028/84b39b2a-27f3-4e9b-b52b-23fb8cc326f7)

![Screenshot 2023-05-18 at 07 59 30](https://github.com/metabase/metabase/assets/107469028/eb5b5608-8f5e-4bd8-80c5-a76e2bf56642)

Same happens if we sort the results so the numeric values appears at the end. 

### To Reproduce

1. Create a question and group by a column that is a string column, but that contains some numeric values as a string. 
2. Make sure that in the result set the results are sorted having the number values at the top.
3. Display with a bar visualization, selecting as the x axis 2 columns, having the first column the one with the numeric values.
![Screenshot 2023-05-18 at 08 03 27](https://github.com/metabase/metabase/assets/107469028/9ea180a5-6ad4-4c12-bd13-30ba054ee090)

### Information about your Metabase installation

```JSON
Metabase 0.46.2 

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.0-1009-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.5 (Debian 13.5-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-28",
      "tag": "v0.46.2",
      "branch": "release-x.46.x",
      "hash": "8967c94"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Medium

**Comment by Tony-metabase** [comment]
Hi David,

Can you share the axis setting for x-axis? Is it ordinal or timestamp?

**Comment by paoliniluis** [comment]
@davidvirgilnaranjo are you able to reproduce this with the sample database? I was trying to reproduce this to prioritize it thanks!

**Comment by davidvirgilnaranjo** [comment]
It was fixed once modifying the x-axis. Thank u @paoliniluis  and @Tony-metabase
