### ISSUE TITLE
Building with the root Dockerfile doesn't generate the version.properties correctly

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30865]
### Describe the bug

I don't know why but when you build via the Dockerfile which is on the root, you don't get the version.properties correctly populated

### To Reproduce

1) check out a tag
2) do "docker build ."
3) run the image, you won't get the version populated

### Expected behavior

In the same way you get the version when building from the host, you should get the version in the container

### Information about your Metabase installation

```JSON
-master
```

### Severity

P3

**Comment by filipesilva** [comment]
Interestingly enough, `docker build .` does not work on either `v0.46.4` (from last week) or `v0.46.2` (from last month).

Both fail with this error:
```
#0 319.6    "fatal: detected dubious ownership in repository at '/home/node'"
#0 319.6    "To add an exception for this directory, call:"
#0 319.6    ""
#0 319.6    "\tgit config --global --add safe.directory /home/node"
```

Some more information on this error with docker: https://www.kenmuse.com/blog/avoiding-dubious-ownership-in-dev-containers/

Does running `docker build .` work for you?
