### ISSUE TITLE
Upgrade to 1.46 fails due to invalid state in permissions table

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#30872]
### Describe the bug

Previously we used to allow to have two paths that are identical except for the value after /schema/ in the permission table.

For example in the first path there's no value, and in the second path there is a value:

`/db/67/schema//table/283/query/segmented/`(no schema)
`/db/67/schema/dwh_name/table/283/query/segmented/`

Seems we used to allow this behaviour before 1.46.2 but not anymore since the upgrade fails

### To Reproduce

Not sure how to insert these kind of entries in the DB but there are people that have this issue. One such case in [stats](https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6ODM0NCwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiwyODkxMjUsbnVsbF0sImFrdGl2byJdXSwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJicmVha291dCI6W1siZmllbGQiLDI4ODYwNCxudWxsXV19LCJkYXRhYmFzZSI6NDV9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLmNvbHVtbl93aWR0aHMiOls1MzRdfSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=):

When upgraded to 1.46.3 from 1.45.3.1 it started to fail with:

```
Reason: liquibase.exception.DatabaseException: ERROR: more than one row returned by a subquery used as an expression [Failed SQL: (0) UPDATE sandboxes s SET permission_id = (

Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::v46.00-066::noahmoss:
```

### Expected behavior

Upgrade works

### Information about your Metabase installation

```JSON
Migration from 1.45 to 1.46
```

### Severity

some customers are stuck in 1.45

**Comment by hilarudeensaktivo** [comment]
Hi Team, 

looks like, this is happening on every time when metabase release on after 1.45. is there any resolution?

**Comment by paoliniluis** [comment]
@hilarudeensaktivo this happens only if you used the api to add permissions and you left the permissions table in an invalid state

**Comment by hilarudeensaktivo** [comment]
@paoliniluis how do i resolve the issue? can you provide some steps?

**Comment by paoliniluis** [comment]
@hilarudeensaktivo go to your permissions table in the app db, try looking for a permission that has a "//" string, delete that permission, backup the DB first

**Comment by hilarudeensaktivo** [comment]
@paoliniluis could you elaborate `permissions table in the app db`? 
we are using bigquery to feed data to metabase. i don't see any permission table anywhere.
