### ISSUE TITLE
Question with source query containing aggregation and sorting by that aggregation fails on mongodb

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#30874]
### Describe the bug

MBQL question with `:source-query` containing `:aggregation` and sorting by that aggregation fails on mongodb.

### To Reproduce

Open some mongo dataset in query builder.

1. Create question with aggregation and sort by that aggregation.

<img width="1127" alt="Screenshot 2023-05-19 at 13 33 47" src="https://github.com/metabase/metabase/assets/8920752/14deff72-9555-415e-96a3-bf543b4bd0a5">

2. Save question.
3. Use that question as a source for another question.
4. Run the question and see the error.

<img width="838" alt="Screenshot 2023-05-19 at 13 38 10" src="https://github.com/metabase/metabase/assets/8920752/e7e16eae-7d85-475a-b6e3-f0ac172fa354">

### Expected behavior

This action should be executable without an error.

### Information about your Metabase installation

```JSON
- metabase version: master e06c9673f8
```

### Severity

I guess P2

**Comment by paoliniluis** [comment]
fixed with https://github.com/metabase/metabase/pull/30877
