### ISSUE TITLE
Add export to PDF in Signed/Public embeddings

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30889]
**Is your feature request related to a problem? Please describe.**
Our current export to PDF solution will only be available in Full app embedding. Creating this request to see how many users would like the same feature in public/signed embeddngs

**Describe the solution you'd like**
Include export to PDF in signed/public embeddings

**Describe alternatives you've considered**
The old but good puppeteer

**How important is this feature to you?**
NA

**Additional context**
NA

**Comment by EuanKirkhope** [comment]
Option to email pdf also welcome.  Especially for outlook users, where all the charts are broken.
