### ISSUE TITLE
Absolute links don't work on link cards when Metabase is on a sub-path

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30893]
### Describe the bug

Entire repro is on https://github.com/metabase/metabase/issues/30891

### To Reproduce

1) set up Metabase on a sub-path with https://github.com/paoliniluis/metabase-subpath
2) create a dashboard and a link to an absolute URL
3) try to click that link it won't work

### Expected behavior

it should take the user to the absolute path

### Information about your Metabase installation

```JSON
1.46.2
```

### Severity

P1

**Comment by cdeweyx** [comment]
@ranquild @NevRA Does this make sense for our team to take on? I see it was removed from our board and I can't quite recall why.
