### ISSUE TITLE
Relative links inside tables get encoded characters and fail

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#30894]
### Describe the bug

full repro is on https://github.com/metabase/metabase/issues/30891

### To Reproduce

1) create a question
2) create another question, this question needs to have a relative link to the first question (you can make the link easily with a "concat(relativeurl, "")"
3) format the relative url as a link in the table
4) try clicking the link, see that fails because of the encoded character

### Expected behavior

why are we encoding certain characters on the table links?

### Information about your Metabase installation

```JSON
NA
```

### Severity

P2

**Comment by albertoperdomo** [comment]
I was reproducing this, so leaving here a few tips for reproduction based on my understanding:
After creating the 2nd question with the relative URL, you need to format the column like this (hit cog icon the column header):

<img width="404" alt="image" src="https://github.com/metabase/metabase/assets/24216/edf8372a-b8ec-47f1-a6fc-4067a44bf991">

Even though the link text looks fine, the actual URL is actually encoded. 

The URL `/question/103-products` points to `http://localhost:3000/%2Fquestion%2F103-products`. It seems the slash symbol is being escaped.

**Comment by heypoom** [comment]
@albertoperdomo thank you for reproducing this! I wasn't aware that parameters could be applied to the fields, learned something new today 😄
