### ISSUE TITLE
Visualization bug on stacked graphs - Tooltip Error

### ISSUE THREAD

**Issue by fdevillalobos** [metabase/metabase#30906]
### Describe the bug

In any stacked graph that comes from a query with multiple group by columns, the tooltip only shows the value one of the values of the group by column that is not the one defining the stacked area.

Example:
`SELECT
    DATE(s.created_at) AS date
    ,p.restaurant
    ,s.sale_type
    ,pm.name AS payment_method
    ,SUM(p.amount) AS sales
    ,COUNT (DISTINCT p.uuid) AS num_sales

FROM payments p
    LEFT JOIN sales s ON p.sale_id = s.uuid
    LEFT JOIN payment_methods pm ON p.pay_method_id = pm.uuid

WHERE s.sale_state = 'CLOSED'
    AND {{restaurant}}
    AND {{sale_type}}
    AND {{payment_method}}

GROUP BY date, p.restaurant, s.sale_type, payment_method
ORDER BY date DESC, p.restaurant`
---------------------------------------------
This query has the number of sales and sales (in money) from several restaurants, grouped by the restaurant, the sale type and the payment method.
Here we are going to do a stacked graph on payment method for example:

<img width="1461" alt="image" src="https://github.com/metabase/metabase/assets/6305634/da34178f-5030-4ba9-8583-19ffdc320278">
Here we can clearly see the stacked graph, by payment method. Amazing.
Let focus for example in May 13th. If we follow the dotted line, we should see that the sales amount was about 230 to 240k. But when we look at the tooltip...

<img width="503" alt="image" src="https://github.com/metabase/metabase/assets/6305634/00f6e00a-2cba-40d7-9fb4-ac9e83e0372b">
We see here that the tooptip shows us sales only for 137k (52k Efectivo, 62k MercadoPago, 23k Tarj Debito). Upon further inspection of the table view:
<img width="877" alt="image" src="https://github.com/metabase/metabase/assets/6305634/99334675-83ce-40b3-8d84-c674c87cdef7">
We see that what the tooltip is showing is Efectivo and Tarj. Debito for Marina Market, and Mercado Pago for The Craft. This is the first entry for each of them. Correct output should be that it has too add all Efectivo values for all restaurants for the date.

This happens to me in a LOT of graphs. Tooltip only shows the first value of the second group by column.
Graph still appears correctly and is adding correctly in the visual part. The problem is the tooltip, which is still what most of users use.

### To Reproduce

1. Go to create new query.
2. Create a New Query that has more than one column in the GROUP BY clause, and at least one SUM or COUNT column
3. Create stacked or stacked 100% graph
4. Look at the tooltip in any date
5. Compare to table view

### Expected behavior

Tooltip should be adding all the registers with the desired value and adding them instead of only taking the first register for each one

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "4.4.302+",
    "user.language": "en",
    "user.timezone": "America/Argentina/Buenos_Aires"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3 (Debian 15.3-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-05-18",
      "tag": "v0.46.3",
      "branch": "release-x.46.x",
      "hash": "8d74de2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying, users complain a lot. Several errors in analysis because incorrect numbers were copied

**Comment by luizarakaki** [comment]
Reproduced on the sample dataset


![Image](https://github.com/metabase/metabase/assets/32561114/a388191c-0402-4c4c-94bd-730f5415a299)

2026 Basic shows 477k while is should show 477k + 121k

![Image](https://github.com/metabase/metabase/assets/32561114/0cd3eda5-5001-41b1-861a-799d2385da57)

**Comment by luizarakaki** [comment]
![Image](https://github.com/metabase/metabase/assets/32561114/83cb01eb-1e95-43f1-9eeb-ef6170a1eba2)
