### ISSUE TITLE
[MLv2] [Bug] `long-display-name` should keep the LHS part when coming from a source question

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#30948]
Follow up on #30857

### To Reproduce

1. New > Question > Sample Database > Orders
2. Join the Products table
3. Save the question
4. New > Question > Saved Questions > pick the question you just created
5. Click the "Pick a column to group by" in the summarization section of the editor
6. Click the "Product → Category" column

**Expected:** the clause should be called "Product → Category" as in the source question
**Actual:** the clause is called "Category"

[Related e2e test](https://github.com/metabase/metabase/blob/26b01750e98b328cdd19ca09bb2cb2cc1a51de5e/e2e/test/scenarios/question/nested.cy.spec.js#L272)

**Comment by camsaul** [comment]
I'm having trouble reproducing this

<img width="944" alt="image" src="https://github.com/metabase/metabase/assets/1455846/347e8661-c18d-40af-81c6-61cb51b9aed9">

**Comment by kulyk** [comment]
@camsaul I assume you're testing on `master`? It works as expected there, but we have a [failing e2e test](https://github.com/metabase/metabase/blob/c0c9511d779ed9b4905be1f35bff184587b69efc/e2e/test/scenarios/question/nested.cy.spec.js#L272) because of it on MLv2 breakouts branch #30693

**Comment by kulyk** [comment]
Fixed in #31312
