### ISSUE TITLE
Bug in mini bar chart toggle on dashcard viz settings

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#30966]
### Describe the bug

On a dashboard card, if you toggle the mini bar chart viz setting for a column, it requires two separate clicks to enable/disable. The first click moves the toggle but doesn't affect the setting, and the second click affects the setting. 

### To Reproduce

1. Create a dashboard and add a table card to it
2. Go to Visualization Options (on the dashcard) and click the ... on a numerical column to open its viz settigns
3. Try to toggle the mini bar chart option 

### Expected behavior

Toggle should work like normal

### Information about your Metabase installation

```JSON
Current master
```

### Severity

P3, but weird

**Comment by npfitz** [comment]
This is actually a slightly larger issue than it initially appeared to be. Due to my terrible code with the settings popover widget, changing any nested setting on a dashcard is very, very annoying and prone to not really working.
