### ISSUE TITLE
Can't add dashboard level filter

### ISSUE THREAD

**Issue by coussej** [metabase/metabase#3096]
I can't create a dashboard level filter. This is my dataset:

```sql
CREATE TABLE batchprops (id serial, description text, ts timestamptz, ammonium float, nitrogen float);  
INSERT INTO batchprops (description, ts, ammonium, nitrogen)
  VALUES 
    ('testbatch 1', '2016-06-30 00:21', 0.83, 0.80)
  , ('testbatch 2', '2016-07-10 00:21', 0.85, 0.95)
  , ('testbatch 3', '2016-07-11 00:21', 0.86, 0.98)
  , ('testbatch 4', '2016-07-20 00:21', 0.81, 0.94)
  , ('testbatch 5', '2016-07-21 00:21', 0.80, 0.96);
```
I created a line plot (with no filters) line mentioned in issue #3095. Then, I added this question to a new dashboard and tried adding a filter to that dashboard. Both for the a timebased filter as an ID based filter, it tells me there are no valid fields in my question to filter on. When I try to apply the same filters on the question level, everything works fine.

<img width="550" alt="screen shot 2016-08-02 at 09 31 14" src="https://cloud.githubusercontent.com/assets/9944663/17320646/eba77518-5894-11e6-9b12-8df3d1a6cd3a.png">

*  ~~I am using the ___________ browser.~~
*  My computer's OS is OSX El Capitan.
*  I'm running Metabase locally with the Mac App and it is using the H2 database.
*  My data is in a Postgres database. 
*  My Metabase version is 0.19.

**Comment by mavimo** [comment]
@camsaul @tlrobinson this issue can be closed? I see the related MR is merged in the release branch (same for #3090 and #3095)

**Comment by tlrobinson** [comment]
Yup thanks

**Comment by HugoPouliquen** [comment]
I can't create a dashboard level filter too.

My sql query : 
```SELECT table2.CompanyName AS CompanyName, table1.EstimatedRevenue AS Revenue FROM table1 LEFT JOIN table2 ON table1.CustomerId=table2.CustomerId WHERE CompanyName is not null```

![fieldsbug](https://user-images.githubusercontent.com/7288882/27549973-356f4fa2-5a9e-11e7-96e8-88204083a290.JPG)
