### ISSUE TITLE
run "yarn build-hot" happened error

### ISSUE THREAD

**Issue by WSYProject** [metabase/metabase#30970]
### Describe the bug

 Error building classpath. Unable to clone /Users/zhangyewei/.gitlibs/_repos/https/github.com/metabase/hawk 
[cljs] error: RPC failed; curl 28 Recv failure: Operation timed out 
[cljs] fatal: expected 'packfile'

### To Reproduce

1. dowload "metabase-master" folder
2. run "yarn"
3. run "yarn build-hot"
4. See error " Error building classpath. Unable to clone /Users/zhangyewei/.gitlibs/_repos/https/github.com/metabase/hawk 
[cljs] error: RPC failed; curl 28 Recv failure: Operation timed out 
[cljs] fatal: expected 'packfile'"

### Information about your Metabase installation

```JSON
// OS X 
last version
// Chrome version
113.0.5672.126
// node -v
v18.16.0
// yarn -v
1.22.19
// npm -v
9.5.1
// java -version
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
// clojure -version
Clojure CLI version 1.11.1.1273
```

### Severity

I want run frontend developmemnt environment

**Comment by paoliniluis** [comment]
Seems to be a network error, try again or with a different dns/connection

**Comment by WSYProject** [comment]
Thank you，I'll try again

**Comment by WSYProject** [comment]
Set default language in code
 I set the default value of "site local" in the  /src/metabase/public_settings.clj file, it still displays English

**Comment by paoliniluis** [comment]
@WSYProject please read the development documentation
