### ISSUE TITLE
[MLv2] [Bug] Clauses using breakout columns are not updating on bucket change

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#30980]
Clauses using columns with a temporal bucket or binning applied, don't update when the column's bucket is changed

## To Reproduce

1. New > Question > Raw Data > Sample Database > Orders
2. Add any standard aggregation
3. Breakout by "Created At" by Month (any bucket can work really)
4. Order by "Created At"
5. Change the "Created At" column bucket to Quarter (any other bucket can work)

**Expected:** the order-by clause displays "Created At: Quarter" now
**Actual:** the order-by clause displays the original temporal bucket (Month)

Note: this happens for binnable columns as well

## Demo

https://github.com/metabase/metabase/assets/17258145/6aa812ed-c4e2-440b-a49f-8b7ed42d4ced

**Comment by metamben** [comment]
@kulyk can you list the (MLv2) calls you make in this scenario? E.g., do you remove the breakout clause (this should clean up the query), and add a new one? (In that flow I would expect the order by to disappear when the breakout clause is removed.)

**Comment by kulyk** [comment]
@metamben the FE uses `replace-clause` for updates; to reproduce, start a query from sample orders table, and do the following:

```js
// Add a breakout
const createdAt_breakoutable = ML.breakoutableColumns(query).find(
  c => ML.displayInfo(q, c).name === "CREATED_AT"
)
const bucketMonth = ML.availableTemporalBuckets(query, createdAt_breakoutable).find(
  b => ML.displayInfo(q, b).displayName === "Month"
)
const createdAt_month = ML.withTemporalBucket(createdAt_breakoutable, bucketMonth)
const query2 = ML.breakout(query, createdAt_month)

// Add an order-by

const createdAt_orderable = ML.orderableColumns(query).find(
  c => ML.displayInfo(q, c).name === "CREATED_AT"
)
const query3 = ML.orderBy(query2, createdAt_orderable)

// Update breakout column's bucket

const breakoutClause = ML.breakouts(query3)[0]
const createdAt_breakoutable_2 = ML.breakoutableColumns(query).find(
  c => ML.displayInfo(q, c).name === "CREATED_AT"
)
const bucketQuarter = ML.availableTemporalBuckets(query, createdAt_breakoutable_2).find(
  b => ML.displayInfo(q, b).displayName === "Quarter"
)
const createdAt_quarter = ML.withTemporalBucket(createdAt_breakoutable_2, bucketQuarter)
const query4 = ML.replaceClause(
  query3,
  -1,
  breakoutClause,
  createdAt_quarter
)

// Check order-by's display name
const orderByClause = ML.orderBys(query4)[0]
ML.displayInfo(query4, orderByClause)

// Expected: `displayName: "Created At: "Quarter"`
// Actual: `displayName: "Created At: "Month"`
