### ISSUE TITLE
Text in donut/pie chart overlapping viz/chart

### ISSUE THREAD

**Issue by dahyeik** [metabase/metabase#30996]
### Describe the bug

See screenshot for the text overlap

![Screenshot 2023-05-18 at 10 11 14 AM](https://github.com/metabase/metabase/assets/116025058/90f59dc3-ddd8-49d2-ab04-57b21e0fad9d)

### To Reproduce

1. Use the Accounts table in the sample database to create a new question
2. Filter on ID < 8
3. Group by email address and summarize count
4. Change to Pie chart 
5. Save and add to dashboard
6. Hover over email address to see the issue 

<img width="605" alt="Screenshot 2023-05-24 at 10 54 37 AM" src="https://github.com/metabase/metabase/assets/116025058/0f120177-0f66-4b39-811f-c5f1a251e2de">

### Expected behavior

Text should wrap or truncate

### Logs

N/A

### Information about your Metabase installation

```JSON
Metabase Version 1.46.3
```

### Severity

Cosmetic

### Additional context

Related issues:
- https://github.com/metabase/metabase/issues/25273
- https://github.com/metabase/metabase/issues/30259
- https://github.com/metabase/metabase/issues/6826
- https://github.com/metabase/metabase/issues/20628
- https://github.com/metabase/metabase/issues/4648
- https://github.com/metabase/metabase/issues/26916

**Comment by mmoole** [comment]
right now with version v0.47.9 it looks like this when the numbers are bigger than the 'inner circle' - I guess it's not supposed to look that way?
![image (2)](https://github.com/metabase/metabase/assets/678765/feec3817-e8a5-4907-9014-b0282040e42b)
Although it's not the nicest view, it would be more useful if text would be in front of the chart, I would suggest, if wrapping is not possible - for example for big numbers.
