### ISSUE TITLE
Overlay GeoJSONmaps on OpenStreetMaps

### ISSUE THREAD

**Issue by DMDatak** [metabase/metabase#30991]
**Is your feature request related to a problem? Please describe.**
I want to be able to define the administrative divisions on the maps OpenStreetMaps

**Describe the solution you'd like**
The best solution would be to connect Matabase to a WMS server

**Describe alternatives you've considered**
Another solution is to overlay the GeoJSONmaps 

Here an example from other BI application : 
<img width="1040" alt="image" src="https://github.com/metabase/metabase/assets/99891554/19ce62c8-d0d4-4a77-9e9b-421953e285ef">

**Comment by paoliniluis** [comment]
I think you're looking for https://github.com/metabase/metabase/issues/3991
