### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by kerwin** [metabase/metabase#3100]
If this is a bug report, please fill in the blanks:

*  I am using the _____chrome______ browser.
*  My computer's OS is ___mac________.
*  I'm running Metabase _____aws______ [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.] and it is using the _____postgres_____ [Postgres / MySQL / H2 (default)] database.
*  My data is in a ______postgres_____ database. [Postgres / MySQL / Redshift / BigQuery / MongoDB / SQLite / SQL Server / etc.]
*  My Metabase version is ____v0.19.0_______.

Any plan to support localization, like chinese.

**Comment by camsaul** [comment]
Hi @kerwin, we already have an open issue to consider this: #1451. Closing as duplicate.
