### ISSUE TITLE
[MLv2] Port Metrics and Segments v1 Editing GUI

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#31011]
If I understand correctly, the GUI for editing legacy Metrics and Segments uses different components than the normal notebook Query Builder, so it will need to be ported separately.

We are planning on deprecating and removing Metrics and Segments in the near future anyway, so we may decide that porting this stuff is not worth it, since it is effectively dead code. TBD. So we should not start on that project yet. But I will leave this issue open to track it until the decision is made one way or another.

**Comment by camsaul** [comment]
Product to discuss and decide what the timeline is for dropping legacy Metrics/Segments GUI

**Comment by luizarakaki** [comment]
As discussed: we won't touch this for now as we are deprecating Metrics and Segments v1
