### ISSUE TITLE
Reverting cards doesn't include `dashboard_tab_id`

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#31032]
### Describe the bug

When reverting to an earlier revision of a dashboard, the tab id of its cards is not included, causing it to appear on all tabs and saving to fail.

### To Reproduce

1. Create dashboard with multiple tabs
2. Add card then save
3. Remove that card then save
4. Revert to the revision where the card was added

https://github.com/metabase/metabase/assets/37751258/3023fa56-643f-43bf-9bd6-b60e575334ce

### Expected behavior

Any cards returning to the dashboard should have their original `dashboard_tab_id`s

### Logs

See API responses in screen recording

### Information about your Metabase installation

```JSON
Master 111c47ee89
```

### Severity

Moderately severe. Doesn't break dashboard completely but reversion doesn't work for tabbed dashboards.

**Comment by qnkhuat** [comment]
Should be fixed by https://github.com/metabase/metabase/pull/30898

**Comment by qnkhuat** [comment]
Implemented in https://github.com/metabase/metabase/pull/30898
