### ISSUE TITLE
Edit text on trend visualization

### ISSUE THREAD

**Issue by ryanr-trustengine** [metabase/metabase#31038]
We're currently producing a handful of trend visualizations, for 1 month ago vs prior month, but also for 2 months ago vs prior month, etc. Currently the text on our trend visualization reads "was X last month".  

The mention of "last month" can be confusing if you're comparing against a historical period of time.

Can we create the option to edit that text? or perhaps change to the more generic "was X in previous [time period]"?

**Comment by paoliniluis** [comment]
I think this is a duplicate of https://github.com/metabase/metabase/issues/8919
