### ISSUE TITLE
Reverting dashboard does not re-add text card properly

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#31031]
### Describe the bug

I removed a text card from a dashboard, and upon reverting to an older version that still had the card, the card was no longer viewable. Instead it had the `Sorry, you don't have permission to see this card.` error message.

### To Reproduce

1. Add a text card to a dashboard
2. Remove it
3. Revert to the revision where the card was added

https://github.com/metabase/metabase/assets/37751258/885a3b25-2426-477f-b2fc-ca3960a5b6d4

### Expected behavior

The card should be visible with the text it had

### Logs

Backend response from `GET /api/dashboard/{id}` is missing the `visualization_settings` on the text card, normally this is where the data for a text card is stored.

```JSON
{
  "description": null,
  "archived": false,
  "collection_position": null,
  "ordered_cards": [
    {
      "size_x": 4,
      "dashboard_tab_id": null,
      "series": [],
      "action_id": null,
      "collection_authority_level": null,
      "card": {
        "query_average_duration": null
      },
      "updated_at": "2023-05-25T13:59:18.555664Z",
      "col": 0,
      "id": 9147,
      "parameter_mappings": [],
      "card_id": null,
      "entity_id": "PfisA-v12yfhvwFnwMtRW",
      "visualization_settings": {},
      "size_y": 4,
      "dashboard_id": 1540,
      "created_at": "2023-05-25T13:59:18.555664Z",
      "row": 0
    }
  ],
  "param_values": null,
  "can_write": true,
  "enable_embedding": false,
  "collection_id": 662,
  "show_in_getting_started": false,
  "name": "A test dashboard",
  "caveats": null,
  "collection_authority_level": null,
  "creator_id": 157,
  "updated_at": "2023-05-25T13:59:18.555664Z",
  "made_public_by_id": null,
  "embedding_params": null,
  "cache_ttl": null,
  "ordered_tabs": [],
  "id": 1540,
  "position": null,
  "entity_id": "GVjFv1FZt30AKb-UVQwlc",
  "param_fields": null,
  "last-edit-info": {
    "id": 157,
    "email": "emmad@metabase.com",
    "first_name": "Emmad",
    "last_name": "Usmani",
    "timestamp": "2023-05-25T13:59:18.555664Z"
  },
  "parameters": [],
  "auto_apply_filters": true,
  "created_at": "2023-05-25T13:55:45.01724Z",
  "public_uuid": null,
  "points_of_interest": null
}
```

### Information about your Metabase installation

```JSON
On stats commit `111c47e`
```

### Severity

Moderatley severe. There is no way to recover a removed text card.

**Comment by EmmadUsmani** [comment]
I think this issue is coming from the backend not returning the `visualization_settings` on the card in the response to the revert request, but I'm not 100% sure. Since @qnkhuat and I are already working on refactoring revisions history and reversions, I will take a look and figure out if it's a backend or frontend fix (or both), then one of us can work on it.

**Comment by qnkhuat** [comment]
should be fixed by https://github.com/metabase/metabase/pull/31118
