### ISSUE TITLE
Pulse graph/answer showing the wrong dates

### ISSUE THREAD

**Issue by hivre** [metabase/metabase#3109]
Whenever I create a Pulse, the answers show the wrong date, a day behind the actual date of the answer.
See attached images. It reads Aug 1, 2016, and Jul. 31, 2016, however the data shown (both the spark line, and the numbers - 764,82, 760,68 etc.) is from Aug. 2, 2016 and Aug 1, 2016 respectively. 
(I expect to see Aug. 2, Aug.1 instead of the 1 aug / 31 july ones)

As a test I created one using the "last 7 days" filter, and one where I edited the SQL to show the last 7 days, starting from `now()` .
As you can see, both result in the dates being printed one day older than the actual range (for the record: today is Aug. 3. So the top should show Aug. 2, Aug 1, and the bottom graph should show Aug. 3, 2016 and Aug. 2, 2016)
I upgraded to 0.19 today, and re-selected my timezone (Europe/Brussels). 
If I perform a `SELECT now();` at the MySQL console, it gives me my current local time, 
`SELECT @@global.time_zone;` gives me SYSTEM,
`more /etc/timezone` in the terminal gives me `Europe/Amsterdam`

Attached are the admin-side of the pulse, and the resulting graphs in Slack.

![metabase_pulse_wrong_date-admin](https://cloud.githubusercontent.com/assets/9581049/17359227/f9eb2ac6-5965-11e6-9fed-17632ed24db7.png)
![metabase_pulse_wrong_date-slack](https://cloud.githubusercontent.com/assets/9581049/17359228/f9eb36d8-5965-11e6-8292-c5d096440ab7.png)
-  I am using the Chrome (latest) browser.
-  My computer's OS is Win10.
-  I'm running Metabase locally from the JAR on Ubuntu, and it is using the MySQL `Server version: 5.5.50-0ubuntu0.14.04.1 (Ubuntu)` database.
-  My data is in the same MySQL database. 
-  My Metabase version is 0.19. But also persists at 0.18.1

**Comment by asenyshyn** [comment]
I also have the same problem. Metabot answers do not take into account time zone configured in the admin panel.

**Comment by key88sf** [comment]
Can we at least mark this with a bug label ?

**Comment by jesusrtc** [comment]
+1

**Comment by hugocar** [comment]
+1

**Comment by javiercr** [comment]
I think this is related to #3841

**Comment by hivre** [comment]
I still have this problem, this is what I get:

```
$ java -jar metabase.jar version

02-14 13:05:55 INFO metabase.util :: Loading Metabase...
Metabase version: {:tag v0.22.0, :date 2017-01-10, :branch release-0.22.0, :hash fd04424}

OS: Linux 4.4.0-57-generic amd64

Java version: Java HotSpot(TM) 64-Bit Server VM 1.8.0_101

Country: US
System timezone: Europe/Amsterdam
Language: en
File encoding: UTF-8
```

Country is obviously wrong, not sure how I can change that? But that still shouldn't influence the timezone...

**Comment by senior** [comment]
I can confirm this behavior. When we format dates coming from the database, they get converted to the JVM's timezone. In my test, I had data from the pacific timezone (UTC offset of -07:00) and a JVM in UTC. This moved forward my dates by 7 hours, which was the next day.

If the database supports it, and a report timezone is set, we should be using that timezone.
