### ISSUE TITLE
[MLv2] Port bulk filter modal GUI

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#31091]
We need to port this UI

<img width="864" alt="image" src="https://github.com/metabase/metabase/assets/1455846/7e214b9c-84e1-42e6-95ae-2e7db4f9823f">

You see this when you click the `Filter` button when looking at query results

This should probably be done after the notebook mode filters stuff is all finished (see #30512)

**Comment by ranquild** [comment]
Duplicate of https://github.com/metabase/metabase/issues/34112
