### ISSUE TITLE
Moving dashboard to Our analytics collection creates a `null` revision description

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#31109]
### Describe the bug

When moving a dashboard to the "Our analytics" collection, the revision description is `You null`

### To Reproduce

1. Create a Collection "A"
2. Create and save a new dashboard in Collection "A"
3. Move the dashboard to "Our analytics" Collection
4. Open the revision history tab
5. See there is a `You null` revision

### Expected behavior

Should have a description that something like "You moved this to Our analytics"

### Information about your Metabase installation

```JSON
master
```

### Severity

minor

**Comment by nemanjaglumac** [comment]
Here's a Replay.io recording as a repro, which can also be used for debugging purposes:
https://app.replay.io/recording/31109-reproduction--48fd5227-032c-4ce9-ab58-71de10a1a7f4

**Comment by jasonLaster** [comment]
Took a look and found that the `CollectionPicker` is using a collection with a `null` id
https://www.loom.com/share/16400ec647fa462ba4bd3b647397d808

**Comment by qnkhuat** [comment]
fixed by https://github.com/metabase/metabase/pull/31118
