### ISSUE TITLE
No results given for a SQL query

### ISSUE THREAD

**Issue by dlebedev1** [metabase/metabase#3111]
I am running a rather complex SQL query that counts a sliding total of distinct values from my database. It normally takes around 20 seconds to process in BigQuery UI, but Metabase thinks for about a minute or so, then just shows a default text: "If you give me some data I can show you something cool. Run a Query!"

Here's a screencast for your convenience: http://monosnap.com/file/yrDWrqy145eNJRGAmi75UfBuH32Mwj

*  I am using the macOS client 0.19.0.
*  My computer's OS is OS X El Capitan 10.11.5 .
*  I'm running Metabase locally with Mac App and it is using the default database.
*  My data is in a BigQuery database.
*  My Metabase version is 0.19.0.

**Comment by camsaul** [comment]
@dlebedev1 do you see any error messages in the server logs?

**Comment by dlebedev1** [comment]
@camsaul I'm not sure where do I see the server logs for Metabase on Mac. Would you advise?

**Comment by dlebedev1** [comment]
@camsaul btw, adding another complex query to a dashboard, makes the dashboard crash on load: http://monosnap.com/file/or3VVIw5fVWQKNYm3rxHnSW8ZfyHpg

**Comment by salsakran** [comment]
@dlebedev1 open up `console` and you should see the logs.

**Comment by camsaul** [comment]
@dlebedev1 ?

**Comment by camsaul** [comment]
@dlebedev1 ?

**Comment by camsaul** [comment]
@dlebedev1 ?

**Comment by dlebedev1** [comment]
@camsaul hi! sorry for a delay. Seems like problem was solved. At least I can't reproduce it now, which is amazing! :) thanks for your hard work.

**Comment by salsakran** [comment]
glad to hear it's working!
