### ISSUE TITLE
Invalid native MongoDB query

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#31122]
### Describe the bug

This BE issue is related to FE issue #31121 - the extra quotes are added in FE.

Found as a part of code review discussion: https://github.com/metabase/metabase/pull/31111#discussion_r1209125938

![image](https://github.com/metabase/metabase/assets/6830683/5aa6aabf-ed23-4d22-8624-b2c905dac746)

### To Reproduce

1. Connect `QA Mongo4` (`mongo-4`) test database
2. Browse it
3. Browse `Orders` table
4. Click "Show editor" button
5. Click "View the native query" button
6. A modal opens. Inspect the generated query.

The generated query is not valid JSON i.e. it is not a valid Mongo query.
If you convert the question to a native query, the native query will fail to run.

### Expected behavior

Valid native Mongo query is generated

### Information about your Metabase installation

```
- Chrome Version 113.0.5672.126 (Official Build) (64-bit)
- Ubuntu 22.04
- Hash: edc969ce4247f810fe5fce806a19d77115ca80f1
```

### Severity

Looks like P1

**Comment by paoliniluis** [comment]
I don't see this, so it might be a regression in master
![image](https://github.com/metabase/metabase/assets/1711649/fa217456-d0cc-4a33-a2d1-581da329acc9)
