### ISSUE TITLE
Problem upgrading to v0.19.0: Duplicate column name 'points_of_interest'

### ISSUE THREAD

**Issue by haktansuren** [metabase/metabase#3113]
Having problem upgrading to the latest version. Here is the error messages I see in the terminal while metabase is being started.

`ERROR metabase.core :: Metabase Initialization FAILED:  Migration failed for change set migrations/038_getting_started_guide.yaml::38::camsaul`

`Duplicate column name 'points_of_interest' [Failed SQL: ALTER TABLE metabase.metabase_database ADD points_of_interest TEXT NULL`

*  I am using the Chrome browser.
*  My computer's OS is CentOS.
*  I'm running Metabase locally from the JAR and it is using the MySQL database.
*  My data is in a MySQL database. 
*  My Metabase version is v0.19.

**Comment by camsaul** [comment]
@haktansuren are you upgrading from 0.18/0.18.1?

**Comment by haktansuren** [comment]
@camsaul upgrading from v0.17.1. Thanks!

**Comment by camsaul** [comment]
@haktansuren I've been looking into this and am really not sure how your DB got in this state. It looks like the migration ran and completed but it's trying to run the migration a second time.

Can you look at your MySQL DB and tell me what rows you see in the `databasechangelog` table?

**Comment by haktansuren** [comment]
@camsaul Sorry I could not reply to you earlier. As soon as the problem happened, I had to revert the DB to the previous state. But I remember the last row was migrations/037. Currently I see the last one is /034 (see attached image). I am not sure if it is what you are asking though, let me know if I can help more. 

![image](https://cloud.githubusercontent.com/assets/17882120/17607953/2dc4ea48-5ff7-11e6-9dd9-8be39ffeedcb.png)

**Comment by haktansuren** [comment]
Do you think upgrading from v0.17.1 to v0.18 and then to the latest would help @camsaul ?

**Comment by camsaul** [comment]
@haktansuren you can try that, it might work. Alternatively it might make sense to just create a new MySQL database, run the migrations there, and copy over the rows from `databasechangelog`. Unfortunately your database is in a bit of a weird state where some of the migration changes have been made but it didn't record the migration itself as finished.

**Comment by camsaul** [comment]
@haktansuren After thinking about this a little longer I wrote a new command that should fix your database for you automatically. Once Metabase 0.20 ships in the next few weeks you'll be able to fix your database using the new `migrate force` command:

```bash
java -jar metabase.jar migrate force
```

**Comment by haktansuren** [comment]
@camsaul Great thanks! I will try and let you know
