### ISSUE TITLE
Sample dataset stops working if you move the JAR after initial launch

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3115]
This is happening on stats.

H2 requires an absolute path to a database file; since it's inside our JAR, we determine where the metabase JAR lives and construct this path the first time the sample dataset is added. Unfortunately, if the JAR is moved, the path to the sample dataset DB file is no longer correct and subsequent connections fail.

To make sure this problem doesn't happen anymore I think we should do the following:

*  Reset the path to the sample dataset *every time* Metabase launches, just in case the JAR has moved; this is easy to do now that we have the recently added `is_sample_dataset` column on `Database`
*  Log a giant red error message if Metabase starts up and cannot find the sample dataset DB file.

**Comment by salsakran** [comment]
I'm starting to feel that this is due to something weird about our dockerfile --
https://github.com/metabase/metabase/blob/master/bin/docker/Dockerfile#L15

There's no real mechanism for the metabase.jar file to move between restarts of the app server, and I think what's happening is that copy is failing somehow. digging in deeper in EBS

**Comment by camsaul** [comment]
If the copy failed wouldn't that mean Metabase wouldn't be able to run at all?

**Comment by salsakran** [comment]
yeeaaaahhh ... lemme back off the "copy" bit above. I'm still not seeing a way for the path to ever change and think it's something to do with the mounting of /app

**Comment by salsakran** [comment]
hmm. actually, I'm a moron. stats is using https://github.com/metabase/metabase/blob/master/Dockerfile

**Comment by salsakran** [comment]
I *still* am unclear as to why the path `./target/uberjar/metabase.jar` would ever change.

**Comment by camsaul** [comment]
Oh
Maybe when `./bin/build` is running inside the container it's not copying the sample dataset over to where we'd expect (?)

**Comment by camsaul** [comment]
Oh wait a minute. It's not running the jar from `/app`. $5 says that's our problem

**Comment by salsakran** [comment]
ok. sorted. turns out maybe having 3 separate docker files floating around wasn't too hot an idea?

**Comment by camsaul** [comment]
No longer high-priority but worth addressing at some point in the future. People could run into this issue if they rename their JAR or move the directory they launch it from
