### ISSUE TITLE
Update csv loading status when taking a long time

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#31214]
## Context
We have made performance improvements to csv uploads but there will still be some files that take multiple minutes to load. It can be confusing to the user since they just see a spinner and don't know if the file is still on track to upload or if something has gone wrong.

## Specified Behavior
Let's update the copy on the status component after 1 min (and each subsequent minute it's still uploading afterwards) to let the user know we're still working on the upload. Let's cycle through these copy bits:
1. Still working…
2. Getting our ducks in a row...
3. Arranging bits and bytes...
4. Doing the heavy lifting...
5. Pushing pixels...
6. [[Other fun ideas if you have them]]

Note that `Uploading data to [[Collection Name]]` is the current default and should still be shown for the first minute. Then we start cycling through the new copy above.

<img width="353" alt="Screenshot 2023-05-31 at 12 13 32" src="https://github.com/metabase/metabase/assets/16455495/d4b2916d-2d27-4452-a8fc-7c59660aaa93">

**Comment by iethree** [comment]
@cdeweyx how do you feel about 30 seconds rather than a minute? 1 min is a really long time in loading-spinner world.

**Comment by cdeweyx** [comment]
> @cdeweyx how do you feel about 30 seconds rather than a minute? 1 min is a really long time in loading-spinner world.

Yep, 30 is better.
