### ISSUE TITLE
BE - Instance Analytics search results ui/icons

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#31221]
this requires a backend change:

- need to hydrate `type` for collection search results if we want the special icon to show up. Once that is populated it *should* just work on the frontend.

**Comment by escherize** [comment]
I added collection_type to the **collection** search results. But re-reading what you've asked for on the PR, I think you want the collection hydrated on **all** search results.

**Comment by darksciencebase** [comment]
will it work with this, @iethree? https://github.com/metabase/metabase/pull/34451

**Comment by iethree** [comment]
LGTM!

![Screen Shot 2023-10-16 at 12 40 35 PM](https://github.com/metabase/metabase/assets/30528226/95717c81-7185-4d6a-a43d-43a8dc1d762e)
