### ISSUE TITLE
[MLv2] [Bug] Incorrect display name for cumulative count operator

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#31255]
Once applied, the "Cumulative count" operator is displayed like "Cumulative count of nil" in the notebook editor
This name is coming from `ML.displayInfo(query, index, aggregationClause).displayName`

Can be reproduced on aggregations integration branch (#31209)

### To Reproduce

1. New > Question > Any data source
2. Click "Pick the metric you want to see"
3. Pick the "Cumulative count of rows" option in "Basic operators"

**Expected:** the clause shows "Cumulative count"
**Actual:** the clause shows "Cumulative count of nil"

**Comment by camsaul** [comment]
👍 the field for cumulative count is optional, at least in MBQL, it looks like we're not handling that case.
