### ISSUE TITLE
[MLv2] [Bug] Can't use explicitly joined table columns after adding an aggregation

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#31256]
After adding an aggregation using a column from an explicitly joined table, these table's columns are no longer available for breakouts.

Can be reproduced on the aggregations integration branch (#31209), can be verified with [this e2e tet](https://github.com/metabase/metabase/blob/c0c9511d779ed9b4905be1f35bff184587b69efc/e2e/test/scenarios/joins/joins.cy.spec.js#L34)

### To Reproduce

1. New > Question > Raw Data > Sample Database > Products
2. Join the Reviews table on Products.ID = Reviews.Product_ID
3. Click "Pick the metrics you want to see"
4. Pick any aggregation operator that requires a column (e.g. Average)
5. Pick Reviews > Rating (or whatever column from the Reviews table)
6. Click "Pick a column to group by"

**Expected:** "Reviews" table columns are listed in the column picker (`breakoutable-columns`)
**Actual:** it's only possible to use columns from the source table or implicitly joinable tables

**Additional info**

It seems like something happens right after aggregation is added. E.g. join Orders and Products and try to add a breakout, you'd notice that the "Product" section has an explicit join icon. But once an aggregation is added (even Count), the icon changes to implicit join's one. Also, field references would use the `source-field` instead of a `join-alias`

### Demo

https://github.com/metabase/metabase/assets/17258145/b61520e9-8f09-402f-bbca-fa928488652c

**Comment by camsaul** [comment]
I'm not able to repro this on your branch 

<img width="959" alt="image" src="https://github.com/metabase/metabase/assets/1455846/8132e23b-dd24-4530-8093-6a1493a72836">

I don't really know why this didn't work tho, `breakoutableColumns` has been returning joined columns all along, in fact I fixed some bugs around this in #31233/#31237 yesterday (if you only picked certain fields from a Join it would only show those fields, which was the wrong behavior -- but this means it was still showing Fields from the join)

Is this possibly related to the weird stuff I saw yesterday in https://metaboat.slack.com/archives/C04DN5VRQM6/p1685559468422979? It seems like the MLv2 version of the query that's being passed to stuff like `orderableColumns()` or `breakoutableColumns()` is wrong, like it's not getting updated correctly when a join is added or modified or something.

**Comment by kulyk** [comment]
@camsaul are you sure you've tried the aggregations branch (#31209) and not the breakouts branch (#30693)? 
I can only reproduce this with MLv2 aggregations _and_ MLv2 breakouts

**Comment by camsaul** [comment]
Oh, I was trying it with `origin/mlv2-fe/break-out-support-notebook`. Oops

**Comment by camsaul** [comment]
I'll try to repro again and then I should be able to fix

**Comment by camsaul** [comment]
So it turns out this was already fixed upstream, I think by #31237, I've manually repro'ed the fix and wrote a failing test for it in the aggregations branch and confirmed it works on latest `master` I'll push a PR in a second to add that test

**Comment by camsaul** [comment]
Actually in  #31237 I wrote a test for this already
