### ISSUE TITLE
[MLv2] [Bug] Query fails when aggregating by an aggregated custom column

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#31266]
Query fails with `Column "..." not found` when trying to aggregate an aggregated custom column. My guess is the field reference in MLv2 is off at the moment.

For example, let's say we have a query:

* started from the sample Products table
* having a custom column called "Half Price" (definition: `[Price] / 2`)
* aggregation: average of Half Price
* breakout: by product's "Created At" (month) column

<details>
<summary>Query JSON representation</summary>

```json
{
  "source-table": 1,
  "expressions": {
    "Half Price": [ "field", 2, null ]
  },
  "aggregation": [
    [ "avg", [ "expression", "Half Price" ] ]
  ],
  "breakout": [
    [ "field", 7, { "base-type": "type/DateTime", "temporal-unit": "month" } ]
  ]
}
```

</details>

Now if we try to add another aggregation for "Average of Half Price", MLv2 generates an aggregation clause like:

```js
[ "max", [ "field", "avg_Half Price", { "base-type": "type/Float" } ] ]
```

OTOH, MLv1 produces the following reference:

```js
[ "max", [ "field", "avg", { "base-type": "type/Float" } ] ]
```

**Comment by camsaul** [comment]
This is somewhat related to #29907 ... for MLv2 we should just make sure we match the names calculated by MLv1/the QP 1:1 for now and maybe try to give things better names in the future
