### ISSUE TITLE
Now() function doesn't work

### ISSUE THREAD

**Issue by jjgungab** [metabase/metabase#31278]
### Describe the bug

I'm trying to create a custom column where I could use NOW() function when creating question but it seems it doesn't work at the moment. Also, I tried to create a CURRENT_TIMESTAMP which similar to now function but there's no option on it.

### To Reproduce

From the main menu:

1. Go to New and select Question
2. Pick any kind of database depending on your database available. For instance, I use sample database
3. Click on Accounts table
4. Make a custom column
5. Apply NOW() function to the custom column
7. See error
<img width="435" alt="Screen Shot 2023-06-02 at 11 21 34 AM" src="https://github.com/metabase/metabase/assets/128586284/415fe781-0df8-4705-a858-476ea7bf3304">

### Expected behavior

My expectation would be I want to return a column that returns the current timestamp

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.4.228-132.418.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.8 (Ubuntu 13.8-1.pgdg18.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

It blocking some users like me. Also, this function is somehow urgent to us that we need to track our data from time to time

**Comment by mayankagarwals** [comment]
Hey @jjgungab , could you try using the master build? Working on master build for me

<img width="916" alt="image" src="https://github.com/metabase/metabase/assets/39498938/bdf70d96-cba2-47dd-bb5b-c086a700580d">

**Comment by jjgungab** [comment]
Hi @mayankagarwals. I'm sorry I'm kinda new in metabase. By what exactly is master build you mean? Do you have steps on how do I get there?
<img width="403" alt="Screen Shot 2023-06-03 at 9 51 56 AM" src="https://github.com/metabase/metabase/assets/128586284/82cc5d3f-e582-43dd-bf94-c4a83b219648">

**Comment by paoliniluis** [comment]
Please upgrade to version 46.4 and try again
