### ISSUE TITLE
DashCardActionsPanel is clipping under other dash-cards

### ISSUE THREAD

**Issue by JesseSDevaney** [metabase/metabase#31274]
### Describe the bug

The `DashCardActionsPanel` for adding series to dash-cards, editing dash-card visualization settings, previewing/editing text cards, deleting cards, etc. clips under other dash-cards.
![image](https://github.com/metabase/metabase/assets/22608765/4eae9346-85df-4838-9af0-451d4a58b7b8)
[](url)

### To Reproduce

1. Go to any dashboard populated with dash cards
2. Edit the dashboard
3. Hover over any dash card that has a dash card above it
4. You should see the dash card actions panel clipping under the dash card above it
  a. If you do not, move the top dash card below the bottom dash card and hover over the bottom dash card

![dash-actions-panel-clipping](https://github.com/metabase/metabase/assets/22608765/90cf62f0-d237-4bc7-8a54-ba205a68f534)

### Expected behavior

The dash card actions panel should always be completely visible over other dash cards

### Information about your Metabase installation

```JSON
- Version: master
- Browser: Chrome
```

### Severity

P3: Non-blocking cosmetic bug

**Comment by WiNloSt** [comment]
After trying to implement this using Portal, it's starting to get more complicated than I thought.

1. We need to decide which element we want to render these dashcard actions in.
2. We need to deal with z-index with various banners, so when we're scrolling the dashcard actions don't stay above other sticky components and banners.
3. I tried to incorporate Mantine's `Portal` and `Popover` and it's also not so straightforward.

With these reasons above, I'd like to pause this issue and move on to something else first.

**Comment by uladzimirdev** [comment]
@WiNloSt do you see any problem such fix? do you have an idea about the possible tests for this issue?
