### ISSUE TITLE
[Safety Net] Prevent auto-apply filters in slow dashboards

### ISSUE THREAD

**Issue by NevRA** [metabase/metabase#31288]
Epic: https://github.com/metabase/metabase/issues/29267

Several areas seem under-tested:
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/31691
- [ ] https://github.com/metabase/metabase/pull/31720
- [ ] https://github.com/metabase/metabase/pull/31890
- [ ] https://github.com/metabase/metabase/pull/31898
```

An example of a bug - we don’t check for write permissions when we show the toast to disable auto apply of filters

**Comment by WiNloSt** [comment]
I'm closing this issue since all the PRs are merged and backport PRs from PR number 2 to 4 is also merged. The first PR doesn't have a corresponding backport PR like others since it was merged before we cut the 47 release branch.

cc @NevRA @ranquild
