### ISSUE TITLE
GET /api/database/:id/schemas is giving empty list

### ISSUE THREAD

**Issue by Rahmat711** [metabase/metabase#31280]
Hi Team, 

When i am trying to fetch schema from database using 
curl -X GET \
  -H "Content-Type: application/json" \
  -H "X-Metabase-Session: key" \
  https://localhost:3000/api/database/7/schemas
  
  I am getting a empty list []. it looks like some bug can you please look into it.

**Comment by likeshumidity** [comment]
Closing, we do not have enough information to troubleshoot.

If you could recreate the bug report using our template:
1. Click New issue
2. Click Get Started next to Bug Report
3. Fill out all of the fields/questions or put NA if not applicable

If you are a paid Metabase customer, you can also email help@metabase.com for more support.
