### ISSUE TITLE
Investigate flakiness of Dashboard PDF Test

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#31297]
### Describe the bug

Head to https://www.deploysentinel.com/ci/analysis, and click on Flakiness. It's most likely the top issue with a flake rate in the 90's

![image](https://github.com/metabase/metabase/assets/1328979/7bf0d4a0-7f64-423e-bfa5-c2deed9f4e69)

### To Reproduce

N/A

### Information about your Metabase installation

```JSON
Current Master
```

### Severity

Fairly low, as long as it doesn't start failing

**Comment by iethree** [comment]
see also discussion: https://metaboat.slack.com/archives/C5XHN8GLW/p1685716636001849

**Comment by npfitz** [comment]
Turns out, this is happening because the `verifyDownload` command is happening before the file is actually downloaded and saved. It always succeeds on the second try because it's finding the download from the first run. Going to see if I can make this a little more robust
