### ISSUE TITLE
Day of Month option missing from frontend

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3130]
It's been available in the backend since we implemented date bucketing but I assume we hid it in the frontend to avoid too many knobs. Anyways @hivre asked for it in #3110 so we should consider exposing it.

Might be useful for things like seeing whether toucan sales spike around the 1st and 15th when people get paid

**Comment by hivre** [comment]
To add another case:
day of the month allows for easier month-over-month analysis. 
You can plot multiple months, each their own series, and get a better understanding of trend development between different months.

**Comment by zachlatta** [comment]
Any updates on this? Need this for the above use case, would be nice to not have to use SQL.

**Comment by camsaul** [comment]
It looks like the only thing that we need to do here is uncomment out the option [here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/TimeGroupingPopover.jsx#L20).

@metabase/core-developers any objection to doing that? Seems like a few people want it.

**Comment by tbatchelli** [comment]
I have it uncommented in our setup, and it just works. There is one more change needed, but that's about it:

```diff
diff --git i/frontend/src/metabase/lib/formatting.js w/frontend/src/metabase/lib/formatting.js
index 3f0e5e6..c3744bf 100644
--- i/frontend/src/metabase/lib/formatting.js
+++ w/frontend/src/metabase/lib/formatting.js
@@ -74,6 +74,8 @@ function formatTimeWithUnit(value, unit, options = {}) {
             return moment().hour(value).format("h A");
         case "day-of-week": // Sunday
             return moment().day(value - 1).format("dddd");
+        case "day-of-month":
+           return moment().date(value).format("D");
         case "week-of-year": // 1st
             return moment().week(value).format("wo");
         case "month-of-year": // January
diff --git i/frontend/src/metabase/query_builder/TimeGroupingPopover.jsx w/frontend/src/metabase/query_builder/TimeGroupingPopover.jsx
index 3217d3c..b8bdc93 100644
--- i/frontend/src/metabase/query_builder/TimeGroupingPopover.jsx
+++ w/frontend/src/metabase/query_builder/TimeGroupingPopover.jsx
@@ -17,7 +17,7 @@ const BUCKETINGS = [
     // "minute-of-hour",
     "hour-of-day",
     "day-of-week",
-    // "day-of-month",
+    "day-of-month",
     // "day-of-year",
     "week-of-year",
     "month-of-year",
```

**Comment by camsaul** [comment]
@metabase/core-developers any thoughts on this?

**Comment by salsakran** [comment]
👍 on the overall problem, I'm ok with uncommenting this, and re-systematizing the granularity picker to allow other granularities in general. Eg, we've had folks ask for second (or smaller) granularities when plotting sensor data. 

Paging @kdoh

**Comment by kdoh** [comment]
I'm 👍 for getting this up and running with the picker as is in the short term and as we start to rethink how we handle time generally and more cohesively come up with a new and more expressive way to allow for other granularities.

So basically I'm in agreement with @salsakran  :P

**Comment by camsaul** [comment]
Cool, I'll move this into 0.21.0 so we can remember to uncomment those lines
