### ISSUE TITLE
Duplicating a model creates a new model that uses the original model

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#31309]
### Describe the bug

When duplicating a model (normal / not native), it will create a new model that uses the original model instead of duplicating the original model. 

### To Reproduce

1. Create a model with several joins -- optionally add filters, etc. 
2. Duplicate the model
3. Edit the definition of the duplicated model, it will show the original model as the data source and nothing else. 

### Expected behavior

The duplicated model should be a copy of the original model instead of using it as a source

### Logs

n/a

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-01",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "c45c9be"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

Can't duplicate automatically so I need to manually rebuild a copy.

**Comment by calherries** [comment]
This is FE, not BE. When duplicating a model, the POST `/api/card` request body has a `dataset_query` that only references the original card, e.g.  `{type: "query", database: 1, query: {source-table: "card__<card-id>"}}`
