### ISSUE TITLE
A slow database query executed every day at 12:00AM

### ISSUE THREAD

**Issue by xujijun** [metabase/metabase#31318]
### Describe the bug

Not sure why there is a very slow database query as follows executed every day at 12:00AM+08:00. Can I config to avoid executing it?

- SELECT * FROM `task_history` ORDER BY `ended_at` DESC LIMIT 1 OFFSET 100000

### To Reproduce

Found it by checking the Mysql database slow query log.

### Logs

[674b1c7a-a5f2-46bc-95b5-721d39edbc77] 2023-06-05T12:00:00+08:00 INFO metabase.task.send-pulses 正在发送预设的定时...
[674b1c7a-a5f2-46bc-95b5-721d39edbc77] 2023-06-05T12:08:00+08:00 INFO metabase.task.sync-databases 启动数据库2的同步任务。

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "17.0.4.1+1-LTS-2",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "17.0.4.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "17.0.4.1+1-LTS-2",
    "os.name": "Linux",
    "os.version": "3.10.0-957.21.3.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.18"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-05",
      "tag": "v0.46.1",
      "branch": "release-x.46.x",
      "hash": "12a6e1d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Low severe 

### Additional context

None

**Comment by paoliniluis** [comment]
Why is it slow? That’s the Metabase task scheduler

**Comment by xujijun** [comment]
> 

It takes 1.353 seconds, and scans 200.03K rows of data. And I'm not sure why it needs to "OFFSET 100000", do you know? Can I set it offset from 0 that might make it faster?

**Comment by paoliniluis** [comment]
@xujijun truncate the task_history table or leave the last row
