### ISSUE TITLE
CI Failure - MongoDB

### ISSUE THREAD

**Issue by mavimo** [metabase/metabase#3132]
## CI failure
https://circleci.com/gh/metabase/metabase/7633

## Cause
```
  Could not connect to downloads-distro.mongodb.org:80 (23.23.96.15), connection timed out
```

see also official [README.md](http://downloads-distro.mongodb.org/README-3.0)

## Fix
Replace repository URL to:
```
echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
```
and use the server key:
``
`
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
```
as reported in the [official doc](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu)

**Comment by camsaul** [comment]
@mavimo CircleCI tends to randomly fail *a lot*. So running the tests again would probably fix this specific issue. That being said, we have Circle set up to inject connection details for external databases we test against like SQL Server; it would be a security vulnerability to make those available to for PRs submitted by untrusted individuals, so unfortunately tests for you won't pass whether downloading the new version of Mongo works or not.
