### ISSUE TITLE
Have control over Pop ups

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#31336]
**Is your feature request related to a problem? Please describe.**
Mostly for embedded use cases, pop-ups might result recurrent and may be invasive. 
Example: "Thanks for using Metabase."

"Add question to dashboard?" after saving a question
<img width="451" alt="Screenshot 2023-06-25 at 2 53 34 PM" src="https://github.com/metabase/metabase/assets/132273646/6e80a434-f71a-4c5c-8382-6ff8ff7e50ed">

"It's okay to play around with saved questions", the first time you open a saved question.
<img width="596" alt="Screenshot 2023-06-25 at 2 54 14 PM" src="https://github.com/metabase/metabase/assets/132273646/4fc7dfec-2c91-4d16-bafc-2ebfdb8fde7f">

"Models", after creating the first Model
<img width="451" alt="Screenshot 2023-06-25 at 2 59 41 PM" src="https://github.com/metabase/metabase/assets/132273646/4d220f74-5245-4c04-98fb-b23446c65355">

**Describe the solution you'd like**
A toggle option in Settings that enables/disables pop/ups.

**Describe alternatives you've considered**
N/A

**How important is this feature to you?**
Would be useful for customers that want to hide it from their users, as they requested.

**Additional context**
N/A

**Comment by paoliniluis** [comment]
@ignaciobeinesfurcada please post screenshots

**Comment by brunobergher** [comment]
I'm sorry but this issue is way too broad for us to be able to handle it. Lots of core interactions in the product happen through pop-ups. And educational popups have a reason to exist (even if we can do a much better job at when to show them).

Closing this.
