### ISSUE TITLE
Full story: Add custom product analytics to Metabase 

### ISSUE THREAD

**Issue by ignaciobeinesfurcada** [metabase/metabase#31356]
**Is your feature request related to a problem? Please describe.**
There is a lack of information available to the admin about the usage of Metabase, particularly for embedding. It would be good to have information about the use of filters, clicks, and tags to understand how the user interacts with the app.

**Describe the solution you'd like**
Add google tag manager

**Describe alternatives you've considered**
Inserting a custom tracker, but that means a custom build and would not be as practical as having it integrated. 

**Additional context**
Related to https://github.com/metabase/metabase/issues/5462, https://github.com/metabase/metabase/issues/9494

**Comment by paoliniluis** [comment]
closing in favor of https://github.com/metabase/metabase/issues/5462
