### ISSUE TITLE
[MLv2] [Bug] Errors for queries based on questions/models

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#31366]
Seems to be related to #31365

If a query is based on a saved question or a model (like `source-table: "card__1"`), MLv2 throws an error when:

* you add some clause to it
* you start a new question _without_ loading a source question/model metadata first

```
No method in multimethod 'metabase.lib.metadata.calculation/visible-columns-method'
for dispatch value: :dispatch-type/nil
```

> **Warning**
> Can only be reproduced on the breakouts branch #30693

[Example of an e2e test](https://github.com/metabase/metabase/blob/324bcb83339c9dd7e08c28651313f6b3c76f9d99/e2e/test/scenarios/question/notebook.cy.spec.js#L433) failing because of this issue

### To Reproduce

1. New > Question > Raw Data > Sample Database > Orders > Save
2. Open the homepage and reload Metabase
3. New > Question > Saved Questions > Pick question from step 1

**Expected:** you can see and use the notebook editor
**Actual:** you see an error screen because of the error above

**Comment by metamben** [comment]
Fixed by commit [92c7718](https://github.com/metabase/metabase/pull/30693/commits/92c7718b47c5a80c44e98b45ccf0a363fdf56338).
