### ISSUE TITLE
[MLv2] Handle MLv1 field references for columns from questions/models in MLv2

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#31368]
If a query is based on a saved question or a model (like `source-table: "card__1"`), MLv2 would always use field literals to reference source card's columns:

```js
[ "field", "CATEGORY", { "base-type": "type/Text" } ]
```

On the other hand, MLv1 could use both field literals and concrete field references:

```js
[ "field", 13, null ]
```

As a result, if a query was made with MLv1, MLv2 can have issues figuring out where some columns are coming from.
We need to make this more robust to ensure MLv2 gracefully handles existing queries built with MLv1

> **Warning**
> Can only be reproduced on the breakouts branch #30693

[Example of an e2e test](https://github.com/metabase/metabase/blob/324bcb83339c9dd7e08c28651313f6b3c76f9d99/e2e/test/scenarios/question/nested.cy.spec.js#L272) failing because of this issue

### To Reproduce

Use the E2E test above

**Comment by camsaul** [comment]
Fixed by #31487
