### ISSUE TITLE
[MLv2] [Bug] `available-` bucket methods shouldn't return anything for custom columns

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#31367]
We discovered the FE was offering binning and temporal bucketing for custom columns without actual BE support (in MLv1)

#31037 fixed this for MLv2, but `available-temporal-buckets` and `available-binning-strategies` still return bucket objects for custom columns

**Comment by metamben** [comment]
Fixed by commit [9e75315](https://github.com/metabase/metabase/pull/30693/commits/9e753152b8bc5636d36b0a34b5d5ec76768a7ac0).

**Comment by kulyk** [comment]
Fixed 🎉
