### ISSUE TITLE
option to disable email login, either globally or per user

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#3136]
mostly applies to instances with existing users that then turn on google SSO. [originally mentioned here.](https://github.com/metabase/metabase/issues/1008#issuecomment-237915352)

thanks in advance! we're already loving google SSO.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by 23ranjan** [comment]
Any idea when this is going to be released ?

**Comment by drewB** [comment]
I am a big fan of this request.  It kind of defeats the purpose of using google for MFA if you can still sign in with a simple username and password.

**Comment by jwhitcraft** [comment]
This is huge for security, is there any update on this?

**Comment by flamber** [comment]
You can block requests to `/api/session`, since that's where regular logins are handled, whereas Google SSO is done via `/api/session/google_auth` - any negative side effects, I don't know.
On Nginx you would add the following before `location / { ... }`
```
location = /api/session { return 404; break; }
```

**Comment by jwhitcraft** [comment]
@flamber thanks for posting the workaround, in AWS land I just added a rule to the load balancer to 404 that path and it worked great.

**Comment by kikocastro** [comment]
Hi guys, 

Do you know how can @flamber 's solution can be achieved on a heroku running metabase instance?

**Comment by salsakran** [comment]
This is part of our enterprise Auth offering. Closing since this gets into "a million knobs" territory on the OSS side

**Comment by Zhann** [comment]
> You can block requests to `/api/session`, since that's where regular logins are handled, whereas Google SSO is done via `/api/session/google_auth` - any negative side effects, I don't know.

as for side effects, we tried this, and it gave us warnings that we didn't have sufficient permissions, viewing the main page.

**Comment by jonathanrhodes** [comment]
> You can block requests to `/api/session`, since that's where regular logins are handled, whereas Google SSO is done via `/api/session/google_auth` - any negative side effects, I don't know.

Tried this today and it did effectively block password login...but if you block the whole path then it also seems to block logout, which appears to be implemented as `DELETE /api/session`.

**Comment by tamvm** [comment]
For ones who don't use with nginx, we can create firewall rule on Cloudflare and block exact url `/api/session`

**Comment by YouveGotMeowxy** [comment]
> You can block requests to `/api/session`, since that's where regular logins are handled, whereas Google SSO is done via `/api/session/google_auth` - any negative side effects, I don't know. On Nginx you would add the following before `location / { ... }` - I have not tested this, so you might need to adjust/test yourself:
> 
> ```
> location = /api/session {
>   limit_except DELETE {
>     return 404;
>     break;
>   }
> }
> ```

I get this error when trying that block:

> nginx: [emerg] "return" directive is not allowed here in /config/nginx/proxy-confs/dashboard.subdomain.conf:20

I'm trying to use Authelia for my credential handling and would like to disable the native login handling; has anyone figured out how to do this yet?

**Comment by meyerovb** [comment]
Why is this closed?  The workaround isn't a stable or acceptable solution.

**Comment by paoliniluis** [comment]
@meyerovb this is a feature in the product (global feature)

**Comment by fedeisas** [comment]
> > You can block requests to `/api/session`, since that's where regular logins are handled, whereas Google SSO is done via `/api/session/google_auth` - any negative side effects, I don't know. On Nginx you would add the following before `location / { ... }` - I have not tested this, so you might need to adjust/test yourself:
> > ```
> > location = /api/session {
> >   limit_except DELETE {
> >     return 404;
> >     break;
> >   }
> > }
> > ```
> 
> I get this error when trying that block:
> 
> > nginx: [emerg] "return" directive is not allowed here in /config/nginx/proxy-confs/dashboard.subdomain.conf:20
> 
> I'm trying to use Authelia for my credential handling and would like to disable the native login handling; has anyone figured out how to do this yet?

I'm using:

```
  location = /api/session {
    if ($request_method != 'DELETE') {
      add_header Content-Type application/json always;
      return 401 '{"errors":{"password":"Password authentication is disabled."}}';
    }
    
    proxy_pass ....
 }
```

**Comment by meyerovb** [comment]
> > I'm trying to use Authelia for my credential handling and would like to disable the native login handling; has anyone figured out how to do this yet?

thx for the recommendation on url blocking. To use a non google oauth provider on free metabase set up google cloud identity with passthrough oauth to your provider. I made it work with azure accounts just fine. U probably need a domain and a single paid google account but that’s it. U get 50 free cloud identities but can just ask for more. They upped me to 1k, but we also pay a lot for google translate so there’s that…
