### ISSUE TITLE
[MLv2] [Bug] Error when adding breakouts to queries based on questions/models

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#31365]
Seems to be related to #31366

If a query is based on a saved question or a model (like `source-table: "card__1"`), MLv2 throws an error when adding some clauses:

```
Error calculating display info for field: unknown type of :field ref in lib.stage/ref-to?
```

> **Warning**
> Can only be reproduced on the breakouts branch #30693

[Example of an e2e test](https://github.com/metabase/metabase/blob/324bcb83339c9dd7e08c28651313f6b3c76f9d99/e2e/test/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js#L259) failing because of this issue

### To Reproduce

1. New > Question > Raw Data > Sample Database > Orders > Save
2. New > Question > Saved Questions > Pick question from step 1
3. Try to add a breakout

**Expected:** you can add a breakout, run the query, etc.
**Actual:** you see an error screen because of the error above

**Comment by metamben** [comment]
Fixed by commit [251b965](https://github.com/metabase/metabase/pull/30693/commits/251b9657eccf2e29795a89881b3da09534142673).
