### ISSUE TITLE
If initial data for a question doesn't contain numeric fields number summaries (sum, avg, etc.) don't become available after data is joined

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#31384]
### Describe the bug

If the initial data/table selection for starting a question doesn't have any number fields then numeric aggregates are not available in the "Summarize" section, even if there are numbers in subsequently joined tables.

### To Reproduce

1. Go to Admin > Data Model ("Table Metadata" in newer versions) > Sample Dataset > People
2. Set visibility of all numeric fields (latitude, longitude) to "Do not include", can leave the ID and Zip as the semantic type seems to exclude numeric summaries already.
4. Start a new question from Sample Dataset > People
5. Click green "Summarize" button. Note that no sum, avg etc. are available, this is valid as there is nothing to act on
6. Join "Orders" table on the ID -> User ID
7. "Summarize" options for numeric values are still not available even though Orders table has things I want to sum.

![image](https://github.com/metabase/metabase/assets/4504437/9a078689-ca95-4dcf-b02f-b61356575aa2)

### Expected behavior

When I join a table with numeric values I should be able to summarize them.

### Logs

No relevant logs.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-05-24",
      "tag": "v0.46.4",
      "branch": "release-x.46.x",
      "hash": "f858476"
    },
    "settings": {
      "report-timezone": "NZ"
    }
  }
}
```

### Severity

Significant. Need to make sure the starting table has numbers if you ever want to summarise values. This is manageable for me but most of our users will be confused by this.

### Additional context

A custom expression can be created in the notebook editor for numeric summary(e.g. `=Sum([Orders → Total])`) but this is discarded when the "Visualize" button is clicked.

Can work around these issues by creating a custom column that produces a number (e.g. `=coalesce(1,1)`). Can then summarise numbers from any of the tables, but this doesn't feel very scalable or correct.

**Comment by kamilmielnik** [comment]
Reproducible in 0.46.4.
[Fixed in `master`](https://github.com/metabase/metabase/assets/6830683/8eafa3f5-3876-49b3-a2bd-8680b57d8a29) ([d35c779](https://github.com/metabase/metabase/commit/d35c779976ae6bd79369e9cc6bec8540908f37d2)).
Marking as fixed in the next version (48).
Closing.

**Comment by snoe** [comment]
Reopen to add test
