### ISSUE TITLE
Failed to connect to MySQL to Metabase and here's the issue

### ISSUE THREAD

**Issue by mansohal** [metabase/metabase#31395]
Hello there, 

I have this problem while connecting MySQL to Metabase. 

Could not connect to address=(host=zto.res.el.eee.intern)(port=3306)(type=master) : (conn=335) Access denied for user 'admin'@'10.155.226.14' (using password: YES) Current charset is windows-1252. If password has been set using other charset, consider using option 'passwordCharacterEncoding'

Any help or suggestion would be appreciated. 

Thanks

**Comment by paoliniluis** [comment]
you need to allow that user to the DB
