### ISSUE TITLE
Separate CSV error messages and details

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#31397]
Related to https://github.com/metabase/metabase/issues/31215

[Designs](https://www.figma.com/file/OPqbn5aPZiKDPueODxqMvo/CSV-Upload?type=design&node-id=6%3A6625&t=LJaQsf6XWXaQjdtT-1)

 ![Screen Shot 2023-06-07 at 8 49 20 AM](https://github.com/metabase/metabase/assets/30528226/cc4966bb-4bff-4740-83b5-208691228c94) ![Screen Shot 2023-06-07 at 8 49 29 AM](https://github.com/metabase/metabase/assets/30528226/08eb058e-f0cf-4989-8326-9ac99b0b1cd1)

![Screen Shot 2023-06-07 at 9 38 45 AM](https://github.com/metabase/metabase/assets/30528226/92553ccb-de37-4f91-9706-2a305ea1c38a)

[Discussion](https://metaboat.slack.com/archives/C04S696LRUM/p1686089604811819)

- [x] Frontend: Allow more info / stack trace modal
- https://github.com/metabase/metabase/pull/31430

**Comment by tsmacdonald** [comment]
@iethree everything to do with this is merged, right? Are we okay to close the issue?
