### ISSUE TITLE
Remove Google Analytics Driver from the codebase

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#31410]
Follow-up of https://github.com/metabase/metabase/issues/28036

GA3 is approaching EOL and we decided to remove it. It was deprecated on 46 and we should remove it from the codebase on 47.

**Comment by john-metabase** [comment]
What do we do with frontend logic based on this specific driver? Removing the driver upstream will still leave the plugin in place for someone who tries to upgrade, but the frontend code depends on e.g. `if (table.db.engine === "googleanalytics"` in a few places.

So, a GA database could continue to work for a while in v47 with no guarantees, if the plugin stays, and if we don't touch the frontend code. But how long do we want to leave frontend code in that case?

**Comment by luizarakaki** [comment]
What kind of FE code depends on driver engine? I think we should remove everything. This driver won't work anyway from July 1st (GA3 EOL).

**Comment by darksciencebase** [comment]
We're gonna keep it for 47 but eventually it needs to go. [More context on slack](https://metaboat.slack.com/archives/C010ZSXQY87/p1688395673936829?thread_ts=1687973862.806419&cid=C010ZSXQY87)

**Comment by camsaul** [comment]
Resolved by #43352
