### ISSUE TITLE
Bad Message 431 reason: Request Header Fields Too Large

### ISSUE THREAD

**Issue by thl3538** [metabase/metabase#31424]
![image](https://github.com/metabase/metabase/assets/59004749/7726d994-4608-461f-bae6-db90ddc2e750)
Hello, suppose there is a scenario where there is a lot of data in the drop-down filter box, and then all of them are checked to filter, causing the parameters of the report query Get request to exceed the maximum length limit of the browser. How to solve this problem? Can the Get request be converted into What about Post requests? Or there are other ways to solve it

**Comment by Tony-metabase** [comment]
Did you try to increase MB_JETTY_REQUEST_HEADER_SIZE ... The default is 8192. For reference: 

https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_jetty_request_header_size

**Comment by thl3538** [comment]
> Did you try to increase MB_JETTY_REQUEST_HEADER_SIZE ... The default is 8192. For reference:
> 
> https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_jetty_request_header_size

Thank you for your reply, but I have a question, isn't this a limitation of the browser, can adding this environment variable solve this problem?

**Comment by Tony-metabase** [comment]
One way to find out :P check how long is your header and set a value larger than that

**Comment by Tony-metabase** [comment]
Are you thinking of doing a custom build to do those changes?

the maximum length should be predictable since you know the distinct options you have per column

**Comment by thl3538** [comment]
> Are you thinking of doing a custom build to do those changes?
> 
> the maximum length should be predictable since you know the distinct options you have per column

At present, we have customized the metabase drop-down filter box. The data source of the drop-down filter box is obtained from the api. There may be thousands of pieces of data, so this problem occurs when selecting all. Is there any recommended way to make us normal? run this filter?

**Comment by thl3538** [comment]
![image](https://github.com/metabase/metabase/assets/59004749/68b20fd7-7378-49cd-b0e2-63564d1ec8c5)
like this

**Comment by Tony-metabase** [comment]
None that comes to mind, except to increase MB_JETTY_REQUEST_HEADER_SIZE or make the filter a search filter rather than dropdown so you can search with contains and so on which should make the URL smaller

**Comment by thl3538** [comment]
> Did you try to increase MB_JETTY_REQUEST_HEADER_SIZE ... The default is 8192. For reference:
> 
> https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_jetty_request_header_size



> None that comes to mind, except to increase MB_JETTY_REQUEST_HEADER_SIZE or make the filter a search filter rather than dropdown so you can search with contains and so on which should make the URL smaller
Ok thanks, so is it actually still not recommended to change the filtered GET request method to a POST request method? I think it would be a particularly heavy workload

**Comment by thl3538** [comment]
> None that comes to mind, except to increase MB_JETTY_REQUEST_HEADER_SIZE or make the filter a search filter rather than dropdown so you can search with contains and so on which should make the URL smaller

Ok thanks, so is it actually still not recommended to change the filtered GET request method to a POST request method? I think it would be a particularly heavy workload
