### ISSUE TITLE
Add to Dashboard/Save Question Menu doesn't respect Collection Alphabetical order as in Main Menu

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#31425]
### Describe the bug

In the Main Menu Collections are sorted Alphabetically but when you go to Add a Question form a Dashboard those seem to be ordered based on creation Date

### To Reproduce

1. Go to New Collection -> Name it `a` -> Save
2. Go to New Collection -> Name it `c` -> Save
3. Go to New Collection -> Name it `b` -> Save

<img width="1495" alt="image" src="https://github.com/metabase/metabase/assets/110378427/aa2fe503-c714-4f4e-8995-8873b4d2d4c5">

4. New -> Dashboard -> Add Question -> Notice how order is not alphabetically anymore:

<img width="1511" alt="image" src="https://github.com/metabase/metabase/assets/110378427/454e0c46-1693-4891-b68e-028eeca1b9af">

5. This also happens when you create a new question and save it:

<img width="1502" alt="image" src="https://github.com/metabase/metabase/assets/110378427/e8c2b9c3-109b-4e59-8ba8-74d498d6b2f5">

### Expected behavior

Same ordering, ideally alphabetically

### Logs

None

### Information about your Metabase installation

```JSON
1.46.4 and master
```

### Severity

minor

**Comment by brunobergher** [comment]
Dupe/complementary to #31294?

**Comment by Tony-metabase** [comment]
Yes it's the same, except that this one also mentions other menus which are impacted not just the move so i am not sure if this fixes all paths:

https://github.com/metabase/metabase/pull/31355

@kamilmielnik can you also consider the above paths for Collection Alphabetical order. Not sure if you already did just want to point this one out
