### ISSUE TITLE
Missing chart title after loading data

### ISSUE THREAD

**Issue by mirceapasoi** [metabase/metabase#3146]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac OS X 10.11.16.
*  I'm running Metabase 0.19.1 on AWS and it is using the Postgres database.
*  My data is in a Redshift database. 
*  My Metabase version is 0.19.1

After upgrading to 0.19.1 some chart titles disappear after loading the data (attached [images)]
![loading chart, title is correct](https://cloud.githubusercontent.com/assets/29048/17464804/3e78f702-5c9c-11e6-9029-6ee86b08055f.png)
![same chart after loading - title changed, can't click on it anymore](https://cloud.githubusercontent.com/assets/29048/17464803/3d4e3b12-5c9c-11e6-8551-ef4868d86648.png)

**Comment by mirceapasoi** [comment]
Here's the query in case in helps:

```sql
with teams as (
    select team_id, count(*) as num_users
    from bots.user
    where deleted is not true and is_bot is not true
    group by team_id
)
select num_users, count(*) as teams from teams 
group by num_users
order by num_users
```

**Comment by jschell12** [comment]
Yup. I just upgraded to v019.1 as well and noticed this, too. I was on v0.171. but might revert to v0.18.1 until this is fixed.

While Loading...
![screenshot 2016-08-08 14 41 11](https://cloud.githubusercontent.com/assets/1191881/17491586/3dff032c-5d76-11e6-8157-52c9944d61c2.png)

Once Loaded
![screenshot 2016-08-08 14 41 25](https://cloud.githubusercontent.com/assets/1191881/17491591/401ada82-5d76-11e6-8825-c725a42fa213.png)

**Comment by mazameli** [comment]
Note that this bug also prevents the user from being able to click the title to go to the question detail for that card. I'm seeing this on our stats instance as well.

**Comment by jschell12** [comment]
Yup. I just upgraded to v019.1 as well and noticed this, too. I was on v0.17.1 but might revert to v0.18.1 until this is fixed.

FYI
I'm running 
Chrome Version 52.0.2743.116 (64-bit)
Mac OS X 10.11.6

**_While Loading..._**
![screenshot 2016-08-08 14 47 42](https://cloud.githubusercontent.com/assets/1191881/17491786/15b00dfc-5d77-11e6-9734-bb3252a4566d.png)

**_Once Loaded_**
![screenshot 2016-08-08 14 41 11](https://cloud.githubusercontent.com/assets/1191881/17491802/2620dd4c-5d77-11e6-9dd4-b47effae4fdb.png)
