### ISSUE TITLE
Allow users to upload custom style sheet as part of whitelabeling

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#31461]
**Is your feature request related to a problem? Please describe.**
- Some Metabase customers want to adjust styles, fonts, colors, etc. beyond what our Settings allow
- Sometimes they find these so valuable that they will have their own developers and engineers setup a reverse proxy to edit styles by intercepting requests or fork the code and roll their own version.
  - In may cases though, the above options are a bit out of reach, so a simpler way requiring a much smaller bit of know-how (i.e. CSS) would allow users to customize the interface significantly

**Describe the solution you'd like**
- Allow a style sheet to be uploaded through the GUI 

**Describe alternatives you've considered**
- using a reverse proxy to intercept requests and replace styles
- fork the repo and roll own version

**How important is this feature to you?**
- Would address multiple customer requests for style changes relative to mostly branding but sometimes layout

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/11169? or duplicate?

**Comment by likeshumidity** [comment]
Thanks @paoliniluis close enough I think, Closing in favor of https://github.com/metabase/metabase/issues/11169
