### ISSUE TITLE
Incorrect message catalog for plural forms in the backend code

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#31480]
### Describe the bug

`locales/metabase-backend.pot` contains incorrect `msgid_plural`.

### To Reproduce

1) Run `./bin/i18n/update-translation-template`, which generates the message catalogs for both the frontend and backend. We're interested in the latter.
2) Do `grep plural locales/metabase-backend.pot`

Actual result:

```
msgid_plural "added a tab"
msgid_plural "removed a card"
msgid_plural "removed a tab"
msgid_plural "added a card"
```

This doesn't look right. For instance, in `src/metabase/models/dashboard.clj` we have:

```
(deferred-trun "added a tab" "added {0} tabs" num-tabs-diff)
```

Opening `locales/metabase-backend.pot` with an editor reveals something like (note that the plural form isn't different at all):

```
#: metabase/models/dashboard.clj:293
msgid "added a tab"
msgid_plural "added a tab"
msgstr[0] ""
```

### Expected behavior

Expected result:

```
msgid_plural "added {0} tabs"
msgid_plural "removed {0} cards"
msgid_plural "removed {0} tabs"
msgid_plural "added {0} cards"
```

### Information about your Metabase installation

latest master, after revision 9e21ae22bf5

### Severity

affecting the correct translation for 47

### Additional context

I'm not sure where the issue is, potentially it's in `bin/build/src/i18n/enumerate.clj`.

**Comment by paoliniluis** [comment]
might be related to https://github.com/metabase/metabase/issues/28559
