### ISSUE TITLE
file type icons dissapeared

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#31490]
### Describe the bug

Maybe this is the new look, but I just wanted to double check
![image](https://github.com/metabase/metabase/assets/1711649/5a10ffb3-7e78-4a28-9822-d4a4354bdf7e)

### To Reproduce

Build a question
download it
you'll only get the extensions

### Expected behavior

should there be icons for the file types?

### Information about your Metabase installation

```JSON
master
```

### Severity

P3

**Comment by darksciencebase** [comment]
yes, it is the new look: https://github.com/metabase/metabase/pull/30913
