### ISSUE TITLE
Embed Dashboard Background Color / Theme Bug

### ISSUE THREAD

**Issue by paperguns** [metabase/metabase#31493]
### Describe the bug

An embed dashboard has a parameter for the theme or background color. The background is not getting colored or styled correctly in the iframe.

If 'night' is chosen and border is set to false, there is a white border line still showing around the left, top, and right edges of the iframe that is the length of the height of the iframe. If one then scrolls through a large dashboard the border ends at the iframe height and is not visible on the rest of the dashboard. This is definitely a problem as the UI looks terrible and unclean.

![metabase_ui_bug_theme_night](https://github.com/metabase/metabase/assets/29148524/9768f1fd-a888-405b-98ba-9e503ed4ddda)

If 'white' is chosen and the border is set to false, there is a white background still showing but is only filled in up to the height of the iframe. If one then scrolls through a large dashboard the white background ends and the rest of the dashboard has no color. This looks much worse than the use case above.

![metabase_ui_bug_theme_white](https://github.com/metabase/metabase/assets/29148524/572cd9e2-f709-40c5-9107-f034c09365d0)

Setting the value to 'transparent' is one way to avoid these issues but does not facilitate user desired theming and the colors of the text and visualizations may not work with the page color behind the embed.

![metabase_ui_bug_theme_transparent](https://github.com/metabase/metabase/assets/29148524/704fa6f0-bb9f-4d96-bf59-f83b4c553a96)

This is a major issue for my team as we approach release of the embed dashboard feature for our application. Please advise.

### To Reproduce

1. Create a large dashboard with lots of cards and visualizations
2. Enable embedding
4. Embed content into an iframe with a height no larger than 1000px
5. Set embed parameters to 'border=false' and 'theme=night | white | transparent'
6. View embed content and scroll down
7. Night - should see a border than shouldn't be there, White - background is not set for all content, Transparent - font color is problematic depending on page background color.

### Expected behavior

Night theme should not have any bordering when border is set to false. White theme should have a white background for the entirety of the content when scrolling. Transparent should be supported by text color choice.

### Information about your Metabase installation

```JSON
- Browser -> Chrome: Version 114.0.5735.110 (Official Build) (64-bit)
- OS -> Windows 11 Home 10.0.22621 Build 22621
- DB -> not relevant (can provide if needed)
- Metabase Version -> v1.46.3
- Metabase Hosting Environment -> VM self hosted
- Metabase Internal DB -> not relevant
```

### Severity

High Impact on Release

### Additional context

The content of the dashboard is proprietary and confidential.

**Comment by albertoperdomo** [comment]
Hello @paperguns ,

in version 51, we've refined the theming for static embeds. This is the summary of the changes:

* choose between light and dark themes, we've dropped the transparent theme
* you can set the the background to be transparent, in combination with both the light and dark themes

I think should address some of the issues you are seeing. If you are curious to try this out, this is live in the 51 beta before we cut an official gold release: 

Docker image: https://hub.docker.com/r/metabase/metabase-enterprise/tags?name=beta
Download the JAR here: https://downloads.metabase.com/enterprise/beta/metabase.jar
