### ISSUE TITLE
Spinner appears on the top left on the sidebar

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#31503]
### Describe the bug

We make the spinner appear on a weird place when loading the sidebar, should be vertically and horizontally aligned
![image](https://github.com/metabase/metabase/assets/1711649/761faae0-9f91-4510-9fd6-0467e71fe96c)

### To Reproduce

1) open the browser dev tools, go to network and switch the connection to fast 4g
2) enter the internal metabase instance
3) refresh, see the spinner in the wrong place

### Expected behavior

vertically and horizontally aligned?

### Information about your Metabase installation

```JSON
version: master
```

### Severity

P3

**Comment by nemanjaglumac** [comment]
Maybe caused recently by https://github.com/metabase/metabase/pull/31306? cc @kdoh
