### ISSUE TITLE
Unknown column in 'field list'

### ISSUE THREAD

**Issue by joshembling** [metabase/metabase#31507]
### Describe the bug

I've updated my database by removing a column that is no longer needed.

I have gone to Admin Settings > Databases > My database > Sync database schema now && Re-scan field values now

I have also gone to Data Model > Table > Settings > Re-scan this table && Discard cached field values

Those four options don't seem to have done anything for me.

When I view the table in an embed, or in Metabase, I am still getting the following error message: 
`Unknown column 'bookings.promo_code' in 'field list'`

Is there a way I can refresh the field list elsewhere? I am on the latest version 0.46.4

### To Reproduce

1. Remove a field from your database.

2. Admin Settings > Databases > My database > Sync database schema now && Re-scan field values now

3. Data Model > Table > Settings > Re-scan this table && Discard cached field values

### Expected behavior

Should sync database, so old values are not present.

### Information about your Metabase installation

```JSON
MySQL database, with docker image
```

### Severity

Blocking

**Comment by Tony-metabase** [comment]
Can you confirm that you are not explicitly using this column inside a question? Also share the Information about your metabase installation, you can simply go to Admin -> Troubleshooting -> Diagnostic Info

**Comment by joshembling** [comment]
> Can you confirm that you are not explicitly using this column inside a question? Also share the Information about your metabase installation, you can simply go to Admin -> Troubleshooting -> Diagnostic Info

Just realised the column has not been deleted, but renamed. But is still trying to find the older name of this field and not the new. 

I remember on an older version of Metabase, I was able to go somewhere and click save on field types and it would do a sort of auto reload to update the fields. I can't find that in this version. Should mention that this field name was changed months ago, but was able to solve it before using what I just described.

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.15.0-1020-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.12"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-05-24",
      "tag": "v0.46.4",
      "branch": "release-x.46.x",
      "hash": "f858476"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by Tony-metabase** [comment]
my question is if you are explicitly using the column in a question ... For example you have column123 and then you renamed the column to column456 but the question would still reference column123 since metabase doesn't know to which column this new column changed to

**Comment by joshembling** [comment]
> my question is if you are explicitly using the column in a question ... For example you have column123 and then you renamed the column to column456 but the question would still reference column123 since metabase doesn't know to which column this new column changed to

It is being used. How can I map the old field to the renamed field so Metabase knows of the change?
