### ISSUE TITLE
[Epic] Preserve action call form values after edit an action from where I'm using it

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#31510]
This is a separate milestone from https://github.com/metabase/metabase/issues/29866

**Links**

- [Product doc](https://www.notion.so/metabase/Make-it-easier-to-fix-edit-an-action-from-where-I-m-using-it-26050f5fd6904bec90a55505aa37a13e?pvs=4#8687fce9e9c846f48373326c8bfb37f7)
- feature branch: `29866-preserve-values`

**Implementation Plan**

```[tasklist]
### Milestone 1
- [ ] https://github.com/metabase/metabase/pull/31417
```

**Comment by ranquild** [comment]
After discussions we decided that the implementation costs are too high for the product outcome.
