### ISSUE TITLE
 Assert failed: No more than 1024 pending puts are allowed on a single channel

### ISSUE THREAD

**Issue by yasithab-pf** [metabase/metabase#31513]
### Describe the bug

Hello Team,

When I try to browse a collection (https://metabase.example.com/dashboard/20-mysql), it says,

`Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer. (< (.size puts) impl/MAX-QUEUE-SIZE)`

This is the same issue posted [here](https://discourse.metabase.com/t/assert-failed-no-more-than-1024-pending-puts-are-allowed-on-a-single-channel/9980), but I'm running the latest metabase version which is v0.46.4

Could you please look into this? Thanks in advance :)

### To Reproduce

Browse a collection. For example https://metabase.example.com/dashboard/20-mysql
<img width="1450" alt="metabase" src="https://github.com/metabase/metabase/assets/111726818/b5a38a55-4730-4e3a-b6b2-8f8c3095c25b">

### Expected behavior

It shod show data

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.10.179-168.710.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo",
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.12"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-05-24",
      "tag": "v0.46.4",
      "branch": "release-x.46.x",
      "hash": "f858476"
    },
    "settings": {
      "report-timezone": "Asia/Muscat"
    }
  }
}
```

### Severity

Developers are unable to use metabase now

**Comment by paoliniluis** [comment]
first time I see this error in my life, can you send us if you have any environment variable configured? also when this started happening and on top of that how many questions the dashboard has and which types?

**Comment by yasithab-pf** [comment]
Hello @paoliniluis Thank you for the quick reply, I really appreciate it :)

The issue arose following the upgrade to metabase v0.46.4 and is not limited to a specific dashboard. It exhibits the same behavior across most dashboards containing 2 to 30 questions. Here are the environment variables configured for metabase in our AWS ECS setup that utilizes RDS.

```
JAVA_OPTS: -Xmx5g
MB_DB_DBNAME: example
MB_DB_HOST: <RDS_DB_HOST>
MB_DB_PASS: example
MB_DB_PORT: 3306
MB_DB_TYPE: mysql
MB_DB_USER: example
MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE: false
```

Thanks in advance :)

**Comment by paoliniluis** [comment]
Thanks, is there any configuration I need to take into account? E.g load balancer config, or MySQL version

**Comment by yasithab-pf** [comment]
Hello @paoliniluis Thanks again for the quick reply :)

We are using a AWS ALB with default settings. MySQL version is 5.7.mysql_aurora.2.08.3 runs in a Aurora Serverless cluster.

And I have the following caching configurations in metabase.

<img width="1099" alt="Screenshot 2023-06-13 at 4 41 58 PM" src="https://github.com/metabase/metabase/assets/111726818/788c2f23-75b1-44c3-a1e9-83af511fdad3">

Please let me know if you need any additional information. Thanks in advance 👍

**Comment by yasithab-pf** [comment]
Hello @paoliniluis 

When attempting to add a data source using curl today, I encountered an error that randomly returned the following message.

**Command:**

```
## MetabaseAPI-CreateDatabase
curl -X "POST" "https://metabase.example.com/api/database" \
     -H 'X-Metabase-Session: 65629c95-8da3-3r67-b7ad-9276243efee6' \
     -H 'Content-Type: application/json' \
     -H 'Cookie: metabase.DEVICE=f44rt317-629e-440d-889f-75ea8e458a41; metabase.SESSION=64756c95-8da3-46trd-b7ad-92b88e3654ee6; metabase.TIMEOUT=alive' \
     -d $'{
  "details": {
    "dbname": "demo",
    "password": "demo",
    "port": 3306,
    "advanced-options": false,
    "ssl": false,
    "host": "demo.mysql.local",
    "tunnel-enabled": false,
    "user": "metabase"
  },
  "engine": "mysql",
  "name": "demo-app"
}'

```

**ERROR:**

`│ Error: unexpected response code '500': {"via":[{"type":"java.lang.AssertionError","message":"Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.\n(< (.size puts) impl/MAX-QUEUE-SIZE)","at":["clojure.core.async.impl.channels.ManyToManyChannel","put_BANG_","channels.clj",157]}],"trace":[["clojure.core.async.impl.channels.ManyToManyChannel","put_BANG_","channels.clj",157],["clojure.core.async$put_BANG_","invokeStatic","async.clj",201],["clojure.core.async$put_BANG_","invoke","async.clj",189],["metabase.events$publish_event_BANG_","invokeStatic","events.clj",73],["metabase.events$publish_event_BANG_","invoke","events.clj",66],["metabase.api.database$fn__94994","invokeStatic","database.clj",769],["metabase.api.database$fn__94994","invoke","database.clj",735],["compojure.core$wrap_response$fn__42386","invoke","core.clj",160],["compojure.core$wrap_route_middleware$fn__42370","invoke","core.clj",132],["compojure.core$wrap_route_info$fn__42375","invoke","core.clj",139],["compojure.core$wrap_route_matches$fn__42379","invoke","core.clj",151],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__42379","invoke","core.clj",152],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398","invoke","core.clj",200],["metabase.server.middleware.auth$enforce_authentication$fn__86706","invoke","auth.clj",17],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398","invoke","core.clj",200],["compojure.core$make_context$handler__42426","invoke","core.clj",290],["compojure.core$make_context$fn__42430","invoke","core.clj",300],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$make_context$fn__42430","invoke","core.clj",301],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$make_context$fn__42430","invoke","core.clj",301],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$make_context$fn__42430","invoke","core.clj",301],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$make_context$fn__42430","invoke","core.clj",301],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$make_context$fn__42430","invoke","core.clj",301],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$make_context$fn__42430","invoke","core.clj",301],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$make_context$fn__42430","invoke","core.clj",301],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$make_context$fn__42430","invoke","core.clj",301],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["metabase.api.routes$fn__98511$fn__98514","invoke","routes.clj",64],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398","invoke","core.clj",200],["clojure.lang.AFn","applyToHelper","AFn.java",160],["clojure.lang.AFn","applyTo","AFn.java",144],["clojure.core$apply","invokeStatic","core.clj",667],["clojure.core$apply","invoke","core.clj",662],["metabase.server.routes$fn__98672$fn__98673","doInvoke","routes.clj",70],["clojure.lang.RestFn","invoke","RestFn.java",436],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398","invoke","core.clj",200],["compojure.core$make_context$handler__42426","invoke","core.clj",290],["compojure.core$make_context$fn__42430","invoke","core.clj",300],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__42379","invoke","core.clj",153],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__42379","invoke","core.clj",153],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["compojure.core$wrap_route_matches$fn__42379","invoke","core.clj",153],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398$f__42399$respond_SINGLEQUOTE___42400","invoke","core.clj",197],["metabase.server.routes$fn__98657$fn__98659","invoke","routes.clj",47],["compojure.core$routes$fn__42398$f__42399","invoke","core.clj",198],["compojure.core$routes$fn__42398","invoke","core.clj",200],["metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__95304","invoke","exceptions.clj",103],["metabase.server.middleware.exceptions$catch_api_exceptions$fn__95301","invoke","exceptions.clj",91],["metabase.server.middleware.log$log_api_call$fn__100396$fn__100397$fn__100398","invoke","log.clj",216],["metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info","invokeStatic","diagnostic.clj",18],["metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info","invoke","diagnostic.clj",12],["metabase.server.middleware.log$log_api_call$fn__100396$fn__100397","invoke","log.clj",208],["toucan2.execute$do_with_call_counts","invokeStatic","execute.clj",112],["toucan2.execute$do_with_call_counts","invoke","execute.clj",103],["metabase.server.middleware.log$log_api_call$fn__100396","invoke","log.clj",207],["metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__103823","invoke","browser_cookie.clj",44],["metabase.server.middleware.security$add_security_headers$fn__79562","invoke","security.clj",153],["metabase.server.middleware.json$wrap_json_body$fn__102563","invoke","json.clj",67],["metabase.server.middleware.offset_paging$handle_paging$fn__79586","invoke","offset_paging.clj",45],["metabase.server.middleware.json$wrap_streamed_json_response$fn__102581","invoke","json.clj",103],["ring.middleware.keyword_params$wrap_keyword_params$fn__104090","invoke","keyword_params.clj",55],["ring.middleware.params$wrap_params$fn__104109","invoke","params.clj",77],["metabase.server.middleware.misc$maybe_set_site_url$fn__50518","invoke","misc.clj",61],["metabase.server.middleware.session$reset_session_timeout$fn__63863","invoke","session.clj",441],["metabase.server.middleware.session$bind_current_user$fn__63832$fn__63833","invoke","session.clj",336],["metabase.server.middleware.session$do_with_current_user","invokeStatic","session.clj",315],["metabase.server.middleware.session$do_with_current_user","invoke","session.clj",304],["metabase.server.middleware.session$bind_current_user$fn__63832","invoke","session.clj",335],["metabase.server.middleware.session$wrap_current_user_info$fn__63813","invoke","session.clj",285],["metabase.server.middleware.session$wrap_session_id$fn__63796","invoke","session.clj",217],["metabase.server.middleware.auth$wrap_api_key$fn__86714","invoke","auth.clj",30],["ring.middleware.cookies$wrap_cookies$fn__104010","invoke","cookies.clj",216],["metabase.server.middleware.misc$add_content_type$fn__50500","invoke","misc.clj",29],["metabase.server.middleware.misc$disable_streaming_buffering$fn__50526","invoke","misc.clj",78],["ring.middleware.gzip$wrap_gzip$fn__104052","invoke","gzip.clj",86],["metabase.server.middleware.misc$bind_request$fn__50529","invoke","misc.clj",95],["metabase.server.middleware.ssl$redirect_to_https_middleware$fn__103839","invoke","ssl.clj",51],["metabase.server$async_proxy_handler$fn__99162","invoke","server.clj",77],["metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a","handle",null,-1],["org.eclipse.jetty.server.handler.StatisticsHandler","handle","StatisticsHandler.java",173],["org.eclipse.jetty.server.handler.HandlerWrapper","handle","HandlerWrapper.java",122],["org.eclipse.jetty.server.Server","handle","Server.java",563],["org.eclipse.jetty.server.HttpChannel","lambda$handle$0","HttpChannel.java",505],["org.eclipse.jetty.server.HttpChannel","dispatch","HttpChannel.java",762],["org.eclipse.jetty.server.HttpChannel","handle","HttpChannel.java",497],["org.eclipse.jetty.server.HttpConnection","onFillable","HttpConnection.java",282],["org.eclipse.jetty.io.AbstractConnection$ReadCallback","succeeded","AbstractConnection.java",314],["org.eclipse.jetty.io.FillInterest","fillable","FillInterest.java",100],["org.eclipse.jetty.io.SelectableChannelEndPoint$1","run","SelectableChannelEndPoint.java",53],["org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy","runTask","AdaptiveExecutionStrategy.java",416],["org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy","consumeTask","AdaptiveExecutionStrategy.java",385],["org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy","tryProduce","AdaptiveExecutionStrategy.java",272],["org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy","lambda$new$0","AdaptiveExecutionStrategy.java",140],["org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread","run","ReservedThreadExecutor.java",411],["org.eclipse.jetty.util.thread.QueuedThreadPool","runJob","QueuedThreadPool.java",936],["org.eclipse.jetty.util.thread.QueuedThreadPool$Runner","run","QueuedThreadPool.java",1080],["java.lang.Thread","run",null,-1]],"cause":"Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.\n(< (.size puts) impl/MAX-QUEUE-SIZE)","message":"Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.\n(< (.size puts) impl/MAX-QUEUE-SIZE)"}
`

Thanks in advance :)

**Comment by paoliniluis** [comment]
Yeah, there’s clearly something going on in your Metabase server (specifically in the web server) that can’t handle the load. Do you have something that programmatically hits the server?

**Comment by yasithab-pf** [comment]
@paoliniluis Indeed, we programmatically add user groups and databases using the mentioned curl request. However, we strictly maintain a request rate of 1 request per second, and we never exceed a total of 50 requests per day.

**Comment by paoliniluis** [comment]
If anyone can repro this with a new server and the sample db we will be grateful

**Comment by swaroopsaurav** [comment]
Any resolution to this. I am also facing the same issue. Usually happening with dashboards having many questions

**Comment by paoliniluis** [comment]
I discovered that we did something that increases the cpu load between 44 and 45: https://github.com/metabase/metabase/issues/33567

Also, this error happens when the DB can’t take more load and then operations start queuing on Metabase, so if you do the load test and underpower the DB then you’ll hit this.

I think that the performance regression also brought more load to the App DB and that’s why it started happening when users upgraded.

Temporary solution: increase the sizing (CPU and RAM) of the app db and Metabase

**Comment by paoliniluis** [comment]
Just finished a load testing and https://github.com/metabase/metabase/pull/33397 fixed this
