### ISSUE TITLE
Pin Map keeps zooming on San Francisco

### ISSUE THREAD

**Issue by Hennisa** [metabase/metabase#3152]
-  I am using the Chrome Version 51.0.2704.106 (64-bit) browser.
-  My computer's OS is OS X 10.11.6 (15G31) El Capitan.
-  I'm running Metabase AWS Elastic Beanstalk and it is using the AWS Redshift Database
-  My data is in a _Redshift Database
-  My Metabase version is  v0.19.1.

On Dashboard & New Question sections pin map keeps zooming on San Francisco even though I'm trying to set my default view to Berlin area (where all my data points are located).

**Comment by tlrobinson** [comment]
I think I've reproduced this. Can you confirm it's saving the zoom level but not the coordinates?

**Comment by Hennisa** [comment]
Hi, It is neither saving the zooming level nor the coordinates. Whenever I filter the Dashboard it goes back to same zoom level on San Francisco area even though I have edited the dashboard and set a certain zoom level & coordinates as default.

**Comment by Hennisa** [comment]
<img width="628" alt="screen shot 2016-08-09 at 19 31 05" src="https://cloud.githubusercontent.com/assets/14327271/17526521/dddb4d78-5e67-11e6-8762-d3d8832db1b2.png">

**Comment by hugocar** [comment]
It seems the bug reappeared

**Comment by jesusrtc** [comment]
+1

**Comment by salsakran** [comment]
@jesusrtc + @hugocar  this is fixed in #3693 and should be going out in 0.21

**Comment by hugocar** [comment]
thanks!
