### ISSUE TITLE
Columns don't move

### ISSUE THREAD

**Issue by tylinka** [metabase/metabase#31520]
### Describe the bug

My table was based on SQL query. There were 12 different columns with several variables, which I reordered easily. Then I added 3 additional columns and I can't move them or any column in that table anymore. If you try hard then it can move your chosen (or another random column) in random position. Also I tried to rename columns (it didn't work neither).
Safari and Chrome

### To Reproduce

Make a big table
Try to reorder columns

### Expected behavior

Columns must move easily 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ru",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "4.19.0-18-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-28",
      "tag": "v0.46.2",
      "branch": "release-x.46.x",
      "hash": "8967c94"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

It's annoying and broke the logic of constructed table

**Comment by ptavasci-provart** [comment]
I experienced the same issue and just figured it out.

When you set some columns to invisible, the order becomes completely erratical.
If you make all columns visible again, it will let you reorder just fine, and then you can make them invisible again.

For the development team, I should take a look at relative order instead of absolute order, invisible columns should not be considered when reordering.

**Comment by tylinka** [comment]
> 

Thank you very much! Indeed the problem are in invisible columns.
