### ISSUE TITLE
edit bar and save / cancel not showing up after starting to edit an entity in the data reference

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#3153]
Looks like when you hit edit on segments or metrics the bar is taking up space but not visible which makes it impossible to save edits.
<img width="1680" alt="screen shot 2016-08-09 at 12 03 54 pm" src="https://cloud.githubusercontent.com/assets/5248953/17529754/7203ad0e-5e29-11e6-81bb-cfaa4115f400.png">

*  I am using Chrome v52
*  My computer's OS is Mac OSX
*  My data is in a H2 database. 
*  My Metabase version is HEAD.

**Comment by lewisl9029** [comment]
Thanks @kdoh I'll take a look. Though my first hunch is that this might be one of the angular-apocalypse integration issues I already fixed in the useful-questions branch that hasn't been merged yet.

**Comment by lewisl9029** [comment]
Yep just verified #3060 should fix this.
