### ISSUE TITLE
[Serdes v2] Error parsing JSON when exporting data model

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#31553]
### Describe the bug

Then exporting the data model, some exports fail with JSON parsing errors.

### To Reproduce

1. Get the Audit AppDB creds on [1pass](https://start.1password.com/open/i?a=AEO4BXOSHNFCJLK26XA7AD522E&h=my.1password.com&i=7iueth2ylmucfjkea34wei5nja&v=jc42hdh6wgip5i74fuxzhtqe2i)
2. Serialize this instance `java -jar metabase.jar export audit_instance`
3. See errors on console

### Expected behavior

It should export all fields fine

### Logs

```
2023-06-12 18:14:12,054 INFO models.serialization :: Extracting Database 34
2023-06-12 18:14:12,148 ERROR models.interface :: Error parsing JSON
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'LqgfJr6zyrxMuI': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 15]
```

and

```
2023-06-12 18:11:15,073 INFO models.serialization :: Extracting Field 1,388
2023-06-12 18:11:15,195 ERROR models.interface :: Error parsing JSON
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('m' (code 109)): Expected space separating root-level values
 at [Source: (StringReader); line: 1, column: 3]
```

### Information about your Metabase installation

```JSON
Running on `master`
```

### Severity

P2

**Comment by john-metabase** [comment]
@luizarakaki did you set the encryption key env var for export? We don't have any explicit error message about it, but if an instance is configured with encryption but commands are run without the key, it will encounter problems.

**Comment by luizarakaki** [comment]
Why is the encryption key relevant here?

There are two errors on the logs:

**Database 34** I didn't add the `--include-database-secrets` flag, so it shouldn't serialize encrypted data.
**Field 1388** We don't encrypt any field data

**Comment by piranha** [comment]
@luizarakaki so the exception with databases happens because field `details` is encrypted and you need encryption key to read it correctly. Our current logic is to check if encryption key is not set, then just return the string as is.

**Comment by piranha** [comment]
So right now values coming through json+decryption pass will silently pass decryption step if there is no encryption key configured. We could add a check to see if a value at least somewhat resembles json (starts with `{` or `[` or `"` or is `null`) and if it's not and there is no encryption key - abort the mission with understandable error.

How does that sound?
