### ISSUE TITLE
Performance degradation when query_execution is large

### ISSUE THREAD

**Issue by JohniMichels** [metabase/metabase#31560]
### Describe the bug

After using metabase heavily for the last 4 years our query_execution table has ~58 million rows.
On the last update, the recent views executes a query for every user accessing the home page as per this [file](https://github.com/metabase/metabase/blob/b3f19f9bfcf0eacadf5487b149e7e79db4fdf1e0/src/metabase/api/activity.clj#L115-L132)
This causes performance degradation on the metabase db, since the current execution will scan the entire query_execution table.
Since there's already a index on started_at column, there should be a limit to something reasonable (like last 90 days) on the recent_queries.

### To Reproduce

1. Fill the query execution table with millions of rows
2. Let more than 100 users access metabase
3. DB performance will throttle

### Expected behavior

A DB that worked in previous versions should handle the new version

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.10.178-162.673.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics",
      "redshift",
      "mysql",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-05-24",
      "tag": "v0.46.4",
      "branch": "release-x.46.x",
      "hash": "f858476"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking upgrade

### Additional context

The most used query on our DB:
```sql
SELECT MIN("executor_id") AS "user_id", "query_execution"."card_id" AS "model_id", COUNT(*) AS "cnt", MAX("started_at") AS "max_ts" FROM "query_execution" LEFT JOIN "card_bookmark" AS "bm" ON ("bm"."user_id" = $1) AND ("query_execution"."card_id" = "bm"."card_id") WHERE ("context" = ?) AND ("bm"."id" IS NULL) GROUP BY "query_execution"."card_id", "context" ORDER BY "max_ts" DESC LIMIT $2
```

Relative usage as shown from aws rds console:
![relative-usage](https://github.com/metabase/metabase/assets/28475162/c5b1aa31-f7ca-42d1-ae8b-fcb04329032e)

**Comment by paoliniluis** [comment]
Yup, we know this is an issue and that’s why we’re having an option to trim the log in 47
