### ISSUE TITLE
Cannot download any question form the Audit tab

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#31570]
### Describe the bug

All questions fail to download inside the Audit tab

### To Reproduce

1. Go to stats or any instance with pro features -> Admin -> Audit -> Any question and try to download

<img width="1509" alt="image" src="https://github.com/metabase/metabase/assets/110378427/e55edd9c-9bff-44ad-9065-146ef5facc29">

2. Click on csv and xlsx and these will show corruption in file but if you download json and open it you will get the below:

On stats you get:

```
<html>
  <head>
      <link rel='stylesheet' href='https://www.metabase.com/css/main.css'>
      <title>Metabase instance not found</title>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  </head>
<body>
  <div class="MB-Error">
    <div class="relative mt4 py4 pb5">
      <div class="container sm-text-centered z6">
        <img width="128" height="128" src="https://s3.amazonaws.com/static.metabase.com/plug.png">
        <h1>Metabase instance not found</h1>
        <p>The instance you tried to reach does not exist. Please check the domain in the address bar, or create a new instance in the store.</p>
      </div>
    </div>
  </div>
</body>
</html>
```

On 1.46.5 hosted locally you get:

`"API endpoint does not exist."`

Both have a 404 not found for the json endpoint

<img width="1511" alt="image" src="https://github.com/metabase/metabase/assets/110378427/3da08c2d-dd50-40b2-9d88-3d31d9e7ac2d">

### Expected behavior

download the data

### Logs

"API endpoint does not exist."

### Information about your Metabase installation

```JSON
able to replicate on both 1.46.5 and master
```

### Severity

people are paying for this and not getting the full functionality

### Additional context

Not sure if it's a backend or frontend issue but metabase seems not to be able reach the api endpoint to initiate downloads

**Comment by paoliniluis** [comment]
Both frontend and backend:

Frontend: we're calling ```/api/dashboard/[object%20Object]/dashcard/dashcard8/card/card9/query/xlsx``` which doesn't exist, as the audit section is not a dashboard and the "cards" there, are not cards. In fact, all those cards you see there are calls to internal Metabase functions via the dataset endpoints (e.g.: ```{"type":"internal","fn":"metabase-enterprise.audit-app.pages.queries/most-popular","args":[],"parameters":[]}```)

Backend: as we're calling those cards with very special parameters (type, fn, args, parameters) they don't adhere to our /dataset call parameters (which is simply ```query: {"database":2,"query":{"source-table":10},"type":"query","middleware":{"js-int-to-string?":true,"add-default-userland-constraints?":true}}```)

**Comment by paoliniluis** [comment]
I'm pretty sure this won't get fixed as we'll move all this to the audit v2 stuff @darksciencebase @luizarakaki, which should make this more standard

**Comment by luizarakaki** [comment]
Yeah, Auditv2 uses Metabase native components. We will solve this with the new design.

**Comment by Tony-metabase** [comment]
The milestone on this ticket is wrong it should be linked to the release of Audit V2 which is not part of 47
