### ISSUE TITLE
Master branch of metabase-deploy repository does not include commit which is tagged as 0.19.1

### ISSUE THREAD

**Issue by holtkamp** [metabase/metabase#3158]
First of all, it seems issues can not be reported at https://github.com/metabase/metabase-deploy

Second, one can see that the current master branch does not include the last changes related to [```0.19.1```](https://github.com/metabase/metabase-deploy/tree/v0.19.1).

So:
- the "Deploy to Heroku" button will deploy ```0.19.0``` 
- updating an existing Heroku installation requires to push a specific commit: ```git push heroku c57208ad42a7c086345694fa06b1c2e9a7628df6:master```

![screen shot 2016-08-10 at 15 59 51](https://cloud.githubusercontent.com/assets/776405/17556611/4e4d250c-5f14-11e6-9d1c-1324f47cc584.png)

Or am I missing something?

**Comment by salsakran** [comment]
Good catch. Digging into it.

**Comment by salsakran** [comment]
this should be fixed now.
