### ISSUE TITLE
Archiving dashboard used as a custom homepage leads to "We're little lost"

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#31599]
### Describe the bug

Archiving dashboard used as a custom homepage leads to "We're little lost" being shown.

### To Reproduce

1. Select any of the existing dashboards as a custom homepage
2. Archive that dashboard
3. Navigate to the homepage
4. See "We're little lost" displayed on the homepage
![image](https://github.com/metabase/metabase/assets/31325167/febcdebb-3ef3-42e1-a20a-53745358a53f)

### Expected behavior

Either we shouldn't let custom homepage dashboard be archived, or we should fall back to the regular home page if the dashboard is not available.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Mac OS X",
    "os.version": "13.4",
    "user.language": "en",
    "user.timezone": "Europe/Ljubljana"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-06-14",
      "src_hash": "7902870c35aba903f05d919b0c75dbbf8244d9f8",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "auditv2/test-id-agnosticism",
      "hash": "71b9cfd"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2 because you can recover from this.

**Comment by darksciencebase** [comment]
@cdeweyx any wishes for the expected behavior?

**Comment by cdeweyx** [comment]
> @cdeweyx any wishes for the expected behavior?

@darksciencebase What Nemanja said here:

> We should fall back to the regular home page if the dashboard is not available.
