### ISSUE TITLE
SQL filter gives impression there is no value when you input and then delete the value. 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#31606]
### Describe the bug

Once you setup a filter in an SQL question you need to provide a value else it fails since you are comparing things. If you input a value and remove it then it will work giving the impression the filter is empty where in fact it's taking an empty space.

### To Reproduce

1. Go to New Question -> `Select * from products Where category = {{test}}`
2. Set test filter to a text variable type
3. Follow the following video that shows the inconsistent behaviour when you insert and remove a value form a filter:

https://github.com/metabase/metabase/assets/110378427/0dbe874d-54bb-4b76-9398-58426465819c

4. You will notice even though you removed all the values the filter shows like it's empty ... Its filtering for an empty string "" but that is not visible in the filter and shows the name of the Filter as if it's not being used but then there is a `x` sign which shows there is a value

<img width="847" alt="image" src="https://github.com/metabase/metabase/assets/110378427/9980316f-41cf-4a48-9c9f-cc3cb6b6e91f">

### Expected behavior

Make empty string filtering more intuitive since the filter is not helpful to identify what you are filtering for 

### Logs

None

### Information about your Metabase installation

```JSON
1.46.5 and master
```

### Severity

minor

**Comment by uladzimirdev** [comment]
@Tony-metabase could you please verify the merged solution? Sorry for I forgot to ping you in advance 😄

**Comment by Tony-metabase** [comment]
Yep all good :) Sorry for the delay!
