### ISSUE TITLE
Model name shows as Question n when joined in question notebook editor

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#31627]
### Describe the bug

- Showing Question number instead of Model Name when joining a model
- If starting with a model, the model name is shown, but if any models are not the first data source, then they show up in Filter as Question n instead of with the model name

### To Reproduce

1. Create a model based on Sample Data > Orders
2. Create a new question with Sample Data > Products
3. Open question notebook editor, and add a join to the Orders model that you created in step 1
4. Click filters and see that model name is not present, instead it shows Question n (where n = the question id)

![image](https://github.com/metabase/metabase/assets/8808703/0e59e4a8-f1ec-4d5d-85df-dbd55e595872)

### Expected behavior

- Should show model name

### Logs

#n/a

### Information about your Metabase installation

```JSON
- Metabase v1.46.5
```

### Severity

P3: consistency and usability

**Comment by luizarakaki** [comment]
I think this is a P2, this is very annoying

**Comment by likeshumidity** [comment]
Closing, duplicate.
