### ISSUE TITLE
Trend charts look very broken with new dashboard grid changes

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#31628]
## Context
We updated the dashboard grid row height in https://github.com/metabase/metabase/pull/31019 and it's impacting Trend charts to make them look broken. See the first three cards in the top row of [this dashboard](https://stats.metabase.com/dashboard/357).

## Expected Behavior
- Update font size and spacing to look like it did before
- Make sure this is the case as small as 2x2 (the new min size). We should be able to lean on similar logic that exists for Scalars which truncates the field name with `...` when needed.

**Comment by kamilmielnik** [comment]
### Recordings of behavior using various viewport widths for reference

The question is: "Orders" table from "Sample Database" - "count" summarized by "created at: year".

<details>
<summary>Before - 18 columns</summary>

https://github.com/metabase/metabase/assets/6830683/6c49a819-0763-40ff-8cc0-cdd9389697b3

</details>


<details>
<summary>Now - 24 columns</summary>

https://github.com/metabase/metabase/assets/6830683/227baae7-dcb6-4706-a1a5-c0acbdb475af

</details>

**Comment by cdeweyx** [comment]
Yeah this looks _much_ better. Let's give this list a go. — Thanks for the write-up and investigation here.
