### ISSUE TITLE
Wrong field names when using parameters and joins with Models

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#31624]
Showing field_id and mbql description as field names:

`Activity` is a model
`Group Members` is a model

The `759 is All Users` was applied as a dashboard parameter

[Question link](https://audit-v2-dev.hosted.staging.metabase.com/question/notebook#eyJuYW1lIjoiV2Vla2x5IGFjdGl2ZSB1c2VycyIsImRlc2NyaXB0aW9uIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozNCwicXVlcnkiOnsiYWdncmVnYXRpb24iOltbImRpc3RpbmN0IixbImZpZWxkIiwxNDAyLG51bGxdXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsInRpbWVzdGFtcCIseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lV2l0aExvY2FsVFoiLCJ0ZW1wb3JhbC11bml0Ijoid2VlayJ9XSxbImZpZWxkIiw3NTkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJqb2luLWFsaWFzIjoiUXVlc3Rpb24gMzQifV1dLCJmaWx0ZXIiOlsiYW5kIixbInRpbWUtaW50ZXJ2YWwiLFsiZmllbGQiLDEzOTksbnVsbF0sLTUyLCJ3ZWVrIl0sWyI9IixbImZpZWxkIiw3NTkseyJqb2luLWFsaWFzIjoiUXVlc3Rpb24gMzQifV0sIkFsbCBVc2VycyJdXSwiam9pbnMiOlt7ImFsaWFzIjoiUXVlc3Rpb24gMzQiLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMTQwMixudWxsXSxbImZpZWxkIiw3NTcseyJqb2luLWFsaWFzIjoiUXVlc3Rpb24gMzQifV1dLCJmaWVsZHMiOiJhbGwiLCJzb3VyY2UtdGFibGUiOiJjYXJkX18zNCJ9XSwic291cmNlLXRhYmxlIjoiY2FyZF9fNjcifSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJsaW5lIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsidGltZXN0YW1wIl0sImdyYXBoLm1ldHJpY3MiOlsiY291bnQiXSwiZ3JhcGguc2hvd192YWx1ZXMiOnRydWUsInRhYmxlLmNlbGxfY29sdW1uIjoibW9kZWxfaWQiLCJ0YWJsZS5waXZvdF9jb2x1bW4iOiJlbmRfdGltZXN0YW1wIn0sIm9yaWdpbmFsX2NhcmRfaWQiOjcxfQ==)

Access creds: ([link](https://metaboat.slack.com/archives/C04CYTEL9N2/p1686854600823099))

![Image](https://github.com/metabase/metabase/assets/32561114/08ffe23b-2810-47ee-8bee-a6dc492881f7)

**Comment by camsaul** [comment]
Here's the (legacy) query we're editing, I'm guessing the issue is that the Field in question is not in the metadata and this is the fallback behavior -- we should check whether its in the model metadata tho
```json
{
  "type": "query",
  "query": {
    "aggregation": [
      [
        "distinct",
        [
          "field",
          1402,
          null
        ]
      ]
    ],
    "breakout": [
      [
        "field",
        "timestamp",
        {
          "base-type": "type/DateTimeWithLocalTZ",
          "temporal-unit": "week"
        }
      ],
      [
        "field",
        759,
        {
          "base-type": "type/Text",
          "join-alias": "Question 34"
        }
      ]
    ],
    "filter": [
      "and",
      [
        "time-interval",
        [
          "field",
          1399,
          null
        ],
        -52,
        "week"
      ],
      [
        "=",
        [
          "field",
          759,
          {
            "join-alias": "Question 34"
          }
        ],
        "All Users"
      ]
    ],
    "joins": [
      {
        "alias": "Question 34",
        "condition": [
          "=",
          [
            "field",
            1402,
            null
          ],
          [
            "field",
            757,
            {
              "join-alias": "Question 34"
            }
          ]
        ],
        "fields": "all",
        "source-table": "card__34"
      }
    ],
    "source-table": "card__67"
  },
  "database": 34,
  "parameters": []
}
```

**Comment by camsaul** [comment]
@luizarakaki steps to repro locally?

**Comment by camsaul** [comment]
@luizarakaki please verify the fix whenever this PR hits stats or whatever, I am pretty sure this should fix it but not 100% because there were no steps to repro locally

**Comment by luizarakaki** [comment]
I tested the question I linked in the issue and it is working as expected.
