### ISSUE TITLE
Make Dashboard filters global or tab specific

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#31621]
**Is your feature request related to a problem? Please describe.**
right now, when you add a filter to a dashboard, that filter will apply to all tabs if mapped.

**Describe the solution you'd like**
Ability to have dashboard filters to be global to the whole dashboard or be tab specific. 

**Describe alternatives you've considered**
Clearly can be done by creating filters for each tab and mapping only to that tab, but may end up with a lot of filters.

**How important is this feature to you?**
Maybe will make filters more clear for the user

**Comment by steven1u** [comment]
+1
This would be awesome to have, to better organise dashboards

**Comment by tbarillet** [comment]
Yes it will be awesome

**Comment by TeoM08** [comment]
+1

**Comment by gauravkumar37** [comment]
Hey, I see this is marked as completed but I do not see a commit associated with it. I downloaded the latest 0.49.0-RC2 which lists this enhancement but I do not notice anything regarding this on the filters UI. Please let me know if I am missing anything.

**Comment by steven1u** [comment]
+1!
I don't see the new feature either, unless I'm missing sth

**Comment by steven1u** [comment]
My bad, it seems it works: filters not linked to a tab are not displayed in that tab
