### ISSUE TITLE
Empty state experience of No Saved Question Labels is a little rough

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3163]
Given how unintuitive it currently is to create new labels I think we should add the ability to create labels to the label application dropdown. 

![screen shot 2016-08-10 at 1 28 51 pm](https://cloud.githubusercontent.com/assets/107439/17569644/051044ca-5efe-11e6-89e7-e4cd3d99ba0f.png)

**Comment by mazameli** [comment]
Dropdowns with nothing in them make me die a little inside.

**Comment by mazameli** [comment]
Here's a rough concept. We could add a link to the bottom of the menu like this:
![no questions copy](https://cloud.githubusercontent.com/assets/2223916/17574720/76f703f2-5f18-11e6-8e0b-71d773173f52.png)

And I don't see why we wouldn't want to keep this beyond the empty state, like this:
![with questions](https://cloud.githubusercontent.com/assets/2223916/17574730/885839c2-5f18-11e6-95ef-4d428f47f329.png)

Clicking it would do this:
![in-line label creation](https://cloud.githubusercontent.com/assets/2223916/17574745/9aa4ba7e-5f18-11e6-8a82-c04ffbcfa5ee.png)

Clicking `Done` after inputing some text would take you back to the list of labels, with your new one added to the list. `Cancel` of course would just go back to the existing list of labels.

One piece of weirdness is that you could get some popping-over-a-popover action:
![picking color or emoji](https://cloud.githubusercontent.com/assets/2223916/17574767/b395de32-5f18-11e6-83e5-cd74f8c5dc85.png)

**Comment by salsakran** [comment]
closing as we've moved to a collections based approach with a saner empty state
