### ISSUE TITLE
Content Transfer sanity checks

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#31631]
We want to avoid errors when building the Instance Analytic content.

Add tests to check for

- [ ] the only email in the yaml files are `internal@metabase.com`
- [ ] only .yaml files are in the zip file
- [ ] the root directory in the zip file is `instance_analytics`

**Comment by darksciencebase** [comment]
@escherize has figured out a way to load the instance_analytics from a directory in resources from the uberjar instead
