### ISSUE TITLE
[histogram]how to set the lower bar chart to display the data at the top of the bar chart in histogram

### ISSUE THREAD

**Issue by zhangguoqiang666** [metabase/metabase#31638]
**Is your feature request related to a problem? Please describe.**

May I ask how to set the lower bar chart to display the data at the top of the bar chart in histogram , because put the data in the middle of the column sometimes will not be sight

**Describe the solution you'd like**
I can't find the configuration

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 
it is very important
**Additional context**

**Comment by paoliniluis** [comment]
I don't know what is the "lower bar chart", please post the question in Discourse
