### ISSUE TITLE
I am unable to fetch values from card dimension using GET /api/card/:card-id/params/:param-key/values

### ISSUE THREAD

**Issue by Rahmat711** [metabase/metabase#31645]
### Describe the bug

I am unable to fetch values from card fields using GET /api/card/:card-id/params/:param-key/values

### To Reproduce
```
import requests
# GET /api/card/:card-id/params/:param-key/values

# API endpoint for retrieving a database
url = 'https://xxxxx.in/api/database/'

# Replace with your Metabase session ID
session_id = 'xxxx'

# Replace with the ID of the database you want to retrieve
database_id = 7

# Set headers
headers = {
    'Content-Type': 'application/json',
    'X-Metabase-Session': session_id
}

# Send GET request to retrieve the database with tables
response = requests.get('https://xxxxxx/api/card/222/params/26100/values', headers=headers)
print(response.text)
```
### Expected behavior

It should provide me list of all possible values for fields.

### Information about your Metabase installation

```JSON
Version 114.0.5735.106 (Official Build) (arm64)
```

### Severity

blocking some users

**Comment by paoliniluis** [comment]
You didn't include Metabase troubleshooting info and also the error you're seeing

**Comment by Rahmat711** [comment]
The error i am seeing is **"API endpoint does not exist."** i am using 'https://localhost:8000/api/card/card_id/params/:param-key/values' -> https://localhost:8000/api/card/222/params/id/values'

**Comment by paoliniluis** [comment]
you didn't include troubleshooting info, so we're not able to know if the endpoint you're calling existed in the metabase version you're running

**Comment by Rahmat711** [comment]
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Ubuntu-0ubuntu118.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Ubuntu-0ubuntu118.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1101-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "dremio",
      "postgres",
      "athena",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-16",
      "tag": "v0.44.1",
      "branch": "release-x.44.x",
      "hash": "112f5aa"
    },
    "settings": {
      "report-timezone": "Etc/UTC"
    }
  }
}

**Comment by paoliniluis** [comment]
Please upgrade Metabase, thanks

**Comment by Rahmat711** [comment]
Thanks i will update my version, can you please specify metabase version. that would be very help full :)
