### ISSUE TITLE
Between filter causes an exception in the frontend on refresh

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#31662]
### Describe the bug

If you add a between filter with default values on a dashboard it will work on the first load, but on reload the FE will break

### To Reproduce

1) add a dashboard
2) add a number filter with "between" operator and add 2 values
3) save and refresh
4) if it doesn't break, try refreshing again

see
![image](https://github.com/metabase/metabase/assets/1711649/010abbea-5990-4526-9aa1-46f1ca4582d1)

### Expected behavior

we shouldn't break the FE

### Information about your Metabase installation

```JSON
I think it only happens on master, but have my serious doubts
```

### Severity

P3?

**Comment by ranquild** [comment]
@paoliniluis Could you please describe repro steps in more detail? I can't repro it on the latest master

**Comment by paoliniluis** [comment]
Just hit this one again on stats

1) add a dashboard
2) add a "between" filter on the dashboard
3) add 2 default values on that filter, like 5 and 3
4) save it
5) refresh it
6) refresh it again if not working

BTW: I'm using Brave
![image](https://github.com/metabase/metabase/assets/1711649/26b8b679-2c01-4e9e-92a0-1d8e19e19fb4)
