### ISSUE TITLE
Skip fetching a model index if there is no model

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#31671]
Original Slack convo: https://metaboat.slack.com/archives/C505ZNNH4/p1686918534218189

We should not call `/api/model-index` when the model editor is open and there is no model id.

## Steps
- New -> Model
- Open devtools -> network tab
- There is a failed request to `/api/model-index`

**Comment by rafpaf** [comment]
The problem seems to be that `props.question.id()` returns `undefined` here when the model is new: https://github.com/metabase/metabase/blob/51e7f99d4472303994b2c4b0b8c34eb54b09dbb9/frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx#L523-L529
