### ISSUE TITLE
Native MongoDB queries don't work if they contain ISODate() calls

### ISSUE THREAD

**Issue by cwbeck** [metabase/metabase#3170]
Query fails to run: (MongoDB)

``` json
[
  {
    "$match": {
      "hour": {
        "$gte": ISODate("2016-08-09T00:00:00Z")
      }
    }
  },
  {
    "$group": {
      "_id": {
        "year": {"$year": "$hour"},
        "month": {"$month": "$hour"}
      },
      "count": {
        "$sum": "$count"
      }
    }
  }
]
```

```
Unrecognized token 'ISODate': was expecting 'null', 'true', 'false' or NaN at [Source: java.io.StringReader@2b0b4b64; line: 6, column: 24]
```

**Comment by camsaul** [comment]
@cwbeck it looks like Metabase is trying to parse your MongoDB query as JSON (which works in most cases). We need to skip parsing and just pass the query string in directly because as this example shows Mongo aggregation pipeline queries are not necessarily strict JSON.

**Comment by cwbeck** [comment]
@camsaul thanks for the update. I'll take a look shortly

**Comment by camsaul** [comment]
So as far as I can tell there is no easy way to handle this situation given our current setup with Monger. I've reached out to the library authors to see if they have any ideas how we can work around this: https://github.com/michaelklishin/monger/issues/143

In the meantime, I'm going to mark this as a limitation

**Comment by Compuabhi** [comment]
@camsaul i was dealing with MongoDB native queries in metabase. In sql, one can add query parameters using {{var_name}}. What is the format for MongoDB query parameters? Using same format was throwing errors that "It is expecting double-quote to start field name.

**Comment by camsaul** [comment]
Fixed by #4132

**Comment by daorren** [comment]
@camsaul can U provide an example for `ISODate()`
I tried as below, neither worked
```
[
    {
      "$match": {"$and": [
          {"logType": "ClickGlobalNavBtn"},
          {"target": "Mail"},
          {"created": {"$gte": "ISODate(2018-06-21)"}}
      ]}
    },
    {
      "$group": {"_id": "$target", "count": {"$sum": 1}}
    }
]
```
or
```
[
    {
      "$match": {"$and": [
          {"target": "Mail"},
         {"created": {"$gte": ["ISODate", "2018-06-21"]}}
      ]}
    },
    {
      "$group": {"_id": "$target", "count": {"$sum": 1}}
    }
]
```

**Comment by mhdali93** [comment]
Not working for me, it is showing: No results!
This may be the answer you’re looking for. If not, try removing or changing your filters to make them less specific.
