### ISSUE TITLE
I shouldn't be able to select filters, view options, or groupings until I've chosen a table

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3171]
I can't remember if this behavior has always been possible, so it might be a regression. In any case, it's super stupid that I can do this, especially because these selections get wiped out when I finally **do** pick a table:

![screen shot 2016-08-11 at 10 19 29 am](https://cloud.githubusercontent.com/assets/2223916/17597985/2bff9266-5fad-11e6-8abc-c0ffab55f354.png)

**Comment by tlrobinson** [comment]
This was probably a result of the reduxification of the query builder. I think it can only occur if you've previously loaded a different card then click "new question". We probably aren't clearing out all of the qb state.

**Comment by Pritoj** [comment]
I want to contribute to this project and was trying to replicate this issue but couldn't.

I tried @tlrobinson's way as well but couldn't replicate it.. Can you maybe give steps for replication?

**Comment by mazameli** [comment]
Pritoj, are you running the latest build from `master`? The steps to replicate should be:
1. open up a previously saved question
2. from that screen click on `new question` in the main nav
3. observe that you can select filters, aggregations, and groupings even though you haven't selected a table yet

**Comment by tlrobinson** [comment]
This will be fixed by #3738
