### ISSUE TITLE
yarn add cypress@12.8.1 error

### ISSUE THREAD

**Issue by WSYProject** [metabase/metabase#31713]
### Describe the bug

when execute "yarn" command, an error has occurred，the error message is as follows：
<img width="1021" alt="image" src="https://github.com/metabase/metabase/assets/33391668/4f26c8e9-f8d2-4d43-8c3c-7e9aefe61917">

### To Reproduce

1. Go to 'yarn'
2. See error
<img width="1021" alt="image" src="https://github.com/metabase/metabase/assets/33391668/8b17dcc6-d167-4de0-bf85-f84c283d65de">

### Information about your Metabase installation

```JSON
node --version // 18.14.2
yarn --version  // 1.22.19
```

### Severity

I want run frontend developmemnt environment

**Comment by paoliniluis** [comment]
Use node 16

**Comment by WSYProject** [comment]
> Use node 16

use node 16.14.1 and use node 16.16.0，the same bug still appears

**Comment by WSYProject** [comment]
@paoliniluis 
I found an answer under cypress-io, download issue resolved.
github address：https://github.com/cypress-io/cypress/issues/26228
