### ISSUE TITLE
Mongo nested fields being displayed in the QB filter dropdown without the top level 

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3173]
Eg, for the parse backend's mongo collections, there are documents like:
{"acl":{"blah":1}} that are being showing in the query builder as 
a field named `blah` instead of a field named `acl.blah`

**Comment by camsaul** [comment]
@salsakran So they are being shown? Does that mean #1328 is fixed?

**Comment by tlrobinson** [comment]
Do we want to do `acl.blah` or `acl: blah`, since the names will be humanized and thus might contain spaces.

**Comment by tlrobinson** [comment]
e.x.

![screen shot 2016-11-14 at 1 48 39 pm](https://cloud.githubusercontent.com/assets/18193/20284197/012b64fc-aa71-11e6-8d8c-e8d4283113fc.png)
![screen shot 2016-11-14 at 1 48 21 pm](https://cloud.githubusercontent.com/assets/18193/20284198/0158d9f0-aa71-11e6-828c-d2f27a16fd47.png)
