### ISSUE TITLE
Linked dashboard filters that use field filters of the same table are not being linked

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#31785]
### Describe the bug

So I was checking https://github.com/metabase/metabase/issues/16872, which "should" have a workaround (not very clear), but now if you do the query and connect to fields that are all in the same table, it won't work either

### To Reproduce

1) create a SQL question like:
```
SELECT * FROM people
WHERE {{id}}
AND {{source}}
```
id is a field filter to the people.id column
source is a field filter to the people.source column

2) build a dashboard, add the SQL question you just created and add 2 filters, ID and Source, connect those 2 filters to the SQL question. You see that metadata gets populated (as they're field filters)
3) now embed it (signed embedding), passing 2 as the ID value (locked) and leaving the source filter editable
3) see all values getting populated in the source filter, should be just 1 ("Twitter")

Also, if you link them, it doesn't matter, it will still show all the values

### Expected behavior

If we have all the metadata of those 2 filters, we should show just the values that match the condition (in the example, just source = Twitter, just as you do with a GUI question

### Logs

None

### Information about your Metabase installation

```JSON
I'm almost sure this worked before, but I checked this in v45, 46 and 47 now
```

### Severity

Kinda P0-P1

**Comment by calherries** [comment]
I can't reproduce this on master. I set up a signed embedding with the steps above and link filters are working as expected:
<img width="523" alt="image" src="https://github.com/metabase/metabase/assets/39073188/592d1b55-54f3-424d-856f-b6a71fc3804c">

loom demo: https://www.loom.com/share/d45a1ad189a147fc9b64911282945237?sid=9d043808-b251-414e-bf0c-1ea458615806

**Comment by paoliniluis** [comment]
This clearly works, pretty much I was completely exhausted yesterday night when testing this and I might have forgotten something.

**Comment by paoliniluis** [comment]
taking it out while the customer replies

**Comment by paoliniluis** [comment]
Cancelling
