### ISSUE TITLE
Back to dashboard button doesn't go back to the right tab

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#31786]
**Is your feature request related to a problem? Please describe.**
After clicking thru a question from a dashboard, when you try to click on the "Back to <dashboard>" button, it will take you back to the dashboard, but always to the first tab instead of the other tab that you were previously on. 

It also removed any applied filters as well, so you need to redo those too. 

**Describe the solution you'd like**
It should take you back to the same tab with the same filters applied. 

**Describe alternatives you've considered**
Manually re-click on the right tab after going back to dashboard and re-apply filters. 

**How important is this feature to you?**
It's just convenience. But it gets annoying if you need to drill-thru different cards several times and go back to the dashboard. 

**Additional context**
n/a

```[tasklist]
### Milestone 1
- [ ] https://github.com/metabase/metabase/pull/32142
- [ ] https://github.com/metabase/metabase/pull/32147
- [ ] https://github.com/metabase/metabase/pull/32196
- [ ] https://github.com/metabase/metabase/pull/32192
```

**Comment by maxzheng** [comment]
@cdeweyx I think ideally the dashboard should remember what tab and filters were used, so that when you visit a dashboard, it will restore the last view (regardless of how the user gets back to the dashboard). Then it will naturally solve the problem for the back to dashboard link. Currently, I find myself constantly having to re-apply filters and re-clicking tabs.

**Comment by uladzimirdev** [comment]
@maxzheng could you please verify https://github.com/metabase/metabase/pull/32192 before merging?
