### ISSUE TITLE
Message on homepage when homepage is customized to be a dashboard appears every time you go to the homepage

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#31802]
### Describe the bug

When going to the homepage, I see a message:

Your admin has set this dashboard as your homepage [Got it]

This message appears every time I go to the homepage, even if I press the [Got it] button.

### To Reproduce

1. Go to Admin, General
2. Set CUSTOM HOMEPAGE to be a dashboard
3. Log in as a different user
4. Press "Got it"
5. Press the home icon

### Expected behavior

This message should appear only once

### Information about your Metabase installation

```JSON
- Using Chrome
- Master built on June 22
```

### Severity

It's very annoying.  I'm starting to resent the admin who made this change.

**Comment by darksciencebase** [comment]
https://metaboat.slack.com/archives/C056QEW4KNF/p1687461617554309?thread_ts=1687454676.162179&cid=C056QEW4KNF
