### ISSUE TITLE
Filter modal search icon is tiny

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#31814]
### Describe the bug

The search icon on the question filter modal is really small, and as this it houw you expand the search box it's hard to find.
![image](https://github.com/metabase/metabase/assets/4504437/5aed2c6f-f3ba-42f2-82db-42bec66903d4)

Looks like the svg is sized appropriately but the path drawn within has been shrunk.
![image](https://github.com/metabase/metabase/assets/4504437/52c55090-68c5-4978-953a-7d2da37f4fb6)

### To Reproduce

1. Start a new question on any table
2. Visualise it
3. Click the "Filter" button (top right)
4. Filter modal is displayed and you'll see that the magnifying glass icon is really small (top right beside the close "x")

### Expected behavior

Icon should be easier to see.

### Logs

Nothing of interest in logs

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-21",
      "tag": "v0.47.0-RC1",
      "branch": "master",
      "hash": "4323f01"
    },
    "settings": {
      "report-timezone": "NZ"
    }
  }
}
```

### Severity

low, visual only

**Comment by mazameli** [comment]
Thank you, I missed this when doing the big icon update!
