### ISSUE TITLE
Build frontend components as an analytics component library

### ISSUE THREAD

**Issue by hotlong** [metabase/metabase#31846]
**Describe the solution you'd like**

Our team is working on an enterprise low-code platform [Steedos](https://github.com/steedos/steedos-platform) and we hope to introduce data analysis functionality.

Metabase has great front-end and back-end capabilities, but if it is directly connected to the database, it cannot be integrated with the existing permission management system.

We want build frontend components as an analytics component library with following components:

- Data Browser Component
- Question Component
- Card Component
- Dashboard Component

We will implement data query APIs in Steedos Platform according to the existing API specifications of Metabase, and add permission control features on top of that.

**How important is this feature to you?**

Very important

**Additional context**

Do we need additional license agreement if we only use the community edition frontend code in the control repository and not the EE portion?

**Comment by paoliniluis** [comment]
@hotlong send an email with your licensing questions to our sales at Metabase dot com mailbox
