### ISSUE TITLE
Our 404 error is not humanized

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#31840]
### Describe the bug

if you go to a question that doesn't exist it will give you

![image](https://github.com/metabase/metabase/assets/1711649/1636fca7-a818-4be6-b726-c4e4d95e40b5)

let's put a more human message

### To Reproduce

1) spin up 47
2) go to a link that doesn't exists (like /question/999)
3) see the message

### Expected behavior

a more human error

### Logs

NA

### Information about your Metabase installation

```JSON
v47
```

### Severity

P3

**Comment by dpsutton** [comment]
closed by https://github.com/metabase/metabase/pull/35695
