### ISSUE TITLE
Additional colors in chart settings

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#3185]
Currently we have 5 (very nice) colors available for line/area/bar charts. We should consider allowing the user to pick a custom color, or at least adding some basic colors like gray, as requested in #2596

**Comment by cwbeck** [comment]
this would be very very useful!!

**Comment by anki-code** [comment]
Many colors please! I really have big pain with this issue 😷 

Also I've found the bug (0.22):

![image](https://cloud.githubusercontent.com/assets/1708680/21852054/b220de3e-d822-11e6-9ae8-642243bb4311.png)

**Comment by Hennisa** [comment]
This would be very useful for us too since for some charts we have 5+ series (series as weekdays for example)

**Comment by kdoh** [comment]
#4270 Should help ease the color pain and will be shipping as part of version 0.23. Thanks to everyone for their input on this.
