### ISSUE TITLE
Cannot execute simple actions against the CSV uploaded model

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#31867]
### Describe the bug

Frontend blows up when trying to execute simple action against the CSV upload (automatically created model based on the CSV upload).

### To Reproduce

_Make sure "Model actions" are enabled for the Sample Database
1. Go to Admin > Settings and enable Uploads on a Sample Database with the default `PUBLIC` schema
<img width="658" alt="image" src="https://github.com/metabase/metabase/assets/31325167/99d9df5c-8d98-4cf4-9f22-c6670137b2a1">

2. Go to "Our analytics"
3. Click on the upload icon and upload any CSV file (you can use one from here: https://www.datablist.com/learn/csv/download-sample-csv-files)
4. Open that model actions `model/id/detail/actions`
5. Click "Crete basic actions"
6. Try to execute the "Delete" action

FE fails with "Something's gone wrong".

What's interesting is that even when you edit model's metadata and explicitly set the primary key, this still fails.

### Expected behavior

FE shouldn't result in an error page. It should rather warn that the primary key is missing (if that's the requirement) or it should assume a PK column and execute an action.

### Logs

```
utils.ts:160

Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at generateFieldSettingsFromParameters (utils.ts:160:1)
    at getOrGenerateFieldSettings (utils.ts:134:1)
    at use-action-form.ts:26:1
    at mountMemo (react-dom.development.js:15442:1)
    at Object.useMemo (react-dom.development.js:15738:1)
    at useMemo (react.development.js:1521:1)
    at useActionForm (use-action-form.ts:25:1)
    at ActionForm (ActionForm.tsx:53:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)


The above error occurred in the <ActionForm> component:
```

### Information about your Metabase installation

```
local dev, latest master deced97db63a583a384aceb9f44a043a54c1b697, H2, Sample Database

also on 47-RC1
```

### Severity

P1 if running actions against CSV uploads is expected behavior.

### Additional context

Trying out "Create" and "Update" actions results in 
```
Must execute implicit action on a table with a single primary key.
```

This happens before one edits model metadata (when we still have no semantic data), but also even after explicitly telling Metabase that a certain column should be PK.

**Comment by cdeweyx** [comment]
@iethree I see you're assigned on https://github.com/metabase/metabase/issues/31867 so wanted to flag this as the broader root cause issue for that.
