### ISSUE TITLE
Reverting a question to a revision prior to Metabase upgrade 0.46 does not work

### ISSUE THREAD

**Issue by Gerrit-K** [metabase/metabase#31901]
### Describe the bug

We recently upgraded our Metabase instance from `v0.45.2` to `v0.46.4` and are unable to revert some questions to older versions since then. When clicking on the "Revert to this version" button in the frontend, nothing seems to be happening. Inspecting the server logs reveals that there is an exception, which essentially says:
```
ERROR: column "is_write" of relation "report_card" does not exist
```
This leads me to believe it has something to do with the huge PR #27413 where I think this column has been removed.

### To Reproduce

It's currently pretty difficult for me to actually test this, but I would assume these steps would reproduce the behavior:

1. Install Metabase <0.46
2. Create a question
3. Upgrade to >0.46
4. Edit that question
5. Attempt to roll back to the previous version

### Expected behavior

The rollback should work

### Logs

If needed, I can attempt to sanitize and share the full stack trace

### Information about your Metabase installation

```JSON
self-hosted `v0.46.4` in docker on kubernetes using a Postgres database
```

### Severity

Annyoing, since we cannot roll back, but manual reverts should be possible

**Comment by jmaicher** [comment]
We're affected by this as well. The card objects are still serialized with the `is_write` property in the revision table and [revert-to-revision!](https://github.com/metabase/metabase/blob/master/src/metabase/models/revision.clj#L32) then fails with the above error because the `is_write` column doesn't exist.

**Comment by paoliniluis** [comment]
yup, valid, I just repro'd

**Comment by ignacio-mb** [comment]
@noahmoss is this 50.11?
