### ISSUE TITLE
[MLv2] Port custom expressions to MLv2

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#31910]
Our custom expressions implementation operates with MBQL directly on a low level. In order to fully move the expression editor to MLv2 we need to migrate logic inside `frontend/src/metabase-lib/expressions/**` **except**:
- `frontend/src/metabase-lib/expressions/suggest.ts`
- `frontend/src/metabase-lib/expressions/helper-text-strings.ts`

Since porting all functions dealing with the textual representation and editing of expressions is a fairly big chunk of work, we should postpone that so that we can focus on the migration of the main code to MLv2. The suggested way forward is the following:
- make the JS expression parsers capable of outputting `ExternalOp` objects (it might be the easiest to add an option the caller can use to opt-in to the new output format)
- make sure the relevant MLv2 functions can take `ExternalOp` arguments
- either port the `format` function to MLv2 or make it capable of formatting `ExternalOp` objects (since the `format` function is quite small, just porting it might be simpler)

**Comment by camsaul** [comment]
Discussion on Slack about what to port https://metaboat.slack.com/archives/C04CYTEL9N2/p1687885036622849?thread_ts=1687879267.933529&cid=C04CYTEL9N2

**Comment by metamben** [comment]
Discussion on Slack about the way forward: https://metaboat.slack.com/archives/C04CYTEL9N2/p1688074675774869

**Comment by camsaul** [comment]
RE 
> In order to fully move the expression editor to MLv2 we need to migrate logic inside `frontend/src/metabase-lib/expressions/**` except

That's all these files:

```
├── completer.js
├── config.js
├── diagnostics.js
├── format.js
├── index.js
├── pratt
│   ├── compiler.ts
│   ├── index.ts
│   ├── parser.ts
│   ├── syntax.ts
│   └── types.ts
├── process.js
├── recursive-parser.js
├── resolver.js
├── __support__
│   ├── expressions.js
│   └── shared.js
├── tokenizer.js
├── typeinferencer.js
└── types.ts
```

I don't think we need to move all that stuff to Cljs. The parser can stay in TS for now as long as it's hooking into MLv2 where appropriate.
