### ISSUE TITLE
Can't remove certain cards from dashboard

### ISSUE THREAD

**Issue by nigeljyng** [metabase/metabase#3192]
Sorry for opening another thread. But I'm running into the problem of not being able to remove cards from the dashboard. When I hover over the cards, the 'x' does not appear on the top right corner. This bug appears on bar and line charts. It seems to be fine with pie charts and single number cards. I haven't tried other chart types.

Running Metabase  v0.19.2 built on 2016-08-10 on Docker on an AWS Ubuntu instance.

**Comment by tlrobinson** [comment]
Sorry about that. This has been fixed in 0.19.3.
