### ISSUE TITLE
Account Settings page should look like the rest of the app

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3193]
Currently it uses a layout/style that isn't really used anywhere else in the product, so it's jarring.

**Comment by camsaul** [comment]
![image](https://cloud.githubusercontent.com/assets/1455846/17679201/421039d0-62ef-11e6-9b6a-1fe5706db95f.png)

**Comment by mazameli** [comment]
Your gift for pun images is un-**can**-y.

**Comment by mazameli** [comment]
One thing I'm wondering with this is if we could get rid of the need to use tabs, and just have both the personal info and the change password fields on the same screen. This could be approached with either one or two buttons, but I think two buttons makes it clearer which action you're performing:

![25 copy 10](https://cloud.githubusercontent.com/assets/2223916/17794354/7e3ed058-6563-11e6-9d86-5d3010df35fa.png)

I also think we can kill the confirm new password field, especially if we introduce a show/hide password toggle. I'd also love to get rid of the number requirement for passwords and maybe just up the character limit from 6 to 8 or something instead, so that people can more easily use passphrases.

**Comment by salsakran** [comment]
Two forms on one pane with different submit buttons? 👎

**Comment by mazameli** [comment]
Fair enough, though it might be easy enough to clarify with frames:
![two buttons with frames](https://cloud.githubusercontent.com/assets/2223916/17875249/a0913e5a-6885-11e6-9452-f6f2d23ba066.png)

 A single button is obviously an option, though I think it can be slightly confusing to have the change password stuff there if all you're doing is updating your email or something:

![one button](https://cloud.githubusercontent.com/assets/2223916/17875217/5860bf70-6885-11e6-9ae2-7cf1a156d9cb.png)

Another option is keeping the forms on separate views like we currently have, but just updating the visual style so that it looks like other parts of the app, e.g. using the left sidebar that's on the saved questions page. Feels slightly like overkill, but is arguably the clearest IX approach, and might be the easiest to implement.

![side panel a](https://cloud.githubusercontent.com/assets/2223916/17875238/84576c8c-6885-11e6-80a5-3f5b68b18319.png)

![side panel b](https://cloud.githubusercontent.com/assets/2223916/17875241/8956723c-6885-11e6-8ee4-1ad57c149f0d.png)

**Comment by salsakran** [comment]
I strongly prefer the last approach.

A single button is confusing and I personally prefer a strong separation between changing your password and the rest of your profile. Multiple forms in a single page still feels really hokey for me.

**Comment by mazameli** [comment]
Ship it. 👍

**Comment by flamber** [comment]
@mazameli 
Fun to see how Metabase looked in the early versions :-) But this is already implemented, right? 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52895120-619e1800-317b-11e9-909b-ab07f5b201d1.png)

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/9937
