### ISSUE TITLE
Navigation should be usable on a mobile device

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3194]
Currently, you can't even see several of the nav items at small screen widths:

![screen shot 2016-08-15 at 1 37 02 pm](https://cloud.githubusercontent.com/assets/2223916/17678779/7617d8a2-62ed-11e6-8208-efd7d9943808.png)

A solution should include a way to access all of the main navigation menu items from a mobile phone. 

Open question: what's the minimum pixel width we plan on supporting?

**Comment by anki-code** [comment]
+1

**Comment by moumny** [comment]
iPad support for CEO dashboards plz ^^

**Comment by anki-code** [comment]
I think MVP for this feature is just minimizing menu to icon:

![image](https://cloud.githubusercontent.com/assets/1708680/21161775/17b478d0-c19b-11e6-8699-bac836180c6d.png)

**Comment by mazameli** [comment]
This was fixed a while back.
