### ISSUE TITLE
Reorganize Data Reference detail subsections

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3195]
Right now it's a bit cumbersome to navigate through the new Data Reference. Specifically, it's hard to navigate "laterally" between items at the same level of hierarchy, such as tables within a single database or namespace; you have to keep going back up a level.

We should consider bringing the subsection navigation for Data Reference entries into the main content area for that item, freeing up the sidebar to maintain navigation for other items at that same level of hierarchy.

This isn't a final design, but here's an illustration. In this example, this new navigation would let the user quickly riffle through the other metrics without having to go back or up a level. It also gives us more room for more relevant breadcrumbs:

![screen shot 2016-08-15 at 1 58 58 pm](https://cloud.githubusercontent.com/assets/2223916/17679606/fd9dfdc6-62f0-11e6-8fa8-85a718635b9f.png)

Current implementation, for context:

![screen shot 2016-08-15 at 2 03 19 pm](https://cloud.githubusercontent.com/assets/2223916/17679630/127774e8-62f1-11e6-8c54-9566768150ec.png)

Props to @tlrobinson for suggesting this.

**Comment by brunobergher** [comment]
Not applicable anymore.
