### ISSUE TITLE
Increase design control over Big Numbers (Trend Chart)

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#31951]
**Is your feature request related to a problem? Please describe.**
There is no such way of customizing the text displayed on Big Numbers (BANs) on dashboards.

**Describe the solution you'd like**
**Is your feature request related to a problem? Please describe.**
It would be great to control the function behind the Trend chart and, in consequence, the text displayed.
For example, instead of comparing the amount from this period to last year's period, calculate the % over the total of some value.

**Describe alternatives you've considered**
Using other charts or adding text cards with the info but it's not the same thing

**How important is this feature to you?**
This is addressed because Trend chart is the only BAN Metabase offers besides Number viz, and a customer would find it helpful to have more control over the text and function applied. 

**Additional context**
NA

**Comment by icemtel** [comment]
Trend chart suggestion: instead of "+X% last week", show "+X% previous week"

A common use case is that you compute a metric on Monday morning for the last week. Then you want to compare to the week **before that**. Alternatively, increase design control as described by the issue author.
