### ISSUE TITLE
Snowplow "task" events could not be processed on production

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#31955]
### Describe the bug

There are a lot of errors related to `task` snowplow schema on production, many events are discarded

<img width="1424" alt="Screenshot 2023-06-28 at 18 43 56" src="https://github.com/metabase/metabase/assets/8542534/215c406c-550e-4359-b8f8-98252eaa4ada">

### To Reproduce

Go to our snowplow instance -> Data inspector -> Bad rows. Please ping me if you need more details.

### Expected behavior

No bad rows.

### Logs

For `details`:

```
{
  "messages": [
    {
      "error": {
        "dataReports": [
          {
            "path": "$.task_details",
            "message": "$.task_details: may only be 2048 characters long",
            "keyword": "maxLength",
            "targets": [
              "2048"
            ]
          }
        ],
        "error": "ValidationError"
      },
      "schemaKey": "iglu:com.metabase/task/jsonschema/1-0-0"
    }
  ],
  "timestamp": "2023-06-28T15:42:19.954Z"
}

```

For `duration`:
```
$.duration: must have a minimum value of 0
```

### Information about your Metabase installation

```
0.47 RC1
```

### Severity

Invalid data on stats

**Comment by calherries** [comment]
Backports PRs:
```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/31977
- [ ] https://github.com/metabase/metabase/pull/31978
- [ ] https://github.com/metabase/metabase/pull/31979
```

**Comment by calherries** [comment]
I backported the removal of snowplow tracking to 46, 45, and 44 release branches (even if this fix isn't worth it to justify a 45 and 44 bugfix release, these changes will go out with the next release).
