### ISSUE TITLE
Dashboard click through behavior to a question does not pass time filters correctly

### ISSUE THREAD

**Issue by crupley** [metabase/metabase#31960]
### Describe the bug

When setting up click through behavior on a dashboard that goes to a custom destination question, the time filters are not passed correctly. If the chart is set up with a time grouping, for example 'by month', the filter passed to the underlying question should be a time range (e.g. between June 1 - June 30), but instead it passes a filter for just the first day of the range (e.g. "on June 1").

### To Reproduce

1. Create a dashboard with a chart that is grouped by some time interval.
2. Set up click through behavior:
  3. Go to a custom destination
  4. Question
  5. Select the same chart that is in the dashboard
  6. Select the same date column that is used for grouping to pass through as a filter
7. Save the dashboard updates
8. Click a point on the chart to drill down
9. The chart will not show the correct number of results and the time filter will be a single point instead of the range that it should correspond to.

### Expected behavior

The time filter should be a range that corresponds to the grouping on the chart

### Logs

No admin access, nothing relevant in the console.

### Information about your Metabase installation

```JSON
No admin access
```

### Severity

Prevents us from using this drill down feature. There is a workaround that involves additional work and could introduce errors.

### Additional context

Chart in dashboard showing time range:

![Screenshot 2023-06-28 at 10 17 57 AM](https://github.com/metabase/metabase/assets/2078673/ce9b5fc1-1e75-49ce-bab5-b25eefe70dda)

After click through only filtering to a single day:

![Screenshot 2023-06-28 at 10 18 12 AM](https://github.com/metabase/metabase/assets/2078673/6d01b679-2f6d-44f5-a19a-548853944ad2)

**Comment by FilmonK** [comment]
Here's a Loom recording of this issue.
https://www.loom.com/share/bcde88477b8f459aa8c711fa61977bb3

**Comment by darksciencebase** [comment]
@FilmonK does it reproduce on `master`?
