### ISSUE TITLE
Dashboard cards are supposed to fade out if not connected to an active filter

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3196]
These two cards aren't wired up to this dashboard filter:

![screen shot 2016-08-15 at 2 46 10 pm](https://cloud.githubusercontent.com/assets/2223916/17680845/2c042d88-62f7-11e6-8966-937676ad3f5f.png)

When I activate the filter, the expected behavior is that these two cards should fade back to show they're not being filtered (b/c they're not wired up), but they don't do that. This seems to be the case for every filter type. Unclear if this happens only for GUI cards, or SQL cards as well.

![screen shot 2016-08-15 at 2 46 35 pm](https://cloud.githubusercontent.com/assets/2223916/17680896/617d21a4-62f7-11e6-85d5-555c67661bba.png)

**Comment by federicokeen** [comment]
I'm experiencing the same issue 👍
