### ISSUE TITLE
Filter list values in looked filters

### ISSUE THREAD

**Issue by jatorna** [metabase/metabase#31998]
I am developing an application with the free version. To only display the data for each user in my single database, I filter a column by a locked filter using the signed embed.

The problem is that when I have filters with dropdown lists, the values ​​of those lists take all the data of the question. Is there a way to make the filter values ​​relate to the locked mandatory filter?

**Comment by paoliniluis** [comment]
This should work right now. If you’re using a sql question then use field filters.
