### ISSUE TITLE
SQL parameters missing from TOC in 0.19.3 documentation

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3202]
As noted by @mazameli it was present in the 0.19.0 documentation, but it looks we might have ran into a merge conflict or other broken linkery of some sort.

**Comment by salsakran** [comment]
looks right to me https://github.com/metabase/metabase/blob/release-0.19.3/docs/users-guide/start.md. Going to fix in the docs repo, and close this issue.

**Comment by salsakran** [comment]
fixed - http://www.metabase.com/docs/v0.19.3/users-guide/start.html
