### ISSUE TITLE
how to allow cross origin requests?

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#3203]
Use Case: Trying to create a session based on a post request from another origin
Found this: https://github.com/r0man/ring-cors

PS: Clojure illiterate. 😫

**Comment by camsaul** [comment]
@VikramTiwari can you tell us a little more about why you would want to do this?

**Comment by VikramTiwari** [comment]
Trying to emulate something similar to "magic link" used by Slack

**Comment by salsakran** [comment]
@VikramTiwari we specifically disallow cross origin requests to XSS attacks and their ilk.

We'll have a different auth scheme once we explore embedding, but in general for the core metabase application we won't be allowing this.

If you're interested in SSO with slack, that's definitely something we're thinking about, with #3210 being a first step in that direction.
