### ISSUE TITLE
Lets get the CII Best Practices Badge! 🏅

### ISSUE THREAD

**Issue by brasilikum** [metabase/metabase#3204]
The linux-foundation came up with a badge program for Core Infrastructure that awards a open source projects for following best practices.

https://www.coreinfrastructure.org/programs/badge-program

I think a lot of the criteria is already fulfilled by this app, like secure download via https and so on.
Others are still to do, like securing the project website via https.
There could be a milestone  called CII with issues for each unmet [criteria](https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/criteria.md).

What do you think, do you want to get the badge? I am willing to contribute because I really love the simplicity and the focus on data-sharing of metabase. I would really appreciate to have it certified that the project follows best practices and therefore will be around for a long time!

**Comment by salsakran** [comment]
Hey @brasilikum -

Appreciate you taking the time to think of us, and agree with you on the goals of creating a project that will be around a long time. =)

That said, as a team of core committers, we're focused on our users, the actual product and our own process for creating the best BI application out there (that happens to be OSS). 

While there are a lot of great points of advice in that program, we're not specifically interested in any kind of external credentialing and definitely not going to be doing work to earn a badge at the expense of doing work that closes bugs, improves core features or adds new features that help out our users. 

That said, we'd *love* it if you could help. Check out https://github.com/metabase/metabase/blob/master/docs/contributing.md for info on how we do things and ways you can help out.

<3
