### ISSUE TITLE
Row charts do not render when aggregating 

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#32044]
### Describe the bug

When you are aggregating by a custom column, the row chart fails to render:

<img width="930" alt="image" src="https://github.com/metabase/metabase/assets/22856340/9ad195ee-0472-4075-8930-6640cf9125a7">

### To Reproduce

1. Go to Sample Data 
2. Create a New GUI question on the Products table
3.  Summarize Count by Category
4. Hit Visualize
5. Change the Visualization to a Row chart

### Expected behavior

Rows should appear

### Information about your Metabase installation

```JSON
- On Chrome, Windows
- I'm seeing this on the build from  2023-06-30
```

### Severity

Upgrade blocker.  Previously working questions stopped working

**Comment by darksciencebase** [comment]
![image](https://github.com/metabase/metabase/assets/125455699/3034ded7-7dec-438d-826c-3a25809f44fd)

![image](https://github.com/metabase/metabase/assets/125455699/2be468de-462d-43f1-8280-e318238a7e99)

**Comment by iethree** [comment]
culprit is #31722, looking into a fix

**Comment by cbalusek** [comment]
I edited the bug any aggregation will break row charts, not just custom columns
