### ISSUE TITLE
Query builder for timeseries DB

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3207]
For timeseries databases, most queries contain both a time filter and a grouping by time. 
In most analytics tools selecting the granularity of the grouping and the date range is done in the same place. For example it should be easy to select "daily data for last month". Also a good default granularity value can be selected based on date range eg 30 days -> daily, 1 day-> hourly...

Perhaps it would make sense to have a special query builder for timeseries DB, to reduce number of clicks required to make a new query.

**Comment by salsakran** [comment]
We've definitely had requests for other granularities, and it definitely makes sense to have the QB be smarted when it's working on a time series.

**Comment by brunobergher** [comment]
Handled organically over time.
