### ISSUE TITLE
MySQL versions older than 4.1 (pre-2004) not supported

### ISSUE THREAD

**Issue by danje** [metabase/metabase#3208]
*  I am using the **Chrome** browser.
*  My computer's OS is **Windows 7 Professional SP1**.
*  I'm running Metabase **locally from the JAR** and it is using the **H2 (default)** database.
*  My data is in a **MySQL** database.
*  My Metabase version is **0.19.3**.

I have data in a MySQL database running on version 4.0.16 but I'm unable to successfully add the database to Metabase. When trying to add the database the logs show the following error for each table:

    08-16 15:22:48 ←[1mERROR sync-database.introspect←[0m :: ←[31mUnexpected error introspecting table schema: userdb_rating←[0m #error {
     :cause Column 'Collation' not found.
     :via
     [{:type java.sql.SQLException
       :message Column 'Collation' not found.
       :at [com.mysql.jdbc.SQLError createSQLException SQLError.java 963]}]
     :trace
     [[com.mysql.jdbc.SQLError createSQLException SQLError.java 963]
      [com.mysql.jdbc.SQLError createSQLException SQLError.java 896]
      [com.mysql.jdbc.SQLError createSQLException SQLError.java 885]
      [com.mysql.jdbc.SQLError createSQLException SQLError.java 860]
      [com.mysql.jdbc.ResultSetImpl findColumn ResultSetImpl.java 1077]
      [com.mysql.jdbc.ResultSetImpl getString ResultSetImpl.java 5202]
      [com.mysql.jdbc.DatabaseMetaData$2 forEach DatabaseMetaData.java 2466]
      [com.mysql.jdbc.DatabaseMetaData$2 forEach DatabaseMetaData.java 2341]
      [com.mysql.jdbc.IterateBlock doForAll IterateBlock.java 50]
      [com.mysql.jdbc.DatabaseMetaData getColumns DatabaseMetaData.java 2339]
      [com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData getColumns NewProxyDatabaseMetaData.java 3968]
      [metabase.driver.generic_sql$describe_table_fields invokeStatic generic_sql.clj 334]
      [metabase.driver.generic_sql$describe_table_fields invoke generic_sql.clj 332]
      [metabase.driver.generic_sql$describe_table invokeStatic generic_sql.clj 364]
      [metabase.driver.generic_sql$describe_table invoke generic_sql.clj 362]
      [metabase.driver$fn__18257$G__18169__18266 invoke driver.clj 45]
      [metabase.sync_database.introspect$introspect_tables_BANG_$fn__21817 invoke introspect.clj 151]
      [metabase.sync_database.introspect$introspect_tables_BANG_ invokeStatic introspect.clj 146]
      [metabase.sync_database.introspect$introspect_tables_BANG_ invoke introspect.clj 140]
      [metabase.sync_database.introspect$introspect_database_and_update_raw_tables_BANG_ invokeStatic introspect.clj 205]
      [metabase.sync_database.introspect$introspect_database_and_update_raw_tables_BANG_ invoke introspect.clj 196]
      [metabase.sync_database$sync_database_with_tracking_BANG_$fn__22089 invoke sync_database.clj 77]
      [metabase.sync_database$sync_database_with_tracking_BANG_ invokeStatic sync_database.clj 74]
      [metabase.sync_database$sync_database_with_tracking_BANG_ invoke sync_database.clj 68]
      [clojure.core$partial$fn__4763 invoke core.clj 2528]
      [metabase.driver$fn__18414 invokeStatic driver.clj 242]
      [metabase.driver$fn__18414 invoke driver.clj 242]
      [metabase.driver$fn__18376$G__18161__18385 invoke driver.clj 45]
      [metabase.sync_database$sync_database_BANG_ invokeStatic sync_database.clj 43]
      [metabase.sync_database$sync_database_BANG_ doInvoke sync_database.clj 24]
      [clojure.lang.RestFn invoke RestFn.java 410]
      [metabase.events.sync_database$process_sync_database_event$fn__33820 invoke sync_database.clj 32]
      [clojure.core$binding_conveyor_fn$fn__4676 invoke core.clj 1938]
      [clojure.lang.AFn call AFn.java 18]
      [java.util.concurrent.FutureTask run nil -1]
      [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
      [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
      [java.lang.Thread run nil -1]]}

The database is part of a commercial product so cannot be upgraded or modified.  I don't have any other MySQL 4.0 databases to test against so haven't been able to verify if this is a "problem" with the database schema or a compatibility issue with version 4.0.

**Comment by camsaul** [comment]
It looks like [the official MySQL JDBC driver (which we use under the hood) only supports version 4.1 or newer](http://dev.mysql.com/doc/connector-j/5.1/en/connector-j-versions.html). This is true even of older versions of the JDBC driver. MySQL 4.1 came out almost 12 years ago, and 4.0.x stopped being officially supported almost 9 years ago. 

That being the case, I honestly don't think we'll be able to devote time writing a custom JDBC driver for long-deprecated versions of MySQL. You might be able to dump the database and load it into a newer version of MySQL, or bring the issue up with the vendors of the commercial product.

**Comment by danje** [comment]
Thanks for your quick response. I suspected it may have been something along those lines. :smile:
