### ISSUE TITLE
"Column not found" error after editing metadata of a model with custom column

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#32085]
Possibly related to #29943 & #32087
Originally reported as scenario 3 in https://github.com/metabase/metabase/issues/29943#issuecomment-1618237890

----

**Describe the bug**

![image](https://github.com/metabase/metabase/assets/6830683/706c2acd-80ca-4de8-bf9f-2a7151ca5312)

https://github.com/metabase/metabase/assets/6830683/cbd90cc9-0ec5-4e6b-b727-fdd9a0fc4fdb

**To Reproduce**

1. Create a question to query all data from Accounts table in Sample Database.
2. **Do not** visualize it.
3. Save it.
4. Turn the question into a model.
5. In the notebook editor add custom column called `Seating type` with `CASE([Seats] = 1, "Single", [Seats] = 2, "Double", "Other")`
7. Save as a new question (is this expected to save this as a new question? see scenario 3)
8. Turn the question into a model.
9. Edit metadata
10. Move new column in between "Trial Converted" and "Active Subscription"
11. Click the play icon to reload results
12. Error - [screenshot](https://github.com/metabase/metabase/assets/6830683/9251ac5b-641f-4ba2-9d27-6e5531028b5a)

```
Column "source.Seating type" not found; SQL statement:
SELECT "source"."ID" AS "ID", "source"."EMAIL" AS "EMAIL", "source"."FIRST_NAME" AS "FIRST_NAME", "source"."LAST_NAME" AS "LAST_NAME", "source"."PLAN" AS "PLAN", "source"."SOURCE" AS "SOURCE", "source"."SEATS" AS "SEATS", "source"."CREATED_AT" AS "CREATED_AT", "source"."TRIAL_ENDS_AT" AS "TRIAL_ENDS_AT", "source"."CANCELED_AT" AS "CANCELED_AT", "source"."TRIAL_CONVERTED" AS "TRIAL_CONVERTED", "source"."Seating type" AS "Seating type", "source"."ACTIVE_SUBSCRIPTION" AS "ACTIVE_SUBSCRIPTION", "source"."LEGACY_PLAN" AS "LEGACY_PLAN", "source"."LATITUDE" AS "LATITUDE", "source"."LONGITUDE" AS "LONGITUDE", "source"."COUNTRY" AS "COUNTRY" FROM (SELECT "source"."ID" AS "ID", "source"."EMAIL" AS "EMAIL", "source"."FIRST_NAME" AS "FIRST_NAME", "source"."LAST_NAME" AS "LAST_NAME", "source"."PLAN" AS "PLAN", "source"."SOURCE" AS "SOURCE", "source"."SEATS" AS "SEATS", "source"."CREATED_AT" AS "CREATED_AT", "source"."TRIAL_ENDS_AT" AS "TRIAL_ENDS_AT", "source"."CANCELED_AT" AS "CANCELED_AT", "source"."TRIAL_CONVERTED" AS "TRIAL_CONVERTED", "source"."ACTIVE_SUBSCRIPTION" AS "ACTIVE_SUBSCRIPTION", "source"."LEGACY_PLAN" AS "LEGACY_PLAN", "source"."LATITUDE" AS "LATITUDE", "source"."LONGITUDE" AS "LONGITUDE", "source"."COUNTRY" AS "COUNTRY" FROM (SELECT "PUBLIC"."ACCOUNTS"."ID" AS "ID", "PUBLIC"."ACCOUNTS"."EMAIL" AS "EMAIL", "PUBLIC"."ACCOUNTS"."FIRST_NAME" AS "FIRST_NAME", "PUBLIC"."ACCOUNTS"."LAST_NAME" AS "LAST_NAME", "PUBLIC"."ACCOUNTS"."PLAN" AS "PLAN", "PUBLIC"."ACCOUNTS"."SOURCE" AS "SOURCE", "PUBLIC"."ACCOUNTS"."SEATS" AS "SEATS", "PUBLIC"."ACCOUNTS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ACCOUNTS"."TRIAL_ENDS_AT" AS "TRIAL_ENDS_AT", "PUBLIC"."ACCOUNTS"."CANCELED_AT" AS "CANCELED_AT", "PUBLIC"."ACCOUNTS"."TRIAL_CONVERTED" AS "TRIAL_CONVERTED", "PUBLIC"."ACCOUNTS"."ACTIVE_SUBSCRIPTION" AS "ACTIVE_SUBSCRIPTION", "PUBLIC"."ACCOUNTS"."LEGACY_PLAN" AS "LEGACY_PLAN", "PUBLIC"."ACCOUNTS"."LATITUDE" AS "LATITUDE", "PUBLIC"."ACCOUNTS"."LONGITUDE" AS "LONGITUDE", "PUBLIC"."ACCOUNTS"."COUNTRY" AS "COUNTRY" FROM "PUBLIC"."ACCOUNTS") AS "source") AS "source" LIMIT 2000 [42122-214]
```
</details>

**Expected behavior**

No error

**Comment by ignacio-mb** [comment]
@kamilmielnik is this still happening? I couldn't reproduce either in master or 48.4. I think it was fixed in 48

**Comment by kamilmielnik** [comment]
@ignacio-mb I cannot reproduce it today on `master` (c18aecb6ca).
Looks like it's fixed. Closing.
