### ISSUE TITLE
"Cannot determine the source table" error after editing metadata of a model with custom column

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#32087]
Possibly related to #29943 & #32085
Originally reported as scenario 2 in https://github.com/metabase/metabase/issues/29943#issuecomment-1618237890

----

**Describe the bug**

![image](https://github.com/metabase/metabase/assets/6830683/4b186ae3-6cf3-4e8e-9ec5-b0c142f128b8)

https://github.com/metabase/metabase/assets/6830683/3178a8f4-777a-4e06-85f6-2170f71e5396

**To Reproduce**

1. Create a question to query all data from Accounts table in Sample Database.
2. Visualize it.
3. Save it.
4. Turn the question into a model.
5. Edit query definition
6. Add custom column called `Seating type` with `CASE([Seats] = 1, "Single", [Seats] = 2, "Double", "Other")`
7. Save model
8. Edit metadata
9. Move new column in between "Trial Converted" and "Active Subscription"
10. Click the play icon to reload results
11. Error - [screenshot](https://github.com/metabase/metabase/assets/6830683/2b90b851-37a6-41ea-9009-2c4e2b6bb3b6)
```
Cannot determine the source table or query for Field clause [:field "seating type" {:base-type :type/Text}]
```

**Expected behavior**

No error

**Comment by uladzimirdev** [comment]
It's not an issue anymore in v48 and later, works in master as well, but I was able to reproduce the issue in v47.13

**Comment by uladzimirdev** [comment]
There is a test, which covers this behaviour - `e2e/test/scenarios/models/reproductions/29943-custom-column-in-metadata.cy.spec.ts`
