### ISSUE TITLE
Underlying records drill-thru is confused by negative values

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#32108]
### Describe the bug

If you have an aggregation with negative values, the label for the "See these TableNames" will be mis-pluralized.

![bad-name-for-negative](https://github.com/metabase/metabase/assets/157812/ad8ea0aa-d2ff-4ca7-9c0e-a442283be7c7)

### To Reproduce

1. Create a new GUI question
2. Sample Database > People
3. Visualize it
4. Click the Longitude column heading
5. Choose the `Sum` drill-thru
6. Open the Summarize sidebar, group by State.
7. Click a state - "See these Person"

### Expected behavior

The label should read "See these People", with the proper plural name of the table.

### Information about your Metabase installation

```JSON
Running locally
```

### Severity

Trivial

**Comment by bshepherdson** [comment]
Should try to fix this while working on #31004

**Comment by kamilmielnik** [comment]
Reproducible in 0.46.4.
Fixed in `master` ([d35c779](https://github.com/metabase/metabase/commit/d35c779976ae6bd79369e9cc6bec8540908f37d2)) - [screenshot](https://github.com/metabase/metabase/assets/6830683/6609e6fb-6176-414b-b568-c211afc80dcf).
Marking as fixed in the next version (48).
Closing.
