### ISSUE TITLE
Make SSO providers modular

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3210]
We shipped #1008 which provided a Google SSO option.

As per our conversations on the PR, it's a transitional first step towards modular SSO options. As a prelude to supporting LDAP #1488 or other options, we should clean up the code in question to make writing an SSO provider an easy thing for outsiders to do.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by tlrobinson** [comment]
Related issues:

LDAP: #1488 (~38 👍  / +1s)
OpenID: #3101 (~2 👍  / +1s)
SAML: #4308 (~3 👍  / +1s)
2 factor authentication: #3729 (~2 👍  / +1s)

**Comment by camsaul** [comment]
@tlrobinson Adding 2FA directly in Metabase itself isn't really related to adding more SSO providers.

If the SSO provider does MFA (e.g. like Google Auth can do) it's out of our hands. #3729 is about adding MFA directly to Metabase, e.g. for people who log in via email/password

**Comment by moumny** [comment]
With OpenID/SAML you can have an AD as identity provider, which is what i think all +1 in the LDAP story want. (though direct ldap authentication is maybe easier to implement)

**Comment by timwilliate** [comment]
Hi team. Really like your product thus far. I was wondering if you can provide any idea about when SSO support (as hinted at in this issue) will be worked into Metabase?

**Comment by FallenChromium** [comment]
Seems like @camsaul just introduced awesome possibility for this issue by bringing up #9087. That should fit good for upcoming 1.0 too, as it will get SAML and JWT.

**Comment by gil0109** [comment]
Has anyone got Keycloak to work with Metabase?  Or is that only available if we have OAuth2 support?

**Comment by samsja** [comment]
> Has anyone got Keycloak to work with Metabase? Or is that only available if we have OAuth2 support?

Did you succed to get keycloak work with Metabase ?

**Comment by gil0109** [comment]
No I haven’t.

**Comment by salsakran** [comment]
closing this as we have modular drivers now, as well as a variety of SSO options

**Comment by meyerovb** [comment]
@salsakran Starter only has Google SSO or janky LDAP MFA like https://duo.com/docs/ldap, what are these 'modular drivers' u speak of, and are they only available in Pro?

**Comment by thomasjetzinger** [comment]
Any news here? Do we really have to pay 500$/month just for 2FA???

**Comment by meyerovb** [comment]
@thomasjetzinger I just finished integrating azure ad through google sso so I could do this without paying for it. You set up a single google workspace admin account, request a higher limit of free google cloud identity accounts to cover everyone in your organization, then find setup instructions by googling google sso azure ad. My ops guys still can’t believe that it worked.
