### ISSUE TITLE
Not getting delete response back or any response status like 200 even though the api is successfully deleing the card. please add this feature.

### ISSUE THREAD

**Issue by Rahmat711** [metabase/metabase#32129]
### Describe the bug

No response after using Delete metabase API to delete the card even the the API is deleting the card with out any return response. Also in metabase documentation it has mentioned it will archieve the card not delete but for me card is getting deleted

### To Reproduce

import requests

url = 'http://localhost:3000/api/card/83'
session_id = 'sesseion-key'

# Set headers
headers = {
    'Content-Type': 'application/json',
    'X-Metabase-Session': session_id
}
response = requests.delete(url, headers=headers)

if response.status_code == 200:
    print("Card deleted successfully!", response.text)
else:
    print("Card deletion failed. Error:", response.text)

### Expected behavior

Reponse should contain status_code and other log message

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.10.124-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-14",
      "tag": "v0.46.5",
      "branch": "release-x.46.x",
      "hash": "272e3e6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking your usage

**Comment by paoliniluis** [comment]
the error is on your code, please review it
