### ISSUE TITLE
Boolean fields are not available in list of fields to sort by

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#32156]
### Describe the bug

In the Notebook Editor, when trying to sort, the list of fields doesn't include boolean fields. This is necessary to show active accounts first using an is_active boolean field. 

I can workaround it by clicking on the boolean column when browsing the table and then selecting the sort order, but that isn't always possible if my question isn't showing the fields / when using a visualization. 

### To Reproduce

1. Create a new question using a table/model with a boolean field
2. Try to sort and the boolean field isn't listed

### Expected behavior

Boolean field should be listed 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "postgres",
      "redshift",
      "mysql",
      "bigquery-cloud-sdk",
      "mongo",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-05",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "f877f0e"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

It's inconvenient

**Comment by cdeweyx** [comment]
Question for engineering: Does this interact with MLv2?

**Comment by uladzimirdev** [comment]
@cdeweyx yes, we introduced MLv2 there https://github.com/metabase/metabase/pull/29842

@kulyk do you think it's a bug?

**Comment by kulyk** [comment]
AFAIK boolean fields are not considered sortable in MLv2 right now. I started an [internal thread](https://metaboat.slack.com/archives/C04CYTEL9N2/p1698054387531879?thread_ts=1696873812.471329&cid=C04CYTEL9N2) to figure it out.

Potentially related issues: #34461 #34286
