### ISSUE TITLE
[MLv2] allow access to column metadata from a filter

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#32159]
[slack discussion](https://metaboat.slack.com/archives/C04CYTEL9N2/p1688402562625939)

**Comment by camsaul** [comment]
> Can be done by calling `Lib.externalOp(filterClause)`

I'm not 100% sure this is strictly true, if you use `external-op` it returns the raw `:field` reference MBQL clause and I don't think we currently expose a way to get ColumnMetadata from a `:field` clause. But I think most places where you think you need the ColumnMetadata we can just update to take either a `:field` clause or ColumnMetadata
