### ISSUE TITLE
Role Level Security (impersonation) for Presto

### ISSUE THREAD

**Issue by Aka-shi** [metabase/metabase#32169]
**Is your feature request related to a problem? Please describe.**
We want to use Metabase with Trino. Our access control policies and cluster resource control policies are defined on user and connection attributes such as user.email or username. Currently, metabase only supports defining a static user while creating a database connection, we want the database connection to leverage the logged in user's attributes such as user.email or user.name(configurable) to pass it down to the database. 

Does this EPIC #29491 also cover this scenario?

**Comment by luizarakaki** [comment]
The epic builds the foundations for this, but right now it is available for Postgres and Snowflake only.

The Trino driver is developed by the Starburst team, so it depends on their prioritization.

I suggest you open this issue in their repo https://github.com/starburstdata/metabase-driver
We will also contact them about this new feature.

**Comment by Aka-shi** [comment]
@luizarakaki With the epic, is it possible to use email attribute of the logged in user as role?

**Comment by paoliniluis** [comment]
@Aka-shi yes

**Comment by likeshumidity** [comment]
related to https://github.com/metabase/metabase/issues/9845

**Comment by paoliniluis** [comment]
dupe of https://github.com/metabase/metabase/issues/9845
