### ISSUE TITLE
[MLv2] Enable access to field IDs from column metadata

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#32160]
The FE needs a field ID to fetch its values (`/api/field/:fieldId/values`) and present them in filtering UI

[Related Slack discussion](https://metaboat.slack.com/archives/C04CYTEL9N2/p1688402562625939)

**Comment by camsaul** [comment]
I think for now we should just return Field ID, because accessing FieldValues is outside of the scope of MLv2 for the time being.

**Comment by camsaul** [comment]
we should just add a function to get the Field ID since column metadata is opaque in JS land
