### ISSUE TITLE
Update "Contact" copy on model detail page

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#32161]
## Context
We use "Contact" on the model detail page today, but *I think* it just refers to the creator of the model. This language becomes misleading in certain situations, namely when someone creates something valuable and then later leaves the company.

## Expected Behavior
Let's change this copy instead to "Created by" to actually match the logic here.

## Example
![Image](https://github.com/metabase/metabase/assets/16455495/9027ddf5-ed38-42bc-9eb8-276206fdb8fd)

**Comment by cdeweyx** [comment]
@mazameli any preference on the language we use here? 

I suggested "Created by" but "Author" works the same. Looking to ensure we're matching design patterns elsewhere across the product.

**Comment by mazameli** [comment]
@cdeweyx I went with "Created by" since that's what we use elsewhere, and I have a PR for this: #32162
