### ISSUE TITLE
Allow to trigger database syncs using a CRON expression

### ISSUE THREAD

**Issue by moreaupascal56** [metabase/metabase#32176]
Hello all :) 

**Is your feature request related to a problem? Please describe.**

Working with Snowflake syncs can be relatively costly on warehouse credits, I always wondered why there is no CRON expression option on the scan scheduling option, for example in order to not run scans during the night. 

**Describe the solution you'd like**
An option to use a CRON expression here: 
![Capture d’écran 2023-07-06 à 14 28 46](https://github.com/metabase/metabase/assets/50910271/8f3105fa-e202-4981-bb9e-d0e81650e435)

**How important is this feature to you?**
This would be cool but to be honest I am not sure I have understood everything about the metabase syncs so let me know if that does not make sense.

**Comment by paoliniluis** [comment]
please check https://github.com/metabase/metabase/issues/10398
