### ISSUE TITLE
X-axis label doesn't auto-populate as Y-axis label does in one series charts

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#32179]
### Describe the bug

When first editing a two-series chart settings, you can see that the Label for X-axis doesn't auto-populate like the Y-axis one (minor detail). See screenshot above
![Screenshot 2023-07-06 at 11 02 29 AM](https://github.com/metabase/metabase/assets/132273646/b9dd7043-1688-4d6d-a42a-1ce87ddc58a7)

### To Reproduce

1. Create a question and then a chart with two series
2. See Label field for X-axis in chart settings

### Expected behavior

The field should auto populate with whatever the x-axis field series is (in this case, "Created At")

### Information about your Metabase installation

```JSON
- master
```

### Severity

Not severe

**Comment by ignacio-mb** [comment]
@luizarakaki 

sorry, more detailed steps:

1. on `master`, GUI Query Invoices table from  Sample database, Sum of Payment and Group By Recieved At: month.
2. Run query > viz settings

![Screenshot 2023-07-19 at 10 34 59 AM](https://github.com/metabase/metabase/assets/132273646/24a138de-b798-4686-a72f-a3ed5a7e8d78)

Shouldn't the X-axis Label field auto-populate with "Date received" as the Y-Axis label does with "Sum of Payment"?

Another way to reproduce:
1. GUI Query Accounts table from Sample database, Sum of Seats, and Group By Plan.
2. Run query > viz settings > See X-axis label field
![Screenshot 2023-07-19 at 10 43 52 AM](https://github.com/metabase/metabase/assets/132273646/0974a46b-2d11-440e-9dae-2ee57a14e30e)

**Comment by luizarakaki** [comment]
Ok, makes sense.

I think I got confused by the "two series" in the title. Isn't it a one series chart?

**Comment by ignacio-mb** [comment]
Mb, I'll edit it
