### ISSUE TITLE
[Bug] Error occurs when performing "Join data" with fields containing "." character

### ISSUE THREAD

**Issue by NuhYlmz** [metabase/metabase#32182]
### Describe the bug

Hello,

I am using Metabase along with my MongoDB database, and I encountered an error when trying to use the "Join data" feature in creating questions. The error occurs when I attempt to join data using fields that contain the "." (dot) character. The reason for the error is that the "." character is present within an object to represent a nested value.

For example, when I try to join the "payload.sessionId" field from one collection with the "_id" field from the "sessions" collection, I receive the following error:

`Command failed with error 16868 (Location16868): ''let_payload.userId_125589' contains an invalid character for a variable name: '.'' on server ***.mongo.ondigitalocean.com:**** The full response is {"operationTime": {"$timestamp": {"t": 1688656452, "i": 6}}, "ok": 0.0, "errmsg": "'let_payload.userId_125589' contains an invalid character for a variable name: '.'", "code": 16868, "codeName": "Location16868"...`

I kindly request your assistance in resolving this issue. Could you please investigate this error and provide guidance on the necessary fixes?

Thank you.

### To Reproduce

1. Open Metabase.
2. Connect Metabase to a MongoDB database.
3. Create a new question by clicking on the "Questions" tab.
4. Select the "Join data" option.
5. Choose a collection that contains fields with the "." (dot) character, such as "payload.sessionId".
6. Select another collection to join with, which has a field that doesn't contain the "." character, such as "sessions" and "_id".
7. Configure the join conditions by selecting the appropriate fields.
8. Click on "Preview" or "Run" to execute the query.
9. Observe the error message: "Command failed with error 16868 (Location16868): '...'".

### Logs

` ["com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)"
  "com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:302)"
  "com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:258)"
  "com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)"
  "com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450)"
  "com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)"
  "com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:226)"
  "com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)"
  "com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)"
  "com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)"
  "com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)"
  "com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)"
  "com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)"
  "com.mongodb.operation.CommandOperationHelper$5.call(CommandOperationHelper.java:206)"
  "com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)"
  "com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:203)"
  "com.mongodb.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:200)"
  "com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:333)"
  "com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:42)"
  "com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:199)"
  "com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:180)"
  "com.mongodb.DBCollection.aggregate(DBCollection.java:1530)"
  "com.mongodb.DBCollection.aggregate(DBCollection.java:1488)"
  "com.mongodb.DBCollection.aggregate(DBCollection.java:1473)"
  "--> driver.mongo.execute$aggregate.invokeStatic(execute.clj:142)"
  "driver.mongo.execute$aggregate.invoke(execute.clj:136)"
  "driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:179)"
  "driver.mongo.execute$execute_reducible_query.invoke(execute.clj:173)"
  "driver.mongo$fn__120778$f__119596__auto____120779.invoke(mongo.clj:313)"
  "driver.mongo.util$do_with_mongo_connection$fn__119584.invoke(util.clj:230)"
  "util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:141)"
  "util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:130)"
  "driver.mongo.util$do_with_mongo_connection.invokeStatic(util.clj:224)"
  "driver.mongo.util$do_with_mongo_connection.invoke(util.clj:219)"
  "driver.mongo$fn__120778.invokeStatic(mongo.clj:312)"
  "driver.mongo$fn__120778.invoke(mongo.clj:310)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:12)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___69242.invoke(cache.clj:224)"
  "query_processor.middleware.permissions$check_query_permissions$fn__64714.invoke(permissions.clj:126)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__68133.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__70761$combined_post_process__70766$combined_post_process_STAR___70767.invoke(query_processor.clj:243)"
  "query_processor$fn__70761$combined_pre_process__70762$combined_pre_process_STAR___70763.invoke(query_processor.clj:240)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69153$fn__69158.invoke(resolve_database_and_driver.clj:36)"
  "driver$do_with_driver.invokeStatic(driver.clj:90)"
  "driver$do_with_driver.invoke(driver.clj:86)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__69153.invoke(resolve_database_and_driver.clj:35)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__65024.invoke(fetch_source_query.clj:316)"
  "query_processor.middleware.store$initialize_store$fn__65202$fn__65203.invoke(store.clj:12)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:47)"
  "query_processor.store$do_with_store.invoke(store.clj:41)"
  "query_processor.middleware.store$initialize_store$fn__65202.invoke(store.clj:11)"
  "query_processor.middleware.normalize_query$normalize$fn__69442.invoke(normalize_query.clj:25)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__66380.invoke(constraints.clj:54)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__69378.invoke(process_userland_query.clj:151)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__69755.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___59523$thunk__59525.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___59523.invoke(reducible.clj:109)"
  "query_processor.reducible$async_qp$qp_STAR___59523.invoke(reducible.clj:94)"
  "query_processor.reducible$sync_qp$qp_STAR___59535.doInvoke(reducible.clj:129)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:366)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:362)"
  "query_processor$fn__70810$process_query_and_save_execution_BANG___70819$fn__70822.invoke(query_processor.clj:377)"
  "query_processor$fn__70810$process_query_and_save_execution_BANG___70819.invoke(query_processor.clj:370)"
  "query_processor$fn__70855$process_query_and_save_with_max_results_constraints_BANG___70864$fn__70867.invoke(query_processor.clj:389)"
  "query_processor$fn__70855$process_query_and_save_with_max_results_constraints_BANG___70864.invoke(query_processor.clj:382)"
  "api.dataset$run_query_async$fn__86650.invoke(dataset.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__54386$fn__54387.invoke(streaming.clj:166)"
  "query_processor.streaming$streaming_response_STAR_$fn__54386.invoke(streaming.clj:165)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__36975.invoke(streaming_response.clj:88)"],`

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "tr-TR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7-post-Ubuntu-0ubuntu120.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7-post-Ubuntu-0ubuntu120.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-150-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-29",
      "tag": "v0.46.6",
      "branch": "release-x.46.x",
      "hash": "****"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2

**Comment by Atsocs** [comment]
I'm having the same problem :/

**Comment by stygmate** [comment]
exact same problem for me.
maybe just a little modification to add here to fix: https://github.com/metabase/metabase/blob/7d8412017ed3db5b80688b8908f7b85a6c8c24cb/modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj#L912

**Comment by Sergeant61** [comment]
same problem for me

**Comment by stygmate** [comment]
I don't know the clj syntax but seems it can be resolved with a simple `(str/replace "." "_")`
one join out of two don't work because of that bug...
anyone to do a pull requests ?
