### ISSUE TITLE
Custom column name is not respected in column filters UI

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#32181]
### Describe the bug

When applying a filter to a column with a custom name, the filter brings the physical column name and not the name user selected for visualization purpose.

### To Reproduce

1. Create a new question.
2. Visualize it like a table
3. Click on column title
4. Click on gear icon
5. Type a custom column name
6. Click on column title again
7. Click on "Filter by this column"
8. Check that custom column name is not displayed in search field input

Custom column name is also not respected for a search results message like this:
<img width="1096" alt="Screenshot 2023-07-06 at 18 33 50" src="https://github.com/metabase/metabase/assets/7983744/2b37f604-1bf7-4c05-819b-a4c204f19e97">

https://github.com/metabase/metabase/assets/7983744/9b1bcb71-f9d1-4748-a37f-9e4712ea24a4

### Expected behavior

Custom column name should be displayed in filter widget messages and placeholders

### Information about your Metabase installation

```JSON
Happens on our stats instance
```

### Severity

P3

**Comment by kamilmielnik** [comment]
Workaround: it will work as expected if column name is set via "Admin settings" -> "Table Metadata".

**Comment by ranquild** [comment]
This was intended to work this way. To change column metadata please either use Table Metadata or create a model.
