### ISSUE TITLE
Charts in Audit should not show "Edit question" action

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#32211]
### Describe the bug

(Note: I ran into this a week or so ago, before filing https://github.com/metabase/metabase/issues/32210)

You can't edit the charts in the Audit section, so this action should not be listed in this menu in this context. (Incidentally, the ability to download the results seems useful, but I'm guessing its inclusion is accidental.)

<img width="1057" alt="image" src="https://github.com/metabase/metabase/assets/2223916/c24c1b8d-92a0-48c8-b978-6f0f36abc993">

### To Reproduce

1. Go to Audit in the Admin Panel
2. Hover over one of the charts and click the "…" menu
3. See that the "Edit question" action is incorrectly present

### Expected behavior

You can't edit the charts in the Audit section, so the "Edit question" action should not be listed in the "…" menu in this context.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Mac OS X",
    "os.version": "11.5",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-11-18",
      "src_hash": "09f4ec50c4b6096192e18c140068ce8a7e67434d",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "maz-make-saving-a-question-less-fear-inducing",
      "hash": "f694966"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3 IMO

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/31843
