### ISSUE TITLE
Metric fields are missing, when creating question from model

### ISSUE THREAD

**Issue by MartijnDB** [metabase/metabase#32217]
### Describe the bug

When creating a new question based on model there are no columns to use as metrics. Only columns to summarize by.

Note: This bug does not happen all time. And this bug also happens in other cases ( like duplicate model).

I want 'Cost' as a metric:
![image](https://github.com/metabase/metabase/assets/47593731/533d7423-47f2-4641-b9c2-7a4e783813cf)

There are 0 fields available as metric:
![image](https://github.com/metabase/metabase/assets/47593731/840adb75-76dc-4865-8eaa-ad1b78f1af85)

Which is strange. Because they are listed as summarizing column:
![image](https://github.com/metabase/metabase/assets/47593731/653c7bdd-ff86-40e3-8cc5-81355776943f)

### To Reproduce

1. New Question
2. Based on model
3. Press Summarize
4. Choose Metrics
5. No metrics available

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.242-156.349.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-14",
      "tag": "v1.46.5",
      "branch": "release-x.46.x",
      "hash": "272e3e6"
    },
    "settings": {
      "report-timezone": "Europe/Amsterdam"
    }
  }
}
```

### Severity

8

**Comment by paoliniluis** [comment]
Hi, I'm not able to replicate, can you check refreshing the page? how many rows does the model/query have?

**Comment by MartijnDB** [comment]
Sometimes refreshing works indeed. This issue happens when I use Metabase a lot, creating a lot of models / dashboards. 
Right now it's working. I'll post back when it happens again.

There are not so many rows, maybe a 100... Dont think thats the cause.
