### ISSUE TITLE
Create special card type: label

### ISSUE THREAD

**Issue by julzhk** [metabase/metabase#3221]
To describe and annotate dashboards it would be useful to create a card without data, but just a heading label or a description paragraph. This would break up and allow several charts to effectively share a common heading.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by alee792** [comment]
If this were to be implemented, making it a fully featured markup card would be fantastic.

**Comment by EvaSchreyer** [comment]
Hi, I was wondering if there are any developments of implementing a free text field in metabase? Would help a lot in describing a dashboard (of course you can do it in the description field but when you then create a pdf out of it - and yes, a lot of our customers still want to have it "printed") the description is not visible anymore. Would be a great feature. Thanks!

**Comment by alee792** [comment]
You can create a new SQL question and `SELECT "YOUR TEXT HERE"` as a janky workaround.

**Comment by kstan79** [comment]
+1

**Comment by jornh** [comment]
Implemented by #6436

**Comment by bpinaya** [comment]
Any idea how to add this to the dashboard? Can't seem to find the Card Type

**Comment by jornh** [comment]
@bpinaya see first screen in the design spec mock-up in https://github.com/metabase/metabase/issues/6360

Which version are you trying this on? It’s not in any official release yet. So you either have to build the `master` branch yourself or test it out using the `metabase/metabase-head` Docker image.

**Comment by bpinaya** [comment]
Thanks! I'll try it now, I think I was with an old version of the repo, having seen the changes I saw that the change was around 25 days ago, while I checked out the repo almost a month ago or so. Thanks for the help @jornh

**Comment by jornh** [comment]
I believe this issue can be closed now, right?
 ... Implemented by #6436

**Comment by tlrobinson** [comment]
Yes, thank you @jornh
