### ISSUE TITLE
can i send data to metbase and visualize it without giving access to metabase

### ISSUE THREAD

**Issue by asadroy77** [metabase/metabase#32222]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by paoliniluis** [comment]
we don't understand the issue, please use the forums

**Comment by asadroy77** [comment]
i want to integrate metabase with react single page app having no database , i want metabase to take data from my app and generate graphs for me . is this possible ?
