### ISSUE TITLE
Broken navigation in question data source picker 

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#32225]
**Describe the bug**
Related to #29760.

**To Reproduce**
Create a fresh Metabase instance.
1. Create 2 models and save them
2. Click `+ New` -> `Question`
3. Click `Models` option

Expected behavior: search input is visible
Actual result: search input is not visible

4. Click back button

Expected behavior: data source picker is shown.
Actual behavior: step does not change, search input appears.

**Screenshots/videos**

https://github.com/metabase/metabase/assets/6830683/d2f8ef69-bcaf-40b1-93d8-ec753cf780fd

**Severity**
Low

**Additional information**
`DataSelector` component logic is mixed with React lifecycle making it difficult to debug.

I'm not entirely sure what should happen if there is only 1 model in the database but in the code it looks like there is some special treatment for it (`onSchemaChange`).

**Comment by uladzimirdev** [comment]
With a new data picker modal it's not a problem anymore

**Comment by uladzimirdev** [comment]
works fine on master e74f0bbf41 and `0.50.6`
