### ISSUE TITLE
Search for questions containing a string in their SQL

### ISSUE THREAD

**Issue by mirceapasoi** [metabase/metabase#3222]
We have a lot of questions written in SQL and they span multiple dashboard.

I would love to be able to search for questions containing a specific string such that when something changes in the data (for example we rename a field) I can easily find which questions need updating.

**Comment by mirceapasoi** [comment]
This is still a big pain for us... We have a lot of questions in SQL and whenever something changes (table names, column names, etc.) i need to find all the queries that need updating and I can only do that manually now 😒

**Comment by tlrobinson** [comment]
This isn't a good long term solution, but a workaround is you can add Metabase's own application DB to Metabase (you'd only want to grant access to admins, for obvious reasons), then use Metabase to find questions in Metabase...

![screenshot 2017-05-25 15 37 30](https://cloud.githubusercontent.com/assets/18193/26473434/2ff63218-4160-11e7-9128-f8fe904b1815.png)

#yodawg

**Comment by flamber** [comment]
Closing in favor of #4227, because it has much more upvotes.

**Comment by lillikulak** [comment]
@tlrobinson @flamber version 0.47 recently eliminated the ability to search within SQL queries (as noted in [#4227](https://github.com/metabase/metabase/issues/4227)) -- how do I add the metabase application DB to metabase?
