### ISSUE TITLE
Cannot read properties of undefined (reading 'name') when adding an incomplete card

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32231]
### Describe the bug

Spin off of https://github.com/metabase/metabase/issues/32230

If you combine 2 cards:
1) a barchart (e.g. count of all people group by birth_date)
2) an incomplete bar char (e.g. sql question of select 1, saved as a bar chart)

you'll get a frontend error
![image](https://github.com/metabase/metabase/assets/1711649/0c221823-be3e-4b8d-af67-276dd34a374b)

### To Reproduce

Above

### Expected behavior

We should return what's the offending card?

### Information about your Metabase installation

```JSON
v47.x but guessing this comes from way before
```

### Severity

P3

**Comment by kamilmielnik** [comment]
See https://metaboat.slack.com/archives/C057T1QTB3L/p1691587662019079?thread_ts=1691585903.901969&cid=C057T1QTB3L for expected result
