### ISSUE TITLE
Data source picker sources not refreshed after archiving a question

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#32252]
**Describe the bug**
Related to #29760 & #32225.

**To Reproduce**

0. **Create a fresh Metabase instance.** - important as it has an Examples collection
1. archive Examples collection from `/collection/1-examples`
2. Click `+ New` -> `Question`.
3. Notice that `Saved Questions` appears in the list of options, but there is no `saved questions`

Expected behavior:  Saved Questions tab is not shown
Actual result: Save Questions tab is shown

It works correctly after refreshing the page.

**Screenshots**
<img width="1026" alt="image" src="https://github.com/metabase/metabase/assets/125459446/1076797d-742a-4ddd-b9cc-d48035281f74">

**Severity**
Low

**Comment by kamilmielnik** [comment]
Reproducible in `master` at bfceeebf16.

**Comment by uladzimirdev** [comment]
With a new data picker modal it's not a problem anymore

**Comment by kamilmielnik** [comment]
Reopening, it's still reproducible in 0.50.6.

1. Create a fresh Metabase instance
2. Click `+ New` -> `Question`
3. Notice that `Saved Questions` tab is present
4. Archive the "Examples" collection
5. Click `+ New` -> `Question`.

Expected behavior: Saved Questions tab is not shown
Actual result: Saved Questions tab is shown

@uladzimirdev please don't close issues without having repros for them.

**Comment by uladzimirdev** [comment]
@kamilmielnik well, steps to reproduce are different, let me reopen another one as well https://github.com/metabase/metabase/issues/32225
