### ISSUE TITLE
Dashboard editing state gets all kinds of weird

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3226]
As you can see in this screen recording, if I enter into dashboard editing mode, I can navigate to other dashboards and remain in editing mode, which seems super weird. I can also navigate to other parts of the app and then navigate back to a dashboard, and I remain in dashboard editing mode. This latter UX could be improved by showing a confirmation modal if a user tries to navigate away from a dashboard (or Question, or Getting Started Guide…) editing state, and toss their unsaved changes if they confirm they want to navigate away.

[dashboard-editing-weirdness.zip](https://github.com/metabase/metabase/files/423724/dashboard-editing-weirdness.zip)

**Comment by tlrobinson** [comment]
Yeah this is a general problem with our Redux code, it doesn't always reset all the state when you switch routes. Previously our frankenangulareactdux masked that issue since it created a new Redux store every time the route changed.
