### ISSUE TITLE
Don't allow CSV uploads when sandboxing is enabled

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#32263]
## Context
Sandboxed users shouldn't be able to upload CSVs. [More context here](https://metaboat.slack.com/archives/C04S696LRUM/p1688502771309619).

**Comment by tsmacdonald** [comment]
@cdeweyx unfortunately this will introduce new strings :sweat_smile:

**Comment by cdeweyx** [comment]
> @cdeweyx unfortunately this will introduce new strings 😅

Not sure I follow, how will this introduce new strings?

**Comment by tsmacdonald** [comment]
just the error message if a sandboxed user tries to do it.

It would be great if we had a FE check to disable the upload icon as well, but Ryan is OOO. I'll see if @npfitz or someone can help

```
(throw (Exception. (tru "Uploads are not permitted for sandboxed users.")))
```
