### ISSUE TITLE
Time shift on x-axis visualization bug

### ISSUE THREAD

**Issue by gladkikhtutu** [metabase/metabase#32286]
### Describe the bug

We have incorrect x-axis times on histogram.
![image](https://github.com/metabase/metabase/assets/88535677/f6ddd66c-b4f2-4022-a426-11fc74b4aaa0)

### To Reproduce

Query uses function formatDateTime (Clickhouse) 

```sql
select
formatDateTime(toStartOfFiveMinutes(cdate), '%F %T', 'Europe/Moscow') as dt,
uniqExact(id) as count
from db.table
group by dt
order by dt
```

Without this function visualization is OK but timezones are incorrect.

### Expected behavior

In the picture above dt time 11:25 should not be after 12:00 on axis

### Information about your Metabase installation

```JSON
Metabase version v0.42.4
```

### Severity

Blocking users in our company

### Additional context

I saw old the issue like mine https://github.com/metabase/metabase/issues/5246, but our version is newer

**Comment by paoliniluis** [comment]
can you please upgrade to the latest version?
