### ISSUE TITLE
Update copy for OSS and Enterprise images on Docker Hub

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#32327]
**Context**

* Internal document: https://www.notion.so/metabase/Update-Docker-Hub-image-copy-1186064d381e451c8cfe8d9f46f2e55d
* Slack conversation: https://metaboat.slack.com/archives/C010L1Z4F9S/p1688549929041299

# Copy

## OSS image

[Metabase](https://www.metabase.com/) is the easy, open-source way for everyone in your company to ask questions and learn from data.

This image contains the open-source version of Metabase. For the Metabase with all of the bells and whistles, check out [Metabase Enterprise](https://www.metabase.com/product/enterprise).

To get started, check out our docs:

- [Running Metabase on Docker](https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker).
- [Running Metabase in production](https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker#production-installation).

If you’d prefer Metabase host your instance and application database for you, check out [Metabase Cloud](https://www.metabase.com/pricing/)

## Enterprise image

[Metabase Enterprise Edition](https://www.metabase.com/product/enterprise) is a paid version of Metabase that includes [additional features](https://www.metabase.com/docs/latest/paid-features/overview) for managing large deployments or delivering interactive embedded analytics to your customers.

To activate these paid features, you'll need a [license key](https://www.metabase.com/docs/latest/paid-features/activating-the-enterprise-edition#how-to-activate-your-token-when-self-hosting).

To get started, check out our docs:

- [Pro or Enterprise quick start with Docker](https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker#pro-or-enterprise-quick-start).
- [Running Metabase in production](https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker#production-installation).

If you’d prefer Metabase host your instance and application database for you, check out [Metabase Cloud](https://www.metabase.com/pricing/).

**Comment by nemanjaglumac** [comment]
Done 🎉 

## OSS
https://hub.docker.com/repository/docker/metabase/metabase/general
![image](https://github.com/metabase/metabase/assets/31325167/eef27fdf-d724-4577-8684-872b2ad15b62)

## EE
https://hub.docker.com/repository/docker/metabase/metabase-enterprise/general
![image](https://github.com/metabase/metabase/assets/31325167/4d143984-cf9d-44f7-b66a-260ab714543c)

**Comment by albertoperdomo** [comment]
Let's update the descriptions too:

>Metabase Enterprise Edition docker image

>Metabase open-source docker image
