### ISSUE TITLE
Dashboard auto resize does not work properly after filtering

### ISSUE THREAD

**Issue by dempo93** [metabase/metabase#32328]
### Describe the bug

Scatter plot does not center results when a parameter filter is applied.
I have the following dashboard:
![image](https://github.com/metabase/metabase/assets/19284225/70f9cebc-c254-41c8-8f5d-d594301748ab)
Notice that when the parameter filter is unset, the axes size is nicely fit to min_x, max_x, min_y, max_y  of the scatter plot.

Now when I select any part, the axes min and max are wrongly chosen. The dots of the scatter plot tend to be on the far left of the canvas, sometime **outside** of it and thus **not visible** and clickable. The visualization is mainly white space
![image](https://github.com/metabase/metabase/assets/19284225/18179e8c-cb0e-470e-b46d-96eda02a3eb1)

### To Reproduce

1. Create a table similar to this one, fill with (random?) numbers
```

+----+----+----+----+----+----+----+
| ID | Ax | Ay | Bx | By | Cx | Cy |
+----+----+----+----+----+----+----+
|  1 |    |    |    |    |    |    |
|  2 |    |    |    |    |    |    |
|  3 |    |    |    |    |    |    |
|  4 |    |    |    |    |    |    |
|  5 |    |    |    |    |    |    |
+----+----+----+----+----+----+----+

```
2. Create scatter plots A (Ax, Ay), B  (Bx, By), C (Cx, Cy) with label ID
3. Create a dashboard containing scatter plot A. 
4. Click on add_series and add scatter plot B and C
5. Add a filter for ID
6. Save and set a specific ID in the filter

### Expected behavior

All datapoints should be visible. The filtered scatter plot should be centered.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.10.179-166.674.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-05-18",
      "tag": "v1.46.3",
      "branch": "release-x.46.x",
      "hash": "8d74de2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocker for some users (when data is not visible)

**Comment by EmmadUsmani** [comment]
Spent some time trying to repro but it seems like this issue is no longer occurring. The scatter plot always chooses the correct bounds after filtering. I'm assuming this was fixed when we migrated to echarts, so I'm closing the issue. @dempo93 Upgrading to v50 should fix the bug, but please feel free to re-open the issue if it still occurs after upgrading.
