### ISSUE TITLE
Custom homepage search errors when previously set within the same session

### ISSUE THREAD

**Issue by JesseSDevaney** [metabase/metabase#32337]
**Problem:** After setting a dashboard (from your personal collection) as a homepage and then trying to search for a dashboard (from your personal collection) to choose again, the whole setting component errors

![search-error](https://github.com/metabase/metabase/assets/22608765/c16428ab-ebd3-453f-9ff2-9e1ebeae62d2)

---
**Context:** The specific error is
![image](https://github.com/metabase/metabase/assets/22608765/e75ad9df-a86d-4bda-87b1-164c31565cf0)

---
**Desired Behavior**

- [ ] Component does not error on multiple homepage changes and searches (within the same session)
  - Should component not allow searching and setting of dashboards within personal collections?

---
**Steps to Reproduce**

1. Go to admin settings -> settings (top bar) -> general (side bar)
2. Remove the custom homepage (if set)
3. Set a new custom homepage using a dashboard from your personal collection
4. Try to change the custom homepage again by searching for a dashboard from your personal collection

---
**Priority:** P2

**Comment by npfitz** [comment]
I'm having some trouble reproducing this. I reached out to @JesseSDevaney , He's going to add some more details when he gets a chance

**Comment by npfitz** [comment]
Nevermind... it happens because you can still search within personal collections. I'm guessing the  "All Visualizations" dashboard in the example above is in @JesseSDevaney's personal collection.
