### ISSUE TITLE
Basic model action names are not translated

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#32358]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6830683/0ff6b0c7-dad6-4e0c-8ab2-5822ff3911a0)

### To Reproduce

1. Change language to any except English
2. Create a model
3. Open model details page for it
4. Enable basic actions for it
5. Inspect names of actions that appeared

### Actual behavior

Actions are named in English: "Create", "Update" & "Delete".

### Expected behavior

Names of actions are translated into chosen language.

### Severity

Low

**Comment by NevRA** [comment]
Fixed translation should be there in the new version
