### ISSUE TITLE
Metabase subscriptions always sending attachments

### ISSUE THREAD

**Issue by shalza95** [metabase/metabase#32351]
### Describe the bug

When I create a dashboard subscription it always sends csv attachments for all questions even if the "Attach results" is disabled. Is there a way to disable all result attachments? Thanks.

### Information about your Metabase installation

```JSON
Metabase -  v1.46.5
```

### Severity

Medium

**Comment by paoliniluis** [comment]
This is by design if the cards have more than a certain amount of values
