### ISSUE TITLE
Support MetaBot through proxy outgoing connection

### ISSUE THREAD

**Issue by steinex** [metabase/metabase#3236]
Hi, we are running Metabase v0.19.2.

To use the Slack integration, we must allow traffic from the Host running Metabase to Slack. As Slack is running on AWS and IP-Adresses always change, this is a real pain.

If Metabase would allow to use a proxy for outgoing connections, that would solve our problem, as we could use URL-Regexes in the Proxy to allow outgoing connections.

Would this feature feasible to implement?

Thanks in advance,
Frank

**Comment by tlrobinson** [comment]
@salsakran I assume @steinex means his firewall doesn't allow outbound connections unless the IP address is whitelisted, but Slack API's IP addresses occasionally change. I don't think that's particularly Slack's fault.

**Comment by wyvernnot** [comment]
:+1: We also need this feature for Google Analytics driver to work, because we run metabase behind a firewall.

The `HTTPS_PROXY` `HTTP_PROXY` and `NO_PROXY` environment variable should be respected in order to send outboud connections

**Comment by m30m** [comment]
We have this problem with google analytics too.

**Comment by tlrobinson** [comment]
@wyvernnot @m30m @steinex Could you try setting these JVM flags? https://stackoverflow.com/questions/120797/how-do-i-set-the-proxy-to-be-used-by-the-jvm

(note that the Docker image doesn't currently pass along JAVA_OPTS #3884)

**Comment by alex-mohemian** [comment]
Can probably be closed. Since https://github.com/metabase/metabase/pull/3884 was closed, proxy options can be set like this:

```bash
docker run --rm -d -e JAVA_OPTS="-Dhttp.proxyHost=http://web.proxy.internal -Dhttp.proxyPort=80 -Dhttps.proxyHost=http://web.proxy.internal -Dhttps.proxyPort=80" -p 3000:3000 --name metabase metabase/metabase
```

For Slack integration, you need the HTTPS proxy.

**Comment by alex-mohemian** [comment]
@vrivellino agreed, Slack does not honor the proxy options!

**Comment by asolera** [comment]
These set of docker run options worked for me:

``` 
docker run -d -e JAVA_OPTS="-Dhttp.proxyHost=10.10.193.25 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=10.10.193.25 -Dhttps.proxyPort=3128" -e "MB_DB_TYPE=postgres" -e "MB_DB_DBNAME=metabase" -e "MB_DB_PORT=5432" -e "MB_DB_USER=metabase" -e "MB_DB_PASS=password" -e "MB_DB_HOST=metabase_db" -e "MB_DB_FILE=/metabase-data/metabase.db" -p 3000:3000 --net=metabase --name metabase metabase/metabase
```

**Comment by oBoMBaYo** [comment]
These set of java run options worked only Metabase send pulse to Slack but doesn't work when using Metabot on Slack. https://metabase.com/docs/latest/users-guide/11-metabot.html

> java \
                       -Dhttps.proxyHost=[proxyhost] \
                       -Dhttps.proxyPort=3128 \
                       -Dhttp.proxyHost=[ProxyHost] \
                       -Dhttp.proxyPort=3128 -jar $PATH_TO_JAR


Got same error like @vrivellino 

```
11-26 17:50:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 17:53:05 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 18:19:45 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 18:22:04 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 18:26:41 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 18:29:00 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 18:31:19 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 18:54:22 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 18:56:42 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 19:48:01 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 19:50:26 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 19:52:52 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 19:55:11 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 19:59:48 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 20:02:07 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 20:04:26 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 20:48:38 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 20:50:57 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 20:55:34 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 20:57:54 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 21:02:31 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 21:35:10 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 21:49:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 21:54:17 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 21:56:36 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:01:13 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:03:32 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:10:30 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:22:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:25:13 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:30:18 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:32:52 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:35:11 ERROR metabase.metabot :: Error connecting websocket: Read timed out
11-26 22:40:02 ERROR metabase.metabot :: Error connecting websocket: Read timed out
```

**Comment by asolera** [comment]
> @asolera Could you help to test Metabot? Is it work in your environment?

@oBoMBaYo Metabot won't work here because my metabase installation is unaccessible from outside/internet, it is running on my company's intranet

**Comment by oBoMBaYo** [comment]
@asolera Metabase configure Metabot to use websocket which is a computer communications protocol, providing full-duplex communication channels over a single TCP connection.

So, websocket secure (wss) should honor the proxy options.

**Comment by asolera** [comment]
> @asolera Metabase configure Metabot to use websocket which is a computer communications protocol, providing full-duplex communication channels over a single TCP connection.
> 
> So, websocket secure (wss) should honor the proxy options.

It didn't work here, maybe because of some firewall configuration.

**Comment by oBoMBaYo** [comment]
@asolera Thank you for the answer.

**Comment by patok28** [comment]
> These set of java run options worked only Metabase send pulse to Slack but doesn't work when using Metabot on Slack. https://metabase.com/docs/latest/users-guide/11-metabot.html
> 
> > java 
> >                        -Dhttps.proxyHost=[proxyhost] 
> >                        -Dhttps.proxyPort=3128 
> >                        -Dhttp.proxyHost=[ProxyHost] 
> >                        -Dhttp.proxyPort=3128 -jar $PATH_TO_JAR
> 
> Got the same error like @vrivellino.
> @asolera Could you help to test Metabot? Is it work in your environment?
> 
> ```
> 11-26 17:50:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 17:53:05 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 18:19:45 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 18:22:04 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 18:26:41 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 18:29:00 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 18:31:19 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 18:54:22 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 18:56:42 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 19:48:01 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 19:50:26 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 19:52:52 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 19:55:11 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 19:59:48 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 20:02:07 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 20:04:26 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 20:48:38 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 20:50:57 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 20:55:34 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 20:57:54 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 21:02:31 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 21:35:10 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 21:49:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 21:54:17 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 21:56:36 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:01:13 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:03:32 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:10:30 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:22:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:25:13 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:30:18 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:32:52 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:35:11 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> 11-26 22:40:02 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> ```

I have the same problem, I can send pulse to Slack but doesn't work when using Metabot on Slack. 
I have metabase running on my company's intranet with the proxy settings.
@oBoMBaYo could you resolved this?
Does anyone know if it is an open port issue that can be resolved asking to the networking area of my company to open this port?. 
Thank you!

**Comment by razer96** [comment]
> > These set of java run options worked only Metabase send pulse to Slack but doesn't work when using Metabot on Slack. https://metabase.com/docs/latest/users-guide/11-metabot.html
> > > java
> > > -Dhttps.proxyHost=[proxyhost]
> > > -Dhttps.proxyPort=3128
> > > -Dhttp.proxyHost=[ProxyHost]
> > > -Dhttp.proxyPort=3128 -jar $PATH_TO_JAR
> > 
> > 
> > Got the same error like @vrivellino.
> > @asolera Could you help to test Metabot? Is it work in your environment?
> > ```
> > 11-26 17:50:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 17:53:05 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 18:19:45 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 18:22:04 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 18:26:41 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 18:29:00 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 18:31:19 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 18:54:22 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 18:56:42 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 19:48:01 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 19:50:26 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 19:52:52 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 19:55:11 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 19:59:48 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 20:02:07 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 20:04:26 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 20:48:38 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 20:50:57 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 20:55:34 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 20:57:54 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 21:02:31 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 21:35:10 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 21:49:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 21:54:17 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 21:56:36 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:01:13 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:03:32 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:10:30 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:22:40 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:25:13 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:30:18 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:32:52 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:35:11 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > 11-26 22:40:02 ERROR metabase.metabot :: Error connecting websocket: Read timed out
> > ```
> 
> I have the same problem, I can send pulse to Slack but doesn't work when using Metabot on Slack.
> I have metabase running on my company's intranet with the proxy settings.
> @oBoMBaYo could you resolved this?
> Does anyone know if it is an open port issue that can be resolved asking to the networking area of my company to open this port?.
> Thank you!

I have asked security department in my company to give an access to all ports and all domains used by slack. It doen't make sense. The connection is still timed out...

**Comment by paoliniluis** [comment]
I believe we can close this one @flamber as the proxy for outgoing connections is already there, the websocket issue for Slack is going to be addressed in https://github.com/metabase/metabase/issues/5380

**Comment by oBoMBaYo** [comment]
> @oBoMBaYo could you resolved this?
> Does anyone know if it is an open port issue that can be resolved asking to the networking area of my company to open this port?.
> Thank you!

Sorry for very very delay, Actually we solved this issue long back by using proxychains4 to change metabot traffic to proxy server that supported socks.

`proxychains4 -q java -jar metabase.jar`

cat /etc/proxychains.conf
> strict_chain
> 
> #proxy_dns
> 
> tcp_read_time_out 1500000
> tcp_connect_time_out 800000
> localnet 10.0.0.0/255.0.0.0
> localnet 0.0.0.0:389/0.0.0.0
> 
> [ProxyList]
> socks4 99.999.9.99 xxxx << Your socks proxy server
> socks5 99.999.9.99 xxxx << Your socks proxy server

**Comment by flamber** [comment]
Closing as MetaBot is deprecated as of v0.42 #19435
