### ISSUE TITLE
After hiding column in table settings on question based on another question, all joined columns unchecked in notebook editor when still selected

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#32374]
### Describe the bug

- After hiding/removing columns in the question notebook editor on a question using a model or saved question as a data source, then using the table settings to hide a column from a table that was joined in the model/saved question, all joined columns show as unselected in v1.46.6, and all columns show as unselected in `master` as of `7dc11856`

### To Reproduce

1. Create and save a question using Sample Data > Orders with a left join to to Sample Data > People on Orders.user_id = People.id as Question A
2. Create a new Question (Question B) using Question A as the data source
3. Hide a few columns using the Question Notebook editor and click Visualize
<img width="618" alt="image" src="https://github.com/metabase/metabase/assets/8808703/703fdb8d-eef5-4890-ba2c-ab888a6ad192"> 

4. Click the Table settings ⚙️ gear icon and try to add the columns back
5. See error (columns are not added back, and browser console has errors) and all columns show as addable (show up under "Add columns" in table settings) even when the are already added.

6. In v1.46.6, visiting the Notebook editor after hiding a column in the table settings shows the joined tables all unchecked (even if only one column is hidden)
<img width="654" alt="image" src="https://github.com/metabase/metabase/assets/8808703/802171a0-52a9-4f4b-9b79-789692c0599a">

7. In `master`, all columns shown as unchecked
<img width="474" alt="image" src="https://github.com/metabase/metabase/assets/8808703/9c92b940-3fcc-493d-96fc-7c0a2e5b71d7">

8. Clicking Visualize still shows all columns that are selected in table settings even though unchecked in Notebook editor

### Expected behavior

selected columns should have show as selected in both notebook editor and table settings

### Logs

<img width="966" alt="image" src="https://github.com/metabase/metabase/assets/8808703/e584150c-8e16-483b-90d2-d5ddbc301698">

<img width="928" alt="image" src="https://github.com/metabase/metabase/assets/8808703/39adefcc-ae46-4419-90d9-0d2546161fca">

### Information about your Metabase installation

```JSON
- Metabase v1.46.6 and `master` as of `7dc11856`
```

### Severity

P1: selected columns should match the selected columns in both table settings and the notebook editor

### Additional context

- Related to
  - https://github.com/metabase/metabase/issues/30546
  - https://github.com/metabase/metabase/issues/31321
  - https://github.com/metabase/metabase/issues/32373

**Comment by ranquild** [comment]
Caused by invalid field references in https://github.com/metabase/metabase/issues/32373

**Comment by ranquild** [comment]
Broken by https://github.com/metabase/metabase/pull/31581 on the CLJS side.

**Comment by likeshumidity** [comment]
Seems to be fixed in changes fixing https://github.com/metabase/metabase/issues/32373
