### ISSUE TITLE
Suggestion: Allow reordering of dashboard level field filters and SQL parameter widgets

### ISSUE THREAD

**Issue by ShmuelTreiger** [metabase/metabase#3238]
I suggest a drag and drop method, but it doesn't matter too much

**Comment by mazameli** [comment]
Yeah, I think this would be nice. We could probably try and use a similar interaction to what we're using for dashboard cards already.

**Comment by Hennisa** [comment]
Any ideas when this could be implemented? This would make a huge difference for our organization.

**Comment by mazameli** [comment]
This could be relatively simple using patterns we already have.

**Dashboard edit mode with redesigned filters that look more like cards:**

![01 filters](https://user-images.githubusercontent.com/2223916/30447875-150cbb5e-9942-11e7-8221-ac72b6d996b1.png)

**Click and drag to move a filter. The can only be positioned on grid tiles in the top row:**

![02 click and drag to move](https://user-images.githubusercontent.com/2223916/30447883-1934dbd0-9942-11e7-90e3-89bc556a796a.png)

**Indicator that you can insert a filter in between other filters:**

![03 insert between filters](https://user-images.githubusercontent.com/2223916/30447919-2b2f8380-9942-11e7-9817-68e928971b8d.png)

**Repositioned filter:**

![04 filter in new position](https://user-images.githubusercontent.com/2223916/30447940-3c7d87ae-9942-11e7-8499-a71600ab6116.png)

**Comment by ryanfoxsquire** [comment]
This has been open since Aug 2016? Am I understanding correctly that there is no way to adjust the order of the parameter boxes/widgets on the dashboard other than deleting them all and re-entering them? .... :(

**Comment by cliff-pennalligen** [comment]
For SQL filter widgets, I work around this by referencing the variables in comments at the start, in the desired order.  However, this only works until you reach a certain number of filters, then they become randomly ordered as per #5136

**Comment by jonhyde-legl** [comment]
Hey @mazameli We're interested in whether we could locate a filter anywhere on a dashboard so we could create areas of the dashboard covered by specific filters (also maybe a line break across sections would be nice?
Is this covered in this request or somewhere else?? Happy to explain on a call if you'd like :)

**Comment by flamber** [comment]
@jonhyde-legl Have a look at #12482/#13821
