### ISSUE TITLE
Role level security for Redshift

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32388]
**Is your feature request related to a problem? Please describe.**
One of our customers who tested the feature needs this for Redshift

**Describe the solution you'd like**
Implement the feature for this https://docs.aws.amazon.com/redshift/latest/dg/t_Roles.html

**Describe alternatives you've considered**
None currently

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by dobomode** [comment]
I believe the correct Redshift feature is:
https://docs.aws.amazon.com/redshift/latest/dg/r_SET_SESSION_AUTHORIZATION.html

**Comment by paoliniluis** [comment]
closing as https://github.com/metabase/metabase/issues/38445
