### ISSUE TITLE
Pie Chart can crash/lock up Chrome

### ISSUE THREAD

**Issue by lewisl9029** [metabase/metabase#3239]
Steps to reproduce:
1. Create a new question
2. Select the `People` table from the Sample Dataset
3. Choose `Count of Rows` by `State`
4. Click `Get Answer`
5. Switch Visualization to Pie Chart

Expected:

Pie chart is displayed without significant delay or crashing the browser tab.

Actual:

Using Chrome on Windows 10, the browser tab crashes after a brief moment. Using Chrome on NixOS 16.03, browser tab locks up and then eventually (after around 2 minutes) displays a very unresponsive pie chart with the following errors in console:

![image](https://cloud.githubusercontent.com/assets/6934200/17786817/6f7b7fda-653b-11e6-94fb-131389fa6fc1.png)

The "Maximum call stack size exceeded" error means this could be related to #2608

~~Also note that the resulting pie chart claims to have 2500 items when other visualizations only have 62:~~ Never mind, it looks like the total on the pie chart is the sum of all the individual items.

![image](https://cloud.githubusercontent.com/assets/6934200/17787236/25e9bd9e-653d-11e6-9b59-72e9171d96e4.png)

![image](https://cloud.githubusercontent.com/assets/6934200/17787291/609b23e2-653d-11e6-9a8b-6fbf579fe9c7.png)

Not reproducible on Firefox 50.0a2.

If this is a bug report, please fill in the blanks:
-  I am using the Google Chrome 52.0.2743.116 browser.
-  My computer's OS is NixOS 16.03 (locks up and then eventually call stack exceeded error) and Windows 10 (tab crashes).
-  I'm running Metabase locally from the dev server, and on Heroku and it is using the H2, and Heroku Postgres database.
-  My data is in a H2 database. 
-  My Metabase version is latest master.

**Comment by pate** [comment]
A company executive reports that their Metabase dashboard is throwing "Maximum call stack exceeded" in Firefox and Chrome (latest, I presume). Their dashboard contains a pie chart. I haven't managed to isolate it to that, but here is a screenshot of the inspector logs:

![image](https://cloud.githubusercontent.com/assets/1011676/20102174/c326de2c-a5cd-11e6-86e3-4e5d3513297b.png)

**Comment by tlrobinson** [comment]
This also occurs in the Mac app, I believe only when the legend gets truncated.

**Comment by tlrobinson** [comment]
Resolved by #4071

**Comment by tlrobinson** [comment]
@shwhl This fix will be released in v0.23.0.

If you have a chance could you try running `master` and see if it's fixed (easiest way is `docker run metabase/metabase-head:latest`, or pull the source and run `./bin/build`)

**Comment by shwhl** [comment]
@tlrobinson I'm running it on production, so it's not quite possible to try master branch, but I will let you know the results once I update it to v0.23.0 after you released.

**Comment by shwhl** [comment]
@tlrobinson just updated to 0.23, I think it's solved, thanks!
