### ISSUE TITLE
[MLv2] Migrate legacy segments to MLv2

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#32409]
MLv1 allows to apply a legacy segment as a filter. We should follow a similar route we went with legacy metrics for MLv2 aggregations (#31871)

- [ ] `available-segments` method
- [ ] `display-info` implementation for segments (should have a display name and a description)
- [ ] if a segment is used in a filter clause, it should be marked as selected in the `available-segments` list or something
- [ ] there should be a way to apply a segment filter. E.g. `filter` method could accept a segment object
- [ ] it should be possible to replace one filter segment with another using `replace-clause` (similar to #32049)

**Comment by camsaul** [comment]
This sounds like two separate issues

**Comment by kulyk** [comment]
@camsaul done, please LMK if something is still unclear
