### ISSUE TITLE
Allow the user control which series are split on the left and right axis

### ISSUE THREAD

**Issue by underyx** [metabase/metabase#3242]
-  I am using the Google Chrome browser.
-  My computer's OS is macOS Sierra.
-  I'm running Metabase via Docker remotely and it is using the Postgres database.
-  My data is in a Postgres database.
-  My Metabase version is 0.19.3.

I have the following data (series names intentionally cut off, if they are relevant I can anonymize the data and post it like that):
![](https://i.imgur.com/BQv8ZCL.png)

If I select the Line viz type, the chart will look like this; the series with the sudden jump on the right is the first column from the table:
![](https://i.imgur.com/2rAW2ry.png)

The tooltips seem to suggest that it's an issue with thousands separators:
![](https://i.imgur.com/FlNoKue.png) ![](https://i.imgur.com/P1JJzPK.png)

**Comment by tlrobinson** [comment]
It looks like we're just automatically splitting the axis (which we probably shouldn't be doing for breakout multiseries). See how there are different ranges on the left and right axis?

You can disable this behavior in the chart settings.

<img width="875" alt="screenshot 2016-08-19 09 08 25" src="https://cloud.githubusercontent.com/assets/18193/17816152/951ecdee-65ec-11e6-9bdc-b71accb1014c.png">

If i'm misunderstanding the issue please let me know.

**Comment by underyx** [comment]
Oh, right, I did not notice the labels on the left. I'll rename this issue then, thanks!

**Comment by drewnewell** [comment]
I'm finding that the setting is actually under eager -- could it be changed to a off/on instead of trying to set it automatically? I have the same setup as original reporter, but on version 20.3.

![image](https://cloud.githubusercontent.com/assets/2434851/20317833/9d2adc42-ab1c-11e6-9f50-ef0e38602aca.png)

**Comment by salsakran** [comment]
@drewnewell as @tlrobinson mentioned, there is a manual override if we get things wrong.

Closing this as NotABug. If anyone wants to take a crack at improving the axis selection logic at https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/lib/utils.js, or help us with writing test cases for examples that split `incorrectly`, we'd love the help =)

**Comment by drewnewell** [comment]
Where is the manual override to force separate axes?

**Comment by underyx** [comment]
@salsakran do you think I could at least file an issue about the UI not making it clear enough that the data are on separate axes? You might notice that I opened this issue with the title

>Line chart not placing values on Y axis correctly, possibly related to thousands separator

which means I didn't even realize multiple axes charting was a thing in Metabase. If the lower line didn't look so weird, I probably wouldn't have noticed at all, which could be quite disastrous :(

**Comment by tlrobinson** [comment]
@drewnewell You are right, there is only a manual override to turn it off, not force it on. We should give the user more control over how the axis is the split.

**Comment by mazameli** [comment]
Yeah, I think drewnewell is talking about something like changing the split axis toggle from `auto / off` to `auto / on / off`, and if it's set to `on`, presumably you'd have another set of inputs for the min/max of the second y-axis.

**Comment by jacklenehan** [comment]
This is a pretty frustrating limitation. IMO it's not that uncommon that two series need different axes (and, by extension, labels and ranges).

**Comment by nickcarenza** [comment]
It will have to be more than auto/on/off in case there are more than 2 series. If not auto, each series will need to be given an option of whether to use the left/right axis.
