### ISSUE TITLE
The ability to copy an entire collection with all the belongings

### ISSUE THREAD

**Issue by okaeiz** [metabase/metabase#32425]
**Is your feature request related to a problem? Please describe.**
In my use case, I need to create reports for several groups that have similar reports with similar queries. I'm frustrated that every time a new group is added to the list, I need to create every single collection and question from scratch.

**Describe the solution you'd like**
It would be wise if we could copy the entire collection with all the questions that it includes.

**How important is this feature to you?**
If this feature is added, it can save everyone's time and energy; because they will no longer have to create dashboards or collections that already exist.

**Additional context**
[Copy collection](https://discourse.metabase.com/t/copy-collection/8508)

**Comment by paoliniluis** [comment]
This is available via the new serialization implementation
