### ISSUE TITLE
Field Filter SQL Template tag doesn't work outside of a subselect

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3243]
Not sure exactly how we'd fix this but the below example gets dinged because the fully qualified field name references a table name that is only valid inside the innermost sub-select.

```
SELECT COUNT(*) FROM    
     (SELECT * FROM 
         (SELECT * FROM payment WHERE state = 'confirmed'
         ORDER BY create_time ASC) p
     GROUP BY merchant_id
     /* HAVING date_format(create_time, '%Y-%m') = date_format(now(), '%Y-%m') */
     HAVING {{chosen_time}}
     ) t2
```

more info in the conversation in http://discourse.metabase.com/t/sql-variable-to-work-with-month-and-year-dashboard-filter/584/8

**Comment by flamber** [comment]
Closing in favor of #3324
