### ISSUE TITLE
[MLv2] Make `joinable_columns` return JS array

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#32443]
Currently, it seems like `joinable_columns` returns a Clojure vector in JS, and the FE has to use `to_array` from `cljs/cljs.core` to make it work. We should update the JS wrapper to do that

**Comment by camsaul** [comment]
You can just add `to-array` to the JS wrapper in `src/metabase/lib/js.cljs` yourself if you want it's a one-liner

**Comment by kulyk** [comment]
> You can just add to-array to the JS wrapper in src/metabase/lib/js.cljs yourself if you want it's a one-liner

@camsaul I did it for now, but I figured we'd like to do this in `js.cljs` as for other methods
