### ISSUE TITLE
Bugs on People tab

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#32451]
**Context**
List of small and independent bugs on the People tab.
These should be low-drama issues.

```[tasklist]
### Bugs
- [ ] https://github.com/metabase/metabase/issues/14431
- [ ] https://github.com/metabase/metabase/issues/28091
- [ ] https://github.com/metabase/metabase/issues/30197
```

**Comment by nemanjaglumac** [comment]
I have a fix for #28091 but had issues trying to set up the proper mock environment to be able to properly unit test it.
