### ISSUE TITLE
Add proportional bars ("100%") option to bar charts

### ISSUE THREAD

**Issue by pjutard** [metabase/metabase#3246]
Allow to transform a chart like this:
![image](https://cloud.githubusercontent.com/assets/1218897/17827711/e9bc38d0-6657-11e6-8734-b4de2337aa7b.png)

Into one like this:
![image](https://cloud.githubusercontent.com/assets/1218897/17827719/158ac198-6658-11e6-92b2-598ec1469df3.png)

As you have the "Stacked" option today, I´d like to have a "proportional" option to allow for this.

Thanks!

**Comment by tlrobinson** [comment]
Here's an example using dc.js, which is what we're currently using for bar charts https://github.com/austinlyons/dcjs-normalized-bar

**Comment by mazameli** [comment]
@tlrobinson, in #3705, we were talking about the possibility of enabling this through adding a "100%" scale in the axis chart options. This generally makes sense to me, though one weird thing is that that scale only really makes sense when stacked bars are turned on, yeah? I.e., another direction would be to turn the stacked option from a toggle into a set of radio options, like, "Bar style: normal, stacked, proportionally stacked," in which case the y-axis scale would be overridden. I guess I'm saying it feels a little funny to have to select two different options in two different places to get the desired chart.

**Comment by tlrobinson** [comment]
I actually like the idea of turning the stacked toggle into a a select/radio, since they're just two different forms of stacking.
