### ISSUE TITLE
No tables shown in sample data or otherwise.

### ISSUE THREAD

**Issue by wttw** [metabase/metabase#3248]
If this is a bug report, please fill in the blanks:

*  I am using the Safari (current) browser.
*  My computer's OS is OS X (current).
*  I'm running Metabase locally from the JAR and it is using the Postgres and H2  databases.
*  My data is in a Postgres database. 
*  My Metabase version is v0.19.3 (796613e release-0.19.3).

From the web interface everything seems to work and there are no errors, but no databases have any tables.

Running a new instance with "MB_JETTY_PORT=8082 java -jar metabase.jar" everything looks reasonable, with just a few "level ->FINE, text -> "The configuration file ... could not be found, Skipping" until it tries to load the sample data:

08-21 09:21:51 INFO metabase.sample-data :: Loading sample dataset...
08-21 09:21:51 INFO metabase.sync-database :: Syncing H2 database 'Sample Dataset'...
08-21 09:21:51 INFO sync-database.introspect :: Introspecting schema on H2 database 'Sample Dataset' ...
08-21 09:21:51 DEBUG driver.generic-sql :: Creating new connection pool for database 1 ...
08-21 09:22:23 ERROR metabase.sample-data :: Failed to load sample dataset: Connections could not be acquired from the underlying database!
["driver.generic_sql$describe_database.invokeStatic(generic_sql.clj:359)"
 "driver.generic_sql$describe_database.invoke(generic_sql.clj:356)"
 "driver$fn__18203$G__18171__18210.invoke(driver.clj:45)"
 "sync_database.introspect$db__GT_tables.invokeStatic(introspect.clj:186)"
 "sync_database.introspect$db__GT_tables.invoke(introspect.clj:185)"
 "sync_database.introspect$introspect_database_and_update_raw_tables_BANG_.invokeStatic(introspect.clj:202)"
 "sync_database.introspect$introspect_database_and_update_raw_tables_BANG_.invoke(introspect.clj:196)"
 "sync_database$sync_database_with_tracking_BANG_$fn__22089.invoke(sync_database.clj:77)"
 "sync_database$sync_database_with_tracking_BANG_.invokeStatic(sync_database.clj:74)"
 "sync_database$sync_database_with_tracking_BANG_.invoke(sync_database.clj:68)"
 "driver$fn__18414.invokeStatic(driver.clj:242)"
 "driver$fn__18414.invoke(driver.clj:242)"
 "driver$fn__18376$G__18161__18385.invoke(driver.clj:45)"
 "sync_database$sync_database_BANG_.invokeStatic(sync_database.clj:43)"
 "sync_database$sync_database_BANG_.doInvoke(sync_database.clj:24)"
 "sample_data$add_sample_dataset_BANG_.invokeStatic(sample_data.clj:32)"
 "sample_data$add_sample_dataset_BANG_.invoke(sample_data.clj:14)"
 "core$init_BANG_.invokeStatic(core.clj:168)"
 "core$init_BANG_.invoke(core.clj:126)"
 "core$start_normally.invokeStatic(core.clj:226)"
 "core$start_normally.invoke(core.clj:220)"
 "core$_main.invokeStatic(core.clj:260)"
 "core$_main.doInvoke(core.clj:255)"
 "core.main(Unknown Source)"]

When using postgresql (both for configuration and to access my database) it appears to connect correctly to the database containing data (I see it connect, run "SET extra_float_digits = 3" and "SELECT 1" in the server logs), but it doesn't display any tables. There is no error shown in the web interface, but java shows:

{:message "ERROR: syntax error at or near \"NULL\"\n  Position: 54",
 :stacktrace
 ["db$query.invokeStatic(db.clj:368)"
  "db$query.doInvoke(db.clj:364)"
  "db$simple_select.invokeStatic(db.clj:427)"
  "db$simple_select.invoke(db.clj:419)"
  "db$select.invokeStatic(db.clj:673)"
  "db$select.doInvoke(db.clj:666)"
  "api.database$fn__22219$fn__22220.invoke(database.clj:205)"
  "api.common.internal$wrap_catch_api_exceptions.invokeStatic(internal.clj:220)"
  "api.common.internal$wrap_catch_api_exceptions.invoke(internal.clj:217)"
  "api.database$fn__22219.invokeStatic(database.clj:200)"
  "api.database$fn__22219.invoke(database.clj:200)"
  "middleware$enforce_authentication$fn__24945.invoke(middleware.clj:79)"
  "api.routes$fn__25043.invokeStatic(routes.clj:40)"
  "api.routes$fn__25043.invoke(routes.clj:40)"
  "routes$fn__30135.invokeStatic(routes.clj:24)"
  "routes$fn__30135.invoke(routes.clj:24)"
  "middleware$log_api_call$fn__25030$fn__25031.invoke(middleware.clj:264)"
  "db$do_with_call_counting.invokeStatic(db.clj:337)"
  "db$do_with_call_counting.invoke(db.clj:331)"
  "middleware$log_api_call$fn__25030.invoke(middleware.clj:263)"
  "middleware$add_security_headers$fn__24990.invoke(middleware.clj:200)"
  "middleware$bind_current_user$fn__24949.invoke(middleware.clj:94)"
  "middleware$wrap_current_user_id$fn__24936.invoke(middleware.clj:62)"
  "middleware$wrap_api_key$fn__24956.invoke(middleware.clj:105)"
  "middleware$wrap_session_id$fn__24929.invoke(middleware.clj:53)"]}

... and the matching queries in the postgresql server log are ...

2016-08-21 09:44:56 PDT [1368-222] metabase@metabase LOG:  duration: 0.117 ms  bind <unnamed>: SELECT "metabase_table"."id" FROM "metabase_table" WHERE ("db_id" = 5 AND "active" = TRUE)
2016-08-21 09:44:56 PDT [1368-223] metabase@metabase LOG:  duration: 0.008 ms  execute <unnamed>: SELECT "metabase_table "."id" FROM "metabase_table" WHERE ("db_id" = 5 AND "active" = TRUE)
2016-08-21 09:44:56 PDT [1368-224] metabase@metabase ERROR:  syntax error at or near "NULL" at character 54
2016-08-21 09:44:56 PDT [1368-225] metabase@metabase STATEMENT:  SELECT * FROM "metabase_field" WHERE (("table_id" in NULL) AND "special_type" = $1)

**Comment by camsaul** [comment]
@wttw thanks for the bug report. I've merged PR #3290 which should address the issues you're seeing. It will ship as part of our next release (0.20) which should ship in the next few weeks.
