### ISSUE TITLE
[MLv2] Fields in Viz settings

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#32501]
Migrate changing query fields in viz settings to MLv2.

The primary reason for migrating this area to MLv2 is that it is buggy and cannot be easily fixed in MLv1. The current implementation doesn't work correctly with nested queries and/or models, and fixing the issues requires deep understanding of MBQL. Recent escalations for the reference
- https://github.com/metabase/metabase/issues/32373
- https://github.com/metabase/metabase/issues/32374

The flow looks like this:
- Open a question with display `table`
- All query columns + potential available ones are displayed via `query.fieldOptions` https://github.com/metabase/metabase/blob/77fbb5822d90efa5facae9f3c656172d92166489/frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx#L38 Note that columns from `fieldOptions` are intersected with columns from query results by comparing `field_ref`.
- The user adds a column which modifies `visualization_settings` with key for the column computed by `getColumnKey` https://github.com/metabase/metabase/blob/b0c4d99261dde4176ccad199cd0ff247d73f218c/frontend/src/metabase-lib/queries/utils/get-column-key.ts#L13
- `syncColumnsAndSettings` is called to sync field clauses https://github.com/metabase/metabase/blob/b01a41bbeecd233dc1ce50a921e882c1998fa5e7/frontend/src/metabase-lib/Question.ts#L842 which in turn modifies fields in the query https://github.com/metabase/metabase/blob/716aed38dd365c929340ab94dff50f3849c5f54e/frontend/src/metabase-lib/queries/utils/dataset.js#L116
- UI for the reference https://github.com/metabase/metabase/assets/8542534/9c6ad3a2-defb-4d55-b556-9b3f56439ff8

```[tasklist]
- [ ] BE - Extend fieldable-columns in MLv2 or provide a new function that also return columns from FKs, like fieldsOptions on the FE does
- [ ] BE - Add a way to get field ref from a MLv2 column
- [ ] FE - Migrate column list in table viz settings to MLv2
```

**Comment by camsaul** [comment]
RE

> BE - Add a way to get available columns in the query, taking fields from the results and fields from implicitly joined tables into account

I believe `filterable-columns` actually returns exactly this information, we should probably write a bespoke function for this specific purpose in case we need to include `:selected` information or stuff like that, but you can use that to get started

**Comment by camsaul** [comment]
> BE - Add column key for viz settings

What do you mean by this? `field_ref`? Do you need a function to get the field ref from an MLv2 query? Please explain

**Comment by camsaul** [comment]
> BE - Sync viz settings with field clauses

I don't understand this one either. Are you talking about migrating `syncColumnsAndSettings()` to MLv2? I don't think that's in scope for the current project. We should leave it in JS for now and just update the parts that actually touch the query to use MLv2. So it can use some MLv2 function to get column metadata, and use MLv2 to add a field, but the overall structure of the code can stay in JS for the time being.

**Comment by ranquild** [comment]
> > BE - Add column key for viz settings
> 
> What do you mean by this? `field_ref`? Do you need a function to get the field ref from an MLv2 query? Please explain

Yes, exactly this - a field ref from a column

**Comment by ranquild** [comment]
> > BE - Sync viz settings with field clauses
> 
> I don't understand this one either. Are you talking about migrating `syncColumnsAndSettings()` to MLv2? I don't think that's in scope for the current project. We should leave it in JS for now and just update the parts that actually touch the query to use MLv2. So it can use some MLv2 function to get column metadata, and use MLv2 to add a field, but the overall structure of the code can stay in JS for the time being.

The issue is that columns that come to `syncColumnsAndSettings` are computed incorrectly and have broken field refs, that's why we cannot use `withFields` from MLv2 instead of `addField`, `clearField` etc. Furthermore, `syncColumnsAndSettings` also changes fields in joins. 

Maybe we could the issue by providing a MLv2 function that computes columns for table viz settings, with a way to get a field ref for every column. Maybe with the correct list of columns and refs existing code would work correctly.

**Comment by ranquild** [comment]
@camsaul Updated the backend tasks based on the previous comments - now it's only about computing the correct list of columns + a way to get `field_ref` for compatibility with existing code
