### ISSUE TITLE
[MLv2] `joinable-columns` returns nothing if a given table isn't linked to the source table

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#32511]
It seems like `joinabe-columns` returns columns only for tables that are linked to the source table via FKs. It doesn't match MLv1 behavior when it's possible to join any table in the same database.

**Comment by camsaul** [comment]
As discussed in this Slack thread https://metaboat.slack.com/archives/C04CYTEL9N2/p1689796383221859 this is actually an issue with the metadata for the table not being present in the MLv2 MetadataProvider, so we need to solve the problem 

> We need a way to provide MLv2 with the new metadata once it is fetched

mentioned there. I'll link this to the relevant issue once we decide how to approach that problem

**Comment by camsaul** [comment]
I wrote a test for this

```clj
(deftest ^:parallel joinable-columns-unrelated-table-test
  (testing "joinable-columns should return all columns from joinable Table, even if it is not related to the source Table (#32511)"
    (are [joinable-columns] (=? [{:lib/type :metadata/column, :name "ID"}
                                 {:lib/type :metadata/column, :name "EAN"}
                                 {:lib/type :metadata/column, :name "TITLE"}
                                 {:lib/type :metadata/column, :name "CATEGORY"}
                                 {:lib/type :metadata/column, :name "VENDOR"}
                                 {:lib/type :metadata/column, :name "PRICE"}
                                 {:lib/type :metadata/column, :name "RATING"}
                                 {:lib/type :metadata/column, :name "CREATED_AT"}]
                                joinable-columns)
      (lib/joinable-columns lib.tu/venues-query -1 (meta/table-metadata :products))
      (lib/joinable-columns lib.tu/query-with-join -1 (meta/table-metadata :products))

      (let [query (-> lib.tu/venues-query
                      (lib/join (-> (lib/join-clause (meta/table-metadata :products))
                                    (lib/with-join-conditions [(lib/= (meta/field-metadata :venues :id)
                                                                      (meta/field-metadata :products :id))]))))
            [join] (lib/joins query)]
        (lib/joinable-columns lib.tu/venues-query -1 join)))))
```

but it passes because the metadata provider in the tests does have that data. So not sure it's even worth adding the test or not.

**Comment by camsaul** [comment]
Anton has a demo of this not working at https://metaboat.slack.com/archives/C04CYTEL9N2/p1689956490690979?thread_ts=1689796383.221859&cid=C04CYTEL9N2

**Comment by camsaul** [comment]
Should be able to repro on `mlv2-fe/join-columns` as well

**Comment by camsaul** [comment]
Demonstrated in the Loom linked here https://metaboat.slack.com/archives/C04CYTEL9N2/p1690233272016989?thread_ts=1689796383.221859&cid=C04CYTEL9N2

The problem is that `joinableColumns()` is called immediately after you select a Table to join, before the metadata gets updated, then this response is cached and it never gets called again, even after the metadata is updated. So the empty result is cached forever. 

To fix this, we should only call `joinableColumns()` when we want to render the Fields picker, and avoid caching the results. Caching will likely lead to other problems, because `selected` status won't get updated properly either.

**Comment by kulyk** [comment]
Turned out to be a FE issue, closing
