### ISSUE TITLE
Getting "java.io.IOException: Failed to bind to /0.0.0.0:80" while running on AWS ECS

### ISSUE THREAD

**Issue by abhi1045** [metabase/metabase#32528]
### Describe the bug

I'm trying to deploy Metabase v0.46.6 on AWS ECS type Fargate.

I'm using AWS RDS Postgres DB for Metabase metadata DB.

Here is my Dockerfile :

```
FROM metabase/metabase:v0.46.6

ENV MB_DB_TYPE=postgres \
    MB_DB_DBNAME=<your_db_name> \
    MB_DB_PORT=5432 \
    MB_DB_USER=<your_db_user_name>\
    MB_DB_PASS=<your_db_password> \
    MB_DB_HOST=<your_db_host> \
    MB_JETTY_PORT=80

EXPOSE 80
```

Task definition:

```
{
  "family": "<your_service_name>",
  "networkMode": "<your_network>",
  "containerDefinitions": [
    {
      "name": "<your_service_name>",
      "image": "<your_docker_image>:latest",
      "portMappings": [
        {
          "containerPort": 80,
          "hostPort": 80,
          "protocol": "tcp"
        }
      ],
      "essential": true,
    }
  ],
  "requiresCompatibilities": ["FARGATE"],
  "cpu": "1024",
  "memory": "2048",
  "executionRoleArn": "<your_arn>"
}
```

Docker image is build using this command

```
docker build --no-cache -t <your_docker_image>:latest .
```

The same I try to do locally, it worked.

### To Reproduce

1. Go to AWS ECS.
2. Into your define Cluster, create new service by clicking on service.
3. Use the above mentioned task definition.
4. Click on create.
5. See error in the logs of ECS service.

### Expected behavior

It should work properly, without shutting down the metabase instance or without having issue to bind at port 80

### Logs

When I try to deploy it on AWS ECS, I'm getting error and Error message is -

```
ERROR metabase.core :: Metabase Initialization FAILED

java.io.IOException: Failed to bind to /0.0.0.0:80
```
<img width="492" alt="image" src="https://github.com/metabase/metabase/assets/86192930/52987587-3057-42da-9b9c-f3c9b4be5a5b">

### Information about your Metabase installation

```JSON
- Metabase version : v0.46.6
- Metabase Internal database - Postgres
```

### Severity

High Severity

**Comment by paoliniluis** [comment]
you can't use port 80 in a linux environment without permissions. Please use port 3000 and do a NAT

**Comment by abhi1045** [comment]
@paoliniluis, I think you misunderstood. We have deployed other applications on port 80 using ECS.
When I'm running locally, I got to know that both port `3000` and `80` are open.

<img width="1263" alt="image" src="https://github.com/metabase/metabase/assets/86192930/a09d3e8a-3593-47c4-bc23-12b3c1cbbde6">


While deploying on ECS, getting this error

```
java.io.IOException: Failed to bind to /0.0.0.0:80
```

**Comment by paoliniluis** [comment]
Please check https://repost.aws/questions/QU1bCV9wT4T5iBrrP1c2ISfg/container-cannot-bind-to-port-80-running-as-non-root-user-on-ecs-fargate

**Comment by abhi1045** [comment]
I'm trying from last couple of days and found this solution and this works fine.

Here is my Dockerfile:

```
FROM openjdk:11

RUN wget -O metabase.jar "https://downloads.metabase.com/v0.46.6/metabase.jar"

ENV MB_DB_TYPE=postgres \
    MB_DB_DBNAME=<your_db_name> \
    MB_DB_PORT=5432 \
    MB_DB_USER=<your_db_user_name>\
    MB_DB_PASS=<your_db_password> \
    MB_DB_HOST=<your_db_host> \
    MB_JETTY_HOST=0.0.0.0 \ 
    MB_JETTY_PORT=80

EXPOSE 80

CMD ["java", "-jar", "metabase.jar"]
```

**Comment by luuizdias** [comment]
I encountered the same issue and wondered why @abhi1045’s solution worked. It turns out that the Metabase Docker image is based on Eclipse Temurin images, which include the BusyBox package. This package uses port 80. Therefore, when you create your own image without this package, port 80 becomes available for binding.
