### ISSUE TITLE
Unable to rename columns individually when coming from the same table on 2 joins

### ISSUE THREAD

**Issue by Timelessprod** [metabase/metabase#32551]
### Describe the bug

I have a table `Transactions` containing two columns with country codes in the ISO 2 character format, let's call them `coutry_from` and `country_to`. On another dim table (called `Countries`) I have informations about countries including the correspondence between ISO codes and country names. I joined this table twice on `Transactions` and keep only the `Name` column to get the country name for `country_from` and `country_to`. This result in a table with two columns being named `Countries -> Name`. As it is confusing to distinguish which is for `country_from` and `country_to` I wanted to rename them to `country_from_name` and `country_to_name`. However when I rename one of them , the other is also renamed with the same name which, as a user, is not the behavior I would expect. I would like to be able to rename them independently to provide meaningful results. This behavior has been observed in different situations where we realize two or more joins on same table and keeping the same column.

### To Reproduce

1. Go to Metabase web UI and open any table with *n* (*n* > 1) columns of the same category (countries, customer id, user id, etc.)
2. Go to the editor and create *n* joins with another table (the same for all joins) that is joinable with your current one on the columns mentioned above. For each join keep only one column from the joining table. Click on visualize and on the bottom of your window, click on the right icon (3 squares) to switch to visualisation mode.
3. Click on one of the columns coming from the joins and rename it.
4. See that all other columns from the joins are also renamed the same.

### Expected behavior

I should be able to rename independently each columns from those joins

### Information about your Metabase installation

```JSON
- Browser: Chrome Version 114.0.5735.198 (Official Build) (arm64)
- OS: MacOS Ventura 13.4.1
- Databases: parquet files managed by BigQuery on GCS
- Metabase version: v0.46.6 build 2023.06.29
- Metabase hosting environment: Docker
```

### Severity

Annoying but non-blocking

**Comment by Timelessprod** [comment]
Hello, any update possible please ? Thank you.

**Comment by calherries** [comment]
This should be fixed in Metabase 47 with https://github.com/metabase/metabase/issues/27504
