### ISSUE TITLE
Separate Read / Write permissions for Native SQL

### ISSUE THREAD

**Issue by mark-sparks** [metabase/metabase#32555]
**Is your feature request related to a problem? Please describe.**

When allowing users access to SQL questions, it would be useful for security and data segregation purposes to prevent the user from being able to edit the SQL, but still be able to read the dataset. 

With the current permission setting, it appears to be all-or-nothing - unless I am missing something obvious!

This is linked to other configuration issues, for example:
- you cannot use sandboxing AND native queries, so a workaround is to use a native query and ask users to apply a text filter with a secret passphrase
- if the user can edit the native query, they can potentially remove the filter from within the query, and by default will be able to see all data

**Describe the solution you'd like**

Replace the current all-or-nothing option with two separate options for read and write permission

**Describe alternatives you've considered**

- Support sandboxing AND native queries on the same dataset
- Support native querying permissions at a lower level than database level
- Provide a default filter setting on dashboards where no data is shown if the filter is empty (this has been described in another unresolved issue already)

**How important is this feature to you?**

Pretty important - the use-case of being able to share user-specific data with external parties (who are licensed) without the risk that they will be able to see other party's data, or be able to edit the native query to remove the filtering

**Comment by paoliniluis** [comment]
so you want users to read the SQL syntax but not edit that?

**Comment by mark-sparks** [comment]
As in - they can execute the query, i.e. read only access - I don't care personally if they can "see" the raw SQL - but as far as I understand currently, users can't return results from a native query unless they have full access - which means they can also potentially edit the SQL.

**Comment by paoliniluis** [comment]
Nope, If you give “no self service” users will be able to run questions made in sql and not edit them
