### ISSUE TITLE
"Assert failed" error when upgrading to v0.46.6.1 to apply security patches for security vulnerability

### ISSUE THREAD

**Issue by amartinsn** [metabase/metabase#32564]
### Describe the bug

Hi Metabase folks, 

Today we tried to upgrade our instance to v0.46.6.1 following the recommendations from this post (https://www.metabase.com/blog/security-advisory), and we ran into a lot of errors while users tried to execute their queries. Here's the error we are getting:

`
Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer. (< (.size puts) impl/MAX-QUEUE-SIZE)
`

We ended up reverting the upgrade back to v0.46.1, but we still need to address this security vulnerability.
Is this issue known? What recommendation would you make to apply the security patches? 

Thank you.

### To Reproduce

When accessing any question page.

### Logs

Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer. (< (.size puts) impl/MAX-QUEUE-SIZE)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "4.14.314-238.539.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.38-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-05",
      "tag": "v0.46.1",
      "branch": "release-x.46.x",
      "hash": "12a6e1d"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

### Severity

High

**Comment by paoliniluis** [comment]
This doesn’t have to do with the patch. There’s no change in the jetty side

**Comment by amartinsn** [comment]
It looks like this error was introduced somewhere between v0.46.1 and v0.46.6, and it is still happening in v0.46.6.1

Is there a bug ticket already created for this bug? I didn't understand why you closed it. We’re happy to help reproduce the issue under 0.46.6.1 if that helps.

Also, I came across this post on the forum: https://discourse.metabase.com/t/assert-failed-no-more-than-1024-pending-puts-are-allowed-on-a-single-channel-consider-using-a-windowed-buffer/25574/7

**Comment by mstepniowski** [comment]
The problem is likely related to this open issue: https://github.com/metabase/metabase/issues/31513 

What is interesting here, is that the issue didn't occur for us under v0.46.1. Was there a performance regression?

**Comment by paoliniluis** [comment]
@amartinsn please send us the complete reproduction steps on an instance that you pull from scratch if possible with the sample database. We’ve tried in many ways to hit this and couldn’t
