### ISSUE TITLE
Custom expression that has a name consisting only of whitespace breaks the question

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32571]
### Describe the bug

If you name a custom expression with just an space, it will break the question as the query processor is expecting a non-blank string

### To Reproduce

1) create a GUI question. E.g Orders -> group by -> custom expression: "CountIf([Quantity] > 1) / SumIf([Total], [Product → Category] = "Gizmo")" . The name of the custom grouping: just a space char " " (without the double quotes)
2) run it and see
```
Input to resolve-card-id-source-tables* does not match schema: 

	 [0;33m  [(named {:query {:aggregation [[nil nil (named {:name (not ("Non-blank string" " ")), :display-name (not ("Non-blank string" " "))} "options")]]}} arg0)] [0m 
```

### Expected behavior

We shouldn't allow spaces as names

### Logs

NA

### Information about your Metabase installation

```JSON
pretty sure it's been since forever
```

### Severity

P3

**Comment by ibedwi** [comment]
Hi @paoliniluis @kamilmielnik , I've created a PR to fix this issue. Would you mind to review it? Thanks!
