### ISSUE TITLE
New tables won't show up

### ISSUE THREAD

**Issue by mostafaqanbaryan** [metabase/metabase#32577]
### Describe the bug

After replacing a database with the new one that has 2 more tables, everything works fine in Metabase.
Except that the new tables won't show up anywhere.
Of course  I can query them directly from SQL Editor.

I've read these:
https://www.metabase.com/docs/latest/troubleshooting-guide/cant-see-tables
https://discourse.metabase.com/t/new-mysql-db-tables-not-showing-up/2295
https://discourse.metabase.com/t/tables-not-showing-up/15977
and a few more others. But nothing works.

Eventually I was forced to delete the database from Metabase and add it again!

### To Reproduce

1. Connect a Mysql database to Metabase
2. Create a new table in the database
3. Replace the old one with the new one (Restore the backup)
4. New table should show up on Metabase (But won't)
5. (Created a new table inside the connected database without the backup/restore part, won't who either)

### Expected behavior

After replacing an old database with a new one, new tables should show up on Metabase 

### Logs

No log is generated

### Information about your Metabase installation

```JSON
- metabase/metabase:v0.44.5
- mariadb:10.5.8-focal
```

### Severity

I had to remove the entire database and restore it again. So that says it

**Comment by paoliniluis** [comment]
have you tried forcing a sync?

**Comment by mostafaqanbaryan** [comment]
> 

I did the `Sync database schema now` and `Re-scan field values now`, and even set an hourly `Database syncing`.
But if there is something else, I don't know about it

**Comment by mostafaqanbaryan** [comment]
So there is no way I assume?

**Comment by paoliniluis** [comment]
Hi @mostafaqanbaryan did you fix the issue?

**Comment by mostafaqanbaryan** [comment]
> Hi @mostafaqanbaryan did you fix the issue?

Hello.
Yes.
Updated to latest version, hit the sync button and after a few hours, somehow it was fixed.
