### ISSUE TITLE
Custom landing page with an external URL will lock everyone out of MB

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#32585]
### Describe the bug

If we customize homepage with an external URL, MB will fail to load and display a blank page.

The only way to reset that value is to update the setting using SQL manually.

### To Reproduce

1. Enable enterprise
2. Go to Admin => Appearance
3. Set the custom homepage setting with `https://google.com`
4. open MB in a new tab

### Expected behavior

should not allow entering external URLs

### Information about your Metabase installation

```JSON
master
```

### Severity
locking everyone out of MB is quite serious

**Comment by cdeweyx** [comment]
For when it comes time to address this: [More context here](https://metaboat.slack.com/archives/C01LQQ2UW03/p1690166757208049)

**Comment by luizarakaki** [comment]
Related [#35497](https://github.com/metabase/metabase/issues/35497)

**Comment by sloansparger** [comment]
I've merged a PR that will prevent users from inputting an invalid input on the frontend, but we still need to mirror this change on the backend.
