### ISSUE TITLE
Add more properties to the config.yml file

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#32586]
**Is your feature request related to a problem? Please describe.**
At the moment it is hard to automate because I have to launch Metabase, wait till it finishes initialising, and then launch a second script to load the data. If we can pass a dump to the config.yaml it would be more easy.

To add with the above config files might get a little limited since they do not handle all the configurations we expose via environment variables. Also currently they're just to add users and data sets, but you can't configure settings like email servers, SSO providers, or parameters like the amount of connections you want Metabase to send to the data sources.

**Describe the solution you'd like**
Beef the config.yml to support more properties and options

**Additional context**
Serialization can be used to achieve this but using a config.yaml makes the whole CI process much more easy and efficient

**Comment by paoliniluis** [comment]
@Tony-metabase why would you handle that via config.yml and not via env vars?

**Comment by Tony-metabase** [comment]
That is an option but a particular client asked for configs for spinning up test environments (eventually for CI) ... And having those in one place seem to be an idea scenario. 

Adding to that the Docker image on M1 is pretty slow so they are not launching Metabase with docker in their local development (I experience that as well) because it is significantly slower than launching the jar in a terminal. So something like:

- I install and configure Metabase
- I export the config.yml
- Edit config.yml 
- Deploy config.yml

Seems to be a simple approach. Having more features in the config.yml just makes the whole process above more easier. But it's not a must and there might be better alternatives to it. Just an option that we might consider

**Comment by luizarakaki** [comment]
@Tony-metabase The config file supports anything that is defined in the `setting` table in the app db.
https://www.metabase.com/docs/latest/configuring-metabase/config-file#list-of-settings

I tested some of these and everything worked:
site-uuid-for-premium-features-token-checks
application-colors
config-from-file-sync-databases
site-uuid-for-version-info-fetching
analytics-uuid
site-uuid
check-for-updates
experimental-enable-actions
persisted-model-refresh-cron-schedule
version-info-last-checked
email-smtp-host
version-info
enable-query-caching
email-smtp-username
start-of-week
email-smtp-password
email-smtp-port
query-caching-min-ttl
email-from-name
email-from-address
email-reply-to
premium-embedding-token
follow-up-email-sent
persisted-models-enabled
startup-time-millis
site-locale
application-name
settings-last-updated
instance-creation
enable-public-sharing
enable-embedding
embedding-secret-key
jwt-group-sync
anon-tracking-enabled
snowplow-available
jwt-enabled
google-auth-enabled
redirect-all-requests-to-https
site-url
site-name

**Comment by Tony-metabase** [comment]
Oh my bad! then that solves this since it offers extensive customisations I was under the impression you cannot configure settings like email servers, SSO providers
