### ISSUE TITLE
Queries run from Metabase to Mongo seems to ignore MongoDB built in caching

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#32587]
### Describe the bug

When you run queries from Metabase to Mongo they end up being very slow compared to when running query directly to Mongo.

Something to note is that the 2 queries run very similar the first time but the ones on Mongo get slashed by half.

### To Reproduce - I am using the Sample DB that comes with mongo Atlas

1. Go to New GUI Question-> Select Data Source -> Count and Group by something -> Run ... You can see it took around 6sec

<img width="1144" alt="image" src="https://github.com/metabase/metabase/assets/110378427/3bc16278-e427-4439-9d90-8db10295f952">

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/7000c467-335f-414c-ae24-956985d9bc4b">

2. If you run the same directly on MongoDB you will see a similar result (this syntax to run):

```
db.getSiblingDB("sample_mflix").getCollection("movies").aggregate([
    {
        "$group": {
            _id: {
                genres: "$genres"
            },
            count: {
                "$sum": 1
            }
        }
        
    },
    {
        "$sort": {
            _id: 1
        }
    },
    {
        "$project": {
            _id: false,
            genres: "$_id.genres",
            count: true
        }
    },
    {
        "$limit": 21
    }
])
```

3. Go to point 1 and run again ... You can see it took again around 6sec so it ignores MongoDB cache

4. Go to point 2 and run again ... You can see it too around 2 sec now (half what it was before) so any subsequent run seems to be using some kind of cache

<img width="1304" alt="image" src="https://github.com/metabase/metabase/assets/110378427/644fd27f-1c81-4eb7-a272-2f7254478533">

### Expected behavior

Ideally it uses the native cache of mongo so queries are more efficient

### Logs

None to report

### Information about your Metabase installation

```JSON
1.47 and master
```

### Severity

if you have large queries and speed is an issue then this is very problematic

**Comment by Tony-metabase** [comment]
The issue is worse if you convert the GUI question to SQL and run the query it takes 10 times more

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/293df9ca-a016-44c6-879b-806acae4888c">

**Comment by metamben** [comment]
Running this query in a local container using mongosh takes 2-3 ms on my machine.

**Comment by Tony-metabase** [comment]
@metamben can you share a similar step by step as I shared please so we can check the response time ... This is the query i run locally

```
db.getSiblingDB("sample").getCollection("analytic_events").aggregate([
        {
            "$group": {
                _id: {
                    timestamp: {
                        "$dateTrunc": {
                            date: "$timestamp",
                            unit: "minute",
                            timezone: "GMT",
                            startOfWeek: "sunday"
                        }
                    }
                },
                count: {
                    "$sum": 1
                }
            }
        },
        {
            "$sort": {
                "_id": 1
            }
        },
        {
            "$project": {
                "_id": false,
                "timestamp": "$_id.timestamp",
                "count": true
            }
        }
])
```

**Comment by metamben** [comment]
@Tony-metabase Sorry, I wasn't measuring correctly (I didn't pull all result rows). If I do pull all rows, this is what I see in a freshly created dockerized MongoDB instance:

```javascript
root@61aa6878fc37:/# mongosh mongodb://metabase:metasample123@localhost/sample?authSource=admin
Current Mongosh Log ID:	6511e0847883ee000b692059
Connecting to:		mongodb://<credentials>@localhost/sample?authSource=admin&directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.10.6
Using MongoDB:		6.0.9
Using Mongosh:		1.10.6

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

------
   The server generated these startup warnings when booting
   2023-09-25T19:33:13.514+00:00: vm.max_map_count is too low
------

sample> let start = Date.now(),
...  cursor = db.getSiblingDB("sample").getCollection("analytic_events").aggregate([ { "$group": { _id: { timestamp: { "$dateTrunc": { date: "$timestamp", unit: "minute", timezone: "GMT", startOfWeek: "sunday" } } }, count: { "$sum": 1 } } }, { "$sort": { "_id": 1 } }, { "$project": { "_id": false, "timestamp": "$_id.timestamp", "count": true } }] ),
...  len = cursor.toArray().length,
...  end = Date.now()

sample> console.log(`${len} matches in ${end - start} ms`)
20194 matches in 916 ms

sample> let start = Date.now(),
...  cursor = db.getSiblingDB("sample").getCollection("analytic_events").aggregate([ { "$group": { _id: { timestamp: { "$dateTrunc": { date: "$timestamp", unit: "minute", timezone: "GMT", startOfWeek: "sunday" } } }, count: { "$sum": 1 } } }, { "$sort": { "_id": 1 } }, { "$project": { "_id": false, "timestamp": "$_id.timestamp", "count": true } }] ),
...  len = cursor.toArray().length,
...  end = Date.now()

sample> console.log(`${len} matches in ${end - start} ms`)
20194 matches in 840 ms

sample> let start = Date.now(),
...  cursor = db.getSiblingDB("sample").getCollection("analytic_events").aggregate([ { "$group": { _id: { timestamp: { "$dateTrunc": { date: "$timestamp", unit: "minute", timezone: "GMT", startOfWeek: "sunday" } } }, count: { "$sum": 1 } } }, { "$sort": { "_id": 1 } }, { "$project": { "_id": false, "timestamp": "$_id.timestamp", "count": true } }] ),
...  len = cursor.toArray().length,
...  end = Date.now()

sample> console.log(`${len} matches in ${end - start} ms`)
20194 matches in 865 ms

sample> 
```

All runs seem to take around 0.85 seconds, I cannot see any 4x speedup.

**Comment by metamben** [comment]
Tested with the `sample_mflix` database in a docker container running on my machine.

Metabase is obviously slower than querying with mongosh in the docker container. the query with `limit 21` takes about 300 ms (255 ms wait for the server, 10 ms downloading the result) on my machine in Metabase, about 40 ms in mongosh in the container.

![Image](https://github.com/metabase/metabase/assets/103100869/c5203882-6984-4bf2-84e2-80f72c344af3)

If we remove the limit clause, 1027 rows are produced. In this case, the query took about 450 ms (312 ms waiting for the response, 145 ms downloading the result) in Metabase, and 93 ms in mongosh. 

![Image](https://github.com/metabase/metabase/assets/103100869/4ce3d58d-bd1c-49d8-b300-a279c9892a48)

This behavior seems normal (even if not totally satisfactory) and I don't think this slowness is specific to how we deal with MongoDB. I definitely cannot see anything related to disabled caching.

I suggest closing this ticket, and either do some proper measurement and optimization or look at a concrete problem a client has.

**Comment by Tony-metabase** [comment]
Thanks Tamas will close for now and open another one once I get a better understanding of the slowness
