### ISSUE TITLE
Improve organization of FK target field dropdown

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3260]
If you have a lot of primary keys in a database, it can be brutal scrolling down to find it.

We should provide a better organization structure and/or a search widget.

**Comment by tlrobinson** [comment]
As part of this we should explore supporting joins across multiple tables #1173 

IIRC the QP already supports it, it's just not exposed on the frontend.

**Comment by mazameli** [comment]
Pretty sure this is a dupe of https://github.com/metabase/metabase/issues/2805
