### ISSUE TITLE
Creating a collection when saving a question should return to the question save modal with the new collection selected

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#32600]
**Context**
Polish item from #29774
Slack context: [link](https://metaboat.slack.com/archives/C02H619CJ8K/p1690225861040359)

1. Create new question
2. Save
3. When saving, create a new collection

The current behavior: the collection is created and the question is automatically saved.
Desired behavior: create the collection and return to the question save modal with the new collection selected.

**Comment by shaunlebron** [comment]
**NOTE:** I’m keeping the milestone blank to prevent duplicate release notes on 47 for this parent issue: https://github.com/metabase/metabase/issues/29774
