### ISSUE TITLE
Google sign-in failing for some geolocations due to Google Identity Services (GSI) client issues

### ISSUE THREAD

**Issue by leonaascimento** [metabase/metabase#32602]
### Describe the bug

I've been using Metabase and Google auth without issues, and suddenly for users in Brazil, instead of the authentication page, we see the "Something's gone wrong page." Users in other locations, such as Portugal and USA, can log in to Metabase normally. Please take a look at the screencast below.

### To Reproduce

1. Metabase instance with Google auth enabled
2. Enable VPN going through Sao Paulo/Brazil region
3. Open Metabase and get redirected to the login page

![image](https://github.com/metabase/metabase/assets/6169152/58a3ce0f-1feb-46d3-b5b5-a0879339f8b6)

### Expected behavior

Proposal is to stop embedding Google Auth and redirect to Google Auth page (something like OpenAI does with chatgpt login) as it seems more stable

### Logs

```
api.js:209     GET https://metabase.<domain>/api/user/current 401
(anonymous) @ api.js:209
value @ api.js:167
value @ api.js:162
(anonymous) @ api.js:135
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
p @ app-main.bundle.js?28f670131887d2ef460e:2
a @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ api.js:32
(anonymous) @ api.js:111
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
p @ app-main.bundle.js?28f670131887d2ef460e:2
a @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ api.js:60
(anonymous) @ user.js:13
r @ createAction.js:16
u @ createAction.js:22
(anonymous) @ user.js:24
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
f @ app-main.bundle.js?28f670131887d2ef460e:2
a @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ user.js:22
(anonymous) @ redux.js:204
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
y @ app-main.bundle.js?28f670131887d2ef460e:2
a @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ redux.js:202
(anonymous) @ store.js:19
(anonymous) @ routes.jsx:175
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
kMt @ app-main.bundle.js?28f670131887d2ef460e:2
a @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ app-main.bundle.js?28f670131887d2ef460e:2
(anonymous) @ routes.jsx:174
o @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
l @ AsyncUtils.js:34
g @ AsyncUtils.js:51
r @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
r @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
l @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
l @ AsyncUtils.js:41
g @ AsyncUtils.js:51
F @ matchRoutes.js:231
c @ createTransitionManager.js:41
r @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
_o @ react-dom.production.min.js:137
$s @ react-dom.production.min.js:176
ya @ react-dom.production.min.js:263
mc @ react-dom.production.min.js:246
bc @ react-dom.production.min.js:246
cc @ react-dom.production.min.js:239
rc @ react-dom.production.min.js:230
Xc @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
uc @ react-dom.production.min.js:240
Gc @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
oI @ app.js:78
(anonymous) @ app.js:111
react-dom.production.min.js:209 Error
    at _.$e (client:128:335)
    at new qp (client:226:3)
    at $p (client:245:34)
    at Mo (client:243:246)
    at Object.No [as renderButton] (client:215:62)
    at index.esm.js:89:82
    at la (react-dom.production.min.js:211:320)
    at _c (react-dom.production.min.js:257:303)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Yi (react-dom.production.min.js:122:325)
oa @ react-dom.production.min.js:209
Oa.n.payload @ react-dom.production.min.js:227
bo @ react-dom.production.min.js:129
$s @ react-dom.production.min.js:179
ya @ react-dom.production.min.js:263
mc @ react-dom.production.min.js:246
bc @ react-dom.production.min.js:246
cc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yi @ react-dom.production.min.js:122
Gi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
_c @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yi @ react-dom.production.min.js:122
wc @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
N @ scheduler.production.min.js:17
w.port1.onmessage @ scheduler.production.min.js:14
app.js:16 Error: {componentStack: '\n    in l\n    in o\n    in div\n    in Styled(div)\n …\n    in p\n    in DragDropContextProvider\n    in I'}
f @ app.js:16
n.<computed> @ bindActionCreators.js:8
value @ ErrorBoundary.tsx:29
Oa.o.componentDidCatch.n.callback @ react-dom.production.min.js:227
go @ react-dom.production.min.js:131
ua @ react-dom.production.min.js:212
Oc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yi @ react-dom.production.min.js:122
zc @ react-dom.production.min.js:248
cc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yi @ react-dom.production.min.js:122
Gi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
_c @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yi @ react-dom.production.min.js:122
wc @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
N @ scheduler.production.min.js:17
w.port1.onmessage @ scheduler.production.min.js:14

```

### Information about your Metabase installation

```JSON
- My browser: Chrome/115.0.5790.102
- My OS: Ubuntu 22.04.2 LTS
- Metabase version: 0.46.6.1
- Metabase hosting environment: Kubernetes
- Metabase internal database: Postgres
```

### Severity

Blocking all users from Brazil to use Metabase

### Additional context

Problems like that have happened before #26184, and there are no changes we can make in Metabase to prevent it from happening again.

**Comment by JohniMichels** [comment]
I'm having the same problem. As soon as today, users that log off can't login again.
For some users clearing the cookies made the user to be able to login again ONCE. But as soon as logoff the bug comes back.

**Comment by betosaulo-cw** [comment]
+1

**Comment by rpyxao** [comment]
+1

**Comment by ruandocini** [comment]
+1

**Comment by lucascoimbr** [comment]
+1

**Comment by Jojoooo1** [comment]
+1

**Comment by JohniMichels** [comment]
Even through VPN in another countries I'm having the same issue.

**Comment by frenchita** [comment]
+1

**Comment by gustavohwulee** [comment]
Using login and password thru this link might help if you have user/password acess>

https://metabase.pesoreal.xyz/auth/login/password

**Comment by afquintana95** [comment]
If you go to the console error (`at _.$e (client:128:335)`) and use the debugger, if you change the `c: "300"` in the pic

![image](https://github.com/metabase/metabase/assets/13751642/c97c5639-24f2-42ad-9640-f1e29fc7644a)

 to a number (i.e `c:300:`) and then continue the excecution it will let you continue as normal with the login
![image](https://github.com/metabase/metabase/assets/13751642/36ce60cd-fbec-489c-bb4a-b629baf50140)

Most likely an update to the google script? Value seems hardcoded here I think https://github.com/metabase/metabase/blob/master/frontend/src/metabase/auth/components/GoogleButton/GoogleButton.tsx#L58

**Comment by bilby91** [comment]
We found the same problem today. Opened the following issue for dependency that metabase is using => https://github.com/MomenSherif/react-oauth/issues/277

**Comment by paoliniluis** [comment]
we're testing right now to push a fix ASAP

**Comment by alxnddr** [comment]
We will publish the release shortly but here are artifacts you can already use:

### 1.46.6.2
JAR: https://downloads.metabase.com/enterprise/v1.46.6.2/metabase.jar
Docker image: `metabase/metabase-enterprise:v1.46.6.2`

### 0.46.6.2
JAR: https://downloads.metabase.com/v0.46.6.2/metabase.jar
Docker image: `metabase/metabase:v0.46.6.2`

### v1.45.4.2
JAR: https://downloads.metabase.com/enterprise/v1.45.4.2/metabase.jar
Docker image: `metabase/metabase-enterprise:v1.45.4.2`

### v0.45.4.2
JAR: https://downloads.metabase.com/v0.45.4.2/metabase.jar
Docker image: `metabase/metabase:v0.45.4.2`

**Comment by rodolpho-amadatsu** [comment]
Hey [alxnddr](https://github.com/alxnddr), the elasticbeanstalk file is good to go?

**Comment by billy-arnold** [comment]
@rodolpho-amadatsu Looks like it's here https://downloads.metabase.com/v0.46.6.2/metabase-aws-eb.zip , have tried out and seems to be working

**Comment by rickvig** [comment]
> If you go to the console error (`at _.$e (client:128:335)`) and use the debugger and put a breakpoint, if you change the `c: "300"` in the pic
> 
> ![image](https://user-images.githubusercontent.com/13751642/255714053-c97c5639-24f2-42ad-9640-f1e29fc7644a.png)
> 
> to a number (i.e `c:300`) and then continue the excecution it will let you continue as normal with the login ![image](https://user-images.githubusercontent.com/13751642/255714189-36ce60cd-fbec-489c-bb4a-b629baf50140.png)
> 
> Most likely an update to the google script? Value seems hardcoded here I think https://github.com/metabase/metabase/blob/master/frontend/src/metabase/auth/components/GoogleButton/GoogleButton.tsx#L58

This is work for me

**Comment by marcel-puchol-jt** [comment]
Hi!
We are using the version `v0.44.7.1`, and we also have this problem. Do you plan to create a new release for `v0.44.x` versions?

**Comment by olliem36** [comment]
Is there a patch available for the Heroku buildpack? Many thanks!

**Comment by likeshumidity** [comment]
The patch for 44.x is in the works and we expect to release within the next few days.

**Comment by alxnddr** [comment]
@marcel-puchol-jt we've just patched Metabase 44 as well:
[Metabase v0.44.7.2](https://github.com/metabase/metabase/releases/tag/v0.44.7.2)
[Metabase® Enterprise Edition™ v1.44.7.2](https://github.com/metabase/metabase/releases/tag/v1.44.7.2)

**Comment by jbourdale** [comment]
Hello @alxnddr 

Do you plan to upgrade v0.47 RC also? I'm facing the same issue on this version

**Comment by jwg2s** [comment]
We are still experiencing this issue despite being on v1.46.6.2. I've heard from Metabase support that another patch is being released today, but no confirmation it's related to this specific Google SSO issue yet.

**Comment by sabarishp** [comment]
We are still facing the issue even after upgrading it to V1.46.6.4. We are located in Australia. What should be the next step?

**Comment by swaroopsaurav** [comment]
Guys, as a workaround, would suggest these steps which enabled users to login:

1. **Disbale the Google Login on your metabase Instance**: Disable the google auth from admin setting if any admin is still logged in. If not, you can update `google-auth-client-id`  key from setting table to NULL. This can solve the login page to at least load. 
2. **Disable Google Auth for all users:** Update the `google_auth` column for all users to `0x00` so that user can use forgot password to request new password to login.

**Comment by paoliniluis** [comment]
It seems that we should support the property as text and number

**Comment by m0nt3cr1st0** [comment]
Hi @alxnddr  I can confirm that we are still experiencing the issue while running the latest Metabase docker image: v0.46.6.4

I can see from a previous comment that you stated the issue was fixed in that case, are you aware of this?

**Comment by jrmywelco** [comment]
Still have issue with 0.46.6.2, 0.46.6.3, 0.46.6.4 and 0.47.0RC2

**Comment by Jordanjc3** [comment]
We were seeing this issue on `v0.46.6.1`, upgrading to `v0.46.6.2` has resolved it.

**Comment by jamesgreenblue** [comment]
FYI @Jordanjc3 `v0.46.6.2` has multiple reported vulnerabilities suggest you keep going to at least `v0.46.6.4`, see: https://www.metabase.com/blog/security-advisory-h2

**Comment by victorouse** [comment]
> Hello @alxnddr
> 
> Do you plan to upgrade v0.47 RC also? I'm facing the same issue on this version

We're also on the v0.47 RC and cannot downgrade since the schema changed [and I foolishly did not make a DB backup before upgrading 🤦]. 

@alxnddr can the v0.47 RC version be patched / released as well? 🙏

**Comment by alxnddr** [comment]
@victorouse we plan to release RC3 in a few days. The current latest RC does not have the security patches so it is not recommended to use

**Comment by paoliniluis** [comment]
@victorouse you can execute "java -jar metabase.jar migrate down" in v47 and move the db schema to v46. Closing this issue

**Comment by jrmywelco** [comment]
> @victorouse you can execute "java -jar metabase.jar migrate down" in v47 and move the db schema to v46. Closing this issue

Doesn't work for me. I'm hung now since our team use only google auth...
When will you provide a fix?

Thanks
