### ISSUE TITLE
Reimplement Google SSO resilient to any changes by Google

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#32614]
**Context**

Google SSO got broken two times (the last one: https://github.com/metabase/metabase/issues/32602). Every time this happens, it fully blocks users, who aren't logged in, from using Metabase if Google SSO is the only enabled login method. We should implement a more resilient approach.

**Comment by alxnddr** [comment]
The previous Google SSO implementation got [deprecated](https://developers.google.com/identity/sign-in/web/sign-in) and it was not secure because it exposed the access token to the client.

It is easy to implement oauth implicit flow for the SSO but it will have the same flaw of exposing the access token. There is [an RFC](https://datatracker.ietf.org/doc/draft-ietf-oauth-security-topics/) about it. The server flow considered to be more secure than this. But the current [Google Sign In](https://developers.google.com/identity/gsi/web/guides/overview) flow which separates authentication and authorization, includes CSRF and exposes only ID token is the best and I'm not sure if we can do anything without sacrificing security to prevent it from breaking when Google rolls out new breaking changes

**Comment by alxnddr** [comment]
@luizarakaki @darksciencebase please have a look at the summary above, I think we should not sacrifice security for the overall flow simplicity which is theoretically less fragile

**Comment by luizarakaki** [comment]
@alxnddr OpenAI uses Auth0 with Google SSO. Is their solution also sensitive to google breaking changes or vulnerable to CSRF?

https://chat.openai.com/auth/login

**Comment by ranquild** [comment]
Based on the "Installation" tab it seems that Auth0 uses the same Google APIs we use today for authentication https://marketplace.auth0.com/integrations/google-social-connection. 

I believe what @alxnddr meant is that our current solution is the most secure, but it's sensitive to API changes on the Google side.

**Comment by luizarakaki** [comment]
A user pointed to the differences between pop-up UX and redirect. Docs here:
https://developers.google.com/identity/gsi/web/guides/integrate#sign_in_with_google_button_considerations

My question is if we would have these problems if we deployed the redirect solution instead of the pop-up.
Both are recommended by Google, so if we have a more stable implementation with the redirect, I think it is worth changing it.

**Comment by eborysko** [comment]
This just re-appears for me after an update from v0.4.6.3 to v0.4.7. My test instances are still using v0.4.6.3 and don't appear affected.

**Comment by paoliniluis** [comment]
@eborysko please purge your CDN

**Comment by eborysko** [comment]
Thanks @paoliniluis, but I've purged Cloudflare twice and cleared the browser cache, but still having the same issue in v0.4.7

Steps:
1. open https://metabase-dev.{{MYDOMAIN}}/auth/login , get 401 on`/api/user/current`
2. Sign-in with Google
3. nothing happens on UI, but the console log contains two 500 errors on `/api/user/current` & `/api/session/properties`

<img width="557" alt="image" src="https://github.com/metabase/metabase/assets/2164805/3342e682-6291-43ab-9cc5-1b1d81d6f999">

**Comment by alxnddr** [comment]
> A user pointed to the differences between pop-up UX and redirect. Docs here: https://developers.google.com/identity/gsi/web/guides/integrate#sign_in_with_google_button_considerations
> 
> My question is if we would have these problems if we deployed the redirect solution instead of the pop-up. Both are recommended by Google, so if we have a more stable implementation with the redirect, I think it is worth changing it.

Unfortunately, it is still the recommended "Sign In with Google for Web" which implements the button. The issue was about the button itself so changing UX to redirect would not have prevented the issue. What could prevent it is to switching to implicit flow (unsafe due to exposure of access tokens to the client) or to the server flow. Anyway we depend on Google with them and there is always a chance of accidental breaking changes

**Comment by myupchar** [comment]
> Thanks [@paoliniluis](https://github.com/paoliniluis), but I've purged Cloudflare twice and cleared the browser cache, but still having the same issue in v0.4.7
> 
> Steps:
> 
> 1. open [https://metabase-dev.{{MYDOMAIN}}/auth/login](https://metabase-dev.%7B%7BMYDOMAIN%7D%7D/auth/login) , get 401 on`/api/user/current`
> 2. Sign-in with Google
> 3. nothing happens on UI, but the console log contains two 500 errors on `/api/user/current` & `/api/session/properties`
> 
> <img alt="image" width="557" src="https://private-user-images.githubusercontent.com/2164805/265853176-3342e682-6291-43ab-9cc5-1b1d81d6f999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTMyNDQsIm5iZiI6MTczNjQ5Mjk0NCwicGF0aCI6Ii8yMTY0ODA1LzI2NTg1MzE3Ni0zMzQyZTY4Mi02MjkxLTQzYWItOWNjNS0xYjFkODFkNmY5OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTBUMDcwOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY4YWJkMjBhMjFhMWQyMjg3NzE0YTU0YTMyY2M5MWRkZDg1YmVkM2ZlNGQzN2I4NDU3NTMzMjU0ZDNlYjcyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LJfbEgo0GXAfYt_9qsa5jgPWftYJARw5QTwQoGoIESI">

Did you find any solution for this? I am facing exactly the same issue.

**Comment by paoliniluis** [comment]
@myupchar please open an issue if you're hitting this again
