### ISSUE TITLE
Login error when "Updated" from 0.47.0-RC2 to 0.46.6.2

### ISSUE THREAD

**Issue by raphamotta** [metabase/metabase#32640]
### Describe the bug

When put correct username and password, i got this error:

ERROR: column core_user.google_auth does not exist Position: 204

Btw i got this error trying to back to any version prior to 0.47.

Any tips?

THnak you

### Information about your Metabase installation

```JSON
homemade docker on arm64 linux
```

### Severity

low

**Comment by paoliniluis** [comment]
You can't downgrade Metabase without executing a migration on the application database. Please run java -jar metabase.jar migrate down on the 47 container and then start the 46 once again

**Comment by raphamotta** [comment]
Thank you, the command:

` java -jar metabase.jar migrate down`

worked. I didn't find it on documentation, I think it's better to put there somewhere.
