### ISSUE TITLE
Clicking on "View details" after a drill down generates an error in the FE 

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32654]
### Describe the bug
1. Go to Admin > Table Metadata > Hide Orders table
2. Go to Products table and click the view detail icon.

<details>
<summary>Old reproduction</summary>

1) Go to question 2915 in our internal Metabase instance. then click on the pie chart on "show xxxx"
2) in the table that appears, go to the left side till the "view details" icon appears

you'll see that the FE breaks there with
```
TypeError: Cannot read properties of undefined (reading 'table')
    at schema_metadata.js:10:41
    at Array.map (<anonymous>)
    at i (schema_metadata.js:9:6)
    at p7 (ObjectRelationships.tsx:34:27)
    at Jo (react-dom.production.min.js:153:146)
    at Os (react-dom.production.min.js:261:496)
    at mc (react-dom.production.min.js:246:265)
    at bc (react-dom.production.min.js:246:194)
    at cc (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```
</details>

### To Reproduce

Above

### Expected behavior

It should show the detail view without problems

### Logs

NA

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

### Additional context

NA

**Comment by darksciencebase** [comment]
@NevRA added this to your inbox, but please re-route if the cause is somewhere else

**Comment by uladzimirdev** [comment]
brief investigation result:

```diff
diff --git a/frontend/src/metabase/lib/schema_metadata.js b/frontend/src/metabase/lib/schema_metadata.js
index ed6cb9544c..dc0fa21299 100644
--- a/frontend/src/metabase/lib/schema_metadata.js
+++ b/frontend/src/metabase/lib/schema_metadata.js
@@ -7,9 +7,9 @@ export function foreignKeyCountsByOriginTable(fks) {
 
   return fks
     .map(function (fk) {
-      return "origin" in fk ? fk.origin.table.id : null;
+      return fk.origin?.table.id ?? null;
     })
-    .reduce(function (prev, curr, idx, array) {
+    .reduce(function (prev, curr) {
       if (curr in prev) {
         prev[curr]++;
       } else {

```

**Comment by WiNloSt** [comment]
`origin_id: 536841` resulted in `origin: undefined` when it was populated with this line
https://github.com/metabase/metabase/blob/e55e7f78c74526472e8b5aa4996a45e9157cb445/frontend/src/metabase/selectors/metadata.ts#L345

However, after observing the response to `/api/table/<table_id>/fks` we seem to get the response with `origin` for the field ID `536841`

#### Redacted response: One of the items in the list result from `/api/table/<table_id>/fks`
```js
{
  "origin_id": 536841,
  "origin": {
    ...originObject,
    "id": 536841
  },
  "destination_id": 533184,
  "destination": destinationObject
}
```

I'm gonna investigate further why field 536841 isn't populated in `Metadata` at the time the referenced code above is called.

**Comment by WiNloSt** [comment]
I think I can reproduce this. The problem was because some of the foreign key is from a disabled table

To reproduce
1. Go to Admin > Table Metadata > Hide Orders table
2. Go to Products table and click the view detail icon.

It will crash

**Comment by WiNloSt** [comment]
There are 3 places that we call  `/api/table/<table_id>/fks`

1. [TableInfo.tsx](https://github.com/metabase/metabase/blob/c1d88baef0de186026b946b74ea45a461564e594/frontend/src/metabase/components/MetadataInfo/TableInfo/TableInfo.tsx#70) e.g. Browse data > select a database > select a table and hover on the table name in the table header
    ![Screenshot 2023-08-31 at 9 26 23 PM](https://github.com/metabase/metabase/assets/1937582/0b51bfb3-3530-4225-845e-4ec08aeb0d50)
2. [TableInfoLoader.tsx](https://github.com/metabase/metabase/blob/c1d88baef0de186026b946b74ea45a461564e594/frontend/src/metabase/query_builder/components/dataref/TableInfoLoader.tsx#37): SQL Query > Learn about your data > Select a table
    ![Screenshot 2023-08-31 at 9 33 51 PM](https://github.com/metabase/metabase/assets/1937582/67616d7d-2562-4a9c-9c49-f76da7043e36)
3. [ObjectDetail](https://github.com/metabase/metabase/blob/c1d88baef0de186026b946b74ea45a461564e594/frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx#L118) e.g. Browse data > select a database > click any row's View Detail icon (on the left of each row's ID)
    ![Screenshot 2023-08-31 at 9 35 40 PM](https://github.com/metabase/metabase/assets/1937582/33004fe7-d778-495e-87d2-bf60e1b2b59f)

Following the repro from [the previous comment](https://github.com/metabase/metabase/issues/32654#issuecomment-1699085207), after hiding the Products table, 1) and 2) are still working fine, but 3) crashes

**Comment by WiNloSt** [comment]
Fixing the UI using @uladzimirdev's code above would prevent the crash, but that's only part of the story. 
![image](https://github.com/metabase/metabase/assets/1937582/d61edefc-e618-432c-af46-817201a0ca61)


I think it could be a good compromise if we don't want to fix the problem created by that approach.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'table_id')
    at _callee2$ (object-detail.js:94:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:293:1)
    at Generator.next (runtime.js:118:1)
    at asyncGeneratorStep (navigation.js:112:1)
    at _next (navigation.js:112:1)
    at navigation.js:112:1
    at new Promise (<anonymous>)
    at navigation.js:112:1
    at _getFKCount3 (object-detail.js:75:1)
```

However, I think to match the behavior on `<TableInfo />` and `<TableInfoLoader />` we should fix the `<ObjectDetail />` so that we display non-hidden tables e.g. `Reviews` in this case.
e.g. here's how `<TableInfo />` displays when *Orders* table is hidden. It still shows the reference to *Reviews* table.
![image](https://github.com/metabase/metabase/assets/1937582/4ce02644-00d8-4125-bf2d-cc6e46dd7413)
