### ISSUE TITLE
App crashes when connecting a model action to a dashboard button

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#32665]
### Describe the bug

100% reproducible on stats instance. Can not reproduce locally.
Possibly related to #32666 (reviews table seems to be the key).

![image](https://github.com/metabase/metabase/assets/6830683/59ff1853-7c74-41cf-8d3a-cff38ca8e313)

### To Reproduce

1. Create a model based on reviews table from sample db
2. Enable actions in that model
3. Create a new dashboard
4. Add an action button to it
5. Try to connect update action of that model to your button

### Expected behavior

No crash

### Information about your Metabase installation

```JSON
Built on 2023-07-26
Branch: master
Hash: d687abe
```

### Severity

P1/P2

**Comment by ranquild** [comment]
I think it's the same issue https://github.com/metabase/metabase/issues/31918. The BE sometimes sends `parameters: null` for implicit actions and we don't expect this. To confirm. If that's the case, we need to fix it on the BE.
