### ISSUE TITLE
Metabase resets to "Run a Query" screen when running long queries

### ISSUE THREAD

**Issue by AlexandraLouise** [metabase/metabase#3268]
If this is a bug report, please fill in the blanks:
-  I am using the Metabase IOS application.
-  My computer's OS is OS X El Capitan.
-  I'm running Metabase locally with Mac App and it is using the Postgres database.
-  My data is in a Redshift database.
-  My Metabase version is 19.3.0.

When I submit my question, it goes into the "Doing Science" status and then eventually goes back to the "If you give me some data I can show you something cool. Run a Query!" So it fails to run the query. 

I went to my console and had the attached issue. 

Any advice? 

![screen shot 2016-08-25 at 2 37 02 pm](https://cloud.githubusercontent.com/assets/7575801/17969250/73ba3942-6ad1-11e6-8dd2-8b8449e85679.png)

**Comment by camsaul** [comment]
Unfortunately I don't think that Console message has anything to do with Metabase.

Does the query you're trying to run take a long time?

**Comment by camsaul** [comment]
You're using the Metabase iOS application?

**Comment by camsaul** [comment]
@AlexandraLouise ?

**Comment by camsaul** [comment]
@AlexandraLouise ?

**Comment by AlexandraLouise** [comment]
Hi @camsaul , yes it was taking a really long time. Is there a specific time out with Metabase?

**Comment by camsaul** [comment]
@AlexandraLouise yeah, there's a timeout if the query takes too long, but if that happens you're supposed to see a screen that says "Your question took too long" (I think). @tlrobinson is that still the case?

(Related: Issue #1749 and PR #2570)

**Comment by AlexandraLouise** [comment]
Is there a way to configure the time out?

**Comment by mazameli** [comment]
So, in #1749 we'd discussed having a simple input box in the Settings to configure the timeout on the individual query page (Question page):

"I'm inclined to just use our standard pattern under "Settings -> General". Could see a case being made for this being a per-DB setting, but am inclined to keep it simple. To recap, this would apply to individual questions, not database cards."

This still seems like a Thing We Should Do™.

**Comment by funktopus** [comment]
Hello, I am getting the same behaviour. Query is taking long and then resets to the "Run a query!" screen without info on what went wrong.

I am using Metabase for Mac v 0.24, connected to a MySQL database running on localhost.

Is this something unique to the mac version maybe?

**Comment by martinvy** [comment]
We have started to have this issue since we upgraded Metabase to version 0.24.2 last week. Our queries are taking long time to run, but previously we always got a result before. Our database is PostgreSQL. Do you think it may be connected to changes in the last release? thank you.

**Comment by camsaul** [comment]
I changed how the Mac App runs in #6116 and took out the logic that caused server restarts in situations like this. So as of version 0.26.2 this should be fixed

**Comment by mbvictoria** [comment]
Closing - fixed in newer versions.
