### ISSUE TITLE
Default value for optional parameter in query only works at end of line

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#32693]
**Describe the bug**
Setting a default value for an optional parameter in the query only works if the expression is at the end of a line.
For example, this snippet fails when a value is given to the `min_rating` parameter:
```between [[ {{ min_rating}} --]]1 and 5```.

The same works correctly if the variable and the rest of the expression are separated by a newline:
```
between [[ {{ min_rating}} --]]1 
and 5
```

**Logs**
-

**To Reproduce**
1. Save this as an SQL query on the sample database, and set a value for `min_rating`.
```
select rating, count(*) from REVIEWS
where RATING 
     between [[ {{ min_rating}} --]]1 and 5
group by rating
order by rating
```

2. An error occurs:
```Syntax error in SQL statement "-- Metabase:: userID: 1 queryType: native queryHash: 73adc3e1e0b94bd63b12ec8b6fef8d9117b8734cd6ce07fb078f8e7277019216\000aselect rating, count(*) from REVIEWS\000awhere RATING \000a between 1 --1 and 5\000a[*]group by rating\000aorder by rating"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, AND"; SQL statement: select rating, count(*) from REVIEWS where RATING between 1 --1 and 5 group by rating order by rating [42001-212]```

**Expected behavior**
SQL variable expressions should work irrespective of whitespace around.
Alternatively, if this is a known limitation we need to have it documented [here](https://www.metabase.com/docs/latest/questions/native-editor/sql-parameters#setting-complex-default-values-in-the-query).

**Screenshots**
-

**Severity**
Low since there is a workaround.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-14",
      "tag": "v1.46.5",
      "branch": "release-x.46.x",
      "hash": "272e3e6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by ranquild** [comment]
@zbodi74 this is a hack with comments. There are proper default values that can be set in the Variables sidebar.
