### ISSUE TITLE
Allow non-admins to create slack alerts if only slack notifications are configured

### ISSUE THREAD

**Issue by christopheralme** [metabase/metabase#32700]
**Is your feature request related to a problem? Please describe.**
We configured Slack notifications and want to allow non-admins to configure slack alerts. However, in the UI, there is a blocking experience that asks users to notify their admin to configure their email notifications, instead of allowing them to configure the alert. [Code here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/AlertModals.jsx#L133)

**Describe the solution you'd like**
Allow slack alerts to be configured by non-admin users when even when email notifications aren't configured.

**Describe alternatives you've considered**
Temporarily making people who create alerts an admin. This is gives more permissions than we're comfortable with to users.

**How important is this feature to you?**
We want to teams in our company to be able to configure slack alerts for core business metrics to get proactively looked at when they drop below thresholds. Our security team wants us doing this through slack. This is something metabase does support but this configuration is getting in the way. 

**Additional context**
Our company loves metabase and the analytics the self serve nature allows so many people to unlock.

**Comment by EmmadUsmani** [comment]
This should be solved by https://github.com/metabase/metabase/issues/27784 which @JesseSDevaney will start working on soon:

> From the Product side, we would like the following expected behavior:
> 
> - If neither email nor slack has been set up, if the user is a non-admin, don’t show them the dashboard subscription button at all.
> 
> - If either email or slack has been configured but not the other, and there are no existing subscriptions, take them straight to the new subscription form for the channel that is configured.
> 
> - If there are existing subscriptions they can see, show them that list first, and if they click new subscription, if only one channel has been configured, take them straight to the new subscription form for that channel.

@christopheralme I'm going to close this issue as a duplicate, feel free to comment on the other issue if there is anything we missed in the described behavior
