### ISSUE TITLE
403 Errors when logged in as admin user

### ISSUE THREAD

**Issue by ndmason1** [metabase/metabase#32724]
### Describe the bug

Hello, 

I am getting 403 Forbidden responses to two API calls being made via Metabase Admin settings. I've tried logging out and back in multiple times which did not resolve the issue. 

1. GET {metabaseDomain}/api/setup/admin_checklist (Settings > Setup tab)

![image](https://github.com/metabase/metabase/assets/3247269/d95c8f45-6cb4-45e2-89ec-55a2c461d922)

2. POST {metabaseDomain}/api/database (Attempting to create a new database connection)

![image](https://github.com/metabase/metabase/assets/3247269/dbd47f4b-53c4-4a61-a25c-be9f3e7be5b2)

I seem to be able to access every other part of the admin settings without issue. I was also able to do (2) the day before writing this.

FWIW, I checked with two other admin users in my org and they experience the same issue. We made some very minor changes to our user groups and permissions recently but I don't see how that would impact admin functionality.

### To Reproduce

I don't know how one would reproduce this to be honest.

### Expected behavior

I should be able to see the Setup tab and create a new connection without error.

### Logs

![image](https://github.com/metabase/metabase/assets/3247269/4e0683ff-0b2f-4023-be95-31a9b3851a7f)

![image](https://github.com/metabase/metabase/assets/3247269/daf12a46-2e31-43ed-8419-5af347e09ba9)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.242-156.349.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-24",
      "tag": "v1.46.6.2",
      "branch": "patch-google-sso-button",
      "hash": "a4c740a"
    },
    "settings": {
      "report-timezone": "America/Winnipeg"
    }
  }
}
```

### Severity

Minor - just annoying at the moment. Could be more of an issue if we need to make changes to our prod settings.

**Comment by paoliniluis** [comment]
This is a temporary measure we made
