### ISSUE TITLE
Metabase Pulse / Subscriptions are not working

### ISSUE THREAD

**Issue by SantosU** [metabase/metabase#32739]
Since 25th July 2023, the Automated Pulses / Subscriptions are not working. Though manual pulses (Send Email now) is working if triggered. I was able send Send Test Email as well.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**Expected behavior**
Daily Pulses / Subscriptions to be sent which has stopped since 25th July 2023

**Severity**
The management is not alerted on the issues with the data.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-LTS",
    "os.name": "Linux",
    "os.version": "5.10.135-122.509.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-14",
      "tag": "v0.40.1",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

**Comment by SantosU** [comment]
[Metabase Logs.txt](https://github.com/metabase/metabase/files/12212502/Metabase.Logs.txt)

Please find the Logs attached as well

**Comment by luizarakaki** [comment]
Please upgrade your instance before filling bug reports. We are running v46 and your instance is running v40.

**Comment by de-deepanshu** [comment]
@SantosU how did you get this solved ? we are also running into the same issue

**Comment by wasimb-atica** [comment]
@SantosU @de-deepanshu 
We were also facing same issue.
Trying changing your Reply-To email address to same as From email Address

It worked for use
