### ISSUE TITLE
200 OK on "Something gone wrong" Error

### ISSUE THREAD

**Issue by zumby** [metabase/metabase#32757]
### Describe the bug

We had an issue that prevented users from logging into metabase (OSS).
That issue was fixed by upgrading to latest metabase. 
The issue was caused by Google Auth that metabase is relying on. 
When the issue occurred - no automated alarms worked, as the Metabase was responding with 200 OK. Thus the issue was spotted by human :)

 

### To Reproduce

Attached the screenshots related to the issue. 
Browser console can clearly show that when you see Something went wrong" Error on the Metabase UI - you get 200 OK. 
This is not an expected behavior.

### Expected behavior

Something went wrong" Error should be related to 5xx Error - that is how automated alerting systems can understand that metabase instance is not functioning properly

### Logs

<img width="1792" alt="image (1)" src="https://github.com/metabase/metabase/assets/26290616/e87ef099-2866-4d20-9049-d2354b6be649">
<img width="1792" alt="image (2)" src="https://github.com/metabase/metabase/assets/26290616/b1dbe5dd-fbfa-401f-8240-3820245dd227">
<img width="1792" alt="image" src="https://github.com/metabase/metabase/assets/26290616/f3a52ecf-19ba-4fc4-ae6f-aa005e33045f">

### Information about your Metabase installation

```JSON
Metabase OSS (0.46)
```

### Severity

high

**Comment by mattkoch-bb** [comment]
We are also experiencing this.

**Comment by SimantovYousoufov** [comment]
We were experiencing this on 0.46.6.1 and upgrading to 0.46.6.4 seemed to resolve it. Hopefully this helps!

**Comment by Michae94** [comment]
We are also experiencing this on 0.46.6.2. We are going to try the latest upgrade to see if it resolves this issue.

**Comment by paoliniluis** [comment]
This was a frontend error, and that’s why Metabase kept working even if you were seeing errors as the browser was the problem here
