### ISSUE TITLE
There is a vulnerability in the redis service that can be injected with viruses, I've been hit!!!!

### ISSUE THREAD

**Issue by ellieot** [metabase/metabase#32755]
### Describe the bug

I don't want to describe it, it's rather tiring, and I don't need to discredit this open source project, my server alerts viruses, source is from metabase.
Just here to inform, if the company has a very important project, as far as possible, do not use this open source project, used to learn, not put into the public network on it!

### To Reproduce

![image](https://github.com/metabase/metabase/assets/32187143/2c0a6255-3eb1-4097-877b-7b66415e1ebb)
![image](https://github.com/metabase/metabase/assets/32187143/4b62273a-fe4a-482d-a108-36924d81c1b3)
![image](https://github.com/metabase/metabase/assets/32187143/ea1661d0-c42a-419c-b323-f0334f547fc9)
![image](https://github.com/metabase/metabase/assets/32187143/7080b394-accb-4bb9-99ec-3156ecfce2ff)

### Information about your Metabase installation

```JSON
1
```

### Severity

1

**Comment by luizarakaki** [comment]
Metabase doesn't use Redis.

Anyway, a vulnerability was identified last week. We released information and patches on our blog and communication channels.
https://www.metabase.com/blog/security-advisory-h2

**Comment by ellieot** [comment]
> Metabase doesn't use Redis.
> 
> Anyway, a vulnerability was identified last week. We released information and patches on our blog and communication channels. https://www.metabase.com/blog/security-advisory-h2

okey，thanks for the project，I will delete this post in a week，just to let people know the old version has problem, it seems like the hacker used docker to install redis on my server...
