### ISSUE TITLE
[MLv2] Tweaks to `join-lhs-display-name` method

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#32764]
Apparently, the `join-lhs-display-name` logic is a bit more comprehensive when adding a new join. Scenarios:

### 1. Adding a join when there're no joins

When adding a new join and there're no other joins, we should use the source table/model/question name as the LHS table display name (even before the RHS table is selected and before there're any conditions added)

<details>
<summary>Screenshot</summary>
<img width="383" alt="join-lhs-display-name-1" src="https://github.com/metabase/metabase/assets/17258145/c683ea1f-b054-4355-88d0-8fdbb19a2646">
</details>

### 2. Adding a join when there're other joins

When adding a new join and there's at least one join on the same stage, we should display "Previous results" before at least an LHS column is selected. After the LHS column is selected, the LHS display name should be the LHS column's table name.

I believe there're both FE and BE parts of the fix:

1. When the LHS column is selected, but the RHS one isn't yet selected, there's no join condition yet. This means `join-lhs-display-name` has nothing to use to figure out the LHS table display name. We probably want the FE to figure this out until there's at least one condition
2. Once there's at least one join condition, we probably want to completely rely on `join-lhs-display-name` (BE) here

<details>
<summary>Screenshot (no RHS table selected)</summary>

<img width="664" alt="join-lhs-display-name-2" src="https://github.com/metabase/metabase/assets/17258145/b9fef436-2dab-4f6e-b3b4-f050e42d0294">

</details>

<details>
<summary>Screenshot (RHS table selected, no columns selected)</summary>

<img width="934" alt="join-lhs-display-name-2 1" src="https://github.com/metabase/metabase/assets/17258145/c9c6b16e-f78b-49e7-8c78-abdb94860ded">

</details>

<details>
<summary>Screenshot (RHS table selected, LHS column selected)</summary>

<img width="931" alt="join-lhs-display-name-2 2" src="https://github.com/metabase/metabase/assets/17258145/b80ca08b-1d65-4b20-86ad-fe98d292223a">

</details>

**Comment by camsaul** [comment]
Original GH issue for reference: https://github.com/metabase/metabase/issues/32015

**Comment by camsaul** [comment]
So it appears that the LHS should actually come from the LHS column in the first condition.

Right now the signature is

```js
joinLHSDIsplayName(query, stageIndex, joinOrJoinable)
```

But I think we need to add an additional arity

```js
joinLHSDIsplayName(query, stageIndex, joinable, conditionLHSColumnOrNull)
```

so you can use this in the process of building a join
