### ISSUE TITLE
Updating heroku app fails

### ISSUE THREAD

**Issue by soilforlifeforms** [metabase/metabase#3277]
If this is a bug report, please fill in the blanks:

*  I am using the terminal.
*  My computer's OS is OSx 10.11.4.
*  I'm running Metabase on heroku and it is using the Postgres  database.
*  My data is in a postgres database.
*  My Metabase version is v0.17.0.

I am trying to update my app to the newest version, when I run git push -f heroku master I recieve these logs:

Counting objects: 243, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (89/89), done.
remote: fatal: early EOF
Writing objects: 100% (243/243), 535.06 MiB | 81.00 KiB/s, done.
Total 243 (delta 102), reused 243 (delta 102)
error: unpack failed: index-pack abnormal exit
To https://git.heroku.com/sfl-data-staging.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to 'https://git.heroku.com/sfl-data-staging.git'

I have tried a number of times now with the same result every time.

**Comment by kdoh** [comment]
Hey there @soilforlifeforms. Sorry you're running into problems. How did you initially deploy Metabase to Heroku? Was it via the Heroku deploy button or straight from Git?

**Comment by camsaul** [comment]
@soilforlifeforms ?

**Comment by camsaul** [comment]
@soilforlifeforms ?

**Comment by camsaul** [comment]
@soilforlifeforms ?

**Comment by camsaul** [comment]
@soilforlifeforms ?

**Comment by camsaul** [comment]
@soilforlifeforms since we haven't heard back in the better part of two months I'm going to go ahead and close this issue since we can't do anything without more information. Please feel free to open a new issue if you run into any more problems.
