### ISSUE TITLE
Date/time input does not respect date/time format settings

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#32781]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6830683/1f53811d-e02f-444f-9a29-a517665e2903)

### To Reproduce

1. Go to "Admin settings" > "Localization"
2. Change date style to YYYY/MM/DD
3. Change time style to 24h
4. Create and save a dashboard
6. Add new "Date filter" to this dashboard and save
7. Try to use the new "Date filter": choose "Specific dates...", then "Add a time" and then "Update filter"

### Expected behavior

Date/time format in the input value is formatted according to user settings

### Severity

P3

**Comment by ranquild** [comment]
I'd double check with designers and PMs about the expected behavior. Previously we agreed on using browser default settings in some cases.

**Comment by jakoblo** [comment]
Hey, i see the same behaviour when using the value from a date filter in a markdown text block as a variable. The variable always receives the value as a string in the format 'December 12, 2023' and doesn't reflect what was set in the settings.
The format is not usable in a url or something so i don't know if there is a workaround to have a format like 2023/12/12 or similar.

**Comment by ranquild** [comment]
Now we use formatting settings for query results and browser defaults for formatting regular values. This might change in the future.
