### ISSUE TITLE
Zero on axis not rounded, has many decimal places with single-row chart

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#32815]
### Describe the bug

Zero value on axis is not rounded as expected

### To Reproduce

1. Create a new Native SQL question
```sql
WITH base_query AS (
SELECT '2023-06-01' AS time_value, 'Under Benchmark' AS relative_status, -0.0094 AS special_clients
)

SELECT * FROM base_query
```

2. Select a bar chart visualization type
3. See the issue, zero on axis not visible, instead showing near-zero value
![image](https://github.com/metabase/metabase/assets/8808703/4fd27c19-ea7f-4db5-b5ae-fc334d67a8b2)

### Expected behavior

- expect value on axis to be rounded to zero

### Information about your Metabase installation

```JSON
- v1.46.6.4 and `master` as of `c8afac24`
```

### Severity

P3: makes chart look unpolished

### Additional context

related to:
- https://github.com/metabase/metabase/issues/9986
- https://github.com/metabase/metabase/issues/10062

**Comment by iethree** [comment]
related to https://github.com/metabase/metabase/issues/5816
