### ISSUE TITLE
Save button for SMTP settings form is in middle of page

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#32818]
**Problem:** Half of the email settings page, the SMTP connection settings, is click-to-save. The other half, email configuration settings, is auto-save. This is a confusing paradigm.

_Click-to-Save_
![image](https://github.com/metabase/metabase/assets/22608765/66f43a36-8793-41ab-a240-294a218cf68f)

_Auto-save_
![image](https://github.com/metabase/metabase/assets/22608765/e5a5f8d3-8c6e-496d-935f-e9f76bb47f99)

---
**Desired Behavior:** The SMTP configuration should be moved into its own card like the authentication cards (SAML, LDAP, Google). The remaining configuration should remain in the top-level email settings page.

![image](https://github.com/metabase/metabase/assets/22608765/0e7b1e6a-c548-4aa5-82c9-5d94b32fc54b)

**Value Proposition:** We no longer have two saving paradigms within one component, so admins are no longer confused if there changes were correctly saved.

```[tasklist]
### Acceptance Criteria
- [x] SMTP connection configuration moved into separate setup placed behind a configuration card
- [x] If SMTP is not configured, navigating to email settings auto-redirects to SMTP connection setup
- [x] After first time SMTP configuration, re-direct back to top-level email settings page to unveil further configuration options
- [x] All the original functionality behaves the same
- [x] ⚗️ Tests added to validate the behaviors above
```

---
**How to Verify the Issue**
1. Navigate to admin settings > settings > email
2. See that connection configuration changes require the clicking the `Save changes` button.
3. See that configuration changes besides the connection are auto-saved when edited

---
**Reference:**
- Slack discussion: https://metaboat.slack.com/archives/C505ZNNH4/p1690930241025789
- Figma designs: https://www.figma.com/file/kgV5rD58dH2LcKNtYuAwTm/Alerts-%26-Subscriptions-groups?type=design&node-id=331%3A7729&mode=design&t=Adwka3MswL4Cz4iF-1

**Comment by EmmadUsmani** [comment]
Closing this since it was an intentional change, let's continue the discussion about it on [slack.](https://metaboat.slack.com/archives/C505ZNNH4/p1690930241025789)

**Comment by luizarakaki** [comment]
These are the designs to fix it: https://www.figma.com/file/kgV5rD58dH2LcKNtYuAwTm/Alerts-%26-Subscriptions-groups?type=design&node-id=331%3A7729&mode=design&t=Adwka3MswL4Cz4iF-1
