### ISSUE TITLE
Dashboards with filters should reflect filtered values in the URL

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#3282]
When using a dashboard filter we reflect the chosen option in the url to make sharing easier. We should provide the same functionality with SQL params.

**Comment by tlrobinson** [comment]
@kdoh This is labelled for dashboards but I assume you're referring to the query builder?

**Comment by kdoh** [comment]
@tlrobinson We should probably do both, but what I was trying to get at here was that if you add dashboard filters those filter params should be reflected in the URL to make filtered dashboards easier to share. The issue title is kinda terrible at reflecting that in retrospect so I'll update it.

**Comment by kdoh** [comment]
Looks like this is working as intended.
