### ISSUE TITLE
Issue - e.dataset_query is undefined

### ISSUE THREAD

**Issue by jimmyh-onepilot** [metabase/metabase#32832]
**Describe the bug**
Since yesterday we cannot create simple queries such as a simple join (between Tickets and Customers for example).

**Logs**
See logs attachment after having attempted to save the query
![Capture d’écran 2023-08-02 à 11 08 09](https://github.com/metabase/metabase/assets/90448597/6b870b13-d9ee-44b4-bfc1-d04325958800)

**To Reproduce**
1. Create a question
2. Join two table Tickets and Customers 
3. Add a filter such as customers.name = 'Orpi' 
5. Save

**Expected behavior**
Metabase query should be saved

**Screenshots**
![Capture d’écran 2023-08-02 à 11 10 35](https://github.com/metabase/metabase/assets/90448597/229745df-93dd-4abf-ac12-93f51509e00a)

**Severity**
Very blocking, since we do need to create many queries to track our activity.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Ubuntu-0ubuntu120.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Ubuntu-0ubuntu120.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-131-generic",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-02-19",
      "tag": "v0.45.3",
      "branch": "release-x.45.x",
      "hash": "070f57b"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

**Comment by jimmyh-onepilot** [comment]
Admin > Troubleshooting > Logs
- Seems not to show any error regarding the save attempt

Thanks you in advance.

**Comment by Tony-metabase** [comment]
Can you try in incognito and also please upgrade to 0.46.6.4

**Comment by jimmyh-onepilot** [comment]
On it

**Comment by jimmyh-onepilot** [comment]
Fixed. Thx u so much @Tony-metabase.
