### ISSUE TITLE
Destructive SerDes functions like `seed-entity-ids` and `v2-load` are missing exclamation points in their names

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#32880]
The rules are easy, if the function has destructive side effects like modifying data in the app DB or writing files to disk, they should get exclamation points at the end of their names. This helps us know whether the functions are safe inside `^:parallel` tests or not, for example. Good hint: if the function is calling something that has a `!` in its name, it probably needs to have a `!` too.

There are a bunch of functions in the SerDes code that doesn't follow this rule:

* `metabase-enterprise.serialization.cmd/seed-entity-ids`
* `metabase-enterprise.serialization.cmd/v1-dump`
* `metabase-enterprise.serialization.cmd/v1-load`
* `metabase-enterprise.serialization.cmd/v2-dump`
* `metabase-enterprise.serialization.cmd/v2-load`
* `metabase-enterprise.serialization.dump/dump-dimensions`
* `metabase-enterprise.serialization.dump/dump-settings`
* `metabase-enterprise.serialization.dump/dump`
* `metabase-enterprise.serialization.dump/spit-entity`
* `metabase-enterprise.serialization.dump/spit-yaml`
* `metabase-enterprise.serialization.load/load-cards`
* `metabase-enterprise.serialization.load/load-collections`
* `metabase-enterprise.serialization.load/load-dashboards`
* `metabase-enterprise.serialization.load/load-dimensions`
* `metabase-enterprise.serialization.load/load-dimensions`
* `metabase-enterprise.serialization.load/load-fields`
* `metabase-enterprise.serialization.load/load-fields`
* `metabase-enterprise.serialization.load/load-pulses`
* `metabase-enterprise.serialization.load/load-settings`
* `metabase-enterprise.serialization.load/load`
* `metabase-enterprise.serialization.load/load`
* `metabase-enterprise.serialization.v2.backfill-ids/backfill-ids-for`
* `metabase-enterprise.serialization.v2.backfill-ids/backfill-ids`
* `metabase-enterprise.serialization.v2.load/load-deps`
* `metabase-enterprise.serialization.v2.load/load-one`
* `metabase-enterprise.serialization.v2.load/try-load-one`

These are just a few things I found after a cursory glance in the SerDes code... we should go thru it more thoroughly and fix all the stuff that should have `!` but doesn't

**Comment by bera5186** [comment]
Hey @camsaul I would like to work on this issue. Please assign it to me.
