### ISSUE TITLE
Table no longer selected for question

### ISSUE THREAD

**Issue by jstenquist** [metabase/metabase#3289]
### Bug Report Info

*  I'm using this browser:
   - [X] Chrome
*  My computer's OS is:
   - [X] OS X
*  I'm running Metabase:
   - [x] On AWS (via Docker)
* *Internally*, Metabase is using this database:
   - [X] Postgres
*  My data is in a database of this type:
   - [X] MySQL
*  I'm using Metabase version:
   - [X] 0.19.3

When we click to view any question, the query is performed and results returned, however the selected table, filters, grouping etc.. are not displayed. It appears one of the API calls is returning 500. This happens when we open any question.

![metabase_tables_bug](https://cloud.githubusercontent.com/assets/1971648/18138795/765f1cc6-6f7c-11e6-8d42-62121cacf84b.png)

**Comment by camsaul** [comment]
Hi @jstenquist, can you copy and paste the stacktrace from the API call that's failing? I can only see part of it in the screenshot.

**Comment by jstenquist** [comment]
Sure here it is

`{"message":"ERROR: syntax error at or near \"NULL\"\n  Position: 63","stacktrace":["db$query.invokeStatic(db.clj:368)","db$query.doInvoke(db.clj:364)","db$simple_select.invokeStatic(db.clj:427)","db$simple_select.invoke(db.clj:419)","db$select.invokeStatic(db.clj:673)","db$select.doInvoke(db.clj:666)","api.table$fn__24688$fn__24689.invoke(table.clj:87)","api.common.internal$wrap_catch_api_exceptions.invokeStatic(internal.clj:220)","api.common.internal$wrap_catch_api_exceptions.invoke(internal.clj:217)","api.table$fn__24688.invokeStatic(table.clj:81)","api.table$fn__24688.invoke(table.clj:81)","middleware$enforce_authentication$fn__24945.invoke(middleware.clj:79)","api.routes$fn__25075.invokeStatic(routes.clj:58)","api.routes$fn__25075.invoke(routes.clj:58)","routes$fn__30135.invokeStatic(routes.clj:24)","routes$fn__30135.invoke(routes.clj:24)","middleware$log_api_call$fn__25030$fn__25031.invoke(middleware.clj:264)","db$do_with_call_counting.invokeStatic(db.clj:337)","db$do_with_call_counting.invoke(db.clj:331)","middleware$log_api_call$fn__25030.invoke(middleware.clj:263)","middleware$add_security_headers$fn__24990.invoke(middleware.clj:200)","middleware$bind_current_user$fn__24949.invoke(middleware.clj:94)","middleware$wrap_current_user_id$fn__24936.invoke(middleware.clj:62)","middleware$wrap_api_key$fn__24956.invoke(middleware.clj:105)","middleware$wrap_session_id$fn__24929.invoke(middleware.clj:53)"]}`

**Comment by camsaul** [comment]
Hi @	jstenquist, I've merged PR #3291 which should address the issue you're seeing. It will ship as part of our next release (0.20) in the next few weeks.
