### ISSUE TITLE
Stacked Bar Chart - Redirect Issue

### ISSUE THREAD

**Issue by cyb3rplis** [metabase/metabase#32914]
### Describe the bug

If you have multiple series combined to a chart and click on one series, the redirection to the chart works fine.
If you go to options and **stack** the charts, the redirection to single chart is not working as it should.

![Screenshot 2023-08-03 at 17 53 28](https://github.com/metabase/metabase/assets/6849623/2628205e-7181-48fb-98db-aea289ab33d7)

The order of listed charts is not in the right direction. If you click on one chart, you will open another one that is also listed in the stacked chart.

![Screenshot 2023-08-03 at 17 52 21](https://github.com/metabase/metabase/assets/6849623/881e9da0-213f-4a5d-80e4-81cdaf97e6cc)

### Information about your Metabase installation

```JSON
- Tested with Chrome, Firefox and Safari
```

### Severity

Confusing

**Comment by paoliniluis** [comment]
version? reproduction steps?

**Comment by cyb3rplis** [comment]
Version: v0.46.6

Reproduction Steps:

1. Add new chart to dashboard
2. Click on "Edit Series"
![Screenshot 2023-08-06 at 22 05 50](https://github.com/metabase/metabase/assets/6849623/552eb5df-77a1-4252-981b-3ed85ad971e2)

3. Select at least two data
4. Click on "Visualization options"
![Screenshot 2023-08-06 at 22 07 18](https://github.com/metabase/metabase/assets/6849623/313570b0-82f3-4d95-9847-70d69583798b)

5. Stack charts
![Screenshot 2023-08-06 at 22 07 22](https://github.com/metabase/metabase/assets/6849623/c79ad6d0-be00-4f6c-b82c-6d60c390ca7d)

6. Click on on chart

**Comment by luizarakaki** [comment]
I couldn't repro this. As I click on the legend, I have the "View these" button. Not sure what's wrong.
