### ISSUE TITLE
Metabase Command Line Client

### ISSUE THREAD

**Issue by kqiu2** [metabase/metabase#3293]
I have Metabase running on the localhost, and it's connected to a database with a bunch of different tables. Is it possible for me to select which table to display raw data from solely using the terminal? If so, how? Essentially, I want to be able to do everything in Metabase without using the GUI at all.

**Comment by mazameli** [comment]
💔  😭

**Comment by kqiu2** [comment]
Umm are you expressing exasperation because this question has already been answered many times?

**Comment by mazameli** [comment]
Haha, no, I was joking 'cause @kdoh and I do all the GUI designing.

In all seriousness, no, I believe this is the first time we've ever heard this. A whole CLI to replace the GUI isn't something on our radar at all currently.

When you say "I want to be able to do everything in Metabase without using the GUI at all," it's really hard to envision how we would do things like displaying dashboards or visualizations. Maybe you could be more specific?

Are you wanting to do things like creating dashboards and adding cards to them without having to use the GUI? Is the use case just essentially that you live in the terminal, so it's annoying to have to log in to web app? If all you're trying to do is display tables' raw data, I'm honestly not sure why you're not just using the `mysql` command line.

**Comment by kqiu2** [comment]
Good point, I definitely wouldn't want to create dashboards (or do other relatively fancy stuff) without using the GUI. That sounds like a nightmare! 

But let's say I'm using the GUI, and I've submitted a new question whose result is displayed in the form of a bar chart. Now, is there a way for me to change the format of that result to a line graph from the command line? That is, I wanna type some command(s) in the terminal, and then the bar chart in the GUI should change into a line graph.

**Comment by camsaul** [comment]
@kqiu2 if you want to modify things in Metabase from the command line you basically have two options: 

1.  Connect the the Metabase database and use SQL
2.  Use CURL or something similar and modify things via our REST API.

I don't see us writing a dedicated command-line client for Metabase ourselves at any point in the near future but we'd gladly consider PRs from anyone who wants to give it a go themselves.

**Comment by bkryger** [comment]
So, I believe that a command line or config file is needed, I just had to create 77 new questions and 30+ new dashboards and will have to do it again There should be an easier way to do so, GUI is good but does not scale well. I would love to have scripted it, I tried to figure out the REST but it does not seem to be well documented and I spent too much time trying to figure out how to create a question.  Is there a REST guide maybe?    Also, being able to export the configurations of the questions and dashboards, maybe as JSON files would be useful for transferring, versioning (source code control), and backing up dashboards and questions.

**Comment by tlrobinson** [comment]
There's an issue for defining and documenting the public REST API here: #3663

In the meantime you can use the internal (not guaranteed to be stable) API the frontend uses: https://github.com/metabase/metabase/wiki/Using-the-REST-API and https://github.com/metabase/metabase/blob/master/docs/api-documentation.md

It's unlikely we'll provide a command line client ourselves, but it seems like a good opportunity for the community to contribute something.

**Comment by salsakran** [comment]
`I just had to create 77 new questions and 30+ new dashboards and will have to do it again ` 

@bkryger can you elaborate on what you're trying to do?
