### ISSUE TITLE
Query actions won't work when the ID dashboard parameter linked with model ID and action parameter get values from the URL

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#32974]
### Describe the bug

When linking an ID dashboard parameter with a model's ID and a query action's parameter and visiting the dashboard with parameter values in the URL. That action's linked parameter won't be sent with the action execute API request, even though the action form already hides the linked parameter which suggests that the action form is aware of the linked parameter value.

### To Reproduce

1. Create a dashboard
2. Add an ID filter
3. Add a model to the dashboard and link the ID parameter with model's ID field
4. Create an action that utilizes ID because we want to connect this with dashboard ID parameter e.g.
    ```sql
    UPDATE PRODUCTS SET PRICE = 999 WHERE ID = {{ id }}
    ```
5. Add that action to the dashboard and link action's `id` to the dashboard ID parameter.
6. Save the dashboard
7. Execute the action. When creating an action you could have more than 1 parameter, but only `id` is essential to this bug.

The action failed with an error
```
Error executing Action: Cannot run the query: missing required parameters: #{"id"}
```

![image](https://github.com/metabase/metabase/assets/1937582/914988a2-8c1c-4865-a22b-6589ff73e279)

### Workaround

Modifying the dashboard filter in the UI would make the action works.

### Expected behavior

The action is executed successfully.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "13.4.1",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-08-03",
      "src_hash": "824184da442e0fb2453a2bdf9d708d379c83339d",
      "tag": "v1.46.7-SNAPSHOT",
      "branch": "backport-dashboard-performance-fixes",
      "hash": "9d49a66"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Not good. Broken actions on dashboards.

### Additional context

<details>
<summary>
Original report
</summary>
Something broke in the Access Request tool.

Nothing about the actions or the dashboard have changed, to my knowledge, but now when someone tries to approve a request, the ID of the request is missing in the network call to the endpoint from the existing filter. What’s weird is when I added a new filter and set the ID (or ID1 in this case) filter manually and then tried to approve with the action form hooked up to that new filter, it worked.

<https://stats.metabase.com/dashboard/982-respond-to-request>

[— from Kyle's Slack Message](https://metaboat.slack.com/archives/C04FG88HL95/p1691155169655959?thread_ts=1691155169.655959&cid=C04FG88HL95)
</details>

**Comment by WiNloSt** [comment]
`git bisect` pointed out that this PR: https://github.com/metabase/metabase/pull/32470 caused this issue
