### ISSUE TITLE
Improve SQL Editor for readability

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#33002]
**Is your feature request related to a problem? Please describe.**
When starting a query in the Query Editor and then switching to SQL everything is a nightmare for an analyst. The naming conventions with the lengthy full table names is necessary I assume. But on top of that the formatting is horrible.

Current way SQL looks when switchting to SQL from graphic query builder:

```
SELECT `datamart.dim_users`.`id` AS `id`, `datamart.dim_users`.`customer_id` AS `customer_id`, `datamart.dim_users`.`first_name` AS `first_name`, `datamart.dim_users`.`last_name` AS `last_name`, `datamart.dim_users`.`email` AS `email`
FROM `datamart.dim_users`
LIMIT 1048575
```

**Describe the solution you'd like**
Ideal would be to use
a. table aliases
b. FORMATTING

result should look like as close as possible to this:

```
SELECT 
    t.id AS `id`,
    t.customer_id AS `customer_id`, 
    t.first_name AS `first_name`,
    t.last_name AS `last_name`, 
    t.email AS `email`
FROM datamart.dim_users t
LIMIT 1048575
```

**How important is this feature to you?**
Quite important. The time I lose reformatting to be able to understand anything is way to high.

**Comment by paoliniluis** [comment]
coming in v47
