### ISSUE TITLE
Parentheses in a filter break hover on data series

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#33018]
### Describe the bug

The following conditions cause the data element hover function to break:
* an SQL question is being visualized
* the query has a text or field filter
* the visualization is a multi-series chart, and the series consist of both line and bar display types
* the value entered for the filter contains parentheses.

### To Reproduce

1. Create the following SQL query on the sample db:
```
select source, state, count(*) as "count"
from PEOPLE
where ('anything' <> {{ text }} )
group by source, state
``` 
2. Leave the filter as text, and visualize the results as a combo chart.
3. Set the filter value to `something`, and hover on some data points. It works and the corresponding series is highlighted properly.
4. Set the filter value to `something (with parens)`, and try hovering again. The series highlight, and the data point pop-up  doesn't work.

### Expected behavior

Hovering should work regardless of the filter contents.

### Logs

Didn't find relevant frontend or backend logs.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v1.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

A customer has reported this issue, and I am not aware of a workaround at this time.

### Additional context

The issue exists in `v1.46.6.4` as well as on master, as of `0f3b3df`.

**Comment by luizarakaki** [comment]
![image](https://github.com/metabase/metabase/assets/32561114/6ff5516f-97a8-4099-856f-0d1482da9574)
@zbodi74 I couldn't repro it, did I do anything wrong?

**Comment by zbodi74** [comment]
@luizarakaki - the multi-series visualization has to have both line and bar display types for the issue to occur.
Pick combo chart for visualization or pick line chart and in Line options set one of the series to bar type manually.

**Comment by kulyk** [comment]
@zbodi74 hey, could you please check if you can still reproduce the issue? Not sure if I can after the echarts migration, so perhaps this is now fixed?

![CleanShot 2024-05-29 at 10 43 12@2x](https://github.com/metabase/metabase/assets/17258145/f09750e7-7a73-45b5-9151-829aaab13ef9)

**Comment by zbodi74** [comment]
@kulyk - thanks, I can no longer reproduce!

**Comment by zbodi74** [comment]
It can no longer be reproduced.
