### ISSUE TITLE
Code blocks nested inside list items in docs formattted incorrectly metabase.com (but not GH)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3302]
For some reason I think it doesn't like code blocks that are nested inside numbered list items. For example it looks fine [on GitHub](https://github.com/metabase/metabase/blob/master/docs/developers-guide-osx.md):

![screen shot 2016-09-02 at 3 24 52 pm](https://cloud.githubusercontent.com/assets/1455846/18219800/711002ca-7121-11e6-9665-6c9fea9e1657.png)

But [on metabase.com](http://www.metabase.com/docs/latest/developers-guide-osx.html) it looks strange:

![screen shot 2016-09-02 at 3 24 57 pm](https://cloud.githubusercontent.com/assets/1455846/18219813/869f7c7e-7121-11e6-887d-a02b56abb2c7.png)

Not sure how to fix this.

**Comment by salsakran** [comment]
@camsaul check out #3345

**Comment by camsaul** [comment]
Looks like this was fixed by #3348. I double-checked and everything is looking good on metabse.com 👍
