### ISSUE TITLE
Support native parameters in BigQuery

### ISSUE THREAD

**Issue by ralf-rf** [metabase/metabase#3303]
Hello!

First of all my compliments for your great work.
Im am connecting MetaBase to Google BigQuery. Template parsing seems to be disabled on the Native SQL questions. When I add something like:

`SELECT Count(*)
     FROM [test_export_query_to_table]
     WHERE 1=1
    [[AND event_type = {{var_event_type}}]]`

The query template doesn't get parsed. Resulting in the following BigQuery error:
`Encountered " "]" "[[AND event_type = {{var_event_type}}] "" at line 4, column 2. Was expecting: <EOF>`

Using the query-builder queries works as expected.

**Comment by camsaul** [comment]
Hi @ralf-rf, our BigQuery driver doesn't yet support SQL template variables. We're planning on adding support at some point in the future.

**Comment by ralf-rf** [comment]
Is there a great difference between let's say the MySQL implementation and BQ? If not, can I contribute for a solution?

**Comment by camsaul** [comment]
@ralf-rf it shouldn't be too big of a difference. If you're familiar with Clojure then give it a go 👍

**Comment by cwbeck** [comment]
Is there a rough ETA on this? We would love to start using this

**Comment by camsaul** [comment]
@cwbeck it's currently part of our 0.21.0 milestone so we're planning on shipping it with our next release in the next month or so.

**Comment by cwbeck** [comment]
@camsaul awesome news. incredible platform though!

**Comment by szymonm** [comment]
Hey guys, I'm a bit confused after removing this from roadmap. What are your plans?

**Comment by camsaul** [comment]
Hey everyone, thanks for your patience. While looking into a related bug I realized we forgot to enable this feature for BigQuery so I went ahead and did that in PR #3931. We're planning on shipping it as part of our 0.21.1 release in the next few days so you'll be able to use native params in your Big Queries very soon. 🎉 😊

**Comment by camsaul** [comment]
Implemented by #3931

**Comment by cwbeck** [comment]
Hi, are there any updates on this? It would seem BigQuery still does not support variables in queries?
