### ISSUE TITLE
Add documentation about running metabase from JAR file in the background

### ISSUE THREAD

**Issue by hugocar** [metabase/metabase#3304]
Not a bug, just a question who could eventually become a documentation improvement.

When I use `java -jar metabase.jar`, metabase runs as long as the console is not closed.
How can I make metabase run in the background and keep running when the console is closed ?

Using the following command works :

`nohup java -jar metabase.jar &`

**Comment by camsaul** [comment]
Hi @hugocar, I would generally recommend keeping the console visible so if you come across a bug or error you can copy the logs from the console and add it in the bug report you open for us 😉

**Comment by camsaul** [comment]
@hugocar if you want to submit a PR with the proposed changes to the dox we will consider them. As mentioned above there are reasons why we might not want to promote that behavior. But since the fix is so simple it makes more sense just to discuss it in a PR rather than have an open issue for it

**Comment by hugocar** [comment]
Hi Cam Saül,
Your comments raise questions :
- At this point, do you recommend against deploying metabase for production ? 
(the current absence of roles and permissions will probably force me to consider alternatives)

- How can one keep the console visible if metabase is running on a remote server ?
(I don't understand how it could work)

**Comment by mazameli** [comment]
> At this point, do you recommend against deploying metabase for production ?

No, there are plenty of folks using Metabase in production. :) One thing that we know is presenting a challenge for some users is the lack of data permissions, so we're currently working hard on that. #3088 is the work-in-progress PR for our first stab at permissions.

> How can one keep the console visible if metabase is running on a remote server ?
(I don't understand how it could work)

I think Cam just means that if something started acting strange in Metabase, you could always log in to the remote server and bring up the terminal to view the logs. But if you run Metabase in hidden mode, you won't have that option.

**Comment by tlrobinson** [comment]
@hugocar We don't provide detailed instructions for deploying Metabase on every environment because there are so many differences between environments (init vs systemd vs upstart etc).

Docker and Elastic Beanstalk are probably currently our most hardened/documented environments: http://www.metabase.com/docs/v0.19.3/operations-guide/running-the-metabase-jar-file.html

That said, I think it would be nice to provide more detailed instructions for some of the more common Linux distributions. Which distribution are you running?

**Comment by hugocar** [comment]
@mazameli 
Thank you for your answers !

@tlrobinson 
I m running on a AWS AMI instance which is not dedicated to metabase (to save costs).

I believe the nohup command works on every linux and mac but there might be a more clever way.
For instance, Mazameli is talking about how nohup causes losing the logs of metabase. Maybe there is an equivalent of pm2 (a process manager for node.js) for java.

**Comment by wihodges** [comment]
+1 for documentation of keep Jar running on Ubuntu 16.04.

**Comment by rodolfoviolac** [comment]
I used pm2 for it, works great!
