### ISSUE TITLE
Query API

### ISSUE THREAD

**Issue by kqiu2** [metabase/metabase#3305]
On the ReadMe, it says that "Metabase also allows you to hit our Query API directly from Javascript." Could someone explain how to do this? If you have a demo, even better.

**Comment by camsaul** [comment]
Hi @kqiu2, we already have an open issue for this: #2689. I'd recommend reading through the comments on that thread since they explain how to use the API. Feel free to ask further questions about using the API in that thread.

Closing as duplicate.
