### ISSUE TITLE
[MLv2] Column not found errors when joining cards

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#33083]
We have two failing E2E tests on the [joins FE branch](https://github.com/metabase/metabase/pull/32912) when a BE now returns an error when running a query with joined cards:

```
Column "Question 5 - Products → Created At: Month.CREATED_AT" not found;
SQL statement: ...
```

**Failing tests**

⚠️ Please use the [joins FE branch](https://github.com/metabase/metabase/pull/32912) to reproduce the error

- [should join two saved questions with the same implicit/explicit grouped field (metabase#18512)](https://github.com/metabase/metabase/blob/master/e2e/test/scenarios/joins/reproductions/18512-cannot-join-two-saved-questions-with-same-implicit-explicit-grouped-field.cy.spec.js)
- [should join saved questions that themselves contain joins (metabase#12928)](https://github.com/metabase/metabase/blob/master/e2e/test/scenarios/joins/joins.cy.spec.js)
- [shouldn't drop joins using MLv2 format (metabase#31769)](https://github.com/metabase/metabase/blob/master/e2e/test/scenarios/joins/reproductions/31769-mlv2-join-dropped.cy.spec.js)

**Comment by camsaul** [comment]
This test is still failing on the joins branch

https://github.com/metabase/metabase/blob/db5ecb9c7ca961128aae7b502bbb6658bc74abe8/e2e/test/scenarios/joins/reproductions/31769-mlv2-join-dropped.cy.spec.js
