### ISSUE TITLE
X ray cards load bottom to top

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#33085]
### Describe the bug

As @WiNloSt noticed, it seems that the x-ray cards load bottom to top in the `release-x.47.x` AND `master` while they load top to bottom in all previous releases. I mistakenly reported that this happens on 47 release branch only. The title is fixed now.

### To Reproduce

1. Create an ad-hoc question Orders, summarized by average of Total, grouped by Products Category
![image](https://github.com/metabase/metabase/assets/31325167/9019dca2-42fd-4e35-bc85-ce52d69cc6c8)
2. Visualize and click on any of the four bars
3. Choose "Automatic insights" from a popover
![image](https://github.com/metabase/metabase/assets/31325167/2d952fc5-c256-4cdd-98b2-bd313695b4e1)
4. The choose either "x-ray" or "compare to the rest" (the latter is better because it will generate more cards so this effect will be more pronounced)
5. Observe the network tab and notice a bunch of `POST /api/dataset` responses but the top cards are still showing spinning circles
6. If you scroll to the bottom of the page, you'll see that those cards are already painted
![image](https://github.com/metabase/metabase/assets/31325167/d5b2f8f5-9292-43de-9a5a-1baf1a05d2e0)

### Expected behavior

Cards should populate top to bottom.

### Information about your Metabase installation

```JSON
`Metabase v0.47.0-RC3` JAR file with H2 app db.
```

### Severity

P2

### Additional context
Confirmed working top to bottom in 46.7 and bottom to top in `master` and `release-x.47.x`, so this is a regression.

**Comment by NevRA** [comment]
Additional context https://metaboat.slack.com/archives/C056QEW4KNF/p1691759927140699
