### ISSUE TITLE
Select a table dropdown doesn't allow going back to schema selection screen

### ISSUE THREAD

**Issue by diwu1989** [metabase/metabase#3309]
This is on v19.3, using Chrome 53
in postgres, if I have multiples schemas, I get to pick a schema first
![image](https://cloud.githubusercontent.com/assets/380950/18228864/78c60ae2-7215-11e6-813b-d725650c0b34.png)

After clicking on a schema, I can get stuck on the next screen and have no way of going back to the schema selection screen
![image](https://cloud.githubusercontent.com/assets/380950/18228851/361bd802-7215-11e6-8480-5884edc3f3b2.png)

The only workaround I have is to refresh the entire page

**Comment by kdoh** [comment]
Hey @diwu1989. In theory you should be able to click on "Analytics Warehouse" in the second screenshot you added to go up a level to the entire list of schemas. Let me know if that wasn't working or if it just wasn't obvious.

**Comment by kdoh** [comment]
Sorry just re-read this and saw you mentioned neither is working.

**Comment by mazameli** [comment]
This is fixed on master, and I think was resolved by #3229, but to make 100% sure, we'd have to connect a DB w/ schemas to our 0.19.3 test instance (cc @tlrobinson). On our 0.19.3 instance, we still have that phantom up chevron that doesn't do anything, which #3229 definitely resolves:

![screen shot 2016-09-07 at 1 38 13 pm](https://cloud.githubusercontent.com/assets/2223916/18327657/66624f80-7500-11e6-975a-8d124160342e.png)

**Comment by diwu1989** [comment]
hi, when do you guys expect 0.20.0 to be released? I see that the milestone is past due in github, we're heavy users of schemas and would love to run 0.20.0 (vs grabbing master and running master), however, if 0.20.0 isn't gonna be done anytime soon, we'd have to resort to running master

**Comment by kdoh** [comment]
Hey there @diwu1989. I can't put a definite date on it just yet, but we're hoping 0.20 will be avaliable in the next couple of weeks. Permissions (#3362) is one of our most requested features and is a large part of our 0.20 release, so we want to make sure the experience is as solid as we can make it for v1, which  means we're taking the time to make sure that's right.

In general, we don't recommend running off of master for production, but if it's a big enough need for you, it _might_ make sense. If you end up going that route let us know how it goes. Thanks a ton for your patience.

**Comment by diwu1989** [comment]
0.20 is released, thanks!!!

**Comment by diwu1989** [comment]
sorry re-opening this ticket, even on 0.20, i dont see this fixed
