### ISSUE TITLE
New Question button should always reset the question page

### ISSUE THREAD

**Issue by diwu1989** [metabase/metabase#3310]
There's not a easy way to reset the new question screen, especially if I've already picked a table, and then realized that I need to use raw sql mode, right now the only way to reset the state is to refresh the page

![image](https://cloud.githubusercontent.com/assets/380950/18228877/f3aa5966-7215-11e6-8b51-f147cf550236.png)

**Comment by mazameli** [comment]
Ah, you're right that if you haven't run the query, clicking `New Question` doesn't currently reset the page. Seems like it should.

Incidentally, if you mention realizing you need to use raw SQL mode after you've selected a table — you can actually do that. Just click the SQL mode button in the top-right. You can even switch databases once you're in that mode. Hope that helps.

I think I might change the title of this issue to propose that the `New Question` button should always reset the question page.

**Comment by mazameli** [comment]
@kdoh says he believes this is a regression.

**Comment by kdoh** [comment]
Yeah this definitely used to work the way @diwu1989 would like. My guess is there was a bug we missed in the switch over to redux for all the routing.

**Comment by tlrobinson** [comment]
This was resolved at some point.
