### ISSUE TITLE
Bug: Query caused webpage formatting Issues + causes crashing

### ISSUE THREAD

**Issue by ShmuelTreiger** [metabase/metabase#3311]
-  I'm using this browser: Chrome
-  My computer's OS is: Windows
-  I'm running Metabase: On Microsoft Azure
- _Internally_, Metabase is using this database: H2 [I'm pretty sure, I never changed this setting]
-  My data is in a database of this type: Postgres
-  I'm using Metabase version: 0.19.3

I changed the secondary x variable in a certain query's line graph which caused metabase to crash. Metabase cannot seem to run this query with this without crashing. Simultaneously, the formatting went all screwy in chrome (it still looks normal in firefox) even when this query isn't being run. (This query still crashes the webpage in firefox, even though it doesn't mess up the formatting.)

This ultimately leads to three issues:
1) the weird formatting which I can't seem to fix,
2) I can't load the dashboard which contains this query in order to remove the query and salvage the dashboard (archiving the query didn't remove it from the dashboard) and
3) because the query crashes the browser before it loads, I can't access the query's line graph settings in order to fix the graph and salvage the query (if I catch it fast enough I am able to cancel the query and access the code and was thus able to save the code to create a new query)

Attached are two photos which demonstrate the weird formatting, though it manifests itself in numerous ways.

My apologies if I should have submitted this as separate issues.

![formatting 2](https://cloud.githubusercontent.com/assets/14131043/18233907/a44bb4e4-72fd-11e6-9671-e3f403f819d6.png)

![formatting](https://cloud.githubusercontent.com/assets/14131043/18233897/65314404-72fd-11e6-993f-d01e27ac75c4.png)

**Comment by mazameli** [comment]
Sorry you're having trouble! Can you give us any more nonsensitive details about your query? E.g., is it GUI-based or SQL-based? Is it using filtering or grouping, and if so, what types of fields are you filtering/grouping on (timestamp, numeric, etc.)? What kind of aggregation(s) are you doing? Are you doing any joining, etc.?

**Comment by ShmuelTreiger** [comment]
SQL based. The actual query is below,  but to specify: user_id is integer, campaign_name/name is varchar, group is varchar, and sent_at is timestamp. I believe those are the only things filtered or grouped by. The only aggregate function I use here is MAX and I've got one join in there.

The formatting issue seems to have solved itself, though it was really weird while it lasted. The other two issues persist (though 3 isn't terribly critical, since I was able to salvage the code). It would be great if there's some way to fix issue 2, since I'd really rather not have to rebuild the dashboard from scratch.

`SELECT t.user_id AS user_id,
t.campaign_name AS campaign_name,
(CAST (SUM(t.hot) AS FLOAT) / (SUM(t.cold) + SUM(t.hot))) as percent_hot,
MAX(t.sent_at) as sent_at
FROM
	(SELECT email_campaigns.user_id AS user_id,
	email_campaigns.name AS campaign_name,
	CASE
		WHEN sent_emails.group NOT LIKE '%cold%' THEN COUNT(sent_emails.psuid)
	END AS hot,
	CASE
		WHEN sent_emails.group LIKE '%cold%' THEN COUNT(sent_emails.psuid)
	END AS cold,
	MAX(email_campaigns.sent_at) as sent_at
	FROM email_campaigns
	LEFT OUTER JOIN sent_emails
	ON email_campaigns.user_id = sent_emails.user_id AND email_campaigns.campaign_id = sent_emails.campaign_id
	WHERE {{user}}
	[[AND {{campaign}}]]
	GROUP BY email_campaigns.user_id, email_campaigns.name, sent_emails.group
	HAVING COUNT(sent_emails.psuid) > 50
	[[AND MAX(email_campaigns.sent_at) > {{start_date}}]]
	[[AND MAX(email_campaigns.sent_at) <= {{end_date}}]]
	ORDER BY email_campaigns.user_id, email_campaigns.name) AS t
GROUP BY t.user_id, t.campaign_name
ORDER BY user_id, sent_at`

**Comment by tlrobinson** [comment]
@ShmuelTreiger Do you know if this is still an issue in more recent versions of Metabase? I've never seen anything like it, and can't figure out how to reproduce it. If you run into it again could you tell me if there are any errors in your browser's developer tools / JavaScript console?

**Comment by ShmuelTreiger** [comment]
I haven't updated Metabase in while, but I do know that I somehow solved the issue. I think I used firefox to delete the question. I also seem to recall that I came to the conclusion that the bug was caused by having a resource intensive subquery and I have since avoided those. Given that this was 6 months ago, I'm not sure how accurate my recollections are, sorry.

**Comment by tlrobinson** [comment]
@ShmuelTreiger Ok thank you. I'm going to close this for now, but let us know if you run into it again.

**Comment by ShmuelTreiger** [comment]
That's fine. Thank you.
