### ISSUE TITLE
Metabase REST API?

### ISSUE THREAD

**Issue by pgensler** [metabase/metabase#3314]
Hello,

Recently I just came across your product, and was wondering if you guys have thought of allowing some sort of API so we can use Metabase to generate charts with R or python? I think it would be extremely beneficial, as there are not that many packages for integration with R for business intelligence purposes. Thanks for your time.

**Comment by camsaul** [comment]
Hi @pgensler, you can use Metabase's REST API to run queries from R or Python and then do anything you want with the results.

Take a look at the discussion in this issue for an idea how : #2689

**Comment by camsaul** [comment]
Since Metabase does have a REST API, albeït a underdocumented one, I'm going to go ahead and close this as a duplicate. @pgensler we have an open issue to better-document the REST API: #2689

**Comment by salsakran** [comment]
@pgensler was this in the context of calling MB from R/Python or calling out to R/Python from MB?

**Comment by pgensler** [comment]
@salsakran will do. I have not seen any packages that currently provide a gateway, but I would definitely be open to talking about possible ways to access the API.

**Comment by flrngel** [comment]
With my needs, I wrote some code in python for metabase api.

https://github.com/STUnitas/metabase-py

**Comment by apinstein** [comment]
I built a new R package today called [metabaser](https://github.com/apinstein/metabaser). Thanks to the updated API docs I was able to get this working pretty quickly!

This is my first R package, so I am sure it's got all kinds of R syntax problems, but... it works!

Would love to have any feedback!

<img width="1435" alt="screen shot 2018-05-27 at 10 31 17 pm" src="https://user-images.githubusercontent.com/34889/40594536-c2f365b8-61fd-11e8-82db-d6a214a1a3f0.png">

**Comment by salsakran** [comment]
@apinstein that's awesome =)

We're super interested in ways to make R + Metabase work better together. There's a lot of heavy lifting in analytics that imo isn't within scope of Metabase itself, that is probably better done with R.

**Comment by apinstein** [comment]
Thanks! I'd love to get more use of this by others. Are you aware of any other GH issues or other places to let people know it exists?

**Comment by pgensler** [comment]
Looking over the API docs, is it possible to support normal SQL queries? I am thinking something along the lines of the way this API is setup:
https://apidocs.data.world/api/datasets/getdataset

**Comment by bashsebbash** [comment]
Few years late on this thread but here's a function I wrote that should help the next person to stumble to this page.

```
import requests
import pandas as pd

def run_metabase_query(query, database = 47):
    s = requests.Session()
    endpoint = 'your_endpoint'
    auth_url = f'{endpoint}/api/session'
    username = f'xxx'
    password = xxx
    g = s.post(auth_url , json = {"username":username
                           , "password":password
                           })
    query= {
      "database": database,
      "type": "native",
      "native": {
        "query": query
      }
    }
    res = s.post(f'{endpoint}/api/dataset', 
                  headers = {'Content-Type': 'application/json',
                            },
                  json= query
                )
    names = [x['display_name'] for x in res.json()['data']['results_metadata']['columns']]
    df = pd.DataFrame(res.json()['data']['rows'])
    df.columns = names
    return df
```
