### ISSUE TITLE
Support text section in pulse

### ISSUE THREAD

**Issue by drorm** [metabase/metabase#3315]
When sending a pulse I'd like to add a text section both on top and before certain section explaining the chart/table.  
An alternative would be to add an optional text section as part of each question in the pulse.

Example:

This is a weekly report showing visits to our website last week ....

Chart 1
Chart 2
The following chart shows the number of visitors per day
Chart 3
Chart 4

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ChenDogg** [comment]
I really think this would enhance the quality perception and functionality of pulses, taking them from purely functional to user friendly. 

I would also suggest the ability to include **images**, so you could do things like include client logos or your organization's logo.

**Comment by sharedphysics** [comment]
+1 to both (I clicked the thumbs). 
Not being able to include text (even as a preface) means that I can't provide context around the data nor point the recipients on where to go to see a full dashboard.

**Comment by flamber** [comment]
Closing this is favor of #15744, which will be available in 0.41.
Pulses are being deprecated in favor of Dashboard Subscriptions.
