### ISSUE TITLE
Make the delete button appear as default on the archive

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33180]
**Is your feature request related to a problem? Please describe.**
The delete button is hidden and you need to know where it is. It makes sense to make it appear by default

**Describe the solution you'd like**
Make the delete button to appear without hover in the archive

**Describe alternatives you've considered**
NA

**How important is this feature to you?**
NA

**Additional context**
NA

**Comment by luizarakaki** [comment]
It is now in a more prominent, but not too prominent place:

![image](https://github.com/metabase/metabase/assets/32561114/88e8a87a-d051-4f68-af7c-77303ece47aa)

**Comment by luizarakaki** [comment]
#
