### ISSUE TITLE
Header and HeaderBar duplicate item title and description logic.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#3318]
While working on #3317 I noticed there's a fair amount of duplication between `Header` and `HeaderBar` in terms of how they render titles, and I wasn't entirely sure of the distinction. It'd be nice to either have one `Header.jsx` to rule them all or a cleaner way of determining Title and Description content.

**Comment by flamber** [comment]
Closing, since there's no `HeaderBar` anymore and too much code has changed.
