### ISSUE TITLE
Field filters in BigQuery will only work if you use backticks on the table names

### ISSUE THREAD

**Issue by rodolphoya** [metabase/metabase#33183]
**Describe the bug**
When creating a new field filter, mapped on Metabase by using the native SQL questions.
It presents an error when running the query 

Datasource: BigQuery

**Logs**

> 400 Bad Request POST https://www.googleapis.com/bigquery/v2/projects/<< MY PROJECT >>/queries { "code" : 400, "errors" : [ { "domain" : "global", "location" : "q", "locationType" : "parameter", "message" : "Unrecognized name: `prod_activation.movimentos` at [5:20]", "reason" : "invalidQuery" } ], "message" : "Unrecognized name: `prod_activation.movimentos` at [5:20]", "status" : "INVALID_ARGUMENT" }

**To Reproduce**
1. Go to a new SQL native question
2. add a {{variable}} in the code
    

> WHERE {{data_de_cadastro_titulo}}

3. Set the variable as Field Filter and find the field among the tables
4. Set the variable type as Date Filter
5. Mandatory = NO
6. Default Value = not set
7. add a date in the question filter
8. run the query
9. See the error

**Expected behavior**

**Screenshots**
![image](https://github.com/metabase/metabase/assets/5187006/4290ef91-5456-46c2-8bf0-b8a546c6100e)
![image](https://github.com/metabase/metabase/assets/5187006/b31d437f-552e-4765-a6b2-5793e2f3e294)

**Severity**

I could not create more filters on my Dashboard. This was requested by my Customer

**Additional context**

Looking at Metabase SQL output
![image](https://github.com/metabase/metabase/assets/5187006/cb0ea7de-8e94-4aa9-86b7-a99a18104eee)

the only way that I got to run this was by removing the dataset and tablename form the date_trunc, generated by Metabase

Instead of this
> WHERE date_trunc(`prod_activation.movimentos`.`data_de_cadastro_titulo`, day) BETWEEN date "2023-08-06"
   AND date "2023-08-12"

Running this
> WHERE date_trunc(`data_de_cadastro_titulo`, day) BETWEEN date "2023-08-06"
   AND date "2023-08-12"

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "4.4.0",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-06",
      "tag": "v0.46.7",
      "branch": "release-x.46.x",
      "hash": "cfdf23b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
you're missing the backticks on the table name

**Comment by Tony-metabase** [comment]
FYI https://www.metabase.com/learn/sql-questions/field-filters#:~:text=BigQuery%2C%20back%20ticks%20are%20needed

**Comment by rodolphoya** [comment]
It worked. thanks!

Question: Was this instruction already there and I missed it, or did you just add it to the docs?

**Comment by Tony-metabase** [comment]
Always there :)
