### ISSUE TITLE
Question name not displayed when changing click behavior

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#33192]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6830683/2f44f2bc-996b-46e5-a9a5-9fdd65a0158a)

It used to work like this: [image](https://github.com/metabase/metabase/assets/6830683/bc325a75-c119-472d-8efc-843eeb81fc2e)

### To Reproduce

1. Create a question (e.g. Reviews - Summarized by Count by CreatedAt: Month) and save it to a dashboard
2. Edit the dashboard
3. Click "Click behavior" button for the question
4. Select any column
5. Select "Go to a custom destination"
6. Click "Link to" > "Saved question" button
7. Choose any question

### Expected behavior

Selected question's name is displayed in "Link to" button.

Probably it should already be displayed in step 4 - not sure.

### Information about your Metabase installation
847bc00b37

### Severity

P2

### Additional context

Found when working on #17879

**Comment by WiNloSt** [comment]
This has been broken since https://github.com/metabase/metabase/issues/30763
