### ISSUE TITLE
Add unit(time, data volume etc...) formatting in chart settings

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3321]
Often our database contains some value in the smallest unit for example microseconds or bytes. This result in long number such as 1232343245234 microseconds. 
It would be great if we could set the unit in a chart and have it converted to minute or hours for readability reasons. Also we can automatically edit the axes. You can look at how Grafana does it for example.

**Comment by salsakran** [comment]
That sounds very useful indeed. 

@camsaul this is another use of the new type system #2663

**Comment by flamber** [comment]
Closing in favor of #7039/#12057
