### ISSUE TITLE
Disabling Google OAuth locks Google login users out

### ISSUE THREAD

**Issue by underyx** [metabase/metabase#3323]
*  I'm using this browser: Chrome
*  My computer's OS: OS X
*  I'm running Metabase: via Docker
* *Internally*, Metabase is using this database: Postgres
*  I'm using Metabase version: 0.19.3

## Steps to Reproduce

1. As admin, enable Google Sign-In
2. As user, sign in via Google
3. As admin, disable Google Sign-In
4. Of course, user can't sign in anymore, so as user, ask for a password reset
5. **Password reset tells user to sign in with their Google account, can't set an actual password**
6. As admin, delete the user account
7. As admin, invite the same user again
8. **The 'invite' email is actually the same email as in step 5**

**Comment by salsakran** [comment]
So in terms of fixing this, I'm of the opinion that really offending step is 6->7 not resulting in a new user, but rather re-activating the old user. I think we don't do a good enough job of distinguishing between re-enabling a previously exiting user and creating a new one. 

Imo, the immediate fix for this is --   When re-enabling a user manually, clear the GA created bit and send them a normal email.

@kdoh + @camsaul thoughts?

**Comment by kdoh** [comment]
Yeah I'd agree with that. Sounds pretty good to me.

**Comment by camsaul** [comment]
Fixed by #3461
