### ISSUE TITLE
[FR] Don't load Google analytics if not asked

### ISSUE THREAD

**Issue by narcisgarcia** [metabase/metabase#33233]
**Is your feature request related to a problem? Please describe.**
Metabase web portal seems to load google-analytics.com content by default.

**Describe the solution you'd like**
Any 3rd party component to be an option, deactivated by default.

**Describe alternatives you've considered**
To not remove 3rd party components, but only load them if administrator asks explicitly to be enabled; not by default.

**How important is this feature to you?**
Need to show how clean and safe is Metacity to trust it as a secure software.

**Additional context**
Day after day, 3rd party components are perceived as tracking and non-legitimate data collectors.

**Comment by paoliniluis** [comment]
if you don't opt for tracking, then we don't load GA, please check the code and also check how the app behaves when you not enable tracking
