### ISSUE TITLE
What's new notification frontend

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#33230]
Epic: [Provide a heads up when Metabase is upgraded](https://github.com/metabase/metabase/issues/33165)

From the technical point of view, this is how we'll decide if we need to show the notification:
- get the versions list from version-info
- we filter out all versions < of the last acknowledged (if not null)
- we filter out all versions > of the current version
- from the remaining, we get the last version that has a releaseNotesUrl and link to that page

# Testing plan:

## Dimensions:
- is the app in a full embed
- last acknowledged version (null or present)
- presence of a releaseNotesUrl before, inside, and after the range described above

## Actions
- dismiss notification
- click `What's new?` link
- ignore notification and change page/reload page

### Unit/Integration

- [x] if the app is in full embed context => nothing is shown
- [x] links have `_target="blank"` attribute
- [x] if a releaseNotesUrl is present in the range (last ack, current] => show the banner
- [x] if two releaseNotesUrl are present, the last one (more recent) is used
- [x] if the releaseNotesUrl is present but on a version bigger than the current, it is ignored
- [x] if the releaseNotesUrl is present, but on a version already acknowledged, it is ignored

### E2E
- [x] new major update flow
  - user opens metabase and notification shows up
  - user refreshes the page -> notification still there
  - user dismiss the notification -> notification hides
  - user refreshes the page -> notification not shown
- [x] multi user support
  - user A logins
  - user A dismiss notification
  - user B logins
  - -> should see notification

**Comment by ranquild** [comment]
@npretto 

`kind of upgrade, minor, major/gold etc` - we need to take into account:
- minor, patch releases
- upgrades > 1 major version at a time
- downgrades, with a downgrade to >1 major version

`has the user already dismissed the notification` 
- it looks like an extension of the previous testing dimension, e.g. dismissed here means that the current version is equal to one used for the notification, e.g. it's a "no-op" upgrade.

`presence of the release notes url in version-info`
- and presence/absence of the entry itself
