### ISSUE TITLE
[FR] Don't require 'unsafe-inline' for CSP's script-src

### ISSUE THREAD

**Issue by narcisgarcia** [metabase/metabase#33232]
**Is your feature request related to a problem? Please describe.**
Some secured environments require a strict CSP-SOP setup for website. And site reputation concerns too.

**Describe the solution you'd like**
Move all inline javascripts to files.

**Describe alternatives you've considered**
(none found) In the meanwhile, document on all setup guides this 'unsafe-inline' requirement.

**How important is this feature to you?**
Need to clean unsafe code from many web applications and sites, so many people need to trust them.

**Additional context**
Strict CSP-SOP is one of the well-known guarantees today for any web.

**Comment by paoliniluis** [comment]
it's being removed, in fact the PR is about to get merged

**Comment by narcisgarcia** [comment]
> in fact the PR is about to get merged

Do you mean it's in roadmap for next version? No patch reference?
Thank you.
