### ISSUE TITLE
Pie charts cut off in dashboard

### ISSUE THREAD

**Issue by CarolynMooney** [metabase/metabase#33267]
### Describe the bug

In a dashboard, when pie charts are a certain size and the sidebar is closed and then re-opened, the charts get cut off on the right side, and a bit on the bottom as well.
This started happening since we upgraded to v1.47.0.

### To Reproduce

1. Create a dashboard, and add three pie charts. Do not resize them.
3. Save the dashboard.
4. Hide the sidebar, then open it again. The pie charts are cut off strangely.

### Expected behavior

The charts should be resized to fit within the tile.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.15.107+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v1.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": "Europe/Amsterdam"
    }
  }
}
```

### Severity

This is mostly just annoying, as it looks strange and might be confusing to new users.

### Additional context

<img width="1071" alt="Screenshot 2023-08-17 at 15 51 58" src="https://github.com/metabase/metabase/assets/95698893/027eeca8-bc54-4d04-a8a0-e24a296bf849">

**Comment by darksciencebase** [comment]
if it turns out to be big and hairy, stop and leave it for after the migration
