### ISSUE TITLE
Unable to load metabase UI - Upgrade from 0.46.6.4 -> 0.47.0

### ISSUE THREAD

**Issue by mmarcoux09** [metabase/metabase#33275]
### Describe the bug

When going to my login page, it simply breaks, white page.

![image](https://github.com/metabase/metabase/assets/83434552/5384c0f7-d9b3-4cbe-80a1-01e7ca4dc5e5)

Upgraded from 0.46.6.4 to 0.47.0

### To Reproduce

1. Go to 'https://metabase.hisports.app'
2. See error white page.
![image](https://github.com/metabase/metabase/assets/83434552/9e291e58-4404-4d3b-bde5-7857882cced9)

### Expected behavior

See login page

### Logs

Uncaught TypeError: r[e] is undefined
    Webpack 8
bootstrap:25:1
    Webpack 8

### Information about your Metabase installation

```JSON
Any Browser
Any System
Metabase 0.47.0
Postgres 12
Docker image
```

### Severity

Critical

**Comment by cidraljunior** [comment]
Try reloading without cache: Ctrl + Shift + R

**Comment by paoliniluis** [comment]
Please purge the CDN cache...
