### ISSUE TITLE
[FR] Don't require 'unsafe-eval' for CSP's script-src

### ISSUE THREAD

**Issue by narcisgarcia** [metabase/metabase#33276]
**Is your feature request related to a problem? Please describe.**
Some secured environments require a strict CSP-SOP setup for website. And site reputation concerns too.

**Describe the solution you'd like**
Change all function definitions by calls to javascript files with functions.

**Describe alternatives you've considered**
(none found) In the meanwhile, document on all setup guides this 'unsafe-eval' requirement.

**How important is this feature to you?**
Need to clean unsafe code from many web applications and sites, so many people need to trust them.

**Additional context**
Strict CSP-SOP is one of the well-known guarantees today for any web.

(Related to #33232)

**Comment by paoliniluis** [comment]
this has been addressed in https://github.com/metabase/metabase/pull/33188
