### ISSUE TITLE
Ability to filter cumulative sums post-aggregation

### ISSUE THREAD

**Issue by bjeanes** [metabase/metabase#3328]
I have a cumulative sum metric which counts the number of users in the database.

I graph this aggregate over time by a `created_at` field to display basically the user growth over time. However, if I filter this by time, the accumulation starts from 0 from the start of time range. This of course makes sense if I think about the implementation, but it would nice to be able to differentiate between these two circumstances, expressed below as SQL:

``` sql
-- equivalent to what Metabase does now
SELECT date_trunc('week', created_at)::date AS created_at
     , sum(count(*)) OVER (ORDER BY date_trunc('week', created_at)::date) AS sum
FROM users
WHERE created_at >= '2016-01-01'
GROUP BY 1
ORDER BY 1 ASC
```

and

``` sql
-- what I'd like to do
SELECT created_at, sum
FROM (
    SELECT date_trunc('week', created_at)::date AS created_at
         , sum(count(*)) OVER (ORDER BY date_trunc('week', created_at)::date) AS sum
    FROM users
    GROUP BY 1
    ORDER BY 1 ASC
) users
WHERE created_at >= '2016-01-01'
```

I know I can create my own query doing this, however that has another limitation that I ran into. That is, if I want to parameterise this along-side other visualisations on a dashboard for the same time range, I'd have to use a field filter like so:

``` sql
SELECT created_at, sum
FROM (
    SELECT date_trunc('week', created_at)::date AS created_at
         , sum(count(*)) OVER (ORDER BY date_trunc('week', created_at)::date) AS sum
    FROM users
    GROUP BY 1
    ORDER BY 1 ASC
) users
WHERE 1=1 [[ AND {{created_at}}]]
```

Unfortunately, that doesn't work. Based on the logs, I believe this to be because the field filter is outputting a fully-qualified field name (e.g. `"public"."users"."created_at"`) and that field does not correspond to anything accessible from within that scope. Arranging things so that the filter is expressed with a `HAVING` statement and dropping the outer query does not present the correct results.

An option for making this work with custom SQL queries might be letting Field Filters be bound to custom fields (e.g. so that I could explicitly say `"created_at"` instead of letting it inject `"public"."users"."created_at"`). <strike>If this seems worthwhile, I can create an issue for this.</strike> #3324 proposes a solution along these lines.

**Comment by c-schmitz** [comment]
Alternatively the culmination/filter could be done directly on the result set so it behaves more like a "zoom in" on a date range on the existing full dateset.

**Comment by flamber** [comment]
Closing in favor of #3324
Related to #4509/#3156

**Comment by taiyangc** [comment]
> Alternatively the culmination/filter could be done directly on the result set so it behaves more like a "zoom in" on a date range on the existing full dateset.

I am looking for an exact feature like this, a way to filter without having to re-run with query with the date range.
Looking at the issues mentioned above succeed this request, none of them is requesting it. I wonder why?
