### ISSUE TITLE
Custom fields in data model

### ISSUE THREAD

**Issue by bjeanes** [metabase/metabase#3329]
A very common custom field I use is displaying prices as dollars. We store prices everywhere as cents but on most charts/graphs we'd display as dollars. If I define many of the key datapoints we're interested in as Metabase Metrics, I can't define or use custom fields here and nor can I post-process them in Questions or on Dashboards to display as dollars.

It'd be great to be able to add calculated/custom fields _in general_ to the data model and then use them everywhere, including metrics, segments, and questions.

**Comment by camsaul** [comment]
Hi @bjeanes, we have a couple issues that are already open and similar to what you're asking, so I'm going to close this as a duplicate.

#1522 is for supporting special "currency" types for fields.
#3398 is for adding the ability to add custom fields / precalculated new columns that can be used anywhere.
