### ISSUE TITLE
Ability to combine different graph types on single graph

### ISSUE THREAD

**Issue by bjeanes** [metabase/metabase#3330]
Certain graph types could conceivably be plotted on the same chart. For instance, this chart (which I have defined in Google Sheets) can not currently be constructed in Metabase:

![screen shot 2016-09-08 at 1 12 15 pm](https://cloud.githubusercontent.com/assets/2560/18335880/07be4b70-75c6-11e6-9da7-1d40346409a8.png)

Obviously not any graph type can be arbitrarily combined, but at least Line, Bar, and Area charts could conceivably be rendered together.

**Comment by moumny** [comment]
From what i've seen, this type of graphs is very popular among users in my company.

**Comment by rbhalla** [comment]
When adding multiple graphs on top of each other in the dashboard view, I would intuitively expect line charts and bar charts to stack on top of each other as visualised above.

**Comment by jgerstle** [comment]
Any updates on this? The fact that this is lacking might prevent us from using this tool

**Comment by marbetschar** [comment]
Would also highly appreciate this 😍

**Comment by jordanbenkov** [comment]
We'd love to see this too!

**Comment by sksembhi** [comment]
+1. Combo charts are key to any BI tool.

**Comment by jinchener** [comment]
Looking forward to this, too.

**Comment by gvohra** [comment]
+1, this is holding us back from switching off a competing service and fully migrating to Metabase

**Comment by tlrobinson** [comment]
I've just pushed an work in progress PR at #8541 with this and a lot of other things
