### ISSUE TITLE
how to connect aws rds instance to metabase db

### ISSUE THREAD

**Issue by j87596745432** [metabase/metabase#33313]
### Describe the bug

I was attempting to follow along with the instructions on this topic by reading through the guide (listed here: https://www.metabase.com/docs/latest/databases/connections/aws-rds ) but it stops at step 4. What is the user supposed to do after step 4? In other words, once the user has the correct metadata of the rds instance (like the endpoint, etc.), what do they do with that info in metabase? 

### To Reproduce

1. Go to https://www.metabase.com/docs/latest/databases/connections/aws-rds
2. Follow steps 1-4
3. ???

### Expected behavior

I expected there to be some kind of step 5 showing what to do with the information gathered in step 4

### Information about your Metabase installation

```JSON
I don't have this info available right now
```

### Severity

Medium severity as I can't add external DBs

**Comment by paoliniluis** [comment]
go to settings->admin->databases and add the db there
