### ISSUE TITLE
Visualization does not recover from an error in native query editor

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#33327]
### Describe the bug

Once native query can't be visualized, user can't recover from the error without leaving the page.

Video taken using 0.47.6:

https://github.com/user-attachments/assets/2dbc5918-d015-4705-9471-bb1a0c936027

### To Reproduce

1. Create new SQL query using sample db
2. set the visualization and check "detail"
3. Set the query to `select 1;` and run it - you'll get a number visualization
4. Change the query to `select --1;` and run it - you'll get a visualization error
5. Change the query back to `select 1`; and run it
Visualization error is still shown

### Expected behavior

Number visualization is shown

### Information about your Metabase installation

f0dd90e64b, v47

### Severity

P3

**Comment by likeshumidity** [comment]
Related to https://github.com/metabase/metabase/issues/32609 (improper parsing of `--`)
