### ISSUE TITLE
Driver: ClickHouse

### ISSUE THREAD

**Issue by Slach** [metabase/metabase#3332]
Metabase is great tool for Visualization and http://clickhouse.yandex is great database for analytics

Could anybody add support for https://github.com/yandex/clickhouse-jdbc in Metabase ?

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
Hi @Slach @fatum @onexdrk, we're adding support for various DBs based on community demand. Since you're the first people to ask for this DB, that might be a while 😉 

If you're familiar with Clojure and feeling adventurous you can try [writing a driver yourself](https://github.com/metabase/metabase/wiki/Writing-A-Driver). I'm available to help with any questions you might run into.

**Comment by Badya** [comment]
@camsaul can you provide some contacts to ask you questions?

**Comment by camsaul** [comment]
@badya feel free to ask right here on this thread I'll try to help answer anything you might run in to.

**Comment by burdiyan** [comment]
@Badya seems like you started implementing the ClickHouse driver. Do you have any update on that? Thanks!

**Comment by Badya** [comment]
I encountered an issue https://github.com/yandex/clickhouse-jdbc/issues/59 and postponed implementation

**Comment by lloonngg** [comment]
I am also looking for ClickHouse support in Metabase.  I quickly surveyed the open source bigdata sql solutions out there including ones with GPU backends and ClickHouse seems to be one of the easiest to implement, has respectable performance, and has a track record for scalability.  We are curious to see ClickHouse works in Metabase compared to GreenPlum.

**Comment by freeseacher** [comment]
there are probably no news on ch support. yep ?

**Comment by onexdrk** [comment]
👍

**Comment by Stephane-Thales** [comment]
Any news on the Metabase support of clickhouse ?

**Comment by alijorani** [comment]
I'm also interested in ch support.

**Comment by jackpgao** [comment]
Maybe you can try this way.

Now ProxySQL has supported ClickHouse as backend, you can visit ClickHouse using the MySQL way.

Up to now, there is still some limits of using ClickHouse, such as the user and password, and the ProxySQL is hard coded to visit local ClickHouse.

**Comment by ei-grad** [comment]
Maybe someone could implement Clickhouse driver for its REST interface? https://clickhouse.yandex/docs/en/interfaces/http_interface.html

Doesn't look to need much effort if someone is familar with metabase driver interfaces?..

**Comment by ei-grad** [comment]
Just to clarify - clickhouse-jdbc also uses the HTTP interface of Clickhouse.

**Comment by jonatasfreitasv** [comment]
Plz!!!!!!!

**Comment by jornh** [comment]
Sorry `not-camsaul` but, https://github.com/metabase/metabase/search?q=clj-http.client&type=Code says Druid and Presto (if you look for `/driver/**.clj`) 

Also note #7047 - in particular https://github.com/metabase/metabase/pull/7047#issuecomment-371413483 mentioning:

> One interesting possibility is using this as a "base class" (like the generic sql driver) for other REST APIs. Stripe is one that comes to mind.

**Comment by jonatasfreitasv** [comment]
Nice @jornh thx a lot.

**Comment by sundy-li** [comment]
+1 for clickhouse support !!!

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by zeronewb** [comment]
fyi, alternative driver:
https://github.com/housepower/ClickHouse-Native-JDBC

**Comment by tsl-karlp** [comment]
I just submitted a PR and I could use some help testing: #8491

**Comment by BlankRain** [comment]
> fyi, alternative driver:
> https://github.com/housepower/ClickHouse-Native-JDBC
```
[{:type java.sql.SQLFeatureNotSupportedException
   :message nil
   :at [com.github.housepower.jdbc.wrapper.SQLConnection getMetaData SQLConnection.java 69]}]
 ```
clickhouse-native-jdbc may not works until it has some more sql feature supported.

**Comment by ei-grad** [comment]
I still in doubt that using JDBC connectors to ClickHouse is a good idea since ClickHouse could be a bit too far from the RDBMS for Metabase, but I'll give it a try.

**Comment by faibistes** [comment]
When can we expect this feature, even if it is a bit rough?

**Comment by Seb-SK** [comment]
Hi,

Would it be possible to have a quick recap of what remains to be done on this, vs what has already been done with #8722 ? I'm a little lost between the two issues ;)

Thanks !

**Comment by enqueue** [comment]
PR #9469 is filed and open for critique; tests are currently green. But MetaBase team is very busy, and there are probably many more important issues to take care of, or many other PRs that give the reviewers less headaches :wink:  You can checkout the branch, start MetaBase, and connect with your ClickHouse dev / test environment. Please comment on the PR or create an issue in my fork. I will try  to incorporate any feedback, and also rebase the branch on Master once in a while.

**Comment by pengfei-xue** [comment]
mark

**Comment by pomazanbohdan** [comment]
https://github.com/ClickHouse/clickhouse-jdbc/

**Comment by filimonov** [comment]
https://github.com/enqueue/metabase-clickhouse-driver

**Comment by skaboy007** [comment]
Unfortunately, thir is no enthusiasm on the thread no more yet the combination of Metabase and click house is one of the most useful things I encountered in the Opensource space in recent years. incredible performance. this is a call out to all contributors your work is much appreciated. and a general question what can we non-contributers do to drive up the community?

**Comment by The-Alchemist** [comment]
> Unfortunately, thir is no enthusiasm on the thread no more yet the combination of Metabase and click house is one of the most useful things I encountered in the Opensource space in recent years. incredible performance. this is a call out to all contributors your work is much appreciated. and a general question what can we non-contributers do to drive up the community?

@skaboy007 : you might wanna look at https://redash.io/.  Different UI than Metabase, but has Clickhouse support OOTB.

**Comment by skaboy007** [comment]
> > Unfortunately, thir is no enthusiasm on the thread no more yet the combination of Metabase and click house is one of the most useful things I encountered in the Opensource space in recent years. incredible performance. this is a call out to all contributors your work is much appreciated. and a general question what can we non-contributers do to drive up the community?
> 
> @skaboy007 : you might wanna look at https://redash.io/. Different UI than Metabase, but has Clickhouse support OOTB.

Nahh in the UX nothing beats Metabase

**Comment by ohld** [comment]
Is there any plans to merge the Clickhouse support for Metabase?

**Comment by dannyeuu** [comment]
@camsaul I think now has a lot of people that are trying to use Clickhouse, and has this project that has the plugin https://github.com/enqueue/metabase-clickhouse-driver can be merged?

**Comment by shushenghong** [comment]
> Is there any plans to merge the Clickhouse support for Metabase?

+1

**Comment by skaboy007** [comment]
Hi just wanted to point out, no relevant driver for 0.38 due to driver change https://github.com/metabase/metabase/wiki/What's-new-in-0.38.0-for-Metabase-driver-authors
and we are really excited about 0.38

**Comment by alexey-milovidov** [comment]
Here is the tutorial to connect ClickHouse to Metabase: https://clickhouse.com/docs/en/connect-a-ui/metabase-and-clickhouse/
This issue can be closed.

PS. ClickHouse has been moved to a separate company and is no longer associated with Yandex.

**Comment by dannyeuu** [comment]
@flamber, @brunobergher and @luizarakaki this issue can be closed right?

**Comment by paoliniluis** [comment]
@dannyeuu we’ll close it as soon as we bundle the driver in the cloud so we can ping our customers
