### ISSUE TITLE
Dangling expression reference left after removing an expression used in a join

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#33335]
### Describe the bug

In the notebook editor, if a join condition uses a custom column and this column is removed, the condition keeps referencing a now missing column.

### To Reproduce

1. New > Question > Raw Data > Sample Database > Orders
2. Add a custom column `[User ID] + 1` and call it CC
3. Join People on CC = People.ID
4. Remove CC

**Actual behavior**
Metabase 46 and 47: the join still has the CC column reference
`master`: the FE crashes

**Expected behavior**

The join or its condition gets removed

### Information about your Metabase installation

`master`, reproduces on Metabase 46 and 47

### Severity

Low / Medium — a join condition will be removed right before running a query

**Comment by lbrdnk** [comment]
Reproducible on 47.2 but on master [d419e9a](https://github.com/metabase/metabase/commit/d419e9acc4109c59878f4b6fc51a86e23f7dc051).
