### ISSUE TITLE
Selecting a dashboard filter while questions are loading does not apply the filter

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3333]
Steps to reproduce:

Open a dashboard
Before the questions finish loading, select a filter
See that when the questions finish loading, they are loaded without the filter and do not change.
Expected behavior:
When I choose a filter, I would expect the questions to reload so that what is displayed always match the chosen filter.

From http://discourse.metabase.com/t/selecting-a-dashboard-filter-while-questions-are-loading-does-not-apply-the-filter/683/1

**Comment by fimpfimp** [comment]
**I'm using this browser:**
Chrome

**My computer's OS is:**
Mac OSX

**I'm running Metabase:**
On AWS

**Internally, Metabase is using this database:** 
Don't know

**My data is in a database of this type:**
Postgres and MySQL

**I'm using Metabase version:**
0.19.2

**Comment by fimpfimp** [comment]
Any news on when this can be scheduled in?

**Comment by gschlect** [comment]
This is similar to #6645 -- both mean that it's difficult to be confident in query results, especially if you change filters a couple times.
