### ISSUE TITLE
Removing a custom column doesn't remove dependent aggregations

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#33336]
### Describe the bug

In the notebook editor, if an aggregation uses a custom column and this column is removed, the aggregation becomes something like "Average of nil" instead of being removed.

### To Reproduce

1. New > Question > Raw Data > Sample Database > Orders
2. Add a custom column `abs([Discount] - [Total])` and call it CC
3. Add an aggregation like "Average of CC"
4. Remove CC

**Actual behavior**
Metabase 46: the aggregation is removed
`master` and 47: the aggregation becomes "Average of nil"

**Expected behavior**

The aggregation is removed

### Information about your Metabase installation

`master`, reproduces on Metabase 47

### Severity

Low / Medium — an aggregation can be removed manually

**Comment by lbrdnk** [comment]
Issue is reproducible on 47.2 but not on master [d419e9a](https://github.com/metabase/metabase/commit/d419e9acc4109c59878f4b6fc51a86e23f7dc051).
