### ISSUE TITLE
[MLv2] Tweaks and missing methods for native editor conversion

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#33346]
**Tweaks to native extras**

1. #33543
2. #33545
3. #33546

**Missing methods**

There're a few MLv1 methods the editor uses that'd be nice to port to MLv2 as well

* #33547
* https://github.com/metabase/metabase/issues/33548
* https://github.com/metabase/metabase/issues/33549

**Comment by camsaul** [comment]
I've split this out into 6 separate issues and added it them the Native epic, so I'll go ahead and close this out
