### ISSUE TITLE
Values of URL-typed fields should be clickable

### ISSUE THREAD

**Issue by cetra3** [metabase/metabase#3334]
At the moment, the URL field type doesn't seem to do anything:

http://discourse.metabase.com/t/hyperlink-in-table/421

I've noticed the same thing when testing. 

When a database column has entries like:
- https://example.com/test
- http://whatever.biz

This should resolve to a clickable link, especially if you've set the field type to URL.

**Comment by mattxbart** [comment]
I've been struggling to get this to work as well. I'm using 0.19.3, postgresql 9.5 and setting the type to URL but nothing happens. Tried setting it with multiple field types (text, varchar) but nothing works. It saves the metadata info correctly in the admin screen but nothing happens with the UI views. This would be a great feature if it worked.

**Comment by camsaul** [comment]
@cetra3 @mattxbart we don't currently do anything special with URL fields. In the future we'll probably do something like what you're describing and make values of URL fields clickable.

**Comment by camsaul** [comment]
Related: #3103

**Comment by cetra3** [comment]
@camsaul is this in your roadmap currently, or would you be willing to accept a PR to have this included? It'd be a simple change to implement to make it clickable.

**Comment by camsaul** [comment]
@cetra3 We just had a pow-wow and we're adding this to our roadmap for our 0.21.0 release 👍

**Comment by tlrobinson** [comment]
@metabase/core-developers Are there any design considerations for this?

* Show links in tables and object detail for columns marked as URLs
* Probably with `target=_blank`
* Probably a good idea to try parsing the URL and only linkify it if it's a valid URL

Anything else?

**Comment by cetra3** [comment]
If we're going with `target=_blank` might I suggest including `rel="noopener"` : https://dev.to/ben/the-targetblank-vulnerability-by-example

Other stuff on my wishlist:

* Have the URL compress down to an icon or similar if the card is running out of room
* Ability to create URL columns with the Custom Field function and some string concatenation.

**Comment by tlrobinson** [comment]
@cetra3 Thanks. I've gone ahead and done that, as well as whitelisted `^(https?|mailto):` protocols, which I think should be sufficient to prevent XSS since React doesn't evaluate HTML or anything like that, but please let me know if I'm wrong.

**Comment by cetra3** [comment]
React will automatically escape any html/javascript that you pass in as a jsx value unless you explicitly [set it](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml) so I think we're safe from that angle.

The only other consideration is the regex may be a bit too restrictive on URLs, and may need to include our friend `ftp` :)
