### ISSUE TITLE
Redshift shared databases are not correctly supported

### ISSUE THREAD

**Issue by DAlperin** [metabase/metabase#33343]
### Describe the bug

The top level is **Metabase does not support introspecting the schema of redshift shared dbs**.

Here is my understanding of the issue:

 Metabase uses the jdbc connector for redshift. The entrypoint to where redshift collects info about the schemas is [here](https://github.com/metabase/metabase/blob/59d727d74686e853492da4b328ef2cf6f6c2c590/src/metabase/driver/sql_jdbc/sync/describe_database.clj#L32). It calls the `getSchemas` JDBC method (implemented for redshift [here](https://github.com/aws/amazon-redshift-jdbc-driver/blob/610cfe4dbc47d0db985f5312919ce727c8ada990/src/main/java/com/amazon/redshift/jdbc/RedshiftDatabaseMetaData.java#L1941)). Redshifts `getSchemas` implementation has two paths based on whether or not the connection is for a single database (as in no shared databases). The default connection option is true so it [only pulls schemas in the current db](https://github.com/aws/amazon-redshift-jdbc-driver/blob/610cfe4dbc47d0db985f5312919ce727c8ada990/src/main/java/com/amazon/redshift/jdbc/RedshiftDatabaseMetaData.java#L5351) (in my case called stripe1). Thankfully metabase allows custom JDBC connection options, so I set `databasemetadatacurrentdbonly=false`. But that leads to another problem. Now that we are in the correct branch of `getSchemas` in the redshift driver it runs [this query](https://github.com/aws/amazon-redshift-jdbc-driver/blob/610cfe4dbc47d0db985f5312919ce727c8ada990/src/main/java/com/amazon/redshift/jdbc/RedshiftDatabaseMetaData.java#L1965) which outputs results like:
```
| information_schema | stripe1
| pg_catalog         | stripe1
| public             | stripe1
| pg_catalog         | dev
| public             | dev
| information_schema | dev
| stripe_testmode    | stripe_shared
| stripe             | stripe_shared
```
so we can see the `stripe` and `stripe_testmode` schemas from the `stripe_shared` database. Metabase [filters all the schemas](https://github.com/metabase/metabase/blob/master/modules/drivers/redshift/src/metabase/driver/redshift.clj#L342) based on whether the current user has permission using the `HAS_SCHEMA_PRIVILEGE` redshift function. The problem is it ends up executing `SELECT HAS_SCHEMA_PRIVILEGE('stripe', 'USAGE');` and `SELECT HAS_SCHEMA_PRIVILEGE('stripe_testmode', 'USAGE');` but the `HAS_SCHEMA_PRIVILEGE` function operates only on the current database (`stripe1`) so the query errors because `stripe` or `stripe_testmode` are not schemas on `stripe1`. So metabase need to consider the database name and not just the [schema name](https://github.com/metabase/metabase/blob/59d727d74686e853492da4b328ef2cf6f6c2c590/src/metabase/driver/sql_jdbc/sync/describe_database.clj#L34) for the sake of generating the list of schemas.

### To Reproduce

Add a redshift database with shared databases. 

### Expected behavior

It should correctly introspect the schema.

### Logs

https://gist.github.com/DAlperin/04a33272db22400800867458922fb346

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.15.49-linuxkit-pr",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

This is blocking our evaluation of metabase entirely. The core financial data we need analyzed is in a shared redshift database so we can't get around this.

**Comment by paoliniluis** [comment]
How similar is this to https://github.com/metabase/metabase/issues/15083

**Comment by DAlperin** [comment]
@paoliniluis ah very similar sorry, I didn't see that. I disagree with the characterization in that issue that all thats needed is the JDBC param but otherwise the spirit is the same.
