### ISSUE TITLE
Pie chart wedge hover incorrectly displays total for wedges smaller than 0.30%

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#33342]
### Describe the bug

When a pie chart has a wedge lower than 0.30%, the total for that wedge is incorrect.  In this example, the pie chart is counting items so only whole numbers should appear.   The total for the the wedge appears as a number with a fraction:
<img width="960" alt="image" src="https://github.com/metabase/metabase/assets/22856340/61f85435-8347-4f26-8fbe-2fb340eb7f57">

The count is accurate in the raw data:
<img width="267" alt="image" src="https://github.com/metabase/metabase/assets/22856340/80a396cb-8a2e-42c3-a4b6-b3b1317fc70e">

### To Reproduce

1.  Go the the sample data
2. Join orders to the people table 
3. Summarize count by State
4. Filter on the following states: AK, AL, CA, CO, DE, IA, MN, NY, RI, TX, WI
5. Create a pie chart
6. Notice how the DE wedge is showing 21.81 instead of 21

### Expected behavior

The hover should show accurate numbers

### Information about your Metabase installation

```JSON
I replicated this on master.  A user also reported this on 1.46.6.4 in discourse:  https://discourse.metabase.com/t/pie-chart-displaying-wrong-number/26246
```

### Severity

No workaround, also correctness issue.

### Additional context

Reported by at least two users in discourse.  See https://metaboat.slack.com/archives/C013N8XL286/p1692374122920169 for an example.

**Comment by Sultan91** [comment]
Is there are any solution for this?

**Comment by ixipixi** [comment]
This might be related to https://github.com/metabase/metabase/issues/32430.

Potential work around: modifying the minimum slice value on the chart until your smallest wedge is greater than 0.30%
