### ISSUE TITLE
Reordering columns in a question re-runs the query with every drag and drop

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#33347]
### Describe the bug

When iterating on a question in table view, reordering columns results in the query being unnecessarily re-run. This makes the entire process very slow if you want to arrange the table columns in a specific way.

### To Reproduce

1. Create a question with data from sample database: orders joining products, select only a subset of the table fields
2. In the table view, start rearranging the columns of the table. You sometimes need to rearrange a few columns for the query to be re-run
3. When tested locally the query re-runs quite fast, but on stats it is quite slow to render every time.

Tested with hash bec9c95 on stats

### Expected behavior

When re-arranging the columns the query should not re-run as long as we are not changing the sorting criteria

### Information about your Metabase installation

```JSON
- Chrome 115.0.5790.170 (Official Build) (arm64)
- Mac OS X 13.4.1 (c) (22F770820d)
- Tested with hash bec9c95 on stats
```

### Severity

Low

**Comment by npfitz** [comment]
I'm having a hard time reproducing this locally, but in stats, [this question](https://stats.metabase.com/question/4859-active-pro-ee-customers-completing-4-months-this-week) does re run the query on every re-order

**Comment by alxnddr** [comment]
@albertoperdomo @npfitz I could not reproduce this even on [this question](https://stats.metabase.com/question/4859-active-pro-ee-customers-completing-4-months-this-week) in stats, so it appears to be fixed
