### ISSUE TITLE
Card click behavior drops interface component overrides in FullApp embedding

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#33379]
### Describe the bug

In interactive embedding navigating from card to another dashboard via Click Behavior causes interface component overrides to be lost. This looks like a regression of [24756](https://github.com/metabase/metabase/issues/24756).

[Screen recording](https://github.com/metabase/metabase/assets/11080638/ba8c0fd3-0d11-4868-9289-795ae05e8016)

### To Reproduce

1. Create a dashboard with a card that has Click Behavior to another dashboard (regular Dashboard, not Custom URL)
2. View via FullApp embedding, where initial iframe src has overrides (e.g. .../?top_nav=false)
3. Click the card to go to the other dashboard, after browser load, it will now show the other dashboard, but without the overrides.

### Expected behavior

Overrides should be kept on the second dashboard.

### Logs

n/a

### Information about your Metabase installation

```JSON
Metabase version: 1.46.x - 1.47.0 .
```

### Severity

This has been reported by a customer.

### Additional context

I reproduced the issue with releases between `1.46.0` and `1.47.0`. 1.45.4.3 appears to be the last release without the bug.

**Comment by paoliniluis** [comment]
wait, did you use the url parameters in the iframe location?

**Comment by williamkaper** [comment]
We reported the issue, and yes we set the parameters in the iframe src: Here is the snipped from the page we embedded it on (domain obfuscated)
 
<iframe id="metabase-frame" src="https://metabase.****.com/auth/sso?redirect=https%3A%2F%2Fmetabase.******.com%2Fdashboard%2F1-trial-balance-auditability%253Fheader%253Dfalse%2526logo%253Dfalse%2526breadcrumbs%253Dfalse"

**Comment by christianbpedersen** [comment]
We have the same problem. Ideally I would like the setting to be part of the JWT token so users can't tamper with it and change the parameters to get the menus back. From there, it should be part of the user's session for its entire duration.

**Comment by WiNloSt** [comment]
Gotta delve deeper, but this basically has something to do with [Open absolute urls not relatively to a metabase instance](https://github.com/metabase/metabase/pull/27097#top).

Now when we're navigating to saved questions and dashboard we're not navigating using client router, but we open the link like opening a new page/tab, this clears all the cached redux state which stores the embed settings.

**Comment by WiNloSt** [comment]
@paoliniluis Should that become a project so engineers could discuss it in more detail? Right now the way I see serving any application in a subpath would have a problem (there could be more problems I'm not aware of) when we're navigating to absolute versus relative path, this would affect literally every navigation, so we still have to go through every place that works with URLs anyway whether or not we're gonna introduce something more systematic or fix them ad-hoc.

This issue in particular seems to be an effect from the said issue https://github.com/metabase/metabase/pull/27097. Metabase should be smarter even if navigating to an absolute URL, but if the path they're going is the same as the SITE_URL, then it should prefer router navigation instead of loading a new page.

**Comment by albertoperdomo** [comment]
Some ideas, probably crazy or stupid?

>this clears all the cached redux state which stores the embed settings

1. could we persist these? I get that there would be a challenge for when it's desired to honor the cached settings vs not
2. what about appending the current params when opening the absolute URLs so that they are always carried over?

**Comment by albertoperdomo** [comment]
@christianbpedersen I work with Metabase as the product manager for embedding. Thanks for the suggestion.
I've created https://github.com/metabase/metabase/issues/36112 to track it.
