### ISSUE TITLE
Unable to replace a SQL based question after modifying when you're the owner

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#3337]
Browser: Chrome 52 on Mac OS 10.11
Metabase: latest master (both locally and on our AWS env)

Steps to reproduce:
- Create yourself a SQL question and save it.
- Change some part of the query or visualization. 
- Try saving again with the intention of updating the question.
- The modal defaults to replace but you're unable to save.
- Go to another user's question and try to change and then update. You'll be able to save this time.

**Comment by mkrcah** [comment]
Same here.

Browser: Chrome 53 and Firefox 48 on Mac OS 10.11 
Metabase: latest docker image `metabase-head` (commit `37878ca`)

**Comment by tlrobinson** [comment]
@kdoh I'm unable to reproduce this. Is it still present on `master` / stats?

**Comment by kdoh** [comment]
@tlrobinson Just tried again on stats and master and it seems like this was resolved. 👍
