### ISSUE TITLE
Dashboard dropdown menu should close when you click outside of it

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3338]
Right now it's remaining open unless you click the menu button again, even if you navigate elsewhere, which is crazy annoying. It should behave like the Account Settings/Logout menu.

![screen shot 2016-09-09 at 12 42 37 pm](https://cloud.githubusercontent.com/assets/2223916/18400531/3521cf68-768b-11e6-8e1d-5829440b00c8.png)

**Comment by kdoh** [comment]
I poked at this a bit this morning. I couldn't exactly figure out why but it looks like unlike other components that use `<OnClickOutsideWrapper />` the DashboardDropdown component's handleDismissal method never gets called.
