### ISSUE TITLE
Card alert won't render on master

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33382]
### Describe the bug

We have a regression where table card won't render in a slack alert

Card 12874, channel "Cancellation Survey Responses for Alert"

### To Reproduce

See above

### Expected behavior

alerts should render correctly

### Logs

NA

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

**Comment by darksciencebase** [comment]
Duplicate of https://github.com/metabase/metabase/issues/33279

**Comment by paoliniluis** [comment]
thank you!
