### ISSUE TITLE
Dashboard PDF Export using API

### ISSUE THREAD

**Issue by lihan** [metabase/metabase#33393]
**Is your feature request related to a problem? Please describe.**

I need to use API to export dashboards to the PDF format

**Describe the solution you'd like**

Add an dashboard PDF export API (https://www.metabase.com/docs/latest/api/dashboard)

**How important is this feature to you?**

This feature helps wider team to access the dashboards when they do not have accounts.

**Comment by paoliniluis** [comment]
PDF exports of dashboards are currently a Frontend thing, I think what you need is https://github.com/metabase/metabase/issues/28547, please confirm
