### ISSUE TITLE
Dashboard filter not attached to a card still causing the card to be reloaded

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3339]
Reproduction steps
1. Create a "count of rows by time" for the users table
2. Create a "count of rows by time" for the orders table
3. Add both to a dashboard
4. Create a category filter and wire it to the orders by time card
5. Save the changes
6. Pick a category from the drop down

The users by time card is not greyed out.

This is on MB OS X Version 0.19.3

**Comment by tlrobinson** [comment]
Fixed by #3481
