### ISSUE TITLE
Don't offer to create models or use nested questions on 3rd party drivers which don't support it

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33401]
### Describe the bug

A customer hit a bug while trying to create models on the Teradata driver, which doesn't allow nested queries https://github.com/swisscom-bigdata/metabase-teradata-driver/blob/d4418055cb5d78e2bbc460f078e3a472a1d11908/src/metabase/driver/teradata.clj#L392

We shouldn't have offered that option from the beginning

### To Reproduce

Use a driver which does not support nested queries, and create a model or a nested question

### Expected behavior

We should simply hide those options if the driver does not support it

### Logs

NA

### Information about your Metabase installation

```JSON
I think this has been like this since the beginning of the times
```

### Severity

P3

**Comment by kamilmielnik** [comment]
> Don't offer to create models

It should still be possible to create models from raw data - @paoliniluis can you please confirm?

----

Related: #28908

**Comment by paoliniluis** [comment]
@kamilmielnik what do you mean?

**Comment by kamilmielnik** [comment]
Slack discussion for reference: https://metaboat.slack.com/archives/C01LQQ2UW03/p1699454495848059
