### ISSUE TITLE
Up and Down Slider

### ISSUE THREAD

**Issue by magdylabanMP** [metabase/metabase#33417]
**Is your feature request related to a problem? Please describe.**
It is very hard to scroll though the result if it's add to a dashboard so I have to just use right and left arrows.

**Describe the solution you'd like**
Instead of right and left arrow you may create a slider to scroll up and down so it would be more easy to explore a result in the dashboard.

**Describe alternatives you've considered**

**How important is this feature to you?**
Medium 

**Additional context**
![Capture](https://github.com/metabase/metabase/assets/126151672/7d32b0bf-5205-4fd0-bbbb-3cb7103146a9)

**Comment by paoliniluis** [comment]
sorry, what you mean is sort of an infinite scroll on the tables?

**Comment by magdylabanMP** [comment]
Actually, yes 
you may check the image for more explanation 
![metabase](https://github.com/metabase/metabase/assets/126151672/d8aa8802-6a08-4cb7-8d8f-10c46f1a7b06)

**Comment by paoliniluis** [comment]
Duplicate of https://github.com/metabase/metabase/issues/7842
