### ISSUE TITLE
Cross-origin request

### ISSUE THREAD

**Issue by kqiu2** [metabase/metabase#3344]
I want to send an HTTP request to the server I'm running Metabase on. Where in the source code would I add the "Access-Control-Allow-Origin" header to enable cross-origin requests? Because otherwise, I'll get an error that says:

`XMLHttpRequest cannot load http://localhost:3000/api/dataset. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://XXXXXXXX' is therefore not allowed access. The response had HTTP status code 401.`

Thanks!

**Comment by camsaul** [comment]
Hi @kqiu2, you can tweak the `Content-Security-Policy` header that you'll find [here](https://github.com/metabase/metabase/blob/master/src/metabase/middleware.clj#L145) to meet your needs.

**Comment by camsaul** [comment]
If tweaking `Content-Security-Policy` doesn't meet your needs you can modify the `api-security-headers` function below that to add arbitrary headers as needed. Please keep in mind that there are security implications when enabling CORS.

**Comment by kqiu2** [comment]
@camsaul If I modify `api-security-headers` to enable cross-origin requests but the settings in `content-security-policy-header` forbid them, which will override which?

**Comment by camsaul** [comment]
Not sure off the top of my head, but you should be able to find that information by poking around the net. 

I'm not clear on what it is you're trying to do but if you're running into a CORS error it sounds like you might be trying to hit the Metabase API from a different web page not served up the Metabase server? In that case the `Content-Security-Policy` shouldn't affect you since we only attach it to Metabase's `index.html`.

**Comment by camsaul** [comment]
Sorry didn't mean to close that pressed the wrong button

**Comment by kqiu2** [comment]
Well, I think I've managed to allow cross-origin requests now, since I'm no longer getting the `Response to preflight request doesn't pass access control check` message. However, I'm still getting this "unauthorized" error despite passing in a valid token for my `x-metabase-session` header:

`Failed to load resource: the server responded with a status of 401 (Unauthorized)`

On the other hand, if I disable web security in Chrome, the request goes through without a problem. I've tried replacing the the `x-metabase-session` header with `Cookie` (and setting it to `metabase.session_ID=XXXXXX`), but it "refused to set unsafe header 'Cookie,'" so that results in a 401 error as well. It actually refuses to set the Cookie header even if I disable web security.

So, do you know what parameters I have to use to avoid the "unauthorized" error? To give you some more background, I'm doing this by including an AJAX request in an HTML file, and then opening it with Chrome or Safari.

**Comment by camsaul** [comment]
`X-Metabase-Session` should just be the ID. Check out the example `curl` request in this thread to get a sense of how it should work:

https://github.com/metabase/metabase/issues/2689

**Comment by kqiu2** [comment]
Yeah, the ID is what I'm putting in for `x-metabase-session`. I don't have any problem executing curl commands, so I'm not sure why I'm running into this "unauthorized" error for the equivalent AJAX request. Here's what my code looks like, if that helps:
```
<!DOCTYPE html>
<html>
<head>
<script src="jquery-3.1.0.js"></script>
</head>
    
<script>
var settings = {
  "crossDomain": true,
  "url": "http://localhost:3000/api/dashboard",
  "method": "GET",
  "headers": {
    "x-metabase-session": "<ID that was returned from my POST request to /api/session>"
  },
  "contentType": "application/json",
  "dataType": "json" 
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
</script>
</html>
```

**Comment by camsaul** [comment]
@kqiu2, If you're able to perform the request via `curl` without issue then it sounds like an issue with your jQuery request. I haven't used jQuery in the better part of a decade though so I'm not really the best person to help you with this. 

The 401 you're getting here suggests that the `X-Metabase-Session` header isn't getting passed correctly so I'd recommend looking at your browser console to see if that is indeed the case and looking at the jQuery dox to make sure you're doing things the way they like.

**Comment by camsaul** [comment]
@kqiu2 are you still having issues using `curl` to perform Metabase API requests? If not, feel free to close this issue.

**Comment by ACPK** [comment]
I recently hit this issue.

**Comment by snarfed** [comment]
fwiw i've done this in https://github.com/snarfed/metabase/commit/24a99386cb4c000b9242078cff7e5dd8a7800dba . tested, and it works, but i'm not actually using it right now.

```diff
--- a/src/metabase/middleware.clj
+++ b/src/metabase/middleware.clj
@@ -226,6 +226,7 @@
 (defn- api-security-headers [] ; don't need to include all the nonsense we include with index.html
   (merge (cache-prevention-headers)
          strict-transport-security-header
+         "Access-Control-Allow-Origin" "*"
          #_(public-key-pins-header)))
 
 (defn- html-page-security-headers [& {:keys [allow-iframes?] }]
@@ -242,7 +243,9 @@
     ;; Prevent Flash / PDF files from including content from site.
     "X-Permitted-Cross-Domain-Policies" "none"
     ;; Tell browser not to use MIME sniffing to guess types of files -- protect against MIME type confusion attacks
-    "X-Content-Type-Options"            "nosniff"}))
+    "X-Content-Type-Options"            "nosniff"
+    "Access-Control-Allow-Origin" "*"
+    }))
 
 (defn add-security-headers
   "Add HTTP headers to tell browsers not to cache API responses."
```
