### ISSUE TITLE
Custom column with errors is removed from the question without any error being shown

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#33441]
### Describe the bug

If I add a custom column with an error (such as "days" in stead of "day" passed as unit to `datetimeDiff`) it gets removed without warning when trying to see the results of the question.

### To Reproduce

1. Create new question from `Sample Database > Invoices`
2. Click to add a custom column
3. Insert `datetimeDiff([Date Received] , now, "days")` (notice the "days" instead of "day")
4. Insert a name for the custom column and presso done
5. Click on "Visualize"

The query will be run but it will have the custom column removed

https://github.com/metabase/metabase/assets/1914270/06e43787-b0db-448e-940a-e4beb5ac0800

### Expected behavior

I would expect an error, and the custom expression not to be lost

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20.0.1",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "20.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20.0.1",
    "os.name": "Mac OS X",
    "os.version": "13.4",
    "user.language": "en",
    "user.timezone": "Europe/Rome"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-08-21",
      "src_hash": "826d89e820f1b4d5fa882689e8142e668ace999b",
      "tag": "v0.47.1-SNAPSHOT",
      "branch": "whats-new-logic",
      "hash": "098d9f7"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

### Additional context

In case it can help: if I instead use "days" in custom summary expression (example: `datetimeDiff("2022-12-28T12:00:00", "2022-12-25T12:00:00", "day")` I get the following error:
`Invalid input: {:query {:aggregation [[nil [nil nil nil ["datetime-diff unit"]]]]}}`

**Comment by uladzimirdev** [comment]
I can still reproduce the issue, I'd not say it's a bug and P2, but it would be a great improvement of handing wrong expressions
