### ISSUE TITLE
Bar chart with lower value is longer with higher ones

### ISSUE THREAD

**Issue by jonathanrsmjtk** [metabase/metabase#33465]
### Describe the bug

<img width="1293" alt="Screenshot 2023-08-24 at 22 30 32" src="https://github.com/metabase/metabase/assets/49324622/983324d2-c8e9-46c4-b750-c4577cdc09ca">
<img width="1332" alt="Screenshot 2023-08-24 at 22 30 37" src="https://github.com/metabase/metabase/assets/49324622/7144b7a6-517d-49d5-a4fa-718f718609c7">

### To Reproduce

1. Make a SQL question that calculates sum of groups (3 groups in my case)
2. Visualize it with bar chart 

### Expected behavior

The red bar should be shorter

### Information about your Metabase installation

```JSON
- Browser: Chrome 116.0.5845.96
- Database: PostgreSQL
- OS: MacOS 13.5.1
- Metabase version: 0.47.0
- Metabase hosting environment: local (via Homebrew)
```

### Severity

Urgent

**Comment by paoliniluis** [comment]
probably a regression, just tagged it

**Comment by luizarakaki** [comment]
@jonathanrsmjtk looks like you have two Y-axis. You can disable the axis split.

**Comment by luizarakaki** [comment]
Can you send a print screen of the entire chart on the year filter? I can clearly see an axis on the right and left of the first post

**Comment by jonathanrsmjtk** [comment]
> Can you send a print screen of the entire chart on the year filter? I can clearly see an axis on the right and left of the first post

This is captured from question
<img width="1390" alt="Screenshot 2023-08-25 at 20 40 11" src="https://github.com/metabase/metabase/assets/49324622/a3734a8f-0e9e-43da-92b6-2e18843290a5">

**Comment by luizarakaki** [comment]
So? It is not the same size anymore

**Comment by jonathanrsmjtk** [comment]
> So? It is not the same size anymore

You can compare the March and April bar from yearly chart with the first picture captured with quarter filter. The red bars appear bigger as they have smaller amount values than the blue and purple bars.

**Comment by luizarakaki** [comment]
Ok, then send us a screenshot of the entire chart of quarter-filtered chart. I'm pretty sure there are two Y-axis there

**Comment by jonathanrsmjtk** [comment]
> Ok, then send us a screenshot of the entire chart of quarter-filtered chart. I'm pretty sure there are two Y-axis there

Yes, there is a pie chart using that filter too. I can't send it now

**Comment by perivamsi** [comment]
Not able to repro in master.
