### ISSUE TITLE
API endpoints exposing all the data even if the user is not admin user

### ISSUE THREAD

**Issue by vakhariad** [metabase/metabase#33476]
### Describe the bug

The API endpoints available, some data should only be visible to admin users like Database creds, the users list,etc. Even though the user is not admin user, he/she can hit that endpoint and get the required data.

### To Reproduce

1. Hit 'metabase_deployment_host/api/user' endpoint
2. All the user details are visible to the user.

### Expected behavior

This shouldn't work unless the user authenticated is an admin user.

### Information about your Metabase installation

```JSON
Hosting Env: Docker
Metabase Version: 0.46.6.4
```

### Severity

High

### Additional context

If the user can view or list the user or databases, he/she can hit the Delete endpoint and delete the user or dashboards as well.

**Comment by paoliniluis** [comment]
@vakhariad please review the code before posting something like this

**Comment by vakhariad** [comment]
Apologies will take care of this next time.
