### ISSUE TITLE
Save Button doesn't get disabled and can be clicked multiple times in admin panel Add Database page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3347]
It looks like every time you hit "Save" in the admin panel add database page it creates a new database. I accidentally clicked the button twice and now I have two copies of the same database.

It can take a few seconds before the initial round-trip completes and takes you back to the databases list, and it looks like the Save button doesn't get disabled. There's no clear indication that anything is happening once you press it, so I would imagine some impatient people might press it more than once. This can be a big performance issue since clicking "Save" starts up the DB analyzation & sync process, and it could jam up the whole instance firing off a several of them all at once. We should disable the button right away after the first time it's clicked.

Here's a video of the bug in action (I'm pressing Save a few dozen times here):

![out](https://cloud.githubusercontent.com/assets/1455846/18457816/9fe583da-7910-11e6-85f3-f3cc61879d7d.gif)

Note that the Save button never switches to a disabled state

**Comment by kdoh** [comment]
I wasn't able to reproduce this, although it's possible that the database I was trying to add was small enough that it wasn't triggering this case. Mind confirming if this is still a thing when you get a chance @camsaul?

**Comment by camsaul** [comment]
@kdoh a good way to repro it is to modify some backend files so the server is forced to reload everything which means the API request will take a few seconds while the server reloads 

then you'll be able to hit the button lots of times

**Comment by attekei** [comment]
Fixed by #5523
