### ISSUE TITLE
Add Finnish language

### ISSUE THREAD

**Issue by jannekeskitalo** [metabase/metabase#33477]
**Is your feature request related to a problem? Please describe.**
Metabase adoption in Finland is hindered by the lack of native language UI.

**Describe the solution you'd like**
I completed the translation of Finnish language in POEditor. Please add the language in the next release.

**Describe alternatives you've considered**
No alternatives.

**How important is this feature to you?**
It's important for the adoption of Metabase in Finland.

**Additional context**
n/a

**Comment by paoliniluis** [comment]
@jannekeskitalo thank you so much!!!

**Comment by paoliniluis** [comment]
cc @mazameli

**Comment by jannekeskitalo** [comment]
Any update on this?

**Comment by mazameli** [comment]
I'll take the blame on this one, @jannekeskitalo — somehow I neglected to get this into the 0.47 release. The 0.48 release is not far away, so I'll make sure Finnish gets included then. Thanks for your patience.

**Comment by jannekeskitalo** [comment]
👍
