### ISSUE TITLE
Argument is not passed correctly into metabase in docker script

### ISSUE THREAD

**Issue by Holi0317** [metabase/metabase#33485]
### Describe the bug

In docker environment, the `/app/run_metabase.sh` cannot pass command into the underlying jar if the argument contains space.

### To Reproduce

1. Run `docker run --rm metabase/metabase:v0.46.5 migrate release-locks`

### Expected behavior

`migrate release-locks` should be able to run

### Logs

```
The 'migrate' command requires the following arguments: [direction], but received: [].
```

### Information about your Metabase installation

```JSON
- Metabase hosting environment: docker, in ECS
```

### Severity

blocking usage of Metabase entirely because the migration failed and we cannot unlock it now.

### Additional context

Should be caused on https://github.com/metabase/metabase/blob/f72e985ed04efe7dd41c9473dde06ede5b9aaa6b/bin/docker/run_metabase.sh#L171 where metabase uses `$@` instead of `$*`. Tried changing that line and running the script in docker interactive and it worked.

Have a branch containing a patch and will make PR right after opening this issue.

**Comment by paoliniluis** [comment]
I need to test this since serialization commands work without issue

**Comment by paoliniluis** [comment]
Check 
```
docker run -it --rm metabase/metabase:v0.46.5 "migrate release-locks"
```

**Comment by Holi0317** [comment]
> Check
> 
> ```
> docker run -it --rm metabase/metabase:v0.46.5 "migrate release-locks"
> ```

This does work. But that means we need to change the documentation on metabase because the documentation assumes multiple argument getting passed into the init script here:

https://github.com/metabase/metabase/blob/5116f76bad1687c5817278181c1372661280f504/docs/installation-and-operation/upgrading-metabase.md?plain=1#L156

**Comment by paoliniluis** [comment]
@jeff-bruemmer 👆🏻 super simple change
