### ISSUE TITLE
Stacked charts only showing sum of regions

### ISSUE THREAD

**Issue by hukev** [metabase/metabase#3351]
Stacked area charts are only showing one region, with value equal to the sum of the groups. 
http://mb.operator.com/card/1700

Browser: Chrome Version 52.0.2743.116 (64-bit)
Operating system: OS X 10.11.6
Database: MySQL
Metabase version: v0.19.3
- _Repeatable steps to reproduce the issue_

Create a query that has a date column, a groupedby column, and a numerical column. The area chart will only have one region, with value equal to the sum of the values within all groups on the corresponding date.

<img width="482" alt="screen shot 2016-09-13 at 11 16 45 am" src="https://cloud.githubusercontent.com/assets/5407426/18485910/a5c3b7fc-79a3-11e6-9c44-6d8d9b4d911f.png">
<img width="1677" alt="screen shot 2016-09-13 at 11 17 04 am" src="https://cloud.githubusercontent.com/assets/5407426/18485911/a5d9279a-79a3-11e6-8810-3b7960228030.png">

**Comment by flamber** [comment]
Hi @hukev 
I've tried to reproduce your issue on 0.31.2 without success - do you still see the issue on newer versions?
![image](https://user-images.githubusercontent.com/1447303/52688864-c3614680-2f1d-11e9-99c3-4b7763a77fcc.png)

**Comment by mazameli** [comment]
Unable to reproduce this anymore. Must have gotten fixed along the way.
