### ISSUE TITLE
Mongodb connection bug

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#3352]
### Bugs

I got this error message when using metabase with mongodb:

com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=x.x.x.x:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]

---

Please assist.

**Comment by camsaul** [comment]
Can you connect to the Mongo database using another tool like the Mongo shell?

**Comment by thucnc** [comment]
I can connect to the mongodb by mongochef, with the same settings.

**Comment by camsaul** [comment]
@thucnc Mongo is running on a different computer, correct? And you're running both MongoChef and Metabase locally?

**Comment by camsaul** [comment]
@thucnc since we haven't heard back in a few months I'm going to go ahead and close this. Feel free to open a new issue if you're still experiencing problems.

**Comment by minhajali1990** [comment]
My MongoDB is installed in Linux server. it's allowing 1 of 3 time
means if I am trying three times it's connecting one time other two times it's giving error.
from my c# application as well as MongoChef. what would be the reason can you please help.

In other hand I am able to connect with same connection string from c# and mongoChef to my other database which is installed in windows machine so I can say my c# connection string is correct.


![from mongochef](https://cloud.githubusercontent.com/assets/7066802/21890322/47e8c8a2-d8f3-11e6-9fc4-f6782f3a9163.png)
![from c#](https://cloud.githubusercontent.com/assets/7066802/21890323/480f15b6-d8f3-11e6-9abb-cd2755c3bfbf.png)

**Comment by thucnc** [comment]
@camsaul sorry for my late response as I haven't got the notification till today. Yeah, my mongodb in a different machine. I already switched to postgres to utilize sql, metabase seems not good at mongo query at the time I tested.
