### ISSUE TITLE
Running metabase.jar fails with Memory aborted and Core dumped error

### ISSUE THREAD

**Issue by durgaswaroop** [metabase/metabase#33521]
### Describe the bug

I am trying to run Metabase in a docker container on Java8. But I am seeing the following error without any other error messages. 
```
library initialization failed - unable to allocate file descriptor table - out of memoryAborted (core dumped)
```
I am using metabase's latest jar file available on the website - v.0.47.0 and running it on Java 8's docker container. The same error occurs when I try with Mysql DB or with an H2 DB. 

Can someone help me figure out what could be causing this issue?

### To Reproduce

1. Download the latest metabase.jar file (v0.47.0)
2. Run a Java8 docker container and copy the jar file inside it
3. Run the jar with `java -jar metabase.jar`
4. See error appear

### Expected behavior

Metabase should start

### Logs

library initialization failed - unable to allocate file descriptor table - out of memoryAborted (core dumped)

### Information about your Metabase installation

```JSON
NA
```

### Severity

High

### Additional context

This used to work before for an older version of metabase  - 0.41.6.

**Comment by paoliniluis** [comment]
Please read the docs, Java 8 is no longer supported

**Comment by durgaswaroop** [comment]
Oh, I see. Actually the docs still mention Java 8 which is why I used it. 

You may want to get those updated. 

[Running the metabase Jar file](https://www.metabase.com/docs/latest/installation-and-operation/running-the-metabase-jar-file) does not seem to mention any Java version dependency. 

Also, the OSS page mentions Java8 as well which is where I started from. 
![image](https://github.com/metabase/metabase/assets/8543652/8015f7cf-7211-490a-965e-1c5410ee9426)


Thanks for the information. I'll use a later version of Java.
