### ISSUE TITLE
Broken "is not" filtering for Postgres db

### ISSUE THREAD

**Issue by mkrcah** [metabase/metabase#3354]
Version: v0.19.3

When using the `is not` filter in the query builder for a postgres db, the resulting dataset does not contain all relevant rows. Rows with `null` values in the filtered column are missing.

This is caused by wrong translation into a SQL query. The `is not` filter is translated into `<>` postgres operator. However, `a <> b` translates to `null` if one of the operators is `null` and therefore excludes the row when used in a `where` clause.

Proposal: Replace `a <> b` with `a IS DISTINCT FROM b` operator, which yields `true` if one of the operators is `null`.

More info on the operator here: https://www.postgresql.org/docs/current/static/functions-comparison.html

**Comment by flamber** [comment]
Closing in favor of #13332
