### ISSUE TITLE
[MLv2] `with-different-database` should be able to take a query as a parameter

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#33545]
`with-different-database` expects a `metadata-provider` as the third argument. Can we use query (1st arg) metadata here?

**Comment by snoe** [comment]
I don't think we can, unless I'm missing something, but `metadata` only holds a single database, so part of changing the database is to swap out `:lib/metadata` on the original query. If we're asking if a second `query` can be used as the third arg, sure that's possible but probably not helpful to use it that way.

**Comment by snoe** [comment]
Blocked on a reply from @camsaul or @kulyk

**Comment by snoe** [comment]
@kulyk says

> yeah, I don’t have a strong preference here. Does this snippet look correct to you?
> 
> ```
> 
> import * as Lib from "metabase-lib"
> 
> const question = ... // MLv1 Question instance coming from somewhere else
> 
> function handleDatabaseChange(nextDatabaseId: number) {
>   const query = question.getMLv2Query();
> 
>   // question.metadata() should have all available metadata, including a database with the ID we need
>   const nextMetadataProvider = ML.metadataProvider(nextDatabaseId, question.metadata())
> 
>   // New query object with a changed database ID ?
>   const nextQuery = Lib.withDifferentDatabase(query, nextDatabaseId, nextMetadataProvider)
> }
> ```
> 

@snoe says
> you should be able to just pass `question.metadata()` to `withDifferentDatabase`
