### ISSUE TITLE
Snowflake support

### ISSUE THREAD

**Issue by tomsej** [metabase/metabase#3355]
Hi, it would be great to add support for [Snowflake](http://www.snowflake.net).

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
Hi @tomsej, we're adding support for various DBs based on community demand. Since you're the only person who's asked for this DB thus far, that might be a while 😉 

If you're familiar with Clojure and feeling adventurous you can try [writing a driver yourself](https://github.com/metabase/metabase/wiki/Writing-A-Driver). I'm available to help with any questions you might run into.

**Comment by sogorman** [comment]
I will +1 the request for Snowflake support / connector.

**Comment by funkaster** [comment]
same here. +1 for Snowflake support. I'll take a look at the wiki page for a driver as well.

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by Vfisa** [comment]
+1. Thank you!

**Comment by camsaul** [comment]
Hey @Vfisa, please read the comment posted right before yours. One way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

😒

**Comment by sogorman** [comment]
Just throwing it out there but if anyone is willing to take on building a snowflake connector I have a few thousand I can throw their way.

**Comment by kenbier** [comment]
@camsaul @tomsej @rolandoam @DirectMailers @Vfisa @will-unity 
I figured I'd try my hand at this one. PR is #6658.

The PR is pending review and tests. If you could check out the branch and test it for your use cases, that would be awesome. It would help surface any bugs and get Snowflake support merged in faster ❄️ ❄️ ❄️

**Comment by sadhasivam** [comment]
+1

**Comment by metacyclic** [comment]
👍 - this would be great

**Comment by standby** [comment]
Verified that it is working for my snowflake.

**Comment by sogorman** [comment]
Ugh, so being a Git noob I can't figure out how to clone this PR.. so I am unable to build and test the Snowflake Functionality. If anyone wants to point me to a built JAR I will be happy test out the SnowFlake functionality.

**Comment by jornh** [comment]
@sogorman sorry no built JAR - but the code to clone is in this branch in kenbier’s repo:
https://github.com/kenbier/metabase/tree/add-snowflake-database

Building is described in a link above - or to handle all build dependencies [if you have Docker I added a bit in this discourse topic](http://discourse.metabase.com/t/oracle-doesnt-show-up-on-my-database-menu/1525/12?u=jornh)

**Comment by jesusrtc** [comment]
+1

**Comment by jornh** [comment]
Hey everyone, one way the Metabase core team prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍 comments, please just upvote by adding a reaction to the issue description.

**Comment by watthell234** [comment]
When will kenbiers PR be merge and deployed into prod?

**Comment by josephacramer** [comment]
@camsaul - what will it take to get the Snowflake connector merged into the master branch? I'm happy to help coordinate any resources on the Snowflake side to make this happen as quickly as possible. Thank you.

**Comment by camsaul** [comment]
Implemented by #8790
