### ISSUE TITLE
Move Instance Analytics to the bottom of collections in sidebar

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#33554]
Per designs, the Audit collections should always come below the other "normal" instance collections
https://www.figma.com/file/A6Q4571ZvMq2qUUxLgKU4y/Audit-v2?type=design&node-id=15-472&mode=design&t=csAPTCV7H5lAhCeX-4
![image](https://github.com/metabase/metabase/assets/32561114/4ea802ce-73bc-46d2-9d52-331ad7b24cb7)

**Comment by adam-james-v** [comment]
PR #33772 closes this.
