### ISSUE TITLE
[MLv2] [BE] Add `drill-thru/automatic-insights`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#33558]
Braden did a brain dump of how all this stuff works here, please read thru it: https://metaboat.slack.com/archives/C04CYTEL9N2/p1691679718619139

JS code:

https://github.com/metabase/metabase/blob/0b0edf1b916aa6a4000767ec42a41c2721d22391/frontend/src/metabase-lib/queries/drills/automatic-insights-drill.ts

1. Port JS code to Cljs
2. Fill out skeleton `drill-thru-method`
3. Make sure this comes back for the appropriate columns in `available-drill-thrus`
4. Write a million tests

**Comment by camsaul** [comment]
Note that `drill-thru-method` and `available-drill-thrus` currently live in https://github.com/metabase/metabase/pull/31735 but Braden will be getting that merged into `master` shortly.

**Comment by ranquild** [comment]
Proposed API:

Add `drill-thru/automatic-insights` drill returned by `availableDrillThrus` replicating the logic from this function https://github.com/metabase/metabase/blob/5f02f32332a7863548dc9fd2c87c686324ff0883/frontend/src/metabase-lib/queries/drills/automatic-insights-drill.ts#L5

`applyDrill` should should this part https://github.com/metabase/metabase/blob/5f02f32332a7863548dc9fd2c87c686324ff0883/frontend/src/metabase-lib/queries/drills/automatic-insights-drill.ts#L32 - before `ML_Urls` call

`getAutomaticDashboardUrl` https://github.com/metabase/metabase/blob/d161a9cf59e0cff7455028d4ce21b8201c653ac9/frontend/src/metabase-lib/urls.ts#L98 and `getComparisonDashboardUrl` https://github.com/metabase/metabase/blob/d161a9cf59e0cff7455028d4ce21b8201c653ac9/frontend/src/metabase-lib/urls.ts#L121 would be implemented on the FE by calling `toLegacyQuery` and then serializing relevant query parts.
