### ISSUE TITLE
[MLv2] [BE] `drill-thru/quick-filter` - Add support for `contains` / `does not contain` filters for text columns

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#33560]
See @bshepherdson's brain dump in https://metaboat.slack.com/archives/C04CYTEL9N2/p1691679718619139 for more information, or ask him about this

I think this is the FE code in question

https://github.com/metabase/metabase/blob/0b0edf1b916aa6a4000767ec42a41c2721d22391/frontend/src/metabase-lib/queries/drills/quick-filter-drill.ts

1. Port JS code to Cljs if not already ported (not sure how much of this is or is not already ported)
2. Fill out placeholder `drill-thru-method` (again, not sure if this is done yet or not)
3. make sure the `quick-filter` drill thru is coming back in `available-drill-thrus` for text columns for the aforementioned filter types
4. Write a million tests

**Comment by camsaul** [comment]
`drill-thru-method` lives in this PR https://github.com/metabase/metabase/pull/31735 currently but we should try to get that PR merged into `master` so this can be done against `master`.

**Comment by ranquild** [comment]
Please postpone this work - I don't think that any BE / CLJS changes are required here

**Comment by ranquild** [comment]
@darksciencebase reopened - we need to return these operators (`contains` and `does-not-contain`) in `displayInfo` for this drill
