### ISSUE TITLE
Adding certain columns in viz settings results in completely broken query 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#33563]
To repo

1. Follow steps from #33562
2. Add the first `User Id` column 
3. Add the second `User Id` column
4. Run the query
5. Query is broken:

<img width="1410" alt="image" src="https://github.com/metabase/metabase/assets/1455846/a21e267b-59a1-427b-ae66-8b4cef92a3cb">

Generated MBQL:

```json
{
  "database": 1,
  "type": "query",
  "query": {
    "source-table": "card__1131",
    "fields": [
      [
        "field",
        1,
        null
      ],
      [
        "field",
        5,
        null
      ],
      [
        "field",
        10,
        null
      ],
      [
        "field",
        15,
        null
      ],
      [
        "field",
        18,
        null
      ],
      [
        "field",
        23,
        null
      ],
      [
        "field",
        15092,
        null
      ],
      [
        "field",
        25,
        {
          "temporal-unit": "default"
        }
      ],
      [
        "field",
        15093,
        null
      ],
      [
        "field",
        "NAME",
        {
          "base-type": "type/Text"
        }
      ]
    ]
  },
  "parameters": []
}
```

Generated SQL:

```sql
SELECT
  "source"."ID" AS "ID",
  "source"."USER_ID" AS "USER_ID",
  "source"."PRODUCT_ID" AS "PRODUCT_ID",
  "source"."SUBTOTAL" AS "SUBTOTAL",
  "source"."TAX" AS "TAX",
  "source"."TOTAL" AS "TOTAL",
  "source"."DISCOUNT" AS "DISCOUNT",
  "source"."CREATED_AT" AS "CREATED_AT",
  "source"."QUANTITY" AS "QUANTITY",
  "source"."NAME" AS "NAME",
  "source"."PRODUCTS__via__PRODUCT_ID__TITLE" AS "PRODUCTS__via__PRODUCT_ID__TITLE"
FROM
  (
    SELECT
      "PUBLIC"."ORDERS"."ID" AS "ID",
      "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID",
      "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID",
      "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL",
      "PUBLIC"."ORDERS"."TAX" AS "TAX",
      "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL",
      "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT",
      "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT",
      "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY",
      "PRODUCTS__via__PRODUCT_ID"."TITLE" AS "PRODUCTS__via__PRODUCT_ID__TITLE"
    FROM
      "PUBLIC"."ORDERS"
     
LEFT JOIN "PUBLIC"."PRODUCTS" AS "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
  ) AS "source"
LIMIT
  1048575
```

As you can see it's attempting to add a 

```js
 ["field", "NAME", {"base-type": "type/Text"}]
```

column to the query, even tho I did not ask for that column at all (I asked for `User Id`). Worst of all, there is no `NAME` column in `ORDERS` or `PRODUCTS`; my best guess it that `NAME` here is supposed to be coming from `PEOPLE`, altho the Field ref doesn't have the `:source-field` information the QP would need to be able to add an implicit join.

As with #33562, I'm having trouble reproducing this consistently, but @bshepherdson can confirm that we triggered this bug completely accidentally while poking around stats together, so it did exist at some point.

When the MLv2 viz settings stuff lands with the extra tests we can probably close this out if it is no longer reproducible.

**Comment by ranquild** [comment]
Adding columns in viz settings is done via MLv2 entirely

**Comment by oisincoveney** [comment]
I tried to reproduce this one as well (on `0.47.5`, `master`, and #34851) but I'm getting nothing. We'll just need to keep an eye out for this one

**Comment by snoe** [comment]
Closing, incorrect columns no longer appear.
