### ISSUE TITLE
Drill thrus suggest time breakouts e.g. "See this day by hour" for `DATE` columns resulting in broken queries

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#33573]
Bug since forever.

1. New Question > Raw Data > Sample Dataset > People
2. Summarize by Count
3. Group by Birth Date > Day
4. Zoom in a bit 
5. Click a value an click `See this day by hour`
6. Query fails, because you cannot bucket a `DATE` column by `hour`. Dates don't have hours.

We should NOT be presenting this option for `:type/Date` columns, only for `:type/DateTime` columns.

<img width="349" alt="image" src="https://github.com/metabase/metabase/assets/1455846/226f29f2-1355-4b65-bd90-26c9268d5032">

<img width="592" alt="image" src="https://github.com/metabase/metabase/assets/1455846/17e7067e-4a43-4bd9-9ee3-854fa0df8175">

**Comment by appleby** [comment]
Duplicated by https://github.com/metabase/metabase/issues/39366
