### ISSUE TITLE
Reset Password Email Link is Broken

### ISSUE THREAD

**Issue by maksim2042** [metabase/metabase#3357]
When Metabase is running on a non-standard port (e.g. 3000), the reset-password email link contains an extra slash:

http://54.161.150.120/:3000/auth/reset_password/1_afe53d65-0c72-41a4-8ba1-d939642afaa7

**Comment by HugoDellinger** [comment]
I have the same issue. It seems to be also a problem when clicking on a card in a pulse.

**Comment by camsaul** [comment]
@maksim2042 @HugoDellinger I'm having trouble reproducing this. 

How are you running Metabase? And what version are you running?

**Comment by camsaul** [comment]
Also, when you access Metabase, what URL are you using?

Something like http://54.161.150.119:3000 ?

**Comment by camsaul** [comment]
Can you also open this in your browser and let me know what response it gives you?

```
http://<your-metabase-address>/api/setting/-site-url
```

**Comment by camsaul** [comment]
@maksim2042 @HugoDellinger ?

**Comment by camsaul** [comment]
@maksim2042 @HugoDellinger ?

**Comment by camsaul** [comment]
@maksim2042 @HugoDellinger since we haven't heard back in a couple of months I'm going to go ahead and close this. Feel free to open a new issue if you're still having problems.

**Comment by salsakran** [comment]
I poked around on 0.21.1 with the site name and the only way I could produce a second `'` is to place a trailing space. 

👍  on closing this unless we get repro steps.
