### ISSUE TITLE
"Can the 'trace.db' in Metabase be deleted? It's occupying 180GB."

### ISSUE THREAD

**Issue by aicopy** [metabase/metabase#33580]
**Describe the bug**

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.25.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-02",
      "tag": "v0.44.3",
      "branch": "release-x.44.x",
      "hash": "7d50282"
    },
    "settings": {
      "report-timezone": "America/New_York"
    }
  }
}





![image](https://github.com/metabase/metabase/assets/117983090/4c676717-96cb-43a9-8f45-d8769a62c6d7)


If Metabase is occupying 180GB of disk space, how can I delete unnecessary files?

**Comment by aicopy** [comment]
Here are the files, and I'm not sure which ones can be safely deleted without affecting usage:

/var/lib/docker/overlay2/88a2bd5cae76fdfc0899f87ec1165c728bf61ddc2ff175ea276b36b1b7f2a8f6/diff/app/metabase.jar
/var/lib/docker/overlay2/1d69ed29b0847a734c85078a4aaded97ec22944853f512a112cd8cfdd8c4886c/diff/metabase.db/metabase.db.mv.db
/var/lib/docker/overlay2/1d69ed29b0847a734c85078a4aaded97ec22944853f512a112cd8cfdd8c4886c/diff/metabase.db/metabase.db.trace.db
/var/lib/docker/overlay2/1d69ed29b0847a734c85078a4aaded97ec22944853f512a112cd8cfdd8c4886c/diff/app/metabase.jar
/var/lib/docker/overlay2/1d69ed29b0847a734c85078a4aaded97ec22944853f512a112cd8cfdd8c4886c/merged/metabase.db/metabase.db.mv.db
/var/lib/docker/overlay2/1d69ed29b0847a734c85078a4aaded97ec22944853f512a112cd8cfdd8c4886c/merged/metabase.db/metabase.db.trace.db
/var/lib/docker/overlay2/1d69ed29b0847a734c85078a4aaded97ec22944853f512a112cd8cfdd8c4886c/merged/app/metabase.jar
Please note that you should exercise caution when deleting files, especially in a production environment. It's recommended to back up any important data before proceeding, and if you're unsure about a particular file, it's best to seek guidance from someone familiar with your specific Metabase setup to avoid any unintended consequences.

**Comment by paoliniluis** [comment]
First post on discourse, second, get OUT NOW OF H2 or you risk losing everything in your deployment

**Comment by aicopy** [comment]
"Can you provide me with a specific link to the article and teach me how to handle it? Will deleting trace.db affect the normal functioning of Metabase?"

**Comment by paoliniluis** [comment]
https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2

If you delete the file you’ll lose everything
