### ISSUE TITLE
Any way to disable emojis from the logging output?

### ISSUE THREAD

**Issue by NeckBeardPrince** [metabase/metabase#3358]
We are wanting to increase our logging ingesting in my company and we are trying out metabase. Currently there are emojis in the output which is going to cause issues with logstash grokking these logs. Any way to turn them off?

**Comment by camsaul** [comment]
Hi @NeckBeardPrince, we currently don't have any way to remove emoji from the logs. A while back someone contributed a patch to disable log colorization so if you're feeling ambitious and would like to do the same for emoji we would happily accept a PR 👍
