### ISSUE TITLE
Scatter plot renders as a Table in Email/Slack subscription

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#33586]
### Describe the bug

Scatter plots are rendered as a table in email subscription

### To Reproduce

1. Go to New Question -> Orders -> Count Group by Created__at:Month and Category

<img width="1155" alt="image" src="https://github.com/metabase/metabase/assets/110378427/ce6ff7ca-2cc0-425d-a383-617448a4ef70">

2. Select Scatter Plot Viz -> Save -> Add to Dashboard

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/997362e1-46f5-4cd2-b466-b49ac20bfae5">

3. Schedule an Email subscription or Slack and notice it's sent as a table

<img width="799" alt="image" src="https://github.com/metabase/metabase/assets/110378427/695cb469-d203-403d-851f-862e875b4504">

<img width="774" alt="image" src="https://github.com/metabase/metabase/assets/110378427/03991b8d-3ec7-4eb2-99af-a865ae71d957">

### Expected behavior

Send it as a Chart

### Logs

None that can be of importance

### Information about your Metabase installation

```JSON
Able to replicate on Master and 1.46.6.4
```

### Severity

Major issue for people that are dependent on subscriptions for updating their customers

**Comment by alxnddr** [comment]
@Tony-metabase this is a feature request since we haven't had a static scatter chart
