### ISSUE TITLE
Database details contain stale data

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3359]
Metabase version: Master running on postgres+beanstalk viewed on Chrome (latest)

Add a couple databases, and click on the first. Click back and click on the second. You'll see stale data from the first database. Bonus points if the second database is of a different type, in which case things get even more confused.

**Comment by salsakran** [comment]
this also manifests itself when going to /admin/database/create multiple times. That form contains previously entered data as well.

**Comment by camsaul** [comment]
peripherally related: #3347

**Comment by salsakran** [comment]
this is still a problem on master.

**Comment by dovy** [comment]
Details steps to reproduce in #3572

**Comment by camsaul** [comment]
If this is Priority/P1 should we move it from 0.21.0 -> 0.20.1 ?
