### ISSUE TITLE
Request to Extend User Session Token Expiry in Metabase for Improved User Experience

### ISSUE THREAD

**Issue by nickjordanovski** [metabase/metabase#33599]
**Is your feature request related to a problem? Please describe.**
Currently, users are automatically logged out after a certain period of inactivity. This causes inconvenience as users need to frequently log back in, disrupting their workflow and slowing down their productivity.

**Describe the solution you'd like**
I would like to request the option to configure the user session tokens in Metabase so that they do not expire by default. This would enable users to stay logged in and keep their sessions active for an extended period, improving user experience and efficiency.

**Describe alternatives you've considered**
One alternative is to increase the session timeout duration, but this might not be ideal as it could potentially pose security risks. Allowing users to choose whether their tokens expire or not would provide a more flexible and user-friendly solution.

**How important is this feature to you?**
This feature is crucial to us as it directly impacts the usability and productivity of our team. Maintaining active sessions without frequent logouts would significantly enhance our experience with Metabase.

**Additional context**
[Add any other relevant context or screenshots here. For example, if there's a particular use case or scenario that highlights the importance of this feature request, mention it here.]

Thank you for considering this feature request. We believe that this enhancement would make Metabase an even more valuable tool for our organization.

**Comment by paoliniluis** [comment]
Please check the environment variables
