### ISSUE TITLE
Aphro1z

### ISSUE THREAD

**Issue by Aphrone** [metabase/metabase#33621]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

**Comment by Aphrone** [comment]
Fix my wallet

**Comment by paoliniluis** [comment]
This is not the Metabase token project, which has nothing to do with us and also copied our name infringing trademarks
