### ISSUE TITLE
Precisions about v 0.47 release notes

### ISSUE THREAD

**Issue by akileebyines** [metabase/metabase#33624]
### Describe the bug

Release notes of version 0.47 unclear

Relesae notes f version 0.47 (open source) states
"Powered up Pro features
Unlock git-based workflows with serialization 2.0"

Does it mean that some serializaztion features are moving to open source version? If so where can we learn about them in the documentation?

### To Reproduce

Release notes unclear

### Expected behavior

Be clear and unmisleading

### Information about your Metabase installation

```JSON
version 0.47
```

### Severity

question

**Comment by luizarakaki** [comment]
No, Serialization is still a Pro / Enterprise only feature. Sorry for adding this to the OSS release notes, will fix.
