### ISSUE TITLE
Permissions Stage 2

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3363]
This will add column-level permissions and add group ownership of dashboards and pulses.

A dashboard, pulse will be saved to a given user group (defaulting to "All Users"). Users will have access to all artifacts in groups they are members of. 

With regard to column level permissions, these will be given as follows:

Column access within a table
- A user group has access to all fields
- A user group has access to no fields
- A user has access to a white list of fields

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by tlrobinson** [comment]
Could artifacts belong to more than one group?

**Comment by camsaul** [comment]
If I understand correctly I think the idea is that groups would have permissions to see a given DB/Card/etc., or they wouldn't. 

So it's not entirely correct to say an artifact "belongs" to a group. A group may or may not have permissions for an artifact.

**Comment by moumny** [comment]
Not sure if planned but very important for us is to restrict editing of dashboards (we have official/verified dashboards)

**Comment by tlrobinson** [comment]
The description above says "A dashboard, card or pulse will be saved to a given user group" which sort of implies a single group, but I think it would make sense to be able to grant permission to multiple groups.

Also, how does this interact with data permissions? Does a user need to **both** belong to a group that has access to the artifact, and have sufficient data permissions to see that artifact, or only one or the other? I could see scenarios where both would be useful/expected:

1. You want to allow users to see curated cards/dashboards but not do arbitrary queries, so you add them to a group which doesn't have any data permissions but does have artifacts.
2. You need to revoke permission to a particular table for a group, and you don't want them to be able to see existing artifacts that use that table any more.

If we don't care about the 1st use case then requiring a user have both artifact and data permissions would be fine.

If we do, then I think splitting the permissions into "view"/"read" and "create"/"write" like we have for SQL might work.

**Comment by camsaul** [comment]
FWIW I could see a lot of situations where you'd want to let a couple different groups see a dashboard but not necessarily all users. I a dashboard could only belong to one group people would have to work around that by creating a group just for a given dashboard.

IMO that was one of the shortcomings of our old Org perm system

**Comment by djtarazona** [comment]
> 1. You want to allow users to see curated cards/dashboards but not do arbitrary queries, so you add them to a group which doesn't have any data permissions but does have artifacts.

This is exactly what our team needs.  We'd like our engineers to be able to create curated cards / dashboards for non-technical teams and restrict the data they have access to (by using a SQL question and scoping data using a `WHERE` clause).  We don't want to give them data permission to view the database and/or tables, however we'd still like them to be able to see the card / dashboard we created for them.

**Comment by anki-code** [comment]
+1

**Comment by salsakran** [comment]
Breaking out a new issue for collections + collections perms, which is shipping in 0.22. #4052

**Comment by shijialee** [comment]
I would like to grant our engineers data and sql access(read & write) on all tables except for couple tables because sensitive info stored in there.

The doc mentions that read/write sql access requires the group to additionally have Unrestricted data access for the database in question, since SQL queries can circumvent table-level permissions.

Is there a metabase solution? Do I have to grant permission on each table inside my database to limit the access?

**Comment by sohel2020** [comment]
when we can get dashboard level permission for user? Any ETA???

**Comment by alee792** [comment]
One quick workaround is to put all questions in a dashboard in its own collection and create permissions on that collection.

**Comment by savraj** [comment]
Another angle on this is 
> Mark a Column as Personally Identifiable Information

Then, you can set a user group to either see Personally Identifiable Information or not.

-s

**Comment by goodfella1408** [comment]
By default a dashboard created by someone will be visible to all other users because its created under "All Users" permission .I think this behavior should be made optional . Someone having a group permission should be able to create dashboards only for that group .
We want to represent different clients as different groups on metabase .So we would like to strictly hide a dashboard created by one client from the other .

**Comment by sklein12** [comment]
I agree with @djtarazona, that's the exact situation I'm in. I've got one dashboard that I need to scope the data based on whose looking at it.  Another solution, while not as elegant, could have dashboards be associated to collections like questions.

**Comment by samhavens** [comment]
If you found this because you need dashboard-level permissions, you may be able to do that in a way that already exists, following [this part of the docs](https://metabase.com/docs/latest/administration-guide/13-embedding.html).

**Comment by rhnasc** [comment]
Hi. Has the feature of column-level permissions been abandoned? It still shows up at https://metabase.com/docs/v0.23.0/administration-guide/05-setting-permissions.html as a future option.

**Comment by msmaromi** [comment]
need that feature too, any update guys?

**Comment by flamber** [comment]
@msmaromi This issue is closed. Permissions on column and row level are available in the Enterprise Edition:
https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html
