### ISSUE TITLE
Inserting snippet into saved query before conditional field filter overwrites part or all of the field filter text

### ISSUE THREAD

**Issue by Ollie-Beauchamp** [metabase/metabase#33640]
### Describe the bug

When editing a SQL query to replace a hardcoded filter with a snippet,  I deleted the existing filter criteria and then inserted the snippet from the sidebar. 2 possible glitches:
1- The newly inserted snippet inserted while overwriting the [[ (or sometimes also part of the AND) from the filter following it OR
2- the snippet inserts in the wrong place and overwrites the entirety of the filter 2 lines down (leaving just a single preceding [ from the original filter): 

This glitch does not happen every time but I cannot tell what the difference is when it happens vs when it doesn't. I can avoid the overwrite by adding at least one extra row between the insert and the following conditional filter. It only seems to overwrite conditional filters that are following the inserted snippet directly.

Format of query before insert:
WHERE [filter criteria to be replaced]
[[AND {{filter 1}}]]
[[AND {{filter 2}}]]

Format of query after insert V1: overwrites following [[ from next line
WHERE {{snippet}}AND {{filter 1}}]] 
[[AND {{filter 2}}]]

(sometimes it will overwrite more than just the [[) e.g.:
WHERE {{snippet}}D {{filter 1}}]]
[[AND {{filter 2}}]]

Format of query after insert V2: keeps only [ from line 2 down
WHERE 
[[AND {{filter 1}}]]
[{{snippet}}

### To Reproduce

1. Write SQL query with at least a few conditional filters or open a saved one that has filters in this format:

WHERE [hardcoded filter criteria to be replaced]
[[AND {{filter 1}}]]
[[AND {{filter 2}}]]

2. Delete "filter criteria to be replaced" from above, and then select and insert a snippet from the snippet menu. 
3. snippet will overwrite a part of the following conditional field filter 

### Expected behavior

When I insert a snippet I expect it to insert in place and not affect any of the surrounding text, and certainly not overwrite following lines. 

### Information about your Metabase installation

```JSON
- browser Chrome Version 116.0.5845.140 
- OS Monterey V 12.4
- Metabase database: Postgres
- Metabase version: 0.47.0 
- hosting environment amazonaws
- metabase internal database: PostgreSQL
```

### Severity

annoying glitch that interferes with writing queries

**Comment by kamilmielnik** [comment]
I could not reproduce. I tried v47 and latest master at 9c44162334.
