### ISSUE TITLE
Implement unreturnedConnectionTimeout in c3p0 in an env var

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33646]
**Is your feature request related to a problem? Please describe.**
We still have problems with pools filling up and connection queues, so it's time to take the bull by the horns and add the unreturnedConnectionTimeout flag with an env var (default 10 mins, but can be overriden)

We should also add https://www.mchange.com/projects/c3p0/#debugUnreturnedConnectionStackTraces, to dump why a connection timed out.

**Describe the solution you'd like**
Add both flags to the c3p0 config, to start timing out the connections on our end so we can make sure that if queries don't return after 10 mins, it's a DB's problem (Metabase will wipe those)

**Describe alternatives you've considered**
None

**How important is this feature to you?**
We will resolve the connection queue problem by timing out the connection, and also get the stack trace to know what's happenning

**Additional context**
https://www.mchange.com/projects/c3p0/#unreturnedConnectionTimeout

**Comment by iethree** [comment]
shoudl this be closed by #33865 ?

**Comment by paoliniluis** [comment]
Yup
