### ISSUE TITLE
Allow multiple aggregations

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3364]
Right now we allow a single aggregation (or raw rows) to be run per question.

We should use a similar UI idiom as the multiple breakout `+` to allow multiple aggregations. Each aggregation would be filtered via the filter clause, broken out by the breakout clause.

**Comment by tlrobinson** [comment]
@salsakran This would be equivalent to something like `SELECT sum(total), count(*) FROM orders GROUP BY whatever(created_at);` correct?

**Comment by falling-down** [comment]
+1 for this as well.

**Comment by green2k** [comment]
+1

**Comment by ericparland** [comment]
+1

**Comment by jaimebarroso** [comment]
+1

**Comment by rafaelveloso** [comment]
+1

**Comment by crissyw** [comment]
+1
