### ISSUE TITLE
Expression aggregations

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3365]
We should allow the equivalent of druid post aggregations to do things like divide a result by a constant or once #3364 is in place calculate things like averages.

**Comment by underyx** [comment]
This would make it possible to take a table like

|source|users|sales|
|----|----|----|
|search|100|20|
|referral|200|10|
|direct|300|0|

and query for `sum(sales) / sum(users)`, to get the total conversion rate of 5%, right? If so, I won't create a duplicate feature request for queries like that :dancing_men:

**Comment by jbelke** [comment]
v0.27.2 Built on 2017-12-12
Post Aggregates Failing.

custom expression
=Sum(¨Transaction Revenue¨) / Sum(Transactions)

If grouped by Timestamp, daily raw works.

**Comment by Octivian** [comment]
@jbelke  v0.28.1 same issue
