### ISSUE TITLE
Allow embedding of dashboards in other websites

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3366]
Similar to #1380 but for dashboards.

This would allow the use of dashboards defined in Metabase in other web pages or applications.

This should be the main place to discuss how this feature will work + plan out the PR.

**Comment by LukeAbell** [comment]
Would love this!

**Comment by zwalden** [comment]
Definitely interested in seeing this !

**Comment by israrwz** [comment]
+1

waiting for this

**Comment by AnvayaAnalytics** [comment]
Looking for a tool like which sits on DRUID.
I want to develop interactive dashboards and embed in a web app.

**Comment by salsakran** [comment]
closed via #4271
