### ISSUE TITLE
Performance regression in how we parse query_metadata response leads to notebook being unusable

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33676]
### Describe the bug

We introduced a regression in the query_metadata, possibly because of several factors, that lead questions with lots of Metadata to slow down heavily the frontend (Pro tip: use the table metadata and generate a large lorem ipsum on the fields and tables descriptions to make a heavy response along with a "big" question with lots of stages and fields. remember we call the table_metadata for every linked table on a query, so if table 1 has a FK to table 2, we fetch both tables metadata)

Performance in 46:
![image](https://github.com/metabase/metabase/assets/1711649/8315f7da-d508-46ad-a9b1-2cb4a5c29e93)

Profiler
![image](https://github.com/metabase/metabase/assets/1711649/409305b8-4682-4ebe-b183-d1a65a274694)
![image](https://github.com/metabase/metabase/assets/1711649/c742c839-2fb9-4554-89e7-a0a171442a48)

Now let's move to 47:
look at the separation between calls (sizes of responses stayed the same)
![image](https://github.com/metabase/metabase/assets/1711649/7261b36f-4b97-48f2-ba19-3eef9a1c9c8d)

profiler:
2X
![image](https://github.com/metabase/metabase/assets/1711649/ea1c0958-b7e1-4de7-b69d-8180d4af53f2)

This will get amplified as more tables are joined in the data model

### To Reproduce

1) go to the data model and try to join a single table to all others. Also try to complete as much metadata as possible
2) then create a GUI question and add that single table, build a question with lots of aggregations, fields, etc
3) compare it between 46 and 47, see the difference in rendering

### Expected behavior

UI should be F A S T

### Logs

NA

### Information about your Metabase installation

```JSON
v47
```

### Severity

P1

**Comment by ranquild** [comment]
To reproduce:
- Create a question based on the `Accounts` table from the sample DB
<img width="1726" alt="Screenshot 2023-09-04 at 13 57 38" src="https://github.com/metabase/metabase/assets/8542534/96ee2331-f7b1-475a-b6a5-0ae5c4e74253">
- Run profiler with x4 slowdown and remove `Count` from the outer stage
<img width="1728" alt="Screenshot 2023-09-04 at 13 57 14" src="https://github.com/metabase/metabase/assets/8542534/3f7d5933-0d72-480f-89b8-fff68383d69f">

MLv2 functions take a lot of time to execute

**Comment by metamben** [comment]
I could speed up the case in the bug report, but the viz settings page is still terribly slow.

**Comment by bshepherdson** [comment]
The viz settings change landed early this morning NA time, so MLv2 is involved now. (Though perhaps the memoizations in #33761 don't help its speed?)

**Comment by metamben** [comment]
> The viz settings change landed early this morning NA time, so MLv2 is involved now. (Though perhaps the memoizations in #33761 don't help its speed?)

When I looked, MLv2 was not prominent in the profiler. Anyway, the urgent thing is unblocking 47.1 and there the new viz settings changes should not be available.

**Comment by paoliniluis** [comment]
reopening as it's still a thing

**Comment by metamben** [comment]
I've opened #33817 to make it more obvious if caching helps and added caching for orderable columns too.

I think @paoliniluis found another source of slowness nothing to do with MLv2. It seems to me that `dimensionForSourceQuery` got much slower. It would be good if a FE engineer had a look at this issue.

**Comment by paoliniluis** [comment]
@coisnepe you can move down to 46 without reverting a backup by running "java -jar metabase.jar migrate down" and after that shut down 47 and spin up 46. That will allow you to run 46 without having to recover a backup
