### ISSUE TITLE
Click Behaviour on questions with multiple axis categories gives random output

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#33672]
### Describe the bug

If you setup Click Behaviour on a question that has multiple categories on it's axis the filters that should represent the click will give random selection. Sometimes it populates Filter 1, sometimes populates Filter 2 and sometimes both. The pattern is random

### To Reproduce

1. Go to New -> Question -> Accounts -> Count Group by Plan, Source

<img width="1419" alt="image" src="https://github.com/metabase/metabase/assets/110378427/5da95be4-26b9-418b-a14d-3b30e28d7f52">

2. Visualize as a Stacked Bar Chart:

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/d82be86e-dd75-419a-820a-b2ec90855ccb">

3. Add this to a Dashboard -> Add 2 Filters and name them Plan and Source -> Setup Click behaviour so that Plan maps to Plan and Source maps to Source:

<img width="1510" alt="image" src="https://github.com/metabase/metabase/assets/110378427/4ce7d24c-8290-43f0-a1d6-9069af647897">

4. Start clicking on the chart

Clicking the Twitter Source of the Plan Basic - Only populates the Source

<img width="1497" alt="image" src="https://github.com/metabase/metabase/assets/110378427/4692ba32-4b81-49ab-a60b-dbba23c41bb7">

Clicking the Invite Source of the Plan Basic - Populates both the Source and Plan

<img width="1506" alt="image" src="https://github.com/metabase/metabase/assets/110378427/618f9914-bfb0-4b56-801e-e3505f4da138">

And so on for other categories

### Expected behavior

Both filters get populated

### Logs

Nothing of relevance

### Information about your Metabase installation

```JSON
Tested on 1.47 and master
```

### Severity

It's severe if you plan to use interactive dashboards

**Comment by JesseSDevaney** [comment]
Can no longer reproduce on master:


https://github.com/metabase/metabase/assets/22608765/bb6a2544-d05a-4004-87bc-95959273a1fb
