### ISSUE TITLE
On mobile, it's impossible to see cards for dashboards with many filters

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#33670]
### Describe the bug

Dashboard filters remain sticky and never scroll out of view on mobile. When there are enough filters, they cover pretty much the entire UI, and content becomes impossible to view.

https://github.com/metabase/metabase/assets/328388/e86f8d9a-5b3d-4bcb-b7ca-010478c4fca1

### To Reproduce

1. Create a dashboard with a few cards
2. Add several filters to it (no need to wire them to cards)
3. Save it
4. Open it on mobile or in an emulated mobile view
5. You won't see the content

### Expected behavior

I'd expect the filters scroll out of view, such that the cards below can be visible

### Information about your Metabase installation

```JSON
46.7 and up
```

### Severity

Makes it impossible to use certain dashboards on mobile

### Additional context

[More info on Slack](https://metaboat.slack.com/archives/C057T1QTB3L/p1693568203242109?thread_ts=1693567514.956249&cid=C057T1QTB3L)

**Comment by prigal** [comment]
Same problem here, 0.46.8.
