### ISSUE TITLE
INT64 values from BigQuery gets rounded in some parts of Metabase resulting incorrect queries

### ISSUE THREAD

**Issue by evuolas** [metabase/metabase#33685]
### Describe the bug

It looks that some big INT64 values from BigQuery gets rounded resulting incorrect values displayed in various parts of the UI and unexpected filtering results.

I have tested this with the latest release v0.47.0 and also in the master branch. 

## Having the following table in BigQuery: 
<img width="314" alt="Screenshot 2023-09-02 at 22 22 34" src="https://github.com/metabase/metabase/assets/3945526/81cc26c2-c052-47d9-9568-4deefc9d8561">
<img width="466" alt="Screenshot 2023-09-02 at 22 23 14" src="https://github.com/metabase/metabase/assets/3945526/de836fb1-37f0-4daa-aedb-56700d6b8e94">

## And corresponding table config in Metabase:
<img width="820" alt="Screenshot 2023-09-02 at 22 31 18" src="https://github.com/metabase/metabase/assets/3945526/acac9fdc-43a4-402a-937b-64eaaeed19e0">
<img width="355" alt="Screenshot 2023-09-02 at 22 31 27" src="https://github.com/metabase/metabase/assets/3945526/c4dee3bc-15cd-44f2-9b31-cb07bad18b19">

## Metabase renders the `BookingKey` values correctly in question builder
<img width="215" alt="Screenshot 2023-09-02 at 22 30 15" src="https://github.com/metabase/metabase/assets/3945526/5cc721c2-0a6e-4d08-ace0-dffd4a6dee28">

## But when opening the "Filter by this column" the shown values are rounded and selecting any of those also results incorrect query to be run.
<img width="319" alt="Screenshot 2023-09-02 at 22 30 31" src="https://github.com/metabase/metabase/assets/3945526/cf2e28ae-8960-4ad9-8655-d8bd081c80c5">

The incorrect values are returned by the backend on `GET /api/field/<id>/values` response.
<img width="1180" alt="Screenshot 2023-09-02 at 22 35 53" src="https://github.com/metabase/metabase/assets/3945526/b8925b55-ec62-4570-a9f2-55a6fe22058d">

Similar behaviour can be seen already in the results table if `BookingKey` semantic type is removed or changed to for example "Category":
<img width="202" alt="Screenshot 2023-09-02 at 22 47 37" src="https://github.com/metabase/metabase/assets/3945526/b70fcab5-cc15-4ebe-a892-6aff3ef046ed">
<img width="176" alt="Screenshot 2023-09-02 at 22 46 12" src="https://github.com/metabase/metabase/assets/3945526/1a20d72a-81ad-4ead-bb04-18ea378f253e">

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.15.107+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Very annoying as we have all the PKs/FKs in BigQuery with generated INT64 values that are not behaving as expected in Metabase blocking us taking it into wider use.

**Comment by paoliniluis** [comment]
I think this is probably https://github.com/metabase/metabase/issues/5816, can you check?

**Comment by evuolas** [comment]
Yep, you are correct.

Values returned by the API are actually correct, but once JS processing the response the precision is lost.

<img width="1231" alt="Screenshot 2023-09-05 at 0 09 28" src="https://github.com/metabase/metabase/assets/3945526/599e152d-2988-4d76-acbb-e0680971cf55">
<img width="777" alt="Screenshot 2023-09-05 at 0 13 18" src="https://github.com/metabase/metabase/assets/3945526/dbedeac9-0c64-4b78-b3f5-1a596a90aa6d">
