### ISSUE TITLE
Unable to update an SQL question

### ISSUE THREAD

**Issue by udit-001** [metabase/metabase#33691]
### Describe the bug

I had an existing SQL question, and I recently upgraded to version 0.47, I was trying to make updates to the SQL query and save the question, but when I try to do that I get the following error:
![image](https://github.com/metabase/metabase/assets/23015406/d8c55d0c-3f31-4b19-822c-5c250bc8f1de)

### To Reproduce

1. Go to an existing SQL query
2. Make changes to it
3. Click on save
4. Select replace existing question
5. See error

### Expected behavior

I should be able to update the question without errors

### Information about your Metabase installation

```JSON
- Browser : Mozilla 116.0.3 
- Operating System : Fedora 38
- Database : PostgreSQL 14
- Metabase Version : 0.47
- Metabase Hosting Environment: Google Compute Engine
- Metabase Internal Database : PostgreSQL 14
```

### Severity

Severe as this makes us unable to update our questions

**Comment by paoliniluis** [comment]
Please wipe your cache and also purge your CDN

**Comment by udit-001** [comment]
Thanks @paoliniluis! that worked 🙌🏼
