### ISSUE TITLE
Negative number is shown in browser tab during loading cards

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#33692]
### Describe the bug

I can see negative numbers of completed requests during loading the dashboard cards

### To Reproduce

- Go to the dashboard, e.g. on stats open `/dashboard/1907-metabase-business`
- reload the page, check browser tab, notice `-11/15` loaded

https://www.loom.com/share/306315680105409ca6bc9abcc36b7b07

### Expected behavior

Number of cards in loading state should always >= 0

### Information about your Metabase installation

```JSON
Google chrome 116

metabase 0.47.1
7bacd2fa79dbe2c7635768ac5fddd24e4fe10c06
```

### Severity

P3

**Comment by ibedwi** [comment]
Hi @uladzimirdev ! I've submitted a PR that might fix the issue. I also found that this issue might be duplicated with https://github.com/metabase/metabase/issues/34767
