### ISSUE TITLE
Metabase frontend is too slow, it seems as it is not responding

### ISSUE THREAD

**Issue by quique0194** [metabase/metabase#33701]
### Describe the bug

When clicking "Show editor" button it takes 11 seconds to respond, without any user feedback.

![image](https://github.com/metabase/metabase/assets/4630204/347d2eaf-e5f0-41e2-82c8-c220ba0ae418)

While doing so, it shows peak CPU usage:

![image](https://github.com/metabase/metabase/assets/4630204/f1d2ac24-4200-4428-8640-364ac4f8407a)

Then, in the Editor, clicking any existing grouping of filtering, is similarly slow, and shows similar CPU usage.

This happens mainly with existing queries, when creating queries from zero, it is not that bad.

### To Reproduce

1. Go to an existing query
2. Click on "Show editor"
3. It takes a long time to respond
4. Click on any filter or grouping
5. It takes a long time to responde again

### Expected behavior

It should respond immediately or at least provide some kind of feedback

### Information about your Metabase installation

```JSON
- Chrome 116
- Windows 11, 64 bits
- MongoDB
- Metabase v0.47.0 hosted on ECS, internal DB is RDS postgresql
```

### Severity

Blocking usage of metabase entirely

**Comment by paoliniluis** [comment]
Probably the same as https://github.com/metabase/metabase/issues/33676

**Comment by quique0194** [comment]
@paoliniluis how can I get the table metadata? It'd a way to make sure it's the same issue

**Comment by paoliniluis** [comment]
get to the network tab and see if the endpoint takes a lot of time to load

**Comment by quique0194** [comment]
When I click on "Show editor" there is no request on the network tab. As soon as the editor appears, there is a request, but it is quite fast:
![image](https://github.com/metabase/metabase/assets/4630204/37eeee8b-09de-432f-ab37-e64cf2af40e8)

**Comment by paoliniluis** [comment]
please show the entire question

**Comment by quique0194** [comment]
here is a screen recording:

[screen-capture (1).webm](https://github.com/metabase/metabase/assets/4630204/9ad7373f-2e46-4562-a53e-e9d7aaf2639f)

**Comment by quique0194** [comment]
I'd say >100

![image](https://github.com/metabase/metabase/assets/4630204/28a13cf4-94b7-48f0-8139-55b9d8542a2a)

**Comment by paoliniluis** [comment]
same as the one I mentioned above
