### ISSUE TITLE
Add "Identifier" SQL parameter type

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3370]
Background: I was thinking about how SQL parameters could be used to address an issue like #1498.

If I write a query like this:

``` sql
SELECT {{schema}}."addresses"."ip" AS "ip"
FROM {{schema}}."addresses"
LIMIT 2000
```

I can't set `schema` as a `Text` variable because that automatically puts single quotes around its value and produces SQL like:

``` sql
SELECT 'public'."addresses"."ip" AS "ip"
FROM 'public'."addresses"
LIMIT 2000
```

I can work around this by setting `schema` to be a `Number`, which gives me sql that works as I'd like:

``` sql
SELECT public."addresses"."ip" AS "ip"
FROM public."addresses"
LIMIT 2000
```

But this raises another question -- why can I use text for a `Number` parameter?

I think the idea solution here is to add a new `Raw` type that can be used for situations like these. We should also consider enforcing the number constraint somewhere since `public` is not a number.

**Comment by MrMauricioLeite** [comment]
Isn't this dangerous for MySQL injections? =/

[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-09-19 17:00 GMT-03:00 Cam Saül <notifications@github.com>:

**Comment by camsaul** [comment]
@MrMauricioLeite if we're giving you a box to write SQL it's already dangerous in the SQL injection sense because you're already allowed to execute arbitrary SQL. So it wouldn't really become more dangerous by making it easier to tweak the SQL you execute.

**Comment by camsaul** [comment]
SQL injection is a problem when you don't want people executing arbitrary SQL; in this case this is specially what Metabase is supposed to let you do here 😉

**Comment by tlrobinson** [comment]
@camsaul It might be a little more nuanced if we want to allow people without SQL write permissions to use parameters, though I'm not sure its safe even without "raw" parameters. Have we thought through the implications of parameters + permissions yet?

**Comment by MrMauricioLeite** [comment]
Sure but what I think is that a developer is building dashboards and
probably don't want a evil user to sent on the parameters something that
could drop your datawarehouse.

The raw parameter would be a opening for that to happen. But for sure the
raw parameter would be useful.


[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-09-19 21:04 GMT-03:00 Cam Saül <notifications@github.com>:

**Comment by camsaul** [comment]
@MrMauricioLeite Keep in mind that right now evil users can just go to New Question and switch to SQL mode and run whatever SQL they want anyway.

@tlrobinson that's a very good question, @metabase/core-developers thoughts?

**Comment by salsakran** [comment]
I'm  👎  on this, in favor of better snippet support. WRT to the schema, I think it's an interesting use case, and relevant, but I shudder at the idea of expecting end users (eg, dashboard filter consumers) to enter any kind of SQL.

**Comment by salsakran** [comment]
In general, I would want our sql template game to move towards things being better typed, not less.

**Comment by camsaul** [comment]
@salsakran check out issue #1498, people have asked for something that basically exactly like this.

**Comment by MrMauricioLeite** [comment]
You are right @CamSaul, I'm thinking of an environment with user
permissions where we may not what to give SQL access to every type of user,
sorry to barge in.



[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-09-19 21:12 GMT-03:00 Sameer Al-Sakran <notifications@github.com>:

**Comment by salsakran** [comment]
I think the idea of a schema template tag would be a better fit for that than to expect end users to enter raw strings ;)

**Comment by salsakran** [comment]
Also, wrt permissions, it is very likely that folks will get the ability to execute sql templates but not have unfettered sql access to a database. 

This would, as @MrMauricioLeite correctly points out, blow that open.

**Comment by camsaul** [comment]
Something like an identifier template type would might work here then instead. e.g. double quotes / backticks instead of single quotes.

At any rate `public` isn't a number

**Comment by camsaul** [comment]
Closing since I changed my mind about wanting to add this / it doesn't fit in well with out security story

**Comment by camsaul** [comment]
Wait @tlrobinson why did you add this to the 0.23.0 milestone?
