### ISSUE TITLE
Ability to move cards between tabs in dashboards

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#33722]
**Is your feature request related to a problem? Please describe.**
To move a card from 1 tab to another you currently have to delete the card in tab 1, go to tab 2, and add the card to tab 2. This experience can be improved if we make the interaction for a drag and drop of the card to the new tab.

**Describe the solution you'd like**
Grab a card from tab 1 and move it to tab 2 like in this gif, or maybe have a setting in the card that says: "move to tab x"

**Describe alternatives you've considered**
Sample Database question:
![ezgif com-video-to-gif (4)](https://github.com/metabase/metabase/assets/132273646/8e843c8c-bed7-4e06-9d5c-6ac4ecf1cd01)

**How important is this feature to you?**
This was requested by several customers after trying the new tab feature. I would love it as well to be honest

**Additional context**
Feature request to track the epic https://github.com/metabase/metabase/issues/30578

**Comment by dobomode** [comment]
For now, we are using a simple Retool app to give us this functionality, example here:
https://www.loom.com/share/26f4fcec83ad4ea284018eee2e45e56a

**Comment by ignacio-mb** [comment]
Will be closed by the epic https://github.com/metabase/metabase/issues/34367
