### ISSUE TITLE
d is not a function after latest update to v0.47.0 when enabling Show values on data points

### ISSUE THREAD

**Issue by janez33** [metabase/metabase#33725]
### Describe the bug

Graphs stopped working after latest update

![slika](https://github.com/metabase/metabase/assets/4009092/5e1c59db-68ea-4577-9af7-827376861b7b)
![slika](https://github.com/metabase/metabase/assets/4009092/6e690ad3-e047-4051-bb63-8c3c648cf409)

If I add countries mannually it works:
![slika](https://github.com/metabase/metabase/assets/4009092/6f17d37b-2aa1-4e47-812b-48678bd14670)
![slika](https://github.com/metabase/metabase/assets/4009092/156f5b62-4bd8-46b6-91b3-3dd1734f20ee)

### To Reproduce

1. Visualization Bar
2. Gear box to open Preferences for the visualization
3. Click Display tab
4. Enable Show values on data points
5. Graphs doesnt show anymore

### Expected behavior

It should show Values on data points

### Logs

Javascript error console:
[console-export-2023-9-5_18-19-47.txt](https://github.com/metabase/metabase/files/12525992/console-export-2023-9-5_18-19-47.txt)

Logs:
`[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:53+02:00 INFO metabase.query-processor.card Question's average execution duration is 10.3 s; using 'magic' TTL of 52.0 s 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:58+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 21.7 ms (10 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (5 idle, 0 queued) (140 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:58+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 36.5 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (6 idle, 0 queued) (140 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:58+02:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 8.3 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (6 idle, 0 queued) (140 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:58+02:00 DEBUG metabase.server.middleware.log GET /api/search 200 14.7 ms (3 DB calls) App DB connections: 3/15 Jetty threads: 6/50 (3 idle, 0 queued) (140 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:58+02:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 4.7 ms (1 DB calls) App DB connections: 3/15 Jetty threads: 6/50 (3 idle, 0 queued) (140 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:58+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 31.8 ms (3 DB calls) App DB connections: 2/15 Jetty threads: 5/50 (4 idle, 0 queued) (141 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/dashboard/97 200 123.1 ms (13 DB calls) App DB connections: 1/15 Jetty threads: 5/50 (4 idle, 0 queued) (142 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 173.3 ms (5 DB calls) App DB connections: 2/15 Jetty threads: 4/50 (5 idle, 0 queued) (142 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/collection 200 142.6 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (6 idle, 0 queued) (142 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/database/7/schemas 200 21.9 ms (4 DB calls) App DB connections: 3/15 Jetty threads: 6/50 (3 idle, 0 queued) (142 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/table/367/query_metadata 200 63.8 ms (11 DB calls) App DB connections: 2/15 Jetty threads: 5/50 (4 idle, 0 queued) (142 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/table/168/query_metadata 200 113.3 ms (11 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (5 idle, 0 queued) (142 total active threads) Queries in flight: 6 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 INFO metabase.query-processor.middleware.cache Query took 6.0 s to run; minimum for cache eligibility is 8.0 s
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/3/dashcard/532/card/169/query 202 [ASYNC: completed] 6.2 s (19 DB calls) App DB connections: 3/15 Jetty threads: 3/50 (6 idle, 0 queued) (142 total active threads) Queries in flight: 5 (0 queued); mysql DB 7 connections: 5/12 (0 threads blocked)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/table/169/query_metadata 200 72.0 ms (9 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (5 idle, 0 queued) (142 total active threads) Queries in flight: 5 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/collection/165 200 12.0 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (142 total active threads) Queries in flight: 5 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 INFO metabase.query-processor.card Question's average execution duration is 1.2 mins; using 'magic' TTL of 6.1 mins 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 INFO metabase.query-processor.card Question's average execution duration is 1.3 mins; using 'magic' TTL of 6.4 mins 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:18:59+02:00 DEBUG metabase.server.middleware.log GET /api/collection/75 200 12.3 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (6 idle, 0 queued) (142 total active threads) Queries in flight: 7 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:02+02:00 INFO metabase.query-processor.middleware.cache Query took 50.5 s to run; minimum for cache eligibility is 8.0 s
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:02+02:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "7575e02e". 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:02+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/3/dashcard/639/card/768/query 202 [ASYNC: completed] 50.8 s (28 DB calls) App DB connections: 2/15 Jetty threads: 2/50 (7 idle, 0 queued) (142 total active threads) Queries in flight: 6 (0 queued); mysql DB 7 connections: 4/12 (0 threads blocked)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:03+02:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "5f2a4bdc". 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:03+02:00 INFO metabase.query-processor.middleware.cache Query took 1.5 mins to run; minimum for cache eligibility is 8.0 s
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:03+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/3/dashcard/539/card/604/query 202 [ASYNC: completed] 1.5 mins (22 DB calls) App DB connections: 2/15 Jetty threads: 2/50 (7 idle, 0 queued) (142 total active threads) Queries in flight: 5 (0 queued); mysql DB 7 connections: 5/12 (0 threads blocked)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:04+02:00 INFO metabase.query-processor.middleware.cache Query took 23.1 s to run; minimum for cache eligibility is 8.0 s
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:04+02:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "eaa1a068". 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:04+02:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "f6343aaf". 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:04+02:00 INFO metabase.query-processor.middleware.cache Query took 53.1 s to run; minimum for cache eligibility is 8.0 s
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:04+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/3/dashcard/538/card/364/query 202 [ASYNC: completed] 23.2 s (22 DB calls) App DB connections: 3/15 Jetty threads: 2/50 (7 idle, 0 queued) (142 total active threads) Queries in flight: 4 (0 queued); mysql DB 7 connections: 5/12 (0 threads blocked)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:04+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/3/dashcard/638/card/767/query 202 [ASYNC: completed] 53.3 s (22 DB calls) App DB connections: 2/15 Jetty threads: 2/50 (7 idle, 0 queued) (142 total active threads) Queries in flight: 3 (0 queued); mysql DB 7 connections: 3/12 (0 threads blocked)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:11+02:00 INFO metabase.query-processor.middleware.cache Query took 27.5 s to run; minimum for cache eligibility is 8.0 s
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:11+02:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "38e0f88c". 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:11+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/3/dashcard/537/card/365/query 202 [ASYNC: completed] 27.6 s (22 DB calls) App DB connections: 2/15 Jetty threads: 2/50 (6 idle, 0 queued) (141 total active threads) Queries in flight: 2 (0 queued); mysql DB 7 connections: 5/12 (0 threads blocked)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:46+02:00 INFO metabase.query-processor.middleware.cache Query took 47.0 s to run; minimum for cache eligibility is 8.0 s
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:46+02:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "e3dbe8c7". 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:46+02:00 INFO metabase.query-processor.middleware.cache Query took 47.0 s to run; minimum for cache eligibility is 8.0 s
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:46+02:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "26d0ff14". 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:46+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/97/dashcard/763/card/943/query 202 [ASYNC: completed] 47.2 s (29 DB calls) App DB connections: 3/15 Jetty threads: 2/50 (6 idle, 0 queued) (141 total active threads) Queries in flight: 2 (0 queued); mysql DB 7 connections: 5/12 (0 threads blocked)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:19:46+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/97/dashcard/762/card/860/query 202 [ASYNC: completed] 47.3 s (31 DB calls) App DB connections: 2/15 Jetty threads: 2/50 (6 idle, 0 queued) (141 total active threads) Queries in flight: 0 (0 queued); mysql DB 7 connections: 6/12 (0 threads blocked)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:06+02:00 DEBUG metabase.server.middleware.log GET /api/timeline 200 46.0 ms (4 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (4 idle, 0 queued) (136 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:07+02:00 DEBUG metabase.server.middleware.log GET /api/card/860 200 929.1 ms (11 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (5 idle, 0 queued) (136 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:07+02:00 DEBUG metabase.server.middleware.log GET /api/alert/question/860 200 3.0 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (5 idle, 0 queued) (136 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:07+02:00 INFO metabase.query-processor.card Question's average execution duration is 1.2 mins; using 'magic' TTL of 6.2 mins 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:07+02:00 DEBUG metabase.server.middleware.log POST /api/card/860/query 202 [ASYNC: completed] 147.4 ms (24 DB calls) App DB connections: 2/15 Jetty threads: 2/50 (6 idle, 0 queued) (136 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:07+02:00 DEBUG metabase.server.middleware.log GET /api/database/7 200 8.8 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (5 idle, 0 queued) (136 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:18+02:00 INFO metabase.public-settings.premium-features GETTING ACTIVE USER COUNT!
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:18+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 30.7 ms (10 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:18+02:00 INFO metabase.public-settings.premium-features => 114
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:18+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 33.6 ms (7 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:18+02:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 9.3 ms (2 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:18+02:00 DEBUG metabase.server.middleware.log GET /api/card/860 200 42.9 ms (11 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:18+02:00 DEBUG metabase.server.middleware.log GET /api/search 200 10.7 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 11.2 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (133 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 3.9 ms (1 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (133 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 47.7 ms (5 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (133 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/collection 200 37.9 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (133 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/timeline 200 16.8 ms (4 DB calls) App DB connections: 2/15 Jetty threads: 5/50 (2 idle, 0 queued) (133 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/card/860 200 50.0 ms (11 DB calls) App DB connections: 2/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/alert/question/860 200 4.8 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/database/7/schemas 200 11.7 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/table/367/query_metadata 200 38.2 ms (11 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:19+02:00 DEBUG metabase.server.middleware.log GET /api/table/168/query_metadata 200 73.1 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:20+02:00 DEBUG metabase.server.middleware.log GET /api/table/169/query_metadata 200 39.5 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:20+02:00 DEBUG metabase.server.middleware.log GET /api/collection/165 200 12.3 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:21+02:00 INFO metabase.query-processor.card Question's average execution duration is 1.2 mins; using 'magic' TTL of 6.2 mins 💾
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:21+02:00 DEBUG metabase.server.middleware.log GET /api/collection/75 200 54.7 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:21+02:00 DEBUG metabase.server.middleware.log POST /api/card/860/query 202 [ASYNC: completed] 289.6 ms (24 DB calls) App DB connections: 3/15 Jetty threads: 2/50 (5 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:21+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 29.7 ms (10 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (2 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:21+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 35.3 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:21+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 18.5 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:21+02:00 DEBUG metabase.server.middleware.log GET /api/collection 200 47.5 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[c2cd93e1-4c2b-47ea-b80f-45a19de854d8] 2023-09-05T15:20:21+02:00 DEBUG metabase.server.middleware.log GET /api/database/7 200 8.1 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)`

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "4.14.252-131.483.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.23"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": "Europe/Belgrade"
    }
  }
}
```

### Severity

annoying

**Comment by jvpmc** [comment]
This is happening on our end as well. It happens when you are grouping by two dimensions, one of which there is only one value and the other of which there are >8 values. For example, on a query looking at episodes viewed per user per month, we get this error when only the month of August is selected and more than 8 users are selected. If you select only one user and month of August, or if you select multiple months and more than 8 users, the data still displays as fine.

**Comment by luizarakaki** [comment]
Can you try to reproduce this using the Sample Database? I tried again following your directions, but still couldn't get the error.

Something like
count of products group by category, title
filter category: gadget

it has 2 dimensions, one with only one value and the other with multiple. I can add value labels without problems.

**Comment by timoa** [comment]
Same for us, a lot of dashboards that was working before the upgrade from 0.46.x to 0.47.0 get this error.
I will check with our Data team if they can fix some of the cards that don't work, but we're planning to downgrade to 0.46.x because it's too annoying for the marketing team.

**Comment by paoliniluis** [comment]
@jvpmc and @timoa can you reproduce with the sample dataset?

**Comment by npfitz** [comment]
I believe I have a repro with the sample dataset. Join orders and People, Filter by previous Month, and Count by User -> State, Order -> Created At:Month. Set the display to bar chart, then click show values on data points.

Will see if I can come up with a fix for whatever is going on.

![chrome_7WOUo6tQmL](https://github.com/metabase/metabase/assets/1328979/e56cdc58-7bb0-4b79-9f18-1fe0b1a06505)
