### ISSUE TITLE
Uploaded CSVs including numbers greater than integer max are truncated

### ISSUE THREAD

**Issue by drn** [metabase/metabase#33735]
### Describe the bug

Using the new upload functionality (https://www.metabase.com/docs/latest/databases/uploads), a CSV that includes a numeric column (like phone number or loyalty card number) with numeric values greater than 2,147,483,647 (integer max) will be imported and stored as integers but the values will all be set to 2,147,483,647

### To Reproduce

1. Go to a collection and upload a CSV including a numeric column with numbers greater than 2,147,483,647
2. Upload the data, then browse the data
3. All imported numeric values will be set to the integer maximum

### Expected behavior

Numeric values above integer max should be imported as BIGINT (or the default should be bigint)

### Information about your Metabase installation

```JSON
Metabase version v1.47.0
Upload database: MySQL 8.0.33
```

### Severity

Causes data loss with uploaded data

### Additional context

We were able to get around this by adding a new row to the CSV with a value `STRING` in a cell corresponding to the numerical column. This forced Metabase to import that column as a string, which preserved the data. This is a hacky workaround but works in the meantime before this is resolved.

**Comment by tsmacdonald** [comment]
Fixed by #34118

**Comment by drn** [comment]
thank you!
