### ISSUE TITLE
Native query editor window is too small; allow resizing?

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3373]
Or just make it a little more responsive on large screen sizes.

It's really difficult to edit large queries because the native query editor only shows about 12 lines max. There's a ton of wasted space on my screen that I wish I could use for editing my query.

![screen shot 2016-09-19 at 4 53 10 pm](https://cloud.githubusercontent.com/assets/1455846/18652754/c929618e-7e89-11e6-983a-7df1afd0887e.png)

**Comment by camsaul** [comment]
Going to add a +1 from @hugocar in #3404

**Comment by joscarsson** [comment]
I think allowing resize would be better than just making it bigger on bigger screens, otherwise there'll definitely be some users still thinking it is too small when they're working on that huge query :)

**Comment by KeeonTabrizi** [comment]
This is the first thing I noticed when trying metabase. I'm setting it up for some team members to use. I primarily use JackDB. I have queries that are hundreds of lines long that would be really difficult to write or work with in this fixed height area. Would very helpful to provide a substantially larger workspace to write queries.

**Comment by KeeonTabrizi** [comment]
I noted the recent commit worked on this issue: https://github.com/metabase/metabase/commit/b053ec173be5cc05aea82a358aba0312e30e2cf1

I also came up with a quick solution by altering the `NativeQueryEditor.jsx` file and adding `maxlines` and `minlines` to the following:

```javascript
        editor.setOptions({
            enableBasicAutocompletion: true,
            enableSnippets: true,
            enableLiveAutocompletion: true,
            showPrintMargin: false,
            highlightActiveLine: false,
            highlightGutterLine: false,
            showLineNumbers: true,
            minLines: 50
            maxLines: Infinity,
        });
```

This was good enough for me, but I will check out the latest commit.
