### ISSUE TITLE
Card labels, titles etc..

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3375]
While creating dashboards I often notice the following issues
- The question name is the same as the card/chart title
- To be able to indentify questions, you might need to use long unambigious names

Which result in having either long unambiguous chart titles in dashboards or many questions that are hard to identify.

I can see two ways to improve the situation
1. make title of card configurable
2. Automatically add a label with table name to each question. That would make the labeling function more useful (At the moment we hav just too many questions to label them by hand)

**Comment by flamber** [comment]
Hi @moumny 
I'm not sure when custom Title and Description was added to card settings, but now you can give descriptive (long) names to your questions, while displaying short titles in dashboard cards. On 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52812889-23f79d00-305e-11e9-9103-b47a77c2e6ae.png)

**Comment by salsakran** [comment]
we've had dashcard title control for a while. closing,
