### ISSUE TITLE
[MLv2] Add a method changing query's `source-table`

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#33759]
We need a method to change query's `source-table`. It should support both raw tables (integer table ID) and `card__<int>` syntax for cases when a question is based on a model or another question. Once called, it should also remove all the clauses of a query.

We already have a `with-different-database` method to change a database (planned to be used in the native query editor), so maybe we can call this one `with-different-table` for consistency? Expected signature:

```ts
const anotherTableId = 2

// New table's metadata should be present in query's metadataProvider (FE should ensure that)
const nextQuery = Lib.withDifferentTable(query, anotherTableId)
```

**Comment by camsaul** [comment]
Mentioned on Slack but this can be extremely dumb for now and basically reset the entire query, we don't need to try to preserve anything yet. In the future we have plans to make stuff like this smarter e.g. keep filters if there's a field with the same name in the new table, but that's out of scope for this issue
