### ISSUE TITLE
Unnecessary scrollable search filter modal

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#33778]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6830683/63fc07f8-a336-4cfb-8264-5396ff64e786)

### To Reproduce

1. Open up "Filter by" modal in global search

### Expected behavior

1. The modal should not be horizontally scrollable.
2. The "Type" input group should be aligned with modal footer & header

### Information about your Metabase installation

v47, 90b4cde

### Severity

P3

**Comment by rafpaf** [comment]
This modal has been replaced with a dropdown menu:

![image](https://github.com/metabase/metabase/assets/130925/8c931b87-8ad8-43f8-ac41-e8428a4e7957)
