### ISSUE TITLE
query_metadata does not load in parallel

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33786]
### Describe the bug

When you have a table that links to many other tables, the query metadata is pulled one after another instead of doing that concurrently. Most probably we're doing a for loop there where it should be a parallel GET

![image](https://github.com/metabase/metabase/assets/1711649/ca9c8ffe-2d5a-46cb-9ec9-5824a252b849)

### To Reproduce

Using the soccer dimensional model I left in https://github.com/metabase/metabase-qa/pull/38 do the following:
1) load it on a postgres db
2) open the browser developer tools on the network tab
3) go to new->question. Pick soccer as the schema
4) clear the network tab so you can see the exact requests to query_metadata
5) now pick the fact table and see the results
![image](https://github.com/metabase/metabase/assets/1711649/46946632-8850-4b16-98f0-148c80bc28a6)

![image](https://github.com/metabase/metabase/assets/1711649/e4c8656e-f360-4c87-94dd-3bd732135487)

### Expected behavior

We should send requests in parallel when possible

### Logs

NA

### Information about your Metabase installation

```JSON
since the beginning of the times
```

### Severity

P3

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/pull/42953
