### ISSUE TITLE
Version info could have duplicated versions

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#33803]
### Describe the bug

The older version from `http://static.metabase.com/version-info-ee.json` could contain the latest version
![image](https://github.com/metabase/metabase/assets/25661381/23597d1c-8579-4d38-9119-1a5513602860)

This could happen for cases where we release a version twice, but that' totally possible so the code to update version info should prevent this.

### To Reproduce

^

### Information about your Metabase installation

```JSON
master
```

### Severity

P3? since it does not really introduce any bug

**Comment by iethree** [comment]
sorta related to https://github.com/metabase/metabase/issues/33729

**Comment by crisptrutski** [comment]
Alternatively, is the intention that I write defensive code around reading and writing the file in `release.version-info`?

**Comment by crisptrutski** [comment]
I went with adding defensive code, based on the context given in https://metaboat.slack.com/archives/C010L1Z4F9S/p1694093525459809
