### ISSUE TITLE
[MLv2] [BE] `drill-thru/zoom-in.timeseries` doesn't show for ORDERS grouped by CREATED_AT

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#33811]
Timeseries-zoom drill was added in https://github.com/metabase/metabase/pull/33574 . 
But I haven't managed to trigger for a simple orders query with breakout by created_at - see these unit tests - https://github.com/metabase/metabase/blob/33973-mbql2-drills-quick-filters/frontend/src/metabase-lib/drills.unit.spec.ts#L1139 (and other parts marked with `metabase#33811`)

https://github.com/metabase/metabase/assets/7983744/86eed922-ef6e-41f6-9b15-2380c4acb44c

**Comment by camsaul** [comment]
I think this might actually just be an FE bug, see discussion in https://metaboat.slack.com/archives/C04CYTEL9N2/p1695929177537919

**Comment by camsaul** [comment]
reopening based on discussion in https://metaboat.slack.com/archives/C04CYTEL9N2/p1695990363844759?thread_ts=1695929177.537919&cid=C04CYTEL9N2

**Comment by camsaul** [comment]
ok so this is actually fixed after all, but the tests were still commented out because of a bug in the tests (they should have been `:cell` rather than `:header` test cases). I'll update in a separate PR
