### ISSUE TITLE
Add Trino database driver

### ISSUE THREAD

**Issue by YuriyGavrilov** [metabase/metabase#33818]
**Is your feature request related to a problem? Please describe.**

Just to add new driver as Trino

**Describe the solution you'd like**

Possibilities to connect to Trino cluster

**Describe alternatives you've considered**

The also will be support alternative Trino engine but on steroids as Cedrus (https://www.cedrusdata.ru/download)

**How important is this feature to you?**

Mandatory:)

**Additional context**

by adding Trino as a source you also add all the supported other sources by Trino.

**Comment by paoliniluis** [comment]
There’s a driver made by the starburst team for Trino, I would suggest you check that out

**Comment by YuriyGavrilov** [comment]
Thanks @paoliniluis
