### ISSUE TITLE
X-ray filters break all charts

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#33821]
### Describe the bug

Applying any filter in X-ray breaks all charts in the X-ray

https://github.com/metabase/metabase/assets/6830683/6b66bc23-55ef-4b36-9963-15b03ec11f6f

### To Reproduce

1. Go to [Browse data](http://localhost:3000/browse)
2. Click "Sample Database"
3. Hover over Accounts table
4. Click the :zap: icon to X-ray the table
5. Apply any filter, e.g. Plan: Basic

All charts fail to render.
Problem is still there after saving the X-ray as a dashboard.

### Expected behavior

Charts update & render correctly

### Information about your Metabase installation

v47.1 `master`, 1ec0be3e3f

### Severity

P1/P2

**Comment by NevRA** [comment]
Cause by this https://github.com/metabase/metabase/pull/33656
