### ISSUE TITLE
Changing a column's visibility to detail only does not save for models

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#33844]
### Describe the bug

For a model (not table), when changing the visibility of a column to details view only, it does not save.  

### To Reproduce

1. Create a SQL model
2. Edit metadata for model to change one column's visibility to "Details view only"
3. Save changes exits out of edit view however no changes happen and the column is still visible in table view

### Expected behavior

Changing visibility to details view only should save

### Logs

No exceptions in log

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.186-179.751.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "redshift",
      "mysql",
      "postgres",
      "bigquery-cloud-sdk",
      "mongo",
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-08",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "716e8b1"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

Minor as it is mostly presentation

**Comment by calherries** [comment]
I can't reproduce this exactly but I could find some inconsistent state if I go "Edit metadata", and switch to the "Query" tab. The details only column is shown.

https://www.loom.com/share/f963792cea3b4ff490add1bc83a34a71?sid=450d877f-5f74-4bb4-a2d2-03fa06dc0a3b

Max, are you able to reproduce this again and share a loom?

**Comment by beanaroo** [comment]
I'm having this problem too. Will try to do a loom share but will need to sanitize the data presented somehow...

In this example, i'm trying to restrict the JobURL column to detail view only. (but this is happening for multiple columns on multiple models)

- In the UI, it does not save/load the setting in metadata view or have any effect in table view.
- In the metabase db, it appears `visibility_type` is saved
- No backend errors/warnings logged
- Some frontend warnings logged when loading table view "Removing invalid MBQL clause"

### Metadata:
![image](https://github.com/metabase/metabase/assets/1748909/6a07d8bc-70f3-4b3f-a343-d537c8430e0a)

### Table View:
![image](https://github.com/metabase/metabase/assets/1748909/c86cf2a8-d8ab-4288-a0f7-97a0c7cf72bc)

### report_card record
![image](https://github.com/metabase/metabase/assets/1748909/e02883dd-28e4-42de-9a30-9145ed466114)

### Browser console logs
![image](https://github.com/metabase/metabase/assets/1748909/d86245b2-464b-404f-8617-34d474e55877)

**Comment by kamilmielnik** [comment]
Cannot reproduce in 0.46.7, 0.47.0, 0.48.0, 0.49-RC2, master at ef9fb05784.

But I can still reproduce the issue from Cal's video.
I can also see more weird things related to "detail views only":
1. Create a new SQL model: `select * from orders` (don't save it)
2. Run the query
3. Switch to Metadata tab
4. Click "Discount" column header
5. Change its visibility to "Detail views only"
6. Switch to Query tab - "Discount" column is present (bug)
7. Switch back to Metadata tab:
    - "Discount" column is gone (bug)
    - "Created At" column is selected (bug)
    - The sidebar shows info for the "Discount" column (bug)
8. Change column name in the sidebar
9. Discount column magically appears now
10. Save the model
11. Now the issue from Cal's video is reproducible.

Let's keep this issue open to resolve all these issues together.
