### ISSUE TITLE
customize expression using case promote aggregation restriction

### ISSUE THREAD

**Issue by horusli** [metabase/metabase#33848]
### Describe the bug

using 0.47.1 release metabase, it reports following error when try to bucketing data into cycle range.

![image](https://github.com/metabase/metabase/assets/6522657/c6eaf9b2-755e-4522-b961-2e731b663bea)

 

### Expected behavior

based on the value of spc cycle to label corresponding records  into different range gorup.

### Information about your Metabase installation

```JSON
metabase version: 0.47.1
```

### Severity

blocking my usage of metabase to do more deep analysis of my data

**Comment by paoliniluis** [comment]
do a custom column, not a custom expression
