### ISSUE TITLE
Inconsistent relative date filter behaviour on question and SQL query

### ISSUE THREAD

**Issue by romanzdk** [metabase/metabase#33862]
### Describe the bug

We have table "A" in our database. We create super simple _question_ out of it (basically simple SELECT) + using relative date filter which looks like: `Previous X days, starting Y days ago`. Then we create _SQL query_ from the same table and we specified it like:

```sql
SELECT * 
FROM A
WHERE {{ date }}
```
where date is our `Field Filter` on the same table on `Date` column. The issue is that when we select the very same relative date filter settings we get different result than from the question. 

Considering we apply the filter on 2023/09/11, if we set: X = 31, Y = 3 then we get:
* question: records between 2023/08/08 - 2023/09/08
* SQL query: records between 2023/08/11 - 2023/09/08

Our current workaround is to explicitly tell users to _not_ use relative date filter in form above - specific start/end date filters work fine.

### To Reproduce

See description above

### Expected behavior

Records should be the same in both question and sql query

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.4.0-148-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.6 (Ubuntu 14.6-1.pgdg22.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

annoying

**Comment by luizarakaki** [comment]
@romanzdk I can't reproduce this. Can you give us more information? Tried it on Postgres and didn't get problems.
Past 31 starting 3 days ago always return 2023-08-09 > 2023-09-08 to me

**Comment by ignacio-mb** [comment]
Hi @romanzdk is this still happening? What is the DB that you are querying?
