### ISSUE TITLE
Automatic Insights drill not using custom port for localhost

### ISSUE THREAD

**Issue by parkerdaminer** [metabase/metabase#33866]
### Describe the bug

I'm running Metabase on localhost on port 3333 instead of 3000.

When I run the Analytics Drill from a dashboard graph, then choose X-Ray or Compare To, I get the same results:

This site can’t be reached
localhost refused to connect.

The URL shows it going to: http://localhost:3000/auto/dashboard/question/3/cell/WyJhbmQiLFsiPSIsWyJmaWVsZCIsNDIyOSx7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWVXaXRoTG9jYWxUWiIsInRlbXBvcmFsLXVuaXQiOiJkYXkifV0sIjIwMjMtMDgtMTJUMDA6MDA6MDAtMDQ6MDAiXSxbIj0iLFsiZmllbGQiLDQyNDAseyJiYXNlLXR5cGUiOiJ0eXBlL0JpZ0ludGVnZXIifV0sMTBdLFsiPSIsWyJmaWVsZCIsNDIyMSx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiSGFuc29uIl1d/compare/table/201

Here's a video: https://www.loom.com/share/ed811d2f0f404033ab8126ebf3aedfa2?sid=d6abea35-6278-4ca1-bd73-0b1bb01fd019

So it looks like my port 3333 gets lost. If I manually change the port, then Compare This works pretty well. For X-Ray on changing the port back to 3333, the cards within the dashboard show "No Result" with either a 404 error or a 202 accepted response.

### To Reproduce

1. Run Metabase on localhost on a non-default port
2. Go to a dashboard
3. Click on the graph and show the Automated Insights.
4. Click on X-Ray
5. See error - it tries to go to port 3000

### Expected behavior

It should use the port specified

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20.0.2+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "20.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20.0.2+9",
    "os.name": "Mac OS X",
    "os.version": "13.4.1",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-07",
      "tag": "v0.47.1",
      "branch": "release-x.47.x",
      "hash": "bd278b9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

$ env | grep PORT
MB_JETTY_PORT=3333
```

### Severity

Blocking a cool feature for users. Semi annoying.

**Comment by paoliniluis** [comment]
What do you have in the settings->admin-> site url?

**Comment by parkerdaminer** [comment]
Ooh, I do have localhost:3000 there. Changed it. Now the drills are working.
