### ISSUE TITLE
Log why Serialization v2 fails when trying to export a dashboard that contains cards in outside collections

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33882]
### Describe the bug

Seems like a dependency issue, where if you use the --collection flag, the process will fail exporting everything when a dashboard has a card outside of that collection

### To Reproduce

1) set up a plain empty instance, create a /target folder so you can export to it
2) click on any x-ray, save the created dashboard
3) then move any card from the created collection to the root collection
4) run "java -jar /app/metabase.jar export /target --collection 3", see that there's no card being exported to the /target folder

### Expected behavior

should we send an error? or just export the cards that are in that collection

### Logs

2023-09-13 09:45:16,673 INFO v2.extract :: Dashboard cards outside the collection
2023-09-13 09:45:16,673 INFO v2.extract :: ======================================
2023-09-13 09:45:16,679 INFO v2.extract :: Dashboard 1: A look at People

2023-09-13 09:45:16,680 INFO v2.extract ::           	Card 3: User growth

2023-09-13 09:45:16,680 INFO v2.extract ::         from collection [no collection]

2023-09-13 09:45:16,683 INFO serialization.cmd :: Export to /target complete! 🚛💨 📦
metabase_origin:/# ls /target/

### Information about your Metabase installation

```JSON
47.x
```

### Severity

P2

### Additional context

We need some help from the product team on this one

**Comment by paoliniluis** [comment]
@luizarakaki need your help here

**Comment by luizarakaki** [comment]
The logs are bad, but the behavior was intentional.

I think we should improve the error message/logs, would this be good enough?

**Comment by darksciencebase** [comment]
@luizarakaki what message would you want to see? or shall we surprise you?

**Comment by luizarakaki** [comment]
I think something at the warning level makes sense:

WARN: Failed to export Dashboard {{id}} containing Card {{id}} saved outside requested collections
