### ISSUE TITLE
Enable SQL-based Sandboxing without relying on database roles

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#33884]
**Is your feature request related to a problem? Please describe.**
- Some users need SQL-based sandboxing but don't have access to database roles
- Some databases are more difficult to implement role-based "impersonation" sandboxing

**Describe the solution you'd like**

**Describe alternatives you've considered**
- Role-based connection "impersonation"
  - https://www.metabase.com/docs/latest//api/ee/advanced-permissions-impersonation
- Workaround:
  1. Setup Sandboxing on a table that can be joined to the SQL question (must have a join condition that aligns with sandboxing attributes)
  1. Create a saved GUI question that is a SELECT * FROM the sandboxed table
  1. Create a SQL question/model and INNER join the results at the end (not in a CTE) with the Saved GUI Question of the sandboxed table
  1. Save the query in a collection where the end user has only View access and not Curate access.

**How important is this feature to you?**
- Requested from users daily to weekly.

**Additional context**
related to:
- https://github.com/metabase/metabase/issues/33881

**Comment by paoliniluis** [comment]
Isn’t this the same as https://github.com/metabase/metabase/issues/23858?
