### ISSUE TITLE
Linked filters are not working with "Custom List" or "From another model or question"

### ISSUE THREAD

**Issue by Kavinya21** [metabase/metabase#33892]
### Describe the bug

I am trying to use linked filter in dropdown but it not working
- But after saving when filter1 is selected filter2 is not limiting its value based on the filter as it is linked all the values are appearing.

### To Reproduce

- Dropdown filters have been used via filter --> Text or Category --> is --> Dropdown.
- In Selectable value tried both **From another model or question** and **Custom list**.
- In the Linked filter **Limit this filter's choices** have also been selected.

### Information about your Metabase installation

```JSON
Google Chrome Version 116.0.5845.188 
Window 11
Postgres
Metabse Version 0.47.0
```

### Severity

Not able to connect any of teh linked filters

**Comment by calherries** [comment]
Repro'd. 

If the limited filter's values source is either of type "Custom list" or "From another model or question" then the filter values are not limited in the dropdown. It doesn't matter what the type is for the filter doing the limiting.

<img width="214" alt="image" src="https://github.com/metabase/metabase/assets/39073188/3d02f388-1d14-4edb-92f3-3f7f9e3e68b2">

Here's a full demo:
https://www.loom.com/share/f9c221a0486d4638b0b11b35359ebb63?sid=fca14dbe-ce10-41e1-a45f-f0fdd2056df3

**Comment by calherries** [comment]
@cdeweyx Linked filters have never worked with filters that have "Custom List" or "From another model or question" as their values source. What should we do here? 

I see two paths forward:
1. Support linked filters for "Custom List" and/or "From another model or question". The downside is development time vs other features. Linked filters for "Custom List" is relatively easy and "From another model or question" is much more difficult and should probably wait for the MLv2 refactor to complete.
2. Enforce linked filters to never be enabled when the values source is one of these options. We can add a BE migration on previously created filters so their linked filters toggle is disabled with these options, and we can update the UI to prevent it being set on new parameters. This is considerably less work than (1).

Aside from this issue, linked filters only work for GUI questions, not native ones (I can't find an issue for this). That's probably not changing any time soon either, at least until MLv2 is complete. We face the same decision with that issue too. 

Related #16872

**Comment by calherries** [comment]
[From slack](https://metaboat.slack.com/archives/C057T1QTB3L/p1696573883883329?thread_ts=1696518563.953549&cid=C057T1QTB3L)

Path 1 was chosen. 

Then it needs three changes:
1. On the backend, a migration to recover valid state without changing the behaviour. Filters with linked filters toggled on and one of “Custom list” or “From another model or question” as their values source will be migrated to have linked filters turned off.
2. On the frontend, the linked filters tab when the source of values is “Custom list” or “From another model or question”. We already have a way to display a disabled state when there are no other filters, so we will reuse that and update the message:
![image](https://github.com/metabase/metabase/assets/39073188/1478a53c-8aa7-4c11-b4fb-463e5cb1a883)
3. The “Selectable values” modal look when a linked filter toggle is enabled? Presumably we need to explain why “Custom list” and “From another model or question” cannot be selected when linked filters are enabled
![image](https://github.com/metabase/metabase/assets/39073188/88c8c585-63c8-454c-b130-4177f91f6b3c)

**Comment by calherries** [comment]
Another TODO: update https://www.metabase.com/learn/dashboards/linking-filters

**Comment by leoncydsilva** [comment]
@calherries Hey hope you're doing well, 
we are facing the same issue. . This will be a dealbreaker for us.
We are using MongoDB as data layer and fields are generated through query (as QUESTION || MODEL) and we can't create connected fields as the fields are populated based on query (not directly available on DB). Can you please suggest a workaround for this if possible

Please find the attached query and image (Both Criteria are not working)
1). If we select city -> Area Manager and Field Tech dropdowns should be filtered
2). If We select City and Area Manager -> Field Tech dropdown should be filtered


[sample_query.json](https://github.com/metabase/metabase/files/12885277/sample_query.json)
![Screenshot 2023-10-12 at 10 39 17 PM](https://github.com/metabase/metabase/assets/45206626/783d0718-0cf7-4420-97f6-52a65000f308)

**Comment by calherries** [comment]
@leoncydsilva I've had a look at your problem and that is actually a separate bug, which I've created here: https://github.com/metabase/metabase/issues/34570 

Linked filters were never designed to work with native query variables, only field filters in SQL queries or questions created through the notebook editor (a GUI question). If you need to use a native query in your dashboard, the only workaround I know is to use a question created from the notebook editor, add it to the same dashboard, and wire up each filter to both the GUI question and the native query. As long as each filter is wired to a GUI question's field, linked filters will work.

**Comment by calherries** [comment]
This will be solved by these three PRs in 48:
- https://github.com/metabase/metabase/pull/34424
- https://github.com/metabase/metabase/pull/34438
- https://github.com/metabase/metabase/pull/34531

**Comment by alex-axiobit** [comment]
I created a view  in my database with all the required fields as a workaround. Unfortunately the **Linked filters** do not work in this situation either.
