### ISSUE TITLE
Open a link in the same window

### ISSUE THREAD

**Issue by Roman2nc** [metabase/metabase#33915]
Links are great for navigating from dashboard to dashboard, but currently they open a new window every time.
There should be an option to choose how it opens, and it's preferable to stay in the same window for easier navigation.

**Comment by fran060** [comment]
hi, did you find a solution?

**Comment by Roman2nc** [comment]
Hello,
On the latest version, I no longer have this problem.
sincerely

**Comment by paoliniluis** [comment]
@Roman2nc can you please update all the posts in Discourse and also the github issues where you posted with the solution you found? thannks

**Comment by fran060** [comment]
Hi @Roman2nc thanks for your response, you are running v0.48.8 or previuos one?

**Comment by fran060** [comment]
@paoliniluis Hi Luis, I just only create a topic in metabase help forum and I created this account in github asking for help, nothing else. The email you mean "our support", which one is it? Can i write you in spanish?

**Comment by Roman2nc** [comment]
I'm currently on version 1.48.4, and the problem no longer exists.
I don't know since which release this has been fixed.
