### ISSUE TITLE
Missing one API

### ISSUE THREAD

**Issue by ankushmandalZipteams** [metabase/metabase#33918]
### Describe the bug

Previously, I created a Python code that would take all the cards from one dashboard and recreate it by changing only the `company_id` in the query. After recreating a card, it would store the card in a new collection and create a dashboard with the new card by adding the card details to the `ordered_card` in the dashboard info and then post it. This process would create a new dashboard with cards that had the changes applied in the query.

However, with the recent update, the API I was using to upload the cards to the dashboard is showing an error. The error message is: 'The API doesn't exist.' Here's the relevant code snippet:

```python
for i in new_dashboard_info["ordered_cards"]:
    dashboard_update = requests.post(
        f"https://metabase._company_name_.com/api/dashboard/{new_dashboard_id}/cards",
        headers=headers,
        json=i,
    )
```

The variable 'i' contains the details of the card.

I have been using this code for the last 2-3 months, and it was working properly. However, due to a recent update, I am no longer able to use it."

### To Reproduce

# dashboard_info is the information of the original dashboard.
# new_dashboard_info is the information of the new dashboard
```
for i in dashboard_info["ordered_cards"]:
    if i["card_id"] is None:
        n = {
            "size_x": i["size_x"],
            "col": i["col"],
            "visualization_settings": i["visualization_settings"],
            "size_y": i["size_y"],
            "row": i["row"],
        }
        new_dashboard_info["ordered_cards"].append(n)
    else:
        for j in i["parameter_mappings"]:
            j["card_id"] = target_card_name_id_mapping[i["card"]["name"]]
        n = {
            "size_x": i["size_x"],
            "col": i["col"],
            "cardId": target_card_name_id_mapping[i["card"]["name"]],
            "size_y": i["size_y"],
            "row": i["row"],
            "card_id": i["card_id"],
            "parameter_mappings": i["parameter_mappings"],
            "visualization_settings": i["visualization_settings"],
        }
        new_dashboard_info["ordered_cards"].append(n)
# Updating the new dashboard with the newly ordered cards
for i in new_dashboard_info["ordered_cards"]:
    dashboard_update = requests.post(
        f"https://metabase.zipteams.com/api/dashboard/{new_dashboard_id}/cards",
        headers=headers,
        json=i,
    )
```

### Information about your Metabase installation

```JSON
- Browser: Google Chrome Version 116.0.5845.188 (Official Build) (64-bit)
- Operating System: Windows 11
```

### Severity

This code automates the process of generating a new dashboard whenever a new customer registers an account for their company. However, it is currently experiencing issues due to the time-consuming nature of creating four dashboards for each customer. Managing multiple clients has become a challenging task as a result.

**Comment by qnkhuat** [comment]
We’ve removed POST, DELETE and refactored the PUT /api/dashboard/:id/cards endpoint to handle editing dashboard cards. You can find details here https://github.com/metabase/metabase/pull/29641
