### ISSUE TITLE
bad gateway 502 for API via reverse proxy (POST request ignores 'location' v0.47.2)

### ISSUE THREAD

**Issue by firstDismay** [metabase/metabase#33910]
I am using an nginx reverse proxy server with a location alias `https://my_server/metabase` . At the same time, the interface and the administration mode work correctly:
```
https://my_server/metabase/admin/troubleshooting/help
https://my_server/metabase/collection/2-aleks
```
But when accessing the API or downloading, I get incomplete links without an alias:
```
https://my_server/api/util/diagnostic_info/connection_pool_info
blob:https://my_server/1aad8658-4006-4366-b702-a81c09f9e0a9
```
In this case, nginx cannot redirect traffic to the metabase address, and I get an bad gateway 502. 
**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "ru",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 YaBrowser/23.7.5.734 Yowser/2.5 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.7+7-Debian-1deb11u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-17",
    "java.version": "17.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.7+7-Debian-1deb11u1",
    "os.name": "Linux",
    "os.version": "5.10.0-25-amd64",
    "user.language": "ru",
    "user.timezone": "Asia/Yekaterinburg"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.9 (Debian 14.9-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-07",
      "tag": "v0.47.1",
      "branch": "release-x.47.x",
      "hash": "bd278b9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by firstDismay** [comment]
I'm sorry. The dumber the error, the harder it is to find it. I have killed so much time, the problem was in the forwarding settings.

**Comment by firstDismay** [comment]
The problem is partially resolved in version 0.47.2. Download requests started working. But POST requests to the API usually do not take into account the location:

`https://my_server/api/util/diagnostic_info/connection_pool_info`
`502 Bad Gateway`.
The reason is the same

**Comment by paoliniluis** [comment]
@uladzimirdev can you check this one out?

**Comment by uladzimirdev** [comment]
@firstDismay could you please provide an example of the POST request you've wrote about to get a better understanding of the problem. How do you talk to the API?
as I see in the [docs](https://www.metabase.com/learn/administration/metabase-api), usually the full path is used to make an http request to metabase 

Indeed 0.47.2 contains a fix for downloading resources when metabase is deployed at subpath (https://yourserver.com/metabase), but our recommended approach is to use sub domain (`metabase.yourserver.com`).

**Comment by firstDismay** [comment]
@uladzimirdev, i use the following reverse proxy settings:
```
location /metabase/ {
                rewrite ^ $request_uri;
                rewrite ^/metabase(/.*) $1 break;
                proxy_pass                              http://127.0.0.1:3000$uri;
                proxy_http_version                      1.1;
                proxy_cache_bypass                      $http_upgrade;
                proxy_set_header Upgrade                $http_upgrade;
                proxy_set_header Connection             $http_connection;
                proxy_set_header Host                   $host;
                proxy_set_header X-Real-IP              $remote_addr;
                proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto      $scheme;
                proxy_set_header X-Forwarded-Host       $host;
                proxy_set_header X-Forwarded-Port       $server_port;
        }
location / {
	        proxy_pass         http://localhost:5144;
		proxy_http_version 1.1;
		proxy_set_header   Host $host;
		proxy_set_header   X-Real-IP $remote_addr;
		proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header   X-Forwarded-Proto $scheme;
		proxy_cache_bypass $http_upgrade;
		proxy_set_header   Connection "";
	}
```
To reproduce the remaining error you need to follow the steps:

1. Enter administration mode.
2. Go to the Troubleshooting tab.
3. Select the "Help" section
4. Scroll down the page and click on the menu item "Connection Pool Details":
`502 Bad Gateway`

`2023/09/20 14:50:44 [error] 93428#93428: *130 connect() failed (111: Connection refused) while connecting to upstream, client: 11.111.111.111, server: my_server, request: "GET /api/util/diagnostic_info/connection_pool_info HTTP/1.1", upstream: "http://[::1]:5144/api/util/diagnostic_info/connection_pool_info", host: "my_server"`

**Comment by uladzimirdev** [comment]
@firstDismay just to double check: is the provided URL the only problematic or were there other broken links/urls?

**Comment by firstDismay** [comment]
@uladzimirdev, these are all the errors I encountered when deploying to a location.

**Comment by Tony-metabase** [comment]
@uladzimirdev FYI there is another issue for enterprise not sure of related:

```
"message": "No implementation of method: :write-body-to-stream of protocol: #'ring.core.protocols/StreamableResponseBody found for class: clojure.lang.PersistentArrayMap",
```

This happens when you go to Admin -> Permissions -> Application -> perform a change there and try to save

<img width="1509" alt="image" src="https://github.com/metabase/metabase/assets/110378427/32c96513-4441-4cba-95cb-26cb029333b0">

Changes in the other Permission tabs (Data & Collection) works

**Comment by uladzimirdev** [comment]
@firstDismay I linked the PR which should fix the problem with connection pool broken link and permissions changes.

As per other POST requests you mentioned (if any is still broken), please double check your proxy settings, we have a working example here https://github.com/paoliniluis/metabase-subpath

**Comment by firstDismay** [comment]
@uladzimirdev, thanks for the working configuration example, it was helpful. Your speed of reaction to such important questions is impressive. I have just started exploring the possibilities of your solution for solving analysis and reporting tasks, and your standalone solution is very suitable. At the moment I have no other errors with proxying. Thank you.
