### ISSUE TITLE
Update logs to S3 deletes configuration

### ISSUE THREAD

**Issue by mkemka** [metabase/metabase#3392]
I am using the ELB installation of metabase. I updated the configuration to spool logs to S3 and it appears that all of the database settings have been deleted. When I access the instance it asks me to create an account all over again.

**Comment by tlrobinson** [comment]
Are you using RDS to store Metabase's application database, as described in the "Using RDS with metabase" section here? http://www.metabase.com/docs/v0.19.3/operations-guide/running-metabase-on-elastic-beanstalk.html#deploying-new-versions-of-metabase

**Comment by salsakran** [comment]
Did you "terminate" the elastic beanstalk environment? This will cause the RDS instance backing the environment to be killed and data lost, as you describe. However, there is a very prominent alert to this effect when you do so.

**Comment by camsaul** [comment]
@mkemka ?

**Comment by mkemka** [comment]
This is a error on my end. I did not set up the RDS properly (deploying a number of services at once) and the settings were stored in h2 which as you mentioned is deleted when there is a large config change.
