### ISSUE TITLE
Models containing joins and repeated column names break the metadata editor

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#33959]
### Describe the bug

Metadata editor behaves incorrectly when there are tables with multiple joins, and repeated column names
- click behavior is incorrect, highlighting the wrong column
- columns displayed gets changed without reordering or saving columns

### To Reproduce

1. Create a new model: Sample Data, Orders, left join Products
2. Click on the triangle button so that results appear
3. Click on Metadata
2. Go to edit metadata
3. Click on Products --> ID, and see the next column label (Products --> Title) is highlighted
4. Click on Products --> Category, and see the next column label (Products --> Vendor) is highlighted
5. Click on Products --> Title, and see the previous column label (Products --> ID) is highlighted
6. Save the model, and open editing the query again
7. Remove and re-add ID as a selected column from Products
8. An additional column gets added with the label of Product ID, actually containing titles.

Screen recordings:
https://github.com/metabase/metabase/assets/11080638/afb4774f-7059-4c42-8fc5-f7a9a2fb6eb1
https://github.com/metabase/metabase/assets/11080638/565cea91-4306-4790-8e0a-8b5b2da933a9

### Expected behavior

Joining multiple tables with columns of the same name should not break the editor

### Logs

n/a

### Information about your Metabase installation
This is reproducible on stats.metabase.com as of this release: built on 2023-09-19, branch: master, hash: c802a23.
I could not reproduce it elsewhere, but similar errors have been reported by other users.

### Severity

Some users have reported similar issues.

**Comment by calherries** [comment]
I couldn't repro on master, but I could on stats.

**Comment by cbalusek** [comment]
The customer that reported this was running 1.47.1

**Comment by kamilmielnik** [comment]
Cannot reproduce in stats. Cannot reproduce in 0.47.1.
Reproducible in `master` at ef9fb05784.
