### ISSUE TITLE
Metabase does not retrieve the whole dataset from Druid

### ISSUE THREAD

**Issue by edevil** [metabase/metabase#3396]
I've tried with the latest Metabase master (f13be5c) and stable v0.19.3, the problem remains.

I have a Druid (0.9.1.1) with a dataset containing 4.2M rows, but even while fetching a simple count Metabase underreports this number. I've compared the query it does to Druid with the one Pivot does (Pivot reports the correct number).

Metabase:
![screen shot 2016-09-26 at 11 52 26](https://cloud.githubusercontent.com/assets/12426/18831819/c9ea8b9c-83df-11e6-90e9-623a66b8f16c.png)

Pivot:
<img width="806" alt="screen shot 2016-09-26 at 11 52 42" src="https://cloud.githubusercontent.com/assets/12426/18831825/d416cff4-83df-11e6-8368-33e80a658234.png">

Metabase query:
```
{"intervals":["1900-01-01/2100-01-01"],
"granularity":"all",
"context":{"timeout":60000},
"queryType":"timeseries",
"dataSource":"allusers",
"aggregations":[{"type":"count","name":"count"}]
}
```
Metabase response:
```
[{"timestamp":"2000-01-01T00:00:00.000Z","result":{"count":1218955}}]
```

Pivot query:
```
{"queryType":"timeseries",
"dataSource":"allusers",
"intervals":"1999-12-31T00:01Z/2000-01-01T00:01Z",
"granularity":"all",
"context":{"timeout":40000},
"aggregations":[{"name":"count","type":"doubleSum","fieldName":"count"}]
}
```
Pivot response:
```
[{"timestamp":"2000-01-01T00:00:00.000Z","result":{"count":4166544.0}}]
```

All my datapoints have the same timetamp, "2000-01-01T00:00:00.000Z", can this be the cause? Either way, I was expecting metabase to be able to report the correct number. From the query I can see that it requests a different aggregation, still I do not see why it gets a different result.

**Comment by moumny** [comment]
In pivot you are requesting the Sum of all the fields called "count" while in metabase you are checking the count of rows which is the count of "buckets" or aggregation. You should get the same number in metabase using sum of "count"

**Comment by edevil** [comment]
Ah, now I understand. Thanks!
