### ISSUE TITLE
To be able of downloading dashboards (data)

### ISSUE THREAD

**Issue by jesusrtc** [metabase/metabase#3399]
This is useful for final users instead of going to questions but mainly important to download de merged questions with your excellent tool "Combining two existing saved questions" Which I must to say It's amazing.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
@jesusrtc I'm not sure I understand what you're asking, can you explain a little more what you want to do?

You can already download the results of a question as a CSV file.

**Comment by jesusrtc** [comment]
Sure.

This screenshot is from a dashboard.
This chart comes from two different questions (green and red).
To get a csv I need to go to each question and download two different csv (and then make a vlookup) instead of just download de CSV whith three columns: XaxisValue, question1Values, question2Values 

![image](https://cloud.githubusercontent.com/assets/17411651/18857314/82fd5b44-8428-11e6-93ea-2b09497fa82a.png)

**Comment by dacort** [comment]
Tagging on here with my use case, which appears to be similar but slightly different from the original poster.

It's common to have filtered dashboards that get linked to from other places. I'd love to be able to have a download link on the filtered dashboard for that data.

If the person clicks through to a specific question, the filters are no longer applied and they have to add them again if they want the filtered data. This can be confused if they are not aware what the filters applied to in the first place.

**Comment by machupichu** [comment]
I aggree with @dacort that for end users, the fact that clicking on the questions reset the filters is very confusing. On top of this, if we use the sql editor, when you click on a question from the dashboard, you land on the question with the editor taking half of the page. For non tech people, I think it is again super disturbing.

For me the best would be having a small download button on each question at the dashboard level in order to download the filtered data directly.

**Comment by moumny** [comment]
I guess what you are describing is related to https://github.com/metabase/metabase/issues/3689

**Comment by arturnt** [comment]
With embedding, this becomes even more useful. I want to embed a dashboard and give the customer the ability to download the underlying data (after they filter it by date).

**Comment by ssatoskar** [comment]
Hi, I am new to Metabase and what to know if we have solve the below questions.

"With embedding, this becomes even more useful. I want to embed a dashboard and give the customer the ability to download the underlying data (after they filter it by date)."

**Comment by flamber** [comment]
Closing this in favor of #11115 - upvote by clicking :+1: on the first post
