### ISSUE TITLE
Add the instance analytics icon

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#33995]
![Screen Shot 2023-09-20 at 12 39 34 PM](https://github.com/metabase/metabase/assets/30528226/02c2f560-8027-4f9a-aa57-d16ec0581322)

discussion: https://metaboat.slack.com/archives/C056QEW4KNF/p1695234765736209

**Comment by luizarakaki** [comment]
The icon is in the Figma file: https://www.figma.com/file/A6Q4571ZvMq2qUUxLgKU4y/Audit-v2?type=design&node-id=15-330&mode=design&t=6Qug7UIh4qX5K1fP-4

**Comment by iethree** [comment]
![audit (1)](https://github.com/metabase/metabase/assets/30528226/391e2fc7-0659-44d9-88e3-8adbea67ad45)

real icon
