### ISSUE TITLE
Logging out not redirecting to login page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3400]
I'm testing permissions so I'm switching back and forth between users a lot.

I created a new dashboard and clicked save, then clicked logout, and my screen went to this state:

![screen shot 2016-09-26 at 4 42 35 pm](https://cloud.githubusercontent.com/assets/1455846/18855530/6ec830a6-8408-11e6-8023-7560a2fbdff5.png)

I see these messages in the console:

![screen shot 2016-09-26 at 4 44 05 pm](https://cloud.githubusercontent.com/assets/1455846/18855533/7a95c8b2-8408-11e6-8d18-560ff5b961a3.png)

**Comment by camsaul** [comment]
If I hit refresh then it redirects me to the login page so maybe this is an issue with logout not redirecting properly

**Comment by kdoh** [comment]
Was able to reproduce this. However after logging out when I went to localhost:3000 my session was still active rather than seeing the login page.

**Comment by kdoh** [comment]
It seems specific to viewing a dashboard.
