### ISSUE TITLE
Duplicate name data may appear in the metabase table

### ISSUE THREAD

**Issue by li-xiaolu** [metabase/metabase#34012]
### Describe the bug

We found that sometimes there may be data with duplicate names in the metabase table without creating a table with the same name.
We don't know how to reproduce this phenomenon. Do you have any insights?
![Snipaste_2023-09-21_17-22-29](https://github.com/metabase/metabase/assets/115760863/985a7473-b191-4a54-bfbe-3310b52546d0)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ja",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+9-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+9-LTS",
    "os.name": "Linux",
    "os.version": "5.10.192-183.736.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Japan"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.26"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-21",
      "tag": "vUNKNOWN",
      "branch": "dev",
      "hash": "e443601"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

**Comment by li-xiaolu** [comment]
A similar problem occurred in 2018, please refer to it.
https://discourse.metabase.com/t/repeated-tables-in-custom-query-builder/3649

**Comment by paoliniluis** [comment]
do you have an index in that table or you removed it?

**Comment by li-xiaolu** [comment]
In duplicate tables, some are indexed, while others are views without indexes.
These tables have been deleted and rebuilt.

**Comment by paoliniluis** [comment]
Redirecting all to https://github.com/metabase/metabase/issues/41374

**Comment by li-xiaolu** [comment]
![Snipaste_2024-04-28_15-16-20](https://github.com/metabase/metabase/assets/115760863/5930648c-99b0-4016-8938-68ba0fd54115)
![Snipaste_2024-04-28_15-08-12](https://github.com/metabase/metabase/assets/115760863/10859a3b-833a-4943-b0ed-4a1dc80f7b64)
My problem is table duplication, not dashboard or card duplication. I think it's a different issue from # 41374.
Additionally, in the version I am using, the revision table does not have the field mosd_recent. @paoliniluis

**Comment by paoliniluis** [comment]
Hi, Metabase shouldn’t allow you to insert 2 tables with the same name

**Comment by li-xiaolu** [comment]
Hi, I did not log in to two tables with the same name, but two tables automatically appeared during the data change and synchronization process.
