### ISSUE TITLE
Multi-series plots of cumulative operations have x-axis out of order

### ISSUE THREAD

**Issue by Gurado** [metabase/metabase#3401]
Multiseries plots get out of order if the first series selected to create the plot has missing values while a second plot does have data there. 

What seems to happen is, that the data from the second plot get added at the end of the data range from the first plot.

![cursor_and_metabase](https://cloud.githubusercontent.com/assets/3722155/18861381/1d7c7124-84c8-11e6-9868-056f39a0a88c.png)

This is
- Your browser and the version: Version 53.0.2785.116 (64-bit)
- Your operating system: OSX 10.11.6
- Your databases: MySQL
- Metabase version: 0.19.3
- Metabase hosting environment: Debian 8
- Metabase internal database: H2 (default)

Reproducible steps 

```
DROP TABLE IF EXISTS `test`;

CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `24hour` smallint(2) NOT NULL,
  `count` int(11) NOT NULL,
  `date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `test` WRITE;
/*!40000 ALTER TABLE `test` DISABLE KEYS */;

INSERT INTO `test` (`id`, `24hour`, `count`, `date`)
VALUES
    (1,0,1,'2016-09-01'),
    (2,1,2,'2016-09-01'),
    (3,2,3,'2016-09-01'),
    (4,6,6,'2016-09-01'),
    (5,7,7,'2016-09-01'),
    (7,9,9,'2016-09-01'),
    (8,7,4,'2016-09-02'),
    (9,8,9,'2016-09-02'),
    (10,9,19,'2016-09-02'),
    (11,10,10,'2016-09-01'),
    (12,11,11,'2016-09-01');

/*!40000 ALTER TABLE `test` ENABLE KEYS */;
UNLOCK TABLES;
```

Multi series plot generated with Questions

```
SELECT `test`.`24hour` AS `24hour`, sum(`test`.`count`) AS `sum`
FROM `test`
WHERE date(`test`.`date`) = date(?)
GROUP BY `test`.`24hour`
ORDER BY `test`.`24hour` ASC
```

**Comment by tlrobinson** [comment]
@Gurado I'm unable to reproduce this, is it still a problem?

**Comment by camsaul** [comment]
As far as I can tell this is no longer an issue. Since we haven't heard back in over a year I'm going to go ahead and close this out. @Gurado feel free to open a new issue if you're still seeing this.
