### ISSUE TITLE
FE - Change permission icon and message for Instance Analytics in permissions table

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#34032]
![Image](https://github.com/metabase/metabase/assets/32561114/e7ef81a9-5e0e-4421-b0b0-b1c48b735927)

The `Instance analytics` collection is view-only for all users, including admins.

We should replace the `Curate` here with `View` (grayed, as it is not possible to change this).
The tooltip shows:
`The Instance analytics collection is read-only for admins`

**Comment by iethree** [comment]
@luizarakaki Can we revisit this tooltip copy? the instance analytics collection isn't read-only for all users. some users can be blocked from it. I don't want people to think that they're exposing audit data to everyone in the instance.

**Comment by luizarakaki** [comment]
Yes, that's right. I updated the tooltip:
`The Instance analytics collection is read-only for admins`
