### ISSUE TITLE
Switching from Wagon to Metabase

### ISSUE THREAD

**Issue by hugocar** [metabase/metabase#3404]
Hi,

I am currently making about 15 colleagues change from Wagon (wagonhq.com) to Metabase.
This change is forced by Wagon imminent interruption of service. Wagon was a cutting-edge SQL editor tool featuring charts and shared queries.

I though it would be helping to the Metabase team to post the feedbacks from my colleagues.
(Creating one issue might not be the best solution, I won't mind if you close it)

**Feedbacks :** 
The following are negatives feedbacks, keep in mind some of them might stem from misuse of metabase full capabilities.
Despite those feedbacks, Metabase was well accepted by users and they liked mostly the query builder and the clean design. 

From non SQL-savvy people : 
- When I started a new question and I want to start a new question (reset all the fields), clicking on "new question" doesn't work.
- There are no 100% charts ( in Wagon 100% bar charts are the same as stacked bar chart but each bar is scaled to the same height. They are very useful to check for relative evolution inside a curve series)
- If the description of a question is long (multiple lines) the space left for chart is too small
- In the left panel of the Questions screen, the label are more useful than Favorites, Recently Viewed, Saved by me, etc.. But one has to scroll to reach them.
- I can't export the chart .png like I used to in Wagon
- I can't type dates and picking a date like 1rst january 2015 requires many clicks
- There is no indication about how much time a query is running ( knowing the time the last run took is very useful )

From SQL savvy people : 
- The SQL editor window is too small
- Some query ran by Metabase are not cancelled properly and keep running with status "sending data" even when the cancel button is clicked
- If I slice a line or bar chart by weeks using the builder, then use the convert to SQL function, the resulting chart is different.  (try it, its easy to reproduce) (the underlying issues is consistency between charts in a dashboard when mixing SQL questions and built questions) 

Let me know if this is a useful feedback format.

Our set up : 
- Your databases: MySQL
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: AWS Linux AMI
- Metabase internal database: MySQL

**Comment by salsakran** [comment]
this is awesome @hugocar 

Some of these we know about, but some are new and good ideas.

**Comment by salsakran** [comment]
@hugocar was there any hassle in importing the queries?

**Comment by hugocar** [comment]
Happy to help!

There was some hassle but not necessarily due to Metabase : 

- The SQL editor window is indeed small

- Wagon doesn't have a variable system. We used to rely on MySQL variables which was dirty.
Setting variables the Metabase way increased the importing time but is so much worth it.

- On wagon, users only have one connection. If a query hangs, they can't run another. In Metabase, users share a pool of connections, and can potentially stack slow queries up. I decided to materialize some of the mostly used views nightly. This led to some extra work on top of importing but again it's worth it in the long run.


Edit : I added a feedback about question runtime in my original post.

**Comment by camsaul** [comment]
@metabase/core-developers I think it makes sense to break this out into separate actionable issues, there's a lot of good ideas in this

**Comment by camsaul** [comment]
@metabase/core-developers are there any more actionable issues we can open based on this? We've opened #3373, and #2399 was already opened for an issue mentioned here. If there's anything else we want to address let's open issues, otherwise let's close this out?

**Comment by camsaul** [comment]
Ok, closing this out based on the 👍 . Thanks for the input @hugocar 😻
