### ISSUE TITLE
Tune smart humanization of table/field names

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#3405]
The word frequency list we use to infer spaces in table and field names was scraped from Wikipedia and includes a lot of short, non-English words that cause words to be incorrectly split, and there are other not-strictly-incorrect edge cases. Lets keep track of false positives here and fix them.

- inbox => in box
- [x] acquirer => ac qui rer
- [x] auth_authenticator => Au Th Authentic At Or
- [x] auth_user => Au Th User
- [x] authprovider  => Au Th Provider
- ~~groupasignee => Group A Sign Ee~~ (typo)
- [x] social_auth_usersocialauth => Social Au Th User Social Au Th
- [x] uid => U ID

Uppercase:

- [x] Api
- [x] Url
- [x] Ip
- [x] Uid

Special case?

- Msg -> Message
- Num x -> Number of x
- Is x => Is x?

Notes:

- Remove a word: `gsed -i '/WORD/d'  resources/words-by-frequency.txt`
- Add a word at line 1000: `gsed -i '10000i WORD' resources/words-by-frequency.txt`
- Add a word at the end: `echo WORD >> resources/words-by-frequency.txt`

**Comment by stefanoeb** [comment]
+1

**Comment by tlrobinson** [comment]
@stefanoeb (or anyone else) if you have any false positives you'd like to contribute as test cases please comment here with the expected and current actual humanization.

**Comment by stefanoeb** [comment]
Actually my database fields and names are in portuguese, and since humanization only works in english, would be better if is there is a way to disable it rather than bring it to the desired languages (given the work/time), what do you think?

**Comment by tlrobinson** [comment]
@stefanoeb We actually do have that setting in Settings => General => Friendly Table Names, it was implemented in v0.19.0 (#3024). If you disable it it will revert your table/field names to the more simple humanization.

![image](https://cloud.githubusercontent.com/assets/18193/19085642/dc4aed68-8a1f-11e6-9b07-b28e3fbbe432.png)

**Comment by stefanoeb** [comment]
Oh, I overlooked the configs, thank you so much @tlrobinson (:

**Comment by moumny** [comment]
There is issue with acronyms containing "I" :)

**Comment by snarfed** [comment]
yup. this has been very entertaining for us here. a couple examples of both false positives and false negatives:

<img width="485" alt="screen shot 2016-11-23 at 11 42 37 am" src="https://cloud.githubusercontent.com/assets/778068/20576603/65a4add6-b173-11e6-823d-094f14a72a2b.png"><br>
(LIMS Samples DNS Quantification Entry)


<img width="488" alt="screen shot 2016-11-23 at 11 48 24 am" src="https://cloud.githubusercontent.com/assets/778068/20576616/735270b2-b173-11e6-9240-7cf37ac94b1d.png"><br>
(LIMS Samples Library Preparation Run V2)

**Comment by camsaul** [comment]
@tlrobinson can this be closed now? I think it makes more sense to open a new issue if it continues to be a problem, it sounds like #3739 fixed most of the issues

**Comment by camsaul** [comment]
Closing since this was addressed by #3739
