### ISSUE TITLE
CSV upload icon will be gone after enabling CSV upload for the first time then go back to the collection.

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#34078]
### Describe the bug

For a Metabase instance that has not enabled CSV upload. After enabling the CSV upload via clicking the upload button on the collection for the first time and go back to the same collection. The upload button will be gone from the collection view unless I refresh the page.

### To Reproduce

0. Create a new Metabase instance.
1. Go to **Our Analytics** collection.
2. Click on **Upload data to <collection_name>** (CSV upload icon)
3. Click **Enable in settings** button. This will bring you to the admin page.
4. In my case, I select **Sample database** and **PUBLIC** schema. And click **Enabled uploads** button.
5. Click back on the browser to go back to the collection (or clicking the **Exit admin** button and navigate manually to the collection)
6. The CSV upload icon will be gone.
7. Refresh the page, the CSV upload icon will be back.

### Expected behavior

The CSV upload button should be visible since step 6 without needing a page refresh

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "13.6",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-09-13",
      "src_hash": "826c1e10414ad2489af3d4cc103f30b2a440f342",
      "tag": "v1.47.1-SNAPSHOT",
      "branch": "33504-remove-timeseries-grouping-on-expression-dimension",
      "hash": "5018829"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Confusing users who just enable the CSV upload for the first time

**Comment by pilvikala** [comment]
The drag and drop is disabled as well until you reload the page.
