### ISSUE TITLE
Timeseries Filter Widget jumps when opening

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#34077]
### Describe the bug

When opening the dropdown menu in the `TimeseriesFilterWidget`, the popover opens on top of the dropdown and then "jumps" above the dropdown.

Here's a video of the bug:

https://github.com/metabase/metabase/assets/25306947/49edd01b-1bff-47e4-8ef0-5db24e7f6c7f

### To Reproduce

1. Go to a timeseries question (i.e. X axis is time, Y axis is a count/metric/etc)
2. Click `View [All Time]` filter on the bottom
3. Click the dropdown within the popover.
4. Notice that the sub-popover jumps when it opens

### Expected behavior

Opening the popover should be smooth and should initialize in the correct position

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20.0.1",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "20.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20.0.1",
    "os.name": "Mac OS X",
    "os.version": "13.5.2",
    "user.language": "en",
    "user.timezone": "Europe/Tallinn"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-09-21",
      "src_hash": "b3c10b0a89544df6724df72f1ec9fb52f0528543",
      "tag": "v1.48.0-SNAPSHOT",
      "branch": "master",
      "hash": "e833b59"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

**Comment by nemanjaglumac** [comment]
Cannot be reproduced neither in master @ https://github.com/metabase/metabase/commit/c7e2a0078a0866af913a99c26ca39b545ef42244, nor in the latest release 50.7.
