### ISSUE TITLE
In E2E tests MongoDB database sync frequently times out

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#34089]
We're waiting 20 seconds in CI for MongoDB to sync in `qa-db.cy.snap.js` but it keeps timing out. Example [here](https://github.com/metabase/metabase/actions/runs/6273158626/job/17036511965?pr=34014#step:17:100). 20 seconds is more than reasonable for this database sync.

Ryan [reports](https://metaboat.slack.com/archives/C5XHN8GLW/p1695657068494269?thread_ts=1695655588.078519&cid=C5XHN8GLW) this happening locally "probably 1/3 of the time".

**Comment by darksciencebase** [comment]
could be related to https://github.com/metabase/metabase/issues/27877#issuecomment-1452060398

**Comment by iethree** [comment]
> If #27877 is the culprit, it looks like the problem could be here: [`master`/e2e/support/helpers/e2e-qa-databases-helpers.js#L84-L91](https://github.com/metabase/metabase/blob/master/e2e/support/helpers/e2e-qa-databases-helpers.js?rgh-link-date=2023-11-07T20%3A13%3A27Z#L84-L91)
> 
> Can we make that block wait on `assertOnDatabaseMetadata(engine)` to complete? @iethree

That block already does wait on `assertOnDatabaseMetadata` 😢 

attempted fix here: https://github.com/metabase/metabase/pull/35498

**Comment by iethree** [comment]
> more recent example [metabase/metabase/actions/runs/6627161914/job/18001544443?pr=35011](https://github.com/metabase/metabase/actions/runs/6627161914/job/18001544443?pr=35011)

I don't think this is limited to mongo - this linked example doesn't even try to set up mongo

**Comment by calherries** [comment]
This was fixed by https://github.com/metabase/metabase/pull/35713 and also https://github.com/metabase/metabase/pull/35498
