### ISSUE TITLE
FE - Add smart defaults when duplicating content in audit collections

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#34086]
When clicking on `Make a copy` or `Duplicate` any content in the `Instance analytics` collection, the destination collection default should be `Custom reports`.

**Comment by iethree** [comment]
The final collection structure seems like it's still up in the air. removing from up next until we decide that.

**Comment by luizarakaki** [comment]
Unpausing this as we will likely keep the current collection structure (maybe change the names)
