### ISSUE TITLE
Spacing on segment creation message in activity feed is off

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3410]
![screen shot 2016-09-27 at 3 41 01 pm](https://cloud.githubusercontent.com/assets/107439/18894632/e2ef9f26-84c8-11e6-9fcb-548427eadbe3.png)

**Comment by mazameli** [comment]
Looks like the string concatenations are missing some `" "`s

**Comment by salsakran** [comment]
yup, fixing it now
