### ISSUE TITLE
Additional color range selectors are missing the toggle button

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#34123]
### Describe the bug

When choosing a color range, the two additional color ranges are missing the "sorting" toggle.

### To Reproduce

1. Open "Orders" table
2. Clock on visualization settings
3. Choose conditional formatting > Add a rule > Total, and select "Color range"
4. Click on the "Colors" stripe to open a popover with more options
5. Notice that the toggle buttons are missing from additional color ranges
![image](https://github.com/metabase/metabase/assets/31325167/7c8018f3-a8ae-4722-8532-0c1e491526aa)

### Expected behavior

Additional color range selectors should have the toggle button

### Information about your Metabase installation

```JSON
local dev, `master`, 7e0eb68fd75fe69849dd263ce07dd2cb1aa67870, Sample database, H2
```

### Severity

P3

### Additional context

Regression only on `master`.
Introduced in #33989

Related to #34017, which was most likely introduced in #29480

**Comment by EmmadUsmani** [comment]
Not a bug but an intentional decision, see [slack thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1695745008053709?thread_ts=1695722686.406949&cid=C01LQQ2UW03)
