### ISSUE TITLE
Metabot is incorrectly enabled by default, can't be turned off

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3412]
It appears MetaBot is enabled, even though I haven't set up Slack. I can't turn the toggle off. This is particularly weird because now there's a MetaBot column in Permissions by default, which is very confusing if I don't know what MetaBot is (because I haven't manually set it, or Slack, up).

It shouldn't be possible to enable MetaBot until a Slack API token has been entered, I would contend.

![screen shot 2016-09-27 at 4 16 19 pm](https://cloud.githubusercontent.com/assets/2223916/18895353/e1a387f4-84cd-11e6-8ff9-5f2c75741a7c.png)

**Comment by camsaul** [comment]
Was this fixed by #3430? It looks like it was but GitHub isn't very good at automatically closing issues related to PRs so I think we just forgot to close this

**Comment by kdoh** [comment]
I believe it was yes.

**Comment by camsaul** [comment]
Fixed by #3430
