### ISSUE TITLE
Cannot stack line charts

### ISSUE THREAD

**Issue by jesusrtc** [metabase/metabase#3413]
### Bugs
- Your browser and the version: (Chrome) Versión 52.0.2743.116 (64-bit)
- Your operating system: (OS El Capitan)
- Your databases: (Postgres)
- Metabase version: (0.19.3)
- Metabase hosting environment: (Elastic Beanstalk)
- Metabase internal database: ( Postgres)

Stacked button is not visible in line charts.
So to use it I need to transform it as area chart, use the button and then return to line chart

**Comment by tlrobinson** [comment]
A stacked line chart would be pretty misleading, so we decided to only allow stacking in bar and area charts. What is the use case for stacking a line chart?

**Comment by tlrobinson** [comment]
@jesusrtc ?

**Comment by camsaul** [comment]
Hi @jesusrtc, since we asked for more info and haven't heard back in over a year I'm going to go ahead and close this issue out
