### ISSUE TITLE
Uploaded CSVs can't contain zoned datetimes

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#34137]
Some CSV downloads from Metabase include the TZ offset in them (such as Model #4523, discovered by @uladzimirdev ):

```
ID,Customer Name,Created At,...
<the ID>, <the customer name>,2023-09-26T04:21:10.645527-07:00,
```

If you then re-upload this to Metabase, the datetime is not recognized since we use `local-date-time` instead of `offset-date-time` for parsing. We also use TZ-less types for the resulting columns in the table.

We should probably detect if TZ data is included and then map that to `TIMESTAMP WITH TIMEZONE` columns.

**Comment by vaibhav2ghadge** [comment]
Hi @tsmacdonald ,
I am checking how we are going to implement this in Mysql and Postgres but both of these databases don't support the datetime with offset.
How we can implement this ?

**Comment by tsmacdonald** [comment]
@vaibhav2ghadge I am not a product manager, but probably the ideal is this:

| DB | `local-date-time` type | `offset-date-time` type | documentation link |
|-|-|-|-|
| Postgres | `timestamp without time zone` | `timestamp with time zone` | [docs](https://www.postgresql.org/docs/current/datatype-datetime.html) |
| MySQL 8 | `datetime` | `datetime` [inserted with offset](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html) | [docs](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) |
| MySQL <8 (or maybe all MySQLs for simplicity) | `datetime` | `datetime` with the offset manually computed | [docs](https://dev.mysql.com/doc/refman/5.7/en/datetime.html) |
| H2 | `TIMESTAMP` | `TIMESTAMP WITH TIME ZONE` | [docs](http://www.h2database.com/html/datatypes.html#timestamp_type) |


If you want to open a PR implementing this it's certainly welcome (assuming you sign the CLA, follow [the style guide](https://github.com/metabase/metabase/wiki/Metabase-Clojure-Style-Guide), etc.). Thanks!
