### ISSUE TITLE
Bug: Date Shifts to One Day Earlier When Creating Events in Charts

### ISSUE THREAD

**Issue by udit-001** [metabase/metabase#34145]
### Describe the bug

After creating an event on the chart, I encounter an issue where, upon pressing the "create" button, the date automatically shifts to one day earlier than intended. Consequently, I am required to rectify this discrepancy by clicking on the "edit event" option to adjust the date to the correct one I originally intended.

### To Reproduce

1. Create a chart that includes a count and group by date column.
2. Ensure that the X-Axis is set to the date column.
3. Click the event button and proceed to add an event.
4. Enter the details for the event, including the date, and then click the "create" button.
5. Verify the date of the created event; it will be set to one day earlier than the intended date.

### Expected behavior

The event should be created with the correct date.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.0-14-cloud-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "snowflake",
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-18",
      "tag": "v0.47.2",
      "branch": "release-x.47.x",
      "hash": "536c24c"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}
```

### Severity

The usage of the events feature with our charts is becoming cumbersome, particularly when dealing with a large number of events.

**Comment by perivamsi** [comment]
Not able to repro in master
