### ISSUE TITLE
[Epic] Remove Pulses while warning customers about it

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#34147]
**Links**
- product doc: [Remove Pulses while warning customers about it](https://www.notion.so/metabase/Remove-Pulses-while-warning-customers-about-it-781d66840a4d4e109c03bce8e0da3e39)
- eng doc: _link to technical design doc, if any_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links:
  - https://github.com/metabase/metabase/issues/32990
  - https://github.com/metabase/metabase/issues/32652
  - https://github.com/metabase/metabase/issues/13575
  - https://github.com/metabase/metabase/issues/16519

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/35841
- [ ] https://github.com/metabase/metabase/pull/35843
- [ ] https://github.com/metabase/metabase/pull/36392
```

**Comment by qnkhuat** [comment]
We decided that we'll only remove pulse as part of this project. 

We'll do a refactoring in the future when we have a better vision of how notification will grow.

For historical context, this is the milestones I laid out in case we want to do a refactor

# Milestones
The end goal here is to refactor how we model alert/dashboard subscriptions, at the same time we'll remove pulse
At the end of these milestones, the model will look like this
![282740694-a8eee63a-3f14-4c32-8997-ac09b6cb5b10](https://github.com/metabase/metabase/assets/25661381/c326bbc0-29b5-40d8-b9b2-0fd1b880aa98)

See (https://github.com/metabase/metabase/issues/17871) for details

### Milestone 1: Migrate alert into its own entity
- Rename: 
  - pulse_channel_recipient -> subscription_channel_recipient
  - pulse_channel -> subscription_channel
- Create 2 new tables: Alert, AlertChannel and migrate alert from pulse to these tables
- Tackle [this](https://github.com/metabase/metabase/issues/13575) and [this](https://github.com/metabase/metabase/issues/31946) while we're at it
- Refactor alert code into its own namespace
- Create a new namespace for sending stuff, it should be re-used across alert and dashboardsub

### Milestone 2: Migrate DashboardSubscription into its own entity
- Create a new table: dashboard_subscription and migrate dashboard subscriptions from pulse 
- Migrate dashboardsub code into its own namespace

### Milestone 3: Purge day
- drop the pulse tables, it should only contain the old pulse now
- Remove FE components

### Milestone 4: cleaning up (optional)
- rename the API `/api/pulse` to `api/dashboard_subscription` or sth that makes more sense
- Create a new `GET /api/alert/form_input` API that is similar to `GEt /api/pulse/form_intput` and update FE To use the alert version for editing
