### ISSUE TITLE
Fields not found for BigQuery views

### ISSUE THREAD

**Issue by szymonm** [metabase/metabase#3414]
Browser: Chrome 53.0, Safari 10.0
OS: OS X Sierra
Databases: BigQuery
Metabase version: 19.3
Metabase hosting environment: MacOS, Linux/Ubuntu 16.04
Metabase internal database: Postgres

Every time I use Builder to query a view defined in the BigQuery I get the following error:
_Field 'db.table.field_name' not found._, so I'm unable to retrieve any data from the view. This does not happen when using SQL editor that retrieves data correctly.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
@szymonm, did you change this view in some fashion after you added your database to Metabase?

**Comment by szymonm** [comment]
@camsaul Nope

**Comment by hgwood** [comment]
Running into the same issue here. I've configured BigQuery in Metabase, then added the view to BigQuery, then sync'ed the DB in Metbase, then ran a query and it failed with a field not found error. The schema for the view shown in the Metabase admin panel is correct and contains all fields.

**Comment by szymonm** [comment]
hey @hgwood we spent some time on this and we are now using a hack: we are periodically materializing our views to tables in BQ. Couldn't find anything better for know...

**Comment by hgwood** [comment]
@szymonm Thanks, I'll use that in the meantime.

**Comment by stigmergist** [comment]
I'm having exactly the same problem with views.

It looks like you cannot use the dateset.table.field syntax to refer to fields of a View, whereas it does work for Tables. (Try creating a simple "select *..." View over a table and referring to a field. Wroks fine in Table, fails in View)

Really need this to work soon. Have multiple layers of views and Metabase looks like exactly the tool I need.

**Comment by BelfodilAimene** [comment]
Same problem Here.

**Comment by remydavid** [comment]
Same problem here for a field filter defined in SQL.

**Comment by marcromeyn** [comment]
Same problem here.

**Comment by ajbosco** [comment]
Is there anyone working on this?

**Comment by camsaul** [comment]
@stigmergist to clarify BigQuery only supports `SELECT *` for views?

**Comment by zbrowne** [comment]
Sam problem here. Any updates on a fix? After reading through why joins are not supported, Metabase says "Take the time you’re spending writing ad hoc queries for them, and throw together a few views that make those queries trivial to ask in Metabase’s GUI query builder." I did this but now it appears that this is failing for myself and others as well and I am at a loss. Are there other workarounds? http://www.metabase.com/blog/Joins

**Comment by salsakran** [comment]
@zbrowne you got us there.

We've been pushing pretty hard on a couple of big features (Embedding, Caching, DrillThrough and Sub-queries). We've shipped the first in 0.23 and the latter three are almost closed. We're planning on plowing through as many of the P1 + P2 bugs after as we can and rolling that combination up into 0.24.

**Comment by zbrowne** [comment]
@salsakran thanks for the quick response and glad to hear it will be looked at soon!

**Comment by camsaul** [comment]
@stigmergist ?

**Comment by camsaul** [comment]
@stigmergist ?

**Comment by salsakran** [comment]
@camsaul have you tried to repro this on your own?

**Comment by camsaul** [comment]
So there's a couple issues we'll have to address to handle this:

1.  Querying VIEWs with any `SELECT` clause other than a `SELECT *` requires wacky syntax, e.g.
    ```sql
    #standardSQL
    SELECT [COLUMN_1, COLUMN_2]
    FROM `[DATASET.VIEW]`
    WHERE allowed_viewer = SESSION_USER()
    ```
    Generating special queries with this "standard" syntax would require some hairy hacks since we assume sane/normal SQL syntax almost everywhere (and most of the code for different SQL drivers is shared).

2.  > You cannot mix standard SQL and legacy SQL queries when using views. A standard SQL query cannot reference a view defined using legacy SQL syntax.

    Currently our driver uses legacy SQL syntax since standard SQL syntax was only made available ~9 months ago and our driver was written well before then. So, to support views written in standard SQL, we'd have to rewrite portions of our driver to output standard SQL instead of legacy. Of course, that would mean we'd break view support for anyone using legacy SQL. It should be noted as well that legacy SQL is still the default.

**Comment by gilhs** [comment]
Any updates on this? I'll speak for myself when I say that support for legacy syntax views is much more important to us than support for the new "standard" syntax - and this additional issue does not exist there, so should be easier to resolve.

**Comment by camsaul** [comment]
Hi @gilhs, unfortunately we're planning on moving towards standard SQL syntax for BigQuery so when we fix this we'll likely only support standard SQL views.

**Comment by gilhs** [comment]
OK, thanks for the update!
