### ISSUE TITLE
Line graph with multiple lines draws empty cells as zeros

### ISSUE THREAD

**Issue by gerbus** [metabase/metabase#3415]
Metabase Version: v0.17.1

![image](https://cloud.githubusercontent.com/assets/2348366/18920467/429d63e4-8556-11e6-91eb-1ccab5cd5e18.png)

I have a table with columns for years, and rows for months. As a line graph, it shows different coloured lines for different years, with data points for every month. Since it's currently September, the 2016-Oct, 2016-Nov, and 2016-Dec cells are blank. However when I look at the line graph, those cells are drawn as zeros, which is highly misleading to any viewers of the graph. 

I realize that it would be difficult for the code to identify when and when not to draw a point on the graph, so I suggest that there be a specified cell value that is interpreted by the rendering engine as "don't draw data point".

**Comment by tlrobinson** [comment]
We actually are adding a setting in the next release (v0.20) to control what to do with missing data points (the options are zero, none, and linearly interpolated).

**Comment by gerbus** [comment]
Amazing!

**Comment by camsaul** [comment]
@tlrobinson do we have a PR or issue number for the new chart options? So we can close this out

**Comment by salsakran** [comment]
@cam this would have been tracked by issue #896 and fixed in  PR #3149
