### ISSUE TITLE
Composite join keys aren't auto-populated when joining in notebook editor

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#34184]
### Describe the bug

I have table A with 2 fields (foreign/composite keys) mapped to another table B with composite entity keys (2 fields). When joining in notebook editor, it would automatically populate the first field as the join key but not he 2nd pair. 

This is the [recommended way to join Snowplow event tables](https://docs.snowplow.io/docs/understanding-your-pipeline/canonical-event/#extensible-schema) -- using 2 keys -- for accuracy and performance.

Another problem is if the entity key is a tstamp field (the case for Snowplow's recommended join), it will get truncated to minute or another interval when joining as there is no option to use the exact value, which makes it useless for joining. There are probably use cases for truncating the tstamp when joining but there needs to be an option to not do it, which should be the case if the field is set to entity key. I have to work around that by setting the tstamp field to foreign key which doesn't have the bug (but then it doesn't allow other foreign keys to map to it). 

### To Reproduce

1. Map 2 fields as foreign keys to another table with 2 entity keys. 
2. Try to join in notebook editor and notice editor only populated the first join key automatically

### Expected behavior

Both (all mapped foreign keys) keys should automatically be populated

### Logs

n/a

### Information about your Metabase installation

```JSON
Master / Postgres
```

### Severity

Without auto-populate, users would have to manually set the 2 keys, which is not possible for new users that don't know the 2 keys and a bit cumbersome to have to do an extra join

**Comment by ranquild** [comment]
`suggestedJoinCondition` returns a single condition now but we probably want to return an array to solve this issue

**Comment by ranquild** [comment]
I can still reproduce on `master`. Steps with the sample database:

- Go to Admin -> Table Metadata -> Orders and change `USER_ID` to be a FK for `Products`:
<img width="1728" alt="Screenshot 2023-11-08 at 11 45 25" src="https://github.com/metabase/metabase/assets/8542534/51b36cc6-cb87-419a-9e9d-fc807e23b753">

- Exit Admin -> New -> Question -> Orders
- Join -> Products
- Only the first FK is auto-populated

<img width="1728" alt="Screenshot 2023-11-08 at 11 45 25" src="https://github.com/metabase/metabase/assets/8542534/bdf43e80-4d56-480e-92ed-561b01f98170">
<img width="1299" alt="Screenshot 2023-11-08 at 11 45 50" src="https://github.com/metabase/metabase/assets/8542534/107c7bb2-d72f-4e3b-b41e-8f18f304b5b8">

As stated in the previous comment, `suggestedJoinCondition` only returns a single join condition, so we need to change it to  `suggestedJoinConditions` and return an array (this needs to be done in CLJS). Then we update the FE to use it.

**Comment by camsaul** [comment]
I think the current behavior is the correct behavior in this case.

When you have multiple FKs to a table pointing to the same column, it's usually because the table is some sort of graph relation between two rows in that other table, rather than a composite key. e.g.

```sql
CREATE TABLE message (
  id SERIAL NOT NULL PRIMARY KEY,
  sender_id INTEGER NOT NULL REFERENCES user (id), 
  recipient_id INTEGER NOT NULL REFERENCES user (id),
  message TEXT NOT NULL,
  ...
);
```

`message` has two FKs, `sender_id -> user.id` and `recipient_id -> user.id`, but you wouldn't want to generate a join with two conditions like

```sql
LEFT JOIN user
  ON sender_id = user.id AND recipient_id = user.id
```

because that would only match messages someone sent to themself. In this case we'd want to have two separate joins against `user`, one for the sender and another for the recipient, since those are (probably) two different users.

I think we'd only want to suggest multiple join conditions when the FKs point to **different** columns on the destination table.
