### ISSUE TITLE
Unused dependencies and devDependencies in package.json

### ISSUE THREAD

**Issue by nomorethat** [metabase/metabase#34202]
### Describe the bug

I have a node_modules folder that has a very large size (almost 2GB). After doing research, I found a large number of unused dependencies and devDependencies. This clogs the file system, slows down the installation of dependencies and the build process.

### To Reproduce

For the analysis I used "depcheck" (https://www.npmjs.com/package/depcheck). It is enough to execute "npx depcheck".

![ksnip_20230928-125255](https://github.com/metabase/metabase/assets/46302088/9dc3c9f5-65de-4871-9260-de870bc8ddf4)

![ksnip_20230928-125309](https://github.com/metabase/metabase/assets/46302088/58c70241-87e8-4396-b928-1757a0b795d0)

### Expected behavior

Optimizing the productivity of the development process =)

### Logs

-

### Information about your Metabase installation

```JSON
-
```

### Severity

Complicates the development process on low-performance computers

### Additional context

-

**Comment by uladzimirdev** [comment]
@nomorethat thanks for bringing the issue. We definitely run depcheck from time to time on the repo and most of the packges on the list are actually used although depcheck shows they are not used. If you found something really not used, do not hesitate to open a PR.

I know, the size of node_modules is a big problem, but it's not easy to solve it. please chech the thread with creator of npm https://twitter.com/izs/status/1705665268486410506

I'm closing it for housekeeping purposes, feel free to reopen with more details
