### ISSUE TITLE
Flaky `vertica` TZ driver test

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#34213]
This particular test has been flaking a lot lately.
```
FAIL in metabase.driver.vertica-test/db-timezone-test (vertica_test.clj:17)

:vertica

expected: (#{"America/Los_Angeles" "UTC"}
           (driver/db-default-timezone :vertica (mt/db)))
  actual: nil
```

https://github.com/metabase/metabase/actions/runs/6339641340/job/17219258671?pr=34209#step:5:427

**Comment by darksciencebase** [comment]
https://github.com/metabase/metabase/pull/34234

**Comment by nemanjaglumac** [comment]
Fixed by https://github.com/metabase/metabase/pull/34234
