### ISSUE TITLE
Invalid identifier when joining tables that have the same column name

### ISSUE THREAD

**Issue by jonathanhuang13** [metabase/metabase#34227]
### Describe the bug

I'm running into a Metabase joining error. I'm trying to join one table (courses) with another table that has aggregate statistics for each course. The join fails with the error:

```
SQL compilation error: error line 1 at position 203 invalid identifier '"Question 2295"."count_2"'
```

The table with aggregate statistics combines data from two different tables (i.e. number of enrollments, number waitlisted). These two tables (table 2292 and table 2293) do a sum by distinct user IDs. It looks like the issue is that there is a "COUNT" column for each aggregation but Metabase doesn't know how to handle multiples of the same column. The resulting SQL is: 

```
SELECT "Question 2295"."Question 2292__count" AS "Question 2295__Question 2292__count", "Question 2295"."count_2" AS "Question 2295__count_2" FROM ...
```

instead of

```
SELECT "Question 2295"."Question 2292__count" AS "Question 2295__Question 2292__count", "Question 2295"."Question 2293__count" AS "Question 2295__Question 2293__count" FROM ...
```

The difference is the "count_2" vs "Question 2293__count".

Here's a Loom: https://www.loom.com/share/5ee216c013ee47a4b0511a056c062f28

### To Reproduce

I tried reproducing in the sample database. I get an error but the error is different:
1. Create three tables (see screenshots)
2. Create a new question that joins table 3
3. See the error: `Distinct, non-empty sequence of Field clauses`. The error is different from what I get but the process is the same

**Table 1**
![CleanShot 2023-09-28 at 10 40 43@2x](https://github.com/metabase/metabase/assets/6477471/cf49723b-82c2-4292-add8-1c74b8b05466)

**Table 2**
![CleanShot 2023-09-28 at 10 41 22@2x](https://github.com/metabase/metabase/assets/6477471/655337e0-0f23-4897-b37d-b0b44e9de87c)

**Table 3**: creates a aggregate table that joins table 1 and 2
![CleanShot 2023-09-28 at 10 42 08@2x](https://github.com/metabase/metabase/assets/6477471/fac56848-0869-4917-9d4a-07b492ad0abe)

**New question**
![CleanShot 2023-09-28 at 10 42 55@2x](https://github.com/metabase/metabase/assets/6477471/c0a5491c-3bc0-41f7-98f6-544586dafe3d)

### Expected behavior

SQL should compile

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-15",
      "tag": "v1.46.8",
      "branch": "release-x.46.x",
      "hash": "27a9ec6"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

### Severity

Medium - we have a lot of tables that depend on the intermediary table so it'd be really annoying to create the intermediary table every time

**Comment by darksciencebase** [comment]
from @kulyk:
>  Just went through the repro steps on the MLv2 joins branch. I’m getting an error on step 4 when trying to select the RHS table (“Sample: User Statistics” in the example)
The error being:
`Ambiguous match! Implement more logic in disambiguate-matches.`
