### ISSUE TITLE
relative date SQL parameters in dashboards not getting fully substituted

### ISSUE THREAD

**Issue by orthagh** [metabase/metabase#3422]
- Your browser and the version: Chrome 52 (and  firefox 49
- Your operating system: metabase server: debian 8.5, my desktop ubuntu 16.04
- Your databases: MySQL
- Metabase version:  0.19.3
- Metabase hosting environment: Jar file
- Metabase internal database: H2

Hello.

I'm currently testing your product, and it's very impressive.

I meet a "bug" with relative dates filter in dashboard.
Here is my mysql query: 

```sql
SELECT
   status,
   COUNT(id) as Tickets
FROM glpi_tickets
WHERE {{ticket_date_creation}}
GROUP BY status
```

I set the ticket_date_creation variable to 'field filter' type and choosed my datetime field (named date) from  glpi_tickets table.
I added my card on a dashboard.
If a add a time filter on the "ticket_date_creation" field, it works with all type of time filter except relative dates.

Maybe i did a mistake, and this a not a bug.
Regards

Here is my logs with 'last week' selected: 
```log
09-29 16:24:29 DEBUG metabase.query-processor :: 
QUERY: 😎
{:database 2,
 :type "native",
 :native
 {:query "SELECT\n   status,\n   COUNT(id) as Tickets\nFROM glpi_tickets\nWHERE {{ticket_date_creation}}\nGROUP BY status",
  :collection "glpi_alerts",
  :template_tags
  {:ticket_date_creation {:id "b691d4e5-94bb-dc01-6d4a-5e061af3da11", :name "ticket_date_creation", :display_name "Ticket date creation", :type "dimension", :dimension ["field-id" 3046]}}},
 :parameters [{:type "date/relative", :target ["dimension" ["template-tag" "ticket_date_creation"]], :value "lastweek"}],
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info {:executed-by 1, :uuid "cf923520-b3d4-4c29-98a8-57d7e9bdaa9b", :query-hash -1204608002, :query-type "native"}}

09-29 16:24:29 DEBUG metabase.query-processor :: 

PARAMS/SUBSTITUTED: 😻
{:database 2,
 :type "native",
 :native
 {:query "SELECT\n   status,\n   COUNT(id) as Tickets\nFROM glpi_tickets\nWHERE date(`glpi_tickets`.`date`) = 'lastweek'\nGROUP BY status",
  :collection "glpi_alerts",
  :template_tags
  {:ticket_date_creation {:id "b691d4e5-94bb-dc01-6d4a-5e061af3da11", :name "ticket_date_creation", :display_name "Ticket date creation", :type "dimension", :dimension ["field-id" 3046]}}},
 :parameters [{:type "date/relative", :target ["dimension" ["template-tag" "ticket_date_creation"]], :value "lastweek"}],
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info {:executed-by 1, :uuid "cf923520-b3d4-4c29-98a8-57d7e9bdaa9b", :query-hash -1204608002, :query-type "native"},
 :driver {},
 :settings {}}

09-29 16:24:29 DEBUG metabase.query-processor :: NATIVE FORM: 😳
{:query "SELECT\n   status,\n   COUNT(id) as Tickets\nFROM glpi_tickets\nWHERE date(`glpi_tickets`.`date`) = 'lastweek'\nGROUP BY status",
 :collection "glpi_alerts",
 :template_tags
 {:ticket_date_creation {:id "b691d4e5-94bb-dc01-6d4a-5e061af3da11", :name "ticket_date_creation", :display_name "Ticket date creation", :type "dimension", :dimension ["field-id" 3046]}}}


09-29 16:24:29 DEBUG metabase.middleware :: POST /api/dataset 200 (100 ms) (4 DB calls)
```

**Comment by camsaul** [comment]
The SQL getting generated is:

```sql
SELECT status COUNT(id) as Tickets
FROM glpi_tickets
WHERE date(`glpi_tickets`.`date`) = 'lastweek'
GROUP BY status
```

That doesn't seem right. Seems like things aren't getting fully substituted 😳 .

@orthagh are you having issues with any relative date option, or just `lastweek`?

**Comment by orthagh** [comment]
Hello @camsaul.

Thank you for your answer.

Yes, all options of relatives dates triggers this issue, in last sql query from logs, it always display the keywords instead of dates.

To be sure, i did some additional tests.
I change my jvm to oracle jre from openjdk.
Yesterday, i also runned the 'metabase/metabase_head' docker image with my H2 database and the issue is still present.

**Comment by orthagh** [comment]
I think #3538 (closed) describes the same issue.
I just upgrade to 0.20.1 and it's ok .

You can close.
