### ISSUE TITLE
Text filters with special characters get wrong values when refreshing the browser

### ISSUE THREAD

**Issue by icorreas** [metabase/metabase#3423]
If we have a dashboard with a text filter that requires special characters, when refreshing the browser the special character gets a wrong value, giving wrong results in the dashboard.
![screenshot from 2016-09-29 20-33-03](https://cloud.githubusercontent.com/assets/18148718/18967087/2d83238e-8684-11e6-8f3d-7a3816d92bc0.png)

For example filtering by email address, if we fill the textbox with user@domain.com and then refresh the browser, the textbox displays then user%40domain.com and the cards in the dashboard will indicate no results. Other special characters give problems too.

I am using Firefox v49.0 on Ubuntu 16.04 with Metabase 19.3.

**Comment by bmcbride** [comment]
Confirmed on Chrome v53.0.2785.116 with Metabase  v0.19.3 on Heroku. Even a space in the filter value causes this, and it's particularly problematic with auto-refresh enabled.

**Comment by camsaul** [comment]
looks like we're URL-encoding the params but not URL-decoding them again

**Comment by tlrobinson** [comment]
As far as I can tell this is fixed at least since v0.22.0. @icorreas @bmcbride can you confirm?

**Comment by icorreas** [comment]
Yes. I just checked and I can confirm it is already fixed. Thanks!
