### ISSUE TITLE
Arabic and Arabic (Saudia Arabia) missing from language options

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#34237]
### Describe the bug

Arabic and Arabic (Saudia Arabia) missing from language options

### To Reproduce

1. Click Account Settings
2. See language options
![image](https://github.com/metabase/metabase/assets/8808703/07094599-539f-4b75-80a6-2bbfc967a823)

### Expected behavior

should have Arabic and Arabic (Saudia Arabia) in list

### Logs

n/a

### Information about your Metabase installation

```JSON
- `master` as of `6927d396b6`
```

### Severity

P1: regression with major functionality missing

**Comment by likeshumidity** [comment]
Seems to be an issue with my local dev build using:
```bash
$ clojure -M:run:drivers:drivers-dev
$ yarn build-hot
```

Maybe need to do:
```bash
$ clojure -M:build:build/i18n
```

**Comment by ranquild** [comment]
@likeshumidity I'm closing the issue. Let us know if you have any further issues.
