### ISSUE TITLE
'-' sign misplaced in shortened visualization of currency type

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#34242]
**Describe the bug**
In cards with a Number visualization, the negative sign of currency type numbers is incorrectly positioned when the card has to displays the shortened version of the number.

**Logs**
n/a

**To Reproduce**
1. Create a SQL question `SELECT -500000`, set visualization type to Number, style to Currency.
2. Save, and add it to a dashboard.
3. When there is enough space the number is displayed as `-$500,000`.
4. Decrease the size of the card, and the number will change to`$-500.0k`, the currency symbol and '-' sign are replaced.

**Expected behavior**
It should look like `-$500.0k`.

**Screenshots**

**Severity**
Reported by a customer.

**Additional context**
n/a

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.186-179.751.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-18",
      "tag": "v1.47.2",
      "branch": "release-x.47.x",
      "hash": "536c24c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by ibedwi** [comment]
@luizarakaki @calherries @zbodi74 Hi! I've submitted fixes for this issue in this PR. Would love to get your feedback! Thanks 🙏
