### ISSUE TITLE
Slack metabot number formatting issue

### ISSUE THREAD

**Issue by podviaznikov** [metabase/metabase#3426]
Noticed today problem with slack metabot.

I have a question that displays githubId as a column value.
<img width="512" alt="metabase" src="https://cloud.githubusercontent.com/assets/429706/18975419/d13df72c-865e-11e6-9463-031e0ac5ff78.png">

But whenever I ask metabot to show me that question I get this data formatted.

<img width="315" alt="slack" src="https://cloud.githubusercontent.com/assets/429706/18975430/f0fc5f90-865e-11e6-908b-b3305529604c.png">

That is a little bit inconvenient. Do you know why that is happening?
If it's bug in metabase you can give me a hint where that is happening and I can submit a PR if help is needed.

**Comment by camsaul** [comment]
@podviaznikov Different code is responsible for rendering cards in the web app vs MetaBot. @tlrobinson do we always format numbers like that in MetaBot?

**Comment by flamber** [comment]
Closing in favor of #3735
