### ISSUE TITLE
Fields of AggregateFunction type omitted from preview and erroring in Query Editor

### ISSUE THREAD

**Issue by wickyvinn** [metabase/metabase#34260]
### Describe the bug

I have a table that is `ReplicatedAggregatingMergeTree`, and several fields that have the type `AggregateFunction(avg, Float64)`. When querying this table via the Clickhouse CLI, I'm able to view at least the hash of such functions, for example:

```
SELECT
    timestamp,
    secure_connection_start_ms
FROM p2p_http_all_aggr_5m_v1_dist
LIMIT 10
┌───────────timestamp─┬─secure_connection_start_ms─┐
│ 2023-09-28 08:00:00 │ @l@                        │
│ 2023-09-28 08:00:00 │ @p@                        │
│ 2023-09-28 08:00:00 │ ?u@                         │
│ 2023-09-28 08:00:00 │ ?v@                         │
│ 2023-09-28 08:00:00 │ v@                         │
│ 2023-09-28 08:00:00 │ ?w@                         │
│ 2023-09-28 08:00:00 │ l@                         │
│ 2023-09-28 08:00:00 │ l?@                         │
│ 2023-09-28 08:00:00 │  l@                        │
│ 2023-09-28 08:00:00 │  j@                        │
└─────────────────────┴────────────────────────────┘
```

And when interacting in with the Metabase preview, those AggregatedFunction fields are omitted. Furthermore, when querying in the Metabase query editor, I get a groupMap error:

<img width="1314" alt="image" src="https://github.com/metabase/metabase/assets/4357885/7a4e3125-12d9-433d-8b06-ef6ac2ade9e3">

Is this intended behavior or should metabase be able to show the AggregatedFunction hashes for data exploration? If intended behavior, the error should be clearer around needing to apply an aggregate function to the AggregateFunction field. 

### Expected behavior

Show the AggregatedFunction hash or a clearer error message around how to query AggregateFunctions.

### Information about your Metabase installation

```JSON
Chrome Version 117.0.5938.92 (Official Build) (arm64)
ClickHouse server version 23.6.1 revision 54464
Metabase version v0.46.2
```

### Severity

low

**Comment by caoimhebyrne** [comment]
The issue was archived over there because it was merged into this repo, is this going to be re-opened?
