### ISSUE TITLE
Inconsistent display of numbers in Arabic locales

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#34271]
### Describe the bug

When the locale is set to Arabic, visualizations show Western numbers except for dates which are shown with Arabic numerals.

<img width="754" alt="products_arabic_locale" src="https://github.com/metabase/metabase/assets/11080638/c05646e0-df10-4fc1-a161-e7eb45c405e3">

### To Reproduce

1. Set Instance Language to Arabic in Admin Settings / Localization.
2. Open any chart or table with dates and other numbers and see dates are in Arabic, while other numbers are displayed with Western numerals.

### Expected behavior

In a visualization, all numbers should be displayed the same way. Ideally whether to display Arabic or Western numerals should be configurable / selectable.

### Logs

n/a

### Information about your Metabase installation

```JSON
`1.47.2`
```

### Severity

It has been reported / requested by a customer.

**Comment by luizarakaki** [comment]
@alxnddr Let's start by making it consistent with Western numerals: all numbers and dates in Western.

If we have more requests to make it configurable, we evaluate this alternative.

**Comment by rafpaf** [comment]
@EmmadUsmani Do you think we should also show Latin numbers when the locale is Persian?

**Comment by EmmadUsmani** [comment]
@rafpaf Good question! I think it makes sense for the numerals to be consistent in the Persian locale as well, ideally users shouldn't see a mix of Latin and Arabic numerals, they should only see Latin. Ideally there would be a setting for this, but that would be significantly more work.
