### ISSUE TITLE
Consolidate `migrate!` helpers

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#34273]
We currently have (at least) two helpers for migrations.

1. [test-migrations](https://github.com/metabase/metabase/blob/master/test/metabase/db/schema_migrations_test/impl.clj#L219)
2. [migrate!](https://github.com/metabase/metabase/blob/master/src/metabase/db/setup.clj#L55)

Given a migration version `N`,
- the first one will run all migrations until and including `N-1`
- the second one will include migration `N` (source: [Slack chat](https://metaboat.slack.com/archives/CKZEMT1MJ/p1696238846373279?thread_ts=1696238370.217509&cid=CKZEMT1MJ))

The second one supports migrating up and down, force-migrating, etc, while the first one only migrates up.

It would be great if we could consolidate these.

**Comment by qnkhuat** [comment]
In https://github.com/metabase/metabase/pull/34400 I've tweaked the `test-migrations` macro to make the `migrate!` function it bound to be able to do both up and down migrations.

You can use it like this

```clojure
(impl/test-migrations "v48.00-001" [migrate!]
  ;; migrate up to "v48.00-001" migration
  (migrate!)
  ;; migrate down to version 47 (aka the last migration of 47)
  (migrate! :down 47))
```

this should remove the need to use `metabase.db.setup/migrate!` function manually.
