### ISSUE TITLE
Pivot Table Viz shows different output and calls different endpoints when saved VS being created 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#34278]
### Describe the bug

When creating a Pivot Table it calls different endpoints when saved VS being created ... These endpoints also load different kinds of data:

Loading a PIVOT after you saved it loads this amount of data:

<img width="1509" alt="image" src="https://github.com/metabase/metabase/assets/110378427/34146bb7-d20c-4d42-897c-408bb5230033">

While recreating the same question before saving it only loads 1/4 of the data:

<img width="1510" alt="image" src="https://github.com/metabase/metabase/assets/110378427/40eb6643-cc01-4cb0-a92e-fb68b845dfdf">

### To Reproduce

1. Go to New Questions -> Analytics -> Summarise by Count and group by all available columns:

<img width="1159" alt="image" src="https://github.com/metabase/metabase/assets/110378427/12006adc-28ae-4f1f-9a7c-cd44e828e54a">

2. Change Visualisation -> Pivot Table -> Set it up as follows and notice that it returns `100,912` rows

<img width="1505" alt="image" src="https://github.com/metabase/metabase/assets/110378427/66b1a9d8-a5e3-4f17-86ab-416568c2e4c7">

Open the network developer tools and you can see a call is being sent to `/api/dataset/pivot`

<img width="1509" alt="image" src="https://github.com/metabase/metabase/assets/110378427/16a3ffba-dc1f-4891-b2f8-2390fbd07967">

3. Now save the question and refresh the question. You will notice it takes much **more time** and  it returns `436,561` rows

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/a6eee659-8123-4694-80cc-4d986566d997">

   This time you will notice a call is being sent to `/api/card/pivot/12/query`

### Expected behavior

For once we should get similar results & second the time should match. Since showing a fast pivot when you are creating it and a very slow one after you save it and add it to the dashboard is very confusing 

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.47.2 and same thing happens for master even though the output gives different row amount for the /pivot endpoint
```

### Severity

Major issue for people using Pivot Tables since the two endpoints are giving different results

**Comment by likeshumidity** [comment]
Changed to P1 re: escalation and two blocked customers
