### ISSUE TITLE
Permissions Stage 1 Test Suite

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3428]
This enumerates a test suite for rules in #3362 

All of these scenarios must be tested before releasing 0.20

**Setup**

Databases
* DB-A - Sample database
* DB-2 - Crunchbase

Groups
* All users:
    * full access to DB-A + SQL
    * no access to DB-2
* Admins
    * Full Access to DB-A + SQL 
    * Full Access to DB-B + SQL 
* Operations
    * full access to DB-A
    * partial access to DB2 
        * No SQL
        * only access to companies

Users
* Admin McAdminster (belongs to admin, all users)

* Normal Userface (belongs to all users)

* Operations McSpecialPerson (belongs to operations, all users)

Questions
* crunchbase
    * count of companies
    * count of acquisitions
    * count of rounds
    * SQL count of acquisitions
* sample database
    * count of orders
    * count of people
    * count of reviews
    * SQL count of people

Dashboards
* All crunchbase
    * count of people, companies, rounds
* Public crunchbase
    * just count of companies
* all sample

Pulses
* AllCrunchbase
    * count of acquisitions, companies, rounds
* PublicCrunchbase
    * just count of companies
* RestrictedCrunchbase
    * count of acquisitions, count of rounds
* AllSample
* AllOfEverything (sign everyone up)
    * crunchbase + sample cards

Metrics
* Sample
    * revenue (sum of total | orders table)
* Crunchbase
    * total acquisitions (sum of price amount in acquisitions)
    * average funding rounds (average of number of rounds of funding in companies)

Segments
* Sample
    * expensive shit (price > 50 in products)
* Crunchbase
    * swedish acquisitions  (company country code = SWE in acquisitions)
    * swedish companies (company country code = SWE in companies)

**Tests Cases:** 

Query Builder
- Admin
* [x] can see all tables in crunchbase
* [x] can see all tables in sample
* [x] can ask SQL questions of either
* [x] can see all metrics + segments
- Normal
* [x] can see all tables in sample
* [x] can see no tables in crunchbase
* [x] can ask SQL questions in sample but not crunchbase
* [x] can see sample metrics (revenue) + segments
- Operations
* [x] can see all tables in sample
* [x] can see companies in crunchbase
* [x] can ask SQL questions in sample but not crunchbase
* [x] can see all sample segments + metrics
* [x] can see swedish companies + avg funding rounds

Saved Questions
- Admin
* [x] Can see all questions
- Normal
* [x] Can only see 3 sample questions + SQL count of people 
- Operations
* [x] Can see all sample questions
* [x] Can only see "count of companies" crunchbase questions
* [x] can see SQL count of people (yes, this is weird)
- (Rules)
    - I can see saved questions for tables I have access to
    - I can’t see saved questions for tables I don’t have access to 
    - I can't see saved sql questions for databases I don’t have access to
    - I can see saved sql questions for databases I have access to
    - I can see saved questions for databases I have full access to

Dashboards
- Admin
* [x] can see all 3 dashboards
- Normal
* [x] can only see sample dashboard 
- Operations
* [x] can see public crunchbase + sample dashboard
- (Rules)
    - I can see dashboards that contain cards I have access to
    - I can see dashboards that contains any card I have access to
    - I can’t see dashboards that contain cards I don’t have access to

Pulses
- Admin
* [x] can see all 5 pulses
- Normal
* [x] can see AllOfEverything, AllSample 
- Operations
* [x] Can see Public Crunchbase, AllSample, AllOfEverything
- (Rule)
    - I can see a pulse that only contains cards I have access to
    - I can’t see a pulse that contains a card I don’t have access to
    - I can’t see a pulse that has no cards I have access to
    - I can see a pulse that has cards I don’t have access to if an admin added me to it but I can’t edit

Data Model Reference
- Admin
* [x] can see all sample + crunchbase metrics, segments + tables
- Normal
* [x] can see all sample stuff
- Operations
* [x] can see revenue, avg funding rounds  in metrics
* [x] can see expensive shit, swedish companies in segments
* [x] can see all sample tables
* [x] can only see companies table in crunchbase
- (Rules)
    - I can only see metrics for tables I have access to
    - I can only see segments for tables I have access to
    - I can only see the databases + tables I have access to

**Comment by camsaul** [comment]
Ok I fixed the merge conflict. 

@tlrobinson since we already had a migration 42 I changed yours to 45. You'll probably need to manually fix change the migration row locally or just drop the new `visualization_settings` column and run the migrations again.

**Comment by camsaul** [comment]
Implemented by #3432
