### ISSUE TITLE
MBQL v1 query breaks with boolean breakout

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#34286]
### Describe the bug

When running a basic aggregation query with a boolean breakout, the query fails.	

### To Reproduce

This query fails:
```clojure
; Source table is Accounts, field 8 is LEGACY_PLAN
(qp/process-query
  {:type :query,
   :database 1,
   :query
   {:source-table 7,
    :breakout     [[:field 8 nil]],
    :aggregation  [["count"]]}})
```

I can fix it with:
```clojure
(qp/process-query
  {:type :query,
   :database 1,
   :query
   {:source-table 7,
    :breakout     [[:field 8 {:base-type :type/Boolean}]],
    :aggregation  [["count"]]}})
```

Note that non-boolean queries work:
```clojure
(qp/process-query
  {:type :query,
   :database 1,
   :query
   {:source-table 7,
    :breakout     [[:field 1 nil]],
    :aggregation  [["count"]]}})
```

This is currently manifesting itself in x-ray code. X-raying the Accounts table in the sample database will show broken charts because those charts have boolean breakouts.

See https://github.com/metabase/metabase/pull/34259 for details of a workaround. However, we'd prefer to not use the workaround and have the queries work as epected.

### Expected behavior

Not fail with queries that have boolean breakouts.

### Information about your Metabase installation

```JSON
Latest dev branch
```

### Severity

Globally bad for any x-ray user

**Comment by metamben** [comment]
The relevant Slack [discussion](https://metaboat.slack.com/archives/C04CYTEL9N2/p1696873812471329).

**Comment by camsaul** [comment]
See also #34461
