### ISSUE TITLE
Add an option in the `/admin/settings/email` to opt-in to CC recipients

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#34293]
On 47, we changed our subscriptions to send all recipients in BCC.
Some customers reported that their emails were being blocked by their email providers for security reasons.

In most cases, sending the recipients in BCC makes sense (as it preserves the anonymity of recipients). But there are cases when admins want to add recipients in CC:
- if the email provider blocks bcc
- if they want to openly share recipients and have discussions on email threads

We are adding an option on `/admin/settings/email` to send emails with all recipients in CC.
The default behavior continues to be adding everyone as BCC.

Copy suggestion:

header: ADD RECIPIENTS AS CC OR BCC
description: Control the visibility of recipients
options: - Bcc (hide recipients) _default_ - Cc (disclose recipients)

Figma [link](https://www.figma.com/file/DdYMSBqSsMfz9ZIN38D9D8/Add-recipients-as-CC-or-BCC?type=design&node-id=23-393&mode=design&t=zHx72CSTP0qDlezU-4)

**Comment by JesseSDevaney** [comment]
Waiting until backport merged to close
