### ISSUE TITLE
504 Gateway - cannot access site

### ISSUE THREAD

**Issue by katypodbielski** [metabase/metabase#34297]
### Describe the bug

A customer of our company reported they cannot access a report built in metabase and continually experience 504 errors. I performed the steps to replicate, and tried opening our company's site (not specific to 1 dashboard), and found the same 504 error. I cannot access reports nor our company's site at https://reporting.cityinnovate.com/ . May I ask for help to resolve this, so that we can access without 504 errors?

### To Reproduce

1. Go to https://reporting.cityinnovate.com/
2. 504 error

Replicated on 3 different computers

### Expected behavior

Load site without errors

### Logs

Failed to load resource: the server responded with a status of 504 ()
reporting.cityinnovate.com/:1    
Failed to load resource: the server responded with a status of 504 ()

### Information about your Metabase installation

```JSON
Have never installed before
```

### Severity

Blocking usage entirely

**Comment by paoliniluis** [comment]
Sorry, is this instance a Metabase cloud instance? if you need support, please go to the forums, not here
