### ISSUE TITLE
Arabic (and some other languages) are an RTL (right to left) language but currently everything works from LTR (left to right)

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#34318]
**Is your feature request related to a problem? Please describe.**
To create a report in Arabic you have to manually translated the field names from English to Arabic but some aspects are still confusing for someone coming form an RTL language like Arabic

Example: You are unable to change the alignment of y-axis, such that the graph reads from right to left.

<img width="1471" alt="image" src="https://github.com/metabase/metabase/assets/110378427/32fef680-ecdb-45f2-904f-a89e3cad3f28">

Other parts of the tool by default work form LTR 

**Describe the solution you'd like**
Changing to Arabic would make the structure to RTL for example  flip the y-axis including title so a chart becomes RTL

**How important is this feature to you?**
It's hard for people to read Arabic if they are used to RTL

**Comment by brunobergher** [comment]
Don't we have a more generic "Proper RTL" support issue somewhere? Doing this correctly cuts across viz, numbers, navigation structure, order of checkbox -> label, etc. We should gather signal for it in one place.

**Comment by Tony-metabase** [comment]
Do you mean like an EPIC of some sort? ... Since there aren't many Arabic related issues right now but a new customer seems to have a number of issues when the setting is changed to Arabic.

I can change the feature request and make it more generic so more research can be applied for all the paths that require RTL

**Comment by brunobergher** [comment]
No, as a single issue to gather signal on the need for RTL support. It would be somewhat similar for Hebrew and Farsi, as far as I know.

**Comment by Tony-metabase** [comment]
Yep you are right! Sorry was looking at issues having Arabic Specific keywords
