### ISSUE TITLE
[MLv2] Removing an aggregation from a query using remove-field corrupts query

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#34321]
[remote-field](https://github.com/metabase/metabase/blob/87cddad248833e2995bd535ca1a8c4e64dbc7145/src/metabase/lib/field.cljc#L643) appears to handle columns with `:source/aggregations`, but calls `exclude-field` which will always assoc the remaning fields in the `:fields` key of the query, instead of removing the column from `:aggregations`. Screenshots below:

Column to be removed, and resulting query: 
![image](https://github.com/metabase/metabase/assets/1328979/caf2820e-89fc-40f4-bb2f-2bfbdb563f2e)

Metabase Lib function used: 
![image](https://github.com/metabase/metabase/assets/1328979/49a905ca-4531-4874-8444-4697f0ca1c3c)

Error Returned when calling `returned-columns` on the returned query:
![image](https://github.com/metabase/metabase/assets/1328979/7aec4cfe-025a-4214-a96d-911bf8cf90a4)

**Comment by metamben** [comment]
@npfitz should we close this issue?

**Comment by npfitz** [comment]
I do still think there is a bug in the code here that `remove-field` accepts an `ColumnMetadata` object with a [source of aggregations](https://github.com/metabase/metabase/blob/171d3d2d9eeac6857dd7bca06d82e063c6da8eea/src/metabase/lib/field.cljc#L661), and the resulting query is corrupt (or at least causes an error when you try to work with it again). If `remove-field` doesn't work with aggregations, it should return an error. I guess what I meant in my response in Slack was that this wasn't a blocker for me

**Comment by metamben** [comment]
I'll have another look at why the query breaks when I'm done with the blockers.

**Comment by bshepherdson** [comment]
This bug is not "bleeding" on master anymore. There's nowhere in the UI where you can trigger this logic - if you open the column selection sidebar on a question with aggregations and breakouts, it shows you the axes. They have :x: symbols to delete them, but that updates the viz settings; the query isn't edited.

That said, I'm going to make `remove-field` on an aggregation or breakout column throw as a protection.
