### ISSUE TITLE
Description for calculated columns in model metadata editing page is incorrectly populated with description from other columns

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#34349]
### Describe the bug

Description for calculated columns in model metadata editing page is incorrectly populated with description from other columns

### To Reproduce

1. New Question > Raw Data > Sample Dataset > Orders
2. Add calculated column "County" with the expression `substring("United States", 1, 20)`
3. Run query
4. Save Question
5. Convert to model
6. Edit model metadata
7. Click `Country` column. Description is from whatever column you clicked last instead of being empty

### Expected behavior

Description should be empty for the calculated column

### Information about your Metabase installation

```JSON
This is on stats on pre-48 (October 3rd, 2023)
```

### Severity

annoying. Correctness issue

### Additional context

https://www.loom.com/share/a2a4943784f347408e4f5b5f270719a5?sid=41e527ff-5883-4af4-bcf9-6d143fc5da32

**Comment by paoliniluis** [comment]
Sibling of https://github.com/metabase/metabase/issues/25884
