### ISSUE TITLE
[MLv2] [BE] `sort` drill generates incorrect query on apply

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#34342]
`sort` drill generates incorrect query on apply. 

Use this unit test to reproduce and validate after the fix - https://github.com/metabase/metabase/blob/33973-mbql2-drills-quick-filters/frontend/src/metabase-lib/drills.unit.spec.ts#L1387 

<table>
<tr>
<th> Expected MBQL: </th>
<th> Actual MBQL: </th>
</tr>
<tr>
<td>

```
{
    "order-by": [
      [
        "asc",
        [
          "field",
          11,
          {
            "base-type": "type/BigInteger"
          }
        ]
      ]
    ],
    "source-table": 2
  }
```

</td>
<td>

```
{
    "order-by": [
      [
        "asc",
        {},
        [
          "field",
          11,
          {
            "base-type": "type/BigInteger"
          }
        ]
      ]
    ],
    "source-table": 2
  }
```

</td>
</tr>
</table>

**Comment by camsaul** [comment]
Next time, can you add a little more info, and add labels to the issue?
