### ISSUE TITLE
Unable to switch question to query table in another database

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#34350]
### Describe the bug

I have questions created for database A (Redshift) that I am trying to migrate to use the same table in another database (Postgres). When I try to change the table, the UI seems to be fine, however when run, it returns this error: Failed to fetch :metadata/table 36176

It seems the database is still tied to the old one instead of switching to the new database attached to the table -- there is only one table in query. 

### To Reproduce

1. Open a saved question in database A (or just browse to a table)
2. In notebook editor, change the table to another table in database B. 
3. Run the query to see error

### Expected behavior

Database should for the question should change based on the first table used

### Logs

n/a

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

It blocks any manual migration; thankfully I do have a migration script that can bypass it via API

**Comment by calherries** [comment]
I can repro on `master` (69ca1a0a9c) but not on `release-x.46.x` (517b218c02) and `release-x.47.x` (80d03f743b).

In the API request body to POST /api/dataset, in the dataset_query, the table is updated but the database is not.

The first request body: 
<img width="434" alt="image" src="https://github.com/metabase/metabase/assets/39073188/1572ba96-ae9b-45d6-bf67-4900977c6c6f">

After changing to use a table from a different database, the second request body contains the original database:
![image](https://github.com/metabase/metabase/assets/39073188/2d22fe47-3781-4f3d-936d-4715a93dbe49)

**Comment by NevRA** [comment]
Broken by this PR: https://github.com/metabase/metabase/pull/34256

**Comment by kulyk** [comment]
Would require a BE change (#35245) and a FE change

**Comment by darksciencebase** [comment]
since the BE change is tracked in #35245 which is on the QPD board, i'm removing this issue from there

**Comment by kamilmielnik** [comment]
Video from repro at 69ca1a0a9c5d87a216cf5e2f5dfe036f074de8ae
https://github.com/metabase/metabase/assets/6830683/e6b318ae-c5a9-4cd2-a123-7e4d321b44bd
