### ISSUE TITLE
Possibility to write within a table

### ISSUE THREAD

**Issue by veniphere** [metabase/metabase#34355]
First, Metabase is a great product, thanks.

Its main function is to read data.

Sometimes there is some circumstances where users need to write data within a join table, making relation between data coming from a database where Metabase is connected to.

Because Metabase can read and show data in rows, it could help users to maintain these data by writing or updating data (if write rights are set up within that remote the database Metabase could be connected on).

Best

**Comment by paoliniluis** [comment]
please check the new actions feature
