### ISSUE TITLE
Split liquibase migration

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#34361]
# Slow on New Instance

Currently, when spinning up a new Metabase instance, it runs through all migrations.  This takes relatively longer on some DBs (ex: MySQL), and that problem will only worsen over time.

**Proposal**: let’s maintain two different Liquibase files, `U` and `C`.  `U` is for updating an existing app DB to the latest state, which is precisely what we already have.  `C` is for creating the initial DDL for a new app DB instance.

As a matter of fact, `C` doesn’t even have to be a Liquibase file.  It can just be a set of DDL statements we execute on a blank app DB when initializing (in lieu of running Liquibase).  And these files (per app DB type) could probably even be generated automatically by having some test code spin up a blank app DB, run Liquibase, then export the DDL to a file (equivalent to `pg_dump`), and capture that file.

In order to do this, we would have to "fake" the current Liquibase state within `C` somehow, so that going forward, migrations from that point onwards work correctly.  That may be tricky.

Originally: https://www.notion.so/metabase/Liquibase-migration-issues-c741757c851a4c3bb52bf4d19c21bf76?pvs=4

**Comment by paoliniluis** [comment]
good idea, the big question is why it takes that amount of time in MySQL

**Comment by qnkhuat** [comment]
We will use all the migrations before 45 to generate an init SQL.

Then the current migration will be splited into 2 files:
1. containing migrations from 0 to the last migration of 44 -- call this legacy migration file
2. containing migrations from 45 till the most recent one

### How upgrade gonna play out in real life?

Scenario 1: Fresh instance
1. Run the init SQL
2. Migrate with the new migration file

(note: there is no need to run data migrations here because data migrations are used to fix bad data)

Scenario 2: Upgrade from pre-45
1. Migrate using the legacy migration file 
2. Migrate using the new migration file
3. Run data migration

Scenario 3: Upgrade from post-45
1. Migrate using the new migration file

Also we'll need to deprecate data migrations, there are no reasons to keep using them as we now have custom migration with liquibase. (#34396)
