### ISSUE TITLE
If a migration fails, log which migration failed

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#34374]
**Is your feature request related to a problem? Please describe.**
When a migration fails, we just log the SQL error. Something like
```
Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2713).
ERROR: column "jsonasdf_unfolding" of relation "metabase_field" does not exist
  Position: 27
```
This makes it much harder to debug failed migrations

**Describe the solution you'd like**
Log which migration failed:
- migration_id
- migration_comment

**How important is this feature to you?**
Important to streamline the Migrate to Cloud process

**Additional context**
Part of [Allow migrate to Cloud from different versions](https://www.notion.so/metabase/Allow-migrate-to-Cloud-from-different-versions-00686c3b541c4b5c9f983838ffdc3cde?pvs=4)

**Comment by crisptrutski** [comment]
@luizarakaki do you have a copy of the full stack trace? I'd like to confirm where the exception is thrown from to be doubly sure.

**Comment by paoliniluis** [comment]
@crisptrutski e.g. https://github.com/metabase/metabase/issues/10087

**Comment by crisptrutski** [comment]
Yeah, I'm guessing this came from the fact that the linked issue failed after all the changesets had run. Printing the comment doesn't add that much value so also inclined to scrap this.

**Comment by luizarakaki** [comment]
So this error comes from load-from-h2 and not the migrations.

Thanks for the investigation. Hopefully we will have a better understanding of these errors when we implement [Prouductize Cloud Migrations](https://www.notion.so/metabase/Productize-Cloud-migration-9ac517a86a5d4312ae4f0a37c9625e67)
