### ISSUE TITLE
Dashboard filter Apply button does not follow column structure and shows up to right of other elements instead of below them

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#34385]
### Describe the bug

- When Auto-apply filters is disabled, and the viewport is narrow like on mobile devices, the Apply button shows up to the right of the filter elements and makes them narrower by taking up a full column.
- From Maz: "I assume that, on mobile, the button should be full-width, and should either appear at the bottom of the list of filters, or at the top of the list (I think my bias is the bottom)."
- Customer reported and also requested Apply button show up below filters.

### To Reproduce

1. View a dashboard with filters (X-ray Sample Data > Products table and save resulting dashboard)
2. Click i icon and disable Auto-apply filters on dashboard
3. Change browser to narrow viewport like mobile emulation or just make window very narrow (200-400px wide)
4. Change a filter
5. See Apply button to right of filters and filters resized narrower

### Expected behavior

Apply button should be same width as filters and show up below filters

### Information about your Metabase installation

```JSON
- Metabase v1.47.3 and `master` as of `24b3553`
```

### Severity

P3: Cosmetic, but can also reduce filter usability a bit by making them narrower

**Comment by zamar-roura-fever** [comment]
Awesome feature! We want to implement the apply filter button in an embedded dashboard but in mobile looks bad and we are waiting for this.
