### ISSUE TITLE
Execute an Action on embedded Dashboard fails with 404 not found API call

### ISSUE THREAD

**Issue by bbohec** [metabase/metabase#34395]
### Describe the bug

Given there is a dashboard with an action.

- Using the action in the dashboard directly on Metabase works as expected. With the API call pattern:
`https://METABASE_URL/api/dashboard/DASHBOARD_ID/dashcard/ACTION_ID/execute`
- Using the action in the dashboard that is embedded on website does not work with a 404 not found API response.
`https://METABASE_URL/api/dashboard/DASHBOARD_EMBEDDED_TOKEN/dashcard/ACTION_ID/execute`

Seems that the embedded routes have missing action execute on API.

### To Reproduce

- Go to an embedded dashboard with an action.
- Click the action.
- Add parameters
- Execute the action
- The action fails with not found error and network error on webclient console with a 404 response

### Expected behavior

Action could be executed from embedded dashboard

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.7+7-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "17.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.7+7-LTS",
    "os.name": "Linux",
    "os.version": "5.4.0-135-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.6 (Debian 14.6-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v0.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking usage of actions on embedded dashboard

**Comment by paoliniluis** [comment]
Actions in static embedding doesn’t work https://github.com/metabase/metabase/issues/30266

**Comment by calherries** [comment]
We should either (1) hide actions from signed embedded dashboards, or (2) support them fully

**Comment by cdeweyx** [comment]
> We should either (1) hide actions from signed embedded dashboards, or (2) support them fully.

We decided to hide this functionality right now rather than support it. [More context here](https://metaboat.slack.com/archives/C057T1QTB3L/p1696519212704419).

**Comment by bbohec** [comment]
Unable to connect to Metabase Slack to get more context. Does the team plan an alternative to be able to execute a Metabase Action outside of direct Metabase access?

**Comment by WiNloSt** [comment]
@albertoperdomo What should the behavior for static embedding and public sharing dashboards be between
1. Currently on `master`: We always disable the action with a tooltip saying that the action is disabled for the given database which is untrue. It's only that we don't send `database_enabled_actions` in `dashboard.dashcards` for public and static embed dashboards, and this is the property we used to determine when to show that tooltip.
    ![Screenshot 2024-02-22 at 3 09 15 PM](https://github.com/metabase/metabase/assets/1937582/d9888dce-3b85-4b75-9cc7-7c5f71b76dcd)

1. We hide the actions from dashboards
    ![image](https://github.com/metabase/metabase/assets/1937582/1da606af-3b5a-4586-9ffa-ded8c9977cf7)

**Comment by albertoperdomo** [comment]
Hello @bbohec,

for now we're completely hiding actions in static embeds. Please follow https://github.com/metabase/metabase/issues/30266 for the feature request to add full support of actions in static embeds. Feel free to upvote there as well to express your need/interest.

Thanks.
