### ISSUE TITLE
Region Map should have some distinguishable border for each state

### ISSUE THREAD

**Issue by nisrulz** [metabase/metabase#3440]
The region map does not have very clear distinguishable borders to show different states inside a country when same color coded 

![screen shot 2016-10-04 at 10 50 40 am](https://cloud.githubusercontent.com/assets/2096087/19063535/74762d9a-8a21-11e6-8947-51e67f028432.jpg)

If we could introduce some `stroke` to the each such section it can be solved. A quick hacky example

![screen shot 2016-10-04 at 10 52 06 am](https://cloud.githubusercontent.com/assets/2096087/19063575/b63a017a-8a21-11e6-89d1-a1b63a46a1f0.jpg)

Configurations 

- Your browser and the version: Version 53.0.2785.89 (64-bit)
- Your operating system:OS X 10 El Capitain
- Your databases: MySQL
- Metabase version:  v0.19.3
- Metabase hosting environment: Mac OSX
- Metabase internal database: MySQL

**Comment by tlrobinson** [comment]
Actually this is already done in `master` and will be released in v0.20 shortly, along with the ability to add custom GeoJSON maps

 
![screenshot 2016-10-03 22 57 41](https://cloud.githubusercontent.com/assets/18193/19064114/db7f455e-89bc-11e6-8285-27a5d94dfece.png)
