### ISSUE TITLE
Native SQL containing special characters like "?" and field filters ends up screwing query preview

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#34402]
### Describe the bug

When you are writing SQL question having field filters and having in the syntax a character like `?` will end up showing field filter values instead of the character `?`

<img width="1357" alt="image" src="https://github.com/metabase/metabase/assets/110378427/b3995743-ab6b-4214-a48d-a1ee56cf6351">

### To Reproduce

1. Go to New -> SQL Question -> Sample Database -> Paste the below:

```
select category,
  CASE WHEN category = '?' THEN 1 ELSE 2 END   AS clean_url_dns,
from products
WHERE {{date}}
AND {{id}}
AND {{category}}
```

2. Setup field filters (as long as they are part of the product table) -> Assign some values -> Click Preview

<img width="1203" alt="image" src="https://github.com/metabase/metabase/assets/110378427/31e1ad8d-88f8-4803-9bd0-4cb2e5905185">

3. Notice how the `?` in the case has become a date and the category field filter now contians a `?`

<img width="1115" alt="image" src="https://github.com/metabase/metabase/assets/110378427/2f9b8c31-a3ba-4fd2-b4be-248876fb9caa">

4. Note that the query runs properly and correct syntax is sent so this is something at frontend level in my opinion

### Expected behavior

Query Preview should work

### Logs

None

### Information about your Metabase installation

```JSON
1.47.3 and master
```

### Severity

Causes confusion when you preview

**Comment by paoliniluis** [comment]
@darksciencebase also see https://github.com/metabase/metabase/issues/34482
