### ISSUE TITLE
DashboardTab missing from `copy` command 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#34411]
### Describe the bug

`copy` command stopped working if you have a DashboardTab

### To Reproduce

1. 47 or above
2. Have a DashboardTab
3. Run `dump-to-h2`

### Logs

```
Command failed with exception: ERROR: insert or update on table "report_dashboardcard" violates foreign key constraint "fk_report_dashboardcard_ref_dashboard_tab_id"
  Detail: Key (dashboard_tab_id)=(2) is not present in table "dashboard_tab".
```

### Information about your Metabase installation

```JSON
This is on 47 or on `master`
```

### Severity

P1

**Comment by camsaul** [comment]
Also missing: `ModelIndex`, `ModelIndexValue`, `TablePrivileges` (48+), and it seems the EE models `GroupTableAccessPolicy` and `ConnnectionImpersonation` were never added either.

The code that caught this stuff was broken recently =(

**Comment by qbey** [comment]
Thank you for the fix :) I used the master branch to be able to make my H2 -> PSQL migration, worked like a charm :ok_hand:
