### ISSUE TITLE
Hiding the title doesn't work for number cards

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#34421]
### Describe the bug

If you disable the title in static embedding, that won't work for number cards
![image](https://github.com/metabase/metabase/assets/1711649/3220ce03-108e-4299-bac7-f4ed19895c86)
![image](https://github.com/metabase/metabase/assets/1711649/cfe5a082-7f22-4c9e-bd6f-e3f8c01483c9)

### To Reproduce

1) enable embedding
2) create a number card
3) disable the title, see that it won't work

### Expected behavior

It should disable the title

### Logs

NA

### Information about your Metabase installation

```JSON
It's been like that for ever
```

### Severity

P3

**Comment by albertoperdomo** [comment]
Work as expected:

* The title (top left) is hidden as expected.
* The name of scalar below the number is not the title.

<img width="1606" alt="image" src="https://github.com/metabase/metabase/assets/24216/a250a39f-8444-4457-a12f-a6e922bcf600">
<img width="1591" alt="image" src="https://github.com/metabase/metabase/assets/24216/77e68ca5-c560-4d8f-8660-f5104424b88a">
