### ISSUE TITLE
[MLv2] [BE] `quick-filter` gets returned for non-metric column

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#34443]
`quick-filter` gets returned for FK column (PRODUCT_ID)

Check this reproduction unit test:
https://github.com/metabase/metabase/blob/5ab317540d064ac3d402508d0038629e8a041575/frontend/src/metabase-lib/drills.unit.spec.ts#L504

ALSO `quick-filter` doesn't get returned for CREATED_AT column in aggregated query - 
https://github.com/metabase/metabase/blob/7d9d4f42af6cf3ef31514b23184a3a79d449c3d2/frontend/src/metabase-lib/drills.unit.spec.ts#L1030

**Comment by camsaul** [comment]
The Cypress tests are enabled in master now, so this is fixed already.
