### ISSUE TITLE
Click behavior doesn't respect tab choice when redirecting to a dashboard

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#34447]
**Is your feature request related to a problem? Please describe.**
If you choose to use click behavior and set it up to go to a dashboard on a click, you can't select the tab, you'll always go to the first tab.

This is important if you want to do a click behavior on teh same dashboard, e.g. click on a card in the first tab and then go to the second tab.

EDIT: you can't go to a specific tab of a dashboard when doing click behavior from another dashboard :(

**Describe the solution you'd like**
Select the tab when you use click behavior

**Describe alternatives you've considered**
~You need to do a URL link to the tab and the category~ can't do that, as the URL will be hardcoded (/dashboard/...) and you're in a signed context where you need a signed token (base64 encoded)

**How important is this feature to you?**
Just figured out this by doing a click behavior

**Additional context**
NA

**Comment by cdeweyx** [comment]
Working on this as part of https://github.com/metabase/metabase/issues/34367

**Comment by paoliniluis** [comment]
Thanks @cdeweyx, just to add: we need to ensure this works on embedding contexts

**Comment by cdeweyx** [comment]
You can select which tab to redirect to, but click behavior always routes you to Tab #1 for some reason...
