### ISSUE TITLE
Doing distribution on boolean field is broken

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#34461]
### Describe the bug

When browsing a model or table, if you try to click on a boolean column and select Distribution, it is showing an error: `Invalid output: {:stages [{:order-by [[nil nil ["an expression that can be compared with :> or :<" "an expression that can be compared with :> or :<"]]], :source-card ["missing required key"]}]}`

Interestingly, if you do a group by yourself via Summarize or editor, it works fine. 

### To Reproduce

1. Try to do distribution on a boolean column

### Expected behavior

It should show distribution instead of error

### Logs

n/a

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

I can workaround it by doing the group by myself

**Comment by uladzimirdev** [comment]
@maxzheng could you please provide more explicit steps to reproduce?

**Comment by paoliniluis** [comment]
I don't know what we did, but it works now

**Comment by bshepherdson** [comment]
That's a Malli error message, and we've disabled those in prod.

I think this specific issue was also fixed before we did that, but I wasn't able to find the PR.
