### ISSUE TITLE
Remove RawTable and RawColumn models

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3448]
They're not really used for anything: they were added as part of #2372, ostensibly to make it easier to implement virtual tables in the future; they've caused lots of problems (e.g. #2632,  #4309, #4474) and suffer from poor performance -- they have no indexes or constraints (#3086).

We keep paying interest on this tech debt so might as well clean up the mess.

**Comment by camsaul** [comment]
They slow down DB sync a lot too because we basically create two artifacts everywhere where we used to create one

**Comment by camsaul** [comment]
It makes our sync logic a lot harder to understand too because instead of one place that had sync logic like we had before there's effectively a duplicate one now.

Before there was one step:
1.  Sync the database, create/update Tables & Fields

Now we have two:
1.  "introspect" the database, create/update RawTables & RawColumns
2.  "sync" the database, going back over everything in RawTables & RawColumns and creating/updating Tables & Fields to match them

**Comment by salsakran** [comment]
before doing anything here, let's chat about how #1822 might work, and whether the notion of fields + tables needs to be generalized. I rather avoid a "put the paper clip in, then take the paper clip out" situation.

**Comment by salsakran** [comment]
let's do this in the context of #1822. 

If we don't need a separation between the raw tables and normal tables to make that work, we can remove it. My hunch is that that separation will make it easier to do #1822 and similar projects.

**Comment by camsaul** [comment]
I don't think we'll need to keep these around to make #1822 work. If anything it might make things a little harder because there's so much extra code involved in the sync process that tweaking it is like stepping on eggshells these days. Plus it's confusing to have two models to represent one object

The easiest thing I think would have been just to add a `is_virtual` flag to Table or something like that rather than creating an entire new model that now has to be kept in sync with everything

**Comment by salsakran** [comment]
That works too. Mainly don't want to remove something only to realize it's useful and pulling it back in

**Comment by camsaul** [comment]
The code as it currently stands won't support #1822 so RawTable and Table would both have to be overhauled, and we'd have to add some way to store a virtual definition of a Table

It would probably be just as fast just to drop the RawTable (and RawField) models so we only have to rework Table.

**Comment by camsaul** [comment]
Fixed by #7863
