### ISSUE TITLE
Snowflake Dynamic Table Support

### ISSUE THREAD

**Issue by vinutshetty** [metabase/metabase#34483]
### Describe the bug

Currently, Metabase Questions doesn't work for Snowflake Dynamic Table type

Below query generated by metabase fails on Snowflake side 
show /* JDBC:DatabaseMetaData.getForeignKeys() */ imported keys in table "L2"."L2_TMS"."L2_CITY"

### Information about your Metabase installation

```JSON
v0.47.1
```

### Severity

high

**Comment by paoliniluis** [comment]
Sorry, this issue lacks the majority of the sections we need to properly address the issue so I'll proceed to close it.

Next time you open an issue in this repository:
1) include reproduction steps
2) include logs and errors
3) include context
