### ISSUE TITLE
"View the SQL" for model or question results in invalid SQL in some cases

### ISSUE THREAD

**Issue by arlampin** [metabase/metabase#34482]
### Describe the bug

We have some native SQL based models, which use standard `||` (concat) and Postgres specific `&&` (array overlap) operators. When using "View the SQL" for some question that uses these models, the resulting query has split these two with a space, so the results are invalid `| |` or `& &`.

### To Reproduce

1. Create a native model with the following content `select 'foo' || 'bar' as baz`
2. Save the model
3. Click on "Show editor" -> "View the SQL"
4. Note the invalid SQL

### Information about your Metabase installation

```JSON
Metabase 0.47.3 on Docker
```

### Severity

Annoying

**Comment by paoliniluis** [comment]
A sibling of https://github.com/metabase/metabase/issues/34402
