### ISSUE TITLE
Summarize button breaks if custom column with ratio between 2 aggregated columns from saved questions

### ISSUE THREAD

**Issue by BertrandToulas** [metabase/metabase#34515]
### Describe the bug

When I create a custom column with a division between 2 aggregated values belonging to 2 saved queries joined together, I'm instantly sent to a "Something has gone wrong" page if I click the Summarize button.

### To Reproduce

Using the Sample Database:
1. Create this query
![image](https://github.com/metabase/metabase/assets/71009735/abe0b3b6-65cf-4920-854d-721853dd27bc)

2. Create this query Click on '....'
![image](https://github.com/metabase/metabase/assets/71009735/b3445fc3-8d97-4ed9-8f71-2ad2408b0af4)

3. Create a third query that joins those two queries. Note: it doesn't matter which is the numerator and which is the denominator in the custom column.
![image](https://github.com/metabase/metabase/assets/71009735/ff667ee1-d666-4c66-9c33-ad8ef5d2cf61)

![image](https://github.com/metabase/metabase/assets/71009735/a83a6689-0cb5-4d62-bff3-b7ab7ee3d08f)

4. Click "Summarize". You should get this error page.
![image](https://github.com/metabase/metabase/assets/71009735/c9e231de-182e-4225-a13b-80063035eb3c)

### Expected behavior

The Summarize button shouldn't break. At the very least, the user should be able to try summarizing, then get an error page with an error message for easier debugging.

### Logs

JS console logs :
`Object { message: 'Error calculating metadata Error calculating display name for [:/ {:lib/uuid "0c2118bd-3217-44a3-adaf-f07eb3763978", :lib/expression-name "ratio"} [:field {:base-type :type/Float, :lib/uuid "05102761-2649-4eda-baaa-caeacfd0aa1d"} "sum"] [:field {:base-type :type/Integer, :join-alias "Question 1819", :lib/uuid "2d736f03-d7a2-4406-b8d8-fdb5dcc14130"} "sum"]]: Error calculating display name for [:field {:base-type :type/Float, :lib/uuid "05102761-2649-4eda-baaa-caeacfd0aa1d"} "sum"]: Error calculating metadata Error calculating display name for [:/ {:lib/uuid "0c2118bd-3217-44a3-adaf-f07eb3763978", :lib/expression-name "ratio"} [:field {:base-type :type/Float, :lib/uuid "05102761-2649-4eda-baaa-caeacfd0aa1d"} "sum"] [:field {:base-type :type/Integer, :join-alias "Question 1819", :lib/uuid "2d736f03-d7a2-4406-b8d8-fdb5dcc14130"} "sum"]]: Error calculating display name for [:field {:base-type :type/Float, :lib/uuid "05102761-2649-4eda-baaa-caeacfd0aa1d"} "sum"]: Error calculating metadata E…', data: {…}, cause: {…}, name: "Error", description: undefined, number: undefined, fileName: "https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js", lineNumber: 2, columnNumber: 5206280, stack: "2880/yr.xj@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5206280\n2880/yr.yj@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5206585\n40471/<@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5868231\n2880/yr.h.j@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5370285\n40471/j.$0@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5861897\nl@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5953564\no@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5503655\n2880/yr.Qm.h/<@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5289051\n2880/yr.h.Oa@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5294382\n2880/yr.Sb@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5170848\n2880/yr.Qm.h@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5289012\n73850/P.h@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5963275\nb@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5958704\n73850/<@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5963812\n2880/yr.h.D@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5370459\n75284/g.N5@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5820489\n75284/g.O5@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5820531\n40590/ie.h@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5786306\nlt@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5176477\nat@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5176415\n2880/yr.R.h@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5262557\nt@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5796026\navailable_aggregation_operators@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:5850311\ni@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:198162\n52314/AK/f<@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:2724622\nuseMemo@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4048070\n18447/t.useMemo@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4494967\nAK@https://b-i.moodwork.com/app/dist/app-main.6c2b4fdd50d45a2344a2.js:2:2724600\nta@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4043218\nxs@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4089267\nSc@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4082028\n_c@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4081951\ngc@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4078974\n83975/Ji/<@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4030622\n39666/t.unstable_runWithPriority@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4525956\nVi@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4030331\nJi@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4030569\nZi@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4030502\nT@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4099403\nKt@https://b-i.moodwork.com/app/dist/vendor.8c94e15957c840c06fcb.js:2:4007822\n" }
react-dom.production.min.js:209:194
    React 9
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
`

`Error: 
Object { componentStack: "\n    in AK\n    in div\n    in u\n    in span\n    in l\n    in Triggerable[l]\n    in div\n    in NotebookCell\n    in XQ\n    in EK\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in JK\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in div\n    in u\n    in QY\n    in div\n    in Styled(div)\n    in iX\n    in div\n    in Styled(div)\n    in Unknown\n    in l\n    in Connect(l)\n    in EntityType\n    in Connect(EntityType)\n    in Unknown\n    in div\n    in Styled(div)\n    in Boe\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in div\n    in o\n    in ExplicitSize[o]\n    in Unknown\n    in Unknown\n    in Title[]\n    in Title[Title[]]\n    in Favicon\n    in Connect(Favicon)\n    in o\n    in Connect(o)\n    in a\n    in EntityType\n    in Connect(EntityType)\n    in Connect(EntityType)\n    in Connect(Favicon)\n    in l\n    in o\n    in Connect(o)\n    in a\n    in EntityType\n    in Connect(EntityType)\n    in Connect(EntityType)\n    in Connect(Favicon)\n    in Unknown\n    in UserIsAuthenticated(Component)\n    in Connect(UserIsAuthenticated(Component))\n    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))\n    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))\n    in main\n    in Styled(main)\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in o\n    in withRouter(o)\n    in s\n    in Unknown\n    in Connect(Component)\n    in Title[Connect(Component)]\n    in RouterContext\n    in Router\n    in p\n    in @mantine/core/MantineProvider\n    in h\n    in DragDropContextProvider\n    in I" }
​
componentStack: "\n    in AK\n    in div\n    in u\n    in span\n    in l\n    in Triggerable[l]\n    in div\n    in NotebookCell\n    in XQ\n    in EK\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in JK\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in div\n    in u\n    in QY\n    in div\n    in Styled(div)\n    in iX\n    in div\n    in Styled(div)\n    in Unknown\n    in l\n    in Connect(l)\n    in EntityType\n    in Connect(EntityType)\n    in Unknown\n    in div\n    in Styled(div)\n    in Boe\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in div\n    in o\n    in ExplicitSize[o]\n    in Unknown\n    in Unknown\n    in Title[]\n    in Title[Title[]]\n    in Favicon\n    in Connect(Favicon)\n    in o\n    in Connect(o)\n    in a\n    in EntityType\n    in Connect(EntityType)\n    in Connect(EntityType)\n    in Connect(Favicon)\n    in l\n    in o\n    in Connect(o)\n    in a\n    in EntityType\n    in Connect(EntityType)\n    in Connect(EntityType)\n    in Connect(Favicon)\n    in Unknown\n    in UserIsAuthenticated(Component)\n    in Connect(UserIsAuthenticated(Component))\n    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))\n    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))\n    in main\n    in Styled(main)\n    in div\n    in Styled(div)\n    in div\n    in Styled(div)\n    in o\n    in withRouter(o)\n    in s\n    in Unknown\n    in Connect(Component)\n    in Title[Connect(Component)]\n    in RouterContext\n    in Router\n    in p\n    in @mantine/core/MantineProvider\n    in h\n    in DragDropContextProvider\n    in I"
​
<prototype>: Object { … }
​​
__defineGetter__: function __defineGetter__()
​​
__defineSetter__: function __defineSetter__()
​​
__lookupGetter__: function __lookupGetter__()
​​
__lookupSetter__: function __lookupSetter__()
​​
__proto__: 
​​
constructor: function Object()
​​
hasOwnProperty: function hasOwnProperty()
​​
isPrototypeOf: function isPrototypeOf()
​​
propertyIsEnumerable: function propertyIsEnumerable()
​​
toLocaleString: function toLocaleString()
​​
toString: function toString()
​​
valueOf: function valueOf()
​​
<get __proto__()>: function __proto__()
​​
<set __proto__()>: function __proto__()
app.ts:22:10
`

Metabase server log: there doesn't seem to be anything out of the ordinary, but here goes:
`[3e3ae458-2ef8-458a-ada3-3f5b47595446] 2023-10-10T10:51:31+02:00 INFO metabase.server.middleware.exceptions Request canceled before finishing.
[3e3ae458-2ef8-458a-ada3-3f5b47595446] 2023-10-10T10:51:33+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 53.2 ms (6 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (4 idle, 0 queued) (147 total active threads) Queries in flight: 0 (0 queued)
[3e3ae458-2ef8-458a-ada3-3f5b47595446] 2023-10-10T10:51:33+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 63.9 ms (10 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (4 idle, 0 queued) (147 total active threads) Queries in flight: 0 (0 queued)
[3e3ae458-2ef8-458a-ada3-3f5b47595446] 2023-10-10T10:51:33+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 71.9 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (4 idle, 0 queued) (147 total active threads) Queries in flight: 0 (0 queued)
[3e3ae458-2ef8-458a-ada3-3f5b47595446] 2023-10-10T10:51:33+02:00 DEBUG metabase.server.middleware.log GET /api/collection 200 77.9 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (4 idle, 0 queued) (147 total active threads) Queries in flight: 0 (0 queued)`

### Information about your Metabase installation

```JSON
Metabase version 47.2
```

### Severity

This use case is relatively rare, which is why I only caught it now. But it does mean I can't create a specific question I need for a strategic dashboard. Besides, I am likely to need this function for some older SQL queries on the same dashboard. They're queries we would like to convert into editor questions for drill-through purposes, and they are very strategic for our business.

**Comment by paoliniluis** [comment]
Couldn't repro on 47.4 on Brave on Linux
