### ISSUE TITLE
BE - prevent users from removing audit collections and custom reports

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#34524]

**Comment by escherize** [comment]
After looking through this, I think it's already been handled by the `can-write?` implementations on [cards](https://github.com/metabase/metabase/blob/auditv2-main/src/metabase/models/card.clj#L65) and [dashboards](https://github.com/metabase/metabase/blob/auditv2-main/src/metabase/models/dashboard.clj#L55).

Going to close this, but please open it with a behavior that is possible that shouldn't be.
