### ISSUE TITLE
"Is not empty" filter generates wrong SQL query with string 

### ISSUE THREAD

**Issue by deusesx** [metabase/metabase#34530]
### Describe the bug

When I create Question and setting filter "Is not empty", Metabase generates SQL with wrong query. 
`SELECT "dm_table"."partners"."X_id" AS "X_id", 
FROM "dm_table"."partners"
WHERE ("dm_table"."partners"."X_id" IS NOT NULL
   AND ("dm_table"."partners"."X_id" <> ''
    OR "dm_table"."partners"."X_id" IS NULL))
LIMIT 1048575`

I expect:
`SELECT "dm_table"."partners"."X_id" AS "X_id", 
FROM "dm_table"."partners"
WHERE ("dm_table"."partners"."X_id" IS NOT NULL
   AND ("dm_table"."partners"."X_id" <> ''
    OR "dm_table"."partners"."X_id" IS NOT NULL))
LIMIT 1048575`

Instead IS NULL should be IS NOT NULL

### To Reproduce

1. Go to 'Question'
2. Make question on some table on PostgreSQL based mart
3. Add Filter Is not empty
4. Click Run
5. See empty result

### Expected behavior

5. See some data that has not null X_id field 

### Information about your Metabase installation

```JSON
self hosted  Metabase 0.44.5 Community Edition;
DB - DWS / Gauss DB (PostgreSQL 9.4 compatible)
```

### Severity

blocking many users who not operate with SQL

**Comment by paoliniluis** [comment]
please upgrade to the latest version
