### ISSUE TITLE
Switch database used for interactive models

### ISSUE THREAD

**Issue by MaxXor** [metabase/metabase#34541]
**Is your feature request related to a problem? Please describe.**
Lets say you have two databases: dev and prod. Both use the identical database layout / schema. Both databases are connected to Metabase. When you create a model using an SQL statement it's easily possible to swtich between dev and prod. When you use the interactive model editor it's not possible to switch the database (by choosing the same table in the first data source element of the interactive model editor) without completely resetting the joins, filters, etc. 

**Describe the solution you'd like**
An easy way to switch the database for a given interactively created model, just like with SQL-models. Maybe it would be enough to check if all tables used (for joins, etc.) are existing in both databases or try it at the users own risk.

**Describe alternatives you've considered**
Re-create the model by selecting the same table from the other database...

**How important is this feature to you?**
It would allow people with separate databases, but same schema, to use Metabase more efficient. :slightly_smiling_face:

**Comment by paoliniluis** [comment]
This is a duplicate

**Comment by MaxXor** [comment]
Sorry and thanks for letting me know. Do you have the link to the original issue?

**Comment by MaxXor** [comment]
@paoliniluis any suggestion? I really can't find the original issue and think its not a duplicate.

**Comment by MaxXor** [comment]
I found a workaround and simply converted the model back to a question, the question to a SQL question and in the last step to a model again. Now that the model is created using a SQL question instead of the interactive editor, it can be switched between prod and dev.
