### ISSUE TITLE
Alias Integer (Enum) Columns

### ISSUE THREAD

**Issue by jacobsmith** [metabase/metabase#3454]
I'm coming to Metabase from a Rails background, and enums are used fairly often there. i.e., a table may have:

`color: 0 | 1 | 2`

and the application code has

`enum color: %w{red green blue}`

I've been able to use the built in filters to say `WHERE color = 0`, but it would be awesome if in the metadata (or somewhere) I could give "hints" to the filter, so that it would be a drop down with "Red", "Blue", "Green".

I have a tiny bit of Java background, but if someone were to point me in the right direction for solving this, I'd love to try and submit a PR for it!

(Original Discourse discussion: https://discourse.metabase.com/t/is-there-a-way-to-alias-integer-enum-columns/736 )

**Comment by hugocar** [comment]
Hi
( I am not from the metabase staff)

Have you tried the segments in the data model admin panel ? 

Depending on your data, you could also create a view of some table with schema more adapted to OLAP queries.

**Comment by c2h5oh** [comment]
We could definitely use this feature, especially since Postgres enum support is broken - people having to use a printout with mappings doesn't provide the best experience.

/api/field/:fieldId/value_map_update and /api/field/:fieldId/values" both work (tested with curl) but there is no UI.
Aliases you set are ignored when when building segments / filters / questions and displaying data, but that again looks like just missing frontend bits.

**Comment by c2h5oh** [comment]
@camsaul how much work is required to have:
- ui for setting / viewing those aliases
- aliases being used in question builder and in answers

we're considering sponsoring this by either setting a bounty or investing our own time

I know that kind of estimation is wildly inaccurate, but an educated guess is better than nothing.

**Comment by camsaul** [comment]
@c2h5oh there needs to be some frontend work (such as pages to set the enum values) and backend work (such as new endpoints and possibly DB migrations) done here so it's not a trivial task. The elite developers that make up the core of the Metabase team (:wink:) could handle it but I think it might be a challenge for people not familiar with the Metabase codebase.

**Comment by salsakran** [comment]
supported via #5130
