### ISSUE TITLE
Snippets showed an input field on Public link

### ISSUE THREAD

**Issue by bhaswarasiwi** [metabase/metabase#34564]
### Describe the bug

Snippets showed an input field filter in the "Public link"

### To Reproduce

1. Go to the Metabase collection
2. Click on 'New' and choose 'SQL Query'
3. Open the 'SQL snippets' menu 
4. Insert a snippet in the SQL query
5. Save the SQL question
6. Click the 'sharing' icon at the right bottom of the page
7. turn on Enable sharing 
8. copy and paste the Public link into the new tab
9. you will see the 'Snippet:' input field filter 
10. add any value in the input field filter
11. You will see an error

### Expected behavior

Snippet should not mark as input variable in the public link

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "6.0.0-0.deb11.6-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-18",
      "tag": "v0.47.2",
      "branch": "release-x.47.x",
      "hash": "536c24c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

This confuses and annoys users who use public links

### Additional context

Screenshot: https://prnt.sc/TYmkbJ8BL7YO

**Comment by bpartridge** [comment]
Also seeing this exact issue on Cloud. Is there any chance that users seeing a Public Link can inject SQL this way?

Steps for a minimal reproduction visible in https://hvn.metabaseapp.com/public/question/c3d673ca-f93b-4598-8c52-423d9fd02a10

- create snippet named "test" with contents `'foo'`
- with sample database, create an SQL query with the query: `select {{snippet: test}} from ACCOUNTS limit 10;`
- share public link
- public link has a variable called Snippet: Test where arbitrary text can be typed in.

It seems that any text breaks the query, but even if that's not an injection risk, it makes the public link extremely confusing for users, and leaks the names of the snippets used, which may be sensitive.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-01",
      "tag": "v1.47.9",
      "branch": "?",
      "hash": "d05b06e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by bpartridge** [comment]
If this helps to triage or route the fix to the correct team:

It seems that in [the above](https://hvn.metabaseapp.com/public/question/c3d673ca-f93b-4598-8c52-423d9fd02a10), https://github.com/metabase/metabase/blob/master/frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx#L143 is rendering with the following parameters:

<img width="459" alt="Screenshot 2023-12-20 at 9 33 04 PM" src="https://github.com/metabase/metabase/assets/20748/9d932611-72dd-41d1-92be-ee8e861e9d3f">

**Comment by bpartridge** [comment]
Following up here after the holidays - this essentially makes public links that use SQL snippets feel extremely insecure, and is holding back adoption in our organization.

Should this be reprioritized different from the current tags @ranquild ? (Apologies if I'm doing something wrong by mentioning you!)

**Comment by ranquild** [comment]
@bpartridge I checked and for me public native questions with snippets throw errors in all cases. Does it happen on your side as well?

**Comment by ranquild** [comment]
https://github.com/metabase/metabase/issues/37270

**Comment by romeovs** [comment]
This issue has been fixed in 48.4. 
@bhaswarasiwi please update you Metabase installation and let us know if you run into any more problems.

**Comment by bpartridge** [comment]
Potentially significant rollout issue here: Our Metabase cloud instance is still running 1.48.3, and ALL our public links that use snippets, including the reproduction case linked above, now show "An error occurred." rather than any results. Which is strictly worse than the extra input field being shown!

Is it possible that frontend code was updated to the latest version but backend code was not, or vice versa?

For instance for that reproduction case, I can see https://hvn.metabaseapp.com/public/question/c3d673ca-f93b-4598-8c52-423d9fd02a10 making an AJAX call to `https://hvn.metabaseapp.com/api/public/card/c3d673ca-f93b-4598-8c52-423d9fd02a10/query?parameters=%5B%7B%22type%22%3A%22category%22%2C%22value%22%3Anull%2C%22id%22%3A%228ea13f8c-dc51-448c-812b-192bf0d55eb1%22%2C%22target%22%3A%5B%22variable%22%2C%5B%22template-tag%22%2C%22snippet%3A%20test%22%5D%5D%7D%5D` which is still trying to parameterize `snippet: test` - but that call fails with Internal Error Occurred.

Worried that this might be impacting other customers as well who haven't upgraded to 48.4, both on and off cloud. I'm not sure how to request an upgrade of our cloud instance to 48.4. Happy to stay on old version or new version, whatever is most helpful to try to troubleshoot any backports on our instance.

<details>
<summary>Metabase Diagnostics</summary>

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.205-195.804.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-11",
      "tag": "v1.48.3",
      "hash": "80d8323"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
</details>

**Comment by paoliniluis** [comment]
@bpartridge you ALWAYS need to contact us via the support email. I'll be upgrading your instance now, but please always contact us via email
