### ISSUE TITLE
Editing description for models do not work and markdown support is inconsistent

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#34574]
### Describe the bug

When viewing a model, you can click on "More info" to see the description. While it allows you to edit the description as well, it doesn't save. It does support markdown while editing, which is nice.

Now to edit the description, you have to click on Model details link first, and then edit the description there, which does work, however it doesn't render markdown. 

Now if you go back to the collection for the model, it also shows a description there where it removed markdown (no bold / links, but just plain text). I can understand the rationale here so it will always fit under the model name, especially if someone starts to add section titles, however removing bold/links removes the emphasize/extra info. 

### To Reproduce

1. Create model
2. Edit description when viewing model from "More info" with markdown. Save doesn't work while markdown does.
3. Go to Model details and do the same. Save does work while markdown doesn't render. 

### Expected behavior

Save should work and markdown rendering should be consistent

### Logs

n/a

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

A bit convenient having to go to model details or admin to edit description otherwise it's minor

**Comment by nemanjaglumac** [comment]
@maxzheng what do you mean when you say "it doesn't save"?
There's no save button. The value is committed on blur.

When I navigate away from the model and come back to it again, the description is preserved.
The issue with the model details not showing markdown preview is still there, though.

**Comment by maxzheng** [comment]
@nemanjaglumac Yep, looks like model description issue is fixed. The only thing remaining is the markdown behavior.

**Comment by nemanjaglumac** [comment]
That's being fixed in #45413.
Will merge and backport in a minute.
