### ISSUE TITLE
Specify intended usage of APGL license

### ISSUE THREAD

**Issue by cgebbe** [metabase/metabase#34610]
First of all thank you for making such an amazing product available open source.

According to [LICENSE.txt](https://github.com/metabase/metabase/blob/master/LICENSE.txt) most of the code is APGL licensed and according to [this comment](https://github.com/metabase/metabase/issues/7657#issuecomment-389949291) the ideas is to "power company's **internal** analytics" and that "For cases where you make money off of Metabase [...] we ask that you support the project by purchasing a commercial license", which sounds perfectly reasonable.

Would you be able to clarify this further by giving some examples? E.g.
- Write an external dashboard application "wrapping" metabase and sell it for profit -> enterprise
- Write an internal application which uses metabase -> enterprise?!
- Write an internal application which uses metabase and open-source the application as a non-profit organization -> open source

For example, [MongoDB states](https://www.mongodb.com/licensing/server-side-public-license/faq) that 
> What are the implications of this new license on applications built using MongoDB and made available as a service (SaaS)?
The copyleft condition of Section 13 of the SSPL applies only when you are offering the functionality of MongoDB, or modified versions of MongoDB, to third parties as a service. There is no copyleft condition for other SaaS applications that use MongoDB as a database.

I'd like to propose Metabase in our **for**-profit company for a small internal tool reaching ~10 users. I'm unsure whether we could open-source the combined application - maybe. Despite the very fair pricing conditions, the process of purchasing a license will take time and is not decided by me. Therefore, I'm wondering whether such a use case was meant to be allowed by you under the APGL license. Thank you in advance!

**Comment by paoliniluis** [comment]
You should ask these questions in the forum. Many customers embed the free product of Metabase without problem
