### ISSUE TITLE
Date Filter (Between) in mysql model not working. 

### ISSUE THREAD

**Issue by sajanlamsal** [metabase/metabase#34638]
**Describe the bug**
Applying a date filter (between) in a model gives unexpected results.  
<img width="1178" alt="AG_data__Filtered_by_last_login_at_is_between__2023-10-02__and__2023-10-13__·_Metabase" src="https://github.com/metabase/metabase/assets/16210881/e45d1486-09ad-4256-a320-0d7e4ca090c1">

<img width="1195" alt="AG_data__Filtered_by_last_login_at_is_between__2023-10-02__and__2023-10-13__·_Metabase-2" src="https://github.com/metabase/metabase/assets/16210881/381f3d72-ad40-4c7d-b7e4-01ca3796f491">

```sql
SELECT
pac.company_reg_id, pac.company_name, pa.agent_name, pa.email, ull.last_login_at, COUNT(*) AS login_count
FROM user_login_logs ull,
     pb_agent pa,
     pb_agent_company pac
WHERE 
   ull.user_type = 'agent'
  and pa.agent_id = ull.user_id
  and pa.company_id = pac.company_id
  and pa.is_agent = true
  and pac.test_status = 0
GROUP BY user_id
order by login_count desc;
```

## Applying the same filter in a custom query, and dates set from the variable works fine as it is returning 477 rows. 

<img width="1495" alt="tst_·_Metabase" src="https://github.com/metabase/metabase/assets/16210881/e094d37a-a784-48a1-80a4-95b9354d0d8b">

```sql
SELECT pac.company_reg_id, pac.company_name, pa.agent_name, pa.email, ull.last_login_at,
COUNT(pac.company_reg_id) AS login_count
FROM user_login_logs ull,
     pb_agent pa,
     pb_agent_company pac
WHERE 
  ull.user_type = 'agent'
[[  and ull.last_login_at between {{begin_date}} and {{end_date}}]]
  and pa.agent_id = ull.user_id
  and pa.company_id = pac.company_id
  and pa.is_agent = true
  and pac.test_status = 0
GROUP BY user_id
order by login_count desc;
```

**Logs**
no console error

**To Reproduce**
- add date filter in model, 
- compare the results with the native query

**Expected behavior**
data should be properly filtered between dates as in the native query

**Severity**
P1
- date filters are used for many reports, If this is not working properly we cannot trust the generated report. 

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "6.1.38-59.109.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.38-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-11",
      "tag": "v0.47.4",
      "branch": "?",
      "hash": "c96dc65"
    },
    "settings": {
      "report-timezone": "Asia/Tokyo"
    }
  }
}
```

**Comment by perivamsi** [comment]
@sajanlamsal is this still an issue? Are you still on 47.4?

**Comment by camsaul** [comment]
@sajanlamsal I'm confused by the SQL you posted for applying the filter on a model, it doesn't have any `WHERE` filters against `last_login_at` at all. Can you please post the query generated for the first example?

I'm wondering if this might be an issue with how we generate the date range. Can you breakout out by day and compare the count in the model versus the native query? I'm wondering if the model is missing results from a specific day like October 12th or October 13th
