### ISSUE TITLE
Data reference isn't accessible if an admin hasn't created a getting started guide

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3463]
In a new installation, I should still be able to get to all metrics, all segments and all tables even if an administrator hasn't created a getting started guide for that instance.

Right now, all I see is the below

![screen shot 2016-10-05 at 4 35 18 pm](https://cloud.githubusercontent.com/assets/107439/19135482/bbb84078-8b19-11e6-9dd0-f4917d4d2d7b.png)

**Comment by mazameli** [comment]
Yep, mentioned this to @kdoh the other day. Thanks for filing an issue for it.
