### ISSUE TITLE
404 when downloading results on embedded questions on sub-paths

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#34634]
### Describe the bug

embedded dashboards do work, but now questions are the ones that fail

related to https://github.com/metabase/metabase/issues/33244

### To Reproduce

1) run metabase on a sub path
2) create a question
3) embed it
4) try to download the results... you get a 404

see the URL on my local instance:
```https://localhost:8443/mbhttps://localhost:8443/mb/embed/question/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6NH0sInBhcmFtcyI6e30sImlhdCI6MTY5NzE0ODAxMywiX2VtYmVkZGluZ19wYXJhbXMiOnt9fQ.nSfqwLkdMgFfyQry_xjDIEpI98HyOZSwlxBh4mDo-w8.xlsx```

### Expected behavior

We should generate the right API calls

### Logs

NA

### Information about your Metabase installation

47.3 onwards

### Severity

P1

**Comment by iethree** [comment]
We need to figure out how to run our e2e suite on a subpath.
