### ISSUE TITLE
Manual schemas changes to FK keep getting overridden

### ISSUE THREAD

**Issue by seanadkinson** [metabase/metabase#3464]
Hi there, thanks for an incredible product so far (just discovered it yesterday, and spent all night configuring it).

I have an issue where the schema detection isn't picking up the destination of a certain composite FK.  I manually tell it what table the FK references in Admin, but that data gets overridden, seemingly at some interval/schedule.

The schema around this particular FK:

```
customer
----------
id int PK

program
---------
id int PK

customer_program
---------------------
customerId int FK references customer (id)
programId int FK references program (id)

enrollment
-----------
id int PK
customerId int
programId int
FK (customerId, programId) references customer_program (customerId, programId)
```

The `enrollment.customerId` and `enrollment.programId` columns are the FKs in question.

In this case, the `enrollment` table doesn't know what to do with `customerId` and `programId`, and has them setup in Admin as "Type: Foreign Key", but with no destination.  I can manually set the destination as `customer (id)` and `program (id)`, which works great.  However, after some time, this configuration gets reset back to not knowing what table the FK references, and any Questions I've created using this path get broken until I fix it again.

I'm not sure if it gets reset on some fixed schedule, or in response to some user action.  Does the database schema sync at regular times?  When manually triggering a Sync action, the FK loses its destination, so I assume that is what is going on, but I'm not sure.

Is there a way to permanently set up this FK to be configured correctly?

Here are the requested details:

Browser: Chrome 53
OS: Max OS X El Capitan
Database: MySQL 5.6
Metabase Version: 0.19.3
Hosting Env: Deployed on an AWS server using docker image
Metabase Internal Database: MySQL 5.6

**Comment by seanadkinson** [comment]
After reading [this blog post](http://www.metabase.com/blog/Joins), looks like I'll try to create a `VIEW` to do what I want.  I'll respond here if that works well, and maybe you can confirm that that would be the recommended approach.  Thanks again!

**Comment by salsakran** [comment]
@seanadkinson this sounds like a bug. We shouldn't ever be overwriting FKs you manually set.

There's a separate feature here which is our ability to support composite FKs which I've separated out into #3475

**Comment by camsaul** [comment]
@salsakran it looks like this bug only affects composite FKs, I've been unable to repro it with noncomposite FKs

**Comment by chamini2** [comment]
This is happening to us in Postgres
