### ISSUE TITLE
Allow to group by tuple ("Day of week", "Hour of day") => "Hour of week"

### ISSUE THREAD

**Issue by holtkamp** [metabase/metabase#3465]
(searched for existing feature requests, could not find any, so submitting a new issue)

Currently one can group date(time)-related information by:

![screen shot 2016-10-06 at 11 29 00](https://cloud.githubusercontent.com/assets/776405/19147520/cee75b44-8bb8-11e6-9e9a-0c223d3d20f9.png)

It would be nice to also allow to group by the tuple ("Day of week", "Hour of day"), maybe call it "Hour of week"?

The rationale is that we would like to plot which time of the day orders are placed, spread out over the week. Currently we can do that by day of the week, but a little more detail on what the peak **times** on each day are would be nice.

![screen shot 2016-10-06 at 11 56 27](https://cloud.githubusercontent.com/assets/776405/19148226/f801c692-8bbb-11e6-96bb-d4bb01b9897f.png)

**UPDATE: example**
This is the idea, currently done by transforming the "question" to SQL:
![screen shot 2016-10-06 at 12 11 59](https://cloud.githubusercontent.com/assets/776405/19305196/273398ba-9070-11e6-9820-6698917ccd45.png)
As you can see, valuable information can be derived from this: the peak is early in the morning.

**Comment by flamber** [comment]
Excellent idea, but instead of adding more options, then being able to breakout the same field multiple times would work.
Closing in favor of #4726, since it has a lot more upvotes and references.
