### ISSUE TITLE
In nested questions fields can be added multiple times to the grouping

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#34662]
### Describe the bug

In nested questions, it is possible to add a field multiple times to the grouping, when the field is a date/time or a numeric type.

### To Reproduce
Note that there is no need to create a native question, the error can also be reproduced starting from a question built via the query builder.

1. Create a native question (or a model): `select * from products`, save it, then Explore results
2. Click Summarize so that the sidebar opens
3. Add grouping: `CREATED_AT`:`Month`
4. The visualization changes accordingly
5. (!): in the field list the grouping field doesn't get highlighted as added
6. Add grouping again: `CREATED_AT`:`Month`
7. (!): the same grouping field can be added again

The `PRICE`:`Auto Binned` field can also be added multiple times.

The grouping field doesn't get higlighted, :
<img width="1126" alt="image" src="https://github.com/metabase/metabase/assets/11080638/8038d0e3-87f3-4178-8e0f-fca984ec725e">

and it can be added again:
<img width="1257" alt="image" src="https://github.com/metabase/metabase/assets/11080638/8c5e1c09-bec6-4b93-b578-350a2c8b5b59">

Fields added multiple times:
<img width="863" alt="image" src="https://github.com/metabase/metabase/assets/11080638/ab411010-a5bb-4081-8c54-6edb0293273b">

<img width="865" alt="image" src="https://github.com/metabase/metabase/assets/11080638/f2e1e5ca-ac93-4751-baa1-61dece5e5210">

### Expected behavior

Adding the same field multiple times should be prevented. It was prevented in 46.x .

### Logs

n/a

### Information about your Metabase installation

```JSON
- Metabase version: 1.47.4
```

### Severity

I found this accidentally while reproducing some other issue.

**Comment by lbrdnk** [comment]
Fixed by #33977 in master.
