### ISSUE TITLE
[MLv2] Joins cause duplicate column groups

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#34665]
It seems like MLv2 methods returning a list of columns can contain duplicates if a query has a certain join

### To reproduce

1. New > Question > Raw Data > Sample Database > Orders
2. Join Reviews on Orders.PRODUCT_ID = Reviews.PRODUCT_ID
3. Click "Pick a column to group by"
4. Inspect a list of column groups in the popover

**Expected:** Orders, Review, User, Product
**Actual:** Product shows up twice

**Demo**

![CleanShot 2023-10-13 at 18 04 07@2x](https://github.com/metabase/metabase/assets/17258145/94ad31ed-31ca-4d89-91e4-9cfbe734a63d)

**Comment by metamben** [comment]
The first Product groups results from `orders.product_id`, the second one from `reviews.product_id`. (Unfortunately, this cannot be seen from the display names.) Enabling more than one relationships was implemented for https://github.com/metabase/metabase/issues/33451. @kulyk please close the ticket if you are OK with the current behaviour.

**Comment by kulyk** [comment]
@metamben thanks for explaining! I'm going to close this in favor of #34735. Please feel free to edit the new one
