### ISSUE TITLE
Auto pivot is freezing query editor on high cardinality fields

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#34677]
### Describe the bug

In the query editor, when you group by 2 fields, it auto pivots the 2nd field as columns, which is neat (though not sure if it is really useful way of looking at the data most of the time when exploring). However, if both fields have high cardinality, the entire page freezes. I was trying to group by Customer ID and Name in our Account model to see which customer have multiple accounts (sorting counts in descending), but got a frozen page instead as it tries to render the pivoted table view. 

For my use case, pivot isn't useful at all, so if it did render, then I would need to go to settings to unpivot to see the highest count in order. 

### To Reproduce

1. Group by 2 fields with high cardinality (at least a few thousand each)
2. Query editor spins / UI is frozen until pivot view is rendered (or never if cardinality is too high). 

### Expected behavior

Auto pivot should only be done if cardinality is low (maybe under 100 or even lower?). Or not at all / only provide a hint/option to easily pivot

### Logs

n/a

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

Medium as the magic is causing more problem than it provides

**Comment by luizarakaki** [comment]
I believe we should pivot it only if the pivot column cardinality is less than or equal to 16
