### ISSUE TITLE
download excel result file error 

### ISSUE THREAD

**Issue by xqwbx163** [metabase/metabase#34682]
### Describe the bug

query  sql,
download excel file, open file show  error 
![image](https://github.com/metabase/metabase/assets/20455410/b9dd34cf-fa66-45cf-b706-1d4c567c5674)

### To Reproduce

![image](https://github.com/metabase/metabase/assets/20455410/fd2ea1eb-a7d3-4db9-aee4-ff2cc54ec6ab)

### Logs

{ "database_id" : 4,
"started_at" : "2023-10-16T10:16:16.531876462+08:00",
"via" :[{ "status" : "failed",
"class" : "class clojure.lang.ExceptionInfo",
"error" : "Cannot trackColumnForAutoSizing because autoSizeColumnTracker failed to initialize (possibly due to fonts not being installed in your OS)",
"stacktrace" :[ "--> query_processor.context.default$default_reducef$fn__60426.invoke(default.clj:60)",
"query_processor.context.default$default_reducef.invokeStatic(default.clj:57)",
"query_processor.context.default$default_reducef.invoke(default.clj:49)",
"query_processor.context$reducef.invokeStatic(context.clj:70)",
"query_processor.context$reducef.invoke(context.clj:63)",
"query_processor.context.default$default_runf$respond_STAR___60430.invoke(default.clj:69)",
"driver.sql_jdbc.execute$execute_reducible_query$fn__80997.invoke(execute.clj:689)",
"driver.sql_jdbc.execute$fn__80798$fn__80799.invoke(execute.clj:384)",
"driver.sql_jdbc.execute$fn__80766$do_with_resolved_connection__80767.invoke(execute.clj:334)",
"driver.sql_jdbc.execute$fn__80798.invokeStatic(execute.clj:378)",
"driver.sql_jdbc.execute$fn__80798.invoke(execute.clj:376)",
"driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:672)",
"driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:661)",
"driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:669)",
"driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:661)",
"driver.sql_jdbc$fn__115855.invokeStatic(sql_jdbc.clj:72)",
"driver.sql_jdbc$fn__115855.invoke(sql_jdbc.clj:70)",
"query_processor.context$executef.invokeStatic(context.clj:60)",
"query_processor.context$executef.invoke(context.clj:49)",
"query_processor.context.default$default_runf.invokeStatic(default.clj:68)",
"query_processor.context.default$default_runf.invoke(default.clj:66)",
"query_processor.context$runf.invokeStatic(context.clj:46)",
"query_processor.context$runf.invoke(context.clj:40)",
"query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)",
"query_processor.reducible$identity_qp.invoke(reducible.clj:12)",
"query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___77052.invoke(cache.clj:224)",
"query_processor.middleware.permissions$check_query_permissions$fn__72635.invoke(permissions.clj:126)",
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__76177.invoke(mbql_to_native.clj:24)",
"query_processor$fn__78285$combined_post_process__78290$combined_post_process_STAR___78291.invoke(query_processor.clj:260)",
"query_processor$fn__78285$combined_pre_process__78286$combined_pre_process_STAR___78287.invoke(query_processor.clj:257)",
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76963$fn__76968.invoke(resolve_database_and_driver.clj:36)",
"driver$do_with_driver.invokeStatic(driver.clj:93)",
"driver$do_with_driver.invoke(driver.clj:88)",
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76963.invoke(resolve_database_and_driver.clj:35)",
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__72945.invoke(fetch_source_query.clj:316)",
"query_processor.middleware.store$initialize_store$fn__73126$fn__73127.invoke(store.clj:12)",
"query_processor.store$do_with_store.invokeStatic(store.clj:56)",
"query_processor.store$do_with_store.invoke(store.clj:50)",
"query_processor.middleware.store$initialize_store$fn__73126.invoke(store.clj:11)",
"query_processor.middleware.normalize_query$normalize$fn__77259.invoke(normalize_query.clj:36)",
"query_processor.middleware.constraints$add_default_userland_constraints$fn__74653.invoke(constraints.clj:54)",
"query_processor.middleware.process_userland_query$process_userland_query$fn__77188.invoke(process_userland_query.clj:151)",
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__77585.invoke(catch_exceptions.clj:171)",
"query_processor.reducible$async_qp$qp_STAR___66802$thunk__66804.invoke(reducible.clj:103)",
"query_processor.reducible$async_qp$qp_STAR___66802$fn__66806.invoke(reducible.clj:108)" ],
"error_type" : "qp",
"ex-data" :{ "type" : "qp" }}],
"error_type" : "qp",
"json_query" :{ "constraints" : NULL,
"type" : "native",
"middleware" :{ "js-int-to-string?" : FALSE,
"ignore-cached-results?" : TRUE,
"process-viz-settings?" : TRUE,
"skip-results-metadata?" : TRUE,
"format-rows?" : FALSE },
"native" :{ "query" : "select dt,hr,table_name,indicator_type,unique_key,indicator_name,indicator_value,tmcreate \nfrom search_report.dws_monitor_indicator_result_all_metabase_hi \n-- where  table_name in ('dm_search.dwd_log_search_recommend_backend_show_hi')\nwhere  table_name in ('dm_search.fct_search_recommend_sid_item_hi','dm_search.fct_search_recommend_sid_hi')",
"template-tags" :{}},
"database" : 4,
"parameters" :[],
"async?" : TRUE,
"cache-ttl" : NULL },
"status" : "failed",
"class" : "class java.lang.IllegalStateException",
"stacktrace" :[ "org.apache.poi.xssf.streaming.SXSSFSheet.trackColumnForAutoSizing(SXSSFSheet.java:1447)",
"--> query_processor.streaming.xlsx$fn$reify__61247.begin_BANG_(xlsx.clj:507)",
"query_processor.streaming$streaming_rff$fn__61333$fn__61338.invoke(streaming.clj:117)",
"query_processor.middleware.process_userland_query$add_and_save_execution_info_xform_BANG_$execution_info_rf_STAR___77179.invoke(process_userland_query.clj:89)",
"query_processor.middleware.add_rows_truncated$add_rows_truncated_xform$fn__74821.invoke(add_rows_truncated.clj:24)",
"query_processor.reducible$combine_additional_reducing_fns$combine_additional_reducing_fns_rf_STAR___66825.invoke(reducible.clj:192)",
"query_processor.context.default$default_reducef$fn__60426.invoke(default.clj:58)",
"query_processor.context.default$default_reducef.invokeStatic(default.clj:57)",
"query_processor.context.default$default_reducef.invoke(default.clj:49)",
"query_processor.context$reducef.invokeStatic(context.clj:70)",
"query_processor.context$reducef.invoke(context.clj:63)",
"query_processor.context.default$default_runf$respond_STAR___60430.invoke(default.clj:69)",
"driver.sql_jdbc.execute$execute_reducible_query$fn__80997.invoke(execute.clj:689)",
"driver.sql_jdbc.execute$fn__80798$fn__80799.invoke(execute.clj:384)",
"driver.sql_jdbc.execute$fn__80766$do_with_resolved_connection__80767.invoke(execute.clj:334)",
"driver.sql_jdbc.execute$fn__80798.invokeStatic(execute.clj:378)",
"driver.sql_jdbc.execute$fn__80798.invoke(execute.clj:376)",
"driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:672)",
"driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:661)",
"driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:669)",
"driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:661)",
"driver.sql_jdbc$fn__115855.invokeStatic(sql_jdbc.clj:72)",
"driver.sql_jdbc$fn__115855.invoke(sql_jdbc.clj:70)",
"query_processor.context$executef.invokeStatic(context.clj:60)",
"query_processor.context$executef.invoke(context.clj:49)",
"query_processor.context.default$default_runf.invokeStatic(default.clj:68)",
"query_processor.context.default$default_runf.invoke(default.clj:66)",
"query_processor.context$runf.invokeStatic(context.clj:46)",
"query_processor.context$runf.invoke(context.clj:40)",
"query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)",
"query_processor.reducible$identity_qp.invoke(reducible.clj:12)",
"query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___77052.invoke(cache.clj:224)",
"query_processor.middleware.permissions$check_query_permissions$fn__72635.invoke(permissions.clj:126)",
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__76177.invoke(mbql_to_native.clj:24)",
"query_processor$fn__78285$combined_post_process__78290$combined_post_process_STAR___78291.invoke(query_processor.clj:260)",
"query_processor$fn__78285$combined_pre_process__78286$combined_pre_process_STAR___78287.invoke(query_processor.clj:257)",
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76963$fn__76968.invoke(resolve_database_and_driver.clj:36)",
"driver$do_with_driver.invokeStatic(driver.clj:93)",
"driver$do_with_driver.invoke(driver.clj:88)",
"query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76963.invoke(resolve_database_and_driver.clj:35)",
"query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__72945.invoke(fetch_source_query.clj:316)",
"query_processor.middleware.store$initialize_store$fn__73126$fn__73127.invoke(store.clj:12)",
"query_processor.store$do_with_store.invokeStatic(store.clj:56)",
"query_processor.store$do_with_store.invoke(store.clj:50)",
"query_processor.middleware.store$initialize_store$fn__73126.invoke(store.clj:11)",
"query_processor.middleware.normalize_query$normalize$fn__77259.invoke(normalize_query.clj:36)",
"query_processor.middleware.constraints$add_default_userland_constraints$fn__74653.invoke(constraints.clj:54)",
"query_processor.middleware.process_userland_query$process_userland_query$fn__77188.invoke(process_userland_query.clj:151)",
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__77585.invoke(catch_exceptions.clj:171)",
"query_processor.reducible$async_qp$qp_STAR___66802$thunk__66804.invoke(reducible.clj:103)",
"query_processor.reducible$async_qp$qp_STAR___66802$fn__66806.invoke(reducible.clj:108)" ],
"card_id" : 1066,
"context" : "xlsx-download",
"error" : "Cannot trackColumnForAutoSizing because autoSizeColumnTracker failed to initialize (possibly due to fonts not being installed in your OS)",
"row_count" : 0,
"running_time" : 0,
"data" :{ "rows" :[],
"cols" :[]}}

### Information about your Metabase installation

```JSON
metabase version :metabase 0.47.3  
os system :  centos 7.9
java version : jdk-18.0.2
```

### Severity

p2

**Comment by paoliniluis** [comment]
Please use Java 11 and install the packages needed for Metabase to work

**Comment by xqwbx163** [comment]
thanks for you help,  
replace java 18  to java 11 , run, it is ok.
