### ISSUE TITLE
Date filtering on time-series viz is not available when the second grouping field is not a category type

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#34690]
### Describe the bug

The date filter and granularity selector on time-series visualizations disappear when the non-time field is not a Category type.

### To Reproduce

1. Create a new question: Sample DB / Products / Summarize / Count
2. Add two groupings in the following order: 1. Created At:Month, 2. Category
3. The filter is displayed at the bottom of the chart
4. Save the question.
5. Go to table metadata, and set the column type for `Products.Category` to _No semantic type_
6. Go to the same question again
7. (!) The filter won't display this time.

Another way to demonstrate this using a custom column: 
1. Create a new question: Sample DB / Products / Summarize / Count
2. Add a custom column: expression: `case(endsWith([Category], "t"), "Foo", "Bar")`, name: `CustomCategory`
3. Add two groupings in the following order: 1. Created At:Month, 2. CustomCategory
4. Visualize
5. (!) The date filter doesn't appear

### Expected behavior

Considering the charts do display correctly I'd expect the filters to work too.

### Logs

n/a

### Information about your Metabase installation

```JSON
{
  "version": {
      "date": "2023-10-11",
      "tag": "v1.47.4",
      "branch": "?",
      "hash": "c96dc65"
  }
}
```

### Severity

P2, because this is quite unintuitive, even if often tthere is a workaround.

### Additional context

No display:
<img width="849" alt="image" src="https://github.com/metabase/metabase/assets/11080638/aa4efad6-07b9-4fb3-b3cd-b226808d007d">

**Comment by kamilmielnik** [comment]
Reproducible in 0.48.0.
Cannot reproduce on master at b09db3b450.
Cannot reproduce on `release-x.49.x`.
