### ISSUE TITLE
Duplicated lines in line plot in dashboard (but not in question)

### ISSUE THREAD

**Issue by PierreSnell** [metabase/metabase#34695]
### Describe the bug

When plotting lines as a question, the visualisation is perfect. 

![image](https://github.com/metabase/metabase/assets/116119917/6c8ddeae-0d69-48ee-8434-1ca66e035181)

Once that question in a dashboard, the lines get duplicated. 

![image](https://github.com/metabase/metabase/assets/116119917/8d2baa10-96de-4ea6-a8ba-9183ce9445de)

Here is the editor : 

![image](https://github.com/metabase/metabase/assets/116119917/b4c2d125-da2f-48d7-a293-4732b2484312)

### To Reproduce

1. Create a question
2. Embed it in a dashboard

(note that it's only for some of our questions not all of it.... I cannot figure a pattern though.. :/ )

### Expected behavior

Have the same visualisation in the dashboard than in the question

### Information about your Metabase installation

```JSON
- Browser : Firefox 118.0.2 (same problem with chrome 118.0.5993.70-1)
- OS: arch linux (kernel 6.5.7)
- database : Postgres 15
- Metabase : 0.47.4
- Hosting :machine on aws
```

### Severity

It's quite severe as we embed those charts in our public website.

**Comment by PierreSnell** [comment]
Thanks for the fast reply, it is much appreciated! 

Unfortunately no... On the same data, I also got the HeartRate / HeartRate variability which are totally fine (coming from the same DB, same table, just different fields) :  

![image](https://github.com/metabase/metabase/assets/116119917/5b17daf7-9d61-44ae-9adf-7054f8e77ba8)
![image](https://github.com/metabase/metabase/assets/116119917/4abd3831-1bd9-4d22-a75a-91eefe8b9de6)

Note that for the heart rate, for the "same day data" it's summing them instead of doing the average (but there are already issues opened for that, I don't mind it here
I also got the `"Activity Date" as an unaggregated field: if it has more than one value at a point on the x-axis, the values will be summed` to warn me :). But maybe the "Oxygen data" problem is related to that? 

Also, adding filters (specific user or specific date range, the problem still happens.)

**Comment by PierreSnell** [comment]
Also, the data is really duplicated (same values on hover on both lines) but the y-axis is labeled weirdly... 

![image](https://github.com/metabase/metabase/assets/116119917/e2cb661a-2492-4fa2-915a-0af70a18a6da)

**Comment by paoliniluis** [comment]
what do you see when you hover over the duplicate line?

**Comment by PierreSnell** [comment]
The plot above, with exactly the same "hover data" for both lines.

When "cropping" the data (select a window with the mouse), it brings up the question, and data visualization is fine.  Only the dashboard create two lines.

**Comment by paoliniluis** [comment]
I was referring to the line below

**Comment by paoliniluis** [comment]
BTW: can you provide some rows as an example?

**Comment by PierreSnell** [comment]
> I was referring to the line below

Sorry, I misunderstood, the line bellow is exactly the same : 
![image](https://github.com/metabase/metabase/assets/116119917/ae06a7ad-acfc-4788-9a2b-d6a136f246e6)

Here are some example rows : 
![image](https://github.com/metabase/metabase/assets/116119917/92507f5c-1c08-44ab-8ded-522e81948e76)

or in csv:

```csv
Activity Date,Device,Average of Avg Oxygen
2023-05-16,WITHINGS,98.22222137451172
2023-05-17,FITBIT,96.78500366210938
2023-05-17,GARMIN,96.96473936601119
2023-05-17,WITHINGS,98.54545593261719
2023-05-18,FITBIT,94.72280883789062
2023-05-18,GARMIN,95.112570699056
2023-05-18,TWINME,98.0
2023-05-19,FITBIT,93.07013702392578
2023-05-19,GARMIN,95.18085791847922
2023-05-19,TWINME,97.66666666666667
2023-05-20,FITBIT,96.57252756754558
2023-05-20,GARMIN,95.53549743652344
2023-05-20,TWINME,98.0
2023-05-21,FITBIT,95.72407829155357
2023-05-21,GARMIN,95.03651574941782
```

**Comment by paoliniluis** [comment]
can you provide the raw data for a few days? I'm not able to replicate

**Comment by PierreSnell** [comment]
I sent it on your email : paoliniluis@gmail.com

**Comment by paoliniluis** [comment]
As you sent me the aggregated data and not the raw data, I don't see the issue
![image](https://github.com/metabase/metabase/assets/1711649/c391a22f-f2bc-4863-be4a-c945c0698a3d)

**Comment by PierreSnell** [comment]
Yes, that's a mistake from my side... I resent you the correct data.

**Comment by paoliniluis** [comment]
Hi, not able to repro again
![image](https://github.com/metabase/metabase/assets/1711649/e37ce74e-06b4-42b0-a49c-83db9b9fbab5)


Please post the DDL of the table, mine is
create table public.biometric_202310170939 (
  id integer,
  user_id text,
  activity_date timestamp without time zone,
  received_date timestamp without time zone,
  device text,
  device_id text,
  avg_heart_rate integer,
  heart_rate_variability integer,
  step_value integer,
  avg_respirations integer,
  avg_oxygen integer,
  avg_temperature numeric
);



also, please post what you see in the table metadata original schema
![image](https://github.com/metabase/metabase/assets/1711649/4c54c47e-a720-47fa-a0e6-18e3732f0362)

**Comment by PierreSnell** [comment]
Thanks to have tried to replicate. 
I will try to modify columns types, if you're not able to replicate, it seems it comes from my schema then. 

Here is the DDL : 
```
id serial4 NOT NULL,
user_id varchar(255) NOT NULL,
activity_date timestamp NOT NULL,
received_date timestamp NOT NULL,
device varchar(255) NOT NULL,
device_id varchar(255) NULL,
avg_heart_rate float4 NULL,
heart_rate_variability float4 NULL,
step_value float4 NULL,
avg_respirations float4 NULL,
avg_oxygen float4 NULL,
avg_temperature float4 NULL,
... (plus many constraints like heart_rate > 0, heart_rate < 150 etc etc)
```
Here is the Table Orignal metadata. 
![image](https://github.com/metabase/metabase/assets/116119917/91bc8e10-899a-41b4-a9f0-0a7cbe6c9d65)
