### ISSUE TITLE
All cards in dashboards are greyed-out 

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3470]
I upgraded to the 0.20 branch.
When I change to a new dashboard using the task switcher all the cards are greyed out. (like if the filter wasnt applied)

I see this in the console.
selectors.js:89 Uncaught TypeError: Cannot read property 'ordered_cards' of undefined

If i reload the dashboards it works as expected or when i access the first dashboard after a refresh. The problem only appears when I switch to another dashboard.

------
Version is the release/0.20 branch.
Chrome on OSX. 
All databases affected.
Metabase on SQL

**Comment by mazameli** [comment]
In my attempts to reproduce, this appears to be happening only for dashboards that have filters. Can you confirm this, moumny?

**Comment by tlrobinson** [comment]
Fixed by #3478
