### ISSUE TITLE
Log function trying to calculate `log{input}(10)` instead of `log10(input)` in BigQuery

### ISSUE THREAD

**Issue by martin-raisely** [metabase/metabase#34719]
### Describe the bug

[Metabase log function](https://www.metabase.com/docs/latest/questions/query-builder/expressions-list#log) puts the user input in the second argument (e.g. `log(10, source.events) AS log_events`) so it is calculating `log{input}(10)` instead of `log10(input)`.

[BigQuery `log` documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#log) is clear the second argument is the base.

> LOG(X [, Y])
> Description
> If only X is present, LOG is a synonym of LN. If Y is also present, LOG computes the logarithm of X to base Y.

This leads to errors in BigQuery (e.g. can't have `1` in data).

### To Reproduce

1. Create a question that uses the Metabase log function on data that is in BigQuery
2. Click "View the SQL"
3. Observe that input has been put as the second argument to log `log(10, source.events) AS log_events`
4. If input data contains the number `1` you will get an error like the following:

```
400 Bad Request
POST https://www.googleapis.com/bigquery/v2/projects/raisely-data/queries
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Floating point error in function: LOG(10, 1)",
      "reason": "invalidQuery"
    }
  ],
  "message": "Floating point error in function: LOG(10, 1)",
  "status": "INVALID_ARGUMENT"
}
```

### Expected behavior

Input data should be in the first argument for `log` in bigquery

### Logs

- 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.186+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-18",
      "tag": "v0.47.2",
      "branch": "release-x.47.x",
      "hash": "536c24c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

This is annoying. It has big implications for a lot of data analysis

### Additional context

![image](https://github.com/metabase/metabase/assets/105570704/d88cdf41-9e44-4175-8990-fbdc8a225c4d)

```
SELECT
  `source`.`campaign_uuid` AS `campaign_uuid`,
  `source`.`events` AS `events`,
  `source`.`log_events` AS `log_events`
FROM
  (
    SELECT
      `source`.`campaign_uuid` AS `campaign_uuid`,
      `source`.`events` AS `events`,
      log(10, `source`.`events`) AS `log_events`
    FROM
      (
        SELECT
          `warehouse.telemetry_donation_events`.`campaign_uuid` AS `campaign_uuid`,
          count(*) AS `events`
        FROM
          `warehouse.telemetry_donation_events`
       
WHERE
          `warehouse.telemetry_donation_events`.`event_stage` = 'Details'
       
GROUP BY
          `campaign_uuid`
       
ORDER BY
          `campaign_uuid` ASC
      ) `source`
  ) `source`

```

**Comment by paoliniluis** [comment]
Interestingly, the code says exactly that https://github.com/metabase/metabase/blob/87fd1e76d3bd803c7482ba3dd757d2a542f06554/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj#L834

**Comment by paoliniluis** [comment]
I just tested this and I get a correct output (bigquery census dataset)
![image](https://github.com/metabase/metabase/assets/1711649/cd49faa5-4a1c-4304-91bb-d97d8bb69ed8)

**Comment by paoliniluis** [comment]
tested again and I still get the correct output 
![image](https://github.com/metabase/metabase/assets/1711649/2a0f0cf5-2733-4b2e-8117-cc2c9d569280)

**Comment by paoliniluis** [comment]
forget it, it was fixed in https://github.com/metabase/metabase/pull/34609, I'll check if we can backport it

**Comment by martin-raisely** [comment]
Incredibly responsive support @paoliniluis!!!
