### ISSUE TITLE
[MLv2] BE - Add `is_segment_filter` API

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#34714]
Currently, we rely on some hacks to differentiate three different filter types that need different UI
- column filter
- segment filter
- custom filter

we should just have some methods that can tell us this instead of relying on this: 

```ts
export function isSegmentFilter(
  query: Query,
  stageIndex: number,
  filter: FilterClause,
) {
  // This is a hack, we should get a real API method for is_segment
  return (
    !filterParts(query, stageIndex, filter) &&
    displayInfo(query, stageIndex, filter)?.name !== "nil"
  );
}
```

**Comment by kulyk** [comment]
@iethree `isSegmentFilter` looks good to me. As for `isCustomFilter`, I'm afraid it'd require duplicating our expression parsing logic on the BE. We had a discussion about where this logic should live, and the FE is in favor right now. Could we keep `isCustomFilter` on the FE for now and exclude it from the issue, please?

**Comment by iethree** [comment]
oh, nevermind, I think I figured out a good way to do this with `expression_parts` !
