### ISSUE TITLE
Using Field Filters and editing query results in schema error

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#34729]
### Describe the bug

If you try to execute a native query with a field filter after editing the query text it will result in an error in the response to POST /api/dataset:

```"error": "Invalid input: {:native {:template-tags {\"text\" {:options [\"invalid type\"]}}}}"```

Inspecting the request payload, we can see `options` has a null value:

![image](https://github.com/metabase/metabase/assets/39073188/281f77a4-0230-44c1-afc9-6f662e3c9830)

The full ex-data is attached in the "Logs" section below.

### To Reproduce

1. Create a native query with a field filter:
```
select * from orders where  {{ id }}
```
2. In the variables sidebar, select "Variable Type" > "Field Filter", and "Field to map to" > Orders > ID, and Filter widget type: "ID"
3. Select a value for the filter.
4. Execute the query. Observe the results are returned as expected.
5. Edit the query text by adding or deleting whitespace.
6. Execute the query. Observe the error in the network tab, in the response to POST /api/dataset.

<img width="499" alt="image" src="https://github.com/metabase/metabase/assets/39073188/e5d255d7-e017-4758-8324-d6967af4f6a5">

The `option=null` and `default=null` entries were not present in the first POST /api/dataset response on step 4.

### Expected behavior

the query should work

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-LTS",
    "os.name": "Mac OS X",
    "os.version": "12.5.1",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.5 (Homebrew)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-10-19",
      "tag": "v0.48.0-SNAPSHOT",
      "hash": "8f8ab29"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

high, breaks field filters

**Comment by calherries** [comment]
The commit where the spec was written works (`18c1b1984e`), so this is not a backend issue. This is the template tag in the request payload at `18c1b1984e`. It doesn't have option=null.

![image](https://github.com/metabase/metabase/assets/39073188/3a0f9998-9f51-435a-86f4-6dcc6a9b1cdf)

**Comment by calherries** [comment]
I nailed this down to how the `extract-template-tags` function coerces its `existing-tags` argument.

If you call `extract-template-tags`, if the `existing-tags` argument is a JS object that doesn't have `options` or `default` keys then it will return an object with `options=null` and `default=null`.

Here's a diff I used to console.log how the argument changes from the caller of `ML.extract_template_tags` in javascript vs inside the body of the `extract-template-tags` function in CLJS.
```
diff --git a/frontend/src/metabase-lib/queries/NativeQuery.ts b/frontend/src/metabase-lib/queries/NativeQuery.ts
index fc342b6b78..e6833a6af8 100644
--- a/frontend/src/metabase-lib/queries/NativeQuery.ts
+++ b/frontend/src/metabase-lib/queries/NativeQuery.ts
@@ -437,6 +437,7 @@ export default class NativeQuery extends AtomicQuery {
    * special handling for NATIVE cards to automatically detect parameters ... {{varname}}
    */
   private _getUpdatedTemplateTags(queryText: string): TemplateTags {
+    console.log("_getUpdatedTemplateTags", JSON.parse(JSON.stringify(this.templateTagsMap())));
     return queryText && this.supportsNativeParameters()
       ? ML.extract_template_tags(queryText, this.templateTagsMap())
       : {};
diff --git a/src/metabase/lib/native.cljc b/src/metabase/lib/native.cljc
index 4a2d5e322e..9822371bb2 100644
--- a/src/metabase/lib/native.cljc
+++ b/src/metabase/lib/native.cljc
@@ -105,6 +105,7 @@
    (extract-template-tags query-text nil))
   ([query-text    :- ::common/non-blank-string
     existing-tags :- [:maybe ::lib.schema.template-tag/template-tag-map]]
+   (js/console.log "extract-template-tags" existing-tags)
    (let [query-tag-names    (not-empty (recognize-template-tags query-text))
          existing-tag-names (not-empty (set (keys existing-tags)))]
      (if (or query-tag-names existing-tag-names)
```

With the resulting diff and following the reproduction steps above, you get this printed out to the console:

<img width="562" alt="Screen Shot 2023-10-17 at 6 45 28 PM" src="https://github.com/metabase/metabase/assets/39073188/1bfbc139-4658-4f46-8508-0d2386cd399d">

**Comment by metamben** [comment]
@calherries what version of `master` were you at when you saw this error? I tried `master` at `6e669a90e0` but couldn't reproduce the issue. The metabase installation info you posted contains `"v0.47.1-SNAPSHOT"`, but in the description you say you are getting the error on `master`.

**Comment by calherries** [comment]
@metamben Sorry for the confusion, I just realised that version information is generated by `bin/build.sh`, which I don't execute whenever I switch branches unless I have to. I was indeed running this on master though. 
I've just recorded a loom to help you reproduce, but I followed the steps exactly:
https://www.loom.com/share/0ef4650091714080bca17db441451ef9?sid=5958f8a8-fb27-46a4-ad0a-55b09af6cdc8
