### ISSUE TITLE
Update dashboard performance 48

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#34721]
We've noticed the performance of updating a dashboard has been much slower recently, it took ~3 seconds to save a dashboard on our stats([slack thread](https://metaboat.slack.com/archives/C01MS7DQKR6/p1697454979662699))

This issue is used to track and report findings.

**Comment by qnkhuat** [comment]
Some initial benchmarks between master and 0.47.4.
when adding 2 cards to an empty dashboard
0.47.4:
- `PUT /api/dashboard/:id` reports 11 DB calls
- `PUT /api/dashboard/cards` report 19 DB calls

master
- `PUT /api/dashboard/:id` reports 20 DB calls
- `PUT /api/dashboard/cards` report 36 DB calls

I think most of this is largely because we overhauled the event system to be synchronous, it was async in 47([PR](https://github.com/metabase/metabase/pull/33392)).

need to do a bit more thorough testing to get the actual timing

**Comment by camsaul** [comment]
Posted my thoughts on this here https://metaboat.slack.com/archives/CKZEMT1MJ/p1697653826005819?thread_ts=1697604232.592589&cid=CKZEMT1MJ
