### ISSUE TITLE
Error when trying to save a new getting started guide

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3472]
I tried creating a new GSG and got this error: `Cannot read property '8' of null`

I tried creating it again, and this time didn't get an error, but instead am taken back to the empty state version of the GSG.

**Comment by tlrobinson** [comment]
@mazameli Do you know how to reproduce this, or can you provide a stack trace with line numbers for that error?

**Comment by tlrobinson** [comment]
Fixed by #3487
