### ISSUE TITLE
[MLv2] - display-info does not return a displayName for a group in a multistage query

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#34745]
Create a question like this:
![image](https://github.com/metabase/metabase/assets/1328979/d38033a6-649e-42e1-9561-79a780c0fdbf)

- After creating groups using `Lib.groupColumns`, and passing the group to `displayInfo`, the group will not have a display name.

**Comment by snoe** [comment]
We decided in [30108](https://github.com/metabase/metabase/issues/30108) ([thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1681401675221809)) that groups shouldn't have a blank name.

It could be that there's more nuance needed for some cases, but in this Epic we are ok without a name,
