### ISSUE TITLE
[MLv2] - A question joined on itself can cause FK columns to be displayed twice

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#34742]
Steps to reproduce: 
- Create a question and save it (orders table, for example). We will call this Question A.
- Create a new question, with a source of Question A, and join Question A on the ID column

`lib.visibleColumns` returns any columns accessible by foreign keys twice (sometimes).

Loom with more details [here](https://www.loom.com/share/dc79afe8449d4d2d88011dea8eb8ce43)

**Comment by metamben** [comment]
I think returning those columns twice is right. Inconsistency is bad, of course. Not being able to distinguish the "duplicate" columns is not nice (at least).

**Comment by bshepherdson** [comment]
I agree, the columns should be there twice. The paths to implicitly join them are distinct, and they're only dupes because it's the same row joined twice.

If we were joining the two tables on some other key, (say, parent_id), then child -> orders is not the same as parent -> orders.

**Comment by npfitz** [comment]
I see where you're coming from, but it does make things rather unfortunate on my end haha. If we're going to stick with returning them twice, do you think we could update them so that `Lib.groupColumns` can distinguish between them?
