### ISSUE TITLE
Frontend Performance when Adding and Removing Columns in Table Visualization

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#34759]
### Describe the bug

Please reclassify this as something else if it’s not a bug. 
This is more of a question about expected performance when having several dozen columns in a table and attempting to add and remove columns within Table visualization.

<img width="305" alt="Screenshot 2023-10-17 at 2 46 26 PM" src="https://github.com/metabase/metabase/assets/17398657/76aee6c6-96cc-4730-80b4-c11c08d93b14">

### To Reproduce

I initially tested using a schema with a mix of JSON and non-JSON data types from a postgres backend that when unpacked would produce 120+ columns. Adding and removing columns would take 2 - 2.5 seconds from click to the time animation was complete.
The amount of rows didn’t seem to matter as much but there were between 5,000 - 10,000. 
I’m also able to reproduce using the Sample database and joining several tables until I had a Question with dozens of columns. 

**20 columns** 
<img width="520" alt="perf_profile_20_columns" src="https://github.com/metabase/metabase/assets/17398657/600c794f-f8db-4d1d-a78c-b678d244d25b">

<br>
<br>
 
**40 columns**
<img width="441" alt="perf_profile_40_columns" src="https://github.com/metabase/metabase/assets/17398657/84d2f411-f42d-4f68-97dd-d66e4e3ab176">

<br>
<br>

**90 columns**
<img width="834" alt="perf_profile_90_columns" src="https://github.com/metabase/metabase/assets/17398657/71fa8464-27a3-4c03-b636-46c9ddca61b3">

<br>
<br>
 
**120 columns**
<img width="830" alt="perf_profile_120_columns" src="https://github.com/metabase/metabase/assets/17398657/1290f512-bc07-417d-9ff2-83aa8812cbfe">

<br>
<br>

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "20.0.2+9-78",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "20.0.2",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "20.0.2+9-78",
    "os.name": "Mac OS X",
    "os.version": "13.5.1",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "tag": "vLOCAL_DEV",
      "hash": "06d1ba2ae111e66253209c01c244d6379acfc6dcb1911fa9ab6012cec9ce52e5",
      "branch": "local"
    },
    "settings": {
      "report-timezone": null
    }
  }
}


This was also tested in This was tested in both 1.47.2
```

### Severity

Becomes a performance issue based on the amount of columns that can be generated by utilizing unpacked JSON

**Comment by paoliniluis** [comment]
great debugging

**Comment by iethree** [comment]
related: https://github.com/metabase/metabase/pull/34087

**Comment by npfitz** [comment]
I should improve with https://github.com/metabase/metabase/pull/35057, but I believe there is a second piece to this. For every cell that's rendered, we check and see if it should be clickable. Currently this is done by computing the list of drills and checking that the length is > 1. @bshepherdson's PR above will make that check go much much quicker, so this should speed up performance

The other thing that's happening (and why this scales with the number of columns) is we also check that cells are clickable when rendering a few rows (10) to measure column width. So, the fairly slow action is computed 10 x `number of columns`, which I believe is unnecessary. We should be able to default the value of `isClickable` when measuring column widths. I'll put up a PR that makes that change.

**Comment by npfitz** [comment]
Since merging https://github.com/metabase/metabase/issues/33841 and https://github.com/metabase/metabase/pull/35148, the impact of this should be greatly reduced. Clicking that eye now just hides the column rather than remove it from the query, and computing fewer drills has a massive impact on rendering time. We do still compute the drills in the header when measuring, that could shave a couple hundred ms off the call (depending on the size of the table), but I'm going to lower close this out as being fixed by PR 35148
