### ISSUE TITLE
Snowplow: Track dashboard save event

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#34751]
## Context
[Analytics spec](https://www.notion.so/metabase/Dashboard-saved-b3bb8eb78bd04c2f82b2ec9ecd236db9?pvs=4)

## Notes
- I figure we can track this on the client but open to feedback there.
- We already track a 'dashboard created' event so we could consolidate, but my assumption is that having this as a distinct event will be easier at this point, since it has unique properties.

Conversation that prompted this in [Slack](https://metaboat.slack.com/archives/C057T1QTB3L/p1697486450725169).

**Comment by ranquild** [comment]
@calherries could you take a look?

**Comment by calherries** [comment]
Yes, will get it done tomorrow

**Comment by calherries** [comment]
@cdeweyx this was shipped as spec'd. It'll be in 48
