### ISSUE TITLE
Error:   Output of edit-information-for-user does not match schema: \n\n\t   {:email (not (instance? java.lang.String a-org.postgresql.util.PGobject

### ISSUE THREAD

**Issue by bamboowonder** [metabase/metabase#34766]
**Describe the bug**
When trying to save a view, or save anything really, this error is thrown.

**Logs**

[java.lang.Thread run "Thread.java" 829]],
 :cause
 "Output of edit-information-for-user does not match schema: \n\n\t   {:email (not (instance? java.lang.String a-org.postgresql.util.PGobject))}  \n\n",
 :data
 {:type :schema.core/error,
  :schema
  {:timestamp (maybe Any),
   :id (maybe (constrained Int "Integer greater than zero")),
   :first_name (maybe Str),
   :last_name (maybe Str),
   :email (maybe Str)},
  :value
  {:timestamp #clj-time/date-time "2023-10-17T21:47:13.835Z",
   :id 1,
   :first_name "David",
   :last_name "xx",
   :email #object[org.postgresql.util.PGobject 0x686d9349 "xx@xx.com"]},
  :error {:email (not (instance? java.lang.String a-org.postgresql.util.PGobject))}},
 :message
 "Output of edit-information-for-user does not match schema: \n\n\t   {:email (not (instance? java.lang.String a-org.postgresql.util.PGobject))}  \n\n",
 :value
 {:timestamp #clj-time/date-time "2023-10-17T21:47:13.835Z",
  :id 1,
  :first_name "David",
  :last_name "xx",
  :email #object[org.postgresql.util.PGobject 0x686d9349 "xx@xx.com"]},
 :error {:email (not (instance? java.lang.String a-org.postgresql.util.PGobject))}}

**To Reproduce**
change any db or model view and attempt to save.

**Expected behavior**
Be able to Save anything.

**Severity**
We can't use Metabase at all while this bug is stopping us from saving.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1-post-Ubuntu-0ubuntu120.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1-post-Ubuntu-0ubuntu120.04",
    "os.name": "Linux",
    "os.version": "5.4.0-164-generic",
    "user.language": "en",
    "user.timezone": "America/Vancouver"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3 (Ubuntu 15.3-1.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-11",
      "tag": "v0.47.4",
      "branch": "?",
      "hash": "c96dc65"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by bamboowonder** [comment]
bump :)

**Comment by paoliniluis** [comment]
Did you redact the email of the user? seems like the error is there but I'm trying to reproduce

**Comment by bamboowonder** [comment]
Yes, I redacted the email of the user (myself).
I finally gave up and truncated all the metabase system tables and
restarted metabase to reseed them from scratch.
We've had metabase going for a few years now and I figure things must have
just been bogged down from historical cruft in there.
But that fixed the issue and now the error is no longer showing.   But the
downside is I've had to go through and recreate everything from scratch.
 Which is a pain, but way less than the system being unusable for everyone
here.
Cheers

**Comment by paoliniluis** [comment]
The error was only in the core_user table

**Comment by MyckeTap** [comment]
Hello guys, do we have something on that case?

**Comment by qwef** [comment]
It seems like the schema requires a string, and I'm guessing the view this schema is no longer upheld? Could you provide more details on the schema and what your changing it to?

**Comment by bamboowonder** [comment]
@MyckeTap  I bet that was the issue.   I recently had moved/change the citext extension between schemas.   I should have been more careful, but I didn't connect the two events as they happened a few days apart, and only after a restart of metabase.
