### ISSUE TITLE
Setting all reports to hide with no results breaks dashboard subscription

### ISSUE THREAD

**Issue by Tlrowan90** [metabase/metabase#34777]
### Describe the bug

I have dashboards that contain exception reporting per data field, in an ideal scenario we want Metabase to send notifications to a channel that show any reporting results if there is any apparent and only the report information where there is results. 

Currently we can send dashboard notifications with the switch for 'don't send if no results' on, which works well except when one of the e.g. 30 reports has results the notification appears with all 30 reports information, not just for the one that has results. 

I tried to use the new hide the report visualization functionality set on for all the reports to see if this would hide them, but instead must cause some kind of error as the the notification doesn't appear with the dashboard notification switch for 'don't send if no results' on and if that is off then appears with no report results even if a report has results. 

### To Reproduce

1. Create Dashboard with multiple reports, designed not to show results.
2. Purposely have one report that shows results vs one that doesn't.
3. Set visualization option to hide reports if no results in dashboard.
4. Create/Send dashboard subscription notification to Slack one with 'don't send if no results' on and one off. 

### Expected behavior

Dashboard Subscription Notification appears with only reports with results included

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "4.14.326-245.539.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "snowflake",
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.19"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-18",
      "tag": "v1.47.2",
      "branch": "release-x.47.x",
      "hash": "536c24c"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

Blocking use of Metabase as quality adherence tool

**Comment by markbastian** [comment]
To restate, you have a dashboard with N cards (N > 0), some of which have results and others that do not. The number with results we'll call R.

- If "Don't send if there aren't results" is on:
  - No results are sent when R = 0
  - When R > 0, we currently get N results -- We see every card
- We want R results -- We only want to see cards with results
