### ISSUE TITLE
You cannot log in to the metabase website through a third-party website

### ISSUE THREAD

**Issue by Jack-Cai-1998** [metabase/metabase#34773]
### Describe the bug

Sorry to bother you. I nested the deployed metabase website into my own website through iframe. Why can't I set cookies and carry cookies when I log in

### Information about your Metabase installation

```JSON
Follow the official website to launch directly locally
```

### Severity

Completely block me from using the metadata

```[tasklist]
### Tasks
```

**Comment by Tony-metabase** [comment]
Hi @Jack-Cai-1998 you haven't provided any details of your issue or what you are experiencing. IF you are not able to provide replication steps with additional information do not open these kind of issues in github.

I would recommend moving this question to https://discourse.metabase.com/ ... Also provide details of error and screenshots of what you are experiencing ... Also mention what type of embedding you are doing
