### ISSUE TITLE
MongoDB query timeout after 10min

### ISSUE THREAD

**Issue by yog27ray** [metabase/metabase#34782]
### Describe the bug

I am using MongoDB atlas as a database. By default, the MongoDB server has a [cursorTimeoutMil](https://www.mongodb.com/docs/upcoming/reference/parameters/#mongodb-parameter-param.cursorTimeoutMillis) of 600000 i.e. 10minutes. So any query that is taking more than 10 minutes gives a timeout error. I know Metabase doesn't have any timeouts, but as Mongodb documentation [noCursorTimout()](https://www.mongodb.com/docs/manual/reference/method/cursor.noCursorTimeout/) can be used to avoid this 10min timout. So is there some way to set `noCursorTimout`

### To Reproduce

Create any aggregation query on metabase DB that takes more than 10minutes.

### Logs

[f3aee9de-ec89-429e-aa5c-9628eff37147] 2023-10-18T16:33:10+05:30 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: PlanExecutor error during aggregation :: caused by :: operation exceeded time limit
{:database_id 2,
 :started_at #t "2023-10-18T10:43:10.232862Z[GMT]",
 :json_query
 {:database 2,
  :native
  {:template-tags
   {:start
    {:type "date", :name "start", :id "7db72ccb-6a2a-4a08-ba5b-00dddc6e334d", :display-name "Start", :required true},
    :end {:type "date", :name "end", :id "5be3dc65-9079-4f50-a8d3-f71992c598d6", :display-name "End", :required true}},
   :query
   "[\n    { \"$match\": { \"effectiveFollowUpDate\": { \"$gte\": {{start}}, \"$lte\": {{end}} } } },\n    {\n        \"$project\": {\n            \"week\": { \"$dateToString\": { \"date\": \"$effectiveFollowUpDate\", \"format\": \"%U\" } },\n            \"time\": \"$_created_at\",\n            \"regimens\": {\n                \"$map\": {\n                    \"input\": \"$regimens\",\n                    \"as\": \"item\"\n                    \"in\": { \"$concat\": [ \"Regimen$\", \"$$item.objectId\" ] }\n               }\n            }\n        }\n    },\n    { \"$unwind\": { \"path\": \"$regimens\", \"preserveNullAndEmptyArrays\": true } },\n    { \"$addFields\": { \"regimens\": { \"$ifNull\": [ \"$regimens\", \"\"] } } },\n    {\n        \"$lookup\": {\n            \"from\": \"RegimenHistory\",\n            \"let\": { \"regimenId\": \"$regimens\", \"time\": \"$time\" },\n            \"pipeline\": [\n                { \"$match\": { \"$expr\": { \"$eq\": [\"$_p_regimen\", \"$$regimenId\"] } } },\n                { \"$match\": { \"$expr\": { \"$lte\": [\"$_created_at\", \"$$time\"] } } },\n                { \"$group\": { \"_id\": 1, \"activeFrom\": { \"$min\": \"$_created_at\" } } },\n            ],\n            \"as\": \"lastActiveTime\",\n        }\n    },\n    { \"$unwind\": { \"path\": \"$lastActiveTime\", \"preserveNullAndEmptyArrays\": true } },\n    { \"$project\": { \"week\": 1, \"weekDiff\": { \"$divide\":[ { \"$subtract\": [\"$time\", { \"$ifNull\": [\"$lastActiveTime.activeFrom\", \"$time\"] }] }, 604800000] } } },\n    { \"$group\": { \"_id\": \"$_id\", \"week\": { \"$first\": \"$week\" }, \"weekDiff\": { \"$min\": \"$weekDiff\" } } },\n    {\n        \"$group\": {\n            \"_id\": \"$week\",\n            \"lessThan2Week\": { \"$sum\": { \"$cond\": [{ \"$lte\": [\"$weekDiff\", 2] }, 1, 0] } },\n            \"2-6Week\": { \"$sum\": { \"$cond\": [{ \"$and\": [{ \"$gt\": [\"$weekDiff\", 2] }, { \"$lte\": [\"$weekDiff\", 6] }] }, 1, 0] } },\n            \"6-10Week\": { \"$sum\": { \"$cond\": [{ \"$and\": [{ \"$gt\": [\"$weekDiff\", 6] }, { \"$lte\": [\"$weekDiff\", 10] }] }, 1, 0] } },\n            \"moreThan10Week\": { \"$sum\": { \"$cond\": [{ \"$gt\": [\"$weekDiff\", 10] }, 1, 0] } },\n        }\n    },\n    { \"$sort\": { \"_id\": 1 } },\n]",
   :collection "FollowUp"},
  :type "native",
  :parameters
  [{:id "7db72ccb-6a2a-4a08-ba5b-00dddc6e334d",
    :type "date/single",
    :value "2023-01-01",
    :target ["variable" ["template-tag" "start"]]}
   {:id "5be3dc65-9079-4f50-a8d3-f71992c598d6",
    :type "date/single",
    :value "2023-10-15",
    :target ["variable" ["template-tag" "end"]]}],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class com.mongodb.MongoExecutionTimeoutException,
 :stacktrace
 ["com.mongodb.internal.connection.ProtocolHelper.createSpecialException(ProtocolHelper.java:239)"
  "com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:171)"
  "com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:302)"
  "com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:258)"
  "com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)"
  "com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450)"
  "com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)"
  "com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:226)"
  "com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)"
  "com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)"
  "com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)"
  "com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)"
  "com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)"
  "com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)"
  "com.mongodb.operation.CommandOperationHelper$5.call(CommandOperationHelper.java:206)"
  "com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)"
  "com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:203)"
  "com.mongodb.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:200)"
  "com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:333)"
  "com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:42)"
  "com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:199)"
  "com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:180)"
  "com.mongodb.DBCollection.aggregate(DBCollection.java:1530)"
  "com.mongodb.DBCollection.aggregate(DBCollection.java:1488)"
  "com.mongodb.DBCollection.aggregate(DBCollection.java:1473)"
  "--> driver.mongo.execute$aggregate.invokeStatic(execute.clj:142)"
  "driver.mongo.execute$aggregate.invoke(execute.clj:136)"
  "driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:179)"
  "driver.mongo.execute$execute_reducible_query.invoke(execute.clj:173)"
  "driver.mongo$fn__132138$f__130690__auto____132139.invoke(mongo.clj:312)"
  "driver.mongo.util$do_with_mongo_connection$fn__130678.invoke(util.clj:230)"
  "util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:156)"
  "util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:145)"
  "driver.mongo.util$do_with_mongo_connection.invokeStatic(util.clj:224)"
  "driver.mongo.util$do_with_mongo_connection.invoke(util.clj:219)"
  "driver.mongo$fn__132138.invokeStatic(mongo.clj:311)"
  "driver.mongo$fn__132138.invoke(mongo.clj:309)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:12)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___77032.invoke(cache.clj:224)"
  "query_processor.middleware.permissions$check_query_permissions$fn__72615.invoke(permissions.clj:126)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__76157.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__78265$combined_post_process__78270$combined_post_process_STAR___78271.invoke(query_processor.clj:260)"
  "query_processor$fn__78265$combined_pre_process__78266$combined_pre_process_STAR___78267.invoke(query_processor.clj:257)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76943$fn__76948.invoke(resolve_database_and_driver.clj:36)"
  "driver$do_with_driver.invokeStatic(driver.clj:93)"
  "driver$do_with_driver.invoke(driver.clj:88)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76943.invoke(resolve_database_and_driver.clj:35)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__72925.invoke(fetch_source_query.clj:316)"
  "query_processor.middleware.store$initialize_store$fn__73106$fn__73107.invoke(store.clj:12)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:56)"
  "query_processor.store$do_with_store.invoke(store.clj:50)"
  "query_processor.middleware.store$initialize_store$fn__73106.invoke(store.clj:11)"
  "query_processor.middleware.normalize_query$normalize$fn__77239.invoke(normalize_query.clj:36)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__74633.invoke(constraints.clj:54)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__77168.invoke(process_userland_query.clj:151)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__77565.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___66783$thunk__66785.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___66783.invoke(reducible.clj:109)"
  "query_processor.reducible$async_qp$qp_STAR___66783.invoke(reducible.clj:94)"
  "query_processor.reducible$sync_qp$qp_STAR___66795.doInvoke(reducible.clj:129)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:383)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:379)"
  "query_processor$fn__78314$process_query_and_save_execution_BANG___78323$fn__78326.invoke(query_processor.clj:394)"
  "query_processor$fn__78314$process_query_and_save_execution_BANG___78323.invoke(query_processor.clj:387)"
  "query_processor$fn__78359$process_query_and_save_with_max_results_constraints_BANG___78368$fn__78371.invoke(query_processor.clj:406)"
  "query_processor$fn__78359$process_query_and_save_with_max_results_constraints_BANG___78368.invoke(query_processor.clj:399)"
  "api.dataset$run_query_async$fn__100119.invoke(dataset.clj:74)"
  "query_processor.streaming$streaming_response_STAR_$fn__61373$fn__61374.invoke(streaming.clj:166)"
  "query_processor.streaming$streaming_response_STAR_$fn__61373.invoke(streaming.clj:165)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__39661.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error "PlanExecutor error during aggregation :: caused by :: operation exceeded time limit",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}

[f3aee9de-ec89-429e-aa5c-9628eff37147] 2023-10-18T16:33:10+05:30 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: canceled] 20.0 mins (4 DB calls) App DB connections: 0/15 Jetty threads: 2/50 (19 idle, 0 queued) (142 total active threads) Queries in flight: 1 (0 queued)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.15.107+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4 (Debian 15.4-2.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-07",
      "tag": "v0.47.1",
      "branch": "release-x.47.x",
      "hash": "bd278b9"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

### Severity

Minor

**Comment by yog27ray** [comment]
@paoliniluis there is no load balancer between Metabase and MongoDB. If you see in logs it also mentions 
```:status :failed,
:class com.mongodb.MongoExecutionTimeoutException,
```

This timeout is 10min by default until passed in query.

Their is a load balancer between client and metabase which has timeout greater than 10min. I am getting below response from metabase when this timeout happens.

```
{
"message":"AsyncContext timeout",
"url":"/api/card/3714/query",
"status":"500"
}
```

**Comment by paoliniluis** [comment]
There is no way to set the cursor timeout from Metabase unfortunately
