### ISSUE TITLE
Content download is taking too long

### ISSUE THREAD

**Issue by raresboboc** [metabase/metabase#34795]
### Describe the bug

I have a metabase instance created in AWS ECS with Fargate. The task has 2 vCPU | 6 GB RAM and is being served by an AWS Application Load Balancer. 

From time to time it takes more than 50s to open a Dashboard which queries an AWS Redshift database. I checked the query execution time and everything looks good over there. 

As you can see in the below screenshot, the problem is not related to the server response time, but the Content Download takes a lot of time. 

<img width="500" alt="metabase_slow" src="https://github.com/metabase/metabase/assets/33001720/e30ac1ce-3c02-47e1-855c-f3a0b85f6e43">

The issue is not related to the network connection as I also tried to reach metabase from inside aws VPC and I noticed the same behaviour. 

### To Reproduce

Trying to access any dashboard will lead to this issue.

### Expected behavior

Content Download should not take that much

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.192-183.736.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "redshift",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.33"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-03",
      "tag": "v0.47.3",
      "branch": "?",
      "hash": "4202328"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2

**Comment by raresboboc** [comment]
> how big is that dashboard? how much time that single query takes?

The dashboard contains only a Pivol Table. As you can see in the picture, the query takes about 7s. The total query result has about 130Kb.

**Comment by paoliniluis** [comment]
if you just click on the pivot table, how much time the single question takes?

**Comment by raresboboc** [comment]
> if you just click on the pivot table, how much time the single question takes?

On the above example it took around 7s. It is a little bit hard to reproduce it right away as the caching is enabled.

**Comment by paoliniluis** [comment]
Caching doesn't work in pivot tables so clearly it's not a matter of caching. Do all questions take the same? how big is the response? where is the server located and where are you located? what's the CPU usage of Metabase once you use that dashboard? can you give us the entire network log?

**Comment by raresboboc** [comment]
> Caching doesn't work in pivot tables so clearly it's not a matter of caching. Do all questions take the same? how big is the response? where is the server located and where are you located? what's the CPU usage of Metabase once you use that dashboard? can you give us the entire network log?

1. The query result is being cached at the redshift level. 
2. No, not all of them. The server response varies from 500ms, up to 10s. 
3. The query result is about 130kb
4. Both in Europe. Germany and Austria to be more specific. But I'm facing the same behavior even if I start the metabase instance on my local environment. 
5. No more than 20%

**Comment by pvajmal** [comment]
Was this issue resolved? I'm also facing similar kind of issue. Content download time is high even though server responded quickly

**Comment by perivamsi** [comment]
@pvajmal which database (Postgres or MySQL) are you using to store Metabase data (appdb)? which database are you querying from (data warehouse database)?

**Comment by perivamsi** [comment]
@raresboboc is this still an issue for you? are you still on 47.3 or have you upgraded your Metabase version?

**Comment by pvajmal** [comment]
@perivamsi yes we are using PostgreSQL.

**Comment by perivamsi** [comment]
@pvajmal could you send us a screenshot of the browser dev tools network tab to see the content download time?

**Comment by pvajmal** [comment]
Please find the attached screenshot. Please not that I'm observing the latency when the application is deployed to cloud. In my local machine, there is no content download time. Initially we thought it's a frontend issue. Later observed that content download time is from backend after adding logs in websecurity layer. I can see the API successfully processed in very short time. Remaining time is consumed by other filters. Please guide me to fix this. 
![Uploading 20240701_141943.jpg…]()

**Comment by bshepherdson** [comment]
I don't think there's anything wrong with your setup, @pvajmal.

While debugging some other performance issues I discovered that a quirk in our JSON streaming of query results was causing one TCP frame to be sent for each query row, rather than letting them batch up to some reasonable size before sending a frame. In practice this causes a `/query` request to send back roughly `3 + #rows` packets when a handful were really needed.

Of course this doesn't affect single aggregations at all, and only slightly hurts a modest time series with perhaps 40 rows. But if you're fetching a dense time series or a whole table with 1000+ rows, the overhead of sending that much traffic through possibly a lot of routing and load balancing etc. could add a huge amount of overhead.

I have a prototype fix, but there's some tricky edge cases here so a lot of testing will be needed.
