### ISSUE TITLE
Allow to downgrade permissions of "All Users" with groups

### ISSUE THREAD

**Issue by oliviertassinari** [metabase/metabase#34799]
**Is your feature request related to a problem? Please describe.**

I would like to create a group that has fewer permissions than "All Users", but I can't. 

**Describe the solution you'd like**

I would like in this configuration:

<img width="666" alt="Screenshot 2023-10-18 at 16 53 49" src="https://github.com/metabase/metabase/assets/3165635/bd0914a7-0681-4be0-85f3-3df43461ce6a">

<img width="704" alt="Screenshot 2023-10-18 at 16 53 54" src="https://github.com/metabase/metabase/assets/3165635/27155e0a-ecdf-4adf-95f4-89c555c74b54">

For the people in the group "Devias" to only have view access to the "MUI Design kit" reports.

**Describe alternatives you've considered**

None

**How important is this feature to you?**

/

**Additional context**

I would like to invite someone outside of the organization and add them to a new group. I would like to retain default access to data internally so changing "All Users" permission doesn't feel possible.

**Comment by oliviertassinari** [comment]
@paoliniluis Are you saying it's not a bug or a feature request?

**Comment by paoliniluis** [comment]
This is a question, not a feature request or bug

**Comment by oliviertassinari** [comment]
In https://www.metabase.com/docs/latest/permissions/collections it says

> Just like with data access permissions, collection permissions **are additive**, meaning that if a user belongs to more than one group, if one of their groups has a more restrictive setting for a collection than another one of their groups, they’ll be given the more permissive setting.

If a user has access to collection A from "All Users" but they are in group B that is configured to not have access to collection A. What's expected outcome? Current product behavior says the expected outcome is to have access because it's configured in "All Users".

I would like to make the case that this might not be the right behavior.
