### ISSUE TITLE
Table permisssions and Dashboard permissions

### ISSUE THREAD

**Issue by hoangtrongphuc** [metabase/metabase#3480]
User group, table-level or column-level permission is good, but if I want to grant permission by value of column, It will not work.
Example : 
If I have a Client table in database, I use partnerId field for each partner of my company, I only want each partner can access to data which have a partnerId of them.
So I have 2 solution for this problem is : 
+ Grant permission by Dashboard. All question is processed by admin, admin create dashboard for each partner and each partner can see the dashboard of them.
+ Column-level permission have limit access for value-based.  
How do u think about solutions ?
Btw, thanks to metabase and team, metabase is great !! Keep up the good work

**Comment by tlrobinson** [comment]
I believe this is covered by #3363 and #2824.
