### ISSUE TITLE
Snowflake Database Setting allows you to input small caps role but breaks connection afterwards (used to work for both in 1.46.8)

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#34829]
### Describe the bug

When you are creating a Snowflake connection you can specify a Role and it will allow you to enter both a small caps `sysadmin` and large caps `SYSADMIN` role but will break for the small caps role:

<img width="1121" alt="image" src="https://github.com/metabase/metabase/assets/110378427/99d2c088-26bc-440d-ac31-862c4a6c090d">

This is critical because in 1.46.8 it used to work for both so people upgrading will end up breaking their instance if the role they specified is in small caps

### To Reproduce

1. Go to New Database Connection -> Snowflake -> Specify role as small caps (saves successfully):

<img width="908" alt="image" src="https://github.com/metabase/metabase/assets/110378427/1cd4c7fa-9d85-4f88-8fec-0e512e9bf11c">

2. New -> Native SQL -> `Select 1`

<img width="1463" alt="image" src="https://github.com/metabase/metabase/assets/110378427/a3d6e700-fcd9-4f19-9e8f-f41d4af3a082">

3. Notice the error:

`SQL compilation error: Object does not exist, or operation cannot be performed.`

### Expected behavior

Works for both small caps and large caps roles

### Logs

SQL compilation error: Object does not exist, or operation cannot be performed.

### Information about your Metabase installation

```JSON
1.47.4 and master
```

### Severity

Blocker for people that are upgrading form 1.46 and have a role specified as small caps

### Additional context

Workaround is to define the role as large caps i.e. from `sysadmin` -> `SYSADMIN`

**Comment by zbodi74** [comment]
Previously, `USE ROLE` was invoked without apostrophes. However, this was recently [changed](https://github.com/metabase/metabase/pull/33651), which now causes Snowflake to match roles in a case sensitive way.

https://docs.snowflake.com/en/sql-reference/sql/use-role
> USE ROLE \<name\>
> name - Specifies the identifier for the role to use for the session. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
