### ISSUE TITLE
PUT and POST and endpoint should return data just like calling GET

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#34828]
On UI we see a lot of places where after we `POST/PUT` a card/dashboard, we have to do another `GET` to get the item.

This is unnecessary and reduces performance, we need to standardize and make all `POST/PUT` to return the result as if you call a `GET`.

This way FE doesn't have to re-fetch after every create or update action.

```[tasklist]
### Tasks
- [x] Replace GET /api/dashboard with PUT/POST
```

**Comment by calherries** [comment]
This already works for the most part. You can see it working for example when archiving a dashboard from a collection page. The FE is just doing unnecessary GET calls in some cases, like when it saves a dashboard from the dashboard editing screen.

But we should (1) enforce GET/POST/PUT equivalence on the BE with tests, and then (2) Remove the unnecessary GET calls from the FE.

**Comment by markbastian** [comment]
https://github.com/metabase/metabase/pull/36205 resolves the BE aspects of this and removes the extraneous GET for dashboard. @EmmadUsmani is going to do a follow on to take care of `Remove redundant GET /api/card request after creating a question`.

**Comment by markbastian** [comment]
FE work for this has been split into https://github.com/metabase/metabase/issues/36326.
