### ISSUE TITLE
"Unknown" displayed after navigating back in the click behavior menu

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#34845]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/b9d88186-4fef-4492-9379-db54de24d9b1

### To Reproduce

1. Create a question with table display, e.g. based on "Orders" table from sample DB
2. Save it and add it to a dashboard
3. Edit that dashboard
4. Add custom click behavior to that dashcard
5. Choose "ID" column
6. Choose "Go to a custom destination" or "Update a dashboard filter"
7. Click "Click behavior for ID" header

"Unknown" is displayed

----

1. Create a question with table display, e.g. based on "Orders" table from sample DB
2. Save it and add it to a dashboard
3. Edit that dashboard
4. Add custom click behavior to that dashcard
5. Choose "ID" column
6. Choose "Go to a custom destination" 
7. Choose "Dashboard"
8. Pick some dashboard
9. Click chevron icon at the top of the aside to go back
10. Choose "Created at" column

"Unknown" is displayed

### Expected behavior

You're navigated to main "On-click behavior for each column" menu

### Information about your Metabase installation

master, v47

### Severity

P3

**Comment by kamilmielnik** [comment]
When fixing this issue, please search for `metabase#34845` in code and update [related code](https://github.com/metabase/metabase/pull/35051/files#diff-3ca928da028c386c159c907bf8f40bee1d8e4bc52150e9ec46a5d0aca0acca29R755-R759).

**Comment by JesseSDevaney** [comment]
Can no longer reproduce on master

**Comment by kamilmielnik** [comment]
Closed by #35863
