### ISSUE TITLE
Default click behavior does not have selected state

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#34848]
### Describe the bug

See [Slack discussion](https://metaboat.slack.com/archives/C01LQQ2UW03/p1697722224990469).

https://github.com/metabase/metabase/assets/6830683/4e30e7ef-0351-41e7-9554-baece1de7797

### To Reproduce

1. Create a question with line chart display
2. Save it and add it to a dashboard
3. Edit that dashboard
4. Click "Click behavior" in that dashcard menu

There is no visual indication that the current default behavior (e.g. "Open the metabase drill-through menu") is selected.

----

1. Create a question with table display, e.g. based on "Orders" table from sample DB
2. Save it and add it to a dashboard
3. Edit that dashboard
4. Add custom click behavior to that dashcard
5. Choose "ID" column
6. Choose "Open the metabase drill-through menu"

There is no visual indication that the current default behavior (e.g. "Open the metabase drill-through menu") is selected.

### Expected behavior

"Open the metabase drill-through menu" option appears as selected when no other click behavior is selected

### Information about your Metabase installation

master, v47

### Severity

P3

**Comment by arishmaurya** [comment]
@kamilmielnik i want to work on this issue can you please assign it to me ? and also I am a new contributor to metabase so any discussion form/ slack channel will be helpful

**Comment by kamilmielnik** [comment]
@arishmaurya This issue requires input from the design team on how the selected state should look like and is not ready to be worked on yet.

**Comment by arishmaurya** [comment]
@kamilmielnik 
okay can you add me in discussion forum where I can get to know which issue is open to work ?

**Comment by kamilmielnik** [comment]
@arishmaurya anything not assigned to anyone is open to work. PRs are welcome.

**Comment by kamilmielnik** [comment]
Closed by #35863
