### ISSUE TITLE
Visualization-specific question icons don't display on first load

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#34850]
### Describe the bug

If we enter the application and go straight into search, we see that questions with specific visualizations don't have the icons specific to their type of visualizations. Bar, line, and other charts all have the default `Table` icon.

![image](https://github.com/metabase/metabase/assets/25306947/55728cd1-3596-49f2-9d6e-d514998dd813)

If you click one of the search results and go back, the icons load just fine.

### To Reproduce

1. On initial load (or refreshing the page), search for a question with a non-table visualization
2. See that the visualization-specific icon isn't rendering 

### Expected behavior

The icons should display on first load

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20.0.1",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "20.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20.0.1",
    "os.name": "Mac OS X",
    "os.version": "13.5.2",
    "user.language": "en",
    "user.timezone": "Europe/Tallinn"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-10-18",
      "src_hash": "82a373231c32080a7109757c4ff5c230c17726a4",
      "tag": "v1.47.1-SNAPSHOT",
      "hash": "6f45ec8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

**Comment by iethree** [comment]
I think this would require that we hydrate the `display` property for questions and recents on the backend.
