### ISSUE TITLE
Write the necessary tests to guarantee that `load-from-h2` and `migrate down` always work and make them green

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#34857]
**Context**
These two commands are necessary for general Metabase operations. They enable moving from H2 to Postgres/MySQL, migrate to Cloud, and downgrade.

- [ ] Test `migrate down` is always working. It should be always possible to `migrate down` from the current major.
- [ ] Test `load-from-h2` is working in the current version and across different versions. We should test at least 4 versions. So if we are on 47. `load-from-h2` should work from a 44, 45, 46, and 47 H2 file.

There are existing issues with both commands, so these tests will fail at first. We need to fix these issues too.

**Comment by darksciencebase** [comment]
So the hope was that these tests would catch everything that's wrong with `migrate down`; they didn't. It's still good that we wrote them, and we've agreed with @cbalusek that this escalation is done with this.

There are two outstanding parts to the larger problem though:
* we couldn't reproduce the original issue that was seen in the wild; @metabase/core-backend-components will stand by for opportunities to investigate this
* we don't have test coverage for the (very real-lifey) scenario of multiple upgrades with non-empty database and then a downgrade. our best guess is that it is exactly that scenario where the rest of the issues occur. to create those, we need (1) meaningful database dumps created from a few last major versions of metabase, (2) the tests working with those dumps to check if `migrate down` works, (3) ideally also a process to keep creating these dumps in the future major versions.

I'll create issues for (1) and (2) and bring (3) up with the EMs.

**Comment by darksciencebase** [comment]
the original tests are in https://github.com/metabase/metabase/pull/35218 and https://github.com/metabase/metabase/pull/35805
