### ISSUE TITLE
Serialization v2 duplicates entities loaded with serialization v1 on old versions

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#34871]
### Describe the bug

This one has been haunting some customers for some time and I was able to repro it today after finding https://github.com/metabase/metabase/issues/34870

When loading with serdes v2 after upgrading, the entities get duplicated

### To Reproduce

1) set up Metabase with 45.4 as an origin and another as as a destination (same version)
2) create a dashboard with an x-ray on the origin.
3) dump the origin and load it onto the destination
4) now upgrade to v47 both instances
5) clean up the folder where the files are, so you're in a clean slate. Now export the source and import on the destination (use the new commands)
6) now see on the destination that the x-ray collection was duplicated

### Expected behavior

We shouldn´t duplicate entities

### Logs

no errors at all

### Information about your Metabase installation

```JSON
v47.x coming from v45
```

### Severity

P1

### Additional context

NA

**Comment by bshepherdson** [comment]
I suspect this has the same cause as #34870. I'm looking into both.

**Comment by bshepherdson** [comment]
Okay, my hunch was correct. Here's the details throughout the workflow:

1. `45 src` Create the dashboard, save it.
    - It gets an `entity_id` generated, say `i7hwdVZ-C-4qowv7vuS4p`
2. `45 src` v1 dump
    - v1 serdes doesn't include `entity_id`
4. `45 dst` Initialize the instance.
5. `45 dst` v1 load
    - Since the v1 serdes didn't include `entity_id`, a new one is generated on the way into appdb, say `qSwoHzuq32IoWwfGldZbE`.
6. `47 src` launch with the upgrade
7. `47 src` v2 export
8. `47 dst` launch with the upgrade
9. `47 dst` v2 import
10. `47 dst` Oops two dashboards!
    - Actually the collections, cards and dashcards are duplicated too.

Laid out like that I think it's pretty clear what happened.

- v1 serdes dropped the `entity_id`, so a new one was generated on `load`.
- v2 serdes relies on the `entity_id` to match up identical entities.
- The exported `src` entity has `i7hwdVZ-C-4qowv7vuS4p` and the `dst` entity has `qSwoHzuq32IoWwfGldZbE`.
    - So they're considered different entities.
- And so there are two in `dst` after `import`.

There's no bug in the code here; this is an unintended interaction of migrating from v1 to v2 serdes. How to repair any particular case is a bit involved, and depends on the purpose serdes is being put to.

If `src` and `dst` are staging and prod environments or similar, where staging is the source of truth and a subset is copied to prod periodically, the easiest path is to just nuke prod and import onto a fresh instance.

An alternative is to `UPDATE` all the `entity_id` columns (on everything) to be `NULL` in `src` and `dst`. Then when `export` or `import` runs they'll generate `entity_id`s based on the hashes, which should be the same in both environments, and then no duplication should result. **This is risky**, and they should definitely try it on clones of the real data first!

**Comment by paoliniluis** [comment]
ok, then we should add something like https://github.com/metabase/metabase/pull/21241 @bshepherdson

**Comment by bshepherdson** [comment]
I'm not so sure. It's tricky, because both serdes versions are working as intended.

I view it as "If you v1 dump from A and v1 load to B, it is **not safe** to just start using v2 export and import on them." Steps are required to migrate from v1 serdes to v2. In this case, the simplest path is to burn down B and import fresh. Then there's no duplication and no problem.

I can only see two paths to changing the code to accommodate this, and neither is a clear win:
1. Update v1 to include `entity_id`s if they're set, and to *overwrite* existing entities that match up in the v1 sense, even if their `entity_id`s are different. (That feels dangerous, but it's not worse than v1 is already.)
    - There might be unintended consequences here? But I think it would work; v1 would treat `entity_id` like any random string field.
    - To be useful, this would have to be backported to several versions, but excluding `master` since v1 is dead.
2. Update v2 to detect cases like this, warn and abort without changing things. This is computationally expensive and nontrivial to code up, and it doesn't actually solve the problem.

**Comment by paoliniluis** [comment]
Then we'll need to build a document for migration, as most of our customers can't burn their prod instance and start from scratch

**Comment by luizarakaki** [comment]
@bshepherdson as this is a only once operation that is required only if they are migrating from v1 to v2 without wiping the prod instance, can we write a script that somehow fixes it for them?

Something that connects to src and dst and runs the necessary entity_id operations to revert to a matching state?

**Comment by bshepherdson** [comment]
@luizarakaki we could do that, yes.

We could add a script that you could run (on the new version, but before `export`ing) that would fix this issue. I think the best path would be to have it do `UPDATE $table SET (entity_id = NULL)` to blank the `entity_id`s. Run that for both environments, then the `export` and `import` will generate hopefully-identical `entity_id`s based on hashing the entities.

That's a modest effort; it's a pretty straightforward thing to add, and I think it would be great for this specific use case.

**Comment by Tony-metabase** [comment]
@bshepherdson on which version will this be fix be?

**Comment by bshepherdson** [comment]
It's in master in time for 48; I tried to auto-backport it but that failed. I'll send a manual backport today.
