### ISSUE TITLE
Allow Admins to Bulk Rename Tables/Datasets

### ISSUE THREAD

**Issue by cbeauch** [metabase/metabase#34919]
**Is your feature request related to a problem? Please describe.**
When tables are renamed or moved to different datasets, there is currently no way to bulk edit questions created with the UI. I can bulk edit Native SQL questions with the backend database only. 

**Describe the solution you'd like**
I'm not sure. Just anything that will allow me to bulk change `dataset1.table` to `dataset2.table` on questions across the org. 

**Describe alternatives you've considered**
Backend database queries. 

**How important is this feature to you?**
This is actually super important. We are a scaling company frequently moving assets around and this is causing headaches. 

**Additional context**
Below is how I change Native SQL questions. 

```
UPDATE report_card SET dataset_query = REPLACE(dataset_query, "REQUESTS.product_merchant_platform_traffic",'ANALYTICS.merchant_platform_traffic') WHERE dataset_query LIKE "%REQUESTS.product_merchant_platform_traffic%";
```

**Comment by paoliniluis** [comment]
isn´t this the same as https://github.com/metabase/metabase/issues/29781 and https://github.com/metabase/metabase/issues/29780?

**Comment by cbeauch** [comment]
> isn´t this the same as #29781 and #29780?

Oops, yes it is. I will close this.
