### ISSUE TITLE
Confusing copy in confirm modal when changing table data access to Sandboxed

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#34911]
### Describe the bug

The copy seems inconsistent with the terms we use:

<img width="1130" alt="image" src="https://github.com/metabase/metabase/assets/24216/56e231a5-ebc6-412b-9da3-2d4c808888e1">
<img width="844" alt="image" src="https://github.com/metabase/metabase/assets/24216/b78e3cb0-b6d3-4ed1-a768-b0c5fddc3833">

I would expect the wording "Granular" if it's about changing the access level for the entire DB or "sandboxed" if it's about the data access level for the table. I'm able to trigger this just by changing data access at the table level, so I am guessing the sentence is also wrong. I'm also able to trigger this by changing the level to unrestricted, which makes no sense.

### To Reproduce

1. Go to Permissions/Data
2. Select a group
3. Select sample database
4. Change data access for one of the tables to Sandboxed
5. The modal will pop

### Expected behavior

"Change access to this table to Sandboxed?" when switching to sandboxed, "Change access to this table to Unrestricted?" when changing to unrestricted, etc.

### Information about your Metabase installation

```JSON
- Metabase v1.47.4, Built on 2023-10-11
```

### Severity

Low

**Comment by shaunlebron** [comment]
>  I'm also able to trigger this by changing the level to unrestricted, which makes no sense.

@albertoperdomo I couldn’t get the modal to pop up when switching the level to unrestricted.  Could you add steps to reproduce this?

**Comment by albertoperdomo** [comment]
@shaunlebron 

1. Create group "bug repro"
2. Go to permissions, select "bug repro"
3. Click on Sample database, permissions seem to default to "No self-service"
4. For one of the tables, change data access from self-service to sandboxed or unrestricted. In both cases I get the same modal

Loom: https://www.loom.com/share/8f6332dc39624463a0f897aea43e007c

**Comment by shaunlebron** [comment]
Fixed by #36243
