### ISSUE TITLE
Disable sync on Audit database

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#34916]
The AuditDB should have only the metadata from the audit views. They come from the serialized yamls: https://github.com/metabase/metabase/tree/auditv2-main/resources/instance_analytics

Disabling sync, the instance won't have access to any other table besides the views.

**Comment by darksciencebase** [comment]
resolved by https://github.com/metabase/metabase/pull/34983 i assume? @escherize @luizarakaki
