### ISSUE TITLE
Metric and Segment creation weirdness

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3492]
On rc-0.20, when attempting to create a Metric, I'm incorrectly shown `raw data` as a possible selection for my aggregation type (and it's unclickable). 

More importantly, I also can't seem to make a selection for **any aggregation type**. If it's a one-step aggregation type, like `count of rows`, it's unclickable; if it's a two-step selection, like `Sum of…`, then the column is unclickable.

This is also happening with Segment creation: select any kind of filter, then try clicking `Add filter` and observe that nothing happens. You also cannot close the popover menu.

<img width="351" alt="screen shot 2016-10-10 at 11 55 31 am" src="https://cloud.githubusercontent.com/assets/2223916/19247566/a12d50a2-8ee0-11e6-9224-2a15830bb9a0.png">

**Comment by salsakran** [comment]
fixed in #3495
