### ISSUE TITLE
Underlying field names in data reference have red borders

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3493]
This is a thing that should not be. 🐝
I'm looking at this on `release-0.20`.

![screen shot 2016-10-10 at 1 30 08 pm](https://cloud.githubusercontent.com/assets/2223916/19250164/c576131a-8eed-11e6-8f39-a1aa51df0d8d.png)

**Comment by tlrobinson** [comment]
This means we're using a CSS module class name that doesn't exist.
