### ISSUE TITLE
Static/Public embeds fail to load dashboard when one of the cards fails to load due to missing filter value.

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#34954]
### Describe the bug

Static/Public embeds fail to load dashboard when one of the cards fails to load due to missing filter value.

### To Reproduce

1. Go to New -> SQL Query -> `Select * from products Where category = {{something}}` -> Save

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/78b51e69-f5d4-48a5-8dd6-5acc86947b4b">

2. Add it to a Dashboard -> Add a filter to the  card:

<img width="1510" alt="image" src="https://github.com/metabase/metabase/assets/110378427/d71a462c-e9f8-4158-a369-023366514bd9">

3. Go to Edit -> Click on the Card and edit visualisation option -> Enable `Hide this card if there are no results`

<img width="1443" alt="image" src="https://github.com/metabase/metabase/assets/110378427/4d913f00-0bef-4a2e-8b1f-8da55a8f7c0e">

4. Go to Share -> Enable Public Sharing (this also happens for Static Embedding) -> Go to the public URL and notice a blank screen:

<img width="1511" alt="image" src="https://github.com/metabase/metabase/assets/110378427/c6e1d52d-8abf-4623-95c2-1ef122fc93b7">

The dashboard is able to load at first but if you notice the network calls when the error due to filter not being selected for the card occurs it simply breaks the screen:

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/7798b9d7-3915-4d1b-97fd-47c6f399c2d3">

Something similar to Metabase should occur like the following:

<img width="1500" alt="image" src="https://github.com/metabase/metabase/assets/110378427/f750346d-75f2-4a0b-90b1-6398e97a541c">

Even though the error message `something is gone wrong` is very misleading instead of a `please select filter for something` 

### Expected behavior

Cannot share an image here but i described it in the Reproduce Section

### Logs

None that are relevant even though the actual error is:

`Cannot run the query: missing required parameters: #{\"something\"}`

Even though it's not specific to that error but how the frontend behaves due to that error

### Information about your Metabase installation

```JSON
1.47.5 ann master
```

### Severity

This completely blocks the usage of 2 important features

### Additional context

The only workaround is to put a default value but if you decide to remove it from the URL then you end up breaking the visual again

**Comment by albertoperdomo** [comment]
@cdeweyx Is this for Dashviz team or for us?

**Comment by cdeweyx** [comment]
> @cdeweyx Is this for Dashviz team or for us?

@albertoperdomo looks embedding-specific so my thinking is #team-embedding

**Comment by WiNloSt** [comment]
This could either be fixed on FE or BE. The reason is that when query from our dashboard. BE will send `data` in the response
![image](https://github.com/metabase/metabase/assets/1937582/08db3534-26e3-44aa-8683-81f860566e89)

but not when we're querying from public embed (public link) or static embed
![image](https://github.com/metabase/metabase/assets/1937582/4fda2351-3133-4444-be26-fec8bab3dc3d)
