### ISSUE TITLE
[MLv2] [BE] Using summarize-column on a custom column produces incorrect query due to expression conversion to a field

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#34957]
Using summarize-column on a custom column produces incorrect query due to extra field types

Use this unit test to reproduce -  https://github.com/metabase/metabase/pull/34908/files#diff-b15cc6d446a355dead5003f1c3b596f577074d40cc275ce8df9243c98ad3552dR2257-R2290

**Comment by camsaul** [comment]
This is not a bug, see discussion in https://metaboat.slack.com/archives/C04CYTEL9N2/p1698073705365269
