### ISSUE TITLE
Visual glitches when dragging a tab on another

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#34966]
### Describe the bug

When moving tabs over other tabs, the tabs gets "stretched" visually
<img width="523" alt="image" src="https://github.com/metabase/metabase/assets/1914270/2a53a07e-1ec2-46db-97ed-f73c11895545">

There's also a small z-index problem, the circle around the chevron is higher than the tab being dragged, this seems to be easier to reproduce when dragging a small tab on a big one

### To Reproduce

1. Create a dashboard with multiple tabs with different tab name lenghts
2. Drag a small tab over a long tab or viceversa

https://github.com/metabase/metabase/assets/1914270/9403a1de-7b4f-4bc1-aa6a-ac3abceb7065

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20.0.1",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "20.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20.0.1",
    "os.name": "Mac OS X",
    "os.version": "13.4",
    "user.language": "en",
    "user.timezone": "Europe/Rome"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-10-23",
      "src_hash": "b0405005069114a27afd983f72ea1227201d24f5",
      "tag": "v0.47.1-SNAPSHOT",
      "hash": "84001ac"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

low

### Additional context

Possibly related to https://github.com/metabase/metabase/issues/34970

**Comment by markbastian** [comment]
This may have the same fix as [this issue](https://github.com/clauderic/dnd-kit/issues/117) on the dnd-kit github.
