### ISSUE TITLE
[MLv2] [Bug] BE - Unexpected join alias in filter names in nested questions

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#34972]
Steps:
- Create a GUI question based on the orders table
- Create another question using the previous one as data source
- Join on the products table
- Add a filter

<img width="780" alt="Screenshot 2023-10-23 at 19 52 47" src="https://github.com/metabase/metabase/assets/8542534/d7090ce7-7d87-4c1e-b473-9109021dcd48">

**Comment by snoe** [comment]
@ranquild It looks like this was fixed elsewhere, although I notice the lhs join table name isn't using the card name here. This is what I see on master.

<img width="1181" alt="image" src="https://github.com/metabase/metabase/assets/105012/66656273-66ba-4290-86ee-8af2e184fe9e">
