### ISSUE TITLE
Can't re-order tabs with long names

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#34970]
### Describe the bug

If you have a dashboard with the following tabs: [Tab 1] [Tab 2] [Tab with very a very long name]

It's impossible to drag the third tab as first

https://github.com/metabase/metabase/assets/1914270/38a2334b-50ef-4116-bb95-a6c4ccd0e459

### To Reproduce

1. Create a new dashboard
2. Create 2 tabs
3. Rename the third one to a long name
4. Try to drag it in the first position

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "20.0.1",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "20.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "20.0.1",
    "os.name": "Mac OS X",
    "os.version": "13.4",
    "user.language": "en",
    "user.timezone": "Europe/Rome"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-10-23",
      "src_hash": "b0405005069114a27afd983f72ea1227201d24f5",
      "tag": "v0.47.1-SNAPSHOT",
      "hash": "84001ac"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

mid low, the workaround is enough clear but annoying,which is to drag the first two tabs instead of the third

### Additional context

Possibly related with https://github.com/metabase/metabase/issues/34966

**Comment by markbastian** [comment]
Based on experimentation it looks like 23 characters is the max that is draggable with 2 default tabs before it. 24 will block. It appears that maybe if the width of the dragged tab is wider than the previous tabs it can't be dragged.
