### ISSUE TITLE
Feature Request: ability to stack bars together, while having a line across for combo charts

### ISSUE THREAD

**Issue by merchantsally** [metabase/metabase#34988]
**Is your feature request related to a problem? Please describe.**
I want to group my revenue by line of business, stack them up to form total revenue, and then compare that total revenue to a target line. This is currently unsupported in Metabase.

**Describe the solution you'd like**
I want to group my revenue by line of business, stack them up to form total revenue, and then compare that total revenue to a target line.

**Describe alternatives you've considered**
n/a

**How important is this feature to you?**
I've run into this every single month, probably multiple times a month. We do this for everything targets related, and it's really hard to live without this feature.

**Additional context**

**Comment by iethree** [comment]
@merchantsally you should be able to stack revenue in a bar chart and compare to a goal line. Here's an example with the included sample database. Is this what you need?

![Screen Shot 2023-10-24 at 8 51 30 AM](https://github.com/metabase/metabase/assets/30528226/a5dc04f5-7ce5-4154-86d3-32b6018b3e1c)


![Screen Shot 2023-10-24 at 8 49 11 AM](https://github.com/metabase/metabase/assets/30528226/e954dde3-dd52-4eea-a0c7-c4a0740498ad)

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/42085
