### ISSUE TITLE
Documentation page is not properly formatted

### ISSUE THREAD

**Issue by TLazarevic** [metabase/metabase#35002]
### Describe the bug

[About the information we collect](https://www.metabase.com/docs/latest/installation-and-operation/information-collection) page has 3 headings with event and metric specification:

https://www.metabase.com/docs/latest/installation-and-operation/information-collection#google-analytics-events
https://www.metabase.com/docs/latest/installation-and-operation/information-collection#snowplow-events
https://www.metabase.com/docs/latest/installation-and-operation/information-collection#server-side-analytics

Instead of tables with event specifications being rendered under the correct headings, tables are all shifted to the bottom of the page

### To Reproduce

1. Go to https://www.metabase.com/docs/latest/installation-and-operation/information-collection#google-analytics-events
2. Scroll down to [Google Analytics Events](https://www.metabase.com/docs/latest/installation-and-operation/information-collection#google-analytics-events)
3. Nothing is under the heading

### Expected behavior

Tables with events are rendered under correct heading

### Information about your Metabase installation

```JSON
-
```

### Severity

Very low

**Comment by reddy2018** [comment]
@TLazarevic Did you find any documentation for installtion? i could not found any helm chart to install it in kubernetes environment.

**Comment by jeff-bruemmer** [comment]
Closing this issue, as we've updated that page and removed the tables. Thanks for reporting, @TLazarevic.
