### ISSUE TITLE
"Date range" filter: I can set a range in which "from" is a later date than "to".

### ISSUE THREAD

**Issue by nomorethat** [metabase/metabase#35043]
### Describe the bug

In the "Date Range" filter, I can set through the input field a range in which "from" is a later date than "to".

![ksnip_20231025-125059](https://github.com/metabase/metabase/assets/46302088/caffbbc5-01d1-429c-8be9-9ab68f874df4)

![ksnip_20231025-125324](https://github.com/metabase/metabase/assets/46302088/f0833667-95ab-43fb-8c80-caf09a5dd974)

It may be worth making sure that when you try to make the date "from" later than the date "to", they are swapped in the widget. If I entered "October 25, 2023" in the "from" field, and I entered "October 15, 2023" in the "to" field, the "from" field in the widget became "October 15, 2023", and the "to" field became "October 25, 2023".

### To Reproduce

Any place where the "date range" filter is used.

### Expected behavior

you cannot enter the date "from" later than the date "to"

### Information about your Metabase installation

```JSON
v0.47.5
```

### Severity

-

**Comment by nemanjaglumac** [comment]
Reproduced and confirmed to be fixed in both `master` and the `release-x.50.x` branches.
