### ISSUE TITLE
Localization doesn't work in the metrics and segments management menu (admin settings).

### ISSUE THREAD

**Issue by nomorethat** [metabase/metabase#35041]
### Describe the bug

Localization doesn't work in the metrics and segments management menu (admin settings). 

### To Reproduce

1. Go to "Admin settings"
2. Go to "Table Metadata"
3. Create a metric and segment
4. Click "Actions"
5. Regardless of the selected language, "metric", "retire metric", "segment", "retire segment" are not translated. Is this a bug?

![ksnip_20231025-123058](https://github.com/metabase/metabase/assets/46302088/27afd71c-4c32-485a-a279-53fe83e7610b)

![ksnip_20231025-123115](https://github.com/metabase/metabase/assets/46302088/23ffeeb7-2e64-487e-9b37-e31c1fff917f)

![ksnip_20231025-123238](https://github.com/metabase/metabase/assets/46302088/ba1cde60-5678-4bb3-a169-cee2a83d280f)

![ksnip_20231025-123255](https://github.com/metabase/metabase/assets/46302088/92e7b96f-a372-410c-bbf9-3f40325ed473)

![ksnip_20231025-123326](https://github.com/metabase/metabase/assets/46302088/aaccef28-4bbb-43a6-b4fb-fcf1a381d487)

![ksnip_20231025-123340](https://github.com/metabase/metabase/assets/46302088/b460b728-9236-4e80-9b98-eb2fbd5b1597)

![ksnip_20231025-124229](https://github.com/metabase/metabase/assets/46302088/3a3d09fb-b601-403f-a4ae-511aaaaa412a)

![ksnip_20231025-124239](https://github.com/metabase/metabase/assets/46302088/75fd5912-c768-4cef-a5fd-5e7b0a35e1c4)

### Expected behavior

"metric", "retire metric", "segment", "retire segment" are translated

### Information about your Metabase installation

```JSON
v0.47.5
```

### Severity

-

**Comment by antonhedstrom** [comment]
Started looking into the related code and can confirm the translations can be improved here. The menu is being shared between `metrics` and `segments`. I am thinking it would be better to have them as separate components to easier handle the separate cases we have here. Something like a `SegmentActionSelect` and `MetricActionSelect`. Would like to get some inputs on these thoughts before looking into implementing it.

```js
// frontend/src/metabase/admin/datamodel/components/ObjectActionSelect.jsx:L67
triggerElement={"Retire " + capitalize(objectType)} // Missing translation and invalid concatenation of object type 
```

**Comment by nomorethat** [comment]
UPD: I found the same problem in the history of changes

![ksnip_20231103-131310](https://github.com/metabase/metabase/assets/46302088/7c7f668a-3dfa-45d5-a836-5ccc2c405a1d)
