### ISSUE TITLE
MySQL SET command not working

### ISSUE THREAD

**Issue by majithiaharshil** [metabase/metabase#3505]
```sql
SET @loan=123;
SELECT * from loan where id=@loan;
```

And it tells me that I have an error in my query

**Comment by hugocar** [comment]
It might be unsafe to use session variables in questions since Metabase users are sharing a pool of connections.
For your exemple, why not use the metabase variable system ?  

`SELECT * from loan where id={{loan}}`

For other variable usages (like rolling Sum), we should wait for someone of the metabase staff to answer

**Comment by majithiaharshil** [comment]
Hey  @hugocar SELECT * from loan where id={{loan}} 
worked

Thanks a lot !!

**Comment by majithiaharshil** [comment]
How do i take multiple inputs from the same ?
Any idea?

for eg , i want 

 _`SELECT * from loan where id in (2,5,6,9,6)`_

will it work if i pass multiple values in {{loan}} 

_`SELECT * from loan where id={{loan}} `_

**Comment by hugocar** [comment]
The feature doesn't exist, sadly.

I guess the best course would be to close this issue and open a suggestion.

Depending on your Database type (MySQL, Redshifts...) you might have access to a split_string function with which you could use to split a single input text into the desired collection input.
Dosent exist in MySQL.

**Comment by camsaul** [comment]
@majithiaharshil it sounds like @hugocar's suggestion solved your problem, so I agree it makes sense to close this out and open a new issue for supporting SQL `IN` clauses. That's something we can look into in the future.

**Comment by camsaul** [comment]
Just saw that you already opened the new issue at #3567. I'm going to go ahead and close this since it sounds like @hugocar's suggestion solved your problem 👍

**Comment by salsakran** [comment]
@majithiaharshil we don't currently run multiple SQL statements in a single query. 
Regarding multiple inputs, is the notion that you'd want to manually type in the `(2,5,6,9,6)` into an input?

**Comment by majithiaharshil** [comment]
I want to take it from a variable {{id}}
