### ISSUE TITLE
Users with read-only permissions to collections are shown "edit question" option in dashboard cards

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35077]
### Describe the bug

Seems like a UI bug where we show "edit question" to someone that does not have permission to edit the question.

(the issue does not let someone edit a question, so this is just a UI bug)
![image](https://github.com/metabase/metabase/assets/1711649/425d05e5-5661-45fe-86d5-36bcff7d84be)

### To Reproduce

1) create a user
2) give "all users" read only permissions to all collections
3) create a dashboard from an x-ray
4) authenticate to Metabase with the normal user
5) go to the dashboard with the user that does not have permissions
6) click on the 3 dots of a card, see "edit question" when it shouldn't be there

### Expected behavior

We shouldn't give options that are not valid for a user

### Logs

NA

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P3

### Additional context

It can lead to users believing they have more permissions than what they actually have

**Comment by uladzimirdev** [comment]
@ranquild can we rely on `dashcard.card.can_write` to understand if we have permissions to edit question?

**Comment by ranquild** [comment]
@uladzimirdev I think yes

**Comment by alxnddr** [comment]
Reopen until backported

**Comment by uladzimirdev** [comment]
backport has been merged
