### ISSUE TITLE
Filters blink when there are many lines of filters in an embedded context with headers=false

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35078]
### Describe the bug

If you have many lines of filter on an interactive embedding context with headers = false, filters will blink

![blink](https://github.com/metabase/metabase/assets/1711649/d07a80b1-ab95-45a6-91d6-af4d3c175670)

### To Reproduce

1) use the full app embedding demo https://github.com/metabase/sso-examples/tree/master/app-embed-example, but ensure that you add headers=false to the embedding URL (https://www.metabase.com/docs/latest/embedding/interactive-embedding#header)
2) as an admin, log into metabase and build a dashboard with an x-ray and then add several filters till you get to a second line
3) then autheticate as a user via the embedding
4) go to the dashboard and scroll down, you'll see the filters blinking

### Expected behavior

filters shouldn't blink

### Logs

NA

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P2

### Additional context

NA

**Comment by uladzimirdev** [comment]
we have a logic which recalculates "sticky" position for the filters based on the number of filters and if it's mobile/or not. Most likely, it's broken with embedding
