### ISSUE TITLE
Community Data Source Connector for StarRocks

### ISSUE THREAD

**Issue by alberttwong** [metabase/metabase#35070]
Hi,

I'd like to create a StarRocks connector for metabase.   Does anyone know what is the process?

**Comment by paoliniluis** [comment]
Hi @alberttwong , I suggest you take a look at our [development documentation](https://www.metabase.com/docs/latest/developers-guide/start), the [wiki](https://github.com/metabase/metabase/wiki)  and also a [partner driver](https://github.com/ClickHouse/metabase-clickhouse-driver)

**Comment by yushesp** [comment]
Check out https://github.com/Carbon-Arc/metabase-starrocks-driver
