### ISSUE TITLE
Timed out after 10.0 s( Getting this error while connecting to MYSql database, staging on a linux server)

### ISSUE THREAD

**Issue by akash-pandey-123** [metabase/metabase#35087]
I installed Metabase on my Linux machine first time, now when I am trying to connect this to the MySql database I am getting a "Time Out after 10s" error message. 

**I am getting a log message like this**
[131befe5-5e90-4541-bca7-52de7ec0fc41] 2023-10-26T15:26:50+05:30 ERROR metabase.driver.util Failed to connect to Database
java.util.concurrent.TimeoutException: Timed out after 10.0 s

**Comment by paoliniluis** [comment]
Please use the forums for question
