### ISSUE TITLE
AWS Lambda frequently fails to fetch Metabase data

### ISSUE THREAD

**Issue by alexanderliu-creator** [metabase/metabase#35081]
### Describe the bug

AWS Lambda function has a high failure rate when accessing a certain card in Metabase through requests.post and fetching the Metabase results. I set the right X-Metabase-Session during the query and can query results from time to time. But when i use a AWS Lambda(Python) cronjob to pull data from Metabase, the cronjob fails frequently.

### To Reproduce

1. Go to AWS Lambda
2. Fill in the rquests.post to access a specific card, for example https://metabase_weburl/api/card/card_id/query/json
3. Click on Test of the AWS Lambda, it may work successfully, but it fails frequently
4. If you use a AWS cronjob to execute the query, you'll see the failure rate is really high.

### Expected behavior

Metabase's connection should be stable, and the failure rate is low.

### Information about your Metabase installation

```JSON
- AWS Lambda, python 3.10
- Metabase internal database: Postgres(Business partner provided so I don't see the detailed info)
- Metabase version: You're on version v0.46.6.3, Built on 2023-07-28, Branch: release-x.46.6.3, Hash: 69632b7
```

### Severity

It's very very very severe. Many of our business scenarios are built on syncing data from Metabase, if Metabase cannot provide stable connections, we'll consider immediately using other services.

### Additional context

Actually, Metabase is a blackbox and AWS is also a blackbox. We're not certain which side cause this problem or both sides have responsibility to the bug. So I raise technical support on both sides. We really appreciate Metabase graceful design and consider using Metabase first. I really hope this problem can be solved and i'll definitely choose to use Metabase as our service provider!!!

**Comment by tsmacdonald** [comment]
Could you post a sample failed response?

**Comment by alexanderliu-creator** [comment]
The requests.post will not return if I don't set the timeout parameter, if I set the parameter timeout to 30s, the requests.post will raise a timeout exception when timeout. I only have two lines of data in my Metabase, so i'm sure this is caused by the network connection problem.

[ERROR] Exception: Fetch user attributes from Metabase failed
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 115, in lambda_handler
    return sync_user_attributes(session_header)
  File "/var/task/lambda_function.py", line 90, in sync_user_attributes
    user_attributes = fetch_user_attributes(query_url, session_header)
  File "/var/task/lambda_function.py", line 85, in fetch_user_attributes
    raise Exception("Fetch user attributes from Metabase failed")

the code here is:
def fetch_user_attributes(url, session_headers):
    try:
        post_response = requests.post(url, headers=session_headers, timeout=30)
        if post_response.status_code == 200:
            return post_response.json()
        elif post_response.status_code == 401:
            session_headers = refresh_session_header()
            post_response = requests.post(url, headers=session_headers)
            if post_response.status_code == 200:
                return post_response.json()
        else:
            logger.info(f"Failed to fetch_user_attributes from Metabase: {str(post_response)}")
    except Exception as e:
        logger.info(f"Failed to fetch_user_attributes from Metabase: {str(e)}")

    raise Exception("Fetc user attributes from Metabase failed")

If the network connection is stable, the Lambda will be executed immediately costing only a few seconds.


> Could you post a sample failed response?

The requests.post will not return if I don't set the timeout parameter, if I set the parameter timeout to 30s, the requests.post will raise a timeout exception when timeout. I only have two lines of data in my Metabase, so i'm sure this is caused by the network connection problem.

[ERROR] Exception: Fetch user attributes from Metabase failed
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 115, in lambda_handler
    return sync_user_attributes(session_header)
  File "/var/task/lambda_function.py", line 90, in sync_user_attributes
    user_attributes = fetch_user_attributes(query_url, session_header)
  File "/var/task/lambda_function.py", line 85, in fetch_user_attributes
    raise Exception("Fetch user attributes from Metabase failed")

the code here is:
def fetch_user_attributes(url, session_headers):
    try:
        post_response = requests.post(url, headers=session_headers, timeout=30)
        if post_response.status_code == 200:
            return post_response.json()
        elif post_response.status_code == 401:
            session_headers = refresh_session_header()
            post_response = requests.post(url, headers=session_headers)
            if post_response.status_code == 200:
                return post_response.json()
        else:
            logger.info(f"Failed to fetch_user_attributes from Metabase: {str(post_response)}")
    except Exception as e:
        logger.info(f"Failed to fetch_user_attributes from Metabase: {str(e)}")

    raise Exception("Fetc user attributes from Metabase failed")

If the network connection is stable, the Lambda will be executed immediately costing only a few seconds.

**Comment by alexanderliu-creator** [comment]
> Could you post a sample failed response?

The requests.post will not return if I don't set the timeout parameter, if I set the parameter timeout to 30s, the requests.post will raise a timeout exception when timeout. I only have two lines of data in my Metabase, so i'm sure this is caused by the network connection problem.

[ERROR] Exception: Fetch user attributes from Metabase failed
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 115, in lambda_handler
    return sync_user_attributes(session_header)
  File "/var/task/lambda_function.py", line 90, in sync_user_attributes
    user_attributes = fetch_user_attributes(query_url, session_header)
  File "/var/task/lambda_function.py", line 85, in fetch_user_attributes
    raise Exception("Fetch user attributes from Metabase failed")

the code here is:
def fetch_user_attributes(url, session_headers):
    try:
        post_response = requests.post(url, headers=session_headers, timeout=30)
        if post_response.status_code == 200:
            return post_response.json()
        elif post_response.status_code == 401:
            session_headers = refresh_session_header()
            post_response = requests.post(url, headers=session_headers)
            if post_response.status_code == 200:
                return post_response.json()
        else:
            logger.info(f"Failed to fetch_user_attributes from Metabase: {str(post_response)}")
    except Exception as e:
        logger.info(f"Failed to fetch_user_attributes from Metabase: {str(e)}")

    raise Exception("Fetc user attributes from Metabase failed")

If the network connection is stable, the Lambda will be executed immediately costing only a few seconds.

**Comment by alexanderliu-creator** [comment]
> Could you post a sample failed response?

the url here is a Metabase card url, through which we can fetch data from Metabase, e.g. https://metabase_website/api/card/card_id/query/json

**Comment by paoliniluis** [comment]
Hi, we don’t answer questions of external code even if our product is involved unless you’re a paid customer and you need support involving Metabase in a solution. Either if we did, you didn’t even post the Metabase logs and on top of that your python code is wiping the exception and throwing a custom one, which makes every debugging impossible
