### ISSUE TITLE
An alert set on a model reverts the models customized column names

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#35091]
### Describe the bug

After an alert set on a model is triggered, the model's customized column names are reverted to the original column names coming from the models data source.

### To Reproduce

1. Create a simple model using a GUI query, for instance select all rows from Products.
2. Update the metadata and rename a few columns.
3. Set an hourly alert on the model, and wait until the alert is triggered.
5. (!) See the column names are changed back to their original versions. 
The change can also be seen in the app db in `report_card.result_metadata`.

### Logs

n/a

### Information about your Metabase installation

```JSON
1.47.5
```

### Severity

P2? I found this while trying to reproduce an unrelated problem. More than a cosmetic issue as the model's configuration is being changed.

### Additional context

This doesn't seem to happen with questions.

**Comment by brunobergher** [comment]
IMO the bug is even offering alerts on models, that makes no sense.
