### ISSUE TITLE
Typing on search bar before dashboard has finished rendering gets the search bar in non-functional state

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#35099]
### Describe the bug

You want to look at something in Metabase. You know search is your best friend. So you open any Metabase dashboard using your browser's history and start typing into the search bar right away.

Then suddenly things stop working...

It looks like dashboard rendering or page loading interferes with the search bar. Search works until it finished loading, then it stops working. There's a trick to make it work again, but it taints the "I know search is the fastest way to get to what I want, fast".

### To Reproduce

1. Open a dashboard in Metabase
2. While the dashboard is rendering, click on search bar and type a search term
3. When the dashboard finishes rendering, the search bar gets into a weird state, where it no longer searches and no longer picks up any changes to the search term
4. To make it work again, reset focus by clicking outside of search bar and then again inside of the search bar

A repro video is available [here](https://metaboat.slack.com/archives/C057T1QTB3L/p1698332411188439).

### Expected behavior

Loading/redering in Metabase does not interfere with my goal of finding things fast :)

### Information about your Metabase installation

```JSON
- Metabase hash 768ba05 Built on 2023-10-26
- Chrome Version 118.0.5993.88 (Official Build) (arm64)
- Mac OS Ventura 13.6 (22G120)
```

### Severity

Low

**Comment by albertoperdomo** [comment]
Related to #34949 (dupe??)

**Comment by npfitz** [comment]
In `SearchBar.tsx`, we compare locations to see to see if we should dismiss the search bar. However, we're comparing objects, and it looks like dashboards actually do a `Replace` on the location, I'm guessing it's to put dashboard filter params in the URL. If we change this to compare `location.pathname`, That should solve the issue
