### ISSUE TITLE
Visualization doesn't pick up the all fields returned by the query

### ISSUE THREAD

**Issue by aaaaahaaaaa** [metabase/metabase#35093]
### Describe the bug

Sometimes (i can't pin-point under which circumstances exactly), the visualization doesn't pick all the fields returned from the database when the query is built via the editor, which prevents the visualization from displaying the data correctly. All the fields would appear as expected in the raw table representation, but for some reason under the `Data` tab of the visualization's configuration, a field would be missing (typically a `string` field).

Here is an example. The `item_description` field is not picked up by the visualization, although the data is correctly returned, which prevents the visualization from breaking down the timeseries by `item_description`:
![image](https://github.com/metabase/metabase/assets/2808155/4a689acf-7fc0-4130-88dd-81a2271c24d7)

It seems to be a bug related to the UI editor specifically, because those 2 different workarounds solve the problem:
* if I copy the query generated via the editor using `View the SQL` button, and copy the query without any modification under a new raw `SQL query` question, then the visualization works as expected.
* using the editor, if I create a custom column using `trim([item_description])` and base the rest of query summary on that new field, the visualization also work.

I've been using Metabase for a few years now, and this is a bug I've encountered several times. Not frequently but occasionally here and there.

### To Reproduce

There isn't to my knowledge a deterministic way to reproduce this bug...

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.15.107+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-20",
      "tag": "v0.47.5",
      "branch": "?",
      "hash": "e7ee12e"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

### Severity

P2

**Comment by paoliniluis** [comment]
Is there a way you can reproduce with the sample database?

**Comment by aaaaahaaaaa** [comment]
Not as far as I can tell. I've just played around with it and it functions properly. Again, it's an issue I've encountered very rarely, but several times nonetheless.

**Comment by paoliniluis** [comment]
It will be very difficult to reproduce then

**Comment by aaaaahaaaaa** [comment]
I found a way to reproduce it with the following public BigQuery table: `dc-int-dwh-dev.metabase_bug_report.issue_35093`.

I can't guarantee how long this table will be kept public though. I would recommend that you guys copy it in your own BQ internally.

**Comment by paoliniluis** [comment]
@aaaaahaaaaa sorry, what’s that table? Where and how do we get it?

**Comment by aaaaahaaaaa** [comment]
If you want to copy it, you can use the `bq` CLI. Or via the BigQuery UI:
* run the query: `select * from dc-int-dwh-dev.metabase_bug_report.issue_35093`
* on the result tab: `Save Results` > `BigQuery Table`

I'm guessing it's possible this bug is actually specific to BigQuery databases. So I think it'd make sense you copy it to BigQuery for debugging purposes.

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/pull/45180
