### ISSUE TITLE
Dashboard Filters - comma keeps getting deleted from input

### ISSUE THREAD

**Issue by samiyabroudi** [metabase/metabase#3510]
This problem happens at the dashboard level, but doesn't happen at the question level (with variables)

Thanks.

**Comment by salsakran** [comment]
is this on numbers or strings?

**Comment by samiyabroudi** [comment]
Numbers

**Comment by attekei** [comment]
Possibly a duplicate of https://github.com/metabase/metabase/issues/5457

**Comment by samiyabroudi** [comment]
It is not. Very separate

**Comment by attekei** [comment]
Could you @samiyabroudi provide steps to reproduce the issue? Thanks!

**Comment by samiyabroudi** [comment]
I believe this issue is from November and was eventually fixed

**Comment by attekei** [comment]
Ah, good to hear. Seems that we are happy with closing this issue.
