### ISSUE TITLE
Messenger notifications bug

### ISSUE THREAD

**Issue by lesniikova** [metabase/metabase#35103]
### Describe the bug

There is a bug when you receive a message on Messenger and you get a little number on the app icon that you have a notification, when you open the message notification was for and close the app, the notification number stays there for quite a while, you have to open and close that conversation a number of times for it to disappear.

### To Reproduce

1. Go to Messenger chat where you have a new unread message
2. Click on that conversation (mark as read)
3. Close the app
4. You can still see that you have unread message
5. Open the conversation again
6. Close the app
7. Notification is still there
8. Repeat a few times and notification icon disappers

### Expected behavior

When you've opened the unread chat, the number for notification on the app icon should disappear

### Logs

No logs, found in mobile device

### Information about your Metabase installation

```JSON
IOS 16.6.1
Messenger 431.0
```

### Severity

This is extremely annoying

**Comment by paoliniluis** [comment]
You’re creating an issue in the Metabase repository which is a BI application
