### ISSUE TITLE
Snowplow: Add a property for `db_version` to database schema and events

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#35119]
## Context
We currently have a `database` schema that houses two events:
- `database_connection_failed`
- `database_connection_successful`

We track a property for the database that was used, but don't include anything around the `db_version` which can be helpful for making product decisions and debugging within the QP team. [More context](https://metaboat.slack.com/archives/C01MC2CKW2G/p1698169258356409).

## Expected Outcome
Add a new property `db_version` to the `database` Snowplow schema and populate it for the two aforementioned events that are housed in the schema right now. If we have the information this can be split up into `engine_version`, `engine_major_version`, and `engine_minor_version`. [More context](https://metaboat.slack.com/archives/C01MC2CKW2G/p1698356655068259?thread_ts=1698169258.356409&cid=C01MC2CKW2G).

**Comment by qnkhuat** [comment]
In case of `database_connection_failed`, it's close to impossible to get the dbms_version. can we ignore it in those cases?

**Comment by qnkhuat** [comment]
we require a connection to get the db version so in case of `database_connection_failed`, we can't get the dbms version.

so it's only available for `database_connection_successful`, is that okay?
