### ISSUE TITLE
Graphing chart with date filter at 24 months is broken 

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#35129]
### Describe the bug

We have a new monthly metric model/table with many metrics as columns per month. When charting with 1 metric by month (no aggregation as it's all aggregated), it works fine until a filter is added for the month to be 24 months. 12 months works and no filter works, but not specific months around 24. It also breaks when aggregated too. Most times, it will look like it works, but if you refresh the page, it breaks. 

When it breaks, it shows this error: Cannot read properties of undefined (reading 'source')

### To Reproduce

1. Make line chart for any metric by a date field
2. Filter date field to last 24 months
3. It might show error now, but if not, refresh the page
4. It breaks with error 

### Expected behavior

Filter by any month should work 

### Logs

TypeError: Cannot read properties of undefined (reading 'source')
    at SVGGElement.<anonymous> (timelines.js:155:26)
    at SVGGElement.<anonymous> (d3.js:792:21)
    at d3.js:962:16
    at Ae (d3.js:968:30)
    at K.each (d3.js:961:12)
    at K.html (d3.js:791:36)
    at timelines.js:153:6
    at iL (timelines.js:240:3)
    at LineAreaBarPostRender.js:402:3
    at pH (LineAreaBarPostRender.js:453:3)
value @ CardRenderer.jsx:97
value @ CardRenderer.jsx:44
fs @ react-dom.production.min.js:212
kc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Go @ react-dom.production.min.js:122
Bc @ react-dom.production.min.js:248
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
...

Visualization.jsx:309 Visualization.jsx:309 Cannot read properties of undefined (reading 'source')
-- | -- | -- | --
  | value | @ | CardRenderer.jsx:98
  | value | @ | CardRenderer.jsx:44
  | fs | @ | react-dom.production.min.js:212
  | kc | @ | react-dom.production.min.js:255
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:19
  | Go | @ | react-dom.production.min.js:122
  | Bc | @ | react-dom.production.min.js:248
  | gc | @ | react-dom.production.min.js:239
  | (anonymous) | @ | react-dom.production.min.js:123
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:19
  | Go | @ | react-dom.production.min.js:122
  | ei | @ | react-dom.production.min.js:123
  | Zo | @ | react-dom.production.min.js:122
  | mc | @ | react-dom.production.min.js:240
  | notify | @ | Subscription.js:16
  | notifyNestedSubs | @ | Subscription.js:88
  | o | @ | Subscription.js:93

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

High as you can't filter for 24 months

**Comment by kulyk** [comment]
This part of the stacktrace makes me think it's about timeline events icons:

```
TypeError: Cannot read properties of undefined (reading 'source')
at SVGGElement. (timelines.js:155:26)
```

[Line 155 in `visualization/lib/timelines.js` file](https://github.com/metabase/metabase/blob/57cd068cf8557667476d6fd0ffe5ceedea573f2d/frontend/src/metabase/visualizations/lib/timelines.js#L155)

**Comment by kulyk** [comment]
I think there's a timeline event with `icon: "balloon"` that is having troubles rendering after #34586

**Comment by ranquild** [comment]
Caused by https://github.com/metabase/metabase/pull/34586 Proposed solution:
- Migrate all `balloons` icons to `cake` for timeline events
