### ISSUE TITLE
Snowplow: Add a property for `pk_generated` to `csv_upload_successful` event

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#35121]
## Context
We currently have a `csv` schema that houses a `csv_upload_successful` event. We want to know how often we are auto-generated PKs. 

## Expected Outcome
Add a new boolean property `pk_generated` to this schema and event. Set to true if we generated a PK and false otherwise.

**Comment by tsmacdonald** [comment]
@cdeweyx happy to implement this as specced, but FYI we already track `generated-columns` in Snowplow. If it's 0 then no PK was added. If it's 1, then it was

**Comment by cdeweyx** [comment]
Once it's reflected in the schema, that would 100% do the trick

**Comment by tsmacdonald** [comment]
Request sent to Joao, it should be in the schema momentarily
