### ISSUE TITLE
Auto split y-axis doesn't work when charting number and percentage types together

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#35127]
### Describe the bug

I have a monthly metric table that has many metrics where I am trying to create a line chart for a percentage and a number fields (month, metric_number, metric_pct). It does work if you summarize it, but the table already contains the metrics so there is no need to do that. 

### To Reproduce

1. Create monthly metric table with a number and pct field
2. Change format style for pct field to show pct
3. Chart the 3 fields (not summarize)
4. Notice the y-axis does not split but takes on the first metric field's format
 

### Expected behavior

y-axis should split for number vs pct

### Logs

n/a

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

Medium as it makes pre-aggregated metrics not usable

**Comment by JesseSDevaney** [comment]
Could not reproduce locally. 

Checking in with Max to see if the issue he had is still occurring before closing the issue.

**Comment by maxzheng** [comment]
Looks to be working now. Closing.
