### ISSUE TITLE
If I don't have SQL writing permission, I should't see the "open editor" button

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3514]
This is the button in question. We should hide this if the user doesn't have SQL editing/writing perms for the given DB.

![screen shot 2016-10-11 at 2 37 03 pm](https://cloud.githubusercontent.com/assets/2223916/19289580/4a92d150-8fc0-11e6-97e7-45021358df03.png)

**Comment by tlrobinson** [comment]
Should we maybe change it to "View query/definition/SQL/source" and make it not editable instead?

**Comment by salsakran** [comment]
+1 to making it viewable but not editable. 

I think life would get really confusing if you can't even see the sql

**Comment by mazameli** [comment]
Yeah, I dig it.

**Comment by salsakran** [comment]
If it's a security issue for someone, hopefully they'll speak up, but in general, we haven't really done the "question definition as an attack target" route.

**Comment by camsaul** [comment]
We don't let people see card definitions if they don't have permissions for it. You can't save a card if you don't have permissions for it either

**Comment by salsakran** [comment]
@camsaul I'm referring to people that have the right to execute the query already. Eg for folks with No SQL access, this card is already hidden. Not sure how much sense it makes to provide another permissions setting (eg, making it "No Access", "Can Execute", "Can Execute + View", "Full Access")

**Comment by camsaul** [comment]
Gotcha.
