### ISSUE TITLE
Email subscriptions do not work

### ISSUE THREAD

**Issue by usrme** [metabase/metabase#35143]
### Describe the bug

After upgrading to v0.47.5 from v0.46.6.4, email subscriptions on a dashboard stopped working. Slack-based subscriptions still work. Clicking "Send email now" seemingly does the correct request as evidenced by the logs:

> 2023-10-27 07:47:22,283 DEBUG middleware.log :: POST /api/pulse/test 200 14.9 s (40 DB calls) App DB connections: 0/4 Jetty threads: 4/50 (1 idle, 0 queued) (56 total active threads) Queries in flight: 0 (0 queued)

But no email arrives despite the dashboard containing questions that have valid answers. The dashboard hasn't changed.

Sending a test email from the administrative section under "Email" works fine, so I am not assuming any fault in the mail provider.

### To Reproduce

I really don't know how to reproduce this as we also have a second Kubernetes deployment with the exact same version of Metabase that also got the v0.46.6.4 -> v0.47.5 upgrade at the same time, but nothing broke there.

### Expected behavior

The email should still be sent.

### Logs

[prune.log](https://github.com/metabase/metabase/files/13187754/prune.log)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.176+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.6 (Debian 13.6-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

This is annoying enough to consider a downgrade back to the previous version in the hopes that it works.

### Additional context

I also tried upgrading to the latest v0.47.6 version, but that didn't change anything. One thing I noticed comparing the two identically versioned Metabase deployments was that just prior to the `POST` request there were entries that are missing from the deployment with the broken email sending:

```text
2023-10-27 06:55:44,955 INFO query-processor.card :: Question's average execution duration is 81.0 ms; using 'magic' TTL of 1000.0 ms
2023-10-27 06:55:45,034 INFO middleware.cache :: Query took 46.0 ms to run; minimum for cache eligibility is 60.0 s
2023-10-27 06:55:46,764 DEBUG middleware.log :: POST /api/pulse/test 200 1.8 s (41 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (2 idle, 0 queued) (142 total active threads) Queries in flight: 0 (0 queued)
```

Now, these may be red herrings, but I don't know enough about Metabase to say that for sure.

**Comment by paoliniluis** [comment]
We don’t have any reports in our entire cloud about this (a few thousand instances), so I would double check what’s going on at your smtp gateway’s

**Comment by usrme** [comment]
@paoliniluis, wouldn't you expect the test email from the admin section of Metabase to fail as well then or do the two have distinct mechanisms for sending emails? Those test emails continue to go through as expected.

**Comment by paoliniluis** [comment]
Nope, because that’s exactly how spam filters work. E.g: try sending yourself an email from a different address with words like “casino online” and a shady URL. The trick is that they score the emails based on contents and that leads the filters to catalog if a certain email is spam or not

**Comment by Crayon-ShinChan** [comment]
https://discourse.metabase.com/t/can-send-invitation-email-but-not-dashboard-subscription-email/44676

I have the same issue

self-host, version as follows. I can send the email for invitation, it works. and my email provider log show me they sent the email for invitation.

but for dashboard subscription. I test it by clicking "Send email now" in dashboard page, and the API return is 200 (see the log below). But I check the log in my Email Provider, there is no record for sending this email, which means although Metabase API returns 200, but the email was not sent.


```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.4.0-1018-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.16 (Ubuntu 12.16-0ubuntu0.20.04.1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```


```
[b84974d6-29d6-4e16-a4f8-b356b7be2d73] 2023-11-05T14:35:33-08:00 DEBUG metabase.server.middleware.log GET /api/task 200 301.4 ms (2 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (5 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[b84974d6-29d6-4e16-a4f8-b356b7be2d73] 2023-11-05T14:35:44-08:00 DEBUG metabase.server.middleware.log GET /api/task/15 200 42.9 ms (3 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (6 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)
[b84974d6-29d6-4e16-a4f8-b356b7be2d73] 2023-11-05T14:36:02-08:00 INFO metabase.query-processor.card Question's average execution duration is 1.3 s; using 'magic' TTL of 13.0 s 💾
[b84974d6-29d6-4e16-a4f8-b356b7be2d73] 2023-11-05T14:36:02-08:00 INFO metabase.query-processor.middleware.cache Query took 244.0 ms to run; minimum for cache eligibility is 60.0 s
[b84974d6-29d6-4e16-a4f8-b356b7be2d73] 2023-11-05T14:36:20-08:00 DEBUG metabase.server.middleware.log POST /api/pulse/test 200 18.6 s (38 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (5 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[b84974d6-29d6-4e16-a4f8-b356b7be2d73] 2023-11-05T14:36:31-08:00 DEBUG metabase.server.middleware.log GET /api/task/info 200 77.9 ms (0 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (5 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued)
```

**Comment by Crayon-ShinChan** [comment]
and when I login again in another browser. the setting for email subscription will disappear. seems it's not saved in db? @paoliniluis

**Comment by Crayon-ShinChan** [comment]
Apart from the deployment in Docker in Ubuntu. I also reproduce in my Mac (install by Jar)

1. Download Jar and install Metabase
2. Configure email setting, I use [Resend](https://resend.com/docs/send-with-smtp). It provide 100 free emails every day.
3. Test invitation email (success), there is record In Resend with Status 200.
4. Create a dashboard from sample database then test email in dashboard setting page. No record in Resend, but `POST /api/pulse/test 200` in Metabase

Therefore, I think this is the bug for Metabase v0.47.6 @paoliniluis 

Version detail:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+9-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+9-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.0",
    "user.language": "en",
    "user.timezone": "America/Vancouver"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
@Crayon-ShinChan repro? Can you detail specifically how to create the dashboard? I’m not able to reproduce this locally even if I create any kind of dashboard

**Comment by paoliniluis** [comment]
@tambetliiv can you specify which?

**Comment by tambetliiv** [comment]
@paoliniluis i was commenting original issue as I had the same sypmtoms and then asked my SMTP provider and they stated that they do not send transactional emails to BCC addresses at all. So it will be very welcome if this would be configurable to specify whether to use BCC, CC or TO.

**Comment by Crayon-ShinChan** [comment]
> @Crayon-ShinChan repro? Can you detail specifically how to create the dashboard? I’m not able to reproduce this locally even if I create any kind of dashboard

just choose a table from sample database, then create a viz then save it in dashboard. Which viz does not matter. Did you try “Resend” as email provider?
