### ISSUE TITLE
Getting error while adding new user

### ISSUE THREAD

**Issue by Ravikapadne** [metabase/metabase#35140]
### Describe the bug

Reference to: https://github.com/metabase/metabase/issues/34679

upgraded Metabase to version 0.45.0 ten days ago. Initially, it was functioning without any issues. However, starting today, we have encountered the same error once more when attempting to add a new user in Metabase

PFB error:

Referential integrity constraint violation: "CORE_USER_COPY_5_20_FK_PERMISSIONS_GROUP_MEMBERSHIP_USER_ID: PUBLIC.PERMISSIONS_GROUP_MEMBERSHIP FOREIGN KEY(USER_ID) REFERENCES PUBLIC.CORE_USER_COPY_5_20(ID) (1305)"; SQL statement: INSERT INTO "PERMISSIONS_GROUP_MEMBERSHIP" ("USER_ID", "GROUP_ID") VALUES (1305, 1) [23506-197]

Also, we have not added anything in the application metadata
how do we fix this issue, can anyone help?

### To Reproduce

install v0.45.0

### Expected behavior

User should be added

### Logs

[8cdb8612-e45c-40d5-b1c8-bb986c110f5e] 2023-10-27T13:44:05+05:30 INFO metabase.query-processor.middleware.cache Query took 71.0 ms to run; minimum for cache eligibility is 13.3 mins
[8cdb8612-e45c-40d5-b1c8-bb986c110f5e] 2023-10-27T13:44:05+05:30 DEBUG metabase.server.middleware.log POST /api/card/1223/query 202 [ASYNC: completed] 81.8 ms (13 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (1 idle, 0 queued) (195 total active threads) Queries in flight: 2 (0 queued); postgres DB 3 connections: 1/2 (0 threads blocked)
[8cdb8612-e45c-40d5-b1c8-bb986c110f5e] 2023-10-27T13:44:05+05:30 WARN metabase.events.view-log Failed to process activity event. :card-query #error {
 :cause Referential integrity constraint violation: "CORE_USER_COPY_5_1_FK_VIEW_LOG_REF_USER_ID: PUBLIC.VIEW_LOG FOREIGN KEY(USER_ID) REFERENCES PUBLIC.CORE_USER_COPY_5_1(ID) (1146)"; SQL statement:
INSERT INTO "VIEW_LOG" ("TIMESTAMP", "USER_ID", "MODEL", "MODEL_ID", "METADATA") VALUES (now(), 1146, ?, 1223, ?) [23506-197]
 :via
 [{:type org.h2.jdbc.JdbcSQLException
   :message Referential integrity constraint violation: "CORE_USER_COPY_5_1_FK_VIEW_LOG_REF_USER_ID: PUBLIC.VIEW_LOG FOREIGN KEY(USER_ID) REFERENCES PUBLIC.CORE_USER_COPY_5_1(ID) (1146)"; SQL statement:
INSERT INTO "VIEW_LOG" ("TIMESTAMP", "USER_ID", "MODEL", "MODEL_ID", "METADATA") VALUES (now(), 1146, ?, 1223, ?) [23506-197]
   :at [org.h2.message.DbException getJdbcSQLException DbException.java 357]}]
 :trace
 [[org.h2.message.DbException getJdbcSQLException DbException.java 357]
  [org.h2.message.DbException get DbException.java 179]
  [org.h2.message.DbException get DbException.java 155]
  [org.h2.constraint.ConstraintReferential checkRowOwnTable ConstraintReferential.java 332]
  [org.h2.constraint.ConstraintReferential checkRow ConstraintReferential.java 274]
  [org.h2.table.Table fireConstraints Table.java 995]
  [org.h2.table.Table fireAfterRow Table.java 1013]
  [org.h2.command.dml.Insert insertRows Insert.java 192]
  [org.h2.command.dml.Insert update Insert.java 134]
  [org.h2.command.CommandContainer update CommandContainer.java 102]
  [org.h2.command.Command executeUpdate Command.java 261]
  [org.h2.jdbc.JdbcPreparedStatement executeUpdateInternal JdbcPreparedStatement.java 199]
  [org.h2.jdbc.JdbcPreparedStatement executeUpdate JdbcPreparedStatement.java 153]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeUpdate NewProxyPreparedStatement.java 1502]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__21546 invoke jdbc.clj 979]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys invokeStatic jdbc.clj 1007]
  [clojure.java.jdbc$db_do_execute_prepared_return_keys invoke jdbc.clj 963]
  [clojure.java.jdbc$db_do_prepared_return_keys invokeStatic jdbc.clj 1038]
  [clojure.java.jdbc$db_do_prepared_return_keys invoke jdbc.clj 1015]
  [clojure.java.jdbc$db_do_prepared_return_keys invokeStatic jdbc.clj 1040]
  [clojure.java.jdbc$db_do_prepared_return_keys invoke jdbc.clj 1015]
  [toucan.db$simple_insert_many_BANG_$iter__23446__23450$fn__23451$fn__23452 invoke db.clj 607]
  [toucan.db$simple_insert_many_BANG_$iter__23446__23450$fn__23451 invoke db.clj 605]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.core$seq__5467 invokeStatic core.clj 139]
  [clojure.core$dorun invokeStatic core.clj 3134]
  [clojure.core$doall invokeStatic core.clj 3149]
  [clojure.core$doall invoke core.clj 3149]
  [toucan.db$simple_insert_many_BANG_ invokeStatic db.clj 604]
  [toucan.db$simple_insert_many_BANG_ invoke db.clj 590]
  [toucan.db$simple_insert_BANG_ invokeStatic db.clj 637]
  [toucan.db$simple_insert_BANG_ invoke db.clj 626]
  [toucan.db$insert_BANG_ invokeStatic db.clj 654]
  [toucan.db$insert_BANG_ invoke db.clj 641]
  [toucan.db$insert_BANG_ invokeStatic db.clj 657]
  [toucan.db$insert_BANG_ doInvoke db.clj 641]
  [clojure.lang.RestFn invoke RestFn.java 731]
  [metabase.events.view_log$record_view_BANG_ invokeStatic view_log.clj 27]
  [metabase.events.view_log$record_view_BANG_ invoke view_log.clj 23]
  [metabase.events.view_log$handle_view_event_BANG_ invokeStatic view_log.clj 39]
  [metabase.events.view_log$handle_view_event_BANG_ invoke view_log.clj 33]
  [metabase.events$start_event_listener_BANG_$fn__41765$state_machine__17099__auto____41772$fn__41775 invoke events.clj 98]
  [metabase.events$start_event_listener_BANG_$fn__41765$state_machine__17099__auto____41772 invoke events.clj 98]
  [clojure.core.async.impl.ioc_macros$run_state_machine invokeStatic ioc_macros.clj 978]
  [clojure.core.async.impl.ioc_macros$run_state_machine invoke ioc_macros.clj 977]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invokeStatic ioc_macros.clj 982]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invoke ioc_macros.clj 980]
  [clojure.core.async.impl.ioc_macros$take_BANG_$fn__17117 invoke ioc_macros.clj 991]
  [clojure.core.async.impl.channels.ManyToManyChannel$fn__13309 invoke channels.clj 139]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 628]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__13196$fn__13197 invoke concurrent.clj 29]
  [clojure.lang.AFn run AFn.java 22]
  [java.lang.Thread run Thread.java 829]]}
[8cdb8612-e45c-40d5-b1c8-bb986c110f5e] 2023-10-27T13:44:19+05:30 WARN metabase.events.view-log Failed to process activity event. :card-query #error {
 :cause Referential integrity constraint violation: "CORE_USER_COPY_5_1_FK_VIEW_LOG_REF_USER_ID: PUBLIC.VIEW_LOG FOREIGN KEY(USER_ID) REFERENCES PUBLIC.CORE_USER_COPY_5_1(ID) (1146)"; SQL statement:
INSERT INTO "VIEW_LOG" ("TIMESTAMP", "USER_ID", "MODEL", "MODEL_ID", "METADATA") VALUES (now(), 1146, ?, 1223, ?) [23506-197]
 :via
 [{:type org.h2.jdbc.JdbcSQLException
   :message Referential integrity constraint violation: "CORE_USER_COPY_5_1_FK_VIEW_LOG_REF_USER_ID: PUBLIC.VIEW_LOG FOREIGN KEY(USER_ID) REFERENCES PUBLIC.CORE_USER_COPY_5_1(ID) (1146)"; SQL statement:
INSERT INTO "VIEW_LOG" ("TIMESTAMP", "USER_ID", "MODEL", "MODEL_ID", "METADATA") VALUES (now(), 1146, ?, 1223, ?) [23506-197]
   :at [org.h2.message.DbException getJdbcSQLException DbException.java 357]}]
 :trace

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7-post-Ubuntu-0ubuntu118.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7-post-Ubuntu-0ubuntu118.04.1",
    "os.name": "Linux",
    "os.version": "5.4.0-1103-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "athena",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-03",
      "tag": "v0.45.0",
      "branch": "release-x.45.x",
      "hash": "4e41d76"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

### Severity

high

**Comment by paoliniluis** [comment]
Creating issues won’t make the debugging and fixing of this issue faster, in fact it will make it slower since we’re losing time from our entire team having to review things that are in different places. Please continue the conversation in the old thread or post this in the correct place which is the discourse forum
