### ISSUE TITLE
[MLv2] [Bug] BE - Date filters with time zone offset values don't work

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#35153]
Steps:
- Open product table
- Click on any Created At cell -> Filter by -> Equals
- Go to the notebook editor

Notes:
- The datetime value comes from `/api/dataset` endpoint and is not processed by the FE in any way 

<img width="1157" alt="Screenshot 2023-10-27 at 15 47 50" src="https://github.com/metabase/metabase/assets/8542534/8a2b029d-c531-40d2-aa67-81e470eafb78">
<img width="1728" alt="Screenshot 2023-10-27 at 14 21 36" src="https://github.com/metabase/metabase/assets/8542534/24b9d300-358b-45a8-98b0-71f0181c4fda">

**Comment by ranquild** [comment]
FE fix https://github.com/metabase/metabase/pull/35167

**Comment by snoe** [comment]
BE part was fixed by #35075

<img width="1217" alt="image" src="https://github.com/metabase/metabase/assets/105012/2ea8ac61-89e1-4518-8790-d502b615983f">
