### ISSUE TITLE
null strings appear in x-ray titles

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#35170]
### Describe the bug

When a `year` filter is used, the title shows `null` instead of `year`:
<img width="1157" alt="image" src="https://github.com/metabase/metabase/assets/8381441/8cb3039f-8891-42e2-b042-87037427b30c">

### To Reproduce

1. Go to `Browse Data`
2. Select `Sample Database`
3. Select `Orders`
4. Click `Summarize`
5. Group by `Created At by year`

At this point you should see this chart:
<img width="1157" alt="image" src="https://github.com/metabase/metabase/assets/8381441/7ebebeee-3ddc-42de-b06b-858329c8a2c2">

6. Click on any chart point
7. Select `Automatic Insights...`
8. Select `X-ray`

You will see an x-ray with a null in the title like "A closer look at number of Orders where null of Created At is 2025"

### Expected behavior

It should show the unit of "year" instead of null.

### Information about your Metabase installation

```JSON
Latest master
```

### Severity

Low

**Comment by nemanjaglumac** [comment]
Related
https://github.com/metabase/metabase/issues/15737

**Comment by paoliniluis** [comment]
Flagging it as a regression based on what Nemanja mentioned before

**Comment by markbastian** [comment]
While they look the same, I think this `null` is in a different place in the name title than the other, so I'm not sure it's a regression. It has to do with the `:year` temporal unit not being matched (which I don't think ever was). Fix coming very soon....
