### ISSUE TITLE
I shouldn't see the edit actions menu for the special permissions groups

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3517]
Currently, we're doing this if you try to remove or edit the name of the Administrators or All Users groups:

![screen shot 2016-10-11 at 3 09 54 pm](https://cloud.githubusercontent.com/assets/2223916/19290493/d7030b74-8fc4-11e6-87ef-fcbd695ebbec.png)

Instead we should either hide or disable the "…" button next to those two groups.

**Comment by salsakran** [comment]
looks good.
