### ISSUE TITLE
add id to dashboard filter controls

### ISSUE THREAD

**Issue by ihorizons2022** [metabase/metabase#35193]
<img width="408" alt="image" src="https://github.com/metabase/metabase/assets/121672603/5165a557-5bd1-44e2-b4df-f1353c43f7c1">
Now, Labels of dashboard filter are used to pass parameter to embed dashboard.
it is preferred to add id to dashboard filter and use id as parameters, not label.

**Comment by paoliniluis** [comment]
Please describe with more detail, examples, context and why you need this. Thanks
