### ISSUE TITLE
breakoutableColumns from MLv2 takes more than 600ms to execute for some questions

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#35205]
### Describe the bug

When opening the summarize sidebar from the query builder for at least some questions, it takes a lot of time to open. I debugged this issue and the root cause is `breakoutableColumns`. We can this function only once when opening the sidebar, there is nothing we can optimize on the FE.

### To Reproduce

1. Go to https://stats.metabase.com/model#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyNiwidHlwZSI6InF1ZXJ5IiwicXVlcnkiOnsib3JkZXItYnkiOltbImRlc2MiLFsiZmllbGQiLCJjb3VudCIseyJiYXNlLXR5cGUiOiJ0eXBlL0JpZ0ludGVnZXIifV1dXSwiZmlsdGVyIjpbIj4iLFsiZmllbGQiLCJjb3VudCIseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIifV0sMV0sInNvdXJjZS1xdWVyeSI6eyJhZ2dyZWdhdGlvbiI6W1siY291bnQiXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsNTI5OTE3LHsiYmFzZS10eXBlIjoidHlwZS9VVUlEIn1dXSwic291cmNlLXRhYmxlIjoiY2FyZF9fNjE4MyIsImZpbHRlciI6WyI9IixbImZpZWxkIiw1Mjk5MzAseyJiYXNlLXR5cGUiOiJ0eXBlL0Jvb2xlYW4ifV0sdHJ1ZV19fX0sImRpc3BsYXkiOiJiYXIiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsiY291bnQiXSwiZ3JhcGgubWV0cmljcyI6WyJjb3VudCJdLCJncmFwaC5zZXJpZXNfb3JkZXJfZGltZW5zaW9uIjpudWxsLCJncmFwaC5zZXJpZXNfb3JkZXIiOm51bGx9LCJvcmlnaW5hbF9jYXJkX2lkIjo2MTgzfQ==
2. Click on 'Summarize'
3. See the performance issue

### Expected behavior

It should open instantly

### Information about your Metabase installation

```JSON
- Chrome 118
```

### Severity

P1. The model has 24 columns, nothing crazy.

**Comment by bshepherdson** [comment]
Has anyone got a reliable repro for this that isn't on stats? I've seen long runtimes for `breakoutableColumns` occasionally, but it seems like it's usually been because of the devtools being open and so on. It's hard to debug on stats itself with the obfuscated code.

**Comment by bshepherdson** [comment]
Further digging on Stats despite the obfuscation has shown that the runtime is dominated (eg. 1048 of 1227ms) by `display_info` calls. That gives me something I can debug into and measure locally, to see where the time is going and what measures we can take to improve it.
