### ISSUE TITLE
Sometimes Getting Permission Error even when I am admin and have all the options.

### ISSUE THREAD

**Issue by stockarea** [metabase/metabase#35227]
### Describe the bug

I copied the SQL from the query builder editor and then wanted to edit out something on it so started a new SQL query but when I copy paste that SQL from query builder I get permission error. 

![image](https://github.com/metabase/metabase/assets/51982217/9ab5553c-7bf7-4665-9b4b-79a7ab9a1345)

This is the query, when I am running getting error like this.

![image](https://github.com/metabase/metabase/assets/51982217/60c8703b-639b-4263-9d19-4009bc50cfa8)

This query is working perfectly normal in MySQL Workbench.

### To Reproduce

1. Frame a new question through query build
2. Generate Some query having some filters and group by and summations etc.
3. Copy paste the SQL generated and then have a 'New Sql Query'

### Expected behavior

It should run as it is running from Query Builder Editor.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "6.2.0-1012-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.38-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Medium

**Comment by luizarakaki** [comment]
We will need very specific reproduction steps because this doesn't happen always...
