### ISSUE TITLE
Slack based pulse testing claims to fail, but sends anyway

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#3523]
1. Add a slack bot token to metabase.
2. Create a new pulse. I named it "Test" (for good measure) and added a single line chart card from the sample dataset.
3. Pick a slack channel, in this case why not send to the fine folks in #general. I also chose hourly.
4. Let's see if it works. 
5. It says sending... for a bit... and then we get the "Send failed" error state of the button.
6. Metabase is like the little engine that could and sends the pulse to the appropriate slack channel anyway.

Tested on latest Chrome on OSX with rc-0.20.0

**Comment by flamber** [comment]
Closing, since this was likely fixed before 0.20
