### ISSUE TITLE
Keep permission group in view when setting it to limited access

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3524]
If I have enough permission groups such that I have to scroll horizontally to see them all, and then I change a group's access to an item to `limited`, when I'm taken to the next screen to choose the items I want them to have access to, my scroll position is reset, so I have to scroll horizontally again to see the group I was trying to modify.

It would be great if the horizontal scroll position was maintained between these two views.

**Comment by flamber** [comment]
Closing, since Permissions was completely revamped in 0.41: https://www.metabase.com/blog/Metabase-0.41/index.html
