### ISSUE TITLE
Don't show formatting options in table header when viewing raw table

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#35244]
### Describe the bug

When viewing a the raw table behind a visualization, you still have access to the drill thrus and click actions on the table. However, some click actions can modify the viz settings, specifically the column formatting. Clicking on this will display the column formatting options, however you are unable to change any of them. 

### To Reproduce

1. New -> Question -> Orders
2. Count by Created At -> Visualize
3. Click the raw table toggle at the bottom of the visualization
4. On the table header, click Count, and select the gear icon in the popover
5. Try changing any of the column settings from here

### Expected behavior

Since the changes can't be applied, we shouldn't show this option

### Information about your Metabase installation

```JSON
Current Master
```

### Severity

Not very severe, but somewhat annoying

**Comment by darksciencebase** [comment]
https://github.com/metabase/metabase/pull/35114 ?

**Comment by npfitz** [comment]
Yup! Originally Ryan had it linked to #16999, but while it's related, isn't quite the same. So I wanted to create a new issue so we didn't close out something with a partial fix

**Comment by npfitz** [comment]
Resolved in https://github.com/metabase/metabase/issues/33841
