### ISSUE TITLE
"Goal" line is cut off on charts

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3525]
On 0.20.0 RC with Chrome on OS X. I can only see the bottom half of the word and can't scroll it into view. This only happens if the Goal is greater than the max value of the chart

![screen shot 2016-10-11 at 4 04 52 pm](https://cloud.githubusercontent.com/assets/1455846/19291827/7b3059c0-8fcc-11e6-8ae5-51320ed4809f.png)

**Comment by camsaul** [comment]
I can only see the bottom half of the word

**Comment by tlrobinson** [comment]
This should be fixed in `master`.
