### ISSUE TITLE
Quantity type is still being sorted as text when db type is varchar

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#35263]
### Describe the bug

I have a "score" field with values from 0 to 10, which is mistakenly stored as varchar when ingested by Fivetran. In Metabase, the metadata type has been changed to Quantity, so it is possible to use it as a number. However when it is grouped, it sorts as text instead of int where 10 is after 1 instead of 9. 

### To Reproduce

1. Add table with a varchar/text field that contains numbers
2. Change metadata type to Quantity 
3. Group by the field and sort by it. Notice it is sorted alphabetically instead of numerically. 

### Expected behavior

It should sort numerically since the type is Quantity 

### Logs

n/a

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

Requires DBA / db owner to fix type

**Comment by dpsutton** [comment]
I don't think this is a bug. varchar is a text field. Marking something as a quantity doesn't change this fact.

**Comment by paoliniluis** [comment]
Agree with @dpsutton, we can't do nothing here till we implement some sort of casting on the base types

**Comment by maxzheng** [comment]
@dpsutton Isn't that the whole point of the metadata type so that Metabase can be smart / do the conversion / treat it as certain types even if the underlying type is wrong -- therefore the users don't need to involve DBA / other data professions? 

I will ask another way, how does Metabase help users treat text as another type? The only place is metadata type or as a model. Model doesn't have any way to convert types unless you switch to SQL, which isn't something that business users should do. So it's a feature gap if not a bug.

**Comment by paoliniluis** [comment]
@maxzheng is this issue the same as https://github.com/metabase/metabase/issues/18974?

**Comment by ignacio-mb** [comment]
When I change the Field Type, I would expect Metabase to treat the field as the thing you converted and not have to build a Custom Expression to workaround. 
Or what for Metabase gives you the possibility to change the type?

**Comment by ignacio-mb** [comment]
Closing as not planned in favor of https://github.com/metabase/metabase/issues/36049
