### ISSUE TITLE
Can't remove "Goal" line from Chart

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3526]
If you clear out Goal value it just resets to 0 giving you a silly goal at the bottom of the chart

![screen shot 2016-10-11 at 4 07 53 pm](https://cloud.githubusercontent.com/assets/1455846/19291887/e6f3446a-8fcc-11e6-8ba3-d2f954903528.png)

**Comment by tlrobinson** [comment]
![screenshot 2016-10-11 16 09 13](https://cloud.githubusercontent.com/assets/18193/19291918/23124e50-8fcd-11e6-8fcb-00f8a1c3a797.png)

**Comment by camsaul** [comment]
Oops.
