### ISSUE TITLE
The second parameter of function convert_tz() in the SQL generated by query is incorrect

### ISSUE THREAD

**Issue by li-xiaolu** [metabase/metabase#35274]
### Describe the bug

Data Analysis>Dashboard Settings>Select the tables in the GUI from the custom display and combine them for filtering. Click the "Results" button to display the data smoothly, and then click "Browse SQL" to go from "Show SQL Editor" to "Run Query". Even if the SQL is not modified, "No Results Found" (the third screenshot) will be displayed.
After investigation, it was found that the second parameter of function convert_tz() in the generated SQL was incorrect.
wrong:
 convert_tz('2023-10-18 00:00:00.000', 'GMT+09:00', @@session.time_zone)
correct:
 convert_tz('2023-10-18 00:00:00.000', '+09:00', @@session.time_zone)

![image](https://github.com/metabase/metabase/assets/115760863/4488349b-609b-4904-891a-77a92b7c5c95)
![image](https://github.com/metabase/metabase/assets/115760863/79c623d4-eb6e-44ed-a2b6-356089a3833f)
![image](https://github.com/metabase/metabase/assets/115760863/f229dd2f-53fb-4041-897f-63a1bddff57e)
![image](https://github.com/metabase/metabase/assets/115760863/c57da6c0-1b97-49ef-844d-170fb5bf51b2)
![image](https://github.com/metabase/metabase/assets/115760863/04a48f7f-20f3-478b-847a-1ddf50544244)
![image](https://github.com/metabase/metabase/assets/115760863/3fda97e7-33ae-441c-b01a-4a58292725c5)
![image](https://github.com/metabase/metabase/assets/115760863/70df4677-100e-4188-9ce5-aad194921a3c)

### To Reproduce

1. Data Analysis>Dashboard Settings>Select the tables in the GUI from the custom display and combine them for filtering
2. Click the "Results" button to display the data smoothly
3. Click "Browse SQL" to go from "Show SQL Editor" to "Run Query".
4. Even if the SQL is not modified, "No Results Found" (the third screenshot) will be displayed.

### Expected behavior

Correctly represent search results

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ja",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+9-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+9-LTS",
    "os.name": "Linux",
    "os.version": "5.10.192-183.736.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Japan"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.26"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-25",
      "tag": "vUNKNOWN",
      "branch": "stg",
      "hash": "7592fec"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

**Comment by paoliniluis** [comment]
Which version of Metabase are you using?

**Comment by li-xiaolu** [comment]
@paoliniluis 
v 0.46.6.4

**Comment by paoliniluis** [comment]
@li-xiaolu please upgrade to the latest version and check if this still exists

**Comment by paoliniluis** [comment]
@li-xiaolu, please reproduce with the sample dataset as well, otherwise we won't be able to address this issue

**Comment by li-xiaolu** [comment]
@paoliniluis 
This issue is no longer present in the latest version.
Thank you.
