### ISSUE TITLE
Add Reminder to Add Milestones to closed PRs

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#35299]
To make [using milestones more](https://www.notion.so/metabase/Let-s-Use-Milestones-More-84b11b0352744da9ae3555bd1cecae2c) easier

**Comment by darksciencebase** [comment]
I thought we add them to the issues and not PRs because the issues tend to have more user-facing descriptions of themselves in the title. Is it possible to go to the linked issue and block the PR until that one is milestoned?
