### ISSUE TITLE
hide/show columns in a table view takes more than 4 seconds

### ISSUE THREAD

**Issue by psalinasy** [metabase/metabase#35296]
### Describe the bug

When making a join, hide/show columns take around 4 seconds. 
https://www.loom.com/share/dfcbb6c072b94e069e6c7234ad967740?sid=cf5e93cc-7200-495b-81a3-a1a06b61a27f

### To Reproduce

1. Join 2 tables 
2. Click on Settings 
3. Change the visibility of a column (hide/show a column)
4. Wait until the change is applied 

### Expected behavior

It should hide/show without delay

### Information about your Metabase installation

```JSON
Browser: Chrome
Metabase version: master
```

### Severity

p1

**Comment by darksciencebase** [comment]
should be fixed by https://github.com/metabase/metabase/pull/35418
