### ISSUE TITLE
Disable /api/health logging via an env var

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35338]
**Is your feature request related to a problem? Please describe.**
Having the health endpoint report on the logs is great, we can now see when a load balancer hits the instance so we're not blind on cloud environments. But this can be also a problem for log aggregators: it clogs our logs with lines that are not useful so we end up paying more money for something we don't probably need after the initialization

**Describe the solution you'd like**
an env var to disable the GET /api/health logging

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Important for debugging

**Additional context**
NA

**Comment by dpsutton** [comment]
relevant:
- issue to surface these logs: https://github.com/metabase/metabase/issues/14964
- PR closing that: https://github.com/metabase/metabase/pull/31081/files

We need to add a knob to make this conditional
