### ISSUE TITLE
Undo in native editor goes back to blank / too far

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#35344]
### Describe the bug

I have a saved question that's in native editor. When using cmd+z to undo, it will continue until the editor becomes blank instead of stopping at the saved state. 

### To Reproduce

1. Open a saved SQL query question
2. cmd+z to undo
3. Editor is now blank

### Expected behavior

It should undo until the last saved state and not blank

### Logs

n/a

### Information about your Metabase installation

```JSON
master on Postgres
```

### Severity

Just annoying / need to click on question again to reopen

**Comment by oleggromov** [comment]
Reproducible on 926b04a1d5377798b0bbb98ef6b28ddac3210c89
