### ISSUE TITLE
Bugs on the "Audit" page

### ISSUE THREAD

**Issue by nomorethat** [metabase/metabase#35357]
### Describe the bug

1) The left menu is different from the other pages (Settings, People, Troubleshooting). Is it a bug?

![ksnip_20231103-133438](https://github.com/metabase/metabase/assets/46302088/b3b77c78-a632-4501-8b55-cbc08f653e62)

![ksnip_20231103-133448](https://github.com/metabase/metabase/assets/46302088/91ac7ffd-df98-4304-8d1b-965d3b31ad59)

2) Audit -> Question: missing localization (ttag)

![ksnip_20231103-133649](https://github.com/metabase/metabase/assets/46302088/afb597b0-2c99-4dcc-8afd-3d15602d3765)

![ksnip_20231103-133744](https://github.com/metabase/metabase/assets/46302088/a305713b-7513-44e5-9af4-7b2c0ee6bd04)

![ksnip_20231103-133818](https://github.com/metabase/metabase/assets/46302088/0d272662-e73d-493d-b2ee-7013db4207b5)

3) Some charts don't work

Audit -> Questions
![ksnip_20231103-134557](https://github.com/metabase/metabase/assets/46302088/a2638030-1f34-4fe7-bec3-be7f2ee5bc93)

Audit -> Dashboards
![ksnip_20231103-134613](https://github.com/metabase/metabase/assets/46302088/f97e2d6b-7805-4fe0-9067-e010cda8f432)

4) Audit -> Questions -> All questions: when sorting, the width of the columns changes

![Peek 2023-11-03 13-49](https://github.com/metabase/metabase/assets/46302088/37b02466-0096-45cb-8a96-75917d9a67f4)

### To Reproduce

1. Go to 'Admin Settings'
2. Click on 'Audit'
3. See "Questions"
4. See "Dashboards"

### Expected behavior

1) The menu is the same as on the Settings, People, Troubleshooting pages 2) Localization works 3) Charts are working 4) The columns of the table are fixed 

### Information about your Metabase installation

```JSON
v1.47.3
```

### Severity

It's not critical for me. Just noticed, decided to pay attention to it.

**Comment by paoliniluis** [comment]
Hi, please upgrade to the latest version and also check how the feature works.

Also, if you're using the enterprise version, please write to our support email
