### ISSUE TITLE
Adding a tab to a dashboard makes the dashboard shows double in collection view

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#35351]
### Describe the bug

Adding a tab to a dashboard makes the dashboard shows double in collection view. This has been tested on a fresh Metabase  instance, though this occurred with my usual testing instance as well.

### To Reproduce

1. Create a dashboard, after it's created and is in edit mode, click cancel (not sure it has any implication, but I did that)
2. Go to the root collection. See that there is only 1 dashboard
    ![Screenshot 2023-11-03 at 4 41 28 PM](https://github.com/metabase/metabase/assets/1937582/8d8a7ec6-e14a-4538-a238-ff46134d7377)
4. Go to the dashboard again, edit, add a tab and save
5. Go to the root collection. Now you'll see 2 dashboards with the same name
    ![Screenshot 2023-11-03 at 4 41 39 PM](https://github.com/metabase/metabase/assets/1937582/2fbcef24-92f1-41f6-8d14-5e0a903a429e)
7. Refresh the page, it still shows 2 dashboards
8. Archive the dashboard, clicking one will automatically select the duplicate.
9. Restore the archive dashboard and go to the root collection. You'll only see 1 dashboard.

### Expected behavior

I should only see 1 dashboard each not also its duplicate

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.0",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-10-30",
      "src_hash": "a3c4f2dde12e997149db5929f356c3181ffa94d3",
      "tag": "v1.47.1-SNAPSHOT",
      "hash": "84c16b6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Not blocking but looks super weird and confusing

**Comment by calherries** [comment]
This was caused by my change at https://github.com/metabase/metabase/pull/35406. 

It's caused by a race condition on dashboard save where there can be two "most recent" revisions. I'm about to fix it with this epic anyway https://github.com/metabase/metabase/issues/35209.

Note because it's a race condition, it's difficult to reproduce. I couldn't reproduce it on stats.
