### ISSUE TITLE
Be able to sort the filter values

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35362]
**Is your feature request related to a problem? Please describe.**
We bring the filter values from the backend already sorted ASC, a customer wants to have the possibility of sorting those DESC

**Describe the solution you'd like**
Add the possibility of sorting the filter values on the front end

**Describe alternatives you've considered**
NA

**How important is this feature to you?**
Ergonomics

**Additional context**
NA

**Comment by skboyle** [comment]
@paoliniluis, I just started a branch for this. Any additional info needed?

**Comment by skboyle** [comment]
I should have a PR up later today to tomorrow. :)

**Comment by paoliniluis** [comment]
@skboyle we need product input for this one

**Comment by skboyle** [comment]
<img width="1115" alt="Screenshot 2023-11-10 at 2 23 35 PM" src="https://github.com/metabase/metabase/assets/31743695/35b666d4-1649-4fdf-962a-9605a143bede">
<img width="1113" alt="Screenshot 2023-11-10 at 2 23 44 PM" src="https://github.com/metabase/metabase/assets/31743695/20f7bf2e-1751-4178-917b-d313525a03e5">
<img width="1115" alt="Screenshot 2023-11-10 at 2 23 51 PM" src="https://github.com/metabase/metabase/assets/31743695/0e4da17a-fa68-410b-bea8-1f04066edbff">
<img width="1114" alt="Screenshot 2023-11-10 at 2 24 25 PM" src="https://github.com/metabase/metabase/assets/31743695/4c674a7e-8db5-46dd-9ae1-98e3be3afcf7">


@paoliniluis This is what the functionality I added looks like. The selected tab shows arrows for default, ascending, or descending order. When the user clicked the selected tab the filter list is sorted accordingly. My tests are passing. Unfortunately I'm not able to push my code for review. I believe I'm lacking access. I'm happy to hop on a call with someone and demonstrate what I've done. I plan to apply to Metabase.

**Comment by skboyle** [comment]
I made the mistake of not using a fork. I'll tag you when it's up.

**Comment by skboyle** [comment]
https://github.com/metabase/metabase/pull/35623

**Comment by paoliniluis** [comment]
Just for the record: the feature that the customer requested was to be able to sort the filter values in the dashboard filters:
![image](https://github.com/user-attachments/assets/ed2a4f2c-e9c2-48b3-9237-b9adbf195ee4)

We should be able to make that happen on FE only

**Comment by paoliniluis** [comment]
this one is a duplicate of https://github.com/metabase/metabase/issues/42403
