### ISSUE TITLE
Time zone issues with dates/timestamps [Snowflake]

### ISSUE THREAD

**Issue by sicarul** [metabase/metabase#35368]
### Describe the bug

We're using a Snowflake database with the timezone set to `America/Los Angeles`; most reports which use dates require some special handling because the timezone fields are not handled correctly, example strange behaviors detailed below

### To Reproduce

A very simple example, without using any table; the date filters are offset by 7 hours, instead of being at 00 o'clock:
<img width="442" alt="image" src="https://github.com/metabase/metabase/assets/4952116/acedf860-70cc-4e1f-8547-89ab664bb9b8">

There's also some oddity in how filters work, because for example if i ask for today's "organizations" in this table, i get 0:
<img width="1011" alt="image" src="https://github.com/metabase/metabase/assets/4952116/6ac862e2-5c99-4cd9-b988-5b1ea4a04286">

However if i run this query which metabase claims it's running (Even on metabase itself!), i get 32 results:
```
select count(*)
from core.DIM_ORGANIZATION
where DATE_TRUNC("day", CAST("CORE"."DIM_ORGANIZATION"."CREATED_AT" AS timestamp)) = '2023-11-03 00:00 -07:00'::timestamp_tz
```

My guess is that there's something wrong with how Metabase processes timezones, at least on Snowflake.

### Expected behavior

It should filter correctly with the dates regardless of the chosen timezone

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.192-183.736.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.40-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

### Severity

Very annoying, requires hacks to work with dates / timestamps

**Comment by paoliniluis** [comment]
Can you check if this issue is any of these 3 https://github.com/metabase/metabase/issues?q=is%3Aopen+is%3Aissue+label%3ADatabase%2FSnowflake+label%3AMisc%2FTimezones?

**Comment by sicarul** [comment]
@paoliniluis it might be the same underlying issue as https://github.com/metabase/metabase/issues/8804, but i'm not sure because i don't know the reason that this issue is happening.

**Comment by sicarul** [comment]
You know what, i've just changed the JAVA_TIMEZONE (or user.timezone) to UTC and it works correctly now, it seems this was the source of the issue. Thanks!
