### ISSUE TITLE
GLPI + Metabase

### ISSUE THREAD

**Issue by ajota21** [metabase/metabase#35382]
### Describe the bug

Hello everyone, I have problems with my Metabase plugin integration in GLPI 10+.

When I changed the name of my collections and created some new ones, it stopped updating in my GLPI. 

Metabase 
![image](https://github.com/metabase/metabase/assets/114438238/4298840a-0838-4a4e-9656-ebf07dc3c4c6)

GLPI
![image](https://github.com/metabase/metabase/assets/114438238/d8ece210-9808-49a9-a815-f4cc687ae595)

You can see that the collections are not the same, i.e. they have not been updated in my GLPI despite changing and adding new ones in the Metabase.

### Information about your Metabase installation

```JSON
Metabase v0.44.6
GLPI 10.0.6
```

### Severity

High

**Comment by paoliniluis** [comment]
@ajota21 you need to ask GLPI, this is not a bug in Metabase
