### ISSUE TITLE
If multiple parameters target a single SQL field filter variable only one is applied

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#3539]
If you have two filter widgets on a dashboard and both of them are wired to the same SQL field filter variable and both are active, only one of them is actually applied to the query:

In this screenshot both widgets are wired to both cards, which are equivalent (GUI "Count of rows" of "Orders" and SQL `SELECT count(*) AS "count" FROM "PUBLIC"."ORDERS" WHERE {{created}}`) and should be returning the same results:

<img width="883" alt="screenshot 2016-10-12 01 58 13" src="https://cloud.githubusercontent.com/assets/18193/19303962/98cfa92e-901f-11e6-9ebb-ff259908246a.png">

Related to #3538

**Comment by camsaul** [comment]
@tlrobinson why are you making everything a Priority/P1 assigning them to me these days...

**Comment by camsaul** [comment]
@metabase/core-developers what is the expected behavior here? When we have two filters applied to the same SQL field filter variable are we supposed to combine them and apply both? I think it makes more sense to only allow one filter at a time

**Comment by camsaul** [comment]
The way the query language is defined you only pass one given value for a field filter variable so the backend probably never even sees both values. The frontend could always combine both into an `:and` filter if that's what's supposed to be happening here

**Comment by tlrobinson** [comment]
@camsaul Regardless of what we allow on the frontend, I feel like the query language should behave consistently across GUI and SQL cards, and it shouldn't silently ignore parameters.

**Comment by salsakran** [comment]
Just to confirm, multiple filters on a single field should always be respected. An example of this being very reasonable would be: A filter on hour of the day (eg, for lunch orders), and another one for the overall time period of interest.

**Comment by camsaul** [comment]
Fixed by #3624
