### ISSUE TITLE
ClickHouse - Cannot search against non-Text Field

### ISSUE THREAD

**Issue by alongls** [metabase/metabase#35401]
### Describe the bug

in the clickhouse DB the column is defined as - LowCardinality(Nullable(String))
in this case when the metabase syncs with the database the field is define as type/* and not as type/Text

when the column in the clickhouse is defined as LowCardinality(String) the field in metabase is described as type/Text

the problem - in a dashboards when trying to define a search again a filed that metabase classified as type/* we get an error (Cannot search against non-Text Field) and the search fails:

error is:
2023-11-05 15:13:09,094 DEBUG middleware.log :: GET /api/dashboard/115/params/7e7fa74e/search/visa 400 64.0 ms (10 DB calls)
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "Cannot search against non-Text Field 144 \"OG_CustomerName\"",
   :data {:status-code 400, :field-id 144, :field "OG_CustomerName", :base-type :type/*},
   :at [metabase.models.params.chain_filter$check_valid_search_field invokeStatic "chain_filter.clj" 601]}],
 :trace
 [[metabase.models.params.chain_filter$check_valid_search_field invokeStatic "chain_filter.clj" 601]
  [metabase.models.params.chain_filter$check_valid_search_field invoke "chain_filter.clj" 592]
  [metabase.models.params.chain_filter$fn__104174$unremapped_chain_filter_search__104179$fn__104180
   invoke
   "chain_filter.clj"
   612]

### To Reproduce

1. in clickhouse define a column as LowCardinality(Nullable(String)) - try to run a search against it 
2. in a dashboard define a search filter against this field . no value will be retrieved (in a question it will retrieve  the data)  
3. change the filed to LowCardinality(String) try to run the search against it and it will sucseed

### Expected behavior

the metabase should read "LowCardinality(String)" as test fields

### Information about your Metabase installation

```JSON
browser - browser - Version 113.0.5672.127 (Official Build) (64-bit)
OS - Windows 10
database - ClickHouse
Metabase version - v0.47.6
metabase hosting - jar file
metabase internal DB - MySQL
clickhouse driver version - 1.2.2
```

### Severity

dashboards are un-operational so upgrade stopper

**Comment by alongls** [comment]
[full error message.TXT](https://github.com/metabase/metabase/files/13259738/full.error.message.TXT)
![Metabase_Metadata](https://github.com/metabase/metabase/assets/46295284/2350008c-0209-4575-9f61-ffb0e2820980)
![ClickHouse Table Definition](https://github.com/metabase/metabase/assets/46295284/1132b67d-bf63-47b5-8621-31b6aa658b52)

**Comment by paoliniluis** [comment]
Please open this issue in https://github.com/ClickHouse/metabase-clickhouse-driver
