### ISSUE TITLE
Using MongoDB, creating a custom expression that operates a number by the Distinct aggregation fails because of lack of $size aggregation

### ISSUE THREAD

**Issue by cubargh** [metabase/metabase#35425]
### Describe the bug

The aggregation pipeline is encountering an error when attempting to use the $divide operator to calculate the ratio of a number to the count of unique elements. The error message received is: "$divide only supports numeric types, not long and array."

When executing the provided MongoDB aggregation pipeline, an error occurs at the $divide stage. The issue seems to stem from the incorrect usage of the $divide operator. The pipeline attempts to divide a numeric value by an array, which is the result of the $addToSet operator. This operation is not supported, as $divide only works with numeric types.

### To Reproduce

1. Create a custom expression like this `Count / Distinct([column])`
2. execute and see error 

### Expected behavior

It should return a number

### Information about your Metabase installation

```JSON
Metabase version: 0.47.6
MongoDB version: 6.0.11
```

### Severity

Medium

**Comment by backtr4ck** [comment]
to fix:

include the $size operator when querying. (Which is used to find the size of the array)

**Comment by backtr4ck** [comment]
`(mu/defn ^:private breakouts-and-ags->projected-fields :- [:maybe [:sequential [:tuple ms/NonBlankString :any]]]
  "Determine field projections for MBQL breakouts and aggregations. Returns a sequence of pairs like
  `[projected-field-name source]`."
  [breakout-fields aggregations]
  (concat
   (for [field-or-expr breakout-fields]
     [(field-alias field-or-expr) (format "$_id.%s" (field-alias field-or-expr))])
   (for [ag aggregations
         :let [ag-name (annotate/aggregation-name (:query *query*) ag)]]
     (let [unwrapped-ag (unwrap-named-ag ag)]
       (cond
         (mbql.u/is-clause? :distinct unwrapped-ag)
         [ag-name {$size (str \$ ag-name)}]

         (mbql.u/is-clause? :size unwrapped-ag)
         [ag-name (format "$_id.%s" (field-alias unwrapped-ag))]

         :else
         [ag-name true])))))
`

I think something like this might work? I'm not familiar with Clojure

**Comment by backtr4ck** [comment]
testing around, it happens with any operation but if I do only `=Distinct([column])` it adds the $size operator correctly.

**Comment by backtr4ck** [comment]
@paoliniluis can this be picked up as a bug? not sure how bugs are handleled here.

**Comment by paoliniluis** [comment]
Done @backtr4ck

**Comment by bshepherdson** [comment]
This seems at least spiritually related to https://github.com/metabase/metabase/issues/14523, that `Distinct` is sort of magic and doesn't play nice with other aggregations and expressions. I'm not sure if the causes are the same between Mongo and other DBs, but perhaps so.
