### ISSUE TITLE
Make the Mac app less confusing/embarassing

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#3544]
When we first released the Mac app we didn't have very many "multi-player" features like Pulses, permissions, etc, so it was a pretty decent "single-player" user experience. That is no longer the case, and the Mac app has become very confusing since many things don't make sense as part of a desktop app, the number one thing being the requirement to create an account (#1185). Forgotten password issues have plagued the Mac app as well.

Things it might make sense to hide:
- Account creation + settings #1185 
- Pulses
- People and Permissions admin sections
- Various settings (Slack, Email, Single Sign-On, Updates, site name/url, email address for help reuqests, etc)
- All of the "Get Connected" steps in the setup guide.
- Getting Started Guide?

Many of these things would just be a matter of adding `if (!window.OSX) { ... }` conditionals around various buttons, etc.

More difficult things it might make sense to add at some point:
- Ability to use the Mac app as a container for external instances (similar to Slack's multiple accounts switcher)
- "1-click" upgrade to a "multi-player" instance

**Comment by salsakran** [comment]
There's also the startup time, which we have only so much control over. I think we need to change the splash screen and actually have something interesting/educational/amusing there.

**Comment by tlrobinson** [comment]
Another possibility is extracting the entire frontend from the jar and immediately serving that on startup, with a modal with something interesting (maybe interactive) while the jar is starting, so it feels a bit more instant.

We could do the same thing for the web app as well. Currently we serve a separate `init.html` but there's no reason we couldn't just serve `index.html` immediately, as long as we handle failed `/api/` requests gracefully.

**Comment by salsakran** [comment]
re: pulses @camsaul there's no way to actually get the mac app to send pulses if the jar isn't running? 

I'd also throw in, that it might make sense to replace those portions with "here's what you get if you run us in the cloud" propaganda. Especially if we get a 1-click upgrade going.

**Comment by tlrobinson** [comment]
@salsakran We could probably use launchd to run a task hourly to send Pulses https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/ScheduledJobs.html#//apple_ref/doc/uid/10000172i-CH1-SW2

Or leave the backend running in the background, which would solve the startup time, but I'm not a fan of that idea given how much memory the backend uses.

**Comment by salsakran** [comment]
Yeah, keeping the backend running in the background doesn't sound like a great idea.

**Comment by salsakran** [comment]
how would that work on Heroku?

**Comment by mazameli** [comment]
Until we have the ability to have the Mac app connect to a real instance as a client, I'm interested in going a lot harder on communicating that the Mac app that is essentially just a demo. We could be clearer on our website, like having the download button say `Try the Metabase demo`, or even breaking it out from the /start/ page and instead putting it next to the `Get started` button to further differentiate it from the "real" deployment options. 

In the app, the splash screen could among other things reiterate the "it's a demo" idea, and like Sameer mentioned we could replace certain sections with messages about running Metabase for real, maybe even going so far as to have a CTA button on those pages that takes you to to the /start/ page.

The one devil's advocate question I have is, is it helping us to have the Mac app at all, while it still doesn't have the ability to connect to a real cloud instance?

**Comment by salsakran** [comment]
I think there's a distinction between "single-player mode" and a "demo". I don't really think of it as a demo, but rather a less crufty alternative to MySQL workbench. 

Maybe we call it "Metabase Solo" or something equivalent?

**Comment by tlrobinson** [comment]
@salsakran On Heroku you can run commands on a schedule https://devcenter.heroku.com/articles/scheduler e.x. tell it to run `java -jar metabase.jar run-hourly-tasks` each hour, which would check for Pulses that need to be sent (and sync databases, etc), and we'd disable those tasks from running in the backend normally.

This would actually be pretty easy I think and is probably worth doing for Heroku, at least. @camsaul should confirm I'm not crazy though.

**Comment by salsakran** [comment]
is there a way to tell heroku to do that as part of the app.json file or do we need to do something wacky?

**Comment by mazameli** [comment]
> Maybe we call it "Metabase Solo" or something equivalent?

Yeah, I could get behind that. Just something to clarify and distinguish it as separate. But I'm also really into the idea of having a for-reals desktop client for multiplayer instances, a la Slack.

**Comment by camsaul** [comment]
I don't think we can really "serve" `index.html` before the JVM is ready since the webserver is part of the JAR. But the app is basically just a `WebView` so that could show a static HTML page while we're waiting for the server to start

**Comment by tlrobinson** [comment]
@camsaul Yeah, that's what I meant to say.

@salsakran There's a way to add the scheduler addon, but I haven't found a way to configure a task :-/

**Comment by mazameli** [comment]
Been noodling on some concepts for how we could replace sections of the Mac App that are nonsensical in single-player mode with info about what you could do if you deployed MB on a server. Beyond this kind of treatment, I also think that the admin checklist page is a great opportunity to tailor that content to a series of steps that would move a user from single-player mode to a real deployment.

Collections permissions modal:

![collection permissions](https://cloud.githubusercontent.com/assets/2223916/24812266/3ad86492-1b7e-11e7-8e72-63cd192ca894.png)

Data access permissions:

![permissions](https://cloud.githubusercontent.com/assets/2223916/24812278/4a060258-1b7e-11e7-8b4c-806d35df164d.png)

Slack settings:

![slack](https://cloud.githubusercontent.com/assets/2223916/24812286/50593bd4-1b7e-11e7-88c9-149d1395ea66.png)

People and Group settings:

![people](https://cloud.githubusercontent.com/assets/2223916/24812295/58ec7428-1b7e-11e7-9b1a-34e016bae160.png)

**Comment by tlrobinson** [comment]
I like it. I don't think we need messages for every "multi-player" feature though, in some cases we can just hide the buttons and streamline the UI. I think there's a tradeoff between pushing users towards "multi player" mode and risking them thinking "oh, yet another thing that doesn't work"

Also, I think the biggest win will be totally bypassing the account creation/login (and avoid password reset issues altogether). We could still show the analytics opt-out and email list sign up though.

**Comment by kdoh** [comment]
@mazameli Where are you thinking `Get started` would take you in these mock ups? 

I think this is a reasonable way to explain the loose ends in the single player experience in the Mac App but I'm a little nervous about a solution that requires us to have to add cases for the single player experience in a bunch of places throughout the app, whether we hide stuff or show messaging.

**Comment by mazameli** [comment]
> @mazameli Where are you thinking Get started would take you in these mock ups?

For now I was thinking it would just go to http://www.metabase.com/start/. In the future, the button would ideally be replaced with one that would start a flow to move your local instance into a remote one.

As for your concerns, yeah, I'm not really sure how else to make the Mac app feel like an intentional, though-out experience without making it diverge from the web app.

**Comment by tlrobinson** [comment]
I'm not too concerned with adding some conditionals, we already have some for certain features that need to be enabled (e.x. embedding), and we can just consolidate all the logic in a "feature-flags" selector file or something.

I think a good heuristic for "hide completely vs. show messaging" is "would the user be interested in this feature if it magically worked in single-player mode?" For example, Pulses and sharing might be useful, but probably not permissions, since there's only one user by definition.

**Comment by flamber** [comment]
Closing, since we are deprecating the Mac App: https://www.metabase.com/blog/Metabase-0.41/#other-news-at-metabase
