### ISSUE TITLE
[MLv2] [BE] - Export functions to parse date and time

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#35447]
Follow up on https://github.com/metabase/metabase/pull/35253

Date parsing gets complex and we need to make sure the FE and CLJS does it in the same way to avoid similar issues in the future. I propose we export functions from CLJS to parse date & time:

```
parseDateTime(input: string): number; // UTC timestamp
parseTime(input: string): number; // UTC timestamp, the "date" part can be arbitrary
```

Examples:
```
parseDateTime("2020-10-20");
parseDateTime("2020-10-20T05:10:20");
parseDateTime("2020-01-05T10:20:00+01:00"); // offset should be ignored

parseTime("10:20");
parseTime("10:20:30");
parseTime("11:08:13.1313");
parseTime("11:08:13.1313Z");
```

**Comment by bshepherdson** [comment]
We already have time/date parsing logic in MLv2, powered by Moment.js or by `java.time.*`, which matches the behavior on the FE. See `metabase.shared.util.time`.

I'll look into exposing these functions appropriately.

**Comment by ranquild** [comment]
I think since we use moment as well maybe there is not much we can do to improve things. I'm ok with closing this task.

**Comment by ranquild** [comment]
@bshepherdson fyi
