### ISSUE TITLE
Label issue after upgrading to v0.20.0.

### ISSUE THREAD

**Issue by genepool99** [metabase/metabase#3545]
I have a dashboard graphs which used to display properly, after upgrading the three labels just say "Average". Interestingly, the correct labels appear in the time between clicking refresh and when the graph completely loads. This issue only started after upgrading to v0.20.0 from v0.19.3. It appears to affect any graph with multiple questions displayed.

Loading:
![loading](https://cloud.githubusercontent.com/assets/3596229/19322488/234372e0-906e-11e6-8763-d563588ffa28.png)

Finished:
![finished](https://cloud.githubusercontent.com/assets/3596229/19322493/271a9bbe-906e-11e6-966a-869ac6820e89.png)

Video:
[metabase issue.zip](https://github.com/metabase/metabase/files/525318/metabase.issue.zip)

browser and the version: Chrome 53.0.2785.143
operating system: Windows 7 Pro
Your databases: MySQL
Metabase version: 0.20.0
Metabase hosting environment: Linux/Ubuntu 16.04
Metabase internal database: H2 (default)

**Comment by Maragues** [comment]
My case is similar but not identical. The legend labels are showed correctly, but hovering over the data always shows the first label of the series

![image](https://cloud.githubusercontent.com/assets/655970/19392664/069315cc-9232-11e6-9b6c-69bfd1c1497d.png) 

![image](https://cloud.githubusercontent.com/assets/655970/19392675/18fdc0fe-9232-11e6-8c09-6ca0d27a405a.png)

Let me know if you'd like me to create a separate issue

**Comment by tlrobinson** [comment]
@Maragues Yes please do, this is a different issue.

**Comment by Maragues** [comment]
I've opened https://github.com/metabase/metabase/issues/3599
