### ISSUE TITLE
Document MB_HUMANIZATION_STRATEGY

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35470]
### Describe the bug

Everything you need to know is as always Flamber's https://github.com/metabase/metabase/issues/14521#issuecomment-847812140

### To Reproduce

NA

### Expected behavior

NA

### Logs

NA

### Information about your Metabase installation

```JSON
NA
```

### Severity

NA

### Additional context

NA

**Comment by jeff-bruemmer** [comment]
Documented here: https://github.com/metabase/metabase/pull/43612

Will go live when we release 50.
