### ISSUE TITLE
Using an absolute URL as a landing page will break the instance

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35497]
### Describe the bug

We're expecting a relative url there but users can input absolute ones in that textbox

### To Reproduce

1) set up Metabase
2) create a collection
3) copy the link and set it as the landing page in settings->admin->appearance->landing page
4) log out

you'll be redirected to 
<metabase_url><absoluteurl>

### Expected behavior

We should sanitize the input or tell the user that they should enter relative url's

### Logs

NA

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P3

### Additional context

NA

workaround: set env var MB_LANDING_PAGE to "/"

**Comment by iethree** [comment]
Duplicate of #32585
