### ISSUE TITLE
Connect a card to a filter in a dashboard doesn't update data

### ISSUE THREAD

**Issue by NevRA** [metabase/metabase#35503]
### Describe the bug

When we connect parameters (SET_PARAMETER_MAPPING / setParameterMapping) we don't trigger the dashboard update. 

Thread: https://metaboat.slack.com/archives/C01LQQ2UW03/p1699416618327629

### To Reproduce

1. Create a question based on Sample Database / Orders
2. Add it to a new Dashboard
3. Click Edit Dashboard
4. Add Time / Relative filter 
5. Save and Refresh page
6. Click Edit and connect the filter to the Order - Created At field
7. Save
8. Filter diesn't apply without page refresh 

### Expected behavior

Dashboard should be updated based on the filter without page refresh

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

**Comment by kulyk** [comment]
Opening again since we had to revert the fix — #36534

**Comment by oleggromov** [comment]
Fixed by https://github.com/metabase/metabase/pull/36760
