### ISSUE TITLE
Clearly communicate the total permissions granted to a group or person

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#3552]
It's fairly misleading to be able to grant less permissions than what the "All Users" group has, since every user has at least those permissions. We should communicate that better. A couple possibilities (we should probably do multiple of these):
1. Explain how "All Users" works somewhere in the permissions grid.
2. Small warning icon/tooltip or other affordance on any permissions cell that has lower permissions than the "All Users" group.
3. Prevent revoking any permissions from any group which the "All Users" has (frontend and backend?)
4. In the confirmation dialog, warn if any groups have lower permissions than "All Users".
5. Have a permissions overview for groups that takes into account the group's permissions + "All User"'s permissions
6. Have a permissions overview for users that takes into account all of the user's group's permissions, including "All Users" group

**Comment by mazameli** [comment]
I think ideally we would do #3 (and also warn if All Users is granted higher permissions than any other group). I can't think of why we'd want to let users do something that is sort of self-defeating.

Falling short of that, we could add a tooltip like this, and add a warning if an admin tries to revoke access for a group which All Users has:

<img width="274" alt="screen shot 2016-11-23 at 3 21 07 pm" src="https://cloud.githubusercontent.com/assets/2223916/20581914/02273b48-b191-11e6-971a-e76281782c8c.png">

![all users warning](https://cloud.githubusercontent.com/assets/2223916/20581985/9d7203ee-b191-11e6-955f-cc676a7b2952.png)

We could also add a tooltip for admins:
<img width="253" alt="screen shot 2016-11-23 at 3 27 53 pm" src="https://cloud.githubusercontent.com/assets/2223916/20581968/700b766a-b191-11e6-9d08-516a76ecbc13.png">

**Comment by salsakran** [comment]
@mazameli wanna make a call on this and move forward?

**Comment by salsakran** [comment]
closed via #3890
