### ISSUE TITLE
Add more tests that v2 serdes is comprehensive, so new models are not forgotten

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#35540]
**Context**

A goal for serdes v2 is to make it impossible to forget to add serdes support for new models.
Many serdes v2 multimethods have `:default` implementations that work for some models, but some do not.

**To do**

For each of these required methods, we should have a test that checks every Toucan model:
- either implements the method; or
- is explicitly listed as not supporting serdes at all

There used to be a list of such excluded models and some tests based on it, but I think it may have been removed in the overzealous "refactoring" changes that removed some important functionality and tests.

I think the right path is to define every subset of models we care about in `metabase-enterprise.serialization.v2.models`: top-level serialized models, embedded models, models that are excluded from serialization, models with `entity_id` columns, etc. and then the tests will all be on the same page about which models need which things.

An example of such a required multimethod is `hash-fields`. Eg. things with `entity_id` columns might not define `hash-fields`, and since the on-insert logic for `entity_id` is filling them in for new things, it's never called. But then if you `drop_entity_ids` because of serdes issues (hopefully a rarity) it will call `hash-fields` and throw for want of a `defmethod` for that model. (This has already happened [in the wild](https://github.com/metabase/metabase/issues/35097).)

**Comment by piranha** [comment]
I'm kinda scratching my head on that issue right now: ParameterCard does not implement either `serdes/hash-fields` or `serdes/entity-id` multimethod and no `:hook/entity-id`... I'm not sure how do I decide it's good enough? There is nothing about serialization in ParameterCard... Should this check rely on a list in [entity-ids-test](https://github.com/metabase/metabase/blob/master/enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj#L77-L118)?
