### ISSUE TITLE
Backend for static viz visualization insights: trend lines

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#35563]
Base branch for this change is `unified-isomorphic-static-viz-be`, base branch PR: https://github.com/metabase/metabase/pull/34820

**Context**

Backend needs to provide `insights` data to static visualizations so that they can render trend lines.

**Spec**

Add `insights` parameter to the [isomorphic chart renderer](https://github.com/metabase/metabase/pull/34820/files#diff-fb611a0a0fdecfa916aa28ed0679a400ec86ca9cd303d45b64069827ee1b1304R133) and pass it to the javascript function. It should have exactly the same shape as the `data.insights` of the /api/dataset:

<img width="773" alt="Screenshot 2023-11-09 at 6 11 40 PM" src="https://github.com/metabase/metabase/assets/14301985/3225047c-f968-4ecf-b6e9-b8a721aff263">

**Comment by EmmadUsmani** [comment]
Closed as this is a non-task, the `insights` object is already provided on the backend
