### ISSUE TITLE
Undo removing text/heading cards in a dashboard break their visualizations

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#35581]
### Describe the bug

When undo removing text cards or heading cards on a dashboard, their visualization won't be displayed.

I've tested undoing moving to another tab, but it doesn't have any problem.

#### Before removing cards
![Screenshot 2023-11-10 at 6 12 36 PM](https://github.com/metabase/metabase/assets/1937582/22934910-29b6-4e0e-8643-3a2c28bcbd63)

#### After undoing removing cards
![Screenshot 2023-11-10 at 6 12 45 PM](https://github.com/metabase/metabase/assets/1937582/7b806870-91e9-4317-9a87-c5b13990f20d)

### To Reproduce

1. Go to a dashboard
2. Add a text card or a heading card
3. Remove the text card or the heading card
4. Undo the removal
5. The visualization will be broken

### Expected behavior

Visualizations work

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.0",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-11-06",
      "src_hash": "3ebaa978bbec305b002c147a85221d6b852caaaa",
      "tag": "v1.47.1-SNAPSHOT",
      "hash": "cb718b1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoyance since I can just refresh the page after saving to see the visualization

**Comment by kulyk** [comment]
Can no longer be reproduced
