### ISSUE TITLE
No method in multimethod 'temporal-value-lower-bound'

### ISSUE THREAD

**Issue by NevRA** [metabase/metabase#35582]
### Describe the bug

Can't open some questions on stats e.g. 13920-team-42-bug-mountain
Error from response `No method in multimethod 'temporal-value-lower-bound' for dispatch value: :field`

### To Reproduce

Open `/question/13920-team-42-bug-mountain` question on stats

### Expected behavior

Should display data 

### Information about your Metabase installation

```JSON
master
```

### Severity

P1

**Comment by bshepherdson** [comment]
This was introduced by #35523. I took a quick look but I can't see clearly what the issue is.

If this can wait for @camsaul I bet he can fix it swiftly; if it can't then we can revert that change.
