### ISSUE TITLE
Anonymous Access

### ISSUE THREAD

**Issue by Woklet** [metabase/metabase#3559]
This is not necessarily a feature request _yet_ but is there any way to allow anonymous access to Metabase's reports? Ideally, I'd like to have some questions that are accessible to the public.

**Comment by camsaul** [comment]
Related to (or possible duplicate of) #1380

**Comment by camsaul** [comment]
@Woklet unfortunately Metabase doesn't currently support any sort of anonymous access.

**Comment by salsakran** [comment]
this is subsumed of #3680  and #3681
