### ISSUE TITLE
Fix Audit dev env after merging to master

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#35591]
**Context**
- [x] Add an environment variable to disable loading Audit content (import yamls)
- [ ] Check if the internal user exists based on email

**Comment by noahmoss** [comment]
Closed as part of https://github.com/metabase/metabase/pull/35522

#2 we decided not to do—all internal users in production will have a consistent ID. The issue here was that the user was created manually so it had an auto-incremented ID, which the backend didn't expect.
