### ISSUE TITLE
A big warning that if you use CSV uploads in the sample database in the cloud, your data will disappear 

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35638]
### Describe the bug

Containers were meant to be stateless, and we shouldn't break that rule never ever

Users started using the CSV upload feature as a mean not to have a DW, and we know how it all ended: the pod recycled and everything dissapeared

we should put a big big warning that if you use the sample database on the cloud, your tables will dissapear once we make any operation

### To Reproduce

1) set up an instance on the cloud
2) upload a csv
3) stop and start the instance, or wait till we upgrade or something
4) see all your tables disappearing and queries not running

### Expected behavior

It should stay the same, but we should warn users

### Logs

NA

### Information about your Metabase installation

```JSON
v46.x+
```

### Severity

P1

**Comment by luizarakaki** [comment]
After the [conversation](https://metaboat.slack.com/archives/C04S696LRUM/p1699874448953159):

Add a warning in `/admin/settings/uploads` if the admin selects any H2 database (including Sample Database) as the upload destination.
