### ISSUE TITLE
Use the official MySQL latest image for drivers tests

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#35641]
We've recently upgraded the oldest supported MySQL version to 8.0 in #34943.
The `circleci/mysql:latest` is two years old and is using `8.0.28-1debian10`.

The official `mysql:latest` is `8.2.0-1.el8` and is two weeks old.
We should start using the official latest image.

There was an attempt to do this in https://github.com/metabase/metabase/pull/35588, but I ran into connection issues that I will not have the time to investigate and solve.

**Comment by paoliniluis** [comment]
We could use https://github.com/metabase/metabase-qa/actions/runs/6837366226/job/18593273116
