### ISSUE TITLE
Feature req: restrict user access to view dashboard without having ability to access underlying tables

### ISSUE THREAD

**Issue by amirnathoo** [metabase/metabase#3565]
We have a Chromebox displaying a dashboard with our KPIs, but this currently gives total read access to our db to anyone who connects a keyboard and mouse to the Chromebox.

I don't think #3362 or #3363 will help since the display of the KPI graphs needs access to sensitive tables. I would need to be able to create a user that only has the ability to view the dashboard, with no ability to edit it or access the underlying tables directly.

**Comment by camsaul** [comment]
#3363 is for permissions for dashboards, cards, and pulses.

**Comment by camsaul** [comment]
This is a duplicate of #3363 so closing as such

**Comment by hfaridgit** [comment]
+1
