### ISSUE TITLE
 Split Y Axis values not automatically being displayed post 1.47.5

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#35662]
### Describe the bug

Not sure it’s completely in relation to [34618](https://github.com/metabase/metabase/issues/34618) which was released in 47.5.

Some of our customers have observed that, even with the 'Split y-axis when necessary' option enabled, they no longer see multiple Y-axes for values of significant difference.

### To Reproduce

Using the following query and Sample data to reproduce.

```
SELECT
   month(CREATED_AT),
   SUM(TOTAL) AS multiply_total,
   AVG(TAX) AS tax_ratio
FROM Orders
GROUP BY month(CREATED_AT)
```
 

Create a bar chart and select the fields for the X and Y axis. In this example, the values for TAX RATIO are being graphed but not visible unless you hover over that area due to the values being significantly smaller than the values for MULTIPLY TOTAL.
<img width="1433" alt="barcharvalues" src="https://github.com/metabase/metabase/assets/17398657/0540e027-bc0b-44ce-8c68-86d9d1b5744b">

You have to manually click on the value and designate the values to be displayed.
<img width="1433" alt="manuallyadd" src="https://github.com/metabase/metabase/assets/17398657/d3760e40-199a-45f5-a2f4-3524f6933ef5">

<br>
<br>

In 1.47.4 and prior, this information is automatically displayed when “Split y-axis when necessary” is enabled.

### Expected behavior

For the values of both Y axis to automatically be displayed, and the bar chart to better represent the values

### Information about your Metabase installation

```JSON
This happens in 1.47.5+
```

### Severity

P2 - There is a workaround but it can become tedious for customers who may have many questions

**Comment by aarthi-subramanian** [comment]
+1 this change is really confusing and thank you to the above ^ for explaining what is actually happening. It felt like the `Split y-axis when necessary` toggle was just broken. Following this issue. Thanks

**Comment by aarthi-subramanian** [comment]
Hi is this gonna be fixed soon? It's very annoying and was hoping it'd be fixed in the latest release 🙏  https://github.com/metabase/metabase/releases/tag/v0.48.1

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/37909
