### ISSUE TITLE
Problem Displaying Dashboard Charts

### ISSUE THREAD

**Issue by jdavissafelease** [metabase/metabase#35666]
### Describe the bug

<img width="1611" alt="Screenshot 2023-11-13 at 9 37 55 AM" src="https://github.com/metabase/metabase/assets/147879399/a187539b-357f-4e3d-b19f-d428329cd4f8">
<img width="808" alt="Screenshot 2023-11-13 at 9 06 56 AM" src="https://github.com/metabase/metabase/assets/147879399/650f52e7-8e23-4511-8ca0-e5243eab295c">
<img width="1325" alt="Screenshot 2023-11-13 at 9 07 04 AM" src="https://github.com/metabase/metabase/assets/147879399/f290ddff-facd-4abd-b409-1f4d3570927b">

Our home dashboard has starting to throw errors all over the place that did not exist previously. After investigation, it seems the "Lease Id is not empty" is part of the root issue, but we must have that condition in place for accurate metrics. This did not throw an error previously, so i'm at a loss as to why the errors exist. I have attached a csv of the LeaseId column where nulls are causing an issue. Please let me know if you need more information to help investigate this error because we need to fix it ASAP. 
[query_result_2023-11-13T16_20_47.825614Z.csv](https://github.com/metabase/metabase/files/13336928/query_result_2023-11-13T16_20_47.825614Z.csv)

Error filtering against :type/Integer Field: unable to parse String "" to a :type/Integer

### To Reproduce

1. See error screenshots
2. See error message
3. See diagnostic info 
4. Investigate csv where nulls are creating a filter error 

### Expected behavior

This should give us a count

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v1.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": "US/Central"
    }
  }
}
```

### Severity

Blocking usage of metabase

**Comment by paoliniluis** [comment]
Hi @jdavissafelease are you a paid customer? if so, please contact us a help at metabase dot com. Also, can you provide us some reproduction steps?

**Comment by jdavissafelease** [comment]
@paoliniluis Yes I am. Can you please send a link to the correct area to place a ticket?

**Comment by paoliniluis** [comment]
@jdavissafelease help at metabase dot com

**Comment by paoliniluis** [comment]
@jdavissafelease was this fixed?
