### ISSUE TITLE
Support SQL IN-clause (i.e., multiple-ID) SQL parameters

### ISSUE THREAD

**Issue by majithiaharshil** [metabase/metabase#3567]
for eg , i want

``` sql
SELECT * FROM loan WHERE id IN (2,5,6,9,6)
```

will it work if i pass multiple values in {{loan}}

``` sql
SELECT * FROM loan WHERE id IN ({{loan}})
```

**Comment by camsaul** [comment]
@majithiaharshil as @hugocar mentioned in #3505 this isn't something that's supported yet. But it's something we can look into adding in the future. I'll change the title accordingly

**Comment by camsaul** [comment]
Related: #3370

**Comment by camsaul** [comment]
This is actually the same issue as #5457. Metabase 0.25.0+ supports this so going to close this out
