### ISSUE TITLE
[MLv2] [BE] `zoom`, `fk-details`, `fk-filter` drills should be returned for a native query model

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#35689]
zoom, fk-details, fk-filter drills should be returned for a model based on native query with set metadata.

Please use this e2e test for reproduction - 
https://github.com/metabase/metabase/pull/35383/files#diff-4ab88f6c6e1a239ee2fc1eacee670bed33e57126cd04c070491fdfbe8a7d221bR343-R344

**Comment by camsaul** [comment]
So I believe I've fixed this locally, but the Cypress test in question just hangs after it sees the menu of drills

<img width="310" alt="image" src="https://github.com/metabase/metabase/assets/1455846/102d4be3-75ff-4349-acd5-96c63b404704">

<img width="312" alt="image" src="https://github.com/metabase/metabase/assets/1455846/4d92e403-ae08-4f77-aa37-314981d07329">

**Comment by camsaul** [comment]
I did manually verify that things work when you click them tho
