### ISSUE TITLE
Frontend hangs when deleting large tables or collections (should be async with progress indicator)

### ISSUE THREAD

**Issue by dovy** [metabase/metabase#3569]
Your browser and the version: Chrome 53.0.2785.143 (64-bit)
Your operating system: OS X 10.11 El Capitan
Your databases: BigQuery
Metabase version: v0.20.0
Metabase hosting environment: Linux
Metabase internal database: MySQL

I have two collections that are day shard'd (one table per day). I have nearly one trillion records in each table. Here's a screenshot: https://cloudup.com/cBuTDzJ5YAy

`log_data_v7` and `log_data_v8` are what matter.

The `day` table is simply a template table, the the rest are day-shard tables because we stream so much data in them everyday and BigQuery doesn't offer streaming inserts to a self-partitioned table... yet.

https://cloudup.com/ceKH2vQuHtp

When I go to delete these tables, metabase just hangs. I think you should turn that into a background processes, maybe even something that can be resumed on restart rather than an inline activity.

**Comment by dovy** [comment]
Doh, I had the gather metadata checked.

I have two collections that are day shard'd (one table per day). I have nearly one trillion records in each table. Here's a screenshot: https://cloudup.com/cBuTDzJ5YAy

`log_data_v7` and `log_data_v8` are what matter.

The `day` table is simply a template table, the the rest are day-shard tables because we stream so much data in them everyday and BigQuery doesn't offer streaming inserts to a self-partitioned table... yet.

https://cloudup.com/ceKH2vQuHtp

When I go to delete these tables, metabase just hangs. I think you should turn that into a background processes, maybe even something that can be resumed on restart rather than an inline activity.

**Comment by camsaul** [comment]
This is related to #2655. I think the API endpoint can take a long time to finish if it has to delete a lot of things related to that object so it probably makes sense not to block the UI while that's taking place.

**Comment by dovy** [comment]
Agreed. You should add status throughout the app so people can do other things, while the process runs in the background.

Check Google Cloud Platform Console for a great example.
