### ISSUE TITLE
Bug in data browsing under MySQL view table.

### ISSUE THREAD

**Issue by dashi6174** [metabase/metabase#35699]
### Describe the bug

When I use MySQL views as a data source in Metabase, and I update the underlying table of the view, the data in the view actually changes when browsing it in Metabase, even before committing the update operation.

### To Reproduce

1. There is a MySQL data source, and the database is named "test". In this database, there is a table called "apple". that contains 15 records. mysql version is 8.0.35-0ubuntu0.20.04.

> MySQL root@127.0.0.1:test> select * from apple ;
> +----+--------------------+--------+-------+
> | id | name               | color  | price |
> +----+--------------------+--------+-------+
> | 1  | Red Delicious      | Red    | 2.99  |
> | 2  | Granny Smith       | Green  | 3.49  |
> | 3  | Golden Delicious   | Yellow | 2.79  |
> | 4  | Fuji               | Red    | 2.59  |
> | 5  | Honeycrisp         | Red    | 4.99  |
> | 6  | Gala               | Yellow | 2.89  |
> | 7  | Pink Lady          | Pink   | 3.79  |
> | 8  | Braeburn           | Red    | 3.29  |
> | 9  | Cripps Pink        | Pink   | 3.49  |
> | 10 | Jonathan           | Red    | 2.69  |
> | 11 | Red Delicious 2    | Red    | 2.99  |
> | 12 | Granny Smith 2     | Green  | 3.49  |
> | 13 | Golden Delicious 2 | Yellow | 2.79  |
> | 14 | Fuji 2             | Red    | 2.59  |
> | 15 | Honeycrisp 2       | Red    | 4.99  |
> +----+--------------------+--------+-------+
> 
> 15 rows in set

2. Create a view in the test database.
```sql
CREATE VIEW apple_view AS
SELECT id, name, color, price
FROM apple;
```
3. "Add the 'test' database for MySQL in Metabase."
4. Browse the "apple_view" table in this database in Metabase, and you will see 15 records.
5. Execute the following code in PyCharm and set a breakpoint at the next line of "cursor.executemany(sql, values)":
```python
import pymysql

# connect to the database
connection = pymysql.connect(
    host='200.200.182.37',
    user='root',
    password='meta_auto',
    database='test'
)

try:
    with connection.cursor() as cursor:
        # clear the table
        delete_query = "DELETE FROM apple"
        cursor.execute(delete_query)

        # insert
        sql = "INSERT INTO apple ( name, color, price) VALUES (%s, %s, %s)"
        values = [
            ('Tom Delicious 2', 'Red', 2.99),
            ('Bob Smith 2', 'Green', 3.49),
            ('Dim Delicious 2', 'Yellow', 2.79),
            ('Fuji 2', 'Red', 2.59),
            ('Dog 2', 'Red', 4.99)
        ]
        cursor.executemany(sql, values)
        pass #  set a breakpoint here
    # commit
    connection.commit()

finally:
    # close the connection
    connection.close()
```    

6. Viewing the "apple_view" table in Metabae, you will find that there are only five records, which are exactly the five records inserted by the above code but not committed.
7. Force stop the code in PyCharm, the program exits from the breakpoint. Note that at this point, the commit is not executed and the data will be rolled back.
8. In Metabase, there are 15 more records in the "apple_view" table.

Overview, shouldn't the previous data always be displayed when I haven't committed to the database?

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1-post-Ubuntu-0ubuntu120.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1-post-Ubuntu-0ubuntu120.04",
    "os.name": "Linux",
    "os.version": "5.4.0-155-generic",
    "user.language": "zh",
    "user.timezone": "Asia/Chongqing"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.35-0ubuntu0.20.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

High

**Comment by paoliniluis** [comment]
What’s the auto commit mode you have enabled?

**Comment by dashi6174** [comment]
> What’s the auto commit mode you have enabled?

1. the auto commit mode
![image](https://github.com/metabase/metabase/assets/1617266/e4e2c48a-9604-4b17-8bcf-22ee7627af4c)

2. The number of records in the 'apple' table that I viewed using the MySQL command-line client has consistently been 15 during this process.
![image](https://github.com/metabase/metabase/assets/1617266/ec735806-b7b6-45b9-b767-d835062606ee)

**Comment by paoliniluis** [comment]
This is not an issue with Metabase, but rather an issue in how you insert values in the DB

**Comment by dashi6174** [comment]
> This is not an issue with Metabase, but rather an issue in how you insert values in the DB

I think you did not carefully examine the issue I raised, and I have sufficient evidence to prove that it is a bug in Metabase.

1. Autocommit is disabled by default when connecting through Connector/Python. 
![image](https://github.com/metabase/metabase/assets/1617266/ad9f8aa0-c0da-432c-af40-95d3526dbda5)
Detail: https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlconnection-autocommit.html

2. Even if I set autocommit to off in MySQL, this issue still exists in Metabase.

3. During this process, I used MySQL Workbench, DBeaver, and Datagear to view the 'apple' and 'apple_view' tables in the database without encountering this issue.

4. You can spend a few minutes trying the operations mentioned in my previous issue. This problem occurs consistently, so if you're not familiar with Python or pymysql, you can seek assistance from someone who is.
