### ISSUE TITLE
[Static embedding] when passing a resource id as string instead of number, things break with cryptic errors

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#35709]
### Describe the bug

While trying out static embedding I setup a small app that embedded a dashboard using the id from the query string. While doing so I forgot to cast it as number, this caused the embedding to be broken with different errors based on the dashboard.

### To Reproduce

Create a dashboard and share it via static embedding.
Pass a the `dashboard` id as a string instead of a number.

When using locked parameters this is even more confusing, as in that case the example generated code uses strings, and string and numbers can be mixed and it still works
```js
  var payload = {
    resource: { dashboard: 15 }, // "15" doesn't work
    params: {
      account_id: [36, "28"], // this works no problem
    },
    exp: Math.round(Date.now() / 1000) + 10 * 60,
  };
 ```

In some cases I got the dashboard started to load but cards with queries didn't work:
(this is from master `cc50e7a94216ae738cb4aad609122abcf8082e32`)
<img width="430" alt="image" src="https://github.com/metabase/metabase/assets/1914270/85beb9ee-05d4-4ef2-b174-a813b58eef02">
```
[BE] 2023-11-14 13:30:18,517 DEBUG middleware.log :: GET /api/embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOiIxNCJ9LCJwYXJhbXMiOnt9LCJleHAiOjE2OTk5NjU2MTgsImlhdCI6MTY5OTk2NTAxOH0.PovBWGCR5zgcrZdlqKTT7a2xJkwZIrFHFURxsqJyQ0g/dashcard/140/card/79 400 2.2 ms (2 DB calls) 
[BE] "Assert failed: (integer? dashboard-id)"
```

In another case (my self hosted instance on v0.47.6) the dashboard didn't load at all giving this error:
Edit: the cause for the different error is most likely that here I'm using PG as db
<img width="1029" alt="image" src="https://github.com/metabase/metabase/assets/1914270/cfb4bc93-015f-4767-a4a4-b8f1c33f63cd">

### Expected behavior

I would expect a clear error message on what I did wrong, otherwise I could blame metabase.

### Severity

very annoying if it's the first experience with static embedding

**Comment by albertoperdomo** [comment]
@npretto Do you think it would make any sense to do implicit type casts or we could be helping developers shoot themselves in the foot without them or the end-users noticing, e.g. locked filters using the wrong values because it was typecasted to 0 as opposed to failing?

**Comment by albertoperdomo** [comment]
Just stumbled on this by coincidence: https://stackoverflow.com/questions/60826853/metabase-embed-question-fails-with-assert-failed-integer-card-id

**Comment by npretto** [comment]
> we could be helping developers shoot themselves in the foot without them or the end-users noticing

Yeah casting things scares me a little, it could work perfectly 99% of the times and break only in 1% of the cases.
Converting a number passed a string, to a number, should be fairly safe, but we never know.

I'm not sure what happened in the StackOverflow question, he seems to pass it as number. Maybe the JWT library casts it to string?

**Comment by albertoperdomo** [comment]
Thanks for confirming my fears... :D
A couple of things:

>In some cases I got the dashboard started to load but cards with queries didn't work:

Should/can we fail early? As in validate the parameters in the JSON match the params of the dashboard before trying to render at all?

Are we in agreement that the back-end errors could be better? I would expect something like "Static embed render for dashboard with ID failed: parameter X be of type Y, but is Z.". As a developer, what kind of error message would you expect?

Then there is the error you saw in the front-end. I think that is super confusing and we should come up with a better error message, too. It should be logged in the back-end regardless of the fact that it's also shown in the front-end. The thing is that we can't expect end-users to be developers, this could be the end-users of our customers or our customers. For the first it's not actionable and confusing, for the latter it is actionable.

**Comment by npretto** [comment]
@albertoperdomo I looked at the bug again (on master), it looks like in the first request we make to the backend (`/api/embed/dashboard/${jwt}/`) the id is casted to a integer:
<img width="250" alt="Screenshot 2023-11-30 at 19 39 07" src="https://github.com/metabase/metabase/assets/1914270/b28a2f43-fea0-4dc6-80e5-43037c36a4c4">
And then the requests to dashcards endpoint fail.

In the second screenshot (the old version), it was probably the first request that failed.

"Failing early" would revert to the old logic but with a clearer explanation, but I feel we should ask somebody from the backend if they know more about it, if they're confident enough in the casting we could just port it to the dashcards endpoint too

**Comment by albertoperdomo** [comment]
Thanks @npretto 

>"Failing early" would revert to the old logic but with a clearer explanation, but I feel we should ask somebody from the backend if they know more about it, if they're confident enough in the casting we could just port it to the dashcards endpoint too

That makes sense. Either we refuse to cast, fail early and show a helpful error message, or we do cast and apply the casted value everywhere. Did I understand it correctly?

Can you try to find out more? There is no real urgency around this, but I would love to clean this up.

**Comment by npretto** [comment]
@dpsutton In my specific case, I was just playing around with embedding and made a simple app that took the id from the query string without casting it.

Update on the second error in the screen: the different error wasn't caused by the older version as I thought, but by the different databased used. My self hosted instance (2nd screen) was using PG, while for the first error I was using h2.
