### ISSUE TITLE
Column 'show_in_getting_started' cannot be null error in getting started

### ISSUE THREAD

**Issue by dovy** [metabase/metabase#3570]
Your browser and the version: Chrome 53.0.2785.143 (64-bit)
Your operating system: OS X 10.11 El Capitan
Your databases: ANY
Metabase version: v0.20.0
Metabase hosting environment: Linux
Metabase internal database: MySQL

#### Bug 1

https://cloudup.com/c67ZJ3SioaV

Definition of schema with multiple items displays Filtered by [unknown field].
https://cloudup.com/cg0ZI-5rjqr

#### Bug 2
Changing schema title, does not update. Error displayed in console: `"Column 'show_in_getting_started' cannot be null"`

**Comment by camsaul** [comment]
@dovy The first bug you're reporting already has an open issue: #3558.

Also it probably makes sense to open separate issues for multiple bugs next time around 😉

**Comment by camsaul** [comment]
@dovy You mean "Segment", not "Schema", correct?

**Comment by camsaul** [comment]
This isn't in the Getting Started Guide either from your pictures it looks like you're in the Segment editing page

**Comment by camsaul** [comment]
Ok, maybe this is what @dovy meant when he said

> Changing schema [segment] title, does not update.

in #3570. (This is actually a 3rd separate bug)

**Comment by dovy** [comment]
I'll be much more explicit next time. My bad.

**Comment by camsaul** [comment]
Fixed by #3583
