### ISSUE TITLE
dashboard_tab is not indexed by dashboard_id

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35710]
### Describe the bug

When we get the dashboard, we do `SELECT * FROM "dashboard_tab" WHERE "dashboard_id" = $1 ORDER BY "position" ASC` and dashboard_id is not indexed

`select * from pg_indexes where tablename = 'dashboard_tab'` returns 
CREATE UNIQUE INDEX dashboard_tab_pkey ON public.dashboard_tab USING btree (id)
CREATE UNIQUE INDEX dashboard_tab_entity_id_key ON public.dashboard_tab USING btree (entity_id)

so dashbboard_tab will always do sequential scans

### To Reproduce

do explain analyze on SELECT * FROM "dashboard_tab" WHERE "dashboard_id" = $1 with any dashboard_id

### Expected behavior

We should use indexes in tables

### Logs

NA

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P2

**Comment by luizarakaki** [comment]
Pretty sure this was fixed by https://github.com/metabase/metabase/pull/33578
As dashboard_id is fk
