### ISSUE TITLE
Models broken with custom fields

### ISSUE THREAD

**Issue by jconnatser** [metabase/metabase#35711]
**Describe the bug**
Changing model metadata when there is a custom field in the model results in broken model.  The results return fine until you try to change the metadata for the model.  I've tried with single source models and with joined objects and the result is the same.  This makes all model functionality unusable at the moment.
Error: Cannot determine the source table or query for Field clause [:field "List Amount" {:base-type :type/BigInteger}]

**Logs**
[16041a54-9f82-417b-9f15-cc60a9b0e4a1] 2023-11-14T05:48:18-08:00 INFO metabase.api.dataset Source query for this query is Card 80
[16041a54-9f82-417b-9f15-cc60a9b0e4a1] 2023-11-14T05:48:19-08:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 634.9 ms (68 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (3 idle, 0 queued) (117 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[16041a54-9f82-417b-9f15-cc60a9b0e4a1] 2023-11-14T05:48:23-08:00 DEBUG metabase.server.middleware.log GET /api/model-index 200 7.6 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (3 idle, 0 queued) (117 total active threads) Queries in flight: 0 (0 queued)
[16041a54-9f82-417b-9f15-cc60a9b0e4a1] 2023-11-14T05:48:27-08:00 DEBUG metabase.server.middleware.log GET /api/health 200 132.1 µs (0 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (3 idle, 0 queued) (117 total active threads) Queries in flight: 0 (0 queued)
[16041a54-9f82-417b-9f15-cc60a9b0e4a1] 2023-11-14T05:48:27-08:00 DEBUG metabase.server.middleware.log GET /api/health 200 135.2 µs (0 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (3 idle, 0 queued) (117 total active threads) Queries in flight: 0 (0 queued)
[16041a54-9f82-417b-9f15-cc60a9b0e4a1] 2023-11-14T05:48:36-08:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Cannot determine the source table or query for Field clause [:field "List Amount" {:base-type :type/BigInteger}]
{:database_id 2,
 :started_at #t "2023-11-14T13:48:36.721521Z[GMT]",
 :error_type :invalid-query,
 :json_query
 {:database 2,
  :query
  {:source-table 56,
   :joins
   [{:fields [["field" 620 {:join-alias "Organizations - Org"}]],
     :source-table 44,
     :condition ["=" ["field" 799 nil] ["field" 625 {:join-alias "Organizations - Org"}]],
     :alias "Organizations - Org",
     :strategy "inner-join"}
    {:fields [["field" 264 {:join-alias "Customers"}]],
     :source-table 15,
     :condition ["=" ["field" 801 nil] ["field" 256 {:join-alias "Customers"}]],
     :alias "Customers",
     :strategy "inner-join"}
    {:fields [["field" 651 {:join-alias "Currencies - Org"}]],
     :source-table 46,
     :condition
     ["and"
      ["=" ["field" 799 nil] ["field" 648 {:join-alias "Currencies - Org"}]]
      ["=" ["field" 784 nil] ["field" 649 {:join-alias "Currencies - Org"}]]],
     :alias "Currencies - Org",
     :strategy "inner-join"}
    {:fields "none",
     :source-table 37,
     :condition ["=" ["field" 775 nil] ["field" 534 {:join-alias "Billing Methods"}]],
     :alias "Billing Methods"}
    {:fields
     [["field" 92 {:join-alias "Payment Methods"}]
      ["field" 93 {:join-alias "Payment Methods"}]
      ["field" 99 {:join-alias "Payment Methods"}]
      ["field" 87 {:join-alias "Payment Methods"}]],
     :source-table 28,
     :condition ["=" ["field" 538 {:join-alias "Billing Methods"}] ["field" 95 {:join-alias "Payment Methods"}]],
     :alias "Payment Methods",
     :strategy "inner-join"}
    {:fields [["field" 443 {:join-alias "Contacts - Primary Contact"}]],
     :source-table 26,
     :condition ["=" ["field" 793 nil] ["field" 448 {:join-alias "Contacts - Primary Contact"}]],
     :alias "Contacts - Primary Contact"}],
   :expressions {:List Amount ["field" 796 nil]},
   :fields
   [["field" 794 nil]
    ["field" 786 nil]
    ["field" 785 {:temporal-unit "default"}]
    ["field" 803 nil]
    ["field" 804 {:temporal-unit "default"}]
    ["field" 780 nil]
    ["field" 789 nil]
    ["field" 791 {:temporal-unit "default"}]
    ["field" 802 {:temporal-unit "default"}]
    ["field" 801 nil]
    ["field" 779 nil]
    ["field" 788 nil]
    ["field" 797 nil]
    ["field" 775 nil]
    ["field" 778 {:temporal-unit "default"}]
    ["field" 796 nil]
    ["field" 795 nil]
    ["field" 798 nil]
    ["field" 787 nil]
    ["field" 790 nil]
    ["field" 776 {:temporal-unit "default"}]
    ["field" 774 {:temporal-unit "default"}]
    ["field" 800 nil]
    ["field" 783 nil]
    ["field" 784 nil]
    ["field" 782 nil]
    ["field" 793 nil]
    ["field" 792 nil]
    ["field" 924 nil]
    ["field" "List Amount" {:base-type "type/BigInteger"}]]},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> query_processor.util.add_alias_info$field_source_table_alias.invokeStatic(add_alias_info.clj:185)"
  "query_processor.util.add_alias_info$field_source_table_alias.invoke(add_alias_info.clj:174)"
  "query_processor.util.add_alias_info$fn__69429.invokeStatic(add_alias_info.clj:331)"
  "query_processor.util.add_alias_info$fn__69429.invoke(add_alias_info.clj:328)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_$replace_69465__69466$fn__69473$fn__69474.invoke(add_alias_info.clj:386)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_$replace_69465__69466$fn__69473.invoke(add_alias_info.clj:386)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_$replace_69465__69466.invoke(add_alias_info.clj:386)"
  "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:47)"
  "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_$replace_69465__69466$fn__69473.invoke(add_alias_info.clj:386)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_$replace_69465__69466.invoke(add_alias_info.clj:386)"
  "mbql.util.match.impl$replace_in_collection$iter__30885__30889$fn__30890.invoke(impl.cljc:44)"
  "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
  "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_$replace_69465__69466$fn__69473.invoke(add_alias_info.clj:386)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_$replace_69465__69466.invoke(add_alias_info.clj:386)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_.invokeStatic(add_alias_info.clj:386)"
  "query_processor.util.add_alias_info$add_alias_info_STAR_.invoke(add_alias_info.clj:383)"
  "query_processor.util.add_alias_info$add_alias_info$fn__69483.invoke(add_alias_info.clj:430)"
  "query_processor.util.add_alias_info$add_alias_info.invokeStatic(add_alias_info.clj:425)"
  "query_processor.util.add_alias_info$add_alias_info.invoke(add_alias_info.clj:396)"
  "driver.sql.query_processor$fn__71521.invokeStatic(query_processor.clj:1436)"
  "driver.sql.query_processor$fn__71521.invoke(query_processor.clj:1434)"
  "driver.sql.query_processor$mbql__GT_honeysql.invokeStatic(query_processor.clj:1445)"
  "driver.sql.query_processor$mbql__GT_honeysql.invoke(query_processor.clj:1438)"
  "driver.sql.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:1456)"
  "driver.sql.query_processor$mbql__GT_native.invoke(query_processor.clj:1452)"
  "driver.sql$fn__88992.invokeStatic(sql.clj:42)"
  "driver.sql$fn__88992.invoke(sql.clj:40)"
  "query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:14)"
  "query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:9)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__76193.invoke(mbql_to_native.clj:21)"
  "query_processor$fn__78301$combined_post_process__78306$combined_post_process_STAR___78307.invoke(query_processor.clj:260)"
  "query_processor$fn__78301$combined_pre_process__78302$combined_pre_process_STAR___78303.invoke(query_processor.clj:257)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76979$fn__76984.invoke(resolve_database_and_driver.clj:36)"
  "driver$do_with_driver.invokeStatic(driver.clj:93)"
  "driver$do_with_driver.invoke(driver.clj:88)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76979.invoke(resolve_database_and_driver.clj:35)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__72961.invoke(fetch_source_query.clj:316)"
  "query_processor.middleware.store$initialize_store$fn__73142$fn__73143.invoke(store.clj:12)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:56)"
  "query_processor.store$do_with_store.invoke(store.clj:50)"
  "query_processor.middleware.store$initialize_store$fn__73142.invoke(store.clj:11)"
  "query_processor.middleware.normalize_query$normalize$fn__77275.invoke(normalize_query.clj:36)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__85305.invoke(handle_audit_queries.clj:131)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__74669.invoke(constraints.clj:54)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__77204.invoke(process_userland_query.clj:151)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__77601.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___66810$thunk__66812.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___66810.invoke(reducible.clj:109)"
  "query_processor.reducible$async_qp$qp_STAR___66810.invoke(reducible.clj:94)"
  "query_processor.reducible$sync_qp$qp_STAR___66822.doInvoke(reducible.clj:129)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:383)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:379)"
  "query_processor$fn__78350$process_query_and_save_execution_BANG___78359$fn__78362.invoke(query_processor.clj:394)"
  "query_processor$fn__78350$process_query_and_save_execution_BANG___78359.invoke(query_processor.clj:387)"
  "query_processor$fn__78395$process_query_and_save_with_max_results_constraints_BANG___78404$fn__78407.invoke(query_processor.clj:406)"
  "query_processor$fn__78395$process_query_and_save_with_max_results_constraints_BANG___78404.invoke(query_processor.clj:399)"
  "api.dataset$run_query_async$fn__100998.invoke(dataset.clj:74)"
  "query_processor.streaming$streaming_response_STAR_$fn__61400$fn__61401.invoke(streaming.clj:166)"
  "query_processor.streaming$streaming_response_STAR_$fn__61400.invoke(streaming.clj:165)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__39657.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "Cannot determine the source table or query for Field clause [:field \"List Amount\" {:base-type :type/BigInteger}]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 2,
  :query
  {:source-table 56,
   :expressions {"List Amount" [:field 796 nil]},
   :fields
   [[:field 794 nil]
    [:field 786 nil]
    [:field 785 {:temporal-unit :default}]
    [:field 803 nil]
    [:field 804 {:temporal-unit :default}]
    [:field 780 nil]
    [:field 789 nil]
    [:field 791 {:temporal-unit :default}]
    [:field 802 {:temporal-unit :default}]
    [:field 801 nil]
    [:field 779 nil]
    [:field 788 nil]
    [:field 797 nil]
    [:field 775 nil]
    [:field 778 {:temporal-unit :default}]
    [:field 796 nil]
    [:field 795 nil]
    [:field 798 nil]
    [:field 787 nil]
    [:field 790 nil]
    [:field 776 {:temporal-unit :default}]
    [:field 774 {:temporal-unit :default}]
    [:field 800 nil]
    [:field 783 nil]
    [:field 784 nil]
    [:field 782 nil]
    [:field 793 nil]
    [:field 792 nil]
    [:field 924 nil]
    [:field "List Amount" {:base-type :type/BigInteger}]
    [:field 620 {:join-alias "Organizations - Org"}]
    [:field 264 {:join-alias "Customers"}]
    [:field 651 {:join-alias "Currencies - Org"}]
    [:field 92 {:join-alias "Payment Methods"}]
    [:field 93 {:join-alias "Payment Methods"}]
    [:field 99 {:join-alias "Payment Methods"}]
    [:field 87 {:join-alias "Payment Methods"}]
    [:field 443 {:join-alias "Contacts - Primary Contact"}]],
   :joins
   [{:alias "Organizations - Org",
     :strategy :inner-join,
     :fields [[:field 620 {:join-alias "Organizations - Org"}]],
     :source-table 44,
     :condition [:= [:field 799 nil] [:field 625 {:join-alias "Organizations - Org"}]]}
    {:alias "Customers",
     :strategy :inner-join,
     :fields [[:field 264 {:join-alias "Customers"}]],
     :source-table 15,
     :condition [:= [:field 801 nil] [:field 256 {:join-alias "Customers"}]]}
    {:alias "Currencies - Org",
     :strategy :inner-join,
     :fields [[:field 651 {:join-alias "Currencies - Org"}]],
     :source-table 46,
     :condition
     [:and
      [:= [:field 799 nil] [:field 648 {:join-alias "Currencies - Org"}]]
      [:= [:field 784 nil] [:field 649 {:join-alias "Currencies - Org"}]]]}
    {:alias "Billing Methods",
     :strategy :left-join,
     :source-table 37,
     :condition [:= [:field 775 nil] [:field 534 {:join-alias "Billing Methods"}]]}
    {:alias "Payment Methods",
     :strategy :inner-join,
     :fields
     [[:field 92 {:join-alias "Payment Methods"}]
      [:field 93 {:join-alias "Payment Methods"}]
      [:field 99 {:join-alias "Payment Methods"}]
      [:field 87 {:join-alias "Payment Methods"}]],
     :source-table 28,
     :condition [:= [:field 538 {:join-alias "Billing Methods"}] [:field 95 {:join-alias "Payment Methods"}]]}
    {:alias "Contacts - Primary Contact",
     :strategy :left-join,
     :fields [[:field 443 {:join-alias "Contacts - Primary Contact"}]],
     :source-table 26,
     :condition [:= [:field 793 nil] [:field 448 {:join-alias "Contacts - Primary Contact"}]]}],
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :type :query,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 3, :context :ad-hoc}},
 :ex-data
 {:type :invalid-query,
  :clause [:field "List Amount" {:base-type :type/BigInteger}],
  :query
  {:source-table 56,
   :expressions {"List Amount" [:field 796 nil]},
   :fields
   [[:field 794 nil]
    [:field 786 nil]
    [:field 785 {:temporal-unit :default}]
    [:field 803 nil]
    [:field 804 {:temporal-unit :default}]
    [:field 780 nil]
    [:field 789 nil]
    [:field 791 {:temporal-unit :default}]
    [:field 802 {:temporal-unit :default}]
    [:field 801 nil]
    [:field 779 nil]
    [:field 788 nil]
    [:field 797 nil]
    [:field 775 nil]
    [:field 778 {:temporal-unit :default}]
    [:field 796 nil]
    [:field 795 nil]
    [:field 798 nil]
    [:field 787 nil]
    [:field 790 nil]
    [:field 776 {:temporal-unit :default}]
    [:field 774 {:temporal-unit :default}]
    [:field 800 nil]
    [:field 783 nil]
    [:field 784 nil]
    [:field 782 nil]
    [:field 793 nil]
    [:field 792 nil]
    [:field 924 nil]
    [:field "List Amount" {:base-type :type/BigInteger}]
    [:field 620 {:join-alias "Organizations - Org"}]
    [:field 264 {:join-alias "Customers"}]
    [:field 651 {:join-alias "Currencies - Org"}]
    [:field 92 {:join-alias "Payment Methods"}]
    [:field 93 {:join-alias "Payment Methods"}]
    [:field 99 {:join-alias "Payment Methods"}]
    [:field 87 {:join-alias "Payment Methods"}]
    [:field 443 {:join-alias "Contacts - Primary Contact"}]],
   :joins
   [{:alias "Organizations - Org",
     :strategy :inner-join,
     :fields [[:field 620 {:join-alias "Organizations - Org"}]],
     :source-table 44,
     :condition [:= [:field 799 nil] [:field 625 {:join-alias "Organizations - Org"}]]}
    {:alias "Customers",
     :strategy :inner-join,
     :fields [[:field 264 {:join-alias "Customers"}]],
     :source-table 15,
     :condition [:= [:field 801 nil] [:field 256 {:join-alias "Customers"}]]}
    {:alias "Currencies - Org",
     :strategy :inner-join,
     :fields [[:field 651 {:join-alias "Currencies - Org"}]],
     :source-table 46,
     :condition
     [:and
      [:= [:field 799 nil] [:field 648 {:join-alias "Currencies - Org"}]]
      [:= [:field 784 nil] [:field 649 {:join-alias "Currencies - Org"}]]]}
    {:alias "Billing Methods",
     :strategy :left-join,
     :source-table 37,
     :condition [:= [:field 775 nil] [:field 534 {:join-alias "Billing Methods"}]]}
    {:alias "Payment Methods",
     :strategy :inner-join,
     :fields
     [[:field 92 {:join-alias "Payment Methods"}]
      [:field 93 {:join-alias "Payment Methods"}]
      [:field 99 {:join-alias "Payment Methods"}]
      [:field 87 {:join-alias "Payment Methods"}]],
     :source-table 28,
     :condition [:= [:field 538 {:join-alias "Billing Methods"}] [:field 95 {:join-alias "Payment Methods"}]]}
    {:alias "Contacts - Primary Contact",
     :strategy :left-join,
     :fields [[:field 443 {:join-alias "Contacts - Primary Contact"}]],
     :source-table 26,
     :condition [:= [:field 793 nil] [:field 448 {:join-alias "Contacts - Primary Contact"}]]}],
   :limit 2000,
   :metabase.query-processor.middleware.limit/original-limit nil}},
 :data {:rows [], :cols []}}

**To Reproduce**
1. Go to My Analytics
2. Click on Subscriptions Model
3. Click Edit Metadata
4. Change the order of any column in the model.  Error appears

**Expected behavior**
No errors.

**Screenshots**

**Severity**
This is blocking our implementation.  If not fixed quickly, we will have to churn to another product.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v1.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by paoliniluis** [comment]
This issue should be resolved on v48

**Comment by ignacio-mb** [comment]
Hi @jconnatser we released [48](https://github.com/metabase/metabase/releases) Release Candidate 1 last week. Can you test it in that version? I wasn't able to reproduce in 48-RC1. Thanks!

**Comment by ignacio-mb** [comment]
Hi @jconnatser do you still see this issue in 48?
