### ISSUE TITLE
Renaming Databases, overwriting

### ISSUE THREAD

**Issue by dovy** [metabase/metabase#3572]
Your browser and the version: Chrome 53.0.2785.143 (64-bit)
Your operating system: OS X 10.11 El Capitan
Your databases: BigQuery
Metabase version: v0.20.0
Metabase hosting environment: Linux
Metabase internal database: MySQL

When trying to mass rename databases (Collections in BigQuery world) I get the following issue.

1. Edit one table.
2. Press save
3. Click the back arrow.
4. Choose to edit another table.
5. Rename table

Result: Second table is now named the SAME as the first.

The data object per table view is getting cross-over from the previous table and I have to reload the page to effectively rename without this cross-over.  ;)

**Comment by salsakran** [comment]
this sounds similar to #3359

**Comment by dovy** [comment]
It's the same thing, though with different steps to reproduce here. I'll close this issue and link from  other ticket.
