### ISSUE TITLE
[MLv2] [BE] refactor manyPks? option key in zoom, fk-details, fk-filter

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#35725]
In zoom, fk-details, fk-filter drills we have `manyPks?` option that cannot be used as a JS/TS variable name.

Could you please rename it to be `hasManyPks`

**Comment by camsaul** [comment]
In #35886 I'm changing this to `isManyPks`, hope that's ok. I know `hasManyPks` is probably better grammar here but I wanted to solve this generally and I didn't want to go down that rabbit hole of trying to decide when to use `is` vs `has`, and one general rule is easier to keep in your head anyway.
