### ISSUE TITLE
Split Axis not working for combo charts

### ISSUE THREAD

**Issue by maadso** [metabase/metabase#35727]
### Describe the bug

I had functioning that i created last week, today they are not working correctly - did something ship since 5 days ago? 

I have native SQL queries to create a combo chart - bars for user volume, line for conversion %, and x-axis is a categorical topic. 

I can't get the split axis to work at all, can't get the "combo" part to work either - it only shows 1 line, or if i flip the order of the metric it shows 2 lines. 

i tried recreating the chart with a new native query - same issue. however - it is working for "questions" rather than sql queries. please help!

<img width="1682" alt="Untitled 2" src="https://github.com/metabase/metabase/assets/75400846/05230256-c4ef-41c3-b022-1c303447c145">

<img width="1682" alt="Untitled" src="https://github.com/metabase/metabase/assets/75400846/306c4bf2-09b0-4790-84fa-7bb7702a53dd">
<img width="1682" alt="Untitled 3" src="https://github.com/metabase/metabase/assets/75400846/39956b19-efb9-4b58-8c46-21690b05cc46">

### To Reproduce

1. native query with 2 metrics (1 percent, 1 volume) and 1 category
2. create combo chart 
3. add category as x-axis and metrics as metrics 
4. doesn't work! 

### Expected behavior

i should have a bar chart + line chart 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "4.4.0",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-07",
      "tag": "v0.47.7",
      "branch": "?",
      "hash": "dd51fd4"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

blocking internal analysis and no known workaround in MB other than recreating the charts in MB UI which isn't possible without redoing all our data tables

**Comment by paoliniluis** [comment]
@FilmonK is this the same as the ine you were debugging?

**Comment by rravi6** [comment]
Hi any updates here? Frustrating a lot of our users

**Comment by alxnddr** [comment]
Hi @maadso! I'm looking at the issue right now and I got one clarifying question. If you set one axis manually to the right, will it work show line and bar? 
<img width="1359" alt="Screenshot 2024-01-17 at 1 47 49 AM" src="https://github.com/metabase/metabase/assets/14301985/5248898b-60a6-482b-9436-d14ce6bbab86">

**Comment by perivamsi** [comment]
@rravi6 are you able to help answer @alxnddr  's question?

**Comment by rravi6** [comment]
Hey sorry I forgot to respond here, but got a response from Metabase support as well with this workaround:

"It is actively being worked on but it's not listed on the roadmap for one of the immediate releases in the coming weeks. At the moment, a workaround of manually clicking on the 3-dot menu for one of the Y-axis values, going to the Style tab, and designate the position."

This does work as a fix in the interim
