### ISSUE TITLE
Question Labels not Working

### ISSUE THREAD

**Issue by dovy** [metabase/metabase#3573]
Your browser and the version: Chrome 53.0.2785.143 (64-bit)
Your operating system: OS X 10.11 El Capitan
Your databases: ANY
Metabase version: v0.20.0
Metabase hosting environment: Linux
Metabase internal database: MySQL

I get an empty screen when I try to add a label to a question. I'd sure love to start grouping some of these questions.  ;)

**Comment by tlrobinson** [comment]
@dovy Have you created any labels yet? If not then sounds like this is the problem: #3163

**Comment by dovy** [comment]
Well, I feel sheepish. Didn't see that, was looking for a "create label" input field. My bad.

**Comment by camsaul** [comment]
🐑
