### ISSUE TITLE
Subscription recipients

### ISSUE THREAD

**Issue by denisburlacu** [metabase/metabase#35739]
**Is your feature request related to a problem? Please describe.**
Right now we are using Metabase as a Free (docker image)
We are grouping users with fixed permission

Multiple Sets, each set is:
- 1 Database
   - 1 Group with permission just to this database, and deny permission to all other databases
   - Users added to this group
![image](https://github.com/metabase/metabase/assets/33527073/8f0fb20b-206b-4859-a8b7-47e042a85363)
When a customer who need to have permission just to 1 database, and is a part of the Group, can select from the "To" any users from the current instance from this Metabase.

**Describe the solution you'd like**
Im expecting if a customer is from a group, to see just other users from the current group.

**Comment by paoliniluis** [comment]
This is a feature of Pro/Enterprise
