### ISSUE TITLE
Multiple Queries in Query Builder

### ISSUE THREAD

**Issue by dovy** [metabase/metabase#3574]
Your browser and the version: Chrome 53.0.2785.143 (64-bit)
Your operating system: OS X 10.11 El Capitan
Your databases: ANY
Metabase version: v0.20.0
Metabase hosting environment: Linux
Metabase internal database: MySQL

I'd love to be able to specify multiple lines in the query builder so I don't have to use raw SQL to get the same thing.

Example, I have 3 groups of data points I generate by comparing a single value (1-10). I'd love to have 3 rows I can select, add counts and possibly even name each so my data could run "3 queries" but only display one row of data.  ;)

**Comment by dovy** [comment]
Also with BigQuery collections, I want to span multiple days (table each) so I need to be able to select from multiple.  ;)

**Comment by camsaul** [comment]
@dovy we already have an open issue for supporting `TABLE_DATE_RANGE` in BigQuery: #2324

**Comment by camsaul** [comment]
@dovy to clarify the first part of this issue it sounds like you want the ability to run multiple queries in the Query Builder and combine them into a single row of results?

**Comment by dovy** [comment]
@camsaul correct. This isn't just BigQuery.

My second post was the BigQuery question, but applied in the same way.

**Comment by tlrobinson** [comment]
@salsakran is this what we've referred to as "query composition"?

**Comment by salsakran** [comment]
@tlrobinson, yes. But this is possibly distinct from #1822

**Comment by salsakran** [comment]
this is now possible with the notebook mode of the query builder
