### ISSUE TITLE
List related questions to a model

### ISSUE THREAD

**Issue by vipera7** [metabase/metabase#35755]
**Is your feature request related to a problem? Please describe.**
I'm looking to transition from one model to another, but I'm unsure about the specific questions/card where the current model is applied.

**Describe the solution you'd like**
When entering a model, there should be an option in the menu to access a list of associated questions.

**Comment by paoliniluis** [comment]
![image](https://github.com/metabase/metabase/assets/1711649/d0fade01-11c9-4ef1-9689-45438610b0ad)

![image](https://github.com/metabase/metabase/assets/1711649/a0e21f2b-ddf2-4cf6-9068-58c580d4fe2a)
