### ISSUE TITLE
Saving a SQL question will change the location to the filter value

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35785]
### Describe the bug

Check question 14403 on stats and change the comment on the top

save it

see that it changes the location of the window to the filter value

### To Reproduce

See above

### Expected behavior

we shouldn't change the location?

### Logs

NA

### Information about your Metabase installation

```JSON
master
```

### Severity

P1

**Comment by uladzimirdev** [comment]
There is a workaround: make sure `from` is the first parameter on the right panel. If it's not first, remove other params from sql and add them again

/cc @maxzheng
