### ISSUE TITLE
Timezone issue with MYSQL

### ISSUE THREAD

**Issue by pdiniz13** [metabase/metabase#3584]
I'm not sure if this is a feature request or a bug. We are currently using MySQL as our database and our timestamps are saved as datetime fields in the database. When displaying the results with those fields included metabase has no issues converting those fields into PST time which we set in settings. The problem occurs when we try to filter by a datetime field. There doesn't seem to be any timezone conversion and the selected filter is added without being converted from pst to utc. As an example if I tried to select items by using today (PST time) as the filter(same thing happens for both relative and exact date searched) I would instead get orders that were booked between yesterday at 5pm until today at 5pm. This issue doesn't happen with hardcoded sql, even with params, because I can force a tz conversion on those values. But for things such as the dashboard and questions generated via the form there seems to be no solution. Again i'm not sure if this is a bug or if the driver was intended to work this way, but if there's some sort of workaround that you guys can point me too it would be greatly appreciated. Even if it involves just pointing to the area of the code where i could add the filter by default to those values in a forked repo it would help a lot.
### Bugs
- Your browser and the version: Chrome(latest), Firefox(latest). This issue is not browser related.
- Your operating system: Machine running metabase is running on ubuntu.
- Your databases: MySQL
- Metabase version: (e.x. 0.20.0)
- Metabase hosting environment: Docker DC/OS
- Metabase internal database: Postgres
- _Repeatable steps to reproduce the issue_
  Add a mysql table with a datetime field in UTC, and try to filter the results based on that datetime filter.

**Comment by camsaul** [comment]
Did you set a "Report Timezone" in the Admin panel?

**Comment by pdiniz13** [comment]
I did. That only seems to affect the return data and not the query data

**Comment by pdiniz13** [comment]
I'm attaching some screenshots to try to help to demo what's going on. In order to help explain what's going on I created a new field which is using the timestamp data type instead of the datetime one in order to show how they are being handle differently to see if that might make it easier for you guys to point me in the right direction. The datetime field is called created_at and the timestamp field is called created_ats.

In this first series of images the report time zone is set on metabase to Pacific/US but the  environment JAVA_TIMEZONE value isn't set.

In this example i'm selecting by the created_at in its datetime format. As you can see the output is coming out in its proper pacific timezone, but it includes results from the 31st. As for the timestamp version it was converted twice and moved back 16 hours instead of 8 in its display.

![screen shot 2016-10-17 at 12 25 07 pm](https://cloud.githubusercontent.com/assets/9104109/19452387/b24707e0-9465-11e6-9257-29aeada8f78b.png)

In this version i'm selecting based on the timestamp field without any timezone conversion. This selects the right datetime period but the display of the timestamp is still off by 8 hours.

![screen shot 2016-10-17 at 12 25 19 pm](https://cloud.githubusercontent.com/assets/9104109/19452533/368361ac-9466-11e6-9584-77740f4bad0c.png)

In this version I'm selecting based on the datetime field but doing the timezone conversion manually. Datetime has the right time period selected and displays properly but it requires a manual conversion on the search which can't be done on the non sql questions.
![screen shot 2016-10-17 at 12 26 25 pm](https://cloud.githubusercontent.com/assets/9104109/19452371/9b3931b8-9465-11e6-8f7e-c85b12238124.png)




In this one I tried switching the report time zone is on metabase as well as the environment var JAVA_TIMEZONE to Pacific/US.

In this first example as you can see both the selection and return values are coming back in UTC 
![screen shot 2016-10-17 at 12 22 05 pm](https://cloud.githubusercontent.com/assets/9104109/19452820/5ce40530-9467-11e6-9494-66534d49a71e.png)

**Comment by pdiniz13** [comment]
As I was writing this I found a combination that actually works. If we don't use datetime and only timestamps and set both the report time zone on metabase as well as the environment var JAVA_TIMEZONE to Pacific/US then the report does do a timezone conversion on the input query as well as the return value. I need to test this a bit more since I was getting some weird answers with timestamps but it seems to be working.

**Comment by bendog** [comment]
+1

**Comment by bendog** [comment]
+1

**Comment by pdiniz13** [comment]
The timestamps switch did fix the issue. I don't know if I should leave this open or not since the datetime date field still doesn't work.

**Comment by daymun** [comment]
I'm querying a PostgreSQL database hosted on Heroku and also seeing some unexpected behavior related to the timezone offset.

Data is stored in UTC and I've set the timezone to PST in the admin. It seems timestamps are displayed in PST as expected, but queries use UTC.

Here is an example of what happens when I ask metabase for records created today -- the expected answer is zero but the given answer is two. As you can see, the records were created yesterday around 10pm according to the displayed PST timestamp.

I tried setting the JAVA_TIMEZONE env var to Pacific/US but it does not seem to have an effect.

![image](https://cloud.githubusercontent.com/assets/138947/26123364/7b75993c-3a2f-11e7-9607-34cbd8608126.png)

**Comment by senior** [comment]
This issue should be fixed with the PR I just merged in (https://github.com/metabase/metabase/pull/5729) and it will be included in the next 0.26 RC release. Would be great to get a confirmation that it fixes your issue.

**Comment by salsakran** [comment]
@daymun @pdiniz13 @bendog release 0.26 just went out which should fix this. Do you mind checking to see if this is still occurring?

**Comment by pdiniz13** [comment]
I already converted all of our tables to timestamp so haven't had a chance to test it with datetime yet.

**Comment by pdiniz13** [comment]
I created a test table to test this and everything worked fine with datetime.

**Comment by pdiniz13** [comment]
This issue needs to be reopened. Even though this push did fix datetime is now broke timestamp. So now we basically have the same issue but reversed. With datetime working as expected but timestamp not working

**Comment by salsakran** [comment]
@pdiniz13 can you be more specific? What kind of timestamp?

**Comment by pdiniz13** [comment]
the mysql timestamp data type. If you read the original reported problem and you switch the data type datetime with timestamp that is the issue we are currently having.

**Comment by pdiniz13** [comment]
@salsakran could you please reopen this issue since it hasn't really been solved?
