### ISSUE TITLE
Downloading results (csv, xlsx, json) from public question is not working

### ISSUE THREAD

**Issue by zedidas** [metabase/metabase#35854]
### Describe the bug

I have a metabase question for which I have enabled sharing through a public link

When I try to download the full results of that question from the public link (ex: https://my.hostname/metabase/public/question/dd4c851d-2c5b-4864-b527-e909c5add8fb) , the downloaded file appears to be incorrect (even corrupted in the case of .xlsx).

The download works fine if I try to download the results from the metabase backoffice (ex: https://my.hostname/metabase/question/2275-my-question).

I believe it may be relevant to share that my metabase instance has a site URL configured with a context part:
![image](https://github.com/metabase/metabase/assets/5529181/164a888e-a609-4b01-9ac8-0a596e9472a9)

### To Reproduce

1. Set up a Site URL in the administration page, having the format "https://my.hostname/metabase"
2. Create a question
3. Enable publish sharing
4. Open the question using the public link
5. Click on "Download results" (either CSV, XLSX or JSON)

The downloaded file does not contain valid data.

### Expected behavior

The download files should be correctly generated, just has when using the metabase backoffice

### Logs

I did some investigation using Google Chrome DevTools (GCDT). When using the public link, if I click on the download results button, I'll see this request on the GCDT:
![image](https://github.com/metabase/metabase/assets/5529181/b54be383-f70f-4c41-85ae-507b6d01a39e)

It seems that there is some kind of problem with the link generation.

I am also sharing the content of the .json and .csv files that are incorrect, as I believe they can give an hint on the cause of the problem:

* .csv file (downloaded with the name query_result_2023-11-16T11_14_51.089Z.csv)
`{`
`data:  "timestamp" : "2023-11-16T11:14:51.106+00:00",`
`data:  "status" : 404,`
`data:  "error" : "Not Found",`
`data:  "path" : "/metabasehttps:/my.hostname/metabase/public/question/dd4c851d-2c5b-4864-b527-e909c5add8fb.csv"`
`data:}`

* .json file (downloaded with the name query_result_2023-11-16T11_08_06.782Z.json)
`{`
`data:  "timestamp" : "2023-11-16T11:14:51.106+00:00",`
`data:  "status" : 404,`
`data:  "error" : "Not Found",`
`data:  "path" : "/metabasehttps:/my.hostname/metabase/public/question/dd4c851d-2c5b-4864-b527-e909c5add8fb.json"`
`data:}`

Looking at the path property, it is clearly incorrect.

### Information about your Metabase installation

```JSON
- Browser: Chrome Version 119.0.6045.124 (Official Build) (64-bit)
- Operating System: Windows 11
- Database: PostgreSQL
- Metabase version: 0.47.2
- Metabase internal DB: PostgreSQL
```

### Severity

Blocking some users to export results required for the business operation

**Comment by paoliniluis** [comment]
Upgrade to the latest version

**Comment by J-cyber-d** [comment]
Public link downloading is not working in  V0.49.10 , it showing an 304 in network console
