### ISSUE TITLE
Bigquery jobs not canceled if query is canceled and duplicate job creation

### ISSUE THREAD

**Issue by LarsKlingen** [metabase/metabase#35862]
### Describe the bug

If we cancel queries from Bigquery in the Metabase UI the jobs do not get cancelled and it even starts a second BQ job of the same query. 

### To Reproduce

1. create a BigQuery project and add a public dataset
2. Start a Metabase server 
3. Connect your BigQuery project to Metabase
4. Build a query than can take 30-40 seconds (something with many unions)
5. run the query and the click cancel in the metabase UI

```
SELECT
 job_id,
 creation_time,
 query,
 start_time,
 end_time,
 end_time - start_time,
 state
 FROM `region-us`.INFORMATION_SCHEMA.JOBS_BY_PROJECT
WHERE state = 'RUNNING'
 order by start_time desc
```
It ll show that the query job finished. And it will also show a SECOND job for the same query. 

### Expected behavior

The Bigquery Job gets cancelled if we cancel it in the Metabase UI.

### Information about your Metabase installation

```JSON
v0.47.2
```

### Severity

P2

### Additional context

Possibly related to #32027

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/32372

**Comment by LarsKlingen** [comment]
Will close it again since it contains two issues at one. 
One related to #32027 and for the other will open a new issue
