### ISSUE TITLE
Do not create orphaned records or corrupt audit log when deleting old tables

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#35884]
**Is your feature request related to a problem? Please describe.**
- The current task definition for metabase.task.delete-inactive-tables to delete old tables will delete user data corrupting the Metabase application database by:
  - Creating orphaned records in
    - ~~`metabase_field` (may be addressed already if `t2/delete` deletes dependent records referenced by foreign keys, but it does not appear to do so)~~
    - ~~`metabase_fieldvalues` (may be addressed already if `t2/delete` deletes dependent records referenced by foreign keys, but it does not appear to do so)~~
    - `report_card`
    - `revision`
    - `view_log`
  - Making questions referencing those deleted tables unrecoverable even if database, schema, tables are re-added
  - Corrupting the audit log by removing data referenced in `view_log` and `revision`

**Describe the solution you'd like**
- Exclude tables from delete if they are referenced in:
  - `report_card`
  - `view_log`
  - `revision`
- ~~Deleting records referencing deleted tables in `metabase_field` and `metabase_fieldvalues`~~
- Check if `table_id` is referenced anywhere else in the application database and address
- Add functionality when `MB_INACTIVE_TABLE_MAX_DAYS` is set to 0, then disable/skip this task
  - Useful in regulated environments where deleting any data is not an acceptable practice

**Describe alternatives you've considered**
- n/a - no workarounds once data is deleted except recover from backup of application database

**How important is this feature to you?**
The deleting tables functionality should not be included in a release until the above issues are addressed. Introducing the functionality as-is will cause data loss for customers and is unrecoverable except from application database backups if they exist.

**Additional context**
- https://github.com/metabase/metabase/issues/30425
- https://github.com/metabase/metabase/pull/35443

**Comment by luizarakaki** [comment]
The current implementation already deletes `metabase_field` and `metabase_fieldvalues`

Creating orphaned records in revision and view_log is not a problem, imo. If someone really needs to audit what happened in the past, they can find who viewed the card and what it looked like using revisions.

We can add the function to set `MB_INACTIVE_TABLE_MAX_DAYS` to 0 to skip this. This would be the same as setting it to something like 9999999 but 0 is more elegant
