### ISSUE TITLE
Error when more than one field with the same name appears during summarization

### ISSUE THREAD

**Issue by azraagull** [metabase/metabase#35899]
### Describe the bug

Hello,

I use Metabase with my MongoDB database, and while I use the summarize section to create a question, there are multiple fields with different paths and the same value in the filter section, but the summarize section does not display the paths correctly and causes complexity. This happened after the last update.

Below is what it looks like in the ss filter section.
![image](https://github.com/metabase/metabase/assets/98816385/f9171f76-95bc-4250-8e4a-b679359cb9ac)

And in the summarize section it looks like this:
![image](https://github.com/metabase/metabase/assets/98816385/7dd75faf-464d-4efa-9009-f2b0b5d53cb1)

### To Reproduce

1. Open Metabase.
2. Connect Metabase to a MongoDB database.
3. Create a new question by clicking on the "Questions" tab.
4. In the Summary section, type the name of a field with the same name but different paths.
5. The path does not appear and appears with the same name.

### Expected behavior

To summarize I would like the path to appear correct

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "tr-TR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1-post-Ubuntu-0ubuntu122.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1-post-Ubuntu-0ubuntu122.04",
    "os.name": "Linux",
    "os.version": "5.15.0-78-generic",
    "user.language": "en",
    "user.timezone": "Asia/Istanbul"
  },
  "metabase-info": {
    "databases": [
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-07",
      "tag": "v0.47.7",
      "branch": "?",
      "hash": "dd51fd4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

low

**Comment by luizarakaki** [comment]
same as #35938
