### ISSUE TITLE
Cannot upload CSV file

### ISSUE THREAD

**Issue by rapides** [metabase/metabase#35910]
### Describe the bug

A few days ago I successfully set up CSV uploads with Postgres. Then I uploaded 2 CSV files with success and was able to browse the data and it was great. 

Then I came after a few days to use this feature again and tried to upload another CSV and I was not able to do anything. The CSV upload button stopped working. It does not open a popup to browse and select a file. Nothing is happening.

<img width="1188" alt="image" src="https://github.com/metabase/metabase/assets/2733755/6ef6da18-8cf7-466f-9de5-0ed06aed2f29">

I checked if my database and selected schema still exist and it does. I have no idea what is wrong. Also updated Metabase to the latest version and still has the same issue.

Any thoughts?

### To Reproduce

1. Go to 'Collections'
2. Click on 'Navigate to any selection'
3. In the top right corner, try to upload a CSV file
4. Then nothing happens

### Expected behaviour

On clicking the "Upload CSV button" it should open a popup to let me upload a CSV file.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.198-187.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-07",
      "tag": "v0.47.7",
      "branch": "?",
      "hash": "dd51fd4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking some users

**Comment by paoliniluis** [comment]
Do a full refresh of the page and show what’s going on at the browser console

**Comment by rapides** [comment]
I did. I even re-logged in. No change.

The browser console shows me nothing :(

<img width="1101" alt="image" src="https://github.com/metabase/metabase/assets/2733755/3f6c6888-0c07-4f8b-895a-d45e6f7b0050">

**Comment by paoliniluis** [comment]
That's when you click on the button?

**Comment by paoliniluis** [comment]
Do you have anything on the browser that might be interfering?

**Comment by rapides** [comment]
@paoliniluis 

Thank you for your investigation.

> That's when you click on the button?
Yes, it is. A popup should be opened to browse and select a CSV file. There is no action instead. The button does not do anything, also there is no action recorded in the console log.

> Do you have anything on the browser that might be interfering?
Nope, I don't use anything that may affect the application.

The only thing I did in the meantime (and I haven't mentioned it in the issue description) was changing the database config in Metabase by adding an additional Postgres schema that should provide more tables that can be read. This shouldn't change anything.

**Comment by rapides** [comment]
@paoliniluis 

Any update here? Do you think we can find a quick solution to proceed?

**Comment by iethree** [comment]
I have seen some bugs with macOS and browser file picker windows. Have you tried dragging the CSV file onto the collection?

**Comment by rapides** [comment]
@iethree 

> Have you tried dragging the CSV file onto the collection?
Yes, it did the trick! Thank you

Let me know when you provide a fix for this 😄

**Comment by paoliniluis** [comment]
@rapides unless we can reproduce consistently I'm afraid we will have to close the issue. If there's any way you can let us know how to reproduce, feel free to reopen this issue
