### ISSUE TITLE
MongoDB nested fields not showing in v0.47.x

### ISSUE THREAD

**Issue by msaadatkh** [metabase/metabase#35938]
### Describe the bug

MongoDB nested fields were not showing up in the query summary section in **v0.47.x**. It was working fine previously in **v0.46.x**.

Both versions are connected to the same database.

Check the screenshots below to see the differences between the versions:

**v0.46.x**
![image](https://github.com/metabase/metabase/assets/22921290/72babd62-f9f0-44d8-abb4-8ab5f1eb3d8b)

**v0.47.x**
![image](https://github.com/metabase/metabase/assets/22921290/0ec71dc6-8942-4394-88f1-c0a8564fc7ce)

### To Reproduce

Connect Metabase to a MongoDB database with documents that have nested JSON fields.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.0-23-amd64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v0.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

It is preventing to use the new version of Metabase.

**Comment by paoliniluis** [comment]
Thanks for the comparison! help us a lot to debug

**Comment by azraagull** [comment]
same as #35899 which previously created
