### ISSUE TITLE
Uncaught "Cannot remove the final join condition"

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#35976]
### Describe the bug

When there is a join step after summarize step, nothing happens in the UI when changing temporal unit or binning strategy in the summarize step and JS console shows an uncaught error.

![image](https://github.com/metabase/metabase/assets/6830683/7dd86fb1-e1da-495c-b344-513898946a80)

https://github.com/metabase/metabase/assets/6830683/050a06d9-c917-41ba-a514-0f5b31e9518b

### To Reproduce

1. Create a new question: "Orders", summarize "Count" by "Created At: Month"
2. Save it
3. Add a join step and join the newly created question to itself on "Created At: Month" = "Created At: Month"
4. Try to change binning strategy or temporal unit in the Summarize step

Nothing happens in the UI.
JS console shows "Cannot remove the final join condition" error coming from ML.

### Expected behavior

?

### Information about your Metabase installation

master, v47

### Severity

P2

**Comment by lbrdnk** [comment]
Reproduced on 47.2. Unable to reproduce on master [0e9b99f9](https://github.com/metabase/metabase/commit/0e9b99f934fb0a0648502fe56301215c61c20246) -- join is correctly removed on breakout change.
