### ISSUE TITLE
Hovering labels always show first label of the series

### ISSUE THREAD

**Issue by Maragues** [metabase/metabase#3599]
The legend labels are showed correctly, but hovering over the data always shows the first label of the series

![image](https://cloud.githubusercontent.com/assets/655970/19392664/069315cc-9232-11e6-9b6c-69bfd1c1497d.png) 

![image](https://cloud.githubusercontent.com/assets/655970/19392675/18fdc0fe-9232-11e6-8c09-6ca0d27a405a.png)

Browser: Chrome 53.0.2785.143 (64-bit)
OS: macOS Sierra
My databases: MySQL
Metabase version: 0.20.0
Metabase hosting: centOS 6.5
Metabase internal database: H2

**Comment by camsaul** [comment]
Possibly related: #3602

**Comment by camsaul** [comment]
@tlrobinson is this fixed by any of the 20.1 PRs?

**Comment by tlrobinson** [comment]
This should be fixed in `master`.
