### ISSUE TITLE
[MLv2] [BE] Add `quickFilterDrillDetails` for `quick-filter` drill

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#36001]
Add 

```
function quickFilterDrillDetails(drillThru: DrillThru): {
  query: Query,
  column: ColumnMetadata,
  stageIndex: number,
  value: unknown, // value passed to availableDrillThrus
}
```

Caveat here is that `query`, `column` and `stageIndex` would be used for adding a filter manually in some cases (e.g. Filter by this -> Contains...), so it should follow the same logic from https://github.com/metabase/metabase/pull/35878

====

alternatively, if you prefer that, I could call `columnFilterDrillDetails` here (maybe rename to `filterDrillDetails`?); in that case we could add `value` to `displayInfo` of the drill.

**Comment by bshepherdson** [comment]
I forgot to link this to the PR. This was fixed by #36092.
