### ISSUE TITLE
`result_metadata` being overwritten by `qp/process-query-and-save-execution!`

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#36003]
### Describe the bug

Invoking `process-query-and-save-execution!` on models with hand-curated metadata overwrites that metadata with the query execution results.

### To Reproduce

1. Create a model
2. Change the metadata for a column type
3. Run `(render-card-to-png your-model-id)` as shown [here](https://github.com/metabase/metabase/blob/master/dev/src/dev/render_png.clj#L77).
4. Run `(t2/select-one :model/Card your-model-id)` and note that the metadata has been overwritten

### Expected behavior

It should not overwrite hand-curated metadata.

### Information about your Metabase installation

```JSON
Latest master branch.
```

### Severity

Annoying

### Additional context

See [this](https://metaboat.slack.com/archives/C04DN5VRQM6/p1700257498797559) slack thread for context and further details.

**Comment by dpsutton** [comment]
I think this is user error. If you find the usages of `:metadata/dataset-metadata` you can see how `qp.util/combine-metadata` is used to propagate that. But the `:metadata/dataset-metadata` metadata must be present to know that it is a model.

We could make this less error prone but this is a bug in the dev tooling of `render-card-to-png` and not in the query processor necessarily.

**Comment by dpsutton** [comment]
Alternatively, the second arg to `qp/process-query-and-save-execution!` is the `info` param. It should have the following style (taken from `metabase.query-processor.card`)

```clojure
        info  (cond-> {:executed-by            api/*current-user-id*
                       :context                context
                       :card-id                card-id
                       :card-name              (:name card)
                       :dashboard-id           dashboard-id
                       :visualization-settings (:visualization_settings card)}
                (and (:dataset card) (seq (:result_metadata card)))
                (assoc :metadata/dataset-metadata (:result_metadata card)))
```

versus the `info` in `dev.render-png`:

```clojure
(binding [qp.perms/*card-id* nil]
  (qp/process-query-and-save-execution!
    (-> dataset_query
        (assoc :async? false)
        (assoc-in [:middleware :process-viz-settings?] true))
    {:executed-by (:id user)
     :context     :pulse
     :card-id     card-id}))
```

**Comment by markbastian** [comment]
Yeah, in a local branch I've changed `render-card-to-png` to look like this:

```clojure
(defn render-card-to-png
  "Given a card ID, renders the card to a png and opens it. Be aware that the png rendered on a dev machine may not
  match what's rendered on another system, like a docker container."
  [card-id]
  (let [{:keys [dataset_query] :as card} (t2/select-one card/Card :id card-id)
        query-results                    (qp/process-query dataset_query)
        png-bytes                        (render/render-pulse-card-to-png (pulse/defaulted-timezone card)
                                                                          card
                                                                          query-results
                                                                          1000)
        tmp-file                         (File/createTempFile "card-png" ".png")]
    (with-open [w (java.io.FileOutputStream. tmp-file)]
      (.write w ^bytes png-bytes))
    (.deleteOnExit tmp-file)
    (open tmp-file)))
```

The primary change is to just use `process-query`. If the fix is simply to use a nondestructive query in this case that makes sense. I'm still unsure if it makes sense for `process-query-and-save-execution!` to overwrite user metadata. Seems like maybe that should be preserved or there could be an `:overwrite?` flag to preserver what the user has done. I don't have a strong opinion about it, though, just throwing the idea out there.

**Comment by dpsutton** [comment]
`process-query-and-save-execution!` doesn't actually do the metadata saving. That's from `metabase.query-processor.middleware.results-metadata/record-metadata!`. We always save metadata so that if the query results shape changes (new cols show up, cols go away, etc) the result_metadata is the correct shape.

This was one of the tricky bits for models in the beginning. I agree with you that it could get better.
