### ISSUE TITLE
Support filter by external SQL query results

### ISSUE THREAD

**Issue by Maragues** [metabase/metabase#3600]
I have a dashboard that shows user activity over time (nb of entries, nb of messages, etc). Now, I'd like to be able to show this results for a specific set of users, so my queries would look like

```
select nb_of_entries
from user_months
[[where user_id in ({{active_user_ids}})]]
```

The *active_user_ids* must be generated by another query. It'd be something like

```
/*
* Active users every month of the specified period
*/
select m.user_id, count(*) months, sum(m.user_active) active_sum 
from user_months m inner join users on m.user_id=users.user_id 
where m.date between {{start}} and {{end}} and is_listable=true
group by m.user_id 
having months=active_sum;
```
as you can see, this query also needs date range filters.

If I only had to apply that condition on one question I could add a nested query, but since it's something dashboard wide, it's not maintainable across multiple questions

I understand that this is a complex request. Without being a database expert, I've thought on some tools that could help

- Add dashboard temporary tables (which also support filters). Currently can't be done in SQL editor. It'd be like creating a question but without a chart, just for storing results.
- Add dashboard SQL filters. Execute this query and replace placeholders with the result.

It may also be that this is out of scope for Metabase and I should insert this data into a table while in ETL phase.

Might be related: https://github.com/metabase/metabase/issues/3574

**Comment by camsaul** [comment]
@Maragues it sounds like what you want could be accomplished with a `JOIN` or two.

We already have an open issue to cover your first suggestion, #1822.

**Comment by Maragues** [comment]
Thanks @camsaul , https://github.com/metabase/metabase/issues/1822 would be a nice to have

Closing this issue
