### ISSUE TITLE
[Epic] Let dashboard filters only apply to select tabs

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#36012]
**Links**
- [Product doc](https://www.notion.so/metabase/Make-dashboard-filters-local-to-tabs-and-configurable-like-cards-43915e4512e9494cb18abe1dba0b7c2d?pvs=4)
- eng doc: _link to technical design doc, if any_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links: _related issues if any_

**Implementation Plan**

***Milestone 1***
_insert tasklist here_

***Milestone 2***

**Comment by hss-iullah** [comment]
This is 100% needed.

**Comment by cdeweyx** [comment]
Moving to https://github.com/metabase/metabase/issues/36010 — Just project management.
