### ISSUE TITLE
slack: document requirement of metabase_files channel during setup

### ISSUE THREAD

**Issue by abn** [metabase/metabase#3601]
This issue was raised on [discourse](http://discourse.metabase.com/t/slack-integration-problem/725/4). The resolution was noted in [this reply](http://discourse.metabase.com/t/slack-integration-problem/725/6).

The requirement of having a channel _metabase_files_ previously existing could be documented in both the admin guide as well as the _/admin/settings/slack_ endpoint in order to avoid any issues. Note that a bot user is unable to create a channel.

References:
https://github.com/metabase/metabase/blob/master/src/metabase/integrations/slack.clj#L75
https://api.slack.com/methods/channels.create

**Comment by camsaul** [comment]
Oh yeah, I don't think we realized this was a requirement. @metabase/core-developers @salsakran is this a recent development? Maybe Slack changed their API again and doesn't autocreate the channel any more. We should definitely at least update the documentation for 0.20.1 to mention this and maybe try to look into a better fix at some point.

**Comment by tlrobinson** [comment]
Yeah, I think we overlooked that bot users can't created channels when we recently switched the documentation from recommending creating a test token to bot token.
