### ISSUE TITLE
Tool tip showing wrong series on multi-series charts

### ISSUE THREAD

**Issue by hugocar** [metabase/metabase#3602]
> ### Bugs
> If you're filing an issue about a bug please include as much information
> as you can including the following.

- Your browser and the version: Chrome, Safari
- Metabase version 2.0

Easy to reproduce : 
`
SELECT 'x' as x_axis, 1 as serie_one, 2 as serie_two, 3 as serie_three`

 in the SQL editor

Result : 

<img width="1196" alt="capture d ecran 2016-10-17 a 5 27 01 pm" src="https://cloud.githubusercontent.com/assets/19691106/19444123/7579cca6-948f-11e6-84c6-e2e5e21b9aac.png">

As you can see the tooltip is show the value of the third series with the name of the first series 

Line, bar and area charts are affected

**Comment by camsaul** [comment]
I think this might be expected behavior, the first column in this case is the x axis value. @tlrobinson @kdoh @salsakran ?

**Comment by hugocar** [comment]
This is a duplicate of #3599 which was posted 5 hours before, I agree.
It cannot be the expected behavior : it is writing "series_one" when hovering the third series.

**Comment by camsaul** [comment]
Right, that makes sense @hugocar

**Comment by hugocar** [comment]
Thanks @camsaul
Sorry for the duplicates, I expressed the issue differently and didn't saw it was already posted with other words.
