### ISSUE TITLE
Waterfall visualization does not work after removing join & summarize steps and saving the question

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#36027]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/fd8c17b2-830a-4816-b975-2c147f67605d

### To Reproduce

1. Create a new question: "Orders", summarize "Count" by "Created At: Month"
2. Save it
3. Add a join step and join the newly created question to itself on "Created At: Month" <= "Created At: Month"
4. Add summarize step: "Sum of Count" by "<joined question> - Created At: Month"
5. Visualize it
7. Change visualization type to "Waterfall" - notice that this works
8. Save the question as a new question
9. Open GUI editor
10. Remove last Summarize step
11. Remove Join step
12. Visualize it

There is no visualization, even though the question is now in the same state as in step 7, where it could be visualized.

### Expected behavior

Waterfall visualization should work

### Information about your Metabase installation

master, v47

### Severity

P2

**Comment by cdeweyx** [comment]
Able to still reproduce this [here](https://stats.metabase.com/question/19049-waterfall-2-cd).
