### ISSUE TITLE
Druid "raw data" is not sorted

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3604]
Druid allows to sort "raw data" or "select" queries by timestamp. (http://druid.io/docs/latest/querying/select-query.html)
This feature is not currently supported by the druid driver. Sorting by other fields is not supported by druid.

**Comment by camsaul** [comment]
Right, we should be sorting by timestamp if someone specifies that. Unfortunately we still can't sort by any other columns for `select` queries because Druid doesn't support it
