### ISSUE TITLE
Allow click behaviour to land on specific tab inside a dashboard

### ISSUE THREAD

**Issue by hss-iullah** [metabase/metabase#36044]
**Describe the solution you'd like**
Currently you can set click behaviour to open another dashboard and pass variables. What you cannot do is select which tab to land on. This is the same for when adding a new object to a dashboard. It just adds it to the 1st tab each time.

You should also be able to use the native adding of a link in the dashboard and be able to set which tab should be the default.

It should also allow for existing variables to be removed between tabs so not to keep passing the variables between tabs, if the user requires.

**Describe alternatives you've considered**
I have created a solution using a bespoke URL but the UX isn't ideal. I can pass and hardcode the tab into the URL but if I want to add a "go back to previous tab" button this doesn't work and only allows you to open the whole dashboard inside a new browser tab.

**How important is this feature to you?**
Important, this is how dashboards should work :)

**Comment by paoliniluis** [comment]
coming in v48
