### ISSUE TITLE
"Connect your database" doesn't go away after adding a database

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#36063]
["Connect your database" doesn't go away after adding a database - Watch Video](https://www.loom.com/share/a6f1b59c1e2c41ca835094a3f2dc0c92)

If you don't have a database, a banner at the top of the screen prompts you to "Connect your database"; if you add the Sample Dataset, it remains. See Loom video.

1. Have no DBs connected
2. See "Connect your database" banner
3. Click "Connect your database"
4. Click back to go to Databases list
5. Click "Bring the Sample Database back"
6. Wait for it to appear
7. Go back to home page
8. "Connect your database" banner is still there, but should not appear anymore.

This is on master (pre-48)

**Comment by luizarakaki** [comment]
Showing the banner when only the sample dataset is connected is a [product requirement](https://www.notion.so/metabase/Enable-saving-questions-directly-to-dashboards-and-make-this-the-default-path-a84be6e0540241189b251401fb35ca91?pvs=4)
So it is behaving as expected.
