### ISSUE TITLE
Metabase model update - Scheduled job not triggering

### ISSUE THREAD

**Issue by vipera7** [metabase/metabase#36079]
### Describe the bug

I configured my model to update every 12 hours, but I've noticed that the updates aren't happening. Checking the Tools panel in the admin settings, I see that the last run was a day ago. I initially resolved the issue by updating Metabase to the latest version, but now the scheduled job for refreshing the model doesn't seem to trigger. Should I consider restarting the Metabase service occasionally to address this issue? when I manually initiate model refresh from the Tools menu, the selected model updates successfully, and all the models update accordingly. This implies that the trigger for the scheduled job might not be executing properly. How can we address this problem?

### To Reproduce

1. Navigate to 'Admin settings.'
2. Select 'Settings' and then choose 'Caching.'
3. Activate Models and set the caching to 12 hours.
4. Go to 'Databases.'
5. Choose the specific database for which you want to cache data.
6. Enable the model for the selected database.

![image](https://github.com/metabase/metabase/assets/18635706/dd8f8f04-99fd-4d55-b1dc-5c431b6283f5)

![image](https://github.com/metabase/metabase/assets/18635706/e706ff09-8ec8-48b1-8cc8-a5cd1285e183)

### Expected behavior

I should see my models being updated every 12 hours

### Logs

Diagnostic info : 

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.4.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.4.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.4.1+1",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.36"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v0.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

### Information about your Metabase installation

```JSON
Browser : Google Chrome Version 119.0.6045.107
Operating system : Windows Server 2016 Standard
Database : PostgreSQL 12
Metabase version : v0.47.8 (Built on 2023-11-17)
Metabase hosting environment : Jar-file on windows, production installation
Metabase internal database : 5.7.36 - MySQL Community Server (GPL)
```

### Severity

 This is important as I'm unable to run my report using these models.

**Comment by vipera7** [comment]
Metabase is installed on a MySQL server and my data are coming from a PostgreSQL server.

**Comment by paoliniluis** [comment]
It's impossible to debug what's going on without seeing the logs, also you're using Java 17 and the recommended version is Java 11. Please send the logs

**Comment by vipera7** [comment]
I'll provide the logs once the issue is replicated. Currently, the models are caching correctly.
How can I easily downgrade my Java version? Metabase is set in production mode, running the JAR file as a windows service.

**Comment by darksciencebase** [comment]
@vipera7 Has the issue ever resurfaced?

**Comment by vipera7** [comment]
The issue is outdated now
