### ISSUE TITLE
[Version v47.8] The data display in Pie chart not consistent

### ISSUE THREAD

**Issue by duongnt18** [metabase/metabase#36096]
### Describe the bug

The data display in Pie chart and and the detail data while we deep dive by move the mouse to the Piechart.

Example: The data of "lack all info" is 94, but the data display here when we move the mouse on is 2282.97
<img width="1325" alt="image" src="https://github.com/metabase/metabase/assets/19161026/6d180517-3b41-4df7-ab76-3ba8c607b1ef">

### To Reproduce

1. Create data as the capture above
2. Display with pie chart
3. Move the mouse to the pie chart to see the detail data

### Information about your Metabase installation

```JSON
- Browser : Chrome
- Version Metabsae : v47.8
```

### Severity

Confuse

**Comment by firelegacy0** [comment]
@quentinvernot 

Hey, we also had the same issue for a while, though I believe the workaround is by editing the Settings (cogwheel) for the Pie Chart Visualization itself, and change the **Minimum slice percentage** (default is 2.5%) to 0, this seems to resolve our issue.

## Edit Pie Chart's Settings:
![image](https://github.com/metabase/metabase/assets/55813746/a1a074fb-6003-4cac-826e-a158051fe85a)

## Using the sample query:
![image](https://github.com/metabase/metabase/assets/55813746/d3e292b8-5cb0-4c24-83b7-d353e19a4a8c)

**Comment by quentinvernot** [comment]
Nice, I didn't know there was an option for that.

I guess there's still a bug because the minimum displays slice size probably should not affect the numbers, but the workaround helps a lot, thanks!
