### ISSUE TITLE
BE flake: metabase.query-processor-test.filter-test/nonstandard-temporal-arithmetic-test

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#36099]
Failed for bigquery for me once
https://github.com/metabase/metabase/actions/runs/6978130163/job/18989015875?pr=36082#step:3:670

**Comment by lbrdnk** [comment]
Closing the issue as the last failure occurred ~3 weeks ago. See [this question](https://stats.metabase.com/model#eyJuYW1lIjoiVGVzdCBGbGFraW5lc3MiLCJkZXNjcmlwdGlvbiI6IkZsYWtleSB0ZXN0cyBmb3IgTWV0YWJhc2UgZnJvbSB3b3JrZmxvdyBqb2JzIHBlciB0ZXN0L2pvYi9ydW4vYnJhbmNoL2NvbW1pdC4gIFxuXG5BIHRlc3QgaXMgY29uc2lkZXJlZCB0byBiZSBmbGFrZXkgaWYgaXQgaGFzIGF0IGxlYXN0IG9uZSBwYXNzICYgZmFpbCB3aXRob3V0IGFueSBjaGFuZ2VzIChzYW1lIGNvbW1pdC9icmFuY2gvcnVuL2V0YykuICIsImRhdGFzZXRfcXVlcnkiOnsiZGF0YWJhc2UiOjI2LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOiJjYXJkX18xNDgyOCIsImZpbHRlciI6WyI9IixbImZpZWxkIiwidGVzdF9uYW1lIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwibm9uc3RhbmRhcmQtdGVtcG9yYWwtYXJpdGhtZXRpYy10ZXN0Il19fSwiZGlzcGxheSI6InRhYmxlIiwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9LCJvcmlnaW5hbF9jYXJkX2lkIjoxNDgyOH0=) on stats. If flake resurfaces, we should reopen the issue and tackle it while it's fresh.
