### ISSUE TITLE
Block data access permission setting not rendered in data permissions matrix after moving from EE to OSS

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#36090]
### Describe the bug

I had setup a group as blocked to access some table. My license expired. Now the permission level shows empty for that group/table combination.

Before:
<img width="1489" alt="image" src="https://github.com/metabase/metabase/assets/24216/ea25e67c-f404-46ed-8816-409e16989394">

After:
<img width="1483" alt="image" src="https://github.com/metabase/metabase/assets/24216/12248987-90de-432a-8a33-40c929aedbf5">

### To Reproduce

1. Setup data permissions with option "block" 
2. Load a bad license via env vars 
3. Go to data permissions
4. You will see the "block" option is missing 

### Expected behavior

If the setting is no longer available, it should be visible, if it's not because not supported, then it should be updated to some other value? We could also let the user know the config is no longer valid and how to resolve it.

### Information about your Metabase installation

```JSON
- Metabase v1.47.7
```

### Severity

It's confusing but only happens when the license expires, I am not sure what happens at the permission level

**Comment by albertoperdomo** [comment]
This also happens with Sandboxed:

Before:
<img width="1502" alt="image" src="https://github.com/metabase/metabase/assets/24216/7de62c25-8124-47ef-b24c-04e8944a95d1">
After:
<img width="1500" alt="image" src="https://github.com/metabase/metabase/assets/24216/7515c235-9183-4ab8-af78-9fcce482e2ae">

**Comment by paoliniluis** [comment]
raised to a P2, probably because the permissions will drop and could lead to an issue

**Comment by qwef** [comment]
Related: https://github.com/metabase/metabase/issues/20813

**Comment by paoliniluis** [comment]
it's a duplicate
