### ISSUE TITLE
Fine-grained permissions creating vs using (SQL) native query

### ISSUE THREAD

**Issue by ilons** [metabase/metabase#36098]
**Is your feature request related to a problem? Please describe.**
In our use of Metabase, we try to encourage our users **not** to create native (SQL) queries unless strictly needed, as that limits other users from understanding what is shown, and some UI functionality does not work (drill 

**Describe the solution you'd like**
I would like the permissions option to limit which users are able to **create** native queries, which should not impact the ability to _run_ existing native queries.

**Describe alternatives you've considered**
Restricting `Native query editing` permissions, but this also restricts users from getting the results of such queries.

**How important is this feature to you?**
It is nowhere near a blocker or deal-breaker.
This is something that would improve our work with pushing "power users" into using the UI query builder, instead of writing the query in SQL as a force of habit.

**Additional context**
I think the existing permission `Native query editing` is quite misleading, as it is a single permission for both running and creating native queries, but it is named `editing`.
The suggestion would be to split it into two:
- `Create native query` - Allow a user to run ad-hoc SQL queries, saving a SQL query as a question
- `Use native query` - Allow user to run existing native query questions

**Comment by paoliniluis** [comment]
In Metabase, the no self service permissions allow you to run SQL questions, while no seeing those. Please review the documentation
