### ISSUE TITLE
BE flake: metabase.query-processor-test.timezones-test/filter-datetime-by-date-in-timezone-relative-to-current-date-test

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#36097]
`metabase.query-processor-test.timezones-test/filter-datetime-by-date-in-timezone-relative-to-current-date-test`

This flaked for me twice for presto-jdbc. e.g.
https://github.com/metabase/metabase/actions/runs/6978130163/job/18989018539?pr=36082#step:10:643

**Comment by lbrdnk** [comment]
There are no failures for last ~3 weeks [on stats](https://stats.metabase.com/model#eyJuYW1lIjoiVGVzdCBGbGFraW5lc3MiLCJkZXNjcmlwdGlvbiI6IkZsYWtleSB0ZXN0cyBmb3IgTWV0YWJhc2UgZnJvbSB3b3JrZmxvdyBqb2JzIHBlciB0ZXN0L2pvYi9ydW4vYnJhbmNoL2NvbW1pdC4gIFxuXG5BIHRlc3QgaXMgY29uc2lkZXJlZCB0byBiZSBmbGFrZXkgaWYgaXQgaGFzIGF0IGxlYXN0IG9uZSBwYXNzICYgZmFpbCB3aXRob3V0IGFueSBjaGFuZ2VzIChzYW1lIGNvbW1pdC9icmFuY2gvcnVuL2V0YykuICIsImRhdGFzZXRfcXVlcnkiOnsiZGF0YWJhc2UiOjI2LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOiJjYXJkX18xNDgyOCIsImZpbHRlciI6WyI9IixbImZpZWxkIiwidGVzdF9uYW1lIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiZmlsdGVyLWRhdGV0aW1lLWJ5LWRhdGUtaW4tdGltZXpvbmUtcmVsYXRpdmUtdG8tY3VycmVudC1kYXRlLXRlc3QiXX19LCJkaXNwbGF5IjoidGFibGUiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e30sIm9yaWdpbmFsX2NhcmRfaWQiOjE0ODI4fQ==). Hence closing the issue. In case failure reappears, we should reopen the issue and tackle it while it's still fresh.
