### ISSUE TITLE
Replace do-with-source-and-dest-dbs macro

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#36103]
We could remove some macrology in test code and replace `do-with-source-and-dest-dbs` with an extended `with-empty-h2-app-db`, that optionally binds the database of the created database to a var whose symbol is provided by the caller. Then you could write test code that switches between dbs using `(mt/with-db source-db ...)` or something like it

Context: https://metaboat.slack.com/archives/C0641E4PB9B/p1700834887052379?thread_ts=1700811376.911959&cid=C0641E4PB9B

**Comment by crisptrutski** [comment]
I see there are 20 tests using the macro we want to deprecate - 1 command test, 7 e2e, and 12 loads tests. It probably makes sense to start by deprecating this macro updating just a single test, ideally the most complex one, to use the upgraded h2 helper, to keep turn around on the first PR fast.

Any guidance on which test to start with would be appreciated. Will look for one that resembles the one Braden suggested in the linked slack thread above.

**Comment by crisptrutski** [comment]
Wow, some scary anaphoric macros. The desire for this refactor makes a lot more sense now 😅

**Comment by crisptrutski** [comment]
I see that `with-empty-h2-app-db` rebinds two of the `perms-groups` vars, so I'm a bit hesitant to just nest these calls, still seems like a bit of a foot gun. Will dig a bit further to see if this is already happening with the deprecated macro, and how dangerous it is.
