### ISSUE TITLE
Table Metadata having 2 foreign keys from the same table pointing to the same key cause implicit joins to only show 1

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#36122]
### Describe the bug

When you have a table in which you got two columns setup as foreign key types and pointing to the same key cause the GUI editor to only show 1 of them as an implicit join and ignore completely the other

### To Reproduce

1. Go to Admin -> Table Metadata -> Sample DB -> Reviews -> Set the Rating as Foreign Key to Product ID (so it matched the Product ID one)

<img width="1510" alt="image" src="https://github.com/metabase/metabase/assets/110378427/d3be3026-04d6-4b46-9189-20b04b37ff57">

2. Go to New Question -> Reviews -> Click on Group By -> Notice only the Product is Visible and there is no Rating option

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/687b6a0b-e0d0-49dc-bd24-68ebf11b7415">

### Expected behavior

Both implicit joins are visible and selectable 

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
47.8 and `master`
```

### Severity

It's not a blocking issue since a user can still manually perform the join from the join option of the GUI but it's annoying

**Comment by kamilmielnik** [comment]
I can reproduce it in 0.47.0.
It's fixed in `master` and in 0.48.0.
Closing.
