### ISSUE TITLE
legacyExpressionForExpressionClause returns more than just the expression

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#36120]
See [Slack discussion](https://metaboat.slack.com/archives/C0645JP1W81/p1701082998021059).

```
Lib.legacyExpressionForExpressionClause(query, stageIndex, aggregationClause)
// returns ["aggregation-options", ["count"], { "name": "oko", "display-name": "oko" }

// but it should return just ["count"]
```

I also had a case like this:
```
Lib.legacyExpressionForExpressionClause(query, stageIndex, clause)
// returned ['count', null]
```

----

How to reproduce:
1. `git checkout master`
2. Create a question with [named custom expression as aggregation](https://github.com/metabase/metabase/assets/6830683/0ad90cef-518f-4289-94c3-921ac58e5eed) and save it.
3. `git checkout 35947-legacy-expression-clause-filters-and-aggregations` (#36031)
4. Open notebook editor for question created in step 2
5. Add a breakpoint in `ExpressionEditorTextfield.tsx`:
```diff
diff --git a/frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx b/frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
index 5821a97fbe..b2732ea5f7 100644
--- a/frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
+++ b/frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
@@ -88,7 +88,7 @@ function transformPropsToState(
     query,
     stageIndex,
   } = props;
-
+  debugger;
   const expression = clause
     ? Lib.legacyExpressionForExpressionClause(query, stageIndex, clause)[1] // TODO: remove [1], see https://github.com/metabase/metabase/issues/36120
     : undefined;
```
6. Click the aggregation to edit it
7. Inspect result of `metabase_lib__WEBPACK_IMPORTED_MODULE_6__.legacyExpressionForExpressionClause(query, stageIndex, clause)` ([screenshot](https://github.com/metabase/metabase/assets/6830683/58e44d3a-0604-4f34-9234-0468dba747d8))

**Comment by kamilmielnik** [comment]
> @kamilmielnik what input made `Lib.legacyExpressionForExpressionClause(query, stageIndex, clause)` produce `['count', null]`?

Follow reproduction steps from the original report, and then:
8. Focus the aggregation name input field

Then you'll hit the breakpoint from step 5 again and that's when [`null` will appear in the array](https://github.com/metabase/metabase/assets/6830683/6a302bcd-6657-43d7-83dd-192ac97cb263).

Interestingly, this `null` comes from [`Lib.expressionClauseForLegacyExpression` (it's only used in 1 place).](https://github.com/metabase/metabase/assets/6830683/8919bf1e-397a-4d8d-b388-7856ec44d045)

----

These 2 functions (`expressionClauseForLegacyExpression` and `legacyExpressionForExpressionClause`) need to be _reversible_ and complement each other in all cases. Pseudocode to illustrate:

```js
function expectExpressionReversibility(query, stageIndex, expression) {
  const clause = Lib.expressionClauseForLegacyExpression(query, stageIndex, expression);
  const expression2 = Lib.legacyExpressionForExpressionClause(query, stageIndex, clause);
  expect(expression2).toEqual(expression);
}

function expectExpressionClauseReversibility(query, stageIndex, clause) {
  const expression = Lib.legacyExpressionForExpressionClause(query, stageIndex, clause);
  const clause2 = Lib.expressionClauseForLegacyExpression(query, stageIndex, expression);
  expect(clause2).toEqual(clause); // "equal" with exception of inner UUIDs, which are expected to differ
}
```

**Comment by kamilmielnik** [comment]
> These 2 functions (`expressionClauseForLegacyExpression` and `legacyExpressionForExpressionClause`) need to be _reversible_ and complement each other in all cases. Pseudocode to illustrate:

After more debugging I think it may not be entirely possible because `ExpressionClause` contains more information than `Expression`.

**Comment by kamilmielnik** [comment]
The issue with `['count', null]` causes frontend to re-format the expression `Count` -> `Count()`

**Comment by metamben** [comment]
> These 2 functions (`expressionClauseForLegacyExpression` and `legacyExpressionForExpressionClause`) need to be _reversible_ and complement each other in all cases.

Since we strip `aggregation-options`, the operations are not reversible in general.
