### ISSUE TITLE
[MLv2] [BE] [Bug] `drill-thru/distribution` is not returned for text columns

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#36124]
Previously this drill worked for all column types except https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase-lib/queries/drills/distribution-drill.js#L4

```
type/PK
type/SerializedJSON
type/Description
type/Comment
```

It doesn't work (not returned in `availableDrillThrus`) for `type/Text` columns anymore.  We need to make sure it works for text and other column types not from the list above.

Previous implementation for the reference https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/queries/utils/actions.js#L64

Repro test https://github.com/metabase/metabase/blob/6763b43d9e426db9105a1a2bb3aa94c8e3a281cd/frontend/src/metabase-lib/tests/drills-distribution.unit.spec.ts#L175

**Comment by camsaul** [comment]
This is already fixed in `master`, see https://metaboat.slack.com/archives/C04CYTEL9N2/p1701813591813219
