### ISSUE TITLE
Get cloud-gateway-ips from an environment variable 

### ISSUE THREAD

**Issue by imrkd** [metabase/metabase#36131]
**Context**
https://metaboat.slack.com/archives/C010ZSXQY87/p1700622228090499

We now support multi-region Cloud. Each region has their own gateway-ips.

![image](https://github.com/metabase/metabase/assets/32561114/46dab91a-4f21-4cc8-8b4f-3303302a01db)

We are currently fetching cloud gateway IPs from a static json file via an api request to the store (https://github.com/metabase/metabase/blob/ddfb64e9ff46f931a6496da07b3962f8441d5689/src/metabase/public_settings.clj#L671C8-L671C8) 

Since we launched the multi-region project those IPs are different in each hosting region, and non-US customers are seeing the wrong IPs in the UI. We should be reading them from an env_var which will be set by harbormaster when creating the instance. Note, the env_var will have a coma delimited list of IPs, not a single value. 

The name of the env var is `MB_CLOUD_GATEWAY_IPS` and looks like: `1.2.3.4,5.6.7.8`

Depends on: https://github.com/metabase/harbormaster/issues/4445

**Comment by kidd** [comment]
The name of the env var is `MB_CLOUD_GATEWAY_IPS` and looks like: `1.2.3.4,5.6.7.8`

**Comment by escherize** [comment]
Since this value gets set by harbormaster, should it continue to be a publicly visible value in the app? Seems like it should be an internal value instead.
