### ISSUE TITLE
Feature: Database Specific Timezone support

### ISSUE THREAD

**Issue by bendog** [metabase/metabase#3614]
I have a situation where I report from a Django data set running on a MySQL database, Django stores it's date time in UTC on MySQL, The other databases I use have date time stored in System TimeZone.

It might be a solution to a lot of these other timezone bug reports if each database had a 'database TZ' option, so you could specify the TZ for data stored in those tables.

Database1.database-timezone = UTC
Database2.database-timezone = 'Australia/Melbourne'

Your operating system: Ubuntu 16.04
Your databases: MySQL
Metabase version: 0.20.0
Metabase hosting environment: UBUNTU default-jre-headless package
Metabase internal database: MySQL

**Comment by salsakran** [comment]
This was added in 0.26.
