### ISSUE TITLE
Apply filters is not mobile friendly

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#36148]
### Describe the bug

Our new apply filter is not friendly on small viewports

### To Reproduce

1) create a dashboard
2) disable the auto apply filters
3) see it on a mobile device

### Expected behavior

it should show at the bottom of the filters

### Logs

NA

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P2

### Additional context

![image](https://github.com/metabase/metabase/assets/1711649/7ce35762-0252-4b33-bea4-2147ec4fea19)

**Comment by kulyk** [comment]
Closing as it's fixed on master

![CleanShot 2024-02-21 at 18 50 58@2x](https://github.com/metabase/metabase/assets/17258145/eeabebfa-843d-472a-8c99-09fb4ebe2fdc)
