### ISSUE TITLE
Metabase field filter no longer accepts a single date value when the Specific Date selection is chosen and "On" is the condition

### ISSUE THREAD

**Issue by j-carlton** [metabase/metabase#36141]
### Describe the bug

Recently upgraded the software from .46 to .47.8 and the field filter variable no longer accepts a single date value when the selection is Specific Dates > On (as condition).  Date ranges work fine but the single date option was working as expected prior to the upgrade.

### Expected behavior

After the field filter date value is mapped to an existing table field, the variable should allow single dates for the "On" option, date ranges as the "Between" option, dates before a certain date as the "Before" option and dates aftera certain date as the "After" option.

### Information about your Metabase installation

```JSON
-Browser: Firefox 188.0.2 (64 bit)
-OS Windows 11 Enterprise  OS Build: 22621.2428
```

### Severity

annoying

**Comment by nemanjaglumac** [comment]
I am unable to reproduce this issue.
We should have enough E2E tests by now that make sure this functionality doesn't break.
