### ISSUE TITLE
[Auditv2] Add instructions for updating Audit V2 YAMLs if a migration breaks content loading

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#36158]
If a migration changes the database schema in such a way that it breaks audit v2 content deserialization, the only way to fix it currently is to manually edit the YAMLs according to the schema change and commit the changes. We should print a more helpful error message if content loading fails, and maybe make it a fatal error.

If these kinds of migrations are relatively rare, this may be enough of a solution here. i.e. if you drop a column or change the type of a field it should be easy enough to grep for the field name in the YAML and edit the spots it shows up.

If these migrations become more common and this becomes a pain point we can consider more automated solutions

**Comment by noahmoss** [comment]
I started working on this, but actually had trouble reproducing a case where modifying a column broke content loading—I think due to recent changes to ignore extra columns during serialization.

I'll close this for now but can revisit if this sort of issue is hit internally and we have a concrete case to address.

**Comment by escherize** [comment]
Changing a column's type should cause this error.
