### ISSUE TITLE
CSV upload support for Redshift 

### ISSUE THREAD

**Issue by Olaktal** [metabase/metabase#36166]
Hello,

**Describe the solution you'd like**
CSV upload support for Redshift 

**How important is this feature to you?**
Requested by customers

**Additional context**
None

Thanks !

**Comment by paoliniluis** [comment]
Shipped in 48.2 https://github.com/metabase/metabase/pull/37005

**Comment by calherries** [comment]
This didn't actually ship in 48.2, there was a bug in https://github.com/metabase/metabase/pull/37005. It'll be closed by https://github.com/metabase/metabase/pull/37505

**Comment by calherries** [comment]
Closed by https://github.com/metabase/metabase/pull/37505. Redshift support will go out in 49 unless anyone really needs it in 48

**Comment by rodrigotassinari** [comment]
Hi, this feature was scheduled to be included on v0.49, it even was available on the [v0.49.0-RC2 relase](https://github.com/metabase/metabase/releases/tag/v0.49.0-RC2), but was [removed](https://github.com/metabase/metabase/pull/38776) from the final [v0.49.0 release](https://github.com/metabase/metabase/releases/tag/v0.49.0).

Shouldn't then this issue be re-opened? Or is it better to create a new issue?

At my company we were really excited to finally be able to use CSV uploads, so we're tracking this issue.

**Comment by hss-iullah** [comment]
Hi has this gone out on 49.1? Thx

**Comment by hss-iullah** [comment]
Hi, I've tested in 49.1 and still not working. Can you confirm this is the case and it's actually being released in 49.2?

**Comment by calherries** [comment]
Closed by https://github.com/metabase/metabase/pull/41088. Redshift uploads will go out in the next release (49.6). Thanks for your patience everyone!
