### ISSUE TITLE
withExpressionName does not affect name/displayName of an ExpressionClause

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#36167]
Given a [simple question with custom expression aggregation](https://github.com/metabase/metabase/assets/6830683/9e90d98b-37de-4c4b-a4dc-3a720cf7669d), this is how the aggregation clause looks like:

(notice `:display-name` and `:name` in the aggregation)
![image](https://github.com/metabase/metabase/assets/6830683/b88a52c7-aca2-4d41-995b-3a5271d836fe)

Calling `Lib.withExpressionName` on that clause won't affect `:display-name` or `:name` - ~instead~ it will only add `:lib/expression-name`:

![image](https://github.com/metabase/metabase/assets/6830683/f2fb1b27-ca74-4b31-b7e9-c7789a0dfee7)

`Lib.displayName(query, clause)` won't return the name updated with `Lib.withExpressionName`.

**Comment by metamben** [comment]
I think `withExpressionName` is about changing the name of a custom column, not the name of an expression clause.
