### ISSUE TITLE
Completely remove Google Maps from an installation

### ISSUE THREAD

**Issue by andrioni** [metabase/metabase#3617]
Hi, is it possible to add a way to completely remove Google Maps from Metabase?

We got a not-so-nice notice from the Google Maps team due to unlicensed usage of the Maps API inside Metabase, and we would prefer, if possible, to just have an option to remove all chances of even loading the Maps javascript or showing users the map visualization. For now we are going to fork Metabase and try to remove everything manually, but it would certainly be better if it were something officially supported.

Thanks!

**Comment by tlrobinson** [comment]
@andrioni Sorry about that, Google eliminated "keyless" access after we built that feature, and we're planning on replacing it with Leaflet very soon (#3133 #3496).

In the meantime you'll have to either build your own jar to remove the Pin Map option, or a hackier solution would be to just remove the Google Maps JavaScript from index.html in the jar and unsign the jar, similar to what's described in #2470, but the Pin Map option will still appear but won't work.

**Comment by andrioni** [comment]
Nice, good to hear about Leaflet!

I'll go with a forked version of 0.20.0 so. I don't think there's any interest to have these changes contributed back, right? If so, I'll just build the fork on our private Docker registry and use it for now.

Thanks for the quick response!

**Comment by salsakran** [comment]
@andrioni  this is "fixed" in #3693 , which has been merged into master, and will be going out in 0.21!

**Comment by andrioni** [comment]
Great, looking forward to the release!
