### ISSUE TITLE
Show SQL on questions derived from native questions splits some operators and results in SQL error

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#36175]
### Describe the bug

When using the Show SQL function on questions derived from native questions, it seems to incorrectly split certain SQL operators, leading to incorrect SQL syntax. This issue has been observed with operators `!=` and `#>>`.

### To Reproduce

1. Create a native question: `select * from products where category != 'Widget'`
2. Save it, Explore results, Show editor
3. View the SQL 
4. (!) The SQL will have the `!=` operator split by a space: `[...] CATEGORY ! = 'Widget' [...]` , and when run, results in a syntax error.

### Expected behavior

The split should not happen.

### Logs

n/a

### Information about your Metabase installation

```JSON
Reproducible on `master`.
```

### Severity

Just annoying, but customers have run into this. 

### Additional context

https://github.com/metabase/metabase/issues/36078 is likely about the same problem.

**Comment by metamben** [comment]
@paoliniluis This is not new, 47.9 behaves the same. Why is this a P1 and why does it block 48?
