### ISSUE TITLE
Invalid json for env variable settings breaks site

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#36182]
### Describe the bug

We have a few `:json` type `defsettings` like `metabase.public-settings/custom-formatting`

An example of a well-formatted value for this is

```clojure
public-settings=> (custom-formatting)
{:type/Temporal {:time_style "HH:mm", :date_abbreviate true}}
```

We allow setting this by environmental variable like other settings. But if the json is invalid the entire application breaks.

### To Reproduce

I'm using an 0.47.5 jar:

in a terminal:

```shell
# the json is missing a closing `}`
MB_JETTY_PORT=3006 MB_CUSTOM_FORMATTING="{\"type/Temporal\":{\"time_style\":\"HH:mm\",\"date_abbreviate\":true}" java -jar 0.47.5.jar
```

From a repl to this jar we see:

```clojure
❯ netcat localhost 6006
user=> (doto 'metabase.public-settings require in-ns)
metabase.public-settings
metabase.public-settings=> (custom-formatting)
Execution error (JsonEOFException) at com.fasterxml.jackson.core.base.ParserMinimalBase/_reportInvalidEOF (ParserMinimalBase.java:696).
Unexpected end-of-input: expected close marker for Object (start marker at [Source: (StringReader); line: 1, column: 1])
 at [Source: (StringReader); line: 1, column: 63]
metabase.public-settings=>
```

And catastrophically, the application itself renders like so:

<img width="1467" alt="image" src="https://github.com/metabase/metabase/assets/6377293/6f04880b-fec7-4115-a078-bea40120d3d6">

### Logs

Interestingly enough, there are no logs generated in the terminal. The only stacktrace is rendered in the browser.

<details>
<summary>Stack trace in browser</summary>

{"via":[{"type":"clojure.lang.ExceptionInfo","message":"Error parsing Setting :custom-formatting: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (StringReader); line: 1, column: 1])\n at [Source: (StringReader); line: 1, column: 63]","data":{"setting":"custom-formatting"},"at":["metabase.models.setting$get_raw_value$parse__46770","invoke","setting.clj",554]},{"type":"com.fasterxml.jackson.core.io.JsonEOFException","message":"Unexpected end-of-input: expected close marker for Object (start marker at [Source: (StringReader); line: 1, column: 1])\n at [Source: (StringReader); line: 1, column: 63]","at":["com.fasterxml.jackson.core.base.ParserMinimalBase","_reportInvalidEOF","ParserMinimalBase.java",696]}],"trace":[["com.fasterxml.jackson.core.base.ParserMinimalBase","_reportInvalidEOF","ParserMinimalBase.java",696],["com.fasterxml.jackson.core.base.ParserBase","_handleEOF","ParserBase.java",506],["com.fasterxml.jackson.core.base.ParserBase","_eofAsNextChar","ParserBase.java",523],["com.fasterxml.jackson.core.json.ReaderBasedJsonParser","_skipWSOrEnd","ReaderBasedJsonParser.java",2520],["com.fasterxml.jackson.core.json.ReaderBasedJsonParser","nextToken","ReaderBasedJsonParser.java",698],["cheshire.parse$parse_STAR_","invokeStatic","parse.clj",65],["cheshire.parse$parse_STAR_","invoke","parse.clj",63],["cheshire.parse$parse","invokeStatic","parse.clj",100],["cheshire.parse$parse","invoke","parse.clj",88],["cheshire.core$parse_string","invokeStatic","core.clj",208],["cheshire.core$parse_string","invoke","core.clj",194],["cheshire.core$parse_string","invokeStatic","core.clj",205],["cheshire.core$parse_string","invoke","core.clj",194],["metabase.models.setting$fn__46828$fn__46829","invoke","setting.clj",615],["metabase.models.setting$get_raw_value$parse__46770","invoke","setting.clj",551],["metabase.models.setting$get_raw_value","invokeStatic","setting.clj",558],["metabase.models.setting$get_raw_value","invoke","setting.clj",517],["metabase.models.setting$fn__46828","invokeStatic","setting.clj",615],["metabase.models.setting$fn__46828","invoke","setting.clj",613],["clojure.lang.MultiFn","invoke","MultiFn.java",234],["clojure.core$partial$fn__5908","invoke","core.clj",2641],["clojure.core$partial$fn__5908","invoke","core.clj",2640],["metabase.models.setting$get","invokeStatic","setting.clj",635],["metabase.models.setting$get","invoke","setting.clj",624],["metabase.models.setting$user_readable_values_map$fn__47016","invoke","setting.clj",1267],["clojure.core$map$fn__5931$fn__5932","invoke","core.clj",2759],["clojure.core$filter$fn__5958$fn__5959","invoke","core.clj",2823],["clojure.core.protocols$iter_reduce","invokeStatic","protocols.clj",49],["clojure.core.protocols$fn__8230","invokeStatic","protocols.clj",75],["clojure.core.protocols$fn__8230","invoke","protocols.clj",75],["clojure.core.protocols$fn__8178$G__8173__8191","invoke","protocols.clj",13],["clojure.core$transduce","invokeStatic","core.clj",6947],["clojure.core$into","invokeStatic","core.clj",6962],["clojure.core$into","invoke","core.clj",6950],["metabase.models.setting$user_readable_values_map","invokeStatic","setting.clj",1261],["metabase.models.setting$user_readable_values_map","invoke","setting.clj",1248],["metabase.server.routes.index$load_entrypoint_template","invokeStatic","index.clj",81],["metabase.server.routes.index$load_entrypoint_template","invoke","index.clj",78],["metabase.server.routes.index$entrypoint","invokeStatic","index.clj",106],["metabase.server.routes.index$entrypoint","invoke","index.clj",101],["clojure.core$partial$fn__5910","invoke","core.clj",2650],["compojure.response$fn__39631","invokeStatic","response.clj",70],["compojure.response$fn__39631","invoke","response.clj",67],["compojure.response$fn__39589$G__39584__39600","invoke","response.clj",17],["compojure.response$send","invokeStatic","response.clj",27],["compojure.response$send","invoke","response.clj",22],["compojure.core$wrap_response$fn__44405","invoke","core.clj",160],["compojure.core$wrap_route_middleware$fn__44389","invoke","core.clj",132],["compojure.core$wrap_route_info$fn__44394","invoke","core.clj",139],["compojure.core$wrap_route_matches$fn__44398","invoke","core.clj",151],["compojure.core$routes$fn__44417$f__44418","invoke","core.clj",198],["compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419","invoke","core.clj",197],["metabase.server.routes$fn__112215$fn__112217","invoke","routes.clj",47],["compojure.core$routes$fn__44417$f__44418","invoke","core.clj",198],["compojure.core$routes$fn__44417","invoke","core.clj",200],["metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__108657","invoke","exceptions.clj",107],["metabase.server.middleware.exceptions$catch_api_exceptions$fn__108654","invoke","exceptions.clj",95],["metabase.server.middleware.log$log_api_call$fn__112502","invoke","log.clj",205],["metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__114646","invoke","browser_cookie.clj",42],["metabase.server.middleware.security$add_security_headers$fn__90803","invoke","security.clj",153],["metabase.server.middleware.json$wrap_json_body$fn__113202","invoke","json.clj",69],["metabase.server.middleware.offset_paging$handle_paging$fn__90827","invoke","offset_paging.clj",45],["metabase.server.middleware.json$wrap_streamed_json_response$fn__113220","invoke","json.clj",103],["ring.middleware.keyword_params$wrap_keyword_params$fn__114913","invoke","keyword_params.clj",55],["ring.middleware.params$wrap_params$fn__114932","invoke","params.clj",77],["metabase.server.middleware.misc$maybe_set_site_url$fn__57251","invoke","misc.clj",61],["metabase.server.middleware.session$reset_session_timeout$fn__71750","invoke","session.clj",457],["metabase.server.middleware.session$bind_current_user$fn__71717$fn__71718","invoke","session.clj",352],["metabase.server.middleware.session$do_with_current_user","invokeStatic","session.clj",331],["metabase.server.middleware.session$do_with_current_user","invoke","session.clj",315],["metabase.server.middleware.session$bind_current_user$fn__71717","invoke","session.clj",351],["metabase.server.middleware.session$wrap_current_user_info$fn__71698","invoke","session.clj",285],["metabase.server.middleware.session$wrap_session_id$fn__71681","invoke","session.clj",217],["metabase.server.middleware.auth$wrap_api_key$fn__100301","invoke","auth.clj",30],["ring.middleware.cookies$wrap_cookies$fn__114833","invoke","cookies.clj",216],["metabase.server.middleware.misc$add_content_type$fn__57233","invoke","misc.clj",29],["metabase.server.middleware.misc$disable_streaming_buffering$fn__57259","invoke","misc.clj",78],["ring.middleware.gzip$wrap_gzip$fn__114875","invoke","gzip.clj",86],["metabase.server.middleware.misc$bind_request$fn__57262","invoke","misc.clj",95],["metabase.server.middleware.ssl$redirect_to_https_middleware$fn__114662","invoke","ssl.clj",41],["metabase.server$async_proxy_handler$fn__79487","invoke","server.clj",77],["metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a","handle",null,-1],["org.eclipse.jetty.server.handler.StatisticsHandler","handle","StatisticsHandler.java",173],["org.eclipse.jetty.server.handler.HandlerWrapper","handle","HandlerWrapper.java",122],["org.eclipse.jetty.server.Server","handle","Server.java",563],["org.eclipse.jetty.server.HttpChannel","lambda$handle$0","HttpChannel.java",505],["org.eclipse.jetty.server.HttpChannel","dispatch","HttpChannel.java",762],["org.eclipse.jetty.server.HttpChannel","handle","HttpChannel.java",497],["org.eclipse.jetty.server.HttpConnection","onFillable","HttpConnection.java",282],["org.eclipse.jetty.io.AbstractConnection$ReadCallback","succeeded","AbstractConnection.java",314],["org.eclipse.jetty.io.FillInterest","fillable","FillInterest.java",100],["org.eclipse.jetty.io.SelectableChannelEndPoint$1","run","SelectableChannelEndPoint.java",53],["org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy","runTask","AdaptiveExecutionStrategy.java",416],["org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy","consumeTask","AdaptiveExecutionStrategy.java",385],["org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy","tryProduce","AdaptiveExecutionStrategy.java",272],["org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy","lambda$new$0","AdaptiveExecutionStrategy.java",140],["org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread","run","ReservedThreadExecutor.java",411],["org.eclipse.jetty.util.thread.QueuedThreadPool","runJob","QueuedThreadPool.java",936],["org.eclipse.jetty.util.thread.QueuedThreadPool$Runner","run","QueuedThreadPool.java",1080],["java.lang.Thread","run","Thread.java",833]],"cause":"Unexpected end-of-input: expected close marker for Object (start marker at [Source: (StringReader); line: 1, column: 1])\n at [Source: (StringReader); line: 1, column: 63]","message":"Error parsing Setting :custom-formatting: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (StringReader); line: 1, column: 1])\n at [Source: (StringReader); line: 1, column: 63]","setting":"custom-formatting"}

</details>

### Information about your Metabase installation

```JSON
it's 0.47.5 jar
```

### Severity

since i'm the first reporter it seems not hit in the wild, but pretty serious bug

**Comment by dpsutton** [comment]
There are several different ways we could go. But I don't have an opinion on what we should do.

Options:
- safely parse it and ignore it if its invalid
- check on startup that all (just json?) env settings are valid according to their type and fail to start up with helpful error messages
- maintain the same behavior but with a better error message pointing to which env var (DO NOT INCLUDE ITS VALUE)

I think this is a good thing to wrestle with product with. There is also no big timescale on this because at the moment there are no people hitting this because it doesn't just silently work, and we don't have very many json settings that people use.

**Comment by darksciencebase** [comment]
@luizarakaki

**Comment by crisptrutski** [comment]
@luizarakaki did you have a chance to thing about which behaviour would be best here?

I lean towards the "fail on startup" approach because I think it will be the most transparent to operators, who are best positioned to debug and fix the config. Killing the process might also cause breaking deployment to abort or rollback, preventing impact to end users.

**Comment by luizarakaki** [comment]
@crisptrutski agreed. Fail on startup seems the best to me.
