### ISSUE TITLE
Can't export files when in embbed mode

### ISSUE THREAD

**Issue by NunesPX** [metabase/metabase#36207]
### Describe the bug

When use Microsoft Gateway, all export methods returns "_API not found_", in our infrastructure us made a redirect from a domain to another domain and when matebase tries call an export API apearance one url malformed. Bellow an example:

Metabase generate
https://api-****.hubie.cloud/dash/api/embedboard/

But that should be it
https://api-****.hubie.cloud/api/embed/dashboard/ 

For some reason metabase is changing the form of the URL causing the error on our gateway.
This error not appearing on earlier version, that's began to occur on current version.

### To Reproduce

1. Go to Any panel
2. Click on 'Download Results'
2. Click on '.csv' and dowload the file

### Expected behavior

See exported data on CSV file

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.15.131.1-2.cm2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v0.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Critical

**Comment by paoliniluis** [comment]
you're using Metabase in a subdomain right?

**Comment by NunesPX** [comment]
Yes, i use it
