### ISSUE TITLE
Create a test to prevent serialization bugs with new settings

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#36240]
This bug https://github.com/metabase/metabase/issues/36232 happened because we created new settings, but they weren't added to the list of settings to be serialized, when they should have been. We should have a test that forces engineers introducing new settings to choose whether or not to add it to the exported list of settings.

**Comment by crisptrutski** [comment]
- [x] [Add mechanism for explicit import.](https://github.com/metabase/metabase/pull/37624)
- [x] [Make all exported settings explicit in their definition.](https://github.com/metabase/metabase/pull/37640)
- [ ] Make it impossible to add new settings without explicit `:export?` in definition.
