### ISSUE TITLE
Instrument dashboard endpoint performance

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#36274]
When a dashboard loads, the following directly related API calls are made (These examples use `localhost` as the host, but this can be replaced with the actual host):
* `http://localhost:3000/api/dashboard/:id`, which returns a _hydrated_ dashboard containing the dashboard, dashcards, and all other data needed to display the board.
* `http://localhost:3000/api/collection/:id` is sometimes called
* `http://localhost:3000/api/dashboard/:dashboard-id/dashcard/:dashcard-id/card/:card-id/query` is called for each dashcard in the dashboard

A few other endpoints are called (e.g. user, session, database, schema), but they don't stand out as locations that need instrumentation based on the network tab when looking at dashboard loads.

<img width="1122" alt="image" src="https://github.com/metabase/metabase/assets/8381441/89d602c9-5786-45ae-8174-c847d7b5d349">

Spans already exist for the following endpoints/functions:
- By default, we get instrumentation on all HTTP actions
- `get-dashboard` along with the subcomponents of `api/defendpoint GET "/:id"` are well instrumented
- `run-query-for-dashcard-async` has a span. This covers the body of `api/defendpoint POST "/:dashboard-id/dashcard/:dashcard-id/card/:card-id/query"`

With the fix in #35895 for slow dashboard loads, it seems like our next bottleneck is individual card loading performance. Not only can these be slow, but Chrome only allows 6 concurrent connections per domain.

At this point, we have a few potential next steps for performance improvements:
- Get `spanmetrics` working so we can view duration stats in grafana
- Profile the query code for hot spots and iterate on discoveries

**Comment by markbastian** [comment]
On stats we actually have a [Top 20 P90 Backend performance report](https://grafana.monitoring.metabase.com/d/wOByfRSIz/top-20-backend-api-avg-p90-performance?orgId=1&var-p90=All&var-targets=All&var-service=metabase&var-method=All).

**Comment by markbastian** [comment]
Closing this per discussion with @perivamsi since instrumentation is in place and we know where to look.
