### ISSUE TITLE
Remove unused API endpoints

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3627]
According to @tlrobinson the following are no longer used and can be removed.

- [x] `GET /api/card/:cardId/favorite`
- [x] `GET /api/database/:dbId/tables`
- [ ] `GET /api/table/:tableId`
- [x] `GET /api/table/:tableId/fields`
- [x] `POST /api/table/:tableId/reorder`
- [x] `POST /api/table/:tableId/sync`
- [ ] `GET /api/field/:fieldId`
- [x] `PUT /api/setting/`
- [x] `DELETE /api/setting/:key`
- [ ] `GET /api/user/:userId`
- [x] `GET /api/dataset/card/:id` (?)

These shouldn't be removed because they should be used in the future to fix #3454:

- [ ] `GET /api/field/:fieldId/summary`
- [ ] `GET /api/field/:fieldId/values`
- [ ] `POST /api/field/:fieldId/value_map_update`

**Comment by salsakran** [comment]
wrt 
```
GET /api/field/:fieldId/summary
GET /api/field/:fieldId/values
POST /api/field/:fieldId/value_map_update
```

are they being done somewhere else? Do we still have the value_map code? it would solve eg #3454

**Comment by camsaul** [comment]
@salsakran unfortunately it looks like at some point that functionality was removed from the frontend. I didn't realize that was the case so I'm not sure when it happened 😓 

But we can keep those endpoints around so they're ready to go if we want to put the functionality back in
