### ISSUE TITLE
MB_DB_FILE can write to HDFS

### ISSUE THREAD

**Issue by djvulee** [metabase/metabase#3632]
When we run metabase on Mesos Marathon, if the Marathon can not support the persistent storage, the metadata for the Metabase itself will lost, store the information in a Postgres/MySQL is not simple than just offer a HDFS file. 

If we can set like the following, it would be very simple.

```
export MB_DB_FILE=hdfs://mypath
```

**Comment by tlrobinson** [comment]
I think it's unlikely we'll support this directly. We really recommend using Postgres or MySQL in production. We've seen corruption issues with H2 in the past, though we think we've made some progress making it more robust.

You could try mounting HDFS with Fuse and point `MB_DB_FILE` there, or maybe have a script that copies to and from HDFS periodically (with the obvious caveat that if the container is killed without a final copy to HDFS you'll lose some data)

**Comment by salsakran** [comment]
Given the I/O patterns of H2, we won't be looking to support HDFS. 

Like Tom said, if you're at the point where you have a Mesos cluster running, you should *really* be using a real database for metabase application data.

**Comment by djvulee** [comment]
I got your idea, thanks for your reply!
