### ISSUE TITLE
Elastic Beanstalk Artifact File hasn't been made available after v47.2

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#36332]
### Describe the bug

[Last published ElasticBeanstalk Artifact file](https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-elastic-beanstalk#upgrade-your-elastic-beanstalk-deployment) is for v47.2. 

### To Reproduce

The download links doesn't work for versions after 47.2 (e.g. for latest version https://downloads.metabase.com/v0.47.9/metabase-aws-eb.zip)

### Information about your Metabase installation

```JSON
v47.2
```

### Severity

Blocking Upgrade

**Comment by paoliniluis** [comment]
This is on purpose, we added a guide for upgrading beanstalks manually but we won’t push any other artifacts from now on. Beanstalk has too many problems and it’s difficult to debug when something goes wrong, so we decided to deprecate the artifacts
