### ISSUE TITLE
Feature Request/Bug: Limited Colors for Bar Chart Stacking Option

### ISSUE THREAD

**Issue by kritop** [metabase/metabase#3633]
- Your browser and the version: Chrome 54
- Your operating system: OS X Sierra
- Your databases: MysQL
- Metabase version: 0.20.1
- Metabase hosting environment: Heroku
- Metabase internal database: default

see here

http://look.neta.io/hotJ

I can only select 5 different colors, even if i can stack way more values.

**Comment by mazameli** [comment]
Hmm, yeah, we should be using the same logic for extra colors here as we do for pie/donut charts. Is this a bug or a limitation @tlrobinson / @kdoh ?

**Comment by kdoh** [comment]
I think this is just an oversight. We just need to apply the same color harmony to bar charts we do to pie slices when the number of slices is > 5. 

It'd be rad if we could find a way to standardize that logic across all our chart types.

**Comment by tlrobinson** [comment]
Sort of a duplicate of #3185.

Do we want all of those colors to appear in the picker, or maybe have a custom color picker?

**Comment by kritop** [comment]
thanks for looking into this! is there a general limit, because it seems sometime if the "stackable" axis is to large it just fails to produce a bar chart?

**Comment by camsaul** [comment]
@kritop, this isn't a bug 😒

**Comment by camsaul** [comment]
@tlrobinson I think this does sound like a duplicate of #3185

**Comment by camsaul** [comment]
Duplicate of #3185
