### ISSUE TITLE
Fix and uncomment flaky tests in `metabase-enterprise.audit-app.permissions-test`

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#36345]
Some tests in `metabase-enterprise.audit-app.permissions-test` introduced by  [disable can-write for cards and dashboards in default audit collection](https://github.com/metabase/metabase/pull/36237) were flaking frequently so I commented them out https://github.com/metabase/metabase/pull/36341 to unblock master.

We should fix the flakiness and uncomment them.

Here are some errors:
https://github.com/metabase/metabase/actions/runs/7062703250/job/19230026705#step:5:2668
https://github.com/metabase/metabase/actions/runs/7062703250/job/19230026705#step:5:2750

And here are some failures:
https://github.com/metabase/metabase/actions/runs/7062703250/job/19230026705#step:5:2742
https://github.com/metabase/metabase/actions/runs/7062703250/job/19230026705#step:5:2746

**Comment by dpsutton** [comment]
https://github.com/metabase/metabase/pull/36331

PR that addresses it: https://github.com/metabase/metabase/pull/36331 Just need someone to finish it out
