### ISSUE TITLE
Allow HTML in prefix/suffix and around card values

### ISSUE THREAD

**Issue by tmaiaroto** [metabase/metabase#3635]
Feature request here. It would be really nice to allow HTML in the prefix/suffix for dashboard cards. Original thought wasn't actually full blown HTML, it really came out of the thought - "hey, it'd be neat to put a Font Awesome icon before the number here."

...But I then figured well why not just HTML? It would be nice to add some additional styling around card values. Perhaps coloring the numbers even (conditionally?)? A field for inline styles? 

I think just a few tiny (but _conservative_) additional features here would make the world of difference for many dashboards. 

I'm new to Metabase, but I love it. If I can, I'll work on making a pull request if people think it's a good idea and remains consistent with project scope...But I figured it was best to just get an issue out first in case there's already a solution or someone else has ideas or can add it in sooner. Thanks!

**Comment by salsakran** [comment]
We'd definitely consider a way to get icons, currency symbols etc in the prefix/suffix.

I don't think free form html is really within the "zen" of Metabase. Our goal is a clean consistent, elegant user interface. Free form html reminds me too much of Myspace. =)

**Comment by tmaiaroto** [comment]
Oh I know what happens when you unleash the beast =)
Any thoughts around conditional coloring/formatting?

**Comment by flamber** [comment]
Closing, since 0.31 introduced a lot of formatting options including conditional formatting (and since we're likely not going to allow arbitrary HTML)
https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#column-formatting-options
Related #1903
