### ISSUE TITLE
Permission group list doesn't scroll when adding a new user.

### ISSUE THREAD

**Issue by mattxbart** [metabase/metabase#3636]
When adding a new user, you cannot scroll through the available permission groups. Clicking the select list only brings up a non-scrolling dialogue. When the list of groups is lengthy the dialog moves off the screen and you cannot select non visible groups. If the dialog would scroll it would solve the issue. 

Thanks!
- Your browser and the version: Chrome 53
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.20.0
- Metabase hosting environment: Linux/Ubuntu 16
- Metabase internal database: Postgres

**Comment by salsakran** [comment]
out of curiosity, how many permissions groups do you have?

**Comment by mattxbart** [comment]
We have 23. Each one is viewing a restricted select of one main database view.
