### ISSUE TITLE
Can't edit metadata for models with several columns

### ISSUE THREAD

**Issue by renatodossantosleal** [metabase/metabase#36364]
### Describe the bug

When working with models in metabase 0.47.8 I cannot edit metadata on models that have more than 30+ columns.
The behavior is when editing a model (after its creation) we try to click on a column far on the right and what happens is that a column at the beginning of the table is actually selected on the right side (detail side). 

**Bug first reported in**: [https://discourse.metabase.com/t/not-able-to-select-specific-columns-in-edit-metadata-when-working-with-model/26059](https://discourse.metabase.com/t/not-able-to-select-specific-columns-in-edit-metadata-when-working-with-model/26059)
 

### To Reproduce

1. Go to a model with 30+ columns and select edit metadata.
2. Try to edit a column at the end of the table (i.e. column number 40)
3. See error (column details are from another column, not the one selected)

### Information about your Metabase installation

```JSON
- Your browser and its version: Versão 119.0.6045.199 (Versão oficial) 64 bits
- Your operating system: ( Ubuntu 22.04.3 LTS )
- The type of database(s) you've connected to Metabase: (Redshift)
- The version of Metabase you're running: ( 0.47.8 )
- Hosting Env: EKS
- Metabase's internal database type: (Postgres)
```

### Severity

High

### Additional context

We cannot work with big models because of this error, preventing us to move to metabase as our solution. (We have 20+ models like this)

**Comment by paoliniluis** [comment]
Thanks, we'll release v48 in the next few days, can you check if this has been fixed?

**Comment by ignacio-mb** [comment]
Hi @renatodossantosleal is this still happening in 48?

**Comment by mikeflynn** [comment]
I'm still seeing this issue on 0.48.4
