### ISSUE TITLE
Heroku source deploy broken due to switch to Yarn

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#3639]
Oops, might have been a little too eager to aggressively deprecate Yarn. Heroku needs to add support to the Node buildpack. #337

This shouldn't affect `metabase-deploy`, only deploying from source.

One workaround is to remove the `preinstall` script from `package.json` before pushing to Heroku, but since we removed the `npm-shrinkwrap.json` your dependencies aren't guaranteed to be consistent with `yarn.lock`, so you should probably `npm shrinkwrap` as well.

I'm thinking we should just remove (or replace with a less aggressive) that `preinstall` script and commit both `yarn.lock` and `npm-shrinkwrap.json` for now :-/

**Comment by tlrobinson** [comment]
Actually looks like they've got a branch with yarn support https://github.com/heroku/heroku-buildpack-nodejs/issues/337#issuecomment-253286196 Giving it a try now.

**Comment by hunterloftis** [comment]
How is that branch working for you?

**Comment by tlrobinson** [comment]
@hunterloftis It seems to work great. Thanks! Any ETA on merging that branch? Otherwise I can just add `#yarn` to our script for now.
