### ISSUE TITLE
Update alert shouldn't call update card API

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#36395]
### Describe the bug

When updating an alert, we call `PUT /api/card/:id` before calling `PUT /api/alert/:id` even though the card didn't change

### To Reproduce

1. Setup email
2. Create a new card
3. Setup alert and save

### Expected behavior

We probably don't need the update card API call

### Information about your Metabase installation

```JSON
master
```

### Severity

low, but it slows down the application and burn uncessary CPU cycles

**Comment by rafpaf** [comment]
Hi @qnkhuat, I'm not yet sure how to reproduce this. When I make an alert, I only see a POST to `/api/alert/`. Here's a [short screencast](https://www.loom.com/share/99bb393220e842be9a53aed4debf5b19?sid=a6a345d4-57c3-46b8-99b7-fd1225065c6b).
