### ISSUE TITLE
scatter plot series labels

### ISSUE THREAD

**Issue by im360admin** [metabase/metabase#3640]
Using Chrome on windows 10
Mysql DB
metabase 0.20.1 on Elastic Beanstalk / Postgres

When creating a scatter plot, both x and y axis has to be numeric fields.  When hovering over the points, how do I get a data field to display?

**Comment by salsakran** [comment]
We currently don't have a way to do that. What are you trying to display?

**Comment by im360admin** [comment]
The name of a product that meets the sell-thru and profitability matrix

**Comment by drewnewell** [comment]
I would like to second this proposal -- I think it is an equivalent of a label series so when you hover over a point you can see additional data - like product id or customer name.

**Comment by rafaelveloso** [comment]
+1

**Comment by tlrobinson** [comment]
This should be fixed in `master`.
