### ISSUE TITLE
Cannot rename a data series when the label is too long - label appears on top of the input value

### ISSUE THREAD

**Issue by Startouf** [metabase/metabase#36421]
### Describe the bug

In those screenshots, the label of the field (distinct xxx) is too long and seems to be on top of the input, making the value unreachable and not editable.

I was able to select and highlight something (which I thought was the value) but it seems like my browser did not let me change the value "clics" to something else, so the highlighted stuff must have been something else

![Screenshot 2023-12-05 at 18 15 58](https://github.com/metabase/metabase/assets/7388889/cb51b8c7-7845-4d72-9e8d-651f51a3039c)
![Screenshot 2023-12-05 at 18 16 03](https://github.com/metabase/metabase/assets/7388889/8d96bc8a-2bb3-4d42-b7ae-1e613d91f8f7)

### To Reproduce

1. Create a query with a join and long names
2. create a visualization with multiple series
3. Try to edit one series' name

### Expected behavior

The name should be editable despite having a long "label"

### Information about your Metabase installation

```JSON
- Chrome Version 119.0.6045.199 (Official Build) (arm64)
- Metabase 0.47.9
- Self hosted on kubernetes using chart https://pmint93.github.io/helm-charts v2.7.6 and changing image tag to 0.47.9
```

### Severity

Annoying. I had to open the console, delete the label, so that I could write inside. It could be blocking to some non-tech users

**Comment by EmmadUsmani** [comment]
https://github.com/metabase/metabase/assets/37751258/aac0ebcb-ad02-4556-a2a9-b5ccae837cf2

Ideal solution would be to switch to a Mantine input

**Comment by EmmadUsmani** [comment]
![image](https://github.com/metabase/metabase/assets/37751258/739dbf0e-9a3b-4591-83b7-7052e4398eaf)

This also happens in the model metadata editor.

**Comment by anandromy** [comment]
Hey, @EmmadUsmani, Can I work on this?
