### ISSUE TITLE
Revision history is using an incorrect date

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3643]
When I edit a segment, the revision timestamp is incorrect. Eg, I just made a change to a segment in staging. The activity feed has the correct time of "a few seconds ago" but the segment revision history has what seems to be the server start time. 

![screen shot 2016-10-21 at 11 29 40 am](https://cloud.githubusercontent.com/assets/107439/19607902/cae6c2a8-9781-11e6-8805-b9bf4230936e.png)

see also http://discourse.metabase.com/t/history-stuck-on-date-in-the-past/792

**Comment by salsakran** [comment]
this also seems to affect the question changelog as shown in http://discourse.metabase.com/t/history-stuck-on-date-in-the-past/792

**Comment by salsakran** [comment]
@camsaul in https://github.com/metabase/metabase/blob/master/src/metabase/models/revision.clj#L67
it looks like `(u/new-sql-timestamp)` is getting called when the function is being defined rather than on every invocation.

**Comment by camsaul** [comment]
Yup this should be an easy enough fix

**Comment by camsaul** [comment]
Fixed by #3659
