### ISSUE TITLE
Dashcard in the "Metabase metrics" dashboard is missing data

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#36447]
### Describe the bug

The "alerts and subscriptions created last week" dashcard is not rendering.

https://stats.metabase.com/dashboard/2102-metabase-metrics?date_filter=past52weeks&user_group=All%20Users

<img width="1025" alt="Screenshot 2023-12-05 at 8 42 12 PM" src="https://github.com/metabase/metabase/assets/127636/be9cd158-0209-4274-92a8-beeed5fdec08">

### To Reproduce

1. Go to https://stats.metabase.com/dashboard/2102-metabase-metrics?date_filter=past52weeks&user_group=All%20Users
2. See that "alerts and subscriptions created last week" dashcard is not rendering
3. Click on the header of the dashcard or go to the [question directly ](https://stats.metabase.com/question#eyJuYW1lIjoiQWxlcnRzIGFuZCBzdWJzY3JpcHRpb25zIGNyZWF0ZWQgbGFzdCB3ZWVrIiwiZGVzY3JpcHRpb24iOm51bGwsImRhdGFzZXRfcXVlcnkiOnsiZGF0YWJhc2UiOjEzMzcxMzM3LCJxdWVyeSI6eyJhZ2dyZWdhdGlvbiI6W1siY291bnQiXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsImNyZWF0ZWRfYXQiLHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIiwidGVtcG9yYWwtdW5pdCI6IndlZWsifV1dLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDU3NjYyNix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJRdWVzdGlvbiAzNCJ9XSwiQWxsIFVzZXJzIl0sWyI9IixbImZpZWxkIiw1NzY2MjYseyJqb2luLWFsaWFzIjoiUXVlc3Rpb24gMzQifV0sIkFsbCBVc2VycyJdXSwiam9pbnMiOlt7ImFsaWFzIjoiUXVlc3Rpb24gMzQiLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsNTc2NzA5LHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dLFsiZmllbGQiLDU3NjYyNSx7ImJhc2UtdHlwZSI6InR5cGUvSW50ZWdlciIsImpvaW4tYWxpYXMiOiJRdWVzdGlvbiAzNCJ9XV0sImZpZWxkcyI6ImFsbCIsInNvdXJjZS10YWJsZSI6ImNhcmRfXzE0MjMyIn1dLCJzb3VyY2UtdGFibGUiOiJjYXJkX18xNDI0MyJ9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InNtYXJ0c2NhbGFyIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsiY3JlYXRlZF9hdCIsImdyb3VwX25hbWUiXSwiZ3JhcGgubWV0cmljcyI6WyJjb3VudCJdfSwib3JpZ2luYWxfY2FyZF9pZCI6MTQyNTd9)
4. The data loads properly

### Information about your Metabase installation

```JSON
Stats
```

### Severity

??

**Comment by noahmoss** [comment]
This card has been fixed, but we're still seeing an issue with the `Member of` question on the People dashboard, so I'm keeping this issue open

**Comment by luizarakaki** [comment]
Fixed by https://github.com/metabase/metabase/pull/36658
