### ISSUE TITLE
Question Corrupt - Columns not shown

### ISSUE THREAD

**Issue by fschloegl** [metabase/metabase#36466]
### Describe the bug

I added 2 more columns to an old (2 years since the last edit) question. The colums are shown up in the "raw" view (marked yellow)
![image](https://github.com/metabase/metabase/assets/13234252/9bf8e7f0-a02e-4643-ac02-c47bc4948b4c)

but they are not shown up in the "visualization" view
![image](https://github.com/metabase/metabase/assets/13234252/0ba85f52-9f6c-4a29-b1a9-93c760e369bf)

If I switch to an other visualitation type eg. pivot, the new columns are shown up
![image](https://github.com/metabase/metabase/assets/13234252/91ec0fd7-198b-47a5-84ba-dbaa72ac3342)

If I delete one old summarize, one new one is showing up.

### To Reproduce

It's not possible to reproduce. Other questions are working

### Expected behavior

the existing columns are to be displayed

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "de",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.0-21-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Vienna"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.16 (Debian 11.16-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-01",
      "tag": "v0.47.9",
      "branch": "?",
      "hash": "d05b06e"
    },
    "settings": {
      "report-timezone": "Europe/Vienna"
    }
  }
}
```

### Severity

blocking some users

**Comment by paoliniluis** [comment]
Can you post the question api result?

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/pull/40398
