### ISSUE TITLE
Top navbar is unnecessarily tall

### ISSUE THREAD

**Issue by diwu1989** [metabase/metabase#3649]
currently, navbar is:
![image](https://cloud.githubusercontent.com/assets/380950/19616519/b2306e6a-97c9-11e6-92f2-22b21430c3fa.png)

how about taking out some top and bottom padding to be more compact?
![image](https://cloud.githubusercontent.com/assets/380950/19616517/a479daa4-97c9-11e6-953c-9ec5438afd44.png)

**Comment by kdoh** [comment]
Done in #6122
