### ISSUE TITLE
Let creators swap out dashboard questions with a different question

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#36497]
## Context

- [Product doc](https://www.notion.so/metabase/Let-creators-swap-out-dashboard-cards-with-something-else-1cbb54963f06471885d5bc2cea608dcb)
- #36586

The project seems small enough not to need a feature branch

## Tasks

- [x] #36589
- [ ] Add "Replace card" feature

**Comment by paoliniluis** [comment]
@cdeweyx I just tested this one and I couldn't get the filter to stick to the replaced card
![image](https://github.com/metabase/metabase/assets/1711649/5d4fcc8b-b64d-441f-a3eb-203d23b40a12)


The new card had the same fields, but not the same amount of columns. Is that the reason why the filter didn't link?

**Comment by cdeweyx** [comment]
> @cdeweyx I just tested this one and I couldn't get the filter to stick to the replaced card ![image](https://private-user-images.githubusercontent.com/1711649/303105357-5d4fcc8b-b64d-441f-a3eb-203d23b40a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDc0MTYsIm5iZiI6MTcwNzM0NzExNiwicGF0aCI6Ii8xNzExNjQ5LzMwMzEwNTM1Ny01ZDRmY2M4Yi1iNjRkLTQ0MWYtYTNlYi0yMDNkMjNiNDBhMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMjMwNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmRiMzg5MGY5OTI0MTU1MzcxZWQ3NGNkMTBhYzRlMmI2MGRiNWQxY2UxMDIxMGZhZWQzMGRlYTUyMTMxMDdhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hi6hhfpqD7kNxKPJ32FRJA-tgFMHJwz73Jxid6j96lE)
> 
> The new card had the same fields, but not the same amount of columns. Is that the reason why the filter didn't link?

Is that the only card on your dash? If so: Auto-wire looks at other cards currently on the dashboard, so if you replace, we remove that card and then add another, and in that moment there's no other cards to detect re auto-wiring. Just repro'ed this on stats. I think it would be nice, but would require us to change the logic a bit for auto-wire.

If it's not that, maybe it's https://github.com/metabase/metabase/issues/35764
