### ISSUE TITLE
"Number of Distinct Values" is treated as categorical column

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#36508]
### Describe the bug

When I want to filter based on "Summaries", if the aggregate is "Number of Distinct Values", it is treated as categorical and doesn't show "greater than", etc.

### To Reproduce

- Simple Question > Sample Database > PEOPLE
- "Number of distinct values of" Email, group by Source
- Now filter the aggregate value and select "Distinct values of Email", it doesn't show "greater than" or other numerical selections. (side-note: instead of "Distinct values of Email" it should say "Number of Distinct values of Email")
<img width="851" alt="Screenshot 2023-12-06 153918" src="https://github.com/metabase/metabase/assets/15974735/94f1c545-c782-46cf-9e3a-3d68a9adecc2">

### Expected behavior

"number of distinct values" summarization type should be numerical not categorical

### Information about your Metabase installation

```JSON
v47.9
```

### Severity

Limitting the usage

**Comment by kamilmielnik** [comment]
Reproducible in 48.0.
Cannot reproduce in 49.0 ([screenshot](https://github.com/metabase/metabase/assets/6830683/9104a8f0-71f4-4247-96c7-4332d3831b33))
