### ISSUE TITLE
legend and axis label become `sum` in multi-line cards in dashboard after upgrade to v0.20.0

### ISSUE THREAD

**Issue by StaymanHou** [metabase/metabase#3651]
It happens to all my multi-line cards in dashboard.

Before upgrading to v0.20.0, it was showing the title of each question. And now it's all `sum`. BTW, all my questions are calculating the sum.

![selection_012](https://cloud.githubusercontent.com/assets/5069041/19619943/140a2286-9840-11e6-8cfe-65bea7e619d3.png)

**Comment by tlrobinson** [comment]
This should already be fixed in 0.20.1. Could you upgrade and let me know? Thanks.

**Comment by tlrobinson** [comment]
Possible duplicate of #3545

**Comment by StaymanHou** [comment]
:+1: fixed after upgrading to 0.20.1
