### ISSUE TITLE
A previously functioning chart can no longer be opened, but a duplicate of it can-ish

### ISSUE THREAD

**Issue by grumBit** [metabase/metabase#36513]
**Description**
A previously functioning pivot chart can no longer be opened, but a duplicate of it can, but is doesn't show everything it should. 

We have an existing chart that had been functioning, but now when we open it, we get "Error running query". 

If we then duplicate the broken chart without making any changes to it at all, the duplicated chart will open mostly correctly. If in the original, `Show row totals` had been selected, the row totals do not appear in the duplicated chart, however, everything else does, including column totals.

This is the primary problem, however, there are a number of other related problems that I have described below in the Additional Context section. Reading these might be helpful in diagnosing the primary problem?

**Logs**

- Javascript console log

![metabase_javascript_console_log](https://github.com/metabase/metabase/assets/19850226/d93e4b53-18fe-4916-a84b-f0eb5c6d5c39)

- Complete server log. 
  - This is the entire entry for the error in the server log. Whenever the chart is opened, a new error with similar contents is written to the log. 
[metabase_server_log_raw_complete.log](https://github.com/metabase/metabase/files/13592740/metabase_server_log_raw_complete.log)

- Raw SQL Query from log
  - This is just the query from the log entry that is marked as failed
[metabase_server_log_raw_query.log](https://github.com/metabase/metabase/files/13592742/metabase_server_log_raw_query.log)

- Run-able SQL query from log
  - This is the query having been re-formatted so it can be run directly in the Snowflake webUI
[metabase_server_log_runable_query.md](https://github.com/metabase/metabase/files/13592790/metabase_server_log_runable_query.md)

- Output from Snowflake when the query above is run
  - **NOTE**: The count values correspond to the column totals, but all other data for the chart is missing.

| pivot-grouping      | count | count_2 |
| ------------------- | ----- | ------- |
| 9223372036854775801 | 4885  | 37553   |

**To Reproduce**
- Navigate to the dashboard: `Clients` -> `AGNSW` -> `AGNSW Pladia Report [WIP]`
- Click on the pivot chart `Object sessions and interactions`

**Expected behavior**
The chart opens and displays these results;
![working_chart](https://github.com/metabase/metabase/assets/19850226/64b7d08d-5618-40db-a2e0-9f6807790273)

**Screenshots**

**Severity**

For us, this is a severe bug as our customer is expecting to see these results and they have expressed their dissatisfaction that we can't deliver the analytics they we believed we could using Metabase. We have a workaround that gives partial results, but it does not meet our customers requirements and they are still dissatisfied. In addition, we have put considerable time into trying to get this working, which is annoying.

**Additional context**

These are some additional notes about related problematic behaviour that may help diagnose the issue;

1. There are hidden row totals in the duplicated chart.

  Going into the duplicated chart settings, `Show row totals` is shown as selected. De-selecting it immediately includes the row totals and greys out the chart, so I assume the query had the results, but it wasn't being displayed by the UI until it was de-selected. After "doing science" completes, the chart continues to display the row totals AND shows `Show row totals` as **de**-selected.

2. Saving changes to the duplicated chart makes it break

  Making any changes to the working duplicated chart (e.g. de-selecting `Show row totals`) and then saving it seems to work fine. However, if you leave the chart or refresh the page, it breaks in the same way as the original.

3. Making changes to the broken chart fixes the problem, but the chart can't be saved

  Going into the broken charts settings, the question details are not displayed, except for the `Show row totals` and `Show column totals` selectors. When either of these are changed, the chart and the question details are both correctly displayed after "doing science" completes. However, if the chart is then saved,  it is broken again after leaving and coming back into the chart.

4. The broken and duplicated charts run different queries

  When the broken chart is duplicated, Metabase seems to run different queries for the two charts, even though the duplicate chart is not changed in any way. Using the browser developer tools, I pulled these two queries from the HTTP responses when opening the broken and duplicated charts;

  - [broken_chart_query.md](https://github.com/metabase/metabase/files/13594324/broken_chart_query.md)
  - [duplicated_chart_query.md](https://github.com/metabase/metabase/files/13594327/duplicated_chart_query.md)
  - _NB: The queries are in markdown files, as github doesn't allow sql files to be uploaded.

  Running diff on these two files shows the broken query is missing select fields, a group-by clause and an order-by clause, which would have returned the data needed for the chart;
 
  -  ![dff_of_broken_and_duplicated](https://github.com/metabase/metabase/assets/19850226/71dd1e66-1764-4428-8819-122eb90fa0f7)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.198-187.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-07",
      "tag": "v1.47.7",
      "branch": "?",
      "hash": "dd51fd4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by grumBit** [comment]
Good question @darksciencebase! We're using Metabase Cloud v1.47.7. It looks like I need to [contact support](https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase#upgrading-metabase-cloud) to request an early upgrade to v1.47.9. I reluctant to do that as I'm not sure if it's possible to downgradde back to v1.47.7 if it causes problems.

Are there any other ways to have this problem looked at?

**Comment by Tony-metabase** [comment]
Hi @grumBit can you please open the request to help@metabase.com ... Indeed we will take a backup for you before the upgrade so we can revert any time :)

**Comment by grumBit** [comment]
Thanks @Tony-metabase , the upgrade fixed the problem. Cheers!
