### ISSUE TITLE
Updates section is showing 0.20.0 being more recent than 0.20.1

### ISSUE THREAD

**Issue by arabold** [metabase/metabase#3652]
Small bug in the Upgrades section. Got 0.20.1 installed but it advertises 0.20 as being more recent:
![image](https://cloud.githubusercontent.com/assets/1548229/19620266/7c8a9adc-982e-11e6-95a3-7036f8b36709.png)

This is a standalone installation on Amazon Linux (using H2 database).

**Comment by salsakran** [comment]
There was a trailing comma in the `version-info.json` file at static.metabase.com/version-info.json

Removed it and it should work now. Will close once an update cycle has run and I've verified this is fixed.

**Comment by tlrobinson** [comment]
We should also do an actual ordered comparison and only show newer versions. Sometimes people will deploy versions newer than the latest published version (e.x. release candidates) and it doesn't make much sense to show an older version as an update.

**Comment by salsakran** [comment]
closing this as it's working now.

@tlrobinson a pretty good idea, opening #3658 for it.
