### ISSUE TITLE
Support of Variables in Native Mongo Queries

### ISSUE THREAD

**Issue by subodhpareek18** [metabase/metabase#3653]
Hi there,

Wanted to inquire if there is any support for `{{ variables }}` in Native Mongo Queries.

We currently heavily rely on Metabase for our BI needs, but not everyone in our company is really capable of writing Mongo Queries. So I was hoping to gain more clarity on this specific feature.

In case there is no support (existing or planned) for variables, we were also considering shifting some of our DB to SQL, but the first preference will obviously be Mongo.

Thanks.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  or `me too` comment**

**Comment by salsakran** [comment]
we don't currently support variables in mongo queries. We're trying to figure out what syntax to use. I.e. square and curly brackets are valid in JSON. Doesn't really seem like an appropriate delimiter. 

Do you have any ideas on how you'd like to insert variables and conditional clauses? Are there are templatized JSON languages you've used?

**Comment by hermansje** [comment]
I've come across [parameterized questions in Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html).
They use double curly brackets inside strings.

**Comment by alirezastack** [comment]
In what release of Metabase, variable will be supported for MongoDB? Without using variables in MongoDB it is really limited. Any plan for this?

**Comment by arthurnobrega** [comment]
I also would like to have this feature of variables in MongoDB.

**Comment by paulozip** [comment]
Me too

**Comment by ThanhWilliamLe** [comment]
me too

**Comment by jonymusky** [comment]
me too

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  or `me too` comments, please just upvote by adding a reaction to the issue description.

**Comment by sanjay8bisht** [comment]
Hey, is there any update on this issue?

**Comment by aviggiano** [comment]
I am also looking for this feature.

**Comment by singhkua** [comment]
plus 1

**Comment by pptoan23** [comment]
Me too

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍 or `me too`  comments, please just upvote by adding a reaction to the issue description.

**Comment by marcomag89** [comment]
mee too

**Comment by jordimorillo** [comment]
Currently my company is migrating all the mongodb aggregations to mysql just to be able to add variables to the queries. This feature is a must have for all mongodb users.

**Comment by tiagopigatto** [comment]
Any updates on this issue?

**Comment by alirezastack** [comment]
@tiagopigatto, It has the most upvotes in `Metabase`, but does not seem why it is not implemented and there is no plan for it. :|

**Comment by oddgames-david** [comment]
please.

**Comment by peaksnail** [comment]
reference redash  mongodb filter https://redash.io/help/data-sources/querying-mongodb

**Comment by ianmartorell** [comment]
Both this issue and #1687 are fundamental for Metabase being useful with a MongoDB data source. There is currently no way to ask most questions without resorting to native queries, depending on how your relationships are modelled, and there is no way to declare variables to be filtered when these questions are placed on dashboards.

**Comment by vertoforce** [comment]
Is there any ongoing development on making this happen?

**Comment by camsaul** [comment]
Hey, we're not currently working on it but there's a good chance we'll do so in the future, but I can't commit to a date when we'd start working on this. Either way, we'd definitely merge a PR if someone wanted to submit one!

**Comment by cparaskeva** [comment]
Any updates on this one?

**Comment by mazameli** [comment]
@cparaskeva Yes, we are currently actively working on this feature. :)

**Comment by camsaul** [comment]
Implemented by #11474, #11513, #11518

**Comment by swapnilbb** [comment]
@camsaul 

I am unable to get it to work for me, are the examples documented somewhere?

https://discourse.metabase.com/t/support-of-variables-for-native-mongo-queries-in-metabase/11568
