### ISSUE TITLE
Incorrect database name '' using MySQL as internal database

### ISSUE THREAD

**Issue by shane-dribble** [metabase/metabase#3655]
I am trying to use MySQL 5.6 as our internal Metabase server (fresh install, not a migration) and I get the following error part way through the migrations.

ERROR metabase.core :: Metabase Initialization FAILED:  Incorrect database name '' [Failed SQL: CREATE TABLE ``.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35) NULL, DESCRIPTION VARCHAR(255) NULL, COMMENTS VARCHAR(255) NULL, TAG VARCHAR(255) NULL, LIQUIBASE VARCHAR(20) NULL, CONTEXTS VARCHAR(255) NULL, LABELS VARCHAR(255) NULL, DEPLOYMENT_ID VARCHAR(10) NULL)]

It is creating quite a few tables without issue, so I assume my configuration is fine.

I tried running that manually by inserting 'metabase' as a database name and it still failed.

Operating System Version = AWS AMI 2016.09
Java Version = OpenJDK Runtime Environment (amzn-2.6.7.2.68.amzn1-x86_64 u111-b01)
Metabase Version = v0.20.1 (05c22e2 release-0.20.1)

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: MySQL; mysqld  Ver 5.6.33 for Linux on x86_64 (MySQL Community Server (GPL))

**Comment by camsaul** [comment]
If you look at the SQL there's a blank identifier where the DB name is supposed to go. Did you specify the `MB_DB_DBNAME` env var?

**Comment by shane-dribble** [comment]
Yeah sorry, i was confused that other database tables got created but my config was wrong.

Thanks
