### ISSUE TITLE
BigQuery and Date Timestamp Filters - TIMESTAMP_TRUNC parameter - day vs minute

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#36561]
### Describe the bug

When using a filter that is relative to minutes, TIMESTAMP_TRUNC is being called with the ‘day’ parameter rather than ‘minute’.  Essentially ignoring the minutes and seconds.

### To Reproduce

1. For this example, I’m also going to compare the values created by TIMESTAMP_TRUNC based on the parameters used.

<img width="724" alt="5" src="https://github.com/metabase/metabase/assets/17398657/e93a6df2-57ab-449b-be66-0fcd73131465">

<img width="1023" alt="6" src="https://github.com/metabase/metabase/assets/17398657/6c9ae619-1cbc-42a9-85f3-9fa324070dc7">

<br>
<br>

2. Run a query such as the following with a relative time filter

<img width="790" alt="1" src="https://github.com/metabase/metabase/assets/17398657/cd5cceca-0c5d-4136-b7fc-d6bb7f3d5a0d">

<br>
<br>

Will produce the following SQL query where TIMESTAMP_TRUNC is defaulting to ‘day’ as opposed to 'minute'.

![2](https://github.com/metabase/metabase/assets/17398657/0bd672bb-18db-440c-bf05-8a1b25e11333)

<br>
<br>

3.  Taking that same query and removing the parameterized field (E.G. availability_timestamp) and putting the WHERE clause from the generated SQL produces undesired results. Even though the BETWEEN clause has the correct representation of the relative filter we have in place.

![3](https://github.com/metabase/metabase/assets/17398657/562c17f2-bb53-4ef1-8d00-6545defcf1db)

<br>
<br>

4. Replacing ‘day’ with ‘minute’ in the same query produces the expected results.
![4](https://github.com/metabase/metabase/assets/17398657/a1404198-9ffd-411d-8770-3116580a5f56)

### Expected behavior

The expectation is for TIMESTAMP_TRUNC to reference the minute parameter when using minutes as the desired filter

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.198-187.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v1.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}


Also tested in .48 RC with the same results
```

### Severity

P2 - Not paying attention and seeing what's happening will present incorrect data

**Comment by snoe** [comment]
We no longer produce sql that uses `timestamp_trunc` for relative filters.
1. We now optimize `BETWEEN` clauses into `>= and <` clauses
2. We now truncate only when necessary.

<img width="1633" alt="image" src="https://github.com/user-attachments/assets/5bb7f16f-c384-4d92-8d10-31be1f3ac8a6">
