### ISSUE TITLE
[dc.js migration] custom y-axis range has an extra split line

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#36587]
_Links are for the shared app db we are using for this project._

Branch: `echarts`

Regressions dashboard: http://localhost:3000/dashboard/28-echarts-regressions

http://localhost:3000/question/169-line-custom-y-axis-range-aapl-stock

Setting a custom y-axis range causes extra splitlines (the dashed horizontal lines aligned with the y-axis ticks) to appear at the min and max of the range. This behavior did not exist in the old dc.js implementation.

The solution would likely be to write a custom function for the [`yAxis.splitLine.interval`](https://echarts.apache.org/en/option.html#yAxis.splitLine.interval) option that will choose not to display these lines.

| dc.js  | echarts |
| ------------- | ------------- |
| <img width="543" alt="Screenshot 2023-12-17 at 9 10 33 AM" src="https://github.com/metabase/metabase/assets/37751258/d070700b-6704-48f4-875f-8cf78dd7fdb5"> | <img width="632" alt="Screenshot 2024-01-18 at 2 50 12 PM" src="https://github.com/metabase/metabase/assets/37751258/7a59bafa-4b9b-4de8-8789-9abedb701006"> |

**Comment by alxnddr** [comment]
ECharts intentionally renders split lines when we specify custom range, the issue has cosmetic value
