### ISSUE TITLE
Make Revision History consistent across artifacts

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3660]
On the detail view for questions, the Revision History appears in the action bar:
![screen shot 2016-10-24 at 11 07 04 am](https://cloud.githubusercontent.com/assets/2223916/19657871/a8799ab4-99da-11e6-9020-665eeda3c04d.png)

On dashboards, you have to click Edit before you see it:
![screen shot 2016-10-24 at 11 12 34 am](https://cloud.githubusercontent.com/assets/2223916/19657921/cd7bc968-99da-11e6-8307-486e2c5b0fe8.png)
![screen shot 2016-10-24 at 11 12 42 am](https://cloud.githubusercontent.com/assets/2223916/19657925/d31b1676-99da-11e6-8e44-78f1d428e9a7.png)

Pulses don't have a way to view their revision history at all.

I'm unsure whether I prefer revision history as a secondary Edit action, or as a primary action. On the one hand, the revision history allows you to revert an artifact back to a previous version, making it feel like an edit action. On the other hand, it's also useful context about the artifact even if you don't intend on reverting or editing it, making it feel weird that you have to click edit first. I don't love adding more primary actions to that space, but I also don't love having lots of things change in that space after clicking edit.

All that being said, I think I'm leaning towards making revision history a primary action that's always accessible in the same place for all artifacts. 

Extra credit: make the revision history icon the same size on every page. 📏

**Comment by mazameli** [comment]
#3801

**Comment by mazameli** [comment]
This is going to be fixed once the content moderation feature (#15797) ships, as questions and dashboards will have the same way to get to and view revision history, and pulses are very likely going to be phased out.

**Comment by brunobergher** [comment]
Handled with the info panel.
