### ISSUE TITLE
Large dataset warning modal has unnecessary horizontal scrollbar

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3661]
![screen shot 2016-10-24 at 11 26 35 am](https://cloud.githubusercontent.com/assets/2223916/19658477/f615e294-99dc-11e6-96fb-7914a5f166da.png)

**Comment by kdoh** [comment]
The switch to a new download UI with the addition of JSON downloads in #3779 should mean this is no longer an issue.
