### ISSUE TITLE
CSV uploads: Can't upload CSV with a column that has boolean and integer values

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#36629]
[(slack thread where this was raised)](https://metaboat.slack.com/archives/C05MPF0TM3L/p1702074978417889)

### Describe the bug

If you try to upload a CSV with a column that has both integer and boolean values (where there is an integer value that is not 0 or 1), the upload fails with an error:

<img width="571" alt="image" src="https://github.com/metabase/metabase/assets/39073188/5e6d7ce8-8f12-489c-a150-5b669d01e4ab">

### To Reproduce

1. Enable uploads to the sample database
2. Upload a CSV file to a collection with the contents:
```
some_column
2
true
```
3. Observe the upload fails with an error message

### Expected behavior

the upload should succeed, and the column should be of type text

### Information about your Metabase installation

```JSON
master
```

### Severity

blocking some uploads

**Comment by calherries** [comment]
^clicked on the wrong team label

**Comment by FilmonK** [comment]
Thanks @calherries for working on this 
Throwing this out there as a suggestion in case issues in relation to CSV uploads happen again. Would it be possible to identify the column(s) from the CSV that are triggering the error?
