### ISSUE TITLE
Cannot change question data source to raw data after selecting saved question

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#36669]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/22ffbba7-1b82-474c-b52f-81c88332ef95

### To Reproduce

1. Create a question based on Orders table from Sample database and save it
2. Create a new question
3. When picking starting data, search for the question created in step 1 by name and choose it
4. Click data to edit it
5. Choose "Raw Data"
6. Choose "Sample Database"

Nothing happens

### Expected behavior

Sample Database is opened in the picker

### Information about your Metabase installation

v48 RC 2, master

### Severity

P3

**Comment by nemanjaglumac** [comment]
I can't reproduce this on master @ 26bbec6367b4680e91bf89156924cee9c69076c8

**Comment by kamilmielnik** [comment]
I can still reproduce it in `master` @ [65ebed4](https://github.com/metabase/metabase/commit/65ebed465c380c3ca4e8d2ac86a347bb40fb733c) & stats.

**Comment by uladzimirdev** [comment]
I still reproduce the issue on master, v48, 926b04a1d5
