### ISSUE TITLE
[MLv2] [BE] Expose version of `query` that takes Table or Card metadata 

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#36671]
Should create a new MBQL query based on the provided table or card id. Should find the corresponding database id automatically. `tableOrCardId` can be a number (table id) or a string (`card__1`)

**Comment by camsaul** [comment]
You can already do this with 

```js
Lib.query(metadata, Lib.tableOrCardMetadatat(metadata, tableOrCardId));
```

**Comment by camsaul** [comment]
Ok we actually still need to expose the `Lib.query(metadata, tableOrCardMetadata)` version in JS. Right now only database ID + metadata + query is exposed. We do have this code in Clj already.
