### ISSUE TITLE
[MLv2] [BE] Add `sourceTableOrCardId(query)`

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#36672]
Should return `source-table` table id (number) or card id (`card__:id` string)

**Comment by camsaul** [comment]
Why do you need/want the `card__<id>` string? That's a legacy thing, not used in MLv2/pMBQL. Is it to hit API endpoints or something? We can just change the API endpoints to take Card IDs instead of the dumb strings we constantly have to parse and unparse

**Comment by ranquild** [comment]
@camsaul we need this for the DataPicker (the component to select source table / card). Currently it depends on this legacy format.
