### ISSUE TITLE
BE: Flaky test `metabase.api.dataset-test/basic-query-test`

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#36691]
Failed job: https://github.com/metabase/metabase/actions/runs/7179354705/job/19549378705?pr=35952#step:4:591

**Comment by bshepherdson** [comment]
I looked into this, and it seemed like a test infra issue, rather than a flaky test itself. I'm not familiar enough with how we load Oracle to know if there's anything to be done.

(This is part of what inspired the conversation on Slack about "smoke tests".)
