### ISSUE TITLE
[MLv2] [BE] removeClause throws "Cannot remove the final join condition" error

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#36690]
Given the following query ([screenshot](https://github.com/metabase/metabase/assets/6830683/469a5495-47ad-478c-9ccb-5394e23b78ef)), `removeClause` throws `Cannot remove the final join condition` error when trying to remove the breakout.

```tsx
Lib.removeClause(query, 0, Lib.breakouts(query, 0)[0])
```

It is expected that `removeClause` drops the entire join clause because it becomes invalid.

### How to reproduce 

1. `git checkout 36516-notebook-steps`
2. Run any of the following e2e tests:
    - `joins.cy.spec.js` (`should handle joins on different stages`)
    - `reproductions/17767-cannot-join-on-aggregation-with-implicit-joins.cy.spec.js`
    - `reproductions/18818-crash-when-joining-on-custom-column.cy.spec.js`

### Additional context

See [Slack](https://metaboat.slack.com/archives/C04CYTEL9N2/p1702378656823469)

**Comment by ranquild** [comment]
@uladzimirdev
