### ISSUE TITLE
Search input in the filter modal gets focused on hover

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#36734]
### Describe the bug

I'm reporting this issue as a Metabase user.

This breaks a11y and UX.

On some viewport sizes the "Filter" button will be directly underneath the search input, so when modal is opened the search input will be hovered and focused instantly, without user even moving the mouse.

https://github.com/metabase/metabase/assets/6830683/f65a62a8-5a19-4a0b-834e-428f6822f97e

### To Reproduce

1. Open up filter modal
2. Move mouse cursor over the search input in modal header

Search input gets focused.

### Expected behavior

Input does not get focus on hover

### Information about your Metabase installation

v48 RC2, master

### Severity

P3

### Additional context

https://github.com/metabase/metabase/pull/36649#discussion_r1424122466

**Comment by kamilmielnik** [comment]
As a user I think it's a bug, but it looks like it's been done on purpose.

It requires product input.

**Comment by nemanjaglumac** [comment]
This is no longer reproducible after the MLv2 rework in `master`.
However, it is an issue in `x.48.3`

**Comment by nemanjaglumac** [comment]
Fixed by https://github.com/metabase/metabase/pull/38183 in the `release-x.48.x` branch.
