### ISSUE TITLE
migrating h2 to mysql, dashboard cards didnt retain the same size (0.20.2)

### ISSUE THREAD

**Issue by kevinjmullen** [metabase/metabase#3677]
version 0.20.2
After migrating, our dashboard cards got blown up to where one card would fill the whole page.
Does the size of these cards get migrated?

**Comment by camsaul** [comment]
Ugh. We changed the scale of our dashboard grid in 0.16.0 and wrote a data migration to to migrate dashboard sizes for people upgrading from 0.15.1 or earlier. 

It sounds like that migration got ran after launching Metabase with your new DB and resized your cards when it didn't need to :(

**Comment by salsakran** [comment]
@kevinjmullen which version did you upgrade to 0.20.2 from?

**Comment by camsaul** [comment]
@salsakran it won't matter what version you upgrade from or even if this is the first version you ever used. The only way you wouldn't see this is if you upgraded from 0.15.1 or older and the first time you ran the 0.20.2 jar was to run the `load-from-h2` command

**Comment by salsakran** [comment]
ugh.

**Comment by camsaul** [comment]
@kevinjmullen I've opened PR #3678 with a fix for the bug. We're planning on shipping a release with this fix, 0.20.3, later today.

When that's released you'll be able to download the new JAR and run the command again with an empty database and everything will be migrated over correctly (i.e. your Dashboards will be the correct size).

**Comment by camsaul** [comment]
Fixed by #3678

**Comment by salsakran** [comment]
we just pushed out 0.20.3,  please grab a new version and do the migration again?

sorry for the hassle @kevinjmullen !
