### ISSUE TITLE
BE: Fix flaky test and uncomment metabase.metabot.metabot-util-test/inner-query-name-collisions-with-joins-test

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#36785]
`metabase.metabot.metabot-util-test/inner-query-name-collisions-with-joins-test` failed for oracle [here](https://github.com/metabase/metabase/actions/runs/7199533718/job/19611430947?pr=36705#step:4:614). 

From memory I've seen this at least twice.

**Comment by calherries** [comment]
Commented the test out https://github.com/metabase/metabase/pull/36786

**Comment by crisptrutski** [comment]
We've decided to leave this dragon sleeping, as the underlying behavior is practically dead code. Users must enable a setting, and we're going in a different direction for integrating LLMs in future.
