### ISSUE TITLE
Map tiles in embedded scenario fails to show pins

### ISSUE THREAD

**Issue by vinceve** [metabase/metabase#36798]
### Describe the bug

We created a dashboard and on that dashboard we show lots of pins on a map. In metabase if we look at the map all pins are visible. But now we embed the chart into our application, the same map doesn't show any pin in the embedded scenario. 

Screenshot within metabase itself:

<img width="850" alt="Screenshot 2023-12-14 at 14 42 54" src="https://github.com/metabase/metabase/assets/875642/4f80813e-0623-423a-85a7-a30eb19b3354">

Screenshot of the same dashboard in the embedded version:

<img width="907" alt="Screenshot 2023-12-14 at 14 43 44" src="https://github.com/metabase/metabase/assets/875642/de303e46-46b5-4b54-8d67-a17aef3046cc">

------------------

What I also notice is that if I start filtering down suddenly the map shows some pins.

<img width="446" alt="Screenshot 2023-12-14 at 15 10 18" src="https://github.com/metabase/metabase/assets/875642/20f3007a-b85f-4486-8514-8752ae73dfe2">

### To Reproduce

We created a dashboard and on that dashboard we show lots of pins on a map. In metabase if we look at the map all pins are visible. But now we embed the chart into our application, the same map doesn't show any pin in the embedded scenario. 

Screenshot within metabase itself:

<img width="850" alt="Screenshot 2023-12-14 at 14 42 54" src="https://github.com/metabase/metabase/assets/875642/4f80813e-0623-423a-85a7-a30eb19b3354">

Screenshot of the same dashboard in the embedded version:

<img width="907" alt="Screenshot 2023-12-14 at 14 43 44" src="https://github.com/metabase/metabase/assets/875642/de303e46-46b5-4b54-8d67-a17aef3046cc">

------------------

What I also notice is that if I start filtering down suddenly the map shows some pins.

### Expected behavior

All pins in the embedded version are shown

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.198-187.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-01",
      "tag": "v1.47.9",
      "branch": "?",
      "hash": "d05b06e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

medium

**Comment by connor-cantrell** [comment]
Having the same issue, causing huge problems on external/client facing dashboard.

**Comment by connor-cantrell** [comment]
@paoliniluis we are having the same issue which is causing problems on external/client facing dashboards.
