### ISSUE TITLE
Tooltip should resize horizontally on large descriptions

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#36793]
### Describe the bug

Our current tooltip has a fixed width and this leads to large descriptions being not displayed correctly
![image](https://github.com/metabase/metabase/assets/1711649/433a9001-db82-4623-a2a9-f03a9e85c7b1)

The tooltip should either resize horizontally, or provide a short description... large description kind of interaction

### To Reproduce

1. Create a question
2. Give a very large lorem ipsum description
3. Check how it renders on the collection view when hovering over it

### Expected behavior

We could have a short/long description interaction with the user having to click on it, or either resize the tooltip horizontally so the text fits better

### Information about your Metabase installation

```JSON
v48
```

### Severity

P3

**Comment by qwef** [comment]
Related: https://github.com/metabase/metabase/issues/36794

**Comment by iethree** [comment]
We should double check with design, but I'd recommend just cutting these off at X (8?) lines.
