### ISSUE TITLE
Provide a public sharable link for a question

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3680]
As per designs in #2683, allow a user to share a given card to users without a Metabase login.

This should have an instance wide admin toggle, and should use a generated, secure UUID for the public facing link

**Comment by camsaul** [comment]
@salsakran isn't this pretty much the same issue as #2683?

**Comment by camsaul** [comment]
Nevermind I saw the comment on #2683 where you mentioned you broke it out into separate issues

**Comment by camsaul** [comment]
Relevant designs from #2683 (cut-and-paste of comment by @mazameli):

Here's some updated thinking.

Let's keep the downloading actions separate from the sharing actions. If the global setting to allow public links is turned on, then a new sharing icon will appear next to the download icon. (Open question: should all users be able to use the link sharing, or only admins? My bias is all users.)

Here's the icon plus tooltip:
![tooltip](https://cloud.githubusercontent.com/assets/2223916/19708388/14c9ef68-9ad3-11e6-86e3-84281740a368.png)

Clicking on the button shows this state if no link has been created. I think it's okay for this to be a two-click process, just to make sure the user's intending on creating the link.
![no link](https://cloud.githubusercontent.com/assets/2223916/19708812/38b9b48c-9ad6-11e6-9839-0908d291e18c.png)

When the user clicks `create public link`, then they'll see this:
![links created](https://cloud.githubusercontent.com/assets/2223916/19748182/1b6f3f4a-9b95-11e6-96b4-dfabcbc3745a.png)

The copy buttons have this hover state:
![copy tooltip](https://cloud.githubusercontent.com/assets/2223916/19748206/2cc1cea2-9b95-11e6-8bce-c2dd0438de22.png)

If they click `copy link`, we could show a confirmation like this, which would fade out after a second or two:
![copied](https://cloud.githubusercontent.com/assets/2223916/19748241/509b56e0-9b95-11e6-8634-4f85a304519f.png)

If they click `disable links`, they'll be asked to confirm:
![disable links](https://cloud.githubusercontent.com/assets/2223916/19748252/5c8479fa-9b95-11e6-902b-b7aaeaea03cc.png)

A public question link should look something like this:
![public-question-link](https://cloud.githubusercontent.com/assets/2223916/19708767/e79c18ce-9ad5-11e6-9967-796a0dd2ee99.png)

**Comment by camsaul** [comment]
Is this the same issue as #1380?

**Comment by camsaul** [comment]
Implemented by #4123

**Comment by codingjoe** [comment]
Just for reference, it's `.csv` now, not `/csv`.
Anyhow, I'd wish there is a field where I can just copy the correct URL. I don't want to explain my CEO, that he needs to go to spreadsheets, type `IMPORTDATA()` then share the metabase report, copy the public URL and paste it while amending `.csv`.
It's just too complicated for your average Joe.
