### ISSUE TITLE
[dc.js migration] refactor scatter and waterfall to use composed functions instead of conditionals

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#36825]
Right now the [scatter plot](https://github.com/metabase/metabase/pull/36317) and [waterfall charts](https://github.com/metabase/metabase/pull/36728) take a conditional based approach to reusing existing code (e.g. the settings, model, and option computation from the combo chart). This is unelegant and something that became a problem in the old dc.js implemenation, as it made the code hard to read and maintain.

Before merging to master, we should rectify this by using composed function calls (e.g. `getScatterPlotOption` calls `getCartesianChartOption`) 

---
Below are further suggestions to improve the code structure. For the sake of keeping this issue simple, let's close it once we've refactored the scatter plot. These further suggestions can be implemented later.

We should also improve the file structure to put shared code in a specific `shared` folder, and chart specific code in their own folders, e.g.

```
cartesian
    shared
        model
        option
    combo
        model
        option
    scatter
        model
        option
    waterfall
        model
        option
```

While we're at it we should improve the React component structure as well to reduce reuse, e.g. `ScatterPlot.tsx` and `ComboChart.tsx` can both use a common `CartesianChart.tsx`.

**Comment by alxnddr** [comment]
@EmmadUsmani but it is not a regression and it does not block merging
