### ISSUE TITLE
Support parameters/filters on public dashboards

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3684]
For dashboards that are shared publicly via #3681, we should also support filters if the dashboard has them.

**Comment by kevinjmullen** [comment]
was experiencing an issue with the filters actually. cards updated but made some on the dashboard appear with a fade. that was with the first filter. the second filter did the same, updated cards, then only one card didn't have the fade applied to it. is this related? or should i open another issue?

**Comment by tlrobinson** [comment]
@kevinjmullen Any cards that aren't wired up to all active filters will be faded out to indicate their data is not subject to the active filters. Make sure all cards are wired to all filters.

**Comment by camsaul** [comment]
This was done by #4123, right?

**Comment by camsaul** [comment]
Implemented by #4123
