### ISSUE TITLE
Failed upgrade to v48 when using MySQL 5.x as the App DB

### ISSUE THREAD

**Issue by wlp7s0** [metabase/metabase#36842]
### Describe the bug

While updating from  v0.47.0 to  v0.48.0 we have a problem with database migrations. 

### To Reproduce

1. start update 
2. See error

### Logs

[metabase_migration.log](https://github.com/metabase/metabase/files/13684737/metabase_migration.log)

### Information about your Metabase installation

```JSON
- Metabase version: v0.48.0
- Metabase hosting env: Jar file
- Metabase database: mysql
```

### Severity

blocking an upgrade

**Comment by qnkhuat** [comment]
Hi @wlp7s0 could you provide the startup logs?

**Comment by qnkhuat** [comment]
@wlp7s0 which mysql version are you running?

**Comment by wlp7s0** [comment]
> @wlp7s0 which mysql version are you running?

5.7.26

**Comment by froggolini** [comment]
got the same error, tried JAR/docker, same error

**Comment by wh1sssss** [comment]
same here on EKS

**Comment by paoliniluis** [comment]
@wlp7s0 @froggolini @wh1sssss The issue is simple: Metabase does not work with MySQL < 8

**Comment by wh1sssss** [comment]
@paoliniluis he works fine before upgrade to v1.48.0

**Comment by paoliniluis** [comment]
Yes, it does work fine before v48, but we introduced features that makes this incompatible with old versions of MySQL (and specifically MySQL 5.x is EoL already)

**Comment by wh1sssss** [comment]
Thanks for the answer, when i try to downgrade to metabase/metabase-enterprive:v1.47.9 he says to me:

`Cant find table database.migration` im stuck on this, do you have any solution or tip to solve? This is a critical problem for my company and i cant upgrade my RDS to MySQL 8.

**Comment by paoliniluis** [comment]
@guibernardi please upgrade to MySQL 8

**Comment by guibernardi** [comment]
@paoliniluis here isn't possible to upgrade my RDS to MySQL 8 right now, we tried the downgrade of Metabase but it didn't work, is there anything that we can do here?

**Comment by paoliniluis** [comment]
@guibernardi you need to restore the latest database backup that worked

**Comment by paoliniluis** [comment]
Ok I just tested the "migrate down" command and it works.

Fix: you need to be able to connect to the application database and with the v48 JAR or container run:
"java -jar metabase.jar migrate down"

that command will fix the schema of the application database and set it up again for v47. Then start v47 again

Check https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase#rolling-back-an-upgrade

@guibernardi @wlp7s0 @wh1sssss @froggolini

**Comment by wlp7s0** [comment]
@paoliniluis thanks for tip. Dumped database from 5.7 (can't move to mysql v8 main database too), created docker mysql with version 8, restored dump from production metabase to 'test before upgrade' version. Metabase migrations and upgrade completed with success. 

Thank you!

**Comment by wh1sssss** [comment]
Thanks a lot, works like a charm here!!!!!

**Comment by paoliniluis** [comment]
@wlp7s0 I hope you made a persistent volume in that docker container or otherwise you'll lose everything when the container recycles

**Comment by wlp7s0** [comment]
@paoliniluis XDD of course I did. Not my first "docker rodeo" )
Thanks for a worry
