### ISSUE TITLE
"Abbreviate days and months" setting is not respected in subscriptions

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#36850]
### Describe the bug
"Abbreviate days and months" setting is not respected in dashboard subscriptions
Card:
<img width="746" alt="Screenshot 2023-12-15 at 10 48 24 AM" src="https://github.com/metabase/metabase/assets/132273646/3342cbc7-6c59-44d3-a8eb-c827a0150acc">

Subscription:
<img width="499" alt="Screenshot 2023-12-15 at 10 48 37 AM" src="https://github.com/metabase/metabase/assets/132273646/cd29ff06-34de-457c-9963-c09c43648f31">

### To Reproduce

1. Create a card with a date field in the x-axis, set "Abbreviate days and months" to true in the viz settings
2. Add it to a dashboard and create a subscription
3. See error

### Expected behavior

Should respect the formatting 

### Information about your Metabase installation

```JSON
- 47.x, master
```

### Severity

Styling error

### Additional context

Related to https://github.com/metabase/metabase/issues/5493

**Comment by ojjj13** [comment]
I believe if you change x-axis to **ordinal** will temporarily fix this issue, however if you have multiple lines in the chart with some missing data where you have to do interploration, you will find the pulse/subscriptions won't even keep the order of the x-axis, will upload screenshot later.

**Comment by zbayoff** [comment]
We see this issue as well, and its causing the labels to overlap which makes this difficult to read. 
<img width="609" alt="Screenshot 2024-01-02 at 12 15 06" src="https://github.com/metabase/metabase/assets/30878344/f7d8faf3-64b8-4ad0-9704-e9fc8fddeff8">
