### ISSUE TITLE
After PostgreSQL DB backup restore, case function not working correctly

### ISSUE THREAD

**Issue by josh289** [metabase/metabase#36896]
**Describe the bug**
We restored our db from a backup, and after, I cannot use a custom column with a case function based on summaries of data in the question.

Error: column source.xdo does not exist Position: 538

**Screenshots**
![Screenshot 2023-12-18 7 53 16 AM](https://github.com/metabase/metabase/assets/71656008/2634e067-7dc7-4e13-b06f-8d9a606cfe70)
![Screenshot 2023-12-18 7 53 11 AM](https://github.com/metabase/metabase/assets/71656008/cefea82d-5eac-4289-bc35-837b1241f6a2)

**Severity**
We need to get these dashboards in customer hands by end of the week.

**Additional context**
SELECT
  ("source"."xdo" # >> array [ 'Efront_userID' ] :: text [ ]) :: bigint AS "xdo → Efront_userID",
  (
    "source"."xdo" # >> array [ 'Efront_Username' ] :: text [ ]
  ) :: text AS "xdo → Efront_Username",
  "source"."Not Started" AS "Not Started",
  "source"."In Progress" AS "In Progress",
  "source"."Completed" AS "Completed",
  "source"."Total Enrolled" AS "Total Enrolled",
  "source"."Courses Behind" AS "Courses Behind",
  "source"."On/Off Track" AS "On/Off Track"
FROM
  (
    SELECT
      ("source"."xdo" # >> array [ 'Efront_userID' ] :: text [ ]) :: bigint AS "xdo → Efront_userID",
      (
        "source"."xdo" # >> array [ 'Efront_Username' ] :: text [ ]
      ) :: text AS "xdo → Efront_Username",
      "source"."Not Started" AS "Not Started",
      "source"."In Progress" AS "In Progress",
      "source"."Completed" AS "Completed",
      "source"."Total Enrolled" AS "Total Enrolled",
      "source"."Courses Behind" AS "Courses Behind",
      CASE
        WHEN "source"."Courses Behind" < 4 THEN 'On Track'
        ELSE 'Off Track'
      END AS "On/Off Track"
    FROM
      (
        SELECT
          (
            "public"."mvpw1_18"."xdo" # >> array [ 'Efront_userID' ] :: text [ ]
          ) :: bigint AS "xdo → Efront_userID",
          (
            "public"."mvpw1_18"."xdo" # >> array [ 'Efront_Username' ] :: text [ ]
          ) :: text AS "xdo → Efront_Username",
          SUM(
            CASE
              WHEN (
                "Mvpw1 16 Course Records"."xdo" # >> array [ 'status' ] :: text [ ]
              ) :: text = 'registered' THEN 1
              ELSE 0.0
            END
          ) AS "Not Started",
          SUM(
            CASE
              WHEN (
                "Mvpw1 16 Course Records"."xdo" # >> array [ 'status' ] :: text [ ]
              ) :: text = 'in progress' THEN 1
              ELSE 0.0
            END
          ) AS "In Progress",
          SUM(
            CASE
              WHEN (
                "Mvpw1 16 Course Records"."xdo" # >> array [ 'status' ] :: text [ ]
              ) :: text = 'completed' THEN 1
              ELSE 0.0
            END
          ) AS "Completed",
          COUNT(*) AS "Total Enrolled",
          COUNT(*) - SUM(
            CASE
              WHEN (
                "Mvpw1 16 Course Records"."xdo" # >> array [ 'status' ] :: text [ ]
              ) :: text = 'completed' THEN 1
              ELSE 0.0
            END
          ) AS "Courses Behind"
        FROM
          "public"."mvpw1_18"
         
LEFT JOIN "public"."mvpw1_16" AS "Mvpw1 16 Course Records" ON "public"."mvpw1_18"."id" = (
            "Mvpw1 16 Course Records"."xdo" # >> array [ 'users_id' ] :: text [ ]
          ) :: bigint
          LEFT JOIN "public"."mvpw1_7" AS "Mvpw1 7 Courses" ON (
            "Mvpw1 16 Course Records"."xdo" # >> array [ 'course_id' ] :: text [ ]
          ) :: bigint = "Mvpw1 7 Courses"."id"
          LEFT JOIN "public"."mvpw1_5" AS "Mvpw1 5" ON (
            "public"."mvpw1_18"."xdo" # >> array [ 'branch_id' ] :: text [ ]
          ) :: bigint = "Mvpw1 5"."id"
       
WHERE
          (
            "public"."mvpw1_18"."xdo" # >> array [ 'Status' ] :: text [ ]
          ) :: text = 'Active'
       
GROUP BY
          "xdo → Efront_userID",
          "xdo → Efront_Username"
       
ORDER BY
          "xdo → Efront_userID" ASC,
          "xdo → Efront_Username" ASC
      ) AS "source"
  ) AS "source"
LIMIT
  1048575

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-07",
      "tag": "v1.47.7",
      "branch": "?",
      "hash": "dd51fd4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
You seem to have restored the backup in another schema or there’s a difference in your previous database and the current one, as Metabase uses the application database reference to build the queries. I would suggest you check that out. Also if you’re a paid customer please contact support

**Comment by josh289** [comment]
Thanks.
