### ISSUE TITLE
Give option to add dashboard filters to the question

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3689]
In a dashboard when I click on a card I would like to carry over the dashboard filters that are already set in order to be able to refine the question ("drill down").

Since adding them directly would "break" Metabase's concept of a saved question, we would need to make it clear to the user that other filters are added that are not part of the question itself.

I believe the use case of "drill down" is well know but let me know if you need more context.

**Comment by salsakran** [comment]
I think we have a notion of lineage for this reason. Eg, we have a label for questions "based" on previous questions and this is a great place to use it.

**Comment by moumny** [comment]
fixed since v0.24
