### ISSUE TITLE
ISO timestamps should be converted to local time when formatted

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3690]
ISO timestamps are sometimes returned in a timezone different than the report timezone. For example in Druid the raw data queries return ISO timestamps in UTC. 
Im not sure what is the excepted behavior, so either the browser needs to convert the timestamp to local time or the druid driver need to convert the timestamp to the report-timezone.
- Your databases: Druid
- Metabase version: 0.20.1

**Comment by tlrobinson** [comment]
Related to #2015

**Comment by moumny** [comment]
Third option would be to leave the timestamps as they are but at least add the timezone so that it's clear what we are displaying. 
My preference goes to always use browser timezone.

**Comment by moumny** [comment]
bump :) @mazameli
