### ISSUE TITLE
All User list is not consistent with People list

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3691]
When I remove users from the People tab this doesnt affect the users in the All user list nor the count.
I have 2 times more users in the All users group than users.

PS: If users are never removed this explains some errors with few accounts where resend link didn't work, even after deleting and adding the user again. Not sure how to reproduce this one though.
- Metabase version: 0.20.1
- Metabase internal database: MySQL

**Comment by camsaul** [comment]
I think one of the API endpoints for the People tab isn't filtering out users who are inäctive. Should be an easy fix

**Comment by salsakran** [comment]
@moumny yes, we never delete the row in the user table, we just mark them as in-active. This allows us to keep the name/id around for things like question/dashboard ownership, change logs, etc.
The alternative would either be a cascading delete (which is definitely not what I think anyone would want) or to have an inconsistent database with dangling FKs. 

I'd guess there's also a bug in what happens to old accounts when you attempt to recreate an account with the same email.
