### ISSUE TITLE
[dc.js migration] bars overflow chart edges

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#36922]
http://localhost:3000/question/136-waterfall-unaggregated-ordinal-waterfall-example-2

<img width="524" alt="after" src="https://github.com/metabase/metabase/assets/37751258/3acd16dd-c094-4f79-b65c-0cb843a62978">

**Comment by alxnddr** [comment]
This one will be fixed within the scope of x-axis change `value` to `category` scale
