### ISSUE TITLE
Incorrect sql is generated when using a field filter by date

### ISSUE THREAD

**Issue by Vladbara705** [metabase/metabase#36929]
### Describe the bug

My version postgres: PostgreSQL 14.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit

Incorrect sql is generated when using a field filter by date.

My field is of type timestamp. when I use a date range filter with time, the wrong sql is generated.

The picture shows a request with a filter by date, it works correctly
![Снимок экрана 2023-12-19 в 10 50 55](https://github.com/metabase/metabase/assets/41969216/deb356c9-579b-4ab0-80e7-bc3c216a2c2a)

The figure shows a request with a filter by date and time, it does NOT work correctly
![Снимок экрана 2023-12-19 в 10 51 40](https://github.com/metabase/metabase/assets/41969216/dda8c178-1e65-4d11-8bc6-8294e9ef487c)

in this part of the request
`and CAST("public"."transactions"."created_at" AS date) BETWEEN timestamp '2023-12-18 12:30:00.000'
   AND timestamp '2023-12-18 20:30:00.000'`
it is necessary to remove as DATE or TIMESTAMP because we are comparing the TIMESTAMP type with the DATE type

### To Reproduce

1. Create SQL request
2. Connect a filter by date and time when the field should be of type timestamp

### Expected behavior

Query must generate valid SQL

### Information about your Metabase installation

```JSON
Metabase version v0.48.0
```

### Severity

ASAP

**Comment by paoliniluis** [comment]
I just repro'd this but it does not generate any error, is that correct?

**Comment by paoliniluis** [comment]
Repro steps
1) get a value from the orders table and check the date and time
2) build a SQL question, with a field filter ( select * from orders where {{date}}) . Select the field filter as a date range
3) then use the date range to include the row you selected in the first step, use the time filters

see that the orders is not coming back

**Comment by darksciencebase** [comment]
@paoliniluis i get all the relevant orders on stats — am i doing it wrong? 

![Image](https://github.com/metabase/metabase/assets/125455699/87b08751-7838-4c88-bb75-094cc7c5a08a)

**Comment by luizarakaki** [comment]
> @paoliniluis i get all the relevant orders on stats — am i doing it wrong?
> 
> ![Image](https://private-user-images.githubusercontent.com/125455699/293195821-87b08751-7838-4c88-bb75-094cc7c5a08a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MzM1MzQsIm5iZiI6MTcwNDgzMzIzNCwicGF0aCI6Ii8xMjU0NTU2OTkvMjkzMTk1ODIxLTg3YjA4NzUxLTc4MzgtNGM4OC1iYjc1LTA5NGNjN2M1YTA4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQyMDQ3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjcxMTA1ZjZlYmI3Nzk5MDI1NTcxNWJlMDVjMTAwNGYxMmQ5NGE0YWQ0Nzc2MmNkZjkxYTkwNTI1OTFlMjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zhWSxqk942r-ESN45xatLhYgUohRTDtYGvR3Db_XYQY)

If you change the first filter timestamp to 11 PM and the second to 1 AM, you'll see that you're retrieving wrong values.
It is comparing dates and not timestamps

**Comment by luizarakaki** [comment]
![image](https://github.com/metabase/metabase/assets/32561114/27b210b9-f535-40be-8e0c-64d049e4ed68)

**Comment by lbrdnk** [comment]
I've reproduced the issue on `v1.48.0`. However I'm unable to on master [7fe1620](https://github.com/metabase/metabase/commit/7fe1620f07ff9cc4e76e5b8b0850fa36444605e0), hence closing.

Results on 48:
<img width="1496" alt="Screenshot 2024-02-19 at 13 15 49" src="https://github.com/metabase/metabase/assets/8920752/0e930e46-a2c5-49a9-bf55-7f58d19a6a8f">

Results on master with same filter criteria:
<img width="1496" alt="Screenshot 2024-02-19 at 13 27 46" src="https://github.com/metabase/metabase/assets/8920752/4dd97334-0ed9-4a57-bbbe-67d4d6d37826">


Modifying filter time works as expected (last row filtered out):
<img width="1496" alt="Screenshot 2024-02-19 at 13 27 57" src="https://github.com/metabase/metabase/assets/8920752/dd785286-fbb2-4ef6-a9d6-5f72f00b800b">
