### ISSUE TITLE
CSV Download for SQL Query Returns Default Value on Variable

### ISSUE THREAD

**Issue by luqmansyauqi** [metabase/metabase#3695]
### Bugs

If you're filing an issue about a bug please include as much information
as you can including the following.
- Chrome 53.0.2785.143
- OSX 10.10
- Postgres, MySQL
- Metabase version v0.20.2
- Metabase hosting environment: Ubuntu16.04
- Metabase internal database: Postgres 9.5

_Repeatable steps to reproduce the issue_
1. Create new card with SQL query with below sample from database **Sample Dataset**:
<img width="1121" alt="screen shot 2016-10-28 at 10 42 50 am" src="https://cloud.githubusercontent.com/assets/13912558/19794315/5bbc3654-9cfb-11e6-9526-a04aea010f3f.png">
`select * from orders
where user_id={{user_id}}`
Then I set default value of user_id into 2.
2. Save the question, reopen it and change the value of variable (example: change the user_id into 3). Everything went well until this step:
<img width="1097" alt="screen shot 2016-10-28 at 10 45 58 am" src="https://cloud.githubusercontent.com/assets/13912558/19794394/cce8e9bc-9cfb-11e6-9dfd-5f84553492e8.png">
3. Click download CSV, and when we open the CSV, it contains user_id 2 (default value of variable user_id). It doesn't respect variable value that we choose. Here is the result from CSV download:
<img width="703" alt="screen shot 2016-10-28 at 10 49 16 am" src="https://cloud.githubusercontent.com/assets/13912558/19794438/46c30b82-9cfc-11e6-8865-93f91571a09a.png">

Okay let's try another case not to set the default value like below card:
1. Create card with sql query and a required variable (without default value)
<img width="1113" alt="screen shot 2016-10-28 at 10 51 23 am" src="https://cloud.githubusercontent.com/assets/13912558/19794465/8598d12a-9cfc-11e6-9758-868c18b83dfe.png">
2. Reopen the card, set the variable value, and click download csv:
<img width="1108" alt="screen shot 2016-10-28 at 10 53 17 am" src="https://cloud.githubusercontent.com/assets/13912558/19794495/cadf261c-9cfc-11e6-84de-6c02bc1d8374.png">
<img width="257" alt="screen shot 2016-10-28 at 10 53 24 am" src="https://cloud.githubusercontent.com/assets/13912558/19794529/240359f2-9cfd-11e6-9524-990eb6b558cb.png">
We cannot download the CSV  with error `'User' is a required param.`

---

**Comment by danielsitnik** [comment]
Same problem here.

- Chrome 54.0.2840.71
- OSX 10.11.6 (El Capitan)
- Database: MySQL
- Metabase version v0.20.3
- Metabase hosting environment: Amazon Linux (EC2)
- Metabase internal database: default (H2 I guess?)

**Comment by salsakran** [comment]
There are two other reports in #3704

**Comment by pdiniz13** [comment]
For the second part of the error 
> Okay let's try another case not to set the default value like below card:
> 
> Create card with sql query and a required variable (without default value)

If there the field is supposed to be optional then it should be wrapped in [[]]

This:
```
select * from orders
where user_id={{user_id}}
```
Should be:
```
select * from orders
[[where user_id={{user_id}}]]
```

**Comment by luqmansyauqi** [comment]
> If the field is supposed to be optional then it should be wrapped in [[]]
@pdiniz13 No, I want the field to be required or it will scan a whole table in the first run (in my case).

**Comment by danielsitnik** [comment]
My field is required as well.

![screen shot 2016-11-09 at 11 11 46 am](https://cloud.githubusercontent.com/assets/1395838/20139473/6eb219a6-a66d-11e6-83f4-e3d843abdfa8.png)

But when I try to download the CSV I get a page with `'Prize ID' is a required param.`

**Comment by pdiniz13** [comment]
@luqmansyauqi they are two separate issues. When I mentioned the optional params I was referring to the second part where you had left the require param empty. I am having the same issue as you when it comes to the having set a required value and then changing it but the csv not changing based on the new value. That's why salsakran tagged my question 3704 on here. For now the workaround I have found was to change the default value itself. Also not sure if it's related or not but the field selector for the fields in the table ui are also not affecting the csv. This is leading me to believe that the csv download is running based on the data_set query saved on the report_card without being influenced by any of the front end changes that affect the web display.

**Comment by salsakran** [comment]
my guess is that it's the same root cause, but I'm leaving both issues open in case that not true.

**Comment by aagarwal-gtr** [comment]
hi i have verified that this bug is not there in v0.20.1 so we have downgraded our metabase docker. i think it came in with #3641
