### ISSUE TITLE
Bhuddhist era year support or at least make it consistent

### ISSUE THREAD

**Issue by JomMarn** [metabase/metabase#3696]
I'm using Metabase on server (and client) with regional setting in Thai which has year to display as Bhuddhist era (+543 years) and this happen.
![1477637057177](https://cloud.githubusercontent.com/assets/11479764/19797656/9ef064b6-9d16-11e6-80cb-9694969fa272.jpg)

Network tab in Chrome.
![1477637105663](https://cloud.githubusercontent.com/assets/11479764/19797655/9ef061c8-9d16-11e6-8526-3ef466089744.jpg)

Browse mysql database on Metabase's activity table. Note that the times is correct (in my timezone) as oppose to JSON above.
![1477637129995](https://cloud.githubusercontent.com/assets/11479764/19797654/9eecd59e-9d16-11e6-9036-6c47e923ab7c.jpg)

Both client and server date format settings.
![1477637458638](https://cloud.githubusercontent.com/assets/11479764/19797657/9f1c6372-9d16-11e6-8c5e-edfa57bf7067.jpg)
![1477637509513](https://cloud.githubusercontent.com/assets/11479764/19797659/9f21925c-9d16-11e6-9cd9-b6e922763a96.jpg)

But data in table display normally like this
![1477637704461](https://cloud.githubusercontent.com/assets/11479764/19797658/9f1e4304-9d16-11e6-91ff-b2beadc4a504.jpg)

So please add Bhuddhist era year support or at least make it consistent.
- Your browser and the version: Chrome 54.0.2840.71
- Your operating system: Windows 7
- Your databases: MySQL
- Metabase version: 0.20.3
- Metabase hosting environment: Windows Server 2008 R2
- Metabase internal database: Both H2, MySQL

**Comment by flamber** [comment]
Closing in favor of #15635
