### ISSUE TITLE
br feature flash?

### ISSUE THREAD

**Issue by StaymanHou** [metabase/metabase#3699]
There's a `br feature flash` field in the atomic.events table. However, looks like there's no data in that field. Am I missing something when I implement the tracking tag? Or maybe the flash feature detection has not been implemented? If so, is it in the roadmap?

Thanks

**Comment by salsakran** [comment]
I'm a bit confused @StaymanHou, are you sure you entered that in the right window? To the best of my knowledge we've never had an atomic.events table in Metabase

**Comment by StaymanHou** [comment]
Oops, Sorry, this issue was supposed to be posted on another project.
