### ISSUE TITLE
Tables are not in the correct order when filtering

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#37018]
### Describe the bug

I have an Account table that has foreign keys to 10 other tables. When filtering, it is showing the list of tables in alphabetical order except for the Account table, which should be first if done alphabetically. That's problem #1. The second problem is, it is showing the fields from the first table instead of the table that I am looking at (the most relevant table). 

This used to work fine, but it's broken in latest change in master.  

### To Reproduce

1. Try to do filtering for a table that has foreign keys to 10+ other tables. 
2. Notice it doesn't show fields from the table that you try to filter by randomly one of the other based on alpha order

### Expected behavior

It should show fields from the table that I am viewing first instead of foreign tables when filtering

### Logs

n/a

### Information about your Metabase installation

```JSON
master @ Postgres
```

### Severity

It's bad user experience

**Comment by darksciencebase** [comment]
@maxzheng can you please link the table and specify exactly how you are filtering (i.e. which UI element you click)?
