### ISSUE TITLE
Strange names for schema columns

### ISSUE THREAD

**Issue by HugoDellinger** [metabase/metabase#3702]
When I import a PostgreSQL Database, the names of the columns have a really strange format. 

For example, 

- abonnements became A Bonne Men Ts
- adlc_decisions -> A Dlc Decisions
... 

<img width="258" alt="capture d ecran 2016-10-31 a 13 16 52" src="https://cloud.githubusercontent.com/assets/5629617/19853907/66249abe-9f6c-11e6-84a0-8b947a70466d.png">

I don't know if there's a kind of formatting of the columns name but, if there is one, it seems to be buggy.

**Comment by camsaul** [comment]
@HugoDellinger if you go to the Admin Panel and then go to Settings > General you can disable advanced humanization if it's giving you trouble:

![screen shot 2016-10-31 at 11 26 01 am](https://cloud.githubusercontent.com/assets/1455846/19866302/e2cdcdb6-9f5c-11e6-9990-efab2d30446b.png)

**Comment by HugoDellinger** [comment]
Indeed. Thank you for the help. Maybe you should add a tooltip somewhere in order to explain these strange names at first
