### ISSUE TITLE
Update 0.47.10 to 0.48.1 idx_view_log_timestamp

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#37036]
### Describe the bug

Hello, 

this morning I attempted to update my Metabase instance from 0.47.10 to 0.48.1. I stopped the service, downloaded the new .jar file, and restarted the service. Unfortunately, due to overconfidence, I didn't notice that my /var/lib/mysql partition was at 100% capacity. I managed to free up some space to properly stop MariaDB, then added 10GB of space to this partition. After restarting MariaDB and ensuring everything was functioning correctly, I proceeded to restart Metabase. However, the update process still gets stuck on idx_view_log_timestamp.

Is it possible to restart the process?

[metabase.txt](https://github.com/metabase/metabase/files/13737537/metabase.txt)

### To Reproduce

1. Stop service : systemctl stop metabase
2. download .jar : wget ....
3. start service : systemctl start metabase
4. /var/lib/mysql is full
5. systemclt stop metabase
6. systemclt stop mariadb
7. +10G to /var/lib/mysql
8. systemctl start mariadb
9. systemclt start metabase

### Logs

[metabase.txt](https://github.com/metabase/metabase/files/13737559/metabase.txt)

### Information about your Metabase installation

```JSON
- debian 11.3
- mariadb : 10.5.15-MariaDB-0+deb11u1 Debian 11
- Firefox 120.1
```

### Severity

blocking all users

**Comment by noahmoss** [comment]
Hi @Philippe-M — sorry you're hitting this. My best guess is that that migration ran, but could not be recorded as having ran due to the partition being full, so it tried to re-run when you restarted Metabase and failed since it is not idempotent.

If you're able to manually add this index on the database, and then restart Metabase, I think it should fix the migration:
```
 CREATE INDEX IF NOT EXISTS idx_view_log_timestamp ON view_log (timestamp);  
```

Please let me know whether this works, and if you continue to have any issues!

**Comment by Philippe-M** [comment]
I came to the same conclusion. While waiting to find a solution, I restored the VM backup. However, I kept the old one to test your solution tomorrow.

**Comment by noahmoss** [comment]
Closing this issue as resolved, but feel free to re-open if you continue seeing this
