### ISSUE TITLE
Dropping and recreating a table doesn't update the effective type causing unwanted behaviour in the GUI

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#37047]
### Describe the bug

The issue spans different areas related to the sync most specifically the `database_type` and `effective_type` found in the table `metabase_field`

<img width="1496" alt="image" src="https://github.com/metabase/metabase/assets/110378427/8065f51d-45d3-4000-98d4-6c7bd990d33f">

What happens is that when a table is dropped and re-created with a column that changed type the effective_type is not updated causing issues with the GUI editor during summation and aggregation. 

### To Reproduce

You need a Database for these replication steps. I am using PostgreSQL so connect This DB with metabase

1) Create a table:

```
CREATE TABLE test2
(
    id             serial PRIMARY KEY,
    this_is_a_text VARCHAR(50),
    this_is_a_time TIMESTAMP
);
```

2) Go to Admin -> Databases -> Sync Database Schema Now
3) Go to Question -> test2 -> You will notice that Metabase picks up the correct type of the field:

<img width="1500" alt="image" src="https://github.com/metabase/metabase/assets/110378427/0a6344b0-71b8-476d-a469-b9f3aa87dec5">

4) In fact if you connect to your appDB -> Go to table `metabase_field` and look for these two fields you will see:

<img width="1499" alt="image" src="https://github.com/metabase/metabase/assets/110378427/f267757e-83a0-431a-aed7-321ebbd043bb">

5) Drop the above table:

```
DROP TABLE test2;
```

6) Re-Create another table which have the same column names but different types and insert some data:

```
CREATE TABLE test2
(
    id      serial PRIMARY KEY,
    this_is_a_text float8,
    this_is_a_time float8
);
```
```
INSERT INTO public.test2 (id, this_is_a_text, this_is_a_time)
VALUES (1::integer, 1::integer, 1::integer)
```

7) Go to Admin -> Databases -> Sync Database Schema Now
8) Go to Question -> test2 -> You will notice that Metabase picks up the old type for the fields and still thinks the fields are text and date:

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/4de34dce-64f0-48ca-b644-f9cf75d4524d">

In fact in this view you cannot even have the option to sum

<img width="1507" alt="image" src="https://github.com/metabase/metabase/assets/110378427/3fe7170d-1f11-4d8e-bbc4-105054f5a9dd">

9) On the other hand if you click visualize -> click on column -> you are given the option to Sum/Avg and it works when you do:

<img width="1511" alt="image" src="https://github.com/metabase/metabase/assets/110378427/34f282d7-6f8e-4cf2-aa09-b5e80ef56c58">

10) Go back to your appDB -> Go to table `metabase_field` and look for these two fields you will see only database_type changed: 

<img width="1496" alt="image" src="https://github.com/metabase/metabase/assets/110378427/6aa9d6b8-ddce-44a2-be11-b7d5a5cf5aaf">

### Expected behavior

The expected bahavior is that the GUI editor and the column Modal are consistent. I should be getting the option to sum in both occasions ... I believe the issue is that `effective_type` should get updated as well

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.47.9 and 1.48.1
```

### Severity

This is a serious problem because you are forced to go to the Table Metadata tab and change the field type if you have a table with a lot of changed columns this becomes a problem

**Comment by paoliniluis** [comment]
nope, if you drop and recreate with the same name, Metabase will only flag those tables/fields as inactive, and then it will flag them as active again. I think you want https://github.com/metabase/metabase/issues/18074

**Comment by Tony-metabase** [comment]
No the issue is larger than that ... Then why does the GUI editor uses the `effective_type` while the filtering uses `database_type`? There is a clear inconsistent behaviour between the two paths.

The `database_type` gets updated so it's not a question of a row being inactive/active. Something gets updated so why not updating the `effective_type` as well

![image](https://github.com/metabase/metabase/assets/110378427/806dd795-d166-47e7-8f4a-340b090c3eaa)

**Comment by Tony-metabase** [comment]
Also to add  the `effective_type` is not controlled by the fingerprint but simply by going to Admin -> Table Metadata and change the type from there which keeps adding stuff to the puzzle

**Comment by dpsutton** [comment]
This is a bug in the field syncing code

```clojure
(mt/defdataset changing-type
  [["changing" [{:field-name "col"
                 :base-type :type/Integer}]
    [[1]]]])

(mt/test-driver :postgres
  (mt/dataset changing-type
    (let [field-info! #(t2/select-one :model/Field :id (mt/id :changing :col))
          spec (->> {:database-name "changing-type"}
                    (mt/dbdef->connection-details :postgres :db)
                    (sql-jdbc.conn/connection-details->spec :postgres))]
      (try
        (is (=? {:effective_type :type/Integer,
                 :base_type      :type/Integer,
                 :database_type  "int4"}
                (field-info!)))
        ;; mt/defdataset requires rows so we null them out and then change type
        (jdbc/execute! spec ["update changing set col = null"])
        (jdbc/execute! spec ["alter table changing alter column col type text"])
        (let [table (t2/select-one :model/Table :id (mt/id :changing))]
          (sync-fields/sync-fields-for-table! table))
        (is (=? {:effective_type :type/Integer,
                 :base_type      :type/Integer,
                 :database_type  "text"}
                (field-info!)))
        (finally
          (jdbc/execute! spec ["alter table changing alter column col type integer using col::integer"]))))))

(comment
  (mt/set-test-drivers! #{:postgres})
  )
```

We updated the base_type to `:type/Integer` but the effective_type remains the same `:type/Text`.

The little hiccup in this comes from `coercion_type`. But it seems fair that if the base type changes, we can throw away the coercion and set the effective_type = base_type.

**Comment by dpsutton** [comment]
The fix should go in `metabase.sync.sync-metadata.fields.sync-metadata/update-field-metadata-if-needed!`
in the `new-base-type?` branch to 
```clojure
         (when new-base-type?
           (log/infof "Base type of %s has changed from ''%s'' to ''%s''."
                     (common/field-metadata-name-for-logging table metabase-field)
                     old-base-type
                     new-base-type)
           {:base_type new-base-type, :effective_type new-base-type, :coercion_strategy nil})
```

and some tests in `metabase.sync.sync-metadata.fields.sync-metadata-test` as well

**Comment by qnkhuat** [comment]
Technically, we're dealing with a new field here, so we need to make sure this field get re-fingerprinted and field values need to be updated.

**Comment by Tony-metabase** [comment]
There is a hidden issue here in which the GUI uses the `effective_type`

![image](https://github.com/metabase/metabase/assets/110378427/912efe9c-3f2f-406f-9ee2-c2ed83e9ae53)

While the filter modal uses the `database_type`

![image](https://github.com/metabase/metabase/assets/110378427/ac8814da-99cb-45ed-a5e9-5a8e2b712b75)

@qnkhuat agree and that limitation is this one https://github.com/metabase/metabase/issues/18074 ... These issues seem to be all kind of related hehe but the difference between this ticket and the 18074 is that one is a schema sync issue and the other a fingerprint limitation (or bug)
