### ISSUE TITLE
[dc.js migration] "total" label is sometimes missing

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#37055]
http://localhost:3000/question/158-waterfall-ordinal-user-flow

| dc.js | echarts |
| ----- | ------- |
| <img width="739" alt="Screenshot 2023-12-21 at 11 03 33 AM" src="https://github.com/metabase/metabase/assets/37751258/e4c95a44-cd9d-4f72-8eef-49ae18e7f7c4"> | <img width="563" alt="Screenshot 2023-12-21 at 11 03 23 AM" src="https://github.com/metabase/metabase/assets/37751258/0565d0b9-2c40-46df-804b-f4955a41ff9b"> |

It seems like this is a consequence of a larger problem of echarts not showing all the dimension labels.

**Comment by alxnddr** [comment]
ECharts intentionally hides the overlapping ticks, this works on wider charts:
<img width="690" alt="Screenshot 2024-02-13 at 11 00 31 PM" src="https://github.com/metabase/metabase/assets/14301985/58d13a25-1e03-4ff1-8643-e15cb4f37b78">
