### ISSUE TITLE
CSV appends: integer columns should be convertable to float

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#37069]
Integer columns in an upload table should be converted to a floating-point type if the uploaded column in the CSV file contains a floating-point number.

- [x]  Test: if a column is an integer type, uploading a single float should convert the column to float

**Comment by ojjj13** [comment]
In the same manner a column should converted to int/float when it has one, when I was uploading csv to metabase I always get "xx is not a boolean value" with a column start with a bunch of 0 and 1s follow by a random number.

**Comment by calherries** [comment]
Some [slack discussion](https://metaboat.slack.com/archives/C04S696LRUM/p1705935547252069)
