### ISSUE TITLE
Incorrect joined table aliases in role playing dimensions (single key columns is referenced multiple times in source table)

### ISSUE THREAD

**Issue by rocky57** [metabase/metabase#37074]
We have DataWarehouse in star schema. In Fact Table we have two columns BuyerKey and CustomeKey , both reference one table (DimContractor). Making two joins to DimContractor table, causing incorrect aliases assigment, like on the screen below:
![image](https://github.com/metabase/metabase/assets/4228063/7d63e6b7-b6f5-411c-80c8-8a34181d4e2b)
As you can see, column name in alias is incorrect as for first join should be "FactDocumentLineItems - CustomerKey" and for second join should be "FactDocumentLineItems - BuyerKey". It causing a lot of missunderstanding when making a filters (End Users does not know which column they are referencing).

I think in a code, you are taking Parent Column Name (from source table), but in my opinion it should be a child column name (in my example BuyerKey and CustomerKey).

In a oposite way (doing it properly, when Fact Table is a source table), it looks like this:
![image](https://github.com/metabase/metabase/assets/4228063/bfb5a5b6-dfd2-4248-805d-542e252ca4fc)
![image](https://github.com/metabase/metabase/assets/4228063/13f41507-0065-427d-be12-2cef13c253a7)

So still End User might be confused:
`SELECT
  TOP 1048575 "dbo"."FactDocumentLineItems"."Id" AS "Id",
  "dbo"."FactDocumentLineItems"."UnitPrice" AS "UnitPrice",
  "DimContractor - BuyerKey"."Email" AS "DimContractor - BuyerKey__Email",
  "DimContractor - BuyerKey_2"."Email" AS "DimContractor - BuyerKey_2__Email"
FROM
  "dbo"."FactDocumentLineItems"
  INNER JOIN "dbo"."DimContractor" "DimContractor - BuyerKey" ON "dbo"."FactDocumentLineItems"."CustomerKey" = "DimContractor - BuyerKey"."ContractorKey"
  INNER JOIN "dbo"."DimContractor" "DimContractor - BuyerKey_2" ON "dbo"."FactDocumentLineItems"."BuyerKey" = "DimContractor - BuyerKey_2"."ContractorKey"`

First join by default used BuyerKey as FK, but I changed it to use CustomerKey (alias has not been updated, which is another issue), so both joins use similiar aliases.

When I remove second join (for purpose of the report), user thinks report is incorrect becuase it is using incorrect alias (End User thinks that report contains Buyer data, not Customer data).

I would like to report two bugs - first of all, aliases are not updated properly, and second - aliases are incorrect when joining one table multiple times (but both issues relates each other).

Merry Christmas :)

### To Reproduce

Join same table multiple times to source table using different FKs. It's hard to reproduce this issue using Sample database, but based on a code which I saw, it's easy to understand the issue.

### Expected behavior

Aliases should be updated any time we are changing join condition and to generate aliases child table column name should be used (referencing table) not referenced table.

### Information about your Metabase installation

```JSON
`{
  "browser-info": {
    "language": "pl",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1250",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "pl",
    "user.timezone": "Europe/Warsaw"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-14",
      "tag": "v0.48.0",
      "hash": "f985e19"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`
```

### Severity

annoying, blocking development (using model to create question where we are referencing same table mulitple times has incorrect, duplicated column names)

**Comment by darksciencebase** [comment]
@rocky57 Could this possibly be https://github.com/metabase/metabase/issues/36185? Merry Christmas to you too!

**Comment by rocky57** [comment]
@darksciencebase , thanks for your reply - they look similar, but I think it's more crucial than others think :) in my case, where I am working with huge data warehouses , such a cases where I am joining same tables multiple times happen on daily basis, so it's blocking a development, especially if joins are really the basics in such a reporting, so they should work properly from very beginning (a lot people faced that issue a lot months in the past). It's a free tool, and it's a great tool, but I think such a bugs should be prioritized. Thanks!
