### ISSUE TITLE
Contains filter not working

### ISSUE THREAD

**Issue by phantom943** [metabase/metabase#37113]
### Describe the bug

The "string" -> contains filter stopped working, resulting in queries not running.

### To Reproduce

1. Create question
2. Add a contains filter on a string column
3. press "visualize"

### Expected behavior

Query runs

### Logs

There was a problem with your question
[:ref :metabase.mbql.schema/value] is not a valid sequence schema; a valid sequence schema consists of zero or more `one` elements, followed by zero or more `optional` elements, followed by an optional schema that will match the remaining elements.

### Information about your Metabase installation

```JSON
Metabase 0.48.1
Docker
Metabase DB: Postgres
Target DB: Clickhouse
```

### Severity

Blocking some queries. Workaround exists

### Additional context

Workaround(ish) is to switch to "is" filter and manually select all matching strings

**Comment by paoliniluis** [comment]
Hi, I was trying to reproduce in Postgres and couldn't. I think this is an issue in Clickhouse. Have you upgraded the driver?

**Comment by phantom943** [comment]
> Hi, I was trying to reproduce in Postgres and couldn't. I think this is an issue in Clickhouse. Have you upgraded the driver?

Hello @paoliniluis 
Indeed, I missed updating the driver to the latest version. Once I updated it - it worked just fine. Thanks for your helpful suggestion!
