### ISSUE TITLE
GraphQL and RESt API drivers

### ISSUE THREAD

**Issue by vmangeym** [metabase/metabase#37135]
After looking at this article: https://medium.com/@techlatest.net/how-to-integrate-metabase-with-your-data-sources-702f02b99606

it seems to show that there is a driver for GraphQL and REST API.

Can anyone here help me understand if this is now available somehow somewhere?

Thank you!

**Comment by paoliniluis** [comment]
That article lies. It was probably built with ChatGPT in a way to drive traffic to the blog. Metabase does not support APIs or GraphQL as data sources
