### ISSUE TITLE
CPU consumption is very high after upgrading to v0.48.1

### ISSUE THREAD

**Issue by Jerrylovescoding** [metabase/metabase#37144]
### Type: 
Metabase (Running on Docker)
### Version: 
v0.48.1
### Bug Description:
After upgrading from v0.47.8 to v0.48.1, the CPU consumption of server becomes higher, at the same time, some cards and dashboards  load  much more slowly than ever before. It never happened before.
For example: 
![image](https://github.com/metabase/metabase/assets/25549512/645d7b3c-2846-472f-b7f2-6bb9e1ed4309)

The main process that consumes CPU:

![image](https://github.com/metabase/metabase/assets/25549512/74991430-6cb3-4410-bbdd-9a1363e434ac)

![image](https://github.com/metabase/metabase/assets/25549512/3f4727bd-8d97-4d9f-a0c9-52559409da04)

![image](https://github.com/metabase/metabase/assets/25549512/fe385d6e-30af-4f8b-88d7-0f9e4049ac6f)

Btw, I also use metabase-clickhouse-driver (v1.3.1) plugin for my Clickhouse db.

### Expected behavior

Hope to improve the loading speed of dashboard.

### Information about your Metabase installation

```JSON
- Metabase hosting env: Docker
- Metabase version: v0.48.1
- Metabase internal database: PostgresSQL
- The OS that Metabase running on: CentOS 7
- My Database: PostgreSQL, MySQL, StarRocks
```

### Severity

The card and dashboard load very very slowly.

**Comment by maxmalysh** [comment]
We have the same issue after upgrading to v0.48.0.

- Metabase hosting env: Docker
- Metabase version: v0.48.0
- Metabase internal database: PostgresSQL
- The OS that Metabase running on: Ubuntu 22.04.3 LTS
- My Database: PostgreSQL

<img width="717" alt="Screenshot 2023-12-28 at 18 17 35" src="https://github.com/metabase/metabase/assets/6844656/00d3e72b-b4c0-4554-8bdc-fb9cb8507c3c">
<img width="745" alt="Screenshot 2023-12-28 at 18 19 30" src="https://github.com/metabase/metabase/assets/6844656/1aa6528e-1ca2-487b-af97-f08be159f633">

**Comment by paoliniluis** [comment]
Is the CPU load happening on dashboards? or when there's other process being run? (like sync) @maxmalysh

**Comment by maxmalysh** [comment]
Yes, the cpu load happens on dashboards. However, we see some periodic load spikes even when nobody uses Metabase.

**Comment by Jerrylovescoding** [comment]
Hi, @paoliniluis . Can I downgrade back to v0.47.8? How compatible are the database schema of v0.47.8 and v0.48.1?

**Comment by darksciencebase** [comment]
@Jerrylovescoding yes, you can downgrade. here are the relevant docs: https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase#rolling-back-an-upgrade

**Comment by leishman** [comment]
We're seeing the same issue. Killing the instance and restarting it seems to bring the CPU and memory consumption back down. I almost seems as if there is some sort of leak that leads to CPU and memory to balloon out of control. Here are some monitoring charts. The spikes in the red line are where we restarted metabase. Blue lines are actual resource consumption. We never saw anything like this before upgrading a few weeks ago.

<img width="895" alt="image" src="https://github.com/metabase/metabase/assets/3648618/6a0431a9-7e3b-48b2-81a7-b60d86caff5e">

**Comment by paoliniluis** [comment]
@leishman what do logs say when the spike happens?

**Comment by leishman** [comment]
I didn't see anything that was the obvious culprit but I'll paste them here next time it happens. It seems to happen after a day or two of restarting the service.

**Comment by tibold** [comment]
This happened to us too.

For us the issue was Questions built on top of Models that were built using the UI builder.
I have created a new Model using SQL (same exact query and data) and fixed all Questions to use the new SQL based model and Metabase was responsive again.

The issue in our deployment was so bad, almost all queries have timed out.

Those Questions were slow before as well, but after the upgrade they became unusable.

I have kept the original models and I think I could do a demo if that helps. 😇

**Comment by paoliniluis** [comment]
@tibold we need a consistent reproduction, is there any way you can reproduce this with the sample database?

**Comment by tibold** [comment]
@paoliniluis 
That is a definitive maybe...

I have setup a quick sample where I joined up some tables I found in the sample H2 database into a `UI` model, then copied the generated SQL into a new `SQL` model.
![image](https://github.com/metabase/metabase/assets/1974659/e08d152d-c2dc-4cb3-8506-400c0432c0f8)

Then I created the same question from both.
![image](https://github.com/metabase/metabase/assets/1974659/db19b437-6d94-4dc4-a097-97989ed786d1)

Last I created a dashboard where I added the same question several times (caching is turned off)
![image](https://github.com/metabase/metabase/assets/1974659/942833f0-c7e0-4006-95ad-b27f42747c09)

The SQL based model loads faster, albeit the difference isn't as big as I've experienced on our own PostgreSQL database.

The models in the sample are simpler as we do have both filters and custom columns in our models.
Let me know if this path seems helpful, I can try to make the models on the sample database a bit more complex as well.

**Comment by paoliniluis** [comment]
@tibold does that reproduction generate a cpu spike/load?

**Comment by tibold** [comment]
@paoliniluis 
It did indeed. However not as much to interfere with loading results.

**Comment by paoliniluis** [comment]
I have just tested this and I'm not able to get CPU spikes. The ones you see at 9:46 are from v47
![image](https://github.com/metabase/metabase/assets/1711649/31cf12f4-cbef-47bf-888a-7a89a1abd94e)

**Comment by Jerrylovescoding** [comment]
> This happened to us too.
> 
> For us the issue was Questions built on top of Models that were built using the UI builder. I have created a new Model using SQL (same exact query and data) and fixed all Questions to use the new SQL based model and Metabase was responsive again.
> 
> The issue in our deployment was so bad, almost all queries have timed out.
> 
> Those Questions were slow before as well, but after the upgrade they became unusable.
> 
> I have kept the original models and I think I could do a demo if that helps. 😇

A lot like us, our issue Questions are built on top of Questions or Models that were built using the UI builder.

**Comment by paoliniluis** [comment]
Ok this is us, probably spitting out errors in the backend that come form the processor store
![image](https://github.com/metabase/metabase/assets/1711649/24f9cd65-e2aa-4c24-835e-98597f1c834d)

model
![image](https://github.com/metabase/metabase/assets/1711649/674aeee9-1635-4be5-85d2-94b8b0bc237d)
question
![image](https://github.com/metabase/metabase/assets/1711649/01033984-485b-4437-b463-47bd8cfebe7b)

save it as pivot table, then add the pivot many times to a dashboard

47.10
![image](https://github.com/metabase/metabase/assets/1711649/590820ba-b2cd-4a8a-a90d-7cc0154d4387)

48.1
![image](https://github.com/metabase/metabase/assets/1711649/07ffa4fc-2087-4c7c-8637-f850ee246f57)

**Comment by prindj** [comment]
we have the same problem
![image](https://github.com/metabase/metabase/assets/122868937/8bf8b550-206e-44cc-a9cf-0fbf9624decc)

**Comment by maximepvrt** [comment]
I still have the problem after updating to v0.48.3

**Comment by maximepvrt** [comment]
@escherize I still have the problem after updating to v0.48.3

**Comment by paoliniluis** [comment]
@prindj that's Metabase running out of memory, increase the RAM

**Comment by paoliniluis** [comment]
@maximepvrt can you post some telemetry and also give us some ideas to try to reproduce?

**Comment by maximepvrt** [comment]
### CPU
![Capture d’écran 2024-01-16 à 14 17 13](https://github.com/metabase/metabase/assets/1840026/c0494ac0-25ae-4430-b9ee-d646e085f081)

### RAM
![Capture d’écran 2024-01-16 à 14 31 45](https://github.com/metabase/metabase/assets/1840026/57cdbc0f-bfaa-4143-afa1-0138f7052dc9)

The vertical bar is the moment when I restarted the Metabase instance

**Comment by maximepvrt** [comment]
@paoliniluis my previous issue #37446

**Comment by paoliniluis** [comment]
Thanks, do you know what is Metabase doing when you see the peaks @maximepvrt ?

**Comment by maximepvrt** [comment]
@paoliniluis No, I don't know what metabase is doing during these times. I will let you know as soon as I have the problem again.

**Comment by maximepvrt** [comment]
![Capture d’écran 2024-01-18 à 10 30 55](https://github.com/metabase/metabase/assets/1840026/2cab7ee7-bd51-49c8-813b-c5f7c1741847)
![Capture d’écran 2024-01-18 à 10 32 43](https://github.com/metabase/metabase/assets/1840026/0dbf52b6-5b0c-46d2-9b52-e6f6d9dda60f)

@paoliniluis I have encountered the CPU bug again; here is the graph with a zoom on the moment when the CPU spikes. Below is the log from that instance 
https://gist.github.com/maximepvrt/ac834d5f05f820a597d9257ce462e8a0. I never had issues like this before version 0.48, and I haven't added new databases or changed any database configurations in the meantime (as I notice a lot of connection errors in the logs). However, my databases have limits on the number of simultaneous connections.

**Comment by paoliniluis** [comment]
@maximepvrt the issue seems to be Metabase trying to connect to the application database to get the pulses, do you have any limits in the application database?

**Comment by maximepvrt** [comment]
@paoliniluis I had obsolete databases which I deleted. That was the connection error in the logs. But I still have problems with GPU at 100%

![Capture d’écran 2024-01-22 à 13 41 22](https://github.com/metabase/metabase/assets/1840026/601642fb-3a8b-4c65-b7d5-825d9619cbe8)

log : https://gist.github.com/maximepvrt/8d34fa1f00e9de3c1fde20255e4c53c9

**Comment by rhombl4** [comment]
@maximepvrt, how did you solve your issue with the CPU?
