### ISSUE TITLE
Let me manually reorder series in pie charts

### ISSUE THREAD

**Issue by csauge** [metabase/metabase#37145]
### Describe the bug

Alphabetical sort in pie chart is not correct even if the filter sort is correct.
In this example the "> 100" string is correctly sorted after all other strings in the filter, but not in the pie chart.
[
<img width="917" alt="Screenshot 2023-12-27 at 19 54 16" src="https://github.com/metabase/metabase/assets/9370091/a4ddabe9-aad5-46f5-ba7c-d3064ef9a51a">
](url)

### To Reproduce

1. Have a database (ex: postgres) with a text column "Size" with values "0-10", "10-25", "25-50", "50-100", "> 100", "null"
2. Create a pie chart and a filter in a dashboard with sorted "Size"
3. Values in filter "Size" are correcly sorted but legend in pie chart is not correctly sorted ("> 100" is after "0-10" but before "10-25")

### Expected behavior

"> 100" should be sorted as the last one in the pie chart

### Information about your Metabase installation

```JSON
- Chrome Version 120.0.6099.109
- Linux
- DB: Postgres 15
- Metabase v0.48.1
- Environment Docker and Kubernetes
- Metabase internal DB: Postgres 15
```

### Severity

Medium, Annoying (no other solution possible except modifying the string values)

**Comment by csauge** [comment]
Hi @perivamsi I have installed the last version of Metabase v0.50.6 (2024-06-19) but i still have the same issue.
How did you conclude this issue is fixed ?
<img width="779" alt="Screenshot 2024-06-24 at 15 19 55" src="https://github.com/metabase/metabase/assets/9370091/0b00b6cf-086b-4e59-85d5-88a9077bb36b">

**Comment by perivamsi** [comment]
My bad, sorry. Re-opening it.

**Comment by cdeweyx** [comment]
Reframing this as a feature request, since we have plans to enable manual reordering of series in pie charts soon, which will let you pick and choose whatever order you want and address this.

**Comment by EmmadUsmani** [comment]
@csauge In the example you provided, you can get your desired sort order (`0-10`, `10-25`, `25-50`, `50-100`, `> 100`) by sorting the column on the question itself.

<img width="587" alt="Screenshot 2024-07-18 at 12 54 08 PM" src="https://github.com/user-attachments/assets/7cfb807d-f1d7-4037-a455-6de20518a18a">

<img width="918" alt="Screenshot 2024-07-18 at 12 54 28 PM" src="https://github.com/user-attachments/assets/a554d808-85a4-45ce-a86b-05e3d44b0742">

**Comment by csauge** [comment]
> @csauge In the example you provided, you can get your desired sort order (`0-10`, `10-25`, `25-50`, `50-100`, `> 100`) by sorting the column on the question itself.
> 
> <img alt="Screenshot 2024-07-18 at 12 54 08 PM" width="587" src="https://private-user-images.githubusercontent.com/37751258/350126292-7cfb807d-f1d7-4037-a455-6de20518a18a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTU4MTAsIm5iZiI6MTcyMTU5NTUxMCwicGF0aCI6Ii8zNzc1MTI1OC8zNTAxMjYyOTItN2NmYjgwN2QtZjFkNy00MDM3LWE0NTUtNmRlMjA1MThhMThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIwNTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTBmMjI1YWM1ODMxZjNjYmI4ODc0YmUyYzQwMzZmNTAzYjhjMzg0Nzk0ZjgzMDU1ZWEzZDQ3N2ViMzI5OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sGgX7ef8-LNGKanCnSBuyjo124YwdxSr8bOYxUe91RY"> <img alt="Screenshot 2024-07-18 at 12 54 28 PM" width="918" src="https://private-user-images.githubusercontent.com/37751258/350126334-a554d808-85a4-45ce-a86b-05e3d44b0742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTU4MTAsIm5iZiI6MTcyMTU5NTUxMCwicGF0aCI6Ii8zNzc1MTI1OC8zNTAxMjYzMzQtYTU1NGQ4MDgtODVhNC00NWNlLWE4NmItMDVlM2Q0NGIwNzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIwNTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTFiMTIwM2FlOGEzYWVlNGY5Y2QyYzFlMzg5N2U5MTBmMzVlZjQxNTNjYmZkNmFjMjk0ZmU3YzI2MmZhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hkOBsbrklZYxzHwU2bLS7Ijf5A1EKHq0Z9b3mf-3cSg">

Hi, thank you but i already sort it but i do not have the same result as you. It is like ">" is ignored in the pie chart... I tried with Category type but nothing changed...

**Comment by csauge** [comment]
Hi @EmmadUsmani, after installing the last metabase version v0.50.27, and recreating a new pie chart, i still have the issue (filter is correctly sorted, but pie not)
![Image](https://github.com/user-attachments/assets/6b5f8642-885f-4b82-8146-01e5af4fe035)
![Image](https://github.com/user-attachments/assets/1ab5475a-046a-454b-abdb-2ba28de3f6a7)

**Comment by cdeweyx** [comment]
> Hi [@EmmadUsmani](https://github.com/EmmadUsmani), after installing the last metabase version v0.50.27, and recreating a new pie chart, i still have the issue with "> 100" (filter is correctly sorted, but pie not) ![Image](https://github.com/user-attachments/assets/6b5f8642-885f-4b82-8146-01e5af4fe035) ![Image](https://github.com/user-attachments/assets/1ab5475a-046a-454b-abdb-2ba28de3f6a7)

This will be available in Metabase v51 coming up.
