### ISSUE TITLE
Using dashboard-wide date filters with a custom SQL request

### ISSUE THREAD

**Issue by HugoDellinger** [metabase/metabase#3714]
I've been trying in all way possible to make dashboard-wide date filters work with custom SQL request. Is there a way to make it work ?

**Comment by salsakran** [comment]
Can you be more specific? What sql are you trying to templatize and what trouble are you having?

**Comment by salsakran** [comment]
@HugoDellinger this vague and not an actionable issue. Please use our discussion forum at discourse.metabase.com to get help.
