### ISSUE TITLE
Speed up access to liquibase changelog

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3715]
Right now, when using signed jars, the slowest part of startup is checking for run migrations and running migrations.

On my dev laptop, each of these takes approximately 13s on a signed jar and <1s on an unsigned jar. 

I think the culprit is how we're accessing the changeset files. We're using liquibase.resource.ClassLoaderResourceAccessor as the ResourceAccessor

At https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L49 this code disables any caching of the signed jar, which causes the loader to do whatever magic verifying + accessing a signed jar invokes. (See http://stackoverflow.com/questions/27860598/netbeans-classloader-slow-on-resource-loading-with-signed-jar for a similar example)

Some options on how to improve this:

1. Remove old migrations files, and require people to upgrade through versions in order (eg, upgrading from 0.12 -> 0.21 would require you to upgrade to each version sequentially). This can be mitigated by keeping the last N versions worth of migrations and letting you migrate up to N versions up. To do this, we'd need to modify the migrations code to check for the previous version number, and bomb out if it's unsupported. I don't believe we're storing version numbers explicitly in the application database, but we probably should.

2. Package up all the changesets into a single changelog. That way we only pay for the verification once. This creates a single, unmanageable file, and makes merging feature branches potentially more annoying. 

3. Modify the liquibase code to cache the jar in question

4. Find a different way of shipping migrations for liquibase.

Thoughts @camsaul ?

**Comment by camsaul** [comment]
I found the relevant PR for when they disabled caching https://github.com/liquibase/liquibase/pull/405

**Comment by salsakran** [comment]
Yup, saw that. It seemed ... short sighted.

**Comment by thearthur** [comment]
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#sec-1">1. possbile solutions</a>
<ul>
<li><a href="#sec-1-1">1.1. Don't have this problem</a>
<ul>
<li><a href="#sec-1-1-1">1.1.1. Stop having this problem by just maintaining one file</a></li>
<li><a href="#sec-1-1-2">1.1.2. limit the number of migration scripts we keep</a></li>
<li><a href="#sec-1-1-3">1.1.3. pre-check if their are any upgrades before letting liquibase run.</a></li>
</ul>
</li>
<li><a href="#sec-1-2">1.2. Solve this problem</a>
<ul>
<li><a href="#sec-1-2-1">1.2.1. Hack Around the problem</a></li>
<li><a href="#sec-1-2-2">1.2.2. Fix the problem in Liquibase</a></li>
<li><a href="#sec-1-2-3">1.2.3. add one more layer of abstraction</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>

# possbile solutions<a id="sec-1" name="sec-1"></a>

## Don't have this problem<a id="sec-1-1" name="sec-1-1"></a>

### Stop having this problem by just maintaining one file<a id="sec-1-1-1" name="sec-1-1-1"></a>

-   This is the most basic solution.
    We use git to manage the contents of a single file rather than a directory.
-   Operationally this seems mostly like a matter of opinion.
-   Requires translating json to yaml, which would then need testing.
-   the combined migration file would be ~4000 lines long

### limit the number of migration scripts we keep<a id="sec-1-1-2" name="sec-1-1-2"></a>

-   This option seems orthoginal to solving this problem. We can choose to do this now, delay it, or not do it
    independently of the rest of this problem. I don't think this is, as such, a solution to this problem.

1.  define "save point" major releases

    -   A long delayed upgrade would have to hop through these designated releases, which can be frusterating.
    -   The advantage of this is it greatly constrains the combinatorial explosion of possible upgrade paths to test.
    -   This also requires work to guide people through the upgrade process.

### pre-check if their are any upgrades before letting liquibase run.<a id="sec-1-1-3" name="sec-1-1-3"></a>

This is also orthogonal to solving this problem, and it's a good idea on it's own. (Arthur's opinion)
-   store the last-run git-hash in the DB on startup
    only run migrations if this value has changed.
-   This is replicating a tiny part of what liquibase does
-   <https://github.com/metabase/metabase/pull/4094>

## Solve this problem<a id="sec-1-2" name="sec-1-2"></a>

### Hack Around the problem<a id="sec-1-2-1" name="sec-1-2-1"></a>

-   Hook Liquibase at runtime to turn the caching back on.
-   This is fragile and almost certainly bad.

### Fix the problem in Liquibase<a id="sec-1-2-2" name="sec-1-2-2"></a>

-   They had a problem with cach invalidation (which is the #2 problem in Computer Science after naming things, after naming things ;-)
    They fixed it by turning off the cache.

1.  Remove their Hack and turn the cache back on

    -   They are unlikely to want to merge this patch.
    -   leads to perma-fork and more work for us.

2.  Find a better method for Liquibase to clear the cache at the start of import

    -   I could be misinterpreting the problem they where trying to solve, though this may help other people that use Liquibase
    -   If this works then they are more likely to take the patch because it makes their library faster

### add one more layer of abstraction<a id="sec-1-2-3" name="sec-1-2-3"></a>

-   Adding just one more layer of abstraction solves all computer problems after all!

1.  Compile time preprocessing

    -   preprocess the migration blobs from one blob per file to many blobs in a single file
    -   We need to determine the application order here.

2.  runtime preprocessing

    -   move the migration scrips to a secure temp folder before each migration
    -   No need to figure out any ordering questions
    -   there needs to be a usable and properly functioning temp directory.

3.  consolidate migrations at runtime

    -   This combines the same process as the compile time prepossessing option with making a temp-file at runtime
    -   Only a temp-file is required, and it may be possible to do it with an in-memory buffer.

**Comment by thearthur** [comment]
https://github.com/metabase/metabase/pull/4793

consolidates the migration scripts into one file and solves part of this issue.
Remaining improvements include:
1. not running liquibase at all when there are certainly no updates (for instance if the build has not changed)
2. speed up applying update on the first launch.

**Comment by salsakran** [comment]
Can you profile the first launch and figure out where that 12 seconds is going?

**Comment by camsaul** [comment]
Implemented by #4763
