### ISSUE TITLE
This page is not working

### ISSUE THREAD

**Issue by boranb** [metabase/metabase#37161]
### Describe the bug

When I change some settings in the admin panel, I suddenly get the This page is not working error. What I did was change the language

### To Reproduce

1. go to admin panel
2. Go to the language changing screen
Change the 3rd language option from English to Turkish
Change the 4th language option from Turkish to English
5. If no error occurs, repeat
![toomany](https://github.com/metabase/metabase/assets/61060561/21775515-81dd-49c4-858c-41a943fc8128)

### Information about your Metabase installation

```JSON
Browser:		117.0.5938.132 64x
Database:		Mssql,Postgresql
Metabase version:	v0.48
Operating system:	w10 pro
Metabase host env:	Ubuntu 22.04 LTS
```

### Severity

very serious, system completely shut down

### Additional context

![toomany](https://github.com/metabase/metabase/assets/61060561/c6f2bf5d-bc22-4a39-b840-b7176e82f31b)

**Comment by Tony-metabase** [comment]
You need to share the metabase logs or better the instance logs you are running metabase on to see what is happening

Do you have some kind of proxy? and what happens after that error page is loaded, how do you fix this?

**Comment by boranb** [comment]
It doesn't get fixed unless you restore the backup. I went back to the backup I took yesterday, there are a lot of areas in the logs that I need to hide. Also, since I reinstalled the backup, we will not see this in the logs.

[log.txt](https://github.com/metabase/metabase/files/13792906/log.txt)

**Comment by Tony-metabase** [comment]
There is a lot of noise in the logs ... Try loading a separate instance via the backup and re-do the same and this time monitor the logs and the exact time it fails so its easier to pinpoint the issue.

Also share Admin -> Troubleshooting -> Diagnostic Info

**Comment by boranb** [comment]
Diagnostic Info:


{
  "browser-info": {
    "language": "tr-TR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1-post-Ubuntu-0ubuntu122.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1-post-Ubuntu-0ubuntu122.04",
    "os.name": "Linux",
    "os.version": "5.15.0-89-generic",
    "user.language": "en",
    "user.timezone": "Europe/Istanbul"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-19",
      "tag": "v0.48.1",
      "hash": "a8302d4"
    },
    "settings": {
      "report-timezone": "Turkey"
    }
  }
}

**Comment by paoliniluis** [comment]
what's the site url? what is the url of the instance? I guess this is a problem on your site url or you set up metabase in a sub path

**Comment by boranb** [comment]
Additionally, due to this situation, I am faced with an error like the one below.
![image](https://github.com/metabase/metabase/assets/61060561/76e06889-acb4-4a21-8eb6-92b4079e6e9d)

**Comment by boranb** [comment]
> [paoliniluis](/paoliniluis)

installed in subdomain I cannot share it because this system closed outside the institution address

**Comment by Tony-metabase** [comment]
Didn't you restore the backup before the issue? Or you where experiencing that even before? The settings should be visible. Share your HAR file when you access the settings page

**Comment by paoliniluis** [comment]
@boranb please check how to do the redirection correctly in the subdomain, you're facing a redirection from your reverse proxy

**Comment by bagafoot** [comment]
h

> Didn't you restore the backup before the issue? Or you where experiencing that even before? The settings should be visible. Share your HAR file when you access the settings page

what is HAR file, why the settings page unreachable when changing language, and how to restore this conf in database, which table store this information in metabaseappdb, Im using postgres

**Comment by boranb** [comment]
hi, @Tony-metabase 

The error where I could not see the settings section was fixed. Even though I cleared the cookies, it was not visible, but when I logged in with Firefox and checked Chrome again, I could see the settings section, but we are still wondering about the reason for the error I mentioned at first
