### ISSUE TITLE
[MLv2] [BE] [Bug] displayName for relative date time filters doesn't work correctly if query is not converted to legacy query first

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37175]
`expressionClause` function doesn't convert strings to keywords when needed and this leads to invalid mbql queries being created. It works correctly in production only because we convert the query to "legacy query" first and then retrieve it back, and it fixes the string <-> keyword mismatch.

In the following example I create a date filter with `Lib.expressionClause(["time-interval", column, "current", "day"])` and later `displayInfo` for this clause doesn't work correctly because other functions expect clojure keywords. The condition is evaluated incorrectly here - see that `n` and `unit` are strings and the function expects keywords:

<img width="1728" alt="Screenshot 2023-12-29 at 18 26 21" src="https://github.com/metabase/metabase/assets/8542534/aa56d892-65ea-4d4d-b1ac-47b9d5713c5b">

**Comment by devstein** [comment]
Hey @darksciencebase @ranquild would an LLM-based auto-labeling bot like [Dosu](https://github.com/apps/dosubot) be helpful for labeling issues and PRs at Metabase?
