### ISSUE TITLE
Cannot update table permissions for Groups with Limited access

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#3718]
Once I have defined table-level permissions for a Group, I'm unable to add permissions for additional tables to that Group without the existing permissions getting revoked.

Browser: Chrome 54.0.2840.71
OS: OS X 10.11.6
DB: Redshift
Metabase Version: 0.20.3
Hosted: Self-hosted Ubuntu 14.04.5 LTS
Internal DB: Default

Repro Steps:

1. Create a new Group in Metabase
2. Go to the Permissions page and click "Limit access" for that Group
3. Select 2 tables to grant access to and proceed to click "Save changes". Click "Yes"
4. Select an additional table to grant access to and click "Save changes" again. 
    - The following message is presented `Test Group will be given access to 1 table in {DATABASE}.`
    - Click "Yes"
5. Find that access to the initial 2 tables has now been revoked.

Expectation: The new table is *added* to the existing tables.
Actual: The new table *replaces* the existing tables the user has access to. 

If multiple tables are selected in Step 4, all of those tables replace the existing tables. However, de-selecting an existing table and re-adding it does not include it in the new set of tables. 

This behavior also occurs if, after Step 3, you navigate elsewhere in the app and then return to the Permissions page and edit a Group's permissions.

I can workaround this by completely revoking data access for that Group, saving the changes, and granting Limited access from scratch.

**Comment by camsaul** [comment]
Thanks @dacort, this does sound like the same issue as #3888 

Fixed by #3891
