### ISSUE TITLE
Enable to Show original schema in Data Reference

### ISSUE THREAD

**Issue by tomsej** [metabase/metabase#3719]
We have some power users who like writing SQL in Query Processor. But it is a little bit complicated because users do not know the physical names of database tables. In case of switching to SQL mode it would be awesome to change business names in Data Reference menu to the physical names from the database. Similarly to original schema switcher in Data reference.

**Comment by mazameli** [comment]
Closing this since the data reference sidebar in SQL mode now shows the underlying "physical" table names instead of the "business names."
