### ISSUE TITLE
Metabase problem with `directConnection` connection setting for MongoDB

### ISSUE THREAD

**Issue by mhbahmani** [metabase/metabase#37209]
### Describe the bug

We recently updated our metabase from 0.45 to 0.48.1. The update was successful and the new version Metabase is up and running. However, we have some problems with MongoDB databases (Replicasets). In older versions of Metabase, we set one of the Mongo replica set members in the database creation page in the admin panel and all the Metabase queries ran on that specific Mongo instance. But after this update, we found out that Metabase is now connecting to the MongoDB instance and gives all the replica set instances, and run the queries on one of them. So there is no limitation on the Mongo node that Metabase would use for running its query. However, to separate Metabase queries load from our production queries, we want Metabase queries to be executed on that specific MongoDB instance.

To get this functionality in the 0.48.1 version of Metabase, we tried using [directConnection](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/connection-options/) in the connection URI, but we're facing this warning log that shows this connection setting is not supported.
We tried using srv, setting database config via both connection string and filling out individual fields.

* The problem exists in both bare and docker installations.
* We tried installing a fresh Metabase instance and the problem still was there. So the update process should not be the root cause.

Our connection string:
`mongodb://username:*******@mongodb_instance_ip:27017/database_name?ssl=false&replicaSet=rs0&authSource=admin&directConnection=true`

Is that a bug in Metabase or we should get out the desired functionality in some other way?

### To Reproduce

1. Setup a Metabase instance with version 0.48.1
2. Define a MongoDB in Metabase databases and use of the replica set instances as the database host.
3. See that the queries are executing on all of the Mongodb nodes.

### Expected behavior

Queries to be executed on the specified node as the database host.

### Logs

`Jan  3 02:04:05 Metabase-Virtual-Machine-Hostname metabase[1965685]: 2024-01-03 02:04:05,180 WARN driver.uri :: Connection string contains unsupported option 'directconnection'.`

### Information about your Metabase installation

```JSON
- OS: Ubuntu 22.04
- Java Version:
`openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)`
```

### Severity

In order to remove the load of Metabase queries from our databases, we disconnected the Metabase from our databases. So, it's blocking our usage of Metabase.

**Comment by paoliniluis** [comment]
Is this similar to https://github.com/metabase/metabase/issues/15862?

I think that it never worked

**Comment by mhbahmani** [comment]
yes, it could be. We managed to limit the Metabase access to our production Mongodb instances to prevent it from affecting production. But before that, we saw the queries getting executed on other MongoDB nodes.
If this had happened before, I wonder how we never faced this issue. We have been using Metabase for maybe 3 4 years and this never happened. Is there some sort of change in the Mongo driver in the newer version of Metabase? Because it's for sure that Mongo driver supports directConnection setting :D

**Comment by paoliniluis** [comment]
We did some changes in how sessions work, so it should be related to that cc @FilmonK

**Comment by mhbahmani** [comment]
Now I'm focusing on why `directConnection` doesn't work. This wasn't talked about in your mentioned issue. But also it's good to know why we're facing this behavioral change in how Metabase connects to MongoDB replica sets after updating to v0.48.1. If this didn't happen, we would not have gone to use `directConnection` setting.

**Comment by lbrdnk** [comment]
@mhbahmani, we were using `monger` library for communication with mongo deployments. That library used older `mongo-java-driver`, version `3.12.11`. Reading its [api docs](https://mongodb.github.io/mongo-java-driver/3.12/javadoc/com/mongodb/ConnectionString.html) for `ConnectionString` class, it seems that driver of that version did not support `directConnection` parameter -- there is no mention of it.

With PR #38017 merged, `directConnection` parameter is now available, hence closing the issue.
