### ISSUE TITLE
We see that the error persists when there are dates in the custom column, for example:

### ISSUE THREAD

**Issue by juangc-wavyssa** [metabase/metabase#37216]
We see that the error persists when there are dates in the custom column, for example:
![image-20231226-154440](https://github.com/metabase/metabase/assets/112938617/f37bf5f8-d5b6-4170-8a80-f7a8bbcf2a09)
![image-20231226-154452](https://github.com/metabase/metabase/assets/112938617/c8b80de8-b53b-49a6-a6ee-12ee4e632dc1)

When we click on "visualizar" (visualize):

![image-20231226-154533](https://github.com/metabase/metabase/assets/112938617/abadc086-097e-487c-836b-c4cdce2e018b)

...and I go back to the report settings and see:
![image-20231226-154606](https://github.com/metabase/metabase/assets/112938617/2f4043c0-96de-40a0-89f0-4ecfd90e70c7)

In a report, when accessing it through a URL, it loads when you click, but if you go to the editor without making any changes and then click on "visualizar" (visualize), it gives an error.

Please, reopen the issue.

_Originally posted by @juangc-wavyssa in https://github.com/metabase/metabase/issues/36893#issuecomment-1872164004_

**Comment by darksciencebase** [comment]
reopened the original issue
