### ISSUE TITLE
[MLv2] [FE] Migrate ViewHeader to MLv2

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37227]
### ViewHeader

**Place 1**
https://github.com/metabase/metabase/blob/b14003c6de4e3b23ea7b0bde71579d92340115c5/frontend/src/metabase/query_builder/components/view/ViewHeader.jsx#L96

In MLv2 it could be:
```
const query = question._getMLv2Query();
const previousQuery = usePrevious(query);

useEffect(() => {
  // existing code

  const filtersCount = Lib.filters(query, -1).length;
  const previousFiltersCount = Lib.filters(previousQuery, -1).length;

  // existing code
});
```

**Place 2**
https://github.com/metabase/metabase/blob/b14003c6de4e3b23ea7b0bde71579d92340115c5/frontend/src/metabase/query_builder/components/view/ViewHeader.jsx#L110

In MLv2 it could be:
```
Lib.aggregations(query, -1).length > 0
```

For non-mbql queries `aggregations` would be an empty list.

`-1` means the last stage of the query.

**Place 3**
https://github.com/metabase/metabase/blob/b14003c6de4e3b23ea7b0bde71579d92340115c5/frontend/src/metabase/query_builder/components/view/ViewHeader.jsx#L419

MLv2:
```
const isNewQuery = Lib.sourceTableOrCardId(query) == null;
```

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/37375
- [ ] Migrate `ViewTitleHeaderRightSide` component
```

**Comment by nemanjaglumac** [comment]
Migrated steps 1 and 2 from the original issue description.
The only outstanding reference to the MLv1 in this file is (step 3):
https://github.com/metabase/metabase/blob/b14003c6de4e3b23ea7b0bde71579d92340115c5/frontend/src/metabase/query_builder/components/view/ViewHeader.jsx#L419

but we cannot fully migrate it until we start supporting native queries with MLv2.

cc @NevRA
