### ISSUE TITLE
Multi series questions won't get imported when using serialization

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#37232]
### Describe the bug

When using serialization, you get only 1 question when having a multi-series card on a dashboard

### To Reproduce

Create 2 questions
Add those 2 one on top of another
export
import

See that in the imported instance you get only the first question and there's no multi-series

### Expected behavior

We should get a multi-series card on import

### Logs

No logs, no exceptions, nothing

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P1

**Comment by calherries** [comment]
@metabase-bot backport release-x.47.x
