### ISSUE TITLE
Mongo GUI question is way slower than it's native twin

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#37245]
### Describe the bug

Something that we identified while debugging it on a customer instance (and we couldn't repro locally): a GUI query is way slower (5x-10x) than it's native counterpart, but there's no delay on the query processor (the /native endpoint is fast)

### To Reproduce

We can't reproduce this locally, but we have all the traces here https://drive.google.com/drive/folders/1cNGbnepp_6YXTYO4YlJrqYHDHeCoJOGG?usp=sharing

### Expected behavior

GUI query should be only a few milliseconds slower than it's native counterpart

### Logs

NA

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P1

### Additional context

I have a strong suspicion this is MLv2 stuff

**Comment by kamilmielnik** [comment]
The queries do seem to be equivalent.
I can see that POST `/api/card/*/query` is indeed 10x slower (0.6s vs 6s) for the GUI query.
Frontend has comparable performance in both cases, no issue here.
Judging by network records and screenshots the performance problem is fully on the backend side.
I can't say what happens in there and whether it's MLv2-related.

I replaced ".Frontend" with ".Backend" label.

**Comment by calherries** [comment]
I've added the 0.47.12 milestone because this should be backported to 47 and blocks the release

**Comment by metamben** [comment]
We are not sure this is a regression.

**Comment by metamben** [comment]
I can reproduce the problem with mongo 4.4, but cannot with mongo latest.
