### ISSUE TITLE
Collections remain accessible and usable post-archiving

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#37259]
### Describe the bug

Archived collections remain accessible, objects still can be created in them and they will show up in search.

### To Reproduce

1. Archive a collection.
2. Use the browser's back button to navigate back to the URL of the now archived collection.
3. (!) The collection remains accessible via its URL, and nothing indicates it is now archived.

4. Now create a question in the archived collection, it will succeed (probably also an error).
5. Enter the name of the question in the search bar.
6. (!) The question will show up, along with the name of the archived collection that contains it. It is possible to navigate to both.

### Expected behavior

When archived a collection should not be accessible, or perhaps be read-only.

### Information about your Metabase installation

```JSON
1.48.2
```

### Severity

Minor, I found it accidentally.

**Comment by rafpaf** [comment]
This is no longer the case - archived collections are labeled with "This collection is in the trash" and their contents have similar labels.

![Image](https://github.com/user-attachments/assets/941c4ada-51ae-4495-9c3d-3091f9861ead)
