### ISSUE TITLE
Public native questions with snippets don't work

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37270]
### Describe the bug

A native question that contains a snippet always returns errors when made public.

### To Reproduce

1. Enable public sharing in Admin settings
2. New -> SQL query
3. Create a native query snippet `CATEGORY = 'Gadget'` with name `IsGadget`
4. Set query to `SELECT * FROM ORDERS WHERE {{snippet:IsGadget}}`
5. Save the question
6. Share -> public question -> open the link
7. See the error

<img width="1726" alt="Screenshot 2024-01-04 at 15 53 17" src="https://github.com/metabase/metabase/assets/8542534/8d026500-d03d-4182-b448-3a74ee04b699">
<img width="1727" alt="Screenshot 2024-01-04 at 15 53 25" src="https://github.com/metabase/metabase/assets/8542534/c12bb847-eab5-4d00-81d7-1b786f0c6cb9">

### Expected behavior

I should see question results

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-LTS",
    "os.name": "Mac OS X",
    "os.version": "12.1",
    "user.language": "en",
    "user.timezone": "Asia/Jerusalem"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-01-04",
      "src_hash": "f566ffd0966ca096ad05e3d0a080a917e9932288",
      "tag": "v0.48.1-SNAPSHOT",
      "hash": "3d45805"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P1

**Comment by ranquild** [comment]
Related to https://github.com/metabase/metabase/issues/34564

**Comment by ranquild** [comment]
I believe it's a FE bug - we shouldn't convert the snippet template tag into a parameter.

**Comment by ranquild** [comment]
@darksciencebase turned out to be a BE bug. The incorrect list of parameters is returned by the BE endpoint. There should be no parameters for snippet template tags. 
<img width="1728" alt="Screenshot 2024-01-05 at 15 46 57" src="https://github.com/metabase/metabase/assets/8542534/07a23081-271f-4431-a085-0dc5d15f3a2b">

**Comment by bpartridge** [comment]
Potential rollout issue for this, cross-posting here as it may impact existing public links for various Metabase Cloud customers: https://github.com/metabase/metabase/issues/34564#issuecomment-1921772420
