### ISSUE TITLE
Dashboard filters are slow

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#37285]
### Describe the bug

Dashboard filters can take a long time.

Eg: https://stats.metabase.com/dashboard/1880?tab=347
Searching by customer name can take >30seconds

There's no getting around searching, but I think we can be better.

### To Reproduce

Make a question selecting People in the GUI. Add this question to a dashboard 6 times, add a category filter on email.

Search for `andreanne`

Searching for "billy" runs the following query for each dashcard:

```clojure
{:database 1
      :type :query
      :query {:source-table 5
              :breakout [[:field 51 nil]]
              :limit 1000
              :filter [:contains
                       [:field 51 nil]
                       "billy"
                       {:case-sensitive false}]}
      :middleware {:disable-remaps? true}}
```

Observe that in `metabase.api.dashboard/chain-filter` it gets the field values for that field for each time and then deduplicates the values. We should dedupe on the field-id here.

Same issue for native queries with field filters on them. Notice that if the param doesn't have any field ids it can identify it runs `filter-values-from-field-refs` which again does not deduplicate on field refs.

<img width="1060" alt="image" src="https://github.com/metabase/metabase/assets/6377293/395bd683-ae21-4550-a4f4-8cbf1b06d949">

### Expected behavior

We should only run as many queries as we need, and not run a query for each dashcard. It's true that each dashcard could have the same field-id but with different where clauses, etc that dictate allowable values, but we don't factor that in. We only get the field values for the field and don't factor the question in. So lets not do extra work.

### Information about your Metabase installation

```JSON
-
```

### Severity

-

**Comment by paoliniluis** [comment]
Fixed by https://github.com/metabase/metabase/pull/37318
