### ISSUE TITLE
Grant segment permission to group

### ISSUE THREAD

**Issue by kldeb** [metabase/metabase#3728]
We'd like to give our external business partners access to our Metabase install. We'd like to make sure that each partner can only view customer information that is relevant to them. It would be helpful if we could create a group for each partner and allow access to their customer segment rather than the table itself.

**Comment by inventti-paulo** [comment]
+1

**Comment by tlrobinson** [comment]
Related to #2824

**Comment by kreno** [comment]
This would be most helpful to us also.  I work for a school district in Yuma, AZ.  We would like to allow access to rows based on location code, and/or account code.  Departments and campuses can only look at their own data.   To give them what they need right now, I need to create a view for each campus and department and give them permission to the pertinent view.

I know this is a huge endeavor, but it would be very helpful to us.

**Comment by metalocator** [comment]
We could use this as well.  Basically something like a customer-specific always enabled "Where" condition.  E.g. WHERE customer_id = 123456

**Comment by flamber** [comment]
Closing, since this is available in the [Enterprise Edition](https://www.metabase.com/enterprise/) as [Sandboxing](https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html)
