### ISSUE TITLE
[dc.js migration] storybook visual test for bubble size with breakout

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#37281]
https://github.com/metabase/metabase/pull/37143 fixed scatter charts not rendering when bubble size was enabled for charts with a breakout, but did not add a storybook example to serve as a reproduction test for this regression

**Comment by alxnddr** [comment]
@EmmadUsmani let's stick to using `.echarts-regression` label only for actual regressions in the new implementation
