### ISSUE TITLE
[MLv2] [BE] [Bug] format() throws for simple expressions

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#37292]
### Steps to reproduce

1. Create GUI question based on Orders table
2. Add custom column
    - name: `whatever`
    - expression: `1`
    - click "Done"
3. Click the custom column to edit it

### Actual result

`format` throws `Uncaught Error: Unknown MBQL clause ["value",1,null]`.
GUI editor crashes.

### Context

`master`, [78b66bc](https://github.com/metabase/metabase/commit/78b66bcae60588f9840f4e357e86a5a4a73bb2ac)
Related to #36254.
This used to work in v47.

**Comment by uladzimirdev** [comment]
Findings so far:

before migration: 
<img width="392" alt="image" src="https://github.com/metabase/metabase/assets/125459446/48fca43c-e0c5-4637-8710-834a984cf367">

after
<img width="591" alt="image" src="https://github.com/metabase/metabase/assets/125459446/b5e6b240-c2a5-4084-a507-57a280de57be">

**Comment by ranquild** [comment]
Caused by https://github.com/metabase/metabase/issues/37461
