### ISSUE TITLE
Editing metadata of a model is not possible when the model returns an empty recordset

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#37300]
### Describe the bug

It is not possible to edit the metadata of a model when the model does not return any records, because the metadata editor won't display the column header in this case.

### To Reproduce

1. Create or update a model, and set filters so that the model does not return any records
2. Switch to Metadata
3. No results! is displayed, and the header will be hidden which makes it impossible to select a column to edit its metadata.
<img width="863" alt="image" src="https://github.com/metabase/metabase/assets/11080638/0771af83-e0fd-4291-8cbe-57961cddb525">

### Expected behavior

A column header should still be present.

### Information about your Metabase installation

```JSON
1.48.1
```

### Severity

Probably minor as it is not a common practice to edit models returning no data. I don't know a workaround though.

**Comment by kamilmielnik** [comment]
Reproducible in `master` at 6b1289e89a.
