### ISSUE TITLE
Item dropdown menu overflows the viewport in Collections page

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#37343]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6830683/6b98f95b-db7f-4f49-aaa5-3ca47f596cc2)

### To Reproduce

1. Go to https://stats.metabase.com/collection/616
2. Open menu for any of the 2 items on the list at the bottom of the page

Can't see all the options in the dropdown menu. Can't scroll to see all the options.

### Expected behavior

Dropdown opens up if there's not enough space for it in the viewport below the trigger button

### Information about your Metabase installation

master, v48, a2d1fc3

### Severity

P2

**Comment by iethree** [comment]
can't reproduce in chrome or firefox 😢 

![Screen Shot 2024-01-16 at 8 33 18 AM](https://github.com/metabase/metabase/assets/30528226/32e37373-9c34-4aa9-8d13-bb30dd4b8140)

**Comment by kamilmielnik** [comment]
I can still reproduce it.

Yes, the bookmark is the only option on the list.

The overflow is tiny, but noticeable/annoying enough that I reported this as issue:
![image](https://github.com/metabase/metabase/assets/6830683/96bb1641-4378-4264-9c2f-7fdb1d2e373a)

----

Bonus: sometimes 2 vertical scrollbars appear (see your 2nd screenshot).

----

To fix this the dropdown should not be touching the edge of the viewport - there should be a margin/padding (unless the viewport is smaller than the dropdown). Something like [`padding` in "detect overflow" in popper.js](https://popper.js.org/docs/v2/utils/detect-overflow/#padding).
