### ISSUE TITLE
BE - Add "metric" card type

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#37348]
Depends on:
- https://github.com/metabase/metabase/issues/38706

----

- [ ] Add a new value to enum from #37367.
- [ ] MLv2 schema and other Malli schemas should allow this
- [ ] Add to TypeScript signatures?
- [ ] Rest API should accept this when creating a new Card. Don't worry about additional constraints, we'll do that in #38733

**Comment by crisptrutski** [comment]
Hi @kamilmielnik, let me know if you want to take over the task that blocks this. I'm brand new here and will be pretty slow on the task. I have my first pairing session with my [onboarding buddy](https://github.com/calherries) tomorrow as another option to speed things up.

**Comment by kamilmielnik** [comment]
> Hi @kamilmielnik, let me know if you want to take over the task that blocks this. I'm brand new here and will be pretty slow on the task. I have my first pairing session with my [onboarding buddy](https://github.com/calherries) tomorrow as another option to speed things up.

@crisptrutski  Actually that task was linked by mistake. Updated. Thanks for staying alert!

**Comment by camsaul** [comment]
This was partially done in #38981, we probably need to add some more stuff in and add some tests to make sure it works end to end
