### ISSUE TITLE
[MLv2] [BE] [Bug] Joining unrelated tables breaks visibleColumns and downstream functions

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37347]
<img width="1330" alt="Screenshot 2024-01-08 at 13 41 24" src="https://github.com/metabase/metabase/assets/8542534/102644fe-4a96-472e-b194-9d5f1518b8c6">

Repro:
- New -> Question
- Raw data -> Reviews
- Join -> Raw data -> Orders -> Select ID column in each table

Issues:
- 2 "Product" groups
- how "Users" (People) table appeared here? there is no FK in the Reviews table to People
- why "Order" and not "Orders" since it's an explicit join?

**Comment by snoe** [comment]
The 2 products are due to `reviews -> product-id` and `orders -> product-id` since those are different paths they are both present (see https://github.com/metabase/metabase/issues/34742)

Users comes from `orders -> user-id`

I don't know why you see "Order" -> where are you getting that display info? I see "Orders"

```
[:source/joins
  "Orders__SUBTOTAL"
  {:is-breakout false,
   :table {:name "ORDERS", :display-name "Orders", :long-display-name "Orders", :is-source-table false},
   :is-aggregation false,
   :semantic-type nil,
   :name "SUBTOTAL",
   :effective-type :type/Float,
   :is-from-join true,
   :long-display-name "Orders → Subtotal",
   :display-name "Subtotal",
   :is-from-previous-stage false,
   :is-calculated false,
   :is-implicitly-joinable false}]
   ```

**Comment by ranquild** [comment]
It turned out to be the expected behavior. Previously implicitly joined tables were only supported for data source itself, and now it works with explicitly joined tables as well. This caused some FE tests to fail. Closing. @snoe fyi
