### ISSUE TITLE
Upgrade to 48.2 failed due to a migration error

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#37344]
### Describe the bug

Upgrading from 47.7 to 48.2 failed with the following error

```
2024-01-06T21:08:44.822152+00:00 app[web.3]: 2024-01-06 21:08:44,817 ERROR metabase.core :: Metabase Initialization FAILED
2024-01-06T21:08:44.822159+00:00 app[web.3]: java.sql.BatchUpdateException: Batch entry 0 UPDATE databasechangelog SET FILENAME = CASE WHEN ID = 'v00.00-000' THEN 'migrations/001_update_migrations.yaml' WHEN ID < 'v45.00-001' THEN 'migrations/000_legacy_migrations.yaml' ELSE 'migrations/001_update_migrations.yaml' END was aborted: ERROR: duplicate key value violates unique constraint "idx_databasechangelog_id_author_filename"
2024-01-06T21:08:44.822159+00:00 app[web.3]: Detail: Key (id, author, filename)=(v00.00-000, qnkhuat, migrations/001_update_migrations.yaml) already exists. Call getNextException to see other errors in the batch.
```

### To Reproduce

Upgrade from 47.7 to 48.2

### Logs

[crash_metabase.log](https://github.com/metabase/metabase/files/13859083/crash_metabase.log)
[sql_logs.log](https://github.com/metabase/metabase/files/13859084/sql_logs.log)

### Information about your Metabase installation

```JSON
N/A
```

### Severity

P1

**Comment by bunnywrote** [comment]
I run into the same issue by updating to v1.48.2. Downgrading to v1.47.11 was not possible, because of corrupted database.
Had to restore database from backup :(

```
{"log":"Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Table 'metabase.data_migrations' doesn't exist","logtag":"F","time":"2024-01-09T17:20:56.270537319Z"}
{"log":"Caused by: java.sql.SQLSyntaxErrorException: (conn=65141) Table 'metabase.data_migrations' doesn't exist","logtag":"F","time":"2024-01-09T17:20:56.27053284Z"}
```

**Comment by qnkhuat** [comment]
@bunnywrote I don't think it relates to this issue; that seems like a separate one. Could you create an issue?
It'd be easier for us to debug if you include the full log and your system info.
Thanks

**Comment by qnkhuat** [comment]
Discussion thread: https://metaboat.slack.com/archives/C064EB1UE5P/p1704840138989869 and https://metaboat.slack.com/archives/CKZEMT1MJ/p1704711031513779

**Comment by aleontiev** [comment]
@noahmoss I tried running `migrate down` to go back to 47.12 and it didn't work:

```Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_databasechangelog_id_author_filename"
  Detail: Key (id, author, filename)=(v00.00-000-BACKUP, qnkhuat, migrations/000_migrations.yaml) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        ... 54 more
Command failed with exception: Batch entry 0 UPDATE databasechangelog SET FILENAME = 'migrations/000_migrations.yaml' was aborted: ERROR: duplicate key value violates unique constraint "idx_databasechangelog_id_author_filename"
  Detail: Key (id, author, filename)=(v00.00-000-BACKUP, qnkhuat, migrations/000_migrations.yaml) already exists.  Call getNextException to see other errors in the batch.```
  
  Big :+1: to this thread and @qnkhuat the Slack threads are not visible to non-Metabase employees... what is the fix for this? 
  Can you provide a list of database changes between 47 and 48??

**Comment by qnkhuat** [comment]
Could you provide us with a dump of your `databasechangelog` after you tried upgrading?

**Comment by qnkhuat** [comment]
@aleontiev, it looks like you have successfully upgraded to 48 before on Jan 8th? this is indicated by there are `v48.*` migrations in your databases.

The strange thing is that for some reason you have 2 migrations with id `v00.00-000` but with different filename
```
id | author | filename
v00.00-000 | qnkhuat | migrations/001_update_migrations.yaml
v00.00-000 | qnkhuat | migrations/000_migrations.yaml
```

I still haven't figured out how it is possible that you can have this state. Could you share more about how you run Metabase? Are you using multiple instances? and what your upgrade process looks like?

For the fix, you can just delete one of these 2 rows, and it should be fine.

```
delete from databasechangelog where id = 'v00.00-000' and author = 'qnkhuat' and filename = '001_update_migrations.yaml';
```

Remember to backup your DB before making these changes :)

**Comment by aleontiev** [comment]
@qnkhuat 🙏 thank you very much! That did the trick. 

We run Metabase through the unofficial Kubernetes Helm chart with multiple replicas turned on... I can see now how that caused an issue if both replicas were applying the migrations simultaneously without some kind of lock to synchronize them.

Will rethink the setup

**Comment by qnkhuat** [comment]
Might be fixed by https://github.com/metabase/metabase/pull/38257, please re-open the issue if you encounter this again

**Comment by wstewarttennes** [comment]
<img width="857" alt="Screenshot 2024-07-27 at 11 42 31 AM" src="https://github.com/user-attachments/assets/a489fd3b-6b60-46d7-b31c-2fd87e5c1f5a">
I'm seeing this same issue -- i just run metabase using a dockerfile with latest tag so this might have happened because of a bad deploy?

**Comment by paoliniluis** [comment]
@wstewarttennes please never ever use the latest tag… you need now to restore a backup and do the process from the beginning

**Comment by wstewarttennes** [comment]
hi @paoliniluis, thank you for the help - which process do i need to do?
