### ISSUE TITLE
FE - Add "Metric" option to "+ New" dropdown menu (+ `/metric/notebook` route boilerplate)

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#37352]
Depends on:
- #37348

----

- [x] Add new option to the menu. It should match visibility settings of models & questions.
- [x] Add icon for the metric.
- [x] Add a new empty `/metric/notebook` route and redirect there on click.

**Comment by nemanjaglumac** [comment]
Done in https://github.com/metabase/metabase/pull/38404
