### ISSUE TITLE
Multiselect Dashboard Option

### ISSUE THREAD

**Issue by sabino** [metabase/metabase#3736]
### Feature request and proposal
Hi there! I was thinking about adding a multiselect possibility to the Category Filter on the dashboard.
Something like this:

![multiselect](https://cloud.githubusercontent.com/assets/982190/20058568/ce0b0372-a4d8-11e6-998a-4d755eadc0f6.png)

What do you guys think?

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by mazameli** [comment]
With query builder category filters, we just enable multi-select by default, and I'm thinking we could and should just follow suit on dashboard filters.

![01 filter](https://user-images.githubusercontent.com/2223916/33404092-dae54ce0-d517-11e7-8ed1-cc626a38b9ba.png)
![02 selections](https://user-images.githubusercontent.com/2223916/33404094-daf933ea-d517-11e7-8514-a3ebf78b32bc.png)
![03 active filter](https://user-images.githubusercontent.com/2223916/33404095-db0d9cfe-d517-11e7-9759-72e4233b69ce.png)

**Comment by mokra** [comment]
will this also work with a bigger list of options - like 100 options?
If so, then a search field will be useful

**Comment by jornh** [comment]
@mokra see https://github.com/metabase/metabase/pull/6563#issuecomment-350965400 in the WIP implementation

**Comment by jornh** [comment]
@mokra to answer your https://github.com/metabase/metabase/pull/6563#issuecomment-353890034:

I believe it by default should work with a list with 100 but not 1000. Looks like the limit could be defined in https://github.com/metabase/metabase/blob/8f921f9cb78837bd7cd8271e26b4cda014a6a6ef/src/metabase/models/field_values.clj#L10 

I’m basing my assumption on this comment:
http://discourse.metabase.com/t/restricted-amount-of-entries-in-drop-down-filter/1646/2?u=jornh

**Comment by mazameli** [comment]
Implemented by https://github.com/metabase/metabase/pull/6563
