### ISSUE TITLE
BE - Migrate `dataset: true` to enum value

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#37367]
See https://github.com/metabase/metabase/issues/29752#issuecomment-1501976631

This is just about turning the boolean into an enum.
Adding a new "metric" value to that enum should be done in #37348.

Suggested attribute name: `type`
Suggested enum values: `"question"` & `"model"` (in [the future also `"metric"`](https://github.com/metabase/metabase/issues/37348))

### Notes (Added by Cam 2/13/24)

This was partially implemented in #38074. #38074 adds the new `type` column, but does not remove the `dataset` column or migrate things to use it in the application database. Let's finish that work and remove `dataset` entirely. We also need to update MLv2 code and other things that #38074 missed to look at `type` rather than `dataset`.

This may need to be done in sync with https://github.com/metabase/metabase/issues/38706

**Comment by qnkhuat** [comment]
what's the expected behavior on downgrade?

**Comment by NevRA** [comment]
@kamilmielnik wdyt? I think it should delete the enum & restore the dataset

**Comment by kamilmielnik** [comment]
Agreed. It should reverse the migration.

**Comment by qnkhuat** [comment]
what about the new metrics? is it okay if we delete them?

**Comment by NevRA** [comment]
Based on [this](https://metaboat.slack.com/archives/C051AG38B2S/p1705062361255429) discussion we probably will not be able to migrate v1 to v2. And I think v2 -> v1 will not be possible as well. I am open to any suggestions if you think this is not the case
Let's try to make the best effort possible to avoid overcomplicating things. If we won't be able to support all cases during the downgrade, so, let's at least ensure that the data remains in the tables, making sure we don't drop them. 
>Turning them into normal questions sounds easy and is probably ok.
Looks like this is our way for now

**Comment by qnkhuat** [comment]
List of APIs will be affected by this change.
This list will be updated as I find out more
- /api/card/
- /api/card/:id
- /api/database/:id/card_autocomplete_suggestions

**Comment by camsaul** [comment]
Reopening because #38074 did not migrate things over to `type`; `dataset` is still there.

**Comment by camsaul** [comment]
#38074 is also missing updates for all the MLv2 code to look at `type` rather than `dataset`

**Comment by kamilmielnik** [comment]
We will also need to change `dataset` to `type` in bookmarks and `/api/database/:id/card_autocomplete_suggestions`.
Bookmarks already have `type` attribute though, but it's something else.

**Comment by kamilmielnik** [comment]
> We also need to change `dataset` to `type` in [bookmarks](https://github.com/metabase/metabase/blob/8b19867/frontend/src/metabase-types/api/bookmark.ts#L13) and [`/api/database/:id/card_autocomplete_suggestions`](https://github.com/metabase/metabase/blob/6657c3cb754e3cb105b44596640158e3ee8ef0e4/frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx#L84).

I've created 2 FE issues for it: #38807 & #38808.

cc: @camsaul
