### ISSUE TITLE
[MLv2] [BE] Make displayInfo for column groups straightforward to use

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37369]
Currently the FE has to use a utility function everywhere when displaying `ColumnGroup`:

```
export function getColumnGroupName(groupInfo: ColumnGroupDisplayInfo) {
  return groupInfo.fkReferenceName || groupInfo.displayName;
}
```

This is not straightforward. We never use `fkReferenceName` or its own, and we never use `displayName` for `ColumnGroup` outside of this function.  

We should improve the API - only `displayName` should be used without additional checks on the FE. MLv2 should update `displayName` for `ColumnGroup` to be the result of this function under the hood.

Without this check when using raw `displayName` now:
<img width="479" alt="Screenshot 2024-01-09 at 14 07 32" src="https://github.com/metabase/metabase/assets/8542534/85d10b31-4a8f-45ae-8239-82564407c23b">

With this check:
<img width="413" alt="Screenshot 2024-01-09 at 14 08 10" src="https://github.com/metabase/metabase/assets/8542534/9a901526-8901-4b2e-a1d8-9f93a0bee11f">

**Comment by snoe** [comment]
See https://github.com/metabase/metabase/issues/37347 here for a good reproduction to make column group displays more useful
