### ISSUE TITLE
Incorrect Save dialog is shown when user has curate access on collection, but no self-service access on source

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#37373]
### Describe the bug

When a question is modified, an incorrect Save dialog will be shown for a user that has curate access on the collection but no self-service access on the question's source.

### To Reproduce

1. Start a new question, simple table visualization on Sample Database / Products, and save it.
2. Open it with another user that has Curate access on the collection, and No self-service access on the Products table
3. Change the visualization (e.g. resize the columns, or switch to detail viz)
4. The question becomes dirty, click Save
5. (!) A _Save new question_ dialog appears that does not prompt for the _Name_ / _Description_ and _Collection_:
<img width="653" alt="image" src="https://github.com/metabase/metabase/assets/11080638/5eff5629-412a-4155-9028-d54886858578">

6. (!) When clicking Save, it is the original question that will be overwritten. The user will not have a chance to specify a new name or a different collection.

### Expected behavior

As the user has curate access, I'd expect the usual Save question dialog to be shown that offers either overwriting the original, or saving it as a new question.

### Information about your Metabase installation

```JSON
1.48.1
```

### Severity

Slightly confusing. It may lead to inadvertent changes of existing questions.

**Comment by kamilmielnik** [comment]
"Self-service" has been deprecated: https://www.metabase.com/docs/v0.50/permissions/no-self-service-deprecation

**Comment by nemanjaglumac** [comment]
The E2E reproduction for this issue has existed all along. We just didn't realize it.
I think it's safe to close this as already fixed.

https://github.com/metabase/metabase/blob/master/e2e/test/scenarios/permissions/permissions-reproductions.cy.spec.js#L334
