### ISSUE TITLE
Users with no self-service access may update pivot tables and leave them in a non-working state

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#37380]
### Describe the bug

Users with no self-service access are allowed to update visualization settings of pivot tables, and they may save cards in a non-workable state with corrupted visualization settings.

### To Reproduce

1. Create a pivot table, on the sample database: Products, Count, Grouped by Category and Rating. Save it.
2. Open it with another user with no self-service access to Products
3. Open visualization settings, and rearrange Rows / Columns / Measures
4. (!) We get the error `You do not have permissions to run this query`.
<img width="684" alt="image" src="https://github.com/metabase/metabase/assets/11080638/c1ed5b75-f050-4451-9305-d04df5becbca">

5. The question becomes dirty, so try to Save it and a Save new question dialog box appears.
 Hit Save again, the original question will be overwritten.  The incorrect dialog error in this step is reported separately in https://github.com/metabase/metabase/issues/37373)

<img width="652" alt="image" src="https://github.com/metabase/metabase/assets/11080638/83c8a574-c645-467b-8f43-b758745e7abd"> 

6. (!) The card is now broken, with incomplete visualization settings.
<img width="150" alt="image" src="https://github.com/metabase/metabase/assets/11080638/108249ef-9163-4859-859f-2a3c620a946e">

With the no self-service access user it is not possible to return the card into a working state.

### Logs

Console log:
```
session-middleware.js:53 Error: Invalid metadata returned for cell 1:
        x:104, y:0, width:NaN, height:30
    at t.cellCount (calculateSizeAndPositionData.js:17:13)
    at t.value (calculateSizeAndPositionData.js:35:1)
    at t.value (CollectionView.js:315:27)
```

api/card response:
```
[...]
    "visualization_settings": {
        "pivot_table.column_split": {
            "rows": [
                [
                    "field",
                    740,
                    {
                        "base-type": "type/Text"
                    }
                ],
                [
                    "field",
                    742,
                    {
                        "base-type": "type/Float",
                        "binning": {
                            "strategy": "default"
                        }
                    }
                ]
            ],
            "columns": [],
            "values": []
        },
[...]
```

### Information about your Metabase installation

```JSON
1.48.1
```

### Severity

A similar issue is blocking some users.

**Comment by nemanjaglumac** [comment]
MLv2 fixed this on `master`.
Still reproducible in the originally reported version, and in `x.48.3`.

**Comment by kamilmielnik** [comment]
The key to reproduce this issue is to deny user access to the Products table but allow access to the database itself.
