### ISSUE TITLE
[MLv2][BE] Introduce a new MLv2 function to handle column type checks

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#37412]
Currently we don't have a way to get a `base_type` of the `ColumnMetadata`

Example of the old behaviour
https://github.com/metabase/metabase/blob/master/frontend/src/metabase-lib/parameters/utils/click-behavior.ts#L168C23-L193

Here we get a `base_type` from the field of Dimension and compare it with the one which passed from the filter by `isa` function.

We need a way to check if MLv2 columns are "compatible", .e.g compare `Number` with `BigInteger` ![image](https://github.com/metabase/metabase/assets/125459446/e71a13a0-b55c-45ec-85e9-f15e4b5ebb79)

**Comment by metamben** [comment]
We have an MLv2 functions  in the `metabase.lib.types.isa` namespace, which can test things like `temporal?`, `numeric?`, or `string?`. Could you use them?

**Comment by uladzimirdev** [comment]
@metamben we don't need to know if the type `temporal`, `numeric` or whatever, we need to know relations between types (the same or descendant or no)

**Comment by ranquild** [comment]
Closing in favour of https://github.com/metabase/metabase/pull/37438
