### ISSUE TITLE
[dc.js migration] timeseries x-axis label is cut off

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#37420]
http://localhost:3000/question/85-line-aapl-stock

The last date label is cut off. This only happens when the width of the chart is too small, both on the dashboard and in the query builder.

![image](https://github.com/metabase/metabase/assets/37751258/99150edd-54e4-4b0d-9c01-f95aea821dee)

<img width="614" alt="Screenshot 2024-01-08 at 3 52 53 PM" src="https://github.com/metabase/metabase/assets/37751258/a302031a-3f77-4bf7-b0ac-f3e2fa974a67">

http://localhost:6006/?path=/story/static-viz-combochart--trend-combo

Same issue but here the first date label is cut off.

<img width="566" alt="Screenshot 2024-02-08 at 9 45 42 AM" src="https://github.com/metabase/metabase/assets/37751258/6291739f-f3f6-4950-b5c3-3efa271919b6">

**Comment by EmmadUsmani** [comment]
@alxnddr This is probably caused by the `grid` option, as removing it fixes the cut off

https://github.com/metabase/metabase/assets/37751258/68c55aee-9182-44e9-94af-22cd8e928fbe

**Comment by alxnddr** [comment]
> @alxnddr This is probably caused by the `grid` option, as removing it fixes the cut off

Default grid paddings are too huge so it looks ok in this specific case but it is still broken. We need to compute grid based on the ticks dimensions including adding some horizontal space for long x-axis ticks

**Comment by EmmadUsmani** [comment]
> We need to compute grid based on the ticks dimensions including adding some horizontal space for long x-axis ticks

Yup I'm currently working on a solution that does this

**Comment by alxnddr** [comment]
@EmmadUsmani the old `dc.js` implementation actually adds paddings and I think this route is simpler:
<img width="423" alt="Screenshot 2024-02-13 at 4 53 46 PM" src="https://github.com/metabase/metabase/assets/14301985/623f519f-d52f-468c-85fd-3c90de35f327">
The logic of side padding calculation should be like `sidePadding = Math.max(yTicksWidth + AxisName, xTickWidth / 2)`
