### ISSUE TITLE
Embedding height is not dynamic

### ISSUE THREAD

**Issue by JasonStrazisar** [metabase/metabase#37437]
### Describe the bug

When embedding a dashboard, and using a "dynamic" iFrame resize, like [iFrameResizer](https://github.com/davidjbradshaw/iframe-resizer), the height of the html is always expending, but never shrinking when it change, due to the use of `height: 100%;` instead of `height: auto;` on the metabase html tag.

https://github.com/metabase/metabase/assets/59898438/9b89b1a2-de16-419d-b3e6-2c370f22f93c

But, when I change the `height` to `auto`, it work as excepted:

https://github.com/metabase/metabase/assets/59898438/91faf735-6f65-41f3-8d89-53ff5f7d2b5e

### To Reproduce

- Using a metabase embedding.

### Information about your Metabase installation

```JSON
- macOS 14.1 (23B2073)
- chrome 120.0.6099.129
- metabase: metabase-enterprise:v1.47.7
```

### Severity

Annoying but not blocking

**Comment by albertoperdomo** [comment]
Hello @JasonStrazisar ,

just to double check: This is using what type of embedding, public, static or interactive?

**Comment by paoliniluis** [comment]
Similar/related to https://github.com/metabase/metabase/issues/30634 ?

**Comment by JasonStrazisar** [comment]
> Hello @JasonStrazisar ,
> 
> just to double check: This is using what type of embedding, public, static or interactive?

Hey ! This is on interactive embedding

**Comment by albertoperdomo** [comment]
Thanks @JasonStrazisar,

have you tried using [postMessage](https://www.metabase.com/docs/latest/embedding/interactive-embedding#supported-postmessage-messages-from-embedded-metabase) to dynamically adjust the iframe? I don't think iframeResizer is supposed to work for interactive embedding.

**Comment by JasonStrazisar** [comment]
Hey ! Yes I tried using postMessage with the 'fit' mode, the only problem, is that the only message the embedd send is with the frame mode set to 'normal', I never get a 'fit' frame mode, is there something to setup before doing it on metabase ? I looked through the documentation, but I didn't found if there was something to do (apart from setting up the listening)

**Comment by bertrandjamin** [comment]
Hi @albertoperdomo  I work with Jason and we are still stucked with this issue. 

Did you fund time to check why the 'fit' event doesn't occur on our side ? 

cc @paoliniluis

**Comment by saqib-airflip** [comment]
I have the same issue.

**Comment by bitshadow** [comment]
> Hello @JasonStrazisar ,
> 
> just to double check: This is using what type of embedding, public, static or interactive?

I can confirm exact behaviour is happening for static embedding as well. We are using `iframe-resizer-react`.

```
      <IframeResizer
        key={src}
        // heightCalculationMethod="taggedElement"
        sizeHeight
        src={src}
        log
        style={{
          width: '1px',
          minWidth: '100%',
          border: 'none',
        }}
      />
```

**Comment by albertoperdomo** [comment]
Many folks on this issue were using interactive (full-app) embedding. For that, the recommended setup is to listen for the 'fit' event with postMessage. This has been fixed in https://github.com/metabase/metabase/pull/40841. The fix has also been backported and is available in releases 49.4 and newer.

**Comment by albertoperdomo** [comment]
What's your issue with static @bitshadow and what version are you using?

**Comment by bitshadow** [comment]
> What's your issue with static @bitshadow and what version are you using?

When using the `iframe-resizer-react` it is supposed to downscale height automatically. It scales iframe to max height but doesn't downscale height. Is there a way to achieve it with static embedding? 

It works fine when I set the Metabase html tag height inside iframe to `auto` instead of `100%`. But we can't modify iframe because of limitations.

https://github.com/metabase/metabase/assets/574802/2d8fd280-63fc-4cd3-9920-8bef39627760

Version Information:
- macOS 14.2 (23C64)
- Chrome 123.0.6312.107 (Official Build) (arm64)
- metabase: metabase-cloud:v1.48.6

**Comment by paoliniluis** [comment]
@bitshadow move to the latest version and it should work

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Hi @dragonsahead,
How do you know the problem is solved with last version of Metabase ?
Because I have the exact same proble as @bitshadow with version "0.57.2" of Metabase.

Thanks in advance for your help !
