### ISSUE TITLE
Subscription intermittently fails to deliver

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#37459]
### Describe the bug

We have a Slack subscription that sometimes fails to be delivered.
More context in [Slack](https://metaboat.slack.com/archives/C05MPF0TM3L/p1704727823706109).

Possibly related to https://github.com/metabase/metabase/issues/14613

### To Reproduce

See Slack
Dashboard: https://stats.metabase.com/dashboard/615

Subscription is configured to be delivered weekly on Mondays via Slack.

Recent timeline and outcome:
* **Failure**: 2023-12-04
* Success: 2023-12-11
* Success: 2023-12-18
* Success: 2023-12-25
* Success: 2024-01-01
* **Failure**: 2024-01-08
* Success: 2024-01-15
* Success: 2024-01-22
* Success: 2024-01-29
* Success: 2024-02-05
* **Failure**: 2024-02-12

### Expected behavior

Delivery should not fail

### Information about your Metabase installation

```JSON
- Stats
```

### Severity

I can see this being a blocking for customers, who don't want to depend on unreliable features

**Comment by piranha** [comment]
Discovered so far: logs for `send-pulses!` on both jan 8 and dec 4 end with `Starting Pulse Execution: 181`, which runs for [dashboard 415](https://stats.metabase.com/dashboard/415). When this subscription runs successfully, it takes about 10 minutes. When it does not, all execution stops at that point.

**Comment by paoliniluis** [comment]
Adding https://github.com/metabase/metabase/issues/12084 as this has been haunting us since literally forever. We need to have something on the new analytics collection for checking this cc @luizarakaki

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/37452, although this is alerts

**Comment by albertoperdomo** [comment]
@piranha We had another failure today, I updated the history in the issue description

**Comment by qnkhuat** [comment]
I checked with Alberto, and the issue seems to be resolved, also checked the history on stats, and all recent send-pulse tasks succeeded.

Probably fixed as part of https://github.com/metabase/metabase/issues/41764.
