### ISSUE TITLE
Prometheus Support

### ISSUE THREAD

**Issue by rrichardson** [metabase/metabase#3745]
### Database support
Searched, couldn't find any mention of prometheus in issues or PRs. 

### Feature requests and proposals
I would like to see Prometheus support in Metabase.  Prometheus has grown to be quite an important piece of infrastructure for both systems monitoring and business event monitoring. 

Even within the scope of systems monitoring it would be quite beneficial to have access to systems data to correlate business events with system events.  Revenue went up, was it a blip, or was there a corresponding increase in impressions / reqs/sec? etc. 

We use it for both business events and systems events, and it would be terribly helpful to augment our metabase data warehouse with prometheus' data.  Or just have great charts of prometheus realtime feeds. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Hi @rrichardson, we're adding support for various DBs based on community demand. Since you're the only person who's asked for this DB thus far, that might be a while 😉 

If you're familiar with Clojure and feeling adventurous you can try [writing a driver yourself](https://github.com/metabase/metabase/wiki/Writing-A-Driver). I'm available to help with any questions you might run into.

**Comment by rrichardson** [comment]
I was a bit surprised that a Prometheus proposal didn't exist yet.  I guess people are happy with Grafana as a front-end.  Its been a while since I've mucked with Clojure, I'll have a look at prevailing client libraries for Prometheus.

**Comment by ludwik** [comment]
Hello
Did anyone have a stab at this?

**Comment by leshik** [comment]
I'm also interested in Prometheus support.

**Comment by zexxar** [comment]
A Prometheus support would really be great

**Comment by shashanksingh** [comment]
Yeah, we would love one place to access all our metrics and relate them to transactional data. Upvoted.

**Comment by ZlobnyiSerg** [comment]
I'm in, idea is great - we'd like to combine our internal data gathered in metabase with external data, reported from external installations into prometheus.

**Comment by obitech** [comment]
+1 for Prometheus support

**Comment by alphavector** [comment]
I really look forward to the support of Prometheus. Perhaps someone started developing a driver? I am ready to help.

**Comment by dannyeuu** [comment]
@alphavector Great to hear that maybe @camsaul and @tlrobinson can help you to help us =) 

Single mortals like me that work with data but do not know Clojure =(

**Comment by wqtty** [comment]
how can I vote this request up? by all means

**Comment by paoliniluis** [comment]
Prometheus data could be visualized via TimescaleDB (Metabase connected to this postgres) by using the Promscale connector, just a thought

**Comment by autumnw** [comment]
Vote for this.

**Comment by SAMZONG** [comment]
+1 support Prometheus or  VictoriaMetrics and PromQL

**Comment by luizarakaki** [comment]
Closed with #25149

**Comment by merlindorin** [comment]
@luizarakaki plz reopen this issue. https://github.com/metabase/metabase/pull/25149 is unrelated (more exactly, it is about using metric from mb not consuming Prometheus metric from mb

**Comment by josebiro** [comment]
> Prometheus data could be visualized via TimescaleDB (Metabase connected to this postgres) by using the Promscale connector, just a thought

This is no longer possible as promscale has been deprecated. @luizarakaki As @merlindorin says, this issue should be reopened as it's a feature request for adding prometheus as a reporting data source, not a monitoring integration.

**Comment by mattheworiordan** [comment]
Agreed, this should be reopened. Prom as a data source would be valuable.
