### ISSUE TITLE
[MLv2] [BE] [Bug] Question filters are not being updated if there are breakout clauses for the same column

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#37463]
### Describe the bug

https://github.com/metabase/metabase/assets/14301985/e010624b-03e0-441d-abf8-13c52016d52e

### To Reproduce

1. New -> Orders -> Summarize by Total
2. Apply any filter by Total
3. Try changing the filter type like from "greater than" to "equals"
4. It has not been updated

### Information about your Metabase installation

```JSON
Latest master but did not check the release branch
```

### Severity

Significant inconvenience

**Comment by ranquild** [comment]
Seems to be a MLv2 bug. It gets confused because of the same column used in the breakout clause:

<img width="1006" alt="Screenshot 2024-01-09 at 18 44 36" src="https://github.com/metabase/metabase/assets/8542534/7b28542f-b591-443d-9cb8-409097a5e8b4">
