### ISSUE TITLE
Tables with a large number of columns can't be displayed as raw data

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3751]
When displaying a table with a large number of columns (201 in this case), I get an error

<img width="1438" alt="screen shot 2016-11-10 at 3 29 55 pm" src="https://cloud.githubusercontent.com/assets/107439/20198647/9047daa4-a75a-11e6-9b7b-47fcc4ce0803.png">

To replicate --  look at the `Raw Data` of the "Sales Flat Order" of the Magento sample database.

almost certainly related to #664

**Comment by tlrobinson** [comment]
I believe this is a duplicate of #3407.

**Comment by tlrobinson** [comment]
@salsakran I can reproduce this on v0.20.3 but not `master`. What version were you running when you ran into this?

**Comment by salsakran** [comment]
I'm on the below version
<img width="366" alt="screen shot 2016-11-15 at 10 47 46 pm" src="https://cloud.githubusercontent.com/assets/107439/20337370/90a7785e-ab85-11e6-9951-0cfdc52ac5f5.png">

**Comment by mattxbart** [comment]
This is a duplicate of #3687

**Comment by tlrobinson** [comment]
Confirmed this is resolved on master.

**Comment by salsakran** [comment]
confirmed that this is fixed in master.
