### ISSUE TITLE
[MLv2] [FE] [Bug] Cache expressionableColumns results

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37528]
Context https://metaboat.slack.com/archives/C04CYTEL9N2/p1704908756231269

We now call `expressionableColumns` on every keystroke (for suggestions) and for every token in the parsed query. Computing the list of columns is a slow operation and `expressionableColumns` should be called only once for the same query and results should be cached.

Same for available metrics and segments.

**Comment by uladzimirdev** [comment]
Both FE and BE fixes are merged, closing
