### ISSUE TITLE
Fix feature flag for `MB_UNAGGREGATED_QUERY_ROW_LIMIT` and `MB_AGGREGATED_QUERY_ROW_LIMIT`

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#37533]
**Context**
Stub task to decide the feature flag situation of these env vars.
We need to fix this before the next minor release

**Comment by perivamsi** [comment]
Does this have to be in 48.3? Can I remove the milestone for now?

**Comment by luizarakaki** [comment]
Yes, but it is fine, not work required.
