### ISSUE TITLE
Liquibase will sometimes hang while checking for unran migrations on windows

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3755]
Windows, running v0.20.3 as a jar. More info in http://discourse.metabase.com/t/could-not-fine-the-main-class-error/833/3

The issue is resolved when killing the jar and starting it again. 

This is going to be fun to re-pro.

**Comment by camsaul** [comment]
I've ran Metabase on Windows dozens of times and have never ran into this :/

**Comment by camsaul** [comment]
This is the same underlying issue as #1871 which I fixed in 0.24.0. Closing as duplicate
