### ISSUE TITLE
Serialization fails when line chart has click behavior linked to a field with base-type

### ISSUE THREAD

**Issue by piranha** [metabase/metabase#37555]
### Describe the bug

When you do what subject says, `click_behavior` key looks like this: `["field",7650,{"base-type":"type/Integer"}]`. This slash in `type/Integer` breaks serialization.

### To Reproduce

Add a line chart to a dashboard (i am using the Sample Database -> Invoices -> Count Group by created at month).
Then link it to another question, in my case a pivot.

### Information about your Metabase installation

```JSON
Metabase 1.47.10
```

### Severity

Preventing serialization

**Comment by iethree** [comment]
@metabase-bot backport release-x.47.x
