### ISSUE TITLE
Serialization fails with export: Unrecognized token 'Text' for click behaviour passing parameters to reports 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#37558]
### Describe the bug

Serialization fails with export: Unrecognized token 'Text' for click behaviour passing parameters to reports 

### To Reproduce

Opening this as reference

### Expected behavior

Able to export without errors

### Logs

Unrecognized token 'Text'

### Information about your Metabase installation

```JSON
1.47.10 and master
```

### Severity

broke serialization for some customers

**Comment by Tony-metabase** [comment]
Duplicate of https://github.com/metabase/metabase/issues/37555

**Comment by Tony-metabase** [comment]
We are hitting a different issue but this can be closed

**Comment by ignacio-mb** [comment]
Sorry, I meant to close as not planned.
