### ISSUE TITLE
Missing databasechangelog index for new instances

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#37552]
In https://github.com/metabase/metabase/pull/34400 we split the migration into 2 files, for new instances the migration should only go through everything in `migrations/001_update_migrations.yaml` in which it has a `v00.00-000` migration that contains a SQL file that used to contains all migration from before 45.

It was an oversight that the initialization sql doesn't include custom changes we made to databasechangelog table, because it's supposed to be managed by liquibase itself.

There is a "nice-to-have" index `idx_databasechangelog_id_author_filename` that we added in [migration id](https://github.com/metabase/metabase/blob/e66c0754cace99451ba1bdc85ef50335ca8dc584/resources/migrations/000_legacy_migrations.yaml#L5562C9-L5562C9) `95` a while ago. This index was not included in the new migration file so new instances won't have this index.

As described in the migration itself, it's nice to have this index and we should add it back. 

Couple of notes:
- we should add this index back and backport it to 48
- the migration need to check whether this index existed before in case old instances try to upgrade

**Comment by noahmoss** [comment]
We should also be careful adding this constraint back in case there are any instances that already have duplicate values in `databasechangelog` for these fields. We might need to delete some entries to ensure there's only one value per migration.
