### ISSUE TITLE
PULSE always shows table for a bar chart question 

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#3759]
- My browser: Chrome 54
- My Metabase OS: Linux
- Metabase version: 0.20.3
- My database server: Postgres
-------------------------------------------------------------------
I created a simple bar chart question like this:
    select 'A' "name", 1 count
    union 
    select 'B' "name", 2 count

but when put it into a pulse, I only see table (as attachment).
![screen shot 2016-11-15 at 2 34 25 pm](https://cloud.githubusercontent.com/assets/2088055/20297017/c6951920-ab40-11e6-86de-553edc556fd6.png)

I knows this problem is similar to #2937 but I can't find any matched condition from the given reference to show as a table like this. Please help. Thanks.

**Comment by salsakran** [comment]
In this situation we placed the bar graph on its side. The purple bars are relatively sized by "count".

This keeps things easily scannable, even in situations (eg a phone screen) where trying to keep the bar chart shape would make the x-axis illegible. While this changes the format of a given saved question, it is much more readable on a large variety of email clients.
