### ISSUE TITLE
[MLv2] [BE] Change `dropStageIfEmpty` into `dropEmptyStages`

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#37626]
See [Slack discussion](https://metaboat.slack.com/archives/C0645JP1W81/p1705049044385729).
Complementary FE task: #37627

----

FE needs to be able to drop intermediate empty query stages, but `dropStageIfEmpty` works only with the last stage.

Up until now, FE incorrectly assumed that `dropStage` and `dropStageIfEmpty` accept `stageIndex` argument, but in BE these functions actually always work only with the last stage.

This `dropStageIfEmpty` function should be changed, so that it drops all intermediate empty stages as well.
Once this happens, this function should be also renamed, to e.g. `dropEmptyStages`.

**Comment by metamben** [comment]
@kamilmielnik Should this function really remove all empty stages or just up to (and including) the one specified by `stageIndex`? If the former, then it shouldn't take `stageIndex` as parameter at all.
