### ISSUE TITLE
Enum type columns don't show up for update actions in MySQL

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#37638]
### Describe the bug

If you have a table with an Enum type in MySQL, basic actions will not show you the Enum columns to udpate  

### To Reproduce

1. Create a table with enum type in MySQL
2. Enable model actions for that database
3. Create a model based on that question
4. Go to model details > actions > Create basic actions
5. You will not see that Enum column, and neither in dashboard actions or record detail in the model table view

#### SQL for step 1

CREATE TABLE IF NOT EXISTS enum_test_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    color ENUM('Red', 'Green', 'Blue') NOT NULL
);

ALTER TABLE enum_test_table
ADD COLUMN email VARCHAR(255) NOT NULL;

INSERT INTO enum_test_table (color, email) VALUES
    ('Red', 'john@example.com'),
    ('Green', 'alice@example.com'),
    ('Blue', 'bob@example.com'),
    ('Green', 'charlie@example.com');
    
SELECT * FROM enum_test_table;

### Expected behavior

Enum column should be there?

### Information about your Metabase installation

```JSON
- Mysql 8.0.33
- Metabase version 48.3
```

### Severity

P2

### Additional context

Works for the other supported database for actions, Postgres

**Comment by qnkhuat** [comment]
Should be fixed by https://github.com/metabase/metabase/pull/43533?

**Comment by calherries** [comment]
closed by https://github.com/metabase/metabase/pull/43533
