### ISSUE TITLE
MB_UNAGGREGATED_QUERY_ROW_LIMIT is limiting in-product download queries

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#37642]
### Describe the bug

Changing MB_UNAGGREGATED_QUERY_ROW_LIMIT to 5000 limits download data to 5000 rows.

### To Reproduce

1. Set MB_UNAGGREGATED_QUERY_ROW_LIMIT=5000
2. Sample Database > Orders
3. Download results
4. Get 5000 rows, but 18k are expected

### Expected behavior

It should download up to 1M rows, limited only by permissions

### Information about your Metabase installation

```JSON
48.3
```

### Severity

P1

**Comment by luizarakaki** [comment]
We should check if `MB_AGGREGATED_QUERY_ROW_LIMIT` is affecting aggregated question downloads too

**Comment by abhishek-superk** [comment]
@paoliniluis Just wanted to know, would 0.48.4 be released once the linked PR is merged?

**Comment by paoliniluis** [comment]
@abhishek-superk we're still analyzing that, most probably yes
