### ISSUE TITLE
 0.48.3 : SQL Server dynamic ports

### ISSUE THREAD

**Issue by mdz0r** [metabase/metabase#37655]
### Describe the bug

We have a SQL Server using dynamic ports.
Since upgrade to 0.48.3, our sql server database connection fails. It tries to connect on port 1433 while the port parameter is not set (it should then use dynamic ports).
If I set the port on the actual dynamic port, connection is OK.

### To Reproduce

Set a sql server connection using dynamic ports (port field left empty)
Connection is refused.
In the logs, we can see that metabase tried to connect on 1433 port.

### Logs

Jan 12 18:03:31 metabase metabase: "Échec de la connexion TCP/IP à l'hôte SQL-SERVER-01, port 1433. Erreur : « Connexion refusée (Connection refused). Vérifiez les propriétés de connexion. Assurez-vous qu'une instance de SQL Server est en cours d'exécution sur l'hôte et accepte les connexions TCP/IP au port. Vérifiez que les connexions TCP au port ne sont pas bloquées par un pare-feu. »."}

### Information about your Metabase installation

```JSON
CentOS 7 / metabase 0.48.3 / mysql 8.0.35
```

### Severity

normal

**Comment by padey** [comment]
We have the same problem. If you change the port to the current dynamic port, it works again!
