### ISSUE TITLE
[MLv2] [BE] Migrate getColumnKey to MLv2

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37678]
Blocks https://github.com/metabase/metabase/issues/37687

https://github.com/metabase/metabase/blob/1efa6c6f000cb4bd38065563176c35ea0027c865/frontend/src/metabase-lib/queries/utils/get-column-key.ts#L13

This is the primary function for computing keys for viz settings. It should be fully ported to clojure, so the FE won't have to know so much details about field references format. I'd add this function to a new top-level file in `metabase-lib`, e.g. `visualizations` etc. to make it clear it's viz-specific.

Possible signature:
```
getVizColumnKey(column: DatasetColumn): string;
```

In context of viz `query` isn't available, so it would be great to make it work with the `column` only.

**Comment by metamben** [comment]
Marking this as blocked, because [we need a decision](https://metaboat.slack.com/archives/C04CYTEL9N2/p1706797196430759?thread_ts=1706737025.075029&cid=C04CYTEL9N2) if it this is really needed in the form proposed here. @ranquild might be able to say what exactly is needed.
