### ISSUE TITLE
Model search takes a long time (15 to 20 seconds)

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#37679]
### Describe the bug

The API https://stats.metabase.com/api/search?models=dataset takes a long time to load.

### To Reproduce

1. Go to stats
2. Open any dashboard and edit it
3. Click on "add action button"
4. Click on "pick an action"

Then the UI calls https://stats.metabase.com/api/search?models=dataset and that takes a long time to load.

### Information about your Metabase installation

```JSON
Stats
```

### Severity

P2

**Comment by qnkhuat** [comment]
the API call need to be paged, fetch all models is not gonna be fast.
