### ISSUE TITLE
[MLv2] [BE] Add `metric-id` and `segment-id` to `GET /api/card` to return only cards that use this segment/metric

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37688]
Blocks https://github.com/metabase/metabase/issues/37511
Blocks https://github.com/metabase/metabase/issues/37510

We need to show questions that use this segment or metric in data reference. Currently the FE loads all questions by calling `GET /api/card` and filters them out on the FE. 

<img width="1728" alt="Screenshot 2024-01-15 at 13 05 09" src="https://github.com/metabase/metabase/assets/8542534/355c1e11-5e77-4239-9bee-5ca80bc2b5b5">

With MLv2 we don't have a function to do that and it seems incorrect to load **all** cards in this case. To make it work in a proper way, let's add `metric-id` and `segment-id` parameters to `GET /api/card` that would return cards that are available to the current user that use this metric or segment. We would never pass both `metric-id` and `segment-id` at once, however it's possible that a card uses both metrics and segments at the same time.

**Comment by calherries** [comment]
As discussed on [slack](https://metaboat.slack.com/archives/C04CYTEL9N2/p1705322342635949?thread_ts=1705317783.553769&cid=C04CYTEL9N2), the QPD team should create an equivalent to `usesSegment` and `usesMetric`, and allow the `GET /api/card` handler to use it to get all the cards that use the segment or metric.
