### ISSUE TITLE
Summarization doesn't get removed when de-selecting it from chart settings

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#37734]
### Describe the bug

After summarizing with more than one metric and removing the metric from the chart setting, drill-down will still have the filter for one of the metrics and tooltip will show wrong information, while the graph doesn't show any reference to the metric

### To Reproduce

1. Create a GUI question from Orders, Summarize Count by Created At and Product category
2. 4 Lines show up in a line graph, that's cool
3. Now go to the chart settings and remove the Product category from the Series Breakout
4. Hover the line in the chart, see that a category is still applied (the values of the tooltip are not correct, it's summarized only by creation date), and if you drill-down, you'll see the category filter is applied to the graph

See that there is no reference to that category, but the graph still shows Doohickey in the tooltip, and when selected, "Doohickey" is applied as a filter
<img width="1492" alt="Screenshot 2024-01-16 at 9 44 09 AM" src="https://github.com/metabase/metabase/assets/132273646/8d342c11-bb12-4dd9-8dab-3d999697c0a7">

### Expected behavior

Maybe this is the expected behaviour, as there is a "Category" field in the summariation, but the grpah doesn't show any reference to that category, and the values are wrong

### Information about your Metabase installation

```json {
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.201-191.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "postgres",
      "redshift",
      "mysql",
      "bigquery-cloud-sdk",
      "mongo",
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-16",
      "tag": "vUNKNOWN",
      "hash": "f926e90"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

Can show misleading results

**Comment by alxnddr** [comment]
> 4\. it's summarized only by creation date

The query is still summarized by both Created at and Category columns and we don't change the query when the series breakout is being removed so the Category values are still in the dataset which is the reason we show them in the tooltip. Although in this situation it might be not entirely correct because for a given date there can be two rows with different categories but we show only one in the tooltip.

@cdeweyx what would be the correct behavior here?

**Comment by cdeweyx** [comment]
> > 4. it's summarized only by creation date
> 
> The query is still summarized by both Created at and Category columns and we don't change the query when the series breakout is being removed so the Category values are still in the dataset which is the reason we show them in the tooltip. Although in this situation it might be not entirely correct because for a given date there can be two rows with different categories but we show only one in the tooltip.
> 
> @cdeweyx what would be the correct behavior here?

@alxnddr I think the correct behavior is to not show Category. But more broadly how we handle unaggregated data tooltips is weird. If we were to [do this](https://www.notion.so/Default-don-t-show-unnecessary-columns-in-unaggregated-tooltips-0e538f6ea0a943a8a1f69545cee95ceb?d=76442b8bc0d94c0f92b41aae5c6e60d1&pvs=4#e75ac61d1a0b409e901fcd0d51b75f62) as described by Maz's comment, then this gets nicer in the process, right? Basically if unaggregated data, we only surface a few columns in the tooltip that are high signal, and others (in this case Category) are hidden behind "More" (dunno how we would handle the exact UX here though, we don't have the notion of clicking in tooltips today)
