### ISSUE TITLE
Add additional information regarding static embedding during setup

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#37740]
**Is your feature request related to a problem? Please describe.**
We currently have some limitation when it comes to static embedding like drill through and click behaviour don't work ... We get a number of customers complaining about this and they end up doing a lot of work thinking it will work but end up not working causing frustration and wasted time.

**Describe the solution you'd like**

If we could flag those somewhere during setup like here:

<img width="1122" alt="image" src="https://github.com/metabase/metabase/assets/110378427/9844e0e5-d711-4b94-aadc-1cc882db8afc">

or somewhere here:

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/4cfe9c2c-d606-4997-9dd1-2151bf4b2d78">

it will help people understand what they are enabling and what they will get.

**Comment by paoliniluis** [comment]
Note: click behavior will work if you send someone to an external site, but we should tell users that click behavior to another dashboard/question will not work

**Comment by albertoperdomo** [comment]
This should be improved soon when we release https://github.com/metabase/metabase/issues/35961. Not that it will feature a comparison matrix or a comprehensive list of limitations for each embedding feature, but it will expose the different options to embed (public, static, and interactive) and provide helpful links to learn more.
