### ISSUE TITLE
Having a combination of no self service and unrestricted on joined tables breaks filter modal

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#37753]
### Describe the bug

When you have a question consisting of 2 tables joined together one having `no self service` and another `unrestricted` will cause the filter modal to not show the columns you are aggregating with (which I think is fine since you don't have self service on that table but makes the experience odd)

### To Reproduce

1. Go to Admin -> People -> Add New Group -> Name it group_1
2. Go to Admin -> People -> Invite Someone -> Assign it to group_1  
3. Go to Admin -> Permissions -> Sample Database -> Set the All-Users to `no self service` -> Then set the People table to `no self service` and Orders table to `unrestricted`

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/ec7f54c7-2328-4cca-ae55-dfc6afca94f0">

4. Go to New -> Collection -> Test -> Give view permissions to group_1

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/9b34d8c7-a7f0-48df-bda1-d182249cb7c9">

5. Go New Question -> Sample Database -> Join Orders with Products -> Group by 2 columns from Orders and 2 columns from Products -> Save it in Test

<img width="1471" alt="image" src="https://github.com/metabase/metabase/assets/110378427/6faf8a38-4b19-4886-8472-1b7b628a594e">

6. Now login as the User you created which is assigned to group_1 -> Then open the above question and notice the resultant columns

<img width="1185" alt="image" src="https://github.com/metabase/metabase/assets/110378427/3918760f-4adb-4ede-8493-edd2a46d4b21">

7. You are not able to filter for any of those columns

<img width="1324" alt="image" src="https://github.com/metabase/metabase/assets/110378427/5345d285-4986-4ea3-b5d5-9450e62f52b4">

### Expected behavior

Filter consistent with the data you are showing

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.48.3 and master
```

### Severity

minor issue

**Comment by Tony-metabase** [comment]
Related to https://github.com/metabase/metabase/issues/37751

**Comment by ranquild** [comment]
Root cause - `editable?` MBQL lib check doesn't take joins into account. The fix is to make `editable?` return false if there are no data permissions to any of the joined tables or no collection permissions to any of joined cards. For MBQL lib  it means that the corresponding entry for `table` or `card` isn't available in metadata.

The fix would also cover https://github.com/metabase/metabase/issues/37751. Discussed in Slack https://metaboat.slack.com/archives/C0645JP1W81/p1719506040735199
