### ISSUE TITLE
Having a combination of no self service and unrestricted on joined tables causes permission error when filtering 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#37751]
### Describe the bug

When you have a question consisting of 2 tables joined together one having `no self service` and another `unrestricted` will not allow you to filter on the question

### To Reproduce

1. Go to Admin -> People -> Add New Group -> Name it group_1
2. Go to Admin -> People -> Invite Someone -> Assign it to group_1  
3. Go to Admin -> Permissions -> Sample Database -> Set the All-Users to `no self service` -> Then set the People table to `no self service` and Orders table to `unrestricted`

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/ec7f54c7-2328-4cca-ae55-dfc6afca94f0">

4. Go to New -> Collection -> Test -> Give view permissions to group_1

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/9b34d8c7-a7f0-48df-bda1-d182249cb7c9">

5. Go New Question -> Sample Database -> Join Orders with Products -> Group by 2 columns from Orders and 2 columns from Products -> Save it in Test

<img width="1471" alt="image" src="https://github.com/metabase/metabase/assets/110378427/6faf8a38-4b19-4886-8472-1b7b628a594e">

6. Now login as the User you created which is assigned to group_1 -> Then open the above question and proceed to filter via the table like so:

<img width="1205" alt="image" src="https://github.com/metabase/metabase/assets/110378427/02e7c6cf-6767-42e6-a9a2-a711b0a8da62">

7. Notice the permission error

<img width="1197" alt="image" src="https://github.com/metabase/metabase/assets/110378427/aa340150-62a9-4f83-bf8f-6191c2c5abcb">

### Expected behavior

Do not allow to filter on that column if I don't have permission to do so

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.48.3 and master
```

### Severity

Problematic since it breaks functionality. At least limit the filtering option

**Comment by Tony-metabase** [comment]
Related https://github.com/metabase/metabase/issues/37753

**Comment by ranquild** [comment]
Root cause - `editable?` MBQL lib check doesn't take joins into account. The fix is to make `editable?` return false if there are no data permissions to any of the joined tables or no collection permissions to any of joined cards. For MBQL lib  it means that the corresponding entry for `table` or `card` isn't available in metadata.

The fix would also cover https://github.com/metabase/metabase/issues/37753. Discussed in Slack https://metaboat.slack.com/archives/C0645JP1W81/p1719506040735199
