### ISSUE TITLE
Add more information about the errors in the frontend

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#37779]
**Is your feature request related to a problem? Please describe.**
Some times we need to debug errors in dashboards or questions in the frontend and it ends up that the error is generic.

E.g. "e.query is not a function" on a dashboard refers to a card that might not be well structured, but which card? a dashboard can have tons of cards

**Describe the solution you'd like**
Add more information about the entity that is failing on the frontend, e.g. which key and value is the one that the FE was not able to parse or run

**Describe alternatives you've considered**
None

**How important is this feature to you?**
This leads us to debug the errors faster

**Additional context**
NA

**Comment by perivamsi** [comment]
From @alxnddr 

> If we had a try-catch inside Dimension.field() that logged its metadata and query, it would probably provide sufficient information


Context: https://metaboat.slack.com/archives/C052ZBWRG3W/p1710437453241519?thread_ts=1705460762.737549&cid=C052ZBWRG3W
