### ISSUE TITLE
Some time filter options are not working on Druid

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#3781]
Hi all,

There are a few errors with time filter on Druid. Here are some that I found:

- Past year is not working 
- This [week, month, year] return current day

How to reproduce:
1. select a druid table 
2. add one of the filters mentioned above
3. look at the native query -> dates are wrong

**Comment by moumny** [comment]
I looked at the code a bit here are some observations

So for the first issue (past year) what happens is in the util.clj date-extract for :year outputs an integer instead of a string so date->iso-8601 obviously converts this assuming it received a timestamp. Here im not sure why :year is an extract and not a trunc. 
If there are good reasons for that we can  either modify date-extract to return string or (if thats not what we want for other reasons) to change druid query processor to do the conversion to string.

For the second issue, when the query get expanded the amount is set to 0 :day even if its this week this month or this year.
The query processor then trunc to 0 day.

I can make a PR if needed, and i suppose try to add some tests :)

**Comment by salsakran** [comment]
We'd love a PR (and tests ;)

**Comment by moumny** [comment]
@camsaul I have a small question looking at druid/query_processor.clj:62
`(u/date-trunc-or-extract unit (u/relative-date unit amount))`
I didnt manage to find a case when date-extract would be executed(same for the two line above). Would you agree that date-trunc-or-extract would always call date-trunc ?

**Comment by camsaul** [comment]
@moumny `date-trunc-or-extract` will call `date-extract` if the `unit` is something like `month-of-year` or `year`

**Comment by camsaul** [comment]
Fixed by #4261
