### ISSUE TITLE
[MLv2] [BE] `findMatchingColumn` does not find matching column

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#37851]
It causes `Adding a breakout should not affect graph.metrics` unit test to fail in #37693.
These 2 usages are giving wrong result: https://github.com/metabase/metabase/pull/37693/files#diff-fdff338c9e6c27877274c27c438055055f0f9395a0a37c3fd360e194f6d2e461R635-R644 for "Count" and "Sum of Price" columns (they're not found when they should).

### To reproduce 

1. `git checkout sync-settings-query`
2. run `Adding a breakout should not affect graph.metrics` unit test in `frontend/test/metabase/lib/dataset.unit.spec.js` suite

----

It's also possibly causing these e2e tests to fail:
- `e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js`
    - `should show error for multi-series questions (metabase#15152)`
    - `should not allow you to choose X-axis breakout`

**Comment by bshepherdson** [comment]
I'll take a look at this. Those matchers are a stack of heuristics and this may be a missing case.

**Comment by bshepherdson** [comment]
It's not actually that they're not found, but that they're being returned in the reverse order. Not sure what's causing that.

```
  ● metabase/util/dataset › syncColumnsAndSettings › Adding a breakout should not affect graph.metrics

    expect(received).toMatchObject(expected)

    - Expected  - 1
    + Received  + 1

      Array [
    -   "count",
        "sum",
    +   "count",
      ]

      86 |         .syncColumnsAndSettings(prevQuestion);
      87 |
    > 88 |       expect(newQuestion.setting("graph.metrics")).toMatchObject([
         |                                                    ^
      89 |         "count",
      90 |         "sum",
      91 |       ]);

      at Object.toMatchObject (frontend/test/metabase/lib/dataset.unit.spec.js:88:52)
```

**Comment by bshepherdson** [comment]
(Deleted my earlier, misleading comment.)

The trouble here is that aggregation refs in MLv2 use a randomized UUID which is only valid inside the same query. More broadly, the `find-matching-column` logic was only intended to match columns and refs that descend from the same query. This logic of trying to check for removed and added columns between the two queries is new behavior. It should work fine for things other than aggregations since those are based on field ID and name, or on the expression name.

**Comment by bshepherdson** [comment]
I'm working on adding a new fallback case that can match up aggregation refs by column name if necessary.
