### ISSUE TITLE
我不知道为什么要用clojure这种晦涩的语言去构建java项目，必然被时代淘汰

### ISSUE THREAD

**Issue by yangmingtao** [metabase/metabase#37850]
clojure真是晦涩难懂，代码语义化很差，很难去维护。不知道开发者为什么要选择这个语言去做jave项目，执行效率我没有看到有什么改变，开发过程艰难，维护成本高。还有有时候,我想直接将sql中的参数执行为sql语句的时候，直接将sql语句中的引号全部用斜线转义了，导致sql执行语法错误。还有用jwt加密没有什么好处，现在只要复制对应加密的内容，就可以可以显示明文，起不到任何加密效果。

**Comment by paoliniluis** [comment]
@yangmingtao English please 🙂
