### ISSUE TITLE
csp- it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by lzsforever** [metabase/metabase#37855]
### Describe the bug
I build.sh the unified code on ubuntu and mac respectively, then put it into ubuntu, use java -jar ./metabase.jar to start, and visit http://localhost:3000
The jar of mac build can access the front-end page normally, but the jar of ubuntu build displays a blank page.
![20240118204132](https://github.com/metabase/metabase/assets/66901910/2c7e906e-d609-4106-806b-e13dfdb93f32)
![20240118204222](https://github.com/metabase/metabase/assets/66901910/5b308639-aea2-4668-999d-c99a0f4b3e8f)

### Information about your Metabase installation

```JSON
Node.js v18.18.2.
yarn 1.22.19
jdk 1.22.19
```

### Severity

Greatly affects the progress of use

**Comment by paoliniluis** [comment]
why do you want to build the product instead of using a release artifact?

pretty sure this is a caching issue or a build with errors
