### ISSUE TITLE
Add minutes and seconds to time filters

### ISSUE THREAD

**Issue by kabadisha** [metabase/metabase#3785]
It would be really helpful to add granularity of minutes and seconds to filter options in the GUI for both questions and dashboards. Currently the smallest time division is hour.
Currently I have to convert to SQL to do this and I can't do it for filters on dashboards.

**Comment by mnzt** [comment]
Looking at `RelativeDatetimeUnit` [here](https://github.com/metabase/metabase/blob/ce38a6dffc84fd7d72a2ee5e24f6e8937a83aa45/frontend/src/metabase/meta/types/Query.js#L19), it looks like minute exists for the Relative Date Picker. However I've had no luck actually getting it to show.

**Comment by mazameli** [comment]
This has been possible in the query builder for a while now, but is still not possible in dashboard date filters. Closing this issue in favor of https://github.com/metabase/metabase/issues/6660, which is explicitly about dashboard filters.
