### ISSUE TITLE
Add support for filtering empty latitude and longitude values

### ISSUE THREAD

**Issue by kabadisha** [metabase/metabase#3786]
Currently for latitude and longitude fields, it is not possible to exclude null values via the GUI. You have to edit in SQL.

**Comment by bertvh** [comment]
This is still an issue.. +1.

We should be able to filter 'is empty' on lon/lat in the same way we can for categories.

**Comment by nosovk** [comment]
unfortunately iit's not always possible to make right selection in SQL :(

**Comment by flamber** [comment]
This was fixed by #12159 in 0.35.4
