### ISSUE TITLE
Copied migration from PostgreSQL is broking MySQL migrations.

### ISSUE THREAD

**Issue by emanueloliveira23** [metabase/metabase#37868]
### Describe the bug

I just tried to migrate from 0.47.x to 0.48.3 and the migration `migrations/001_update_migrations.yaml::v48.00-033::noahmoss:` is not running on a MySQL database because it's copied from PostgreSQL one using its syntax with CTE that isn't compatible with MySQL dialect.

### To Reproduce

1. Configure a metabase with a MySQL at version 0.47.12
2. Try to upgrade to 0.48.3
3. Migration failed!

### Expected behavior

Migration must run successfully 

### Logs

January 18, 2024 at 13:15 (UTC-3:00) | liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v48.00-033::noahmoss:

January 18, 2024 at 13:15 (UTC-3:00) | Reason: liquibase.exception.DatabaseException: (conn=177) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'agg_recipients as ( [Failed SQL: (1064) create or replace view v_subscriptions as

January 18, 2024 at 13:15 (UTC-3:00) | with agg_recipients as (

January 18, 2024 at 13:15 (UTC-3:00) | select

January 18, 2024 at 13:15 (UTC-3:00) | pulse_channel_id,

...

### Information about your Metabase installation

```JSON
- Metabase with MySQL
- Running on AWS
- Managed by pulumi
```

### Severity

CRITICAL

**Comment by noahmoss** [comment]
What version of MySQL are you using?

**Comment by paoliniluis** [comment]
Can you also provide us with more context?

**Comment by noahmoss** [comment]
I'm fairly certain you're on MySQL 5.7 which has been EOL'd and we no longer support as an application database starting with Metabase 48. If you upgrade to MySQL 8 it should work.

**Comment by emanueloliveira23** [comment]
Hi folks!

Yes, I'm using MySQL 5.7 version (sorry, I didn't notice this requirement).

I'll try it later.

It's worth mentioning that I wasn't able to revert to the previous version. I believe this happened because the migration was only partially applied, or the rollback didn't work properly.

**Comment by paoliniluis** [comment]
you need to restore a backup
