### ISSUE TITLE
Audit v2 dashboard error for some dashboards

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#37897]
### Describe the bug

Some dashboards fail to load

Dashboards that don't work:
- Person Overview
- Performance Overview

<img width="1150" alt="image" src="https://github.com/metabase/metabase/assets/6377293/c26b8e33-94c6-4d62-8c06-aee8ec6a9088">

Strangely, the others do. And if you reload the dashboard it works
<img width="1150" alt="image" src="https://github.com/metabase/metabase/assets/6377293/19bf5ed9-2cf2-4573-8991-e0f67303e925">

### To Reproduce

Go to audit and click on all of the dashboards. Two will show an error, the others load fine. The two that error can be refreshed and then work.

### Logs

```javascript
Uncaught (in promise) TypeError: _selectors__WEBPACK_IMPORTED_MODULE_13__.getDashboardComplete(...) is null
    fetchDashboardCardMetadata data-fetching.js:550
    Redux 3
    componentDidUpdate Dashboard.jsx:71
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 6
```

and 

```javascript

TypeError: this.datasetQuery() is undefined
    query Question.ts:1060
    databaseId Question.ts:842
    database Question.ts:836
    createVirtualTableUsingQuestionMetadata nested-card-query-table.ts:68
    getNestedCardTable nested-card-query-table.ts:29
    getStructuredQueryTable structured-query-table.ts:26
    ts StructuredQuery.ts:271
    before Underscore
    _findMatchingQueryField Dimension.ts:797
    field Dimension.ts:824
    getParameterTargetField targets.ts:35
    getTargetFieldFromCard targets.ts:63
    mappedFields dashboards.ts:143
    buildFieldFilterUiParameter dashboards.ts:140
    uiParameters dashboards.ts:121
    getDashboardUiParameters dashboards.ts:119
    fetchDashboard data-fetching.js:268
    Redux 9
    loadDashboard Dashboard.jsx:105
    componentDidMount Dashboard.jsx:56
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
```

### Information about your Metabase installation

```JSON
latest master locally and stats
```

### Severity

p

**Comment by iethree** [comment]
I'm seeing errors with some parameters?
![Screen Shot 2024-01-18 at 3 31 58 PM](https://github.com/metabase/metabase/assets/30528226/e553b239-f3cb-4c6f-8563-de042c4be013)

**Comment by luizarakaki** [comment]
Unable to repro on 49.1
