### ISSUE TITLE
Text filters shown as input box in embed instead as dropdown

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#37914]
### Describe the bug

Decided to open this issue after spending some time reproducing #31347 and noticing the behavior has changed a lot.
Essentially, you expect filters to look the same in the embed, in the embed preview and in the dashboard inside of Metabase.

Findings:
* filter set as dropdown in dashboard, no default value for filter in dashboard, editable in embed -> filter is rendered as input box in embed 
* filter set as dropdown in dashboard, default value set for filter in dashboard, locked in embed -> filter is rendered as input box in embed
* filter set as droddown in dashboard, default value set for filter in dashboard, editable in embed -> filter is rendered as dropdown in embed as it should, but it's rendered differently in the preview

The preview features and linking of the filters seems to work properly, unlike reported in #31347.

### To Reproduce

1. Go to New -> Question -> Products -> Save
2. Create New Dashboard -> Add 3 Filters and Add the above question then link them to column Category
<img width="1500" alt="image" src="https://github.com/metabase/metabase/assets/24216/b0f4195e-dd0f-4e57-b466-1c7cb8b78f24">
3. Link the first filter to the second one -> Save
<img width="1481" alt="image" src="https://github.com/metabase/metabase/assets/24216/85c6cc08-602d-4dcf-9146-a30a296de60c">
4. Confirm that the link is working by selecting Doohickey for Second Filter and Gadget,Gizmo for Third filter ... Notice that on metabase works as expected and First filter only shows Doohickey as an option
<img width="1195" alt="image" src="https://github.com/metabase/metabase/assets/24216/fdb2d8fa-b84a-4d27-af46-f706851a766b">
5. Go to Sharing -> Embed your application -> Make the filters editable -> Publish
6. The filters are rendered in the embed and preview as input boxes instead of as dropdown
<img width="887" alt="image" src="https://github.com/metabase/metabase/assets/24216/22e24079-b70b-47cc-acf3-4e0ed0a023a1">

7. Edit the dashboard, set the default value for text 1 as Doohickey -> Save

8. Go to Sharing -> Embed your application -> Preview

9. In the preview Text filter is still rendered as input box but text 1 is rendered as multi-select, in the embed it is a proper dropdown

Text:
<img width="766" alt="image" src="https://github.com/metabase/metabase/assets/24216/ffbe270c-5854-4e3b-8711-e9de069c774a">

Text 1 in preview inside of UI:
<img width="705" alt="image" src="https://github.com/metabase/metabase/assets/24216/5b7d2d5f-b8b8-41fb-a1cf-49512579084d">

Text 1 opening iframe from preview URL  in incognito mode:
<img width="1456" alt="image" src="https://github.com/metabase/metabase/assets/24216/7b8fa28b-247c-45b0-89c8-e81db744e246">

10. Copy the iframe URL from the preview using inspect and open it in incognito mode. You will see that text and text1 are now rendered as dropdown and also that the linking of the filters is working as expected. Text2 is still rendered as input box.

11. Set text1 to locked, set a preview value for it as "Doohickey", publish, copy the iframe URL from the preview using inspect, open it in incognito mode. The results are properly filtered (Doohickey only), but text filter shows again as input box even though there is a default value
  

### Expected behavior

The filters should look the same across dashboard in MB, embed preview and real life embed. The combination of setting a default value in the dashboard and setting the filter as editable triggers this consistent behavior but it should not be needed

### Information about your Metabase installation

```JSON
Metabase v1.48.1
```

### Severity

Might be blocking in certain use cases

**Comment by albertoperdomo** [comment]
Setting a default value for both filters and embedding triggers the correct behavior and rendering on the embed:

![image (12)](https://github.com/metabase/metabase/assets/24216/6b86d5b7-b4f7-44ac-9c0d-68fb6ea70056)

**Comment by Tony-metabase** [comment]
There was already some research on linked filters by @WiNloSt which is good to have it here for reference:

https://github.com/metabase/metabase/issues/31347#issuecomment-1833609517

**Comment by WiNloSt** [comment]
@albertoperdomo I might found 2 issues in this single issue.
1. The preview embed on Metabase instance and the preview embed when viewing it directly (copy the iframe URL to a new tab) will result in parameters behaving differently because the embed preview will call an unexistent API. This should be solved in this PR https://github.com/metabase/metabase/pull/37972
2. When we set a parameter to locked, all other filters that map to the same locked parameter won't be working in embedding anymore. I think this might be a BE issue, so I'd need some BE engineer aid here.

    in embedding, when calling the dashboard endpoint when all parameters are set to **editable** we'll get `param_fields` (1) in the response which makes FE show the dropdown. But when we set any of the parameters to **locked**, we'll not get any value in `param_fields` (2)
    1. ![image](https://github.com/metabase/metabase/assets/1937582/bb854c0d-d304-4c6c-a7c5-c2b73a1a9c9d)
    2. ![image](https://github.com/metabase/metabase/assets/1937582/a7e9cc8b-0e7e-4e75-8e6d-d32a931e7c06)

**Comment by Tony-metabase** [comment]
I am reopening this one since I am testing to make sure the embedding behaves the same as metabase and I am getting a text filter everywhere so I cannot even test if linked filters are working as expected on embedding (i.e. similar to the metabase dashboard)
