### ISSUE TITLE
Date format in reports

### ISSUE THREAD

**Issue by maliayas** [metabase/metabase#3791]
Do you have any plan to add a setting for how to display dates? As far as I see, currently only English localized dates are supported. Sometimes, other formats may be needed such as `2016-11-21 11:33:23`. IMHO, there should be a system wide setting in the admin panel and a user-wide setting under Account Settings which overrides the system setting.

Thanks in advance.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by LukeAbell** [comment]
+1

**Comment by cyberhorse** [comment]
Also dates sometimes need to be overwritten for a particular report. If there is a date formatting function (date, yeardate, week, etc), there probably shouldn't be more logic added by metabase to override that with a set format.

**Comment by YoungHu** [comment]
OR where can i change the date format in metabase project source code?

**Comment by tanzoniteblack** [comment]
I agree with @cyberhorse , it would be useful if we were able to format date/timestamps as a feature in the query builder.

Ran across a specific use case today, where I'm storing a timestamp with timezone in postgres, and need it that way for several data points, but our billing department only wants one of the final reports to have the date, not the timestamp. It's easy enough in a raw SQL question to cast a datetime to a date, or apply a specific string format, but there doesn't seem to be a way to do this through the query builder.

**Comment by joermungandr** [comment]
I would also like to have this feature :-) Or is it possible to change the date format now? I tried to use sql's date_format command, but metabase's query editor says, that this function is not existent ... any suggestions?

**Comment by peterjlu** [comment]
If you're trying to export the data somewhere else (e.g. to Excel), and you want to format the date/timestamp so that it doesn't show that ugly "2017-04-28T00:00:00.000-07:00" format by default, you can turn it from a time (which Metabase seems to always display like above), into plain text. Now you'll be able to export truncated dates without seeing that extra long string of zeros at the end. Just do:

to_char([timestamp],'YYYY-MM-DD')

**Comment by mazameli** [comment]
Implemented via https://github.com/metabase/metabase/pull/8479 and https://github.com/metabase/metabase/pull/8620
