### ISSUE TITLE
Filtering Dashboard - Limited number of values ?

### ISSUE THREAD

**Issue by flotrek** [metabase/metabase#3792]
Hello,
I am trying to filter a Dashboard by a field that has 100+ values.
The field is not showing up in the Filtering option.
Is there anything I can do to user this field as a possible filter for my users ?

Thank you,m
Florian

**Comment by camsaul** [comment]
@flotrek do you mean you cannot filter the field at all? 

Also could you please fill out the bug questionnaire so we can get a little more info so we can diagnose this issue?

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

**Comment by camsaul** [comment]
This sounds like the same things that were being described in #5680. Over the past year since this issue opened we completely reworked how FieldValues are cached and resolved this issue and many more, so I'm going to go ahead and close this as already fixed.
