### ISSUE TITLE
Pemissions just don't work

### ISSUE THREAD

**Issue by cagiraudo** [metabase/metabase#3793]
Hi,

I am having probelms with restricting permissions to group. It just doesn't work.

I made a group called "Invitados" and added a user to that group
![image](https://cloud.githubusercontent.com/assets/19225821/20488227/0187a9b4-afe5-11e6-9f3d-10bf47edd46d.png)

I blocked all permissions to that group (view or make question to all my tables)
![image](https://cloud.githubusercontent.com/assets/19225821/20488261/241e1472-afe5-11e6-8b52-556e663f9303.png)

But when i log with that client i can see the doesboards and make questions of all my AA3 database without a problem.
![image](https://cloud.githubusercontent.com/assets/19225821/20488313/524570de-afe5-11e6-884c-6601314a7a3a.png)
![image](https://cloud.githubusercontent.com/assets/19225821/20488347/677a12c0-afe5-11e6-892c-f4ddce2633ff.png)

- Your browser and the version: Chrome 49
- Your operating system: Ubuntu 16.04
- Your databases: MySQL
- Metabase version: 0.20.0
- Metabase hosting environment: Ubuntu Server 14.04
- Metabase internal database: MySQL

**Comment by cagiraudo** [comment]
I updated to v0.20.3 and still doesn't work

**Comment by tlrobinson** [comment]
@cagiraudo You need to revoke the permissions for the "All Users" group. We have a ticket open for making this more clear here #3552.

**Comment by cagiraudo** [comment]
Ok, i feel stupid now.

I changed that and now it's working fine

In my defense i agree with your issue #3552 that it can be more clearly
