### ISSUE TITLE
Groups not loading correctly in list

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3794]
On our stats instance, I'm not seeing any of the groups that I've added, and new groups I add don't persist when returning to the groups list page.

I'm seeing the following JS console error:
`
Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZl…07Cgl9OwoJZ2EucmVtb3ZlID0gbm9vcGZuOwoJd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com js.intercomcdn.com *.intercom.io ".
`

There don't appear to be any errors in the server logs.

It does appear that Metabase thinks those groups exist, though, because trying to add one again results a modal error telling you that a group with that name already exists.

![screen shot 2016-11-21 at 10 00 17 am](https://cloud.githubusercontent.com/assets/2223916/20494572/656c25d0-afd2-11e6-992b-1b1f3f7e0e7a.png)

**Comment by camsaul** [comment]
@mazameli how are you running Metabase? This looks like an issue with the Content Security Policy headers which I've only seen when something weird happens

**Comment by mazameli** [comment]
This was on stats.mb. I also tried building master and running locally and saw the same behavior, though I didn't check the console errors.

**Comment by mazameli** [comment]
Checked again and can confirm I see the same JS console error when building from master and running locally:

`Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZl…07Cgl9OwoJZ2EucmVtb3ZlID0gbm9vcGZuOwoJd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com js.intercomcdn.com *.intercom.io localhost:8080".`

**Comment by mazameli** [comment]
@metabase/core-developers any thoughts/news on this one? Feels like a show-stopper to me.

**Comment by salsakran** [comment]
yeeeah. this is a problem

**Comment by ploddi** [comment]
Groups with 0 users not showing up. You can manually fix this by adding records to permissions_group_membership table for missing groups.

**Comment by mazameli** [comment]
I would love to see this fixed in 0.21. @tlrobinson or @camsaul, have you guys had a chance to look into this one?

**Comment by camsaul** [comment]
I'll take a look at this
