### ISSUE TITLE
Archiving a question basically does nothing

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3800]
Currently, if you archive a question that's being used in a dashboard or Pulse, there's no indication on the card that the question is archived. Same thing if you go to the question detail page; there's no way to know that the question is archived. This feels super wonky. Not sure if that was the original design intent, but it seems to me like the behavior should be: 

- Archiving a question removes it from all dashboards/Pulses it appears in (with a warning and notification email to the dashboard/pulse owner)
- OR, archiving a question adds some kind of visual indicator to every card where it's used, calling out the fact it's archived
- and, the question detail should have a badge/label next to its name that says `Archived`

**Comment by camsaul** [comment]
This was partially fixed by #4075

**Comment by flamber** [comment]
Closing, this was fixed long ago. When archiving a question, the dashboard cards gets removed and the question will only be available in the collection Archive.
