### ISSUE TITLE
Schemas with backslashes in Postgres don't get synced

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#38000]
### Describe the bug

Schemas with backslashes in Postgres don't get synced. Might affect other DBs too but I've only tested on Postgres.

### To Reproduce

1. Connect a Postgres database to Metabase
2. Create a new schema in the DB that contains an (escaped) backslash, e.g. `CREATE SCHEMA "schema_with\\backslash";`
3. Create a couple tables in the schema
4. Sync the database
5. The sync will succeed, but neither the schema nor any of its tables will have been synced

### Information about your Metabase installation

```JSON
Current master
```

### Severity

P2?

**Comment by paoliniluis** [comment]
Is this a regression @noahmoss ?

**Comment by noahmoss** [comment]
@paoliniluis Perhaps, but I don't know what version this worked on

**Comment by noahmoss** [comment]
Tested on 45 and it still had this issue so it's not a recent regression, at least
