### ISSUE TITLE
[Epic] Rework cache setup and management

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38016]
**Links**
- product doc: [_link to product doc_](https://www.notion.so/metabase/Rework-cache-setup-and-management-db37ccc280db4da484c15770bd18f0bd)

FE-only project. The BE part will be done by BEC team

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by dpsutton** [comment]
closing in favor of https://github.com/metabase/metabase/issues/39153

**Comment by rafpaf** [comment]
We're using this one now: https://github.com/metabase/metabase/issues/39163
