### ISSUE TITLE
Dashboard Time Filters Don't Work for Cards with SQL Date Variables

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#38012]
### Describe the bug

Time filters on dashboards do not work for SQL questions with variables set up as Date Filter widget types.

### To Reproduce

In V48, if you:

- Create a SQL question with a variable that's a "Field Filter" variable type and a "Date Filter" widget type
- Save it to a Dashboard
- Add any "Time" filter type to the dashboard and link it to the Dashboard card
-
The time filters from the dashboard will not filter the results of the card

### Expected behavior

The dashboard date filters should work

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "mongo",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-19",
      "tag": "v0.48.1",
      "hash": "a8302d4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking Users

### Additional context

Illustrated this working in V47, then failing to function in v48:

https://www.loom.com/share/2e49a98641644d8c91706d5caa7a171f

**Comment by bshepherdson** [comment]
I'm struggling to reproduce this. Do these steps seem sound?

- Start a fresh instance of 0.48.3.
- Log in
- Browse data, Orders, Save, Create dashboard.
- Reopen that question, view its SQL, copy it.
- New -> SQL Question -> Paste
- Add `WHERE {{CreatedAt}}` filter
- Configure that filter with `Field Filter`, select `Orders -> CREATED_AT` column, select `Date Filter` type.
![2024-01-22-165228_664x1575_scrot](https://github.com/metabase/metabase/assets/157812/2af151cf-9417-4273-8567-32c9f20ffab8)
- Save that question too and add it the dashboard.
- Edit that dashboard, add a filter, select `Orders -> CREATED_AT` on the MBQL question.
- It auto-selects `CreatedAt` field filter on the SQL query.
- Select `All of the above` filter style.
    ![2024-01-22-165914_2508x1072_scrot](https://github.com/metabase/metabase/assets/157812/35d5ec12-524f-4d09-a5cf-cc6aa2369a5f)
- It works fine?

So there may be something more subtle going on here that I'm not doing with my repro.

**Comment by bshepherdson** [comment]
This issue is mis-stated.

The real problem is that if multiple dashboard filters are aimed at the same SQL variable, the SQL question will respect either none of them or all of them.

I can reproduce this using the setup I described above, but adding both a Relative Date and Month/Year filter to the dashboard. If I select "Last Year", the MBQL question reacts correctly but the SQL one is still showing everything. If I filter further by setting the Month/Year to December 2023, **both** questions show the same small set of orders.

If I unset the "last year" relative filter, the MBQL question continues to show just Dec 2023 while the SQL question goes back to everything.

I'm still investigating the causes of the issue.

**Comment by bshepherdson** [comment]
I've narrowed down the cause. In 47 when only one of the dashboard parameters has a value, the FE sends the request (`/api/dashboard/1/dashcard/2/card/3/query`) with only the populated parameters. Those with no value set are not mentioned at all.

In 48, all(?) the dashboard parameters are included in the request. The BE logic for matching parameters in native queries doesn't know what to do with that case (a parameter with neither a value nor a default). It fails to determine the value(s) for the field filter, and so it gets replaced with `WHERE 1 = 1`. That fully explains the behavior we're seeing.

I'm going to tweak the BE logic to do the right thing in this case, and then it won't matter what the FE sends.

Just to spell it out, I think the right flow here is:

- Given a field filter tag and all the input parameters,
- Filter to just those parameters which are for this tag,
- Find each tag's value as `:value` if set, then that parameter's `:default` if set, and finally `nil`.
- Filter out any `nil`s from that list of values.
- If the list is now empty, use the `:default` value for the template tag (not any parameter).
- If the tag has no default, return `no-value` and let the filter be `1 = 1`.
