### ISSUE TITLE
Cannot update cell value to null via model actions

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#38033]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6830683/536f8e58-aabc-4824-94c7-7755a61a9018)

### To Reproduce

1. Enable actions in the sample database
2. Create and save a model based on the orders table
3. Enable basic actions for the model
4. View model data as table
5. Click value in the ID column for any of the rows - it will open up object details modal
6. Edit the object ("..." -> "Update")
7. Clear the Product ID input field
8. Hit "Update" button

Entity does not get updated

### Expected behavior

Entity is updated and has nil Product ID

### Information about your Metabase installation

v48, master, fb696adfc8

### Severity

P2

### Additional context

Frontend sends POST `/api/action/:id/execute` with this payload:
```
{"parameters":{"created_at":"2024-09-11T11:22:26","product_id":null,"id":7}}
```

which looks correct, so I'm assigning "backend" label.

**Comment by luizarakaki** [comment]
Maybe I'm missing something here, but:

If the user leaves the param empty, it is because they don't want to update that field. The optionality there means that they don't need to change what is already there. So I'm not sure if we want to replace with null

**Comment by kamilmielnik** [comment]
> If the user leaves the param empty, it is because they don't want to update that field.

True, that's how it works.

But it's not obvious from UX perspective - as a user I expected to be able to remove an existing value by clearing an input value.

**Comment by cdeweyx** [comment]
So if "Product ID" was previously 5, and someone clears out that field, then hits "Update" then my expectation is in line with Kamil, we would update to null.

> If the user leaves the param empty, it is because they don't want to update that field. The optionality there means that they don't need to change what is already there.
Couple of clarifying thoughts: We pre-fill the existing values in the update modal, so if the input is empty already, it's because it was empty previously. Indication that someone "wants to update" a field is determined by if it's changed from the previous state. Lastly, "optionality" refers to if that field is required or not to submit the form, not necessarily if it needs to be altered or not.

**Comment by zdytch** [comment]
> Maybe I'm missing something here, but:
> 
> If the user leaves the param empty, it is because they don't want to update that field. The optionality there means that they don't need to change what is already there. So I'm not sure if we want to replace with null

The concept is understood, but we should consider implementing a method to handle NULL values intentionally. Perhaps we need a specific placeholder that clearly indicates when a NULL value should be preserved in the system rather than being discarded.
