### ISSUE TITLE
Cannot "filter by this column" 

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#38034]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6830683/94c523bf-0099-4895-ad4d-a9e41fa360ce)

### To Reproduce

1. Create a model [like this](https://github.com/metabase/metabase/assets/6830683/353361f3-72d2-490b-80c8-dc4029c20c60)
2. Visualize it as a table
3. Click the "Reviews -> ID" column header
4. Click "Filter by this column"

Nothing happens

### Expected behavior

Filter dropdown is shown

### Information about your Metabase installation

master, fb696adfc8

### Severity

P2

### Additional context

`Lib.availableDrillThrus` returns a drill with `null` column in [`query-drill.ts`](https://github.com/metabase/metabase/blob/06400bc/frontend/src/metabase/querying/utils/drills/query-drill.ts#L12)

**Comment by bshepherdson** [comment]
Huh, I can reproduce this. The "filter by this column" drill works fine ad hoc and as a saved question, but does not appear when the question gets saved as a model. There's no error message to point at the issue, but I'm investigating.
