### ISSUE TITLE
BUG: Pin map background is grey

### ISSUE THREAD

**Issue by kait-stearns** [metabase/metabase#38048]
### Describe the bug

The background for all of the pin maps I have created (spanning multiple dashboards) is now grey. Previously there was a map. Pins are still showing up.

<img width="1553" alt="Screen Shot 2024-01-23 at 11 30 22 AM" src="https://github.com/metabase/metabase/assets/82038092/08711774-890f-4c42-8382-509cbd7c36b4">

### To Reproduce

1. Pull some data with valid latitude and longitudes
2. Create a map visualization 
3. Select pin map and specify lat/long fields 

### Expected behavior

Expect a world/area map to be in the background 

### Logs

Console logs:
```
analytics.js:24 Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=G-29NY6M1W10&cx=c&_slc=1' because it violates the following Content Security Policy directive: "script-src 'self' https://maps.google.com https://accounts.google.com https://www.google-analytics.com   'sha256-9uFLu5CG8mWlvx0LK6lgendCxUX57TuWk3wkgZpBeWU=' 'sha256-ib2/2v5zC6gGM6Ety7iYgBUvpy/caRX9xV/pzzV7hf0=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.205-195.804.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-11",
      "tag": "v1.48.3",
      "hash": "80d8323"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

**Comment by paoliniluis** [comment]
Can you open the browser dev tools and send us the logs in the network tab? also the console contents

**Comment by kait-stearns** [comment]
@paoliniluis 
Console contents: 
Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=G-29NY6M1W10&cx=c&_slc=1' because it violates the following Content Security Policy directive: "script-src 'self' https://maps.google.com https://accounts.google.com https://www.google-analytics.com   'sha256-9uFLu5CG8mWlvx0LK6lgendCxUX57TuWk3wkgZpBeWU=' 'sha256-ib2/2v5zC6gGM6Ety7iYgBUvpy/caRX9xV/pzzV7hf0=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
Id @ analytics.js:24

screenshot of the Network tab (sorry if this isn't what you're asking for!)
![Screen Shot 2024-01-23 at 12 39 23 PM](https://github.com/metabase/metabase/assets/82038092/edb33bb1-16de-409f-aba6-6989a361a0a8)

**Comment by paoliniluis** [comment]
I think that the GeoJSON there doesn’t exist anymore. Look at the first http call, it returns something with a size of 0

**Comment by kait-stearns** [comment]
Got it. Is this something I can fix or does this have to be an internal Metabase fix?

**Comment by paoliniluis** [comment]
@kait-stearns check if the geojson still exists in the instance

**Comment by kait-stearns** [comment]
@paoliniluis I'm not sure where to check this, in the maps section of the admin screen it mentions "Metabase uses OpenStreetMaps by default", but I can't tell where exactly it pulls geojson from 
<img width="1025" alt="Screen Shot 2024-01-29 at 10 05 29 AM" src="https://github.com/metabase/metabase/assets/82038092/c5f7cd01-1ff2-486d-8c2d-e0fb48dbaca2">

**Comment by kait-stearns** [comment]
Not sure what changed, but the map issue is now fixed!
