### ISSUE TITLE
CSV-uploaded data does not show up in Admin -> Table Metadata without refreshing the page

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#38041]
### Describe the bug

CSV-uploaded data does not show up in Admin -> Table Metadata without refreshing the page

### To Reproduce

1. Open up Reviews table in Sample Database
2. Download it as CSV
3. Enable CSV uploads in Sample Database
4. Go to Collections
5. Upload CSV downloaded in step 2
6. Browse the uploaded data
7. Go to Admin -> Table Metadata

Uploaded CSV is not there. You need to refresh the page to see it

### Expected behavior

Uploaded CSV data should be visible without reloading the page

### Information about your Metabase installation

v48, master, fb696ad

### Severity

P2

**Comment by npfitz** [comment]
@kamilmielnik I tried reproducing this this afternoon and it appears to be working for me. Do you mind re-testing this? I suspect we may be able to close this out

**Comment by kamilmielnik** [comment]
I confirm I cannot reproduce it in `master` at 2f0bc49783.
It's reproducible in 0.48.0.
@npfitz please don't close it without a repro :pray:
