### ISSUE TITLE
* in from clause causes syntax error

### ISSUE THREAD

**Issue by olafbuitelaar** [metabase/metabase#38051]
### Describe the bug

when i try to create a question for ClickHouse, with a from function containing * with a variable, metabase seems to produce a syntax error.

### To Reproduce

create a question with query and variable XXX
select 
columnA, 
sum(arrayCount(x -> x == 'abc',`Events.Name`)) as eventAbc
from s3('https://s3.url.location/x/*/*/*/*/*.parquet','admin','default') as data_source
where XXX={{XXX}}
group by columnA

### Expected behavior

the * in the function parameter (string) not causing syntax errors

### Information about your Metabase installation

```JSON
- Metabase Version: v0.48.3
- Hosted on K8s
```

### Severity

between annoying and blocking some users (including me)

**Comment by paoliniluis** [comment]
Hi, I think you need to post this to the clickhouse team in their Metabase driver repo

**Comment by paoliniluis** [comment]
seems it's our fault

**Comment by snoe** [comment]
Important comment from the linked issue https://github.com/ClickHouse/metabase-clickhouse-driver/issues/220#issuecomment-1919582340

> 
> > Similar behavior with MySQL, i.e., confirmed Metabase bug.
> 
> SELECT concat('/*/') 
> WHERE 1=1 [[AND '42' = {{x}}]]
> LIMIT 10
