### ISSUE TITLE
Multiple Dockerfiles

### ISSUE THREAD

**Issue by mccricardo** [metabase/metabase#3805]
We recently felt the need to pass some arguments do the JVM running `metabase` and found that the [container](https://hub.docker.com/r/metabase/metabase/) we were using did not allow it. Going through the repository we found 3 Docker files:
 - https://github.com/metabase/metabase/blob/master/bin/docker/Dockerfile - the one on the Docker Hub
 - https://github.com/metabase/metabase/blob/master/deploy/aws-eb-docker/Dockerfile
 - https://github.com/metabase/metabase/blob/master/Dockerfile

Why are there 3 Dockerfiles and why is it not allowed to tweak JAVA_OPTS in the official image?

**Comment by ihackalot** [comment]
You should either refer to https://hub.docker.com/r/metabase/metabase/, build your own snapshot or use one the various releases available. Of course you can pass you own environment variables, [checkout the documentation for that](http://www.metabase.com/docs/v0.20.3/operations-guide/running-metabase-on-docker.html), or make your own Dockerfile starting from the official one.

**Comment by mccricardo** [comment]
By using `metabase/metabase:v0.20.3` the script running metabase is [this one](https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh) which ignores any `JAVA_OPTS` passed as an environment variable. `JAVA_OPTS` is hardcoded in the [script](https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh#L29).

We used [this](https://github.com/metabase/metabase/blob/master/Dockerfile) Dockerfile which uses [this](https://github.com/metabase/metabase/blob/master/bin/start) script to run metabase and allows `JAVA_OPTS` to be passed as an [environment variable](https://github.com/metabase/metabase/blob/master/bin/start#L85)., allowing us pass, for example `Xms` and `Xmx`. 

Should the official image also allow this?

**Comment by ihackalot** [comment]
`docker run -d -p 3000:3000 --name metabase -e JAVA_OPTS='-Xmx3g -Xms3g' metabase/metabase`?

**Comment by mccricardo** [comment]
`docker run -d -p 3000:3000 --name metabase -e JAVA_OPTS='-Xmx265m -Xms256m' metabase/metabase:v0.20.3`

And the running process:

`java -Dlogfile.path=target/log -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -server -jar /app/metabase.jar`

It's easily fixable. I can do a PR to that shell script if you want.

**Comment by hgwood** [comment]
I've run into this issue too. I would like to pass proxy options to the JVM but can't due to the start script overriding `JAVA_OPTS` completely [here](https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh#L29).
