### ISSUE TITLE
Sync and scan pegs the CPU to 100%

### ISSUE THREAD

**Issue by DavidDudson** [metabase/metabase#38072]
### Describe the bug

We upgraded from: 
v0.47.9 to v0.48.2

Previously we were happily running on a single core ECS instance. However now it is really struggling and we have to upgrade our ECS instance sizes.

Do you have any idea what might have caused this? And whether the new load is expected moving forward?

![image](https://github.com/metabase/metabase/assets/2680733/ba1c426f-67be-4247-9ab8-bb9f245aaeeb)

<img width="2176" alt="Screenshot 2024-01-24 at 10 21 26 am" src="https://github.com/metabase/metabase/assets/2680733/64862f75-deda-4542-8358-bf614cd2236b">

### To Reproduce

Upgraded from v0.47.9 to v0.48.2

### Expected behavior

We wouldnt have expected this large a change in CPU utilization

### Information about your Metabase installation

```JSON
- Metabase: 0.48.3
- Metabase Postgres: 14.10
- Metabase Environment: Self Hosted (AWS Fargate)
- Data Sources: Postgres 12 => 14
```

### Severity

Medium

**Comment by paoliniluis** [comment]
are you on 48.2 or 48.3?

**Comment by paoliniluis** [comment]
BTW: a single core instance is not recommended, as just a sync can take the entire CPU and your users won't be able to use the instance https://www.metabase.com/learn/administration/metabase-in-production

**Comment by charlesqing** [comment]
> BTW: a single core instance is not recommended, as just a sync can take the entire CPU and your users won't be able to use the instance https://www.metabase.com/learn/administration/metabase-in-production

Is there a tutorial for upgrading from v0.47.10 to v0.48.2? The database was switched from MySQL 5.7 to MySQL 8.0.35, but v0.48.2 could not be successfully started, indicating that the database could not find the table

**Comment by DavidDudson** [comment]
@paoliniluis  We moved to 48.3 now, We initially saw the spike when moving to 48.2, 48.3 didn't help. We are going to be move to 2 core anyway. 

It definitely seems to be syncing databases as its spiking from the logs we are receiving. Not sure if its relevant but at approx the same timestamps as the we are getting logs such as:

```
 metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type '_int4range' to a Field base_type, falling back to :type/*.
```

**Comment by paoliniluis** [comment]
@DavidDudson we need to know the exact data type that Metabase is syncing/scanning/fingerprinting to debug

**Comment by paoliniluis** [comment]
@DavidDudson can you send us some data? Are you using Postgres as the dw? Are you able to tell us if you have json values?

**Comment by paoliniluis** [comment]
We just released 48.4 @DavidDudson, can you check if this is fixed?

**Comment by maximepvrt** [comment]
I'm still having issues with the GPU @paoliniluis (V0.48.4)
![Capture d’écran 2024-02-05 à 15 52 38](https://github.com/metabase/metabase/assets/1840026/093ff907-4c52-4711-920f-228f5e88987d)
![Capture d’écran 2024-02-05 à 15 52 16](https://github.com/metabase/metabase/assets/1840026/a0527e75-5d54-43a6-8eec-75bb4802362b)

**Comment by paoliniluis** [comment]
@maximepvrt can you send the logs after 9:30?

**Comment by maximepvrt** [comment]
@paoliniluis https://gist.github.com/maximepvrt/0271aa5b733b993fe0e5023671f023c0

**Comment by paoliniluis** [comment]
@maximepvrt are you running Metabase with Jetty doing SSL instead of using an ingress or a reverse proxy?

**Comment by maximepvrt** [comment]
@paoliniluis I'm using Clever Cloud's reverse proxy (Sozu) with Metabase. Therefore, Metabase doesn't handle SSL since it's the Clever Cloud reverse proxy that manages it, communicating with Metabase over HTTP. So, no, Metabase isn't running with Jetty doing SSL; it receives plain HTTP traffic through the Clever Cloud reverse proxy.

**Comment by DavidDudson** [comment]
We have switched to v0.48.4 and upgraded to a 2 core machine. We are still getting a very spiky load. lets hope the open PR works. Heres a 3 day outlook of our instance.


<img width="1041" alt="Screenshot 2024-02-07 at 2 56 56 pm" src="https://github.com/metabase/metabase/assets/2680733/ec8031b6-71a7-47f7-bb34-d15043d068f0">

**Comment by DavidDudson** [comment]
We have 18 Data Sources (17 Postgres and 1 GA). We definitely have a number of json/jsonb columns, and we have tables with over 400 million rows. So we are probably on the higher side of usage. Happy to disable specific functionality that's causing the issues if there's a toggle in settings somewhere.

**Comment by DavidDudson** [comment]
Saw a couple of logs like this

```

2024-02-07 05:01:20,317 INFO sync.analyze :: [34mfingerprint-fields Analyzed [**********········································] 😞 20% Table 1,911 'Our Table (Redacted)'[0m
```

This specific table is a partition of a much larger table with the following format.

```
 CREATE TABLE "public"."redacted" (
          "id"                UUID NOT NULL DEFAULT uuid_generate_v4(),
          "redacted"     UUID NOT NULL,
          "redacted"         UUID NULL,
          "redacted"              CHARACTER VARYING NOT NULL,
          "redacted"     CHARACTER VARYING NOT NULL,
          "redacted"          CHARACTER VARYING NULL,
          "redacted"           BOOLEAN NOT NULL,
          "redacted"         INTEGER NOT NULL,
          "redacted"        BOOLEAN NOT NULL DEFAULT false,
          "redacted" TIMESTAMP NOT NULL,
          "redacted"             CHARACTER VARYING NOT NULL,
          "redacted" TIMESTAMP NOT NULL,
          "redacted"  UUID NULL
        ) PARTITION BY LIST (redacted);`)
```

There arent really any fancy data types, but the partitions are large and theres around 300 partitions tables. Each with up to 2 million rows

**Comment by calherries** [comment]
Reopening this because we don't know it fixed the issue yet.

**Comment by calherries** [comment]
@maximepvrt @DavidDudson [here's an EE JAR](https://github.com/metabase/metabase/pull/38482) created from the latest commit where https://github.com/metabase/metabase/pull/38482 merged to the 48 release branch. I'd appreciate it if you test it out and let us know whether it fixed the issue or not. Otherwise, you can wait for it in the 48.6 release.

**Comment by paoliniluis** [comment]
Adding something probably relevant to the thread which I just found while syncing a big DB:
![image](https://github.com/metabase/metabase/assets/1711649/ea4918ff-6fb7-487e-a630-7cd831663430)

this is the flamegraph for the specific time
![image](https://github.com/metabase/metabase/assets/1711649/94bb90bc-a412-4ccf-a2a3-74025f6485ed)

![image](https://github.com/metabase/metabase/assets/1711649/86747baf-7d02-40e2-8991-8aee7c221a23)

**Comment by DavidDudson** [comment]
I dont have time to do a manual deploy to test (we have automated minor deployments in terraform), but ill get back to ya as soon as 48.6 is out with my findings. Thanks heaps for looking into it!

**Comment by maximepvrt** [comment]
I will also wait for the release V0.48.6

**Comment by darksciencebase** [comment]
@DavidDudson @maximepvrt have you had a chance to look at it yet? [48.6 is out](https://github.com/metabase/metabase/releases/tag/v0.48.6)

**Comment by maximepvrt** [comment]
@darksciencebase @paoliniluis Since I updated with V48.6 (on the day of its release), I haven't encountered any issues.

**Comment by paoliniluis** [comment]
@DavidDudson can you check as well?

**Comment by DavidDudson** [comment]
Okay! I just had a look at how we have been going. And it's resolved. I'll close this issue. Thanks heaps to everyone involved

<img width="1035" alt="Screenshot 2024-02-22 at 1 30 15 PM" src="https://github.com/metabase/metabase/assets/2680733/04519d3a-98d5-406f-8768-ac5bc6023adb">
<img width="1035" alt="Screenshot 2024-02-22 at 1 29 58 PM" src="https://github.com/metabase/metabase/assets/2680733/54e09a2a-2c27-4d24-8caa-de3f5f15b83e">
