### ISSUE TITLE
Languages mixed into a filter of a dashboard

### ISSUE THREAD

**Issue by Pierre-PSUD** [metabase/metabase#38112]
### Describe the bug

My metabase version is in french.
When I want to apply a filter on a dashboard like : "All the stuffs *of the previous year*", it appears ```Previous année``` (```Année``` being the french word for ```year```).
It could be perfect to have ```Année précédente``` instead.

### To Reproduce

1. Configure your metabase in french version
2. Go to a dashboard with a filter which have a 'date' type
3. Click on it and filter to have all the result whose date is part of the ```Previous year```
4. ```Previous Année``` is written

### Expected behavior

Année précédente

### Logs

No response

### Information about your Metabase installation

French version of Metabase

### Severity

P3

### Additional context

No response

**Comment by paoliniluis** [comment]
this happens in all languages

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/24624

**Comment by ranquild** [comment]
Duplicate of https://github.com/metabase/metabase/issues/24624
