### ISSUE TITLE
Trend chart gives misleading output for some date combinations

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#38122]
### Describe the bug

Trend chart gives mixed outputs when you run an SQL query and shows date's which aren't even there. 

### To Reproduce

1. Go to New -> SQL Question:

```
Select '2023-12-31'::date, 28826833
UNION
Select '2022-12-31'::date, 33872127
```

2. Change the Visualization to a Trend Chart:

<img width="1505" alt="image" src="https://github.com/metabase/metabase/assets/110378427/e4eda18c-2d0f-451d-bb3f-fa2e8fadc0ca">

3. Notice that previously in 1.47 it used to only show the year `2023` now it shows `2023-2024` which is confusing 

### Expected behavior

Shows 2023 since the comparison year is 2023

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.48.3 and master
```

### Severity

Even though this is an aesthetic bug it broke the implementation of a number of customers that had  been already using the Trend Chart

**Comment by JesseSDevaney** [comment]
Closed by:
- https://github.com/metabase/metabase/pull/38344
- https://github.com/metabase/metabase/pull/38383
