### ISSUE TITLE
Prevent thousands-separator from being shown

### ISSUE THREAD

**Issue by hivre** [metabase/metabase#3813]
Since I've updated (now at 0.20.3, but coming from 0.19) thousands-separators are being shown in account-ids and phone-numbers which makes them hard to read, and not copy-pasteable. 

How can I prevent metabase from adding these sperators? The field values are entity-keys and foreign-keys in the database, so I can't give them a different field-type.

The question is custom SQL, and are INTs in the MySQL database, and are shown in a table. There's no option in the table-visualization dialog for showing seperators or data types. Just the ordering of columns.

**Comment by flamber** [comment]
Hi @hivre 
Since version 0.31, you can now change formatting multiple places - also on table columns. Please try the newer versions and close this issue if it fixes your problem.
![image](https://user-images.githubusercontent.com/1447303/52688074-48e2f780-2f1a-11e9-811d-1c1eb6226c61.png)

**Comment by mbvictoria** [comment]
Closing - resolved.
