### ISSUE TITLE
Filtering / grouping by foreign key value does unnecessary join

### ISSUE THREAD

**Issue by c2h5oh** [metabase/metabase#3815]
Right now if a column is defined as a foreign key it is no longer listed in the filter / group dropdowns.

As a result simple filter (specific FK value or IS NULL check) does a completely unnecessary join.

**Comment by underyx** [comment]
What's even more annoying is that apparently Metabase does inner joins only, and if there's no value on the right side, it's impossible to filter on the left.

**Comment by camsaul** [comment]
@underyx What version of Metabase are you using? Metabase has been using `LEFT JOIN`s for everything since 0.18.0 which came out in June 2016.

**Comment by c2h5oh** [comment]
@camsaul it doesn't matter. Because WHERE condition is on the ID field of the table referenced by the foreign key, so if there is no value on the right side row isn't returned, just like it would have been the case with INNER JOIN.

**Comment by salsakran** [comment]
@c2h5oh are you often grouping on the FK id or reaching through to the target table for a title or name? Our expectation was that in most cases, people will be doing the latter.

**Comment by underyx** [comment]
We're often doing the former @salsakran. For instance in tables with currency codes, country codes, etc. Extra info for a currency, like full name is available, but often we just want to get count by currency code, etc.

**Comment by c2h5oh** [comment]
I'm filtering.

Example: 
- Table 1: Events - has foreign key referencing Table 2: Accounts
- I want to filter events by account id 

Resulting query:
```SQL
SELECT "public"."events"."type" AS "type", [...], "public"."events"."account_id" AS "account_id"
FROM "public"."events"
LEFT JOIN "public"."accounts" "accounts__via__account_id" ON "public"."events"."account_id" = "accounts__via__account_id"."id"
WHERE "accounts__via__account_id"."id" = 7
LIMIT 2000
```

Now, since the where condition is on a column of the right table of the join there is no difference between left and inner join in this case.

**Comment by flagbug** [comment]
This is also a problem for us, as the join is making the query perform slower than necessary if you're just grouping/filtering on the foreign key

**Comment by luizarakaki** [comment]
Now it is possible to select from which table you want to filter. If the filter is applied on the left table, it doesn't add a join. If it is applied to the right table, it applies a join. I believe this is the expected behavior.
