### ISSUE TITLE
When using Metabase version v0.48.1, after building with /bin/build.sh, the frontend reports an error. 

### ISSUE THREAD

**Issue by cverdela** [metabase/metabase#38165]
### Describe the bug

When using Metabase version v0.48.1, after building with /bin/build.sh, the frontend reports an error. The specific error is as follows:
app.js:58 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
[
[localhost-1706184598774.log](https://github.com/metabase/metabase/files/14059170/localhost-1706184598774.log)
](url)
Attempting to fix this error leads to more issues.

### To Reproduce

Start Metabase with clojure -M:run to ensure the frontend works correctly.
Build Metabase using /bin/build.sh.
Access the built frontend, and observe the reported error.

### Expected behavior

Metabase should run without frontend errors after building.

### Logs

[localhost-1706184598774.log](https://github.com/metabase/metabase/files/14059184/localhost-1706184598774.log)

### Information about your Metabase installation

```JSON
Metabase Version: v0.48.1
Operating System: windows docker
```

### Severity

can not package

**Comment by paoliniluis** [comment]
Clean all your cache (yarn; node and clojure) and rebuild, when you start your browser do it in incognito
