### ISSUE TITLE
Lots of database suport

### ISSUE THREAD

**Issue by 100n0m3** [metabase/metabase#3819]
Well folks searching for support for different databases I found the following repository

https://github.com/ekzemplaro/data_base_language

Should we use the clojure of each database to create the metabase drivers could anyone help us with this?

**Comment by tlrobinson** [comment]
Unfortunately there's a lot more to creating a driver than just connecting to the database. Most of the work goes into translating our database agnostic query language (MBQL) into the databases' native query language. https://github.com/metabase/metabase/wiki/Writing-A-Driver

**Comment by camsaul** [comment]
Hi @100n0m3, thanks for sharing that link. It looks like it's a reference to connecting to different DBs in different languages.

As @tlrobinson mentioned a Metabase driver needs to do a lot more than just connect to a database. That reference might be a good jumping-off point for new drivers in the future, but we can't just take the examples and convert them to Metabase drivers.

Thanks for the idea, though!
