### ISSUE TITLE
Extreme slowness while editing parameters on a dashboard

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#38225]
### Describe the bug

Broken column mappings and very slow-moving interaction with the dashboard, possibly related. Please see more details and a loom recorded on stats in [this thread](https://metaboat.slack.com/archives/C05MPF0TM3L/p1706535171602269).

### To Reproduce

in the loom

### Expected behavior

We shouldn't be silently breaking mappings, and stuff should be snappier

### Information about your Metabase installation

```JSON
stats at 6c9d52e
```

### Severity

potentially P1 if we're producing incorrect data

**Comment by uladzimirdev** [comment]
I'm checking perf issue of frontend part

**Comment by bshepherdson** [comment]
There's apparently an issue with edited models and the field refs not lining up anymore.

We're making a request for eg. `/api/dashboard/1907/dashcard/13045/card/14066/query` (`Total ARR`, the top-left card). 

Card 14066 adds an aggregation and breakout on top of card 14023, a native model.
* 14023 has the `recognized_at` field with ID and `field_ref: ["field", 575819, {"temporal-unit": "default"}]`
* 14066 still has the ID, but `field_ref: ["field", 575819, {"base-type": "type/Date", "temporal-unit": "month"}]`
* the parameter from the dashboard is mapped to `target: ["dimension", ["field", 575819, {"temporal-unit": "default"}]]`, which matches the inner 14023 field but not the outer 14066 one.

So if we think the models changed lately, that's likely the issue causing `Unknown Field`, that the field refs for the parameter mapping don't match correctly.

**Comment by darksciencebase** [comment]
cc @NevRA

**Comment by uladzimirdev** [comment]
For clarification: 

This issue covers 2 different problems
1. As Braden highlighted, wrong parameter mapping is generated, which leads to `Unknown field` problems
2. Slowness of the editing dashboard
