### ISSUE TITLE
QB crash when zooming in on a pivot table header

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#38265]
### Describe the bug

QB crashes when using the "zoom in" drill-thru on some pivot table headers.

### To Reproduce

1. Create a pivot table kind of query, eg. `COUNT` and `SUM(subtotal)` on Orders, broken out by month, `Product.CATEGORY` and `User.STATE`.
    - [Stats link](https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjEsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdLFsic3VtIixbImZpZWxkIiwxNSx7ImJhc2UtdHlwZSI6InR5cGUvRmxvYXQifV1dXSwiYnJlYWtvdXQiOltbImZpZWxkIiwyNSx7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWUiLCJ0ZW1wb3JhbC11bml0IjoibW9udGgifV0sWyJmaWVsZCIsMzMseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJzb3VyY2UtZmllbGQiOjV9XSxbImZpZWxkIiwxNix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsInNvdXJjZS1maWVsZCI6MTB9XV19fSwiZGlzcGxheSI6InBpdm90IiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InBpdm90X3RhYmxlLmNvbHVtbl9zcGxpdCI6eyJyb3dzIjpbWyJmaWVsZCIsMzMseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJzb3VyY2UtZmllbGQiOjV9XSxbImZpZWxkIiwyNSx7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWUiLCJ0ZW1wb3JhbC11bml0IjoibW9udGgifV1dLCJjb2x1bW5zIjpbWyJmaWVsZCIsMTYseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJzb3VyY2UtZmllbGQiOjEwfV1dLCJ2YWx1ZXMiOltbImFnZ3JlZ2F0aW9uIiwwXSxbImFnZ3JlZ2F0aW9uIiwxXV19LCJwaXZvdF90YWJsZS5jb2x1bW5fd2lkdGhzIjp7ImxlZnRIZWFkZXJXaWR0aHMiOlsxMTEsMTQxXSwidG90YWxMZWZ0SGVhZGVyV2lkdGhzIjoyNTIsInZhbHVlSGVhZGVyV2lkdGhzIjp7fX19fQ==)
3. Select the Pivot Table visualization.
4. Click a row header, eg. Kansas.
5. Receive error message

### Expected behavior

I'm not actually 100% sure what the right query is in this case. I think it should retain the other two breakouts, drop the breakout by `STATE`, and add lat/long buckets instead. (That is what happens to the query internally, but it fails to render.)

### Logs

```
react-dom.production.min.js:209 Error: Invalid metadata returned for cell 2:
        x:276, y:0, width:NaN, height:30
    at t.cellCount (calculateSizeAndPositionData.js:17:13)
    at t.value (calculateSizeAndPositionData.js:35:1)
    at t.value (CollectionView.js:315:27)
    at ij (react-dom.production.min.js:182:192)
    at iI (react-dom.production.min.js:181:224)
    at l (react-dom.production.min.js:263:490)
    at aH (react-dom.production.min.js:246:265)
    at react-dom.production.min.js:246:194
    at aW (react-dom.production.min.js:246:199)
    at react-dom.production.min.js:123:115
```

### Information about your Metabase installation

```JSON
Stats, 49.
```

### Severity

Obscure case

**Comment by bshepherdson** [comment]
Looking a bit closer today, the query appears to be correctly formed, but it won't render.

The `zoom-in.geo` drill calls `setDefaultDisplay()` after updating the query, but that does nothing because `displayIsLocked()` returns true. (I suppose because the user just explicitly set the display to Pivot Table?)

Trying to render the resulting query as a pivot table crashes the FE. If you set the vis to Map and then refresh (because the crash has broken the FE) it renders correctly.

**Comment by qnkhuat** [comment]
Should resolve this [comment](https://github.com/metabase/metabase/blob/9e54403c88493a601669aec94b5efc3f80baf760/test/metabase/lib/drill_thru/zoom_in_bins_test.cljc#L133) while fixing this

**Comment by bshepherdson** [comment]
I can't reproduce this anymore. I suspect this was related to #43993 since it involves pivot tables and extra stages. (The map viz always worked, it was only the pivot table that was busted.)

**Comment by bshepherdson** [comment]
Okay, this was broken the morning I filed this issue - that is as of 3179ab1251e89a4a3a0da9578ffd5a37ef62b3c8.

It didn't exist on Christmas day, and it doesn't exist now or on the 50.x branch. The repro in my PR failed as expected on the bad version.

**Comment by bshepherdson** [comment]
Repro is in place, so I'm closing this out.
