### ISSUE TITLE
After uploading a csv file with Chinese characters, the display will be garbled

### ISSUE THREAD

**Issue by chanmaomao** [metabase/metabase#38260]
### Describe the bug

Whenever I upload a csv file with Chinese characters, when I'm browsing it, it doesn't show me the original characters.
![de48ecf5fbe311a63291c1d25b3d448](https://github.com/metabase/metabase/assets/151730237/32ea07f8-a4a3-4fe4-85e2-b274d00b64d0)

### To Reproduce

![de48ecf5fbe311a63291c1d25b3d448](https://github.com/metabase/metabase/assets/151730237/efbe9385-9d55-4fa9-aa36-fa1cfa644f59)

### Information about your Metabase installation

```JSON
Browser version: Google version 121.0.6167.86 (official) (64-bit)
Operating system: ubnutu20.xx
My database: 8.0.11-TiDB-v7.5.0
Configuration Database Internal Database: 8.0.11-TiDB-v7.5.0
```

### Severity

Urgent, because we have some colleagues who do not know how to use the database, need to upload the csv file, now there is no way to display Chinese, resulting in the inability to use metabase

**Comment by chanmaomao** [comment]
Sorry, I need to add that this is the original csv file I uploaded
![7be0681ec771a1b361e765287d4aca3](https://github.com/metabase/metabase/assets/151730237/818a5670-2087-4a42-bea0-af95b0dedc4e)

**Comment by paoliniluis** [comment]
most probably you're not adding the fonts to the server, are you running the JAR? or the container?
![image](https://github.com/metabase/metabase/assets/1711649/2c77715d-b7bb-419a-99b6-6dff226b01d9)

**Comment by chanmaomao** [comment]
> 很可能您没有将字体添加到服务器，您是否正在运行 JAR？还是容器？ ![图像](https://private-user-images.githubusercontent.com/1711649/300844482-2c77715d-b7bb-419a-99b6-6dff226b01d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjY4NDMsIm5iZiI6MTcwNjY2NjU0MywicGF0aCI6Ii8xNzExNjQ5LzMwMDg0NDQ4Mi0yYzc3NzE1ZC1iN2JiLTQxOWEtOTliNi02ZGZmMjI2YjAxZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMDIwMjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWExNjczM2Q2ZjFjYjI0ZjRkOTFiZjRjMzc0ZDIwYzQ0YzhmZWQwNTRiYTczNTA3M2E4NDdlNGI1NDU4OTBhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.apZ15I7ZivNlmtUiHHcMW_QWU38hXagJ8lvgXrKnobQ)

Sorry for the delayed reply as we have time difference, I am running in a container, where should I add the fonts next?

**Comment by chanmaomao** [comment]
Addendum: the test environment is deployed with containers, the production environment is deployed on k8s
