### ISSUE TITLE
Stop trying to update the analytics content on every start up

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#38270]
### Describe the bug

Seems that we're trying to update the contents on every startup. How do I know? if you start Metabase several times over the same instance, you'll see that the step "Loading Analytics Content" takes some time of the initialization

### To Reproduce

1) set up Metabase 48 with a persistent database
2) then shut it down
3) start it again
4) see in the app db that are queries like
		    10 Query	UPDATE `report_card` SET `query_type` = 'query', `dataset_query` = '{\"database\":13371337,\"query\":{\"aggregation\":[[\"count\"]],\"breakout\":[[\"field\",185,{\"base-type\":\"type/DateTimeWithLocalTZ\",\"temporal-unit\":\"month\"}]],\"filter\":[\"=\",[\"field\",190,{\"base-type\":\"type/Text\"}],\"dashboard\"],\"joins\":[{\"alias\":\"Content - Entity Qualified\",\"condition\":[\"=\",[\"field\",189,{\"base-type\":\"type/Text\"}],[\"field\",73,{\"base-type\":\"type/Text\",\"join-alias\":\"Content - Entity Qualified\"}]],\"source-table\":\"card__3\",\"strategy\":\"left-join\"},{\"alias\":\"Group Members - User\",\"condition\":[\"=\",[\"field\",187,{\"base-type\":\"type/Integer\"}],[\"field\",125,{\"base-type\":\"type/Integer\",\"join-alias\":\"Group Members - User\"}]],\"source-table\":\"card__5\",\"strategy\":\"left-join\"}],\"source-table\":\"card__23\"},\"type\":\"query\"}', `display` = 'line', `visualization_settings` = '{\"column_settings\":null,\"graph.dimensions\":[\"timestamp\"],\"graph.metrics\":[\"count\"],\"graph.show_values\":true,\"table.cell_column\":\"model_id\",\"table.pivot_column\":\"end_timestamp\"}', `created_at` = '2023-08-17 21:55:45.764868', `updated_at` = NOW(6) WHERE `id` = 39

### Expected behavior

We shouldn't do that on every load

### Information about your Metabase installation

```JSON
v48
```

### Severity

P1ish?

**Comment by escherize** [comment]
This has been merged and backported. 

https://github.com/metabase/metabase/pull/38622
https://github.com/metabase/metabase/pull/38627
