### ISSUE TITLE
"Goal" line breaks on scatter plot when too few data points

### ISSUE THREAD

**Issue by drewnewell** [metabase/metabase#3828]
Chrome 54.0.2840.71
OS X 10.11.4
Postgres
MB version 0.20.1

The goal line on charts moves when a filter is applied -- it no longer matches what you enter.

Correct:
![image](https://cloud.githubusercontent.com/assets/2434851/20736604/66d7afbc-b65c-11e6-82c0-3aea488d9b88.png)

Then, I apply a filter to the query, restricting the number of points to a few, and it sticks to the top:
![image](https://cloud.githubusercontent.com/assets/2434851/20736580/498c8b58-b65c-11e6-9cae-47f0e7787e95.png)

Everything works well if I have a data point above and below the goal. If I just have one above or below, the goal line breaks. This is regardless of the scale -- even if the correct goal position is visible, it still gets stuck at the top.

**Comment by flamber** [comment]
Hi @drewnewell 
I've tried to reproduce your issue on 0.31.2 without success. Can you verify it's working in newer versions?
![image](https://user-images.githubusercontent.com/1447303/52687661-93637480-2f18-11e9-8e02-ac016cd90b4e.png)
![image](https://user-images.githubusercontent.com/1447303/52687733-d32a5c00-2f18-11e9-8d38-8b0da425128a.png)
![image](https://user-images.githubusercontent.com/1447303/52687771-f35a1b00-2f18-11e9-81ab-7df1703a8640.png)

**Comment by drewnewell** [comment]
Thanks for looking into it, I can't reproduce either

**Comment by flamber** [comment]
@drewnewell Okay, then please close the issue.
