### ISSUE TITLE
Implementation Plan: ParseSQL Lineage

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#38316]
Part of #36911 

I have [a spike branch](https://github.com/metabase/metabase/tree/tsm-spike/sql-lineage) going that uses [JSQLParser](https://jsqlparser.github.io/JSqlParser/index.html) and it seems like a winner.

The goal is to know which columns of which tables are used by a query, so that we know what needs to be updated when a rename happens. From the product doc:

> Managing data source migrations is a pain in Metabase. If you need to rename a schema/table/field, it is hard to track all the dependencies. Parsing the source table of native queries would give us the necessary data to support lineage (and enable batch source swaps).

The plan is this:

1. Get a list of all the tables used in the query. This is doable with the parser, and I've written code to cover the easy cases. It needs to be extended for joins and such, but it seems tractable.

2. Get a list of all the columns used. Ditto.

3. It is *not* possible to know from the query what column comes from what table. Consider the case of `select name from core_user, report_card;` the column `name` *could* exist in one table, the other, or both. So, we'll have to assume both, but we can make life a little easier by cross-referencing the resulting cartesian product of tables×columns against the columns we know to exist from a DB sync.

4. We'll create a new join table with columns `card_id`, `table_id`, and `column_name`. It will have an entry for each column used in a given card's query.

5. We'll have to do an initial pass over all native cards (with supported engines) to populate the join table.

6. When a card's query is modified, we re-parse it and re-populate the join table.

7. When a column or table is renamed, we can know which questions are affected.
  a. **Question:** How do we know when the column/table is renamed? I don't think DB scanning picks that up (as opposed to "column `foo` no longer exists, column `bar` is new).
  
 8. Automatically updating renaming tables/columns: see note
 
 ## Auto-renaming
 
 This is in theory possible, but in practice I'm nervous about false positives since (similar to above) there are a few undecidable cases. If `core_user.name` is renamed to `core_user.full_name` but `report_card.name` stays the same, what should happen to `select name from core_user, report_card;`?
 
 In general, I'd like to know what the product plan is for "we think this question is affected by a rename, now what?"
  
  ## Dialects
  
  JSQLParser supports the following out of the box. I've bolded the ones that Metabase has official drivers for:
  
* **Oracle**
* **MS SQL Server** and Sybase
* **Postgres**
* **MySQL** and **MariaDB**
* DB2
* **H2** and HSQLDB and Derby
* **SQLite**

Presumably we could use its Postgres support for Redshift, too.

I think it makes sense to get Postgres working first. Then it should be fairly non-invasive to expand to the other dialects.

The key, of course, will be a robust test suite with as many tricky examples sourced from real places (stats, the success team…) as possible.

One drawback is that JSQLParser doesn't support a few dialect-specific features ([link](https://jsqlparser.github.io/JSqlParser/unsupported.html)). Postgres casting and JSON operators are the ones that jumped out at me. The easy option is to throw our hands up when we encounter a parse error and do nothing. I suppose a more graceful option would be to maintain a list of unparseable queries for manual review or something, but that doesn't sound very Metabasey. Extending the parser is always a possibility, but it's not something we should dive into tomorrow…

## A few technical details:

First of all, I considered trying to get the table+column out in one fell swoop and decided that was intractable. Easier to get tables and columns separately and then try to stitch it together.

It seems right to just use a multi-method to pick apart the AST. This reads nicely to me:

```
(defmulti query->tables
  "Given a parsed query, return a sequence of tables that it references."
  class)

(defmethod query->tables PlainSelect
  [^PlainSelect parsed-select]
  (concat
   (query->tables (.getFromItem parsed-select))
   ;; more is needed (join?)
   ))

(defmethod query->tables Table
  [^Table table]
  [(.getFullyQualifiedName table)])

(defmethod query->tables ParenthesedSelect
  [^ParenthesedSelect paren-select]
  (query->tables (.getPlainSelect paren-select)))
  ```
  
 And it's easy to imagine adding a method for `Join` and such.
  
Steps 4-6 are just standard Metabase app dev, I don't think there's anything too spicy there.

**Comment by paoliniluis** [comment]
My 2c here. I would test this with:
1) a GUI question and a SQL question
2) a nested gui question and a nested sql question
3) a gui question that uses sql question as the source, and also the opposite
4) a SQL question with snippets, filters and field filters
5) a sql question with lots of CTEs
6) a sql question with comments

sorry, I embarked on the same journey when building Metagraph and the complex cases were a mess

**Comment by tsmacdonald** [comment]
This is superseded by the one in Notion
