### ISSUE TITLE
Configurable general query timeout

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#38338]
**Is your feature request related to a problem? Please describe.**
Make metabase.query-processor.query-timeout-ms configurable via env vars

**Describe the solution you'd like**
pretty sure it's the cause of https://github.com/metabase/metabase/issues/27789 and others, also it will serve for customers that have massive queries

**Describe alternatives you've considered**
Custom build

**How important is this feature to you?**
Requested by a lead, and seems a decent request to make

**Additional context**
NA

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/4564

**Comment by kevgliss** [comment]
We are running into this with a druid database which has a much smaller query timeout than the default (1200sec). I was under the impression that this could be tweaked via: `MB_JDBC_DATA_WAREHOUSE_UNRETURNED_CONNECTION_TIMEOUT_SECONDS` but that doesn't seem to have an effect as far as I can tell.

**Comment by paoliniluis** [comment]
this is now a thing https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_db_query_timeout_minutes
