### ISSUE TITLE
Correct way to store datetime fields in MongoDB

### ISSUE THREAD

**Issue by davidmir** [metabase/metabase#3833]
Hi,

In MongoDB i'm saving the date fields in the following format: ISODate ("2016-11-30T18: 15: 00Z"). But the metabase never recognizes this field as being of type DateTimeField. 

What format should I save dates to be recognized as DateTimeField.

Thanks.

**Comment by camsaul** [comment]
Hi @davidmir, We're marking any fields that come back as a BSON `Date` type as `DateTimeField`.  It sounds like [`ISODate()` returns a `Date`](https://docs.mongodb.com/manual/core/shell-types/). 

What percentage of the values for that field are `null`?

**Comment by davidmir** [comment]
Hi @camsaul, 

When I was saving the dates in ISO format it was not working (and had no values to null). I started saving the DateTime (python) objects directly and it was identified as a datetime variable.

Thanks.

**Comment by camsaul** [comment]
@davidmir, yeah, they have to be `Date` objects rather than plain strings. Anything else we can help with?

**Comment by davidmir** [comment]
No. You can close this issue.

Thanks@

**Comment by davidmir** [comment]
Hi @camsaul,

I'm dealing with this problem again. I have a field in which the values are as follows: null (30), Date (9). Does this influence the type of data that the metabase assumes?
