### ISSUE TITLE
Improve documentation around drop down filters in dashboards

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#3834]
Metabase Documentation http://www.metabase.com/docs/v0.20.1/users-guide/07-dashboard-filters.html shows drop down filter (select from fields), there is however no documentation how to create this drop down and what are the limitations.

![image](https://cloud.githubusercontent.com/assets/6222611/20766582/d13e87b0-b6eb-11e6-9e96-2e00df8c7710.png)

- document how to create dropdown in dashboards
- document how this works with custom SQL
- document how this works with "show all records" without being forced to pick single value
- document what are the limitations (number of records in dropdown etc)

I am pulling my hair and cannot make it work at all

**Comment by mazameli** [comment]
So sorry you're having trouble with this! You're right in that we haven't specifically documented how to create each different kind of dashboard filter; we've only given the date filter example. To create a dropdown filter, you'll want to use the `Other Categories` filter type. Then you'll choose which field to link your filter to for each card, and based on those selections, the dropdown will be populated with values accordingly.

To make this work with SQL-based cards, you'll need to add a bit of syntax so that Metabase knows how to apply the dashboard filter to the SQL card. You can read the documentation on that here: http://www.metabase.com/docs/v0.20.3/users-guide/12-sql-parameters.html#the-field-filter-variable-type

Your list is a good to-do list for improving our docs for these features. Thanks, and apologies again for the difficulties you're having.

**Comment by CzechJiri** [comment]
Thank you for quick answer. 

I can make it work when the number of records in the lookup table (meaning field filter) for the dropdown is small, but when the table has large number of records (total number of records, in my case there is still few distinct records only), the dropdown simply shows as textbox only. Almost smells like a bug.

**Comment by mazameli** [comment]
Ah, gotcha. Does this issue describe what you're experiencing? https://github.com/metabase/metabase/issues/2848

I know you mentioned there are "still few distinct records only," but the dropdown does turn into an input box if the number of distinct values in the connected field(s) exceeds 40 (which, as you mentioned, I don't believe we currently document anywhere — we need to fix that).

**Comment by CzechJiri** [comment]
there is 4 distinct values in the field, but the table has over 100,000 records total, my feel is that the distinct runs on the server or client side? not sure ideally it should fire DISTINCT SQL on DB

when I run the same on table with 44 records total (still 4 distinct values), it works like a charm

**Comment by mazameli** [comment]
Hmm, @tlrobinson, do you have any insights on what the problem here might be?

**Comment by salsakran** [comment]
Hey @CzechJiri -

The code in question pulls up the list of FieldValues. In general, we only use FieldValues on low cardinality (<= 40) dimensions, and for anything else, we don't suggest values. This is a bit hokey, and we're looking into finding ways to do better at it. 

The code in question lives in https://github.com/metabase/metabase/blob/master/src/metabase/sync_database/analyze.clj#L55 if you're curious.

If you have a low cardinality field (eg, the 4 value one you mention), we should be catching it unless you've disabled "analyse database" in the individual DB.

**Comment by CzechJiri** [comment]
happy to share logs or whatever you need... several of our engineers are braking teeth trying to make it work, its a mystery, btw I can make it work my on laptop in "metabase app", but not in a docker metabase (really spent hours making sure the underlying data is identical)

analyze database is enabled

**Comment by salsakran** [comment]
do you have access to the application database? 
I'd suggest trying to find that field in `metabase_field` and seeing if it has an entry in `metabase_fieldvalue`. Does it have records there?

**Comment by mazameli** [comment]
@CzechJiri, are you still experiencing this problem? This actual github issue seems to be resolved (it was just a request for clearer documentation), but before closing the issue I wanted to see if your separate problem is still present.

**Comment by nickcarenza** [comment]
I am unable to get this to work on v0.22.2. I will try upgrading.

When I add a filter on a dashboard with the "other" type I don't get a dialog asking to link it to any part of a query. My sql is written like documented here http://www.metabase.com/docs/v0.20.3/users-guide/12-sql-parameters.html#the-field-filter-variable-type.

**Comment by mokra** [comment]
Has there been any update on this?
I can't get my filters work either. The table has 400 distinct values

**Comment by Dorithur** [comment]
I can't get what I need from filters too. I have a column in table with ~1300 distinct values and everything works as described above.
I can go without suggestion list, but I definitely need to have more than one value in this filter. Is there any other way to make it?
![image](https://user-images.githubusercontent.com/7486807/38562117-7a62f7a4-3ce2-11e8-85ac-7644d04fe892.png)
I want something like this for a field with a high volume data in it.

**Comment by jyotipatel** [comment]
Hi,

Distinct values in my table field is more than 1000. Is there any hack I can do to make field filter work on this field, I am not able to use metabase because of this restriction.

**Comment by mazameli** [comment]
@jyotipatel I went ahead and answered your question over in #7603. 

I'm going to go ahead and close this issue as we now have plenty of documentation about all of this here: https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html
