### ISSUE TITLE
Changed logo colors in 48

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#38355]
### Describe the bug

In 47 we used to respect the logo colors, now in 48 we no longer do it.

### To Reproduce

1) start your metabase instance with the following env var in 47
MB_APPLICATION_LOGO_URL: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI2LjIuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAyMDAuMyAxMzIuNCIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMjAwLjMgMTMyLjQ7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KCS5zdDB7ZmlsbDojQTEwMDdEO30KCS5zdDF7ZmlsbDojRkY5RTE4O30KCS5zdDJ7ZmlsbDojMDA5QURFO30KCS5zdDN7ZmlsbDojODBCQzAwO30KPC9zdHlsZT4KPGc+Cgk8Zz4KCQk8cG9seWxpbmUgY2xhc3M9InN0MCIgcG9pbnRzPSIxMTAuNSw4Ni41IDEwNC41LDkzLjMgMTA5LjcsOTkuMyAxMTUuNiw5Mi41IAkJIi8+CgkJPGc+CgkJCTxwb2x5Z29uIGNsYXNzPSJzdDEiIHBvaW50cz0iMTAwLjYsMzkuNiAxMjEuOCw2My45IDEyNyw1OCAxMDAuNiwyNy43IDczLjksNTguMyA3OS4xLDY0LjMgCQkJIi8+CgkJCTxwb2x5Z29uIGNsYXNzPSJzdDAiIHBvaW50cz0iMTMxLDYzLjEgMTE5LjksNzUuOCAxMjUuMSw4MS44IDEzMSw3NSAxNTYuNSwxMDQuMiAxNjYuOSwxMDQuMiAJCQkiLz4KCQkJPHBvbHlsaW5lIGNsYXNzPSJzdDIiIHBvaW50cz0iMTE1LjcsOTIuNiAxMjUuOCwxMDQuMiAxMzYuMiwxMDQuMiAxMjAuOCw4Ni42IDExNS43LDgwLjcgMTAwLjMsNjMuMSA4OS4yLDc1LjggOTQuNCw4MS44IAoJCQkJMTAwLjMsNzUgMTEwLjUsODYuNiAJCQkiLz4KCQkJPHBvbHlnb24gY2xhc3M9InN0MiIgcG9pbnRzPSI2NC40LDEwNC4yIDc0LjgsMTA0LjIgODAuNyw5Ny40IDc1LjYsOTEuNSAJCQkiLz4KCQkJPHBvbHlnb24gY2xhc3M9InN0MyIgcG9pbnRzPSI5MC4xLDg2LjYgODUsODAuNyA2OS42LDYzLjEgMzMuOCwxMDQuMiA0NC4xLDEwNC4yIDY5LjYsNzUgNzkuOCw4Ni42IDg1LDkyLjYgOTUuMSwxMDQuMiAKCQkJCTEwNS41LDEwNC4yIDEwNS41LDEwNC4yIDEwMC4zLDk4LjMgCQkJIi8+CgkJPC9nPgoJPC9nPgo8L2c+Cjwvc3ZnPgo=
2) see the logo with colors
3) now move to 48
4) see the logo with the metabase blue color

### Expected behavior

we should respect the logo colors

### Logs

NA

### Information about your Metabase installation

```JSON
v48.x
```

### Severity

P1

### Additional context

Using a P1 here as this is from an enterprise customer who's having this in production and the visuals changed

**Comment by iethree** [comment]
In metabase v48 we updated our Content Security Policy to [disallow inline styles](https://content-security-policy.com/examples/allow-inline-style/) for security reasons. The logo above included an inline <style /> tag in the svg to apply colors. Instead, if you use the svg `fill` property instead, it works as expected without running afoul of CSP.
