### ISSUE TITLE
Mention that we create an internal user in 48 in our docs

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#38362]
A new user has been created in 48 (internal@metabase.com), we should mention that in the docs and what we use the user for

**Comment by jeff-bruemmer** [comment]
This PR closed the issue: https://github.com/metabase/metabase/pull/41207.

Docs are here: https://www.metabase.com/docs/latest/people-and-groups/managing#default-user-accounts

@arunura thanks for reporting!
