### ISSUE TITLE
Add Browse Models below Data section in left menu and keep Browse Data as a link to /browse/databases

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#38373]
**Is your feature request related to a problem? Please describe.**
- Additional click required to get to browse data which is a very common action for self-service users

**Describe the solution you'd like**
Add two items under the DATA heading on the left menu:
- "Browse data" that takes users to /browse/databases
- "Browse models" that takes users to /browse/models

**Describe alternatives you've considered**
- default to Browse data and have models require a second click (adds friction to browse models instead of to browse data)

**How important is this feature to you?**
- behavior in `master` as of `022201a` adds an extra click to a very common action (i.e. browse data)

**Additional context**
- Old behavior was 1 click to get to list of data sources, new behavior is 2 clicks (and a cursor move on a small target)

**Comment by brunobergher** [comment]
That's where we ended up.
