### ISSUE TITLE
Incorrect SQL generated for WHERE clause when using Native Query and DateTime Field Filter Variables: DATE_TRUNC

### ISSUE THREAD

**Issue by mayanala-coxauto** [metabase/metabase#38384]
### Describe the bug

We have an Athena table with column 'partition_date_hour' string datatype. Data for that column looks like this in YYYY-MM-DD HH:00 format

partition_date_hour
---------------------
2024-01-14 23:00
2024-01-14 23:00
2024-01-14 23:00
2024-01-14 23:00
2024-01-14 23:00
2024-01-14 23:00

We did casting at column level to Field Type -> Creation Timestamp and Cast to a specific data type -> Coercion/ISO8601 ->DateTime.

**We created a query with variable p_date with Variable type -> Field Filter and Filter widget type: Date Filter**

![image](https://github.com/metabase/metabase/assets/49332534/00ea8e14-4b0d-4076-a754-5bd73310c0f6)

As you can see we get 0 results and following is the preview of the query,
SELECT
COUNT(*) AS "count"
FROM
"ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"
WHERE
"ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"."account_id" = '183385486431'
AND "ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"."action" = 'ALLOW'
AND "ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"."httpsourcename" in ('ALB','APIGW','APPRUNNER','APPSYNC','CF','COGNITOIDP')
AND **DATE_TRUNC('day', CAST("ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"."partition_date_hour" AS timestamp)) BETWEEN timestamp '2024-01-15 18:00:00.000' AND timestamp '2024-01-15 19:00:00.000'**

**If we take DATE_TRUNC generated by metabase, it returns results.**

**To prove that, we created same query with 2 variables start_time and end time with Variable type -> Date**

![image](https://github.com/metabase/metabase/assets/49332534/8f3bb150-4588-4d41-8d28-b6946f22f505)

** Note: Above selection do not show the Hour selected but that is another bug I guess **

As you can see it returns results as expected 56,556 rows. 

Preview of the above query is as follows

SELECT
  COUNT(*) AS "count" 
FROM
  "ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"
WHERE
"ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"."account_id" = '183385486431' 
   AND  "ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"."action" = 'ALLOW'
AND  "ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"."httpsourcename" in ('ALB','APIGW','APPRUNNER','APPSYNC','CF','COGNITOIDP')  
AND CAST("ca_secdatalakenp_waf_logs_fh_test"."waf_logs_fh_test_raw_h_v13"."partition_date_hour" 
AS timestamp) 
BETWEEN timestamp '2024-01-15 18:00:00.000' and timestamp '2024-01-15 19:00:00.000'

**So DATE_TRUNC is making the difference of results here.**

### To Reproduce

I'm not able to reproduce this issue in Sample Database as there is no column with Datetime stored as string YYYY-MM-DD HH:00 format. I'll try to think of other ways to reproduce it.

### Expected behavior

Explained in Describe Bug section

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9-LTS",
    "os.name": "Linux",
    "os.version": "4.14.273-207.502.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.12"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-05",
      "tag": "v0.47.11",
      "branch": "?",
      "hash": "51935b1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking usage of timestamp in all queries as it returns incorrect results due to DATE_TRUNC

**Comment by mayanala-coxauto** [comment]
@flamber

**Comment by paoliniluis** [comment]
was this working in a previous version?

**Comment by mayanala-coxauto** [comment]
@paoliniluis We are not sure if it worked before as this is the first time we are trying such queries.

**Comment by Tony-metabase** [comment]
Can you upgrade to 1.48.8 ... I think you might be hitting this one https://github.com/metabase/metabase/issues/38037

**Comment by perivamsi** [comment]
@mayanala-coxauto are you still facing this issue? We are unable to reproduce it.
