### ISSUE TITLE
MySQL "Sum of value" not calculating correctly

### ISSUE THREAD

**Issue by ArtursO** [metabase/metabase#3838]
Hello, I am trying to run a query where I want sum of values grouped by day.

When I run the query with a raw data view I'm getting the correct individual values. However, when I want to get a sum of these values and group them by day I'm getting incorrect values.

Below are the raw values for November 29th, which total 7.75.

![screen shot 2016-11-30 at 3 45 52 pm](https://cloud.githubusercontent.com/assets/6081495/20771580/0167a882-b718-11e6-9751-f3dd60ee1dfb.png)

When I want to see the sum of values by day I get this below, which is incorrect (as you can see November 29th is incorrect, as are the other dates too):

![screen shot 2016-11-30 at 3 47 02 pm](https://cloud.githubusercontent.com/assets/6081495/20771615/264e7cac-b718-11e6-9da1-48479e10a8c3.png)

Also, there is data for November 30th, however in the query with the Sum of view, the data isn't appearing. Below is a screenshot confirming that there is data for that date. 

![screen shot 2016-11-30 at 3 45 58 pm](https://cloud.githubusercontent.com/assets/6081495/20771645/445cddf6-b718-11e6-9824-0ab593f78be3.png)

Thanks a lot for working on this tremendous open source project!

### Bugs

- Your browser and the version: Chrome Version 54.0.2840.98 (64-bit)
- Your operating system: mac OS Sierra 10.12.1
- Your databases: MySQL
- Metabase version: 0.20.3
- Metabase hosting environment: Heroku
- Metabase internal database: H2 (default)

- *Repeatable steps to reproduce the issue*
Not exactly sure how you could reproduce this error.

-------

**Comment by camsaul** [comment]
@ArtursO it looks like the days are just off by one when you do the sum (e.g., November 29th should actually be November 30th, &c.).

What timezone is your MySQL database, and have you set a timezone in the admin panel?

**Comment by ArtursO** [comment]
@camsaul thank you for replying so fast.

1) Okay, that's true in the case of November 30th (which is a total value of 4.5), right now it's showing up as November 29th. 
But then wouldn't the November 29th value of 7.75 show up for November 28th (which shows 10.5)?

2) The timezone of the MySQL database is UTC, the timezone set in the admin panel that I set is EST. (note: however the system that's feeding data into the MySQL database is set to EST)

**Comment by ArtursO** [comment]
Looks like we figured it out. Setting the timezone to EST did the job. Thanks @camsaul !

**Comment by lewislevenberg** [comment]
@ArtursO I think you mean setting the timezone to UTC in the metabase admin panel, correct?

**Comment by ArtursO** [comment]
Yes I did. Thanks lewis. :/

**Comment by salsakran** [comment]
Glad you figured it out. Closing.
