### ISSUE TITLE
Grouping by timezone-aware timestamps results in duplicates in DST-changing months (Snowflake)

### ISSUE THREAD

**Issue by sicarul** [metabase/metabase#38399]
### Describe the bug

Our Metabase instance and Snowflake database have timestamps in the America/Los_Angeles timezone, this timezone changes every year at March and November.

The way Metabase is generating queries when grouping by Month on such fields, generates duplicate values.

By inspecting the SQL Query, this seems to be because we are just using "date_trunc", which will generate e.g. on Nov 2023, to have a row that says "Nov 2023, UTC-7" and another row that says "Nov 2023, UTC-8"

### To Reproduce

Create a table in Snowflake that has at least two timestamps with timezone, e.g.:

create table test as (
select convert_timezone('UTC', 'America/Los_Angeles', '2023-11-01 00:00:00')::timestamp_tz as date
union
select convert_timezone('UTC', 'America/Los_Angeles', '2023-11-08 00:00:00')::timestamp_tz as date
)

Go to metabase, sync this table and try to group by this field, instead of getting one row that indicates that there are two rows, you'll get two rows with one each.

### Expected behavior

Only one row should be generated per each month/quarter/year

### Logs

There are no relevant logs, but this is a sample query generated by Metabase from a question with this issue:

```
SELECT
  DATE_TRUNC("month", "CORE"."DIM_ACCOUNT"."CREATED_AT") AS "CREATED_AT",
  COUNT(*) AS "count"
FROM
  "INFORMATION_MARTS"."CORE"."DIM_ACCOUNT"
WHERE
  (
    "CORE"."DIM_ACCOUNT"."CREATED_AT" >= '2023-11-01 00:00 -07:00':: timestamp_tz
  )
 
   AND (
    "CORE"."DIM_ACCOUNT"."CREATED_AT" < '2023-12-01 00:00 -08:00':: timestamp_tz
  )
GROUP BY
  DATE_TRUNC("month", "CORE"."DIM_ACCOUNT"."CREATED_AT")
ORDER BY
  DATE_TRUNC("month", "CORE"."DIM_ACCOUNT"."CREATED_AT") ASC
```

<img width="948" alt="image" src="https://github.com/metabase/metabase/assets/4952116/d480b08e-e499-4efa-9938-93f37cb0fec7">
<img width="304" alt="image" src="https://github.com/metabase/metabase/assets/4952116/c1146660-bdd1-4ad8-ba9e-4d15573cbeb0">

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.201-191.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-29",
      "tag": "v0.48.4",
      "hash": "62145b0"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

### Severity

This breaks a lot of reports and makes us resort to SQL instead of the visual editor in many cases.

**Comment by perivamsi** [comment]
Duplicate of https://github.com/metabase/metabase/issues/37065

**Comment by sicarul** [comment]
Closed as this is a dupe, sorry i didn't see it.
