### ISSUE TITLE
Issues with graphing: disappearing columns & handling of null values 

### ISSUE THREAD

**Issue by aguarin1** [metabase/metabase#3839]
**On disappearing columns caused by null values**
I was recently attempting to generate a scatterplot from a query where some of the cells were null values. The graph worked on a first pass (here's a screenshot of a section of the graph to indicate that the graph works on the first pass):

<img width="537" alt="screen shot 2016-11-30 at 1 27 05 pm" src="https://cloud.githubusercontent.com/assets/4743367/20772069/ebe82516-b700-11e6-89e3-7a4dddd19b3e.png">

However, when saved and/or refreshed the page, the graph would disappear and the following error would be thrown:

<img width="525" alt="screen shot 2016-11-30 at 1 26 48 pm" src="https://cloud.githubusercontent.com/assets/4743367/20772042/d1e9313c-b700-11e6-9d2a-cb9a9e16460d.png">

Upon trying to generate the scatterplot again by clicking the cog and selecting a column (any column) for the x-axis, this is what the output to the console is:

<img width="643" alt="screen shot 2016-11-30 at 1 27 30 pm" src="https://cloud.githubusercontent.com/assets/4743367/20772114/1921ca5a-b701-11e6-96d9-0acf124d3dd8.png">

The workaround here was to make `null` values equal to 0 using a `CASE... WHEN` statement, but it would be better if null values were just handled. 

Here's some example SQL code to replicate on test data, where some of the values are null:

```
SELECT test_table.scatter_field_1,
    test_table.scatter_field_2           [there are null values here]
FROM test_table
```

Generate scatter plot
Refresh the data a couple of times
Plot should clear and throw "Please select columns..." error + console output saying "cannot read property"

Workaround:

```
SELECT test_table.scatter_field_1,
    CASE
        WHEN test_table.scatter_field_2 is NOT NULL
            THEN test_table.scatter_field_2
        ELSE 0
    END as scatter_field_2
FROM test_table
```

**Comment by camsaul** [comment]
Hi @aguarin1, what version of Metabase was this?

**Comment by flamber** [comment]
Hi @aguarin1 
I've tried to reproduce your issue without success - I've tested on 0.31.2 with SQL2008 on Firefox 65:
![image](https://user-images.githubusercontent.com/1447303/52687074-fbfd2200-2f15-11e9-86c6-9b817c504da6.png)
