### ISSUE TITLE
timestamps without time zone get exported as dates in CSV exports

### ISSUE THREAD

**Issue by scd75** [metabase/metabase#38403]
### Describe the bug

I have tz-aware timestamps (timestamptz) stored in my source PostgresDB.
I convert those tz-aware timestamps with the function convertTimezone in a custom column in Metabase, which outputs a naive timestamp, as per Metabase documentation.
When I export it to a csv, this custome column only displays as a date ("2023-02-01"). I do not have the time component.

More generally (feature request) I find that the customization of export formats for csv/excel could be imporved (chose how to output dates: as text or date, in which exact format etc.)

### To Reproduce

To Reproduce
1. create a Postgres DB with a timestamptz column
2. add a custom column with convertTimezone Metabase function
3. download an extract as csv
See error: the csv file only has the date component for this custom column

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.0-1052-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-29",
      "tag": "v0.48.4",
      "hash": "62145b0"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Quite annoying yet not extremely critical

### Additional context

More generally (feature request) I find that the customization of export formats for csv/excel could be imporved (chose how to output dates: as text or date, in which exact format etc.)

**Comment by paoliniluis** [comment]
@scd75 can you try on a test environment (please do not use this in production)  metabase/metabase-head:latest and check if the issue still exists? pretty sure that we fixed this in v49 so I'm closing this while you test

**Comment by brunomenu** [comment]
Hi everyone
I have the same problem: when exporting to CSV, the column containing datetime has datetimes for most hours, but only a date when hour is 00:00, see example attached. There's a temporary solution of exporting as excel, in which case this bug doesn't appear.

![image](https://github.com/metabase/metabase/assets/30413220/a97a49ed-ed4e-4143-bf2f-3aaf5454ea33)
