### ISSUE TITLE
Pulse not using system timezone (always using UTC)

### ISSUE THREAD

**Issue by key88sf** [metabase/metabase#3841]
Metabase v0.20.3 running on AWS ElasticBeanstalk (Docker image).
JAVA_TIMEZONE = US/Eastern

Looks like pulses are firing always based on UTC time?

We have a pulse set up to send email at 5pm, but they are always coming at 12pm EST (which is 5pm UTC).  Shouldn't the pulse respect the timezone setting of the system?

**Comment by camsaul** [comment]
@key88sf are you sure the JVM is actually seeing your timezone as `US/Eastern`? I can't find anything about using an env var called `JAVA_TIMEZONE`, AFAIK you're supposed to use `-Duser.timezone`.

You can double-check the JVM timezone if you run `java -jar metabase.jar version`.

**Comment by key88sf** [comment]
@camsaul http://www.metabase.com/docs/v0.21.0/operations-guide/running-metabase-on-elastic-beanstalk.html#setting-the-jvm-timezone

**Comment by camsaul** [comment]
Ok... it looks like our [`./run_metabase.sh` script](https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh#L31) is allegedly passing that as `-Duser.timezone`:

```bash
if [ ! -z "$JAVA_TIMEZONE" ]; then
  JAVA_OPTS="${JAVA_OPTS} -Duser.timezone=${JAVA_TIMEZONE}"
fi
```

@tlrobinson @salsakran is that the correct `Dockerfile`? I get these mixed up because we have two 😞

**Comment by javiercr** [comment]
I just got the same problem, let's hope we can get this fixed! :D

**Comment by salsakran** [comment]
@javiercr  + @key88sf 

We use either the Reporting timezone (if set) or UTC as a fall back.

Pulses are an end user and analyst facing feature for people who don't know what the server timezone is, or the ability to change it. Additionally, a lot of folks run us on cloud providers that aren't in their timezone. 

We should probably document this better.

**Comment by salsakran** [comment]
Closing this as baring lots of users wanting server timezone to mean something, it's not something we're going to do.

I'd suggest setting a reporting timezone as that provides a shared reference point for all of these things.
