### ISSUE TITLE
Pie chart % show on chart doesn't show for areas larger than 95%

### ISSUE THREAD

**Issue by jamesladyman-cognitant** [metabase/metabase#38424]
### Describe the bug

Hello,

For some reason when selecting 'show percentages on the chart' with pie charts areas over 95% in size don't display the percentage

![image](https://github.com/metabase/metabase/assets/97034772/e718302c-0f1b-495a-9ac4-3b90d9323590)

vs

![image](https://github.com/metabase/metabase/assets/97034772/65003b27-78b6-4dc7-9cda-f82a2317d4f5)

&

![image](https://github.com/metabase/metabase/assets/97034772/addb2969-2377-4539-be4d-e6469317f612)

I suppose this might be intentional behaviour but at the very least that seems to be undocumented, which caused me many hours of frustration, and ideally would be something we could turn off since having this setting turned on means the percentages will not be in the legend so the information is completely lost otherwise. Also it just makes the chart ugly

I'd consider being able to have them in both the legend and on the chart as a slightly less ideal solution to this too.

### To Reproduce

```
select 'first' as "data", 0 as "amount"

union all

select 'second' as "data", 0 as "amount"

union all

select 'third' as "data", 0 as "amount"

union all

select 'fourth' as "data", 500 as "amount"
```

Turn it into a pie chart visualisation and then tweak the values as you like. This should work regardless of which database you point metabase at.

### Expected behavior

I'd like to be able to configure it to not have a max % cap

### Logs

N/A

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.205-195.807.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "?",
      "tag": "vUNKNOWN",
      "hash": "?"
    },
    "settings": {
      "report-timezone": "Europe/London"
    }
  }
}
```

### Severity

Annoying because it's inconsistent and doesn't match other pie charts

**Comment by paoliniluis** [comment]
to reproduce:
1) create a SQL question
```
select 'first' as "data", 5 as "amount"
union all
select 'second' as "data", 5 as "amount"
union all
select 'third' as "data", 5 as "amount"
union all
select 'fourth' as "data", 500 as "amount"
```
2) save it as a pie chart
3) set the legend to be on the chart
![image](https://github.com/metabase/metabase/assets/1711649/b6304acf-51e3-43a6-8a68-49cc8a4d84ab)


percentages won't be shown

**Comment by perivamsi** [comment]
@alxnddr @EmmadUsmani does echarts fix this?

**Comment by alxnddr** [comment]
@perivamsi it is not directly related to visualization layer, the bug appears to be in the way we compute slices. We need to implement the new Pie correctly
