### ISSUE TITLE
No option to hide/show tabs in Interactive embedding as a parameter. header=false will hide all tabs and go to tab 1 by default

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#38429]
**Is your feature request related to a problem? Please describe.**
Setting `header=false` will hide tab selection and default to 1
In addition, I tried to put tab=x in the embedded URL and couldn't set the desired tab

**Describe the solution you'd like**
Have header=false not hide tabs in a dashboard, and instead have a new parameter that hides/shows tabs

**Describe alternatives you've considered**
Enabling header, but you might want the ability to hide one and not the other.

**How important is this feature to you?**
Requested by a customer, internal ticket [24697](https://metabase.zendesk.com/agent/tickets/24697)

**Additional context**
N/A

**Comment by albertoperdomo** [comment]
Turning this into a bug as it's not the expected behavior.
P2 because hiding the header should be compatible with using dashboards tabs.

**Comment by ignacio-mb** [comment]
Should have asked if it was or wasn't the intended behaviour, thanks @albertoperdomo
