### ISSUE TITLE
FE: add UI for uploading from collections list

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#38435]
[figma](https://www.figma.com/file/tLUjTffE2vTCRbQeb71HJQ/Allow-appends-on-existing-CSV-upload-models?type=design&node-id=1005-58551&mode=design&t=WqF2DT117ImHZ3VV-0)

![Screen Shot 2024-02-05 at 1 49 12 PM](https://github.com/metabase/metabase/assets/30528226/60cd8fbb-c388-4bf6-bf61-d28070c5a744)

![Screen Shot 2024-02-05 at 1 49 21 PM](https://github.com/metabase/metabase/assets/30528226/97a4931f-143e-414d-b5ee-39b874410163)

![Screen Shot 2024-02-05 at 1 49 48 PM](https://github.com/metabase/metabase/assets/30528226/1c22bf26-8399-45ad-ae0d-e692b368e7fc)

```[tasklist]
### Tasks
- [x] Create Model Selection Modal
- [x] Handle Errors
- [x] Handle Upload to new model
```

**Comment by calherries** [comment]
@iethree I've removed the 49 milestone from the epic to not label it a blocker, so if this issue is closed before 49 you should add it here
