### ISSUE TITLE
"Relative Date" dashboard filter doesn't seem to work

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3843]
On our own Stats instance, when trying to click the dropdown for a Relative Date filter, nothing happens. I've tried it on numerous dashboards with different cards.

**Comment by tlrobinson** [comment]
I can't reproduce this on stats or master.

**Comment by mazameli** [comment]
Hmm, I'm definitely still seeing this on both stats and a newly built version of master. I've been able to repro on Chrome, Safari, and Firefox, including in Incognito on Chrome. Can anyone else repro? Specifically, the steps are: edit a dashboard, add a relative date filter, hook it up to a card, save the dashboard, then try using the relative date filter. You should find that the relative date dropdown doesn't open up.

**Comment by kdoh** [comment]
I was able to reproduce this on stats yesterday as well.

**Comment by mazameli** [comment]
JS error in console reads: 
`app.bundle.js?f94be82…:94 Uncaught TypeError: Cannot read property 'split' of undefined`

**Comment by tlrobinson** [comment]
Oh I see, when you go to set the value. I thought you meant when adding a new one. Might have been broken in the recent date picker changes. I'll look.
