### ISSUE TITLE
Add connection impersonation to Redshift

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38445]
We support connection impersonation for Snowflake and Postgres. We can extend support to Redshift too.

It behaves slightly differently from Postgres as it uses `SET SESSION AUTHORIZATION` and passes usernames instead of roles.

[Product doc](https://www.notion.so/metabase/Add-impersonation-to-Redshift-5fd1d93fba3b4a9683241ad3729a9041?pvs=4)
```[tasklist]
### Tasks
- [x] [BE] Tweak driver to use `set session authorization`
- [x] [FE] Change copy: replace "role" with "user"
```

**Comment by marcoquerque** [comment]
In general, what are your thoughts on requiring the redshift user in metabase be a super user to use this?

**Comment by luizarakaki** [comment]
Redshift connection impersonation uses `SET SESSION AUTHORIZATION`.

To run this command, the connection must use superuser

**Comment by marcoquerque** [comment]
And what is our general thoughts on the metabase redshift user being a superuser? are we concerned from a security perspective - can we confidently say every query will use this?

**Comment by luizarakaki** [comment]
Queries from users in groups with impersonated connection, yes. But admins are never impersonated, so at least queries run by admin won't use this.

**Comment by calherries** [comment]
Pretty sure this is closed by https://github.com/metabase/metabase/pull/38530, so I'm closing this to get it into the release notes. Please yell at me if not
