### ISSUE TITLE
Issue with click Behavior and passing filters to custom destinations that are tabs of the same dashboard

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#38455]
### Describe the bug

Click Behavior between tabs within the same dashboard don't appear to be working. Specifically passing filters to a custom destination, which happens to be a tab of the same dashboard.

### To Reproduce

1.) Create two questions to place on a dashboard.

Question 1:
```
SELECT *
FROM player_salary
WHERE {{team}}
AND {{seasonID}}
```

Question 2:
```
SELECT *
FROM season_gamelog
WHERE {{team_abv}}
 AND {{seasonID}}
 AND game_date = '2007-03-23'
```

<br>
<br>

2.) Place both questions on a dashboard in their own individual tabs, with the same filters being applied to each one.
Dashboard 1: **Dash Link**

<img width="549" alt="Screenshot 2024-02-05 at 3 51 12 PM" src="https://github.com/metabase/metabase/assets/17398657/de51674c-b251-4928-bee8-bbfd8996eaf4">

<img width="557" alt="Screenshot 2024-02-05 at 3 51 35 PM" src="https://github.com/metabase/metabase/assets/17398657/10418103-2061-4a93-a1b2-5006c6b42889">

<img width="558" alt="Screenshot 2024-02-05 at 3 51 50 PM" src="https://github.com/metabase/metabase/assets/17398657/37a4ffa1-d135-46e8-ad2d-c96b73f6f0ae">

<img width="558" alt="Screenshot 2024-02-05 at 3 51 55 PM" src="https://github.com/metabase/metabase/assets/17398657/e771c1a7-5fe5-4cb8-b8be-ac9adeec762a">

<br>
<br>

3.) Create a duplicate of this dashboard. 
Dashboard 2: **Dash Link - Duplicate**

<br>
<br>

4.) Create Click Behavior that will use a column from Tab 1 as a filter to be used for Tab 2.
This Click Behavior is going from **Tab 1** of **Dash Link**(original dashboard) to **Tab 2** of **Dash Link - Duplicate**(duplicate dashboard).

<br>
<br>
<br>
<br>

<img width="1346" alt="Screenshot 2024-02-05 at 3 53 23 PM" src="https://github.com/metabase/metabase/assets/17398657/a7b19927-653a-483a-94c3-6bed965cc4c1">

<br>
<br>

5.) When starting from **Dash Link** (original) and clicking on the column **‘tm'**, the filter is applied and **Tab 2 of Dash Link - Duplicate** dashboard is in the url.

<img width="840" alt="Screenshot 2024-02-05 at 3 57 02 PM" src="https://github.com/metabase/metabase/assets/17398657/9ad986db-68b8-4406-90f3-f4ac679a901c">

<br>
<br>
<br>
<br>

<img width="840" alt="Screenshot 2024-02-05 at 3 58 19 PM" src="https://github.com/metabase/metabase/assets/17398657/c000afce-c0be-41d6-aa79-8f869d5ac544">

<br>
<br>
<br>
<br>

6.) This Click Behavior is going from **Tab 1** of **Dash Link - Duplicate(duplicate)** to **Tab 2** of **Dash Link - Duplicate(duplicate)**.

<img width="1346" alt="Screenshot 2024-02-05 at 3 54 33 PM" src="https://github.com/metabase/metabase/assets/17398657/8ce91796-837b-4b38-babc-e5b84f7eb637">

<br>
<br>

When starting from **Dash Link - Duplicate** dashboard and clicking on the column **‘tm'**, the filter is applied, but to Tab 1 and the url reflects this.

<img width="840" alt="Screenshot 2024-02-05 at 4 11 43 PM" src="https://github.com/metabase/metabase/assets/17398657/d17c88d0-314f-4af4-bb76-40cdf5f8e67f">

### Expected behavior

For the redirection to be sent to the desired tab of the same dashboard

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.49-linuxkit-pr",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-29",
      "tag": "v1.48.4",
      "hash": "62145b0"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2 - Speaking with a couple customers who have the expectation of being able to go to different tabs in the same dashboard

**Comment by perivamsi** [comment]
@JesseSDevaney can you please backport this to 49?

**Comment by JesseSDevaney** [comment]
@perivamsi 

> @JesseSDevaney can you please backport this to 49?

It was automatically backported to 49
- https://github.com/metabase/metabase/pull/39474

I just forgot to throw the Milestone 0.49 marker on it. Just did :heavy_check_mark:
