### ISSUE TITLE
Failure to see the postgres schemas when apply permissions (ERROR: duplicate key value violates unique constraint)

### ISSUE THREAD

**Issue by mamcx** [metabase/metabase#38454]
**Describe the bug**

I upgrade metabase and [replace the Jdk](https://github.com/NixOS/nixpkgs/issues/215562#issuecomment-1910173978) so I can download excel files, but then after this is impossible to set permission of `group = pg schema`.

When I look at `/admin/permissions/data/group/16/database/2` the schemas are not displayed as before.

Then I see in the logs:

```bash
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1080]],
 :cause
 "ERROR: duplicate key value violates unique constraint \"permissions_revision_pkey\"\n  Detail: Key (id)=(30) already exists.",
```

**Logs**

[error.log](https://github.com/metabase/metabase/files/14172397/error.log)

**To Reproduce**
1. Go to '/admin/permissions/data/group/16'
2. Click on a group and select 'Granular'
3. See that in `Permissions for  Disfami group Sales` there are not schemas listed.

**Severity**

I can't add more companies for the app.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.7+7-nixos",
    "java.vendor": "N/A",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "17.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.7+7-nixos",
    "os.name": "Linux",
    "os.version": "6.7.1",
    "user.language": "es",
    "user.timezone": "America/Bogota"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
1) downgrade to Java 11
2) there seems to be a corruption in your DB, so back up your db and do "DELETE FROM permissions_revision_pkey WHERE id=30"

then upgrade to v48.4

**Comment by mamcx** [comment]
After doing this, I still can't see the schemas

**Comment by paoliniluis** [comment]
@mamcx what do you see after doing the sync?

**Comment by mamcx** [comment]
I do. I upgrade the VM with more RAM, look like it was dying by resources.
