### ISSUE TITLE
Doesn't show new columns in Metabase after added into Snowflake

### ISSUE THREAD

**Issue by mlahlouh** [metabase/metabase#38467]
**Describe the bug**
One of my sources is Snowflake, I had multiple tables in Snowflake and built a dashboard with multiple questions, I added new columns to the tables but I don't see these columns in the table, filter, or summarization, when I run native SQL query `SELCET *` it returns all columns normally.

I did:
- Sync database schema now on database level.
- Re-scan field values now on database level.
- Re-scan this table on table level.
- Discard cached field values on table level.

And didn't fixed.

**Logs**
No error here:

[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:50:11+03:00 DEBUG metabase.server.middleware.log POST /api/table/26/discard_values 200 17.4 ms (5 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (1 idle, 0 queued) (136 total active threads) Queries in flight: 0 (0 queued)
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:50:14+03:00 DEBUG metabase.server.middleware.log POST /api/table/26/rescan_values 200 5.2 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (1 idle, 0 queued) (136 total active threads) Queries in flight: 0 (0 queued)
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:50:54+03:00 DEBUG metabase.server.middleware.log GET /api/database/2 200 8.7 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (2 idle, 0 queued) (134 total active threads) Queries in flight: 0 (0 queued)
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:51:08+03:00 DEBUG metabase.server.middleware.log POST /api/database/2/rescan_values 200 6.6 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (1 idle, 0 queued) (136 total active threads) Queries in flight: 0 (0 queued)
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:51:08+03:00 INFO metabase.sync.util STARTING: Cache field values in snowflake Database 2 'Snowflake'
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:51:08+03:00 INFO metabase.sync.util STARTING: step 'delete-expired-advanced-field-values' for snowflake Database 2 'Snowflake'
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:51:08+03:00 INFO metabase.sync.util FINISHED: step 'delete-expired-advanced-field-values' for snowflake Database 2 'Snowflake' (823.8 ms)
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:51:08+03:00 INFO metabase.sync.util STARTING: step 'update-field-values' for snowflake Database 2 'Snowflake'
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:51:15+03:00 INFO metabase.sync.util FINISHED: step 'update-field-values' for snowflake Database 2 'Snowflake' (6.5 s)
[ce5d18f7-454b-472a-be90-fe0dd2c04518] 2024-02-06T16:51:15+03:00 INFO metabase.sync.util FINISHED: Cache field values in snowflake Database 2 'Snowflake' (7.4 s)

**To Reproduce**
1. Add new column to snowflake table
2. Rescan table in Metabase 
3. explore the table.
4. No new columns here

**Expected behavior**

**Screenshots**

**Severity**
Actually, its block building dashboard 

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "6.2.0-1012-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-19",
      "tag": "v0.48.1",
      "hash": "a8302d4"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
move to 48.4, force a sync, and report back if things haven't appeared
