### ISSUE TITLE
Query executed in Metabase is way slower than when executed directly in database

### ISSUE THREAD

**Issue by pk044** [metabase/metabase#38464]
### Describe the bug

We're running a pretty heavy query that uses: CTEs, aggregation functions, window functions, UNIONs, fetching data from a Materialized View that uses pretty much the same features. It operates on tables that have ~50GB of data in total. When I run the same native query in Metabase it takes around ~4 minutes to complete, while the exact same query executes in 3 seconds in DBeaver.

Metabase is deployed on ECS on Fargate.
 
What I tried:
- Adding more resources to Metabase container - it's currently set at 2 vCPUs and 4GB of RAM. Haven't noticed a change.
- Downgrading from v0.48.3 (I found this issue on this version) to v0.47.6.
-  adding LIMIT 1 (wasn't sure if this was some serialization issue caused by big result set) - no change.

What is interesting is that other less complicated queries execute in an acceptable time (the difference isn't that noticeable), even though they operate on the same tables.

### To Reproduce

Run a query with aggregate and window functions in Metabase and compare the execution time to e.g. DBeaver.

### Expected behavior

Execution time in Metabase should be similar to direct execution time  

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.201-191.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v0.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

it heavily slows down the productivity of our client

**Comment by paoliniluis** [comment]
Is DBeaver fetching the same amount of rows than what Metabase is pulling? are you passing parameters to the query?

if you use a SQL question the query should take the exact amount of time, as we send the query as it is to the DB

**Comment by pk044** [comment]
> Is DBeaver fetching the same amount of rows than what Metabase is pulling? 
yeah - I'm adding `LIMIT 2` at the end of the query
> are you passing parameters to the query?
even if I hardcode the parameters and execute the **exact same** query in both clients the difference is still there.

**Comment by paoliniluis** [comment]
can you see how much time the API call takes in Metabase? As you can imagine we need to reproduce this and it would be pretty difficult.

can you post explain analyze logs and more information?

**Comment by pk044** [comment]
@paoliniluis it was a PG settings-related issue actually - the value for `work_mem` for the Metabase user was set to way lower than other users in the DB, which resulted in choosing a inefficient query plan. 

analyzing the `EXPLAIN` output helped out, thanks for the tip and the quick replies!
