### ISSUE TITLE
Feature Request: Dashboard export

### ISSUE THREAD

**Issue by aagarwal-gtr** [metabase/metabase#3847]
Ability to download the current snapshot of a dashboard. Maybe download all the raw data for all the cards into a single csv or get all the raw data as separate sheets in a xls file / export gifs of the current graphs.

Use case:
We look at some metrics every thursday. So if i put them in a dashboard, i can come back every thursday to look at last weeks stuff. But I want to be able to archive this weekly report for this quarter so I can track progress. If i had the ability to do this I could download it every thursday and archive it locally.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by LukeAbell** [comment]
+1

**Comment by moumny** [comment]
Not really sure why they need this, but our users keep requesting this feature.
My guess is that for most of them they interact exclusively with dashboards.

**Comment by camsaul** [comment]
Related: #3770

**Comment by rylincoln** [comment]
I have setup a sqlite database source that syncs data from another system(ms access based but can't get away from that ...)   I then setup a dashboard with 2 tables and a filter button so the "users" can filter data based on a common field between the 2 tables hoping they could then simply export from the dashboard.  Turns out they can't :(  would love to see download/export icon in top right corner of panes in a dashboard to export the currently filtered view of data.

**Comment by ihackalot** [comment]
I'm also interested in this. Looking for an easy way to apply questions and dashboard settings to different databases without need to redo everything from scratch. 

Use case: I collect a bunch of data related to cities and each city provides same schema and obviously different data. How can I apply the same questions of city 1 to city 2 and so forth?

**Comment by sunshineo** [comment]
I believe a lot of people need this feature badly. My current workaround as a programmer would be use chrome headless browser https://developers.google.com/web/updates/2017/04/headless-chrome to open the public link of the chart and save it as a image/pdf.

Several issues with this approach:
1. You need to know programming
1. You need separate computing resource to run the program
1. The "Question/Card" need to be public
1. The email integration is wasted. You have to email yourself after save.

**Comment by rachid252** [comment]
+1

**Comment by mvrabel** [comment]
maybe related to: #5295

**Comment by mvrabel** [comment]
@aagarwal-gtr. 
IMHO Metabase is an analytic tool and It's not meant to be a backup tool. 
If you want to track changes then the easiest way would be to aggregate data, insert the data (KPI) one a week into a table and then use Metabase to view the data.

**Why it would be cumbersome to compare expoted data:**
If you exported the dashboard then you would need to manually compare 2 (or more) static grafs or tables. 
Imagine the process of comparing data from the last 4 months. 
+ you would need to write a script that somehow downloads all dashboards weekly + the devs would probably need to implement this feature (which would take some time)

**Why it would be easier to create a script that aggregates the data that you want to track and stores them into a separate table:**
You would have all data that you need in one table. You save space,time to analyze it, it's easier to analyze with metabase etc.

I'm not saying that it's a bad idea, only that there are better ways to archive your goal.

e.g. This article: (it was the first one that came up)
https://www.linkedin.com/pulse/20140826130303-52920152-warehousing-kpis-what-to-measure-and-what-to-improve

**Comment by sunshineo** [comment]
@mvrabel Nice comment. You provided us a solid workaround. However I do feel not providing this in Metabase is like a bank website refuses to generate monthly statement and allow user to download, instead requires user to come to the site on 1st of every month to see what happened.

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by mvrabel** [comment]
@sunshineo 
I disagree with your comparison to a bank. Metabase is an analytic tool -> by definition it's a tool which helps you analyze/understand your data. You want metabase to create new data from your existing data.
Of course, if enough people will reqest this feature then metabase devs will program it. 

**But there are problems with this approcah:**
**1. Your data/reports will be platform dependent**. What would happen if metabase would stop beeing developed ?
Now you need to search for new tools that will do those reports. What if this new tool deals with data in a different way ? Now you would get different reporst that are not compatible with old metabase reports. What if you dont find anything that could replace metabase or it costs thousands of dollars. 
**2. What if you want to create more complex reports than simple differences of 2 tables ?** 
Now you need to write SQL **OR** wait for half a year for metabase devs to implement this feature **OR** (if this feature would be implemented) create this report yourself in metabase which would take you about the same time as writing the thing is SQL.
 Even worst what if there will be more demand for other features and this feature for more complex reporting will never be implmented ?
**3. What if there's a bug in the report creating feature ?** Now you need to wait for the fix and use some workaround in meantime.

On the other hand if you take the classical approach to data and create the reports yourself then you gain:
- You can create any report you want
- Your data are platform independent
- You know exactly how you got the data that are in your report

**Let's have a look at your use case:**

> We look at some metrics every thursday. So if i put them in a dashboard, i can come back every thursday to look at last weeks stuff. But I want to be able to archive this weekly report for this quarter so I can track progress. If i had the ability to do this I could download it every thursday and archive it locally.

1. You create a table.
2. Create SQL insert with the current data. 
3. If you are using linux you can use crontab to periodically execute scritps .. i.e. "crontab -e"
4. write this -  0 0 8 * * ? root weekly_insert.sh
    postgres example
    #weekly_insert.sh
    #!/bin/bash
    psql -d database -U insert_user report_1.sql
    psql -d database -U insert_user report_1.sql
    
5. Now you can analyze weekly inserted data in metabase.

- + This feature request is about exporting dashboard data. If you want metabase to create reports for you from your existing data then it would be appropriate to create new request or change the name of this one.

I'm avare that a lot of people would love to have this feature but there are drawbacks. 
Of course there are also drawback to "my" approach:
- You need to keep the sql up-to-date
- SQL is not really readable

Pick the method that suits you best but IMHO it's easier to write sql.

Hope I helped you :)

Most important, correct me when I'm wrong :)

**Comment by goodfella1408** [comment]
This is a critical feature (blocker) for us too.We were planning to use metabase for customer/client facing  dashboards and support for excel download is part of the contract !

**Comment by rNianios** [comment]
@goodfella1408 Then you might want to come in contact with metabase devs and see if they are up to receive a payment (is it even possible?) to sponsor this feature.

Especially when things like a contract is at stake.

**Comment by goodfella1408** [comment]
Well the number of thumbs up on this feature must be a good motivation in itself :) Having said that we did approach the metabase team for some paid features/bugs through the metabase dev network !
Business folks are heavy users of excel .They love and use all the cool features it provides like functions,pivot,transpose etc which is why in any BI demo one of the first questions they ask is can I do a excel download .This feature should be made optional so that folks are free to use it if they want - I am sure if its in place it would be widely used . I saw the download widget in the create question flow and thought that it will be there on the dashboards too - not finding it was a surprise .

**Comment by goodfella1408** [comment]
I am planning to work on this feature (basically putting the download widget thats available on questions , in questions on dashboards too ).I am assuming that since download feature is available in questions - it should be possible/not very hard to put the same download widget in questions added on a dashboard  . Please let me know if that is not the case .

**Comment by goodfella1408** [comment]
PR for download functionality on dashboards (only on embedded dashboards for now) -
https://github.com/metabase/metabase/pull/6322/commits/c8bb27b704d43d12629beb39e6be277510581d81

**Comment by salsakran** [comment]
@mazameli @kdoh mind chiming in on the UX for this and the PR @goodfella1408 linked to?

**Comment by camsaul** [comment]
Implemented by #7315
