### ISSUE TITLE
Progress bar visualization's goal input doesn't let you type commas

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3849]
~If I type `10,000` or `10.000`, Metabase treats it as `10`. This sucks if I'm in the habit of typing numbers with comma/period separators, or if I'm working with very small decimal number goals, like `0.00025`, or goals that include decimal values.~ (This has been fixed.)

Progress bar goals don't let you type in commas, though you can paste in values that contain commas and the input box strips them out. This is mildly annoying for folks like us in the US who type like `1,000.25`, but maybe a bit more annoying for people who write `1.000,25`.

<img width="1101" alt="screen shot 2016-12-01 at 10 26 50 am" src="https://cloud.githubusercontent.com/assets/2223916/20806703/d323921c-b7b0-11e6-9e4b-25f0aecb909b.png">

**Comment by mazameli** [comment]
Bump. This still feels dumb and also seems like it would be relatively simple to fix, but what do I know? :)

**Comment by paulrosenzweig** [comment]
@mazameli It looks like this works now, but maybe I'm misunderstanding.

I see a `<input type="number"`, which won't let me type a comma. However, I'm still able to copy/paste in values that contain commas. That seems like the right behavior to me?

![image](https://user-images.githubusercontent.com/691495/57336076-b609c180-70f2-11e9-81f4-f1fe8d131d76.png)

**Comment by mazameli** [comment]
@paulrosenzweig Yeah, it looks like you still can't type commas, though you can paste values that include them like you said. More importantly you _can_ now type in periods, so decimal values work. I still feel like you should be able to type a comma in here but it's like a P4.

Separately, maybe our localization settings should be smart enough to know that if I change my system settings to use periods for thousands separators and commas for decimals when displaying results, that I probably want to have that be the case for input boxes as well. Not super important relative to other things in the backlog, but it would be friendlier.

**Comment by tlrobinson** [comment]
It seems like `type="number"` doesn't support thousands separators at all, and picks decimal separators based on the browser locale, so I'm not sure there's anything else we can do unless we want to not use `type="number"`.

**Comment by brunobergher** [comment]
Very minor, no traction, closing.
