### ISSUE TITLE
Getting fields in (Redshift) is slow

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#38492]
### Describe the bug
(leaving the old description on the Additional context section of the issue)

Before 48, we used to go table by table on each schema checking for permissions. This was fixed already (checked on my machine and it takes 10 min in v48, super fast to what it was before), but now the problem is on getting fields: for every field we will go one by one inserting those into the DB which takes a huge amount of time

### To Reproduce

1) just connect a redshift cluster with Metabase and see the sync logs, it takes a massive amount of time for lots of tables

### Logs

Above

### Information about your Metabase installation

```JSON
I believe it's been like this forever
```

### Severity

P1

### Additional context

OLD ISSUE here:
Seems that when we check for SELECT we do
```
2024-02-06 22:01:52,345 TRACE sync.describe-database :: Checking for SELECT privileges for "federated_sample1"."_metabase_metadata" with query ["SELECT TRUE AS \"_\" FROM \"federated_sample1\".\"_metabase_metadata\" WHERE 1 <> 1 LIMIT 0"]
2024-02-06 22:01:53,047 TRACE sync.describe-database :: [redshift] SELECT TRUE AS "_" FROM "federated_sample1"."_metabase_metadata" WHERE 1 <> 1 LIMIT 0
2024-02-06 22:01:53,965 TRACE sync.describe-database :: SELECT privileges confirmed
2024-02-06 22:01:53,969 TRACE sync.describe-database :: Checking for SELECT privileges for "federated_sample1"."accounts" with query ["SELECT TRUE AS \"_\" FROM \"federated_sample1\".\"accounts\" WHERE 1 <> 1 LIMIT 0"]
2024-02-06 22:01:54,683 TRACE sync.describe-database :: [redshift] SELECT TRUE AS "_" FROM "federated_sample1"."accounts" WHERE 1 <> 1 LIMIT 0
2024-02-06 22:01:55,472 TRACE sync.describe-database :: SELECT privileges confirmed
2024-02-06 22:01:55,476 TRACE sync.describe-database :: Checking for SELECT privileges for "federated_sample1"."analytic_events" with query ["SELECT TRUE AS \"_\" FROM \"federated_sample1\".\"analytic_events\" WHERE 1 <> 1 LIMIT 0"]
2024-02-06 22:01:56,135 TRACE sync.describe-database :: [redshift] SELECT TRUE AS "_" FROM "federated_sample1"."analytic_events" WHERE 1 <> 1 LIMIT 0
2024-02-06 22:01:57,037 TRACE sync.describe-database :: SELECT privileges confirmed
```
...

Every query needs a separate connection and it can take 1 second or more depending where you are.

There's a way to make this more efficient
```
WITH tables_and_views as (SELECT schemaname
                               , objectname
                               , usename
                               , HAS_TABLE_PRIVILEGE(usrs.usename, fullobj, 'select') AND
                                 has_schema_privilege(usrs.usename, schemaname, 'usage') AS sel
                          FROM (SELECT schemaname,
                                       't'                          AS obj_type,
                                       tablename                    AS objectname,
                                       schemaname + '.' + tablename AS fullobj
                                FROM pg_tables
                                WHERE schemaname not in ('pg_internal', 'pg_automv', 'information_schema', 'pg_catalog')
                                UNION
                                SELECT schemaname,
                                       'v'                         AS obj_type,
                                       viewname                    AS objectname,
                                       schemaname + '.' + viewname AS fullobj
                                FROM pg_views
                                WHERE schemaname not in
                                      ('pg_internal', 'pg_automv', 'information_schema', 'pg_catalog')) AS objs
                             , (SELECT * FROM pg_user) AS usrs),
     external_objects as (SELECT schemaname,
                                 objectname,
                                 usename,
                                 'true' AS sel
                          FROM (SELECT schemaname,
                                       't'                          as obj_type,
                                       tablename                    as objectname,
                                       schemaname + '.' + tablename AS fullobj FROM SVV_EXTERNAL_TABLES)
                              AS objs
                             , (SELECT * FROM pg_user) AS usrs)

SELECT *
FROM tables_and_views
UNION ALL
SELECT *
FROM external_objects
```
(extracted from https://stackoverflow.com/questions/18741334/how-do-i-view-grants-on-redshift with a slight tweak for external objects as we trust that the user has select priviledges there, as otherwise the connection between servers could not have been made)

**Comment by paoliniluis** [comment]
cc @qnkhuat in case you want to take a look

**Comment by qnkhuat** [comment]
Which version are you testing this on? https://github.com/metabase/metabase/pull/37439 should already fix this for redshift

**Comment by paoliniluis** [comment]
@qnkhuat 48.5 release
![image](https://github.com/metabase/metabase/assets/1711649/2930706a-3b98-43d2-891a-40e9ea3da17a)
![image](https://github.com/metabase/metabase/assets/1711649/19bcfcf4-f2e1-4bd9-b7e7-2972204eaab5)

**Comment by paoliniluis** [comment]
Adding a few findings that I was able to get investigating 46, 47 and 48:
1) v47 takes more time than 46 for every single permission change. On 46 it took 366ms for every query, while in 47 it takes 490 ms
Here are the logs and the time differences
[metabase46-filtered.log](https://github.com/metabase/metabase/files/14234629/metabase46-filtered.log)
[metabase47-filtered.log](https://github.com/metabase/metabase/files/14234630/metabase47-filtered.log)
[time-differences46.txt](https://github.com/metabase/metabase/files/14234638/time-differences46.txt)
[metabase47-filtered.log](https://github.com/metabase/metabase/files/14234639/metabase47-filtered.log)
2) in v48 we no longer log the permission check lines with the same logging config we have in 46-47, so I wasn't able to check the performance of 48 on permission checks

I also tested using a single schema with an absurd amount of tables: it works super fast... so it seems that the problem is when we have lots of schemas, and lots of tables inside those schemas

cc @qnkhuat sorry for telling you above that the logs I saw were in 48.5, clearly that was not the version I was running as I'm not able to see that right now

**Comment by paoliniluis** [comment]
Even if we make the permissions check faster, then the describe table, describe field and all subsequent operations will be slow as it goes 1 by 1, e.g. https://github.com/metabase/metabase/issues/38644

**Comment by calherries** [comment]
@paoliniluis since https://github.com/metabase/metabase/pull/37439 was merged we only do one query for non-external tables in a database. We are still doing one query per table for external tables though, so we can incorporate your subquery on `SVV_EXTERNAL_TABLES` that you included above and it should be a lot speedier.

**Comment by paoliniluis** [comment]
@calherries thanks, the test to pass here is to sync the database named "massive" in our dev instance in the shortest amount of time. I've tried to sync it with 48.5 and it's been syncing for a day with no results

**Comment by calherries** [comment]
It's probably not just getting fields that could do with optimizing. Here are the timings from the major steps while syncing the much smaller dev database:
```
sync-fields 2.5 mins
sync-fks 1.4 mins
fingerprint-fields 1.9 mins
update-field-values 4.3 mins
```

Syncing fields seems to be the longest of the analyze-data step, but syncing foreign keys is on the same order of magnitude.

**Comment by calherries** [comment]
@paoliniluis do you know if there was a script used to create massive? Would be nice to have a small version to test on

**Comment by paoliniluis** [comment]
@calherries yup, here it is:

use bun and run:
- bun init
- bun install pg
- bun install random-words
- bun install sequelize

then just run the following script with bun and leave it till it fails:
```
const { Sequelize } = require('sequelize');
import { generate } from "random-words";

const config = {
  dialect: 'postgres',
  host: 'redshifthostname',
  port: 5439,
  database: 'massive',
  username: 'username',
  password: 'password',
  dialectOptions: {
    ssl: {
      require: true,
      rejectUnauthorized: false
    },
    clientMinMessages: 'ignore'
  },
  standardConformingStrings: false
};


const sequelize = new Sequelize(config);

let counter = 0;
// let schema_name = generate().concat("_1");
let schema_name = 'public'

while (true) {
  try {
    if (counter == 10) {
      counter = 0;
      // schema_name = generate().concat(Math.floor(Math.random() * 100) + 1);
      schema_name = 'public'
    }
    let table_name = generate().concat(Math.floor(Math.random() * 100) + 1);
    // await sequelize.query(`CREATE SCHEMA IF NOT EXISTS "${schema_name}";`);
    await sequelize.query(`CREATE TABLE IF NOT EXISTS "${schema_name}"."${table_name}" (
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" SMALLINT,
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" VARCHAR(255),
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" CHAR(10),
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" BIGINT,
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" SMALLINT,
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" DECIMAL(10,2),
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" REAL,
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" DOUBLE PRECISION,
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" BOOLEAN,
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" DATE,
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" TIMESTAMP,
      "${generate().concat(Math.floor(Math.random() * 100) + 1)}" TIMESTAMPTZ
    );`);
    await sequelize.query(`INSERT INTO "${schema_name}"."${table_name}" VALUES 
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00'),
    (1, 'test', 'test', 1, 1, 1.1, 1.1, 1.1, true, '2021-01-01', '2021-01-01 00:00:00', '2021-01-01 00:00:00')
    ;`);
    counter++;
  } catch (err) {
    console.log(err);
  }
}
```

**Comment by calherries** [comment]
I found two causes: (1) querying each table’s metadata one-by-one in series and (2) calling `sql-jdbc.execute/do-with-connection-with-options` once for every table, which is super expensive (>500 ms per table). After we fix these two things, the `sync-fields` should take >90% less time for syncing this database on my laptop. We can apply the same logic to `sync-fks` too. This isn’t a redshift specific issue so solving it will solve it for all DBs. I’m pretty sure it’ll solve our redshift flake issues too. The bad news: it will require a pretty big redesign of the sync code of similar in scope to the last big sync refactor, [3 years ago](https://github.com/metabase/metabase/pull/13746).

btw, https://github.com/metabase/metabase/issues/38644 will help but the biggest problem is that we're not using our connections effectively

**Comment by calherries** [comment]
The plan is to land these two PRs and backport them to 49:
#38828
#38970 

Backporting to earlier versions is also possible and might not be much effort, given the stability of the sync code.

I give a median time estimate of one week to complete these two PRs.

These will make redshift schema sync fast, but only for redshift, and not the fingerprint / field values steps. 

We can then do the same thing for other drivers that we want to make faster, such as bigquery.

**Comment by calherries** [comment]
The first of these, https://github.com/metabase/metabase/pull/38970, is in the 49 branch.
The second, https://github.com/metabase/metabase/pull/38828/, is currently in review. With this second branch I was able to sync the metadata of "massive" in 5 minutes from my laptop.

**Comment by calherries** [comment]
Closed by 
https://github.com/metabase/metabase/pull/38970 (to be released in 49.0)
https://github.com/metabase/metabase/pull/38828 (this didn't quite make 49.0, but will be in 49.1)

**Comment by paoliniluis** [comment]
I just tested syncing the massive database on my laptop. The initial sync will ingest tables very fast but it will take a LOT of time to insert the fields, the code to insert the fields from zero is still sequential and it ingests the fields at around 12 fields per second.

As the massive database has 121051 fields, the total sync time is 10087 seconds or 168 minutes or around 3 hours. Yes, we made an improvement of 10 hours to 3 hours, but I think we can take this to minutes or at least 1 hour (https://github.com/metabase/metabase/issues/38973)

Reopening to keep track that there's still room for improvement

**Comment by paoliniluis** [comment]
removing the escalation tag

**Comment by calherries** [comment]
closing again, Luiggi was using the wrong version, phew :)

**Comment by paoliniluis** [comment]
yes yes yes
