### ISSUE TITLE
Allow more decimal places in table view

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3850]
Currently, we only display up to two decimal places in the Table view. For Scalar view, we've added the option to increase the number of decimal places, but we could also add this to the options for Table view.

We received this request on Discourse here: http://discourse.metabase.com/t/show-more-decimals-in-view/419/3

**Comment by flamber** [comment]
Hi @mazameli Wasn't this fixed as part of the big formatting changes in 0.30 and 0.31?

**Comment by mazameli** [comment]
@flamber Yep, good call! This was implemented in version 0.31. Thanks for all you're doing for the Metabase community!

**Comment by surya-addala** [comment]
@mazameli @flamber 
is this issue solved and should we update any setting on our enterprise cloud instance to enable this? I'm still having this issue where the decimals are being cut down to just 2 places. Screenshot attached for your reference. The score value from my query result is supposed to be a 6 decimal value but it is cutting it down to just 2.
<img width="998" alt="Screenshot 2024-07-02 at 11 02 02 PM" src="https://github.com/metabase/metabase/assets/85649494/070ea237-e6d4-4497-af2c-a9fcfcc21e29">
