### ISSUE TITLE
Dashboard filter of type ID may return wrong Entity name if ID is not unique in the source table

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38517]
### Describe the bug

On Audit v2, the underlying Content table is a `UNION` of questions, dashboards, events, collections. Because of that, the ID column isn't unique.

When we are retrieving entity names to display on the filter, looks like we select the name randomly.

<img width="621" alt="image" src="https://github.com/metabase/metabase/assets/32561114/4aee05d6-428c-44e9-b4ff-f8f889f2035f">

In this case, the dashboard 1907 is called `Metabase Business`, but the filter shows `Monthly Activated Hosting Logo...`

### To Reproduce

1. Go to https://stats.metabase.com/dashboard/2107-dashboard-overview
2. Filter dashboard ID 1907
3. Get wrong name in the filter widget

### Expected behavior

If there are multiple matches, we shouldn't show any value

### Information about your Metabase installation

```JSON
Master
```

### Severity

P2~P3

### Additional context

More like a P2 because it impacts audit v2

**Comment by cdeweyx** [comment]
Getting the correct name now, @luizarakaki could you try again to gut check this. In the meantime, I'm going to close this as already fixed.
