### ISSUE TITLE
issue when  taking build 

### ISSUE THREAD

**Issue by sundarrajan13** [metabase/metabase#38539]
Build frontend with MB_EDITION=oss
    Run 'yarn' to download javascript dependencies
      CI run: enforce the lockfile
      $ "yarn" "--frozen-lockfile"
        yarn install v1.22.19
        $ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
        [1/5] Validating package.json...
        [2/5] Resolving packages...
        warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
        warning Resolution field "set-value@4.0.1" is incompatible with requested version "set-value@^2.0.0"
        warning Resolution field "unset-value@2.0.1" is incompatible with requested version "unset-value@^1.0.0"
        warning Resolution field "set-value@4.0.1" is incompatible with requested version "set-value@^2.0.1"
        warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^1.0.1"
        warning Resolution field "nth-check@2.0.1" is incompatible with requested version "nth-check@^1.0.2"
        warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
        warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
        warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^1.0.1"
        warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^6.0.1"
        [3/5] Fetching packages...
        [4/5] Linking dependencies...
        warning " > @storybook/react@6.5.15" has unmet peer dependency "require-from-string@^2.0.2".
        warning " > css-loader@1.0.1" has incorrect peer dependency "webpack@^4.0.0".
        warning " > mochawesome@7.1.3" has unmet peer dependency "mocha@>=7".
        [5/5] Building fresh packages...
        $ husky install
        fatal: detected dubious ownership in repository at '/home/node'
        Done in 1113.01s.
Step failed: Running build steps for Community (OSS) Edition version UNKNOWN: version, translations, frontend, licenses, drivers, uberjar
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "Running build steps for Community (OSS) Edition version UNKNOWN: version, translations, frontend, licenses, drivers, uberjar",
   :data {},
   :at [metabuild_common.steps$do_step invokeStatic "steps.clj" 88]}
  {:type clojure.lang.ExceptionInfo,
   :message "Build frontend with MB_EDITION=oss",
   :data {},
   :at [metabuild_common.steps$do_step invokeStatic "steps.clj" 88]}
  {:type clojure.lang.ExceptionInfo,
   :message "Run 'yarn' to download javascript dependencies",
   :data {},
   :at [metabuild_common.steps$do_step invokeStatic "steps.clj" 88]}
  {:type clojure.lang.ExceptionInfo,
   :message "$ \"yarn\" \"--frozen-lockfile\"",
   :data {},
   :at [metabuild_common.steps$do_step invokeStatic "steps.clj" 88]}
  {:type clojure.lang.ExceptionInfo,
   :message "Timed out after 900000 ms.",
   :data {},
   :at [metabuild_common.shell$deref_with_timeout invokeStatic "shell.clj" 22]}],
 :trace
 [[metabuild_common.shell$deref_with_timeout invokeStatic "shell.clj" 22]
  [metabuild_common.shell$deref_with_timeout invoke "shell.clj" 19]
  [metabuild_common.shell$sh_STAR_$fn__1706 invoke "shell.clj" 66]
  [metabuild_common.steps$do_step invokeStatic "steps.clj" 85]
  [metabuild_common.steps$do_step invoke "steps.clj" 79]
  [metabuild_common.shell$sh_STAR_ invokeStatic "shell.clj" 45]
  [metabuild_common.shell$sh_STAR_ doInvoke "shell.clj" 27]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabuild_common.shell$sh invokeStatic "shell.clj" 75]
  [metabuild_common.shell$sh doInvoke "shell.clj" 70]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [build$build_frontend_BANG_$fn__19502$fn__19503 invoke "build.clj" 32]
  [metabuild_common.steps$do_step invokeStatic "steps.clj" 85]
  [metabuild_common.steps$do_step invoke "steps.clj" 79]
  [build$build_frontend_BANG_$fn__19502 invoke "build.clj" 28]
  [metabuild_common.steps$do_step invokeStatic "steps.clj" 85]
  [metabuild_common.steps$do_step invoke "steps.clj" 79]
  [build$build_frontend_BANG_ invokeStatic "build.clj" 27]
  [build$build_frontend_BANG_ invoke "build.clj" 22]
  [build$fn__19527 invokeStatic "build.clj" 94]
  [build$fn__19527 invoke "build.clj" 93]
  [build$build_BANG_$fn__19545 invoke "build.clj" 123]
  [metabuild_common.steps$do_step invokeStatic "steps.clj" 85]
  [metabuild_common.steps$do_step invoke "steps.clj" 79]
  [build$build_BANG_ invokeStatic "build.clj" 112]
  [build$build_BANG_ invoke "build.clj" 102]
  [build$build_cli$fn__19557 invoke "build.clj" 131]
  [metabuild_common.entrypoint$do_exit_when_finished_nonzero_on_exception invokeStatic "entrypoint.clj" 7]
  [metabuild_common.entrypoint$do_exit_when_finished_nonzero_on_exception invoke "entrypoint.clj" 5]
  [build$build_cli invokeStatic "build.clj" 130]
  [build$build_cli invoke "build.clj" 126]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [clojure.run.exec$exec invokeStatic "exec.clj" 48]
  [clojure.run.exec$exec doInvoke "exec.clj" 39]
  [clojure.lang.RestFn invoke "RestFn.java" 423]
  [clojure.run.exec$_main$fn__205 invoke "exec.clj" 180]
  [clojure.run.exec$_main invokeStatic "exec.clj" 176]
  [clojure.run.exec$_main doInvoke "exec.clj" 139]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.main$main_opt invokeStatic "main.clj" 514]
  [clojure.main$main_opt invoke "main.clj" 510]
  [clojure.main$main invokeStatic "main.clj" 664]
  [clojure.main$main doInvoke "main.clj" 616]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.main main "main.java" 40]],
 :cause "Timed out after 900000 ms.",
 :data {}}
The command '/bin/sh -c INTERACTIVE=false CI=true MB_EDITION=$MB_EDITION bin/build.sh' returned a non-zero code: 255
while taking build suddenly i'm getting this issue help me to solve this and give steps me steps to take build

**Comment by paoliniluis** [comment]
Reinstall nodejs

**Comment by marcinkoziej** [comment]
@paoliniluis I have the same issue trying to build Metabase via a Gitlab job. How would reinstalling nodejs help with this issue? Are you suggesting some yarn version is necessary for this to build?

**Comment by paoliniluis** [comment]
@marcinkoziej please post your entire ci file

**Comment by marcinkoziej** [comment]
Here it goes! Nothing unordinary. 
```
image: docker:18-git
services:
  - docker:18-dind

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
 stage: build
 rules:
   - if: $CI_COMMIT_TAG != null
     when: always
 script:
   - docker build -t $CONTAINER_IMAGE .
   - docker push $CONTAINER_IMAGE
```

**Comment by marcinkoziej** [comment]
[paoliniluis](https://github.com/paoliniluis) I changed the timeout in `shell.clj` to 60 minutes, and the build completed after 43minutes. I also needed to make memory limit higher for this build as it was hitting some low memory condition.

Not sure what's the action to be taken here? Should the default be increased?

```
diff --git a/bin/build/src/metabuild_common/shell.clj b/bin/build/src/metabuild_common/shell.clj
index 1373b5843b..278e5178f4 100644
--- a/bin/build/src/metabuild_common/shell.clj
+++ b/bin/build/src/metabuild_common/shell.clj
@@ -22,7 +22,7 @@
       (throw (ex-info (format "Timed out after %d ms." timeout-ms) {})))
     result))
 
-(def ^:private command-timeout-ms (* 15 60 1000)) ; 15 minutes
+(def ^:private command-timeout-ms (* 60 60 1000)) ; 60 minutes
 
 (defn sh*
   "Run a shell command. Like `clojure.java.shell/sh`, but prints output to stdout/stderr and returns a map with keys

```

**Comment by sundarrajan13** [comment]
suddenly getting this error, help me to resolve .              



Downloading: org/mongodb/mongodb-driver-core/3.12.11/mongodb-driver-core-3.12.11.jar from central
{:clojure.main/message
 "Execution error (FileNotFoundException) at metabuild-common.aws/eval1459$loading (aws.clj:1).\nCould not locate metabuild_common/shell__init.class, metabuild_common/shell.clj or metabuild_common/shell.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.\n",
 :clojure.main/triage
 {:clojure.error/class java.io.FileNotFoundException,
  :clojure.error/line 1,
  :clojure.error/cause
  "Could not locate metabuild_common/shell__init.class, metabuild_common/shell.clj or metabuild_common/shell.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.",
  :clojure.error/symbol metabuild-common.aws/eval1459$loading,
  :clojure.error/source "aws.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message
    "Syntax error macroexpanding at (metabuild_common/aws.clj:1:1).",
    :data
    {:clojure.error/phase :execution,
     :clojure.error/line 1,
     :clojure.error/column 1,
     :clojure.error/source "metabuild_common/aws.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7665]}
   {:type java.io.FileNotFoundException,
    :message
    "Could not locate metabuild_common/shell__init.class, metabuild_common/shell.clj or metabuild_common/shell.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.",
    :at [clojure.lang.RT load "RT.java" 462]}],
  :trace
  [[clojure.lang.RT load "RT.java" 462]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
   [clojure.core$load invokeStatic "core.clj" 6160]
   [clojure.core$load doInvoke "core.clj" 6144]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5933]
   [clojure.core$load_one invoke "core.clj" 5928]
   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
   [clojure.core$load_lib invokeStatic "core.clj" 5974]
   [clojure.core$load_lib doInvoke "core.clj" 5953]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$load_libs invokeStatic "core.clj" 6016]
   [clojure.core$load_libs doInvoke "core.clj" 6000]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$require invokeStatic "core.clj" 6038]
   [clojure.core$require doInvoke "core.clj" 6038]
   [clojure.lang.RestFn invoke "RestFn.java" 482]
   [metabuild_common.aws$eval1459$loading__6789__auto____1460
    invoke
    "aws.clj"
    1]
   [metabuild_common.aws$eval1459 invokeStatic "aws.clj" 1]
   [metabuild_common.aws$eval1459 invoke "aws.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7194]
   [clojure.lang.Compiler eval "Compiler.java" 7183]
   [clojure.lang.Compiler load "Compiler.java" 7653]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
   [clojure.core$load invokeStatic "core.clj" 6160]
   [clojure.core$load doInvoke "core.clj" 6144]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5933]
   [clojure.core$load_one invoke "core.clj" 5928]
   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
   [clojure.core$load_lib invokeStatic "core.clj" 5974]
   [clojure.core$load_lib doInvoke "core.clj" 5953]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$load_libs invokeStatic "core.clj" 6016]
   [clojure.core$load_libs doInvoke "core.clj" 6000]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$require invokeStatic "core.clj" 6038]
   [clojure.core$require doInvoke "core.clj" 6038]
   [clojure.lang.RestFn invoke "RestFn.java" 805]
   [metabuild_common.core$eval1453$loading__6789__auto____1454
    invoke
    "core.clj"
    1]
   [metabuild_common.core$eval1453 invokeStatic "core.clj" 1]
   [metabuild_common.core$eval1453 invoke "core.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7194]
   [clojure.lang.Compiler eval "Compiler.java" 7183]
   [clojure.lang.Compiler load "Compiler.java" 7653]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
   [clojure.core$load invokeStatic "core.clj" 6160]
   [clojure.core$load doInvoke "core.clj" 6144]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5933]
   [clojure.core$load_one invoke "core.clj" 5928]
   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
   [clojure.core$load_lib invokeStatic "core.clj" 5974]
   [clojure.core$load_lib doInvoke "core.clj" 5953]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$load_libs invokeStatic "core.clj" 6016]
   [clojure.core$load_libs doInvoke "core.clj" 6000]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$require invokeStatic "core.clj" 6038]
   [clojure.core$require doInvoke "core.clj" 6038]
   [clojure.lang.RestFn invoke "RestFn.java" 421]
   [build_drivers.common$eval234$loading__6789__auto____235
    invoke
    "common.clj"
    1]
   [build_drivers.common$eval234 invokeStatic "common.clj" 1]
   [build_drivers.common$eval234 invoke "common.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7194]
   [clojure.lang.Compiler eval "Compiler.java" 7183]
   [clojure.lang.Compiler load "Compiler.java" 7653]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
   [clojure.core$load invokeStatic "core.clj" 6160]
   [clojure.core$load doInvoke "core.clj" 6144]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5933]
   [clojure.core$load_one invoke "core.clj" 5928]
   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
   [clojure.core$load_lib invokeStatic "core.clj" 5974]
   [clojure.core$load_lib doInvoke "core.clj" 5953]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$load_libs invokeStatic "core.clj" 6016]
   [clojure.core$load_libs doInvoke "core.clj" 6000]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$require invokeStatic "core.clj" 6038]
   [clojure.core$require doInvoke "core.clj" 6038]
   [clojure.lang.RestFn invoke "RestFn.java" 512]
   [build_drivers.build_driver$eval228$loading__6789__auto____229
    invoke
    "build_driver.clj"
    1]
   [build_drivers.build_driver$eval228
    invokeStatic
    "build_driver.clj"
    1]
   [build_drivers.build_driver$eval228 invoke "build_driver.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7194]
   [clojure.lang.Compiler eval "Compiler.java" 7183]
   [clojure.lang.Compiler load "Compiler.java" 7653]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
   [clojure.core$load invokeStatic "core.clj" 6160]
   [clojure.core$load doInvoke "core.clj" 6144]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5933]
   [clojure.core$load_one invoke "core.clj" 5928]
   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
   [clojure.core$load_lib invokeStatic "core.clj" 5974]
   [clojure.core$load_lib doInvoke "core.clj" 5953]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$load_libs invokeStatic "core.clj" 6016]
   [clojure.core$load_libs doInvoke "core.clj" 6000]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$require invokeStatic "core.clj" 6038]
   [clojure.core$require doInvoke "core.clj" 6038]
   [clojure.lang.RestFn invoke "RestFn.java" 436]
   [build_drivers$eval222$loading__6789__auto____223
    invoke
    "build_drivers.clj"
    1]
   [build_drivers$eval222 invokeStatic "build_drivers.clj" 1]
   [build_drivers$eval222 invoke "build_drivers.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7194]
   [clojure.lang.Compiler eval "Compiler.java" 7183]
   [clojure.lang.Compiler load "Compiler.java" 7653]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
   [clojure.core$load invokeStatic "core.clj" 6160]
   [clojure.core$load doInvoke "core.clj" 6144]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5933]
   [clojure.core$load_one invoke "core.clj" 5928]
   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
   [clojure.core$load_lib invokeStatic "core.clj" 5974]
   [clojure.core$load_lib doInvoke "core.clj" 5953]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$load_libs invokeStatic "core.clj" 6016]
   [clojure.core$load_libs doInvoke "core.clj" 6000]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$require invokeStatic "core.clj" 6038]
   [clojure.core$require doInvoke "core.clj" 6038]
   [clojure.lang.RestFn invoke "RestFn.java" 1096]
   [build$eval214$loading__6789__auto____215 invoke "build.clj" 1]
   [build$eval214 invokeStatic "build.clj" 1]
   [build$eval214 invoke "build.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7194]
   [clojure.lang.Compiler eval "Compiler.java" 7183]
   [clojure.lang.Compiler load "Compiler.java" 7653]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
   [clojure.core$load invokeStatic "core.clj" 6160]
   [clojure.core$load doInvoke "core.clj" 6144]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5933]
   [clojure.core$load_one invoke "core.clj" 5928]
   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
   [clojure.core$load_lib invokeStatic "core.clj" 5974]
   [clojure.core$load_lib doInvoke "core.clj" 5953]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$load_libs invokeStatic "core.clj" 6016]
   [clojure.core$load_libs doInvoke "core.clj" 6000]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$require invokeStatic "core.clj" 6038]
   [clojure.core$require doInvoke "core.clj" 6038]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.run.exec$requiring_resolve_SINGLEQUOTE_
    invokeStatic
    "exec.clj"
    36]
   [clojure.run.exec$requiring_resolve_SINGLEQUOTE_
    invoke
    "exec.clj"
    29]
   [clojure.run.exec$exec$fn__151 invoke "exec.clj" 44]
   [clojure.run.exec$exec invokeStatic "exec.clj" 43]
   [clojure.run.exec$exec doInvoke "exec.clj" 39]
   [clojure.lang.RestFn invoke "RestFn.java" 423]
   [clojure.run.exec$_main$fn__205 invoke "exec.clj" 180]
   [clojure.run.exec$_main invokeStatic "exec.clj" 176]
   [clojure.run.exec$_main doInvoke "exec.clj" 139]
   [clojure.lang.RestFn invoke "RestFn.java" 397]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Could not locate metabuild_common/shell__init.class, metabuild_common/shell.clj or metabuild_common/shell.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.",
  :phase :execution}}

Execution error (FileNotFoundException) at metabuild-common.aws/eval1459$loading (aws.clj:1).
Could not locate metabuild_common/shell__init.class, metabuild_common/shell.clj or metabuild_common/shell.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name
