### ISSUE TITLE
All queries lost migrating from 0.19.3 to 0.20.0 (H2 on EC2)

### ISSUE THREAD

**Issue by obaqueiro** [metabase/metabase#3853]
I am super frustrated with this (been trying to fix it for hours).  I've got a simple Jar based Metabse deployment using 0.19.3. I am trying to migrate to 0.20.0 (in order to migrate from h2 to mysql... as it is not possible with < 0.20).

However, it seems that when I start metabase with the 0.20.0 jar for some reason it does not recognize the contents of the database and forces me to setup a new database.  Building from scratch is not an option, as I have hundreds of queries and some dashboards already there...

Anyone please help!
The startup log from the "bad" 0.20.0 and the "good" 0.19.3 starts:
0.20.0:
    ~$ java -server -jar metabase.jar.20
    12-01 23:57:34 INFO metabase.util :: Loading Metabase...
    12-01 23:57:43 INFO metabase.core :: Starting Metabase in STANDALONE mode
    12-01 23:57:43 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
     {:port 3000}

    12-01 23:57:43 INFO metabase.core :: Starting Metabase version v0.20.1 (05c22e2 release-0.20.1) ...
    12-01 23:57:43 INFO metabase.core :: System timezone is 'America/Mexico_City' ...
    12-01 23:57:43 INFO metabase.db :: Verifying h2 Database Connection ...
    12-01 23:57:44 DEBUG metabase.driver :: Registered driver :h2 🚚
    12-01 23:57:44 INFO metabase.db :: Verify Database Connection ... ✅
    12-01 23:57:44 INFO metabase.db :: Running Database Migrations...
    12-01 23:57:44 INFO metabase.db :: Setting up Liquibase...
    12-01 23:57:44 INFO metabase.db :: Liquibase is ready.
    12-01 23:57:44 INFO metabase.db :: Checking if Database has unran migrations...
    12-01 23:58:04 INFO metabase.db :: Database Migrations Current ... ✅
    com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
    12-01 23:58:04 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
    12-01 23:58:04 INFO db.migrations :: Finished running data migrations.
    12-01 23:58:04 INFO metabase.core :: Looks like this is a new installation ... preparing setup wizard
    12-01 23:58:04 INFO metabase.core :: Please use the following url to setup your Metabase installation:

    http://localhost:3000/setup/

    12-01 23:58:04 INFO metabase.core :: Metabase Initialization COMPLETE

0.19.3:

    ~$ java -server -jar metabase.jar.19.3
    12-01 23:54:50 INFO metabase.core :: Starting Metabase in STANDALONE mode
    12-01 23:54:50 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
     {:port 3000}

    12-01 23:54:50 INFO metabase.core :: Starting Metabase version v0.19.3 (796613e release-0.19.3) ...
    12-01 23:54:50 INFO metabase.core :: System timezone is 'America/Mexico_City' ...
    12-01 23:54:50 INFO metabase.db :: Verifying h2 Database Connection ...
    12-01 23:54:50 DEBUG metabase.driver :: Registered driver :h2 🚚
    12-01 23:54:50 INFO metabase.db :: Verify Database Connection ... ✅
    12-01 23:55:13 INFO metabase.db :: Database Migrations Current ... ✅
    com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.", exception -> null]
    com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.", exception -> null]
    com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/c3p0.properties' could not be found. Skipping.", exception -> null]
    com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.", exception -> null]
    com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.", exception -> null]
    com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier '/c3p0.properties' could not be found. Skipping.", exception -> null]
    com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
    12-01 23:55:14 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
    12-01 23:55:14 INFO db.migrations :: Finished running data migrations.
    12-01 23:55:14 INFO metabase.sync-database :: Syncing H2 database 'Sample Dataset'...
    12-01 23:55:14 INFO sync-database.introspect :: Introspecting schema on H2 database 'Sample Dataset' ...
    12-01 23:55:14 DEBUG driver.generic-sql :: Creating new connection pool for database 1 ...
    12-01 23:55:14 INFO sync-database.introspect :: [**********········································] 😞   20% Synced table 'PUBLIC.PRODUCTS'.
    12-01 23:55:14 INFO sync-database.introspect :: [********************······························] 😐   40% Synced table 'PUBLIC.ORDERS'.
    12-01 23:55:14 INFO sync-database.introspect :: [******************************····················] 😌   60% Synced table 'PUBLIC.PEOPLE'.
    12-01 23:55:14 INFO sync-database.introspect :: [****************************************··········] 😊   80% Synced table 'PUBLIC._METABASE_METADATA'.
    12-01 23:55:14 INFO sync-database.introspect :: [**************************************************] 😎  100% Synced table 'PUBLIC.REVIEWS'.
    12-01 23:55:14 DEBUG sync-database.introspect :: Marking foreign key 'PUBLIC.ORDERS.USER_ID' -> 'PUBLIC.PEOPLE.ID'.
    12-01 23:55:14 DEBUG sync-database.introspect :: Marking foreign key 'PUBLIC.ORDERS.PRODUCT_ID' -> 'PUBLIC.PRODUCTS.ID'.
    12-01 23:55:14 DEBUG sync-database.introspect :: Marking foreign key 'PUBLIC.REVIEWS.PRODUCT_ID' -> 'PUBLIC.PRODUCTS.ID'.
    12-01 23:55:14 INFO sync-database.introspect :: Introspection completed on H2 database 'Sample Dataset' (571 ms)
    12-01 23:55:15 INFO sync-database.analyze :: Analyzing data in H2 database 'Sample Dataset' (this may take a while) ...
    12-01 23:55:15 INFO sync-database.analyze :: [************······································] 😒   25% Analyzed table 'ORDERS'.
    12-01 23:55:16 INFO sync-database.analyze :: [*************************·························] 😬   50% Analyzed table 'PEOPLE'.
    12-01 23:55:16 INFO sync-database.analyze :: [*************************************·············] 😋   75% Analyzed table 'PRODUCTS'.
    12-01 23:55:16 INFO sync-database.analyze :: [**************************************************] 😎  100% Analyzed table 'REVIEWS'.
    12-01 23:55:16 INFO sync-database.analyze :: Analysis of H2 database 'Sample Dataset' completed (591 ms).
    12-01 23:55:16 INFO metabase.sync-database :: Finished syncing H2 database 'Sample Dataset'. (2 s)
    12-01 23:55:16 INFO metabase.metabot :: Starting MetaBot WebSocket monitor thread...
    12-01 23:55:16 INFO metabase.core :: Metabase Initialization COMPLETE

**Comment by mazameli** [comment]
Sorry for the frustration, Omar. I suspect @camsaul might have some insight into why this might be happening.

**Comment by camsaul** [comment]
@obaqueiro have you tried the 0.20.3 JAR? 

What environment variables related to the DB are you specifying?

**Comment by camsaul** [comment]
It would be helpful if you could fill out some of the bug questionaire stuff so we can try to suss out what's going on here.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)

**Comment by obaqueiro** [comment]
Hello,  sure, I actually have been trying to troubleshoot the issue with git bisect  (works on 0.19.3, doesn't work on 0.20.0) and found that when running via  `lein run`  the database *is* being recognised (con commit v0.20.3) . 

What I am planning to do is try to do the migration that way and then run the migrated database using the jar to se what happens.

**Comment by obaqueiro** [comment]
Interesting, after further analysis, it seems it works (with same h2 db)  on my Mac (OSX el Captain)  but it *does not* work on the EC2 ubuntu environment:

` Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)`

**Comment by camsaul** [comment]
@obaqueiro you were using H2 on EC2?

**Comment by obaqueiro** [comment]
Yep, Is that wrong?

**Comment by camsaul** [comment]
We don't recommend it for production instances. [From the website](http://www.metabase.com/docs/latest/operations-guide/start.html#configuring-the-metabase-application-database):

> For production installations of Metabase we recommend that users replace the H2 database with a more robust option such as Postgres. This offers a greater degree of performance and reliability when Metabase is running with many users.

Any reason you set up Metabase manually on EC2 instead of using the [Elastic Beanstalk quick   launch](http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html)? It's preconfigured to set up an RDS database for you.

**Comment by obaqueiro** [comment]
Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Not Applicable (affects all browsers)

Your operating system: (e.x. OS X 10, Windows XP, etc)
Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64) under EC2 (doesn't happen in OSX El Captain, with same h2 database and same 0.20.0 version)

Your databases: (e.x. MySQL, Postgres, MongoDB, …)
4 MySQL Databases and one MongoDB database

Metabase version: (e.x. 0.19.3)
0.19.3 - h2 database is recognized
0.20.0- h2 database is NOT recognized

Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
AWS EC2  Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)   - I can reproduce error with v.0.20.0 jar file
Mac OSX El Captain - I cannot reproduce the error with v0.20.0  jar file

**Comment by camsaul** [comment]
Hi @obaqueiro, I think your best option here is probably migrating from using an H2 database to using something more production-grade like Postgres or MySQL on RDS. We've written a guide on how to do that [here](http://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres). Let me know if you run into any trouble doing that.
