### ISSUE TITLE
[Feature] Add more than 2 metrics + being able to choose row and column

### ISSUE THREAD

**Issue by Olaktal** [metabase/metabase#3855]
Hello,

We have a DWH where data are organized with a star schema and so we have a lot a measure to display (may be more than 10 in some reports) which can be analyzed from multiple dimensions in order to group data (category of the product, country of the order, client, payment method, seller, ...) (more than 2 can be used of course, in average 4/5+).
Is there a reasy why the number of metrics is limited to one ?
Same question for dimension which are limited to 2 ? (1 for columns and one for rows)

What would be perfect is an unlimited number of dimensions and metrics + being able to choose which dimension will be displayed as rows and which will be used as columns.

Could you please enlight me on these subjects and if this kind of enhancement would be possible ?

If I'm not clear enough I can be more precise

Thanks
Best regards,
Vincent

**Comment by salsakran** [comment]
we've had the ability to pick x/y axes for a while, and we can display multiple metrics with the new notebook mode.
