### ISSUE TITLE
Reset Password does not prevent multiple clicks

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#38610]
### Describe the bug

Clicking the Reset Password button multiple times results in several password reset actions for the user.

### To Reproduce

1. Go to Admin Settings / People and try to reset the password for an existing user
<img width="508" alt="image" src="https://github.com/metabase/metabase/assets/11080638/eb44ebba-531b-427a-a70e-6cc9528f073a">

2. Click the Reset Password button several times
<img width="1157" alt="image" src="https://github.com/metabase/metabase/assets/11080638/2e9fee49-ff60-4506-a183-f5bc6875d2d1">

3. The API will be called multiple times, generating a new password reset link on each call
<img width="1157" alt="image" src="https://github.com/metabase/metabase/assets/11080638/c3d1a2c6-6b24-4198-bfd7-65cb04954d18">

### Expected behavior

The password reset should happen only once.

### Information about your Metabase installation

```JSON
"v1.48.3"
```

### Severity

Cosmetic. Potential confusion from the multiple password reset emails.

**Comment by dpsutton** [comment]
We can likely debounce the front-end and use `throttle.core/make-throttler` on the backend to prevent this.
