### ISSUE TITLE
Linked Filters: Connected fields do not show any values

### ISSUE THREAD

**Issue by sumeetsekhon7** [metabase/metabase#38625]
I am trying to create linked filters for State and City in the Sample DB database by metabase. As a prerequisite for linked filters, I am using connected fields to get the values of the filters. But nothing shows up in the connected fields tab even after running the 'Re-scan this table' option in Table Metadata. Could you please provide the inputs on this. @flamber

**Comment by sumeetsekhon7** [comment]
I am trying to create linked filters for State and City in the Sample DB database by metabase. As a prerequisite for linked filters, I am using connected fields to get the values of the filters. But nothing shows up in the connected fields tab even after running the 'Re-scan this table' option in Table Metadata. Could you please provide the inputs on this. @flamber

**Comment by paoliniluis** [comment]
Please use a question in the forums
