### ISSUE TITLE
Action buttons appear disabled on public dashboards

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#38639]
### Describe the bug

Action buttons on public dashboards don't work for user. They appear with an "Actions are not enabled for this Database" tooltip.

### To Reproduce

To Reproduce:

1. Turn on public sharing in admin settings
2. Create a model from a table and create basic actions for the model
3. Create a dashboard, and add an action dashcard. Save.

<img width="1511" alt="image" src="https://github.com/metabase/metabase/assets/110378427/2371f97d-77ea-4864-8375-08296c26e99b">

4. Enable public sharing of the dashboard. Go to an incognito tab and observe that the action button is faded.

<img width="1503" alt="image" src="https://github.com/metabase/metabase/assets/110378427/532528d9-f54f-4b9a-9671-a9bbbbcf9fd7">

This isn't even possible because To be able to create an Action it has to be enabled!

### Expected behavior

Able to perform an Action in Public 

### Logs

None that Are relevant

### Information about your Metabase installation

```JSON
Able to replicate on 1.48.5 and even in Master
```

### Severity

Some user dashboards which are publicly shared and are using actions are currently unusable

### Additional context

I think it's related to https://github.com/metabase/metabase/issues/30929 but there is no API that points to an error. So i am not sure if its a Frontend or Backend Issue

**Comment by albertoperdomo** [comment]
I think this is no longer the case and actions no longer appear in public dashboards. Can you please confirm @Tony-metabase ?

**Comment by Tony-metabase** [comment]
Correct that Action buttons disappear in public dashboards ... So that is the new expected behaviour? I thought it was going to be possible to use Actions on public dashboards but if that is not the case then this can be closed

**Comment by albertoperdomo** [comment]
@Tony-metabase Do they appear disabled or do they not appear? I am confused. Expectation is they don't appear at all.

**Comment by albertoperdomo** [comment]
AFAIK, they never worked in public shares and embeds. See https://github.com/metabase/metabase/issues/34395.
They should no longer appear on the dashboards as per PR here: https://github.com/metabase/metabase/pull/39048.

Can you please confirm if they do appear disabled or don't appear? This was released in 49.

**Comment by Tony-metabase** [comment]
They just vanish when you make a dashboard publicly available and access the public link. If that's how it's supposed to work I will close this issue then!
