### ISSUE TITLE
Don't fade out visualization options so aggressively

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3863]
I've heard from a few users now that they didn't realize they could select visualization options that are grayed-out (which makes total sense). Usually, their situation was that they were trying to graph using raw/unaggregated data.

So now that we have more flexible charting options — in particular the ability to select fields from a raw data table to graph — I don't know that it makes sense for us to fade out our visualization options. Maybe some of the combinations still truly don't make sense (e.g., the Number or Gauge options for a raw data table), but you can definitely use all of the other visualization types with raw data.

![screen shot 2016-12-05 at 10 44 07 am](https://cloud.githubusercontent.com/assets/2223916/20898011/808af08c-bad9-11e6-9c15-f726153a1d64.png)

One idea would be to add a heading to the top of the list that says "Recommended," and move the visualization types that _probably_ won't work with the given dataset down to the bottom of the list, below another heading that says "Other" or something. The obvious downside is that it moves the options around.

Another way to go would be to really change the dropdown, and do something more visual, similar to how Google Sheets does their recommended visualizations. I actually really like the idea of _showing_ users the different chart options. And then we could just _list_ the less-than-recommended types at the bottom.

![screen shot 2016-12-05 at 10 57 46 am](https://cloud.githubusercontent.com/assets/2223916/20898089/df07ccfc-bad9-11e6-8db8-ea80cf62e936.png)

**Comment by flamber** [comment]
Going to go ahead and close this, since the visualization selector got a facelift in version 0.33:
![image](https://user-images.githubusercontent.com/1447303/75098970-a5143900-55bc-11ea-8cc8-8185969ada82.png)
