### ISSUE TITLE
Table List is not visible on clicking on database name on permission tab. Data is connected to metabase through Athena

### ISSUE THREAD

**Issue by rgrip121** [metabase/metabase#38643]
### Describe the bug

Summary:

I have created some views on Athena and connected that with Metabase. In the data browse section, I am seeing the name of tables as well as can write SQL native queries over it. Now , i want different access to different users.
For that when accessing the permission tab in Metabase and selecting the database name, no tables are listed despite the presence of approximately 150 tables in the database.

Expected Behavior:
When clicking on the database name in the permission tab, the list of tables associated with the database should be displayed, allowing granular access control to be assigned.

Actual Behavior:
No tables are listed when clicking on the database name in the permission tab, rendering it impossible to assign granular access control to specific tables.

### To Reproduce

Log in to Metabase.
Navigate to the permission tab.
Click on the database name to view the tables.
Observe that no tables are displayed.

### Expected behavior

When clicking on the database name in the permission tab, the list of tables associated with the database should be displayed, allowing granular access control to be assigned.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "4.14.314-237.533.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "athena",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-07",
      "tag": "v0.47.7",
      "branch": "?",
      "hash": "dd51fd4"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

### Severity

It is quite important as well as urgent. It is blocking my usage of metabase entirely

### Additional context

Additional Information:

The database connection has been validated, and connectivity between Metabase and Athena is confirmed.
Permissions for the user account utilized for connecting to Athena from Metabase have been meticulously reviewed and deemed appropriate.
The tables are confirmed to exist within the designated database and schema.
The tables were created using SQL queries and DDL (Data Definition Language) statements executed within Athena's query editor or through automation scripts.
Attempts to refresh metadata and schema information within Metabase have been executed, but the issue persists.
There are no discernible network issues or connectivity disruptions.
Logs within Metabase do not reveal any errors or warnings pertaining to database connectivity or table discovery.

**Comment by rgrip121** [comment]
<img width="961" alt="Screenshot 2024-02-09 at 6 46 55 PM" src="https://github.com/metabase/metabase/assets/159687751/cffa4bb3-8c02-49a9-b9d8-44249d7951ed">
Attaching screenshot of the empty table list appearing on clicking database name in permission tab

**Comment by paoliniluis** [comment]
can you show the browse data section where you're seeing the tables?

**Comment by rgrip121** [comment]
PFA the browsed data section where the tables are available.
![Uploading Screenshot 2024-02-12 at 10.13.47 AM.png…]()

**Comment by paoliniluis** [comment]
I can't see the attachment

**Comment by rgrip121** [comment]
<img width="1503" alt="Screenshot 2024-02-12 at 10 13 47 AM" src="https://github.com/metabase/metabase/assets/159687751/3e3a3dae-cdf2-4aaa-b80f-753a4c7f0407">
Attached again

**Comment by noahmoss** [comment]
Hi @rgrip121, sorry we were not able to resolve this when you originally reported it. Are you still seeing this issue?

If so, could you try upgrading to a newer version of Metabase?

**Comment by dpsutton** [comment]
Gonna close as we are not able to reproduce this on the latest releases or on the version reported. If we have more information happy to reopen this in the future.
