### ISSUE TITLE
Archiving and unarchiving a collection leaves dashboards in the collection empty

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#38646]
### Describe the bug

When unarchiving a collection the dashboards restored in it will no longer have the questions that are in the restored collection.

### To Reproduce

1. Create a dashboard with some questions, all saved into the same collection
2. Archive the collection
3. Hit Undo, or unarchive the collection manually
4. (!) All objects are restored, but the dashboard is restored empty

### Expected behavior

The dashboard should be restored in the state prior to the archival

### Information about your Metabase installation

```JSON
v48 as well as on master
```

### Severity

P2

### Additional context

Might be related to https://github.com/metabase/metabase/issues/26168, however this one happens when you simply try to restore the same object that was archived the first place.
The workaround is to restore the dashboard to a previous state.

**Comment by iethree** [comment]
should be handled with https://github.com/metabase/metabase/issues/38063
