### ISSUE TITLE
Unable to give decimal number for the amount field of DatetimeAdd

### ISSUE THREAD

**Issue by e-gaulue** [metabase/metabase#38653]
### Describe the bug

As state in the documentation (https://www.metabase.com/docs/latest/questions/query-builder/expressions/datetimeadd), DatetimeAdd should allow decimal number for amount field. It appears it's not possible and if used in custom expression you don't get any error, expression looks accepted but it's ignored.

This issue is different than #33782, as it has been marked as "Feature request" while that one looks like a bug according to the documentation. It's a first step on the way to allow amount from other columns.

### To Reproduce

1. Create a question with whatever data (the trouble is not linked with data)
2. Add a custom field
3. In expression put datetimeAdd(now, 1, "year")
4. Call it "InOneYear"
5. Click on view => OK
6. Add another custom field
7. In expression put datetimeAdd(now, 0.5, "year")
8. Call it "InHalfAYear"
9. Click on view => KO
10. Add another custom field
11. In expression put datetimeAdd(now, 1/2, "year")
12. Call it "InHalfAYearFraction"
13. Click on view => KO

### Expected behavior

On the 1st of January get something around the 1st of July

### Information about your Metabase installation

```JSON
- Metabase: 0.48.5
- Database : MySQL
```

### Severity

All that can't be done in metabase need to be done in datawharehouse. It's a shame.

### Additional context

#33782

**Comment by ranquild** [comment]
I think the docs should be updated. You cannot add "half a year"
