### ISSUE TITLE
Cannot import dashboards with circular click behavior

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#38665]
### Describe the bug

It is impossible to import dashboards with a circular click behavior, for example, when a dashboard links to itself, or when click behavior dashboard A has a link pointing to dashboard B which has a link pointing to dashboard A.

### To Reproduce

1. Create a DashboardA, add a QuestionA
2. Create DashboardB, add a QuestionB
3. Set up a circular click route between the dashboards:
   * DashboardA/QuestionA --> DashboardB
   * DashboardB/QuestionB --> DashboardA
4. Export everything
5. (!) Import and see the circular reference error below

### Expected behavior

The import should work, load all resources, and restore all exported links.

### Logs

clojure.lang.ExceptionInfo: Circular dependency on [{:model "Dashboard", :id "GUnezeAXjrWMd8k4x8PXx"}] {:path [{:model "Dashboard", :id "GUnezeAXjrWMd8k4x8PXx"}]}

### Information about your Metabase installation

```JSON
Reported in v47, also broken as of 1.48.5.
```

### Severity

Reported by a customer. No workaround, apart from removing some of the links..

**Comment by bshepherdson** [comment]
Ah, someone found it! I wondered if there was a cycle opportunity anywhere in our data model, and here's one after all.
