### ISSUE TITLE
Metric creation aggregation dropdown not appearing

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3866]
This is in v0.21.0-rc2. I've tested both Chrome and Safari. Sometimes the page seems to load indefinitely instead of rendering the below:

<img width="1363" alt="screen shot 2016-12-05 at 2 33 41 pm" src="https://cloud.githubusercontent.com/assets/2223916/20905263/f8ab6dd0-baf7-11e6-80ad-35d445fcddf9.png">

Here are the errors in the JS console:
<img width="1022" alt="screen shot 2016-12-05 at 2 37 12 pm" src="https://cloud.githubusercontent.com/assets/2223916/20905406/8607f7f2-baf8-11e6-8d34-d5a1c2daf1b3.png">

**Comment by salsakran** [comment]
I'm seeing this as well.
