### ISSUE TITLE
Quick Button to open code editor

### ISSUE THREAD

**Issue by OdinTallBeard** [metabase/metabase#38687]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The same way you have a shortcut to hide the sidebar, the same thing to open the code editor

**Describe alternatives you've considered**
NA

**How important is this feature to you?**
Unbelievably important ; speediness in code is amazing

**Additional context**
This would be a massive help ty

**Comment by paoliniluis** [comment]
please check the newest release that we have a command palette
