### ISSUE TITLE
If a group's SQL access is set to View Raw Queries, they can still edit SQL question details

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3869]
Specifically, a user can still edit the question's name and description, but when they go to save those changes, the page hangs. If the user refreshes, then they get a permissions error. Not sure if this is a bug, or just confusing UX. Don't know if we intended for users with "view raw queries" access to be able to edit SQL questions' name/descriptions.

**Comment by camsaul** [comment]
The API returns an error if you try to save a Card you don't have query "write" permissions for so I would guess that's why the page is hanging... do you see any error messages in the console?

**Comment by mazameli** [comment]
Here's what the admin console shows, which seems to me to be as-expected:
<img width="1197" alt="screen shot 2016-12-05 at 3 09 58 pm" src="https://cloud.githubusercontent.com/assets/2223916/20906459/050dad18-bafd-11e6-8e82-bd1a918b1902.png">

The test user account just sees the "saving…" message indefinitely, until they hard refresh or navigate away:
<img width="928" alt="screen shot 2016-12-05 at 3 10 26 pm" src="https://cloud.githubusercontent.com/assets/2223916/20906476/1994064c-bafd-11e6-87e5-b2fe00337eb3.png">

**Comment by camsaul** [comment]
Sorry @mazameli I meant the browser console.

**Comment by tlrobinson** [comment]
I think we just need to include a permissions field (`writable` or `read-only` or whatever) on card endpoints, and disable the edit button if it's not writable.

**Comment by mazameli** [comment]
Ah, test user's JS console looks like this:

<img width="1024" alt="screen shot 2016-12-05 at 3 17 48 pm" src="https://cloud.githubusercontent.com/assets/2223916/20906659/124e4a0e-bafe-11e6-80e9-ec6ec4bfbd1b.png">

**Comment by salsakran** [comment]
yeah, it doesn't make any sense to be able to edit an existing sql card's metadata without having the ability to create sql questions

**Comment by camsaul** [comment]
I can add that field if you let me know which endpoint We should still make sure we're handling errors in a better way than just leaving the page hanging because the endpoint might refuse to save the card for some other reason.

**Comment by camsaul** [comment]
@metabase/core-developers do we want to tackle this for 0.21.1 or 0.22.0? I have the PR open for the backend stuff so hopefully it's not too much of a hassle to check that value and disable the edit button on the frontend
