### ISSUE TITLE
After updating to 0.48.5 all of my questions encounter this error: "The connection string contains invalid user information. If the username or password contains a colon (:) or an at-sign (@) then it must be urlencoded"

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#38697]
### Describe the bug

After updating to 0.48.5

All of my questions are encountering an error related to connstring encoding issues.

Here is a sample password that my connection contains:

sample: p@ssw0rd123

after researching

the fixed password: p%40ssw0rd123

On the recent metabase versions i think this is being handled automatically by Metabase's system.

### To Reproduce

1. Copy paste the username/password on your DB connections that has "@" or ":"
2. Check if you could see the data inside that DB

### Expected behavior

I think the special characters would be handled automatically by Metabase as this was the behavior before 0.48.5

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9-post-Ubuntu-0ubuntu122.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9-post-Ubuntu-0ubuntu122.04",
    "os.name": "Linux",
    "os.version": "6.2.0-1019-azure",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-06",
      "tag": "v0.48.5",
      "hash": "dab12cf"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

It is annoying because if I have multiple DB setup I need to update each one of them with the proper encoding for special characters

### Additional context

![image](https://github.com/metabase/metabase/assets/89201548/ee20e98c-40d5-43bd-ae25-0c23ddc26d98)

**Comment by luizarakaki** [comment]
Does this question source your Mongo or MySQL database?

**Comment by paoliniluis** [comment]
probably an effect of https://github.com/metabase/metabase/pull/38017 @lbrdnk ? haven't had the time to repro

**Comment by jrca025** [comment]
> Does this question source your Mongo or MySQL database?

This is for MongoDB
