### ISSUE TITLE
Unable to filter by some searchable fields

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#38702]
### Describe the bug

https://metaboat.slack.com/archives/C05MPF0TM3L/p1707822061007859

### To Reproduce

https://metaboat.slack.com/archives/C05MPF0TM3L/p1707822061007859

### Expected behavior

The search endpoint should return an empty array instead of 204 no content

### Information about your Metabase installation

```JSON
-
```

### Severity

P1

**Comment by calherries** [comment]
Dupe of https://github.com/metabase/metabase/issues/37492
