### ISSUE TITLE
Date representation on Trend visualization regressed

### ISSUE THREAD

**Issue by iggups** [metabase/metabase#38802]
### Describe the bug

After updating from 0.48.2 to 0.48.6 the date representation on a trend visualization regressed.

In earlier versions yearly comparisons were displayed simply by "2024", now it says "Jan 1, 2024". Same with monthly comparisons. It used to be "Feb 2024", now it is "Feb 1, 2024". Screenshots attached.
![0486](https://github.com/metabase/metabase/assets/55084396/e1dd5f1d-20a5-4873-9ee7-3ff71c6532e9)
![0482](https://github.com/metabase/metabase/assets/55084396/5a0ca755-9e59-4516-ab9b-2bd2a6a88ad0)

### To Reproduce

1. Create Trend visualization with monthly or yearly comparison time frames
2. Year/month is represented as date, not month or year

### Information about your Metabase installation

```JSON
- Metabase 0.48.6
- Firefox 122.0
- Warehouse: Redshift
- Internal: PostgreSQL
- Docker
```

### Severity

annoying

**Comment by perivamsi** [comment]
Hi @iggups, thank you for reporting this. Are you using SQL to create the question or are you using the query builder UI?

**Comment by iggups** [comment]
Hi @perivamsi 
I am using SQL

**Comment by perivamsi** [comment]
The challenge with sql is that Metabase does not have enough information to correctly display the time period (2024 vs Jan 1, 2024) in all the cases. In previous versions, while we correctly displayed it for some examples, we would show [incorrect data for others](https://github.com/metabase/metabase/issues/38122). As a way to err on the side of correctness (we'd rather say Jan 1, 2024 than 2025 which is completely wrong), we decided to go with this approach.

If you use the query builder, Metabase then has enough information to correctly predict the time period with the right granularity (year vs month vs date).

**Comment by perivamsi** [comment]
We will explore that idea as a feature request.
