### ISSUE TITLE
Improve logging for Serialization Failures

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#38804]
**Is your feature request related to a problem? Please describe.**

Failures around serialisation are pretty unique and sometimes debugging them is hard. Currently the error log is not helpful when it comes to entity_id which fail to generate.

For example if a particular collection is missing (could have been deleted by mistake) you might get an error:

`ERROR v2.entity-ids :: Error updating entity ID: Assert failed: (some? entity)`

Which doesn't help in debugging 

**Describe the solution you'd like**
Better error messages, pointing to at least the object that is failing to get serialized.

**Describe alternatives you've considered**
None

**Additional context**
Enterprise customers which handle their own Application DB have unique environments

**Comment by paoliniluis** [comment]
@luizarakaki
