### ISSUE TITLE
Metabase is sending alerts half an hour after it is actually scheduled to send alerts

### ISSUE THREAD

**Issue by abhinav3204** [metabase/metabase#38800]
### Describe the bug

Metabase keeps sending alerts half an hour after it is supposed to. It is hosted directly on an ec2 instance running linux without using docker container.
These are the configuration for the instance
`{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9-post-Ubuntu-0ubuntu120.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9-post-Ubuntu-0ubuntu120.04",
    "os.name": "Linux",
    "os.version": "5.15.0-1038-gcp",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v1.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}`

The logs also don't indicate any issues but duly post half an hour after it is configured to. I have also tried changing the timezone but the issue persists.
Please let me know if any other details are required.

### To Reproduce

1. Create an alert on any dashboard or question
2. This alert is triggered half an hour

### Logs

1. Create an alert

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9-post-Ubuntu-0ubuntu120.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9-post-Ubuntu-0ubuntu120.04",
    "os.name": "Linux",
    "os.version": "5.15.0-1038-gcp",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v1.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}
```

### Severity

HIGH

**Comment by paoliniluis** [comment]
Hi @abhinav3204 how much time does the query takes? have you run the query that metabase does for this alert separately to check the time

**Comment by abhinav3204** [comment]
the query is a simple select 1 which I use for testing the alert generation. It hardly takes a few milisecond

**Comment by abhishek-superk** [comment]
@abhinav3204 This is a timezone issue I believe. In our setup also it's the same.
People just got used to it over time.

**Comment by qnkhuat** [comment]
We're now sending pulses in parallel and prioritize fast pulses, so this problem should be mitigated.
