### ISSUE TITLE
We should never run get-field-values on a dashboard load if the field does not have field values in the metabase_fieldvalues table

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#38826]
### Describe the bug

A customer with a massive database took down many dashboards as the metabase_fieldvalues was wiped by the time they did an upgrade, so Metabase started doing field-values on the DB on production time and several dashboards didn't load at all for the following reason: if a filter is a dropdown and the metabase_fieldvalues entry does not exist for that filter, we should simply return an empty array, not fire a query to the DB to get those

### To Reproduce

1) set up Metabase from scratch
2) create a question of the people table (just a raw table)
3) add a filter connected to the source field
4) go to the app db and wipe the field values from the metabase_fieldvalues for the source field (it's the one with Google, Facebook... fields)
5) load the dashboard, see Metabase running the `SELECT "public"."people"."source" AS "source" FROM "public"."people" GROUP BY "public"."people"."source" ORDER BY "public"."people"."source" ASC LIMIT 1000` query

this query can be extremely hard on some dwh and we're taking those dashboards (and probably the DWH) down due to this

### Expected behavior

If the field is not there just simply return an empty array, don't try to do that on a dashboard run

### Logs

NA

### Information about your Metabase installation

```JSON
v48.6, but probably been like that forever?
```

### Severity

P1

**Comment by calherries** [comment]
[slack discussion](https://metaboat.slack.com/archives/C052ZBWRG3W/p1708062280490179?thread_ts=1708022597.711849&cid=C052ZBWRG3W)

**Comment by luizarakaki** [comment]
I believe the expected behavior is to fetch field values only for fields that are assigned as dashboard filters. We don't need to get field values from all fields in the dashboard.

Ideally, we should fetch field values only if the user opens the dashboard filter widget.

**Comment by paoliniluis** [comment]
@luizarakaki Nope, we should never fetch those values at filter time unless it's a linked filter, as we do right now. Fetching filter values if they're not there at filter time without a WHERE clause can take down a DW if it's too big

**Comment by luizarakaki** [comment]
If fetching a single field values can take the entire DW down we can never scan field values...

**Comment by paoliniluis** [comment]
It's fine if we do it when the admin specifies it (e.g. late at night), but never ever at filter time unless it's a field filter

**Comment by dannyeuu** [comment]
Hi @luizarakaki and @paoliniluis, this behavior happens in my issue at #38921
