### ISSUE TITLE
Dashboard + required filter: default isn't picked up when URL param is empty

### ISSUE THREAD

**Issue by oleggromov** [metabase/metabase#38857]
### Describe the bug

If filter value is empty in the URL, it's not set to default for a required filter.

<img width="1125" alt="Screenshot 2024-02-16 at 13 33 48" src="https://github.com/metabase/metabase/assets/2196347/aa1c9aaa-ff85-42ee-88ec-c7f19f1f2716">

### To Reproduce

1. Create/get a dashboard with a required filter
2. Open it and **unset** its value from the URL
3. See that the filter appears empty

### Expected behavior

It should use default value and, possibly, even change the URL

### Logs

{}

### Information about your Metabase installation

```JSON
{}
```

### Severity

P3

**Comment by oleggromov** [comment]
Quite likely this is related to the behavior introduced here https://github.com/metabase/metabase/pull/31891 
I need to investigate furhter, as the most straightforward solution didn't work.

**Comment by ranquild** [comment]
This is currently by design and our way to clear filters with default values.
