### ISSUE TITLE
SQL editor formatting capability

### ISSUE THREAD

**Issue by darioprencipe** [metabase/metabase#38851]
**Is your feature request related to a problem? Please describe.**
SQL queries behind cards go wild without proper formatting (and linting, that would be for next feat request). Unformatted SQL queries are hardly readable, make the whole management on un-versioned SQL scripts around your Metabase account a nightmare. 

**Describe the solution you'd like**
Option to enable format on save (VSCode-like). When enabling formatting, one should have the option to select SQL dialect she wants the query to be formatted along (a starting point reference could be --> https://docs.sqlfluff.com/en/stable/dialects.html). This could also be configured at database level, i.e. whenever I create a database connection to a certain DB, I can setup that all SQL queries targeting that db will be auto-formatted according to a certain dialect (consistent with chosen DB).  

**Describe alternatives you've considered**
Alternative is for me to go through each query one by one, copy-pasting it to another tool, then formatting it, then copy-pasting it back to Metabase SQL editor. Not great.

**How important is this feature to you?**
This is not a must-have but it really is a WOW-feature.

**Comment by paoliniluis** [comment]
Coming in 49 if I’m not mistaken
