### ISSUE TITLE
No Access to Our Analytics will break the  "Add to Dashboard" in multiple ways

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#38856]
### Describe the bug

The bug is split into 2:

1) When you don't have a dashboard in your personal collection:

Prompt will break with `You don't have permissions to do that` after Question is saved in Personal Collection and you proceed with the  "Add to Dashboard" prompt

2) When you do have a dashboard in your personal collection:

The other collection options are not given as an option and only the personal collection is visible

### To Reproduce

1. Go to New ->  Collection -> Shared Collection
2. Go to Admin Settings -> Permission -> Collection -> Give Our Analytics No Access to All Users (Shared Collection should be Curate)

<img width="1378" alt="image" src="https://github.com/metabase/metabase/assets/110378427/e88d39f7-d774-4674-8110-296a36244e6e">

3. Go to People -> Invite New User -> Make sure it has All Users Group
4. Login to Metabase with this New user
5. New -> Question -> Sample Database -> Orders -> Save 

<img width="1497" alt="image" src="https://github.com/metabase/metabase/assets/110378427/2641ef39-d924-486a-a900-40a9806c6855">

6. You will notice at this point you get prompt where to Save the collection -> Save in your Personal Collection and you will get the prompt Add this Question to Dashboard -> Click Yes -> You will get a Permission Error

<img width="1505" alt="image" src="https://github.com/metabase/metabase/assets/110378427/c714dabe-b638-43bf-b0e3-b5911ee2bdb9">

Note that if on the other hand you decide to save the question in the Shared Collection then Click Yes on the "Add Question to Dashboard" prompt, you get both options:

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/57557ea1-3f97-48b5-8aa8-20d3d5a2f972">

You can bypass this Error by creating a Dashboard in your Personal Collection but when you do so and rerun the process above the "Add to Dashboard" prompt will only show your personal collection not the `Shared Collection`

<img width="1506" alt="image" src="https://github.com/metabase/metabase/assets/110378427/db885c9a-45c8-4c94-94de-8e0e8beccec4">

### Expected behavior

Remove the You don't have permission Error when you don't have a dashboard in the personal collection and when you do have a dashboard make sure all collections are given as an options

### Logs

You don't have permissions to do that

### Information about your Metabase installation

```JSON
Able to replicate in 1.48.6
```

### Severity

Annoying since you have to always add the Question directly on the Dashboard making the prompt useless

**Comment by luizarakaki** [comment]
this is likely related to #38759

**Comment by iethree** [comment]
this may have been fixed by the entity picker (v50) - we did a lot of work to handle this case

**Comment by npfitz** [comment]
Yeah, I'm checking this now

**Comment by Tony-metabase** [comment]
Was too fast to escalated this! Indeed was not able to replicate this on 49.13 and also tested on 50 which changes the outlook completely. 

So this is now fine on new versions
