### ISSUE TITLE
Dashboard with many slower Athena questions does not open even with timeout in 1200 seconds

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#38921]
### Describe the bug

We have some dashboards with question at AWS Athena there is hitting the HTTP server upstream timed out and stop work, not even open the dashboard layout and async open each question, the dashboard is not opening.

![Screenshot from 2024-02-19 13-39-50](https://github.com/metabase/metabase/assets/6808348/5146e4e7-2956-40ab-92ec-e411464b41e7)

### To Reproduce

1. Open the dashboard URL link: https://metabase.domain.tld/dashboard/632-validacao-de-dados-staging

### Logs

2024-02-19 16:40:34,308 DEBUG middleware.log :: GET /api/dashboard/632 200 2.2 hours (59 chamadas ao banco de dados) Conexões com o banco de dados: 1 / 15 Threads do Jetty: 6 / 256 (2 ocioso, 0 na fila) (485 total de threads ativas) Consultas ativas: 0 (0 na fila); athena DB 22 connections: 2/2 (0 threads blocked)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "19+36",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "19+36",
    "os.name": "Linux",
    "os.version": "5.10.0-26-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "mysql",
      "postgres",
      "cubejs",
      "sqlserver",
      "googleanalytics",
      "athena",
      "bigquery-cloud-sdk",
      "mongo",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-06",
      "tag": "v0.48.5",
      "hash": "dab12cf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Stopped working for these dashboards users

**Comment by paoliniluis** [comment]
I have a strong feeling we're seeing https://github.com/metabase/metabase/issues/38826, can you check @dannyeuu

**Comment by dannyeuu** [comment]
Great felling @paoliniluis, I did reproduce the steps and saw the `SELECT "public"."people"."source" AS "source" FROM "public"."people" GROUP BY "public"."people"."source" ORDER BY "public"."people"."source" ASC LIMIT 1000` in the Athena Console


Duplicated of #38826

**Comment by qnkhuat** [comment]
@dannyeuu is it possible for us to get a dump of your task_history for your Athena DB?
```sql
select * from task_history where db_id = [[YOUR_ATHENA_DB_ID]] and started_at > '2024-02-01'::timestamp;
```

**Comment by dannyeuu** [comment]
This is the result @qnkhuat 
[query_result_2024-02-21T15_05_59.742805506Z.csv](https://github.com/metabase/metabase/files/14361243/query_result_2024-02-21T15_05_59.742805506Z.csv)

**Comment by paoliniluis** [comment]
@dannyeuu is there a reason why you reopened this?

**Comment by dannyeuu** [comment]
ops, sorry.
