### ISSUE TITLE
[dc.js migration] missing data on timeseries charts

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#38937]
https://metaboat.slack.com/archives/C06G94JTWBS/p1706201653722559

<img width="1415" alt="Screenshot 2024-02-19 at 12 54 44 PM" src="https://github.com/metabase/metabase/assets/37751258/cef67d8c-fc9d-41e0-9313-6900d24e3a12">

https://metaboat.slack.com/archives/C06G94JTWBS/p1706200083518489

<img width="1638" alt="Screenshot 2024-02-19 at 2 11 35 PM" src="https://github.com/metabase/metabase/assets/37751258/0dac6eff-1e00-4f7d-83ff-ee32552c5279">

This happens when the dataset has overlapping buckets (see this related issue: https://github.com/metabase/metabase/issues/36159). To fix it, we need to manually combine datum that overlap in the selected time bucket.

<img width="1452" alt="Screenshot 2024-02-22 at 12 30 13 PM" src="https://github.com/metabase/metabase/assets/37751258/c0c6f6be-e1cb-46b9-ba8a-886a22fc94c4">

In this example, if we combine these two datum into the first, the chart looks like how it used to in dc.js 

| Uncombined Datum | Combined Datum |
|--------|--------|
| <img width="1029" alt="Screenshot 2024-02-22 at 12 29 29 PM" src="https://github.com/metabase/metabase/assets/37751258/d2eb2c0d-9de6-4a51-ad58-0685be47fef0"> | <img width="985" alt="Screenshot 2024-02-22 at 12 30 18 PM" src="https://github.com/metabase/metabase/assets/37751258/18f33af7-36e9-42bd-95a8-b0f90486d54f"> | 

### More Examples

question/5082
https://metaboat.slack.com/archives/C06G94JTWBS/p1706193538101699

question/14597
https://metaboat.slack.com/archives/C06G94JTWBS/p1706193637425579

question/4223
https://metaboat.slack.com/archives/C06G94JTWBS/p1706193960436849

question/14597
https://metaboat.slack.com/archives/C06G94JTWBS/p1710341059082499

**Comment by alxnddr** [comment]
Concluded it is more desirable not to fix incorrect bucketing coming from the BE becasue charts actually look more correct
https://metaboat.slack.com/archives/C05NQSWPRMK/p1712840771548499?thread_ts=1712672954.660139&cid=C05NQSWPRMK
