### ISSUE TITLE
Show full table results in email Pulse

### ISSUE THREAD

**Issue by boringusername99** [metabase/metabase#3894]
Currently, email pulses only seem to show the first three columns of a table. Presuming this is intentional, it would be useful, for similar reasons to #2623 to have an option to show the full results of a table inline in the email.

For an additional reason, our use case is a daily performance snapshot going to execs. Dropping into Metabase to see the table or Excel to open a CSV (if #2623 were implemented) would be disruptive to the daily workflow and also a poor experience on a mobile device.

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by twarogowski-dts** [comment]
It would be also great to add a switch in settings to disable truncating results to 10 rows.

**Comment by edmarriner** [comment]
+1

**Comment by noamgat** [comment]
+1

**Comment by MathiasDL** [comment]
+1

**Comment by diogocaetano** [comment]
+1

**Comment by byumark** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by tmbull** [comment]
+1

**Comment by camsaul** [comment]
@tmbull, I literally just wrote this in the comment above yours, but one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description. 

😒

**Comment by tmbull** [comment]
My bad for not reading. I've added a reaction.

**Comment by mazameli** [comment]
The main UX questions I have about this:
1. Should we really truly show all rows returned by the query? Do you guys honestly want 2,000 row emails? I.e., I'm saying I think we would probably have a row cap, but I don't know what the reasonable limit should be.
2. How many columns should be displayed? If there are 30, does that mean horizontal scrolling on desktop?
3. How should we handle large tables on mobile? One pattern I've seen is displaying one record at a time, with the headings and values shown in two side-by-side columns. That allows you to see any number of records, and theoretically allows for unlimited columns, but doesn't easily allow you to compare columns across records, and makes the email super tall.

**Comment by boringusername99** [comment]
Looker implements this as follows. Not to say they have it all right, but it's not a bad place to use as a reference:
* Max rows is defined at the report level. There isn't a separate control/limit for emails of that report (although I'm sure there must be a limit, I've never encountered it).
* After a certain amount of data, the emailer reverts to putting the data into an HTML file, which is attached, and the email body simply shows a message that the data exceeded the limit and is in the attachment.
* Data is formatted as HTML tables, and left up to the email client for display. Oftentimes, this means touch dragging to see the data, which is generally works OK.

**Comment by BembelGmbH** [comment]
@mazameli 
I think all the questions may be answered just by attaching a CSV or an EXCEL file to the email as pointed out in #2623 . One could solve all of these problems just by this attachment.

**Comment by JT1301** [comment]
This is about a year old, any update on this?

I think https://github.com/metabase/metabase/issues/2623 doesn't solved the request for everyone.

**Comment by mazameli** [comment]
Hi, everyone. If you're eager for this feature, could you please take a minute to read over the proposal in #6587 and let me know your thoughts? Thanks.

**Comment by georgiraychev** [comment]
Why is this issue marked as closed? I am using 0.28.0 and I am unable to add table in a Pulse.

**Comment by mazameli** [comment]
Yeah, I think this was mistaken for an issue that referenced including csvs or xls file attachments. This is not the same thing and has not yet been implemented.

**Comment by nileshtrivedi** [comment]
I just ran into the 3-column limitation for email pulses. An option to change these limits would be nice.

**Comment by jbrooksuk** [comment]
I recieved my first email from Pulses today and noticed that we only see the first 20 rows. I'd like this to be configurable as for this particular email we're using it to see the conversion of a Call Centre where there is no more than 30 agents. We'd now have to open Excel or similar to see the full response or give access to Metabase to a team who otherwise aren't interested in the rest of Metabase.

I understand that we wouldn't want a Pulse email with 2k rows, so it should be capped as you likely wouldn't be reading the full data anyway, but configurable per-pulse would be ideal.

**Comment by mazameli** [comment]
This feature was implemented back in April in [version 0.29](https://metabase.com/blog/metabase-0.29/index.html). 

I'll open up a separate issue for the suggestion @jbrooksuk and others have raised to allow for configurable row (and column) limits for tables in pulses.
