### ISSUE TITLE
[MLv2] fromLegacyQuery drops invalid expressions

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#38954]
**Context**

`fromLegacyQuery` drops valid expression and returns incorrect result

<img width="853" alt="Screenshot 2024-02-20 at 14 58 30" src="https://github.com/metabase/metabase/assets/125459446/dcf90d2a-bd43-4102-933a-975ec7c3807e">

### Steps to reproduce

```
Lib.fromLegacyQuery(
        databaseId,
        metadata,
        this.datasetQuery(),
      );
```

content of `this.datasetQuery()`

```
{
    "database": 1,
    "type": "query",
    "query": {
        "source-table": 6,
        "expressions": {
            "333": [
                "case",
                [
                    [
                        [
                            "is-empty",
                            [
                                "field",
                                5,
                                {
                                    "base-type": "type/Boolean"
                                }
                            ]
                        ],
                        "true"
                    ]
                ],
                {
                    "default": "false"
                }
            ]
        }
    }
}
```

and MLv2 query was 
<img width="872" alt="image" src="https://github.com/metabase/metabase/assets/125459446/86ea2346-9bf9-40be-96f0-a4d965935041">

- issue links: https://github.com/metabase/metabase/issues/38944

**Comment by uladzimirdev** [comment]
<img width="1158" alt="image" src="https://github.com/metabase/metabase/assets/125459446/5e451283-b023-4e36-9acc-4627ea26f1bf">

**Comment by metamben** [comment]
The issue is that for boolean expressions we don't like `"is-empty"`. `"is-null"` would work. MLv2 accepts `"is-empty"` for locations, text and text-like values. In many cases the `"is-null"` gets the display name `"is-empty"` anyway.

@uladzimirdev is it viable for the FE to use `"is-null"` for boolean values?

**Comment by metamben** [comment]
This thing has never worked properly. With MLv1, it was possible to create queries calling `isempty` on a number, but the execution would fail. Now, the invalid clause gets silently thrown away.

A possible short term solution is to implement a new MLv2 function doing type checking. (The long term solution is porting the editor/parser to MLv2 completely.) The signature of the new function could be something like

```typescript
diagnoseExpression(
  query: Lib.Query,
  stageIndex: number,
  expressionMode: "expression" | "aggregation" | "filter",
  mbql: any,
  expressionPosition?: number,
): ErrorWithMessage | null

type ErrorWithMessage = {
  message: string; // cannot highlight 
};
```
- `mbql` is a legacy MBQL expression like `["is-empty", ["field", 1, null]]`
- `expressionMode` specifies what  type of thing `mbql` is: an expression (custom column), an aggregation expression, or a filter condition.
- `expressionPosition` is only defined when editing an existing custom column and in that case it is the index of that expression in `expressions(query, stageIndex)`. It can be used to detect cyclic references.

**Comment by metamben** [comment]
The BE change has to be integrated to solve the problem.
