### ISSUE TITLE
Add entity-id to Serdes v1 as an optional flag

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38961]
**Context**
As we introduced entity-ids before releasing Serdes v2, some customers are facing problems to upgrade to Serdes v2.
[Thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1708378329446559)

The solutions is
1.v1 dump and load will copy the source's new entity_ids, but use v1's matching of source and target entities (which is presumably working okay for them and doesn't care about entity_ids)

now they have matching entity_ids so v2 works fine.

To make this happen, v1 must transfer entity-ids and overwrite the target entity-ids if they exist.
It should be added behind a flag --include-entity-id to both dump and load commands

This should be backported to 47 and 48.

**Comment by Tony-metabase** [comment]
Leaving comment so I know about updates
