### ISSUE TITLE
Accurate Error Messaging for Cross DB Joins in Notebook Editor

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#38989]
**Is your feature request related to a problem? Please describe.**
In Metabase you can presently select tables or models from multiple databases and join them together in the GUI query builder. This behavior is not supported so it fails. The error provided is "Card does not exists".

**Describe the solution you'd like**
A more clear error message should be presented. Something like, "Questions cannot be created using different database connections".

**Additional context**
This is a common point of confusion because the error message is ambiguous.

**Comment by ixipixi** [comment]
Realted to:

- https://github.com/metabase/metabase/issues/3953
- https://github.com/metabase/metabase/issues/28699

**Comment by mazameli** [comment]
The fix here is that the user should not be presented with questions, models, or tables to join with except for ones originating from the same database as the initial data source.

**Comment by ixipixi** [comment]
@mazameli Totally agree. If it's going to be a while before that's done it would still be really valuable to present a useful error message in the interim, though.

**Comment by romeovs** [comment]
I've put @mazameli's suggestion into a separate issue so we can keep this issue to be about the error message being vague.

**Comment by uladzimirdev** [comment]
@romeovs could you please link the new issue with @mazameli's suggestions?
