### ISSUE TITLE
Metric name to the tooltip in the stacked area

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3899]
Guys, 

1. Could you add the metric name to the tooltip in the stacked area 

![image](https://cloud.githubusercontent.com/assets/1708680/21028097/b6207bd6-bda4-11e6-8f09-493fca56d8c6.png)

or replace "Count" label to metric name:
![image](https://cloud.githubusercontent.com/assets/1708680/21028118/c9c09798-bda4-11e6-87fd-e60ac404131a.png)

Color markers really confused me when I work with many stacked charts with different colors.

Thank you for great product!

**Comment by anki-code** [comment]
For clear understand: I don't suggest remove colors and labels at the top of chart. I suggest add the label in tooltip in addition.

**Comment by mazameli** [comment]
This is really valid. Adding more colors to series (#3185) will definitely help, but I agree that the tooltip isn't helpful if you have > 5 or so series. 

I think if you have one metric broken out into multiple lines/bars due to a second grouping, you'd want the tooltip to display the label for that "bucket" rather than the label for the y-axis (e.g., `iOS` instead of `Count` as per anki's example). If you have more than one metric, e.g. by combining saved questions on a dashboard card, that's a little trickier — do you label the metric with the name of the saved question?

**Comment by anki-code** [comment]
![image](https://cloud.githubusercontent.com/assets/1708680/21248154/f0c6acf0-c345-11e6-9263-7e849b67e24f.png)

**Comment by anki-code** [comment]
Seems the good solution is to show three lines:
```
Name X: Value X
Metric group name: Metric name
Name Y: Value Y
```
For example:
```
Date: 2016-12-14
Platform: iOS
Registered users: 1043
```

**Comment by anki-code** [comment]
@mazameli a little more hell:

![image](https://cloud.githubusercontent.com/assets/1708680/21290599/d45d0c84-c4d1-11e6-93c4-ebaca40b86da.png)

**Comment by anki-code** [comment]
This issue and issue with sorting (3970) just kill my mind. One of my lovely use case is to make Stacked Area/Bar/Line chart and see segments in time. Without metric name on tooltip and sorting by segment size my mind want to get CSV and go away to Excel. Stacked charts analysis is really pain now.

@tlrobinson @mazameli

**Comment by anki-code** [comment]
@tlrobinson @mazameli could it will be fixed in 0.22?

Seems it's have MVP solution — add the name of segment to the tooltip.

**Comment by anki-code** [comment]
@tlrobinson is the #3899 should resolve this issue? 

I see the tooltip in pie chart and it's really cool (thanks!):
![image](https://cloud.githubusercontent.com/assets/1708680/21847382/ac80dbe8-d80c-11e6-849d-b68159334bf4.png)

But no the same tooltip in stacked area:

![image](https://cloud.githubusercontent.com/assets/1708680/21847460/19c59752-d80d-11e6-822f-599f57a7f4df.png)

**Comment by tlrobinson** [comment]
@anki-code #4107

**Comment by anki-code** [comment]
@tlrobinson very big thank you for this feature! 👍 🍺
