### ISSUE TITLE
Add alphabet sort in dashboards dropdown

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3900]
Could  you add the alphabet sort in dashboards dropdown?

Thank you for great product!

**Comment by camsaul** [comment]
@anki-code to clarify are you asking us to sort the dashboards alphabetically by their name?

**Comment by camsaul** [comment]
Related: there's a PR at #3860 but that does adds the sort to the frontend as opposed to the backend where we would want to do it

**Comment by anki-code** [comment]
@camsaul yes I means main list of dashboards. In #3860 I tried to do it for my current production metabase and it works:

![image](https://cloud.githubusercontent.com/assets/1708680/21029189/949ded68-bda9-11e6-9bf5-fbd1aa575f47.png)

**Comment by camsaul** [comment]
Implemented by #3902
