### ISSUE TITLE
BE flakes: redshift-lbv-sync-error-test and redshift-types-test

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#39046]
These are two seemingly related tests flaking on master. Example runs:

`metabase.driver.redshift-test/redshift-types-test`: https://github.com/metabase/metabase/actions/runs/7979299717/job/21786414703#step:3:954

`metabase.driver.redshift-test/redshift-lbv-sync-error-test `:
`https://github.com/metabase/metabase/actions/runs/7978492812/job/21785111342#step:3:920`

Judging by the stack trace, the only info we have is that a redshift exception is being thrown inside `metabase.sync.sync-metadata/sync-db-metadata!`

**Comment by WiNloSt** [comment]
fixed by https://github.com/metabase/metabase/pull/40310
