### ISSUE TITLE
Incorrect "Unaggregated field" warning with stacked charts

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3905]
![screen shot 2016-12-08 at 3 01 37 pm](https://cloud.githubusercontent.com/assets/107439/21031247/4a0466bc-bd57-11e6-9146-3b33d85ec365.png)

This is on the math frontend branch, I'm mapping `avg(tax)` and `sum(tax)/count()` against created_at::month

This shows up when I switch the bar chart to `100% stacked`

**Comment by krismp** [comment]
Any solution for this?

**Comment by GuiSim** [comment]
Still present in 0.24

**Comment by camsaul** [comment]
@GuiSim that's why the issue is still open 😉

**Comment by edenzik** [comment]
Also running into this - any workarounds?

**Comment by dataxpress** [comment]
Seeing this happen with any bar chart set to "Stacked" or "Stacked - 100%". Doesn't happen with "Don't Stack" set. Data seems OK, but warnings are scary!
