### ISSUE TITLE
Pin map uses inverted latitude and longitude

### ISSUE THREAD

**Issue by andrioni** [metabase/metabase#3906]
Hi, I'm having some issues with the new Pin Map on 0.21.0, it is apparently inverting latitude and longitude.

An example with the following dummy table created with two points (Union Square in San Francisco and the Statue of Liberty):
```
lat		lon
37.787904	-122.407514
40.689217	-74.044479
```
![2016-12-08-212838_1865x872_scrot](https://cloud.githubusercontent.com/assets/159177/21032041/f91229e2-bd8d-11e6-8fcf-74912dc8f404.png)

The table in Metabase:
![2016-12-08-212847_701x360_scrot](https://cloud.githubusercontent.com/assets/159177/21032052/05377128-bd8e-11e6-973b-e5825b22b810.png)

This is on Chrome 54.0 on Linux, running a dockerized Metabase with the tag v0.21.0 and using Redshift as the data source.

**Comment by tlrobinson** [comment]
My bad. I think Google Maps and Leaflet user opposite order of lat/lon, and our sample dataset uses random lat/lons so I didn't notice this :-/

**Comment by andrioni** [comment]
No problem! Unfortunately I forgot to test the RCs, so I only discovered this after the release of 0.21.0, but other than that things are pretty nice, and we've already deployed 0.21.0 to our users :)

**Comment by camsaul** [comment]
Fixed by #3907

**Comment by pdiniz13** [comment]
You might want to leave this issue open until 0.21.1 has been released. The default issue search on github is for open issues, so leaving this open might reduce the number of duplicate tickets for the same issue.
