### ISSUE TITLE
Remove "Enable nested queries" setting in the admin panel and set it to True on all instances

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#39071]
**Context**
When nested queries were introduced (many years ago), we added an option to restrict access to this feature (for performance reasons).
![image](https://github.com/metabase/metabase/assets/32561114/0030d796-d3a3-47ff-8ee9-30348c5f91bc)

Metabase evolved significantly and features in the product expect the use of nested queries (like Models).
Very few users change this setting and disabling nested queries makes the product worse.

- [x] Remove the option from the UI
- [x] Set this to True to all instances
- [x] Keep the env var. Users can disable nested queries using the env var.
- [ ] Fix the 20ish failing e2e tests
- [ ] Mention this in release notes

**Comment by nemanjaglumac** [comment]
Related: https://github.com/metabase/metabase/issues/28908
