### ISSUE TITLE
Maps not working for large GeoJSON file

### ISSUE THREAD

**Issue by mhemmings** [metabase/metabase#3909]
- Your browser and the version: Chrome 54.0.2840.98
- Your operating system: OS X 10.11.6
- Your databases: MySQL
- Metabase version: 0.21.0
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

I have a GeoJSON map for Timezone mappings. (https://github.com/candu/efele-tz-world-geojson)

The JSON file is quite large as far as geojson goes I think. Adding it as a custom map presents an infinite loading spinner that caused Chrome to use 100% CPU.  Refreshing the page appears to show the map has been successfully loaded. Then when asking a question and visualising it with the custom map, the same thing happens again; loading spinner that locks up Chrome at 100% CPU.

**Comment by tlrobinson** [comment]
It looks like that file 92.7MB... I'm not sure that's a reasonable size for us to support in a web app, though we should try to handle it more gracefully.

For comparison, GitHub's viewer does display it but it's incredibly sluggish even on my top-of-the-line MacBook Pro: https://github.com/candu/efele-tz-world-geojson/blob/master/tz_world.geojson

I'd suggest trying to reduce the precision of that file, perhaps using something like this: https://www.npmjs.com/package/geojson-precision

**Comment by mhemmings** [comment]
Thanks @tlrobinson
I'll try reducing precision and report back.

**Comment by mhemmings** [comment]
I've reduced the precision dramatically, with the file size about 1/3, but server still responds with a 500

**Comment by flamber** [comment]
Closing this in favor of #6343
