### ISSUE TITLE
H2 database connection must be read-only; auto-server mode not supported

### ISSUE THREAD

**Issue by mavimo** [metabase/metabase#3916]
## Setup

- Your browser and the version: Not relevant
- Your operating system: Not relevant
- Your databases: H2
- Metabase version: 2.21.0
- Metabase hosting environment: Docker
- Metabase internal database: H2

## How to reproduce

 - Have an application that use H2 database
 - Configure DB connection with: `file:/your/application/db;AUTO_SERVER=TRUE` as reported in placeholder

## Result

 - *Expected*:
> Database connection accepted
 - *Actual*:
> `org.h2.jdbc.JdbcSQLException: Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == SERIALIZED || fileLockMethod == FS || inMemory)" [50100-193]`

## Investigation

 - As I can see is not possibile connect to H2 database with options `AUTO_SERVER=TRUE` and `ACCESS_MODE_DATA=r` (see [`TestAutoServer::testUnsupportedCombinations`](https://github.com/h2database/h2database/blob/f3fcb6dbb1e9c68e591dd0b7097c2da77365d62b/h2/src/test/org/h2/test/server/TestAutoServer.java#L48) )
 - In metabase the `ACCESS_MODE_DATA` is enforced at the driver level to enforce user to do not write information in database, see [source code](https://github.com/metabase/metabase/blob/master/src/metabase/driver/h2.clj#L105).

I like that user can't write on DB, but this make impossible to connect to H2 database, any other user have the same issue?

## Proposed solution

I'll propose a PR to remove the `ACCESS_MODE_DATA` flag in the connection to allow user to use the H2 databases, since all other drivers do not block data insert at the driver level but enforce user to do it (eg creating a RO user or ...).

**Comment by camsaul** [comment]
@mavimo why do you need to connect to an H2 DB file with `AUTO_SERVER=TRUE`? 

We want to make sure connections to DBs are read-only.

**Comment by mavimo** [comment]
@camsaul: i have an application running in a docker container with H2 db stored in a exposed volume. I'm sharing the same db with metabase and I want to connect to this db, so I need to connect using the option "auto server" (as also reported in the input placeholder)

**Comment by salsakran** [comment]
@mavimo is this for the MB application database or a DB you want to analyze w/ Metabase?

**Comment by camsaul** [comment]
@salsakran it's with an external DB, the application DB can't be read-only 😉

**Comment by salsakran** [comment]
doh.

**Comment by mavimo** [comment]
@camsaul do you have some suggestion on how to read an H2 db?

PS: the AUTO_SERVER is indicated as default value in placeholder, see
<img width="903" alt="screen shot 2016-12-13 at 20 23 27" src="https://cloud.githubusercontent.com/assets/43941/21155332/169c83e4-c172-11e6-8273-224a0bb9cdb2.png">

**Comment by camsaul** [comment]
good point @mavimo, we probably shouldn't include that in the placeholder if you're not allowed to use it 😓

**Comment by camsaul** [comment]
Closing this out since we don't have any plans to allow readwrite connections for H2 in the future.
