### ISSUE TITLE
[BUG] Queries do not update after model changes

### ISSUE THREAD

**Issue by Pierre-PSUD** [metabase/metabase#39188]
### Describe the bug

When I want to change my model (model1) (ie. change the repository folder, add a colmun, remove a column...), it creates a new question (that I further transforms in model (model2)) and then it does not update my model (model1). I can't modify model1 without creating another question with the graphical interface.

The problem is : if I want to update all the questions that are linked to model1 to have the model2 as a reference for these questions, I have to update all the questions one by one. Thus, if I have a question, I am not sure that the reference model of this question is aligned with the model.

### To Reproduce

1. Create a model named model1
2. Create a question / indicator based on model1 : for instance, the number of lines in model1
3. Modify model1 to apply a filter for instance on a given column (the number of lines of the model must change)
4. To register the modification, you have to create a new question and then transform it as a model
5. You don't need anymore of model1 and you decide to archive it
6. [ERROR] The question / indicator still points out the number of lines of model1 and not of model2

### Expected behavior

The model1 should have changed and queries should have been modified after model1 update

### Logs

-

### Information about your Metabase installation

```JSON
- Windows 10
- Firefox version 115
- Database : postgreSQL
- Metabase version : v1.48.4 (released on 2024-01-29)
- French version
```

### Severity

Slow down the development time of dashboards and is annoying

**Comment by luizarakaki** [comment]
You need to "Edit query definition" of the model.
https://www.metabase.com/docs/latest/data-modeling/models#edit-a-models-query
A model is like a table, if you just add or change clauses, it saves a new question.

**Comment by Pierre-PSUD** [comment]
Thank you Luiz ! Have a nice day
