### ISSUE TITLE
Odd characters - wrong charset?

### ISSUE THREAD

**Issue by bedeoverend** [metabase/metabase#3918]
Hi there - so I'm getting a few odd characters on my frontend version of metabase. For example, in the query builder instead of `...`, I'm getting `â€¦` - that's for the drop down sort / limit menu. 

Looks like it's a charset issue? The resource header has `content-type: text/html; charset=ISO-8859-1` even though the document has a `<meta charset="utf-8">`. Not sure where the discrepancy is...jetty?

My app is running on Google Cloud App Engine in a docker file.

- Custom dockerfile with openjdk:8 dockerfile as a base
- Running either 0.20.3 or 0.21.0 jar versions
- Chrome 55 / Safari 10
- Application DB: MySQL 5.7

**Comment by camsaul** [comment]
Metabase assumes UTF-8 everywhere so that `Content-Type` header `charset` is definitely wrong 😓 

@bedeoverend did you say you're running a custom version of Metabase? Are you seeing the same issues with the official JAR?

**Comment by bedeoverend** [comment]
@camsaul I'm running a custom Dockerfile i.e. not Metabase Dockerfile - but I'm still just pulling down the standard JAR: `ADD http://downloads.metabase.com/v0.20.3/metabase.jar ./metabase.jar`

Given I'm using App Engine, the instance is behind a load balancer, therefore I'd say it's behind an NGINX proxy. I'll try running the dockerfile locally as well to see if the proxy is messing with the headers.

**Comment by camsaul** [comment]
Thank @bedeoverend, let me know how that goes. We're not specifying the charset in the `Content-Type` header so it sounds like something is adding it there for us. I haven't heard of anybody having the same issue on Elastic Beanstalk which is also behind an nginx proxy so I'm guessing it might be something to do with the way the App Engine one is set up.

We might be able to remedy this by just specifying an encoding so something doesn't try to be helpful and add the wrong one for us.

**Comment by bedeoverend** [comment]
@camsaul running the dockerfile locally, it doesn't attach the `charset=ISO-8859-1` header. I'm going to run some more tests (I had to tweak the dockerfile slightly running it locally) but I'd say it's App Engine's proxy.

Even if this is a proxy issue, would you be open to explicitly declaring `charset="utf-8"?

**Comment by camsaul** [comment]
@bedeoverend explicitly declaring the encoding it can't hurt anything and it's certainly better than having something assume otherwise. So we can definitely add it.

The real mystery here is why App Engine is adding the wrong encodings to `Content-Type` headers 😓

**Comment by camsaul** [comment]
@bedeoverend this is only a one-line change I think, so I can add it to our upcoming 21.1 release.

**Comment by camsaul** [comment]
@bedeoverend I've added charset to the `Content-Type` in PR #3932. I can't guarantee that the App Engine won't still overwrite it but I'm hoping they won't.

You're welcome to give it a try if you want; if you check out the branch you can build the JAR yourself [by following the steps here](https://github.com/metabase/metabase/blob/master/docs/developers-guide.md). Otherwise we plan on releasing 0.21.1 with this fix in the next few days or so.

**Comment by camsaul** [comment]
Fixed by #3932

**Comment by bedeoverend** [comment]
@camsaul thanks for responding / patching so quickly, really appreciate that. I'll see if I can test it out to make sure it's patched it.

For anyone coming across this issue / thread later, I've done some more digging, and it looks like it's only happening with App Engine vms that are using the older flexible environment configuration i.e. in your `app.yaml` have `vm: true` rather than `env: flex`. I can't use `env: flex` due to some redirection problems at the moment, but looks like the now deprecated `vm: true` is the only scenario where this happens.

**Comment by bedeoverend** [comment]
@camsaul FWIW just upgraded my live app to 0.21.1 and it's working beautifully 👌 thanks for all the hard work!

**Comment by camsaul** [comment]
@bedeoverend glad to hear it 🎉
