### ISSUE TITLE
Users can't access audit models in other collections unless they have access to metabase analytics

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#39198]
### Describe the bug

If you duplicate an audit model anywhere outside the analytics collection, you won't be able to use it unless you have access to the original metabase analytics collection. It won't matter if you have access to the audit permission in the permissions menu in settings, seems like the metabase analytics collection is completely independent of that.

### To Reproduce

1) as an admin, duplicate any audit model to our analytics
2) create a new user and a new group
3) give the second group access to the audit permission in the settings (optional, this doesn't matter as https://github.com/metabase/metabase/issues/39197)
4) then make sure that the second user does not have access to metabase analytics collection
5) go with the second user to the model that you duplicated in our analytics, see the error
![image](https://github.com/metabase/metabase/assets/1711649/84909356-f15a-4f99-8bba-b6ab8ac71d45)

### Expected behavior

If a user has collection permission to the collection + data permissions, then it should see the data

### Logs

NA

### Information about your Metabase installation

```JSON
v48.x
```

### Severity

P1

### Additional context

Seems that giving access to metabase analytics conjugate data + collection access, which should not be the case as we always split those 2

Data access to audit info should be given from settings->admin->permissions->application
Collection permissions should be given from settings->admin->permissions->collection

**Comment by luizarakaki** [comment]
This is by design... Acccess to Metabase analytics is conditioned to the collection permission. We are removing "Audit" and "Audit permission" soon
