### ISSUE TITLE
Enabling "don't send if there aren't results" in a subscription won't send the text cards

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#39190]
### Describe the bug

Enabling
![image](https://github.com/metabase/metabase/assets/1711649/4db2ead7-7668-41e3-b8cc-ea8d37225ffb)

won't send the text cards in the dashboard sub

Enabled
![image](https://github.com/metabase/metabase/assets/1711649/de60c72e-b053-47d5-ba66-45bc82420924)

Disabled
![image](https://github.com/metabase/metabase/assets/1711649/3e20a870-9e58-4134-b965-87e7eb76bf34)

The reason is that text cards don't have results and that's why https://github.com/metabase/metabase/pull/37546 wiped them

### To Reproduce

1) create a dashboard
2) add text cards
3) enable "don't send if there aren't results"
4) send the test email

### Expected behavior

Text cards should be always included

### Logs

NA

### Information about your Metabase installation

```JSON
v48.6
```

### Severity

P1

**Comment by Tony-metabase** [comment]
This still happens

**Comment by adam-james-v** [comment]
The fix has been [backported to x.48.x now](https://github.com/metabase/metabase/pull/39942), so this can be closed again.
