### ISSUE TITLE
Regression: BigQuery - empty 'Choose an aggregation' dropdown

### ISSUE THREAD

**Issue by bedeoverend** [metabase/metabase#3919]
As of 0.21.0, when building a query for a BigQuery DB, the 'Choose an aggregation' dropdown is empty, doesn't show any fields - it has a height of 0.

<img width="336" alt="screen shot 2016-12-12 at 4 46 19 pm" src="https://cloud.githubusercontent.com/assets/594822/21089254/8bf1c124-c08a-11e6-87fe-988f8b379a22.png">

My app is running on Google Cloud App Engine in a docker file.

- Custom dockerfile with openjdk:8 dockerfile as a base
- Running 0.21.0 jar versions, _works_ on 0.20.3
- Chrome 55 / Safari 10
- Application DB: MySQL 5.7

**Comment by camsaul** [comment]
Fixed by #3931

**Comment by bedeoverend** [comment]
Thanks @camsaul - response rate on metabase issues is fantastic 👍
