### ISSUE TITLE
Audit collection permission not the same as audit permission in settings

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#39197]
### Describe the bug

If you enable permissions in settings->admin->permissions->application->audit, that will only enable permissions for the audit section of the settings, but it will NOT grant permissions to the audit collection, which seems odd.

### To Reproduce

1) create a second group and a second user, add the second user to the second group
2) go to the permissions, assign permissions to app-> audit to the second group
3) try going to metabase analytics collection with the second group, you can't

### Expected behavior

if a user has permissions access to the audit, it should see metabase analytics

### Logs

NA

### Information about your Metabase installation

```JSON
v48.x
```

### Severity

P2

**Comment by luizarakaki** [comment]
When upgrading to 48, we granted permissions to the Metabase Analytics to all users with Audit access. But now, the permission to Metabase analytics is based on the collection permission and we will remove the audit permission with the audit feature in the next release.

**Comment by luizarakaki** [comment]
Audit tab and audit permission was removed on v50.
