### ISSUE TITLE
Ability to divide exported PDF into sections

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#39218]
**Is your feature request related to a problem? Please describe.**
If you want to print (cmd+p, ctrl+p) a PDF exported dashboard, it will come out wrong as there are no page divisions; it is recognized as a single page only.
Instead, you will get a very small part of the dashboard or a very tiny view of the entire dashboard (which is unreadable). 

**Describe the solution you'd like**
Ability to configure pages in PDF exports

**Describe alternatives you've considered**
External tools, but none that we support.

**How important is this feature to you?**
Requested by a customer, internal ticket: [#25247](https://metabase.zendesk.com/agent/tickets/25247)

**Additional context**
Related to https://github.com/metabase/metabase/issues/33876

**Comment by brunobergher** [comment]
My read is that this more along the lines of "Ensure browser-generated PDFs and prints of dashboards are correct", no?

**Comment by cdeweyx** [comment]
Mostly addressed with https://github.com/metabase/metabase/pull/49917 — Still not configurable, but I'm hoping sensible page breaks get us far enough for the time being. Closing for now.
