### ISSUE TITLE
Minified links for unsaved queries

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3924]
Hi guys! Thank you for great product!

I want to copy link on temporary Question. My use case:

1. I want to show the data to my teammate but don't want to save new question
2. I click "New question"
3. I build query and copy the link. The link is toooooo long: (https://mymetabasehost/qweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoierqweioruwoier==)

Can I get minified link like "https://mymetabasehost/q/vnqekjrnf"?

**Comment by camsaul** [comment]
@anki-code, if you're copying-and-pasting the link, why does it matter how long it is?

**Comment by anki-code** [comment]
It looks brutal in group chats. Our Slack channel for example:

![image](https://cloud.githubusercontent.com/assets/1708680/21119215/a27e5d38-c0d2-11e6-9015-2feb1d46e4de.png)

**Comment by anki-code** [comment]
@camsaul When your team are digging the data they want to show the results of queries but don't want to save it as saved questions. It's realtime ad-hoc data analysis. When every link have SEVEN lines of URL in Slack chat it's really sad for other teammates to see the discussion.

**Comment by anki-code** [comment]
@camsaul  Some of our team install Chrome extensions for shorting links :) Close this issue if you want :)

**Comment by anki-code** [comment]
But it's not a full solution. "goo.gl" and Bitly can't convert very long links.

**Comment by anki-code** [comment]
One thought: gzip data - https://github.com/beatgammit/gzip-js

**Comment by anki-code** [comment]
I'm going to close this issue because as result I think the best way is the Google Docs style of sharing.

![image](https://user-images.githubusercontent.com/1708680/29028276-6091c73c-7b8c-11e7-9667-d4800a3d50bf.png)
