### ISSUE TITLE
Enable option to sync after action

### ISSUE THREAD

**Issue by atharen** [metabase/metabase#39245]
### **Is your feature request related to a problem? Please describe.**
I have a model action to insert a record in a PSQL table.
The insert is successful, and can immediately be identified with a direct PSQL connection.

Problem is Metabase is not updated to reflect the change.
I presume it will do so when it re-syncs.

### **Describe the solution you'd like**
I would like the option to trigger a re-sync when an action is successful.

### **Describe alternatives you've considered**
- Setting the model sync interval to hourly.
- Using a dashboard to auto-update the request every minute.
- Considered, running a POST request in PSQL to trigger it using the API (_bit much_)

### **How important is this feature to you?**
It is about having a user-intuitive system; when a user runs an action to save on the db, I think reasonable to expect it to be nearly instant. Waiting an hour seems absurd...

### **Additional context**
- Could not find any related issues (Tried searching for "actions sync")
- From the forums, this was the most related: 
  - https://discourse.metabase.com/t/it-would-be-nice-to-be-able-have-a-parameter-to-update-more-often-the-schema-resync/9654/3
- Followed Model Caching documentation: https://www.metabase.com/docs/latest/data-modeling/models#model-caching

**Comment by calherries** [comment]
@atharen Do you have model caching enabled for the model you are inserting a record to? I think you could be running into this issue https://github.com/metabase/metabase/issues/33149. When model caching is enabled an action to insert a row will not update the model data.

**Comment by atharen** [comment]
Hmm I did not have caching enabled.

Since then I just settled on using the dashboard auto-update, and that seems to work fine. 
With that it also has user feedback is listing the next upcoming update.

To be honest, have not looked into this much since then, so I'd say worth closing this issue for now, since I am not able to properly follow up on it.
