### ISSUE TITLE
metabse used wrong actualRoot, that caused it cannot load resources

### ISSUE THREAD

**Issue by vjuswei** [metabase/metabase#39253]
### Describe the bug

        <meta name="apple-mobile-web-app-status-bar-style" content="default"/>
        <meta name="base-href" content="/metabase/"/>
        <meta name="uri" content="/metabase/"/>
        <title>Metabase</title>
        <base href="/metabase/"/>

it meta data <meta name="uri" content="/metabase/"/>, that caused  the code 
        if (actualRoot !== configuredRoot) {
            console.warn("Warning: the Metabase site URL basename \"" + configuredRoot + "\" does not match the actual basename \"" + actualRoot + "\".");
            console.warn("You probably want to update the Site URL setting to \"" + window.location.origin + actualRoot + "\"");
            document.getElementsByTagName("base")[0].href = actualRoot;
        }
was trigger

    <meta name="uri" content="/metabase/"/> should be <meta name="uri" content="/metabase/"/>
<meta name="uri" content="/"/>
 
How can I set the content of meta name="uri" ?
        

### To Reproduce

no clue

### Logs

metabase/:21 Warning: the Metabase site URL basename "/metabase/" does not match the actual basename "/".

metabase/:22 You probably want to update the Site URL setting to "https://our-domain/"

### Information about your Metabase installation

```JSON
I cannot login to metabase
```

### Severity

block

**Comment by paoliniluis** [comment]
is this a question or an issue?
