### ISSUE TITLE
SQL variables have no behavior when the filter is empty

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3925]
Hi guys! Thank you for great product!

I try to use Variables in SQL. And I want to realize the use case:
1. When filter Created At is empty I want to see LAST WEEK
2. When filter Created At is set I want to see data by filter

How I can realize this behavior?

![image](https://cloud.githubusercontent.com/assets/1708680/21112534/25437c24-c0b7-11e6-916e-794c23a2891b.png)

⬇️ Please click "like" instead of "+1" comment

**Comment by camsaul** [comment]
@anki-code I think you have to add the Card to a dashboard to use field filters. @tlrobinson is that correct?

**Comment by anki-code** [comment]
@camsaul no. I try explain again :)

Example of usecase. I have line chart for registered users (Y) by CreatedAt date (X) on SQL. I want to add this chart to dashboard with filter by CreatedAt. BUT when the filter value is empty I want to see registrations for last week.

![image](https://cloud.githubusercontent.com/assets/1708680/21131813/ccd9dc34-c121-11e6-9371-b56145c3ce31.png)

**Comment by anki-code** [comment]
The solution could be the form for value of Variable when it is not set (for now default value is "1=1" but it's bad solution for me I can't use another behavior when the filter is not set).

**Comment by camsaul** [comment]
@anki-code I was asking @tlrobinson to help clarify, not you 😉

**Comment by anki-code** [comment]
JFYI: I'm not using any filters in dashboards because I can't set the default behavior. For example for DATETIME fields I need to set default filter "past month/week/day".

**Comment by flamber** [comment]
Hi @anki-code 
This seems to have been solved with "Default filter widget value" in the question. So when using filter on the dashboard, when empty it will use the default value, otherwise it will use the specified value. 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52903724-63052a00-31e7-11e9-8b3f-5435de253b17.png)

**Comment by flamber** [comment]
Or alternatively use Complex Default Value:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#default-value-in-the-query
