### ISSUE TITLE
Can't select NULL value in date filter

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3926]
Hi guys! Thank you for great product!

I can't select users who have DeletedAt = NULL in case:

![image](https://cloud.githubusercontent.com/assets/1708680/21114921/f891b84a-c0bf-11e6-990a-a82ec94be967.png)

**Comment by kdoh** [comment]
Hey @anki-code. Based on the example you provided if you'd like to see all the users who haven't been deleted you can click on "Previous" and then select "Is empty" from the dropdown to change the type of date filtering. Conversely, to see all deleted users you'd select "Is not empty"

I'll assume from you filing the issue you had a hard time finding the option. Were you unable to find the dropdown or was the difference in terminology we use "Empty" vs "Null" the point of confusion?

**Comment by anki-code** [comment]
Wow @kdoh thank you! I think that "Previous \/" label is just title for edit with "30". Sorry for stupid issue and thank you for help!

**Comment by kdoh** [comment]
@anki-code Not a stupid issue at all. Thanks for letting us know you had trouble.
