### ISSUE TITLE
Permissions to view for certain dashboards

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3928]
Hi guys! Thank you for great product!

Our team have external partners and investors who want to see certain metrics. We need feature with view only certain dashboards. User can view certain dashboards and question cards which placed on them. User can't edit or view query. User can't view other dashboards or question cards.

**Comment by camsaul** [comment]
@anki-code we're working on adding ways to manage Permissions for "Collections" of Cards. We have an open issue here: #3363
