### ISSUE TITLE
Tab no longer selects highlighted item in filter drop-down

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#39288]
### Describe the bug

- Tab behavior on Search box filters changed in `master`

### To Reproduce

1. Admin > Table Metadata > Sample Database > Products > Vendor > select ⚙️ and change Filtering on this field to Search box
2. Create a new question from Sample Database > Products
3. Click the heading Vendor > Filter by this column > IS > type `keely` and press <kbd>Tab</kbd>

### Expected behavior

Expect <TAB> to select highlighted value like it does in prior versions (47, 48, etc.)

### Information about your Metabase installation

```JSON
- works in 48.7
- not working in `master` as of `03e7fa4`
```

### Severity

P2: Frustrating regression but has workaround (click with mouse)

**Comment by kamilmielnik** [comment]
Introduced in #36539 when we started to use Mantine's `MultiSelect`.

**Comment by kamilmielnik** [comment]
We can fix it using [`selectFirstOptionOnChange` prop](https://mantine.dev/core/multi-select/?t=props).
We'd need to upgrade Mantine to v7, see https://github.com/mantinedev/mantine/pull/4997 (https://github.com/mantinedev/mantine/commit/66fe076971d9a80b7af078a6fa8726254d4f6258).

**Comment by perivamsi** [comment]
I don't think this should be a release blocker for 49, @likeshumidity is there more context to why you picked 49 as the milestone?

**Comment by MathiasGr** [comment]
FYI, we upgraded to 49 a few hours ago, and our entire analyst team is complaining that they used to copy-paste multiple values into the filter dropdown and cannot do that anymore with the new component. That was a fairly important use case and will come up as feedback from many teams. I know you have a full roadmap but whatever you can do to prioritize a fix would really help us!

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/40265

**Comment by paoliniluis** [comment]
fixed
