### ISSUE TITLE
Provide a place in the Getting Started Guide for global information

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3929]
Hi guys! Thank you for great product!

In our team we have group of abbreviations for naming metrics. For fun example:
- NU - Newbie user
- MU - Mature user
- UWLOP - user who love our product
- UWAAFST - user who away from first session
etc :)

We need page (or text area in Data Reference) for describe these abbreviations. But we can't use your "referenced metrics" because our metrics is complex metrics (calculated thru sql) which not created as "Metabase Metrics".

**Comment by anki-code** [comment]
May be the solution is to moving text area in "What should a user of this data know before they start accessing it?" to the top of the page when other fields is empty.

**Comment by camsaul** [comment]
@anki-code, could you include this sort of information in a [Getting Started Guide](http://www.metabase.com/docs/latest/administration-guide/10-getting-started-guide.html)?

**Comment by anki-code** [comment]
What I need:
![image](https://cloud.githubusercontent.com/assets/1708680/21132482/5664cc4a-c125-11e6-87a5-9c4169cca8fe.png)

**Comment by salsakran** [comment]
I'm going to rename this to reflect the underlying goal - providing company wide/team wide information and caveats regarding the data + artifacts available as a whole vs tied to a specific metric.

Separately, @anki-code you would probably get more buy-in from the folks on the team and contributors if you smoothed over your tone a bit. While we appreciate that you chose to use us and that you care enough to tell us what you need, we are not here to fill change requests you might have. We have thousands of other users whose needs we also need to take into account.

**Comment by salsakran** [comment]
actually, scratch that. @mazameli reminded me that we actually do have that.

You should fill out the below entry.

![screen shot 2016-12-13 at 11 30 38 am](https://cloud.githubusercontent.com/assets/107439/21155615/a72e6cce-c127-11e6-8139-2c6e187eee16.png)

**Comment by anki-code** [comment]
@salsakran,
1. sorry for my tone. My english is not so good. I really like your product and I just want express our team use cases and bugs.

2. I wrote above why this block (on your screenshot) is unusable:
- New lines aren't supported
- Links aren't supported
- Pin on top of the page isn't supported

Thank you!
