### ISSUE TITLE
Add syntax for describe the metabase columns in SQL queries

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3930]
Hi guys! Thank you for great product!

Could you add the syntax for mark fields as the metabase columns? For example when I want to build a table with UserId column I want to click on the value in UserId column and go to the user inforamtion as it working with query builder.

![image](https://cloud.githubusercontent.com/assets/1708680/21117932/cca00586-c0cc-11e6-835b-ad8d4350fbe0.png)

**Comment by anki-code** [comment]
Or it could be:

`select UserId as "User id column name [metabase:dm.Users:UserId]" ...`

This way is better because I can get this question and use in SQL Client without editing.

**Comment by camsaul** [comment]
Basically asking for the same thing as #1608
