### ISSUE TITLE
Cached MetadataProvider should store tombstones (e.g. `::nil` markers) for things we tried to fetch that didn't exist

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#39326]
If we try to get Card 100 from a CachedMetadataProvider and it doesn't exist, we should record that fact somehow (maybe by saving `::nil` in the cache) and return `nil` right away the second time around rather than trying to fetch it again. That way we're avoiding potentially expensive hits if it's wrapping something like the ApplicationDatabaseProvider

From the TODO

```
src/metabase/lib/metadata/cached_provider.cljc:65:        
;; TODO -- we should probably store `::nil` markers for things we tried to fetch that didn't exist
```

**Comment by iethree** [comment]
🚀 This should also be released by [v0.51](https://github.com/metabase/metabase/milestone/231)
