### ISSUE TITLE
Rename `metabase.driver.sql.util.unprepare/unprepare` to something more appropriate

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#39339]
`src/metabase/driver/sql/util/unprepare.clj` line `83`:
```
;; TODO - I think a name like `deparameterize` would be more appropriate here
```

**Comment by camsaul** [comment]
I think the right way to fix this is to tackle #28169 and remove it entirely. With Honey SQL 2 you can have it compile everything `:inline`, so we'd have no need to compile with `?` and immediately undo things.
