### ISSUE TITLE
Rename the `metabase.driver.sql.util.unprepare` to `metabase.driver.sql.unprepare`

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#39331]
Why? Because it's no longer just an util namesapace. As the namespace contains defmultis, the change would have to be communicated through the change log / depreciations. See the docstring of the namespace in question for more info.

**Comment by camsaul** [comment]
I think the right way to fix this is to tackle #28169 and remove it entirely. With Honey SQL 2 you can have it compile everything `:inline`, so we'd have no need to compile with `?` and immediately undo things.
