### ISSUE TITLE
Remove Metadata schemas in `lib.metadata` and use the versions in `lib.schema.metadata` instead

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#39334]
Originally Malli schemas for MLv2 metadata like `ColumnMetadata` lived in `metabase.lib.metadata`, a while ago we moved them to `metabase.lib.schema.metadata` so they could live with all of the other MLv2 schemas. Now `ColumnMetadata` is a just a `def` for `::lib.schema.metadata/column`. Let's just use the keyword versions like `::lib.schema.metadata/column` directly everywhere and get rid of the defs in `metabase.lib.metadata`, we don't need two ways to refer to the same thing.

**Comment by bshepherdson** [comment]
Going one step further, there are schemas for queries and parts of queries in the QP codebase as well, which seem to overlap with `metabase.lib.schema.*`. These should be unified, probably in the `lib.schema.*` namespaces.

**Comment by camsaul** [comment]
Fixed by #42070
