### ISSUE TITLE
Remove duplicate `mbql-clause?` fn

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#39333]
One is in mb.mbql.schema.helpers, one is in mb.mbql.util

```
src/metabase/mbql/schema/helpers.cljc:27:;; TODO - this is a copy of the one in the [[metabase.mbql.util]] namespace. We need to reorganize things a bit so we
```

**Comment by sdduursma** [comment]
Hello, I'm interested in contributing to Metabase, and this issue seems like a good one to start with. To make sure, is this issue still relevant, and would you accept an external contribution?

**Comment by darksciencebase** [comment]
@sdduursma yes! (and thank you for your interest in contributing to Metabase)

**Comment by sdduursma** [comment]
Thanks @darksciencebase, I've opened a PR with a proposed solution: https://github.com/metabase/metabase/pull/40945
