### ISSUE TITLE
Disallow and/or automatically fix filters like `:between` or `:inside` with min and max in the wrong order

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#39342]
```clj
[:between {} <field> 200 100]
```

gets compiled to something like 

```sql
WHERE field >= 200 
  AND field < 100
```

which does not give you any results. I think we should probably switch these values around automatically in the MLv2 functions if we see them (DWIM) and also enforce these constraints in the relevant schemas. Hopefully this shouldn't be a big deal for existing queries since those queries would have been broken anyway.

**Comment by ranquild** [comment]
Argument swapping is done on the FE now
