### ISSUE TITLE
For drivers not downloaded popup explanation & hyperlink to documentation

### ISSUE THREAD

**Issue by davidjhpgcc** [metabase/metabase#3935]
Site Administration -> Databases -> Add Database

The Database Type option list currently does not include drivers that due to licensing restrictions need to be downloaded by the user themselves.  

I recommend listing all database types in the list, and for those that are not yet downloaded such as Vertica, when selected a popup is displayed telling the user they need to download themselves, and link to the documentation.

This will save a lot of time in the future for both users and Metabase, and prevent unncessary tickets to be submitted.

References
https://github.com/metabase/metabase/issues/3934
http://www.metabase.com/docs/latest/administration-guide/databases/vertica.html

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
@metabase/core-developers it's probably not a bad idea to do something like this or more generally provide more links to the documentation in the app

**Comment by anki-code** [comment]
+1
