### ISSUE TITLE
Add more robust handling of `?` in `unprepare :sql`

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#39353]
`src/metabase/driver/sql/util/unprepare.clj` line `103`:
```
      ;; TODO - this is not smart enough to handle question marks in non argument contexts, for example if someone
      ;; were to have a question mark inside an identifier such as a table name. I think we'd have to parse the SQL in
      ;; order to handle those situations.
```

Seems that TODO can be addressed easily when the https://github.com/metabase/metabase/issues/36911 is resolved.

**Comment by camsaul** [comment]
I think the right way to fix this is to tackle #28169 and remove it entirely. With Honey SQL 2 you can have it compile everything `:inline`, so we'd have no need to compile with `?` and immediately undo things.
