### ISSUE TITLE
[ux bug] No segment when choose connected table

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3937]
Hi guys! Thank you for great product!

Segment when choose connected table:

![image](https://cloud.githubusercontent.com/assets/1708680/21134606/b2d48cb8-c12f-11e6-9532-e085482fa2fc.png)

**Comment by anki-code** [comment]
@camsaul could you please comment here please :) Is it a bug or feature?

**Comment by anki-code** [comment]
RIP

**Comment by mvrabel** [comment]
We would love to have this feature.
@anki-code Should we create a feature request instead of a bug ? maybe it will catch on :)

**Comment by flamber** [comment]
Closing in favor of #4480
