### ISSUE TITLE
Getting this error CORE_USER.IS_STAFF not found

### ISSUE THREAD

**Issue by beanHead** [metabase/metabase#3938]
**org.h2.jdbc.JdbcSQLException: Column "CORE_USER.IS_STAFF" not found;**

Getting this error when trying to log into my Metabase account. Please guide me on this and how to resolve it.

**Comment by camsaul** [comment]
Did you upgrade to a new version of Metabase and then downgrade back to an old version? We removed some unused things in Metabase v0.20.0. I'd recommend [upgrading to the latest version, v0.21.0](http://www.metabase.com/start/).

**Comment by beanHead** [comment]
Yes I did, it solved the previous issue. But all my charts are now showing this error: (not ("Valid field type" :TextField))

**Comment by salsakran** [comment]
do they work if you recreate them using the same data/definition?

**Comment by beanHead** [comment]
No, if I'm creating using New question with the same data/definition, the filter isn't giving me relative, specific etc. options for date filter, also if I apply any other filter it doesn't give me any result. It gives me error message as (not ("Valid field type" :IntegerField))

**Comment by camsaul** [comment]
@beanHead yeah upgrading to Metabase v0.20.x and back down to v.0.19.x and then back up to a newer version will break things 😢 

You might be able to fix it by forcing the data migration to run again by doing

```sql
DELETE FROM data_migrations
WHERE id = 'fix-invalid-field-types'
OR id = 'migrate-field-types'
```

against the Metabase application DB and restarting Metabase.

**Comment by camsaul** [comment]
@beanHead did that fix your issue?

**Comment by camsaul** [comment]
Closing this out as No Longer Relevant since this was an issue specifically with upgrading from 0.19.x to 0.20.0 and reverting back to 0.19.x
