### ISSUE TITLE
[dc.js migration] non-bar funnel does not work in subscription

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39395]
<img width="600" alt="Screenshot 2024-02-29 at 11 18 48 AM" src="https://github.com/metabase/metabase/assets/37751258/1ddf61f5-cabc-49fe-89f7-d37b051c129d">

http://localhost:3000/question/266-funnel-user-flow

**Comment by alxnddr** [comment]
@EmmadUsmani this is probably not related to ECharts and did not work before

**Comment by EmmadUsmani** [comment]
@alxnddr Yup I'm closing as a duplicate of https://github.com/metabase/metabase/issues/39743
