### ISSUE TITLE
"Scraping Metabase"  using Phantomjs showing empty widgets

### ISSUE THREAD

**Issue by AvnerCohen** [metabase/metabase#3940]
(Thanks so much for making metabase!)
I'm looking to publish a dashboard on some time schedule.
While `pulse` is the initial solution I  considered, it is way too limited at this point (single widget, hard to personalize, etc).

Since dashboards are so nice, I thought I'd work around that with a simple casperjs script:

```js
var casper = require('casper').create({
    verbose: true,
    onPageInitialized: function (page) {
     page.evaluate(function () {
        window.screen = {width: 1920, height: 1080 };
    });
    }
});

casper.start('https://xxx.xxx.com/dash/2', function() {

    casper.thenEvaluate(function(){
        var _event_ = new Event('input', { bubbles: true });
        document.getElementsByName("email")[0].value = "aaaa@aaa.com";
        document.getElementsByName("password")[0].value = "passowrd_in_here";
        document.getElementsByName("email")[0].dispatchEvent(_event_);
        document.getElementsByName("password")[0].dispatchEvent(_event_);
        document.getElementsByClassName("Form-actions")[0].firstChild.click()

    });
    casper.wait(8000, function() {
        this.capture('metabase.png', {
                top: 60,
                left: 0,
                width: 1920,
                height: 1080
            });
    });

});

casper.run();
```

However, the results where not great:
<img width="636" alt="skitch 5" src="https://cloud.githubusercontent.com/assets/1297254/21152707/31dfb524-c170-11e6-8050-501dcc0f34a9.png">

Any suggestions?

**Comment by mazameli** [comment]
Well, if we rewind for a second, what would you ideally like to add to or change about Pulses to get them to work for this use case?

**Comment by AvnerCohen** [comment]
Well. I can go into more details (pulse limits in terms of dataset size, widget selection etc) but what I would really like is to simply be able to "export" dashboard as a PDF or an Image (which is kind of what I tried to hack my way into).

Hopefully this makes some sense.

**Comment by aagarwal-gtr** [comment]
@AvnerCohen #3847 and #3770 
also agree on having to adjust everything to the pulses limitations (which is by design i suppose), dashboard export will solve a lot of these problems

**Comment by AvnerCohen** [comment]
Cool! #3847 is spot on, so closing as duplicate.

**Comment by sunshineo** [comment]
Can we re-open this? It probably will be a long time before export is implemented. It would be nice if fix a small thing can support PhantomJS or other headless browser
