### ISSUE TITLE
[dc.js migration] brushing does not always preserve viz type

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39414]
https://github.com/metabase/metabase/assets/37751258/054be427-93cb-4790-bffe-d8d4eeacb51b

**Comment by alxnddr** [comment]
@EmmadUsmani I could not reproduce it on the latest `echarts` branch. Can you please check it on the questions you could repro originally?

**Comment by EmmadUsmani** [comment]
@alxnddr I still see it happening on the same questions

https://github.com/metabase/metabase/assets/37751258/03a4b6e9-6f03-4408-88cd-b07ea5bcdb89

**Comment by JesseSDevaney** [comment]
I connected to the same AppDB and checked the same questions - it would not longer reproduce.
