### ISSUE TITLE
[dc.js migration] waterfall chart does not render series bars when there are many of them

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39411]
| dc.js | echarts |
|--------|--------|
| <img width="1897" alt="Screenshot 2024-02-29 at 11 45 37 AM" src="https://github.com/metabase/metabase/assets/37751258/9b73c9e6-a4b4-4e72-bd12-0cd26fafca85"> | <img width="1890" alt="Screenshot 2024-02-29 at 11 45 22 AM" src="https://github.com/metabase/metabase/assets/37751258/21eb5574-5bc0-444a-b7dc-56d124d4b2d5"> |

**Comment by alxnddr** [comment]
I assume this may be the limitation of candlestick series, maybe we will need to switch to custom series
