### ISSUE TITLE
Getting Started Guide memo fields shouldn't strip out returns/new lines

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3943]
Currently, when inputting a bunch of text into any of the memo/paragraph inputs in Edit mode of the Getting Started Guide, when you save your text, the Guide ignores any new lines or returns in the text. This makes long passages of text hard to read, and makes writing bulleted lists impossible.

What's interesting is that if you go back to edit mode, the new lines are still present in the saved text, so the ignoring is just happening at the presentation layer apparently.

**Comment by camsaul** [comment]
maybe we should do markdown with `:emoji:` support
