### ISSUE TITLE
Not possible to add nested custom expression

### ISSUE THREAD

**Issue by mngr** [metabase/metabase#39439]
### Describe the bug

https://stats.metabase.com/question/16385-invoices-mbql-bug-2/notebook
I've added custom column QS2 defined by expression expression `concat(year([Date Received]), " Q", quarter([Date Received]))`.
It causes error `Invalid query: {:query {:expressions {"QS2" [nil ["valid instance of one of these MBQL clauses: :expression, :field"]]}}}`
Having separate custom columns year([Date Received] and quarter([Date Received]) I can create a custom column with equivalent definition `concat("Q", [Quarter], " ", [Year])` and it works fine.
<img width="1123" alt="Captura de ecrã 2024-03-01, às 06 33 41" src="https://github.com/metabase/metabase/assets/777800/9f8ac37e-fc90-4c81-af04-3aa39ae2bdd2">
<img width="752" alt="Captura de ecrã 2024-03-01, às 06 33 28" src="https://github.com/metabase/metabase/assets/777800/6ba29989-29cc-4823-90f7-5e3d18547c5c">

### To Reproduce

1. Start new GUI question in stats.metabase.com
2. Choose Invoices dataset from Sample Database
3. Add custom column `concat(year([Date Received]), " Q", quarter([Date Received]))`
4. Click Visualize
5. Error will be shown

### Expected behavior

The expression should be parsed normally

### Logs

Invalid query: {:query {:expressions {"QS2" [nil ["valid instance of one of these MBQL clauses: :expression, :field"]]}}}

### Information about your Metabase installation

```JSON
stats.metabase.com
```

### Severity

Blocks some (rare) use cases

**Comment by ranquild** [comment]
@mngr AFAIK the problem is that you try to concat a number with a string, currently `concat` doesn't allow that

**Comment by mngr** [comment]
No, it actually works if I concat string with number columns without nesting

A sexta, 1/03/2024, 08:10, Alexander Polyankin ***@***.***>
escreveu:

**Comment by metamben** [comment]
Currently, QP uses the schema

```clojure
(defclause ^{:requires-features #{:expressions}} concat
  a StringExpressionArg, b StringExpressionArg, more (rest StringExpressionArg))
```

while metabase-lib (MLv2) uses

```clojure
(mbql-clause/define-catn-mbql-clause :concat :- :type/Text
  [:args [:repeat {:min 2} [:schema [:ref ::expression/expression]]]])
```

QP will be aligned with metabase-lib soon, and I think the metabase-lib definition will win, since databases can usually concat numbers and strings.
