### ISSUE TITLE
Not possible to save static text as a custom expression

### ISSUE THREAD

**Issue by mngr** [metabase/metabase#39438]
### Describe the bug

I've spotted a weird behaviour on [stats.metabase.com](http://stats.metabase.com/), if I put any string like 'test' or "asd" as a custom column expression and click outside the field, the page breaks.
I'm not sure if this is supported, I wanted to create a column with a fixed text value.
But even if this is not supported, a custom expression syntax error should be shown, I suppose.
Bug of MBQLv2?
![Captura de ecrã 2024-02-29, às 23 29 36](https://github.com/metabase/metabase/assets/777800/d9411902-5716-476a-990c-5e416c28b817)
![Captura de ecrã 2024-02-29, às 23 29 46](https://github.com/metabase/metabase/assets/777800/f7580c6b-d085-48a3-90bf-8227672c8212)

### To Reproduce

1. Open query builder for any dataset
2. Click on custom column button
3. Enter "test" as expression
4. Click outside the expression field
5. The page breaks

### Expected behavior

I believe the static text should be possible to save as a custom column value

### Logs

react-dom.production.min.js:209 Error: Unknown MBQL clause ["test"]
    at e (format.ts:74:9)
    at tf.UNSAFE_componentWillReceiveProps (ExpressionEditorTextfield.tsx:167:22)
    at oR (react-dom.production.min.js:135:172)
    at iF (react-dom.production.min.js:179:157)
    at l (react-dom.production.min.js:263:490)
    at aH (react-dom.production.min.js:246:265)
    at react-dom.production.min.js:246:194
    at aW (react-dom.production.min.js:246:199)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)

### Information about your Metabase installation

```JSON
stats.metabase.com
```

### Severity

Blocks some (rare) use cases

**Comment by uladzimirdev** [comment]
I think the issue is related to https://github.com/metabase/metabase/issues/38089

<img width="600" alt="image" src="https://github.com/metabase/metabase/assets/125459446/b0c63a23-8d8d-44f9-a081-214554d02649">

but we'll address it in scope of https://github.com/metabase/metabase/pull/39263 by adding additional check on expression validity

**Comment by mngr** [comment]
@uladzimirdev are you sure it's invalid? why can't we have a static text there specifically?
