### ISSUE TITLE
The order of the months in charts embedded in email is incorrect

### ISSUE THREAD

**Issue by ctouzeau** [metabase/metabase#39451]
### Describe the bug

We have a dashboard that is sent to people every morning. The dashboard contains several charts. One of the bar charts has months on the x axis. The chart renders correctly in metabase but in the email, the months go Oct 2023, jan 2024, nov 2023 - they are out of order.

### Expected behavior

months should display in chronological order.

### Information about your Metabase installation

```JSON
Chrome
happens on all OS
Google workspace (email)
0.48.5
```

### Severity

annoying

### Additional context

thank you

**Comment by vaughnd** [comment]
I've been having this issue for months. On v0.49.3 now.

Sorts the specified way on the dashboard, but reverses in the email.

**Email:**
![image](https://github.com/metabase/metabase/assets/715490/c161a184-a229-46a3-8284-3dc79f82b45d)

**Dashboard:**
![image](https://github.com/metabase/metabase/assets/715490/d0c6a7d1-2f2e-40d2-b127-d43dc8296918)

**Comment by perivamsi** [comment]
@ctouzeau once v50 RC1 comes out, could you please test this with that version and let us know if you still face the issue?

**Comment by ctouzeau** [comment]
Absolutely and thank you for your help.

**Comment by perivamsi** [comment]
@ctouzeau 50 RC1 is out, feel free to test it. Please remember that the release candidate is not a production version, so please upgrade in a test environment, if possible.

**Comment by ctouzeau** [comment]
I'm afraid we don't have a test environment and will need to wait until a
stable production version is available.
