### ISSUE TITLE
Query builder silently fails on duplicate custom column names

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#39508]
### Describe the bug

While reporting [this issue](https://github.com/metabase/metabase/issues/39150), I noticed that we silently fail when adding a custom expression that has the same name as an existing column. This is bad practice and we should alert the user in this case. Ideally, we should allow this behavior even.

### To Reproduce

1. New question
2. Name a custom expression the same as a column, it does not get added

### Expected behavior

Show the user an error that the name already exists

### Information about your Metabase installation

```JSON
stats
```

### Severity

P2

**Comment by perivamsi** [comment]
This seems to be fixed in master

@kamilmielnik can you confirm?

**Comment by kamilmielnik** [comment]
Can reproduce in 0.49.0-RC1.
Cannot reproduce in 0.49.0-RC2.
Cannot reproduce in `master` at d9507f2af8741a8389c78324b5871a8a6266c2a2.
