### ISSUE TITLE
Pivot table disappears

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#39504]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/573555e2-3a45-4bd1-82a4-dc1e8706a549

### To Reproduce

1. Create a new question with 2 aggregations and 1 breakout, [like this](https://github.com/metabase/metabase/assets/6830683/44faf1d0-3d5d-4dfc-929a-525901b74344)
2. Visualize it
3. Change visualization type to Pivot table
4. Open notebook editor
5. Close notebook editor

### Expected behavior

Pivot table is shown

### Information about your Metabase installation

`master`, 950a275387,

It works in 0.48.0, 0.49.0-RC1

### Severity

P2

**Comment by nemanjaglumac** [comment]
Can't reproduce in `master`, but it's still present in `v50`.
I'll add an E2E repro for this soon.

**Comment by nemanjaglumac** [comment]
Interesting.
I am not able to reproduce it using the latest `0.50.10` JAR, but I was able to repro it on `0.50.7`

https://www.loom.com/share/5851ca426f2340ac9d72d3f86fb7795a?sid=4b789f0f-5e6f-4a83-97d5-616ea87dbd05
