### ISSUE TITLE
Custom expressions `cols` don't have type info

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3952]
If I create a custom numeric field, I can't seem to select it for the y-axis or metric in any of our visualization types using the chart settings. Seems like MB doesn't know it's a metric? No JS errors that I can see. This is on both master and the new math branch on Chrome.

Custom field:
![screen shot 2016-12-14 at 10 58 33 am](https://cloud.githubusercontent.com/assets/2223916/21196413/65059208-c1ec-11e6-9ae5-cc2924c31358.png)

Shows up for this axis:
![screen shot 2016-12-14 at 10 58 06 am](https://cloud.githubusercontent.com/assets/2223916/21196429/6ddd3f52-c1ec-11e6-9680-24932ce8bcce.png)

But not this one:
![screen shot 2016-12-14 at 10 58 13 am](https://cloud.githubusercontent.com/assets/2223916/21196440/78da9602-c1ec-11e6-99d3-0c9f1e9ca85e.png)

Shows up here in pie chart:
![screen shot 2016-12-14 at 10 57 44 am](https://cloud.githubusercontent.com/assets/2223916/21196449/7f69f314-c1ec-11e6-9aba-412cdb6ab871.png)

But not here:
![screen shot 2016-12-14 at 10 57 49 am](https://cloud.githubusercontent.com/assets/2223916/21196464/897d31fe-c1ec-11e6-9eed-f525ea4bf386.png)

Scatter plot with two different custom numeric fields (the run differential ones):
![screen shot 2016-12-14 at 10 50 14 am](https://cloud.githubusercontent.com/assets/2223916/21196494/9f811d76-c1ec-11e6-96bf-a534f1848899.png)

Can't use them for the y-axis:
![screen shot 2016-12-14 at 10 53 11 am](https://cloud.githubusercontent.com/assets/2223916/21196510/b25a03ea-c1ec-11e6-9d81-f3fc718ab189.png)

**Comment by tlrobinson** [comment]
Looks like this is due to the corresponding `cols` not having a `base_type`/`special_type`.

Vaguely related to #4256.

**Comment by camsaul** [comment]
@mazameli is this still an issue on master? I think I fixed something similar to this recently

**Comment by mazameli** [comment]
@camsaul another user just reported this problem: #4745

**Comment by mazameli** [comment]
What I'm specifically seeing is that I _can_ plot a custom field if it's aggregated. I can't plot it if it's unaggregated. Is that what you're seeing, @doodlebro?

Related to #4746?

**Comment by doodlebro** [comment]
@mazameli: Yeah, looks like if I sum/aggregate the custom field, it's plot-able on the Y-axis.
Not really a temporary solution though, since the custom field is then renamed to 'sum' and I want to retain the custom field name.

**Comment by mazameli** [comment]
I would strongly advocate for us prioritizing this bug for our next release. It makes it so that custom expressions are unusable in visualizations, which drastically reduces the utility of custom expressions.

**Comment by camsaul** [comment]
I actually fixed this last week as part of #5238. Forgot to close this issue

**Comment by mazameli** [comment]
Hmm, this does not appear to be resolved on master. I created a custom expression, `Sum(FieldA + FieldB)`, and broke it out by a dimension, then tried to display it as a bar chart, but Metabase doesn't recognize my aggregation as something that can be plotted on the y-axis.

![screen shot 2017-06-06 at 11 28 52 am](https://user-images.githubusercontent.com/2223916/26845464-5c0b4f10-4aab-11e7-8800-03cca0b8d486.png)

![screen shot 2017-06-06 at 11 28 59 am](https://user-images.githubusercontent.com/2223916/26845471-5e58fa2e-4aab-11e7-8d2e-682bcc389344.png)

**Comment by camsaul** [comment]
Oh, maybe it's not fixed then. Oops

**Comment by mazameli** [comment]
I'm revoking my 🎉  emoji then. ;)

**Comment by mazameli** [comment]
@salsakran suggested this be changed to a P1

**Comment by Varunram** [comment]
@mazameli and @camsaul Another small update related to this issue. So I created a table with two numeric fields (lets say month and pizzas ordered). As with the issue reported, I can't seem to plot a line graph (or any graph for that matter)

**Comment by KimchaC** [comment]
I think I have a problem that may be related to this bug, which I posted on the forum. I am posting it here once more as an additional test case; In case you need it.

I have created a question that is grouped and has several sum()ed fields. I would like to add a few additional fields that calculate percentages based on those.

I added custom fields, but they don't show up. It seems like they are added to the original table, but I would like to add them to the grouped table.

Basically, I want to know the percentage of people who signed up. For the /, it should display 3% (100/2205*67 = 3).

Is there a way to achieve this or do I have to do a custom sql query?

Screenshot of table: https://dl.dropbox.com/s/89sxuzkyk41q1cq/Screenshot_2017-06-14_12-48-28.png?dl=01

Screenshot of custom fields: https://dl.dropbox.com/s/evi1n6tgsvjtgvd/Screenshot_2017-06-14_12-51-13.png?dl=01

Original forum thread: http://discourse.metabase.com/t/custom-fields-in-grouped-tables/1631

**Comment by mazameli** [comment]
Just verified this was fixed by #5862

**Comment by mazameli** [comment]
Hey everyone. Just a heads up that [we've shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
