### ISSUE TITLE
Incorrect display name of a drill filter based on a temporal extraction

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#39520]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/2ca1f1f2-48a6-4082-b781-3c5c814fdba5

### To Reproduce

1. Create a question: Orders, summarize by Count, group by Created At: **Day of Week**
2. Visualize it
3. Click the bar for Friday
4. Click "See these orders"
5. Examine the name of filter in filter pills

Filter is called "Created At: Day of week is equal to 6"

### Expected behavior

Filter is called "Created At is Friday"

### Information about your Metabase installation

master, a926009707

### Severity

P2

### Additional context

Found here: https://github.com/metabase/metabase/pull/39510#pullrequestreview-1914357985

This filter name comes from MLv2: https://github.com/metabase/metabase/blob/2aa3cec610588238132afbc789da0845c7c2ec5d/frontend/src/metabase/querying/components/FilterPanel/FilterPanelPopover/FilterPanelPopover.tsx#L51

----

Please update these assertions when fixing this issue:
- https://github.com/metabase/metabase/pull/39510/files#diff-0d56b267fa32819f4562ff2af8f8476606cb0a8434043561c7dc2979e0dc7b31R46
- https://github.com/metabase/metabase/pull/39510/files#diff-0d56b267fa32819f4562ff2af8f8476606cb0a8434043561c7dc2979e0dc7b31R51

----

This is how it used to work in v47:
https://github.com/metabase/metabase/assets/6830683/1fdcb100-1b43-4ce9-81b1-5642b67dea80

**Comment by ranquild** [comment]
This is not a bug. We transform names of weeks only in viz.
