### ISSUE TITLE
incomplete data on png image download 

### ISSUE THREAD

**Issue by MeharG811** [metabase/metabase#39546]
### Describe the bug

i have an iframe made using and signed url and when i download the pie chart graph png it dose not shows the categorys.
 
![Visit Graph-3_5_2024, 12_00_00 AM](https://github.com/metabase/metabase/assets/125581538/e1f30f95-1376-4277-8ac1-86da7d7ad58f)

### To Reproduce

i have an iframe made using and signed url and when i download the pie chart graph png .the png dose not shows the categorys.

### Information about your Metabase installation

```JSON
CHROME Version 121.0.6167.185 (Official Build) (64-bit)
WINDOWS 10
DATABASE MYSQL
METABASE V 0.48.7
HOSTING ENVIROMENT UBUNTU
INTERNAL DATABASE MYSQL
```

### Severity

 blocking your usage of Metabase

### Additional context

I DIFFICULT TO GENRATE REPORTS WITHOUT IMAGE FOR USERS

**Comment by paoliniluis** [comment]
how are you able to download the png with signed embedding?

**Comment by MeharG811** [comment]
Used 3 dots button on card (top right side on card) ,=> clicked download =>
clicked png

**Comment by paoliniluis** [comment]
@MeharG811 can you please post a video?

**Comment by MeharG811** [comment]
sure here is the link
https://drive.google.com/file/d/1q--B3Pjdq4yRp48t2C_omOy2gOOiBJMT/view?usp=sharing
