### ISSUE TITLE
The Releases Github pages says 0.20.1 instead of 0.21.1 

### ISSUE THREAD

**Issue by obaqueiro** [metabase/metabase#3956]
<img width="973" alt="screen shot 2016-12-14 at 4 50 59 pm" src="https://cloud.githubusercontent.com/assets/917229/21204565/a754f9ba-c21d-11e6-98a7-37addd90917a.png">
https://github.com/metabase/metabase/releases

**Comment by wyvernnot** [comment]
The `release title` field can be easily edited on github

**Comment by salsakran** [comment]
good catch. fixed.
