### ISSUE TITLE
[dc.js migration] overly frequent line series dots

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39567]
- Discussion: https://metaboat.slack.com/archives/C05NQSWPRMK/p1714165072406309

---
We should also switch the default setting to not show dots, per product/design feedback ([thread](https://metaboat.slack.com/archives/C06G94JTWBS/p1706194727139419)). In fact, if we do that then maybe this issue isn't worth fixing given how infrequently it'd come up.

question/4868
https://metaboat.slack.com/archives/C06G94JTWBS/p1706193945370869

<img width="486" alt="Screenshot 2024-03-04 at 1 01 37 PM" src="https://github.com/metabase/metabase/assets/37751258/7a35dd13-0e7e-4fc1-a151-9847a9d03d29">

question/4223
https://metaboat.slack.com/archives/C06G94JTWBS/p1706193960436849

https://metaboat.slack.com/archives/C05NQSWPRMK/p1714473071596039

**Comment by JesseSDevaney** [comment]
:warning: Currently waiting on product + design feedback before proceeding with implementing a fix
- https://metaboat.slack.com/archives/C05NQSWPRMK/p1714165072406309
