### ISSUE TITLE
[dc.js migration] inconsistent data compared to old implementation

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39581]
question/4172
https://metaboat.slack.com/archives/C06G94JTWBS/p1706194844355449

<img width="1793" alt="Screenshot 2024-03-04 at 2 14 59 PM" src="https://github.com/metabase/metabase/assets/37751258/51b24a94-5de8-4fa3-a56d-7161a8147fc4">

See the 6th data label from the right on the bottom series, in the old implementation it's 40.01%, in echarts its 39.96%

question/14273
https://metaboat.slack.com/archives/C06G94JTWBS/p1706197246775189

**Comment by JesseSDevaney** [comment]
Could not reproduce
