### ISSUE TITLE
[dc.js migration] data labels don't show at all in some cases

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39580]
question/12014
https://metaboat.slack.com/archives/C06G94JTWBS/p1706194772054189

<img width="1799" alt="Screenshot 2024-03-04 at 2 05 34 PM" src="https://github.com/metabase/metabase/assets/37751258/4b73c612-42f4-411f-af4e-763e69599c9a">

question/2701
https://metaboat.slack.com/archives/C06G94JTWBS/p1706194921403509

<img width="1397" alt="Screenshot 2024-03-04 at 2 12 37 PM" src="https://github.com/metabase/metabase/assets/37751258/ee07e599-8853-4c20-a80e-64249c952fad">

Might be related to the trend line

question/4808
https://metaboat.slack.com/archives/C06G94JTWBS/p1706198611931249

question/7545
https://metaboat.slack.com/archives/C06G94JTWBS/p1706201395238719

**Comment by alxnddr** [comment]
The labels are not visible if the series symbol is hidden — we need to add opacity on it instead

**Comment by JesseSDevaney** [comment]
Could no longer reproduce

![image](https://github.com/metabase/metabase/assets/22608765/44234374-8b1a-4468-9687-1cd6ccac2b0b)
