### ISSUE TITLE
[dc.js migration] missing blue highlight in timeline event focus state

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39599]
<img width="1638" alt="Screenshot 2024-03-04 at 4 21 31 PM" src="https://github.com/metabase/metabase/assets/37751258/a7b71636-0aa4-4b1b-91c8-1ed4a0c79c8e">

**Comment by EmmadUsmani** [comment]
This is a very minor style regression, and it's not easy to fix since we can't apply css to the icon image.

**Comment by JesseSDevaney** [comment]
Could not reproduce:


https://github.com/metabase/metabase/assets/22608765/bd1a6e35-2d33-4605-95b1-1e1c7c2890d9

**Comment by EmmadUsmani** [comment]
<img width="1385" alt="Screenshot 2024-05-20 at 6 20 52 PM" src="https://github.com/metabase/metabase/assets/37751258/1767cbd9-1d12-4942-b03c-a847febf2b6c">

@JesseSDevaney Apologies for the lack for description on the original issue. The bug was that the hover state should also be blue, see in this screenshot from your recording it's still grey.
