### ISSUE TITLE
[dc.js migration] wrong tick labels on some histograms

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39591]
question/2767
https://metaboat.slack.com/archives/C06G94JTWBS/p1706195458170079

| dc.js | echarts |
|--------|--------|
| <img width="680" alt="Screenshot 2024-03-04 at 3 41 53 PM" src="https://github.com/metabase/metabase/assets/37751258/dc9aca7a-29a1-4a85-89fb-f2c7e81c875a"> | <img width="885" alt="Screenshot 2024-03-04 at 3 42 02 PM" src="https://github.com/metabase/metabase/assets/37751258/9ffc09f0-3c44-450b-9d65-6009f0ed87ed"> | 

In echarts, the first bar should have the label of `$0`, but instead it's on the second bar. The last label `$70.00` is missing completely.

Also, the labels are misplaced, but that's a separate issue: https://github.com/metabase/metabase/issues/39564

question/2773
https://metaboat.slack.com/archives/C06G94JTWBS/p1706196040243949

<img width="1511" alt="Screenshot 2024-03-04 at 4 03 38 PM" src="https://github.com/metabase/metabase/assets/37751258/1627a908-cfcc-4ed4-b80b-27627fc5a989">

In this case the decimal values aren't shown.

**Comment by JesseSDevaney** [comment]
Could not reproduce
