### ISSUE TITLE
[dc.js migration] normalized stacked tooltip missing `%` symbol

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39590]
question/13700
https://metaboat.slack.com/archives/C06G94JTWBS/p1706195416551909

| dc.js | echarts |
|--------|--------|
| <img width="167" alt="Screenshot 2024-03-04 at 3 36 17 PM" src="https://github.com/metabase/metabase/assets/37751258/c5dbf6d9-459e-455f-900e-5976c5c3989e"> | <img width="178" alt="Screenshot 2024-03-04 at 3 36 21 PM" src="https://github.com/metabase/metabase/assets/37751258/0abed8e6-3fc5-44b1-b08d-f37b7ccb3330"> |

**Comment by alxnddr** [comment]
Not a regression
