### ISSUE TITLE
[dc.js migration] timeseries controls always say `unbinned`

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39594]
question/13114
https://metaboat.slack.com/archives/C06G94JTWBS/p1706195758780859

<img width="596" alt="Screenshot 2024-03-04 at 3 56 34 PM" src="https://github.com/metabase/metabase/assets/37751258/3435742f-954e-42a5-a1ec-e8051477e688">

**Comment by alxnddr** [comment]
Most likely not related and will be fixed by rebasing on top of the master
