### ISSUE TITLE
[dc.js migration] different y-axis auto-split logic

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39595]
In some cases the echarts implementation splits where it shouldn't, in other cases it does not split when it should.

question/1899
https://metaboat.slack.com/archives/C06G94JTWBS/p1706196110016349

question/13527
https://metaboat.slack.com/archives/C06G94JTWBS/p1706199630460249

question/2529
https://metaboat.slack.com/archives/C06G94JTWBS/p1710340971272179

question/13527
https://metaboat.slack.com/archives/C06G94JTWBS/p1710343860190739

**Comment by alxnddr** [comment]
Not a bug, needs rebasing on top of the master
