### ISSUE TITLE
Metabase update: All data lost

### ISSUE THREAD

**Issue by machupichu** [metabase/metabase#3961]
I think we fucked up when we updated our Metabase instance. We killed the Elastic Beanstalk on which it was running in order to upgrade to the new metabase version.

Obivously all config and data disappeared. We have though an access to the backup tht we made 4 days ago. We have though a file system!

We tried to import this file system to the new Elastic Beanstalk leading to a 502.
We would like to know how to retrieve our past data and config and where in the file system config files are located.

You might have also a better solution to retrieve this lost data

Thanks so much for your help!
Best
Mathieu

**Comment by salsakran** [comment]
@machupichu did you run EB using RDS for the application database?

it's possible that there are s3 snapshots.

**Comment by salsakran** [comment]
Hey @machupichu , it's been 14 days, so I'm assuming you've figured something out. I'll re-open if you still need help, or you might try discourse.metabase.com
