### ISSUE TITLE
Can't enlarge preview section while creating a model

### ISSUE THREAD

**Issue by mngr** [metabase/metabase#39628]
### Describe the bug

This handle is not draggable
<img width="1019" alt="Captura de ecrã 2024-03-05, às 10 50 45" src="https://github.com/metabase/metabase/assets/777800/c57ecb94-2285-455c-88f4-817d70809b90">

### To Reproduce

1. Click on + New model
2. Click on Use the notebook editor
3. Pick whatever data or build any query or just do nothing
4. In the bottom there is a preview section which has a handle implying you can drag it to enlarge this section, but this doesn't actually work

### Expected behavior

You should be able to adjust the height of the section by dragging the handle

### Information about your Metabase installation

```JSON
last version
```

### Severity

Annoying

**Comment by nemanjaglumac** [comment]
The same underlying mechanism/cause as in #33982.
