### ISSUE TITLE
Show second x-axis label on hover within chart

### ISSUE THREAD

**Issue by parisholley** [metabase/metabase#3963]
Currently when you create a chart with two x-axis series and a single y-axis, it only shows the first option from each axis when you highlight the point on the chart. If you have more values than colors, it can be hard to tell what belongs to which label. Propose adding all axis (x + y) values to popup when hovering a point.

**Comment by flamber** [comment]
Hi @parisholley 
I'm not sure when this was added, but this is how it looks like in 0.31.2
![screenshot 2019-02-18 19 23 02](https://user-images.githubusercontent.com/1447303/52983959-ff2f5c80-33b2-11e9-9d9f-d465e041ce1e.png)

**Comment by parisholley** [comment]
appears to be the case, i'll close
