### ISSUE TITLE
Using className on a Tooltip component overrides some tooltip styles.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#3964]
If you specify a className on a `<Tooltip />` element it seems like that className ends up replacing `.PopoverBody.PopoverBody--tooltip` which is used for the visual style of the tooltip. 

We should either toss out and ignore the className prop on this component or figure out a way to ensure that the class name inherent to the component stays put.

Here are the offending lines:
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/TooltipPopover.jsx#L40
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/TooltipPopover.jsx#L42

**Comment by tlrobinson** [comment]
Any reason not to just change https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/TooltipPopover.jsx#L40 to `className={cx("PopoverBody--tooltip", this.props.className)}`?

**Comment by flamber** [comment]
This was addressed some years ago
https://github.com/metabase/metabase/blob/a0af4869245f72725238518718840443dc6b3c94/frontend/src/metabase/components/TooltipPopover.jsx#L18-L20
