### ISSUE TITLE
[dc.js migration] stacking order is reversed

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#39667]
<img width="794" alt="Screenshot 2024-03-05 at 3 24 50 PM" src="https://github.com/metabase/metabase/assets/37751258/30d44ece-4543-4e25-87b2-d513c809b45f">

It should follow the order in the side bar from top to bottom (e.g. doohickey on top)

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/40073 needs a follow up https://github.com/metabase/metabase/issues/40177
