### ISSUE TITLE
Sort segments in Area by size

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3970]
![image](https://cloud.githubusercontent.com/assets/1708680/21261386/1c9f8210-c39c-11e6-956e-3e41240ac3fe.png)

⬇️ Please click "like" instead of "+1" comment

**Comment by anki-code** [comment]
More examples. 
1. Sorted Bar:
![image](https://cloud.githubusercontent.com/assets/1708680/21888699/73d4dc7a-d8d6-11e6-99df-f8fcc3cab36c.png)

2. Sorted pie:
![image](https://cloud.githubusercontent.com/assets/1708680/21888637/2bc3138e-d8d6-11e6-896d-fd8ac0e2415b.png)

3. Sorted area:
![image](https://cloud.githubusercontent.com/assets/1708680/21888680/60158bee-d8d6-11e6-81c4-17faf2c1a2c2.png)

**Comment by flamber** [comment]
Closing in favor of #7625, which has a lot more upvotes.
