### ISSUE TITLE
In permissions grid, add action to select accessible items for limited access

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3973]
When I have a group that has Limited Access to a particular database or schema, I wish there were an action, "Select accessible items," in the menu when I click on that block that would let me drill down into that DB or schema so I could change which items that group has access to. I know I can click the `view tables/schemas` link to do this, but that feels indirect. Bonus points if, after drilling down, the scroll position of the groups table is kept the same, so that if I have lots of groups I don't have to scroll over to the right to get to the group I'm trying to edit.

![screen shot 2016-12-16 at 11 17 47 am](https://cloud.githubusercontent.com/assets/2223916/21275414/88c32fca-c381-11e6-9f66-0e59edfce03f.png)

**Comment by brunobergher** [comment]
Not applicable anymore.
