### ISSUE TITLE
Editing Column description of Model is confusing if it contains aggregations

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#39749]
### Describe the bug

Editing 1 columns would propagate the same description to all other columns making the whole process confusing. You would think the other columns contain the same description where infact it's just a frontend issue

### To Reproduce

1. Go to New -> Question -> Sample DB -> Orders -> Count group by Created At Month
2. Turn Question into a Model -> Attempt to edit the description of a column

https://github.com/metabase/metabase/assets/110378427/97c8d8e4-f59e-4c40-8d18-e6beb3656362

### Expected behavior

Only the description of the column you are editing should get updated

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.48.8 and 1.49.RC2
```

### Severity

Cosmetic but makes the whole process confusing if you don't know what is going on

**Comment by ranquild** [comment]
Can be reproduced in 0.48 but not in 0.49+
