### ISSUE TITLE
Ability to change granularity of time series dashboard-wide

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3974]
See this Discourse thread for context: http://discourse.metabase.com/t/control-aggregation-in-the-dashboard-level/971

The gist is that, if I have a time series card on a dashboard, I can currently filter the date range, but I can't change the granularity of the chart from say days to weeks or months without going in and editing the card itself.

**Comment by tlrobinson** [comment]
It might make sense to add a special time range / grouping widget to dashboards that we can automatically apply to any card that is broken out by time. If you change the range drastically we could automatically switch the granularity to something sensible.

SQL cards obviously complicate this. At one point we talked about a special template tag for the `GROUP BY` clause, analogous to the field filter one.

**Comment by petit-pois** [comment]
Is there any work planned on this ? It's a feature often requested by our users

**Comment by flamber** [comment]
Closing in favor of #6583, which has already been added to 0.37 roadmap (not a guarantee)
