### ISSUE TITLE
Unknown table in "connected to" after table deletion

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3975]
![image](https://cloud.githubusercontent.com/assets/1708680/21286598/e07a3a04-c469-11e6-804a-2282a2addb11.png)

**Comment by camsaul** [comment]
We probably just forgot to filter out inactive tables in the API endpoint powering this. Should be an easy fix.

**Comment by anki-code** [comment]
The "unknown" table still in my list. Hoping that will disappear with time )
