### ISSUE TITLE
Why does metabot need slack #metabase_files channel?

### ISSUE THREAD

**Issue by apinstein** [metabase/metabase#3976]
I am quite familiar with slack integrations. I don't understand why a #metabase_files channel is needed. Metabot seems to happily post images in the channel where asked, but is also "cc'ing" the image to #metabase_files. 

Maybe I can help remove this dependency? Could you elaborate on this requirement?

**Comment by tlrobinson** [comment]
I believe there was a reason for it when we implemented this, but I can't recall exactly why. It might have been to prevent the files from appearing in the file listing for the channel where they're posted or the user who created the Slack API token. We can definitely try removing that requirement.

**Comment by apinstein** [comment]
Have you tried using their "attachments" mechanism? I'd have to double check but I don't think those will be manifested as files.

**Comment by salsakran** [comment]
At the time, the only way to have an image render in a pulse was to link to a file already uploaded to slack (or on a public url). Given that we didn't want to expose pulse renderings publicly, we went the file upload path. Also, at the time (not sure about now) you couldn't attach an image file to a message and have it render. Aaaand if we uploaded the file to the channel in question first, it would render (without the link/text) on upload as well as in the pulse.

Uploading to a separate channel was deemed the best of a bunch of bad choices. 

I haven't looked at the slack api in a few months, so I'm not sure if there is a way to do this more cleanly now.

**Comment by apinstein** [comment]
Aaaah that makes sense. You need the URL of a publicly-accessible file to get it to show, so you “laundered” that thru a slack upload. It looks like “channel” is optional now maybe?

https://api.slack.com/methods/files.upload

Anyway, all makes sense now, and it’s easy enough to just “ignore” the #metabase_files channel.

Thanks for the clarifications and maybe `files.upload` makes it even smoother.

**Comment by salsakran** [comment]
thanks! I need to poke at the slack api to debug some metabot issues today, so I'll see if we can simplify this.

**Comment by salsakran** [comment]
Also it looks like you *still* can't include an image with a message. In the link you sent, 
```By default all newly-uploaded files are private and only visible to the owner. They become public once they are shared into a public channel (which can happen at upload time via the channels argument).```
is still there, which was the issue we ran into.  =/

**Comment by apinstein** [comment]
Bummer. Sorry if I caused any mis-direction. Really loving metabase and hoping to find ways to contribute.
