### ISSUE TITLE
Cannot add a SSO user without last name to admin group

### ISSUE THREAD

**Issue by filipesilva** [metabase/metabase#39779]
### Describe the bug

Cannot add a SSO user without last name to admin group

### To Reproduce

1. run `docker run --rm -p 3000:3000 -e MB_PREMIUM_EMBEDDING_TOKEN=TOKEN_WITH_SSO_GOES_HERE -e MB_JWT_ENABLED=true -e MB_JWT_SHARED_SECRET=39475fb1d2610f99d1c05720b6ac2dd1ed3551464e1d77e5526d9925ed8248c9 -e MB_JWT_IDENTITY_PROVIDER_URI=https://test.com metabase/metabase-enterprise
` with a token that supports sso with jwt
2. go to http://localhost:3000/setup and finish setup
3. in an incognito tab or another browser open http://localhost:3000/auth/sso?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZvb0BiYXIuYmF6IiwiZmlyc3RfbmFtZSI6ImZvbyJ9.3ibGD1qlMcTm3XzZ74Z9Tcm7wBSeqKLEfZPrET_XfYU&return_to=%2F to make a new SSO account
4. on the first (admin) tab go to admin -> people -> edit user foo -> groups -> add admin -> update
5. see `nullable value must be a non-blank string` UI error on last name
6. see `PUT /api/user/2 400 6.2 ms (0 DB calls) {:errors {:last_name "nullable value must be a non-blank string."}, :specific-errors {:last_name ["should be at least 1 characters, received: \"\"" "non-blank string, received: \"\""]}}` error on docker server logs
7. try to add `bar` as last name, see `Editing last name is not allowed for SSO users` UI error

### Expected behavior

I think I should be able to make that user an admin regardless of last name

### Information about your Metabase installation

```JSON
Metabase v1.48.7 (c192db1)
```

### Severity

This is blocking me from adding more admins

**Comment by iethree** [comment]
need to verify, but I think this may have been fixed by: https://github.com/metabase/metabase/pull/46511

**Comment by noahmoss** [comment]
Confirmed that this is fixed
