### ISSUE TITLE
Text SQL variable required value but it shouldn't be required

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3978]
![image](https://cloud.githubusercontent.com/assets/1708680/21290743/0d8282fa-c4d7-11e6-9564-273a7acddfd6.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by tlrobinson** [comment]
@anki-code If you make it required you can give it a default value. Why doesn't that work in your case?

**Comment by anki-code** [comment]
@tlrobinson, any chart has two states:
1. when filters empty
2. when filters not empty

When chart built on sql the common behavior is :
Origin query(for example): 
`SELECT * FROM Users WHERE 1=1 AND [[CreatedAt = ?|CreatedAt >= NOW()-30]]`

When filter empty parser should return: 
`SELECT * FROM Users WHERE 1=1 AND CreatedAt >= NOW()-30`

When filter is not empty parser should return: 
`SELECT * FROM Users WHERE 1=1 AND CreatedAt = ?`

In over words there is a block in sql which filter should ON or OFF. For example I want to show or hide columns by filter. I want to write:
```
SELECT 
  a.column1
  [[if_filter_not_empty|  ,b.column2  ]]
  [[if_filter_not_empty|  ,b.column3  ]]
FROM TableA a
[[if_filter_not_empty|  LEFT JOIN TableB b ON a.UserId = b.UserId  ]];
```
This behavior make filters very agile.

Now in Metabase I don't know how to resolve this use case because you return "1=1" as default value or other strange solutions (on this issue screenshot) like creation filter with default text value.

**Comment by anki-code** [comment]
I think it's a bit about #3925

**Comment by flamber** [comment]
In the first screenshot, it's possible to use `SELECT COALESCE([[{{var}},]] null)`
The other examples should use Complex Default Value:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#default-value-in-the-query
