### ISSUE TITLE
Add info tooltip to card on dashboard

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3980]
![image](https://cloud.githubusercontent.com/assets/1708680/21290845/0c32d536-c4db-11e6-844f-c1b6003c253d.png)

**Comment by tlrobinson** [comment]
What do you want the tooltip to show?

**Comment by anki-code** [comment]
@tlrobinson, card description which I write when create card.

**Comment by mazameli** [comment]
Resolved by #4224
