### ISSUE TITLE
CSS box sizing issue on filter

### ISSUE THREAD

**Issue by meldiner** [metabase/metabase#39802]
### Describe the bug

Filter button is overflowing and the box isn't resizing.
https://www.loom.com/share/adffd93b4bca4c4f84607c3f6e05454e?sid=8ec26207-5110-48b1-8954-1bc0e96ff80e 

### To Reproduce

1. open a table view
2. reduce your screen width
3. click on one of the column headers to open the filter dialog 
4. type some text in the text box
5. See error

### Expected behavior

The button should be fully visible and the text box shouldn't be cut off

### Information about your Metabase installation

v46.2

### Severity

annoying

**Comment by ignacio-mb** [comment]
@meldiner Couldn't reproduce in 48.8. Can you post a quick video? Also, what version are you in? thanks!

**Comment by meldiner** [comment]
@ignacio-mb I added a video to the bug summary. We are using Metabase version 46.2
