### ISSUE TITLE
pulse email shows wrong charts on iPhone

### ISSUE THREAD

**Issue by CzechJiri** [metabase/metabase#3982]
metabase version: v0.21.0

This is indeed very strange...

When I look at pulse email on my desktop, it looks fine. When I look at the email on my iPhone (tried default mail client, google client as well as spark), the charts are mismatched meaning the numbers are OK, but the chart is wrong chart (my pulse email has multiple charts). This happens only when 2 pulse emails sit in my inbox (both have multiple charts, both delivered at the same time). When I remove one email, the charts render correctly. It almost feel like some issue with mail caching?

![image](https://cloud.githubusercontent.com/assets/6222611/21295864/150e98ec-c513-11e6-99c6-32f7ce06c63d.png)

vs on desktop

![image](https://cloud.githubusercontent.com/assets/6222611/21295855/c9e68a78-c512-11e6-9441-ba64bbb97573.png)

**Comment by tlrobinson** [comment]
That's very odd. My first thought is it sounds like a bug in the email client, but it would be strange for 3 different clients to have the same issue, unless it's a bug in iOS's web browser engine. Is this reproducible? Do you know under what conditions it occurs?

**Comment by CzechJiri** [comment]
I was able to recreate it with dummy data

**create tables**
I am using `PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit`

```
create table test ( mydate date, mygroup text, mymetric integer);

insert into test values ( '01-DEC-2016', 'first', 1);
insert into test values ( '02-DEC-2016', 'first', 2);
insert into test values ( '03-DEC-2016', 'first', 3);
insert into test values ( '04-DEC-2016', 'first', 4);

insert into test values ( '01-DEC-2016', 'second', 10);
insert into test values ( '02-DEC-2016', 'second', 2000);
insert into test values ( '03-DEC-2016', 'second', 3);
insert into test values ( '04-DEC-2016', 'second', 4000);
commit;
```

**create two charts**
both are the same, the only different is the filter on `mygroup`

![image](https://cloud.githubusercontent.com/assets/6222611/21333098/0b0d132e-c602-11e6-9d60-a4b613909ab8.png)

![image](https://cloud.githubusercontent.com/assets/6222611/21333104/156e8b22-c602-11e6-8650-276a204da0a4.png)


**create 2 pulses**
each has one of these charts

**send both pulses as email and look at the email on iPhone**

**Comment by CzechJiri** [comment]
Were you able to reproduce the issue?

Looking at the raw email, the `Content-ID:` is referencing static `IMAGE0`, here is a bit more info why that is not recommended http://stackoverflow.com/questions/4018709/how-to-create-an-email-with-embedded-images-that-is-compatible-with-the-most-mai/4697643#4697643


here is a sample of image header from one on the pulses...
```
------=_Part_1_577715007.1482190772043
Content-Type: image/png
Content-Transfer-Encoding: base64
Content-Disposition: inline; 
	filename=metabase_pulse_image_7614029412679226950.png
Content-ID: <IMAGE0>
```

**Comment by tlrobinson** [comment]
Yeah, I'm able to reproduce it. This seems like a bug in iOS, but I think we can work around it by using unique `Content-ID`s. Working on it now.

**Comment by tlrobinson** [comment]
@CzechJiri If you have a chance can you build master and see if PR #3996 resolves this for you?

**Comment by CzechJiri** [comment]
tested on `v0.22.0-snapshot c46eb03 fix-email-content-ids 2016-12-2`

**works like a charm**


```
------=_Part_1_730599952.1482513243878
Content-Type: image/png
Content-Transfer-Encoding: base64
Content-Disposition: inline; 
	filename=metabase_pulse_image_7790278690302771982.png
Content-ID: <1729634660@metabase>
```
