### ISSUE TITLE
executing ./bin/build gives OutOfMemoryError

### ISSUE THREAD

**Issue by laportem** [metabase/metabase#3986]
I’ve cloned the master repo for metabase 0.21.1 and while attempting to run ./bin/build
I keep getting OutOfMemoryError
Below is an excerpt of the error log. Any idea?

12-19 19:56:36 DEBUG metabase.driver :: Registered driver :crate 
Compiling metabase.driver.generic-sql.query-processor
Compiling metabase.driver.druid.js
Compiling metabase.driver.druid.query-processor
Compiling metabase.driver.mongo
java.lang.OutOfMemoryError: PermGen space, compiling:(monger/cursor.clj:82:1)
Exception in thread "main" java.lang.OutOfMemoryError: PermGen space, compiling:(monger/cursor.clj:82:1)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.analyze(Compiler.java:6625)
        at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1009)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)

I am going this in a vagrant box with:
ubuntu-trusty-64
java 1.8
node 7.2.1
yarn 0.17.10
Leiningen 2.7.1

**Comment by anki-code** [comment]
Try to check your version of packages here - https://github.com/metabase/metabase/blob/master/package.json

**Comment by tlrobinson** [comment]
@laportem Could you share your Vagrantfile?

**Comment by laportem** [comment]
Thanks, attached is the vagrantfile?
BTW, i am using Vagrant 1.9.1
and the host machine is windows 10
[Vagrantfile.zip](https://github.com/metabase/metabase/files/664526/Vagrantfile.zip)

**Comment by salsakran** [comment]
Add more memory to the vagrant box? they tend to have silly low memory by default. If you're using VirtualBox (which I was), you have to do this via VB and not the vagrant file itself.

In general, we don't recommend using vagrant for MB. We moved away from it ourselves over a year ago, and it's been a relief on most fronts. 

I'll close this as this is not a specific actionable thing we're going to fix, but you and Tom can use this issue to talk things out.
