### ISSUE TITLE
BE flake: postgres tests fail with `mt/with-temp-copy-of-db`

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#39861]
Postgres tests are often flaking on `copy-db-fks!`. 

The tests that fail are not consistent between runs, but the common factor is that they use `mt/with-temp-copy-of-db`

example:
https://github.com/metabase/metabase/actions/runs/8192774915/job/22406695644#step:4:2096

My theory is the fields aren't found because they're inactive.

**Comment by crisptrutski** [comment]
Definitely noticed the uptick in these flakes, thanks for jumping on it.

**Comment by calherries** [comment]
Closed by https://github.com/metabase/metabase/pull/39926

**Comment by calherries** [comment]
closing this because it's a dupe of https://github.com/metabase/metabase/issues/38052
