### ISSUE TITLE
Support for math, string, and other functions in expressions

### ISSUE THREAD

**Issue by arfrank** [metabase/metabase#3990]
### Feature requests and proposals
Small request - in the new mathematical functions under work it'd be incredibly useful to be able to invert the numbers, or to calculate the absolute value of the numbers. We store a lot of negative numbers for financial transactions, and only convert on display to end users, so a lot of our graphs internally are inverted.

Thank you, Metabase is incredibly value for our BI uses internally

**Comment by tlrobinson** [comment]
Actually, you should be able to just multiply by `-1` to invert it. I just tried it and there was a bug in the grammar that prevented negative number literals, but I've fixed it, and it works as expected. One nice thing about custom expressions in aggregations is they also work with our "saved metrics" feature, so you can save the inverted metric for other users to re-use.

But I also agree we should add functions (note the current "functions" you see in aggregation expressions are aggregations, which operate on a set of rows, whereas we're talking about functions that operate on a single value)

I'm going to change the title of this issue to make it more general. Please chime in with any functions you'd like see along with your use-case.

Here's a few that come to mind:

* absolute value
* round, floor, ceiling
  * could be used for binning/histograms, e.x. #798
* string concatenation
  * could be used to build links, e.x. #2529
* other string manipulation functions?
* date functions?

There are obviously [a ton of functions](https://support.office.com/en-us/article/Excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188) [we could support](https://support.google.com/docs/table/25273?hl=en), but keep in mind we need to support them on a number of databases.

**Comment by mfpinhal** [comment]
> Actually, you should be able to just multiply by -1 to invert it. I just tried it and there was a bug in the grammar that prevented negative number literals, but I've fixed it, and it works as expected.

@tlrobinson, is there anyway you submit a PR for this fix only? 🙃

**Comment by GravityWinz** [comment]
Regarding additional functions to support. Since adding a bunch of functions and having to support them across every database would maintenance problem. Have you considered creating a generic pass through function which would just let you call any function that the DB support. In MicroStrategy they call this an 'ApplySimple', ex: ApplySimple("DENSE_RANK() OVER (ORDER BY [1] DESC)", amount)

**Comment by flamber** [comment]
Closing this, since 0.35.0 got a lot more expression functions for math and strings:
https://github.com/metabase/metabase/releases/tag/v0.35.0
There's another issue for more date functions - #11330 - upvote by clicking :+1: on the first post
