### ISSUE TITLE
delete collection cannot work in archived collection view

### ISSUE THREAD

**Issue by hunter-xue** [metabase/metabase#39916]
### Describe the bug

delete collection cannot work in archived collection view

### To Reproduce

in archived collection view and select one or more archived collection. 
click delete button at the button. 

### Expected behavior

collection can be deleted. 

### Logs

console log in dev tools of Chrome: 
Uncaught TypeError: n.actions.delete is not a function
    at search.js:117:43
    at index.js:16:18
    at ArchiveApp.tsx:148:36
    at Array.forEach (<anonymous>)
    at onClick (ArchiveApp.tsx:148:20)
    at Object.A (react-dom.production.min.js:14:84)
    at z (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at w (react-dom.production.min.js:14:393)
    at ti (react-dom.production.min.js:52:170)

### Information about your Metabase installation

```JSON
ubuntu 22.04 with docker. Run the latest version of docker images.
```

### Severity

normal

**Comment by paoliniluis** [comment]
duplicate of https://github.com/metabase/metabase/issues/18372
