### ISSUE TITLE
FedCM in google signin on metabase

### ISSUE THREAD

**Issue by raoanees** [metabase/metabase#39927]
### Describe the bug

Google has notified us of the necessity to integrate Metabase with Google FEDCM (Federated Credentials Management) by March 29. Failure to do so may result in disruption to our open-source Metabase deployment.

### To Reproduce

Attempt to authenticate with Google credentials on our Metabase instance.
Notice lack of integration with Google FEDCM.
Potential service interruption post-March 29.

[https://developers.google.com/identity/gsi/web/guides/overview](https://developers.google.com/identity/gsi/web/guides/overview)

[https://developers.google.com/identity/gsi/web/guides/fedcm-migration#fedcm_flag](https://developers.google.com/identity/gsi/web/guides/fedcm-migration#fedcm_flag)

### Information about your Metabase installation

```JSON
Metabase version 0.48.8
```

### Severity

Urgent

**Comment by iethree** [comment]
see: https://github.com/MomenSherif/react-oauth/issues/333
