### ISSUE TITLE
Metabase deployment, the MySQL data used requires SSL authentication (CA certificate)

### ISSUE THREAD

**Issue by Avey777** [metabase/metabase#39920]
Metabase deployment, the MySQL data used requires SSL authentication (CA certificate)

**Comment by paoliniluis** [comment]
Hi @Avey777, you're hitting https://github.com/metabase/metabase/issues/9629

**Comment by Avey777** [comment]
> Hi @Avey777, you're hitting

I mean the database used by the database itself, not the data source for the data search

**Comment by paoliniluis** [comment]
definitely the same issue
