### ISSUE TITLE
Option to set other localization settings in interactive embedding

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#39933]
**Is your feature request related to a problem? Please describe.**
Interactive embedders would want to change style settings, such as Date and time styles, Separator and Currency styles for their different tenants. 

**Describe the solution you'd like**
Probably related to https://github.com/metabase/metabase/issues/18222 and https://github.com/metabase/metabase/issues/25153

**Describe alternatives you've considered**
Doing sandboxing and converting the formats at a question/view level, but more work

**How important is this feature to you?**
Requested by customers and probably useful for many interactive embedders our there. Internal ticket number: 25502

**Additional context**
May be tackled by SDK?

**Comment by paoliniluis** [comment]
same as https://github.com/metabase/metabase/issues/38343?

**Comment by albertoperdomo** [comment]
I would say duplicate of https://github.com/metabase/metabase/issues/25577

**Comment by ignacio-mb** [comment]
Yes indeed, duplicate of https://github.com/metabase/metabase/issues/25577. I opened this one for the specific request to change formatting styles for each tenant.
