### ISSUE TITLE
Date and number fields in Models based of a SQL question without variables can still be linked to filters in dashboards, but the filters will not work

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#39932]
### Describe the bug

If you have a model that comes from a SQL question without any variables, Date and Number filters in dashboards will still let you connect to date and number fields in the card but the filters won't work.

### To Reproduce

1. Create a SQL question `select * from orders limit 20`, convert it into a model
2. Add the question to a dashboard
3. Create new number and date filters
4. See that you can wire them to a SQL card without any variables
5. Select any date/number from the fields. See that the cards won't get filtered

<img width="509" alt="Screenshot 2024-03-11 at 8 36 36 AM" src="https://github.com/metabase/metabase/assets/132273646/04d1d7a7-4eb9-44df-b669-82cbb8949e4d">

<img width="489" alt="Screenshot 2024-03-11 at 8 36 25 AM" src="https://github.com/metabase/metabase/assets/132273646/9a141fbc-390b-46b6-b6be-5097ef2b5447">

### Expected behavior

I don't know if filters should be blocked entirely from a SQL question/model without any variables in them, or if the date and number filters should work even though there is no variables in the card

### Information about your Metabase installation

```JSON
- reproduced in 48.8 and in master
```

### Severity

P2

**Comment by nemanjaglumac** [comment]
A similar or a duplicate issue has been reported here https://github.com/metabase/metabase/issues/44288

Fixed and reproduced by #44372
