### ISSUE TITLE
Specific dates filter incorrect result

### ISSUE THREAD

**Issue by SeshTiliRest** [metabase/metabase#39968]
### Describe the bug

Hi! I create a new question and select a table from my MS SQL db.
Add a filter by date. Specific dates... Between March 1 - 2.
Preview and visualization in table shows wrong result.
Dates are displayed that do not match the filter March 1-2, 2024, shows 3 Jan - 2 March 2024 (1,154 rows).
The DateTakeoff field with SMALLDATETIME type contains local time, same as on a virtual machine with Docker, Metabase + Postgres containers.
In previous releases everything worked correctly, and then, after several updates, I noticed that my dashboard was displaying incorrect information with this specific date filter.
I'm sure that in version 0.48.1 everything worked correctly.

Preview of Specific dates show incorrect result:
![1](https://github.com/metabase/metabase/assets/28322040/967b20ee-fbea-4bac-8e1d-8b74522e4b66)

Visualization with Specific dates filter show 3 Jan - 2 March 2024 (1,154 rows)
instead of March 1-2, 2024 (31 rows):
![2](https://github.com/metabase/metabase/assets/28322040/f87f4d5d-4e2d-44ac-b2c8-bb9f8d1cce30)

Also here is the query generated in the question:
![3](https://github.com/metabase/metabase/assets/28322040/6df5bb84-aa22-417f-8743-adb15d726acf)

And here is the result of this query in HeidiSQL
which makes the selection correctly March 1-2, 2024 (31 rows)
I tried to create +New -> SQL Query in Metabase and insert the same query and result shows the wrong...
![4](https://github.com/metabase/metabase/assets/28322040/9a7e042a-fcd6-4604-9566-488ae6fa55aa)

Yesteday and others date filters works fine, problem with Specific dates...
![5](https://github.com/metabase/metabase/assets/28322040/24f0ce2c-7853-4b28-847a-2244bab74971)

I tried to select only March 15th and got the following error:
![6](https://github.com/metabase/metabase/assets/28322040/e93532c3-2d50-4a16-be92-3952064cae7f)

### To Reproduce

1. Login in
2. Click on + New
3. Select Question
4. Pick starting data (MS SQL db)
5. Select table
6. Click add filters
7. Select column
8. Click Specific dates...
9. Choose dates 1 March, 2024 - 2 March, 2024
10. Click Add filter
11. Click Preview
12. See incorrect result
13. Click Visualize
14. See incorrect result

### Expected behavior

After filtering by Specific dates, a result should be displayed that corresponds to the filter by a Specific date

### Logs

WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type 'tinyint identity' to a Field base_type, falling back to :type/*
WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type 'smallint identity' to a Field base_type, falling back to :type/*
WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type 'sysname' to a Field base_type, falling back to :type/*
WARN metabase.driver.sql.query-processor.deprecated Warning: The :sqlserver driver uses Honey SQL 1. This method was deprecated in 0.46.0 and will be removed in a future release

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.0-84-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.2 (Debian 16.2-1.pgdg120+2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-04",
      "tag": "v0.48.8",
      "hash": "a900c85"
    },
    "settings": {
      "report-timezone": "Asia/Sakhalin"
    }
  }
}
```

### Severity

Broken dashboard with incorrect results

### Additional context

Metabase Discuss link: https://discourse.metabase.com/t/specific-dates-filter-bug/85926

**Comment by ignacio-mb** [comment]
@SeshTiliRest I'm not able to reproduce. Can you post a screenshot of the query in the browser developer tools? inspect > Network tab > clear the previous >rerun the query with the filter > {;} dataset

**Comment by SeshTiliRest** [comment]
@ignacio-mb Thanks for your reply! Which tab exactly?
![123](https://github.com/metabase/metabase/assets/28322040/52746b50-2752-42bc-95ec-461f22eaac21)

**Comment by AndrewMBaines** [comment]
Try this in SSMS, then in Metabase. You'll soon see the problem:
```
select month(cast('2024-03-01 00:00:00' as datetime)) as full_date_time,  month(cast('2024-03-01' as date)) as just_date
```
Correct answer is 3,3 and that's what SSMS gives.
Metabase give 1,3!

**Comment by SeshTiliRest** [comment]
Hi! You are wright.
Metabase SQL query shows full_date_time 1 and just_date 3 :
![metabase](https://github.com/metabase/metabase/assets/28322040/6e3035d4-f3be-4d61-8d8b-828969a1f9d2)
HeidiSQL shows full_date_time 3 and just_date 3:
![heidisql](https://github.com/metabase/metabase/assets/28322040/0c6a3660-0f5a-477d-9da0-57a44892e149)

**Comment by ignacio-mb** [comment]
May be related to https://github.com/metabase/metabase/issues/39769

**Comment by notrom** [comment]
Just a bit more context from the discourse thread linked in the issue which has some really good info from @AndrewMBaines and @SeshTiliRest ...

I'm not seeing this issue either using filters in the GUI or when using that SQL, both SSMS and Metabase (v0.48.8) give me the correct answer 3,3.

SSMS:
![image](https://github.com/metabase/metabase/assets/4504437/502b3cd2-c6bf-4668-88d9-135b64a1c0e5)

Metabase:
![image](https://github.com/metabase/metabase/assets/4504437/6744d2df-f32f-4d3a-a977-1ef7b0ce1a0c)

So although it's clearly wrong, it doesn't appear to be universally wrong, there must be something else going on.

My SQL Server language (both default and user) is "English (United States)" (standard, we don't change that), my client's Windows locale is "United States" (again standard, we don't change that), my Windows date format is DD/MM/YYYY (as determined by the region settings which is "New Zealand").

**Comment by AndrewMBaines** [comment]
From my post on discourse:
It looks like it's to do with Metabase and SQL server having different locales or just non-US English for the OS.
In the UK, SQL Server is normally left at US English as that's the default. That means that formatting a date is mdy.
However, the OS and Metabase are both set to use British English giving dmy.
Try this:
```
select month(cast('2024-03-01 00:00:00' as datetime)) as full_date_time,  month(cast('2024-03-01' as date)) as just_date,month(cast('01-03-2024' as date)) as dateFormatCheck
```

I get 3,3,1 in SQL
but 1,3,3 in Metabase.

Metabase is using the OS locale to cast the dates. Makes sense except that yyyy-dd-mm hh:MM:ss isn't a valid format and that's what Metabase is trying to use.

If it makes any difference, my test system is all Windows.

**Comment by AndrewMBaines** [comment]
For what it's worth, I've been having another date related issue when the FIRSTDAYOFWEEK is anything other than 7:
https://discourse.metabase.com/t/different-dates-for-week-graph-vs-table/83187
Not sure if I need to start another issue for that or if it's just a bad release for non-US users of MS SQL.

**Comment by SeshTiliRest** [comment]
Yah, i get same result with this query.
3,3,1 in SQL and 1,3,3 in Metabase.

**Comment by SeshTiliRest** [comment]
Hi! As far as I can see, after updating to v0.49.2 I no longer see this problem. Thank you!

**Comment by ignacio-mb** [comment]
Thanks for following up!
