### ISSUE TITLE
[E2E] Fix the flake `question/caching.cy.spec.js`

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#39991]
Failed job: https://github.com/metabase/metabase/actions/runs/8247731157/job/22556914384?pr=38946#step:13:194

**Comment by qnkhuat** [comment]
seeing this agian https://github.com/metabase/metabase/actions/runs/8416379324/job/23043193372?pr=40547#step:13:198

**Comment by WiNloSt** [comment]
I have also been experiencing this quite often lately. My example run https://github.com/metabase/metabase/actions/runs/8535342374/job/23381923689?pr=40681#step:12:394
