### ISSUE TITLE
Model's column order not saved

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#39993]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/2f2e07c2-3b48-4039-b949-2c9df4e544d8

### To Reproduce

1. Create and save a new GUI question based on Accounts table from Sample DB
2. Turn the question into a model
3. Edit query definition
4. Add a custom column, e.g. using `1 + 1` expression
5. Run the query
6. Switch to Metadata tab
7. Drag & drop the new custom column and change its order
8. Save model
9. Visualization is opened

The new custom column is shown as last.

### Expected behavior

New custom column should be positioned according to order set in step 7

### Information about your Metabase installation

Reproducible in `master` at da96c24f80 and 0.49.0-RC2

Works in 0.48.7.

### Severity

P2

**Comment by uladzimirdev** [comment]
works fine for me on master a6684ac137

**Comment by ranquild** [comment]
I see that it's confusing but I see no reason why visualization settings from the model should propagate to the downstream questions. Maybe drag-n-drap of the columns in metadata editor should be disabled instead.

**Comment by ranquild** [comment]
So what happens is that in metadata editor we operate on field_refs within the query itself, but in chill mode we work with an ad-hoc questions. Field refs different and that causes issues with matching viz settings.
1 - Metadata editor
<img width="443" alt="Screenshot 2024-07-03 at 11 16 33" src="https://github.com/metabase/metabase/assets/8542534/8ee28504-617c-4710-bbf5-164a1813ad09">
2 - Chill mode
<img width="786" alt="Screenshot 2024-07-03 at 11 16 49" src="https://github.com/metabase/metabase/assets/8542534/f75fa1c5-fffe-44e2-8040-351048b6bb43">
