### ISSUE TITLE
Remove `set-best-transaction-level!`

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#40012]
See this TODO: 
https://github.com/metabase/metabase/blob/2421226810087efc22ab5e6ce5b270836ec42686/src/metabase/driver/sql_jdbc/execute.clj#L233-L234

**Comment by paoliniluis** [comment]
Related to https://github.com/metabase/metabase/issues/39130

**Comment by camsaul** [comment]
Merging into #39130
