### ISSUE TITLE
[QP] [MLv2] Native models in dashboards can be linked to dashboard filters, but they don't actually filter

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#40011]
### Describe the bug

If I put a native model in a dashboard and link it to a dashboard filter, it won't actually have the filter applied. This can lead to subtly incorrect results!

### To Reproduce

1. Create a native model, say `SELECT * FROM Orders;`
2. Match the ID column in the model's metadata to the underlying `Orders.ID` field.
3. Add the model to a dashboard.
4. Add an ID filter with a default value, eg. `5`.
5. The model can be linked to that filter (it even auto-links!)
6. Save the dashboard so it runs the queries.
7. The query is not filtered; all rows are returned.

### Expected behavior

The model's results are properly filtered - in this case, returning just one row.

### Information about your Metabase installation

```JSON
master
```

### Severity

P2 - significant and should-fix for 0.50

### Additional context

Not a regression; same logic in 48.

Much easier to fix after `metabase.query-processor.middleware.parameters` is ported to MLv2.

**Comment by ranquild** [comment]
We disabled mapping of parameters to native models in dashboards in https://github.com/metabase/metabase/pull/44372
