### ISSUE TITLE
Add a route for getting collection perm graph by id

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#40032]
/api/collection/graph/collection/:collection-id. This route must also return a warnings key, a sibling to `:graph`, which indicates what sub-collections should show `read` or `edit` warnings.
 
 A warning should occur when the group is lacking access to a collection, but can `read` or `edit` one of its subcollections.
 
 Open Question: Should `edit` override `read` if we find both warnings in a non-accessable-collection's subcollections?

**Comment by escherize** [comment]
We moved away from this approach, and fixed it another way.
