### ISSUE TITLE
Can't move card from collection to no collection

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4004]
(this issue is for the `collections` branch which is not yet merged to `master`)

It's not possible to move a card from a collection to no collection, presumably due to this line:

https://github.com/metabase/metabase/blob/collections/src/metabase/api/card.clj#L227

I can fix this but not sure if the `nil` check should go on that line, in `check-permissions-for-collection`, or elsewhere.

**Comment by salsakran** [comment]
I think a 
` (when (or (nil? collection_id) ((not= (:collection_id card) collection_id)))` would be reasonable

**Comment by tlrobinson** [comment]
I think it would be something like `(when (and (not (nil? collection_id)) (not= (:collection_id card) collection_id))` since we don't want to `check-permissions-for-collection` if `collection_id` is `nil`.
