### ISSUE TITLE
Proposal to make redshift testing more robust

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#40058]
Currently, each test run on Redshift is isolated to the schema level, meaning all tests will operate on a single schema.

During testing we create a lot of datasets (test-data, sample-dataset, Tupac-insights... etc.); this leads to a problem in that these databases, when synced, will include all the tables in the current schema. 

E.g.: if you need a test that operates on a custom dataset ( defined by `mt/defdataset`), the database for this custom dataset, when synced, will contain all the tables that were created from other `deftest` (tables from test data, sample-dataset ... etc.). This is not ideal; each database for a custom dataset should only contain tables of that custom dataset.

Some ideas to tackle this:
1. Increase the isolation level to DB: make each test run(aka CI job) operate a newly created database. Each custom dataset should be created with a new schema. 
  - One downside of this is that we can only create 100 DBs per cluster, so it might not be enough if we have too many parallel runs.
2. Modify the sync code during the test so that when it syncs, it only includes tables from the current dataset.

**Comment by qnkhuat** [comment]
IIRC, we have the same problem with any cloud DBs(bigquery, snowflake), so it's good to fix those too

**Comment by tsmacdonald** [comment]
NB: once this is fixed, respond to the comment in [the impersonation test](https://github.com/metabase/metabase/blob/f5cbb2078bb4ffd0c82a1083e216aff9667350e4/enterprise/backend/test/metabase_enterprise/advanced_permissions/driver/impersonation_test.clj#L133-L134) introduced in #40060.
