### ISSUE TITLE
Cannot edit a custom field named like the column it's referencing

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#40064]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/79b1d8a3-767e-4d8f-bf32-6ec7c5c8cf93

### To Reproduce

1. Start a new question based on Orders table from Sample DB
2. Add a custom column referencing the Tax field (example expression: `[Tax] * 100`), call it "Tax", click "Done"
3. Click to edit that custom column
4. Focus the name input

Error is displayed under custom expression input

### Expected behavior

Either:
- the error should not be displayed, or
- it should not be possible to add a custom column named like the column it's referencing

If the second bullet point is how it should work, then we should also make sure this works when a column name is changed via Admin > Table Metadata to a name that is used by an existing custom expression.

### Information about your Metabase installation

master, f0afae8ca7

### Severity

P2

**Comment by bshepherdson** [comment]
There's been some other bugs related to custom column name collisions lately. I thought it should be renaming them to `tax_2`?

Actually I think I'm only remembering that for the `Extract` drill thru; that logic should just go in `Lib.expression` for any added expression.
