### ISSUE TITLE
[Epic] Seed new instances w/ an example dashboard

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#40066]
**Links**
- product doc: [Seed new instances w/ an example dashboard](https://www.notion.so/metabase/Seed-new-instances-w-an-example-dashboard-18571f9ab18d41f882c39db92de3634d)
- eng doc: 
- feature branch: 

[Slack thread with some context](https://metaboat.slack.com/archives/C063Q3F1HPF/p1707322667352249)

**Implementation Plan**

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/40753
- [x] Add a setting with the sample dashboard ID for embedding use
```

The dashboard's ID will be 1.

**Comment by npretto** [comment]
Hey @crisptrutski, for the second part `Expose example dashboard to the frontend`  we were thinking about putting the id of the dashboard on a nullable admin-only setting, it should be the simplest solution for both the BE and the FE, let me know what you think.

**Comment by crisptrutski** [comment]
@npretto yes I saw that in the product doc, and it makes sense to me. it could also help with filtering out the corresponding audit events.

FYI @calherries has picked up the task from me
