### ISSUE TITLE
Docker Hub latest image isn't v21.0 

### ISSUE THREAD

**Issue by GuiSim** [metabase/metabase#4007]
Hi !

The Metabase administration page is telling me that I need to update my metabase installation. However, it appears that metabase/metabase:latest is v.0.20.3 and not v.0.21.0

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
metabase/metabase   v0.21.0             82b72ff9818c        2 weeks ago         218.5 MB
metabase/metabase   latest              0e10667fbffb        8 weeks ago         216.6 MB
metabase/metabase   v0.20.3             0e10667fbffb        8 weeks ago         216.6 MB
``` 

Is this expected?
The documentation still recommends that you use the default (latest) tag. In order to update, I would need to change from using the `latest` tag to use an explicit version number, which I'd like to avoid.

Thanks!

**Comment by salsakran** [comment]
ugh. good catch. there was a typo in the name. we had pushed `metabase/metbase:latest`

**Comment by salsakran** [comment]
fixed now
