### ISSUE TITLE
Invalid migration - Upgrade to v0.48 impossible when backed by MySQL database

### ISSUE THREAD

**Issue by cdaguerre** [metabase/metabase#40080]
### Describe the bug

The MySQL migration file https://github.com/metabase/metabase/blob/master/resources/migrations/instance_analytics_views/subscriptions/v1/mysql-subscriptions.sql is not valid MySQL and breaks upgrading to v0.48.0 when backed by a MySQL database.

### To Reproduce

Copy paste migration SQL from https://github.com/metabase/metabase/blob/master/resources/migrations/instance_analytics_views/subscriptions/v1/mysql-subscriptions.sql in https://www.eversql.com/sql-syntax-check-validator/
> You have an error in your SQL syntax; it seems the error is around: 'CREATE OR REPLACE view v_subscriptions as ( select public_channel_id, ' at line 1

### Expected behavior

Database migration should be valid MySQL and work 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.15.133+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "bigquery-cloud-sdk",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.44-google"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-01",
      "tag": "v0.47.9",
      "branch": "?",
      "hash": "d05b06e"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

### Severity

Medium

### Additional context

qsd

**Comment by paoliniluis** [comment]
you need to jump to v48.8, don't go through each minor version

**Comment by cdaguerre** [comment]
@paoliniluis sorry for the typo but that's of course what I'm doing. I'm trying to upgrade from 0.47.7 to 0.48.8. Regardless, migrations of minor versions are still being run and invalid SQL will break upgrade to any version after 0.48... Could you re-open?

**Comment by cdaguerre** [comment]
ok thanks @noahmoss
