### ISSUE TITLE
Chart render errors aren't cleared when switching visualizations

### ISSUE THREAD

**Issue by witwall** [metabase/metabase#4009]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome  55.0.2883.87
- Your operating system: Windows 7
- Your databases: Postgres
- Metabase version:  v0.21.1
- Metabase hosting environment: Docker
- Metabase internal database: H2 
- *Repeatable steps to reproduce the issue*
create a pivot table in this way, it works
![bug000](https://cloud.githubusercontent.com/assets/3222056/21538561/4b6de02c-cdd9-11e6-8561-38f25ce53038.png)

then I tried to display in line, I got,
This chart type doesn't support more than 20 series
![bug001](https://cloud.githubusercontent.com/assets/3222056/21538592/9b75689c-cdd9-11e6-9c20-3d7e8cdc30e3.png)

then I backed to table again, sill have the same issue, and I have to create the question from zero.

Thanks for being part of the Metabase project!
-------

**Comment by maliayas** [comment]
A page refresh in the last step fixes this issue. No need to rebuild.
