### ISSUE TITLE
Archiving questions, or collections with questions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4012]
This is in reference to the as-yet-to-be-merged `collections` branch. I noted some of this in the to-do list for #3920, but here it is again as its own issue:

Archiving an individual question, or a collection and all of its questions, doesn't remove the question(s) from dashboards or Pulses where it is referenced, though it should. This currently creates a weird path where you can click on an archived card on a dashboard to go to the archived card's detail view, then click on the collection label to arrive at a phantom, archived collection screen.

Also, I don't think this was specced, but going directly to the URL of an archived question should probably result in a page similar to the you-don't-have-permission screen, with the archive box icon in place of the permission key, and with the text, "This question has been archived." Maybe with a link below it to "View the archive".

Lastly, if archiving a question removes it from dashboards and pulses, I'm thinking there should be a blocking modal on archiving individual questions, or using the bulk archive action, which would effectively say the same thing as the collections archive modal. ("Archive this/these question(s)? This will remove it/them from any dashboards or Pulses currently using it/them.")

**Comment by salsakran** [comment]
From our conversation:

1. Provide an explicit warning that archiving a collection will remove all the questions from dashboards.
1a. Include a list of the dashboards that will be affected
2. Remove all cards in an archived collection from dashboards 

A side thought - would it make sense to move questions from an archived collections to "uncategorized"? I'd vote NO, but want to throw that out there.

**Comment by camsaul** [comment]
Are we trying to do 1A as part of 22? It would require a new endpoint to get working

**Comment by salsakran** [comment]
that's the question =)

**Comment by salsakran** [comment]
closed via #4075
