### ISSUE TITLE
Visualization differs after converting question to SQL

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#40126]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/0a9b596a-cfd3-4d4d-85f6-cd4c8ea09148

### To Reproduce

1. Start a question [like this](https://github.com/metabase/metabase/assets/6830683/3ff5a0fa-a37a-471e-b935-a586a3a18e02)
2. Visualize it - it works
3. Save it
4. Open notebook
5. Convert question to SQL
6. Run query

Visualization differs

### Expected behavior

Visualization looks the same as in step 2

### Information about your Metabase installation

master at 45a2e8689f

### Severity

P2

### Additional context

Similar to #40124

**Comment by ranquild** [comment]
column "keys" differ between MBQL and SQL questions, so that's expected. I don't see how we can convert visualization_settings between the questions

**Comment by kulyk** [comment]
As @ranquild pointed out, this is expected for native queries at this point. Fixing this would require SQL parsing, so closing the issue for now
