### ISSUE TITLE
Can't connect to Athena using IAM Role / Profile

### ISSUE THREAD

**Issue by iholoviy** [metabase/metabase#40120]
### Describe the bug

I am able to connect to Amazon Athena from DBeaver using this trick, but can't do the same in Metabase

1. Do your normal AWS login process to refresh your credentials (in our case, we use okta + gimme_aws_creds for this).
2. Go to driver properties on your DBeaver Athena connection and set:

- AwsCredentialsProviderClass to com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider
- AwsCredentialsProviderArguments equal to the name of the profile you want to use (see ~/.aws/config to see which profiles you have) – we use “default”.

3. Test Connection and it should work.

(from [Using Athena From DBeaver with your IAM Role / Profile | Coding Stream of Consciousness](https://coding-stream-of-consciousness.com/2021/11/16/using-athena-from-dbeaver-with-your-iam-role-profile/))

### To Reproduce

1. Run Metabase in Docker (in my case in MacOS)
2. Try to add a connection to Athena using the IAM role
<img width="921" alt="image" src="https://github.com/metabase/metabase/assets/1760612/b52442ea-f572-4f38-af92-05eb174c0bf2">

### Expected behavior

Connection is successul

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.6.12-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-04",
      "tag": "v0.48.8",
      "hash": "a900c85"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

High

**Comment by paoliniluis** [comment]
have you created your data lake with lake formation?

**Comment by iholoviy** [comment]
> have you created your data lake with lake formation?

yes, data lake with lake formation was created

**Comment by paoliniluis** [comment]
please read the last line of https://www.metabase.com/docs/latest/databases/connections/athena#permissions-and-iam-policies

**Comment by iholoviy** [comment]
@paoliniluis all these policies are configured. I am able to query data via DBeaver, so I don't think it's a permission issue. I guess that here should be an option to use com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider

![image](https://github.com/metabase/metabase/assets/1760612/f072d01c-4596-4cd1-8977-cc8b3d16d195)

**Comment by paoliniluis** [comment]
@iholoviy have you been able to connect after going to AWS Lake Formation > Permissions > Data Lake Permissions > Grant data lake permissions; the role Metabase uses needs SELECT and DESCRIBE table permissions?

**Comment by iholoviy** [comment]
@paoliniluis 
why can't I query data from Athena via DBeaver but can't access the same data via Metabase?  Both tools use JDBC connection, both tools should query data via SQL. What is the difference here?
