### ISSUE TITLE
Visualization disappears after converting question to SQL

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#40124]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/bae65d3d-7a00-43be-8c74-8bfe79da2ea9

### To Reproduce

1. Start a question [like this](https://github.com/metabase/metabase/assets/6830683/2ba420e5-4970-4014-afa0-f0953561a5cf)
2. Visualize it - it works
3. Open notebook
4. Convert question to SQL
5. Run query

Visualization disappeared.
Saving the question and refreshing the page does not help.

### Expected behavior

Visualization is shown

### Information about your Metabase installation

master at 45a2e8689f

### Severity

P2

### Additional context

Similar to #40126

**Comment by kamilmielnik** [comment]
Simpler question for repro: [image](https://github.com/metabase/metabase/assets/6830683/a5495a34-995f-4013-8265-086876b7cafc)

**Comment by kulyk** [comment]
Similarly to #40126, this is expected for native queries at this point. Closing as it'd require more advanced SQL parsing
