### ISSUE TITLE
Can't use nested fields in Druid calculated columns

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4015]
When I try to use a druid nested field in an intra-row or aggregation calculation , I get the below error

![screen shot 2016-12-29 at 3 50 49 pm](https://cloud.githubusercontent.com/assets/107439/21557254/a847f058-cdde-11e6-8bc4-1ebe1afc447e.png)

**Comment by tlrobinson** [comment]
@salsakran @camsaul Do Druid nested fields work the same as MongoDB nested fields (in Metabase)? i.e. can I use Mongo when implementing this or do I need to setup a Druid db?

**Comment by salsakran** [comment]
not sure.

**Comment by salsakran** [comment]
That's dimensions, can they be used in aggregations?

**Comment by salsakran** [comment]
closing as this was due to those fields being text in our test DB.
