### ISSUE TITLE
Model does not bring the options in filters although the api responds with a 200 and the values

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#40193]
### Describe the bug

If you try to filter on a column that has synced values, the values won't appear although the endpoint returns those values

### To Reproduce

1) go to our edumation demo and log in
2) go to the assignments model
3) try filtering on the status column

### Expected behavior

It should show the values

### Logs

No logs on BE or FE

### Information about your Metabase installation

```JSON
- v49
```

### Severity

P2ish

### Additional context

![image](https://github.com/metabase/metabase/assets/1711649/a51aba70-5510-443e-ad03-7ef0ebe021fe)
![image](https://github.com/metabase/metabase/assets/1711649/a31d8f0f-1d0e-4157-8fab-8a1f527e1747)

**Comment by ranquild** [comment]
Couldn't repro nowdays. I believe it was solved by this PR https://github.com/metabase/metabase/pull/44440
