### ISSUE TITLE
Model loses metadata in query builder

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#40191]
### Describe the bug

Seems that we're losing metadata in some models (reasons unknown)

### To Reproduce

1) go to https://embedding-demo.metabaseapp.com/
2) log in and go to the assignments model
3) edit the model query, see that the query builder is completely empty

### Expected behavior

You should see the question definition there

### Logs

nothing on the FE or BE which is interesting

### Information about your Metabase installation

```JSON
I don't know if this is v49 or what, don't think so...
Using brave latest on pop-os
```

### Severity

P2'ish

### Additional context

Other models work, don't why this one specifically does not

**Comment by ranquild** [comment]
Duplicate of https://github.com/metabase/metabase/issues/26755
