### ISSUE TITLE
Change "None" in collections

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4019]
As we've discussed, it kinda sounds weird, and it looks bad in a list of collections when moving. It's especially egregious as it doesn't have an icon

![screen shot 2016-12-29 at 4 30 30 pm](https://cloud.githubusercontent.com/assets/107439/21557638/33d97f56-cde4-11e6-87de-c3a635e6c758.png)

**Comment by flamber** [comment]
Hi @salsakran Wasn't this fixed by the big Collections overhaul in 0.30, so now the "None" is called "Our analytics" and has a little stack icon?
![image](https://user-images.githubusercontent.com/1447303/52668931-78720f80-2eda-11e9-9e46-750dfb3cf794.png)

**Comment by salsakran** [comment]
@flamber you are, as usual, correct.
