### ISSUE TITLE
I should be able to create a new collection when saving or moving questions, dashboards, or models

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4020]
It would be nice to be able to create a new collection when moving a bunch of questions.

**Comment by mazameli** [comment]
I'll add that it would similarly be handy to be able to create a new collection when saving a new question.

**Comment by mazameli** [comment]
This is super hella annoying to me, so I'm plopping the 0.34 milestone on it since it also relates to the theme of improving collections UX.
