### ISSUE TITLE
Format of datetime in normal YYYY-MM-DD

### ISSUE THREAD

**Issue by tavarez992** [metabase/metabase#40221]
### Describe the bug

We updated to v0.49.0 and starting getting formated numbers, dates and datetimes in API calls for data - not only in shown frontend tables.

Numbers were fixed by setting localize format, but in date and datetimes is missing standard format YYYY-MM-DD.
Timepart is in 12 hour mode and 24 hour mode, but it puts comma between date and time.

This is what we are getting from API: **2023-7-18, 14:15**
Where is standard format **yyyy-mm-dd hh-mm-ss**?

Should be readable format for tables used also in API calls for data?
In my state of opinion format should be applied only on frontend tables to display data.

![Snímka obrazovky 2024-03-18 094720](https://github.com/metabase/metabase/assets/20593907/b789506d-604d-4b49-af6f-731c3370fe01)
![Snímka obrazovky 2024-03-18 094738](https://github.com/metabase/metabase/assets/20593907/c3455e3b-8bcc-4747-b81f-d8a6e6fdfc82)

### Expected behavior

Datetime format: yyyy-mm-dd hh-mm-ss (without comma and with 2 digits for month and day part)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.4.0-152-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3 (Debian 15.3-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": "Europe/Bratislava"
    }
  }
}
```

### Severity

4

**Comment by tavarez992** [comment]
Set up localization options like this for example:
![image](https://github.com/metabase/metabase/assets/20593907/6cb9de2e-fed1-44a0-b09f-c96aaced7261)

In my opinion this should only affect table cells like here - it's nice formatted
![image](https://github.com/metabase/metabase/assets/20593907/7aa7aee9-d56f-4d32-84f0-493866c42d67)

Then call API
API path: /api/card/{questionId}/query/json
When you get reasource it will return thouse 2 columns in this format in Metabase v0.48.5 (we were forced to downgrade)
```
array(
   'date_updated' => '2023-07-18T14:15:37',
   'date_contract_first' => '2017-08-22',
)
```

In v0.49.0 API response contains formated cells like:
```
array(
   'date_updated' => '18.7.2023, 14:15',
   'date_contract_first' => '22.8.2017',
)
```

But our system works with normal format of dates (yyyy-mm-dd hh-mm-ss) so we found it out really quickly :)
It is same with number formats - if you have separator in thousands API call return reasource with spaces in value and it's string.

**Comment by paoliniluis** [comment]
Hi, this is an API change that I just documented here https://github.com/metabase/metabase/pull/40389

**Comment by tavarez992** [comment]
Could we at least add new formats? 
Or get rid off column in date time part?

**Comment by guybowden** [comment]
The change of formats without the option to either revert back to an unformatted version or set a more ISO friendly format like `YYYY-MM-DD` is causing havoc with my users who are using downloads in Google Sheets.

**Comment by hjc** [comment]
Being unable to set a format that's more predictable, like `YYYY-MM-DD` is also causing havoc for my customers who go through a manual export flow (to .json or .csv) before importing into other tools and databases.

Would love to see some commentary here.

**Comment by ember-zhang** [comment]
The downloaded csv got problems with this. Some apps ( such as Apple Numbers ) can't sort the date colume correctly.

**Comment by tadeumaia** [comment]
Anyone got a solution for this? This broke all my api <> google sheets integrations

**Comment by tavarez992** [comment]
Unfortunately we were forced to run over all report questions and format date columns with
`DATE_FORMAT(xyz, '%Y-%m-%d')`
