### ISSUE TITLE
Data picker shows "Saved Questions" on an empty *not yet activated* enterprise instance

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#40223]
### Describe the bug

The data picker shows "Saved Questions" on an empty enterprise instance that hasn't been activated.

### To Reproduce

1. Start a new Metabase instance from an enterprise JAR or Docker enterprise image and fill out the basic info
2. DO NOT create any questions or models
3. Go to the "New" button in the app bar, and select either a "Question" or a "Model"
4. You'll see "Saved Questions" in a data picker when there are none on the fresh instance

![image](https://github.com/metabase/metabase/assets/31325167/bba6b58d-a19b-40a8-b970-02edaa83a982)

### Expected behavior

"Saved Questions" should not be shown in the data picker. For example, this is what happens on an OSS instance: ![image](https://github.com/metabase/metabase/assets/31325167/c055d6b1-416b-4780-824f-6de2af817ad9)

### Information about your Metabase installation

```JSON
H2, Sample Database, local instance, `master`, c27b676
```

### Severity

P3

### Additional context

can be a duplicate of https://github.com/metabase/metabase/issues/32252

_No response_

**Comment by kamilmielnik** [comment]
I can reproduce it in both EE and OSS versions.

GET `/api/database?saved=true` returns "Saved questions" even when there are no saved questions.

**Comment by uladzimirdev** [comment]
I ran OSS jar 50.6 and got a saved question from the "examples" collection, so there is on saved question even on the fresh instance @kamilmielnik @nemanjaglumac

**Comment by uladzimirdev** [comment]
<img width="803" alt="image" src="https://github.com/metabase/metabase/assets/125459446/e017d820-fffa-411d-b069-ce2a812fdb22">
this is what I see when I run EE version locally for the first time

**Comment by kamilmielnik** [comment]
With the new default Examples collection I think this issue is not "valid" anymore. @nemanjaglumac can you confirm?

**Comment by nemanjaglumac** [comment]
Yep, if we ship "Examples" by default, this whole issue doesn't make sense.
