### ISSUE TITLE
Unable to filter for multiple values

### ISSUE THREAD

**Issue by abhishek-superk** [metabase/metabase#40224]
### Describe the bug

Previously we used to filter for multiple values in a column by copying multiple cell from a sheet and just pasting them in the column filter. All the values (separated by newline character) would be automatically selected.

A few versions ago, some datatype drop-downs became checkbox -- the option of copying and pasting was not there anymore. However, most of the tables were still working fine if the columns were not linked as a foreign key at least.

We recently updated to `v0.49` and since then no table can be filtered by a simple copy paste anymore.

<img width="1480" alt="image" src="https://github.com/metabase/metabase/assets/73629665/0f377ed0-72d4-40bc-a25c-2d07097d29c2">

### To Reproduce

1. Go to any table in your database
2. Click on any column and select filter by this column
3. Paste multiple values together
4. No result would come

### Expected behavior

Values separated by newlines should all be selected in the filter

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7-post-Ubuntu-0ubuntu220.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7-post-Ubuntu-0ubuntu220.04.1",
    "os.name": "Linux",
    "os.version": "5.15.0-1052-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.3.39-MariaDB-0ubuntu0.20.04.2"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

### Severity

P1, unable to use metabase

### Additional context

We use metabase to look at a lot of business data, and a lot of usecases involve filtering for a list of products (100-200) and then applying additional filters on a few other columns to identify any abnormal behaviour flags.

Multiple people looking at different sets of products use the same reports or tables and just change the filters. With this new update, we are unable to filter on so many products at once and we can't ask users to manually do 100+ copy-pastes.

**Comment by MathiasGr** [comment]
+1 from our team at Bigblue, we got many complaints about this already.

**Comment by abhishek-superk** [comment]
Thanks @MathiasGr, please react with 👍 so that this gets prioritized.

**Comment by paoliniluis** [comment]
We’re tracking this issue in the linked one, closing this as duplicate
