### ISSUE TITLE
Problem with MongoDB connection

### ISSUE THREAD

**Issue by poldal12** [metabase/metabase#40240]
### Describe the bug

All MongoDB databases that were working before has stopped working over the weekend.

I receive the following error:

The connection string contains an empty host '[]'. 

### Logs

{:database_id 3,
 :started_at #t "2024-03-18T14:09:27.598241Z[GMT]",
 :action_id nil,
 :json_query
 {:database 3,
  :query
  {:expressions
   {:Product
    ["case" [[["=" ["field" 468 nil] "adult"] "VMA"]] {:default ["case" [[["=" ["field" 468 nil] "vmc"] "VMC"]]]}]},
   :fields
   [["field" 472 nil]
    ["field" 480 {:base-type "type/Text"}]
    ["field" 468 nil]
    ["field" 478 nil]
    ["field" 473 {:temporal-unit "default"}]
    ["field" 2002 {:base-type "type/Text"}]
    ["expression" "Product" {:base-type "type/Text"}]],
   :filter ["=" ["field" 1740 nil] false],
   :source-table 65},
  :type "query",
  :parameters
  [{:id "74ba1e3c", :type "string/=", :value nil, :target ["dimension" ["field" 480 nil]]}
   {:id "d8c5d488", :type "string/=", :value nil, :target ["dimension" ["field" 2002 nil]]}
   {:id "6ffa3994", :type "string/=", :value nil, :target ["dimension" ["expression" "Product"]]}],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:projections ("_id" "name" "source" "client_id" "created_at" "trading_name" "Product"),
  :query
  [{"$match" {"test_business" false}}
   {"$project"
    {"_id" "$_id",
     "name" "$name",
     "source" "$source",
     "client_id" "$client_id",
     "created_at" "$created_at",
     "trading_name" "$trading_name",
     "Product"
     {:$switch
      {:branches [{:case {"$eq" ["$source" "adult"]}, :then "VMA"}],
       :default {:$switch {:branches [{:case {"$eq" ["$source" "vmc"]}, :then "VMC"}], :default nil}}}}}}
   {"$limit" 1048575}],
  :collection "business",
  :mbql? true},
 :status :failed,
 :class java.lang.IllegalArgumentException,
 :stacktrace
 ["com.mongodb.ConnectionString.parseHosts(ConnectionString.java:1150)"
  "com.mongodb.ConnectionString.<init>(ConnectionString.java:396)"
  "com.mongodb.ConnectionString.<init>(ConnectionString.java:321)"
  "--> driver.mongo.connection$db_details__GT_mongo_client_settings.invokeStatic(connection.clj:67)"
  "driver.mongo.connection$db_details__GT_mongo_client_settings.invoke(connection.clj:61)"
  "driver.mongo.connection$do_with_mongo_client$fn__121852.invoke(connection.clj:91)"
  "util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165)"
  "util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)"
  "driver.mongo.connection$do_with_mongo_client.invokeStatic(connection.clj:90)"
  "driver.mongo.connection$do_with_mongo_client.invoke(connection.clj:86)"
  "driver.mongo$fn__125623.invokeStatic(mongo.clj:319)"
  "driver.mongo$fn__125623.invoke(mongo.clj:317)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
  "query_processor.context.default$default_runf.invoke(default.clj:42)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71961.invoke(cache.clj:229)"
  "query_processor.middleware.permissions$check_query_permissions$fn__66347.invoke(permissions.clj:140)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71782.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71792.invoke(enterprise.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71224.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__73106$combined_post_process__73111$combined_post_process_STAR___73112.invoke(query_processor.clj:262)"
  "query_processor$fn__73106$combined_pre_process__73107$combined_pre_process_STAR___73108.invoke(query_processor.clj:259)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66444.invoke(fetch_source_query.clj:303)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71872$fn__71876.invoke(resolve_database_and_driver.clj:77)"
  "driver$do_with_driver.invokeStatic(driver.clj:97)"
  "driver$do_with_driver.invoke(driver.clj:92)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71872.invoke(resolve_database_and_driver.clj:76)"
  "query_processor.middleware.store$initialize_store$fn__67050$fn__67051.invoke(store.clj:14)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.middleware.store$initialize_store$fn__67050.invoke(store.clj:13)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__71869.invoke(resolve_database_and_driver.clj:60)"
  "query_processor.middleware.normalize_query$normalize$fn__72174.invoke(normalize_query.clj:38)"
  "query_processor.middleware.enterprise$fn__71809$handle_audit_app_internal_queries__71810$fn__71812.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__71820.invoke(enterprise.clj:103)"
  "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__70935.invoke(constraints.clj:104)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__72105.invoke(process_userland_query.clj:156)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72706.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___62605$thunk__62607.invoke(reducible.clj:126)"
  "query_processor.reducible$async_qp$qp_STAR___62605.invoke(reducible.clj:132)"
  "query_processor.reducible$sync_qp$qp_STAR___62617.doInvoke(reducible.clj:153)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
  "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
  "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
  "api.dataset$run_query_async$fn__93567.invoke(dataset.clj:79)"
  "query_processor.streaming$streaming_response_STAR_$fn__53135$fn__53137.invoke(streaming.clj:168)"
  "query_processor.streaming$streaming_response_STAR_$fn__53135.invoke(streaming.clj:167)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__43750.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error "The connection string contains an empty host '[]'. ",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 3,
  :query
  {:expressions
   {"Product"
    [:case
     [[[:=
        [:field 468 nil]
        [:value
         "adult"
         {:base_type :type/Text,
          :effective_type :type/Text,
          :coercion_strategy nil,
          :semantic_type :type/Source,
          :database_type "java.lang.String",
          :name "source"}]]
       "VMA"]]
     {:default
      [:case
       [[[:=
          [:field 468 nil]
          [:value
           "vmc"
           {:base_type :type/Text,
            :effective_type :type/Text,
            :coercion_strategy nil,
            :semantic_type :type/Source,
            :database_type "java.lang.String",
            :name "source"}]]
         "VMC"]]]}]},
   :fields
   [[:field 472 nil]
    [:field 480 {:base-type :type/Text}]
    [:field 468 nil]
    [:field 478 nil]
    [:field 473 {:temporal-unit :default}]
    [:field 2002 {:base-type :type/Text}]
    [:expression "Product" {:base-type :type/Text}]],
   :filter
   [:=
    [:field 1740 nil]
    [:value
     false
     {:base_type :type/Boolean,
      :effective_type :type/Boolean,
      :coercion_strategy nil,
      :semantic_type :type/Category,
      :database_type "java.lang.Boolean",
      :name "test_business"}]],
   :source-table 65,
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :type :query,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 26, :context :ad-hoc},
  :user-parameters
  [{:id "74ba1e3c", :type :string/=, :target [:dimension [:field 480 nil]]}
   {:id "d8c5d488", :type :string/=, :target [:dimension [:field 2002 nil]]}
   {:id "6ffa3994", :type :string/=, :target [:dimension [:expression "Product"]]}]},
 :data {:rows [], :cols []}}

### Information about your Metabase installation

```JSON
Chrome Version 122.0.6261.129
macOS 14.3.1 (23D60)
MySQL
Metabase 0.49
```

### Severity

Blocking all the users

**Comment by paoliniluis** [comment]
@poldal12 Go to settings->admin->database-> and check if the connection string on Mongo is there, pretty sure it's not

**Comment by poldal12** [comment]
@paoliniluis Thank you, this was the issue.
