### ISSUE TITLE
GUI model joining native ones break with column not found error

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#40252]
### Describe the bug

After updating its metadata, GUI based model joining native models break with a column not found error.

### To Reproduce
(See a simpler way to reproduce in the comments below).

1. Create a native model `wcount`: 
```
select year(created_at), count(*) as WidgetCount from products where category = 'Widget' group by year(created_at)
```

2. Create a native model `gcount`: 
```
select year(created_at), count(*) as GadgetCount from products where category = 'Gadget' group by year(created_at)
```
3. Create a GUI model `joined`: inner join models created on step 1 and 2, on the year column. Save it.

4. Edit the metadata of `joined`, and rename the count(*) fields: WidgetCount, GadgetCount. Save it.

5. See it break:
<img width="363" alt="image" src="https://github.com/metabase/metabase/assets/11080638/e6b926a1-3e40-478c-a71d-5b7cc61fddae">

### Expected behavior

It should work.

### Logs

n/a

### Information about your Metabase installation
Seen this on master (stats) as of:
```
Built on 2024-03-18
Hash: 6710930
```
I could not reproduce this on v1.49.0, so I also added the .Regression label.

### Severity

Probably P2 - I found it while troubleshooting something else), it might be a regression though.

### Additional context

SQL generated:
```
SELECT
  "source"."EXTRACT(YEAR
FROM CREATED_AT)" AS "EXTRACT(YEAR FROM CREATED_AT)",
  "source"."GADGETCOUNT" AS "GADGETCOUNT",
  "wcount - EXTRACT(YEAR FROM CREATED_AT)"."EXTRACT(YEAR FROM CREATED_AT)" AS "wcount - EXTRACT(YEAR FROM CREATED_AT)__EXTRACT(YEA_8b131169",
  "wcount - EXTRACT(YEAR FROM CREATED_AT)"."WIDGETCOUNT" AS "wcount - EXTRACT(YEAR FROM CREATED_AT)__WIDGETCOUNT"
FROM
  (
    select
      year(created_at),
      count(*) as GadgetCount
    from
      products
    where
      category = 'Gadget'
    group by
      year(created_at)
  ) AS "source"
 
LEFT JOIN (
    select
      year(created_at),
      count(*) as WidgetCount
    from
      products
    where
      category = 'Widget'
    group by
      year(created_at)
  ) AS "wcount - EXTRACT(YEAR FROM CREATED_AT)" ON "source"."EXTRACT(YEAR FROM CREATED_AT)" = "wcount - EXTRACT(YEAR FROM CREATED_AT)"."EXTRACT(YEAR FROM CREATED_AT)"
LIMIT
  1048575
 ```

**Comment by zbodi74** [comment]
This is now broken on `49.1`. Here is a simpler reproduction:
1. create native model `A`: `select 1 as a1, 2 as a2`
2. create native model `B`: `select 1 as b1, 2 as b2`
3. create GUI model A+B: A inner join B, on A.A1=B.B1
4. edit the metadata of A+B: rename the third column from B - A1->B1 to anything else
5.(!) save it and see the error:

Column "source.B1" not found; SQL statement:
```
SELECT "source"."A1" AS "A1",
       "source"."A2" AS "A2",
       "source"."B1" AS "B1",
       "source"."B2" AS "B2"
FROM (
    SELECT "source"."A1" AS "A1",
           "source"."A2" AS "A2",
            "B - A1"."B1" AS "B - A1__B1",
            "B - A1"."B2" AS "B - A1__B2"
    FROM (
        select 1 as a1,
               2 as a2 ) AS "source"
    LEFT JOIN (
        select 1 as b1, 
               2 as b2 ) AS "B - A1" 
    ON "source"."A1" = "B - A1"."B1"
) AS "source"
LIMIT 2000
```

**Comment by zbodi74** [comment]
@uladzimirdev - confirmed, it works fine on 49.2.

**Comment by uladzimirdev** [comment]
The issue still exists, the key point is `inner join`

**Comment by uladzimirdev** [comment]
I added a repro test for this issue https://github.com/metabase/metabase/pull/40772

also the test passed at CI and in simulating fast 3g, but fails when you run it locally (the issue comes from BE), maybe some race condition.

Stacktrace is added to the repro issue

**Comment by bshepherdson** [comment]
For some reason this wouldn't repro for me on the first edit of the column name in the metadata. I edited it again and saw the issue.

The generated SQL shows the issue fairly plainly:

```sql
SELECT
  "source"."A1" AS "A1",
  "source"."A2" AS "A2",
  "source"."B1" AS "B1",
  "source"."B2" AS "B2"
FROM (
  SELECT
    "source"."A1" AS "A1",
    "source"."A2" AS "A2",
    "B - A1"."B1" AS "B - A1__B1",
    "B - A1"."B2" AS "B - A1__B2"
  FROM (select 1 as a1, 2 as a2) AS "source"
  INNER JOIN (select 1 as b1, 2 as b2) AS "B - A1"
  ON "source"."A1" = "B - A1"."B1"
) AS "source"
LIMIT 2000
```

The outermost layer's source aliases don't agree with the inner layer's desired aliases. We're failing to match up the outer layer's fields with the inner layer's fields, so we lose track of the naming.

I've got a fix on the way for this.

**Comment by uladzimirdev** [comment]
@bshepherdson have you tried running the linked repro e2e?

**Comment by bshepherdson** [comment]
Not yet, but I'll be sure to test it as part of the PR.
