### ISSUE TITLE
Generic ODBC driver

### ISSUE THREAD

**Issue by 100n0m3** [metabase/metabase#4026]
I would like to propose the use of odbc datasource when running on windows system
it's possible?
Is there any way to implement it?

**Comment by camsaul** [comment]
@100n0m3 I don't think there's a big chance we're going to implement a generic ODBC interface in the near future. We might offer a generic JDBC driver at some point (#3014) but none of us here really ever use ODBC (or Windows for that matter) so this would be hard for us to develop and test.

If you're familiar with Clojure and feeling adventurous you can try adding support for it yourself. [We have a brief guide to how Metabase drivers work here](https://github.com/metabase/metabase/wiki/Writing-A-Driver).

**Comment by camsaul** [comment]
Actually I guess if we had the generic JDBC driver you could use the ODBC-JDBC bridge (`sun.jdbc.odbc.JdbcOdbcDriver`) with no work on your part but I think that's officially deprecated: https://docs.oracle.com/javase/7/docs/technotes/guides/jdbc/bridge.html

**Comment by camsaul** [comment]
Closing this out since the ODBC-JDBC bridge [was removed in Java 8](https://docs.oracle.com/javase/7/docs/technotes/guides/jdbc/bridge.html)
