### ISSUE TITLE
Copying and pasting values from a spreadsheet to a filter and insert a unique value

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#40265]
### Describe the bug

This is a regression from v47. We used to allow copy-paste from spreadsheets, e.g.:
![image](https://github.com/metabase/metabase/assets/1711649/52adc3b6-40aa-48ab-b207-7921b3bb9b5e)
```
<google-sheets-html-origin><style type="text/css"><!--td {border: 1px solid #cccccc;}br {mso-data-placement:same-cell;}--></style>
Gizmo
--
Gadget


```

In v47 we used to insert values like:
![filter47](https://github.com/metabase/metabase/assets/1711649/9869f3f7-d226-4efe-ba28-751857b40f46)

But now in v49 we do:
![filterv49](https://github.com/metabase/metabase/assets/1711649/230241be-aac5-4531-97ce-5d65cc00df0c)

This is a step back in ergonomics

### To Reproduce

1) create a spreadsheet with 2 values on different rows: Gizmo and Gadget
2) go to metabase product table and try filtering on the category field, see the difference

### Expected behavior

We should provide the same behavior as v47

### Logs

NA

### Information about your Metabase installation

```JSON
v49
```

### Severity

P2 (lost ergonomics)

**Comment by darksciencebase** [comment]
also https://github.com/metabase/metabase/issues/40224

**Comment by alexandroabalo** [comment]
Sorry about reopening the thread but in 0.49.1 it seems to not be working properly. 
![filterNotWorking](https://github.com/metabase/metabase/assets/85824168/6ca9d0fd-7c36-451b-9951-80794b68cdda)

**Comment by hss-iullah** [comment]
Hi this still doesn't appear to work. If I copy and paste a batch of cells fom CSV/Excel/G.Sheet, only the last cell pasted returns a result. All cells / value before appear to be getting a CRLF added to the end which seems to be causing the issue. When I fire the SQL created by MB, it's definitely adding a CR to the end of each value.
Oddly, if I copy and paste the cells which someone has sent to me via Teams, it works.

3rd value returns, values 1 and 2 don't as a CRLF is being added and passed down to the SQL.
![image](https://github.com/metabase/metabase/assets/149382782/ca58a3ea-db11-41be-b586-95895f81bc9e)

Not sure how this was working before as I believe a CR is always needed?

**Comment by hss-iullah** [comment]
0.49.3 - still not fixed.

![image](https://github.com/metabase/metabase/assets/149382782/3a8ec6fe-07a4-4373-991b-cccb42cf5ab4)

**Comment by paoliniluis** [comment]
@hss-iullah please post reproduction steps, otherwise we can’t fix what we can’t hit

**Comment by hss-iullah** [comment]
I simply copied cells from Excel and pasted into the filter. It didn't work against a Redshift database. You can clearly see the carriage return which is being passed into the SQL from Metabase  (the screenshot I supplied earlier).

**Comment by ranquild** [comment]
@hss-iullah are you absolutely sure you're on 49.3? We can't repro with 49.3 and an excel spreadsheet

**Comment by hss-iullah** [comment]
OK sorted. Some caching at play. Confirmed working. Thanks.
