### ISSUE TITLE
Can not use variable in question: Packets out of order when reading field packets

### ISSUE THREAD

**Issue by yuyii** [metabase/metabase#40305]
### Describe the bug

when I use mysql database type to connect starrocks3.2.4 , and I created a question with variable.but error occured.

<img width="849" alt="image" src="https://github.com/metabase/metabase/assets/1222123/a1cd0972-50a6-46df-859b-273536a18e2d">

But if I do not use variable ,then everything is ok.

<img width="709" alt="image" src="https://github.com/metabase/metabase/assets/1222123/55d06a1d-6a13-4450-a6ed-07b0bb833398">

### To Reproduce

1. create datasource connect to starrocks 3.2.4
2. create question with variable
3. preview, See error

### Logs

[46dc2f81-30a1-4dcb-8993-277c7e7a1b1f] 2024-03-19T23:32:01+08:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Packets out of order when reading field packets, expected was EOF stream.Packet contents (hex) = 
+--------------------------------------------------+
|  0  1  2  3  4  5  6  7   8  9  a  b  c  d  e  f |
+--------------------------------------------------+------------------+
| 03 64 65 66 00 00 00 0F  E5 88 86 E6 A1 88 E5 90 | .def............ |
| 8D E5 8D 95 E9 87 8F 0F  E5 88 86 E6 A1 88 E5 90 | ................ |
| 8D E5 8D 95 E9 87 8F 0C  3F 00 14 00 00 00 08 00 | ........?....... |
| 00 00 00 00                                      | ....             |
+--------------------------------------------------+------------------+

{:database_id 35,
 :started_at #t "2024-03-19T23:31:59.722911+08:00[Asia/Shanghai]",
 :via
 [{:status :failed,
   :class java.sql.SQLNonTransientConnectionException,
   :error
   "Packets out of order when reading field packets, expected was EOF stream.Packet contents (hex) = \n+--------------------------------------------------+\n|  0  1  2  3  4  5  6  7   8  9  a  b  c  d  e  f |\n+--------------------------------------------------+------------------+\n| 03 64 65 66 00 00 00 0F  E5 88 86 E6 A1 88 E5 90 | .def............ |\n| 8D E5 8D 95 E9 87 8F 0F  E5 88 86 E6 A1 88 E5 90 | ................ |\n| 8D E5 8D 95 E9 87 8F 0C  3F 00 14 00 00 00 08 00 | ........?....... |\n| 00 00 00 00                                      | ....             |\n+--------------------------------------------------+------------------+\n",
   :stacktrace
   ["org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.handleIoException(AbstractQueryProtocol.java:2089)"
    "org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readResultSet(AbstractQueryProtocol.java:1861)"
    "org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1568)"
    "org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518)"
    "org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:257)"
    "org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:235)"
    "org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.setMaxRows(AbstractQueryProtocol.java:1421)"
    "org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.prolog(AbstractQueryProtocol.java:1901)"
    "org.mariadb.jdbc.MariaDbStatement.executeQueryPrologue(MariaDbStatement.java:214)"
    "org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:201)"
    "org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)"
    "org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)"
    "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)"
    "--> driver.sql_jdbc.execute$fn__77780.invokeStatic(execute.clj:556)"
    "driver.sql_jdbc.execute$fn__77780.invoke(execute.clj:554)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:569)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:565)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__77863$fn__77864.invoke(execute.clj:696)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__77863.invoke(execute.clj:695)"
    "driver.sql_jdbc.execute$fn__77656$fn__77657.invoke(execute.clj:388)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
    "driver.sql_jdbc.execute$fn__77656.invokeStatic(execute.clj:382)"
    "driver.sql_jdbc.execute$fn__77656.invoke(execute.clj:380)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:686)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc$fn__105637.invokeStatic(sql_jdbc.clj:82)"
    "driver.sql_jdbc$fn__105637.invoke(sql_jdbc.clj:80)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
    "query_processor.context.default$default_runf.invoke(default.clj:42)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
    "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:202)"
    "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:186)"

### Information about your Metabase installation

```JSON
- metabase version 0.48.8
- metabase run as jar file in centos
- metabase database: mysql 8.0.30
- datasource: starrocks 3.2.4 with datatype mysql
```

### Severity

blocking

### Additional context

while connect to other starrocks version ,everything is ok.

**Comment by paoliniluis** [comment]
seems like an issue with starrocks, have you checked https://docs.starrocks.io/docs/reference/System_variable/#max_allowed_packet?

**Comment by yuyii** [comment]
I've try to edit  max_allowed_packet = 67108864,but no effects, same error...
