### ISSUE TITLE
Missing Description for MariaDB Connector in Data Source Documentation

### ISSUE THREAD

**Issue by HugoWenTD** [metabase/metabase#40325]
### Describe the bug

Respectfully, I'd like to bring attention to the absence of a description for the MariaDB connectivity within the data source documentation on the [Metabase website](https://www.metabase.com/data_sources/), despite its compatibility with Metabase through the MariaDB connector. Additionally, it's worth noting that even MySQL connectivity utilizes the MariaDB connector, as indicated in the documentation found at [connecting-to-mysql-8-servers](https://www.metabase.com/docs/latest/databases/connections/mysql#connecting-to-mysql-8-servers).

I could not find the website source code on GitHub. Thus, I'm raising this issue to request for adding MariaDB in the documentation.

### To Reproduce

1. Go to main data source page https://www.metabase.com/data_sources/
2. There's no MariaDB database connectivity mentioned.
3. Go to https://www.metabase.com/data_sources/mysql
4. It only mentioned `Connect Metabase to your MySQL database`

### Expected behavior

1. The main data source page https://www.metabase.com/data_sources/ should include MariaDB database.
2. MariaDB should likewise be mentioned in the sub-page of "MYSQL connector" https://www.metabase.com/data_sources/mysql.

### Logs

N/A

### Information about your Metabase installation

N/A

### Severity

Documentation Only

**Comment by paoliniluis** [comment]
Hi @HugoWenTD, you're right, we only say that we connect to MariaDB on "Metabase uses the MariaDB connector to connect to MariaDB and MySQL servers"

**Comment by HugoWenTD** [comment]
> Hi @HugoWenTD, you're right, we only say that we connect to MariaDB on "Metabase uses the MariaDB connector to connect to MariaDB and MySQL servers"

yeah, as a new user begin to use Metabase, I refer to the main data sources page at https://www.metabase.com/data_sources/ to check for compatibility with my database. However, it's unfortunate that MariaDB is not listed there, nor is it specifically mentioned on its direct sub-page at https://www.metabase.com/data_sources/mysql. The description simply states:
`Connect Metabase to your **MySQL** database, and empower your team to explore, visualize, and publish insights in just five minutes.`

Until I reached the third level of detailed documentation I can eventually see something related to MariaDB:
https://www.metabase.com/docs/latest/databases/connections/mysql#connecting-to-mysql-8-servers

So IMO for better user experience and facilitate adoption among MariaDB users, it would be beneficial for Metabase to include mention of MariaDB on the main data sources page at https://www.metabase.com/data_sources. Or at least a simple change on https://www.metabase.com/data_sources/mysql could be:
> \- "Connect Metabase to your **MySQL** database, and empower your team to explore, visualize, and publish insights in just five minutes."
> \+ "Connect Metabase to your **MySQL or MariaDB** database, and empower your team to explore, visualize, and publish insights in just five minutes."

**Comment by ottok** [comment]
@paoliniluis This has 10 +1's - could you please considering merging this?

**Comment by paoliniluis** [comment]
@ottok there's no PR to merge

**Comment by ottok** [comment]
Is the website source code somewhere on GitHub? Can anyone fix this by
contributing a PR instead to close this Issue?

**Comment by ottok** [comment]
@paoliniluis Is the website source code somewhere on GitHub? Can anyone fix this by contributing a PR?

**Comment by HugoWenTD** [comment]
@jeff-bruemmer Great! Thank you for adding the MariaDB documentation. It looks good to me!
