### ISSUE TITLE
Group managers can't add people to groups

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#40329]
### Describe the bug

A group manager is unable to add people to groups.  This is a key function of the group manager feature.

### To Reproduce

1. Go to your Metabase
2. Create two new users:
a Cynthia GroupManager
b Cynthia NotInAgroup
4. Create a new group, TestyTest
5. Add Cynthia GroupManager to TestyTest
6. Make Cynthia GroupManager the manager of TestyTest
7. Log in as CynthiaGroupManager and navigate to the Groups tab
8. Click on the group TestyTest
9. Press Add People
10. Attempt to Add Cynthia NotinAgroup

### Expected behavior

You should be able to add Cynthia Notinagroup, but you can't

### Information about your Metabase installation

```JSON
Seen in 48.8
```

### Severity

This is entire point of the feature, and it doesn't work

### Additional context

Related to https://github.com/metabase/metabase/issues/40328

**Comment by luizarakaki** [comment]
Fixed by https://github.com/metabase/metabase/pull/40619
