### ISSUE TITLE
Specific date filter shifts dates by one day

### ISSUE THREAD

**Issue by jonathan-k-shapiro** [metabase/metabase#40332]
### Describe the bug

When creating a question with the Metabase editor and setting a filter on a range of specific dates as shown

![image](https://github.com/metabase/metabase/assets/16065058/3801586e-8f39-4fba-8db5-ac8808bb6a11)

the results returned are shifted one day 'forward' (spanning Feb 2 through Feb 8) as shown

![image](https://github.com/metabase/metabase/assets/16065058/4a91c32b-2bed-493a-8d0f-68c16795ca0b)

What is most puzzling is that that the generated SQL from the editor appears to be correct
```
SELECT
  DATE_TRUNC("day", "_DIM_DATES__via___DIM_DATE_KEY"."DATE") AS "_DIM_DATES__via___DIM_DATE_KEY__DATE",
  COUNT(*) AS "count"
FROM
  "ANALYTICS"."PUBLIC"."_REDACTED_"
 
LEFT JOIN "ANALYTICS"."PUBLIC"."_DIM_DATES" AS "_DIM_DATES__via___DIM_DATE_KEY" ON "PUBLIC"."_REDACTED_"."_DIM_DATE_KEY" = "_DIM_DATES__via___DIM_DATE_KEY"."_DIM_DATE_KEY"
WHERE
  (
    "_DIM_DATES__via___DIM_DATE_KEY"."DATE" >= '2024-02-01 00:00 Z':: timestamp_tz
  )
 
   AND (
    "_DIM_DATES__via___DIM_DATE_KEY"."DATE" < '2024-02-08 00:00 Z':: timestamp_tz
  )
GROUP BY
  DATE_TRUNC("day", "_DIM_DATES__via___DIM_DATE_KEY"."DATE")
ORDER BY
  DATE_TRUNC("day", "_DIM_DATES__via___DIM_DATE_KEY"."DATE") ASC
  ```
  
  And, indeed, if I take the above SQL and create a new SQL query in Metabase, I get the correct range of dates
  
  
![image](https://github.com/metabase/metabase/assets/16065058/19122bf2-cea5-43b0-a743-a81be5d13cb0)

### To Reproduce

Unfortunately, I am not able to reproduce with an equivalent query in the sample database. One potential difference is that the  sample database uses colums of type DateTime, whereas the date dimension in my example is of type Date. But it's still baffling why the same SQL generated by the question editor works when submitted as SQL.

### Expected behavior

I would expect the Metabase question to return the same set of rows as the SQL query does, for a set of dates that match what was selected in the date picker.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.210-201.852.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "materialize"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

Severely degrading the trust our stakeholders place in Metabase

### Additional context

This example is running against Snowflake.

**Comment by darksciencebase** [comment]
is this https://github.com/metabase/metabase/issues/39769 ?

**Comment by jonathan-k-shapiro** [comment]
> is this https://github.com/metabase/metabase/issues/39769 ?

Not sure but tracking PR #40416 mentioned there with hope.
