### ISSUE TITLE
QB header jumps when switching between a simple and a notebook modes

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#40334]
### Describe the bug

Due to the computed CSS styles, a query builder header is jumping when switching between its modes (simple / notebook). This creates visually displeasing and slightly annoying effect because all textual elements move with the header.

### To Reproduce

1. Open any table and toggle the notebook view on and off
![Kapture 2024-03-19 at 23 04 10](https://github.com/metabase/metabase/assets/31325167/80a8a62c-b34b-4646-8fdc-97bffd7b69f8)

### Expected behavior

Query builder header should have a fixed height, and all its elements should render in a same position every time, regardless of the chosen mode.

### Severity
It can be quite annoying, but it doesn't obstruct the work on QB.

**Comment by asimumba** [comment]
Hi,

I am getting this effect but on filters on a question written in SQL. When I apply a filter I get a jump that re-aligns the order of the filters. I am using Metabase V0.49.1, equally on v0.49.0.
