### ISSUE TITLE
Language version switching issues

### ISSUE THREAD

**Issue by sccll** [metabase/metabase#40342]
### Describe the bug

When I log in to metabase, I set the language version to English, but sometimes when I log in, it still displays Chinese text. No one else is using my account, just me logging in.
![image](https://github.com/metabase/metabase/assets/59472399/59a6a82a-5047-42a4-b92c-e08801bc3863)
![image](https://github.com/metabase/metabase/assets/59472399/4e73ab55-2979-409b-851b-b2aeab81cd37)

### Information about your Metabase installation

```JSON
metabase Version： v0.47.7
database： PostgreSQL
```

### Severity

My users are so frustrated that they have to switch again each time

**Comment by npfitz** [comment]
@sccll I took a look at this in both the latest version, as well as 47.4, and I don't seem to be able to reproduce the issue. Do you know what the language setting for the instance is?

**Comment by npfitz** [comment]
@sccll I was actually able to reproduce. I'm going to work on a fix, but for now refreshing the page after you log in should ensure that translations are correct across the app
