### ISSUE TITLE
Filtering by Aggregated Common Metrics fails with "column not found"

### ISSUE THREAD

**Issue by cgg-pwdt** [metabase/metabase#40355]
### Describe the bug

We are using  Metabase (self-hosted) v0.49.0 with AWS Athena and noticed an issue with Common Metrics and Filtering by these aggregations. 

When we try to filter after summarising by a **common metric**, we get a "COLUMN NOT FOUND" error

When we Convert the question to SQL we see that the filter is referencing the original column name and not the alias created by the Common Metric. I'm attaching the SQL generated where you can see the last WHERE referring "__sessions" instead of "# Sessions".

We have tested this by naming the metric "Number of Sessions" to test if the problem was the "#". Didn't work either.

### To Reproduce

1. Go to 'New > Question'
2. Click on 'Summarize by > Select a common metric'
3. Scroll down to 'filter (by aggregation) > select common metric and pick any value'
4. See error (column not found)

### Expected behavior

Expected behavior would be to generate a question sucessfully. Underneath the hood I believe the expected behavior would be generating a SQL code referencing the new Column Alias instead of the original one.

### Logs

[40661243-a7fa-444f-afce-ff115265bdc4] 2024-03-20T11:46:37+00:00 WARN metabase.query-processor.middleware.upgrade-field-literals Warning: clause [:field "__sessions" {:base-type :type/Integer}] refers to a Field that may not be present in the source query. Query may not work as expected. Found: #{"location_name" "# sessions" "# Sessions"}
[40661243-a7fa-444f-afce-ff115265bdc4] 2024-03-20T11:46:40+00:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. COLUMN_NOT_FOUND: line 2:464: Column 'source.__sessions' cannot be resolved or requester is not authorized to access requested resources [Execution ID: 5e6493f8-e91f-4451-a56c-4c5a17b2a618]
{:database_id 2,
 :started_at #t "2024-03-20T11:46:37.504065Z[GMT]",
 :via
 [{:status :failed,
   :class java.sql.SQLException,
   :error
   "[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. COLUMN_NOT_FOUND: line 2:464: Column 'source.__sessions' cannot be resolved or requester is not authorized to access requested resources [Execution ID: 5e6493f8-e91f-4451-a56c-4c5a17b2a618]",
   :stacktrace
   ["com.simba.athena.athena.api.AJClient.executeQuery(Unknown Source)"
    "com.simba.athena.athena.dataengine.AJQueryExecutor.execute(Unknown Source)"
    "com.simba.athena.jdbc.common.SStatement.executeNoParams(Unknown Source)"
    "com.simba.athena.jdbc.common.BaseStatement.execute(Unknown Source)"
    "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
    "--> driver.sql_jdbc.execute$fn__78950.invokeStatic(execute.clj:560)"
    "driver.sql_jdbc.execute$fn__78950.invoke(execute.clj:558)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:568)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:565)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__79031$fn__79032.invoke(execute.clj:699)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__79031.invoke(execute.clj:698)"
    "driver.sql_jdbc.execute$fn__78824$fn__78825.invoke(execute.clj:388)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
    "driver.sql_jdbc.execute$fn__78824.invokeStatic(execute.clj:382)"
    "driver.sql_jdbc.execute$fn__78824.invoke(execute.clj:380)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:692)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc$fn__106344.invokeStatic(sql_jdbc.clj:78)"
    "driver.sql_jdbc$fn__106344.invoke(sql_jdbc.clj:76)"
    "driver.athena$fn__115542.invokeStatic(athena.clj:445)"
    "driver.athena$fn__115542.invoke(athena.clj:443)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
    "query_processor.context.default$default_runf.invoke(default.clj:42)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71961.invoke(cache.clj:229)"
    "query_processor.middleware.permissions$check_query_permissions$fn__66347.invoke(permissions.clj:140)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71782.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71792.invoke(enterprise.clj:64)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71224.invoke(mbql_to_native.clj:24)"
    "query_processor$fn__73106$combined_post_process__73111$combined_post_process_STAR___73112.invoke(query_processor.clj:262)"
    "query_processor$fn__73106$combined_pre_process__73107$combined_pre_process_STAR___73108.invoke(query_processor.clj:259)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66444.invoke(fetch_source_query.clj:303)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71872$fn__71876.invoke(resolve_database_and_driver.clj:77)"
    "driver$do_with_driver.invokeStatic(driver.clj:97)"
    "driver$do_with_driver.invoke(driver.clj:92)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71872.invoke(resolve_database_and_driver.clj:76)"
    "query_processor.middleware.store$initialize_store$fn__67050$fn__67051.invoke(store.clj:14)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.middleware.store$initialize_store$fn__67050.invoke(store.clj:13)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__71869.invoke(resolve_database_and_driver.clj:60)"
    "query_processor.middleware.normalize_query$normalize$fn__72174.invoke(normalize_query.clj:38)"
    "query_processor.middleware.enterprise$fn__71809$handle_audit_app_internal_queries__71810$fn__71812.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__71820.invoke(enterprise.clj:103)"
    "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__70935.invoke(constraints.clj:104)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__72105.invoke(process_userland_query.clj:156)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72706.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___62605$thunk__62607.invoke(reducible.clj:126)"
    "query_processor.reducible$async_qp$qp_STAR___62605.invoke(reducible.clj:132)"
    "query_processor.reducible$sync_qp$qp_STAR___62617.doInvoke(reducible.clj:153)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
    "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
    "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
    "api.dataset$run_query_async$fn__93567.invoke(dataset.clj:79)"
    "query_processor.streaming$streaming_response_STAR_$fn__53135$fn__53137.invoke(streaming.clj:168)"
    "query_processor.streaming$streaming_response_STAR_$fn__53135.invoke(streaming.clj:167)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__43750.invoke(streaming_response.clj:88)"],
   :state "HY000"}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. COLUMN_NOT_FOUND: line 2:464: Column 'source.__sessions' cannot be resolved or requester is not authorized to access requested resources [Execution ID: 5e6493f8-e91f-4451-a56c-4c5a17b2a618]",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__79031$fn__79032.invoke(execute.clj:701)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__79031.invoke(execute.clj:698)"
    "driver.sql_jdbc.execute$fn__78824$fn__78825.invoke(execute.clj:388)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
    "driver.sql_jdbc.execute$fn__78824.invokeStatic(execute.clj:382)"
    "driver.sql_jdbc.execute$fn__78824.invoke(execute.clj:380)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:692)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc$fn__106344.invokeStatic(sql_jdbc.clj:78)"
    "driver.sql_jdbc$fn__106344.invoke(sql_jdbc.clj:76)"
    "driver.athena$fn__115542.invokeStatic(athena.clj:445)"
    "driver.athena$fn__115542.invoke(athena.clj:443)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
    "query_processor.context.default$default_runf.invoke(default.clj:42)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71961.invoke(cache.clj:229)"
    "query_processor.middleware.permissions$check_query_permissions$fn__66347.invoke(permissions.clj:140)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71782.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71792.invoke(enterprise.clj:64)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71224.invoke(mbql_to_native.clj:24)"
    "query_processor$fn__73106$combined_post_process__73111$combined_post_process_STAR___73112.invoke(query_processor.clj:262)"
    "query_processor$fn__73106$combined_pre_process__73107$combined_pre_process_STAR___73108.invoke(query_processor.clj:259)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66444.invoke(fetch_source_query.clj:303)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71872$fn__71876.invoke(resolve_database_and_driver.clj:77)"
    "driver$do_with_driver.invokeStatic(driver.clj:97)"
    "driver$do_with_driver.invoke(driver.clj:92)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71872.invoke(resolve_database_and_driver.clj:76)"
    "query_processor.middleware.store$initialize_store$fn__67050$fn__67051.invoke(store.clj:14)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.middleware.store$initialize_store$fn__67050.invoke(store.clj:13)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__71869.invoke(resolve_database_and_driver.clj:60)"
    "query_processor.middleware.normalize_query$normalize$fn__72174.invoke(normalize_query.clj:38)"
    "query_processor.middleware.enterprise$fn__71809$handle_audit_app_internal_queries__71810$fn__71812.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__71820.invoke(enterprise.clj:103)"
    "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__70935.invoke(constraints.clj:104)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__72105.invoke(process_userland_query.clj:156)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72706.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___62605$thunk__62607.invoke(reducible.clj:126)"
    "query_processor.reducible$async_qp$qp_STAR___62605.invoke(reducible.clj:132)"
    "query_processor.reducible$sync_qp$qp_STAR___62617.doInvoke(reducible.clj:153)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
    "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
    "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
    "api.dataset$run_query_async$fn__93567.invoke(dataset.clj:79)"
    "query_processor.streaming$streaming_response_STAR_$fn__53135$fn__53137.invoke(streaming.clj:168)"
    "query_processor.streaming$streaming_response_STAR_$fn__53135.invoke(streaming.clj:167)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__43750.invoke(streaming_response.clj:88)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :athena,
    :sql
    ["-- Metabase:: userID: 5 queryType: MBQL queryHash: 2a70304564a1d4b61ad2845c31f310c6d6b3709fa714df0715d8f44b991105cf"
     "SELECT"
     "  \"source\".\"location_name\" AS \"location_name\","
     "  \"source\".\"# Sessions\" AS \"# Sessions\""
     "FROM"
     "  ("
     "    SELECT"
     "      \"reporting\".\"charging_point_performance\".\"location_name\" AS \"location_name\","
     "      SUM("
     "        \"reporting\".\"charging_point_performance\".\"number_of_session\""
     "      ) AS \"# Sessions\""
     "    FROM"
     "      \"reporting\".\"charging_point_performance\""
     "    GROUP BY"
     "      \"reporting\".\"charging_point_performance\".\"location_name\""
     "    ORDER BY"
     "      \"reporting\".\"charging_point_performance\".\"location_name\" ASC"
     "  ) AS \"source\""
     "WHERE"
     "  \"source\".\"__sessions\" = 0"
     "LIMIT"
     "  2000"],
    :params nil,
    :type :invalid-query}}],
 :action_id nil,
 :error_type :invalid-query,
 :json_query
 {:database 2,
  :type "query",
  :query
  {:filter ["=" ["field" "__sessions" {:base-type "type/Integer"}] 0],
   :source-query
   {:source-table 214, :aggregation [["metric" 13]], :breakout [["field" 4941 {:base-type "type/Text"}]]}},
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"location_name\" AS \"location_name\", \"source\".\"# Sessions\" AS \"# Sessions\" FROM (SELECT \"reporting\".\"charging_point_performance\".\"location_name\" AS \"location_name\", SUM(\"reporting\".\"charging_point_performance\".\"number_of_session\") AS \"# Sessions\" FROM \"reporting\".\"charging_point_performance\" GROUP BY \"reporting\".\"charging_point_performance\".\"location_name\" ORDER BY \"reporting\".\"charging_point_performance\".\"location_name\" ASC) AS \"source\" WHERE \"source\".\"__sessions\" = 0 LIMIT 1048575",
  :params nil},
 :status :failed,
 :class com.simba.athena.support.exceptions.GeneralException,
 :stacktrace
 ["com.simba.athena.athena.api.AJClient.executeQuery(Unknown Source)"
  "com.simba.athena.athena.dataengine.AJQueryExecutor.execute(Unknown Source)"
  "com.simba.athena.jdbc.common.SStatement.executeNoParams(Unknown Source)"
  "com.simba.athena.jdbc.common.BaseStatement.execute(Unknown Source)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__78950.invokeStatic(execute.clj:560)"
  "driver.sql_jdbc.execute$fn__78950.invoke(execute.clj:558)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:568)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:565)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__79031$fn__79032.invoke(execute.clj:699)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__79031.invoke(execute.clj:698)"
  "driver.sql_jdbc.execute$fn__78824$fn__78825.invoke(execute.clj:388)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
  "driver.sql_jdbc.execute$fn__78824.invokeStatic(execute.clj:382)"
  "driver.sql_jdbc.execute$fn__78824.invoke(execute.clj:380)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:692)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc$fn__106344.invokeStatic(sql_jdbc.clj:78)"
  "driver.sql_jdbc$fn__106344.invoke(sql_jdbc.clj:76)"
  "driver.athena$fn__115542.invokeStatic(athena.clj:445)"
  "driver.athena$fn__115542.invoke(athena.clj:443)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
  "query_processor.context.default$default_runf.invoke(default.clj:42)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71961.invoke(cache.clj:229)"
  "query_processor.middleware.permissions$check_query_permissions$fn__66347.invoke(permissions.clj:140)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71782.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71792.invoke(enterprise.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71224.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__73106$combined_post_process__73111$combined_post_process_STAR___73112.invoke(query_processor.clj:262)"
  "query_processor$fn__73106$combined_pre_process__73107$combined_pre_process_STAR___73108.invoke(query_processor.clj:259)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66444.invoke(fetch_source_query.clj:303)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71872$fn__71876.invoke(resolve_database_and_driver.clj:77)"
  "driver$do_with_driver.invokeStatic(driver.clj:97)"
  "driver$do_with_driver.invoke(driver.clj:92)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71872.invoke(resolve_database_and_driver.clj:76)"
  "query_processor.middleware.store$initialize_store$fn__67050$fn__67051.invoke(store.clj:14)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.middleware.store$initialize_store$fn__67050.invoke(store.clj:13)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__71869.invoke(resolve_database_and_driver.clj:60)"
  "query_processor.middleware.normalize_query$normalize$fn__72174.invoke(normalize_query.clj:38)"
  "query_processor.middleware.enterprise$fn__71809$handle_audit_app_internal_queries__71810$fn__71812.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__71820.invoke(enterprise.clj:103)"
  "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__70935.invoke(constraints.clj:104)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__72105.invoke(process_userland_query.clj:156)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72706.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___62605$thunk__62607.invoke(reducible.clj:126)"
  "query_processor.reducible$async_qp$qp_STAR___62605.invoke(reducible.clj:132)"
  "query_processor.reducible$sync_qp$qp_STAR___62617.doInvoke(reducible.clj:153)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
  "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
  "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
  "api.dataset$run_query_async$fn__93567.invoke(dataset.clj:79)"
  "query_processor.streaming$streaming_response_STAR_$fn__53135$fn__53137.invoke(streaming.clj:168)"
  "query_processor.streaming$streaming_response_STAR_$fn__53135.invoke(streaming.clj:167)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__43750.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. COLUMN_NOT_FOUND: line 2:464: Column 'source.__sessions' cannot be resolved or requester is not authorized to access requested resources [Execution ID: 5e6493f8-e91f-4451-a56c-4c5a17b2a618]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 2,
  :type :query,
  :query
  {:filter [:= [:field "__sessions" {:base-type :type/Integer}] [:value 0 {:base_type :type/Integer}]],
   :source-metadata
   [{:semantic_type :type/Category,
     :table_id 214,
     :coercion_strategy nil,
     :name "location_name",
     :settings nil,
     :field_ref [:field 4941 {:base-type :type/Text}],
     :effective_type :type/Text,
     :nfc_path nil,
     :parent_id nil,
     :id 4941,
     :display_name "Location Name",
     :fingerprint
     {:global {:distinct-count 1243, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 22.1776}}},
     :base_type :type/Text}
    {:name "# Sessions",
     :display_name "# Sessions",
     :base_type :type/Integer,
     :semantic_type :type/Quantity,
     :settings nil,
     :field_ref [:aggregation 0]}],
   :fields [[:field 4941 {:base-type :type/Text}] [:field "# Sessions" {:base-type :type/Integer}]],
   :source-query
   {:source-table 214,
    :aggregation
    [[:aggregation-options
      [:sum [:field 4955 {:base-type :type/Integer}]]
      {:name "# Sessions", :display-name "# Sessions"}]],
    :breakout [[:field 4941 {:base-type :type/Text}]],
    :order-by [[:asc [:field 4941 {:base-type :type/Text}]]]},
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 5, :context :ad-hoc}},
 :data {:rows [], :cols []}}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.205-195.804.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking some users

### Additional context

SELECT
  "source"."location_name" AS "location_name",
  "source"."# Sessions" AS "# Sessions"
FROM
  (
    SELECT
      "reporting"."charging_point_performance"."location_name" AS "location_name",
      SUM(
        "reporting"."charging_point_performance"."number_of_session"
      ) AS "# Sessions"
    FROM
      "reporting"."charging_point_performance"
   
GROUP BY
      "reporting"."charging_point_performance"."location_name"
   
ORDER BY
      "reporting"."charging_point_performance"."location_name" ASC
  ) AS "source"
WHERE
  "source"."__sessions" = 0
LIMIT
  1048575

**Comment by ViniAppel** [comment]
Hello guys.
We are experiencing the same problem here. We updated from version 0.48.1 to 0.49.10 yesterday and started having this issue for users who use no-code.
Below is an example screenshot and the query generated by Metabase.

![image](https://github.com/metabase/metabase/assets/68851613/60a3cc6c-2218-4f21-8ab5-e5d12afe0ff3)

`SELECT
  "source"."dim_investor_relations__via__fk_investor_relations__b578e382" AS "dim_investor_relations__via__fk_investor_relations__b578e382",
  "source"."dim_investor_relations__via__fk_investor_relations__43b4316e" AS "dim_investor_relations__via__fk_investor_relations__43b4316e",
  "source"."Tier WuM" AS "Tier WuM",
  SUM("source"."WuM") AS "WuM"
FROM
  (
    SELECT
      "source"."WuM" AS "WuM",
      CASE
        WHEN "source"."WuM" >= 10000000 THEN '5. 10M+'
        ELSE CASE
          WHEN "source"."WuM" >= 1000000 THEN '4. 1-10M'
          ELSE CASE
            WHEN "source"."WuM" >= 500000 THEN '3. 500k-1M'
            ELSE CASE
              WHEN "source"."WuM" >= 100000 THEN '2. 100-500k'
              ELSE CASE
                WHEN "source"."WuM" >= 0 THEN '1. 0-100k'
                ELSE '0. Inactive'
              END
            END
          END
        END
      END AS "Tier WuM"
    FROM
      (
        SELECT
          "dim_investor_relations__via__fk_investor_relations_key"."nk_investor_api_id" AS "dim_investor_relations__via__fk_investor_relations__b8278d3c",
          "dim_investor_relations__via__fk_investor_relations_key"."office_name" AS "dim_investor_relations__via__fk_investor_relations__43b4316e",
          "dim_investor_relations__via__fk_investor_relations_key"."advisor_name" AS "dim_investor_relations__via__fk_investor_relations__b578e382",
          SUM("gold"."fact_balance"."gross_balance") AS "WuM"
        FROM
          "gold"."fact_balance"
         
LEFT JOIN "gold"."dim_investor_relations" AS "dim_investor_relations__via__fk_investor_relations_key" ON "gold"."fact_balance"."fk_investor_relations_key" = "dim_investor_relations__via__fk_investor_relations_key"."sk_investor_relations_key"
          LEFT JOIN "gold"."dim_calendar" AS "dim_calendar__via__fk_calendar_key" ON "gold"."fact_balance"."fk_calendar_key" = "dim_calendar__via__fk_calendar_key"."sk_calendar_key"
       
WHERE
          (
            "dim_calendar__via__fk_calendar_key"."is_month_closure" = TRUE
          )
         
   AND (
            "gold"."fact_balance"."date_balance" >= DATE_TRUNC('month', NOW())
          )
          AND (
            "gold"."fact_balance"."date_balance" < DATE_TRUNC('month', DATE_ADD('month', 1, NOW()))
          )
          AND (
            "dim_investor_relations__via__fk_investor_relations_key"."channel" = 'Warren W'
          )
          AND (
            "dim_investor_relations__via__fk_investor_relations_key"."is_active" = TRUE
          )
          AND (
            "dim_investor_relations__via__fk_investor_relations_key"."advisor_name" IS NOT NULL
          )
          AND (
            (
              "dim_investor_relations__via__fk_investor_relations_key"."advisor_name" <> ''
            )
           
    OR (
              "dim_investor_relations__via__fk_investor_relations_key"."advisor_name" IS NULL
            )
          )
       
GROUP BY
          "dim_investor_relations__via__fk_investor_relations_key"."nk_investor_api_id",
          "dim_investor_relations__via__fk_investor_relations_key"."office_name",
          "dim_investor_relations__via__fk_investor_relations_key"."advisor_name"
       
ORDER BY
          "dim_investor_relations__via__fk_investor_relations_key"."nk_investor_api_id" ASC,
          "dim_investor_relations__via__fk_investor_relations_key"."office_name" ASC,
          "dim_investor_relations__via__fk_investor_relations_key"."advisor_name" ASC
      ) AS "source"
  ) AS "source"
GROUP BY
  "source"."dim_investor_relations__via__fk_investor_relations__b578e382",
  "source"."dim_investor_relations__via__fk_investor_relations__43b4316e",
  "source"."Tier WuM"
ORDER BY
  "source"."dim_investor_relations__via__fk_investor_relations__b578e382" ASC,
  "source"."dim_investor_relations__via__fk_investor_relations__43b4316e" ASC,
  "source"."Tier WuM" ASC`

**Comment by cgg-pwdt** [comment]
@ViniAppel we found a workaround. this seems to happen only when we have spaces on the metrics / dimensions. if we don't, it works.

**Comment by mngr** [comment]
Can we close this?

**Comment by NevRA** [comment]
Closing this one, it looks like some issue with automation, PR was merged
