### ISSUE TITLE
Removed admin still receives new user emails

### ISSUE THREAD

**Issue by parisholley** [metabase/metabase#4039]
Had a user setup in the system as an admin, then removed the user, however when a new account sign up happens (through google apps), it still attempts to cc that user on the notification.

- Chrome 55.0
- OS X 10.11.5
- Postgres 9.1
- Metabase: 0.21.1 (Docker, H3)
- Metabase version: (e.x. 0.19.3)

**Comment by camsaul** [comment]
Fixed by #4190
