### ISSUE TITLE
Multi-line custom expression lines collide over each other

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4045]
@tlrobinson, I think maybe this is the padding trade-off you were referencing when we were discussing adding in the ability to correctly use the cmnd+arrow shortcuts while typing a custom expression. I don't think I realized this is what you meant. Can you confirm that that's what this is? I think I'd be embarrassed if we shipped it looking like this:

![screen shot 2017-01-02 at 11 06 57 am](https://cloud.githubusercontent.com/assets/2223916/21594813/e8e7f716-d0db-11e6-8a67-02e90a5d3403.png)

**Comment by tlrobinson** [comment]
Definitely not intentional but probably due to the padding thing we talked about. Should be pretty easy to resolve.

**Comment by tlrobinson** [comment]
Also should we prevent tokens (at least the fields/blue ones, aggregations can be pretty long) from wrapping?

**Comment by mazameli** [comment]
Cool. And yes, not wrapping field tokens does sound preferable to me.

**Comment by flamber** [comment]
Fixed in 0.35:
![image](https://user-images.githubusercontent.com/1447303/82845335-686e1b80-9ee4-11ea-81f0-1bdeaf3bb818.png)
