### ISSUE TITLE
Standalone jar 0.49 version SQL editor broken visually

### ISSUE THREAD

**Issue by wkvolkman** [metabase/metabase#40481]
### Describe the bug

Every time I go into the SQL editor the cursor position is no where near the text being edited.  I would guess that the text pane is using a proportional font and the editor is expecting to position by a fixed width font. Notice the cursor mark to the far right from where I added the text.
<img width="1251" alt="Screenshot 2024-03-21 at 4 35 04 PM" src="https://github.com/metabase/metabase/assets/36056663/97d51b6c-8880-48a0-b81d-25c0254f816c">

### To Reproduce

1. Using standalone .jar file for 0.49
2. Open query and edit with SQL editor
3. Click anywhere in the text of the query and start typing, it will show up in the wrong position in the text.
4. Thanks for using Metabase!
You're on version v0.49.0
Built on 2024-03-14

### Expected behavior

Editor position visually should be next to the text being edited.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7-LTS",
    "os.name": "Linux",
    "os.version": "6.1.79-99.164.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

High blocking all users of SQL queries

### Additional context

I'm trying to show this to a client for them to consider using however running into things that make this an annoyance to try to actually use.  We have a real copy of production data to develop against.  The popup to "Click here to be notified..." is a given, any query takes one minute and 17 seconds as there are 1.52 billion records in the table.  Greenplum database is working just fine at 9.1 million records/second, would like to put a pretty UI on it and am evaluating Metabase.

**Comment by wkvolkman** [comment]
The editor has this as it's font choices:
font: 12px/normal 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'Source Code Pro', 'source-code-pro', monospace;
None of those were available on CentOS 7, I installed the source-code-pro one and it seemed to get corrected.
Your textarea has a font_size: 1px which seems to be incorrect and would be a problem with people who cannot use small fonts, I certainly find the font size in the editor too small.  Make your web designer stand at least 4' away from the screen to see it it's readable.

**Comment by wkvolkman** [comment]
Oh, FYI, I had also tried to look at it on a Macbook Pro and it had the same issue, that font list does not appears to be a good default.

**Comment by wkvolkman** [comment]
So on the .ace_editor class I would want a 16px font however a 14kpx font looks ok, the 12px is too small.  And shouldn't that be "pt".

**Comment by wkvolkman** [comment]
Yep, this looks much better, and with "pt" instead of "px" it's display independent:
12pt/normal 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'Source Code Pro', 'source-code-pro', monospace

**Comment by paoliniluis** [comment]
So it was because of fonts not installed in the operating system?

**Comment by wkvolkman** [comment]
The font list provided is Windows and Apple specific with some allowance for Ubuntu, Linux Redhat will not have those fonts.  The Source Code Pro fonts are Adobe proprietary though free for use, not installed by default.   The aren't OS specific per se however do have to be available.

**Comment by wkvolkman** [comment]
I am curious why the Apple font, Menlo didn't seem to work on Apple, they may have shifted as they like to keep people guessing as to what is compatible.
