### ISSUE TITLE
Changing the timezone in a Read-Only Database puts month aggregated one month behind

### ISSUE THREAD

**Issue by neoecos** [metabase/metabase#4048]
Setting the metabase timezone allow us to query in our local time, and all the times in th db are saved using GMT 0 timezone.

When I change the time zone in metabase and do a group by month query, all data is presented one moth behind, for example if octubter 2016 the sum of sales where $100.000, it shows the $100.000 as it where in september.

When i disable the selection of the timezone the information is reported well.

Please note that *the database i'm querying is read-only and if i check the logs, always there is an error when metabase tries to set a different timezone.*

- Chrome v55
- Ubuntu 15.10 x64
- PostgreSQL 9.3, Read-only replica
- Metabase version: 0.21.1 (from docker image)
- Docker hosted in ElasticBeansTalk
- Metabase internal database: H2 (default)

**Comment by camsaul** [comment]
@neoecos what format are the dates stored in, and what timezone are you setting? Things that happen in October in GMT could happen in September of a different month if you're in a timezone east of GMT

**Comment by neoecos** [comment]
Hi @camsaul, the dates are stored in timestamp, the timezone is UTC. I understand about what your referer of dates, but the issue is totally different.

If i don't change the timezone in metabase, let's the sum of all amount, aggregated by month of September is 0, October is 100.000, and November 50.000 which is true, but if i change the timezone and do the same query, the sum of a amounts aggregated by month of August is 0, September is 100.000, October 50.000.

You see, is when i use aggregated functions on the month.

**Comment by camsaul** [comment]
This sounds like the same underlying issue as #1699 (setting timezones fails in a read-only postgres connection) so I'm going to go ahead and close this as a duplicate. A fix for this is shipping as part of our upcoming release 0.24 which we're planning on shipping in the next week or so.

@neoecos after 0.24 ships feel free to reöpen this issue if you're still running into problems.

**Comment by salsakran** [comment]
Huh? I'm not sure I follow @camsaul

**Comment by salsakran** [comment]
#1699 throws an error, but what's being described here is the timezone change actually working and resulting in numbers that seem off.

**Comment by camsaul** [comment]
An error is thrown here too:

> Please note that the database i'm querying is read-only and if i check the logs, always there is an error when metabase tries to set a different timezone.

There's no way the timezone change was actually working. So it sounds like the timezones are off because the DB is in a different timezone than the server:

> Setting the metabase timezone allow us to query in our local time, and all the times in th db are saved using GMT 0 timezone.

Because setting the timezone failed, instead of running queries using the local timezone, the database is using GMT, which explains the bucketing discrepancies

**Comment by salsakran** [comment]
Ahhhh.

**Comment by neoecos** [comment]
Hi guys, did it  understand if is now fixed ? Please say yes! Thx.

**Comment by camsaul** [comment]
> A fix for this is shipping as part of our upcoming release 0.24 which we're planning on shipping in the next week or so.
