### ISSUE TITLE
Date Filtering Bug in v0.49.1 Docker Image with Japanese Locale Settings

### ISSUE THREAD

**Issue by bell851** [metabase/metabase#40493]
### Describe the bug

A bug occurs in both the v0.49.0 and v0.49.1 Docker images uploaded to DockerHub when the language setting is switched to Japanese. Specifically, when filtering datetime columns by specifying an exact date, the filter incorrectly applies the date subtracted by 2018 years from the chosen date. This issue has been confirmed not to occur in version v0.48.8. Additionally, the bug does not manifest when the language settings are set to English, Chinese, or Korean.

When a date is selected like this:
<img width="250" alt="image" src="https://github.com/metabase/metabase/assets/54491901/ccfd3a63-43d7-4218-a88b-e6eac3670b9f">

The filter incorrectly applies a date subtracted by 2018 years as shown below:
<img width="250" alt="image" src="https://github.com/metabase/metabase/assets/54491901/9c1292ed-7876-4777-931a-1bd4ddc96ec7">

### To Reproduce

1. Use the v0.49.1 image from DockerHub.
2. Change language settings to Japanese.
3. Attempt to filter a datetime column by specifying an exact date.
4. Notice that the applied filter date is 2018 years less than the specified date.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ja-JP",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.210-201.852.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.35"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v0.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2 - High: Critically blocks data analysis for all Japanese locale users by improperly applying date filters.

**Comment by paoliniluis** [comment]
whoa, sorry about that

**Comment by zbodi74** [comment]
Filtering using a date range is also affected.

**Comment by lbrdnk** [comment]
It seem as FE issue. The `metabase.lib.fe-util/expression-clause` gets year already shifted.
