### ISSUE TITLE
Multiply a negative number by 0.0001, and the display becomes as if multiplied by 0.00000001

### ISSUE THREAD

**Issue by TurboWay** [metabase/metabase#40490]
### Describe the bug

In a bar chart or waterfall chart, when displaying a negative number, if it is formatted, such as multiplying by 0.0001, this operation is performed twice, and the displayed value will appear as if multiplied by 0.00000001.
![image](https://github.com/metabase/metabase/assets/23210408/66430d44-c457-47a8-afd5-caac2d701c84)

### To Reproduce

In a bar chart or waterfall chart, when displaying a negative number, if it is formatted, such as multiplying by 0.0001, this operation is performed twice, and the displayed value will appear as if multiplied by 0.00000001.

### Information about your Metabase installation

```JSON
database: mysql、doris
metabase version: v0.49.1
```

### Severity

annoying

**Comment by JesseSDevaney** [comment]
Could not reproduce in 50, but found another bug related to the difference between data label values and tool-tip values.
- https://github.com/metabase/metabase/issues/44176

Will create a separate PR targeting just the v49 branch to fix this behavior.
