### ISSUE TITLE
Sort official collections above regular collections

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#40510]
<img width="317" alt="image" src="https://github.com/metabase/metabase/assets/6377293/62681323-d95f-4177-bf09-9e7f6607366e">

The request is to put all official collections above unofficial collections, as returned from the backend.

Max is using a hack of prepending a "z_" to collection names to enforce this sorting and had a sensible idea that we could just naturally sort like this.

**Comment by johnswanson** [comment]
Resolved by https://github.com/metabase/metabase/pull/40598
