### ISSUE TITLE
Creating a new native query inserts 3 newlines in sql editor

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#40538]
### Describe the bug

Click on "New > SQL query"

<img width="262" alt="image" src="https://github.com/metabase/metabase/assets/6377293/1685149f-5c64-4bd9-824f-05f277184c1e">

The cursor appears at the top of the text input. Start typing "select" and three new lines will be inserted
![image](https://github.com/metabase/metabase/assets/6377293/bb56886b-53e8-474a-b552-835663d557a8)

Seems to only manifest in Firefox and not chrome

### To Reproduce

stated above

### Expected behavior

no unintentional newlines

### Information about your Metabase installation

```JSON
master
```

### Severity

p3

**Comment by romeovs** [comment]
This was caused by the [upgrade to react 18](https://github.com/metabase/metabase/pull/41975), good thing the [fix was easy](https://github.com/metabase/metabase/pull/45129).
