### ISSUE TITLE
[dc.js migration] tooltip double renders on hover

### ISSUE THREAD

**Issue by JesseSDevaney** [metabase/metabase#40532]
https://github.com/metabase/metabase/assets/22608765/bf848bd6-bb1c-4f1e-884f-486d7f7eb459

**Comment by JesseSDevaney** [comment]
Attempted this, but could not find a solution in a reasonable time.

---
**To summarize:**

When hovering over the outer edge of a point, it sometimes makes the `target` of the event, the series line instead of the data point even though it is still passing the data of the point itself. 

This causes the tooltip to be rendered on top of the box containing the series line instead of the data point itself. 

If you then move closer to the data point, it will re-render on top of the data point because the new target is now the data point itself.

**Comment by EmmadUsmani** [comment]
@alxnddr Fixed this once before https://github.com/metabase/metabase/issues/39408
