### ISSUE TITLE
Migrate H2 metabase docker compose

### ISSUE THREAD

**Issue by XaviG99** [metabase/metabase#40558]
Im trying to swap the H2 database to my postgresql database. Im trying to implement it trough docker compose but i have already switched the h2 database so i dont know if there is any option to do it by docker compose.

There is the code: (the line 'command' were just a new implementation i were trying to improve).
services:
  frontend:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=postgres
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=mypass
      - MB_DB_HOST=backend
    
    command: exec su metabase -s /bin/sh -c "exec java $JAVA_OPTS -jar /app/metabase.jar $@"

  backend:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypass
    volumes:
      - pgdata:/var/lib/postgresql/data

  
volumes:
  pgdata:

- issue links: _related issues if any_

**Comment by darksciencebase** [comment]
@XaviG99 hi there! the `.Task` label is for internal use. if you don't have a bug to report, please use [our forum](https://discourse.metabase.com/) or contact support in case you're a customer.
