### ISSUE TITLE
Hitting back after creating a collection should return you to `questions/all`

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4055]
When you hit back after creating a collection, you get to the creation form.

This makes a common flow (create a collection, go back to the full list and add questions to it) a little wonky.

**Comment by tlrobinson** [comment]
I agree this doesn't make sense.

Do we want the back button in all `/questions/*` pages to always go back to `/questions`? I think I had it use the browser's `window.history.back` due to some other case I can't recall. It's a bit confusing having a back button that may or may not take you back to where you came from, but I guess we should at least make it consistent.

**Comment by salsakran** [comment]
Not sure that makes sense in every situation. I think the problem is more with how the form is treated in history and not so much the `/questions/*` state.

@mazameli @kdoh , any thoughts on how the back button should work with regard to forms?

**Comment by mazameli** [comment]
I had really conceptualized the in-app "back" or left-arrow button as primarily being a way to get back to the Questions page, and so I agree that I'd never expect it to take me back to a form. 

But like Sameer said, there are some weird cases that make me uncertain that the left arrow button should always go to `/questions`, such as if you click on the collection label from a question detail screen. I think in that case you'd expect it to take you back to the question you were viewing (which is the current behavior). 

This is making me wonder whether the left-arrow button is really working for us in its current form. I'm trying to think if there's a way to tweak its appearance to better communicate that it goes to `All Collections` (e.g. a breadcrumb style link or something).

We could also remove the button altogether; you can use the browser's back button to go back, and you can get back to the All Collections view just by clicking Questions in the main nav. I think that would feel slightly disconnected to me, but it might be cleaner.

**Comment by salsakran** [comment]
I'd propose not including the form in the history as an alternative. Eg "actions" like editing or creating a collection are not places you can go "back" to as they've either been submitted or canceled.

**Comment by salsakran** [comment]
closed via #4069
