### ISSUE TITLE
Common Metrics gone after Summarising by some other column

### ISSUE THREAD

**Issue by cgg-pwdt** [metabase/metabase#40553]
### Describe the bug

NOTE: this issue is duplicated from [link](https://github.com/metabase/metabase/issues/40393). I'm afraid I used the wrong method to raise the issue and it didn't had bug type tag. Apologies for the spam.

When creating a Metabase question, selecting a **Common Metric** and creating a summary, we lose the Common Metrics group. Moreover, if we pick the initial Common Metric added, Metabase shows a error message. The console log displays a "metric with id xx not found" issue.

We've recorded the following Loom to show the issue: 
[loom](https://www.loom.com/share/a3775a517dc3402ba4e37bd1e4e7fdb0?sid=b196bff3-b455-40dc-8348-a94d9b3663b6)

If we pick all the Common Metrics we are summarizing and then the Dimensions, Metabase outputs the result properly. However, we lose the ability to edit the question.

### To Reproduce

1. Go to 'New > Question' 
2. Click on 'Pick the metric you want to summarize' add any *Common Metric* 
3. Summarize by some other column
4. Go back to metrics
5. Common Metrics are not there.
6. If you click on the initial metric selected, metabase outputs an error.

### Expected behavior

Common metrics should not disappear.

### Logs

Logs
metric with ID does not exist : 32 > react-dom.prodcution.min.js:209
Error app.ts:30

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.205-195.804.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking significant part of the metabase usage 

### Additional context

![image](https://github.com/metabase/metabase/assets/136714486/c3e0ca61-dd25-4951-b124-b6e7de906114)

https://www.loom.com/share/a3775a517dc3402ba4e37bd1e4e7fdb0?sid=b196bff3-b455-40dc-8348-a94d9b3663b6

**Comment by cgg-pwdt** [comment]
thanks everyone! life savers 🚀 

as I mentioned before this was duplicated because I used the wrong form initially. Here's the dupe: https://github.com/metabase/metabase/issues/40393

**Comment by uladzimirdev** [comment]
thanks for the effort on providing clear steps to reproduce the issue @cgg-pwdt
