### ISSUE TITLE
MongoDB - Query failure: Timed out after 3000 ms

### ISSUE THREAD

**Issue by davidmir** [metabase/metabase#4057]
Hi,

Sometimes when I make a query in the Metabase interface I've get the following error:

Query failure: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongo.docker:27019, type=UNKNOWN, state=CONNECTING}]

The stacktrace don't gives me more detail about the error. What can I do to mislead the causes of the problem?

Thanks

**Comment by camsaul** [comment]
That's the error Mongo gives when it's unable to connect to a certain server. Are you sure it's running?

**Comment by davidmir** [comment]
Yes. I'm using the Mongo console.

**Comment by tvacare** [comment]
I'm having the same problem! Exactly the same message. My mongoDB is on amazon AWS

**Comment by anki-code** [comment]
I think it's the same as #2722

**Comment by camsaul** [comment]
Thanks @anki-code, this does look the same underlying issue. Going to close as a duplicate.
