### ISSUE TITLE
Send locale parameter via headers

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#40607]
**Is your feature request related to a problem? Please describe.**
We have a customer that needs to send the locale via headers https://www.metabase.com/docs/latest/embedding/interactive-embedding#locale. We need to accept the parameter via url or via headers

**Describe the solution you'd like**
Accept the locale parameter via a header

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by a customer due to an internal requirement

**Additional context**
NA

**Comment by WiNloSt** [comment]
We implemented `X-Metabase-Locale` in https://github.com/metabase/metabase/pull/12566. Would this work for them?

**Comment by paoliniluis** [comment]
another day, another undocumented secret we find hidden in the depths of the code. Thanks @WiNloSt

**Comment by paoliniluis** [comment]
@jeff-bruemmer FYI, I guess that no one even knew this existed
