### ISSUE TITLE
[dc.js migration] query builder performance slow for certain questions

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#40602]
https://github.com/metabase/metabase/assets/37751258/65e98cb4-b105-4fba-808a-240f811dc996

http://localhost:3000/question/287-bar-stacked-pow-y-axis-poke-avg-of-base-stats-by-gen

In the recording you can see there is no lag on stats, but with echarts there is significant lag when switching to the table view, or opening the notebook editor.

Here is the csv if you need to repro on a different app db

[pokedex.csv](https://github.com/metabase/metabase/files/14748854/pokedex.csv)

**Comment by JesseSDevaney** [comment]
Could not reproduce locally with the same dataset and visualization settings applied.
