### ISSUE TITLE
ERROR: Interval end (763426800000000) must be after last timestamp (763429126166353)

### ISSUE THREAD

**Issue by mattweissstrella** [metabase/metabase#40605]
### Describe the bug

Running a query against our database led to the following error:
ERROR: Interval end (763426800000000) must be after last timestamp (763429126166353)
This query had a datetime column with 1 value per day at midnight each day. Small, seemingly unrelated, modifications to the query would either fix the query or break it again with the same error. After realizing the query always worked outside of metabase, I was able to determine that the issue goes away after turning off a timezone option. US/Pacific would reproduce the issue, UTC would not.

### Expected behavior

Error should not occur.

### Logs

[8bdb4dc8-879f-4a08-8471-5c9f438e6640] 2024-03-25T16:02:05-07:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: ERROR: Interval end (763426800000000) must be after last timestamp (763430024941659)
{:database_id 2,
 :started_at #t "2024-03-25T23:02:04.489120Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query: ERROR: Interval end (763426800000000) must be after last timestamp (763430024941659)",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__77872$fn__77873.invoke(execute.clj:698)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__77872.invoke(execute.clj:695)"
    "driver.sql_jdbc.execute$fn__77665$fn__77666.invoke(execute.clj:388)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
    "driver.sql_jdbc.execute$fn__77665.invokeStatic(execute.clj:382)"
    "driver.sql_jdbc.execute$fn__77665.invoke(execute.clj:380)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:686)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc$fn__111188.invokeStatic(sql_jdbc.clj:82)"
    "driver.sql_jdbc$fn__111188.invoke(sql_jdbc.clj:80)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
    "query_processor.context.default$default_runf.invoke(default.clj:42)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70857.invoke(cache.clj:229)"
    "query_processor.middleware.permissions$check_query_permissions$fn__65066.invoke(permissions.clj:140)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__70678.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__70688.invoke(enterprise.clj:64)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__69925.invoke(mbql_to_native.clj:24)"
    "query_processor$fn__71991$combined_post_process__71996$combined_post_process_STAR___71997.invoke(query_processor.clj:262)"
    "query_processor$fn__71991$combined_pre_process__71992$combined_pre_process_STAR___71993.invoke(query_processor.clj:259)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__65163.invoke(fetch_source_query.clj:303)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__70768$fn__70772.invoke(resolve_database_and_driver.clj:77)"
    "driver$do_with_driver.invokeStatic(driver.clj:94)"
    "driver$do_with_driver.invoke(driver.clj:89)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__70768.invoke(resolve_database_and_driver.clj:76)"
    "query_processor.middleware.store$initialize_store$fn__65555$fn__65556.invoke(store.clj:14)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.middleware.store$initialize_store$fn__65555.invoke(store.clj:13)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__70765.invoke(resolve_database_and_driver.clj:60)"
    "query_processor.middleware.normalize_query$normalize$fn__71070.invoke(normalize_query.clj:38)"
    "query_processor.middleware.enterprise$fn__70705$handle_audit_app_internal_queries__70706$fn__70708.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__70716.invoke(enterprise.clj:103)"
    "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__69640.invoke(constraints.clj:102)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__71001.invoke(process_userland_query.clj:156)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__71591.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___60736$thunk__60738.invoke(reducible.clj:126)"
    "query_processor.reducible$async_qp$qp_STAR___60736.invoke(reducible.clj:132)"
    "query_processor.reducible$sync_qp$qp_STAR___60748.doInvoke(reducible.clj:153)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
    "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
    "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
    "api.dataset$run_query_async$fn__94112.invoke(dataset.clj:79)"
    "query_processor.streaming$streaming_response_STAR_$fn__51589$fn__51591.invoke(streaming.clj:168)"
    "query_processor.streaming$streaming_response_STAR_$fn__51589.invoke(streaming.clj:167)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__42912.invoke(streaming_response.clj:88)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :postgres,
    :sql
    ["-- Metabase:: userID: 3 queryType: native queryHash: 968fa4bf8d6b1b79306a85366153c1c8d5ca7fd79838020b6a736d3791f3bb67"
  [REDACTED],
    :params nil,
    :type :invalid-query}}],
 :action_id nil,
 :state "XX000",
 :error_type :invalid-query,
 :json_query
 {:type "native",
  :native
  {:query
   [REDACTED]
   :template-tags {}},
  :database 2,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)"
  "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)"
  "org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)"
  "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__77791.invokeStatic(execute.clj:560)"
  "driver.sql_jdbc.execute$fn__77791.invoke(execute.clj:558)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:568)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:565)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__77872$fn__77873.invoke(execute.clj:696)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__77872.invoke(execute.clj:695)"
  "driver.sql_jdbc.execute$fn__77665$fn__77666.invoke(execute.clj:388)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
  "driver.sql_jdbc.execute$fn__77665.invokeStatic(execute.clj:382)"
  "driver.sql_jdbc.execute$fn__77665.invoke(execute.clj:380)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:686)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc$fn__111188.invokeStatic(sql_jdbc.clj:82)"
  "driver.sql_jdbc$fn__111188.invoke(sql_jdbc.clj:80)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
  "query_processor.context.default$default_runf.invoke(default.clj:42)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70857.invoke(cache.clj:229)"
  "query_processor.middleware.permissions$check_query_permissions$fn__65066.invoke(permissions.clj:140)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__70678.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__70688.invoke(enterprise.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__69925.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__71991$combined_post_process__71996$combined_post_process_STAR___71997.invoke(query_processor.clj:262)"
  "query_processor$fn__71991$combined_pre_process__71992$combined_pre_process_STAR___71993.invoke(query_processor.clj:259)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__65163.invoke(fetch_source_query.clj:303)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__70768$fn__70772.invoke(resolve_database_and_driver.clj:77)"
  "driver$do_with_driver.invokeStatic(driver.clj:94)"
  "driver$do_with_driver.invoke(driver.clj:89)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__70768.invoke(resolve_database_and_driver.clj:76)"
  "query_processor.middleware.store$initialize_store$fn__65555$fn__65556.invoke(store.clj:14)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.middleware.store$initialize_store$fn__65555.invoke(store.clj:13)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__70765.invoke(resolve_database_and_driver.clj:60)"
  "query_processor.middleware.normalize_query$normalize$fn__71070.invoke(normalize_query.clj:38)"
  "query_processor.middleware.enterprise$fn__70705$handle_audit_app_internal_queries__70706$fn__70708.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__70716.invoke(enterprise.clj:103)"
  "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__69640.invoke(constraints.clj:102)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__71001.invoke(process_userland_query.clj:156)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__71591.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___60736$thunk__60738.invoke(reducible.clj:126)"
  "query_processor.reducible$async_qp$qp_STAR___60736.invoke(reducible.clj:132)"
  "query_processor.reducible$sync_qp$qp_STAR___60748.doInvoke(reducible.clj:153)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
  "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
  "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
  "api.dataset$run_query_async$fn__94112.invoke(dataset.clj:79)"
  "query_processor.streaming$streaming_response_STAR_$fn__51589$fn__51591.invoke(streaming.clj:168)"
  "query_processor.streaming$streaming_response_STAR_$fn__51589.invoke(streaming.clj:167)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__42912.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error "ERROR: Interval end (763426800000000) must be after last timestamp (763430024941659)",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}

### Information about your Metabase installation

```JSON
- Metabase Cloud
https://strella.metabaseapp.com
```

### Severity

Annoying

**Comment by paoliniluis** [comment]
please send us a ticket if you're a cloud customer

**Comment by mattweissstrella** [comment]
> please send us a ticket if you're a cloud customer

@paoliniluis How do I do this? The only link I see in the cloud application takes me here.
