### ISSUE TITLE
Unable to see all labels in pie diagram in Metabase

### ISSUE THREAD

**Issue by akhilasemsani** [metabase/metabase#40617]
### Describe the bug

Unable to see all labels in pie diagram in Metabase
![image](https://github.com/metabase/metabase/assets/165027906/09b962f3-e3ee-4e41-ac6c-60bc974a624a)

In the above image i'm not able to get the percentages for few areas in the pie chart

### To Reproduce

I have written a query to get the list of hours spent on a program, i am listing all the programs available in the database
![image](https://github.com/metabase/metabase/assets/165027906/2c211809-99b2-4637-b4b8-3d92d2b2f103)
The above is my data used to represent the pie diagram

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-22",
      "tag": "v0.48.7",
      "hash": "c192db1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

high

**Comment by paoliniluis** [comment]
Hi, the problem here seems to be that those legends will not fit on the chart, how do you think this should be managed?

**Comment by francisco-mooddie** [comment]
> Hi, the problem here seems to be that those legends will not fit on the chart, how do you think this should be managed?

To resolve this issue, an additional option should be added to the pie chart settings to enable the listing of percentages both on the chart and in the legend.
