### ISSUE TITLE
Scalar view stays after more columns are added to a native query

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#40623]
### Describe the bug

The query results show a nice "scalar" view if you select only a single column. Example `select 'foo'`

<img width="1344" alt="image" src="https://github.com/metabase/metabase/assets/6377293/69350bd9-7c5f-4fbb-8b0d-49815a2bca3f">

If you then extend this same query to `select 'foo', 'bar'` the viz display does not realize it's seeing more than a single column and continues to only show the first column:

<img width="1451" alt="image" src="https://github.com/metabase/metabase/assets/6377293/2be68202-33ed-4db1-b18f-7c3a9f84fd5c">

This is because the display "scalar" has been encoded in the query:

```clojure
;; "#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoibmF0aXZlIiwibmF0aXZlIjp7InF1ZXJ5Ijoic2VsZWN0ICdmb28nLCAnYmFyJyIsInRlbXBsYXRlLXRhZ3MiOnt9fX0sImRpc3BsYXkiOiJzY2FsYXIiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319"


{:dataset_query {:database 2,
                 :type "native",
                 :native {:query "select 'foo', 'bar'",
                          :template-tags {}}},
 :display "scalar",  ;; <----------------
 :parameters [],
 :visualization_settings {}}
```

And reloading the page, sharing the link, etc still exemplifies this bug.

### Expected behavior

A native query selecting a single column and a single row. Then extend to multiple columns and you will only see the first column.

`select email from PEOPLE where id = 1` on sample database. Then `select id, email from PEOPLE where id = 1`

<img width="1451" alt="image" src="https://github.com/metabase/metabase/assets/6377293/0b8bbc48-8b1a-404a-b126-90cc1ab20316">

### Information about your Metabase installation

```JSON
master
```

### Severity

p2

### Additional context

at first thought it was a p1. But since it requires selecting a single column first and then not dropping that it seems not a p1.

**Comment by JesseSDevaney** [comment]
Dropping this for now in favor of higher priority issues. 

Context: https://metaboat.slack.com/archives/C064QMXEV9N/p1718761174731189?thread_ts=1718747924.798209&cid=C064QMXEV9N
