### ISSUE TITLE
Filter modal UI breaks when there are many tables in a question

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#40622]
### Describe the bug

When there are several tables in a question, either via explicit or automatic joins, the table selector in the filter model may overflow, causing the elements that don't fit to spill into a second column, which breaks the UI.

### To Reproduce

1. Go to Table Metadata, Sample Database, rename Reviews to 'Reviews, but a very long name' 
2. Create a GUI question, Reviews inner join Orders
3. Click on Visualize
4. Click on Filter
5. Resize the browser so that there is less vertical space, and see the error:

<img width="828" alt="image" src="https://github.com/metabase/metabase/assets/11080638/a4e914bc-57d1-48eb-9e66-821ca0af3acb">

### Expected behavior

The table selector should be vertically scrollable?

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.1.75-0-virt",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v1.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Reported by a customer

**Comment by kamilmielnik** [comment]
Closed by #45352 + #45363
