### ISSUE TITLE
Shortcut to open code editor

### ISSUE THREAD

**Issue by OdinTallBeard** [metabase/metabase#40634]
**Is your feature request related to a problem? Please describe.**
Its very annoying to have to click the tiny 'open editor' button everytime. 

**Describe the solution you'd like**
Please add the same quick button you have to open the side bar (Cmd + .) to open the code editor.

Allow you to open and close the code editor easily.

View graph, then instantly see code.

**Describe alternatives you've considered**
Please please 

**How important is this feature to you?**
10 / 10 convenience and seamlessness to product

**Additional context**
please

**Comment by OdinTallBeard** [comment]
I think [ Cmd + ; ] would be a good input

**Comment by ignacio-mb** [comment]
Dupe of https://github.com/metabase/metabase/issues/38687. Fyi, this is coming very soon

**Comment by OdinTallBeard** [comment]
Hi this has still not happened yet

**Comment by OdinTallBeard** [comment]
please put this in this would be great for seamlessness
