### ISSUE TITLE
Progress visualisation not working, gives an error

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#40658]
### Describe the bug

I create a simple question returning a single count value, this previews in the notebook mode, and displays a number correctly when visualised. When I change it to a Progress visualisation I get the exclamation mark displayed instead. I then can't change back to a number or table, I need to refresh or start a new question.

### To Reproduce

1. Create a new question
2. Sample Database > Accounts
3. Count of rows
![image](https://github.com/metabase/metabase/assets/4504437/29adfe48-69ae-4e2b-9761-4453fcc8172e)
4. Visualise, Number is presented as expected
![image](https://github.com/metabase/metabase/assets/4504437/fa56011d-8cc2-4833-9d61-d7659d902cca)
5. Change the visualisation type to "Progress", error occurs
![image](https://github.com/metabase/metabase/assets/4504437/02c2a2d7-17cc-459f-a853-9174a7640e2e)
6. Can't change to any other type of visualisation, need to restart
7. Can't use the data/visualisation slider to view the raw data either

### Expected behavior

Progress chart to be displayed and I can continue to work on the question.

### Logs

JavaScript console:
```
TypeError: Cannot read properties of undefined (reading 'height')
    at oy.componentDidUpdate (Progress.jsx:100:39)
    at oy.componentDidMount (Progress.jsx:86:10)
    at react-dom.production.min.js:212:132
    at a$ (react-dom.production.min.js:213:322)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at on (react-dom.production.min.js:122:325)
    at aX (react-dom.production.min.js:248:370)
    at aW (react-dom.production.min.js:239:376)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v0.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

### Severity

Can't create progress bars at all. We don't use them much so not a big issue for me.

### Additional context

Also and issue in Firefox.

I don't get this on v0.48.6, progress bars are working as expected.

**Comment by paoliniluis** [comment]
Lowering to p2

**Comment by NicolasPA** [comment]
I confirm this issue and the fact that it still renders in dashboard on v0.49.2.
