### ISSUE TITLE
the move to collection modal renders the collection list unreliably depending on scroll position when triggered.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#4068]
When trying to move a question into a collection from the "Everything else" list, depending on where the question is in the list and how many collections you have, the list of collections is never centered in the modal.

Example:

Attempting to move the 1st question in the list in Chrome:
![screen shot 2017-01-04 at 10 57 27 am](https://cloud.githubusercontent.com/assets/5248953/21655068/3934eb74-d26d-11e6-99a3-32d5e0fd5438.png)

Attempting to move the last (of 5 questions) into a collection in Chrome:
![screen shot 2017-01-04 at 10 57 34 am](https://cloud.githubusercontent.com/assets/5248953/21655077/53ecbbae-d26d-11e6-8040-59d028e90ab2.png)

Running into this on the `release-0.22.0` branch.

Safari does a similar but slightly different behavior. The position in the list doesn't matter and you always get a slightly off screen list unless it's the first question.
![screen shot 2017-01-04 at 11 03 36 am](https://cloud.githubusercontent.com/assets/5248953/21655115/784194e8-d26d-11e6-9280-06dc80a4f151.png)

**Comment by salsakran** [comment]
closed via #4069
