### ISSUE TITLE
Visualization differs after converting question with aggregation and breakout to SQL

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#40711]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/f7227e23-314e-4f23-9db8-03f7b066aa9f

### To Reproduce

1. Start a new question based on Orders table from Sample DB
2. Summarize "Cumulative count of rows" by "Created At: Month"
3. Visualize it, remember the shape of the chart
4. Go back to notebook editor
5. Convert this question to SQL
6. Visualize it

### Expected behavior

Visualization should look the same as before converting the question to SQL

### Information about your Metabase installation

master, 7efd8d3627

### Severity

P2

**Comment by darksciencebase** [comment]
(rerouting; [thread](https://metaboat.slack.com/archives/C0641E4PB9B/p1711613293992959))
