### ISSUE TITLE
[49.1] impossible to filter on IDs identified as Identity key (PK)

### ISSUE THREAD

**Issue by kevbarns** [metabase/metabase#40770]
### Describe the bug

impossible to filter on IDs identified as Identity key (PK)
![image](https://github.com/metabase/metabase/assets/22106329/0be9f5c8-e6dc-485b-9063-b7e99105d288)

### To Reproduce

1. Go to a collection with a field set as Primary key by Metabase discovery
2. Click on filters
3. Scroll down to ID

### Expected behavior

Filtering on IDs should be possible

### Information about your Metabase installation

```JSON
image: metabase/metabase:v0.49.1
MB_DB_TYPE: mysql
```

### Severity

Low

**Comment by ranquild** [comment]
@kevbarns what is the database type for these columns?

**Comment by kevbarns** [comment]
@ranquild it's a mongoDB database

**Comment by paoliniluis** [comment]
is the Id an UUID right?

**Comment by paoliniluis** [comment]
probably the same as https://github.com/metabase/metabase/issues/40176?

**Comment by uladzimirdev** [comment]
Hey @kevbarns. FYI #40176 is fixed, but you'll need to wait for 0.49.3 to be released. Feel free to reopen this issue with more details if it's still an issue in 0.49.3

**Comment by kevbarns** [comment]
hello @uladzimirdev , after updating to 0.49.5 I'm still having the issue.

**Comment by uladzimirdev** [comment]
@kevbarns it would be helpful if you could record a small repro video as we have a test for initial problem and it passes, we might miss something specific in your case

**Comment by kevbarns** [comment]
hello @uladzimirdev, here is a loom video : https://www.loom.com/share/1e446df025a041e39420bc50d0ae77e5?sid=941cb337-4ab8-418b-a9d7-933d92c6a0c7
- When visualizing a dataset, clicking on the field arrow set as Primary key by metabase discovery, filter button does not work
- When visualizing a dataset, clicking on the filter button with the list of fields available, the field set as Primary key cannot be filtered (as shown in my screenshot above).

**Comment by kevbarns** [comment]
@uladzimirdev is there a documentation/scripts available to rollback from `0.49.5` to `0.47.8` ? We also notice discrepancies with number when looked at from different filter settings.

**Comment by paoliniluis** [comment]
@kevbarns you need to move to the latest version first and then do a "migrate down" https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase
