### ISSUE TITLE
Better KeepAlive timeout handling

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4077]
Doing a bit of digging on the KeepAlive interval mentioned in http://discourse.metabase.com/t/is-the-db-keepalive-configurable/977. Found a bit of info at http://www.mchange.com/projects/c3p0/#configuring_connection_testing

I think there are some improvements to be had in how we deal with connection timeouts. 

First off, we should probably reset the connection and retry the query on the `Communications link failure` error noted in http://discourse.metabase.com/t/database-connection-keep-alive/181.

Second, we could potentially replace the default C3P0 connection test of `DatabaseMetaData.getTables()` to a `SELECT 1` and decrease the interval from 3 minutes to something smaller. 

Of the two, I think the first is more important.

**Comment by camsaul** [comment]
I added connection testing in #11086
