### ISSUE TITLE
Font size for "New question" title is different from size of saved question titles

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4080]
Just seems odd to me. I'd prefer if we changed the larger saved question titles to the smaller "New question" size:

<img width="399" alt="screen shot 2017-01-05 at 10 59 28 am" src="https://cloud.githubusercontent.com/assets/2223916/21693565/42436cb2-d336-11e6-8c5c-a59a51ffb011.png">

<img width="410" alt="screen shot 2017-01-05 at 10 59 35 am" src="https://cloud.githubusercontent.com/assets/2223916/21693569/45155bda-d336-11e6-9cae-ce840f5740ee.png">

**Comment by flamber** [comment]
Hi @mazameli 
I cannot reproduce this anymore. Not sure when it was fixed. Both are `.Header-title-name > 1.24em`.
![image](https://user-images.githubusercontent.com/1447303/52671796-b0c91c00-2ee1-11e9-9cb5-8900d487b34b.png)
![image](https://user-images.githubusercontent.com/1447303/52671851-d0f8db00-2ee1-11e9-9c88-071b1b65a24d.png)
