### ISSUE TITLE
Public dashboards no longer allow titled=false in url parameters (only allows true)

### ISSUE THREAD

**Issue by bharlettvista** [metabase/metabase#40815]
### Describe the bug

example:
https://metabase.company.com/public/dashboard/32c37b38-318a-4321-b142-99098kii89#theme=transparent&bordered=false&titled=false <- will load the page but the data will never populate, just spinning loader for every widget.

https://metabase.company.com/public/dashboard/32c37b38-318a-4321-b142-99098kii89#theme=transparent&bordered=false&titled=true <- everything loads just as it should except now has ugly title on the page.

this is happening directly after upgrading to v0.49.2 from v0.49.1

this seems to only apply to the title parameter, all the other params seem to still works as normal.

example:
#theme=transparent&bordered=false&titled=false <- FAILS
#theme=transparent&bordered=false&titled=true <- WORKS
#theme=transparent&bordered=false <-WORKS
#theme=transparent&bordered=true <- WORKS
#titled=false <-FAILS
#titled=true <- WORKS

### To Reproduce

happens when sharing any dashboard and attempting to hide the title of the dashboard by embedding via simple iframe or directly accessing the shared url with the parameters set as follows:
#theme=transparent&bordered=false&titled=false

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7-post-Ubuntu-0ubuntu222.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7-post-Ubuntu-0ubuntu222.04.1",
    "os.name": "Linux",
    "os.version": "5.15.0-92-generic",
    "user.language": "en",
    "user.timezone": "America/Detroit"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.11.6-MariaDB-1:10.11.6+maria~ubu2204"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v0.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

High / Breaking

**Comment by bharlettvista** [comment]
Hi!,

the only parameters we are passing are: #theme=transparent&bordered=false&titled=false
when titled=false is passed, the widgets are loaded but there is no data just the loading spinner forever

its strange, when we pass the titled=false param there are no console errors, but also there are less 'files' pulled in via the (shrome dev console) Networking page....

example Networking tab when titled=false:
![Screenshot 2024-03-29 at 12 52 24 PM](https://github.com/metabase/metabase/assets/97744345/d9b16d0b-640d-4f17-a4f5-e0e4fbbc844d)

example Netwokring tab when titled is not passed in the URL, and all the data loads properly:
![Screenshot 2024-03-29 at 12 53 39 PM](https://github.com/metabase/metabase/assets/97744345/4858ad65-99e1-4e33-944b-e6ebb4899fdb)

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/pull/40836
