### ISSUE TITLE
上传csv文件报错

### ISSUE THREAD

**Issue by Memory5210** [metabase/metabase#40831]
在执行写入查询时出错。(conn=4749) Identifier name '%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD_%EF%BF%BD%EF%BF%BD%C5%80' is too long

**Comment by paoliniluis** [comment]
Change the name of the CSV file to something shorter and try again. I think this is due to the encodings. Can you share the name of your CSV file?

**Comment by Memory5210** [comment]
> Change the name of the CSV file to something shorter and try again. I think this is due to the encodings. Can you share the name of your CSV file?

The file names are ces.csv and ce.csv, just for testing functionality.I also think it's a encoding issue, but I don't know where to set it up.

**Comment by Memory5210** [comment]
The downloaded CSV file in Chinese is also garbled due to the encoding format, but I don't know how to modify its default settings

**Comment by paoliniluis** [comment]
duplicate of https://github.com/metabase/metabase/issues/45689
