### ISSUE TITLE
Named aggregations in BigQuery can't have spaces/special characters 

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4087]
Trying to name an aggregation "hello world" results in this error:

> Invalid field name "hello world". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 128 characters long.

**Comment by camsaul** [comment]
This is sort of a BigQuery limitation the only thing I guess we could do here would be to automatically convert names BigQuery doesn't like (e.g. `2016 sales report!`) to ones it does (`____sales_report_`?). Or maybe it makes more sense to validate this on the frontend and have people pick a valid name so we don't end up with weird corrected names that are missing important info (`2016` in the example above)

**Comment by VikramTiwari** [comment]
I think BigQuery is fine with numbers, so no need to replace `2016` with `_` in above example.

Also, if the name is modified during query run, then once the query returns the result, it should miss association with the datatype. Not sure if this will be a modification on driver level or frontend. But validation in frontend does not sound great.

Quoting zen guide: Go extra mile for end user. The end user doesn't care if BigQuery can't take spaces.

**Comment by camsaul** [comment]
@VikramTiwari we're going to address this, we're just deciding how 😉 

From the error message above:

| Fields must [...] start with a letter or underscore

So a field named `2016 sales report` wouldn't work.

**Comment by camsaul** [comment]
Fixed by #4707
