### ISSUE TITLE
Highlighting specific pins in a pin map based on a categorical column.

### ISSUE THREAD

**Issue by MickyKohoOC** [metabase/metabase#40886]
Problem of pin maps have limited additional functionality beyond marking strictly latitude and longitude coordinates.  Other information that would be useful to be able to highlight in a pin map is the different locations of pinned entities that fall under different categories. Highlighting could be done either by a transparency value for the pin or more useful for non-binary categories by different colors with an added legend.

Alternative I use now is creating custom SQL questions with parameter filters to only show pins of entities that match the selected category in the filter but this does not show the entire map as a full perspective.  Additionally does not work as well when selecting multiple values of the parameter to get an intuitive understanding of the visual without another method of differentiating pins.

**Comment by paoliniluis** [comment]
I think that this falls under https://github.com/metabase/metabase/issues/5973, is that correct?
