### ISSUE TITLE
Custom column to compare temporal to nulls is deleted from the notebook

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#40883]
### Describe the bug

Interesting bug where we seem to fail when trying to build a column with a case statement trying to compare against null temporals

### To Reproduce

1) grab the postgres sample dataset and set to null a few dates in the orders table so you have data to play with
2) new->question-> do a custom column in the orders table that's: `case(isempty([Created At]), 1, 0)`
3) see that as soon as you click on accept the column is deleted, but it's still on the sql of the question
4) click on visualize
5) go back to the notebook, the column dissapeared

### Expected behavior

There's clearly some FE bug there, column should still be there

### Logs

no logs

### Information about your Metabase installation

```JSON
v49?
```

### Severity

P2, only because it won't crash everything like in SQL Server

### Additional context

NA

**Comment by lbrdnk** [comment]
Fixed by https://github.com/metabase/metabase/pull/40957
