### ISSUE TITLE
Exporting the date as JSON now involves a new format instead of a timestamp

### ISSUE THREAD

**Issue by vipera7** [metabase/metabase#40881]
### Describe the bug

Previously, when I downloaded my report in JSON format, I received a Unix timestamp in milliseconds. Now, the format I receive is like this: `1 April, 2024, 03:48`

### To Reproduce

1. Utilize the provided API endpoint: http://localhost:3000/api/card/123/query/json to fetch data, ensuring that there is at least one column containing date information.
2. The retrieved date is formatted.

### Expected behavior

The expected behavior is to extract the date with millisecond precision, as was the case previously.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.4.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.4.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.4.1+1",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.36"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-28",
      "tag": "v0.49.2",
      "hash": "4b83b88"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

### Severity

The severity is very high, as there are post-processing scenarios that I have previously worked with based on the previous format.

### Additional context

{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.4.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.4.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.4.1+1",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.36"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-28",
      "tag": "v0.49.2",
      "hash": "4b83b88"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}

**Comment by paoliniluis** [comment]
We're fixing this in 49.3/49.4. We'll offer the options to export with and without formatting
