### ISSUE TITLE
[MBQL lib] Add join to suggestedJoinConditions

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#40916]
Blocks https://github.com/metabase/metabase/pull/40891

Currently `suggestedJoinConditions` was made to work only for new join clauses. When we start to modify the rhs table for existing join clauses, it will return join conditions based on the columns from the same join clause that we want to replace, which results in a broken query. Suggested fix is to pass an optional `join` to `suggestedJoinConditions`. `suggestedJoinConditions` should ignore all join clauses in the referenced stage of the query with the same `join` or after it.

**Comment by bshepherdson** [comment]
Making progress on this, but it's not ready for review yet.

I think it's actually practical to look at the `joinable` parameter itself - if it's a join that already exists on the query, then we can figure out its position and make sure any suggestions are only using earlier joins.

**Comment by ranquild** [comment]
@bshepherdson `suggestedJoinConditions` is called like `suggestedJoinConditions(query, stageIndex, rhsTable)` where `rhsTable` is `joinable`; it won't be possible to compute the correct list only based on that. Instead of `joinPosition` I can pass the join clause itself. Wdyt?

**Comment by bshepherdson** [comment]
Ah, yeah, that's a good point. If you've got the position handy, that's easier to work with, so let's plan for
`suggestedJoinConditions(query, stageIndex, newRhsTable, position)`, with position optional.
