### ISSUE TITLE
Downloading results of an embedded question (via iframe) fails because of "Unknown parameter :format_rows"

### ISSUE THREAD

**Issue by dbbert** [metabase/metabase#40959]
**Describe the bug**
Since yesterday, when clicking the "Download full results" download button in the bottom right of an iframe-embedded question, it makes a network request to `https://my-metabase.com/api/embed/card/xxxxxxx/query/xlsx?format_rows=false`.
This then downloads a file which just contains the text `Unknown parameter :format_rows.` 

**Expected behavior**
If I copy the download link and remove the `?format_rows=false` query parameter, the file gets downloaded correctly, as expected. I have no idea though why this query parameter is now suddenly being added to the download URL.

**The downloaded file**
[query_result_2024-04-03T13_45_03.806Z.xlsx](https://github.com/metabase/metabase/files/14853439/query_result_2024-04-03T13_45_03.806Z.xlsx)

**Severity**
The issue is pretty annoying, as we have customers who download a daily Excel report from our dashboards and now they're blocked in doing so.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.210-201.855.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.13 (Ubuntu 13.13-1.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-02",
      "tag": "v0.49.3",
      "hash": "dba0992"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by dbbert** [comment]
Is it possible we have something misconfigured on our end? I'm suprised this isn't a more popular issue impacting almost everyone.

**Comment by jmm312** [comment]
I have the same issue. I had to downgrade to v0.49.0 to get it to work.

**Comment by kuesley** [comment]
I have the same issue. I downgrade too

**Comment by juheok** [comment]
Same issue. We downgraded from 0.49.3 to 0.49.0 too.

**Comment by dbbert** [comment]
When downgrading, did you restore a previous database backup or is that not needed?

**Comment by kuesley** [comment]
> When downgrading, did you restore a previous database backup or is that not needed?

is not necessary
