### ISSUE TITLE
Scatter plot icon is tiny compared to others

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4099]
It should take up roughly the same amount of space as the others. 

Incidentally, I just noticed in this screenshot that the label for pie chart reads `PieChart`. It's missing a space.

![screen shot 2017-01-09 at 10 51 18 am](https://cloud.githubusercontent.com/assets/2223916/21778768/9c063f56-d659-11e6-8274-46f85be1e066.png)

**Comment by tlrobinson** [comment]
@mazameli the 2nd part is due to #4084 and should be fixed

**Comment by tlrobinson** [comment]
Is this on master or release-0.22.0?

**Comment by mazameli** [comment]
Master

**Comment by tlrobinson** [comment]
I'll need you or @kdoh to re-export the bubble/scatter icon, I think it was missed when we updated the rest. 

I'm not setting the `PieChart` issue on master. If you're looking at stats I think the last build failed so it's out of date.

**Comment by tlrobinson** [comment]
The "Add Series" icon also got borked ![screenshot 2017-01-09 14 24 26](https://cloud.githubusercontent.com/assets/18193/21786124/5f87c1c6-d677-11e6-8151-e0baaf8a0988.png)
