### ISSUE TITLE
Pie chart disappears once you add filter

### ISSUE THREAD

**Issue by dahyeik** [metabase/metabase#41059]
### Describe the bug

If you create a new question, switch the visualization type to a pie chart, add a new filter to the pie chart, and then click 'visualize', the pie chart will disappear and you'll only see the legend on the side. Refreshing the chart won't resolve the issue; it only reappears when you resize the window.

Context: https://metaboat.slack.com/archives/C01LQQ2UW03/p1712261043955499

### To Reproduce

1. Create a question
2. Change the viz type to pie chart
3. Hit the editor button
4. Add an additional filter
5. Hit visualize
See pie chart disappear

### Expected behavior

It should just work - without resizing windows. 

### Information about your Metabase installation

```JSON
stats
```

### Severity

  P3

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/42430
