### ISSUE TITLE
Stacked bar "sum" data label

### ISSUE THREAD

**Issue by gilhs** [metabase/metabase#4109]
A really useful feature to have, is to be able to display the total value of a stacked column.

Suppose I have the following data:
![image](https://cloud.githubusercontent.com/assets/22723398/21812063/6975f11a-d75a-11e6-9697-953010a1365a.png)

While I can more or less understand the range of the bar total from the axis labels, I can't possible know the actual value for each of the bars.
I can hover over the specific items which comprise each of the bars, but there's no place to get the total.

I suggest adding a flag, possible in the 'labels' section of the chart customization, which allows showing the total at the top of each bar.

**Comment by DavidAwatere** [comment]
Agree - currently having to manually add labels in powerpoint.  It would be fantastic to be able to switch on labels for each bar and even better if we could select top/middle location for the label to be displayed.  By the way - metabase is absolutely amazing.  Really appreciate the great work.  Thank you.

**Comment by kritop** [comment]
@salsakran will this ever see the day of light?

**Comment by flamber** [comment]
There's work being done right now to add data labels to non-stacked charts (see and upvote #4788).
It seems like the PR doesn't support multiple series or stacking currently, but it has been on the drawing board too, so maybe it will arrive after.

**Comment by MarcGJA** [comment]
Oh yeah, this is what I was looking for in v0.34.0!  Especially when using different scales in a combo chart it would really help users to have the values on the chart to instantly associate which data series go with which y-axis.  And now that values can appear above a single series extending the logic to do this would be a real asset!

**Comment by paulrosenzweig** [comment]
This feature was added with #12645. It will go out in v0.36.0.
