### ISSUE TITLE
empty filter for a date field is creating invalid SQL

### ISSUE THREAD

**Issue by runxc1** [metabase/metabase#41105]
### Describe the bug

On a table using the sql builder I added a filter to only display rows where a date column is null and ended up with SQL that looked like this.   A value can never equal null in Sql server.  (https://stackoverflow.com/a/12108091/30850)

Below is the Sql output

SELECT
  "dbo"."FulfillmentInfo"."PromotionType" AS "PromotionType",
  COUNT(*) AS "count"
FROM
  "dbo"."FulfillmentInfo"
WHERE
  ("dbo"."FulfillmentInfo"."CitySparkFulfilled" = 1)
 
   AND (
    "dbo"."FulfillmentInfo"."fulfillDate" = CAST(NULL AS datetime)
  )
GROUP BY
  "dbo"."FulfillmentInfo"."PromotionType"
ORDER BY
  "dbo"."FulfillmentInfo"."PromotionType" ASC

### To Reproduce

1. Ask a new question of a table that contains a date column
2. Add a filter for that column
3. Select Exclude from the date options
4. Select Is Not empty
5. End up with a Column is empty filter
6. Click View SQL to see invalid SQL

### Expected behavior

It should  create a Column IS NULL statement as opposed to a = CAST(NULL AS DATETIME) statement

### Information about your Metabase installation

```JSON
metabase:latest from docker
```

### Severity

Blocks the abilty to check if DateTime values are null

### Additional context

This is running against SQL Server, there could be some SQL dialect that understands the statement but it's probably not valid for most all SQL implementations

**Comment by paoliniluis** [comment]
We fixed that a few days ago (should be in 49.3 or 49.4), so closing
