### ISSUE TITLE
Browser title changes to "e=>e?l.t'Waiting for results...'" while data is being fetched

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#41112]
### Describe the bug

Updated to v0.49.3 and now getting strange browser window title while the data is fetched.
![image](https://github.com/metabase/metabase/assets/4504437/15e54426-5e14-4595-8a01-94b9fc1da0be)

It resolves when the query completes and data is returned

### To Reproduce

1. Start a new question, Sample Database > Orders
2. To make a slightly slow query join Orders a few times (4 worked for me)
3. Visualize the question
4. The browser title changes to "e=>e?l.t`Waiting for restults...`"
5. Once the query completes the title changes to the expected wording

### Expected behavior

No strange content that looks like code in the window title

### Logs

Nothing of note.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-02",
      "tag": "v0.49.3",
      "hash": "dba0992"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

### Severity

Minor, just looks strange for a short time.

### Additional context

Same for Firefox browser. Same behaviour for saved and ad-hoc questions.

**Comment by qnkhuat** [comment]
Duplicated of https://github.com/metabase/metabase/issues/40051. The fix will be included in 49.4
