### ISSUE TITLE
Casting integer to Datatime via Table Metadata makes column unusable 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#41122]
### Describe the bug

Casting integer to Datatime via Table Metadata makes column unusable  ... The lack of logs or error in console makes this absolutely insane to debug

### To Reproduce

1. Go to Admin -> Table Metadata -> Sample DB -> Orders -> Set Product_ID to Creation Date

<img width="1510" alt="image" src="https://github.com/metabase/metabase/assets/110378427/61793350-8711-45ab-acb8-4a57caccb3af">

2. Then edit setting and cast it to DateTime

<img width="1223" alt="image" src="https://github.com/metabase/metabase/assets/110378427/3399dc9b-2cd5-4797-98fd-8363e09cd2f5">

3. Go to the orders table via the GUI and notice that the product ID turned into a Date (I know it doesn't make sense in this case but it's the easiest replication path)

<img width="1364" alt="image" src="https://github.com/metabase/metabase/assets/110378427/acba9f51-8018-4b2e-8225-73131cd7dc76">

4. Now try to filter on the Product_ID

https://github.com/metabase/metabase/assets/110378427/61c7746e-945a-427b-be46-8f77d55dbfc9

### Expected behavior

The filtering needs to work and even though it kind of works it's not visible in the GUI

### Logs

None

### Information about your Metabase installation

```JSON
Works on 48 but breaks on any 49 release
```

### Severity

This will break the GUI functionality for anyone casting epoch times to Date

### Additional context

Left the needs triage since i have no clue if its a backend or frontend issue since there are no logs anywhere

**Comment by bshepherdson** [comment]
This is very likely an MLv2 issue, rejecting the badly typed filter.

I'll look into it.
