### ISSUE TITLE
In Safari, Collection dropdown rendering oddly in Save question modal

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4116]
On 0.22.0 in Safari (and Mac app), when you save a new question or save a modified question, when you go to select which collection it should be saved in, you see this:

![screen shot 2017-01-10 at 2 58 00 pm](https://cloud.githubusercontent.com/assets/2223916/21828516/b6012e7e-d745-11e6-8d28-fab69b3bdf6b.png)

**Comment by camsaul** [comment]
@mazameli does that happen in Safari too?

**Comment by mazameli** [comment]
Ah, yep. Let me rename the issue.
