### ISSUE TITLE
How are you using Metabase to intergrate with other systems ( Email, Push Notification .. )

### ISSUE THREAD

**Issue by adalyz** [metabase/metabase#4120]
Hi Guys, We have been using metabase for some time now and we really like the product. We have been using it for our internal analytics and its been a smooth experience so far. We are now thinking of integrating metabase with our existing systems like email, push notification. 

Let me explain our use case to you guys, since we connect metabase to internal analytics and crm data, we usually feel the need to export the data from metabase and build a campaign ( email, push for our users ), we have been working with CSV export feature for now and its working fine, but usually we need to repeatedly extract out emails and then then build a campaign.

Is there a way where in we could create a pulse/trigger which runs every day and sends out the email to column mentioned in the question ? I know its a stretch but has anyone else faced the same problem before and how do you guys deal with such repeated tasks.

Thanks for all the support.

**Comment by gilhs** [comment]
If you're up for the task, there's good API documentation [here](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md).

We developed a simple Python class that wraps the endpoints of running queries and using cards, and we use to it to generate emails with Metabase data.

**Comment by salsakran** [comment]
There are a couple of options -

1. do what gilhs mentioned and hit our API directly.
2. Wait till #4123 gets merged and just use a json link directly (you won't need to authenticate), it'll be much easier to script. 

You can do 1 or 2 via a cron job pretty easily.

Regarding having MB itself send out an email per row in a result set on a schedule, that falls out of scope of our immediate roadmap. It's the sort of thing we could potentially treat as a module you can add, and if you (or anyone else) are interested in doing the legwork, we'd be down to help produce some sort of module system you could plug into.

**Comment by adalyz** [comment]
Thanks a lot for your answers guys, we will wait for the public dashboard and cards, they look pretty exciting, and i think public json, with a small script could be used from webhooks too.

We will explore options and keep you posted in case we would need to build a module system ( which on the face of it looks pretty exciting )

**Comment by navdeepghai1** [comment]
Can we push the data from metabase server to other server  using hooks.
Hooks which will get trigger after creation, modification, deletion of Card, Dashboard etc.

This will be amazing  to share the data between two servers.

**Comment by sbelak** [comment]
I know @denispavliha has done some impressive integrations and workflow automations using Metabase and Mautic. Maybe he can chime in.

**Comment by denispavliha** [comment]
Hey, unfortunately Metabase can't fire webhooks yet, as far as I know. I had a similar requirement like @navdeepghai1 as I had to show a number (or two) from Metabase on one of our webpages.

Actually, what I did was attach Metabase to Mautic's SQL database where we store our app's users, and also to our app's PostgreSQL where we store reservations. **Two simple questions in Metabase, then, count those users and reservations, respectively, which we wanted to showcase on https://dozdravnika.si/predstavitev/#apply as live counters.**

To do that, I've set up a simple PHP script that calls Metabase's card the same way a dashboard does. E.g. for reservations this is my code:

```
$data = json_decode(file_get_contents("https://insert_metabase_base_url_here/api/embed/card/insert_guid_of_card_here_by_inspecting_ajax_calls_using_browser_console/query"), true);
$reservationCount = $data["data"]["rows"][0][0];
echo `number_format((string)($reservationCount),0,",",".");
```
The code grabs a JSON payload from Metabase's backend, and parses out what we want to display (and formats the number). Not that smooth, but it works - we have Metabase-backed live counters on our webpage. :)

**Comment by navdeepghai1** [comment]
@denispavliha  @sbelak 

I have the inbuilt scheduler in ERP and I setup this scheduler to execute after every five minutes.
It will sync all the cards, Dashboards and users in ERP. But implementation is  only useful for new records, which are not synced with ERP.

What If user from metabase website make changes in existing Users, (Rename, Delete, Modify) Then I won't be able to modify the existing records in ERP which are already synced.

For this purchase  I wanted to know about hooks(On Deletion, Modification, Renaming etc).

Second Option:
In ERP itself I can update the users but then I have to iterate through  all the existing synced users and modify the each one by one.(in this case, existing user can be modified on metabase website or not, but have to update all).

If we  manage to provide this feature of hooks in metabase then we can integrate metabase with ERPNext.

You can also check how I have integrated metabase with ERP in this video:
https://drive.google.com/open?id=1wqg_1GiRN7crSpUZ9Y8L9c7Q_tYkHEhq

**Comment by denispavliha** [comment]
I'm not sure why you're trying to get these data out of Metabase, since the latter is clearly a BI visualization tool that, per se, does not hold any data. (OK, it can if you create custom fields and combined values using queries, but tbh you can do all that on the primary database Metabase has access to.)

**Comment by ppinck-CardTapp** [comment]
I found this thread because I'm looking to implement a sync of metabase native objects (specifically pulses and questions/cards) to a Salesforce environment. The webhook approach would be useful to me in that I would like to be notified if a record representing those entities is changed.

In the current architecture I will probably just have a nightly job run that retrieves all records from metabase and upserts data into the destination system.

**Comment by intellischool-dave** [comment]
Same as @ppinck-CardTapp here - a webhook approach would be extremely useful for us to enable alerts and other relevant notifications from Metabase in our user interface.

At the moment we're looking at watching the Metabase database for alert questions that have been run (and returned a result triggering an alert), but a webhook would be a much cleaner and better supported way of doing this :)

**Comment by salsakran** [comment]
closing since this is a discussion that is better had on our user forum vs an actionable task for our issue tracker.
