### ISSUE TITLE
Color table based on cell value - Feature request

### ISSUE THREAD

**Issue by jsve** [metabase/metabase#4121]
It would be great to be able to somehow color the cells / rows of a table based on the values in the cell / row. 

Coloring of cells would be great for example to illustrate customer retention, like in the appended file. Coloring of rows, based on the value of one or more of the cells would be great to draw special attention to some of the rows, might this be best / worst performer in a set of coworkers / products.

Cell coloring should probably be a gradient between two values, or max / min in the set. Row colors could probably use the same gradient, or just a color if above / below a certain value.

This functionality is similar to conditional formatting in excel.

![table1b](https://cloud.githubusercontent.com/assets/9053945/21842876/ee7c9402-d7e8-11e6-91a5-26c698eb78fe.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by GuiSim** [comment]
I would have used this feature today. We would have liked to have some cells turn red if their value is negative.

**Comment by sailxjx** [comment]
I wonder how to create a retention table by metabase.

**Comment by maxfielm** [comment]
+1 to this feature request. Adding a vote for red/yellow/green gradients to indicate positive/negative trends would be great.

**Comment by raghavkhajuria** [comment]
Yeah, having conditional formatting of data would be great, any idea if this proposal would be considered ?

**Comment by sebmartel** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by WhatWapp** [comment]
+1

**Comment by wordisborn** [comment]
+1

**Comment by mazameli** [comment]
I hope all of you heard already, but [this feature is now available](https://metabase.com/blog/0.30/) in version 0.30 of Metabase. We'd love to hear what you think about it, as well as 0.30 overall if you have a minute to [fill out this survey](https://goo.gl/forms/D8Zt8uUAUR3Up1Lv1). Thanks!

**Comment by MarkRx** [comment]
It's great! I would love to see it expanded to include more data types - Strings and dates in particular :)
