### ISSUE TITLE
Progress visualizations don't show, except on dashboards

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#41243]
### Describe the bug

Questions with a "Progress" visualization have an error on the visualization on the question page, although they work fine when you add them to a dashboard.

- Duplicated Issue: https://github.com/metabase/metabase/issues/40658

Here's the error:

<img width="821" alt="image" src="https://github.com/metabase/metabase/assets/39073188/050a6111-6f6a-4318-88e5-e1fa519ce82c">

this is the error in the browser console:
```
console.js:13 TypeError: Cannot read properties of undefined (reading 'height')
    at bP.componentDidUpdate (Progress.jsx:101:39)
    at bP.componentDidMount (Progress.jsx:87:10)
    at react-dom.production.min.js:219:411
    at a9 (react-dom.production.min.js:221:83)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at on (react-dom.production.min.js:122:325)
    at a7 (react-dom.production.min.js:252:279)
    at aG (react-dom.production.min.js:243:371)
    at react-dom.production.min.js:123:115
```

### To Reproduce

See an example on [stats](https://stats.metabase.com/question/15546-revenue-goal-for-this-quarter) or

1. Create a new question that selects one number, such as "Sum of Total" from "Orders":
![image](https://github.com/metabase/metabase/assets/39073188/108aba3b-0ee5-4616-8fc5-341407ce2179)
2. Select the "Progress" visualization type, and observe the error

### Expected behavior

the graph should look like it does on a dashboard, e.g.
![image](https://github.com/metabase/metabase/assets/39073188/990775a6-3106-4a56-8697-b5932a016121)

### Information about your Metabase installation

```JSON
master, haven't checked 49 though
```

### Severity

blocks users from using the progress visualization

**Comment by NicolasPA** [comment]
I think it is the same as https://github.com/metabase/metabase/issues/40658.
