### ISSUE TITLE
Visualization settings are not persisted during question edits.  

### ISSUE THREAD

**Issue by DillonWhatley** [metabase/metabase#41276]
### Describe the bug

The visualization settings of certain chart types (line chart is the primary tested) are lost when making unrelated changes to the question.  

### To Reproduce

Create a question with your sql
Choose line chart visualization and set your x & y axis in the visualization settings
Save and leave question
Come back to question and alter anything, except visualization settings, that allows you to save.  For example change a Field Filter's filter widget type from date range to date filter.  
Save
Leave question and return.  Run your query and receive a greyed out line chart with no axis selected.

### Expected behavior

Axis should remain selected unless something about the query changes that removes the selected axis columns.  If axis are not selected for chart types then disable save or provide some UI indicator to the user. 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.4.16-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-02",
      "tag": "v1.49.3",
      "hash": "dba0992"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Low

### Additional context

**EDIT**

Added video of bug

https://github.com/metabase/metabase/assets/6433224/54693473-e9ec-4ffe-9225-f0bd27db8642

SQL Used -
`SELECT
"PUBLIC"."ORDERS"."USER_ID" AS "USER_ID",
  SUM("PUBLIC"."ORDERS"."TOTAL") AS "TOTAL",
  CAST("PUBLIC"."ORDERS"."CREATED_AT" AS DATE) AS "CREATED_AT"
FROM
  "PUBLIC"."ORDERS"
WHERE {{time_period}} 
AND "PUBLIC"."ORDERS"."USER_ID" = {{user}}
GROUP BY 
    CAST("PUBLIC"."ORDERS"."CREATED_AT" AS DATE), "PUBLIC"."ORDERS"."USER_ID"
LIMIT
  200`

Note - I believe the text filter for `User` with no default is part of the problem.   
When you navigate to the question it's initially "broken" until you enter a value into the filter.  I believe saving the question  in this state saves it without the AXIS selected.

**Comment by ignacio-mb** [comment]
Hi @DillonWhatley I used the following SQL and couldn't reproduce:

`SELECT
  DATE_TRUNC('month', "PUBLIC"."ORDERS"."CREATED_AT") AS "CREATED_AT",
  COUNT(*) AS "count"
FROM
  "PUBLIC"."ORDERS"
[[WHERE {{TEST}}]]
GROUP BY
  DATE_TRUNC('month', "PUBLIC"."ORDERS"."CREATED_AT")
ORDER BY
  DATE_TRUNC('month', "PUBLIC"."ORDERS"."CREATED_AT") ASC`

Can you provide the SQL using Sample data?

Maybe a video can help as well.

Thanks!

**Comment by zbodi74** [comment]
Thank you @DillonWhatley, yes, it appears the visualization settings are lost if the native question is saved in a "broken" state, when a required parameter is missing.
