### ISSUE TITLE
[dc.js migration] chart layout includes excessive paddings

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#41288]
https://metaboat.slack.com/archives/C06G94JTWBS/p1712761135590019
https://metaboat.slack.com/archives/C06G94JTWBS/p1712761335456369

This issue is caused by a bug within echarts. The bug is that echarts applies an inconsistent amount of bottom padding if x-axis labels are rotated 45 degrees, and the `grid.containLabel` option is `true`.

<img width="497" alt="Screenshot 2024-04-18 at 9 48 30 AM" src="https://github.com/metabase/metabase/assets/37751258/7e768fb7-5676-46dd-8ff9-ac195f691b1f">

In this example, `grid.bottom` is 40 and `grid.containLabel` is `true`. When the axis labels are not rotated, echarts applies 49px of bottom padding, but when they are rotated 45 degrees, then an extra 9 pixels of bottom padding are added, despite the `grid.bottom` option still being 40.

We unfortunately cannot solve this by subtracting a constant offset from `grid.bottom` when labels are rotated 45 degrees, because the amount of extra padding varies.

<img width="507" alt="Screenshot 2024-04-18 at 9 48 35 AM" src="https://github.com/metabase/metabase/assets/37751258/ab90ee59-3c93-45ae-a043-75be6bfba95b">

In this example where `grid.bottom` is 30, then only 6 extra pixels are added.

**Comment by alxnddr** [comment]
@EmmadUsmani since we compute ticks dimensions, axis name dimensions by ourselves we can use it to add grid paddings and do not use `containLabel`

**Comment by EmmadUsmani** [comment]
@alxnddr We still need `containLabel` to contain data labels and goal line labels
