### ISSUE TITLE
Two lines with the same color highlighted when mouse over one label

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4129]
Metabase 0.22

![image](https://cloud.githubusercontent.com/assets/1708680/21852054/b220de3e-d822-11e6-9ae8-642243bb4311.png)

**Comment by camsaul** [comment]
Hey @anki-code, didn't you already bring this up in #3185?

**Comment by camsaul** [comment]
![screen shot 2017-01-11 at 3 06 50 pm](https://cloud.githubusercontent.com/assets/1455846/21870104/ab0a52d2-d80f-11e6-9f70-9ef4e2a1ae51.png)

**Comment by tlrobinson** [comment]
This is also fixed by #4107

**Comment by anki-code** [comment]
@camsaul Yep, I've moved this here as separate issue. Seems it's right.

@tlrobinson Thank you!

**Comment by tlrobinson** [comment]
Fixed in `master`
