### ISSUE TITLE
Pivot table: setting the XY columns manually

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4130]
I really love Pivot table function for the sql-based Questions. Thank you for this!

But now the columns for X and Y axes in result table are chosen automatically by Metabase logic. Metabase tries to make table with minimal width but it's not working in some cases and I need to set columns for X and Y axes in pivot table manually.

Please add the dropdown for setting X and Y axes of pivot table manually.

**Comment by tlrobinson** [comment]
Duplicate of #2618
