### ISSUE TITLE
Admin checklist indicates more progress than actual due to audit items

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#41335]
### Describe the bug

The admin checklist of a completely fresh enterprise instance makes me think i have set the instance up. 
<img width="1276" alt="image" src="https://github.com/metabase/metabase/assets/6377293/b00da519-043e-497f-8bf8-5c3ebaf9e34e">

### To Reproduce

`MB_JETTY_PORT=3007 java -jar 1.49.5.jar`

Run a recent ee version and the checklist is far too filled out.

```clojure
setup=> (state-for-checklist)
{:db-type :h2,
 :hosted? false,
 :configured {:email false, :slack false},
 :counts {:user 2, :card 75, :table 21}, ;; <- audit content here
;; the following indicates that there are dashboards, non-sample dbs (audit db connection), collections, models. 
;; It's a rich instance but solely because of the audit info
 :exists {:non-sample-db true, :dashboard true, :pulse false, :hidden-table false, :collection true, :model true}}
```

### Expected behavior

The audit items should not factor into this checklist for new admins

### Information about your Metabase installation

```JSON
1.49.5.jar
```

### Severity

p2

**Comment by albertoperdomo** [comment]
Related: would it be possible to skip this content in the [usage stats aggregates](https://github.com/metabase/metabase/blob/master/src/metabase/analytics/stats.clj)?

**Comment by calherries** [comment]
I can take this since and I'll look into https://github.com/metabase/metabase/issues/41524 as well, since I made the issue much worse with the sample content.
