### ISSUE TITLE
Hide Editor in Question card by default

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4133]
We already have almost 100 question cards and most of them built on SQL and most of users don't want to see Editor every time they open the question card (Editor and Metabase header takes 50% of screen). Could it possible to hide the Editor by default?

**Comment by gilhs** [comment]
I would suggest making that behavior a feature flag (whether or not it's default)

**Comment by anki-code** [comment]
One of the simple ways is to store editor state in LocalStorage. If user hide the editor, doesn't open it in next card.

**Comment by salsakran** [comment]
I agree. In most situations the SQL is intimidating to 90% of the users of a given card.

**Comment by tlrobinson** [comment]
@salsakran So SQL should always be hidden by default for saved cards? Or store the user's last state and use that?
