### ISSUE TITLE
Proposal for a more sensible aggregation logic for custom fields with division and multiplication

### ISSUE THREAD

**Issue by StaymanHou** [metabase/metabase#4134]
Hi Metabase team,

We've been enjoying using metabase for a couple of months. One important thing that's impeding us from fully utilize the power of the platform is the aggregation logic for custom fields with division and multiplication. Therefore, we would like to propose a aggregation logic that makes more sense for us (and hopefully for others as well).

## Use Case

Sample Table Schema - Daily Revenue - Visitor Data
* id - pk
* date - date
* utm_source - string (e.g. google organic search / adsense cpc)
* utm_campaign - string (e.g. regular banner ads / video preroll ads)
* device - string (e.g. desktop / mobile / tablet)
* country - string (e.g. U.S. / U.K. / others)
* revenue - currency (e.g. $2000.00)
* visitor - integer (e.g. 100)

We would like to have a custom field `revenue per visitor = revenue / visitor`

Now, for example, we want to get the average total revenue per visitor grouping by country for last month.

The question will be `Data (Daily Revenue - Visitor Data), Filter by (date = last month), View (Sum(revenue per visitor)), Group by (country)`

That result in the following SQL query `SELECT sum(revenue / visitor) AS sum ...`

However, what we actually meant is `SELECT sum(revenue) / sum(visitor) AS sum ...`

As an engineer, I know I can always write SQL query to get the desired data, but for the non-tech people in the team, it's hard to have them to get the thing correct.

Also, when I think more about that, I guess most people would use division to compute some sort of ratio, whereas `sum(column A / column B)` will hardly make sense, and `sum(column A) / sum(column B)` will mostly likely be desired.

In addition, it might make sense to do all the aggregation before applying the math in the custom field, since for addition and subtraction, `sum(column A) + sum(column B)` is same as `sum(column A + column B)`

**Comment by salsakran** [comment]
Hey @StaymanHou -

As of v0.22 which we released yesterday you can do the sorts of things you're discussing. Both intra row (`sum(revenue/visitor)`) and post-aggregation (`sum(revenue)/sum(visitor)`) are now possible.

**Comment by salsakran** [comment]
closing unless you meant something else. 

dupe of #3365 and #3364

**Comment by StaymanHou** [comment]
Wow! Awesome! Upgrading to v0.22 right now.
