### ISSUE TITLE
[FE] Add `combine_via_column_header` analytics event

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#41350]
`combine_via_column_header`

https://www.notion.so/metabase/0df8245abb8f46edbede12065d65e774?v=86c486a9c8904fb0ab086ad389f63f81

https://metaboat.slack.com/archives/C0645JP1W81/p1712845418159769

----

update event status in the doc once it's ready

**Comment by romeovs** [comment]
Duplicate from another [epic](https://github.com/metabase/metabase/issues/41770): https://github.com/metabase/metabase/issues/41773
