### ISSUE TITLE
feature require: html, markdown, image, iframe support in dashboard and restful api support

### ISSUE THREAD

**Issue by alitrack** [metabase/metabase#4135]
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

### Database support
If there's an exisiting issue, please add a +1 in the comments as we
prioritize drivers by the level of support. Otherwise, please include the name
of the database and the version.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by salsakran** [comment]
Hey @alitrack 

Please fill out an issue per request, and note that a number of your requests already have issues open for them. 

Also, please fill out the template if you are submitting a bug report, or delete them from the issue, and replace with a description of what you're asking for. 

Closing for now. I'll re-open if you provide more information.
