### ISSUE TITLE
In-question multi series charts do not appear to work in 0.22

### ISSUE THREAD

**Issue by kristian-elder** [metabase/metabase#4136]
Metabase version: 0.22.0 (as released)
Browser: Chrome Version 55.0.2883.87 (64-bit)
Metabase datebase (and internal): MySql

*Expected behaviour*

Creating a question grouped by two dimensions should allow for a multi series line chart as described in 
http://www.metabase.com/docs/latest/users-guide/08-multi-series-charting.html

*Observed behaviour*

Only one of the group by dimensions appear to be used to draw the chart, with no options to change this.

The screenshot in the doc is from an older version, but has this functionality changed?

**Comment by salsakran** [comment]
I just tried this out on 0.22 and was't able to replicate it. When I created a 2-d breakout using the sample dataset, I was able to create multi-series charts.

Can you share the query + a screenshot of what you're seeing?

**Comment by camsaul** [comment]
Closing this out since we weren't able to repro 11 months ago and haven't heard back after a request for more info
