### ISSUE TITLE
Wrong Link for "Learn more" Collections Info Box

### ISSUE THREAD

**Issue by calmyournerves** [metabase/metabase#4137]
Hey there

The "Learn more" link in the info box at `/questions` links to `http://www.metabase.com/FIXME`.

![image](https://cloud.githubusercontent.com/assets/480921/21884618/55fed754-d8b4-11e6-950c-8334dead7cf2.png)

The link seems to be missing here: 
https://github.com/metabase/metabase/blob/e99e07c54c6f5d9f9aaffedee1edf536682e788a/frontend/src/metabase/questions/containers/QuestionIndex.jsx#L121

**Comment by salsakran** [comment]
Good catch. Thanks for letting us know.
