### ISSUE TITLE
Migration on MySQL/MariaDB leads to having multiple revisions with latest=true which leads to repeated items in the FE

### ISSUE THREAD

**Issue by mdz0r** [metabase/metabase#41374]
### Describe the bug

Just upgraded to 0.49.5, self hosted, mariadb database.
We have multiple same entries in a collection, with only dashboards. It doesn't seem to happen on collections with queries.

### To Reproduce

Go to a collection containing dashboards and list it

### Expected behavior

We shouldn't have duplicates entries.

### Logs

metabase: 2024-04-12 17:16:15,724 DEBUG middleware.log :: #033[32mGET /api/collection/2/items 200 32,9 ms (5 appels de DB) Connexions App DB : 3/15 Threads Jetty : 4/50 (1 inactif, 0 en file d'attente) (112 total de threads actifs) Requêtes en cours : 0 (0 en file d'attente)#033[0m

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.105.1.el7.x86_64",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "snowflake",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.35"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-11",
      "tag": "v0.49.5",
      "hash": "31c4887"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

### Additional context

![mb](https://github.com/metabase/metabase/assets/42241744/00728122-98a0-4464-b5ab-cf8922853386)

**Comment by ignacio-mb** [comment]
Hi @mdz0r, can you put https://yourmetabaseurl/api/collection on your browser and paste the JSON here? You can remove sensitive information if needed.

**Comment by mdz0r** [comment]
Here it is.
[json_mb.txt](https://github.com/metabase/metabase/files/14961172/json_mb.txt)

**Comment by ignacio-mb** [comment]
@mdz0r sorry, I meant to ask for the collection you are in. 
For example, my URL is:  https://myurl.com/collection/40, so I need https://myurl.com/api/collection/40
Are you using serialization?

**Comment by mdz0r** [comment]
What do you mean by serialization?

/api/collection/2 :
{
  "authority_level": null,
  "description": null,
  "archived": false,
  "slug": "000_dashboards",
  "can_write": true,
  "name": "000 Dashboards",
  "personal_owner_id": null,
  "type": null,
  "effective_ancestors": [
    {
      "metabase.models.collection.root/is-root?": true,
      "authority_level": null,
      "name": "Nos analyses",
      "is_personal": false,
      "id": "root",
      "can_write": true
    },
    {
      "name": "xxxx",
      "id": 3,
      "personal_owner_id": null,
      "can_write": true
    }
  ],
  "effective_location": "/3/",
  "parent_id": 3,
  "id": 2,
  "entity_id": null,
  "location": "/3/",
  "namespace": null,
  "is_personal": false,
  "created_at": "2020-07-17T14:06:49+02:00"
}

/api/collection/2/items : returns the same dashboard multiple times :
    {
      "description": null,
      "collection_position": null,
      "database_id": null,
      "name": "Global",
      "id": 52,
      "entity_id": "GR-MQpVfakfekZyzNk_S8",
      "last-edit-info": {
        "id": 1,
        "timestamp": "2024-02-26T11:24:08+01:00"
      },
      "model": "dashboard"
    },
    {
      "description": null,
      "collection_position": null,
      "database_id": null,
      "name": "Global",
      "id": 52,
      "entity_id": "GR-MQpVfakfekZyzNk_S8",
      "last-edit-info": {
        "id": 1,
        "timestamp": "2024-02-26T11:24:08+01:00"
      },
      "model": "dashboard"
    },
    {
      "description": null,
      "collection_position": null,
      "database_id": null,
      "name": "Global",
      "id": 52,
      "entity_id": "GR-MQpVfakfekZyzNk_S8",
      "last-edit-info": {
        "id": 1,
        "timestamp": "2024-02-26T11:24:08+01:00"
      },
      "model": "dashboard"
    },
    {
      "description": null,
      "collection_position": null,
      "database_id": null,
      "name": "Global",
      "id": 52,
      "entity_id": "GR-MQpVfakfekZyzNk_S8",
      "last-edit-info": {
        "id": 1,
        "timestamp": "2024-02-26T11:24:08+01:00"
      },
      "model": "dashboard"
    },

**Comment by mdz0r** [comment]
Hello,

Did a bit of drill down on this particular issue.
It's actually related to the `revision` table.

```
mysql> select count(*) from revision where model_id=52 and model = 'Dashboard' and most_recent = true;
+----------+
| count(*) |
+----------+
|        4 |
+----------+
```

I have actually several dashboards with multiple "most_recent" = true which I guess shouldnt happen.

```
mysql> select model_id, count(*) from revision where model = 'Dashboard' and most_recent = true group by model_id having count(*)>1;
+----------+----------+
| model_id | count(*) |
+----------+----------+
|       15 |        3 |
|       18 |        3 |
|       20 |        4 |
|       22 |        2 |
|       21 |        2 |
|       43 |        2 |
|       40 |        2 |
|       44 |        2 |
|       52 |        4 |
+----------+----------+
9 rows in set (0,00 sec)
```

Would it be OK to set most_recent = true on the most recent record for each dashboard ?

**Comment by sicarul** [comment]
I'm having the same issue with many dashboards
<img width="602" alt="image" src="https://github.com/metabase/metabase/assets/4952116/1d8d72ca-20d4-4251-94b1-35b0e0ee3f68">

**Comment by mdz0r** [comment]
Updating the revision table to keep the latest most_recent record = true fixed the issue for me.

**Comment by paoliniluis** [comment]
@mdz0r so you say that this was due to the revision table having multiple entries (same dashboard id) with "true"?

**Comment by mdz0r** [comment]
Yep

**Comment by paoliniluis** [comment]
@qnkhuat assigning you also on this one as it's a migration MySQL migration specifically

**Comment by sfaut** [comment]
Thx @mdz0r, I have fixed the problem with :

```sql
create table metabase.revision_bak like metabase.revision;
insert into metabase.revision_bak select all * from metabase.revision;

start transaction;

with duplicate_dashboard as (
	-- metabase.revision.timestamp is duplicate too, so I use metabase.revision.id and keep the last one
	select all model_id, max(id) as last_most_recent 
	from metabase.revision 
	where model = 'Dashboard' and most_recent = true 
	group by 1
	having count(*) > 1
)
update metabase.revision
set most_recent = false
where true
	and model = 'Dashboard'
	and model_id in (select all model_id from duplicate_dashboard)
	and id not in (select all last_most_recent from duplicate_dashboard)
;

commit work;
```
