### ISSUE TITLE
Adding a string to UI question's custom column crashes Metabase

### ISSUE THREAD

**Issue by TLazarevic** [metabase/metabase#41381]
### Describe the bug

Upon entering a string in UI query editor's custom column and clicking away, Metabase crashes

### To Reproduce

1. Go to UI query editor
2. Click on Custom Column
3. Enter a string with single or double quotes - example: 'Test'
4. Click somewhere in the dropdown, away from the input field
5. Metabase crashes
<img width="1080" alt="Screenshot 2024-04-12 at 20 40 23" src="https://github.com/metabase/metabase/assets/18078190/2087606d-6cb9-4f96-9612-e96e5bcbfe62">
<img width="1080" alt="Screenshot 2024-04-12 at 20 40 31" src="https://github.com/metabase/metabase/assets/18078190/142f9026-65b5-4c01-a50f-1f38cbf39cf7">

### Expected behavior

No crash

### Information about your Metabase installation

```JSON
Metabase v0.49.1
```

### Severity

P3?

**Comment by uladzimirdev** [comment]
likely related
https://github.com/metabase/metabase/issues/27671
https://github.com/metabase/metabase/issues/34580
