### ISSUE TITLE
MongoDB Error Exception Opening the Socket.

### ISSUE THREAD

**Issue by minhajali1990** [metabase/metabase#4139]
My MongoDB is installed in Linux server. it's allowing 1 of 3 time
means if I am trying three times it's connecting one time other two times it's giving error.
from my c# application as well as MongoChef. what would be the reason can anyone help.

In other hand I am able to connect with same connection string from c# and mongoChef to my other database which is installed in windows machine so I can say my c# connection string is correct.

![from mongochef](https://cloud.githubusercontent.com/assets/7066802/21890322/47e8c8a2-d8f3-11e6-9fc4-f6782f3a9163.png)
![from c#](https://cloud.githubusercontent.com/assets/7066802/21890323/480f15b6-d8f3-11e6-9abb-cd2755c3bfbf.png)

**Comment by salsakran** [comment]
Hey @minhajali1990 -

Given that your problem doesn't relate to Metabase, this is not an appropriate forum to ask for help. You might try our discussion forum at discourse.metabase.com and perhaps someone might know the answer.
