### ISSUE TITLE
Clicking in a dashboard filter too easily gets captured as an accidental drag which edits the dashboard

### ISSUE THREAD

**Issue by brendanheywood** [metabase/metabase#41394]
### Describe the bug

When using a dashboard, if you click into a filter and hold the mouse button for fractionally longer than you should which ends up as a mouse drag, then the filter gets dragged as though you were editing the dashboard. In most instances this drag could be a single pixel and is completely unintentional but it puts the dashboard into the 'editing' mode which then surprises you later on when you try to leave or change something and it asks you to save, but you have no idea what you just did.

The 'drag' tolerance is way too sensitive, it should have a threshold of say 10 pixels. On top of this, even if you did drag but then end up dropping it back into its original location, in other words nothing has changed, then it should detect this and not trigger edit mode.

Compare this to normal inputs anywhere else in any other app. eg a click and drag in the metabase search box doesn't have any unexpected side effects.

### To Reproduce

1. Go to any dashboard with a filter where you have edit rights
2. Click on a filter while moving the mouse slightly
3. Noticed that metabase has unintentionally toggled into the dashboard edit mode

### Expected behavior

1) It should ignore drags under a certain threshold
2) and it should also not toggle editing, when a drag resulted in no change

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.210-201.852.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Australia/Melbourne"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v1.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": "Australia/Sydney"
    }
  }
}
```

### Severity

It's annoying

**Comment by perivamsi** [comment]
@brendanheywood thank you for reporting this. could you please add a video for this? I am not able to repro this based on the text description and a video of the bug would be helpful.

**Comment by brendanheywood** [comment]
thanks @perivamsi here is a gif, sorry the cursor isn't visible, but the first time I click in the input I am very careful to just click, the second click is a 'typical'click where the mouse is moving like 2 or 3 pixels and its enough to trigger the drag

![Peek 2024-04-15 14-34](https://github.com/metabase/metabase/assets/187449/9ddb8655-bc59-4566-9e21-4e61e2354faa)

**Comment by perivamsi** [comment]
Very helpful, thank you!

**Comment by Tony-metabase** [comment]
Upgrade to that should fix it, you are hitting https://github.com/metabase/metabase/issues/40663 ... It's a duplicate
