### ISSUE TITLE
"Could not convert UTC to a ZoneOffset!" when zoom in an aggregation element

### ISSUE THREAD

**Issue by claudiomerli** [metabase/metabase#41392]
### Describe the bug

I'm using Metabase to display a simple dashboard for my personal banking movement. I'm using MongoDb.
My documents have this structure:
![image](https://github.com/metabase/metabase/assets/71256977/f4c6b613-8f92-4a72-9e6c-df1eb7e1b6b4)

I've a question with a simple aggregation on date field that sum all expenses by day.

This is a visualization example:
![image](https://github.com/metabase/metabase/assets/71256977/5a608908-c94e-44e9-82da-a2da40d85dce)

But when I click on a spike and then on zoom in:
![image](https://github.com/metabase/metabase/assets/71256977/54b4f5e2-c6d3-4a3d-9659-2a18c9401ecd)

appears this error:
![image](https://github.com/metabase/metabase/assets/71256977/0b2bbf72-db6d-4af2-9a41-7ed3664128d5)

### To Reproduce

- Connect to a mongodb
- Insert a document like:
```
{
    "_id" : "aaa",
    "date" : ISODate("2024-04-13T23:43:49.000+0000"),
    "import" : NumberInt(5),
    "card" : "Mastercard 123,
    "casual" : "Amazon Shopping"
}
```
- Create a question grouping by date
- Click on zoom in on UI visualization

### Expected behavior

It should show up single movements on that date.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "19-ea+20-1369",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "19-ea",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "19-ea+20-1369",
    "os.name": "Linux",
    "os.version": "6.1.73-haos-raspi",
    "user.language": "en",
    "user.timezone": "Europe/Rome"
  },
  "metabase-info": {
    "databases": [
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": "Europe/Rome"
    }
  }
}
```

### Severity

It's annoying

**Comment by ignacio-mb** [comment]
Hi @claudiomerli, you are running version 43, which is very old and unsupported. Please upgrade :)

Cool use case btw!

**Comment by claudiomerli** [comment]
Oh ok! I’m using an addon for home assistant thank at this point I think is not updated. Thank you!
