### ISSUE TITLE
Update Docs - Can't assign high-level category to field

### ISSUE THREAD

**Issue by gysi** [metabase/metabase#4141]
_Mebase version: 0.21.1
Database: Postgres 9.6
Metabase hosting environment: OS X, metabase.jar
Metabase internal database: H2 (default)_

The docs are stating the following:

> **Types**
> Type assigns a field a high-level category, and changes how the field can be used within Metabase. For example, only Metric fields can be added or averaged. A field can be assigned one of four basic types:
> 
> - **Metric** — a metric is a number that you expect to plot, sum, take averages of, etc. You could think of it as anything that would end up being plotted on the y-axis of a graph.
> - **Dimension** — This is any field that you expect to use as an x-axis of a graph or as part of a pivot table. Anything that you could group your results by could be called a dimension, such as dates.
> - **Information** — This is any other information that is not expected to be used in any kind of aggregate metrics but contains other information. Examples include descriptions, names, emails.
> - Sensitive Information — Use this setting for fields that you don’t want to show up anywhere in **Metabase**. This does the same thing as changing the visibility to Do Not Include, and in fact if you set a field’s visibility to Do Not Include, it’ll automatically get assigned the type Sensitive Information.

But I can't find such a dropdown

![screen shot 2017-01-12 at 15 16 46](https://cloud.githubusercontent.com/assets/1576445/21893091/e745633e-d8d9-11e6-87b3-ac412afe5281.png)

**Comment by salsakran** [comment]
That documentation is outdated. We no longer use those distinctions as they didn't prove very useful. Eg, people wanted to filter on metrics, etc.
