### ISSUE TITLE
No edit icon after edit question

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4142]
Regress in 0.22:

![image](https://cloud.githubusercontent.com/assets/1708680/21894731/5021a90a-d8f1-11e6-9029-b5dec2f8dd00.png)

**Comment by tlrobinson** [comment]
Looks like this is due to the addition of the `can_write` attribute returned by `GET /api/card/:id` but not `PUT /api/card/:id`. @camsaul could we have the PUT endpoint response include everything the GET endpoint does?

**Comment by camsaul** [comment]
Yeah I can do that

**Comment by camsaul** [comment]
Fixed by #4164
