### ISSUE TITLE
[dc.js migration] tool-tip and axis column names should respect BE `display_name` values

### ISSUE THREAD

**Issue by JesseSDevaney** [metabase/metabase#41437]
**Master**
![image](https://github.com/metabase/metabase/assets/22608765/0d800ca2-b85a-4b83-828a-c062701e386c)

**ECharts**
![image](https://github.com/metabase/metabase/assets/22608765/3dde93df-3f80-406b-992d-19b0bfb909df)

---
**Query**
![image](https://github.com/metabase/metabase/assets/22608765/35f4074c-24e7-46fb-9ef6-63c39523a37d)

**Comment by EmmadUsmani** [comment]
<img width="940" alt="Screenshot 2024-04-16 at 11 27 38 AM" src="https://github.com/metabase/metabase/assets/37751258/562d4ca7-5015-48c5-ab1f-61e27805b1c7">

This was fixed by https://github.com/metabase/metabase/pull/41450
