### ISSUE TITLE
Tab query param not applied in embed

### ISSUE THREAD

**Issue by tboulis** [metabase/metabase#41440]
### Describe the bug

Hello everyone 👋 
We've noticed that in the latest version (v0.49.5) the `URL?tab=tab_id` is not applied when embedding a dashboard in an iframe. 
In our case we have `https://URL?tab=2-tab-2` but the iframe renders the tab with id `1-tab-1`

### Screenshot:
<img width="1517" alt="Screenshot 2024-04-15 at 22 18 35" src="https://github.com/metabase/metabase/assets/24255041/712f5726-e333-4f2f-b59a-bd698fa42469">

### To Reproduce

1. Create a dashboard with more than one tabs
2. Enable embedding for that dashboard
3. Create an embedding URL and defined a tab other than the first in the url of the embedded dashboard by appending ?tab="TAB_ID" in the url
4. Expect the embed to open the tab with id "TAB_ID:
5. The embed loads the default tab (first one)

### Expected behavior

It should render the url defined tab like it did in previous versions

### Information about your Metabase installation

```JSON
- Browser: Google Chrome Version 123.0.6312.123 (Official Build) (arm64)
- OS: Macos 14.4.1 Sonoma
- DB: PostgreSQL
- Metabase instance: self-hosted but happens on the cloud instance too
- Metabase version: `v0.49.5`
```

### Severity

High - blocks multiple users

**Comment by saadbahir** [comment]
Hello @kulyk

Sorry to ping you like this but I wondered whether your [PR](https://github.com/metabase/metabase/commit/7efd8d3627171fa1805a543d4f8e36873a38296a) right here may have introduced this regression

**Comment by npretto** [comment]
This has been fixed by https://github.com/metabase/metabase/pull/41399, a release should be made soon

**Comment by npretto** [comment]
To add some context, I think this is what's going on:
https://github.com/metabase/metabase/pull/41399 doesn't render `<DashboardTabs>` unless we have tabs, `<DashboardTabs` calls `useDashboardTabs` which dispatches `initTabs` before we have the tabs loaded, causing the code to think we're selecting an invalid tab on the reducer and therefore setting the selected tab to null https://github.com/metabase/metabase/blob/5a7360d23b9c4048f1b99f86aa8daa5848367467/frontend/src/metabase/dashboard/actions/tabs.ts#L569-L578

**Comment by saadbahir** [comment]
Thank you @npretto for your quick feedback!

This is a vital fix for us as we use Metabase Embedding at scale and this is currently breaking a lot of our workflows

Do you please have any timeline on the release? are we talking hours or days?
Thank you for your help!

**Comment by Tony-metabase** [comment]
@saadbahir we should be releasing 49.6 today so expect a couple of more hours for it to be available
