### ISSUE TITLE
timestamp filter 'last N hours'  discards current hour

### ISSUE THREAD

**Issue by rrichardson** [metabase/metabase#4144]
Metabase version 0.22.0
Database :  Postgres 9.6
Env : Docker in Kubernetes on AWS

when filtering by 'last 24 hours' it creates the query : 
``` sql
SELECT count(*) AS "count", date_trunc('hour', "public"."preping"."timestamp") AS "timestamp", "public"."preping"."campaign_uuid" AS "campaign_uuid"
FROM "public"."preping"
WHERE date_trunc('hour', "public"."preping"."timestamp") BETWEEN date_trunc('hour', (NOW() + INTERVAL '-24 hour'))
   AND date_trunc('hour', (NOW() + INTERVAL '-1 hour'))
GROUP BY date_trunc('hour', "public"."preping"."timestamp"), "public"."preping"."campaign_uuid"
ORDER BY date_trunc('hour', "public"."preping"."timestamp") ASC, "public"."preping"."campaign_uuid" ASC
```

I think that in the 2nd clause of BETWEEN,  the INTERVAL `-1 hour` is unneccesary.  It should truncate to the current time period, not the prior time period.

**Comment by flamber** [comment]
Hi @rrichardson 
While I can reproduce what you're seeing, I'm not sure if the filter picker had the "[X] Include ..." in 0.22.0, but when I activate that, then the query is without `-1 hour`.
![image](https://user-images.githubusercontent.com/1447303/52672461-8a0be500-2ee3-11e9-99b7-b4f32bb649a2.png)

**Comment by rrichardson** [comment]
This may have been fixed between Jan '17 and now.  I'll have to double check.
