### ISSUE TITLE
SAML with Keycloak - Single Logout failing

### ISSUE THREAD

**Issue by mcmluck** [metabase/metabase#41457]
### Describe the bug

After setting up SAML with keycloak, I'm unable to log out of the SSO user even though I have been successfully logged out of Keycloak. I get a `500` error even though the SAML Response is valid. 

### To Reproduce

1. Go to top right cog
2. Click on Sign out

### Expected behavior

Return to Login Page

### Logs

SAML logout failed.

### Information about your Metabase installation

```JSON
- Metabase version: 1.49.5
- Environment: Kubernetes
- DB: Postgres
```

### Severity

blocking deployment of metabase

### Additional context

Post Binding URL is set in keycloak to `<server_uri>/auth/sso/handle_slo`  

decoded SAML response:

```
<samlp:LogoutResponse
  xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
  xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
  xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
  Destination="http://localhost:3000/auth/sso/handle_slo"
  ID="<redacted>"
  InResponseTo="<redacted>"
  IssueInstant="2024-04-16T00:55:19.257Z"
  Version="2.0">
  <saml:Issuer>http://localhost:8080/realms/abc123</saml:Issuer>
  <dsig:Signature
    xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
    <dsig:SignedInfo>
      <dsig:CanonicalizationMethod
        Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
      <dsig:SignatureMethod
        Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
      <dsig:Reference
        URI="<redacted>">
        <dsig:Transforms>
          <dsig:Transform
            Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
          <dsig:Transform
            Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
        </dsig:Transforms>
        <dsig:DigestMethod
          Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
        <dsig:DigestValue><redacted></dsig:DigestValue>
      </dsig:Reference>
    </dsig:SignedInfo>
    <dsig:SignatureValue><redacted></dsig:SignatureValue>
    <dsig:KeyInfo>
      <dsig:X509Data>
        <dsig:X509Certificate><redacted></dsig:X509Certificate>
      </dsig:X509Data>
    </dsig:KeyInfo>
  </dsig:Signature>
  <samlp:Status>
    <samlp:StatusCode
      Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
  </samlp:Status>
</samlp:LogoutResponse>
```

**Comment by escherize** [comment]
Hello @mcmluck. Thanks for the bug report. I've been looking into your issue.

Can you help me out with some more info?

> I get a 500 error even though the SAML Response is valid.

Do you get the 500 from Metabase or from Keycloak? Please provide the error messages associated with this request.

---

I was able to make things work with the following Keycloak settings:

<img width="543" alt="Screenshot 2024-04-23 at 4 55 00 PM" src="https://github.com/metabase/metabase/assets/343288/4125160c-cd4f-446b-847c-01e7c48f7396">

<img width="723" alt="Screenshot 2024-04-23 at 4 54 28 PM" src="https://github.com/metabase/metabase/assets/343288/d74e550d-1311-4ae7-a897-d9b2800a7c50">


Do those match what you have?

**Comment by paoliniluis** [comment]
This is a pending in our docs, we need to document everything we’ve done with SLO cc @jeff-bruemmer

**Comment by paoliniluis** [comment]
@mcmluck can you check our comments above?

**Comment by mcmluck** [comment]
Sorry for the late reply, yeah I have the settings like your screenshots. Not exactly sure what the exact issue was, but I think it was my own fault in adding complexity into the routing. Keycloak was port forwarded to localhost while metabase was exposed to the internal network. Once both were exposed, the SAML worked fine 👍
