### ISSUE TITLE
[Epic] Upsell system

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#41466]
- final visual structure with redlines for engineering [on this figma](https://www.figma.com/file/kdZZogH2tWBVwnG03N7XXc/Upsell-System?type=design&node-id=491-8759&mode=design&t=TmLLwF1Tg9l2aQaM-11)
- final flows and final copy for the pilot set of cases [on this other figma](https://www.figma.com/file/kdZZogH2tWBVwnG03N7XXc/Upsell-System?type=design&node-id=476-9367&mode=design&t=TmLLwF1Tg9l2aQaM-11) page
- the system guidelines [on this notion](https://www.notion.so/metabase/Upsell-System-Guidelines-WIP-72ce6f7402fb4c93a165e904dcf7a93c?pvs=4)

exact scope TBD

**Comment by iethree** [comment]
can we use this one https://github.com/metabase/metabase/issues/41116 ?

**Comment by luizarakaki** [comment]
Sure
