### ISSUE TITLE
Error message in LDAP settings

### ISSUE THREAD

**Issue by CZvacko** [metabase/metabase#41494]
### Describe the bug

Although everything should be set up correctly (it seems to work normally), a red error message "**e.ldap-port?.trim is not a function**" appears above the Save button. I didn't notice this in previous versions.

### To Reproduce

Settings is like:
FQDN for server name
636 for port
SSL
some LDAP user
some LDAP password
set Search base for user
set User filter
set Attribute for name

Appears only when creating mappings!

### Information about your Metabase installation

```JSON
Metabase version v0.49.1 v0.49.4
```

### Severity

low

**Comment by paoliniluis** [comment]
did you complete the port number in the ldap form?

**Comment by CZvacko** [comment]
Yes, the port has been specified, it can also be found in the internal database table (setting).

**Comment by aboydude** [comment]
same here, tested with version 0.49.1 and 0.49.7

**Comment by cabarria** [comment]
We are seeing the same error message on 0.49.11, 0.49.12, 1.49.11, and 1.49.12. We cannot make any changes to LDAP via the web interface, but we can using the API.

**Comment by sloansparger** [comment]
We have a fix on the way, but as a workaround if you re-enter the configured port you should be able to save the form from the web interface.
