### ISSUE TITLE
Configuring sandboxed permissions in schemaless databases removes tables from the list

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#41490]
### Describe the bug

when you open the sandboxing modal to configure permissions on a table in a schemaless db (mysql or sqlite), we lose all tables but the one being edited from the table list. then if you try to reopen the sandboxing modal, the app crashes.

this is likely due to the fact that on the frontend we create "fake" schema under the hood to make the ui work, but the metadata load for this modal is messing with that fiction

### To Reproduce

reproduces on mysql and sqlite

![permsbug](https://github.com/metabase/metabase/assets/30528226/cf42b1d9-0344-4296-913b-755654c9ac4c)

### Expected behavior

it should not remove the table list, and should not crash the app

### Information about your Metabase installation

```JSON
- latest master 2024-04-18
```

### Severity

p3, you can still configure permissions, just 1 table at a time

**Comment by sloansparger** [comment]
I solved this with the permissions UI updates as you can see here. Fix should go out in v50.

https://www.loom.com/share/8ee6e27ac51f4e1795cef31673161715?sid=0db02096-c97e-4c42-9f38-72d4aa79e517
