### ISSUE TITLE
Hovering on legend to see a specific series always shows first series as well

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#41526]
Hovering on the legend for any series other than the first one, incorrectly always shows the first series for some reason. Happens on the question itself and on dashboards. [Internal example](https://stats.metabase.com/question/17107-assigned-tickets).

![Image](https://github.com/metabase/metabase/assets/16455495/ed77c4d5-0aaa-4b75-a848-c1a674071510)

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/41395
