### ISSUE TITLE
No visible alert for users when downloads fail

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#41532]
### Describe the bug

When downloading full data results, if an error occurs, the frontend currently does not display any visible alert to the user, and the downloaded file will be corrupted. 

The error can be anything that interrupts the download - e.g. timeout caused by a slow query, or a Metabase OOM error or instance restart due to a large result set. 

This confuses the user who will likely re-attempt the same download several times before changing their query or giving up.

### To Reproduce

1. Create a native question `select pg_sleep(900) as a, 234 as b` and save it.
2. Open, and download the results (in any format).
3. Wait for the download
... time passes ...
4.(!) After a period (likely due to jetty or proxy timeout), notice that the "spinning circle" disappears and the download icon reappears.
5.(!) The downloaded file does not contain the expected data but an error message instead.

Alternatively, you can just Metabase between steps 3 and 4, no file will be downloaded, yet the frontend will not display any error indication.

### Expected behavior

The user should see a relevant and actionable alert when a download error happens. Ideally, any partially downloaded files should also be removed.

### Logs

Downloaded file contents:
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 AsyncContext timeout</title>
</head>
<body><h2>HTTP ERROR 500 AsyncContext timeout</h2>
<table>
<tr><th>URI:</th><td>/api/card/87/query/xlsx</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>AsyncContext timeout</td></tr>
<tr><th>SERVLET:</th><td>-</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 11.0.20</a><hr/>

</body>
</html>
```

Console error:
```
downloading.ts:171  POST http://localhost:1495/api/card/87/query/xlsx?format_rows=false net::ERR_EMPTY_RESPONSE
```

DB Logs:
```
2024-04-17 15:44:28.173 UTC [20243] LOG:  execute <unnamed>: -- Metabase:: userID: 1 queryType: native queryHash: 1847d12cb0a569a24fe90dec8be60de1c8596700c67f46bad2229998e9cc5b14
        select pg_sleep(900) as a, 234 as b
24~2024-04-17 15:54:30.695 UTC [20243] ERROR:  canceling statement due to user request
```

### Information about your Metabase installation

```JSON
1.49.5
```

### Severity

P2, annoying and affects performance when users repeat their download attempts

**Comment by cdeweyx** [comment]
Partially handled by https://github.com/metabase/metabase/pull/45697 but still remaining is:
1. "any partially downloaded files should also be removed"
