### ISSUE TITLE
 Customer wants Email Links to Redirect to Their Company Page with Embedded Metabase, Not Just Metabase

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#41531]
**Is your feature request related to a problem? Please describe.**
Our customer, who has multiple clients, has integrated Metabase into their company's webpage, which clients access by logging in. They offer subscriptions and want to ensure that when a user clicks on a link in an email from a subscription, it directs them to the company's webpage where Metabase is embedded, instead of leading them directly to Metabase.

This looks to be controlled by a template for subscriptions/pulses.
```
  <div class="footer" style="font-size: 11px; width: max-content; margin: 0 auto">
              Sent from <a href="{{siteUrl}}" style="color: {{applicationColor}}">{{siteUrl}}</a>.
              <a href="{{notificationManagementUrl}}" style="color: {{applicationColor}}">{{notificationText}}</a>
  </div>
```

**Describe alternatives you've considered**
Proxy that will handle the redirect with parameters

**How important is this feature to you?**
This will help the customer maintain a visual and workflow consistency for their end users.

**Additional context**
N/A

**Comment by FilmonK** [comment]
Late but found out about [MB_NOTIFICATION_LINK_BASE_URL](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_notification_link_base_url) however doesn't appear to be working with initial tests. Will test next week and create an issue if need be.

**Comment by ignacio-mb** [comment]
@FilmonK should this be closed as not planned instead as completed?
