### ISSUE TITLE
Control Size of Query Execution Log

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4155]
Some folks are starting to report really big `query_execution` logs, in one case > 5G. 

I think we should do 2 things -

1. Provide an optional log rotation setting that removes logs that are older than X days. This should default to a pretty high setting.
2. Not include raw SQL queries or alternatively gzip them. 
3. Remove unused fields (result_data, result_file, version)

Also , #4154 would be nice here, as we could separate thing where we want to hold onto things for shorter or longer periods

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
We could do something to deduplicate the queries since the whole thing is stored in every entry

**Comment by tlrobinson** [comment]
I think de-duplicating the queries definitions would be the biggest win. We already have `query-hash` we could use as the key.

**Comment by aaronbannin** [comment]
I'm running Metabase on the free tier of Heroku which has a 10k record limit for Postgres. It looks the `query_queryexecution` and `view_log` are taking up the majority of this allocation. Can I safely delete excess records in these tables?

From a user perspective, it might make sense to encapsulate log rotation into a `hobby` vs `pro` setting. Hobby would be much more aggressive about managing space and wouldn't require the user to first learn what the config vars mean.

**Comment by camsaul** [comment]
@aaronbannin you can feel free to `TRUNCATE` those tables and get rid of all the rows until we implement some sort of solution for this issue

**Comment by pybuche** [comment]
Hi !
Is there a way to control this table's size now ? I am not sure this is possible :/

**Comment by flamber** [comment]
Related to #9688

**Comment by rxlky** [comment]
Hi, out of curiosity, what about table query? Is it also safe to truncate this table?

**Comment by camsaul** [comment]
The current `query_execution` Table doesn't have the `result_data`, `result_file`, and `version` rows anymore so that stuff is already done

**Comment by camsaul** [comment]
Also FWIW the `query_execution` table does deduplicate queries as well -- the query itself is stored in the table `query` and `query_execution.hash` is used as an FK to it

**Comment by camsaul** [comment]
So the only one of those things we need to do here is 

> Provide an optional log rotation setting that removes logs that are older than X days. This should default to a pretty high setting.

How high is "pretty high"? 3 months? A year?

**Comment by camsaul** [comment]
For implementing this we'll need to decide on the default value and what sort of granularity we want people to be able to specify (do we want people to be able to choose some number of weeks or months or years? Forever? 1 day?)

Also FWIW deleting query logs after a short period of time is probably a security risk -- e.g. maybe I get unauthorized access and set log retention to 1 minute, and now you won't know what shenanigans I've gotten up to. Do we send admins an email when this value is changed? etc.

**Comment by camsaul** [comment]
Unassigning myself for now until this is shovel-ready. We need product input

**Comment by camsaul** [comment]
Discussion happening in https://www.notion.so/metabase/Keep-query_execution-light-f94dda5477b7473eac7b226306087299 ... we still have some open questions but my intention is to move on this and get it in for 42 once we shake those out

**Comment by camsaul** [comment]
This is shovel-ready now

**Comment by noahmoss** [comment]
Closed by https://github.com/metabase/metabase/pull/28595 and https://github.com/metabase/metabase/pull/28560

**Comment by guneraykut** [comment]
After truncated tables `query_execution` and `view_log`, I got error message at home screen like below


![image](https://github.com/metabase/metabase/assets/21086881/a277961c-b63f-456f-94bc-519bb74b4110)

**Comment by darksciencebase** [comment]
@guneraykut could you please open a new issue about it? https://github.com/metabase/metabase/issues/new/choose and choose "Bug Report"
