### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'dashcards')

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#41563]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6830683/f64322ef-b93b-4201-9746-e33f6c0aa5e1)

### To Reproduce

1. Go to https://stats.metabase.com/
2. Click on Metabase logo in top-left corner of the app (do this until you see the error)
3. Observe JS console

> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'dashcards')

### Expected behavior

No TypeError in JS console

### Information about your Metabase installation

master, 39cf70c

### Severity

P2

**Comment by uladzimirdev** [comment]
similar to https://github.com/metabase/metabase/issues/34699

**Comment by kulyk** [comment]
Closing in favor of https://github.com/metabase/metabase/issues/43800
