### ISSUE TITLE
Indicate whether `dependent-metadata` needs to be called again

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#41568]
Needed for #41520

https://metaboat.slack.com/archives/C051AG38B2S/p1713200875104199

> dependent-metadata needs to be called twice when creating a metric based question. the first time around it would tell to load the metadata of the card, and the second time (when it can look at the metadata of the card), it will tell to load the metadata of the table underlying the metric (card).

----

#### Variant A - new function

```tsx
function hasCompleteMetadata(query: Query): boolean;
```

Alternative name suggestions:
- `hasAllDependentMetadata`
- `hasDependentMetadata`
- `hasAllMetadata`

#### Variant B - enhancing `dependentMetadata` result with this information

```tsx
function dependentMetadata(query: Query): {
  items: DependentItem[];
  hasCompleteMetadata: boolean; // subject to alternative name suggestions from Variant A
};
```

**Comment by metamben** [comment]
Closing in accordance with the discussion in [slack](https://metaboat.slack.com/archives/C0643FZ5E83/p1713452628224769).
