### ISSUE TITLE
Static Embedding doesn't behave like Metabase Application when filter is locked and linked

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#41586]
### Describe the bug

Currently Metabase `!=` Embedding Preview `!=` to Static Embedding ... none of those 3 situations behave the same. This bug will consider Metabase `!=` to Static Embedding

### To Reproduce

So i setup a dashboard with 3 filters all mapping to the column category but the first filter is linked to the second one:

![image](https://github.com/metabase/metabase/assets/110378427/fae84228-46fe-42f3-9114-8776fd1ba02e)

and when I try to filter on the first value (and assigning values to the other filters) using these filters:
(2nd) Text 1: Doohickey
(3rd) Text 2: Gizmo, Gadget

I get the proper results:

![image](https://github.com/metabase/metabase/assets/110378427/5ec8653a-cb76-44f7-995c-75687b8516df)

On the other hand i get completely different behaviour in static embedding. Setup the following locked filters

<img width="289" alt="image" src="https://github.com/metabase/metabase/assets/110378427/de2195f8-2c2b-4363-9a34-3e52d5a858d2">

and check the static embed:

![image](https://github.com/metabase/metabase/assets/110378427/2668fc20-fee4-4ec4-90ff-631004dbc0d7)

My expectation here is that the embedding will show Doohickey since the 2 filters are locked and the second filter is linked with this one .

### Expected behavior

Metabase `=` Static Embedding 

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.49.6
```

### Severity

It's a blocker to me since it makes Static Embedding not working as expected

**Comment by Tony-metabase** [comment]
Also for reference https://github.com/metabase/metabase/issues/37914#issuecomment-1904104979 and https://github.com/metabase/metabase/pull/41342#issuecomment-2061198768

**Comment by WiNloSt** [comment]
I can confirm that the preview and the embed behave differently.

**Comment by Tony-metabase** [comment]
Decided to split this into two ... Changed the description of this one and also opened this one to tackle embedding preview https://github.com/metabase/metabase/issues/41635

**Comment by albertoperdomo** [comment]
@WiNloSt @Tony-metabase Can you help me with repro steps?

The first part of the steps is clear. I get to the point I have the dashboard. I select Doohickey in Text1 and Gizmo, Gadget in Text2. When I open Text I see Doohickey as only option.

What are the steps to embed? Is any of the params Locked? That information seems missing. Also the screenshot shows some JSON. How does it look in the UI?

**Comment by Tony-metabase** [comment]
@albertoperdomo That is my bad because when i split the two issues i took the information on the [other issue ](https://github.com/metabase/metabase/issues/41635)only ... I amended the steps

**Comment by albertoperdomo** [comment]
Thanks @Tony-metabase. The difference I observe is that text filters renders as a text input instead of as a dropdown. Is that it?

**Comment by Tony-metabase** [comment]
Correct but we need to be cautious here because as @WiNloSt mentioned even if it ends up showing a Dropdown filter it's not gonna show `Doohicky` with the linked and locked setup (as we are getting with metabase UI) ... We need to be very cautious here cause we don't want to expose sensitive information which the Locked filter would prevent

**Comment by Tony-metabase** [comment]
Closing since this was a misunderstanding form my part I expected Metabase = Static Embedding but when locked filters and come into place and filters start to work as chained filters. So here metabase is working as expected  and we also got a note on our docs:

 Locked parameters may also limit the values that are shown in your [editable filter widgets](https://www.metabase.com/docs/latest/embedding/static-embedding-parameters#adding-a-filter-widget-to-a-static-embed)
