### ISSUE TITLE
Downloading files on public link, fails when using many filters

### ISSUE THREAD

**Issue by NicolasPLG** [metabase/metabase#41595]
### Describe the bug

When downloading a table with selected filters, it generates a 502 error when it is a public link. However, when using the direct metabase link (no shared link), it downloads correctly.

Attached 502 error
![image](https://github.com/metabase/metabase/assets/61419471/176023fb-c0df-4fe0-9b0b-12a3c5c756fc)

Attached are the filters used
![image](https://github.com/metabase/metabase/assets/61419471/f27aecc7-3082-492e-b80f-90f45a32a2f0)

Attached file error
![image](https://github.com/metabase/metabase/assets/61419471/dc9b9048-9a13-45a5-9752-ceddb667a16c)
<img width="296" alt="image" src="https://github.com/metabase/metabase/assets/61419471/213d2ee1-b707-49f5-bddc-9e372a3c30d1">

We are using the latest version 0.49.6

### To Reproduce

1.- Create a public link with filters and select several in a table.
2.- download
3.- See behavior

### Expected behavior

You should be able to download and open the file without problems.

### Logs

**### NUMBER 1**

[eb9d4870-a313-4a7c-8ab8-8516268b24da] 2024-04-18T12:27:00-04:00 ERROR metabase.driver.util Failed to connect to Database,org.postgresql.util.PSQLException: Connection to pgsql-marfil:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.,	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:346),	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54),	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273),	at org.postgresql.Driver.makeConnection(Driver.java:446),	at org.postgresql.Driver.connect(Driver.java:298),	at java.sql/java.sql.DriverManager.getConnection(Unknown Source),	at java.sql/java.sql.DriverManager.getConnection(Unknown Source),	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271),	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250),	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411),	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:326),	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:323),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__51096.invoke(connection.clj:335),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__51078.invoke(connection.clj:311),	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165),	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:309),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:305),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:334),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:330),	at metabase.driver.sql_jdbc$fn__106731.invokeStatic(sql_jdbc.clj:49),	at metabase.driver.sql_jdbc$fn__106731.invoke(sql_jdbc.clj:47),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at metabase.driver.util$can_connect_with_details_QMARK_$fn__60006.invoke(util.clj:148),	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047),	at clojure.lang.AFn.call(AFn.java:18),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	at java.base/java.lang.Thread.run(Unknown Source),Caused by: java.net.ConnectException: Connection refused (Connection refused),	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method),	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source),	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source),	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source),	at java.base/java.net.SocksSocketImpl.connect(Unknown Source),	at java.base/java.net.Socket.connect(Unknown Source),	at org.postgresql.core.PGStream.createSocket(PGStream.java:243),	at org.postgresql.core.PGStream.<init>(PGStream.java:98),	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136),	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262),	... 36 more

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "es-CL",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.179-168.710.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-16",
      "tag": "v0.49.6",
      "hash": "5abf130"
    },
    "settings": {
      "report-timezone": "America/Santiago"
    }
  }
}
```

### Severity

high

**Comment by paoliniluis** [comment]
can you open the file with a text editor and show the results? the logs you posted say:
"Failed to connect to Database,org.postgresql.util.PSQLException: Connection to pgsql-marfil:5432 refused", which is an error connecting to the database

**Comment by NicolasPLG** [comment]
hello I attach what it tells me in the text editor

----
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by paoliniluis** [comment]
ok so the issue is simply that Metabase can't connect to the database or the database takes too much time to resolve the query, that's why you see a 502... (it's nginx cutting the connection after a long period of time)
