### ISSUE TITLE
When saving a line chart with default settings while viewing data as table it does not persist the defaults for line chart

### ISSUE THREAD

**Issue by JesseSDevaney** [metabase/metabase#41612]
## Description

For line/area/bar/combo/watefall/scatter charts we persist `graph.dimensions` and `graph.metrics` settings because in their definitions persistDefault is true. However, if you toggle raw data view when saving the question these settings defaults won't be saved. As the result this question won't appear compatible with other line charts when trying to combine it in a dashcard.

## Steps to reproduce
- New Orders -> Group by Created at -> Visualize
- At the bottom of the line chart toggle data view
- Save the question as Q1
- Repeat the same steps and save the question as Q2
- Add Q1 on a dashboard and try combine it with Q2
- The list does not show Q2 as a compatible question as well as any timeseries

**Comment by alxnddr** [comment]
Intersting, this modal is showing the list of compatible questions coming from the backend and the ECharts migration should not have changed it 🤔

**Comment by alxnddr** [comment]
@JesseSDevaney the behavior you described in the issue initially could be also reproduced on master so I updated the description of the issue. The spec failures are caused by https://github.com/metabase/metabase/issues/41290 which I'm looking at
