### ISSUE TITLE
`displayInfo` throws on queries using metrics

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#41626]
### Reproduction steps

1. `git checkout metrics-v2`
2. New -> Metric
3. Select Orders table as source
4. Aggregate by Count
5. Run it and Save it
6. Open notebook editor

App crashes, this error is coming from `Lib.displayInfo` when trying to compute the info of the aggregation clause:

```
Error calculating display info for metric: Error calculating display info for metric: Error calculating metadata for :metadata/metric: metabase.lib.schema.expression/type-of: Don't know how to determine the type of {:id 319, :table-id 5, :name "19/04 Metric Orders Count", :description nil, :archived false, :definition {:database 1, :type "query", :query {:source-table 5, :aggregation [["count"]]}}, :lib/type :metadata/metric}
```

### More details

When calling `Lib.toLegacyQuery(query)` on the `query` being passed to `Lib.displayInfo`, it looks like this:
```tsx
{
    "database": 1,
    "type": "query",
    "query": {
        "aggregation": [
            [
                "metric",
                321
            ]
        ],
        "source-table": "card__321"
    }
}
```

The aggregation clause passed to `Lib.displayInfo` looks like this when serialized: ` ['metric', 321]`

**Comment by perivamsi** [comment]
not reproable with the new branch changes, closing it

we can reopen if needed
