### ISSUE TITLE
Uploaded model not showing latest rows appended to the underlying table

### ISSUE THREAD

**Issue by crisptrutski** [metabase/metabase#41630]
### Describe the bug

When appending new rows to an existing Uploaded model it can appear that the action "succeeds" but no new data is actually added. This appears to be an issue with the model however, the underlying table appears to be updated as expected. Perhaps this is a caching issue?

This is sporadic issue and hard to reproduce, but one a given model is being affected the issue persists even when additional appends are made.

You can see the issue in action during [this portion of the Metabase 49 webinar](https://youtu.be/iig0-CoZLbw?si=irWaWpHZMdo7b2LV&t=1358). 🙈 

### To Reproduce

1. Go to [this uploaded model](https://stats.metabase.com/model/17094-pixarmovies)
2. Notice that 27 rows are being shown.
3. Append this file: [Pixar Movies(2).csv](https://github.com/metabase/metabase/files/15038812/Pixar.Movies.2.csv)
4. Wait for upload to succeed and model to refresh.
5. Notice that there are still only 27 rows being shown, i.e. it looks like nothing was appended.
6. Go to a [question that queries the underlying model directly](https://stats.metabase.com/question/17191-pixarmovies-direct-query-to-20240415131022/notebook).
7. Notice that there are a bunch of extra rows, a bunch of duplicates from the file above being appended multiple times.

Converting the model into a native question also appears to resolve the issue.

### Expected behavior

I expect the model to display all the newly appended rows after the upload succeeds.

### Information about your Metabase installation

```JSON
- Server: stats.metabase.com 
- Built on: 2024-04-17
- Commit: 39cf70c
- Version: pre-50.0
```

### Severity

P2

**Comment by crisptrutski** [comment]
Interestingly enough the "stale" results are not cached according to the server response.

![Screenshot 2024-04-19 at 13 31 40](https://github.com/metabase/metabase/assets/881351/70d07d0f-dafe-4642-a581-793466c00128)

**Comment by crisptrutski** [comment]
@camsaul Do you have any idea why we're getting stale data when querying the model?

```sql
select table_id, dataset_query from report_card where id = 17094;
```
table_id | dataset_query
--|--
50008 | `{"database":26,"query":{"source-table":50008},"type":"query"}`

Yet when we process the queries:

Query | Row count
--|--
`{"source-table": "card__17094"}` | 27
`{"source-table": 50008}`| 60

**Comment by calherries** [comment]
From slack:

This is an issue with using CSV uploads with model caching turned on.

This is what I did:
1. I went to [this uploaded model](https://stats.metabase.com/model/17094-pixarmovies)
2. Noticed that 27 rows are being shown.
 3.  Turned off model caching. There’s now 60 rows

So the issue is with uploads, because model caching is working as expected. We should know to invalidate the model’s cache when a user uploads the rows to a table.

It’s a little complicated because we’d need to get the models that use the table, because append/replace are table APIs, not model ones. That’s relatively simple to do because we only need to invalidate models where the upload table is the base table for the model, and we can use `report_card.table_id`.

**Comment by crisptrutski** [comment]
Nice, good to know it's a fairly isolated issue. 

I'm not sure that busting caches when we upload is the right call, there's another part of me that thinks it's very strange to automatically cache "no-op" models if that wouldn't give a perf benefit. There are at least three ways to fix it that I see:

1. Cache busting.
2. Being more selective about when models get automatic caching.
3. Being more selective about when the cache is actually created / QP actually uses it.

There are pros and cons with each, going to chat to @luizarakaki about it.

**Comment by crisptrutski** [comment]
While (3) is quite attractive in some ways, it's a much lower level change. Option (1) is very localized and can be done internally by our team, and directly targets the user pain, so we're starting there - at least for patching 49.

**Comment by calherries** [comment]
For reference, we have a similar problem with actions and model caching https://github.com/metabase/metabase/issues/33149
