### ISSUE TITLE
Embedding Preview doesn't behave like Metabase Application when filter is locked and linked

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#41635]
### Describe the bug

Currently Metabase `!=` Embedding Preview `!=` to Static Embedding ... none of those 3 situations behave the same. This bug will consider Metabase `!=` Embedding Preview

### To Reproduce

So i setup a dashboard with 3 filters all mapping to the column category but the first filter is linked to the second one:

![image](https://github.com/metabase/metabase/assets/110378427/fae84228-46fe-42f3-9114-8776fd1ba02e)

and when I try to filter on the first value (and assigning values to the other filters) using these filters:
(2nd) Text 1: Doohickey
(3rd) Text 2: Gizmo, Gadget

I get the proper results:

![image](https://github.com/metabase/metabase/assets/110378427/5ec8653a-cb76-44f7-995c-75687b8516df)

On the other hand i get completely different behaviour in preview embedding

![image](https://github.com/metabase/metabase/assets/110378427/e279db17-0ab8-46e9-8ed2-f18fee020479)

### Expected behavior

Metabase = Embedding Preview

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.49.6
```

### Severity

Cosmetic because it's just at preview level

### Additional context

Similar to https://github.com/metabase/metabase/issues/41586

**Comment by WiNloSt** [comment]
Since this issue is split from #41586. I'll repost [my comment](https://github.com/metabase/metabase/issues/41586#issuecomment-2066053566) which was specifically for the preview issue.

> I can confirm that the preview and the embed behave differently. I updated the issue description with proper filter values to reproduce the issue. You need to set (3rd) Text 2 filter to have any values except Doohicky for this to happen.
> 
> The difference in the behavior is that when we query on preview, we call `GET /api/dashboard/:id/params/:param-key/values` to get the values. This would behave differently from when we're actually call on the dashboard since it would pass the linked parameter in the URL `GET /api/dashboard/:id/params/:param-key/values?:linked-param-key=Doohickey`.
> 
> When we call this on embed it's `GET /api/embed/dashboard/:jwt/params/:param-key/values`. And BE could use the parameter values inside the :jwt filter proper results.
> 
> I think what we should do here is to add an equivalent endpoint in [`preview_embed`](https://github.com/metabase/metabase/blob/2ab84940ed15658a35a50049f260c688409c71c3/src/metabase/api/preview_embed.clj) endpoint so we could call `GET /api/preview_embed/dashboard/:jwt/params/:param-key/values` instead of using the dashboard endpoint.
