### ISSUE TITLE
Token activation error persists, even after connectivity is restored

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#41654]
### Describe the bug

If a license activation attempt fails because token-check.metabase.com is not reachable or anything else prevents the token check API to be called, subsequent activation attempts continue to fail with the same error, even after the connectivity is restored. 
The issue persists until Metabase is restarted.

### To Reproduce

1. Set up a new instance
2. Disable connectivity to the token-check API (I just turned off my wifi connection while running Metabase locally)
3. In Admin Settings / Licencing, enter a valid token, and click Activate
4. Activation will time out
5. Now restore the connectivity
6. Try to activate the same token again
7.(!) The same validation timeout error occurs. 
The validation error will persist until Metabase is restarted.

### Expected behavior

Validation should be successful once the connectivity is restored.

### Logs

2024-04-19 17:38:58,209 DEBUG middleware.log :: GET /api/setting 200 47.0 ms (15 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (4 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
2024-04-19 17:38:58,250 WARN middleware.log :: GET /api/premium-features/token/status 404 1.5 ms (0 DB calls)
"Not found."
2024-04-19 17:39:04,645 ERROR public-settings.premium-features :: Error setting premium features token
clojure.lang.ExceptionInfo: Unable to validate token {:status-code 400, :error-details "Token validation timed out."}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.1.75-0-virt",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-16",
      "tag": "v1.49.6",
      "hash": "5abf130"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2 - rare but confusing

**Comment by paoliniluis** [comment]
@zbodi74 is this JAR or Docker?

**Comment by zbodi74** [comment]
@paoliniluis, I noticed this with Docker.

**Comment by paoliniluis** [comment]
@zbodi74 check with the JAR then as this "might" be the docker layer being nasty

**Comment by zbodi74** [comment]
This problem also affects JAR deployments.
Additionally, it isn't limited to network errors. It can be triggered by any factor that prevents token validation. For instance, a customer faced a temporary certificate issue—likely due to the Java certificate store being refreshed. This resulted in an error {:message "Unable to validate token", :status-code 400, :error-details "the trustAnchors parameter must be non-empty"} that got resolved by restarting Metabase.
However it appears, the next successful periodic token also resolves the issue.
