### ISSUE TITLE
Druid: Naming collision when having multiple aggregation

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#4166]
Hi guys,

Great work on the Math aggregation feature ! its pretty awesome :)

In druid queries you need to name aggregations. In the driver this constant(eg. sum) so when having more that one aggregation this creates few issues :)

Steps to reproduce:

1. select a Druid table
2. select sum of something
3. select another sum of something else
4. run query

Error message
Instantiation of [simple type, class io.druid.query.timeseries.TimeseriesQuery] value failed: [sum] already defined

**Comment by camsaul** [comment]
Basically the same issue as #4089 (for BigQuery)

**Comment by Dadard** [comment]
Hello,

I think this issue has been fixed for BigQuery but is still present for druid.

I think this is basic feature and it is a shame that it is not working atm.

Do you plan to deal with this anytime soon ?

**Comment by Digma** [comment]
Can confirm still failing with Druid and Metabase 0.28.3. The error messae is 

> java.lang.Exception: Unknown exception

**Comment by aerendil** [comment]
Hello guys,

Wrote a quick patch for this, not sure if it's the good solution or elegant or what not as this is my first time with Clojure or any functional language.

`diff --git a/src/metabase/driver/druid/query_processor.clj b/src/metabase/driver/druid/query_processor.clj
index 3a4de54ae..f7714107e 100644
--- a/src/metabase/driver/druid/query_processor.clj
+++ b/src/metabase/driver/druid/query_processor.clj
@@ -258,7 +258,8 @@
                                                      {:type :fieldAccess, :fieldName count-name}]}]}])
       [:distinct _] [[(or output-name-kwd :distinct___count)]
                      {:aggregations [(ag:distinct ag-field (or output-name :distinct___count))]}]
-      [:sum      _] [[(or output-name-kwd :sum)] {:aggregations [(ag:doubleSum ag-field (or output-name :sum))]}]
+      [:sum      _] (let [sum-name (name (str "sum_" (->rvalue ag-field)))]
+                      [[(keyword sum-name) (or output-name-kwd :sum)] {:aggregations [(ag:doubleSum ag-field sum-name)]}])
       [:min      _] [[(or output-name-kwd :min)] {:aggregations [(ag:doubleMin ag-field (or output-name :min))]}]
       [:max      _] [[(or output-name-kwd :max)] {:aggregations [(ag:doubleMax ag-field (or output-name :max))]}])))
 
@@ -887,7 +888,7 @@
   "Remove keys that start with `___` from the results -- they were temporary, and we don't want to return them."
   [columns]
   (let [keys-to-remove (for [k     columns
-                             :when (re-find #"^___" (name k))]
+                             :when (or (re-find #"^___" (name k)) (re-find #"^sum$" (name k)))]
                          k)]
     (if-not (seq keys-to-remove)
       columns`

**Comment by petit-pois** [comment]
Hi guys any progress on this ?

**Comment by camsaul** [comment]
Related issue for MongoDB: #5393

**Comment by camsaul** [comment]
Fixed by #8987
