### ISSUE TITLE
Create an ENV Variable that allows you to setup when a query would timeout

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#41685]
**Is your feature request related to a problem? Please describe.**
I would like to execute queries that take more than 20 minutes. Currently we have hardcoded 20 minutes in our code [more than 20 min](https://github.com/metabase/metabase/blob/68fc6f4477bd0887bb131cbce2aec03b639a7000/src/metabase/query_processor/pipeline.clj#L100)

**Describe the solution you'd like**
An ENV Variable that would control this value so i can reduce or increase a query timeout

**Describe alternatives you've considered**
Forking the code and changing this directly

**Comment by Timelessprod** [comment]
Would be a much appreciated feature when unpacking JSON payloads which takes time
