### ISSUE TITLE
Sample Database doesn't start with any perms (on master)

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#41701]
### Describe the bug

Sample database doesn't start with any permissions when you start up a new instance of Metabase.

### To Reproduce

1. Start up Metabase with a fresh application database
2. View permissions for sample database

### Information about your Metabase installation

```JSON
Current master
```

### Severity

n/a

**Comment by calherries** [comment]
This doesn't require a milestone since it was only a regression on master
