### ISSUE TITLE
'Custom Expression' aggregate names not capitalized

### ISSUE THREAD

**Issue by Hennisa** [metabase/metabase#4171]
Browser and the version: Chrome 53.0.2785.143 (64-bit)
Operating system: OS X 10.11.6
DB: Redshift
Metabase internal database: Postgres
Metabase version 0.22.0
Metabase hosting environment: Elastic Beanstalk

I've set up names for custom aggregates with capital letters but they are not capitalized in the visualization:

<img width="1244" alt="screen shot 2017-01-16 at 17 50 06" src="https://cloud.githubusercontent.com/assets/14327271/21992160/b8f1806e-dc15-11e6-9390-ae8d75fea98d.png">

**Comment by camsaul** [comment]
Unfortunately Redshift automatically lowercases all column aliases when you run a query.

**Comment by flamber** [comment]
Not sure when this was fixed, but on 0.35.3:
![image](https://user-images.githubusercontent.com/1447303/82846143-be908e00-9ee7-11ea-9a21-efd850c46fbf.png)
