### ISSUE TITLE
Cannot find the new column in pick columns after alter schema and synced

### ISSUE THREAD

**Issue by jodotlearn** [metabase/metabase#41765]
### Describe the bug

alter a table's schema to add a new column and sync schema manually in admin settings
we can see the new column when browse data  
![image](https://github.com/metabase/metabase/assets/8278560/3d170e0b-a8a4-46f1-912d-00b06caccbd7)
  
but pick columns in editor cannot see the new column  
![image](https://github.com/metabase/metabase/assets/8278560/d6d073e2-f457-4ba3-8733-7f5b0f1665d4)

although we can tell users to refresh or logout, but it's strange, especially users can see the new column in data but cannot pick the column in editor.

### To Reproduce

1. [DB] add a new column in a table which already synced in metabase
2. [Metabase] sync schema in admin settings
3. [Metabase] New a question and choose the table from raw data
4. [Metabase] click pick columns then can reporduce the issue

### Information about your Metabase installation

```JSON
- Metabase version: v0.49.4
- Database: PostgreSQL
```

### Severity

blocking users

**Comment by paoliniluis** [comment]
Can you do a full browser refresh on the GUI editor?

**Comment by jodotlearn** [comment]
> Can you do a full browser refresh on the GUI editor?

works fine if do full browser refresh on the GUI editor.
