### ISSUE TITLE
Support PostGIS geometry columns

### ISSUE THREAD

**Issue by timiyay** [metabase/metabase#4177]
### Feature requests and proposals

I've trialled the Mac version of Metabase, trying to create a map using PostGIS geometry columns. The geometry columns weren't accepted by Metabase.

I would like to see one or more of the following features:

1. recognise PostGIS `geometry` columns for use in the `Region` field of a map visualisation
2. allow a custom SQL function to be entered, to compute the geometry value

Feature 1 would be a user-friendly way to get started with PostGIS visualisations.

Feature 2 would enable the use of `ST_AsGeojson(geom)` to export the format that Metabase expects. Arguably, a SQL view is more appropriate here.

**Comment by camsaul** [comment]
Duplicate of #2327
