### ISSUE TITLE
Allow Metabase to not have a login screen, or alternative to allow authentication on the network level.

### ISSUE THREAD

**Issue by MrChadMWood** [metabase/metabase#41789]
**Feature Request**

**Is your feature request related to a problem? Please describe.**
Authentication to occur on the network with Single Sign-on via an Identity Platform, outside of Metabase's scope. A reverse proxy would handle access via authentication/authorization. In effect, if a user gets to Metabase that means they're allowed to be there.

Alternatively, *I think* JWT can be used to achieve a similar effect with some re-directs in the middle.

**Describe the solution you'd like**
I'd like if a Metabase administrator had the option to disable users. Every user could be considered a "Guest". 

**Describe alternatives you've considered**
Alternatively, if JWT authentication was available that could work too. An unauthorized user would visit Metabase, get redirected to the SSO portal, and the SSO portal could recognize the user as already being authorized- thus forwarding the visitor back with a auth-token in the URL.

**How important is this feature to you?**
5/10. Right now, user adoption rate among nontechnical stakeholders is quite low and I believe this would improve that metric. 

**Additional context**
I see JWT is available on the Pro offering. This is a great offer with a large variety of great features, though we aren't at the stage where we can justify the $500/mo for everything included in the package. I believe having easier access can more quickly get us to higher adoption rates.

**Comment by paoliniluis** [comment]
Duplicate/similar of https://github.com/metabase/metabase/issues/6709
