### ISSUE TITLE
Using Column picker to remove columns on model breaks question with ERROR: column source.name_2 does not exist   Position

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#41785]
### Describe the bug

Using the Add or Remove Columns picker breaks question and shows unexpected duplicated values in list of columns

### To Reproduce

1. Visit https://stats.metabase.com/model/6759-ticket
2. Click the ⚙️ gear icon on bottom left to edit Visualization Settings
3. Click `Add or Remove Columns`
4. Uncheck "Assignee ID" (3rd from last column)
![image](https://github.com/metabase/metabase/assets/8808703/3666b89e-295f-4d60-b390-e8e0887a8726)

5. See error `ERROR: column source.name_2 does not exist  Position: 1703`

https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyNiwidHlwZSI6InF1ZXJ5IiwicXVlcnkiOnsiZmllbGRzIjpbWyJmaWVsZCIsImlkIix7ImJhc2UtdHlwZSI6InR5cGUvQmlnSW50ZWdlciJ9XSxbImZpZWxkIiwic3ViamVjdCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJmaWVsZCIsIm9yZ2FuaXphdGlvbl9uYW1lIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwiYXNzaWduZWVfbmFtZSIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJmaWVsZCIsInJlcXVlc3Rlcl9lbWFpbCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJmaWVsZCIsImRvbWFpbiIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJmaWVsZCIsImNyZWF0ZWRfYXQiLHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIn1dLFsiZmllbGQiLCJhc3NpZ25lZV91cGRhdGVkX2F0Iix7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWVXaXRoTG9jYWxUWiJ9XSxbImZpZWxkIiwidXBkYXRlZF9hdCIseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lV2l0aExvY2FsVFoifV0sWyJmaWVsZCIsInN1cnZleV9jcmVhdGVkX2F0Iix7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWVXaXRoTG9jYWxUWiJ9XSxbImZpZWxkIiwiYXNzaWduZWVfZ3JvdXBfbmFtZSIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJmaWVsZCIsImlzX29wZW4iLHsiYmFzZS10eXBlIjoidHlwZS9Cb29sZWFuIn1dLFsiZmllbGQiLCJzdGF0dXMiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJ0aWNrZXRfcmVhc29uIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwiYml6X29wc19hcmVhIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwicHJvZHVjdF9hcmVhIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwic2VudF9zdXJ2ZXkiLHsiYmFzZS10eXBlIjoidHlwZS9Cb29sZWFuIn1dLFsiZmllbGQiLCJzYXRpc2ZhY3Rpb25fcmF0aW5nX3Njb3JlIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwic2F0aXNmYWN0aW9uX3JhdGluZ19jb21tZW50Iix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwidmlhX2NoYW5uZWwiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJyZWNpcGllbnQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJzdWJtaXR0ZXJfbmFtZSIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJmaWVsZCIsImhhc19pbmNpZGVudHMiLHsiYmFzZS10eXBlIjoidHlwZS9Cb29sZWFuIn1dLFsiZmllbGQiLCJwcm9ibGVtX2lkIix7ImJhc2UtdHlwZSI6InR5cGUvQmlnSW50ZWdlciJ9XSxbImZpZWxkIiwidXJsIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwiZGVzY3JpcHRpb24iLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJvcmdhbml6YXRpb25faWQiLHsiYmFzZS10eXBlIjoidHlwZS9CaWdJbnRlZ2VyIn1dLFsiZmllbGQiLCJjdXN0b21lcl9pZCIseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIifV0sWyJmaWVsZCIsImFjY291bnRfaWQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJncm91cF9pZCIseyJiYXNlLXR5cGUiOiJ0eXBlL0JpZ0ludGVnZXIifV0sWyJmaWVsZCIsImFzc2lnbmVlX2lkIix7ImJhc2UtdHlwZSI6InR5cGUvQmlnSW50ZWdlciJ9XSxbImZpZWxkIiwicmVxdWVzdGVyX2lkIix7ImJhc2UtdHlwZSI6InR5cGUvQmlnSW50ZWdlciJ9XSxbImZpZWxkIiwic3VibWl0dGVyX2lkIix7ImJhc2UtdHlwZSI6InR5cGUvQmlnSW50ZWdlciJ9XSxbImZpZWxkIiwic2F0aXNmYWN0aW9uX3JhdGluZ19pZCIseyJiYXNlLXR5cGUiOiJ0eXBlL0JpZ0ludGVnZXIifV0sWyJmaWVsZCIsImVtYWlsIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwibmFtZV8yIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XV0sInNvdXJjZS10YWJsZSI6ImNhcmRfXzY3NTkifX0sImRpc3BsYXkiOiJ0YWJsZSIsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLnBpdm90X2NvbHVtbiI6ImJpel9vcHNfYXJlYSIsInRhYmxlLmNlbGxfY29sdW1uIjoicHJvYmxlbV9pZCIsInRhYmxlLmNvbHVtbnMiOlt7Im5hbWUiOiJpZCIsImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNTQ3ODAzLG51bGxdXSIsImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NDc4MDMsbnVsbF19LHsibmFtZSI6InN1YmplY3QiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgxMCxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODEwLG51bGxdfSx7Im5hbWUiOiJvcmdhbml6YXRpb25fbmFtZSIsImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNTQ3ODI1LG51bGxdXSIsImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NDc4MjUsbnVsbF19LHsibmFtZSI6ImFzc2lnbmVlX25hbWUiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgzMixudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODMyLG51bGxdfSx7Im5hbWUiOiJyZXF1ZXN0ZXJfZW1haWwiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgyNyxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODI3LG51bGxdfSx7Im5hbWUiOiJkb21haW4iLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU1OTQxOCxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTU5NDE4LG51bGxdfSx7Im5hbWUiOiJjcmVhdGVkX2F0Iiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MTYsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgxNix7InRlbXBvcmFsLXVuaXQiOiJkZWZhdWx0In1dfSx7Im5hbWUiOiJhc3NpZ25lZV91cGRhdGVkX2F0Iiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MTQsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgxNCx7InRlbXBvcmFsLXVuaXQiOiJkZWZhdWx0In1dfSx7Im5hbWUiOiJ1cGRhdGVkX2F0Iiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MTIsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgxMix7InRlbXBvcmFsLXVuaXQiOiJkZWZhdWx0In1dfSx7Im5hbWUiOiJzdXJ2ZXlfY3JlYXRlZF9hdCIsImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNTU5NDE5LG51bGxdXSIsImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NTk0MTkseyJ0ZW1wb3JhbC11bml0IjoiZGVmYXVsdCJ9XX0seyJuYW1lIjoiYXNzaWduZWVfZ3JvdXBfbmFtZSIsImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNTQ3ODMzLG51bGxdXSIsImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NDc4MzMsbnVsbF19LHsibmFtZSI6ImlzX29wZW4iLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgxOSxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODE5LG51bGxdfSx7Im5hbWUiOiJzdGF0dXMiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgxNSxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODE1LG51bGxdfSx7Im5hbWUiOiJ0aWNrZXRfcmVhc29uIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MjYsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgyNixudWxsXX0seyJuYW1lIjoiYml6X29wc19hcmVhIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MjQsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgyNCxudWxsXX0seyJuYW1lIjoicHJvZHVjdF9hcmVhIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MjEsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgyMSxudWxsXX0seyJuYW1lIjoic2VudF9zdXJ2ZXkiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgxOCxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODE4LG51bGxdfSx7Im5hbWUiOiJzYXRpc2ZhY3Rpb25fcmF0aW5nX3Njb3JlIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MDUsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgwNSxudWxsXX0seyJuYW1lIjoic2F0aXNmYWN0aW9uX3JhdGluZ19jb21tZW50Iiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MDksbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgwOSxudWxsXX0seyJuYW1lIjoidmlhX2NoYW5uZWwiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgyMixudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODIyLG51bGxdfSx7Im5hbWUiOiJyZWNpcGllbnQiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgwOCxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODA4LG51bGxdfSx7Im5hbWUiOiJzdWJtaXR0ZXJfbmFtZSIsImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNTQ3ODA0LG51bGxdXSIsImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NDc4MDQsbnVsbF19LHsibmFtZSI6Imhhc19pbmNpZGVudHMiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgzMCxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODMwLG51bGxdfSx7Im5hbWUiOiJwcm9ibGVtX2lkIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MjgsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgyOCxudWxsXX0seyJuYW1lIjoidXJsIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MTcsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgxNyxudWxsXX0seyJuYW1lIjoiZGVzY3JpcHRpb24iLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgwNixudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODA2LG51bGxdfSx7Im5hbWUiOiJvcmdhbml6YXRpb25faWQiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU0NzgzMSxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTQ3ODMxLG51bGxdfSx7Im5hbWUiOiJjdXN0b21lcl9pZCIsImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNTQ3ODIzLG51bGxdXSIsImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NDc4MjMsbnVsbF19LHsibmFtZSI6ImFjY291bnRfaWQiLCJrZXkiOiJbXCJyZWZcIixbXCJmaWVsZFwiLDU2OTk0NyxudWxsXV0iLCJlbmFibGVkIjp0cnVlLCJmaWVsZFJlZiI6WyJmaWVsZCIsNTY5OTQ3LG51bGxdfSx7Im5hbWUiOiJncm91cF9pZCIsImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNTQ3ODI5LG51bGxdXSIsImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NDc4MjksbnVsbF19LHsibmFtZSI6ImFzc2lnbmVlX2lkIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MjAsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgyMCxudWxsXX0seyJuYW1lIjoicmVxdWVzdGVyX2lkIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MTEsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgxMSxudWxsXX0seyJuYW1lIjoic3VibWl0dGVyX2lkIiwia2V5IjoiW1wicmVmXCIsW1wiZmllbGRcIiw1NDc4MDcsbnVsbF1dIiwiZW5hYmxlZCI6dHJ1ZSwiZmllbGRSZWYiOlsiZmllbGQiLDU0NzgwNyxudWxsXX0seyJuYW1lIjoic2F0aXNmYWN0aW9uX3JhdGluZ19pZCIsImtleSI6IltcInJlZlwiLFtcImZpZWxkXCIsNTQ3ODEzLG51bGxdXSIsImVuYWJsZWQiOnRydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NDc4MTMsbnVsbF19XX0sIm9yaWdpbmFsX2NhcmRfaWQiOjY3NTl9ydWUsImZpZWxkUmVmIjpbImZpZWxkIiw1NDc4MTMsbnVsbF19XX0sIm9yaWdpbmFsX2NhcmRfaWQiOjY3NTl9

### Expected behavior

- expect to be able to uncheck/check
- expect only one Assignee ID to show up

### Logs

![image](https://github.com/metabase/metabase/assets/8808703/4f648407-e993-40e0-a0a7-38368a875fad)

Diagnostics:
- https://drive.google.com/file/d/13yt2TeuQ74VjijT660rf65h-7e0-rltL/view?usp=drive_link

### Information about your Metabase installation

```JSON
- `master` as of `9e9e310`
```

### Severity

P1: Regression, commonly used functionality

**Comment by nemanjaglumac** [comment]
@likeshumidity this error message seems to point to the backend issue.
What's interesting is that the Assignee ID shows up three times in the sidebar when you click "Add or remove columns"
![Screenshot 2024-06-04 at 15 47 37](https://github.com/metabase/metabase/assets/31325167/9c016f3d-21cc-4be8-b6b6-fecb50c8ced6)

I'm wondering how did it come to that?
The source of this issue most likely lies in the model definition.

**Comment by kamilmielnik** [comment]
Fixed by #44721
