### ISSUE TITLE
[dc.js migration] missing combined card in subscription

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#41787]
https://github.com/metabase/metabase/assets/37751258/45d2fe78-0e04-46d4-9d68-aa033137bf7a

When I add a series to combine two questions in to a single dashcard, in the subscription email I only see a single series on the chart. Furthermore, the chart title in the email is from the first question, yet the series being rendered is the second question, albeit with the first series color.

**Comment by dpsutton** [comment]
This [commit](https://github.com/metabase/metabase/pull/41395/commits/25ec412bb196ed14e943392090da30ea0aa992c1?file-filters%5B%5D=.clj&show-viewed-files=true#diff-79c051a13f9e859c56dc5bffd3f145bb696e2da951d6ff45dc1fa38d4a3b9807) in the [echarts PR](https://github.com/metabase/metabase/pull/41395) stopped using `data`.

#### Before:
```clojure
(s/defmethod render :javascript_visualization :- formatter/RenderedPulseCard
  [_chart-type render-type _timezone-id card dashcard data]
  (let [combined-cards-results                 (if dashcard
                                                 (pu/execute-multi-card card dashcard)
                                                 (pu/execute-card {:creator_id (:creator_id card)} (:id card)))
        cards-with-data                        (map (fn [c d] {:card c :data d})
                                                    (cons card (map :card combined-cards-results))
                                                    (cons data (map #(get-in % [:result :data]) combined-cards-results))) ;; data blended here
        dashcard-viz-settings                  (get dashcard :visualization_settings)
        {rendered-type :type content :content} (js-svg/javascript-visualization cards-with-data dashcard-viz-settings)]
```

#### After

```clojure
(mu/defmethod render :javascript_visualization :- formatter/RenderedPulseCard
  [_chart-type render-type _timezone-id card dashcard _data]
  (let [combined-cards-results (if dashcard
                                 (pu/execute-multi-card card dashcard)
                                 [(pu/execute-card {:creator_id (:creator_id card)} (:id card))])
        cards-with-data        (map
                                (comp
                                 add-dashcard-timeline-events
                                 (fn [c d] {:card c :data d}))
                                (map :card combined-cards-results)
                                (map #(get-in % [:result :data]) combined-cards-results))
```

The `data` coming into this function has the results of the base card. The error here is that `pu/execute-multi-card` sounds like it will the base card in addition to the series, but it seems it only runs the series and the caller has to manually blend the two. Seems a simple fix.
