### ISSUE TITLE
Tile maps are visualizations are broken

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#41794]
### Describe the bug

**Broken only on Stats**

Tile maps aren't loading correct tiles:

<img width="1726" alt="Screenshot 2024-04-24 at 3 31 57 PM" src="https://github.com/metabase/metabase/assets/14301985/2941a271-e687-4883-8552-134bcfe95208">

### To Reproduce

1. New Question -> People table -> switch to the map view
2. Ensure latitude and longitude are set
3. See the map is not loaded: tiles are empty but data points are visible

### Information about your Metabase installation

```JSON
Stats, latest master
```

### Severity

Very high

**Comment by kulyk** [comment]
Turned out to be a misconfig on stats. `map-tile-server-url` setting was set to a US states geojson for some reason
