### ISSUE TITLE
Wrong ticks in bar/line charts

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#4180]
Hi 

When i select a count of rows by day for past x days the **ticks** in the bar charts are off by 1 day. The **tooltips** on the other hand are correct.
 
Happens on sample dataset and druid. 
Noticed in 0.21 and 0.22

![ticks](https://cloud.githubusercontent.com/assets/1543669/22039650/685fac0c-dd00-11e6-9a60-54ffb9912385.png)

Report timezone: Europe/brussels 

- Your browser and the version: firefox 50.0.2 and chrome
- Your operating system:OS X 
- Your databases: Sample dataset / druid
- Metabase version: 0.22
- Metabase hosting environment: Linux
- Metabase internal database:  MySQL

**Comment by salsakran** [comment]
Can you give us the query on the sample dataset you're using and the server timezone, reporting timezone + browser timezone you're on?

**Comment by salsakran** [comment]
bump @moumny 

You mentioned that this happened with the sample dataset. We're going over as many timezone bugs this micro-cycle as we can, and it would be very helpful to get 
- The query,
- Your server timezone
- Your browser timezone

**Comment by moumny** [comment]
Metabase timezone: Europe/Brussels  
Server Time zone: Europe/Zurich (CEST, +0200)  
Server RHEL7 
Browser timezone Europe/Zurich

query sample dataset -> past 7 days -> sum of something -> group by day

**Comment by EvaSchreyer** [comment]
Hi, 
I still have this issue (not only day to day but also month on month is wrong). I work with metabase v0.25.1 and its shown correct when I do a row chart but wrong when I do a bar chart. 
Would be great if that could be solved soon. 
The funny thing is (you can see my SQL syntax below) I even concat month and year to avoid the wrong labeling and metabase still tries to be clever and shows me the wrong date label. 

That is my query:
SELECT concat(bi_donation_values.donation_created_at_year_local, '-', bi_donation_values.donation_created_at_month_local) AS Spendendatum, 
sum(`bi_donation_values`.`amount_in_cents`)/1000 AS  Volumen
FROM `bi_donation_values`
left join bi_client_member_values on (bi_client_member_values.client_member_member_identifier = bi_donation_values.receiver_identifier)
left join bi_project_values on (bi_project_values.identifier = bi_donation_values.receiver_identifier)
WHERE bi_donation_values.receiver_type = "Project"
   and bi_project_values.tracking_via = {{var}}
    AND bi_client_member_values.client_member_client_identifier [[LIKE CONCAT ('%',{{var}},'%')]]
    AND bi_project_values.confirmed_clients_list [[LIKE CONCAT ('%',{{var}},'%')]]
    AND bi_donation_values.donation_status = "confirmed"
    And str_to_date(concat(date_format(`bi_donation_values`.`donation_created_at_local`, '%Y-%m'), '-01'), '%Y-%m') BETWEEN str_to_date(concat(date_format(date_add(now(), INTERVAL -12 month), '%Y-%m'), '-01'), '%Y-%m')
    AND str_to_date(concat(date_format(date_add(now(), INTERVAL -1 month), '%Y-%m'), '-01'), '%Y-%m')
GROUP BY Spendendatum

**Comment by mazameli** [comment]
This issue should be resolved in version 0.26. You can test out the release candidate, and we plan to ship the actual release this week.

**Comment by EvaSchreyer** [comment]
great, thanks Maz! Will update and have a look!
Cheers, Eva

**Comment by moumny** [comment]
works on master !
