### ISSUE TITLE
Issues connecting to Snowflake using RSA Keypair Authentication

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#41852]
### Describe the bug

1.) We can not setup a connection to Snowflake using just a user account and private key. You'll receive the following:

> Private key provided is invalid or not supported: /private/var/folders/4r/57lvgm8n4xd4fw3cmtlr3p000000gn/T/metabase-secret_4618509373001869555.tmp: java.security.InvalidKeyException: IOException : DER input, Integer tag error

<br>

2.) Once a connection to Snowflake has been setup by entering a password along with a private key, we're using password for the primary authentication factor.

### To Reproduce

1.) I went through the steps provided in the following article and tested using a non encrypted and encrypted key.
https://docs.snowflake.com/en/user-guide/key-pair-auth

<br>

2.) I setup a database connection to Snowflake within Metabase without a password to receive the error:
> Private key provided is invalid or not supported: /private/var/folders/4r/57lvgm8n4xd4fw3cmtlr3p000000gn/T/metabase-secret_4618509373001869555.tmp: java.security.InvalidKeyException: IOException : DER input, Integer tag error

<br>

3.) I proceeded to add a password to the database setup in Metabase in order to establish connectivity to Snowflake

<br>

4.) I  confirmed the public fingerprint being used for the account in Snowflake and public key matches.
```
DESC USER <my user account>;
SELECT TRIM((SELECT "value" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
  WHERE "property" = 'RSA_PUBLIC_KEY_FP'), 'SHA256:');
```

<br>

5.) I created a Node app using the example from[ Snowflake for Node app](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-authenticate#label-nodejs-key-pair-authentication) to test connectivity.

<br>

6.) Used the following query to show login history and the difference between Metabase and the Node app. 

```
SELECT *
FROM TABLE(snowflake.information_schema.login_history_by_user(USER_NAME => '<your user account>', result_limit => 10))
ORDER BY event_timestamp DESC;
```
<br>

Note the Node app using RSA Key pair for the primary authentication factor

<br>

<img width="804" alt="Screenshot 2024-04-22 at 11 05 36 AM" src="https://github.com/metabase/metabase-private/assets/17398657/05cd36ab-1e55-4cb3-9bf3-3f4504c5fe2b">

### Expected behavior

To be able to use RSA Key Pair Authentication

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Mac OS X",
    "os.version": "13.5.1",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "snowflake",
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-16",
      "tag": "v1.49.6",
      "hash": "5abf130"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

P1 - Concern for users intending to use RSA authentication

### Additional context

Other related issues going back a year:
https://github.com/metabase/metabase/issues/31273
https://github.com/metabase/metabase/issues/26078
https://github.com/metabase/metabase-private/issues/194

<br>
<br>

Example Node app as reference

```
import crypto from 'crypto';
import fs from 'fs';
import snowflake from 'snowflake-sdk';

const privateKeyFile = fs.readFileSync('path to private p8 key');

const privateKeyObject = crypto.createPrivateKey({
  key: privateKeyFile,
  format: 'pem',
  passphrase: 'your token secret key/password'
});


const privateKey = privateKeyObject.export({
  format: 'pem',
  type: 'pkcs8'
});


const connection = snowflake.createConnection({
  authenticator: "SNOWFLAKE_JWT",
  privateKey: privateKey,
  account: 'your account name', // <-- Example: GK592.us-west-1.aws 
  username: 'user name used for authentication' 
});


function handleConnectionResult(err, conn) {
    if (err) {
      console.error("Connection error:", err); 
    
      return;
    }
  
    if (conn) {
      console.log(`Successfully connected. Connection ID: ${conn.getId()}`);
    } else {
      console.warn("No connection returned from Snowflake."); 
    }
  }
  

  connection.connect(handleConnectionResult);
```

**Comment by camsaul** [comment]
We're using the Snowflake JDBC driver, not Node, have you got it working with that? https://docs.snowflake.com/en/developer-guide/jdbc/jdbc

**Comment by FilmonK** [comment]
@camsaul Sorry for the confusion, I understand we use the JDBC driver. 
The reason I referenced Node is to compare the authentication factor Snowflake identifies when Metabase currently connects (Password factor) versus Node app (RSA Key factor).
Better shown in the image above under the "First_Authentication_Factor" column.

I can give it a try later today with JDBC drivers.

**Comment by lbrdnk** [comment]
Hey @Adovenmuehle, I'm able to connect a cloud (also local) Metabase instance to Snowflake using private key. However, when my user's role does not have required privileges on the database I'm attempting to connect, I see the same error as you.

I believe that every user should have the `SNOWFLAKE_SAMPLE_DATA` database accessible. Could you try to connect to that db? What's the result?

Then, here's how I created the database and the user for testing: I've logged in as user that has privileges required to create a new user, database and grant privileges. Afterwards I've created the user and the database as follows.

```
create user ANOTHER_RSA_TEST_USER;
alter user ANOTHER_RSA_TEST_USER set default_role = public;
alter user ANOTHER_RSA_TEST_USER set rsa_public_key = <public key>;

create database ANOTHER_RSA_TEST_DB;
create table ANOTHER_RSA_TEST_DB.PUBLIC.ANOTHER_RSA_TEST_TABLE (id integer, name varchar);
insert into ANOTHER_RSA_TEST_DB.PUBLIC.ANOTHER_RSA_TEST_TABLE (id, name) values (1, 'John');

grant usage on database ANOTHER_RSA_TEST_DB to role PUBLIC;
grant usage on all schemas in database ANOTHER_RSA_TEST_DB to role PUBLIC;
grant select on all tables in database ANOTHER_RSA_TEST_DB to role PUBLIC;
```

Would you be able to setup the user and the database as described and try to connect using private key? If so, please make sure to input database name in case sensitive manner -- all caps in this case.

**Comment by bombadil444** [comment]
Came across same issue as @Adovenmuehle above when switching from Snowflake passphrase auth to key/pair auth.

In Snowflake, I needed to set a default role on the user I was trying to connect with that had access to the database. This resolved the issue.

The "Role (required for connection impersonation)" field seemed to work for passphrase auth, but apparently no longer applied when authenticating with a private key.

The `Looks like the database name is incorrect.` error message is generally unhelpful as it can pop up when the issue is actually to do with permissions.

**Comment by Adovenmuehle** [comment]
@bombadil444 your suggestion fixed it. However, one interesting thing, I _did_ have a default role set but it was lower case, I changed it to uppercase and it seemed to work. 

I now show the RSA_KEYPAIR auth in `FIRST_AUTHENTICATION_FACTOR` from ```sql
select *
from table(snowflake.information_schema.login_history_by_user(USER_NAME => 'METABASE', result_limit => 1000))
order by event_timestamp desc;
```

One slightly weird thing, when going back to the database settings page after saving it with the `.p8` file and no password, it shows `No file chosen` for the private key file, but a populated password.
![image](https://github.com/metabase/metabase/assets/27858/5ba633b4-e92a-47f1-957e-78214cdae95b)
I thought maybe it had reverted or my 1password was auto-filling it, but it's using the keypair authentication according to Snowflake so I'll trust that.

**Comment by Numianlo** [comment]
Connecting to Snowflake using RSA Keypair Authentication, getting the "Looks like the database name is incorrect"

To solve this set a defaul_role on the user.
example: ALTER USER your_user SET DEFAULT_ROLE = <your_role> ;

If the user already has a default role,  but you are connecting using another role that this user also has, then you need to set the DEFAULT_SECONDARY_ROLES.
example: ALTER USER your_user SET DEFAULT_SECONDARY_ROLES = ( 'ALL' );
