### ISSUE TITLE
Missing png export enum in API POST /api/card/:card-id/query/:export-format

### ISSUE THREAD

**Issue by turran** [metabase/metabase#41879]
### Describe the bug

The `png` export-format is not supported on the [API](https://www.metabase.com/docs/latest/api/card#post-apicardcard-idqueryexport-format)

### To Reproduce

1. Get a token
2. Call `curl -H 'x-api-key: API_KEY' -X POST 'https://MB_HOST/api/card/694/query/png'`
3. The result is `{"errors":{"export-format":"enum of csv, api, xlsx, json"},"specific-errors":{"export-format":["should be either csv, api, xlsx or json, received: \"png\""]}}`

### Expected behavior

A png image should be returned

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.11.0-49-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.4 (Debian 13.4-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-22",
      "tag": "v0.49.7",
      "hash": "f0ff786"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

### Severity

It is blocking our automation

**Comment by paoliniluis** [comment]
Sorry, what are you trying to do? the PNG export is a frontend concept, we don't have a backend logic for generating something like a front end screenshot (it's handled by html2canvas)

**Comment by turran** [comment]
I was trying to programmatically fetch the generated image of a card/question. I saw on https://github.com/metabase/metabase/issues/4701 that this was supported. I wasn't aware this is a frontend concept. Are other export formats generated on the backend?

**Comment by paoliniluis** [comment]
The PDF export of the dashboard and the PNG export of the cards are pure frontend.

Closing this as I don't believe we'll do this anytime soon
