### ISSUE TITLE
Views are logged for cards in a dashboard even if the user didn't view the tab

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#41892]
### Describe the bug

If a user views a dashboard, we add a `view_log` record and increment the `report_card.view_count` column for each card in the dashboard. If the dashboard has multiple tabs, we'll log views for cards on all tabs, even if the user never viewed it. We should only log and count views for the tabs users view.

[slack conversation](https://metaboat.slack.com/archives/C0641E4PB9B/p1714143102927189?thread_ts=1714129699.563259&cid=C0641E4PB9B)

### To Reproduce

1. Create a dashboard with a question in the second tab. Save it and view the first tab without viewing the second.
2. Query the app DB: `select * from view_log where model = 'card' and model_id = <id>;`, where <id> is the ID of the question.
You should see views for the question, even though you never visited the first tab.

### Expected behavior

views should only be logged if the user clicks on the tab containing the card.

### Information about your Metabase installation

```JSON
master
```

### Severity

low

**Comment by luizarakaki** [comment]
This is a high-priority P2 imo. Our audit logs must be right
