### ISSUE TITLE
Slack integration uses a deprecated API

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#41890]
### Describe the bug

Slack integration uses a deprecated endpoint to upload files.

https://api.slack.com/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay
> The original web API method for uploading files to Slack, [files.upload](https://api.slack.com/methods/files.upload), is being sunset on March 11, 2025. Beginning May 8, 2024, newly-created apps will be unable to use this API method.
> 
> Apps & integrations should migrate away from files.upload and instead leverage a combination of two APIs: [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) and [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal). The use of these two methods is more reliable, especially when uploading large files.
> 

### To Reproduce

n/a

### Expected behavior

Use the endpoints recommended instead of the deprecated one.

### Information about your Metabase installation

```JSON
master
```

### Severity

P1 - beginning May 8 it won't be possible to set up a new Slack integration

### Additional context

https://github.com/metabase/metabase/blob/dd66a69a264c10fe6cadb1860a45a77a1b5061d6/src/metabase/integrations/slack.clj#L321-L342

**Comment by paoliniluis** [comment]
![image](https://github.com/metabase/metabase/assets/1711649/fe6f97b8-7012-4503-a445-52e843f31816)
