### ISSUE TITLE
Check for the existence of Poifiles in temporary directory before creating XLSX files

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#41919]
### Describe the bug

Had a customer run into an issue where they were getting the following errors when attempting to download results as an XLSX file.

> ERROR async.streaming-response :: Caught unexpected Exception in streaming response body 
> 
> metabase: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/poifiles/poi-sxssf-sheet5437265569215382033.xml 
> 
> metabase: at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:728)
> 

They’re hosted in an AWS EC2 Linux instance that periodically runs **systemd-tmpfiles --clean** to clean everything within the /tmp directory.
What happens is Metabase can’t locate **'/tmp/poifiles/'** as it’s going through the process of creating the XLSX file.
I mention '/tmp/poifiles/' as an example but it’s wherever the **java.io.tmpdir** directory is pointing to, which can be found by running the following command.

`java -XshowSettings:properties -version`

In this particular situation, I did suggest creating an exclusion in the cleanup process so the 'poifiles' folder is not removed during cleanup.
However, as a precautionary measure, should we be checking if that directory exists before attempting to write to it?

### To Reproduce

1. Run Metabase as you normally would.

2. Test downloading results of a card an XLSX to confirm it's working

3. Identify the location of the 'poifiles' temp folder. Either programmatically or running the following command **java -XshowSettings:properties -version** and locating the value for **java.io.tmpdir** 

4. Remove the 'poifiles' folder

5. Download results of a card to XLSX and errors should occur as 'poifiles' can't be located

6. Restarting or manually creating 'poifiles' resolves the issue

### Expected behavior

Possibly checking if 'poifiles' folder exists before creating XLSX files

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Mac OS X",
    "os.version": "13.5.1",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-16",
      "tag": "v1.49.6",
      "hash": "5abf130"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

P3 - There are work arounds and even restarting Metabase should resolve the issue.  However, a suggestion for improving customer experience.

**Comment by mbosecke** [comment]
For those who are looking for a workaround, you can create a file called `/etc/tmpfiles.d/metabase.conf` with the following contents to prevent `systemd-tmpfiles --clean` from removing this particular directory:
```
# Prevent metabase "poifiles" directory from being cleaned up
d /tmp/poifiles 0755 metabase metabase -
```

See:

* `man systemd-tmpfiles`
* `man tmpfiles.d`

**Comment by dpsutton** [comment]
This looks like an issue with the apache poi library that we use. I can trigger this by deleting the temp file right before downloading the file:

```clojure
  (let [f (io/file (str (System/getProperty "java.io.tmpdir") "/poifiles"))]
    (when (.exists f)
      (doto f (.delete))))
```

This is fixed in https://bz.apache.org/bugzilla/show_bug.cgi?id=69323  https://github.com/apache/poi/commit/5a977d1a7b70714e1efa1d780478394f63dc112a and appears to be slated for the next release 5.3.1
![Image](https://github.com/user-attachments/assets/0e99f30a-4288-4a32-a7da-f9140f2adff4)

https://poi.apache.org/changes.html#5.3.0
