### ISSUE TITLE
Add series icon on dashcards is wrong

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4191]
Looks like there's a collision between two icons that are showing up: the + icon and an icon that represents the kind of visualization the chart is:

![screen shot 2017-01-18 at 1 02 56 pm](https://cloud.githubusercontent.com/assets/2223916/22082903/8886bdf8-dd7e-11e6-91a6-b3cc66220fbc.png)

![screen shot 2017-01-18 at 1 03 55 pm](https://cloud.githubusercontent.com/assets/2223916/22082915/973b4328-dd7e-11e6-89f1-ea1384ea9288.png)

**Comment by tlrobinson** [comment]
Mentioned in #4099 as well
