### ISSUE TITLE
[FE] UI changes to the QB for new metric

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#41927]
These are all label/text changes to the query builder when the user does New > Metric

- Add `(optional)` to filters
- `Measure calculation` instead of `Summarize`
- Remove the `by` in the breakout

These are more involved changes that need additional details from the product side and probably should be spun off as separate issues
- `Primary time dimension` instead of nothing in the breakout
- Add the sidebar with the instruction (this needs to be spec-ed out)

**Comment by luizarakaki** [comment]
`Primary time dimension` instead of nothing in the breakout

This requires new design input, as now it is possible to add multiple non-time dimensions there
