### ISSUE TITLE
Can't print the full public dashboard

### ISSUE THREAD

**Issue by watollop** [metabase/metabase#41926]
### Describe the bug

I upgraded our metabase from 47.13 to 49.6.

Previously when displaying a public dashboard with a very long table so it could fit a table of 100 rows, when pressing Control + P, I could print the full length of the result. After the upgrade, I only can print the info that I'm looking not the full generated answers, like 20 rows.
<img width="971" alt="Captura de pantalla 2024-04-28 a las 18 50 25" src="https://github.com/metabase/metabase/assets/10385633/b1317e06-5065-49fa-bf5b-044ab7e87229">

### To Reproduce

1. Go to a public dashboard or question with a table with 100 rows
2. Click on Control + P in other to print

### Expected behavior

Multiple print pages are generated

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "es-ES",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.133+",
    "user.language": "en",
    "user.timezone": "Europe/Madrid"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "oracle",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-16",
      "tag": "v0.49.6",
      "hash": "5abf130"
    },
    "settings": {
      "report-timezone": "Europe/Madrid"
    }
  }
}
```

### Severity

annoying

**Comment by paoliniluis** [comment]
Hi, printing the page has always printed what you see, how is it able that you were able to see all the results?

**Comment by watollop** [comment]
Hi!, What I use to do is crate a dashboard with with a very long table so it do not paginate, and then I was able to print all the rendered answer.

**Comment by zbodi74** [comment]
Confirmed for version 49.6. To reproduce the issue, add a table visualization to a dashboard and resize it to be very tall, extending it by scrolling down several screens. Then, share the dashboard publicly and compare the print previews of both the internal and shared versions. 
The shared version will only have the first page in the print preview.
