### ISSUE TITLE
FE won't load the full query builder when using metabase analytics model

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#41925]
### Describe the bug

Seems like a race condition in the frontend that doesn't load the full query builder on the first attempt
![image](https://github.com/metabase/metabase/assets/1711649/afa30a18-1044-46f2-b5d0-6b051d123952)

The workaround is to click the model name and select it again
![weird](https://github.com/metabase/metabase/assets/1711649/6c920f91-59d7-4610-bf61-c1ab1247fb25)

### To Reproduce

1) start metabase
2) go to new->question-> select any metabase analytics model

### Expected behavior

it should work straight from the first try

### Logs

NA

### Information about your Metabase installation

```JSON
v49
```

### Severity

P3

**Comment by nemanjaglumac** [comment]
Duplicate of #43088

**Comment by darksciencebase** [comment]
@nemanjaglumac thanks for cleaning this up. please close duplicate issues with "Close as not planned", and not "Close as completed", it helps with the accuracy of the alert on the #engineering channel.
