### ISSUE TITLE
[BE] Renaming a metric does not work

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#41929]

**Comment by ranquild** [comment]
Seems to be a BE bug 
<img width="761" alt="Screenshot 2024-04-29 at 15 29 25" src="https://github.com/metabase/metabase/assets/8542534/491c323f-a07a-43b2-8ef0-b1f148a369b1">

**Comment by metamben** [comment]
Seems to work for me: https://metaboat.slack.com/files/U03AN4TRM6Y/F0710H53ATY/metric-rename.mov

**Comment by metamben** [comment]
This should be fixed now on `metrics-v2`.
