### ISSUE TITLE
Empty dashboards are visible to everyone

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4194]
To reproduce:
- user1:group1
  - create a question and save it
  - add it to dashboard1
  - go to dashboard1 and remove the question from there

- user2:group2
  - can see that dashboard while they shouldn't be able to

Expected behavior will also include:
- user3:group1
  - should be able to see the dashboard

If I understand it correctly then the reason user2 can see dashboard1 is cause there are no questions assigned to it. At that point why don't we fall back to group Id using creator id which is associated with the dashboard in database.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by salsakran** [comment]
We've focused more on security than organization/visibility in recent releases. 

What situations would you want an empty dashboard to be visible? I.e. could it be as simple as keeping dashboards "private" to just their creators until there's something in them?

**Comment by VikramTiwari** [comment]
Yes, I think that would work. It's not just the case initially when someone creates a new dashboard, but also when someone removes all questions from the dashboard.

**Comment by VikramTiwari** [comment]
Any update on this? This is trivial but it keeps being a nuisance.

**Comment by VikramTiwari** [comment]
@camsaul Would a sample solution here be a new interface `can-group-read` which can be represented as:

(`can-read` and (Use `current-user-id` to find the `permission-group` == `created-by` id's `permission-group` or `current-user-id` belong to `admin` `permission-group`))

This should complete following cases:
- dashboard created by any `current-user-id` if it has access to underlying card's DB
- Empty dashboards are visible only to admins and creator's group rather than everyone

**Comment by edenzik** [comment]
Can we generalize this? We are interested in private dashboards - AKA ones that one user creates and decides who to share it with.

**Comment by edenzik** [comment]
Also +1 to this

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by edenzik** [comment]
Thanks @camsaul. Or is that a bot you wrote to that effect? Regardless, done.

**Comment by camsaul** [comment]
Thanks! No bot, I just got an email with your comment and I had a GitHub saved reply ready to go 😂

**Comment by edenzik** [comment]
@camsaul your comment failed my turing test! Would be a great bot though :)

**Comment by flamber** [comment]
This was fixed in 0.30 with the changes to how Collections and permissions worked.
