### ISSUE TITLE
"Collection type" tooltip is hidden behind the collection modal

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#41953]
### Describe the bug

The collection type tooltip renders behind the collection modal.

### To Reproduce

You'll need an enterprise Metabase edition for this.

1. Go to "New > Collection"
2. Hover the `i` icon next to the "Collection type"
3. See that the tooltip renders behind the modal

![image](https://github.com/metabase/metabase/assets/31325167/531a8f01-f706-4d0c-991b-2fadc538ba2d)

### Expected behavior

The tooltip should render in front of the modal and should not be obstructed.

### Information about your Metabase installation

```JSON
local dev, `master`, 48e4888, H2, Sample Database
```

### Severity

P3

### Additional context
Not present in `x.49.7`. This is a regression in `master` only.

**Comment by noahmoss** [comment]
Introduced by https://github.com/metabase/metabase/pull/38298
