### ISSUE TITLE
unable to edit database name for bigquery database

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4196]
On v0.22.0 and v0.21.0. Possibly more:

In the admin panel, I can edit the name for a MySQL database but can't edit it for a BigQuery database? Can't seem to understand why that would be?

**Comment by tlrobinson** [comment]
@VikramTiwari It looks like the form validation is failing because the auth code isn't filled in. We test the db each time you save but we don't need to do that if you're only changing the name.

As a workaround you can get a new auth code then save.

**Comment by salsakran** [comment]
Hmm. Yeah, we should probably test using the old value of the auth token, like we do for passwords. In this situation that token is effectively a password and should be treated as such.

**Comment by VikramTiwari** [comment]
I don't think you can use the same auth code, since:
- In OAuth based flow auth code is one-time use token only and is used to get refresh token which is a long-lived token and can be used for as long as you can keep refreshing it. Virtually forever, unless user disabled the application from their OAuth provider.
- Metabase doesn't save auth code

I think the solution would be along the lines of:
- If user updates only the `name` of the database, do not do any checks and update that in the `metabase_database` table.
- If anything other than the `name` has been updated, go through the normal flow of making sure that Metabase gets all required details necessary and update those in the database.

**Comment by flamber** [comment]
Fixed by #12498 in 0.36.0 - Service Accounts, which makes the auth code field obsolete.
Still valid for Google Analytics #6613
