### ISSUE TITLE
Provide the ability to specify a scale factor in scatter plots

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#41984]
https://www.notion.so/metabase/Provide-the-ability-to-specify-a-scale-factor-in-scatter-plots-a09a5b6356fa4ef7b2e126ec7eb95fa4

**Comment by cdeweyx** [comment]
Pausing until we have higher conviction on this / hear more about the problem from customers: [Slack thread](https://metaboat.slack.com/archives/C064QMXEV9N/p1714938138808549?thread_ts=1714765064.408709&cid=C064QMXEV9N)

**Comment by EmmadUsmani** [comment]
https://github.com/metabase/metabase/pull/42351

Had a very rough prototype locally, leaving the PR here for posterity if we ever revisit this
