### ISSUE TITLE
Data with type 'Category' auto-formatted as a date in visualizations

### ISSUE THREAD

**Issue by Hennisa** [metabase/metabase#4199]
Browser and the version: Chrome 53.0.2785.143 (64-bit)
Operating system: OS X 10.11.6
DB: Redshift
Metabase internal database: Postgres
Metabase version 0.22.0
Metabase hosting environment: Elastic Beanstalk

I have a column in "Date & Time" table called "Year and Week Actual" this value is formatted as a category and it is displayed correctly in "Table" visualisation:
<img width="772" alt="screen shot 2017-01-19 at 17 58 41" src="https://cloud.githubusercontent.com/assets/14327271/22116818/0402feee-de72-11e6-8283-8dae6428bc32.png">

However, when I change the visualization type to something else (like Line-chart), the "Year and Week Actual" category is auto-formatted (incorrectly) as a date:
<img width="1053" alt="screen shot 2017-01-19 at 17 59 26" src="https://cloud.githubusercontent.com/assets/14327271/22116969/7b729912-de72-11e6-82ac-9122ea36bf43.png">

The reason why we have a separate table "Year and Week Actual" instead of using the built-in functionally for grouping by week is because Metabase, by default, starts weeks on Sundays, but in our case a new week should start each Monday and there is no way to change this default setting, thus we have had to create our own weekly grouping.

**Comment by flamber** [comment]
This was fixed by #11156 in 0.34.2 (if not before), but unless the value goes above `12`, then Metabase would not know if you're trying to display a year-month or year-week.
To help Metabase understand, add a `W` in front of the week, like `2020-W02`
Related to #1779
