### ISSUE TITLE
Users can't see question which they have collection permission but not data permission

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4200]
As reported in this [Discourse thread](http://discourse.metabase.com/t/collection-permissions-cant-view-questions-to-download-data-or-view-line-graphs/1051), if a user group has **no access** to a database or table, but **does** have access to a collection which contains saved questions based on that data, they currently are correctly seeing those questions listed in the collection(s) for which they have access, and are also correctly seeing those cards on dashboards.

However, they are **not** currently able to view those questions' detail views. The specced behavior is that collection permissions should supersede data access permissions. Therefore, if a user group has View permission for a collection, they should be able to view the question detail page, _even if they don't have data access permission_ for the underlying data. In this scenario, they should also probably not be shown the query builder bar, or perhaps should see a disabled version of the query builder.

**Comment by mazameli** [comment]
And I'll let @salsakran decide if this is a P0. ;)

**Comment by mazameli** [comment]
Moreover, I also can't see questions I should have access to in the `Add Series` dialog for dashboard cards:

**Current (not seeing baseball related cards, though I should, because I have View access to the collection they're in, but no underlying data access):**

![current](https://cloud.githubusercontent.com/assets/2223916/22119307/f5d17266-de2f-11e6-8033-74b7bc71abd7.png)

**Expected (note the baseball-related questions, which this user should have access to):**

![expected](https://cloud.githubusercontent.com/assets/2223916/22119367/35ad1d72-de30-11e6-9190-54fc3d461f20.png)

**Comment by tlrobinson** [comment]
This is due to the query builder trying to load the table metadata, which the user doesn't have access to, which triggers a 403 handler. We'll also need 

@mazameli  Can you file the Add Series one separately? They're not related technically.

**Comment by mazameli** [comment]
Will do.

**Comment by mazameli** [comment]
https://github.com/metabase/metabase/issues/4201

**Comment by maximilianmessing** [comment]
really looking forward to the next release which should resolve this issue 👍

**Comment by mazameli** [comment]
@maximilianmessing we just released 0.22.1, which you can get [here](http://www.metabase.com/start/).
