### ISSUE TITLE
When updating a filter value in chill mode, the order of the columns is messed up

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#42049]
### Describe the bug

When updating a filter value in chill mode, the order of the columns is messed up.

### To Reproduce

1. Go to stats https://stats.metabase.com/question/4859
2. Click on filters on the top bar
3. Click on the filter `Created At is in the previous week, starting 16 weeks ago`
4. Change the value of starting from, from 16 to 17 weeks
5. Click on update filter
6. The order of the columns is not preserved, notice the 2nd column is now different.

Slack thread w/ Loom https://metaboat.slack.com/archives/C01LQQ2UW03/p1714409454229319

blocked by [RFC](https://www.notion.so/metabase/Tech-Remove-field-refs-from-viz-settings-bec453dc75bd40efb54a1ddb83acd536)

> there is viz settings -> cols mismatch as cols's format of the field_ref is `['field', 'created_at']` for some columns and viz settings use `['field', 34]` where 34 is created_at id, the issue can't be addressed in the current state of field_refs, so we expect it to be fixable after RFC gets implemented

### Expected behavior

The order of the columns is preserved

### Information about your Metabase installation

```JSON
- Stats Built on 2024-04-30 Hash: 389886d
```

### Severity

P2

**Comment by zbodi74** [comment]
This has also been reported by a customer in `v1.49.7`.

**Comment by albertoperdomo** [comment]
The order of columns is also messed up jas well when sorting by a specific column.

**Comment by uladzimirdev** [comment]
@albertoperdomo you're right, this change is related to the latest rework to MLv2, I'm trying to understand where we should fix it - FE or BE
