### ISSUE TITLE
Redshift syncs different databases at once which causes confusion in the Metadata

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#42045]
### Describe the bug

Relevant thread https://metaboat.slack.com/archives/C04DN5VRQM6/p1714479864467729 but in summary in 49 we updated the sync driver methods to solve [Getting fields in (Redshift) is slow](https://github.com/metabase/metabase/issues/38492#top). 

### To Reproduce

Metabase during table scans is sending out querys like:

```
select c.column_name, c.data_type, c.ordinal_position, c.schema_name, c.table_name
from svv_all_columns as c
         left join (select tc.table_schema, tc.table_name, kc.column_name
                    from information_schema.table_constraints as tc
                             join information_schema.key_column_usage as kc
                                  on tc.constraint_name = kc.constraint_name and tc.table_schema = kc.table_schema and
                                     tc.table_name = kc.table_name
                    where tc.constraint_type = 'PRIMARY KEY') as pk
                   on c.schema_name = pk.table_schema and c.table_name = pk.table_name and
                      c.column_name = pk.column_name
where c.schema_name !~ '^information_schema|catalog_history|pg_' AND c.table_name = 'table'
```

Which gets all the columns for a particular Table for a given Database. The problem we are experiencing is that if you have a Prod Database and Dev Database and each of those DBs have a similar table with a different set of columns then metabase is ending up combining the columns of the two tables which are found in two different schemas together. 

The following shows an images which shows the above query being run (I added the database column) and it fetches columns from different DBs which shouldn't be possible:

<img width="818" alt="image" src="https://github.com/metabase/metabase/assets/110378427/2343f039-394d-45ae-b644-88854a4e0ea2">

To replicate:

1) created 2 connections Data Warehouse Prod Test and Data Warehouse Staging Test
2) using same user as the original connection: "metabase" ... So same user with same password is used to create this connection
3) Query the svv_all_columns and get the columns from both databases

Since we changed how the sync works and started using the jdbc we are learning about [redshift parameter groups](https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-parameter-groups.html) (aka cluster parameter groups), and I we think those might be very relevant here to reproduce the issue. So the issue is potentially caused by those two parameters:

datashare_enabled: if this is “on” or “off”
external_database: if this is “on” or “off”

### Expected behavior

Sync is performed only to 1 database

### Information about your Metabase installation

```JSON
1.49
```

### Severity

Breaks questions which start referencing columns that are not really there

**Comment by darksciencebase** [comment]
[slack thread](https://metaboat.slack.com/archives/C04DN5VRQM6/p1714479864467729)

**Comment by Tony-metabase** [comment]
This got fixed with the following backport https://github.com/metabase/metabase/pull/41068/files
