### ISSUE TITLE
[Question] Filter Dashboards

### ISSUE THREAD

**Issue by federicokeen** [metabase/metabase#4206]
First of all guys, great work! Metabase is becoming crucial in our company!
This might be a simple question or end up eventually in a feature request. Our users are creating dashboards with the questions each one is interested in. Is there a way to make them private so that when you are searching for a dashboard its not listed? The main problem is that the dashboards menu is getting out of control, not really worried about making dashboards private, even better if they are not so they can share them with the link, i guess its more about choosing which Dashboards show up on the menu...

**Comment by mazameli** [comment]
Glad to hear your company is enjoying Metabase! Thanks for the feedback. We agree that dashboard organization needs work. That's being tracked in this issue:
https://github.com/metabase/metabase/issues/2326

We are also discussing dashboard-level permissions:
https://github.com/metabase/metabase/issues/3363

So I'm going to close this as a duplicate.
