### ISSUE TITLE
Admin CSV Table Cleanup UI

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#42069]
[designs](https://www.figma.com/file/adwVx31Cb5yI5lhW4iYa4v/Let-people-delete-previous-CSV-uploads-and-their-underlying-table?type=design&node-id=1273-8245&mode=design&t=WYFxBUIkLcV4kX5I-0)

- [x] add uploaded table list to upload settings page
- [x] deletion confirmation modal
- [ ] pagination
- [x] single deletion
- [x] multi-deletion
- [ ] deletion progress display
- [ ] deletion toasts
- [ ] handle failure case

**Comment by addison-grant** [comment]
Is there a plan to release this to Open Source?
