### ISSUE TITLE
Allow filtering for empty strings

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4212]
As proposed in #4211, allow users to search for empty strings and not just nulls.

**Comment by tlrobinson** [comment]
Would this be another operator, or just relax the input validation to allow an empty string?

**Comment by camsaul** [comment]
@tlrobinson Do you mean relax the input validation on the frontend or backend? I don't think the backend requires the string to be non-empty for filtering purposes

**Comment by tlrobinson** [comment]
Frontend

**Comment by camsaul** [comment]
ok got it.

**Comment by dangold1138** [comment]
Does it make sense for "is empty" queries to just also return empty strings?

**Comment by bcbob** [comment]
this is needed! it's currently not possibly to filter for empty (but not null) strings. this is very limiting in many situations, and surely simple to fix.

**Comment by bcbob** [comment]
any help here possible?

**Comment by bcbob** [comment]
![2019-06-20 10 11 30](https://user-images.githubusercontent.com/30799811/59832332-e7a5b780-9343-11e9-85b3-39bb4dd18d50.jpg)

**Comment by flamber** [comment]
@bcbob 
It is possible in 0.32 to filter by empty string, if the field shows list values. But it's not possible to set the filter if using a searchable field, since the "Add filter" button is disabled (a hack would be to remove the `disabled` class from the button via inspector in the browser) - https://github.com/metabase/metabase/issues/5299#issuecomment-463781960

**Comment by montanaflynn** [comment]
This is needed for us as well!

**Comment by flamber** [comment]
This was fixed in 0.36.1, so now filtering is done like this:
"Is empty" generates `(column IS NULL OR column = '')`
"Not empty" generates `(column IS NOT NULL AND column <> '')`

And old filters from before 0.36.1 are changed to "Is empty" => "Is null", and "Not empty" => "Not null"
