### ISSUE TITLE
Support SQLite on cloud

### ISSUE THREAD

**Issue by healthbjk** [metabase/metabase#42135]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to set up a separate database on my own personal cloud to use Metabase's cloud option. I thought that the SQLite option might offer an easy way to pass in a file version of my database, but it is not an option on Metabase cloud. I'd like to be able to upload some files and persist them. Creating a public database on my own is a pain in the ass.

A SaaS offering that has a lot of burden to set up isn't worth it.

**Describe the solution you'd like**
Pass in a SQLite file. 

**Describe alternatives you've considered**
Maybe being able to link Google Sheets as a "database" or datasource?

**How important is this feature to you?**
Considering closing my Metabase Cloud account - I was hoping to use it for our public facing reports.

**Additional context**

**Comment by paoliniluis** [comment]
Something is coming for solving this, but definitely not SQLite… we won’t spin up persistent storage for our cloud for now

**Comment by healthbjk** [comment]
@paoliniluis thanks for the quick reply. 

>Something is coming for solving this

Mysterious haha.

> definitely not SQLite
Not wedded to SQLite or even persistent storage in your cloud, just an option to get something going easily without having to set up something super heavy like AWS.

**Comment by Tony-metabase** [comment]
Closing this https://github.com/metabase/metabase/issues/44233
