### ISSUE TITLE
"Looks like this is a new installation" even though it is not and metabase.db.mv.db exists

### ISSUE THREAD

**Issue by axb21** [metabase/metabase#4215]
### Issue
- Your browser and the version: Firefox 50.1.0
- Your operating system: Kubuntu 16.04 (4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
- Your databases: mysql  (Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper)
- Metabase version: 0.21.0, 0.22.0
- Metabase hosting environment: Ubuntu 16.04 (4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux). run metabase with java -jar
- Metabase internal database: H2 (metabase.db.mv.db file)
- Unknown how to reproduce the issue

I had to reboot the machine on which I host mysql and metabase. When I attempted to restart metabase after the machine came back up, the log file informed me `01-23 11:56:22 INFO metabase.core :: Looks like this is a new installation ... preparing setup wizard`. However, this is not a new metabase installation.  I've been using metabase for a bit over a month, there is an existing `metabase.db.mv.db` file, and I attempted to restart metabase in the same way I always have (as far as I am aware, anyway). I've already run the setup wizard etc. and have two dashboards and a bunch of questions I'd like to recover if possible.

I made a copy of the `metabase.db.mv.db` file and attempted to start the latest metabase (v0.22.0), but receive the same log message about running setup.

Anyone have a hint about how I can diagnose and possibly repair this issue? Could something have gone awry in metabase's H2 database file that I might be able to query/fix? I don't know how to proceed from here and would prefer not re-creating all the questions and two dashboards I had. Thank you!

**Comment by tlrobinson** [comment]
First of all, make sure you're using the right DB file. By default Metabase uses `metabase.db.mv.db` in the current working directory, and if it doesn't exist it will create a new one.

A database that hasn't been set up will probably be about 12KB, while one that has been recently set up will be about 210KB (as of v0.21), and if you've been using it for awhile it should be a bit larger.

Try setting the `MB_DB_FILE` environment variable when starting Metabase. If your DB file is `metabase.db.mv.db` then run:

```
MB_DB_FILE=metabase.db java -jar metabase.jar
```

Note you don't need to include the trailing `.mv.db`. Try the absolute path as well.

You can also run SQL commands against the database like this:

```
java -cp metabase.jar org.h2.tools.Shell -url jdbc:h2:./metabase.db -user "" -password "" -driver org.h2.Driver -sql "select * from core_user"
```

Make sure the user(s) you've previously set up appear in the results of those commands.

Also note, we recommend using Postgres or MySQL as the application database in production.

**Comment by axb21** [comment]
Thanks for your help. I was never able to sort out what went wrong and, luckily, I had a copy of that file; it was outdated but worked fine. I lost a bit of work, but it was easier to re-create what I'd lost than try to sort this out. So, I'll close this issue.
