### ISSUE TITLE
Erroneous field referenced in parameter search for dashboard filter

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#42153]
### Describe the bug

Stats is searching an unrelated field for the `Customer Name` filter on Dashboard 1880:

```
GET /api/dashboard/1880/params/85e5498e/search/Onecom

{"via":
[
{"type":"clojure.lang.ExceptionInfo",
"message":"Cannot search against non-Text Field 541,278 \"id\"",
"data":{"status-code":400,"field-id":541278,"field":"id","base-type":"type/BigInteger"},
"at":["metabase.models.params.chain_filter$check_valid_search_field","invokeStatic","chain_filter.clj",607]}],
"trace":[["metabase.models.params.chain_filter$check_valid_search_field","invokeStatic","chain_filter.clj",607],
...
"message":"Cannot search against non-Text Field 541,278 \"id\"","field-id":541278,"field":"id","base-type":"type/BigInteger"}
```

What's mysterious is that _no_ dashboard params (not on that one nor anywhere else) use Field 541278. Something is going wrong in the chain filtering that's pulling in the wrong field ID.

### To Reproduce

1. Go to dashboard 1880 on stats
2. Add a Customer Name filter
3. Check the network tab

(alternatively, GET the endpoint directly)

### Information about your Metabase installation

```JSON
Built on 2024-05-02

Hash: 3db638f
```
```


### Severity

blocking some users

### Additional context

Unsure how widespread this is

**Comment by tsmacdonald** [comment]
Tried to repro this locally and couldn't manage

**Comment by qnkhuat** [comment]
Answered in https://metaboat.slack.com/archives/C05MPF0TM3L/p1714616294801369
