### ISSUE TITLE
Seems like a bug in a BigQuery join

### ISSUE THREAD

**Issue by marcromeyn** [metabase/metabase#4218]
### Bug

Joins don't work for me with BigQuery as database, seems a problem with the way Metabase aliases fields and tables.

- Your browser and the version: _Chrome 52.1_
- Your operating system: _OS X 10.12_
- Your databases: _BigQuery_
- Metabase version: _0.21.1_
- Metabase hosting environment: _AppEngine_
- Metabase internal database: _MySQL_

*Repeatable steps to reproduce the issue*

The error is as follows: 
_Field 'logs.table_conversations__via__conv.agent_id' not found on either side of the JOIN_

The SQL-query Metabase creates is:
```sql
SELECT
  [logs.table_conversations__via__conv.agent_id] AS [logs.table_conversations__via__conv.agent_id]
FROM
  [logs.table_chatuser_events]
LEFT JOIN
  [logs.table_conversations] [table_conversations__via__conv]
ON
  [logs.table_chatuser_events.conversation_id] = [table_conversations__via__conv.id]
GROUP BY
  [logs.table_conversations__via__conv.agent_id]
ORDER BY
  [logs.table_conversations__via__conv.agent_id] ASC
LIMIT
  2000
```

It should be this (add the dataset to table you join with):
```sql
SELECT
  [logs.table_conversations__via__conv.created_by] AS [logs.table_conversations__via__conv.created_by]
FROM
  [logs.table_chatuser_events]
LEFT JOIN
  [logs.table_conversations] [logs.table_conversations__via__conv]
ON
  [logs.table_chatuser_events.conversation_id] = [logs.table_conversations__via__conv.id]
GROUP BY
  [logs.table_conversations__via__conv.created_by]
ORDER BY
  [logs.table_conversations__via__conv.created_by] ASC
LIMIT
  2000
```

Should be a very straightforward fix.

**Comment by asafeilam** [comment]
I also experienced the same problem.
what to do?

**Comment by MiBaDK** [comment]
Hi guys, any plans for this one?

**Comment by MiBaDK** [comment]
Having dreams about one day waking up and seeing a patch for this one or at least assigned a milestone. That would be a great day :)

**Comment by MiBaDK** [comment]
https://www.bountysource.com/issues/41273748-seems-like-a-bug-in-a-bigquery-join

Anyone up for joining?

**Comment by MiBaDK** [comment]
Hi, a proposed fix has been committed some time ago. Any chance of getting this in a release soon :)

**Comment by vbarroso** [comment]
I also would like to know about this issue :)

**Comment by vbronsky** [comment]
Any news about this Fix? Any chance to add this to release?
