### ISSUE TITLE
Unable to edit metadata of model

### ISSUE THREAD

**Issue by dstollie** [metabase/metabase#42203]
### Describe the bug

In the metadata editor of a model I would like to update the name of the columns, updating a column works but navigating through the other columns does not work. This also triggers a javascript error. The error occurs on webkit based browsers as safari
![Screenshot 2024-05-03 at 11 12 38](https://github.com/metabase/metabase/assets/7110155/06757e7a-a06b-4e97-b4ae-dd8ffc4c61c8)

### To Reproduce

1. Go to 'Metadata editor of a model'
2. Click on 'A random column'
3. Scroll down to '-'
No error but the column is not being selected and I get an error in dev-tools of the browser

### Expected behavior

Selection the clicked column

### Information about your Metabase installation

```JSON
- Latest version of Chrome and Safari
- Metabase version 0.49.8 latest
```

### Severity

annoying

### Additional context

We cannot deliver metadata model production ready

**Comment by zbodi74** [comment]
@dstollie - I tried to replicate this but wasn't able to. Could you record a quick video showing what's happening? 
Also, are there any plugins installed on your end?

**Comment by Tony-metabase** [comment]
@dstollie can you answer @zbodi74 questions please so we can investigate further

**Comment by darksciencebase** [comment]
@dstollie are you still experiencing this issue?

**Comment by ranquild** [comment]
I can only repro with multiple self joins where exactly the same column is selected.
