### ISSUE TITLE
Converting a Question to SQL causes map to render no colors and NaN - NaN for the legend

### ISSUE THREAD

**Issue by seafoodbuffet** [metabase/metabase#4221]
- Chrome Version 55.0.2883.95 (64-bit)
- OS X 10 Sierra
- PostgreSQL 9.6
- Metabase v0.22.0 Built on 2017-01-10
- Running in Docker
- Internal H2 database

Converting a question to SQL without changes causes the map render to work differently than the question that created it.

1. Create a question using "New Question"
2. Have the query return fields for a numeric metric (e.g. count of customers), group by State (render a region map, United States, select the count for the metric and State for the region)
3. See that it renders appropriately
4. Click to see the SQL and click on "Convert this question to SQL"
5. Click on Get Answer
6. Re-select metric and region
7. Instead of the same map render, the map shows black highlights in each region and the legend displays NaN - NaN for each range.

**Comment by tlrobinson** [comment]
There are two issues here:

1. it's more difficult for us to automatically pick the "correct" columns from SQL queries because we don't know the structure of the query, which is why you have to manually select the columns.
2. there's a bug in the map visualization, I've fixed it in #4222
