### ISSUE TITLE
The filter by time dialogue at the bottom of the screen should include "Include This X"

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#42220]
**Is your feature request related to a problem? Please describe.**
I often like to see today \ this week \ this month when filtering on time and I use the time filtering options at the bottom of the UI a lot. So it's really annoying that I have to go somewhere else to choose this week \ day \ month.

Here's a loom:  https://www.loom.com/share/29c1f6aa28be461f9095d01e04aa2a52?sid=cfbddc53-51f9-4d6e-8546-9ce4f9117d6f

**Describe the solution you'd like**
I'd like a checkbox or whatever to choose it where I'm choosing the other time things:
<img width="1892" alt="image" src="https://github.com/metabase/metabase/assets/22856340/fcafa3f5-a85a-4428-b241-2f5c037b3971">

**Describe alternatives you've considered**
I can go into the filter dialogue, but why do I have to do that?

**How important is this feature to you?**
It's a little thing that would make my experience more pleasant and chill and less annoying.

**Comment by nemanjaglumac** [comment]
Implemented as part of https://github.com/metabase/metabase/issues/44096
