### ISSUE TITLE
Window function does not generate a correct inner query

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#42234]
### Describe the bug

Testing the new wf feature I saw that it does not generate correctly the inner query
https://stats.metabase.com/question/17517-window-function-test/notebook

### To Reproduce

1) see the question above

### Expected behavior

it should work/generate the query correctly

### Logs

NA

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

**Comment by perivamsi** [comment]
this is not a bug, you are using `Offset` incorrectly

the correct expression should be something along the lines of `Offset(Sum([Total]), 1)`
