### ISSUE TITLE
Disappearing Edit button on saved questions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4223]
On master, when you edit a question and save it, the Edit button disappears until you refresh the page:

![screen shot 2017-01-24 at 10 23 47 am](https://cloud.githubusercontent.com/assets/2223916/22260780/4767e496-e21f-11e6-8d78-1854b6a631c1.png)

**Comment by kdoh** [comment]
Pretty sure this was already reported and fixed in #4142 and #4164

**Comment by camsaul** [comment]
Duplicate of #4142

**Comment by camsaul** [comment]
oops. Maz this is fixed in the 22.1 branch
