### ISSUE TITLE
Overflow menu on collections list are not disappearing

### ISSUE THREAD

**Issue by vbenedetti** [metabase/metabase#42235]
### Describe the bug

In stats, when browsing any collection, the overflow menus (aka . . .) are overlapping each other once you go from row to row, the second one overlaps with the first and so on sequentially. 

### To Reproduce

1. Go to any collection
2. Click on the '...' menu in any row,
3. Repeat step 2 in the row below or above and keep repeating

### Expected behavior

The second menu you access should make the previous menu disappear so that there's only one menu on the screen at a given moment.

### Information about your Metabase installation

```JSON
Browser: Version 123.0.6312.123 (Official Build) (arm64)
OS: Mac OS Ventura 13.2
Metabase version: You're on version vUNKNOWN
Built on 2024-05-03
Hash: 395c898
```

### Severity

annoying

### Additional context

https://www.loom.com/share/f8c3b1ae39664a358e67e4b3c92702ae?sid=0f462d9f-95fe-457e-b3a0-3a1d5d514fa3

**Comment by calherries** [comment]
I tested on the release branch (`dd71f00dd7`) and couldn't reproduce it, but I can on master (`43c0ce979a`).
