### ISSUE TITLE
Ingest multiple MySQL schemas/databases from the same server

### ISSUE THREAD

**Issue by MChamberlin** [metabase/metabase#42248]
According to the [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_schema), "a schema is synonymous with a database." And [vice versa](https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_database):
> Users coming from an Oracle Database background may find that the MySQL meaning of a database is closer to what Oracle Database calls a schema.

In fact, you can substitute the keywords in MySQL SQL syntax.

It is quite common in practice to have multiple databases/schemas on a single MySQL server and to join between them. However, Metabase currently only allows connecting to a single MySQL database/schema per server, which you must specify in the Metabase DB connection configuration.

This arbitrarily prevents cross-database/schema joins within Metabase, even though they are fully supported by MySQL. 

Given that "a schema is synonymous with a database" in MySQL, can Metabase instead ingest multiple databases from the same MySQL server, and register these as separate _schemas_ within the same Metabase DB connection, similar to what is done for schemas in PostgreSQL and other database engines?

This issue is essentially the same as https://github.com/metabase/metabase/issues/5887, but I wanted to give more context and get fresh eyes on it, since that issue is from 2017 and is still unresolved.

Thanks!

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/22237

**Comment by parsaap** [comment]
> related to [#22237](https://github.com/metabase/metabase/issues/22237)

It's not quite similar to this issue. For #22237, you actually need to use something like Presto to query multiple databases, but with MySQL, a schema is just a kind of namespace for tables. I've been waiting for this feature for quite some time. It'll be very useful, and should not be hard at all to implement. The database itself handles all the joins and everything, you just have to prefix the table name with the schema name in the query generator and some UI changes to support this.

**Comment by paoliniluis** [comment]
We should close this in favor of https://github.com/metabase/metabase/issues/5887 then
