### ISSUE TITLE
Add client-side sorting for SQL queries

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4226]
Sorting table by column on dashboard is working:
![image](https://cloud.githubusercontent.com/assets/1708680/22287513/42d4512c-e304-11e6-8d9e-392feaca280c.png)

But sorting table in question card isn't working:
![image](https://cloud.githubusercontent.com/assets/1708680/22287555/6352571e-e304-11e6-8f03-1c4eca837f6c.png)

Metabase 0.22.0
Google Chrome
Question by SQL Query

**Comment by camsaul** [comment]
@anki-code just add an `ORDER BY` clause.

**Comment by anki-code** [comment]
@tlrobinson my use case:

I have a table with many parameters. It's really helpful table. Users of this table like to sort the table by fields (in this case client-side sorting - is a working solution for them) and I've made special dashboard **only for this table**. I want to reduce count of dashboards in the list and remove this dashboard. But I can't do it because sorting isn't working.

@camsaul it's working for me but it's not working for my users.

**Comment by anki-code** [comment]
@tlrobinson  One thought:
> We can't sort SQL questions because we don't know how to automatically modify the query
Ok. But you know total count of rows from DB. If count of rows <= count of rows you display then you can enable the client side sorting feature.

**Comment by tlrobinson** [comment]
We don't know which table(s) a SQL query is based on.

**Comment by anki-code** [comment]
@tlrobinson You have a limit (1000 rows). What if enable sort if count of rows below the limit?

**Comment by tlrobinson** [comment]
I don't think that limit applies to SQL questions.

**Comment by anki-code** [comment]
@tlrobinson For example:
![image](https://cloud.githubusercontent.com/assets/1708680/22864824/7247b6e2-f169-11e6-98f4-5f55fdaf4e2a.png)

**Comment by camsaul** [comment]
@anki-code if you want to sort your SQL query why don't you just add an `ORDER BY` clause?

**Comment by tlrobinson** [comment]
@anki-code You're right, however we won't know if you've added your own `LIMIT` clause.

**Comment by anki-code** [comment]
@tlrobinson I think it's not a problem. Client side sorting better than nothing.

**Comment by anki-code** [comment]
Seems like this issue was resolved by adding "Analyze the results" feature.

![image](https://user-images.githubusercontent.com/1708680/29027856-14439bea-7b8b-11e7-8e9c-84e99765660c.png)

![image](https://user-images.githubusercontent.com/1708680/29027952-6cc3ec66-7b8b-11e7-932f-1cfbbb69e510.png)

**Comment by anki-code** [comment]
This is still actual. And after 3 years of pain I still think that client side sorting better than nothing.

**Comment by flamber** [comment]
Closing in favor of #11329, which has more upvotes and detailed description of the limitation.
