### ISSUE TITLE
The decimal columns in starrocks cannot be mapped the specific type in metabase

### ISSUE THREAD

**Issue by Jerrylovescoding** [metabase/metabase#42264]
### Describe the bug

The decimal columns whose 'database_type' are 'DECIMAL64' or 'DECIMAL128' in StarRocks cannot be mapped the specific types like 'Decimal' in metabase, which causes that we can't use such columns to filter.

Pic1:
![image](https://github.com/metabase/metabase/assets/25549512/0c7c1f65-87ea-4300-b386-318a5fe22187)
Pic2:
![image](https://github.com/metabase/metabase/assets/25549512/4a304b57-d5a9-4985-b38a-2474ecdcb190)
Pic3:
![image](https://github.com/metabase/metabase/assets/25549512/339c66ba-ed0b-4057-bcc8-b44e8a20b369)

### Information about your Metabase installation

- Operating system: CentOS 7
- Database: StarRocks
- Metabase version: v0.49.6
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

### Severity

Medium. We can't use some decimal columns to filter when we use question editor.

**Comment by calherries** [comment]
StarRocks does not have its own MB driver, I think it only works with the MySQL/MariaDB driver by "coincidence". If you'd like Metabase to support StarRocks upvote the issue [here](https://github.com/metabase/metabase/issues/28081).
