### ISSUE TITLE
[dc.js migration] Data labels auto-compactness should not be recomputed on hovers

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#42281]
Data labels auto-compactness should not be recomputed on hovers because it causes noticeable lags.
Extend `ChartMeasurements` with a property `dataLabelsFormat: "full" | "compact" | "default"` and set it based on the viz settings and the auto-compactness algorithm.

**Comment by alxnddr** [comment]
@JesseSDevaney I'll take this since it is convenient to fix while implementing https://github.com/metabase/metabase/pull/42247

**Comment by JesseSDevaney** [comment]
- Closed by: https://github.com/metabase/metabase/pull/42616
