### ISSUE TITLE
Split y-axis manually

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4228]
Now splitting works automatically:
![image](https://cloud.githubusercontent.com/assets/1708680/22295144/eb5ba6b6-e326-11e6-8939-6365cfd47111.png)

And I faced with problem when I want to show "Count" metric and "Percent" metric on the one chart:

![image](https://cloud.githubusercontent.com/assets/1708680/22295280/728dcaf6-e327-11e6-9477-69dbed173501.png)

**Comment by tlrobinson** [comment]
Duplicate of #3242
