### ISSUE TITLE
Implement minimal viable serialization for Trash

### ISSUE THREAD

**Issue by johnswanson** [metabase/metabase#42301]
Serialization for the Trash collection needs to be carefully considered, and I hadn't researched serialization well enough before now to know exactly what it entailed. My understanding is still a bit limited, but I think the minimum viable v1 implementation is something like this:

- if you specify `--collections` to export, we should serialize items that were trashed _from_ one of those collections, as well as the items directly in that collection
- we do not need to serialize the Trash collection itself - it should be the same across all instances. But we can serialize it if not doing so is difficult - it's a few lines of YAML, and we'll set the `entity_id` such that the serdes system recognizes that it's the same entity in the destination database
- if you don't specify `--collections`, we should serialize items that are trashed, just like we do currently.
- `trashed_from_collection_id` should be converted to an entity ID on extraction, and back on load, just like `collection_id`
- `trashed_from_location` needs a similar conversion process, modeled on `location`

I think the most difficult part of this might be ensuring that the Trash collection is exported if necessary, while _not_ exporting _every_ item in the Trash. The existing serialization machinery has logic preventing "escaping", where e.g. a dashboard shows a card in a non-exported collection. Currently in this case it just warns the user and does not export any of the items. We'll need a way to say "include this Collection in the serialization set... but not everything in it, just those items that were going to be included anyway."

**Comment by bshepherdson** [comment]
Each model (eg. Dashboards) can customize what it "contains", in terms of what should be serialized, when you do selective export (eg. `--collections`). It's powered by the multimethod `descendants` (not to be confused with `dependencies`!).

So it won't be hard to achieve the first point, by adjusting the `descendants` for collections to include both items in the collection and items in the Trash which were trashed from that collection.
