### ISSUE TITLE
Manual db sync doesn't indentify column name changes

### ISSUE THREAD

**Issue by Hennisa** [metabase/metabase#4230]
Browser and the version: Chrome 53.0.2785.143 (64-bit)
Operating system: OS X 10.11.6
DB: Redshift
Metabase internal database: Postgres
Metabase version 0.22.0
Metabase hosting environment: Elastic Beanstalk

I changed a column name from **epoch** to **date_local_id** in my source db and started a manual db sync in the admin panel around 30 mins ago, however now all my questions to this table are failing, because Metabase is still trying to get the table with original column name **epoch** , Doesn't the manual synch get changes in column names?

Here's the error I get when I am trying to view the raw data in the related table after the manual sync:
_ERROR: column import_trans_availability_request_norm.epoch does not exist_

Custom SQL queries run normally. 

I can also see in the data model section that the table column name is still the old one (in the original schema section).

**Comment by camsaul** [comment]
@Hennisa when Metabase syncs your DB it will find the new column. Since syncing takes a while it isn't ran all the time, and it sounds like your DB hasn't been synced again yet. You can trigger a manual sync from the admin panel.

**Comment by camsaul** [comment]
Oh sorry I didn't see that you had triggered a manual sync. This should be working, but it might be a bug. I will write a test and see if I can repro it

**Comment by Hennisa** [comment]
For your information, I did not do any changes in the table name, just changed to order of a few columns and renamed them. Just discovered that one of the tables I changed yesterday hasn't synced either. This has been working in the previous versions as I've been doing schema changes before & successfully syncing them.

**Comment by Hennisa** [comment]
Seems like the problem was in our end. The sync works normally now. I'll close this issue. Thanks!
