### ISSUE TITLE
Auto-detect Latin/Arabic encoded text in an uploaded csv file

### ISSUE THREAD

**Issue by El3aber** [metabase/metabase#42313]
### Describe the bug

What I did:
1- Enabled uploading csv files from settings to (PostgreSQL Database)
2- Created the attached csv file 
[test.csv](https://github.com/metabase/metabase/files/15231189/test.csv)
3- Uploaded csv 
4- ![Screenshot 2024-05-07 092331](https://github.com/metabase/metabase/assets/62171887/d83b4bb5-917e-4590-85aa-41337fc65f72)

### To Reproduce

1. create a csv file and fill it with data in arabic letters or download the attached one
[test.csv](https://github.com/metabase/metabase/files/15231236/test.csv)

2. Enable Uploading csv from settings (https://yourmetabaselink/admin/settings/uploads)

3. Upload the csv

4.Display the Uploaded csv & See error

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.0-200.131.27.1.el8uek.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.36-0ubuntu0.22.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-16",
      "tag": "v0.49.6",
      "hash": "5abf130"
    },
    "settings": {
      "report-timezone": "Asia/Riyadh"
    }
  }
}
```

### Severity

blocking some users

**Comment by calherries** [comment]
@El3aber the text in the CSV appears to be encoded with Latin/Arabic encoding. https://en.wikipedia.org/wiki/ISO/IEC_8859-6. If you first convert the file to UTF-8 encoding, the upload should work.

Here's the test file I uploaded:
[utf8_test.csv](https://github.com/metabase/metabase/files/15234303/utf8_test.csv)

And here's how it is displayed in Metabase:
<img width="393" alt="image" src="https://github.com/metabase/metabase/assets/39073188/481f86ff-4c06-414f-98e9-eaf70533e654">

I tested uploading the original test file and uploaded it to Google Sheets, and detects the correct encoding.
