### ISSUE TITLE
Ensure we canonicalize MBQL tokens on the frontend

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4233]
A bunch of frontend code was written before MBQL was [changed to case-insensitive](https://github.com/metabase/metabase/wiki/Query-Language-'98#tokens) and wasn't updated. This hasn't been a total disaster because generally the frontend generates all the MBQL it consumes, but bugs are starting to creep in because of it (e.x. #4231)

I've started using `mbqlEq(a, b)` in place of `a === b` when comparing MBQL strings. We should migrate all of the code to that, or do something like what the backend does and canonicalize/wrap the whole MBQL tree.

Progress:

* [x] `time-interval` #4234
* [x] `fk->` #4423
* [x] `field-id` #4423
* [x] `datetime-field` #4423
* [x] `relative-datetime` #4423
* [x] `template-tag` #4423 
* [ ] everything else

Also, note certain tokens like `METRIC` seem to still be case sensitive ¯\\_(ツ)_/¯ 

* [ ] `METRIC`
* [ ] `SEGMENT`
* ?

**Comment by camsaul** [comment]
Yeah, `METRIC` and `SEGMENT` were added in #1624 and sort of bolted-on to the rest of the query processor in a way that didn't really follow any of the patterns that had already been established there. 

So those still have to be `METRIC` and `SEGMENT` (capitalized) for now. (I'm equally annoyed by this.)

FWIF they weren't ever added to the [MBQL ref](https://github.com/metabase/metabase/wiki/Query-Language-'98), so I like think of them as an unofficial extension to MBQL, which helps explain away their weird behavior 😉

**Comment by camsaul** [comment]
Closing as already implemented since this is handled by the shared Cljs code now
