### ISSUE TITLE
Copy question info/description when duplicating.

### ISSUE THREAD

**Issue by subzet** [metabase/metabase#42348]
**Is your feature request related to a problem? Please describe.**
When creating a question from a saved one, the info/description of the previous question is lost. If you want to create a question that has a different aggregation, for example `Daily orders` and change to `Weekly orders` the description for the question will be the same, only changing the time aggregation.

**Describe the solution you'd like**
When saving a new question from a previous saved question, it would be awesome that the description for the new question is copied from the original question.

**Comment by nemanjaglumac** [comment]
Related https://github.com/metabase/metabase/issues/41196

**Comment by nemanjaglumac** [comment]
This has been implemented already.
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/SaveQuestionForm/util.ts#L81-L82

And we have a test that ensures this functionality.
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx#L404-L407
