### ISSUE TITLE
Can't edit multiseries dashboard card if underlying visualization type is changed

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4235]
If you have a dashboard card based on a saved question with a visualization setting that allows for adding series (line/bar/area chart, scalar), and then add a series and save the dashboard, but then you go and modify the first saved question's underlying visualization setting to something like table or pie chart, the added series on the dashboard card still shows up in the legend, but isn't displayed on the chart.

The main problem is that if the card is in this state, you can't remove/edit the added series.

So, we could either allow the user to modify the added series so they could remove it, or we could hide the legend item(s) that shows the additional series. Don't know if we need a warning icon+message or something.

I would not want to just blindly _remove_ the additional series just because some yahoo changed the visualization setting for one of the underlying saved questions.

Normal card with added series:
![bar chart](https://cloud.githubusercontent.com/assets/2223916/22309834/d3cc4ab6-e301-11e6-9f73-73f8a6fc90c2.png)

First saved question has been modified to be a pie chart, so now the card looks like this, showing the 2nd series in the legend, but not in the chart:
![pie](https://cloud.githubusercontent.com/assets/2223916/22309865/f7b90b76-e301-11e6-94b4-64cbd29562c6.png)

First saved question has been modified to be a table, so now the card looks like this, showing the 2nd series in the legend, but not in the table:
![table](https://cloud.githubusercontent.com/assets/2223916/22309849/e7df891e-e301-11e6-8c7a-cf105c4e16ab.png)

**Comment by tlrobinson** [comment]
I think the easiest fix would be to show the "edit" button if there's ever more than one card on a dashcard, regardless of whether the current visualization type supports multi series.

Alternatively we could lock a dashcard's visualization type to the initial card's visualization type.

**Comment by mazameli** [comment]
> Alternatively we could lock a dashcard's visualization type to the initial card's visualization type.

Not sure what you mean by this.

**Comment by tlrobinson** [comment]
If a dashcard has multiple series then "remember" what the initial visualization type is, even if the underlying cards change to a different one.

Currently we use whatever the first card's visualization type and settings were, but maybe that doesn't make sense  with multiseries.

**Comment by mazameli** [comment]
Gotcha.
