### ISSUE TITLE
Don't expose query definition (SQL or GUI) to users who wouldn't be able to write the query

### ISSUE THREAD

**Issue by brnt** [metabase/metabase#4237]
Browser: Chrome 55.0.2883.95 (64-bit)
OS: OSX 10.12.2
Database: PostgreSQL
Metabase: 0.22.0
Host: Heroku
Metabase DB: PostgreSQL

Steps to reproduce:
Create a group. Add a user with no permissions (and no other group memberships) to the group. Set group permissions:
    Data Access -> Unrestricted Access
    SQL Queries -> No Access

<img width="1123" alt="screen shot 2017-01-25 at 5 18 14 pm" src="https://cloud.githubusercontent.com/assets/1072638/22315245/d5e202de-e322-11e6-8349-63ca50bf282f.png">

(the last group in the list--the furthest right)

Expected functionality: The user in the group with granular permissions should not be able to view the SQL query, only the answer to the question.

Actual functionality: The user is presented with the (non-editable) query above the rendered answer to the question. 

<img width="1086" alt="screen shot 2017-01-25 at 5 18 31 pm" src="https://cloud.githubusercontent.com/assets/1072638/22315256/e61a36a8-e322-11e6-8bae-ee7986341656.png">

**Comment by tlrobinson** [comment]
We shouldn't expose SQL (both in `card.dataset_query.query` and `result.data.native_form`) to users who aren't able to write SQL questions, and likewise we shouldn't expose queries (`card.dataset_query.query`) to users who don't have sufficient data permissions to execute that query from scratch.

There will be some trickiness around the filter widgets we generate based on SQL `template_tags`, but as part of embedding the backend will need to be aware of those, and could generate `card.parameters`.

**Comment by flamber** [comment]
Closing in favor of #8773 - upvote by clicking :+1: on the first post
