### ISSUE TITLE
Metabase REST API setup token

### ISSUE THREAD

**Issue by jojojojochen** [metabase/metabase#4240]
I am trying to use "POST /api/setup/" and it requires a token field. When I tried a dummy token, the error message was "Token does not match the setup token." I am wondering where can I find the setup token.

**Comment by camsaul** [comment]
@jojojojochen You'll see the setup token in the console output from Metabase when you first launch.

**Comment by rulio** [comment]
@camsaul I have he same question.  I don't believe the token is output in the log anymore.  It appears to have been removed in this commit 0a559587298eec9c1b6c3ccb12aa80f9dadf68ed. 

Is there some other way to generate a setup token?

**Comment by rulio** [comment]
For anyone searching for this question in the future, here is the solution I found.  Setup token can be retrieved from the /api/session/properties endpoint.  It contains a setup_token key.  Once setup is complete that key will be null.

**Comment by camsaul** [comment]
Thanks @rulio. @jojojojochen if that answers your question feel free to close this issue 👍
