### ISSUE TITLE
Feature request: visible entity IDs for every entity created in the system 

### ISSUE THREAD

**Issue by danielrosehill** [metabase/metabase#42408]
Hi guys,

Hope it's okay to drop in with another feature request. As I roll out Metabase, these are coming to me organically from time to time.

Something that strikes me is that as the system begins to scale, it quickly becomes hard to retrieve visualisations through the "quick" mechanisms of searching in the search bar and choosing from one of the dropdown populations.

Something I think that would be very valuable: every "entity" that you create (whether that's a dashboard, a question, a model) has an entity ID (I imagine this already exists in the backend).

Here are a couple of ideas for how this could be useful:

1: Permalink masking: visit yourmetabase.com/[entityid] to jump to the target URL 

2: To expedite retrieval of the right visuals between colleagues. For example, I could tell a colleague to search for 12345. If this retrieved the desired entity there would be no chance of ambiguity if objects with similar names were stored in the system. 

- Daniel

**Comment by Tony-metabase** [comment]
That's what happens actually. If you look at the URL when you try to edit a person, go to a dashbaord or even a collection:

<img width="1439" alt="image" src="https://github.com/metabase/metabase/assets/110378427/50b49c5e-98c7-4b96-b19b-e7701975a175">

You will notice that each collection and so on will carry an ID that if placed in the proper URL it will render that object for that context.

To add with that there is also an entityID in the Table but that ID is used for Serialization purposes
