### ISSUE TITLE
Email Reports showing incorrect data

### ISSUE THREAD

**Issue by OdinTallBeard** [metabase/metabase#42460]
**Is your feature request related to a problem? Please describe.**
the email reports are not great quality.

I have seen emails where a graph is displayed fine then next week it is grayed out with that image silhouette.

The trials and repeats chart is just a normal line chart by quarter but it looks so bad and confusing with incorrect values in the email report.

**Describe the solution you'd like**
Fix the email to correctly display what is on the dashboard

**Describe alternatives you've considered**
NA

**How important is this feature to you?**
11 /10 
We need to have proper automated emails

**Additional context**
This is so unbelievably vital for my organization and I believe very important for your platform to perfect to be a top data analysis platform imho, having automated reports with no error. This is a very important part of data reporting so this truly needs to be improved.

ty very much this is very important to me

<img width="418" alt="Screenshot 2024-05-09 at 12 00 38 PM" src="https://github.com/metabase/metabase/assets/121153315/f8f62d33-186a-4adf-8637-7a5af1632de1">

<img width="56" alt="Screenshot 2024-05-09 at 12 05 39 PM" src="https://github.com/metabase/metabase/assets/121153315/e74adae3-151d-464f-b10f-e95b6a94930e">

**Comment by Tony-metabase** [comment]
Yeah there are a lot of issues around Static Viz and line charts but most of those should be closed with release 50 since the StaticVic will convert to eCharts so we shouldn't have these kind of inconsistencies anymore. 

Closing as duplicate https://github.com/metabase/metabase/issues/30315
