### ISSUE TITLE
Bug: Fatal Error, Metabase server termination

### ISSUE THREAD

**Issue by omassamo** [metabase/metabase#4246]
![screen shot 2017-01-26 at 11 33 01](https://cloud.githubusercontent.com/assets/4628377/22344826/ee852434-e3fd-11e6-9b58-f9c687292894.jpg)
#Description
Upon launching mac app I get a Fatal Error The Metabase server terminated unexpectedly. This happened after updating to 0.22.1.0.

##System details
Screenshot including system details https://cl.ly/iuHy 
- maOS sierra 10.12.1 MacBook Pro (Retina, 13-inch, Late 2013)
- metabase mac app version 0.22.1.0
- database MySQL (mariaDB)

**Comment by tlrobinson** [comment]
@omassamo Could you see if there are any errors in the logs? You can open Console.app and search for "metabase".

**Comment by camsaul** [comment]
@omassamo can you just include the screenshot directly in your post?

**Comment by omassamo** [comment]
@camsaul Screenshot included.

**Comment by camsaul** [comment]
@omassamo Could you see if there are any errors in the logs? You can open Console.app and search for "metabase".

**Comment by omassamo** [comment]
@camsaul I see following errors:

error	09:33:27.712030 +0100	Metabase	TIC TCP Conn Failed [27:0x600000184fa0]: 1:61 Err(61)
error	09:33:27.713764 +0100	Metabase	HTTP load failed (error code: -1004 [1:61])
error	09:33:27.714579 +0100	Metabase	NSURLConnection finished with error - code -1004

**Comment by amadeu01** [comment]
I'm having the same issue, I can't even setup the app

![screenshot 2017-01-27 07 29 51](https://cloud.githubusercontent.com/assets/11631092/22366171/6d6273ba-e462-11e6-80ce-c76c603f017d.png)

**Comment by camsaul** [comment]
@amadeu01 can you do the same thing and let us know what errors you see in `Console.app`?

**Comment by camsaul** [comment]
@metabase/core-developers can anyone else repro this? My computer isn't on Sierra

**Comment by mazameli** [comment]
I couldn't repro this on Sierra, but the only DB I have connected is the sample dataset (H2).

**Comment by camsaul** [comment]
I don't think that should matter, from the console output it looks like Metabase isn't even launching

**Comment by camsaul** [comment]
@camsaul anything else (besides errors)?

**Comment by camsaul** [comment]
@omassamo anything else (besides errors)?

**Comment by mazameli** [comment]
I'm just noticing the other two guys have versions of Sierra > than 10.12.0, so I'm going to try upgrading real quick to 10.12.3 adn see if the Mac app still works.

**Comment by mazameli** [comment]
Still works for me on macOS 10.12.3:

![screen shot 2017-01-27 at 10 21 17 am](https://cloud.githubusercontent.com/assets/2223916/22382410/6f46e4dc-e47a-11e6-9010-d876b10cb5cd.png)

**Comment by camsaul** [comment]
weird. @amadeu01 @omassamo can you try restarting your computers and seeing if it works after that? I have a theory that some process is left hanging somewhere which keeps it from launching properly

**Comment by amadeu01** [comment]
![screenshot 2017-01-28 00 16 02](https://cloud.githubusercontent.com/assets/11631092/22393514/0a29b848-e4ef-11e6-9f90-fdd686768e0e.png)

**Comment by omassamo** [comment]
Restarting does not help. I now also deleted the app, downloaded and re-installed. I'm still having the exact same issue. 

error	08:58:15.047631 +0100	Metabase	TIC TCP Conn Failed [56:0x600000382220]: 1:61 Err(61)
error	08:58:15.047896 +0100	Metabase	HTTP load failed (error code: -1004 [1:61])
error	08:58:15.047959 +0100	Metabase	NSURLConnection finished with error - code -1004
 
Anyone has any other suggestions?

**Comment by camsaul** [comment]
@omassamo It might be a problem with the application DB. Backup the files in `~/Library/Application Support/Metabase` and delete that directory and then start Metabase. Let me know if that works

**Comment by omassamo** [comment]
@camsaul Thanks. Unfortunately did not work. 
![screen shot 2017-01-30 at 20 00 04](https://cloud.githubusercontent.com/assets/4628377/22437064/d2cf176e-e726-11e6-8307-980933ac7a97.jpg)

**Comment by tlrobinson** [comment]
Possibly the same issue: http://discourse.metabase.com/t/metabase-isn-t-working-anymore-after-update/1106/2

**Comment by tomclaus** [comment]
Same issue here on **Sierra 10.12.1** .
When starting I get the Fatal Error message.

![Console](https://www.dropbox.com/s/im7dr737uflp3lq/Screenshot%202017-01-31%2010.22.48.png?dl=1)

**Comment by camsaul** [comment]
Hi everyone, we figured out how to reproduce this issue and pushed a new build that addresses this. [Download the fixed version here](https://s3.amazonaws.com/downloads.metabase.com/v0.22.2/Metabase.dmg).

Sorry about this issue, please let us know if you have any more problems!

**Comment by omassamo** [comment]
Bliss! Thanks for the help! ![screen shot 2017-02-01 at 20 16 29](https://cloud.githubusercontent.com/assets/4628377/22522298/5b2a80e0-e8bb-11e6-9b06-1dc696f17dab.jpg)

**Comment by kikohernandez92** [comment]
Hey everybody, I know this is a closed issue, but I'm having it happen on macOS Sierra 10.12.5 after updating from 10.12.4, on latest Metabase App

**Comment by camsaul** [comment]
@kikohernandez92 what do you see in `Console.app`

**Comment by kikohernandez92** [comment]
TIC TCP Conn Start [14:0x600000385bd0]
TIC TCP Conn Event [14:0x600000385bd0]: 3 Err(61)
TIC TCP Conn Failed [14:0x600000385bd0]: 1:61 Err(61)
TIC TCP Conn Cancel [14:0x600000385bd0]
TIC TCP Conn Destroyed [14:0x600000385bd0]
HTTP load failed (error code: -1004 [1:61])
NSURLConnection finished with error - code -1004

**Comment by camsaul** [comment]
@kikohernandez92 can you launch the app, and filter by "Metabase" and post those logs? We want the ones relevant to the crash

**Comment by kikohernandez92** [comment]
I'm using Metabase 0.24.0.1, on macOS Sierra 10.12.5. As I said, worked flawlessly on 10.12.4, but is failing to start in 10.12.5, and an OS rollback is not possible

**Comment by camsaul** [comment]
@kikohernandez92 cool, but what does that have to do with posting the relevant logs 😉 ?

**Comment by kikohernandez92** [comment]
![screen shot 2017-05-23 at 3 18 35 pm](https://cloud.githubusercontent.com/assets/12051998/26372275/588926d6-3fcb-11e7-9029-7db0e78bf219.png)

These are the only logs for Metabase, exactly the ones in the screenshots above

**Comment by kikohernandez92** [comment]
Reinstalling does not fix the issue, either

**Comment by rawrmaan** [comment]
I'm experiencing this on SIerra with Metabase 0.24.0.1 too. The Console messages are the same as @kikohernandez92.

**Comment by kikohernandez92** [comment]
Latest Sierra? @rawrmaan

**Comment by rawrmaan** [comment]
@kikohernandez92 My Sierra was one minor version behind and I did just do a restart/update to latest Sierra which fixed Metabase. I should definitely add that the problem started after my system gave me one of those "out of disk space, you should terminate some applications" dialogs. So I'm guessing the OS killed some important process related to Metabase?

**Comment by kikohernandez92** [comment]
@rawrmaan I'm not that sure, 'cuz the issue started for me after updating from macOS 10.12.4 to 10.12.5 and I have plenty space on my machine.

**Comment by fandomfilms** [comment]
Reinstalling doesn't fix the issue for me either

default	14:17:00.853790 -0500	Metabase	TIC TCP Conn Start [273:0x61800038f7d0]
default	14:17:00.857335 -0500	Metabase	TIC TCP Conn Event [273:0x61800038f7d0]: 3 Err(61)
error	14:17:00.857365 -0500	Metabase	TIC TCP Conn Failed [273:0x61800038f7d0]: 1:61 Err(61)
default	14:17:00.857380 -0500	Metabase	TIC TCP Conn Cancel [273:0x61800038f7d0]
default	14:17:00.857401 -0500	Metabase	TIC TCP Conn Destroyed [273:0x61800038f7d0]
error	14:17:00.857513 -0500	Metabase	HTTP load failed (error code: -1004 [1:61])
error	14:17:00.857597 -0500	Metabase	NSURLConnection finished with error - code -1004

**Comment by camsaul** [comment]
We've actually opened a new issue for this at #6068. 

@fandomfilms try using 0.25.2 (http://downloads.metabase.com/v0.25.2/Metabase.dmg) which seems to work for everybody. There's an issue with the latest version of the Mac App, 0.26.1, that's causing it to fail to launch for a few people. I'm having trouble reproducing it but still trying to figure out what's going on.

Chime in on #6068 and let me know whether 0.25.2 works for you. Keep an eye on that issue for further updates.
