### ISSUE TITLE
[BE] [QP] Check which drivers lose metric support because of nested queries

### ISSUE THREAD

**Issue by metamben** [metabase/metabase#42474]
- [x] Athena via sql-jdbc
- [x] BigQueryCloudSDK via sql
- [ ] Druid
- [x] Druid-JDBC via sql-jdbc 
- [x] H2 via sql-jdbc
- [x] Mongo
- [x] MySQL via sql-jdbc
- [x] Oracle via sql-jdbc
- [x] Postgres via sql-jdbc
- [x] Presto-JDBC via sql-jdbc
- [x] Redshift via postgresql
- [x] Snowflake via sql-jdbc 
- [x] SparkSQL
- [x] SQLite via sql-jdbc
- [x] SQLServer via sql-jdbc
- [x] Vertica via sql-jdbc

**Comment by perivamsi** [comment]
Only old druid does not support this (out of all the drivers we own)
