### ISSUE TITLE
Installation Follow up email received every day

### ISSUE THREAD

**Issue by gboudreau** [metabase/metabase#4253]
Metabase installed on AWS Elastic Beanstalk, per the latest documentation.
Internal database is the default, a RDS instance running Postgres.
Metabase version: 0.22.0

Every day, I receive the same email. Subject: `[Metabase] Tell us how things are going.`

I looked quickly at the code, and it seems it wouldn't send that email if the `follow-up-email-sent` setting is `true`, and I checked that it is, using

    SELECT value FROM setting WHERE key = 'follow-up-email-sent'`

Result: `true`

Any idea what might be wrong..?

The email definition is here: https://github.com/metabase/metabase/blob/1810ab1d181ddd11ab31386ae7ee5511c8773096/src/metabase/email/messages.clj#L160
The `follow-up-email-sent` setting is loaded here: https://github.com/metabase/metabase/blob/1810ab1d181ddd11ab31386ae7ee5511c8773096/src/metabase/task/follow_up_emails.clj#L27
And it is used here: https://github.com/metabase/metabase/blob/1810ab1d181ddd11ab31386ae7ee5511c8773096/src/metabase/task/follow_up_emails.clj#L56

**Comment by salsakran** [comment]
How embarrassing. 

Looking into it.

**Comment by camsaul** [comment]
That doesn't sound right. I'll add a test for this and fix this.

**Comment by camsaul** [comment]
I figured out why this is happening. When Metabase starts, it checks to see if a follow-up email has been sent, and if not, starts a job that runs once a day to send the follow-up email 😂
