### ISSUE TITLE
SQLITE Error "no such column"

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#42547]
### Describe the bug

Somewhere between v45 and current version this error started to appear. It was working fine in v0.45.2.1.

When I select a filter value it gives the error: `[SQLITE_ERROR] SQL error or missing database (no such column: test_table2.col1)`. 
The `test_table2.col1` exists and is selected on the right column:

![Screenshot 2024-05-12 at 20-48-14 test_card_2 · Metabase](https://github.com/metabase/metabase/assets/15974735/c5525727-67e6-4e9d-8c0c-36010ae3aefa)

### To Reproduce

- Connect a SQLITE DB.
- Create a sql card: 
```
select *
from test_table
where 1 = 1 
[[ and {{test_filter}} ]]
```
- connect the filter to a string column
- select a filter value and run the code

### Expected behavior

The shouldn't be an error

### Logs

no relevant logs

### Information about your Metabase installation

```JSON
v49.9
```

### Severity

blocking some unittests

**Comment by Tony-metabase** [comment]
You are mapping the column to a different table than the one you are filtering from .. So off course there will be no column `Col1` in table test_table

<img width="847" alt="image" src="https://github.com/metabase/metabase/assets/110378427/ae289fca-22e6-4eb3-aac0-44a7dea10dd0">

Or am i missing something?
