### ISSUE TITLE
Can't upgrade existing Heroku instance?

### ISSUE THREAD

**Issue by danconnell** [metabase/metabase#4255]
I deployed Metabase v0.20.3 using the deploy button. Now I want to upgrade to v0.22.2 by deploying from the command line, but it results in app crashes.

I tried deploying master, v0.22.2, v0.21.1 all with the same failed result. I also tried deploying v0.20.3 while on a newer one and it resulted in failure as well. I had to use Heroku's rollback to get it back to a working state.

In the logs, this is the error message I see:

`Error: Unable to access jarfile ./target/uberjar/metabase.jar`

Is there something special I have to do to upgrade on Heroku or is this a bug?

**Comment by tlrobinson** [comment]
@danconnell Just to confirm you're deploying from the `metabase-deploy` repo? https://github.com/metabase/metabase-deploy repo

**Comment by danconnell** [comment]
I was not. It worked using that repo. My bad!

Thanks 😄
