### ISSUE TITLE
Native Queries w/ an initial null causes the type of a column to be marked as "type/*"

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4256]
When doing Month over Month (or any time period over previous time period) metrics, the first value is often null. 

This makes the end column unchartable, and requires the use of a weirdo subselect 

```sql
SELECT * from 
(MYREALQUERY) a
WHERE column IS NOT NULL
```
which is kind of ghetto.

**Comment by tlrobinson** [comment]
Likely also the cause of #4128
