### ISSUE TITLE
Expose growth over time period in the query builder

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4257]
Eg, Week over Week growth should be a top level operator. Right now it requires some fairly heavy SQL. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mngr** [comment]
We released [offset() function](https://www.metabase.com/docs/latest/questions/query-builder/expressions-list#offset) in .50
Here is a nice video demoing its usage https://www.youtube.com/watch?v=LgPiQdkV4g8
