### ISSUE TITLE
datasource add csv

### ISSUE THREAD

**Issue by nogeek-cn** [metabase/metabase#42587]
**Is your feature request related to a problem? Please describe.**

Since CSV does not have a data format, there is currently no range filtering for the number format in CSV, which may be necessary.

 For non-software practitioners, it is still a bit troublesome to build a MySQL or PG data source, if you can add a pre-set data type change transformation or the like to the CSV data source, so that the number column can support range queries, 

this may be a good extension for Metabase users, because the barrier to entry is lower. 

I need this feature as well

**Describe the solution you'd like**

**Describe alternatives you've considered**

https://github.com/Markenson/csv-metabase-driver/issues/38

![image](https://github.com/Markenson/csv-metabase-driver/assets/37619525/7d127787-abf5-4eb1-bd75-a7486f15a74a)

![image](https://github.com/Markenson/csv-metabase-driver/assets/37619525/8f85b023-1760-44e0-8201-981f75aa0134)

---

![image](https://github.com/Markenson/csv-metabase-driver/assets/37619525/70396f6d-7af4-4bbc-b525-b0aadbf9930a)

![image](https://github.com/Markenson/csv-metabase-driver/assets/37619525/8e96b8eb-c45a-4f37-9af8-c61328245c82)

---

what can id do???

 less than or grather than

**How important is this feature to you?**

**Additional context**

https://github.com/Markenson/csv-metabase-driver/issues/38

**Comment by ignacio-mb** [comment]
Hi @nogeek-cn Metabase will try to match the type based on several factors (field values and field name, for example).

Can you share an example of the data in which it's not converted to the type you want? Thanks

**Comment by nogeek-cn** [comment]
Thanks ，this is file

[test.csv](https://github.com/metabase/metabase/files/15354102/test.csv)

alse can see this data

```csv
姓名,总分,语文,数学,外语,物理,化学,道德与法治
mic,428.5,82,70,38.5,32,30,43
tom,557,98,94,71.5,61,43.5,56
james,472,88,71,56,41,32,50
hhh,44,2,45,66,77,88,99
aaaa,566,74,32,74,36,42,22
```

i use this driver

https://github.com/Markenson/csv-metabase-driver

---

OK

i input this file.

in metabase change clumn to Scope .
![image](https://github.com/metabase/metabase/assets/37619525/2d3f7c63-d772-4ea1-bc05-97dcaa0eab0a)


<img width="707" alt="image" src="https://github.com/metabase/metabase/assets/37619525/69240466-f375-4934-874c-611cd7f6da04">

<img width="651" alt="image" src="https://github.com/metabase/metabase/assets/37619525/4f8c16f7-42f0-4d6f-9427-b2ae263a3121">

thanks

ok,

**Comment by paoliniluis** [comment]
I think that the problem is on the custom driver

**Comment by ignacio-mb** [comment]
It is indeed the driver, because using our new CSV upload feature I can use the proper Score (number) filters. Why are you using the driver and not the [our CSV feature](https://www.metabase.com/product/csv-uploads)?

**Comment by paoliniluis** [comment]
@nogeek-cn please contact the builder of the custom driver for this
