### ISSUE TITLE
Trouble viewing multi-series dashboard cards with collection perms

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4259]
As reported in [this Discourse thread](http://discourse.metabase.com/t/collection-permissions-cant-view-questions-to-download-data-or-view-line-graphs/1051/14), if a user has collection view/curate access, but no data access to the questions in the collection, they hit a permissions bug when trying to create a multi-series dashboard card with the questions in said collection. 

The expected behavior is the user should be able to create and view the multi-series card provided it uses cards for which they have collection access, even if they don't have data access. The actual behavior is that when trying to create the multi-series card, they see the `you don't have permission` screen.

Both @tlrobinson and I have been able to reproduce this.

**Comment by Digma** [comment]
I was able to reproduce this in 0.23.1

**Comment by flamber** [comment]
I cannot reproduce in 0.35.3 - this was likely fixed in 0.30, if not long before.
