### ISSUE TITLE
Admin panel - setup - organize questions - refers to labels and not collections, and is a broken link

### ISSUE THREAD

**Issue by ecommandeur** [metabase/metabase#4260]
As far as I am aware labels will be removed in future versions ( http://www.metabase.com/blog/Metabase-0.22 ). Therefore, I think the text under Admin Panel > Setup > Curate your data > Organize Questions should be changed from

> "Have a lot of saved questions in Metabase? Create labels to help manage them and add context."

to sth like

> "Have a lot of saved questions in Metabase? Create collections to help manage them and add context."

The description itself lives in "src/metabase/api/setup.clj" .

**Comment by mazameli** [comment]
Good catch! I've updated the title of this issue because I also noticed that clicking on the box you're referencing goes to `/questions/all` which results in a 404. It should go to `/questions/`
