### ISSUE TITLE
[BE] [Bug] Metrics are not returned by `/api/activity/popular_items`

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#42607]
E2E repro https://github.com/metabase/metabase/blob/44d530b560da058de09ddf576ea8b404e596dff3/e2e/test/scenarios/metrics/metrics-search.cy.spec.js#L70

Steps:
- Run EE
- Log in as user A.
- Create a metric and run its query
- Log out and log in as user B.
- Open homepage
- There are no "popular items" and x-rays are displayed.

When doing the same with a question, the question is returned by the endpoint correctly.

**Comment by metamben** [comment]
@ranquild, how exactly should the metric's query be run? If I just open it it gets executed via the `POST /dataset` endpoint in `ad-hoc` context, so the execution is not returned in `popular_items`. I also managed to execute it in `collection` context, but those executions don't count either. Do we need a new type of context? It's probably not a good idea to allow those context to be considered by `popular_items`.
