### ISSUE TITLE
Model Permession

### ISSUE THREAD

**Issue by MQinna** [metabase/metabase#42620]
### Describe the bug

Users can Edit a Model Query using Native Query editor Without Having PermessionPermission

### To Reproduce

a. Create a Group with preview-only access and add a user to this group only.
b. Disable Native Query Editor for this Group.
c. Create a user with model creation access.
d. Create a model with native query enabled and add it to the analytics collection.
e. Log in as the user from the newly created group.
f. Navigate to the newly created model.
g. Attempt to edit the model query.

### Expected behavior

The user from the group with preview-only access, and with the Native Query Editor restricted, should not be able to edit the model query. The system should enforce the read-only access level set for the group, preventing any modifications to the model's query.

### Logs

the log will be no use case for this.

### Information about your Metabase installation

```JSON
Version 124.0.6367.201 (Official Build) (64-bit)
Windows 11
MySql 
0.49.8
Jar File on Ubuntu
MySql
```

### Severity

Altering Security and access rights

**Comment by paoliniluis** [comment]
Hi, please check the repro steps, although the user can SEE the SQL, it doesn't mean that they can EDIT it.

I wasn´t able to reproduce

**Comment by Tony-metabase** [comment]
The moment you press on `edit` you are not able to write anything in the editor and not even save

<img width="1503" alt="image" src="https://github.com/metabase/metabase/assets/110378427/3f8de118-6d81-4a12-92ab-588470e31644">
