### ISSUE TITLE
Issue with changing chart type for Google Analytics query

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#4265]
•	browser and the version: Chrome 55
•	operating system: Windows 10
•	databases: MysQL
•	Metabase version: 0.22.2
•	Metabase hosting environment: Heroku
•	Metabase internal database: default

I have a problem with a chart for the following GA query:
-> Filter e.g. “organic traffic”, view “revenue” (“e-commerce conversion rate”), group by “week”

The table result cannot be changed to display as bar or line chart, there is “nothing to select” under “Y-axis” in the visualization options. However, for some reason it does work as a bar or line chart for other metrics, such as “sessions” or “transactions” (basically the same query).
Thanks in advance for looking into this!

**Comment by salsakran** [comment]
Can you graph the same query in GA's interface?

**Comment by salsakran** [comment]
what do the entries in the table look like?

**Comment by HelenMertes** [comment]
Yes, I can graph it in GA, it is simply revenues or conversion rate filtered by a channel.

The entries in the query result table look for example like this:
![image](https://cloud.githubusercontent.com/assets/24734846/23356332/ba379cc6-fcd9-11e6-8816-bbf464875cbb.png)

**Comment by finer9** [comment]
Also having this exact problem

**Comment by flamber** [comment]
I cannot reproduce on `master` commit `af0a18e` (the upcoming 0.36.0) - unsure when it was fixed.
Related #5291
