### ISSUE TITLE
Enhancement of chart visualization options

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#4267]
•	Browser and the version: Chrome 55
•	Operating system: Windows 10
•	Databases: MysQL
•	Metabase version: 0.22.2
•	Metabase hosting environment: Heroku
•	Metabase internal database: default

A couple of points that would help chart visualization and add a lot of value from our perspective, making charts/dashboards more user-friendly and insightful:

- Option to select and display data labels - so that it is not necessary to hover over series to see the value of a data point (also useful if chart is exported)
- Sum data label for stacked bar charts - #4109
- Additional colours for charts, e.g. bar chart with 6th series currently starts with the first colour again - #3185 – this had been scheduled for an earlier release already?
- Option to combine different chart types, i.e. bar und line chart, which is for example great to show revenues, and profit as bar and margin in % as line on secondary axis - supposedly covered by #3433
- Option to show percentage change such as growth rates, e.g. monthly/weekly change in % in bar chart - #4257
- Export of (single) charts (e.g. multi-series charts from dashboards) – partly #3847 / #3770

It would be great if these can be covered in the upcoming release!

**Comment by DannyDouglass** [comment]
exporting a card's data would be very helpful!

**Comment by AnthonyRobles** [comment]
The first point "Option to select and display data labels - so that it is not necessary to hover over series to see the value of a data point (also useful if chart is exported)" would be especially useful!

**Comment by lbellan** [comment]
We want dashboards to be looked at by operational teams on Ipads or screens where they cannot hover to see the details of the data

**Comment by bcherry** [comment]
we've just installed metabase and started building dashboards with it and a lot of these things have come up within the first week.

- sum totals along the top of bar charts (stacked and unstacked)
- bar chart and area/line chart in same graphic (to show % change month/month)
- automatic computation of % change on time series data (it's not hard to do with `lag` but it is a bit of work to copy/paste for all of our questions)

**Comment by nidanaz168** [comment]
Hi Any update or work around is available on same??

**Comment by mazameli** [comment]
Every request in this issue is either implemented or is covered in a more specific single feature request, so I'm going to close this issue.

> Option to select and display data labels - so that it is not necessary to hover over series to see the value of a data point (also useful if chart is exported)

Covered in https://github.com/metabase/metabase/issues/4788

> Sum data label for stacked bar charts - #4109

https://github.com/metabase/metabase/issues/4109

> Additional colours for charts, e.g. bar chart with 6th series currently starts with the first colour again - #3185 – this had been scheduled for an earlier release already?

Implemented.

> Option to combine different chart types, i.e. bar und line chart, which is for example great to show revenues, and profit as bar and margin in % as line on secondary axis - supposedly covered by #3433

Implemented.

> Option to show percentage change such as growth rates, e.g. monthly/weekly change in % in bar chart 

#4257

> Export of (single) charts (e.g. multi-series charts from dashboards)

#3847 / #3770
