### ISSUE TITLE
Empty collections handling

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#42687]
Currently root collections and personal collections are always displayed in the picker, see:

https://github.com/metabase/metabase/blob/1c5e5998bbe7ea6ebd6d59bb23fbfbe2d81a9068/frontend/src/metabase/common/components/QuestionPicker/utils.ts#L94-L105

https://github.com/metabase/metabase/blob/4cbae2ee70c64738695db8705b172efbb4524a0f/frontend/src/metabase/common/components/CollectionPicker/components/PersonalCollectionItemList.tsx#L51

https://github.com/metabase/metabase/blob/1163109d9e38ec322129f67daf2c336788f4d616/frontend/src/metabase/common/components/DataPicker/utils.ts#L188-L190

This can sometimes lead users to dead ends.

Ideally we'd

> update the API to correctly populate personal collections. I think the right way to do this is probably not via search, but should be a special case like `collection/personal/items` to list all other personal collections with the same shape as `collection/:id/items`

See [Slack thread](https://metaboat.slack.com/archives/C010L1Z4F9S/p1715776154458989?thread_ts=1715177121.332039&cid=C010L1Z4F9S).

----

This should be covered with tests.

----

We [had to remove](https://github.com/metabase/metabase/pull/42565) this assertion in the Data Picker epic because of it: https://github.com/metabase/metabase/blob/14e66a08dbb51104f1ece7e84920ecdb1002723e/e2e/test/scenarios/question/new.cy.spec.js#L198-L200

We should bring it back.

**Comment by iethree** [comment]
see [discussion](https://metaboat.slack.com/archives/C010L1Z4F9S/p1715776154458989?thread_ts=1715177121.332039&cid=C010L1Z4F9S)

**Comment by kamilmielnik** [comment]
Duplicate of #40924
