### ISSUE TITLE
Metabase doesn't automatically center-align labels in horizontal axis when removing columns

### ISSUE THREAD

**Issue by taqattack** [metabase/metabase#42695]
### Describe the bug

When a combo visualization is used to display information with columns removed, the texts appear to be off-center. See following:

![Uploading image.png…](https://p23.zdusercontent.com/attachment/9175259/uQuHYm3D0H4xa9m6exjYuDeLX?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..-0hfLX0XIHMEHloizFgjMw.YwXZnk8QZLJkmXAVUbQ-fhxa3h-Wg7RUJc-4YUiQOrBrSSTg9WsbuBl16Ddt1fHVcp1q47jAkEMfPWIXQ4cVg6Fdgr19w-4EpBwLivs-beLBLom3B3Mg_2K1n6XI69OsjRS5z0n1B11juV3s0Y2aDhma0yGxjSFdHfHAQNHQalr0lZwH9BDDuWn1ssvp6zj_81er8jcN0admQoNKdaU0BOOEV4T1ELwXhflxijNLuPlggItL8h-BM7lqO1U-_OMK3wTmkJ5pQ_paJVAHbSIUsyj38MGnaoHUbmK9mXJG3FKYVqpDxDp0y3Bi7Rk6zuvA.rajQgv3UD1naEarCfwOSmQ)

### To Reproduce

1. Create a new question using SQL editor. For example:

`with orders_table as (
SELECT
  extract(YEAR from created_at) AS year_,
  extract(MONTH from created_at) AS month_,
  COUNT(id),
  SUM(total)
FROM orders
WHERE extract(YEAR from created_at) = 2024
GROUP BY
  extract(YEAR from created_at),
  extract(MONTH from created_at)
ORDER BY
  extract(MONTH from created_at)
)
SELECT
    orders_table.*,
    CASE month_
        when 1 then 'Jan'
        when 2 then 'Feb'
        when 3 then 'Mar'
        when 4 then 'Apr'
        when 5 then 'May'
        when 6 then 'Jun'
        when 7 then 'Jul'
        when 8 then 'Aug'
        when 9 then 'Sep'
        when 10 then 'Oct'
        when 11 then 'Nov'
        when 12 then 'Dec'
    else null
  END case_status_date_cdt_month_txt,
FROM orders_table
WHERE month_ <= 5`

2. Change visualization to Combo

3. Remove columns YEAR_ and MONTH_

### Expected behavior

The texts should be centered across the current bars being displayed.

### Information about your Metabase installation

```JSON
Metabase Cloud v1.49.8
```

### Severity

minor

**Comment by alxnddr** [comment]
Hi @taqattack, for the upcoming 50 release we've revamped cartesian charts and the query you've provided will look as expected:

<img width="969" alt="Screenshot 2024-05-15 at 3 14 59 PM" src="https://github.com/metabase/metabase/assets/14301985/8e82c4c9-2497-43a0-8754-f15c0923f543">

**Comment by alxnddr** [comment]
Hi @taqattack, we've revamped our cartesian charts in the upcoming Metabase 50 release and this particular case will work as expected:

<img width="1724" alt="Screenshot 2024-05-15 at 3 16 58 PM" src="https://github.com/metabase/metabase/assets/14301985/7f7fc663-3a41-42ce-aef2-28a232bf9453">
