### ISSUE TITLE
Possible to get into unclear SQL permissions state

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4273]
If a group starts out with unrestricted data access perms and full SQL read/write perms for a given database, if you then set that group's data access perms to Limited, but then grant them access to 0 tables within that DB (which is a weird thing to do), the top level permissions table gets into a weird state and shows the SQL perms cell like this:

![screen shot 2017-01-31 at 11 28 49 am](https://cloud.githubusercontent.com/assets/2223916/22481095/c4992efa-e7a8-11e6-8fec-b39427b6f378.png)

It's ambiguous what that group's sql permissions are now, and there's no tooltip if you hover on that cell. My instinct is to just set that group's data access perms to No Access if you revoke access to all tables within the DB, but I suppose there's a weird edge case where you'd want to revoke access to all the tables so the group can't create a new ad hoc query, but you still want them to be able to view SQL questions from that DB.

In any case, this scenario should be solved or at least simplified when we remove the "view sql" option and just let Collections take care of sorting that out.

**Comment by salsakran** [comment]
closed via #4847
