### ISSUE TITLE
Custom columns don't work after aggregation unless the user has native query permissions

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#42765]
### Describe the bug

In questions based on native models, post aggregation custom columns no longer work, unless the user is given **native query permissions**.

### To Reproduce

1. Create a native model (`select * from products`), save it

Log in with a user that does not have native query permissions:
2. Create a GUI question, based on the model created in step 1
3. Add an aggregation(summarize: Count of Rows, by Category)
4. Add a custom column (`[Count] + 1`)
5.(!) Visualize, and see the error
<img width="524" alt="image" src="https://github.com/metabase/metabase/assets/11080638/b27adcb4-8acb-46a7-a993-113b5a857448">

Assigning native query permissions to the user makes the question runnabl.

### Expected behavior

The question should work without native query permissions.

### Logs

n/a

### Information about your Metabase installation

```JSON
1.49.10
```

### Severity

P1 - affects a common function

### Additional context

Reproduced it in `49.10` but I suspect the issue might have existed in earlier versions (`49.8`).

**Comment by bshepherdson** [comment]
No repro on 50.x.

- I defined a SQL model with my admin user: `SELECT * FROM products;` and saved it.
- I created a new user with QB but no native query perms (see screenshot; I can't make a new native question)
- That user can write a `[Count] + 1` expression and it works fine.

I'm closing this one; reopen if there's still an issue here.

![2024-06-21-100206_1604x1096_scrot](https://github.com/metabase/metabase/assets/157812/1a7ec126-9b42-467b-af13-6385ccf13c44)
![2024-06-21-100229_1292x537_scrot](https://github.com/metabase/metabase/assets/157812/b4a2008f-6876-46b0-8a95-8a63031562c7)
