### ISSUE TITLE
Don't use relative link for geojson maps

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#42767]
From @oisincoveney 

Hey backend team! I have a quick question for y'all. Right now we're trying to embed a static dashboard using the Embedding SDK, but one snag that we found was that the geojson maps that we use for the visualizations aren't loading, since the links to the map are using a relative URL. That means that if a client has a map visualization on, for example, localhost:420420/admin/whatever, the SDK tried to fetch the map from localhost:420420/admin/whatever/app/assets/geojson/us-states.json .
I see that it's initialized to this relative url within the geojson.clj  file as a setting. Do you think we could do something to explicitly specify the backend URL so it looks like [MB_BACKEND_URL]/app/assets/geojson/us-states.json? Or is there something else that we should do?

**Comment by NevRA** [comment]
@dpsutton any updates on this?
