### ISSUE TITLE
Border showing on night theme with bordered=false

### ISSUE THREAD

**Issue by lokalise-mark** [metabase/metabase#42763]
### Describe the bug

Hey,

It looks as though the bordered=false property is not being respected when an embedded dashboard has theme=night set. 

I noticed that your team recently released a fix aimed at addressing this issue, but it doesn't seem to have quite worked: https://github.com/metabase/metabase/pull/41514.

From what I can see, it looks as though the issue is within `EmbedFrame.module.css`, which contains the following CSS:

```
.ThemeNight.EmbedFrame .DashCard .Card {
  background-color: var(--color-bg-black);
  border: 1px solid var(--color-bg-dark);
}
```

I've confirmed in-browser that this is the style being applied to my dashboard.

### To Reproduce

1. Embed a dashboard with theme=night and bordered=false applied

### Expected behavior

No border is shown when theme=night and bordered=false are set.

### Information about your Metabase installation

```JSON
Latest Chrome (v124)
Macbook Pro (Sonoma 14.2.1)
```

### Severity

Medium - it's complicating convincing our designers to use Metabase dashboards

**Comment by npretto** [comment]
Hey @lokalise-mark, the fix in the PR you linked has not been released yet, it will come out with v50, the RC should come out in a few days
