### ISSUE TITLE
"-modified" suffix briefly shown in a model's name input during creation

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#42773]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/1bba1142-2652-4ed0-adf8-9834a56457ef

### To Reproduce

1. Start a new notebook model based on Orders table
2. Click "Save"
3. Observe name input in the modal from now
4. Click "Save" in the modal

Observe that the name input will briefly show `- modified` suffix

### Expected behavior

`- modified` suffix is not shown

### Information about your Metabase installation

master, 44cb385c40

### Severity

P3

**Comment by paoliniluis** [comment]
happens on questions as well

**Comment by nemanjaglumac** [comment]
Still present in 50.13.

**Comment by nemanjaglumac** [comment]
Fixed on `master` by https://github.com/metabase/metabase/pull/45457

**Comment by nemanjaglumac** [comment]
Fixed in `master` by https://github.com/metabase/metabase/pull/38457, which wasn't backported.

The diff is huge, but the line to look for is:
`const [originalQuestion] = useState(latestOriginalQuestion); // originalQuestion from props changes during saving`

**Comment by nemanjaglumac** [comment]
Fixed by https://github.com/metabase/metabase/pull/47086
