### ISSUE TITLE
Replace Missing Values with Nothing or Zero removes existing values from a chart

### ISSUE THREAD

**Issue by rchowe** [metabase/metabase#4277]
I have a chart where I select count of rows by date; Metabase says that this is the SQL query:

```SQL
SELECT count(*) AS "count", CAST(CAST("reporting"."LatestReports"."CreatedDate" AS date) AS datetime) AS "CreatedDate"
FROM "reporting"."LatestReports"
GROUP BY CAST(CAST("reporting"."LatestReports"."CreatedDate" AS date) AS datetime)
ORDER BY CAST(CAST("reporting"."LatestReports"."CreatedDate" AS date) AS datetime) ASC
```

When I make a line chart and change the selected option for *Replace missing values with* in the chart display options, the data on the chart essentially disappears. Here the chart is in the default (working) state:

![Working Screen Shot](https://cloud.githubusercontent.com/assets/179738/22495086/32d2326a-e80b-11e6-8d14-0e80b63b564c.png)

Here's the chart when I select *Zero* for *Replace missing values with*:

![screen shot 2017-01-31 at 11 03 07 pm](https://cloud.githubusercontent.com/assets/179738/22495103/4f1c7d54-e80b-11e6-87e3-d987b641d9ca.png)

Here's the chart when I select *Nothing* for *Replace missing values with*:

![screen shot 2017-01-31 at 11 03 09 pm](https://cloud.githubusercontent.com/assets/179738/22495113/5de1fad0-e80b-11e6-9097-fc9ed7b3efc0.png)

I'd expect that if missing values are being replaced with zero or nothing, the values that exist would stay around.

----

### Environment Information

- Your browser and the version: **Safari 10.0.3**; it also seems to occur on Firefox 50.1.0 and Chrome 55.0.2883.95
- Your operating system: **macOS Sierra 10.12.3**
- Your databases: **Microsoft SQL Server Express 12.00.4422.0.v1** (Amazon RDS)
- Metabase version: **0.22.2**
- Metabase hosting environment: **Elastic Beanstalk**
- Metabase internal database: **Postgres 9.5.4** (Amazon RDS)

**Comment by rchowe** [comment]
I'm not sure what it is, but I downloaded the latest version from GitHub (80b539a) to see if I could fix the issue, and it seems that this issue has disappeared (exact same database, running on my Mac instead of EB). Good job I guess; I'll have to see if it's still there on my production server when 0.23.0 comes out.

Could someone please close this and mark as invalid?

**Comment by tlrobinson** [comment]
I've also seen this happen before but can't reproduce it on `master`, so it may indeed be fixed.

I'm not sure if I should be grateful or disturbed by bugs that accidentally get fixed...
