### ISSUE TITLE
Remove Google Analytics driver and related special case stuff

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#42792]
We made the decision to deprecate it about a year ago because of https://github.com/metabase/metabase/issues/12905#issuecomment-1611804549, now because it's blocking Metrics v2 we are finally going to drop it entirely. ([We announced this in 47.](https://www.metabase.com/releases/Metabase-47)) This needs to be done before we ship 50. See https://metaboat.slack.com/archives/C04DN5VRQM6/p1715888743074829 for more info.

We need to delete all the code related to GA in the repo including the CI job and any mentions of `:googleanalytics` in the codebase. We have a lot of special edge case stuff in the codebase for GA's hardcoded `:metric`s and `:segment`s (which use string IDs instead of integers), we should remove that stuff from the MBQL schemas and all of the special case code. Examples of stuff to remove:

- `modules/drivers/googleanalytics`
- https://github.com/metabase/metabase/blob/d142da9984b0485c56c224b79116031973226399/src/metabase/legacy_mbql/schema.cljc#L987-L996
- https://github.com/metabase/metabase/blob/59e7b3d1cb2f22a9574cad9aef1a2bea3a72fc80/deps.edn#L388
- https://github.com/metabase/metabase/blob/cd007ba6ac34dc3ab2769c5333718eef41c15d69/src/metabase/xrays/automagic_dashboards/names.clj#L31
- GitHub Actions related to Google Analytics

**Please be thorough and remove all the dead GA-related code!!! Please 🙇‍♂️**

**Comment by camsaul** [comment]
We should also double-check that things like the Database REST API endpoints don't blow up if we have a `Database` with a driver that no longer exists. The `after-select` method for `:model/Database` only calls `metabase.driver.util/features` if the driver is registered, so that should be good at least, but we should check other things as well just to be safe.

**Comment by crisptrutski** [comment]
@camsaul do you have an ETA for landing the remaining work here?
