### ISSUE TITLE
Internet Explorer 11: error "Out of stack space" on all dashboards

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4279]
In IE 11 all my dashboards return:
![image](https://cloud.githubusercontent.com/assets/1708680/22499061/9aa861e0-e86d-11e6-93e3-43b1f3882515.png)

In console:
![image](https://cloud.githubusercontent.com/assets/1708680/22499154/18be29ac-e86e-11e6-8aeb-4f88ef174a06.png)

IE version:
![image](https://cloud.githubusercontent.com/assets/1708680/22499162/25602c32-e86e-11e6-9429-18bbf46cc738.png)

**Comment by tlrobinson** [comment]
@anki-code Is this a recent regression or did you just try using IE?

**Comment by anki-code** [comment]
@tlrobinson I've tried IE first time. Metabase 0.22.1.

**Comment by moumny** [comment]
Ive seen this on earlier version. 
For this reason we block access to Metabase from IE and recommend chrome.

**Comment by camsaul** [comment]
@anki-code any reason you're using IE and not Edge?

**Comment by anki-code** [comment]
@camsaul I'm not using IE. One of my users was trying to open Metabase in IE and he told me about this bug. I've checked the Edge Browser and it works fine. Thank you!

**Comment by moumny** [comment]
Entreprise => windows 7 => IE11 and no admin rights :)

**Comment by louis-eyond** [comment]
Well, that is super-reproducible...  I usually use Chrome, but got a report of our Metabase installation not working with the "Out of stack space" error message.  I opened Internet Explorer 11 on Windows 10 and all the Dashboards show the error.

Let me know if I can provide additional details to help.

**Comment by salsakran** [comment]
hey @anki-code, can you email me? I have a question for you =)

**Comment by anki-code** [comment]
@salsakran I don't know your email. I've sent message to your facebook :)

**Comment by tlrobinson** [comment]
@anki-code @moumny @louis-eyond Could you verify PR #4458 (branch `issue-4458`) resolves this, if you have a few minutes?

**Comment by anki-code** [comment]
@tlrobinson it works on `master`!

JFYI: While I am testing it I see some UI problems in IE:
1. Dialogs are shifted:
![image](https://cloud.githubusercontent.com/assets/1708680/23451017/109ce2e2-fe6f-11e6-9aee-6e72152d9d42.png)

2. No save button when I try to add a card on dashboard:
![image](https://cloud.githubusercontent.com/assets/1708680/23451072/51347360-fe6f-11e6-865c-afead38fc9e1.png)

**Comment by salsakran** [comment]
@anki-code mind opening separate issues for those? Good catches!

**Comment by anki-code** [comment]
@salsakran yep: #4471 #4470

**Comment by salsakran** [comment]
much appreciated!
