### ISSUE TITLE
Include plan alias in token information

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#42828]
We want to include plan alias in the token information so that we can use it in the upsell badging.

See 
https://github.com/metabase/harbormaster/pull/4993/commits/462da5a91c33f2a7662ed15de1ac83b99da2c859 for the shape. Just a string on the key `:plan-alias`.

This is already the case. The `token-status` setting is visible to admins. We only show the upsell information to admins, so that information is already on the FE.
```
❯ http get "localhost:3000/api/session/properties" Cookie:$SESSION -pb | jq '."token-status"."plan-alias"'
"internal"
```

If you don't see it yet, add 

```diff
modified   deps.edn
@@ -262,6 +262,7 @@
                  "-Dfile.encoding=UTF-8"
                  "-Duser.language=en"
                  "-Duser.country=US"
+                 "-Dmetastore.dev.server.url=https://token-check.staging.metabase.com/"
                  ;; Allow clojure goes fast tooling to work
                  "-Djdk.attach.allowAttachSelf"
                  ;; This will suppress the warning about dynamically loaded agents (like clj-memory-meter)
```

To your deps.edn file under the `:dev` alias. 

And perhaps we should also document it in the malli schema

```diff
modified   src/metabase/public_settings/premium_features.clj
@@ -102,6 +102,7 @@
   [:map
    [:valid                          :boolean]
    [:status                         [:string {:min 1}]]
+   [:plan-alias    {:optional true} :string]
    [:error-details {:optional true} [:maybe [:string {:min 1}]]]
    [:features      {:optional true} [:sequential [:string {:min 1}]]]
    [:trial         {:optional true} :boolean]
@@ -118,6 +119,15 @@

```

**Comment by escherize** [comment]
Besides the PR to metabase, we should update [the other repo too](https://github.com/metabase/token_airgap_gen/issues/5).
