### ISSUE TITLE
No edit icon after saving a new question

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4283]
Metabase 0.21.1

![image](https://cloud.githubusercontent.com/assets/1708680/22509520/6cb6bc00-e89f-11e6-95cc-46dbae7a59b7.png)

**Comment by tlrobinson** [comment]
Probably a similar issue to #4142. Without looking, I'm guessing the `POST /api/card` endpoint isn't returning all the relevant info.

**Comment by mazameli** [comment]
This is still present in 0.23.1

**Comment by attekei** [comment]
Fixed by #5520
