### ISSUE TITLE
Milestone Reminder GH Action doesn't always work

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#42835]
### Describe the bug

We have a very useful milestone reminder GH action, but it doesn't always work as expected.
There are two scenarios we need to fix:
1. The action sometimes literally fails because of an exception ([example](https://github.com/metabase/metabase/actions/runs/9129775294))
2. The action posting a comment on PRs that don't even have the closing keyword ([example](https://github.com/metabase/metabase/pull/42624#issuecomment-2110361435))

### To Reproduce

1. Close a PR that contains this body: `Closes #12345 and #23456`

or 

2. Close a PR that doesn't have a closing keyword at all.

### Expected behavior

1. Action should never fail
2. Action should not post comments on PRs that didn't have the closing keyword and a linked issue to begin with

### Information about your Metabase installation

```JSON
.
```

### Severity

p3

### Additional context

Internal.

**Comment by darksciencebase** [comment]
I'm probably missing something, but if a PR doesn't have a closing keyword, that means it's not connected to an issue, which in turn means the PR itself should have a milestone, so I'm lost about the #2 in the description.

**Comment by nemanjaglumac** [comment]
> which in turn means the PR itself should have a milestone

Not always. There are a ton of tech debt PRs that don't really need a milestone. I'm not aware that we're enforcing a milestone in 100% of cases?

**Comment by darksciencebase** [comment]
> Not always. There are a ton of tech debt PRs that don't really need a milestone. I'm not aware that we're enforcing a milestone in 100% of cases?

not 100% but (1) better too many PRs than too few, (2) many tech debt PRs should have a milestons, (3) the reminder doesn't know a difference. let's continue this discussion on the notion doc explaining our usage of milestones
