### ISSUE TITLE
Entity Picker difficult to use on mobile

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#42879]
![image](https://github.com/metabase/metabase/assets/6830683/1df58db6-e7f4-440f-a02f-eddbfab45d39)

### Description

On mobile:
- when search is available, the search input will take most of the horizontal space resulting in wrapped modal title and "x" being off-screen (it should probably go into a separate row - to confirm with product)
- when tabs don't horizontally fit in the viewport, they wrap into multiple lines instead of becoming scrollable (to confirm with product)
- the entity picker modal is horizontally scrollable (only the `nested-item-picker` should be horizontally scrollable)

### How to reproduce

On mobile:
- start a new question
- try to move existing question to a different collection

### Information about your Metabase installation

master, 5d795be

### Severity

P3

**Comment by iethree** [comment]
note: we have some [really great mobile designs](https://www.notion.so/metabase/Make-picking-an-item-a-nice-experience-with-an-EntityPicker-component-05e457c1b84f413f84ab9756e0c68b57?pvs=4#3d63f32dc2994226ac8353a507371e70), they just haven't been implemented yet

**Comment by kamilmielnik** [comment]
I'll close this for now then, thanks!
