### ISSUE TITLE
Find a way to start running Crate tests again

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#4290]
So we can keep supporting Crate.

Discussion from #4285:

Metabase supports Java 7 and we ran into a bug because we were using some Java 8-specific features, so we decided to switch our CI containers to use Java 7.

As I mentioned in #4278 I found out the hard way that Crate requires Java 8 (it's not super clear in the documentation). So for the time being I've disabled running tests against Crate.

Could you please look into a way to get Crate tests working again? I would imagine you can install Java 8 and then set some sort of Crate configuration to specify which JRE to use, but I wasn't able to determine how to go about doing that.

**Comment by camsaul** [comment]
@mikethebeer I opened this issue to figure out how to start running Crate tests again

**Comment by mikethebeer** [comment]
@camsaul see comment here https://github.com/metabase/metabase/pull/4285

**Comment by camsaul** [comment]
@mikethebeer is there some way you can run Java 8 and Crate in a docker container or something like that? Let me know what you can figure out for Crate testing so we can keep supporting it.

**Comment by mikethebeer** [comment]
@camsaul yes, sure.
Just be sure to expose the default Postgresql Port `5432`

```
docker run -d -p 5432:5432 crate/crate crate
```

**Comment by mikethebeer** [comment]
@camsaul @salsakran What could we do to help you in getting this a step forward? Since there are no CI tests for CrateDB running on PRs anymore the Metabase feature support for Crate does not fit anymore. I just ran the integration tests and got this as  result.

```sh
Ran 2572 tests containing 2572 assertions in 159718 msecs
2 failures, 170 errors.
```

**Comment by camsaul** [comment]
@mikethebeer we'd need to modify [our CI script](https://github.com/metabase/metabase/blob/master/bin/ci) to use the docker image. We're doing something similar for Vertica so you can use that as an example

**Comment by camsaul** [comment]
Closing as no longer relevant. Starting with 0.32.0 Crate driver is community-supported and lives at https://github.com/metabase/crate-driver
