### ISSUE TITLE
Creating a new collection in the root collection from the entity picker errors

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#42934]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6377293/92d60bcb-c21d-40e3-95e3-8b26fdb5222d)

```
2024-05-20 17:40:50,369 DEBUG middleware.log :: POST /api/collection 400 16.1 ms (0 DB calls) {:metabase-user-id 1}
{:errors {:parent_id "nullable value must be an integer greater than zero."},
 :specific-errors {:parent_id ["value must be an integer greater than zero., received: \"root\""]}}
```

Values sent over the wire:

```
{"name":"restore point","parent_id":"root"}
```

Values sent when creating a new collection from the regular "New" button in the root collection:

```
{parent_id: null, authority_level: null, color: "#509EE3", description: null, name: "collection"}
```

(note null parent_id, also the color option there is completely removed i think)

### To Reproduce

use the new collection entity picker. Easiest way is to move an item, create a new collection, navigate away from recents to the collection picker, select Our Analytics root collection and then click "create collection"

<img width="1005" alt="image" src="https://github.com/metabase/metabase/assets/6377293/fca453d4-3492-4d26-9f7f-89fe2b94d93f">

### Expected behavior

should not error

### Information about your Metabase installation

```JSON
latest
```

### Severity

p1-p2

**Comment by iethree** [comment]
we should also verify that creating a dashboard in the root collection works correctly from the entity picker
