### ISSUE TITLE
Create column actions always visible

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#42949]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/a82178b4-8bba-41d6-9c7a-6c6caae6a6e6

### Case 1

1. Create a native question for Sample DB:
    ```sql
    SELECT DATE '2024-05-21' AS created_at, null as v
    UNION ALL SELECT DATE '2024-05-20' , 1
    UNION ALL SELECT DATE '2024-05-19' , 2
    ORDER BY created_at
    ```
3. Save it
4. Explore results

Plus button is visible but it should not.
Extract and combine shortcuts are shown after clicking it.

-----

### Case 2

1. Create a native question for Sample DB: `select 1`
2. Save it
3. Explore results

Plus button is visible but it should not.
Nothing happens when clicking it.

### Information about your Metabase installation

master, c09ec3ddeb

### Severity

P3

**Comment by nemanjaglumac** [comment]
This might be a desirable behavior now when we added "combine columns".

cc @romeovs @mngr

**Comment by kamilmielnik** [comment]
> This might be a desirable behavior now when we added "combine columns".

Notice that in the video user cannot submit "Extract part of column" or "Combine columns" forms (because there are no columns to select from), so it does not make sense to show these options. And if there are no options to show, the plus menu also should not be shown.

**Comment by mngr** [comment]
@kamilmielnik Why can't we extract from the created_at column here?
