### ISSUE TITLE
Hide setup tip "Hide irrelevant tables"

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4295]
I see this tip every day but I haven't irrelevant tables :)
This tip irritates me more and more :)
Please make it closeable or show only first days after Metabase setup.

![image](https://cloud.githubusercontent.com/assets/1708680/22540671/8676d13c-e932-11e6-8c5f-63550f0f4d78.png)

**Comment by mazameli** [comment]
Out of curiosity, are all of the tables in the database(s) that you've connected to Metabase tables that you intend for people to be able to query against? We've just typically seen the pattern that most schemas have some kinds of technical tables that tend not to be pertinent for analysis — hence this tip.

However, taking your word for it, it could make sense to add a manual checkbox to these tips in case our auto-detection gets it wrong, like in your case.

**Comment by anki-code** [comment]
@mazameli I have a special **[data mart]**(https://en.wikipedia.org/wiki/Data_mart) for Metabase. The data mart has only views with excellent structure for visualization and digging. It's very agile structure.

So in my case this tip box isn't working ;)

![image](https://cloud.githubusercontent.com/assets/1708680/22585146/5c216322-ea07-11e6-874e-5e7408ecf778.png)
