### ISSUE TITLE
Empty collections shown in Data Picker

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#42957]
### Describe the bug

[Slack thread](https://metaboat.slack.com/archives/C02H619CJ8K/p1716303539629889?thread_ts=1716303478.270139&cid=C02H619CJ8K)

### To Reproduce

1. Create a model 
2. Create a collection and add a question to it (but not the model from step 1)
3. Start a new question
4. Open Models tab

Collection created in step 2 should not be visible

### Information about your Metabase installation

master, c09ec3ddeb

### Severity

P2

**Comment by iethree** [comment]
@kamilmielnik , I see you added the v50 milestone. I thought metrics weren't in 50?

**Comment by kamilmielnik** [comment]
@iethree The issue is not metrics-specific, repro steps just happened to be. I changed it to models so it's clear.
