### ISSUE TITLE
disable invalid move targets in the recents tab (needs recents API update: effective_location)

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#42980]
the collection/id/items endpoint populates each item's full `effective_path` and the frontend uses this information to provide a nice collection-moving experience by disabling any item that is a child of the moving collection (you can't move something into itself).  The recents api lacks this information, so we have to rely on a backend API error, instead of filtering/disabling invalid choices at the outset.

![Screen Shot 2024-05-21 at 3 13 36 PM](https://github.com/metabase/metabase/assets/30528226/4250a610-e0dd-4534-aba9-2be01774c542)

It's not awful, but we can do better.

If we can get effective paths populated on the recents endpoint, we can do the same nice UI magic that we do with the collection items endpoint

**Comment by escherize** [comment]
As of https://github.com/metabase/metabase/pull/42813 we only send back `effective_parent`s in the recents api. **Would it be helpful to send you the effective_path on recent items with model='collection' as well?** (We need to calculate that to get the effective_parent, to show a collection's parent collection correctly, so it would be very easy to do).

**Comment by escherize** [comment]
Closed by #43018
