### ISSUE TITLE
Enumerate all expected behaviour wrt Embedding + Permissions and write tests for them

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4300]
As a hard blocker to releasing #4271, we should enumerate all expected behaviour wrt signing, collection permissions, data access permissions, etc and make sure we have tests around them.

**Comment by camsaul** [comment]
What does collection permissions have to do with embedding?

**Comment by salsakran** [comment]
At the moment, nothing specifically.

This is more a reminder to make sure we have our security house in order before shipping stuff that might allow remote non-logged in access to people's data.

**Comment by salsakran** [comment]
@camsaul how's this
*Things to test*

Embedding
1. If embedding is not enabled, any attempt to use the embedding endpoints is rejected
2. If embedding is enabled but a card/dashboard is not published, an appropriate error message should be returned
3. if embedding is enabled and a card/dashboard is enabled
    1. if the jwt token is invalid, return a 400
    2. if the jwt token is valid
        1. if a locked parameter is missing, return a 400
        2. if a locked parameter is of the wrong type (eg, a dashboard with an id of “Ted”), return a 400
        3. if a locked parameter can’t be injected, return a 400
        4. if a disabled parameter is present, return a 400
        5. if an editable parameter is signed, that’s ok 

Public links
1. if public links is disabled, any call to public links or dashboards should return an error (3XX)
2. if public links is enabled, but the uuid is wrong, return a 400
3. if a public link is enabled for a dashboard/card, and the user is un-authenticated, /dashboard/X should return an error
4. if a public link is enabled and then disabled, that url should 404

**Comment by camsaul** [comment]
I'm 99% sure all of the cases for public links are already covered as part of the `public-links` PR but I will double-check

**Comment by salsakran** [comment]
yup, just there for completeness.

**Comment by camsaul** [comment]
This is all done inside the #4271 PR so going to go ahead and close this out
