### ISSUE TITLE
There's no "new" button on mobile

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#43024]
### Describe the bug

When using Metabase on mobile, there's no "new" button

### To Reproduce

Just open Metabase on your mobile

### Expected behavior

Probably this is the expected behavior?

### Logs

NA

### Information about your Metabase installation

```JSON
- v50
- brave mobile
```

### Severity

P3

### Additional context

![image](https://github.com/metabase/metabase/assets/1711649/6b6d28a2-6ba7-4eab-b180-b65344792c6b)

**Comment by darksciencebase** [comment]
@kdoh @mazameli wasn't this by design? i vaguely recall reading something like that, might've been a dream though

**Comment by kdoh** [comment]
Yeah this is intentional as of now.
