### ISSUE TITLE
Enhance scatterplot / bubble chart hover state

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4302]
As mentioned in [this discussion board comment](http://discourse.metabase.com/t/bubble-chart-tagging/1128), scatter/bubble charts could be improved in two simple ways:

1. Because each bubble/dot on the chart represents a single row, it would be really handy to give the entity name and/or ID for that row in the tooltip when hovering on a bubble. I.e., if I see an outlier bubble, I should be able to hover on it and immediately learn which item it is. This feels like an especially acute need due to the lack of drill-through, but would still be super helpful even if and when drill-through is added. Right now, there's no way to know which row/item the bubble represents unless you switch back to table view, which defeats the purpose.
2. Not as sure about this one, but either on hover or on click, it could be nice to have the hovered/clicked bubble become opaque, and the rest of the bubbles to fade out a bit in order to help focus on the highlighted item. I'm somewhat less sure about this one because it could potentially be a bit twitchy/flickery if it's a hover behavior. 

The discussion board comment also mentions the ability to change the base bubble size, but that feels like a separate issue to me, and perhaps less important.

**Comment by mazameli** [comment]
Here's a good (fabricated) example. If I create a scatterplot of these unaggregated orders, broken out by subtotal and tax, when I hover of this bubble, I don't know which order(s) I'm looking at:

<img width="1059" alt="screen shot 2017-02-06 at 11 23 09 am" src="https://cloud.githubusercontent.com/assets/2223916/22662672/aa912570-ec5e-11e6-8318-7aa1e0bdb4f8.png">

**Comment by anki-code** [comment]
I think base technology for this issue and also for #4263 is a technology for concatenating points which looks like one point on chart and show in this case a tooltip with full data.

In scatter plot case:
![image](https://cloud.githubusercontent.com/assets/1708680/22664586/62e3ddc6-ecc2-11e6-9433-9335b5ec09f5.png)
