### ISSUE TITLE
Update the design for custom expression shortcuts

### ISSUE THREAD

**Issue by mngr** [metabase/metabase#43064]
We've implemented [shortcuts](https://github.com/metabase/metabase/issues/41177) and popular custom expressions [suggestions](https://github.com/metabase/metabase/issues/41187) for which the designers want to make small adjustments:
- Change text case for headers from upper case to sentence case
- Increase spacing before headers

**Comment by crisptrutski** [comment]
@mngr is this something we want to include in RC2 this week?

**Comment by mngr** [comment]
We can postpone this to RC# if it happens
