### ISSUE TITLE
SQL query editor with variables - no cascading on variables list

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4312]
Image:
![screen shot 2017-02-06 at 18 31 00](https://cloud.githubusercontent.com/assets/1330677/22675521/1284529c-ec9b-11e6-8822-98fe31d9833e.png)

Issue: The variables input fields don't get cascaded hence causing weird layout in UI
To reproduce: choose more than 2-3 variables and resize the browser.

PS: Disregard the wrong value in the query. I know that it should be table_name_1 etc.

**Comment by flamber** [comment]
Hi @VikramTiwari 
I don't remember when this was fixed - think it was 0.29.x - anyways, this is how it looks in 0.31.2
![image](https://user-images.githubusercontent.com/1447303/52681245-c13cbf00-2f00-11e9-95b4-0fce40976b4f.png)
