### ISSUE TITLE
Variables - Text value contains single quotes

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4313]
While this is a totally correct behavior for majority of the scenarios where one would use string, it does not work well when being used for metadata variables. Maybe this is the case only for BigQuery, but I doubt it.

Image:
![screen shot 2017-02-06 at 18 47 18](https://cloud.githubusercontent.com/assets/1330677/22675999/c3e0283e-ec9d-11e6-9076-dc123e16ead8.png)

Expected behavior: Shouldn't contain single quotes.

**Comment by VikramTiwari** [comment]
Similar to https://github.com/metabase/metabase/issues/3816

**Comment by camsaul** [comment]
@VikramTiwari what version of Metabase are you using?

**Comment by VikramTiwari** [comment]
Should have mentioned this while opening the issue. Latest release 0.22.2

**Comment by camsaul** [comment]
Fixed by #4325
