### ISSUE TITLE
Single metadata endpoint for a dashboard

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#43156]
Single /api/dashboard/:id/query_metadata endpoint that returns all metadata for a dashboard

This will improve the dashboard load performance

context: https://metaboat.slack.com/archives/C0645JP1W81/p1716586270545149

**Comment by ranquild** [comment]
Please use this format:
```
{
  databases: [ // /api/database OR /api/database/:id for each db
    database1,
    database2,
  ],
  schemas: { 
    dbId1: ["schema1", "schema2"], // /api/database/:id/schemas
    dbId2: ["schema1", "schema2"],
  },
  tables: [ // /api/table/:id/query_metadata and /api/table/card__:id/query_metadata
    table1,
    table2,
  ],
  fields: [ // /api/field/:id
  ]
}
```

Where entries are obtained by calling `Lib.dependentMetadata` for each card in the dashboard.
