### ISSUE TITLE
Connecting a filter to a model will render "unknown field"

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#43155]
### Describe the bug

If you connect a filter to model in a dashboard you get an "unknown field" error

### To Reproduce

1) create a model (orders join people)
2) add it to a dashboard
3) connect a categorical filter to it
4) see the error
![image](https://github.com/metabase/metabase/assets/1711649/7a0a5603-d1b5-4df9-9ee6-eddae9e70531)

### Expected behavior

It should show the name of the field

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P2

### Additional context

Probably related to https://github.com/metabase/metabase/issues/43154

(I believe it's a P2, but might have something to do with metadata so it could transform to a P1)

**Comment by paoliniluis** [comment]
pretty sure it has a strong connection to https://github.com/metabase/metabase/issues/42379

**Comment by ranquild** [comment]
@paoliniluis I cannot repro in v50. Could you double check?

**Comment by paoliniluis** [comment]
fixed
