### ISSUE TITLE
Animation happening when hovering between columns that prevents the column metadata from populating fast

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#43163]
### Describe the bug

There's a weird animation happening when I hover between columns

### To Reproduce

1) create a question and transform it into a model
2) then hover over the columns on the right, see the screen turning white'ish

### Expected behavior

It should not do any animation

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P3

### Additional context

![Peek 2024-05-24 19-44](https://github.com/metabase/metabase/assets/1711649/9b040c6d-8e52-4511-a39a-0493a46f0088)

**Comment by NevRA** [comment]
@paoliniluis can you help with reproduction?

**Comment by uladzimirdev** [comment]
@NevRA I was able to reproduce it using steps from @paoliniluis. `Orders` table and `Quantity` column do the trick
