### ISSUE TITLE
Support Azure Managed Identity

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#43168]
Support [Azure Managed Identity](https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-connect-with-managed-identity#retrieving-the-access-token-from-azure-instance-metadata-service) as an auth mechanism to login to Postgres hosted on Azure

context: https://metaboat.slack.com/archives/C01LQQ2UW03/p1716418798546319

This is a sample BASH script to do this
```

# Retrieve the access token

export PGPASSWORD=`curl -s 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fossrdbms-aad.database.windows.net&client_id=CLIENT_ID' -H Metadata:true | jq -r .access_token`

# Connect to the database

psql -h SERVER --user USER@SERVER DBNAME
```

**Comment by paoliniluis** [comment]
Same as IAM auth

**Comment by perivamsi** [comment]
Tracked here https://github.com/metabase/metabase/issues/43348
