### ISSUE TITLE
Variables - default value - overwrite

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4316]
Issue: The default value for a variable prevents the ability to totally remove the value and add a new value. The only way to do it is the write new value along with older value and remove older value.

Steps to reproduce:
- Create a SQL Query with variables and assign a default value to the variable
- Try to remove the value totally

Image:
![image](https://cloud.githubusercontent.com/assets/1330677/22679087/59c0f174-ecb4-11e6-8f19-ea23e5f1e083.png)

Expectation: 
One should be able to totally remove a value from UI and maybe even leave it blank. Once the query is run, these values will get populated with default values and reflect back in the UI.

**Comment by tlrobinson** [comment]
@VikramTiwari What version are you on? I think this might be fixed in `master`.

However, if you have a default set you can't run the query without either the default or another value. This is because the default is substituted on the backend if no other value is provided.

**Comment by VikramTiwari** [comment]
I am on v0.22.0

My expectation was that I should be able to remove it totally so that I can input a new value. But as soon as I do so, the default value kicks in. Will check if this is fixed in master.

**Comment by VikramTiwari** [comment]
I will check it this weekend and provide a closure (clojure? haha)

**Comment by camsaul** [comment]
Just tried to repo this and can confirm this is indeed fixed as we suspected back in April
