### ISSUE TITLE
Err: Card Nox not exists when try to connet two Models /Questions from different database.

### ISSUE THREAD

**Issue by Jianbin719** [metabase/metabase#43174]
### Describe the bug

I created two Questons), Once I try to create third question which includes two Questions from from two database. then the error comes, Card xxx not exists. 

My purpose to use metabase to connect two database and compare the completion of the sales target. 

### To Reproduce

1. Create two questions, they are from two database.
2. Create third question, and select two Question above
3. Error comes.

### Information about your Metabase installation

```JSON
All the latest version from edge and Metabase.
```

### Severity

blocking your usage of Metabase entirely

**Comment by Tony-metabase** [comment]
That’s not possible. One of the most requested features. You’ll have to use a data warehouse. For reference:

https://github.com/metabase/metabase/issues/3953
