### ISSUE TITLE
MYSQL - Regexextract option is not available anymore in GUI custom column 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#43180]
### Describe the bug

The regexextract option is no longer available on MYSQL for custom columns

### To Reproduce

1. Go to a MYSQL [Database](https://stats.metabase.com/browse/databases/11-magento-test) -> Custom Column and try to use the [regexextract](https://www.metabase.com/docs/latest/questions/query-builder/expressions/regexextract) -> Nothing shows up:

<img width="1047" alt="image" src="https://github.com/metabase/metabase/assets/110378427/c63949e6-3068-4cc5-9148-52d983590f18">

### Expected behavior

The function is given as an option:

<img width="1103" alt="image" src="https://github.com/metabase/metabase/assets/110378427/3ad904d0-0620-48db-9945-6c1c721a91d1">

### Logs

Nothing that are relevant

### Information about your Metabase installation

```JSON
replicated on 50 and on master
```

### Severity

it is a regression

### Additional context

If you have old questions coming from different version the regex still work but new questions don't work

**Comment by bshepherdson** [comment]
This is deliberate, and not a new change or a regression so far as I can tell. MySQL only supports a poor subset of regular expression features, so it does not have the `:regex` driver feature. That [controls](https://github.com/metabase/metabase/blame/master/frontend/src/metabase-lib/v1/expressions/config.ts#L116) the `regexextract` function appearing in expressions. That code and the setting of `:regex false` for MySQL have been around for years.

If newer MySQL versions support a fuller set of regex features, then perhaps `:regex` can be enabled for them. In particular, we have regexes that expect `:regex true` drivers to support things like lookahead and lookbehind. A separate feature request can be filed in that case.

**Comment by bshepherdson** [comment]
On further discussion, newer MySQL (and MariaDB) have proper PCRE support. I'm adding the `:regex` feature for the MySQL driver, and from Metabase 0.50 onwards `regexextract` (and other regex-powered features like extracting domains from emails and URLs) will be supported.

**Comment by bshepherdson** [comment]
Reopening until the backport to `release-x.50.x` lands.
