### ISSUE TITLE
[Epic] Streamline sandbox setup

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#43193]
After the v50 permissions refactor, the sandbox setup UX is weird.

At the database level, the `view data` permission is `granular` although the only reason to use this permission level is to set up `sandbox`.

For each table, the only available options are `can view` and `sandboxed`. We should have another option `can't see` that is the same as an empty sandbox.

**Comment by luizarakaki** [comment]
Closed in favor of table-level block

**Comment by jpleyden98** [comment]
Is there a link to the table-level block issue?
