### ISSUE TITLE
Questions based on a custom SQL query aren't updated

### ISSUE THREAD

**Issue by alexisvisco** [metabase/metabase#43216]
### Describe the bug

When you modify a SQL question A and you have a question B that use A, if you have modified A, B does not receive the change until you completely rewrite the question with the metabase editor. (B is metabase editor, A is plain SQL)

### To Reproduce

1. create a sql question that returns fields A, B and C
2. create a metabase editor based question using the first one
3. modify the first one to add a field D
4. returns in the second question, try to select the field D -> you can't unless you reset the question

### Expected behavior

It should receive change without need to almost destroy the question and restart everything ... 

### Information about your Metabase installation

```JSON
- metabase version 0.49.12
```

### Severity

annoying

**Comment by ranquild** [comment]
FE caching issue
