### ISSUE TITLE
Show timestamps to second resolution

### ISSUE THREAD

**Issue by jjohnston1** [metabase/metabase#4322]
Hi. Couldn't find this feature in Metabase v 0.21.0 or opened as an existing issue.

We have high frequency transaction data we're dumping into Druid. Doesn't appear there is a way to get a tabular view with timestamps to second resolution, i.e., "Tuesday, February 7, 2017 12:00:**00** AM". Things currently bottom out at the minute level. Any way to (optionally) show the greater resolution?

**Comment by camsaul** [comment]
Related: #2680

**Comment by flamber** [comment]
This was fixed in 0.31, which added a lot of formatting options - also showing seconds and milliseconds:
![image](https://user-images.githubusercontent.com/1447303/54221104-6de66e00-44b8-11e9-972b-fc3471667124.png)
