### ISSUE TITLE
 yarn build, getting error in executing this command

### ISSUE THREAD

**Issue by sandeepraghu** [metabase/metabase#43223]
ubuntu@ip-172-16-1-181:~/exploratory-analytics$ yarn build
yarn run v1.22.22
$ yarn build:cljs && yarn build:js
$ yarn && yarn build-pure:cljs
$ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^2.2.3"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^2.2.3"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^1.0.1"
warning Resolution field "set-value@4.0.1" is incompatible with requested version "set-value@^2.0.0"
warning Resolution field "unset-value@2.0.1" is incompatible with requested version "unset-value@^1.0.0"
warning Resolution field "set-value@4.0.1" is incompatible with requested version "set-value@^2.0.1"
warning Resolution field "source-map-js@1.2.0" is incompatible with requested version "source-map-js@^0.6.2"
warning Resolution field "nth-check@2.0.1" is incompatible with requested version "nth-check@^1.0.2"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^1.0.2"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^6.0.1"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^6.0.1"
success Already up-to-date.
$ husky install
husky - Git hooks installed
$ yarn clean-dev:cljs && shadow-cljs compile app
$ rm -rf target/cljs_dev/*
shadow-cljs - config: /home/ubuntu/exploratory-analytics/shadow-cljs.edn
shadow-cljs - starting via "clojure"
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
-A:cljs (No such file or directory)

Full report at:
/tmp/clojure-921353521078117295.edn
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by paoliniluis** [comment]
please more info: java version, node version, yarn version...

**Comment by sandeepraghu** [comment]
java --version
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)
node --version
v18.20.3
yarn --version
1.22.22

**Comment by paoliniluis** [comment]
branch?

**Comment by sandeepraghu** [comment]
master

**Comment by paoliniluis** [comment]
have you installed clojure cli?

**Comment by sandeepraghu** [comment]
yes

**Comment by sandeepraghu** [comment]
it build successfully with yarn build command 
but when i accessing it on a browser and adding database in that i am only getting two database option in database type dropdown. How to fix this?

**Comment by paoliniluis** [comment]
I don't understand the problem

**Comment by sandeepraghu** [comment]
thansk it is fixed!
