### ISSUE TITLE
Add question to Dashboard from Add Card in Dashboard bug broken

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#4327]
On clicking Add Card in a Dashboard, the search query does not work.

Also on clicking Everything Else, the scroll does not work. I can only select from a few questions.

Metabase: 0.22.2
OS: MacOS Sierra
Browser: Chrome 56.0.2924.87
DB: MySQL
Metabase Hosting Env: Jar on EC2.

**Comment by kdoh** [comment]
The scrolling part seems like it's the same issue I noted in #4413 (fix in #4414). I haven't been able to reproduce the search issue, although you do have to hit enter which might not be the most obvious.

**Comment by tlrobinson** [comment]
@kdoh can we close this?

**Comment by kdoh** [comment]
Yup.

**Comment by zaiddabaeen** [comment]
I did try the enter back then. Yes it works now, thanks. Nonetheless I understood intuitively that it is search on type, not on enter.
