### ISSUE TITLE
[ParseSQL] Handle shadowed names properly with find-and-replace

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#43291]

**Comment by crisptrutski** [comment]
@tsmacdonald some additional details on the requirements here would be helpful. 

The example we discussed in Slack already seems to be supported since we did the qualifier work, see the [following test](https://github.com/metabase/macaw/blob/4087b86/test/macaw/core_test.clj#L407-L419).

**Comment by tsmacdonald** [comment]
@crisptrutski this might deserve to be a separate issue (sorry for bad project management here) but I think now is the time to deal with your embedded model / transparent field ref business, which will require work on both the Metabase and Macaw side. Like

```sql
-- card 123
SELECT total FROM orders WHERE subtotal > 100

-- card 321
SELECT total FROM {{#123}}

/*
we want to replace orders.total with order.amount
*/

-- either:
-- new card 123
SELECT amount AS total FROM orders WHERE subtotal > 100

-- new card 321
SELECT total FROM {{#123}} -- unchanged

-- or, and I think preferably:
-- new card 123
SELECT amount from orders WHERE subtotal > 100

-- new card 321
SELECT amount FROM {{#123}}
```

**Comment by crisptrutski** [comment]
Yeah, I was also thinking it's a good time to pick that up 👍

**Comment by crisptrutski** [comment]
Closing this ticket to finish off where I see the scope of Milestone 5b ending, opening a new issue for tracking how fields are exposed to other cards.
