### ISSUE TITLE
Runtime errors when drilling down on Interactive Question component using SDK

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#43304]
### Describe the bug

Runtime errors when drilling down

### To Reproduce

1. Embed an interactive question component
2. Drill down (see these records)
3. The table loads but there are uncaught runtime errors

Loom: https://www.loom.com/share/2deefad86e1442108a2a71a24065e8f4

### Information about your Metabase installation

```JSON
- SDK npm v0.1.5
```

### Severity

P2

**Comment by albertoperdomo** [comment]
Related to https://github.com/metabase/metabase/issues/42352. We fixed the loading state, but we didn't remove the runtime errors.

**Comment by WiNloSt** [comment]
[We discussed that ](https://metaboat.slack.com/archives/C063Q3F1HPF/p1716985096688679?thread_ts=1716983463.904489&cid=C063Q3F1HPF)it's okay to prevent this specific error from surfacing to users for now if we can't fix the root cause.

**Comment by albertoperdomo** [comment]
I've tested again with 0.1.40 using https://github.com/metabase/metabase-nodejs-react-sdk-embedding-sample and getting the following error:

![Image](https://github.com/user-attachments/assets/cde059ce-3954-4736-b02c-c86baad6a05e)
