### ISSUE TITLE
[Epic] Remove field refs from viz settings

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#43306]
**Links**
- product doc: None - eng-led project
- [eng doc](https://www.notion.so/metabase/Tech-Remove-field-refs-from-viz-settings-bec453dc75bd40efb54a1ddb83acd536)
- feature branch: `viz-settings-deref`
- issue links: _This definitely is expected to fix several open issues but I don't have a list handy._

**Implementation Plan**

***Milestone 1: Foundation***

- [x] #43467
- [x] #43307

***Milestone 2: Consumption***

- [ ] #43308
- [ ] #43309

***Milestone 3: Storage***

- [ ] #43310
- [ ] #43311

**Future work**

`desired-column-alias` does not include the temporal unit of a breakout (nor should it). However, if we want to support multiple breakouts on the same column we need an alternative way to reference them, including from viz settings.

Similarly, `desired-column-alias` doesn't avoid the dangling refs issue: if there are, say, three `SUM` aggregations on different fields (`sum`, `sum_2` and `sum_3`) and they have viz settings defined, then deleting the middle one will result in dangling viz-settings for `sum_3` _and_ wrongly using the old `sum_2` viz settings for what is really `sum_3`.

**Comment by NevRA** [comment]
Decided to proceed in a dedicated epic
