### ISSUE TITLE
Full date range filter widget in dashboards

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#4332]
Currently there in the dashboard there are relative date filter, a single date filter, and date range filter. As a user i would like to see by default the last X days when opening the dashboard while having the possibility to select a specific date range if possible.

I find the old date filter quite intuitive. (Though perhaps could be better few more options (like quarter-6months). The new date filter is more powerful but maybe not as easy to use.

<img width="349" alt="screen shot 2017-02-08 at 22 48 47" src="https://cloud.githubusercontent.com/assets/1543669/22759025/3d1a5e54-ee51-11e6-8b7b-4d7bf13cd9c4.png">
<img width="334" alt="screen shot 2017-02-08 at 22 48 38" src="https://cloud.githubusercontent.com/assets/1543669/22759024/3d1a634a-ee51-11e6-99c2-df8384d8001a.png">

**Comment by tlrobinson** [comment]
Duplicate of #2959?

**Comment by moumny** [comment]
oops, my bad. 
I was sure that i commented on this once ^^
