### ISSUE TITLE
"Compact" and "Full" are flipped in viz settings > Auto formatting when presenting percentages

### ISSUE THREAD

**Issue by dahyeik** [metabase/metabase#43347]
### Describe the bug

Say you create a time series, like churn rate per quarter and you want the values of each quarter to show on the chart. So, you create the following chart 

<img width="1093" alt="Screenshot 2024-05-29 at 2 39 02 PM" src="https://github.com/metabase/metabase/assets/116025058/1279409e-57f1-4f88-83ad-f3f455a87549">

And go to visualization settings > display > toggle "Show values on data points". 

The "Compact" and "Full" buttons have opposite effects. 

### To Reproduce

1. Create a time series - i.e. count of orders grouper by month
2. Go to visualization settings > display > toggle "show values on data points"
3. Select "compact" or "full" in Auto formatting and see Metabase behave with opposite commands

<img width="773" alt="Screenshot 2024-05-29 at 2 46 03 PM" src="https://github.com/metabase/metabase/assets/116025058/d76d0808-e96f-4f15-a80a-71a2b64e9ac6">

<img width="803" alt="Screenshot 2024-05-29 at 2 46 23 PM" src="https://github.com/metabase/metabase/assets/116025058/098f4dec-bd74-4ec1-b395-2d642cb194fc">

### Expected behavior

Compact numbers should show compact values and Full numbers should the full values. 

### Information about your Metabase installation

```JSON
Database: H2 (sample database)
Metabase version: v1.49.13
Metabase cloud
```

### Severity

Not blocking since I can select the opposite option, might be annoying to our customers

**Comment by JesseSDevaney** [comment]
**Diagnosed Issue:** Essentially, when `full` formatting is used, it respects the `Minimum number of decimals` specified in the metric column formatting options, but `compact` formatting does not. `compact` formatting uses a different set of logic than `full` formatting does.

**Demo**

https://github.com/metabase/metabase/assets/22608765/f7ab2af0-8269-463c-acc2-29afbad420ad
