### ISSUE TITLE
The branch name make git error on Windows: `39026-metrics->legacy-metrics`

### ISSUE THREAD

**Issue by cowcomic** [metabase/metabase#43355]
### Describe the bug

> git fetch origin
error: cannot lock ref 'refs/remotes/origin/39026-metrics->legacy-metrics': Unable to create 'D:/code/metabase/.git/refs/remotes/origin/39026-metrics->legacy-metrics.lock': Invalid argument
From https://github.com/metabase/metabase
 ! [new branch]            39026-metrics->legacy-metrics -> origin/39026-metrics->legacy-metrics  (unable to update local ref)

### To Reproduce

git fetch or git pull on windows

### Information about your Metabase installation

```JSON
- Windows
```

### Severity

blocking build

**Comment by metamben** [comment]
I've just deleted the branch, it's PR has been closed.
