### ISSUE TITLE
Fix DashcardMenu.shouldRender perf

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#43360]
<img width="749" alt="image" src="https://github.com/metabase/metabase/assets/125459446/a1f99285-8ca7-4b62-b696-22011a325d1f">

```
const { isEditable } = Lib.queryDisplayInfo(question.query());
return question.canWrite() && isEditable;
```

if possible, we need to optimize `question.query()` or `question.canWrite()`

**Comment by ranquild** [comment]
I think this is the same story about `isEditable`. We need to move this check to the BE.

**Comment by uladzimirdev** [comment]
closing it then
