### ISSUE TITLE
Cannot edit advanced sandboxing SQL Question

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#43371]
### Describe the bug

There is a particular advanced sandboxing question which is failing when trying to save:

![image](https://github.com/metabase/metabase/assets/110378427/07033adc-b753-4eaf-b27d-ec19aa7b8dc9)

### To Reproduce

I am not able to reproduce but the customer is hitting an issue like this:

`Cannot update Card: Card is used for Sandboxing, and updates would violate sandbox rules. No fields found for table "MITM_PROTECTION_DETAILS". {:table-id 577, :type :invalid-query, :toucan2/context-trace [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection" {:toucan2.jdbc.query/sql-args ...`

Attaching the problematic collection for reference https://drive.google.com/file/d/1btUZI6aGdzZU2YO6SJq2s74Wy0_41HXO/view?usp=drive_link

In case you want to import said question locally

### Expected behavior

Able to save Sandboxing Question ... Note this is impacting the serialization process because the question is ending in the same state 

### Logs

Had to attach a file due to some Github max character error

[export_error.zip](https://github.com/metabase/metabase/files/15500592/export_error.zip)

### Information about your Metabase installation

```JSON
They are currently on 1.49.12 but they are old timers on metabase so those sandboxed questions might have been created in 1.47 or even 1.44/1.45
```

### Severity

A customer is blocked since they are moving form Serialization v1 to v2 and they need this to work

**Comment by Tony-metabase** [comment]
@piranha just an FYI this is related to results metadata. If the customer removes all problematic card (cause he has a lot) and leaves only 1 ... The import still fails. 

BUT if they go to this SQL card, do a small edit and save, then export and import it works. So it's something related to metadata which requires update when it's on a different version.

**Comment by noahmoss** [comment]
Here's what we know after some investigation. Copying over my comment [from Slack](https://metaboat.slack.com/archives/C064EB1UE5P/p1721405962906229).

* A SQL question A is used as the source for a sandbox on a table T 
* When this question is edited and re-saved as B, we try to verify that that the result metadata of B matches up with the types of the columns in T
* To determine the column types for T we construct a basic MBQL query that selects from T and call metabase.query-processor.preprocess/query->expected-cols on it

This ultimately throws an exception in metabase.query-processor.middleware.add-implicit-clauses/sorted-implicit-fields-for-table saying that no fields were found for the table. This is the function which fetches the fields:
```
(defn- table->sorted-fields
  "Return a sequence of all Fields for table that we'd normally include in the equivalent of a `SELECT *`."
  [table-id]
  (->> (lib.metadata/fields (qp.store/metadata-provider) table-id)
       (remove :parent-id)
       (remove #(#{:sensitive :retired} (:visibility-type %)))
       (sort-by (juxt :position (comp u/lower-case-en :name)))))
  ```
So if this issue reproduces consistently for the user, I'd expect a basic MBQL query over the table being sandboxed to also fail with a similar error.

The closest thing I can get to a repro is to set the visibility of all the fields in a table to hidden. Then I do get an equivalent error when querying it. Screenshot attached.

So the next things I'd look at are:
* Is the metadata provider not correctly including fields for this table, or is lib.metadata/fields not returning them properly?
* If fields are being returned, are they all marked as sensitive/retired? (I'm not sure what the :parent-id removal is about but maybe that's in play too)

**Comment by noahmoss** [comment]
@Tony-metabase If this customer is still seeing this issue, can they check if they can view the table that's being sandboxed at all? i.e. just via the data browser

**Comment by perivamsi** [comment]
more context in this [slack thread](https://metaboat.slack.com/archives/C052ZBWRG3W/p1717075622845209)

**Comment by metamben** [comment]
An admin user can see about 50 columns in the `CONFIGURATION_TAMPERING_ATTEMPT_DETAILS` table.

**Comment by metamben** [comment]
The problem is that the sandboxed table (and all it's columns) have `active = false`, so the QP cannot find any columns.

**Comment by mngr** [comment]
Can we close this?

**Comment by Tony-metabase** [comment]
No, the customer still has this issue but we are trying to surgically fix it via the DB

**Comment by NevRA** [comment]
Update based on https://metaboat.slack.com/archives/C013N8XL286/p1725896356839389?thread_ts=1725892783.667429&cid=C013N8XL286

**Comment by Tony-metabase** [comment]
Closing since we surgically fixed this via the DB
