### ISSUE TITLE
Query button not showing up under new drop down

### ISSUE THREAD

**Issue by amaliacote** [metabase/metabase#43402]
**Describe the bug**
When I go to the New drop down, 'New Query' isn't there (I can't remember if that's what it's called). I only see the option to add new Dashboard or new Collection.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
<img width="672" alt="image" src="https://github.com/metabase/metabase/assets/130695508/2ccfdb0e-ec24-4499-8dfe-6e848a355649">

**To Reproduce**
1. Go to New
2. Querying option not there

**Expected behavior**

Ability to query.

**Screenshots**
<img width="441" alt="image" src="https://github.com/metabase/metabase/assets/130695508/3dc3f3dd-364c-49ec-929c-9950ca52fd56">

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

This is blocking my usage of Metabase entirely so it is pretty high priority.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en",
    "platform": "Mac",
    "userAgent": "Chrome",
    "vendor": "Google Inc."
  }
}
```

**Comment by ignacio-mb** [comment]
Hi @amaliacote, can you paste the complete diagnostic information please?

**Comment by paoliniluis** [comment]
closing due to a lack of an answer
