### ISSUE TITLE
[feature] Increase number of colors for Line Charts

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#4342]
Feature Request:
Add more colors to the line charts. They are not enough for showing high density graphs.

![image](https://cloud.githubusercontent.com/assets/5732288/22776417/3c631ed0-eeb8-11e6-9d30-9dc91da5f088.png)

P.S: The sixth color (white) is actually showing as blue (default color).

- Metabase version: 0.22.2
- Metabase hosting environment: Jar on EC2

**Comment by tlrobinson** [comment]
This is done in `master` #4270

Duplicate of #3185

**Comment by zaiddabaeen** [comment]
Aaaah sweet 👍
