### ISSUE TITLE
Add ability to filter by dimensions in questions

### ISSUE THREAD

**Issue by tanzoniteblack** [metabase/metabase#4346]
### Feature requests and proposals

While it's great that we can filter by dimensions for sql cards on dashboards, I don't see any reason why this same functionality can't also be done on questions.

The main use case is that users can download data, or filter data, on an explicit question as well as a dashboard regardless of whether the card was written in sql or through the query builder. The current parameters in sql give us a start in this direction, but remove the usefulness of the parameter widgets (like changing between `=` and `contains`, using the date/time picker, or selecting from a list of available values.

Is there any reason we can't just connect something similar to what we use in the query builder for fields once the SQL creator has entered in which field the parameter is filtering on?

**Comment by flamber** [comment]
Field Filters has been around for a very long time and can be used on questions and dashboards.
Related to #5245/#6820
