### ISSUE TITLE
Can't edit joined tables after saving the question

### ISSUE THREAD

**Issue by abcRede** [metabase/metabase#43531]
### Describe the bug

After saving a question, I can no longer edit the joined table. 

I can add and remove joined tables, but the existing ones aren't editable (can't change from table A to table B). 

At first it seemed like a limitation, however I suspect this is a bug, because if I add a new join (which I can do), and if it pick a wrong join field (which may exists in complex tables) , then I can't correct, and it will use wrong auto picked one.

### To Reproduce

1. Create a new question
2. Add a few joins
3. Save the question
4. Try editing the question changing one of the joins you made. You'll be able to change the left and right column, but you won't be able to change the left and right tables.

[Gravação de tela de 2024-06-03 14-18-38.webm](https://github.com/metabase/metabase/assets/119939906/ec31fe18-a270-4313-9d67-b30f4381f1af)

### Expected behavior

You should be able to edit joined tables.

### Logs

There are no relevant logs in  Troubleshooting -> Logs or in Javascript.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.0-71-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.31-0ubuntu0.22.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-28",
      "tag": "v0.49.13",
      "hash": "de28e83"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

It's very annoying, users can't edit a mistake after saving.

**Comment by romeovs** [comment]
This persists in 49.17 but was fixed with the new data picker in 50.

**Comment by romeovs** [comment]
@abcRede I'm closing this issue for now, as it is fixed in v50, please reopen if the issue persists.
