### ISSUE TITLE
Securely store sensitive credentials

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4353]
Now that #4341 is merged, we should also optionally store things like SMTP keys, etc encrypted. 

Candidates 
* SMTP password
* Slack Secret API key
* ???

**Comment by camsaul** [comment]
I think we're already storing `???` securely, at least in the sense of security through obscurity. Since noöne is sure what it is, it's hard to steal it from the DB 😂

**Comment by vietvudanh** [comment]
Wow, it is really need to add this into must to-do list. 

No encryption on these data seems pretty dangerous to me. Not all sysad know how to secure the connections.
