### ISSUE TITLE
URLs won't work as expected

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4358]
Example:
Works: https://metabase.example.com/reference/guide
Not so much: https://metabase.example.com/reference/guide/

A trivial issue but should be following normal URL rules.

**Comment by tlrobinson** [comment]
Are you manually typing the trailing slash, or is there anywhere in the app we link with the trailing slash?

**Comment by VikramTiwari** [comment]
Sorry for delayed response. That was a manual try/happenstance.

**Comment by flamber** [comment]
I cannot reproduce on 0.35.3 - I think it was fixed a long time ago with an upgrade of Jetty
