### ISSUE TITLE
Row Chart breaks sort order when resized

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4359]
Here's a table of the average number of runs scored per baseball game, broken out by the ballpark. It's sorted in descending order by the average:
![screen shot 2017-02-10 at 3 43 34 pm](https://cloud.githubusercontent.com/assets/2223916/22848226/d48da9f6-efa7-11e6-9ee0-14debf10a12b.png)

When I increase the height of my browser window, allowing more rows to be displayed and taken out of the `Other` bucket, Metabase shows the new rows in a willy nilly order:
![screen shot 2017-02-10 at 3 43 44 pm](https://cloud.githubusercontent.com/assets/2223916/22848280/27cc9cc6-efa8-11e6-8430-fe48b00b3afc.png)

**Comment by tlrobinson** [comment]
Due to dc.js wackiness https://github.com/dc-js/dc.js/issues/598

We have a workaround for the other charts, I'll apply it to row chart as well.
