### ISSUE TITLE
Serialization - Inconsistent datasource YAML for password field for MongoDB

### ISSUE THREAD

**Issue by taqattack** [metabase/metabase#43615]
### Describe the bug

Datasource YAML file for MongoDB shows password field as "pass" instead of "password" like other datasources.

### To Reproduce

1. Export Metabase with MongoDB connection with "-s" parameter
2. Edit datasource YAML file for this connection.
3. Notice that the password field is set as "pass" and not "password" like other data sources
4. Changing it to "password" and then importing it breaks the connection in Metabase

### Expected behavior

"pass" should be the same as "password" for consistency

### Information about your Metabase installation

```JSON
v1.50.0-RC1
```

### Severity

annoying

**Comment by calherries** [comment]
I wouldn't label this a bug, this is merely an annoyance. While I agree it's a little unexpected, the password connection property for MongoDB has always been `pass`. Changing it to `password` will break backwards compatibility so to solve this we'd have to maintain both `pass` and `password`. And allowing multiple names for the same property is simply complicating things for not much gain, unless there's a use case that requires they are consistent across databases. I'm inclined to close this issue until there's a greater reason to act on this.

**Comment by darksciencebase** [comment]
confirming with the product team
