### ISSUE TITLE
Feature: Kubernetes Deployment

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4363]
Using images from docker hub

- [x] Deployment file
- [x] Service file
- [x] Docs
- [ ] Feedback

**Comment by VikramTiwari** [comment]
@camsaul @salsakran Feedback?

**Comment by allansene** [comment]
Just deployed on my cluster. All seems ok... :+1:

**Comment by jamesjrg** [comment]
Not entirely sure about this, but should `- containerPort: 80` be 3000 instead? I think as long as the target port in the service YAML is correct it will work either way regardless, but as I understand it containerPort should be the internal port.

**Comment by VikramTiwari** [comment]
@jamesjrg Do you mean this? https://github.com/VikramTiwari/metabase/blob/608bf027702ff60c5717ea528927f23f475e6423/bin/kubernetes/ingress.yaml#L21

Container port is 3000. here: https://github.com/VikramTiwari/metabase/blob/608bf027702ff60c5717ea528927f23f475e6423/bin/kubernetes/deployment.yaml#L21

**Comment by imsky** [comment]
nice 😎

**Comment by imsky** [comment]
@VikramTiwari why does the service need to be of `NodePort` type? Metabase can work with a load balancer, no?

**Comment by VikramTiwari** [comment]
@imsky I am currently trying to make it work with Kube-Lego + GCP so that it's secure by default using LetsEncrypt SSL certificates. `NodePort` is one of the requirements of Kube-Lego to run on GCP.
Ref: https://github.com/jetstack/kube-lego#gce-loadbalancers

**Comment by jamesjrg** [comment]
Sorry, I was looking at an old version of the file, `bin/kubernetes/web-deployment.yaml`, which has since been deleted

**Comment by igorlimansky** [comment]
Successfully deployed and configured with my mongodb, thanks! 👍

**Comment by VikramTiwari** [comment]
Closing this in favor of https://github.com/metabase/metabase/issues/5736 https://github.com/kubernetes/charts/tree/master/stable/metabase Go helm charts!
