### ISSUE TITLE
Instrument parsing performance

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#43645]

**Comment by crisptrutski** [comment]
I presume this is around performance in prod?

It would also be good to have some micro benchmarks in the repo.

**Comment by crisptrutski** [comment]
I did a bit of benchmarking of queries in our tests, using clj-sync-profile. Timewise the analysis was taking about 14% of the time, with database queries taking up the remainder, which was a bit more than I expected, but not alarming. Given there's little low hanging fruit on the database side, this is probably fine.

**Comment by crisptrutski** [comment]
Passing this over to Tim as I'm not sure what the brief is here

**Comment by tsmacdonald** [comment]
We decided that with manual monitoring/testing on stats, the general tooling surrounding k6, etc., performance is okay and doesn't need further scrutiny
