### ISSUE TITLE
Pinned Models lack an icon

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#43658]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/6377293/2c347453-4426-42a2-a363-1e494c29b7d9)

### To Reproduce

a

### Information about your Metabase installation

```JSON
a
```

### Severity

p3

**Comment by WiNloSt** [comment]
Closed because it's a duplicate of https://github.com/metabase/metabase/issues/43659
