### ISSUE TITLE
Error: There was a problem displaying this chart

### ISSUE THREAD

**Issue by progremir** [metabase/metabase#43654]
**Describe the bug**
Question/model is not showing up in dashboard. Even tho the question/model itself is working as expected. This started happening after I added a date range filter to the dashboard.

**Logs**

[Console logs](https://gist.github.com/progremir/ee7cdaac9b80df4ba3a6bee17246baee)

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1204" alt="image" src="https://github.com/metabase/metabase/assets/17231674/8ff4fc25-c510-4f4c-b0d8-262179fd29ef">

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.217-205.860.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-28",
      "tag": "v1.49.13",
      "hash": "de28e83"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
Please contact the support email as it seems you’re a pro or enterprise customer

**Comment by progremir** [comment]
Will do! thanks
