### ISSUE TITLE
Unable to Use Custom SQL Questions with Parameters in Dashboard? +Ability to Select Columns from Multi-Column Result

### ISSUE THREAD

**Issue by orware** [metabase/metabase#4367]
### Feature requests and proposals

I didn't seem to see an issue touching this directly (at least in name) but I'm noticing that if I did create a custom question that required a parameter in order for a result to be displayed, it doesn't allow me to really use this within a dashboard at the moment.

When I try and do so it just shows up in the Dashboard as "There was a problem displaying this chart" but I was thinking I'd be able to use the Dashboard to combine multiple quick "info lookup" tools (such as searching for a user by username, ID, or first and last name) into a single area.

In other cases it'd be nice to have a general custom question that's been prebuilt with a variable and to be allowed to select which value that variable should use in the dashboard (which enhances the reusability of the original question that's been built).

Related to this idea of being able to more easily reuse questions, I had created a question that contained multiple columns and in the Dashboard I would have liked to use the same question twice, but only display the result of each column separately.

For example, a result that contains the term, the number of enrollments and the total capacity we have available would be in a result filtered by the current term code. Our variable in this case would be the term code, but I might want to use the question twice in the dashboard. In the first case, I'd like to be able to select the enrollments value to be displayed in that nice bigger format used for the questions that just have a single number value returned. Then create a second copy of it in the dashboard and be able to select just the capacity value. Even nicer would be some option to show them together in a single card to save some space but show the enrollments in a much bigger format with the capacity shown there in a smaller font.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ecommandeur** [comment]
Seems that these are separate requests that perhaps should have their own issue. The second request got me thinking: now a question conflates both the actual question and the visualization of the question. Perhaps one way to reuse questions is to be able to store (SQL) queries and refer to these queries in a question. That would be hugely useful.

**Comment by viluon** [comment]
**Bump**! Is this still not implemented (the first issue)? Are parametric questions really unusable with Dashboards?

**Comment by flamber** [comment]
Closing this in favor of the following - please go and upvote by clicking :+1: on the first post:
#6449 - being able to pass-thru filters from nested questions
#5320 - better errors on missing Required filters
#3575 - being able to set fixed value of a dashboard card
