### ISSUE TITLE
Font Sizing / Number Rounding Options in Dashboards

### ISSUE THREAD

**Issue by orware** [metabase/metabase#4369]
### Feature requests and proposals

I was creating a dashboard which contained mostly numerical items and when the card is sized to the smaller 3x3 option I didn't like how it started rounding my numbers even though there was plenty of horizontal space for the number to be displayed.

For example, the number 2,820 was changed to be 2.8k and 22,676 was changed to 22.7k. For larger numbers perhaps this might be a bit more useful, but in our case being able to look at the exact numbers should be an option without having to go to the larger sized 4x4 card.

Also, when trying this out I initially had an idea to emphasize one card really strongly in a really large card, and then have a secondary value off over to the side in a smaller card. I was hoping that the numeric value's font size in the larger card would be resized to take up more of the  available space but while the card size increased, the amount of space the numeric value took up within the card did not, so it really didn't matter that I had increased the card size at all since it didn't increase the size of that number within the card the way I was hoping it might. Having some sort of feature that could be configured in these cases to increase the size of the number within the card according to some relative value would be nice :-).

**Comment by MarkRx** [comment]
Agreed. The rounding is annoying.

**Comment by Go2ClassPoorYorick** [comment]
I'm surprised this change isn't more popular- the current use of the dashboard is hugely wasteful- I can display a maximum of 6 single line numbers wide, and 3 tall, on a 1440p screen- on a 1080 screen it's only just able to handle the same number of cards, cutting off the bottom of the last screen.

This is hugely wasteful when trying to use dashboards for any sort of presentation, not to mention that even at this stupidly large sizing for the cards themselves, I can't display more than 4 digits (rounded) of a 6 digit number- meaning that if we'd like to quickly see more accurate numbers the amount of space available gets even smaller.

**Comment by oddgames-david** [comment]
Yes please, trying to find out what my average session per user is at a quick glance... I need the decimal.

**Comment by vitoravancini** [comment]
Was this ever solved or worked around somehow?

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.

**Comment by GitBronch** [comment]
You can kind of hack this by editing manually metabase's database to adjust the size of the cards under the limits of the dashboard editor. Go to the table report_dashboardcard. The columns row and col are the coordinates in the dashboard grid. They start by 0. Columns "sizeX" and "sizeY" are self-explanatory just take into account that the size is counted from the starting coordinates to the left/down. Minimum size is 0, max X is 18
