### ISSUE TITLE
[Flaky Test]: should be able to reference a saved native question that ends with a semicolon `;` (metabase#28218)

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43707]
Last Flake: https://github.com/metabase/metabase/actions/runs/9357716394
Last Flake Time: 2024-06-03T15:21:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 2
Flakes in the last 7d: 2

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9407548339
Last Flake Time: 2024-06-06T14:17:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 1
Flakes in the last 7d: 3

**Comment by nemanjaglumac** [comment]
Fixed by #46048
