### ISSUE TITLE
[Flaky Test]: odal should switch back to not having tabs when the search query is cleared

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43709]
Last Flake: https://github.com/metabase/metabase/actions/runs/9360217246
Last Flake Time: 2024-06-03T19:45:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by JesseSDevaney** [comment]
Closing as this test does not appear to be flaking anymore/the posted CI run does not even have a test failure for the test it is mentioning.
