### ISSUE TITLE
[Flaky Test]: should always show the most recent revision (metabase#16559)

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43700]
Last Flake: https://github.com/metabase/metabase/actions/runs/9357939752
Last Flake Time: 2024-06-03T16:08:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 6
Flakes in the last 7d: 12

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9407924722
Last Flake Time: 2024-06-06T16:59:00-07:00
Flakes in the last day: 2
Flakes in the last 3d: 11
Flakes in the last 7d: 11

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9423499617
Last Flake Time: 2024-06-09T23:15:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 4
Flakes in the last 7d: 17

**Comment by kamilmielnik** [comment]
Fixed by #49472
