### ISSUE TITLE
Add a tooltip on a cutted text in table when mouse over

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4370]
![image](https://cloud.githubusercontent.com/assets/1708680/22877024/7f636026-f1e4-11e6-93fc-49800047d259.png)

⬇️ Please click "like" instead of "+1" comment

**Comment by tlrobinson** [comment]
👍 

If anyone wants to do this we already have an `Ellipsified` component that should make it easy.

**Comment by flamber** [comment]
This was added in 0.33, if I remember correctly. On 0.35.3 it looks like this:
![image](https://user-images.githubusercontent.com/1447303/82841479-8896de00-9ed6-11ea-9ab7-2f5ab486db60.png)
