### ISSUE TITLE
[Flaky Test]: should work when set as the default filter

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43703]
Last Flake: https://github.com/metabase/metabase/actions/runs/9360021255
Last Flake Time: 2024-06-03T19:00:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 5
Flakes in the last 7d: 5

**Comment by JesseSDevaney** [comment]
Closing as it does not appear to be flaking anymore + I cannot find where the old flake was even occurring:
![image](https://github.com/metabase/metabase/assets/22608765/82420f42-f781-465f-aa3f-d08928fb2cec)
