### ISSUE TITLE
[Flaky Test]: scenarios > visualizations > line/bar chart > tooltips > percent change across daylight savings time change should not omit percent change the week after DST begins

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43702]
Last Flake: https://github.com/metabase/metabase/actions/runs/9358676003
Last Flake Time: 2024-06-04T07:41:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 5
Flakes in the last 7d: 6

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9405346911
Last Flake Time: 2024-06-06T11:18:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 2
Flakes in the last 7d: 4

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9422395346
Last Flake Time: 2024-06-09T23:15:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 6
Flakes in the last 7d: 9

**Comment by JesseSDevaney** [comment]
Similar to #43701, closing as it appears this was fixed by:
- https://github.com/metabase/metabase/pull/43975
