### ISSUE TITLE
[Flaky Test]: should work when set through the filter widget

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43704]
Last Flake: https://github.com/metabase/metabase/actions/runs/9360021255
Last Flake Time: 2024-06-03T19:00:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 5
Flakes in the last 7d: 5

**Comment by JesseSDevaney** [comment]
Similar to #43703, closing as it does not appear to be flaking anymore + I cannot find where the old flake was even occurring:
![image](https://github.com/metabase/metabase/assets/22608765/97e32a4c-f19e-4900-a503-01ce440d61d7)
