### ISSUE TITLE
[Flaky Test]: scenarios > visualizations > line/bar chart > tooltips > percent change across daylight savings time change should not omit percent change on April

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43701]
Last Flake: https://github.com/metabase/metabase/actions/runs/9373741984
Last Flake Time: 2024-06-04T13:58:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 5
Flakes in the last 7d: 7

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9407877818
Last Flake Time: 2024-06-06T14:56:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 6
Flakes in the last 7d: 11

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9437892268
Last Flake Time: 2024-06-09T09:51:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 3
Flakes in the last 7d: 3

**Comment by JesseSDevaney** [comment]
Closing as it appears this was fixed by:
- https://github.com/metabase/metabase/pull/43975
