### ISSUE TITLE
[Flaky Test]: tag dimension should default to string/= for a new low cardinality string field filter

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43713]
Last Flake: https://github.com/metabase/metabase/actions/runs/9360097620
Last Flake Time: 2024-06-03T19:33:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9405559240
Last Flake Time: 2024-06-06T11:17:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 2

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9498293569
Last Flake Time: 2024-06-13T04:08:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 2
Flakes in the last 7d: 3

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9967292106
Last Flake Time: 2024-07-16T19:41:00-07:00
Flakes in the last day: 5
Flakes in the last 3d: 11
Flakes in the last 7d: 19

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9967292106
Last Flake Time: 2024-07-16T19:41:00-07:00
Flakes in the last day: 5
Flakes in the last 3d: 11
Flakes in the last 7d: 19

**Comment by nemanjaglumac** [comment]
Fixed by https://github.com/metabase/metabase/pull/45978
