### ISSUE TITLE
The insert statement will be executed

### ISSUE THREAD

**Issue by sw2011** [metabase/metabase#43722]
### Describe the bug

Create a new "SQL problem", enter "insert into a (id) values (1)" and execute it. The execution will be successful, and select with no result will be returned

### To Reproduce

1. to 'SQL PROBLEM'
2. write on "insert into a (id) values (1)" 
3. Records inserted into the database

### Information about your Metabase installation

```JSON
Metabase version 0.49.13
```

### Severity

Serious impact on the database, but can be avoided by revoking permissions

**Comment by paoliniluis** [comment]
Sorry I don’t understand what you’re doing

**Comment by sw2011** [comment]
What I mean is that when an insert statement is executed in the SQL editor of Metabase, it will be successfully executed; In historical versions of Metabase, this syntax has been reported as an error and cannot be executed.
