### ISSUE TITLE
Show date range on Pulse time series x-axis

### ISSUE THREAD

**Issue by timabe** [metabase/metabase#4375]
When I look at a time series chart in a pulse, the labels are generally Today and Yesterday. I'd also like to be able to see the **earliest day, so I can get a sense of how much time the chart spans.** 

Design Ideas
1. Add the date range next to the card title (next to "Updates per Day" in the image)
2. Align the Today/Yesterday to the right side and put the earliest date on the left side (where Feb 11 is in the image)

![screen shot 2017-02-13 at 4 10 01 pm](https://cloud.githubusercontent.com/assets/1427277/22909103/faafff7e-f206-11e6-9951-6060a833eae1.png)

**Comment by kdoh** [comment]
@timabe Yeah we definitely need to take another stab at pulse layouts, especially for time series. Dig all the suggestions in this.

**Comment by mtvan** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction.

**Comment by flamber** [comment]
Closing in favor of #6518
