### ISSUE TITLE
Logs filled with 'uploads-enabled' has been removed; use 'uploads_enabled' on the database instead

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#43756]
### Describe the bug

For some reason my logs are filled with WARN metabase.public-settings :: 'uploads-enabled' has been removed; use 'uploads_enabled' on the database instead

### To Reproduce

1) start a metabase with a postgres db as the app db
2) start it and authenticate
3) check the logs

### Expected behavior

We should not have that error at all

### Logs

NA

### Information about your Metabase installation

```JSON
v50-RC2
```

### Severity

P2

### Additional context

NA

**Comment by perivamsi** [comment]
This is not a release blocker, removing 50 milestone

**Comment by dpsutton** [comment]
This arises from https://github.com/metabase/metabase/pull/42869. That PR adds these logs. Unclear at a quick glance what should happen.
