### ISSUE TITLE
Sorting not working in the query builder with a group

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4377]
Metabase 0.22.1

![image](https://cloud.githubusercontent.com/assets/1708680/22920992/e7b05692-f2a8-11e6-92e9-61ff1abf0717.png)

**Comment by kdoh** [comment]
Hey there @anki-code. I believe this is a duplicate / related to #3939. If you have some additional details, lets collect them there.

**Comment by anki-code** [comment]
@kdoh hm... this issue not about label but about sorting. When I choose the second field for sorting then I see no sorting in table by this field.

**Comment by kdoh** [comment]
Hey @anki-code. Yup I totally understand. After doing a bit of digging I'm fairly sure the two issues are most likely related, so that's why I suggested we group that info together instead of having separate issues.
