### ISSUE TITLE
Why world map is cropped at the top? 

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#4378]
When I open the MAP, MAP is cropped from the top section. The below picture speaks thousands word:
![screen shot 2017-02-14 at 2 13 07 pm](https://cloud.githubusercontent.com/assets/6417083/22926304/3ed4e830-f2c1-11e6-99d8-064c382813b7.png)

Is this a bug? How should I solve this issue?

- browser and the version: (Chrome 56.0, Firefox Developer Edition 53.0)
- operating system: (OS X 10,)
- databases: (MySQL)
- Metabase version: (0.22.2)

**Comment by kdoh** [comment]
Hey there @alirezastack. This seems like a bug. I was able to reproduce this.
