### ISSUE TITLE
Users with "View" permissions on a collection can modify dashboard

### ISSUE THREAD

**Issue by j-p-k** [metabase/metabase#4379]
I realize there are a number of tickets on improved permissions, e.g. #4333, #3363, #2682, and #1175. The purpose of this issue is to understand whether the behaviour observed is a bug independent of the more general effort to improve the model of permissions:

A collection can has three levels of privileges, which have an affect on dashboards.

1. Red: Revoke Access
2. Yellow: View
3. Green: Curate Collection

* On level red, dashboards are hidden.
* On level yellow, dashboards are visible *and can be modified*
* On level green, same as level yellow.

It appears there is no level for read-only access to dashboards. Is this desired?

version v0.22.2 -- Built on 2017-01-26

**Comment by mazameli** [comment]
Yeah, I think I understand your confusion. The way collection permissions affect cards in dashboards can feel odd, especially if a dashboard only contains questions from a single collection. However, it's possible for dashboards to contain questions from any and all collections, so trying to sort out dashboard permissions from collections would lead to some strange UX dead-ends (e.g., If I have View/Yellow level permissions for half of the cards in a dashboard, but Curate/Green permissions for the rest of the cards in the dashboard, can I edit it?) 

Our current thinking is that instead, we'd implement permissions at the _dashboard_ level, for each dashboard independently. We would probably handle Pulses the same way.

**Comment by remydavid** [comment]
+1 for permissions at the dashboard level

**Comment by pygeek** [comment]
+1 for permissions at the dashboard level

**Comment by mnzt** [comment]
Getting to the stage where lots of keen fingers are playing around with our metabase instance, and we're definitely worried some dashboards may be modified by mistake.

Permissions here would be glorious.

**Comment by jornh** [comment]
I believe this is resolved in version 0.30 - and can be closed.

@j-p-k if you’re still around can you verify it meets your needs, and if not comment or otherwise help in keeping it neat and tidy in here and close this issue as resolved?

**Comment by j-p-k** [comment]
OK
