### ISSUE TITLE
Make enhancement on dashboard by adding static text as a widget by format

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#4384]
I have created a dashboard with multiple reports (questions). But as a dashboard on a big screen there is something that is missing. When creating a numeric widget, numbers are small:  

![screen shot 2017-02-15 at 10 17 32 am](https://cloud.githubusercontent.com/assets/6417083/22963368/03196062-f368-11e6-82f9-28dd3119ee1d.png)

I think it could be much readable if text font size and formatting was customizable. As picture above, numeric widget's height could not be less than the height shown above! It takes so much space and I cannot put more widgets when there is less room for questions.

**Comment by kdoh** [comment]
Hey @alirezastack. I think we'll want to tweak our scalar font sizing logic a bit as noted by you,  @orware in #4369, and others elsewhere.

One trick if you're putting a Metabase dashboard on a big screen is you can put the dashboard in fullscreen mode and in that mode we increase the font size a bit to account for viewing from a farther distance.

<img width="1386" alt="screenshot 2017-02-15 09 31 35" src="https://cloud.githubusercontent.com/assets/5248953/22986828/99f5cbb2-f361-11e6-8019-c8a7483ac334.png">

You may already know about this but I couldn't tell from your screenshot.

**Comment by benjamin-pinaya-mojix-com** [comment]
Any tips to add static text as a widget? I wanted to customize some titles for the dashboard.

**Comment by mazameli** [comment]
@benjamin-pinaya-mojix-com our next release will include text cards, with Markdown formatting supported: https://github.com/metabase/metabase/pull/6436

**Comment by flamber** [comment]
Closing in favor of #2552 - upvote by clicking :+1: on the first post
