### ISSUE TITLE
[Flaky Test]: basic-timeseries-test

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43879]
Last Flake: https://github.com/metabase/metabase/actions/runs/9388257785
Last Flake Time: 2024-06-05T10:47:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9490526367
Last Flake Time: 2024-06-12T16:07:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by qnkhuat** [comment]
Fixed by https://github.com/metabase/metabase/pull/43924
