### ISSUE TITLE
[Flaky Test]: should automatically pin newly created models

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43870]
Last Flake: https://github.com/metabase/metabase/actions/runs/9407750048
Last Flake Time: 2024-06-06T14:38:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 7
Flakes in the last 7d: 7

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9474194065
Last Flake Time: 2024-06-12T14:53:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 9
Flakes in the last 7d: 26

**Comment by nemanjaglumac** [comment]
50/50 ✅ on `master`
https://github.com/metabase/metabase/actions/runs/10164813914
