### ISSUE TITLE
Dashboard does not load for no apparent reason

### ISSUE THREAD

**Issue by soobrosa** [metabase/metabase#4387]
Case simplified: have admin user group and an other user group who have access to the same schemas, but is not admin.

Built dozens of dashboards, they work fine.

Adding a new dashboard the other user group can access the new dashboard, the top of the page loads, but nothing else. Checking dev tools it looks like the loading has actually stopped. The load icon animates.  All previously made dashboards load properly.

What could make one and only one specific dashboard not to load?

I know it's pretty vague, but we couldn't really nail it down. When user from other user group have been moved to the admin group the dash loaded for them.

Any ideas how to resolve this maybe? Would be happy to provide any details you might found useful.

- Your browser and the version: Safari 10.0.2., Chrome 56.0.2924.87
- Your operating system: macOS Sierra 10.12.2
- Your databases: AWS Redshift
- Metabase version: 0.22.1
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: RDS Postgres

**Comment by salsakran** [comment]
can you see if there are any JS console logs or server logs when the user tries to load the dashboard?

**Comment by soobrosa** [comment]
@salsakran my facepalm that I didn't checked the console before, so it seems that cards drop 403 Forbidden why loading -- but user has access to the same resources, so I don't know where could I give more rights :)

**Comment by salsakran** [comment]
@soobrosa can you share the console test + the server logs? Also, how are the groups defined? 

Can you reproduce this error using the sample dataset? (if so, that would really help us find the root cause)

**Comment by soobrosa** [comment]
@salsakran console just drops a 403, see attached server logs.
[metabase_server_logs.txt](https://github.com/metabase/metabase/files/806882/metabase_server_logs.txt)

Funny thing is that user can access schema and tables, SQL inside card runs properly manually, but user can't access the _card_ itself ('Sorry, you don’t have permission to see that.'). I cannot set anything that would give explicit access to the card.

I also figured in the meantime that giving SQL write rights to a schema overrides granular table access related to schema. Is this an expected behaviour?

**Comment by collegeimprovements** [comment]
We are getting the exact issue.

**Comment by flamber** [comment]
There has been many fixes in the past three years. I'm fairly sure this permission problem has been fixed and tests were added too. I cannot reproduce on 0.35.1
If you're still seeing this problem, then please post version info and steps-to-reproduce.
