### ISSUE TITLE
[Flaky Test]: lifecycle-test

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43875]
Last Flake: https://github.com/metabase/metabase/actions/runs/9384253083
Last Flake Time: 2024-06-05T06:48:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by qnkhuat** [comment]
Fixed by https://github.com/metabase/metabase/pull/43924
