### ISSUE TITLE
Documentation link on website returning "404" page

### ISSUE THREAD

**Issue by kenny-evitt** [metabase/metabase#4390]

**Comment by kdoh** [comment]
Hey @kenny-evitt. Thanks for reporting this. Mind adding a bit more context around which link is broken?

**Comment by anki-code** [comment]
@kdoh he tells about this link:
![image](https://cloud.githubusercontent.com/assets/1708680/22996357/93f986e4-f3df-11e6-8074-4cbed5d1d74a.png)

![image](https://cloud.githubusercontent.com/assets/1708680/22996375/9e83e29e-f3df-11e6-859b-bffef40b852b.png)

**Comment by salsakran** [comment]
This should be "fixed" now. Github pages is not substituting jeykll variables on the redirect page for some reason. I'll be trying to figure out if it's a transient issue or something bigger. It might be affecting other places we substitute the version number in.

**Comment by kenny-evitt** [comment]
@salsakran Where are the GitHub Pages files? Are the docs on the website the same as in the app?

**Comment by fredrikekelund** [comment]
I'm still seeing this :(

**Comment by mazameli** [comment]
It seems to me that the header link is fixed and the button link towards the bottom of the page is fixed, but not the one in the footer:

![screen shot 2017-02-22 at 9 51 55 am](https://cloud.githubusercontent.com/assets/2223916/23224798/95a2e06c-f8e4-11e6-9682-37cde8416200.png)

**Comment by salsakran** [comment]
ok, tracked this down to a change in the jekyll redirect-from gem. Site variables are no longer properly treated in redirect urls. Fixed this in the docs repo. All of this should be good now.
