### ISSUE TITLE
Specifying Foreign Key for Table's Primary Key Field?

### ISSUE THREAD

**Issue by orware** [metabase/metabase#4391]
### Bugs

I'm not sure if this is an actual bug or not but our database has a lot of tables (~8000) and Metabase has done its best to bring in the Foreign Key relationships.

However, in one of example my coworker brought up for a table, while it had several foreign key relationships defined, it's primary entity key is also related to other tables (e.g. this field was similar to a user ID so it would be nice to easily join it back to that main users table).

When creating a question using this table it didn't seem to make that connection by itself.

Our first thought would be to change the Primary Entity Key field to be a Foreign Key instead, but this is where a second hurdle was encountered because the dropdown that appeared wasn't really sorted in a logical way, nor could you search easily through the list, which meant a whole bunch of scrolling for us.

Basically my coworker was asking me whether it would be possible for us to grant access to a few tables to our researchers for example, and since Metabase would know how the tables interrelated, the researchers would have no issues creating their own queries that may relate to multiple tables.

There may be some features already in the works to remedy some of this but figured it was worth sharing.

Also, I hope you guys are able to improve the Data Model area's performance since trying to go into it to search for things to update here on our end is pretty slow with this database in particular due to the large number of tables. 

I think I mentioned this in another issue as well, but having the ability to search by table name directly would be pretty helpful (we are very much used to not referring to our schemas when querying our Oracle database, so having that extra layer in between us and our tables slows us down because technically we have to go use our desktop SQL Developer program, run a query to find out what schema that table we want to use belongs to, and then come back to Metabase and find it within that schema).

**Comment by salsakran** [comment]
Hey @orware , can you please try to keep each issue related to an individual matter? We currently have 700+ and having a single issues that reference multiple matters makes it extremely difficult to stay on top of things. Eg, this has 3 separate things (the FK matter, performance and table search).

**Comment by orware** [comment]
@salsakran No worries, I probably won't be submitting any additional issues in the immediate future. Mainly I just wanted to share my observations/issues that I had run into during the period where I was more intensively trying things out so as not to miss something and any related items in an issue I may have mentioned I probably did so because they came up around that same time period. For future ones I'll try and break it up more individually, but like I said I'm probably not going to be posting many more at this time so it's a bit of a moot point from my end right now.

**Comment by flamber** [comment]
Closing in favor of #1177
