### ISSUE TITLE
[Flaky Test]: tag dimension should default to string/contains for a new high cardinality string field filter

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43938]
Last Flake: https://github.com/metabase/metabase/actions/runs/9421622574
Last Flake Time: 2024-06-07T12:00:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by iethree** [comment]
still flaking a lot: https://github.com/metabase/metabase/actions/runs/9957930568/job/27511091587?pr=45643#step:6:1124

**Comment by iethree** [comment]
flake on master: https://github.com/metabase/metabase/actions/runs/9963360395/job/27530375483#step:5:1128

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9965162542
Last Flake Time: 2024-07-16T15:47:00-07:00
Flakes in the last day: 2
Flakes in the last 3d: 9
Flakes in the last 7d: 17

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9965162542
Last Flake Time: 2024-07-16T15:47:00-07:00
Flakes in the last day: 2
Flakes in the last 3d: 9
Flakes in the last 7d: 17

**Comment by nemanjaglumac** [comment]
Fixed by https://github.com/metabase/metabase/pull/45978.
