### ISSUE TITLE
[Flaky Test]: tag dimension should default to number/= for a new numeric field filter

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43937]
Last Flake: https://github.com/metabase/metabase/actions/runs/9422395340
Last Flake Time: 2024-06-07T13:16:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9498293569
Last Flake Time: 2024-06-13T04:08:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 2
Flakes in the last 7d: 5

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9569015651
Last Flake Time: 2024-06-18T10:15:00-07:00
Flakes in the last day: 2
Flakes in the last 3d: 3
Flakes in the last 7d: 6

**Comment by nemanjaglumac** [comment]
Fixed by https://github.com/metabase/metabase/pull/45978
