### ISSUE TITLE
[Flaky Test]: should prevent saving new and updating existing models without result_metadata (metabase#37009)

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#43934]
Last Flake: https://github.com/metabase/metabase/actions/runs/9426004442
Last Flake Time: 2024-06-09T22:21:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 5
Flakes in the last 7d: 5

**Comment by nemanjaglumac** [comment]
Fixed by #46038
