### ISSUE TITLE
Pin Maps with more than 1000 results (LeafletTilePinMap) not working with native queries

### ISSUE THREAD

**Issue by pdiniz13** [metabase/metabase#4394]
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome and firefox
- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
MySQL
- Metabase version: (e.x. 0.19.3)
0.22.2
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Azure/"DC/OS"/Marathon/Docker
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Postgres
- *Repeatable steps to reproduce the issue*
Generate a pin map from a custom query with long lat. If the query has 999 of fewer results it displays fine, otherwise it crashes.
The error on the client is 
`https://our-domain.com/api/tiles/8/46/94/undefined/undefined/2/3/?query…ourquery Failed to load resource: the server responded with a status of 404 (Not Found)`
and the server logs
`02-15 17:23:38 [1mDEBUG metabase.middleware[0m :: [31mGET /api/tiles/8/47/93/undefined/undefined/2/3/ 404 (80 µs) (0 DB calls)[0m
"GET /api/tiles/8/47/93/undefined/undefined/2/3/ does not exist."`

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment]
@metabase/core-developers this is likely true for public links/embeds as well.

**Comment by camsaul** [comment]
Is there any way it wouldn't be true of those? (I.e. Don't they all use the same code?)

**Comment by pdiniz13** [comment]
Another note, if you use the visual question builder there doesn't seem to be a limit on the number of results displayed on the map that only happens for the custom sql queries.

**Comment by tlrobinson** [comment]
@camsaul I mean for GUI queries in public links / embedding, since the > 1,000 row pin maps use server-rendered tiles and we don't have endpoints that support public UUIDs/JWT tokens.

**Comment by delfer** [comment]
The same with "Grouped by" values. Checked it in Docker on embedded Demo DB.
![image](https://cloud.githubusercontent.com/assets/3233181/26396982/7b8ea270-407d-11e7-856b-cc62e12b710d.png)
Without filter it shows nothing on the map.

**Comment by JohanSJA** [comment]
Encountering the same issue. Pin doesn't show when result is equal or more than 1000. It works fine when the rows count is 999 or less.

**Comment by 5an1ty** [comment]
Same issue for me, limiting to 999 pins just works, I think for huge datasets like that we need heatmaps as well.

**Comment by anthonylau** [comment]
Same issue for me on version 0.26.2

**Comment by luqmansyauqi** [comment]
same issue for me (limiting to 999 pins works fine), but is there a hacky way to allow more than 999 pins in the source code/ config itself?

**Comment by keskmc** [comment]
Same issue

**Comment by danwolch** [comment]
It would be nice if the value was 1,000 or less. For the GUI built queries, you can limit the rows to 100 or 1000, nothing in between. Have to switch to a custom SQL query to specify a row limit of 999 rows.

**Comment by ceyhunkerti** [comment]
Also seems to be freezing even for 500 records

**Comment by RobertLowe** [comment]
Still an issue.

OT: Is there an open issue for row limit as a customizable number (besides using SQL)

**Comment by flamber** [comment]
@RobertLowe There's a request for custom row limit in #4544 - go and upvote by clicking :+1:

**Comment by orware** [comment]
I'm experiencing this same issue as well with a custom SQL query. It would be nice to make it so that this doesn't rely on a configuration setting and could "just work". It might be cool to have it automatically cluster things into bigger dots and then as a user zooms into the map things could be broken down into more discrete chunks (as an example, I have some address info and a whole lot of addresses and it would be nice to see things grouped by the City/ZIP and then Street Levels and then get down into the individual addresses as I zoom in. Right now since there are a lot of rows it just hits that 1000 record limit and doesn't display anything, so I tried a City/ZIP grouping and for Street Levels I made a separate question and have it limited only to Streets with Greater Than a certain number of people on them in order to get some results.

**Comment by rburhum** [comment]
Not trying to hijack the conversation, but I am a bit stuck with this 1000 record limit.

I have system that can generate vector tiles that can be rendered in leaflet from SQL queries. Is there any way I can embed an iframe on a dashboard and render the tiles myself?

**Comment by flamber** [comment]
@rburhum You can change the tile server in Admin > Settings > Maps. Not sure if that's a fix for you otherwise please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by rburhum** [comment]
Those are options for *basemaps*. I was talking about generating vector tiles for the *results* instead of using javascript markers which presumably is the reason why you have 1000 records as limit since more than ~5000 pins will create a problem unless you switch to server rendered tiles.

I will ask at the discourse site though. Thanks!

**Comment by diegoalefe** [comment]
Guys it still a issue, theres a fix?

**Comment by rburhum** [comment]
still an issue :)

**Comment by diegoalefe** [comment]
> still an issue :)

:P

**Comment by flamber** [comment]
Please refrain from spamming. We look at upvotes of the first post of an issue as one of the indicators to prioritize issues. There's 2000+ other issues. Metabase is a fairly small development team. If you want to help, then please submit a PR - it is an open source project after all :wink:

**Comment by Loccolito** [comment]
Guys, there's a fix? 🙏

**Comment by TurkerTunali** [comment]
I have a 41 row limit with Pin Map on v0.36.7 when using visual query builder.

**Comment by flamber** [comment]
@TurkerTunali Then it's not this issue. Open a new issue with steps to reproduce with Sample Dataset or please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by paoliniluis** [comment]
Related to https://github.com/metabase/metabase/issues/9420 as well

**Comment by richxrich** [comment]
Upvoted, please conisder removing the limit

**Comment by ranquild** [comment]
I've investigated the issue and it seems to be easy to fix. The underlying problem is that the BE accepts field `id` for latitude and longitude fields, and uses them like this:
```
(defn- query-with-inside-filter
  "Add an `INSIDE` filter to the given query to restrict results to a bounding box"
  [details lat-field-id lon-field-id x y zoom]
  (let [top-left      (x+y+zoom->lat-lon      x       y  zoom)
        bottom-right  (x+y+zoom->lat-lon (inc x) (inc y) zoom)
        inside-filter [:inside
                       [:field lat-field-id nil]
                       [:field lon-field-id nil]
                       (top-left :lat)
                       (top-left :lon)
                       (bottom-right :lat)
                       (bottom-right :lon)]]
    (update details :filter mbql.u/combine-filter-clauses inside-filter)))
```

The important part is:
```
[:field lat-field-id nil]
```

For SQL questions, there is no field id, but there is a string name and a type. **The fix would be to accept `field_ref`s for latitude and longitude fields.** `(api/defendpoint GET "/:zoom/:x/:y/:lat-col/:lon-col/:lat-col-idx/:lon-col-idx/"` should be changed by the BE first.

**Comment by fermuch** [comment]
Hello! Sorry to revive this thread, but it happened to me on 0.42.4. Is it supposed to be fixed?

**Comment by freQniK** [comment]
I can confirm that there is still a limit of 999 pins for a map. I have to put a row limit of 999 on my pings from my application to see a global userbase, so unfortunately I'm not getting the entire data set on the pin map.

**Comment by jamesladyman-cognitant** [comment]
I'm getting this issue also, exactly on the 999-1000 split (also implemented using a limit) the pins turn into unclickable squares and then somewhere beyond 1,000 the query completely fails to complete.

**Comment by jamesladyman-cognitant** [comment]
> I'm getting this issue also, exactly on the 999-1000 split (also implemented using a limit) the pins turn into unclickable squares and then somewhere beyond 1,000 the query completely fails to complete.

Actually using a larger value or setting no limit appears to actually cause the entire metabase application to freeze up, giving me a 502 and 503 errors when attempting to load other pages. That's a far larger issue than just limiting the map data and I guess indicates that there's some big performance issue when adding the pins?

**Comment by jamesladyman-cognitant** [comment]
The freezing issue turned out to be caused, I think, by having an sql comment line `--limit 10000` at the end of the query and that causing a syntax error when metabase wraps it with some other stuff. Not sure why that would happen since I do that elsewhere in queries just fine.

The square/pin thing is evidently intended behaviour so no worries there.

Seems like the query just takes forever to actually put down the pins if they go past 1000, but I've realised from the logs that metabase's 2000 row limit is still going to apply so the metabase pin map isn't really suitable for my use case anyway.

**Comment by vinceve** [comment]
@jamesladyman-cognitant What did you end up using? For us, this is really inconvenient. We are looking at the binning option to make it more compact, but that isn't feasible in our case (we represent really detailed locations)

**Comment by MusharrafSakran** [comment]
We are still facing this issue with metabse v0.50.20. the annoying limit of 999 is persistant whatsoever. Hope it get's fixed soon :(

**Comment by freQniK** [comment]
> The freezing issue turned out to be caused, I think, by having an sql comment line `--limit 10000` at the end of the query and that causing a syntax error when metabase wraps it with some other stuff. Not sure why that would happen since I do that elsewhere in queries just fine.
> 
> The square/pin thing is evidently intended behaviour so no worries there.
> 
> Seems like the query just takes forever to actually put down the pins if they go past 1000, but I've realised from the logs that metabase's 2000 row limit is still going to apply so the metabase pin map isn't really suitable for my use case anyway.

As for the 2000 row limit in metabase, there is a solution to that. Add the following parameters to your `/etc/default/metabase` 

```
MB_UNAGGREGATED_QUERY_ROW_LIMIT=50000
MB_AGGREGATED_QUERY_ROW_LIMIT=50001
```

Adjusting the numbers to your desired row limit

**Comment by freQniK** [comment]
Yes, this is still an issue. 999 pins only!

**Comment by TurkerTunali** [comment]
> Yes, this is still an issue. 999 pins only!

Which version did you test it?

**Comment by freQniK** [comment]
> > Yes, this is still an issue. 999 pins only!
> 
> Which version did you test it?

0.48.8

**Comment by jalinvi** [comment]
Having same issue with the 999 limit. I can't understand this hasn't been solved yet after so many years

**Comment by ouraios** [comment]
I think the incriminated line code is this one: 

https://github.com/metabase/metabase/blob/c0a3f19b8721cf46dabb24ff916a391b3d754124/frontend/src/metabase/visualizations/visualizations/Map/Map.jsx#L156

I dont know why there's this arbitrary limit ...

**Comment by HansBambel** [comment]
It's still an issue in 0.55.4

**Comment by dragonsahead** [comment]
@HansBambel please create a new issue if this is the case

**Comment by HansBambel** [comment]
@paoliniluis, I found this issue that is basically the same: https://github.com/metabase/metabase/issues/40999
