### ISSUE TITLE
Hotkey for run query on Windows

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4395]
It will be cool to be able to run query by hotkey. It makes work a bit faster.

My favorite hotkeys for run query (in SQL Workbench/J) on Windows keyboard:
* `Ctrl + Enter` (for run query)
* `Ctrl + E` (for run selected part of query)

**Comment by tlrobinson** [comment]
We have command-enter (or whatever your OS's "meta" key is) #3634

**Comment by anki-code** [comment]
I have windows keyboard. I've tried `Ctrl + Enter`, `Fn + Enter` but I've got no result.

**Comment by anki-code** [comment]
I have windows keyboard. I've tried `Ctrl + Enter`, `Fn + Enter` but I've got no result.

**Comment by anki-code** [comment]
@tlrobinson this is works perfect for me:

```
function doc_keyUp(e) {
    if (e.ctrlKey && e.keyCode == 13) {
		alert('Ctrl + Enter!');
    }
}
document.addEventListener('keyup', doc_keyUp, false);
```

**Comment by anki-code** [comment]
For run selected part of query: `Ctrl + Alt + Enter`:
```
function doc_keyUp(e) {
    if (e.ctrlKey && e.altKey && e.keyCode == 13) {
		alert('Ctrl + Alt + Enter!');
    }
}
document.addEventListener('keyup', doc_keyUp, false);
```

**Comment by camsaul** [comment]
When we made Super-Return/Command-Enter run queries we did talk about what to do for windows users #3634

@anki-code since Super is the Windows key in Windows that means Windows+Enter should run the query. That should work unless Windows intercepts the keystroke... Does that work?

**Comment by camsaul** [comment]
I think I suggested the same thing in #3634, enabling Ctrl+Enter as well since it's a more natural combo for Linux and Windows users. Maybe we should revisit that idea? Not everyone has a super key on their keyboards

**Comment by anki-code** [comment]
@camsaul 
>  Windows+Enter should run the query. 

`Win + Enter` isn't working.

**Comment by tlrobinson** [comment]
Alright, I said we'd keep it as-is until a Windows complained, and a Windows user has officially complained :)

Supporting cmd+enter and ctrl+enter seems fine to me.

ctrl+alt+enter to run the selection seems interesting, not sure how easy that will be but I'll take a look.
