### ISSUE TITLE
SQL Server database table not showing up

### ISSUE THREAD

**Issue by kenny-evitt** [metabase/metabase#4396]
I'm running a local instance of Metabase v0.22.2, via the JAR, and connecting to a SQL Server 2012 (Express) instance.

When I create a new question, I can see almost all of the tables in my database. The only that I know is missing is the one named *dbo.BATCH*. I'm assuming it's missing because 'batch' is considered reserved or otherwise an invalid table name.

**Comment by kenny-evitt** [comment]
The JAR 'info' output indicates that the table was synced:

```
02-16 05:50:02 [1mINFO sync-database.introspect[0m :: [35m[*******╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖╖] ?   15% Synced table 'dbo.BATCH'.[0m
```

**Comment by kenny-evitt** [comment]
The table is also not listed in the admin 'Data Model' info for the database.

**Comment by camsaul** [comment]
That's strange, I don't know any reason why it shouldn't work. How did you create a table with an invalid table name?

**Comment by camsaul** [comment]
@kenny-evitt ?

**Comment by kenny-evitt** [comment]
@camsaul "batch" isn't a reserved keyword in SQL Server, or in ANSI SQL either. Nor does it seem be reserved for PostgreSQL or MySQL either. Is it definitely invalid in some other database system?

**Comment by kenny-evitt** [comment]
@camsaul Note that I was assuming that Metabase considers "batch" to be an invalid name; I definitely don't know that and the only evidence I have that it might be true is that the table with that name isn't visible in my Metabase instance.

**Comment by camsaul** [comment]
@kenny-evitt when you said 

> I'm assuming it's missing because 'batch' is considered reserved or otherwise an invalid table name.

I took it to mean that SQL Server considered it to be reserved. Sorry for the confusion. Metabase doesn't have any sorts of reserved keywords for table names so there's probably some other reason it's not showing up in the list. Is this a table that you've dropped and recreated at any point?

**Comment by camsaul** [comment]
@kenny-evitt I opened PR #5491 (branch `allow-additional-options-for-sqlserver`) which switches the JDBC driver we use under the hood from jTDS to the official Microsoft one. It seems to fix several issues with SQL Server and I have a feeling it might fix this one as well. Is there a chance you could try that branch out and see if it fixes this issue for you?

**Comment by camsaul** [comment]
@kenny-evitt awesome, thanks!

**Comment by camsaul** [comment]
@kenny-evitt we ended up merging the SQL Server JDBC driver swap and shipped it as part of 0.26.0. Are you still seeing this issue on the latest version of Metabase?

**Comment by kenny-evitt** [comment]
@camsaul I tried this out somewhat recently but I could never get it working. I tried every combination for every name that could be domain-qualified.

I tried again just now, running the 0.26.0.RC1 version and it seems to be much more of a reasonable failure!

Here's what I've entered for the connection in Metabase:

 - Host – just the regular host name of the SQL Server server
 - Port – blank (so the default of 1433 should be used)
 - Database name – the name of the database I want to use
 - Database instance name – blank (so the default SQL Server instance should be used)
 - Windows domain – the short form of my Windows domain
 - Database username – my Windows user (short) name
 - Database password – blank

The output I see in the console (from which I ran the Metabase JAR):

```
11-06 11:06:25 [1mERROR metabase.driver[0m :: Failed to connect to database: com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:3f027635-2604-463d-9c3c-fa70af22ca1e
11-06 11:06:25 [1mDEBUG metabase.middleware[0m :: [31mPOST /api/setup/validate 400 (69 ms) (0 DB calls)[0m
{:message
 "com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: \"sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\". ClientConnectionId:3f027635-2604-463d-9c3c-fa70af22ca1e"}

11-06 11:06:25 [1mERROR metabase.driver[0m :: Failed to connect to database: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'DOMAIN\kenny'. ClientConnectionId:253c25f9-bd96-4909-9bb4-e1c8fc5d0eb4
11-06 11:06:25 [1mDEBUG metabase.middleware[0m :: [31mPOST /api/setup/validate 400 (37 ms) (0 DB calls)[0m
{:message "com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'DOMAIN\\kenny'. ClientConnectionId:253c25f9-bd96-4909-9bb4-e1c8fc5d0eb4"}
```

I'm going to check that I've got everything setup for TLS/SSL connections to SQL Server otherwise. I'll try adding the data connection in Metabase again after that.

I ran the Metabase JAR file from a PowerShell window just now. Previously I was running it from a Windows Command Prompt window. Maybe this change helped.

**Comment by kenny-evitt** [comment]
I added `trustServerCertificate=true` to the _Additional JDBC connection string options_ setting, and that seems to have resolved the SSL certificate error. But I still got the `Login failed ...` error message logged in the console. I even tried entering my password in _Database password_, but to no avail.

**Comment by jornh** [comment]
@kenny-evitt with the Microsoft driver and a domain user see #6056

**Comment by kenny-evitt** [comment]
@jornh @camsaul Installing and setting-up Kerberos is too much for me (at the moment). But I *was* able to test this specific issue again.

And it seems like this has been fixed (or resolved). When I look at the schema that contains the table I can find the table, but it's listed at the very bottom of the batch under a "HIDDEN TABLE" section. But it's there!
