### ISSUE TITLE
We're maxing out fields at 255 characters in several places in the UI while our DB supports infinite text

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#43983]
### Describe the bug

There are some sections where we're maxing out the text fields to 255 chars:
![image](https://github.com/metabase/metabase/assets/1711649/62d26ede-70c1-4497-b08c-1806bb0f5fe4)

The problem is that for many of those fields, the DB allows more/infinite characters

### To Reproduce

1) e.g. create a dashboard and use a long text
![image](https://github.com/metabase/metabase/assets/1711649/9ce3e7cb-579d-4d8e-bc49-62f23c6029a7)

2) see the limitation

3) check the DB, we're using text fields which are infinite in lenght

### Expected behavior

We should allow more text, even more if we're going to allow AI descriptions

### Logs

NA

### Information about your Metabase installation

```JSON
-v50, but this comes from before
```

### Severity

P2

### Additional context

NA

**Comment by perivamsi** [comment]
Bug or feature request?

**Comment by paoliniluis** [comment]
A customer we have is hitting this as a bug, that’s why I tagged it as such

**Comment by perivamsi** [comment]
My suggestion is to remove this restriction on [dashboard creation](https://github.com/metabase/metabase/blob/35f97092e09109b998e3f5b4678d06123bbd9793/frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx#L28) and [dashboard copying](https://github.com/metabase/metabase/blob/35f97092e09109b998e3f5b4678d06123bbd9793/frontend/src/metabase/dashboard/containers/CopyDashboardForm.tsx#L32).

**Comment by cdeweyx** [comment]
[Thread](https://metaboat.slack.com/archives/C064QMXEV9N/p1718628995208319)
