### ISSUE TITLE
Wrong error about limit in Area chart after query editing

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4399]
Metabase 0.22.1

![image](https://cloud.githubusercontent.com/assets/1708680/23067831/0d3eff72-f532-11e6-81c3-795de0feee14.png)

Query:
```
select 1 dt, 'a' ct, 1 m union all
select 2, 'b', 1 union all
select 3, 'c', 1 union all
select 4, 'd', 1 union all
select 5, 'e', 1 union all
select 6, 'f', 1 union all
select 7, 'g', 1 union all
select 8, 'h', 1 union all
select 9, 'i', 1 union all
select 10, 'j', 1 union all
select 11, 'k', 1 union all
select 12, 'l', 1 union all
select 13, 'm', 1 union all
select 14, 'n', 1 union all
select 15, 'o', 1 union all
select 16, 'p', 1 union all
select 17, 'r', 1 union all
select 18, 's', 1 union all
select 19, 't', 1 union all
select 20, 'o', 1 union all
select 21, 'v', 1 union all
select 22, 'p', 1 union all
select 23, 'x', 1 union all
select 24, 'y', 1 union all
select 25, 'z', 1 
```

For fix this I click "New question" and execute the query again. 

Sometimes I faced with other situations when error after the query execution is affected on future execution of changed query. In this case I click "New question" and try from clear state for escape a karma :) I'll tell you when it will repeat.

**Comment by tlrobinson** [comment]
I believe this was fixed incidentally in the `public-embedding` branch.

**Comment by salsakran** [comment]
@anki-code can you confirm it was fixed in that branch?

**Comment by anki-code** [comment]
Sorry I can't test it now. Please try to use test case in the first message.

**Comment by anki-code** [comment]
@camsaul what do you want to tell me by setting this emoji? Sorry but I really can't checkout and test this branch till Monday.

**Comment by anki-code** [comment]
> @anki-code can you confirm it was fixed in that branch?

Yes. I've built `public-embedding` branch and this issue was fixed.

**Comment by anki-code** [comment]
Fixed! Thank you!
