### ISSUE TITLE
SQL "Unknown column" errors on 0.50.0 with breakouts on nested models

### ISSUE THREAD

**Issue by Jianbin719** [metabase/metabase#43993]
### Describe the bug

After updating to V0.50.0 the errors comes, some of fields turns to unkonw

### To Reproduce

After updating to V0.50.0 

### Information about your Metabase installation

```JSON
Any information?
```

### Severity

 blocking usage of Metabase entirely

**Comment by paoliniluis** [comment]
Screenshot?

**Comment by ranquild** [comment]
@Jianbin719 could you provide some additional information? You get this issue in dashboards with parameters, right? Does it happen with saved questions or models? Anything special about them?

**Comment by Jianbin719** [comment]
I have one model X which consists of two table A and B. Then I created one more question Y to filter model X. 

The error exists in Pivot Table display, when trying to Summarize by field in Table B. 

I do not have any problem in [v0.49.15]. the problem with version 0.50.0 only.

**Comment by Jianbin719** [comment]
![image](https://github.com/metabase/metabase/assets/75652286/f7870e29-2c64-424c-82e2-7ee8690f3505)

**Comment by paoliniluis** [comment]
@Jianbin719 I don't see where the field turns to unknown

**Comment by Jianbin719** [comment]
> ![image](https://github.com/metabase/metabase/assets/75652286/f7870e29-2c64-424c-82e2-7ee8690f3505)
> 

@paoliniluis The company field turns into unknown. 

Where I can show you the log or detailed information

![Screenshot_20240612_001555.jpg](https://github.com/metabase/metabase/assets/75652286/87f0c1fd-d4f3-4bb5-8ae5-e76f83fe1336)

**Comment by paoliniluis** [comment]
ok, please open the browser console and send us what you see. It's a FE error that crashes the query builder

**Comment by Jianbin719** [comment]
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
[login](http://192.168.11.18/auth/login?redirect=%2Fquestion%2F117%2Fnotebook)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value\n {:lib/type :mbql/query,\n  :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n  :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value\n  {:lib/type :mbql/query,\n   :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n   :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value\n {:lib/type :mbql/query,\n  :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n  :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value\n  {:lib/type :mbql/query,\n   :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n   :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value\n {:lib/type :mbql/query,\n  :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n  :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value\n  {:lib/type :mbql/query,\n   :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n   :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “style-src 'self' 'nonce-hkGpf76bw8' https://accounts.google.com/” [emotion-sheet.browser.esm.js:74:22](webpack:///node_modules/@emotion/sheet/dist/emotion-sheet.browser.esm.js)
Error getting setting pivot_table.column_split TypeError: e is undefined
    t settings.ts:122
    t settings.ts:122
    eG Underscore
    getValue settings.ts:121
    e settings.js:86
    e settings.js:69
    ee settings.js:42
    f visualization.js:97
    eV selectors.js:737
    Redux 10
    et9 QueryBuilder.jsx:118
    Redux 7
    aJ React
    Redux 5
    aJ React
    Redux 5
    aJ React
    Redux 5
    aJ React
    Redux 5
    aJ React
    Redux 5
    aJ React
    Redux 5
    aJ React
    Redux 5
    aJ React
    Redux 9
    em querying.js:211
    Redux 2
    eo querying.js:139
[settings.js:109:12](webpack:///visualizations/lib/settings.js)
Error getting setting pivot_table.column_split TypeError: e is undefined
    t settings.ts:122
    t settings.ts:122
    eG Underscore
    getValue settings.ts:121
    e settings.js:86
    e settings.js:69
    ee settings.js:42
    f visualization.js:97
    eV selectors.js:737
    Redux 10
    et9 QueryBuilder.jsx:118
    Redux 4
    u use-sync-external-store-shim.production.min.js:10
    c Redux
    React 9
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 10
[settings.js:109:12](webpack:///visualizations/lib/settings.js)
Error getting setting pivot_table.column_split TypeError: e is undefined
    t settings.ts:122
    t settings.ts:122
    eG Underscore
    getValue settings.ts:121
    e settings.js:86
    e settings.js:69
    ee settings.js:42
    f visualization.js:97
    g visualization.js:116
    _getWidgets ChartSettings.jsx:167
    render ChartSettings.jsx:285
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
[settings.js:109:12](webpack:///visualizations/lib/settings.js)

​

**Comment by Jianbin719** [comment]
![image](https://github.com/metabase/metabase/assets/75652286/c75890b4-f9b8-4afb-89f8-fd812d527b2c)

**Comment by bshepherdson** [comment]
I tried to reproduce this with an MBQL model on the Sample Database: Orders joined to People, Sum of SUBTOTAL by People.NAME. It works in a regular table view and chart view, but if I try to pivot it fails on the server side with a similar error:

```sql
-- 2024-06-12 15:07:20,488 ERROR middleware.catch-exceptions :: Error processing query: Column "source.NAME" not found; SQL statement:                                                                                                                         
SELECT
  "source"."NAME" AS "People - User__NAME",
  "source"."pivot-grouping" AS "pivot-grouping",
  SUM("source"."SUBTOTAL") AS "sum"
FROM (
  SELECT
    "source"."SUBTOTAL" AS "SUBTOTAL",
    ABS(0) AS "pivot-grouping"
  FROM (
    SELECT
      "PUBLIC"."ORDERS"."ID" AS "ID",
      "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID",
      "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID",
      "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL",
      "PUBLIC"."ORDERS"."TAX" AS "TAX",
      "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL",
      "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT",
      "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT",
      "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY",
      "People - User"."ID" AS "People - User__ID",
      "People - User"."ADDRESS" AS "People - User__ADDRESS",
      "People - User"."EMAIL" AS "People - User__EMAIL",
      "People - User"."PASSWORD" AS "People - User__PASSWORD",
      "People - User"."NAME" AS "People - User__NAME",
      "People - User"."CITY" AS "People - User__CITY",
      "People - User"."LONGITUDE" AS "People - User__LONGITUDE",
      "People - User"."STATE" AS "People - User__STATE", 
      "People - User"."SOURCE" AS "People - User__SOURCE",
      "People - User"."BIRTH_DATE" AS "People - User__BIRTH_DATE",
      "People - User"."ZIP" AS "People - User__ZIP",
      "People - User"."LATITUDE" AS "People - User__LATITUDE",
      "People - User"."CREATED_AT" AS "People - User__CREATED_AT"
    FROM "PUBLIC"."ORDERS"
    LEFT JOIN "PUBLIC"."PEOPLE" AS "People - User" ON "PUBLIC"."ORDERS"."USER_ID" = "People - User"."ID"
  ) AS "source"
) AS "source"
GROUP BY "source"."NAME", "source"."pivot-grouping"
ORDER BY "source"."NAME" ASC, "source"."pivot-grouping" ASC;
```

The first inner query selects only `source.SUBTOTAL` and `pivot-grouping`, and not `NAME`, so it's not available for the outer source. I think this is an issue with pivoting on models. I'll try the similar query without the extra layer introduced by models.

**Comment by bshepherdson** [comment]
Ah, it's actually an issue with nesting and pivot tables.

This query is a bit contrived, to get multiple stages on a simple dataset, but it does repro the issue.

This one-stage works fine:
![2024-06-12-112816_1894x1122_scrot](https://github.com/metabase/metabase/assets/157812/768dd5a1-3cd6-4874-a0bb-13c28e8600a1)

But this is broken with the same kind of error:
![2024-06-12-113218_1953x1317_scrot](https://github.com/metabase/metabase/assets/157812/7c40778c-82e6-4faa-bfee-1450921aab90)

**Comment by bshepherdson** [comment]
I'm debugging into this issue.

**Comment by bshepherdson** [comment]
I've narrowed down this issue to how fields are tracked across stages when we introduce extra levels of nesting (eg. when there are expressions).

There's a subtle case that's not being properly handled. Should be fixed tomorrow.

For the record, this only appears on:
- nested queries
- with aggregations in the last stage
- either when pivoting or with expressions in non-first stages

**Comment by bshepherdson** [comment]
I'm actually failing to see the regression here. This fails in the same way on 49.16.

I'm trying 49.0 and the last 48.x now for comparison.

**Comment by bshepherdson** [comment]
Okay, I understand my confusion about the regression or not: this has been broken for single multi-stage queries for a long time, but it used to work for **models**. That's the part that broke in 0.50.0.

I've got a fix for this. I'll clean it up and get the PR posted today.

**Comment by Jianbin719** [comment]
Thanks for fixing the issue. 

But the problem again, when I used Custom Field in secondary nesting model or more for Pivot Table. 

![image](https://github.com/metabase/metabase/assets/75652286/b9143dc5-8303-4b19-a53a-1c8572254994)

QtyNoMotor is a Custom Field from secondary nesting model

**Comment by Jianbin719** [comment]
It is also fine in any 0.49

**Comment by paoliniluis** [comment]
@Jianbin719 you moved to 50.4 or 50.5?

**Comment by bshepherdson** [comment]
@Jianbin719 it's working for me on 50.5. Can you give more detail of the model, the query, and especially the error message you're getting?

I'm using this as the model definition:
![2024-06-17-165117_2522x1132_scrot](https://github.com/metabase/metabase/assets/157812/361a1fba-9253-4e63-a3b7-1ebdc1e43653)

and this as the query:
![2024-06-17-165038_2547x552_scrot](https://github.com/metabase/metabase/assets/157812/6523e7c1-0386-48fd-930f-8b0fd63267bc)

The best help you could give me for debugging this would be to try to reproduce this issue using the Sample Database. 

Second best would be to include the diagnostic information. Press Ctrl+F1 on the question that failed, and send the JSON file with at least these selections:
![2024-06-17-165523_1256x1086_scrot](https://github.com/metabase/metabase/assets/157812/044845da-1046-460c-ad5b-19449a430d16)
But do review the JSON file first - it might include sensitive things you don't want to post on the Github issue.

**Comment by Jianbin719** [comment]
[metabase-diagnostic-info-2024-06-18T01_10_57.280Z.json](https://github.com/user-attachments/files/15878972/metabase-diagnostic-info-2024-06-18T01_10_57.280Z.json)

@bshepherdson Thanks for your reply. I updated it to 0.50.5

**Comment by Jianbin719** [comment]
> [metabase-diagnostic-info-2024-06-18T01_10_57.280Z.json](https://github.com/user-attachments/files/15878972/metabase-diagnostic-info-2024-06-18T01_10_57.280Z.json)
> 
> @bshepherdson Thanks for your reply. I updated it to 0.50.5
> 

I updated to 0.50.5, but problem not solved

**Comment by bshepherdson** [comment]
Right! Sorry for the extra close-and-reopen there.

Thanks for the diagnostic info! Here's the SQL from one of the errors:

```sql
SELECT                                                                                                                        
  `source`.`Group Product - Series__ProductGroup` AS `Group Product - Series__ProductGroup`,                                  
  `source`.`pivot-grouping` AS `pivot-grouping`,                                                                              
  SUM(`source`.`QtyNoMotor`) AS `sum`,                                                                                        
  SUM(`source`.`subtotal_usd`) AS `sum_2`                                                                                     
FROM                                                                                                                          
  (                                                                                                                           
    SELECT                                                                                                                    
      `source`.`subtotal_usd` AS `subtotal_usd`,                                                                              
      `source`.`QtyNoMotor` AS `QtyNoMotor`,                                                                                  
      ABS(0) AS `pivot-grouping`                                                                                              
    FROM                                                                                                                      
      (                                                                                                                       
        select                                                                                                                
          *                                                                                                                   
        from                                                                                                                  
          `metabase_cache_00491_2`.`model_57_模型-鼎捷订单`                                                                   
      ) AS `source`                                                                                                           
  ) AS `source`                                                                                                               
GROUP BY                                                                                                                      
  `source`.`Group Product - Series__ProductGroup`,                                                                            
  `source`.`pivot-grouping`                                                                                                   
ORDER BY                                                                                                                      
  `source`.`Group Product - Series__ProductGroup` ASC,                                                                        
  `source`.`pivot-grouping` ASC 
  ```
  
which looks like this same issue. The ```source.`Group Product - Series__ProductGroup` ``` doesn't exist on the middle query.

The MBQL here is:

```clojure
  {:lib/type :mbql/query                                                                                                      
   :qp.pivot/breakout-combination [0]                                                                                         
   :stages [{:lib/type :mbql.stage/mbql                                                                                       
             :aggregation [[:sum {} [:field {:base-type :type/BigInteger} "QtyNoMotor"]]                                      
                           [:sum {} [:field {:base-type :type/Decimal} "subtotal_usd"]]]                                      
             :source-card 57                                                                                                  
             :breakout    [[:field {:base-type :type/Text} "ProductGroup"]                                                    
                           [:expression                                                                                       
                            {:base-type :type/Integer,                                                                        
                             :effective-type :type/Integer}                                                                   
                            "pivot-grouping"]]                                                                                
             :expressions [[:abs {:lib/expression-name "pivot-grouping"} 0]]}]                                                
   :middleware {:pivot-options                     {:pivot-rows nil, :pivot-cols nil}}                                        
   :database 2}
```

which looks plausible and valid. 

My current speculation is that the inner ```(SELECT * FROM `metabase_cache_00491_2`.`model_57_模型-鼎捷订单`)``` is the issue - if we don't know which fields are coming from that innermost query, the logic to nest the query might be broken.

I'm continuing to debug this.

**Comment by Jianbin719** [comment]
ProductGroup is the custom field for the relatwd model

**Comment by bshepherdson** [comment]
I can't reproduce this, even guided by the MBQL from your error messages, which I posted above.

It may be related to model caching, but it's hard to check that.

Can you post screenshots of the whole query editor for both the model's query and the query using the model? You can blur the field and table names if needed, but please keep the icons (it matters sometimes whether something is a table or a model).

**Comment by Jianbin719** [comment]
![image](https://github.com/metabase/metabase/assets/75652286/ceb9a26a-331b-464f-aedc-eb47426b6fba)

**Comment by Jianbin719** [comment]
![image](https://github.com/metabase/metabase/assets/75652286/c6edc9d4-7cec-43ea-b9b7-18ea873018ef)

**Comment by Jianbin719** [comment]
> ![image](https://github.com/metabase/metabase/assets/75652286/c6edc9d4-7cec-43ea-b9b7-18ea873018ef)
> 

Problem with this configuration in Pivot table.

**Comment by bshepherdson** [comment]
Thanks! Two nested models with the expression on the inner one was a combination I hadn't tried.

I'll try to reproduce this.

**Comment by bshepherdson** [comment]
This will be in 50.7.
