### ISSUE TITLE
Lib.expressionClauseForLegacyExpression throws when using a multi-value string/contains filter

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#43990]
Thread with info https://metaboat.slack.com/archives/C0645JP1W81/p1718109273559439

### Describe the bug

https://github.com/metabase/metabase/assets/6830683/fdcf4d3d-a6cb-4bd5-ad15-911ef701d1ee

### To Reproduce

1. Create a question Orders > Limit 5
2. Add it to a new dashboard
3. Add Text > Contains filter to the dashboard and connect it to Source field in the card
4. Save dashboard
5. Set 2 filter values: "aa" and "bb"
6. Click dashcard title

Nothing happens.
There's an error in JS console:
```
Uncaught (in promise) Error: No protocol method IAssociative.-assoc defined for type number: 14
```

### Expected behavior

No error in JS console.
You get navigated to question page.

### Information about your Metabase installation

master, 459429985c, v50+ (we didn't support multiple values in these filters before)

### Severity

P1/P2

**Comment by kamilmielnik** [comment]
This issue happens when computing URL for the dashcard title.
It has not been caught by tests because you need to click such link to get the error.

However #43816 adds link computation even before the click event happens, so this bug prevails there.
I had to add a temporary try/catch to work around it (see 08a5606ad6)

:warning: Please revert [that commit](https://github.com/metabase/metabase/commit/08a5606ad6752aa7b60c5f2e0bd5d287568a1ed8) when issue is fixed :warning:

**Comment by kamilmielnik** [comment]
There's a repro for it already, see: #43000
:warning:  When this issue is fixed please unskip it and update the issue id in the test name :warning:

**Comment by ranquild** [comment]
As discussed, for legacy mbql only we need to pass args differently on the FE.
