### ISSUE TITLE
0.50.0 line graph with multiple series all jumbled up

### ISSUE THREAD

**Issue by VD-arjenh** [metabase/metabase#43998]
### Describe the bug

Upgraded metabase to 0.50.0.

1. Under line area goes in a diagonal line from the X and Y origin to the first data point.

![image](https://github.com/metabase/metabase/assets/165997959/571d3446-0c28-4a5f-800a-bf3fc4640dbb)

### To Reproduce

1. Have a table with multiple series
2. Plot series as line charts
3. Enable area under (some of the) line series
4. Set line shape to stepped (<- important)

### Expected behavior

- The area under the line should climb vertically to meet the first datapoint

### Information about your Metabase installation

```JSON
- all browsers I could lay my hands on
- windows 11
- Postgres
- metabase 0.50.0
- jar file on debian
- Postgres
```

### Severity

blocking an upgrade

**Comment by alxnddr** [comment]
Related to https://github.com/apache/echarts/issues/20021
