### ISSUE TITLE
Development - components examples

### ISSUE THREAD

**Issue by mariusz-jachimowicz-83** [metabase/metabase#4403]
I am just thinking about separete place with example components. Similar to [Bootstrap](http://getbootstrap.com/components).

Value:

- quickly learn about components
- easier components development with isolation
- easier work for newbies

What do you think?

**Comment by kdoh** [comment]
@mariusz-jachimowicz-83 I think you're talking about something similar to #3582. We're definitely interested in doing that, just having a hard time making time for it. I'm going to go ahead and close this so we keep the conversation consolidated but if you have more ideas about how to go about it feel free to add them to that issue.
