### ISSUE TITLE
"Not able to modify the internal user" for example dashboard creator user

### ISSUE THREAD

**Issue by gouline** [metabase/metabase#44034]
### Describe the bug

I'm the author of [dbt-metabase](https://github.com/gouline/dbt-metabase) that allows users to export Metabase dashboards as dbt exposures. To populate the exposure owner, I use dashboard `creator` block whenever available or `creator_id` fetched via [`GET /api/user/:id`](https://www.metabase.com/docs/latest/api/user#get-apiuserid) otherwise.

Attempting to query the `creator_id` on example dashboards returns HTTP 400 "Not able to modify the internal user", even though I'm only reading, not modify it. [`GET /api/dashboard/:id`](https://www.metabase.com/docs/latest/api/dashboard#get-apidashboardid) also doesn't return the `creator` block like some others (e.g. [`GET /api/dashboard/`](https://www.metabase.com/docs/latest/api/dashboard#get-apidashboard)), so there's nowhere to get that name from.

### To Reproduce

1. Fresh install of Metabase 50
2. Query `GET /api/dashboard/:id` with any example dashboard ID (from `GET /api/dashboard`)
3. Find `creator_id` and query API `GET /user/:id` with that ID
4. Observe HTTP 400 "Not able to modify the internal user" response

### Expected behavior

- **Option 1:** `GET /user/:id` responds 200 with internal user details
- **Option 2:** `GET /api/dashboard/:id` includes `creator` block with user details

### Information about your Metabase installation

```JSON
- Metabase version: 0.50.0
```

### Severity

Annoying

### Additional context

There's likely no legitimate use case for exporting examples to dbt, but I'm sure users will attempt to export everything and be puzzled by the error. For now, I'm filtering for 400 responses that mention "internal user", not the most elegant workaround.

**Comment by paoliniluis** [comment]
Hey first of all thanks for your project, it’s really helpful for the community. I’m taking this to the product team so we can fix it as soon as we can
