### ISSUE TITLE
[Flaky Test]: above-goal-alert-test

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#44041]
Last Flake: https://github.com/metabase/metabase/actions/runs/9453305966
Last Flake Time: 2024-06-10T12:22:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by darksciencebase** [comment]
we've already had [an issue in progress ](https://github.com/metabase/metabase/issues/43321) about this, but we're switching to this one to make it easier for the bot.

**Comment by qnkhuat** [comment]
Fixed by reworking how test setup works in https://github.com/metabase/metabase/pull/43924
