### ISSUE TITLE
Why someone who does not have access to table should have access to questions?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#4406]
In permissions tab there is something that really is missing and that is when I create a group with access to few tables and assign user to that group, user has access to questions! which is related to that table.

When I want to prevent user from reading a table it is because I don't want him/her to access that data at all.

Could this behaviour change? Or have permissions for questions too.
To be frank without any limitation on questions, table grants are meaningless.

Thank you all for the time you have put for this great project.

**Comment by camsaul** [comment]
@alirezastack, I'm not sure I understand what you want to do. If you give someone access to questions but not the tables they read from [you can set up Collections](http://www.metabase.com/docs/latest/administration-guide/06-collections.html) of questions and manage their permissions.

**Comment by salsakran** [comment]
@alirezastack can you be more specific with respect to the specific permissions set?

Also, it should be noted that the "access to tables" refers to a user's self serve access to question. If you're giving a user access to SQL, we don't restrict SQL queries at the current time. As @camsaul mentioned, we'd suggest putting SQL questions into collections, and using those to define permissions.

**Comment by alirezastack** [comment]
@camsaul I didn't notice that! Thank you it solved my problem.
