### ISSUE TITLE
Search during selection of Foreign Key within Data Model

### ISSUE THREAD

**Issue by bohlian** [metabase/metabase#4408]
To have search functionality when selecting Foreign Keys within the Data Model section. For very long lists it is very hard to find the FK which you are looking for.

**Comment by siggibjarna** [comment]
If implementing search is difficult, it would help a lot to have the FK list in sorted order

**Comment by flamber** [comment]
Related to #7586

**Comment by mazameli** [comment]
Duplicate of https://github.com/metabase/metabase/issues/2805
