### ISSUE TITLE
where is model cache and cache scheduler? 

### ISSUE THREAD

**Issue by mohamed-montaser91** [metabase/metabase#44094]
### Describe the bug

after upgrading to v0.50.0 and v0.50.1 the caching tab doesn't exist anymore under settings
![image](https://github.com/metabase/metabase/assets/145304304/5d2b2f31-42b6-4e4c-9861-6a8109a51505)

also Model persistence doesn't exist also
![image](https://github.com/metabase/metabase/assets/145304304/df593f96-55aa-459d-b430-7fa184cd48ee)
![image](https://github.com/metabase/metabase/assets/145304304/41159fc5-5e28-489c-a5e8-e1b5d5e052df)

and nothing under performance tab like the [documentation](https://www.metabase.com/docs/latest/data-modeling/model-persistence#turn-on-model-persistence-for-your-metabase) says
![image](https://github.com/metabase/metabase/assets/145304304/be4edb3f-bb8e-423e-b3af-2937b4c1b9bf)

and I can't rollback to v0.49.15 also, so what should i do now, all our models are dependent on this feature. 

### To Reproduce

Go to settings - admin settings and you will find no cache setting for model.
Also go to performance and you will not find Model persistence

### Expected behavior

this setting should exist
![image](https://github.com/metabase/metabase/assets/145304304/9b91c4b1-69c3-4f21-9557-47082daa60ca)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.146.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.3 (Debian 16.3-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-12",
      "tag": "v0.50.1",
      "hash": "cc4ca82"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Extremely Severe and annoying, all our models are dependent on this feature

**Comment by paoliniluis** [comment]
Move to 50.2
