### ISSUE TITLE
Next Update

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#4410]
Hi, thx for amazing product.
When you are planning to release the next update?

**Comment by kdoh** [comment]
Hey @MixMe. We try to release major new features on around a monthly basis, but depending on what those features are that can add or remove some time. I can't give you an exact date for our next version (0.23) just yet, but it should definitely be ready within the next couple weeks, probably sooner.

Is there a particular feature you're looking for in 0.23?

**Comment by MixMe** [comment]
i'm waiting this fix: https://github.com/metabase/metabase/issues/3816 :)

**Comment by kdoh** [comment]
@MixMe Gotcha. Thanks for waiting and checking in with us. I'm going to go ahead and close this issue for now.
