### ISSUE TITLE
Grouping by Description Semantic Type Breaks Pivot Table

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#44105]
### Describe the bug

In the query builder if you take an aggregate and group it by multiple fields, one of which has a semantic type of "Description" - the description typed field gets stuck as a measure in the Pivot viz settings.

### To Reproduce

1. In the "Products" table change "Vendor" to a semantic type of "Description"
2. Create a question that takes a count (or another aggregate) grouped by "Vendor" and another field
3. Switch the viz to a pivot type
4. Look in visualization settings and see the "Vendor" field is there but it's stuck in the "Measure" section

Note: If you make a pivot using non description fields and then add this in with an edit it works fine.

### Expected behavior

The description field should be a dimension 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "h2",
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-28",
      "tag": "v1.49.13",
      "hash": "de28e83"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

**Comment by cdeweyx** [comment]
[More context](https://metabase.zendesk.com/agent/tickets/27818) on how to repro

**Comment by cdeweyx** [comment]
Having trouble repro'ing this [here](https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjMsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdLFsiYXZnIixbImZpZWxkIiwyNCx7ImJhc2UtdHlwZSI6InR5cGUvRmxvYXQifV1dXSwiYnJlYWtvdXQiOltbImZpZWxkIiwyOSx7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWUiLCJ0ZW1wb3JhbC11bml0IjoibW9udGgifV0sWyJmaWVsZCIsMjAseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dfX0sImRpc3BsYXkiOiJwaXZvdCIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJwaXZvdF90YWJsZS5jb2x1bW5fc3BsaXQiOnsicm93cyI6W1siZmllbGQiLDIwLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSwiY29sdW1ucyI6W1siZmllbGQiLDI5LHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZSIsInRlbXBvcmFsLXVuaXQiOiJtb250aCJ9XV0sInZhbHVlcyI6W1siYWdncmVnYXRpb24iLDBdLFsiYWdncmVnYXRpb24iLDFdXX0sInBpdm90X3RhYmxlLmNvbHVtbl93aWR0aHMiOnsibGVmdEhlYWRlcldpZHRocyI6WzE4N10sInRvdGFsTGVmdEhlYWRlcldpZHRocyI6MTg3LCJ2YWx1ZUhlYWRlcldpZHRocyI6e319fSwidHlwZSI6InF1ZXN0aW9uIn0=), tried private browser and other tips outlined in [the ticket](https://metabase.zendesk.com/agent/tickets/27818).

**Comment by ixipixi** [comment]
@cdeweyx I have a local copy of 50.18 running so I checked there. This doesn't occur in 50.18 (still happens in 49.21). So I imagine this was fixed at some point in 50 by proxy of another bug fix.
