### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by Geronimonetto** [metabase/metabase#44120]
### Describe the bug

Fiz uma atualização da versão 0.47.2 para versão 0.50.1 e não estou conseguindo fazer conexão com o meu banco de dados postgreSQL o erro que está acometendo é:

```
[c9b5bde9-114a-4a63-8a8c-52242c6a7ddc] 2024-06-13T06:32:11-03:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: The connection attempt failed.
{:database_id 2,
 :started_at #t "2024-06-13T09:31:40.661697Z[UTC]",
 :via
 [{:status :failed,
   :class org.postgresql.util.PSQLException,
   :error "The connection attempt failed.",
   :stacktrace
   ["org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)"
    "org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)"
    "org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)"
    "org.postgresql.Driver.makeConnection(Driver.java:446)"
    "org.postgresql.Driver.connect(Driver.java:298)"
    "java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)"
    "java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)"
    "--> connection_pool$proxy_data_source$reify__42125.getConnection(connection_pool.clj:29)"],
   :state "08001"}
  {:status :failed,
  ```

### Expected behavior

o certo seria não dar esse erro ja que a versão anterior estava funcionando, atualizei o driver do dremio, por que minha conexão do metabase é com o dremio e mesmo assim nada foi resolvido.

### Information about your Metabase installation

```JSON
estavamos usando a versão 0.47.2 e baixamos a versão 0.50.1 direto na nossa instancia da aws e colocamos na nossa pasta do metabase o nosso arquivo metabase.jar e iniciamos o serviço.
```

### Severity

importante

### Additional context

Estamos sem saber o que fazer para esse problema.

**Comment by paoliniluis** [comment]
Please post:
1) full logs
2) diagnostic info
3) how you’re connecting to the app db

**Comment by Geronimonetto** [comment]
{
"browser-info": {
"language": "pt-BR",
"platform": "Win32",
"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
"vendor": "Google Inc."
},
"system-info": {
"file.encoding": "UTF-8",
"java.runtime.name": "OpenJDK Runtime Environment",
"java.runtime.version": "11.0.20.1+9-LTS",
"java.vendor": "Amazon.com Inc.",
"java.vendor.url": "https://aws.amazon.com/corretto/",
"java.version": "11.0.20.1",
"java.vm.name": "OpenJDK 64-Bit Server VM",
"java.vm.version": "11.0.20.1+9-LTS",
"os.name": "Linux",
"os.version": "6.1.52-71.125.amzn2023.x86_64",
"user.language": "en",
"user.timezone": "UTC"
},
"metabase-info": {
"databases": [
"dremio"
],
"hosting-env": "unknown",
"application-database": "postgres",
"application-database-details": {
"database": {
"name": "PostgreSQL",
"version": "15.4"
},
"jdbc-driver": {
"name": "PostgreSQL JDBC Driver",
"version": "42.7.3"
}
},
"run-mode": "prod",
"version": {
"date": "2024-06-13",
"tag": "v0.50.3",
"hash": "855535b"
},
"settings": {
"report-timezone": null
}
}
}

Em qui., 13 de jun. de 2024 às 08:46, Luis Paolini ***@***.***>
escreveu:

**Comment by paoliniluis** [comment]
So you can’t connect to a new Postgres database, is that correct?

**Comment by Geronimonetto** [comment]
Não estou conseguindo conectar com nenhum banco de dados na verdade


Em qui., 13 de jun. de 2024 às 13:13, Luis Paolini ***@***.***>
escreveu:

**Comment by paoliniluis** [comment]
ok so it's definitely the dremio driver, please remove it or downgrade

**Comment by darksciencebase** [comment]
closing, will reopen if the problem persists with dremio out of the equation.
