### ISSUE TITLE
Feature Request: Allow two queried inputs in the Progress visualization

### ISSUE THREAD

**Issue by brnt** [metabase/metabase#4412]
Currently, the Progress visualization type allows one queried number and one static input ("Goal"). It would be great if both of those fields could be generated, rather than the Goal having to be set statically. There are many cases where an organization's goal (small G) will vary based on some observable value and it would be nice to have the Goal (big G) follow that value without user intervention.

#### An example use case: New users today vs New users contacted today
The "goal" in this scenario would be to contact each new user. The graph would represent the new user count (as the anchor/goal value) and the number contacted (the progress value).

**Comment by benjR** [comment]
Been searching for this too, being static does not help, have to use the row chart for now and do the math.

**Comment by EBoisseauSierra** [comment]
One workaround for this is to use a KPI that can cope with a “hardcoded” goal, namely the ratio 
```
new users contacted today ÷ new users today
```
and to plot it against 1 (or 100%).  
I agree this is not entirely satisfactory, though.

---

I'd like to extend the principle of this feature request to **Gauge visualisation as well** — do we want to raise a separate issue for this?

**Comment by flamber** [comment]
Closing in favor of #6514, which now has a milestone set (not a guarantee)
