### ISSUE TITLE
Indexed Entities lack visual context in command palette

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#44136]
### Describe the bug

<img width="1198" alt="image" src="https://github.com/metabase/metabase/assets/6377293/37551cdb-eada-422c-9915-0cad84bf1e6c">

The indexed entities in the command palette lack visual information

Contrast with 49's search results:
<img width="1383" alt="image" src="https://github.com/metabase/metabase/assets/6377293/ee2ad800-7736-4419-845c-a65144b4ec22">

and the full page results
<img width="1535" alt="image" src="https://github.com/metabase/metabase/assets/6377293/9dea1d98-0df4-42c4-9320-9f9ca29200b8">

### To Reproduce

on a 50 or master version, create a model on Products, edit it's metadata and create an index on the title

![image](https://github.com/metabase/metabase/assets/6377293/23bb7dd9-3d9d-44f0-8448-b3404d76ab2f)

Then use command palette to search for some of the products ("rustic" is a great search term)

### Expected behavior

Some visual indicator that these are _rows_ in a model rather than just tables or cards themselves.

### Information about your Metabase installation

```JSON
master
```

### Severity

p3

**Comment by mazameli** [comment]
My suggested solution is for this to take the form: `{Indexed entity name} — a record in {table/model display name}`, e.g.:

**Rustic Paper Bench** — a record in Products
