### ISSUE TITLE
[Flaky Test]: should open the same dashboard when a custom URL click behavior points to the same dashboard (metabase#22702)

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#44146]
Last Flake: https://github.com/metabase/metabase/actions/runs/9468524002
Last Flake Time: 2024-06-11T09:09:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 4
Flakes in the last 7d: 4

**Comment by JesseSDevaney** [comment]
Closing this as it was fixed by:
- https://github.com/metabase/metabase/pull/44016
