### ISSUE TITLE
[Flaky Test]: should not allow cards to be resized smaller than min height

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#44144]
Last Flake: https://github.com/metabase/metabase/actions/runs/9487485391
Last Flake Time: 2024-06-12T11:45:00-07:00
Flakes in the last day: 2
Flakes in the last 3d: 5
Flakes in the last 7d: 6

**Comment by JesseSDevaney** [comment]
Closing as I cannot find any recent runs that still have this test failing, so there is nothing to be able to reproduce the flake and fix it
![image](https://github.com/metabase/metabase/assets/22608765/c3505086-f417-49c6-b4c3-3462c2f46f11)
