### ISSUE TITLE
Development - use lodash instead of underscore

### ISSUE THREAD

**Issue by mariusz-jachimowicz-83** [metabase/metabase#4415]
I noticed that some libs like `redux-actions` require  `lodash` so it is included by webpack into bundle. 
I also noticed that we use `underscore`.
Maybe we could use only `lodash` for simplicity? It might be better from performance perspective also.
What do you think?

**Comment by tlrobinson** [comment]
I'm open to to it. It might be a good project for someone looking to start contributing to Metabase.

**Comment by VikramTiwari** [comment]
@tlrobinson I am up for it.

Some clarification:
- Does it mean that `frontend/interfaces/underscore.js` won't be required and all instances will be replaced with `lodash`
- Does it also mean that `frontend/interfaces/icepick.js` won't be required as well?

Any other suggestions? n00b to react.

**Comment by salsakran** [comment]
closing since this seems like it doesn't actually reduce our download size materially and it involves work and potential bugs coming out of it. Also, no one's stepped up in 2 years.
