### ISSUE TITLE
Remove help@metabase.com from Error Diagnostic Modal

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#44150]
We want to avoid getting a deluge of emails from customers without support plans.

see [discussion](https://metaboat.slack.com/archives/C013N8XL286/p1718285213011609?thread_ts=1718284371.001519&cid=C013N8XL286)

**Comment by rafpaf** [comment]
@iethree Should the diagnostic modal just say: `Click the button below to download diagnostic information`?
