### ISSUE TITLE
Add option to download as Excel (.xls/.xlsx) file

### ISSUE THREAD

**Issue by robinpapa** [metabase/metabase#4417]
The current workflow for importing data into Microsoft Excel for further analysis is:
_Download the .csv, open in Excel, use the "text-to-column" function to separate the columns._

To make Metabase more attractive for use in office environments, I would suggest building a direct Excel export into the application. I am willing to do the development myself but first I would like to know if such a feature is appreciated. Also, I need to decide on the filesystem (.xls or .xlsx).

Thanks in advance for your feedback.

**Comment by kdoh** [comment]
@robinpapa We'd definitely love your contribution on this. Let us know if there are any questions you have.

Off the top of my head the main question besides the file format like you mentioned above is how to incorporate the choice between csv and excel formats into the download experience on the frontend but we can cross that bridge later since I don't think it would impact you working on getting the format and download side of things working if you're feeling excited about this.

**Comment by camsaul** [comment]
I saw the author of [docjure](https://github.com/mjul/docjure) give a talk at Clojure/West a couple of years ago and it looks promising as a library to use for creating Excel files

**Comment by tlrobinson** [comment]
@kdoh we've already got CSV and JSON download buttons, would we need to do anything other than add a XLS or XLSX button, UX-wise?

If not, should we add the "Help Wanted" label to this?

**Comment by KeeonTabrizi** [comment]
+1 from me. 

Here are the export options JackDB currently supports:

![image](https://cloud.githubusercontent.com/assets/3408390/23203113/e977b428-f895-11e6-98bd-faa30f36b611.png)

**Comment by robinpapa** [comment]
@kdoh agreed, I'll work on the functional part for now but I agree with you that we need to think about the download experience. 
@camsaul thank you for the library, I'll look into it!

I'm just going with a third button on the front-end for now. Now moving on to the back-end. Thanks for the support!

<img width="432" alt="metabase" src="https://cloud.githubusercontent.com/assets/6068083/23257256/585fad5e-f9c3-11e6-95c0-f3caa543f4d1.png">

**Comment by robinpapa** [comment]
Hi! I'm sorry, I currently can't make time to read into Clojure and make this happen. Can we put a help wanted tag on this issue? Maybe someone can help me with this?

**Comment by theronic** [comment]
To +1 this, CSV as a format causes a number of problems for us - any dirty text data that contains a comma, semicolon or tab character is rarely interpreted correctly by Excel or Google Sheets

**Comment by tlrobinson** [comment]
FYI this should be a pretty easy way for someone to start contributing to Metabase.

1. create a function similar to [`as-csv`](https://github.com/metabase/metabase/blob/master/src/metabase/api/dataset.clj#L49) called `as-xlsx` in `src/metabase/api/dataset.clj` using [docjure](https://github.com/mjul/docjure#example-create-a-spreadsheet). Also add `[dk.ative/docjure "1.11.0"]` to `project.clj`
2. search for the 4 endpoints that use `as-csv` (in `dataset.clj`, `card.clj`, `embed.clj`, and `public.clj`) and create the `xlsx` equivalents. However it might be time to refactor this a bit now that we have 4 types of endpoints and 3 different download formats. @camsaul?
3. add `/question/:uuid.xlsx` and `/question/:token.xlsx` routes in `src/metabase/routes.clj`
4. add `xslx` to the list of download types in [`QueryDownloadWidget.jsx`](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/QueryDownloadWidget.jsx#L34) (maybe move that list to a `const` at the top of the file while you're at it)

**Comment by stefano** [comment]
Hi, I started an implementation of this feature: https://github.com/stefano/metabase/commit/fa4baacd8351a2ebf262b4f621f840ff5216c1a2

It's still not  complete, before it can be considered ready I need to:

- refactor some of the duplicatation between CSV/XLSX/JSON export code
- add some tests

I don't have much time next week, but I should be able to complete the code and make a PR over the next weekend hopefully.

**Comment by kdoh** [comment]
Awesome @stefano. Thanks for your work on this.

**Comment by aniamin** [comment]
Is there any update on this? Can I directly import any data from Metabase Question (that is added to a dashboard) to xlsx/csv?

**Comment by camsaul** [comment]
Implemented by #4866/#4922

**Comment by sldorman** [comment]
Has this officially been released?  I have 0.24.1 and I see the download options.  If I select XLSX, I get an error.  If I select CSV, the file is generated but some columns have the wrong information in them.

**Comment by tlrobinson** [comment]
@sldorman Yes it's released, but it's certainly possible there are bugs. Maybe #5145?

Regarding the CSV one can you search for an existing issue and if there is none file a new, please?
