### ISSUE TITLE
Integrate metabase with AI models

### ISSUE THREAD

**Issue by e-gaulue** [metabase/metabase#44214]
**Describe the solution you'd like**
 * 1rst stage
Learn how the dataware house is structured. Generate information schema from the data field. Allow admins to help it understand (training).
Allow to build query in natural langage: "I want to get all my orders of the last year" 
 * 2nd stage
Help users to present their data using natural language: "I want in a bar chart the number of order each month"
 * 3nd stage
Mix them all: "I want a chart with the number of order by month this year compared with last year."

**Describe alternatives you've considered**
SQLAI. Excel Copilote. PandsAI. MindsDB.

**How important is this feature to you?**
Ready to pay for, while now we are on Free on promise system.

**Comment by samtuke** [comment]
I would guess most Metabase users want AI features. Any news?

**Comment by paoliniluis** [comment]
Please check our roadmap

**Comment by mjftw** [comment]
Just to add to this - this is also a feature my company is likely to be willing to pay for!

**Comment by brunobergher** [comment]
Duplicate of #38272
