### ISSUE TITLE
Saved metric didn’t appear in the list of recent items after a click on “search”

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#44223]
### Describe the bug

A newly created metric does not show up in the recent items when clicking on search.

<img width="1474" alt="Screenshot 2024-06-14 at 16 07 32" src="https://github.com/metabase/metabase/assets/1250185/22ba5dd1-8cf3-4982-aefa-f8b031a8181b">

### To Reproduce

1. Create a new metric
2. Click on the search bar in the top menu

The new metric does not display in recent items

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Mac OS X",
    "os.version": "14.2.1",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-06-12",
      "src_hash": "7a87e1a1173927a489fc70b6fc3e9bded123a326",
      "tag": "v1.2.0-SNAPSHOT",
      "hash": "3afe482"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

**Comment by nemanjaglumac** [comment]
Some more context
The recents API doesn't return the new metric.
<img width="2056" alt="image" src="https://github.com/user-attachments/assets/3b116f51-a979-4196-960e-36f75661163b">

https://metaboat.slack.com/archives/C0645JP1W81/p1721300382482059

**Comment by iethree** [comment]
this is caused because metrics don't GET after the POST to create them, unlike questions and models:

repro: https://www.loom.com/share/1a7f078fda5f47a5a729b58f73305d99
