### ISSUE TITLE
Enhancement - automatic trend line in line charts

### ISSUE THREAD

**Issue by dburgan** [metabase/metabase#4424]
It would be super cool if Metabase would offer an option for line charts to automatically calculate/display a linear regression trend line based on the data points in the chart.  Something like this:

![image](https://cloud.githubusercontent.com/assets/25944315/23196006/5efe9744-f87c-11e6-85e6-0a0709bb628f.png)

It could simply be a checkbox on the "Customize this chart > Data" dialog:

![image](https://cloud.githubusercontent.com/assets/25944315/23196054/d32a258e-f87c-11e6-9bf2-f684cfe4e028.png)

Ideally we could also change the color of the trend line:

![image](https://cloud.githubusercontent.com/assets/25944315/23196113/37822d88-f87d-11e6-8b85-20480053c56b.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by tanzoniteblack** [comment]
For the note: Since we're now including the simple-statistics package (pulled in with https://github.com/metabase/metabase/pull/4593 ), calculating the trend lines themselves is pretty simple (see http://simplestatistics.org/docs/#linearregression )?

**Comment by mchip22** [comment]
Yes please

**Comment by lcorrales** [comment]
+1 to this feature :)

**Comment by Schusti91** [comment]
+1 because it's quite difficult to implement something with SQL only

**Comment by MarkRx** [comment]
There are several methods to create trend "lines" with some not being lines at all. What computation method(s) would be available?

**Comment by jornh** [comment]
Related: https://github.com/metabase/metabase/issues/5705 (simple average line)
