### ISSUE TITLE
Development - long backend starting process

### ISSUE THREAD

**Issue by mariusz-jachimowicz-83** [metabase/metabase#4426]
Investigate `lein ring server` starting process. 
Is it possible to reduce this time?
![start](https://cloud.githubusercontent.com/assets/10278877/23213480/5fda5d4e-f90b-11e6-993e-c6e44fb6efa3.png)

**Comment by salsakran** [comment]
we figured out some aspects of this and it should be significantly improved. had to do with classpath loading I _believe_
