### ISSUE TITLE
Cannot connect a number filter to a native card

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#44276]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/051766a8-80ad-4e8d-bb55-44c6beb70f41

### To Reproduce

1. Create a new native question `select {{x}};` and save it
2. Add it to a dashboard when asked
3. Add number > equal to filter to the dashboard

> A number variable in this card can only be connected to a number filter with Equal to operator.

There's an error in JS console: 

```
TypeError: Cannot read properties of null (reading 'map')
    at getDatasetQueryParams (app-main.hot.bundle.js:431998:28)
    at app-main.hot.bundle.js:431761:84
    at type (app-main.hot.bundle.js:443135:35)
    at vendor.hot.bundle.js:335156:18
    at dispatch (vendor.hot.bundle.js:335885:28)
    at app-main.hot.bundle.js:431915:14
    at Array.map (<anonymous>)
    at app-main.hot.bundle.js:431910:49
    at vendor.hot.bundle.js:335156:18
    at dispatch (vendor.hot.bundle.js:335885:28)
```

### Expected behavior

User is able to connect this filter to the card

### Information about your Metabase installation

`master`, 93334133ea

### Severity

P1

### Additional info

Possibly related to #44266

**Comment by Tony-metabase** [comment]
Hey @kamilmielnik I might be missing something but isn't the filter a TEXT? So i would expect a NUMBER filter to not work

<img width="735" alt="image" src="https://github.com/metabase/metabase/assets/110378427/af18a028-a356-4c91-b100-2c5d4a74a000">

**Comment by kamilmielnik** [comment]
> Hey @kamilmielnik I might be missing something but isn't the filter a TEXT? So i would expect a NUMBER filter to not work

Absolutely, thanks!
Closing.
