### ISSUE TITLE
Dashboard filters do not work with SQL models

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#44288]
### Describe the bug

When a dashboard filter is connected to a SQL model, adding a filter doesn't actually filter data.

### To Reproduce

1. New -> Model -> SQL -> `SELECT * FROM PRODUCTS` - run and save
2. Add to a dashboard
3. Add a text filter and connect to the `CATEGORY` field
4. Set the filter value to `Widget` 
5. See that after the filter is applied the query results are the same and obviously not filtered
6. The same seems to happen with any other filter type or column

### Expected behavior

It should actually filter data.

### Logs

No relevant FE or BE logs. It seems that the BE silently ignores some error.

### Information about your Metabase installation

```JSON
v50
```

### Severity

P1/P2

**Comment by cdeweyx** [comment]
The fix here is not to support filtering for SQL models on dashboards, but rather to make it clear that this limitation exists. We should add the following message to both GUI and SQL models when in parameter mapping mode on dashboards:

> Models are data sources and thus can’t have parameters mapped. [Learn more](https://www.metabase.com/learn/data-modeling/models#:~:text=If%20you%20add%20a%20model%20to%20a%20dashboard%2C%20you%E2%80%99ll%20notice%20that%20you%20can%E2%80%99t%20map%20any%20of%20its%20columns%20to%20a%20dashboard%20filter%2C%20even%20after%20you%E2%80%99ve%20set%20the%20types%20for%20those%20filters.%20To%20get%20those%20same%20results%20with%20models%2C%20you%20can%3A)

Example design pattern for a different limiting case: 

<img width="331" alt="Screenshot 2024-06-17 at 11 33 20" src="https://github.com/metabase/metabase/assets/16455495/440591b5-27a8-4090-a6e0-3e290ca9ce61">

[More Slack context](https://metaboat.slack.com/archives/C05NXACAG1G/p1718638141251419?thread_ts=1718629292.335359&cid=C05NXACAG1G).

**Comment by ranquild** [comment]
Closed by https://github.com/metabase/metabase/pull/44372
