### ISSUE TITLE
[Flaky Test]: two-cards-in-one-pulse-test

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#44333]
Last Flake: https://github.com/metabase/metabase/actions/runs/9528897878
Last Flake Time: 2024-06-15T08:35:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by darksciencebase** [comment]
we suspect it's gonna get closed by https://github.com/metabase/metabase/pull/43924 but will verify first

**Comment by qnkhuat** [comment]
Fixed by reworking how test setup works in https://github.com/metabase/metabase/pull/43924
