### ISSUE TITLE
Trendline moves on refresh on aggregated timeseries data

### ISSUE THREAD

**Issue by monneyboi** [metabase/metabase#44349]
### Describe the bug

I have a small dataset containing timeseries data. When i create a bar chart for the sums of the numerical data, aggregated by week, and enable the trend line. The trendline will sometimes move on refresh, as show on the attached screenshots. When i aggregate by day, there doesn't seem to be a problem.

### To Reproduce

Create a question for a date, number dataset. 
X-axis = date, Y-axis = sum of number
Enable trend-line under the "display" options.

Look at your bar chart with trend line, and refresh a couple of times.

### Expected behavior

I expect the trendline to not move

### Information about your Metabase installation

```JSON
Firefox 128.0b4 (64-bit)
Metabase 0.50.5, experienced the same problem with 0.48.6
Postgresql 15
Container in K8s on gcloud.
```

### Severity

Harms trust

### Additional context

![image](https://github.com/metabase/metabase/assets/86304937/c242e9e4-0ecf-493c-8a7b-19d0ba20616d)
![image](https://github.com/metabase/metabase/assets/86304937/990502d4-0858-4227-a350-fd382899abad)

The dataset contains 2 colums, one date and one number.

Am i misunderstanding something or is this a issue?

**Comment by Tony-metabase** [comment]
Is the data changing as well? Like is the bar here changing values?

<img width="913" alt="image" src="https://github.com/metabase/metabase/assets/110378427/5d1df81f-69ca-47eb-b481-8acc5deccd17">

**Comment by JesseSDevaney** [comment]
Hi @monneyboi! 

I tried to reproduce this locally, but could not get the trend-line to move as it does in your chart. There may be an edge case for your dataset specifically (different date formatting, values, etc.).

In order for me to be able to resolve this issue, it would really help if you were able to share the data. 
- _As long as their is nothing sensitive in the data that you are not comfortable with sharing_

**Specifically:** Would you be able to share the `/api/dataset` response for your trend charts in at least two of the different trend line scenarios?
- One where it is in one location and another where it is in a different location

---
**Demonstration for how to retrieve the data**

https://github.com/metabase/metabase/assets/22608765/5a50a2b2-c0c3-46ce-9fff-c333f9d7932e

**Comment by monneyboi** [comment]
Thanks for looking into this!

Here's the `/api/dataset` responses.
[response_up.json](https://github.com/user-attachments/files/15913202/response_up.json)
[response_down.json](https://github.com/user-attachments/files/15913204/response_down.json)

The only meaningful difference is in the `insights`, the data is exactly the same.
```
424,425c424,425
<           "*",
<           309193.57441625773,
---
>           "+",
>           -62547.458657534145,
427,432c427,429
<             "exp",
<             [
<               "*",
<               -0.00009509785331076283,
<               "x"
<             ]
---
>             "*",
>             5.7833110464025825,
>             "x"
```
