### ISSUE TITLE
Making a model that joins a table 2 times will generate wrong x-rays

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#44379]
### Describe the bug

A query that is extremely wrong formed is made out of an x-ray
![image](https://github.com/metabase/metabase/assets/1711649/84ab2ef5-e912-4855-a31c-4b12f6aec774)

### To Reproduce

1) do new question: orders join people join people
2) save it as a model
3) x-ray the model

see the queries that are being generated

### Expected behavior

It should generate correct queries

### Logs

NA

### Information about your Metabase installation

```JSON
v50.x
```

### Severity

P1

### Additional context

NA

**Comment by bshepherdson** [comment]
This smells like the sort of thing that's seen in #36185 symptoms, though in this case outside the QP/QB stack.

Watch out for treating field IDs, or indeed almost anything about columns, as unique keys.

**Comment by piranha** [comment]
From what I've learned so far it seems like x-rays try to apply `created_at > last 30 days` filter on top of model definition - and model, after aggregation, just has not enough data (only id and count, no created_at) to make this work. This has nothing to do with two joins - removing one of the joins will not make this work, removing aggregation makes x-rays work even with two joins.

Seems like a logic bug in the x-rays generation — how and why do they find this filter and try to apply it on top of a model (which has it applied already)?
