### ISSUE TITLE
If you archive the dashboard you get in /api/activity/most_recently_viewed_dashboard then the modal to add a question gets weird

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#44382]
### Describe the bug

![image](https://github.com/metabase/metabase/assets/1711649/d94d44b7-54ea-447f-8384-c2be1f7348f4)

### To Reproduce

1) create an x-ray
2) archive it
3) now create a new question and then click to save it and add it do a dashboard
4) see the modal with "The object has been archived."

### Expected behavior

Product needed for this

### Logs

NA

### Information about your Metabase installation

```JSON
v50.x
```

### Severity

P3

**Comment by ranquild** [comment]
I'm pretty sure that `most_recently_viewed_dashboard` shouldn't return an archived dashboard

**Comment by kamilmielnik** [comment]
Reproducible in 0.50.0 and 0.50.6. Can't reproduce in `master` at 638d79c457.
