### ISSUE TITLE
Missing filter in dashboard chart

### ISSUE THREAD

**Issue by meldiner** [metabase/metabase#44381]
### Describe the bug

In the dashboard of one of our customers, Metabase is dropping one of the filters defined in a chart question when the chart is opened by clicking on its title. This issue leads to incorrect data being displayed, which undermines the reliability of the dashboard.

See video: https://www.loom.com/share/c94966bfe4c845e992c59e736858e632?sid=d8573159-52c0-4dc7-b234-25da7992a9e8

When opening the chart's question directly by clicking on "Edit Question," the filter "Max out_of_sla is equal to 1" is present and the data displayed is correct. The issue only occurs when accessing the chart through the dashboard.

### To Reproduce

1. Navigate to the dashboard.
2. Locate the chart in question.
3. Click on the chart's title to open it.
4. In the chart view, click on "Show Editor."

### Expected behavior

The filter defined in the chart question, `Max out_of_sla is equal to 1`, should be retained and applied when opening the chart through the dashboard.

### Information about your Metabase installation

```JSON

v48.10

```

### Severity

blocking

**Comment by paoliniluis** [comment]
version? we need the version to see what's going on and the context

**Comment by meldiner** [comment]
v48.10

**Comment by paoliniluis** [comment]
@meldiner ok, upgrade to, at least, 49.15 and then we can see if this is an issue or not. Closing the issue till then

**Comment by tovbinm** [comment]
Are there any fixes in the latest version that address this issue?

**Comment by ranquild** [comment]
@tovbinm yes - we fixed some bugs with filter application in v50

**Comment by meldiner** [comment]
This reproduces with the same chart on a newly created clean dashboard.

I'm going to try reproducing this locally with a newer Metabase version.
