### ISSUE TITLE
[Flaky Test]: should show columns available in the model (metabase#35039) (metabase#37009)

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#44408]
Last Flake: https://github.com/metabase/metabase/actions/runs/9557474309
Last Flake Time: 2024-06-17T19:08:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by nemanjaglumac** [comment]
Fixed by #46038
