### ISSUE TITLE
Permissions for new users not working

### ISSUE THREAD

**Issue by ihackalot** [metabase/metabase#4444]
As Admin group, a couple of users were able to define a dabase with relative questions and dashbords and everything's working fine for them.

Adding a new user, and setting his group permissions for this database doesn't really work. Of 4 dashboards only three are selectable, and none of the cards will display results other than a message of lacking permissions.

_All Users_ group is set to have no permissions for both _data access_ and _sql queries_ for this database, while the _New_ group has all permissions on as _Admin_ group.

--
Metabase 0.22.2
MariaDB 10.1 database

**Comment by salsakran** [comment]
What do you mean by "Adding a new user, and setting his group permissions for this database doesn't really work."? 

I'm having a hard time following what the exact groups + permissions are. Are the questions SQL, GUI or both?

**Comment by ihackalot** [comment]
Just like the attached picture, with all permissions granted to new user group, as admins, only three out of 4 set dashboards become available via the dashboard drop down. If I visit the url for the unavailable dashboard I get a giant _Sorry, you don’t have permission to see that._ message. The very same message is visible within each of the cards in all other three dashboards.

If I add the new user to the admin group, then everything is back to normal.

![screen shot 2017-02-28 at 8 39 34 am](https://cloud.githubusercontent.com/assets/28128/23395978/a4e4de0c-fd91-11e6-9d19-6734783ae35a.png)

**Comment by KidkArolis** [comment]
I don't know if this is the same issue as I'm having, but in my case:

1. A new user signs up using their Google Account.
2. They are now in "All Users" group which has all permissions enabled.
3. They don't see any saved queries, collections, dashboards or activity.

They only see those if I make them admins?

**Comment by salsakran** [comment]
@ihackalot what is in the dashboard they can't access?

**Comment by ihackalot** [comment]
99% of the cards are gui everywhere (no join or fk used, just like select, from Android group by), except a sql one in the unavailable dashboard, which is needed because a field filter variable is set. However, removing the sql card from dashboard doesn't make the dashboard visible again.

**Comment by KidkArolis** [comment]
My issue was related to collections having separate permissions, didn't
realise that at first. All works as expected now. Really enjoying metabase
so far!

**Comment by ihackalot** [comment]
Great! @KidkArolis solution fixes me as well. I didn't set collection permissions and when I created the new group no permission was granted.
