### ISSUE TITLE
Issue with put request for changing a user's password

### ISSUE THREAD

**Issue by jonnyenglish** [metabase/metabase#4445]
Hi, I just found out, that it doesn't  matter whether or not the old_password is correct when updating a users password. This applies to both, the web interface (can be seen in the web inspector e.g. in Chrome) and the api. 
This is the endpoint: https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#put-apiuseridpassword

steps to reproduce (example in python):

```
import httplib
host = 'metabaseHost:3000'
sessionId = getSessionId #as explained here: https://github.com/metabase/metabase/wiki/Using-the-REST-API#authorizing
c = httplib.HTTPConnection(host)
headers = {
    "Content-Type": "application/json",
    "X-Metabase-Session": sessionId 
}

endpoint = '/api/user/1/password'
data = '{"password": "newPass", "old_password": "doesNotMatter"}'

c.request('PUT', endpoint, data, headers=headers)
c.getresponse().read()
```

You can try the same on the web interface. Just type anyting as the old password. Is this the expected behaviour?

**Comment by camsaul** [comment]
@jonnyenglish, are you logged in as an admin? You only need to pass the `old_password` if you're a regular user, as admins have permissions to reset passwords without knowing the original. If you try the endpoint as a regular user you'll see that `old_password` is being validated

**Comment by jonnyenglish** [comment]
Oh now that totally makes sense 🙈 Thanks for clarifying and sorry for the interruption
