### ISSUE TITLE
DBT & Metabase

### ISSUE THREAD

**Issue by Dillbearer** [metabase/metabase#44467]
I am using the DBT to transform data in my DB (PostgreSQL). It DROPs and CREATEs tables for update.
My tables in Metabase (v 0.49.12) automatically take wrong "Field type". I change it, but after updating the tables in DBT, the "Field type" automatically changes back to the wrong one.

Metabase needs to remember the table with columns by names and not change the "Field type".

Thank you!

**Comment by qnkhuat** [comment]
Could you show us how to repro this?

> My tables in Metabase (v 0.49.12) automatically take wrong "Field type". I change it, but after updating the tables in DBT, the "Field type" automatically changes back to the wrong one.

What's the wrong field type? and when you say you change it, what exactly does it mean?

**Comment by calherries** [comment]
Related: https://github.com/metabase/metabase/issues/44698

**Comment by calherries** [comment]
@Dillbearer can you tell us a bit more about the column? 
1. What type you were changing it to? 
2. What type did it reverted back to?
3. Does the column have many NULL values?
4. And what the Postgres type of the column is?
5. What semantic category of values are stored in the column? (example answer: the values are all URLs)

**Comment by darksciencebase** [comment]
@Dillbearer have you had a chance to read the questions @calherries posted?

**Comment by darksciencebase** [comment]
@Dillbearer we need to narrow this down to reproduce and fix the issue, could you please answer the questions above?

**Comment by darksciencebase** [comment]
closing for the lack of leads. will reopen if more information comes in
