### ISSUE TITLE
Missing schema name in data picker

### ISSUE THREAD

**Issue by attaxia** [metabase/metabase#44460]
### Describe the bug

In Metabase 49, when starting a question and searching for a table, the schema name was displayed so that tables that exist with the same name in more than one schema were easy to identify.

### To Reproduce

1.  Have a Postgres data source with two schemas
2. Have a table with the same name in both schemas
3. Create a new question, enter the name of the table in the search box
4. Try to tell apart the two tables

![Screenshot 2024-06-20 at 10 36 58](https://github.com/metabase/metabase/assets/4743303/1fd31fed-dfdd-47ad-abff-0c61267f4fb9)

### Expected behavior

Metabase 49 would show the schema name under the table name, I would expect the same here.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.0-28-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": "Europe/Amsterdam"
    }
  }
}
```

### Severity

Blocking for some users

### Additional context

We have two schemas with mostly the same table names but containing completely different data. This makes it very difficult to make new questions.

**Comment by kamilmielnik** [comment]
Reopening, see https://github.com/metabase/metabase/pull/44468#issuecomment-2196623087

**Comment by kamilmielnik** [comment]
We need to display table schema in at least these 4 cases:
- Tables in Search results in Data Picker (done in #44468)
- Tables in Search results in Command Palette (todo)
- Tables in Recents in Data Picker (todo)
- Tables in Recents in Command Palette (todo)

`api/activity/recents` does not return table schema, we need to add it there (see [`SearchResult["table_schema"]`](https://github.com/metabase/metabase/blob/95adc26b34f7d9ab1efb36d0723ccbed2a299e4f/frontend/src/metabase-types/api/search.ts#L98))
