### ISSUE TITLE
Check whether driver supports `expression-aggregations` before showing Custom Expressions UI

### ISSUE THREAD

**Issue by whitef0x0** [metabase/metabase#4447]
For some reason I'm getting this error `Assert failed: (keyword? aggregation-type)` when I try to create the Custom Expression "Count / Distinct(ID)".

I can't find anything online about this so I'd figure I'd ask here.

- Your browser and the version: Chrome 56
- Your operating system: OSX 10.11.6
- Your databases: MongoDB 3.0
- Metabase version: Metabase
- Metabase hosting environment: Heroku App
- Metabase internal database: H2

1. Import Database
2. Create Question with Expression "Count / Distinct(Field)"
3. Press Refresh

**Comment by tlrobinson** [comment]
This works on the Sample Dataset, so I'm guessing it's a MongoDB issue.

**Comment by camsaul** [comment]
We don't currently support Custom Expressions for MongoDB. @tlrobinson are we checking whether the driver supports the `expression-aggregations` feature?
