### ISSUE TITLE
Native Mongo Query with ObjectId : Unrecognized token 'ObjectId' Error

### ISSUE THREAD

**Issue by ampsarfraz** [metabase/metabase#4448]
Hello,
Can you please give me a sample to use ObjectId in Native Queries, I am trying to use native queries in MongoDB to overcome the ISODate Issue.  However I get the below error when I use ObjectId for BSON id fields.

**Unrecognized token 'ObjectId': was expecting ('true', 'false' or 'null') at [Source: java.io.StringReader@5d8a3934; line: 2, column: 38]**

```json
 [{"$project":{"entityId":"$entityId","data___maturingamount":"$data.maturingamount","data":"$data","createdAt":"$createdAt"}},
{"$match":{"entityId":{"$eq":ObjectId("583327789137b2700a1621fb")}}},
{"$group":{"_id":null,"sum":{"$sum":"$data___maturingamount"}}},
{"$sort":{"_id":1}},{"$project":{"_id":false,"sum":true}}]
```

Thank you !

**Comment by camsaul** [comment]
@ampsarfraz, unfortunately `ObjectId(...)` isn't valid JSON so our JSON parser is throwing an exception when it sees that in the query. I fixed the same issue for `ISODate(...)` calls in #4132 by manually replacing them in the query string *before* it gets parsed as JSON. We can do something similar here to get `ObjectId(...)` working.

**Comment by ampsarfraz** [comment]
Thank you @camsaul . That would be great!

**Comment by asbaker** [comment]
Why do any JSON parsing/validation and wrapping the aggregate call at all?
We could pass down the entirety of the statement down to mongo and bubble up any errors it throws.

This could also help solve the problem with #3653 as well since they would just be native javascript variables then.

**Comment by sibelius** [comment]
this is breaking for me

java.lang.IllegalArgumentException: No implementation of method: :->temporal of protocol: #'metabase.sync.analyze.fingerprint.fingerprinters/ITemporalCoerceable found for class: org.bson.types.ObjectId

**Comment by sibelius** [comment]
it is working now
