### ISSUE TITLE
v50: Foreign keys no longer work with MongoDB

### ISSUE THREAD

**Issue by arasmussen** [metabase/metabase#44511]
### Describe the bug

Questions that leverage foreign keys are no longer working as of Metabase 50, but were working well in Metabase 49.

### To Reproduce

Repro steps:
- create two collections
  - collectionA: `{ _id: ObjectId, bID: ObjectId, value: string }`
  - collectionB: `{ _id: ObjectId, value: string }`
- in metabase admin, set `collectionA.bID` as a foreign key to `collectionB._id`
- ask a new question: count of rows for collectionA where collectionB.value == 'foo'

### Expected behavior

This worked well in Metabase 49, but regressed in Metabase 50. It would answer the question.

Now I'm getting: `:mongo driver does not support foreign keys.`

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9-LTS",
    "os.name": "Linux",
    "os.version": "4.14.109-99.92.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

pretty darn significant for mongodb users

**Comment by paoliniluis** [comment]
hey sorry about that. I'm flagging this as a regression

**Comment by arasmussen** [comment]
thanks for the quick response! I also tried downgrading back to v49 with `migrate down` and it corrupted my database file 😓 but that's on me for not backing it up

could be good to add an "are you sure? have you backed up your db?" step to migrate down if migrating down isn't well supported

**Comment by qnkhuat** [comment]
@arasmussen downgrade should work. Could you file a bug describing how corrupted your db is after the downgrade?

But yeah, you should backup before doing any kind of migration.
