### ISSUE TITLE
[0.49.2->v0.50.3] query joining metabase_table and metabase_field overwhelms our PG instance

### ISSUE THREAD

**Issue by CeliaMonstro** [metabase/metabase#44537]
### Describe the bug

Right after upgrading to v0.50.3, we encountered massive perf issues. 

![image](https://github.com/metabase/metabase/assets/91955383/165b4c25-022a-4c5d-a293-fed5d1b1f942)

We identified that the CPU was completely consumed by these queries:
```
SELECT *
FROM "metabase_field" AS "f"
INNER JOIN "metabase_table" AS "t" ON "table_id" = "t"."id"
WHERE ("t"."db_id" = $1) AND (((LOWER("f"."name") = $2) AND ((LOWER("t"."name") = $3) OR (LOWER("t"."name") = $4) OR -- ... with hundreds of other conditions
```

### 💡 What we understood
- In v50, a new table named `query_field` has been introduced and a background job aims at backfilling the table (the job starts when Metabase boots).
- This job is especially slow in our setup because our `metabase_table` and `metabase_field` tables are massive (136k resp. 3.5M rows)
- Once the job was done, we though our instance would get back on its feet, but then the queries mentioned above started (SQL analysis queries) 
- The SQL analysis code is executed on every Metabase card (and we have 40k of them)
- In addition we suspect a performance regression on the [underlying code](https://github.com/metabase/metabase/blob/93334133eabd167bbde56aa63db9b399a1a00184/src/metabase/native_query_analyzer.clj#L107C8-L115) that has been introduced in [this PR](https://github.com/metabase/metabase/pull/41781/files) (also for v50) because it breaks usage of existing indexes

### 👩🏻‍💻 What we did
- Huge clean-up of `metabase_table` (we removed all our dead tables, we went from 136k to 24k rows)
- Re-indexed `metabase_field` with simple btree indexes on `name` and `LOWER(name)` 
This worked and we are now back to our usual load. 

### 🤔 Why do we report a bug if it works now ?
We're still opening this report because:
- We think the fat WHERE clause of the SQL analysis query is sub-optimal
- We think the lack of indexes for `metabase_table` and `metabase_field` is sub-optimal
and we suspect other users of big DBs could encounter a similar issue

### To Reproduce

1. Have 136k rows in `metabase_table`, 3.5M rows in `metabase_field`, and 40k Metabase cards
2. Upgrade from 0.49.2 to v0.50.3

### Expected behavior

The backfilling of `query_field` and then the SQL analysis queries happen seamlessly without impacting perf

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9-LTS",
    "os.name": "Linux",
    "os.version": "4.14.345-262.561.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-12",
      "tag": "v0.50.2",
      "hash": "1a2c2da"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking usage of Metabase entirely

**Comment by piranha** [comment]
Hello! Wow, fantastic bug report! Thanks a lot for the analysis and for your numbers, we certainly underestimated what could be out there, I'm really sorry for this and for the time it took from you.

We've disabled SQL analysis by default in [v0.50.6](https://github.com/metabase/metabase/releases/tag/v0.50.6), so if you update there it should not bother you. We have plans re-enabling it, but we'll be more aware of the load it generates and will make sure it's contained better.
