### ISSUE TITLE
Administrators can not have access permission of connected MySQL DB 

### ISSUE THREAD

**Issue by chrinide** [metabase/metabase#4455]
I have added a mysql DB into metabase, but unfortunately, as a administrator, i can not access the DB in metabase, just show like below:

![image](https://cloud.githubusercontent.com/assets/7123439/23397672/79811724-fdd4-11e6-85bb-9e19e70e46ef.png)

The DB setup is below:
![image](https://cloud.githubusercontent.com/assets/7123439/23397735/b90d50b0-fdd4-11e6-99f4-a644c1e8085e.png)

And also I can not change the permissions.

My system is Windows 7

**Comment by chrinide** [comment]
I have tested under Ubuntu 14.04 system, the metabase work well under Linux Ubuntu, but not Windows7

**Comment by dengelke** [comment]
I have the same issue with the ElasticBeanstalk image with v0.22.2

**Comment by Micka33** [comment]
On a fresh install, just added a postgresql server.
![screen shot 2017-04-11 at 17 02 41](https://cloud.githubusercontent.com/assets/3918958/24915967/006596d2-1ed9-11e7-8d2e-ec29e8f4c567.png)

**Comment by fernandosjp** [comment]
I might be facing the same issue! As an administrator, the last database I added and my saved questions appear for me as "No access" in the permissions table. When hovering the mouse, I am not able to change the permissions for the administrator group and when I change for other groups I am not able to save the changes.

- Your browser and the version: Chrome Version 56.0.2924.87 (64-bit)
- Your operating system: Ubuntu 16.04 
- Your databases: BigQuery, Postgres
- Metabase version: 0.25.2
- Metabase hosting environment: EC2 Ubuntu
- Metabase internal database: Postgres

![image](https://user-images.githubusercontent.com/4928401/29823139-27c3e9c0-8ca4-11e7-94e7-1c19428d602e.png)

**Comment by camsaul** [comment]
@fernandosjp "Saved Questions" aren't supposed to show up in the permissions grid. We fixed that bug in 0.25.2

Everyone else: try refreshing the page after adding the new DB. We have a bug where the permissions grid doesn't work after adding a new DB until you refresh the page

**Comment by fernandosjp** [comment]
Thats is exactly the case @cumsaul. After refreshing a couple of times it comes back to normal. Thanks!

**Comment by salsakran** [comment]
this should be fixed by #5848 which is going out in the next release.

**Comment by mazameli** [comment]
Hey everyone. Just a heads up that [we've just shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
