### ISSUE TITLE
Collection permissions page not working in master

### ISSUE THREAD

**Issue by luissancho** [metabase/metabase#4456]
- Your browser and the version: Chrome 56.0
- Your operating system: OS X 10.12.3
- Your databases: MySQL
- Metabase version: metabase-head:latest
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

<img width="1216" alt="captura de pantalla 2017-02-28 a las 12 22 17" src="https://cloud.githubusercontent.com/assets/12734676/23403591/1de8b0b6-fdb1-11e6-822e-68ff5525f38e.png">

Something went wrong in the latest realease with the collection permissions page. It was working fine in previous update.

**Comment by camsaul** [comment]
@luissancho, it looks like the screenshot isn't showing up, can you post it again?

**Comment by salsakran** [comment]
@luissancho can you post the contents of your server logs and js console when this happens?

**Comment by salsakran** [comment]
reproduced it on our internal stats instance.

**Comment by luissancho** [comment]
It seems everything is working well in terms of queries. This is the log:

Mar 01 15:48:11 DEBUG metabase.middleware :: GET /api/user/current 200 (2 ms) (1 DB calls)
Mar 01 15:48:11 DEBUG metabase.middleware :: GET /api/session/properties 200 (2 ms) (1 DB calls)
Mar 01 15:48:11 DEBUG metabase.middleware :: GET /api/dashboard 200 (5 ms) (2 DB calls)
Mar 01 15:48:11 DEBUG metabase.middleware :: GET /api/collection 200 (6 ms) (2 DB calls)
Mar 01 15:48:11 DEBUG metabase.middleware :: GET /api/permissions/group 200 (6 ms) (2 DB calls)
Mar 01 15:48:11 DEBUG metabase.middleware :: GET /api/collection/graph 200 (14 ms) (4 DB calls)

Chrome dev console is showing the same.

**Comment by camsaul** [comment]
@salsakran should we add this to the 0.23.0 milestone? Don't want to ship the release knowing there are regressions
