### ISSUE TITLE
Custom Column Case Expression Doesn't Save

### ISSUE THREAD

**Issue by ccalby** [metabase/metabase#44584]
### Describe the bug

Upgraded Metabase to latest and a question no longer functions.

Appears to be due to a custom column.
This column should be
```
case([Assigned Type] = "App\Models\User", concat([Assigned To → First Name], " ", [Assigned To → Last Name]), "Stock/Location")
```

However when attempting to save, Metabase overwrites the expression to:
```
case([Assigned Type] = "App\Models\User", concat(, " ", ), "Stock/Location")
```

### To Reproduce

Attempt to create a nested concat within the case statment.

### Logs

``
"Invalid query: {:stages [{:expressions [nil [nil nil [[[nil nil [\"arguments should be comparable\"]]] [[nil nil [\"arguments should be comparable\"]]]]]]}]}",
``

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.0-56-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.37-0ubuntu0.22.04.3"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

High

**Comment by ranquild** [comment]
Based on the issue it should be this https://github.com/metabase/metabase/blob/fb4b8ca2a60fede819fff9362956941ccccadbcb/frontend/src/metabase-lib/v1/expressions/format.ts#L102 - i.e. where we cannot find the column by the field ref stored in the expression.

**Comment by ranquild** [comment]
@ccalby does the issue occur if you re-create this custom expression? Could you shot the list of columns you get when typing the expression? Are there any duplicates?

**Comment by ccalby** [comment]
> @ccalby does the issue occur if you re-create this custom expression? Could you show the list of columns you get when typing the expression? Are there any duplicates? Is your question based on a model?

@ranquild If I delete the custom column, save the question and then add the custom column back, the issue remains. The custom column is overwritten.
Regarding the columns displayed when typing the expression, the right columns come up as a selectable option - with no duplicate options.
![image](https://github.com/metabase/metabase/assets/680553/aec12f5e-8719-475e-994e-871683b0c6e9)

Question is based on a database table, not a model within Metabase :)

**Comment by ranquild** [comment]
Repro (internal):
- Open https://stats.metabase.com/model/6759
- Go to notebook
- Add custom column `concat([Assignee → ID] , "A")`
- On blur this will be converted to `concat(, "A")`

Cause `expressionClauseForLegacyExpression` -> `legacyExpressionForExpressionClause` breaks `base-type` in MBQL 
<img width="621" alt="Screenshot 2024-06-28 at 13 38 26" src="https://github.com/metabase/metabase/assets/8542534/36a28ca2-4a31-4739-8976-f6fbe1897379">
<img width="431" alt="Screenshot 2024-06-28 at 13 41 01" src="https://github.com/metabase/metabase/assets/8542534/23f8a376-43f3-4f3e-9b0d-b5bb8a277da3">

**Comment by ranquild** [comment]
Related to https://github.com/metabase/metabase/issues/44767

**Comment by Jerrylovescoding** [comment]
We have the same issues as well. After upgrading metabase from v0.49.17 to v0.50.* (even the latest v0.50.9), many custom columns in other custom columns disappear. Like this:
In v0.49.17, it is fine:
![image](https://github.com/metabase/metabase/assets/25549512/66ecc750-026d-466a-ae32-e9661f84badd)

But in v0.50.9, it is broken:
![image](https://github.com/metabase/metabase/assets/25549512/caf9750f-22a4-411e-b56a-b828d37aecfc)

**Comment by Jerrylovescoding** [comment]
> @ccalby does the issue occur if you re-create this custom expression? Could you show the list of columns you get when typing the expression? Are there any duplicates? Is your question based on a model?

@ranquild  For us, we have another weird issue. In v0.50.9, if we re-create the custom expression with a different display name, the custom column "[Net Fee]" doesn't disappear. Like this:

![image](https://github.com/metabase/metabase/assets/25549512/175034e8-7c53-426a-9897-ddb6f377a0d3)

But after changing the display name to the original name, the custom column "[Net Fee]" disappear. Like this:

![image](https://github.com/metabase/metabase/assets/25549512/0a9d9a56-774b-4695-a297-291b426d7685)

**Comment by metamben** [comment]
@ranquild's repro is caused by remapped columns incorrectly handled in saved question and model based questions. @ccalby can you tell if there are remapped fields in your setup?

**Comment by Jerrylovescoding** [comment]
@ranquild @metamben @ccalby  After upgrading to v0.50.12, this issue still exists.
![image](https://github.com/user-attachments/assets/060da105-874c-4fb3-bbb4-e776d20dcb2e)
![image](https://github.com/user-attachments/assets/af5a8d68-244f-42bd-bbef-196717221594)

**Comment by metamben** [comment]
@Jerrylovescoding do you have any errors or warning in the browser console when the custom column name disappears? (I suppose you have a problem different from what has been fixed but producing the same symptoms.)

**Comment by Jerrylovescoding** [comment]
@metamben The first snapshot below displays the errors and warnings that we get. I don't know if they are related to this issue.
![image](https://github.com/user-attachments/assets/038e6881-73b1-4172-bfaa-6def020aaa5c)


And by the way, we found the custom columns in custom column would disappear when adding the ninth custom column. (in Metabase v0.50.12)

Before adding the ninth custom column, it is normal:

![image](https://github.com/user-attachments/assets/560342cc-0e42-4648-a9f7-26afc67b888f)

But after adding the ninth custom column, the custom columns in custom column disappear:

![image](https://github.com/user-attachments/assets/178b0646-1765-4268-933c-e470aa9f2520)



> @Jerrylovescoding do you have any errors or warning in the browser console when the custom column name disappears? (I suppose you have a problem different from what has been fixed but producing the same symptoms.)

**Comment by metamben** [comment]
> And by the way, we found the custom columns in custom column would disappear when adding the ninth custom column. (in Metabase v0.50.12)

Thanks, @Jerrylovescoding, that's helpful.
