### ISSUE TITLE
[Flaky Test]: describe-fields-or-table-test

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#44597]
Last Flake: https://github.com/metabase/metabase/actions/runs/9615919843
Last Flake Time: 2024-06-22T01:03:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9965186377
Last Flake Time: 2024-07-16T16:39:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9965186377
Last Flake Time: 2024-07-16T16:39:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 1
Flakes in the last 7d: 1
