### ISSUE TITLE
Validation for Organization or Company Name during Setting Up Admin account

### ISSUE THREAD

**Issue by Rich-Edwards** [metabase/metabase#4459]
- Your browser and the version: (Mac Client)
- Your operating system: (OS X 10)
- Your databases: (N/A)
- Metabase version: (v0.22.2)
- Metabase hosting environment: (Mac app)
- Metabase internal database: (default)

When filling out the first run form to setup an admin account, validation for the field Organization or Company Name will allow for a single space, but this condition will fail to start the service (i.e. the Next button after Usage data preference throws a 400 error). Filling in any other text in that field does not cause the error and the first run process continued as in the documentation.

**Comment by salsakran** [comment]
We should consider killing that field entirely, as I don't think we use it anywhere.

**Comment by camsaul** [comment]
I believe we use that field for invite emails, e.g. "Cam invited you to join Kentucky Dept. of Highways' Metabase"
