### ISSUE TITLE
Can't deny table permissions anymore in v50.x

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#44635]
### Describe the bug

You could make granular table permissions <50 but now you can't do it anymore

### To Reproduce

1) in v50, add a new group
2) go to permissions
3) try to give a specific group access to only a specific table (you'll see only sandboxed and "can view"
![image](https://github.com/metabase/metabase/assets/1711649/35b23989-7208-4c34-81a1-6c076baa7160)

### Expected behavior

You should be able to give table level permission if the user does not have SQL access

### Logs

NA

### Information about your Metabase installation

```JSON
- 50
```

### Severity

P1

**Comment by dpsutton** [comment]
@paoliniluis Can you show how you would configure this in 1.49.x?

**Comment by paoliniluis** [comment]
The old "no self service" is now
![image](https://github.com/metabase/metabase/assets/1711649/deb8769d-6cb9-4d3c-b14a-37a88432d310)

we should reflect that on the UI or on the documentation. It's confusing that the permission is "can view" while the user can't see the table

**Comment by luizarakaki** [comment]
The permission is that the user `can view` the data. If there is a question querying that table, they can view the data but can't create queries themselves.

The setup flow is indeed weird. We are working on small changes to make it more intuitive https://github.com/metabase/metabase/issues/43193
