### ISSUE TITLE
Can't display line or bar chart for empty result set

### ISSUE THREAD

**Issue by Recursing** [metabase/metabase#44637]
### Describe the bug

After updating from 0.49 to to v0.50.6, some questions give an error when opened. After some investigation it seems that it's questions with empty resultset and a "line" or "bar" visualization.

### To Reproduce

1. Go to '+ New' => 'SQL Query', select a Postgres database
2. Enter a query with a date column and an integer columns which returns no results (example with Postgres)
```sql
SELECT '2023-01-01'::date, 2
FROM pg_type
WHERE false;
```
3. Select Visualization => Bar (or Line)
4. See error. It either shows an eternal spinner or shows "Something’s gone wrong"

### Expected behavior

It should show the usual empty results placeholder, and let you edit the question, instead of crashing.

### Logs

Sometimes I don't get any error and it just shows an eternal spinner (despite the network request completing successfully)
Sometimes I get this in the console (sometimes with includes sometimes with clone, apologies that this probably is not very useful, I hope you can easily reproduce)

![image](https://github.com/metabase/metabase/assets/6978200/a35b4163-c7e4-4b7b-b7ce-b2f4ed9d92fc)

Since the POST to `/api/dataset` completes successfully I don't think server logs are relevant, but happy to provide them if you can't reproduce.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.0-1058-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

This would be blocking a dashboard we share with users, but we have a workaround for now

### Additional context

https://github.com/metabase/metabase/assets/6978200/4ba8f4dc-cd70-4f1f-9074-327e1ae248f2

**Comment by calherries** [comment]
I can reproduce this on the release-x.50.x branch `7c779882be`
