### ISSUE TITLE
Visualization error with a custom column

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#44668]
### Describe the bug

Adding a custom column breaks visualization

<img width="1272" alt="Screenshot 2024-06-25 at 5 04 50 AM" src="https://github.com/metabase/metabase/assets/127636/2ff9d32c-d33a-49e3-8b9e-612a5bdde793">
<img width="1983" alt="Screenshot 2024-06-25 at 5 05 21 AM" src="https://github.com/metabase/metabase/assets/127636/5aec083c-b8f1-4119-bb5c-c381c32a731a">

### To Reproduce

1. Start with https://stats.metabase.com/question/18346-top-5-states
2. Add a custom column `concat([Count],"")` and call it `Count 2`
3. Sort by `Count 2` asc
4. Click on Visualize

### Information about your Metabase installation

```JSON
stats
```

### Severity

P1

**Comment by ccalby** [comment]
Related to #44584 ?
