### ISSUE TITLE
Suggestion: Creating filter selections from queries

### ISSUE THREAD

**Issue by shrike71** [metabase/metabase#4467]
More of a feature request than an issue, per se, but would it be possible at some point in the future to create a re-usable question filter whose options are from a query on an existing table in the db somewhere?

![filter](https://cloud.githubusercontent.com/assets/748514/23461852/7b2c2172-fe83-11e6-84e3-f0b98a8f964a.png)

![filter2](https://cloud.githubusercontent.com/assets/748514/23461853/7b389be6-fe83-11e6-93d7-ee423478d7e3.png)

i.e. instead of selecting an operator on an ID field, selecting one or more options from a drop-down, where the ID is provided as the data against a description line of each option of the drop-down?

Thanks,

Shrike71

**Comment by flamber** [comment]
Unless I'm misunderstanding, this is possible with remapping:
https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#remapping-field-values
