### ISSUE TITLE
No save button when user try to add a card on dashboard in IE11

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4471]
Metabase 0.23-snapshot
IE11

No save button when I try to add a card on dashboard:
![image](https://cloud.githubusercontent.com/assets/1708680/23451072/51347360-fe6f-11e6-865c-afead38fc9e1.png)

**Comment by tlrobinson** [comment]
This appears to be a combination of two things:

1. when you open a full page modal like the "add card" one, then close it (either by adding a card or clicking the "x") scrolling on the page breaks
2. when we add a new card we immediately scroll to it using `scrollIntoView`.

We should definitely try to fix the former.

For the latter I also noticed we scroll even if the new card is already visible. It would be nice if we didn't.

**Comment by tlrobinson** [comment]
At least we're not the only ones... https://connect.microsoft.com/IE/feedback/details/936231/ie11-youtube-scrolling-breaks-after-fullscreen

**Comment by attekei** [comment]
Seems that `overflow: hidden` is left to body element because `componentWillUnmount` of FullPageModal isn't properly run (see https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/Modal.jsx#L147). Any idea @tlrobinson why that might be happening? Because of all `unstable_...` React method calls in the component? :joy:

**Comment by attekei** [comment]
Checked that this is the order of some modal-related function calls:

```
AddToDashSelectQuestionModal onAdd
Triggerable HOC toggle (isOpen=false)
Routeless HOC componentWillUnmount
Modal component componentWillUnmount
```
So one other option is that either Triggerable or Routeless causing something strange that prevents the `componentWillUnmount` of Modal from running normally on IE.
