### ISSUE TITLE
Coercion strategies don't have human-friendly text in Admin Table Metadata

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#44723]
On `master` (51.x)

Admin Panel > Table Metadata > (Select any table) > (Click the Gear Icon For any Column)

The list of possible coercion strategies just uses the underlying internal names for the strategies rather than a human friendly description of them.

IIRC these used to have human-friendly names, so I think this is probably a regression.

![image](https://github.com/metabase/metabase/assets/1455846/64ce9558-15c5-4a19-83d8-3124b278915b)

**Comment by npfitz** [comment]
I went back to v45 and this is what we had. Not sure that they're more human readable, but they weren't namespaced 😂 

![image](https://github.com/user-attachments/assets/eefd2917-f561-4c5e-8432-64987fe4602f)
