### ISSUE TITLE
You cannot do a full serialization export on stats via API

### ISSUE THREAD

**Issue by piranha** [metabase/metabase#44747]
If you go to `/api/docs/`, find serialization and click `Try` without changing anything, you'll get a following message — with some toucan context, but with no actual stacktrace. [Some context](https://metaboat.slack.com/archives/C05MPF0TM3L/p1718060686322929)

```
{"lvl":"ERROR","lgr":"metabase-enterprise.serialization.api","m":"Error during serialization","exception":{"exception_class":"clojure.lang.ExceptionInfo","exception_message":null,"stacktrace":"clojure.lang.ExceptionInfo: null
```

Serializing some particular collection seems to be working — be sure to disable settings and data model export, they put quite a load on the server.

**Comment by darksciencebase** [comment]
might turn out to be a P1

**Comment by piranha** [comment]
This seems like a problem with data. Serialization tries to extract dashboard 743, which was last edited (and archived) in 2022, and its click behavior has `{linkType: "page"}`, which we do not support.

**Comment by darksciencebase** [comment]
the investigation has uncovered a slew of issues, and generally it's not great™ that we can't export stats. raising to P1
