### ISSUE TITLE
Users that upgraded to v50 receive an email with a link that goes to a 404

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#44755]
### Describe the bug

The email about permission groups goes to https://www.metabase.com/docs/latest/permissions/no-self-service-deprecated, which doesn´t exist

### To Reproduce

1) do any permission setup on v49
2) move to 50, get the email
3) click on it

### Expected behavior

We should have that page alive

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P1

### Additional context

NA

**Comment by noahmoss** [comment]
The docs location is being fixed: https://metaboat.slack.com/archives/C01R1JY03J4/p1719411982257589

**Comment by noahmoss** [comment]
Fixed via redirected
