### ISSUE TITLE
Unique constraint doesn't prevent duplicate fields for MySQL and H2

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#44771]
Follows up on [Defective fields from JSON array values still exist and can be used in questions](https://github.com/metabase/metabase/issues/44659), and has to be landed afterwards.

Duplicate fields (fields with the same name in the same table) were allowed to be created https://github.com/metabase/metabase/issues/44459 and we fixed the root cause in #44465. We have a constraint that was meant to prevent this happening, but it didn't work for MySQL and H2.

On all db types, we have a unique index on metabase_field(table_id, parent_id, name). But most fields have parent_id = null, this column is only used for nested fields on MongoDB.  And in most databases, null != null, so that’s why you can have multiple a field with the same table_id, name and not violate the unique index.
On postgres, things are little brighter because it supports partial index and we added a unique index on (table_id, name) where parent_id is null. This is why it only fails when you migrate to postgres.

### To Reproduce

1. Start from https://github.com/metabase/metabase/pull/43812 with `git checkout 33df115`
2. Use MB with a MySQL app DB
3. Create a postgres DB with this table
```
CREATE TABLE my_table (
    id serial PRIMARY KEY,
    data jsonb
);

INSERT INTO my_table (data)
VALUES ('[1, 2, 3]'::jsonb);
```
4. Sync the created DB.
5. Create a question that selects from both "Data" fields.
![image](https://github.com/metabase/metabase/assets/39073188/cf2aefee-1a48-4df8-a6cf-4991e4c5c02b)

### Expected behavior

It should be impossible to create fields with the same name on the same table, unless they are nested fields and have different `parent_id`.

### Information about your Metabase installation

```JSON
it has been this way since we introduced nested fields
```

### Severity

High, these issues block cloud upgrades

**Comment by qnkhuat** [comment]
Should be fixed as part of https://github.com/metabase/metabase/pull/44866
