### ISSUE TITLE
Add back `view_count`

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#44781]
Incrementing `view_count` for tables, cards, and dashboards was removed in [perf: disable view log and card used updates during metadata fetches](https://github.com/metabase/metabase/pull/44502/files). We need to add it back.

We will likely start using `view_count` at some point, so we want to add it back.

Epic where we added `view_count`: https://github.com/metabase/metabase/issues/38229

**Comment by qnkhuat** [comment]
We discussed using grouper as a batch processing tool in [slack](https://metaboat.slack.com/archives/C0641E4PB9B/p1719478364644629)

**Comment by qnkhuat** [comment]
Closed by [Batch processing usage metadata](https://github.com/metabase/metabase/pull/45007)
