### ISSUE TITLE
Add back `report_card.last_used_at`

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#44782]
Updating `report_card.last_used_at` for cards was removed in [perf: disable view log and card used updates during metadata fetches](https://github.com/metabase/metabase/pull/44502/files). We need to add it back.

There is ongoing work that depends on `last_used_at` ([auto cleanup collections](https://www.notion.so/metabase/Auto-cleanup-collections-54b3b58e254a48e69b26a054c84fd944)), so we want to add it back.

Epic where we added `last_used_at`: https://github.com/metabase/metabase/issues/38229

**Comment by qnkhuat** [comment]
We discussed using grouper as a batch processing tool in [slack](https://metaboat.slack.com/archives/C0641E4PB9B/p1719478364644629)
