### ISSUE TITLE
[ENHANCEMENT] When applying filters in dashboard, use all fields from linked tables

### ISSUE THREAD

**Issue by ipeevski** [metabase/metabase#4481]
When applying filters in dashboard, also show linked tables' columns, not just their ids (via foreign keys)

For example if I am showing a count of votes, which is linked to users, I would like to be able to apply a "Group" filter that filters on users.group_id

**Comment by flamber** [comment]
@ipeevski 
I'm not sure if this was a limitation in the version you tried with, but if I create custom question using the Sample database, where I select `Raw data` from `ORDERS`, and then add that question to a dashboard, and create a filter (category) on the dashboard, then I'm presented with columns from the other linked tables (in this case `PRODUCTS` and `USERS`). Tested on 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52739327-458d5180-2f96-11e9-8b76-82a937bd1da6.png)

**Comment by ipeevski** [comment]
Yes, looks like it has been addressed now. Thanks for pointing this out.
