### ISSUE TITLE
Updating filter on one dashboard automatically updates filters on other dashboards with cards referencing the same data

### ISSUE THREAD

**Issue by gloriaalt** [metabase/metabase#44858]
### Describe the bug

Updating filter on one dashboard automatically updates filters on other dashboards with cards referencing the same data. It used to not be the case. 

eg. we have sales rep dashboard for each sales rep with a text filter defaults to that sales rep's name. Recently (not sure since when), whoever opens their dashboard first would change that text filter's value to their name across all sales reps' dashboards. 

### To Reproduce

1. open a dashboard with a text filter applying to a text field of a card. The text filter value defaults to "a" in the dashboard setting.
2. open another dashboard with a text filter applying to the same text field of a different card. The text filter value defaults to "b" in the dashboard setting.
3. open the dashboard from step 1, and the text filter value now defaults to "b" instead of "a".

### Expected behavior

changing filters in one dashboard should not change filters automatically of other dashboards

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.217-205.860.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking some users

**Comment by adam-james-v** [comment]
@gloriaalt, I'm sorry you've encountered this. 
Sadly, I've not been able to reproduce this issue. 

Are you able to provide a bit more context? If it's possible do you have some screenshots showing the specifics of how you've encountered this?

**Comment by adam-james-v** [comment]
@gloriaalt , I'm curious if you've created the dashboards exhibiting this behaviour by using the 'duplicate' feature? If the answer is 'yes', then I can confirm that the linked PR above #45064 will solve this bug and should be in an upcoming v50 minor release.

**Comment by gloriaalt** [comment]
That's right - the dashboards were duplicated and then modified. Thanks for
the update!

**Comment by adam-james-v** [comment]
Thanks for letting me know. That's great news, once that PR is merged this issue should then be solved :)
