### ISSUE TITLE
Grouping by date changes to unexpected bin after clicking

### ISSUE THREAD

**Issue by pepijn** [metabase/metabase#4486]
- Your browser and the version: Chrome 56.0.2924.87
- Your operating system: OS X 10
- Your databases: H2
- Metabase version: `f2ca97244` (up to date with master as of writing)
- Metabase internal database: default

## Step 1 

We group created at by month.

<img width="761" alt="metabase" src="https://cloud.githubusercontent.com/assets/85931/23587995/050cddd2-0195-11e7-831f-edb04169e798.png">

## Step 2
Let's switch to another date field:

<img width="782" alt="pasted_image_05_03_2017__11_16" src="https://cloud.githubusercontent.com/assets/85931/23588011/3627e02e-0195-11e7-9a9f-e9dd412027f8.png">

## Step 3

Although it showed 'month' on the label, it switched to day.

<img width="789" alt="pasted_image_05_03_2017__11_17" src="https://cloud.githubusercontent.com/assets/85931/23588020/4ba547b6-0195-11e7-8c11-a606e9b8bba6.png">

# Solution

Either the label has to change or the bin that is displayed on the label should be picked instead of the unexpected one (it always picks day).

**Comment by salsakran** [comment]
This got fixed in the big query builder refactor #5134
