### ISSUE TITLE
Google Analytics: Date filter "current" use wrong dates

### ISSUE THREAD

**Issue by nordbotten** [metabase/metabase#4492]
When selecting "Current month" or "Current week" date filter inserts these settings:
start_date: "today"
end_date: (date of tomorrow)

Filter settings:
![image](https://cloud.githubusercontent.com/assets/5918267/23645266/95409db8-030b-11e7-8b83-a6852a5279d8.png)

Native query:
![image](https://cloud.githubusercontent.com/assets/5918267/23645379/0d8a40ee-030c-11e7-957b-000b1111c783.png)

**Comment by HelenMertes** [comment]
Same here, I am filtering using "after 1 June", but the query returns data from May:
![image](https://user-images.githubusercontent.com/24734846/33833684-b62ae7ee-de80-11e7-9e76-3fb99d2060b8.png)
![image](https://user-images.githubusercontent.com/24734846/33833725-da8ce27c-de80-11e7-89e8-5c467173e190.png)

**Comment by jornh** [comment]
https://metabase.com/docs/latest/troubleshooting-guide/timezones.html contains suggestions for debugging timezone related problems. According to a quick glance it doesn’t look like Google Analytics are among the data sources supporting the Metabase Timezone setting timezone.

Hoping this can help you guys to get closer to a resolution - or at least you should be able to supply more complete details related to your environment to help others look into if there is a bug.

**Comment by kristynrb** [comment]
Looks like the code that might need to be modified to fix this issue and [issue 4327](https://github.com/metabase/metabase/issues/4372) is in:  src/metabase/pulse/render.clj

If we can format that time that is returned to us from GA into UTC and convert the user's timezone to UTC and use that to compare the difference, then that should hopefully fix the problem. Unfortunately, I don't know Clojure well enough to tackle this problem.

**Comment by camsaul** [comment]
Same issue as #4327, fixed
