### ISSUE TITLE
Auto hyperlinks for unspecified columns

### ISSUE THREAD

**Issue by wvengen** [metabase/metabase#4493]
I'd love to have clickable generated links (as the result of a SQL query e.g. using `CONCAT`).

This came up before in https://github.com/metabase/metabase/issues/2791#issuecomment-268404301
Other solutions would be adding virtual/computed columns, adding a url template for a primary key column (so that its value becomes a link), or perhaps a metric with specified type (#1858).

In any case, I think having urls hyperlinked by default fits in _The Zen of Metabase_'s "Don't ask the user for information the system should already know": if something is a hyperlink, it's meant to be followed.

Suggested solution: in [frontend/src/metabase/lib/formatting.js:145](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/formatting.js#L145) format as url and email if the column has no `special_type` and it looks like one.

I'd be happy to submit a PR. **edit** see #4503

**Comment by michael-jiang** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction.

**Comment by tlrobinson** [comment]
Closing this as we currently do support it:

![screenshot 2018-04-12 10 53 36](https://user-images.githubusercontent.com/18193/38694940-c71d4320-3e3f-11e8-9b7c-4df7ffb1d4db.png)

**Comment by Crusader4Christ** [comment]
Can we change the label of link? I mean make some links like 
<a href="http://....long_ugly_url_here">pretty title here</a>
Maybe in markdown format?
