### ISSUE TITLE
How to delete dashboard what can't be open?

### ISSUE THREAD

**Issue by elfet** [metabase/metabase#4494]
I have a dashboard what when i'm trying to open fails app and redirect to main page (I'm using desktop latest version of metabase). Now i created exactly same dashboard what works fine.

How to delete first one?

**Comment by tlrobinson** [comment]
Sorry about that, it sounds like #3950 which I don't think we've been able to reproduce yet.

I think the easiest way to work around this would be to run the following in the browser developer tools JavaScript console (you'll need to copy the URL from the Mac app and open it in a browser):

```javascript
services.DashboardApi.delete({ dashId: 1234 })
```

(Obviously replace 1234 with the actual dashboard ID)

**Comment by elfet** [comment]
Thanks! How open dev tools in app on macos?

**Comment by tlrobinson** [comment]
@elfet I think you'll need to copy the URL using the Navigate menu and open it in a browser.

**Comment by elfet** [comment]
Thanks. 

PS Dash works in browser.
