### ISSUE TITLE
Date_trunc wrong month based on time zone

### ISSUE THREAD

**Issue by jamintz** [metabase/metabase#4495]
I'm trying to use the group by date -> month function but it seems to be returning the wrong (previous) month. Looking at the SQL I see it uses date_trunc('month', "public"."timeexpenses"."date").

I ran a sample query of this and got:
![image](https://cloud.githubusercontent.com/assets/3538254/23668121/16df6058-032e-11e7-94b5-513bee35496c.png)

It seems like date_trunc is resetting to March 1, then it's subtracting 5 hours for my timezone (EST) which is causing the date to appear as Feb 28, 7pm.

I can fix this in SQL by something like  date_trunc('month', ("public"."timeexpenses"."date" AT TIME ZONE 'UTC')) AS "month" which results in:
![image](https://cloud.githubusercontent.com/assets/3538254/23668162/3ff84c2a-032e-11e7-85de-7299a3835f72.png)

Unfortunately that doesn't work for most of the users on my team who want to run these queries through the UI. Is there a way to set a timezone offset for a table / field / user etc so the group by month in the UI will function as expected?

**Comment by mfpinhal** [comment]
I'm having the same issue with postgres where database timezone is not the same as metabase.

**Comment by jamintz** [comment]
Fixed this by setting my timezone in admin settings to 'database default'
