### ISSUE TITLE
Unable to connect to local postgres

### ISSUE THREAD

**Issue by benoittgt** [metabase/metabase#4497]
Hello

I'm suprised I have this issue.

I can connect locally to postgres with `psql -h myhost` or postico. But in Metabase with only database and user specified (no database url, default port) it fails : 

![capture d ecran 2017-03-08 a 13 30 00](https://cloud.githubusercontent.com/assets/8417720/23704074/62ded7f6-0403-11e7-88db-7cfc788c65de.png)

Logs : 
```
03-08 12:29:29 DEBUG metabase.middleware :: GET /api/database 200 (15 ms) (2 DB calls)
03-08 12:29:48 ERROR metabase.driver :: Failed to connect to database: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
03-08 12:29:48 ERROR metabase.driver :: Failed to connect to database: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
03-08 12:29:48 DEBUG metabase.middleware :: POST /api/database 400 (29 ms) (0 DB calls)
{:valid false,
 :dbname "org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
 :message "org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."}
```

I tried to set localhost, use 127.0.0.1... etc. Without success

- Your browser and the version: Chrome 56.0.2924.87
- Your operating system: OSX sierra
- Your databases: Postgres 9.4.5
- Metabase version: v0.22.2 (e318fee release-0.22.2)
- Metabase hosting environment: docker
- Metabase internal database: H2 (default)

**Comment by coussej** [comment]
Seems unrelated to metabase, as the error is ac TCP/IP connection refused. Have you checked everything on [this](http://stackoverflow.com/a/20830893/1682515) answer on SO?

**Comment by coussej** [comment]
Just saw you are running metabase in docker. Is postgres running on the same docker container? If not, you probably are trying to connect to the localhost of the container and not to where postgres is running.

**Comment by benoittgt** [comment]
@coussej oooh yes. You are correct. I would dig into how to make it accessible. Thanks

**Comment by coussej** [comment]
@benoittgt (this)[http://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach] would probably be a good start 😄

**Comment by leandrohmvieira** [comment]
Just had this same problem, did you find any solution @benoittgt ?

**Comment by benoittgt** [comment]
@leandrohmvieira 
If I remember (I don't use metabase locally anymore) I did something like

`host.docker.internal:5432`

Is is working?

If not maybe check https://stackoverflow.com/a/43541681/2747638

**Comment by leandrohmvieira** [comment]
@benoittgt I solved the problem yesterday by rerunning the metabase image like this:

`docker run -d -p 3000:3000 --net=host --name metabase metabase/metabase`

I lost all the changes i did on last container, but i'm ok with that.

**Comment by mnarendra333** [comment]
`add your ip in jdbc url 
spring.datasource.url=jdbc:postgresql://12.45.67.12:5432/postgres

add this conf  in pg_hba.conf file 
host all all 0.0.0.0/0 md5`

this conf is working for me

**Comment by anistark** [comment]
Update: Use `host.docker.internal` in host if you're on docker and want to connect to host network.

**Comment by sneggoroddd** [comment]
who are junior like me, that's what you do.
change
Host: localhost
on
Host: host.docker.internal
