### ISSUE TITLE
Entity picker surfaces questions that are not valid joins

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#44974]
### Describe the bug

_Arakaki comment: this is not only about recents, the collection navigation also shows questions and models in other databases ([context](https://metaboat.slack.com/archives/C0645JP1W81/p1720027645702959))_ 

When joining data in a table, the entity picker surfaces recent questions and models from different databases. 

Until we have https://github.com/metabase/metabase/issues/3953, that is always going to lead to errors, [so as @mazameli mentioned](https://github.com/metabase/metabase/issues/38989#issuecomment-2070982901), it would be better to now show these suggestions in the entity picker at all when joining.

### To Reproduce

1. Set up two databases (locally the sample database and Postgres will work for example)
2. Create a new question in the Postgres database (details do not matter) and save it as "Question A"
3. Create a new question that has a table from the Sample database as source
4. Click Join
5. The entity picker shows "Question A" under the "Recents" tab

For this issue to come up it seems like both databases need to have questions in the recents tab.

### Expected behavior

Questions, models and tables that would result in invalid joins should not be shown in the entity picker for joins.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Mac OS X",
    "os.version": "14.2.1",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-06-28",
      "src_hash": "af14ffe6d342f2c32114b0cac8d56b060c3bcd29",
      "tag": "v1.1.15-SNAPSHOT",
      "hash": "da0c9cb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

### Additional context

This issue is a follow up for https://github.com/metabase/metabase/issues/38989

**Comment by ranquild** [comment]
Caused by https://github.com/metabase/metabase/pull/29698: https://github.com/metabase/metabase/pull/29698/files#diff-2dc4d6ebb8cf3c4a3003c7b94201d62cd7f31e09239c00a28d3d984ce75acd52L55

**Comment by iethree** [comment]
FWIW, this has existed since v47, though in v47, we had a better error message

v50 | v47
---|---
![Screen Shot 2024-07-15 at 4 57 48 PM](https://github.com/user-attachments/assets/b926db94-edcb-4140-a4b6-de1decbf59aa) | ![Screen Shot 2024-07-15 at 4 38 41 PM](https://github.com/user-attachments/assets/cbde1f0c-f51e-4d15-9d4c-9fda38653d44)
