### ISSUE TITLE
OOM errors during fingerprinting

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#44983]
### Describe the bug

Some customers have OOM errors during the fingerprinting step. This issue is just to track its investigation and the fix

[Context in slack](https://metaboat.slack.com/archives/C0641E4PB9B/p1719624233280609)

### To Reproduce

NA, yet

### Information about your Metabase installation

```JSON
various
```

### Severity

high

**Comment by calherries** [comment]
I expect this to be closed by https://github.com/metabase/metabase/pull/45160, but I will wait for confirmation from @ixipixi before closing

**Comment by ixipixi** [comment]
We can confirm impacted cloud customers OOM errors resolve once 49.21 is cloud available.

**Comment by ixipixi** [comment]
@piranha this knocked out a sizable number of instances with OOM errors. There are still more OOM instances but I spot checked the 10 of the 15 and they appear to be mostly sync related. None of them appear to be fingerprint related. So I think we're good to close this one! Cal opened another one specific to the sync issues: https://github.com/metabase/metabase/issues/45163

**Comment by calherries** [comment]
Great news. Thanks
