### ISSUE TITLE
Progress vs Gauge Use cases

### ISSUE THREAD

**Issue by coussej** [metabase/metabase#4500]
I was wondering if the implementation of a gauge visualisation is still on the roadmap? I get the impression that a progress visualisation is being pushed to fill this use case, but I believe the uses are quite different.

I see there have been a couple of issues raised around this topic, and I see that there has even been done some work around them (#3149) by @mazameli ? 

![image](https://cloud.githubusercontent.com/assets/9944663/23713095/1b3159a2-0425-11e7-8ef6-cbb2950d2a71.png)

A gauge is, after a normal line chart, the most used visualisation type for the type of end-user I work with, and in 90% of the cases exactly like displayed in the image above!

Thanks for the update, and keep up the good work! Metabase is brilliant :-)

**Comment by kdoh** [comment]
Hey @coussej. We ended up implementing a simpler progress bar. You can create a progress bar by creating a query that returns a scalar value and adding a goal in chart settings. It ends up looking like this. 

<img width="1400" alt="screenshot 2017-02-15 09 18 26" src="https://cloud.githubusercontent.com/assets/5248953/22986393/360ae6c4-f360-11e6-8457-a5152ea2708d.png">

We ended up going this route to satisfy the need for showing progress without adding the additional complexity of a user having to define and specify the logic for ranges and what values correspond to those ranges. Are you specifically in need of something that has defined range values and if so would you mind chiming in a bit more about the use case?

**Comment by moumny** [comment]
This is usefull when you have operational metrics and want to show what are good values, not so good values, and bad values. (so different order of colors depending on the usecase)

**Comment by coussej** [comment]
Hi @kdoh, thanks for your interest :-) 

I want to use metabase for dashboarding on relational data in factories. For timeseries, we use Grafana, which you probably know. Next to the typical single stats and graphs, we mostly use gauges to display KPI's. Some examples of parameters:
* the OEE (overall equipment effectiveness) is a KPI that gives (as the name says) an indication on how well a production line is running. This kind of parameter is typically displayed on a gauge with a red area (bad), a yellow one (almost good) and a green one (on or above target). Grafana example: 
![image](https://cloud.githubusercontent.com/assets/9944663/23738990/829de476-049c-11e7-8380-ba3828421d30.png)

* an average quality test value: Say I want to diplay the average the average density of my last 1000 produced pieces. Typically, this would have a lower and upper treshold, and the ideal value is somewhere in the middle. Grafana example:
![image](https://cloud.githubusercontent.com/assets/9944663/23739122/2995737a-049d-11e7-9434-dbf43cb13a65.png)

For displaying these KPI's, we currently calculate them in advance and store then in a timeseries database, but with adding this kind of visualisation to metabase the flexiblity would be greatly increased, and KPI's could be calculated on the fly.

Ideally, the gage should have the following functions:
- Configurable amount of tresholds (with respective color)
- Treshold values can be assigned either by input from a static value or from query result.

I think these functions also apply as improvements on the progress visualisation. Maybe it is possible to add these functions there, and add another option to choose between the current bar and a gauge form factor by means of a checkbox? I would be willing to assist in any way I can, but for the actual implementation I'd have some skills to learn first 😅 

Thanks for your input on this!

**Comment by kdoh** [comment]
Thanks for the additional info @coussej. Really helpful.

**Comment by btrebbien** [comment]
I'm also extremely interested in this. For metrics such as cycle time where lower is better, the concept of a progress bar doesn't work as currently implemented. I use gauges as well from grafana but would love to bring this functionality into my metabase implementation.

Is there any ETA for this enhancement?

**Comment by rodrigortz** [comment]
I'm also super interested in this implementation...is this still on the roadmap? is there a timeframe?

**Comment by mnlbox** [comment]
@kdoh This issue is for more than 1 years later. Are you any plan to add gauge chart?
