### ISSUE TITLE
Recents selection context gets diluted by recently viewed items.

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#45003]
### Describe the bug

> When I open the data picker in the query builder I expect to see in Recents only stuff that I recently picked there, and nothing else.

---

We can achieve this by removing the `context=views` query parameter from the `api/actions/recents` api call used to populate the data picker.

### To Reproduce

1. Have some recent views (you can view them by hitting Cmd+K). Make some recent views by viewing ~5 collections, dashboards, cards, models, and/or tables.
2. New > Question > select something. This is the recent item that you should see as first, next time you open the data-picker.
3. Make some more recent *views* by viewing ~5 collections, dashboards, cards, models, and/or tables.
5. You will see recently _viewed_ items, not ones that you recently picked using the datapicker.

### Expected behavior

We ought to show only recent items that were recently picked there, and either nothing else, or sort the selected items first. 

Currently that view is sorted by timestamp of the most-recent view.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21+35-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21+35-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.3",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "valid-thru": "2025-01-01T12:00:00Z",
    "current-user-count": 4,
    "application-database": "postgres",
    "settings": {
      "report-timezone": null
    },
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.2 (Homebrew)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "databases": [
      "h2",
      "postgres"
    ],
    "max-users": 7,
    "hosting-env": "unknown",
    "run-mode": "dev",
    "version": {
      "date": "2024-06-27",
      "tag": "v1.2.0-SNAPSHOT",
      "hash": "2d911b9"
    },
  }
}
```

### Severity

P2

**Comment by iethree** [comment]
note: in order for the frontend to log models as recents, we need to fix the backend api: we should accept `dataset` as the model for models, not `model` 🥴
