### ISSUE TITLE
Track queries with columns that don't correspond to known `Field`s

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#45027]
See https://www.notion.so/metabase/Query-Validator-Backend-df75801389a1434c95139fa1227798bf for a discussion of the implementation ideas - we chose Option 5.

**Comment by crisptrutski** [comment]
The essential part of the schema change is that `field_id` becomes nullable, and we add a `name` field so that we can make sense of these non-resolving rows.

**Comment by crisptrutski** [comment]
It'll be important to filter out references that (could) point to cards rather than tables, to avoid false positives for bad references.
