### ISSUE TITLE
Track queries with tables that don't correspond to known `Table`s

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#45028]

**Comment by crisptrutski** [comment]
The plan to expose this data is to introduce a new `query_data_source` table which holds the name of the "table" and a nullable reference to `metabase_table`.

For future proofing to using models as sources as well, there will be a type column (`table` or `card`) and a nullable `card_id` field.

The query for the SQL validation should thus be checking `type == 'table' AND table_id IS NULL`.

**Comment by crisptrutski** [comment]
We should probably also differentiate between cases more finely.

Here is the current behavior:

 _ | No such table | Table is inactive | Table is active
--|--|--|--
No such field | *not detected* | *not detected* | *not detected*
Field is inactive | - | Field is inactive | Field is inactive
Field is active | - | - | ✅ 

I think that we should classify them as follows rather:

 _ | No such table | Table is inactive | Table is active
--|--|--|--
No such field | Table not found | Table is inactive | Field not found
Field is inactive | - | Table is inactive | Field is inactive
Field is active | - | - | ✅
