### ISSUE TITLE
Allow editing links for cells in table view

### ISSUE THREAD

**Issue by ipeevski** [metabase/metabase#4505]
Be able to define what happens when you click on a cell in any given column.
It should be a setting for the table, and configurable by column
Some options to include would be:
- Go to a particular URL, attaching the value of the cell to the end of it
- If the field is an ID or Foreign Key, go to the related record
- Open the current record
- Pass the value as a parameter to a dashboard (for example use-case, click on a user id to open a dashboard for that particular user)

**Comment by wvengen** [comment]
> Go to a particular URL, attaching the value of the cell to the end of it

Or a [URL Template](https://en.wikipedia.org/wiki/URL_Template)?

Agree that this can be a table setting, per column (without cluttering the UI).
Another, perhaps less powerful, option could be to give a URL Template for the table, which will make the ID a link (foreign keys in other tables could use that as well).

**Comment by cyberhorse** [comment]
URL Template would be great.

I think it should be per column - that will give a lot of flexibility to have a question/dashboard as a central point to other information (either within or outside of metabase)

**Comment by cyberhorse** [comment]
This should be a prerequisite to having embed-able widgets. In most cases, it won't make sense to link to a system, which users may not have access to.

Also, when specifying the URL template, it should be possible to say it should open in a new window (add target="_blank" tag)

**Comment by flamber** [comment]
Some of this is possible since 0.35 by using Custom Column with an `concat` expression:
https://www.metabase.com/docs/latest/enterprise-guide/customizing-drill-through.html

More advanced version is available in [Enterprise Edition](https://www.metabase.com/enterprise/) as [Custom Drill-through](https://www.metabase.com/docs/latest/enterprise-guide/customizing-drill-through.html)

Related #10370 #12366
