### ISSUE TITLE
Admin Settings page doesn't surface errors when saving settings

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#4506]
Some of the Settings have validators to make sure they're valid values before saving in the backend. If you save a Setting and it fails for whatever reason (such as validation failing), the saving spinner in the Settings page turns red and keeps spinning forever, but the error message is never displayed.

**Comment by robdaemon** [comment]
This appears to have already been fixed - the best setting I can make fail is the Site URL, and it does this:

![Screenshot_20200826_143744](https://user-images.githubusercontent.com/287213/91359656-d4914180-e7a9-11ea-9a89-bfe1f3c87ac5.png)

I will see if I can get a better error message there than the schema error.

**Comment by flamber** [comment]
@robdaemon Think you're right that this was mostly fixed (think it was 0.35), but some pages are not using the new forms #11659

**Comment by flamber** [comment]
@nemanjaglumac I don't think the forever-spinner has been around for several years. I would probably skip testing this.

**Comment by paulrosenzweig** [comment]
@nemanjaglumac I think replicating Rob's screenshot in a test would be valuable. That would ensure that the frontend and backend are communicating errors correctly. If something changes on one side of that e.g. `error` changes to `err`, the test would fail.

**Comment by camsaul** [comment]
@tsmacdonald has mentioned he's seeing error messages being swallowed when saving custom GeoJSON settings

**Comment by camsaul** [comment]
We'll need a new Cypress test for this page specifically I think

**Comment by nemanjaglumac** [comment]
@tsmacdonald - can you please write a few repro steps re: GeoJSON error Cam mentioned?

**Comment by tsmacdonald** [comment]
Repro:

1. Go to `admin/settings/maps`
2. Click "Add a map"
3. If you put in a URL that's not good GeoJSON the message is bad:

![image](https://user-images.githubusercontent.com/784417/105745285-bb7cf000-5f03-11eb-857e-aafff66586b7.png)


And if you put in a garbage value it's worse:

![image](https://user-images.githubusercontent.com/784417/105745343-c899df00-5f03-11eb-96a2-4a3b970ebed5.png)


And if you leave out the map name (which is required) it doesn't say anything:

![image](https://user-images.githubusercontent.com/784417/105745422-dbacaf00-5f03-11eb-9740-e6a345ad9a16.png)

**Comment by flamber** [comment]
Closing in favor of #14635
