### ISSUE TITLE
Relative date filter on query result (not from an existing field)

### ISSUE THREAD

**Issue by benjR** [metabase/metabase#4507]
Hi,

I'm trying to use the result of a mysql query with the variables (the relative date one) but without success, is there a way to accomplish this ? I'm rebuilding a date from several fields like this :

`SELECT count(*), CONCAT(t.col1,'-',t.col2,'-',t.col3,...) as rebuiltDate`

When creating the relative date variable, I can't see the rebuiltDate from my query, is that something doable ?

Thanks

**Comment by salsakran** [comment]
Not sure what you're trying to do based on the example you give.

In this case "rebuiltData" is an alias or label for the result column, not a variable in the context of Metabase SQL templates. 

Can you elaborate on what you're doing, what you're seeing and what you expect to see? It would also be easiest if you give us SQL queries against the sample database so we can try to reproduce it on our end .

**Comment by salsakran** [comment]
@benjR, can you give more context to the problem you're having?

**Comment by benjR** [comment]
Sorry for the delay...
My problem is (and sorry if it's more SQL related than metabase) : 

- I'm dealing with some dirty tables where I don't directly have a date field clearly identified and foramtted
- I have a series of columns where I can extract the year/month/day
- The result of my query contains something that I'm making look like a date (by using a concatenation of several fields)
- I would like want to use the variables/filters to have Last 30 days, yesterday, today or even a range date

Is this even possible? 🙈
