### ISSUE TITLE
Decouple MB_UNAGGREGATED_QUERY_ROW_LIMIT from FE rendering (subscriptions issue)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#45078]
**Is your feature request related to a problem? Please describe.**
At some point in the past we decided that we would use this variable to allow users to get all the results in the attachments on subscriptions. But also this env var is used to set how many items get back on API calls, which means that now the FE will need to render more items if the env var is raised.

**Describe the solution you'd like**
Decouple these 2 things:
1) allow users to get all items on the attachments while
2) have the normal Metabase behavior on the FE (max 2K or more items, if defined)

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by a customer who now has performance regressions on the FE

**Additional context**
There's also a bug:
![image](https://github.com/metabase/metabase/assets/1711649/26d90147-7f19-453e-bc85-285722864c22)

**Comment by adam-james-v** [comment]
Closing as https://github.com/metabase/metabase/pull/46401 provides this
