### ISSUE TITLE
Can't load schema of database in Spark SQL

### ISSUE THREAD

**Issue by lakechain** [metabase/metabase#45086]
### Describe the bug

I'm using latest version of Metabase and use SparkSQL to connect to data warehouse
![image](https://github.com/metabase/metabase/assets/171651073/a4813af0-a07e-42a6-befe-bb32851865ce)

although I can use SQL to show the schemas in the warehouse like this

![image](https://github.com/metabase/metabase/assets/171651073/38311ad5-c38d-465a-a669-65de3428e1d6)

But when I access the browser database I don't see any schemas or tables, even when I use the Sync database and schemas function in the admin section.

![image](https://github.com/metabase/metabase/assets/171651073/059423a4-0625-44d5-99c8-03273d961edf)

### To Reproduce

1. Go to Admin page
2. Click on database and create database
3. Input connection info of Spark SQL
4. Back to browser database and can't see any schema???

### Information about your Metabase installation

```JSON
- Browser: Chrome Version 126.0.6478.126 (Official Build) (64-bit)
- OS: Ubuntu 20.04
- Database: SparkSQL
- Metabase version: 0.50.8
- Metabase hosting environment: Docker
- Metabase internal database: postgres
```

### Severity

The error is quite serious as I cannot explore my data and view the schemas or tables in my warehouse.

**Comment by tsmacdonald** [comment]
Hi @lakechain , do you see anything about the Database Sync for this DB happening in `/admin/troubleshooting/tasks` ? It'd be helpful to know if the issue is the sync not running, the sync failing, or the sync allegedly succeeding but not populating things correctly.

**Comment by calherries** [comment]
@lakechain I tested syncing the test database we have for Spark on 50.8, and the tables are syncing fine, so this is likely something specific about your setup. Can you:
1. go to the Databases page for that database in Admin Settings and click "Sync database schema now"
2. go to Admin Settings > Troubleshooting > Logs and copy+paste the log messages made during the database sync?
The database logs for syncing database schema should start with something like this:
```
2024-07-03 18:04:53,996 INFO sync.util :: STARTING: Sync sparksql Database 1 ''test-data''
2024-07-03 18:04:53,997 INFO sync.util :: STARTING: Sync metadata for sparksql Database 1 ''test-data''
...
```

**Comment by lakechain** [comment]
@calherries @tsmacdonald table sync is fine, but schemas are not. And I don't understand why Database name is required, in Spark SQL, Schema and Database are one, so when I enter database name as "default", no tables appear in the Database browser of metabase, but when I enter the name of a schema in the database name input, the tables of that schema appear in the Database browser.
How can I display all schemas (databases) in my warehouse on the database browser of Metabase?

**Comment by calherries** [comment]
Ah yes, now I understand. Having to specify a single schema is indeed a limitation of the Spark driver. Can you confirm whether [this issue](https://github.com/metabase/metabase/issues/13763) represents the solution you'd like? 

Specifically:

> if you leave the database blank, the UI will show the metadata from all databases.

**Comment by lakechain** [comment]
Maybe that's what I need.
But I read in the SparkSQL connector documentation. I see that the database name is not required. https://www.metabase.com/docs/latest/databases/connections/sparksql

**Comment by lakechain** [comment]
@calherries I can't leave the database blank, it's required, Is this a bug?
![image](https://github.com/metabase/metabase/assets/171651073/08c00203-a33c-4997-9911-c7d9408f4f74)

**Comment by calherries** [comment]
I'm not sure it's a "bug" or a flaw in the design. As you said before:

> when I enter the name of a schema in the database name input, the tables of that schema appear in the Database browser.

Is it a feasible workaround to create a database in Metabase for each database/schema in your Spark SQL database?

**Comment by lakechain** [comment]
In the document I don't see anything that says I need to input a database name. I'll try some ways to see if I can get around it, thanks for your help.

**Comment by calherries** [comment]
Thanks, please update this issue if you find the workaround satisfactory. Given you and a few others are obviously having issues with this, I will see if there's an easy way to fix this limitation. No promises though! There might be a good reason for this

**Comment by darksciencebase** [comment]
@lakechain did the workaround work for you?

**Comment by lakechain** [comment]
@darksciencebase I am having to create a database for each schema in the data warehouse. This is probably the best way possible.
