### ISSUE TITLE
Table schema not refreshing if the table visibility is set to hidden

### ISSUE THREAD

**Issue by kaiks** [metabase/metabase#45085]
### Describe the bug

I'm using Metabase 0.50.6 and Snowflake as the database. I couldn't find a matching issue.

The table does update immediately after setting visibility to Queryable, which leads me to believe this is strictly tied to table visibility. The same issue does not happen for tables that are always queryable.

### To Reproduce

1. Create a new table in snowflake
2. Make sure the schema is synced to metabase
3. Set the table visibility to hidden in metabase
4. Change the table schema (rename a field)
5. The table doesn't update in metabase no matter what I do (cache dropping, rescan, sign in/out, wait 12h)

### Expected behavior

the table schema updates either immediately, shortly after the schema change, or at least upon manually rescanning the schema

### Information about your Metabase installation

```JSON
- Metabase version: 0.50.6
- Database: Snowflake
```

### Severity

annoying

### Additional context

The rescan query itself is executed after I manually trigger it:

> [6f056a24-7796-4859-89b7-06a0edf3d698] 2024-07-03T11:24:15+02:00 DEBUG metabase.server.middleware.log POST /api/table/67/rescan_values 200 4.7 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (2 idle, 0 queued) (104 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 20}

but does not update the schema if the table is hidden

**Comment by Tony-metabase** [comment]
That is expected. If you mark it as hidden ... You can mark it as visible and the scan will pick the table up

**Comment by kaiks** [comment]
Is this behavior documented somewhere? Should we disable scanning hidden tables, if it deliberately does not do anything? (or, preferably, change the behavior so that it still does update; after all, why would it not?)

**Comment by Tony-metabase** [comment]
Hidden tables should not be synced or scanned for reference:

https://www.metabase.com/docs/latest/databases/sync-scan#disabling-syncing-and-scanning-for-specific-tables

**Comment by kaiks** [comment]
Okay, thanks. I might create a feature request ticket later for a way of hiding tables but still keeping them in sync.
