### ISSUE TITLE
Upgrade to v50 where Permissions are Mapped to "No self-service (deprecated)" Blocks View Access to Other Data in the Database

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#45116]
### Describe the bug

Upgrading from v49 to v50 with "No Self Service" in play can cause other schemas to be blocked (tested with Snowflake - didn't attempt to replicate with other DBs).

### To Reproduce

1. In v49 set up a Snowflake Connection that contains at least 2 schemas
2. Set all user to "Block"
3. Create a test user and assign them to a test group
4. For the group assign one of the schemas in Snowflake to "No Self Service" and the other to "Unrestricted"
5. Create a test Question from each schema and place it in a collection the group has view access to (confirm user can access both questions before upgrade)
7. Upgrade to v50
8. Note the permissions map correctly
9. Note that test user cannot view Questions from either schema even though they have "Can View" data permissions

Loom recording: https://www.loom.com/share/4b4154c362e342ba9811addaf7c62a18

### Expected behavior

If the user has "View Data" permission they should be able to view the questions

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-28",
      "tag": "v1.50.8",
      "hash": "dc9e68b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Severe

**Comment by kbrownlees** [comment]
We just hit this upgrading to 0.50 from 0.49 as well. All out permissions are broken, to the point where I can't event save a question I am currently looking at (and running): https://www.loom.com/share/f8e2060528264e718dda59508478c7f3
