### ISSUE TITLE
Can't Remove Dashboard Sole Tab Name in Pulse

### ISSUE THREAD

**Issue by ojjj13** [metabase/metabase#45123]
### Describe the bug

For a dashboard that previously added new tabs, after removing all tabs but the last one, the pulse still attaches that last tab's name. 

### To Reproduce

1. Create a new dashboard.
2. Add a random question.
3. Create a new tab, save, then remove the new tab.
4. Email that dashboard.
5. Email shows 'Tab 1' under dashboard title.

### Expected behavior

It should not show tab's name if there is only one tab.

### Information about your Metabase installation

```JSON
"version": {
      "date": "2024-07-02",
      "tag": "v0.50.9",
      "hash": "720e549"
    },
```

### Severity

Mild

**Comment by alxnddr** [comment]
@cdeweyx what do you think about the issue? Maybe we can omit the tab name in subscriptions only if it is the only tab

**Comment by ojjj13** [comment]
> @cdeweyx what do you think about the issue? Maybe we can omit the tab name in subscriptions only if it is the only tab

Or give user ability to change the tab name?

**Comment by cdeweyx** [comment]
> Maybe we can omit the tab name in subscriptions only if it is the only tab
Yeah we should omit tab name if there's only one tab
