### ISSUE TITLE
I can not find oralce in Database Type

### ISSUE THREAD

**Issue by lostwing** [metabase/metabase#4513]
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

### Database support
If there's an exisiting issue, please add a +1 in the comments as we
prioritize drivers by the level of support. Otherwise, please include the name
of the database and the version.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by salsakran** [comment]
We can't redistribute oracle drivers, so you'll need to follow the directions at 
http://www.metabase.com/docs/latest/administration-guide/databases/oracle.html
