### ISSUE TITLE
subscribe to a dashboard with charts, the mail received has Changed chart's size and settings.

### ISSUE THREAD

**Issue by ErezBlockTemin** [metabase/metabase#45130]
**Describe the bug**
When sending dashboard charts via email subscriptions and then converting them to Slack reports, I am noticing unintended changes in the dashboard’s appearance and functionality. These modifications include resizing of the charts, conversion of data from raw numbers to percentages, and changing from line charts to bar charts. These transformations often compromise the original design and clarity of the dashboard, affecting the overall understanding of the data presented.

link to the report 
https://metabase.voyantis.co/dashboard/124-predictions-dashboard-mosh?product_id=mosh&version=2&cohort_dates=2024-01-01~2025-01-

01&action_id=&run_id=&prediction_target=intent%20with%20PMI%20to%20LTV&action_type=Foresight&iw_days=7&iw_hours=&horizon=30&raw%252Fpmi=PMI&is_matured=true&exclude_backfills=&cv_buckets=10&cohort_dates_(cv2)_=&birds_segment=&segment_name_1=&segment_value_1=&segment_name_2=&segment_value_2=&segment_name_3=&segment_value_3=
**Expected behavior**
The behavior is that I don't want the change happening in the visualization. I added pictures 
**Screenshots**
![Screenshot 2024-07-04 at 15 23 52](https://github.com/metabase/metabase/assets/162147634/61fcf01b-9717-4532-9971-1c9939ad60ab)
![Screenshot 2024-07-04 at 15 23 59](https://github.com/metabase/metabase/assets/162147634/530c8ac5-19d6-4992-b46a-b02d36cc7743)
![Screenshot 2024-07-04 at 15 24 07](https://github.com/metabase/metabase/assets/162147634/84938ffb-be03-485c-acda-c86e219f6b08)
![Screenshot 2024-07-04 at 15 27 03](https://github.com/metabase/metabase/assets/162147634/c29fc01f-fb84-4ccd-8fef-b47365db801a)
![Screenshot 2024-07-04 at 15 27 12](https://github.com/metabase/metabase/assets/162147634/404ed04a-b70a-4ce7-9755-881109807a2d)
![Screenshot 2024-07-04 at 15 27 18](https://github.com/metabase/metabase/assets/162147634/fb8f9793-5f6b-4049-9f13-1ccff986bdc5)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.218-208.862.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-23",
      "tag": "v0.49.12",
      "hash": "77e7a81"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by alxnddr** [comment]
Hey @ErezBlockTemin 👋 We've reworked line, bar, area, combo, scatter, waterfall charts entirely in v50 and one of the goals was to make the email/slack versions of them look exactly as what you can see in the app. This already should've been fixed in the latest version but if not please let us know. As for resizing, emailed charts may have different dimensions but this is needed to make emails readable, otherwise some labels may look very tiny
