### ISSUE TITLE
Downloads from public questions or dashboards are not logged

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#45147]
### Describe the bug

Logging of downloads from publicly shared questions do not appear to work. The download events do not show up in `v_query_log`.

### To Reproduce

Enable public sharing for a question. Open it, and download data as csv / json / xlsx. 
The view event is logged, however the download event does not show up in Metabase Analytics / `v_query_log` .

### Expected behavior

We should log these events as well.

### Logs

n/a

### Information about your Metabase installation

```JSON
v50.8
```

### Severity

P2

**Comment by adam-james-v** [comment]
@zbodi74 , can you clarify this:

> Downloads from publicly shared dashboards or questions do not work.

Do you mean that the downloads are failing? 
Or is it simply that the (successful) download is not being logged?

**Comment by zbodi74** [comment]
Hi, sorry, corrected the description. The issue is only the (successful) downloads are not being logged.

**Comment by notrom** [comment]
Are downloads of question data to CSV/xlsx from a public shared dashboard available? It doesn't appear as an option for me but I'd love to be able to do it. Reading this issue makes me think it should be working, am I missing something?

Dashboard question when logged in:
![image](https://github.com/metabase/metabase/assets/4504437/f5afc348-9c25-41e8-a57e-eab05e001dc1)

Same dashboard question when public shared:
![image](https://github.com/metabase/metabase/assets/4504437/dd3c2f77-825d-45ae-b41a-c4ecb2e4f281)

v0.50.10

Old open issue asking for this https://github.com/metabase/metabase/issues/6687

**Comment by zbodi74** [comment]
@notrom - apologies for the incorrect title, fixed it, this applies only for individual questions, not dashboards.

**Comment by tom-vpj** [comment]
@notrom im having the same issue
