### ISSUE TITLE
Exception in thread "Timer-1" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#4514]
I run a docker image on a digital ocean 40$ vm (2 cores, 4GB RAM), but recently I usually got the unresponding situation of metabase (it just loads forever).
Check the docker log, I got the error: "2017-03-13T02:49:50.457355636Z Exception in thread "Timer-1" java.lang.OutOfMemoryError: Java heap space"

Is there any way to trace/debug more info about this error or how to fix it ?

Thanks

**Comment by marcoruggine** [comment]
We have the same exact error on queries that used to run under 1 second.
This is our setup:
Docker version 1.12.5, build 7392c3b
Linux 4.4.0-53-generic #74-Ubuntu SMP x86_64 GNU/Linux
VM with 4GB

Right now this error is blocking almost every query we try to run.

**Comment by salsakran** [comment]
Was this after an upgrade? Did the server restart or otherwise change?

Also, what jvm version + Metabase are you guys running?

**Comment by marcoruggine** [comment]
Hi @salsakran, yes this happened after upgrading to the latest Metabase version.

We tried restarting the server a few times but nothing happend, now we upgraded the server and it's always a 2 core but with 8GB ram but we're still having the same issue though.

**Comment by camsaul** [comment]
@marcoruggine what JVM options are you setting? Does Digital Ocean set any defaults?

**Comment by marcoruggine** [comment]
We didn't set any particular setting, we run it with this:
docker run -d -p 3000:3000 -e "MB_DB_TYPE=postgres" -e "MB_DB_DBNAME=metabase" -e "MB_DB_PORT=5432" -e "MB_DB_USER=puc" -e "MB_DB_HOST=*.*.*.*"  metabase/metabase

**Comment by camsaul** [comment]
@marcoruggine you probably just need to set some JVM options to let it know explicitly how much memory it should use for the heap space. On other shared hosting instances I've seen a few cases where the JVM doesn't automatically choose sensible limits.

Something like

```
-Xmx2g
```

is more than enough but if you're running an instance with 8 GB of RAM then you could opt for something higher like `4g` if you want.

Let me know if that solves your issues.

**Comment by camsaul** [comment]
@marcoruggine let me know if that works for you

**Comment by marcoruggine** [comment]
@camsaul I've asked my colleague to try your solution, as soon as I have a feedback I'll get back to you.

**Comment by thucnc** [comment]
@marcoruggine may you share how to config `-Xmx2g` in docker instance ? Thanks.

**Comment by marcoruggine** [comment]
@thucnc all we do is this:
`docker run -d -p 3000:3000 -e "MB_DB_TYPE=postgres" -e "MB_DB_DBNAME=metabase" -e "MB_DB_PORT=5432" -e "MB_DB_USER=puc" -e "MB_DB_HOST=*.*.*.*" -e "JAVA_TOOL_OPTIONS=-Xmx2048m" metabase/metabase`

**Comment by camsaul** [comment]
@thucnc since you added a 👍  to @marcoruggine's post it sounds like this fix worked for you, right? If so, feel free to close this issue again

**Comment by camsaul** [comment]
@thucnc it sounds like this worked for you so I'm going to go ahead and close this out

**Comment by camsaul** [comment]
Added some documentation [here](https://github.com/metabase/metabase/blob/master/docs/operations-guide/start.md#metabase-fails-to-start-due-to-heap-space-outofmemoryerrors) and [here](https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-metabase-on-docker.md#fixing-outofmemoryerrors-in-some-hosted-environments) for anyone else who runs into this issue

**Comment by swatisinghi** [comment]
My metabase server keeps running out of memory and stopping. I have given a lot of memory to the process
`java -Xms14336m -Xmx14336m -jar metabase/metabase.jar`

Stack trace
```
Exception in thread "qtp156797912-1379" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at sun.misc.IOUtils.readFully(IOUtils.java:60)
        at java.util.jar.JarFile.getBytes(JarFile.java:425)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
        at java.util.jar.JarFile.getManifest(JarFile.java:180)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:981)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
```
