### ISSUE TITLE
OOM errors during JSON unfolding

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#45163]
### Describe the bug

Some customers have OOM errors while inferring the schema of a JSON column during the sync-fields step. This issue is just to track its investigation and the fix.

[Context in slack](https://metaboat.slack.com/archives/C0641E4PB9B/p1719624233280609)

### To Reproduce

NA

### Information about your Metabase installation

```JSON
NA
```

### Severity

high

**Comment by qnkhuat** [comment]
Reopening as it's not fully resolved, see this discussing [thread](https://metaboat.slack.com/archives/C0641E4PB9B/p1722607969980679)

**Comment by calherries** [comment]
false alarm, that was before this change landed
