### ISSUE TITLE
Creating a new folder on the snippet menu will use the new entity modal which suggests collections

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#45161]
### Describe the bug

The folder picker in the snippet view is the new entity picker modal, which was made for collections
![image](https://github.com/metabase/metabase/assets/1711649/a34586ed-d204-4d74-b967-01cebcdc2669)

clicking on "create a new collection" will actually create a collection and not a folder, and then selecting a collection to save a snippet will end up in a failed api call

### To Reproduce

Just try to create a snippet and select the folder where you want the snippet to live

### Expected behavior

we should either return to the old modal there or allow the new picker to create folders

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P1

**Comment by paoliniluis** [comment]
it seems that the modal works, but suggest collections as well, so we should make very slight changes

**Comment by npfitz** [comment]
@paoliniluis I believe this was resolved by https://github.com/metabase/metabase/pull/45477, Which solved the "Create New Collection" bug and removed the recents tab from that particular modal. Can you confirm that the recents tab was what was suggesting incorrect collections for you?
