### ISSUE TITLE
No more new records produced in table "view_log" after upgrading metabase to v0.50.9

### ISSUE THREAD

**Issue by Jerrylovescoding** [metabase/metabase#45170]
### Describe the bug

After upgrading metabase to v0.50.9 and v0.50.10, no more new data produced in table "view_log", the system table of metabase.

### To Reproduce

1. Viewing any reports on metabase.
2. Checking if the metabase system table "view_log" produces the newest records.

### Information about your Metabase installation

```JSON
* Metabase hosting environment: CentOS, Docker
* Metabase internal database: Postgres
* Metabase version: v0.50.9 and v0.50.10
```

### Severity

Low

**Comment by luizarakaki** [comment]
This change was announced on v49 but only implemented on v50: `view_log` is not populated anymore on the community version.

**Comment by mikmack** [comment]
I was using this table to monitor the number of users and their departments...
Do you know what are the workarrounds to keep this monitoring ?

**Comment by paoliniluis** [comment]
@mikmack number of users and departments, you have core_user and groups tables
