### ISSUE TITLE
Questions become broken with missing field if a table is deleted from the schema (and later recreated)

### ISSUE THREAD

**Issue by kristian-elder** [metabase/metabase#4517]
We sometimes drop a table in the database and then recreate it - as part of a job that creates tables for reporting. It appears that, when metabase inspects the schema and see the table as missing, all questions that used it as a foreign key get broken and show "missing field" where the filters or groupings were.

I see no way of getting the original definition of the question so need to guess what was originally used in order to recreate the query. It is also not possible to convert to SQL in this state.

1) Is this expected behaviour?
2) Is there a way of re-creating the questions once the table has been resurrected?
3) Alternatively as a workaround, is there a way to turn _off_ automatic import of the schema in Metabase so that it never gets a chance to see tables like these as deleted (then manually trigger sync only in a safe state).

Cheers,
Kristian

**Comment by camsaul** [comment]
This is the same issue as #3331 (fix shipping in next release) closing as a duplicate
