### ISSUE TITLE
Issue with Card API with parameters

### ISSUE THREAD

**Issue by leenasn** [metabase/metabase#4519]
I am trying the below curl command to download the card data as JSON:

```
curl -X POST \ 
  -H "Content-Type: application/json" \
  -H "X-Metabase-Session: session" \
  'https://myurl/api/card/55/query/json?parameters="{\"studio\":\"1\"}"'

```
Studio is the parameter am expecting for the card.

I am getting the below error.

{"message":"Assert failed: (u/maybe? sequential? parameters)"

When I use the below curl command, I get a different error i.e. "Malformed JSON in request body"

```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "X-Metabase-Session: d3d33e3b-c2ae-4a9d-bbd3-bc6da99e8fa4" \
  -d 'parameters={"Studio": "1"}' \
  https://gk-production-analytics.herokuapp.com/api/card/55/query/json

```
Can someone help me to fix it? 

The API works fine when I don't have parameters

**Comment by camsaul** [comment]
That's the wrong syntax for parameters (hence the error message), take a look at the way the requests look when issued by the Metabase frontend in your browser console to get a feel for how they should look

**Comment by leenasn** [comment]
Thank you @camsaul. I got it working by looking at the browser console.

**Comment by ddduarte** [comment]
@leenasn Please, help me, I getting same error. Can you post a example of curl request for me?

**Comment by tobyhinloopen** [comment]
For future readers, I'm using something like this to convert a JS object of params to a request body:

```typescript
const params: { [key: string]: string } = { something: "1", other: "2" };

const parameters = _.toPairs(params).map(([key, value]) => ({
  type: "category",
  target: ["variable", ["template-tag", key]],
  value,
}));

const body = "parameters=" + escape(JSON.stringify(parameters));

fetch(`${this.endpoint}/api/card/${id}/query/json`, {
  method: "POST",
  body,
  headers: {
    "Content-Type": "application/x-www-form-urlencoded",
    "X-Metabase-Session": sessionId,
  },
})
```

To clarify: The POST params expects a form urlencoded body with a key called "parameters" and a value of stringified JSON, containing your params as an array of `{ type: "category", target: ["variable", ["template-tag", "--KEY--"]], value: "--VALUE--" }`

**Comment by jkramp** [comment]
@tobyhinloopen  Amazing thanks. This saved me. Was going bonkers on how to do this
