### ISSUE TITLE
Athena connection constantly syncing

### ISSUE THREAD

**Issue by james-n-centric** [metabase/metabase#45208]
### Describe the bug

After creating an Athena connection, Metabase is issuing an endless stream of queries to Athena. I have not created any dashboards or models. The Athena queries run every few seconds, incurring read costs each time. Over the course of 48 hours 1000's of queries where issued by Metabase generated over 200GB of data in the Athena results folder with no human interaction. I'd expect these queries to stop once Metabase has synced under underlying data model but they did not stop until I deleted the db connection.  

### To Reproduce

Add new Athena db using the following params:
Database Type: Amazonf Athena
Display name: test
Region: eu-west-1
Workgroup: Primary
S3 Staging Directory: xxxxxx-datalake-athena
Catalog: AwsDataCatalog
Access Key: xxx
Secret Key: xxx
Include User ID and query hash in queries: false
Rerun queries for simple explorations: false
Choose when syncs and scans happen: false
Periodically refingerprint tables: false

### Expected behavior

The connection should not keep running queries against Athena - once sync has completed this process should stop. Every query running against Athena costs $$.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "22.0.1+8-16",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "22.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "22.0.1+8-16",
    "os.name": "Linux",
    "os.version": "6.1.94-99.176.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

High

**Comment by qnkhuat** [comment]
@james-n-centric can you get us a dump of running this query?
```sql
select task, started_at, duration, ended_at  from task_history where db_id = <your-athena-db-id> order by started_at desc;
```
You should be able to get your athena DB by checking the URL when visiting your db in admin panel.

My suspect is that scanning field values is super slow. You can try turning it off in the advanced setting like so
![Screenshot 2024-07-09 at 15 57 45](https://github.com/metabase/metabase/assets/25661381/7650893e-3ab8-41ca-82b9-16e346fcc0ce)

**Comment by james-n-centric** [comment]
Thanks for looking at this.

I made a new connection to Athena today at [2024-07-09 15:32:46.872 +0100] UK

The is the dump from task_history after 15 mins:

"task","started_at","duration","ended_at","db_id"
update-field-values,2024-07-09 15:38:25.321 +0100,,,7
delete-expired-advanced-field-values,2024-07-09 15:38:13.279 +0100,12032,2024-07-09 15:38:25.311 +0100,7
field values scanning,2024-07-09 15:38:13.208 +0100,,,7
classify-tables,2024-07-09 15:38:10.116 +0100,448,2024-07-09 15:38:10.564 +0100,7
classify-fields,2024-07-09 15:37:46.671 +0100,23432,2024-07-09 15:38:10.103 +0100,7
fingerprint-fields,2024-07-09 15:33:01.680 +0100,284970,2024-07-09 15:37:46.650 +0100,7
analyze,2024-07-09 15:33:01.671 +0100,308900,2024-07-09 15:38:10.572 +0100,7
sync-table-privileges,2024-07-09 15:33:01.198 +0100,12,2024-07-09 15:33:01.210 +0100,7
sync-metabase-metadata,2024-07-09 15:33:01.174 +0100,14,2024-07-09 15:33:01.189 +0100,7
sync-indexes,2024-07-09 15:33:01.156 +0100,9,2024-07-09 15:33:01.166 +0100,7
sync-fks,2024-07-09 15:33:01.008 +0100,137,2024-07-09 15:33:01.145 +0100,7
sync-fields,2024-07-09 15:32:48.198 +0100,12796,2024-07-09 15:33:00.994 +0100,7
sync-tables,2024-07-09 15:32:47.089 +0100,1102,2024-07-09 15:32:48.191 +0100,7
sync-timezone,2024-07-09 15:32:47.009 +0100,24,2024-07-09 15:32:47.034 +0100,7
sync-dbms-version,2024-07-09 15:32:46.910 +0100,73,2024-07-09 15:32:46.983 +0100,7
sync,2024-07-09 15:32:46.872 +0100,14741,2024-07-09 15:33:01.614 +0100,7

Athena show queries being issues almost constantly:

![image](https://github.com/metabase/metabase/assets/173671402/73a8e078-fd4e-4511-8854-23befdd3708d)

I tried to set the Scan setting as you showed, but nothing has changed so far.

**Comment by qnkhuat** [comment]
These queries are part of our sync field values process to power filter dropdown.

> I tried to set the Scan setting as you showed, but nothing has changed so far.

If you don't want this process to run, you should uncheck the option before creating the database.

Though this sync performance is unacceptable, we'll create another issue for it.
