### ISSUE TITLE
Unsupported function offset `Offset` Function in Metabase Query Builder 

### ISSUE THREAD

**Issue by DieudonneCesar** [metabase/metabase#45204]
### Describe the bug

I am encountering an issue where the `Offset` function does not work as expected in the Summarize step of the Metabase Query Builder. When attempting to use `Offset` to access values from previous or next rows based on the current row, it either results in an error is returned, contrary to the expectations set by the official Metabase documentation.

**Actual Behavior**:
The function does not return an error

**Metabase Version**:
v0.50.8

**Additional Information**:
Any other details that might be helpful for the developers to diagnose the issue, such as the browser used, specific settings in Metabase, or screenshots depicting the problem.

### To Reproduce

1. Open Metabase and navigate to the Query Builder.
2. Select the `your-table` table.
3. Set up an aggregation to calculate the sum of the `Total` column.
4. Apply `Offset(Sum([Total]), -1)` to attempt retrieving the sum from the previous row.
5. Observe that the output does not match expected results or an error message is displayed.

### Expected behavior

The `Offset` function should return the sum of `Total` from the previous row according to the documentation but i have:

![image](https://github.com/metabase/metabase/assets/123993587/1e3f7d6f-6419-47f6-8962-69a3dcadc538)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.146.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-28",
      "tag": "v0.50.8",
      "hash": "dc9e68b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking my usage

**Comment by uladzimirdev** [comment]
@DieudonneCesar are you sure you're running 50.8? I just checked it and there is no issue in offset function usage.

<img width="1451" alt="image" src="https://github.com/metabase/metabase/assets/125459446/53ed255a-5465-4c14-bc4e-a797baf37c26">

**Comment by uladzimirdev** [comment]
if there is any error in the browser console, could you please also paste it?

**Comment by DieudonneCesar** [comment]
After several tests, it appears that the Offset function works perfectly with Metabase's sample database. However, when using my own MySQL 8.3.0 database, the problem occurs. Can anyone help me?

**Comment by uladzimirdev** [comment]
@DieudonneCesar how did you solve the issue? I checked 50.8 and offset function is available there

**Comment by DieudonneCesar** [comment]
> @DieudonneCesar how did you solve the issue? I checked 50.8 and offset function is available there

Refere to this issue https://github.com/metabase/metabase/issues/42908

I didn't know MySQL doesn't support offset function

**Comment by uladzimirdev** [comment]
indeed, it's not atm 
<img width="846" alt="image" src="https://github.com/metabase/metabase/assets/125459446/7cffe557-21a2-4091-81a6-993bd37b8605">

**Comment by Jianbin719** [comment]
Looking forward to the same for me.

**Comment by synque-dev-admin** [comment]
Looking forward to this function
