### ISSUE TITLE
Snowflake regextract no longer working

### ISSUE THREAD

**Issue by nmeneil** [metabase/metabase#45206]
### Describe the bug

We have just upgraded to v0.50.6 ( and v0.50.10) using the docker image, when creating a custom column using the below expression:

substring(regexextract([Tags], "\"Name\":\"((\\\"|[^\"])*)"), 9, 60)

we're now getting "Invalid expression". I can't remember the exact version we were on but I believe it was v.0.48. I've also tried the sample from the documentation regexextract([Tags], "^[^?#]+\?utm_campaign=(.*)") and that gives the same error

[This has more details](https://discourse.metabase.com/t/snowflake-regextract-no-longer-working/128266/4)

Metabase datatype "Field containing JSON"
Snowflake datatype "Variant"

### To Reproduce

1. Enter substring(regexextract([Tags], "\"Name\":\"((\\\"|[^\"])*)"), 9, 60) into a custom expression

### Expected behavior

This should work as per previous versions

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.219-208.866.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-07-04",
      "tag": "v0.50.10",
      "hash": "49d9e46"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Broken most of our Dashboards

**Comment by kamilmielnik** [comment]
Error is coming from `Lib.diagnoseExpression`, assigning to QP.
It seems to depend on field type.

**Comment by camsaul** [comment]
@kamilmielnik can you please post the error that popped up?

**Comment by camsaul** [comment]
to repro locally:

1. Load Snowflake `test-data`
2. manually change `venues.name` `base_type` to `type/*` and `database_type` to `VARIANT`
3. In QB, start a new query against Venues
4. Add custom column with expression `regexextract([Name] , "\"((\\\"|[^\"])*)")`
5. Observe error

![image](https://github.com/user-attachments/assets/424e7ef2-a17d-40ba-aa81-665137592e67)

```
core.cljs:3996 [metabase.lib.normalize] Error normalizing pMBQL:
{:value
 [:regex-match-first
  {:lib/uuid "fc8e78ed-a4ee-43f5-aa3f-fbff96d62d62"}
  [:field {:base-type :type/*, :lib/uuid "5250f36c-2d28-4ece-bd03-0ed63836b433"} 33526]
  "\\\"((\\\\\\\"|[^\\\"])*)"],
 :schema #object[malli.core.t_malli$core39458],
 :explain
 {:schema #object[malli.core.t_malli$core39458],
  :value
  [:regex-match-first
   {:lib/uuid "fc8e78ed-a4ee-43f5-aa3f-fbff96d62d62"}
   [:field {:base-type :type/*, :lib/uuid "5250f36c-2d28-4ece-bd03-0ed63836b433"} 33526]
   "\\\"((\\\\\\\"|[^\\\"])*)"],
  :errors
  ({:path [0 2 0 0 1],
    :in [2],
    :schema #object[malli.core.t_malli$core39189],
    :value [:field {:base-type :type/*, :lib/uuid "5250f36c-2d28-4ece-bd03-0ed63836b433"} 33526]})}}

diagnostics.ts:158 diagnostic error Type error: , , ["expression returning a string"]
```
