### ISSUE TITLE
Serialization: better errors

### ISSUE THREAD

**Issue by piranha** [metabase/metabase#45225]
When serialization breaks because Metabase threw an exception - so, it's not an unexpected logic error, but more like "we don't know what to do with that data" - we should output this error in a concise way (so, no long stacktraces, Toucan connection details which confuse users) without losing useful data (so all the nested messages and their data).

Also: possibly append `:table` to data when data contains `:model` so it's easier for users to determine where's the error coming from.

**Comment by crisptrutski** [comment]
Waiting for https://github.com/metabase/metabase/pull/46147#discussion_r1705411916 to land before doing this.
