### ISSUE TITLE
Stacked bar charts don't take into account negative values when the positive values are very large

### ISSUE THREAD

**Issue by a-termis** [metabase/metabase#45254]
### Describe the bug

When you make a stacked bar chart, the negative values don't subtract from the total so the bar is artificially higher. If you hover in the breakdown of a bart you can see the negative values. 
Example:
![Screenshot 2024-07-08 at 3 21 42 p m](https://github.com/metabase/metabase/assets/114109351/83f4e49c-6cee-4eaa-bec3-095e40312a2e) 
Total appears to be 103 k.
Breakdown: 
![Screenshot 2024-07-08 at 3 21 48 p m](https://github.com/metabase/metabase/assets/114109351/0a76bc5a-9ffb-4b96-977f-438666e11a30) 
Negative value doesn't subtract from the total

### To Reproduce

1. Run this query: 
`select 1 as class, 'A' as type, 1000000 as value union all select 2 as class, 'A' as type, 1000000 as value union all select 3 as class, 'A' as type, 1000000 as value union all select 1 as class, 'B' as type, 1000000 as value union all select 2 as class, 'B' as type, 1000000 as value union all select 3 as class, 'B' as type, 1000000 as value union all select 1 as class, 'C' as type, 1000000 as value union all select 2 as class, 'C' as type, 1000000 as value union all select 3 as class, 'C' as type, 1000000 as value union all select 1 as class, 'D' as type, 1000000 as value union all select 2 as class, 'D' as type, 1000000 as value union all select 3 as class, 'D' as type, 1000000 as value union all select 1 as class, 'E' as type, 1000000 as value union all select 2 as class, 'E' as type, 1000000 as value union all select 3 as class, 'E' as type, 1000000 as value union all select 1 as class, 'F' as type, 1000000 as value union all select 2 as class, 'F' as type, 1000000 as value union all select 3 as class, 'F' as type, 1000000 as value union all select 1 as class, 'G' as type, 1000000 as value union all select 2 as class, 'G' as type, 1000000 as value union all select 3 as class, 'G' as type, 1000000 as value union all select 1 as class, 'H' as type, 1000000 as value union all select 2 as class, 'H' as type, 1000000 as value union all select 3 as class, 'H' as type, 1000000 as value union all select 1 as class, 'I' as type, 1000000 as value union all select 2 as class, 'I' as type, 1000000 as value union all select 3 as class, 'I' as type, 1000000 as value union all select 1 as class, 'J' as type, 1000000 as value union all select 2 as class, 'J' as type, 1000000 as value union all select 3 as class, 'J' as type, 1000000 as value union all select 1 as class, 'K' as type, 1000000 as value union all select 2 as class, 'K' as type, 1000000 as value union all select 3 as class, 'K' as type, 1000000 as value union all select 1 as class, 'L' as type, 1000000 as value union all select 2 as class, 'L' as type, 1000000 as value union all select 3 as class, 'L' as type, 1000000 as value union all select 1 as class, 'M' as type, 1000000 as value union all select 2 as class, 'M' as type, 1000000 as value union all select 3 as class, 'M' as type, 1000000 as value union all select 1 as class, 'N' as type, 100000 as value union all select 2 as class, 'N' as type, 100000 as value union all select 3 as class, 'N' as type, -10000 as value`
2. Click on 'Visualization'
3. Click on 'Bar'
4. Click on the settings gear icon for visualization
5. Select the 'type' column as the X-Axis value, 'class' column as the breakdown value for the x-axis,  and 'value' as the y-axis value
6. Click on Display tab
7. Click on 'Stack' for the Stacking setting
8. Click on 'Show values on data points' toggle
9. Click done
10. See error
![Screenshot 2024-07-08 at 3 48 31 p m](https://github.com/metabase/metabase/assets/114109351/3f3c84bd-c114-412b-b5f5-4f122ffc31ae)
![Screenshot 2024-07-08 at 3 48 37 p m](https://github.com/metabase/metabase/assets/114109351/bb0e2f89-f92e-4285-a3ed-bffa03695f4f)
Even if you click on 'Full' in 'Auto formatting' , the mistake is still there
![Screenshot 2024-07-08 at 3 50 09 p m](https://github.com/metabase/metabase/assets/114109351/6a3037c0-e0ce-4193-b4cf-0e76a489de25)

### Expected behavior

The last bar on the x-axis (called 'N' in the example) should show a total of 190k in Compact or Auto, or 190,000 in Full for 'Auto formattting'. And the bar should take into account the negative value for the total.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.219-208.866.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "h2",
      "bigquery-cloud-sdk",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-25",
      "tag": "v1.49.18",
      "hash": "fd3765d"
    },
    "settings": {
      "report-timezone": "America/Mexico_City"
    }
  }
}
```

### Severity

Blocking some users that need accurate financial reporting

**Comment by alxnddr** [comment]
Hi @a-termis 👋 When we stack values on bar/area charts, we do it separately for positive and negative values. It is more noticeable on the example below:
<img width="457" alt="Screenshot 2024-07-09 at 12 40 50 PM" src="https://github.com/metabase/metabase/assets/14301985/f5b530d5-0828-4596-a24b-6471ac3087df">

In the case you mentioned, the negative value is too small relatively to positive ones so it is hardly visible but it is there. The `103.0k label` is correct because it shows the value of the positive stack. The fact that this chart while having a negative `-10000` value starts from zero causes confusion which makes it easy to miss the negative value. In Metabase v50 we've reworked the bar chart and the new implementation makes it visible there is a negative value:

<img width="1339" alt="Screenshot 2024-07-09 at 12 47 35 PM" src="https://github.com/metabase/metabase/assets/14301985/f71bb5df-3a74-490b-89cb-9aaf3fc124fc">

Please let me know if you have any other concerns or ideas!
