### ISSUE TITLE
Icons in Recently Viewed list should be updated

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4525]
I think we should replace these old style icons with the ones we're using in the questions lists, though perhaps with a bolder color. Any opinions on this, @kdoh?

Current:

![screen shot 2017-03-15 at 11 07 32 am](https://cloud.githubusercontent.com/assets/2223916/23963941/0f80d600-0970-11e7-8454-402b6233b31b.png)

Newer icon style:

![screen shot 2017-03-15 at 11 09 38 am](https://cloud.githubusercontent.com/assets/2223916/23963967/26101b06-0970-11e7-93d4-4e873324baf6.png)

Related to #4524

**Comment by kdoh** [comment]
Yup, been wanting to do this forever just haven't gotten around to it yet.
