### ISSUE TITLE
Shouldn't be able to send a test Pulse email if there aren't any recipients

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4526]
It's weird to me that Metabase let's me send a test Pulse via email when I haven't specified any recipients. I think the `send` button should be disabled until there's at least one email address entered.

![screen shot 2017-03-15 at 11 13 09 am](https://cloud.githubusercontent.com/assets/2223916/23964087/8a5316f4-0970-11e7-9696-22ad186998d7.png)

(Incidentally, I mulled over whether users should even be able to save the Pulse at all in this state, but I think we should continue to allow them to do so even if they've selected the email method of delivery without any specified recipients, because we want to allow people to save work-in-progress Pulses.)

**Comment by flamber** [comment]
Hi @mazameli Wasn't this fixed by #8291 a couple of weeks ago ?

**Comment by mazameli** [comment]
@flamber Thanks yet again! Turns out #8291 closed out https://github.com/metabase/metabase/issues/8229, which in turn was actually a duplicate of this issue.
