### ISSUE TITLE
API calls using the API key don't work for all endpoints

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#45299]
### Describe the bug

It's possible that some endpoints don't work with the API key. I managed to find one `api/user`

### To Reproduce

1. Go to Admin -> Authentication -> Manage API -> Create new API key in Admin Group

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/bbaafc03-9d79-4ae6-9283-a8ec07d2e520">

Then try to use the API. The following call works:

`curl -H 'x-api-key: Ymb_UGXWibc0YbG+s9AClYhUTDk0bw3Wxe9GqQraBWcBvnQ=' -X GET 'http://localhost:3000/permissions/group'`

This one doesn't

`curl -H 'x-api-key: Ymb_UGXWibc0YbG+s9AClYhUTDk0bw3Wxe9GqQraBWcBvnQ=' -X GET 'http://localhost:3000/api/user'
`

### Expected behavior

Yeah API key should work for all endpoints if it was created in the admin group ... There might be more endpoints that doesn't work so we need to confirm it works on all endpoints

### Logs

GET /api/user/ 401 4.9 ms (0 DB calls) {:metabase-user-id nil}

### Information about your Metabase installation

```JSON
1.50.10
```

### Severity

Not blocking

**Comment by dpsutton** [comment]
Works for me?

#### Against master
```
❯ curl -s -H "x-api-key: $API_KEY" -X GET 'http://localhost:3000/api/user' | jq '.data|map(.email)'
[
  "crowberto@metabase.com",
  "dan@metabase.com",
  "limited@metabase.com",
  "lucky@metabase.com",
  "rasta@metabase.com",
  "segment@metabase.com"
]

```

##### against 0.50.9:

Using port 3059:

<img width="1102" alt="image" src="https://github.com/metabase/metabase/assets/6377293/86995f7b-6520-4912-992d-bc50f8a10cd2">


```
❯ http get localhost:3059/api/user x-api-key:$API_KEY -pb | jq '.data|map(.email)'
[
  "dan@metabase.com"
]
```

**Comment by noahmoss** [comment]
Works for me as well. @Tony-metabase pretty sure you just have an extra character at the start of the API key.

**Comment by dpsutton** [comment]
I think the urls are wrong

`'http://localhost:3000/permissions/group'` is not an api route. So it returns html and doesn't check the api key

```
❯ curl -H "x-api-key: $API_KEY" -X GET 'http://localhost:3000/permissions/group'
<!doctype html><html lang="en" translate="no"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" ...
```
