### ISSUE TITLE
Funnel column ordering freak out

### ISSUE THREAD

**Issue by boneill42** [metabase/metabase#45296]
### Describe the bug

When trying to reorder the columns in a funnel, the list freaks out.  This may be because there are numerous same values and there is an order by in the query?

See video:
https://www.loom.com/share/9fedfc525e6e44eba83e93d29ee66901

![image](https://github.com/metabase/metabase/assets/897229/6942fe9e-fea4-424b-84f0-d0aa6f7c7e7a)

### Expected behavior

I should be able to drag a column to reorder it in the funnel.

### Information about your Metabase installation

```JSON
Running: 1.50.9
Using Chrome: Version 126.0.6478.127 (Official Build) (arm64)
```

### Severity

Our funnel chart is broken, which is causing issues with our client reports.

**Comment by uladzimirdev** [comment]
@boneill42 could you please check browser console, is there any error reported?
