### ISSUE TITLE
queries result in more than 2000 rows

### ISSUE THREAD

**Issue by asafeilam** [metabase/metabase#4532]
It would be great to be able to get more than 2000 rows in a query.
even just to download the overall results and to be limit in 2000 rows.

**Comment by salsakran** [comment]
We limit what comes back in a table view to keep things from getting crazy on the front end. You can download larger datasets via csv or json, however we need to keep some sort of limit so people don't try to download 1B event table rows. 

I

**Comment by abelliae** [comment]
Couldn't this be parametrized? And possibly an unlimited dump allowed to folder curators?

**Comment by jlisyc** [comment]
related https://github.com/metabase/metabase/issues/9651
