### ISSUE TITLE
Funnel display broken on Firefox

### ISSUE THREAD

**Issue by wvengen** [metabase/metabase#4534]
Trying out #4310 on master, I find that the Funnel view doesn't fully work on Firefox 52.0 (64-bit, Linux):

![image](https://cloud.githubusercontent.com/assets/503804/24004710/4bc2830a-0a67-11e7-8cf2-dc3227ade5ca.png)

The same thing on Chromium 55.0.2883.87 (64-bit, Linux) does render correctly:

![image](https://cloud.githubusercontent.com/assets/503804/24004736/641d6dfc-0a67-11e7-843e-53e5452786c4.png)

I do not see any suspicious messages in the JS console related to this.
Inspecting a blue element in the inspector, I see that the `clip-path` style is missing on Firefox.
Adding this manually, I see the warning _Invalid property value_. Apparently Firefox doesn't like the format of this `clip-path`.

**Comment by tlrobinson** [comment]
Firefox doesn't support % clip-paths 🙄  https://stackoverflow.com/questions/33816793/clip-path-doesnt-work-in-firefox-values
