### ISSUE TITLE
Cannot open a collection containing a non-ASCII character "ł"

### ISSUE THREAD

**Issue by jgoclawski** [metabase/metabase#4535]
- Your browser and the version: Chrome 57.0.2987.98 (64-bit)
- Your operating system: Linux
- Your databases: Postgres
- Metabase version: v0.23.0-RC1 (from https://hub.docker.com/r/metabase/metabase/)
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

### Repeatable steps to reproduce the issue

1. Create a new collection, use a non ASCII character as it's name, e.g. "Obsługa klienta" (BTW: "Customer Service" in Polish).
1. Click on the new collection in the "Questions" tab.
1. Observe "Not found" screen.
1. Observe that the generated URL is: /questions/collections/obsługa_klienta

The bug however does NOT occur when viewing a question from such collection. In the upper-left part of the question screen, above it's name, there is a collection name. When clicked I can successfully view the collection. The generated URL is "/questions/collections/obs%25C5%2582uga_klienta" and this one works.

I'm attaching 2 screenshots, that present the issue.

![zrzut ekranu z 2017-03-16 17-25-45](https://cloud.githubusercontent.com/assets/1043875/24007251/4c4e5450-0a6e-11e7-8129-3c191040d011.png)
![zrzut ekranu z 2017-03-16 17-27-16](https://cloud.githubusercontent.com/assets/1043875/24007252/4c4f722c-0a6e-11e7-972b-9f2d2909eb21.png)

**Comment by jgoclawski** [comment]
Just a follow-up:
The issue is probably related to PR #4258.
But the problem is only with one of Polish characters: "ł", all the rest works. So I have amended the title, to better reflect the scope of the bug.

Examples:
* Collection name: "Bad letter: ł"
  Works: no
* Collection name: "ĄĆĘŃÓŚŹŻąćęńóśźż"
  Works: yes!

I think that the problem is with `remove-diacritical-marks` which doesn't handle all of possible characters.
You can see similar issues in other projects and as far as I can tell, usually they're covered by having a custom mapping for those few edge cases.
Example: https://github.com/ilopmar/grails-slug-generator/commit/8289563d5d418fe0d768c28c0f710193c43eb241

**Comment by camsaul** [comment]
@jgoclawski, if you have some basic familiarity with Clojure, we'd love to have you as a contributor and would welcome a PR to support this. It should be pretty straightforward to tweak `remove-diacritical-marks` to handle characters like `ł` 👍

**Comment by jgoclawski** [comment]
Thanks for fixing this! I'm impressed with your attention to detail in Metabase and commiting your time even to the smallest issues :)

Unfortunately I have no knowledge of Clojure, so the best I could do was to let you know about the issue ;)
