### ISSUE TITLE
Migration error on PostgreSQL 11.22

### ISSUE THREAD

**Issue by entvia** [metabase/metabase#45367]
https://github.com/metabase/metabase/blame/d814074bea5b697868d2bf494fd44da827a122e7/resources/migrations/001_update_migrations.yaml#L6495

Hi! I guess this change is not compatible with Postgres 11.22 and would work only starting from version 12. Metabase docs say that the product is compatible with PostgreSQL 9.0 and higher, so to keep this a valid point I think a fix is needed. Here is the error we get starting from yesterday, after automatic upgrade:

```
ERROR:  syntax error at or near "(" at character 87
STATEMENT:  ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
	  CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
	) STORED
```
Let me know if you are planning to keep it compatible with older PostgreSQL versions. If not, I would suggest to update the docs.

**Comment by camsaul** [comment]
Our general policy is to only officially support databases that are supported upstream. [Postgres 11 was EOL'ed in November 2023](https://endoflife.date/postgresql), so we're not officially supporting it anymore. Which doc page did you see where it said we support 9+? We'll update it.

**Comment by camsaul** [comment]
CC @jeff303 -- let's update the documentation about supported versions of Postgres

**Comment by notrom** [comment]
I agree, only supporting supported versions makes a lot of sense. But a heads up in the release notes would have been nice. Worth noting that v0.48 release notes had a section about no longer supporting Postgres lower than 9.5. https://www.metabase.com/releases/metabase-48 

> # Postgres as app db for Metabase must be 9.5 or higher
> If you’re using Postgres as your application database for Metabase, you’ll need to upgrade to Postgres version 9.5 or higher before you upgrade your Metabase to 48.

I tripped up on this one myself today when trying to upgrade from v0.49.7 to v0.50.11. No excuses, this one's on me for not keeping Postgres up to date.

**Comment by entvia** [comment]
Hi @camsaul and @jeff303! Thank you for a fast reply and clarification.
Here is the link https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data 
So, this is present also in the docs of the latest version.
