### ISSUE TITLE
Add Embedding Documentation

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4537]
We a bit of copy from both the interface, embedding applications and blog post.

Should we split this out into a "developers guide" or create a separate guide for embedding? Seems pretty thorny to put in our users guide.

**Comment by kdoh** [comment]
Seems to make the most sense as a developers guide.
![giphy](https://cloud.githubusercontent.com/assets/5248953/24010895/5c4f0a44-0a36-11e7-8ec8-1ff7c90c7032.gif)

**Comment by salsakran** [comment]
As reminded by @tlrobinson we should talk about caching public links

**Comment by tlrobinson** [comment]
possibly based off of https://github.com/metabase/metabase/issues/3966

bonus points for a docker-compose.yml that demos it.

**Comment by salsakran** [comment]
fixed via #4553
