### ISSUE TITLE
Allow to set a custom label for the "goal"

### ISSUE THREAD

**Issue by lucacioria** [metabase/metabase#4538]
### enhancement description
Allow to set a custom label for the "goal" so that it can be used for other use cases, such as a dangerous threshold (the opposite of a goal).

### use case

In my company, we have a widget showing the current WIP of the team. We have a WIP limit, a threshold which we should not cross. We currently use the goal to visualize the WIP limit (currently it's 34), but many people reacted saying "this looks like we should reach 34, not stay below!"

**Comment by flamber** [comment]
Hi @lucacioria 
Custom label/text for Goal is now available - think it was added in 0.30/31 - this is an example on 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52734332-8bdcb380-2f8a-11e9-8328-1a7b043bd03c.png)
