### ISSUE TITLE
Weird behavior after saving questions in v1.50.11

### ISSUE THREAD

**Issue by vebjorre** [metabase/metabase#45416]
### Describe the bug

Bug first seen in v1.50.11

After saving a question a new dialogue pops up: "Save new question". It disappears after a few seconds and the question is saved as expected. This happens when you start from a saved question and either replace it or create a new question.
The behavior seems to be related to the query_metadata request. 

See screen recording below for an example

### To Reproduce

1. Upgrade to v.1.50.11
2. Go to a saved question
3. Edit something in this question
4. Save question, either by overwriting the old one or creating a new question.
5. See behavior

### Expected behavior

The second dialogue should never show.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "nb-NO",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "6.1.85+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.19"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-07-09",
      "tag": "v1.50.11",
      "hash": "e08c1fb"
    },
    "settings": {
      "report-timezone": "Europe/Oslo"
    }
  }
}
```

### Severity

Annoying to any user creating questions

### Additional context

https://github.com/metabase/metabase/assets/55921651/a3da8813-bcea-4607-8784-a89877772f8c

**Comment by nemanjaglumac** [comment]
That "Save dialog" prompt looks like this one:
https://github.com/metabase/metabase/issues/37373

@vebjorre What was the version from which you upgraded?

**Comment by vebjorre** [comment]
Yes, it does look similar. I have only tested questions I created myself, so it is not exactly the same regarding permissions (both old and new ones). See permissions below:
![Skjermbilde 2024-07-11 kl  15 27 37](https://github.com/metabase/metabase/assets/55921651/6a6444de-189c-406c-81ba-3cf229b2fa51)

> What was the version from which you upgraded?

1.50.10
We usually upgrade for each new patch and I am positive I did not see this issue in 1.50.10 or earlier.

**Comment by nemanjaglumac** [comment]
I was able to reproduce it on a fresh x.50.11 instance.
Upgrading doesn't play a role here.

Investigating further...

**Comment by nemanjaglumac** [comment]
@vebjorre this was present in x.50.10 as well.
Please see the attached video. It happens very briefly.

https://github.com/metabase/metabase/assets/31325167/994139ea-5434-48fa-8c1c-3291e113db0e

**Comment by nemanjaglumac** [comment]
Related (and probably the same root cause) - https://github.com/metabase/metabase/issues/35150

**Comment by paoliniluis** [comment]
@vebjorre your endpoints are extremely slow, can you send us an email?

**Comment by uladzimirdev** [comment]
@vebjorre 50.13 contains a fix, could you please share a video of the wrong behaviour in 50.13 if you still experience it?
