### ISSUE TITLE
Filter Field Dropdown list never gets refreshed

### ISSUE THREAD

**Issue by chandraonline** [metabase/metabase#4542]
I have a dashboard with bunch of SQL based cards and all cards have a company as a filter field. The filter field is included in the sql as an optional:  [[ company_id = {{company}} ]] and the filter field definition points to Filter Field type and pointing to the Name in the Companies table. Everything works as expected except new entries added to the Companies table don't show in the dropdown. There are 22 rows in the table. I tried to recreate the dashboard etc to no avail. Where is this information cached and how do I refresh it. When I go to the Data Reference-> See all tables and select that table it has the two rows that are not shown in the drop down. I tried deleting a few rows from that table and metabase still continues to show them.

### Bugs
- Your databases:  Amazon Redshift
- Metabase version: (e.x. 0.19.3): 0.22.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database:  Postgres

**Comment by salsakran** [comment]
This is in the FieldValues attached to a given field. It's separate from the dashboard or cards. 

It should be getting refreshed every evening if you've enabled "in depth analysis" in the general settings. We don't (yet) have a way to selectively update field values for a subset of tables/columns unfortunately.

**Comment by chandraonline** [comment]
I remember seeing the "in depth analysis" checkbox somewhere and turning it on but I tried to look for it now in the Admin Panel->General->Settings and don't see it. I only see the following:

SITE NAME
SITE URL
EMAIL ADDRESS FOR HELP REQUESTS
REPORT TIMEZONE - PST
ANONYMOUS TRACKING - Not Enabled
FRIENDLY TABLE AND FIELD NAMES - Enabled

What's the easiest way to verify that this is getting refreshed, something I could search in the logs?

Thanks for enhancing and maintaining this great product.

**Comment by chandraonline** [comment]
I found it under Database and it was turned on already.

https://cloud.githubusercontent.com/assets/933276/24118826/636046b6-0d6c-11e7-82fb-c05b17839b0d.png

**Comment by BembelGmbH** [comment]
@salsakran - I use v. 0.24.0  and I do have this option enabled but the filter values are not getting updated.
Imagine a scenario:
Event table: | id | name | product_id |   - this table is set as visible in settings. order_id is a foreign key
Product table: | id | name |  - this table is set as invisible

When I select event table and want to filter by product_name I get a list of Product names. This list is **never** getting updated. In order to update it, I have to "unhide" the Product table, make a query `SELECT * FROM Prodcut` and then hide it again. Only then the filter is getting updated.
Is there an other way?

**Comment by od3n** [comment]
@BembelGmbH what do you by unhide table? I need fast fix for now too

**Comment by MarkRx** [comment]
I encountered this. For now I am just restarting Metabase to get the changes to show up. Not the best workaround...

**Comment by EvaSchreyer** [comment]
Hi, I am using v0.25 with a SQL database and encountered something similar: 
[](http://discourse.metabase.com/t/data-model-hard-join-does-not-disappear-after-de-joining/3054)

**Comment by briankalbster** [comment]
I found that your can refresh the values in admin under table settings

![image](https://user-images.githubusercontent.com/37079367/38320841-4fd57c28-37fb-11e8-85bd-62e6c564e130.png)

Click on discard cached field values and resync

![image](https://user-images.githubusercontent.com/37079367/38320780-23773176-37fb-11e8-8d9f-aa8bbc8e81c7.png)

**Comment by mazameli** [comment]
@chandraonline, are you still experiencing this in more recent versions of Metabase. As @briankalbster pointed out, in [Metabase version 0.26](https://metabase.com/blog/Metabase-0.26/index.html) (two major versions ago), we added a lot of new tools for improving sync and scan scheduling as well as on-demand sync/scan.

Let me know if this issue should be closed from your perspective.

**Comment by flamber** [comment]
Closing, since manual sync+scan has been available for many versions, including scheduling:
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis
