### ISSUE TITLE
Metadata % description shows up behind popup

### ISSUE THREAD

**Issue by filipesilva** [metabase/metabase#45441]
Mouseover the 15% here will show the description (in black) behind the other popup (in white). Metabase v1.50.7, on Safari.

![image](https://github.com/metabase/metabase/assets/4172079/24bb4075-6a6f-4dbb-9060-02a7c465024e)

Followup from https://metaboat.slack.com/archives/C505ZNNH4/p1720722799246589

**Comment by nemanjaglumac** [comment]
I think I know why 🫣
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/ui/components/overlays/Popover/Popover.styled.tsx
