### ISSUE TITLE
Where can I select the row limit?

### ISSUE THREAD

**Issue by cqcn1991** [metabase/metabase#4544]
Due to the response time limit by Heroku, I want to set the row limit return to 300

but I only find buttons 
![qq](https://cloud.githubusercontent.com/assets/2425141/24072257/4d2d5030-0c1f-11e7-84ee-21ca783fc638.png)

Is there any way I can specify the row limit number?

**Comment by salsakran** [comment]
The heroku response time probably doesn't have much to do with the row limit.

How big is the table, what else is going on in the queyr, and is "created_at" indexed? The difference between 1000 and 300 rows should be pretty negligible  if you're sorting on an unindexed column.

**Comment by salsakran** [comment]
to answer your actual question, we don't allow arbitrary numbers of rows in the UI.

**Comment by cqcn1991** [comment]
@salsakran OK. I can get response if I select 100, and can hardly get response if I select 1000.

**Comment by mazameli** [comment]
This will be implemented in https://github.com/metabase/metabase/pull/9592.

**Comment by mazameli** [comment]
Implemented in version 0.33. You can now enter a custom row limit.
