### ISSUE TITLE
API Keys can access/query Dashboards/Cards of No-Access Collections

### ISSUE THREAD

**Issue by Nexxurs** [metabase/metabase#45458]
### Describe the bug

Through the usage of the /api endpoint, an API key, created for Group X, can access card queries in collections where that group has no view permission (permission No Access)

### To Reproduce

1. Create a Group (Group X)
2. Create a collection and set the permissions for Group X to "No Access"
3. Add a dashboard/card to this collection
4. Create an API Key for Group X
5. Query `/api/dashboard/<dashboard-id>` or `/api/card/<card-id>/query` and receive data

### Expected behavior

The api request should respect the permissions of the card/dashboard it queries and return Permission-Denied if the group for that key is not allowed to view the card/dashboard/collection

### Logs

[2c7a2cb5-aebf-4c1a-9e9c-835d2d9c5e5a] 2024-07-12T12:54:08+02:00 INFO metabase.query-processor.middleware.cache Query bf4c9284 took 433.0 ms to run; minimum for cache eligibility is 1000.0 µs; eligible
[2c7a2cb5-aebf-4c1a-9e9c-835d2d9c5e5a] 2024-07-12T12:54:08+02:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "bf4c9284". 💾
[2c7a2cb5-aebf-4c1a-9e9c-835d2d9c5e5a] 2024-07-12T12:54:08+02:00 DEBUG metabase.server.middleware.log POST /api/card/874/query 202 [ASYNC: completed] 729.7 ms (31 DB calls) App DB connections: 1/13 Jetty threads: 4/50 (2 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued); mysql DB 5 connections: 0/1 (0 threads blocked) {:metabase-user-id 112}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.4.0-91-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.34"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-09",
      "tag": "v0.50.11",
      "hash": "e08c1fb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Medium

### Additional context

I am not sure if this is a bug/security vulnerability or feature request - please modify the tag as applicable!

**Comment by noahmoss** [comment]
@Nexxurs I'm not able to reproduce. Are you certain that the API key is created in the correct group? And can you double check the permissions for that group, as well as the permissions for the All Users group?

**Comment by Nexxurs** [comment]
Hey @noahmoss!

Sorry, this was my mistake - I accidently synced my browser cookies with Postman when sending those requests, so the queries were executed within session permission scope instead of the API one. 

I will close this issue again - thanks for the support!
