### ISSUE TITLE
Question error with filter on version 0.23

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#4545]
------
I got below error when running saved question with filter on new docker image 0.23 (these questions work fine with  v0.22):
![screen shot 2017-03-20 at 9 50 13 am](https://cloud.githubusercontent.com/assets/2088055/24087583/4a289838-0d53-11e7-9cc7-5dff2440d57e.png)

I can not fix my question based on the error description.

**Comment by buren** [comment]
I'm seeing a similar syntax error for:

```sql
SELECT jobs.id, jobs.name
FROM jobs
WHERE 1=1
    AND cancelled = false
    AND filled = true
    AND (
        ((job_date >= {{start_date}} AND job_date <= {{end_date}}) AND job_end_date <= {{end_date}})
        OR (job_date <= {{start_date}} AND job_end_date >= {{end_date}})
    )
```

The exact message is: `ERROR: syntax error at or near "=" Position: 243`.

I've executed that RAW-SQL and it returns the correct result..

ℹ️  Running: v0.22.2, built 2017-01-26.

**Comment by camsaul** [comment]
@thucnc @buren the Metabase logs should show what the SQL looks like after params are substituted, can you post that SQL?

**Comment by salsakran** [comment]
@thucnc + @buren tried to repro on the sample dataset on h2 and a test db we have on MySQL but can't.

What is the database these queries is being run on, and as @cam mentioned can you find the sql being run in the server logs and share that here? 

Can't repro on our end, and this looks like a blocker.

**Comment by thucnc** [comment]
@salsakran I used a postgres. Here is what I got from metabase logs:
![screen shot 2017-03-21 at 11 11 00 am](https://cloud.githubusercontent.com/assets/2088055/24132345/7f1ebe26-0e27-11e7-80e4-936a81607363.png)

**Comment by salsakran** [comment]
can you scroll up and find the fully expanded form, as @camsaul mentioned?

**Comment by salsakran** [comment]
We're specifically looking for the SQL that is generated once the parameters are inserted. We log that for this exact situation ;)

**Comment by thucnc** [comment]
@salsakran I only get the before-processed query like this:
![screen shot 2017-03-21 at 11 35 29 am](https://cloud.githubusercontent.com/assets/2088055/24132791/9dc49140-0e2a-11e7-88fe-6e6fcdf5e611.png)

**Comment by thucnc** [comment]
I checked the docker logs, and couldn't find the after-processed query.

**Comment by salsakran** [comment]
Tried it on a posgres db, and still can't replicate. 

Could you try removing filters until you find the offending one, and perhaps simplifying the query until you figure out what element is causing this?

**Comment by thucnc** [comment]
A simplified version is made as below but still got the same error:
```
with end_date as (select extract ('epoch'from timestamp {{end_date}} + interval '1 day' - interval '7 hour') as en),

SAMPLE as (
select o.id
from "order" o, end_date
WHERE order_time <= end_date.en),

select * from SAMPLE

```

![screen shot 2017-03-21 at 1 35 12 pm](https://cloud.githubusercontent.com/assets/2088055/24135192/4419976a-0e3b-11e7-9680-b18e625c7ba4.png)

**Comment by salsakran** [comment]
Ok, that actually gave me that error.

Thanks for the patience and help @thucnc !

**Comment by salsakran** [comment]
for posterity, 
```
with end_date as (select extract ('epoch'from timestamp {{end_date}} + interval '1 day' - interval '7 hour') as en),

SAMPLE as (
select o.id
from orders o, end_date
WHERE created_at <= end_date.en),

select * from SAMPLE
```
against the sample dataset barfs. 
we should use it (or something similar) in a test.

**Comment by camsaul** [comment]
of course it does, that's Postgres-specific syntax 😉 

try replacing the variable `{{end_date}}` with a literal timestamp (`cast('2017-03-09T00:00:00.000' as timestamp)`) and it will still barf.

**Comment by salsakran** [comment]
try the pg specific card I linked to earlier on slack ;)

**Comment by camsaul** [comment]
So it looks like this is just an issue with the syntax of the original query

The original query (edited for readability)

```sql
WITH end_date AS (
    SELECT extract('epoch' from (timestamp {{end_date}} + interval '1 day' - interval '7 hour') AS en
) sample AS (
    SELECT o.id
    FROM order o, end_date
    WHERE order_time <= end_date.en
)
SELECT * 
FROM SAMPLE
```

gets replaced with

```sql
WITH end_date AS (
    SELECT extract('epoch' from (timestamp ? + interval '1 day' - interval '7 hour') AS en
) sample AS (
    SELECT o.id
    FROM order o, end_date
    WHERE order_time <= end_date.en
)
SELECT * 
FROM SAMPLE
```

(`?` being the prepared statement placeholder arg)

This doesn't work, because it's invalid Postgres syntax; `TIMESTAMP <string>` only works for string literals.

If you instead change the original query to

```sql
WITH end_date AS (
    SELECT extract('epoch' from ({{end_date}}::timestamp + interval '1 day' - interval '7 hour') AS en
) sample AS (
    SELECT o.id
    FROM order o, end_date
    WHERE order_time <= end_date.en
)
SELECT * 
FROM SAMPLE
```

things work as expected.

**Comment by salsakran** [comment]
any idea why it worked before?

**Comment by camsaul** [comment]
Here's actually the simplest possible demo

![screen shot 2017-03-21 at 2 32 40 pm](https://cloud.githubusercontent.com/assets/1455846/24171855/4bcbc516-0e43-11e7-8fef-76c36dff698d.png)

![screen shot 2017-03-21 at 2 32 54 pm](https://cloud.githubusercontent.com/assets/1455846/24171858/4d8e85aa-0e43-11e7-8465-2eaab9e132e7.png)

**Comment by camsaul** [comment]
@salsakran it used to work before because we substituted string literals directly into the SQL instead of using prepared statement args. That wasn't a big issue in the past but now that we support public cards and dashboards it's a potential SQL injection vulnerability which is why we switched over.

**Comment by salsakran** [comment]
ok @thucnc does that resolve things? 
In any event since the re-pro didn't re-pro, pushing this out to a point release.

**Comment by camsaul** [comment]
Unfortunately there isn't anything we can do to fix this on our end without removing our security improvements, you'll need to use the `::timestamp` syntax instead

**Comment by buren** [comment]
Thank you @camsaul and @salsakran for being awesome 🙇 and ⚡️

**Comment by thucnc** [comment]
@salsakran it's all clear. I will fix my queries manually then. Thank you so much. I love Metabase 👍

**Comment by mattes** [comment]
Just ran into the same issue. Anyone has an idea how to make `{{period}}` work again? (Postgres)

<img width="708" alt="screen shot 2017-03-23 at 10 47 18 am" src="https://cloud.githubusercontent.com/assets/1240531/24262062/21eff66c-0fb6-11e7-8fcd-7d3dc6c748ac.png">
<img width="327" alt="screen shot 2017-03-23 at 10 47 23 am" src="https://cloud.githubusercontent.com/assets/1240531/24262065/2409f51a-0fb6-11e7-9f85-014cb4642aed.png">

**Comment by mattes** [comment]
It's actually quite simple. haha. 

```sql
SELECT d FROM generate_series(current_date - cast({{period}} as interval), current_date, '1 day') d
```

**Comment by mirceapasoi** [comment]
I'm also on Postgres and running into issues with queries that used to work fine until v0.23

<img width="1178" alt="screen shot 2017-03-23 at 2 06 27 pm" src="https://cloud.githubusercontent.com/assets/29048/24270357/0e340a66-0fd2-11e7-87ec-71ec59bc4627.png">

**Comment by mattes** [comment]
Try to cast as text.
```
select date_trunc(cast({{period}} as text), current_date)
```

**Comment by mirceapasoi** [comment]
Thank @mattes , but it still doesn't work, there's something about using {{period}} in GROUP BY 
<img width="1193" alt="screen shot 2017-03-23 at 2 36 38 pm" src="https://cloud.githubusercontent.com/assets/29048/24271399/45b8a416-0fd6-11e7-9bef-ac37c4383e26.png">

**Comment by mattes** [comment]
did you try to use the alias? `group by period`

**Comment by mirceapasoi** [comment]
That worked, thank you for the help @mattes!

**Comment by salsakran** [comment]
@mattes @mirceapasoi @thucnc -- Are all of these situations "morally equivalent" to providing a user facing ENUM? I.e. a limited set of values that you expect?

**Comment by mattes** [comment]
Not for me. See my use-case above.

**Comment by mirceapasoi** [comment]
@salsakran for my use-case yes, we only use "day", "week", "month", "year", etc. (whatever date_trunc supports)

**Comment by salsakran** [comment]
@mirceapasoi would the ability to use dashboard time widgets in a sql question remove the need for what you're doing?

**Comment by salsakran** [comment]
Hey @mirceapasoi @mattes @thucnc  -

First off, really sorry for the mess you've been dealing with. We didn't expect quite so many people to be using sql parameters in as many creative ways. We also think some of this was due to the weakness of the input options for number/date/string filters, and the lack of date filters equivalent to the dashboard filter widgets.

We've just release 0.23.1, which will hopefully remove a bit of the pressure. You can now take a field-based filter clause, and assign it a filtering widget, just as if it were a dashboard. 

You'll be able to do things like filter by last 7 days, etc without your end users need to remember the formats or typing.

We're also going to be extending the template language over the next couple of versions in response to any other uses you were finding for the old style completely freeform template variables.

We *really* want to un-muck this up for you, but like I said, SQL injection attacks are a real worry of ours and we're going to try to do so in a type-safe way.

**Comment by salsakran** [comment]
removing this from 0.23.1 to let people chime in with specific use cases.

**Comment by agentscript** [comment]
Can anyone help me with MS SQL Server for the date filter, I am SQL Server 2008

**Comment by camsaul** [comment]
@agentscript unfortunately SQL Server 2008 doesn't support some of the functions we need in order to support the date filtering functions. This is discussed in more detail in #2330

**Comment by rohit1675** [comment]
getting an error while trying to save any question in Metabase -
More details are ::
1, v0.30.3
2, Running under Amazon linux under docker container deplyed via Elstic Beanstalk
Any idea what's going on behind this scene.

Note:: In GUI it says "Save Failed" but on searching the Saved Data, can see it.

**Comment by camsaul** [comment]
Almost everything mentioned here has already been fixed (e.g. #2330), if anyone is still running in to issues related to this and needs help writing valid SQL please ask for help on https://discourse.metabase.com
