### ISSUE TITLE
Visualisation doesn't render properly. I see `ResizeObserver loop completed with undelivered notifications.` error in browser console

### ISSUE THREAD

**Issue by hb-akhilesh** [metabase/metabase#45454]
### Describe the bug

I have a pretty straightforward visualisation. Like this.
<img width="1229" alt="image" src="https://github.com/user-attachments/assets/8b35390f-daea-4b17-943e-da03f2cfeaa9">

Below is the last part of the question (this is when things work fine)
<img width="1398" alt="image" src="https://github.com/user-attachments/assets/47548c94-9648-41ab-9771-20eeaa06399a">

Now, Say I further want to filter out dataset (count ) and only visualise count's which are > 10, then I get a rendering issue. Attaching the video.

https://github.com/user-attachments/assets/028c8783-ea7a-4c03-8647-45e747ab52fe

When problem happens, the question is like this:

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/28cc7074-4d10-43dc-8e8a-f07f66010c38">

### To Reproduce

1. Create a question (say sales orders) when you plot data grouped by (say city) and then further group by dates.
2. See that visualisation is working fine. Graph comes up correctly grouped by count, cities and plotted against dates (say day wise).
3. Then Edit the question to further add a condition: Visualise the data where count > 10 and click visualise.
4. See that answer loads and then UI goes in resize loop. and graph doesn't render properly.

### Expected behavior

Graph should hold good, as it was when we rendered it at step 2.

### Information about your Metabase installation

```JSON
- Browser Safari (Version 17.5 (19618.2.12.11.6))
- Metabase hosted on Ubuntu 22.04 (running latest as of today)
- Database postgresql 14
- JDK: OpenJDK Runtime Environment Corretto-11.0.23.9.1 (build 11.0.23+9-LTS)
```

### Severity

Medium

**Comment by alxnddr** [comment]
@hb-akhilesh thanks for reporting the issue. Could you please tell me what version of Metabase you are using?

**Comment by hb-akhilesh** [comment]
0.50.9

**Comment by alxnddr** [comment]
@hb-akhilesh thank you for the information about version you are using. I could not reproduce it yet so I wonder if you could provide additional information that would help identify the problem. Could you please try to reproduce it in Chrome and tell if it also weirdly resizes?

**Comment by hb-akhilesh** [comment]
Alright. So Tried to reproduce this again on my system. But it’s not happening now. I thought I shall debug into the code, but not able to for now. Shall keep a watch.

Though when it happened, I had seen the browser console. Luckily I had searched for that error as I was intrigued.  This was the error that I had seen in the browser console. 

https://stackoverflow.com/questions/76187282/react-resizeobserver-loop-completed-with-undelivered-notifications￼
React: ResizeObserver loop completed with undelivered notifications
stackoverflow.com
 

Will try to give you exact source line if it happens with me again.

**Comment by hb-akhilesh** [comment]
Okay. So I have that tab open where this is still happening. Let me know what you want me to look for. Or we can get on a call. I cannot see the exact js source code line since code is minimised. 

￼

**Comment by alxnddr** [comment]
@hb-akhilesh thanks for the additional information! I still could not reproduce it locally but I noticed there was unnecessary resizing updates which I've eliminated. Once PR gets released I'd appreciate if you could tell whether the issue is fixed or not. If this does not help I'd also appreciate if we could schedule a call

**Comment by hb-akhilesh** [comment]
Sure. I shall keep the tab open for next few days 😃

**Comment by hb-akhilesh** [comment]
I see this has been marked to milestone v0.50.14 . Once released, I shall
test.

**Comment by hb-akhilesh** [comment]
Upgraded to [0.50.15](https://github.com/metabase/metabase/milestone/256), I don't see the behaviour.

Though I see another problem:

The x axis is hidden now. 

<img width="1325" alt="image" src="https://github.com/user-attachments/assets/a523c97a-613f-42fa-895b-b6e2d01ff8ab">

**Comment by hb-akhilesh** [comment]
Though If I open the browser console, then it shows
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/462576c6-cf19-43ee-90be-e89c51e7d6ce">
