### ISSUE TITLE
Sharing and embedding link permissions are messed up

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4552]
As I understand it, right now we've implemented public sharing and iframe embedding such that only admins can turn public links on for a given artifact. Right now, if an admin enables sharing on a dashboard or saved question, a non-admin user can then see the share icon. Clicking on that icon results in a blank screen and breaks all navigation until a hard refresh.

If sharing is enabled on a given artifact, I believe the expected behavior is either A) the non-admin user shouldn't see the share icon, or B) the non-admin should be able to see it and click on it and use the public link or embedding snippet, but should not be able to turn sharing for that item off, nor should they see the application embedding option.

I've been a little removed from the discussions around this feature, so please correct me if I'm wrong here.

This is on Chrome on the 0.23 release branch. Here's the JS log:
![screen shot 2017-03-20 at 5 34 25 pm](https://cloud.githubusercontent.com/assets/2223916/24127641/8416bfd0-0d93-11e7-9b77-f5e50c9427b0.png)

Nothing found in the server logs.

**Comment by salsakran** [comment]
I think (B) should be the behaviour, fwiw.

**Comment by tlrobinson** [comment]
@mazameli i'm only seeing this on dashboards, not questions, which doesn't show the icon at all. Is that correct?

**Comment by salsakran** [comment]
closed via #4552
