### ISSUE TITLE
Duplicate Dashboard with Action

### ISSUE THREAD

**Issue by MateusRamos10** [metabase/metabase#45525]
### Describe the bug

Guys, I went to duplicate a dashboard that has actions and it gave the image error, if I fill in some parameters like description or archived via the api, is it possible to duplicate a dashboard with action?

![bug metabase dashboard duplicate](https://github.com/user-attachments/assets/116c295d-984a-4063-913d-d1def74b3ab7)

### To Reproduce

1. Go to your Dashboard that has Action
2. Click on Duplicate Dashboard
3. See this error

### Information about your Metabase installation

```JSON
- Metabase version: v0.49.20
```

### Severity

Low Severity

**Comment by bshepherdson** [comment]
Needs investigation to see whether this is a FE or BE issue.

**Comment by kulyk** [comment]
Possibly a duplicate of #38224

**Comment by kulyk** [comment]
Duplicate of https://github.com/metabase/metabase/issues/38224
