### ISSUE TITLE
Metabase v0.50.12 broken migration

### ISSUE THREAD

**Issue by truckpad-dev** [metabase/metabase#45530]
### Describe the bug

When updating to the latest version of Metabase, v0.50.12 one migration fails to execute due to sql error.

Tried going back to version v0.50.11 but got stuck in the same migration somehow.

Finally went back to v0.50.10 then it booted up no problems.

### To Reproduce

1. Have the version v0.50.10 installed
2. Restart Pod and get the latest image or update to the latest version v0.50.12
3. Se error then booting up the server

### Expected behavior

The migrations should run as expected and the server would run without problems.

### Logs

[service.log](https://github.com/user-attachments/files/16228145/service.log)

### Information about your Metabase installation

```JSON
- GCP K8s with metabase/metabase:latest image
```

### Severity

Blocking usage

**Comment by qnkhuat** [comment]
Please update your Postgres version to 12+ and try again. 11.22 has gone out of support 8 months ago https://endoflife.date/postgresql
