### ISSUE TITLE
Feature Request: Common Table Expressions

### ISSUE THREAD

**Issue by barillax** [metabase/metabase#4555]
### Summary

Many of our most interesting internal analytics queries make heavy use of common table expressions, aka WITH queries. Unfortunately, the JDBC connector used in metabase apparently doesn't support more than one query.

It would be ideal if the Raw SQL mode allowed these sorts of advanced queries. As is, the tool is less useful for team members with advanced SQL knowledge.

### Example Query

`WITH sub_query AS (select * from users limit 1) select * from sub_query;`

This works fine in a normal querying environment, but results in the following error in Metabase:

`Syntax error in SQL statement " WITH TESTING_QUERY AS[*] (SELECT * FROM USERS LIMIT 1) SELECT * FROM TESTING_QUERY; "; expected "., ("; SQL statement: -- Metabase:: userID: 1 executionID: 2d597259-eed2-4546-b754-3f6a189ab56c queryType: native queryHash: 1582907852 with testing_query as (select * from users limit 1) select * from testing_query; [42001-193]
`

### Alternative Approaches

We haven't been able to find an adequate workaround so we've had to switch back to Redash 😢

**Comment by salsakran** [comment]
Side question : 

Are these common table expressions shared?

These sound like candidates for #1825 or something similar to how we treat segments + metrics.

**Comment by salsakran** [comment]
I think the main story is that we originally didn't want to do any parsing of SQL, and if we split on ";", we'd need to deal with escaping, etc. 

I forget the exact details of the JDBC one-statement per call, @camsaul do you remember the exact story here?

**Comment by barillax** [comment]
Sometimes these queries are shared, true, but just as often they're a convenient way to break up a complicated query, especially when doing cohort-style analysis, where it's handy to piece the data together in several steps, with CTEs forming temporary tables at each step, e.g.:

`
WITH pool_of_data AS ( 
    ...
),
step_1 AS (
    ...
),
step_2 AS (
   ...
)
step_3 AS (
   ...
)
SELECT * from step_3 ORDER BY created_at ASC;
`

It's also handy for debugging, since you can easily change the last query to inspect one of the sub-queries if things look odd.

**Comment by wvengen** [comment]
I seem to be able to use CTEs without a problem, using PostgreSQL:

```sql
WITH
  foo AS (SELECT UNNEST(ARRAY[1,2,3,4]) i),
  bar AS (SELECT i, i+1 AS j FROM foo)
SELECT * FROM bar;
```

yield a list of numbers in Metabase.

Metabase version 1f022e970e5b166cc81a7f6b1bc2d72e0fb01d42, PostgreSQL version 9.6.1.

**Comment by barillax** [comment]
@wvengen interesting! That same query gives me the following error:

`Syntax error in SQL statement " WITH FOO AS[*] (SELECT UNNEST(ARRAY[1,2,3,4]) I), BAR AS (SELECT I, I+1 AS J FROM FOO) SELECT * FROM BAR; "; expected "., ("; SQL statement: -- Metabase:: userID: 1 executionID: fea0e955-0e6d-485c-b450-d8757e268db1 queryType: native queryHash: -124515155 WITH foo AS (SELECT UNNEST(ARRAY[1,2,3,4]) i), bar AS (SELECT i, i+1 AS j FROM foo) SELECT * FROM bar; [42001-193]`

I'm running the local metabase app on Mac OS. I wonder if this could be limited to that version?

**Comment by barillax** [comment]
PS: my remote database is also PostgreSQL v. 9.6.1! Metabase reports version 0.22.2.1.

**Comment by barillax** [comment]
OK, I think I got it working. I can't reproduce the behavior yet, but I believe the problem was that the Database selector was indicating my remote DB, but in fact was stuck querying the "Sample Data" database!

After restarting metabase, I ran the queries again and the errors went away 😒 

I'll close this ticket and re-open a new one if I can reproduce the "sticky database selection" oddness!
