### ISSUE TITLE
We don't cancel queries when the user closes the tab

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#45571]
### Describe the bug

While investigating https://github.com/metabase/metabase/issues/15817, I found that we don't cancel the running queries in v50.13 when we close the tab

### To Reproduce

1) spin up v50 with Oracle
2) create a dashboard with sql questions
TIP: USE
```
DECLARE
  v_start TIMESTAMP;
  v_result NUMBER;
BEGIN
  v_start := SYSTIMESTAMP;
  LOOP
    IF SYSTIMESTAMP >= v_start + INTERVAL '60' SECOND THEN
      v_result := 1;
      EXIT;
    END IF;
  END LOOP;
  
  -- 1
  DBMS_OUTPUT.PUT_LINE('Result: ' || v_result);
END;
```
to create queries that take 60 seconds
3) run it
4) close the tab in 30 seconds, on a new tab run the dashboard again

you'll see that there's no cancellation of queries in the logs and also the second dashboard will take more than the first one, since Metabase is still holding the connections

### Expected behavior

We always closed the connections when the tab is closed

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P1

### Additional context

NOTE: I started testing this with Oracle but the same thing happens on postgres and most probably many other databases

**Comment by sabyasachinandy** [comment]
@bshepherdson When we used 0.39.6 this used to work for  us with the default presto-jdbc driver for both dashboard and questions. Any help on how we can verify if this is not a driver specific issue? We are using trino starburst driver on 0.50.0

**Comment by lbrdnk** [comment]
FWIW, it could be worth looking a the traces using `jconsole` to see where those threads are clogged as described in [this comment](https://github.com/metabase/metabase/issues/45910#issuecomment-2283538552). And also observing the behavior in/after the moment when the limits those variables represent are reached.

**Comment by paoliniluis** [comment]
now we do after https://github.com/metabase/metabase/pull/47740
