### ISSUE TITLE
Slow dashboard timing calls on a public dashboard trigger auth check

### ISSUE THREAD

**Issue by sailxjx** [metabase/metabase#4557]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome  56.0.2924.87

- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X 10.12.3

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Redshift

- Metabase version: (e.x. 0.19.3)
0.23.0

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
docker

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
postgres

When access metabase with public link and the dataset need a lot of time to load, metabase will post an request on `/api/dataset/duration`, which return 404 in response.

And, when user anonymous visit public link, the `duration` request will return 401 and redirect to an 
404 not found page. This maybe another problem.

<img width="583" alt="2017-03-21 16 24 17" src="https://cloud.githubusercontent.com/assets/909853/24138615/dda0e9a2-0e53-11e7-8107-70ee61db5305.png">

Thanks for being part of the Metabase project!
-------

**Comment by camsaul** [comment]
The `POST /api/dataset/duration/` endpoint checks whether you have read permissions for the `database` in the query so it will return a 404 if there is no database and a 401 if you don't have permissions to view it, or if you're not logged in

We shouldn't be hitting endpoints that require auth if we're not logged in

**Comment by salsakran** [comment]
This is also a great reason to pre-compute average card load times rather than having big chunks of the dashboard code do different things for logged in vs non-logged in users.

**Comment by drorm** [comment]
#4644 is related and possibly a dup of this one.

**Comment by tlrobinson** [comment]
@salsakran Do we want to:

1. disable the duration estimates for public/embed
2. return the estimates for each query in the initial request to the dashboard (we'd probably want to start saying `query-hash` on the card so we can do that with a join)
3. add public/embed endpoints for duration

1 is definitely the easiest (a couple lines on the frontend), 2 and 3 require backend work

**Comment by salsakran** [comment]
I think 2 is the path of least overall complexity.

**Comment by tlrobinson** [comment]
Ok.

@camsaul we'll need to add `average_execution_time` to each `card` (including `series`) returned in each `dashcard` in dashboards (on all 3 dashboard endpoints).

I'm guessing we'll want to add a `query_hash` field to `report_card` (and make sure it's updated when `query` is) to make that efficient.

**Comment by camsaul** [comment]
Alright @tlrobinson backend to power this is ready in PR #4883
