### ISSUE TITLE
SSL / HTTPS for the docker container?

### ISSUE THREAD

**Issue by dholdaway** [metabase/metabase#4558]
Hello, 

I am running a selection of metabase containers on a host and doing the redirecting via Nginx 

I want to enable SSL on our main container, but I am unsure how to run the Docker container at the moment I am using

`sudo docker run -d -p 3000:3000 -e "MB_DB_TYPE=XXX" -e "MB_DB_DBNAME=XXX" -e "MB_DB_PORT=XXX" -e "MB_DB_USER=XXX" -e "MB_DB_PASS=XXXX" -e "MB_DB_HOST=XXXX" --name metabase-production metabase/metabase:v0.21.1
`
do i need to use NGINX_FORCE_SSL in the nginx conf?

**Comment by tlrobinson** [comment]
If you're terminating SSL in nginx this doesn't seem like a Metabase specific question. Our container doesn't include/run nginx. Check the documentation for your nginx container.

If you want to terminate SSL in Metabase itself, look at the section called "Using HTTPS with Metabase": http://www.metabase.com/docs/latest/operations-guide/start.html You'll need to include a JKS keystore in a volume in the Metabase container, and set the appropriate environment variables.

**Comment by chavenor** [comment]
I saw this but I have it working with this nginx config.   What issues did you run into @dholdaway? 

You would have to replace your ```<<your-site>>```.  

NOTE: I'm importing the self-generated CERTBOT ```options-ssl-nginx.con```

```nginx
#Metrics
############################################################
server {
  listen 80;
  listen [::]:443 ssl ipv6only=on; # managed by Certbot
  listen 443 ssl; # managed by Certbot
  server_name metrics.<<your-site>>.com
  ssl on;
  ssl_certificate     /etc/letsencrypt/live/metrics.<<your-site>>.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/metrics.<<your-site>>.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  add_header Front-End-Https on;
  add_header X-Content-Type-Options nosniff;
  access_log /var/log/nginx/<<your-site>>.access.log combined;
  error_log /var/log/nginx/<<your-site>>.error.log;
  location / {
          proxy_pass http://127.0.0.1:3000;
          proxy_set_header Host $host;
          proxy_redirect off;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
      }
  }
##########################################################
```

**Comment by dholdaway** [comment]
hey, I resolved this last year.

**Comment by LynceanP** [comment]
@dholdaway How do you resolve it ?

**Comment by alinoudev** [comment]
Hi Guys,
You can easily do this with Cloudflare SSL flexible option. If you have option of cloudflare you can easily do it. If some one has problem in configuration one can message me.

**Comment by fooddudesdelivery** [comment]
@alinoudev yes can you help us do it with cloud fare

**Comment by alinoudev** [comment]
@fooddudesdelivery sure you can email me at ali@alinoudev.com Many thanks!
