### ISSUE TITLE
Dashboard subscription mail sent multiple in v0.50.x

### ISSUE THREAD

**Issue by CZvacko** [metabase/metabase#45622]
### Describe the bug

After updating from version 0.49.4 to v0.50.6, one of the Dashboard subscriptions started sending 3 copies of the same email instead of one. A week later it started sending 4 copies. Then I updated to v0.50.11, issue remains. I also reacreated subscription of dashboard, issue still remains.

The other subscriptions seem to be fine, only one is facing this problem, its settings is unchanged (between 0.49 and 0.50).

Other users also face this [issue](https://discourse.metabase.com/t/dashboard-subscription-mail-sent-3x-in-v0-50/130080/4). 

### To Reproduce

Hard to reproduce, not all subscriptions face this issue:
-have dashboard with one question inside
-question use Table visualisation (no any setting inside)
-dashboard has one Date filter, set Today as default value
Subscription setting is:
Sent daily, Don't send if there aren't results, Attach results

### Expected behavior

Send single email same as previously...

### Logs

Troubleshooting logs (4th line is probably other subscription because have other pulse-id)
![image](https://github.com/user-attachments/assets/5a5ca1be-e4d0-4b99-971e-4b8efa926bba)

### Information about your Metabase installation

```JSON
v0.50.6 and v0.50.11
```

### Severity

low

**Comment by qnkhuat** [comment]
Hey, Thanks for reporting.

It'd help if you could give us the task history of send-pulse tasks by executing this query

```sql
select * from task_history where task = 'send-pulse' order by started_at desc limit 100;
```

Also, what does the query of the question look like?

**Comment by CZvacko** [comment]
Here is output for task_history
Note: since dashboard have Date filter = Today, not every day have results, like once per week. 
2024-07-15 with results, 2024-07-16 without results.
|    id   |    task    | db_id |         started_at         |          ended_at          | duration |            task_details            |  status |
|:-------:|:----------:|:-----:|:--------------------------:|:--------------------------:|:--------:|:----------------------------------:|:-------:|
| 4998826 | send-pulse | NULL  | 2024-07-16 08:00:00.006530 | 2024-07-16 08:00:00.022154 | 11       | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998683 | send-pulse | NULL  | 2024-07-16 07:00:00.015459 | 2024-07-16 07:00:00.023437 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998682 | send-pulse | NULL  | 2024-07-16 06:00:01.033857 | 2024-07-16 06:00:01.162477 | 128      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4998681 | send-pulse | NULL  | 2024-07-16 06:00:00.860705 | 2024-07-16 06:00:00.988953 | 128      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4998680 | send-pulse | NULL  | 2024-07-16 06:00:00.687150 | 2024-07-16 06:00:00.812807 | 126      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4998679 | send-pulse | NULL  | 2024-07-16 06:00:00.499662 | 2024-07-16 06:00:00.638284 | 137      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4998678 | send-pulse | NULL  | 2024-07-16 06:00:00.340931 | 2024-07-16 06:00:00.455642 | 115      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4998677 | send-pulse | NULL  | 2024-07-16 06:00:00.198348 | 2024-07-16 06:00:00.302037 | 104      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4998676 | send-pulse | NULL  | 2024-07-16 06:00:00.032137 | 2024-07-16 06:00:00.037123 | 5        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998675 | send-pulse | NULL  | 2024-07-16 06:00:00.013217 | 2024-07-16 06:00:00.158429 | 145      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4998622 | send-pulse | NULL  | 2024-07-16 05:00:00.956293 | 2024-07-16 05:00:01.222637 | 265      | {"pulse-id":13,"channel-ids":[13]} | success |
| 4998621 | send-pulse | NULL  | 2024-07-16 05:00:00.859557 | 2024-07-16 05:00:01.082495 | 223      | {"pulse-id":12,"channel-ids":[12]} | success |
| 4998620 | send-pulse | NULL  | 2024-07-16 05:00:00.646060 | 2024-07-16 05:00:00.908423 | 262      | {"pulse-id":13,"channel-ids":[13]} | success |
| 4998619 | send-pulse | NULL  | 2024-07-16 05:00:00.588218 | 2024-07-16 05:00:00.816674 | 228      | {"pulse-id":12,"channel-ids":[12]} | success |
| 4998618 | send-pulse | NULL  | 2024-07-16 05:00:00.338898 | 2024-07-16 05:00:00.590213 | 251      | {"pulse-id":13,"channel-ids":[13]} | success |
| 4998617 | send-pulse | NULL  | 2024-07-16 05:00:00.314964 | 2024-07-16 05:00:00.533368 | 218      | {"pulse-id":12,"channel-ids":[12]} | success |
| 4998616 | send-pulse | NULL  | 2024-07-16 05:00:00.054989 | 2024-07-16 05:00:00.060972 | 6        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998615 | send-pulse | NULL  | 2024-07-16 05:00:00.038035 | 2024-07-16 05:00:00.302997 | 264      | {"pulse-id":13,"channel-ids":[13]} | success |
| 4998614 | send-pulse | NULL  | 2024-07-16 05:00:00.015097 | 2024-07-16 05:00:00.279061 | 263      | {"pulse-id":12,"channel-ids":[12]} | success |
| 4998610 | send-pulse | NULL  | 2024-07-16 04:00:00.012128 | 2024-07-16 04:00:00.020107 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998470 | send-pulse | NULL  | 2024-07-16 03:00:00.014831 | 2024-07-16 03:00:00.031078 | 9        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998463 | send-pulse | NULL  | 2024-07-16 02:00:00.017905 | 2024-07-16 02:00:00.033528 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998320 | send-pulse | NULL  | 2024-07-16 01:00:00.014477 | 2024-07-16 01:00:00.022455 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998317 | send-pulse | NULL  | 2024-07-16 00:00:00.015001 | 2024-07-16 00:00:00.024973 | 9        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998129 | send-pulse | NULL  | 2024-07-15 23:00:00.016239 | 2024-07-15 23:00:00.025214 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4998128 | send-pulse | NULL  | 2024-07-15 22:00:00.013978 | 2024-07-15 22:00:00.021956 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997937 | send-pulse | NULL  | 2024-07-15 21:00:00.015767 | 2024-07-15 21:00:00.026765 | 10       | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997930 | send-pulse | NULL  | 2024-07-15 20:00:00.015819 | 2024-07-15 20:00:00.024794 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997787 | send-pulse | NULL  | 2024-07-15 19:00:00.019305 | 2024-07-15 19:00:00.027284 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997786 | send-pulse | NULL  | 2024-07-15 18:00:00.014263 | 2024-07-15 18:00:00.022241 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997643 | send-pulse | NULL  | 2024-07-15 17:00:00.065778 | 2024-07-15 17:00:00.070765 | 5        | {"pulse-id":4,"channel-ids":[4]}   | success |
| 4997642 | send-pulse | NULL  | 2024-07-15 17:00:00.049822 | 2024-07-15 17:00:00.055806 | 6        | {"pulse-id":3,"channel-ids":[3]}   | success |
| 4997641 | send-pulse | NULL  | 2024-07-15 17:00:00.032869 | 2024-07-15 17:00:00.042842 | 9        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997640 | send-pulse | NULL  | 2024-07-15 17:00:00.014216 | 2024-07-15 17:00:05.104086 | 5089     | {"pulse-id":5,"channel-ids":[5]}   | success |
| 4997636 | send-pulse | NULL  | 2024-07-15 16:00:00.016321 | 2024-07-15 16:00:00.025297 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997496 | send-pulse | NULL  | 2024-07-15 15:00:00.016826 | 2024-07-15 15:00:00.025802 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997492 | send-pulse | NULL  | 2024-07-15 14:00:00.010987 | 2024-07-15 14:00:00.018965 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997343 | send-pulse | NULL  | 2024-07-15 13:00:00.012903 | 2024-07-15 13:00:00.020881 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997341 | send-pulse | NULL  | 2024-07-15 12:00:00.015462 | 2024-07-15 12:00:00.022444 | 6        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997198 | send-pulse | NULL  | 2024-07-15 11:00:00.018298 | 2024-07-15 11:00:00.026245 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997197 | send-pulse | NULL  | 2024-07-15 10:00:00.011858 | 2024-07-15 10:00:00.017842 | 5        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997050 | send-pulse | NULL  | 2024-07-15 09:00:00.978657 | 2024-07-15 09:00:01.433477 | 446      | {"pulse-id":14,"channel-ids":[14]} | success |
| 4997049 | send-pulse | NULL  | 2024-07-15 09:00:00.916149 | 2024-07-15 09:00:01.292862 | 373      | {"pulse-id":15,"channel-ids":[15]} | success |
| 4997048 | send-pulse | NULL  | 2024-07-15 09:00:00.806836 | 2024-07-15 09:00:01.511577 | 702      | {"pulse-id":16,"channel-ids":[16]} | success |
| 4997045 | send-pulse | NULL  | 2024-07-15 09:00:00.509446 | 2024-07-15 09:00:00.947417 | 437      | {"pulse-id":14,"channel-ids":[14]} | success |
| 4997044 | send-pulse | NULL  | 2024-07-15 09:00:00.493826 | 2024-07-15 09:00:00.869316 | 384      | {"pulse-id":15,"channel-ids":[15]} | success |
| 4997040 | send-pulse | NULL  | 2024-07-15 09:00:00.061615 | 2024-07-15 09:00:00.077288 | 6        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997039 | send-pulse | NULL  | 2024-07-15 09:00:00.061615 | 2024-07-15 09:00:00.775604 | 713      | {"pulse-id":16,"channel-ids":[16]} | success |
| 4997038 | send-pulse | NULL  | 2024-07-15 09:00:00.045995 | 2024-07-15 09:00:00.431372 | 393      | {"pulse-id":15,"channel-ids":[15]} | success |
| 4997037 | send-pulse | NULL  | 2024-07-15 09:00:00.014751 | 2024-07-15 09:00:00.462613 | 446      | {"pulse-id":14,"channel-ids":[14]} | success |
| 4997036 | send-pulse | NULL  | 2024-07-15 08:00:00.053785 | 2024-07-15 08:00:00.053785 | 5        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4997035 | send-pulse | NULL  | 2024-07-15 08:00:00.038166 | 2024-07-15 08:00:25.408963 | 25371    | {"pulse-id":8,"channel-ids":[8]}   | success |
| 4997034 | send-pulse | NULL  | 2024-07-15 08:00:00.006891 | 2024-07-15 08:00:17.545975 | 17535    | {"pulse-id":9,"channel-ids":[9]}   | success |
| 4996978 | send-pulse | NULL  | 2024-07-15 07:00:00.033598 | 2024-07-15 07:00:00.039554 | 5        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996977 | send-pulse | NULL  | 2024-07-15 07:00:00.014622 | 2024-07-15 07:00:27.330058 | 27316    | {"pulse-id":2,"channel-ids":[2]}   | success |
| 4996976 | send-pulse | NULL  | 2024-07-15 06:00:00.966295 | 2024-07-15 06:00:01.224529 | 258      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4996975 | send-pulse | NULL  | 2024-07-15 06:00:00.674277 | 2024-07-15 06:00:00.921418 | 246      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4996974 | send-pulse | NULL  | 2024-07-15 06:00:00.379082 | 2024-07-15 06:00:00.630425 | 252      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4996973 | send-pulse | NULL  | 2024-07-15 06:00:00.035829 | 2024-07-15 06:00:00.042810 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996972 | send-pulse | NULL  | 2024-07-15 06:00:00.015883 | 2024-07-15 06:00:00.333238 | 317      | {"pulse-id":21,"channel-ids":[21]} | success |
| 4996919 | send-pulse | NULL  | 2024-07-15 05:00:00.983342 | 2024-07-15 05:00:01.225686 | 241      | {"pulse-id":12,"channel-ids":[12]} | success |
| 4996918 | send-pulse | NULL  | 2024-07-15 05:00:00.728963 | 2024-07-15 05:00:01.019244 | 290      | {"pulse-id":13,"channel-ids":[13]} | success |
| 4996917 | send-pulse | NULL  | 2024-07-15 05:00:00.657157 | 2024-07-15 05:00:00.936928 | 279      | {"pulse-id":12,"channel-ids":[12]} | success |
| 4996916 | send-pulse | NULL  | 2024-07-15 05:00:00.380906 | 2024-07-15 05:00:00.662144 | 281      | {"pulse-id":13,"channel-ids":[13]} | success |
| 4996915 | send-pulse | NULL  | 2024-07-15 05:00:00.338422 | 2024-07-15 05:00:00.603303 | 264      | {"pulse-id":12,"channel-ids":[12]} | success |
| 4996914 | send-pulse | NULL  | 2024-07-15 05:00:00.051197 | 2024-07-15 05:00:00.057181 | 6        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996913 | send-pulse | NULL  | 2024-07-15 05:00:00.032249 | 2024-07-15 05:00:00.343408 | 310      | {"pulse-id":13,"channel-ids":[13]} | success |
| 4996912 | send-pulse | NULL  | 2024-07-15 05:00:00.013328 | 2024-07-15 05:00:00.299527 | 286      | {"pulse-id":12,"channel-ids":[12]} | success |
| 4996908 | send-pulse | NULL  | 2024-07-15 04:00:00.018233 | 2024-07-15 04:00:00.027209 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996768 | send-pulse | NULL  | 2024-07-15 03:00:00.016852 | 2024-07-15 03:00:00.027928 | 11       | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996761 | send-pulse | NULL  | 2024-07-15 02:00:00.017766 | 2024-07-15 02:00:00.024740 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996618 | send-pulse | NULL  | 2024-07-15 01:00:00.016358 | 2024-07-15 01:00:00.025305 | 9        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996615 | send-pulse | NULL  | 2024-07-15 00:00:00.019257 | 2024-07-15 00:00:00.027235 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996427 | send-pulse | NULL  | 2024-07-14 23:00:00.015090 | 2024-07-14 23:00:00.022071 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996426 | send-pulse | NULL  | 2024-07-14 22:00:00.015273 | 2024-07-14 22:00:00.024249 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996235 | send-pulse | NULL  | 2024-07-14 21:00:00.013862 | 2024-07-14 21:00:00.021841 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996228 | send-pulse | NULL  | 2024-07-14 20:00:00.019124 | 2024-07-14 20:00:00.027072 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996085 | send-pulse | NULL  | 2024-07-14 19:00:00.015302 | 2024-07-14 19:00:00.023280 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4996084 | send-pulse | NULL  | 2024-07-14 18:00:00.016250 | 2024-07-14 18:00:00.026232 | 9        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995896 | send-pulse | NULL  | 2024-07-14 17:00:00.741565 | 2024-07-14 17:00:01.073783 | 332      | {"pulse-id":5,"channel-ids":[5]}   | success |
| 4995895 | send-pulse | NULL  | 2024-07-14 17:00:00.370032 | 2024-07-14 17:00:00.700129 | 331      | {"pulse-id":5,"channel-ids":[5]}   | success |
| 4995891 | send-pulse | NULL  | 2024-07-14 17:00:00.065745 | 2024-07-14 17:00:00.074721 | 9        | {"pulse-id":4,"channel-ids":[4]}   | success |
| 4995890 | send-pulse | NULL  | 2024-07-14 17:00:00.049788 | 2024-07-14 17:00:00.055772 | 5        | {"pulse-id":3,"channel-ids":[3]}   | success |
| 4995889 | send-pulse | NULL  | 2024-07-14 17:00:00.033832 | 2024-07-14 17:00:00.040813 | 6        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995888 | send-pulse | NULL  | 2024-07-14 17:00:00.011927 | 2024-07-14 17:00:00.331139 | 319      | {"pulse-id":5,"channel-ids":[5]}   | success |
| 4995884 | send-pulse | NULL  | 2024-07-14 16:00:00.017200 | 2024-07-14 16:00:00.026169 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995696 | send-pulse | NULL  | 2024-07-14 15:00:00.018011 | 2024-07-14 15:00:00.026986 | 9        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995692 | send-pulse | NULL  | 2024-07-14 14:00:00.010510 | 2024-07-14 14:00:00.022478 | 12       | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995495 | send-pulse | NULL  | 2024-07-14 13:00:00.013901 | 2024-07-14 13:00:00.021879 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995493 | send-pulse | NULL  | 2024-07-14 12:00:00.016218 | 2024-07-14 12:00:00.027190 | 10       | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995302 | send-pulse | NULL  | 2024-07-14 11:00:00.014267 | 2024-07-14 11:00:00.022244 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995301 | send-pulse | NULL  | 2024-07-14 10:00:00.017632 | 2024-07-14 10:00:00.026604 | 8        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995106 | send-pulse | NULL  | 2024-07-14 09:00:00.993143 | 2024-07-14 09:00:01.419613 | 426      | {"pulse-id":14,"channel-ids":[14]} | success |
| 4995105 | send-pulse | NULL  | 2024-07-14 09:00:00.743196 | 2024-07-14 09:00:01.108803 | 366      | {"pulse-id":15,"channel-ids":[15]} | success |
| 4995102 | send-pulse | NULL  | 2024-07-14 09:00:00.518810 | 2024-07-14 09:00:00.946248 | 427      | {"pulse-id":14,"channel-ids":[14]} | success |
| 4995098 | send-pulse | NULL  | 2024-07-14 09:00:00.076854 | 2024-07-14 09:00:00.082838 | 6        | {"pulse-id":17,"channel-ids":[17]} | success |
| 4995097 | send-pulse | NULL  | 2024-07-14 09:00:00.061894 | 2024-07-14 09:00:01.010073 | 948      | {"pulse-id":16,"channel-ids":[16]} | success |
| 4995096 | send-pulse | NULL  | 2024-07-14 09:00:00.043968 | 2024-07-14 09:00:00.701311 | 657      | {"pulse-id":15,"channel-ids":[15]} | success |
| 4995095 | send-pulse | NULL  | 2024-07-14 09:00:00.013057 | 2024-07-14 09:00:00.462963 | 449      | {"pulse-id":14,"channel-ids":[14]} | success |
| 4995094 | send-pulse | NULL  | 2024-07-14 08:00:00.015156 | 2024-07-14 08:00:00.023134 | 7        | {"pulse-id":17,"channel-ids":[17]} | success |

Here is output for qrtz_cron_triggers:
|     SCHED_NAME    |                    TRIGGER_NAME                   | TRIGGER_GROUP | CRON_EXPRESSION | TIME_ZONE_ID |   |   |   |
|:-----------------:|:-------------------------------------------------:|:-------------:|:---------------:|:------------:|---|---|---|
| MetabaseScheduler | metabase.task.send-pulse.trigger.21.0_0_6_*_*_?_* | DEFAULT       | 0 0 6 * * ? *   | Europe/Paris |   |   |   |

Dashboard look like this (contains sensitive employee data)
![image](https://github.com/user-attachments/assets/39366b10-d3ae-4a48-bdfe-2cd35d79be6f)

And the question is based on DB view, so in visual editor I just set order of DATUM_NASTUPU to be descending

**Comment by qnkhuat** [comment]
It's having multiple task history so I suspect this is quartz issue where it's being triggered multiple times.

Can you do another query:

```sql
select * from qrtz_triggers where job_name = 'metabase.task.send-pulses.send-pulse.job';
```

**Comment by CZvacko** [comment]
Here is it 
|     SCHED_NAME    |                    TRIGGER_NAME                   | TRIGGER_GROUP |                 JOB_NAME                 | JOB_GROUP | DESCRIPTION | NEXT_FIRE_TIME | PREV_FIRE_TIME | PRIORITY | TRIGGER_STATE | TRIGGER_TYPE |   START_TIME  | END_TIME | CALENDAR_NAME | MISFIRE_INSTR |   JOB_DATA  |
|:-----------------:|:-------------------------------------------------:|:-------------:|:----------------------------------------:|:---------:|:-----------:|:--------------:|:--------------:|:--------:|:-------------:|:------------:|:-------------:|:--------:|:-------------:|:-------------:|:-----------:|
| MetabaseScheduler | metabase.task.send-pulse.trigger.12.0_0_5_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721271600000  | -1             | 3596     | WAITING       | CRON         | 1721185203000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.13.0_0_5_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721271600000  | -1             | 3596     | WAITING       | CRON         | 1721185203000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.14.0_0_9_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721199600000  | -1             | 3599     | WAITING       | CRON         | 1721113201000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.15.0_0_9_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721199600000  | -1             | 3599     | WAITING       | CRON         | 1721113201000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.16.0_0_9_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721199600000  | -1             | 3599     | WAITING       | CRON         | 1721113201000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.17.0_0_*_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721199600000  | 1721196000000  | 6        | WAITING       | CRON         | 1718976821000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.2.0_0_7_?_*_2_*  | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721624400000  | -1             | 3572     | WAITING       | CRON         | 1721019627000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.21.0_0_6_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721275200000  | -1             | 3599     | WAITING       | CRON         | 1721188801000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.3.0_0_17_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721228400000  | 1721142000000  | 6        | WAITING       | CRON         | 1718976821000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.4.0_0_17_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721228400000  | 1721142000000  | 6        | WAITING       | CRON         | 1718976822000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.5.0_0_17_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721228400000  | -1             | 3594     | WAITING       | CRON         | 1721142005000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.7.0_0_1_?_*_6_*  | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721343600000  | -1             | 3597     | WAITING       | CRON         | 1720738802000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.8.0_0_8_?_*_2_*  | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721628000000  | -1             | 3574     | WAITING       | CRON         | 1721023225000 | 0        | NULL          | 1             | 1 070 bajtů |
| MetabaseScheduler | metabase.task.send-pulse.trigger.9.0_0_8_?_*_2_*  | DEFAULT       | metabase.task.send-pulses.send-pulse.job | DEFAULT   | NULL        | 1721628000000  | -1             | 3582     | WAITING       | CRON         | 1721023217000 | 0        | NULL          | 1             | 1 070 bajtů |

(I used markdown table generator, not many efforts for me...)

**Comment by qnkhuat** [comment]
I can reproduce and will have a fix soon

**Comment by Praesklepios** [comment]
So for me this issue still persists even after updating to v0.50.19.4. Three reports are send out every time a subscription is triggered. I newly set up every subscription by now. When testing a subscription manually (send email now Button) this problem doesn't occur.
