### ISSUE TITLE
Search not working in aggregations picker

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#45702]
### Describe the bug

![image](https://github.com/user-attachments/assets/dd573c63-0c8c-4bb4-a78c-58d8d6c97ce0)

### To Reproduce

1. Go to stats
2. New > Question
3. Search for a model called "Pull Request Review" and use it
4. Add a Count aggregation (notice that there is no search in the popover)
5. Try to add another aggregation

This time search is shown in the popover.
If you try to use it, all options disappear (except "Custom Expression")

### Expected behavior

Search should not be available

### Information about your Metabase installation

stats @ 8aeebaa

### Severity

P3/P2

### Additional context

I was not able to reproduce it locally

**Comment by romeovs** [comment]
This will be fixed by https://github.com/metabase/metabase/pull/46887

**Comment by romeovs** [comment]
We've fixed this in #46887 by making the Basic Metrics available to the search bar.
