### ISSUE TITLE
Can not reset user's password

### ISSUE THREAD

**Issue by FlorianGlinko** [metabase/metabase#45704]
**Describe the bug**

Hello, I am Florian from Glinko. I apologize in advance I don't know how to send you the logs. I am a simple user administrator on Metabase. 
I have a user who has been unable to log in since last night. I tried to reset his password from the administration console. The button is present but there is no action when the button is clicked. My user can't reset it either. The user is : mehdi.bouzemboua@glinko.fr

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "6.1.0-20-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-03",
      "tag": "v0.37.3",
      "branch": "release-x.37.x",
      "hash": "2f1e783"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by bshepherdson** [comment]
@FlorianGlinko You can hit Ctrl+F1 (Cmd+F1 on Mac) in Metabase to capture a bug report. That will include both server and client logs.

Can you try to reset the password again and then capture that report and attach the file to this bug?

**Comment by luizarakaki** [comment]
Please upgrade to v49. We don't support releases this old.

**Comment by FlorianGlinko** [comment]
Ok, thank you for your time. Metabase is connected with our production tool, I am afraid to break some components.
