### ISSUE TITLE
Stacked bar chart "Stack values to show" setting produces "Cannot read properties of undefined" error

### ISSUE THREAD

**Issue by phantom943** [metabase/metabase#45717]
### Describe the bug

When selecting a value of "Stack values to show" choice to anything other than Total (e.g. Segment or Both), an error is produced by Metabase `Cannot read properties of undefined (reading 'null:value:d')`. This works on inputs with specific characteristics.

### To Reproduce

For any database engine, use the following SQL query:
```sql
    select '2024-06-23 00:00:00' as date,	'a' as value_type,	14080 as value
    UNION ALL
    select '2024-07-24 00:00:00' as date,	'd' as value_type,	0 as value
 ```
 Then build a bar chart
 X-axis: `date`, series breakout by `value_type`
 Y-axis: `value`
Set Display -> **Stacking**: Stack, **Values to show**: Some, **Stack values to show**: Segments.
Observe error `Cannot read properties of undefined (reading 'null:value:d')`

### Expected behavior

No error being produced

### Logs

This error does not occur when set **Stack values to show**: Total
This also does not happen on a different input:
```sql
    select '2024-06-23 00:00:00' as date,	'a' as value_type,	14080 as value
    UNION ALL
    select '2024-06-24 00:00:00' as date,	'd' as value_type,	0 as value
 ```
 Here the date is changed to 06-24 instead of 07-24 on a second row

### Information about your Metabase installation

```JSON
Metabase version: 0.50.13
Metabase database: postgres
```

### Severity

Annoying

**Comment by bshepherdson** [comment]
Something about the dates being in the future, perhaps.

@phantom943 Can you include more details about that error? Either capture a bug report (Ctrl-F1 or Cmd+F1 on Mac) or include a copy-paste or screenshot of the error's stack trace. With a generic JS error like that it's hard to know where to look for the problem.

**Comment by phantom943** [comment]
![image](https://github.com/user-attachments/assets/be52541e-ced8-4574-bce0-4416d5c90d0e)

Here is the screenshot of the error, because cmd+f1 seems to do nothing.
Also, the dates in the future seem not to be the cuplrit, because the error is also observed for this query:
```sql
select '2024-05-23 00:00:00' as date,	'a' as value_type,	14080 as value
    UNION ALL
    select '2024-06-24 00:00:00' as date,	'd' as value_type,	0 as value
```
