### ISSUE TITLE
Add basic auth capabilities to Druid JDBC

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#45728]
Add basic auth capabilities to Druid JDBC. It is supported by Avatica driver as per [docs](https://calcite.apache.org/avatica/docs/client_reference.html#authentication). Testing requires modification to Druid's configuration mounted to the test container.

**Comment by paoliniluis** [comment]
@davilavp please let us know if you're a paid customer so we can reorganize the priorities of this

**Comment by davilavp** [comment]
Hola @paoliniluis! 
I work in a government entity in the province of Santa Fe, Argentina. We are currently using the free version of Metabase. Right now, we are in a project that involves Druid as a data source and we need this functionality. Regarding this, we made a custom adaptation that we could use, but the ideal would be to have the official release to avoid compatibility problems in the future.
