### ISSUE TITLE
[Flaky Test]: should be possible to add and remove a metric from bookmarks

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#45740]
Last Flake: https://github.com/metabase/metabase/actions/runs/9967438512
Last Flake Time: 2024-07-16T20:34:00-07:00
Flakes in the last day: 3
Flakes in the last 3d: 3
Flakes in the last 7d: 3

**Comment by github-automation-metabase** [comment]
This test is still flaky

Last Flake: https://github.com/metabase/metabase/actions/runs/9967438512
Last Flake Time: 2024-07-16T20:34:00-07:00
Flakes in the last day: 3
Flakes in the last 3d: 3
Flakes in the last 7d: 3

**Comment by rafpaf** [comment]
Stress tested this test: https://github.com/metabase/metabase/actions/runs/12198047313/job/34028958272#step:9:237
