### ISSUE TITLE
[Flaky Test]: e2e-storage-ingestion-test

### ISSUE THREAD

**Issue by github-automation-metabase** [metabase/metabase#45747]
Last Flake: https://github.com/metabase/metabase/actions/runs/9943505153
Last Flake Time: 2024-07-15T10:29:00-07:00
Flakes in the last day: 0
Flakes in the last 3d: 1
Flakes in the last 7d: 1

**Comment by calherries** [comment]
This is still happening, just flaked for me so that's 3 times this week

**Comment by crisptrutski** [comment]
This hasn't flaked again in almost 3 weeks, so I'm not sure how much time it's worth putting into it, given the complexity of this helper. For now I'm just going to mitigate it further by increasing the number of attempts that we make.

**Comment by crisptrutski** [comment]
Jinxed it, just flaked twice this week.
