### ISSUE TITLE
Theme options for tooltip text colors and background colors for sdk

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#45764]
Tooltip looks broken in light-themed apps, because `text-*` could be set to dark colors. We need to expose a separate semantic color variable for tooltip foreground and background colors.

![Image](https://github.com/user-attachments/assets/e3a38926-05dc-4fa4-a39d-f6bb3d666a3c)

**Comment by albertoperdomo** [comment]
@heypoom Is this still relevant?

**Comment by heypoom** [comment]
@albertoperdomo this is still relevant, I visited https://embedded-analytics-sdk-demo.metabase.com/admin/products/40 and then hovered on the bar in the bar chart 

![Image](https://github.com/user-attachments/assets/18cdcbe8-8382-428f-b79e-5f034c450248)
