### ISSUE TITLE
Update aggregation picker to support interactive questions in embedding sdk

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#45766]
We should replace the use of `const question = useSelector(getQuestion)` in the aggregation picker component with one that considers the SDK context. The aggregation picker does not work in the SDK right now. We should re-add the `checkNotNull` method to `useQuestion` as well - we've temporarily removed the runtime null assertion because the SDK did not has the question in the query builder reducer, and it would crash the SDK.

**Comment by albertoperdomo** [comment]
@heypoom Is this still relevant?

**Comment by heypoom** [comment]
Tested that aggregation picker is actually working now. The question was only used for tracking the column_compare_via_shortcut event. It used to throw errors in the older versions of the SDK, but works without issues/errors now.

![Image](https://github.com/user-attachments/assets/fedbe540-8360-48f8-86c2-3f372c13a40a)
