### ISSUE TITLE
[Epic] Metrics defined on a question/model should be shown in the summarize block

### ISSUE THREAD

**Issue by mngr** [metabase/metabase#45824]
Product doc https://www.notion.so/metabase/Querying-and-combining-metrics-defined-on-the-same-data-source-1229f547df8140ce9c6f96cd707d28a5
Depends on https://github.com/metabase/metabase/pull/46054

### Describe the bug

If you create a metric that is defined on top of a model, and then start new question based on that model, you won't see this metric in the Common Metrics list in the Summarize block

### To Reproduce

1. Go to + New metric
2. Choose any model as a data source
3. Choose any aggregation
4. Save this metric
5. Go to + New question
6. Choose the same model as a data source
7. Click on Summarize
8. There is no Common metrics with your newly created metric there

### Information about your Metabase installation

```JSON
06d1ba2ae111e66253209c01c244d6379acfc6dcb1911fa9ab6012cec9ce52e5
```

### Severity

Breaks major use cases

### Implementation details

We currently allow single stage metrics only. Please note that there is a follow-up epic https://github.com/metabase/metabase/issues/46055

```[tasklist]
- [ ] Allow card-based metrics in aggregation clauses in the QP
- [ ] Return compatible card-based `:metrics` in query metadata
```

**Comment by ranquild** [comment]
We currently allow single stage metrics only. BE work
- Allow card-based metrics in aggregation clauses in the QP
- Return compatible card-based `:metrics` in query metadata
