### ISSUE TITLE
Public card API example

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#4582]
Hi,

I failed to construct a working api url for my public card as below, please help 
`https://abcxyz.com/api/public/card/42fdsfc41-9543-41e5-a8bc-144243e7089f/query/json?parameters=[{\"supplier_id\":\"841668861644\"}]`

**Comment by thucnc** [comment]
Hi,

I made it worked now, as below
`https://abcxyz.com/api/public/card/42fdsfc41-9543-41e5-a8bc-144243e7089f/query/json?parameters=[{"type":"category","target":["variable",["template-tag","supplier_id"]],"value":"841668861644"}]`

Hence, close this issue.

**Comment by edmondo1984** [comment]
This doesn't seem to work for us, which version was the public api added?

**Comment by flamber** [comment]
@edmondo1984 Several years ago. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by edmondo1984** [comment]
Thank you @flamber I guess I was misleaded by the fact that I was expecting to be a POST (it seems like it is a POST in the documentation) but only the GET works.

Can you share with me also the documentation of the parameters arg?

**Comment by flamber** [comment]
@edmondo1984 The documentation is available here: https://github.com/metabase/metabase/blob/master/docs/api-documentation.md
The best way to learn the API, is to just use Metabase while having your browser developer Network-tab open and looking at the request, and what data is being send/received.

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
