### ISSUE TITLE
Support on data limit in query using MongoDB

### ISSUE THREAD

**Issue by ivyctx** [metabase/metabase#4584]
**I am generating reports from Metabase with limit of 2000 rows that I want to increase and I edit with dataset.clj file. Increase the limit from 2000 to 500000 but now getting error:**

**03-22** 17:06:58 WARN metabase.query-processor :: Query failure: Command failed with error 16389: 'aggregation result exceeds maximum document size (16MB)' on server 10.216.204.164:27017. The full response is { "ok" : 0.0, "errmsg" : "aggregation result exceeds maximum document size (16MB)", "code" : 16389, "codeName" : "Location16389" }
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:149)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:142)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:181)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:175)"
"query_processor$fn__26502$dataset_query__26507$fn__26508.invoke(query_processor.clj:212)"
"query_processor$fn__26502$dataset_query__26507.invoke(query_processor.clj:199)"
"api.dataset$fn__37808$fn__37811.invoke(dataset.clj:36)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
"api.dataset$fn__37808.invokeStatic(dataset.clj:30)"
"api.dataset$fn__37808.invoke(dataset.clj:30)"
"middleware$enforce_authentication$fn__39612.invoke(middleware.clj:119)"
"api.routes$fn__39738.invokeStatic(routes.clj:57)"
"api.routes$fn__39738.invoke(routes.clj:57)"
"routes$fn__40024.invokeStatic(routes.clj:44)"
"routes$fn__40024.invoke(routes.clj:44)"
"middleware$log_api_call$fn__39711$fn__39713.invoke(middleware.clj:331)"
"middleware$log_api_call$fn__39711.invoke(middleware.clj:330)"
"middleware$add_security_headers$fn__39661.invoke(middleware.clj:246)"
"middleware$bind_current_user$fn__39616.invoke(middleware.clj:139)"
"middleware$maybe_set_site_url$fn__39665.invoke(middleware.clj:268)"]

Browser and the version: Chrome Version 56.0.2924.87 (64-bit)
Operating system: Linux redhat
Databases: MongoDB
Metabase hosting environment:  Linux

**Comment by salsakran** [comment]
Sounds like you're hitting the limits of the driver. Incidentally, the limit is there to prevent cases like this where end users request too much data and result in server errors. 

We *strongly* suggest not using MB as a way to move large amounts of data around. It's designed with the assumption that it is being used to perform reporting, ad hoc exploration and visualization. Trying to use it to pull down large results sets is possible, but should be considered a "side effect" and not something we really support. If you're pulling out 500k records, you should really consider having that be a scheduled job and export the table via ETL software or some sort of data pipeline.

**Comment by ivyctx** [comment]
Can you suggest maximum number of records I can pull i.e. 20K, 50K 100K, etc. ?

**Comment by salsakran** [comment]
`aggregation result exceeds maximum document size (16MB)` suggests that something in either MongoDB or the MongoDB driver caps the results of an aggregation at 16MB.

I don't know what you're aggregating (and hence how big records are)but, you would want to pick a number of records that fits in that result size.
