### ISSUE TITLE
Date widget difficult to navigate if desired date too far from current date

### ISSUE THREAD

**Issue by tanzoniteblack** [metabase/metabase#4585]
Currently, if you want to use the date picker widget for a date that's a year or more ago, you have to page through every single month. It'd be great if we could add something to that widget so we can navigate by year in addition to month.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Are you talking about the date picker for dashboard filters, or in the GUI query builder? With the latter, you can type the specific date you want. The dashboard "Single Date" widget does have the problem you're describing, though.

**Comment by tanzoniteblack** [comment]
The single date widget, as used on both dashboards and SQL questions (with SQL parameters). The date range widget also suffers from this.

Oh dashboards, since parameters are in the URL, I've just been recommending my users edit the URL manually, which isn't ideal, but works. Not possible on question cards though.

**Comment by tlrobinson** [comment]
I think @kdoh had designs for this but they never got implemented.

**Comment by tanzoniteblack** [comment]
@tlrobinson  / @kdoh if you guys can post the designs for this, I'll try to go ahead and implement it later this week.

**Comment by sailxjx** [comment]
I think an editable date picker should work. https://hacker0x01.github.io/react-datepicker/

**Comment by morrison999** [comment]
It appears this request is kind of stale, but it is still a problem. I give my users date ranges for the queries and if it's more than a couple months, it's a pain to use the date picker. The react-datepicker suggested by sailxjx over a year ago would work fine.

**Comment by glassguitars** [comment]
any plans for fixing this?    Am beginning to wonder about bug-prioritization at Metabase; it would be most useful if you would address these low-hanging fruit before venturing out elsewhere.  please?
