### ISSUE TITLE
Don't auto-complete var names when typing numbers

### ISSUE THREAD

**Issue by brnt** [metabase/metabase#4587]
Browser: Chrome 56.0.2924.87 (64-bit)
Operating System: OSX 10.12.3
Database: PostgreSQL
Metabase Version: 0.22.2
Hosting Env: Heroku
Internal DB: PostgreSQL

When typing an SQL question, if you type a number, something like:

`WHERE foo > 0`

the editor provides autocomplete alternatives for the `0` which (1) doesn't make any sense and (2) breaks your ability to start a new line after the number without typing some other character (`space`, `esc`, or the like). Hitting `enter` while in auto-complete suggestion mode results in the editor inserting the first (or currently-selected) option, which is ... unhelpful when you're simply entering digits. Desired functionality is that entering digits doesn't invoke auto-complete suggestion mode.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mngr** [comment]
Doesn't reproduce
