### ISSUE TITLE
Feature Request: Goal Line Display option for Row Bar Charts

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#4588]
Hi there,

I love the new "Row Chart" visualization type in Metabase v0.23.
We were literally just wondering this afternoon if this was supported. The upgrade to latest was a breeze.

Would really appreciate it if the Row Chart display options could reach feature parity with the standard Bar chart visualization.

In particular, we love the "Goal Line" feature available in columnar bar charts, can't wait to see that as a consistent option across all applicable visualizations (and hopefully persisted when you switch visualization types).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by agoud1993** [comment]
We Would love to have a goal line setting option on a Row Chart. And also Allow us to label the axis. We currently don't have an option for the Row chart like we have an option for setting up a goal line for a Bar chart

**Comment by agoud1993** [comment]
@tlrobinson any improvements on Row chart in the upcoming releases for building multiple series on a Row chart?

**Comment by agoud1993** [comment]
@tlrobinson  any updates to use a goal line on a row chart or any releases in the upcoming versions?
