### ISSUE TITLE
 org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"

### ISSUE THREAD

**Issue by douglaz** [metabase/metabase#45885]
### Describe the bug

Error getting the fields of a table

### To Reproduce

Not sure. But one important thing is that there is another table in another schema with same name and fields and it works.

### Expected behavior

Correctly mapping of the table

### Logs

[log.log](https://github.com/user-attachments/files/16317564/log.log)

### Information about your Metabase installation

```JSON
- Metabase v0.50.6
- AWS Aurora Postgres
```

### Severity

Blocks the usage of a table

**Comment by qnkhuat** [comment]
Could you upgrade to the latest version and try again? 

We have a fix related to this index in https://github.com/metabase/metabase/issues/44659#issuecomment-2192932023

**Comment by qnkhuat** [comment]
probably a dup of https://github.com/metabase/metabase/issues/44459

**Comment by douglaz** [comment]
Yes, it works, thanks!
