### ISSUE TITLE
"Is" Filter on Notebook editor does not show list of values for fields with `has_field_values=:list`

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#45904]
### Describe the bug

If a field is manually set "Filtering on this field" to "A list of values", filtering on this field in the Notebook Editor still shows a search box.

### To Reproduce

1. Go to Admin => Table Metadata => Sample Dataset => Reviews => Body
2. Change "Filtering on this field" to "A list of values"
3. New => Question => Reviews
4. Try filter with the "Is" operator on "Body" column, the UI shows a search box

### Expected behavior

The UI should show a list of values, and when the user types in, the UI makes API calls to search.

### Information about your Metabase installation

```JSON
master
```

### Severity

P2?

### Additional context

Worked on 49.9, I didn't check later versions.

**Comment by qnkhuat** [comment]
Giving this a p1 because it's a regression

**Comment by qnkhuat** [comment]
On 49.9 when I open the filter on "Body" column, the default filter operator is "Is" and it shows a list of values.

But on master(8d22b08feeac5127b08851a02c544ee326645628), the default filter operator is "Contains", when I switch to "Is", I see FE make an API call to get a list of values but still not display the values list.
![Screenshot 2024-07-22 at 15 11 58](https://github.com/user-attachments/assets/ef8a98d8-6712-4a17-9406-5e7ac1794f07)

**Comment by NevRA** [comment]
Removed P1 based on comment here https://metaboat.slack.com/archives/C07BWMG9C8M/p1721650241505399?thread_ts=1721635626.507529&cid=C07BWMG9C8M
