### ISSUE TITLE
Spacing around embedded dashboard cards could be tightened up

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4590]
This is messing around with embedding on a local instance of our marketing site, so I'm not sure if that's contributing to this extra spacing or not.

<img width="952" alt="whitespace" src="https://cloud.githubusercontent.com/assets/2223916/24222877/ead8198e-0f10-11e7-9fe9-9d6eecabe78c.png">

**Comment by tlrobinson** [comment]
"holy white space" is due to the fixed aspect ratio of dashboards, and we can't easily size the iframe to fit.

We should implement some method of resizing the iframe to fit, if the user is ok with including a little snippet of Javascript.

**Comment by tlrobinson** [comment]
Alternatively/additionally we could compute the required height based on the default width and the content of the dashboard, and use that in the generated embed code (but if you change number of rows of content in the dashboard existing embeds won't be updated to match)

**Comment by mazameli** [comment]
Nah, I'm dumb — I think this is mostly resolved just by changing the iframe's height.
