### ISSUE TITLE
Model metadata changes are not reflected in the notebook preview

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#45928]
### Describe the bug

Model metadata changes are not reflected in the notebook preview for any of the stages, including the initial change without any query modifications.

### To Reproduce

1. Create a new GUI model
2. Edit metadata and rename any column to "Foo"
3. Save the model (but this is possible to reproduce without saving  as well)
4. Edit query definition
5. Do not actually change the query (it will wipe out the metadata, which is #45924), but instead just click on the preview
6. Notice that the column name in the preview is not "Foo"

<img width="2054" alt="Screenshot 2024-07-22 at 16 01 30" src="https://github.com/user-attachments/assets/c97da256-a312-4961-9dd0-e7fba8d2b05e">

### Expected behavior

Query previews should ideally reflect the actual query (including metadata changes)

### Information about your Metabase installation

```JSON
local dev, `master`, fcf8c51, H2, Sample Database
```

### Severity

P3

**Comment by ranquild** [comment]
This is no way how we can map metadata from query results to arbitrary query stages. By design - for now.
