### ISSUE TITLE
Share/Embed widget should have better disabled states

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4592]
When public links and embedding are disabled we still show the widget to admins, and it's not obvious they need to go to settings to enable them:

![image](https://cloud.githubusercontent.com/assets/18193/24223585/22e3e710-0f14-11e7-87c4-240ee475a0e7.png)

**Comment by mazameli** [comment]
Good catch. Definitely think we talked about doing a state that's similar to the disabled Pulses page, but evidently we never did. 😮

**Comment by albertoperdomo** [comment]
This is going to be addressed soon as part of a small redesign. Closing.
