### ISSUE TITLE
Model breaks with "column source.ID does not exist"

### ISSUE THREAD

**Issue by Somtom** [metabase/metabase#45938]
### Describe the bug

Older models in 50.x (at least 50.6 models in 50.8; probably earlier ones really) can result in this error.

It seems to be a change somewhere in how columns and refs are handled with models, causing us to generate a SQL that `SELECT`s a column that the inner query doesn't provide.

More context in [this slack thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1721654026800009).

### To Reproduce

See the [broken original model](https://metabase-public.metabaseapp.com/model/1382-euro-2024-player-stats) or the (nearly) working [duplicate](https://metabase-public.metabaseapp.com/model/1519-euro-2024-player-stats-duplicate).

### Expected behavior

The original model should still be working fine.

### Information about your Metabase installation

```JSON
* Version v1.50.8 (after upgrading from v1.50.6)
```

**Comment by iethree** [comment]
🚀 This should also be released by [v0.51](https://github.com/metabase/metabase/milestone/231)
