### ISSUE TITLE
Download full results for Bigquery tables is giving duplicated data in file

### ISSUE THREAD

**Issue by shubz-zoop** [metabase/metabase#45953]
### Describe the bug

We majorly use bigquery and it was working fine until 0.50.13 version
After upgrading to 0.50.13, when we are writing questions with filter conditions and downloading data > 1 lakh records, then in result csv file some rows are getting repeated and some are missing.

### To Reproduce

1. Go to 'any large bigquery table and apply filter conditions'
2. Click on 'Download full results'
3. summerise and see count in metabase
4. see records count in file
5. records in file are more and repeating

### Expected behavior

after downloading, count of records in file should match actual records in bigquery table

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.177+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "postgres",
      "bigquery-cloud-sdk",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.19"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-15",
      "tag": "v0.50.13",
      "hash": "2086968"
    },
    "settings": {
      "report-timezone": "Asia/Kolkata"
    }
  }
}
```

### Severity

blocking my usage of Metabase entirely

**Comment by perivamsi** [comment]
@shubz-zoop which version of Metabase were you using before where this worked?

**Comment by shubz-zoop** [comment]
@perivamsi  i have not taken a note of metabase pervious version but here is docker image metabase/metabase@sha256:28e8a33cfa70e8126d96727b201e6f1888938376e376063a066225469171eb17

**Comment by kasinathreddy** [comment]
Metabase version : 0.50.14
Query used : `SELECT id from UNNEST(GENERATE_ARRAY(1,516667)) id;`
For above query I have exported results as a csv ended up with 7lakh records where id is available from 1 to 350000 and it is exactly duplicated twice
You can test this query without any dependency of the table or filters

**Comment by perivamsi** [comment]
Thanks @kasinathreddy 

This also repros the issue very clearly

`SELECT id from UNNEST(GENERATE_ARRAY(1,350001)) id;`

But this works fine

`SELECT id from UNNEST(GENERATE_ARRAY(1,350001)) id;`

**Comment by kasinathreddy** [comment]
@adam-james-v 
Kindly let us know when a patch fix can be expected for the above

**Comment by perivamsi** [comment]
@kasinathreddy we are working on it, don't have an ETA yet unfortunately

**Comment by kasinathreddy** [comment]
@perivamsi 
It is currently blocking lot of our work, we have decided to roll the version back to 0.49 and while setting it up we are getting issue as **Unknown column report_card.dataset in field list**
So currently we are fully blocked because there is no patch fix and reverting back isn't helping either

**Comment by perivamsi** [comment]
Can you send me the full logs for rollback?

**Comment by shubz-zoop** [comment]
rollback will create problem with database. it will ask for database downgrade before metabase downgrade..

our work is also affected allot because of this issue.. we need it before month end

**Comment by shubz-zoop** [comment]
@perivamsi  is it possible to downgrade to previous version 0.47.5 from current updated version 0.50.13 without previous postgres database backup?

**Comment by perivamsi** [comment]
Can you downgrade to [49.21](https://github.com/metabase/metabase/releases/tag/v0.49.21)? You don't need to restore postgres db backup for that. Just follow the [instructions here](https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase#rolling-back-an-upgrade). Please don't downgrade to 47 though, these instructions wont work for downgrading multiple versions.

**Comment by kasinathreddy** [comment]
I downgraded it to 0.49.21 and it fixed the issue for me
