### ISSUE TITLE
Password Reset Failed: Attempting to call unbound fn: #'metabase.db/select-one-id

### ISSUE THREAD

**Issue by akashdmukherjee** [metabase/metabase#4597]

**Comment by kuttor** [comment]
Also getting this error

**Comment by camsaul** [comment]
@akashdmukherjee @kuttor what version of Metabase are you using?

**Comment by camsaul** [comment]
This was caused by not rebuilding the reset password JAR after the refactoring in #4252. I've done that locally so when we ship 0.23.1 it will have an updated JAR and things will work as expected.
