### ISSUE TITLE
Java / Scala - Graph Embedding & Signing

### ISSUE THREAD

**Issue by cwbeck** [metabase/metabase#4600]
Hi,

Metabase Version: 0.23.0 - > Mac 10.12.3 -> Chrome 56.0.x

The examples are given for Ruby, NodeJS, Python etc, but nothing is given for Java / Scala.

I've attempted to use https://github.com/jwtk/jjwt

```
import io.jsonwebtoken.{Jwts, SignatureAlgorithm}
...
val payload = NativeDocument(
  "resource" -> NativeDocument(
    "question" -> NativeLong(1)
  ),
  "params" -> NativeDocument()
)
println(payload.toJson) // -> {"resource":{"question":1},"params":{}}
val token = Jwts.builder().setPayload(payload.toJson).signWith(SignatureAlgorithm.HS256, METABASE_SECRET_KEY).compact()
val url = METABASE_SITE_URL + "/embed/question/" + token + "#bordered=true&titled=true"
```

Result...

![screen shot 2017-03-23 at 12 50 01](https://cloud.githubusercontent.com/assets/425262/24248436/576de8c4-0fc7-11e7-9895-417acbb80350.png)

I find it interesting that the graph works as usual, but the preview is actually broken in Metabase.

![screen shot 2017-03-23 at 12 51 16](https://cloud.githubusercontent.com/assets/425262/24248466/7ce37420-0fc7-11e7-9093-8f72e7c1c4b4.png)

This is great feature and looking forward to get this into our app!

Chris

**Comment by cwbeck** [comment]
Resolved, using wrong lib. https://jwt.io/

**Comment by fbeaufil** [comment]
Dear cwbeck,
Could you share your code and the library id you used ?
Regards,
FBS

**Comment by cwbeck** [comment]
@fbeaufil 

```
libraryDependencies ++= Seq(
  "com.pauldijou" %% "jwt-core" % "0.12.0"
)
```

```
import pdi.jwt.{Jwt, JwtAlgorithm}

val payload = NativeDocument(
  "resource" -> NativeDocument(
    "question" -> NativeLong(question.toInt)
  ),
  "params" -> NativeDocument()
)
val token = Jwt.encode(payload.toJson, METABASE_SECRET_KEY, JwtAlgorithm.HS256)
val url = METABASE_SITE_URL + "/embed/question/" + token + "#bordered=true&titled=true"
```

Note: NativeDocument / NativeLong etc are part of our own library, but just describe the JSON as per Metabase API docs and allow easy translation to a string. I'm sure you have your own library for this.

**Comment by salsakran** [comment]
@cwbeck we'd love a PR for the java and/or scala embedding, if you would be willing =)
