### ISSUE TITLE
Database encryption h2

### ISSUE THREAD

**Issue by Nyno-Kun** [metabase/metabase#4602]
Hi!
I just upgraded to Metabase v0.23.0 and started it.$
In the first few lines i found this: 
`03-23 15:36:46 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance.`
So, im currently using h2. How do i turn the encryption on?
Or do i have to migrate to, for example, mysql?

Debug Infos:
Running on a Debian Jessie 64Bit 
root@...# java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed 

Regards, Nyno

**Comment by camsaul** [comment]
@Nyno-Kun, read [this documentation](http://www.metabase.com/docs/v0.23.0/operations-guide/start.html#encrypting-your-database-connection-details-at-rest) for details on how to enable DB details encryption.
