### ISSUE TITLE
What driver is "sql server"?

### ISSUE THREAD

**Issue by glensc** [metabase/metabase#46033]
https://www.metabase.com/docs/latest/databases/connecting#connecting-to-supported-databases

There's some "SQL Server", but if I open the details, it doesn't describe what it is, is that microsoft mssql? please clarify in documentation!

- https://www.metabase.com/docs/latest/databases/connections/sql-server
- https://github.com/metabase/metabase/blob/65bb3bb3a9fc978afcf3f3e67cb20a3596a7fc2c/docs/databases/connections/sql-server.md

**Comment by paoliniluis** [comment]
Microsoft sql server

**Comment by glensc** [comment]
issue idea was to indicate documentation needs updating
