### ISSUE TITLE
Slack integration documentation unclear about Metabot channel limitations

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4604]
Neither the users guide nor the admin guide sections on Slack/Metabot explain from which channels Metabot commands may be invoked. In trying it out on our own instance of Slack, it seems like you can only use Metabot in #general, but I have no idea why, or if that's even the case.

**Comment by VikramTiwari** [comment]
@mazameli I think you have to invite the bot to different channels in order to talk to him, but this could have certainly changed since.

**Comment by tlrobinson** [comment]
@VikramTiwari That appears to be correct.
