### ISSUE TITLE
[Epic] Use the metric's data source when creating a new query based on a metric

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#46055]
Product doc https://www.notion.so/metabase/Querying-and-combining-metrics-defined-on-the-same-data-source-1229f547df8140ce9c6f96cd707d28a5
Depends on https://github.com/metabase/metabase/issues/45824

We currently allow only single-stage metrics. When creating a query based on a metric, we should use the metric's data source for the new query data source and append an aggregation clause based on the metric. E.g.

```
// metric with id 2
{
  "source-table": "card__1",
  "aggregation": [["count"]],
}

// new query should be like this
{
  "source-table": "card__1",
  "aggregation": [["metric", 2]]
}
```

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/46687
- [ ] https://github.com/metabase/metabase/issues/46781
- [ ] https://github.com/metabase/metabase/issues/46782
```

**Comment by metamben** [comment]
@ranquild, is there more to this epic (e.g., the recent items issue) or can it be closed?
