### ISSUE TITLE
Edit Pulse > Heads up banner overlays remove button

### ISSUE THREAD

**Issue by mattes** [metabase/metabase#4605]
When editing a pulse it sometimes shows a "Heads up" message. This message is preventing me from being able to click on the remove (cross) button in the top right corner.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Version 57.0.2987.110 (64-bit)

- Metabase version: (e.x. 0.19.3)
v0.22.2

<img width="434" alt="screen shot 2017-03-23 at 9 44 23 am" src="https://cloud.githubusercontent.com/assets/1240531/24259261/9fc1842e-0fad-11e7-83ac-39903a3f8bf1.png">

**Comment by mazameli** [comment]
This was fixed in 0.23 by #4561. :)

**Comment by mattes** [comment]
ah great. just saw the update notification in the admin panel. thanks!
