### ISSUE TITLE
Intermittent (but frequent) "There was a problem displaying this chart."

### ISSUE THREAD

**Issue by hss-iullah** [metabase/metabase#46071]
**Describe the bug**
I am intermittently getting the message "There was a problem displaying this chart " across charts randomly. Its happens randomly on different charts. If I refresh, they might work, they might not. It might happen to a different chart. Who knows, it's completely random!

**Logs**
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/1486/dashcard/4762/card/5228/query 202 [ASYNC: completed] 4.2 s (25 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (120 total active threads) Queries in flight: 5 (0 queued); redshift DB 3 connections: 3/8 (0 threads blocked) {:metabase-user-id 1}
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 WARN metabase.server.middleware.log OST /api/dashboard/1486/dashcard/4760/card/5226/query 404 145.8 µs (0 DB calls) {:metabase-user-id 1} 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/1486/dashcard/4761/card/5227/query 202 [ASYNC: completed] 2.9 s (25 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (6 idle, 0 queued) (120 total active threads) Queries in flight: 3 (0 queued); redshift DB 3 connections: 5/8 (0 threads blocked) {:metabase-user-id 1}
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/1486/dashcard/4764/card/5230/query 202 [ASYNC: completed] 4.2 s (24 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (120 total active threads) Queries in flight: 4 (0 queued); redshift DB 3 connections: 1/8 (0 threads blocked) {:metabase-user-id 1}
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 WARN metabase.server.middleware.log OST /api/dashboard/pivot/1486/dashcard/4274/card/4966/query 404 123.1 µs (0 DB calls) {:metabase-user-id 1} 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/1486/dashcard/4763/card/5229/query 202 [ASYNC: completed] 4.2 s (25 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (120 total active threads) Queries in flight: 2 (0 queued); redshift DB 3 connections: 0/8 (0 threads blocked) {:metabase-user-id 1}
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 WARN metabase.server.middleware.log OST /api/dashboard/1486/dashcard/4768/card/5225/query 404 118.9 µs (0 DB calls) {:metabase-user-id 1} 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

**Severity**
HIGH

**Metabase Diagnostic Info**

{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.219-208.866.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-15",
      "tag": "v0.50.13",
      "hash": "2086968"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by paoliniluis** [comment]
seems like it's not the backend, can you check if there's something on the browser console when this happens?

**Comment by hss-iullah** [comment]
It's weird cos it's intermittent. If I refresh the page again, the chart might work and then might not on the next reload or when applying a filter. It's totally sporadic.

But this is what appears in the logs for every chart which fails to load:
![image](https://github.com/user-attachments/assets/52b08446-759b-4562-8f81-2d5b8a65f239)

For each chart that fails to load I get this in the browser:
![image](https://github.com/user-attachments/assets/83bafa20-9067-4842-b9bb-981f4f606f5a)

In the browser I get loads of errors in general for metabase
![image](https://github.com/user-attachments/assets/ed673070-0d21-412d-8e22-9470fd658903)

**Comment by hss-iullah** [comment]
It's weird cos it's intermittent. If I refresh the page again, the chart might work and then might not on the next reload or when applying a filter. It's totally sporadic.

But this is what appears in the logs for every chart which fails to load:
![image](https://github.com/user-attachments/assets/52b08446-759b-4562-8f81-2d5b8a65f239)

For each chart that fails to load I get this in the browser:
![image](https://github.com/user-attachments/assets/12711f25-5526-4f50-ab8c-768b3d9803b3)


In the browser I get loads of errors in general for metabase
![image](https://github.com/user-attachments/assets/ed673070-0d21-412d-8e22-9470fd658903)

**Comment by paoliniluis** [comment]
do you know if you have dns problems in your infrastructure?

**Comment by hss-iullah** [comment]
No, all is good and it's just one specific dashboard (the questions themselves load fine, it's just in the dashboard mode) which is using Redshift **plus some Redshift external schema tables** which pull from a postgres database.
The SQL fires totally fine, no performance issues or delays, it's just this one specific dashboard which uses a combination of Redshift tables and Redshift external schema tables.

**Comment by paoliniluis** [comment]
@hss-iullah do you have a CDN in place that might be caching stuff? Have you cleared the cache in your browser?

**Comment by alxnddr** [comment]
@paoliniluis I think it may not be related to CDN because the request hits Metabase BE and the BE middleware logs 404

**Comment by alxnddr** [comment]
@hss-iullah do you use in-app caching?

**Comment by paoliniluis** [comment]
@alxnddr my theory here was that they were using a cached FE bundle (many people end up with old FE assets after upgrading due to CDN stuff) and this ends in very weird behaviors like this one

**Comment by hss-iullah** [comment]
Hi. No cdn. The issue persists and only affects redshift federated tables.  Have you tested metabase with redshift federated tables?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by paoliniluis** [comment]
Just reproduced this with a customer, we'll address it ASAP

**Comment by snoe** [comment]
Related issues that are showing the `OST` logs.
https://github.com/metabase/metabase/issues/36775 
https://github.com/metabase/metabase/issues/36774

**Comment by snoe** [comment]
Reproduction steps:
- On a metabase instance running outside AWS
- Make a native query against a redshift test data orders table
`select * from "2024_08_07_c997e9dd_9140_4b37_b9d4_ffff99b57876_schema".test_data_orders`
- Open dev tools
- Run it, after the query finishes you should see a request for `GET /api/database/:id` in network requests, it may or may not fail. (usually does for me)
- You can refresh the page and re-run it to test or you can "copy as curl" the `POST /api/dataset` and `GET /api/database/:id` requests from the network tab and combine them using `--next`

```
curl 'https://stats.metabase.com/api/dataset' \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  -H 'cookie: metabase.TIMEOUT=alive; metabase.SESSION=$SESSION' \
  --data-raw '{"type":"native","database":168,"native":{"query":"select * from \"2024_08_07_c997e9dd_9140_4b37_b9d4_ffff99b57876_schema\".test_data_orders","template-tags":{}},"parameters":[]}' \
--next 'https://stats.metabase.com/api/database/168' \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  -H 'cookie: metabase.SESSION=$SESSION'
```

**Comment by bshepherdson** [comment]
I can reproduce this on localhost, a bit less consistently than I would like.

I captured the packets with Wireshark and the `GET` definitely went over the wire. The server only caught `ET /api/database/487`, though.

**Comment by bshepherdson** [comment]
The method is `ET` by the time it reaches the Jetty server: both the Jetty `Request` and Jakarta `HttpServletRequest` have method `"ET"`.

So there's something happening deeper in the network or server infra, before we reach the request handlers in Clojure land.

**Comment by paoliniluis** [comment]
@bshepherdson redshift as well?

**Comment by bshepherdson** [comment]
Yeah, I'm using the Redshift query that Case mentioned above. It reproduces more often if I keep refreshing the page, rather than using `curl`.

**Comment by bshepherdson** [comment]
With `DEBUG` logging turned on in Jetty, the repro gets a bit less frequent but it does still happen. The logs show that when it repros most of the Jetty internals (`HttpInput`, `AsyncContentProcessor` and more) are the same instances, recycled. That is, the async streaming `/query` request/response used the same Jetty machinery as the new `/database` request that loses a byte.

That's telling, but it's still not clear how that byte actually gets skipped or consumed wrongly. Since this is Redshift-specific I suspect it's related to the Redshift JDBC driver's `RingBufferThread`, which is still receiving data rows from the server.

The Redshift servers don't respect `.setMaxRows`, and are either slow to react to a cancellation message, or don't respect those either. Therefore when max rows is reached, the Redshift JDBC driver closes the result set, and spawns a separate thread (`RingBufferThread`) to drain the data rows which the server is still sending to it. That leads to Metabase thinking that (1) the query is finished; (2) the Redshift connection can be reused; and (3) the Jetty HTTP connection parts can be `.recycle()`ed and `.reopen()`ed.

In fact none of those three conditions are quite true, but I wasn't able to find where it actually goes wrong. The connection can be reused, but it [starts by waiting for the old one to finish](https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/src/main/java/com/amazon/redshift/core/v3/QueryExecutorImpl.java#L331) which might take a long time. Since the Redshift socket is separate from the Metabase HTTP sockets, I'm not sure what happens to that lost byte. Maybe it tries to write something via the `ResultSet` when the query really ends, and that advances the `ByteBuffer.pos()` by 1?

**Comment by paoliniluis** [comment]
@nathanjones4323 we don't know, we have a strong belief this is redshift, so if I were you I would be downgrading the redshift JDBC driver rather than the Metabase version

**Comment by nathanjones4323** [comment]
Thanks for the quick response!

My team is experiencing the same issue as the OP, but we are using Postgres.

**Comment by paoliniluis** [comment]
@nathanjones4323 is PostgreSQL the app db or the DW?

**Comment by evan-dixon** [comment]
@paoliniluis I am on the same team as @nathanjones4323 . PostgreSQL is our data warehouse, we do not have redshift/snowflake/etc

**Comment by nathanjones4323** [comment]
@paoliniluis We use separate instances but both RDS for our warehouse and Metabase backend.

**Comment by sifxtreme** [comment]
Running into an issue that manifests itself similarly. With the "There was a problem displaying this chart.". Digging deeper, we are getting intermittent 500s from the Metabase backend. The error message is "ERROR: cannot execute UPDATE in a read-only transaction".

Not sure what changed and where that would be coming from. Any ideas?

**Comment by paoliniluis** [comment]
@sifxtreme this is not the issue you're seeing, please post version and reproduction steps or conditions in another issue so we can investigate and fix

**Comment by paoliniluis** [comment]
@evan-dixon can you confirm that you're seing the HTTP verbs getting chopped on the logs? first time we hear this happens on pure postgres so that will discard that this is an issue with Redshift

**Comment by evan-dixon** [comment]
@paoliniluis I think we have the same outward symptoms with different inward issues. The POST requests don't seem to be getting chopped, but instead are experiencing internal server errors. This particular thread still may just be related to redshift, sorry for any mis-direction.

**Comment by hudovisk** [comment]
Hey @paoliniluis we are using two postgres instances, one for both Metabase backend and one for the warehouse. I was running locally using a localhost postgres for metabase backend and I observed the same behavior on `OST` requests:
```
metabase-1  | {"@timestamp":"2024-09-17T23:43:19.721Z","ecs.version":"1.2.0","log.level":"WARN","message":"OST /api/dashboard/17/dashcard/200/card/288/query 404 11.8 ms (0 chamadas ao banco de dados) {:metabase-user-id 1} \n#metabase.util.i18n.UserLocalizedString{:format-string \"API endpoint does not exist.\", :args [], :pluralization-opts {}}\n","process.thread.name":"qtp1460527055-220","log.logger":"metabase.server.middleware.log"}
```

This is an intermittent issue that displays the "There was a problem displaying this chart." in the dashboard

**Comment by nsaje** [comment]
Facing this locally as well with Redshift. The browser is not to blame (confirmed with tcpdump, see screenshots). It appears like some middleware does a substring on the URI and cuts off the `P`. The resulting URI starting with `OST ...` obviously doesn't match any known path so a 404 is returned.

<details><summary>Diagnostic Info</summary>
<p>

{
  "url": "http://localhost:3000/dashboard/35-leadership-dashboard?tab=13-customers-by-tier",
  "entityName": "dashboard",
  "bugReportDetails": {
    "metabase-info": {
      "databases": [
        "redshift"
      ],
      "run-mode": "prod",
      "plan-alias": "",
      "version": {
        "date": "2024-10-02",
        "tag": "v0.50.28",
        "hash": "3179ef2"
      },
      "settings": {
        "report-timezone": "UTC"
      },
      "hosting-env": "unknown",
      "application-database": "postgres",
      "application-database-details": {
        "database": {
          "name": "PostgreSQL",
          "version": "16.2 (Debian 16.2-1.pgdg120+2)"
        },
        "jdbc-driver": {
          "name": "PostgreSQL JDBC Driver",
          "version": "42.7.3"
        }
      }
    },
    "system-info": {
      "file.encoding": "UTF-8",
      "java.runtime.name": "OpenJDK Runtime Environment",
      "java.runtime.version": "11.0.24+8",
      "java.vendor": "Eclipse Adoptium",
      "java.vendor.url": "https://adoptium.net/",
      "java.version": "11.0.24",
      "java.vm.name": "OpenJDK 64-Bit Server VM",
      "java.vm.version": "11.0.24+8",
      "os.name": "Linux",
      "os.version": "6.10.12-orbstack-00282-gd1783374c25e",
      "user.language": "en",
      "user.timezone": "GMT"
    }
  }
}

</p>
</details> 

### browser network tab

![Image](https://github.com/user-attachments/assets/f21ba580-cfc7-4836-bdb7-0112ca7a760b)

### server logs error
![Image](https://github.com/user-attachments/assets/12fd7be2-db6d-42a6-890d-72beb5c1b39b)

### wireshark request
![Image](https://github.com/user-attachments/assets/6a8f7901-a751-48ec-b4b4-e9377b02ed5d)

### wireshark response
![Image](https://github.com/user-attachments/assets/96681841-3a5b-44b0-8f44-5e78d91054ea)

**Comment by paoliniluis** [comment]
@nsaje nice debugging skills. Just want to mention that the issue seems to be the HTTP method here which the Jetty web server does not seem to understand (because it simply doesn't exist). So everything is fine on the browser end and at some point in the middle, something strips the P from the HTTP method and the backend receives an unknown method and replies with a 404

**Comment by nsaje** [comment]
> backend receives an unknown method

The backend receives the method correctly as evidenced by tcpdump. My theory is that there is some middleware _within_ the Metabase backend that malforms the URI before it's matched against known endpoints.

**Comment by perivamsi** [comment]
Got excited about the docker repro for a second but looks like this is happening directly as well.

**Comment by bshepherdson** [comment]
I agree with [nsaje above](https://github.com/metabase/metabase/issues/46071#issuecomment-2416365819) that the issue lies in the depths of the Metabase server somewhere.

I think my earlier [comment](https://github.com/metabase/metabase/issues/46071#issuecomment-2338470348) is still on the right track, except for the Redshift-specific part. Jetty has a `recycle()` flow that wipes and reuses various internal objects. I think somewhere a `Socket` (or `HttpConnection` etc.) is getting recycled and used for the "chopped" request, even though some async process still has references to it.

I suspect the lost byte is getting read[1] by that async process and the new request never sees it. Perhaps with a heap snapshot tool like VisualVM we could capture that moment of recycling eg. Jetty's `HttpInput`, and find who still has references to that or the `ByteBuffer`/`InputStream`/`Socket` it previously owned.


[1] I can easily imagine a process that's either pre-fetching a byte optimistically, or `.get()`ing the byte, realizing it's the wrong thing, and rewinding the stream (`PushBackReader`, adjusting `ByteBuffer.pos()`, etc.) but either too "locally" or too late for the other consumer to get the byte back.

**Comment by nsaje** [comment]
@alexander-yakushev I might need some help running this (not a Clojure dev) - I get `Unable to resolve symbol: health-request in this context` when I paste the above snippet into REPL.

**Comment by alexander-yakushev** [comment]
@nsaje Thank you very much for repeating my experiment! With you confirming once again that it reproduces, I managed to reproduce it myself and [hopefully] fix this issue.
