### ISSUE TITLE
check error log when 'There was a problem displaying this chart.'

### ISSUE THREAD

**Issue by prinspark** [metabase/metabase#4608]
Is there any clue to do that?
I wanna know why it fails,thanks

**Comment by salsakran** [comment]
You can get at the server logs via the dropdown menu in the upper right corner of the application.

<img width="209" alt="screen shot 2017-03-30 at 6 30 06 pm" src="https://cloud.githubusercontent.com/assets/107439/24532666/014925d4-1577-11e7-9ad7-fcdbce0876f5.png">

You should also look at the Javascript console in your browser for any other errors.

Closing this as it's not an actionable issue. Please chime in here or better yet open a separate issue if you discover a specific bug or enhancement idea.

**Comment by prinspark** [comment]
thanks!
it's useful.

**Comment by psrawke** [comment]
Hey,

I am also getting a message display on the dashboard, while the standalone question looks to be working completely fine.

Surprisingly when I refresh the dashboard page it displays the chart properly.

Any help is much appreciated.

Thanks,
Prasanna
