### ISSUE TITLE
Non-administrators attempting to create an alert encounter an error

### ISSUE THREAD

**Issue by matthelm** [metabase/metabase#46100]
### Describe the bug

Alerts are created successfully by administrators. However, non-administrators attempting to create an alert encounter a message that says, "To send alerts, an admin needs to set up email integration."

### To Reproduce

1. Log in as a non-administrator
2. Go to an existing question
3. Click on the bell icon to "Get alerts"
4. See a message saying that the administrator must setup the email integration.

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/e39fa701-a43a-452f-b393-6031a385964a">

### Expected behavior

Assuming alerts are configured to allow administrators to create them, I expect non-administrators to have the same ability. The following link specifies that all users can create alerts and dashboard subscriptions.

https://www.metabase.com/docs/latest/permissions/notifications

### Information about your Metabase installation

- Your browser and the version: Chrome 126.0
- Your operating system: macOS 14.5
- Your database: Snowflake
- Metabase version: v0.50.13
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

### Severity

Blocking some users

**Comment by qnkhuat** [comment]
I can't reproduce it with an email setup.

A couple of questions for you:
1. Do you use slack or email, or both?
2. Is your non-admin user sandboxed or impersonated?

**Comment by matthelm** [comment]
@qnkhuat thanks for taking a look! 
1. We've only configured Slack.
2. I’m unclear on your question. We experienced the issue with two separate logins. First, a non-admin colleague brought it to my attention. I then created a test user, logged in with that user, and confirmed the issue myself.

**Comment by qnkhuat** [comment]
Thanks, I can reproduce with Slack now.

@metabase/core-frontend-admin-webapp I believe this is a FE bug, the API `GET /api/pulse/input_form` does return slack as configured so we should show it.

**Comment by iethree** [comment]
So this is the intended behavior, non-admins can only send email alerts. This message, however, is confusing, we will improve it. 👍 

see https://github.com/metabase/metabase/issues/17526

**Comment by matthelm** [comment]
Thank you for the clarification and for improving the message.
