### ISSUE TITLE
You should be able to use auto-refresh, night mode, and fullscreen mode withs public dashboards

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4612]
One of our main drivers in creating publish dashboards was to provide a secure way to display them on large format displays, etc. 

We should include the standard controls (nighttime mode, etc) in publish dashboards. 

Should they be in iframes? Is there a way to control this aside from url params?

**Comment by mazameli** [comment]
Do we think that [caching](https://github.com/metabase/metabase/issues/1666) is a pre-req for this?

**Comment by salsakran** [comment]
If the controls are in an i-frame, perhaps.
For the standard "put a dashboard on a tv and refresh", no.

**Comment by mazameli** [comment]
Changed the title per this comment above:
> We should include the standard controls (nighttime mode, etc) in publish dashboards.

**Comment by mazameli** [comment]
So post-conversation with @salsakran:
- Public-linked dashboards should have the identical full-screen and auto-refresh buttons as normal dashboards. And in full-screen mode, there should be the same three buttons as normal dashboards (auto-refresh, exit fullscreen, and toggle night mode)
- _iframed_ dashboards should _not_ have those options

**Comment by kmcgaire** [comment]
How am I able to get these changes? I was following http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html#deploying-new-versions-of-metabase for updating my metabase version but I don't see this feature

**Comment by tlrobinson** [comment]
@kmcgaire This will be available in the next release, 0.24, which should be available in the next week or two. You are also welcome to build from `master` (basically git clone then run `./bin/build`), but be sure to backup your database first.

Normally you could also run our `metabase-head` Docker container, but it hasn't been building recently, we need to fix that. https://hub.docker.com/r/metabase/metabase-head
