### ISSUE TITLE
Broken navigation when using Click Behavior and Tabs

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#46163]
### Describe the bug

You won't be able to go back to the original dashboard if you do this set up. A video and steps below:
https://www.loom.com/share/d002458364d8449d974444958766ea9d?sid=bd706dc1-f1ed-45b1-b20d-6dd9341198ef

### To Reproduce

1. Set up two dashboards. Dashboard 2 should have 2 tabs.
2. Put a random table/card in Dashboard 1, and set click behavior of table/card to the Dashboard 2, Tab 2. 
3. Save
4. Click on the field of the table you set up Click Behavior on. It should correctly take you to Dashboard 2, Tab 2.
5. Now try to go back, using browser back button. See that you can't do it.

### Expected behavior

Should take to the original Dashboard 1

### Information about your Metabase installation

```JSON
- 50.14
```

### Severity

P2

**Comment by perivamsi** [comment]
Fixed with https://github.com/metabase/metabase/pull/44639

Will be released in v51

more context in [Slack](https://metaboat.slack.com/archives/C052ZBWRG3W/p1721942106499729)

**Comment by cdeweyx** [comment]
@perivamsi Can we close this issue?

**Comment by perivamsi** [comment]
yes please
