### ISSUE TITLE
Inconsistency of columns on a dashboard card and the exported csv file

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#46175]
### Describe the bug

Removal of columns from a question may cause missing columns or incorrect order of columns in the data downloaded from the card on the dashboard.

### To Reproduce

1. Create a question: 
  * Sample db / People - select the following columns: ID, Address, Email, Name, City, State, Birth Date, Zip
  * Table visualization
2. Save it and add to a dashboard
3. Edit the dashboard, on the cards visualization settings: hide Email and Address. Save the dashboard.
4. Now edit the question, and on the visualization settings: remove Email, Address (they were already hidden on the dashboard).
5. On the dashboard visualization settings: hide Zip, and move the ID column to the last position. Save it.
6. Now edit the question again, and add back the Email column. Save the question.
7. Email will be displayed as the last column on the dashboard:
<img width="851" alt="image" src="https://github.com/user-attachments/assets/4bef7108-639f-4e1e-ac1d-f3f188ebc6a0">
8. (!) Download CSV results from the card, and see the error: the Email column is missing.
<img width="332" alt="image" src="https://github.com/user-attachments/assets/d1b3b594-b204-4efb-8a85-5bf337bc835a">

### Expected behavior

The downloaded files should have the same columns in the same order as they are displayed on the dashboard.

### Information about your Metabase installation

```JSON
1.49.21
```

### Severity

P2 - reported by a customer

### Additional context

Clicking on 'Reset to defaults' on the card visualization settings seems to be a workaround. It resets the columns of the displayed card to the ones of the underlying question and after that rearranging columns or hiding individual ones works for both the dashboard and the downloaded data.

**Comment by kulyk** [comment]
@zbodi74 i can't seem to reproduce this neither on v49 or v50. Could you please double-check if it's still an issue? If so, I'd appreciate if you could record a video repro, maybe I misunderstood some of the steps
