### ISSUE TITLE
Question working but pulse linked to it is broken - no preview and no updates

### ISSUE THREAD

**Issue by kristian-elder** [metabase/metabase#4618]
**Environment**
Metabase v0.23.0 running the official Docker image
MySql database for Metabase internally, and for querying

**Description**
One of our pulses is no longer working. Attempting to edit it, or to create another pulse for the same question results in a stuck spinner in the UI where the questions is being added and the following error:

```
{:message nil,
 :stacktrace
 ["pulse.render$format_cell.invokeStatic(render.clj:159)"
  "pulse.render$format_cell.invoke(render.clj:156)"
  "pulse.render$render_table$fn__18560$iter__18561__18565$fn__18566.invoke(render.clj:241)"
  "api.pulse$fn__33803$fn__33804.invoke(pulse.clj:113)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
  "api.pulse$fn__33803.invokeStatic(pulse.clj:106)"
  "api.pulse$fn__33803.invoke(pulse.clj:106)"
  "middleware$enforce_authentication$fn__34556.invoke(middleware.clj:119)"
  "api.routes$fn__34708.invokeStatic(routes.clj:72)"
  "api.routes$fn__34708.invoke(routes.clj:72)"
  "routes$fn__35755.invokeStatic(routes.clj:44)"
  "routes$fn__35755.invoke(routes.clj:44)"
  "middleware$log_api_call$fn__34655$fn__34657.invoke(middleware.clj:331)"
  "middleware$log_api_call$fn__34655.invoke(middleware.clj:330)"
  "middleware$add_security_headers$fn__34605.invoke(middleware.clj:246)"
  "middleware$bind_current_user$fn__34560.invoke(middleware.clj:139)"
  "middleware$maybe_set_site_url$fn__34609.invoke(middleware.clj:268)"]}
```

The question is written in SQL and returns a handful of entries.

**Comment by tlrobinson** [comment]
@kristian-elder Can you give me some more details about the question that's breaking?

Ideally you could load it in Metabase (`/card/:cardId`) and tell me what the response of the `/api/card/:cardId/query` request is (the `json_query` and `data.cols` properties of the response are the important bits, and maybe one row of `data.rows`)

**Comment by gauravgoyal1** [comment]
Running v0.26.0.RC2
Connected PostgreSQL.
Saw same error in logs.

Pulse is breaking for questions where I have grouped on 2 columns. Worked when I removed group on the second column.

This is what I could diagnose. Hope it helps.

**Comment by flamber** [comment]
Closing in favor of #9648
