### ISSUE TITLE
Dashboard filters with long values go off-screen

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#46189]
### Describe the bug

Dashboard string filters with long enough values go off-screen

### To Reproduce

1. Open a dashboard with at least one question
2. Add a string filter (don't forget to link it to a column so the filter is visible after leaving editing mode)
3. When editing the string filter, set pick "Input box" in the "How should people filter on this column?" section of the filter sidebar
4. Save the dashboard
5. Add a long enough value (could be a few sentences)
6. Notice the filter goes off-screen

### Expected behavior

String filters should have a fixed length (~30 characters), ellipsify text, and display the full value in a tooltip on hover

### Information about your Metabase installation

```JSON
`master`, but it's been like that for at least a few versions
```

### Severity

P2

### Additional context

  
![before](https://github.com/user-attachments/assets/672d65e2-44e7-43ff-9b2c-a0955ba12ab2)

**Comment by nemanjaglumac** [comment]
@kulyk duplicate of https://github.com/metabase/metabase/issues/44435?

**Comment by kulyk** [comment]
> @kulyk duplicate of #44435?

@nemanjaglumac I don't think so, this issue is about dashboard filters and the issue you mentioned is about QB filters
