### ISSUE TITLE
Add hungarian translation

### ISSUE THREAD

**Issue by istvano** [metabase/metabase#46215]
**Is your feature request related to a problem? Please describe.**
Hungarian translation is still missing. 

**Describe the solution you'd like**
I have completed the translation that can be found at 
https://poeditor.com/projects/po_edit?id_language=65&id=200535

**Describe alternatives you've considered**

**How important is this feature to you?**
This is important as it will enable every user from Hungary to use the project.

**Additional context**
The translation is now complete and validated.

**Comment by paoliniluis** [comment]
@zbodi74

**Comment by istvano** [comment]
Hi,
I have managed to update the translations again. it is 100% again

**Comment by istvano** [comment]
Hi @paoliniluis 

I check it again and it is still 100% complete. Do you think it would be possible to include it in the next release ?

**Comment by istvano** [comment]
Hi @paoliniluis 

thanks a lot. this one had the needs triaging flag and other one had no such a thing. I am happy either way. If someone has a quick look. thanks again for looking!
