### ISSUE TITLE
convertTimezone expression not working

### ISSUE THREAD

**Issue by Jianbin719** [metabase/metabase#46216]
### Describe the bug

I followed the instruction below to use timezone conversiono. but it did not work

https://www.metabase.com/docs/latest/questions/query-builder/expressions/converttimezone

convertTimezone("2022-12-28T12:00:00", "Canada/Pacific", "Canada/Eastern")

### To Reproduce

I added the custom column "Test", then enter 
convertTimezone("2022-12-28T12:00:00", "Canada/Pacific", "Canada/Eastern")

But it remiains empty in "Test"

### Information about your Metabase installation

```JSON
0.50.16 version I am using.
```

### Severity

blocking my usage of Metabase entirely

**Comment by qnkhuat** [comment]
What is the DB you're querying against? is it in the supported dbs list? : https://www.metabase.com/docs/latest/questions/query-builder/expressions/converttimezone#limitations

**Comment by Jianbin719** [comment]
I see, MySQL is not support. sorry
