### ISSUE TITLE
Links to table/database are broken in "Most viewed tables" Metabase analytics question

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#46256]
### Describe the bug

For the Metabase analytics question "Most viewed tables", the links for the table/database columns are broken: 

E.g. For table, it is using this link: https://.../question#?db=1&table=1
For database, it is using this link: https://.../browse/1

<img width="772" alt="Screenshot 2024-07-29 at 4 51 34 PM" src="https://github.com/user-attachments/assets/3d622a3f-5dbb-4d48-821b-39e58a4cdf7a">

### To Reproduce

1. Go to Metabase analytics -> Most Viewed Content dashboard
2. Scroll down to Most Viewed Tables card
3. Click on any table / database to open them
4. Bad links

### Expected behavior

Working links to tables and databases

### Information about your Metabase installation

```JSON
master @ Postgres
```

### Severity

Good to fix, but not sure how many people look at it and click-thru

**Comment by ranquild** [comment]
1. Database link should be `/browser/databases/:id` and not `/browse/:id`
2. Table link seems to be correct, but there are some non-existing tables here for which the BE throws 404.
