### ISSUE TITLE
Postgres tests should only run when the postgres engine is enabled

### ISSUE THREAD

**Issue by senior** [metabase/metabase#4626]
Current master breaks when running H2-only tests.

The error is that it can't connect to a Postgres instance (I don't have one configured): "class org.postgresql.util.PSQLException - Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."

The issue appears to be a missing `expect-with-engine` [here](https://github.com/metabase/metabase/blob/master/test/metabase/driver/postgres_test.clj#L208)

**Comment by camsaul** [comment]
good catch
