### ISSUE TITLE
Can't create a funnel when in SQL Mode

### ISSUE THREAD

**Issue by simonflore** [metabase/metabase#4629]
When I'm making questions in SQL Mode, the Funnel seems to hit a bug. 

- Chrome 56.0
- Your operating system: macOS Sierra
- Your databases: MySQL 5.7
- Metabase version: 0.23
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

-Create a question which can be shown in a Funnel
-Convert the question to SQL
-Try to run the SQL
-Metabase asks which fields to use
-When picking the right fields it fails to generate a new funnel

<img width="1586" alt="screen shot 2017-03-28 at 15 14 32" src="https://cloud.githubusercontent.com/assets/121579/24406898/c5a758a6-13c9-11e7-95ab-a04998d6c871.png">

**Comment by mazameli** [comment]
#4682 was filed later, but I believe it subsumes this issue.

**Comment by tlrobinson** [comment]
I thought #4682 was a different issue than it appears to be, and I agree it's a bug. I'll close #4682 since I think it's a duplicate.
