### ISSUE TITLE
Query Builder time filters don't get executed on PostgreSQL data

### ISSUE THREAD

**Issue by sbrodehl** [metabase/metabase#4632]
We use a PostgreSQL database with timestamp fields.
Now if we filter data by using only the date information, everything works fine, but using also time information produces the error below.
```
ERROR: function date_trunc(unknown, unknown) is not unique Hint: Could not choose a best candidate function. You might need to add explicit type casts. Position: 458
```
Using version v0.23.0 on Heroku with a PostgreSQL database version 9.6.1

Trying the same filter on the sample dataset (H2 database) works fine.

**Comment by mazameli** [comment]
Was able to reproduce this, and confirmed it's specifically a problem with PostgreSQL.
