### ISSUE TITLE
Field filters are not getting cached in saved questions

### ISSUE THREAD

**Issue by harshith-bolar-rapido** [metabase/metabase#46332]
### Describe the bug

Drop down field filters are not getting cached in saved questions. When I reload the question and try accessing the drop down menu, it triggers a new query every time. 

### To Reproduce

1. Go to any saved question with a field filter
2. Click on the filter drop down
3. Let the query run and filter populate
4. Reload the page
5. Click on the filter drop down again

### Expected behavior

Once the field filter is populated with values, the second reload should fetch these values from cache and not fetch it from DB again

### Information about your Metabase installation

```JSON
- Browser: `Version 126.0.6478.127`
- Operating system: Mac OS
- Database: Trino with Startburst driver
- Metabase version: 0.50.4
- Hosting: Kubernetes
- Internal database: MySQL
```

### Severity

Blocking as each time a user clicks on field filter drop down, it triggers a new query which is very slow due to full table scan

**Comment by ranquild** [comment]
@harshith-bolar-rapido you can get your values cached if you go to Admin -> Table Metadata -> Select your database, schema, table, field -> And set `Filtering on this field` to `A list of all values`. This will only work if there are less than about a thousand unique values for this field.

**Comment by harshith-bolar-rapido** [comment]
@ranquild I tried this, set the field to `A list of all values`, hit re-scan this field, it triggered a query which finished successfully. Then I reloaded the question and clicked on the drop down filter, and it fired the same query again to fetch filter values.

Is there any way I can validate that it is caching something?

**Comment by Tony-metabase** [comment]
Go to the Application Database and find the `metabase_fieldvalues` table and you should find the filter values there if they are getting cached:

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/d54abcbb-a75f-4716-889f-16643e7145c1">

**Comment by harshith-bolar-rapido** [comment]
Verified that the field values are stored in `metabase_fieldvalues` table. But in the question it still triggers another query to the DB to fetch these values. Added screenshots for reference.

<img width="479" alt="image" src="https://github.com/user-attachments/assets/17e12f5c-35d1-4034-8da2-ee13d1856416">
<img width="338" alt="image" src="https://github.com/user-attachments/assets/ba5277de-2c93-4341-8b1f-c5c790af800f">
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/0a55fa6e-285a-4110-adf9-4e5bcca5e4c5">

**Comment by harshith-bolar-rapido** [comment]
@Tony-metabase 

<img width="901" alt="image" src="https://github.com/user-attachments/assets/8689624d-1c2f-41e1-86e7-eb50c1c8ceec">

**Comment by Tony-metabase** [comment]
It's possible you are hitting this issue then https://github.com/starburstdata/metabase-driver/issues/44 which seems to be driver related

**Comment by harshith-bolar-rapido** [comment]
I see the same behaviour using the default presto driver shipped with Metabase, don't think this is a Starburst driver issue.

Another observation - Caching of field filters works in saved dashboards but not in saved questions.

**Comment by sabyasachinandy** [comment]
@Tony-metabase Can you please help us as with what to check in the driver?

**Comment by ArthurNGN** [comment]
> Another observation - Caching of field filters works in saved dashboards but not in saved questions.

up, same painful observation here...
