### ISSUE TITLE
BigQuery should use Service Accounts for OAuth

### ISSUE THREAD

**Issue by spencerhakim** [metabase/metabase#4634]
Instead of an admin [copy/pasting an auth code tied to their Google account](http://www.metabase.com/docs/v0.23.0/administration-guide/databases/bigquery.html), Metabase should support using [Service Accounts](https://developers.google.com/identity/protocols/OAuth2ServiceAccount), which would instead involve uploading a Google-provided JSON file containing a service account address, keypair, and some other metadata (see [Redash's docs](https://redash.io/help/data-sources/bigquery.html) for an idea of what this process is like). The current auth system is bound to cause issues eventually, like when the person who set up Metabase changes jobs and their account is deleted.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Some vague ideas on how this could be implemented in https://github.com/metabase/metabase/issues/7564.

**Comment by hden** [comment]
> when the person who set up Metabase changes jobs and their account is deleted.

We had that exact situation today.

**Comment by mumblez** [comment]
any update on this? Using a gcp service account for this would be ideal!

**Comment by Saurabh-Shrivastava-Narvar** [comment]
Is there any plan of including this in future releases? Using service account will give us more control in sharing datasets.

**Comment by LienM** [comment]
+1 We'd be very happy with this!

**Comment by camsaul** [comment]
@mumblez @Saurabh-Shrivastava-Narvar @LienM if you're interested we'd love a PR for this!

**Comment by hden** [comment]
@camsaul There is a PR for this. https://github.com/metabase/metabase/pull/7907

**Comment by camsaul** [comment]
@hden that PR is "EXAMPLE ONLY", but we'd love a complete PR!

**Comment by camsaul** [comment]
One benefit of supporting service accounts is that it would be easier for people to lock down access to a single dataset (e.g. one service account per dataset, and one Metabase "Database" per service account/dataset). This would however prevent you from doing joins between multiple datasets. 

Thus I think we'd want to support *either* Service Accounts or OAuth w/ a Google Account (i.e., the way things currently work). That way we'd avoid breaking existing setups as well

**Comment by DrPhil** [comment]
Another problem with the current setup is if the google cloud administrator has set a short [session length expiration](https://support.google.com/a/answer/9368756?hl=en).

The auth code will expire and the Metabase admin has to re-authenticate. Failing to do so will cause Metabase queries to that database to fail for all users with `400 bad Request {"error": "invalid_grant", "error_description": reauth related error (rapt_required)", "error_subtype": "rapt_required"}`.

**Comment by camsaul** [comment]
@kdoh adding you to this ticket so we can wire up the FE stuff

**Comment by ashrodan** [comment]
This is great but now has lost the ability to scope auth query federated tables such as google sheets.

Scopes needed are: `https://www.googleapis.com/auth/drive.readonly`

Is there any future efforts here planned to support this.

Several issues in this space have now been logged
https://discourse.metabase.com/t/why-is-metabase-asking-for-access-to-my-google-drive-files/10764/5?u=ashrodan

**Comment by flamber** [comment]
@ashrodan There's an issue open about that #13001
