### ISSUE TITLE
Can not open model page after create a new model when language is Chinese

### ISSUE THREAD

**Issue by ouchuji** [metabase/metabase#46440]
### Describe the bug

Set language to Chinese， then create a model， then the model page crash

### To Reproduce

1. Set language to Chinese
2. Then create a model
3. Then the model page crash

### Expected behavior

Can display the model page

### Logs

[metabase-diagnostic-info-2024-08-02T15_27_59.927Z.json](https://github.com/user-attachments/files/16472400/metabase-diagnostic-info-2024-08-02T15_27_59.927Z.json)

### Information about your Metabase installation

```JSON
- Chrome 127
- WIndow10
- Postgres
- v0.50.18.1
- K3S
- Postgres
```

### Severity

P0

### Additional context
![1](https://github.com/user-attachments/assets/0867805b-06ce-4a2d-975e-3eaa3d4adc50)

_No response_

**Comment by ouchuji** [comment]
when the pr can merge ?

**Comment by dpsutton** [comment]
@ouchuji the PR is merged to the main branch. Waiting on a merge to the release branch (https://github.com/metabase/metabase/pull/46537) and then i need to update the strings in poeditor.com.

**Comment by ouchuji** [comment]
@dpsutton  I update to 0.50.20.  the error page is stll there, but error msg is new , here is the log
[metabase-diagnostic-info-2024-08-19T12_08_04.107Z.json](https://github.com/user-attachments/files/16659994/metabase-diagnostic-info-2024-08-19T12_08_04.107Z.json)
