### ISSUE TITLE
FE doesn't handle API errors in the "Edit user" modal

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#46449]
### Describe the bug

If anything goes wrong during the `PUT /api/user/:id` request (e.g. #46446), frontend doesn't properly handle that error. It leaks the error details in the "Edit user" modal.

### To Reproduce

1. Go to `/admin/people`
2. Click on `...` menu for ANY user and click "Edit user"
3. Trigger the API error* by clicking on the "Update" button in the modal
4. See the error leaking in the modal itself

*Examples:
- Try to use an empty string for a first/last name `"   "`
- Set the browser connection to offline

---
Chrome browser family
![image](https://github.com/user-attachments/assets/1ef30511-3f53-4fac-938b-b3ab421c5026)

Firefox
![image](https://github.com/user-attachments/assets/b2e884aa-7fb8-4626-b345-dedf340b14ce)

### Expected behavior

FE should be more flexible (expect that this request can fail).
FE should not leak abstract error details in the UI.

### Logs

```
console.js:13 TypeError: Cannot read properties of undefined (reading 'id')
    at user.ts:46:1
    at redux-toolkit.modern.mjs:719:1
    at Immer2.produce (immer.mjs:571:1)
    at redux-toolkit.modern.mjs:718:1
    at Array.reduce (<anonymous>)
    at reducer (redux-toolkit.modern.mjs:699:1)
    at combination (redux.mjs:315:1)
    at hu (<anonymous>:3:1043)
    at yu (<anonymous>:3:1331)
    at <anonymous>:3:4637
```

`Request entities,users,2,update failed:`
```
{
  "status": 400,
  "data": {
    "errors": {
      "first_name": "nullable value must be a non-blank string."
    },
    "specific-errors": {
      "first_name": [
        "should be at least 1 characters, received: \"\"",
        "non-blank string, received: \"\""
      ]
    }
  },
  "isCancelled": false
}
```

### Information about your Metabase installation

```JSON
local dev, `master`, da92a62, H2, Sample Database
```

### Severity

P2

### Additional context

Not sure if this is a regression or not, but I suspect not.

**Comment by kamilmielnik** [comment]
Also reported as #46938
