### ISSUE TITLE
Advanced view permissions do not save if you also make changes to create query permissions in the same edit

### ISSUE THREAD

**Issue by sloansparger** [metabase/metabase#46450]
### Describe the bug

Advanced permissions are not saving correctly if first edit an entity to have advanced view permissions and then subsequently edit the create queries permissions to be something different. After save the UI will reflect the previous view permissions.

### To Reproduce

If you set a table to be "Sandboxed" and then subsequently change create queries permissions from "No" to "Query builder only", the sandbox doesn't get included in the POST request and thus doesn't get persisted.

Similarly if you set a database to "Impersonated" then change create queries permissions from "No" to "Query builder only", the impersonation does not get saved.

The above was reproduced on v50. I can reproduce the issue with impersonation on 49 when subsequent edits to the "download results" or "manage table metadata" columns, but table sandboxing works as expect <=v49.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "22.0.2",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "22.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "22.0.2",
    "os.name": "Mac OS X",
    "os.version": "14.2.1",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1 (Debian 16.1-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-08-02",
      "src_hash": "24950de29df4c37be0dadec431aa7d88e19c644c",
      "tag": "v1.2.0-SNAPSHOT",
      "hash": "5607dc9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

**Comment by iethree** [comment]
could this be related to https://github.com/metabase/metabase/issues/46170 ?

**Comment by sloansparger** [comment]
unlikely
