### ISSUE TITLE
Pie chart not working in email subscriptions

### ISSUE THREAD

**Issue by TLazarevic** [metabase/metabase#46489]
### Describe the bug

When sending pie charts via email subscriptions, the chart fails to render.
Message attached. 
![Screenshot 2024-08-05 at 16 02 51](https://github.com/user-attachments/assets/20124c7e-a62f-481e-9b43-ab15a0808a50)

Changing viz of the same question to a bar chart renders the chart in subscription successfully.

I tried changing the display options like legend and percentages, minimal slice percentage, etc, nothing helped.

### To Reproduce

1. Go to a dashboard with a bar chart
2. Set up email subscription
3. Click on Send email now
4. See error - Subscription chart is broken

### Expected behavior

Subscription renders pie charts successfully

### Information about your Metabase installation

```JSON
I am reporting for Metabase v0.50.18.3, but I noticed the same behavior in 49.1. It was one of the reasons for the upgrade.
```

### Severity

Severe for me.

**Comment by Tony-metabase** [comment]
Is it possible you are hitting this issue https://github.com/metabase/metabase/issues/28568

**Comment by TLazarevic** [comment]
@Tony-metabase Possible, since I think I saw numbers and strings being mentioned in the logs once, will try updating the query and report back, thanks for the blazing fast response

**Comment by Tony-metabase** [comment]
You're welcome! Let us know :)

**Comment by TLazarevic** [comment]
@Tony-metabase Confirming as fixed by swapping column order, you can close this one and I'll upvote the original issue. Thanks again

**Comment by npfitz** [comment]
Labelled as a duplicate
