### ISSUE TITLE
Handle long titles better in dashboards

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4648]
There are a few instances where long saved question titles or breakout legends get cutoff, and we don't do anything about it:

With scalars, it would be nice if we let the title wrap ~if there's room, and ellipsify it if not, with a tooltip to show the full title~.

<img width="253" alt="screen shot 2017-03-30 at 11 27 47 am" src="https://cloud.githubusercontent.com/assets/2223916/24520211/88513020-153c-11e7-921c-34d003798290.png">

Same thing on smaller charts like this one ~but probably no wrapping; just ellipsify + tooltip:~

<img width="244" alt="screen shot 2017-03-30 at 11 27 42 am" src="https://cloud.githubusercontent.com/assets/2223916/24520298/c733d55e-153c-11e7-8a6f-a8bf8929b7fc.png">

We're doing a little better on chart legends, but right now the tooltip target is only on the dot instead of on the text as well. That plus ellipsifying the legends would be muy bueno.

<img width="248" alt="screen shot 2017-03-30 at 11 28 07 am" src="https://cloud.githubusercontent.com/assets/2223916/24520313/d4f8d978-153c-11e7-9b9c-2194b0b024d3.png">

**Comment by mazameli** [comment]
Somewhat related to #3979 under the conceptual umbrella of "let's handle small dashboard cards better."

**Comment by mazameli** [comment]
I was about to create this issue all over again. This has reared its head again recently on x-rays:

<img width="347" alt="screen shot 2018-04-26 at 2 07 14 pm" src="https://user-images.githubusercontent.com/2223916/39332079-43bdd856-495b-11e8-838b-40d1181ecdfd.png">

<img width="348" alt="screen shot 2018-04-26 at 2 07 05 pm" src="https://user-images.githubusercontent.com/2223916/39332089-47d8f5a6-495b-11e8-950c-7cbc02f6044f.png">

**Comment by brunobergher** [comment]
We're doing pretty much all of these at this point.
