### ISSUE TITLE
Non-admin requests to /api/search?models=dataset&limit=1 time out for non-admin users on v0.49.20

### ISSUE THREAD

**Issue by KelWill** [metabase/metabase#46510]
### Describe the bug

It takes 60s for non-admin users on our metabase to open up the dropdown menu for "Select a database" after hitting "new question" or "new SQL question." After opening up the network panel, we see a request to /api/search?models=dataset&limit=1 time out with a "504 Gateway Time-out" 

- this route returns quickly for admins. it's only slow for non-admins. switching a user from non-admin to admin will speed things up
- while tailing logs, I don't see this route getting hit
- I don't see any slow queries in metabase's database

https://github.com/metabase/metabase/issues/38557 describes some concerns with performance for this endpoint, but 

A few quick notes about our setup:

- we upgraded to v0.50 before downgrading to v0.49 after seeing a lot of performance problems with v0.50.
- we're backed by a postgresql database
- we have a staging cluster that we can easily destroy and recreate if there are any theories that you'd like us to test
- we're running on k8s (EKS)

### To Reproduce

1. Log in with a non-admin user on a v0.49.20 metabase connected to postgresql
2. Query  /api/search?models=dataset&limit=1 

It should time out. (Sorry this isn't a better repro! I'm not sure what about our setup makes this slow)

<img width="828" alt="Screenshot 2024-08-05 at 3 25 48 PM" src="https://github.com/user-attachments/assets/906be56c-73cd-4ef2-835b-17ba0751b72a">

### Expected behavior

This route should return just as fast for non-admin as admins. 

### Logs

There's nothing interesting in the JavaScript console:

```
Failed to load resource: the server responded with a status of 504 /api/search?models=dataset&limit=1:1
app-main.64b70b1268cea597e09b.js:29 Request entities,search_list,{"models":"dataset","limit":1},fetch failed
```

Surprisingly, I don't see anything in the metabase container's logs either. I _can't_ find any of the /api/search logs when querying as a non-admin user, but I do see them when querying as an admin user:

```
...
2024-08-05 22:55:34,145 DEBUG middleware.log :: GET /api/health 200 1.6 ms (0 DB calls) App DB connections: 3/13 Jetty threads: 31/50 (2 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
2024-08-05 22:55:37,907 DEBUG middleware.log :: GET /api/health 200 1.7 ms (0 DB calls) App DB connections: 3/13 Jetty threads: 32/50 (2 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
2024-08-05 22:55:38,240 DEBUG middleware.log :: GET /api/health 200 329.5 ms (0 DB calls) App DB connections: 3/13 Jetty threads: 32/50 (2 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
```

I also can't find any slow queries in the Postgresql database or any indication that /api/search is reaching the backing DB.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.0-1064-aws",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "mysql",
      "athena",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.15"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-07-09",
      "tag": "v0.49.20",
      "hash": "af03591"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

blocking some users

**Comment by perivamsi** [comment]
@KelWill could you email me at vamsi@metabase.com please? I'll invite you to Slack and we can debug it faster there, if that works for you.

**Comment by johnswanson** [comment]
After https://github.com/metabase/metabase/pull/47395 performance on `/api/search` and other endpoints that involve lots of collection permissions should be much improved.
