### ISSUE TITLE
site-url should always include the protocol

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4651]
When we detect the initial `site-url` we don't include the protocol, i.e. `foo.com` instead of `http://foo.com`.

It would be nice if we did so anything that needs the `site-url` to format URLs could assume it's there, and so that users could see that they could change it to use `https://` if they configure SSL, etc.

Ideally any time `site-url` is set (i.e. manually) we check for a protocol and if it's not present we add `http://` as the default.

**Comment by camsaul** [comment]
are you talking about when running locally? It doesn't include the protocol for `localhost` for whatever reason

**Comment by tlrobinson** [comment]
I think it's more than just `localhost`, I tested by setting up a new instance with `MB_JETTY_HOST=dev1.metabase.com` (with `/etc/hosts` pointing it to 127.0.0.1) and it detected the `site-url` as `dev1.metabase.com`.

**Comment by camsaul** [comment]
this should be easy enough to fix

**Comment by camsaul** [comment]
Fixed by #4656
