### ISSUE TITLE
Models with UUID Columns as Join Keys Generate Invalid SQL

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#46558]
### Describe the bug

If you have two tables with UUID columns, create questions and promote them to models - you cannot join on the UUID columns in the models. The generated SQL is invalid.

### To Reproduce

1. Run a copy of Metabase v50
2. Generate some test tables in Postgres

```
CREATE TABLE test_parent
(
	name varchar(404),
	id uuid default gen_random_uuid (),
	PRIMARY KEY(id)
); 

CREATE TABLE test_child
(
	name varchar(100),
	id uuid default gen_random_uuid (),
	test_parent_id uuid  references test_parent(id),
	PRIMARY KEY(id)
); 
```

3. Create questions from each table
4. Promote them to models
5. From the Question builder, join the two questions
6. View the invalid SQL / attempt to run the Question to see the bad join:

`AS "Test Child Model" ON CAST("source"."id" AS varchar) = "Test Child Model"."test_parent_id"`

https://www.loom.com/share/886dcef3a7a1475da0d681f55f814295

### Expected behavior

Valid SQL should be generated

### Information about your Metabase installation

```JSON
v50.18
```

### Severity

Blocking some users

### Additional context

This worked correctly in v49

**Comment by snoe** [comment]
Likely caused by https://github.com/metabase/metabase/pull/45575
