### ISSUE TITLE
Exports of Pivot Table contains pivot-grouping on version 0.50.15

### ISSUE THREAD

**Issue by VictorOmondi1997** [metabase/metabase#46561]
### Describe the bug

When downloading results from a pivot table (.csv, .xlsx or .json) the results are coming with a `pivot-grouping` column which is not available in the question. The results do not match what the question is displaying.

### To Reproduce

1. Go to any pivot table question in a dashboard or the question itself
2. Click on "Download results" (*if on dashboard*) or "Download full results" (*in the question*)
3. Select the download format (*.csv, .xlsx, or .json*) and download the results
4. Open the downloaded file, there will be a `pivot-grouping` column in it

### Expected behavior

Don't expose system data like pivot-grouping to users.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.0-1026-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-23",
      "tag": "v0.50.15",
      "hash": "c6697cf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking some users

**Comment by natashamathur** [comment]
Hello! @cdeweyx @perivamsi Is there any update on this - could we get a timeline for when it will be looked into?

**Comment by perivamsi** [comment]
@natashamathur sorry, we don't have a timeline yet. will keep you posted. what is your use case?

**Comment by tm-anndee-atendido** [comment]
Hello, also encountering this issue. Can we have an explanation what the `pivot-grouping` column is (i.e. what do these values represent) so that our team may implement an appropriate workaround while the issue is being fixed.

**Comment by Tony-metabase** [comment]
Increasing the priority since it's not just about the pivot grouping column anymore but the download is adding duplicate rows. Making the result very confusing. In the below example the pivot grouping 2 is the addition of the first two in group 0

<img width="575" alt="image" src="https://github.com/user-attachments/assets/82c717a2-5391-4c0b-80da-bf16fdd2b027">

So if you don't know about the problem and decide to add them in csv the amounts don't match

**Comment by paoliniluis** [comment]
@adam-james-v the subscriptions are also rendering really bad due to this, e.g.
![image](https://github.com/user-attachments/assets/9d05d987-aeed-48dd-9dc3-489d3114d293)

will your fixes also fix subscriptions?
