### ISSUE TITLE
Clearing a dashboard filter closes the entire browser tab

### ISSUE THREAD

**Issue by cgddrd-gardin** [metabase/metabase#46570]
### Describe the bug

Clearing a dashboard filter closes the entire browser tab. This applies only to dashboards (questions seem unaffected). From basic testing, issue appears to be isolated to Chrome Browser (Windows and Mac at least). 

### To Reproduce

1. Go to any dashboard with an applied filter.
2. Click on the 'X' icon in the filter box to clear it.
3. See that the browser tab completely closes down.

### Expected behavior

Filter box should be cleared/reset as per the expected behaviour, and the browser tab should not be closed.

### Logs

No browser logs unfortunately as the closing of the tab means we lose that information from Chrome Devtools.

### Information about your Metabase installation

```JSON
Chrome 127.0.6533.89
{"arch":"arm64","os":"mac"}

Mac OS X: 14.6.0

Metabase version: v0.50.19
Metabase hosting environment: AWS ECS
Metabase DB: Amazon Aurora
```

### Severity

Annoying, but can work around it.

**Comment by paoliniluis** [comment]
Please post a video

**Comment by npfitz** [comment]
@cgddrd-gardin I'm not able to reproduce locally, but it's possible there could be a bug specific to the settings your dashboard is using. As @paoliniluis mentioned, a video would be very helpful, along with any other details like what kind of filter you're clearing, and what kinds of questions are in the dashboard

**Comment by kochalex** [comment]
We are seeing this as well, however FWIW I only personally see it on Arc (a chrome based browser) but not Chrome proper.

Here's a potentially useful log from Chrome's console after clicking the X for the filter:

```
ParameterValueWidget.jsx:158 Scripts may close only the windows that were opened by them.
onClick @ ParameterValueWidget.jsx:158

```

**Comment by cgddrd-gardin** [comment]
Thanks for your responses @paoliniluis, @npfitz - I'll sorting out a video for you, weirdly having closed my Chrome browser and reopening it on my Mac, the problem isn't happening now, but it is still happening for a colleague running MS Edge on Windows 11. 

I don't want to waste anyone's time so let me get to a point where I can (hopefully) reliably reproduce this (I thought I could before) and will come back to you shortly.

**Comment by TLazarevic** [comment]
Just encountered the issue 4 times, on 2 different dashboards. Clearing the selected date filter option closed the whole browser tab. The behavior just stopped as I was trying to take a recording.

Browser: Firefox 128.0.3 (64-bit)
Metabase: v0.50.19.1

Not much to record though, the 'last 30 days' date range filter was selected, and while a dashboard was loading, clicking on 'x' to clear the filter closed the tab. The behavior continued, and now I cannot reproduce.

**Comment by cheyuriy** [comment]
Same problem with several dashboards

**Comment by cheyuriy** [comment]
Also found out that it's related to the way you open a dashboard. If it was direct URL, then this issue appears. However if I open it from navigation/search, or just switch tabs in dashboard (in other words, anything that changes URL in browser programmatically), then everything works fine.

**Comment by cgddrd-gardin** [comment]
> Also found out that it's related to the way you open a dashboard. If it was direct URL, then this issue appears. However if I open it from navigation/search, or just switch tabs in dashboard (in other words, anything that changes URL in browser programmatically), then everything works fine.

Great find @cheyuriy!

Confirming this behaviour with video @npfitz, @paoliniluis 

https://github.com/user-attachments/assets/0c205614-244f-415c-8f15-8fa5fc3224d1

**Comment by turbotankist** [comment]
the same issue with v0.50.19 on EKS

**Comment by paoliniluis** [comment]
Prioritized, this is a core flow and many users are hitting this

**Comment by cgddrd-gardin** [comment]
Thanks @paoliniluis!
