### ISSUE TITLE
Pivot Table not showing sub row totals - when using models

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#46575]
### Describe the bug

This is a bug which causes row totals to not show ... What makes it more complex is that it happens for Models based questions that carry a join. There might be other combinations that cause this though

### To Reproduce

There is an example [here](https://stats.metabase.com/question/19076-non-working-pivot-row-total) 

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/b3ea03ca-8774-41cb-bf4e-2320dff5b398">

 
But in summary:

a) Create a model as follows:

![image](https://github.com/user-attachments/assets/3f37c583-7c3c-46cb-8526-14c8afabe55f)

b)  Create a question as follows:

![image](https://github.com/user-attachments/assets/eb8b280a-f9d4-48af-b7b1-9922e7377aa8)

Then Visualise as a Pivot with the combination int he link above. 

What is more confusing is that instead of the model column you use the implicit join for the Users -> Name 

<img width="931" alt="image" src="https://github.com/user-attachments/assets/c55d6f9f-f678-4e19-90f3-ad39b47ca6d3">

You get the proper output

<img width="782" alt="image" src="https://github.com/user-attachments/assets/e90b47cb-469d-472f-be2b-78ae28b2403d">

### Expected behavior

Row totals show up

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
Master happens also on 50
```

### Severity

Annoying

**Comment by zbodi74** [comment]
Escalating - as this is a blocking issue for a paying customer.

**Comment by alxnddr** [comment]
> What is more confusing is that instead of the model column you use the implicit join for the Users -> Name You get the proper output

Even simple reordering of columns here to make the question dirty make it work because dirty queries go to `/api/dataset/pivot` endpoint which works correctly for the same query and the same viz settings.
<img width="346" alt="Screenshot 2024-09-10 at 2 44 38 PM" src="https://github.com/user-attachments/assets/a589afae-1bdb-4482-8961-219c930f8f34">

I assume there is a bug in `/api/card/pivot/:cardId/query` endpoint
