### ISSUE TITLE
Using the same variable multiple times doesn't work

### ISSUE THREAD

**Issue by stem** [metabase/metabase#4659]
Hi,

Same kind of query than #4657 but a different problem :/

my browser and the version: Safari 10.0.3
my operating system: OS X 10.12.3 on the client, some linux on the server
my database: postgres 9.6
Metabase version: 0.23.0 or 0.23.1
Metabase hosting environment: heroku like
Metabase internal database: postgres 9.6

This time, the problem I found is the following syntax :
```
SELECT *
FROM compta
WHERE true
[[ AND ( "Libellé" = {{text}} OR "Pièce"   = {{text}}) ]]
```
which generate the following error when I put a value into `text` : `No value specified for parameter 2.`

This was working fine before 0.23.0.

**Comment by mazameli** [comment]
Yeah, I think I'm seeing this on master and on 0.23.1 unfortunately. :/

![screen shot 2017-03-31 at 10 21 03 am](https://cloud.githubusercontent.com/assets/2223916/24561482/c267c98a-15fb-11e7-9e43-142be94e19c5.png)
