### ISSUE TITLE
Public link toggle should have a way to select URL

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4662]
Not sure when we added these text radio buttons below the public link box, but a weird thing about it is that if you click on `csv` or `json` there's no button to revert the link back to the HTML page, unless you close the modal. Not a huge deal, just a weird quirk that might make users feel momentarily stuck.

![screen_shot_2017-03-31_at_10 46 07_am](https://cloud.githubusercontent.com/assets/2223916/24563519/701a3bc4-1603-11e7-9c4e-576dea1e52b9.png)

**Comment by flamber** [comment]
Hi @mazameli 
I cannot reproduce in 0.31.2 - now I can happily click `CSV` `XLSX` `JSON` and click the selected option, which then returns to the "plain" version without `.extention`.

**Comment by tlrobinson** [comment]
Confirmed
