### ISSUE TITLE
Should parameter widgets work on public questions?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4663]
I'm not sure if there are good reasons why we're not doing this, but if you have a filter widget mapped to a variable in a sql question and then you share it as a public link, the widget(s) is not exposed: 

---
The query:

![screen shot 2017-03-31 at 11 43 36 am](https://cloud.githubusercontent.com/assets/2223916/24564626/5855face-1607-11e7-870e-6cbee8f45ad9.png)

----

The public link:

![screen shot 2017-03-31 at 11 43 51 am](https://cloud.githubusercontent.com/assets/2223916/24564628/5abb4904-1607-11e7-9a01-61f27bed77b7.png)

**Comment by skwasha** [comment]
+1 This would save me from having to adjust date ranges and pulling csvs and sending them to someone. I could just give them the link and be done.
