### ISSUE TITLE
Draft join can cause invalid queries

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#46675]
### Describe the bug

![image](https://github.com/user-attachments/assets/a0373d6d-a3f2-419b-815d-396fcabf34b0)

### To Reproduce

1. New > Question > Orders
2. Join > Reviews > Choose right join column: "Created At" (don't choose the left one)
3. Change join table to Invoices
4. Choose left join column, e.g. "Created At"
5. Visualize

Error:
"Column "Invoices - Created At.CREATED_AT" not found"

### Information about your Metabase installation

master, e6b84e42e05a051f357d8c20ca438ef4e387216c

### Severity

P2

**Comment by mngr** [comment]
the dropdown value should be cleared if the newly chosen table doesn't support it
we should clear local state immediately in this case
