### ISSUE TITLE
When adding a question to a dashboard, skip collection selection step if none exist

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4668]
When adding a question to a dashboard, if no collections exist (of if the user doesn't have permission to view any), we shouldn't make the user click on `everything else` to see the list of questions. ~This might also be happening in the add-card-to-Pulse popout menu but I haven't checked yet.~

![screen shot 2017-03-31 at 10 44 13 am](https://cloud.githubusercontent.com/assets/2223916/24572875/9a087d1e-1631-11e7-9d49-f7d2aea23e2f.png)

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by mazameli** [comment]
If anyone from @metabase/core-developers is looking for a simple issue to take a break from whatever else they're doing, this could be an easy UX win — should be a simple logic fix with no UI/CSS changes. The logic is just, if count of collections == 0, show the list of questions within "everything else." `Else`, show the list of Collections.

**Comment by camsaul** [comment]
Come on, this is a BASIC need for all users. PLEASE do it.
