### ISSUE TITLE
how to connect sqlserver 2008r2?

### ISSUE THREAD

**Issue by tumbler-x** [metabase/metabase#46700]
Hello, I would like to use Metabase to connect to SQL Server 2008 R2, but no matter how many times I reinstall and compile, and regardless of what configurations I make, I still can't add this database. First of all, my database server is functioning properly, and I've also followed many other configuration tutorials. However, the result is always “Time out after 10.0 s” when I try to add it. I suspect that the issue might be due to the built-in JDBC driver in Metabase being too new, causing incompatibility with the older version of SQL Server. Has anyone else encountered this issue? If so, could you please share your solution? I would greatly appreciate it.

**Comment by tumbler-x** [comment]
All configurations were done according to the Metabase documentation, and my SQL Server can be remotely connected via SSMS. However, when trying to add this database in Metabase, I keep getting the error "Time out after 10.0 s."

**Comment by paoliniluis** [comment]
please start a thread in our forums, this is for raising issues, not questions
