### ISSUE TITLE
All Javascript from main site stops working after embedded Metabase iframe is loaded

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#4671]
Metabase 0.23.1 version
When i put iframe(Public embed) on my web sait i got this error:  

Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.
Content Security Policy: Interpreting self as a hostname, not a keyword. If you intended this to be a keyword, use ‘self’ (wrapped in single quotes).

![error](https://cloud.githubusercontent.com/assets/3535911/24614471/f9360770-1893-11e7-9a26-02491fca9e8a.PNG)

**Comment by camsaul** [comment]
This is a P1?

**Comment by MixMe** [comment]
> This is a P1?
what is P1 ?

**Comment by salsakran** [comment]
@MixMe does the iframe display or not?

**Comment by MixMe** [comment]
@salsakran Yes it displayed, but all functionality from main site is blocked

**Comment by salsakran** [comment]
What do you mean by `all functionality from main site is blocked`, do you mean filters not working or something else?

**Comment by MixMe** [comment]
i don't know why but all Javascript from my main site stop working after metabase iframe is loaded

**Comment by MixMe** [comment]
Firefox developer edition show me This: 

![sssss](https://cloud.githubusercontent.com/assets/3535911/24627676/6a04e5aa-18be-11e7-9384-64a83ec365c5.PNG)

**Comment by camsaul** [comment]
I've noticed that -- the embedding pages are calling `GET /api/user/current` even though we're not logged in. But that doesn't cause problems on Chrome (?) so not sure if that's the cause of the issue here

**Comment by camsaul** [comment]
That "self as a hostname" might be the issue, we should wrap that in quotes for sure

**Comment by MixMe** [comment]
in chrome i get this:

![e](https://cloud.githubusercontent.com/assets/3535911/24628175/0ef6382a-18bf-11e7-939b-5f5ba6f807c9.PNG)

**Comment by camsaul** [comment]
Yeah that API error message is expected when calling the endpoint with no session, but it shouldn't cause things to fail to load

**Comment by MixMe** [comment]
maybe it a problem in Yii2 backend compatibility

**Comment by camsaul** [comment]
Strangely enough I'm also seeing that XML parsing error in Firefox when I log in normally:

![screen shot 2017-04-03 at 2 12 30 pm](https://cloud.githubusercontent.com/assets/1455846/24632055/9a5b4b1e-1877-11e7-8ed2-f36eb4a2797b.png)

Weirdly enough everything still works and I can still log in.

Not sure why it's trying to parse the API response as XML. @tlrobinson ?

**Comment by tlrobinson** [comment]
I don't think and of the warnings/errors that have been posted in this thread would explain why the parent frame's JavaScript stops working. I can't think of why that would happen, since iframes are almost totally isolated, except maybe the JavaScript runs on the same thread and the Metabase app is hanging for some reason.

I'll try to reproduce it.

@MixMe does this only happen in Firefox, or other browsers too?

**Comment by tlrobinson** [comment]
@MixMe I'm guessing this is due to incorrect embed code we're generating, issue #4594. The `<iframe>` tag is not self-closing, so instead of doing `<iframe ... />` could you try `<iframe ...></iframe>`?

**Comment by MixMe** [comment]
@tlrobinson Yes, this was the problem, thx ;)
