### ISSUE TITLE
No space between "Field to Map To" and "(required)" 

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#46724]
### Describe the bug

There is no space between "Field to Map To" and "(required)" when mapping field filters in version 50.

### To Reproduce

Create a SQL question with a field filter variable.

![no_space](https://github.com/user-attachments/assets/bd370393-727f-4206-8d69-1ed556f0c53e)

### Information about your Metabase installation

```JSON
v50
```

### Severity

cosmetic

**Comment by nemanjaglumac** [comment]
Not just release v50. This happens in master as well.
