### ISSUE TITLE
Automatic email sending is not working

### ISSUE THREAD

**Issue by lrkarthi** [metabase/metabase#46758]
**Describe the bug**
A clear and concise description of what the bug is Automatic email sending is not working

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to 'spcific dashboard', 
2. Click on 'Subscription
3. Scroll down to send email now and click send email now
4. See error - sending email failed 

[
[pp-analytics-wfa.sequoia.com.har.zip](https://github.com/user-attachments/files/16593555/pp-analytics-wfa.sequoia.com.har.zip)
](url)

**Expected behavior**
email should send successfully, 

**Screenshots**
no screen shot, har file attached for the api response

**Severity**
Major

**Additional context**
cause: "Multiple methods in multimethod 'global-type-settings' match dispatch value: :type/SnowflakeVariant -> :type/Temporal and :type/Number, and neither is preferred"

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-IN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.220-209.869.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.35"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2024-07-30",
      "tag": "v1.50.18",
      "hash": "c323ffc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by paoliniluis** [comment]
Please send us an email to help at metabase dot com
