### ISSUE TITLE
Display type info for endpoint parameters that use custom types in generated docs

### ISSUE THREAD

**Issue by jeff-bruemmer** [metabase/metabase#46799]
In our API docs, we should display type information for endpoint parameters that accept custom types to make it easier for people to work with the endpoints.

Currently, docs generated from our endpoints lose type information for custom types.

For example, in the `card` endpoint, the `type` is missing info. The generated doc just supplies that the type is `:metabase.api.card/card-type`, which isn't useful to people working with the endpoint.

```
## `POST /api/card/`

Create a new `Card`.

### PARAMS:

-  **`visualization_settings`** Value must be a map.

-  **`parameters`** nullable sequence of parameter must be a map with :id and :type keys.

-  **`description`** nullable value must be a non-blank string.

-  **`collection_position`** nullable value must be an integer greater than zero.

-  **`result_metadata`** nullable :metabase.analyze.query-results/ResultsMetadata.

-  **`collection_id`** nullable value must be an integer greater than zero.

-  **`name`** value must be a non-blank string.

-  **`type`** nullable :metabase.api.card/card-type.

-  **`cache_ttl`** nullable value must be an integer greater than zero.

-  **`dataset_query`** Value must be a map.

-  **`parameter_mappings`** nullable sequence of parameter_mapping must be a map with :parameter_id and :target keys.

-  **`display`** value must be a non-blank string.
```

When generated via Rapidocs, we have a similar issue:

![image](https://github.com/user-attachments/assets/ae3fd25f-27e8-4b37-9871-1117a0a390b5)

Ideally, the `type` parameter docs would specify the acceptable values (in this case, the values would be `question`, `model`, or `metric`.)

What else would be cool: if we could include docstrings for these parameters (or types) in the source code, so that we could include notes for key params in the generated docs.

**Comment by iethree** [comment]
🚀 This should also be released by [v0.51](https://github.com/metabase/metabase/milestone/231)
