### ISSUE TITLE
Make ability to run selected portion of a SQL query more discoverable

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4681]
On our discussion board, [Klisko3d had an entirely reasonable suggestion](http://discourse.metabase.com/t/make-it-so-you-can-run-highlighted-parts-of-a-query-to-check-subqueries-and-with-statements/1327/2) to make this feature more discoverable: change the run button to "Run Selection" instead of "Run" when you have something highlighted.

**Comment by flamber** [comment]
Closing, since the UI has changed and there's a tooltip in 0.34.0
