### ISSUE TITLE
OOM error during send-pulses task

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#46830]
### Describe the bug

There's an OOM error happening to some instances in cloud from the `task.send-pulses`.

### To Reproduce

no reproduction steps yet.

### Expected behavior

~

### Logs

[Example logs 1](https://grafana.monitoring.metabase.com/d/Zjw_nJX7k/metabase-logs?orgId=1&var-cluster=prod-prod-eu-central-1&var-filter=OutOfMemoryError&var-namespace=All&var-dns_host=downtown-music.metabaseapp.com&var-pod=All&from=1723507200000&to=1723679999000) (v49.21)

[Example logs 2](https://grafana.monitoring.metabase.com/d/Zjw_nJX7k/metabase-logs?orgId=1&var-cluster=prod-prod-ap-southeast-1&var-filter=OutOfMemoryError&var-namespace=All&var-dns_host=quickli-79.metabaseapp.com&var-pod=All&from=1723507200000&to=1723679999000) (v49.22)

### Information about your Metabase installation

```JSON
49.21 and 49.22
```

### Severity

high

**Comment by qnkhuat** [comment]
We've changed the mechanism to send pulse in 50, see https://github.com/metabase/metabase/pull/41772.

Let's see if this fixes the OOM issue.

**Comment by qnkhuat** [comment]
Closing in favor of https://github.com/metabase/metabase/issues/50863
