### ISSUE TITLE
Common Metrics search doesn't work when you add a space ` `

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#46843]
### Describe the bug

Common Metrics search doesn't work when you add a space ` `

### To Reproduce

Create a bunch of metrics having a space in their name and try to search for them:

https://github.com/user-attachments/assets/208c7bc1-1770-4aaa-97b9-2e0ead52d999

### Expected behavior

I am able to search for names which have a space in their name

### Logs

None

### Information about your Metabase installation

```JSON
master and version 50
```

### Severity

annoying

**Comment by crisptrutski** [comment]
Not sure whether this is an issue on the FE or BE, starting from the front.

**Comment by romeovs** [comment]
This will be fixed when we merge https://github.com/metabase/metabase/issues/46843
