### ISSUE TITLE
Broken link to models article under "Custom List" option in dashboard filter

### ISSUE THREAD

**Issue by jessicaul** [metabase/metabase#46865]
### Describe the bug

The link in Metabase has an extra "learn" which results in the "Page Not Found"

Mistake is in [this line](https://github.com/metabase/metabase/blob/e426b1a3b9cf8f818d84e110fb664042025f68a7/frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceTypeModal.tsx#L445), it shouldn't have `learn`, just `/data-modeling/models`
[ValuesSourceTypeModal.tsx](https://github.com/metabase/metabase/blob/e426b1a3b9cf8f818d84e110fb664042025f68a7/frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceTypeModal.tsx)
 `const href = getLearnUrl("learn/data-modeling/models");`

### To Reproduce

1. 
![Screenshot 2024-08-14 at 1 17 50 PM](https://github.com/user-attachments/assets/c5321fc3-cf19-4b2d-b342-0e832c74965d)
2. 
![Screenshot 2024-08-14 at 1 22 56 PM](https://github.com/user-attachments/assets/0f2e7c73-dd3b-45b0-a713-afae8d098870)
3. ![Screenshot 2024-08-14 at 1 22 56 PM](https://github.com/user-attachments/assets/ff16e882-9dc8-4fed-963e-1aa1ed57f364)

Error: 
![Screenshot 2024-08-14 at 1 39 47 PM](https://github.com/user-attachments/assets/dfd51d16-7feb-4968-850f-a45ce927a49b)

### Expected behavior

Hyperlink should go to `https://www.metabase.com/learn/data-modeling/models`

### Information about your Metabase installation

```JSON
Looks like this link never worked so information about installation is not relevant :)
```

### Severity

not severe at all

**Comment by crisptrutski** [comment]
Thanks for reporting! Opened a PR.
