### ISSUE TITLE
Migrations `DISABLE TRIGGER ALL;` on Google Cloud SQL db instance lead to error

### ISSUE THREAD

**Issue by Kulikovpavel** [metabase/metabase#46874]
### Describe the bug

In some migrations there is a line that run operation `DISABLE TRIGGER ALL` /  `ENABLE TRIGGER ALL`
 e.g.
```
-- Changeset migrations/001_update_migrations.yaml::v50.2024-01-10T03:27:30::noahmoss
-- Migrate data-access permissions from `permissions` to `data_permissions`
SET SEARCH_PATH TO public, "$user","public";

ALTER TABLE data_permissions DISABLE TRIGGER ALL;
```

This operation requires `superuser` rights (because system trigger exists) from Postgresql user, which is impossible to get with managed google cloud sql instance.

Happily, it can be replaced with `DISABLE TRIGGER USER` or ignored, seems there is no user triggers or Foreign keys mismatch. But need to spend some time to check and run manual migrations.

### To Reproduce

1. Take db with user without superuser rights
2. Run `DISABLE TRIGGER ALL` migrations

### Information about your Metabase installation

```JSON
Migrating metabase from 0.47 to 0.50
Google cloud SQL, Postgresql 14.2
```

### Severity

annoying

**Comment by crisptrutski** [comment]
We're retracted this command in v50.21, see https://github.com/metabase/metabase/pull/46826

**Comment by chukwuma-azubuike** [comment]
I noticed the docker image for v50.21 has not been pushed. Is there a timeline for this?

**Comment by crisptrutski** [comment]
@chukwuma-azubuike we have just released it
