### ISSUE TITLE
Static Embed Preview Dropdown Menus Broken Until Published

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#46872]
### Describe the bug

If you create a new dashboard with dropdown filters on it and set up a static embed - the dropdown menus don't work in preview mode until after you publish the dashboard.

### To Reproduce

1. Set up version 49+ (didn't test older than that)
2. Enable embedding
3. Create a dashboard
4. Create a simple question with the People table & add it to the dashboard
5. Add a text filter and wire it to "Source"
6. See that the dashboard filter has a drop down menu
7. When setting up the static embed set the parameter to "Editable" 
8. Look at the preview and note that the param is an input box instead of a menu
9. Publish the embed
10. Check the param in the preview again and note that it works

https://www.loom.com/share/bb9f8e531e5d448c911a0aa9b1823e31

### Expected behavior

The preview should mirror what the published dashboard will look like

### Information about your Metabase installation

```JSON
testing in 49.23 and 50.13
```

### Severity

Very confusing to users

**Comment by kulyk** [comment]
Should be fixed in x.50.14 by #45447
