### ISSUE TITLE
We should show what's the query going to the DW on linked filters

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#46888]
**Is your feature request related to a problem? Please describe.**
The way that Metabase works is magical, but sometimes it's neat to know the inner workings of the tricks of the magician in complex scenarios. E.g. linked filters can really drive someone crazy if they don't render the results you're expecting or it simply doesn't work. The reality is that linked filters will send a query to the DW but the only way to see it is by profiling the DW, which many times is useless due to the amount of queries being sent

**Describe the solution you'd like**
A feature that can show me the queries being sent to the DW when using linked filters, only for admins

**Describe alternatives you've considered**
Profiling the DW, which is cumbersome

**How important is this feature to you?**
Well... it could have saved me endless debugging hours and probably a few thousand hairs

**Additional context**
NA

**Comment by thebiglabasky** [comment]
Could we at least ensure these are logged so accessible through the logs (maybe with a label allowing to quickly search for them)? That seems like a 1 liner which could indeed save a ton of time...
