### ISSUE TITLE
/admin/databases/:id with unknown ID shows 500 Internal Server Error

### ISSUE THREAD

**Issue by devurandom** [metabase/metabase#46886]
### Describe the bug

I open `/admin/databases/:id` on a Metabase instance, where `:id` is any integer that does not correspond to an existing database, and see raw HTML for a 500 Internal Server Error.

### To Reproduce

1. Go to `/admin/databases` and check what database IDs exist (on a pristine system only ID 1 would exist)
2. Go to `/admin/databases/100` (assuming ID 100 does not correspond to an existing database; any other non-existent ID also works)
3. See the literal text `<html> <head><title>500 Internal Server Error</title></head> <body> <center><h1>500 Internal Server Error</h1></center> <hr><center>nginx</center> </body> </html>` (see screenshot below)
4. In browser dev tools, see that this is the raw response from a `GET /api/database/100` HTTP request

### Expected behavior

I would expect to get a 404 Not Found page instead, similar to what I get when I go to `/admin/gobbledegook`.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.220-209.869.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "starter",
    "version": {
      "date": "2024-08-14",
      "tag": "v1.50.20.3",
      "hash": "3fb0cf2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

### Additional context

![screenshot](https://github.com/user-attachments/assets/cffe266d-039a-4d27-83c4-6524029e5317)

**Comment by crisptrutski** [comment]
It's also slightly different running master on my dev machine 🤷 

<img width="461" alt="Screenshot 2024-08-15 at 17 26 37" src="https://github.com/user-attachments/assets/e4ac2cc6-43c6-42e5-8f7f-738c0b32e6b3">

**Comment by rafpaf** [comment]
This is solved
