### ISSUE TITLE
System permission on application database: RI_ConstraintTrigger

### ISSUE THREAD

**Issue by xavierraffin** [metabase/metabase#46902]
### Describe the bug

I am installing Metabase with [latest](https://hub.docker.com/layers/metabase/metabase/latest/images/sha256-f7b5dc52c21aaa2dca910a450e7e6119a975090ce9fc80726aa0742882ca176c?context=explore) docker image using an application database on Google Cloud SQL Postgresql.
The connection works and all the metabase table are created but metabase fail to start with the following error:

```
Reason: liquibase.exception.DatabaseException: ERROR: permission denied: "RI_ConstraintTrigger_c_83876" is a system trigger [Failed SQL: (0) ALTER TABLE data_permissions DISABLE TRIGGER ALL]
```
Since it is not possible to provide metabase with superuser permissions on GCP I am unable to finalize the deployment.

**Reverting to metabase/metabase:v0.49.23 solve the problem. This is a regression on the latest**

### To Reproduce

Deploy latest docker image with a postgresql application database with no superuser permissions.

### Expected behavior

Metabase should start.

### Information about your Metabase installation

```JSON
- Metabase latest (August 15th 2024)
- Cloudrun GCP
- Google Cloud SQL with PostgresQL 15
```

### Severity

prevent deployment

**Comment by paoliniluis** [comment]
please use v50.20.3

**Comment by xavierraffin** [comment]
It works with v0.50.20.3.
Why does it fail with `latest` ? This is the version mentioned by the documentation and it is nice to auto update.
