### ISSUE TITLE
To view scrollbars in pivot viz in dashboard you must first scroll "outer" scrollbars

### ISSUE THREAD

**Issue by ilvenini** [metabase/metabase#46928]
### Describe the bug

When I put a pivot in a dashboard, I can't scroll columns and rows normally (verified in Chrome)
There are in fact an horizontal and a vertical scrollbar, which I must scroll (respectively) right and down, to see the "real" pivot scrollbars.
The two "outer" scrollbars get generated even if the pivot doesn't need scrolling.
![image](https://github.com/user-attachments/assets/6369231e-f368-41c5-a132-2db2167ee65d)
![image](https://github.com/user-attachments/assets/b11bfc95-b3a1-4f79-b38e-0c8ae41c98fb)

### To Reproduce

1. Go to dashboard
2. Click on edit dashboard, add questions -> examples -> orders according to sources per quarter

### Information about your Metabase installation

```JSON
Browsing on Chrome 127.0.6533.120 (Windows 11)
Metabase v0.50.20 on Docker container running on Ubuntu 24.04
Metabase internal DB: Postgres on Docker container running on Ubuntu 24.04
Database: Citus on Docker container running on Ubuntu 24.04
```

### Severity

Can't show dashboard with pivot viz to customers

**Comment by cdeweyx** [comment]
Can't repro on Mac [here](https://stats.metabase.com/dashboard/644-email-subscriptions-all-the-charts?month_and_year=&tab=576-tab-1), seems specific to Linux

**Comment by cdeweyx** [comment]
Not closely related but found this as well during repro: https://github.com/metabase/metabase/issues/47019

**Comment by ilvenini** [comment]
Tried downgrading to v.0.49.0 (using the same setup) and I didn't encounter the bug: pivot was working as expected.
Then went back again to v0.50.20 and the bug came back.
