### ISSUE TITLE
When creating a new collection, a color should be randomly assigned to it automatically

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4693]
Right now a default color isn't assigned, randomly or otherwise, to new collections which blocks the "done" button until a color is manually chosen. We should just randomly assign one instead and let the user change it if they want; it'll decrease friction.

Also, the primary button text for the create/edit collection modals should probably be `Done` instead of `Update`.

![screen shot 2017-04-04 at 2 32 32 pm](https://cloud.githubusercontent.com/assets/2223916/24680020/2312bace-1944-11e7-8c81-fe76d5aae06e.png)

**Comment by camsaul** [comment]
yeah honestly i was a little confused when i first tried to create a new collection i was like why is the ~~Save~~ Update button disabled and how do I enable it 

I tried adding a description and then realized I had to pick a color

**Comment by kdoh** [comment]
Yeah this used to work properly. Clearly something regressed.

**Comment by salsakran** [comment]
seeing this again in 0.24

**Comment by salsakran** [comment]
nvm. user error.
