### ISSUE TITLE
Feature Request | Embedded Dashboard Filtering

### ISSUE THREAD

**Issue by starantino** [metabase/metabase#4702]
### Embedded Dashboard Filtering

I am thrilled to see we now have the ability to embed dashboards on client sites! 

I would love to see the ability to be able to filter data on the embedded dashboards. This would allow myself and I am sure many others to leave some of our highly priced analytics providers. I have clients who like to filter out the data I provide them for example if they have regions and want to check on users from a specific region they can filter by that region or any other field they wish within the dashboard I embed in their system.

I currently use Cloud9Charts--all it would look like is a filtering icon on the dashboard at each question/query on the dashboard and then implement 3 drop-down menus:

1. Field to Filter by
2. Condition (Equals, not equal to etc)
3. Values (from selected field) which can be multiple.

![capture](https://cloud.githubusercontent.com/assets/13489240/24707516/e155df50-19e1-11e7-8e60-405d1c400506.jpg)

**Comment by tlrobinson** [comment]
@starantino Are you using a "public embed" or a JWT-signed "application embed"?

The latter definitely supports parameters (you need to add them to the dashboard first under the funnel icon, then enable them in the embed modal).

The former isn't currently enabled but we have issue #4663 tracking that.

**Comment by jornh** [comment]
#4663 mentioned above was closed back in v0.24. In addition we got the super nice filter criteria picker UI enhancements around v0.27-ish (very close to the screenshot above) I think this feature request is resolved and is safe to close as having no more meat 🥩 on it.

**Comment by mbvictoria** [comment]
Closing - last comment states this is resolved.
