### ISSUE TITLE
Upgrading from 48 -> 49 with PostgreSQL backends fails because user is not superuser

### ISSUE THREAD

**Issue by veer0318** [metabase/metabase#47057]
### Describe the bug

I'm trying to upgrade Metabase from version 48 to version 49. This does not work, as some of the SQL migrations run the command `ALTER TABLE ... DISABLE TRIGGER ALL` which is [an action which can only be executed by a PostgreSQL superuser](https://stackoverflow.com/questions/67371661/postgresql-permissions-for-disable-enable-trigger-all). As it is bad practice to connect to the database as a superuser when not strictly necessary, this should be treated as a bug.

The solution is also quite simple: don't be lazy and don't rely on `.. DISABLE TRIGGER ALL` but disable the triggers that should be disabled. As it is now, it also disables FK checks (as they, internally in PostgreSQL, are triggers).

A temporary work-around (confirmed to work) is to **temporarily** set the metabase storage user in PostgreSQL to superuser and then disable it. This works, but is a (small) security risk and prevents sensible automatic upgrades if you manage a whole bunch of Metabase installations. __However__, this does not work if you're PostgreSQL is hosted in the cloud (e.g. Azure), as you're not allowed to be a superuser, so this only fixes the issue for some, not all.

### To Reproduce

1. Have a working installation of Metabase 48 with a PostgreSQL storage backend
2. Attempt to install Metabase 49 and run it
3. See it fail on the error as copied below in the logs.

### Expected behavior

Being able to upgrade without depending on superuser privileges. 

### Logs

dl-co-metabase.1.l359jeziub6w@server    | 2024-08-21 11:13:12,243 INFO db.liquibase :: Checking if Database has unrun migrations...
dl-co-metabase.1.l359jeziub6w@server    | 2024-08-21 11:13:13,323 INFO db.liquibase :: Database has unrun migrations. Checking if migration lock is taken...
dl-co-metabase.1.l359jeziub6w@server    | 2024-08-21 11:13:13,347 INFO db.liquibase :: No migration lock found.
dl-co-metabase.1.l359jeziub6w@server    | 2024-08-21 11:13:13,348 INFO db.liquibase :: Migration lock acquired.
dl-co-metabase.1.l359jeziub6w@server    | 2024-08-21 11:13:13,717 INFO db.liquibase :: Running 66 migrations ...
dl-co-metabase.1.l359jeziub6w@server    | 2024-08-21 11:13:14,146 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v50.2024-01-10T03:27:30::noahmoss encountered an exception.
dl-co-metabase.1.l359jeziub6w@server    | liquibase.exception.DatabaseException: ERROR: permission denied: "RI_ConstraintTrigger_c_365022" is a system trigger [Failed SQL: (0) ALTER TABLE data_permissions DISABLE TRIGGER ALL]
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.lambda$child$0(Scope.java:186)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:195)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:185)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:164)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.lambda$child$0(Scope.java:186)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:195)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:185)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:164)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:252)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:256)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.lambda$child$0(Scope.java:186)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:195)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:185)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:164)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.command.CommandScope.execute(CommandScope.java:217)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.lambda$child$0(Scope.java:186)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:195)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:185)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:164)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Liquibase.update(Liquibase.java:234)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Liquibase.update(Liquibase.java:212)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Liquibase.update(Liquibase.java:194)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44483.invoke(liquibase.clj:360)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$run_in_scope_locked$reify__44479.run(liquibase.clj:325)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.lambda$child$0(Scope.java:186)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:195)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:185)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.Scope.child(Scope.java:164)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:318)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:301)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:349)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:342)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$migrate_BANG_$fn__53428.invoke(setup.clj:84)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$do_with_liquibase$f_STAR___44420.invoke(liquibase.clj:140)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:143)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:131)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.RestFn.invoke(RestFn.java:425)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$setup_db_BANG_$fn__53456$fn__53457.invoke(setup.clj:167)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$setup_db_BANG_$fn__53456.invoke(setup.clj:161)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db$setup_db_BANG_$fn__53481.invoke(db.clj:86)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.RestFn.invoke(RestFn.java:421)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.core$init_BANG_.invokeStatic(core.clj:170)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.core$init_BANG_.invoke(core.clj:165)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.core$start_normally.invokeStatic(core.clj:182)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.core$start_normally.invoke(core.clj:176)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.core$entrypoint.invokeStatic(core.clj:215)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.core$entrypoint.doInvoke(core.clj:209)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.Var.applyTo(Var.java:705)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.core$apply.invokeStatic(core.clj:667)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.core$apply.invoke(core.clj:662)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
dl-co-metabase.1.l359jeziub6w@server    | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
dl-co-metabase.1.l359jeziub6w@server    | 	at metabase.bootstrap.main(Unknown Source)
dl-co-metabase.1.l359jeziub6w@server    | Caused by: org.postgresql.util.PSQLException: ERROR: permission denied: "RI_ConstraintTrigger_c_365022" is a system trigger
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
dl-co-metabase.1.l359jeziub6w@server    | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
dl-co-metabase.1.l359jeziub6w@server    | 	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
dl-co-metabase.1.l359jeziub6w@server    | 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
dl-co-metabase.1.l359jeziub6w@server    | 	... 86 more
dl-co-metabase.1.l359jeziub6w@server    | 
dl-co-metabase.1.l359jeziub6w@server    | UPDATE SUMMARY
dl-co-metabase.1.l359jeziub6w@server    | Run:                         66
dl-co-metabase.1.l359jeziub6w@server    | Previously run:             287
dl-co-metabase.1.l359jeziub6w@server    | Filtered out:                50
dl-co-metabase.1.l359jeziub6w@server    | -------------------------------
dl-co-metabase.1.l359jeziub6w@server    | Total change sets:          403
dl-co-metabase.1.l359jeziub6w@server    | 
dl-co-metabase.1.l359jeziub6w@server    | 
dl-co-metabase.1.l359jeziub6w@server    | FILTERED CHANGE SETS SUMMARY
dl-co-metabase.1.l359jeziub6w@server    | DBMS mismatch:               50

### Information about your Metabase installation

```JSON
Version 49 (updgrading from version 48)
```

### Severity

High: blocking safe & sane upgrades, thus potential security issues for security fixes in Metabase

**Comment by crisptrutski** [comment]
We have [retracted the disabling of triggers](https://github.com/metabase/metabase/pull/46826) in newer releases, so you can try updating to v50.20.7 instead.

**Comment by veer0318** [comment]
@crisptrutski alright, thanks; I am working the most recent Docker image you published (when I log in, after migration, I get v0.50.20). Could it simply be that this Docker image is lagging behind and thus not version v0.50.20.7 but an earlier one?

**Comment by crisptrutski** [comment]
@veer0318 the docker image for 50.21 has just been released

**Comment by veer0318** [comment]
Just to confirm: as expected, everything works again with version 50.21 (tested via the Docker image). Great work!
