### ISSUE TITLE
Add documentation to update metabase when running on Docker

### ISSUE THREAD

**Issue by benjR** [metabase/metabase#4709]
### Feature requests and proposals
Such as what exists for Heroku, a part on the documentation to update Metabase when running on Docker would be great, to update without any loss of data depending on the options you run the docker container with (without specifiying the metabase.db location and using it).

Exemple for Heroku :
http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html#deploying-new-versions-of-metabase

**Comment by tlrobinson** [comment]
We should also consider adding a VOLUME declaration to the Dockerfile to automatically create a persistent volume.

Open PR with some other Docker docs improvements #4264

**Comment by benjR** [comment]
Thanks for the updates @tlrobinson ;)

So the complete doc to upgrade metabase with docker should be as follows, right ?

docker cp metabase:/metabase.db.mv.db /mylocaldir/metabase.db
docker stop metabase
docker rm metabase
docker pull metabase/metabase:latest
docker run -d -p: 3000:3000 -v /mylocaldir:/tmp -e "MB_DB_FILE=/tmp/metabase.db" --name metabase metabase/metabase:latest

Would there be a reason why when doing this, it would not use this file but start as if it's a completely new install ?

**Comment by c-schmitz** [comment]
Why was this issue closed? The documentation still lacks detail on this.

**Comment by benjR** [comment]
@c-schmitz What was not clear for you? Maybe I can help

**Comment by christianseel** [comment]
Hi! The documentation does not explain how to actually update the image (`docker pull metabase/metabase:latest`). That should be added from my point of view.
