### ISSUE TITLE
Improve the story for encryption of settings

### ISSUE THREAD

**Issue by johnswanson** [metabase/metabase#47101]
We added the ability to never-encrypt certain settings. We should go through the existing settings and decide which ones can safely be never-encrypted. This probably includes all booleans.

**Comment by dpsutton** [comment]
reopening because we should be a bit more comprehensive. I'm trying to see the values of `'query-caching-min-ttl'` and `'query-caching-ttl-ratio'` but many of them are encrypted. These are non-sensitive numbers.
