### ISSUE TITLE
Hipchat integration

### ISSUE THREAD

**Issue by blopker** [metabase/metabase#4712]
Hello, first off Metabase is great. Thank you.

This is a feature request for Hipchat integration, similar to the Slack integration. It looks like there is already a request for Telegram support: https://github.com/metabase/metabase/pull/4462
If a more generalized solution can be made for this, maybe it can fit all three use cases (Slack, Telegram, Hipchat).

Cheers!

⬇️  Please click "like" instead of leaving a `+1` or 👍  comment

**Comment by edenzik** [comment]
+1

**Comment by blopker** [comment]
Just wanted to refresh my interest in this feature. We're using Metabase more and more and while email pulses are great, many people prefer chat integration.

Thank you!

**Comment by JoaquinIbar** [comment]
Thanks for making Metabase awesome!

Email is getting more uncommon for collaborative teams, another used tool is [Microsoft Teams](https://products.office.com/en-us/microsoft-teams/group-chat-software) it is (really) similar to Slack, this is also a possible integration.

Or simple `Pulse` with webhooks it will be great! 😄

**Comment by jornh** [comment]
@JoaquinIbar For webhook you want to 👍 upvote #2298

**Comment by JoaquinIbar** [comment]
Upvoted @jornh :D, I would love to develop myself but I am still trying to learn Clojure sorry about that!

**Comment by kdoh** [comment]
Atlassian [discontinuing Hipchat and partnering with Slack](https://www.atlassian.com/partnerships/slack) and telling folks to migrate to it basically seals the deal on this I think. Going to close it in light of that. We should still make non Slack integrations easier just so we don't completely abandon alternatives to team chat hegemony.
