### ISSUE TITLE
Allow editing of just database + column of a question 

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4714]
In unifying some data pipelines, I'm consolidating two tables that have largely the same fields. It would be awesome if I could somehow keep a question's filters, aggregations, visualization settings, etc but just have it point to a new table.

**Comment by flamber** [comment]
Closing in favor of #6496

**Comment by slavashaz** [comment]
@salsakran 
If anyone needs it, I've made my script and uploaded in my repository. https://github.com/slavashaz/Metabase-Dashboard-Cloner
you can clone your dashboard with automatic changes for another db or same db but different identical table
