### ISSUE TITLE
Line Visualization is squashed when the SQL Editor box is open

### ISSUE THREAD

**Issue by ysim** [metabase/metabase#4718]
### Bugs

- Your browser and the version: Firefox 52.0.2 (64-bit)
- Your operating system: OS X 10.11.6 
- Your databases: Postgres 
- Metabase version: v0.23.0
- Metabase hosting environment: Docker on AWS EC2 Container Service
- Metabase internal database: Postgres

*Repeatable steps to reproduce the issue*

1. Create a new card. Compose a SQL query in the editor and create a line visualization for it. 
1. Select 'Get Answer'
1. The line visualization that is produced is 'squashed' to the bottom of the window by the SQL editor box, like so: 

<img width="1221" alt="screen shot 2017-04-07 at 15 20 59" src="https://cloud.githubusercontent.com/assets/1258564/24801786/e466903e-1ba5-11e7-8467-a48f04856f45.png">

vs being displayed in full with the option to scroll down to look at it in its entirety, which seems more logical - this way, it makes you think that there was something wrong with the query altogether, when in reality the line visualization is fine once you hide the SQL editor.

**Comment by salsakran** [comment]
Ick. That looks pretty questionable.
