### ISSUE TITLE
`Lib.isNumber` returns `false` for aggregation-based columns after join is removed

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#47184]
### Describe the bug

https://github.com/user-attachments/assets/0fdad69e-ef03-4de4-9084-6c24748402d8

### To Reproduce

_this might not be the optimal path to reproduce and certainly isn't the only possible one_

1. New > Question > Orders > Save
2. New > Model > Notebook > Use question from step (1) as data source > Join Reviews on Product ID = Product ID > Count > Save
3. New Dashboard > Add new number filter
4. Add model from step 2 to dashboard 
5. Try to connect the number filter to the model - notice that you can choose "Count" column
6. Save dashboard
7. Open model
8. Edit query definition
9. Remove join
10. Save
11. Go back to dashboard
12. Try to connect the number filter to the model

### Expected behavior

It should be possible to connect the "Count" column to the number filter

### Information about your Metabase installation

master, 743ae09aca

### Severity

P2

### Additional info

This `Lib.isNumber` check gives unexpected result for the "Count" column: https://github.com/metabase/metabase/blob/bcd1a90cb67e4aa10da252aa296b00f06496a74f/frontend/src/metabase-lib/v1/parameters/utils/filters.ts#L52

**Comment by kamilmielnik** [comment]
TODO: When working on this issue, please search for `https://github.com/metabase/metabase/issues/47184` in `e2e/test/scenarios/dashboard-filters/dashboard-filters-query-stages.cy.spec.ts` and uncomment related blocks.

_This suite will be added in #46958 and will go to an integration branch (#47167) before landing in `master`.

**Comment by metamben** [comment]
@kamilmielnik, my [repro](https://www.loom.com/share/60636d9a96e5410e8631dd7285f42f16?sid=6046a021-614d-4cd7-b6b0-9c134aaac73f) fails already at step 5. Am I not following the steps properly?

**Comment by kamilmielnik** [comment]
> Am I not following the steps properly?

I think you are.
In my original video steps 3 and 4 are done in reverse order but that should not matter though.

It seems that something else must have gotten broken since this issue was reported.
