### ISSUE TITLE
Add setting to make query analysis synchronous on card updates

### ISSUE THREAD

**Issue by crisptrutski** [metabase/metabase#47180]
By default, we use a queue with a single consumer to asynchronously analyze cards when they change. This is to avoid adding latency to the UI or strain to the server.

The idea is to add a new setting which can toggle between the current async behavior and a fully synchronous mode, where analysis is done as part of the API calls to update cards.

In particular, this setting will be useful for our e2e tests, to avoid complexity and flakes due to task scheduling in-determinism. We've recently done a fair amount of optimization to the analysis, and its not too expensive, especially for deployments with few cards and a low mutation rate, so exposing this to customers as well should be fine - although please run that past @luizarakaki.

Note that this *should not* use `analyze-sync!`, which synchronously waits for the analysis worker to receive the job, and does not wait for it to complete it. This method is poorly named, and should only be used by the sweeper task. What we want instead is for the analyze to be performed immediately as part of the card mutation hook, i.e. we want to call`analyze-card!`.

Feel free to improve the naming in this area as part of the task, naming was hard. 
Note that merely overriding `execution` will have the unwanted side effect of removing our rate limiting back pressure from the sweeper job, so we'll need to do something a bit different. The whole structure around the `execution` dispatch key is up for rework, if necessary.

**Comment by tsmacdonald** [comment]
We decided to make it synchronous on update all the time (not toggled by a setting). Will be fixed in #47231
