### ISSUE TITLE
Proper E2E round-trip test (with on-disk YAMLs)

### ISSUE THREAD

**Issue by piranha** [metabase/metabase#47222]
We don't have any full e2e tests (with files to test against already stored on disk) and we need even if just to see that serialization format is not changed much after every change.

It would also catch bug like #47220, since they main reason it happened - data wasn't read from disk, but used from memory.

**Comment by crisptrutski** [comment]
The e2e tests already do write to disk, but the issue is that they diff a subset of the properties in memory only.

Rather than more `db -> yaml -> db` testing, we're going to do `yaml -> db -> yaml`, and do an (almost) exhaustive cross-check.
