### ISSUE TITLE
Non-ASCII Characters in CSV Column Names Cause SQL Syntax Error in Metabase Upload

### ISSUE THREAD

**Issue by jobins-devs** [metabase/metabase#47279]
### Describe the bug

When uploading a CSV file to Metabase where the column names contain non-ASCII characters (e.g., Japanese characters), the upload fails with an SQL syntax error. This issue occurs despite the fact that rows containing non-ASCII text are handled correctly when column names are in English.

### To Reproduce

1. Create a CSV file with non-ASCII characters (e.g., Japanese) in the column names.
   - Example CSV content:

   ```csv
   ID,名前,年齢,職業,都市
   1,佐藤太郎,25,エンジニア,東京
   2,鈴木花子,30,デザイナー,大阪
   3,田中一郎,28,マーケター,名古屋
   4,山田次郎,35,プロジェクトマネージャー,福岡
   5,中村美咲,32,データサイエンティスト,札幌
   ```

2. Attempt to upload the CSV file to Metabase.

3. Observe the error message:

   ```
   (conn=20363649) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%90%8D%E5%89%8D(), E5%B9%B4%E9%BD%A2(), E8%81%B7%E6%A5%AD(), E9%83%BD%E5%B8%82()' at line 1
   ```

### Expected behavior

The CSV file should be uploaded without errors, with non-ASCII characters in column names correctly interpreted and stored.

### Logs

(conn=20363649) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%90%8D%E5%89%8D(), E5%B9%B4%E9%BD%A2(), E8%81%B7%E6%A5%AD(), E9%83%BD%E5%B8%82()' at line 1

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "6.1.38-59.109.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.37"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": "Asia/Tokyo"
    }
  }
}
```

### Severity

moderate

**Comment by crisptrutski** [comment]
Thanks for the report. 

It turns out that the issue is only triggered if there are headers that start with a non-ASCII character, so you can work around it by adding a prefix to the relevant headers, e.g. 

```
ID,_名前,_年齢,_職業,_都市
```

We're working on a fix and it should land in the next patch and minor releases.

Note that the column names will also be encoded, so you will need to configure display names manually for now. We plan to improve this in the future.

**Comment by jobins-devs** [comment]
@crisptrutski Thank you for prompt response, will do use workaround as possible.
