### ISSUE TITLE
Remove default borders from entity picker's button in the sdk's CreateQuestion component

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#47344]
The entity picker in create question are dependent on CSS resets being available - the default button style with gray borders are appearing. If we add `appearance: none` and `border: none` to the button, it should get rid of the browser-default grey border.

This happens when you use `<CreateQuestion />` SDK component in a React application that does not have CSS resets for buttons.

![Image](https://github.com/user-attachments/assets/ae93971f-b938-412f-8f84-79192f9a568f)

**Comment by npretto** [comment]
I may be able to fix this too while working on https://github.com/metabase/metabase/issues/47624 so I'll temporarily assign it to myself so that people don't start working on this

**Comment by npretto** [comment]
This particular issue seems to be fixed, but the modal is rendered outside of the portal so it has other styling issues
