### ISSUE TITLE
Docker image shouldn't run Metabase as root

### ISSUE THREAD

**Issue by 5an1ty** [metabase/metabase#4734]
Seems very dangerous to run a java process as root. Is there any reason why you are not dropping to lower permissions?

**Comment by tlrobinson** [comment]
We should probably just run as a non-root user to begin with. I think adding the following to the Dockerfiles (`Dockerfile` and `bin/docker/Dockerfile`) will do it:

```
RUN addgroup -S metabase && adduser -S -g metabase metabase
USER metabase
```

In the meantime, you can add these arguments to the `docker run` command: `-u 65534 -w /tmp -e _JAVA_OPTIONS=-Duser.home=/tmp` per https://blog.csanchez.org/2017/01/31/running-docker-containers-as-non-root/ (note that it changes the workdir and thus location of the H2 database, if you're using H2 and haven't set MB_DB_FILE)

**Comment by 5an1ty** [comment]
Hi, thanks for the feedback, yes you should run as non root to begin with. You should probably use some environment variables like PGID and PUID for the user you create in the container. This will help avoid file system permission issues as I can pass these with docker run and make sure the folder that I mount has permissions for that GID and UID.

**Comment by tlrobinson** [comment]
@5an1ty Do you know of any Docker containers that do this the "right" way?

**Comment by 5an1ty** [comment]
@tlrobinson 

One example: https://github.com/linuxserver/docker-mariadb#user--group-identifiers

they use PGID and PUID environment variables.

some best practices from docker themselves (they solve it a different way):

https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#entrypoint

they run their entrypoint as root chown the folder that is mounted and then exec the process with gosu to drop privileges and run the process as the user they created.

I think both solutions are fine, its a matter of preference.

The first solution works great if you need to share the folder with other processes / docker containers.

The second solution is great if you want to use the mounted folder exclusively for your process. the host system / other docker containers wont mind.
