### ISSUE TITLE
Suffix is Added to "Rate of Change" in Tooltip

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#47373]
### Describe the bug

If you add a custom suffix to a series in a chart that generates a period over period change rate in the tooltip - the suffix is added to the rate of change. 

![suffix_rate](https://github.com/user-attachments/assets/3058bca9-39d0-40c7-b975-f6fb215ceb29)

### To Reproduce

1. Set up v50
2. Create question from the Orders table that sum of discount grouped by month
3. Add a custom suffix like "kr" or "dollars"
4. View the line chart and mouse over the data point and see that it will say something like "+18.3% dollars"

### Expected behavior

Either remove prefix and suffixes from the rate of change in the tooltip or split it out into it's own setting

### Information about your Metabase installation

```JSON
v50
```

### Severity

Annoying

**Comment by cdeweyx** [comment]
Should tackle https://github.com/metabase/metabase/issues/42867 at the same time if we can
