### ISSUE TITLE
Slack notification mixes metrics

### ISSUE THREAD

**Issue by danilofuchs** [metabase/metabase#47392]
### Describe the bug

We upgraded from v0.49.13 to v0.50.22 and now one of our periodic Slack dashboard notifications is showing wrong metrics:

Before:
![image](https://github.com/user-attachments/assets/b90e3fa4-9e14-4097-a82a-d01974626ee6)

After:
![image](https://github.com/user-attachments/assets/a1bae4c4-f428-4aee-8f09-10f42fe58882)

Now, some numeric questions have the value, and link to, the first question in the dashboard

### To Reproduce

1. Create a dashboard with multiple numeric questions
2. Send a Slack notification
3. Most metrics point to the first one

### Expected behavior

Each metric should be independent

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-08-26",
      "tag": "v0.50.22",
      "hash": "16a6c22"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.220-209.869.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Misleading metrics for our business team

**Comment by danilofuchs** [comment]
Update:
I sent another Slack notification manually, and one metric which was wrong is now correct. This seems like a caching issue

**Comment by luizarakaki** [comment]
> I sent another Slack notification manually, and one metric which was wrong is now correct. This seems like a caching issue

Only one? The others are still repeating the first question?

**Comment by danilofuchs** [comment]
> > I sent another Slack notification manually, and one metric which was wrong is now correct. This seems like a caching issue
> 
> Only one? The others are still repeating the first question?

Correct, this was the behavior

We upgraded to 0.50.23.1 and the issue seems fixed, I will reopen if it happens again
