### ISSUE TITLE
Azure MySQL database --require_secure_transport=ON

### ISSUE THREAD

**Issue by SilvaFernando** [metabase/metabase#47399]
### Describe the bug

Hi team.

I'm triyng using Metabase + Azure MySQL Database with require secure transport on and not working, follow my configs:
MB_DB_TYPE=mysql
MB_DB_DBNAME=nome_do_banco
MB_DB_PORT=3306
MB_DB_USER=usuario
MB_DB_PASS='pa$$w0rd'
MB_DB_HOST=mysql.database.azure.com
MB_DB_SSL=true
MB_DB_SSL_CA_CERT=/caminho/para/DigiCertGlobalRootCA.crt.pem

I tried using this URI too: MB_DB_CONNECTION_URI=jdbc:mysql://database.azure.com:3306/metabase?user=metabase&password=passwordc&verifyServerCertificate=true&useSSL=true&requireSSL=true&sslmode=REQUIRED&serverSslCert=/usr/share/metabase/DigiCertGlobalRootCA.crt.pem

### To Reproduce

Try  use Metabase with Azure database with require secure transport=ON

### Logs

Caused by: java.sql.SQLTransientConnectionException: Could not connect to address=(host=mysql.database.azure.com)(port=3306)(type=master) : (conn=11864) Connections using insecure transport are prohibited while --require_secure_transport=ON.
 

### Information about your Metabase installation

```JSON
Azure MySQL database with Require_Secure_tranport=ON
 
I can't copy admin > troubleshooting because Metabase does not start :(
```

### Severity

Unable to use Metbase

**Comment by paoliniluis** [comment]
You need to use the MB_DB_CONNECTION_URI environment variable, not the other approach. What’s the log that you get when you use the URI?

**Comment by SilvaFernando** [comment]
Am I correct in using this ENV? 

MB_DB_CONNECTION_URI=jdbc:mysql://database.azure.com:3306/metabase?user=metabase&password=passwordc&verifyServerCertificate=true&useSSL=true&requireSSL=true&sslmode=REQUIRED&serverSslCert=/usr/share/metabase/DigiCertGlobalRootCA.crt.pem

**Comment by SilvaFernando** [comment]
@paoliniluis I tried and worked, thanks :)
