### ISSUE TITLE
Interactive embed using JWT SSO authentication doesn't pass all URL parmeters through

### ISSUE THREAD

**Issue by outinspace** [metabase/metabase#47425]
### Describe the bug

I'm trying to embed a Metabase interactive view in our SaaS product using JWT SSO. The authentication works, but URL parameters in the SSO return url are dropped after the first parameter.

![image](https://github.com/user-attachments/assets/addc4b48-ad72-4329-aaac-cc035c691ceb)

### To Reproduce

- Set up interactive embedding scenario with JWT SSO.
- Hide UI elements using URL parameters in the return_url passed to /auth/sso.
- Bug: Only the first URL parameter is kept in the iframe src.

### Expected behavior

The entire return url should be preserved from Metabase's /auth/sso endpoint.

### Information about your Metabase installation

```JSON
- Chrome v128.0.6613.85
- MacOS Sonoma 14.5
```

### Severity

Low

**Comment by paoliniluis** [comment]
version of metabase?

**Comment by rafavalerio** [comment]
Seeing something similar, where I have some params being passed in the JWT, but getting back from Matabase:
`You must specify a value for :projectid in the JWT.`

I can see the param present in the JWT when I decode it

**Comment by albertoperdomo** [comment]
@rafavalerio [Your issue](https://github.com/metabase/metabase/issues/47436) is related to static embedding, which also relies on a JWT, but unrelated to this issue, which is about interactive embedding and JWT SSO.

**Comment by albertoperdomo** [comment]
@outinspace I believe this is the intended product behavior:
* the params are stripped from the URL but
* the logo and side nav will still be hidden if the user navigates around

If this is what you are observing and you have a different expectation (preserve the params), I would consider this a request for improvement and it would help to understand why.

If this is not what you are observing, e.g. the side_nav or logo appear after the user navigating around, this is a bug and we'll fix it. We would need to know which version of Metabase you are using.

**Comment by npretto** [comment]
@outinspace I think I reproduced what you're running into, is it possible you're not encoding the `return_to` query string parameter in the sso endpoint when you redirect the user?
I can see you're doing that in the iframe url, but it needs to be done also in the sso endpoint.
For me the fix was this:
```diff
- MB_BASE_URL + "/auth/sso" + "?jwt=" + jwtToken + "&return_to=" + url
+ MB_BASE_URL + "/auth/sso" + "?jwt=" + jwtToken + "&return_to=" + encodeURIComponent(url)
```

**Comment by albertoperdomo** [comment]
BTW, I've found that it's best to [point the iframe to the local SSO endpoint in the app and include the return_to param there](https://github.com/metabase/metabase-nodejs-express-interactive-embedding-sample/blob/main/index.js#L135), and then have the [SSO endpoint handle the additional params and the URL encoding](https://github.com/metabase/metabase-nodejs-express-interactive-embedding-sample/blob/main/index.js#L190-L196).

**Comment by outinspace** [comment]
Thanks for the quick feedback guys. I'm using v1.50.22. I think I've figured out the issue. It seems that `encodeURI` strips off URL params after the first one, but `encodeURIComponent` preserves them all.
