### ISSUE TITLE
Filtering Dates by Quarter

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#4742]
Users should be able to filter by quarter when filtering on dates. This is useful for any type of "Quarter to Date" or "Last X Quarters" visualizations, which I think is a good use-case. If we have granularity as fine as by minutes and hours, we should also include by quarter to fill the gap between monthly and yearly.

If there's a hacky way to do this (without using distinct dates that quarters start on), please let me know.

Didn't see a current PR or Issue related to this, but feel free to direct me if I've missed it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mvrabel** [comment]
But it is possible to group by quarter. At least in the  0.24.2 version.
![inception_quarter](https://user-images.githubusercontent.com/12628893/27030426-745a7116-4f6c-11e7-8f96-5e0647eee1f7.PNG)

**Comment by doodlebro** [comment]
@mvrabel: My issue is regarding the filters, not the group by.

**Comment by jornh** [comment]
Related: 3785

**Comment by rafho1** [comment]
Hi, found this request - would like the option to filter by [previous | current | next] quarter
