### ISSUE TITLE
Failing migration between 0.50.10 and 0.50.22

### ISSUE THREAD

**Issue by ActualAl** [metabase/metabase#47450]
### Describe the bug

Migrating between community editions 0.50.10 -> 0.50.22 produced the following error:

```
ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries:
Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
) STORED]
```

### To Reproduce

1. Go to a version 0.50.10
2. Upgrade to 0.50.22

### Expected behavior

It should migrate as normal

### Logs

ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries:
Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
) STORED]

### Information about your Metabase installation

```JSON
This isn't browser related.

The metabase instance is running on AWS ECS - we've had no issue migrating in the past but I'm not sure how to debug a syntax error.
```

### Severity

blocking an upgrade

**Comment by qnkhuat** [comment]
Could you provide info about your database?

**Comment by paoliniluis** [comment]
Please upgrade your Postgres

**Comment by ActualAl** [comment]
Thanks for your replies everyone. We're running PG v11.22 - I'll update to latest and try again
