### ISSUE TITLE
Custom fields cannot be visualized, but should be

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#4745]
Specifically, it looks like when I create a visualization that uses a custom field, I am able to use the series on the X-axis, but not add it as a series on the Y-axis.

![screen shot 2017-04-10 at 11 55 02 am](https://cloud.githubusercontent.com/assets/7634378/24875218/9dc25686-1de4-11e7-9ad3-7f8c00cb2bc9.png)

![screen shot 2017-04-10 at 11 55 19 am](https://cloud.githubusercontent.com/assets/7634378/24875224/a44b5ca0-1de4-11e7-8f44-e043fe7a4649.png)

As seen in the second screen shot, I am unable to add the custom field 'net new mrr' as a Y-axis series. I am unsure of why this is, since any custom field should be visualizable on either axis.

**Comment by mazameli** [comment]
That's eerie: I was literally just trying to reproduce the old issue I filed for this same problem: https://github.com/metabase/metabase/issues/3952

Pretty sure this issue is a dupe of that one, but correct me if I'm wrong.

**Comment by doodlebro** [comment]
@mazameli: Nice, thanks for the push in the right direction. Hope it gets fixed soon!

**Comment by mazameli** [comment]
@doodlebro just thought you'd like to know that [we've shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
