### ISSUE TITLE
Order Metrics Alphabetically in GUI editor

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#47465]
**Is your feature request related to a problem? Please describe.**
Now, Common Metrics in the GUI editor are not ordered alphabetically/indexed, but yes, by creation date. This, to some users, can be confusing.
<img width="271" alt="Screenshot 2024-08-30 at 12 51 19 PM" src="https://github.com/user-attachments/assets/79691f25-8379-4eed-ab4e-94309740b59b">

**Describe the solution you'd like**
Have a way to sort them or order them alphabetically by default

**Describe alternatives you've considered**
N/A

**How important is this feature to you?**
Requested by a customer, internal ticket [here](https://app.usepylon.com/issues?conversationID=908b339e-4b90-4c22-a0c7-cfce213fdce3)

**Additional context**
N/A

**Comment by mngr** [comment]
Fixed here
