### ISSUE TITLE
Add onSave and isSaveEnabled prop to CreateQuestion component in the sdk

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#47464]
Add the `onSave` and `isSaveEnabled` prop to the `<CreateQuestion />` component in the SDK, to allow handling when the question has been saved (e.g. close the modal) and to hide the save button.
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/47442
- [ ] #47538
```

**Comment by oisincoveney** [comment]
All tasks are done 🎉
