### ISSUE TITLE
New time granularity filter acting weird

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4751]
This is on Chrome on our stats instance. No JS errors.

The new time granularity dropdown on time series is behaving sort of oddly. I find I have to make a selection twice before it seems to take effect. Or I'll make a selection on the dropdown, and the query will appear to refresh but then nothing changes and the dropdown reverts to the previous state.

[Here's a video of the behavior](http://recordit.co/2flIiumIbR). Notice how after I change it to `Week`, it gets stuck when I try to change it back to `Day`, etc.

**Comment by mazameli** [comment]
@tlrobinson, @salsakran I think this is a bug we ought to prioritize, yeah?

**Comment by salsakran** [comment]
Prioritizing it because it keeps happening to me =)

JK, mainly cause it's a brand new feature that's directly in sight of everyone using the product.
