### ISSUE TITLE
Remove `enable-embedding` and introduce `enable-embedding-static` and `enable-embedding-interactive`

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#47524]
#### Description
- Remove `enable-embedding`
- Introduce `enable-embedding-static` (implement in https://github.com/metabase/metabase/issues/47525)
- Introduce `enable-embedding-interactive` (implement in https://github.com/metabase/metabase/issues/47526)

Using this [migration strategy](https://www.notion.so/metabase/Feature-flag-and-settings-for-SDK-8ed424c776194528b6332c5fc2510a0c#6a615898a14648bfae230652e9d87f2d).

#### Note
- Most usage of `enable-embedding` would be referred to `enable-embedding-static` instead. Only the usage around setting the value to frame-ancestors that we should be referred to `enable-embedding-interactive` instead.
- We could almost say that this is like 90%+ renaming `enable-embedding` to `enable-embedding-static` as most of the code uses `enable-embedding` for static embedding, the rest 10% is for interactive embedding.

**Comment by escherize** [comment]
closed by https://github.com/metabase/metabase/pull/48154
