### ISSUE TITLE
Add a new string setting `embedding-app-origins-sdk`

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#47522]
Add a new `string` setting `embedding-app-origins-sdk`
- Will be used for authorized SDK hosts on production
- `localhost:*` is always assumed (always append `localhost:*` to whatever the value this input has).

Here’s how this ~setting~ works:
  - When `enable-embedding-sdk: true`
      - By default, if the request origin is `localhost` from any port, we’ll allow it and return the same origin back in `Access-Control-Allow-Origin`
      - If users specify `localhost` in the value, just ignore it since it works the same way as the implicit `localhost:*` matching.
      - For EE users with a token with `embedding-sdk` flag, this input is editable and we allow saving this value, otherwise, don’t allow modifying this value.
  - When `enabled-embedding-sdk: false`
      - No CORS headers are set

**Comment by escherize** [comment]
Hi @WiNloSt, Can you explain what shape you expect this string setting to have? Is it a list of comma seperated `host:port|*`'s?

EBNF explained here:

```
S = h +
h = host ':' port
host = ip | hostname
ip = \d+ '.' \d+ '.' \d+ '.' \d+
hostname = \w+
port = \d+ | '*'
```

Please let me know what you expect, and how you think this will be updated. (In the meantime I'll see if I can figure it out on your PR).

**Comment by escherize** [comment]
We can take an array of strings as json that we can validate on-write, I think that could work better for this, compared to encoding a collection inside of a string.

**Comment by escherize** [comment]
Should this default to `"localhost:*"`, (or `["localhost:*"]`, or even `[{:host "localhost" :port "*"}]`)?

The reasons to go for json are that it's easier to validate the shape, and it's easier to go from data -> string than parse it (and include good error messages).
