### ISSUE TITLE
Add a new boolean setting `enable-embedding-sdk`

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#47521]
Add a new `boolean` setting `enable-embedding-sdk`
- [x] Default value: `false`
- [x] Unencrypted
- [x] Will be used for enabling or disabling embedding SDK.
- [ ] This flag works independently from `enable-embedding-static` and `enable-embedding-interactive`
- [x] Send snowplow events when it is toggled, like `enable-embedding` does

**Comment by escherize** [comment]
@WiNloSt Do we know if `enable-embedding-sdk` should send snowplow events whenever it is toggled?

**Comment by escherize** [comment]
I am going to swap out usages of the `enable-embedding` defsetting, but keep it there so we can add a deprecation notice when it gets set (and maybe forward it's environment variable value into `MB_ENABLE_EMBEDDING_SDK`)
