### ISSUE TITLE
Link back to related cards in emailed Pulse seems to be broken.

### ISSUE THREAD

**Issue by pygeek** [metabase/metabase#4754]
Metrics are not clickable in the emailed pulse (Gmail - Safari + Chrome).
Metrics seem to be clickable but do not go anywhere (Apple Mail).

- Latest Chrome browser and Safari browser
- OSX 10.11.6
- MySQL
- Metabase version 0.23
- Metabase hosting environment Docker
- Metabase internal database: H2

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

Steps to reproduce:
- create an email pulse
- add metrics
- send test email
- attempt to click a metric in the email should fail.

**Comment by mazameli** [comment]
Hmm, I can't reproduce this with Gmail on either Safari or Chrome. I'm on the master branch of MB, MacOS Sierra (10.12), PostgreSQL. I tried both with an existing pulse and with a test email sent from a new pulse, and was able to click through on everything. I wonder if there's some kind of security setting you have that's preventing click through? Or an extension? I know you said it's also not working with Apple Mail, either, but have you tried on an incognito browser window?

**Comment by camsaul** [comment]
Going to go ahead and close this out since we couldn't repro it back in April and haven't heard back after asking for more info. @pygeek if you think this is in error and you are still running into issues please let us know and we can reopen this.
