### ISSUE TITLE
Can't run SQL questions (or models) if there's a least 1 table with "blocked" permissions

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#47547]
### Describe the bug

If you have at least 1 table with blocked permissions, you won't be able to run SQL questions

### To Reproduce

1) create a question (select * from people)
2) create a group and a user, add this user to the group
3) go to permissions, and block access to a single table
![image](https://github.com/user-attachments/assets/0d2a2b01-edb2-4992-88da-518026a46aa5)

(BTW: all users should have everything blocked)

4) log in as the user and try running the SQL question

### Expected behavior

The user should be able to run the SQL question (it has permissions to run questions, and we don't care about the block, unless we did a change in v50 that blocking a single table implies that the SQL questions can't be run)

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P?

### Additional context

regression?

**Comment by WiNloSt** [comment]
Noah mentioned [this is documented](https://www.metabase.com/docs/latest/permissions/data#blocked-view-data-permission).

**Comment by paoliniluis** [comment]
Although I agree @WiNloSt, this is a spot of confusion, and several customers hit this spot already. I would really like product to make the call here
