### ISSUE TITLE
Option to customize which dashboard tabs are sent in dashboard subscription 

### ISSUE THREAD

**Issue by J-Reichardt** [metabase/metabase#47550]
**Is your feature request related to a problem? Please describe.**
Some users are only interested in some tabs in a dashboard, while others are interested in all of them. 

**Describe the solution you'd like**
It would be nice to select which dashboard tabs are to be sent in a subscription mail. Also only filters linked to the chosen tabs would need to be selected.

**Describe alternatives you've considered**
The current working alternative is to create multiple redundant dashboards for each different subscription. This results in a high number of dashboards which all have to be maintained.

**Comment by paoliniluis** [comment]
I think this is a dupe of https://github.com/metabase/metabase/issues/36366

**Comment by MfMark** [comment]
We also need this feature of setting subscriptions on specific tabs
