### ISSUE TITLE
Notebook editor's entity picker button and the pick columns button is different in size in the sdk

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#47561]
In the notebook editor, the button for entity picker and the "pick columns" button directly on the right size has a slight size difference. It is supposed to be of equal size.

![CleanShot 2567-09-03 at 20 47 38@2x](https://github.com/user-attachments/assets/dbd21aad-b7ed-4188-b542-fbc218afe7a1)

**Comment by npretto** [comment]
This seems to be fixed either on master or on a branch i'm opening soon
