### ISSUE TITLE
Add a loading state in the ModifyQuestion component when the question is being loaded

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#47562]
When the question is being loaded in ModifyQuestion, we are left with a brief period where the question editor becomes empty. Should we add a loading state here?

<div>
    <a href="https://www.loom.com/share/7c12d5adab7f4205b1e2bd326c0096d5">
      <p>Should we add a loading state in ModifyQuestion - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/7c12d5adab7f4205b1e2bd326c0096d5">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/7c12d5adab7f4205b1e2bd326c0096d5-820e83a1a0de5380-full-play.gif">
    </a>
  </div>

**Comment by oisincoveney** [comment]
@heypoom i think we should close this one since we'll probably nuke ModifyQuestion soon?

**Comment by albertoperdomo** [comment]
ModifyQuestion has been deprecated.
