### ISSUE TITLE
Entity picker's hover colors are not themeable in the sdk

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#47560]
In the entity picker that is part of the notebook editor (`<InteractiveQuestion.Editor />`), the hover color of the entity picker button (e.g. in the Recents tab) makes it so that the text is not legible. It should support dark-themed apps as well.

Recents Button Hover

![CleanShot 2567-09-03 at 20 42 27@2x](https://github.com/user-attachments/assets/93eb7b7f-987c-4749-bc2d-3f6d1a7c4ace)

Sidebar Button Hover

![CleanShot 2567-09-03 at 20 46 12@2x](https://github.com/user-attachments/assets/15449f8e-089a-472a-a17d-aa964b599d5f)

Tab Hover

![CleanShot 2567-09-03 at 20 46 46@2x](https://github.com/user-attachments/assets/20200696-ca64-4472-8406-5faeef299858)

**Comment by albertoperdomo** [comment]
@heypoom Is this issue specific to Shoppy themes or generic (SDK)?
