### ISSUE TITLE
Can't see vertical and/or horizontal scrollbar in pivot chart

### ISSUE THREAD

**Issue by ilvenini** [metabase/metabase#47595]
### Describe the bug

As you can see, there are no scrollbars.
![Screenshot from 2024-09-04 00-11-57](https://github.com/user-attachments/assets/335c9eff-59e2-4bac-998c-434d47cf80af)

The same chart shows scrollbars correctly when put inside a dashboard
![Screenshot from 2024-09-04 00-15-33](https://github.com/user-attachments/assets/3bb11c0d-416a-48b5-8eb1-984417ce5868)

### To Reproduce

1. Create new chart
2. Select pivot as visualization
3. Notice no scrollbars when expected

### Information about your Metabase installation

```JSON
- Metabase 0.50.23 on Docker container running on Ubuntu 24.04
- Browser: Chromium/Firefox on Ubuntu 24.04
```

### Severity

Can't explore data on a pivot if mouse has no horizontal scrolling capability

**Comment by iethree** [comment]
🚀 This should also be released by [v0.51](https://github.com/metabase/metabase/milestone/231)
