### ISSUE TITLE
Always allow `localhost:*` in `embedding-app-origin`

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#47615]
> [!note]
> The work in the PR should be replaced by the work in https://github.com/metabase/metabase/issues/46970 when merged.

This is a follow up task for https://github.com/metabase/metabase/pull/47229. As a temporary measure as the actual work would be implemented in https://github.com/metabase/metabase/issues/46970, but that feature won't be merged to `master` until we feel ready.

Without this, we won't be able to test the CLI without valid enterprise token, because without valid tokens, users can't modify `embedding-app-origin`.

**Comment by iethree** [comment]
🚀 This should also be released by [v0.51](https://github.com/metabase/metabase/milestone/231)
