### ISSUE TITLE
Minified React Error on embedding Questions

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#47617]
### Describe the bug

A Minified React Error is popping out on 50 for some questions. It could be related to data that our react app is not able to handle. Question works on metabase without issues

### To Reproduce

I am using a csv output from a customer.

1) Upload the csv [test_dataset.csv](https://github.com/user-attachments/files/16868877/test_dataset.csv) to metabase
2) Go to New -> Question using this data -> Bar Chart -> X-Axis Month and the Y-Axis Owner Earnings same as below:

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/2ecc04f9-e96a-449f-a3f7-db5e435c4bb3">

3) Go to Embedding -> Preview

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/ca6706dd-3be0-4706-9517-3282493e0c78">

Fails both on preview and on actual embedding with error `Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

### Expected behavior

The Question loads 

### Logs

Nothing on the backend everything frontend:

`Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

### Information about your Metabase installation

```JSON
50.24
```

### Severity

Broke some questions of a customer and potentially other customers will reachout. This was working on 49

**Comment by WiNloSt** [comment]
Can't reproduce with `master` @ c86e4b3fa394af347ead1d8953d75a697a49262e
<img width="1181" alt="Screenshot 2024-09-04 at 9 29 25 PM" src="https://github.com/user-attachments/assets/840ad6ce-4a56-42ef-8734-3cee794e871c">

But can reproduce with `release-x.50.x` @ d40b0287c95fb3433b97c42ec05f08f5fde3263f
<img width="1161" alt="Screenshot 2024-09-04 at 9 34 22 PM" src="https://github.com/user-attachments/assets/a4ed9d23-33aa-4af9-ba86-d35691f487da">
