### ISSUE TITLE
If we export something that relies on an import from "embedding-sdk" the users of the sdk will see it types as any

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#47627]
Thread 1: https://metaboat.slack.com/archives/C063Q3F1HPF/p1723023805043939

Thread 2: https://metaboat.slack.com/archives/C063Q3F1HPF/p1725464383559709

**Comment by heypoom** [comment]
I think this is caused by the fixup script not fixing up "embedding-sdk" references.

![image](https://github.com/user-attachments/assets/216b6c8c-6c75-4c1d-bb36-1607c846e694)
