### ISSUE TITLE
Archived cards are included in dashboard subscriptions

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#47649]
### Describe the bug

If you have a dashboard that has archived cards on it, the dashboard subscriptions will include those cards.

### To Reproduce

1. Setup email
2. Create a card and Add it to a dashboard
3. Create a dashboard subscription
4. Archive the card
5. Try sending the dashboard subscription
6. See the archived card is included in the email

### Expected behavior

Archived cards should be excluded

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

**Comment by iethree** [comment]
🚀 This should also be released by [v0.51](https://github.com/metabase/metabase/milestone/231)
