### ISSUE TITLE
Error upgrading metabase 0.46.6 to 0.50.24

### ISSUE THREAD

**Issue by wangxiaojie0506** [metabase/metabase#47657]
### Describe the bug

Im trying to upgrade my self hosted metabase (docker) from 0.46.6 to 0.50.24, but the following migration fails: Migration failed for changeset migrations/001_update_migrations.yaml::v49.00-059::qnkhuat:

with the following error:
Reason: clojure.lang.ExceptionInfo: (conn=3836133) SAVEPOINT 70c9749c-9fa1-48d3-9c82-1eb4ffc3c2f8 does not exist {:toucan2/context-trace [["resolve connection" {:toucan2.connection/connectable org.mariadb.jdbc.MariaDbConnection}] ["resolve connection" {:toucan2.connection/connectable nil}]]}

### Information about your Metabase installation

```JSON
OS: centos 7.9
database : mysql 8
run by docker
```

### Severity

yes

### Additional context

[databasechangelog.txt](https://github.com/user-attachments/files/16886525/databasechangelog.txt)

**Comment by wangxiaojie0506** [comment]
the following error is also occur when i use a new empty database to redeploy 0.50.24

**Comment by paoliniluis** [comment]
Please upgrade your Postgres or MySQL database version

**Comment by wangxiaojie0506** [comment]
thanks, but which version need i upgrade to ?

**Comment by paoliniluis** [comment]
@wangxiaojie0506 can you check 52.5?
