### ISSUE TITLE
Multiple line series is not displayed in embedding

### ISSUE THREAD

**Issue by nakazavva** [metabase/metabase#4768]
Version: 0.23.1

When I put multiple line series on a dashboard and embed it into an application,  the API, 

`GET /api/embed/dashboard/:token/dashcard/:dashcard-id/card/:card-id` 

returns 200 for the one series(card), but returns 400 for the rest.

**Comment by tlrobinson** [comment]
I believe this is a backend issue. It appears to affect JWT embedding but not public links.

**Comment by camsaul** [comment]
Note sure why that would be the case since they're both powered by the same function. What's the message for the 400?

**Comment by nakazavva** [comment]
@camsaul sorry that's not 400, returns 404 "Not Found". I will show you later on with screenshot.

**Comment by nakazavva** [comment]
@camsaul returns 400 "Bad Request", the following are screenshots.

My multi line series is a combination of card 38 and 29.


In embedding, multi line series does not work. it even call card 29 twice.
![2017-04-13 10 17 50](https://cloud.githubusercontent.com/assets/15145442/24986717/e05a702e-2036-11e7-8bcc-799e6b2e7cdb.png)


In embedding, remove 29 card, only one line works fine.
![2017-04-13 10 18 52](https://cloud.githubusercontent.com/assets/15145442/24986614/3f3fedc2-2036-11e7-88ae-2586d16829bd.png)


just copy and paste the url to browser which has 400 response.
![2017-04-13 10 21 40](https://cloud.githubusercontent.com/assets/15145442/24986615/3f66c28a-2036-11e7-9b2c-12f6cc691fe0.png)

**Comment by camsaul** [comment]
What do you see in the server logs?

**Comment by nakazavva** [comment]
Sorry for late response. here is the server logs

![2017-04-13 17 12 26](https://cloud.githubusercontent.com/assets/15145442/24996151/b952c73e-206c-11e7-985b-471cc4f023b5.png)
![2017-04-13 17 12 44](https://cloud.githubusercontent.com/assets/15145442/24996153/bad87716-206c-11e7-8e9a-85daa1dbf53c.png)
![2017-04-13 17 13 09](https://cloud.githubusercontent.com/assets/15145442/24996155/bc378afc-206c-11e7-8752-0aad7630ca84.png)

**Comment by tlrobinson** [comment]
@metabase/core-developers Just ran into this again. I'd call it a P1.5

**Comment by attekei** [comment]
Seems that there are multiple interrelated bugs. With a dashcard composed of multiple questions (either multi line/area/bar chart or multi scalar chart) I encounter error 404 when trying to load the second cards of composed dashcards instead of error 400.

Starting to work on fixing these now.

**Comment by attekei** [comment]
Seems that `resolve-dashboard-parameters` in https://github.com/metabase/metabase/blob/899ab30acaecc8380e81edfefc67dccf5a821ee2/src/metabase/api/embed.clj#L162-L162 doesn't currently search from `dashboardcard_series` and for that reason throws 404 for cards in composed dashcards.

For normal public dashboards, kinda similar `public-dashcard-results` in https://github.com/metabase/metabase/blob/0eae3323dadb9f132722fc88f1173407d29afd3b/src/metabase/api/public.clj#L193-L193 does include also `dashboardcard_series` to the search.

Do you think @camsaul that this is quick to fix?

**Comment by rhansma** [comment]
This issue is still present in version 0.24.2. When attaching multiple line series to one graph the response when embedding is: 400 Bad Request, with as body:  Not found.

Any updates on a possible fix?

Please let me know if there is anything I can do to help fix this issue.

**Comment by zirmite** [comment]
I've run into this issue as well.

**Comment by wouafff** [comment]
same for me

**Comment by ivanaclairineirsan** [comment]
I encountered the same issue

**Comment by mazameli** [comment]
Hey everyone. Just a heads up that [we've just shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
