### ISSUE TITLE
New collection modal missing a heading

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4769]
The `create new collection` modal is supposed to have a title like this:

![screen shot 2017-04-12 at 12 40 22 pm](https://cloud.githubusercontent.com/assets/2223916/24976196/57a8e30a-1f7d-11e7-83a2-84990d2ec989.png)

Currently it has nothing by default, like this:

![screen shot 2017-04-12 at 12 39 58 pm](https://cloud.githubusercontent.com/assets/2223916/24976205/63b459ea-1f7d-11e7-839d-a30feb9eeb84.png)

Then, as you start typing in a name, the screen awkwardly jumps down and fills in the name of your collection as you type, which is jarring:

![screen shot 2017-04-12 at 12 40 04 pm](https://cloud.githubusercontent.com/assets/2223916/24976219/73eab26e-1f7d-11e7-858d-e28cdcace5a1.png)

**Comment by kdoh** [comment]
Pretty sure this is related to the problem in #4758 (in fact you can see it in that same screenshot). I'll fix this as. part of #4764

**Comment by mazameli** [comment]
Sweet. If it looks easy enough to do, might as well throw a fix for #4693 in there, too.
