### ISSUE TITLE
AWS guide S3 URL isn't a valid S3 URL

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#4770]
According to a tweet from this morning:

> AWS guide URL is out of date :) The one listed is not a valid S3 path.  I used https://s3.amazonaws.com/downloads.metabase.com/v0.23.1/metabase-aws-eb.zip

**Comment by camsaul** [comment]
Apparently the Markdown has

```
http://downloads.metabase.com/{{ site.latest_version }}/metabase-aws-eb.zip
```

But http://downloads.metabase.com/v0.23.1/metabase-aws-eb.zip works for me OK

**Comment by camsaul** [comment]
Oh snap

> Simply enter the following url in the S3 URL textbox:
>
> http://downloads.metabase.com/v0.23.1/metabase-aws-eb.zip

they're right. Not an S3 URL :D

**Comment by camsaul** [comment]
the picture actually shows the correct URL for some reason

**Comment by salsakran** [comment]
wait a second ... is it actually out of date? This doesn't make any sense, as it's been working fine so far. Did something change in E Beanstalk

**Comment by camsaul** [comment]
it's not out of date. It's just not a valid S3 URL

**Comment by camsaul** [comment]
look at the link and compare to the pic in the dox http://www.metabase.com/docs/v0.23.1/operations-guide/running-metabase-on-elastic-beanstalk.html

**Comment by salsakran** [comment]
ahhhh. gotcha.

**Comment by camsaul** [comment]
yeah the tweet was correct in that the link didn't work but a little misleading since it wasn't out of date after all. Updated bug title to reflect that
