### ISSUE TITLE
Public Actions Fail

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#47704]
### Describe the bug

Public actions fail with "An error occurred".

### To Reproduce

1. Set up a simple test table in Postgres
`CREATE TABLE test_table (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50)
);

INSERT INTO test_table (NAME)
VALUES 
    ('Alice'),  
    ('Ivan'),
    ('Judy');`
2. In Metabase create a model on this table
3. Add an action
`UPDATE test_table
SET NAME = {{newName}}
WHERE ID = {{id}};`
4. Test the action to confirm it works
5. Publish the action
6. Navigate to the public link for the action
7. Test the action and see that it fails

### Expected behavior

Public actions should work

### Logs

400 Bad Request response on the post request:

http://localhost:15023/api/public/action/ba5262f7-f0d6-41c1-af03-822837bc5bb1/execute

### Information about your Metabase installation

```JSON
v50.23
```

### Severity

Blocking some users

### Additional context

https://www.loom.com/share/d62b408926e84fcabe2f7daff746c4d3

**Comment by perivamsi** [comment]
@ixipixi can you try opening the link in a normal browser tab, not in incognito mode?

**Comment by ixipixi** [comment]
@perivamsi it still fails

**Comment by ixipixi** [comment]
I did just notice that it still works if you open the public link from a browser where you're already authenticated. Might be a helpful detail for anyone else trying to reproduce this!
