### ISSUE TITLE
Querys buggeadas

### ISSUE THREAD

**Issue by epacheco90** [metabase/metabase#47714]
**Describe the bug**
We have a problem with queries that is still being processed. We cut off the process and they start again but we do not find them in any dashboard. These are: 

SELECT "history"."sales_ticket"."document_type_id" AS "document_type_id" FROM "history"."sales_ticket" GROUP BY "history"."sales_ticket"."document_type_id" ORDER BY "history"."sales_ticket"."document_type_id" ASC LIMIT 1000

SELECT "history"."sales_ticket_details"."unit_of_measure_code" AS "unit_of_measure_code" 
FROM "history"."sales_ticket_details" 
GROUP BY "history"."sales_ticket_details"."unit_of_measure_code" 
ORDER BY "history"."sales_ticket_details"."unit_of_measure_code" 
ASC LIMIT 1000

SELECT "history"."sales_ticket"."loyalty_program_code" AS "loyalty_program_code" 
FROM "history"."sales_ticket" 
GROUP BY "history"."sales_ticket"."loyalty_program_code" 
ORDER BY "history"."sales_ticket"."loyalty_program_code" ASC 
LIMIT 1000

SELECT "history"."sales_ticket"."is_deleted" AS "is_deleted" 
FROM "history"."sales_ticket" 
GROUP BY "history"."sales_ticket"."is_deleted" 
ORDER BY "history"."sales_ticket"."is_deleted" ASC 
LIMIT 1000

**To Reproduce**

**Expected behavior**
We need to find the queries to delete them

**Severity**
It´s a severe issue, is a bug to us, because block the entire database for our customers.

**Comment by paoliniluis** [comment]
Please disable field values (settings-> admin->databases -> advanced settings in your database + disable all linked filter and also set all field to “input box”
