### ISSUE TITLE
Not able to use existing tables and models as starting points for new questions

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#47741]
### Describe the bug

We have a cloud customer that we updated to 1.50.24 and hasn't been able to use existing tables and models as starting points for new questions. We haven't been able to reproduce the issue on our end.

### To Reproduce

Create a new Question as you normally would by clicking on the New button, then click on Tables or Models.
Nothing is available and you encounter the following error making a call to the /api/search/?limit=&models=card endpoint.

<img width="1582" alt="5" src="https://github.com/user-attachments/assets/a5b8768e-8040-40f6-bfe5-d7900ba4afe6">

<br>
<br>

More details about the 500 error
<img width="938" alt="6" src="https://github.com/user-attachments/assets/5bd57f14-0a0d-4f25-95d1-173d5ceb9df7">

<br>
<br>

A call to the http://ncx.metabaseapp.com/api/search endpoint does work and returns a JSON, which I can provide independently from posting in this github issue.

### Expected behavior

For them to be able to use existing questions and models as starting points for new questions.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2024-09-04",
      "tag": "v1.50.24.2",
      "hash": "014582c"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

P1

**Comment by noahmoss** [comment]
@FilmonK Could they send the entire stack trace in the error response?

**Comment by FilmonK** [comment]
> @FilmonK Could they send the entire stack trace in the error response?

@noahmoss Will do. We let them know we can temporarily log into their environment and making sure they're good with that before proceeding.

**Comment by ixipixi** [comment]
@riazjahangir I have an update for you I just shared in your ticket.

**Comment by riazjahangir** [comment]
Our issue is resolved; we had several questions with large (1000+ lines) raw queries. Seems like either this suddenly became a problem after our upgrade to 1.50.24, or else creating a few new small questions finally put us over the edge to make the result from /api/search too large.

Deleting the questions with the largest `dataset_query` values got things back in working order.
