### ISSUE TITLE
Which parts of the frontend business logic should we improve and how?

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#4775]
The interface between React components/containers and business logic needs a lot of improvement in order to be understandable and easy to use. We thought with @salsakran that it's a great idea to collect all quality defects one place, together with ideas of how to improve the situation.

The end goal of all improvements is to have a simple and well-documented business logic layer which is convenient to consume and extend. This would really delight new contributors and speed up frontend development in general. 🌞

Some of stuff will probably involve moving logic from frontend to backend for easier maintenance.

### Work-in-progress summary of quality issues

__General notes__

- Metabase backend has short and concise docstrings for majority of functions. Frontend doesn't have much docstrings at all. We should make establish a routine of documenting functions and enforce it in our code reviews.

__Feature: Dashboard parameters__

Also the backend part of dash params is a little cryptic, but let's focus on frontend now.

- Parameter mapping stuff isn't easy to comprehend. Example: https://github.com/metabase/metabase/blob/3225accb87d24d3d5f3226c1a4f5b3632b2d4bef/frontend/src/metabase/dashboard/selectors.js#L99

- The metabase business logic really needs documentation and use examples, https://github.com/metabase/metabase/blob/3225accb87d24d3d5f3226c1a4f5b3632b2d4bef/frontend/src/metabase/meta/Dashboard.js

**Comment by tlrobinson** [comment]
Some overlap with #927

**Comment by attekei** [comment]
I don't find this issue relevant anymore so closing this. We have done a lot of frontend improvements in June-July and seem to have pretty clear understanding on what to work on next.
