### ISSUE TITLE
Update copy/design

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#47767]
- Add a beta flag to the SDK card
    ![image](https://github.com/user-attachments/assets/dcc3cbdc-1443-4214-9151-845129d47933)
- Add an API key banner in SDk settings page
    ![image](https://github.com/user-attachments/assets/9e1316ae-d794-42aa-81f8-1cec49f9e707)
- Add Try SDK CTA
    ![Screenshot 2024-09-09 at 8 52 05 PM](https://github.com/user-attachments/assets/d9e6c872-39ef-4dd4-8a02-c749e3e03c12)
- Add a doc link
    ![Screenshot 2024-09-09 at 8 52 57 PM](https://github.com/user-attachments/assets/4a14e7e2-43dd-4e08-a8da-7ef2f599aefb)
- Add an upsell banner (non Pro/EE)
    ![image](https://github.com/user-attachments/assets/65bc69ac-d42a-4f12-8036-4dd5cb997929)
- Add version pinning CTA for Pro cloud
    ![image](https://github.com/user-attachments/assets/6b08439e-9904-4810-adb8-42f033dc266e)

**Comment by oisincoveney** [comment]
Closed with https://github.com/metabase/metabase/pull/47891. For some reason I wasn't able to directly link the branch on the sidebar.
