### ISSUE TITLE
Serialization fails for Mongo nested fields

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#47795]
### Describe the bug

Full context [here](https://metaboat.slack.com/archives/C0641E4PB9B/p1725634813914559)

### To Reproduce

@piranha is already aware of this and the below is mainly his research:

So in mongo db you can have nested data:
```
qwe> db.whatever.find()
[
  {
    _id: ObjectId('664f3e4fe27a442f03aace62'),
    level_0: { level_1: { level_2: 'test' } }
  },
  {
    _id: ObjectId('66dffa90f3ee3a31efa72a44'),
    level_0: { level_2: 'a lie' }
  }
]
```

We represent those nested levels as separate fields, which point to their parent id (so they don't create new parent_ids, they just reference them)

The problem here is that we disregard those `parent_ids` during serialization phase, we just don't care
and so if you have a same name for a column on two different levels - there will be errors

### Expected behavior

Serialisation works when there are nested columns in Mongo

### Logs

```
Caused by org.postgresql.util.PSQLException
   ERROR: duplicate key value violates unique constraint "idx_unique_field"
   Detail: Key (name, table_id, unique_field_helper)=(level_2, 60, 468) already
   exists.
```

### Information about your Metabase installation

```JSON
50.24 and master
```

### Severity

Blocking some customer from upgrading to 50 since they depend on a serialization pipeline

**Comment by paoliniluis** [comment]
I would actually escalate this @Tony-metabase

**Comment by Tony-metabase** [comment]
it's on Alexander radar and he will start working on this once he adds a fix to the deadlock problems we are facing
