### ISSUE TITLE
[Epic] Allow to filter by all columns

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#47800]
Product doc https://www.notion.so/metabase/Allow-to-filter-by-all-columns-47f4e5eef7f04e2f9d41e4f140c93596

#### Milestone 1 - deduplicate column group names

Fix existing issues with column group names that become more important if we expose more groups.

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/47802
- [ ] https://github.com/metabase/metabase/issues/47811
```

#### Milestone 2 - QB

Allow filtering on any column in the QB.

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/47817
```

**Comment by JamesPoel** [comment]
Is this in 1.51.1? The change log suggests so but it doesn't seem to be - unless I'm misunderstanding this ticket.
