### ISSUE TITLE
Mobile CSS causing homepage sidebar to render incorrectly

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4782]
It looks like the `.sm-show` that was added for the mobile layout has `display: inherit !important;` causing the sidebar to inherit `flex` instead of `block` from it's parent: https://github.com/metabase/metabase/blob/20ceb23b51082a35424179e32d0ce4d7aa237922/frontend/src/metabase/home/containers/HomepageApp.jsx#L97

![](https://files.slack.com/files-pri/T078VCLCR-F4Z25EN1H/screen_shot_2017-04-13_at_1.55.35_pm.png)

**Comment by salsakran** [comment]
Example in chrome

![screen shot 2017-04-13 at 1 55 35 pm](https://cloud.githubusercontent.com/assets/107439/25024589/58fadd90-2053-11e7-96d5-8ae0a1e4bb55.png)
