### ISSUE TITLE
[Epic] Surface SDK in the share/embed flow

### ISSUE THREAD

**Issue by NevRA** [metabase/metabase#47840]
https://www.figma.com/design/W1TfzdrR8ldzp4vdjP1z36/SDK-Embedding%3A-admin-settings-%2B-embed-flow?node-id=10661-18909&t=UnHxyK1bnFGE3Npy-4

**Comment by npretto** [comment]
Closing as  [47840 - surface sdk in share modal](https://github.com/metabase/metabase/pull/47967) has been merged in the integration branch `sdk-launch-in-core-app`
