### ISSUE TITLE
Display the variable name in a dashboard's filter selector

### ISSUE THREAD

**Issue by stem** [metabase/metabase#4787]
Hi,

I'm using 0.23.1 and I'm creating dashboard with a date based filter.

I would like to be able to filter using relative date (last month / year, etc) or a period (Q1 or between 2016-12-01 and 2017-02-28)

As I understood it, I cannot use the same filter for all the date kind I need, and I cannot use the same question's variable in multiple filters so I created 2 variables based on the same table field and 2 filters, 1 for each variable.

But when I want to assign a filter to a variable, I get the name of the underlying field, which is the same. Because of that, it's tricky to get all the filter on the same variable. In my case, it's not that important, but it could be on certain queries.

I think it would be appropriate to name it with the variable name or variable label.

What's your opinion on this subject ?

PS : Some screenshots for a graphic and better? explanation.

<img width="402" alt="screenshot 2017-04-14 19 27 16" src="https://cloud.githubusercontent.com/assets/2844/25050566/6eb30e96-2148-11e7-8076-23a782a5bdc4.png">
<img width="286" alt="screenshot 2017-04-14 19 27 33" src="https://cloud.githubusercontent.com/assets/2844/25050565/6e98db02-2148-11e7-911e-b47b6a60c398.png">
<img width="357" alt="screenshot 2017-04-14 19 14 51" src="https://cloud.githubusercontent.com/assets/2844/25050536/4ea834f0-2148-11e7-9f9b-b0e1ad7277ca.png">

**Comment by flamber** [comment]
Closing in favor of #12792
