### ISSUE TITLE
Inconsistent bar chart legend

### ISSUE THREAD

**Issue by Pierre-PSUD** [metabase/metabase#47878]
### Describe the bug

I created my bar chart and put a legend. I added this question to a dashboard. Few days after, I changed my legend (ordinate).
From the dahsboard, I continue seeing the old ordinate legend on my graph whereas the good legend is set when I see my question.

It is weird because some others charts updated weel but some others did not.

From dashboard :
![image](https://github.com/user-attachments/assets/f15cb58e-94a2-47f3-b1ac-476e774effce)

From question :
![image](https://github.com/user-attachments/assets/25d1d8f5-ddec-4ebc-8cd1-06e256e398a7)

### Expected behavior

Both legends shall be the same

### Information about your Metabase installation

```JSON
- Windows 10
- Firefox version 115
- Database : postgreSQL
- Metabase version : v1.48.4 (released on 2024-01-29)
- French version
```

### Severity

Annoying...

**Comment by paoliniluis** [comment]
go to the visualization settings on the card on the dashboard and click on "reset to defaults"

**Comment by Pierre-PSUD** [comment]
Thanks Luis !
