### ISSUE TITLE
Custom column that returns a date is not interpreted as a date filter

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#47887]
### Describe the bug

I am creating a custom column that is returning a Date. The UI is also saying that is a date but it's filtering options are only empty and is not empty

### To Reproduce

1. Go to New -> Sample DB -> People -> Add a Custom column ->`case([Name] = "Won", datetimeAdd([Created At], 0, "month"), datetimeAdd([Birth Date], 0, "month"))`

You can access the Question [here](https://stats.metabase.com/question/19582-wrong-filter-option/notebook)

2. Try to filter on this custom column:

<img width="792" alt="image" src="https://github.com/user-attachments/assets/e0724a4e-0b2e-454b-9797-00f0106fd3ff">

The UI clearly knows it's a date but it's not giving the right options

<img width="781" alt="image" src="https://github.com/user-attachments/assets/2ade2b6e-53bf-4e5b-a5b4-cd28a224e42c">

### Expected behavior

I get the usual date filtering

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
Doesn't happen on 50 and only on master (you can check stats)
```

### Severity

Breaking change/regression

**Comment by NevRA** [comment]
@lbrdnk discussed with AlexP, the solution looks ok
