### ISSUE TITLE
Mongo Queries based on Views (Feature Request)

### ISSUE THREAD

**Issue by BenHizak** [metabase/metabase#4789]
I would like to request queries based on saved queries (also called [MongoDB Views](https://docs.mongodb.com/manual/core/views/) ).

Benefits:
1. Give users the best of both worlds (Native Queries and Metabase Query builder). Each tool has it's own strength.
2. Enable future support for MongoDB (if metabase does not support something, it can be implemented at the view level). I am talking about such features as `allowDiskUse: <boolean>` and  `cursor: <document>`.

3. Users will no longer have to tweak mongoDB queries (at present, users have to add double parentheses around operators (this is not supported by MongoDB, hence, this is a new 'query dialect')

4. This would also solve https://github.com/metabase/metabase/issues/4603

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by Serfenia** [comment]
Any news on this proposal? Really want this feature.

**Comment by Serfenia** [comment]
This proposal has 10 up votes, anything planned for this?

**Comment by thedavidprice** [comment]
Any updates on Views support since the update of Monger? Assuming still not working but curious if it's been attempted by anyone yet.

**Comment by samuelbirocchi** [comment]
This feature is working properly, I think we can close this issue.

**Comment by flamber** [comment]
Closing, since [createView](https://docs.mongodb.com/manual/reference/method/db.createView/) works on MongoDB 4.0+ with Metabase (tested 0.41.1)
