### ISSUE TITLE
Problems with windows 10 and google cloud

### ISSUE THREAD

**Issue by BeHiz** [metabase/metabase#4790]
There is a possible related issue in [discourse](http://discourse.metabase.com/t/jetty-going-to-sleep-http-error-500/1388) (may not be a metabase bug)
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your operating system: 
`Windows 10 x64, 
Docker version 17.03.1-ce, build c6d412e`- 
- Your databases: Mongo `3.4` on Google Compute Engine (not relevant since issue occurs at boot)
- Metabase version: `0.23.1`
- Metabase hosting environment: Windows 10 docker `Docker version 17.03.1-ce, build c6d412e`
- Metabase internal database: Configuration DB: `MySQL` hosted on Godaddy

- *Repeatable steps to reproduce the issue*
(I am happy to give my password privately)
```
docker run \
-d \
-e MB_DB_TYPE=mysql \
-e MB_DB_DBNAME=metabase \
-e MB_DB_PORT=<MY_PORT>\
-e MB_DB_USER=metabase_config \
-e MB_DB_PASS=<MY_PASSWORD> \
-e MB_DB_HOST=<MY_HOST> \
-p 3001:3000 \
--name metabase \
metabase/metabase
```

Errors
[errors.txt](https://github.com/metabase/metabase/files/923025/errors.txt)

**Comment by salsakran** [comment]
Your errors indicate something is going wrong with the connection with the mysql application database. 

The connection is being reset after
``` Checking if Database has unrun migrations...```

```
The last packet successfully received from the server was 76,468 milliseconds ago.  
The last packet sent successfully to the server was 12 milliseconds ago.
```
It's possible we're doing something silly, but the odds are *really* high it's something to do with your network setup or godaddy's. In general, we'd recommend running the server as close to the application server as you can.

**Comment by salsakran** [comment]
Given that this is happening in all kinds of situations (as evidenced by the discourse issue), I'm 99% certain this is GD dropping connections for some reason and not something we're doing in a specific query.

**Comment by BeHiz** [comment]
@salsakran looks like you were right. I migrated to Google mySQL and it seems the problem is solved
