### ISSUE TITLE
Casting UNIX to Datetime on a Field Generates Invalid SQL in Several Cases

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#47940]
### Describe the bug

If you have a datetime stored in UNIX format and cast the field to datetime it shows up correctly in the Questions. If you JOIN this to another question it generates invalid SQL:

![wut](https://github.com/user-attachments/assets/0164141a-eb4b-40f7-88c3-e7dbc409490b)

```
ERROR: operator does not exist: timestamp with time zone / integer
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 180
```

This also presents if you bad Questions promoted to models before you applied the CAST. 

### To Reproduce

1. Set up a test table in Postgres with sample data in it:

`CREATE TABLE hits (
    id SERIAL PRIMARY KEY,
    hit_time BIGINT
);
`

`INSERT INTO hits (hit_time) VALUES
(1724693536475),
(1724694536475),
(1724695536475);
`

2. Create a GUI question with this table in Metabase
3. Promote the Question to a Model
4. In Table Metadata, cast the field with "UNIX milliseconds → Datetime"
5. Refresh the model & observe the error

Second path: 
1. Create a GUI question with this table in Metabase (don't promote this one)
2. Start a question in Metabase with another table and then JOIN the Question with the date column in it 
3. Run it
4. Observe the error

### Expected behavior

We should generate valid SQL in these cases

### Information about your Metabase installation

```JSON
v50.25
```

### Severity

Prevents users form leveraging models in some cases

**Comment by camsaul** [comment]
See also https://github.com/metabase/metabase/issues/38994

**Comment by parker-codes** [comment]
I also ran into this issue. My tables were set up to cast from unix timestamps (in seconds). These unix timestamps worked well for a single question, but failed with `ERROR: function to_timestamp(date) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts.` when I would use a 3rd question to join the results of two other questions that exposed those timestamps.

I converted all of the timestamps in the DB to be "proper", and now it works just fine. This makes me think that it was properly casting at one question "deep", but not understanding when to cast or not cast as those questions were composed.

See support ticket 31722 for more info.

**Comment by metamben** [comment]
@ixipixi the two reproduction paths highlight different causes. The one with the model doesn't fail in 0.49.17, the one with the join does (so it's not a regression in 0.50.x). The problem with the model is easier to fix. Would fixing the model reduce the priority of this issue? If yes, I create a PR fixing only that.

**Comment by metamben** [comment]
#49502 should fix the regression.

**Comment by ixipixi** [comment]
@metamben I didn't set the priority on this one. Looks like @ranquild made that change and may have some additional context?
