### ISSUE TITLE
Feature: foreign keys not supported with bigquery?

### ISSUE THREAD

**Issue by kritop** [metabase/metabase#4795]
When i try to add a foreign key in the Admin Panel -> Data Model

i see
<img width="923" alt="screen shot 2017-04-17 at 15 44 10" src="https://cloud.githubusercontent.com/assets/2034466/25090714/24bdf794-2385-11e7-88dc-aeb796328cac.png">

is that due missing support for foreign keys with bigquery? or am i doing something wrong?

**Comment by salsakran** [comment]
Do you see any fields we've identified as "Primary Key" in your data model? We only let you point an FK to another table's primary key. It's possible we're not correctly identifying your PKs in BigQuery.

Can you share the schema for that table and the table you're trying to links to?

**Comment by VikramTiwari** [comment]
@salsakran Maybe totally unrelated but my observation:

One of the features of BQ is that you do not need primary keys and other similar setups to make query execution faster. Most of the times BQ is used for analytics data warehousing where creating a unique key is not required.

But even in those cases, one might want to query on two tables and using joins they can do so. This is currently possible in SQL query builder. To make it work in the GUI query builder, the requirement becomes that tables need to share a column which contains a unique value which can be used for FK references.

This is one of the limits I have encountered while using Metabase. It works well for me cause I can write SQL queries, but isn't the case for others.

Not sure how one would approach about solving it but it could be as simple as providing the ability to define FK references in BQ based table without doing any actual identification. This will allow me to create a map/join for different columns on different tables and now it's up to me to make sure that my data is actually joinable on those set of columns.

**Comment by kritop** [comment]
@salsakran its like @VikramTiwari describes it. we use bigquery as our dwh and don't define any keys and want to enable people who don't write SQL to use do queries, in our case its crucial since we rely on joins using a fact -> dimension model.
as @VikramTiwari described it would be great to manually assign FK without detection, hence this is a admin task i don't see any issue any users messing them up

@VikramTiwari thanks for the explanation thats exactly our use case.

**Comment by kritop** [comment]
@salsakran i tried to setup a manual foreign key relation to another table and ended up with this error:

http://look.neta.io/k8Ai

also isn't it clearer to show the joined table instead of the key "order number" ?

**Comment by salsakran** [comment]
is that the case for aggregations as well?

**Comment by HelenMertes** [comment]
Yes, it is the same for aggregations, too

**Comment by MiBaDK** [comment]
The error @kritop is getting would be this issue I believe: https://github.com/metabase/metabase/issues/4218

**Comment by flamber** [comment]
Closing, since it has been possible to make arbitrary joins in [Notebook editor](https://www.metabase.com/docs/latest/users-guide/custom-questions.html) (0.33) without any Entity/Foreign Key definitions.
