### ISSUE TITLE
varieties in maps or how to implement in metabase

### ISSUE THREAD

**Issue by gustavosobol** [metabase/metabase#47964]
Hi, I don't know if I should go this way, but I need to implement more varieties of maps in the metabase...
like heat maps, or that the pins are variable in color, in size according to the variables that are adjusted...
I apologize if it already exists but I couldn't find documentation to implement this...

Thank you very much in advance

**Comment by paoliniluis** [comment]
@gustavosobol we know that. Please add your upvote on the corresponding map that you want in the issue tracker
