### ISSUE TITLE
Option to easily include All Personal Collections in Serialization Export

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#47976]
**Is your feature request related to a problem? Please describe.**
It can be frustrating when you need to export personal collections via the serialization API, as there is no way to export all personal collections at once. Currently, you have to manually identify and export them one by one, which is time-consuming and error-prone, especially in environments with many users.

Additionally, some customers build questions in public collections that depend on models located in personal collections. When the models in personal collections don’t get exported, the import fails due to missing dependencies. The error messaging only provides an entity ID, which makes it difficult and cumbersome to trace where the missing model is coming from.

**Describe the solution you'd like**
I would like an option in the serialization API to allow the export of all personal collections in a single request. This would ensure that all dependent models and collections are included in exports, simplifying migrations and avoiding import failures due to missing dependencies.

**Describe alternatives you've considered**
The alternative is to manually list and export personal collections by ID, but this requires additional effort and custom scripting, especially in large environments. Manually identifying and exporting the dependencies for public questions that rely on personal collections is also cumbersome and prone to error due to limited error messaging.

**How important is this feature to you?**
This feature is important because it would streamline backup, migration, and dependency management processes for instances with many users, ensuring personal collections and models are not overlooked and aid in prevention of import errors.

**Additional context**
Personal collections contain important user data and dependencies for public collections. Having an easy way to include them in exports would improve administrative efficiency and reduce the risk of missing critical data during migrations or backups.

**Comment by avaitla** [comment]
We hit this issue and it is a significant blocker in versioning our metabase as we have 100s of users, some of which may accidentally put a personal question in a public collection and this crashes the serialization api.
