### ISSUE TITLE
CSP issue in chrome.

### ISSUE THREAD

**Issue by ashoksahoo** [metabase/metabase#48018]
### Describe the bug

The page goes blank, and we can see CSP errors in chrome console.
Version 128.0.6613.138 (Official Build) (arm64)
Works fine in Safari.
You're on version v0.50.26
Built on 2024-09-16

### To Reproduce

<img width="1726" alt="Screenshot 2024-09-19 at 1 22 48 PM" src="https://github.com/user-attachments/assets/5ca5c722-1915-4131-a281-0593d9bc3875">

### Expected behavior

Page should load normally

### Logs

GET https://metabase.superfone.co.in/app/dist/runtime.5f1e4129a9a1d5c3575e.js net::ERR_ABORTED 404 (Not Found)Understand this error
metabase.superfone.co.in/:1 Refused to execute script from 'https://metabase.superfone.co.in/app/dist/runtime.5f1e4129a9a1d5c3575e.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.Understand this error
metabase.superfone.co.in/:42 
        
        
       GET https://metabase.superfone.co.in/app/dist/vendor-styles.c6e62ca30b8107c42e2a.js net::ERR_ABORTED 404 (Not Found)Understand this error
metabase.superfone.co.in/:1 Refused to execute script from 'https://metabase.superfone.co.in/app/dist/vendor-styles.c6e62ca30b8107c42e2a.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.Understand this error
metabase.superfone.co.in/:42 
        
        
       GET https://metabase.superfone.co.in/app/dist/styles.32c2bf2b0dfceff31e0e.js net::ERR_ABORTED 404 (Not Found)Understand this error
metabase.superfone.co.in/:1 Refused to execute script from 'https://metabase.superfone.co.in/app/dist/styles.32c2bf2b0dfceff31e0e.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.Understand this error
metabase.superfone.co.in/:42 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' https://maps.google.com https://accounts.google.com https://www.google-analytics.com   'sha256-9uFLu5CG8mWlvx0LK6lgendCxUX57TuWk3wkgZpBeWU=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE=' 'sha256-3N2Z+Nu++/yNMVHIl863JigVmt2Nr9gt2doEMJT2Wzk='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
Understand this error
metabase.superfone.co.in/:42 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' https://maps.google.com https://accounts.google.com https://www.google-analytics.com   'sha256-9uFLu5CG8mWlvx0LK6lgendCxUX57TuWk3wkgZpBeWU=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE=' 'sha256-3N2Z+Nu++/yNMVHIl863JigVmt2Nr9gt2doEMJT2Wzk='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
Understand this error
metabase.superfone.co.in/:42 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' https://maps.google.com https://accounts.google.com https://www.google-analytics.com   'sha256-9uFLu5CG8mWlvx0LK6lgendCxUX57TuWk3wkgZpBeWU=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE=' 'sha256-3N2Z+Nu++/yNMVHIl863JigVmt2Nr9gt2doEMJT2Wzk='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
Understand this error
metabase.superfone.co.in/:1 

### Information about your Metabase installation

```JSON
Version 128.0.6613.138 (Official Build) (arm64)
Works fine in Safari.
You're on version v0.50.26
Built on 2024-09-16
metabase
```

### Severity

Blocking in Chrome, everyone is forced to use something else.

### Additional context

Only happens in chrome, but does not happen in safari.
Used to be fine, before upgrade.

**Comment by uladzimirdev** [comment]
Can it be a mime type error, which means file is not located correctly? Could you please also clear browser cache and try again?
