### ISSUE TITLE
Crash when discarding new metric

### ISSUE THREAD

**Issue by mngr** [metabase/metabase#48024]
### Describe the bug

When you start to create a metric and then decide to discard it, app crashes

### To Reproduce

1. Go to + New metric
2. Choose Sample database, Orders table
3. Click Cancel on top
4. Click Discard changes
5. App crashes
[metabase-diagnostic-info-2024-09-19T15_53_51.071Z.json](https://github.com/user-attachments/files/17062386/metabase-diagnostic-info-2024-09-19T15_53_51.071Z.json)

### Information about your Metabase installation

```JSON
06d1ba2ae111e66253209c01c244d6379acfc6dcb1911fa9ab6012cec9ce52e5

775d9c9
```

### Severity

Breaks the app until refresh

**Comment by iethree** [comment]
```
TypeError: Cannot read properties of undefined (reading 'card')
    at createRawSeries (index.ts:162:1)

navigation.js:155 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'query')
```
