### ISSUE TITLE
Is Empty / Is Not Empty filters break on Postgres enums

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#48022]
### Describe the bug

The Is Empty / Is Not Empty filters generate incorrect SQL for Postgres enums.

### To Reproduce

1. On Postgres, create a table with an enum column.
2. Create a GUI question
3. Add a simple 'is empty' or 'not empty' filter for the enum column
<img width="333" alt="image" src="https://github.com/user-attachments/assets/a2ba7baa-bf2b-4d26-83da-f604d12c7eca">

4. Visualize, and see the error: `ERROR: invalid input value for enum mood: ""`

Generated SQL

```
SELECT
  "public"."person"."id" AS "id",
  "public"."person"."name" AS "name",
  "public"."person"."current_mood" AS "current_mood",
  "public"."person"."description" AS "description"
FROM
  "public"."person"
WHERE
  ("public"."person"."current_mood" IS NULL)
    OR (
    "public"."person"."current_mood" = CAST('' AS "mood")
  )
LIMIT
  1048575
```

### Expected behavior

It should work.

### Information about your Metabase installation

```JSON
1.50.25
```

### Severity

Found it while troubleshooting something else

### Additional context

Custom expressions `isnull()` and `notnull()` can work as a workaround.

**Comment by bshepherdson** [comment]
I don't know if we capture metadata about Postgres strings vs. enums very clearly. It feels like it should be `:type/Category` but that's a lot broader than formal enums.

We do have the `db_type` of the column, so at least at the Postgres driver level we can avoid generating the empty string branch for these expressions.
