### ISSUE TITLE
Float numbers get rounded automatically in charts

### ISSUE THREAD

**Issue by amywtlin** [metabase/metabase#4803]
Did a little searching but didn't find the issue I encountered to be reported or in PRs yet (to my surprise); if there's a duplicate, please point me over - I'll remove this one. Thanks!

- Your browser and the version: Chrome Version 57.0.2987.133 
- Your operating system: OS X 10
- Your databases: Postgres 
- Metabase version: 0.22.2
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*: simply do a query with `select 12.011, 12.019`:
![screen shot 2017-04-18 at 4 13 33 pm](https://cloud.githubusercontent.com/assets/11730007/25120777/fd506520-2451-11e7-9586-17b23f45e618.png)

With the display, you can't really see if the number is 12.011 or 12.010; I do understand two decimal places should be sufficient for most of the use cases, however it'd be great if there's a way to switch this on or off somehow.

Thank you!

**Comment by nishalspace** [comment]
No worries, I got my workaround.

format(loc.lat,6) lat, format(loc.lng, 6) lng 

This is displaying the digits of float numbers up to 6 digits.

I hope this helps.

**Comment by cboecking** [comment]
Where are you placing the "format(loc.lat,6)" to get the desired result?

**Comment by flamber** [comment]
This was fixed in 0.31 by all the formatting features add, so show more decimals or none at all.
On 0.31.2 it looks like this:
![image](https://user-images.githubusercontent.com/1447303/53273997-4f603480-36bb-11e9-930a-4545a481ceea.png)

**Comment by mazameli** [comment]
Closing as we fixed this with column formatting settings.
