### ISSUE TITLE
Models not showing values on search box

### ISSUE THREAD

**Issue by fer-batista** [metabase/metabase#48048]
### Describe the bug

I`ve create a model and use CASE to change some values:
  CASE
    WHEN auth_ongoing = 0 THEN 'no'
    WHEN auth_ongoing = 1 THEN 'yes'
  END AS auth_status
  But, when I put the filter in query builder, the options 'no' and 'yes' do not appear.
  
  
![image](https://github.com/user-attachments/assets/3d410b41-f437-4e0e-b751-e6cd9f6f7fa7)
![image](https://github.com/user-attachments/assets/5e9b283e-c61d-4e37-87a4-4727f956a87a)

The option for custom mapping for this field not appear. That`s only 2 options to mapping.
![image](https://github.com/user-attachments/assets/82e37316-cd74-4f05-bdee-34fdb12b4c36)

### To Reproduce

1. Go to 'New'
2. Click on 'Model'
3. Create a SQL question
4. Use case to change values
5. Save the Model
6. Create a Question
7. Try to filter the changed field
8. Noting appears to select, requesting to put a text

### Expected behavior

Show the value from the field to selection.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-09-16",
      "tag": "v1.50.26",
      "hash": "5a65f46"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.1.90+",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

P1

**Comment by luizarakaki** [comment]
Unfortunately, this isn't how this works.

If you create a custom column (in native SQL or visual editor custom column) and want to show a dropdown with a list of values, you need to create a custom list of values at the dashboard level:
https://www.metabase.com/docs/latest/dashboards/filters#change-a-filters-selectable-values

Create the question as you want. Add the question to a dashboard, create a dashboard filter and configure which values are available in the dropdown.
