### ISSUE TITLE
Not renamed fields in a same table join inherit the renamed name in exports

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#48046]
### Describe the bug

It is very common to do the same table join. And if you export, names of the columns aren't not how they are supposed to be called, and the users might get confused. 

### To Reproduce

1. Create a GUI question Orders and join it to Orders. Same ID in the join.
2. Rename ID from the first table in the join to "Test ID"
3. Save and export to CSV
4. See that the column that should be named Orders ID is now called Test ID

Viz setting:
<img width="265" alt="Screenshot 2024-09-20 at 12 05 21 PM" src="https://github.com/user-attachments/assets/92d29599-9c17-4f04-8b6c-ea2915400194">

CSV export:
<img width="721" alt="Screenshot 2024-09-20 at 12 06 01 PM" src="https://github.com/user-attachments/assets/2ee03a99-8fd9-43a9-8792-5e23da6cae28">

### Expected behavior

Not-renamed column should be named as it's originally set up to in the viz setting

### Information about your Metabase installation

```JSON
-50.x
```

### Severity

P1

**Comment by mngr** [comment]
https://metaboat.slack.com/archives/C052ZBWRG3W/p1726852641223079
Doesn't reproduce in master, but needs to be backported to 50 and 49?
