### ISSUE TITLE
Developers Guide

### ISSUE THREAD

**Issue by oyosc** [metabase/metabase#4804]
hi, i want to ask you for some thing,when i saw the Developers Guide, in the  Build Metabase, when i use sudo ./bin/build,  it occurs sudo: ./bin/build：can't find the command;
the path is metabase, and os is ubuntu 16

so what's the error?

**Comment by camsaul** [comment]
does it say which command it can't find? Did you make sure to install the prereqs (Java, Node, Yarn, and Leiningen)?
