### ISSUE TITLE
subscribe send email unrecognized code

### ISSUE THREAD

**Issue by wangfpp** [metabase/metabase#48050]
### Describe the bug

![image](https://github.com/user-attachments/assets/32ffb818-21bb-4069-88fa-ca150d1e53ee)

### To Reproduce

email subscribe send image 中文 乱码

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.9+8-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "17.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.9+8-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.0",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-05-29",
      "tag": "v0.48.0-SNAPSHOT",
      "branch": "master",
      "hash": "64e3895"
    },
    "settings": {
      "report-timezone": "Hongkong"
    }
  }
}
```

### Severity

p0

**Comment by wangfpp** [comment]
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.84-10.2.al8.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.37-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-29",
      "tag": "v0.48.0-SNAPSHOT",
      "branch": "master",
      "hash": "64e3895"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by paoliniluis** [comment]
Upgrade your Metabase and install the fonts you need

**Comment by wangfpp** [comment]
@paoliniluis I copied the font file in Docker, but the png sent in the email is still garbled
`COPY ./fonts/PingFang.tff /usr/share/fonts/`
