### ISSUE TITLE
ERROR: unsupported startup parameter: options in Postgres additional JDBC connection

### ISSUE THREAD

**Issue by RomantsovArtur** [metabase/metabase#48068]
### Describe the bug

I'm setting the Postgres connection to the backend database and trying to specify the Additional JDBC connection string options. If I put the value from the example: https://www.metabase.com/docs/latest/databases/connections/postgresql#additional-jdbc-connection-string-options

I'm getting ERROR: unsupported startup parameter: options

### To Reproduce

1. Go to 'Database Setting'
2. Input the example: options=-c%20key=value in Additional JDBC connection string options
3. Press save
4. See error - ERROR: unsupported startup parameter: options

### Expected behavior

Metabase should allow to specify options to Postgres connections.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.1.100+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "starburst"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-07-31",
      "tag": "v0.49.22",
      "hash": "04c8190"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking the setting of statement_timeout, affecting the performance of backend DBs

**Comment by piranha** [comment]
Are you using pgbouncer by any chance? Quick googling suggests this could be a problem (I'm unable to reproduce this locally).

**Comment by RomantsovArtur** [comment]
Yes, we're connected to the DBs via PGbouncer. You mean the error comes from it and not from the MB side?

**Comment by piranha** [comment]
Oh, it for sure is not coming from Metabase. :)
