### ISSUE TITLE
Permission Changes not saved

### ISSUE THREAD

**Issue by AdamLandis** [metabase/metabase#4807]
Somewhat similar to [#4000]([https://github.com/metabase/metabase/issues/4000]) except I can't seem to save any permission changes. Running v 23.1 - can't seem to make any permission changes to the current schema. Adding a new database automatically enables All Users full access and this overrides any limitations set on groups.

When a change is made, the save box appears, click "Save Changes" the Save Permissions, are you sure dialogue comes up > click Yes - the Save Changes button remains, the permissions _seem_ to have changed a page refresh shows that indeed they are not.

Navigating away from the Permissions tab after saving prompts "you have unsaved changes" prompt.

Chrome - 57.0.2987.133
And Internet Explorer - 11.0.96
Windows 8.1
MySQL
Elastic Beanstalk
------

-------

**Comment by attekei** [comment]
Thank you for the bug report @AdamLandis! Could you check out what kind of server error and related stack trace you see after clicking "Save Changes"? You can easily access the server logs from the top-right navigation of Metabase:

![screen shot 2017-04-24 at 15 31 51](https://cloud.githubusercontent.com/assets/6034928/25361480/2ca9da58-2903-11e7-9ed2-7f6de56fba41.png)

**Comment by attekei** [comment]
I was able to reproduce a similar saving error but the db I was using is Redshift instead of MySQL. In my case I'm trying to change a group access from No Access (as in the screenshot) to Unlimited access:
![screen shot 2017-04-24 at 15 38 23](https://cloud.githubusercontent.com/assets/6034928/25361611/1de3fb06-2904-11e7-8690-65c54b313b1c.png)

When trying to save the permission changes, it fails and the following error appears to the server log:
```
04-24 15:36:29 WARN models.permissions :: Invalid DB permissions: if you have readonly native query access, you must also have data access.
04-24 15:36:29 ERROR metabase.middleware :: PUT /api/permissions/graph 500 (1 ms) (0 DB calls)
{:type :schema.core/error,
 :schema
 [{:schema
   {:revision Int,
    :groups
    {(constrained Int "Integer greater than zero")
     {(constrained Int "Integer greater than zero")
      (constrained
       {(optional-key :native) (enum :read :write :none),
        (optional-key :schemas) (cond-pre (enum :all :none) {Str (cond-pre (enum :all :none) {(constrained Int "Integer greater than zero") (enum :all :none)})})}
       "DB permissions with a valid combination of values for :native and :schemas")}}},
   :optional? false,
   :name new-graph}],
 :value
 [{:revision 36,
   :groups
   {1 {1 {:native :none, :schemas :none}, 2 {:native :none, :schemas :none}, 4 {:native :write, :schemas :all}},
    2 {1 {:native :write, :schemas :all}, 2 {:native :write, :schemas :all}, 4 {:native :write, :schemas :all}},
    3 {1 {:native :read, :schemas :all}, 2 {:native :write, :schemas :all}, 4 {:native :write, :schemas :all}},
    4 {1 {:native :read, :schemas :none}, 2 {:native :none, :schemas :all}, 4 {:native :read, :schemas :all}}}}],
 :error [(named {:groups {4 {1 (not ("DB permissions with a valid combination of values for :native and :schemas" a-clojure.lang.PersistentArrayMap))}}} new-graph)],
 :message
 "Input to update-graph! does not match schema: \n\n\t   [(named {:groups {4 {1 (not (\"DB permissions with a valid combination of values for :native and :schemas\" a-clojure.lang.PersistentArrayMap))}}} new-graph)]  \n\n",
 :stacktrace
 ["models.permissions$eval23937$update_graph_BANG___23946.invoke(permissions.clj:474)"
  "api.permissions$fn__44368$fn__44370.invoke(permissions.clj:72)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
  "api.permissions$fn__44368.invokeStatic(permissions.clj:60)"
  "api.permissions$fn__44368.invoke(permissions.clj:60)"
  "middleware$enforce_authentication$fn__40490.invoke(middleware.clj:118)"
  "api.routes$fn__45341.invokeStatic(routes.clj:66)"
  "api.routes$fn__45341.invoke(routes.clj:66)"
  "routes$fn__45401$fn__45402.doInvoke(routes.clj:59)"
  "routes$fn__45401.invokeStatic(routes.clj:55)"
  "routes$fn__45401.invoke(routes.clj:55)"
  "middleware$log_api_call$fn__40605$fn__40607.invoke(middleware.clj:327)"
  "middleware$log_api_call$fn__40605.invoke(middleware.clj:326)"
  "middleware$add_security_headers$fn__40539.invoke(middleware.clj:241)"
  "middleware$bind_current_user$fn__40494.invoke(middleware.clj:138)"
  "middleware$maybe_set_site_url$fn__40543.invoke(middleware.clj:264)"]}
```

Any insight @camsaul what might be causing this? This happened immediately after linking the Redshift database to my Metabase installation (I didn't do other other permission changes in-between).

**Comment by camsaul** [comment]
It sounds like something is trying to save an invalid permissions combination? That's an API validation error:

> Invalid DB permissions: if you have readonly native query access, you must also have data access.

Check the API request body. This sounds like the same issue as #4280

**Comment by attekei** [comment]
Ok, will try to figure out the root cause!

**Comment by attekei** [comment]
Actually the error is always triggered if you have followed the steps described in #4273 and try to change some other permissions after that.

Let's move the conversation to #4280 because these seem very, very similar.
