### ISSUE TITLE
Multiple measures in a query; column alias SUM and SUM2; unable to sort

### ISSUE THREAD

**Issue by wrjohnston** [metabase/metabase#4810]
Just installed metabase (windows 7, using firefox).

When I do a new question, filter on one column, SUM() two columns, and group by an additional column.  Problem I'm running into is that the two SUM measures get alias in the actual SQL as SUM and SUM.   On the visualizations,  it shows up as 'Sum' and 'Sum 2'.   It cases SQL errors when sorting as well, since ORDER BY SUM is ambiguous.

This seems like I must be missing something, but can't seem to find how to 'resolve' this issue; so I'm wondering if it's a bug.  (I'm also getting some strange behavior when doing custom formulas, I'll research that more).

**Screenshot showing behavior described above**
![image](https://cloud.githubusercontent.com/assets/27742894/25152681/d4383a4a-2457-11e7-983f-99fa13b2cff7.png)

**Screenshot showing ORDER BY SUM error:**
![image](https://cloud.githubusercontent.com/assets/27742894/25152917/a4fb41ae-2458-11e7-95b6-3079dbfe8af2.png)

Thanks!
William

SQL generated is as follows:

SELECT sum("perks"."trans_activity"."post_discount_price") AS "sum", sum("perks"."trans_activity"."quantity") AS "sum", "perks"."trans_activity"."trans_hour" AS "trans_hour"
FROM "perks"."trans_activity"
WHERE CAST("perks"."trans_activity"."trans_date" AS date) BETWEEN CAST((getdate() + INTERVAL '-2 day') AS date)
   AND CAST((getdate() + INTERVAL '-1 day') AS date)
GROUP BY "perks"."trans_activity"."trans_hour"
ORDER BY "perks"."trans_activity"."trans_hour" ASC

Database is Amazon Redshift, OS is Windows 7, browser is Firefox 52.  
Metabase internal DB is H2.
Metabase version is 0.23.1

**Comment by wrjohnston** [comment]
As a test, I installed Metabase on a different machine (still Win7) and tested using the sample data.  Same issue happens, multiple aggregations in a single query result in unlabelled results.

**Comment by salsakran** [comment]
closing in favor of #6042 where we've discussed a few solutions

**Comment by yanivgold** [comment]
@salsakran, is there a fix planned to be out soon for this one? it's quite an important feature.
Greatest solution for this as I see it is having the ability to choose the naming given to a measure as the sort by option, and have that calc as the order by statement

**Comment by Ipfs44** [comment]
Finally understood



https://angular-devkitvanishing.github.io/TXItSwebh31EQKkSh2OaMfG80HyvC_dprAz82e9L/
