### ISSUE TITLE
when adding google analytics as source, it's not clear that I have to enable the API

### ISSUE THREAD

**Issue by lucacioria** [metabase/metabase#4812]
I spent abount half an hour trying to figure out why I got this strange `closure lang something..` error when adding the source, and the reason was simple: I needed to enable the google analytics API in the google api dashboard.

Also, after understanding that, I got another error.. I was using the tracking id (UA-....) instead of the account id (the tracking id is much more often used when dealing with google analytics)

While this seems obvious now, I would suggest to put small hints to guide users that are not experts in Google APIs, in line with the exceptional onboarding experience of metabase.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by c990802** [comment]
Agree 👍

**Comment by davidfurlong** [comment]
Where on earth is my google analytics account id?

**Comment by tiwariayush** [comment]
Also, for the Google Analytics Account ID:

It is in View Settings => View ID.

Please add this also in documentation
