### ISSUE TITLE
Upload CSV containing Cyrillic words with spaces and special characters fail to render

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#48135]
### Describe the bug

Upload CSV containing Cyrillic words with spaces and special characters fail to render.

### To Reproduce

1. Go to Upload CSV and upload the following CSV [hello.csv](https://github.com/user-attachments/files/17147106/hello.csv) ... You will notice 2 columns having a space and a special character respectively

<img width="409" alt="image" src="https://github.com/user-attachments/assets/73f42cef-58f0-4526-b120-7ffeb5c8823d">

2. You will notice that once you upload the csv you get a strange looking column for the two of them:

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/db69b40e-78ea-4897-95f5-4bb2c298fc26">

### Expected behavior

The proper name gets reflected in the Upload CSV

### Logs

```
{:database 26,
 :type :native,
 :native
 {:query
  "CREATE TABLE \"uploads\".\"hello_20240926110149\" (\"_mb_row_id\" BIGSERIAL, \"id\" BOOLEAN, \"%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80\" BOOLEAN, \"%D0%B0%D0%B4%D1%80%D0%B5%D1%81\" BOOLEAN, \"unnamed_column\" BOOLEAN, \"%D0%B4%D0%B0%D1%82%D0%B0%D0%B2_%D1%8B%D0%B5%D0%B7%D0%B4%D0%B0\" BOOLEAN, \"%D0%BF%D0%BE%D1%87%D0%B8%D0%BD%D0%B8%D0%BB%D0%B8_\" BOOLEAN, PRIMARY KEY(\"_mb_row_id\"))"}}

[1572d83d-bb19-4bae-9ce7-432773e62486] 2024-09-26T13:01:49+02:00 DEBUG metabase.query-processor.writeback Executing query

{:database 26,
 :type :native,
 :native
 {:query
  "CREATE TABLE \"uploads\".\"hello_20240926110149\" (\"_mb_row_id\" BIGSERIAL, \"id\" BOOLEAN, \"%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80\" BOOLEAN, \"%D0%B0%D0%B4%D1%80%D0%B5%D1%81\" BOOLEAN, \"unnamed_column\" BOOLEAN, \"%D0%B4%D0%B0%D1%82%D0%B0%D0%B2_%D1%8B%D0%B5%D0%B7%D0%B4%D0%B0\" BOOLEAN, \"%D0%BF%D0%BE%D1%87%D0%B8%D0%BD%D0%B8%D0%BB%D0%B8_\" BOOLEAN, PRIMARY KEY(\"_mb_row_id\"))"}}
```

### Information about your Metabase installation

```JSON
Tested both on 50 and stats
```

### Severity

It blocks cyrillic users from uploading files and forces them to update the file each time

**Comment by crisptrutski** [comment]
The strange looking names are the underlying munged column names we use for the database, which for better or worse is URL encoding. We can't change this format without breaking append to models with even just a space in a column name.

The way this is meant to work is that we automatically configure a display name for the column. Its strange that this is only happening for some of the columns, will dig into it.

**Comment by crisptrutski** [comment]
While we're waiting for the fix to get released, another workaround is to update the display name on the table in Metabase.

**Comment by Tony-metabase** [comment]
Will that break subsequent uploads to the same model? Right now the workaround I am suggesting is to remove spaces and special characters where possible

**Comment by crisptrutski** [comment]
No, changing the display name is totally safe
