### ISSUE TITLE
Investigate occasional subscriptions failures

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#48141]
**Context**

[Example failure](https://metaboat.slack.com/archives/C064QMXEV9N/p1727352120474199)

Sometimes dashboard subscriptions fail as in the example above. A manual attempt to send the same dashboard worked fine.
From the failed subscription we can see that tables and scalars that were rendered by clojure code did not fail, only js-based subscriptions failed which signals there can be an issue with out usage of GraalJS.

**Comment by qnkhuat** [comment]
see this [thread](https://metaboat.slack.com/archives/C064QMXEV9N/p1727361040757189?thread_ts=1727353490.018049&cid=C064QMXEV9N) for why it happened on our stats.
