### ISSUE TITLE
Remove deprecated `MB_API_KEY` used in notify endpoint

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#48210]
**Context**
We shipped API keys on v49. They should replace this feature.
[Context](https://metaboat.slack.com/archives/C01LQQ2UW03/p1727471920876049)

**Comment by johnswanson** [comment]
@luizarakaki one issue is that you can't currently create an API key programatically. I think we might need to build a solution for that before we can totally remove `MB_API_KEY`, because people might be depending on the ability to set an API key when launching Metabase.

**Comment by luizarakaki** [comment]
Given the scope of this API key, I'm not too concerned about this. I'd be more concerned if it was an endpoint required for instance setup like permissions or settings.

Fwiw I think we should have a way to generate API keys using the CLI or config.yml, but I wouldn't tie these things.
