### ISSUE TITLE
Navbar background distortion

### ISSUE THREAD

**Issue by calleo** [metabase/metabase#4823]
Hi,

I am using Chrom Version 57.0.2987.133 (64-bit) on MacOS 10.12.4 (Sierra). Just deployed Metabase 0.23.1 to Heroku.

However, the navbar background looks really wierd, especielly when switching back and forth between tabs. Some examples:

![screen shot 2017-04-20 at 08 55 45](https://cloud.githubusercontent.com/assets/316289/25217605/d990293e-25a7-11e7-8e3b-55d3817dff30.png)
![screen shot 2017-04-20 at 08 55 42](https://cloud.githubusercontent.com/assets/316289/25217606/dad1896e-25a7-11e7-8a7c-90f98df09754.png)
![screen shot 2017-04-20 at 08 54 35](https://cloud.githubusercontent.com/assets/316289/25217609/dca92ec2-25a7-11e7-9b5e-2067eac80bc4.png)
![screen shot 2017-04-20 at 08 54 21](https://cloud.githubusercontent.com/assets/316289/25217611/de661874-25a7-11e7-9f0f-394772a7a802.png)

I clicked around in Safari, and there it seems to be working fine.

**Comment by calleo** [comment]
Updated Chrome to Version 58.0.3029.81 (64-bit) but still have the same issue.

**Comment by anshulk** [comment]
Same happens with me too. Chrome Version 57.0.2987.133 (64-bit) on MacOS 10.12.4 (Sierra)

**Comment by anshulk** [comment]
Any idea why this might be happening, I might be able to work on it.

**Comment by calleo** [comment]
Absolutely no idea why this is happening 😄

**Comment by mazameli** [comment]
You found our secret Space Invaders game inside the navbar! ;) But seriously, this is weird. Does this happen in Safari or other browsers? Does it happen in an Incognito window in Chrome? Have you tried restarting Chrome? @kdoh might have some ideas why this might be happening.

**Comment by kdoh** [comment]
Hrm. Something goofy must be going on with the background image. I haven't been able to reproduce this myself yet but I'll poke at it and see if I can think about why this would happen.

**Comment by VikramTiwari** [comment]
Have been looking at it for some time now. Always thought that something was either wrong with my laptop or I was capping my RAM, hence improper rendering. If it helps: `Chrome: 57.0.2987.133 (64-bit)`

**Comment by kdoh** [comment]
Will be fixed by #4850
