### ISSUE TITLE
UX Suggestions - Sidebar

### ISSUE THREAD

**Issue by manjeshpv** [metabase/metabase#4824]
As we using SpagoBI & Other Tools,

I seen fastest adoption to the kibana(lack of user login) compared to all other tools,

Personally Myself and all others in organization feeling comfortable with phpMyAdmin over Metabase for playing with queries.

I noticed some patterns that phpMyAdmin and Kibana Helps,

Kibana: 
*. Sidebar Helps to Choose Index(Database)
*. First Select Visualization Type, Then Query on header, Filters and Visualization options in sidebar

PhpMyAdmin: 
*. Sidebar Helps to Choose Database(Same in Kibana Discover Tab)
*. First Select Database and Table and Start Query

Both take us directly to workspace. So clicks will be less.

Some of the simple changes I suggest:
*. Minimal Header (max-height:50) - fb:42px phpMyAdmin:32px kibana:45px
*. Sidebar for Query Writing & Visualization Options in New Question for Resolution greater than ~1000px
*. Duration/Time Series( Absolute | Relative | Quick ) selection like Kibana (Which greatly enhances usability)

![image](https://cloud.githubusercontent.com/assets/1999957/25219356/db1b3ee6-25cb-11e7-8f6b-914d38a3c29f.png)

![image](https://cloud.githubusercontent.com/assets/1999957/25218898/2481541e-25ca-11e7-8496-deef610d14b4.png)

**Comment by flamber** [comment]
A lot has changed in the UI with 0.33. Closing in favor of #10237/#11183/#6583
