### ISSUE TITLE
Support for SQLite views

### ISSUE THREAD

**Issue by bmcbride** [metabase/metabase#4826]
- Your browser and the version: Chrome 57.0.2987.133 (64-bit)
- Your operating system: OS X 10.11.6
- Your databases: SQLite
- Metabase version: 0.23.1.0
- Metabase hosting environment: Mac app
- Metabase internal database: H2 (default)

Metabase doesn't seem to recognize SQLite views. Based on [this thread](http://discourse.metabase.com/t/ask-questions-based-on-a-view-and-not-a-table/520/7), I'm assuming this is a bug. Anything I can do to help troubleshoot, just let me know!

**Comment by atpage** [comment]
This is still an issue for me in 0.24.1.  It's a significant problem, since one of the workarounds for lack of JOIN support in Metabase is to create some views with the JOINs already done.

**Comment by starhel** [comment]
If you need sqlite views to work, you need to compile Metabase with sqlite-jdbc 3.20.0.

**Comment by camsaul** [comment]
@starhel It seems like every time we try to use a newer version of the SQLite driver it ends up breaking things for people. See #3753. I'd like to update our driver so this works, but making sure we don't break SQLite support for people entirely is even more important. So thanks for your patience as we wait to make sure upstream issues are fixed before updating to a newer version with support for views

**Comment by flamber** [comment]
Wasn't this fixed in Metabase 0.28.0, when `sqlite-jdbc` was updated to `3.21.0.1` ?
