### ISSUE TITLE
Add global settings in Admin Panel to localize formatting

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4827]
Not certain where in the Admin Panel this should go exactly, but we should add the ability to globally set local-specific formatting for things like:
- Numeric delimiters (commas vs. period for thousands place, etc.)
- 24-hour vs. 12-hour-AM/PM time
- Various day/month/year format options
- Default currency symbol to use (if and when we add `currency` as a subtype in the data model)
- Whether or not to put a `u` in the word `color` ;)

Related: https://github.com/metabase/metabase/issues/3791
Also related: https://github.com/metabase/metabase/issues/3201
Tangentially related: https://github.com/metabase/metabase/issues/1451

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
I think `color` vs `colour` is more of an i18n thing 

en-US vs en-GB

**Comment by sailxjx** [comment]
The time format is really a pain in metabase. Please give us a global setting of how time should display in metabase, like 'YYYY-MM-DD HH:mm:ss'.

**Comment by siggibjarna** [comment]
Is there any movement on this issue? Having to manually configure every card to use the "de" style number formatting and no decimals is rather painful.

Even if it would just be made possible to configure defaults for [Scalar.jsx#L74 settings](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/visualizations/Scalar.jsx#L74) via environment variables would be a good step forward.

I currently have to configure the following settings on all cards:
<img width="903" alt="screenshot 2017-11-17 13 19 15" src="https://user-images.githubusercontent.com/2643070/32949402-90a22fd0-cb9a-11e7-9bd2-41c149f854be.png">

Last but not least, keep up the good work on this awesome product!

**Comment by jornh** [comment]
## Week numbers

While at it with the bucket list in https://github.com/metabase/metabase/issues/4827#issue-223150537 please also consider adding setting week numbers as a system wide setting: https://en.wikipedia.org/wiki/ISO_week_date. 

Particularly some cultures in Europe practically *live and-almost-breathe* by week numbers! Since it's part of ISO 8601 Handling of the non-trivial calculations should be a problem long trivialized by libraries (e.g. [clj-time](https://github.com/clj-time/clj-time#clj-timeformat) already has `w` [formatting](http://www.joda.org/joda-time/key_format.html))

**Comment by emetselaar** [comment]
Good idea of making a global 'locale' setting for numbers at least.

**Comment by restyler** [comment]
adding "upper" and "lpad" for every number in sql report is really, really dirty and painful. Until this feature is implemented, is there any way to disable number formatting at all to avoid commas added everywhere?
<img width="492" alt="screenshot at jul 11 16-55-13" src="https://user-images.githubusercontent.com/775507/42572781-5a89e3f2-852b-11e8-9ba9-eaca5b05c3ad.png">

**Comment by mlrabbitt** [comment]
Agree with @restyler , would having some kind of "Disable commas in numbers" option fall into the scope of this issue, though?  It seems like it would be preferable to have "Number Format" options in the table customization section similar to how redash does it.  I would settle for a global comma disable though.

**Comment by Siddarth434** [comment]
Hi All,

I want different date formatting options in Metabase. Is it possible now or there is no solution yet?
I am seeing dates as Tuesday, January 30, 2018 12:00 AM
I want to see as 30/01/2018 without time.

Please suggest me if there is any work around

**Comment by mazameli** [comment]
Implemented in https://github.com/metabase/metabase/pull/8620!
