### ISSUE TITLE
clojure.core/load-file being overshadowed in metabase.routes

### ISSUE THREAD

**Issue by oyosc** [metabase/metabase#4830]
load-file already refers to: #'clojure.core/load-file in namespace: metabase.routes, being replaced by: #'metabase.routes/load-file

Exception in thread "main" java.awt.HeadlessException, compiling:(/tmp/form-init4471326940635545105.clj:1:73)

so please tell me how to solve?

tha java version is 8

**Comment by camsaul** [comment]
Hi @oyosc, that's a warning you can safely ignore. I'm planning on fixing it later today
