### ISSUE TITLE
`Lib.ensureFilterStage` does not add a stage when last stage has breakouts without aggregations

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#48339]
### Describe the bug

There are 2 issues here, see this comment for the other one: https://github.com/metabase/metabase/issues/48339#issuecomment-2393449924

https://github.com/user-attachments/assets/ce310fb2-4092-4ccd-be20-86c683e8156a

### To Reproduce

1. New > Question > Orders > Aggregate by Count > Breakout by Created At: Month > New stage > Aggregate by Count
2. Visualize
3. Open filter modal

There are 2 "Summaries" groups

----

1. New > Question > Orders > Aggregate by Count > Breakout by Created At: Month > New stage > Breakout by Created At: Month
2. Visualize
3. Open filter modal

There are 2 "Summaries" groups

### Expected behavior

There are 3 "Summaries" groups

### Information about your Metabase installation

master, 40ed53e

### Severity

P2

### Additional context

Affects https://github.com/metabase/metabase/issues/47800 and https://github.com/metabase/metabase/issues/46519

**Comment by uladzimirdev** [comment]
@kamilmielnik as I see in the method description

> "Adds an empty stage to `query` if its last stage contains both breakouts and aggregations.

**Comment by kamilmielnik** [comment]
@uladzimirdev description matches how it works, but it's not how it should work :)

**Comment by kamilmielnik** [comment]
> [@kamilmielnik](https://github.com/kamilmielnik) as I see in the method description
> 
> > "Adds an empty stage to `query` if its last stage contains both breakouts and aggregations.

Ok, adding filter stage does not make sense when there are only aggregations and no breakouts, because in that case we will only ever get 1 result row. Filtering 1 row can technically give you 0 or 1 rows though.

However adding filter stage makes sense when there are breakouts but no aggregations, because in that case we will get multiple result rows.

**Comment by kamilmielnik** [comment]
I tried to fix it myself but it's not as simple as changing `and` to `or` [here](https://github.com/metabase/metabase/blob/8b1f884/src/metabase/lib/stage.cljc#L415) as there are more issues at play.

1. `git checkout 47219-dashboard-drills-tests`
2. New > Question > Orders > Count > Save
3. Add it to a dashboard
4. Add Number filter to the dashboard and connect it to "Count" column
5. Save
6. Set filter value 

POST `/api/dashboard/:id/dashcard/:id/card/:id/query` gives this error: `Cannot determine the source table or query for Field clause`

If you add one more stage to the query, then the filter will be applied to stage -2 instead of -1.

Interestingly it works correctly if you drill into the question via dashcard header though.

**Comment by metamben** [comment]
I remember that I asked why we require both aggregation and breakout, and the answer was that it was by design.

**Comment by appleby** [comment]
> I remember that I asked why we require both aggregation and breakout, and the answer was that it was by design.

Link to previous discussion:

https://github.com/metabase/metabase/pull/46670#discussion_r1724048435

**Comment by kamilmielnik** [comment]
Conversation with product team in Slack: https://metaboat.slack.com/archives/C0645JP1W81/p1729599523886239

**Comment by kamilmielnik** [comment]
Conclusion: presence of breakouts in the last query stage is enough for `Lib.ensureFilterStage` to kick in and add an extra stage.
If there are aggregations but no breakouts - there should be no extra filter stage.
