### ISSUE TITLE
Google Analytics dimension missing in query builder dropdown 

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#4834]
The query builder does not show the entire list of Google Analytics data columns, i.e. “transaction ID” does not appear in the options in the “filtered by” or “grouped by” drop-down menu.
The data does exist though, as it can be retrieved using the native query by including “transaction ID” as additional dimension.

Thanks in advance for looking into this!

• browser and the version: Chrome 57
• operating system: Windows 10
• databases: MysQL
• Metabase version: 0.23.0
• Metabase hosting environment: Heroku
• Metabase internal database: default

**Comment by salsakran** [comment]
We removed some GA dimensions + metrics to keep the list from getting too crazy. 

We'll probably revisit the list of exposed D+M's at some point in the near future.

**Comment by HelenMertes** [comment]
"Transaction ID" is really one of the key dimensions though, being the order number from and link to the shop system...

**Comment by flamber** [comment]
Not sure when it was added back, but I can see `Transaction ID` on 0.35.3
