### ISSUE TITLE
Disable last edit text opening sidebars in sdk

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#48345]
<@U5A85JL4V> <@U01BP8Z3CVA> It looks like we accidentally surfaced the new sidesheet in the SDK? I think for now we should probably make sure it's hidden in the SDK component.

<https://metaboat.slack.com/archives/C063Q3F1HPF/p1728026135262979>

[Slack Message](https://metaboat.slack.com/archives/C064EB1UE5P/p1728033672858099?thread_ts=1728033672.858099&cid=C064EB1UE5P)

**Comment by iethree** [comment]
fixed by https://github.com/metabase/metabase/pull/48630

**Comment by WiNloSt** [comment]
Duplicate of https://github.com/metabase/metabase/issues/48354
