### ISSUE TITLE
"Frontend" calculations

### ISSUE THREAD

**Issue by benjR** [metabase/metabase#4835]
### "Front" calculations

After searching through existing issues, I saw that you don't want to mix data from multiple sources which as far as I understand would be very hard to do at the query level.

That being said, will there be a way to do some basic calculations at the "front" level ?
By handling the results of queries being done on two different sources ?

My basic need is the following, we are now using metabase as an internal "BI" tool to look after our figures and this already is great (really, great stuff), but we can't calculate stuff such as the conversion rate because we don't own the traffic data (it comes from Google Analytics) and we don't store it on our end.
We basically have a dashboard with one widget for the total number of sessions, and another one for the number of sales, I just want to get the conversion rate figure using those two.

Thanks for your time and your work on metabase :)

**Comment by benjR** [comment]
@salsakran Do you think this is something that you will look into in a near future?

**Comment by benjR** [comment]
Looks similar to #3251

**Comment by salsakran** [comment]
we do a version of this in notebook, and any kind of calculations on the frontend are out of scope for the project at this time.
