### ISSUE TITLE
Custom Chart Annotations

### ISSUE THREAD

**Issue by justin-yan** [metabase/metabase#4838]
Feature Request: I searched through the issues but couldn't find anything that was quite the same - #1454 might be similar - sorry if I missed it!

The problem we were facing is that we have a few charts that are graphed as time series.  Occasionally, there is a blip in the time series (maybe a spike due to some unusual event, or a dip because there was an outage) - and we thought that it would be nice if we could "comment" on the chart and leave an explanation for why something occurred, etc.

Something akin to Soundcloud's track annotation on time series would be really cool.  I can't think of any immediate use cases for comments on other charts, but perhaps others might have some?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by marciovicente** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by namdnguyen** [comment]
Superset provides an annotation layer: https://superset.incubator.apache.org/usertutorial.html#annotations

It works great to help explain shifts in a time series. Provides useful context, see: https://www.locallyoptimistic.com/post/adding_context_with_annotations

**Comment by luizarakaki** [comment]
@flamber may we close this?
