### ISSUE TITLE
Pin map tile endpoint can cause backend to hang / run out of memory

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4844]
It looks like the tiles endpoint basically executes the original query with an added `INSIDE` filter, which, if you do a bare rows query, will include every column in the table, when really only the lat/lon columns are required to generate the pin map.

https://github.com/metabase/metabase/blob/11f44fade3158835f3399e9e28a46539f4e2dd17/src/metabase/api/tiles.clj#L47-L57

Since `absolute-max-results` is 1048576, a large table with many columns and/or rows could result in a huge query that takes a lot of memory and time to execute (up to the entire size of the table, say, 1M rows x 400 bytes per row = ~400MB)
Often this can cause OOM.

Also, depending on the size of  map, multiple tiles are fetched for a single visualization (18 tiles on a full screen on my laptop, for example), which might amplify this (though each tile will only query a subset of the data)

If we were to only select the latitude and longitude columns the query result would be bounded to 1M x (8 bytes double float for latitude + 8 bytes double float for longitude) = 16 MB, which might be ok?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by hugocar** [comment]
I used the pin map a large table and ended having to restart metabase.jar
It seems related to this issue.

**Comment by janmpeterka** [comment]
Can default limit for map data be set for less than `absolute-max-result`, better to `max-results`? 
Our server got knocked out today because of this - Metabase took around 8GB of memory at one for this.
As there is separate request (with limit of 1M rows) for each tile, you can get to overloading database quite simply.
