### ISSUE TITLE
In Native Mongo Queries, JSON Parser adds extra quotes around variables when variable is inside quotes, breaking queries with dynamic fields

### ISSUE THREAD

**Issue by cubargh** [metabase/metabase#48484]
### Describe the bug

When using a mongo native query with a variable ({{coin}}) in JSON syntax (for example: "balance.{{coin}}"), the Metabase JSON parser incorrectly adds extra double quotes around the variable name, breaking the JSON structure. This results in errors like "balance."USD"" instead of the expected "balance.USD".

### To Reproduce

1. Create a query in Metabase using a variable, such as:
```
(...)
{
  "balance.{{coin}}": {
    "$ne": null
  }
}
(...)
```
2. Assign a variable to {{coin}} (e.g., USD)
3. Run the query.
4. Observe how Metabase generates the query with extra double quotes, resulting in an error.

### Expected behavior

Metabase should substitute the {{coin}} variable into the JSON query without adding extra quotes, generating the correct JSON structure (e.g., "balance.USD").

### Logs

Relevant output:

```
 ...    {\r\n          \"balance.\"USD\"\": {\r\n        ...
```

### Information about your Metabase installation
      "tag": "v0.50.24",

### Severity

blocks usage

**Comment by appleby** [comment]
Enclosing a variable in quotes is not supported, and not something we plan to do at this time.

Alternatively, if you can get the full nested field into a variable, you can use something like

```
{{field}}: {"$ne": null}
```

Internal slack discussion: https://metaboat.slack.com/archives/C0645JP1W81/p1729202416761989
