### ISSUE TITLE
Banner for instance in trial

### ISSUE THREAD

**Issue by losrebellos** [metabase/metabase#48522]
__Context__
We want to nudge our cloud customers on trial to activate their instance.

__Problem__
We do not have a mechanism for us to show our customers that their trial will soon end.

__Proposal__

[Product doc](https://www.notion.so/metabase/No-CC-required-for-Cloud-trial-d268a1a7f1d94990aef261cf1211aa76?pvs=4#10e69354c901800a802cd38e56aedd5b).

- [x] We need to display a banner for to admin users of an instance in trial, similarly to the past-due payment banner. 
- [x]  Banner appears 14d before trial ends
- [x]  X dismisses the banner
- [x]  banner appears 3d before trial ends, 2d before trial ends, 1d before trial ends (this is just conditional on the days until the end of trial, does not check if the banner was dismissed or not)
- [ ] Depends on https://github.com/metabase/infra-frontend/issues/1153, exact deep link url tbd 

[Figma with the updated design](https://www.figma.com/design/OGkkIYPpfcEfd7EjnmL6SJ/No-CC-required-for-Cloud-trial?node-id=657-1054&t=8zdpNzGRg0uz7WJ0-4)

![Image](https://github.com/user-attachments/assets/50e9413a-36ee-44a8-b616-93bef6a28768)

**Comment by nemanjaglumac** [comment]
The store URL: `https://store.metabase.com/account/manage/billing#section=payment-method`

**Comment by imrkd** [comment]
This suggestions are fairly complex, each of them has non trivial implementation cost. Specifically `if they close it again, it will re-appear every 24h` is turning into a backend concern for what should've been a trivial FE only change, and also imo user hostile. 
Can we narrow down suggestions to "minimal set of things that you're ok shipping"? and also once agreed let's update the product doc please.

**Comment by trinya** [comment]
Thanks, yes, let's not do the backend.
Minimal set we talked to with Nemanja about is hardcoded on FE:
- banner appears 14d before trial ends
- X dismisses the banner
- banner appears 3d before trial ends, 2d before trial ends, 1d before trial ends (this is just conditional on the days until the end of trial, does not check if the banner was dismissed or not)

**Comment by trinya** [comment]
>  why are we making this dissmisable again? why can't we just leave it there always till they put in the card?
Because we want to keep it for all trialers, even those that have a card. They don't need this banner whatsoever. If we make it conditional on having the card, that can work.

> and now thinking about it, what should we do when they do input the card? figure out a way to hide the banner via some signal, or should we make adding the CC effectively end the trial and be a "Buy Now" moment?
That was supposed to be "Buy Now" moment, yes. If this is too hard to do, then we need something else - either a way to dismiss it, or hide the banner if the payment details are in place.

**Comment by imrkd** [comment]
ok, so dismiss-able 👍 
conditional on having a card is going to be fairly tedious. 
@kidd note re "Buy Now" ☝

**Comment by trinya** [comment]
[Figma with the updated design](https://www.figma.com/design/OGkkIYPpfcEfd7EjnmL6SJ/No-CC-required-for-Cloud-trial?node-id=657-1054&t=8zdpNzGRg0uz7WJ0-4)

![Image](https://github.com/user-attachments/assets/50e9413a-36ee-44a8-b616-93bef6a28768)

**Comment by nemanjaglumac** [comment]
We're still not able to use this color in the main app. I have to use deep yellow (`warning`) color instead.
See: https://github.com/metabase/metabase/pull/49344#discussion_r1857294644
