### ISSUE TITLE
Pie chart labels are hidden when there's not enough space, causing confusion with settings

### ISSUE THREAD

**Issue by fer-batista** [metabase/metabase#48587]
### Describe the bug

When you disable show labels in pie chart it enables the labels. It is inverted.

[Slack context](https://metaboat.slack.com/archives/C01LQQ2UW03/p1728614230478829)

### To Reproduce

Create a new question, select pie chart, go to display, switch show labels.
![Image](https://github.com/user-attachments/assets/505702f2-c193-4024-a2d5-092baf025a53)
![Image](https://github.com/user-attachments/assets/a9ef8671-6b37-402d-bc7a-1850f72becff)

### Information about your Metabase installation

v1.51.0-beta

### Severity

P2

**Comment by cdeweyx** [comment]
[Slack context](https://metaboat.slack.com/archives/C01LQQ2UW03/p1728614230478829)
