### ISSUE TITLE
Something wicked this modal way comes.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#4863]
Seeing some odd visual bugs with modals off of master.

1. The `Which collection should this be in?` modal title should be centered but isn't.
![screen shot 2017-04-24 at 5 11 27 pm](https://cloud.githubusercontent.com/assets/5248953/25363729/9ab9775c-2911-11e7-94d5-1c557faebd64.png)

2. The save question modal is full width.
![screen shot 2017-04-24 at 5 15 01 pm](https://cloud.githubusercontent.com/assets/5248953/25363725/93f3143c-2911-11e7-8eb7-175aeccdd3a7.png)

After a cursory tour these were the only ones that seemed specifically to be off-kilter but it's possible there are others affected by this fun "things aren't where the should be" disease.

**Comment by mazameli** [comment]
This issue title is A+. 10 points for Gryffindor! 🌟
