### ISSUE TITLE
Error when unfold nested records in BigQuery

### ISSUE THREAD

**Issue by fer-batista** [metabase/metabase#48642]
### Describe the bug

Error when unfold nested records in BigQuery.

![Image](https://github.com/user-attachments/assets/d1e1401d-5fa2-44ab-aa29-504994ab0cea)

The first query created by Metabase return the error.
The second query created by me run fine.

BigQuery schema and query:
![Image](https://github.com/user-attachments/assets/bda893b7-3552-4abb-a7dd-fbb1473de379)
![Image](https://github.com/user-attachments/assets/66e29141-7cb3-40af-8067-750d088f0d8d)
![Image](https://github.com/user-attachments/assets/f52a582e-1f88-4406-8902-9a239e135563)

### To Reproduce

1. Go to query builder ou native SQL
2. Select a nested field
3. See error

### Information about your Metabase installation

v1.51.0-beta

### Severity

P2

**Comment by luizarakaki** [comment]
We don't support arrays (or repeated in BQ), but we also shouldn't error like this.
