### ISSUE TITLE
Export dashboard to HTML file

### ISSUE THREAD

**Issue by EderO** [metabase/metabase#4865]
Metabase is just great, but I miss how to export a dashboard to a single html file offline.

So we can send the file to any person and he can use any browser to check dynamically any chart of that dashboard.

I tried through chrome "Save as... MHTML, etc, but charts are not working.

**Comment by salsakran** [comment]
@EderO we render all of our charts dynamically. 

There's a bit too much going on on that front (authentication, data warehouse queriest, etc) for a save as html to work.

**Comment by flamber** [comment]
Closing in favor of #3770
