### ISSUE TITLE
Metabase pulse report fails if we include both internal and external email addresses

### ISSUE THREAD

**Issue by Chandra-cp** [metabase/metabase#48651]
We have generated a Metabase pulse report; however, when we include both internal and external email addresses, the pulse fails, however when we include only internal email addresses, it succeeds. The most recent pulse report, which included both internal and external email addresses, was successful on September 9, 2024. Would you kindly suggest

**Comment by paoliniluis** [comment]
This is not an issue but a question. Please post this in our forums and include all relevant information

**Comment by Chandra-cp** [comment]
Can you please share the path or url for forums?
