### ISSUE TITLE
Deleting a model doesn't remove it from database.

### ISSUE THREAD

**Issue by vipera7** [metabase/metabase#48664]
### Describe the bug

Deleting a model doesn't remove from database.

### To Reproduce

1. Go to View archive
2. Delete a model
3. Go to the database side
4. The model is still persisted

### Expected behavior

It should be removed from the database

### Information about your Metabase installation

Metabase version: v0.50.29
Metabase hosting environment: Jar-file
Metabase internal database : MySQL

### Severity

Unable to clean the database, which consumes disk space and leads to database clutter.

**Comment by kamilmielnik** [comment]
Related Slack thread: https://metaboat.slack.com/archives/C05NXACAG1G/p1728898909893109
