### ISSUE TITLE
Crash when showing data on map

### ISSUE THREAD

**Issue by naxIO** [metabase/metabase#4867]
Setup: Using 0.23.1.0 Standalone Mac, connected to a remote postgresql db. Using the default metabase database.

Problem: I want to display entries via Lat, Long and ID via the Map type. Once it tries to render the icons on the map, metabase shows a loading spinner and then returns me to the start page.

I assumed it has to do with the amount of rows, so I limited them to 10, 20 etc. and that worked. However if I just use 100 and zoom in a little, it "crashes" and throws me back to the start. 

I'm aware that processing 1000 or even more markers can be performance heavy, but instead it should just take longer and not crash.

Can I find the logs somewhere to see what the problem is? MaxRam maybe?

**Comment by jmwohl** [comment]
I'm seeing this too, and also curious about looking at logs — not sure if it's bad data that's crashing it, would be helpful to see the error.

**Comment by camsaul** [comment]
@naxIO @jmwohl do you run into this issue if you view the page in your browser? Open the Mac App and then click the link button in the upper-right corner and it will copy a link to the page to your clipboard. You can then paste that in your browser 

BTW you can look at logs by opening `Console.app`. You'll want to filter by `Metabase`

**Comment by naxIO** [comment]
Sorry for the delay. Browser is fine, its the mac app.

**Comment by flamber** [comment]
This seems to have been fixed in 0.26.2
