### ISSUE TITLE
In question sidesheet, models appear to be based on themselves

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#48698]
Discussion here: https://github.com/metabase/metabase/pull/48315#issuecomment-2411947670

**Comment by rafpaf** [comment]
Upgrading priority to P2 since the sources for models are now inaccurate. The table is not included in the list, and the model itself is. The sources for a model are not listed in the header, so this means crucial info is missing.

**Comment by iethree** [comment]
note: SQL models don't work in v51, but seem to work on master. Might be because of native SQL parsing?
