### ISSUE TITLE
Date-picker Issue

### ISSUE THREAD

**Issue by krishna-tech-dot** [metabase/metabase#48692]
### Describe the bug

When i execute the native query in the Metabase with hard-coded "FROM_DATE" and "TO_DATE", it is giving me "**correct results**" same as MYSQL DB.

But when i read From and To Date from the **date-picker of Metabase** then i am getting **one day older data**.

Note: 
Both Metabase and MySQL both zones are in-sync.

Please share the steps to resolve the date-picker issue.

### Expected behavior

Even i select the from and to date from the date picker from Metabase, native sql query should give the same result as hard code dates.

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_401-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_401",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.401-b10",
    "os.name": "Linux",
    "os.version": "4.18.0-425.19.2.el8_7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

### Severity

blocking my usage

**Comment by paoliniluis** [comment]
your version of metabase is so old that this might have been fixed in the last 4 years, please upgrade
