### ISSUE TITLE
Warning is not shown when trying to zoom in a line chart in an unsaved sql query

### ISSUE THREAD

**Issue by mngr** [metabase/metabase#48693]
### Describe the bug

When trying to zoom in a line chart in an unsaved sql query nothing happens
https://www.loom.com/share/ecba0c9b068c4991be321c7d689cb1b1

### To Reproduce

1. Click + New SQL
2. Write some code and visualize it as a line chart but don't save
3. Try to zoom in part of the chart

### Expected behavior

It should show the same modal "Save this question to drill-thru" as for the other drills

### Information about your Metabase installation

464902f

### Severity

very minor

**Comment by ranquild** [comment]
@mngr currently the behavior is different. We don't allow brush filters for unsaved native queries
