### ISSUE TITLE
Add option to automatically redirect all requests to HTTPS

### ISSUE THREAD

**Issue by wvengen** [metabase/metabase#4871]
On an ssl-enabled Heroku instance, both http and https are accessible, which means that users may inadvertently login over http. A redirect from http to https would be appropriate here.

This is similar to #1356, but then on Heroku instead of AWS. On Heroku one cannot configure a webserver to perform the redirect. Basically, if `X-Forwarded-Proto` is present and not `https` and the site url uses https, a redirect is needed.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by kylehg** [comment]
Is there any plan to implement this? We (like many users) would be keen to use this in our Heroku deployment of Metabase

**Comment by chungskie** [comment]
I would love this

**Comment by paulmwatson** [comment]
Any update on this? It's usually just `config.force_ssl = true` in a Rails app. As Metabase is now I send the link to colleagues who can't sign in with Google because it defaults to http:// and Google won't load it's scripts over http, it requires https. So I then spend a few minutes responding to each of them saying "make sure you are on https://blahblahblah.blah.com"

**Comment by dansteele** [comment]
Would still love this ^_^

**Comment by antoineverger1** [comment]
Hi @flamber. Short question :  you thumbed down the comments on this issue. Is there a particular reason why you think it's not a good idea ? I did some research but I can't figure out why it might be a bad idea.

**Comment by flamber** [comment]
@antoineverger1 
Because they provide no new details. If you want to upvote, then just click the :+1: on the first post.

**Comment by antoineverger1** [comment]
Thank you for the feedback @flamber ! Done for the :+1:

**Comment by camsaul** [comment]
we should add a toggle and it seems easy enough to add a middleware function to our Ring router to redirect it

**Comment by tlrobinson** [comment]
Do we think it should be a "redirect to HTTPS" or "redirect to site URL" setting?

**Comment by camsaul** [comment]
redirect to HTTPS

**Comment by easeev** [comment]
\+ Google App Engine Flexible https://stackoverflow.com/questions/41944776/force-ssl-on-app-engine-flexible-environment-custom-runtime

**Comment by camsaul** [comment]
We already detect whether a request is HTTPS here: https://github.com/metabase/metabase/blob/master/src/metabase/middleware/session.clj#L45

So we can probably leverage that code and write some new middleware to redirect non-HTTPS requests as appropriate.

Steps to implement this are:

1.  Add a new Setting called `redirect-all-requests-to-https` or something like that in that namespace using [`defsetting`](https://github.com/metabase/metabase/blob/master/src/metabase/models/setting.clj#L469). The setting should probably live in [`metabase.public-settings`](https://github.com/metabase/metabase/blob/master/src/metabase/public_settings.clj)
1.  Add the Setting to an appropriate page in the admin UI
1.  Create new Ring middleware that will redirect requests if setting is enabled and request is not HTTPS. It can probably go in [`metabase.middleware.security`](https://github.com/metabase/metabase/blob/master/src/metabase/middleware/security.clj).
1.  Add middleware to our Ring handler in [`metabase.handler`](https://github.com/metabase/metabase/blob/master/src/metabase/handler.clj#L25)
1.  Write lots of tests

**Comment by camsaul** [comment]
alternatively for step 3: check if something like this already exists so we don't have to reinvent the wheel

**Comment by tlrobinson** [comment]
Idea: having a setting in the UI to enable HTTPS redirect is a bit dangerous since if you don't actually have HTTPS you could end up locking yourself out. So when you try to enable HTTPS we could detect whether you actually have HTTPS enabled by attempting to load a resource with the HTTPS version of the URL.

I just tested this and it seems to work:

```js
function detectHttps() {
  return new Promise((resolve) => {
    if (window.location.protcol === "https:") {
      resolve(true);
    } else {
      const img = new Image();
      img.onload = () => resolve(true);
      img.onerror = () => resolve(false);
      img.src = window.location.origin.replace(/^http:/, "https:") + MetabaseRoot + "app/img/empty.png";
    }
  })
}
```

It's just using a random image we already have as the resource, since you can load images cross-origin without enabling CORS.

**Comment by camsaul** [comment]
@mazameli WRT the designs can we just make this a tab on one of the admin settings pages?

**Comment by mazameli** [comment]
> WRT the designs can we just make this a tab on one of the admin settings pages?

Yeah, I think this could just be an on/off toggle on `https://stats.metabase.com/admin/settings/general`, maybe right after the `Language` setting, with text like this:

`Redirect to HTTPS`
`Turn this on to automatically redirect all requests to this instance to HTTPS.`

If we can do what @tlrobinson described above and detect whether the instance actually has HTTPS, then we could have a separate state in the case where it's not available and have the toggle be disabled, ideally with different description text to the effect of, `It looks like HTTPS isn't set up for this instance.`
