### ISSUE TITLE
doesn't correspond to initial query LOAD DATA LOCAL INFILE

### ISSUE THREAD

**Issue by yangshifei** [metabase/metabase#48720]
(conn=328) LOAD DATA LOCAL INFILE asked for file 'C:UsersADMINI~1AppDataLocalTemp2upload_test_202410151656215568985393024798676.tsv' that doesn't correspond to initial query LOAD DATA LOCAL INFILE 'C:\Users\ADMINI~1\AppData\Local\Temp\2\upload_test_202410151656215568985393024798676.tsv' INTO TABLE `upload_test_20241015165621` (`1`, `2`). Possible malicious proxy changing server answer ! Command interrupted

**Comment by paoliniluis** [comment]
I don't think we support TSV

**Comment by yangshifei** [comment]
![Image](https://github.com/user-attachments/assets/0e8c1712-5d25-441f-a6ca-aea6146d3024)
support TSV
