### ISSUE TITLE
Should entity/primary/foreign key fields have their own icon in menus?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4873]
Currently they're just marked with the number (#) or category (Aa) icon:

![screen shot 2017-04-26 at 1 28 06 pm](https://cloud.githubusercontent.com/assets/2223916/25455327/3a7e24ea-2a84-11e7-9973-b2e512483185.png)

**Comment by flamber** [comment]
Not sure when this was changed, but probably long ago. This is how it looks on 0.35.3:
![image](https://user-images.githubusercontent.com/1447303/82759720-6a09e780-9def-11ea-8968-3c6a22c67154.png)
