### ISSUE TITLE
Upgrade to 0.50.29 fails with missing column report_card.dataset

### ISSUE THREAD

**Issue by cabarria** [metabase/metabase#48763]
### Describe the bug

Metabase goes into a loop after upgrading from v0.50.0-RC2 to 0.50.29. The following column is missing:
report_card.dataset

[Failed SQL: (1054) ALTER TABLE `metabase`.`report_card` MODIFY `dataset` BIT(1)]

Oct 15 15:34:21 host01 metabase[3459389]:         ... 90 more
Oct 15 15:34:21 host01 metabase[3459389]: UPDATE SUMMARY
Oct 15 15:34:21 host01 metabase[3459389]: Run:                         67
Oct 15 15:34:21 host01 metabase[3459389]: Previously run:             345
Oct 15 15:34:21 host01 metabase[3459389]: Filtered out:                 5
Oct 15 15:34:21 host01 metabase[3459389]: -------------------------------
Oct 15 15:34:21 host01 metabase[3459389]: Total change sets:          417
Oct 15 15:34:21 host01 metabase[3459389]: FILTERED CHANGE SETS SUMMARY
Oct 15 15:34:21 host01 metabase[3459389]: DBMS mismatch:                5
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,231 INFO liquibase.util :: UPDATE SUMMARY
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,231 INFO liquibase.util :: Run:                         67
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,231 INFO liquibase.util :: Previously run:             345
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,231 INFO liquibase.util :: Filtered out:                 5
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,231 INFO liquibase.util :: -------------------------------
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,231 INFO liquibase.util :: Total change sets:          417
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,232 INFO liquibase.util :: FILTERED CHANGE SETS SUMMARY
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,232 INFO liquibase.util :: DBMS mismatch:                5
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,234 INFO liquibase.util :: Update summary generated
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,236 INFO liquibase.command :: Update command encountered an exception.
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,241 INFO liquibase.lockservice :: Successfully released change log lock
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,242 INFO liquibase.command :: Logging exception.
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,243 INFO liquibase.command :: Command execution complete
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,245 INFO liquibase.lockservice :: Successfully released change log lock
Oct 15 15:34:21 host01 metabase[3459389]: 2024-10-15 15:34:21,276 ERROR metabase.core :: Metabase Initialization FAILED

### To Reproduce

Attempt to upgrade from v0.50.0-RC2 to 0.50.29.

### Expected behavior

It should correctly deal with missing column.

### Logs

These are the relevant log entries:

Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-05-29T09:26:20::johnswanson:
Oct 15 15:13:43 host01 metabase[3440275]:      Reason: liquibase.exception.DatabaseException: (conn=684) Unknown column 'dataset' in 'report_card' [Failed SQL: (1054) ALTER TABLE `metabase`.`report_card` MODIFY `dataset` BIT(1)]
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.changelog.ChangeSet.execute(ChangeSet.java:797)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.lambda$child$0(Scope.java:186)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.child(Scope.java:195)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.child(Scope.java:185)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.child(Scope.java:164)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.lambda$child$0(Scope.java:186)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.child(Scope.java:195)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.child(Scope.java:185)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.child(Scope.java:164)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.child(Scope.java:252)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.Scope.child(Scope.java:256)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
Oct 15 15:13:43 host01 metabase[3440275]:         ... 66 more
Oct 15 15:13:43 host01 metabase[3440275]: Caused by: liquibase.exception.DatabaseException: (conn=684) Unknown column 'dataset' in 'report_card' [Failed SQL: (1054) ALTER TABLE `metabase`.`report_card` MODIFY `dataset` BIT(1)]
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
Oct 15 15:13:43 host01 metabase[3440275]:         ... 81 more
Oct 15 15:13:43 host01 metabase[3440275]: Caused by: java.sql.SQLSyntaxErrorException: (conn=684) Unknown column 'dataset' in 'report_card'
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:362)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:500)
Oct 15 15:13:43 host01 metabase[3440275]:         at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
Oct 15 15:13:43 host01 metabase[3440275]:         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
Oct 15 15:13:43 host01 metabase[3440275]:         ... 86 more
Oct 15 15:13:43 host01 metabase[3440275]: Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Unknown column 'dataset' in 'report_card'
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:195)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:263)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)
Oct 15 15:13:43 host01 metabase[3440275]:         ... 89 more
Oct 15 15:13:43 host01 metabase[3440275]: Caused by: java.sql.SQLException: Unknown column 'dataset' in 'report_card'
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1693)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1555)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518)
Oct 15 15:13:43 host01 metabase[3440275]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:257)
Oct 15 15:13:43 host01 metabase[3440275]:         ... 90 more

### Information about your Metabase installation

:: System info:
Oct 15 15:29:55 host01 metabase[3455052]:  {"file.encoding" "UTF-8",
Oct 15 15:29:55 host01 metabase[3455052]:  "java.runtime.name" "OpenJDK Runtime Environment",
Oct 15 15:29:55 host01 metabase[3455052]:  "java.runtime.version" "17.0.12+7",
Oct 15 15:29:55 host01 metabase[3455052]:  "java.vendor" "Eclipse Adoptium",
Oct 15 15:29:55 host01 metabase[3455052]:  "java.vendor.url" "https://adoptium.net/",
Oct 15 15:29:55 host01 metabase[3455052]:  "java.version" "17.0.12",
Oct 15 15:29:55 host01 metabase[3455052]:  "java.vm.name" "OpenJDK 64-Bit Server VM",
Oct 15 15:29:55 host01 metabase[3455052]:  "java.vm.version" "17.0.12+7",
Oct 15 15:29:55 host01 metabase[3455052]:  "os.name" "Linux",
Oct 15 15:29:55 host01 metabase[3455052]:  "os.version" "4.18.0-553.22.1.el8_10.x86_64",
Oct 15 15:29:55 host01 metabase[3455052]:  "user.language" "en",
Oct 15 15:29:55 host01 metabase[3455052]:  "user.timezone" "America/New_York"}

### Severity

We've reverted back to previous version

**Comment by paoliniluis** [comment]
What version of MySQL are you running? Also, please always use Java 11

**Comment by cabarria** [comment]
> What version of MySQL are you running? Also, please always use Java 11

8.0.36 (Source distribution)

**Comment by cabarria** [comment]
Any ideas why does it fail with unknown column dataset?

**Comment by paoliniluis** [comment]
@cabarria there's a migration missing most definitely. Some previous migration on your app db didn't run and now you're hitting this.

This is the DDL of the table that has an error, please adapt your table to this:
```
create table if not exists metabase.report_card
(
    id                     int auto_increment
        primary key,
    created_at             timestamp(6)                   not null,
    updated_at             timestamp(6)                   null,
    name                   varchar(254)                   not null,
    description            longtext                       null,
    display                varchar(254)                   not null,
    dataset_query          longtext                       null,
    visualization_settings longtext                       null,
    creator_id             int                            not null,
    database_id            int                            not null,
    table_id               int                            null,
    query_type             varchar(16)                    null,
    archived               bit         default b'0'       not null,
    collection_id          int                            null comment 'Optional ID of Collection this Card belongs to.',
    public_uuid            char(36)                       null comment 'Unique UUID used to in publically-accessible links to this Card.',
    made_public_by_id      int                            null comment 'The ID of the User who first publically shared this Card.',
    enable_embedding       bit         default b'0'       not null comment 'Is this Card allowed to be embedded in different websites (using a signed JWT)?',
    embedding_params       longtext                       null,
    cache_ttl              int                            null comment 'The maximum time, in seconds, to return cached results for this Card rather than running a new query.',
    result_metadata        longtext                       null,
    collection_position    smallint                       null comment 'Optional pinned position for this item in its Collection. NULL means item is not pinned.',
    dataset                bit         default b'0'       not null,
    entity_id              char(21)                       null comment 'Random NanoID tag for unique identity.',
    parameters             longtext                       null comment 'List of parameter associated to a card',
    parameter_mappings     longtext                       null comment 'List of parameter associated to a card',
    collection_preview     bit         default b'1'       not null,
    metabase_version       varchar(100)                   null comment 'Metabase version used to create the card.',
    type                   varchar(16) default 'question' not null comment 'The type of card, could be ''question'', ''model'', ''metric''',
    initially_published_at timestamp(6)                   null comment 'The timestamp when the card was first published in a static embed',
    constraint entity_id
        unique (entity_id),
    constraint public_uuid
        unique (public_uuid),
    constraint fk_card_collection_id
        foreign key (collection_id) references metabase.collection (id)
            on delete set null,
    constraint fk_card_made_public_by_id
        foreign key (made_public_by_id) references metabase.core_user (id)
            on delete cascade,
    constraint fk_card_ref_user_id
        foreign key (creator_id) references metabase.core_user (id)
            on delete cascade,
    constraint fk_report_card_ref_database_id
        foreign key (database_id) references metabase.metabase_database (id)
            on delete cascade,
    constraint fk_report_card_ref_table_id
        foreign key (table_id) references metabase.metabase_table (id)
            on delete cascade
);

create index idx_card_collection_id
    on metabase.report_card (collection_id);

create index idx_card_creator_id
    on metabase.report_card (creator_id);

create index idx_card_public_uuid
    on metabase.report_card (public_uuid);
```
