### ISSUE TITLE
Color options for numbers visualization

### ISSUE THREAD

**Issue by tatuhey** [metabase/metabase#48774]
**Is your feature request related to a problem? Please describe.**
We heavily use Cards in Power BI on our dashboard and we color coded some significant value, sometimes even with conditional formatting too. It would be amazing if Metabase can support this as well.

**Describe the solution you'd like**
Option to select static color and dynamic color depending on its conditional formatting

**Describe alternatives you've considered**
n/a

**How important is this feature to you?**
![Image](https://github.com/user-attachments/assets/d6f3bef1-1bda-4cd2-9745-43a487869cea)
We use it a lot before migrating to Metabase

**Additional context**
![Image](https://github.com/user-attachments/assets/69bd3f48-ee53-4caf-9e4c-e36213c4cf9e)
_Image off Power BI_

**Comment by paoliniluis** [comment]
similar, if not the same as https://github.com/metabase/metabase/issues/48142
