### ISSUE TITLE
Extra filter stage breaks pivot table drills

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#48787]
### Repro steps #1

1. `git checkout dbfd4618ef5b981933035752c3b7bf81a26bd026`
    - it's branch `48445-unit-of-time-and-other-stages-tests` (#48726)
2. Run this test: https://github.com/metabase/metabase/blob/dcc33cebdfcd406f2a9bfb7359fcbe76f1446f7a/e2e/test/scenarios/dashboard-filters/temporal-unit-parameters.cy.spec.js#L401

### Repro steps #2

1. `git checkout dbfd4618ef5b981933035752c3b7bf81a26bd026`
2. Create a question with aggregation and 2 temporal breakouts in the last stage (e.g. Orders > Count > Breakout by Product Created At > Breakout by Order Created At)
3. Add it to dashboard and save it
4. Notice that POST `/api/dashboard/:id/dashcard/:id/card/:id/query` will give `data.cols[].source === "aggregation"` for the aggregation column ([screenshot](https://github.com/user-attachments/assets/bec2a230-186e-4360-97cd-794dbc8b4426))
5. Add unit of time parameter to the dashboard and connect it to the dashcard
6. Save dashboard
7. Notice that POST `/api/dashboard/:id/dashcard/:id/card/:id/query` will now give `data.cols[].source === "fields"` for the aggregation column ([screenshot](https://github.com/user-attachments/assets/491d3870-cd0b-4fb4-b8fe-e8e9dc368439))

This breaks FE logic detecting whether pivot table should be used: https://github.com/metabase/metabase/blob/92d615073a3ba31710e26be9f2e83141352d1d1c/frontend/src/metabase/visualizations/visualizations/Table.tsx#L97

`data.cols.filter(isDimension).length` will be `3` instead of `2`

### Additional info

It's the mere presence of `{ "stage-number": -2 }` in `dashboard.dashcards[].parameter_mappings[].target` that causes this.

We can't simply remove this because FE depends on the presence of this information when applying dashboard filters and parameters to a dashcard when clicking on its title (which navigates to an ad-hoc question).

### Non-negative stage indexes

Using [non-negative stage indexes](https://github.com/metabase/metabase/issues/48441) could possible help with this.
OTOH it may cause some issues with composed ad-hoc questions on FE side where we use virtual tables to use models and metrics as query source.

**Comment by kamilmielnik** [comment]
### Repro steps #3

1. `git checkout dbfd4618ef5b981933035752c3b7bf81a26bd026`
2. Run this test: https://github.com/metabase/metabase/blob/dcc33cebdfcd406f2a9bfb7359fcbe76f1446f7a/e2e/test/scenarios/dashboard-filters/temporal-unit-parameters.cy.spec.js#L471

The root cause of this issue looks the same.
In this case we're getting unexpected:
- `data.cols[].source === "fields"` instead of `data.cols[].source === "breakout"`
- `data.cols[].field_ref[2]` is missing `"temporal-unit"` attribute

**Comment by kamilmielnik** [comment]
The following tests are failing in `48445-unit-of-time-and-other-stages-tests` (#48726) due to this issue:
- `multiple-column-breakouts.cy.spec.ts`
    - `should be able to use temporal-unit parameters with multiple temporal breakouts of a column`
- `visualizations-tabular/pivot_tables.cy.spec.js`
    - `should allow filtering drill through (metabase#14632) (metabase#14465)`
- `temporal-unit-parameters.cy.spec.js`
    - `should connect a parameter to a question and drill thru`
    - `should connect multiple parameters to a card with multiple breakouts and drill thru`

**Comment by ranquild** [comment]
@kamilmielnik the `source` is actually correct and it's not a BE bug. We get an extra stage which changes `source`. Which is bad news for us because the FE needs to be fixed, but (!) pivot tables are just built this way so they rely on presence of aggregations and breakouts in the last stage.

**Comment by kamilmielnik** [comment]
We decided to not use the extra filtering stage for pivot tables.
Closing in favor of #48884 and #48885.
