### ISSUE TITLE
Unsaved changes warning redundantly shown when targeting a question with custom click behavior

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#48829]
### Describe the bug

https://github.com/user-attachments/assets/32c719c5-3ce9-4a3d-a738-a40363a7c5e3

### To Reproduce

1. New > Question > Orders > Visualize > Save
2. Add this (or any other) question to dashboard
3. Configure click behavior for this dashcard:
    - choose any source column
    - set saved question from step 1 as target
    - choose any target column
4. Save
5. Try out the click behavior
6. You're now taken to chill mode
7. Click "Show editor"
8. Remove the filter
9. Click "Visualize" or "Show Visualization"

❌ Unsaved changes warning is shown

10. Click "Show editor"

❌ Unsaved changes warning is shown

### Information about your Metabase installation

master, deac5cbcc7

### Severity

P2

**Comment by romeovs** [comment]
This also happens when:

1. New > Question > Orders > Visualize > Save
2. Navigate to the question
3. Add a filter to the question
4. Show Editor
5. Remove the filter
6. Visualize

❌ Unsaved changes warning is shown
