### ISSUE TITLE
Roll back default filter operator to "is" from "contains"

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#48845]
**Is your feature request related to a problem? Please describe.**
The problem is the new default operator when filtering string columns. Before the default operator was "is". For a couple releases it is "contains", which leads to a lot of danger in filtering and getting false positives. Very dangerous for beginners.

**Describe the solution you'd like**
Roll back to having "is" as the default operator.

**Describe alternatives you've considered**
95% of filter operations are "is". I just have to spend more time every time i filter.

**How important is this feature to you?**
Very important. I think it is a dangerous default to set as most users will think of a direct match as the default filter.

**Comment by Timelessprod** [comment]
Big up on this one!

**Comment by paoliniluis** [comment]
@carstenkadmos here's what the FE team is mentioning about this:
```
it’s Is for
- PKs
- FKs
- Anything with field values
Otherwise it’s "Contains"
```

would you say what's the use case here so we can check this out?

**Comment by mngr** [comment]
@carstenkadmos what is you Metabase version? the mentioned logic is implemented in 51
