### ISSUE TITLE
Text Filter breaks when to many values are added

### ISSUE THREAD

**Issue by carstenkadmos** [metabase/metabase#48851]
### Describe the bug

When adding a lot of ids via copy paste to the filter box, it currently becomes infinitely long without a scroll option. as such it is impossible to click the filter button and go ahead with the desired operation.

(image redacted for data privacy reasons)

![Image](https://github.com/user-attachments/assets/13c38aa3-b3eb-4b57-9332-04695563a37b)

### To Reproduce

1. Go to a table and filter for a text value.
2. Copy paste a big list of values, for instance from an excel, to the filter box. The filter box is as per default set to the "contains" operator.
3. See the list extents beyond the screen without the option to filter.
4. There is no way to click next and actually filter.

### Expected behavior

The box with the added values becomes scrollable and does next extend infinitely.

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-15",
      "tag": "v0.50.30",
      "hash": "a49cb77"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.15"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.12+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.12+7",
    "os.name": "Linux",
    "os.version": "6.1.100+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}

### Severity

High

**Comment by Timelessprod** [comment]
I got some users reporting getting stuck because of this. The workaround is to change the filter type which will bring back the popup to the default size with a scrollable list and then switch again to the correct filter type. Not ideal solution.
