### ISSUE TITLE
New question text and actions are misaligned

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#4885]
This seems to be because the title expects there to be a collection item there but there isn't one.
<img width="1120" alt="screen shot 2017-04-26 at 4 04 03 pm" src="https://cloud.githubusercontent.com/assets/5248953/25460767/178da56c-2a9a-11e7-86f3-4ff1c4e32ce8.png">

**Comment by flamber** [comment]
Hi @kdoh 
I guess this was fixed as part of the HeaderBar cleanup? It looks fine in 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52813509-8ac98600-305f-11e9-9b42-8eb2d3fe3639.png)
