### ISSUE TITLE
Y-Axis label should be per-y axis

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4887]
Right now if I have two series on a dashcard and they result in split axes, the label input overrides both of them..

Ideally, they should be independently settable 

![screen shot 2017-04-26 at 4 06 27 pm](https://cloud.githubusercontent.com/assets/107439/25460827/56db04e4-2a9a-11e7-80db-c2558737d9c8.png)

**Comment by kdoh** [comment]
I'm going to close this (even though it was filed first) since it's the same issue as #5583 and there's a bit more of a discussion thread over there.
