### ISSUE TITLE
Databases added by config file are not synced regularly

### ISSUE THREAD

**Issue by devurandom** [metabase/metabase#48881]
### Describe the bug

No Quartz trigger is created for databases added by the config file, thus they are not synced regularly.

### To Reproduce

1. Metabase starts with an empty application database, and a [config file
   containing configuration for a connected database](https://www.metabase.com/docs/latest/configuring-metabase/config-file#databases)
2. It passes "INFO advanced-config.file :: Initializing :databases from config file... 🗄️"
3. It prints "INFO task.sync-databases :: A trigger for "Sync and Analyze" of Database "Metabase Cloud Storage" has been enabled with schedule: "0 22 * * * ? *"" *multiple* times
4. It reaches "INFO metabase.task :: Task scheduler started"
5. `qrtz_triggers` does not contain *any* `metabase.task.sync-and-analyze` triggers (not for the DB from the config file and not for the sample H2 DB)
6. Changes to the database (adding tables) do not become visible to Metabase

### Expected behavior

Databases should always be synced regularly, no matter how they are created.

### Information about your Metabase installation

Local setup of deac5cbcc7e68d20f7ffe71d021dafa73e6e9de6.

### Severity

Full blocker

### Additional context

References: https://metaboat.slack.com/archives/C079ZS06ERJ/p1728991333736979

**Comment by dpsutton** [comment]
I'm starting up a local instance with an empty app-db:

```shell
MB_PREMIUM_EMBEDDING_TOKEN=$TOKEN MB_JETTY_PORT=3006 MB_DB_CONNECTION_URI=$PG_CONN java "$(socket-repl 6006)" -jar $JARS/1.50.30.jar
```

and i see there are indeed no triggers for the database:

```clojure
task=> (filter (comp #{"metabase.task.sync-and-analyze.job"} :key) (jobs-info))
({:key "metabase.task.sync-and-analyze.job",
  :class "metabase.task.sync_databases.SyncAndAnalyzeDatabase",
  :description "sync-and-analyze for all databases",
  :concurrent-execution-disallowed? true,
  :durable? true,
  :requests-recovery? false,
  :triggers ()})
```

This demonstrates that there are indeed no triggers for the database. I had a suspicion that a trigger would be added when the instance restarted but this is not the case unfortunately.

**Comment by devurandom** [comment]
Fix in https://github.com/metabase/metabase/pull/48882.

**Comment by devurandom** [comment]
* v50: https://github.com/metabase/metabase/pull/48897
* v51: https://github.com/metabase/metabase/pull/48894
