### ISSUE TITLE
Date range filtration with unix timestamp (SQL)

### ISSUE THREAD

**Issue by AshrafSam** [metabase/metabase#4888]
I'm in love with Metabase, but I still have a lot of things in mind for it.

I'm more comfortable using the SQL editor, my database date fields are unix-timestamp formatted, and I want to use the Date Range Filter.

I don't seem to be able to just add a variable of Field Filter type and put "where {{date}}" in the SQL editor. Instead, the only way I can think of is to do:

"where date >= unix_timestamp({{date1}}) and date <= unix_timestamp({{date2}})" and do two Date variables. This limits the date range experience since users will need to use two date pickers instead of a one easy-to-use date range picker.

Is there a way around it? Are you considering this in future versions?

Best.
ASH

**Comment by salsakran** [comment]
If you go to the data model page in the admin and set those fields' semantic type to "Unix Timestamp" it'll work.

![screen shot 2017-05-03 at 6 04 43 pm](https://cloud.githubusercontent.com/assets/107439/25687437/0e479922-302b-11e7-8987-f8b571e05bcb.png)

**Comment by AshrafSam** [comment]
@salsakran I tried that but it doesn't work.

`time` is int(15) in the database. in the traced query, it says date(`time`) though i think it should something like from_unixtime(`time`). am i doing anything wrong?

Some screenshots:
<img width="967" alt="screen shot 2017-05-29 at 12 14 01 pm" src="https://cloud.githubusercontent.com/assets/351800/26546136/c6fdfbd6-4468-11e7-8a66-f080126e02a5.png">
<img width="929" alt="screen shot 2017-05-29 at 12 15 50 pm" src="https://cloud.githubusercontent.com/assets/351800/26546135/c6fc56b4-4468-11e7-8b72-17d63fd170bb.png">
<img width="1091" alt="screen shot 2017-05-29 at 12 16 05 pm" src="https://cloud.githubusercontent.com/assets/351800/26546137/c703fe14-4468-11e7-852e-c305b98b5db5.png">

**Comment by camsaul** [comment]
Duplicate of #4058
