### ISSUE TITLE
Interactive Charts in Dashboard

### ISSUE THREAD

**Issue by AshrafSam** [metabase/metabase#4889]
So my use case is:

- I display funnels for events happening on our website.
- I want user to be able to explore each funnel step's data when they click on the step.

So basically, if they click on the first step, they see a table of all this step's users, and so on other steps.

The simplest way I'm thinking of is that I can say: For step 1, show dashcard 1 and hide 2, and for step 2, show 2 and hide 1.

Thanks!

**Comment by salsakran** [comment]
#4496 is our solution to this.
