### ISSUE TITLE
Funnels?

### ISSUE THREAD

**Issue by AshrafSam** [metabase/metabase#4890]
I was trying to use the funnels in SQL mode but was never able to figure out how to make it work.

It asks for the steps, and they are always disabled and I can do nothing.

Found similar things reported here but wasn't able to understand if it was ever fixed or if it's still a problem and how I can get over it.

Any thoughts?

**Comment by salsakran** [comment]
what is the shape of your output data? can you provide an example of a sql query that doesn't let you do a funnel?

**Comment by AshrafSam** [comment]
The general format of the query is that it select three scalar fields (i.e 3 aggregations).

I just tried this sample query: "select 100, 90, 30". The funnels option is turned off though I want to create a funnel out of the 100, 90 and 30.

Am I getting your funnels wrong? I already do that with other visualisation tools and I thought it's very logical. But the funnels is disabled and when I click on it a weird behavior is happening (I select fields but nothing happens again).
