### ISSUE TITLE
No More external DB mess and issue of loss of data with h2 bydefault database

### ISSUE THREAD

**Issue by mehboobpatel** [metabase/metabase#48921]
![Image](https://github.com/user-attachments/assets/b6d5ff0f-8c1a-424c-a05c-eff1d422a247)

**Solved**
**Use the h2 database giving persistent volume**

services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    user: "1001"  # Switch to non-root user ID  modify the existing container and commit OR modify the Dockerfile  image creation                     
    ports:
      - "3000:3000"
    volumes:
      - metabase-db:/metabase.db
    restart: always

volumes:
  metabase-db:
    driver: local

* Note : please make sure that the you restrict permissions of tha docker volume folder on your host machine
connect me : maheboob.dev

**Comment by paoliniluis** [comment]
sorry I don't know what this is. Please do not, never ever, use H2 as a database that you'll use in a production deployment. You'll end up losing everything, forever, and it's going to be unrecoverable. We can't say this enough: please use postgres or mysql when using Metabase for production deployments
