### ISSUE TITLE
Clarify the removal of 'Powered by Metabase' banner for Cloud / Starter plan

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#48925]
### Describe the bug

On OSS instances, the Admin Settings / Embedding section directs users to upgrade to a paid plan to remove the "powered by" banner on static embeds:
> A "powered by Metabase" banner apperas on static embeds. You can upgrade to a paid plan to remove it.
![Image](https://github.com/user-attachments/assets/4f304876-5c4a-472b-87cb-eb656d90a32f)

The message is correct for self-hosting, but it could be confusing for admins of cloud instances on the Starter plan, as it's also a paid tier. To avoid this, we should display a different message for them, something like:

> "A 'powered by Metabase' banner appears on static embeds. Upgrade to a Pro or Enterprise plan to remove this banner from your cloud instance."

### To Reproduce

Go to Admin Settings / Embedding on a Cloud hosted Starter instance.

### Information about your Metabase installation

All versions

### Severity

Confusing for customers on the Starter plan

**Comment by brunobergher** [comment]
Yeah, let’s change it to 

> A “powered by Metabase” banner appears on static embeds. You can upgrade to a paid plan which removes it.

using the same URL
