### ISSUE TITLE
CSV Imports Sometimes Incorrectly Infer Encoding (50.25+)

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#48945]
### Describe the bug

Imported a UTF8 CSV file with ASCII extended characters and it's importing them as Chinese characters. Interestingly whether this occurs seems to have some relationship to the size of the sample set in the file. the same row in the file 7 times will be imported correctly. But duplicate the 7 rows 10 more times and things go sideways.

The user initially experiencing this has large CSV files - oddly if the sample dataset is small the file imports correctly. Adding the same rows via copy/paste to the same file until the sample set is larger results in this bug presenting as well. So if you begin with a smaller CSV, then the encoding breaks as the files grows, you can no longer append to CSV, either.

### To Reproduce

1. Spin up version 50.25+ (works in 50.24)
2. Enabled CSV uploads for Postrges test DB
3. Import these test files:

- Incorrect: [import_test.csv](https://github.com/user-attachments/files/17464933/import_test.csv)
- Incorrect: [import_test2.csv](https://github.com/user-attachments/files/17464935/import_test2.csv)
- Correct: [import_test3.csv](https://github.com/user-attachments/files/17464938/import_test3.csv)

These import correctly in 50.24 and prior. They also work correctly if you use UTF8-BOM rather than UTF8.

### Expected behavior

Character encoding should be inferred correctly.

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-09-10",
      "tag": "v1.50.25",
      "hash": "473a7ca"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.15.153.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}

### Severity

blocking some users

**Comment by crisptrutski** [comment]
Sound like this may be related to https://github.com/metabase/metabase/pull/47799

**Comment by crisptrutski** [comment]
I've confirmed that this behavior is due to the inference coming from our 3rd party dependency.

The files are inferred respectively as:

1. TIS620 (Thai)
2. GB18030 (Chinese)
3. UTF-8

**Comment by crisptrutski** [comment]
One potential solution is to have a allowed or disallowed encoding list, and treat the excluded ones as UTF-8.

Another avenue could be to explore the confidence our inference has, although there's no high level API for doing this in the dependency and it would need to be quite complex. I'm also not sure what the confidence ratings are in these particular cases, let alone in the customer's actual data.

A more long term solution could be to add a modal on upload where the user can confirm the encoding. This modal could also be used for confirming column types, matching columns on append, etc.

**Comment by crisptrutski** [comment]
The reason longer files tended to trigger the issues more is that the detection algorithms build confidence based on both the relative and absolute frequency of various codepoints.
