### ISSUE TITLE
Multiple aggregations (view) for Google Analytics

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4894]
Not sure if it's a bug or feature request but I can't seem to do multiple aggregations for Google Analytics on latest Mac app.

![screen shot 2017-04-26 at 19 09 25](https://cloud.githubusercontent.com/assets/1330677/25465030/af87a01a-2ab4-11e7-89e5-2f8858564891.png)
vs
![screen shot 2017-04-26 at 19 09 37](https://cloud.githubusercontent.com/assets/1330677/25465031/af88d03e-2ab4-11e7-96d0-55e477194aac.png)

**Comment by VikramTiwari** [comment]
@camsaul @tlrobinson Isn't this a bug? If not backend then UI should not be showing multiple aggregations if it's yet to be implemented.

**Comment by tlrobinson** [comment]
@VikramTiwari I've got a fix for this in #6822. Please try it out.

**Comment by VikramTiwari** [comment]
Hey, @tlrobinson This works great! Thanks for the update. Waiting for next release 👍
