### ISSUE TITLE
Map is not populating

### ISSUE THREAD

**Issue by TomUssery** [metabase/metabase#4897]
I have connect metabase to Google Analytics, the question is:
Filter by Date: After Jan 1 2017
View Sessions
Group by Region

Desired Format: Map

The key is populating, however the map is not showing the colors within each state. I have converted this to a huge pie chart in the meantime.

**Comment by salsakran** [comment]
Google analytics returns regions, region ids and region iso codes in a format that's different from the geo-json files we ship with Metabase. You'd need to find a map that uses those identifiers.

**Comment by sbelak** [comment]
Retired in favour of #6768
