### ISSUE TITLE
Implement :not for Google Analytics

### ISSUE THREAD

**Issue by TomUssery** [metabase/metabase#4898]
I have connected to Google Analytics

Desired Questions

Filter:  Page contains "a" AND Page does not contain "b"
View sessions 
Grouped by Page

I am receiving an error message that "not" isnt working. Do you have timing for this? 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
You're the first person to notice. This is the sort of thing we build out in response to people using/hitting it.

**Comment by benoneal** [comment]
I'm noticing this too. I'm trying to show pageviews by facebook vs not facebook referrer, and the lack of `:not` makes this impossible.

**Comment by e346m** [comment]
Is it difficult to implement :not?
How does everyone filter for now?

**Comment by camsaul** [comment]
I think Google Analytics doesn't directly support negating a filter with something like SQL's `NOT` e.g. you can't do something like

```sql
SELECT ... WHERE NOT (a = b AND c > d))
```

Of course you can just rewrite the logic something like 

```sql
SELECT ... WHERE a != b OR c <= d
```

it shouldn't be too hard to do. This can be done as an MBQL transformation. `:not` is only used internally and only used to implement a few filters

**Comment by camsaul** [comment]
I actually added some util functions to logically negate filter clauses to the MBQL lib so this should be trivial now.

**Comment by martin-knap** [comment]
Implementation is very easy, just replace = with ! in json statement. Can somebody create pull request please?
**contains**               "filters": "ga:campaign=~(?i)brand",  
**does not contain** "filters": "ga:campaign!~(?i)brand",
