### ISSUE TITLE
Dashboard Time Filter vs Question Filter Error

### ISSUE THREAD

**Issue by TomUssery** [metabase/metabase#4899]
While connected to Google Analytics

I set up a question for display on my dashboard
 - Filter: Date after Jan 1 2017
   View Sessions 
   Result as a Number
   Dashboard label  = Sessions Month To Date
- Desired end state -  two tiles where one shows year to date, the other by month that is selected as a dashboard filter on Month and Year

However, the date filter within the original question is causing the dashboard level filter to throw an error is message. is this by design?

**Comment by salsakran** [comment]
what is the error that is returned?

**Comment by TomUssery** [comment]
![error msg](https://cloud.githubusercontent.com/assets/27392006/25703910/838cfebe-30a5-11e7-97b1-f00ba189a7b1.JPG)
As seen on the dashboard

**Comment by sashankQ** [comment]
@TomUssery  @salsakran  any update on this issue? I am also stuck in this situation.

**Comment by flamber** [comment]
Duplicate of #4766
