### ISSUE TITLE
dashboard organization enhancement request

### ISSUE THREAD

**Issue by TomUssery** [metabase/metabase#4900]
Our business has over 40 clients, each that will require multiple dashboards. Is there a way to organize the dashboards in the drop down? Ideal State would be

As a best practice we have setup question folders for each dashboard and a higher level grouping like what is proposed here would be a great help there as well. 

Client 1 >
Client 2>
  Dash 1
  Dash 2
  Dash 3
Client 3>
  Dash 1 
  Dash 2
  Dash 3

**Comment by salsakran** [comment]
related to #2326

**Comment by VikramTiwari** [comment]
This could be closed now since the view is totally different and easily organizable as well. @salsakran

**Comment by mbvictoria** [comment]
Closing - no longer relevant in the current design.
