### ISSUE TITLE
URL manipulation allows unauthorised data access

### ISSUE THREAD

**Issue by Vivek-M-08** [metabase/metabase#49070]
### Describe the bug

Hello Metabase team,

I am currently using the free version of Metabase for learning and testing purposes. I've set up two dashboards for two different users based on hardcoding state names into the filters. The expectation is that users should only be able to view data for their respective states.

For example, if a user from Karnataka logs in, they should only see data related to Karnataka, and similarly for another user from a different state.

### The Problem:

When a user from Karnataka logs in, they are initially presented with the correct data. However, if they manually modify the URL and change the query parameter from select_state=Karnataka to another state like select_state=Kerala, they can then access data for Kerala, which should not be permitted.

### For example:

**Original URL (working as expected):**
`/dashboard/4-state-report-karnataka?state_param=Karnataka`
[Image](https://discourse.metabase.com/uploads/default/original/3X/3/f/3f72c903836f1a2e84a791047ba56fb51fd41f92.png)

**Modified URL (security issue):**
`/dashboard/4-state-report-karnataka?state_param=Kerala`
[Image](https://discourse.metabase.com/uploads/default/original/3X/5/e/5ed8e8aee1231aa9894c0c308ca69d6dd42e9a41.png)

This unauthorized access exposes data from other states, which breaks the intended state-specific restrictions. My expectation was that each user would be restricted to their own state data, regardless of any changes they make to the URL.

I would appreciate your help in fixing this issue or guiding me towards the correct way to implement state-specific access restrictions that cannot be overridden by URL changes.

Thank you for your attention to this matter!

### To Reproduce

5. https://discourse.metabase.com/uploads/default/original/3X/3/f/3f72c903836f1a2e84a791047ba56fb51fd41f92.png

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.4.16-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-08-13",
      "tag": "v0.50.20",
      "hash": "df82d58"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

### Severity

High - This will allow user to access unauthorised data

**Comment by paoliniluis** [comment]
As I mentioned in your stackoverflow post, please read the docs before creating an issue, this is not a security issue and the product has a feature to make filters to be locked to user parameters
