### ISSUE TITLE
Very high default topN limit causes Druid cluster to blow up on queries

### ISSUE THREAD

**Issue by TheMP** [metabase/metabase#4907]
Hi, we are currently using:

- Druid 0.9.1 cluster
- Metabase v. 0.23.1

When doing topN query without specifying limit on number of results, metabase currently uses the **absolute-max-results** constant to define it. According to code it comes from Excel properties  and is currently set to 1048576. Such a big value is too heavy for druid cluster to handle, which causes either serious timeouts for all parallel queries or sometimes even brings the nodes down due to OOM exceptions while trying to fetch the results. 

So far the only solution is to ask  users to avoid doing queries without specifying the limit themselves, which is of course hard to enforce.

According to Druid doc (http://druid.io/docs/latest/querying/topnquery.html) the recommended value that is used by default (hardcoded somewhere in druid is 1000). Therefore the quick and easy fix to this big issue would be just modifying this default limit to be consistent with druid and set it to 1000.

**Comment by salsakran** [comment]
closed via #4908
