### ISSUE TITLE
Results In visualization and dashboards are different from actual results in the tables on metabase and the actual database

### ISSUE THREAD

**Issue by ZiadEK8** [metabase/metabase#49103]
**Describe the bug**
When creating a question it initially shows the correct numbers but after saving it and adding it to dashboards the questions show wrong values even tho if remove the visualisations and look at the actual table with filters only the numbers are correct 

**To Reproduce**
1. Create a question 
2. Save it
3. Add it to a dashboard
4. Refresh after a while

**Expected behavior**
Show correct results that reflect the data in the tables 

**Screenshots**
![Image](https://github.com/user-attachments/assets/6f039d07-a89d-4d03-9d34-f23b516aaedc)
![Image](https://github.com/user-attachments/assets/b62778b7-ef81-4a2c-b95c-eec017e5d9b1)
![Image](https://github.com/user-attachments/assets/81abbfd6-c730-4e61-aeeb-7c787a36d3ea)
When I remove the summary and add a filter for today:
![Image](https://github.com/user-attachments/assets/4f606c87-507b-41e9-b815-bd73042ec5f4)
and here it is as a number card showing the correct result:
![Image](https://github.com/user-attachments/assets/0c0f8e43-c404-4395-927b-0f0ca242d1fd)
but even if I save it as a number card the same thing happens and the results become wrong after a while and not even increase but decrease which is impossible 
**Severity**
High imo, reports are showing wrong numbers and some of these reports are being sent daily or hourly to higher-ups at my workplace thus making all reports coming from Metabase worthless rn 

**Additional context**
We're using MariaDB

**Metabase Diagnostic Info**

``{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-02",
      "tag": "v0.50.28",
      "hash": "3179ef2"
    },
    "settings": {
      "report-timezone": "Africa/Cairo"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.226-214.879.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

**Comment by paoliniluis** [comment]
please ensure that the rows are commited, we just send queries to the DW an render that, we're actually rendering what comes from the DB here
