### ISSUE TITLE
"Week of Year" and "Week" differs

### ISSUE THREAD

**Issue by atharvai** [metabase/metabase#4910]
- Your browser and the version: Chrome 57.0
- Your databases: Redshift
- Metabase version: 0.23.1
- Metabase internal database: Postgres

I followed several issue discussions 
https://github.com/metabase/metabase/issues/1987
https://github.com/metabase/metabase/issues/1635
https://github.com/metabase/metabase/issues/1779
http://discourse.metabase.com/t/how-are-mysql-dates-queried-for-this-week-and-last-week/185/2

It seems at some point "add 1 day" solution was added. When I do Group By "Week of Year" in the Question interface the produced SQL expression is as follows:
`CAST(extract(week from (<datecolumn> + INTERVAL '1 day')) AS integer) AS "date"` 
What is the reason for this add 1 day? It doesn't make sense as it means that the week number is returned for following day and not current day. 
Similarly Day of Week produces `(CAST(extract(dow from <datecolumn>) AS integer) + 1) AS "date"` which adds 1 again.
`select CAST(extract(dow from '2017-04-28'::date) AS integer)` returns 5 
but above expression returns 6. Again Sunday based but seems to be forced/hacked way of setting date. 

I feel like ISO standards define the timezone, timestamp and calendar definitions pretty clearly and are fundamental concepts expected to be consistent during any analysis. Why not use the source database defaults? Why try to hack standards like calendars and times?

**Comment by camsaul** [comment]
@atharvai it's an effort to get different databases to return consistent results. Some databases have weeks start on Monday while others have them start on Sunday. It would be nice if all databases followed ISO standards but unfortunately that's not the case. 

You're right about it being a hacky solution. We're always working on improving date bucketing and timezone support, so feel free to play around with the code and try the changes you suggested. If you find things work better without the hack, we'd love to have you as a contributor and would welcome a PR to improve the behavior 👍

**Comment by atharvai** [comment]
Thanks Cam for the reply. Does it make sense to make Metabase ISO compliant and make changes to questions against non compliant DBs follow this hack? It just seemed off to me that Metabase chose to deviate from ISO standard.

Will take a look at code base and try

**Comment by atharvai** [comment]
Noting the fix suggested here https://github.com/metabase/metabase/issues/2517

**Comment by atharvai** [comment]
I'm running master branch locally and testing out simple question. "Count of rows grouped by Week of Year and Year" However I am unable to select two groups based on same date field. 
![image](https://cloud.githubusercontent.com/assets/14027470/25993697/c4f9cfb8-3702-11e7-822a-ba601c7ed528.png)

However in version 0.23.1 (built on 2017-03-30) it is possible
![image](https://cloud.githubusercontent.com/assets/14027470/25993865/78697c38-3703-11e7-967e-12255bfdfb11.png)

I tried searching in issues and PRs here but didn't see any related changes. I noticed this with both a PostgresQL and Redshift database.

Can you give me any pointers?

**Comment by camsaul** [comment]
@atharvai, can you please open a separate issue for that? It's not related to this issue (#4910)

**Comment by denisesenguel** [comment]
..what makes even less sense in my head at all is that _week of the year_  and  _week_ seem to follow different logics as to when the week starts (see example below)

![Bildschirmfoto 2020-01-13 um 18 45 37](https://user-images.githubusercontent.com/17010657/72279579-b883ca00-3636-11ea-9a2b-03e13aed388f.png)
![Bildschirmfoto 2020-01-13 um 18 45 26](https://user-images.githubusercontent.com/17010657/72279586-bcafe780-3636-11ea-94f7-657f334fc4e9.png)

is that intended and if so.. why??

I'm working with ..
- Chrome 79.0 
- OS X 10.15.1
- Druid 0.16.1
- Metabase 0.33.7 hosted on Docker with internal Postgres database

**Comment by flamber** [comment]
While most of this issue is outdated and a lot has been fixed (different results etc), we're still handling the ISO differently.

0.41.1 with start of week to Monday (doesn't seem to make a difference) and tried several database types, but here's H2:
![image](https://user-images.githubusercontent.com/1447303/140733699-0ea0008d-f802-4ee2-8898-b5c418b1383d.png)
![image](https://user-images.githubusercontent.com/1447303/140733926-90826dd5-b37c-46c1-9e25-6706a34ac92a.png)

**Comment by qnkhuat** [comment]
I think we've got consistent results now.
For week of year: the 1st week of the year will start on the first `start-of-week setting` day of that year.

Every date before that will be considered the last week of last year. that is why you'll see the bucket Dec 30th 2018 -> 5th Jan 2019 when grouped by `Week` (assuming the Start of week  setting = Sunday )

H2
![Screenshot 2022-11-14 at 18 35 59](https://user-images.githubusercontent.com/25661381/201650328-5d731905-57f7-4305-8068-6187de8dcb84.png)

Postgres
![Screenshot 2022-11-14 at 18 38 58](https://user-images.githubusercontent.com/25661381/201650796-9e194f11-e8da-4090-8492-c1b9964b8673.png)
