### ISSUE TITLE
Unknown parameter when name label has accentuation - embedded data download

### ISSUE THREAD

**Issue by fer-batista** [metabase/metabase#49118]
### Describe the bug

Error on download data when the parameter label has accentuation.
Tested on static embedding.

[dbe7ab84-dd27-4f58-83a2-c7201c342f63] 2024-10-24T14:26:09-03:00 DEBUG metabase.server.middleware.log GET /api/embed/dashboard/eyJhbGciOiJIUxxxxxxxxxxx/dashcard/2570/card/2337/xlsx 400 6,9 ms (2 chamadas ao banco de dados) {:metabase-user-id 446} 
"Unknown parameter :nome_do_usuário."

![Image](https://github.com/user-attachments/assets/e1db1d06-7017-48a6-825a-28bffcededf7)

### To Reproduce

1. Create a question
2. Create a dashboard
3. Insert a filter and name it using accentuation like "usuários"
4. Embedded it
5. Try to download the data

### Information about your Metabase installation

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-10-23",
      "tag": "v1.51.1",
      "hash": "b8178a8"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.1.90+",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}

### Severity

P1

**Comment by WiNloSt** [comment]
Tested with v1.51.1 and v1.50.31.2. It only happened on v51.
