### ISSUE TITLE
Migrate existing click behavior to always include explicit target stage-number

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#49110]
Similar to #48734 but for click behavior in viz settings.

**Comment by metamben** [comment]
@kamilmielnik Where should these references show up?

**Comment by kamilmielnik** [comment]
> Looking at the code, I'm assuming a path like `["visualization_settings" "click_behavior" "parameterMapping" ["target" "dimension"]]`, where `parameterMapping` contains a map from IDs to records with `target` fields.

@metamben precisely. You can also run the app, create a new custom click behavior as a user would, and then inspect the network payload.

**Comment by metamben** [comment]
I was wrong, I missed `column_settings`.

So the path should be like `["visualization_settings" "column_settings" ["click_behavior" "parameterMapping" ["target" "dimension"]]]`, where `column_settings` is a map from column ref strings to column setting records containing `click_behavior`s, and  `parameterMapping` contains a map from IDs to records with `target` fields.

**Comment by kamilmielnik** [comment]
Closed by #49911.

@metamben please don't forget to close your issues ([1](https://github.com/metabase/metabase/issues/47304#issuecomment-2324196030), [2](https://github.com/metabase/metabase/issues/48441#issuecomment-2437481888), [3](https://github.com/metabase/metabase/issues/48884#issuecomment-2437482627), [4](https://github.com/metabase/metabase/issues/48734#issuecomment-2443425921), [5](https://github.com/metabase/metabase/issues/48613#issuecomment-2488602355)).
GitHub won't automatically close them if a PR is not targeted against `master`.
