### ISSUE TITLE
Drill Polish 3 - Grab-bag o nits edition

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4913]
This is a catch-all issue for iterative improvements to drill-through. Leave comments on weirdness below, and we'll synthesis all of it sometime next week and see what if anything should be changed

**Comment by salsakran** [comment]
it’s not obvious which of these is clickable

<img width="168" alt="screen shot 2017-04-27 at 5 47 09 pm" src="https://cloud.githubusercontent.com/assets/107439/25542048/cfc99f70-2c05-11e7-8f75-ca36c0677c36.png">

**Comment by salsakran** [comment]
I preferred it when “Zoom in” and “View this/these X” were on separate lines. Think we should have a different icon

<img width="336" alt="screen shot 2017-04-27 at 5 48 38 pm" src="https://cloud.githubusercontent.com/assets/107439/25542049/cfcb0f0e-2c05-11e7-9b27-e9b462bf4e8d.png">

**Comment by salsakran** [comment]
I should be able to click into a scalar and see “these orders” imo

<img width="306" alt="screen shot 2017-04-27 at 5 48 07 pm" src="https://cloud.githubusercontent.com/assets/107439/25542047/cfc929be-2c05-11e7-891a-6c7b496042a1.png">

**Comment by mazameli** [comment]
> it’s not obvious which of these is clickable

we could try the inequality symbols as words instead

> I preferred it when “Zoom in” and “View this/these X” were on separate lines. Think we should have a different icon

fair enough. i don’t feel strongly about this; i had just grouped them because it seemed like they were both “going into this item,” and I liked having fewer rows of actions. but we could just put it on the second row with one of the table icons or something.

> I should be able to click into a scalar and see “these orders” imo

yeah, good call.

**Comment by mazameli** [comment]
The spacing to the right of each action doesn’t seem like it’s changed yet, btw. should be 30px.

![image](https://cloud.githubusercontent.com/assets/2223916/25542229/7d002c36-2c06-11e7-98f6-ba84d46770a0.png)

More like this:

![image](https://cloud.githubusercontent.com/assets/2223916/25542320/dc97bed4-2c06-11e7-80bf-b76b828e2424.png)

**Comment by mazameli** [comment]
I don't think we should present sum (or sum by time) or avg for entity/primary key fields. I think there could be legitimate cases for min/max, and definitely for distincts.

![screen shot 2017-05-01 at 11 02 58 am](https://cloud.githubusercontent.com/assets/2223916/25588638/ed7dc064-2e5d-11e7-85b2-f5066e3df7da.png)

Incidentally, doing the `count by time` aggregation results in a weird QB state where it shows the name of the field as part of the aggregation, which is nonsensical (this is just count of rows in the orders table, for example):

![screen shot 2017-05-01 at 11 07 57 am](https://cloud.githubusercontent.com/assets/2223916/25588752/82e5168e-2e5e-11e7-9c48-c0a22cf09cfd.png)

**Comment by mazameli** [comment]
Pop over menu doesn't stay anchored if the window is resized:

![screen shot 2017-05-01 at 11 13 57 am](https://cloud.githubusercontent.com/assets/2223916/25588948/56d98308-2e5f-11e7-8b83-014c2148b80c.png)

**Comment by mazameli** [comment]
This guy's missing an icon. The sigma one maybe?

![screen shot 2017-05-01 at 11 02 41 am](https://cloud.githubusercontent.com/assets/2223916/25589164/6243d562-2e60-11e7-8e94-40e014409e29.png)

**Comment by mazameli** [comment]
There's a remaining bit of funkiness with the way table headings work:
- I don't think we want to show the up/down sort arrow anymore on hover
- The whole table cell appears to be a click target (since it triggers the hover state), but you can only click on the word itself. I think if and when we implement #4621, we'll probably want to have only the label itself be the click target. But if #4621 isn't part of 0.24, then the whole table heading cell should probably be a click target for the actions.

![screen shot 2017-05-02 at 9 54 07 am](https://cloud.githubusercontent.com/assets/2223916/25629233/b2e8723a-2f1d-11e7-8d7f-7f77883ebf7d.png)

**Comment by mazameli** [comment]
Would `count of rows by [field name]` be clearer if we labeled it simply `Distribution`?

**Comment by mazameli** [comment]
Sometimes when changing the granularity on a time series with a secondary category breakout, the breakouts get swapped, and instead of seeing time on the x-axis, I see something like product category, with each series representing a year.

**Comment by mazameli** [comment]
Zooming in when you're already at the `minute` granularity doesn't do anything, so perhaps we should remove that action when you're at that granularity.

**Comment by mazameli** [comment]
If I do "view this x" like "view this order" and there's only a single row, it feels like it would make sense to go straight to the single record / detail view.

**Comment by mazameli** [comment]
I'm really unclear what the logic is for when the "count of rows by [this field]" heading action appears (it's the action that I'm proposing we relabel as "Distribution"). I'd really love it to appear on category fields or even FK fields (like Product ID, so I can see the distribution of orders by product ID for example). 

As an example, for these columns, the action only appears in the Subtotal column but I don't understand why:

![screen shot 2017-05-05 at 11 45 34 am](https://cloud.githubusercontent.com/assets/2223916/25759700/6ac58aca-3188-11e7-93c1-4648bee5f32b.png)

**Comment by mazameli** [comment]
Looks like it might only appear for Category fields, and Subtotal is weirdly marked as Category. So Maybe I'm actually just proposing it also should appear for FK fields too.

**Comment by mazameli** [comment]
I think I should be able to break out by a number, especially now that we have binning. E.g., I'm viewing Count of Orders, and I want to see the distribution of orders by Subtotal.

<img width="436" alt="screen shot 2017-08-31 at 1 21 09 pm" src="https://user-images.githubusercontent.com/2223916/29943847-ed6b5bd4-8e4f-11e7-9443-340bb94c3da2.png">

**Comment by flamber** [comment]
This has a lot of ideas - some are fixed, others have their own issue, and some obsolete.
Should we close this?
- #10625 - Clickability
- "Zoom" and "View this/these X" are on different rows
- #4983 - Number drill-through "View these ..."

**Comment by mazameli** [comment]
Yeah, let's close this. In general I'm not really a fan anymore of these big uber issues with smaller issues inside of them. They linger forever and are hard to search on.
