### ISSUE TITLE
Items in the audit collection are sometimes suggested as stale

### ISSUE THREAD

**Issue by johnswanson** [metabase/metabase#49164]
### Describe the bug

Original report:

>  after moving unused items to trash I'm seeing "Sorry, you don't have permissions to see that" screen – which is weird because I'm an instance admin. Is that a bug?

### To Reproduce

Attempt to clean up the root collection with "include subcollections," making sure that an item in the audit collection has not been used since the cutoff date. When you attempt to move the discovered items to the trash, the `PUT` request to update the dashboard or card with `archived: true` will return a 403.

### Expected behavior

Do not suggest archiving items that can't actually be archived.

### Information about your Metabase installation

v51

### Severity

Fairly low, but this is a very annoying way to be introduced to a new feature.

**Comment by paoliniluis** [comment]
please post the logs
