### ISSUE TITLE
Problem with the docs

### ISSUE THREAD

**Issue by zjasper666** [metabase/metabase#49207]
The doc https://www.metabase.com/docs/latest/questions/query-builder/expressions/cumulative#queries-without-datetime-dimension said you will do the cummulative sum along the last dimension specified in the Group By block. However it's actually using the first one. Could you check?
![Image](https://github.com/user-attachments/assets/8ccb0682-e483-4b35-955e-9ade1aea0c77)

**Comment by paoliniluis** [comment]
if this is a question please create one on the forums, we don't answer questions here
