### ISSUE TITLE
unable to create custom expressions

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4920]
- Chrome Version 58.0.3029.81 (64-bit)
- OS X 10.12.4 (16E195)
- Metabase version: 0.23.1

- *Repeatable steps to reproduce the issue*
Try creating a custom metric. The cursor tends to stick to left as if the left key was always pressed. This seems like some issue which surfaced cause of either Chrome or OS.

@tlrobinson Seems like your forte.

**Comment by mazameli** [comment]
Seems to be the same issue as https://github.com/metabase/metabase/issues/4906. So I'll close this one as a dupe and update the title of that one.
