### ISSUE TITLE
The Fields List in "Learn about this Table" isn't very legible

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#49257]
### Describe the bug

The columns in the table of fields in the data reference no longer appear to be verified to the column.

### To Reproduce

1. Go to:  Databases ->Sample Database -> Learn about this table

![Image](https://github.com/user-attachments/assets/0d9a6109-8ab8-4dad-935b-07c8dac669e3)

### Expected behavior

The table should be pretty

### Information about your Metabase installation

Checked v51.1 and v50.30

### Severity

annoying

**Comment by iethree** [comment]
caused by https://github.com/metabase/metabase/pull/47747
