### ISSUE TITLE
Unable to start metabase

### ISSUE THREAD

**Issue by naxIO** [metabase/metabase#4927]
Im running metabase v0.23.1 as jar via system service on ubuntu using and external PG DB.  I'am aware of the operation guide and followed it throughly. 

I have the required values for metabase  in the env as well as the service file. 

Once starting I receive:

```
 05-02 10:40:21 INFO metabase.db :: Database Upgrade Required

NOTICE: Your database requires updates to work with this version of Metabase.  Please execute the following sql commands on your database before proceeding.

:done

Once your database is updated try running the application again.
```

So you can see there is no following sql command for me to run, never the less I tried the one in the operations guide.

Before I stopped the service, changed 
```MB_DB_AUTOMIGRATE=false ``` or is it no?

And inserting into the db
```
CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));
```

If I start metabase now.. it still fails and nothing happened on the DB. 

The error also happens when I start with a fresh and clean DB! The user has all permissions for this database!

I'm sure im using the external DB and not H2, I even deleted the local H2 files just to be sure.

I'm running out of ideas... please help me. Thanks

**Comment by camsaul** [comment]
hi @naxIO, if you set `MB_DB_AUTOMIGRATE=false` it won't automatically migrate your application database, which is why it's shutting down and giving you instructions for manually migrating the DB.

Unless you have a special case you probably don't want to be using `MB_DB_AUTOMIGRATE=false`, so I'd recommend just removing that env var and starting MB so it can migrate automatically.

**Comment by naxIO** [comment]
hi @camsaul and thanks for answering.

It seems I got confused by 
```
MB_DB_AUTOMIGRATE=false 
```

and seeing it with ``` yes ``` somewhere in the docs, but obviously the right value is ```true``` .

**Comment by camsaul** [comment]
@naxIO I don't think it says `MB_DB_AUTOMIGRATE=yes` anywhere in the dox (I just grepped the dox and the only reference to `MB_DB_AUTOMIGRATE` is the one about setting it to `false`).

Are you sure you saw that somewhere? I'd like to fix it if it indeed said that somewhere

**Comment by naxIO** [comment]
good comment, maybe it was stackoverflow or else. Thanks for looking this up.
