### ISSUE TITLE
Dashboard performance bottlenecks

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#4929]
While testing #4853 I noticed that loading dashboards with multiple cards and filters takes long time (> 10 seconds). Because I had earlier encountered similar issues also in other parts of dashboard UI, I decided to analyze the slow parts with Chrome profiler and collect my observations here.

### Common

- Calls of `updateIn` in [getMappingsByParameter](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/selectors.js#L100) account for slowdowns in dashboard loading and state changes (entering edit mode etc)

### Dashboard loading

- Two calls of `_.isEqual` in [shouldComponentUpdate](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/components/DashboardGrid.jsx#L68) take at least 85% of the total page load time (over 10 seconds in my heaviest dashboard)

### Graph renderers

-  When leaving dashboard edit mode, calling [HACK_parseTimestamp (LineAreaBarRenderer)](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js#L779) seems to cause a major garbage collection. I don't totally understand why this happens so here is the profiler trace for further analysis:

<img width="829" alt="gc" src="https://cloud.githubusercontent.com/assets/6034928/25627473/8d388eb8-2f17-11e7-8577-3f4b2629df7e.png">

### Entering/leaving dashboard edit mode

- Recalculation of styles in [Header.jsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/Header.jsx#L33) takes 50-100ms when entering/leaving edit mode. Could this be easy to optimize? (Not as serious as other perf concerns)

### Other

- @tlrobinson suggested that if the dashboard has lots of cards and only a few of them are visible at once, [react-virtualized](https://github.com/bvaughn/react-virtualized) could be useful for rendering only the visible cards

**Comment by tlrobinson** [comment]
I'm not sure we'll be able to use `react-virtualized` directly (I don't think they have an arbitrary grid like we have), but we could apply the same concept pretty easily.

Basically `DashCard` or `Visualization` could check to see if it's container element is visible and decide to render the content or not. We have some functions in `metabase/lib/dom` that can help with that.

We could even do the same for actually loading the data on long dashboards. At a minimum we should prioritize visible cards, then maybe prefetch cards below the fold.

**Comment by attekei** [comment]
The original issue (sluggish dashboards) was solved in #4943. We can later improve the performance of `Visualization` (affects both QB and dashboards) and `Dashcard` (affects only dashboards)  as mentioned also in https://github.com/metabase/metabase/pull/4943#issuecomment-299528280, but that is a separate discussion so I will close this issue.
