### ISSUE TITLE
Editing custom expressions for Contains filter with multiple values causes an error

### ISSUE THREAD

**Issue by alexyarosh** [metabase/metabase#49304]
### Describe the bug

If you use contains/endwith/startswith filter with multiple values, and then attempt to edit the custom expression, the filter block in the query builder breaks. It works fine when you only have one value in the contains/endwith/startswith filter 

https://github.com/user-attachments/assets/1211a637-3254-4383-ad6e-27707d037fa4

### To Reproduce

1. Start a query builder question from "Products"
2. Add a filter on `Category`: Contains `Gad`, `Wid`
![Image](https://github.com/user-attachments/assets/8dcbe900-b323-4c5a-83ba-1073799fd146)

4. Click "Add filter". (Note: another bug it seems that you have to click "Add filter" twice)
5. Once the filter is added, click on it to edit
6. In the filter editing thing, click on the "Back" button to get back to the one that has "Custom expression"
7. Click on "Custom expression"
8. Error:
![Image](https://github.com/user-attachments/assets/1880d50b-59df-4f7f-a344-9abe32929a04)

### Expected behavior

Opens a custom expression editor with the custom expression for the filter filled in, like it does when there's one value in the filter

### Information about your Metabase installation

51.1 and master `c3f9a20`

### Severity

P3?

**Comment by ranquild** [comment]
`format` function in the expression editor doesn't expect the special syntax for multi-value clauses with options

**Comment by kamilmielnik** [comment]
> `format` function in the expression editor doesn't expect the special syntax for multi-value clauses with options

True.

Also `contains` function does not support multiple arguments.
When this is attempted `Lib.diagnoseExpression` throws with `Error: No protocol method IAssociative.-assoc defined for type number: 58`

I don't think `contains(...) OR contains(...) OR ...` is acceptable. We need to update MLv2. I added BE label as well.

And we need to update [helper text](https://github.com/user-attachments/assets/79ff714e-55b7-4b6c-8f51-8a76a34857f0) which does not mention [the `"case-insensitive"` parameter](https://www.metabase.com/docs/latest/questions/query-builder/expressions-list#contains).

**Comment by ranquild** [comment]
@kamilmielnik this is not an MBQL lib unfortunately. This is legacy MBQL being tricky. We would have to handle it ourselves, there is nothing MBQL lib can do. See this https://github.com/metabase/metabase/blob/92d615073a3ba31710e26be9f2e83141352d1d1c/frontend/src/metabase-lib/v1/parameters/utils/mbql.js#L156
