### ISSUE TITLE
Type thunk action cases in embedding sdk reducers to fix type errors

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#49316]
There is a TypeScript error `Type instantiation is excessively deep and possibly infinite
` in `frontend/src/embedding-sdk/store/reducer.ts` in the [Mantine V7 branch](https://github.com/metabase/metabase/pull/49097). 

This is caused by TypeScript trying to compare the types for the `refreshTokenAsync.fulfilled` action case. We should explicitly type the `action` parameter in the `builder.addCase`'s callback, so we don't run into the stack depth issue.

![Image](https://github.com/user-attachments/assets/c827f2c4-66d8-4b7b-9eb8-06544861e149)

**Comment by npretto** [comment]
@heypoom heads up that I'm refactoring that code in https://github.com/metabase/metabase/pull/49214/, I'll open MY PR today in case you want to wait and avoid conflicts

**Comment by heypoom** [comment]
@npretto whoops, sorry just saw your comment. I had the PR https://github.com/metabase/metabase/pull/49352 here open, but it's very simple - just use Immer's syntax to avoid TypeScript type issues. It'd be fairly easy to replicate once your PR merges 🙏🏻
