### ISSUE TITLE
Embedding preview is broken on master

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#4933]
Not sure when this happened but its' causing an e2e test failure and preview has stopped working:

![screen shot 2017-05-02 at 11 01 11 am](https://cloud.githubusercontent.com/assets/1455846/25631936/d26af016-2f26-11e7-9f52-5e832472af63.png)

The backend is returning a 404 because there is no

```
GET /api/embed/card/:token/query/:garbage
```

endpoint. Not sure what the `:garbage` is for?

We support `GET /api/embed/card/:token/query` and `GET /api/embed/card/:token/query/:download-format` but `LU6OvzvcJtHr5OcaaJSiR0z6Bde52wIp8O1d5e7riuQ` is not a valid `:download-format`.

**Comment by camsaul** [comment]
what's also really weird is that the page is calling `/api/embed` instead of `/api/preview_embed` on the Preview page...

**Comment by camsaul** [comment]
@tlrobinson looks like `IS_EMBED_PREVIEW` is `false` because it's trying to use the `/api/embed` endpoints instead of `/api/preview_embed` endpoints when I preview an embed

**Comment by camsaul** [comment]
OK, so for

```javascript
export function getSignedPreviewUrl(siteUrl, resourceType, resourceId, params = {}, options, secretKey, previewEmbeddingParams) {
    const token = getSignedToken(resourceType, resourceId, params, secretKey, previewEmbeddingParams);
    return `${siteUrl}/embed/${resourceType}/${token}${optionsToHashParams(options)}`;
}
```

why does the preview URL use `/embed/` instead of `/preview_embed/`?

**Comment by tlrobinson** [comment]
It only uses `preview_embed` endpoints if it's loaded in an iframe inside of Metabase. In the e2e test it's just loading it in a top level page, but that should be ok because the e2e test publishes the embed first.

It looks like the `.` in the JWT token is conflicting with `.extension`.

**Comment by camsaul** [comment]
yeah i just came across that conclusion myself. I'm in the process of fixing it

the redirects made this all very confusing to debug :/

**Comment by camsaul** [comment]
yay it works now
