### ISSUE TITLE
Filters on a full screen dashboard with dark mode does not have a dark background

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#49332]
Reported in https://metaboat.slack.com/archives/C01LQQ2UW03/p1730246980582729

The filters on a full-screen dashboard with dark mode enabled does not have a dark background. We should make sure that filters has a matching background with the theme.

![Image](https://github.com/user-attachments/assets/49545f13-ef59-4717-9a44-45a0e6236e2e)

**Comment by WiNloSt** [comment]
This is caused by this line

https://github.com/metabase/metabase/blob/35d99ba88be996f9c95701c4afdeb25e17fae54b/frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.styled.ts#L12
from https://github.com/metabase/metabase/pull/46428
