### ISSUE TITLE
Large Pivot Tables fail to download (CSV) when Keep Data Pivoted is enabled

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#49353]
### Describe the bug

When you try to download a big Pivot table it seems to break (i cannot find the breaking limit though)

### To Reproduce

1. Go to -> Question -> Sample Database and Create a large Table like so:

![Image](https://github.com/user-attachments/assets/434b4a80-64e8-4afe-bac7-69fba448d0f0)

2. Turn it into a Pivot Visual and set the following Rows and Measures:

![Image](https://github.com/user-attachments/assets/093be1dd-adda-492f-b7d8-6895082fc32b)

3. Try to Download the Pivot as a CSV with the Keep Data Pivoted enabled (the error doesn't happen when the toggle is disabled):

![Image](https://github.com/user-attachments/assets/89dd5cad-d3dd-425e-866f-b3a956385cf2)

The file might not download, and the export causes CPU spiking
https://github.com/metabase/metabase/issues/49977#issuecomment-2477094397

There is [question on stats ](https://stats.metabase.com/question/20344-large-pivots-break-download-tony)for this to test it out

### Expected behavior

The download works or we explain why it doesn't

### Information about your Metabase installation

Version 51

### Severity

Even though this is new functionality it will kind of break current implementation since by default the Keep Data Pivoted is enabled and users will notice the download to start failing

**Comment by Tony-metabase** [comment]
@adam-james-v this is still a problem even though it looks like the fix is merged ... If you try to download the question i have created on stats it still fails with the same error

**Comment by mdjmay4** [comment]
@adam-james-v @Tony-metabase I still get this issue, the PR that closed it seems to be focused on the XLSX export, not the CSV one
