### ISSUE TITLE
We should list deactivated SSO-created accounts and let admins restore them from the UI

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4936]
I'm too scared to try this on any of our actual Google-auth-created accounts, but I think it might be the case that if you use the `remove` action on an account created via Google Auth that there's no way to restore that account, and thus that user can never log into metabase with that Google account again.

If I'm right about that, I'm going to change this issue to be a more general proposal about creating a system to display "deactivated" SSO-created accounts (be they Google, LDAP, Okta in the future, etc.), and have a way to restore accounts from that list. I mentioned this in https://github.com/metabase/metabase/pull/4340 and just wanted to have a place to discuss this specific problem.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
I think an admin can reënable those accounts just like any other account. That's why we have an issue to give you an appropriate error message when your Google Auth account is disabled (#3245)

You could always create an account with a `maz+1` email or something like that and try it out

**Comment by salsakran** [comment]
we currently don't allow you to see or re-enable deactivated accounts. It's kind of ghetto

**Comment by camsaul** [comment]
if you send an invite to an inactive account it get reäctivated I think

**Comment by edenzik** [comment]
For what it's worth, I also had a similar problem of users showing up as "deactivated" and then can't log in once LDAP is set up. I had to hack around with the following queries to purge deactivated users:

```
delete from activity where user_id in (select user_id from core_user where ldap_auth='f');
 delete from permissions_group_membership where user_id in (select user_id from core_user where ldap_auth='f');
 delete from core_session where user_id in (select user_id from core_user where ldap_auth='f');
 delete from view_log where user_id in (select user_id from core_user where ldap_auth='f');
 update report_card set creator_id=[some new owner];
 update collection_revision set user_id=[some new owner];
 update report_dashboard set creator_id=[some new owner];
 update report_cardfavorite set owner_id=[some new owner];
 update pulse set creator_id=[some new owner];
 update report_card set made_public_by_id=[some new owner];
 update report_dashboard set made_public_by_id=[some new owner];
 update permissions_revision set user_id=[some new owner];
 delete from core_user where ldap_auth='f';

```

Note that "some new owner" is in order to re-parent their dashboards and collections. Just choose anybody with LDAP auth.

**Comment by mazameli** [comment]
Came up with a quick spec + design for this.

**What this should do:**
- In the admin panel, if I have any deactivated users I should see a list of deactivated accounts.
- I should be able to restore any deactivated user (email-based, Google Auth, or LDAP).
- When one of these users is restored, their previous user group assignments are restored.

**Details:**
- The `Remove` menu item in the active user context menu should be changed to `Deactivate`
- The deactivation modal should no longer say "This can't be undone."

**Design:**

![deactivated_accounts](https://user-images.githubusercontent.com/2223916/32757038-35d84e00-c892-11e7-9989-63e33b4d1b0b.png)

![restore_confirm](https://user-images.githubusercontent.com/2223916/32757134-b3593d94-c892-11e7-99b3-96a79ff1b7af.png)

**Comment by salsakran** [comment]
done in #7481
