### ISSUE TITLE
Remove ctrl+L shortcut for going to a line number

### ISSUE THREAD

**Issue by vkarpov15** [metabase/metabase#4942]
ctrl+l is the chrome shortcut for selecting the text in the URL bar, I use it a lot. But, whenever I happen to be in a metabase window and the SQL editor has focus, metabase throws up a spammy alert:

![image](https://cloud.githubusercontent.com/assets/1620265/25644902/b46d4542-2f66-11e7-95d3-ace7eb2fba18.png)

I appreciate the fact that this may be a useful feature, but can we please make it not conflict with such a commonly used chrome keyboard shortcut?

**Comment by camsaul** [comment]
We could always change it to `M-g g` for the benefit of our Emacs users

**Comment by Varunram** [comment]
@camsaul Could you lead me as to where I must look for doing this change? I'm new here, so I'm just getting familiar. Thanks!

**Comment by camsaul** [comment]
@Varunram that shortcut is a feature of the [ACE Editor](https://github.com/ajaxorg/ace) which we're using for our SQL editor, so if you want to remove that your best bet might be opening an upstream PR with them

**Comment by Varunram** [comment]
Oh, alright. Thanks for your time!

**Comment by camsaul** [comment]
Just a heads up I'm not sure they'd want to merge a PR to remove one of their features

**Comment by Varunram** [comment]
I got lost while searching for where to make the changes. The codebase is so big, its taking a while :)

**Comment by flamber** [comment]
Not sure when it was changed, but we've upgraded ACE multiple times. I cannot reproduce on 0.35.3
