### ISSUE TITLE
Databricks Catalog is not Validated when the Connection is Set Up

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#49444]
### Describe the bug

When you set up a Databricks connection a catalog is required - but you can provide an invalid catalog and the connection will still save, the sync modal will pop up and it looks like it's syncing successfully. You have to go to the logs to identify that there's an error.

### To Reproduce

1. Add a Databricks connection to v51
2. Provide the name of a catalog that doesn't exist

### Expected behavior

The catalog should be validated

### Information about your Metabase installation

v51

### Severity

annoying

**Comment by ranquild** [comment]
This is a common flow + the "successful" sync modal is misleading; hard to debug; thus P1.
