### ISSUE TITLE
Verified model isn't showing up in typeahead list when looking for models to select from in native editor

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#49454]
### Describe the bug

In native editor, I am trying to find the Account model, which is a verified model by typing {{#account}} but nothing shows up. This does work for some models, so it seems to be specific to the instance data. This can be reproduced in Stats using the Analytics Data Warehouse connection. 

```
select * from {{#account}}
```

Normally, I don't report issues only in Stats, but adding one just to make sure someone look at it as it is a **potential release blocker**.  Someone should investigate to see what the real problem is and then update this issue. 

### To Reproduce

1. Go to Stats
2. Open native editor for Analytics Data Warehouse and try to select from the verified Account model by typing: `select * from {{#account}}`
3. Notice nothing shows up -- no typeahead selection preview

### Expected behavior

Typeahead selection preview box should show up with the Account model as it is verified. 

### Logs

n/a

### Information about your Metabase installation

Master @ Postgres

### Severity

Medium as it makes it hard to select from other models in native editor for new users that don't know the workaround (could be worked around by manually typing the model id).

**Comment by maxzheng** [comment]
@romeovs This still doesn't work for the Account model (not a metric) in Stats? Is the fix not deployed to Stats yet?

**Comment by romeovs** [comment]
@maxzheng can you have another look, stats has been deployed now.

**Comment by maxzheng** [comment]
@romeovs Yep, it's working now. Thanks for fixing this! Hopefully we have tests to prevent regression as this has happened before.
