### ISSUE TITLE
SDK modal z-index loses to other element from other stacking contexts

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#49466]
In this case `z-index: 3` of the modal is losing to Mantine's [AppShell](https://mantine.dev/core/app-shell/) (z-index: 100)

![Image](https://github.com/user-attachments/assets/c79ef516-eff5-42f3-b338-d0df1b324977)

Maybe modal is a kind of type that we could justify having a very high `z-index`?

**Comment by WiNloSt** [comment]
This seems to be fixed by #49442 in my setup.

![Image](https://github.com/user-attachments/assets/c06963b1-575f-47d0-94ac-60c7af15c667)

**Comment by albertoperdomo** [comment]
Can this be closed @WiNloSt ?

**Comment by heypoom** [comment]
@albertoperdomo the above PR (https://github.com/metabase/metabase/pull/49442) isn't merged yet, so we should wait until the PR is merged to close this issue.
