### ISSUE TITLE
MetabaseProvider should not reload the store when its parent component re-renders

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#49482]
When the parent component re-renders, the underlying Metabase components under `MetabaseProvider` will show the loading indicator again. This happens in every re-render. This is caused by how we [re-create the store](https://github.com/metabase/metabase/pull/48071/files#r1776753555) by default in MetabaseProvider.

### How to reproduce

Try rendering this code snippet, and click on the `reload (+1)` button. You can see the loading spinner triggers every time you click the button. If you move the `store` variable to a singleton, this issue goes away.

```tsx
const Example = (props: Props) => {
  const [_, forceReload] = useReducer(x => x + 1, 0);

  return (
    <div style={{ padding: "1rem" }}>
      <button onClick={forceReload}>reload (+1)</button>
        <MetabaseProvider config={storybookSdkDefaultConfig}>
          <InteractiveQuestion {...props} />;
        </MetabaseProvider>
      </div>
    </div>
  );
}
```

### Related issues

This also causes an issue in the auth code PR (https://github.com/metabase/metabase/pull/49214), where the component shows "Initializing..." whenever we navigate back and forth between pages.

![Image](https://github.com/user-attachments/assets/c3faa6ca-4f74-4e4f-8ea0-f59ffda8bdff)

**Comment by heypoom** [comment]
Closing this as https://github.com/metabase/metabase/pull/49492 has been merged already, cc @npretto

**Comment by npretto** [comment]
Thanks @heypoom , weird that it didn't pick up the "Fixes" keyword, [it should be a supported keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
