### ISSUE TITLE
Return key triggers events outside of the Metabot

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#49488]
### Describe the bug

When using the LLM Metabot in chill mode, since the `return` key is bound to show row details, it triggers _that_ every time I send a request.

### To Reproduce

1. Go to any table or model
2. Open the Metabot
3. Type anything
4. Hit `return`

### Expected behavior

We should probably stopEventPropagation or something when the user hits `return` in the Metabot text intput.

### Information about your Metabase installation

https://github.com/metabase/metabase/pull/48814 @ `8cbb0f4d442c71c733234c3954cfe11ee9d29a42`

### Severity

P1

**Comment by sloansparger** [comment]
Fixed in `0dabbb8071451dbedca1ed83e6706061607b9ee3`
