### ISSUE TITLE
Dashboard embedding - passing a value into an editable field, makes the filter widget disappear

### ISSUE THREAD

**Issue by berill** [metabase/metabase#49508]
### Describe the bug

We have a dashboard with two editable mandatory fields:

- start_date
- end_date

![Image](https://github.com/user-attachments/assets/997c7de5-c971-4665-9d84-024908ca6021)

if set from the requesting code:

```python
params={
            # for whatever reason, setting this make them disappear from the widget, even though, as per the documentation, they should be ok
            "start_date": start_date.strftime("%Y-%m-%d"),
            "end_date": end_date.strftime("%Y-%m-%d"),
        },
```

they are applied, but the settings are not changeable by the user:

![Image](https://github.com/user-attachments/assets/6a9ef3c8-08b4-45bd-9694-68cd05720b67)

if we are not passing them, they are correctly shown:

```python
params={
            "project_id": metabase_project_id,
        },
```

![Image](https://github.com/user-attachments/assets/ab2bb126-745c-4c05-b120-a3d91eeed412)

### To Reproduce

1. Create a question that uses two variables `start_date`, `end_date`
2. Add the question to the dashboard
3. Add two filters:
     1. Date Picker, Single Date, and apply it to the questions
4. Make the dashboard embeddable
5. Set the two parameters as `Editable`
6. Try and embed them with and without passed in variables

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "sqlite"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-23",
      "tag": "v0.51.1",
      "hash": "b8178a8"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8-post-Ubuntu-1ubuntu320.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8-post-Ubuntu-1ubuntu320.04",
    "os.name": "Linux",
    "os.version": "5.15.0-1071-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}

### Severity

Blocking the correct usage of the embedded dashboards

**Comment by ranquild** [comment]
This looks like the expected behavior to me - you can't change values in the jwt token. To be confirmed with Product

**Comment by mngr** [comment]
Yes, this is what happens when you pass parameter values in the jwt token, as explained [here](https://www.metabase.com/learn/metabase-basics/embedding/securing-embeds).
To pass the default filter values but allow editing it's possible either to set them [in the dashboard settings](https://www.metabase.com/docs/latest/dashboards/filters#set-a-default-filter-value) or [in the url](https://www.metabase.com/docs/latest/embedding/static-embedding-parameters#populating-an-embedded-filter-widget-with-a-default-value).

**Comment by berill** [comment]
Hi @ranquild ,

thanks for the quick turn around on this; you can even see from the documentation that it is not what is "expected":

- "locked": hidden from end-users but you can set their values from the app
- "editable": so end users can see them and modify them

How do you propose for us to then give them a default start and end date which is relative to now (can't do relative on single date field defaults) and that they can edit as they please?

**Comment by berill** [comment]
Sorry, had replied before the UI updated with @mngr reply. Will try the URL way, thanks!
