### ISSUE TITLE
Centralized question store

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#4951]
One issue I run into a bit when working on the frontend of ye olde Metabase is (or at least have run into quite a bit recently) is the fact that we store the current working question in one part of our redux store, (QB) and the list of questions for the instance in a different part, and other lists of questions in yet other parts. The end result is a question being loaded in the QB doesn't necessarily mean it's loaded in the question list or vice versa which means we can't always re-use question actions, and overall it just becomes a bit hard to reason about.

Similarly, it probably means we're over fetching data when we load things like the activity feed or recents, requiring us to do another call to load questions when a user visits the Question / Collection page when we might already have some of the data locally. 

In a slightly more ideal world it'd be great to be able to just keep a reference to a question in the QB store and work off of one object rather than having several copies floating around (things get a bit wobblier when talking about unsaved or modified queries I realize but there are definitely solutions there)

A dumb overly idealistic store might look like this.
```
qb: {
  focusedQuestion: 123,
},
recents: {
   { type: 'question', id: 123, }
},
activity: {
   { storyType: 'archived', type: 'question', targetId: 456 }
},
questions: {
   123: { ... },
   456: { ... }
}

We're already using normalizr a bit but I think we might want to take another look at whether we're "doing it right" (TM) and more importantly if we're doing it right for our needs.

**Comment by kulyk** [comment]
#25102 fixed the QB to use the Questions entity to fetch saved questions. This should guarantee that QB and question entities list should stay in sync
