### ISSUE TITLE
Non-Admin user found error in search box "PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. "

### ISSUE THREAD

**Issue by unnyns-307** [metabase/metabase#49526]
### Describe the bug

Whenever non-admin user search on search box on home page or search box to add question, metabase end up with error 

> 'PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. '

### To Reproduce

1. Set your account as non-admin role
2. Click on search box and type any value
3. Enter and wait for result

### Expected behavior

Metabase be able to show the related item

### Logs

![Image](https://github.com/user-attachments/assets/d4f75a08-c41b-43ea-8f6a-467b61ebac77)

### Information about your Metabase installation

- Metabase Version: v0.48.4-SNAPSHOT

### Severity

Urgent

**Comment by unnyns-307** [comment]
@paoliniluis Hi, thank you so much for checking on this. We need some information to track and understand the issue better.
Would you mind elaborating us a bit more what is the root cause of this issue and the issue was resolve in which version?

**Comment by paoliniluis** [comment]
@unnyns-307 my bad, this is a duplicate of https://github.com/metabase/metabase/issues/33037
