### ISSUE TITLE
Row visualization settings sidebar crashes

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#49529]
### Describe the bug

![Image](https://github.com/user-attachments/assets/18eed282-cebb-4d47-b1af-a8ccfcb6f432)

### To Reproduce

1. New > Question > Orders > Visualize
2. Change viz type to Row
3. Open viz settings sidebar
4. Select some Y-axis 
5. Click "Add series breakout" and select some Y-Axis

Sidebar crashes

### Information about your Metabase installation

master, 518e79b8fb292ba17b402042b05ccdfb64b30ad6

### Severity

P1

### Additional context

Error in JS console: `TypeError: Cannot read properties of undefined (reading 'filter')` coming from [here](https://github.com/metabase/metabase/blob/9b4d3d2b2ebb24975ed8a673f86e15d9417d1215/frontend/src/metabase/visualizations/components/settings/ChartSettingSeriesOrder.tsx#L83)

**Comment by kamilmielnik** [comment]
I also got a crash from [here](https://github.com/metabase/metabase/blob/dbdef76e639d3f5857f8e787d5435530f0ebaac7/frontend/src/metabase/visualizations/lib/settings/graph.js#L175) because `transformedSeries` was `undefined` but I can't remember repro steps.

**Comment by romeovs** [comment]
This is a dupe of https://github.com/metabase/metabase/issues/49523
