### ISSUE TITLE
Dashboards shouldn't have unnecessary padding

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4952]
There is extra padding at the bottom of dashboards that doesn't need to be there. @attekei told me: "it’s basically because the QB and dashboard currently (unnecessarily) share the same styles and QB has some special requirements [I think for spacing visualizations]."

**Notice the scrollbar here:**

![screen shot 2017-05-03 at 12 03 08 pm](https://cloud.githubusercontent.com/assets/2223916/25676912/beca4fe8-2ff8-11e7-9673-90cdffc318c7.png)

**There should be padding below the last cards, but not this much. Should be more like how much margin/padding there is on the left and right:**

![screen shot 2017-05-03 at 12 03 37 pm](https://cloud.githubusercontent.com/assets/2223916/25676942/d9721902-2ff8-11e7-9963-a8f3cbcea6c6.png)

**Comment by mazameli** [comment]
Looking at it more, I think this might have to do with the usage of `minHeight: "100%"` in `Dashboard.jsx`. I say this because I was trying to get the new Dashboards list page to have the same colored background as the dashboard page itself and so I applied this style to the `LoadingAndErrorWrapper` component the way Dashboard.jsx does, and I see the same padding problem happening now.

**Comment by mazameli** [comment]
Oddly, sometimes dashboards also don't have _enough_ padding after the last row of cards:

![screen shot 2017-05-03 at 12 30 45 pm](https://cloud.githubusercontent.com/assets/2223916/25717453/5b06046a-30b7-11e7-8e34-c5ad8e9cf53f.png)

**Comment by salsakran** [comment]
closed via #4987
