### ISSUE TITLE
Google chat webhook - crateChannel & testChannel not working

### ISSUE THREAD

**Issue by FoltanMilos** [metabase/metabase#49533]
Edit.: this is a limitation of our implementation, but it isn't a bug.
This will be fixed with custom notification templates.

### Describe the bug

In section notification channels, in admin, section webhooks for alerts - its not possible to add google chat as webhook destination. Error response says "message": "Message cannot be empty" and creation of this webhook fails. Is there any possible workaround or fix?

### To Reproduce

1. Go to 'admin -> notfication channels -> webhooks for alerts '
2. Click on 'add a webhook'
3. Put url to google chat webhook and press send test button -> see error
4. Fill formular fields 'give it a name' and 'description' and press 'create destination' -> see error

### Expected behavior

Create channel works

### Logs

{
    "via": [
        {
            "type": "clojure.lang.ExceptionInfo",
            "message": "Unable to connect channel",
            "data": {
                "status-code": 400,
                "request-status": 400,
                "request-body": "{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Message cannot be empty.\",\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n"
            },
            "at": [
                "metabase.api.channel$test_channel_connection_BANG_",
                "invokeStatic",
                "channel.clj",
                41
            ]
        }
    ],

### Information about your Metabase installation

each browser, version v0.51.1.3 

### Severity

HOTFIX

**Comment by luizarakaki** [comment]
This is a limitation, not a bug.

We currently don't support customizing the webhook payload. This will be possible in a future release.
You can check the [current payload schema here](https://www.metabase.com/docs/latest/configuring-metabase/webhooks).

An easy workaround is to create a lambda function or add Zapier to translate our payload into the Google Chat expected payload.

**Comment by ipapast** [comment]
> This is a limitation, not a bug.
> 
> We currently don't support customizing the webhook payload. This will be possible in a future release. You can check the [current payload schema here](https://www.metabase.com/docs/latest/configuring-metabase/webhooks).
> 
> An easy workaround is to create a lambda function or add Zapier to translate our payload into the Google Chat expected payload.

Hi, do you have a link where we can collow this feature (customising payload)?

**Comment by paoliniluis** [comment]
most probably you need https://github.com/metabase/metabase/issues/9966

**Comment by ipapast** [comment]
> most probably you need [#9966](https://github.com/metabase/metabase/issues/9966)

I'm not sure it's exactly the same. I'd like to be able to customise the payload of the webhook.
