### ISSUE TITLE
No tooltip anymore in static embedded bar chart

### ISSUE THREAD

**Issue by nicovl-rombit** [metabase/metabase#49537]
### Describe the bug

Regression detected when upgrading Metabase from v1.50.27 to v1.51.1 and the issue persists in v1.51.2:

In the Metabase editor a tooltip appears on hover in a bar chart:

![Image](https://github.com/user-attachments/assets/a35a83a0-c7af-4191-bb3b-d4387db2d4b7)

But once the dashboard is embedded statically the tooltip is not displayed anymore when hovering the mouse pointer on the same bar:
![Image](https://github.com/user-attachments/assets/d883a13c-99fa-42b3-a324-d6f0ba507ed5)

### To Reproduce

1. Create a bar chart with a native query question
2. Hover on a bar when static embedded

### Expected behavior

A tooltip should popup giving more value details.

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-10-23",
      "tag": "v1.51.1",
      "hash": "b8178a8"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.217-205.860.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}

### Severity

major

**Comment by robswanLL** [comment]
Reproducible on 0.51.2 docker self-hosted

**Comment by WiNloSt** [comment]
I tested on both `1.51.1` using H2 and `0.52.2` using H2 and PostgreSQL.

Using this question
```sql
SELECT
  DATE_TRUNC('month', "public"."orders"."created_at") AS "created_at",
  "products__via__product_id"."category" AS "products__via__product_id__category",
  COUNT(*) AS "count"
FROM
  "public"."orders"
 
LEFT JOIN "public"."products" AS "products__via__product_id" ON "public"."orders"."product_id" = "products__via__product_id"."id"
GROUP BY
  DATE_TRUNC('month', "public"."orders"."created_at"),
  "products__via__product_id"."category"
ORDER BY
  DATE_TRUNC('month', "public"."orders"."created_at") ASC,
  "products__via__product_id"."category" ASC
```
Set the viz type to "Line" and changed the display to stacked, and I can still hover the embed.

![Image](https://github.com/user-attachments/assets/623b77e7-29ac-4491-8e6d-c51cc395856d)

**Comment by npretto** [comment]
@nicovl-rombit thanks for reporting this. Unfortunately I also wasn't able to reproduce this on `v1.51.1 `, could you give us some more details?
Some info that could help use reproduce and fix this faster:
- does this happen only on sql queries or also on queries create via the UI editor?
- does this happen on public links?
- does it happen only on data coming from postgres?

**Comment by YvesBos** [comment]
It seems to be related to static embedding in combination with `iframe-resizer`, tooltips work fine when not resizing the iframe but that obviously introduces other issues. The issue persists even when upgrading to the latest `iframe-resizer` version.

**Comment by nicovl-rombit** [comment]
@npretto are you using the `iframe-resizer` when trying to reproduce this issue on your local dev environment?

**Comment by npretto** [comment]
Thanks to both, we were able to reproduce the issue with `iframe-resizer` and we're investigating.

It seems like without the iframe resizer the tooltip container has this size
![Image](https://github.com/user-attachments/assets/97bff20a-70b2-4bbe-ab22-7592560b802e)

but with the iframe resizer it's moved to the bottom of the page with height 0:
![Image](https://github.com/user-attachments/assets/1dfaff71-8b7c-440d-9a6a-47bb1229033a)

**Comment by WiNloSt** [comment]
This is caused by https://github.com/metabase/metabase/pull/46359, and https://github.com/metabase/metabase/pull/49964 should fix it.
