### ISSUE TITLE
Row limit doesn't work in Firefox by clicking arrows

### ISSUE THREAD

**Issue by juheok** [metabase/metabase#49587]
### Describe the bug

If You make a new question and set the row limit by clicking (not by entering value), it returs all rows in the table.

### To Reproduce

1. Go to 'New Question => [Sample Database] =>Accounts'
2. Click on 'Row limit => click the arrows to increase value in field (for example "3")'
3. Click "Visualize"
4. It lists all rows, not the number you wanted

- If you enter the number you want, then row limit works
- Works in Chrome
![Image](https://github.com/user-attachments/assets/7fc0a031-0041-4fc1-8e7d-21940f4a623f)

### Expected behavior

It should return as many rows I'd wanted, not all

### Information about your Metabase installation

{
  "browser-info": {
    "language": "fi-FI",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "h2",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-cloud",
    "version": {
      "date": "2024-10-15",
      "tag": "v1.50.30",
      "hash": "a49cb77"
    },
    "settings": {
      "report-timezone": "Europe/Helsinki"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}

### Severity

annoyuing

**Comment by ranquild** [comment]
Yes, currently the row limit is updated on blur.
