### ISSUE TITLE
Adjust the diagnostics dialog towards filing a bug (vs downloading diagnostics)

### ISSUE THREAD

**Issue by thebiglabasky** [metabase/metabase#49586]
**Context**
The current diagnostics dialog is oriented towards downloading (and reviewing) a JSON file containing diagnostics, which are eventually useful to file a bug.

We'd like this dialog to be about filing a bug that contains the diagnostics information, along with extra context users could add themselves, so the bug could be more easily filled.

**Current dialog**
![Image](https://github.com/user-attachments/assets/c98eb33a-1ad6-4079-86bb-0091df5175ae)

**Proposal**
Update the dialog's title to "Report a bug"
Add a "Context" free form text area with a placeholder "Please describe your issue and steps to help us reproduce it"
Place the diagnostics option below, possibly in a toggled area to ensure most context remain ticked by default
For now keep the "Download" action the main one for end users

**Comment by thebiglabasky** [comment]
[Figma designs](https://www.figma.com/design/Hnb7RXZaL4gMjINWQPjhhf/Bug-reporting?node-id=14001-6934&t=iHy3stv3hBUcYvOL-4)

**Comment by filiphric** [comment]
update: the issue is now on PR, I need to update tests so that they reflect the newly added buttons and textarea

**Comment by filiphric** [comment]
tests are done, waiting for peer review
