### ISSUE TITLE
Introduce a Cmd/Ctrl + K command called "File a bug"

### ISSUE THREAD

**Issue by thebiglabasky** [metabase/metabase#49585]
People should also be able to report a bug via the Cmd/Ctrl + K command.
Flow:
1. Cmd or Ctrl + K
2. Type "bu" or "report" (or whatever else matches "Report a bug")
3. Select "Report a bug"
4. Pop the diagnostics dialog

**Comment by thebiglabasky** [comment]
[Figma designs](https://www.figma.com/design/Hnb7RXZaL4gMjINWQPjhhf/Bug-reporting?node-id=14001-6211&node-type=frame&t=iHy3stv3hBUcYvOL-11)

**Comment by filiphric** [comment]
currently blocked by https://github.com/metabase/metabase/pull/49875
