### ISSUE TITLE
Add "File a bug" option to the top-right cog menu

### ISSUE THREAD

**Issue by thebiglabasky** [metabase/metabase#49584]
We want to make it more obvious that people can report bugs directly from the interface. To that end, we should add a new menu entry to the "cog" menu at the top right, between "Help" and "About Metabase" called "Report bug". This would open the Diagnostics dialog as it exists today

**Comment by thebiglabasky** [comment]
[Figma designs](https://www.figma.com/design/Hnb7RXZaL4gMjINWQPjhhf/Bug-reporting?node-id=14001-5996&t=iHy3stv3hBUcYvOL-4)

**Comment by filiphric** [comment]
currently blocked by https://github.com/metabase/metabase/pull/49875
