### ISSUE TITLE
Adapt browser logs to JSON format

### ISSUE THREAD

**Issue by thebiglabasky** [metabase/metabase#49594]
Have a place to display browser logs. Ideally allow searching into them (can be postponed if not straightforward).
This is mostly about adapting the existing log viewer from https://metabase-debugger.vercel.app/ to the new JSON format

**Comment by filiphric** [comment]
I added this to "in progress" along with https://github.com/metabase/metabase/issues/49664 and hadn’t realized this is something else. console logs from browser are already part of debugger and are searchable (as is everything in debugger)
