### ISSUE TITLE
Non-admins creators can't change question/dashboard cache settings

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#49597]
### Describe the bug

[Context in Slack](https://metaboat.slack.com/archives/C01LQQ2UW03/p1730838603477989)

We are requiring users to be admins to change single dashboard/question cache settings.
Any creator with curate access should be able to change cache settings.
Admin-level is required to configure root/db-level cache.

### To Reproduce

1. As a non-admin, go to cache settings on any question/dashboard
2. Trying to change the cache settings return an error

### Expected behavior

Any non-admin creator can change cache settings on questions and dashboards

### Information about your Metabase installation

v1.50.6 until v1.51.1

### Severity

P2

**Comment by noahmoss** [comment]
Fixed by https://github.com/metabase/metabase/pull/49804
