### ISSUE TITLE
[BUG] using filter 'month & year' in dashboard missing last 1 day of month.

### ISSUE THREAD

**Issue by evil7** [metabase/metabase#49641]
**Describe the bug**

using filter 'month & year' in dashboard missing last 1 day of month. 

![Image](https://github.com/user-attachments/assets/44889480-7872-4ded-ba32-5fb663044b0f)

E.g.: pick ' Oct - 2024 ' then the table just add filter maybe `datetime > 2024-10-01T00:00:00 and datetime < 2024-10-31T00:00:00` I guess.

![Image](https://github.com/user-attachments/assets/863e053e-d928-4830-84df-27953e3f3118)

Then. the table on this dasboard only show 30 days (missing last 1day).

![Image](https://github.com/user-attachments/assets/376cb8a6-2b1c-4661-b708-cb925892b20d)

**To Reproduce**
1. create any of date list table.
2. add table to a dashboard.
3. add a 'month & year' filter to this dashboard.
4. pick a month and last 1day missing at table.

**Expected behavior**

**Screenshots**

maybe `datetime > 2024-10-01T00:00:00 and datetime < 2024-10-31T00:00:00` in fitler ??

maybe should fix to be `<= month range2` or `< dateAdd([range1], '+1', 'month')` I think... 🤔

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "oracle"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-04",
      "tag": "v0.51.2",
      "hash": "8bdb22c"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.0 (Debian 17.0-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "4.18.0-553.22.1.el8_10.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  }
}
```

**Comment by evil7** [comment]
when I trying filter `Year and Month` or `this month` / `this week` / `Today` for testing. I found this `query` log of web response json:

```sql
-- E.g: filter today
WHERE
    ( xxx_some_user_filter_xxxx )
    AND ( 'source'.'REGISTER_TIME' = TRUNC(CURRENT_TIMESTAMP, 'dd') )
```

But in this main model. I have checking it's already set the `REGISTER_TIME` type to `Creation timestamp`.

So I think maybe this dashboard filter should be fix like:

```sql
-- trunc both side to fix
AND ( TRUNC(source.REGISTER_TIME, 'dd') = TRUNC(CURRENT_TIMESTAMP, 'dd') )
```

then it will work fine will my tests.

## my test

```sql
-- oracle 11g
WITH
  source AS (
    SELECT
      (TRUNC(SYSDATE) + DBMS_RANDOM.VALUE (0, 1)) AS REGISTER_TIME
    FROM
      dual
    CONNECT BY LEVEL <= 10
  )
SELECT
  REGISTER_TIME,
  TO_CHAR(REGISTER_TIME, 'yyyy-mm-dd hh24:mm:dd') AS register_time_to_char,
  TO_CHAR(TRUNC(REGISTER_TIME, 'dd'), 'yyyy-mm-dd hh24:mm:dd') AS register_trunc_dd_to_char,
  TO_CHAR(TRUNC(CURRENT_TIMESTAMP, 'dd'), 'yyyy-mm-dd hh24:mm:dd') AS filter_trunc_dd_to_char
FROM
  source
WHERE
--   source.REGISTER_TIME = TRUNC(CURRENT_TIMESTAMP, 'dd') -- the BUG happend here!
  TRUNC(source.REGISTER_TIME, 'dd') = TRUNC(CURRENT_TIMESTAMP, 'dd')
```

![Image](https://github.com/user-attachments/assets/d4acf789-6359-4f94-a3dd-91a6f4c12bbf)

```sql
-- postgresql 17
WITH source AS (
    SELECT
        (CURRENT_DATE + INTERVAL '1 second' * FLOOR(RANDOM() * 86400)) AS register_time
    FROM
        generate_series(1, 10)
)
SELECT
    register_time,
    TO_CHAR(register_time, 'yyyy-mm-dd hh24:mi:ss') AS register_time_to_char,
    TO_CHAR(DATE_TRUNC('day', register_time), 'yyyy-mm-dd hh24:mi:ss') AS register_trunc_dd_to_char,
    TO_CHAR(DATE_TRUNC('day', CURRENT_TIMESTAMP), 'yyyy-mm-dd hh24:mi:ss') AS filter_trunc_dd_to_char
FROM
    source
WHERE
    -- source.register_time = DATE_TRUNC('day', CURRENT_TIMESTAMP) --the BUG happend here!
    DATE_TRUNC('day', source.register_time) = DATE_TRUNC('day', CURRENT_TIMESTAMP)
```

![Image](https://github.com/user-attachments/assets/f913924d-bded-45aa-b7a1-cffba96bb0f0)

It's both happend with oracle and postresql.

## suggestion

I think it should be modify for all filter of times. To keep left and right of filter can be same timestamp format.
include `TRUNC('xxx', 'dd')` and `yyyy` or `mm` too and some others.

And maybe we can have a option to show `datetime display format` with full `yyyy-mm-dd hh24:mm:ss` not like only show `yyyy-mm-dd` now.

now I need spend many time to add custom cols every times every where to convert all `datetime` to `char` or `Text` ot `Link`.

help u good and plz fix this soon. 📅 ⛏

**Comment by ranquild** [comment]
https://github.com/metabase/metabase/issues/49641
