### ISSUE TITLE
Support MongoDB Date() function calls in native queries

### ISSUE THREAD

**Issue by jjw123** [metabase/metabase#4964]
I have just started using Metabase and getting into it with my mongodb database.

I have a complex query that can't be done through the query UI, but I need to be able to do relative dates (previous month, day etc.)

Putting a `Date()` constructor in there obviously causes the JSON to not work, I saw this was fixed for ISODate, but this doesnt allow to get the current Date object as far as I can tell.

Thanks for Reading.

PS. I am more than aware that this could be something that I am just missing, in which case I apologise.

**Comment by camsaul** [comment]
@jjw123 can you give us an example query? It would help us in fixing this

**Comment by camsaul** [comment]
@jjw123 Can't you just use `ISODate()` to get the current date? It sounds like [`Date()` just returns the current date as a string](https://docs.mongodb.com/manual/core/shell-types/) so `ISODate()` is probably more useful

**Comment by camsaul** [comment]
@jjw123 I can implement this if you let me know what you expect it to do. If I open a `mongo` console and enter `Date()` I get a string:

```
> Date()
"Thu May 04 2017 16:51:35 GMT-0700 (PDT)"
```

is that what you're expecting `Date()` to do in your query (return the current Date as a string?)

**Comment by jjw123** [comment]
Hi,

After doing some more research, ISODate() would indeed be more useful, however the parsing regex doesnt work if there are no arguments.

I Suggest changing from
`%s\\(([^)]+)\\)`
to
`%s\\(([^)]*)\\)`

Current RegEx: [http://regexr.com/3ft5l](url)
Proposed RegEx: [http://regexr.com/3ft5o](url)

In the mean time, I will try ISODate( ) which should work in theory (The Regex matches, however I am not able to access my metabase instance right now), but this proposed change should make the function calls be more in line with expected behaviour.

**Comment by jjw123** [comment]
As a side note, I Don't think adding the Date function behaviour is a bad idea anyway, as the more Functions that work as intended the better.

**Comment by jjw123** [comment]
@camsaul 

ISODate( ) does not work, resulting in the following error.

`Unexpected character (']' (code 93)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source: java.io.StringReader@21a788ce; line: 25, column: 39]`

It looks to be an error in the decoding where as with the encoding it expects an argument

**Comment by camsaul** [comment]
@jjw123 good catch with the regex 👍

**Comment by jjw123** [comment]
@camsaul 

In theory, ISODate( ) (with a space in the args) should have worked though, so there may be something to fix in the decoding as well as the encoding. 

Just giving you a heads up. The error I posted above is with a space as the arg, and it looks from the decoder is throwing an error if there is nothing there for the arg.

Thanks for making the changes though, I look forward to 0.24.0. :+1:
