### ISSUE TITLE
Performance: static embedding - Lighten app/dist/vendor.XXX.js file - 1.4MB

### ISSUE THREAD

**Issue by polomarcus** [metabase/metabase#49657]
### Describe the bug

For static embedding on a website the JS assets' (pp/dist/vendor.XXX.js ) size is 5.66 MB and Gzipped is 1.43MB.

Would it be possible to configure what to use or not to lighten the final size ?

### To Reproduce

1. Go to a static embedded dashboard
2. Inspect JS assets size

### Expected behavior

Possible to have a light JS assets  with less options (core only mode)

### Information about your Metabase installation

Metabase 0.50.28

### Severity

low

**Comment by albertoperdomo** [comment]
Hello @polomarcus,

is this for static embedding or interactive embedding?

**Comment by polomarcus** [comment]
Hi @albertoperdomo 

For static embedding, just updated my issue.

Thanks ✨

**Comment by paoliniluis** [comment]
related, if not the same as https://github.com/metabase/metabase/issues/33220

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/4665
