### ISSUE TITLE
Click behavior does not get removed when the destination card is deleted

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#49667]
### Describe the bug

New Trash functionality doesn't remove click behaviour reference to deleted card. This might work on the frontend part even though the behaviour is strange but Serialization will fail in these cases

### To Reproduce

1. Go to New -> Question -> Sample DB -> Orders -> Save as Question 1
2. Go to New -> Question -> Sample DB -> Products -> Save as Question 2
3. Add both to a dashboard:

![Image](https://github.com/user-attachments/assets/2945619a-bef1-4fdc-84f4-b6f684e7a391)

4. Setup Click behaviour on Question 1 to go to Question 2

![Image](https://github.com/user-attachments/assets/35ea9db8-2264-4a94-9d1f-c6037ae76eb3)

5. Now go to Question 2 -> Archive it (or as we call it now - Move to trash) ... Notice the changes that happen int he dashboard. The Question gets removed as well (so far so good)

![Image](https://github.com/user-attachments/assets/53cb4d7d-0058-439f-8a25-41c04aa86b5f)

6. When you click on the Click behaviour it still takes you to the archive (not sure if it's by design):

![Image](https://github.com/user-attachments/assets/806a10a9-9bab-4238-ac4d-f7282eb2a82e)

7. Now go back to that archived question and delete it permanently. Nothing changes on the dashboard which is good but now try to click on Question 1 Click behaviour and the click behviour redirects you to Question 1 and if you check the settings it shows Not Found:

![Image](https://github.com/user-attachments/assets/26340631-5f65-4f82-8e8c-6347d63aff77)

NOW THIS IS THE PROBLEM I AM SEEING WITH THIS. If you check the Database. report_dashbaordcard you will notice the click behaviour still points to card 213 but that card doesn't exist anymore

![Image](https://github.com/user-attachments/assets/9e4b751b-e59a-4c63-8777-558268af0998)

The main problem would be around serialization cause the frontend seems to have away to handle this even though it's kind of buggy (instead of just removing the reference on all click behaviour) it redirects to the same question when the question on click behaviour is not Found. But Serailization will fail cause these references don't exist anymore

![Image](https://github.com/user-attachments/assets/3211b24b-e59f-4b66-998e-826251b9aff9)

to get the logs above you need to pass the `?full_stacktrace=true` else they wound show up and the serialization will just fail

### Expected behavior

Not sure but when we permanently delete a Question we should completely delete every reference there is to it

### Information about your Metabase installation

51

### Severity

Not sure of the severity right now but this flow can make serialization hard to work with

**Comment by luizarakaki** [comment]
[Discussion here](https://metaboat.slack.com/archives/CEM835PJP/p1730982280283309)

We should remove click_behavior references when deleting a card.
If a card is permanently deleted, it shouldn't have references elsewhere, including dashboardcard click behavior.

This will resolve the Serialization and other inconsistency symptoms

**Comment by johnswanson** [comment]
Two notes: first, unfortunately, it seems like this might be the tip of an iceberg: it seems that serialization has quite a few places where we're serializing entities that may no longer exist. This is one example, but another would be if Card A uses Card B as a data source, and then Card B is deleted - that triggers exactly the same issue.

Second, while the existence of the Trash has made it easier/more common to delete cards or dashboards, this bug actually predates the Trash - I've verified that it happens on v49 as well. I'm not sure if this should be a cloud blocker given that - although, if this was a rare bug before and the Trash makes it a more common bug (because no one went to the archive and permanently deleted items?) then I can see it being a blocker.

**Comment by Tony-metabase** [comment]
@johnswanson indeed! This is pre-exists 51 and we have other bad references throughout our Database like:

https://github.com/metabase/metabase/issues/49832

What concerns me the most is that yes I feel it's much easier to hit due to the new Trash Feature (especially because of Step 6 above) ... I could be wrong here and it could be just some stupid feeling I have. We can remove it from a blocker and see how it goes since as you said it has been there before 51 and the fact that Trash makes it easier to hit doesn't mean it will become common to hit.

I know this is very hard to fix at Metabase level, even due to the way these bad references are stored. Not sure how easy/hard it is to  check what the reference is during serialization and if it's an archived card then just remove the reference? Instead of completely getting rid of the bad reference at Application Level?

**Comment by perivamsi** [comment]
I propose we keep this as a P1 but remove the cloud-blocker tag since this issue has been existing since before and I am not convinced that the trash feature makes it any worse.
