### ISSUE TITLE
Revoking the access to schema's tables one-by-one for a multi-schema data source acts weirdly

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#4970]
1. Use Redshift as the data source (I'm using Metabase's test Redshift instance)
2. Go to Redshift schema list ("View schemas") and grant unrestricted access for a schema to a user group
![screen shot 2017-05-04 at 15 46 14](https://cloud.githubusercontent.com/assets/6034928/25728005/419a084e-30e1-11e7-8118-51714a724259.png)
3. Go to the table list for that schema ("View tables") and revoke access one-by-one to all tables. Save the changes.
4. Back in the schema list you would expect the UI to show "No access" for that schema. Instead, it shows "Limited access".
![screen shot 2017-05-04 at 15 55 19](https://cloud.githubusercontent.com/assets/6034928/25728161/1cb2d10e-30e2-11e7-9687-3ea04ae8c200.png)

When I look at the permissions table in the database, there are lots of schema table permission entries that are not visible in the permissions editor:

![screen shot 2017-05-04 at 15 44 52](https://cloud.githubusercontent.com/assets/6034928/25728140/09d192be-30e2-11e7-9cb5-ba8b48405eb0.png)

**Comment by salsakran** [comment]
closed via #4847
