### ISSUE TITLE
Trash folder - collections cannot be deleted permanently

### ISSUE THREAD

**Issue by fer-batista** [metabase/metabase#49724]
### Describe the bug

Collections cannot permanently deleted from trash folder.
Should administrators see the deleted items from all users or just items they delete themselves?

![Image](https://github.com/user-attachments/assets/8a5fb254-2ad4-463b-8e9b-17628abd28a8)

### To Reproduce

1. Create a collection
2. Delete
3. Go to trash
4. Try do delete permanently

### Information about your Metabase installation

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-11-04",
      "tag": "v1.51.2",
      "hash": "8bdb22c"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "6.1.90+",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}

### Severity

P3

**Comment by paoliniluis** [comment]
Duplicate
