### ISSUE TITLE
Join block disappears when swapping the data source

### ISSUE THREAD

**Issue by alexyarosh** [metabase/metabase#49738]
### Describe the bug

Join block disappears when swapping the data source... sometimes. 
I have only been able to reliably reproduce it when:
- swapping from model or saved question to a table
- both the model/question and the table have the same name

but I think I had it happen when the names didn't match too, just can't figure out repro steps.

### To Reproduce

1. Save People table as a question called "People"
2. Start a New question from the Orders table
3. Add a Join block to the People _question_
4. Click on the People card to swap the data source to People _table_

The entire Join block disappears

### Expected behavior

The join block remains with the new data source picked

### Information about your Metabase installation

v50+

### Severity

P3

### Additional context

https://github.com/user-attachments/assets/07807bfd-d766-4aad-865a-755384e8a00b

**Comment by ranquild** [comment]
It should always disappear. We don’t support data source swapping now.
