### ISSUE TITLE
Check if the mantine branch breaks something on the sdk

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#49756]
Updated: I tried again on the original branch (without rebasing on master) and everything seems correct.
It's interesting that a lot of stuff broke with the rebase on master, we should probably do another check when the mantine branch is picked up again by admin web app.

---
OLD RESULTS 

Results:

# Colors
Not sure if it's caused by me rebasing the mantine branch on master, but some colors were missing and it made the sdk crash, i manually added some renames to make it work:
```ts
export function themeColor(colorName: string, theme: MantineTheme): string {
  console.log("themeColor", colorName, theme);
  const remaps: Record<string, string> = {
    "text-primary": "text-medium",
    "text-secondary": "text-light",
    "text-tertiary": "text-white",
    background: "bg-white",
  };
  const keyToUse = remaps[colorName] ?? colorName;
  return theme.colors[keyToUse][0] ?? "transparent";
}
```

Edit: it's probably caused because master switched to the new colors and the mantine branch didn't

# Static Question
it seems there are some issues with default sizing and with the layout of the numeric vis
![Image](https://github.com/user-attachments/assets/22ca3b33-66d9-4ac4-a31b-3b1d2a0a8e2c)

# Static Dashboard
The filters popover are rendered at the bottom of the page
![Image](https://github.com/user-attachments/assets/3a6a88e2-35cb-4ab8-957e-3cc8ea3cf586)
Other layout issues
![Image](https://github.com/user-attachments/assets/a0b75c27-b77b-4121-9123-c3095555b208)

# Interactive question
Seems to be completely broken
![Image](https://github.com/user-attachments/assets/5a9b0b0a-2bcb-42d0-9491-2587a0c4e208)

**Comment by heypoom** [comment]
> Not sure if it's caused by me rebasing the mantine branch on master, but some colors were missing and it made the sdk crash

The crash is likely new -- I didn't get that before when I was building the SDK and testing it on Shoppy. I think interactive question was working as well at that time: https://metaboat.slack.com/archives/C063Q3F1HPF/p1730713830351609?thread_ts=1730711693.450249&cid=C063Q3F1HPF

(I think the SDK build was working, as I  got the Mantine provider leak issue and that confirmed that Mantine v7 was used)

**Comment by npretto** [comment]
Updated the body of the issue, closing this.
