### ISSUE TITLE
After update 0.51.2 On public Dashboard the link goes to URL don't work

### ISSUE THREAD

**Issue by DooBio** [metabase/metabase#49776]
### Describe the bug

Hello 

After update on 0.51.2 i noticed that on **public dashboard** on a section "Lien goes to URL" the link don't Work .

if I am connected to metabase and not in public link mode it works very well

### To Reproduce

1. Go to a public Dashboard which has a section with an external https link. if we click on the button of the section the click does not work nothing happens
2. Click on the button of the section the click does not work nothing happens

### Expected behavior

if we do the same action while connected to metabase on the same dashboard it works normally

### Information about your Metabase installation

CHrome 130.0.6723.92
Metabase 0.51.2

### Severity

Blocking Public dashboard

**Comment by brettcvz** [comment]
Relatedly, we just recently upgrade to 51.2 from a 50. release and noticed that in our Static Embeds t "Click on a column to set dashboard filters" no longer works on table views either.

I was able to trace it to [this line](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx#L249) returning `true` in our metabase instance (and therefore continuing on to getClickActions) but returning `false` in the static embed, but I wasn't able to narrow down the specific recent change that broke it.

**Comment by uladzimirdev** [comment]
@DooBio which version did you upgrade from?
