### ISSUE TITLE
disable authentication throttling for development

### ISSUE THREAD

**Issue by lsh-0** [metabase/metabase#4979]
Feature request

I'm working with the REST api and authentication keeps getting throttled. I'd like to disable it for development please.

**Comment by tlrobinson** [comment]
@Ish-0 is there a reason you closed this?

It would also be useful for E2E test development

**Comment by lsh-0** [comment]
I took a closer read of the documentation and it said the session token lasts for 14 days and it should be cached and re-used between requests. Which seemed eminently sensible and showed my laziness up. 

I _can_ see scenarios within CI where ruling out throttling would be beneficial so by all means, re-open if a mechanism for disabling throttling would be useful elsewhere. What would be *most* useful would be reading a simple `.ini` type file to avoid abominations like this: https://github.com/elifesciences/metabase-init-script
