### ISSUE TITLE
ssl peer shut down incorrectly

### ISSUE THREAD

**Issue by MaxiTalenti** [metabase/metabase#4981]
I have this error when configured a ssl keystore, only i can connected to Metabase from local pc, but tested in other, rejected the connection.

![errormetabase](https://cloud.githubusercontent.com/assets/7159779/25759003/1a711912-31a7-11e7-8a19-31cb091dad6c.jpg)

Your operating system: Windows 7
Your databases: SQL Server
Metabase version: v0.23.1
Metabase hosting environment: (e.x. Java in Windows)

**Comment by salsakran** [comment]
This sounds like an issue with your firewall/network settings. 

What have you ruled out in debugging this so far?

**Comment by MaxiTalenti** [comment]
I had poorly defined https ports. Thanks!

**Comment by MaxiTalenti** [comment]
When i put -Djava.net.UseSystemProxies=true i have this error:

![metabase2](https://cloud.githubusercontent.com/assets/7159779/25802701/dd581966-33c9-11e7-8246-59bdb1e226c4.jpg)

**Comment by camsaul** [comment]
@MaxiTalenti try the latest version of Metabase, we changed how Metabase connects to the H2 database. It previously started a separate H2 server process and connected to that via a local port. We tweaked it so it runs as part of the same process (no need to open a port) which should fix the issue you're seeing
