### ISSUE TITLE
DateTime fields should have a corresponding metadata Type in admin panel

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4982]
For anal-retentive completionist types like myself, it feels weird that there's nothing "correct" to select in the Type dropdown for DateTime fields. It makes me feel like my settings are wrong or that Metabase hasn't correctly intuited that that field is in fact a datetime:

![screen shot 2017-05-05 at 11 52 23 am](https://cloud.githubusercontent.com/assets/2223916/25759913/54ece116-3189-11e7-8901-3703d00d2ead.png)
![screen shot 2017-05-05 at 11 52 28 am](https://cloud.githubusercontent.com/assets/2223916/25759912/54d7554e-3189-11e7-8ed3-bfe930235c6a.png)

**Comment by camsaul** [comment]
i think that's because datetime is a "base type" and that's a list of "special types" 

e.g. you can't pick Integer or Boolean or w/e from that list either

**Comment by infomofo** [comment]
@mazameli I would also love to be able to mark a field as a epoch timestamp- it's a number, but it would be great if I could get date operators applied to it in the query builder.

**Comment by camsaul** [comment]
@infomofo you can mark a field as an epoch timestamp, just choose `UNIX Timestamp (Seconds)` from the dropdown.

![screen shot 2017-06-02 at 10 34 13 am](https://cloud.githubusercontent.com/assets/1455846/26737452/0eabf686-477f-11e7-8b10-41bf85c791f6.png)

**Comment by hughcameron** [comment]
Hey @camsaul - I can't spot the UNIX Timestamp options in the Data Model Field Type drop-down as shown in that screengrab above. 
I'm running version 0.24.2 to query a Redshift db with a schema from Segment.com. Is there anything I'm missing?

**Comment by camsaul** [comment]
@hughcameron you can only mark fields that are stored in your database as numbers as UNIX Timestamps.

**Comment by hughcameron** [comment]
Thanks @camsaul, I'll fix the schema.

**Comment by mazameli** [comment]
Closing this since we now have a bunch of special types to choose from, like `creation timestamp` etc.
