### ISSUE TITLE
Add a `force` param to update permission graph endpoints that always update permissions and doesn't require a `revision` number

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#49845]
An intermediate step before we solve https://github.com/metabase/metabase/issues/13884

**Comment by luizarakaki** [comment]
Discussion [here](https://metaboat.slack.com/archives/C05MPF0TM3L/p1731343498768859)

I think adding a `force` property to the update graph endpoint that ignores the `revision` makes sense and avoid making another request just to get the number.
