### ISSUE TITLE
Dashboard date filter "Previous Month, Starting 1 Month Ago" is off by one day

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#49853]
### Describe the bug

When started from a dashboard, the date filter "Previous Month, Starting 1 Month Ago" filters an incorrect range of records.

### To Reproduce

1. Create a GUI question:
- Sample Database, Orders
- Group by: Created at: Day
- Summarize: Count, Min of Created at: Day (don't bin), Max of Created at: Day (don't bin)

2. Add it to a dashboard, and wire a date filter to Created at: Day
3. Filter on: 'Previous month, starting 1 months ago'
* the filter widget shows a correct date range: Sep 1 - Sep 30
![Image](https://github.com/user-attachments/assets/dda4a5ca-9c09-49d7-a2fb-50f3fad5cdc2)
* the actual results are not correct: Sep 1 - Oct 1
![Image](https://github.com/user-attachments/assets/88c01034-dd4c-4c2e-8bc5-6a56f7773076)
4. Open the filtered card
![Image](https://github.com/user-attachments/assets/a21a5262-6e2d-4639-86dc-ed8ac7bfb19f)
* the results are still not correct
5. Click on the filter expression to open the filter widget
![Image](https://github.com/user-attachments/assets/cdc6dc06-6980-425a-973c-c9bcc1ee914d)
* it shows the correct range
6. Click on apply filter
![Image](https://github.com/user-attachments/assets/53727fad-7108-42cf-a895-dfd69f80a54e)
* the updated results are now correct

### Expected behavior

It should always return records between Sep 1 - Sep 30 .

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk",
      "mysql",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2024-11-01",
      "tag": "v1.51.1.8",
      "hash": "488b888"
    },
    "settings": {
      "report-timezone": "America/Denver"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

P1 - incorrect results, affecting a customer

### Additional context

Reported in v1.50.30-x03, reproduced in v1.51.1.8 .

**Comment by appleby** [comment]
Unclear on the cause, but the filter sent to the dataset endpoint differs between the working and non-working cases.

**non-working when first navigating to card from dashboard**

```json
filter": [
    "between",
    [
        "+",
        [
            "field",
            "CREATED_AT",
            {
                "base-type": "type/DateTime"
            }
        ],
        [
            "interval",
            1,
            "month"
        ]
    ],
    [
        "relative-datetime",
        -1,
        "month"
    ],
    [
        "relative-datetime",
        0,
        "month"
    ]
]
```

**working, after clicking "update filter" from the filter widget**

```json
"filter": [
    "relative-time-interval",
    [
        "field",
        "CREATED_AT",
        {
            "base-type": "type/DateTime"
        }
    ],
    -1,
    "month",
    -1,
    "month"
]
```

**Comment by epbarger** [comment]
I'm also seeing this issue
