### ISSUE TITLE
Serialization import breaks when an ID number is followed by "e" or "E" due to it being interpreted as scientific notation

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#49880]
### Describe the bug

 YAML, when a number is followed by "e" or "E", it's interpreted as scientific notation causing an exception with ` ##inf`

### To Reproduce

Create a new metabase instance since this would come with an Example Collection, always having an ID of 1

![Image](https://github.com/user-attachments/assets/16a4eb97-e48a-47c0-acfd-985d68e78648)

Create an API key and export that collection

```
 curl \        
  -H 'x-api-key: your_api_key' \
  -X POST 'http://localhost:3000/api/ee/serialization/export?collection=1&full_stacktrace=true' \ 
  -o metabase_data.tgz 
```

If you go to the ecommerce insights YAML file, which is the dashboard inside the Examples Collection

![Image](https://github.com/user-attachments/assets/15e5e213-61e0-465e-9bc7-b05ad6a301af)

You will find a number of IDs which are not exported with the `''` 

![Image](https://github.com/user-attachments/assets/cf1e3ca9-d346-4546-8a54-de7bbf506d02)

Now the above will not hit the issue since it doesn't have any IDs that have an `e` followed by a sequence of numbers such as `89e41117` the serialization process will interpret this in the scientific notation and will fail the serialization with the following error:

`#ordered/map ([:id ##Inf] [:isMultiSelect false] [:name "Name"] [:sectionId "string"] [:slug "name"] [:type "string/="] [:values_source_config #ordered/map ([:card_id 5579] [:value_field ["field" "empl_fullname" #ordered/map ([:base-type "type/Text"])]])] [:values_source_type "card"])`

Notice the `id ##Inf` at the beginning 

### Expected behavior

**These kind of IDs are interpreted as a string so there is no confusion of scientific notations**

metabase.util.yaml> (yaml/parse-string "a: 1\nb: 2")
{:a 1, :b 2}

metabase.util.yaml> (yaml/parse-string "a: 1\nb: 89")
{:a 1, :b 89}

metabase.util.yaml> (yaml/parse-string "a: 1\nb: 89e41117")
{:a 1, :b ##Inf} -- `WRONG`

metabase.util.yaml> (-> {:a 1, :b "89e41117"} yaml/generate-string)
"{a: 1, b: '89e41117'}\n" -- `RIGHT`

### Logs

`#ordered/map ([:id ##Inf] [:isMultiSelect false] [:name "Name"] [:sectionId "string"] [:slug "name"] [:type "string/="] [:values_source_config #ordered/map ([:card_id 5579] [:value_field ["field" "empl_fullname" #ordered/map ([:base-type "type/Text"])]])] [:values_source_type "card"])`

### Information about your Metabase installation

```JSON
Happens in 49, 50 and 51
```

### Severity

A customer in 49 flagged this since it broke the serialization process

### Additional context

A workaround for this would be to manually add the `''` directly in the yaml file

**Comment by piranha** [comment]
Cannot reproduce this, tests in #49967 show that YAML quotes strings if they resemble numbers (even in scientific notation).

**Comment by Tony-metabase** [comment]
Thanks @piranha !! 

I also confirm from my end. these kind of numbers get a `''` when dumped. I am asking for more details around 2 the customers that hit this like their Diagnostic Info, Environment and how they integrated serialization with the whole import/export flow

**Comment by Tony-metabase** [comment]
I will drop the escalation for now since we need more information around this

**Comment by Tony-metabase** [comment]
Moving this to P2 since we cannot replicate and we don't have more information to work on right now

**Comment by Tony-metabase** [comment]
Closing this one since there has been inactivity form the user that reached out about this issue and internally cannot be replicated
