### ISSUE TITLE
Multiple Series in the Query Builder

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4989]
Right now the only way to have multiple series on a given card is to put a question in a dashboard and add a question to it. 

We should allow users to eg, plot DAU and Total Revenue on the same question. 

Related to #3574, but likely to be somewhat more specific to time-series.

**Comment by sabino** [comment]
Hey @salsakran will this add the possibility of combining different charts? Like a bar chart and a line chart together?

Like this:
![image](https://cloud.githubusercontent.com/assets/982190/26793060/f272ef12-49f2-11e7-805c-81d2b91e2cc2.png)

**Comment by mazameli** [comment]
@sabino we're definitely discussing that possibility.

**Comment by lucasloami** [comment]
Hey, guys, are you planning to wok in this feature for now? This is a key point in my current reality to convince managers and other team members to use Metabase. 

I believe this feature is one of the key points to leverage Metabase towards other paid tools and can be very useful for the community.

**Comment by thenaturalist** [comment]
Any update on this?

**Comment by lucasloami** [comment]
@thenaturalist try to add a thumbs up in the first post of this topic, so them Metabase team can prioritize this task =)

**Comment by lucasloami** [comment]
Hey, @mazameli , will this idea be addressed in the v0.31?

**Comment by mazameli** [comment]
This is now possible by joining a time series to another time series in the Custom/notebook graphical query builder. I've opened another issue thought to propose adding an easier way of doing this from the Simple query builder when looking at a time series chart: https://github.com/metabase/metabase/issues/11157
