### ISSUE TITLE
Provide a more guided New Question flow

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4990]
Right now we're dropping you right in the query builder, which is kind of confusing for new users. 

We should provide a less intimidating means of asking quesitons. 

Worked on in #4642

**Comment by mazameli** [comment]
Addressed by #5790, though this issue doesn't specify that we'll want to continue building on this updated New Question UX beyond what's been done in 5790.

**Comment by salsakran** [comment]
closed via #5790

improvements to the overall process will be done as we identify what we need to do.
