### ISSUE TITLE
Support lineage

### ISSUE THREAD

**Issue by psalinasy** [metabase/metabase#49910]
**Is your feature request related to a problem? Please describe.**
When changing a table or schema you have very little visibility of the impact it would have on the already created questions/dashboards in Metabase. 

Having a way to visualize all the dependencies would be ideal. 

**How important is this feature to you?**
Request by a customer

**Additional context**
Related to the [ParseSQL Epic](https://github.com/metabase/metabase/issues/36911)

**Comment by paoliniluis** [comment]
Related if not the same as https://github.com/metabase/metabase/issues/27106?
