### ISSUE TITLE
Refactor Sync + Analysis 

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4991]
The code for syncing and analysis is a bit of a hairball.

We should re-factor it to both make it more maintanable, more testable and hit the following 

1. Separate out schedules for syncing, analysis (i.e. guessing field types) and storing field values
2. Break up analysis into a fingerprinting stage and a classification stage
3. Provide user-land scheduling controls for syncing, analysis and field values

**Comment by camsaul** [comment]
Closing this since #5510 refactored sync and analysis. We have #4262 already open for tracking the ability to set separate schedules for sync/analysis/field values caching so I'll use that to track parts 2 & 3 of the Sync Refactor
