### ISSUE TITLE
administration role get error 'Sorry, you don’t have permission to see that.'

### ISSUE THREAD

**Issue by negahsol** [metabase/metabase#49952]
### Describe the bug

i have metabase version v0.50.11 and i have administration access but on root collection and some questions i get 'Sorry, you don’t have permission to see that.'
i checked all permissions and log but i couldnt find any thing that can change to fix this.
can you help me to find the problem plz.

### To Reproduce

GET /api/collection/root 403 8.1 ms (2 DB calls) {:metabase-user-id 102} 
"You don't have permissions to do that."

### Information about your Metabase installation

```JSON
metabase version v0.50.11 
postgres version 15.3
```

### Severity

blocking some users

**Comment by negahsol** [comment]
![Image](https://github.com/user-attachments/assets/f28dba72-dec4-41c9-978a-26cc14cd1a1e)
 in postgresql database
![Image](https://github.com/user-attachments/assets/5382d05f-92eb-430d-b1f8-4112fa697438)
in metabase UI

**Comment by npfitz** [comment]
@negahsol Are you able to go to the permissions page, and check collection permissions for "Our Analytics"? The route should look like this: `/admin/permissions/collections/root`.

**Comment by paoliniluis** [comment]
closing due to no response
