### ISSUE TITLE
MongoDB Function without argument still not working.

### ISSUE THREAD

**Issue by jjw123** [metabase/metabase#4996]
Last week I submitted Issue #4964 regarding the mongodb functions that have been added. @camsaul worked on this and marked the issue as closed.

It was identified that it wouldn't encode functions without an argument.

I have downloaded the latest version of Metabase and compiled from source. There is still an issue that occurs when using ISODate() in a query.

`Unexpected character (']' (code 93)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source: java.io.StringReader@66944e1f; line: 10, column: 38]`

I believe that it is encoding the function properly, but failing when decoding the arguments and passing them to the function.

**Comment by camsaul** [comment]
Fixed by #5003
