### ISSUE TITLE
Add Data box is showing in version 50.33 and should not be in 50 at all

### ISSUE THREAD

**Issue by cbalusek** [metabase/metabase#49973]
### Describe the bug

The "Add data" box is appearing in 50

![Image](https://github.com/user-attachments/assets/94981e3b-40ed-429a-8fbe-49d32eab8e68)
![Image](https://github.com/user-attachments/assets/fd6bc910-30a9-4f2b-b7f3-a3b7bf2edc93)

### To Reproduce

1.  Upgrade or install 50.33 or 50.32
2. Log in

### Expected behavior

This shouldn't appear

### Information about your Metabase installation

```JSON
Chrome, v 1.50.33

Reported by a customer on 1.50.32 as well
```

### Severity

P1

### Additional context

New UI features should not appear for customer when they take a minor release, which is why I am labeling as a P1 or escalation

**Comment by nemanjaglumac** [comment]
Resolved by #49984
