### ISSUE TITLE
Progress charts should have an action to "view these [table name]"

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4998]
Related to https://github.com/metabase/metabase/issues/4983

![goal](https://cloud.githubusercontent.com/assets/2223916/25815074/864292ae-33d4-11e7-95ae-8d70d5d1c850.png)

**Comment by tlrobinson** [comment]
From an implementation standpoint this is a duplicate of #4983, since the bar is treated the same as a scalar.

**Comment by mazameli** [comment]
Closing as duplicate of #4983
