### ISSUE TITLE
0.51.x: ERROR metabase.task Error rescheduling job,org.quartz.ObjectAlreadyExistsException

### ISSUE THREAD

**Issue by michael-gratton** [metabase/metabase#50063]
### Describe the bug

We upgraded from 0.50.x to 0.51.x and these started occurring. It also seems that new alerts are not being sent, unclear if related.

### To Reproduce

1. Upgrade to 0.51.x

### Expected behavior

No error is reported.

### Logs

```
[fa705b8e-d7fb-4d33-b15b-74494d6383e9] 2024-11-15T13:17:37+11:00 ERROR metabase.task Error rescheduling job
org.quartz.ObjectAlreadyExistsException: Unable to store Trigger with name: 'metabase.task.backfill-query-fields.trigger' and group: 'DEFAULT', because one already exists with this identification.
at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1184)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.replaceTrigger(JobStoreSupport.java:1503)
at org.quartz.impl.jdbcjobstore.JobStoreSupport$11.execute(JobStoreSupport.java:1478)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
at org.quartz.impl.jdbcjobstore.JobStoreTX.executeInLock(JobStoreTX.java:93)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.replaceTrigger(JobStoreSupport.java:1474)
at org.quartz.core.QuartzScheduler.rescheduleJob(QuartzScheduler.java:1121)
at org.quartz.impl.StdScheduler.rescheduleJob(StdScheduler.java:321)
at metabase.task$reschedule_task_BANG_93209__93210.invokeStatic(task.clj:201)
at metabase.task$reschedule_task_BANG_93209__93210.invoke(task.clj:192)
at metabase.task$schedule_task_BANG_93225__93226.invokeStatic(task.clj:221)
at metabase.task$schedule_task_BANG_93225__93226.invoke(task.clj:213)
at metabase.task.sweep_query_analysis$fn__108080.invokeStatic(sweep_query_analysis.clj:113)
at metabase.task.sweep_query_analysis$fn__108080.invoke(sweep_query_analysis.clj:96)
at metabase.task$init_tasks_BANG_$fn__93132.invoke(task.clj:79)
at metabase.task$init_tasks_BANG_.invokeStatic(task.clj:75)
at metabase.task$init_tasks_BANG_.invoke(task.clj:71)
at metabase.task$init_scheduler_BANG_.invokeStatic(task.clj:166)
at metabase.task$init_scheduler_BANG_.invoke(task.clj:153)
at metabase.task$start_scheduler_BANG_.invokeStatic(task.clj:177)
at metabase.task$start_scheduler_BANG_.invoke(task.clj:172)
at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:166)
at metabase.core$init_BANG__STAR_.invoke(core.clj:102)
at metabase.core$init_BANG_.invokeStatic(core.clj:181)
at metabase.core$init_BANG_.invoke(core.clj:176)
at metabase.core$start_normally.invokeStatic(core.clj:193)
at metabase.core$start_normally.invoke(core.clj:187)
at metabase.core$entrypoint.invokeStatic(core.clj:226)
at metabase.core$entrypoint.doInvoke(core.clj:220)
at clojure.lang.RestFn.invoke(RestFn.java:400)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.RestFn.applyTo(RestFn.java:135)
at clojure.lang.Var.applyTo(Var.java:707)
at clojure.core$apply.invokeStatic(core.clj:667)
at clojure.core$apply.invoke(core.clj:662)
at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
at clojure.lang.RestFn.invoke(RestFn.java:400)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.RestFn.applyTo(RestFn.java:135)
at metabase.bootstrap.main(Unknown Source)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-AU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "redshift"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-11",
      "tag": "v0.51.3",
      "hash": "d757d0b"
    },
    "settings": {
      "report-timezone": "Australia/Sydney"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "5.10.226-214.880.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Australia/Sydney"
  }
}
```

### Severity

blocking some users

### Additional context

Deployment context is Docker using AWS ECS Fargate, 1-2 instances typically running concurrently.

**Comment by qnkhuat** [comment]
Could you give us the result of this query?
```sql
select * from qrtz_triggers;
```

>  It also seems that new alerts are not being sent

Could you try creating a new alert and then running this query
```sql
select * from qrtz_triggers where trigger_name like 'metabase.task.send-pulse.trigger.{{YOUR_NEW_ALERT_ID}}%'
```
There should be one record returning.

**Comment by michael-gratton** [comment]
Sure thing:

> select * from qrtz_triggers;

| sched_name        | trigger_name                                        | trigger_group | job_name                                   | job_group | description                               | next_fire_time | prev_fire_time | priority | trigger_state | trigger_type | start_time    | end_time | calendar_name | misfire_instr | job_data  |
|-------------------|-----------------------------------------------------|---------------|--------------------------------------------|-----------|-------------------------------------------|----------------|----------------|----------|---------------|--------------|---------------|----------|---------------|---------------|-----------|
| MetabaseScheduler | metabase.task.anonymous-stats.trigger               | DEFAULT       | metabase.task.anonymous-stats.job          | DEFAULT   |                                           |  1731988140000 |  1731901740000 |        5 | WAITING       | CRON         | 1731655582000 |        0 |               |             0 | 0 bytes   |
| MetabaseScheduler | metabase.task.send-pulse.trigger.111.0_0_0_*_*_?_*  | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1732021200000 |  1731934800000 |        6 | WAITING       | CRON         | 1721962889000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.follow-up-emails.trigger              | DEFAULT       | metabase.task.follow-up-emails.job         | DEFAULT   |                                           |  1731978000000 |  1731891600000 |        5 | WAITING       | CRON         | 1731655582000 |        0 |               |             0 | 0 bytes   |
| MetabaseScheduler | metabase.task.sync-and-analyze.trigger.58           | DEFAULT       | metabase.task.sync-and-analyze.job         | DEFAULT   | sync-and-analyze Database 58              |  1731972780000 |  1731969180000 |        5 | WAITING       | CRON         | 1683795973000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.creator-sentiment-emails.trigger      | DEFAULT       | metabase.task.creator-sentiment-emails.job | DEFAULT   |                                           |  1732287600000 |  1731682800000 |        5 | WAITING       | CRON         | 1731655582000 |        0 |               |             0 | 0 bytes   |
| MetabaseScheduler | metabase.task.update-field-values.trigger.8         | DEFAULT       | metabase.task.update-field-values.job      | DEFAULT   | update-field-values Database 8            |  1732042800000 |  1731956400000 |        5 | BLOCKED       | CRON         | 1659406805000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.send-pulse.trigger.75.0_0_9_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1732053600000 |  1731967200000 |     3575 | WAITING       | CRON         | 1721862025000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.truncate-audit-tables.trigger         | DEFAULT       | metabase.task.truncate-audit-tables.job    | DEFAULT   |                                           |  1731978000000 |  1731934800000 |        5 | WAITING       | CRON         | 1731655582000 |        0 |               |             2 | 0 bytes   |
| MetabaseScheduler | metabase.task.refresh-channel-cache.trigger         | DEFAULT       | metabase.task.refresh-channel-cache.job    | DEFAULT   |                                           |  1731981120000 |  1731966720000 |        5 | WAITING       | CRON         | 1731655582000 |        0 |               |             2 | 0 bytes   |
| MetabaseScheduler | metabase.task.upgrade-checks.trigger                | DEFAULT       | metabase.task.upgrade-checks.job           | DEFAULT   |                                           |  1732000500000 |  1731957300000 |        5 | WAITING       | CRON         | 1731655582000 |        0 |               |             0 | 0 bytes   |
| MetabaseScheduler | metabase.task.PersistencePrune.scheduled.trigger    | DEFAULT       | metabase.task.PersistencePrune.job         | DEFAULT   | Prune deletable PersistInfo once per hour |  1731970800000 |  1731967200000 |        5 | WAITING       | CRON         | 1731655563000 |        0 |               |             2 | 0 bytes   |
| MetabaseScheduler | metabase.task.update-field-values.trigger.11        | DEFAULT       | metabase.task.update-field-values.job      | DEFAULT   | update-field-values Database 11           |  1731956400000 |  1731870000000 |        5 | BLOCKED       | CRON         | 1659406816000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.analyze-queries.trigger               | DEFAULT       | metabase.task.analyze-queries.job          | DEFAULT   |                                           |             -1 |  1731884183090 |        5 | COMPLETE      | SIMPLE       | 1731655582686 |        0 |               |             0 | 0 bytes   |
| MetabaseScheduler | metabase.task.sync-and-analyze.trigger.8            | DEFAULT       | metabase.task.sync-and-analyze.job         | DEFAULT   | sync-and-analyze Database 8               |  1731972300000 |  1731968700000 |        5 | WAITING       | CRON         | 1659320701000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.task-history-cleanup.trigger          | DEFAULT       | metabase.task.task-history-cleanup.job     | DEFAULT   |                                           |  1732021200000 |  1731934800000 |        5 | WAITING       | CRON         | 1731655582000 |        0 |               |             0 | 0 bytes   |
| MetabaseScheduler | metabase.task.send-pulse.trigger.72.0_0_8_1_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1733000400000 |  1730408400000 |     3469 | WAITING       | CRON         | 1719784930000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.63.0_0_9_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1732053600000 |  1731967200000 |     3597 | WAITING       | CRON         | 1721862002000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.50.0_0_*_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1731970800000 |  1731967200000 |     3596 | WAITING       | CRON         | 1721865604000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.update-field-values.trigger.3         | DEFAULT       | metabase.task.update-field-values.job      | DEFAULT   | update-field-values Database 3            |  1731967200000 |  1731880800000 |        5 | BLOCKED       | CRON         | 1659320693000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.backfill-query-fields.trigger         | DEFAULT       | metabase.task.backfill-query-fields.job    | DEFAULT   |                                           |  1731979140000 |  1731964740000 |        5 | WAITING       | CRON         | 1731633453000 |        0 |               |            -1 | 0 bytes   |
| MetabaseScheduler | metabase.task.sync-and-analyze.trigger.11           | DEFAULT       | metabase.task.sync-and-analyze.job         | DEFAULT   | sync-and-analyze Database 11              |  1731972600000 |  1731969000000 |        5 | WAITING       | CRON         | 1659320705000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.send-pulse.trigger.60.0_0_*_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1731970800000 |  1731967200000 |        6 | WAITING       | CRON         | 1718058711000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.74.0_0_8_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1732050000000 |  1731963600000 |     3531 | WAITING       | CRON         | 1720389668000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.sync-and-analyze.trigger.56           | DEFAULT       | metabase.task.sync-and-analyze.job         | DEFAULT   | sync-and-analyze Database 56              |  1731972000000 |  1731968400000 |        5 | WAITING       | CRON         | 1659320696000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.update-field-values.trigger.56        | DEFAULT       | metabase.task.update-field-values.job      | DEFAULT   | update-field-values Database 56           |  1732039200000 |  1731952800000 |        5 | BLOCKED       | CRON         | 1659406968000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.PersistenceRefresh.database.trigger.3 | DEFAULT       | metabase.task.PersistenceRefresh.job       | DEFAULT   | Refresh models for database 3             |  1731970800000 |  1731963600000 |        5 | WAITING       | CRON         | 1731655582000 |        0 |               |             2 | 376 bytes |
| MetabaseScheduler | metabase.task.send-pulse.trigger.67.0_0_8_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1732050000000 |  1731963600000 |        6 | WAITING       | CRON         | 1718058710000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.110.0_0_11_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1731974400000 |  1731888000000 |     3558 | WAITING       | CRON         | 1721178042000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.71.0_0_9_1_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1733004000000 |  1730412000000 |     3548 | WAITING       | CRON         | 1719788452000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.update-field-values.trigger.55        | DEFAULT       | metabase.task.update-field-values.job      | DEFAULT   | update-field-values Database 55           |  1731960000000 |  1731873600000 |        5 | BLOCKED       | CRON         | 1659320690000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.sync-and-analyze.trigger.59           | DEFAULT       | metabase.task.sync-and-analyze.job         | DEFAULT   | sync-and-analyze Database 59              |  1731970560000 |  1731966960000 |        5 | WAITING       | CRON         | 1695701116000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.send-pulse.trigger.176.0_0_*_*_*_?_*  | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1731970800000 |  1731967200000 |        6 | WAITING       | CRON         | 1731629454000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.61.0_0_*_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1731970800000 |  1731967200000 |        6 | WAITING       | CRON         | 1718058711000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.109.0_0_11_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1731974400000 |  1731888000000 |     3554 | WAITING       | CRON         | 1721523645000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.sync-and-analyze.trigger.2            | DEFAULT       | metabase.task.sync-and-analyze.job         | DEFAULT   | sync-and-analyze Database 2               |  1732046400000 |  1731960000000 |        5 | WAITING       | CRON         | 1720681039000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.update-field-values.trigger.58        | DEFAULT       | metabase.task.update-field-values.job      | DEFAULT   | update-field-values Database 58           |  1732028400000 |  1731942000000 |        5 | BLOCKED       | CRON         | 1687076758000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.update-field-values.trigger.2         | DEFAULT       | metabase.task.update-field-values.job      | DEFAULT   | update-field-values Database 2            |  1731963600000 |  1731877200000 |        5 | BLOCKED       | CRON         | 1718930089000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.sync-and-analyze.trigger.55           | DEFAULT       | metabase.task.sync-and-analyze.job         | DEFAULT   | sync-and-analyze Database 55              |  1731971100000 |  1731967500000 |        5 | WAITING       | CRON         | 1647867550000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.send-pulse.trigger.112.0_0_18_*_*_?_* | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1731999600000 |  1731913200000 |        6 | WAITING       | CRON         | 1722071722000 |        0 |               |             1 | 996 bytes |
| MetabaseScheduler | metabase.task.send-pulse.trigger.66.0_0_0_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1732021200000 |  1731934800000 |        6 | WAITING       | CRON         | 1718058710000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.142.0_0_9_?_*_5_*  | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1732140000000 |  1731535200000 |        6 | WAITING       | CRON         | 1725489688000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.send-pulse.trigger.64.0_0_*_*_*_?_*   | DEFAULT       | metabase.task.send-pulses.send-pulse.job   | DEFAULT   |                                           |  1731970800000 |  1731967200000 |        6 | WAITING       | CRON         | 1718058710000 |        0 |               |             1 | 1 KB      |
| MetabaseScheduler | metabase.task.sync-and-analyze.trigger.3            | DEFAULT       | metabase.task.sync-and-analyze.job         | DEFAULT   | sync-and-analyze Database 3               |  1731970500000 |  1731966900000 |        5 | WAITING       | CRON         | 1676941133000 |        0 |               |             2 | 358 bytes |
| MetabaseScheduler | metabase.task.update-field-values.trigger.59        | DEFAULT       | metabase.task.update-field-values.job      | DEFAULT   | update-field-values Database 59           |  1732003200000 |  1731916800000 |        5 | BLOCKED       | CRON         | 1695701116000 |        0 |               |             2 | 358 bytes |


> Could you try creating a new alert and then running this query
> 
> select * from qrtz_triggers where trigger_name like 'metabase.task.send-pulse.trigger.{{YOUR_NEW_ALERT_ID}}%'
> 
> There should be one record returning.

That is indeed what happened. I think the issue with the alerts is maybe unrelated, or at least perhaps worth resolving the first issue and I'll file another one if I think there is still an outstanding problem.

**Comment by qnkhuat** [comment]
everything looks normal there, are you getting this error consistently on every deployment? if so, does it happen if you run Metabase on a single instance?

**Comment by qnkhuat** [comment]
query analysis is unused for now, so it's just a P2. Alert not sending might be a separate one
