### ISSUE TITLE
Document MB_EMAIL_MAX_RECIPIENTS_PER_SECOND

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#50087]
**Is your feature request related to a problem? Please describe.**
Admins can now slow down / throttle the sending rate of emails from their instance. It would be helpful to document this.
[See #49477](https://github.com/metabase/metabase/pull/49477)

**Comment by jeff-bruemmer** [comment]
Documented here: https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_email_max_recipients_per_second
