### ISSUE TITLE
Can't run Cucumber in Metabase. Please Help!!

### ISSUE THREAD

**Issue by jegglestone** [metabase/metabase#5008]
Hi,
I am trying to get Cucumber.js tests to run but can't get any success. Here is my branch:

https://github.com/GearStream/Portfolio-BI-FrontEndExperimental/tree/feature_scenarios_joseph

I have my test under the folder gearstream/test/cucumber/ 

I am running the command "yarn test-cukes", which I have set up to execute the tests from this folder.

Issue 1. When there's any ES6 features in the step definitions (such as 'imports from' or exports.module etc,) it errors with a "Reserved keyword" error. I have confirmed that we have "presets"["es-2016"] in the .babelrc but this has not made a difference.

Issue 2. To get around the above I have reverted my JavaScript to traditional JS using var, define, require etc. However, it comes up with 'illegal token' errors.

This is all very strange as I'm doing everything by the common convention bt for some reason Metabase doesn't seem to like anything Cucumber related.

Any help much appreciated.

**Comment by salsakran** [comment]
Hello @jegglestone -

Your questions are kind of out of scope of what we'd be able to help you with. First off, that branch is private, and secondly we aren't planning on using Cucumber in the project itself.
