### ISSUE TITLE
Custom destination click behavior broken for statically embedded trend charts

### ISSUE THREAD

**Issue by YvesBos** [metabase/metabase#50086]
### Describe the bug

Starting in v1.51.1, the custom click behavior on statically embedded trend charts is broken. Nothing happens, no errors logged in the console. 

Only trend seem to be affected, the click behavior for our other chart types still works. I've reproduced the issue using the sample database, see below. On version v1.50.27 it still works, I've verified using the same method.

### To Reproduce

1. Ensure static embedding is enabled
2. Create a new dashboard with the `Discount given per quarter` trend chart
3. Add custom destination click behavior to the trend chart: link to `https://google.com`
4. Save & publish the dashboard
5. Open the iframe URL that you get by running the suggested snippet
6. Click on the number in the trend chart

### Expected behavior

`https://google.com` should open in a new tab.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-11-04",
      "tag": "v1.51.2",
      "hash": "8bdb22c"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "5.10.217-205.860.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

High

**Comment by uladzimirdev** [comment]
thanks for a nice bug report, we have a similar problem reported here https://github.com/metabase/metabase/issues/49776

table view is affected as well
