### ISSUE TITLE
"count by time" action on table headings doesn't make sense

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5009]
<img width="377" alt="screen shot 2017-05-08 at 2 03 25 pm" src="https://cloud.githubusercontent.com/assets/2223916/25825392/b593fc78-33f7-11e7-8c1e-a55494b6d7d5.png">

Choosing this action takes you to a count of rows over time, but weirdly puts the field name into the aggregation, like this:

<img width="247" alt="screen shot 2017-05-08 at 2 07 18 pm" src="https://cloud.githubusercontent.com/assets/2223916/25825387/b1d679a8-33f7-11e7-9e53-f957bbbca068.png">

This is pretty nonsensical. Was this intended to be "count by time and by [this field]"?

**Comment by flamber** [comment]
Hi @mazameli 
I'm not sure, but it seems like this is fixed - looks like this in 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52833524-b9b51b80-30a2-11e9-9a95-746e60a8ea14.png)
And from what I can tell, `Distribution` does a `Count of rows` grouped by `Subtotal (auto binned)`

**Comment by mazameli** [comment]
This got fixed somewhere along the way.
