### ISSUE TITLE
Inconsistent quoting when downloading CSV

### ISSUE THREAD

**Issue by demorenoc** [metabase/metabase#5013]
Hi. 

I am using Metabase 0.23.1 in Elastic Beanstalk to interface data from a MySQL database. My team has been experiencing inconsistent behavior with the file format when downloading CSV from the UI: some text values that have a comma in it are quoted (with `""`) but in other cases the value (with a comma) is not quoted (even within the same column where we get some quoted values). This ends up in people not being able to parse the file consistently with whatever tool they use. 

We mostly experience this issue with biggish CSVs (say 2000+ records) but we have seen this occur with small data-sets as well. (I think this is fully back-end, but just in case we have seen this occur when downloading from Chrome as well as from Firefox).

As far as I could read from the code I think this is automatically done by the `write-csv` function in the `clojure.data.csv` module, but I have no idea if it is because of the way the function is called or a bug there. I would like to suggest the ability to pass in or configure the delimiter and whether to quote or not text columns from the UI before downloading (more options like date format could be offered), or at least make sure text columns are always quoted by default.

**Comment by salsakran** [comment]
What character encoding are you using, and can you share examples of values that get encoded properly and ones that don't? 

Do any of the columns get encoded properly in some cases and incorrectly in other cases?

**Comment by demorenoc** [comment]
- We use UTF8. Stuff like: `Category A, category B and category C`. Nothing particular.

- Not columns but rows, I think we have not tried downloading a query where more than 1 column has strings with commas. As explained we would get, in the same column, some values properly quoted and some not, even for the same value, e.g. in a row we would get `"Category A, category b and category C"` (properly quoted) and in another row we would get the same value not quoted.

**Comment by turicas** [comment]
Hi! Any news about this issue? It's also affecting me (sample data in the screenshow below), I'm using v0.30.4 ([metabase-deploy](https://github.com/metabase/metabase-deploy) running on Heroku).
For some reason the server is timing out when generating the same result in XLS, so I've switched to CSV (but this bug is happening).

![photo4956247115915438085](https://user-images.githubusercontent.com/186126/50241064-a12fca00-03ad-11e9-9242-de749cdf941f.jpg)

**Comment by flamber** [comment]
I have tried multiple databases and datasets of all sizes, but I haven't been able to reproduce on 0.35.3. Please comment if you're still experiencing this, and include version info and possibly a way to reproduce.
