### ISSUE TITLE
SSH tunnel credentials not being validated

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#5016]
It's possible to add a database with invalid SSH tunnel credentials. The database doesn't sync and it isn't usable.

**Comment by thearthur** [comment]
This happens in cases where you have direct access to a DB and have chosen to us an ssh tunnel anyway (for security).

**Comment by salsakran** [comment]
You shouldn't be able to add a db with invalid SSH creds, we should do form validation on that similarly to how we deal with DB connection strings that fail to connect.

**Comment by thearthur** [comment]
Yes, the validator is fixed, working on the test now

**Comment by thearthur** [comment]
The same bug existed in druid's can-connect?
I'm adding tests for all of them.

**Comment by thearthur** [comment]
Fixed
