### ISSUE TITLE
"Summarize this segment" aggregation doesn't fill the whole width of the popover

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#5021]
<img width="373" alt="screen shot 2017-05-08 at 5 07 30 pm" src="https://cloud.githubusercontent.com/assets/5248953/25830362/23dbbd10-3411-11e7-89f9-e3a9470b37b6.png">

Browser: Firefox, Chrome, Safari
Version: Metabase 0.24 RC4

**Comment by attekei** [comment]
Was fixed as part of https://github.com/metabase/metabase/pull/5516
