### ISSUE TITLE
Accessing a public link for a dashboard that has been archived results in a 400

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5023]
I'd expect a 404 as opposed to an error message

<img width="371" alt="screen shot 2017-05-08 at 5 14 07 pm" src="https://cloud.githubusercontent.com/assets/107439/25830454/c75b67b0-3411-11e7-984e-050f42718188.png">

**Comment by albertoperdomo** [comment]
This is actually rendering the 404 image now. Closing.

<img width="853" alt="image" src="https://github.com/metabase/metabase/assets/24216/5e2cc997-f9eb-4330-a7d5-d5e6df017b24">
