### ISSUE TITLE
Certain modals aren't closing when you click outside or hit `esc`

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#5024]
Looks like certain modals aren't responding to clicks outside or `esc` key presses anymore.

Specifically:

- Add to dash modal.
- Add question to dashboard

(possibly others?)

Browsers: all
Version:  0.24 RC4

**Comment by flamber** [comment]
Hi @kdoh 
I cannot replicate this on 0.31.2 - only problems with collections Move modal, which was solved by #9417
