### ISSUE TITLE
Drill-through and title links for multi-scalar dashcards work incorrectly

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#5028]
With this example dashcard:

<img width="417" alt="screen shot 2017-05-08 at 17 25 21" src="https://cloud.githubusercontent.com/assets/6034928/25830694/63141c3c-3413-11e7-9485-981a950a9eb1.png">

* If I try to drill through by clicking "Orders total" bar, it's incorrectly using "Orders total empty" instead
* If I try to click "Orders total" title, then I see the correct data but the lineage says "Orders total empty"

**Comment by salsakran** [comment]
fixed via #5040
