### ISSUE TITLE
Tooltips Stop Working When Using iFrameResize with Embedded Metabase Dashboards

### ISSUE THREAD

**Issue by rodrigoGA** [metabase/metabase#50300]
### Describe the bug

When embedding a Metabase dashboard using the iFrameResize library, tooltips within the dashboard stop functioning as expected. This issue does not occur when the dashboard is embedded without the iFrameResize integration.

This issue is highly severe because embedding is the only way to integrate Metabase dashboards into other applications. The lack of functioning tooltips disrupts the user experience, especially for interactive visualizations, impacting the utility of Metabase in external-facing applications.

### To Reproduce

1. Embed a Metabase dashboard into a webpage using the following HTML structure:
html
```
<section class="dashboard-section">
    <h2>Dashboard 1</h2>
    <div class="iframe-wrapper">
        <iframe
            src="<%= iframeUrl %>"
            frameborder="0"
            allowfullscreen
            onload="iFrameResize({}, this)"
        ></iframe>
    </div>
</section>
```
2. Include the iFrameResize library from Metabase:
```
<script src=".../app/iframeResizer.js"></script>
```
3. View the embedded dashboard and attempt to interact with tooltips (e.g., hover over a chart element).

### Expected behavior

Tooltips should work as intended within the embedded dashboard, regardless of whether iFrameResize is used.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-11",
      "tag": "v0.51.3",
      "hash": "d757d0b"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.114.2.el7.x86_64",
    "user.language": "es",
    "user.timezone": "Europe/Madrid"
  }
}
```

### Severity

high

**Comment by paoliniluis** [comment]
same as https://github.com/metabase/metabase/issues/49219?
