### ISSUE TITLE
Is there a way to add textbox to dashboard like what we do in questions?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#5033]
In questions we have an option that we could set variable in order to be filled by end users to get their desired output. Is there a same way for dashboard to do the same thing?

If it is not available yet, is there any plan to add such an option to dashboards? Or at least we could see those variables in questions inside of dashboard?

**Comment by kdoh** [comment]
Hey @alirezastack. If you're talking about dashboard filters [this docs article on the subject](http://www.metabase.com/docs/latest/users-guide/07-dashboard-filters.html) is your best bet.
