### ISSUE TITLE
We broke the pivot grouping in 51

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#50346]
### Describe the bug

We broke the pivot table groupings in v51, users can't collapse and expand the groups anymore

### To Reproduce

1) Make a question like
![Image](https://github.com/user-attachments/assets/3dcfc6e2-e262-4735-b06a-0ad631406fd6)
2) visualize it as a pivot table with these viz settings
![Image](https://github.com/user-attachments/assets/5b2ce37a-2a13-4ef9-9973-23867e317e50)
3) see that theres's no way to minimize and maximize the groupings

50 looked like
![Image](https://github.com/user-attachments/assets/7fc01c90-3b09-4068-8e85-cbb4500869bb)

### Expected behavior

We should have the grouping as we had in v50

### Logs

NA

### Information about your Metabase installation

```JSON
v51
```

### Severity

P1

**Comment by NevRA** [comment]
Reopened by mistake https://metaboat.slack.com/archives/C0645JP1W81/p1748962364088729
