### ISSUE TITLE
Category Dropdown behavior - Not showing when mapped to category and text field

### ISSUE THREAD

**Issue by sabino** [metabase/metabase#5034]
### Bug
Don't know if this is expected behavior but it is currently a problem for us.
We have some dashboards that uses queries and they don't have the Category Filter Dropdown. We've managed to "fix" it in a hacky way by adding another card with a simple question to be used as a reference for the Category Filter.

As for 0.24.RC4 this is not working anymore.

- Your browser and the version: Chrome 55.0.2883.87 (64-bit)
- Your operating system: Ubuntu 16.04.2 LTS
- Your databases: Postgresql
- Metabase version: 0.24.RC4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Repeatable steps to reproduce the issue**

Using Sample Database.

1. Create a question poiting to the Products table and add to a dashboard.
2. Create another question but using a query and a text variable, a simple one like: select {{variable}} and add to the same dashboard.
3. While at the dashboard add a Category Filter and map it to the Category field in the first question, a dropdown should apper.
4. Map the same filter to the other question, using the variable.
5. No more dropdown.

![metabase_dropdown](https://cloud.githubusercontent.com/assets/982190/25850270/0add0512-3498-11e7-8ad1-1f6bf62b646d.gif)

Thanks!
-------

**Comment by salsakran** [comment]
closed via #5036
