### ISSUE TITLE
Customizing grouping options for time group filter breaks some functionality (Ex: Publishing Static Dashboards)

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#50371]
### Describe the bug

If you add a time group filter to a dashboard and then customize the "Time Grouping Options" for the filter you can save it. But you cannot subsequently publish the changes to embedded dashboards, move the dashboard to trash, etc. Seems we're sending malformed requests to '/api/dashboard/id'.

### To Reproduce

1. Set up a dashboard
2. Add time group filter
3. See that you can publish the static dashboard
4. Edit the dashboard and customize the "time grouping options" for the filter
5. See that you cannot publish the embedding changes, put the dashboard in the trash, drill into questions, duplicate the dashboard, etc.

https://www.loom.com/share/31b9bad1317b494185c0c093a89ee0de

### Information about your Metabase installation

```JSON
v51.3
```

### Severity

Blocking

### Additional context

If you add all options back to the time filter settings the UX is still broken. As a workaround you can remove the filter completely, add it back and save it without customizing granularity.

**Comment by ixipixi** [comment]
You also can't duplicate dashboards or click card titles to navigate to questions.

**Comment by ranquild** [comment]
It seems that in some cases the BE doesn't convert strings to keywords for `Parameter` ![Image](https://github.com/user-attachments/assets/8f8c9d52-52a2-4982-87aa-05ae77768370)
![Image](https://github.com/user-attachments/assets/2b3df134-4979-4893-8e2f-5dfbf39b6905)

**Comment by JurenaMat** [comment]
@metamben I discovered this issue when working with static embeds again. We've just upgraded to 1.51.4. I see the task as completed under https://github.com/metabase/metabase/pull/50418, when can we expect the fix on prod?

**Comment by metamben** [comment]
@JurenaMat, it should be released in 0.51.6.
