### ISSUE TITLE
SSO/SAML support

### ISSUE THREAD

**Issue by mokra** [metabase/metabase#5039]
HI everyone,
I am searching for a way to create a kind of SAML on metabase. Here is the background:

I have a dashboard where people login. From there they should be able to access metabase (both systems are on the same server). The problem in this case is, that metabase also needs an authentication - so the user would need to login again and this is not very user friendly. I would like to use some kind of SSO or SAML or maybe some other protocol to automatically authenticate the user. 

Best case scenario looks like this:
1. User registers in my dashboard. The registration process would also create the same user (same username & password ) in metabase - which can be created using metabase api. 
2. User logs in into my dashboard and receive some kind of an auth.token from metabase.
3. User clicks on a link containing a token and accesses metabase without the need of logging in. 
4. User logs out of my dashboard and the token will be removed.

There are definitely a lot of different ways to accomplish steps 2 and 3. The easiest way is to pass the username password via GET or POST to metabase, but this is clearly not the most secure one ;) But I am open for any other option.

Thanks a lot in advance

**Comment by pbollu** [comment]
Hello Team @ Metabase,

I tested LDAP in my environment and is working fine. Also please provide SAML or Header based SSO solution to allow users to login automatically.

This feature will enhance the User login experience.

Thank you,
Phani.

**Comment by DCTech2k** [comment]
+1

**Comment by jornh** [comment]
Duplicate of #4308.

**Comment by omiadgaonkar** [comment]
Mine is same case as of @mokra. Any update on this ?

**Comment by camsaul** [comment]
Duplicate of #4308
