### ISSUE TITLE
Permissions to access questions data

### ISSUE THREAD

**Issue by francisco-mooddie** [metabase/metabase#50402]
### Describe the bug

Why is the "Data Access" tab no longer visible in the latest version of Metabase, which used to indicate whether a group/user had access to table data?

I need to filter a group to allow them to view the drill-down of a question only, without being able to edit the original query.

In a previous version, I can still see this option.

![Image](https://github.com/user-attachments/assets/89e12a22-5a20-4a42-bb8c-2bca1ee355b9)

### To Reproduce

1. Go to admin
2. Click on permissions
3. Scroll down to Data -> Groups

### Expected behavior

![Image](https://github.com/user-attachments/assets/87b4a0ec-bc6e-40dc-a848-93d375654f6d)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-PT",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "clickhouse",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-13",
      "tag": "v0.51.3.3",
      "hash": "cd3e26b"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "5.15.0-91-generic",
    "user.language": "en",
    "user.timezone": "Europe/Lisbon"
  }
}
```

### Severity

High

**Comment by luizarakaki** [comment]
`No self-service` has the exact same behavior as Create queries: `No`. There was no change there.

**Comment by francisco-mooddie** [comment]
@luizarakaki But when I had unrestricted access, I could view the data behind the query, and now I can’t, even if I gave all permissions to all users like administrator.

![Image](https://github.com/user-attachments/assets/c3918598-a29b-4a23-a581-91be7d2b8752)

![Image](https://github.com/user-attachments/assets/cb0853ef-6b86-4ce4-b02c-bc3398ac72b4)
