### ISSUE TITLE
Setting a custom loading message prevents questions from loading in Metabase v51

### ISSUE THREAD

**Issue by eskrm** [metabase/metabase#50414]
### Describe the bug

Setting a custom loading message via `MB_LOADING_MESSAGE` on Metabase v51 EE prevents questions from loading. You get a generic "Something’s gone wrong" error instead. The `POST /api/card/:cardId/query` request is canceled by the frontend immediately because of a type error when loading the custom message:

```
TypeError: Cannot read properties of undefined (reading 'value')
```

### To Reproduce

1. Run Metabase v51 EE with a custom loading message, e.g., `MB_LOADING_MESSAGE="Loading..."`.
2. Create or go to a question. When visualizing, it will error our with "Something’s gone wrong".

### Expected behavior

Questions should load when a custom loading message is set.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "tag": "vLOCAL_DEV",
      "hash": "06d1ba2ae111e66253209c01c244d6379acfc6dcb1911fa9ab6012cec9ce52e5"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.2+13-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.2+13-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.0.1",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  }
}
```

### Severity

Just annoying since it works by unsetting the env var

### Additional context

I'm running Metabase EE from the git repo, on tag `v1.51.4.3` without any modifications.

**Comment by dpsutton** [comment]
repro:

```shell
MB_PREMIUM_EMBEDDING_TOKEN=$TOKEN MB_LOADING_MESSAGE="Loading" MB_JETTY_PORT=3006 java -jar $JARS/1.51.4.3.jar
```

Error in browser console:
![Image](https://github.com/user-attachments/assets/e577dfb6-e239-4650-8aab-63734b2bd25f)

![Image](https://github.com/user-attachments/assets/eee7d0f1-5a6d-4b7b-98cb-3c2432f7a895)

```shell
❯ http get http://localhost:3006/api/session/properties x-api-key:$API_KEY -pb | jq '."loading-message"'
"Loading"
```

**Comment by sloansparger** [comment]
@eskrm unfortunately we don't support a completely custom message via `MB_LOADING_MESSAGE`, it must be an enum value of `doing-science`, `running-query`, or `loading-results`. We've just merged a change that will go out in the next release which makes it clearer that this env variable requires an enum input and prevents the UI from breaking if it's not. In your specific case the `loading-results` option would be closest to your desired message.

**Comment by eskrm** [comment]
@sloansparger That's fine, thanks!
