### ISSUE TITLE
Snowflake - Specifying Schema in Database Setup still requires Schema in Queries

### ISSUE THREAD

**Issue by swatland610** [metabase/metabase#50422]
### Describe the bug

In setting up a Snowflake Database connector, I want it to only read one schema from the database - so our users can simply query `select * from <table>` instead of `select * from <schema_name>.<table>`

In the database set up, I selected `Only these...` and specify the only one as `<schema_name>` . It connects successfully. But when I go to build a query with this connection, it will only succeed when I specify what schema needs to read from. 

Additionally, I've tried a combination of `only these` or `all schemas` while also setting `schema=schema_name` in the "Additional JDBC connection string options". The outcomes are the same. Queries work while specifying the schema & table, but will not work with just the table. 

Following the threads from [this closed PR](https://github.com/metabase/metabase/pull/19651) I would expect this action to allow for `select * from <table>` work. 

I am also certain that the snowflake user record is set up with the correct & corresponding `DEFAULT_NAMESPACE` of "database_name.schema_name"

Is this functionality not possible or is this a bug? 

### To Reproduce

1. Go to Metabase Admin. 
2. Connect to a Snowflake Database and select `only these` in Schema. 
3. Then specify the one schema to connect to in the box below. And save the new settings.
4. Build a query and attempt this on one of the tables. `select * from <table_name> limit 10;`
5. You should get a `object not authorized response`
6. Redo your query with `select * from <schema_name>.<table_name> limit 10;` 
7. It should produce results successfully

Alternatively, we tried the "Additional JDBC connection string options" route as well...
1. Go to Metabase Admin. 
2. Connect to a Snowflake Database and select 'All' (we also tried 'Only these`)
3. Set `schema=schema_name` in "Additional JDBC connection string options" and hit save.
4. Build a query and attempt this on one of the tables. `select * from <table_name> limit 10;`
5. You should get a `object not authorized response`
6. Redo your query with `select * from <schema_name>.<table_name> limit 10;` 
7. It should produce results successfully

### Expected behavior

This is explained in the steps to reproduce

### Logs

[50235815-1473-48b8-8ae5-b14459847772] 2024-11-22T14:44:46-06:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: SQL compilation error:
Object '<table_name>' does not exist or not authorized.
{:database_id 80,
 :started_at #t "2024-11-22T20:44:46.243693Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query: SQL compilation error:\nObject '<table_name>' does not exist or not authorized.",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__87286$fn__87287.invoke(execute.clj:717)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__87286.invoke(execute.clj:714)"
    "driver.sql_jdbc.execute$fn__87090$fn__87091.invoke(execute.clj:398)"
    "driver.sql_jdbc.execute$do_with_resolved_connection87060__87061.invokeStatic(execute.clj:338)"
    "driver.sql_jdbc.execute$do_with_resolved_connection87060__87061.invoke(execute.clj:321)"
    "driver.sql_jdbc.execute$fn__87090.invokeStatic(execute.clj:392)"
    "driver.sql_jdbc.execute$fn__87090.invoke(execute.clj:390)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
    "driver.sql_jdbc$fn__113432.invokeStatic(sql_jdbc.clj:79)"
    "driver.sql_jdbc$fn__113432.invoke(sql_jdbc.clj:77)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
    "query_processor.execute$run.invokeStatic(execute.clj:62)"
    "query_processor.execute$run.invoke(execute.clj:56)"
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_76957__76958$fn__76959.invoke(update_used_cards.clj:60)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__76974.invoke(execute.clj:25)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__76980.invoke(execute.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76930.invoke(cache.clj:241)"
    "query_processor.middleware.permissions$check_query_permissions$fn__73967.invoke(permissions.clj:147)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__74678.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__74688.invoke(enterprise.clj:64)"
    "query_processor.execute$execute77007__77008$fn__77009.invoke(execute.clj:94)"
    "query_processor.setup$do_with_qp_setup75203__75204.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup75203__75204.invoke(setup.clj:216)"
    "query_processor.execute$execute77007__77008.invokeStatic(execute.clj:93)"
    "query_processor.execute$execute77007__77008.invoke(execute.clj:89)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
    "query_processor.middleware.enterprise$fn__74705$handle_audit_app_internal_queries__74706$fn__74708.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__74716.invoke(enterprise.clj:103)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware77863__77864$fn__77865.invoke(process_userland_query.clj:204)"
    "query_processor.middleware.catch_exceptions$catch_exceptions77928__77929$fn__77930.invoke(catch_exceptions.clj:132)"
    "query_processor$process_query77969__77970$fn__77971.invoke(query_processor.clj:80)"
    "query_processor.setup$do_with_canceled_chan75198__75199$fn__75200.invoke(setup.clj:187)"
    "query_processor.setup$do_with_database_local_settings75191__75192$fn__75193.invoke(setup.clj:181)"
    "query_processor.setup$do_with_driver75184__75185$fn__75186$fn__75187.invoke(setup.clj:166)"
    "driver$do_with_driver.invokeStatic(driver.clj:106)"
    "driver$do_with_driver.invoke(driver.clj:101)"
    "query_processor.setup$do_with_driver75184__75185$fn__75186.invoke(setup.clj:165)"
    "query_processor.setup$do_with_metadata_provider75175__75176$fn__75177$fn__75180.invoke(setup.clj:151)"
    "query_processor.store$do_with_metadata_provider58710__58711.invokeStatic(store.clj:170)"
    "query_processor.store$do_with_metadata_provider58710__58711.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider58710__58711.invokeStatic(store.clj:159)"
    "query_processor.store$do_with_metadata_provider58710__58711.invoke(store.clj:150)"
    "query_processor.setup$do_with_metadata_provider75175__75176$fn__75177.invoke(setup.clj:150)"
    "query_processor.setup$do_with_resolved_database75165__75166$fn__75167.invoke(setup.clj:128)"
    "query_processor.setup$do_with_qp_setup75203__75204.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup75203__75204.invoke(setup.clj:216)"
    "query_processor$process_query77969__77970.invokeStatic(query_processor.clj:78)"
    "query_processor$process_query77969__77970.invoke(query_processor.clj:71)"
    "api.dataset$run_streaming_query100086__100089$fn__100093.invoke(dataset.clj:84)"
    "query_processor.streaming$_streaming_response$fn__61541$fn__61542$fn__61543.invoke(streaming.clj:176)"
    "query_processor.streaming$_streaming_response$fn__61541$fn__61542.invoke(streaming.clj:174)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
    "query_processor.streaming$_streaming_response$fn__61541.invoke(streaming.clj:171)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
    "async.streaming_response$do_f_async$task__53194.invoke(streaming_response.clj:97)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :snowflake,
    :sql
    ["select"
     "  *"
     "from"
     " <table_name>"
     "limit"
     "  10;"
     "-- {\"pulseId\":null,\"serverId\":\"cc9364b2-c536-43d9-b60d-661d54c973bc\",\"client\":\"Metabase\",\"queryHash\":\"4312c0c7a79a4f9b1f1da8a89e7e69931bc30b375c3da9e4b7f83e389aeb689f\",\"queryType\":\"native\",\"cardId\":null,\"dashboardId\":null,\"context\":\"ad-hoc\",\"userId\":8,\"databaseId\":80}"],
    :params nil,
    :type :invalid-query}}],
 :action_id nil,
 :state "42S02",
 :error_type :invalid-query,
 :json_query
 {:database 80,
  :type "native",
  :native {:template-tags {}, :query "select * from <table_name> limit 10;"},
  :parameters [],
  :middleware {:js-int-to-string? true, :userland-query? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class net.snowflake.client.jdbc.SnowflakeSQLException,
 :stacktrace
 ["net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:176)"
  "net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:109)"
  "net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:490)"
  "net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:396)"
  "net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:498)"
  "net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:215)"
  "net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:149)"
  "net.snowflake.client.core.SFStatement.execute(SFStatement.java:786)"
  "net.snowflake.client.core.SFStatement.execute(SFStatement.java:693)"
  "net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:354)"
  "net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:429)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__87216.invokeStatic(execute.clj:570)"
  "driver.sql_jdbc.execute$fn__87216.invoke(execute.clj:568)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:578)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:575)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__87286$fn__87287.invoke(execute.clj:715)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__87286.invoke(execute.clj:714)"
  "driver.sql_jdbc.execute$fn__87090$fn__87091.invoke(execute.clj:398)"
  "driver.sql_jdbc.execute$do_with_resolved_connection87060__87061.invokeStatic(execute.clj:338)"
  "driver.sql_jdbc.execute$do_with_resolved_connection87060__87061.invoke(execute.clj:321)"
  "driver.sql_jdbc.execute$fn__87090.invokeStatic(execute.clj:392)"
  "driver.sql_jdbc.execute$fn__87090.invoke(execute.clj:390)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
  "driver.sql_jdbc$fn__113432.invokeStatic(sql_jdbc.clj:79)"
  "driver.sql_jdbc$fn__113432.invoke(sql_jdbc.clj:77)"
  "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
  "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
  "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
  "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
  "query_processor.execute$run.invokeStatic(execute.clj:62)"
  "query_processor.execute$run.invoke(execute.clj:56)"
  "query_processor.middleware.update_used_cards$update_used_cards_BANG_76957__76958$fn__76959.invoke(update_used_cards.clj:60)"
  "query_processor.execute$add_native_form_to_result_metadata$fn__76974.invoke(execute.clj:25)"
  "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__76980.invoke(execute.clj:36)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76930.invoke(cache.clj:241)"
  "query_processor.middleware.permissions$check_query_permissions$fn__73967.invoke(permissions.clj:147)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__74678.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__74688.invoke(enterprise.clj:64)"
  "query_processor.execute$execute77007__77008$fn__77009.invoke(execute.clj:94)"
  "query_processor.setup$do_with_qp_setup75203__75204.invokeStatic(setup.clj:225)"
  "query_processor.setup$do_with_qp_setup75203__75204.invoke(setup.clj:216)"
  "query_processor.execute$execute77007__77008.invokeStatic(execute.clj:93)"
  "query_processor.execute$execute77007__77008.invoke(execute.clj:89)"
  "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
  "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
  "query_processor.middleware.enterprise$fn__74705$handle_audit_app_internal_queries__74706$fn__74708.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__74716.invoke(enterprise.clj:103)"
  "query_processor.middleware.process_userland_query$process_userland_query_middleware77863__77864$fn__77865.invoke(process_userland_query.clj:204)"
  "query_processor.middleware.catch_exceptions$catch_exceptions77928__77929$fn__77930.invoke(catch_exceptions.clj:132)"
  "query_processor$process_query77969__77970$fn__77971.invoke(query_processor.clj:80)"
  "query_processor.setup$do_with_canceled_chan75198__75199$fn__75200.invoke(setup.clj:187)"
  "query_processor.setup$do_with_database_local_settings75191__75192$fn__75193.invoke(setup.clj:181)"
  "query_processor.setup$do_with_driver75184__75185$fn__75186$fn__75187.invoke(setup.clj:166)"
  "driver$do_with_driver.invokeStatic(driver.clj:106)"
  "driver$do_with_driver.invoke(driver.clj:101)"
  "query_processor.setup$do_with_driver75184__75185$fn__75186.invoke(setup.clj:165)"
  "query_processor.setup$do_with_metadata_provider75175__75176$fn__75177$fn__75180.invoke(setup.clj:151)"
  "query_processor.store$do_with_metadata_provider58710__58711.invokeStatic(store.clj:170)"
  "query_processor.store$do_with_metadata_provider58710__58711.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider58710__58711.invokeStatic(store.clj:159)"
  "query_processor.store$do_with_metadata_provider58710__58711.invoke(store.clj:150)"
  "query_processor.setup$do_with_metadata_provider75175__75176$fn__75177.invoke(setup.clj:150)"
  "query_processor.setup$do_with_resolved_database75165__75166$fn__75167.invoke(setup.clj:128)"
  "query_processor.setup$do_with_qp_setup75203__75204.invokeStatic(setup.clj:232)"
  "query_processor.setup$do_with_qp_setup75203__75204.invoke(setup.clj:216)"
  "query_processor$process_query77969__77970.invokeStatic(query_processor.clj:78)"
  "query_processor$process_query77969__77970.invoke(query_processor.clj:71)"
  "api.dataset$run_streaming_query100086__100089$fn__100093.invoke(dataset.clj:84)"
  "query_processor.streaming$_streaming_response$fn__61541$fn__61542$fn__61543.invoke(streaming.clj:176)"
  "query_processor.streaming$_streaming_response$fn__61541$fn__61542.invoke(streaming.clj:174)"
  "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
  "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
  "query_processor.streaming$_streaming_response$fn__61541.invoke(streaming.clj:171)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
  "async.streaming_response$do_f_async$task__53194.invoke(streaming_response.clj:97)"],
 :card_id nil,
 :context :ad-hoc,
 :error "SQL compilation error:\nObject '<table_name>' does not exist or not authorized.",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk",
      "snowflake"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-11",
      "tag": "v0.51.3",
      "hash": "d757d0b"
    },
    "settings": {
      "report-timezone": "US/Central"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "5.15.0-1066-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Pretty Big, if this isn't resolved, it's going to delay some data migration work

**Comment by luizarakaki** [comment]
You can specify the default parameter as a JDBC parameter https://docs.snowflake.com/en/developer-guide/jdbc/jdbc-parameters#schema in "Additional JDBC connection string options"

We maybe could do it automatically if you choose a single schema, but the workaround is there

**Comment by swatland610** [comment]
Thank you for the response! @luizarakaki I neglected to mention that I actually tried that too. I have set in the "Additional JDBC connection string options" `schema=schema_name` and the problem still persists. I'll update my submission above to include that

**Comment by luizarakaki** [comment]
@swatland610 can you add here the name of the database, schema, and tables?

Snowflake JDBC driver automatically changes everything to uppercase. So if you have lowercase db/schema/table, you need to define these with quotes and also enable this toggle
![Image](https://github.com/user-attachments/assets/e0b9516f-f74e-4eb1-9a11-d3f469dfdfe6)

This query works in my env:
```select * from "orders"``` if I pass `db=v3_sample-dataset&schema=PUBLIC`

**Comment by swatland610** [comment]
Sure! I will say those that we don't have specific case requirements matching in snowflake for any of database / schema / tables relevant for this. Here's a few examples: 

1. `select * from users limit 10; ` -> does not work
2. `select * from USERS limit 10;` -> does not work
3. `select * from "users" limit 10;` -> does not work

4. `select * from PG_DSCOUT.USERS limit 10;` -> this does work
5. `select * from pg_dscout.users limit 10;` -> this does work

Here's a screeshot of our current set up (but know that we've tried all iterations as I described above)
![Image](https://github.com/user-attachments/assets/a4abd7f7-204d-4ade-9881-728fea0f6fb6)

**Comment by luizarakaki** [comment]
Did you try:
`db=RAW_STITCH&schema=PG_DSCOUT`

In the connection string?

**Comment by swatland610** [comment]
Just tried it now, and it's producing the same result

**Comment by swatland610** [comment]
It's worth calling out that the user record I'm using defaults namespace is `RAW_STITCH.PG_DSCOUT` as well

**Comment by luizarakaki** [comment]
Ok, I think I found something here. The schema name is not being applied, it works only if the schema is "PUBLIC"

**Comment by luizarakaki** [comment]
@swatland610 this was released. Can you confirm it works?

**Comment by swatland610** [comment]
@luizarakaki thanks for your help! It looks like it's working great!
