### ISSUE TITLE
Native parameter mapping is broken after multi-stage filters in dashboards

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#50467]
### Describe the bug

Context https://metaboat.slack.com/archives/C064QMXEV9N/p1732553732526949

### To Reproduce

1. Open https://stats.metabase.com/dashboard/2422
2. Find the "Cohort" card
3. See that the mapping is broken - the filter is not applied and the FE believes it's a "Unknown field" because it cannot match it either

### Expected behavior

It should work as before

### Information about your Metabase installation

```JSON
stats
```

### Severity

P1

**Comment by metamben** [comment]
The DB migration introduced `stage-number` for native query parameters, which resulted in this issue.
