### ISSUE TITLE
Download bug on V0.24.0

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#5047]
If some filters are empty, **the download button is disappeared,** although they are optional parameters. Below are screenshots in two cases: 

With empty filter:
![screen shot 2017-05-10 at 11 30 03 am](https://cloud.githubusercontent.com/assets/2088055/25883417/bb051470-3574-11e7-9b6b-5fcb5b34ea6d.png)

Without empty filter: 
![screen shot 2017-05-10 at 11 31 43 am](https://cloud.githubusercontent.com/assets/2088055/25883423/c0453668-3574-11e7-8d38-d719d4b27806.png)

**Comment by attekei** [comment]
Fixed by https://github.com/metabase/metabase/pull/5099

**Comment by thucnc** [comment]
Hello, is there any plan to release this fix soon, in v0.24.2, as this bug is quite annoyed for my team. Anyway, thank you for developing Metabase. My company really love it.
