### ISSUE TITLE
Sorting doesn't work on columns with custom expressions

### ISSUE THREAD

**Issue by mxmzdlv** [metabase/metabase#5048]
There are cases when sorting doesn't seem to work on columns with custom expressions. If you click on the header and select desc / asc it refreshes the table without ordering applied to the column. Sorting doesn't work when:

1. Using names for custom expressions
2. Using multiple aggregations, e.g.
   `Sum(Total - Tax)` works, but 
   `Sum(Total) - Sum(Tax)` doesn't work.

Generated SQL also doesn't show properly applied ordering.

---
- Browser: Chrome 58.0, Firefox 55.0a1
- Databases: Tried on built-in sample dataset (H2) and BigQuery
- Metabase version: 0.23.1 and 0.24-snapshot
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Comment by mazameli** [comment]
I was able to reproduce this and couldn't make the sorting work in any situation at all.

**Comment by KimchaC** [comment]
I am able to reproduce this too. It seems to only happen if you have any custom expressions, even simple ones like sum()

**Comment by rpsobiran** [comment]
Yup, I'm experiencing the same too. Do we have any timeline on this?

**Comment by EvaSchreyer** [comment]
Hi All, this is still an issue in v0.28. As custom expressions are the only way to rename a column in a nice way (as a custom field will always be named "sum" or "sum2" it would be nice to be able to use custom expressions - but we have to be able to sort by them.

**Comment by TurkerTunali** [comment]
On v0.30.4 problem persists.

**Comment by tlrobinson** [comment]
FYI sorting seems to work if you set the sort under the "..." menu on the right of the query builder bar, it's just the header actions that aren't working. I think this is because the result `cols` don't include the `expression-name`

**Comment by kconti** [comment]
Not sure if this is related, but if we build a question using the SQL query editor, we are unable to sort the columns for that question by clicking on the column.  If we pull it into a dashboard it works fine.  If we click the settings cog and see a preview of the data under the "Data" tab, we can even sort the preview of it.  We just can't sort the question view of it if built with SQL - very odd.  SQL questions don't have the ". . ." menu...so no workaround there.  New questions without making it a SQL query question, the sort works fine.
We are in 0.30.1 and upgrading to 31.2 tonight.

**Comment by tlrobinson** [comment]
As far as I can tell this has been fixed (both clicking table headers and in the sort widget) in 0.31.

**Comment by agoud1993** [comment]
I'm having dashboards which are mainly built with SQL Query Editor. The sorting works in the dashboard level but when we drill into the question level it doesn't.  We are working on 0.31.2 version hopefully you guys should rethink to open the issue and fix it in the upcoming versions.

**Comment by tlrobinson** [comment]
@agoud1993 That's a different issue. Sorting in the query builder works by modifying the query, which we can't do for SQL.
