### ISSUE TITLE
Line/bar series should retain color when pivoting/zooming

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5051]
If a line/bar has a color due to it being a breakout or due to display settings, it should retain that color when pivoting or zooming to help users keep track of what's happening.

**Here's a breakout series:**

![screen shot 2017-05-10 at 10 17 36 am](https://cloud.githubusercontent.com/assets/2223916/25911839/2177eb5c-356a-11e7-82f5-96865649d67d.png)

**When zoomed in, it turns from purple to blue:**

![screen shot 2017-05-10 at 10 17 49 am](https://cloud.githubusercontent.com/assets/2223916/25911912/5b6421e6-356a-11e7-8900-dfe94c8eacc5.png)

**Comment by brunobergher** [comment]
Can't reproduce.
