### ISSUE TITLE
Tutorial is broken in 0.24

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5052]
When going through the tutorial, I get to the date filter part. I click into the filter, and put in 10 days and click add filter and then it doesn't actually advance.

When I go back to the query builder and click on `how do I use this thing?`, it updates the URL but doesn't start the tutorial. If I refresh that url, the tutorial starts. Think there's something wacky going on with how the QB routes are working.

**Comment by salsakran** [comment]
This was closed in 0.24. It was broken in 0.23.1. Did anyone ever report it?

**Comment by tlrobinson** [comment]
I don't believe so. Also we have an E2E test that should cover that.
