### ISSUE TITLE
Pivot Viz will not Load Until Sandboxed User Visits Table the Viz is Built On

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#50545]
### Describe the bug

Can be related to https://github.com/metabase/metabase/issues/50256

If you create a pivot table on TableA, then set up an advanced sandbox group on that table, the sandboxed user cannot view the pivot table results until they visit TableA via "Browse Data"

### To Reproduce

1. Create a pivot table on the Orders table
2. Create test user with "attribute1" = 1
3. Create a native SQL question that contains a parameter for order ID and use it to set up **advanced** sandboxing for Orders (ID = attribute1)
4. Add test user to sandboxed group
5. Assign a value to the attribute for the sandbox
6. Log in as test user and view the pivot table
7. See "Error running query"
8. Go view the table via the data browser (if the user has access to it)
9. Now go back to the Pivot and it works

### Expected behavior

Sandboxed user should be able to see the pivot table

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "athena",
      "mongo",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-10-15",
      "tag": "v1.50.30",
      "hash": "a49cb77"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.15.167.4-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Blocker for a customer

### Additional context

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "athena",
      "mongo",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-10-15",
      "tag": "v1.50.30",
      "hash": "a49cb77"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.15.167.4-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}

**Comment by metamben** [comment]
@ixipixi, I was unable to reproduce the issue on `master` at 9cc1a46c8a. Can you? If  you can, could you please record a loom?

**Comment by ixipixi** [comment]
@metamben I can't repro on master. Noah suspected this was probably the same issue that was fixed with this PR: https://github.com/metabase/metabase/pull/50049

**Comment by metamben** [comment]
@ixipixi should this be kept open then? Note that I failed to reproduce it with `v1.50.30` too.

**Comment by ixipixi** [comment]
@metamben I can still repro on 50.30 but I just ran through it on 51.6 and can't repro there - so I think we can safely call this fixed.
