### ISSUE TITLE
Line chart dots don't have `cursor: pointer` when hovering

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5056]
This is on chrome. All the other charts have it.

**Comment by tlrobinson** [comment]
They weren't clickable before, I don't think it was ever added.

**Comment by mazameli** [comment]
Could have sworn it was present at some point in one of the drill-through branches, but I might be hallucinating.

**Comment by tlrobinson** [comment]
I think it's due to the voronoi overlay blocking the `cursor: pointer`, which is only used when there are < 500 dots.

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/15382
