### ISSUE TITLE
In the object details, if a given FK has only a single entry, clicking it should take me to the object detail for that row

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5058]
Right now we display the number of records with an FK pointing to it in the right hand pane.

If there is only 1, it would be cool if I could get straight to that record. Right now I need to click on it, go to the list, click on the record, and then click "view details". Feels pretty cumbersome.

**Comment by brunobergher** [comment]
This seems to refer to old UI we don't have anymore, closing.
