### ISSUE TITLE
Export CSV button on cards does not work

### ISSUE THREAD

**Issue by rodrigoGA** [metabase/metabase#50603]
### Describe the bug

The Export CSV button for cards in dashboards does not work. When attempting to export a card's data using the button, Metabase makes a request to:

```
POST /dashboard/api/4/dashcard/6/card/7/query/csv
```

This results in a 404 Not Found error. The following is logged:
```
WARN middleware.log :: POST /api/4/dashcard/6/card/7/query/csv 404 129,8 µs (0 DB calls) {:metabase-user-id 3}
metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}
```

However, manually executing a POST request to:
```
POST /dashboard/api/card/7/query/csv
```
successfully downloads the data in CSV format.

Here is an example of the cURL command that works:
```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Cookie: JSESSIONID=...; metabase.DEVICE=...; metabase.SESSION=...; metabase.TIMEOUT=..." \
  -d '{"parameters": []}' \
  "https://<my-metabase-url>/dashboard/api/card/7/query/csv"

```

This indicates the Export CSV button is pointing to the wrong endpoint.

### To Reproduce

1. Open a dashboard with cards in Metabase.
2. Click the Export CSV button on a card.
3. Observe the error in the logs

### Expected behavior

The Export CSV button should correctly call the api and download the data in CSV format without requiring a manual POST request.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-19",
      "tag": "v0.51.4",
      "hash": "47f05f3"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.114.2.el7.x86_64",
    "user.language": "es",
    "user.timezone": "Europe/Madrid"
  }
}
```

### Severity

high

**Comment by rodrigoGA** [comment]
Just to clarify: it also happens with the other types of downloads on the dashboard cards.

**Comment by dpsutton** [comment]
I'm not able to recreate this. On 1.51.5 i can download results from a dashcard:
![Image](https://github.com/user-attachments/assets/8f6780a4-43bd-4f17-842e-9431010f6a0c)

The network tab shows that my browser requested `http://localhost:3006/api/dashboard/9/dashcard/68/card/85/query/csv`

On the backend I have a log that the browser hit
```shell
2024-11-27 21:11:31,933 DEBUG middleware.log :: POST /api/dashboard/9/dashcard/68/card/85/query/csv 200 [ASYNC: completed] 85.0 ms (23 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (7 idle, 0 queued) (110 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/9 (0 threads blocked) {:metabase-user-id 1}
```

But one thing I want to point out is that i'm hitting 
`api/dashboard/<dash-id>/dashcard/<dashcard-id>/card/<card-id>/query/<format>`

You have several different formats listed:
`POST /dashboard/api/4/dashcard/6/card/7/query/csv` (api is after dashboard)
`POST /api/4/dashcard/6/card/7/query/csv` (missing dashboard)
`POST /dashboard/api/card/7/query/csv` (missing dashcard, dashcard id, api after dashboard)

I only point this out because these all look like they were copy-pasted from logs and network tabs so it's surprising that there were transcription errors. Can you put the _exact_ routes (omit the domain of course) that are 404'ing and also where exactly in the UI you are initiating the download?

I'm getting the above routes `http://localhost:3006/api/dashboard/9/dashcard/68/card/85/query/csv` and getting these downloads when viewing a dashboard, clicking the three dots on a dashcard and clicking download results:

![Image](https://github.com/user-attachments/assets/060fb8a0-b03c-49c4-840a-77fd1b9e3744)

**Comment by rodrigoGA** [comment]
In my case, Metabase is behind an Apache server, and the URL where Metabase is deployed is: **subdomain.domain.com/dashboard**

If I try to download data from a card, I see the following in the browser console:

![Image](https://github.com/user-attachments/assets/15f83624-dba1-4fcc-9b6d-c6f3ca045e5e)

![Image](https://github.com/user-attachments/assets/b70c5f06-ed42-45ba-ba54-e86abf235c59)
The server log:
![Image](https://github.com/user-attachments/assets/d43d6e4c-c5ed-4bee-b829-de7819fe1d71)

Now I tried to replicate the behavior from the console by extracting the cookies from the browser, and I got the same result.

In the list of APIs, I couldn’t find the /dashcard API, but I found the card API: https://www.metabase.com/docs/latest/api/card.

So, I attempted to make a POST request to that API, and the CSV was successfully downloaded.
```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Cookie: JSESSIONID=..; metabase.DEVICE=...; metabase.SESSION=...; metabase.TIMEOUT=alive" \
  -d '{"parameters": []}' \
  "https://midominio.com/dashboard/api/card/7/query/csv"
```

Therefore, the issue might be related to the fact that my Metabase is deployed behind /dashboard, and this is configured on the Metabase site.

![Image](https://github.com/user-attachments/assets/0ea7f3a8-42d5-4e25-8a06-3eb71cd1d370)


Perhaps there is an issue with how URLs are handled in the backend. It is strange that the POST is made to the dashboard API, but the backend logs show dashcard.

**Comment by rodrigoGA** [comment]
Here is an example of how to reproduce it:

1.Start the following Docker Compose
[docker-compose-config.zip](https://github.com/user-attachments/files/17966678/docker-compose-config.zip)
2. Go to localhost:3000 and set up Metabase.
3. Then go to Settings > General > Site URL and set it to localhost/dashboard.
4. Open localhost/dashboard in your browser, where Metabase will be located.
5. Go to a sample dashboard and try to download a card.

**Comment by paoliniluis** [comment]
@rodrigoGA you're seeing https://github.com/metabase/metabase/issues/30895, and also, you're not rewriting correctly every request that goes to the backend
