### ISSUE TITLE
Public dashboard does not have field values for a category filter

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5060]
Using a public link for a dashboard with a category filter, the publicly viewed dashboard does not show the field values.

Inside MB
<img width="555" alt="screen shot 2017-05-10 at 11 46 25 am" src="https://cloud.githubusercontent.com/assets/107439/25915474/6e02e0ce-3576-11e7-8822-8ab7a017b1df.png">

Public Link
<img width="1440" alt="screen shot 2017-05-10 at 11 46 38 am" src="https://cloud.githubusercontent.com/assets/107439/25915480/71e04b96-3576-11e7-8ec7-9e9a66e11970.png">

**Comment by tlrobinson** [comment]
I'm having trouble reproducing this. Is there more than one dashcard?

**Comment by attekei** [comment]
I couldn't reproduce either on any of my dashboards, and I tested similar scenarios yesterday as I tried to reproduce #4832. Is there anything odd in the console while that happens?
