### ISSUE TITLE
Questions list looks empty if you haven't created questions yet

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#5061]
In a fresh installation, it's only showing the collections empty state:

<img width="989" alt="screen shot 2017-05-10 at 11 52 00" src="https://cloud.githubusercontent.com/assets/6034928/25915816/7dae98e6-3577-11e7-8c9e-5caa91de9165.png">

We already talked with @mazameli that adding a "You don't have any saved questions yet" text is a reasonable for this.

**Comment by salsakran** [comment]
fixed by #5080
