### ISSUE TITLE
If you exit fullscreen in night mode, are you supposed to stay in night mode?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5062]
This is on a public dashboard on chrome, 0.24-rc5. It's a little weird since the day/night toggle goes away when exiting fullscreen:

<img width="1372" alt="screen shot 2017-05-10 at 11 56 45 am" src="https://cloud.githubusercontent.com/assets/2223916/25915958/ee71ded0-3577-11e7-8c7d-1acb74da4ece.png">

**Comment by tlrobinson** [comment]
For public links / embeds you can change the theme via the URL, so you could have actually started with the "night" theme. Since this is a pretty edgey edge case I'd rather not add code to "remember" which theme you started on when entering fullscreen.

**Comment by brunobergher** [comment]
This is ultimately about missing dark mode, which is handled elsewhere. Closing
