### ISSUE TITLE
When setting/resetting password, `sign in with your new password` shouldn't make you retype your password again

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5063]
It should just log you in. (I don't believe this is a 0.24 regression.)

![screen shot 2017-05-10 at 12 18 19 pm](https://cloud.githubusercontent.com/assets/2223916/25916826/e26b60fe-357a-11e7-8c75-d7ad9b70315d.png)

![screen shot 2017-05-10 at 12 18 24 pm](https://cloud.githubusercontent.com/assets/2223916/25916839/ecbed0a4-357a-11e7-8c94-b6fa54bc8fd5.png)

![screen shot 2017-05-10 at 12 18 28 pm](https://cloud.githubusercontent.com/assets/2223916/25916843/ef813b42-357a-11e7-93b5-ce38b5cb3c07.png)

**Comment by luizarakaki** [comment]
As of 46 😂, we don't require a pw retype after reset.
