### ISSUE TITLE
Field filter dropdowns do not work for view-only users

### ISSUE THREAD

**Issue by ChloePont** [metabase/metabase#50645]
### Describe the bug

When you create a question with a field filter with a dropdown option, people with "curate" rights can see the filter dropdown, but people with "view" rights only see a free-form field without auto-completion. 

### To Reproduce

1. Create a question with a field filter with a dropdown.
2. Connect with a user who only has View rights for this question
3. Try to use the filter
4. See the absence of filter options

### Expected behavior

The filter should have a dropdown list of values.

### Logs

The `values` endpoint is never called with a View role, while it is called with a Curator role. 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-26",
      "tag": "v0.51.5",
      "hash": "d79d949"
    },
    "settings": {
      "report-timezone": "UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9-post-Ubuntu-1ubuntu124.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9-post-Ubuntu-1ubuntu124.04",
    "os.name": "Linux",
    "os.version": "5.10.228-219.884.amzn2.aarch64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Blocking some users

**Comment by ranquild** [comment]
@ChloePont I couldn't reproduce the issue you described. The only way I managed to get something similar is if the other user doesn't have access to the source question/model used for the dropdown options at all. Is that what you've been experiencing? 

![Image](https://github.com/user-attachments/assets/f1133922-10bc-4c45-9911-ce390653ca31)

**Comment by ChloePont** [comment]
Thank you for getting back to me @ranquild 🙏 

Yes, that's correct, the user wouldn't have access to the underlying model (in our setup, we only want users to access specific prepared questions, but we don't want them to access unfiltered data).

The screenshot you added is exactly what we're experiencing 👍 (the values endpoint is either not called or returns a 403)
