### ISSUE TITLE
getting JDBC driver internal error: when setting snowflake connection

### ISSUE THREAD

**Issue by udil-brightdata** [metabase/metabase#50641]
**Describe the bug**
trying to set a connection to snowflake.

**Logs**
JDBC driver internal error: exception creating result java.lang.NoClassDefFoundError: Could not initialize class net.snowflake.client.jdbc.internal.apache.arrow.memory.RootAllocator at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.<init>(SnowflakeResultSetSerializableV1.java:368).

**Metabase Diagnostic Info**

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-26",
      "tag": "v0.51.5",
      "hash": "d79d949"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.10+0",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "17.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.10+0",
    "os.name": "Mac OS X",
    "os.version": "15.1.1",
    "user.language": "en",
    "user.timezone": "Asia/Jerusalem"
  }
}
```

**Comment by paoliniluis** [comment]
Please use Java 11
