### ISSUE TITLE
There are a few places where logs are still colorized even if colorization is disabled

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5068]
Only a tiny handful of places. About ~1% of the logs are still colorized

![screen shot 2017-05-10 at 1 12 56 pm](https://cloud.githubusercontent.com/assets/1455846/25919098/74d121fc-3582-11e7-825e-b35c2056dc14.png)

It looks like we're only checking the value of `MB_COLORIZE_LOGS` in the function `format-color`. We should check it in `pprint-to-str` as well since that is also occasionally used to generate colorized output.

**Comment by salsakran** [comment]
note that elastic beanstalk logs also don't render emoji/colors properly.
