### ISSUE TITLE
Feature request: export data in public and embedded links/dashboards

### ISSUE THREAD

**Issue by PekopT** [metabase/metabase#5070]
That will be nice I think

**Comment by flamber** [comment]
Hi @PekopT 
I'm not sure which version you tested, but try the newest version - 0.31.2
It supports export via embedded dashboards and export via public questions.

**Comment by flamber** [comment]
Export of data from Embedded dashboard/question was added in 0.30.0
#6687 - Public Shared doesn't have that option as of 0.35.3
