### ISSUE TITLE
Metabase rounding 17 digit strings

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5076]
Reported on Discourse here: http://discourse.metabase.com/t/bug-metabase-rounding-17-digit-strings/748

> I've got a very strange bug/feature appearing in one of my tables where a certain bit of user data (the Steam ID) is having it's last digit rounded to the nearest 10. So 765611980024149**61** becomes 765611980024149**60**

Was originally reported a long time ago, but seems like a recent comment shows it's still an issue.

**Comment by tlrobinson** [comment]
I'm guessing this is because Javascript can't represent extremely large numbers. If you type `76561198002414961` in a Javascript console you'll get back `76561198002414960`.

**Comment by camsaul** [comment]
this is almost certainly because it's interpreting the results somewhere as a 64-bit floating point number somwhere

```clojure
(double 76561198002414961M) ; -> 7.656119800241496E16
```

**Comment by tlrobinson** [comment]
Perhaps IDs should always be treated as strings, at least as far as the frontend is concerned.

**Comment by vk4ut** [comment]
I've run in to this issue also. Both the value displayed in the table and the values applied by a filter are rounded (filter doesn't work). Digging deeper it's certainly related to the 'number' type being 64 bit floating point number --> http://www.ecma-international.org/ecma-262/5.1/#sec-8.5

**Comment by flamber** [comment]
Closing in favor of #5816
