### ISSUE TITLE
Wrong database_type value

### ISSUE THREAD

**Issue by smiecielica-billtech** [metabase/metabase#50771]
We are experiencing problems with database_type field in metabase_fields table. When given field has a type from schema eg. "test_schema"."category" the value in the database_type is only "category". There is not such a a type in the public schema so the SQL queries behind the questions/dashboard are not working at all. When I update it manually it works till next automatic database update. There is also possibility to have same type both in public and some schema, so it need to have a schema prefix.

We have been using metabase on this database for more than one year. We didn't have any problems with fields. Now after latest update we are using current stable metabase version which is:
version v0.51.6
Built on 2024-11-28
and the bug shows up.

Please fix it or give some advice how to handle this bug. Thank you! 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pl",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-28",
      "tag": "v0.51.6",
      "hash": "fc77ed4"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "5.15.0-1057-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blocking usage,sql queries not working

**Comment by smiecielica-billtech** [comment]
@luizarakaki Hi, thanks for answering my issue. 
Here is screenshot from metabase_field:
![Image](https://github.com/user-attachments/assets/761d78ab-0fae-4e8f-82c4-e30f3bd77e4f)
You ca see that there is column database_type which should determine the exact type in the database.
For example you can see type DeliveryDispatchType. By default the query search for the type in public.DeliveryDispatchType (or how it is set in search_path in postgresql). But we have two types schema1.DeliveryDispatchType and schema2.DeliveryDispatchType.
In this case the column value should be "schema1"."DeliveryDispatchType" and "schema2"."DeliveryDispatchType" (depend to which table it refers). Now we get an error while entering the question:
![Image](https://github.com/user-attachments/assets/2d78830d-9944-44c6-be97-07684f9b5c4e)
(I know screenshot tells about ListingType but this is the same case)

It cannot find given database_type in out database. We cannot solve it by adding extra schemas in search_path config of postgres because Metabase wouldn't know how to differentiate same type name in different schemas.

**Comment by luizarakaki** [comment]
Thanks for the clarification. Something is off about `database_type`, it should be the database data type, not the column name

**Comment by smiecielica-billtech** [comment]
@luizarakaki the name is correct, but is is missing schema prefix

**Comment by luizarakaki** [comment]
The schema isn't defined in metabase_field. It is defined in metabase_table

**Comment by luizarakaki** [comment]
Can you check if `schema` in `metabase_table` is correct?

**Comment by smiecielica-billtech** [comment]
I have "schema X", which uses types from "schema Y". So if I have a field in table in "schema X" and the fields that return a value with type from "schema Y" it won't work. 
Previously in Metabase schema was saved in the metabase_field table as on the screen below:
![Image](https://github.com/user-attachments/assets/c39a68f9-f4dc-47fb-82b7-8719d4bcea44)
