### ISSUE TITLE
Allow database filter to drive multiple field variables 

### ISSUE THREAD

**Issue by malkomalko** [metabase/metabase#5082]
I looked for this issue but could not find it.  I love the field variables you can use for sql queries and think it's wonderful that you can hook them up to dashboard filters... but I've hit a wall.

I have a query that uses a sub query and requires two different variables to drive filtering by a date range.  Table A has a column called timeA and table B has a column called timeB for example.

If I use that question in a dashboard with a date filter, I can only select one of the variables from the question.  It would be great if I could select multiple OR have some type of variable syntax to change the field name.  {{timeA:timeB}} where it would take the timeA field variable and change the field name used in the variable to timeB.  Then it wouldn't matter about selecting multiple for dashboard filters and you could just assign to timeA.

Does this make sense?

**Comment by malkomalko** [comment]
In fact, the second option would be ideal because the questions themselves would work with just one variable field.

**Comment by flamber** [comment]
Closing in favor of #4509/#3156. Related to #3324
