### ISSUE TITLE
Allowing empty entity_id's leads to app db inserting duplicate entities which ends up with serialization not working anymore

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#50830]
### Describe the bug

Seems that we're being very generous here, and the fact that we try to do the backfill when we do exports will break the process if users have done wrongly in the past if they import stuff with null entity id's

### To Reproduce

1) start Metabase from scratch, just a blank instance
2) now create a collection, let's say "abc"
--- state of the app db till this step is ---
![Image](https://github.com/user-attachments/assets/c0b4eca2-387d-4aaf-bf43-88fcffaf5e49)
---end state---
3) do an export (curl "http://<url>/api/ee/serialization/export?database_secrets=false&field_values=false&data_model=false&settings=false" -X POST -o export.tar.gz --header "Cookie: metabase.SESSION=xxxxxxxxxxxxxxx")
4) unzip it
5) open the yaml file of the newly created collection and make the entity_id a null value (just to reconfirm, it will have an entity_id, you need to make it null), e.g. like
![Image](https://github.com/user-attachments/assets/0e272839-55f6-406c-a7e7-f559ec1090a6)
6) now zip it and import it
--- state of the app db till this step is ---
![Image](https://github.com/user-attachments/assets/b75070ac-293f-4552-97fc-cf916ed55533)
check the null in the entity id
---end state---

7) now reuse the same bundle you had from the previous export and now wipe the entity id key completely, zip it and import it again
--- state of the app db till this step is ---
![Image](https://github.com/user-attachments/assets/9839ddde-87a9-45ca-aa61-f4c46c2887bb)
check the collection being duplicate, one with entity id, the other without
---end state---

8) now you won't be able to export anything since we'll want to seed the app db, but we can't

```
2024-12-04 00:38:36,789 INFO v2.backfill-ids :: Backfilling entity_id for 1 rows of Collection
2024-12-04 00:38:36,804 ERROR serialization.api :: Error during serialization: ERROR: duplicate key value violates unique constraint "collection_entity_id_key"
  Detail: Key (entity_id)=(VwkhS217DKxiXQyVjBzaK) already exists.
  caused by: ERROR: duplicate key value violates unique constraint "collection_entity_id_key"
  Detail: Key (entity_id)=(VwkhS217DKxiXQyVjBzaK) already exists.
```

### Expected behavior

We shouldn't allow empty entity id's? why did we allow this?

### Logs

above

### Information about your Metabase installation

```JSON
probably since v50
```

### Severity

P1

**Comment by thebiglabasky** [comment]
Out of curiosity, in what situations would one want to nullify an entity ID? I'm wondering about the use case or reason why this happens?

**Comment by bshepherdson** [comment]
We have occasionally suggested that people blank that column in their appdb if there are bad values in it, but they should get regenerated with the hash-based values before any serdes action. I'm not sure why one would blank it in the exported files.

I'm not sure how this would come up in practice, so it's hard to see this as a P1 bug. Yes, deleting key information from an export will make import do odd things, but why would that ever happen?

That said, I think it makes sense to reject an import if it's malformed, including if it's missing an `entity_id` on anything. Those should have been added before the export.

**Comment by ixipixi** [comment]
https://github.com/metabase/metabase/issues/50106

**Comment by paoliniluis** [comment]
Then this is a duplicate
