### ISSUE TITLE
Filtering on a multi stage question in MongoDB results in a non-working query

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#50832]
### Describe the bug

For some reason we end up with MBQL in the results of a Mongo query when there's a multi stage question

### To Reproduce

1) use a Mongo database
2) use the orders table
- first stage do a distinct count of product id by created_at: day
- second stage do a cumulative sum of the distinct value of the first stage, by day
- third stage do a filter on any date of the previous stage
3) run the query and see the results
![Image](https://github.com/user-attachments/assets/38a6a54e-6e4f-46ef-83c2-4a39536b08ba)

### Expected behavior

The query should run and we should see results?

### Logs

NA

### Information about your Metabase installation

```JSON
v51,probably comes from many versions before, at least 49
```

### Severity

P1

### Additional context

NA

**Comment by wzimrin** [comment]
Worth noting that the fix for this will only work in mongo version 5 or later.  In older versions, if you are using a cumulative sum or cumulative count, that has to be the final stage.  Doing a filter or the like afterwards will cause this error.
