### ISSUE TITLE
Support connection URIs for MongoDB and JDBC databases

### ISSUE THREAD

**Issue by davidmir** [metabase/metabase#5084]
It would be quite useful to support a url to connect to multiple instances of mongodb to guarantee availability.

```
host1[:port1][,host2[:port2]
```

https://docs.mongodb.com/manual/reference/connection-string/

Thanks

### Notes from 05/14/2020 Meeting:

- need to make sure we obfuscate the connection URI on subsequent views so passwords aren't visible in plaintext
- I think we actually want to support 3 different options: broken out details, connection URI, or URI + separate password/username

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
I think for implementing this we should just allow connection URIs as an alternative to broken-out connection details for all DBs that support it (MongoDB and the JDBC ones at the very least) -- it would allow us to close out a whole class of issues. A good chunk if not most of these https://github.com/metabase/metabase/search?p=1&q=connection+string&state=open&type=Issues

**Comment by camsaul** [comment]
Notes from our meeting about this today:

- need to make sure we obfuscate the connection URI on subsequent views so passwords aren't visible in plaintext
- I think we actually want to support 3 different options: broken out details, connection URI, or URI + separate password/username
