### ISSUE TITLE
Labels still showing up, but no label controls

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5089]
We've been planning for a while to rip out the old labels code in favor of switching over to Collections completely, but the behavior was supposed to be that if your instance had labels already, when you upgraded you'd still see those labels and you'd also see the UI controls to edit those labels. 

On our stats instance right now, however, labels are still showing up, but the Labels dropdown is missing entirely, meaning there's now no way to remove or edit those labels. 😱 

<img width="481" alt="screen shot 2017-05-11 at 1 40 18 pm" src="https://cloud.githubusercontent.com/assets/2223916/25970977/83f36d52-364f-11e7-925b-87b5ed596c0f.png">

We should either put the dropdown back so people can migrate off of labels, or pull the bandaid off and get rid of labels entirely. The latter path seems like a bigger deal, and probably shouldn't be in a point release.

**Comment by mazameli** [comment]
Kinda sorta related to https://github.com/metabase/metabase/issues/4960

**Comment by flamber** [comment]
Hi @mazameli 
Wasn't labels totally killed off in 0.30 - maybe even earlier?
