### ISSUE TITLE
Date Variable replaces ? in string literals with date variables, makes syntactically incorrect queries

### ISSUE THREAD

**Issue by mcpeterson** [metabase/metabase#5091]
metabase version: 0.23.0
repro: question mark in a string literal causes metabase to prematurely inject date variables into the string literal:
db: BigQuery
hosting: beanstalk

query:
breaks:
#standardSQL
select '?mystring', {{start_date}}

works:
#standardSQL
select 'mystring', {{start_date}}

**Comment by flamber** [comment]
Closing in favor of #7325
