### ISSUE TITLE
[QUERY EDITOR] Unable to join a subquery anymore since update to 0.52.1

### ISSUE THREAD

**Issue by labiloute** [metabase/metabase#50924]
### Describe the bug

Hi !
This issue take place in the question editor of version 0.52.1.
In previous releases (0.51.x), we where able to join data from tables and if needed, from any other previously saved queries (that make a subquery).
In this release, only tables are proposed to be "JOINed" by the assistant.

### How to reproduce : 

- Select a table, open the query editor
- click on "Join data"
- click on "Select Data"
- only the tables are proposed, not all the queries like it was before

Consequence = unable to run subquery based on already saved query.

### Information about my Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-12-04",
      "tag": "v0.52.1",
      "hash": "5bc320b"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.16 (Debian 13.16-0+deb11u1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.12+7-Debian-2deb11u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-17",
    "java.version": "17.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.12+7-Debian-2deb11u1",
    "os.name": "Linux",
    "os.version": "5.10.0-32-amd64",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  }
}
```

### Severity

High

**Comment by paoliniluis** [comment]
have you clicked on "saved questions" on the top @labiloute ![Image](https://github.com/user-attachments/assets/1d0ed394-9ac4-4f71-ae69-60d002e983db)?

**Comment by labiloute** [comment]
> My bad !Message ID: ***@***.***>
>
> My bad !

I had to clear my cache.

Thanks a lot an sorry for inconvenience.

Cheers
