### ISSUE TITLE
flaky test in `queue-test`

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#50948]
### Describe the bug

```clojure
FAIL in metabase.util.queue-test/delay-queue-test (queue_test.clj:92)
expected: (nil? (queue/take-delayed-batch! q 3 90 0))
  actual: (not (nil? [689583922888]))
```

### To Reproduce

run the test

### Information about your Metabase installation

```JSON
master
```

### Severity

p2

**Comment by dpsutton** [comment]
https://github.com/metabase/metabase/actions/runs/12183946047/job/33986704000?pr=50941

**Comment by crisptrutski** [comment]
Haven't seen the issue again, can open if we do.
