### ISSUE TITLE
Error processing query: write beyond end of stream - Sustained More than 80% CPU

### ISSUE THREAD

**Issue by li-xiaolu** [metabase/metabase#50973]
### Describe the bug

The CPU of the metabase remained at around 80% for two days, and there were a large number of "Error processing query: write beyond end of stream" errors in the log.

### To Reproduce

As it is the customer's operation, we do not know the specific operating procedures.
But we have found some abnormal phenomena: 
1 We checked the execution status of queries and found that queries related to the same table were executed approximately 100000 times in the past two days. However, I checked the API requests during the same period and found that there were no API requests for a long time in between, but queries were executed. I don't understand why this situation occurred.
2 We found that the CPU has been at around 80% for the past two days.
3 There are a large number of 'Error processing query: write beyond end of stream' errors in the log.
![Image](https://github.com/user-attachments/assets/03e5a8ee-cd4f-4ab0-9fca-76f823c74ffb)
![Image](https://github.com/user-attachments/assets/a97f0278-c0f4-4a9a-a629-d8236c607c40)![Image](https://github.com/user-attachments/assets/4c900c6b-1a7d-4e08-b4f1-47e80885aac5)![Image](https://github.com/user-attachments/assets/872a2c7e-7984-467d-a1d4-812f9f13c504)
![Image](https://github.com/user-attachments/assets/1a724ac0-4c64-4278-b760-f6e28df7cb00)
![Image](https://github.com/user-attachments/assets/f31e6bbb-e3ff-4121-9158-f161a43ec516)
![Image](https://github.com/user-attachments/assets/c1001942-f8a0-40d6-bcde-9f09a3443784)![Image](https://github.com/user-attachments/assets/ffc4e823-1d24-47fa-8acf-f9869cf815b4)
![Image](https://github.com/user-attachments/assets/a61a0dcc-d813-4856-bf33-85e6b75209cc)

### Information about your Metabase installation

```JSON
We are currently using version 0.46.6.4
{
  "browser-info": {
    "language": "ja",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7-LTS",
    "os.name": "Linux",
    "os.version": "5.10.226-214.880.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Japan"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.32"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "?",
      "tag": "vUNKNOWN",
      "branch": "?",
      "hash": "?"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking some users

**Comment by paoliniluis** [comment]
Please upgrade to the latest version, we have fixed a ton of bugs since then
