### ISSUE TITLE
Locale configuration not working in static embedding after upgrading to v0.52.1

### ISSUE THREAD

**Issue by rodrigoGA** [metabase/metabase#50986]
### Describe the bug

I recently upgraded to Metabase v0.52.1, and the locale configuration in static embeddings has stopped working. According to the changelog, the following feature was introduced:
```
Language localization in static embedding with hash parameter #locale=xx
```
Before upgrading, I had several static embeddings where all dashboards were designed to display in English. These dashboards were embedded using the following format:
```
.../embed/dashboard/...?locale=en#...

```
This worked perfectly fine in previous versions. However, since the update, this functionality is broken.

I also tried changing the locale configuration to:
```
.../embed/dashboard/...#locale=en&...
```
But this doesn’t work either.

I saw in the PR that there’s support for public dashboards, but it seems like this might have introduced a regression in static embeddings. The discrepancy between the changelog and the actual behavior is quite confusing.

### To Reproduce

1. Embed a dashboard using the URL format: .../embed/dashboard/...?locale=en#...
2. Verify if the locale configuration works as expected after upgrading to v0.52.1.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-12-04",
      "tag": "v0.52.1",
      "hash": "5bc320b"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.114.2.el7.x86_64",
    "user.language": "es",
    "user.timezone": "Europe/Madrid"
  }
}
```

### Severity

high

**Comment by albertoperdomo** [comment]
Hello @rodrigoGA ,

thanks for reaching out. In Metabase 44, we introduced this functionality for interactive embedding. It seems, as a side-effect, this was also accidentally introduced for static embedding, but wasn't fully working, and it was never meant to be released. To this extent, this was not part of our official documentation.

In 52, we've had to implement a new feature for this to work properly, and as a result, we've decided to clean things up.

**Comment by rodrigoGA** [comment]
@albertoperdomo I think we are not understanding each other, or your message has not been clear enough.
The changelog states the following:
```
Language localization in static embedding with hash parameter #locale=xx  
```
That doesn't work with static embedding, as I explained, so it should be considered a bug.

On the other hand, static embedding already supported the locale parameter in the form locale=xx#, but it stopped working.
Now the locale as #locale=xx, as mentioned in the changelog, also doesn't work!

Your message is confusing. According to what you are saying, have you actually removed localization support for static embedding?
Shouldn't that changelog line state that you removed support rather than saying you added it?

As a developer, I can tell you it's very frustrating to convince a client to use metabase, explain and show them it has a functionality to always keep localization in English (which is documented in your forums), only for that functionality to be removed in the next version.

**Comment by albertoperdomo** [comment]
@rodrigoGA 

>Language localization in static embedding with hash parameter #locale=xx  

Ok, I can get the confusion. Sorry about the lack of clarity.

It should work, but requires a Pro or Enterprise license. I will see that we amend the release notes to include this bit.
We have removed the support for `?locale`, which was never meant to be introduced and wasn't fully working.

Can you provide some links to the forum discussions where we suggest using this method? I am aware of threads where we mention that this only worked for interactive embedding. It seems at some point, this started working for static embedding by accident but wasn't fully working (no localized downloads, for instance).

**Comment by rodrigoGA** [comment]
Thank you for the clarification, but I would like to express my dissatisfaction as a developer who recommends Metabase to clients. This decision has directly impacted dashboards in production.

It’s common for applications to be multilingual, but Metabase does not support multiple languages in static texts, such as titles and labels. Setting a fixed language was the most sensible solution to avoid inconsistencies in the dashboards.

I’ll leave a quote from your own words in another issue,:

> This is supported since 44 in
> 
> * regular app usage, e.g. `https://mymb.metabaseapp.com/dashboard/1-a-look-at-invoices?locale=de-DE`
> * interactive embedding, e.g. `https://mymb.metabaseapp.com/dashboard/1-a-look-at-invoices?locale=de-DE`
> * static embedding, e.g. `https://mymb.metabaseapp.com/embed/dashboard/TOKEN?locale=de-DE#theme=night&background=false&bordered=true&titled=true")`
> * public links, e.g. `https://mymb.metabaseapp.com/public/dashboard/UUID?locale=de-DE`


I hope that in the future you consider more carefully the impact that removing existing functionalities has on users. With this change, dashboards are now broken and unpolished, seriously affecting their presentation.

Could you clarify which is the minimum plan we would need to upgrade to in order to regain this functionality? Please note that, for privacy reasons, the client requires the Metabase instance to remain self-hosted.

**Comment by albertoperdomo** [comment]
Hello @rodrigoGA .

Yes, I understand your frustration, and I am really sorry about it.

If you scroll up on the same issue, you will find a comment saying it was introduced in 44 but only for interactive embedding.
I did publish that comment on Aug 23 because when we discovered that it was working, but we later realized that it wasn't working as expected and then later followed up with another comment on September 9. 

I should have probably updated or removed the comment to not mislead people into believing it's something they should use. It's currently hidden.

This feature requires a Pro subscription (available for self-hosting as well as cloud), which also removes the Powered by Metabase banner, adds the ability to hide downloads, and customizes the embedding font and appearance settings.

**Comment by albertoperdomo** [comment]
Follow up, @rodrigoGA, am I reading right that you are using this feature to make sure the embeds are always in the same language and not in multiple languages? If yes, can you explain further? Why would the embeds show in different languages?

**Comment by albertoperdomo** [comment]
If you are up for it, let's talk @rodrigoGA : https://calendly.com/d/cqvv-ykn-gs2/15min

**Comment by rodrigoGA** [comment]
he application we use to integrate the dashboards supports many languages (English, German, Turkish, Spanish, French, and Portuguese).
To avoid duplicating and maintaining dashboards in all languages, it was decided that the dashboard section would be in English using locale=en. Everything looked fine in: chart titles, dates, currencies, descriptions...

With the update, we now have a mix of languages on the home page, elements that Metabase renders in the user's browser language, such as dates, currencies, interface options....and card titles, alongside descriptions and chart information in English.

We were aware this was a feature we had read about in a forum, not in the official documentation, but it worked, and we proposed it, and the client accepted it.

Thanks for the information about the plan; I'll pass it along to see if it's accepted. Here's a suggestion regarding plans: https://discourse.metabase.com/t/suggestion-introduce-a-mid-tier-plan-for-embedded-analytics/182847
