### ISSUE TITLE
Infer visualization type when running a new query

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#5100]
After adding drill through, I really miss the visualization type inference when using the normal query builder. Although the new question flow might alleviate this, since it does set the visualization type.

I think the logic should be something like:

1. if brand new query (no visualization type set) guess the visualization type
2. if existing query unchanged, never change the visualization type
3. MAYBE: if existing query changed, and existing visualization is not considered "suitable" (grayed out in visualization type menu), then guess the new visualization type.
  * Need to be careful what's considered "suitable" (raw data can now be charted, for example)

**Comment by flamber** [comment]
Closing, since this was partially done in 0.34.0 (#11368) and should be completed in 0.36.0 (#12476)
