### ISSUE TITLE
Click behavior uses numerical ID's for tabs so serialization does not work with dashboard tabs

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#51018]
### Describe the bug

Interesting bug that a customer reported where subsequent changes in the staging environment leads to wrong destinations in click behavior when you use serialization

### To Reproduce

1) deploy 2 instances: origin and destination
2) create a simple card (e.g. count of people per source, make a row chart) 
3) create a dashboard in the origin which has 2 tabs and add the card to the first tab, which has a click behavior that opens the second tab of the same dashboard
4) export from origin and now import into destination
5) now on the origin do the following:
5.1) edit the dashboard, delete the second tab and save the dashboard
5.2) edit again the dashboard, add a tab and save the dashboard
5.3) edit again the dashboard, delete the tab and save the dashboard
5.4) edit again the dashboard, add the tab and save the dashboard
6) make sure that the click behavior works, so go to the card in tab one and make sure that the click behavior opens the second tab
7) now export from origin and import to destination

As the tab in the origin is now a few id's over the id's of the destination the click behavior will not be able to link to the tab via serialization, so the only way to make it work is to delete the origin and restore a backup from the destination into the origin

### Expected behavior

This should be painless

### Logs

NA

### Information about your Metabase installation

```JSON
it has always been like this
```

### Severity

P1

### Additional context

NA

**Comment by bunny-rich** [comment]
+1
