### ISSUE TITLE
Updating a filter via click behavior will not populate the field on actions

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#51020]
### Describe the bug

If you populate a filter in a dashboard by using a click behavior, then this field will not be used in an action if the action requires that field

### To Reproduce

1) enable actions in settings->admin->databases->pick your db->enable model actions
2) create a model (e.g. a select of the people table)
3) go to the model reference and create the basic actions (click on the little book you see when hovering over a model and then actions tab -> create actions)
4) then create a dashboard and add the model, then add a filter connected to the ID field and then make a click behavior to populate the ID field when clicking on the ID column of the table
5) add an update action to the dashboard, that connects to the UPDATE action of the model (set that the ID field will come prepopulated from the filter)
6) then save the dashboard and click on any ID
7) now click on the action and try to modify any field, you'll get an error saying that ID is required

### Expected behavior

The ID field should be obtained from the filter

### Logs

NA

### Information about your Metabase installation

```JSON
v52.1, but I'm thinking that this comes from way way before
```

### Severity

P1

### Additional context

It's interesting since not using a click behavior and just selecting the ID value will work, so definitely there's something on the click behavior there

**Comment by kamilmielnik** [comment]
I can also reproduce in 0.51.7
