### ISSUE TITLE
Check If Variable Is Blank/Null

### ISSUE THREAD

**Issue by mpacarroll** [metabase/metabase#5104]
It would be useful to be able to check if a variable is filled in or not.  

For example, I want to group by a column if a variable is present, but not if the variable is blank.  I looked and couldn't find an existing issue for this.  Thanks.

**Comment by salsakran** [comment]
if you surround a variable with `[[ ]]`, the inside of the double brackets will only be evaluated if there is a non-null variable inside.

Eg `[[GROUP BY {{column_variable}}]]` will only emit the `group by` if `column_variable` is not null.
