### ISSUE TITLE
Question execution in endless loop from version 0.24

### ISSUE THREAD

**Issue by jellelute** [metabase/metabase#5105]
I'm using Metabase with Bigquery. Queries used to timeout at 60 seconds (could you please increase this limit to 300 sec. or so?), but from version 0.24 while using questions with custom SQL, there is no user message of a timeout and queries appear to run endlessly.

![image](https://cloud.githubusercontent.com/assets/17344830/26032620/fad36176-3897-11e7-9ebf-bf2ea84bdfff.png)

**Comment by salsakran** [comment]
Are there any javascript error messages?

Also, how long does that query normally take?

**Comment by flamber** [comment]
Closing in favor of #12003. Related #4086
