### ISSUE TITLE
Opening Data Reference "kills" Metabase with a particularly heavy database

### ISSUE THREAD

**Issue by andrioni** [metabase/metabase#5106]
Whenever I try to open the Data Reference tab, the CPU on the server goes to 100% and stays there forever, until they get killed by the load balancer.

Looking into it, getting the metadata (`/api/database/*/metadata`) from one of our Redshift clusters (from Amplitude) seems to be the culprit, as it either fails or returns a whooping 11.5MB response after 1.4 minutes waiting. I've already disabled the in-depth analysis, but no dice.

- Your browser and the version: Chrome 57.0
- Your operating system: Arch Linux
- Your databases: Four Redshift databases
- Metabase version: v0.22.2 and v0.24.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres on RDS

**Comment by salsakran** [comment]
Can you share how many schema, tables and fields do you have in that database?

**Comment by sldorman** [comment]
I'm experiencing the same thing. Selecting Data Reference brings metabase to a crawl.  Even if it does return, everything is very slow after that.  I have 188 tables with 3714 columns. Everything is being run on the same computer (i.e. database, metabase, and browser).  

Your browser and the version: Firefox 53.0.2 (32-bit)
Your operating system: Windows 7
Your databases: SQL Server, single db
Metabase version: 0.24.0
Metabase hosting environment: local to db

**Comment by Varunram** [comment]
@sldorman That's weird. I have 3 dbs with approx 100 tables (and each table with like 15 columns in it). Seems to work perfectly fine for me. I'm on macOS Sierra. Maybe there's an upper cap after which this appears to happen?

**Comment by MiBaDK** [comment]
Wish I had seen this before we tested upgrade today. It started killing our AWS RDS. Turns out it also started crawling our BigQuery. Hope we got it stopped before billing got too bad :/
<img width="731" alt="screen shot 2017-08-03 at 19 19 37" src="https://user-images.githubusercontent.com/27769361/28919610-c6f14a16-7880-11e7-89de-35f682d65354.png">

**Comment by mnzt** [comment]
@MiBaDK turn off "Enable in-depth database analysis" if you don't want this behaviour.

**Comment by MiBaDK** [comment]
It is turned off. Simply made a copy of the one we use in production.
Upgraded the test instance. We have disabled in-depth on all our
connections.

**Comment by senior** [comment]
This issue should be resolved now that https://github.com/metabase/metabase/pull/6638 and https://github.com/metabase/metabase/pull/6623 has gone in. It's currently in master and will be included with the next release (like 0.28.0 RC1).

@andrioni Could you test this out and verify it's fixed for you?

**Comment by senior** [comment]
Thanks for reporting this issue, I'm going to close it as it was resolved with the 0.28.0 release. Please open a new issue if it occurs again.
