### ISSUE TITLE
Postgres materialised views are not listed within targets for foreign keys at 'datamodel' page 

### ISSUE THREAD

**Issue by YurZ** [metabase/metabase#5107]
Hello and thanks for a great product!  
It looks like materialised views are not listed within targets for foreign keys at **datamodel** page. 
How to reproduce:
- Create 2 materialized views: **mv_a** and **mv_b**
- Navigate to **/admin/datamodel**
- Make sure you can see both views listed under **Find Schema / Find Table**
- Select **mv_a** and try linking one of its fields as a Foreign Key to a Target (**Select Target** drop-down) in **mv_b**
- Discover that **mv_b** is not listed

My environment:
- Browser: **Google Chrome 58.0.3029.110 (64-bit)**
- Operating system: **Ubuntu Linux 16.04**
- Database: **Postgres**
- Metabase version: **0.24.1**
- Metabase hosting environment: **Docker** 
- Metabase internal database: **Postgres**

**Comment by salsakran** [comment]
Foreign Keys right now can only be linked to columns marked as a Primary Key.

Can you share the schema of mv_a and mv_b?

**Comment by YurZ** [comment]
Thanks for the response, @salsakran 
Primary Key requirement then explains this behaviour. 
Even though being very similar to ordinary tables, Postgres materialized views cannot have primary keys added (Postgres current latest version 9.6) but can have unique indexes.
Would it be possible to consider similar Metabase foreign keys functionality based on unique indexes in future releases?

**Comment by tlrobinson** [comment]
@YurZ you should be able to mark fields as the "Entity Key" type in the data model regardless of whether they are primary keys in the underlying database.

**Comment by YurZ** [comment]
Thank you @tlrobinson and @salsakran ! I got it working. My apologies for confusion.
