### ISSUE TITLE
Achieving a Stacked Line or Bar Chart

### ISSUE THREAD

**Issue by su-narthur** [metabase/metabase#5109]
I'm having difficulty creating a stacked chart of any kind. I think my data should be compatible with a stacked chart:

<img width="990" alt="screen shot 2017-05-15 at 11 54 17 am" src="https://cloud.githubusercontent.com/assets/20328940/26066541/41ad189e-3965-11e7-92d1-d5f782ed5e6d.png">

But when I go into the bar chart options, for instance, stacking isn't an option:

<img width="1719" alt="screen shot 2017-05-15 at 11 55 02 am" src="https://cloud.githubusercontent.com/assets/20328940/26066610/70be4158-3965-11e7-9a90-60f9edd70f1e.png">

This is the message displayed with the yellow caution sign:

<img width="377" alt="screen shot 2017-05-15 at 11 55 16 am" src="https://cloud.githubusercontent.com/assets/20328940/26066628/7cc0474e-3965-11e7-8c77-d4bdee21e28f.png">

How can I achieve a stacked chart with my data?

I'm using Metabase v0.23.1

**Comment by mazameli** [comment]
Hmm, that's strange. Is your `Name` field marked as a `Category` in the Data Model section of the Admin Panel? What type of database are you using for this chart?

This feature seems to be working correctly for me, though I'm also seeing that warning:

![screen shot 2017-05-15 at 10 29 56 am](https://cloud.githubusercontent.com/assets/2223916/26070452/925b70f8-3959-11e7-83bb-b4aeb4ab9b8d.png)

![screen shot 2017-05-15 at 10 29 51 am](https://cloud.githubusercontent.com/assets/2223916/26070454/96d00982-3959-11e7-9e71-cb94e00bea9e.png)

![screen shot 2017-05-15 at 10 29 35 am](https://cloud.githubusercontent.com/assets/2223916/26070456/99c2ffd2-3959-11e7-906a-4578d8412792.png)

**Comment by su-narthur** [comment]
@mazameli The `Name` type is `Entity Name`. Someone else set up the Metabase instance. How do I tell what type of database it's using?

**Comment by flamber** [comment]
Closing, since hasn't been reported by anyone else.
