### ISSUE TITLE
Saved Question edit mode should use same cancel/archive/save bar as dashboards

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5113]
I could have sworn there was a really old issue about this but I couldn't find it.

In question edit mode, we should remove this button, link, and icon:

![saved question](https://cloud.githubusercontent.com/assets/2223916/26074009/3c8a1d58-3965-11e7-80a3-8a0706938bfe.png)

…and replace it with this bar at the top (obviously with it saying `You are editing a saved question` instead of `dashboard`):

![screen shot 2017-05-15 at 11 49 22 am](https://cloud.githubusercontent.com/assets/2223916/26074035/5032579e-3965-11e7-86b3-a74658720da5.png)

**Comment by kdoh** [comment]
Due to the query builder edit changes in 0.33 this is no longer relevant.
