### ISSUE TITLE
Authenticate access to Databricks with a service principal using OAuth (OAuth M2M)

### ISSUE THREAD

**Issue by AlexVialaBellander** [metabase/metabase#51276]
### **Is your feature request related to a problem? Please describe.**
The current implementation of the Databricks drivers were inspired by the implementation of [relferreira](https://github.com/relferreira)
[metabase-sparksql-databricks-driver](https://github.com/relferreira/metabase-sparksql-databricks-driver). However, the problem with this implementation, in contrast to [Brigad](https://github.com/Brigad/metabase-sparksql-databricks-driver) is that it makes use of User Access Tokens. Brigad's implementation, which follows Databricks recommendations, uses Machine 2 Machine authentication.

> [!NOTE]
> We make the assumption that no Database connection should be set up using individual user credentials. The connection method, which should be somewhat abstracted from the underlying drivers of the current Databricks implementation should not be affected.

### **Describe the solution you'd like**
We expect that the Databricks Drivers utilise OAuth client id and client secrets as [recommended](https://docs.databricks.com/en/dev-tools/auth/oauth-m2m.html#manually-generate-and-use-access-tokens-for-oauth-m2m-authentication) by Databricks and implemented by  [Brigad](https://github.com/Brigad/metabase-sparksql-databricks-driver). Minimal changes to the underlying drivers are likely needed, only how the authentication works.

> Databricks recommends using client unified authentication, however if you must manually generate, refresh, or use Databricks OAuth access tokens, follow the instructions in this section. (they must be updated every hour)

### **Describe alternatives you've considered**
There are no serious alternatives to do M2M authentication with Metabase and databricks as of today. Thus, the current implementation forces users to utilise non-recommended methods by the vendor.

### **How important is this feature to you?**
Let's just say that using individual credentials to connect to Databases isn't exactly something I dream of......

### **Additional context**
There is an implementation of this already. Maybe we can just lift and shift the authentication part?

**Comment by AlexVialaBellander** [comment]
CC: @tetiana-kolmychek

**Comment by AlexVialaBellander** [comment]
### Using Brigad
> Credentials and details are not real ⚠️

<details>
<summary>Click to expand / see image</summary>

![Brigad Implementation](https://github.com/user-attachments/assets/0659dd81-862c-428d-b1ed-42f5cf318137)

</details>

---

### Current Implementation (Official in Main)
> Credentials and details are not real ⚠️

<details>
<summary>Click to expand / see image</summary>

![Official Implementation](https://github.com/user-attachments/assets/3b641f03-5ddd-4bca-8ea9-813c377e1a09)

</details>

**Comment by paoliniluis** [comment]
@AlexVialaBellander will you be able to make a PR adding that?

**Comment by AlexVialaBellander** [comment]
I gave it a shot in #51476.
Would be great if you could guide me in the process here.
I tried it on our Databricks Servers and worked as expected.

**Comment by AlexVialaBellander** [comment]
@nemanjaglumac @paoliniluis Hey :) When can we expect this in a release?

**Comment by paoliniluis** [comment]
@AlexVialaBellander got into master, so it's going to be shipped in 53 at least. I'm going to check with the team if we want to backport this to 52
