### ISSUE TITLE
Not all values listed in filters - cannot select value not listed.

### ISSUE THREAD

**Issue by funktopus** [metabase/metabase#5128]
When I am using a filter (in questions or dashboards), there is a new drop down menu with all the values. However not all of them are listed (it ends with letter G in my case) and I cannot select a value that I want, because they are not listed. This is a catch-22 style work blocker :-(

**Comment by salsakran** [comment]
This is an issue with FieldValues not being properly picked up. 

Related to #4991 and #5046

**Comment by camsaul** [comment]
Basically the same underlying issue as #5323. This was resolved by #5510.

**Comment by camsaul** [comment]
Duplicate of #5323

**Comment by mazameli** [comment]
Hey everyone. Just a heads up that [we've shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
