### ISSUE TITLE
Raw SQL Query Issues for Generic SELECT Queries

### ISSUE THREAD

**Issue by orware** [metabase/metabase#5133]
### Bugs

I don't seem to recall this occurring before (on the original 0.22.2 possibly even the .23.1 versions I was running initially) but maybe it's because I didn't try it out back then however I let one of our Researchers loose on Metabase to start using it and so far they've mainly been using it to learn about SQL and are mostly running some basic SQL queries from the editor.

I think one of the things they've run into is that if you issue a basic select query on a table (such as `SELECT * FROM our_table`) Metabase tends to not return something right away, possibly because it's not adding a limit option to the database and is truly trying to gather the entire result set. If we issue the same query with a filter applied, a result gets returned fairly quickly so it's mainly something I wanted to bring to your attention since they are running into this issue quite often it seems since they keep on mentioning it when I speak with them.

I also just updated to 0.24.1 and ran the same sort of tests and saw the same issue occur.

The other issue this person has noticed is that Metabase's behavior across different browsers appears to be rather unpredictable and for example IE 11 support is so-so (with a particular script causing the browser to hang at times). I normally use Chrome for everything so I hadn't noticed, but this user (and other users here on campus that'd probably end up using Metabase) would probably go towards IE 11 first so having semi-decent performance without JavaScript glitches in IE would be a nice to have. Related to this, it seems like Metabase tries caching things in the frontend sometimes in a way that negatively impacts the user experience (e.g. stale information might get returned or the UI just stops working as expected and refreshes don't help...essentially you're forced to go back to the Metabase home for your install and that usually helps reset things in the UI so it works again).

**Comment by salsakran** [comment]
Hey @orware , for `select *`, while we limit the number of rows, in general, you should get people used to slapping a `limit 10` on the end. This holds for using us or any other SQL client.

Regarding the other issues, do you mind opening separate issues with more specifics? It's hard to do much without information to reproduce the problems you're referring to.

**Comment by orware** [comment]
@salsakran I believe the behavior of Metabase in this case is incorrect though and this issue should be left open.

If you think about it, when typing in general select queries into programs like Oracle SQL Developer or MySQL workbench (or phpMyAdmin) the results are limited automatically when the query is executed.

Currently, with Metabase's default behavior for the custom queries it is attempting to load the entire result set in the case of a general select query which is something it shouldn't do since it basically makes Metabase unusable for quick ad-hoc querying using the SQL Editor feature (this particular issue that's been having the trouble hasn't been creating their own actual questions yet and have been mainly playing with the SQL Editor and running simple queries so that's why he's run into the issue so much).

I think the behavior of the SQL Editor feature should mimic how users using tools like SQL Developer/MySQL Workbench would expect such a feature to behave, rather than expecting them to limit the results manually on their own (which is significantly more difficult with Oracle and a few other types of databases which may not have the ease of a built-in LIMIT clause the MySQL does).

**Comment by orware** [comment]
Can this issue be reopened please? It is a valid issue and can be improved upon.

This would be a not-too-difficult thing to fix and would make Metabase infinitely more useful when attempting to query larger tables for our Researchers that are testing the software with me.

As an example, today one of the Researchers was trying to create a very simple `SELECT * FROM table` type query but it blew up Metabase because it stupidly goes out and tries to retrieve all of the result set (I'm guessing). On the Researchers end the page simply times out, and then on the server I can see Metabase continuing with 100% CPU usage for who knows how long and I end up needing to kill the process completely and restarting Metabase just to get the web UI responding again. (This particular table has about 4.2 million rows).

I know the suggestion above is assuming folks are all using MySQL, but we're not here and Oracle 11g doesn't have an easy to use limit clause...instead you need to do something like this:
```
select *
from  
( select * 
  from emp 
  order by sal desc ) 
where ROWNUM <= 5;
```

It would just be a lot easier if Metabase could just limit the results automatically for users as they are doing ad-hoc queries, and maybe provide an option they can toggle if they want to attempt to pull in more data, but it would be very reasonable to limit the results (which would put the Metabase ad-hoc querying capability in-line with how most tools, like SQL Developer or MySQL Workbench, do things).
