### ISSUE TITLE
Calling Metabase from another app

### ISSUE THREAD

**Issue by sldorman** [metabase/metabase#5138]
I have been using Metabase the last few days to see if it can be used in conjunction with our data app.  So far, it's unclear to me if Metabase can be used this way.  I would be interested in advice regarding my use case:

I have a web application that loads data into the database. From that app, I would like the user to press a button that brings up Metabase with the appropriate database already configured/connected.  The user can then create queries or run existing queries against the connected database.  

When the web application exits, the data is removed for security purposes so Metabase must be brought up while the web app is up and the data has been loaded.

The user should not have to log into Metabase.

The user should not be allowed to connect to any other databases.

*The user should only see the data he loaded. The userid is stored in the tables so would need a way to pass the userid to Metabase and include it in the queries without user intervention.

*Some tables should not be accessible to the user (not just hidden from the schema display but also not allowed in select statements if the user knows the table names).

*All queries must be read-only.

The last 3 criteria (marked with a *) may be able to be controlled by transferring only the user's data to a separate db that has limited tables and have Metabase point to that limited db.  The data can be quite large so I don't want to do this step if another option is available.  If I use Views instead, can I tell Metabase to only acknowledge the Views?

I'm also concerned about Metabase's performance.  I installed it and queried 1 table which returned 500 rows. Returning the rows was fine but the entire app started choking after that as I navigated through menus looking at other features. The biggest problems occurred after doing a line chart of that query or, on a separate run, when I selected the Data Reference option.   The java process was using over 1GB of memory when it hadn't even done much yet.  I have Metabase and the SQL Server database installed on my laptop - not a powerful machine but usually adequate - what are the minimum requirements (I'm running from the jar)?

**Comment by salsakran** [comment]
While in theory what you're describing is possible, it's not really a use case we're specifically designing towards. In general, we expect to be a persistent application that users interact with in an ongoing fashion. 

We do a fair amount of front-loaded work to analyze a database and generate a data model to simplify end user interaction and generally server as a primary BI application for a company. 

` I installed it and queried 1 table which returned 500 rows. Returning the rows was fine but the entire app started choking after that as I navigated through menus looking at other features.` sounds very atypical, and it's hard to infer exactly what happened, but in general, we don't see this kind of behaviour when run against small data warehouses. 

We do however, expect to have a pretty performant database (either a filesystem for our embedded DB, or a MySQL/PG server) for our application data, so if you had an especially slow file system or an application database with high latency, something like what you described could occur. 

Some mix of the embedded database, https://github.com/metabase/metabase/wiki/Using-the-REST-API + https://github.com/metabase/metabase/blob/master/docs/api-documentation.md could probably put together what you described, but it would take a fair bit of glue code. 

Also, depending on what you're trying to do, the fact that we're licensing the Metabase application under the AGPL might come into play.

**Comment by salsakran** [comment]
possibly related to #4991

**Comment by tlrobinson** [comment]
Sounds like you're asking for row level security: #2824

You could fake it with views and data permissions. You'd have to create a group per user, and give that group access to only the views for that user.

**Comment by flamber** [comment]
Closing, since this question would probably be better suited for the forum.
And the Enterprise Edition has row level security in the form of Sandboxing:
https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html
