### ISSUE TITLE
Unable to download XLSX (Excel) when there's an array or UUID type

### ISSUE THREAD

**Issue by GuiSim** [metabase/metabase#5145]
Using Postgresql 9.6, Metabase 24.1

1. Create a new SQL question
2. Enter the following: `select '{"a", "b", "c"}'::varchar[]`
3. Click download as XLSX

Expected: Successful download of the data

Actual: Error
```
{
"message": "No method in multimethod 'set-cell!' for dispatch value: class org.postgresql.jdbc4.Jdbc4Array",
"stacktrace": [
"api.dataset$export_to_xlsx.invokeStatic(dataset.clj:58)",
"api.dataset$export_to_xlsx.invoke(dataset.clj:57)",
"api.dataset$as_format.invokeStatic(dataset.clj:102)",
"api.dataset$as_format.invoke(dataset.clj:94)",
"api.dataset$fn__28513$fn__28514.invoke(dataset.clj:123)",
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)",
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)",
"api.dataset$fn__28513.invokeStatic(dataset.clj:116)",
"api.dataset$fn__28513.invoke(dataset.clj:116)",
"middleware$enforce_authentication$fn__38784.invoke(middleware.clj:120)",
"api.routes$fn__38910.invokeStatic(routes.clj:59)",
"api.routes$fn__38910.invoke(routes.clj:59)",
"routes$fn__39540$fn__39541.doInvoke(routes.clj:64)",
"routes$fn__39540.invokeStatic(routes.clj:60)",
"routes$fn__39540.invoke(routes.clj:60)",
"middleware$log_api_call$fn__38883$fn__38885.invoke(middleware.clj:329)",
"middleware$log_api_call$fn__38883.invoke(middleware.clj:328)",
"middleware$add_security_headers$fn__38833.invoke(middleware.clj:243)",
"middleware$bind_current_user$fn__38788.invoke(middleware.clj:140)",
"middleware$maybe_set_site_url$fn__38837.invoke(middleware.clj:266)"
]
}
``` 

It seems that you can't download as XLSX any table that includes an array type.

CSV and JSON downloads work fine.

IMO an acceptable workaround would be to `::varchar` the array before exporting.

**Comment by ujjwal-gupta** [comment]
Same issue with Mongo. XLSX fails to download if the collection has arrays.

**Comment by jonahwh** [comment]
I am having this *exact* same issue, but with UUIDs. This query will cause the same result.

`SELECT '10f2f0aa-cc8e-4ed7-b972-8ef55b2afcaf'::uuid`

I was going to open a new issue, but the stack trace is *identical* to this one. The only difference is the error message
> "No method in multimethod 'set-cell!' for dispatch value: class java.util.UUID"

This appears to be a regression, because I believe exporting UUIDs worked fine in the past.

In my case, I'm using Postgres 9.5.6, and attempted this on both Metabase v0.24.0 and v0.24.2
