### ISSUE TITLE
CSS issue: Metabase Dashboards that display a bunch of table data are nearly invisible in dark mode

### ISSUE THREAD

**Issue by exabrial** [metabase/metabase#51524]
### Describe the bug

Hello, we're running latest Metabase 52.2.3, JDK 17 on linux/mysql8.

I don't know which exact release this broke in, but a lot of our dashboards are nearly invisible in dark mode/full screen.  I've redacted some of the data below with background colors, but you can see below that the dark text on a dark background is nearly impossible to read.

![Image](https://github.com/user-attachments/assets/57713203-97c1-418d-87f4-330f7b617411)

We're happy long time Metabase users and continue to recommend the platform to everyone we know. Thank you for your consideration! To avoid creating additional work, I did search for existing bugs on this but did not find a similar one. If my search was ineffective, my apologies for adding a duplicate ticket, please feel free to close this and link me to the correct one.

### To Reproduce

1. Create a dashboard with a tables
2. Enter Full screen and select dark mode
3. Squint

### Expected behavior

These were legible up to a recent release, I imagine this was just an oversight. I believe the bug existed in 52.2.2 as well

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-12-14",
      "tag": "v0.52.3",
      "hash": "6f76bb6"
    },
    "settings": {
      "report-timezone": "US/Central"
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.39-30"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.12+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.12+7",
    "os.name": "Linux",
    "os.version": "5.15.0-126-generic",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  }
}
```

### Severity

Blocking Some Usages/Obnoxious, but there is a workaround: use light mode

**Comment by heypoom** [comment]
Thank you so much for the detailed report @exabrial! We'll deliver the fix (#51538) in the next minor release.
