### ISSUE TITLE
Change dashboard type by a combobox

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#5155]
In metabase there is a cool feature that we can create dashboards by charts. As it is a normal thing to have multiple dashboards. Is it possible to change the dashboard type by a combo box?

Let's say we categorize dashboards by company's products. Is there a way to select product from a combobox in dashboard and it gets switched to that dashboard? If there is no such a feature, is it possible to add that feature to future releases?

![screen shot 2017-05-20 at 11 48 28 am](https://cloud.githubusercontent.com/assets/6417083/26273956/4686ef98-3d52-11e7-9c7e-e720255d4184.png)

**Comment by salsakran** [comment]
you can do that with dashboard filters. http://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html

**Comment by alirezastack** [comment]
Dashboard filters change charts by some metrics like date, interval, user id, etc. The thing I want is to switch dashboards completely which in filters it is not the case.
