### ISSUE TITLE
Why table question height cannot be less than a specific height?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#5156]
When I create a new question which shows a list of data, I want to make the height of chart less than the picture below:
![screen shot 2017-05-20 at 11 52 39 am](https://cloud.githubusercontent.com/assets/6417083/26273979/da49de02-3d52-11e7-81fc-5c1acb4434c2.png)

The height is so much that fills most of the dashboard space. Isn't there a way to make the height less than the picture above? 

Change to one cell maybe:
![screen shot 2017-05-20 at 11 53 59 am](https://cloud.githubusercontent.com/assets/6417083/26273990/1439bd12-3d53-11e7-8736-c988e3543d4a.png)

**Comment by kdoh** [comment]
@alirezastack You should be able to resize any card on a dashboard by clicking and dragging in the lower right of the card.

**Comment by alirezastack** [comment]
@kdoh it's really interesting that I cannot resize to the height I want. It seems a bug then.

Browser: Chrome 58.0, Firefox 53.0
Operating System: OS X Yosemite
Metabase: 0.24.1

**Comment by kdoh** [comment]
@alirezastack Are you able to resize the width? Also can you move the card around in the dashboard outside of resizing it?

**Comment by alirezastack** [comment]
@kdoh I can resize the width, and I can move it around, but the height cannot be lower than the height shown in above picture. I can make the height bigger too but not less than 4 cells!

**Comment by tlrobinson** [comment]
@kdoh we have minimum sizes hardcoded for different card types.

**Comment by kdoh** [comment]
Ah ok I misunderstood the original issue. I was under the impression resizing the Y axis was broken. @alirezastack we limit how small certain cards can be to try and ensure that they'll be legible. Mind elaborating why you're interested in a tiny table?

**Comment by alirezastack** [comment]
It is used for customer support and we have to zip many tables that have one row. Each table has info about user and services thay have purchased. But user infilo always has one row, so having table with a big height waste the space.

**Comment by mazameli** [comment]
Going to consider this solved by #6106.
