### ISSUE TITLE
Showing description and title for saved scalars in the query builder feels redundant.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#5159]
It makes sense to display the title and description icon in dashboards but since we already show this info in the header it feels odd to me that we do it again.

<img width="1436" alt="screen shot 2017-05-21 at 9 42 50 am" src="https://cloud.githubusercontent.com/assets/5248953/26285753/62f3c134-3e0a-11e7-9ef1-bf9ec0d76e81.png">

**Comment by mazameli** [comment]
Totally agree. I think we should remove the title and description from below the scalar in this situation.
