### ISSUE TITLE
Unicode issue when using MySQL as the app database

### ISSUE THREAD

**Issue by maliayas** [metabase/metabase#5160]
- Your browser and the version: Firefox 53.0.2
- Your operating system: Windows 10
- Your databases: MySQL
- Metabase version: 0.24.1
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

I've switched to MySQL from H2 as the app database. The result is working fine except one thing: I can't enter unicode text for question titles, dashboard names, collection names etc.

Tables columns in the app database (MySQL) has `utf8_general_ci` as the collation. If I modify the question names directly from the db, then Metabase can show the text fine as unicode. However if I use Metabase GUI and enter unicode text, result is broken.

For example, I enter "Bağımsız raporlar" as a collection name throught the Metabase GUI, then it ends up like this in the `collection` table:

* name: `Ba??ms?z raporlar`
* slug: `bag%C4%B1ms%C4%B1z_raporlar`

Here is the request when saving collection name, taken from the devtools:

* Request header: `Content-Type: application/json`
* Request body: `{"name":"Bağımsız raporlar","description":null,"color":"#509EE3"}`

***

* Response header: `Content-Type: application/json; charset=utf-8`
* Response body: `{"id":1,"name":"Ba??ms?z raporlar","slug":"bag%C4%B1ms%C4%B1z_raporlar","description":null,"color":"#509EE3","archived":false}`

**Comment by mokra** [comment]
I have the exact same problem

**Comment by maliayas** [comment]
Any interest in this bug? We're still modifying queries through MySQL admin tools instead of Metabase GUI. Thanks in advance.

**Comment by mokra** [comment]
Yes I am.
It is certain that this is not a MySQL collation issue, since I've tried all of them. Also setting character-set-server=utf8 didn't help!

**Comment by maliayas** [comment]
Hi @salsakran Would you be interested in this issue for the next version, please? I've waited for some months before asking this, due to the already existing rush in the issue tracker. Thanks again.

**Comment by senior** [comment]
@maliayas I've looked into this and I think it's something that you can fix through configuration. MySQL defaults to latin1 encoding. An encoding in MySQL can be applied at the instance, database, table or column (:scream_cat:) level. I tried just specifying that the Metabase database use UTF8 but that didn't quite fix it as there appears to be some encoding negotiation going on between the MySQL JDBC driver and the MySQL instance. What did appear to fix it was making the MySQL instance UTF8. I followed the below steps and it worked for me:

- Start with a fresh MySQL instance (i.e. no existing Metabase database present)
- Launch MySQL with `--character-set-server=utf8` for me the invocation looks like `mysqld --defaults-file=/../my.sandbox.cnf --character-set-server=utf8` 
- Create the Metabase application database
- Start Metabase, pointing at the new MySQL instance and database

What this should do is launch MySQL with UTF8 as the default character encoding. When you create the Metabase database, it should use UTF8 encoding for that database by default. When Metabase connects to MySQL it should auto-negotiate to UTF8 for incoming data.

**Comment by senior** [comment]
@mokra did you set that after creating the database? it's possible that the database itself was still in latin-1

**Comment by maliayas** [comment]
@senior Thanks very much for the help!

`character-set-server=utf8` and `default-character-set=utf8` fixed the issue for me. (For details see https://stackoverflow.com/a/3513812/1135429)

However I think that behaviour can be done via `SET NAMES utf8` from the Metabase app itself. I shouldn't be modifying my server conf for an external requirement, which can be already achieved externally.

**Comment by looric** [comment]
@senior
Metabase version v0.28.5 without setting character-set-server=utf8 for [mysqld] in my.cnf,
the database is default to utf8

mysql> show variables like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

mysql> show variables like 'collation%';
+----------------------+-------------------+
| Variable_name        | Value             |
+----------------------+-------------------+
| collation_connection | utf8_general_ci   |
| collation_database   | utf8_general_ci   |
| collation_server     | latin1_swedish_ci |
+----------------------+-------------------+
3 rows in set (0.00 sec)

but the frontend see ?? after save to database;

after add character-set-server=utf8  to [mysqld] in my.cnf ,
this problem solved.

is it possible to set character-set-server using these environment variables like?
export MB_DB_TYPE=mysql
for example in alfresco:
db.url=jdbc:mysql://localhost/alfresco52f?useUnicode=true&characterEncoding=utf-8&useSSL=false

**Comment by senior** [comment]
@looric you should post this issue to our [discourse forum](http://discourse.metabase.com/). We can troubleshoot it there.

**Comment by camsaul** [comment]
Fixed by #11753
