### ISSUE TITLE
PDF can't show whole data. The rightmost part is cut off.

### ISSUE THREAD

**Issue by JessieLiuz** [metabase/metabase#51612]
### Describe the bug

I export tab as PDF. This PDF can't show whole data. The rightmost part is cut off. The last page is displayed normally.

### To Reproduce

1. Go to 'a big whole dashboard '
2. Click on 'edict dashboard', export tab as PDF. 
3. Check the PDF (more than one page) The rightmost part of the first few pages is cut off. The last page is displayed normally. 

### Information about your Metabase installation

```JSON
no idea
```

### Severity

blocking some users

**Comment by cdeweyx** [comment]
Fixed with https://github.com/metabase/metabase/pull/51491 cc: @alxnddr
