### ISSUE TITLE
Basic Action Fails if ID Comes from Filter set by Custom Click Behavior

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#51644]
### Describe the bug

Basic actions fails if they get a value from a dashboard filter that was set with custom click behavior.

### To Reproduce

1. Create a model with basic actions enabled
2. Set up a dashboard with a question that contains ID field that also exists in the model
3. Add a dashboard filter for the ID field
4. Add custom click behavior to the card such that the ID filter is updated when the field is selected
5. Add action button to the dashboard that refers to a Basic Action

https://www.loom.com/share/f3082c367166498091e002a75b70f719

### Expected behavior

Click action should work.

### Logs

Cannot run the query: missing required parameters: #{"id"}

### Information about your Metabase installation

```JSON
Works in 49. Busted in 51 and 52.
```

### Severity

Annoying / Possibly blocking

### Additional context

You can technically work around it with a custom action. If someone had actions built prior to upgrade I imagine it would be a pain to have to recreate them. I haven't seen explicit reports of people having to rebuild them, though.

**Comment by joeledwardson** [comment]
Confirmed this is happening for us, this is the version:

```
Thanks for using Metabase!
You're on version v1.51.6.5
Built on 2024-12-03

Hash: 22b76e9
```

I would use custom actions but there a couple of features of basic actions I haven't figured out how to replicate in custom actions:

- toggles for booleans
- copying table data into forms

**Comment by paoliniluis** [comment]
fixed in https://github.com/metabase/metabase/issues/51020
