### ISSUE TITLE
Local dynamic port

### ISSUE THREAD

**Issue by tuliofmoura** [metabase/metabase#5166]
Hi. I installed and I'am running the Metabase Mac application. I added my co-workers so they had access to the instance on my Macbook via LAN. However, every time I run a new instance of the application, the port number changes and I have to pass the new number to everyone. Is there any way to leave the local port number fixed?
Thanks.

**Comment by camsaul** [comment]
Hi @tuliofmoura, the Mac App is only really intended for personal use so you can evaluate the product. If you want a multi-user instance we highly recommend you set up a Metabase server -- that way your co-workers can access Metabase even when your computer isn't connected to the LAN.

Elastic Beanstalk is probably the easiest to set up. Check out our guide to setting it up here: http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html
