### ISSUE TITLE
We should remove extraneous borders and grid lines from tables

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5169]
This was mentioned in issue https://github.com/metabase/metabase/issues/4621, but we should consider stripping out vertical borders and the exterior grid from our tables to clean them up a bit.

**Standard table:**

![325e8a2c-13b7-11e7-8695-4d45b798f25e](https://cloud.githubusercontent.com/assets/2223916/26329492/5e7cde18-3efc-11e7-8f52-ec739ada907e.png)

**Pivot table:**

![aa7a5a52-1927-11e7-8e29-eb4ed649483e](https://cloud.githubusercontent.com/assets/2223916/26329501/63542108-3efc-11e7-946f-0590d1b3b77c.png)

We'll have to figure out what small tables with few columns and/or rows would look like without the exterior border.

**Comment by Varunram** [comment]
@mazameli May I work on this? Or is it not that much of a starter issue? Thanks!

**Comment by mazameli** [comment]
@Varunram I think @kdoh had done a little tinkering on this issue, but I don't think anyone is actively working on it right now, and we definitely do accept pull requests. I think I mentioned this to you on Gitter, but just make sure to check out our [Contributor's Guide](https://github.com/metabase/metabase/blob/master/docs/contributing.md) before diving in. Thanks!

**Comment by Varunram** [comment]
Cool, will work on it. Just wanted to comment on the issue to make sure no one's one it atm. Thanks a ton!

**Comment by Varunram** [comment]
@mazameli Sorry for the delay, was facing a few issues with the dev environment. Since you asked, I've attached a screenshot of what small tables look like without borders. Thanks for your time! 
<img width="1280" alt="screen shot 2017-06-06 at 9 32 26 pm" src="https://user-images.githubusercontent.com/18598959/26839172-e4a2d5e2-4aff-11e7-98ac-e162cadb1a0b.png">

**Comment by mazameli** [comment]
Nice! We'll want to make sure the column headings have the same alignment as the cell values; i.e., in your screenshot, the headings and cell values should all be right-aligned (since they're numbers).

I'm also wondering if maybe we should make the horizontal rules extend to 100% width.

Thanks for your work on this!

**Comment by Varunram** [comment]
@mazameli almost done, but I'm not able to figure out one small component. As  you can see in the picture, all but two cells are perfectly right aligned. These were the cells which earlier had `justify-end` set as true. Any ideas why this is happening (P.S. now all the values have `justify-end` as true)

<img width="1233" alt="screen shot 2017-06-09 at 3 46 13 pm" src="https://user-images.githubusercontent.com/18598959/26971520-2218d552-4d2b-11e7-8c75-b6b597fa00bb.png">

**Comment by Varunram** [comment]
@mazameli Oh, okay got that. But as of now, we do detect whether they're values right? Why doesn't it work in this case? Is it maybe a separate issue?

**Comment by Varunram** [comment]
Also, what do you propose we do for hover highlighting? Create a new class or?

**Comment by mazameli** [comment]
This issue might get closed out by the work you've been doing, @kdoh

**Comment by kdoh** [comment]
Was fixed in #5882
