### ISSUE TITLE
"Get answer" / "refresh" button is mispositioned on Safari

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5170]
It actually might be that the whole row/div with the visualization options, the get answer button, and the number of rows has too much top padding.

![screen shot 2017-05-22 at 1 46 17 pm](https://cloud.githubusercontent.com/assets/2223916/26330493/fe818978-3f00-11e7-86de-6c4f9b42abbd.png)

**Comment by mazameli** [comment]
I tried messing around with this a bit, but not sure how to get Safari + Chrome to agree on the margin/padding used here.

**Comment by kdoh** [comment]
I can't reproduce this. Are you still seeing this @mazameli?

**Comment by mazameli** [comment]
Yes, still present on our stats instance. Try making your browser window smaller maybe?

![screen shot 2017-06-28 at 7 53 14 pm](https://user-images.githubusercontent.com/2223916/27665499-85931bc8-5c3b-11e7-8f8d-8f71ef3f2104.png)
