### ISSUE TITLE
Sorting works on dashboard but not in a question

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5174]
### Version: Latest version of the mac app

I have a column date and I'm able to order it in Descending order in the Dashboard, but I'm not able to do so inside the question. It would be amazing if we could do that, since the dashboard view resets to default each time. Thanks!

**Comment by tlrobinson** [comment]
@varunram is it a SQL question or built using the query builder?

The table on dashboards does client-side sorting, which works with SQL, while the table in the query builder modifies and reruns the query, which we can't do for SQL.

**Comment by Varunram** [comment]
@tlrobinson It was built using the query builder. So if I use a SQL query for the same would it work fine?

**Comment by mbvictoria** [comment]
Closing - resolved.
