### ISSUE TITLE
Tooltips shouldn't display every single column in the result when visualizing raw/unaggregated data

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5176]
This is a bit of an edge case, but tables with lots of columns can result in tooltips like this one:

<img width="870" alt="screen shot 2017-05-22 at 4 57 33 pm" src="https://cloud.githubusercontent.com/assets/2223916/26369009/41a23930-3fa8-11e7-8cf5-8d35ff00fd8c.png">

Since this is a pretty goofy situation, I think it would be okay to just show the first n columns, and then say `and x more…`. (It also might make sense in cases where the user is visualizing raw data, like a pin/heat map or a scatterplot, to have the table settings' show/hide columns selections affect which fields show up in a data point's tooltip.

For an example of when and why we might want max-width, look no further than https://github.com/metabase/metabase/issues/4748

**Comment by kdoh** [comment]
We can definitely constrain tooltips to certain max sizes but it seems like the underlying issue here is that we're doing a real bad job of showing you pertinent info. Seems like in this case where you're visualizing Raw Data as a scatter plot we should only show the marked entity name or entity key by default rather than reproduce the table in a tooltip.

**Comment by Varunram** [comment]
@mazameli @kdoh Any pointers as to where I should look in order to fix this? Thanks!

**Comment by bmcbride** [comment]
This occurs on map visualizations as well. Would it make sense to include the same "Fields to include" option that's available in the table visualization?

**Comment by mazameli** [comment]
Quoting @kdoh:

> Seems like in this case where you're visualizing Raw Data as a scatter plot we should only show the marked entity name or entity key by default rather than reproduce the table in a tooltip.

For scatter plots, I would just add that in addition to the row's entity ID and entity name (if there is one), I think for each point you'd also want:
- The x-axis column's value
- The y-axis column's value
- The z-axis column value (bubble size) if present

**Comment by kritop** [comment]
i have the same for any kind of visualization bars, lines etc. 
- hovering over one section i cannot identify which one i am hovering on, driving me nuts
- there is no way to know if they are stacked what is the total
