### ISSUE TITLE
/dashboards page loading time enhancements

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#5177]
What happens currently:
- goes to /dashboard and a query to get all the dashboards is made
- this does a full table scan for dashboards table
- it then filters out the dashboards which current user does not have permission to see

This means that as the number of dashboards grows for the whole company, the time taken for dashboards page to load increases regardless of the number of dashboards a user/team can see.

This can be made better by either adding a group column to dashboards table (which will contain permission group value) and thus can be used as a filter on the query.

One argument against this method is, what if there are multiple teams sharing a dashboard.

@camsaul @salsakran Thoughts.

**Comment by VikramTiwari** [comment]
Seems like this is being discussed here (https://github.com/metabase/metabase/issues/336) as well. Close this if it seems a duplicate.

**Comment by flamber** [comment]
Closing, since there were a lot of performance improvements in 0.34 and 0.35 - #11856
