### ISSUE TITLE
Change in mysql permission doesn't propogate to metabase

### ISSUE THREAD

**Issue by shijialee** [metabase/metabase#5179]
Hello,

I would like to limit access to few tables for sql read/write access. I am aware of issue #3363, #1689 and  #1175. It looks like I need to restrict access on the database level by revoke SELECT privilege on few tables for metabase. 

Note that I started the initial metabase setup without access restriction. After I revoked SELECT on the targeted tables(flush too), I can still run SELECT to the restricted tables from metabase.  There is no change after I turned off the cache feature in metabase setting.

How long does the database permission change take effect? 

The use case of the permission requirement is to allow selected engineers read/write sql but not on the table containing sensitive information.

**Comment by shijialee** [comment]
After a day, the privileges changes appears on metabase. It would be nice to have this taken effect immediately though. 

I hope the metabase team can shed some light on this behaviour.

**Comment by salsakran** [comment]
We automatically sync our metadata once a day. If you want to do so more frequently, you can do so by clicking "Sync now" on the database page in the admin panel. 

Was caching on? We do not currently evict cached results when the tables they reference disappear, since sometimes networks go down, etc.

**Comment by mazameli** [comment]
I'm not sure if there's anything actionable about this issue. Is this a bug, a feature request (i.e. to evict cached results when the tables they reference disappear), or should we just close this?

**Comment by flamber** [comment]
This was likely caused by MySQL not dropping the current connection Metabase had.
Closing, since I haven't heard of anyone else having this problem in later versions of MySQL/Metabase
