### ISSUE TITLE
Missing download icon in card page

### ISSUE THREAD

**Issue by gilhs** [metabase/metabase#5180]
- Your browser and the version: Chrome 58.0.3029.110 (64-bit)
- Your operating system: OS X 10
- Your databases: BigQuery
- Metabase version: 0.24.1

Seemingly random, but in many of my cards the download raw data button is missing. There's 1 JS exception which doesn't strike me as relevant, but maybe is:

Refused to execute script from 'https://metabase.omcomcom.com/question/snippets/text.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

![image](https://cloud.githubusercontent.com/assets/22723398/26392487/6a4d1ea0-406f-11e7-8e27-b7cc64f80834.png)

This started happening after upgrading from 0.22 to 0.24.1

**Comment by leomelzer** [comment]
Does your question have a filter without default value?

Then se here: https://github.com/metabase/metabase/issues/5047

**Comment by gilhs** [comment]
Yes, that's actually the case. This can be closed as duplicate - thanks!
