### ISSUE TITLE
Provide better validation for custom field expression input

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5184]
There are a couple of things we could do to make it clearer in the UI what you can and can't do in custom field formulas:

1) We should make it clearer that you can't use aggregation functions. Right now all we do is make the border of the input field red and disable the `Done` button. Maybe we also should not tokenize the functions:

![screen shot 2017-05-24 at 10 26 40 am](https://cloud.githubusercontent.com/assets/2223916/26416743/c64c5742-406b-11e7-908a-605984ea71af.png)

2) Arguably, until we have valid operations you can perform on non-numeric fields, we shouldn't be displaying those fields in the autocomplete/suggestion menu:

![screen shot 2017-05-24 at 10 24 40 am](https://cloud.githubusercontent.com/assets/2223916/26416793/ed9398e2-406b-11e7-97d4-0e9cd7339d5a.png)

![screen shot 2017-05-24 at 10 25 13 am](https://cloud.githubusercontent.com/assets/2223916/26416798/f36f8c26-406b-11e7-9761-dda4d6bb68a2.png)

**Comment by flamber** [comment]
Likely fixed since 0.35.0 - otherwise 0.39.0 would be another improvement
