### ISSUE TITLE
Erroneous error using variable in both `group by` and `select`

### ISSUE THREAD

**Issue by rhys-vdw** [metabase/metabase#5189]
_Perhaps related to #5181, but this may be a separate issue._

- Your databases: PostgreSQL
- Metabase version: v0.23.0
- Metabase hosting environment: Heroku
- Metabase internal database: _will investigate if requested_

I want to use the following query:

```sql
select
  date_trunc({{interval}}, created_at) date,
  case when response_id is not null then 'responded' else 'not responded' end,
  count(*)
from panelist_order_assignments
group by
  date_trunc({{interval}}, created_at),
  response_id is not null
```

But I get the following error:

![image](https://cloud.githubusercontent.com/assets/822105/26431480/692385d6-4138-11e7-8017-c053f681d5c3.png)

However manually interpolating the variable works fine:

```sql
select
  date_trunc('day', created_at) date,
  case when response_id is not null then 'responded' else 'not responded' end,
  count(*)
from panelist_order_assignments
group by
  date_trunc('day', created_at),
  response_id is not null
```

**Comment by salsakran** [comment]
You'll need to add quotes to the template, eg
`'{{interval}}'`

**Comment by rhys-vdw** [comment]
Sorry, but I don't think that's correct:

Query suggested by @salsakran:

```sql
select
  date_trunc('{{interval}}', created_at) date,
  case when response_id is not null then 'responded' else 'not responded' end,
  count(*)
from panelist_order_assignments
group by
  date_trunc('{{interval}}', created_at),
  response_id is not null
```

Result:

![image](https://user-images.githubusercontent.com/822105/26871524-cb85911e-4bb6-11e7-9606-480ad7eca438.png)


However the following query (without quotes) executes fine:

```sql
select date_trunc({{interval}}, created_at) date from panelist_order_assignments;
```

**Comment by jeffling** [comment]
```
select
  date_trunc({{interval}}, created_at) date,
  case when response_id is not null then 'responded' else 'not responded' end,
  count(*)
from panelist_order_assignments
group by
  1,
  response_id is not null
```
will work

**Comment by camsaul** [comment]
Sounds like the question was answered. For future reference, these sorts of questions are best asked on https://discourse.metabase.com

**Comment by rhys-vdw** [comment]
The answer appears to be a different query (didn't see it until now). This is not a question, but a bug report. However, I have no idea if the issue is still present.

**Comment by corbettzhang** [comment]
How about trying it this way?

**Comment by corbettzhang** [comment]
How about trying it this way?

`select
  CAST(date_trunc({{interval}}, created_at) date) AS "c1",
  case when response_id is not null then 'responded' else 'not responded' end,
  count(*)
from panelist_order_assignments
group by
  "c1",
  response_id is not null`

**Comment by corbettzhang** [comment]
How about trying it this way?

`
select
  CAST(date_trunc({{interval}}, created_at) date) AS c1,
  case when response_id is not null then 'responded' else 'not responded' end,
  count(*)
from panelist_order_assignments
group by
  c1,
  response_id is not null
`
