### ISSUE TITLE
Unable to build docker image using Dockerfile

### ISSUE THREAD

**Issue by cbhimavarapu-datalicious** [metabase/metabase#5190]
------
I'm using  master branch to build docker image using the Dockerfile but its failing 

> Retrieving compojure/compojure/1.5.2/compojure-1.5.2.jar from clojars
Retrieving ring/ring-codec/1.0.1/ring-codec-1.0.1.jar from clojars
Retrieving dk/ative/docjure/1.11.0/docjure-1.11.0.jar from clojars
Retrieving environ/environ/1.1.0/environ-1.1.0.jar from clojars
Retrieving medley/medley/0.8.4/medley-0.8.4.jar from clojars
Retrieving metabase/throttle/1.0.1/throttle-1.0.1.jar from clojars
Retrieving honeysql/honeysql/0.8.2/honeysql-0.8.2.jar from clojars
Retrieving postgresql/postgresql/9.3-1102.jdbc41/postgresql-9.3-1102.jdbc41.jar from clojars
Retrieving ring/ring-jetty-adapter/1.6.0/ring-jetty-adapter-1.6.0.jar from clojars
Retrieving prismatic/schema/1.1.5/schema-1.1.5.jar from clojars
Retrieving ring/ring-core/1.6.0/ring-core-1.6.0.jar from clojars
Retrieving ring/ring-servlet/1.6.0/ring-servlet-1.6.0.jar from clojars
Retrieving ring/ring-json/0.4.0/ring-json-0.4.0.jar from clojars
Retrieving scout/scout/0.1.0/scout-0.1.0.jar from clojars
Retrieving stencil/stencil/0.5.0/stencil-0.5.0.jar from clojars
Retrieving quoin/quoin/0.1.2/quoin-0.1.2.jar from clojars
Retrieving toucan/toucan/1.0.3/toucan-1.0.3.jar from clojars
Could not find artifact io.crate:crate-jdbc:jar:2.1.6 in central (https://repo1.maven.org/maven2/)
Could not find artifact io.crate:crate-jdbc:jar:2.1.6 in clojars (https://clojars.org/repo/)
Could not transfer artifact io.crate:crate-jdbc:jar:2.1.6 from/to bintray (https://dl.bintray.com/crate/crate): Read timed out
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Uberjar aborting because jar failed: Could not resolve dependencies
The command '/bin/sh -c bin/build' returned a non-zero code: 1

Am I doing something wrong here?
I just ran `docker build .` command in master branch

**Comment by thearthur** [comment]
`from/to bintray (https://dl.bintray.com/crate/crate): Read timed out` 

Sounds like a networking problem downloading a dependency?

**Comment by cdmarioe** [comment]
You Should probe Java Version. it's easiest

**Comment by camsaul** [comment]
Resolved now that we're no longer bundling the Crate driver directly
