### ISSUE TITLE
Prefix "₹" gets converted to "?" on save on RDS

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#5192]
This used to work fine on 0.22.2 on H2 but not on RDS (MySQL)

Observed on:

Chrome Version 58.0.3029.81 (64-bit)
Ubuntu 16.04
MongoDB
Metabase version: 0.24.1
Hosted on Elastic Beanstalk t2.medium
Metabase internal database: MySQL

**Comment by jefffriesen** [comment]
@ujjwal-gupta Sorry to hijack this ticket. We are unable to use Metabase on RDS because of this issue: https://github.com/metabase/metabase/issues/1350

Have you found a way to use Metabase with RDS using SSL?

**Comment by ujjwal-gupta** [comment]
@jefffriesen Unfortunately no. Both Metabase and RDS are on our VPC.

**Comment by camsaul** [comment]
What is this a prefix for? (i.e. what are you saving?)

**Comment by ujjwal-gupta** [comment]
This is the prefix for "Rupee" the Indian national currency(INR). Similar to how '$' is for Dollars. We are saving amounts in this currency. You can refer to encodings for the same [here](http://www.fileformat.info/info/unicode/char/20b9/index.htm)

**Comment by camsaul** [comment]
Sorry I meant what is it you're saving with the rupee symbol in the name? E.g. A question or dashboard or collection or ?

**Comment by ujjwal-gupta** [comment]
In the extra options menu for numbers, prefix and suffix for the number can be set. I have a saved question for a number and after adding the prefix to it, and saving it, on reload, the '₹' change to a '?'

**Comment by ujjwal-gupta** [comment]
This issue seems to still have the 'Need more info' label. @camsaul any more information required from my side on this?

**Comment by jornh** [comment]
I would strongly suspect this to be a database configuration issue see #7438 and what lead to resolution in https://github.com/metabase/metabase/issues/7438#issuecomment-385920191

Your environment is the same MySQL on RDS

**Comment by feronera** [comment]
For infra side. Confirm that in RDS just change **character_set_database** and **characeter_set_server** to your unicode at parameter group or cluster parameter group. 

For me utf8mb4 is correctly display after changed params.

Cheers!

**Comment by camsaul** [comment]
Related to #10691. Fixed for new Metabase DBs by #11742 and for existing DBs by #11753 (once merged)

**Comment by camsaul** [comment]
Fixed by #11753
