### ISSUE TITLE
AutoHide banner in public dashboards when idle in full screen

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#5199]
Feature request / proposal:

Currently the banner at the bottom with the refresh, night-mode, full-screen option is taking up valuable screen real-estate. We use a public shared dashboard to display important stats on a TV and we'll be able to show more if the banner auto-hides in fullscreen. 

Ideally full-screen mode should just display the dashboard and nothing else unless someone mouses over to the bottom/top.

**Comment by nmuldoon** [comment]
Related to https://github.com/metabase/metabase/issues/4468

**Comment by flamber** [comment]
Closing this, since it's showing below-the-fold when I test on 0.41.1 with Public dashboard in fullscreen.
This this might have been changed around 0.34
