### ISSUE TITLE
Database list not cleared on logout - may show databases user doesn't have access to

### ISSUE THREAD

**Issue by sldorman** [metabase/metabase#5202]
I revoked access to a database for All Users and for all groups. When I log out of my admin session, then log in as another user, on the same browser, without refreshing, and try to create a new question, the restricted database appears in the database dropdown and if selected, the tables appear in the dropdown. Once the query is run, it says "Sorry, you don’t have permission to see that.".  I would expect that the database would not even appear in the dropdown.

- Your browser and the version: 53.0.2 (32-bit)
- Your operating system: Windows 7
- Your databases: SQL Server
- Metabase version: 0.24.1
- Metabase hosting environment: jar on Win 7
- Metabase internal database: H2 (default)

**Comment by mazameli** [comment]
I didn't test this on Windows or with a SQL Server DB, but was unable to reproduce this on MacOS with any of the DBs I tried. Does this behavior happen even if the other users log out and back in again? Have you verified those other users aren't marked as Admins?

**Comment by sldorman** [comment]
I only have 2 user accounts - SD which is admin and SV which is not.  I have logged out and back in several times. Here is information about the accounts and database permissions:

![peoplepermissions](https://cloud.githubusercontent.com/assets/7422621/26631984/bca9f1d4-45db-11e7-82a3-f6e2d3cd1ca8.png)

![databasepermissions](https://cloud.githubusercontent.com/assets/7422621/26632013/deda6504-45db-11e7-89af-5514d4464b9d.png)

I'm logged into the SV account

![svaccount](https://cloud.githubusercontent.com/assets/7422621/26632074/27a6b742-45dc-11e7-93d9-7e8b525d7f67.png)

When I create a New Question, I see all of the databases in the dropdown:

![newquestiondatabasedropdown](https://cloud.githubusercontent.com/assets/7422621/26632088/3a6f366a-45dc-11e7-9214-ec7f510a8c2d.png)

**Comment by sldorman** [comment]
Some further information - if I try to create a query with the restricted database (SLQ Server 2012 DataViewer) - like I mentioned in my first post - I am able to select tables and get an error message when I select Get Answer.  Once that error message is up, I can't seem to do anything so I hit F5 to refresh and when I tried to create another new question, the restricted db is no longer in the dropdown.  I logged out and then back in as the admin user (SD) and it does not show the restricted db in the dropdown (and it should since admin has permission).  If I hit F5, the dropdown is corrected.  I have restarted the jar and get the same response - the dropdown list only shows whatever was last seen, regardless of user, and the only way to get the correct one is to refresh.

**Comment by hagen** [comment]
I get this too. There's some client side caching going on, that isn't invalidated on log out. If I log in as admin, pull up all databases, then log out and back in as ordinary user, I see admin dbs, but can't actually query them.

**Comment by hagen** [comment]
The other thing that we as users of metabase need to do is be 'way' more specific with our issues. Your issue reads:

> I revoked access to a database for All Users and for all groups. When they try to create a new question, the restricted database appears in the database dropdown and if selected, the tables appear in the dropdown. Once the query is run, it says "Sorry, you don’t have permission to see that.". I would expect that the database would not even appear in the dropdown.

But the actual problem is:
> I revoked access to a database for All Users and for all groups. When _I log out of my admin session, then log in as another user, on the same browser, without refreshing_, and try to create a new question...

Not something we automatically know, but helps get right to the nub of the problem.

**Comment by sldorman** [comment]
Thanks @hagen for the better description.  Can the "Unable to Reproduce" label be removed for this issue?

**Comment by attekei** [comment]
Ugh, I didn't realize that we don't clear all frontend state when user logs out. I'll take care of this. Thanks @sldorman and @hagen for the report. Could you @sldorman also update the description?

**Comment by paulrosenzweig** [comment]
Fixed by #7600
