### ISSUE TITLE
When editing a question in certain circumstances, question is removed from the collection it was originally a member of

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#5204]
Here is my flow to reproduce:

1. Go to any dashboard, click on a card to be taken to the question (question must be part of a collection)
2. Edit some part of the new question, for me it was adding  a variable
3. Save the new question, overwriting the original question
4. The newly saved question is no longer in a collection, but is in the 'Everything Else' section of the 'Questions' page

I would expect the question to stay in the same collection it was originally a member of.

**Comment by mazameli** [comment]
I couldn't reproduce this unfortunately. Any other JS console errors or server log errors? Which version of Metabase are you on, and what's your setup environment? Which browser are you using? What kind of database are you working with?

**Comment by doodlebro** [comment]
Hmmmm, looks like I can't reproduce it either. When I made this 5 days ago, I kept reproducing it for a dashboard I was building. I'll keep an eye out for this coming back & re-open the issue if necessary.
