### ISSUE TITLE
MongoDB near query problem 

### ISSUE THREAD

**Issue by zaza81** [metabase/metabase#5206]
I am using MongoDB  3.2.12

The following query:

`.find( {latlng : { "$near" : [ 37.76 , -122.43 , 0.2]}})
`

is working fine when directly querying with a basic client.

The latlng field is the following:

```
"latlng" : {
        "lat" : Double,
        "long" : Double
    }
```

When using a native query in metabase:

```
[
    { 
        "latlng" : 
            { 
                "$near" : [ 37.76 , -122.43 , 0.2]               
            }       
    }
]
```

I get the following:

>  { "ok" : 0.0, "errmsg" : "Unrecognized pipeline stage name: 'latlng'", "code" : 16436 }

I am using correctly the native query system or there are still limitations on the geo search?

**Comment by camsaul** [comment]
Hi @zaza81, that doesn't look like a correctly written Mongo query. Check out the [Mongo Aggregation Pipeline docs](https://docs.mongodb.com/manual/core/aggregation-pipeline/) for a little more info.

**Comment by zaza81** [comment]
Thanks @camsaul!

I am not trying to aggregate. It's a simple query for getting a list of documents. Am I using the wrong syntax?

**Comment by camsaul** [comment]
@zaza81 Metabase only accepts native Mongo queries written as Mongo Aggregation Pipeline queries. Refer to that link I posted to learn more about how to write your queries that way.

**Comment by zaza81** [comment]
@camsaul I see. Thanks a lot
