### ISSUE TITLE
Is it possible to develop with Metabase in Windows OS

### ISSUE THREAD

**Issue by joboyx** [metabase/metabase#5214]
**Question**

Can anyone confirm if we can develop with metabase in Windows 8/10 OS?

I've tried to follow the Development Guide, but we're stuck with running the front-end server

```
$ yarn run build-hot
yarn run v0.24.6
$ NODE_ENV=hot webpack-dev-server --progress
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm and.
```

and it looks like yarn is executing bash shell scripts which is expected to fail in `cmd` of Windows.

----

**Why we're doing this?**

We would just like to update frontend CSS files to change the look and feel of metabase UI.

**Comment by camsaul** [comment]
Hi @joboyx, unfortunately it's a know issue that `yarn run build-hot` doesn't work on Windows. You should still be able to run `yarn run build`, which certainly isn't ideal for interactively working on frontend components, but at least will still allow you to make changes and see them in action.

**Comment by joboyx** [comment]
Good to know. Will try this out. Thanks!

**Comment by salsakran** [comment]
Updated the docs to reflect this.
