### ISSUE TITLE
Cannot save slack integration

### ISSUE THREAD

**Issue by 5an1ty** [metabase/metabase#5216]
Running the latest docker image: 0.24.1

docker run -d -p 3000:3000 --restart=always -v /usr/local/metabase:/tmp -e "MB_DB_FILE=/tmp/metabase.db" --name metabase metabase/metabase

All ports open and no firewall stopping anything. Everything else seems to work fine including smtp integration. Bot account seems to be set up correctly on the slack side and I have created the channel #metabase_files and invited the bot to it.

```
05-29 07:53:49 ERROR metabase.middleware :: PUT /api/slack/settings 500 (1 s) (0 DB calls)
{:message "Read timed out",
 :stacktrace
 ["integrations.slack$do_slack_request.invokeStatic(slack.clj:32)"
  "integrations.slack$do_slack_request.doInvoke(slack.clj:30)"
  "api.slack$fn__38214$fn__38217$fn__38218.invoke(slack.clj:22)"
  "api.slack$fn__38214$fn__38217.invoke(slack.clj:19)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:229)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:224)"
  "api.slack$fn__38214.invokeStatic(slack.clj:11)"
  "api.slack$fn__38214.invoke(slack.clj:11)"
  "middleware$enforce_authentication$fn__38784.invoke(middleware.clj:120)"
  "api.routes$fn__38946.invokeStatic(routes.clj:77)"
  "api.routes$fn__38946.invoke(routes.clj:77)"
  "routes$fn__39540$fn__39541.doInvoke(routes.clj:64)"
  "routes$fn__39540.invokeStatic(routes.clj:60)"
  "routes$fn__39540.invoke(routes.clj:60)"
  "middleware$log_api_call$fn__38883$fn__38885.invoke(middleware.clj:329)"
  "middleware$log_api_call$fn__38883.invoke(middleware.clj:328)"
  "middleware$add_security_headers$fn__38833.invoke(middleware.clj:243)"
  "middleware$bind_current_user$fn__38788.invoke(middleware.clj:140)"
  "middleware$maybe_set_site_url$fn__38837.invoke(middleware.clj:266)"]}
```

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by salsakran** [comment]
Sounds like a network issue.  Are you able to connect to `https://slack.com/` from within that docker container?

**Comment by 5an1ty** [comment]
I can curl https://slack.com and ping slack.com

**Comment by 5an1ty** [comment]
Still an issue with: 0.24.2

**Comment by panuavakul** [comment]
I have the same problem

**Comment by flamber** [comment]
The Slack integration was rewritten in 0.36.0 with a timeout of 10 seconds, instead of 1 second, which was likely the problem here. Closing, since it hasn't been reported for years.
