### ISSUE TITLE
Contributing to frontend - help with a Guidance 

### ISSUE THREAD

**Issue by mokra** [metabase/metabase#5217]
Dear Team,
I would also like to contribute, but I don't have any JAVA or Clojure understanding. But I do work on SQL, JS and CSS a lot. And I would love to contribute, but it seems, that every time i do ./bin/build it takes about 5 min. untill the process is finished. Is there a way to change JS and CSS files live without the need of rebuilding the whole project? This would definitely make things much faster. Thanks

**Comment by jornh** [comment]
Looks like https://github.com/metabase/metabase/blob/master/docs/developers-guide.md#frontend-development has some hints. In particular `yarn run build-hot`

**Comment by mokra** [comment]
I see - and in which folder are the js and css files that I can then edit?

**Comment by jornh** [comment]
https://github.com/metabase/metabase/tree/master/frontend

**Comment by kdoh** [comment]
@mokra - Looks like @jornh has steered you in the right direction (thanks @jornh!) so I'm going to close this issue. I'd also recommend taking a look at our [contributing guide](https://github.com/metabase/metabase/blob/master/docs/contributing.md) to get a sense of the process, and starting with issues labeled ["Help Wanted"](https://github.com/metabase/metabase/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22). Thanks for your interest!

**Comment by mokra** [comment]
Thanks @kdoh & @jornh- I could start the command and I can see that it is running in the console. In the config file I see localhost:8080 (right now the project is on a server in the web). How do I access metabase in browser? If I try to go to http://IP:8080 I don't get any result
