### ISSUE TITLE
Support Google Auth with multiple domains

### ISSUE THREAD

**Issue by lukabirsa** [metabase/metabase#5218]
We're using Google SSO support which works great, as long as you use only a single domain. We do have multiple leading domains / sub organizations in our setup, which means that a part of our users cannot access the server without adding them manually. 

To fix: convert the domain entry field to support multiple domains, separated with ; or , or ' '.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by paivaric** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by luosprz** [comment]
+1

**Comment by MaximeLaurenty** [comment]
Hi,
I see this has a decent number of 👍 but no action for a few years, any plan on tackling this?
(I did 👍 it)

**Comment by noahmoss** [comment]
I've merged #15820, so this will be available in 0.40 with a valid enterprise SSO token

**Comment by aaaaahaaaaa** [comment]
It's a bummer that this feature is only part of your enterprise offer. Redash offers this by default.

**Comment by haithem-souala** [comment]
Can you make this available in the FREE version?
