### ISSUE TITLE
Error exporting XLSX and CSV when use VARCHAR(MAX)

### ISSUE THREAD

**Issue by sldorman** [metabase/metabase#5220]
This may be related to #5145 which used arrays on the query.  The XLSX error was similar but the CSV was fine on that bug - that is not the case for me.  When I export to XLSX, I get an error.  When I export to CSV, I don't get an error but I get bad data in the CSV file.

The problem is caused by declaring a variable with a MAX size.  If I change VARCHAR(MAX) to VARCHAR(200), everything works fine.

- Your browser and the version: 53.0.3 (32-bit)
- Your operating system: Windows 7
- Your databases: SQL Server 2012
- Metabase version: 0.24.1
- Metabase hosting environment: Jar on Windows 7 (same machine as SQL Server and browser)
- Metabase internal database: H2

Question:

DECLARE @someString	VARCHAR(MAX);
SET		@someString = 'Just a string';

SELECT Row_Num, @someString AS MaxString
FROM [dbo].[POV_ContractDate_Analysis] 

Answer:

![image](https://cloud.githubusercontent.com/assets/7422621/26586682/f7f270ea-451d-11e7-9e69-b1904937e92c.png)

XLSX Error:

![image](https://cloud.githubusercontent.com/assets/7422621/26586724/133a1ace-451e-11e7-9232-6200830dea86.png)

CSV File Contents:

![image](https://cloud.githubusercontent.com/assets/7422621/26586790/44579c76-451e-11e7-94c3-877d7d701a60.png)

**Comment by camsaul** [comment]
This should be easy enough to fix we just need to add an implementation for `set-cell!` for the JTDS `ClobImpl` class as suggested by the error message

**Comment by camsaul** [comment]
@sldorman in PR #5491 (branch `allow-additional-options-for-sqlserver`) I'm experimenting with switching from the jTDS JDBC driver to the official Microsoft one which as far as I can tell doesn't return a CLOB type like jTDS does which would eliminate this issue. Could you give that a try and let me know if it indeed resolves this for you?

**Comment by sldorman** [comment]
@camsaul I'm just getting back to this (sorry) - do you still need me to test this?  Is it still in the same branch?

**Comment by camsaul** [comment]
@sldorman don't worry about testing this, we actually ended up fixing problems with XLSX exports more generally in #5496 which we shipped as part of 0.25.

**Comment by elcolumbio** [comment]
thanks for fixing. I think i run in this problem at other places now.
Pulses and Download as CSV, latter is not so important since XLSX export works now.
I am on the newest version 0.25.2
