### ISSUE TITLE
Clicking on line cards in dashboards loses lineage in query builder

### ISSUE THREAD

**Issue by Digma** [metabase/metabase#5221]
I couldn't find any issue already open so posting. Not sure if this is part of https://github.com/metabase/metabase/pull/5208

## Bug

When clicking on the title of a "line" card (may apply to "area" and some other visualization as well) inside a dashboard, the filters already applied in the dashboard are lost when arriving in the query builder. Clicking on the tile of a "raw data" card (the same query but saved as "raw data") does forward the filters properly to the query builder.

<img width="882" alt="screen shot 2017-05-30 at 17 15 51" src="https://cloud.githubusercontent.com/assets/3279847/26590736/b0ddeca0-455b-11e7-9d49-a578b3f44b0c.png">
(same problem apply to both "time" and "dimension" filter visible in the image)

## Step to reproduce

   1. Create a card a pick "Line" as visualization
   2. Add that card to a dashboard
   3. Add a filter to the dashboard and link it to the card
   4. Load the dashboard, when clicking on the title of the card, the filter will be lost in the query builder. 

Doing the same steps but picking "Raw Data" works though (or having a card with 2 or more "lines" does work)

## Info

- Your browser and the version: Chrome 58.0
- Your operating system: OS X
- Your databases: Bug reproduced with MySQL & Druid
- Metabase version: 0.24.1
- Metabase hosting environment: RHEL 7
- Metabase internal database: MySQL

**Comment by mazameli** [comment]
I was able to reproduce this, but specifically, you have to click the title of the line chart. If you use the pivot or drillthrough actions, the dashboard filters do persist.

**Comment by Digma** [comment]
@mazameli Good point, I updated the issue to reflect this

**Comment by Digma** [comment]
Seems line #5208 fixed the issue. However now another issue arise. When clicking on the title of a "line" card, it redirects properly to the query builder with filters but it displays the card as a "raw table". It is impossible to change it back to "line" without changing the query

This query in the dashboard:

<img width="834" alt="screen shot 2017-06-01 at 16 46 41" src="https://cloud.githubusercontent.com/assets/3279847/26685340/181582ea-46ea-11e7-91b2-57a26d25ac20.png">

Produces this in the query builder (cannot change the visualization back to line):

<img width="627" alt="screen shot 2017-06-01 at 16 46 34" src="https://cloud.githubusercontent.com/assets/3279847/26685339/180f532a-46ea-11e7-87ba-347be37b8986.png">

**Comment by salsakran** [comment]
closed via #5208
