### ISSUE TITLE
Druid HyperUnique aggregator in View dropdown

### ISSUE THREAD

**Issue by psalaberria002** [metabase/metabase#5223]
### Feature requests and proposals

Hi guys!

I am trying to generate a query that involves a Druid HyperUnique aggregator. Currently I am able to do so via native query.

It would be great if this was available in the View dropdown. Currently "Number of distinct values of..." returns 1 for yyperUnique type columns.

Did you already have a look at this feature? If not, could you point me in the right direction so I can try to implement it?

Thank you.

**Comment by slipset** [comment]
This would make working with Druid much more effective. +1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.
