### ISSUE TITLE
Rename Field (column) Labels

### ISSUE THREAD

**Issue by lukabirsa** [metabase/metabase#5233]
As a user, I would like to be able to edit field (column) labels.

If I create a dual aggregation view then I get generic labels - example: SUM_1, SUM_2... Please allow me to edit this so it's clearer what data is displayed.

**Comment by PierreBM** [comment]
:+1: 
It's a pity that we cannot change automatic labels for this kind of charts
![capture du 2017-06-01 18-14-16](https://cloud.githubusercontent.com/assets/22468422/26689560/521f88bc-46f6-11e7-91a4-36951672d354.png)
But great job anyway !

**Comment by tlrobinson** [comment]
You can actually do this if you switch the aggregation to a custom expression (only aggregations at the moment)

**Comment by PierreBM** [comment]
Thank you for you help. 
Metabase is awesome, however, the documentation is sometimes not enough detailed.
It would be great if you had many chart examples with all kinds of setings, that we can explore to see the configuration you set !
Regards,
Pierre

**Comment by PierreBM** [comment]
For example, is there a way to choose in which order the data is used ? It seems to use the label alphabetical order. I prefixed the labed with a number to define the 
![metabase_bar_sort](https://cloud.githubusercontent.com/assets/22468422/26699243/56bdc64a-4719-11e7-92ed-c92e76a99c6e.png)
order.

**Comment by CherylEveritt** [comment]
We would also love to see improvements to the column naming. Is there any plan to include this in the near future?

**Comment by thenaturalist** [comment]
+1

**Comment by Ayusuf95** [comment]
Same issue, this would be particularly useful for GA goal completion reporting since you can't return custom column names in the API query like you can in SQL

**Comment by mazameli** [comment]
Happy to report this was implemented via #8541. This will be included in the upcoming 0.31 release.

![rename-series](https://user-images.githubusercontent.com/2223916/46977000-ccc9c780-d07f-11e8-848f-357b56cb8120.gif)

**Comment by davidproxima** [comment]
What about on Table reports?

**Comment by Ayusuf95** [comment]
As far as I can ascertain you still can't change columns/series names in Tables, this update allows changing series names in charts though. Which still isn't useful for GA table reports where you can't bypass/change names using SQL

**Comment by davidproxima** [comment]
I get it. that response makes sense. and i did just use sql to update my table headers. would just be nice to be able to do that in the gui....as a sql statement, you then lose the ability to convert that to a graph later.

**Comment by mazameli** [comment]
I should have been more specific: it works for table headers, too. :) Again, this will be included in our upcoming 0.31 release, which is not out quite yet.

![table-column-name](https://user-images.githubusercontent.com/2223916/47747076-b8bbc380-dc44-11e8-929d-ce2b3940e7a8.gif)

**Comment by Ayusuf95** [comment]
That's great to hear, look forward to it! Y'all are doing a good job keeping up with peoples feature requests and providing a very useful product!

**Comment by davidproxima** [comment]
Ahhh, got it. I missed the reference to the version. Very cool. Thank you sir!
