### ISSUE TITLE
Feature request: make required slack channel name configurable

### ISSUE THREAD

**Issue by ricardojmendez** [metabase/metabase#5236]
Currently Metabase has hard-coded a required channel name, `metabase_files` (see #3976). It would be useful to have this channel name configurable from the environment.

Filing for tracking purposes, I'll likely submit a PR later this week.

Context, so you can see how this bit us: 

- A user on our team created the channel as private;
- We can't turn private channels public (something he didn't know);
- Slack does not let you delete private channels, only archive them;
- Pulse fails if the `metabase_files` channel is private and reports it as missing, even if the Metabot is on the channel.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
For what its worth -`metabase_files` is where we store rendered charts for the pulses + slackbot responses as the slack api doesn't allow you to attach an image file to a post. It is not where things should be posted. This is actually entirely separate from Metabot.

**Comment by ricardojmendez** [comment]
Well, duh. For what it's worth, I just found a silly workaround for our problem. We can't delete private channels nor turn them public, but we _can_ rename the private channel and create a new one for `metabase_files`.

**Comment by maxzheng** [comment]
It would be great if it would work with private channels, otherwise it's not safe to use for sensitive content as anyone can see/join a public channel.

**Comment by mih-kopylov** [comment]
It would be even better to avoid having such a channel
https://github.com/metabase/metabase/issues/3976#issuecomment-268064205
Referring to this comment, it was a best choice from a number of bad ones.

@salsakran Probably, Slack API provides a better solution now, as several years have passed since that?

**Comment by mysticaltech** [comment]
It would be great, "metabase_files" is not the sexiest of names, if we are going to hard-code things, why not make it generic as hell, like "metabase" ?

**Comment by vkambhampati493** [comment]
I made the same mistake of making metabase_files private and I followed @ricardojmendez 's work around but it is not working. The pulse will not post to the new new metabase_files channel (this is public)
