### ISSUE TITLE
Ability to create pre-populated SQL filters

### ISSUE THREAD

**Issue by gilhs** [metabase/metabase#5245]
Roughly all of our queries are SQL queries, as they pretty much all require multiple joins or sub-queries.  This causes different kinds of pains when it comes to interacting with the queries via a dashboard, mostly around filtering:
- BigQuery Views cannot work with dropdowns, as view discovery is not currently supported (#3414)
- Using field filters forces us not to use table or sub_query aliasing, due to its structure (#3328) which creates really ugly / hard to maintain queries
- Using the same field filter for multiple tables fails, because field-filters are tied to a single table (this is probably the only thing that I cannot find a way to workaround)

This means that we are forced to use textual filters, which honestly generate a bad user experience.

I have 2 possible resolution suggestions:

1. Add a new type of filters which has a SQL query behind it. This can be capped with # of results for performance. Usage would be identical to field filters (`where {{filter}}`) with a new type of variable called `dashboard` - just have to make sure that the dashboard filter uses the same name (e.g. `filter`) and it should work.
2. Add ability to create pre-populated filters using the admin panel. These could be dynamic (SQL, same as above) or static (based on a list of updatable values through the panel).

This would be a great addition to MB (which is an amazing product btw!), and would remove one of the biggest pain-points we are experiencing with using it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
Thanks for the thought out suggestion! Really appreciate how much context you've put into this. 

I'm digesting your suggestions and trying to think through how this would all work.

**Comment by salsakran** [comment]
oh, are you using legacy or standard sql?

**Comment by gilhs** [comment]
Currently using legacy, but it is my understanding that going forward you plan to only support the standard syntax, so will sooner or later migrate.

**Comment by gilhs** [comment]
Another piece of feedback - yesterday I was sitting with our product team, and I was showing them the self-service question tool. Once snag we hit was not having auto-complete for possible values when adding filters - something they are used to from working with other tools (e.g. Mixpanel).

While this is not the same use-case, it's similar enough that a single solution might be plausible for both cases.

**Comment by RomanCPodolski** [comment]
Is there progress on this?

**Comment by flamber** [comment]
Related to #6820

**Comment by aaaaahaaaaa** [comment]
@flamber Out of curiosity, is this on your radar in terms of roadmap?
I've been a user of Metabase for a little while now, and I have to say I keep facing on a regular basis the lack of SQL based variables as a major drawback. `Field Filter` is a nice functionality when it works, but it's very constraining and often incompatible.

**Comment by flamber** [comment]
@aaaaahaaaaa Roadmap is available here: https://www.metabase.com/roadmap/
If you don't see the functionality you want on the list, then I cannot tell you when it will be addressed.

**Comment by luizarakaki** [comment]
This was shipped on 0.46
https://github.com/metabase/metabase/issues/26873
