### ISSUE TITLE
Automated download

### ISSUE THREAD

**Issue by Nyno-Kun** [metabase/metabase#5252]
Hi!
We want to build a pkg from Metabase to automate updates.
So we also want to build those packages automated but we can not do this because the download of the Jar is based on a versioned link (http://downloads.metabase.com/v0.24.2/metabase.jar).
Is it maybe possible to change this to something like http://downloads.metabase.com/latest/metabase.jar ?
That would help us much! 
Regards, Nyno

**Comment by flamber** [comment]
I don't know exactly when it was added, but now `/latest/` is available - so you can bookmark this:
https://downloads.metabase.com/latest/metabase.jar

**Comment by thbar** [comment]
Thank you very much! This allows unattended upgrades in cases this is practical.
