### ISSUE TITLE
question regarding stored SQL queries and results

### ISSUE THREAD

**Issue by mokra** [metabase/metabase#5253]
I wish to update the query_cache table manually (using a cron). 
I've got 2 questions:
1. In the table report_card - column dataset_query the query is stored. How can I convert this to an actual SQL-query?
2. Afaik, MB stores cached results for cached questions in the query_cache table. But these results are stored as BLOB format.  How can these be compressed/uncompressed?

thanks a lot

**Comment by salsakran** [comment]
translating the dataset_query to sql is what a database driver (https://github.com/metabase/metabase/tree/master/src/metabase/driver) and the query processor code (https://github.com/metabase/metabase/tree/master/src/metabase/query_processor) do.

It's ... nontrivial. I'd suggest just running each saved question (called report_card for legacy reasons). This will result in the query results being placed in the cache.

Closing this as the specific questions relate to an internal api that is neither fixed, nor recommended for use =)

**Comment by mokra** [comment]
@salsakran Thanks.
Here is the reason for this question: Some cached qustions might take a really long time to query. So I don't want the user to wait. Instead I want the run the query of cached questions in the background. 

One other trick would be to let only one specific user refresh the cache (by running each saved question) - All other users would just open the question and see cached results (only by clicking "refresh" they would acctually refresh the cahe.)

But this is just a trick - could you think of something else, how to achieve this?
