### ISSUE TITLE
Funnel visualization doesn't show title and description

### ISSUE THREAD

**Issue by alexdebrie** [metabase/metabase#5254]
I'm making some funnel visualizations in a dashboard by combining multiple data sources. If I use the "Bar chart" funnel type, it shows my title and description as created in the card settings. If I switch it to a "Funnel" funnel type, the title and description are hidden -- it only shows the series legend.

Screenshot (Bar chart on left, Funnel on right):

![screen shot 2017-06-02 at 9 00 52 am](https://cloud.githubusercontent.com/assets/6509926/26729448/4b992c50-4773-11e7-8388-61cb1eda983a.png)

I poked through the code a bit. I think the Bar Chart funnel works because of [this section](https://github.com/metabase/metabase/blob/1a845b12326605f20bc5fad266645a392529c204/frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx#L212-L235), which allows for two `LegendHeaders` -- one for the title and description, and one for the series legend. I don't know if a similar option should be included [here](https://github.com/metabase/metabase/blob/1a845b12326605f20bc5fad266645a392529c204/frontend/src/metabase/visualizations/visualizations/Funnel.jsx#L117-L123) for the "Normal Funnel", or if all `LegendHeader` logic should be dropped into the `FunnelNormal` component.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome 58
- Your operating system: OSX 10.12
- Your databases: Redshift
- Metabase version: 0.24.1
- Metabase hosting environment: Amazon Linux
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*

**Comment by attekei** [comment]
Fixed by #5545
