### ISSUE TITLE
Filter Filter doesn't show all possible values

### ISSUE THREAD

**Issue by JoelESvensson** [metabase/metabase#5267]
- Your browser and the version: Chrome 58 (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: MacOS 10.12.5
- Your databases: Postgres
- Metabase version: 0.24.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

I have a filter widget that allows me to filter by a slug in the database. However, it only shows 23 of the possible values instead of all 33 that are available.

**Comment by salsakran** [comment]
are the remaining values picked up if you manually trigger a sync in the database detail page in the admin?

**Comment by Varunram** [comment]
I think a mural sync should do the trick as @salsakran mentioned. Happens to me a lot of times while adding tables and stuff. @JoelESvensson can you confirm?

**Comment by JoelESvensson** [comment]
Yes they are! All values are shown right now

**Comment by flamber** [comment]
Closing, since sync worked and without the logs it's hard to know what had failed
