### ISSUE TITLE
iFrame, Public embed, 401 (Unauthorized)

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#5269]
If you have drop down list(Category filter) on iframe, and you are no login on metabase app in any browser tab, then you give 401 (Unauthorized)
![screenshot from 2017-06-05 16-49-17](https://cloud.githubusercontent.com/assets/3535911/26786534/a4539e36-4a0f-11e7-89c7-c52bc175655a.png)

**Comment by attekei** [comment]
I think that this is a duplicate of #5060 and was resolved in #5349.
