### ISSUE TITLE
Embedding Metabase in other Applications, PHP support

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#5270]
PHP Support for server side to generate the signed embedding URL

**Comment by kdoh** [comment]
Hey @MixMe. Embedding support is language agnostic. We shipped with some code examples, but all you really need is a way to work with JSON web tokens (so you can sign the request to Metabase with your secret key) in the language of your choice.

A quick search for PHP turned up https://github.com/firebase/php-jwt, although I haven't worked with PHP in years so I can't vouch for it personally.

More info on embedding can be found [in the embedding guide](http://www.metabase.com/docs/latest/administration-guide/13-embedding.html). In addition we have [embedding reference apps](https://github.com/metabase/embedding-reference-apps) which could help serve as inspiration for your own PHP usage.

**Comment by kdoh** [comment]
@MixMe In addition it looks like there's a PR for a PHP example in the reference apps repo http://github.com/metabase/embedding-reference-apps/pull/1
