### ISSUE TITLE
Undefined Graph filter error

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5271]
## Version: Mac App

I got this weird error while trying to view a dashboard's view. Any suggestions as to why this happened? Thanks for your time!

<img width="1280" alt="screen shot 2017-06-05 at 3 00 01 pm" src="https://cloud.githubusercontent.com/assets/18598959/26794448/4cf4e93a-4a3f-11e7-942d-2f10c095cd20.png">

**Comment by salsakran** [comment]
what version of the mac application are you on? 

what's on the dashboard exactly?

**Comment by Varunram** [comment]
@salsakran I'm on 0.24.0.1 right now. The dashboard pretty much has the standard stuff you'd expect, nothing major. I think this might be a random freeze, although i'm not very sure about that. Any ideas from your side?

**Comment by camsaul** [comment]
@Varunram are you still seeing this issue on the latest version of Metabase?

**Comment by flamber** [comment]
Closing, since no reply. Without the browser console log, it's hard to tell, but it sounds similar to #10247, which was fixed in 0.33.1
