### ISSUE TITLE
Drag-to-filter chart doesn't seem to work on master

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5272]
JS error:

![screen shot 2017-06-05 at 10 14 31 am](https://cloud.githubusercontent.com/assets/2223916/26794753/d8042eb8-49d7-11e7-8460-d15091419810.png)

**Comment by sabino** [comment]
Not only on master. I've just updated to 0.24.2 from the release-0.24.2 branch (which after the update shows as 0.25-snapshot) and I'm having the same problem.
