### ISSUE TITLE
Trying to open Logs from the dropdown menu doesn't work

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5273]
On master on Chrome.

JS errors:

![screen shot 2017-06-05 at 10 17 38 am](https://cloud.githubusercontent.com/assets/2223916/26794876/4515d790-49d8-11e7-9c11-8d752274dca4.png)

**Comment by Varunram** [comment]
@mazameli Can confirm on Safari too. I'll try to look into it

**Comment by Varunram** [comment]
Okay, I tried to take a dig at it, but the only example of `response.json` in use was in `seq.js` as `response.json({ status: 'error', message: err.message });` , that too as a comment.
