### ISSUE TITLE
Impossible to change visualization after clicking on the title (drill-through with filters) of a line card in dashboards

### ISSUE THREAD

**Issue by Digma** [metabase/metabase#5278]
## Bug

Seems line #5208 fixed the previous issue (https://github.com/metabase/metabase/issues/5221) but created (highlighted?) a new one.

When clicking on the title of a "line" card, it redirects properly to the query builder with filters but it displays the card as a "raw table". Furthermore it is impossible to change it back to "line" without editing the query

Clicking on the title of this query in the dashboard:

<img width="627" alt="screen shot 2017-06-01 at 16 46 34" src="https://cloud.githubusercontent.com/assets/3279847/26823277/5645a736-4aad-11e7-888c-2747e25b8432.png">

Produces this in the query builder and it is not possible to change the visualization back to line without editing first the query:

<img width="834" alt="screen shot 2017-06-01 at 16 46 41" src="https://cloud.githubusercontent.com/assets/3279847/26823287/5c4b19f4-4aad-11e7-86d1-ec37c7cce0a8.png">

## Step to reproduce

1. Create a card a pick "Line" as visualization
2. Add that card to a dashboard
3. Add a filter to the dashboard and link it to the card
4. Load the dashboard, when clicking on the title of the card, the query builder will open the query as a raw table. Changing the visualization type does not work

## Info

Your browser and the version: Chrome 58.0
Your operating system: OS X
Your databases: Bug reproduced with both MySQL & Druid data
Metabase version: 0.24.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by attekei** [comment]
Thanks for the report @Digma! I was able to reproduce the issue easily for line/bar/area visualizations (other visualizations seem to function correctly). 

When clicking a title of line/bar/area dashcard with a dashboard filter applied, the `visualization_settings` property of card object is completely lost. That leads to an error in `updateVisualizationSettings` when changing the visualization type.

**Comment by attekei** [comment]
Fixed by #5544
