### ISSUE TITLE
[bug] Loss of navigation on smaller screen sizes

### ISSUE THREAD

**Issue by nkconnor** [metabase/metabase#5279]
Since the dashboard refactor it is impossible to navigate on smaller screen sizes, including phones and most mobile devices. The navbar items are hidden by default and have 

```
@media screen and (--breakpoint-min-sm) {
	  .sm-show { display: inherit !important; }
}
```

A potential fix is adding a `.xs-show` and at least including links to Dashboards and Questions for smaller devices.

**Comment by kdoh** [comment]
@nkconnor For context can you add a bit of information on what type of device you're running into this on?

**Comment by nkconnor** [comment]
All devices. The navbar items are hidden at any screen size below `--breakpoint-min-sm`
