### ISSUE TITLE
0.24.2 is not the latest version on docker

### ISSUE THREAD

**Issue by benjR** [metabase/metabase#5280]
Hi,

I'm regularly pulling the latest version on docker (metabase/metabase:latest) and got the 0.24.1 installed instead of the 0.24.2.

Maybe something you can automate when releasing a new version ? For each version it seems that when you release there are a couple of hours/days before it gets upgraded on docker side.

Thanks!
Benjamin

**Comment by salsakran** [comment]
This should be sorted now.
