### ISSUE TITLE
impossible to create a graphic with Analytics Data

### ISSUE THREAD

**Issue by LauraSom** [metabase/metabase#5291]
![bildschirmfoto 2017-06-07 um 09 45 12](https://user-images.githubusercontent.com/28920848/26867785-072222aa-4b67-11e7-9067-d6de2f41453f.png)

It is impossible to create a graphic based on Google Analytics when there is a decimal number

**Comment by Pet3ris** [comment]
Can report the same issue using a number of metrics, e.g., avg. session duration, pages / session.

**Comment by flamber** [comment]
I cannot reproduce on `master` commit `af0a18e` (the upcoming 0.36.0) - unsure when it was fixed.
