### ISSUE TITLE
Filter in query builder does not contain all values in dropdown

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#5294]
Hi, 
The automatic dropdown options in the filter in the query builder do not contain all the values that are actually displayed in the data table. Hence not very useful as the filter can not be correctly applied (no option to list values manually). 
This also means that segments cannot be properly built.
Thanks for looking into it!

Your browser and the version: Version 58.0.3029.110 (64-bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: 24.2
Metabase hosting environment: Heroku

**Comment by mvrabel** [comment]
I resolved it by triggering the sync in the Admin Panel. It will take some time until it takes effect but it will sync eventually.

browser and the version: 58.0.3029.110 (64-bit)
operating system: Win 10
databases: Postgressql 9.6
Metabase version: v0.24.2 Built on 2017-06-01
Metabase hosting environment: CentOS 7

It's the same with changing tables. The sync takes some time

**Comment by mvrabel** [comment]
Hello again @HelenMertes.  When were these values that you dont see added ? When you have some values ABC, then added D and right after that opened metabase then it's normal that you dont see them. 
Please, correct me if that's not the case. 
If it is the case I would recommend to take a look at https://github.com/metabase/metabase/issues/5129 :)

**Comment by HelenMertes** [comment]
The database was synced a couple of times in the meantime, so this was probably not the reason.
In any case, it seems to be working now. 
Thanks

**Comment by salsakran** [comment]
The list of values in filters in the QB are based on the results of our sync (more specifically, our "analysis" or "value caching") process. 

We walk a fine line regarding how often to do this as it's fairly expensive to do. Do you have any more specifics @HelenMertes regarding when the field was introduced into the underlying dataset and when it was picked up in the query builder?

**Comment by Digma** [comment]
It seems like for some dimensions in Druid (not sure about BigQuery), some dimensions that have a large cardinality (1000+) have a list of values in the query builder. However that list only contains the first ~100 values in alphabetical order and all the other ones are not visible. Typing the name of a variable that is not part of these X first suggestion doesn't refresh the list and so it is not possible to select it.

**Comment by moumny** [comment]
Also for Druid at least, most columns (even cardinality is very low) were not detected. It seems the analysis is not working properly.

**Comment by moumny** [comment]
I see another problem with Druid, is for the Multi valued dimmensions (ie lists) where the dropdown shows the java toString of the object.

Is it possible to disable this feature ?

**Comment by moumny** [comment]
found the bug comes from 5323

**Comment by flamber** [comment]
Closing, since it was likely a sync issue, but without the logs, then it's hard to know.
