### ISSUE TITLE
Adittional JDBC connection string options for SQL Server (Azure)

### ISSUE THREAD

**Issue by Rodrigojg** [metabase/metabase#5296]
I need to configure a JDBC connection with specific configurations like encrypt=true;trustServerCertificate=false... In the GitHub #3765 was implemented the same configuration to Mysql Database. The implementation are needed to configure a best connection on SQL Server Azure. 
Thanks,

**Comment by marknightingale** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by cladjules** [comment]
Hi there,

we have the same issue there,

I think that post in kind of related.

http://discourse.metabase.com/t/cannot-open-a-sql-server-database-on-azure/1034

Thanks for your help.

**Comment by camsaul** [comment]
It's pretty easy to add this option for SQL Server so I can go ahead and add it so you can connect to your Azure DB

**Comment by camsaul** [comment]
@Rodrigojg @marknightingale @cladjules @hamishirving @dtwilliamsWork @HeathHopkins

I implemented this in PR #5491 (branch `allow-additional-options-for-sqlserver`). Can you guys try it out and let me know if it fixes your issue? As part of the fix I had to switch from the jTDS JDBC driver to the official Microsoft one so I don't want to make a change like that without verifying that it actually fixes something.

**Comment by cladjules** [comment]
Hi cam. Thanks for that. That's amazing.  We will give it a go this week
and let you know :)

**Comment by camsaul** [comment]
@cladjules awesome, thanks.

**Comment by camsaul** [comment]
We're cutting a release candidate for 0.25.0 so we won't be able to ship this as part of that (still need to hear back from people to make sure we don't break anything), but if we do hear back then I think we can ship it as part of 0.25.1

**Comment by cladjules** [comment]
Hi @camsaul ,

no worries.

We have just run some test today and looks like we can now connect to our database successfully :)

We didn't need to specify any additional parameter, looks like the JDBC driver has handled it for us.

Thanks for your help,

**Comment by camsaul** [comment]
@cladjules awesome!

@salsakran looks like the switch fixes at least one issue

**Comment by camsaul** [comment]
Fixed/Implemented by #5491
