### ISSUE TITLE
Pie chart problem with values equal to zero

### ISSUE THREAD

**Issue by regenerat85** [metabase/metabase#5300]
Hi,

We have a Dashboard with a few pie charts to show the number of incidents created on the current day grouping them by their status. We use the following query 

`SELECT SUM(CASE WHEN (Product='XXXXX' AND TO_CHAR(PROB_FEC_ALTA, 'YYYY-MM-DD') = TO_CHAR(sysdate, 'YYYY-MM-DD')) THEN 1 ELSE 0 END) AS Incidents, TESTADO.EST_DES_EN AS Status
FROM ADMIN_HELPDESK.TPROBLEMA INNER JOIN ADMIN_HELPDESK.TESTADO ON TPROBLEMA.PROB_EST_ID=ADMIN_HELPDESK.TESTADO.EST_ID
GROUP BY TESTADO.EST_DES_EN
ORDER BY TESTADO.EST_DES_EN ASC`

Why do we use a case statement instead of just performing a count and grouping the results by their status? Because that's the only way we have to consolidate the colors of the legend within the dashboard. As long as we have one pie chart for each of our products, we need them to show the same colour for each of the possible status. As you would know, there's no way to assign them manually on a pie chart, so the only way we could thought of to achieve this was to perform a case statement and return all the possible status even if their count for the current moment is zero, so we could order by this field and have the same colours over the different cards.This problem, we noticed when switching from version 0.23.1 to 0.24.1, arises when any of those pie charts have 0 results for each of the possible status.

In that moment, and until any of the possible status returns a result, it will keep on spinning and won't show anything at all. Here's an example, the result in table mode (on the left) and the attempt of showing it in a pie chart (on the right):

![image](https://user-images.githubusercontent.com/29280336/26934334-5bbffd70-4c69-11e7-9a06-fb0ba3ded7b4.png)

Has anyone noticed this behaviour? 

Just to add more info about it, when this problem affects one of a Dashboard's cards, all the other cards at the same level (position in the dashboard) or below the one with this problem won't render too. They will all keep on spinning until the card with this problem returns a result. Until that moment, This Dashboard's edit mode is faulty. You can drag cards but it won't allow you to drop , resize or perform any change at all on them.

Hope this help to clear out what's wrong with it.

Thanks in advance!

P.S. You can reproduce it easily on the Sample Dataset with the following query:

`SELECT Category, SUM( Case WHEN Rating > '5' THEN 1 ELSE 0 END)
FROM PRODUCTS
GROUP BY CATEGORY`

browser and the version: Chrome 58.0.3029.110 (64-bit) (Also FF and IE11)
operating system: Win 7
databases: Oracle (Also H2 - Sample Dataset)
Metabase version: v0.24.1
Metabase hosting environment: Ubuntu 16.04.2 LTS
Metabase internal database: MySQL

**Comment by salsakran** [comment]
reproduced. thanks so much for the sql query against the sample dataset!

**Comment by regenerat85** [comment]
Hi guys!

I wonder if you have any news regarding this bug. For us, it's not a big deal to have those cards without results showing the "loading" spinning symbol until they have something to return, but it's quite annoying the fact that all the cards below the one with this problem won't render too (Even though they have results):

![image](https://user-images.githubusercontent.com/29280336/33709970-675c1258-db3f-11e7-9343-3861b1ae85c0.png)

This means that most of the days, half of the dashboard will remain empty. (Two of our products may not have incidents for days)

Let me know if there's anything I can do or provide to help with this bug.
Thanks in advance!

P.S. This keeps happening in v0.27.1.

**Comment by gitnik** [comment]
Is there any update on this?

**Comment by gitnik** [comment]
Some more info: When you return multiple rows with a value of `0` there are javascript errors being thrown 
<img width="1438" alt="screen shot 2018-01-25 at 09 18 53" src="https://user-images.githubusercontent.com/996623/35377810-e5151d9c-01b0-11e8-909f-3c314cf5ac00.png">

**Comment by jornh** [comment]
I dug a bit into this one. I believe the front end code in 

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/visualizations/PieChart.jsx#L150 

will end in a division by zero due to `total` calculated a few lines above. Guess the solution will simply be to add a guard and render something different (a warning).

@gitnik (or anyone else interested) I see on your GH profile you do JavaScript- maybe enough for you to run with? I’m not really one that fancy pie charts myself so don’t plan to dig any further on this one myself 😉

**Comment by gitnik** [comment]
@jornh I should be able to have a pull request up by the end of this week 😃

**Comment by gitnik** [comment]
OK so much for that... Sorry guys, will try to get it done this week
