### ISSUE TITLE
Cannot delete cards from Dashboard in edit modus

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#5301]
When trying to edit a dashboard it is not always possible to delete existing questions by clicking on the "x" in the top right corner. It works sometimes, but I cannot figure out what causes it not to work, and I guess it would work easily and in any case.
Thanks for looking into this!

Your browser and the version: Version 58.0.3029.110 (64-bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: 24.2
Metabase hosting environment: Heroku

**Comment by mazameli** [comment]
Hmm, do you see any javascript console errors in your web browser when you click on the X? You didn't state this explicitly, but it looks like you're using Chrome based on the version number you provided.

**Comment by HelenMertes** [comment]
Sorry, yes it's Chrome indeed.
No I don't see any errors (you meant in the javascript console)?

**Comment by HelenMertes** [comment]
Hi, 
I keep having this problem, I basically am not able to edit the dashboard - it is not possible to change the settings of a card on the dashboard, add another question or anything else. 
This is the case using Chrome as well as with Firefox. 
Any ideas how to solve this? 
Thanks a lot!

**Comment by notrom** [comment]
This seems to be the same as #2187 which has been an issue for me on and off for a while now. There's a work around listed in that issue that you can use via the javascript console but it's time consuming.

It's very frustrating. So far I find that at least one of Chrome, Firefox or IE will let me use the settings and delete button at any time so I can work around it, but it is annoying to have to try 3 browsers just to be able top click a single button!

Chrome, Windows, Metabase v0.30.3

**Comment by mazameli** [comment]
This should be fixed by #10206 in version 0.32.10 or later (current latest is v0.33.3), so I'm going to close this, but please let us know if you're still experiencing it.
