### ISSUE TITLE
Shorter auto-refresh interval, or another way to view live data

### ISSUE THREAD

**Issue by josteinaj** [metabase/metabase#5303]
For live data / data that is updated very frequently, to answer questions such as "how many visitors are on my website right now", it could be useful to have a lower interval for the autorefresh. Maybe 1 second.

Alternatively, some kind of "live-mode" where new data are streamed to the browser/dashboard.

**Comment by kdoh** [comment]
Hey there @josteinaj. If you're dealing with frequently updated data and you're confident your metabase server and database can handle the number of requests, you can add a custom refresh interval in the URL to get a more frequent refresh than what we provide in the dropdown. 

`dashboard/<your-dash-id>#refresh=<your-custom-interval>`

There's a bit more context in #4299 about why we're currently not adding intervals below one minute to the dropdown itself. Hopefully this URL work around will let you get what you want until we support a live mode like the kind you alluded to.

**Comment by josteinaj** [comment]
Thanks!
