### ISSUE TITLE
Duplicate columns should have nicer aliases

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5307]
From a Slack discussion between me and @senior.

Right now if we have two columns with the same identifier, e.g. `name`, the Clojure JDBC library "helpfully" suffixes duplicates so we'll have `name` and `name_2`. It would be better if we just handled this ourselves where possible so we could give them more informative aliases, e.g. `venue_name` and `category_name`. This would be 100% under-the-hood so no UI changes.

However we need to consider UX implementations. We might get complaints about us changing MB’s behavior, e.g.

> why are the columns in my CSV different in 25 from 24?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by wrjohnston** [comment]
This is similar to issue I opened awhile back relating to being able to add an alias to a column.

 Multiple measures in a query; column alias SUM and SUM2; unable to sort #4810
