### ISSUE TITLE
Support unicode parameter names -- all non-ASCII characters are converted to `_` when slugifying

### ISSUE THREAD

**Issue by eudj1n** [metabase/metabase#5313]
Good day, if I try to share (or to embed) my dashboard which has filters with not english letters (in my case - it's russian), I can't correct set and use this params in my code.

Parameters toolbar:

<img width="392" alt="2017-06-12 19 52 31" src="https://user-images.githubusercontent.com/195489/27037176-f521b444-4fa8-11e7-9672-8a4d8cf194a3.png">

Code snippet:

<img width="1021" alt="2017-06-12 19 52 47" src="https://user-images.githubusercontent.com/195489/27037174-f006eb5a-4fa8-11e7-8a09-e47b71950eb5.png">

First parameter name has been replaced by multiple underscore "_" chars. In frame, url looks like this:

<img width="906" alt="2017-06-12 20 00 20" src="https://user-images.githubusercontent.com/195489/27037455-da4baef8-4fa9-11e7-8581-cbd9c66fff4e.png">

- Your databases: MySQL
- Metabase version: 0.24.2
- Metabase internal database: H2

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
It seems like the code we added in #4258 could be used here too perhaps to help fix this issue

**Comment by flamber** [comment]
Notice that the URL converts the filter as `...?__=value`, so multiple filters will all be the same (`__`) if they're the same length, which is common for Chinese.
**Workaround** is to add an unique ASCII character to each filter. Example:
If your filter is called `類型`, then name it `類型:1` - if you have another filter, then name it `...:2`

**Comment by sunui** [comment]
We can use https://github.com/jeremys/uslug  replace `slugify` function in  `frontend/src/metabase/lib/formatting.js ` to solve this problem.

**Comment by camsaul** [comment]
Now that I think about this, I don't think there's any reason we need to be slugifying parameter names in the first place? Normally they're passed in in the JSON body of a POST request when running an individual query. For dashboards AFAIK they *are* passed in as query parameters, but URL-escaping them should be sufficient; we should be able to keep the original non-ASCII name

**Comment by lewiscowleschipuk** [comment]
Is this closed delivered, or closed, will not be fixed?

**Comment by flamber** [comment]
@lewiscowleschipuk It's part of release 0.36.5
