### ISSUE TITLE
Automatic switching between dashboards (carousel)

### ISSUE THREAD

**Issue by josteinaj** [metabase/metabase#5314]
I would like it if there was a way to set up multiple dashboards to be displayed in a carousel-like manner.

**Comment by alee792** [comment]
Would also love this feature. I created a quick and dirty static web page to cycle through embedded iframes of dashboards/questions, but would love this as a native feature.

**Comment by jornh** [comment]
Sounds like a duplicate of https://github.com/metabase/metabase/issues/4468 to me.

**Comment by josteinaj** [comment]
Yes, it's a duplicate. Didn't see that issue when I created this one.
