### ISSUE TITLE
Metrics should have unique names enforced

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5315]
Especially as we head towards implementing multi-metric queries from different source tables, it seems to me that we should ensure that all saved metrics have unique names (e.g., it would be bad if you had a flat list of metrics where a few of them were called "Count of Rows" or something dumb like that). 

I think all this would require to implement would be a check on save/update to make sure there isn't another metric with the same name. If we wanted to get fancy, we could do a delayed on-key-up event, sort of like when you're signing up for Twitter or whatever and it lets you know if that username is available (I think that we would just say nothing if the name is okay, but put a message below the input box if the name is taken — `There is already a metric with that name`).

Should this also be the case with segments?

**Comment by brunobergher** [comment]
Not relevant with the new setup.
