### ISSUE TITLE
[docs] link in docs broken

### ISSUE THREAD

**Issue by morenoh149** [metabase/metabase#5318]
at the bottom of http://www.metabase.com/docs/latest/users-guide/12-data-model-reference.html link 'how to use variables in your native SQL queries' is broken.

**Comment by mazameli** [comment]
This was fixed by #5186, so it's fixed in master but won't take effect on the website until the next release unfortunately.

**Comment by mazameli** [comment]
Here's the correct link: http://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html
