### ISSUE TITLE
Better UX for required missing parameters on dashboards

### ISSUE THREAD

**Issue by VasekPurchart** [metabase/metabase#5320]
### Feature requests and proposals

If there is a question with a required parameter without default value, every time when you add it to a dashboard, then you will see `There was a problem displaying this chart.`. From a technical point this is clear (and correct), but I think this would appreciate some UX improvement towards the user.

This will commonly happen if the dashboard is a parametrized report - meaning it is used for seeing information about a single user fro example, so it makes no sense to either fill in a default or make it optional. 

This is kind of how it currently looks when executing the question, you will see `'User ID' is a required param.` and I think it would be much more clear if something like this showed up in the dashboard as well. Of course this is more complex, since then there are filters involved, but I think this can be handled in two stages:

1. If the missing parameter is already mapped to a filter, change it to `'<filter>' is a required.` and possibly mark the filter input, so that user sees it clearly. This would work especially well if all the reports need this parameter. But of course it will not always be like that, so maybe the card should be grayed out like if you are using an unmapped filter?

2. If the parameter is unmapped, then the error can stay like `'<param>' is a required param.`, because this would usually suggest that the question/dashboard is wrongly configured, so something someone who understands all the underlying concepts needs to change. This should basically show up, when you are setting up new questions/dashboards and guide you in case you overlooked something somewhere.

What do you think about this? I hope these changes should be quite minimal (since most of the stuff is already somewhere there) and could have nice impact on the UX. (started using metabase today and this threw me off several times when I was trying to figure out the parameter+sql specifics).

Btw I am running on `0.24.2` (in case this is already changes somewhere, but haven't found anything).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Great feedback! Thanks for taking the time to write this out.

> If the missing parameter is already mapped to a filter, change it to '<filter>' is a required. and possibly mark the filter input, so that user sees it clearly. This would work especially well if all the reports need this parameter. But of course it will not always be like that, so maybe the card should be grayed out like if you are using an unmapped filter?

I think we could just leave it at showing the message, `Select a value for {filter name} to see this card`. The string would need to be dynamic to handle multiple required params, like: `Select a value for {filter1 name}, {filter2 name}, and {filter3 name} to see this card.`

> If the parameter is unmapped, then the error can stay like '<param>' is a required param., because this would usually suggest that the question/dashboard is wrongly configured, so something someone who understands all the underlying concepts needs to change. This should basically show up, when you are setting up new questions/dashboards and guide you in case you overlooked something somewhere.

I think if the card has any unmapped parameters, in all states on the dashboard it could say, `This card has a required parameter/has required parameters that need/s to be connected to a dashboard filter."

**Comment by VasekPurchart** [comment]
Thanks for reacting to this, both texts you suggest are clearly understandable, so 👍 .

Btw I realized one more advantage in handling this - it will be much more responsive, because the query should not run, when these situations are detected.

**Comment by oleggromov** [comment]
Will be fixed in [0.49](https://github.com/metabase/metabase/milestone/192).
