### ISSUE TITLE
FieldValues does not check for cardinality (cannot select value not listed)

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#5323]
In dashboards with category widget, the field/id/values call fills the database with 300values regardless of the cardinality of the column (cardinality is only checked in analysis).

This make the column unusable since you cannot enter a different value from the top 300.

**Steps to reproduce**

1. Open data model of sample dataset
2. Change the userID column in Orders to category
3. New question -> sample dataset -> save question(raw data is fine) -> add to dashboard
4. add categoryWidget in dashbord and bind to the userID of the the previous question
5. Save and refresh the page
6. You can now see you have a dropdown of userIDs (300 of them) even if there are 1700

**Comment by mazameli** [comment]
Related to, or perhaps the same issue as this one I think: https://github.com/metabase/metabase/issues/5150

**Comment by moumny** [comment]
Oh yeah, correct, I did even comment on those...
I think it's quite a serious bug, might be worth 0.24.3 with a patch disabling the feature in the meantime. WDYT?

**Comment by camsaul** [comment]
This was resolved by #5510. FieldValues won't get saved if cardinality is over the limit regardless of how it is triggered (old code only checked cardinality during sync but not if you manually set a category)

**Comment by mazameli** [comment]
@salsakran you reopened this one a while back after the fix was implemented. Would you like to keep it open or can we call this resolved?

**Comment by mazameli** [comment]
We haven't heard any users reporting that this problem has persisted since #5510 was merged. I motion that we close this issue.
