### ISSUE TITLE
Unable to add more fields to query

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5325]
An edge case which you might not encounter 99.9% of the time. Its very difficult to add another query column to this.
<img width="1234" alt="screen shot 2017-06-07 at 9 10 00 pm" src="https://user-images.githubusercontent.com/18598959/27100255-0923bd82-509b-11e7-92f5-1568aefb71ab.png">

Moreover, if we keep adding more queries, the + seems fixated at that position and overlaps with the fields themselves. @mazameli Any suggestions? Thanks!

**Comment by tschut** [comment]
I wouldn't consider this an edge case, depending on your screen size and what you're doing with your data it's quite easy to run into this. Workaround is to adjust the browser zoom level but this quickly makes stuff unreadable.

**Comment by flamber** [comment]
Many things has been fixed with the new query browser since 0.33:
![image](https://user-images.githubusercontent.com/1447303/82742585-7dba3d00-9d60-11ea-98ba-47ce2c11f53c.png)
