### ISSUE TITLE
Logs become impossible to read because of auto scrolling

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#5329]
I am unable to read logs because the cursor keeps moving as new logs come in. 

When the user scrolls to the bottom, the logs should be refreshed but if they scroll up, the logs should not move up (Similar to the behaviour of the tail command).

**Comment by mazameli** [comment]
This is fixed in master. Server logs are now available at `/admin/troubleshooting/logs`, and do not scroll as they're updated.
