### ISSUE TITLE
Fonts and charts can look bad in all browsers except Chrome

### ISSUE THREAD

**Issue by dtheodor** [metabase/metabase#5330]
I was testing Metabase 0.24.2 with firefox, and I realized it didn't look as pretty as when I was working on Chrome. I proceeded to test it with different browsers to find out that the results are not ideal

Chrome output is perfect

![chrome](https://user-images.githubusercontent.com/1549648/27137045-883afd4e-5125-11e7-9496-ca67865ad5f6.png)

Firefox fonts in legends, chart titles, and filters look awful, a chart is resized within its surrounding frame so that a part of it is not visible

![firefox](https://user-images.githubusercontent.com/1549648/27137079-a3663192-5125-11e7-8b06-9f5103fae949.png)

Edge, almost identical to firefox

![edge](https://user-images.githubusercontent.com/1549648/27137128-c8da17a4-5125-11e7-98fb-4a44dc873b26.png)

IE11, charts have no resize issues, fonts have the same issues, the filter text is not centered

![ie](https://user-images.githubusercontent.com/1549648/27137171-e7d1b180-5125-11e7-9a96-571fa1828f03.png)

I've tried this on a windows 10 machine and on an ubuntu trusty with the same results. I think this is not a problem with my system's fonts although I didn't go much into system fonts and how/if they should affect browsers

**Comment by kdoh** [comment]
This should be fixed by #6154.
