### ISSUE TITLE
Don't change parameter values when leaving edit dashboard mode

### ISSUE THREAD

**Issue by VasekPurchart** [metabase/metabase#5332]
### Feature requests and proposals

I am not sure if this is a regression or just an oversight (I am on `0.24.2`), but when leaving the dashboard edit mode, the parameters get changed, which is quite annoying, because when you are setting multiple boards/cards you have to fill in all the values all the time.

When you leave the edit mode either with `save` or `cancel`, then filters without default values are removed completely and filters with default value are reset to this value. This is probably due to removing the parameters from the URL, but they are there in the edit mode, they disappear only when leaving it.

With `cancel` this was a little bit more unpredictable, sometimes the value without a default would stay filled in, haven't found the reason behind the difference in the behavior.

This might have been partly intentional, because when saving the dashboard, the parameters could have changed, so removing them might be ensuring, there are not filled in any incompatible values, but if this is the case and it is really needed, then this should not be the case for `cancel` and with `save` I think a change of type of the particular filter should be detected first before removing it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Ah, yeah, that _is_ annoying. I don't know that this is a bug, per se, but it is an annoying behavior. 

Steps to reproduce:
- Make some selections for your dashboard filters.
- Enter into dashboard edit mode.
- Hit `save` or `cancel`
- All the filter value selections you've made are cleared out. Filters with default values get reset to their defaults.

**Comment by andreychirikba** [comment]
The consequence is, the dashboard ends up in an inconsistent state: the filters display their default values, but the newly added question on the dashboard doesn't have those filters applied. I've added a screen recording in #13607 to illustrate that. So it looks like a bug to me.
