### ISSUE TITLE
Input filter boxes on public dashboards rendering incorrectly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5335]
After putting in a value:

![screen shot 2017-06-14 at 5 12 38 pm](https://user-images.githubusercontent.com/2223916/27159847-e0ac63ba-5124-11e7-8d89-01f7b0cd5133.png)

After clearing out the value:

![screen shot 2017-06-14 at 5 13 09 pm](https://user-images.githubusercontent.com/2223916/27159850-e6c429c2-5124-11e7-9f56-35d8cc873ca0.png)

**Comment by Varunram** [comment]
Weird, I'll take a shot at fixing. Any things you'd want to watch out for? @mazameli

**Comment by mazameli** [comment]
This appears to only be happening now on Safari (Version 10.1.1). I think after reporting this issue, I updated Chrome from 58 to 59, so it's possible this is still present on Chrome 58. Not present on Firefox.
