### ISSUE TITLE
Attempting to download data from a public card results in a 404

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5336]
Specifically, if you use the download icon in the bottom right of the public card.

Public links that go directly to the CSV, JSON etc. file work fine.

**Comment by Varunram** [comment]
@mazameli I tried the links and as correctly stated by you, the CSV, JSON, etc links work fine. I don't quite get what you mean by this though:
> Specifically, if you use the download icon in the bottom right of the public card.

Would help if you elaborated a bit. Thanks!

**Comment by kdoh** [comment]
I can't seem to reproduce this. When on a public question clicking the download icon in the bottom right pops up the download options and each one of the buttons for the different formats works as I'd expect.

**Comment by mazameli** [comment]
I just reproduced it in both Chrome and Safari on master. Make sure you're using an incognito window or in a browser where you're not logged in.

**Comment by kdoh** [comment]
Ah! I should have probably guessed that but being sure to specify stuff like that in the issue itself is always helpful in debugging.
