### ISSUE TITLE
Common Sharing for all questions in a dashboard

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5337]
When creating a set of 10 dashboards or so with lets say 10 questions each, it becomes painful to click each individual question and enable public sharing. It would be amazing if we could have some sort of common filter to handle these types of situations. But the question remains as to how we would go about implementing this. Any ideas?

**Comment by salsakran** [comment]
Why not just share the dashboards themselves?

**Comment by mazameli** [comment]
Yeah, I'm not sure I understand the use-case here, @Varunram, given that we have the ability already to publicly share entire dashboards. Can you elaborate?

**Comment by mbvictoria** [comment]
Closing - no comments/updates since 2017.
