### ISSUE TITLE
Embed dashboard does not display Map charts

### ISSUE THREAD

**Issue by becca0330** [metabase/metabase#5338]
- Your browser and the version: Chrome  58.0.3029.110 & safari 10.10.1
- Your operating system: OS X 10.10.5
- Your databases: Oracle
- Metabase version: 0.23.1
- Metabase hosting environment: CentOS 6
- Metabase internal database: MySQL

My map charts shows correctly on the dashboard, however if I **embed** the dashboard to my own site it keeps loading and never get the map shown. (Other chart types works fine, and also if I change to use public iframe, it works, too. Only the "**embeded**" one didn't. )

Please see the attached images.

The correct map chart on the metabase dashboard:
![map_on_dashboard_is_displayed](https://user-images.githubusercontent.com/1653403/27168937-614c2dd8-51da-11e7-839d-643874401a0e.png)

The keep-loading map chart on the **embeded** dashboard:
![map_on_embeded_dashboard_is_not_displayed](https://user-images.githubusercontent.com/1653403/27168949-67c983b8-51da-11e7-8ef4-46b305775add.png)

Error I got from chrome developer tools
<img width="1098" alt="chrom_developer_tools_message" src="https://user-images.githubusercontent.com/1653403/27169322-f62c03f0-51db-11e7-80fb-f7dfceff5d95.png">

> GET http://my.site.com/api/user/current 401 (Unauthorized)
> GET http://my.site.com/api/geojson/622ed923-9686-5ff7-f1a2-6f40af4d1026 401 (Unauthorized)

Could anyone help me with this or give some hint?

**Comment by becca0330** [comment]
I found that if I login the metabase site, the embeded dashboard on the other site shows the map chart correctly. If I logout the metabase site, then the map chart on the other site is gone ( the other charts are still fine).

**Comment by ralexsander** [comment]
Exactly same problem here. @becca0330 you was able to find a workaround without requiring user to log in metabase?

**Comment by ShayChris** [comment]
Can I ask you how do you add china map?I add a geojson url but it isn't work

**Comment by mariomka** [comment]
Same issue here. Any workaround?

**Comment by MarcGJA** [comment]
Thanks @mazameli, I absolutely agree on closing this up as a duplicate and was about to do so myself.  What I'll do instead is note in <a href="https://github.com/metabase/metabase/issues/5338"> Issue #5338</a> that GeoJsons do in fact resolve in vintage FireFox 52.9.0 albeit with "peek-a-boo" labels.  Perhaps that little nugget of information will help diagnose what's going on.

Between multiple <a href="http://discourse.metabase.com/t/filter-search/5082/4">Filter Search</a> issues, the unavailability of Metabase's <a href="http://discourse.metabase.com/t/metabase-fails-w-elastic-beanstalk-mysql/5077">MySQL Option</a> for AWS EB, <a href="https://github.com/metabase/metabase/issues/8111">Embed URL Security</a> concerns, and the exceedingly steep learning curves associated with AWS, PHP, SQLs of every stripe, and a plethora of other technologies I feel rather like Jack-and-the-Elastic-Beanstalk!

**Comment by becca0330** [comment]
@ShayChris 

if you haven't found one for the china geojson, this url should works:
https://raw.githubusercontent.com/longwosion/geojson-map-china/master/china.json

**Comment by becca0330** [comment]
A "very ugly and not secured" workaround for those who really need to embed the map....

Since I guess this is an authentication issue ( error I got from chrome developer tools says "Unauthorized"), I try to load the page as a metabase logged user in the background by calling metabase api ( your-metabase-url/api/session ) and setting cookie and session, then the embedded map is displayed.  

Again, there is strong security risk by doing so, if your application is not for internal use, I don't recommend you to do this way.

**Comment by ricardobaehr** [comment]
any perspective?

I'm evaluating the metabase to use with whitelabel and show the maps without authentication is essential :/

**Comment by MarcGJA** [comment]
@ricardobaehr Check this post comment out if you haven't already, <a href="https://github.com/metabase/metabase/issues/6593#issuecomment-353636687">#6593</a>.  Evidently the auth issue can be cleared up by changing one line of clj code.  Haven't tried it myself yet, I have to learn how to use Docker first to get it on AWS.  But it sounds doable.

**Comment by camsaul** [comment]
Duplicate of #5338

**Comment by camsaul** [comment]
Easy fix

**Comment by atranel** [comment]
Easy fix for bug preventing people not-logged in Metabase to see custom maps. In the metabase/api/routes.clj file

(context "/geojson" [] (+auth geojson/routes))

JavaScript

change to

(context "/geojson" [] geojson/routes)

**Comment by camsaul** [comment]
Fixed by #9807

**Comment by camsaul** [comment]
Hi everyone, this is fixed in Metabase 0.32.5 which has just been released.
