### ISSUE TITLE
Ability to hide US/World maps

### ISSUE THREAD

**Issue by josteinaj** [metabase/metabase#5340]
A simple enable/disable checkbox under the Settings > Maps menu for hiding the built-in US/World maps would be great.

see also: https://github.com/metabase/metabase/issues/2740#issuecomment-241582727

**Comment by camsaul** [comment]
Hi @josteinaj, if you have some familiarity with React/Redux and want to submit a PR to support this we would happily consider it 👍

**Comment by paoliniluis** [comment]
[MB_CUSTOM_GEOJSON_ENABLED](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_custom_geojson_enabled)
