### ISSUE TITLE
Create Question : bug when using field filter and others filters like date

### ISSUE THREAD

**Issue by seblurtz** [metabase/metabase#5341]
Your browser and the version: Chrome 58.0.3029.110
Your operating system: Windows 7
Your databases: sample one & sql server
Metabase version: 0.24.2
Metabase hosting environment: Windows server 2012 via metabase.jar command

Hello, your product is really cool. There is just an annoying bug when using field filter and others fields like date : all filters take the field list values ! Sometimes it occurs on dates even if i delete the field filter after...

Here is a screen of the problem : 
![image](https://user-images.githubusercontent.com/5920177/27187113-9c4c25cc-51ea-11e7-953f-eb32d678c6ea.png)

As you can see on the right, the 2 parameters are well configured but the 2 filters contains the field list values even the date filter !

here is the request used to reproduce this problem : 
SELECT * from Products where 1=1
[[and {{Category}}]]
[[and CREATED_AT > {{mydateChustom}}]]

Thank you in advance.

**Comment by salsakran** [comment]
That's strange. can you screenshot the right side panel scrolled down so we can see the definition of `mydateChustom` ?

**Comment by seblurtz** [comment]
All is in the screenshot, mydateCustom is simply a date, nothing more.
I didn't access the application in few days, and the problem was gone when i use it as read. 
The problem occurs again if i configure it again : 
1) copy/paste the query
2) i configure the field filter to be Category from product
3) then define mydateChustom as a date 
--> the problem occurs again, the date filter displays the categories...

**Comment by seblurtz** [comment]
Another thing, the problem seems to occur when i access the screen from a dashboard.
- Access the screen From Dashboard link : bug occurs
- Refresh the page : F5, or retype the url --> it solves the problem

So it seems that maybe some javascript events are not trigger the same way.

**Comment by camsaul** [comment]
I don't know exactly when this got fixed, but I can confirm it is no longer happening. Screenshot attached.

![screen shot 2017-11-13 at 5 30 09 pm](https://user-images.githubusercontent.com/1455846/32758258-52075804-c898-11e7-8e57-3a5defeabf24.png)

@seblurtz thanks for the detailed steps to reproduce and please let us know if you run into any further issues.
