### ISSUE TITLE
Export feature is missing after upgrading to 24.1 and also after 24.2 update

### ISSUE THREAD

**Issue by ramcend** [metabase/metabase#5343]
After I updated my Metabase to 24.1, all my existing Questions are missing the export to CSV arrow until I choose a value for all the optional clauses, [[ AND {{platform}} ]], for example. I'm querying a MySQL database. The optional clauses are set as field filters - category widgets. The Questions were made using 'Switch to SQL'.

SELECT DATE_FORMAT(`report_files`.`date`, "%Y-%m-%d") AS `Date Uploaded`
, `report_files`.`platform` AS `Platform`
, `report_files`.`name` AS `Report Filename`
FROM `report_files` 
WHERE 1 = 1 
[[ AND {{platform}} ]]
[[ AND {{date_range}} ]] 
ORDER BY DATE_FORMAT(`report_files`.`date`, "%Y-%m-%d") DESC, `report_files`.`platform` ASC, `report_files`.`name` ASC

**Comment by salsakran** [comment]
What os, browser and browser versions are you on?

**Comment by attekei** [comment]
Strange as we fixed a similar issue in #5099 which is part of 0.24.2. I tried a similar query with two `[[ AND {{variable-name}} ]]` clauses next to each other and the download button appeared correctly and I was able to download the CSV. Are you @ramcend still experiencing the issue?

**Comment by gerbus** [comment]
Thanks @attekei. I also had this issue in 0.24.1. I'll confirm if it's resolved after we upgrade to 0.24.2 (this week).

**Comment by mazameli** [comment]
Are you still experiencing this issue, @gerbus?

**Comment by camsaul** [comment]
Since we're not able to reproduce this and haven't heard back in 3 months I'm going to go ahead and close this out. @gerbus if you run into any further issues please let us know.

**Comment by gerbus** [comment]
Sorry for dropping the ball. It was resolved in 0.24.2.
