### ISSUE TITLE
Multiple Series (Combine two questions)

### ISSUE THREAD

**Issue by KeviGitHub** [metabase/metabase#5344]
Hello!
 I have an issue concerning the multiple series charting. Indeed, I want to merge the chart of two questions into a single one (the commun axis is a time serie). But when I'm going into a Dashboard then click on "edit dashbord" and then on "add" in one of my saved question, I can't find other questions...it is written "Whoops, no compatible questions match your search"
![metabasediscussion](https://user-images.githubusercontent.com/29477650/27482318-42f540ac-5821-11e7-847e-6f4653642743.PNG)

- Browser and Version: Chrome 59.0.3071.86 
- Databases:  MySQL
- Metabase version: v0.24.2
- Metabase hosting environment: Ubuntu 16.04.2
- Metabase internal database:  H2 (default), MySQL

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
This happens when we can't find compatible questions with the same axis. Can you share the question you're adding a series to as well as the question you're trying to add? Anything that would tell us the exact column types you're working with on the y and x axis in the two cards.

**Comment by ihr** [comment]
In my case, I use:
- MacOS Metabase 0.25.2 
- MongoDB v3.4.7

Both charts are line charts and have X-axis Timeseries scale and Y-axis Linear scale. Could it be that the problem arises from the values of Linear scale? The max value of one of the axis is twice as small as the min value of the other axis.

**Comment by juliancesar** [comment]
I have the same problem, and i notice in my case when i use a dashboard filter, being that when i remove the filter everything is ok.

Maybe when i add a second chart the metabase need to show options for the filters.

**Comment by mpoornima** [comment]
I have a similar problem. My x-axis is time-series data and y-axis is a number, there are several other questions which match this filter with the same range of y-axis values & x-axis values and metabase is not showing any matching questions. All the questions have filters applied to them.

**Comment by tiwariayush** [comment]
Hi, I have been facing the same issue, given that x-axis and y-axis are exactly same for the 2 questions and there is not too much difference in the value (count of rows)
@salsakran : Here are the screenshots of the 2 questions I'm trying to add in multiple series:
![image](https://user-images.githubusercontent.com/5693204/71721385-1b9a8300-2e25-11ea-9adf-7b03ab691bcf.png)
![image](https://user-images.githubusercontent.com/5693204/71721400-26551800-2e25-11ea-9dc5-bcae1504328f.png)

**Comment by guicoelho** [comment]
Is there any solution to this? I have the same issue. Two previously saved questions with a Time axis and I can't display them together on a dashboard.

**Comment by ajcoll5** [comment]
Had the same issue on a TimescaleDB (PostgreSQL) table. Was able to workaround it by creating a summarize column in MB that took the max value grouped by the time/minute. That finally allowed me to add that question as a series to another question on a dashboard.

**Comment by ccasado-asac** [comment]
Hi, same problem here.
In my case, I think it has something to do with the custom expression I'm using to summarize.
I'm working on a dashboard with the same X-axis for all of his questions, with the same grouping for each one.

Let me put you an example of what I'm trying to say. Let's say we have two "types" of questions:
- A: Use Month as X-axis and a "Count" as Summarize with a gruping by Year and month.
- B: Use Month as X-axis and a Custom expression (Math operation) as Summarize with a gruping by Year and month.

Well the "B" type question don't appear in the list of availiable questions to combine.
If I add an "A" question, I can combine it with other "A" questions.
If I add a "B" question, I can combine it with "A" questions.

using **Metabase 0.35.3**

Please, let us know if you need further information for this issue

**Comment by AMorenoStratio** [comment]
This problem occurs when questions have variables. It is solved by modifying the questions to check that the variables are mandatory.

**Comment by luizarakaki** [comment]
Tried to repro this but I failed.

Tried with variables, different groupings. If someone has repro steps, I'll open this again.
