### ISSUE TITLE
Metric Revisions broken in master

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5356]
If you create a metric, even the base "revision" in `/reference/metrics/X/revisions` shows an empty aggregation.

![screen shot 2017-06-18 at 4 52 40 pm](https://user-images.githubusercontent.com/107439/27265227-95eebd6c-5446-11e7-8159-32e94a7f3f2f.png)

**Comment by attekei** [comment]
I was able to reproduce and if the metric contains a filter, it rendered incorrectly:
<img width="853" alt="screen shot 2017-07-17 at 16 22 51" src="https://user-images.githubusercontent.com/6034928/28294028-4b3e6772-6b0c-11e7-9c51-c65c69a20d79.png">

**Comment by flamber** [comment]
Cannot reproduce on 0.38.1
