### ISSUE TITLE
DashBoard Filters and variables in SQL queries

### ISSUE THREAD

**Issue by iLc02** [metabase/metabase#5360]
Your browser and the version: Chrome 59.0.3071.104, Firefox 54
Your operating system: Windows 10
Your databases: MySQL
Metabase version: 0.24.2
Metabase hosting environment: Docker
Metabase internal database: H2 (default)

Hello, There seems to be a bug with DashBoard Filters and variables in SQL queries : the dropdown menu does not show when sharing the dashboard.

I have a few queries (graphs) in which I use one variable. It is the same variable for all queries.
I put them on a dashboard on which I added a filter that connects to that variable. 

When creating / editing the dashboard, I can see a dropdown menu to select a specific value for the variable.

![image](https://user-images.githubusercontent.com/25204650/27306316-79fa786c-5545-11e7-8e6b-0a93ef70ac46.png)

However, when I share the dashboard there are two different cases.

1. If I open the dashboard on the same computer and on the same browser, the dropdown menu shows :
 
![image](https://user-images.githubusercontent.com/25204650/27306596-76571868-5546-11e7-88e1-aab6341ad3c7.png)
![image](https://user-images.githubusercontent.com/25204650/27306600-7c2ae92c-5546-11e7-841b-02b42de8bd27.png)

2. If I open the dashboard on a different computer and/or on a different browser on the same machine, the dropdown menu does not show. Instead I get a textbox, where I need to write the value by hand.

![image](https://user-images.githubusercontent.com/25204650/27306611-86fc3e1e-5546-11e7-991f-7be5b61bfe19.png)
![image](https://user-images.githubusercontent.com/25204650/27306612-8bcb35a8-5546-11e7-9487-087293efe548.png)

This somehow seems to be related to the user being logged in to the application or not.
If logged in, then you see the dropdown menu, otherwise you just see a textbox.

Thank you.

Pierre

**Comment by attekei** [comment]
Thanks for the detailed report! This was discussed in #5060 and I just a few days ago created a PR (#5349, still work in progress) which will solve the problem. 

As you described, confusingly everything works correctly if you are logged in, but for anyone else the category filter dropdown isn't shown at all.

**Comment by Siddarth434** [comment]
I get this error even now. I am using the version - 0.35.2
I get this error for a date variable - using sql. 
I am running the jar directly on a centos machine.

**Comment by flamber** [comment]
@Siddarth434 You're seeing a different problem, almost nothing works the same way as in 0.25. Latest release is 0.36.3. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by Siddarth434** [comment]
I am using 0.35.2. Not 0.25.
