### ISSUE TITLE
Sorting by column for query with native source query changes column order

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5379]
In some cases sorting by a column will cause that column to get displayed ahead of others in the results. It is intentional behavior from a while back but it might not make sense anymore. Consider removing the logic behind this behavior.

Should be a simple fix.

**Comment by camsaul** [comment]
Actually I was confused. We don't sort by columns just because they appear in an `order-by` clause. Something else must be at play here

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4 - and I haven't experienced this in earlier versions either, but a lot has changed the past 3 years.
