### ISSUE TITLE
Metabot often stops running 

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5380]
Still trying to find out a pattern to when/why, but Metabot on our own stats instance randomly stops running and starts up again. Seems to happen regardless of whether or not it's being interacted with. It happens every few minutes, and then seems to spin itself back up again after another few minutes. You'll often notice that the Metabot Slack user goes offline, and then doesn't respond to `metabot` commands:

<img width="547" alt="metabot in slack" src="https://user-images.githubusercontent.com/2223916/27409796-242a1b1e-5698-11e7-913c-2e0a808c8145.png">

#4056 seems to tangentially reference this issue, but I don't think it's strictly related.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by justin-yan** [comment]
This was happening to us frequently enough that we just had to disable metabot entirely due to the erraticness.  Observed in a Metabase 0.24.1 JAR deploy running on Ubuntu 14.04.

**Comment by mazameli** [comment]
Can anyone else from @metabase/core-developers verify if this is a bug or if it's a problem with Slack tokens or some such?

**Comment by nickstenning** [comment]
We're also seeing metabot (from Metabase v0.24.2 in Docker) having real trouble connecting to Slack, while running from inside EC2 in us-west-1:

```
Jul 13 15:51:09 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 15:58:04 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:00:23 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:02:42 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:05:01 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:07:20 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:11:58 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:14:13 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:16:28 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:18:45 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:21:04 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:23:24 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:25:43 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:28:02 ERROR metabase.metabot :: Error connecting websocket: Read timed out
Jul 13 16:30:21 ERROR metabase.metabot :: Error connecting websocket: Read timed out
```

**Comment by samhavens** [comment]
I am debugging the same issue now. I installed Metabase on AWS Elastic Beanstalk per the instructions as of 2018-02-13. My hypothesis is that Beanstalk ELB is listening for HTTP traffic?

**Comment by samhavens** [comment]
Changing the ELB Network configs to use TCP instead of HTTP(S) worked for me. Gonna submit a PR with an update to the docs.

**Comment by Esya** [comment]
We're using metabase behind an [ALB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html) and we experience the same issue. 

We only have HTTPS turned on, and stickiness disabled, it should work, as it is the setup we use for other applications that rely on websockets too.

**Comment by hdiass** [comment]
Are still facing the issue ? I'm running behind traefik but from times to times it get disconnected

**Comment by hdiass** [comment]
So i found the issue. Versions prior to v0.32.0 use lib aleph (which handles http stuff) in alpha version

**Comment by ChristineChetty11** [comment]
> So i found the issue. Versions prior to v0.32.0 use lib aleph (which handles http stuff) in alpha version

@hdiass Please let me know how you resolved this. I am pretty new to all this stuff and have been having issue of metabot disconnecting randomly, then not restarting unless I restart my server instance. Even if I disable in Admin and then enable again the Metabot does not come back online. 

Which steps should I take to replace the lib? Which lib should it be replaced with?

**Comment by cparaskeva** [comment]
Hello! Any updates on this one?

**Comment by paoliniluis** [comment]
Hi @cparaskeva! please post your issue in the Discourse forum so we can help you troubleshoot it
@ChristineChetty11, @hdiass, @Esya are you still having this issue?

Thanks!

**Comment by sickill** [comment]
I am experiencing this issue too. When I first enabled Slack integration + bot, the bot didn't respond at all for a while until it went online and started responding (hour later I think). It used to work fine for a day and now it went offline again and doesn't respond.

Note that pulses and query alerts work just fine, it's just the realtime websocket connection which is not reliable. 

I'm running Metabase with Docker on EC2, behind ALB.

**Comment by paoliniluis** [comment]
@sickill can you post the logs if you see any error? also if you can send all the specifics about the configuration it would be nice

**Comment by noahmoss** [comment]
Closing this as we are deprecating Metabot (and #19499 disables it for all instances in v42)
