### ISSUE TITLE
Filters with a list of values are not working

### ISSUE THREAD

**Issue by ObadaM** [metabase/metabase#5384]
### Bugs

- Browser and the version: Chrome 58
- operating system: OS X 10
- databases:  Postgres :x:
- Metabase version:  0.24.2
- Metabase hosting environment: Elastic Beanstalk

Now with the new version, we are not able to put a list of numbers or strings in the filter. 
like 123,321,132, ...etc. 

`select * from user
where id in (123,321,132)`

<img width="1400" alt="screen shot 2017-06-23 at 13 59 12" src="https://user-images.githubusercontent.com/5006984/27481305-3e5035fc-581c-11e7-9370-e9de26e4cedc.png">

is there any solution to run this query in the new version with a filter? 

## UPDATE: 
ENGINE: Postgres. 
database: Redshift

**Comment by ObadaM** [comment]
@camsaul could you please check this ticket. It's blocking our cards and we could not rollback to an older version. 
Any help from your side is appreciated.
Thanks in advance,

**Comment by salsakran** [comment]
This is a result of us locking down sql templates. Previously we allowed things like `1,2,3` to be substituted directly into templates, but as of 0.24, we are checking types and only allowing "Numbers" to be inserted into number fields. 

We will not be opening this back up. Is this widely used in your templates? Perhaps we can find a workaround.

**Comment by ObadaM** [comment]
Thanks for your reply! 

Actually, yes. We are using this in most of our questions. It would be great if we can find a workaround.

**Comment by rafaelveloso** [comment]
Quick workaround would be to define your variable as text and use a query similar to:

```sql
WITH params AS (
  SELECT ('{' || {{ids}} || '}')::text[] AS param
)
SELECT *
FROM users,
  params
WHERE id = ANY(param)
```

**Comment by ObadaM** [comment]
@rafaelveloso Thanks for your workaround. 
I am getting this error: 
`ERROR: cannot cast type text to character varying[]`

**Comment by rafaelveloso** [comment]
@ObadaM have a look at this practical example using `metabase`'s database.

<img width="1595" alt="screenshot 2017-07-11 11 46 38" src="https://user-images.githubusercontent.com/4039615/28064991-a7ce08c2-662e-11e7-9dc7-e26ca7a54655.png">

**Comment by ObadaM** [comment]
@rafaelveloso not working for me. 
<img width="1413" alt="screen shot 2017-07-11 at 13 49 32" src="https://user-images.githubusercontent.com/5006984/28067078-f6ffcfd2-663f-11e7-8625-1fb2d914b132.png">
<img width="1421" alt="screen shot 2017-07-11 at 13 49 57" src="https://user-images.githubusercontent.com/5006984/28067079-f702a7c0-663f-11e7-9bb7-1b139263fc28.png">
I cannot cast to array.

**Comment by rafaelveloso** [comment]
Oh, I see. Redshift does not provide support for `array`. It does support `json` arrays though.
I don't have means to test it on a redshift cluster right now but you'll probably have to play around with `JSON_EXTRACT_ARRAY_ELEMENT_TEXT` and `JSON_ARRAY_LENGTH` redshift functions.

I believe something along the lines of the following meta-code for the previous example would work:

```sql
WITH exploded_array AS (
  SELECT JSON_EXTRACT_ARRAY_ELEMENT_TEXT(('[' || {{ids}} || ']')::json, seq.i) AS id
  FROM seq_0_to_10 AS seq -- Depends on how many ids you'll want to accept
  WHERE seq.i < JSON_ARRAY_LENGTH(('[' || {{ids}} || ']')::json)
)
SELECT *
FROM metabase_field
WHERE id IN (SELECT id FROM exploded_array)
```

**Comment by ObadaM** [comment]
I found a way to do it: 
`with seq_0_9 AS (
  select 0 as num union all
  select 1 union all
  select 2 union all
  select 3 union all
  select 4 union all
  select 5 union all
  select 6 union all
  select 7 union all
  select 8 union all
  select 9
), seq_0_999 as (
select a.num + b.num * 10 + c.num * 100 as num
from seq_0_9 a, seq_0_9 b, seq_0_9 c
)SELECT TRIM(SPLIT_PART('123,321', ',',seq_0_999.num))
from seq_0_999
where seq_0_999.num > 0;`

but unfortunately, it's not optimal for us. We have a lot of cards with multiple filters, we prefer to have this feature back actually. Nevertheless, running time cost here is higher. 
Anyway, thanks for your help and suggestions.

**Comment by paoliniluis** [comment]
We are having the same issue there, sometimes end users want to input several values and the "IN" operator worked flawlessly.

**Comment by igorbraz89** [comment]
```
[[ AND yourtable.field in ( regexp_split_to_array( {{variable::text[]}}, ',' ) ) ]] 

```

**Comment by walterl** [comment]
Closing this, since it works for me: 
![image](https://user-images.githubusercontent.com/23798/76459255-839cb500-63e4-11ea-9870-bd693ba9ea5d.png)

**Comment by benpony** [comment]
> ```
> [[ AND yourtable.field in ( regexp_split_to_array( {{variable::text[]}}, ',' ) ) ]] 
> ```
> 
> Works for me on Metabase ( Query on Redshift )

metabase does not recognize variable that way:
tried also the version below to no vail :\  
```
  [[ WHERE storyline_uuid IN  ( regexp_split_to_array( {{storyline_ids}}::text[], ',' ) ) ]] 
```

**how can one uses TEXT seperated values within IN clause?**

**Comment by flamber** [comment]
@benpony Redshift requires a lot more hoops than previously, where it was closer to Postgres. Upvote #4728 and see comments.

**Comment by benpony** [comment]
> @benpony Redshift requires a lot more hoops than previously, where it was closer to Postgres. Upvote #4728 and see comments.


thanks for replaying, it seems i can implement a solution to my use-case using Filters (by passing an array as a Filter defined variable)
