### ISSUE TITLE
Enable Time choice in daterange variable

### ISSUE THREAD

**Issue by mokra** [metabase/metabase#5385]
I couldn't find it in the issues list.
If I add a variable and set it a daterange, I can't choose the time - only date. 
Is this still an issue or didn't I search good enough?

thanks

**Comment by salsakran** [comment]
At the moment, I believe our date widgets for native queries are date only.

**Comment by flamber** [comment]
Related to #7418 and #8221

**Comment by flamber** [comment]
Closing in favor of #7418
