### ISSUE TITLE
Add multiple metrics with same operator (Ex: sum)

### ISSUE THREAD

**Issue by joanabelem** [metabase/metabase#5393]
Hi, I tried to add more than one metric with same operator (example: Sum of Completed Tasks and Sum of Assigned Tasks) but only metabase only as a new column sum on the table with the results of the last sum applied.

![image](https://user-images.githubusercontent.com/5632861/27481076-bfcb3442-5812-11e7-82dd-34c6463bbfd9.png)

Can I add differents metrics with the same operator? 
Thanks

**Comment by joanabelem** [comment]
![image](https://user-images.githubusercontent.com/5632861/27481076-bfcb3442-5812-11e7-82dd-34c6463bbfd9.png)

**Comment by davidmir** [comment]
Hi,

I think that is a issue with the MongoDB database only. With the Sample Dataset I can make many Sum operations (see bellow).

![screen shot 2017-07-07 at 15 37 16](https://user-images.githubusercontent.com/4657051/27962677-8ce68d9c-632a-11e7-876d-99d7fcf9d707.png)

This is what I see in the log when I make multiple sum's using the metabase with MongoDB:

> MONGO AGGREGATION PIPELINE:
> [{"$project" {"assigned_tasks" "$assigned_tasks", "completed_tasks" "$completed_tasks"}}
>  {"$group" {"_id" nil, "sum" {"$sum" "$completed_tasks"}}}
>  {"$sort" {"_id" 1}}
>  {"$project" {"_id" false, "sum" true}}]
> 
> 07-07 11:12:35 DEBUG middleware.mbql-to-native :: NATIVE FORM: 😳
> {:query
>  [{"$project" {"assigned_tasks" "$assigned_tasks", "completed_tasks" "$completed_tasks"}}
>   {"$group" {"_id" nil, "sum" {"$sum" "$completed_tasks"}}}
>   {"$sort" {"_id" 1}}
>   {"$project" {"_id" false, "sum" true}}],
>  :collection "tasks_events",
>  :mbql? true}

And this is the log using the metabase with H2 database:
> 07-07 11:29:25 WARN query-processor.annotate :: There are fields we weren't expecting in the results: #{:sum_2}
> Expected: #{:TOTAL :TAX :sum}
> Actual: #{:sum_2 :sum}
> 07-07 11:29:25 DEBUG query-processor.sort :: Sorted fields:
> ([:1-aggregation 2147483647 :2-other :TAX]
>  [:1-aggregation 2147483647 :2-other :TOTAL]
>  [:1-aggregation 2147483647 :2-other :sum]
>  [:1-aggregation 2147483647 :2-other :sum]
>  [:1-aggregation 2147483647 :2-other :sum_2])

Can you please confirm if that is a issue of metabase integration with MongoDB?

Thanks in advance

**Comment by mikepii** [comment]
Seems to be fixed for MongoDB in v0.31.0. I had the same issue in v0.29.3 prior to updating. Now I get multiple "sum" columns, and I can rename them.

**Comment by camsaul** [comment]
Fixed by #8987
