### ISSUE TITLE
Drag to filter not working for nested queries

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5398]
steps to repro that drag-to-filter issue:

- save a question that has at least a metric column and a date column (it might also be the case that it must have a date filter as part of its definition, e.g. “birthday is between 1980 and 1990”). mine was just the People table with that `between` filter on it
- create a new quesiton using that saved question, and do something like count of rows by birthdate, then plot it as a line or bar chart
- try using the drag-to-filter
- you’ll see two things that are wrong: 
   1. you’ll incorrectly get a second breakout instead of it just adding the filter (this is a separate issue that i reported already), 
   2. you’ll get this error message: “Must be an OrderableValue or OrderableValuePlaceholder”

**Comment by camsaul** [comment]
This was on the `issue-5272` branch

**Comment by mokra** [comment]
I am also having a bug with drag to filter function, but also with normal quieries (not nested ones)
![chrome_2017-06-24_20-37-24](https://user-images.githubusercontent.com/1849512/27511047-3b9a7082-591d-11e7-862a-2a8ddbe3ad58.png)

**Comment by camsaul** [comment]
@mokra it sounds like your problem is covered by issue #5272
