### ISSUE TITLE
Can't add dashboard filter 

### ISSUE THREAD

**Issue by HugoPouliquen** [metabase/metabase#5403]
I can't create a dashboard filter

My sql query : 
```SELECT table2.CompanyName AS CompanyName, table1.EstimatedRevenue AS Revenue FROM table1 LEFT JOIN table2 ON table1.CustomerId=table2.CustomerId WHERE CompanyName is not null```

![fieldsbug](https://user-images.githubusercontent.com/7288882/27549973-356f4fa2-5a9e-11e7-96e8-88204083a290.JPG)

**Comment by salsakran** [comment]
For dashboard filters on SQL cards, you will need to add "field based" template variables. 
See http://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html for more information. Closing this as Github is meant to be for reporting bugs and working on the product itself. If you need more help please open a thread on our discussion forum (discourse.metabase.com)

**Comment by HugoPouliquen** [comment]
@salsakran Ok thanks for this. But when I do this, I haven't the dropdown list...
