### ISSUE TITLE
Metabase Mac app using wrong username domain to connect to external MySQL databse

### ISSUE THREAD

**Issue by sharedphysics** [metabase/metabase#5414]
I'm using the local mac instance of Metabase to test out if it would be right for our company. I was able to connect it to our Google Analytics, but when it came time to connect to our MySQL database (minor data warehouse), I'm having some trouble accessing the database. In particular, I'm getting the error: 
`java.sql.SQLException: Access denied for user 'USERNAME'@'mail.DOMAIN.com' (using password: YES)`
Issue is, I have no idea where the "@mail.DOMAIN.com" section is coming from, because it bears no relation to anything. Looks like it is pulling my personal Metabase account URL instead of the hostname I've given. Help??

**Comment by camsaul** [comment]
What did you put for `host` for your MySQL database when you added it?

**Comment by sharedphysics** [comment]
_subdomain.domain.com_ as generated by the SQL query:
`SHOW VARIABLES WHERE Variable_name = 'hostname'`

**Comment by camsaul** [comment]
I would take a look at the database connection details in the admin panel and double-check that you put the right host in

**Comment by sharedphysics** [comment]
See image below... what I put in the host and what the error is showing is being used are different domains. The one in the error happens to be my local machine's domain.

![image](https://user-images.githubusercontent.com/5796884/27709551-8a61be34-5cea-11e7-8198-7f77442ccf3c.png)

**Comment by camsaul** [comment]
can you connect to it with the same details from any other applications? Or the `mysql` command?

**Comment by sharedphysics** [comment]
I haven't tried that. How would I connect via the mysql command in metabase? Can you provide screenshot of where to input and template script that I'd need to use?

**Comment by sharedphysics** [comment]
Perhaps this is the issue? MySQL database is running on an external-hosted site, not my local machine or local server. Error seems to be that Metabase is picking up my local IP/address and using that. It doesn't match what I input, not sure why that is happening.

**Comment by camsaul** [comment]
See if you can connect to it from the `mysql` command in the terminal or from another application with the same details. My guess is that something's weird with your configuration or your DB details, we've had tons of people connect to MySQL successful and haven't seen this before so I don't think it's a problem with Metabase itself

**Comment by sharedphysics** [comment]
Ah, thank you. Just fixed it. Turns out, I forgot to enable remote MySQL access for my external domain. Good thing to note in a FAQs/Troubleshooting page ;)
