### ISSUE TITLE
Support BigQuery standard SQL backtick syntax in Field Filter

### ISSUE THREAD

**Issue by tobbbles** [metabase/metabase#5423]
Currently the following metabase Field Filter variable of type `TIMESTAMP` will generate an invalid query when using standard SQL.

**Metabase:**
```sql
#standardSql
SELECT
    COUNT(*)
 FROM 
    `data.stats*`
[[ WHERE {{range}} ]]
```
**Generated:**
```sql
#standardSql
SELECT
    COUNT(*)
 FROM 
    `data.stats*`
 WHERE CAST(date([data.stats.timestamp]) AS timestamp) BETWEEN ? AND ?
```
You can see here that the `WHERE` statement is generated with the legacy SQL square bracket syntax, and not the standard backticks. So we're given the error of `Unrecognized name: data at [7:19]` (full error/debug log [here](https://pastebin.com/raw/fHfNh3n9).)

I manually edited the query to use standard syntax, however the argument for `CAST()` gives the dataset, table, and column name; which is gives the error:
```
Error: Unrecognized name: `data.stats.timestamp`; Did you mean data.stats*? at [7:13]
```

The correct argument here is just the column name, enclosed in backticks.

**Note:**
The column where the date's being cast is named `timestamp` but is also of type `TIMESTAMP`. This isn't a problem with valid standard SQL, but may be a factor in the issue here.

**Comment by mnzt** [comment]
#5402 Related.

**Comment by mnzt** [comment]
#3012 Also related.

**Comment by mnzt** [comment]
This occurs at the following line: https://github.com/metabase/metabase/blob/master/src/metabase/driver/bigquery.clj#L342

How does a proposed solution of checking `setUseLegacySql`, and doing the following based on sql version sound?
**Legacy:**
```
(hsql/raw (apply format "[%s.%s.%s]" dataset (field/qualified-name-components field)))))
```
**Standard:**
```
(hsql/raw (get (field/qualified-name-components field) 1)))) ;; Proposed solution
```

I've tested the Standard implementation and it works well with my one query. However I'm concerned of breaking existing queries.

**Comment by mnzt** [comment]
After checking, even with legacy SQL there's no requirement to specify `[data_set.tablename.field]` as so done here:
https://github.com/metabase/metabase/blob/master/src/metabase/driver/bigquery.clj#L342

I'll ready a PR for this issue in where only the column name is used in `field->identifier`, ready for testing.

**Comment by mnzt** [comment]
#5402 related.

**Comment by mnzt** [comment]
@salsakran Pinging you again, as I see this is a high priority bug rather than a proposal.

Currently, It's not possible to use field filters on `timestamps`, with standardSql on BigQuery due to this.

**Comment by pfeiffer** [comment]
Any updates on this? Would really like to use standardSql and filters :-)

**Comment by gamars** [comment]
@salsakran any update on this issue or  is there a "grander design" about BQ Standard SQL implementation? Because this PR can go a long way to unleash many blockers! We're currently running a forked version of metabase unlikely for this reason.  Not that you can also simply use %s.%s.%s without the []

**Comment by aanjaria** [comment]
The issue exists for all data types, not just TIMESTAMP fields

Do we have any updates on this? This seems like a deal-breaker for pretty much any BQ user looking to use field filters

**Comment by camsaul** [comment]
With #7945 Metabase will now generate BigQuery Standard SQL, so this will now work as expected
