### ISSUE TITLE
Datetime 'is null'  or 'is not null'

### ISSUE THREAD

**Issue by joshhopkins** [metabase/metabase#5444]
### Feature requests and proposals

Be great to have condition such as 'is empty' and 'Not empty' as filters for datetime / timestamps.

**Comment by kdoh** [comment]
Hey @joshhopkins. You should be able to specify "Is empty" and "Not empty" for date fields. 
<img width="327" alt="screen shot 2017-07-08 at 2 36 13 pm" src="https://user-images.githubusercontent.com/5248953/27989298-d3a32f72-63ea-11e7-864c-56ec09c7471b.png">

Are these options not showing up in filters for you?

**Comment by joshhopkins** [comment]
Oh – I was sure it was possible, but I'm only seeing this:
<img width="299" alt="screen shot 2017-07-08 at 11 39 00 pm" src="https://user-images.githubusercontent.com/11452674/27989354-03be34da-6437-11e7-9509-35120f101331.png">

**Comment by kdoh** [comment]
If you hit the top drop down "Previous" it gives you more date time options.

**Comment by joshhopkins** [comment]
Ah I must be tired – thanks! Don't recall "previous" being the default filter for date fields, but there you go.

**Comment by kdoh** [comment]
Np! We've had it as the default for a while, the rationale being questions like "What happened in the past 30 days?" tend to be fairly common and are an easy starting place for folks to build off of.
