### ISSUE TITLE
widget "drop down" as multiselect

### ISSUE THREAD

**Issue by BembelGmbH** [metabase/metabase#5445]
Hi - is there a place for this?
I am wring about a drop down as multiselect that would contain custom keys and values and could be used as a variable ins the SQL-Queries. 
Or does this function already exist?

thanks!!!

**Comment by sabino** [comment]
possibly to #3736

**Comment by flamber** [comment]
This was implemented in 0.28 for Field Filters.
Related to #5245 and #6820
