### ISSUE TITLE
No access when inside docker or use docker link

### ISSUE THREAD

**Issue by sunshineo** [metabase/metabase#5446]
When deployed to docker cloud, here is what the /etc/hosts file looks like
```
/ # cat /etc/hosts                                                                                                                                                       
127.0.0.1       localhost                                                                                                                                                
::1     localhost ip6-localhost ip6-loopback                                                                                                                             
fe00::0 ip6-localnet                                                                                                                                                     
ff00::0 ip6-mcastprefix                                                                                                                                                  
ff02::1 ip6-allnodes                                                                                                                                                     
ff02::2 ip6-allrouters                                                                                                                                                   
172.17.0.10     metabase-b2dc2d37-1                                                                                                                                      
10.7.0.29       metabase-b2dc2d37-1  
```
This works `curl https://172.17.0.10:3000`
These does not work `curl http://127.0.0.1:3000` `curl http://10.7.0.29:3000` 

The problem is that I am trying to setup a reverse proxy using nginx, so that the link is a subdomain on port 80 like this `http://report.mysite.com` . The unlucky part is that the nginx in docker only get the ip `10.7.0.29` that does not work.

Do you have code that look at the request url and block? Or is this something completely about docker?

Thank you very much!

**Comment by sunshineo** [comment]
Report: I switched the base image from java:openjdk-jre-7-alpine to openjdk:7-jre and then it works.

**Comment by flamber** [comment]
Closing, since this is documented that `MB_JETTY_HOST` defaults to `localhost`:
https://www.metabase.com/docs/latest/operations-guide/customizing-jetty-webserver.html#listening-on-a-specific-network-interface
