### ISSUE TITLE
Asking for basic auth 3 times behind nginx proxy

### ISSUE THREAD

**Issue by parabolic** [metabase/metabase#5449]
- **Browser:** google chrome Version 59.0.3071.115 (Official Build) (64-bit)
- **OS:** Ubuntu 16.04 64bit
- **Databases:** not applicable
- **Metabase version:** 0.24.2
- **Hosting environment:** Docker running on AWS ECS
- **Metabase internal database:** Postgres
- **Nginx version:** 1.13.2

### Problem
When using an nginx proxy with a basic http authentication I get asked 3 times for the basic authentication password. 
1. On the first hit.
2. Before the login page loads.
3. After pressing the login button.

I  am suspecting that it has to do with the 2FA and it sends some data to nginx which confuses it and nginx asks for a authentication again.
When I drilled down to the problem I noticed that I get asked for an password when metabase hits the url `/api/user/current`. I wasn't able to pinpoint the problem but I got it the nginx asking for the password once by putting this block
```
location ~ ^/api/user/current/ {
    proxy_pass http://metabase_service;
    expires 0;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
```
and the rest of the locations default to 
```
location / {
    auth_basic "Restricted Content";
    auth_basic_user_file http_passwd;
    proxy_pass http://metabase_service;
    expires 0;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
```
Thanks for making an awesome software like metabase! It really is very useful!
Cheers.

**Comment by camsaul** [comment]
This sounds like it's outside of the scope of the Metabase project. Metabase itself doesn't use HTTP Basic Auth for authentication, so I'm guessing you'll probably need to tweak your nginx proxy settings to make sure you set it up correctly.

**Comment by ianflorian** [comment]
@camsaul Yes, you can fix it! ;-) The issue is actually at least partially caused by Metabase. When the user is not logged in, Metabase responds to ``/api/user/current`` with HTTP status code ``401`` during an active ``basic auth`` session. This seems Chrome to end the session and prompt for username and password again. When the user is logged in, ``/api/user/current`` responds with ``200`` and Chrome keeps the ``basic auth`` session. We have put ``Nginx`` in front of Metabase for ``basic auth`` and to convert the ``401`` for ``/api/user/current`` into a ``452`` to address this issue. It's certainly not an ideal solution but it works for now. Maybe you could try to avoid the ``401`` status in the future.

**Comment by impca** [comment]
@ianflorian do you have an example nginx config you could share that converts 401 to 452?

**Comment by flamber** [comment]
@impca Haven't tested, but `error_page` should work, if you're intercepting the proxy errors.
https://stackoverflow.com/questions/8237761/is-it-possible-to-change-the-http-status-code-returned-when-proxy-pass-gateway-i

**Comment by fgiroud** [comment]
@ianflorian , could you post your nginx configuration to convert 401 to 452 ? We are facing the same issue and this would help a lot

**Comment by exister** [comment]
@fgiroud faced it myself recently, my working solution is

```
location /api/user/current {
        proxy_intercept_errors on;
        error_page 401 =402 /empty.gif;
        proxy_pass http://127.0.0.1:3001;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
    }
```

**Comment by ianflorian** [comment]
Thank you @exister, our Nginx configuration may have looked very similar. Unfortunately, we don't have it anymore since we started using Google Cloud GCIP and IAP, @fgiroud.
