### ISSUE TITLE
metabase_fieldvalues is not updated on database sync

### ISSUE THREAD

**Issue by rafaelveloso** [metabase/metabase#5452]
Sorry if this is a duplicate but I searched for similar issues and didn't find any describing this particular problem.
When an new `category` type value is added to the source database table field data, the value is not showing in any dropdown or query builder filter. After a quick investigation, I found out that `metabase_fieldvalues` is not updated even after a manual database sync (through the admin interface). I ended up having to manually update `metabase_fieldvalues` to include the newly added `values`.
Is anyone else experiencing this? I've seen the values get updated in the past, so this might be some kind of regression?

Using Metabase v0.24.2 with postgres 9.6.2

**Comment by mvrabel** [comment]
@rafaelveloso I gad the same problem and the values updated after half an hour cca. I manually synced like 5 times and even restarted metabase. Nothing helped. After cca 30 min the new category was in the dropdown menu.

**Comment by salsakran** [comment]
a manual database sync will start the process.

however, it's a fairly intensive process, and typically takes a bit of time. We're going to be shipping better controls for this in the next two releases.

If you examine your server logs you should see a bunch of "sync" and "analyze" log lines.
