### ISSUE TITLE
Allow anonymous LDAP lookup user

### ISSUE THREAD

**Issue by kjad** [metabase/metabase#5460]
I've been testing out the LDAP integration and its working smoothly. The only issue that I ran into during setup was the required username/password for the LDAP lookup user. My implementation of LDAP allows anonymous binding. Would it be possible to remove the requirement of an LDAP lookup user on the configuration page?

**Comment by wwwiiilll** [comment]
Anonymous binds aren't enabled where I am, so I overlooked that when I made the LDAP integration.

**Comment by kjad** [comment]
Just tested this out, so far so good. Thanks for the quick change!
