### ISSUE TITLE
Outdated code on wiki page

### ISSUE THREAD

**Issue by luwanjiu** [metabase/metabase#5469]
Example code of authorizing on wiki page [link](https://github.com/metabase/metabase/wiki/Using-the-REST-API#authorizing) should be passing '**email**' param:
```
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"email": "cam@metabase.com", "password": "myPassword"}' \
  http://localhost:3000/api/session
```
instead of the  '**username**' param.

**Comment by kdoh** [comment]
Thanks for reporting this @luwanjiu. It should be fixed now. I'd over eagerly updated the wiki to reflect changes in our upcoming release. Just note that as of version 025 the username param will need to be used instead of email.
