### ISSUE TITLE
Scrollbar for filters in query builder isn't showing up, so not all filters are visible

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5470]
This is on Chrome on master. You can still scroll horizontally using the arrow keys, but there's no visible horizontal scroll bar.

![screen shot 2017-07-13 at 10 40 09 am](https://user-images.githubusercontent.com/2223916/28179735-b4c1804c-67b7-11e7-86bd-2e85f7c7e4a5.png)

**Comment by kdoh** [comment]
Just tried to reproduce this but I can't seem to on master using Chrome 58. Are there any other relevant details you can think of? I tried matching the filters you were using as close as I could.
<img width="695" alt="screen shot 2017-07-17 at 8 58 29 am" src="https://user-images.githubusercontent.com/5248953/28277236-2cb37984-6ace-11e7-911c-efcbf95f9e9b.png">

**Comment by mazameli** [comment]
Appears to only be happening on Chrome, v59+

**Comment by jaredlt** [comment]
I can reproduce this issue on Chrome 61. Have tested in a new Chrome profile to rule out extensions being a factor.

Edge and Firefox 56.0.1 work as expected and show the horizontal scroll bar.

**Comment by Sigurs** [comment]
Reproduced on Chrome 63.
Not a web developer so can't find the exact cause for this.
I was able to work around this locally by overriding  `<div class="Query-filterList scroll-x scroll-show scroll-show--horizontal">` to exclude the class `scroll-show--horizontal` which in turn caused a grey scrollbar to appear.
