### ISSUE TITLE
QB renders incorrectly with read-only question and limited access to db

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#5505]
Steps to reproduce:
1) Create a new user group and grant it limited access to Sample Dataset with no access to Orders table
2) Create a new collection and grant to the user group a read-only access to that collection
3) Create a question which queries Orders table and belongs to the collection
4) Login with a user belonging to the user group and open the question. You will see the query results together with a query editor bar which is in an odd state:
<img width="946" alt="screen shot 2017-07-18 at 16 00 44" src="https://user-images.githubusercontent.com/6034928/28343715-95c9b57c-6bd3-11e7-840d-664411cbcfdc.png">

You should only see query results without the query editor because the question is read-only and user has no access to the current table.

**Comment by flamber** [comment]
Hi @attekei 
I've tested in 0.31.2 and now it doesn't show the QB and the browser gives a few Access Denied.
And I cannot do any drill-down.
But all of this seems to be correct, given how Collections had the major overhaul in 0.30
![image](https://user-images.githubusercontent.com/1447303/52894489-df5c2680-316f-11e9-8e7a-b5dadacf8719.png)
