### ISSUE TITLE
Duplicate slack pulse with one instance

### ISSUE THREAD

**Issue by alexauvray** [metabase/metabase#5512]
Hello !

I have only one instance, and two bots are sending the same notification on Slack. One is MetaBot, the other one is the custom one I set up to connect Slack with Metabase. Both are sending the same pulse everytime it shoots.

Any idea ?

![image](https://user-images.githubusercontent.com/28756458/28383028-632803f6-6cc0-11e7-8e44-b5b4440032cf.png)

Thanks !

**Comment by alexsonnay** [comment]
Other issue : the pulse didn't shoot automatically.

**Comment by salsakran** [comment]
Hmm. The way we embed images in slack is to upload an image in `_metabase_files` and then create a post that references that image. The slack api didn't allow you to include an image file at the time we wrote that code (and I don't believe allows you to now). Which channel are you seeing that in?

**Comment by alexsonnay** [comment]
I'm seeing that in channel #metabase_files

**Comment by inazarv** [comment]
were you able to resolve this issue, @alexsonnay?

**Comment by mralexpopa** [comment]
I am having the same problem. Any solutions so far?

**Comment by brnt** [comment]
I have an issue that could be related (if not, I can create a separate ticket):

When I scale up the number of dynos in Heroku (where my Metabase install lives) beyond one, I get duplicate pulses to Slack. It feels like the dynos are running independent-enough copies that both instances believe they're the only one and wholly responsible for sending out pulses.

I'm not sure what the internal implementation of pulses looks like, but it seems like a blocking flag (mutex) during the pulse processing and then an indication that today's run has completed successfully would be appropriate.

**Comment by base16soft** [comment]
Hi,

I had the same issue here at version 0.27.2

I've just disabled METABOT from "admin/settings/slack"

> METABOT
> Enable MetaBot, which lets you search for and view your saved questions directly via Slack.

And the duplication stop...

**Comment by shreyas-spocket** [comment]
did anyone solve this issue? I am facing the same problem as I am subscribing to the dashboard in Matabase.

**Comment by flamber** [comment]
@shreyas-spocket Post "Diagnostic Info" from Admin > Troubleshooting, and how you're hosting Metabase (Docker, k8s, etc)

**Comment by flamber** [comment]
Closing as this issues has not been seen for years.

**Comment by mousavii** [comment]
this issue is occurring for my pulses.

**Comment by flamber** [comment]
@mousavii Post "Diagnostic Info" from Admin > Troubleshooting, and how you're hosting Metabase (Docker, k8s, etc).

**Comment by Dam-Buty** [comment]
Hi !

I'm having this exact same issue, diagnostic info is pasted at the bottom of this comment. 

For information i'm running the **official Metabase Docker image** on **Digital Ocean** [App Platform](https://www.digitalocean.com/products/app-platform) **thing**.

I didn't manage to implement @augustocsmartins 's solution (no "Metabot" option in Admin>Settings>Slack). Here's a screenshot of the double-post. I renamed the bot user `Metabase-bot` to differentiate the two posts.

![image](https://user-images.githubusercontent.com/1461760/158143888-104b7264-cd7b-4d0e-a147-4ef7c543be48.png)

Thanks in advance !

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.4.0",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
@Dam-Buty You should change the files channel to some public channel that is not used by anyone #20936
There's no "Metabot" anymore. It has been removed completely: https://www.metabase.com/blog/Metabase-0.42/index.html#some-cleanup-to-start-the-year-fresh
