### ISSUE TITLE
Map view is dependent on SELECT field order

### ISSUE THREAD

**Issue by tobbbles** [metabase/metabase#5526]
With the following query, the "Country" and "Impressions" label and values are switched up
```
SELECT Impressions, Country
```
![2017-07-20-143832_263x129_scrot](https://user-images.githubusercontent.com/10098811/28420237-651b0a5c-6d59-11e7-8ba9-1da9547a095f.png)

However when correcting the SELECT fields to be in order, the issue disappears, see:
```
SELECT Country, Impressions
```
![2017-07-20-144212_237x91_scrot](https://user-images.githubusercontent.com/10098811/28420316-a34af7ba-6d59-11e7-94f3-52f407ded6e9.png)

----

Personally, I feel Metabase should be smart enough to put know that Country should be mapped to country code strings, and any other field to populate the metric.

Feedback on this is always welcome. :smile:

**Comment by camsaul** [comment]
I've never met anyone from `210145` but it sounds like a cool place 😹

**Comment by flamber** [comment]
Not sure when this was fixed, but I never remember seeing this problem. I cannot reproduce on 0.35.3
![image](https://user-images.githubusercontent.com/1447303/82759850-18159180-9df0-11ea-828f-ce32e767b8fa.png)
