### ISSUE TITLE
Nested queries not working with saved questions with a segment filter

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5530]
Testing 0.25-rc2 on Chrome. Trying to use this saved question as the source data for a new question (the large orders segment is `subtotal >= 50`):

<img width="855" alt="screen shot 2017-07-20 at 3 25 50 pm" src="https://user-images.githubusercontent.com/2223916/28441573-4dbb32b8-6d60-11e7-9f7b-badc3ca784ef.png">

I get this error after selecting that question from the data menu and trying a raw query:

<img width="893" alt="screen shot 2017-07-20 at 3 26 20 pm" src="https://user-images.githubusercontent.com/2223916/28441587-6c392dda-6d60-11e7-81f8-50102ea96fd8.png">

Text of the error:

`Input to compound-filter does not match schema: [0;33m [nil (named (named (not (matches-some-precondition? nil)) "Valid filter clause") subclause)] [0m`

**Comment by jpulec** [comment]
Adding to this report, I've encountered this issue in 0.25-RC2 in Chrome as well. Except I'm experiencing it with just a regular query, not using a saved question as the source of other data. In may case, it only occurs when I try to use an aggregation with a group by, and then add a timestamp filter.

**Comment by falling-down** [comment]
I am getting the same error using regular table with query builder, but I see it when I include a segment filter with any other filter on the table.
v0.25.0 
Chrome

**Comment by matstevenson** [comment]
Adding to @falling-down's comment.  On Firefox, I get it randomly when using a segment with another filter.  If I manually enter those same filters instead of the Segment, I don't get an issue.

So far only happening with our Mongo database.

**Comment by camsaul** [comment]
Yeah, it sounds like this isn't Nested Query-specific. Nested Queries don't even work for Mongo yet so if this error is happening with Mongo it can't be a Nested Queries thing

**Comment by camilonova** [comment]
I got this using postgresql

**Comment by gahabeen** [comment]
Working workaround given in #5706 : F5 (reload the page)

**Comment by mazameli** [comment]
Hey everyone. Just a heads up that [we've just shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.
