### ISSUE TITLE
Using a metric as a nested subquery doesn't work

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5531]
Reproduction steps
1. Create a metric that's Avg of latitude of people in the sample dataset
2. Save a question with just that metric
3. Use that saved question and select "raw data"
you get the raw data of the people table rather than the metric.

**Comment by salsakran** [comment]
likewise, a metric broken out by a date (eg, avg latitude by birthday) results in a list of birthdates

**Comment by mazameli** [comment]
Example:

<img width="759" alt="screen shot 2017-07-20 at 3 37 10 pm" src="https://user-images.githubusercontent.com/2223916/28441807-8b8c166a-6d61-11e7-9842-857025b29832.png">

<img width="820" alt="screen shot 2017-07-20 at 3 36 57 pm" src="https://user-images.githubusercontent.com/2223916/28441812-9327b88e-6d61-11e7-82f8-02f6abf5d649.png">

**Comment by mazameli** [comment]
I can no longer reproduce this in RC 0.31:

Nested query with just a saved metric:

![screen shot 2018-11-05 at 1 09 47 pm](https://user-images.githubusercontent.com/2223916/48026874-290e8d00-e0fc-11e8-8b24-9fe7db7076b7.png)

Nested query consisting of an official metric broken out by time:

![screen shot 2018-11-05 at 1 09 40 pm](https://user-images.githubusercontent.com/2223916/48026918-45aac500-e0fc-11e8-8061-653758934c94.png)
