### ISSUE TITLE
We shouldn't show "public" in data model menus if it's the only schema

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5535]
0.25-rc2 on Chrome.

<img width="419" alt="screen shot 2017-07-20 at 3 59 35 pm" src="https://user-images.githubusercontent.com/2223916/28443092-d92adf08-6d68-11e7-9d28-b731b3203758.png">

<img width="528" alt="screen shot 2017-07-20 at 4 32 58 pm" src="https://user-images.githubusercontent.com/2223916/28443148-205e8226-6d69-11e7-974d-0394a7a5c7d5.png">

It seems the custom projections stuff has introduced behavior where we’re appending the name of the schema to every possible FK-linked field, even if there’s only one schema in the DB (like public). I guess we were special casing it before? It looks cluttered to me now.

**Comment by attekei** [comment]
Fixed by #5557
