### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Nyno-Kun** [metabase/metabase#5539]
- Your browser and the version: Chromium Version 57
- Your operating system: Debian 9
- Your databases: MySQL, PG
- Metabase version: Version v0.24.2 (b859d40 release-0.24.2)
- Metabase hosting environment: Debian 8 Jessie
- Metabase internal database: H2

Hi there
Our internal MetaBase instance started to crash randomly this week. I've restarted it about 3 Times this week. So what the syslog says is:
[large log, sometimes its restarting itself]
[restarts self at 19:04]

Jul 20 19:03:57 metabase-server MetaBase[605]: 07-20 19:03:57 #033[1mINFO metabase.util#033[0m :: Loading Metabase...
Jul 20 19:04:06 metabase-server MetaBase[605]: 07-20 19:04:06 #033[1mINFO util.encryption#033[0m :: DB details encryption is ENABLED for this Metabase instance. <U+1F510>
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mINFO metabase.core#033[0m :: Starting Metabase in STANDALONE mode
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mINFO metabase.core#033[0m :: Launching Embedded Jetty Webserver with config:
Jul 20 19:04:23 metabase-server MetaBase[605]: {:port 3000}
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mINFO metabase.core#033[0m :: Starting Metabase version v0.24.2 (b859d40 release-0.24.2) ...
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mINFO metabase.core#033[0m :: System timezone is 'Europe/Zurich' ...
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:bigquery#033[0m <U+1F69A>
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:crate#033[0m <U+1F69A>
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:druid#033[0m <U+1F69A>
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:googleanalytics#033[0m <U+1F69A>
Jul 20 19:04:23 metabase-server MetaBase[605]: 07-20 19:04:23 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:h2#033[0m <U+1F69A>
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:mongo#033[0m <U+1F69A>
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:mysql#033[0m <U+1F69A>
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:postgres#033[0m <U+1F69A>
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:presto#033[0m <U+1F69A>
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:redshift#033[0m <U+1F69A>
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:sqlite#033[0m <U+1F69A>
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mDEBUG metabase.driver#033[0m :: Registered driver #033[34m:sqlserver#033[0m <U+1F69A>
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mINFO metabase.core#033[0m :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
Jul 20 19:04:24 metabase-server MetaBase[605]: 07-20 19:04:24 #033[1mINFO metabase.db#033[0m :: #033[36mVerifying h2 Database Connection ...#033[0m
Jul 20 19:04:29 metabase-server MetaBase[605]: 07-20 19:04:29 #033[1mERROR metabase.driver#033[0m :: Failed to connect to database: Timed out after 5000 milliseconds.
Jul 20 19:04:29 metabase-server MetaBase[605]: java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
Jul 20 19:04:29 metabase-server MetaBase[605]: (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.db$verify_db_connection.invokeStatic(db.clj:334)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.db$verify_db_connection.invoke(db.clj:327)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.db$verify_db_connection.invokeStatic(db.clj:330)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.db$verify_db_connection.invoke(db.clj:327)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.db$setup_db_BANG_.invokeStatic(db.clj:382)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
Jul 20 19:04:29 metabase-server MetaBase[605]: at clojure.lang.RestFn.invoke(RestFn.java:421)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.core$init_BANG_.invokeStatic(core.clj:103)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.core$init_BANG_.invoke(core.clj:82)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.core$start_normally.invokeStatic(core.clj:187)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.core$start_normally.invoke(core.clj:181)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.core$_main.invokeStatic(core.clj:279)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.core$_main.doInvoke(core.clj:274)
Jul 20 19:04:29 metabase-server MetaBase[605]: at clojure.lang.RestFn.invoke(RestFn.java:397)
Jul 20 19:04:29 metabase-server MetaBase[605]: at clojure.lang.AFn.applyToHelper(AFn.java:152)
Jul 20 19:04:29 metabase-server MetaBase[605]: at clojure.lang.RestFn.applyTo(RestFn.java:132)
Jul 20 19:04:29 metabase-server MetaBase[605]: at metabase.core.main(Unknown Source)
Jul 20 19:04:29 metabase-server MetaBase[605]: 07-20 19:04:29 #033[1mERROR metabase.core#033[0m :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.
Jul 20 19:04:29 metabase-server MetaBase[605]: (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
Jul 20 19:04:29 metabase-server MetaBase[605]: 07-20 19:04:29 #033[1mINFO metabase.core#033[0m :: Metabase Shutting Down ...
Jul 20 19:04:29 metabase-server MetaBase[605]: 07-20 19:04:29 #033[1mINFO metabase.core#033[0m :: Metabase Shutdown COMPLETE

After that i just restart metabase using systemd.
The Service File looks as following:

[Unit]
Description=Metabase server
After=syslog.target
After=network.target

[Service]
WorkingDirectory=/var/lib/metabase
SyslogIdentifier=MetaBase
ExecStart=/bin/sh -c "MB_ENCRYPTION_SECRET_KEY='not posted' java -jar metabase.jar"
User=metabase
Type=simple

[Install]
WantedBy=multi-user.target

After stoping and starting the Service, MetaBase runs normal.
So what is it then?

**Comment by salsakran** [comment]
The below indicates an error reading from the filesystem.

```
Jul 20 19:04:29 metabase-server MetaBase[605]: 07-20 19:04:29 #33[1mERROR metabase.driver#033[0m :: Failed to connect to database: Timed out after 5000 milliseconds.
Jul 20 19:04:29 metabase-server MetaBase[605]: java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
```

Is it possible you filled up a disk or something similar?

**Comment by camsaul** [comment]
@Nyno-Kun ?

**Comment by Nyno-Kun** [comment]
@camsaul sorry, was offline for a time.. well, since we updated, our metabase instance is not crashing anymore. Therefore, you can close this case.

**Comment by camsaul** [comment]
Ok. Glad it's working now.
