### ISSUE TITLE
Field Filter Fails Query

### ISSUE THREAD

**Issue by shirishsurti** [metabase/metabase#5553]
If a Field Filter type parameter is used for storeName variable the below query fails with error mentioned. Same query runs fine if parameter type is set as Text.

```sql
select distinct(so.booking_channel) as Channel, sum(so.total_amount) as Total, count(so.id) as Orders, (sum(so.total_amount)/count(so.id)) as APC  
from cabbeein_cpos.cp_pos_storeorders so join cabbeein_cpos.store_master smr on  (smr.id = so.store_id)
where date(so.bill_time) between {{fromDate}} and {{toDate}} [[and smr.name = {{storeName}}]] 
group by so.booking_channel order by so.booking_channel
```

ERROR: invalid reference to FROM-clause entry for table "store_master" Hint: Perhaps you meant to reference the table alias "smr".

Database: Redshift
Metabase Version: 0.24.2

**Comment by shirishsurti** [comment]
Is there a work around for this issue ? This is a blocker for us currently.

**Comment by jpulec** [comment]
@shirishsurti I believe this has to do with the fact that you're aliasing `cabbeein_cpos.store_master` as `smr`. If you were to rewrite the query without the alias, specifying the full table name everywhere, I believe the field filter would work. Seems related/duplicate of #3324

**Comment by shirishsurti** [comment]
@jpulec  I tried changing the query with full table name as below,

select date(so.bill_time) as "Sales Date", sum(so.total_amount) as "Total Sales"   
from cabbeein_cpos.cp_pos_storeorders so  join cabbeein_cpos.store_master  on  (cabbeein_cpos.store_master.id = so.store_id)
where date(so.bill_time) between {{fromDate}} 
and {{toDate}} [[and cabbeein_cpos.store_master.name = {{storeName}}]] 
group by date(so.bill_time);

However getting below error,
ERROR: operator does not exist: character varying = boolean Hint: No operator matches the given name and argument type(s). You may need to add explicit type casts.

**Comment by jpulec** [comment]
@shirishsurti Not positive, but I think that may be related to an issue that I've seen pop up other places... #5632 . Maybe checking that out could help?

**Comment by shirishsurti** [comment]
@jpulec  As it turns out I was writing the query wrongly. Once the alias is removed from the query was facing below issue mentioned here http://discourse.metabase.com/t/basic-sql-query-not-working-with-field-filter/1057

Corrected Query
```sql
select date(so.bill_time) as "Sales Date", sum(so.total_amount) as "Total Sales"   
from cabbeein_cpos.cp_pos_storeorders so  join cabbeein_cpos.store_master  on  (cabbeein_cpos.store_master.id = so.store_id)
where date(so.bill_time) between {{fromDate}} 
and {{toDate}} [[and {{storeName}}]] 
group by date(so.bill_time);
```
**Note** :  [[and cabbeein_cpos.store_master.name = {{storeName}}]]   has been replaced by  [[and {{storeName}}]]

**Comment by shirishsurti** [comment]
Duplicate of #3324
