### ISSUE TITLE
We should show progress charts' current values on small dashboard cards

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5554]
Progress bar charts are allowed to get as small as this, but do not display their current value in any way when at this size. It seems to me there should still be room above the bar to display the value, e.g. by making the bar itself smaller, or by putting the value inside the bar (the former seems more consistent).

![progress](https://user-images.githubusercontent.com/2223916/28534837-f142e662-7056-11e7-80ae-fb38f6079da5.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by qin4zhang** [comment]
Same Question. Have you solved it?
