### ISSUE TITLE
Integrated tests run forever if Metabase server startup fails

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#5560]
Recently the integrated test bootstrapping has often failed to a Metabase instance startup error:
```
.07-21 11:32:04 ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
.java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
...
07-21 11:32:04 INFO metabase.core :: Metabase Shutting Down ...
07-21 11:32:04 INFO metabase.core :: Metabase Shutdown COMPLETE
```

Currently that doesn't properly terminate the integrated test process and it blocks other scheduled tests in CircleCI until you manually cancel it.

**Comment by flamber** [comment]
Closing, since there's timeouts in place now
