### ISSUE TITLE
Issue related to working with MySQL time fields

### ISSUE THREAD

**Issue by sharedphysics** [metabase/metabase#5563]
I'm working with a MySQL call-center-related database which has numerous time fields (00:00:00). I'm trying to calculate the average ring time and am running into a few issues:

1. Looks like Metabase is reading and interpreting the time field incorrectly? 
In database:
![image](https://user-images.githubusercontent.com/5796884/28547628-c53a46ae-709d-11e7-9637-4cd422cb5d69.png) 
In Metabase:
![image](https://user-images.githubusercontent.com/5796884/28547641-d28a394a-709d-11e7-8714-8409f9653bba.png)

2. Not sure if #1 is the root problem, but I can't group or sort by time, nor average a time field.

**Comment by salsakran** [comment]
Are you using a reporting timezone and are you using native or SQL queries?

Also, which version are you on and how are you running metabase (eg, on heroku, the mac app, etc)?

**Comment by sharedphysics** [comment]
I'm not sure if I am using a reporting timezone. Not using native queries, using question builder. 
Running Docker instance, I believe.

**Comment by salsakran** [comment]
it looks like we're interpreting the `time` as a `datetime`. 

If it isn't too much hassle, can you open up the network inspector in chrome (or equivalent in other browsers) and see what the return value of the "dataset" api call returns?  Just the "rows" portion would be enough. Also, can you share your MySQL table schema or create statement with us?

**Comment by sharedphysics** [comment]
Did you want to see the full rows return? 

For the Ring Time, Row 0:
`"1969-12-31T19:00:19.000-05:00"`
Images: 
![image](https://user-images.githubusercontent.com/5796884/28852763-ac166fa6-76f9-11e7-9587-7dc3f9eb44a4.png)
![image](https://user-images.githubusercontent.com/5796884/28852813-11d57940-76fa-11e7-8281-c7bdcd2c8139.png)
Looking at it more closely, looks like `Date` may be interpreted wrong as well? 


In MySQL: 
![image](https://user-images.githubusercontent.com/5796884/28852703-35bc9fa6-76f9-11e7-9af7-678784d8768c.png)

![image](https://user-images.githubusercontent.com/5796884/28852718-4bee73b2-76f9-11e7-8540-9557cca5a8f3.png)

Am I setting it up wrong in MySQL?
(Note: difference in column numbers is due to them being returned alphabetically in MetaBase. 

![image](https://user-images.githubusercontent.com/5796884/28852859-65e4cbb2-76fa-11e7-9457-70990f6dc72e.png)

![image](https://user-images.githubusercontent.com/5796884/28852878-7abd3858-76fa-11e7-967a-7b980fff4834.png)

**Comment by sharedphysics** [comment]
@senior Just to bubble this up in context of your comment in #5319 , looks like individual `Date` fields are being parsed incorrectly as well (see above screens): `Row 11` = `Date`, how is it displayed vs how it is in the database.

**Comment by senior** [comment]
@sharedphysics you're correct, we have a similar problem with Date as we do with time. We're using default behavior, which is giving it a time of midnight. I've got that on my list to work on soon as well (likely while working on the time field stuff).
