### ISSUE TITLE
When a given breakout category has only a single value, we should skip the selection in drill-through

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5575]
eg 
![screen shot 2017-07-25 at 2 03 52 pm](https://user-images.githubusercontent.com/107439/28593686-1d2af544-7142-11e7-8751-5f82a3873d6c.png)

**Comment by mazameli** [comment]
I don't know that I agree. How would I know what it's about to break out by?

**Comment by brunobergher** [comment]
No traction in 4 years, closing.
