### ISSUE TITLE
Multiple tables with the same name in the same schema.

### ISSUE THREAD

**Issue by jmoseley** [metabase/metabase#5578]
- Your browser and the version: Chrome 59.0.3071.115
- Your operating system: macOS Sierra
- Your databases: Postgres, Redshift
- Metabase version: 0.24.0
- Metabase hosting environment: AWS ECS
- Metabase internal database: RDS Postgres

Not sure how to reproduce the issue, but we are seeing multiple tables in the same schema that have the same name. I confirmed that this is reflected in the Metabase database:

```
ebdb=> select schema from metabase_table where name = '<redacted>';
         schema
------------------------
 public
 public
 extract
 src
 src
```

**Comment by LukeAbell** [comment]
I’m seeing this issue if I reference the same table using two foreign keys in a question:
Customer ID -> Users
Recipient ID -> Users

“ERROR: table name "lrt_user_meta_pivot_prepared__" specified more than once”

**Comment by camsaul** [comment]
@jmoseley are you sure they're part of the same database? Try selecting `schema` and `db_id`

**Comment by camsaul** [comment]
@LukeAbell that sounds like a different issue altogether. What database and version of Metabase are you using?

**Comment by LukeAbell** [comment]
@camsaul 25.1 - Reading a postgres DB - metabase is running a postgres db

**Comment by jmoseley** [comment]
@camsaul Looks like the same db_id:

```
ebdb=> select schema, db_id from metabase_table where name = 'shipper_programs';
         schema         | db_id
------------------------+-------
 public                  |     2
 public                  |     2
 extract                |     2
 src                       |     4
 src                       |     4
```

**Comment by camsaul** [comment]
Ick. I opened #669 a couple years ago for adding unique constraints or `Table` `db_id` + `schema` + `name` because I was worried something like this would happen. We didn't end up doing that at the time because fixing any duplicates that might exist automatically is tricky. It seems like maybe we should tho

**Comment by camsaul** [comment]
I just had an epiphany 

@jmoseley can you also look at `active` and `visibility_type`?

**Comment by jmoseley** [comment]
```
ebdb=> select schema, db_id, active, visibility_type from metabase_table where name = '<redacted>';
         schema         | db_id | active | visibility_type
------------------------+-------+--------+-----------------
 public                 |     2 | t      |
 public                 |     2 | t      |
 extract                |     2 | t      |
 src                    |     4 | t      |
 src                    |     4 | t      |
```

**Comment by LukeAbell** [comment]
@camsaul anything on my issue?

**Comment by camsaul** [comment]
Sorry @LukeAbell not yet. If you want to open a new issue for it to make sure it doesn't get overlooked once we fix this one that would probably be a good idea. It seems like it's almost certainly a separate issue

**Comment by camsaul** [comment]
This was fixed a few years ago. Not sure what the PR is but there's a test for the issue here

https://github.com/metabase/metabase/blob/master/test/metabase/query_processor_test/joins_test.clj#L67
