### ISSUE TITLE
how to Change the secondary y-axis label in multi series bar chart 

### ISSUE THREAD

**Issue by shyam2794** [metabase/metabase#5583]
Unable to change the label for secondary y-axis the y-axis on the left needs to be volume and the right needs to be revenue, but changing the value in y-axis changes both the axes . 

![screenshot from 2017-07-26 13-55-47](https://user-images.githubusercontent.com/30238125/28611662-3106c7f0-720a-11e7-8691-4d15c5a933f3.png)

**Comment by mazameli** [comment]
Seems like we should be showing an additional form field on this screen in the event that there is a second y-axis, with the label `Secondary y-axis label`.

**Comment by gukras** [comment]
Yes, this is difficult with more than 2 fields there. I have reports with Sum 1 , Sum2, Sum 3, and its difficult to follow

**Comment by MarcGJA** [comment]
Same problem, solution for the time being is to type into the single Y-axis label box "xyz (left) -- abc (right)" to let users know what's what; not pretty but gets it done...

**Comment by flamber** [comment]
This is a duplicate of #3897

**Comment by flamber** [comment]
Closing in favor of #3897
