### ISSUE TITLE
Can't edit some filter values

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5589]
On master, using chrome, when trying to edit a numeric or string value for a filter with an input box, rather than a check box, I consistently get a JS error, and the filter value change does not persist. With strings, it seems to be specifically happening with contains/does not contain filters; `Is` or `Is not` do not seem to show the error. The error also does not appear to occur with datetime filters.

**Before**

![screen shot 2017-07-26 at 2 25 46 pm](https://user-images.githubusercontent.com/2223916/28644467-8dd7d056-720e-11e7-8c5c-f31b7169adec.png)

**After editing**

![screen shot 2017-07-26 at 2 25 54 pm](https://user-images.githubusercontent.com/2223916/28644484-a0ebec5e-720e-11e7-9b94-3a72cb513c83.png)

**A string example**

![screen shot 2017-07-26 at 2 26 32 pm](https://user-images.githubusercontent.com/2223916/28644500-b13c9a86-720e-11e7-9cc9-88adacedf595.png)

**Comment by mazameli** [comment]
@attekei, do I seem to recall this was fixed in the Binning branch?

**Comment by attekei** [comment]
I'm not sure, the issue I fixed in #5331 was actually caused by a regression in the same branch.

**Comment by mazameli** [comment]
Just tried it out, and this appears to be fixed in master.
