### ISSUE TITLE
Remappings should work on broken out fields

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#5600]
Regarding Metabase 0.25.0 new Friendlier name feature:
My tables have an `id` and a `name` field. On grouping by a foreign key, I have expected that the name would show rather than the ID since I have enabled showing `name` in Display value setting for that table.

The view is count of rows.

Expected behaviour:
Group by ID, but show names.

Actual outcome:
Group by ID, it shows IDs.

Workaround:
Group by name (given its unique), but that's inefficient as it is not indexed.

- Your browser and the version: Chrome 59.0.3071.115
- Your operating system: osX Sierra
- Your databases: MySQL
- Metabase version: 0.25.3
- Metabase hosting environment: JAR on EC2
- Metabase internal database: H2

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by lawrencedudley** [comment]
Yeah, I'm seeing this too - works in the raw view but when broken down in a bar chart it's just the ID. I think as a user I'd definitely expect the behaviour to match up.

**Comment by zaiddabaeen** [comment]
Any news on this? We've been experiencing this since ever, and no solution has come up yet :(

**Comment by berill** [comment]
It would be very good to have this working as well to help our users.

**Comment by dedman** [comment]
Isn't this a major bug? I'm just starting with Metabase but this seems like an odd bug to go unfixed in 2+ years.

**Comment by magnusfagerlund** [comment]
I am also very curious regarding the status on this. Is it in any releaseplan?

**Comment by mazameli** [comment]
Here's a visual for why this is confusing, and an explanation for what should happen instead:

In this GIF, I have my `Orders` table with a foreign key column, `Product ID`, which is remapped to show product titles. When I open up the summarization sidebar and try to group by that foreign key column within the Orders table, I'm shown the original product ID values, whereas I'd expect to see the titles. However, when I break out by the actual `ID` column in the linked `Product` table, I'm correctly shown the IDs, which matches my expectations.

![remapped-fk-breakout](https://user-images.githubusercontent.com/2223916/90694889-3d1e7280-e22e-11ea-9e81-0222c759eca8.gif)

**Comment by camsaul** [comment]
Fixed by #13202
