### ISSUE TITLE
Drill Down Report - Clickable link to clickable links with a variable

### ISSUE THREAD

**Issue by noblemavely** [metabase/metabase#5601]
Is there a way where we can have hyperlink the data output to an external URL?

Example: If I have the following data in a table
-------------------------------------------------
id   |   name   |   dob   |   number   |   email
-------------------------------------------------
1   |   noble   |  1111   |   2222221  |   nob@mavely.in
-------------------------------------------------
2   |   darshit |  1111   |   2222221  |   dar@mavely.in
-------------------------------------------------
3   |   mialn   |  1111   |   2222221  |   mil@mavely.in
-------------------------------------------------

Can I hyperlink the values in the ID column to an external link like - google.com/{{id}}

**Comment by mazameli** [comment]
One way we'd talked about doing this in the past is by adding additional functions to the custom field menu to allow things like string concatenation to enable a use case like this one. For example, `strcat("google.com/", "ID")` would create a new hyperlinked field.

**Comment by tlrobinson** [comment]
BTW there's an old PR that prototypes `concat` and some other expression functions https://github.com/metabase/metabase/pull/4047

We'd also need a way to set type of the extra column to be a URL to get it to include the link.

**Comment by manjeshpv** [comment]
I'm using google chrome extension for it which have below js code

```mysql
select concat('<a class="drilldown" target="_blank" href="https://quezx.com/candidates/', id, '">',id, '</a>') as id, name from candidates limit 1
```

```js
document
.querySelectorAll('span')
.forEach(x => {
    if(x.textContent.includes('drilldown')) {
      x.innertHTML = x.textContent.replace(/&gt;/g, '>').replace(/&lt;/g, '<');
    }
})
```

**Comment by manjeshpv** [comment]
duplicate #2791

**Comment by jornh** [comment]
I see 3 different approaches to solving this being discussed on various issues here:

* As mentioned in https://github.com/metabase/metabase/issues/5601#issuecomment-318495543 a few posts up to add the concatenation of id's through the custom field menu. *This would make the feature available to any user who is able to use the Query Builder. The downside is it has to be built and maintained for each Question it’s used in. It’s not available on ad hoc drill downs unless*

* As proposed in PR #8068 “Add basic support for formatting markdown links in table cells“. This as far as I can see either requires ETL or a database view to build the Markdown formatted link as a database field OR native SQL queries to do the concatenation. *This makes the feature available to “SQL literate” users. If it’s built through ETL or a database view it’s available for any querying user afterwards. Further cons regarding ETL/views are in OP of #8461*

* As proposed in #8461 “Associate URL templates with tables in data model”.  *This require involvement of an admin to configure once for each table. After that the navigation action would work with any query even drill downs/unsaved ad hoc queries for any user. If a link URL changes it would need to be maintained in one place only in Metabase.*

**Comment by grncdr** [comment]
thanks for tracking and summarizing these issues @jornh!

**Comment by flamber** [comment]
Closing this, since 0.35.0 introduced many [expressions](https://www.metabase.com/docs/latest/users-guide/expressions.html), so it's possible to create a Custom Column with the formula `concat("https://example.com/?id=", [my_column])`
There's also a more advanced version available in [Enterprise Edition](https://www.metabase.com/enterprise/) as [Custom Drill-through](https://www.metabase.com/docs/latest/enterprise-guide/customizing-drill-through.html)
