### ISSUE TITLE
Fields named in SQL editor transformed in column header

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#5603]
I've got an SQL query that names the column `Last Week ASSD`, which is an acronym that my company uses. However, Metabase 0.25.0 shows that as `Last Week As Sd`.

I believe that Metabase shouldn't rename `ASSD` into `As Sd`.

This only started happening starting 0.25.0.

Your browser and the version: Chrome 59.0.3071.115
Your operating system: osX Sierra
Your databases: MySQL
Metabase version: 0.25.3
Metabase hosting environment: JAR on EC2
Metabase internal database: H2

**Comment by maximilianmessing** [comment]
experiencing the same issue

v0.25.1

**Comment by camsaul** [comment]
Hi @zaiddabaeen @maximilianmessing Metabase tries to automatically make Table and Field names look a little friendly but as you're seeing the process isn't always perfect. You can disable it in the Admin Panel by setting `General` > `Friendly Table and Field Names` to `Disabled`

**Comment by camsaul** [comment]
Related: #3948

**Comment by cyberhorse** [comment]
May I suggest that one or more of the following is considered:
- if the column name has spaces, use it as is (likely that the label is already set as appropriate)
- if the column name was explicitly defined, use it as is
- if the column name contains lowercase and capitals, don't parse friendly names to the all capitals text (likely to be an acronym)

@camsaul please update this issue to feature request.

**Comment by camsaul** [comment]
Fixed by #6708

**Comment by JoaquinIbar** [comment]
In this case query is:
`#standardSQL
SELECT
  AnioMes,
  UsuariosDistintos as Usuarios, 
  Dispositivos
FROM...`

And when you do mouse over on the chart I get `Aniomes`

![image](https://user-images.githubusercontent.com/2813344/35781878-7bff3b00-09ce-11e8-8070-b44a736a0c89.png)

**Comment by zaiddabaeen** [comment]
@JoaquinIbar I'd have to disagree with you on this, since by the naming conventions your fields _should_ be snake cased for SQL, **but this is not official**.

(Also, they should be singular)
