### ISSUE TITLE
 How to do Month vs Month , Q1 of 2015 vs Q1 of 2016 comparisons ? 

### ISSUE THREAD

**Issue by shyam2794** [metabase/metabase#5606]
1. I would like to do the comparisons between the current month vs last month , Q1 of this year vs previous year etc . what i can see that we can create individual questions and add them together in the Dashboard . But it will be helpfull if there is a filtering options to choose the quarter alone ( something like filtering Q1 will give all the Q1's across different years similarly for months too ) .
2. I hope this problem arises as we can apply one filter at a time like either Q1,2016 or Q1,2017 . Is there anyway possible to do mutiselect in a filter values . 

![screenshot from 2017-07-27 19-17-07](https://user-images.githubusercontent.com/30238125/28673480-4014bb3e-7300-11e7-8365-8f729e31e79e.png)

 Also i was able to see the multiselect in the questions Filter , where there is a option to check the values (check boxes) . It will be helpfull if the same is provided in the Dashboard . 

 **In Dashboard** 
![screenshot from 2017-07-27 19-13-06](https://user-images.githubusercontent.com/30238125/28673243-b48de112-72ff-11e7-800c-1d7144848c1d.png)

**In Questions Builder**
![screenshot from 2017-07-27 19-12-39](https://user-images.githubusercontent.com/30238125/28673231-ada7ce9e-72ff-11e7-800b-dd39bd751085.png)
 
:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
we're working on something for this, though not in the Query Builder.

**Comment by salsakran** [comment]
check out X-Rays in release 0.26 when it comes out!

**Comment by lkraav** [comment]
Is this issue for the same thing as https://discourse.metabase.com/t/this-month-vs-last-month-graph/666

**Comment by rodrideme** [comment]
+1

**Comment by mazameli** [comment]
@rodrideme To make sure we record your support for this issue, please click on the thumbs-up 👍 button in the issue description. Writing a "+1" comment will not get factored into our issue prioritization and unnecessarily sends a notification to all followers of this issue. Thanks.

**Comment by sbelak** [comment]
If you are only interested in current period versus some past, there's also smart numbers: https://www.metabase.com/blog/0.31/

**Comment by rodrideme** [comment]
@mazameli my bad, sorry

@sbelak thank you I created one, check it out
https://powertic.com/wp-content/uploads/2019/12/graph-produto.jpg

I just need that feature to use Mautic with Metabase to create a Hubspot report style like that https://i.pinimg.com/originals/8c/4e/72/8c4e72d3d5bc5e1c2a985d48007a89ac.jpg

**Comment by that0n3guy** [comment]
@rodrideme How did you do "engaged leads" in your `graph-produto.jpg` above

**Comment by flamber** [comment]
@that0n3guy 
That's funnel: https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#funnel
Also see https://discourse.metabase.com/t/how-to-make-a-funnel-chart/5751
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
