### ISSUE TITLE
Metabase is REALLY Slow after 0.25.0 update

### ISSUE THREAD

**Issue by sabino** [metabase/metabase#5607]
### Bug
- Your browser and the version: Chrome 58.0.3029.110 (64-bit)
- Your operating system: Manjaro 17.0.2
- Your databases: Postgres
- Metabase version: 0.25.0
- Metabase hosting environment: Linux/Ubuntu 12 + Docker
- Metabase internal database: Postgres

Hi there.
Yesterday we've updated our metabase from 0.24 to 0.25 but we are struggling with a really slow UI.

We've checked the server and the CPU usage doesn't get passed 10%.
The problem looks to be on the client side since it just hangs for quite a while before the dashboards starts loading and the mouse focus gets any response (you can see in the video that the other links are not highlighted by the mouse cursor). Looks like some hungry iteration or something.

Here is a video to show.
![slow_dashboards](https://user-images.githubusercontent.com/982190/28673920-42790c18-72ba-11e7-83a7-65a46e0c4f61.gif)

While I was preparing things I've tried to open another dashboard and this happened, I don't know if this is related:
```
app-main.bundle.js:205855 RangeError: Maximum call stack size exceeded
    at h._updateDOMProperties (inflection.js?8c97:1)
    at h.updateComponent (inflection.js?8c97:1)
    at h.receiveComponent (inflection.js?8c97:1)
    at Object.receiveComponent (isEventSupported.js?cc9e:11)
    at d._updateRenderedComponent (inflection.js?8c97:1)
    at d._performComponentUpdate (inflection.js?8c97:1)
    at d.updateComponent (inflection.js?8c97:1)
    at d.receiveComponent (inflection.js?8c97:1)
    at Object.receiveComponent (isEventSupported.js?cc9e:11)
    at d._updateRenderedComponent (inflection.js?8c97:1)
    at d._performComponentUpdate (inflection.js?8c97:1)
    at d.updateComponent (inflection.js?8c97:1)
```
![download](https://user-images.githubusercontent.com/982190/28674292-614f53c6-72bb-11e7-952a-07693d67a555.png)

**Comment by sabino** [comment]
There is deffinetly something very wrong. The browser just hangs. It is happening to all of our users.

You can check in the performance graphs that the JS Heap, Nodes and Listeners are going really high. Looks like its loading more information than necessary.

![freezing_browser](https://user-images.githubusercontent.com/982190/28783454-c6755826-75e6-11e7-8aee-452aa2234025.png)

**Comment by salsakran** [comment]
That's ... not great. 

@sabino how many saved questions do you hav eon that instance?

**Comment by sabino** [comment]
1490

**Comment by salsakran** [comment]
I'm guessing it's due to the nested queries being in the big metadata blob we send back. 

@camsaul @attekei @tlrobinson we're going to need to break up the big metadata blob into more bite-sized chunks. 

@camsaul we should probably quickly add a `Nested Queries Enabled` admin setting to both check whether that's the source of the performance hit, and if it is, let @sabino get back to doing things other than staring at our loading indicators.

**Comment by camsaul** [comment]
@sabino we've got a temporary workaround for your issue in #5644. We can send you a build with the fix. Does a JAR work for you, or do you need some other sort of build artifact?

**Comment by sabino** [comment]
@camsaul thanks!
I can apply the patch
We already have a deploy process around metabase

**Comment by camsaul** [comment]
@sabino awesome. We added a setting in the Admin Panel under "General" called "Enable Nested Queries". Setting that to "Disabled" should fix your performance issues.

**Comment by sabino** [comment]
@salsakran @camsaul 
The performance issue is still happening. The browser freezes and become unresponsive for a while. Is there anything I can do to help you guys check the reason?
Thank you!

**Comment by camsaul** [comment]
@sabino did you set "Enable Nested Queries" to "Disabled"?

**Comment by sabino** [comment]
Yep, it is off
![nested-off](https://user-images.githubusercontent.com/982190/28795468-583521f0-7610-11e7-9b9e-1a151e3afe10.png)

**Comment by camsaul** [comment]
Hmm. Try hitting refresh in your browser? The metadata used in the query builder is cached so the nested query stuff that we think is slowing your browser down could still be there.

**Comment by salsakran** [comment]
One thing to note is that the dashboard detail page doesn't pull down the entire collection of database metadata. It seems to just pull down those needed for the dashboard. 

Hmm. 

@sabino how many cards are in the dashboard, and do you have a single or multiple databases? Nested-queries was the main change, and the first thing we wanted to check.

Also, is the dashboard you're pulling up have any dashboard filters?

**Comment by salsakran** [comment]
a screenshot of the network pane of the debug tools would also be helpful

**Comment by sabino** [comment]
Almost every dashboard is having the same issue.
This test was made using a dashboard with 9 cards, they query pg specific tables for monitoring so the queries are pretty fast.

![performance-tab](https://user-images.githubusercontent.com/982190/28796648-beda5084-7614-11e7-8848-238d31f11e41.png)
![network-tab](https://user-images.githubusercontent.com/982190/28796737-131a9ec4-7615-11e7-83ee-104dd2284c42.png)

Even when clicking cards it is taking quite some time to load. When I click any card this screen sits there for a while.
![load](https://user-images.githubusercontent.com/982190/28796835-76186dda-7615-11e7-9e7a-a3aeb0990a6c.png)

**Comment by camsaul** [comment]
Those metadata responses are huge (`GET /api/database/5/metadata` is 3.6 MB) 🙀 

I confirmed the backend code for that endpoint hasn't changed recently. @metabase/core-developers did something change on the frontend? (Maybe now it's blocking waiting for the endpoint return whereas it wasn't before?)

**Comment by camsaul** [comment]
Do we need to block loading a dashboard while we fetch Metadata? Do we even need to be fetching DB metadata for a dashboard? 

Queries come back with metadata...

**Comment by salsakran** [comment]
It looks like we're taking ~4 and 5 seconds to load the metadata of databases 24 and 5 respectively. 

I believe those block rendering during that entire time.

**Comment by salsakran** [comment]
I'm fairly certain we're loading that for dashboard parameters. I'm also fairly certain I'm not a fan of that codepath. Don't know it super well, but we should make it a lot more efficient imo.

**Comment by salsakran** [comment]
I also don't know if anything changed between 0.24.2 and 0.25 in this regard, though the query-lib refactor probably touched this in some way. paging @attekei =)

**Comment by attekei** [comment]
What I currently know:
- The database metadata request itself doesn't block the frontend rendering; I validated that by adding an extra delay to `fetchDatabaseMetadata`
- In https://github.com/metabase/metabase/issues/5607#issuecomment-319093017 you can see that it takes basically 60s to process the loaded metadata, and that probably blocks everything else. I'll try to identify the bottleneck next. This is likely something related to the query lib / metadata refactoring.

**Comment by sabino** [comment]
Thank you @attekei @camsaul @salsakran

Is there any possibility to go back to the 0.24.2? Or this is not possible due to migrations?

**Comment by attekei** [comment]
This is what the profiler shows for the db metadata request when loading a dashboard:

<img width="748" alt="screen shot 2017-08-01 at 9 56 41" src="https://user-images.githubusercontent.com/6034928/28836917-c40d9472-769f-11e7-8f16-f4f58e4d70e8.png">

So seems that `getHumanReadableValues` is very slow, and it's actually pretty dumb that `equivalentArgument` in `schema_metadata.js` is using it (it doesn't really need it!).

Sorry to bug you @sabino again, but if you open the Bottom-Up tab in the profiler, do you see similar method calls as in the image above?

**Comment by sabino** [comment]
@attekei 
It took quite some time to open the Bottom-Up tab but I am not able to find `schema_metadata.js`
![slow](https://user-images.githubusercontent.com/982190/28837879-c06f3ae4-76c4-11e7-8756-f9b88ec37842.png)

**Comment by salsakran** [comment]
@sabino you should be able to downgrade without any real issues, as I don't think there were any migrations that deleted or changed underlying data. (https://github.com/metabase/metabase/commits/master/resources/migrations/000_migrations.yaml) 

We, of course, strongly suggest you back up you application database whenever upgrading/downgrading/sidegrading.

**Comment by pavoooo** [comment]
@sabino we have the same terrible situation! have you already fixed it?

**Comment by sabino** [comment]
@pavoooo We did a rollback
