### ISSUE TITLE
Should we ask report timezone in setup?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5612]
The report timezone setting is currently tucked away in the General settings section of the admin panel. Though it doesn't apply to all databases, this setting seems to be responsible for fixing a number of timezone/chart problems users have been having, particularly those in Asia. [Here's an example](http://discourse.metabase.com/t/facing-a-issue-with-date-in-year-month-year-quarter/1813/3)

I don't think this setting is discoverable enough, and it's not clear that this is even something a user could try to solve their timezone issues. One possible solution would be to ask users to choose their report timezone in the initial setup form, such as here:

![screen shot 2017-07-27 at 10 01 34 am](https://user-images.githubusercontent.com/2223916/28682821-28723bfc-72b3-11e7-8527-97bd4da5ced5.png)

**Comment by brunobergher** [comment]
No traction in 4 years, closing.
