### ISSUE TITLE
When you add a new database permissions graph is broken until you refresh the page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5619]
If you add a new database and head straight to the permissions graph it will show "no permissions" for *everybody* for that new database until you refresh the page. I'm guessing this is another bug that arose from caching the database metadata.

**Comment by camsaul** [comment]
I believe this is the same issue as what's being described in #4455

**Comment by attekei** [comment]
I couldn't reproduce the "No Permissions" issue but what I was able to reproduce is that the database doesn't immediately appear to the permissions list after its creation. That is addressed in #5848

**Comment by camsaul** [comment]
Fixed by #5848
