### ISSUE TITLE
Modify instead of replace default EB nginx config

### ISSUE THREAD

**Issue by senior** [metabase/metabase#5623]
Switch approaches from overwriting the Elastic Beanstalk nginx config to changing the config that Elastic Beanstalk provides. PR #5118 ended up causing problems because it asserts things about the EB setup that might not be true. In #5537 the issue was the nginx config required enhanced health monitoring and if the user didn't have it enabled (instead specifying "Basic" health monitoring) Metabase would fail to start as it didn't have the healthd log format.

Elastic Beanstalk includes the heathd log format and will add an access_log for that, but we are currently overwriting that. By switching back to modifying the config we give our users more config flexibility.

**Comment by paoliniluis** [comment]
I added this issue to the https://github.com/metabase/metabase/pull/17261 PR as tweaking NGINX is now as simple as changing the conf file and redeploying, no more piping of files (which I even think that it didn't do anything)
