### ISSUE TITLE
Adding to a Pulse a single metric table broken out by time, sorted by the metric, results in insanity

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5628]
**Original saved question. Saved as a table, sorted by count, descending:**

![screen shot 2017-07-27 at 5 25 47 pm](https://user-images.githubusercontent.com/2223916/28697468-f3a14876-72f0-11e7-9712-8ba70ef7fcaf.png)

**Pulses interprets the table this way, very creatively:**

![screen shot 2017-07-27 at 5 26 08 pm](https://user-images.githubusercontent.com/2223916/28697478-0359dde6-72f1-11e7-84ab-67b86aeadc2d.png)

The pulse logic must be confused because of the presence of the time field dimension. The expected behavior is that this would be rendered as a horizontal row / table chart, like one of these examples:

![aggregated table](https://user-images.githubusercontent.com/2223916/28697517-44bd4444-72f1-11e7-9ce8-59400e519355.png)

![area chart broken out by category](https://user-images.githubusercontent.com/2223916/28697516-44bb41c6-72f1-11e7-8ebb-b884ee4b233a.png)

**Comment by flamber** [comment]
I cannot reproduce in 0.41.1 with the new static visualization.
