### ISSUE TITLE
Bug: Timeseries is shifted for bar / line graphs

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#5629]
I don't think this is a duplicate of other time-series shift issues posted as time zone is set to GMT and the date-time values are in GMT too specifically mongo date-time objects or ISODate() objects which are always in GMT.

- Your browser and the version: Chrome 59.0
- Your operating system: Ubuntu 16.04
- Your databases: MongoDB
- Metabase version: 0.24.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*
Mongo collection containing documents like:
```
{ "value" : "5", "event_datetime" : ISODate("2017-03-01T18:55:00.206Z")},
{ "value" : "15", "event_datetime" : ISODate("2017-04-01T18:55:00.206Z")},
{ "value" : "25", "event_datetime" : ISODate("2017-05-01T18:55:00.206Z")},
{ "value" : "35", "event_datetime" : ISODate("2017-06-01T18:55:00.206Z")},
{ "value" : "45", "event_datetime" : ISODate("2017-07-01T18:55:00.206Z")},
```
Getting sum of values and grouping by event_datetime:month the results in table view:
![modified date time gap table](https://user-images.githubusercontent.com/4945922/28709731-16d33300-739f-11e7-93e1-26b5f48d7eba.png)

Line:
![modified date time gap](https://user-images.githubusercontent.com/4945922/28709755-26d56b38-739f-11e7-8dc1-368c637ee51d.png)

Bar:
![modified date time gap bar](https://user-images.githubusercontent.com/4945922/28709761-2ba621ac-739f-11e7-91fc-bfc64f083410.png)

Clearly, the data for May is being shown in April, Data for March is being shown in Feb (which has no actual data) and the last data segment (July) is being shown in June.  

-------

**Comment by anki-code** [comment]
Seems like this is the same as #4245

**Comment by camsaul** [comment]
Yeah, this is the same issue as #4245. Closing as a duplicate since that one has a lot more activity
