### ISSUE TITLE
Cyclic load dependency when only testing BQ

### ISSUE THREAD

**Issue by mnzt** [metabase/metabase#5631]
When only testing BigQuery with `ENGINES=bigquery lein test` You get a cyclic load dependency and nice big stack trace:
```
Exception in thread "main" java.lang.Exception: Cyclic load dependency: [ /metabase/test/util ]->/metabase/test/data/bigquery->/metabase/test/data/datasets->/metabase/test/data->[ /metabase/test/util ]->/metabase/publc_settings_test, compiling:(metabase/test/data/bigquery.clj:1:1)
```

This can be resolved by testing against H2 _and_ BigQuery, `ENGINES=h2,bigquery lein test`.

~I don't see this as a bug per se, but something that should be noted in the [developer's guide](https://github.com/metabase/metabase/blob/master/docs/developers-guide.md).~

I've testing running other engines (mysql, postgres, ...) separately and they seem to run tests fine. Is this a bug with the bigquery tests, or just undocumented behaviour?

**Comment by camsaul** [comment]
@mnzt this is something we should have mentioned in the Developer's Guide, so I went ahead and added a short blurb about it.

> Due to some issues with the way we've structured our test setup code, you currently always need to include `h2` in the `ENGINES` list. Thus to test something like `bigquery` you should specify `ENGINES=h2,bigquery`. Fortunately the H2 tests are fast so this should not make a noticeable difference.

Let me know if that fixes things for you.

**Comment by camsaul** [comment]
Oops. Just realized that you mentioned that you already tried that and it worked. Going to go ahead and close this out since the workaround worked for you and it's now included in the dox.
