### ISSUE TITLE
/api/dataset/* does not work with custom queries

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#5635]
When I write a query with the builder, I can download the results to any format without issues, the API responds perfectly.

When the same query is built manually (a custom SQL query), the API responds with a 404 and I cannot download anything (even csv, json or xlsx)

- Your browser and the version: Any, it happens with all browsers
- Your operating system: Any, it happens with all OSs
- Your databases: currently Redshift, not working
- Metabase version: 0.25.1
- Metabase hosting environment: Ubuntu Linux
- Metabase internal database: Postgre

- *Repeatable steps to reproduce the issue*
Build a query with the query builder, click on download and it downloads OK
Try to do a custom query with a SQL syntax, click on download, it will show "not found 404"

**Comment by camsaul** [comment]
@paoliniluis I'm not able to reproduce your issue. What API endpoint is getting called that returns the 404?

**Comment by camsaul** [comment]
@paoliniluis I'm going to go ahead and close this out since we we're able to reproduce it and haven't heard back after asking for more info since July. If you run into any more issues please let us know.
