### ISSUE TITLE
Sync refactor follow-on: reorganize sync tests

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5636]
I changed the structure of the sync code changed dramatically in #5510, but I tried to touch the sync tests as little as possible to keep the size of the PR down and make it clear that all the old tests still pass.

Once #5510 is merged it would be nice to go back and move tests around so they're in namespaces that correspond to the ones they're testing

**Comment by camsaul** [comment]
not sure how much of this is still relevant but we should still go in and make sure the sync tests are in the appropriate test namespace e.g. something that tests `metabase.sync.whatever/f` should be called somethingl like `metabase.sync.whatever-test/f-test`

**Comment by dpsutton** [comment]
closed by https://github.com/metabase/metabase/pull/13474
