### ISSUE TITLE
SQL queries with column values that are blank cause invalid metadata warning

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#5637]
Metabase: 0.25.1 
OS: MAC OS X

When I use custom expression like `sum(amount)/10` with `group by` some field get blank as there is no amount on that specific day:

`Valid array of results column metadata maps`

When I put `/10` inside of sum as `sum(amount/10)` it works but gives a warning that:

![screen shot 2017-07-29 at 3 33 51 pm](https://user-images.githubusercontent.com/6417083/28744309-5dc8207a-7473-11e7-9714-cc414df427a1.png)

This report worked in previous versions. Why is this happening? Is it because of blank values for amount in expression? Or something else?

The query I use and the error is:

![screen shot 2017-07-29 at 3 36 16 pm](https://user-images.githubusercontent.com/6417083/28744326-b4645dea-7473-11e7-9537-eaa49e2542f4.png)

I couldn't find any extra information in response returned by metabase through inspect elements.

**Comment by salsakran** [comment]
That's odd. Can you share the table result that throws up the "choose fields" screen?

**Comment by alirezastack** [comment]
@salsakran this is the result:
![screen shot 2017-08-08 at 9 52 41 am](https://user-images.githubusercontent.com/6417083/29057456-b02bc87c-7c1f-11e7-9b76-d3ff2124df3c.png)
