### ISSUE TITLE
Big points in Firefox

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#5639]
Windows 10
Chrome 59.0.3071.115:
![image](https://user-images.githubusercontent.com/1708680/28756712-6076d8b6-757c-11e7-96c8-4fc9a2eeb0a6.png)

Firefox 54.0.1:
![image](https://user-images.githubusercontent.com/1708680/28756703-45e3c09a-757c-11e7-91ca-a05a62b43fb1.png)

⬇️ Please click "like" instead of "+1" comment

**Comment by mazameli** [comment]
This appears to be fixed in Firefox version 69 (comparing it to Chrome).

![image](https://user-images.githubusercontent.com/2223916/66611113-6718fa00-eb72-11e9-9a1f-0e4e0bc6218f.png)
