### ISSUE TITLE
Password Reset Links in Emails are broken

### ISSUE THREAD

**Issue by aefcollins** [metabase/metabase#5646]
- I am the only user that currently can access our Metabase instance. I added new people to the account + sent them invitation emails
- The invited users opened the invite emails and clicked the password-reset link
- The users were redirected to an IP address that would not load (http://172.31.39.136/auth/reset_password/3_e27f632e-0173-4eca-bf5a-8bd5108e16ca)
- Additionally, when an invited user goes to our company's metabase URL, and clicks on the password reset link, they are also redirected to a page that fails to load (see screenshot below)

<img width="684" alt="screen shot 2017-07-31 at 4 30 15 pm" src="https://user-images.githubusercontent.com/20302908/28802851-90b54026-760d-11e7-8bc0-b816311b7b29.png">

Browser: Version 59.0.3071.115 (Official Build) (64-bit)
OS: Mac OS 10.12.5
Database: MySQL
Metabase version: v0.25.1
Metabase hosting environment: Elastic Beanstalk
Metabase internal database: MySQL

**Comment by ujjwal-gupta** [comment]
Is http://172.31.39.136 the base URL via which you access Metabase? If not, you can set the base URL for Metabase from Admin Panel > General > SITE URL. This parameter is used as the base path for the email invite links.

**Comment by aefcollins** [comment]
Ah yes. This fixed the issue. It had defaulted to that IP address instead
of the correct Metabase domain name (metabase.company-name.com).

**Comment by mazameli** [comment]
Closing this issue as it seems @aefcollins problem is solved.
