### ISSUE TITLE
Sync Refactor Part 1.5: Only analyze new Fields

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5647]
Follow-on to #5510. 

Add some logic, which should be pretty straightforward, to make sure we only do analysis (special type inference) for *new* Fields.

**Comment by ujjwal-gupta** [comment]
How are new fields determined? What if the type of an old field changes? Also what if an old field is removed? Will it stay on Metabase? #5292

**Comment by camsaul** [comment]
@ujjwal-gupta new fields are determined by fetching metadata from a database. If a field is no longer present in a database it is marked inactive.

**Comment by camsaul** [comment]
Implemented by #5649
