### ISSUE TITLE
Remember that one time we released the front end for something without the back end?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5653]
Somehow, the front-end UI for binning got "dark released" (cough) in 0.25. This is… less than optimal.

<img width="1040" alt="screen shot 2017-08-01 at 11 28 53 am" src="https://user-images.githubusercontent.com/2223916/28840738-cb913b24-76ac-11e7-9a15-f0d02320c292.png">

<img width="1038" alt="screen shot 2017-08-01 at 11 29 03 am" src="https://user-images.githubusercontent.com/2223916/28840739-cb93ed7e-76ac-11e7-8c5b-6773fb85bf2b.png">

**Comment by mazameli** [comment]
This will be resolved by shipping 0.26, so do we just close it now?

**Comment by camsaul** [comment]
Yeah let's close this but we should make a note of which PR # resolved this

**Comment by attekei** [comment]
Resolved by #5331
