### ISSUE TITLE
X-Ray Fields, Tables, Metrics + Segments

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5655]
An X-Ray is a user facing feature that exposes our internal fingerprints for a field, table, etc.

Worked on in #5316

**Comment by salsakran** [comment]
partially closed via #5316 

Remaining issues:
- [ ] Test Coverage for all api endpoints
- [ ] Rename `db-id` ->`field->db-id` or something similar
- [ ] Sort out naming of user  facing x-rays, the "fingerprints" that power them and if/how they are different from analysis fingerprints. We should expect one of these two internal names to change

**Comment by sbelak** [comment]
Any particular reason why we don't include the db_id in the field model like we do for other models? It seems quite wasteful to hit the db for this.

**Comment by sbelak** [comment]
done 3/4 (still needs tests for the actual api endpoints, but everything from the api border onwards is now covered), done (generalize it to work with all models), and done in #5731
