### ISSUE TITLE
We should clarify how many rows a user is downloading

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5657]
Presuming we know how many rows are in the full result of a query, we should clarify how many rows will be downloaded. Currently, several users have reported being confused about this, thinking that the _visible_ row limit is the _downloadable_ row limit. (See [this thread](https://github.com/metabase/metabase/issues/3810#issuecomment-319496554) for example.)

Here's one idea for how we could do this:

**Hover:**

![download-tooltip](https://user-images.githubusercontent.com/2223916/28850725-3842b3da-76d3-11e7-9403-88044f0463f8.png)

**Menu:**

![download-menu-highlighted](https://user-images.githubusercontent.com/2223916/28850751-58b79a5e-76d3-11e7-98ee-6ad0ac4eddea.png)

**Comment by tlrobinson** [comment]
We don't actually know how many rows it will be until we run the query without the limit, which I don't think we want to do until necessary.

**Comment by mazameli** [comment]
Got it. How do we know that "your answer has a large number of rows?" Do we have an approximate idea of the count of rows? The label could be something less specific, like, "Download all rows (about 100,000)."

**Comment by salsakran** [comment]
I believe the logic is based on whether there were exactly 2k or 10k rows, which signifies that the query probably hit the cap?
