### ISSUE TITLE
Issue in linear interpolation with single source

### ISSUE THREAD

**Issue by aldone932** [metabase/metabase#5660]
Hello,
I have an issue when i try to display the values of a query with linear interpolation.

![screen shot 2017-08-02 at 11 48 53](https://user-images.githubusercontent.com/30653516/28868113-b5de54de-7778-11e7-89c3-7ed7bda80a65.png)

The graph creates a void space between the 2 series when the value from the select query changes.

Below the graph output without the separeted values and with point markers.

![screen shot 2017-08-02 at 11 49 24](https://user-images.githubusercontent.com/30653516/28868134-c5f914ee-7778-11e7-8e0c-2bd3c8ff2e32.png)

**Comment by tlrobinson** [comment]
It's not clear to me there's actually a bug here. By default we connect all the points in a series, but you can disable that by changing the "Replace missing values with" setting in the chart settings to "Nothing" (or "Zero")

If I'm mistaken please let me know and I'll reopen it.
