### ISSUE TITLE
Is metabase-deploy now metabase-heroku?

### ISSUE THREAD

**Issue by dangold1138** [metabase/metabase#5665]
I'm trying to upgrade metabase on Heroku. It looks like the metabase-deploy repo is no longer being updated, but is instead metabase-heroku. Is that true?

**Comment by salsakran** [comment]
Metabase-deploy is still the primary place you should deploy from.

We are transitioning to a single repo for both the one-button deployer and the buildpack. 

You should use http://www.metabase.com/start/heroku.html to deploy and http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html for information about upgrading. 

Any questions as to which are the current official artifacts are found there, and we'll treat those as canonical. We experiment with new repos, etc from time to time, but you should *not* depend on anything not linked to by the website directly.

**Comment by dangold1138** [comment]
thanks @salsakran . Looks like metabase-deploy hasn't been updated with the newest release. Is that intended?
