### ISSUE TITLE
Unable to run in Docker - Error: Could not find or load main class metabase.core

### ISSUE THREAD

**Issue by GuiSim** [metabase/metabase#5670]
When running the latest Metabase Docker image I get the following error in my logs:

```
Error: Could not find or load main class metabase.core
```
Nothing else is output.

$docker --version
Docker version 1.11.2, build b9f10c9/1.11.2

$docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
metabase/metabase   latest              847bc7b2bb3f        5 days ago          244.6 MB

This is running on an AWS EC2 instance.

Running `docker run metabase/metabase:v0.24.2` works correctly.
Running `docker run metabase/metabase:v0.25.0` works correctly.
Running `docker run metabase/metabase:v0.25.1` fails with the above error.

I am unable to reproduce using the latest image on my personal Macbook running macOS.

**Comment by camsaul** [comment]
@salsakran @metabase/core-developers did we change anything in the Docker image in 0.25.1 that could be causing this?

**Comment by salsakran** [comment]
Not to my knowledge. I tried to reproduce this, but I had no problems running `latest` on my machine just now.

Which EC2 AMI, and instance type are you using? I'll try to spin up a new instance to see if I can repro it.

**Comment by GuiSim** [comment]
`docker run metabase/metabase:v0.25.2` works.

We simply went from 0.25.0 to 0.25.2, skipping 0.25.1 which we never managed to get to work.

Our Metabase is running on a `t2.small` using `Amazon Linux 2016.09`.

**Comment by mbvictoria** [comment]
Closing - fixed by upgrading to a newer version.
