### ISSUE TITLE
Dropdown filter disappears when applied to different sql-questions

### ISSUE THREAD

**Issue by Oberonhive** [metabase/metabase#5677]
Let's say we have two tables: registrations and transactions with common field "Locale". When I create a dashboard with two sql-questions with shared parameter, filter dropdown replacing to textbox without list of Locales. It's not desired behavior. When filter is applied to only one question filter dropdown is showing, but when I apply filter to both charts list of Locales disappears.

Locale is defined as Category in both tables in data model.

Is it possible to apply filter dropdown to both sql-questions with select to different tables?

![metabasebug](https://user-images.githubusercontent.com/10414629/28939750-06b69592-789b-11e7-921a-8206270b9966.gif)

**Comment by clintongwen** [comment]
Hey guys. Any update on this? This is quite an annoying issue as it now means the people using the dashboard have to manually type out the exact string.

**Comment by attekei** [comment]
@clintongwen I tried to address a similar issue in https://github.com/metabase/metabase/pull/5543, are you using 0.26.0 or newer version?

**Comment by clintongwen** [comment]
@attekei Sorry for the late reply. I'm currently using 0.27.1. The drop downs used to work, but now they don't.

**Comment by attekei** [comment]
@clintongwen Ah okay, I'll try to reproduce this when I have a chance.

**Comment by clintongwen** [comment]
Alright! Thanks a lot. Do let me know when you do. Cheers

**Comment by clintongwen** [comment]
Hi @attekei , Any update?

**Comment by clintongwen** [comment]
@attekei Hey. Whats happening with this?

**Comment by JMGGarcia** [comment]
Hello, I'm having a similar (although not exactly but maybe related?) problem. In a dashboard with two cards from two different tables, I'm applying a filter to a category (which appears in both tables). If I apply it to one, the dropdown menu appears without a problem. If I apply it to both, the correct behaviour continues. However, if I start a new sessions (e.g. through a anonymous tab) or come back later, there no longer is a dropdown menu. If I edit the filter, remove it from the second card and re-add it, the normal correct behaviour returns (but only until I start another session). Does anyone else have this problem? This seemed to be working fine before. Tested on Safari and Chrome.

**Comment by joebordes** [comment]
I am having this problem also

**Comment by alexcohaniuc** [comment]
Any updates on this ^

**Comment by fopsmark** [comment]
Hi Guys, any update on this? I'm experiencing this issue in version 0.3. Do you have and recommendations, workarounds or fixes planned? Thanks...

**Comment by pedybr** [comment]
We have the exact same problem using 0.31.2 - would be highly appreciated if this could be fixed!

**Comment by MarkRx** [comment]
Also related to #7168.

Implementation should query each field in parallel then aggregate results removing duplicates and ordering. A value should show up if it exists in at least 1 field.

**Comment by slickrock22** [comment]
I am having the same issue.  I worked hard to have the same exact field names and values in the column of two separate data sources.  Really need this fixed.

**Comment by paulrosenzweig** [comment]
I think this was resolved by #10341 which shipped with 0.32.10. I just tried to repro to confirm and no longer can.

There's a related UI "quirk" where the parameter dropdown switches between our two different styles when it's connected to the second field. I think that's ok for now, but it might indicate that we should consolidate the two dropdown styles across the app.
