### ISSUE TITLE
Cached FieldValues dissatisfaction mega-issue

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5680]
This is a compilation of the various threads related to shortcomings in our current process of caching the values of a given column, and using it in the query builder's field selectors.

In the past, we used the special_type `category` to denote either a low cardinality column, or a column the user had marked as a low cardinality column (effectively asking us to store it's values)

**How Field Values are cached:**
We perform the equivalent of a `select distinct(column)` to determine the number of distinct values (or cardinality). If this is below a certain threshold (right now 300), we store them. 

**How Field Values are used:**
* Integer field values can be treated as an enum and given human readable names
![screen shot 2017-08-03 at 4 46 08 pm](https://user-images.githubusercontent.com/107439/28948555-48fe2454-786b-11e7-8d32-91d7f281ded6.png)

* They are used to populate the dropdown on dashboard filter widgets of type `category`
![screen shot 2017-08-03 at 4 44 12 pm](https://user-images.githubusercontent.com/107439/28948518-02897f78-786b-11e7-9fcb-787d8f2615f7.png)

* In the query builder, they populate the select for IN filters
![screen shot 2017-08-03 at 4 44 45 pm](https://user-images.githubusercontent.com/107439/28948533-1b1d9600-786b-11e7-86fc-ce24313ae67c.png)

**Currently identified problems with our treatment**
1. These filter widgets are very useful, and people want to use them for columns that are fundamentally high cardinality. (eg https://github.com/metabase/metabase/issues/5323)
2. If a column goes from having 300 to 301 distinct values, then all of a sudden filter widgets "stop working" from the user's perspective
3. It is relatively expensive to re-scan for these (`select distinct` is a fairly expensive table scan), and most columns in most tables never change
4. We don't seem to be clearing old values that have disappeared (unsure, but there was discourse conversation reporting this)
5. The only way to trigger a rescan is per-DB, which exacerbates (3).
6. Coupling field value caching with the "analysis" process of doing a table scan per-field, which leads people to turning off our "in depth analysis feature" (eg, https://github.com/metabase/metabase/issues/5106#issuecomment-319941433)
7. Sometimes there are values that are incorrect, and should not be displayed in filters, eg "S.f." in place of a canonical "SF". (minor and probably OutOfScope)
8. Defining a `category` as something with fewer then 300 distinct values results in mis-classifications like #4565

**Solutions in flight:**
* Tweaked logic for which fields should have values cached:  #5381
* A search widget to prevent people from using FieldValues as a poor man's search #4241
* Mega refactor of the sync/analyze code to remove outdated assumptions and make the code more maintainable #5679

**Relevant issues for details**
 #5323, #5128, #5150, #5267, #4565, #4542

**Comment by salsakran** [comment]
One important addition to this is that I think the past (and maybe current) version of the sync code includes a row-count operation. While very fast in some databases (eg MySQL) it can be really slow in others. 

We can consider this a pseudo table fingerprint and move to analysis so that users can better control how much load we put on their data warehouse.

**Comment by salsakran** [comment]
eg https://github.com/metabase/metabase/issues/5681#issuecomment-320952394

**Comment by camsaul** [comment]
I think one of the underlying problems is that we're using MBQL to fetch distinct values for Fields. That ends up generating pretty inefficient SQL queries like this one:

```sql
SELECT $column AS $column
FROM $table
GROUP BY $column 
ORDER BY $column ASC LIMIT 301
```

WHERE we'd probably want something more like

```sql
SELECT DISTINCT $column
FROM $table
LIMIT 301
```

That alone would make things a lot more efficient

**Comment by salsakran** [comment]
pushing this on to 0.26.1 just so that we can assess how people respond to the set of changes. Hopefully their dissatisfaction will be mollified.

**Comment by camsaul** [comment]
Can this be closed now? If not, what's left to do?

**Comment by camsaul** [comment]
@salsakran what's left to do here? Anything actionable? I'll tackle it if there is

**Comment by salsakran** [comment]
Closing this for now. I think there's still a few rough patches to fix up, but we can re-open as we get more feedback.
