### ISSUE TITLE
Changing log4j through environment variables

### ISSUE THREAD

**Issue by ricardojmendez** [metabase/metabase#5684]
This is more of a question than a bug report. I may have config/code blindness by now.

Metabase's [default logging](https://github.com/metabase/metabase/blob/master/resources/log4j.properties) seems to be a very verbose debug.   We have it running from a container, deployed through terraform.

I'm setting environment variables to change these items to from DEBUG to WARN.

```
      { "name": "LOG4J_LOGGER_METABASE_DRIVER",
        "value": "${log_level_driver}" 
      },
      { "name": "LOG4J_LOGGER_METABASE_MIDDLEWARE",
        "value": "${log_level_middleware}" 
      },
      { "name": "LOG4J_LOGGER_METABASE_QUERY_PROCESSOR",
        "value": "${log_level_query_processor}" 
      },
      { "name": "LOG4J_LOGGER_METABASE_MODELS_FIELD_VALUES",
        "value": "${log_level_field_values}" 
      }
```
It doesn't seem to have an effect even after restart. Anything I could be missing? Are environment variables being disregarded for some reason?

I did find #3294, but it's unclear what the expected behavior should be here.

**Comment by camsaul** [comment]
You can configure logging any way you like by specifying a custom log4j properties file:

``` bash
java -Dlog4j.configuration=file:/path/to/custom/log4j.properties -jar metabase.jar
```

Our log4j properties file is [here](https://github.com/metabase/metabase/blob/master/resources/log4j.properties); you can use that as a starting-off point.

**Comment by camsaul** [comment]
We should add this secret knowledge to our dox somewhere

**Comment by ricardojmendez** [comment]
Thanks @camsaul - will test it on Monday.

**Comment by camsaul** [comment]
I added this info to the documentation for future reference purposes

https://github.com/metabase/metabase/blob/master/docs/operations-guide/start.md#configuring-logging-level
