### ISSUE TITLE
Sync not running on PostgreSQL (0.25.1)

### ISSUE THREAD

**Issue by epervago** [metabase/metabase#5685]
Metabase is not syncing with my databases, either new ones or existing ones. The SQL queries work great, but the builder doesn't see any of the new tables. I had configured the first database using H2, then ran the migration to store Metabase's information on PostgreSQL -- that's when the sync stopped working.

When I run a sync using the Sync button on the database detail screen, the only thing that appears in the logs is:

`08-04 15:45:44 DEBUG metabase.middleware :: POST /api/database/34/sync 200 (2 ms) (1 DB calls)`

With nothing coming after that.

Thanks!
Evgeny

P.S. Metabase is wonderful

**Comment by salsakran** [comment]
Hello Evgeny -

What do you mean by "I had configured the first database using H2, then ran the migration to store Metabase's information on PostgreSQL"? Do you mean you migrated from an H2 application database to PG using http://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres ?

**Comment by epervago** [comment]
Yes, exactly, I followed the steps on the page you linkd

**Comment by doodlebro** [comment]
I am also seeing this, but on a redshift DB.

Since upgrading I do not get refreshed tables/views in the query builder within ~4 hours as I used to see.

**Comment by camsaul** [comment]
@epervago @doodlebro are you still seeing this issue? I reworked all of our sync code for 0.26.0 so hopefully it's not still an issue in the new code.

**Comment by epervago** [comment]
Doesn’t seem to be an issue anymore. Thanks!

**Comment by camsaul** [comment]
@epervago Good to know! I'm going to go ahead and close this out. Please let us know if you run into any other issues.
