### ISSUE TITLE
Google Analytics DB queries constantly forget their aggregation type in query builder

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5687]
Often when going to a saved google analytics question, the metric/aggregation type gets dropped, showing `Choose an aggregation` instead. Hard refreshing will sometimes cause the correct aggregation to reappear.

**Comment by flamber** [comment]
This seems to have been fixed by #12595 - I saw this issue several times until this was merged.
Closing, but please comment if you're still experiencing this in 0.35.4+
