### ISSUE TITLE
Google Analytics driver missing `Unique Events` metric

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5688]
**GA:**

![screen shot 2017-08-04 at 11 16 43 am](https://user-images.githubusercontent.com/2223916/28981406-7fb63cf2-7906-11e7-9611-92a8adab47ed.png)

**Metabase:**

![screen shot 2017-08-04 at 11 17 52 am](https://user-images.githubusercontent.com/2223916/28981430-9549c70a-7906-11e7-8cda-1ffc02e6eab8.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by designandcopy** [comment]
Is there a workaround to get this metric?

**Comment by benjR** [comment]
I have the same issue with Unique Events... is there a workaround ?
I would happily use the json stuff but as there is no way to add custom filters I can't.

**Comment by FpazHn** [comment]
I can't believe this doesn't work --- it's basically a deal breaker for moving into Metabase

**Comment by camsaul** [comment]
Closing as not planned due to dropping GA support
