### ISSUE TITLE
something wrong when update version 0.24.2->0.25.1

### ISSUE THREAD

**Issue by futureio** [metabase/metabase#5697]
I am trying to upgrade my metabase from version 0.24.2 to version 0.25.1, but had some troublesome problems as follows:
1. The log output some errors, when the metadata synchronization analysis
08-07 19:55:23 WARN sync-database.analyze :: Unable to determine row count for 'table_name_xxx': null
2. Some pages have problems, such as opening the /question page took a long time to show some content
3.dashboard is still a problem, when the data is loaded, it still takes a long time to scroll the interface.
Fortunately, my old version is still running in the normal, but the new features are really attractive. Dose there anyone know how to upgrade it?

Here are some infomations.
- Your browser and the version: Chrome 59.0.3071.115
- Your operating system:  OS X 10.12.5
- Your databases:  MySQL, impala etc.
- Metabase version: 0.25.1
- Metabase hosting environment: CentOS 6.3
- Metabase internal database: MySQL

**Comment by camsaul** [comment]
Is his a dupe of the the performance things @attekei fixed?

**Comment by attekei** [comment]
I think that (2) and (3) are maybe duplicates of #5607 which was fixed as part of 0.25.2. I don't know about (1) though.

**Comment by camsaul** [comment]
That's just a warning message and not something new in 25

**Comment by attekei** [comment]
Could you @futureio try to upgrade to 0.25.2 and see if the performance problems will be gone?

**Comment by camsaul** [comment]
@futureio ?

**Comment by camsaul** [comment]
I think we can go ahead and close this since 1 is just a warning and 2+3 were fixed by #5607

**Comment by futureio** [comment]
@camsaul Thank you for your help, the above mentioned issues have been resolved by verification.
