### ISSUE TITLE
Mapping Regions With Google Analytics or "City" Data?

### ISSUE THREAD

**Issue by sharedphysics** [metabase/metabase#5700]
I'm having some trouble getting "City" fields to map properly:
![image](https://user-images.githubusercontent.com/5796884/29040294-73cce94a-7b7c-11e7-8a1a-7169d93327e1.png)

Looks like the map isn't properly reading or mapping to city fields? I.e.,
![image](https://user-images.githubusercontent.com/5796884/29040643-c2d8b77a-7b7d-11e7-80f0-67eecc69becb.png) 
![image](https://user-images.githubusercontent.com/5796884/29040657-d4b8630a-7b7d-11e7-869e-99445a0d3d99.png)
(Table view vs. How the map is looking at it).

Looks like the map is still mapping to state, not city.

My data structure: 
![image](https://user-images.githubusercontent.com/5796884/29040685-edde1a32-7b7d-11e7-9256-8f2e788025f9.png)

On a side note, mapping to state and mapping to latitutde/longitude works fine.

**Comment by salsakran** [comment]
We don't have a city map view, and it looks like you're trying to apply the city field to a US state map.

Our geojson maps (like US state or world) expect very specific abbreviations for states or countries respectively

**Comment by sharedphysics** [comment]
Ok, so the standard Metabase maps are state and Lat/Long only?

Then if I want to map to cities, I would either need to:

A) load a new map tile w/ .geojson data (which I'm getting the following error: `this.props.onRenderError is not a function` (using this data: https://raw.githubusercontent.com/mahemoff/geodata/master/cities.geojson))

or 

B) Convert all cities/zipcodes into lat/long points before querying them?

**Comment by salsakran** [comment]
state, country and lat/long.

Correct regarding your read on alternatives. We've talked about auto-encoding things in and out of lat/logs, but that's still in the conversation mode rather than any kind of firm plan aside from experiments like https://github.com/metabase/metabase/pull/4636

**Comment by sharedphysics** [comment]
Thank you, confirmed... Any idea on the 'this.props.onRenderError is not a function' error?

Also, is it possible to overlay two map datasets on each other, similar to layering two graphs on each other?

**Comment by fR0DDY** [comment]
Facing the same problem
`this.props.onRenderError is not a function`

Trying to use this json 
https://gist.githubusercontent.com/fR0DDY/588805d9e2701896c0380ab47c9ab2e5/raw/19cecdd7cd479844b4d4e79b18e9812e326bfa1b/staions.json

**Comment by EranUzan** [comment]
Same here  : 
`this.props.onRenderError is not a function`

When loading the following geoJSON : [https://raw.githubusercontent.com/yuvadm/geolocations-il/master/cities.geojson](https://raw.githubusercontent.com/yuvadm/geolocations-il/master/cities.geojson)

**Comment by camsaul** [comment]
Closing since it sounds like this was just an issue with the GeoJSON file rather than with Metabase itself
