### ISSUE TITLE
When I use a query as table ,it show the "not found" when i download the result(raw data or summary)

### ISSUE THREAD

**Issue by wugufly** [metabase/metabase#5704]
When I use a query as table ,it show the "not found" when i download the result(raw data or summary)
show as below:

![1](https://user-images.githubusercontent.com/9857840/29054729-752e41c2-7c2a-11e7-9a42-8e90756b821c.png)

![2](https://user-images.githubusercontent.com/9857840/29054792-ea7591a6-7c2a-11e7-9ea1-069143372e2c.png)

**Comment by salsakran** [comment]
what version of Metabase is this happening in?

**Comment by salsakran** [comment]
does this still occur if you save the card and try downloading again?

**Comment by wugufly** [comment]
@salsakran ,version as below:
- Metabase version: 0.25.1
- Your databases: Presto

after i saved the question and download it again. yes it works!

**Comment by flamber** [comment]
Fixed by #9872 in 0.32.6
