### ISSUE TITLE
How to restart the running metabase in ubuntu

### ISSUE THREAD

**Issue by muhammadumargroupdocs** [metabase/metabase#5708]
Hi All,

I need to get help that how we can restart the running metabase instance in ubunto. I can see the metabase.jar in the installation folder. It might be a basic question but I am new to ubuntu and metabase

Many Thanks

**Comment by mvrabel** [comment]
@muhammadumargroupdocs 

- I would recommend to create a systemd service.

create a file:          /etc/systemd/system/metabase.service
run:                       sudo systemctl daemon-reload
now you can use: sudo systemctl restart metabase

- Here's an example metabase.service file

[Unit]
Description=Metabase server
After=syslog.target
After=network.target

[Service]
WorkingDirectory=/opt/metabase
ExecStart=/usr/bin/java/java -jar /opt/metabase/metabase.jar
Environment=MB_JETTY_PORT=8080
User=root
Type=simple
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=metabase
SuccessExitStatus=143
TimeoutStopSec=120
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by salsakran** [comment]
@mvrabel Do you mind if we use your instructions in our documentation?

**Comment by mvrabel** [comment]
@salsakran not at all 👍 

maybe you can add:
 /usr/bin/java/java <JAVA_OPTS> -jar /opt/metabase/metabase_0.25.jar
e.g.
 /usr/bin/java/java -Xmx1g -Xms1g -jar /opt/metabase/metabase_0.25.jar

I can Imagine that few users would like set the RAM usage but aren't tech savvy enough to know how to do it.
