### ISSUE TITLE
Could metabase display total fields including the joined table's besides the original one's ?

### ISSUE THREAD

**Issue by abcfyk** [metabase/metabase#5714]
### Feature requests and proposals
Hello, guys. First of all, I would like to say: "this stuff is Sooooooo AWESOME" !

It just helped us get rid of a vicious circle of "requirement gathering -> hand made report -> requirement re-gathering ...etc". 
    But we've been confused by this:

----
**Why can't it list total fields while doing query across two tables?**
----
e.g:
table1: fieldA, fieldB, fieldC
table2: fieldC, fieldD, fieldE

**prepare**:
have table2.fieldC's type set as “Foreign Key” and associated to table1.fieldC in “AdminPanel -> DataModel -> Table2 -> fieldC – Field Settings -> Foreign Key”

**expected**: 
After select table2 as DataSource and click the "Get Answer" button, I hope I could manually select the additional fields from the table1 through the associated fieldC. So the result may looks like
    
| FieldA | FieldB | FieldC | FieldD | FieldE |
| :-----:| :----: | :----: | :----: | :----: |
| Value1 | Value2 | Value3 | Value4 | Value5 |

Thanks.

**Comment by salsakran** [comment]
thanks for the kind words!

**Comment by salsakran** [comment]
we've played around with this over the years, eg related PR #3043

**Comment by abcfyk** [comment]
Does this feature, as yet only exists in embryonic form or in progress already? @salsakran

**Comment by EvaSchreyer** [comment]
Hi, 
I use metabase v0.28.1 and there is still the issue that fields that are defined as entity or foreign key fields are hidden in the query builder and not usable for filtering. Is this ab bug and can be fixed or is this how the joining works? Thanks :)

**Comment by flamber** [comment]
Closing this, since it's now (since many versions ago) possible to add columns via [visualization Settings](https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#tables) or via [joins in the Notebook editor](https://www.metabase.com/docs/latest/users-guide/custom-questions.html).
