### ISSUE TITLE
Unable to connect to mongoDB using VPN

### ISSUE THREAD

**Issue by manishsangwan** [metabase/metabase#5715]
We are using AWS for our server instances and mlab as mongoDb database service. There is VPN peering between mlab and aws for our setup. When i provide connection credentials it times out, as expected. Is there a work around that allows metabase connection for VPNs?

**Comment by kumarz** [comment]
facing the same issue, my application is able to connect to mongoDb if its not using VPN. did you happen to find out the work around using VPN ?

**Comment by flamber** [comment]
Closing, since our SSH implementation has been upgraded several times since, and default connection timeout was raised to 10 seconds since 0.41.1
