### ISSUE TITLE
Data Reference edit mode doesn't display current string values

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5717]
This is on master (`981d700`) on Chrome. This makes correcting or slightly editing existing text extremely annoying.

**Current state:**

![screen shot 2017-08-09 at 10 10 24 am](https://user-images.githubusercontent.com/2223916/29134350-31bdfd30-7ceb-11e7-8878-701928518265.png)

**Click on edit**

![screen shot 2017-08-09 at 10 10 28 am](https://user-images.githubusercontent.com/2223916/29134407-5a27411e-7ceb-11e7-9820-f0cba2782307.png)

**Put in some new text and save**

![screen shot 2017-08-09 at 10 10 33 am](https://user-images.githubusercontent.com/2223916/29134419-670393a6-7ceb-11e7-8b76-4f2bc79fb859.png)

**Changes get pushed correctly**

![screen shot 2017-08-09 at 10 10 38 am](https://user-images.githubusercontent.com/2223916/29134437-7668837e-7ceb-11e7-938a-5efea589242a.png)

**But trying to edit again shows same blank boxes**

![screen shot 2017-08-09 at 10 10 28 am](https://user-images.githubusercontent.com/2223916/29134469-90696d06-7ceb-11e7-88da-957bba90cf6d.png)

**Comment by attekei** [comment]
Also mentioned in https://github.com/metabase/metabase/pull/5354#issuecomment-313804220

**Comment by camsaul** [comment]
@mazameli does this affect other databases as well?

**Comment by mazameli** [comment]
Sorry, brain fart. Meant to say "Data Reference edit mode." Will change.
