### ISSUE TITLE
Field Filter dropdown showing hidden tables

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#5730]
- Your browser and the version: Chrome
- Your operating system: OSX
- Your databases: RedShift
- Metabase version: 0.25.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database:Postgres

- Hidden tables are showing up in the field filter column on sql editor
![image](https://user-images.githubusercontent.com/539599/29226803-43fb928e-7e88-11e7-91dd-f598945da483.png)
![image](https://user-images.githubusercontent.com/539599/29226785-37186a2e-7e88-11e7-9a13-6ba2685083eb.png)

-------

**Comment by flamber** [comment]
Hi @infomofo 
I've reproduced your issue on 0.31.2, but if you do a browser refresh after making changes to tables, then the dropdown is not showing the hidden tables anymore.
Related to #3746 #5959
