### ISSUE TITLE
[Data Model] Confusing Same Columns Names

### ISSUE THREAD

**Issue by gahabeen** [metabase/metabase#5735]
Hi  there,

What an amazing tool you're building!
After some tests on pretty big datasets it works pretty well (on Heroku with a 1Gb RAM plan).

Version used here : **Metabase 0.25.2** 

I'm struggling a bit with de **Data Model** because I've got **lots of sub-properties which have the same name** and so it gets confusing in the **Data Model Columns part** when trying to properly set the Type for each of them.

See an example here:
![](http://i.imgur.com/kiWcANs.png)

Something cool would be to **display the path of each of them** in the description field for example?

**Comment by salsakran** [comment]
can you share the underlying schema for the fields in your collection/table?

**Comment by flamber** [comment]
Closing in favor of #9684
