### ISSUE TITLE
My contribution for running Metabase on Kubernetes

### ISSUE THREAD

**Issue by pmint93** [metabase/metabase#5736]
First, thank every one who created and contribute to Metabase, an amazing bussiness intelligence tool for analyze companies's data.

Currently I'm running Metabase on Kubernetes to analyze my company OLAP data.

By that way, I've made a helm chart for better release management here: https://github.com/kubernetes/charts/tree/master/stable/metabase

I think it's good idea to add this to docs for anyone who needed. And if you want, I can make a short document contribution too.

**Comment by salsakran** [comment]
thanks!

we'd love a doc about how to use us on Kubernetes. We don't use it internally, but would love to learn more!

**Comment by VikramTiwari** [comment]
Awesome! 👍  I have been meaning to do that for a while. This looks good.

Just as a suggestion might wanna add that metabase is not horizontally scalable as of now, hence should run just 1 replica.
related issues: https://github.com/metabase/metabase/issues/2754 https://github.com/metabase/metabase/issues/3983

**Comment by pmint93** [comment]
Yeah thanks ! I also have a note at [config file](https://github.com/kubernetes/charts/blob/master/stable/metabase/values.yaml) about horizontal scale 😀

**Comment by ms-choudhary** [comment]
@pmint93 I see that #2754 is closed in milestone `0.30`. And we're already using `v0.30.1` in the stable/metabase chart. We should be able to autoscale, right?

**Comment by thomasLeclaire** [comment]
Hi!
sounds not to be working correctly.
I basically just try to set replicas to 3 in the helm values file. 
And we have strange behavior : it sounds like when some request is done on instance1, it is instance2 who get the answer for example.. 

is anyone has a horizontal scaling working on kubernetes ?

**Comment by benjsicam** [comment]
@thomasLeclaire You might be able to use Kubernetes' Service sessionAffinity configuration to route to the same back-end. https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies

**Comment by benjsicam** [comment]
I tested Metabase Horizontal Scaling through Docker Compose.

1. Here's the Gist: https://gist.github.com/benjsicam/7a52efd0bdeaf7cba4f926999a896064
2. Here's the Youtube video: https://youtu.be/SuH2K92FOaE

**Comment by thomasLeclaire** [comment]
hi @benjsicam and thx ! have several instances like you do in your docker-compose is working yes, I currently use it but it is not a kubernetes-managed horizontal scaling with pod replicas.

**Comment by RohitR1** [comment]
> it is not a Kubernetes-managed horizontal scaling with pod replicas.

Why? What's the reason? Why it's not scaling with pod replicas?

**Comment by thomasLeclaire** [comment]
> Why? What's the reason? Why it's not scaling with pod replicas?

I didn't tested with last metabase versions. 
But at the moment of my comments : metabase was not stateless therefore replicas are not useable. It resulted into mixed answers to clients. 
SessionAffinity set to ClientIP could maybe be a solution if your clients have distinct ip (which is not my case..).

**Comment by jakwuh** [comment]
One can simply use raw k8s deployment

Example for terraform:

```
locals {
  metabase_values = {
    "MB_DB_TYPE" = "postgres",
    "MB_DB_DBNAME" = var.project_name,
    "MB_DB_PORT" = "5432",
    "MB_DB_USER" = onepassword_item.postgres.username,
    "MB_DB_PASS" = onepassword_item.postgres.password,
    "MB_DB_HOST" = "${helm_release.postgresql.name}.${helm_release.postgresql.namespace}.svc.cluster.local"
  }
}

resource "kubernetes_namespace" "metabase" {
  metadata {
    name = "metabase-ns"
  }
}

resource "kubernetes_deployment" "metabase" {
  metadata {
    name      = "metabase-deployment"
    namespace = kubernetes_namespace.metabase.metadata.0.name
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        app = "metabase"
      }
    }

    template {
      metadata {
        labels = {
          app = "metabase"
        }
      }

      spec {
        container {
          image = "metabase/metabase:latest"
          name  = "metabase"

          port {
            container_port = 3000
          }

          dynamic "env" {
            for_each = local.metabase_values
            content {
              name  = env.key
              value = env.value
            }
          }
        }
      }
    }
  }
}

resource "kubernetes_service" "metabase" {
  metadata {
    name      = "metabase-service"
    namespace = kubernetes_namespace.metabase.metadata.0.name
  }

  spec {
    type = "NodePort"

    port {
      port        = 3000
      target_port = 3000
      protocol    = "TCP"
    }

    selector = {
      app = "metabase"
    }
  }
}
```
