### ISSUE TITLE
Error filtering on time buckets on redshift.

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5741]
A count of rows by week limited to the past 30 days blows up on our redshift CI instance. 

![screen shot 2017-08-14 at 11 46 26 am](https://user-images.githubusercontent.com/107439/29286265-49c6d740-80e6-11e7-8d7d-68e0611b4e89.png)

**Comment by camsaul** [comment]
sounds like the specified types or functions aren't supported by redshift

**Comment by salsakran** [comment]
I can't seem to get any date extract filters (eg, current, this, next) to work.

**Comment by camsaul** [comment]
Weird that this is passing CI but not working here. I'll take a look

**Comment by camsaul** [comment]
@salsakran are you still seeing this on 27.1 or 28-SNAPSHOT?

I can't repro it locally

![screen shot 2017-12-08 at 4 17 37 pm](https://user-images.githubusercontent.com/1455846/33790240-641f1d0c-dc33-11e7-89b5-8d9144029c03.png)

**Comment by camsaul** [comment]
@salsakran bump

**Comment by salsakran** [comment]
Not seeing it now. Closing.
