### ISSUE TITLE
Trying to set up Email pulse adds person twice

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5742]
This is on master.

I went to try to create an Email pulse and I used auto-complete to add myself

![screen shot 2017-08-14 at 12 11 20 pm](https://user-images.githubusercontent.com/1455846/29287282-bf7b10e8-80e9-11e7-9c9c-315b3ab5a811.png)

When I click my name *once* I get added *twice*

![screen shot 2017-08-14 at 12 11 42 pm](https://user-images.githubusercontent.com/1455846/29287290-c64cb7c8-80e9-11e7-9e46-84f9f09a9218.png)

And when I try to delete one of them I deletes both

![out](https://user-images.githubusercontent.com/1455846/29287484-7a2ce574-80ea-11e7-8283-b27fe04cabc9.gif)

I think a reasonable person would expect clicking one user only adds them once, and that adding duplicates is disallowed.

**Comment by mazameli** [comment]
I also wrote up in https://github.com/metabase/metabase/issues/6202 that hitting return/or enter in the autocomplete dropdown doesn't do anything.
