### ISSUE TITLE
Feature Request: Formatting Axis Labels

### ISSUE THREAD

**Issue by alee792** [metabase/metabase#5743]
I'm running into an issue with charts where x-axis labels are consistently overlapping due. Most commonly with dates in line and area charts, as seen below:

![image](https://user-images.githubusercontent.com/6137401/29287425-5ded4dfe-8103-11e7-8606-401002239973.png)

It would be great if there were a date format option or if the cards were responsive enough to automatically scale such that labels along the axis would disappear rather than overlap. Vertical ticks to mark data points would also help with clarity. 
-------
Version 60.0.3112.90 (Official Build) (64-bit)
Encountered with data from MSSQL, Oracle and PostGres with QueryBuilder and SQL questions.

**Comment by crsrusl** [comment]
This is definitely needed. It's not possible to read dates or produce useable graphs at the moment.

👍

**Comment by mazameli** [comment]
I have a suspicion that this has to do with the type of date/time field you're using. Can you tell me what the field/variable type is for the datetime column you're breaking out by, and also the granularity you're breaking out by (it looks like it's by day, but it's hard to tell)? I think @senior said he thought it might have to do with how [we mistakenly are appending times to fields that are actually just dates](https://github.com/metabase/metabase/issues/5563#issuecomment-321848606).

**Comment by alee792** [comment]
The field is stored as a timestamp in Postgres, and grouped by minute. All timestamps in our table are at 15 minute intervals.

**Comment by crsrusl** [comment]
Hi @mazameli  - I'm using mongodb standard mongo Date field

**Comment by mazameli** [comment]
Got it. So this actually appears to be a problem with how we're formatting axis labels when grouping by minute:

<img width="1160" alt="screen shot 2017-08-31 at 9 51 52 am" src="https://user-images.githubusercontent.com/2223916/29934980-0de141c6-8e32-11e7-8717-92fca65cbfff.png">

@tlrobinson, is this what's supposed to be happening? I.e., is this a technical issue, or is this a design oversight?

@crsrusl, just to double-check, in your scenario are you also doing a by-minute time grouping?

**Comment by crsrusl** [comment]
@mazameli yes grouping by minute also.

**Comment by tlrobinson** [comment]
I think there are a few things we can improve:

1. Better formatting of minute/hour granularities so they don't take up as much space
2. More intelligent tick label density. Currently I believe we hard-code a minimum width (`const MIN_PIXELS_PER_TICK = { x: 100, y: 32 };` in `LineAreaBarRenderer.js`), but we could adjust the density based on the actual tick label widths (since we already end up rendering the chart twice)
3. Maybe include an option for diagonal / vertical labels in cases where we don't want to hide some labels (ordinal x axis), or the label density would be too low.

**Comment by toddclucas** [comment]
Please do #3: include an option for diagonal / vertical labels .  Please? :)

**Comment by mazameli** [comment]
@toddclucas there's a design proposal for that [here](https://github.com/metabase/metabase/issues/7015) if you'd like to chime in or give us feedback.

**Comment by faisaliftikhar66** [comment]
Hi guys,

I just having problem of overlapping labels in x-axis exactly same live above pictures, can you people provide me any solution what i do to get rid from this situation ? also do let me know what changes i do in code to get rid from overlapping issue either its bar or line graph.
I am waiting of your replies.
Thank you
