### ISSUE TITLE
Values Improperly Represented in Area Chart

### ISSUE THREAD

**Issue by alee792** [metabase/metabase#5744]
When building a multi-series area chart in SQL, area charts can misrepresent the underlying data. 

I have two series: one of units (orange) and one that is a cumulative sum of units (blue). The blue cumulative line should never dip lower than the previous point because, well, it's cumulative. But the line fluctuates with the unaggregated orange line. 

This behavior is not observed when toggling the display settings.
It occurs for all display types (step, curve, line).

### Incorrectly displayed :( : 
![Incorrect Visualization](https://user-images.githubusercontent.com/6137401/29287678-4974f1fa-8104-11e7-8247-e833646686aa.png)

### Correctly displayed as a line:
![image](https://user-images.githubusercontent.com/6137401/29287730-786155b2-8104-11e7-869b-25d7984bc50c.png)

### Correctly displayed in Settings Menu:
![image](https://user-images.githubusercontent.com/6137401/29287965-0e0883c4-8105-11e7-993f-9dc44722d0a6.png)
---------------------------------------------------------------------------------
Version 60.0.3112.90 (Official Build) (64-bit)
Encountered with data from MSSQL, Oracle and PostGres with QueryBuilder and SQL questions.

**Comment by flamber** [comment]
The default behavior is to stack area visualization:
![image](https://user-images.githubusercontent.com/1447303/82842533-3bb50680-9eda-11ea-90ca-135ae4341bb0.png)
Changing it to non-stacked will display it like you want:
![image](https://user-images.githubusercontent.com/1447303/82842582-64d59700-9eda-11ea-8f01-31c4ec23ab23.png)
