### ISSUE TITLE
Add 3rd option to complete disable friendly table and field names

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#5751]
Hi guys! In the new Metabase version the column names were crushed (example below). Could you please give me workaround or make the ability to change this behavior?

I've tried to switch off "FRIENDLY TABLE AND FIELD NAMES" in settings but had no result.

Example:
![image](https://user-images.githubusercontent.com/1708680/29314751-16c6cc14-81c8-11e7-9bd1-2a992c7da2ca.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
@anki-code when you switch off "FRIENDLY TABLE AND FIELD NAMES" does it still break apart `DAU` into `Da U`? If it's off it should still just be something like `Dau`. (You'll have to run the query again when you switch it on/off)

**Comment by anki-code** [comment]
Yes, is the options is switched off `DAU` is `Dau` but is should it work for native queries?

For example, we have some more other abbreviations with days and they looks ugly (friendly names is off):
![image](https://user-images.githubusercontent.com/1708680/29329272-0161d630-81fe-11e7-860f-a365a84a1f8a.png)

**Comment by anki-code** [comment]
Yep :) When you have a field with a percent value 1-100% you don't want to name the column like a Shakespeare.

**Comment by anki-code** [comment]
So, for me this issue looks like regress not proposal. Because I had right names but now I have ugly names of columns.

**Comment by camsaul** [comment]
Giving the columns "nice" names like that is done on purpose, but there are definitely some issues with it (see #3948).

I marked this as a proposal because the fix here is to add a setting to let you disable "nice" names for SQL queries.

**Comment by salsakran** [comment]
👍  to having the friendly names actually turn all of this stuff off. It's going to get harder and harder as more languages are used to have sensible "friendliness" and we should actually make sure we aren't mangling things in a way that can't be turned off.

**Comment by camsaul** [comment]
@salsakran when you turn Friendly names off the only thing it still does it turn underscores into spaces and capitalize words, I don't think that's going to affect other languages any more negatively than it does English. Unless we're talking about a robot language where underscores are letters

**Comment by mazameli** [comment]
How hard would it be to fix this behavior? Feels like this could be a quick easy win that fits in with the theme of 0.28.

**Comment by anki-code** [comment]
> I marked this as a proposal because the fix here is to add a setting to let you disable "nice" names for SQL queries only

Ok, I'll rename the issue.

**Comment by sbelak** [comment]
Can't we just be smarter about this and not do splitting at all if we detect spaces and not uppercase tokens that are initially all caps in a mixed case string? And infer spaces could be amended to work better with abbreviations (in the mixed case setting where it's clear what's an abbreviation). 

@camsaul different languages have different capitalization rules. In Slovenian of instance capitalizing every word is wrong.

**Comment by salsakran** [comment]
I think this is a feature where we're on the wrong side of the uncanny valley, and it's probably a nightmarish amount of work to get it over.

Imo, we should be less aggressive about applying it automatically. 

It's great at simple examples in english but falls apart on a lot of datasets I've had a chance to see it in action on.

**Comment by camsaul** [comment]
I think one thing that would make a lot of people happy is just to add a 3rd option to turn off the behavior entirely which should be simple enough (as discussed in #3948)

**Comment by camsaul** [comment]
Implemented by #6708

**Comment by Gio666** [comment]
where can i disable friendly table and field names?

**Comment by myersCody** [comment]
You can find the disabled friendly table & field names in: 
Admin Panel > General > Friendly Table and Field Names.
