### ISSUE TITLE
Notify when Sync is complete

### ISSUE THREAD

**Issue by cetra3** [metabase/metabase#5764]
It would be nice if there was a way to be notified when a database sync has been completed.  Either by providing a synchronous API endpoint or other.

The Notify endpoint doesn't appear to do anything, and there is no notification on the frontend that the sync is complete.

**Comment by salsakran** [comment]
The notify endpoint is actually there to tell Metabase to schedule a sync.

**Comment by flamber** [comment]
Closing in favor of #11354
