### ISSUE TITLE
Odd behavior and slow query responses

### ISSUE THREAD

**Issue by ricardojmendez** [metabase/metabase#5765]
I'm seeing a strange behavior on Metabase queries to a PostgreSQL 9.3.14  database.

We have a dashboard which includes six queries. They vary in complexity, with the simpler one being simply a sum of all values in a column. The queries on the dashboard are uniformly slow in their response time, and normally return within 0.05 seconds of each other.

<img width="866" alt="screen shot 2017-08-17 at 15 42 29" src="https://user-images.githubusercontent.com/31263/29415377-297c3c30-8363-11e7-9b71-7e5617337bcd.png">

Neither the server that Metabase is running on nor the database itself are under any particularly heavy load.

<img width="707" alt="screen shot 2017-08-17 at 15 46 30" src="https://user-images.githubusercontent.com/31263/29415432-5660b776-8363-11e7-994a-7236636d4e9c.png">

I'm a bit at a loss as to why it would behave like this. From the outside, it would seem like all queries are waiting for a common process to complete before they return, or waiting on a common lock.  This is a read-only replica, so the latter is unlikely.

Any ideas?

**Comment by salsakran** [comment]
Do you have access to the query logs on the database server? Also, can you pull up the server logs from the metabase server and find the `query` POSTS and their timing info?

**Comment by flamber** [comment]
Closing, since there's not enough information to know what's going on. Please comment if this is still an issue and provide version info and logs.
