### ISSUE TITLE
Pulse Dependency

### ISSUE THREAD

**Issue by JasonGluck** [metabase/metabase#5768]
It would be great if we could conditionally send a pulse based on the availability of new data. 

Our data warehouse is refreshed once per day. Conditional on yesterday's date showing up in the agg table we are querying for a pulse, send the pulse. If yesterday's date does not show up in the agg table query result, do not send the pulse. In the event of a warehouse load error/failure, incomplete data would not send out.

I would imagine adding a new field "Trigger" to pulse creation could work. The trigger would be  TRUE/ FALSE  1/0 return from a SQL query. In the case of a daily warehouse load:

`
SELECT 
    COUNT(*) 
FROM agg_table
WHERE date = CURRENT_DATE()
`

If query returns true, allow pulse to be sent out at scheduled time. 

This feature could also be used to continually send pulses based on availability of new data without a specified scheduled time.

**Comment by dboek** [comment]
Could this be related to #1373 which was added to the roadmap in column 'soon'
There it's called a condition, but as long as the condition/trigger will be based on a question working with a result of true/false 1/0 should be possible.
