### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by BembelGmbH** [metabase/metabase#5769]
Running current metabase version.

When executing 
```
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"email": "email@email.com", "password": "PASSWORD"}' \
  http://URL.com:8443/api/session 
```
I am getting this response:
```
{"errors":{"username":"value must be a non-blank string."}}
```

Please help me
Thanks!

**Comment by kdoh** [comment]
Hey there @BembelGmbH. We recently changed the API to use "username" instead of email to accommodate LDAP. If you change the `email` key to `username` you should be good to go.

**Comment by BembelGmbH** [comment]
Thanks!
