### ISSUE TITLE
Support variables in Pulse/Dashboard Subscription questions

### ISSUE THREAD

**Issue by drorm** [metabase/metabase#5770]
This should mimic the interactive parameter feature: http://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html

When you add a question, if it supports parameters, there should be an additional input for each parameter. 

This way, it's easy to create a pulse for different people with different results.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by vkhattar** [comment]
Any updates on this feature ? It will def be very useful to me

**Comment by ScionOfBytes** [comment]
We have a use-case where we want to send out the same pulse template for various apps we support (parametrized on the appId field). We want to create questions that all accept an appId parameter and then add them to pulses. Further we want to copy pulses and change the appId parameter and have pulses for different apps going to different people.

**Comment by mfpinhal** [comment]
We have a use-case where we want to add the same question twice in the same pulse with different parameters.

**Comment by dlikhten** [comment]
A very common use case we have is: A question say 7 days out, 4 days out, 1 day out all variables on a single question in an email.

**Comment by SemStu** [comment]
This feature would be really helpful!

**Comment by camsaul** [comment]
See #15084 for more details on current plan for implementing

**Comment by rlotun** [comment]
closed by: https://github.com/metabase/metabase/pull/15404
