### ISSUE TITLE
Support pulse filters

### ISSUE THREAD

**Issue by drorm** [metabase/metabase#5771]
This should mimic the interactive feature: http://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html

It depends on #5770 being done first. 

This way, it's easy to create a pulse for different people with different results.

**Comment by flamber** [comment]
Dashboard Subscriptions, which was introduced in 0.38 has the ability to use define filters:
https://www.metabase.com/docs/latest/users-guide/dashboard-subscriptions.html
