### ISSUE TITLE
csv/xlsx downloads ignore table visualization settings

### ISSUE THREAD

**Issue by robokaso** [metabase/metabase#5773]
After I tweak the the table visualization settings (reordering and hiding columns) I expect the csv/xlsx/json download to be identical to the displayed table. However the downloaded files always contain all columns sorted alphabetically ignoring the desired formatting. 

- Your databases: Postgres 9.5
- Metabase version: 0.25.2
- Metabase internal database: H2

**Comment by mvrabel** [comment]
Already created an issue for it #5295

**Comment by salsakran** [comment]
dupe of #5295
