### ISSUE TITLE
Columns from joined tables do not show up inside a custom expression or custom column

### ISSUE THREAD

**Issue by goodfella1408** [metabase/metabase#5775]
- Your browser and the version: Chrome Version 59.0.3071.115
- Your operating system: OS X 10 
- Your databases: Sample Dataset on metabase
- Metabase version: Faced the same issue both on 0.24.2 & 0.25.2
- Metabase hosting environment: Mac
- Metabase internal database: H2

Columns from joined tables do not come up in a custom expression - they only come up in a normal aggregation . 
Similar issue has been reported in the forum -
http://discourse.metabase.com/t/error-groupings-not-showing-when-using-a-custom-expression-or-a-common-expression/1878

This is important for
1) Calculating ratios/percentages using columns from joined tables
2) We can give names to custom expression but not to normal aggregations -> https://github.com/metabase/metabase/issues/2725

<img width="1651" alt="screen shot 2017-08-18 at 2 12 43 pm" src="https://user-images.githubusercontent.com/8938889/29450961-6b656804-841e-11e7-8ddc-2014cc8a0aa0.png">
<img width="1653" alt="screen shot 2017-08-18 at 2 11 55 pm" src="https://user-images.githubusercontent.com/8938889/29450962-6b65c6c8-841e-11e7-8ead-597f060870b2.png">

**Comment by goodfella1408** [comment]
Is this a bug on the drivers - where they cant deal with custom expressions involving columns from multiple tables or is this only on the display . I can take a shot at fixing this if it is the latter (assuming the fix would be simpler ) .

**Comment by goodfella1408** [comment]
PFA a patch on master for fixing this . Cant push commits to bug fix branch on metabase project .Please give me the permission (user - goodfella1408) so that I can raise a PR -
git push origin issue-5775
Username for 'https://github.com': goodfella1408
Password for 'https://goodfella1408@github.com': 
remote: Permission to metabase/metabase.git denied to goodfella1408.
fatal: unable to access 'https://github.com/metabase/metabase.git/': The requested URL returned error: 403

[issue_5775.zip](https://github.com/metabase/metabase/files/1367908/issue_5775.zip)

**Comment by joevandyk** [comment]
@goodfella1408 you want to fork the metabase repo and push your change to there. Then open a pull request from the branch you made your change on.

**Comment by goodfella1408** [comment]
PR for this-
https://github.com/metabase/metabase/compare/master...goodfella1408:bug_5775?expand=1

**Comment by dinana** [comment]
Is there any update on this issue/PR?

**Comment by ElectricMonk92** [comment]
I am also Interested in an update on this issue.

**Comment by Bacto** [comment]
Hi,
I have the same problem with Metabase 0.33.0
What is strange is that at a point it worked, I got columns from join table in "custom column" but I don't know how.
I tried to reproduce it and can't find how I did it. Just before I was using Metabase 0.33.0-preview2 and maybe I created this question with this preview version but I'm not sure at all.

**Comment by Bacto** [comment]
More informations...

I've tried with the "Sample dataset".

First I make a join. Then in "Summarize" / "Basic metrics" / "Sum of...", I can select the table I want.

<img width="1329" alt="Screenshot 2019-08-22 at 11 39 51" src="https://user-images.githubusercontent.com/1188497/63504823-a3b16900-c4d2-11e9-98c2-a716a44f9c81.png">

But, if I go to "Summarize" / "Custom expression" / "Sum", I only get fields from the first table (orders) and not fields from the joined table (products).

<img width="1360" alt="Screenshot 2019-08-22 at 11 40 12" src="https://user-images.githubusercontent.com/1188497/63504821-a3b16900-c4d2-11e9-8345-4706e4b668a2.png">

The same problem occurs in with the "Custom column".

<img width="1331" alt="Screenshot 2019-08-22 at 11 44 53" src="https://user-images.githubusercontent.com/1188497/63504820-a3b16900-c4d2-11e9-8dfb-e6be97345129.png">

**Comment by mazameli** [comment]
Just reproduced this myself:

![image](https://user-images.githubusercontent.com/2223916/63964444-f3041600-ca4b-11e9-9bd0-529d9e7b7311.png)
