### ISSUE TITLE
Password reset is not working

### ISSUE THREAD

**Issue by timuric** [metabase/metabase#5776]
Every time I update metabase my credentials are purged, and the password reset is not working. 
This is the main reason I rarely manage to use metabase :)

Metabse version 0.25.2.0
Mac OS 10.12.6 (16G29)

[log.txt](https://github.com/metabase/metabase/files/1234392/log.txt)

![image](https://user-images.githubusercontent.com/4006792/29458535-efc9ce90-841f-11e7-8c2e-b6c4ab593223.png)

**Comment by camsaul** [comment]
This was actually fixed in 0.26.0, I had a duplicate issue, #5881 for fixing it. 

Fixed by #5898
