### ISSUE TITLE
Feature Request: Chart type modifier for "small multiples"

### ISSUE THREAD

**Issue by heliostatic** [metabase/metabase#5777]
Sometimes I want to view categorical data over a period of time. Currently, I use stacked bar charts for this, but that is limited to a single value on the x-axis. 

To capture trends over a time period across, for example, multiple instances of our application, I'd like to be able to view line graphs as small multiples (https://en.wikipedia.org/wiki/Small_multiple). 

This would be very valuable for some of our dashboards.

**Comment by jornh** [comment]
I like this idea with “small multiples”

The WIP PR #6840 seems related. Even though it seems to – currently – be specific to the *very* small multiple of 2. 🙂

**Comment by mazameli** [comment]
I'm going to close this issues in favor of https://github.com/metabase/metabase/issues/12396, since that one has a bit more context, and this one hasn't seen a lot of activity or upvotes since 2018.
