### ISSUE TITLE
Numeric dashboard cards ignore some formatting options when small

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5778]
If I have a number that I want to display as a percent, e.g. 2.407. I can use Metabase's chart options to multiply it by 100, reduce the number of displayed decimals, and add a % symbol suffix, like this:

![screen shot 2017-08-18 at 1 05 07 pm](https://user-images.githubusercontent.com/2223916/29475767-0a716dd4-8416-11e7-8680-e4b092c010f7.png)

The problem is, because Metabase does some … questionable … reformatting of numbers when dashboard card sizes gets small, it also drops the multiply-by reformatting, giving me a completely different and wrong result:

![screen shot 2017-08-18 at 1 05 26 pm](https://user-images.githubusercontent.com/2223916/29475781-1613b64c-8416-11e7-8c1d-fb424501acaa.png)

**Proposal: Metabase shouldn't transform numbers at all when they're small.** Just reduce their font size.

**Comment by lbalves** [comment]
That should also allow smaller blocks than 4x3, specially for number cards. Maybe an option to convert to short format or shrink font size would be great (that are cases where short formating for smaller screens is better than shrinking font size).

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/7116
