### ISSUE TITLE
Can't connect to mongodb when using docker

### ISSUE THREAD

**Issue by extraymond** [metabase/metabase#5783]
- Your browser and the version: Firefox 57
- Your operating system:Ubuntu 17.04 64bit
- Your databases: Mongodb)
- Metabase version: 2.5.2
- Metabase hosting environment:  docker
- Metabase internal database: (e.x. H2 (default)

- *Repeatable steps to reproduce the issue*

Hi! I have trouble connecting to mongodb when metabase is installed via docker.
I've tried just executing the java jar and it worked.

This is the log it gave me when failed to connect to mongo.

```
Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]
```

**Comment by jornh** [comment]
The error message you posted above contains indication that you try to connect to localhost:
```
servers=[{address=localhost:27017 
```
When something runs inside a Docker container `localhost` refers to that docker container itself. Inside the Metabase admin UI you need to user either the IP address or a DNS name representing the Mongo instance.

We have connection to both Mongo and other databases working fine with both DNS names and IP addresses.

**Comment by extraymond** [comment]
Thx for your reply, I've thus tried the instruction on thie [SO thread](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach) but still not working.

I've bind the docker eth0 ip into mongod.conf and assign the bridge ip of localhost during database setup in metabase. It  still gives me the same error with the above address assigned to what I've set up.

My environment is docker metabase + apt installed mongodb. Any further instruction would be appreciated.

**Comment by jornh** [comment]
You're welcome. Happy to see you resolved it from there 😄 

Regarding your off topic question it looks like in the sources that [db drivers have `features`](https://github.com/metabase/metabase/blob/v0.25.2/src/metabase/driver.clj#L138) and that [`expressions` isn't supported for mongodb](https://github.com/metabase/metabase/blob/v0.25.2/src/metabase/driver/mongo.clj#L214). That matches with what I experience on Metabase 24.2 here.

**Comment by extraymond** [comment]
Thx for the info!! Having good moments with metabase so far.

**Comment by jornh** [comment]
Excellent!

Guess you can close this issue then?

**Comment by ChaoLiou** [comment]
Hi! I am facing similar problem. 
I can connect with mongoose in node.js, can connect in browser too.(but it says "It looks like you are trying to access MongoDB over HTTP on the native driver port.")
What should I do next? thanks

```
com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=x.x.x.x:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.NoRouteToHostException: Host is unreachable (Host unreachable)}}]
```
* the x.x.x.x is not localhost
