### ISSUE TITLE
Don't show potential source Queries for DBs that don't support nested queries

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#5788]
Not sure if this is a feature request or a bug, but seems like I can't use nested queries on questions created on BigQuery. Attached screenshot.

![screen shot 2017-08-21 at 15 25 01](https://user-images.githubusercontent.com/1330677/29540760-f2af703a-8684-11e7-951f-015434eeb61c.png)

**Comment by salsakran** [comment]
@camsaul do the nested query tests run on all drivers?

**Comment by camsaul** [comment]
They run on all the databases that support nested queries. BigQuery isn't currently on that list.

This query shouldn't have been allowed, although the drill-thru button in the SQL editor doesn't do any sort of checks. (Everything else does checks and filters out DBs that aren't allowed.) @VikramTiwari did you write a SQL query and use that button to start the new query based on it? That's the only explanation

**Comment by camsaul** [comment]
IMO this is actually two separate issues:

1.  Don't present the drill-thru option in the SQL editor for questions that are ineligible (this is a known bug, we knew about this when we shipped 0.25.0, but haven't yet addressed it).
2.  Support nested queries for BigQuery. That's a feature rather than a bug. There are some weird things about BigQuery syntax that made support a little trickier than the other SQL drivers. Plus it might also make sense to switch over to standard SQL syntax (from legacy) before adding significant amounts of new logic for SQL generation.

**Comment by camsaul** [comment]
Also a 3rd thing: we should make sure we have a better error message in this situation as well

**Comment by VikramTiwari** [comment]
Here's how I did it:
- The query that I created was built using GUI query builder.
- It's the simplest query (Raw Data).
- Saved the query and it appeared in the "Saved Questions" section.
- Tried to use the question as a source which resulted in the error.

So this is a bug that any BQ based question should have never appeared in the "Saved Questions" section and a better error message. But a feature that BQ supports nested queries.

**Comment by camsaul** [comment]
Oh you're totally right. I found the reason the query is showing up when it normally wouldn't have. I will fix that in a second

**Comment by camsaul** [comment]
@VikramTiwari I've addressed the issue with the Question showing up in the first place in bugfix PR #5807. I'll open a new issue for you so we can track BigQuery support for Nested Queries

**Comment by VikramTiwari** [comment]
Awesome! Thanks 👍

**Comment by mazameli** [comment]
@VikramTiwari just a heads up that [we've just shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) which fixes this issue.

**Comment by VikramTiwari** [comment]
Confirming that this was fixed. Thanks! 👍
