### ISSUE TITLE
Oracle date operations don't account for report timezone

### ISSUE THREAD

**Issue by senior** [metabase/metabase#5789]
For Oracle, we are correctly setting the session's timezone [here](https://github.com/metabase/metabase/blob/master/src/metabase/driver/oracle.clj#L330). While working on https://github.com/metabase/metabase/pull/5729 I found the tests returning query results like a UTC only database, even though the session timezone was being set to pacific time. from reading [these docs](https://docs.oracle.com/cd/E11882_01/server.112/e10729/ch4datetime.htm#NLSPG263) I think we might need to specifically cast things to timestamps with timezones to make that timezone session setting have an affect.

The impact of this bug from a user facing perspective is dates that are off by the difference between the report-timezone and the Oracle database's clock. In my case, Oracle was UTC and the report timezone was pacific. This led to query results that were 7 hours off.

**Comment by camsaul** [comment]
I believe I fixed this but need to double-check that we have tests to confirm
