### ISSUE TITLE
time series randomly showing month tick

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#579]
can be confusing and only happens with most recent month, it looks like. occurs in prod and staging

(February '15 shows as a tick which looks like Feb 15th when data is the beginning of month) also would be great to have the OPTION to show the points

also, the line gets weirdly thin at the end of the graph.

**Comment by tlrobinson** [comment]
@agilliland Can you clarify this one? Looks like the Asana attachment is gone.

**Comment by agilliland** [comment]
Here's a similar example.  Notice how the labels are just month names until it gets to Jan where the label is the year ...

<img width="710" alt="screen shot 2016-01-27 at 11 08 58 am" src="https://cloud.githubusercontent.com/assets/1987787/12624958/70b36192-c4e6-11e5-9d8b-150107a0b6f7.png">

I'm not actually seeing the originally reported issue though and since this is an old one it's entirely likely we have addressed this at some point along the way.

The example above is SQL which means we don't have the benefit of some of the metadata, so I'm fine with closing this one if you think it's not happening any more.

**Comment by camsaul** [comment]
@tlrobinson @agilliland can we close this? A couple weeks ago it looks like A-Dawg said

> I'm fine with closing this one if you think it's not happening any more
