### ISSUE TITLE
Have to refresh page before seeing newly created Metrics

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5796]
In master. Create a new Metric in the Admin Panel, and then exit to Query Builder. New Metrics do not show up until you refresh the page.

I would assume this applies to Segments as well.

I'm guessing this is another bug with the new (ish) API response caching. It seems like we added the caching but did not add any logic to *ever* mark it dirty  😕

**Comment by ranquild** [comment]
Couldn't reproduce these 2 issues. Closing
