### ISSUE TITLE
metabase-deploy huge git repo 

### ISSUE THREAD

**Issue by guybowden** [metabase/metabase#5802]
Not sure if this is the right place to put this, but the metabase-deploy repo is only about 5 files big, yet because of the history is about 1gb in size.

Both `git clone`ing and pushing to heroku seem to require the full 900meg repo is transferred up and down.

Is there a way around this aside from copying the files into a new repo and pushing that to Heroku?

**Comment by camsaul** [comment]
@metabase/core-developers we should do something about the 1 gig repo. Do we need all the history there? Maybe we should just squash into a single commit with the latest version

Otherwise it seems the repo will continue to grow with each release and get out of control

**Comment by salsakran** [comment]
We're eventually going to move to metabase-heroku as the primary deployment repo once I have a day or two to finalize it. This will nuke the old history

**Comment by dacort** [comment]
Closing as this is an old issue and `metabase/metabase-deploy` now uses `metabase/metabase-buildpack` (https://github.com/metabase/metabase-deploy/blob/master/app.json) and repo size is manageable again.
