### ISSUE TITLE
Data Model not updating after adding new fields - MongoDB

### ISSUE THREAD

**Issue by josemontiel** [metabase/metabase#5811]
Already tried Syncing the DB but it doesn't work. No errors in logs either.

Browser: Chrome 60
OS: MacOS Sierra 10.12
DB: MongoDB 3.4
Metabase version: 0.25
Hosting: Heroku
Internal Database: default.

**Comment by salsakran** [comment]
Can you share the collection schema before and after the additional fields?

**Comment by MohGanji** [comment]
I have the same issue, same database but on Linux server.

**Comment by flamber** [comment]
Closing in favor of #5129/#10330
