### ISSUE TITLE
Sending mail with Site Name alias

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#5812]
The default `from:noreply@mydomain.com` when we received e-mails is only and e-mail, was good if we can receive the Pulse Mail or others comunications from Metabase like `from:{{site name}}<noreply@mydomain.com>` instead.

![image](https://user-images.githubusercontent.com/1447303/140926771-b3d57b09-4b52-4676-a725-9df07dc92708.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by WIlliSantos** [comment]
I have the same problem here, I would like to know if there is any prediction about this case? it would help me a lot

**Comment by rodiana** [comment]
Same problem here

**Comment by brow1998** [comment]
Me too! That would help me a lot as well

**Comment by paoliniluis** [comment]
I don't think this one was completed @dannyeuu, did you close it for some reason?

**Comment by calherries** [comment]
This was completed by https://github.com/metabase/metabase/pull/23381, but it looks like I forgot to close it.
