### ISSUE TITLE
Sending XLSX / CSV with Pulses instead only images

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#5813]
There are some issues that was previews closed, but How about send as attach files (json / xlsx / csv) too instead only images? Using the same as manual download from question data.

**Comment by Rafaelathaydemello** [comment]
Yes please - I have some regular updates I send via Slack but I have to send them in 2 different pictures! Pulses should be a bit more versatile when sending tables

**Comment by salsakran** [comment]
dupe of #2623
