### ISSUE TITLE
[Feature Request] Annotate graphs

### ISSUE THREAD

**Issue by marwann** [metabase/metabase#5815]
### Feature request : Annotate Graphs

Annotating graphs would be awesome.

![image](https://user-images.githubusercontent.com/11060074/29706584-962cceec-8982-11e7-961f-41d39d3548c1.png)

For example, I have this graph and when clicking on a specific point, I can view more detail, zoom-in, etc. I'd love to see the possibility to annotate the graph with relevant data, for example if I see a peak in traffic to my website, I'd like to write down it's because we were featured in a magazine that day.

It helps everyone understand what happens more quickly. Related issue #3221 would already be a good compromise if it looks too hard to implement.

**Comment by salsakran** [comment]
related to #3922

**Comment by flamber** [comment]
Closing in favor of #4838
