### ISSUE TITLE
Possible to time-shift relative date filters?

### ISSUE THREAD

**Issue by rsslldnphy** [metabase/metabase#5817]
Hi, I haven't been able to find an existing issue for this, and I can't find anything to this effect in the docs, so I guess this is a feature request.

It would be really useful for us to be able to filter not only by the (for eg) past 30 days, but for dates between 60 and 30 days ago - or put another way, the past 30 days, time-shifted by 30 days.

Use case: when looking at graphs of metrics that we want to improve, we usually want to compare what's happened this month to what's happened last month, on a rolling basis. I've posted an example screenshot from a graph created by Airbnb's superset, which has a similiar feature:

![image](https://user-images.githubusercontent.com/1231200/29721875-88ffef9a-89b6-11e7-8784-b529f03d9dab.png)

The solid line shows the data for the past month, the dotted line is the previous month's data overlaid on it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
One way that we're considering doing this is by having an explicit Compare action or option for metrics that have a time dimension, like "Compare to previous period."

**Comment by rsslldnphy** [comment]
That sounds great! Would make it super easy.

**Comment by vjeantet** [comment]
It could be awesome if a table result can be compared to previous time shift (add an arrow symbol :arrow_upper_right: or :are ow_lower_right:)

**Comment by pierrerigal** [comment]
We really want this too :)

Our marketing team actually consider using airbnb superset over metabase because of this. Dashboards and questions are way more interesting with data from previous period. 

As @vjeantet said, we should improve each vizualisation to integrate "growth" labels.

Other tickets linked to this one : 
- https://github.com/metabase/metabase/issues/4257
- https://github.com/metabase/metabase/issues/5606

**Comment by sbelak** [comment]
We are working on something similar (to be released in 0.26). Just to clarify, are you primarily interested in changes, or is seeing the two lines side by side a feature?

What we currently have in the works looks like this:
https://www.dropbox.com/s/rnabqe5tpswpeim/Screenshot%202017-09-05%2016.33.22.png
ie. you get a single series of relative changes (hopefully growth). This (alongside a statistical analysis and some additional visualization will be available for every card without you having to do anything).

**Comment by pierrerigal** [comment]
@sbelak It's a good start to have the info. How do you choose the compare period ? (As soon as dashboard has a date filter, you add a compare period filter ?)

Next step should be to improve how it's displayed. Hovering each data point to have the information and figure how is the trend is way less natural than having directly the second line.

**Comment by sbelak** [comment]
We infer it from the aggregation resolution you used (or try some heuristics if you used raw SQL) and try to 0-fill missing values.

The goal is for the chart to be legible enough that you can read it straight from the chart (however outliers like on the picture are an issue). We do like the time shifted view as well, so we'll probably add that too.

**Comment by pierrerigal** [comment]
@sbelak Thanks for your answer, not sure I understand how you get data from aggregation. Let's say I'm viewing my main "sales" dashboard with these cards  : 

- # of orders (big number)
- Sales in $ (big number) 
- Average cart in $ (big number)
- # of orders by days (bar chart)
- repartition of products (pie chart)

And I'm filtering on "current month" and I'm sep.6 (so data from 09.01 to 09.06)

I will have : 
- each big number with a small % representing growth (comparing with 08.01 to 08.06) (aggregation here is the period from 09.01 to 09.06 ?)
- bar chart with growth as label on each day (comparing with 08.01 to 08.06) (aggregation here is the period from 09.01 to 09.06 combined with days ?)
- repartition of product with growth as label on each parts (same)

**Comment by rsslldnphy** [comment]
I guess I'm used to seeing the two lines overlaid, rather than a growth series, so not sure which one I'd find easier to read on a day to day basis. If it helps, I'd happily put some time in this weekend on this or an equivalent feature if there are any tasks I can help out with.

**Comment by shreya0712** [comment]
"The solid line shows the data for the past month, the dotted line is the previous month's data overlaid on it."
Does anyone else find the legend (red dots for both solid and dashed lines) confusing? Is there a way we can change the legend to lines instead of dots?

**Comment by lidengke52** [comment]
We really want this too

**Comment by ngunyimacharia** [comment]
Greatly looking forward to this

**Comment by danipolo** [comment]
+1

**Comment by rcbm** [comment]
Heya, just checking in - is there any progress or updates on this issue?

**Comment by taurus227** [comment]
And for a non-plus-ultra solution look at how Superset integrated Prophet for predictive analysis:
https://preset.io/blog/2021-3-22-druid-prophet-pt3/

**Comment by camsaul** [comment]
Once we merge #42318 we can close this out

**Comment by mngr** [comment]
So we released [offset() function](https://www.metabase.com/docs/latest/questions/query-builder/expressions-list#offset) for time-over-time comparison in the .50 version.
Here is the nice video on how it works https://www.youtube.com/watch?v=LgPiQdkV4g8.
