### ISSUE TITLE
Mongodb new collection conflict

### ISSUE THREAD

**Issue by extraymond** [metabase/metabase#5820]
### Bugs

Hi! I've noticed the following endeaver.

1. If I delete a mongodb collection(table) in mongodb,  when adding a new collection with the same name as the deleted one, metabase will not be able to find the schema which ends up disallowing me to use  the query builder since there are no recognized columns in the schema.

2. If I update a column name in an already existed mongodb  collection(table), I will miss some columns. Sometimes it's not missing any column but the one altered still exists.

I'm wondering whether these are related to how metabase cache and analyse the structure of the connected database. Since after the above execution I'm having the exact expected results in  mongodb, the problem is very likely a results of how metabase log my db.

Any further investigation is appreciated.

Currently the workaround is to:
1. Not add any collection(tables) with names exists before.
2. Don't alter any column names, if must just add another database.

Currently my collection is not very large so to repeat adding datas back is acceptable, but in the foreseeable future this might become nasty.

Thx.

- Your browser and the version: Firefox Nightly
- Your operating system: Ubuntu 17.04 64bit
- Your databases: MongoDB
- Metabase version: 0.25.2
- Metabase hosting environment: Linux/Ubuntu 17.04
- Metabase internal database: default

**Comment by salsakran** [comment]
are you running a manual sync when you add columns or just waiting for the nightly one to occur? For situations where you know the schema has changed, you should probably trigger a manual re-sync.

**Comment by extraymond** [comment]
Thx for the reply, I've tried wait the sync and forced manual sync. In both cases the problem persists.
The workaround for me is to switch from H2 to postgresql. It's been alright ever since.

**Comment by flamber** [comment]
Closing, since it looks like it was a bug in H2, which is not recommended to use in production:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
