### ISSUE TITLE
Update or fix documentation about upgrading Metabase on jar file

### ISSUE THREAD

**Issue by Leoat12** [metabase/metabase#5824]
Hello,

The upgrade notification to 0.25.2 is showing for some days and I decided to upgrade today, I went to the documentation to see the right way to do it and it says this:

> Jar file
> If you are running the JVM Jar file directly, then you simply kill the process, and restart the server. On startup, Metabase will perform any upgrade tasks it needs to perform, and once it is finished, you’ll be running the new version.

I killed the process and restarted as instructed, but it didn't update, the notification to upgrade is still showing. Do I have to substitute the Jar? If so, a fix on the documentation may be necessary.

**Comment by fernandosjp** [comment]
Yes @Leoat12. You need to replace for the new .jar file and then restart the server. 

I thik maybe adding the replace step would make it clearer. What do you think?

> 
> Jar file
> If you are running the JVM Jar file directly, then you simply kill the process, **replace the .jar file with the newer version** and restart the server. On startup, Metabase will perform any upgrade tasks it needs to perform, and once it is finished, you’ll be running the new version.

**Comment by Leoat12** [comment]
Yes @fernandosjp , it would be clearer. Thanks for the answer!

**Comment by salsakran** [comment]
fixed in #5907

**Comment by salsakran** [comment]
thank you @fernandosjp for the clearer wording!
