### ISSUE TITLE
LDAP Auth issues

### ISSUE THREAD

**Issue by Nyno-Kun** [metabase/metabase#5825]
Your browser and the version: Chromium Version 57
Your operating system: Debian 9
Your databases: MySQL, PG
Metabase version: Version  v0.25.2
Metabase hosting environment: Debian 8 Jessie
Metabase internal database: H2

Hi there!
We are currently starting to use LDAP with Metabase but we encountert a Problem!
It seems that all Users that have more than one Group in LDAP that is configured to map to a group in Metabase can not login. We dont get any error in the Webbrowser. It emptys the fields and thats it.
The logs says: 
Aug 28 15:17:15 DEBUG metabase.middleware :: POST /api/session 200 (295 ms) (3 DB calls)
Aug 28 15:17:17 DEBUG metabase.middleware :: GET /api/user/current 401 (302 µs) (0 DB calls)
"Unauthenticated"

All the other Users that only have our group "mitarbeiter" (this maps to the default users in metabase) can login.

But users with the group "mitarbeiter" and for ex. "admin" (that maps to the Administrators) can not login.

**Comment by camsaul** [comment]
Hey @wwwiiilll do you have any suggestions on what we need to do to fix this? I don't have a ton of experience with LDAP

**Comment by wwwiiilll** [comment]
That's odd, we're using multiple LDAP groups just fine where I am.

@Nyno-Kun Which LDAP server are you using?
How is your directory organised and how did you set it up in MB?

**Comment by Nyno-Kun** [comment]
@wwwiiilll we are using a Univention LDAP Server. We just turned Group-Mapping off for now and its working. But we would like to use it...

In other Apps like Gitlab, Samba-Shares and Mailing via Kopano, every thing works fine.
