### ISSUE TITLE
Dates aren't formatted correctly when exported to .csv

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5828]
Reported here: http://discourse.metabase.com/t/csv-date-format/631

Expected behavior is that the date fields would contain the year, month, and day, without the time. Actual behavior looks like this:

![image](https://user-images.githubusercontent.com/2223916/29784162-e3d22fc8-8bd7-11e7-97ff-1dd0f1f03549.png)

**Comment by senior** [comment]
Caused by #5859
