### ISSUE TITLE
Double scrollbars in data selector popover

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5829]
This is on Chrome on our Stats instance:

![screen shot 2017-08-28 at 11 47 55 am](https://user-images.githubusercontent.com/2223916/29788268-d20172cc-8be6-11e7-805d-aab475f7b587.png)

**Comment by senior** [comment]
Ooops, accidentally closed the wrong ticket, reopening.

**Comment by mazameli** [comment]
Still seeing this in 0.33.5. Also seeing double scrollbars for field filter selection:

![double-scrollbar](https://user-images.githubusercontent.com/2223916/68980057-33a23e80-07b4-11ea-9f50-c6251c7d6015.png)
