### ISSUE TITLE
Rethink UX of viewing a single record's details

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5837]
Now that we have the ability to page through single records (object details), I started thinking about how our current implementation of the detail or single-record view is a little off. 

For queries that return a single record, I think we should keep doing what we're doing. But the other use case is looking at a segment or subset of not-necessarily-sequential records (in terms of their ID numbers that is), and paging through each record one at a time. This second use case doesn't really work well right now, for two reasons:
1. When clicking on a single record's ID to "view details," we run a new query (devoid of any notion of the context of the originating segment or filtered table) instead of showing a "zoomed in" view of that record. This means that if I then want to go to the "next" record, I'll be paging through _all_ the records; not just the records included in the list I had started from.
2. The current implementation of the next/previous record arrows just simple increments or decrements the ID in the filter, which of course doesn't work if the IDs aren't simple sequential integers, and also doesn't work if there are "missing" numbers (you'll get a "no results" message). 

Both of these could be solved by implementing a kind of single record zoom view, instead of running a totally new query. Sort of like opening a single row in a modal, with the ability to close it to go back to the list without re-running the list query, and allowing the user to page through the current list while in the single-record view.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Changing to bug, since it is very common now that IDs are UUID/GUID, where showing Previous/Next buttons doesn't make sense.
Some are using datetime as their primary columns, which would also be misleading.

Currently I'm almost more inclined to remove the buttons, since it only makes sense in few cases, and because I have seen way too many people clicking the Previous button, because they thought it was the "Back to results" button.

**Comment by mazameli** [comment]
> Both of these could be solved by implementing a kind of single record zoom view, instead of running a totally new query. Sort of like opening a single row in a modal, with the ability to close it to go back to the list without re-running the list query, and allowing the user to page through the current list while in the single-record view.

I still agree with myself from 4.5 years go. :laughcry:

**Comment by gdoron** [comment]
@paoliniluis @flamber we just got yet another support ticket because of this.
![image](https://user-images.githubusercontent.com/6141009/150118421-a93bbff3-48d6-4e42-9370-172fd48e6d00.png)
When can we expect it to be fixed?

**Comment by flamber** [comment]
@gdoron It has been prioritized internally.
