### ISSUE TITLE
We shouldn't show the SQL option in the new question window if a user doesn't have permission to write raw queries

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5838]
Right now if a user doesn't have permission to do so, and they click on the SQL option, they'll see the SQL editor but won't be able to interact with it:

<img width="1066" alt="screen shot 2017-08-29 at 5 03 56 pm" src="https://user-images.githubusercontent.com/2223916/29849490-12abe08c-8cdc-11e7-8138-5da07228a1d2.png">

**Comment by salsakran** [comment]
closed via #5906
