### ISSUE TITLE
If a user only has the New Question option available to them, we should jump straight to the query builder

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5839]
If there aren't any saved metrics or segments, or a user doesn't have permission to view any of them; and if the user also doesn't have permission to write raw queries, then their only option should be to create a new custom GUI query. In this scenario, we should just drop them straight into the query builder when then click New Question.

This is related to #5838, since this scenario won't occur until 5838 is fixed.

**Comment by salsakran** [comment]
closed via #5906
