### ISSUE TITLE
LDAP integration with user removal not working as expected in Metabase

### ISSUE THREAD

**Issue by matthewaquilina** [metabase/metabase#5842]
**Installed and configure latest metabase software and connected to a Microsoft AD server using LDAP  SSL.** 

Needed to remove a user from metabase. User was removed through GUI.

A few days later user was approved for access again. 

The user could not login using his account as account was not getting created, error in log was "unauthenticated".

Given this was in test mode we cleared and re-created the H2 database and user was able to connect and create account.

We migrated to MySQL to investigate the issues further as we intend to roll this out to several users for internal use.

And again user was removed from GUI and same issue persisted. User could not login and could not re-add his account.

Checking MySQL we noticed that user was not cleaned through all the tables so we executed a clean up of the user id through several tables of MySQL.

It seems issue exists in H2 and MySQL.

User was now able to login successfully. We created a script to handle user removal going forward ideally the GUI does a good cleanup once user is removed. So the user can join again if needed.

**#!/bin/bash
source /opt/metabase/connection.conf
user_id=$1
[[ -z $user_id ]] && echo "Please inform user_id to be deleted" && exit 1
mysql -u $MB_DB_USER -p$MB_DB_PASS -e "delete from metabase.activity where user_id=$user_id"
mysql -u $MB_DB_USER -p$MB_DB_PASS -e "delete from metabase.permissions_group_membership where user_id=$user_id"
mysql -u $MB_DB_USER -p$MB_DB_PASS -e "delete from metabase.core_session where user_id=$user_id"
mysql -u $MB_DB_USER -p$MB_DB_PASS -e "delete from metabase.core_user where id=$user_id"**

-------

**Comment by wwwiiilll** [comment]
This would be solved by #4936 

As a workaround you don't need to delete the user, restoring the active flag should be sufficient:
```
mysql -u $MB_DB_USER -p$MB_DB_PASS -e "UPDATE FROM metabase.core_user SET is_active = 1 WHERE id = $user_id"
```

**Comment by MarkRx** [comment]
I also encountered this. Some details in closed issue #5842.

**Comment by camsaul** [comment]
This is fundamentally the same issue as #4936 so closing as duplicate.

**Comment by identigral** [comment]
For those who attempt the same purge exercise with embedded H2 before #4936 ships, here's what I did

java -cp h2*.jar org.h2.tools.RunScript -url jdbc:h2:./metabase.db -script deleteUser.sql 

My deleteUser.sql:

delete from computation_job where creator_id=$userid;
delete from view_log where user_id=$userid;
delete from pulse_channel_recipient where user_id=$userid;
delete from revision where user_id=$userid;
delete from activity where user_id=$userid;
delete from permissions_group_membership where user_id=$userid;
delete from core_session where user_id=$userid;
delete from core_user where id=$userid;

Please note that the list of tables above is based on my usage of MB; you may need to add tables to this list.

Replace $userid with the id of the actual user. You can see users and their IDs by looking at Core_Users table
