### ISSUE TITLE
Docker `:latest` tag points to outdated version v0.24.2

### ISSUE THREAD

**Issue by mikethebeer** [metabase/metabase#5843]
`metabase/metabase:latest` pulls version `v0.24.2` instead of latest stable version.

**Comment by salsakran** [comment]
that's not what I see on https://hub.docker.com/r/metabase/metabase/tags/ 
0.24.2 is 153M while latest is 157M (like 0.25.2).

**Comment by mbvictoria** [comment]
Closed - resolved.

**Comment by camsaul** [comment]
I see v0.32.9.
