### ISSUE TITLE
Allow for multiple series on a row chart

### ISSUE THREAD

**Issue by rbhalla** [metabase/metabase#5855]
My current problem is I'd like to use a column chart but I have x axis labels being cut off. Row charts seem like the obvious choice but don't seem to support multiple series.

I would expect the functionality between the two to be very similar.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by karlrapley** [comment]
We are having exactly the same problem here. Multiple series in a Row Chart (with options to stack), would be highly beneficial.

**Comment by kconti** [comment]
Agreed.  We are in need of this feature.  This can help with turning your row chart into a pyramid chart.

**Comment by agoud1993** [comment]
@salsakran  any improvements on Row chart in the upcoming releases for building multiple series on a Row chart?

**Comment by ilizunov** [comment]
+1

**Comment by ggerade** [comment]
+1 - and wondering if anyone has done any exploratory work on this feature?

**Comment by juanalvarezamaro** [comment]
+1
