### ISSUE TITLE
color selection in pie charts

### ISSUE THREAD

**Issue by orthagh** [metabase/metabase#5857]
It would be great if pie setup permits to select colors for sections like bar charts

**Comment by rNianios** [comment]
I second this!

**Comment by ruiisidro** [comment]
This would be a great feature. I use a lot of pie charts to show OK/NOK views on logs it would be great to be able to choose red and green colors for these.

**Comment by JAC2703** [comment]
+1 to both colours and numbers (top 2 comments)

**Comment by ipeevski** [comment]
Also, what number to be shown in the middle:
- Total count (current option)
- Percentage of the top row (If there are only two rows)
- None (don't show label in the middle)

**Comment by MarkRx** [comment]
This was attempted https://github.com/metabase/metabase/pull/8541#issuecomment-426639842 but removed. The problem there was changing the coloring model resulted in sub optimal color combinations.

One idea would be to have radio/slider option to change color selection from "automatic" (uses existing color harmony model) or "manual" (allows users to assign colors to categories). Should a new category come up in manual mode the next non-used harmony color could be used. Chances are a user would go in and setup that color anyway so I wouldn't worry about that case.

@tlrobinson

**Comment by MarkRx** [comment]
This is in 0.31.2.

![image](https://user-images.githubusercontent.com/17504314/50796322-27e61180-129f-11e9-9e54-07e0b84d43b6.png)

**Comment by mazameli** [comment]
Good call, @MarkRx. Closing as implemented.
