### ISSUE TITLE
We're incorrectly appending time to Date fields that don't have an explicit time

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5859]
According to @senior, [we're using default behavior, which is giving Date fields a time of midnight](https://github.com/metabase/metabase/issues/5563#issuecomment-321848606). It's possible that this might be the root cause of issues like https://github.com/metabase/metabase/issues/4245.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
I think this also might be the root cause of #5743 as well.

**Comment by joevandyk** [comment]
This is a bit of an annoyance for us, as excel doesn't recognize dates like `2016-01-01T00:00:00.000Z`

**Comment by davidflexe** [comment]
Also having this same issue, even when casting as date. Shows in UI and csv/xlsx downloads.

**Comment by camsaul** [comment]
Is this still an issue? @flamber @mazameli

**Comment by flamber** [comment]
@camsaul Yes, it happens in multiple places like SQL, Pulses, Exports - example:
![image](https://user-images.githubusercontent.com/1447303/113122956-6b2c5200-9214-11eb-9ade-cca599b155b5.png)
