### ISSUE TITLE
Unable to delete database due to a RAW_TABLE fk reference

### ISSUE THREAD

**Issue by senior** [metabase/metabase#5866]
While trying to reproduce #5696, I found that I wasn't able to delete a database due to a foreign key reference to RAW_TABLE. That table is no longer used by Metabase, but it wasn't deleted as it would prevent users from downgrading in the event of problems with a Metabase upgrade.

Removing the foreign key is an easy workaround.

**Comment by camsaul** [comment]
Fixed by #5867
