### ISSUE TITLE
Export is not working with filter

### ISSUE THREAD

**Issue by sumputhi** [metabase/metabase#5868]
Metabase filter is working correctly, however, when export, filter simply not work, it will always export all. Please help update it.

**Comment by salsakran** [comment]
What kind of question is this, what version of MB are you on, and what is the filter?

**Comment by mvrabel** [comment]
@salsakran I think (s)he reffers to https://github.com/metabase/metabase/issues/5295 :)

**Comment by camsaul** [comment]
Sounds like a duplicate of #6407, which we fixed in 0.27.1. @sumputhi please chime in if that doesn't sound right. Closing as duplicate
