### ISSUE TITLE
Deploy Script totally broken

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5873]
Found out today both 0.25.1 and 0.25.2 were missing the EB configuration files zip in their respective S3 folders which meant our EB deployment script was completely broken for both versions. I managed to manually fix this for 0.25.2 but we seriously need to figure out what went wrong in the deploy script and how it kept running after things went south.

**Comment by salsakran** [comment]
I've audited the S3 logs and the files were correctly updated in the release process. They were then removed by a deletion event on Aug 29th.
