### ISSUE TITLE
Heroku docs reference the wrong repo

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5874]
It looks like we changed our Heroku repo from [metabase-deploy](https://github.com/metabase/metabase-deploy) to [metabase-heroku](https://github.com/metabase/metabase-heroku) but [didn't update any of the docs](http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html). Thus Heroku deployment has been mostly broken since 0.24.2. Anyone following our instructions is stuck on version 0.24.1 and upgrading is impossible.

**Comment by camsaul** [comment]
Relevant Discourse discussions:

http://discourse.metabase.com/t/trouble-upgrading-metabase-on-heroku/1823

http://discourse.metabase.com/t/update-to-0-25-2-in-heroku/1990/5

**Comment by salsakran** [comment]
The current repo for heroku deployments is `metabase-deploy`, and the buildpack is `metabase-buildpack`. Please use this, and not `metabase-heroku`
