### ISSUE TITLE
should have confirmation dialog when removing yourself as an admin

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5877]
You can remove yourself from the Admin group in the People page with a single click on the gray X button. After that you're locked out of the admin panel because you don't have permissions to see it anymore.

We should at the very least add a confirmation dialog so people can't accidentally shoot themselves in the foot so easily.

**Comment by mazameli** [comment]
This is fixed in master by the fact that you can no longer remove yourself as an admin. You can only add/remove others as admins.
