### ISSUE TITLE
Once we have internationalization (i18n), "Friendly Field Names" should take that into account

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5878]
Our "Friendly Field Names" setting currently "tries to format table and field names better by looking for common words, but it uses a word frequency list built from the English Wikipedia, which obviously won't work well for other languages," as @tlrobinson [wrote here](http://discourse.metabase.com/t/weird-spacing-of-table-and-field-names-on-v0-18/498/2).

Once we begin to support i18n, the Friendly Field Names setting should take note of which language is set as the primary language, and perhaps should be disabled unless it's set to English.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment]
Makes sense. I assume regardless of whether we detect the user's language for the frontend via the `Accept-Language` header or not we'll also have a global / default language setting we use to send out emails, pulses, and other backend stuff like this.

**Comment by siggibjarna** [comment]
I'd like to add that here in Iceland, most databases are a mix of English and Icelandic. This means that the easiest change to implement, and also the most helpful is give us the ability to "execute" the _Friendly Table and Field Names_ parser on individual tables in the Data Model Admin, even if set to _Disabled_ by default in Global Settings.

**Comment by flamber** [comment]
Closing this, since from 0.40 it will now only use "simple" instead of "advanced" - reference: #7606
