### ISSUE TITLE
Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl'

### ISSUE THREAD

**Issue by hexleyOlive** [metabase/metabase#5884]
Results of questions are not correctly visible in the pulse UI and mail / slack.
Datas and graphical are correct in the UI, but not when the question is adding in Pulse.

Some values are replaced by a strange texts: net.sourceforge.jtds.jdbc.ClobImpl@xxxxx

An example of the result in the UI:
COUNT	MyValue
**3	net.sourceforge.jtds.jdbc.ClobImpl@2d70f5c4
5	net.sourceforge.jtds.jdbc.ClobImpl@185c45b2
**

A screenshot of the trouble

<img width="588" alt="capture d ecran 2017-09-03 a 12 49 35" src="https://user-images.githubusercontent.com/8439893/30002312-62e7b2ce-90a6-11e7-9764-89e016ee6d71.png">

**Systems**
This behavior can be produced on my Mac and jar versions under windows (0.25.2.0)
Tested and can be reproduced with
System mac OS 10.12.6 (16G29)
or Windows Server 2012 R2

**Browser**
Safari Version 10.1.2 (12603.3.8) and Google Chrome Version 60.0.3112.113 (Build officiel) (64 bits).

**Database used**
MSSQL

Below the log / message during Pulse setup:

09-03 12:37:14 ←[1mDEBUG middleware.log←[0m :: ←[34m
QUERY: ?
{:database 34,
 :type "native",
 :native
 {:query
  "SET DATEFIRST 1 -- Define beginning of week as Monday\nSELECT count(distinct \"StatExportArticle__via__idLog\".\"idLog\") AS \"count\", \"StatExportArticle__via__idLog\".\"Redac
tion\" AS \"Redaction\"\nFROM \"dbo\".\"StatExportArticleErreur\"\nLEFT JOIN \"dbo\".\"StatExportArticle\" \"StatExportArticle__via__idLog\" ON \"dbo\".\"StatExportArticleErreur\".
\"idLog\" = \"StatExportArticle__via__idLog\".\"idLog\"\nwhere\n   -- Date greater than or equal to Monday of last week\n   DateExport >= dateadd(dd,((datediff(dd,'17530101',getdat
e())/7)*7)-7,'17530101')\n   and\n   -- Date before Saturday of last week\n   DateExport < dateadd(dd,((datediff(dd,'17530101',getdate())/7)*7)-0,'17530101')\nGROUP BY \"StatExport
Article__via__idLog\".\"Redaction\"\nORDER BY \"StatExportArticle__via__idLog\".\"Redaction\" ASC",
  :template_tags {}},
 :info
 {:executed-by 1,
  :context :pulse,
  :card-id 72,
  :query-hash [69, 20, 121, 55, -112, 74, -93, -114, 94, -53, -46, -68, 64, 78, 13, 43, 123, 4, -65, 47, 114, 57, -120, -17, 29, 51, 27, 18, 32, 127, 54, -114],
  :query-type "native"}}
←[0m
09-03 12:37:14 ←[1mDEBUG middleware.permissions←[0m :: ←[33mPermissions Check ? : Does user have permissions for /collection/3/read/?←[0m
09-03 12:37:14 ←[1mDEBUG middleware.permissions←[0m :: ←[32mPermissions Check ? : Yes ?  because user has permissions for /.←[0m
09-03 12:37:14 ←[1mDEBUG middleware.mbql-to-native←[0m :: ←[32mNATIVE FORM: ?
{:query
 "SET DATEFIRST 1 -- Define beginning of week as Monday\nSELECT count(distinct \"StatExportArticle__via__idLog\".\"idLog\") AS \"count\", \"StatExportArticle__via__idLog\".\"Redact
ion\" AS \"Redaction\"\nFROM \"dbo\".\"StatExportArticleErreur\"\nLEFT JOIN \"dbo\".\"StatExportArticle\" \"StatExportArticle__via__idLog\" ON \"dbo\".\"StatExportArticleErreur\".\
"idLog\" = \"StatExportArticle__via__idLog\".\"idLog\"\nwhere\n   -- Date greater than or equal to Monday of last week\n   DateExport >= dateadd(dd,((datediff(dd,'17530101',getdate
())/7)*7)-7,'17530101')\n   and\n   -- Date before Saturday of last week\n   DateExport < dateadd(dd,((datediff(dd,'17530101',getdate())/7)*7)-0,'17530101')\nGROUP BY \"StatExportA
rticle__via__idLog\".\"Redaction\"\nORDER BY \"StatExportArticle__via__idLog\".\"Redaction\" ASC",
 :template_tags {}}

←[0m
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mWARN metabase.driver←[0m :: Don't know how to map class 'class net.sourceforge.jtds.jdbc.ClobImpl' to a Field base_type, falling back to :type/*.
09-03 12:37:14 ←[1mDEBUG middleware.log←[0m :: Result Metadata:
 ←[34m({:name "count", :display_name "Count", :base_type :type/Integer} {:name "Redaction", :display_name "Redaction", :base_type :type/*})
←[0m
09-03 12:37:14 ←[1mDEBUG metabase.middleware←[0m :: ←[32mGET /api/pulse/preview_card_info/72 200 (234 ms) (7 DB calls)←[0m

**Comment by camsaul** [comment]
Closing as no longer relevant since we switched to the official Microsoft JDBC SQL Server driver so `net.sourceforge.jtds.jdbc.ClobImpl` is no longer something we can possibly encounter. @hexleyOlive if you see any more issues like this after upgrading to a newer version of Metabase please let us know.
