### ISSUE TITLE
Show percent in "Stack 100%"

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#5885]
![image](https://user-images.githubusercontent.com/1708680/30028832-4fd34cb8-918f-11e7-844c-d45678fc862e.png)

```
select 1t,1A, 2B, 3C union all
select 2, 2, 0, 0  union all
select 3, 1, 2, 3 
```

⏬ Please click the like icon instead of "+1" messages.

**Comment by kdoh** [comment]
Fixed by #5905
