### ISSUE TITLE
Dynamic week (current/previous week) filters cause SQL error on SQL Server

### ISSUE THREAD

**Issue by etcook** [metabase/metabase#5888]
### Database support

- Your browser and the version: Chrome 60.0.3112.78
- Your operating system: OSX 10.13
- Your databases: SQL Server 11.00.2100
- Metabase version: v0.25.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

When attempting to use the dynamic date filters for week (current week, previous n weeks, etc) I get a SQL error on SQL Server.

"The conversion of a date data type to a datetime data type resulted in an out-of-range value."

The column that I'm querying is in datetime. I can't seem to see the query Metabase is creating until after a succesful run, so I'm having a hard time debugging/troubleshooting.

**Comment by camsaul** [comment]
We have a big test suite around these sorts of things now so there's a good chance this is already fixed. I can't verify however without having more information. @etcook if you're still running into this please let us know. Closing as unable to repro
