### ISSUE TITLE
Feature request: Support field filters on custom fields or with saved questions

### ISSUE THREAD

**Issue by amywtlin** [metabase/metabase#5903]
Hello team and fellow Metabase users,

I've recently come across the time filter function on dashboards and that's exactly what I've been looking for, which is awesome.

I was joining 3 tables of different types of transactions and wanted to filter them by `date range` or `relative date`, but then I realized these field filters can't be used on a custom field (mine was `created_at` from 3 different tables), which is a pity. I know that I can always specify the variables separately when I join each of the 3 tables, but supporting field filters on custom fields or with saved questions will add lots of flexibility and efficiency to what SQL writers can play with data.

I might also have misunderstood how I should use it... I can get `created_at >= {{date}}` to work with `single date` filter, but don't see a way around the case I just mentioned.

**Comment by salsakran** [comment]
what do you mean by "custom field" in this situation?

**Comment by amywtlin** [comment]
Sorry for the slow response - here's an example:
```
with union_table as(
select user_id, min(created_at) as created_at from tableA group by 1
union
select user_id, min(created_at) as created_at from tableB group by 1
union
select user_id, min(created_at) as created_at from tableC group by 1)

select * from union_table
where {{field filter with created_at}}
```

I was hoping I can use `created_at` with field filter, so I can filter united data with relative date (past 30 days for example). If further clarification needed do let me know!

**Comment by flamber** [comment]
Hi @amywtlin 
Aliases are not supported with Field Filters (as of 0.31.2). Have a look at #3328 and :+1: the first post.

**Comment by flamber** [comment]
Closing in favor of #3324
Related to #4509/#3156
