### ISSUE TITLE
Switch Metabase from Joda Time to java.time

### ISSUE THREAD

**Issue by senior** [metabase/metabase#5909]
The Metabase code currently prefers to use Joda Time where we are able to, such as date parsing. There are areas where we can't use Joda Time, such as in the dates that are returned from the various JDBC drivers. This leads to some splits in the code, where a Joda Time object is expect or a JDK date/timezone object is expected which has created a bit of a mess. On top of this there are some subtle differences in how timezones are defined and handled in Joda Time vs. the older JDK code. This has led to issues like #5869.

Once we've dropped support for JDK 7, we should move over to java.time and away from Joda Time (and the older JDK date code if we can). Some investigation needs to be done on which JDBC drivers support the newer java.time code as that would also greatly reduce this incidental complexity.

**Comment by flamber** [comment]
Fixed by #11390 in 0.34.0
