### ISSUE TITLE
Azure SQL Database connection encryption

### ISSUE THREAD

**Issue by crstnmrtn** [metabase/metabase#5913]
My goal is to enable connection encryption. I've followed this [issue](https://github.com/metabase/metabase/issues/5296) which it's supposed to allow parameter addition to the connection string passed to the JDBC driver, but the extra field is missing in the Admin Panel Database settings, looking at the SQL Server driver code the encryption flag seems to default to false. The connection logs in the Azure SQL Database show though that the connection is encrypted. 
So my question is if the connection encryption is handled by the driver or when not if is possible to enable it.

- Your databases: Azure SQL Database
- Metabase version: 0.25.2
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Comment by jornh** [comment]
Since the Microsoft driver got merged in https://github.com/metabase/metabase/pull/5491 you should be able to give parameters to the JDBC driver according to https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-with-ssl-encryption 

Does that resolve this issue for you?

**Comment by crstnmrtn** [comment]
Yes, thank you.
