### ISSUE TITLE
metabase can not connect crate

### ISSUE THREAD

**Issue by daqingtian** [metabase/metabase#5914]
when i connect crate , return timeout
can metabase support cratedb ?
when i select crate, how input host ?
i use cratedb defalut config, and bind 0.0.0.0

**Comment by salsakran** [comment]
can you include more info on versions of Metabase, versions of crate, etc?
paging @mikethebeer

**Comment by mikethebeer** [comment]
@daqingtian yes, a CrateDB is included in the Metabase core.
As @salsakran already mentioned, can you provide more infos on the versions of Metabase and CrateDB that you are using. A stacktrace of your exception would also be helpful.

**Comment by camsaul** [comment]
Starting with Metabase 0.32.0 we're removing the CrateDB driver from the core Metabase project and instead making it available as a community-supported driver. You can download it and see instructions to install it here: https://github.com/metabase/crate-driver

If you're still having problems with CrateDB, please open an issue at https://github.com/metabase/crate-driver/issues
