### ISSUE TITLE
New Question results displayed with incorrect column names

### ISSUE THREAD

**Issue by aniketaranake** [metabase/metabase#5923]
- Your browser and the version: Safari Version 10.1.2 (12603.3.8), Chrome Version 60.0.3112.113 (Official Build) (64-bit)
- Your operating system: macOS Sierra 10.12.6
- Your databases: BigQuery
- Metabase version: v0.25.2 (35bce2d release-0.25.2)
- Metabase hosting environment: Ubuntu 16.04.2 LTS 
- Metabase internal database: Postgres

Today, via the Admin Tools web interface, I added a new database and connected it to a BigQuery dataset containing a table I created for this purpose. The setup appears to work properly and there are no errors.

The bug is this: When I run a New Question on this table, the results appear with incorrect column names.

Example: Among our columns on BigQuery are 'state' and 'photo1_caption'. In the result displayed on Metabase, the column with heading "Photo1 Caption" corresponds to the data that belongs to the field "state". 

Correspondingly in the log under the heading "DEBUG middleware.log :: Result Metadata:" I find the row:
{:table_id 292, :special_type :type/Category, :name "state", :source :fields, :extra_info {}, :id 4265, :visibility_type :normal, :display_name "Photo1 Caption", :base_type :type/Text}

Every column is mixed up in a similar way.

We have several datasets on BigQuery which are connected to Metabase and work properly. This bug appears to be unique to this table. The table has 48 fields all with simple datatypes (STRING, BOOLEAN, INTEGER, FLOAT).

**Comment by salsakran** [comment]
can you share the table schema so we can try to reproduce this?

**Comment by aniketaranake** [comment]
I was able to word around this problem by removing one field from the table with mode REPEATED (as opposed to the default NULLABLE). This appears to have caused the issue. I suppose repeated fields are not supported as of yet?

**Comment by JoaquinIbar** [comment]
I suggest you tu use [BigQuery Views](https://cloud.google.com/bigquery/docs/views) for BI purpouse.

If you build the view in legacySQL you will have no problem to use the `Query Builder`. If you build the view with standarSQL you will need to use `Native Query` intead.

**Comment by jeff303** [comment]
I realize this is years old, so a reproduction at this point is unlikely.  However, I believe we will be able to consider this one fixed in 41.  The changes in #17907 should make sure that the presence of `REPEATED` fields doesn't cause issues with syncing.  If we had the original table DDL, we could of course test ourselves.

**Comment by aniketaranake** [comment]
Thank you for taking the time to follow up on this thread. The table is the
property of an organization to which I no longer belong, so I will not be
able to provide it.

**Comment by jeff303** [comment]
As outlined above, we believe this should be fixed in the new BigQuery driver coming in `x.41`.
