### ISSUE TITLE
Bar chart colors shuffle when refreshing the chart in dashboard

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#5925]
I have created a dashboard with multiple charts. One of the charts is bar chart and when I refresh the dashboard with a new value each bar gets a random color as below:

![screen shot 2017-09-10 at 4 00 42 pm](https://user-images.githubusercontent.com/6417083/30248665-53c42188-9641-11e7-849e-6060265fc729.png)
![screen shot 2017-09-10 at 4 01 03 pm](https://user-images.githubusercontent.com/6417083/30248666-53c63d10-9641-11e7-841c-ac5c758255ae.png)

It seems that there are not a setting to set color for each label. Is there any workaround for this? It is very confusing.

**Comment by salsakran** [comment]
this should probably be solved via #5910

**Comment by adjenks** [comment]
This is also a problem for me. I assign colours by label but they change when the statistics change. It seems to be assigned by the order of the labels, not by the names but the order they appear in. So like in the image above by @alirezastack , the colors are always assigned in the order blue, green, purple, red.

**Comment by MarkRx** [comment]
See https://github.com/metabase/metabase/issues/5910#issuecomment-375120530
