### ISSUE TITLE
All zero-valued metrics on Line graph

### ISSUE THREAD

**Issue by northtree** [metabase/metabase#5926]
I used SQL Editor to grab data from MySQL. This Line graph shows four metrics from a sensor. In most cases, the visualization is good since it's automatically applies left y-axis range for CO2/light, and right y-axis range for motion/temperature.

![screen shot 2017-09-11 at 10 59 36 am](https://user-images.githubusercontent.com/419509/30254817-0ca92e4c-96e1-11e7-8ad7-ae0b3ca9a4a7.png)

However, when the motion metric is all zero, the right y-axis will disappear and shows motion as label. Moreover, the temperature line is unreadable since it's plotted too close to x-axis.

![screen shot 2017-09-11 at 10 59 17 am](https://user-images.githubusercontent.com/419509/30254824-1c87f6f4-96e1-11e7-9eee-1feee1d0752f.png)

My metabase version is v0.24.2.

**Comment by northtree** [comment]
@mazameli Is it a bug?

**Comment by mazameli** [comment]
This appears to be a flaw with the logic for determining the need for dual axes. I think ultimately we just need to let users force dual axes and choose which metric(s) to put on which axis.

**Comment by flamber** [comment]
A lot has changed, so besides the logic getting better, it's also possible to manually select axis.
Please comment if this is still happening, then the logic should be looked at again.
![image](https://user-images.githubusercontent.com/1447303/82761059-fddfb180-9df7-11ea-9fe2-ec3bfae0ae77.png)
