### ISSUE TITLE
Format date in calendar filter

### ISSUE THREAD

**Issue by vitorfraga** [metabase/metabase#5928]
Hello, is possible? 

![image](https://user-images.githubusercontent.com/4948363/30278399-a2e4b9d6-96e0-11e7-9b64-7ae1ed20f30d.png)

**Comment by mazameli** [comment]
This is not currently possible, but it's something we're definitely aware of as a problem for some of our users. Closing this issue as a duplicate of #3791, and related to https://github.com/metabase/metabase/issues/4827

**Comment by vvaezian** [comment]
Isn't this solved in #8620? I still see month/day/year format although I chose day-month-year in the settings.

![dateFormat](https://user-images.githubusercontent.com/15974735/54561387-c79bdc00-4981-11e9-8a8a-b5001d96e08c.png)

**Comment by flamber** [comment]
@vvaezian I think you're seeing #9079 - try messing around with Field Type or set formatting via the settings in Data Model.

**Comment by vvaezian** [comment]
@flamber Thanks for the reply. I have no problem with the format of date columns in my data (they correctly reflect what I choose in the settings). This issue is about format of date when picking date ranges in "between" date filter (as shown in the picture posted by OP).

**Comment by flamber** [comment]
@vvaezian Ahh, okay, then you should vote/follow #9151 and #9159
