### ISSUE TITLE
"Sort by" buttons in add-question-to-dashboard screen don't do anything

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5930]
[This was reported on Discourse](http://discourse.metabase.com/t/sort-by-in-questions-list-does-not-seem-to-work/2056). I reproed in Chrome on our Stats instance. The `last modified` and `alphabetical order` links don't do anything when clicked, but don't cause any JS errors. 

![screen shot 2017-09-11 at 10 21 30 am](https://user-images.githubusercontent.com/2223916/30287753-1aab7b22-96db-11e7-8a6c-8a50ab1b172e.png)

**Comment by flamber** [comment]
Hi @mazameli 
This issue is not relevant anymore, since format has completely changed and has search option. 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52906696-d3776f80-3216-11e9-8885-bf85558afd5d.png)
