### ISSUE TITLE
Improve dashboard filters adding/editing UX

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5934]
This is a "folder" issue composed of several smaller issues related to dashboard filters:

1. Adding/editing filters shouldn't be its own edit state: https://github.com/metabase/metabase/issues/5114
2. When adding a new filter, automatically map it to all cards in the dashboard: #4767 
3. Ability to change an existing filter's type: #5963
4. Simplify the way you edit a filter's label and default value: #5972
5. Rearrange the order of filters: https://github.com/metabase/metabase/issues/3238

I'll post specific designs in each of these issues, but the design that's related to each of them is this new edit state, and specifically the new look for filter widgets. They'll now have their own menu of options, making it clearer how to do different things with them: 

![filter edit](https://user-images.githubusercontent.com/2223916/30296131-f397bda8-96f7-11e7-95e4-40abef4890ec.png)

**Comment by moumny** [comment]
I would add reorder the filters (drag and drop)

**Comment by moumny** [comment]
-  "contains" filter
- IN filter / drop down with multiple options

**Comment by mazameli** [comment]
@moumny I agree on reordering filters; I've added that to the description. I explored a solution for this feature within the context of these designs, so might as well post them, too.

I think the "contains" filter and "in"/multi-select filter feature requests are fine as their own issues, since this one is strictly about filter adding/editing, but thanks for the reminder that you desire those features. 👍

**Comment by moumny** [comment]
Correct i didn't read properly, then #4767 is the most important one IMHO

**Comment by mokra** [comment]
May be at this rate, one could also add a description to filters.

**Comment by jornh** [comment]
Seeing in OP you’re calling this a “folder” issue - on the topic of dashboard filter UX maybe it’s appropriate to add here: 
* The first issue with being able to resize the filter as mentioned in 
http://discourse.metabase.com/t/dashboard-filter-and-number-of-rows/4315 to allow the filter boxes to display long values. I think it could be added as something triggered by a “resize” menu option in the first picture shown above, to not have too much state management going on

It’s probably not the *most* wanted feature, but I can imagine it’s needed when you needed. Now I found an appropriate place to mention it `/methinks`

**Comment by flamber** [comment]
Closing this, since most have been implemented in the past few major releases, and everything has changed so much that new issues should be created for any future work.
