### ISSUE TITLE
Expired strategies sometimes cause great harm

### ISSUE THREAD

**Issue by futureio** [metabase/metabase#5942]
My database sometimes produces some strange exceptions, causing the table list to return a null value (actually some of the wrong api operations are caused, and the data is still there).

At the same time, in the metabase, due to the retirement strategy, all associated with the database table and row will be permanently retired and difficult to recover (if not stop service).

This is a disaster for all saved questions and changed field comments and types (I found a lot of blank cases for saved questions).

Often, there is no one-time removal of the entire database situation, on the conditions of retirement, I think there is a better way to deal with robustness.

**Comment by salsakran** [comment]
We keep the table name around and un-retire it if the table comes back. Or at least that how things should work. Which version of Metabase are you on?

**Comment by futureio** [comment]
The current expiration strategy is catastrophic. Once the form disappears, even if it is restored as it is, all of the field descriptions in the metabase include Segments, Metrics, and Dependent Questions are none of the notifications disappearing or unavailable, which makes my heart hurt!

**Comment by flamber** [comment]
I cannot reproduce on `master` (the upcoming 0.36.0). Everything is restored, if the database is suddenly saying it's empty during one sync, and returns all the tables again in the next sync.
A lot has changed with the sync process of the past couple of years.
