### ISSUE TITLE
Cannot sort on custom and saved metrics

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#5943]
Reproduced on sample dataset on Master.

Steps
select sample dataset -> orders
select count of rows grouped by created_date/year
click on count in table header -> descending
it works
now modify count of rows and click on custome metric and put something like count*10 for eg.
click on "count *" in table header -> descending/ascending 
no effect

PS: name of the column "count*" is wierd, should be "count * 10 "

**Comment by moumny** [comment]
Ps2 same for saved metric

**Comment by senior** [comment]
I can confirm this on both 0.25.2 and on master. It looks like the custom expression that is being setup doesn't get resolved properly in the order by clause. Below is a query that was generated following similar steps to @moumny's above
```
SELECT (count(*) * 10.0) AS "count * ", year("PUBLIC"."ORDERS"."CREATED_AT") AS "CREATED_AT"
FROM "PUBLIC"."ORDERS"
GROUP BY year("PUBLIC"."ORDERS"."CREATED_AT")
ORDER BY NULL ASC, year("PUBLIC"."ORDERS"."CREATED_AT") ASC
```

**Comment by on99** [comment]
I am encountering the same issue with MySQL driver, on latest 0.33.0 preview 2 metabase.

![image](https://user-images.githubusercontent.com/13196393/61120456-9f576080-a4cf-11e9-9c19-6daf2b02664d.png)
There is no `Ascending Descending` in the indicator.

Can you please take a look? @senior Thank you so much!

**Comment by flamber** [comment]
@on99 The screenshot you're showing is not 0.33.0-preview2. Go and upvote #8283 by clicking :+1:

**Comment by on99** [comment]
@flamber Well I compiled metabase 27 days ago from master, it is a little bit different from preview 0.30 preview 2. 

I've upvoted the issue for months, but seems like no progress. 😂
