### ISSUE TITLE
New Question Pagination doesn't work properly

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5948]
When I paginate through a list of 13 metrics on the new question flow, the lists aren't correct.

Page 1
<img width="769" alt="screen shot 2017-09-12 at 3 30 29 pm" src="https://user-images.githubusercontent.com/107439/30351272-70046d0a-97cf-11e7-8644-bf1f58d0d0cc.png">

Page 2
<img width="753" alt="screen shot 2017-09-12 at 3 30 34 pm" src="https://user-images.githubusercontent.com/107439/30351269-6d337206-97cf-11e7-8d7b-7ef47ad31772.png">

Page 3 
<img width="764" alt="screen shot 2017-09-12 at 3 30 39 pm" src="https://user-images.githubusercontent.com/107439/30351267-6a62a934-97cf-11e7-8392-80ef371a6e83.png">

On the middle page, results 11-13 are shown in place of results 1-3, but results 4-10 are kept.

**Comment by attekei** [comment]
Still seeing an old version (`Built on 2017-08-29`) on stats so I'm unable to verify whether this issue still exists or not.

**Comment by salsakran** [comment]
fixed on master.
