### ISSUE TITLE
Ability to rename Series in charts

### ISSUE THREAD

**Issue by niparis** [metabase/metabase#5951]
**Could we have the possibility to rename Series to have charts more clear?**

In this case, we have two aggregations (sums of different columns), shown as "Sum" and "Sum 2", which is not very helpful to understand what they represent.

![image](https://user-images.githubusercontent.com/3415960/30373332-89b45244-98b3-11e7-84ac-19716da86cf8.png)

### Potential solutions:
*1. Allow editing directly in the chart interface*

![image](https://user-images.githubusercontent.com/3415960/30373723-d6d9cdf0-98b4-11e7-9b39-7198c3b1ec8e.png)

*2. Reuse the actual aggregation names that we see in the "View" section of the question builder.*

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by camsaul** [comment]
Implemented by #6260
