### ISSUE TITLE
Unable to connect to Aurora RDS Database

### ISSUE THREAD

**Issue by CGC-Dennis** [metabase/metabase#5953]
We are able to connect using SSL to an Aurora RDS Database Instance (or Cluster) however, when attempting to connect to a different Aurora RDS Database Instance (or Cluster), getting an error message:

java.sql.SQLException: Access denied for user 'metabasedbu'@'xxx.xxx.xxx.xxx' (using password: YES)

I am able to connect from command line to that database using mysql client without issue from the Metabase server, so I know it is not an AWS Security Group or IP Restriction.

Here is output from Metabase logs:

09-13 13:51:55 ERROR metabase.driver :: Failed to connect to database: java.sql.SQLException: Access denied for user 'metabasedbu'@'xxx.xxx.xxx.xxx' (using password: YES)
09-13 13:51:55 DEBUG metabase.middleware :: POST /api/database 400 (35 ms) (0 DB calls)
{:valid false,
 :dbname "java.sql.SQLException: Access denied for user 'metabasedbu'@'xxx.xxx.xxx.xxx' (using password: YES)",
 :message "java.sql.SQLException: Access denied for user 'metabasedbu'@'xxx.xxx.xxx.xxx' (using password: YES)"}

Metabase is version 0.25.1.

**Comment by salsakran** [comment]
We don't explicitly support Aurora, except to the degree to which it's protocol compatible with MySQL.

**Comment by salsakran** [comment]
Can you spin up a MySQL RDS instance with the same security settings and see if we can connect to that? Might be a driver incompatibility issue.

**Comment by flamber** [comment]
Closing, since no response, but I have seen multiple people using Aurora.
