### ISSUE TITLE
We should be able to parse variables with leading or trailing whitespace

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5954]
[As reported here](http://discourse.metabase.com/t/how-to-use-variables/2074). I repro-ed it on our stats branch on Chrome.

Currently, this query won't recognize the `cat` variable:

```
SELECT count(*)
FROM userdata_metadata
WHERE 1 =1
[[AND country = {{ cat }}]]
```

but this query **will:**

```
SELECT count(*)
FROM userdata_metadata
WHERE 1 =1
[[AND country = {{cat}}]]
```

**Comment by salsakran** [comment]
How embarassing.

**Comment by camsaul** [comment]
To clarify, this doesn't work with the Query Builder (the variable doesn't get picked up) but it works fine on the backend
