### ISSUE TITLE
How to query inside field

### ISSUE THREAD

**Issue by gusgustavo** [metabase/metabase#5956]
Hi, I'm trying to query this data, but it gives me an error message. How can I search inside this field?

![metabase1](https://user-images.githubusercontent.com/15200517/30397449-5bb7cf3e-98a3-11e7-993d-731bffa26bc6.png)

![metabase2](https://user-images.githubusercontent.com/15200517/30397464-63542b98-98a3-11e7-844c-d5b50ca1061a.png)

![metabase3](https://user-images.githubusercontent.com/15200517/30397611-c855aa58-98a3-11e7-9f96-f958fed871a5.png)

------
Browser: Firefox
Debian Stretch
Database: MongoDB
Metabase version: 0.26.0 RC2
Metabase hosting environment: Debian Stretch

**Comment by salsakran** [comment]
we should have those columns sync'd and available for filtering. any value you filter on must be a real value, and we don't allow json values.
