### ISSUE TITLE
No loading indicator when switching X-ray fidelities

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5962]
Load an x-ray and then hit the button to switch to a different fidelity and there's no indication that the x-ray calculations are in-flight. This is especially bad for X-rays that take several minutes. The buttons are left enabled which means you can go ahead and click them again which leads to this UI weirdness where multiple fidelities are active: 

![screen shot 2017-09-13 at 2 26 24 pm](https://user-images.githubusercontent.com/1455846/30401693-027b6402-9890-11e7-95bf-a10de3f7f2fa.png)

Which means multiple API requests can be active at the same time:

![screen shot 2017-09-13 at 2 29 12 pm](https://user-images.githubusercontent.com/1455846/30401731-1e4c9368-9890-11e7-812f-dcffe2571205.png)

so a frustrated user thinking the buttons aren't responding can nuke an entire Metabase instance by doing the "if I keep pressing the button it will sense my impatience" thing. 

If *any* of the API calls fail due to a 500 or timeout the entire page will eventually just go into an infinite loading spinner. So this is a potential scenario: you have a working X-ray, click to switch fidelity, nothing happens for two minutes, then it switches to an infinite loading spinner :/

**Comment by kdoh** [comment]
Fixed by #5988
