### ISSUE TITLE
[ERROR] iFrameResizer resizer already defined.

### ISSUE THREAD

**Issue by northtree** [metabase/metabase#5964]
When I open my metabase dashboard, it returns iFrameResizer ERROR via console.log and nothing loaded on the page except this.

![screen shot 2017-09-14 at 10 10 26 am](https://user-images.githubusercontent.com/419509/30406510-8de3ceee-9935-11e7-9c1f-0a64c7a02484.png)

![screen shot 2017-09-14 at 10 10 10 am](https://user-images.githubusercontent.com/419509/30406507-89384cd0-9935-11e7-8315-0779d0b64d02.png)

- Your browser and the version: Chrome 61.0.3163.79 (Official Build) (64-bit)
- Your operating system: Windows 7
- Metabase version:   v0.24.2
- Metabase hosting environment: Docker

**Comment by salsakran** [comment]
Does this happen with every dashboard? What happens if you create a new one?

Also, does this still occur with 0.25.2?

**Comment by MixMe** [comment]
Same problem...

**Comment by Irioth** [comment]
Same problem
Metabase version: 0.26.0
And it fails only on some specific iframe sizes.

for example
`<iframe    src=".../public/dashboard/372331db-546f-4abd-b9b3-7aa9a24cef12"    frameborder="0"   width="1800"    height="1400"    allowtransparency></iframe>`
iFrameResizer error occur

but after changing width to  2000
`<iframe    src=".../public/dashboard/372331db-546f-4abd-b9b3-7aa9a24cef12"    frameborder="0"   width="2000"    height="1400"    allowtransparency></iframe>`
everything works ok

other dashboards works fine

**Comment by woohoou** [comment]
Same problem here
Metabase version: 0.27.2

**Comment by the-undefined** [comment]
Same on:
- Metabase: `v0.28.1`
- Mac OSX `10.13.3 `
- Chrome ` 64.0.3282.186 `

Except we have taken off the width attribute from the iframe and are using the bootstrap v4 `container` class, and the error occurs when the css is using
```
max-width: 1140px;
width: 100%;
```
```html
<iframe src="https://the-url.com#bordered=true&amp;titled=true"
    height="900"
    allowtransparency
    class="container"></iframe>
```
After shrinking the browser window to hit the next breakpoint:
```
max-width: 960px;
```
and reloading the page, then the embedded dashboard appears without issue.

**Comment by gauravdaxini** [comment]
Facing the similar issue.
When the dashboard is embedded into the application it shows `An error occurred` message. This is an intermittent issue but happens many times.

Metabase Version: v0.27.2

Please provide a fix for this issue. It has been opened since Sep 2017.

**Comment by aviggiano** [comment]
See [here](https://github.com/metabase/metabase/issues/6352#issuecomment-362256188), this worked for me

**Comment by astathis** [comment]
I have the same issue with Firefox and I just resize the browser to be smaller on width dimension and the problem solved. I think it has to do with `<iframe src="'+CURRENT_DATA+'" scrolling="no"  **_width="100%"_** frameborder="0" height="1000px;" ></iframe>` attribute.

**Comment by rlotun** [comment]
we upgraded iframeresizer which likely closes this issue - feel free to reopen if it hasn't: https://github.com/metabase/metabase/pull/16952
