### ISSUE TITLE
ADD i18n support

### ISSUE THREAD

**Issue by marcelmfs** [metabase/metabase#5968]
### Feature requests and proposals

Add internationalisation support to be able to translate Metabase into different languages.

**Comment by jornh** [comment]
There's already an issue for that, see https://github.com/metabase/metabase/issues/1451#issuecomment-323420922 AND it's being worked on with PR's linked over there.

The good part *you* can help: http://www.metabase.com/blog/Metabase-in-your-language 😄 🎉

**Comment by marcelmfs** [comment]
I had searched before opening this issue but couldn't find that particular one... thanks
