### ISSUE TITLE
The Action menu doesn't know when a metric has been retired

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6002]
This is on Chrome on our stats instance.

Haven't tested to see if this is also the case with retired segments, but if I open up a table that has retired metrics in it, they're still listed in the action menu, and I can run them:

![screen shot 2017-09-18 at 3 48 01 pm](https://user-images.githubusercontent.com/2223916/30568243-eeee6a54-9c88-11e7-82de-7a16e16fb797.png)

Here's the retired metric after running it:

![screen shot 2017-09-18 at 3 48 10 pm](https://user-images.githubusercontent.com/2223916/30568255-f91fa6e6-9c88-11e7-925c-eda0dd733af0.png)

**Comment by kdoh** [comment]
Just tried to reproduce this but I'm not able to locally or on stats.

**Comment by paulrosenzweig** [comment]
I also can't repro this. @mazameli, think it's safe to close?

**Comment by mazameli** [comment]
Yeah, I'm sure a lot has changed in this area of the code since September of 2017, so since neither you nor Kyle can reproduce it, I'll close it.
