### ISSUE TITLE
Disable editing rights on Dashboards

### ISSUE THREAD

**Issue by kapilssn001506** [metabase/metabase#6005]
Team,

Need to remove the rights to edit the dashboard from All Users group.

Please suggest a way for it.

**Comment by flamber** [comment]
Hi @kapilssn001506 
I cannot reproduce your issue on 0.31.2 - I think this was fixed as part of the Collections overhaul in 0.30

**Comment by flamber** [comment]
Closing issue because of no reply and I cannot reproduce on 0.34.3
