### ISSUE TITLE
No option via Beanstalk template for SSL?

### ISSUE THREAD

**Issue by alikhan-io** [metabase/metabase#6008]
We are currently running Metabase via Elastic Beanstalk (version 0.24.1). We'd like to enable SSL to the Postgres DB powering Metabase (RDS). There seems to be no flag to enable this easily, nor any directions in the docs.

Can we get a config option to enable SSL for the connection to Metabases's DB?

**Comment by salsakran** [comment]
You should be able to turn on SSL via elastic beanstalk in the "Load Balancer" section of the configuration options when you start or edit your application environment. You should see something like 

![screen shot 2017-09-21 at 10 56 41 am](https://user-images.githubusercontent.com/107439/30710831-a2dd5f0a-9ebb-11e7-95b5-333b9de0b6d6.png)

Enabling SSL requires you to have gotten certs from AWS, and is outside the current scope of our docs.

**Comment by salsakran** [comment]
actually, I just realized we do discuss SSL in the docs http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#modify-metabase-to-enforce-https
