### ISSUE TITLE
Drill through / underlying records action doesn't respect filters in metric definitions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6010]
This is on Chrome on our stats instance.

If I have a "common metric" which includes one or more filters in its definition, when I view it in the query builder and then either use the `underlying records` action, or click on a point on a line and use the `view these items` drill-through action, the list of rows that gets returned don't include the filters that are part of the metric's definition.

For example, say I have a metric called `Revenue from Octogenarian Users`, which is defined as `sum of subtotal where purchaser age is between 80 and 89`.  If I'm viewing it as a time series and I click `view these users` from the drill-through menu on one of the line's points, the raw data query that's subsequently run will correctly filter on the date I clicked on, but it won't include the `age is between 80 and 89` filter. This means I'm viewing the wrong segment.

Here's a very similar example:

**Query using a common metric**

![screen shot 2017-09-19 at 11 08 20 am](https://user-images.githubusercontent.com/2223916/30607754-f4e5e69c-9d2a-11e7-8f9c-45f4c0eba120.png)

**Result of viewing underlying records (note the filter isn't there)**

![screen shot 2017-09-19 at 11 08 35 am](https://user-images.githubusercontent.com/2223916/30607765-fc43e074-9d2a-11e7-91f3-dbf0737919ae.png)

**Comment by rcronin** [comment]
Is there any plan to get this working?
