### ISSUE TITLE
Buttons unusable with multiple selections

### ISSUE THREAD

**Issue by mpekalski** [metabase/metabase#6011]
Problem with filter/selection row. We tend to have quite long column names, so they could be as descriptive as possible, and then when person works on a laptop not many of those could be selected as the + button gets out of the screen in case of selecting columns or + from filters it gets hidden behind column from selection making it unclickable. For the second issue you have to be lucky to get columns of good width that would sum up exactly so the plus button would get hidden. For the first case it is just enough to add as many as possible even in sample database.

My suggestion would be to introduce some scroll bar if the selection/filter gets too wide, or wrap them and introduce another row. 

Metabase 0.26 RC 1
Windows 7 
Chrome Version 60.0.3112.113
Internal Database: Postgres
Hosting environment: Dockerized Ubuntu 16.04

I am sorry but I had to blank out the column and database names. 
![metabase_error2](https://user-images.githubusercontent.com/2975068/30608919-23292bdc-9d7a-11e7-8228-1697e22328d1.PNG)

![metabase_error](https://user-images.githubusercontent.com/2975068/30608886-017b17ac-9d7a-11e7-866b-e0761320ba9c.JPG)

**Comment by flamber** [comment]
This was fixed in 0.33 with the new query browser UI:
![image](https://user-images.githubusercontent.com/1447303/82760873-b60c5a80-9df6-11ea-8bb7-fe51dbcbbda7.png)
