### ISSUE TITLE
Feature Request: Excel/CSV export date format string based on grouping granularity?

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#6012]
I would love for the CSV/XLSL export of date/time-based data to have varied (or customizable) formatting based on the granularity selected in the "Group By" clause of a visual query.

**Use case:**

One of our employees wants to download an excel file of a time-based query to do further analysis in excel. They select the "by day" granularity for a "group by" clause of a datetime field.

Their expectation is that the downloaded excel file column for the datetime field will be in a *date* formatted string that excel can correctly automatically interpret as a date.

Instead the column entries are long datetime strings with timezone information and hours/minutes/seconds all set to 0.

I get that the current behavior is nice from a consistency standpoint, especially if you are a programmer, but for a lay user who is acclimated to excel, they just view it as another "data massaging" step that they have to do on every single date-related query that they download from metabase.

It would be cool if Metabase either:

1. Tried to intelligently format the datetime string based on requested export format and the time field granularity.
2. Alternatively, exposed an option like in the row settings or overall settings for the metabase instance for users to specify their desired datetime string export format.

If this functionality already exists and his hiding somewhere in plain sight, my apologies!

Related #10879 #10803
:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mvrabel** [comment]
Related #5295

**Comment by flamber** [comment]
Fixed by #13447

**Comment by camsaul** [comment]
@robdaemon I've added you as the assignee so we can remember you were the one who fixed this. Just for info purposes
