### ISSUE TITLE
Do something better with 403 responses than the /unauthorized/ url

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#602]
It's pretty sad looking right now.

**Comment by camsaul** [comment]
+1 styling is kinda wonky [bird]

![screen shot 2016-07-06 at 9 26 08 pm](https://cloud.githubusercontent.com/assets/1455846/16642498/79850862-43c0-11e6-8c47-ef8bcdaa0a32.png)

**Comment by tlrobinson** [comment]
This is what we have now, can we close this? (our oldest open issue!)

![screenshot 2016-10-11 23 19 46](https://cloud.githubusercontent.com/assets/18193/19299458/47ab99ce-9009-11e6-90d1-33a32e59ecf9.png)

**Comment by salsakran** [comment]
Works for me. Wanna do the honors?
