### ISSUE TITLE
Feature Request: Filter field values filtered by locked parameter in embedded dashboards

### ISSUE THREAD

**Issue by rubenmch** [metabase/metabase#6022]
Using a CrateDB database and Metabase 0.25.2

In Metabase we create dashboards that can by used by our customers in our embedded application. Each dashboard has a locked CustomerId parameter that is set by our application so each customer can see only their data and can't see the data of other customers. Each table in the database has a CustomerId column.

We added some additional category filters to the dashboards. The issue we have now is metabase displays all the distinct values in the database for the filter so customers can see other customers values when selecting a value in the filter.

We need a way to filter the filter field values so each customer only sees the values available in his rows.

**Comment by salsakran** [comment]
This is related to #2824

**Comment by killthekitten** [comment]
@rubenmch how have you implemented the `CustomerId` locking?

@salsakran this is not related to #2824, and rather to #8472 and #2682. It is kinda achiveable with the [data sandboxes](https://www.metabase.com/docs/latest/enterprise-guide/data-sandboxes.html) enterprise feature:

> The simplest way to filter a sandboxed table is to pick a column in the sandboxed table and match it up with a user attribute so that any time a user with sandboxed access to this table views it, they’ll only see rows in the table where that column’s value is equal to the value that user has for that attribute.

Then @rubenmch would create a user with a locked `CustomerId` value, and grant them sandboxed permissions to the tables based on the locked value.

However, I'm looking for something simpler, I'd like only the admin to be able to change filters' values, and lock them for anyone who views the dashboard. That wouldn't even require a user account – specifically for the dashboards that are available via a public link. 

Is it currently possible, or would you like to see something like this implemented in a free version?
