### ISSUE TITLE
Feature Request: Default to contains instead of equals in text dashboard field filters

### ISSUE THREAD

**Issue by rubenmch** [metabase/metabase#6023]
DB: Crate
Metabase Version: 0.25.2

When adding a filter to a dashboard that shows a textbox to enter the filter value (not a category) the input value must match exactly the value in the rows, otherwise no results are returned. 

It would be very useful to be able to choose the condition (equals, not equals, contains, starts with, ends with). 

Or at least use **contains** by default instead of **equals**. Most of our users type only part of the value and expect the result to include all the rows containing the text input.

**Comment by mazameli** [comment]
We're currently trying to solve the underlying problem you're describing here through https://github.com/metabase/metabase/pull/4241, which will provide autocomplete searching of possible values for category filters.

**Comment by flamber** [comment]
Closing in favor of #8219
