### ISSUE TITLE
Missing date format parameter when adding date field filter to custom sql

### ISSUE THREAD

**Issue by rubenmch** [metabase/metabase#6024]
Database: Crate
Metabase: 0.25.2

I created the following custom sql question:

```sql
select * from test where {{Date}}
```
Date is set as a **field filter**. Widget set to **Date Filter** but I tested with the other widgets and the same error happens.
When I try to get the answer I get the following error:
```
No value specified for parameter 3.
```
The metabase log shows the following request that has 3 declared parameters (```date_format(?, ```, ```BETWEEN ?```, ```AND ?```) in the query but only passes 2 parameters, the date format parameter is missing.
```
Sep 21 13:37:14 DEBUG metabase.query-processor.middleware.mbql-to-native :: NATIVE FORM: 😳
{:query "select * from test where date_format(?, date_trunc('day', \"doc\".\"test\".\"date\")) BETWEEN ? AND ?",
:template_tags {:Date {:id "67ee7881-53a8-a931-627c-2d756b6c88ff", :name "Date", :display_name "Date", :type "dimension", :dimension ["field-id" 787], :widget_type "date/all-options"}},
:params (#inst "2017-08-22T00:00:00.000000000-00:00" #inst "2017-09-20T00:00:00.000000000-00:00")}
```

**Comment by camsaul** [comment]
This might have been fixed by #6375 

@rubenmch can you try that out and see if it resolves your issue? It's already merged so you can just run `master`

**Comment by cOnjuer** [comment]
I'm also facing the same issue on:-
      Metabase - 0.30.2 (deployed as jar)
      CrateDB - 3.0.6

Error on UI
`io.crate.shade.org.postgresql.util.PSQLException: No value specified for parameter 2.`

Full error trace
  `09-13 10:34:14 WARN metabase.query-processor :: {:status :failed,
 :class java.util.concurrent.ExecutionException,
 :error "io.crate.shade.org.postgresql.util.PSQLException: No value specified for parameter 2.",
 :stacktrace
 ["driver.generic_sql.query_processor$cancellable_run_query.invokeStatic(query_processor.clj:485)"
  "driver.generic_sql.query_processor$cancellable_run_query.invoke(query_processor.clj:477)"
  "driver.generic_sql.query_processor$run_query.invokeStatic(query_processor.clj:502)"
  "driver.generic_sql.query_processor$run_query.invoke(query_processor.clj:497)"
  "driver.generic_sql.query_processor$do_with_auto_commit_disabled.invokeStatic(query_processor.clj:535)"
  "driver.generic_sql.query_processor$do_with_auto_commit_disabled.invoke(query_processor.clj:524)"
  "driver.generic_sql.query_processor$do_in_transaction$fn__56673.invoke(query_processor.clj:540)"
  "driver.generic_sql.query_processor$do_in_transaction.invokeStatic(query_processor.clj:539)"
  "driver.generic_sql.query_processor$do_in_transaction.invoke(query_processor.clj:538)"
  "driver.generic_sql.query_processor$run_query_without_timezone.invokeStatic(query_processor.clj:553)"
  "driver.generic_sql.query_processor$run_query_without_timezone.invoke(query_processor.clj:552)"
  "driver.generic_sql.query_processor$execute_query$fn__56697.invoke(query_processor.clj:577)"
  "driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:519)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:514)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:574)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:570)"
  "driver$fn__28369$G__28176__28376.invoke(driver.clj:104)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:54)"
  "query_processor$execute_query.invoke(query_processor.clj:48)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__33121.invoke(mbql_to_native.clj:30)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__31435.invoke(annotate_and_sort.clj:42)"
  "query_processor.middleware.limit$limit$fn__33076.invoke(limit.clj:15)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__32926.invoke(cumulative_aggregations.clj:58)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__32926.invoke(cumulative_aggregations.clj:58)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__37053.invoke(results_metadata.clj:51)"
  "query_processor.middleware.format_rows$format_rows$fn__33066.invoke(format_rows.clj:26)"
  "query_processor.middleware.binning$update_binning_strategy$fn__31529.invoke(binning.clj:165)"
  "query_processor.middleware.resolve$resolve_middleware$fn__30920.invoke(resolve.clj:492)"
  "query_processor.middleware.expand$expand_middleware$fn__32806.invoke(expand.clj:607)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__31109.invoke(add_row_count_and_status.clj:15)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__32946.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__35593.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31443$fn__31444.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:82)"
  "util.date$call_with_effective_timezone.invoke(date.clj:71)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31443.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__31618.invoke(cache.clj:149)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__32857.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:135)"
  "query_processor$process_query.invoke(query_processor.clj:131)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:249)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)"
  "query_processor$fn__37091$process_query_and_save_execution_BANG___37096$fn__37097.invoke(query_processor.clj:289)"
  "query_processor$fn__37091$process_query_and_save_execution_BANG___37096.invoke(query_processor.clj:275)"
  "query_processor$fn__37115$process_query_and_save_with_max_BANG___37120$fn__37121.invoke(query_processor.clj:310)"
  "query_processor$fn__37115$process_query_and_save_with_max_BANG___37120.invoke(query_processor.clj:306)"
  "api.dataset$fn__43568$fn__43571.invoke(dataset.clj:45)"
  "api.common$fn__20630$invoke_thunk_with_keepalive__20635$fn__20636$fn__20637.invoke(common.clj:433)"],
 :query
 {:type "native",
  :native
  {:query
   "SELECT \nsum(\"totalCartValue\") AS \"CartValue\"\nFROM events\nWHERE 1=1 AND {{eventDateTime}} [[AND {{isExcluded}}]] [[AND {{advertiserName}}]] [[AND {{campaignName}}]] [[AND {{publisherName}}]] [[AND {{countryLong}}]]",
   :template_tags
   {:advertiserName {:id "15c10a45-97c8-91db-3930-c362bd64e428", :name "advertiserName", :display_name "Advertisername", :type "dimension", :dimension ["field-id" 66752], :widget_type "category"},
    :campaignName {:id "b7309b09-d8b4-1543-0443-b9dfecf3ffd6", :name "campaignName", :display_name "Campaignname", :type "dimension", :dimension ["field-id" 66835], :widget_type "category"},
    :publisherName {:id "f7c4949d-3e9d-f2b3-b8f4-440387107eaa", :name "publisherName", :display_name "Publishername", :type "dimension", :dimension ["field-id" 66807], :widget_type "category"},
    :countryLong {:id "058ae575-8b3d-a730-7500-b0cc4f97bed1", :name "countryLong", :display_name "Countrylong", :type "dimension", :dimension ["field-id" 66761], :widget_type "location/country"},
    :isExcluded {:id "e622e567-d3d6-2cda-5a80-0dfa0a2b0313", :name "isExcluded", :display_name "Isexcluded", :type "dimension", :dimension ["field-id" 66837], :widget_type "category"},
    :eventDateTime
    {:id "2c310c74-fdcc-fa91-e622-63407c7a7010", :name "eventDateTime", :display_name "Eventdatetime", :type "dimension", :dimension ["field-id" 66781], :widget_type "date/all-options"}}},
  :parameters [{:type "date/all-options", :target ["dimension" ["template-tag" "eventDateTime"]], :value "2018-09-04"}],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [-56, 37, -108, -15, 16, -30, -15, 120, -101, -84, -53, 8, -85, 40, 60, 40, -64, 126, 17, 93, 59, 105, -100, -6, 6, 21, -112, 18, 43, -49, -69, -6],
   :query-type "native"}},
 :expanded-query nil}

09-13 10:34:14 WARN metabase.query-processor :: Query failure: io.crate.shade.org.postgresql.util.PSQLException: No value specified for parameter 2.
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:217)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:210)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:250)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)"
 "query_processor$fn__37091$process_query_and_save_execution_BANG___37096$fn__37097.invoke(query_processor.clj:289)"
 "query_processor$fn__37091$process_query_and_save_execution_BANG___37096.invoke(query_processor.clj:275)"
 "query_processor$fn__37115$process_query_and_save_with_max_BANG___37120$fn__37121.invoke(query_processor.clj:310)"
 "query_processor$fn__37115$process_query_and_save_with_max_BANG___37120.invoke(query_processor.clj:306)"
 "api.dataset$fn__43568$fn__43571.invoke(dataset.clj:45)"
 "api.common$fn__20630$invoke_thunk_with_keepalive__20635$fn__20636$fn__20637.invoke(common.clj:433)"]`

Field filters of other types work fine.

**Comment by camsaul** [comment]
Hi everyone, starting with Metabase 0.32.0 we're removing the CrateDB driver from the core Metabase project and instead making it available as a community-supported driver. When you upgrade to Metabase v0.32.0+, you can download the Crate driver and see instructions to install it here: https://github.com/metabase/crate-driver. 

If you're still having problems with CrateDB, please open an issue at https://github.com/metabase/crate-driver/issues
