### ISSUE TITLE
Dashboard Auto Refresh Support Seconds interval

### ISSUE THREAD

**Issue by willddy** [metabase/metabase#6026]
Feature requests and proposals

Feature request: 
Ability to support seconds in dashboard refresh.
Ability to support manual refresh (button) in dashboard.
Ability to support refresh in dashboard using like corntab.
Thanks!

**Comment by salsakran** [comment]
we already allow seconds http://www.metabase.com/docs/latest/users-guide/07-dashboards.html#configuring-a-dashboard-through-its-url

**Comment by datafibers** [comment]
I tried a couple of times. The minimum refresh time is 60 seconds. I mean to make it smaller, such as 10 sec.
