### ISSUE TITLE
Sync process has too many open cursors

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6029]
As reported in the discussion forum - 

http://discourse.metabase.com/t/metadata-sync-fails-with-ora-01000-maximum-open-cursors-exceeded/2090

**Comment by salsakran** [comment]
Is it possible we're leaking connections somewhere?

**Comment by JAC2703** [comment]
+1 I just came across this today when connecting to a large Oracle instance (large in table count).

**Comment by dop12** [comment]
+1 
it happened to me too
Can it be solved temporarily by some workaround at least?

**Comment by baksale** [comment]
+1
happened to me to.
Checked with database developer - system keeps hundreds of cursors with the same query.

**Comment by ricardoj-br** [comment]
+1

Having this same issue

My environment is : Metabase 0.26.2 Ubuntu 16.04

Let me explain what I did so far

    changed from open-jdk to oracle jdk
    changed from SID to service
    changed jdbc driver versions ( ojdbc7.jar and ojdbc6.jar )

No luck !

From this same machine and using the same oracle configuration I can connect **dremio** to the oracle without problems and browse the schema and its contents.

Any idea ? What else could be tested ?

Thanks,

Ricardo Jorge

**Comment by MarkRx** [comment]
Similar issues: #6467, #4389

**Comment by gnyuan** [comment]
+1, it seems like bug from ojdbc7.jar

**Comment by MarkRx** [comment]
Happens with ojdbc8.jar as well. What makes you think it is a bug with ojdbc? My guess is it is due to functional recursion exploding resulting in too many open cursors.

**Comment by joboyx** [comment]
I think this is not a harmful error. Since my instance of Metabase still was able to sync fields and schema even this error pops up.

We just need to confirm with Metabase core team, if Metabase do retry to sync a table once it encountered an error like "ORA-01000: maximum open cursors exceeded". Or if we just need to wait for the next sync to happen or manual trigger the sync.

**Comment by senior** [comment]
This issue appears to have been resolved by ensuring the ResultSets returned by the JDBC metadata calls get closed explicitly, which was added in https://github.com/metabase/metabase/pull/7666. If you're still hitting this issue with version `0.30.3`+, ensure you are using the latest Oracle JDBC Driver (`12.2.0.1.0` and `ojdbc8.jar`).
