### ISSUE TITLE
Druid > Number of Distinct Values

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6032]
When I ask this question, the result return a number rounded, not a truth value.

When I list Raw Data in table, the total of rows is truth number.

Any idea ?

**Comment by salsakran** [comment]
what do you mean by "truth value"?

**Comment by jonatasfreitasv** [comment]
Example, the total of rows is 241, in Table/Raw Data with Distinct Values, Metabase show all rows and total is correct.

But when make Question with "Number of Distinct Values", the Metabase showing 242 or 240, showing approximate value.

**Comment by moumny** [comment]
http://druid.io/docs/latest/querying/aggregations.html
Druid uses HLL aggregator by default.

**Comment by jonatasfreitasv** [comment]
Yes @moumny, is Druid arch. thx a lot.
