### ISSUE TITLE
Feature request: make max-results configurable or overridable

### ISSUE THREAD

**Issue by canburak** [metabase/metabase#6033]
All API results seems to be capped to 10k and limit queries are ignored.

Is it possible to make this configurable, or overridable?

https://github.com/metabase/metabase/blob/4c3588a5d01e488d74e336c93679f38314f9a086/src/metabase/api/dataset.clj#L31

**Comment by salsakran** [comment]
What are you trying to use the API for? 

In general, we're not set up to push through entire tables, and you should probably use export tools or a backup process for that sort of thing. If you hit the download links those are capped at 1M records.

**Comment by canburak** [comment]
Hello, download links, or better https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apidatasetexport-format seems to be a solution. Thanks.
