### ISSUE TITLE
X-Rays of druid cards don't seem to work

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6044]
count of rows broken out by time gives me

![screen shot 2017-09-25 at 5 52 08 pm](https://user-images.githubusercontent.com/107439/30837700-a3e22ecc-a21b-11e7-96ba-092a4457248d.png)

**Comment by sbelak** [comment]
Closing this as with 0.29 we are retiring this approach to xrays in favour of a dashboard-based one.
