### ISSUE TITLE
Group by week (timeseries with week granularity) in Druid displays incorrect results

### ISSUE THREAD

**Issue by andrewboltachev** [metabase/metabase#6047]
- Your browser and the version: Google Chrome 60.0.3112.90 64 bit
- Your operating system: Ubuntu 16.04.3 LTS
- Your databases: Druid
- Metabase version: 62368d3
- Metabase hosting environment: Ubuntu 16.04.3 LTS
- Metabase internal database: H2

Notes:
- Druid runs on a machine which's clock is in UTC
- Metabase was also forced to UTC using `JVM_OPTS="-Duser.timezone=UTC" lein ring server-headless`
- No special TZ for this Database is selected in Control panel

- Repeatable steps to reproduce the issue:
1. Insert the following into Druid database:

`data2.json`
```json
{"time":"9/22/17 0:00","name":"event1"}
{"time":"9/23/17 0:00","name":"event2"}
{"time":"9/24/17 0:00","name":"event3"}
{"time":"9/25/17 0:00","name":"event4"}
{"time":"9/26/17 0:00","name":"event5"}
```
`data2-index.json`
```json

{
  "type" : "index_hadoop",
  "spec" : {
    "ioConfig" : {
      "type" : "hadoop",
      "inputSpec" : {
        "type" : "static",
        "paths" : "./data2.json"
      }
    },
    "dataSchema" : {
      "dataSource" : "data2",
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "day",
        "queryGranularity" : "none",
        "intervals" : ["2017-09-22/2017-09-27"]
      },
      "parser" : {
        "type" : "hadoopyString",
        "parseSpec" : {
          "format" : "json",
          "dimensionsSpec" : {
            "dimensions" : [
              "name"
            ]
          },
          "timestampSpec" : {
            "format" : "MM/dd/yy H:m",
            "column" : "time"
          }
        }
      },
      "metricsSpec" : [
        {
          "name" : "count",
          "type" : "count"
        }
      ]
   }
  }
}
```

Command to insert might be this:
```bash
curl -X 'POST' -H 'Content-Type:application/json' -d @data2-index.json localhost:8090/druid/indexer/v1/task
```

Add Druid to Metabase and run "Raw data" query against "Data 2" datasource:
![_2017-09-26_15-46-55](https://user-images.githubusercontent.com/731973/30860994-0192e47e-a2d2-11e7-894b-062edc32881e.png)

Everything is fine. Then, select Grouped By: Timestamp Week:

![_2017-09-26_15-48-38](https://user-images.githubusercontent.com/731973/30861056-35719b14-a2d2-11e7-82b7-2447848c4e05.png)

As we can see, it returns 3 for period `17..23` (but there's 2: `22` and `23`) and 2 for period `24..30` (but there're 3: `24`, `25` and `26`).

This happens 'cause Druid handles weeks as staring from Monday, and the last query:
```json
{
    "intervals": ["1900-01-01/2100-01-01"],
    "granularity": {
        "type": "period",
        "period": "P1W",
        "timeZone": "UTC"
    },
    "context": {
        "timeout": 60000
    },
    "queryType": "timeseries",
    "dataSource": "data2",
    "aggregations": [{
        "type": "count",
        "name": "count"
    }],
    "descending": false
}
```

returns weeks as first day of week, which are Mondays:
```json
[ {
  "timestamp" : "2017-09-18T00:00:00.000Z",
  "result" : {
    "count" : 3
  }
}, {
  "timestamp" : "2017-09-25T00:00:00.000Z",
  "result" : {
    "count" : 2
  }
} ]
```

In fact, that Metabase's UI which then displays the info.

---

I think this might be fixed in two ways:
1. Specifying `origin` as midnight of any available Sunday (e.g. 3th of Sep, or sth in 1970 or the like, _whatever it would tolerate_), so that Druid would start weeks from Sunday:
```json
{
    "intervals": ["1900-01-01/2100-01-01"],
    "granularity": {
        "type": "period",
        "period": "P1W",
        "origin": "2017-09-03T00:00:00+00:00",
        "timeZone": "UTC"
    },
    "context": {
        "timeout": 60000
    },
    "queryType": "timeseries",
    "dataSource": "data2",
    "aggregations": [{
        "type": "count",
        "name": "count"
    }],
    "descending": false
}
```
Result (notice `17` and `24` compared to `18` and `25` above):
```json
[ {
  "timestamp" : "2017-09-17T00:00:00.000Z",
  "result" : {
    "count" : 2
  }
}, {
  "timestamp" : "2017-09-24T00:00:00.000Z",
  "result" : {
    "count" : 3
  }
} ]
```
2. Making Metabase start weeks from Monday. Related: #1779 

**Please tell what way is better and I'll submit a PR then.**

**Comment by senior** [comment]
@andrewboltachev Thanks for digging in! I agree with your assessment of the issue and the first solution you have listed seems like the right one. I'd also suggest you put a comment around that origin date describing it's purpose. I've read the docs and it makes sense, but I could see that somewhat arbitrary date being confusing for people looking at that code in the future.
