### ISSUE TITLE
JAR for Metabase 0.26.1

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#6055]

**Comment by lindsay-stevens** [comment]
Can be gotten here: http://www.metabase.com/start/jar.html

Direct link: http://downloads.metabase.com/v0.26.1/metabase.jar

**Comment by salsakran** [comment]
We sometimes will create the release artifacts but not publicize a release. We do this for any number of reasons-- we might want to test out a new deployment change, want to let folks test a release more formally before pointing people at it, or just not release at the end of a work day in our timezone.

While the releases list on GH will mostly track the timing of a release, it should not be viewed as official until it hits our main webpage at www.metabase.com.
