### ISSUE TITLE
How does Metabase compare with QuickSight?

### ISSUE THREAD

**Issue by gajus** [metabase/metabase#6057]
In general, it would be good for you to have a wiki-style comparison table between Metabase, QuickSight, Redash, Superset and Tableau.

Comparison tables make it easy to create a business case for the product. I am sure you would do good in the comparison tables, considering that you are open-source, have commercial support and can be hosted in house.

**Comment by camsaul** [comment]
Hi @gajus, we use GitHub Issues primarily for tracking product bugs and features, so the best place to ask questions like these is probably our [Discourse discussion forum](https://discourse.metabase.com/).
