### ISSUE TITLE
question/new page does not show images behind a reverse proxy.

### ISSUE THREAD

**Issue by csawyerYumaed** [metabase/metabase#6061]
This also applies to the other 2 images on the question/new page.

I think this should have a url(' ') wrapper, so it will work behind a proxy:
https://github.com/metabase/metabase/blob/0651d270633a7530e3d4534447d01fd00bc99d2b/frontend/src/metabase/questions/containers/QuestionIndex.jsx#L48

**Comment by togawara** [comment]
As the temporal solution, the following nginx config works for my environment.
NGINX: 1.12.2-1~stretch
metabase: metabase/metabase:v0.28.6

https://gist.github.com/togawara/da23566632e11edf813da1e24a2d8d26

It may be slow because of no gzip...

**Comment by roemhildtg** [comment]
Also related - Create your metric Preview button goes to the wrong place behind a reverse proxy:

![image](https://user-images.githubusercontent.com/5471079/40848075-c543c130-6583-11e8-9fae-a16b50bd80aa.png)

**Comment by jornh** [comment]
I believe this could already be fixed by PR #7601 merged into master. It should be available in 0.30.0 RC1 which I encourage you guys to take for a testing ride 🚗 🏍 ✈️ ⛵️ 

Related: #6704 and #7841

**Comment by jornh** [comment]
@csawyerYumaed -  @togawara - @roemhildtg the fix mentioned above got released as part of v0.30.0. Would be good to know if that fixes the issue(s) for you!

A good starting point for planning to go to v0.30 - as it contains quite some UI changes etc. is 
https://metabase.com/blog/before-upgrading-to-0.30/index.html#before-you-upgrade

**Comment by roemhildtg** [comment]
Yeah, it actually doesn't appear to be an issue any more for me. Thank you.

**Comment by tsibley** [comment]
I'm still running into [the metric preview button error](https://github.com/metabase/metabase/issues/6061#issuecomment-393910209) in 0.31.2 when behind a reverse proxy.

**Comment by flamber** [comment]
Was fixed in 0.30.0 - metric/segment Preview-button is #12580
