### ISSUE TITLE
Weird date filter on v0.26.0 (timezone issue?)

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#6062]
The date filter on v0.26.0 gives value different from constant value, as below
![weird_date_filter](https://user-images.githubusercontent.com/2088055/30946869-97d47506-a430-11e7-8c66-c5a772babcd0.png)

Our metabase and metabase postgres server use UTC timezone. 
Please help to troubleshoot this issue.

Thanks.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by thucnc** [comment]
This issue doesn't happen on v0.25.2 (with above query) so I'm using v0.25.2 temporarily.

**Comment by camsaul** [comment]
Hi @thucnc, can you give me a little more details about this issue? What do you expect the query to return? The date parameter `{{start_date}}` should be handling timezones automatically so it looks to me like you're adding the timezone offset twice for those fields

**Comment by senior** [comment]
@thucnc There are a few different ways a timezone can be set and that can affect the timezone you are seeing the results in.

- What is the JVM timezone? This will either be specified via the `user.timezone` property or inherited from the system's timezone. To check the system timezone, use `date +"%Z %z"`.

- What is your report timezone? This is in the "General Settings" tab of the admin panel in Metabase

**Comment by thucnc** [comment]
Hey, sorry for my late response,
I setup another metabase v.27.2 container in the same machine and don't see any issue with the date filter, so this issue may be very specific to my old container that I can't figure out the root cause.

So I think we can close this issue, thank you.

**Comment by salsakran** [comment]
Glad to hear it got fixed! If you see any other weird timezone behaviors let us know! We're trying to systemically stamp out all the bugs we can find on that front, and we're prioritizing fixing anything that might result in incorrect numbers.
