### ISSUE TITLE
pre-populate set of dashboards + visualzations

### ISSUE THREAD

**Issue by araza82** [metabase/metabase#6064]
Hello,
I am looking to use metabase for my users to pull data from mysql. Many of my users need a common set of dashboards and visualizations and they all use the same database schema.

Is it possible to import/export some configs or pre-populate some set of visualization/dashboards? So as soon at the user configure their database settings, the dashboards can be automatically populated?

**Comment by salsakran** [comment]
Easiest way would be to use our REST Api https://github.com/metabase/metabase/wiki/Using-the-REST-API

**Comment by flamber** [comment]
Closing in favor of #9434
