### ISSUE TITLE
Custom mapping doesn't work for PostgreSQL views

### ISSUE THREAD

**Issue by lfcipriani** [metabase/metabase#6065]
- Metabase version: 0.25.2
- Metabase hosting environment: ubuntu, Mac app
- Metabase internal database: Postgresql

Steps to reproduce:

- Create a Postgresql view from a table that has a numeric field;
- Go to original table data model and make sure you can create a custom mapping for that field;
- Then go to the View and try to add custom mapping for the same field;
- The option "Custom mapping" never appears for Views, but in Tables they appear.

**Comment by salsakran** [comment]
Can you screenshot the datamodel "raw" view for that view and ideally the underlying table as well, if you can.

**Comment by lfcipriani** [comment]
Here's table and view raw datamodel:

![screenshot from 2017-09-29 22-28-08](https://user-images.githubusercontent.com/37157/31034768-bea1ef16-a565-11e7-969f-fc82b2e51e07.png)

![screenshot from 2017-09-29 22-29-00](https://user-images.githubusercontent.com/37157/31034774-c171a13c-a565-11e7-8033-0f667baf7034.png)

**Comment by shiena** [comment]
I also have the same issue with redshift.
However, I found that Custom mapping does not work if it contains null in the fetched value.
And I found a type checked here.

https://github.com/metabase/metabase/blob/v0.28.3/frontend/src/metabase/admin/datamodel/containers/FieldApp.jsx#L514-L524

**Comment by ddio** [comment]
I found the root cause may related to whether metabase has write permission to the table.

Same issue can be observed when using read only account to access Postgres regular table.

**Comment by shedd** [comment]
I am also running into this issue with a BigQuery datasource.

No matter what field type I select, there is no option to create Custom Mapping for the field.

<img width="841" alt="screen shot 2018-06-16 at 9 25 37 am" src="https://user-images.githubusercontent.com/180497/41500500-55db87cc-7147-11e8-9782-70a8f8b76cfa.png">

To address the suspected causes suggested in the thread - my user does have write access to the data table, however, there are nulls in these columns.

Any known workarounds?

**Comment by FallenChromium** [comment]
@shedd I made a SELECT VALUES view and changed column type to FK, so the option "FK mapping" appeared. That's frustrating though, also probably related to #8116.

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4 with Postgres 12.2
#8116 - Custom Mapping not available for column with `null` values
#9115 - Custom Mapping getting reset, when column is FK
