### ISSUE TITLE
Error when install Metabase

### ISSUE THREAD

**Issue by esaiekuitche** [metabase/metabase#6067]
Hi, 
I'm starting using Metabase, I successful install it on my PC, but when I try to install metabase on my server I got this error. 
ekuitche@ubuntu:~$ java -jar metabase.jar
09-28 14:08:50 INFO metabase.util :: Loading Metabase...
09-28 14:08:53 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓 
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
09-28 14:08:57 INFO metabase.core :: Starting Metabase in STANDALONE mode
09-28 14:08:57 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

09-28 14:08:57 INFO metabase.core :: Starting Metabase version v0.26.1 (dacff52 release-0.26.1) ...
09-28 14:08:57 INFO metabase.core :: System timezone is 'America/Montreal' ...
09-28 14:08:58 WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
09-28 14:08:58 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
09-28 14:08:58 INFO metabase.db :: Verifying h2 Database Connection ...
09-28 14:08:58 INFO metabase.db :: Verify Database Connection ...  ✅
09-28 14:08:58 INFO metabase.db :: Running Database Migrations...
09-28 14:08:58 INFO metabase.db :: Setting up Liquibase...
09-28 14:08:58 INFO metabase.db :: Liquibase is ready.
09-28 14:08:58 INFO metabase.db :: Checking if Database has unrun migrations...
09-28 14:09:00 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
09-28 14:09:01 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
09-28 14:09:01 INFO db.migrations :: Finished running data migrations.
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.dependencies 👂
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications 👂
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.last-login 👂
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle 👂
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.notifications 👂
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.revision 👂
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.sync-database 👂
09-28 14:09:01 INFO metabase.events :: Starting events listener: metabase.events.view-log 👂
09-28 14:09:01 INFO metabase.task :: Loading tasks namespace: metabase.task.follow-up-emails 📆
09-28 14:09:01 INFO metabase.task :: Loading tasks namespace: metabase.task.send-anonymous-stats 📆
09-28 14:09:01 INFO metabase.task :: Loading tasks namespace: metabase.task.send-pulses 📆
09-28 14:09:01 INFO metabase.task :: Loading tasks namespace: metabase.task.sync-databases 📆
09-28 14:09:01 INFO metabase.task :: Loading tasks namespace: metabase.task.upgrade-checks 📆
09-28 14:09:01 INFO metabase.core :: Looks like this is a new installation ... preparing setup wizard
09-28 14:09:01 INFO metabase.core :: Please use the following url to setup your Metabase installation:

http://localhost:3000/setup/

09-28 14:09:01 INFO metabase.core :: Metabase Initialization COMPLETE
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
	at io.aleph.dirigiste.Pool.updateStats(Pool.java:237)
	at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:320)
	at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
	at io.aleph.dirigiste.Pool$1.run(Pool.java:381)
	at java.lang.Thread.run(Thread.java:748)

Please Help me
Thank you.

**Comment by camsaul** [comment]
@esaiekuitche it looks like everything is working fine. Those error messages are just warnings and you can safely ignore them. As suggested you need to open http://localhost:3000/setup/ in your browser to start the setup process.

**Comment by esaiekuitche** [comment]
I tried, It did work. Just turn.

look this line in the log : 
09-28 14:08:57 INFO metabase.core :: Launching Embedded Jetty Webserver with config: {:port 3000}

I should have  {localhost:port 3000}  instead have  {:port 3000} right?

**Comment by camsaul** [comment]
Nope, `localhost` is implied since you can't really start a server on a different computer. `{:port 3000}` is a correct configuration.

**Comment by camsaul** [comment]
@esaiekuitche does that make sense?

**Comment by esaiekuitche** [comment]
I think that the problem is because the port 3000 is not remotely accessible.

**Comment by camsaul** [comment]
@esaiekuitche if you want to use Metabase with multiple users you probably don't want to be running on a personal computer anyway. Think about it -- if you turn the computer off no one would be able to access it. We recommend using something like AWS or even Heroku. Check out our installation instructions [here](http://www.metabase.com/docs/latest/operations-guide/start.html#installing-and-running-metabase). 

At any rate, you can change the port Metabase runs on by setting the env var `MB_JETTY_PORT`.

**Comment by camsaul** [comment]
@esaiekuitche it sounds like your question was answered, so I'm going to go ahead and close this out. Feel free to reopen if you have any more questions
