### ISSUE TITLE
Can't connect to Crate DB after updating to v0.26.1 from v0.25.2

### ISSUE THREAD

**Issue by rubenmch** [metabase/metabase#6069]
Browser: Chrome 61
Database: Crate
Metabase: 0.26.1
Metabase hosting environment: Docker
Metabase internal database: MySQL

I had working dashboards and questions using a Crate database in Metabase 0.25.2. 

After updating to 0.26.1 the dashboards stopped working with the error message:
```
Connections could not be acquired from the underlying database!
```
If I try to add the database again I get the following error:
```
No suitable driver found for jdbc:crate
```

I stopped the 0.26.1 container and restarted the 0.25.2 container and everything works again.

**Comment by salsakran** [comment]
What version of crate are you using?

**Comment by rubenmch** [comment]
Crate version 2.1.6

**Comment by salsakran** [comment]
@mikethebeer do you have any ideas?

**Comment by mikethebeer** [comment]
@salsakran @rubenmch It could be the case that you need to adapt the connectionstring (host) with a trailing `/` in the database management panel of Metabase. This has changed with https://github.com/metabase/metabase/pull/5801

e.g. if you had a host entry like this `localhost:5432` it will be now `localhost:5432/`

**Comment by salsakran** [comment]
@mikethebeer It's really .... not cool to make breaking changes like this without informing anyone. I don't want to get all Linus about this, but you really should be a little more careful in breaking end users environments. 

Were trailing slashes a valid format before? Or is everyone going to have to change their connection strings?

**Comment by mikethebeer** [comment]
@salsakran I'm sorry that I didn't highlight this in the PR I made. However, I would also be happy to get some feedback on the PR if the code change seems strange for you or if you have concerns with merging it immediately. Anyway, I will try to be more cautios in future here 👍

The trailing slash has been always valid format, so users who have it in before should not get affected. The main reason why we added it is because of consistency and also the fact that jdbc properties can get appended after the `/`.

**Comment by rubenmch** [comment]
@mikethebeer @salsakran adding the trailing slash solved my issue.

**Comment by camsaul** [comment]
It sounds like adding the trailing slash fixed the issue. @salsakran can we close this?

**Comment by camsaul** [comment]
> adding the trailing slash solved my issue.

Going to go ahead and close this out since we figured out how to fix it
