### ISSUE TITLE
Enable the ability to switch from gui to sql after running a question

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#607]
once you start down building a card and run it, there's no way to change to sql without starting over. This is most problematic if you just need to do something more advanced on a card and it's already properly placed on a dash. Makes more sense to be able to write sql for the same card.

**Comment by jgvandehey** [comment]
+1

**Comment by AdamLandis** [comment]
+1

**Comment by tlrobinson** [comment]
Bonus points: it would be pretty neat if when switching from GUI to SQL mode we could pre-populate the SQL editor with the SQL that would be generated by the GUI question. That said, I know the SQL queries we generate can be pretty verbose, so I'm not sure we want to show the user (even power users) "how the sausage is made", so to speak.

**Comment by salsakran** [comment]
@tlrobinson +100

**Comment by camsaul** [comment]
Most of the time the SQL we generate is parameterized, e.g. something like

```sql
SELECT *
FROM "my.table"
WHERE "my.table.field" = ?
```

So it's not like you can run the SQL we generate anyway :scream_cat:

**Comment by salsakran** [comment]
well, presumably, we could take the parameterized sql and insert the parameters in place of the `?`. Maybe we could find a javascript model on npm that could deal with that sort of craziness

**Comment by tmyoon** [comment]
+1

**Comment by rossgeesman** [comment]
+1

**Comment by salsakran** [comment]
This has no UX features, so aside from the difficulty of replacing parameterized SQL with the values (via string interpolation), this is ready to be worked on.

**Comment by agilliland** [comment]
I think there are still some real UX implications with this one.  The most obvious of which is where to put the toggle between SQL and GUI mode when it would need to be on the screen at all times.  Currently it only needs to be there briefly on a new question and takes the place of several other buttons which aren't relevant on a new question.  Or maybe there is a different UI mechanic for making this transition after a GUI card is formed?

We'll also want to be very clear about the UX around what happens after you do this and are looking at the SQL view, such as if there is any way to get back to GUI mode, etc.

**Comment by salsakran** [comment]
This issue is limited to just the movement from GUI -> SQL and is a one-way transition. 

In my mind, the toggle would remain on the GUI query builder. @kdoh + @mazameli, could we take a look at this?

**Comment by that0n3guy** [comment]
+1

**Comment by gincor** [comment]
+1

**Comment by mazameli** [comment]
Here's a prototype with a proposal for where to put the toggle and how this will all work. Once the prototype loads, click on the flashing blue dot to start the tour:

https://invis.io/WK77GMQM8#/156383432_New_Question

@kdoh @salsakran: let me know if you have any final thoughts.

**Comment by salsakran** [comment]
I think it works. I would want to revisit the icon placement and reduce the number of different kinds of icons as we get into working on QB3 =)
