### ISSUE TITLE
100% CPU Usage - Deadlock ?

### ISSUE THREAD

**Issue by ghost** [metabase/metabase#6071]
Hi everyone,

For a few weeks, we are experiencing huge performance difficulties on Metabase. Our CPU goes up to 100% several times a day and does not want to go down. We are then forced to kill the Metabase process.

We can not clearly identify the problem (or the queries), the logs are not very explicit. We think this happens when we run a query returning serveral hundred thousand lines on Redshift and / or MariaDB (MySQL). The same queries run very well on our databases.

Here some details:

- Your browser and the version: Chrome 61.0.3163.100 64 bits
- Your operating system: Windows 10
- Your databases: MySQL / Redshift (problems happen on both)
- Metabase version: 26.1 (also occurred on earlier versions)
- Metabase hosting environment: EC2 Server on AWS
- Metabase internal database: MySQL

Our EC2 Server:

vCPU : 8
RAM : 32Go
Intel Xeon E5-2676v3
Hz: 2,4 
SSD

Our logs:

1) our CPU Usage:
![image](https://user-images.githubusercontent.com/32383534/31005019-37ee1cf6-a4f7-11e7-88f2-b1c0a02df16d.png)

2) Metabase log at 8PM:

Sep 28 17:59:59 INFO metabase.sync.analyze :: [***************···································] 😕 30% Analyzed Table 98 'TABLE_NAME_1'
Sep 28 21:27:11 DEBUG metabase.sync.analyze.table-row-count :: Set table row count for Table 99 'TABLE_NAME_2' to 126874363
Sep 28 22:44:08 INFO metabase.sync.analyze :: [***************···································] 😕 31% Analyzed Table 99 'TABLE_NAME_2'
Sep 28 22:44:09 ERROR metabase.driver.generic-sql.query-processor :: nil

Best regards,

**Comment by salsakran** [comment]
This is our analysis process, it might be doing something silly. 

Worst case, you can turn off that analysis, and manually update fields that change while we get to the bottom of things. Would you be wiling to do a screenshare so we can get to the bottom of what's causing the issue?

**Comment by incaff** [comment]
Thank you for your quick reply!

I'm not sure I understand what you want. When the problem occurs, Metabase stops responding and we can not access the UI.

How to better identify the source of the problem?

**Comment by senior** [comment]
Something useful (in addition to setting up a screenshare like @salsakran suggests) is to get a stackdump of the process when it's spiked at 100% CPU. It's important that this be run while the instance is in that 100% CPU hung state. 

To do this, you need to be on the server that Metabase is hosted on and you need to know what the Process ID (PID) is of the Metabase instance. The easiest way to do this is using the `jps` command, which is included in the JDK and lists the running JDK process ids. You should see a "metabase" process in that output. Next run the `jstack <PID>` where PID is the Process ID of the metabase instance you found when you ran `jps`.

It might be easiest to redirect that output to a file (i.e. `jstack PID > my-stack-dump.txt`) and attach that file to a gist. The stack dump will tell us what code each thread is executing at that exact moment.

Not sure if it would help debug what's going on here or not, but the log output above seems to affected by https://github.com/metabase/metabase/issues/5761 as well.

**Comment by senior** [comment]
The stacktrace is interesting. From what I can tell, there is only one database connection open and that is to MySQL. I'd need to dig in deeper to be sure, but what I think I'm seeing is 1 connection open and database being returned and an attempt to open a second connection that is somehow blocked.

Is it possible that the MySQL instance, or the user connecting to the MySQL instance is somehow limited to only 1 open connection? What should happen is our connection pool should dynamically increase the number of open connections until it reaches it's max, which is 15.

You mentioned a MySQL query that returns a lot of results. Is this a query that you're exporting to CSV? How many results?

**Comment by senior** [comment]
@incaff bump

**Comment by pridnt** [comment]
Hi, guys!

We observed that CPU's consume is higher (100%) when someone make an export, independently of the file format used.

**Comment by akua73** [comment]
hello , any solution to this problem? we also experienced a high cpu usage (not on the metabase server but on one postgresql dababase we use as data source... )
thanks!

**Comment by dannyeuu** [comment]
@senior Is someone looking for this issue?

**Comment by abronte** [comment]
I see the same issue on 0.29.3.

Other details:
* syncing configured for 6am daily
* scanning for filter values set to manual 
* x-rays disabled
* metabase CPU pegged at 100% seems to happen randomly
* Presto/hive and postgres backends configured. Don't see CPU issues with them

**Comment by efron** [comment]
I see the same issue on  0.29.2

**Comment by sbelak** [comment]
We belive this got fixed in 0.30.2 via #8428

**Comment by mbvictoria** [comment]
Closing - no new reports since 0.30.2
