### ISSUE TITLE
Dashboard date range values do not map to variables for SQL questions?

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#6076]
This is in-between a feature request and a bug.

In Metabase v0.26, if I make an SQL question with date field variable(s), my expectation is that it will be possible to place it in a dashboard that has a date (or date range) filter defined, and map that filter to the variable(s) [2 distinct variables if there is a start and end date] .

This does not seem to work currently. Am I missing something?
Apologies if this is a dupe!

**Comment by salsakran** [comment]
You should be using a field filter 
eg 
```
SELECT count(*)
FROM table
[[where {{fieldLabel}}]] 
```and map

**Comment by sherbondy** [comment]
Sorry! Totally missed that detail somehow. Have now thoroughly read: http://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html

Seems reasonable, just quite nuanced, tricky to get right on the first go.

Thank you, and my apologies for the issues spam!

Feel free to close unless you want to keep open for the sake of reevaluating the interface/nomenclature around variables, filters, and parameters.

**Comment by stefolog** [comment]
Hi, 

I'm facing a similar problem but with a bit more complex WHERE clause which doesn't let me use the field filter. Here's the actual query:
```
SELECT os_type, count(*) as devices_count
FROM devices 
WHERE {{period_start}} <= created_at
  AND (deleted_at IS NULL OR deleted_at >= {{period_end}})
GROUP BY os_type;
```
Is there a way to do this or I have to pass two dates?
Thanks

**Comment by flamber** [comment]
@stefolog You cannot use Field Filter for that query, you would have to use two simple Date filters.

**Comment by stefolog** [comment]
@flamber Got it. Thank your fast reply.

**Comment by flamber** [comment]
Closing in favor of #4509/#3156
