### ISSUE TITLE
Feature request: Grouping dashboards

### ISSUE THREAD

**Issue by ThanhWilliamLe** [metabase/metabase#6081]
It would be nice to be able to group dashboards as right now I am having over 15 dashboards and they are about to grow into many many more. And I don't want to filter every time I want to find a dashboard

Some simple way to split the groupings of dashboards instead of having them staying next to each other would be nice.

**This is what I'm having in mind**
<img src="https://i.imgur.com/Ah25I3R.png">

**Comment by jornh** [comment]
Same title/related request in #6509.

Even though this request was raised first I think #6509 is the one to keep as it has more votes and more discussion including current thinking from the Metabase core team in https://github.com/metabase/metabase/issues/6509#issuecomment-348558947

**Comment by ThanhWilliamLe** [comment]
Sure thing!

**Comment by mbvictoria** [comment]
Closing - resolved with Collections.
