### ISSUE TITLE
Dashboard filter for BigQuery as string instead of number

### ISSUE THREAD

**Issue by gamars** [metabase/metabase#6082]
Somewhat a duplicate/regression of [#2854](https://github.com/metabase/metabase/issues/2854). When using a BigQuery based question all filters work fine. When adding the question to a dashboard we get the following error: 

`09-29 17:55:18 WARN metabase.query-processor :: Query failure: Argument type mismatch in function EQUAL: 'cid' is type int64, '20348' is type string`

- Your browser and the version: **Chrome 61.0**
- Your operating system: **OS X**
- Your databases: **BigQuery**
- Metabase version: **0.26.1**
- Metabase hosting environment: **Docker**
- Metabase internal database: **H2**

**Comment by flamber** [comment]
This was likely fixed by #12012 in 0.35.0. Please comment with more details if this is still happening.
