### ISSUE TITLE
OpenJDK 64-Bit Server VM warning -> MaxPermSize

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6087]
```bash
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
```
Can I remove this attr from `project.clj` and `frontend/test/__runner__/backend.js` ?

**Comment by salsakran** [comment]
It's there for a reason -- to support java 7.

See https://github.com/metabase/metabase/pull/5298

When we drop support for Java 7, we'll remove it.

**Comment by jonatasfreitasv** [comment]
Ok! Thx a lot!
