### ISSUE TITLE
Unable to download CSV/Excel/JSON when using Mongo

### ISSUE THREAD

**Issue by tusharmakkar08** [metabase/metabase#6089]
### Bugs: 

- Metabase version: 0.24.2
- Metabase hosting environment: Elastic Beanstalk using Docker
- Metabase internal database: MySql

Whenever the size of CSV > 16MB in Mongo Collections we are unable to download it. For other databases like MySQL and PostgreSQL we are able to download it. 

AFAIR, I have seen the similar error while inserting document with size greater than 16 MB. Please have a look [here](https://docs.mongodb.com/manual/reference/limits/#bson-documents). Since CSV conversion shouldn't require to use mongo document/collection insertion, I think this problem is solvable. 

PFA the image. It would be great if you can help in resolving it or guide me on how to resolve it.

Thanks. 
![screen shot 2017-10-03 at 1 32 16 pm](https://user-images.githubusercontent.com/2357025/31115599-9ce4f91c-a840-11e7-91f4-32b49b451809.png)

**Comment by jonatasfreitasv** [comment]
@tusharmakkar08 When you use MongoDB aggregation framework, a pipeline (https://docs.mongodb.com/manual/aggregation/) is executed, in Metabase It's no different.

Your pipeline is greater then 16MB.

For resolve this, try to execute query in Metabase Query Builder, use MongoDB $project to remove unnecessary fields and reduce your data length.
