### ISSUE TITLE
CSV Uploads

### ISSUE THREAD

**Issue by Bryze** [metabase/metabase#6094]
Spending some time in metabase, I couldn't find an option to create visualizations based on csv's.
I apologise if the option is present ( in that case, please guide me on where to find it )

If not, it would be lovely to have this as a feature

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by salsakran** [comment]
related to #1704

**Comment by hagen** [comment]
Perhaps another option @salsakran (having read #1704) is to connect to Google Sheets/ Microsoft Graph API to pull and query spreadsheet data? This alleviates the need to store csvs, either in H2 or a wroteable database. It’s also easy to upload csvs to these platforms.

**Comment by arita37** [comment]
We need static load from local folder when we cannot access external datasource....

**Comment by aadrian** [comment]
@Bryze would https://github.com/metabase/metabase/pull/7534 fulfill this?

**Comment by Bryze** [comment]
@aadrian  yes this does it. Also, I was wondering what sort of options can this support. I mean, it would be less than the sql query thingy but still I'll expect basic aggregations.

PS: While this may be out of context, but just reminded me of apache spark. It also provides various ways of transforming data fetched from a csv. (Incase, anyone needs ideas)

**Comment by aadrian** [comment]
@Bryze Query should be the same as with any Relational (SQL) DB, since AFAIK one would see each CSV file as a H2 table.

**Comment by Bryze** [comment]
@aadrian Yes, in that case we are to assume that the output table from querying the db will be equal to the table in the input file provided as csv

**Comment by vvaezian** [comment]
One fairly easy workaround is to first convert the CSV file to SQLite, and then import it to Metabase as SQLite db.

Code in Python (based on [this](https://stackoverflow.com/a/2888042/2445273) answer):

````Python
import csv, sqlite3

con = sqlite3.connect("C:\\Users\\John\\testdb.db") # first create an empty file to save the db
cur = con.cursor()
cur.execute("CREATE TABLE t ('Col1' text, 'Col2' text);")

with open('C:\\Users\\John\\test.csv','rb') as csvFile:
    # csv.DictReader uses first line in file for column headings by default
    dr = csv.DictReader(csvFile) # comma is the default delimiter
    to_db = [(i['Col1'], i['Col2']) for i in dr]

cur.executemany("INSERT INTO t ('Col1','Col2') VALUES (?, ?);", to_db)
con.commit()
con.close()
````

**Comment by MrSaints** [comment]
Similar to the previous response, you can load CSV data into Postgresql fairly easily with https://github.com/lukasmartinelli/pgfutter.

**Comment by philshem** [comment]
> Code in Python (based on [this](https://stackoverflow.com/a/2888042/2445273) answer):


this works fine but you have to define your data model. Check out this script for automatic csv-to-sqlite3 conversion:

https://github.com/rufuspollock/csv2sqlite

```
usage: csv2sqlite.py [-h] [--headers [HEADERS]] [--types [TYPES]]
                     [--bz2 | --gzip]
                     csv_file sqlite_db_file [table_name]
```

**Comment by philshem** [comment]
> Similar to the previous response, you can load CSV data into Postgresql fairly easily with https://github.com/lukasmartinelli/pgfutter.

This works fine, but then you need to have a PG instance running. The strength of sqlite is that it is a file. Check out this comment, which has a robust csv-to-sqlite conversion.

https://github.com/metabase/metabase/issues/6094#issuecomment-575161523

**Comment by ctmay4** [comment]
Unfortunately the CSV driver referenced in the [Community drivers page](https://www.metabase.com/docs/latest/developers-guide-drivers.html) no longer works with versions 34+.  

https://github.com/Markenson/csv-metabase-driver

Any thought of adding a working version to the base package of plugins?
