### ISSUE TITLE
Show actual SQL statement run

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#6096]
I need to debug queries run by metabase but I can't find a way in metabase to see what the actual SQL statement that it ran. I am writing a manual sql query in metabase with variables and I'm pretty sure metabase does some timestamp manipulation so I really want to see what the query looks like after all that.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by joebordes** [comment]
Doesn't the "View SQL" button show you this?

![metabaseviewsql](https://user-images.githubusercontent.com/1237191/31199082-96d53642-a956-11e7-9b16-3f5c1c8b7b13.png)

**Comment by joebordes** [comment]
BTW, I think this would be better asked on the discussion forum.

**Comment by nickcarenza** [comment]
I wrote the query using raw sql with variables not using the query builder. This is a feature request.

**Comment by joebordes** [comment]
Ah, sorry. Now I understand your request.

**Comment by bcbob** [comment]
This will be very handy for debugging native sql queries. Great proposal 👍🏼👍🏼

**Comment by stringbeans** [comment]
definitely! ive found the documentation for "field filters" variables is very lacking and doesnt provide good examples... being able to see the generated query for native queries would be VERY useful!

**Comment by nbrustein** [comment]
Also very useful if you're using snippets.

**Comment by incompletude** [comment]
I top this. Sometimes I can't understand why my query is failing, and seeing the actual query being run would help debugging.

**Comment by matotias** [comment]
This is also very important to us

**Comment by brunobergher** [comment]
Will be closed by #26837 when we release 46.
