### ISSUE TITLE
SQL x-ray action doesn't work as expected

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6097]
I've mentioned this a few times in slack, but I think it keeps getting overlooked. This is on our stats instance on Chrome:

**If I use the x-ray action on this saved SQL timeseries…**

![sql-time-series](https://user-images.githubusercontent.com/2223916/31196050-35b6f346-a901-11e7-9f93-e7f50f9122ef.png)

**…I'm shown the table view of my chart:**

![sql-timeseries-xray-result](https://user-images.githubusercontent.com/2223916/31196130-7c15f5da-a901-11e7-984d-9bc65c536160.png)

**I'm also given the option to x-ray SQL questions with scalar results:**

![screen shot 2017-10-04 at 12 39 44 pm](https://user-images.githubusercontent.com/2223916/31196052-39584568-a901-11e7-97f3-64bf9280552a.png)

**Clicking on that also shows me the "raw data" for my sql question's result:**

![screen shot 2017-10-04 at 12 43 12 pm](https://user-images.githubusercontent.com/2223916/31196185-a5be9f54-a901-11e7-8c38-63de67825d4e.png)

It's unclear to me what the intended behavior is supposed to be here, but the current behavior is clearly broken. Also, we're no longer showing the "View this as a table" action, which we used to do for SQL, as I recall.

**Comment by attekei** [comment]
@mazameli `Analyze the results of this Query` is not an x-ray action, it's the "create a new question based on this question" action. `X-ray this question` action isn't currently shown for native query questions – only for GUI timeseries questions. 

> Also, we're no longer showing the "View this as a table" action, which we used to do for SQL, as I recall.
This can be easily changed if we want so (as far as I know, the current behavior hasn't been changed lately)

**Comment by sbelak** [comment]
Now that we have insights and all, we could try enabling xrays for native queries as well.

**Comment by attekei** [comment]
@sbelak I think I encountered some errors when trying to xray one native query question although I think that those are just frontend problems. The API response seems to be fine

**Comment by salsakran** [comment]
@mazameli do you have a better idea for copy to start a nested query with the results of a sql query? 
Closing this as not being accurate...

**Comment by mazameli** [comment]
@salsakran here's where I'm confused:
- Did we or did we not intend for time series questions backed by native queries to be x-ray-able yet? If not, then I agree this issue should be closed.
- If @attekei is right about what that action is supposed to be doing, isn't there also supposed to be an additional action to view the current chart's data? I.e., `view this as a table`

As for better copy for a nested query action, first of all I don't think it makes sense to display that action in the state depicted in my screenshot — the user in this situation is looking at a chart, not a table. I get that the query result is the same whether it's being shown as a chart or a table, but it sounds weird to me to show that action while looking at anything other than a table. Also, are we showing this for unsaved questions? In any case, the action text could be `Ask a new question about this data`.
