### ISSUE TITLE
Database tables aren't listed when building a question, without first going to Data Reference

### ISSUE THREAD

**Issue by hagen** [metabase/metabase#6105]
- Your browser and the version: Chrome Version 61.0.3163.100
- Your operating system: Win 10
- Your databases: AWS Aurora (MySQL)
- Metabase version: v0.25.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
Log in
Go to New Question
Only relevant API call made is this one:
http://domain.tld/api/database?include_tables=true&include_cards=true (which returns databases)
Data > Select a table
Pick database
No tables listed
![image](https://user-images.githubusercontent.com/5161952/31257767-4df70bc2-aa86-11e7-854d-d919eb5b4413.png)

Go to Data Reference
Now database metadata API calls a triggered for all databases I have access to.
http://domain.tld/api/database/{id}/metadata (x3)
See all tables
Pick database
Select 'Tables in <Database name>'
Tables are listed.

Back to New Question
Data > Select a table
Pick database
Tables are now listed
![image](https://user-images.githubusercontent.com/5161952/31257807-86971760-aa86-11e7-9fa1-2afcc946885e.png)

Seems to me the metadata call should be triggered at New Question for all databases, but nothing is happening there.

**Comment by hagen** [comment]
Additionally, this could just be an API issue, as this URL:
_http://domain.tld/api/database?include_tables=true_
does not return tables in the database.

**Comment by hagen** [comment]
Close this. My fault.
Lots of things go wrong when you put Metabase behind AWS CloudFront. Note to self - don't do that again.

**Comment by mrdeds** [comment]
How did you solved this?

**Comment by hagen** [comment]
I had Metabase behind a CDN. The CDN was caching an API response that had no tables in it. As soon as a moved it from behind the CDN, all API queries showed correct response.
