### ISSUE TITLE
Running demo

### ISSUE THREAD

**Issue by guilhermecgs** [metabase/metabase#6107]
Hi Folks,

Is there a running demo where I can see all the functionalities working together?

**Comment by kdoh** [comment]
Hi @guilhermecgs. We don't currently have a running online demo up anywhere, but we've worked pretty hard to make it easy to get Metabase set quickly if you want to give it a spin. I'd recommend either the Mac app or spinning up a quick Heroku instance if you're interested in seeing how things work. Both are available over at https://metabase.com/start

**Comment by FireEmerald** [comment]
Although this issue is quite old, in my opinion it's wrong to say _"it's easy to set it up, do it on your own"_. In fact it is easy to copy+paste the docker command but without any database attached with relevant data it's useless. And after that you have to create your dashboards pp. pp... time wasting.

If you really want to show a new user what your software is able to deliver, the best way is a **working demo**. 😉

**Comment by davidbonachera** [comment]
Was looking for a demo to showcase it to someone quickly, but couldn't find one. It could be a good use case but requires some maintenance/update.

**Comment by flamber** [comment]
It is possible to use the free trial of Metabase Cloud: https://www.metabase.com/start/hosted/

**Comment by davidbonachera** [comment]
> It is possible to use the free trial of Metabase Cloud: https://www.metabase.com/start/hosted/

Quite extreme to add the payment method just for that no?

**Comment by flamber** [comment]
@davidbonachera Without a credit card, then it would be way too easy to abuse. It's not free to run servers. And this will give you your own private demo instance.
But if you're just looking to show something to a colleague, then downloading (Docker, JAR, Mac App) the free version should get you up and running on your local computer within minutes.
There's a lot of showcase material on our blog, which shows the individual functionality: https://www.metabase.com/blog/

**Comment by set92** [comment]
@flamber I was trying to use your idea to have a demo environment, but there isn't a demo database to load some data to have a real demo no? So, I would need to start fighting to add some database and see if I can make it work properly for a demo.

**Comment by flamber** [comment]
@set92 Metabase comes with a Sample Dataset, which is used for most parts of the docs and learn articles:
https://www.metabase.com/docs/latest/ - https://www.metabase.com/learn/
But the entire point is that you should load Metabase with your data.

The amount of data you have mostly does not concern Metabase - that is up to your database to handle that.

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
