### ISSUE TITLE
ability to send emails to all users of the system

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#611]
e.g. notices about things that happened, upgrades, etc.

**Comment by camsaul** [comment]
@metabase/core-developers is this still something we want? This is officially our oldest open issue at this point and nobody has ever asked for it

**Comment by kdoh** [comment]
I'm 👍 for closing this.

**Comment by moumny** [comment]
We extract the emails from the DB and send emails. This is OK for us.

**Comment by camsaul** [comment]
Cool, I'm going to go ahead and close this as No Longer Relevant. We can always revisit this if someone wants it in the future
