### ISSUE TITLE
Presto tests should be refactored to use a single catalog

### ISSUE THREAD

**Issue by senior** [metabase/metabase#6111]
Currently when we define a new dataset in our test code, that dataset needs to be followed up with a PR [here](https://github.com/wwwiiilll/presto-mb-ci/tree/master/etc/catalog) and a subsequent update to the docker container. Looking at the Presto docs, it seems like we could just swap our usage of catalogs for schemas and we'd get the same level of isolation in our tests and also gain the ability to define new datasets via code.

**Comment by senior** [comment]
@wwwiiilll have any opinions on this issue? Seems like from a maintenance perspective this would be an improvement over what we have now.

**Comment by wwwiiilll** [comment]
Moving everything all to a single catalog would definitely make things easier to manage Presto-wise.

An other option would be to generate the list of catalogs with the startup script in the container, an ENV var could be passed to tell Presto which names are needed.

Mounting a folder with the files from somewhere in this repo is also an idea (assuming CircleCI allows it).

**Comment by flamber** [comment]
Closing, since the new Presto driver in 0.41 was a complete re-write of everything.
