### ISSUE TITLE
Admin Panel/DataModel - console error "Uncaught (in promise) field with ID does not exist: 56"

### ISSUE THREAD

**Issue by friulchingo** [metabase/metabase#6112]
Hi,

I broke Metabase. Please, help me.

When going to Admin Panel -> Data Model and selecting a specific database and a specific table (all the other tables and databases connected to metabase don't have this problem), I can't perform any operation due to "Uncaught (in promise) field with ID does not exist: 56" as shown in the Browser's console.

Here's a video in .gif format showing what's going on: https://d.pr/i/QOdG6x

Actions performed that might have created the problem:
- I made changes to the data model while I was asking a question. ... ... ...I know.

Actions taken to fix it without success: 
1. re-scanned field values for database
2. synced database
3. dropped and recreated all the database's tables (every 24 hrs)
4. discarded cached field values
5. re-scanned the table
6. updated metabase from 0.25.x to 0.26.1
7. I have added the same database again and in there the data model has no problem at all, it works as it should. However, there I have neither data model, questions and dashboards stored. So it's not really a fix.

More info:
- Your browser and the version: Version 61.0.3163.100 (Official Build) (64-bit)
- Your operating system: - macOS Sierra 10.12.6  
- Your databases: Aurora MySQL 5.6.10a
- Metabase version: v0.26.1
- Metabase hosting environment: AWS Beanstalk
- Metabase internal database: MySQL

Let me know what else I can do to help you help me :)

Cheers

BONUS: here's an artwork that just appeared when I tried to replicate the problem again
![screenshot 2017-10-06 16 28 50](https://user-images.githubusercontent.com/26676966/31282676-975f81a4-aab3-11e7-8f7e-e87e26857579.png)

**Comment by stepan-romankov** [comment]
I also have the same issue after update to 0.26.1

**Comment by friulchingo** [comment]
I am guessing it might something related with custom metrics too. The only table's question not working is the only one viewing a custom metric. It looks like I neither can deselect it nor visualise its formula.

I am starting being hopeless and probably I'll spend a wknd replicating all visualisation from scratch in a newly imported database. 

@stepan-romankov what's your experience?

**Comment by attekei** [comment]
Hey @friulchingo, @stepan-romankov or @MaicolPiani, are you still experiencing the issue? 

Might be that your table schema has changed at some point and some custom segment/metric is still linked to a table column that doesn't exist anymore. And because our sync process apparently doesn't remove invalid segments/metrics, then bad things happen.

I could try a quick frontend fix on this (so that the data model page doesn't completely blow up) but I think the real solution is making our sync process go through segments/metrics and make sure that there are not invalid field references.

**Comment by stepan-romankov** [comment]
Hi, @attekei 

You are right this happens when schema is changed. It would be nice if sync process will clean up queries from invalid fields, ideally with list of queries which where cleaned, so they can be reviewed.

**Comment by attekei** [comment]
Ping @camsaul on this

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4 - after column is removed and doing a sync, then Data Model still works.
And accessing the metric displays an empty field, which can be removed.
![image](https://user-images.githubusercontent.com/1447303/83503706-c641cb00-a4c3-11ea-9fbd-e3c1883cd9b3.png)
