### ISSUE TITLE
Why records returned while it is not between the provided date?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#6117]
My query condition is as below:
![screen shot 2017-10-07 at 6 42 48 pm](https://user-images.githubusercontent.com/6417083/31309206-5ad2725a-ab8f-11e7-897e-464e7d8230ec.png)

My timezone is set to `Asia/Tehran` and all dates are in `UTC`. Now there are records returned from `22nd of Aug.` while my date range is just for `23rd of Aug` (start and end is set to the same date just to limit my response I have problems in larger date ranges too):

![screen shot 2017-10-07 at 6 43 58 pm](https://user-images.githubusercontent.com/6417083/31309235-c752f878-ab8f-11e7-810a-6e687ff67841.png)

Why these data has been returned?
Even other date ranges return data from previous days.

**Comment by flamber** [comment]
I'm quite sure this was fixed in 0.34 - if not before. Please comment if you're still experiencing this.
