### ISSUE TITLE
Specify which columns to use in chart

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#612]
currently our charting code expects the columns to be in a specific order for the charting to be able to work properly, but that's silly and causes user confusion.  it should be possible to order the columns in the query either way and still be able to chart the data.

**Comment by agilliland** [comment]
Adding 1 vote for submitter of #1397

**Comment by agilliland** [comment]
Adding a vote for the submitter of #1419

**Comment by ttotev** [comment]
Hi @agilliland, being able to pick columns and changing their order in the Table Visualization was the first question my users raised. Are there plans for adding this functionality?

**Comment by salsakran** [comment]
@ttotev we're looking at ways to introduce it to the query builder. Definitely something we'll be adding, not sure on exactly which version however.

**Comment by MrMauricioLeite** [comment]
+1

**Comment by anavuk** [comment]
+1 for column order in table visualization. Would like to select default order (not alphabetical, which it is now)

**Comment by mazameli** [comment]
Link to the design prototype below. Access the table options by clicking the gear in the top-left next to the visualization menu. You can also toggle to other visualization types and their respective options by using the visualization menu in the top-left.

https://projects.invisionapp.com/share/WP7X4NXDY#/screens/173083662

**Comment by MrMauricioLeite** [comment]
Wow, great design as always!!

Congrats Maz Amelli.

I'm looking ahead to see this out.

[]'s,

Mauricio R. Leite
(11) 9 4141  2201

2016-07-18 13:44 GMT-03:00 Maz Ameli <notifications@github.com>:

**Comment by Idanwo** [comment]
looks and feels just great!

**Comment by tongnk** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by camsaul** [comment]
Wait a minute. @tongnk we implemented this over a year ago

**Comment by jefffriesen** [comment]
I keep trying to see these invision mockups posted but they are archived. It would be nice to post the invision link and a screenshot

**Comment by mazameli** [comment]
@jefffriesen any reason you're trying to see the mockups? This was a feature that was implemented a long time ago, back in 2016, so you should be able to see it live in Metabase itself. :)

**Comment by jefffriesen** [comment]
Yes, this was the second time I saw a dead link and wasn't sure what a ticket was referring to. As an outsider, it's hard to know from just word description what tickets relate to what parts of the app. Not a big deal. Thanks for Metabase!
