### ISSUE TITLE
Export from unsaved queries is not working

### ISSUE THREAD

**Issue by jescorotero** [metabase/metabase#6125]
Hi
When we try to export from "saved" queries, we have not issues, but when trying to export from "unsaved" queries, it doesn't export and an error is shown.

For example, we have some saved queries  working as datasource.  Then using navigation we use "Analyze the results of this query"" and we do some filters and groupings.  The result is right and we would like to export but we don't need to save the new query first.  Then the export goes to an error page.

The problem seems to be the inability to export without first saving the new query, but this is so frequent using "Analyze the results of this query" feature and make sense to export unsaved queries.

You have a screen capture here:
https://share.vidyard.com/watch/q5iKBVt8ASVzVY5HrbwSvr

**Comment by attekei** [comment]
Currently the query builder simply fails to generate a proper url for downloading the data if the data source is a saved question. If the data source is a normal question, everything works normally. I'll take a look at this.

**Comment by attekei** [comment]
Actually this is a backend issue rather than frontend, the backend returns `404` for all downloads of unsaved questions which use saved questions as a data source. Ping @camsaul

**Comment by jescorotero** [comment]
This problem doesn't exist any longer after upgrade to v0.30.1

**Comment by cwu-argo** [comment]
We are using v0.30.1 and still seeing this issue. Same query cannot be downloaded when 'unsaved' but can do so after 'save'. Can we re-open this issue?

**Comment by nautilus28** [comment]
We are using v0.31.2 and still experiencing this issue.

**Comment by flamber** [comment]
Hi @cwu-argo and @nautilus28 
Metabase version 0.32.6 was released yesterday and I cannot reproduce this issue on that version.
