### ISSUE TITLE
Data export/download fails for size greater than 16MB in MongoDB

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#6134]
- Your databases: MongoDB
- Metabase version: 0.24.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*
Create large mongo collection (size > 16MB) and try to download csv/xlsx/json. Following error is thrown:

Command failed with error 16389: 'aggregation result exceeds maximum document size (16MB)' on server. The full response is { "ok" : 0.0, "errmsg" : "aggregation result exceeds maximum document size (16MB)", "code" : 16389 }

I don't think aggregate query should be needed for download.

**Comment by paoliniluis** [comment]
@ujjwal-gupta I believe that this is an issue in MongoDB https://www.mongodb.com/docs/manual/core/aggregation-pipeline-limits/

The aggregation comes from the actual query that we run in MongoDB, we need to run the query to then download it
