### ISSUE TITLE
mongodb - field containing JSON

### ISSUE THREAD

**Issue by oliviersaintgobain** [metabase/metabase#6135]
Hello,
we are working on a dashboard on a MongoDB database (v 3.4.7)
I'm using the last (docker today install) version of metabase.

My request is more an help to know how I can read a JSON field in one of my table.

Actually, I would like to run a query wich show the number of download by my clients.
I have 1 row by client (id of my table), and for each one, I have a field containing JSON (I have forced the 
type in metabase).
the download field value example :
[
-{
"fileDescriptor" : -{
"fileId" : 594b89c695fe1300016ede7c,
"contentType" : application/octet-stream,
"fileName" : Asembly_Celotex_PIRFoamBrd_FR5000.rvt,
"fileFormat" : RVT 2014,
"fileFormat2" : { \"$ref\" : \"format\", \"$id\" : \"RVT 2014 }
},
"alreadySentAnExpirationNotification" : false,
"downloadDate" : 2017-06-22T09:12:25.323Z,
"product" : { \"$ref\" : \"product\", \"$id\" : \"5940094095fe130001b19c77 }
},
-{
"fileDescriptor" : -{
"fileId" : 5924163895fe1300015a85d6,
"contentType" : application/octet-stream,
"fileName" : Tripla vetrata isolante per serramento - Saint-Gobain Glass.rfa,
"fileFormat" : RFA 2017,
"fileFormat2" : { \"$ref\" : \"format\", \"$id\" : \"RFA 2017 }
},
"alreadySentAnExpirationNotification" : false,
"downloadDate" : 2017-07-27T13:06:48.902Z,
"product" : { \"$ref\" : \"product\", \"$id\" : \"5915df7c95fe130001ecaca4 }
},
-{
"fileDescriptor" : -{
"fileId" : 5924163895fe1300015a85e1,
"contentType" : application/octet-stream,
"fileName" : Tripla vetrata isolante per serramento - Saint-Gobain Glass.txt,
"fileFormat" : TXT,
"fileFormat2" : { \"$ref\" : \"format\", \"$id\" : \"TXT }
},
"alreadySentAnExpirationNotification" : false,
"downloadDate" : 2017-07-27T13:06:49.271Z,
"product" : { \"$ref\" : \"product\", \"$id\" : \"5915df7c95fe130001ecaca4 }
}
]

My question : in Metabase, how to read this field and aggregate the number of "filedescriptor" ?

thanks

**Comment by salsakran** [comment]
This isn't really appropriate to the issue tracker.

You might get more help on our discussion forum - discourse.metabase.com
