### ISSUE TITLE
MySQL DB Migration issue

### ISSUE THREAD

**Issue by abhiCR7** [metabase/metabase#6148]
I'm running Metabase in developer mode.
Before deploying to production we are moving the data to MySQL.
Following exports were done:
`export MB_DB_TYPE=mysql`
`export MB_DB_DBNAME=metabase`
`export MB_DB_PORT=3306`
`export MB_DB_USER=root`
`export MB_DB_PASS=<password>`
`export MB_DB_HOST=localhost`
I ran the following command:
`java -jar target/uberjar/metabase.jar load-from-h2 <path to h2 file>`
It is throwing following error:
`Command failed with exception: Unknown column 'cache_field_values_schedule' in 'field list'`
Please find complete log [here](https://gist.github.com/abhiCR7/0b85a5fe48f6d4e62d58869f77150d68)

Any help in debugging this issue would be appreciated.

**Comment by salsakran** [comment]
What version are you on?

**Comment by abhiCR7** [comment]
Hi @salsakran the issue is resolved. It was version issue

**Comment by camsaul** [comment]
Closing since this was resolved

**Comment by bagajab** [comment]
> Hi @salsakran the issue is resolved. It was version issue

Is it metabase version or mysql version

**Comment by flamber** [comment]
@bagajab This issue is almost 3 years old. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
