### ISSUE TITLE
Grouped By and Filtered By Lists not showing all available fields

### ISSUE THREAD

**Issue by CherylEveritt** [metabase/metabase#6149]
I am designing a question using the metabase question builder (not using custom sql).

I would like to group by user_id, which is a string field in my underlying data table (BigQuery is the data source).

However, user_id is not showing in the list of fields available for Group By.  Nor is it showing in Filtered By.

In the data model, the field is set to be visible everywhere.  It is also set as a foreign key.

Is there any other reason all table fields would not be visible in these lists?

**Comment by gil0109** [comment]
I have the same issue. Using Foreign keys.

**Comment by salsakran** [comment]
what is the base type in the schema and what did we categorize it as in the data model section of the admin?

We try to only show relevant fields in those lists, but might be getting something subtly wrong.

**Comment by Shashwat986** [comment]
So, I think the issue only happens for foreign keys in general. They don't show up as fields in the query builder, and if I need to group by the foreign key itself, the generated SQL joins the table unnecessarily.

**Comment by mazameli** [comment]
I think we fixed this somewhere along the way. As you can see here I can select this foreign key to group by:

![image](https://user-images.githubusercontent.com/2223916/67526686-29d06400-f66a-11e9-8b75-3f574d044e57.png)]

Will reopen if this is still happening.
