### ISSUE TITLE
Field Filter dropdown is incomplete 

### ISSUE THREAD

**Issue by sergeiGKS** [metabase/metabase#6158]
I have a field filter on a table that has more than 40 rows. When adding a filter value, users see a dropdown with the first ~15 values that appear in the table. Is this the expected behaviour or is something wrong?

##I am using
- browser: Chrome Version 61.0.3163.100
- operating system:  Windows 7
- Database: Postgres,
- Metabase version: v0.24.2

**Comment by mazameli** [comment]
If you upgrade your metabase instance to the latest version (0.26.1) this issue should be fixed. We overhauled the way we do field values caching.
