### ISSUE TITLE
Weird capitalization of column names

### ISSUE THREAD

**Issue by joevandyk** [metabase/metabase#6160]
I'm using Metabase 0.26.0 on a postgresql 9.6 database.

http://take.ms/UYHY5 is the query I'm using.

I would expect the column name to be "Sku Vendor Name", not "Sk U Vendor Name".

**Comment by mazameli** [comment]
This is the infamous "Friendly field names" behavior, which is a setting you can turn off in the Admin Panel under the general settings tab. 

This wouldn't work in your specific case, since you're using an alias, but you can also manually correct table and field names in the Data Model section of the admin panel if you don't want to turn Friendly Field Names off entirely.

**Comment by joevandyk** [comment]
Right.. but I can't understand why "sku_vendor" would get turned to "Sk U Vendor" in the first place if the software is trying to be friendly. That sounds like an unfriendly field name behavior.

**Comment by joevandyk** [comment]
@mazameli is this something that could be fixed in the "Friendly Field Name" code?

**Comment by UnicycleJonathan** [comment]
Why was this closed? The "friendly names" behavior seems quite insane to me. A column label like "Entire US" gets turned into "Entire Us". A much more logical default would be not to apply "friendly" naming to a label that already clearly has its own capitalization or formatting. That is, if somebody uses "entireus" as a label, sure try to friendly-fy it. But if they clearly typed "Entire US" with selective capitalization and spacing, accept it as-is, it's not hard to infer.

**Comment by arjunbanker** [comment]
+1 @mazameli may want to consider re-opening this, i've definitely noticed / been frustrated by the strange casing logic that seems to run by default and add spaces at non-expected juncture points in the column name.

**Comment by flamber** [comment]
@arjunbanker There was just a big fix for making "humanization" better - it should be in 0.33 - #10174
