### ISSUE TITLE
Add "Custom List" as Variable type

### ISSUE THREAD

**Issue by jescorotero** [metabase/metabase#6165]
Hi
It would be interesting and very easy to implement having a new "Custom List" option for variable types.
Now we have "Text" and the user has to write keyword .  Then we have "Field Filter", that lets user choose between "all" field values.  But what if I don't wanna display "all" values but only certain ones.

For example, we have to build 2 Questions:  "calls by agent by department A" and "call by agent by department B"

The query based Question 1 uses now a "Field Filter" variable for "Search Agent"  filter.  The query is filtering by 10 agents only.  The Field Filter variable is showing us alll Agents from "CALL_AGENT" field.

Then it would be interesting define this "Search Agent" variable as "Custom List" when we can specify some values comma separated like:
`Anthony=1,Joseph=2,Carlos=9, Oscar=12, Susan=340, Kristin=365`

This option is used in Reportico: [http://www.reportico.org/documentation//4.5/doku.php?id=the_criteria_menu#list_values]

Second option could be a pre-sql variable:  the variable shows a list not from fiedl values, but from SQL resultset (only one column resultset).  In our example could be:

`SELECT CALL_OPERATOR
FROM T_CALL_OPERATORS
WHERE DEPARTMENT = 1`

Thanks

**Comment by gilhs** [comment]
In #5245 I suggested pretty much the same thing.

**Comment by flamber** [comment]
Closing in favor of #5245
