### ISSUE TITLE
No Time selection (day/month/etc...)  on nested queries in "groupby"

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#6166]
This is similar to https://github.com/metabase/metabase/issues/5938 but with dates.

- Your browser and the version: (Version 61.0.3163.100 (Official Build) (64-bit)
- Your operating system: Windows 10 pro
- Your databases: MySQL
- Metabase version: 0.26.1
- Metabase hosting environment: docker
- Metabase internal database: MySQL

### Repeatable steps to reproduce the issue
- create new question using a previous question as the data source (nested query).
- group by a date field
- there is no "month, day, week, year, etc..." selector next to the date field.

![image](https://user-images.githubusercontent.com/113870/31556076-0fa024de-b009-11e7-954d-2e6dc7b7fc7a.png)

### Expected behavior:
I expect something like this:
![image](https://user-images.githubusercontent.com/113870/31556132-48f51bea-b009-11e7-8e0e-323cee9504ee.png)

**Comment by sbelak** [comment]
Same for binning.

**Comment by attekei** [comment]
The `dimension_options` metadata is missing for virtual table fields and for that reason the granularity dropdown doesn't appear.

Do you think @senior that using something like current `assoc-field-dimension-options` for `card-result-metadata->virtual-fields` would be possible, at least for date fields (if not other binning types as well)?

**Comment by senior** [comment]
@attekei Taking a look at the code you reference, I agree, looks like it would b epretty easy. It's got the type information, it's just adding dimensions there like we're doing for non-nested questions
